### ISSUE TITLE
Log unsuccessful login attemps

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/FreshRSS#1015]
I wanted to do a fail2ban rule modeled on this one : http://www.sublimigeek.fr/fail2ban-securiser-instance-wallabag
But unsuccessful login attempts seem not to be registered on Apache logs, I only have : 

```
freshrss.example.org IP.xxx.xxx.xxx - - [25/Oct/2015:11:16:02 +0100] "GET /i/?c=javascript&a=nonce&user=hacker HTTP/1.1" 200 688 "http://freshrss.example.org/i/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36"
```

Is there something to change on my Apache conf, or is it something in FreshRSS?

**Comment by Alkarex** [comment]
Related to https://github.com/FreshRSS/FreshRSS/issues/1001

**Comment by Alkarex** [comment]
Please test https://github.com/FreshRSS/FreshRSS/pull/1016
You will now see an HTTP status 403 in the Web server logs.

**Comment by Alwaysin** [comment]
It works, thanks.

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/2903
