### ISSUE TITLE
Call for testing /dev before 1.2.0 and 1.3.0-beta

### ISSUE THREAD

**Issue by marienfressinaud** [FreshRSS/FreshRSS#1017]
It's time (yes I know, it was already time few weeks ago) to release new stable version 1.2.0 (and so, new 1.3.0-beta version).

The list of [tickets to close](https://github.com/FreshRSS/FreshRSS/milestones/1.1.4-beta) is a bit long but I saw @Alkarex is working hard today :).

I personally continue on https://github.com/FreshRSS/FreshRSS/issues/995 since I really want to start my new project. This next stable version is probably the last on which I'll work for some time.

**Comment by Alkarex** [comment]
:-) I suggest merging my 5 PR's (the list for 1.1.4-beta only contains things with limited impact) in /dev and shortly after merge /dev in /beta to release 1.1.4-beta, which can become 1.2.0-master.

I would have liked to investigate https://github.com/FreshRSS/FreshRSS/issues/999 before 1.2.0-master but I do not think there will be time...

**Comment by marienfressinaud** [comment]
Ok, I'll see your PR later. Also, I have to fix https://github.com/FreshRSS/FreshRSS/issues/935

**Comment by marienfressinaud** [comment]
`dev` branch is ready now. I'll release the next version tomorrow, I still have to write a small article for this new stable version.

**Comment by Alkarex** [comment]
:+1: 
Don't you want to release 1.1.4-beta first, and then 1.2.0-master?

**Comment by marienfressinaud** [comment]
We always released both beta and stable versions at the same time. I don't know if it's a good idea but it's the purpose of 1.2.1 to fix potential annoying bugs. Also note there is no 1.1.4-beta but a 1.3.0-beta (new stable = new major number for beta)

**Comment by marienfressinaud** [comment]
I don't have time to wait for #1028 so I release 1.2.0 and 1.3.0-beta without it.

**Comment by Alkarex** [comment]
Sure @marienfressinaud , it is because in the milestones, I had 1.1.4-beta < 1.2.0-master < 1.3.0-beta. I will rename the 1.3.0-beta milestone.
Edit: Ah, I can see you have created 1.3.1-beta. Very good.

**Comment by marienfressinaud** [comment]
Already done ;)

**Comment by dadall** [comment]
Oh, time to update ? :)

**Comment by marienfressinaud** [comment]
Wait a bit, auto-update is not yet configured ;)

**Comment by marienfressinaud** [comment]
auto-update is working :+1:

**Comment by dadall** [comment]
Update done. No problems, yet ;-)

Thanks guys !

**Comment by aledeg** [comment]
I don't know if it's just me, but the share.php file seems to be left at an older version. Is this file in the process of deployment?

**Comment by marienfressinaud** [comment]
Nop: just fixed https://github.com/FreshRSS/update.freshrss.org/commit/9761239ec1cd1a225f54c70d48b72ac3fc335015

**Comment by aledeg** [comment]
Thanks

**Comment by marienfressinaud** [comment]
Thanks to you, I totally forget about this file!

Also, if you already did the update, you can copy/paste [the `shares.php` file](https://raw.githubusercontent.com/FreshRSS/FreshRSS/beta/data/shares.php) into `./data`

**Comment by aledeg** [comment]
I did the update, but I don't need the shares.php update. So I'll wait until the next update to get this file.
