### ISSUE TITLE
Number of items in public rss

### ISSUE THREAD

**Issue by marcomrc** [FreshRSS/FreshRSS#1018]
I need to increase the number of item included in the public rss feed from starred category

This is the url of the interested page p/i/?a=rss&get=s&token=XXXXXX.....

Which file I have to modify? I try in indexController.php but I can't find the number of items to show in public rss.

Thanks for support.

**Comment by Alkarex** [comment]
Currently, this limit is the same as for the number of articles shown in the Web page. You can find it in the configuration page
![nb](https://cloud.githubusercontent.com/assets/1008324/10716036/d3770b18-7b2a-11e5-8571-69f6c4f42bd9.png)
