### ISSUE TITLE
Clicking on an article while the page is still loading opens it in a new window without marking it as read

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/FreshRSS#1021]
Sorry for the long title but I think it actually describes the issue well. So when I reload freshrss main page and when I click on an article as the page hasn't finished loading, the behavior is equivalent to a click on the middle button of the mouse. If I wait until the page has finished loading, the behavior is as expected. 

I may take a video if you are unable to reproduce the issue. Maybe it is related to my browser (Chrome), I will try to test on another one.

**Comment by aledeg** [comment]
That's nothing we can do about it. That's how the web works.
The
notification is sent through javascript and javascript is the last thing
loaded on the page. So as long as the page is still loading, no
javascript actions can be done. 

Le 2015-10-27 3:37, Alwaysin a écrit :

> Sorry for the long title but I think it actually describes the issue
> well. So when I reload freshrss main page and when I click on an article
> as the page hasn't finished loading, the behavior is equivalent to a
> click on the middle button of the mouse. If I wait until the page has
> finished loading, the behavior is as expected. 
> 
> I may take a video
> if you are unable to reproduce the issue. Maybe it is related to my
> browser (Chrome), I will try to test on another one. 
> 
> ## 
> 
> Reply to
> this email directly or view it on GitHub [1].

## Links:

[1]
https://github.com/FreshRSS/FreshRSS/issues/1021

**Comment by Alkarex** [comment]
Alternatively, we could for instance show a "loading" message until everything is ready

**Comment by Alkarex** [comment]
@Alwaysin I have made some changes in the /dev branch, which should help a bit https://github.com/FreshRSS/FreshRSS/issues/1123
Testing of the /dev branch welcome
Feel free to re-open if necessary
