### ISSUE TITLE
Timeout when updating feed

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#1023]
Hello, 

I got plenty of timeout when freshrss is trying to update my feed from rssbridge-youtube

 cURL error 28: Operation timed out after 10000 milliseconds with 0 bytes received

Sometime my server did not respond within the 10sec, where can I change this timeout ?

thanks

**Comment by ghost** [comment]
I reply to myself
in the config file in the data directory.
'timeout' => 10

**Comment by ghost** [comment]
Unfortunately I'm reopening this one.
I've change from 10 to 20 sec the timeout, and from 20 to 30sec and I'm still have a lot of timeout

[Mon, 02 Nov 2015 14:50:59 +0100] [warning] --- cURL error 28: Operation timed out after 30000 milliseconds with 0 bytes received [http://bridge.prysme.net/?action=display&bridge=YoutubeBridge&u=SiliconSentier&format=AtomFormat]

It's seems that it is not related to my server response time. manually I can get the feed within few second.

Is it an incompatibility between rssbridge and freshrss beta 1.3 ?

**Comment by Alkarex** [comment]
When trying your feed from here, I get some "504 Gateway Time-out".
From your server, please try a command such as:

``` sh
curl -m 30 'http://bridge.prysme.net/?action=display&bridge=YoutubeBridge&u=SiliconSentier&format=AtomFormat'
```

In my case, I receive:

```
curl: (28) Operation timed out after 30001 milliseconds with 0 bytes received
```

It seems unrelated to FreshRSS.

**Comment by ghost** [comment]
I get the answer instantly, I don't understand  ...

**Comment by Alkarex** [comment]
Did you try exactly the curl command above?
Now I get a "File not found" response. It looks like there is something wrong with bridge.prysme.net.
Please try with https://validator.w3.org/feed/ also

**Comment by Alkarex** [comment]
![error](https://cloud.githubusercontent.com/assets/1008324/10883806/b4ce1bb6-8174-11e5-956c-9cbdfea39950.png)

**Comment by ghost** [comment]
Thank Alkarex, it seems indeed to be my setup of rssbridge ... the youtube bridge is from time to time gives me timeout ... maybe a flood protection on the youtube side I don't know.
thanks for help me point it out.
