### ISSUE TITLE
Installation does not work anymore

### ISSUE THREAD

**Issue by marienfressinaud** [FreshRSS/FreshRSS#1025]
Due to https://github.com/FreshRSS/FreshRSS/pull/1012, we can't finish installation process since `title` is required.

**Comment by Alkarex** [comment]
Hum, it was supposed to be set by https://github.com/marienfressinaud/FreshRSS/blob/fix/remove-requirement-on-title/app/install.php#L102

**Comment by marienfressinaud** [comment]
This line is executed only during a reinstallation if we keep the previous configuration

**Comment by Alkarex** [comment]
Ok
