### ISSUE TITLE
Translation to russian

### ISSUE THREAD

**Issue by asmfreak** [FreshRSS/FreshRSS#1029]
I want to translate FreshRSS to russian for my personal use. Thank you for the great and lightweight tool.

**Comment by Alkarex** [comment]
You are very welcome to do so, @ASMfreaK 
Let us know if you have any question.

**Comment by royalterra** [comment]
Yes @ASMfreaK I will like that to but I not speak Russian possible if you translate all the words I can help you with the code

**Comment by Alkarex** [comment]
Hi  again @ASMfreaK,
When you are done with the translation, please make a pull request against our /dev branch.
Do not hesitate to ask for help for that.

**Comment by Alkarex** [comment]
The discussion continues in https://github.com/FreshRSS/FreshRSS/pull/1085
