### ISSUE TITLE
NoSql : Redis / MongoDB

### ISSUE THREAD

**Issue by Jean-Mich-Much** [FreshRSS/FreshRSS#1034]
Bonjour,

j'utilise FreshRSS depuis ses premières versions (et actuellement la version bêta).
J'ai migré depuis peu sous MariaDb (rien à signalé pour info), FreshRSS a aussi tourné sous mysql et Sqlite, chacun ayant des avantages et inconvénients.
Comme beaucoup de personnes je m'intéresse de plus en plus aux SGBD No Sql.
Serait-il possible d'envisager le support de Redis / MongoDb. Redis est connue pour conserver l'intégralité des données en RAM, l’accès aux données est très rapide comme vous pouvez l'imaginer, pour une petite base de données c'est particulièrement intéressant et évite les accès disques tout en gardant la possibilité de sauvegarder les données dans un fichier, MongoDB semble "apparemment" plus simple à configurer, fiable, facilite la migration d'un serveur vers un autre, pas mal d'amis webmasters commencent à l'adopter d'où mon intérêt de plus en plus important pour MongoDb. Merci par avance pour votre réponse et aussi pour cette application que me facilite la vie.

**Comment by Alkarex** [comment]
Bonjour,
Ce n'est pas au programme et nécessiterait pas mal de changements. Mais si quelqu'un est motivé pour envoyer un patch, pourquoi pas.
Ceci dit, vous pouvez avoir un SQLite ou MySQL en mémoire, avec réplication sur disque de temps en temps, entre autres solutions.
Pour les performances dans le cas de FreshRSS, je vous suggère plutôt de commencer par essayer PHP7.

**Comment by Jean-Mich-Much** [comment]
Bonsoir,

Merci pour la réponse (je m'en doutais un peu à vrai dire, fallait voir si c'était possible), pour ce qui est de sqlite avec les pragma en effet on peut tout monter en ram facilement, et mariadb pareil avec les buffers/caches (il y a aussi tmpfs / shm /  memcache et toutes ces joyeusetés mais le couple redis/MongoDb va certainement remplacer tout ça sur mon serveur pour 2016, je teste et me forme pour l'instant). Pour php7 je vais attendre un peu les retours d'amis, mais les premiers tests semblent prometteurs en performances et empreinte mémoire (le serveur qui héberge freshrss est principalement utilisé par d'autres applications php destinées au public donc je dois etre patient... et testé, retesté encore et encore lol). Bonne soirée.
