### ISSUE TITLE
disable rss update based on category

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#1036]
Hello

Is it possible to disable RSS update based on a category ?
Even by changing something on the database ? I need to stop requesting RSS update on youtube because my server seems to be blacklisted by Google.

thanks.

**Comment by Alwaysin** [comment]
Related to #968

**Comment by Alkarex** [comment]
It is possible to disable automatic updating by setting `_feed.ttl = -1` in the database for selected feeds.
Not tested, something like:

``` sql
UPDATE freshrss_example_feed SET ttl = -1 WHERE category = ?
```

Put it back to `-2` to go back to default settings.

**Comment by ghost** [comment]
Great thanks Alexandre.
