### ISSUE TITLE
Non-breaking spaces &nbsp; not converted from html

### ISSUE THREAD

**Issue by minami-o** [FreshRSS/FreshRSS#1037]
RSS items from [Mediapart](https://www.mediapart.fr/articles/feed) show non-breaking spaces as **&nbsp;** instead of being converted.
This doesn't seem to happen with other flows, but what surprises me is that other special characters (like **&#039;** for instance) are correctly resolved.
My FreshRSS item:
![mdp](https://cloud.githubusercontent.com/assets/3458254/11472205/42e342d0-976b-11e5-82b0-585aadde5159.JPG)  
RSS flow from browser:
![mdp2](https://cloud.githubusercontent.com/assets/3458254/11472230/784fd0c8-976b-11e5-9a7c-4c710591097f.JPG)
This might be caused by the format of Mdp's RSS flow, but I thought I'd check that out with people who know...
Note that the issue is not always with quotation marks, it also happens with **:** for instance.
Cheers,
Minami-o

**Comment by Alkarex** [comment]
This is a bug on the feed itself. It is triple-encoding those spaces:

``` xml
<![CDATA[ &amp;nbsp; ]]>
```

It would be difficult to support this feed without breaking other legitimate feeds.

We could add some manual options to correct wrong feeds, or via extensions, but I am not sure it is a good idea to be too much tolerant with erroneous feeds - I would rather like to get them corrected.

On Mediapart's side, the easiest would be to avoid trying to do such random encoding, and use Unicode instead.

**Comment by minami-o** [comment]
Thanks for your quick feedback, I'll see if I can reach any tech team on the mdp side.Cheers

Envoyé via Firefox OS
