### ISSUE TITLE
PHP7.0 et connexion

### ISSUE THREAD

**Issue by Rahe** [FreshRSS/FreshRSS#1038]
Bonjour,

Depuis que j'ai mis à jour mon serveur en PHP7.0, lors de la connexion FreshRss me renvoie cette erreur : 

Error 403 - Forbidden
Vous n’avez pas le droit d’accéder à cette page !

Les sessions existantes ne semblent pas être impactées. Est-ce qu'il y a une incompatibilité PHP7.0 ? Parce que l"application est extrêmement rapide depuis la MAJ :)

Merci

**Comment by Alkarex** [comment]
Petite réponse rapide. PHP7 est supporté. Il y a peut-être un bug, mais le
plus probable est que les sessions n'ont pas été configurées correctement
dans le php.ini de votre PHP7.
Est-ce qu'il y a des messages dans les logs de FreshRSS ou du serveur Web ?

**Comment by NodokaMurmevent** [comment]
J'ai le même probleme sous PHP7 dans les logs tout ce que j'ai c'est : 

[Sat Dec 05 17:14:10.340042 2015] [access_compat:error] [pid 12828] [client 90.57.235.196:49338] AH01797: client denied by server configuration: /var/www/FreshRSS/
[Sat Dec 05 17:14:10.553944 2015] [access_compat:error] [pid 12828] [client 90.57.235.196:49338] AH01797: client denied by server configuration: /var/www/FreshRSS/favicon.ico

**Comment by NodokaMurmevent** [comment]
je me permet de m'auto répondre mon php.conf : 
session.save_path = "/var/lib/php/sessions"
session.use_strict_mode = 0
session.use_cookies = 1

et le dossier en question en 777

**Comment by Rahe** [comment]
Je vais regarder du côté des sessions, j'ai pas accès à mon SSH pour le moment je reviens fermer le ticket si c'est ça :) 

Merci !

**Comment by NodokaMurmevent** [comment]
gnarf j'ai toujours le probleme

j'ai un install d'owncloud qui utilise le dossier /var/lib/php/sessions sans aucun probleme j'ai aussi testé le dossier d'install de freshrss et je peut ouvrir un sessions de son emplacement tant que freshrss n'est pas là. je vais tenter avec php7.0-fpm peut être
si tu a besoin de plus d'info hésite pas.

**Comment by Jean-Mich-Much** [comment]
Bonjour,

J'ai testé php 7 et problème identique, les sessions sont stockées dans /var/lib/php7/sessions/,  nginx 1.9.6 (variables utilisées au moment du test sous php 7  : 
1. try_files $uri $uri/ /index.php?$args;
2. fastcgi_split_path_info ^(.+?.php)(/.*)$;
3. fastcgi_pass unix:/run/php/php7.0-fpm.sock; 
rien de particulier :)

chmod 777 sur les dossiers et 755 sur les fichiers (le mode feignasse, juste pour tester lol)

A noter que j'avais installé les paquets debian jessie sid php7.0 avec les versions opitmisées pour php 7 : cgi/fpm/sqlite3/mysql/curl/json/dev/opcache (https://packages.debian.org/search?suite=sid&searchon=names&keywords=php7)

J'ai testé une petite heure : tout fonctionne (cron inclus), sauf  lors de la connexion à FreshRss (Error 403). Mes autres scripts php qui sont indépendants de freshrss fonctionnent tous (pas de problèmes de session pour ceux-ci).

Je n'ai pas creusé plus loin (certainement un petit truc à changer coté nginx ou php.ini : à voir) et remis php 5.6.16.

**Comment by NodokaMurmevent** [comment]
j'ai pas mal creuser et même en passant par php7.0-fpm le probleme reste le même reste plus qu'a voir sir le probleme viens bien de freshRSS ou peut être un beug de PHP7.0 il viens de sortir après tout.

**Comment by Alkarex** [comment]
Merci pour les retours. Je tâcherai de regarder de ces jours-ci. D'ici là, n'hésitez pas à poster plus d'infos. Est-ce que certains d'entre vous ont constaté le même problème avec Apache ?

**Comment by NodokaMurmevent** [comment]
mon install est avec apache et php7.0 (non fpm)

**Comment by Jean-Mich-Much** [comment]
J'ai refait un test cette nuit sur php 7, profitant d'un nombre de visiteurs réduits, j'ai trouvé la solution pour ce qui me concerne :

le dossier contenant les sessions a les permissions 755, il suffit de le passer en 777, pour les non spécialistes, la solution :

chmod 777 /var/lib/php/sessions

service php7.0-fpm restart

Magie, ça fonctionne lol

**Comment by Rahe** [comment]
J'ai fait la même manipulation avec le chmod et tout est rentré dans l'ordre.
Je suppose que c'est uniquement un problème serveur et non pas de FreshRSS :)

**Comment by marienfressinaud** [comment]
Ça ne me paraît quand même pas très sécurisé de mettre des droits 777 sur votre répertoire de sessions (ce qui implique que n'importe quel utilisateur du système peut créer des sessions). C'est _potentiellement_ pas gravissime si vous êtes seul utilisateur sur vos serveurs mais je pense qu'il y a une meilleure solution comme un `chown www-data:www-data /var/lib/php/sessions` (à adapter avec l'utilisateur qui exécute php7.0-fpm)

**Comment by Rahe** [comment]
Oui, ça ne s'applique pas à mon cas, je suis tout seul sur mon serveur :) .
Mais j'entend le propos ;)

**Comment by Jean-Mich-Much** [comment]
Bonjour,

Je suis entièrement d'accord pour la sécurité, c'était un test de stabilité/vitesse/empreinte mémoire/compatibilité concernant php7 pendant une heure max, donc le but n'était pas de chercher une solution en production mais d'avoir un php7 qui tourne  pendant le test avant de réinstaller php 5 avec des sessions cette fois bien sécurisées je vous rassure lol. Conclusion du test : ... je vais attendre quelques mois de patchs avant d'utiliser php 7 (mes propres scripts php fonctionnent sans problèmes mais le bug rencontré sur freshrss me fait penser que php 7 est encore trop jeune pour une réelle utilisation en production au quotidien : voir la liste des bugs ici ---> https://bugs.php.net/search.php?limit=30&order_by=id&direction=DESC&cmd=display&status=Open&bug_type=All&phpver=7.0).

**Comment by marienfressinaud** [comment]
Ok parfait :) Je tenais à faire cette précision au cas où des gens tombent sur ce ticket en pensant que c'est LA solution ;)

**Comment by NodokaMurmevent** [comment]
Personnellement pour résoudre le problème avec php7 sans 777 j'ai mis dans apache.conf

```
<IfModule mod_fastcgi.c>
     AddType application/x-httpd-fastphp .php
     Action application/x-httpd-fastphp /php-fcgi    
    # PHP7
    Alias /php-fcgi /usr/lib/cgi-bin/php
    FastCgiExternalServer /usr/lib/cgi-bin/php -appConnTimeout 10 -idle-timeout 250 -socket /run/php/php7.0-fpm.sock -pass-header Authorization
</IfModule>
```

et dans php.ini

```
session.save_path = "/tmp"  
```

sans toucher aux droits et comme ça au redémarrage du serveur les sessions sautent
