### ISSUE TITLE
Export to OPML from the CLI

### ISSUE THREAD

**Issue by ingelres** [FreshRSS/FreshRSS#1039]
Hi,

As part of my daily backup, I would like to export my feeds to an OPML file. It seems that currently it's possible to do that only from the WEB interface, where a script (e.g., à la actualize_script.php) would be needed.

I know I could back up the DB, but it's specific to FreshRSS. I would much prefer back up a plain OPML file.

**Comment by aledeg** [comment]
That's a good idea. I think that it will be nice to decouple the code to have reusable components

See #956

**Comment by Alkarex** [comment]
Related https://github.com/FreshRSS/FreshRSS/issues/1090

**Comment by Alkarex** [comment]
Implemented in https://github.com/FreshRSS/FreshRSS/pull/1338
Comments welcome there

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/issues/1095
