### ISSUE TITLE
php 5.6 problem ?

### ISSUE THREAD

**Issue by falcon-zz-ix** [FreshRSS/FreshRSS#1040]
Hello, 
I got a problem when i move my freshrss from another server ( old server use php 5.5 )

[Sat Dec 12 17:52:03.184201 2015] [:error] [pid 38235] [client xxxxxx:61313] PHP Catchable fatal error:  Argument 1 passed to SimplePie::set_curl_options() must be of the type array, null given, called in /usr/home/user/public_html/news/lib/lib_rss.php on line 173 and defined in /usr/home/user/public_html/news/lib/SimplePie/SimplePie.php on line 826, referer: http://news.web.com/p/i/

freshrss 1.2.0
database sqlite

user@server:~/log % httpd -v
Server version: Apache/2.4.17 (FreeBSD)
Server built:   Dec  1 2015 20:12:02

user@server:~/log % php -v
PHP 5.6.16 (cli) (built: Dec  2 2015 18:48:46)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies

**Comment by Alkarex** [comment]
Hello,
There is probably something wrong with your `data/config.default.php` and/or `data/config.php`.
See https://github.com/FreshRSS/FreshRSS/blob/bb0556543d3d5d54832ea6d81372587b88062a5b/data/config.default.php#L98

**Comment by Alkarex** [comment]
Feel free to re-open if there is still a problem.
