### ISSUE TITLE
Flux sans activité pour freshrss

### ISSUE THREAD

**Issue by monsieurpouet** [FreshRSS/FreshRSS#1041]
J'ai constaté depuis la maj vers la 1.2.0 que plusieurs de mes flux RSS étaient reconnu comme sans activité ou invalide par freshrss malgré leurs existences sur les différents blogs que je consulte.

Freshrss m'indique le nom du blog en rouge en me disant: "Arf ! Ce flux a rencontré un problème. Veuillez vérifier qu’il est toujours accessible puis actualisez-le."
![prtscr capture](https://cloud.githubusercontent.com/assets/3777059/11785235/15a76136-a281-11e5-82bc-809373075fad.jpg)

Alors que le flux existe bien.
J'ai supprimé les .spc dans ./data/cache/, mais sans succès. Je n'ai pas supprimé les *.freshrss.lock dans /tmp car je n'en ai pas.

**Comment by Alkarex** [comment]
Essayez de consulter les logs pour plus d'informations sur la raison du problème.
Vous pouvez aussi essayer de mettre une valeur de `timeout` supérieure dans votre `data/config.php` https://github.com/FreshRSS/FreshRSS/blob/1.1.1/data/config.default.php#L65 (évitez de modifier `data/config.default.php`).

**Comment by badconker** [comment]
J'ai un problème similaire avec le flux : https://wpchannel.com/feed/.
Quand je l'actualise, j'ai le message "Il n’y a aucun flux à actualiser…" et pas de log. Si j'essaie de l'ajouter à nouveau, j'ai le log `Feed error [https://wpchannel.com/feed/]` 
Pas de soucis à la validation : http://validator.w3.org/feed/check.cgi?url=https://wpchannel.com/feed/

**Comment by Alkarex** [comment]
@badconker Je pense que dans votre cas, c'est simplement un problème de certificat HTTPS de `https://wpchannel.com/feed/` (la chaîne du certificat est cassée) :

``` sh
$ curl https://wpchannel.com/feed/
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html
```

Plus d'informations sur https://www.ssllabs.com/ssltest/analyze.html?d=wpchannel.com

Si l'auteur du flux ne peut pas corriger le problème de son côté et que vous tenez vraiment à ce flux, vous pouvez alors baisser la sécurité dans `data\config.php` (voir `CURLOPT_SSL_VERIFYHOST` et `CURLOPT_SSL_VERIFYPEER` sur le modèle de `data\config.default.php`). Profitez-en pour vous mettre en `'environment' => 'development',` pour avoir plus de messages dans les logs.

**Comment by monsieurpouet** [comment]
J'ai augmenter le timeout de 10 à 20.
Je verrais avec le temps.

Pour info, je viens de me faire avoir par mon crontab qui m’envoyait, sur une adresse mail de monitoring, le résultat de actualise.php à un mail qui n'existait pas. Donc, le serveur destina ire m'a renvoyé plus de 4900 mail pour dire que cette adresse n’existait pas.. Donc vérifiez bien vos crontab et votre conf de mailer.
C'était pour l'anecdote.

**Comment by Alkarex** [comment]
Ok, n'hésitez pas à rouvrir au besoin.

**Comment by badconker** [comment]
D'accord merci pour votre réponse :)
