### ISSUE TITLE
OPML import: Automaticly fetch feed url for website

### ISSUE THREAD

**Issue by BlackLotus** [FreshRSS/FreshRSS#1042]
I searched for the function and I looked at the existing tickets, but couldn't find one fittings this.
I imported my feeds from a different feed reader that took website urls and extracted the feeds from it.
Basicly what http://validator.w3.org/feed/check.cgi?url= does which is looking for a <link> tag with type="application/rss+xml" or atom.
Right now I got a feed list with a few dozen incomplete feed urls and my only option is to either update them manually (which is easy, but manual labor) or write a script to do so.If I missed a function I would be happy too.

**Comment by Alkarex** [comment]
I cannot remember in the OPML import, but at least when you add a new Web site to FreshRSS, an automatic discovery is done. Is that your question?

**Comment by BlackLotus** [comment]
Yes I was talking about opml import.I admit that I didn't yet try to add a side manually, since I got a complete feedlist (I manually corrected the import already)
But it would be neat if an import would do a lookup aswell.

**Comment by math-GH** [comment]
Is it still an relevant feature request?

**Comment by BlackLotus** [comment]
Switched to newsblur 7 years ago. Can be closed

**Comment by Alkarex** [comment]
Was implemented in https://github.com/FreshRSS/FreshRSS/pull/3071
