### ISSUE TITLE
can't connect to API using FreshRSS (because of a TLS 1.1 or 1.2 issue)

### ISSUE THREAD

**Issue by oupala** [FreshRSS/FreshRSS#1043]
Hello,

I'm trying to connect to my FreshRSS instance using EasyRSS. But connecting fail due to a login /password error. On the server side, the 

```
Invalid API authorisation for user poulpe: 82fee2gb4dd7ee12ad8c6085d7d4394b7d965841
unauthorized()
Array
(
    [date] => 2015-12-18T22:56:12+01:00
    [headers] => Array
[...]
```

First I was using https, then I switched to http in order to check if it could be due to the certificate. But same result in http.

I've double checked each item from this thread: #443 but nothing fixed my problem.

Any help is welcome.

**Comment by Alkarex** [comment]
Did you remember to set the API password for user `poulpe` in FreshRSS Web interface?

![password](https://cloud.githubusercontent.com/assets/1008324/11912982/56604b20-a655-11e5-8385-c1a920f2f87d.png)

**Comment by oupala** [comment]
Yes I did, I set the main password, and the API password (by the way "API password" would be better english than "Password API").

I set and set and set this password again an again. By the way, what is the small "key" icon for? It does nothing for me...

I typed and retyped the password on the EasyRSS interface.

I still have the same problem.

In order to check if the password is well stored in the config file, what how is the hash calculated from the original password?

**Comment by oupala** [comment]
Can I use the API even if my user is the admin user?

Does the email has to be set ? There is no email set for my account.

**Comment by Alkarex** [comment]
Yes, you can use the API even with an admin user. E-mail does not have to be set.

Try to uncomment the lines 544-545 https://github.com/FreshRSS/FreshRSS/blob/9534ea0e6b54cd899ac4432f1ae8f14258613ae6/p/api/greader.php#L544 and then look at the API logs in `/data/users/_/log_api.txt` (you should see your password).

**Comment by oupala** [comment]
Ok, I can now see in the logfile that the password I entered in FreshRSS is the one that is logged.

But I still get the same error message:

```
Invalid API authorisation for user poulpe: 82fee2gb4dd7ee12ad8c6085d7d4394b7d965841
unauthorized()
```

The strange thing is that I still get the same hash in the log file (`82fee2gb4dd7ee12ad8c6085d7d4394b7d965841`) even though I changed the API password.

Is it normal that the email in the log file is filled with the FreshRSS username?

```
[INPUT] => Email=poulpe&Passwd=mdpmdpmdp&accountType=GOOGLE&service=reader&source=Sun-EasyRSS
```

**Comment by oupala** [comment]
You said in #443 (in [this comment](https://github.com/FreshRSS/FreshRSS/issues/443#issuecomment-36666133)that we had to use the username and not the email to login:

```
You can now try from a mobile app, using http://your.server.example/FreshRSS/p/api/greader.php as the address, together with your FreshRSS username, and the special API password.
```

I tried to compare the password I see on the log file with the password stored on disk, but this password is hashed so I can't compare them. I'd like to manually rehash my password and then compare this hash to the stored value. How could I achieve that?

**Comment by oupala** [comment]
I also have to say that I used to be a happy EasyRSS user along with FreshRSS. So I know EasyRSS can work with FreshRSS. I did it without problem!

But I had a disk failure and I had to reinstall everything. I then updated FreshRSS to 1.1.3-beta while I was previously using 1.1.0.

What has changed from 1.1.0 to 1.1.3-beta? Could this be a clue to find out why it is not working?

**Comment by oupala** [comment]
I can see in source code that FreshRSS is using sha1 hashing, with a salt.

Could it be a salt issue? Is it possible to reset the sal value?

**Comment by Alkarex** [comment]
Could you please try:
- To change your normal FreshRSS password, and see if it is changed properly;
- Try with a new API password with only alphanumeric characters (no special characters);
- Try to re-install EasyRSS;

The rest you have shown seems to be normal.
The salt is in `data/config.php`.

You can have a look at http://php.net/password-verify to manually compare the hashes during login
https://github.com/FreshRSS/FreshRSS/blob/9534ea0e6b54cd899ac4432f1ae8f14258613ae6/p/api/greader.php#L190 and then during the token check
https://github.com/FreshRSS/FreshRSS/blob/9534ea0e6b54cd899ac4432f1ae8f14258613ae6/p/api/greader.php#L159

Based on your error message, it seems like the problem is in the token, not in the first login.
https://github.com/FreshRSS/FreshRSS/blob/9534ea0e6b54cd899ac4432f1ae8f14258613ae6/p/api/greader.php#L159

**Comment by oupala** [comment]
I've already tested to modify the main password, it works as the new password allows me to log in.

I also tested to change the API password, with alpha characters only. I can see that the config.php file from my user is getting updated (the apiPasswordHash variable).

I will try to reinstall FreshRSS v1.1.0.

**Comment by oupala** [comment]
It appears that there was two problems.

First, it seems that EasyRSS does not really change the password if you try to connect with different passwords. I advise users to close and reopen EasyRSS if they had updated the api password on FreshRSS side and want to try to connect with EasyRSS and the new password.

This first problem explains probably why my tests failed with http.

Second, I had configured a strong apache configuration with TLS enforcement (see [Mozilla SSL Configuration Generator](https://mozilla.github.io/server-side-tls/ssl-config-generator/) for more information) and TLS 1.0 was disabled. It appears that my Android device was not supporting TLS upper than 1.0. I think my Android device has a _19 API levels_ and TLS 1.1 and 1.2 is only activated by default with API levels 20 and more (see [this page](http://developer.android.com/reference/javax/net/ssl/SSLSocket.html) for more information).

This second problem explains probably why my tests failed with http**s**.

**Comment by oupala** [comment]
As it does now work and as I added all needed explanation, feel free to close this issue. Thanks for your help!

**Comment by Alkarex** [comment]
Ok, I am glad it works for you again.

TLS 1.1+ should work on some devices with Android 4.1+, but my own tests show that it first works reliably with Android 5.0+ https://github.com/Alkarex/EasyRSS/commit/762d3f4472aedb2228203fa95731bbe85b341b65#commitcomment-11011379

I have corrected the English wording problem https://github.com/Alkarex/FreshRSS/commit/7184ad7b2f0d8f65faa6600f015605662b3705f1
