### ISSUE TITLE
marked-as-read post come back on next update

### ISSUE THREAD

**Issue by oupala** [FreshRSS/FreshRSS#1044]
I have some marked-as-read post. They disappear when I set them as read.

I'm using cron to refresh all my feeds each hour.

After a refresh, some of my posts are coming back as unread (it is always the same posts).

Do you know why?

**Comment by Pazns** [comment]
There is an option in Configuration panels to mark read posts as "not read" when they are updated.

I have this exact problem with one specific feed, I need to investigate to uncover whose fault it is : 
- FreshRSS incorrect parsing;
- Feed incorrect RSS generation, or correct RSS but weird behaviour.

**Comment by oupala** [comment]
Yes I've seen that option in configuration. I don't think this is the case as it is always the same 17 posts that come back as unread. Altought I don't think these 17 posts are updated every day. These 17 posts come from different feeds.

That's why I'm thinking of a FreshRSS issue. Maybe a permission problem on files ?

Nevertheless, I'll try to disable this option to see if has any effect.

**Comment by Alkarex** [comment]
It is most likely that the feed entries are updated. Please re-open with more information if this is not the case (ideally, a copy of the RSS feed at two different times). See https://github.com/FreshRSS/FreshRSS/issues/798#issuecomment-89655370 for more details, and examples of feeds wrongly updating their content. If you set `'environment' => 'development',` in your `data/config.php` you will get some logs with information about the entries that get updated.
