### ISSUE TITLE
FreshRSS orders posts in a weird way.

### ISSUE THREAD

**Issue by Pazns** [FreshRSS/FreshRSS#1045]
FreshRSS seems to order posts (« recent to old », or « old to recent ») according to the SQL field « id » and not the expected SQL field « date » .

It's _very_ annoying when you set up FreshRSS the first time : posts are packed by feeds because FreshRSS parsed them this way, one by one, making their respective « id » grouped together. Even if dates are not at all grouped.
It can produce this weird behaviour even with day-to-day work with high activity feeds.

Anyone can confirm this behaviour ?

**Comment by Pazns** [comment]
Well, seems to be already in processing, according to #530 .
What is the status of this ?

**Comment by Alkarex** [comment]
The order should be quite fine already if you set up a cron job that refreshes the feeds regularly. In particular, the feeds served by push (PubSubHubbub) are fine.
Continues in https://github.com/FreshRSS/FreshRSS/issues/530

**Comment by Pazns** [comment]
How can I correct the order for everything, essentially from the initial first parse, that is still packed together improperly, then ?

**Comment by Alkarex** [comment]
An implementation of the more natural order is available. Tests much welcome https://github.com/FreshRSS/FreshRSS/pull/1470
