### ISSUE TITLE
Feature resquest: Order MAin Stream

### ISSUE THREAD

**Issue by royalterra** [FreshRSS/FreshRSS#1046]
Will be a good Idea order Main Stream according to the language use in the Browser. Like is now if you have multiples languages show all mixed

**Comment by Alkarex** [comment]
I do not understand. Could you please send a screenshot explaining the problem?

**Comment by royalterra** [comment]
Is not a problem Example now you can archive the feeds by Category I can make category according to a country UK, Spain, USA, China ....
Every Feed in a category have different language example English, Spanish, Chinese ...
Can be a good Feature when the user go to the web the Main Stream become the category with language use in the own web browser .
Example if my web browser or computer is in Spanish when I go to my FreshRss will show first the category Spain have the language Spanish

**Comment by Alkarex** [comment]
Ah, I see. I do not plan to implement that in FreshRSS; however, you could easily do a landing page with such a functionality:

landing.php (not tested):

``` php
$lang = empty($_SERVER['HTTP_ACCEPT_LANGUAGE']) ? '' : substr($_SERVER['HTTP_ACCEPT_LANGUAGE'], 0, 2);

switch ($lang) {
  case 'en':
    header('Location: /FreshRSS/p/i/?get=c_11');
    break;
  case 'fr':
    header('Location: /FreshRSS/p/i/?get=c_12');
    break;
  default:
    header('Location: /FreshRSS/p/');
    break;
}

```

This is similar than http://stackoverflow.com/questions/3770513/detect-browser-language-in-php , but it would be better with a proper language negotiation http://php.net/manual/en/function.http-negotiate-language.php
