### ISSUE TITLE
Deleting a feed in statistics page result in an error

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/FreshRSS#1047]
Steps to reproduce :
- Go to `http://<freshrss>/i/?c=stats&a=idle`
- Click on "delete" on one feed

Then you are redirected to `http://<freshrss>/i/http%3A%2F%2F<freshrss>%2Fi%3Fc%3Dstats%26a%3Didle` and you get this :

```
Not Found

The requested URL /i/http://<freshrss>/i?c=stats&a=idle was not found on this server.
```

But the feed is indeed deleted.

**Comment by Alwaysin** [comment]
https://github.com/FreshRSS/FreshRSS/blob/dev/app/views/stats/idle.phtml#L29, I've replaced

```
formaction="<?php echo _url('feed', 'delete', 'id', $feed['id'], 'r', $current_url); ?>"
```

with

```
formaction="<?php echo _url('feed', 'delete', 'id', $feed['id']); ?>"
```

and it works, but we are redirected to `http://<freshrss>/i/?c=subscription`

**Comment by Alkarex** [comment]
@Alwaysin  Could you please provide a pull request with your modification?

**Comment by marienfressinaud** [comment]
The idea was to stay on the idle statistics page, I would prefer a PR which fix the redirection instead of redirecting to the subscription page...

**Comment by Alkarex** [comment]
Fixed in https://github.com/FreshRSS/FreshRSS/pull/1109
