### ISSUE TITLE
OPML import with "title" field

### ISSUE THREAD

**Issue by plarus** [FreshRSS/FreshRSS#1048]
OPML export from Netvibes generate xml file with "title" field instead of "text" field.
It could be great if freshRSS can manage "text" and "title" field for category and feed element.
It seem that something like that have already be done here : https://github.com/Alkarex/FreshRSS/commit/0696890c06557770ba2ab4f101003c3e8bb95ccf

**Comment by Alkarex** [comment]
@plarus Could you please provide a sample of such an OPML?

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/commit/0696890c06557770ba2ab4f101003c3e8bb95ccf

**Comment by plarus** [comment]
The netvibes generated file :
[InfoNews-88382560.zip](https://github.com/FreshRSS/FreshRSS/files/74766/InfoNews-88382560.zip)

**Comment by Alkarex** [comment]
``` xml
<?xml version="1.0" encoding="UTF-8"?>
<opml version="1.0">
 <head>
  <title>InfoNews</title>
 </head>
 <body>
  <outline title="Informatique" icon="http://cdn.netvibes.com/img/icons/computer.gif" cols="3" layout="3-0">
   <outline title="News et articles clubic" xmlUrl="http://www.clubic.com/articles.rss" htmlUrl="http://clubic.com/" type="rss" row="1500" col="1"/>
   <outline title="01net. Actualités" xmlUrl="http://rss.feedsportal.com/c/629/f/502199/index.rss" htmlUrl="http://www.01net.com/actus/" type="rss" row="2250" col="1"/>
   <outline title="Next INpact" xmlUrl="http://www.nextinpact.com/rss/news.xml" htmlUrl="http://www.nextinpact.com/" type="rss" row="500" col="2"/>
   <outline title="MiniMachines.net" xmlUrl="http://feedpress.me/minimachines" htmlUrl="http://www.minimachines.net/" type="rss" row="1250" col="2"/>
   <outline title="Les Numériques" xmlUrl="http://feeds.feedburner.com/lesnumeriques/news" htmlUrl="http://www.lesnumeriques.com/" type="rss" row="1000" col="3"/>
   <outline title="Actualité Tom's Hardware FR" xmlUrl="http://www.tomshardware.fr/feeds/rss2/news.xml" htmlUrl="http://www.tomshardware.fr/" type="rss" row="3000" col="3"/>
   <outline title="Developpez.com, le club des décideurs et professionnels en Informatique" xmlUrl="http://www.developpez.com/index/rss" htmlUrl="http://www.developpez.com/index/rss" type="rss" row="4000" col="3"/>
  </outline>
 </body>
</opml>
```

**Comment by Alkarex** [comment]
It seems the bug was introduced in version 1.3.0 with https://github.com/FreshRSS/FreshRSS/commit/9ea3819402746d8425d4a608f2d5f3c0f5bc29fb

**Comment by Alkarex** [comment]
@plarus Should be fixed in https://github.com/FreshRSS/FreshRSS/pull/1112
Please test if you can

**Comment by Alkarex** [comment]
https://github.com/marienfressinaud/lib_opml/issues/3

**Comment by Alkarex** [comment]
Discussion continues in https://github.com/marienfressinaud/lib_opml/issues/3

**Comment by Alkarex** [comment]
Now merged in /dev https://github.com/FreshRSS/FreshRSS/issues/1113
