### ISSUE TITLE
how to implement sharing menu entry

### ISSUE THREAD

**Issue by dmaglio** [FreshRSS/FreshRSS#1051]
I would to add an entry in sharing menu, i need to add Pocket. I read about wallabag but i use Pocket and i know their API.
Is it a wiki page or documentation about it?

**Comment by Alkarex** [comment]
You can see an example on e.g. https://github.com/FreshRSS/FreshRSS/pull/1054

**Comment by Alkarex** [comment]
Feel free to re-open if needed
