### ISSUE TITLE
PHP 5.2 not compatible

### ISSUE THREAD

**Issue by barbuslex** [FreshRSS/FreshRSS#1055]
Hi,

I have this error on PHP 5.2 : 

> Call to undefined function array_replace_recursive() in //lib/Minz/Configuration.php

array_replace_recursive() is available on PHP 5.3. In FreshRSS documentation it is writtent compatible with PHP 5.2.1+.

Can you help me ?

++

**Comment by Alkarex** [comment]
Ok, this should be easy to fix. I will make a patch.

**Comment by barbuslex** [comment]
Ok thanks !
Maybe there are other inconsistencies I did not go further in the script.

**Comment by Alkarex** [comment]
@barbuslex Here is a patch. Could you please test https://github.com/FreshRSS/FreshRSS/issues/1059 ?

**Comment by barbuslex** [comment]
@Alkarex I've tested.

Another error now : 

> Fatal error: Cannot redeclare recurse() (previously declared in /lib/lib_rss.php:20) in /lib/lib_rss.php on line 20

I've tried to change recurse() by recurse_arr() (_arr for array replace recursive) and i get the same error : 

> Fatal error: Cannot redeclare recurse_arr() (previously declared in /lib/lib_rss.php:20) in /lib/lib_rss.php on line 20

**Comment by barbuslex** [comment]
In your modification in /lib/lib_rss.php,

I have replace : 

``` php
function recurse($array, $array1) {
    foreach ($array1 as $key => $value) {
        if (!isset($array[$key]) || (isset($array[$key]) && !is_array($array[$key]))) {
            $array[$key] = array(); //create new key in $array, if it is empty or not an array
        }
        if (is_array($value)) {
            $value = recurse($array[$key], $value); // overwrite the value in the base array
        }
        $array[$key] = $value;
     }
    return $array;
}
```

By : 

``` php
if (!function_exists('recurse')) {
    function recurse($array, $array1) {
        foreach ($array1 as $key => $value) {
            if (!isset($array[$key]) || (isset($array[$key]) && !is_array($array[$key]))) {
                $array[$key] = array(); //create new key in $array, if it is empty or not an array
            }
            if (is_array($value)) {
                $value = recurse($array[$key], $value); // overwrite the value in the base array
            }
            $array[$key] = $value;
        }
        return $array;
    }
}
```

And it work's !

But now, in installation steps (url : /p/i/index.php?step=2) i have this error : 

> Parse error: syntax error, unexpected '{' in /lib/password_compat.php on line 10

The line in question is (/lib/password_compat.php line 10) : 

``` php
namespace {
```

**Comment by Alkarex** [comment]
Ah, yes indeed. The password form requires PHP 5.3.3, and the inclusion of this code needs to check for `cryptAvailable()` first.

On line https://github.com/FreshRSS/FreshRSS/blob/dev/app/install.php#L133

``` php
if ($password_plain != false && cryptAvailable()) {
```

I will make a patch later.

**Comment by barbuslex** [comment]
With this fix i stay on step 2 with this html alert error in top of the form : 

> Veuillez corriger les erreurs avant de passer à l’étape suivante.

**Comment by Alkarex** [comment]
It looks like for some reason you have been able to select `form` as a login method. It is a bug if this option is available for < PHP 5.3.3. Could you please try again by selecting HTTP or nothing for login?

**Comment by Alkarex** [comment]
P.S. Loging with HTTP requires that you make a password protection with your Web server, e.g. a `.htaccess` with Apache:

```
AuthUserFile /xxx/.htpasswd
AuthGroupFile /dev/null
AuthName "FreshRSS news"
AuthType Basic
Require valid-user
```

**Comment by Alkarex** [comment]
Indeed, there is a bug https://github.com/FreshRSS/FreshRSS/blob/dev/app/install.php#L684 which pre-selects `form` login even when not available. I will fix it.

**Comment by Alkarex** [comment]
I have made another attempt in https://github.com/FreshRSS/FreshRSS/pull/1059 (not tested).
I may have to install a virtual machine with PHP 5.2 to test...

**Comment by barbuslex** [comment]
I have succefully install FreshRSS with this fix.
But it's impossible to enable authentication. Non authentication mode is very dangerous :(

**Comment by Alkarex** [comment]
Yes, form-based login requires PHP 5.3.3+. With older version, you can use HTTP login. See https://github.com/FreshRSS/FreshRSS/issues/1055#issuecomment-174639966
(This is the login system I use myself)

**Comment by barbuslex** [comment]
Yes but if i want generate a rss feed aggregated must not authentication in this case.

**Comment by Alkarex** [comment]
HTTP login is less convenient for that indeed, but there are different possibilities such as making some URL rewriting for those URLs or a proxy. (I do that for my Shaarli, of which I only expose an RSS feed, the rest being with an HTTP password).

Until November 2016, you can also use Persona for login https://github.com/FreshRSS/FreshRSS/issues/1052

On a related topic, here is a reference to a discussion from a year ago about PHP versions https://github.com/FreshRSS/FreshRSS/issues/789#issuecomment-73878076

Out of curiosity, on which distribution do you run PHP 5.2? (It is interesting to get some feedback from users to help setting minimal requirements).

**Comment by barbuslex** [comment]
I will try persona.

I use 000webhost.com hosting ^^

**Comment by royalterra** [comment]
@barbul..... 000 is a share hosting with very bad performance one and is hack several times. Really if you use free hosting like that why you post bugs?

**Comment by Alkarex** [comment]
In any case, my plan is more or less to have one last version of FreshRSS supporting PHP 5.2, then to set the minimal version to PHP 5.3.3 for some time (for CentOS 6, which stops in Q2 2017, but we may not wait that long).

**Comment by Alkarex** [comment]
@barbuslex Maybe your hosting plan allows to change the PHP version. Did you check?

**Comment by barbuslex** [comment]
Yes i know it's just for test this plan. I will migrate to better hosting plan later.
Not possible to change PHP version in free hosting :)

**Comment by royalterra** [comment]
That host not allow changes and is full of limitations and bugs for that is hack several times a year. Still I got emails from the admin every time go down. really a hosting can be free but you choice the worse free hosting in internet

**Comment by barbuslex** [comment]
Yes ^^ i have migrate to GoogieHost with last version of PHP.

**Comment by Alkarex** [comment]
Just to close the topic here, can you please confirm, @barbuslex , that https://github.com/FreshRSS/FreshRSS/issues/1059 works with your PHP 5.2?

**Comment by barbuslex** [comment]
Yes it work's fine
