### ISSUE TITLE
Problem when running FreshRSS on openshift

### ISSUE THREAD

**Issue by oussemos** [FreshRSS/FreshRSS#1057]
Hello,
I'm running FreshRSS on OpenShift, when I want to actualize feeds, I got the following error

Version 1.2.0
PHP 5.4.40

php /var/lib/openshift/5640cd417628e1c395000118/app-root/runtime/repo/app/actualize_script.php
Starting feed actualization at 2016-01-20T11:28:23+00:00
Actualize admin...
PHP Warning:  DOMDocument::loadXML(): XML declaration allowed only at the start of the document in Entity, line: 1 in /var/lib/openshift/5640cd417628e1c395000118/app-root/runtime/repo/lib/SimplePie/SimplePie/Parser.php on line 145

Any advice? Thanks.

**Comment by Alkarex** [comment]
Hello. It is only a warning, not an error, and probably due to an RSS feed with slightly invalid content.

**Comment by Alkarex** [comment]
Feel free to re-open if there is still a problem.
