### ISSUE TITLE
No favicons after import opml file

### ISSUE THREAD

**Issue by barbuslex** [FreshRSS/FreshRSS#1068]
Hi,

I just import opml file to my new installation of FreshRSS 1.3.0-beta and never favicons appears.
![favicons](https://cloud.githubusercontent.com/assets/113057/12579301/4b5feb8c-c427-11e5-8700-dc61d696554d.PNG)

Can you help me ?

Thanks

**Comment by Alkarex** [comment]
Is it also when running PHP 5.2? https://github.com/FreshRSS/FreshRSS/issues/1055 If yes, I have just seen that the Favicon library uses namespaces (could easily be removed) https://github.com/FreshRSS/FreshRSS/blob/beta/lib/Favicon/Favicon.php#L3

If running PHP 5.3+, could you please have a look at your logs, and also try to browse to one of these icons? Please check also the content for your directory `./FreshRSS/data/favicons/` : it should contain some *.txt (containing a URL) and some *.ico.

**Comment by barbuslex** [comment]
I am on PHP 5.5

When i go to this url : /p/f.php?d905fac3
I have some txt and ico files in /data/favicons folder.

I get this PHP error : 

> Fatal error: Call to undefined function Favicon\finfo_open() in /lib/Favicon/Favicon.php on line 229

**Comment by barbuslex** [comment]
Is it because fileinfo php extension was not installed on my php.
