### ISSUE TITLE
cannot install when data directory is a symlink

### ISSUE THREAD

**Issue by oupala** [FreshRSS/FreshRSS#1069]
It seems that FreshRSS cannot be installed when `data` directory is a symlink:

When I open the homepage of FreshRSS in a browser, I get the following error:

```
### Fatal error! ###
```

And the apache error show me the following error:

```
[Mon Jan 25 10:20:15.645598 2016] [:error] [pid 31843] [client 192.168.1.13:39772] PHP Warning: file_put_contents(/home/pi/apps/FreshRSS/data/users/ploc/log.txt): failed to open stream: No such file or directory in /home/pi/apps/FreshRSS/lib/Minz/Log.php on line 69
[Mon Jan 25 10:20:15.647989 2016] [:error] [pid 31843] [client 192.168.1.13:39772] PHP Fatal error:  Uncaught exception 'Minz_PermissionDeniedException' with message 'Permission is denied for `/home/pi/apps/FreshRSS/data/users/ploc/log.txt`' in /home/pi/apps/FreshRSS/lib/Minz/Log.php:70
Stack trace:
#0 /home/pi/apps/FreshRSS/lib/Minz/Log.php(103): Minz_Log::record('Permission is d...', 2, NULL)
#1 /home/pi/apps/FreshRSS/p/i/index.php(49): Minz_Log::error('Permission is d...')
#2 {main}\n  thrown in /home/pi/apps/FreshRSS/lib/Minz/Log.php on line 70
```

I think that it is not a permission related issue, as I'm doing the following operation:

``` bash
cd freshrss-directory
mv data data-moved
ln -s data-moved data
```

This is only a test, but I know that data-moved is allowing write for www-data user.

Thanks for any suggestion for further testing, or for a solution.

**Comment by JD557** [comment]
Could you run a `ls -l`?

I believe that a symlink does not keep the same permissions/owner of the original file.

**Comment by Alkarex** [comment]
After checking the permissions of the source and the target, in the case of Apache, check also FollowSymLinks / SymLinksIfOwnerMatch http://httpd.apache.org/docs/trunk/mod/core.html#options

**Comment by oupala** [comment]
@JD557 In fact, symlinks have no permission. They only link to a destination file, which has its own permissions. See http://superuser.com/questions/303040/how-do-file-permissions-apply-to-symlinks/303063#303063

**Comment by oupala** [comment]
@Alkarex Permissions are ok, and FollowSymLinks / SymLinksIfOwnerMatch are set.

But it is still not working.

``` bash
>ll
total 124
drwxrwxrwx 2 pi   pi    4096 janv. 29 01:40 another-data
drwxr-xr-x 9 pi   pi    4096 janv. 24 16:35 app
lrwxrwxrwx 1 pi   pi      13 janv. 29 01:40 data -> another-data/
drwxr-xr-x 2 pi   pi    4096 janv. 24 16:35 extensions
drwxr-xr-x 5 pi   pi    4096 janv. 24 16:35 lib
-rwxr-xr-x 1 pi   pi   34521 janv. 24 16:35 LICENSE
drwxr-xr-x 6 pi   pi    4096 janv. 29 01:37 p
drwxr-xr-x 3 pi   pi    4096 janv. 24 16:35 tests
-rw-r--r-- 1 pi   pi     308 janv. 24 16:35 index.html
-rw-r--r-- 1 pi   pi   23670 janv. 24 16:35 CHANGELOG.md
-rw-r--r-- 1 pi   pi    3437 janv. 24 16:35 CONTRIBUTING.md
-rw-r--r-- 1 pi   pi    2279 janv. 24 16:35 CREDITS.md
-rw-r--r-- 1 pi   pi    8086 janv. 24 16:35 README.fr.md
-rw-r--r-- 1 pi   pi    6982 janv. 24 16:35 README.md
-rw-r--r-- 1 pi   pi     974 janv. 24 16:35 constants.php
-rw-r--r-- 1 pi   pi      64 janv. 24 16:35 index.php
```

As you can see, all files belongs to the `pi` user, and everybody has read, write and execute permission on `data` directory.

**Comment by Alkarex** [comment]
Did you check your php.ini for restrictions such as `open_basedir` ?

**Comment by oupala** [comment]
`open_basedir` is not enabled.

I'm writing an ansible role to install FreshRSS automagically. I'll test again to see if it is still not working, and why...

**Comment by oupala** [comment]
Can't reproduce it any more.
