### ISSUE TITLE
Turkish Language

### ISSUE THREAD

**Issue by hckweb** [FreshRSS/FreshRSS#1073]
Hi from Turkey.

I have translated FreshRSS to Turkish language.

Is it possible you to release it officially ?

https://github.com/hckweb/FreshRSS-Turkish-Language

Thanks.

**Comment by Alkarex** [comment]
Excellent @hckweb , thanks!
Would you mind making a pull request against our /dev branch?

**Comment by aledeg** [comment]
:+1:

**Comment by hckweb** [comment]
Done. https://github.com/FreshRSS/FreshRSS/pull/1074
Anything wrong ? @Alkarex

**Comment by Alkarex** [comment]
Looks good :+1:

**Comment by Alkarex** [comment]
Any discussion continues in the pull request https://github.com/FreshRSS/FreshRSS/pull/1074
