### ISSUE TITLE
api easy rss & nginx

### ISSUE THREAD

**Issue by lolop-lj** [FreshRSS/FreshRSS#1079]
Bonjour,

je me confronte sûrement à un problème tout bête.

J'essaye de faire tourner mon instance de freshrss dans EasyRss sur fdroid.
J'ai configurer mon nginx et au moment du test de l'api (les deux) j'ai tout simplement une page blanche. Pas d'erreur. Rien dans les log si ce n'est quand j'essaye de me connecter:
`77.154.204.34 - - [16/Feb/2016:23:50:11 +0100] "POST /rss/p/api/greader.php/accounts/ClientLogin HTTP/1.1" 200 5 "-" "Dalvik/1.6.0 (Linux; U; Android 4.1.2; GT-S7390G Build/JZO54K)"`

Et ma configuration nginx un peu fouillis:
`

> # user html;
> 
> worker_processes  1;
> 
> error_log  /var/log/nginx/error_log;
> # error_log  logs/error.log  notice;
> # error_log  logs/error.log  info;
> # pid        logs/nginx.pid;
> 
> events {
>     worker_connections  1024;
> }
> 
> http {
>     include       mime.types;
>     default_type  application/octet-stream;
> server_tokens off;
>     #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
>     #                  '$status $body_bytes_sent "$http_referer" '
>     #                  '"$http_user_agent" "$http_x_forwarded_for"';
> # access_log  /var/log/nginxaccess.log  main if=$log_ip;
> 
> ```
> sendfile        on;
> #tcp_nopush     on;
> 
> #keepalive_timeout  0;
> keepalive_timeout  65;
> 
> #gzip  on;
> ```
> 
>   client_max_body_size 50m;
> 
> ```
> server {
>     listen       80;
>     server_name  lolop.no-ip.org;
> 
>     #charset koi8-r;
> 
>     #access_log  logs/host.access.log  main;
> 
>   root /mnt/data/www;
> ```
> 
>   index index.php index.html index.htm;
> 
>   location ~ .php$ { 
>        fastcgi_pass 127.0.0.1:9000;
>        fastcgi_index index.php;
>        include fastcgi_params;
>        fastcgi_param SCRIPT_FILENAME /mnt/data/www/$fastcgi_script_name;
> }  
>         error_page   500 502 503 504  /50x.html;
>         location = /50x.html {
>             root   /usr/share/nginx/html;
>         }
> 
>  location ^~ /awstats-icon { 
>  alias /usr/share/webapps/awstats/icon/; 
> access_log off; 
> } 
> 
> location ^~ /awstatscss { 
> alias /usr/share/webapps/awstats/examples/css/; 
>  access_log off; 
>  } 
> 
> location ^~ /awstatsclasses { 
>  alias /usr/share/webapps/awstats/examples/classes/; 
> access_log off; 
> } 
> 
> location ~ ^/cgi-bin/.*.(cgi|pl|py|rb) { 
>  gzip off; 
>  fastcgi_pass 127.0.0.1:9000; 
>  fastcgi_index cgi-bin.php; 
>  fastcgi_param SCRIPT_FILENAME /etc/nginx/cgi-bin.php; 
>  fastcgi_param SCRIPT_NAME /cgi-bin/cgi-bin.php; 
>  fastcgi_param X_SCRIPT_FILENAME /usr/share/webapps/awstats$fastcgi_script_name; 
>  fastcgi_param X_SCRIPT_NAME $fastcgi_script_name; 
>  fastcgi_param QUERY_STRING $query_string; 
>  fastcgi_param REQUEST_METHOD $request_method; 
>  fastcgi_param CONTENT_TYPE $content_type; 
>  fastcgi_param CONTENT_LENGTH $content_length; 
>  fastcgi_param GATEWAY_INTERFACE CGI/1.1; 
>  fastcgi_param SERVER_SOFTWARE nginx; 
>  fastcgi_param REQUEST_URI $request_uri; 
>  fastcgi_param DOCUMENT_URI $document_uri; 
>  fastcgi_param DOCUMENT_ROOT $document_root; 
>  fastcgi_param SERVER_PROTOCOL $server_protocol; 
>  fastcgi_param REMOTE_ADDR $remote_addr; 
>  fastcgi_param REMOTE_PORT $remote_port; 
>  fastcgi_param SERVER_ADDR $server_addr; 
>  fastcgi_param SERVER_PORT $server_port; 
>  fastcgi_param SERVER_NAME $server_name; 
>  fastcgi_param REMOTE_USER $remote_user; 
>  }
> 
> location ~ ^/awstats {
>    rewrite ^ http://192.168.1.15/cgi-bin/awstats.pl?config=192.168.1.15;
> }
> 
> location ~ /mnt/data/www/cloud/data/.*$ {allow all;}
> 
> location ~ /mnt/data/www/cloud/data/cache {deny all;}
> 
> location ~ [^/].php(/|$) {
>     fastcgi_split_path_info ^(.+?.php)(/.*)$;
>     if (!-f $document_root$fastcgi_script_name) {
>         return 404;
>     }
> 
> ```
> fastcgi_pass 127.0.0.1:9000;
> fastcgi_index index.php;
> include fastcgi_params;
> ```
> 
> }
> 
> }
> 
> ```
> # another virtual host using mix of IP-, name-, and port-based configuration
> #
> #server {
> #    listen       8000;
> #    listen       somename:8080;
> #    server_name  somename  alias  another.alias;
> 
> #    location / {
> #        root   html;
> #        index  index.html index.htm;
> #    }
> #}
> 
> 
> # HTTPS server
> #
> #server {
> #    listen       443 ssl;
> #    server_name  localhost;
> 
> #    ssl_certificate      cert.pem;
> #    ssl_certificate_key  cert.key;
> 
> #    ssl_session_cache    shared:SSL:1m;
> #    ssl_session_timeout  5m;
> 
> #    ssl_ciphers  HIGH:!aNULL:!MD5;
> #    ssl_prefer_server_ciphers  on;
> 
> #    location / {
> #        root   html;
> #        index  index.html index.htm;
> #    }
> #}
> ```
> 
> }

**Comment by Alkarex** [comment]
Voir peut-être https://github.com/FreshRSS/FreshRSS/issues/957#issuecomment-134388220

**Comment by lolop-lj** [comment]
merci j'arrive a le faire tourner maintenant.

**Comment by Alkarex** [comment]
Super :+1:
