### ISSUE TITLE
Option to dynamically load feed entry content

### ISSUE THREAD

**Issue by ingelres** [FreshRSS/FreshRSS#1081]
Hi,

Currently the content of the articles is always loaded, although it's hidden by default (at least that's the setting I'm using). It would be cool to dynamically load the content when opening the article to:
- Save bandwidth since I don't always open all articles
- Decrease startup time
- Avoid HTTPS mixed content alerts

The last point is what brought me here: I'm using FreshRSS over HTTPS, and get a warning each time an article points to an image that is fetched from the source site over HTTP. Loading dynamically the article content (and thus images as well) would at least mitigate this issue.

**Comment by Alkarex** [comment]
Hello @ingelres 
Yes, that could be an interesting feature. In the meantime:
- We already have a mechanism to load pictures and other dependencies such as `<video>` and `<iframe>` on demand (see "Lazy load" option in FrenshRSS). If there is any remaining case, we can address them.
- I also plan to add a feature for rewriting the URLS of known services (e.g. YouTube) to use their HTTPS version. https://github.com/FreshRSS/FreshRSS/issues/1083

**Comment by ingelres** [comment]
Thanks for your reply.

As for the "Lazy Load" option, it's strange because it's enabled in my settings and I still get the mixed content warning. I've just checked with Firefox network inspector and can see that the only content loaded over HTTP are the pictures included in the articles (that are not opened). When I actually open the article, I can see that the picture is already displayed and that it's not fetched over the network at that moment (no additional request made)

**Comment by Alkarex** [comment]
@ingelres Which version of FreshRSS are you using? If you can, please give a try to the /beta or /dev branch. It is possible that some images are not caught by the Lazy load feature, in which case I would have to fix that.

Before opening an article, if you inspect the DOM with e.g. Firefox, an image should appear like:

``` html
<img lazyload="" postpone="" src="../themes/icons/grey.gif" data-original="http://s2.lemde.fr/image/2016/02/17/644x322/4866932_3_e7f9_il-a-recu-cette-arme-a-columbia-en-caroline-d_8aa2a1226805c1e0c8bb46d258a91f7f.jpg" alt="">
```

**Comment by ingelres** [comment]
I am currently using v1.2.0. Here is a feed for which images are loaded automatically:

http://stephenkingfrance.fr/feed/

This is what the DOM looks like before opening the first article:

`<img src="../themes/icons/grey.gif" data-original="http://stephenkingfrance.fr/wp-content/uploads/2016/02/Ca66OEgXEAAeD9Y.jpg" alt="Ca66OEgXEAAeD9Y" srcset="http://stephenkingfrance.fr/wp-content/uploads/2016/02/Ca66OEgXEAAeD9Y-297x440.jpg 297w, http://stephenkingfrance.fr/wp-content/uploads/2016/02/Ca66OEgXEAAeD9Y-486x720.jpg 486w, http://stephenkingfrance.fr/wp-content/uploads/2016/02/Ca66OEgXEAAeD9Y-270x400.jpg 270w, http://stephenkingfrance.fr/wp-content/uploads/2016/02/Ca66OEgXEAAeD9Y-300x444.jpg 300w, http://stephenkingfrance.fr/wp-content/uploads/2016/02/Ca66OEgXEAAeD9Y.jpg 510w" sizes="(max-width: 510px) 100vw, 510px" lazyload="" postpone="" height="755" width="510">`

But on initial load I still get the mixed content warning, and if I disable Firefox protection against mixed content (by clicking on the lock), I can see in the network tab all the images being fetched immediately without opening any article.

BTW I'm using FF 44.0.2 on Debian Jessie.

**Comment by Alkarex** [comment]
Ah, this is due to `srcset`. See https://github.com/FreshRSS/FreshRSS/issues/1077 with a patch https://github.com/FreshRSS/FreshRSS/pull/1080 (only for the new articles, not the ones already retrieved)

**Comment by Alkarex** [comment]
I have just merged https://github.com/FreshRSS/FreshRSS/pull/1080 in /dev so you can more easily test /dev if you want

**Comment by ingelres** [comment]
I have cloned the git repo and tried the dev version: So now the image isn't loaded on startup, but it's neither loaded when I open the article :-) Instead the alt attribute is shown (Ca66OEgXEAAeD9Y in the case I tested).

**Comment by Alkarex** [comment]
Could you please show the DOM before and after opening the article?

**Comment by ingelres** [comment]
Before :

`<img src="../themes/icons/grey.gif" data-original="http://stephenkingfrance.fr/wp-content/uploads/2016/02/Ca66OEgXEAAeD9Y.jpg" alt="Ca66OEgXEAAeD9Y" sizes="(max-width: 510px) 100vw, 510px" lazyload="" postpone="" height="755" width="510">`

After :

`<img src="http://stephenkingfrance.fr/wp-content/uploads/2016/02/Ca66OEgXEAAeD9Y.jpg" alt="Ca66OEgXEAAeD9Y" sizes="(max-width: 510px) 100vw, 510px" lazyload="" postpone="" height="755" width="510">`

This looks correct to me, but still FF seems to display grey.gif in a much larger size (I guess the size of the actual image after loading) and when I right-click on the image and choose "view image" (after opening the article), I'm taken to "p/themes/icons/grey.gif".

I've tested with Chrome and everything seems to be fine there: The image is indeed loaded only when I open the article and it displays fine then.

**Comment by Alkarex** [comment]
Maybe a bug in Firefox because I left the `sizes` attribute

**Comment by Alkarex** [comment]
@ingelres I have now filtered `sizes` too. Let me know if you can see any difference on new articles.
It works well when I test http://stephenkingfrance.fr/feed/atom/

**Comment by ingelres** [comment]
I updated my repo and now Firefox correctly loads the image and only when I open the article. Thanks!

**Comment by Alkarex** [comment]
Very good :-) Although we do not load the text dynamically, the dynamic loading of images/videos/sounds/iframes does a part of the job. For the startup time, it is possible to decrease the number of articles to load, and FreshRSS will auto-load the rest. So I close for now.

**Comment by Alkarex** [comment]
@ingelres I have added in /dev an option to provide a list of HTTPS domains for which to always use HTTPS:
https://github.com/FreshRSS/FreshRSS/blob/dev/data/force-https.default.txt
And you can supplement it with your own list in a new file  `./data/force-https.txt`.
For instance, YouTube videos embedded as HTTP will be re-written as HTTPS.
If you can, please test /dev while keeping an eye on the third-party dependencies that gets loaded.
