### ISSUE TITLE
Error 403 - Forbidden - You don’t have permission to access this page

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [FreshRSS/FreshRSS#1082]
So, everything installed fine according to the log. But when I try to log in I'm always getting:

https://i.imgur.com/V4g9gkY.png

What's going on?

**Comment by Alkarex** [comment]
Hello,
Please provide some information about FreshRSS version as well as platform.
In `./data/config.php`, set `'auth_type' => 'none',` and then try to change your password and login method from the Web interface again.

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/issues/960

**Comment by Labo9** [comment]
> 'auth_type' => 'none',

This worked for me !

**Comment by SoWhatI** [comment]
这可以让你进入页面，但是无法修改密码，因为修改密码需要旧密码，我有一个方法，在用户管理页面新增一个临时的管理员用户，使用新建用户登录，然后在用户管理页面可更新原来用户的密码
