### ISSUE TITLE
ansible role to deploy FreshRSS automatically

### ISSUE THREAD

**Issue by oupala** [FreshRSS/FreshRSS#1090]
I'm working on an ansible role to deploy FreshRSS automatically.

With the current version of my role, I can deploy FreshRSS automatically, but I still have to do some post-install manual operations using the web interface. I'd like to automatize these operations so that FreshRSS works out of the box.

The manual operations are - up to now - the following:
- set the token (which is used for the API **and** for the cronjob)
- set the cronjob (with the previously defined token)
- import the feed list in OPML

I can see that the token is defined **unciphered** in `FreshRSS/data/users/<username>/config.php`, under the `token` key. I find it **not very secure**, but it can at least be set by ansible. However, I think it would be better to set this token using a FreshRSS API so that ansible doesn't bypass FreshRSS.

How can I import an OPML file programmatically?

Generally speaking, is there a way to access the FreshRSS API so that I can set the token, import the feeds list?

**Comment by Alkarex** [comment]
Hello @oupala 
- The token is neither used by the API (which uses `apiPasswordHash`) nor the local cron (which uses nothing). You do not need to set the token at all (but it is fine if you do), and can let each user do it when they need it (we should do a button for suggesting a new token instead of letting the user typing something random - please file a new issue if you need that).
- The (local) cronjob does not need any token. Here is the content of my own `/etc/cron.d/FreshRSS` on Ubuntu:

```
MAILTO=root
3,33 * * * * www-data php -f /path/to/FreshRSS/app/actualize_script.php > /tmp/FreshRSS.log 2>&1
```
- OPML from the command line is related to https://github.com/FreshRSS/FreshRSS/issues/1039 I will think about a solution.
- By the way, you do not talk about other fields that need to be customized, such as the password, API password, salt, base_url...

**Comment by oupala** [comment]
Concerning the crontab, I'm using the following crontab:

``` crontab
0 * * * * curl --insecure 'https://127.0.0.1/rss/i/?c=feed&a=actualize&token=fq6r9m8aO8' -O /tmp/freshrss.cron
```

I see that you're not using the network and that you directly calling a php script. Is there any advantage using one solution or another? In my solution, you can see that the token is needed.

**Comment by oupala** [comment]
Concerning the API, I'm pretty sure that I configured the token as the password in EasyRSS. I think that EasyRSS is using the API (the greader.php API). Am I wrong?

**Comment by oupala** [comment]
And finally, I obviously need to customize all the parameters configured at install time, and more generally all the parameters that can be configured.

This is a requirement in order to get an automatically installable instance of FreshRSS, using Ansible or any other deployment solution.

FreshRSS has to be scriptable in order to be embedded in automatic deployment recipes.

Currently, I'm only automatically installing all components around FreshRSS, but not really FreshRSS itself. I'm installing apache, sqlite, php5-curl, php5-gmp and mod_rewrite (for EasyRSS). Installation of FreshRSS is limited to cloning the git repo. That's not bad, but that's not enough to make FreshRSS working **and configured** out of the box.

**Comment by Alkarex** [comment]
EasyRSS is using the Google Reader API indeed, and the login password is compared with `apiPasswordHash` (which is a hashed version of the API password), not the token.

I would very much recommend a local cron instead of a network one. The local cron will not suffer from timeouts, can refresh all users at once, uses fewer resources, and does not need the token.

**Comment by oupala** [comment]
To clarify, I've listed three different authentication strings:
- the main user password
- the API password
- the token

In my case, I think that I've set the same string for the API password and for the token.

All these strings should be settable by the CLI.

**Comment by oupala** [comment]
I switched the ansible role to use a local cron.

**Comment by Alkarex** [comment]
Feel free to re-open if needed

**Comment by oupala** [comment]
I really need the CLI interface in order to configure FreshRSS using an ansible role.

I would need to set:
- the password
- API password
- salt
- base_url
- import OPML feeds

PS : I cannot re-open the issue by myself.

**Comment by Alkarex** [comment]
I believe what you ask is covered by this other issue https://github.com/FreshRSS/FreshRSS/issues/1095

**Comment by oupala** [comment]
Right, I'll watch this issue.

**Comment by Alkarex** [comment]
Draft of implementation in https://github.com/FreshRSS/FreshRSS/pull/1338
Comments welcome there

**Comment by Alkarex** [comment]
I believe all the features you have asked are now implemented in https://github.com/FreshRSS/FreshRSS/pull/1338 :-)

**Comment by oupala** [comment]
The ansible role is now ready to be published.

Would you be interested in publishing it somewhere? If yes, where?

**Comment by Alkarex** [comment]
It sounds good, @oupala 👍 
How many files is there?
We could consider making a repository on https://github.com/FreshRSS/ with write access for you, especially if you believe you could maintain it a bit over time.

**Comment by oupala** [comment]
There is between 1 and 5 files, depending on how configurable the ansible role is.

The core of the role is in one file. Other files serve as configuration, integration, dependencies...

My problem is that my role is actually part of a bigger playbook with many many roles.

I can either publish the role as snippets (in this case, it is just a source of inspiration, I have no real need to maintain it), or try to publish it as a real independant role (and in this case I think I should better maintain it).

My main problem is that I won't be a user of this independant role, at least for the moment. And it's hard to maintain something you don't use...

What's your point of view?

**Comment by Alkarex** [comment]
Ok. I think it is best to focus on what you use and maintain, and link to that.

**Comment by oupala** [comment]
Ok, so it's maybe better to start by some snippets, then maybe one day convert it to an ansible role that could even be published on the official ansible repo : ansible galaxy.

It is possible to add snippets to a project or to a group? Is **gist** the GitHub name of snippets ? Or should you add a regular directory named ansible into the FreshRSS repo with my snippets inside?

What's your opinion?

**Comment by Alkarex** [comment]
The main options I see are:
1. Link to the place where you will have your larger project
2. Put short snippets in the [FreshRSS documentation](https://github.com/FreshRSS/documentation)
3. New repository on e.g. https://github.com/FreshRSS (like `https://github.com/FreshRSS/FreshRSS-Ansible`)
    * This last option would probably scale better for an Ansible role.
    * It would be nice if you could consider having the FreshRSS part of your project there, and import it in your larger project via e.g. Git Submodules or similar https://github.com/blog/2104-working-with-submodules
      * This would probably have the best maintainability, if you use it yourself
