### ISSUE TITLE
500 error when importing if php-json is not installed.

### ISSUE THREAD

**Issue by plietar** [FreshRSS/FreshRSS#1092]
Hi,
I was trying to import feeds from another FreshRSS instance, but got a 500 error and the following in the logs :

```
2016/02/24 18:18:21 [error] 8#0: *2 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot use object of type stdClass as array in /opt/freshrss/app/Controllers/importExportController.php on line 337" while reading response header from upstream, client: 172.28.128.1, server: localhost, request: "POST /i/?c=importExport&a=import HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "172.28.128.3:82", referrer: "http://172.28.128.3:82/i/?c=importExport"
```

It turns out that because I am missing the php-json module, a [substitute is used](https://github.com/FreshRSS/FreshRSS/blob/339e324/lib/lib_rss.php).
`JSON::decode` from `JSON.php` returns an object rather than an array. `json_decode` then converts it into an array, but only for the top level object, not recursively, hence the error.
When php-json is installed, everything works fine.

I don't know what the best action would be :
- Fix `json_decode` by honoring the `$assoc` argument recursively.
- Don't convert the object to an array at all, and use object member access instead of indexing
- Disable importing when php-json is missing
- Make php-json a hard requirement, and remove the substitute version

For reference, here are my specs:

```
nginx version: nginx/1.8.1
PHP 5.6.17 (cli) (built: Jan 24 2016 22:39:03)
FreshRSS 1.3.0-beta
```

A quick glance at the commit history suggests that this hasn't changed since the beta.

**Comment by Alkarex** [comment]
Thanks for the bug report @plietar . Would you be so kind as to try this patch? https://github.com/FreshRSS/FreshRSS/issues/1093 (not tested at all)

**Comment by plietar** [comment]
Thanks, this worked on a small import.
It is however very slow, and times out on a bigger import (3.8M unzipped), but I guess there's nothing that can be done other than installing `php-json`

**Comment by Alkarex** [comment]
Thanks for the feedback @plietar 
Was it much faster with php-json?

**Comment by plietar** [comment]
Yes, it is instantaneous with php-json, whereas JSON.php hits the 30 seconds timeout

**Comment by Alkarex** [comment]
Ok, thanks. If you have time, it would be great if you could make a PR adding a warning during install :-)
https://github.com/FreshRSS/FreshRSS/blob/dev/app/install.php#L310
https://github.com/FreshRSS/FreshRSS/blob/dev/app/install.php#L531

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/1097
