### ISSUE TITLE
FreshRSS command line

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#1095]
Command line entry point allowing a few things such as:
- [x] Initial setup https://github.com/FreshRSS/FreshRSS/issues/1090
- [x] Create new user https://github.com/FreshRSS/FreshRSS/issues/1090
- [x] Import OPML https://github.com/FreshRSS/FreshRSS/issues/1090
- [x] Export OPML https://github.com/FreshRSS/FreshRSS/issues/1039 https://github.com/FreshRSS/FreshRSS/issues/1277
- [x] Actualize a user
- [x] Do not insert default feeds during user create (do that by OPML import instead)

**Comment by Alkarex** [comment]
Related to https://github.com/FreshRSS/FreshRSS/issues/956 https://github.com/FreshRSS/FreshRSS/pull/1070 https://github.com/FreshRSS/FreshRSS/pull/963 https://github.com/FreshRSS/FreshRSS/issues/833

**Comment by aledeg** [comment]
I think it's a really good idea. And actually, it will probably a good idea to restructure the project as well.
We could design an API that could be reused both in the CLI tool and in the controllers.
It will also give the opportunity to third party clients to behave the same way as the application does.

See  #956

**Comment by Alkarex** [comment]
@aledeg There is a little bit of refactoring in 1.6 already, in order to support new API functions (`addFeed(), actualizeFeed()`), but not as ambitious as what you wrote https://github.com/FreshRSS/FreshRSS/pull/1261

**Comment by Alkarex** [comment]
Draft of implementation in https://github.com/FreshRSS/FreshRSS/pull/1338
Comments welcome there

**Comment by Alkarex** [comment]
* [ ] Do not insert default feeds during user create (do that by OPML import instead)
* [ ] Actualize a user

**Comment by Alkarex** [comment]
The initial version of the CLI is completed

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/issues/1328
