### ISSUE TITLE
Hi,is support ended for FreshRSS

### ISSUE THREAD

**Issue by GaneshKandu** [FreshRSS/FreshRSS#1100]
Hi,is support ended for FreshRSS??
or is it stable

**Comment by Alkarex** [comment]
Hello,
I am not sure to understand your question:
We have 3 branches: master, beta, dev. Pick the one most appropriate for you:
https://github.com/FreshRSS/FreshRSS/blob/dev/README.md#note-on-branches

**Comment by GaneshKandu** [comment]
OK! Thax to Reply 
Which one is stable??

**Comment by GaneshKandu** [comment]
Thank you ! :smile: :+1:
