### ISSUE TITLE
FreshRSS blank page

### ISSUE THREAD

**Issue by mangepatate** [FreshRSS/FreshRSS#1101]
Hello,

I used FreshRSS for now almost one year on my Raspberry Pi with Raspbian Wheezy. Yesterday I updated to Raspbian Jessie, and since then when I attemps to access FreshRSS i have an empty page with no error message.
I checked the files in /var/www/ and the authorisations of this folder, no problem. I checked the Nginx sites-enabled file, no problem. I also checked my install of php5 and nothing more.

Does somebody have an idea to solve this issue ?

**Comment by Alkarex** [comment]
Brief message from mobile: try to set the environment variable to development in config.php to have more error messages.
Which version of FreshRSS? You can try to make a copy and test the current /dev

**Comment by Alkarex** [comment]
P.S. Ensure that your PHP config is set to log errors, and check both Fresh RSS logs and your Web server logs

**Comment by mangepatate** [comment]
Hello Alkarex, thanks for the ideas :-) I'm using the 1.1.2-beta version. As I'm quite a noob in Linux and web hosting, I'll search in the logs. 

For the config.php file, it currently contain the following lines :

```
<?php
 return array (
  'salt' => 'a668adca************1242cc823fbf1fec',
  'base_url' => 'http://192.168.1.xx/p',
  'title' => 'FreshRSS',
  'default_user' => '*****',
  'auth_type' => 'form',
  'db' => 
  array (
    'type' => 'mysql',
    'host' => 'localhost',
    'user' => 'root',
    'password' => '*******',
    'base' => 'freshrss',
    'prefix' => 'freshrss_',
    'pdo_options' => 
    array (
    ),
  ),
  'pubsubhubbub_enabled' => true,
);
```

I read the documentation on the freshrss.org website but did not found what to write to switch to dev version, could you help me with that ?

**Comment by Alkarex** [comment]
Just add a line `'environment' => 'development',` for instance just below your line `salt`

**Comment by mangepatate** [comment]
Thanks.

I think I found one problem, when I read the error.log of Nginx I have this line many times and date matches the update of the os :
`2016/03/03 19:12:00 [error] 691#0: *14 open() "/var/www/FreshRSS/favicon.ico" failed (2: No such file or directory), client: 192.168.1.46, server: , request: "GET /favicon.ico HTTP/1.1", host: "192.168.1.6"`

I also read the /var/log/php5-fpm.log file, it says that everything is ok with php.

When I go in the /var/www/FreshRSS/ I do not have a favicon.ico file, so maybe that could cause me trouble ?

**Comment by Alkarex** [comment]
No, the favicon is not the problem. But in your Web server config, the root should be the `./FreshRSS/p/` directory, not directly `./FreshRSS/`

**Comment by Alkarex** [comment]
You can maybe search for nginx tips in https://github.com/FreshRSS/FreshRSS/search?q=Nginx&type=Issues

**Comment by Alkarex** [comment]
Feel free to re-open if needed.
For the record, alternatives includes using Apache2, or using automatic installations such as via DPlatform or YunoHost which will do the configuration for you https://github.com/FreshRSS/FreshRSS/tree/dev#automated-install
