### ISSUE TITLE
Dutch translation 1.2.0

### ISSUE THREAD

**Issue by Wanabo** [FreshRSS/FreshRSS#1103]
I noticed some changes from version 1.1.3-dev to 1.2.0.
It only affects the translations files admin.php and gen.php

I submitted a complete branch 1.2.0 Dutch translation files on my account on Github.
See, https://github.com/Wanabo/FreshRSS-Dutch-translation

**Comment by Alkarex** [comment]
Thanks @Wanabo.
It would be great if you could make a pull request against the current /dev version (not many changes since 1.2).

**Comment by Alkarex** [comment]
Replaced by https://github.com/FreshRSS/FreshRSS/pull/1108
