### ISSUE TITLE
Missing loader.gif called in p\themes\base-theme\templates.css

### ISSUE THREAD

**Issue by Wanabo** [FreshRSS/FreshRSS#1104]
Noticed loader.gif is missing in p\themes\base-theme\
File p\themes\base-theme\templates.css:
`.loading {
    background: url("loader.gif") center center no-repeat;
    font-size: 0;
}`

I use this one on my site: http://www.nieuwskop.be/p/themes/base-theme/loader.gif
![Image of loader](http://www.nieuwskop.be/p/themes/base-theme/loader.gif)

**Comment by Alkarex** [comment]
Thanks. Even though the base-theme is not supposed to be used directly, it is probably a good idea to include `loader.gif` indeed. If you can, please make a pull request to /dev with a copy of `loader.gif` from the Origine theme. Otherwise I will do it later.

**Comment by Alkarex** [comment]
P.S. If you are not familiar with pull requests, this simple one would be a good example to get started :-)

**Comment by Wanabo** [comment]
Well I believe I just did my first pull request ever. Hope it is okay.
https://github.com/FreshRSS/FreshRSS/pull/1106

**Comment by Alkarex** [comment]
Hello @Wanabo 
It is almost good. Please try again by selecting /dev as the target for the pull request, instead of /beta

**Comment by Wanabo** [comment]
Tried again. https://github.com/FreshRSS/FreshRSS/pull/1107

**Comment by Alkarex** [comment]
Almost :-) Now it is "into dev from beta". It needs to be "into dev from dev" :-)
You can see that it works when there is an indication that your pull request can be merged without conflict.

**Comment by Alkarex** [comment]
So on your side (your "fork"), you must add the "loader.gif" file when you are on your /dev branch.

**Comment by Wanabo** [comment]
Okay, I didn't forked FreshRSS. Now I have and created a pull request.
Indeed I had a green line stating there where no conflicts.

I have updated Dutch language for 1.3.1 as well but in my own repository. I'll update the translation in my fork as well en try a pull request.

**Comment by Alkarex** [comment]
Very good. Now I can merge it :+1: https://github.com/FreshRSS/FreshRSS/pull/1108

To do it even better next time, after the fork, you make a new branch from /dev on your side (so you do not work on your /dev), with the purpose of having only the changes for one thing: e.g. you make a new branch for the Dutch translation, another branch for the loader.gif bug. Then you make one pull request for each. When your branches gets accepted/merged, you will have a menu offering you to delete your local branch.

**Comment by Wanabo** [comment]
Github is complex to a newbie Github user.

Ok thanks for the guidance. Will my fork of FreshRSS automatically be 
updated with the source?

**Comment by Alkarex** [comment]
Indeed, the git branch workflow can be disturbing at first, but is very efficient.

As explained, it is best if you make all changes in your own branches (branched from /dev). You can give them any name, but best something a bit meaningful (e.g. "loader-gif-bug").

If you use the Web interface of GitHub, you can update your local copy of /dev using the "compare" feature, and making sure the original FreshRSS is used as "head":

![github](https://cloud.githubusercontent.com/assets/1008324/13553865/b375513c-e397-11e5-86aa-f94ba3901bbd.png)

Otherwise, there is also a desktop client https://desktop.github.com/ and finally, there is also a command line for more advanced functionalities.

**Comment by Wanabo** [comment]
Thank you for the clarification.
