### ISSUE TITLE
proposed change, allow robots /searchengines in v1.2.0

### ISSUE THREAD

**Issue by Wanabo** [FreshRSS/FreshRSS#1105]
Changelog 2015-11-03 FreshRSS 1.2.0 / 1.3.0-beta
- New option to allow robots / search engines #938 

In version 1.2.0 these lines of code was introduced in app/layout/layout.phtml
`<?php if (FreshRSS_Context::$system_conf->allow_robots) { ?>
        <meta name="description" content="<?php echo htmlspecialchars(FreshRSS_Context::$name . ' | ' . FreshRSS_Context::$description, ENT_COMPAT, 'UTF-8'); ?>" />
<?php } else { ?>
        <meta name="robots" content="noindex,nofollow" />
<?php } ?>
`
I think these lines of code are better and do exactly what allow_robots must do:
`<?php if (FreshRSS_Context::$system_conf->allow_robots) { ?>
        <meta name="robots" content="index, follow" />
<?php } else { ?>
        <meta name="robots" content="noindex, nofollow" />
<?php } ?>
`

If you want keywords and description you can try my solution: (improvements are welcome)
`<meta name="description" content="<?php echo trim(htmlspecialchars_decode(substr(self::title(), ($pos = strpos(self::title(), ')')) !== false ? $pos + 1 : 0))); ?>" />
        <meta name="keywords" content="<?php echo str_ireplace(array(' ',', ·, ', ':', ', , , ', ', &amp;, '), ', ', trim(substr(self::title(), ($pos = strpos(self::title(), ')')) !== false ? $pos + 1 : 0))); ?>" />
`

**Comment by Alkarex** [comment]
Hello @Wanabo,
`<meta name="robots" content="index, follow" />` is superfluous since those are just the default settings.
Please explain what you would like to achieve with the meta description.

**Comment by Wanabo** [comment]
You are right about index and follow are superfluous. https://googlewebmastercentral.blogspot.nl/2007/03/using-robots-meta-tag.html

> By default, Googlebot will index a page and follow links to it. So there's no need to tag pages with content values of INDEX or FOLLOW.

Then I suggest to change allow_robots to **generate_auto_description** and **generate_auto_keywords**
And for the purpose of preventing indexing your site to keep it private add **deny_robots**

I'm no SEO expert but I believe it helps. If the general opinion is that description and keywords are not relevant than leave it with **deny_robots** and do nothing else.

What I would like to achieve is this:
**generate_auto_description** 
1- home page -> description of the site, manually entered somewhere (config.php)
2- in Subscriptions management add a field for description of the categorie and use this as meta description. Will be used when clicking a category.
3- In Subscriptions management there is al ready a feed description, use this as meta description when a feed source is clicked in a category.
4- When an article is clicked, take the first 150 characters / 20 words of the text and use this as meta description.

**generate_auto_keywords**

1- as above but now for keywords
2- as above but now for keywords
3- as above but now for keywords
4- as above but now for keywords, max 20 keywords and filter out common words and very small words.

**Comment by Alkarex** [comment]
@Wanabo 

For the meta description:
1. I have implemented a `meta_description` option https://github.com/FreshRSS/FreshRSS/pull/1294 - Please give it a try
2. This would require a new database field, additional UI and translations, which is something I am reluctant to do for small features; Categories already have a title which is used in the meta description. Feel free to open another ticket if this important for you. I would welcome a pull request, but do not plan on implementing more of that myself in the near future.
3. This is already the case.
4. FreshRSS currently does not have landing pages per articles: only the main view, the categories, and the feeds.

For the meta keywords, as explained in https://github.com/FreshRSS/FreshRSS/issues/938#issuecomment-127051876 , it is not worth putting energy into it. Keywords are extracted by search engines from the real content of the page, not from the meta keywords anymore.

**Comment by Alkarex** [comment]
Done?
