### ISSUE TITLE
Call for testing /dev before 1.3.1-beta

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#1113]
Hello all FreshRSS users,
The upcoming version 1.3.1-beta is now ready to be tested from the /dev branch
https://github.com/FreshRSS/FreshRSS/milestones/1.3.1-beta

The last call for testing was in October https://github.com/FreshRSS/FreshRSS/issues/1017 and it is more than time for a new round :-)

Thanks to all of you who have reported bugs and helped fixed them, or have contributed with new features. Please check the /dev branch if you can, focussing on the bugs / features you have been involved in: @marienfressinaud @aledeg @Wanabo @ealdraed @Tets42 @plietar @oupala @hckweb @Angristan @danc @barbuslex @jjk-jacky @plarus @purexo @edhelas @seboss666 @Cyrixo @mangepatate etc. :+1: 

Edit: changes are listed on https://github.com/FreshRSS/FreshRSS/blob/dev/CHANGELOG.md

**Comment by Wanabo** [comment]
First impression. Udated from 1.2.0 to 1.3.1-dev. Site is working. At first glance no visable errors.
When using console mode in FireFox I get warnings and errors!
`Content Security Policy: Couldn't process unknown directive 'child-src' <unknown>
FreshRSS immediate init… main.js:1344:3
FreshRSS init done. main.js:1338:3
Content Security Policy: The page's settings blocked the loading of a resource at self ("default-src http://www.nieuwskop.be").`

FireFox html validator:

`line 306 column 48 - Error: Element “a” is missing one or more of the following attributes: “role”.
line 311 column 48 - Error: Element “a” is missing one or more of the following attributes: “role”.
line 316 column 48 - Error: Element “a” is missing one or more of the following attributes: “role”.
line 321 column 49 - Error: Element “a” is missing one or more of the following attributes: “role”.
`
example: `<a class="no-mobile" href=".?c=configure&amp;a=queries"><img class="icon" src="../themes/icons/configure.svg" alt="⚙" /></a>`

**Comment by Alkarex** [comment]
Thanks for the quick feedback @Wanabo.
Some of the CSP warnings are expected (new security feature). The warning `unknown directive 'child-src'` will disappear when you update your browser (e.g. Firefox 45 https://developer.mozilla.org/en-US/Firefox/Releases/45#Security ). But please let me know if there are some things that are blocked, which should not have been blocked.
The rest are ARIA warnings regarding accessibility (we have almost no ARIA so far).

**Comment by Wanabo** [comment]
I think not. Also checked with Chrome, but there were no CSP warnings or errors.

For what it is worth (I know html validator is not perfect) below a list of errors and warnings.

`Result: 67 errors / 0 warnings

Info: W3c Online Validation

line 16 column 134 - Error: Bad value “icon msapplication-TileImage apple-touch-icon” for attribute “rel” on element “link”: The string “msapplication-tileimage” is not a registered keyword.
line 308 column 35 - Error: Element “a” is missing one or more of the following attributes: “role”.
line 313 column 35 - Error: Element “a” is missing one or more of the following attributes: “role”.
line 318 column 35 - Error: Element “a” is missing one or more of the following attributes: “role”.
line 323 column 36 - Error: Element “a” is missing one or more of the following attributes: “role”.
line 419 column 131 - Error: Attribute “lazyload” not allowed on element “img” at this point.
line 419 column 131 - Error: Attribute “postpone” not allowed on element “img” at this point.
line 445 column 241 - Error: Attribute “lazyload” not allowed on element “img” at this point.
line 445 column 241 - Error: Attribute “postpone” not allowed on element “img” at this point.
line 445 column 527 - Error: Attribute “lazyload” not allowed on element “img” at this point.
line 445 column 527 - Error: Attribute “postpone” not allowed on element “img” at this point.
line 478 column 131 - Error: Attribute “lazyload” not allowed on element “img” at this point.
line 478 column 131 - Error: Attribute “postpone” not allowed on element “img” at this point.
line 504 column 232 - Error: Attribute “lazyload” not allowed on element “img” at this point.
line 504 column 232 - Error: Attribute “postpone” not allowed on element “img” at this point.
line 504 column 561 - Error: Attribute “lazyload” not allowed on element “img” at this point.
line 504 column 561 - Error: Attribute “postpone” not allowed on element “img” at this point.
line 537 column 131 - Error: Attribute “lazyload” not allowed on element “img” at this point.
line 537 column 131 - Error: Attribute “postpone” not allowed on element “img” at this point.
line 563 column 131 - Error: Attribute “lazyload” not allowed on element “img” at this point.
line 563 column 131 - Error: Attribute “postpone” not allowed on element “img” at this point.
line 589 column 131 - Error: Attribute “lazyload” not allowed on element “img” at this point.
line 589 column 131 - Error: Attribute “postpone” not allowed on element “img” at this point.
line 615 column 131 - Error: Attribute “lazyload” not allowed on element “img” at this point.
line 615 column 131 - Error: Attribute “postpone” not allowed on element “img” at this point.
line 641 column 131 - Error: Attribute “lazyload” not allowed on element “img” at this point.
line 641 column 131 - Error: Attribute “postpone” not allowed on element “img” at this point.
line 667 column 131 - Error: Attribute “lazyload” not allowed on element “img” at this point.
line 667 column 131 - Error: Attribute “postpone” not allowed on element “img” at this point.
line 693 column 231 - Error: Attribute “lazyload” not allowed on element “img” at this point.
line 693 column 231 - Error: Attribute “postpone” not allowed on element “img” at this point.
line 693 column 543 - Error: Attribute “lazyload” not allowed on element “img” at this point.
line 693 column 543 - Error: Attribute “postpone” not allowed on element “img” at this point.
line 726 column 252 - Error: Attribute “lazyload” not allowed on element “img” at this point.
line 726 column 252 - Error: Attribute “postpone” not allowed on element “img” at this point.
line 726 column 575 - Error: Attribute “lazyload” not allowed on element “img” at this point.
line 726 column 575 - Error: Attribute “postpone” not allowed on element “img” at this point.
line 759 column 131 - Error: Attribute “lazyload” not allowed on element “img” at this point.
line 759 column 131 - Error: Attribute “postpone” not allowed on element “img” at this point.
line 785 column 131 - Error: Attribute “lazyload” not allowed on element “img” at this point.
line 785 column 131 - Error: Attribute “postpone” not allowed on element “img” at this point.
line 811 column 451 - Error: Bad value “120px” for attribute “width” on element “img”: Expected a digit but saw “p” instead.
line 811 column 451 - Error: Attribute “lazyload” not allowed on element “img” at this point.
line 811 column 451 - Error: Attribute “postpone” not allowed on element “img” at this point.
line 837 column 255 - Error: Bad value “120px” for attribute “width” on element “img”: Expected a digit but saw “p” instead.
line 837 column 255 - Error: Attribute “lazyload” not allowed on element “img” at this point.
line 837 column 255 - Error: Attribute “postpone” not allowed on element “img” at this point.
line 863 column 131 - Error: Attribute “lazyload” not allowed on element “img” at this point.
line 863 column 131 - Error: Attribute “postpone” not allowed on element “img” at this point.
line 884 column 168 - Error: Forbidden code point U+0092.
line 884 column 209 - Error: Forbidden code point U+0092.
line 888 column 166 - Error: Forbidden code point U+0092.
line 888 column 207 - Error: Forbidden code point U+0092.
line 889 column 175 - Error: A numeric character reference expanded to the C1 controls range.
line 889 column 221 - Error: A numeric character reference expanded to the C1 controls range.
line 889 column 275 - Error: A numeric character reference expanded to the C1 controls range.
line 889 column 321 - Error: A numeric character reference expanded to the C1 controls range.
line 889 column 365 - Error: Bad value “120px” for attribute “width” on element “img”: Expected a digit but saw “p” instead.
line 889 column 365 - Error: Attribute “lazyload” not allowed on element “img” at this point.
line 889 column 365 - Error: Attribute “postpone” not allowed on element “img” at this point.
line 915 column 370 - Error: Bad value “120px” for attribute “width” on element “img”: Expected a digit but saw “p” instead.
line 915 column 370 - Error: Attribute “lazyload” not allowed on element “img” at this point.
line 915 column 370 - Error: Attribute “postpone” not allowed on element “img” at this point.
line 941 column 232 - Error: Attribute “lazyload” not allowed on element “img” at this point.
line 941 column 232 - Error: Attribute “postpone” not allowed on element “img” at this point.
line 941 column 554 - Error: Attribute “lazyload” not allowed on element “img” at this point.
line 941 column 554 - Error: Attribute “postpone” not allowed on element “img” at this point.
`

**Comment by danc** [comment]
So far so good.
Clean install on debian8, no issue.
sharing with “Journal du Hacker” #1056 ok

**Comment by Alkarex** [comment]
Merci @danc :+1:

**Comment by Alkarex** [comment]
Thanks @plarus
