### ISSUE TITLE
Issue to add Espacenet patents rss feed

### ISSUE THREAD

**Issue by techexo** [FreshRSS/FreshRSS#1121]
Hi,

I have problems adding the following RSS feed : 
http://worldwide.espacenet.com/websyndication/searchFeed?IC=C07D487%2F04+C12Q1%2F66

The error is 

> A feed could not be found at `http://worldwide.espacenet.com/websyndication/searchFeed?IC=C07D487%2F04+C12Q1%2F66`; the status code is `200` and content-type is `application/xhtml+xml;charset=UTF-8` [http://worldwide.espacenet.com/websyndication/searchFeed?IC=C07D487%2F04+C12Q1%2F66] 

It seems that the rss feed is not perfectly valid (miss http:// before various uri), but is there any way to add it anyway, as the `<rss></rss>` seems to be ok? I will try to find how to submit a reclamation to espacenet, but as it is a European office, I reckon that it will be quite long to see any modification...

Thanks in advance, do not hesitate to ask further informations if needed. :)

Best regards

**Comment by techexo** [comment]
A copy of the formal complaint to the European Patent Office:

> Topic_: Online services / software
> Reason for complaint_: The RSS feed given by Espacenet is not valid according to W3C rules and some software consequently deny adding them, making them impossible to use for scientific monitoring. For example with the RSS feed related to CIB:A01B1/02, https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fworldwide.espacenet.com%2Fwebsyndication%2FsearchFeed%3FAB%3D%26AP%3D%26CPC%3D%26DB%3DEPODOC%26IC%3DA01B1%252F02%26IN%3D%26PA%3D%26PD%3D%26PN%3D%26PR%3D%26ST%3Dadvanced%26Submit%3DRECHERCHE%26TI%3D%26locale%3Dfr_EP The main problem is the URLs that are not valid (missing "http:" or "https:" before the "//" in the URLs) and the media type that is weird for a rss feed (application/xhtml+xml). Thanks in advance for considering the issue and thus allowing everyone to efficiently monitor the patents. Yours faithfully.

If there is a way for FreshRSS to bypass the issue, it would be greatly appreciated (by me at least ;)).

Bests

**Comment by techexo** [comment]
The answer from EPO 

> We make reference to your complaint submitted on 18.03.2016 in which you draw our attention to an issue related to the RSS feed provided in Espacenet. We thank you very much for this feedback and we would like to inform you that the Office is well aware of this problem and the competent technical department is already working on a solution to it. In the meantime, it may be helpful for you to know that the current protocol agnostic approach works suitably with Chrome and Outlook.

I am wondering however what is the "protocol agnostic approach" is, and if it can be supported by FreshRSS without to much pain. I will be glad to test that if needed. Thanks in advance!

**Comment by Alkarex** [comment]
The "protocol agnostic" is the use of // in the links instead of e.g.
http:// or https://
I have not had a chance to look at the problem(s) yet, but I do not think
this is the issue (FreshRSS should support such links)

**Comment by Alkarex** [comment]
P.S. The main problem is that the feed is served with a wrong mime type
(application/xhtml+xml instead of one of the RSS mime types), but even when
forcing the feed it does not work due to other problems I have not
investigated yet

**Comment by Alkarex** [comment]
Hello again,
Please try to use the `#force_feed` trick to force the parsing as RSS even though the page is served as HTML (see https://github.com/FreshRSS/FreshRSS/issues/456#issuecomment-62807209 )
Like so `http://worldwide.espacenet.com/websyndication/searchFeed?IC=C07D487%2F04+C12Q1%2F66#force_feed`
Before doing that, you might have to clear your `./FreshRSS/data/cache/*.spc`.
Please let me know if it works for you.

**Comment by techexo** [comment]
It worked great, without the need the clear the cache or anything! Thank you so much for the fix and your reactivity :)
