### ISSUE TITLE
Auto upgrade not working. 

### ISSUE THREAD

**Issue by calaad** [FreshRSS/FreshRSS#1122]
Hi, 

I use version 1.3.0-beta of FreshRSS and i want to upgrade to 1.3.1-beta. 

Using auto update tool, it show me an error : 
"Arf ! Le serveur de mise à jour n’a pas été trouvé. [https://update.freshrss.org?v=1.3.0-beta] "

Error log show : 
"Error during update (HTTP code 0): error setting certificate verify locations:"

No error in apache logs. 

When i manually test "curl https://update.freshrss.org?v=1.3.0-beta" from server, it works, the web page is found and readable. 

Rights on files seems good, Installation checking is all green. I don't use proxy or something like that...

**Comment by Alkarex** [comment]
Hello,
Could you please try
http://stackoverflow.com/questions/3160909/how-do-i-deal-with-certificates-using-curl-while-trying-to-access-an-https-url

**Comment by calaad** [comment]
Thank Alkarex,

I have ca-certificates installed and up to date.
I've also tried to uncomment :
                //CURLOPT_SSL_VERIFYHOST => 0,
                //CURLOPT_SSL_VERIFYPEER => false,
in config.default.php, with no result. 

Curl work when i launch it from comand line...

**Comment by calaad** [comment]
Hi, 
You were right Alkarex. 

It was my php.ini pointing on false ca certs paths. 

Thank for your time :). I close.

**Comment by Alkarex** [comment]
Ok. Thanks for the feedback.
