### ISSUE TITLE
Les articles ne sont pas marqués comme lus

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#1123]
Bonjour,

J'ai choisi comme option marqué un article comme lu lorsque celui-ci est affiché, je fais défiler avec la touche j, de façon raisonnable on peut penser que je devrais rester en haut et ne pas avoir d'articles précédents or j'ai un tas d'articles qui ont été lus et pourtant ils ne le sont pas. 

Le problème est plus important si je fais le choix de marquer les flux comme lus lorsqu'on arrive à la fin de la page, par défaut 20 pour moi. Aucun article ne passe en marqué lu au changement de page. 

Le problème c'est que dès lors j'ai une masse d'articles qui ont été lus et qui restent en permanence, ils apparaissent en non lus. 

Cyrille

**Comment by ghost** [comment]
je vais répondre partiellement. En fait, il faut à l'article environ 1 à 2 secondes pour passer comme lu, or, il me faut moins de temps parfois quand j'appuie sur j pour faire défiler. Il faudrait que l'article passe automatiquement comme lu quand il est affiché.

**Comment by Alwaysin** [comment]
Avez-vous une connexion lente ? Du côté client ou bien serveur.

C'est probablement dû à cela plus qu'à FreshRSS comme indiqué dans l'issue https://github.com/FreshRSS/FreshRSS/issues/738 si vous avez une version contenant le fix #794

**Comment by ghost** [comment]
Effectivement c'est exactement le même problème. Ma version est celle du github d'hier, je n'ai pas de connexion lente côté serveur ou côté ligne internet. En outre, je vais vite.

**Comment by ghost** [comment]
si je devais faire la comparaison avec Kriss Feed par exemple, le problème ne se produit pas.

**Comment by ghost** [comment]
Pour exemple cet article n'arrive pas à passer au bleu : http://www.bfmtv.com/societe/la-tour-eiffel-aux-couleurs-du-drapeau-belge-en-solidarite-avec-bruxelles-961228.html

je suspecte la vidéo d'entrée d'être bloquante.

**Comment by NerosTie** [comment]
Cela vient que Freshrss attend que tous les éléments de l'article soient chargés pour le marqué comme lu. J'ai toujours trouvé ça curieux comme façon de faire...

**Comment by lapineige** [comment]
> Cela vient que Freshrss attend que tous les éléments de l'article soient chargés pour le marqué comme lu. J'ai toujours trouvé ça curieux comme façon de faire...

Y compris quand on ne déplie pas l'article ?

Je constate le même problème, pas toujours régulier mais ça doit venir de ce temps d'attente.

**Comment by NerosTie** [comment]
Qu'entends-tu par "y compris quand on ne déplie pas l'article ?"
Quand tu cliques sur l'icône sans le déplier ?
Si c'est ça, j'utilise assez rarement cette fonction, donc je ne peux pas dire.

**Comment by lapineige** [comment]
> Quand tu cliques sur l'icône sans le déplier ?

Exact. Et typiquement j'ai l'impression que si je le fais trop vite quand les articles reviennent, ce n'est pas efficace.
Aussi j'ai tendance à recharger la page une fois que c'est marqué comme lu, pour les faire disparaître. Peut-être que je le fais trop vite.

**Comment by NerosTie** [comment]
Oui c'est possible. Le client te dit que c'est bon, mais le serveur n'as pas eu le temps de recevoir l'information. Par contre, quand on ouvre chaque article (comme moi avec "j"), ceux qui refusent de se marquer comme "lu", c'est pénible parfois.

**Comment by lapineige** [comment]
Par contre dans mon cas (#1148) l'article semble être marqué lu, et si je recharge il l'est bien... sauf que plus tard de nouveaux articles disponibles sont signalés, et ces articles "lus" sont de nouveau non-lus.
@cborne ça te fait la même chose ?

**Comment by Alwaysin** [comment]
Ceci semble être autre chose, en l'occurrence une mise à jour des articles. Je pense que vous avez "Marquer les articles mis à jour comme non-lus" dans "Configuration -> Lecture" qui est coché.

**Comment by lapineige** [comment]
Ah c'est une bonne idée ça, je fais désactiver pour voir.
(fiou ça en fait des articles mis à jours alors ^^)

**Comment by Alwaysin** [comment]
Il peut y avoir des sites problématiques comme Le Monde, voir https://github.com/FreshRSS/FreshRSS/issues/798#issuecomment-89655370, ce qui pourrait être une explication.

**Comment by Alkarex** [comment]
Je peux reproduire le problème, dont la source semble être https://github.com/FreshRSS/FreshRSS/commit/69ce70be35c511921cf0bfe05f21c3ba44c0f17a qui était en réponse à https://github.com/FreshRSS/FreshRSS/issues/423
Je vais essayer de corriger

**Comment by Alkarex** [comment]
Corrigé dans https://github.com/FreshRSS/FreshRSS/pull/1191 et fusionné dans /dev
Merci de tester la version /dev si vous en avez la possibilité (attention, plusieurs autres changements, voir https://github.com/FreshRSS/FreshRSS/blob/dev/CHANGELOG.md ).
