### ISSUE TITLE
Lecteur libre sur le site

### ISSUE THREAD

**Issue by mikl86** [FreshRSS/FreshRSS#1124]
Bonjour,
Est t-il possible de mettre l'outil en mode open, de façon à permettre à tous les internautes de voir l'ensemble des flux, sans avoir besoin de créer un compte ou de  s'identifier ?
Merci d'avance.

**Comment by Alwaysin** [comment]
Bonjour,

dans la configuration, menu "Authentification", "Méthode d’authentification" -> "Aucun (dangereux)".
Mais cela implique que tout le monde a accès aux paramètres.

Pour avoir la lecture anonyme mais pas d'accès aux paramètres il faut garder l'authentification et cocher "Autoriser la lecture anonyme des articles de l’utilisateur par défaut (xxx)" et cela donne le même résultat que http://demo.freshrss.org/i/.

**Comment by Alkarex** [comment]
Voir le mode «anonyme» dans les paramètres de FreshRSS.

**Comment by Alkarex** [comment]
Voir par exemple une démo configurée en mode anonyme sur http://demo.freshrss.org
