### ISSUE TITLE
Add valid feed error (carnetdevol)

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#1125]
Hello, 

I can't add this feed
http://carnetdevol.shost.ca/wordpress/feed/

Freshrss 1.2, the feed seems to be valid, but freshrss refuse to add it.
Feed error [http://carnetdevol.shost.ca/wordpress/feed/]
Cheers.
P.

**Comment by Alkarex** [comment]
@prysme01 
A quick test on my side (from an OVH server) seems to show that an IP range is blocked:

```
 curl http://carnetdevol.shost.ca/wordpress/feed/
curl: (7) Failed to connect to carnetdevol.shost.ca port 80: Connection refused
```

I have also tried with various user-agents and other parameters, so it is probably that some IPs are blocked. I have never visited this site before from my server, so they are probably blocking large IP ranges.
