### ISSUE TITLE
Problème avec PHP 5.6 sur NAS Synology pour actualiser

### ISSUE THREAD

**Issue by dkmatt0** [FreshRSS/FreshRSS#1126]
Bonjour,

J'ai le message suivant quand je souhaite mettre à jour les flux de TOUS les utilisateurs de mon instance FresRSS :

```
dkmatt0@NAS:~$ php /volume1/web/freshrss/app/actualize_script.php 
Starting feed actualization at 2016-03-30T04:15:39+08:00
Actualize dkmatt0...
PHP Fatal error:  Undefined class constant 'MYSQL_ATTR_INIT_COMMAND' in /volume1/web/freshrss/lib/Minz/ModelPdo.php on line 64
Results: 
dkmatt0
```

Les solutions pour mettre à jour les flux avec `curl` ne mettent à jour que l'utilisateur par défaut. Je n'ai donc pas le choix et je dois passer par cette commande php.

J'utilise donc une version 5.6 de php (avec l'os de synology dsm 6.0). Le problème est probablement dû à ce dernier mais sachant que je ne dois pas être le seul à utilisé FreshRSS sur un NAS, je me dis qu'il serait bien de rendre compatible FreshRSS.

**Comment by Alkarex** [comment]
Bonsoir,
- Est-ce que FreshRSS marche par ailleurs correctement sur votre Synology ?
- Est-ce que vous utilisez une base de données MySQL (ou bien SQLite) ?

À vue de nez, il semblerait que votre version PHP CLI (ligne de commande) de dispose pas de l'extension PDO / MySQL, ce qui peut sûrement être corrigé dans le php.ini utilisé par votre PHP CLI http://php.net/manual/pdo.installation.php

Essayez un `php -i`

**Comment by dkmatt0** [comment]
Donc FreshRSS marche parfaitement ailleur qu'en CLI en MySQL.
Et en effet, Aucune trace de pdo_mysql avec `php -i`.

Je ne savais pas que PHP CLI utilisait sont propre php.ini, j'ai donc tenter d'utiliser l'autre pour le CLI mais c'est pire.

```
root@NAS:/etc/php# php /volume1/web/freshrss/app/actualize_script.php 
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php56/modules/gd.so' - libgd.so.3: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php56/modules/imap.so' - libc-client.so.1: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lib/php56/modules/pdo_mysql.so' - /usr/local/lib/php56/modules/pdo_mysql.so: undefined symbol: mysqlnd_allocator in Unknown on line 0
PHP Warning:  Cannot load module 'mysql' because required module 'mysqlnd' is not loaded in Unknown on line 0
Starting feed actualization at 2016-03-30T08:11:29+02:00
Actualize dkmatt0...
PHP Fatal error:  Undefined class constant 'MYSQL_ATTR_INIT_COMMAND' in /volume1/web/freshrss/lib/Minz/ModelPdo.php on line 64
Results: 
dkmatt0
```

Je retenterais des choses ce soir.

**Comment by dkmatt0** [comment]
Je pense que je ne peux rien faire avec le cli php de mon NAS, il ne doit pas être compiler avec ces options.

Ne serais t'il pas possible pouvoir mettre à jour l'ensemble des flux lorsque l'on utilise le token plutôt que seulement les flux de l'utilisateur par défaut ?
Ça me simplifierais les choses... Mais je suppose que ce n'est pas simple à coder...

**Comment by dkmatt0** [comment]
Pour mon cas j'ai résolu mon soucis !
Il y a 2 executables php dans le nas. Un `php` et (dans dsm 6.0) `php56`.
J'ai donc tester avec `php56 /volume1/web/freshrss/app/actualize_script.php` et ça fonctionne !

En espérant que cela servira à d'autre !

**Comment by Alkarex** [comment]
Merci pour les infos !
