### ISSUE TITLE
FreshRSS return bad address

### ISSUE THREAD

**Issue by nicolas-rdgs** [FreshRSS/FreshRSS#1129]
Hello,

I recently installed FreshRSS on Nginx server and I use Haproxy in front. My problem is that the virtual host listening on port 8000 and only ports 80 and 443 are open. 

When I go on FreshRSS, it returns :8000 so it should not. I saw $base_url in config.php which contains :8000 but when I delete the port, the problem persist. Finally, I have a page blank, it is normal because the port 8000 is blocked.

My workaround for now is to wait that page is loaded and I delete the port in the address bar.

**Comment by Alkarex** [comment]
Could you please try after clearing the cache or with another browser, to be sure there is not a cached redirection?
If there is still a problem, please try to send me a log of the HTTP headers (e.g. what HTTP response you get for your first request).

**Comment by nicolas-rdgs** [comment]
I already tried other browsers but the problem still persists.

My first request:

```
GET /freshrss HTTP/1.1
Host: www.piwiteam.fr
Connection: close
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
Accept-Encoding: gzip, deflate, sdch
Accept-Language: fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4
```

and response:

```
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Mon, 11 Apr 2016 08:40:47 GMT
Content-Type: text/html
Content-Length: 178
Location: http://www.piwiteam.fr:8000/freshrss/
Connection: close

<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by Alkarex** [comment]
As you can see, the redirection is made by nginx. I do not think the problem is due to FreshRSS.

**Comment by nicolas-rdgs** [comment]
But I don't have any redirection in my configuration.

My simple nginx configuration:

```
server {
        listen 127.0.0.1:8000;
        root /var/www/html/www;
        client_max_body_size 1G;
        fastcgi_buffers 64 4K;
        gzip off;

        # Add index.php to the list if you are using PHP
        index index.php index.html index.htm index.nginx-debian.html;

        location = /robots.txt {
                allow all;
                log_not_found off;
                access_log off;
        }

        location ~ \.php(?:$|/) {
                fastcgi_split_path_info ^(.+\.php)(/.+)$;
                include snippets/fastcgi-php.conf;
                fastcgi_pass unix:/var/run/php5-fpm.sock;
        }
}
```

**Comment by Alkarex** [comment]
The FreshRSS redirection would be to a `/p/` sub-directory: https://github.com/FreshRSS/FreshRSS/blob/dev/index.php
You probably have a file in `/var/www/html/www/` doing the redirection.

**Comment by Alkarex** [comment]
Ah, maybe the 301 redirection is cached by your Haproxy.

**Comment by nicolas-rdgs** [comment]
Could you try please https://www.piwiteam.fr/freshrss ? It work in your side?

**Comment by Alkarex** [comment]
It works from my side if you add the final slash: https://www.piwiteam.fr/freshrss/
I am guessing the redirection without the slash is cashed by your Haproxy.

**Comment by nicolas-rdgs** [comment]
I solved my problem! FreshRSS uses the variables $SERVER_NAME, $SERVER_PORT and $HTTP_HOST. To prevent the local port is added I made these changes:

I edited /etc/nginx/fastcgi_param and I added this:
`fastcgi_param HTTP_HOST $host;`

And in my nginx configuration:

```
location / {
    try_files $uri $uri/ =404;
    if (-d $request_filename) {
        rewrite [^/]$ $scheme://$http_host$uri/ permanent;
    }
}
```

**Comment by Body4** [comment]
Where is the button solved? :)

**Comment by Alkarex** [comment]
Thanks for the feedback.
