### ISSUE TITLE
Force encoding of RSS feed

### ISSUE THREAD

**Issue by Draky50110** [FreshRSS/FreshRSS#1130]
Hello.

I'm following this feed : http://www.lamanchelibre.fr/rss.php

As you can see, problem with encoding !

Is it possible to "force" it to have accents correctly displayed ?

**Comment by Alkarex** [comment]
Hum the feed has some Unicode UTF-8 characters in the `<description>`, while the rest is encoded in ISO-8859-1. In case of conflict between Unicode and ISO (neither are working), FreshRSS prefers Unicode.
https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fwww.lamanchelibre.fr%2Frss.php
I will think about it, but the producer should fix the "description" which contains invalid characters.

**Comment by Draky50110** [comment]
Send an email to the webmaster...

**Comment by Alkarex** [comment]
Now that I am back on my computer, I can see that the feed is served over HTTP as ASCII, with an XML encoding as ISO-8859-1, and with the items in UTF-8.

**Comment by Alkarex** [comment]
The best approach, and probably the easiest in their case as well, it to declare the feed as UTF-8 and update the few sections that are in ISO-8859-1 to UTF-8.

**Comment by Draky50110** [comment]
Solved as the RSS feed seems to have turned back to full UTF-8, after my email to webmaster ;)
Seen here : http://www.lamanchelibre.fr/rss.php (refresh if opened yesterday)

**Comment by Alkarex** [comment]
Very good :+1:
