### ISSUE TITLE
Erreur avec authentification http sur LBCAlerte

### ISSUE THREAD

**Issue by Draky50110** [FreshRSS/FreshRSS#1131]
Bonjour.

J'utilise LBCAlerte pour créer des flux RSS d'alerte pour LEBonCoin : https://github.com/Blount/LBCAlerte
Le script nécessite une identification pour l'utiliser et donc le flux RSS a aussi besoin de cette identification.

Sauf que je n'arrive pas à utiliser le flux avec les identifiants dans FreshRSS (dev).

Voici un exemple de flux : 
http://gilles.wittezaele.fr/LBCAlerte/?mod=rss&a=refresh&url=https%3A%2F%2Fwww.leboncoin.fr%2Fannonces%2Foffres%2Fbasse_normandie%2Fmanche%2F%3Fth%3D1%26q%3Dpoussette%25203%2520roues&price_max=50&price_strict=0

id/pass = test/test

Le script se trouve sur http://gilles.wittezaele.fr/LBCAlerte/ (du coup avec id/apss = test/test) si quelqu'un veut tester.

J'ai vérifié en collant l'URL du flux dans un navigateur, l'identification est demandée, je rentre test/test et ça passe.

Côté log de FreshRSS, ça ne donne rien : 
http://gilles.wittezaele.fr/paste/?323a06799d770147#ln7fSdTI9ssyyWBx+rZUQE62CO9E3bKTrr/hhWjw3O4

**Comment by Alkarex** [comment]
Il semble effectivement qu'il y a un bug dans FreshRSS. Je regarderai.

**Comment by Alkarex** [comment]
Cela devrait être corrigé avec https://github.com/FreshRSS/FreshRSS/issues/1137
Pourriez-vous essayer la branche /dev ?

**Comment by Draky50110** [comment]
Je confirme que ça marche :)
Merci.
