### ISSUE TITLE
Error loading feeds and categories, no feed to refresh

### ISSUE THREAD

**Issue by risq** [FreshRSS/FreshRSS#1138]
I just installed FreshRSS (`1.3.1-beta`) for the first time using docker with dokku. Everything seems to work fine during the configuration (all checks are OK and MySQL connection looks fine). I imported an OPML and FreshRSS successfully retrieved all the feeds. In `Subscription management` I can see all the feeds and the categories loaded.

However, in the left column of the main page, no feeds/category are shown (only `Main feeds` and `Favorites`). It does not seems to update feeds and pressing Refresh button display `There is no feed to refresh…` notification. Also, the global view is blank.

Did I missed something ? Do you think it may be related to my [docker env](https://github.com/risq/docker-freshrss/blob/master/Dockerfile) ?

Thanks !

**Comment by Alkarex** [comment]
Hello,
It is probably related to https://github.com/FreshRSS/FreshRSS/pull/1132
Fixed in /dev version.

**Comment by risq** [comment]
You're right ! Works fine on `dev`. Thanks !
