### ISSUE TITLE
Blogs list missing

### ISSUE THREAD

**Issue by ryanknapper** [FreshRSS/FreshRSS#1139]
After using FreshRSS for about a week I have lost the Blog menu.  I started out with v1.2 but installed v1.3.1-beta while trying to resolve this issue.

[Screenshot](http://i.imgur.com/YOCDqPL.png)

Version: 1.3.1-beta
Configuration: PHP
Storage: MySQL

**Comment by Alkarex** [comment]
Probably related to https://github.com/FreshRSS/FreshRSS/pull/1132
Fixed in /dev.
See also https://github.com/FreshRSS/FreshRSS/issues/1138

**Comment by ryanknapper** [comment]
/dev works, thank you.  Sorry, I promise I searched the buglist before I submitted.

**Comment by Alkarex** [comment]
No problem, and thanks for the feedback :-)
