### ISSUE TITLE
FreshRSS PHP 7.0 issues

### ISSUE THREAD

**Issue by canyapan** [FreshRSS/FreshRSS#1140]
Hi,
I have upgraded my environment to PHP 7.0. Now, I am having some troubles with FreshRSS.
- Categories not showing on the left panel. But when I click on the subscriptions, I can see the categories still there.
- Export fails with "### Fatal error! ### See logs files." text, but I cannot find any log record about it.

FreshRSS Ver: 1.2
OS: Ubuntu 16.04
PHP: 7.0
WS: Nginx 1.10

**Comment by Alkarex** [comment]
For the left panel, it is fixed in /dev https://github.com/FreshRSS/FreshRSS/pull/1132 and not due to PHP 7 but to a new version of MySQL https://github.com/FreshRSS/FreshRSS/issues/1139

**Comment by JanPetterMG** [comment]
Isn't FreshRSS relying on SimplePie?
According to Travis, PHP 7 isn't fully supported yet. I'm not sure if it is related to this issue, but there may also exist other issues we're not aware of yet...
https://travis-ci.org/simplepie/simplepie

**Comment by Alkarex** [comment]
I run FreshRSS with PHP7 without problem so far :-)

**Comment by JanPetterMG** [comment]
Thanks for the feedback, good to know :-)

**Comment by canyapan** [comment]
I am aware that php 7 has only beta support.

@Alkarex are you running the current dev version? And, if you are, do you have any suggestions to upgrade the current dev version?

**Comment by canyapan** [comment]
I have upgraded to `1.3.2-dev` and everything seems working. Thanks...

**Comment by Alkarex** [comment]
Very good :+1:  Please let us know if you encounter any problem.

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/issues/889
