### ISSUE TITLE
Flux RSS valide non lisible

### ISSUE THREAD

**Issue by Vincent14** [FreshRSS/FreshRSS#1141]
Bonjour,

Voici un flux que je n'arrive pas à lire en 1.3.1-beta  http://carrefour-numerique.cite-sciences.fr/blog/feed/

Savez vous si je peux faire quelque chose ?

**Comment by Alkarex** [comment]
Bonsoir,
Cela semble être un problème de délais. Le flux met plus que les 10 secondes par défaut pour répondre. Essayez dans `./data/config.php` :

``` php
'timeout' => 15,
```

**Comment by Vincent14** [comment]
J'obtiens :
 Le flux ne peut pas être ajouté. Consulter les logs de FreshRSS pour plus de détails.

Et dans les logs :

2016-05-01 08:04:41Feed error [http://carrefour-numerique.cite-sciences.fr/blog/feed/]

**Comment by Alkarex** [comment]
Et avec une valeur encore plus grande ?

**Comment by Vincent14** [comment]
Ca passe à 30 secondes :)
