### ISSUE TITLE
Autre flux RSS non valide, non lisible

### ISSUE THREAD

**Issue by Vincent14** [FreshRSS/FreshRSS#1142]
Bonjour,

J'ai trouvé un flux comportant des erreurs selon RSS Validator, j'aimerais savoir cependant si ces erreurs sont un réel problème pour FreshRSS ? 

Voici l'URL du flux : http://ouiaremakers.com/feed/

Est-ce que je peux aider ?

**Comment by Alkarex** [comment]
J'ai fait un patch exprès https://github.com/FreshRSS/FreshRSS/pull/1143
Veuillez essayer la version /dev

**Comment by Vincent14** [comment]
Corrigé merci !
