### ISSUE TITLE
Flux RSS valide avec certificat invalide

### ISSUE THREAD

**Issue by Vincent14** [FreshRSS/FreshRSS#1144]
Hello, 

Je rencontre aussi un soucis sur ce flux : http://validator.w3.org/feed/check.cgi?url=https://lab.limouzi.org/feed/

Est-ce que c'est important d'avoir un certificat valide sur un RSS (à tout hasard ?), il y a peut être un cas que je n'envisage pas

Merci par avance de votre temps :)

**Comment by Alkarex** [comment]
Oui, je trouve que le HTTPS et ses certificats sont intéressants à avoir, même pour les communications entre serveurs (meilleure sécurité, authenticité, confidentialité...).

À vos risques et périls donc ;-) Essayez dans votre `./data/config.php` de mettre les options suivantes dans la section `curl_options` :

``` php
    'curl_options' => array(
        # Options to disable SSL/TLS certificate check (e.g. for self-signed HTTPS)
        CURLOPT_SSL_VERIFYHOST => 0,
        CURLOPT_SSL_VERIFYPEER => false,
    ),
```

**Comment by Vincent14** [comment]
Cela fonctionne, merci !

**Comment by xiamuguizhi** [comment]
@Alkarex  Doesn't work for AlphaSSL certificates either, everything works fine after closing
