### ISSUE TITLE
Erreur de flux qui semble valide

### ISSUE THREAD

**Issue by Vincent14** [FreshRSS/FreshRSS#1145]
Hello

Firefox a arrive à m'afficher sans problème http://caen.libre.cc/feed/atom

Ceci dit le Validator indique une erreur http://validator.w3.org/feed/check.cgi?url=http://caen.libre.cc/feed/atom

Je me demande si SimplePie ne bloquerait pas dessus ?

**Comment by Alkarex** [comment]
Ce flux fonctionne bien depuis mon FreshRSS

**Comment by Vincent14** [comment]
Ca remarche, étrange
