### ISSUE TITLE
Les flux (marqués comme) lus réapparaissent après actualisation

### ISSUE THREAD

**Issue by lapineige** [FreshRSS/FreshRSS#1148]
(I can do an english version if needed)

Bonjour,
J'ai un problème récurrent plutôt gênant avec mon instance de FreshRSS version 1.2.0 (sur une distribution Yunohost installé sur un Raspberry Pi 2).
Les flux que je marque comme lus ou que je lis pendant un temps relativement court (bien que ça ne soit pas le cas pour tous) sont bien marqués lus et disparaissent du flux des articles non lus. 
Cependant, quand le bandeau indiquant que de nouveaux articles sont disponibles apparait, je clique dessus et ces articles réapparaissent, comme non lus.
Cela ne se produit pas avec tout les flux.

Il arrive également qu'ils réapparaissent après ce message, mais sans nouveaux flux. (Comme s'ils étaient de nouveaux détectés). Mais ça ne se produit pas systématiquement à chaque recherche de nouveaux flux (il m'arrive de ne pas voir ce bandeau pendant une heure, en ayant marqués des flux en lus).
Le problème n'est pas constaté si j'actualise les flux manuellement.

Je suppose que la description est un peu vague pour vous aider, mais je ne vois pas quelles informations supplémentaires vous seraient utiles.

Merci :)

**Comment by Alkarex** [comment]
Est-ce avec une base de données MySQL ou SQLite ?

**Comment by lapineige** [comment]
MySQL, désolé pour l'oubli.

**Comment by Alkarex** [comment]
Si vous avez la possibilité d'activer les logs MySQL (requêtes, et erreurs), et de montrer la partie correspondant au moment où le problème est constaté, cela aiderait beaucoup.

**Comment by lapineige** [comment]
Je ne sais pas le faire :(
Je vais demander sur le forum de Yunohost.

**Comment by lapineige** [comment]
Petit up, je n'avais pas eu le temps de chercher, mais ça semble lié à ce bug #1123.
Je vais faire plus de test avant de jetter un oeil aux logs.

**Comment by Alkarex** [comment]
Le patch https://github.com/FreshRSS/FreshRSS/issues/1123 est maintenant dans la branche /dev de FreshRSS. Si vous avez la possibilité de tester /dev, merci de dire si le problème est toujours présent ou pas

**Comment by lapineige** [comment]
Mince, j'ai oublié de mettre à jour cette issue, désolé:

J'ai la solution, elle était toute bête:

> Ceci semble être autre chose, en l'occurrence une mise à jour des articles. Je pense que vous avez "Marquer les articles mis à jour comme non-lus" dans "Configuration -> Lecture" qui est coché.

Merci à @Alwaysin

**Comment by Alkarex** [comment]
Pour ceux qui utilisent la version /dev, je viens de corriger un bug introduit le 1er août qui faisait lui aussi que certains articles n'étaient pas marqués comme lus https://github.com/FreshRSS/FreshRSS/pull/1217
