### ISSUE TITLE
Should mobile styles expose more info?

### ISSUE THREAD

**Issue by Frenzie** [FreshRSS/FreshRSS#1149]
Basically I want more info in my mobile styles with generated content, for instance (just brainstorming atm; not tested and certainly not quite the right selectors for FreshRSS):

```
/*probably mostly xkcd and what if; maybe other elements like a and abbr are relevant too*/
img[title]::after {display:block; margin-top:1em; content:attr(title)}
/*don't want to hold down on a link just to see where it goes*/
a[href]::after {content:" ("attr(href)")"; font-size:90%}
a[href^="data"]::after {content:""}
```

Of course I'll stick this in my custom styles, but I think at least some of this might be desirable to all?

**Comment by Alkarex** [comment]
Sorry for the delay.
If you find a customs style that works well for you, feel free to share it :-)
