### ISSUE TITLE
Aucun affichage avec des flux non lus

### ISSUE THREAD

**Issue by Draky50110** [FreshRSS/FreshRSS#1152]
Je ne sais pas pourquoi, mon affiche déconne sur une version DEV et une version BETA, depuis la mise à jour de ce matin que j'ai faite pour les 2.

En gros, FRSS me signale de nouveaux flux, c'est bien affiché dans les catégories/flux mais rien ne s'affiche à l'écran alors que l'icône "afficher non lus" est "enfoncée".
Si j'enfonce "afficher les lus", rien non plus.

Une idée ?

**Comment by Draky50110** [comment]
La même sur une 1.3.0 canal BETA.
Y'a eu un changement récemment ?
J'ai pas mis à jour depuis un bail...

**Comment by Alkarex** [comment]
Essayez de faire un coup "optimiser la base de donnée" dans les réglages de FreshRSS.

**Comment by Draky50110** [comment]
Bah c'est revenu de la façon suivante : j'ai cliqué sur une catégorie, les flux se sont affichés, j'ai "Marquer tous lu" et c'était bon le reste des non lus était bien affiché sur le flux principal.

Je me demande s'il n'ya pas eu un souci de rafraîchissement de cache ou de BdD en effet.
Peut-être à prévoir après une mise à jour automatiquement ?
