### ISSUE TITLE
Display problem with MySQL 5.7

### ISSUE THREAD

**Issue by angristan** [FreshRSS/FreshRSS#1154]
I updated my Percona Server from 5.6 to 5.7 (=MySQL 5.7) and FreshRSS works, no error anywhere but it does not diplay the same way : 
![](https://lut.im/K9rfO80gQr/MPJWMMEnt5fzbdET)

The categories on the left are missing and the button (I don't remember what it is) when ou have new articles and you want to mark them all as read is missing too. 

I don't have much infomations to give you... :/

**Comment by Alwaysin** [comment]
Are you on latest /dev? This has been resolved in https://github.com/FreshRSS/FreshRSS/pull/1132

**Comment by angristan** [comment]
Oh yeah I wanted to mention it : 1.2 and 1.3.1 have the same problem.
It should be fixed on 1.3.2, any way I could test it ?

**Comment by Alkarex** [comment]
As @Alwaysin mentioned, it is fixed in the current /dev branch. Please give it a try.

**Comment by angristan** [comment]
Works great on the dev branch :)
