### ISSUE TITLE
Canot display categories on sidebar after ubuntu16 update

### ISSUE THREAD

**Issue by me88** [FreshRSS/FreshRSS#1156]
Hello, 
I have checked the installation checking. It shows everything as all right. 
However on my mainpage I only see "main stream" and "favorite" in the sidebar. 
Where are my categories? Any idea?

PS: In subcription management I see all my categories... It just does not show on the sidebar (on all browswer)

**Comment by Alwaysin** [comment]
Hi,

Are you using MySQL 5.7? If so, are you on latest /dev branch? This is a known problem which has been resolved in #1132.

**Comment by me88** [comment]
Hello thanks for the answer. Yes I am on MySQL 5.7. 
The latest /dev branch of what ??? I do not understand...
I am using Freshrss 1.3.1-beta and also the 1.2 stable version: on both it's NOT working.

**Comment by Alwaysin** [comment]
Latest /dev branch of FreshRSS. Currently you use stable and beta, and there is another one called dev where all the changes are going directly (but still I've nearly never got any problem when running this branch, though you can expect to hit some bugs from time to time).

If you don't want to go with this branch, you can either wait for the fix to be included in the beta, or downgrade your MySQL version. Also, but less recommended, you could apply the patch manually : https://github.com/FreshRSS/FreshRSS/pull/1132/files

**Comment by me88** [comment]
Hello, 
It's OK for me to use the dev version (I was thinking dev=beta)...
Please can you tell me where I can find that version ?
Regards,

**Comment by Alwaysin** [comment]
Just select "dev" on the branch selector on Github. For downloading the source directly use this URL : https://github.com/FreshRSS/FreshRSS/archive/dev.zip

**Comment by me88** [comment]
It works thanks
