### ISSUE TITLE
Subscribe bookmark not working

### ISSUE THREAD

**Issue by Wieke** [FreshRSS/FreshRSS#1157]
Hi

I'm running freshrss on a nginx server with the root pointing directly at `pathtostuff/FreshRSS-beta/p` so `/p` doesn't get appended to `rss.mydomain.com`, basically the way it's setup in the docs. It seems to work except for the "Subscribe (FreshRSS bookmark)" bookmark which still uses `https://rss.mydomain.com/p/i/...` which obviously shouldn't have the `/p` bit in there.

I can't tell from the documentation whether or not this is a configuration problem on my end (I did fiddle with constants.php but that didn't help), so I figure it might be a bug.

Cheers,

Wieke

**Comment by Alkarex** [comment]
Hello,
Could you please check what value you have for `base_url` in your `./data/config.php`?

**Comment by Wieke** [comment]
It says `https://rss.mydomain.com/p` and removing the `/p` seems to have solved the issue. Did I miss some configuration option/instruction somewhere?

**Comment by Alkarex** [comment]
Which version of FreshRSS are you running?
It could be due to an older version, or to a bug in the initialization during install, or if you have changed your FreshRSS setup after the install.

**Comment by Alkarex** [comment]
For reference https://github.com/FreshRSS/FreshRSS/blob/b042d3a7728037db90a9306c61091be0a8ac42c4/lib/Minz/Request.php#L103

**Comment by Wieke** [comment]
I'm using 1.3.1-beta. 

Initially, during installation, I did have .../html/FreshRSS/ configured as the root in my nginx server. Only after spotting the security suggestion in the docs did I reconfigure it to .../html/FreshRSS/p/. Could that be the cause?

**Comment by Alkarex** [comment]
@Wieke Yes, you may have to manually update a path in your `./data/config.php`

**Comment by Wieke** [comment]
Well mystery solved then. It should probably be mentioned in the security section of the docs once they're written.
