### ISSUE TITLE
Update frequency

### ISSUE THREAD

**Issue by OliverGee** [FreshRSS/FreshRSS#1158]
Hi there,

Where can i choose the update frequency? I need mine to be in near-realtime (2 min delay at most) but FreshRSS doesn't seem to update very often. I am aware how taxing this is.

Oliver

**Comment by aledeg** [comment]
You can change that globally in the `archiving` configuration page. There is the `Do not automatically refresh more often than` option for that. Unfortunately, the lower limit is set to 20 minutes.

You can also change that per feed in the feed configuration page. The lower limit is set to 15 minutes.

It's far from being real-time but that's the closest you can get at the moment!

**Comment by OliverGee** [comment]
Thanks for the quick reply!

What if i wanted to edit the values manually to be quicker than that? I do realise realtime is not really feasible, but I would be happy with 2 minutes. Where in the app's backend could i do that?

Oliver

**Comment by aledeg** [comment]
You'll need to modify the value `ttl_default` in the configuration file located in `data/users/OliverGee/config.php`. The value is in seconds.
Then you need to set all your feeds to use the default value.

So to run it every other minute, you can set `ttl_default` to 0 and run your cron every other minute.
The problem with that is that you'll need to make that modification every time you need to change the configuration of the related page.

**Comment by OliverGee** [comment]
Thanks for the info. 

I assume editing the info in the default config will apply it to all users in the future? Of course with the same stipulation about making changes...

Oliver

**Comment by aledeg** [comment]
I haven't tried but I guess so.

**Comment by JanPetterMG** [comment]
What about calculating the update interval automatically? (feature suggestion)
2min intervals is a really bad idea !!! but also just right for the most frequent updated feeds.

How to do it:

``` php
$interval = $index / $count;
$interval = min($max, max($min, $interval));
```

`$interval` - needs no explanation
`$index` - a number that is increased/decreased if the feeds are updated too frequent/slowly
`$count` - the number of feed items for a given period of time.
`$min` / `$max` - lowest / highest allowed intervals.

Ps. don't forget to set a slow static interval if the feed `$item` count is set to zero. eg. once a day...

That's what I do with mine 760.000 feeds :-) cheers!

**Comment by OliverGee** [comment]
Yeah I realise 2 min intervals is a bad idea for most people/purposes but i am using it for something very specific hence the need for frequent updates!

It would be nice if this was a feature in future versions!

**Comment by Alkarex** [comment]
Hello,
The refresh time is purposely not faster than 20 minutes, because this is a bad use of polling, which risks having your IP banned, or even the FreshRSS user agent.

Feeds that have very frequent updates really should have a realtime PubSubHubbub push system, which FreshRSS supports by default. For compatible feeds, you get notifications immediately when a new story is published. See https://github.com/FreshRSS/FreshRSS/issues/312#issuecomment-102414760

Regarding the automatic detection of how often a feed should be refreshed, this is indeed a desired feature. See https://github.com/FreshRSS/FreshRSS/issues/968

**Comment by OliverGee** [comment]
I understand that.

In this case though the feeds are being generated by a script i wrote that is hosted on a separate server that i own so there is no risk of an IP ban. Obviously a cron is not the ideal way to run it realtime though.

I'll look into PubSubHubbub (ridiclous name much?). 

Thanks for your help!
