### ISSUE TITLE
Auto Actualize ?

### ISSUE THREAD

**Issue by hckweb** [FreshRSS/FreshRSS#1160]
Is it possible that freshrss to actualize itself ? I have to login in and actualize twice per day. If it can do it for me that would be great.

Thanks.

**Comment by Alwaysin** [comment]
Hi, yes you can do it. The process is described in the README : https://github.com/FreshRSS/FreshRSS#automatic-feed-update

**Comment by hckweb** [comment]
Thanks a lot. that works well :)
