### ISSUE TITLE
Broken mobile display

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/FreshRSS#1163]
Am I the only one experiencing this? Only happens on mobile (Android here),  I tried both Chrome and Firefox. 

![screenshot_2016-06-12-00-37-29](https://cloud.githubusercontent.com/assets/7189936/15987778/f210bdf6-3035-11e6-863a-75b82dcbbd19.png)

**Comment by Alwaysin** [comment]
Ok it has nothing to do with FreshRSS, it behaves like this on mobile network on Bouygues Télécom, not on WiFi. Will try other mobile network providers to see...

**Comment by Alkarex** [comment]
Cela ressemble à un problème de permissions ou de connexion vers les images / css.
- Essayez de naviguer vers une image, par exemple le logo, et de rafraîchir (regarder la console dans Firefox)
- Essayez de voir si vous voyez cette requête dans vos logs du serveur Web

**Comment by Alkarex** [comment]
Ah, messages croisés...
