### ISSUE TITLE
Pull more RSS feeds

### ISSUE THREAD

**Issue by ChuTang23** [FreshRSS/FreshRSS#1164]
Hello, are the amount of RSS feeds first pulled in by Craigslist controlled by Craigslist? When I use their RSS feed URL it pulls in only 25 feeds at that moment. Is this something they control ?

**Comment by Alkarex** [comment]
Hello,
You are probably asking about the number of _entries_ in a feed, aren't you? Yes, it is indeed controlled by the server (Craigslist).

**Comment by ChuTang23** [comment]
Thank you, @Alkarex for letting me know. I am new to RSS.  Thank you very much
