### ISSUE TITLE
Purge items by cron

### ISSUE THREAD

**Issue by Jean-Mich-Much** [FreshRSS/FreshRSS#1166]
Bonjour,

j'aimerais purger automatiquement les articles par un cron, j'ai cherché dans la doc fr sans aucun résultat, pourriez vous m'indiquer comment faire (si c'est possible bien sûr), merci.

Par ailleurs, j'utilise la commande VACUUM depuis un bon mois sans aucun soucis pour ceux que cela intéresse (l'air de rien je suis passé de 120 mb à ... 22 mb, le temp d'accés est divisé par 3 :).

English version (sorry, i use google translate): 
I would like to automatically purge items by cron, i look in the doc : no results, could you tell me how to do (if possible of course), thank you.
Furthermore, I use VACUUM (sqlite) since 1 month without errors for those interested (casually I went from 120 mb to 22 mb ..., access time divided by 3 :) .

**Comment by aledeg** [comment]
Tu peux configurer la durée de rétention des articles sur la page de configuration de l'archivage.
Normalement, les articles seront purgés automatiquement lors de la recherche de nouveaux articles.
À vérifier.

**Comment by Alkarex** [comment]
Effectivement, les articles sont déjà purgés, de manière aléatoire, lors de l'ajout de nouveaux articles (donc par cron, s'il y en a un) https://github.com/FreshRSS/FreshRSS/blob/7bc2ff45009a601550d77007c94ec23e2ced8f19/app/Controllers/feedController.php#L408

**Comment by Jean-Mich-Much** [comment]
Merci pour la réponse :)
