### ISSUE TITLE
No more categories after new install and previous DB

### ISSUE THREAD

**Issue by essembeh** [FreshRSS/FreshRSS#1169]
Hello 

I'm migrating my services as docker container.
So I decided to run a mysql container in which I imported a SQL dump of my freshrss DB.
In another container I run the latest stable version using nginx/php5 from debian jessie.

I run the "setup wizard" of freshrss and in the Database page, I set the values to connect to my mysql container.

The installation finishes with no error, I have all my history, my starred items, my feeds...
But I noticed there are no more category on the left panel of my new instance, only the two "Flux principal" and "Favoris".

Maybe it comes from my workflow, I use the new instance wizard to connect to an existing database?
Any idea?

Thx

**Comment by Alkarex** [comment]
If you use MySQL 5.7+, please use the current /beta or /dev version of FreshRSS
https://github.com/FreshRSS/FreshRSS/issues/1154
https://github.com/FreshRSS/FreshRSS/pull/1132
A /master version will be released in the coming weeks

**Comment by essembeh** [comment]
I tried using a mysql5.5 image and it worked.

Thanks
