### ISSUE TITLE
Support of sharing to Wallabag v2

### ISSUE THREAD

**Issue by lapineige** [FreshRSS/FreshRSS#1175]
Hello,

The sharing option to wallabag is no longer working with wallabag v2 - the wallabag tab/window is opened correctly, with the right address (including add-link=...) but the article is not added.

Someone is working on a [Tiny tiny rss plugin](https://github.com/joshp23/ttrss-to-wallabag-v2) to use wallabag v2, I link it there in case it can be useful (as an example, ...).
I don't know what changed with wallabag API, but I suppose it's not a big deal, a matter of url adaptation.
(not enough php skills to submit a PR, sorry)

Thanks ! :)

**Comment by JD557** [comment]
It's working for me with FreshRSS 1.3.3-dev and Wallabag 2.0.5.

Are you in the dev branch? I believe that the Wallabag v2 support is not yet on the main release.
See issue #1162 and pull request #1150

**Comment by lapineige** [comment]
Sorry I forgot to had my version: I'm using FreshRSS 1.2.0, on yunohost.
I guess I need to wait for the next stable version. Thank you ;)

**Comment by Alwaysin** [comment]
@Alkarex @marienfressinaud time to release a new /master maybe? It has been a time and a lot of great features and fixes are in the latest versions!

**Comment by lapineige** [comment]
Well, I see the milestone for 1.3.2-beta almost completed, so I suppose you will archive to publish this release soon ;)

(and after I'll ask for an update of this app for yunohost: https://github.com/YunoHost-Apps/freshrss_ynh)

**Comment by Alkarex** [comment]
Yes, we need to release a new master version, probably based on the current 1.3.2-beta, which was released on 12 June, and which seems quite stable.

**Comment by marienfressinaud** [comment]
It's done :). Note everyone will migrate to this stable version (even beta users) since beta branch will be dropped in the next weeks ;).

**Comment by lapineige** [comment]
Oh great ! Thanks, you are very reactive ;)
@plopoyop is working on an update for Yunohost. (https://github.com/YunoHost-Apps/freshrss_ynh/issues/15)
But the sharing seem to be working partly (not retrieving the content)

edit: do you know where I can see the changelog ? (or the list of commits)

**Comment by Alwaysin** [comment]
I think you are searching for this : https://github.com/FreshRSS/FreshRSS/commit/3f705cf03ccd919e0930bc3e95b98daff9f0560a and this : https://github.com/FreshRSS/FreshRSS/blob/master/CHANGELOG.md

**Comment by marienfressinaud** [comment]
Even better: https://github.com/FreshRSS/FreshRSS/releases/tag/1.4.0

**Comment by lapineige** [comment]
Thanks a lot @Alwaysin and @marienfressinaud  ! :smiley:
