### ISSUE TITLE
Go back to previous view when collapsing article

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/FreshRSS#1177]
J'espère que je vais être clair : quand j'ouvre un article, la vue est calée sur l'article de dessus, et se décale à chaque fois au fur et à mesure du défilement. Cependant, quand les articles sont longs et qu'il faut descendre pour les lire, au moment du repliement (avec le raccourci ou en cliquand sur les côtés), la vue est complétement décalée ; j'aimerais pouvoir revenir au calquage avec l'article du dessus.

**Comment by aledeg** [comment]
@Alwaysin 
Je suis fatigué par ce comportement, j'ai fait une PR sur develop pour le corriger. Peux-tu la tester ?
Dis-moi si cela te conviens ou s'il faut apporter des ajustements. Merci !

**Comment by Alwaysin** [comment]
@aledeg Mille mercis !!!!! Le patch fonctionne parfaitement sur mon instance, que ce soit en cliquant sur les côtés ou en utilisant le raccourci de fermeture d'article !
