### ISSUE TITLE
Logs : scroll avec Firefox impossible depuis 1.2.0 bêta

### ISSUE THREAD

**Issue by Leepic** [FreshRSS/FreshRSS#1178]
Depuis la version bêta 1.2.0, il m'est impossible de scroller dans les logs avec Firefox, je peux en revanche changer de page. J'ai essayé en 1.3.1, 1.3.2, 1.4.0, en désactivant les modules, en vain.

Versions testées : 
- 47 de Firefox sous Linux Mint 17.3 ;
- Firefox Développeur Édition 47.0a2 ;
- Vivaldi 1.0.83.38 c'est OK.

**Comment by Alkarex** [comment]
Yes indeed. This needs to be fixed

**Comment by Alkarex** [comment]
Fixed in https://github.com/FreshRSS/FreshRSS/pull/1182
The discussion continues there

**Comment by Alkarex** [comment]
The patch is now merged in the /dev branch, if you can give it a try.
