### ISSUE TITLE
[EasyRSS] Articles non-lus de flux supprimés

### ISSUE THREAD

**Issue by gllmhyt** [FreshRSS/FreshRSS#1179]
# FreshRSS
- FreshRSS 1.4.0
- Nombre d'articles non lus : 0

![capture du 2016-07-26 12-16-30](https://cloud.githubusercontent.com/assets/696539/17134554/4435eb84-532b-11e6-9e5b-857260ef1ea1.png)
- Politique d'archivage (par défaut, je crois) : 

![capture du 2016-07-26 12-20-45](https://cloud.githubusercontent.com/assets/696539/17134579/69c3ba34-532b-11e6-90a6-0cdaf282ac4d.png)
# EasyRSS
- Onglet "Non-lus" : nombre d'articles non-lus à 0.
- Si je sélectionne "Tous les articles non-lus", après un certain temps de chargement, sont affichés des articles de flux qui ne figurent plus dans mes abonnements.

![screenshot_20160726-121407](https://cloud.githubusercontent.com/assets/696539/17134678/e72ade44-532b-11e6-8aaf-196fb7b0e528.png)
- Marquer tous les éléments comme lu ne les fait pas disparaître définitivement, il suffit de quitter l'application puis de la relancer pour observer le même comportement.

Est-ce que ça veut dire que, d'une manière ou d'une autre, ces éléments figurent encore quelque part dans ma base de données (MySQL) ?
# Addendum 1

Si je recherche "terrain philosophique" depuis l'interface web, le premier article affichés dans EasyRSS ne remonte pas.

Première manipulation :
- purge manuelle des articles vieux de plus de trois mois depuis la page Archivage (message : 0 articles supprimés, alors que dans EasyRSS il m'en affiche qui ont plus de deux ans).
- suppression des fichiers de cache dans `data/cache`
- déconnexion / reconnexion du compte dans EasyRSS

Le comportement reste similaire tout du long : je peux arriver à nettoyer la file en entier, mais quitter l'application et réafficher la liste complète des articles non-lus réaffiche des articles de flux qui ne figurent plus dans mes abonnements.
# Addendum 2

Deuxième manipulation : avec phpmyadmin, recherche des articles litigieux en identifiant leur site de provenance.

``` mysql
SELECT * FROM `freshrss_postblue_entry` WHERE `link` LIKE '%implications-philosophiques%'
```

Et il y a des articles qui s'y trouvent ! Je remarque qu'alors qu'il n'y a _aucun article non-lu_ dans FreshRSS, il y a plus de 300 éléments ayant le champ `is_read` = 0.

``` mysql
SELECT * FROM `freshrss_postblue_entry` WHERE `is_read` = 0
```

J'ai une belle liste d'articles qui s'affichent. Donc on supprime tout ça, façon ménage bien sale.

``` mysql
DELETE FROM `freshrss_postblue_entry` WHERE `is_read` = 0
```

Et ça marche ! (Enfin, dira-t-on, il n'y a plus d'articles non-lus-qui-ne-devraient-pas-être-là.)
# Le bug le vrai

Donc : comment se fait-il que des articles de flux auxquels je n'étais plus abonné aient été conservés dans la base de données (déjà), qui plus est avec le champ `is_read` à 0 qui les faisait ressortir dans EasyRSS ?

**Comment by postblue** [comment]
Addendum: si je recherche "terrain philosophique" depuis l'interface web, le premier article affichés dans EasyRSS ne remonte pas.

**Comment by postblue** [comment]
Manipulations en cours :

* suppression des fichiers de cache dans `data/cache`
* déconnexion / reconnexion du compte dans EasyRSS
[... plus à venir]

**Comment by postblue** [comment]
Deuxième manipulation : avec phpmyadmin, recherche des articles litigieux en identifiant leur site de provenance.

```mysql
SELECT * FROM `freshrss_postblue_entry` WHERE `link` LIKE '%implications-philosophiques%'
```

Et il y a des articles qui s'y trouvent !

(... en cours d'identification des sites repris dans EasyRSS)

**Comment by Alkarex** [comment]
Bonjour @postblue ,
Merci pour ce post détaillé.
- Si vous avez supprimé des flux depuis l'interface Web de votre FreshRSS, ils sont supprimés complètement. Lorsque un flux est supprimé dans FreshRSS, les articles correspondants sont supprimés en cascade par MySQL, grâce à la déclaration `FOREIGN KEY (`id_feed`) REFERENCES `%1$sfeed`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,`. Je viens de re-tester, par acquis de conscience. Il est possible que vous ayez plusieurs flux fournissant des articles avec les mêmes liens, ou des liens du même domaine.
- La recherche dans FreshRSS se fait sur les titres et le contenu, pas les liens (à moins de l'indiquer avec `inurl:philosophie`)

Il faudrait donc tester de manière encore un peu plus systématique avant de pouvoir définir le problème.

**Comment by gllmhyt** [comment]
Salut @Alkarex 

De rien, je l'ai rédigé en même temps que je rencontrais des ennuis et comment j'ai réussi à m'en sortir finalement.

Je crois que le problème se situe quelque part dans le fait que justement, le contenu des flux n'aurait pas été complètement supprimé, laissant des cadavres ayant conservé leur champ `is_read` à 0 (et qui du coup remontaient dans EasyRSS).

Le bug n'est malheureusement pas réitérable, de fait la suppression en cascade marche bien. Du coup, je n'arrive pas à isoler ce qui aurait pu être la cause du problème. Peut-être un problème à ce moment là dans ma configuration MySQL ?

**Comment by Alkarex** [comment]
Il me semble peu probable que la contrainte d'intégrité de MySQL n'ait pas été respectée. N'hésitez pas à rouvrir si le problème se rematérialise. Tant que vous êtes dans MySQL, j'en profite pour dire que je suis intéressé par des tests de la version /dev de FreshRSS d'aujourd'hui, où MySQL est passé en utf8mb4 https://github.com/FreshRSS/FreshRSS/issues/1153
