### ISSUE TITLE
Le script n'actualise pas tous les flux 

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#1180]
Bonjour,

J'ai créé un cron pour executer le script d'actualisation comme décrit dans la documentation.
Seulement, j'ai l'impression que seuls les flux marqués "Uncategorized" sont rafraîchis automatiquement, car je dois actualiser à la main pour voir de nouveaux articles dans les autres catégories.

Est-ce un souci du script ? De mon installation ? De mon cron ?

J'utilise la version 1.3.2-beta

Merci

**Comment by Alkarex** [comment]
La catégorie des flux ne devrait avoir aucune incidence sur leur rafraîchissement.
Essayez de regarder vos différents logs.
Lorsque votre cron s'exécute, il y a pleins de détails dans votre le log système (`/var/log/syslog` sur Debian / Ubuntu) et dans votre répertoire temporaire (`/tmp/FreshRSS.log` sur Debian / Ubuntu), en plus des logs de FreshRSS (`./FreshRSS/data/users/*/log*`).
Voici une ligne de commande que j'utilise pour voir ces différents logs en même temps :

``` sh
multitail --mergeall /var/log/*log --mergeall /var/log/apache2/*.log --mergeall /var/log/mysql/*.log --mergeall /opt/FreshRSS/data/users/*/log*
```

**Comment by Alkarex** [comment]
Est-ce que le problème est résolu ?

**Comment by ghost** [comment]
Tout à fait.
Par contre, la ligne de cron fournie par la documentation n'a pas fonctionné pour moi, et j'ai du préciser un user, soit : 
`0 * * * * www-data php /path/to/FreshRSS/app/actualize_script.php > /tmp/FreshRSS.log 2>&1`
au lieu de 
`0 * * * * php /path/to/FreshRSS/app/actualize_script.php > /tmp/FreshRSS.log 2>&1`

**Comment by Alkarex** [comment]
Ok. J'ai ajouté un exemple pour Debian / Ubuntu dans le Readme https://github.com/FreshRSS/FreshRSS/pull/1296
