### ISSUE TITLE
Actualiser cache des favicons

### ISSUE THREAD

**Issue by Glaived** [FreshRSS/FreshRSS#1181]
Bonjour,
comment actualiser le cache des favicons ? Car actuellement j'ai maj mon freshrss, mais je n'ai plus les favicons (je l'ai maj de façon un peu violente, manuellement)

**Comment by Glaived** [comment]
Hmm, manifestement sur les dernières entry que j'ai, je n'ai pas le soucis, mais pour les anciennes en revanche oui.

**EDIT:** Il me semblerait que si un nouvel article d'un feed (genre: Grafikart.rss?type=php) est détecté, il actualise toutes les favicons pour le reste, cette solution me va donc :)

**Comment by Alkarex** [comment]
L'existence d'une favicon pour un flux est effectivement vérifiée lors de l'actualisation du flux.

**Comment by Draky50110** [comment]
Une petite relance : certains sites/flux changent de favicons.
Est-il possible de forcer FRSS à vider le cache puis recharger ?
Dans les options ou en URL ou autre ?

Sinon je suppose qu'il faut vider un répertoire sur le FTP...

**Comment by Draky50110** [comment]
Merci pour la milestone :)

Pour info, j'ai vidé "data/favicons" et les favicons ont donc été remis dès qu'un flux avait du neuf.

**Comment by Alkarex** [comment]
Patch avec actualisation automatique au bout de 15 jours https://github.com/FreshRSS/FreshRSS/pull/1290
Tests bienvenus
