### ISSUE TITLE
PHP 5.3: install ok mais pas de login possible

### ISSUE THREAD

**Issue by galuel** [FreshRSS/FreshRSS#1192]
L'install s'est bien terminée, mais quand j'essaie de me connecter il me renvoie sur : 

http://.../p/i/?c=auth&a=login

Avec le message dans la page : 

Error 403 - Forbidden

You don’t have permission to access this page
← Go back to your RSS feeds

**Comment by Alwaysin** [comment]
Vous pourriez tenter la méthode décrite ici : https://github.com/FreshRSS/FreshRSS/issues/1082#issuecomment-185222031

**Comment by Alkarex** [comment]
Bonjour @galuel 
Avec quelle version de FreshRSS, et quel serveur HTTP?

**Comment by galuel** [comment]
La dernière version "release" notée ici même + hébergement mutualisé.

**Comment by Alkarex** [comment]
Comme a dit @Alwaysin , essayez la petite procédure https://github.com/FreshRSS/FreshRSS/issues/1082#issuecomment-185222031 pour ré-initialiser votre mot de passe

**Comment by Alkarex** [comment]
Le problème ressemble fortement https://github.com/FreshRSS/FreshRSS/issues/1208 si l'installation est sous PHP 5.3.
Corrigé dans https://github.com/FreshRSS/FreshRSS/pull/1209

**Comment by ecmu** [comment]
Oui, mais non !

La correction #1209 qui corrige bien #1208 si je suis déjà connecté ou en authentification "none", mais en authentification "form", une fois déconnecté, impossible de me reconnecter...
Même en environnement "development", je n'ai aucun message d'erreur, uniquement la page 403.

Y-a-t-il des logs sur le serveur qui pourraient être utiles ?

**Comment by Alkarex** [comment]
Quel est le message d'erreur exact? Et pourriez-vous essayer avec un navigateur navigateur? Quelle version de PHP?

**Comment by Alkarex** [comment]
@ecmu Auriez-vous par hasard un réglage sur votre navigateur qui modifie les entêtes HTTP `Referer` ?

**Comment by ecmu** [comment]
Le message d'erreur est : 
![selection_005](https://cloud.githubusercontent.com/assets/8342237/17643802/c61c8354-6174-11e6-833f-3c2ae67d2ccf.png)

J'utilise Firefox sous ubuntu 16.04. Et j'ai essayé Midori (moteur webkit je crois), même constat après avoir saisi mon login/password.
Pour rappel, tout fonctionne avec 'auth_type' => 'none'...

Voici la vérification de l'installation donnée par freshrss :
![selection_004](https://cloud.githubusercontent.com/assets/8342237/17643789/84f3b65e-6174-11e6-91ed-4cf8982beff3.png)

A priori, non je n'ai aucun réglage du type "HTTP referer" (mais je ne sais pas ce que c'est...).
Information importante : mon site freshrss ne fonctionne plus depuis qu'il a migré de 1.2.0 vers 1.4.0 (j'ai ensuite appliqué la correction #1209). Autrement dit, en version 1.2.0, tout fonctionne parfaitement avec le même navigateur (donc le même réglage).

En tout cas, merci beaucoup pour votre disponibilité et la rapidité de vos réponses.

**Comment by Alkarex** [comment]
On va bien finir par trouver le problème :-)
Après avoir mis `'auth_type' => 'none'`, avez-vous bien changé votre mot de passe via l'interface FreshRSS?
![password](https://cloud.githubusercontent.com/assets/1008324/17644261/dee5caa0-6181-11e6-9ba2-2868dd6348c4.png)

**Comment by Alkarex** [comment]
Avez-vous dans les logs de FreshRSS un message du type `Password mismatch for user=XX nonce=, c=` ?
Si oui, ça pourrait être le même problème que https://github.com/FreshRSS/FreshRSS/issues/1208#issuecomment-239642650

**Comment by Alkarex** [comment]
Je viens de mettre à jour la branche /dev avec une correction pour PHP 5.3 (https://github.com/FreshRSS/FreshRSS/pull/1212). Merci d'essayer la branche /dev si possible.

**Comment by ecmu** [comment]
Effectivement, j'ai cette ligne dans le log.txt utilisateur : 
[Mon, 15 Aug 2016 13:30:45 +0200] [warning] --- Password mismatch for user=ecmu, nonce=, c=

Et je viens de reprendre la version 1.5.0-dev avec la correction #1212 qui corrige ce point aussi.
OK pour moi.

**Comment by Alkarex** [comment]
Merci pour le test, @ecmu :+1:

**Comment by Alkarex** [comment]
@galuel Votre problème devrait être corrigé dans la branche /dev de FreshRSS
https://github.com/FreshRSS/FreshRSS/tree/dev
Merci de confirmer (ou infirmer !) si vous en avez la possibilité
