### ISSUE TITLE
SQL error updateFeed: UNIQUE constraint failed: feed.url

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#1193]
I don't have much information, but this error is from my error log.
Any idea ?

**Comment by Alkarex** [comment]
Do you happen to have a log of the SQL request that has generated this error?
Or HTTP logs at the same point in time?
Was it maybe when you tried to add a new feed or edit an existing feed?

**Comment by ghost** [comment]
yes right it did not happen anymore, and I was adding few new feed.
