### ISSUE TITLE
update.freshrss.org : certificat expiré

### ISSUE THREAD

**Issue by Leepic** [FreshRSS/FreshRSS#1200]
Depuis 16h38 aujourd'hui (09/08/2016) le certificat TLS émis par StartCom n'est plus valide. Impossible donc de mettre à jour FreshRSS. Exemple lors d'une recherche de mise à jour : 

« Arf ! Le serveur de mise à jour n’a pas été trouvé. [https://update.freshrss.org?v=1.4.0] »
Ou dans les logs
« Error during update (HTTP code 0): SSL certificate problem: certificate has expired »

**Comment by Alkarex** [comment]
@marienfressinaud

**Comment by Alkarex** [comment]
Voir aussi https://github.com/FreshRSS/FreshRSS/issues/907

**Comment by marienfressinaud** [comment]
Arf désolé j'ai zappé :/ Je viens de mettre en place un certificat Let's Encrypt, ça devrait refonctionner ;)

**Comment by Alkarex** [comment]
@marienfressinaud Je viens de remarquer que https://freshrss.org/feeds/all.atom.xml ne fonctionne plus en HTTPS. La version HTTP fonctionne

**Comment by marienfressinaud** [comment]
J'avais oublié ton message, j'ai corrigé ce soir !
