### ISSUE TITLE
liens cassés dans « À propos »

### ISSUE THREAD

**Issue by Leepic** [FreshRSS/FreshRSS#1201]
Les liens ci-dessous ne sont plus bons dans la page « À propos » section « Crédits » : 
- police "Open Sans" de [Steve Matteson](https://www.google.com/webfonts/specimen/Open+Sans) => https://fonts.google.com/specimen/Open+Sans
- 404 pour [getFavicon](https://getfavicon.appspot.com/) => https://ucygetfavicon.appspot.com/

**Comment by Alkarex** [comment]
Merci

**Comment by Alkarex** [comment]
Fixed in /dev, thanks https://github.com/FreshRSS/FreshRSS/pull/1204

**Comment by Alkarex** [comment]
More credits updated https://github.com/FreshRSS/FreshRSS/pull/1211
