### ISSUE TITLE
Import opml, categories are not created

### ISSUE THREAD

**Issue by Wanabo** [FreshRSS/FreshRSS#1202]
Installed version 1.40 to replace an RNews installation. First exported everything in OPML format from RNews. Imported it in FreshRSS. All feeds were imported but all were assigned to "Uncategorized".

I expected categories were created from the opml file because categories are used in the opml file.
Below an example.
`<?xml version="1.0" encoding="UTF-8" ?>
<opml version="1.0">
  <head>
    <title>Rnews feeds</title>
    <dateCreated>Wed, 10 Aug 2016 22:32:49 +0200</dateCreated>
    <ownerName>me</ownerName>
  </head>
  <body>
    <outline version="RSS" text="NuJij Wetenschap" title="NuJij Wetenschap" xmlUrl="http://www.nujij.nl/Rss/Nieuw/?topic=Wetenschap" htmlUrl="http://www.nujij.nl/" category="Wetenschap" type="rss" />
    <body>
</opml>
`
I had to export opml file per categorie and then import them, create the category and assign them to the category. A lot of extra work.

So please make it so that categories are created upon import and assign the correct feeds to the category specified in the opml file.

**Comment by Alkarex** [comment]
Hello @Wanabo 
At a first glance, I cannot see the categories in your OPML example. Could you please provide a longer example?

**Comment by Wanabo** [comment]
Well it is there, search for category="Wetenschap".
Perhaps RNews did not follow the OPML standard.

I'll send you a complete file by mail.

**Comment by Alkarex** [comment]
Ah indeed! I am more used to seeing hierarchies. Ok.

**Comment by Wanabo** [comment]
I hope I send the mail to the right address. Did you receive it?

**Comment by Alkarex** [comment]
Jep. Working on it.

**Comment by Alkarex** [comment]
@Wanabo I have made a workaround https://github.com/FreshRSS/FreshRSS/pull/1206
Could you please give it a try?
I think the easiest to test is just to replace your `./FreshRSS/lib/lib_opml.php` with this version https://github.com/Alkarex/FreshRSS/blob/29d79185880f361545cf08b9faa4c755206c296e/lib/lib_opml.php

**Comment by Wanabo** [comment]
I'll test it tomorrow with a new install. With current install I checked all feeds for https support and changed a lot of url's. I think I have suggested once to use a proxy to show insecure images as secure images to avoid mixed content. That would be nice.

**Comment by Wanabo** [comment]
Just did a fresh install and imported the big opml file containing all categories.
Every thing went fine! All feeds imported, all categories created and all feeds assigned to the correct category.
Great you found the problem!
