### ISSUE TITLE
web update deletes database!

### ISSUE THREAD

**Issue by Wanabo** [FreshRSS/FreshRSS#1203]
Wanted to replace an existing RNews website with FreshRSS.
I all ready have an FreshRSS website version 1.20, so copied it to a new url. 

Website was working ok on the new url, but I also noticed there was an update. So I tried the web update, but after updating all feeds were gone, the site was like a fresh install. Never used web update before. My preferred updating/upgrading is downloading a new version and overwriting old files.

I guess it has to do with file ownership permissions. When updating and thus retrieving files from internet the files are owned by Apache instead of the user.

Finally I grabbed the latest version and did a fresh install. See also my trouble with importing OPML files here, https://github.com/FreshRSS/FreshRSS/issues/1202

**Comment by Alkarex** [comment]
Was that with a SQLite database?

**Comment by Wanabo** [comment]
Yes, that is correct. So it is a known bug?

**Comment by Alkarex** [comment]
No, not a known bug. But you probably have gotten a screen asking you to chose between:
- Keep previous installation
- Reinstall FreshRSS

Could you maybe have clicked the wrong option?

**Comment by Wanabo** [comment]
There was no additional choice!

**Comment by marienfressinaud** [comment]
I'm closing this, if the problem was still there I'm pretty sure someone else would complain :p
