### ISSUE TITLE
FreshRSS_Context::$description

### ISSUE THREAD

**Issue by Wanabo** [FreshRSS/FreshRSS#1207]
I found FreshRSS_Context::$description in layout.phtml but it has no value.

Is this a start on automatic generation of description?

My previous solution is not working correctly anymore.

`<meta name="description" content="<?php echo trim(htmlspecialchars_decode(substr(self::title(), ($pos = strpos(self::title(), ')')) !== false ? $pos + 1 : 0))); ?>" />`

**Comment by Alkarex** [comment]
Hello,
Isn't it the same discussion than https://github.com/FreshRSS/FreshRSS/issues/938#issuecomment-150912635 ?
Have you remembered to switch on `allow_robots`?

**Comment by Wanabo** [comment]
Yes it is the same issue. I set allow_robots to true.
Then this line will be activated in freshrss:
`<meta name="description" content="<?php echo htmlspecialchars(FreshRSS_Context::$name . ' | ' . FreshRSS_Context::$description, ENT_COMPAT, 'UTF-8'); ?>" />`

FreshRSS_Context::$name gives output but FreshRSS_Context::$description NOT! Thats why I asked about FreshRSS_Context::$description

**Comment by Alkarex** [comment]
Description is populated from the name of the category, of from the description of the feed.
E.g. when visualising a feed:

``` html
<title>Planet Libre · FreshRSS</title>
<link id="prefetch" rel="next prefetch" href=".?a=normal&amp;get=f_105&amp;next=1469100755988349&amp;ajax=1" />
<link rel="alternate" type="application/rss+xml" title="Planet Libre | FreshRSS" href=".?a=rss&amp;get=f_105" />
<meta name="referrer" content="origin" />
<meta name="description" content="Planet Libre | Communauté du Libre partage" />
```

Let's continue in the original discussion https://github.com/FreshRSS/FreshRSS/issues/938#issuecomment-150912635
