### ISSUE TITLE
PHP 5.3: Fatal error, blank page

### ISSUE THREAD

**Issue by cjrobe** [FreshRSS/FreshRSS#1208]
I installed it and everything went successful. First, I got a 403 error when logging in to FreshRSS. Then I set authentication to none and it made FreshRSS load as a blank page. Then I set the environment to development and it showed the following error.

`Fatal error: Using $this when not in object context in /home/coryrcom/public_html/feedme/app/Controllers/indexController.php on line 37`

I'd appreciate any help. Thanks!

**Comment by Alkarex** [comment]
Hello,
Which version of FreshRSS, which platform?

**Comment by cjrobe** [comment]
Thanks for the quick response.

I'm on Linux and I downloaded the package from this URL today:
https://github.com/FreshRSS/FreshRSS/archive/master.zip

When I look at Changelog.md, the top version is "FreshRSS 1.4.0".

**Comment by Alkarex** [comment]
I have just double-checked and this version works fine on an Ubuntu 16.04 box with PHP7.0.8 and Apache 2.4.18, using SQLite installation, also when using authentication => none. Could you please provide more precise info about your system (PHP version...)?

``` sh
alexandre@alexandre-VirtualBox:/var/www/html$ wget https://github.com/FreshRSS/FreshRSS/archive/master.zip
alexandre@alexandre-VirtualBox:/var/www/html$ unzip master.zip 
alexandre@alexandre-VirtualBox:/var/www/html$ mv FreshRSS-master/ FreshRSS
alexandre@alexandre-VirtualBox:/var/www/html$ sudo chown alexandre:www-data -R FreshRSS/
alexandre@alexandre-VirtualBox:/var/www/html$ sudo chmod g+rw -R FreshRSS/data/
alexandre@alexandre-VirtualBox:/var/www/html$ php -v
PHP 7.0.8-0ubuntu0.16.04.2 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8-0ubuntu0.16.04.2, Copyright (c) 1999-2016, by Zend Technologies
alexandre@alexandre-VirtualBox:/var/www/html$ apache2 -v
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2016-07-14T12:32:26
```

**Comment by cjrobe** [comment]
URL removed - PHP info

URL removed is the URL I'm trying to run it on.

Comment if you want the URLs back.

**Comment by cjrobe** [comment]
I just did another installation in a different directory and did a super basic password. It still did the same thing - unable to login with 403.
![image](https://cloud.githubusercontent.com/assets/5606066/17633932/f353fdca-609d-11e6-92cf-f17e77c3c25c.png)

**Comment by Alkarex** [comment]
I believe this is a bug specific to PHP 5.3. I am having a look

**Comment by Alkarex** [comment]
@cjrobe Could you please try this patch https://github.com/FreshRSS/FreshRSS/pull/1209 ?
For instance by trying https://github.com/Alkarex/FreshRSS/archive/php5.3-closure.zip, or just by manually updating the two files that have changed https://github.com/FreshRSS/FreshRSS/pull/1209/files
P.S. I do not have an old PHP 5.3 readily available to test.

**Comment by cjrobe** [comment]
I transferred app/layout/layout.phtml and app/Controllers/indexController.php.

I then tried it and with authentication still got the 403 and without and got a slightly different fatal error on line 37.

`Fatal error: Call to private method FreshRSS_index_Controller::listEntriesByContext() from context '' in /home/coryrcom/public_html/feedme/app/Controllers/indexController.php on line 37`

I then went through the install again and had the same results.

Thanks for your time.

**Comment by Alkarex** [comment]
Ok, I forgot that the scope for PHP < 5.4 would be different. Fixed https://github.com/Alkarex/FreshRSS/commit/af31f1b20fa7675a208c7a73933231ac2fb8928a
Could you please try https://github.com/FreshRSS/FreshRSS/pull/1209 again?

**Comment by Alkarex** [comment]
@cjrobe Some fixes for PHP 5.3 have been merged in the /dev branch of FreshRSS. It would be nice if you could it a try https://github.com/FreshRSS/FreshRSS/tree/dev

**Comment by cjrobe** [comment]
I downloaded FreshRSS-dev and went through the install into a fresh directory and database. When trying to login with the user created, I still get a 403 error. I then changed the auth_type to none and it loaded! I'm playing around with it and everything is working very nicely - an impressive piece of software. I think I will really enjoy this, importing my feeds as we speak.

I went into settings and created another user and I still get a 403 error when I try login with the newly created user (username demo, password demodemo). I went into /data/users/cjrobe/log.txt and in the log it says:

`[Sat, 13 Aug 2016 17:33:16 -0400] [warning] --- Password mismatch for user=demo, nonce=, c=
`

And it also says the same thing for my main account.

**Comment by Alkarex** [comment]
@cjrobe It could be a JavaScript error. Could you please look at your Web browser's console?
Could you please try with another browser? What is your PHP version? What server?

**Comment by cjrobe** [comment]
I just tried in Internet Explorer, Firefox, and Google Chrome Incognito and none can login. PHP Version 5.3.28 on a Linux server running Apache.

I see in my console:

`VM204:2 Uncaught SyntaxError: Unexpected end of JSON input`

**Comment by Alkarex** [comment]
Ok, that is the problem then. Could you please paste the first ~30 lines of
the HTML (view source, in your browser)?
Still nothing in your Web server logs?

**Comment by cjrobe** [comment]
I just checked my server log and this is what is says:
`[Sun Aug 14 09:59:10 2016] [error] [client 70.187.78.44] PHP Warning:  json_encode() expects parameter 2 to be long, string given in /home/coryrcom/public_html/feedme/app/views/helpers/javascript_vars.phtml on line 53, referer: http://cory-r.com/feedme/p/`

`[Sun Aug 14 09:59:10 2016] [error] [client 70.187.78.44] PHP Notice:  Use of undefined constant JSON_UNESCAPED_UNICODE - assumed 'JSON_UNESCAPED_UNICODE' in /home/coryrcom/public_html/feedme/app/views/helpers/javascript_vars.phtml on line 53, referer: http://cory-r.com/feedme/p/`

And I can't get the first 30 lines of the to show correctly without Github breaking the code section in the middle. You can pull it from here if you need to.

URL removed.

Thanks!

**Comment by Alkarex** [comment]
Ah, finally an error message :-)
Ok, JSON_UNESCAPED_UNICODE is from PHP 5.4. I will make a fix for PHP 5.3.

**Comment by Alkarex** [comment]
@cjrobe Could you please try this patch? https://github.com/FreshRSS/FreshRSS/pull/1212
Only one new line.

**Comment by Alkarex** [comment]
Merged in the /dev branch

**Comment by cjrobe** [comment]
You rock! Everything is working great now. Thanks again.

**Comment by Alkarex** [comment]
And thanks for the feedback :+1:
