### ISSUE TITLE
Proxy-cache for pictures

### ISSUE THREAD

**Issue by Liandriz** [FreshRSS/FreshRSS#1215]
Hi, is it possible to add an option to embed pictures in articles db, as base64 in the content?
Some sites are providing full articles feeds, but do not allow image hotlinking, or error with old down sites :/

**Comment by Alkarex** [comment]
@Liandriz The /dev version of FreshRSS does not send a Referer anymore, which will make pictures to work on some sites where hot-linking did not work before.
I guess what you ask is a kind of proxy-cache for the photos, isn't it? Storing the multimedia resources along with the text in database would be impractical for performance reasons, but a proxy-cache would be doable.

**Comment by Liandriz** [comment]
Yes thanks, storing multimedia resources in this kind of cache folder would be great.
With option to activate it or not, a ttl limit and space limit seems interesting.

**Comment by Alkarex** [comment]
See extension https://github.com/FreshRSS/Extensions/pull/5

**Comment by Alkarex** [comment]
Related issue https://github.com/FreshRSS/FreshRSS/issues/1341

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/Extensions/tree/master/xExtension-ImageProxy

**Comment by helmut72** [comment]
Thank you, but this extension use an external service. Installing imageweserv locally is a bit bloated only to save images, also Docker runs poorly on a Raspberry.
I'd like to have at least my starred articles (how-to articles) completely independent from Internet. Isn't it possible to save the original image in an imagecache folder and reference to this? This won't be bloat the database. TT-RSS will do that, but TT-RSS isn't an option for other reasons.

**Comment by math-GH** [comment]
is this feature request still needed? Does have @helmut72 still have this issue while reading the feeds?

**Comment by helmut72** [comment]
a local image cache would be great

**Comment by helmut72** [comment]
Update: Works for me. Using now Nginx instead of Weserv with high numbers to cache it "forever". Thanks!

**Comment by Frenzie** [comment]
Out of curiosity, as per the sample added in https://github.com/FreshRSS/Extensions/pull/117 or something else?

**Comment by helmut72** [comment]
Yes, using the sample from [xExtension-ImageProxy](https://github.com/FreshRSS/Extensions/tree/master/xExtension-ImageProxy). Sorry for the long time, but FreshRSS was for testing and playing until now. Want to move from TT-RSS when FreshRSS 1.20 with xpath feature is released.

**Comment by Alkarex** [comment]
See https://github.com/FreshRSS/Extensions/pull/139
