### ISSUE TITLE
Empty Feed issue

### ISSUE THREAD

**Issue by jwhipp** [FreshRSS/FreshRSS#1216]
I am trying to resolve an issue I am having with 1.4.0

This feed: http://www.depechemode.com/feed/

Shows up as empty, yet when I curl it or check it with the validator, it's fine.   

I have a similar issue with this feed: http://www.linuxinsider.com/perl/syndication/rssfull.pl

Checks and curls fine, but FreshRSS says it's empty.  Could be two seperate issues, but they look similar. 

Server details:

Ubuntu 16.04, PHP 7.0.8-0ubuntu0.16.04.2 (cli) ( NTS )

**Comment by Alkarex** [comment]
Hello @jwhipp,
I have just tried from my own instance running the /dev branch and both feeds work fine.

A couple of ideas (both from FreshRSS Web interface):
- For the first one, most the the posts are old, so try to increase the retention value in the archiving settings of FreshRSS
- Try to see if you have anything in the FreshRSS logs

While debugging, to try again and be sure you do not hit the cache, you can try adding a parameter to the URL, such as `http://www.depechemode.com/feed/?2` and `http://www.linuxinsider.com/perl/syndication/rssfull.pl?2`

**Comment by jwhipp** [comment]
I managed to get Linux Insider going, but the 'Mode one is still empty.  I've adjusted the archival but I am sure they just need to post something new.   Thanks for the help!
