### ISSUE TITLE
Call for testing /dev before version 1.5

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#1219]
The future version 1.5 of FreshRSS is [ready](https://github.com/FreshRSS/FreshRSS/milestone/18) for testing. There is a nice changelog https://github.com/FreshRSS/FreshRSS/blob/dev/CHANGELOG.md with new features and bug corrections, all in all a good improvement since the [previous version](https://github.com/FreshRSS/FreshRSS/issues/1113) :-)

Please give a try to the [/dev version](https://github.com/FreshRSS/FreshRSS/tree/dev) if you can.
Watch out, login by Mozilla Persona has been removed, and the minimum versions for PHP and MySQL have slightly increased.

@marienfressinaud @aledeg @galuel @cjrobe @ecmu @romibi @j8r @AmauryCarrade @Frenzie @cborne @Alwaysin @lapineige @NerosTie @JD557 @Wanabo @Leepic ...

**Comment by lapineige** [comment]
Happy to see a new version so soon :) (with a good list of features)

I'll try to test it on Yunohost. Unfortunately, the maintainer of the app (https://github.com/YunoHost-Apps/freshrss_ynh) is in holidays, so I guess I'll not be able to do so soon.

**Comment by marienfressinaud** [comment]
Mmm, I just realised the last version was 1.4, I didn't pay attention when you send me an email but since we don't have `beta` anymore, the next stable version can be 1.5 (sorry about that!)

**Comment by Wanabo** [comment]
Great to see a new version. I setup a new install of 1.5.0-dev.

First step installation: Choose a language. Need to save/submit it before proceeding. Is it possible when you select a language from the dropdownbox and then you only have to click go to the next step to make the language choice stick? 
Selected English for installation.
Step 3: HTTP username and HTTP password should be DB username and DB password
Database should be DB name

Installation of 1.5.0-dev went fine.
Imported OPML file and all feeds and categories were ok.
All the descriptions of the feeds are empty. I would request an extra option to check for feed descriptions once during import or as an extra button to retrieve the description manually. If a feed has a description then no auto update of the description should take place. 

Thanks for this new version.

**Comment by Wanabo** [comment]
Was playing with enabling/disabling lazy load setting because I noticed html errors. Enabled or disabled both settings produces lazyload="" postpone="" in output html. I was hoping to suppress html errors by disabling lazy load.

**Comment by Alkarex** [comment]
@Wanabo Please open another issue. Damn, I can see that the spec has been abandoned... https://www.w3.org/TR/resource-priorities/ https://lists.w3.org/Archives/Public/public-web-perf/2015May/0006.html http://caniuse.com/#feat=lazyload
There is no consequence with those additional attributes, but I will change them in a later version

**Comment by ecmu** [comment]
I am using 1.5.0-dev for a few days and it works perfectly.

**Comment by Alkarex** [comment]
FreshRSS version 1.5.0 released :-) https://github.com/FreshRSS/FreshRSS/releases/tag/1.5.0

**Comment by Frenzie** [comment]
Hooray! =)

**Comment by Wanabo** [comment]
Just updated a 1.5.0-dev to 1.5.0. One remark though. Due to \data\do-install.txt I got the installer again. Not very user friendly. 
A check should be performed if a existing user/database is present. If present do not present install dialog, but just the (updated) website. Or ask to use existing user/database or perform a fresh install.

Next days I will update 2 v1.2.0 and 1 v 1.4.0 websites to 1.5.0.

**Comment by Alkarex** [comment]
@Wanabo It could be better indeed, but both the git update (with a simple `git pull` command) and the built-in update process will not present you the install page again. In any case, the install script will warn you.

**Comment by Wanabo** [comment]
Persona was removed in 1.5.0. There is still a left over directory persona.

**Comment by Alkarex** [comment]
@Wanabo Thanks. https://github.com/FreshRSS/FreshRSS/pull/1239
