### ISSUE TITLE
Remove resource-priorities attributes

### ISSUE THREAD

**Issue by Wanabo** [FreshRSS/FreshRSS#1222]
Issue created on request, see https://github.com/FreshRSS/FreshRSS/issues/1219#issuecomment-240867176

Was playing with enabling/disabling lazy load setting because I noticed html errors. Enabled or disabled both settings produces lazyload="" postpone="" in output html. I was hoping to suppress html errors by disabling lazy load.

> the spec has been abandoned.

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/issues/1219#issuecomment-241013021

> the spec has been abandoned... https://www.w3.org/TR/resource-priorities/ https://lists.w3.org/Archives/Public/public-web-perf/2015May/0006.html http://caniuse.com/#feat=lazyload

**Comment by Alkarex** [comment]
Done https://github.com/FreshRSS/FreshRSS/pull/1295
Tests welcome
