### ISSUE TITLE
"You don’t have permission to access this page"

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [FreshRSS/FreshRSS#1224]
I can't seem to log into my self-hosted FreshRSS installation. No matter what I do, nothing works.

![https://i.imgur.com/n6qZL0A.png](https://i.imgur.com/n6qZL0A.png)

**Comment by Alkarex** [comment]
Hello,
What platform are you using, and which FreshRSS version?

If you are using an old PHP 5.3, we had a similar problem that has already been fixed (https://github.com/FreshRSS/FreshRSS/issues/1192, https://github.com/FreshRSS/FreshRSS/issues/1208)
Please give a try to the /dev version of FreshRSS https://github.com/FreshRSS/FreshRSS/issues/1219

**Comment by Unrepentant-Atheist** [comment]
https://www.kaputniks.org/inf.php

Even with the dev version I'm getting the same issue.

**Comment by Alkarex** [comment]
Could you please try to add  `'environment' => 'development',` in your `data/config.php` and then look at the FreshRSS logs (available from the Web interface)? If you can, please check your HTTP logs, and Web browser console.

**Comment by Alkarex** [comment]
Seems to be the follow-up of https://github.com/FreshRSS/FreshRSS/issues/1082
I am happy to help, if you can provide a bit more info :-)
You can also write me in private, if you would like to share non-public info (e.g. the address of your login page, etc.)

**Comment by Alkarex** [comment]
Did you find the problem, @Unrepentant-Atheist ?

**Comment by Unrepentant-Atheist** [comment]
No, but I unfortunately have zero time to do a proper investigation due to a large project at work currently. So I closed it. I'll reopen it, maybe somebody else has the problem and time to investigate.

Neither of your suggestions worked for me so far.

**Comment by ryanknapper** [comment]
I ran into this just this morning, after upgrading from 1.4.0 to 1.5.0.  For me, the problem was an incorrect password.

**Comment by Alkarex** [comment]
@Unrepentant-Atheist Feel free to re-open if still relevant. I can look at your deployment, if you like.

**Comment by JOduMonT** [comment]
> I ran into this just this morning, after upgrading from 1.4.0 to 1.5.0. For me, the problem was an incorrect password.

I may understand I cut and past the wrong password but FreshRSS should more clear about their password policy such as

- smaller than ...
- no special character nor only these one: ...

I'm just saying because most of the time I randomly use a 24 characters long password generated by Keepass which use alphanumeric and special characters but now even with only an alphanumeric password I still unable to login

**Comment by Frenzie** [comment]
@JOduMonT I'm reasonably sure there aren't any other than the one stated (7 characters). For example, I just tried this password and it works for me: `wkcD]OC/K[:-$/1ZT4UuytBPHXQxY~\yU1![4(%0G;kA_eklG?{,*m.r_w]\BO;+lSu*,/Qip#=rQshc;Q71yn_4OvOc[IOSv(12`.
