### ISSUE TITLE
Do not delete user custom theme when upgrading

### ISSUE THREAD

**Issue by GLLM** [FreshRSS/FreshRSS#1225]
Hi all,

along the different upgrades I've done on my serve, I noticed that every time my own theme is deleted and I need to get to my server to put the files back in the proper folder.

Is it possible to avoid deleting themes that are not in the update package ?
So that only the official themes get deleted then updated.

Many thanks,
GLLM

**Comment by Alkarex** [comment]
Related to https://github.com/FreshRSS/FreshRSS/issues/907

**Comment by GLLM** [comment]
Good news : when I upgraded yesterday from 1.4.0 to 1.5.0 my customized theme was kept and even remained as the active one.

Looks like this issue is fixed :)

MErci !

**Comment by Alkarex** [comment]
Thanks for the feedback :-)

**Comment by marienfressinaud** [comment]
Mmm, I didn't do anything special during the last update… @Alkarex did you?

**Comment by Alkarex** [comment]
Nope :-)

**Comment by GLLM** [comment]
Opération du St Esprit !

I don't care who did it, it works as I expected :) :)
But since no one fixed it : prolly means something else has been broken :S
