### ISSUE TITLE
In 1.4.0 and 1.5.0-dev custom ad script not working anymore

### ISSUE THREAD

**Issue by Wanabo** [FreshRSS/FreshRSS#1226]
I placed some custom html js code in aside_feed.phtml for showing ads.
In version 1.2.0 this is working perfectly.
But in version 1.4.0 and 1.5.0-dev it is not working any more.

Is this due to filtering somewhere in FreshRSS?
Is there perhaps an extension for custom ad code?

**Comment by Alkarex** [comment]
Hello @Wanabo 
This is likely due to the Content Security Policy (CSP) rules https://github.com/FreshRSS/FreshRSS/pull/1078
You should be able to make your script work by putting the JavaScript in an external file instead of inline

**Comment by Alkarex** [comment]
See also https://github.com/FreshRSS/FreshRSS/issues/1075

**Comment by Wanabo** [comment]
Thanks for pointing me in the right direction. But I ended up with stripping:
`switch (Minz_Request::controllerName()) {
            case 'index':
                header("Content-Security-Policy: default-src 'self'; child-src *; frame-src *; img-src * data:; media-src *");
                break;
            case 'stats':
                header("Content-Security-Policy: default-src 'self'; style-src 'self' 'unsafe-inline'");
                break;
            default:
                header("Content-Security-Policy: default-src 'self'");
                break;
        }`
from app/FreshRSS.php to get it to work.

Before that I tried different failed approaches:
- saving a copy of show_ads.js in p/scripts and make <script type="text/javascript" src="https://ad-vertise.nl/show_ads.js"></script> pointing to p/scripts.
- removed <script type="text/javascript" src="https://ad-vertise.nl/show_ads.js"></script> completely and added it to app/FressRSS.php
      Minz_View::appendScript(Minz_Url::display('/scripts/show_ads.js?' . @filemtime(PUBLIC_PATH . '/scripts/main.js')));
  But my script does not support async, don't know about defer.
- put complete code in ad.php and called with an include.

Nothing worked! Except the solution I started this post with.

These ads are important to me because I want to promote my own free ad exchange system.
Here is my complete snippet:
`<script type="text/javascript"></script>
<script type="text/javascript" src="https://ex-ads.com/show_ads.js"></script>`

Hope you can guide me how to solve this without editing app/FreshRSS.php

**Comment by Alkarex** [comment]
How do you currently load/include your script snippet? By editing `layout.html`?

**Comment by Wanabo** [comment]
No by editing /app/aside_feed.phtml
Two example sites running these ads:
http://www.nieuwskop.be/p/i/  version 1.2.0
http://www.nieuwskop.nl/p/i/ version 1.4.0
Both have some custom mods.
Latest with version 1.5.0-dev (no ads yet), http://www.daily-breaking-news.com/p/i/

**Comment by Alkarex** [comment]
All right. You can use something like:

``` html
<script src="../scripts/show_ads_vars.js" />
<script src="../scripts/show_ads.js" />
```

Where `show_ads_vars.js` contains your variables, so you end up without any inline JavaScript

**Comment by Alkarex** [comment]
P.S.: I can see that your script is using `document.write()`, which might cause problems, and could advantageously be replaced by a proper DOM injection (by doing so, you could also be compatible with async / defer, and fix your `&` encoding issues at the same time).
P.P.S: The issues you see are not specific to FreshRSS, but will be similar for any Web site using CSP, which is a current good security practice
