### ISSUE TITLE
Feedburner trouble

### ISSUE THREAD

**Issue by Wanabo** [FreshRSS/FreshRSS#1228]
Some feedburner feeds are not valid rss feeds because the webmaster configured them wrong in feedburner panel.

I found a way to make these feeds valid again by adding ?format=xml to the end of the feed url.
But after 1 time reading the feed correctly the url is stripped by FreshRSS from ?format=xml
Making the feed not working anymore.

Even adding ?format=xml directly in the database gets stripped.

How to fix this?

`PHP Notice: A feed could not be found at`http://feeds.feedburner.com/ComputableRss`; the status code is `200` and content-type is `text/html; charset=UTF-8` in /home/.../nieuwskop.nl/public_html/lib/SimplePie/SimplePie.php on line 1644
PHP Notice: A feed could not be found at `http://feeds.feedburner.com/boek9-berichten`; the status code is `200` and content-type is `text/html; charset=UTF-8` in /home/.../nieuwskop.nl/public_html/lib/SimplePie/SimplePie.php on line 1644
PHP Notice: A feed could not be found at `http://feeds.feedburner.com/nosvoetbal`; the status code is `200` and content-type is `text/html; charset=UTF-8` in /home/.../nieuwskop.nl/public_html/lib/SimplePie/SimplePie.php on line 1644
PHP Notice: A feed could not be found at `http://feeds.feedburner.com/scientias-wetenschap`; the status code is `200` and content-type is `text/html; charset=UTF-8` in /home/.../nieuwskop.nl/public_html/lib/SimplePie/SimplePie.php on line 1644`

**Comment by Alkarex** [comment]
All these feeds seem to work fine in my FreshRSS (current dev version).
What version of FreshRSS are you testing with?
In case a feed has the wrong mime type, you can add `#force_feed` at the end of the URL

**Comment by Wanabo** [comment]
These are reports from freshrss v 1.4.0.

Adding #force_feed does not solve it for me.

At the moment I am testing with original lib\lib_rss.php to see if the modified the user agent string is the culprit.

**Comment by Wanabo** [comment]
Indeed with original lib\lib_rss.php no problems.
Strange that only feedburner feeds seems to have trouble with my modification.
So the problem is created by me and not FreshRSS.

Thanks for your quick response! This issue can be closed or deleted.

**Comment by Alkarex** [comment]
Remember not to query feeds to often, or your risk having your IP and/or user-agent string banned
