### ISSUE TITLE
Update checker not up to date

### ISSUE THREAD

**Issue by chriscamacho** [FreshRSS/FreshRSS#1234]
When using v1.4.0 if I go into the update checker in configuration it doesn't "see" version 1.5.0 (or any update for that matter)

**Comment by Alkarex** [comment]
Yes, version 1.5.0 is out, and you can already update via e.g. `git pull` .
@marienfressinaud will push this new version to the update service soon.
So not a bug, but a delay, partially on purpose, to have more testing before offering the automatic updates.

---

https://github.com/FreshRSS/FreshRSS/issues/1219
https://github.com/FreshRSS/FreshRSS/issues/907

**Comment by chriscamacho** [comment]
okay fair enough! sorry didn't mean to be demanding - keep up the good work!

**Comment by marienfressinaud** [comment]
Yep, it's in my todo-list :)

**Comment by marienfressinaud** [comment]
It should be OK now :)
