### ISSUE TITLE
System update:  Updates are not detected

### ISSUE THREAD

**Issue by jwhipp** [FreshRSS/FreshRSS#1235]
Version 1.40 

When checking for updates, I am met with the error in the screen shot below.   Apache is running the service and has full R/W on the directory structure. I'm not seeing any error logging on the subject either.

![selection_004](https://cloud.githubusercontent.com/assets/556332/18107732/6b2b32ce-6ec6-11e6-8d42-86c43ed4eab2.png)

**Comment by aledeg** [comment]
Duplicate of #1234

**Comment by marienfressinaud** [comment]
It should be OK now :)
