### ISSUE TITLE
View attachments / enclosures directly in article display

### ISSUE THREAD

**Issue by donlencho** [FreshRSS/FreshRSS#1236]
Hello,
I have been using Tiny Tiny RSS for a while but recently switched to Fresh mostly because TTRSS doesn't work on my mobile.
There is one essential thing I'm missing: the ability to see attached files as a direct link, which allows for an easy download (useful for podcasts for instance). Here is a pic from TTRSS with an example podcast and the attached mp3 appears, I can just click on it and download it. In Fresh, I just see the player and if I want to download the mp3, I have to go to "manage" next to the feed, then select "open feed URL" to finally find the attached file. Pretty annoying. I can also get the link with a right click on the player, but it depends on the browser's implementation and it's not always straightforward.
So is there a way to show it already, something that I'm missing in the settings?
Or if not could it be integrated?
Thank you for your consideration (and for FreshRSS obviously!),

![attachment_in_ttrss](https://cloud.githubusercontent.com/assets/8362161/18226725/87e8c4a6-7210-11e6-823e-9c40026c6a50.png)

**Comment by Alkarex** [comment]
Welcome @donlencho
See this proposition https://github.com/FreshRSS/FreshRSS/issues/1238

![default](https://cloud.githubusercontent.com/assets/1008324/18227369/58aeca66-7222-11e6-8a25-1f8f9470101b.png)

**Comment by Alkarex** [comment]
P.S.: A click on 💾 will auto-start the download in Edge and Chrome, but not in Firefox, except if the media is from the same domain as FreshRSS.
http://caniuse.com/#search=download

**Comment by Alkarex** [comment]
P.P.S.: The changes will only be visible for the new items and/or new feeds.

**Comment by donlencho** [comment]
Thank you! Looking forward to the next release then!

**Comment by Alkarex** [comment]
Did you have a chance to test the pull request? If not, could you test if I merge the feature in the /dev version of FreshRSS?

**Comment by donlencho** [comment]
I just did, seems perfectly functional, thank you for your prompt implementation!
There is just one feed for which it's not working, but I think it's due to an encoding problem on their side, if you want to have a look: http://rss.rtbf.be/media/rss/audio/lp-decadrages_recent.xml
One other thing for consideration though: probably not due to FreshRSS, but the icon is not displaying properly for me, I just see the unicode box (using Linux Mint).
Thanks again,

**Comment by Alkarex** [comment]
The feed http://rss.rtbf.be/media/rss/audio/lp-decadrages_recent.xml does not contain enclosures / attachments / podcasts:

``` xml
<item>
    <title>D&#233;cadrages, Progr&#232;s films 2/2, 21/08/2016 - 21/08/2016</title>
    <link>http://www.rtbf.be/radio/podcast/player?id=2126197&amp;channel=lapremiere</link>
    <pubDate>Sun, 21 Aug 2016 00:00:00 +0200</pubDate>
    <description>
        <![CDATA[Petite histoire de Progrès films - Jean-Louis Dupont reçoit Morgan di Salvia]]>
    </description>
    <author>D&#233;cadrages</author>
    <guid>http://www.rtbf.be/radio/podcast/player?id=2126197&amp;channel=lapremiere</guid>
    <itunes:author>D&#233;cadrages</itunes:author>
    <itunes:duration>0:26:34</itunes:duration>
    <itunes:subtitle>Petite histoire de Progr&#232;s films - Jean-Louis Dupont re&#231;oit Morgan di Salvia</itunes:subtitle>
    <itunes:summary>Petite histoire de Progr&#232;s films - Jean-Louis Dupont re&#231;oit Morgan di Salvia</itunes:summary>
    <itunes:keywords>RTBF,lapremiere,D&#233;cadrages,</itunes:keywords>
    <itunes:block>yes</itunes:block>
    <itunes:image href="http://www.static.rtbf.be/radio/radio/images/logo/1400x1400/lapremiere-1400x1400.png"  />
</item>
```

**Comment by Alkarex** [comment]
The emoji 💾 works fine in Firefox 48 on Ubuntu 16.04. Is your Mint based on an older version of Ubuntu?

![ubuntu](https://cloud.githubusercontent.com/assets/1008324/18233698/7e67669c-72ee-11e6-8b67-fcab44bf397a.png)

**Comment by donlencho** [comment]
Yes, based on Ubuntu 14.04.
As for the feed I sent, I do see an attached mp3 in Tiny Tiny RSS, see the picture below.

![feed_mp3](https://cloud.githubusercontent.com/assets/8362161/18239746/977c6ff2-7347-11e6-845c-e168ecb20448.png)

**Comment by Alkarex** [comment]
I do not know where this link to an MP3 file comes from. There is no such link in the RSS feed itself `http://rss.rtbf.be/media/rss/audio/lp-decadrages_recent.xml`, and not from the article's link either (`http://www.rtbf.be/radio/podcast/player?id=2126197&channel=lapremiere`). Are you sure it is the same RSS feed you are using?

**Comment by Alkarex** [comment]
Ah, Ubuntu 14.04 is two years old. The current one is 16.04 (LTS), with 16.10 approaching. If you update your Mint to version 18+, it should work.

**Comment by donlencho** [comment]
Yes but it's an LTS supported until 2019... Anyway, not a big problem.
As for the feed, it's mysterious. The article links do link to a player which loads the audio file, it must come from there. But again, not a big problem as it's not a regular rss way of attaching a file.
Thanks for digging into this.

**Comment by Alkarex** [comment]
Ok. It would be possible to overwrite the emoji with a CSS rule loading an image, if it is a problem.

**Comment by donlencho** [comment]
maybe it is "safer", but up to you!

**Comment by Alkarex** [comment]
Ok. Let's try with the current approach (it is possible for users to add a custom CSS rule if needed) and come back to it later if needed

**Comment by donlencho** [comment]
Just an update after testing on Linux Mint 18 (based on Ubuntu 16.04), same issue: unicode bloc in Firefox and empty rectangle in Chromium/Vivladi.

**Comment by Alkarex** [comment]
Damn. Works out of the box on Ubuntu 16.04 with Firefox (48), Chromium (52), Midori (0.5.11).
It looks like the emoji can be provided both by the OS (in my case, the `Symbola` font) and [recent Firefox versions](https://www.linuxbabe.com/browser/install-firefox-developer-edition-ubuntu-16-04-linux-mint-18) when not available at OS level.
Could you try to install the [`ttf-ancient-fonts`](apt://ttf-ancient-fonts) package? (It is [installed by default on Ubuntu](http://releases.ubuntu.com/16.04/ubuntu-16.04-desktop-amd64.manifest) - I cannot find what default packages are installed in Mint)

``` sh
sudo apt-get install ttf-ancient-fonts
```

**Comment by donlencho** [comment]
Installing fonts-symbola did the trick, thanks.

**Comment by truongan** [comment]
I'm sorry to beat up a dead horse. But I have a feed with attachment/enclosure but my installation of freshrss won't show the download icon: http://nethd.org/torrentrss.php?rows=10&cat=401&standard401=415,416
I'm new to fressh and clueless of where to start looking, any help would be very appreciate

**Comment by Alkarex** [comment]
@truongan Should be fixed in https://github.com/FreshRSS/FreshRSS/pull/1522
It was because the MIME type `application/x-bittorrent` was not supported.
Could you please give it a try? For instance by trying the [/dev version of FreshRSS](https://github.com/FreshRSS/FreshRSS/tree/dev).

**Comment by truongan** [comment]
Wow, that was blazing fast response. I was hesitate to checkout the whole dev tree. But I can confirm that with a simple `git cherry-pick e9e6fc3`  newly actualized feed now show the download icon

**Comment by truongan** [comment]
Err, I spoke too soon. #1522 cause a regression IMO. Now feed WITHOUT attatchment will display a download icon as well, which link to nowhere: `<a download="" href="">💾</a>`

**Comment by Alkarex** [comment]
@truongan Indeed. Please check https://github.com/FreshRSS/FreshRSS/pull/1523

**Comment by truongan** [comment]
Sorry for the long reply. I can confirm #1523 fix the regression. Very quick work indeed @Alkarex

**Comment by Alkarex** [comment]
Thanks for the feedback :-)

**Comment by squromiv** [comment]
I`ve faced with a problem.
Check for example the [feed](https://feed.eugenemolotov.ru/?action=display&bridge=Telegram&username=telegram&format=Atom). As I understood, attached pictures are displayed in FreshRSS as duplicated images. To make it clear what i mean, compare how it looks in

**TinyTinyRSS**

![TTRSS](https://user-images.githubusercontent.com/15985877/59886165-3132e880-93be-11e9-846c-24e7d0a17ac4.png)

**RSSOwl**

![RSSOwl](https://user-images.githubusercontent.com/15985877/59886195-51fb3e00-93be-11e9-9590-2ab0b595762c.png)

**FreshRSS**

![FreshRSS](https://user-images.githubusercontent.com/15985877/59886218-6f300c80-93be-11e9-8b3a-f9bfffc8a36b.png)

**Comment by Alkarex** [comment]
@squromiv Indeed. The reason is that there are some feeds were the relevant images are only in the "attachments", in which case I believe it is useful to display them inline.
Your feed is an example with the data duplicated in the feed itself (it is provided both inline as an `img` and as an enclosure). We could try to check whether a given attachment is already provided inline to avoid duplicates. Could you please open a new issue?

```xml
<entry>
		<title type="html">Today&amp;amp;#39;s update allows you to add entire group chats as exceptions to any privacy settings....</title>
		<published>2019-06-01T11:13:26+00:00</published>
		<updated>2019-06-01T11:13:26+00:00</updated>
		<id>https://t.me/telegram/112</id>
		<link rel="alternate" type="text/html" href="https://t.me/telegram/112"/>
		
		<content type="html">&lt;div class="tgme_widget_message_text js-message_text" dir="auto"&gt;Today&amp;#39;s update allows you to add entire &lt;b&gt;group chats&lt;/b&gt; as exceptions to any &lt;b&gt;privacy settings&lt;/b&gt;. Settings will adapt as people join or leave the groups. &lt;br/&gt;&lt;br/&gt;We&amp;#39;ve also added a new privacy setting for &lt;b&gt;Who Can See My Phone Number&lt;/b&gt;.&lt;br/&gt;&lt;br/&gt;Channel admins can now link a &lt;b&gt;discussion group&lt;/b&gt; to their channel. And developers can make bots that can &lt;b&gt;seamlessly authorize&lt;/b&gt; you on web services.&lt;br/&gt;&lt;br/&gt;Any public channel can now be &lt;b&gt;viewed&lt;/b&gt; from the web, even without a Telegram account.&lt;br/&gt;&lt;br/&gt;Read more on our blog:&lt;br/&gt;&lt;a href="https://telegram.org/blog/privacy-discussions-web-bots" target="_blank" rel="noopener"&gt;https://telegram.org/blog/privacy-discussions-web-bots&lt;/a&gt;&lt;/div&gt;&lt;blockquote&gt;&lt;a href="https://telegram.org/blog/privacy-discussions-web-bots"&gt;&lt;img src="https://cdn4.telesco.pe/file/H8Zp3K778OY2DfG-KsZQOq7nXi-Y6g5dl6BaZX-c9048YQ9hsgZMCBZ1JAxSwUPDe1vPaQ4z6vsXK3KZXmqzK7D802L3JAHs8dOXVdglyG6xM0WelJ_2SaeMwSbqj3EwUYPtYa725Id1wZjBED-cXZlzg925q5Bz3YfL04lNjG2UCvamz9S5U5ge8Td7Y_wq5de2NkWL4OSjUglk1Dxz3pQoqSXsXDVrj6hNdDn3L8DLnam9LsJHHGiATp3dMhFDifYPt8zrjLgr_A9hRagK0o5bR0RQ9wYBfyqbW4UdV-CO7Y7r-cwS3LqcNDtBjZciBpxorbJ2rJhQmxRHpB4oTg.jpg"/&gt;&lt;/a&gt;&lt;br&gt;&lt;a href="https://telegram.org/blog/privacy-discussions-web-bots"&gt;
Focused Privacy, Discussion Groups, Seamless Web Bots and More - Telegram&lt;/a&gt;&lt;br&gt;Telegram is about privacy. In 2014, we pioneered granular privacy settings in messaging. Today we are making them even more flexible with exceptions for group chats.&lt;/blockquote&gt;</content>
		<link rel="enclosure" href="https://cdn4.telesco.pe/file/H8Zp3K778OY2DfG-KsZQOq7nXi-Y6g5dl6BaZX-c9048YQ9hsgZMCBZ1JAxSwUPDe1vPaQ4z6vsXK3KZXmqzK7D802L3JAHs8dOXVdglyG6xM0WelJ_2SaeMwSbqj3EwUYPtYa725Id1wZjBED-cXZlzg925q5Bz3YfL04lNjG2UCvamz9S5U5ge8Td7Y_wq5de2NkWL4OSjUglk1Dxz3pQoqSXsXDVrj6hNdDn3L8DLnam9LsJHHGiATp3dMhFDifYPt8zrjLgr_A9hRagK0o5bR0RQ9wYBfyqbW4UdV-CO7Y7r-cwS3LqcNDtBjZciBpxorbJ2rJhQmxRHpB4oTg.jpg" type="image/jpeg" />

		
	</entry>
```

**Comment by squromiv** [comment]
@Alkarex 
I have found the same existing issue. #1668 Could you open it again?

**Comment by squromiv** [comment]
Or should i create a new one?
