### ISSUE TITLE
Communication

### ISSUE THREAD

**Issue by marienfressinaud** [FreshRSS/FreshRSS#124]
Lors de la sortie de la version 1.0, il faudra penser à communiquer réellement sur FreshRSS.
- Acheter nom de domaine avec site fait sur-mesure (celui actuel est un simple template Github, pas envie de dépendre d'eux pour une version stable)
- Écrire un journal LinuxFR
- En parler plus largement aux gens qui cherchent des alternatives

**Comment by marienfressinaud** [comment]
La liste des articles de blog continue sur https://github.com/FreshRSS/freshrss.org/issues/9 en attendant une page dédiée sur freshrss.org (je n'en vois, pour le moment, pas l'intérêt)

**Comment by marienfressinaud** [comment]
Je ferme ce ticket puisque la 1.0 est sortie depuis un moment et que la communication se fait au fil de l'eau.

**Comment by Alwaysin** [comment]
http://blog.niqnutn.com/index.php?article22/lecteur-de-flux-rss-atom :)

**Comment by marienfressinaud** [comment]
Mais pourquoi les gens qui écrivent des articles aussi complets ne nous aident-ils pas pour la doc ? :'( L'article est vraiment très bien !

**Comment by Alwaysin** [comment]
Quand j'ai vu les vidéos... woah ! C'est du super boulot. Je te suggère de prendre contact avec lui.

**Comment by Alkarex** [comment]
Quelques bons articles (en retard) de plus :-) :
- http://wilfriedcaruel.svnet.fr/2014/05/easyrss-lapplication-android-opensource-de-la-semaine/
- http://pled.fr/?p=8413
- https://angristan.fr/freshrss-un-lecteur-rss-libre-a-auto-heberger/
- http://genma.free.fr/?Yunohost-FreshRSS-et-EasyRSS-pour-Android

**Comment by marienfressinaud** [comment]
https://github.com/FreshRSS/freshrss.org/issues/9 ;)

**Comment by Alkarex** [comment]
@marienfressinaud Je me disais bien qu'il y avait une autre liste, mais je ne la retrouvais plus...

**Comment by Alwaysin** [comment]
I didn't know where to put this but if someone is interested in answering: https://www.reddit.com/r/selfhosted/comments/5cvdo0/freshrss_vs_tiny_tiny_rss_ttrss/

**Comment by Alkarex** [comment]
Thanks @Alwaysin . I do not think I should answer myself, but here is some quick input form my side.
FreshRSS also has a couple of Android apps (see https://github.com/FreshRSS/FreshRSS#compatible-clients ) (edit: and an [extension for compatibility with TT-RSS](https://github.com/FreshRSS/Extensions/tree/master/xExtension-TTRSS_API)). In my opinion, FreshRSS does a better job for self-hosting without using too many resources. Another central point for me is that we try to be a friendly and caring community in FreshRSS, which contrasts with the very aggressive and rude behaviours repeatedly observed on TT-RSS's side, which are against my open-source values (I am not the only one, see e.g. http://alternativeto.net/software/freshrss/reviews/ , http://alternativeto.net/software/tiny-tiny-rss/reviews/ ).
More generally, I personally try to support a distributed Internet with e.g. RSS (so I am even happy when people use proprietary systems like Feedly compared to e.g. Twitter), and self hosting (so I am also happy when people use alternatives to FreshRSS such as Leed, Kriss Feed, Sismics Reader, etc.).

**Comment by Alwaysin** [comment]
I agree with all you said. I am a bit disappointed that much people are recommending TT-RSS ; I've made a little post.
