### ISSUE TITLE
Export: add date to file name

### ISSUE THREAD

**Issue by donlencho** [FreshRSS/FreshRSS#1240]
Just an idea, if you want to archive your feeds with an export, it could be convenient.

**Comment by Alkarex** [comment]
@donlencho I have just added the feature https://github.com/FreshRSS/FreshRSS/pull/1275
Please test the /dev branch of FreshRSS if you can, and if possible for multiple combination of import/export.

**Comment by donlencho** [comment]
Thanks! I could just test the exports in my current install, I don't have time to install another branch for the moment and can't mess too much with my feeds.
Just one thing, the ompl file is named opml.xml (from line 476 of your code), not sure it's on purpose, it used to be just .opml

**Comment by Alkarex** [comment]
You can just replace this file on your instance: https://github.com/Alkarex/FreshRSS/blob/2621e1cc49818e2bd5566d5072a8a7dc537536d0/app/Controllers/importExportController.php
Yes, the `.opml.xml` is on purpose.

**Comment by donlencho** [comment]
yes, this is what I did, and the exports are fine, I just didn't check the imports.
