### ISSUE TITLE
Change MySQL port

### ISSUE THREAD

**Issue by EtienneM** [FreshRSS/FreshRSS#1241]
Hi !

I would like to install FreshRSS on a server but my provider changed the port on which MySQL listen. When I configure FreshRSS and I specify as a host `hostname:30777`, I get the following error:

```
Veuillez modifier la valeur pour correspondre au format demandé
```

Probably because of the `:`. Any chance to be able to specify it?

FYI I have been able to insert the `:` by deleting the pattern attribute using Firefox web developers tools

**Comment by Alkarex** [comment]
Yes, I will try to add that. Reference: http://php.net/pdo.construct

**Comment by Alkarex** [comment]
@EtienneM Here is a suggestion https://github.com/FreshRSS/FreshRSS/pull/1244
Not tested at all. Please give it a try if you can.

**Comment by Alkarex** [comment]
Available in /dev
