### ISSUE TITLE
Instruction to configure by hand (without UI)

### ISSUE THREAD

**Issue by EtienneM** [FreshRSS/FreshRSS#1242]
Hi!

I would like to deploy FreshRSS on a [PaaS platform](https://scalingo.com/). On such a platform, we need to modify the configuration file by hand and not using the initial web UI. Indeed, when I use the web UI, everything is then written in `data/config.php` but I cannot get this file back. Is there any place with instruction on how to fully configure FreshRSS thrgouh configuration file? I understood that it is required to create the `data/config.php` file based on `data/config.default.php` but I don't know how to configure the user and the password. I also understood that I need to remove the `data/do-install.txt` file.

**Comment by Alkarex** [comment]
Hello @EtienneM This seems to be quite related to https://github.com/FreshRSS/FreshRSS/issues/1095 , which should add some of the features you are lacking. I suggest we continue the discussion there.
