### ISSUE TITLE
OVH: Update to 1.5.0 crashes

### ISSUE THREAD

**Issue by symac** [FreshRSS/FreshRSS#1243]
Hello,
my freshrss install was 1.2.0, going to the check for update page I was offered to update to 1.4.0, everything went fine, then checking again for a new version I was offered the 1.5.0, I decided to run this second update and it crashed. I now get an error "### Fatal error! ### See logs files." and in the log files I can see an error saying "Access to database is denied for". 

Looking at the latest CHANGELOG I can see that mysql 5.5.\* is required, I am on an OVH shared hosting and according to my phpinfo() the "Client API version" for mysql is 5.1.73, I assume it might be the issue.

So my questions are : 
- is this a correct assumption regarding the issue, should I just revert the files on my server to 1.4.0 version ? 
- should not the update process check that the mysql version is ok and warn the user if not before breaking everything ? 

Btw thanks for the great work, first time I encounter a breaking bug with Freshrss after all this time !

**Comment by Alkarex** [comment]
Hello,
If you get this error message, it is more probably a password problem for accessing your database.
During update from version 1.4.0, nothing should change regarding the database, and you should be able to run FreshRSS 1.5.0 even on older MySQL versions (MySQL 5.5.3 is from March 2010), as long as you do not attempt to read feeds that contain advanced Unicode such as emojis 💾 in the titles of their entries.
Indeed, we should add a version check for the database.

**Comment by symac** [comment]
Hello,
giving the issue a second chance this morning I can confirm that 1.5.0 does not work on my OVH shared hosting for the moment. Trying a clean install I know the database connection is working fine as three tables *category *entry *feed have been created with the test prefix I have set for this clean install. But afterwards, the login page redirects me to an error on /p/i/

Will let you know if I can find anything.

**Comment by symac** [comment]
Ok, I have now found the issue, related to the change regarding emojis I imagine, not only does it crash when you try to read feeds containing special characters as I have a clean install without any feed configured, but I have found that the [change in ModelPDO.php](https://github.com/FreshRSS/FreshRSS/commit/fe18d12551f626c56257f825caf8f97a4a5461ce#diff-e04a6e853bb48d50b8ada0a243b8ee4a) was the origin of the crash. 

According to phpmyadmin on my server the mysql version is 5.5.46-0+deb7u1-log so I believe it should be ok but there seems to be an issue with this specific encoding. I will stay with the 1.4.0 for the moment but it should be good to improve the prerequites checking at some point to prevent users from crashing their system while trying to update.

**Comment by Alkarex** [comment]
Thank you for testing. Do you have any error message?
There are two cases:
- When making a clean install of 1.5.0, the charset utf8mb4 is used immediately. Did you have a chance of trying a clean install?
- When updating from 1.4.0, we only update to utf8mb4 the first time it is needed (special Unicode characters detected).

**Comment by Alkarex** [comment]
Link to https://github.com/FreshRSS/FreshRSS/issues/1219

**Comment by symac** [comment]
@Alkarex I did a clean install of 1.5.0, reached the end of the install process and the 3 tables are created but then, when I try to follow the link to open the app at the end of the install process (don't remember the name), I see the big blue button for a second, then am redirected to an error screen that just tell me there is a Fatal error and suggests to look the logs. I have found that changing back the two occurences of utf8mb4 in ModelPDO.php were fixing the issue.

The same happens when trying to run the upgrade fro 1.4 to 1.5, I have not tried to apply the same fix on this version but the error seems to be the same.

**Comment by Alkarex** [comment]
Ah indeed, I was wrong: utf8mb4 is of course needed immediately to open the connection. I will have to test whether utf8 could maybe be enough for the connexion itself.

**Comment by Alkarex** [comment]
But utf8mb4 should be available already from MySQL 5.5.3 https://dev.mysql.com/doc/refman/5.5/en/charset-unicode-utf8mb4.html so it is a bit strange that you are facing problems with a version 5.5.46

**Comment by Alkarex** [comment]
Could you please try to run a little test?

``` php
<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

$dbHost = 'localhost';
$dbName = 'freshrss';
$dbUser = 'freshrss';
$dbPassword = 'XXX';
$table = 'freshrss_alex_category';


header('Content-Type: text/plain;charset=UTF-8');

echo "PHP version:\t", PHP_VERSION, "\n";

$db = new PDO('mysql:host=' . $dbHost . ';dbname=' . $dbName . ';charset=utf8mb4',
                $dbUser,
                $dbPassword,
                array(
                    PDO::ATTR_EMULATE_PREPARES => false,
                    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
                )
              );

echo "MySQL version:\t", $db->getAttribute(PDO::ATTR_SERVER_VERSION), "\n";

$stmt = $db->query('SELECT VERSION()');
$results = $stmt->fetchAll(PDO::FETCH_ASSOC);

print_r($results);

$stmt = $db->query('SELECT * FROM ' . $table);
$results = $stmt->fetchAll(PDO::FETCH_ASSOC);

print_r($results);
```

**Comment by symac** [comment]
Sure : 

```
PHP version:    5.5.37

<b>Fatal error</b>:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2019] Can't initialize character set utf8mb4 (path: /usr/share/mysql/charsets/)' in /home/opensour/www/outils_perso/frssdev/test.php:25
Stack trace:
#0 /home/opensour/www/outils_perso/frssdev/test.php(25): PDO-&gt;__construct('mysql:host=mysq...', 'opensourdrup', 'XXXX', Array)
#1 {main}
  thrown in <b>/home/opensour/www/outils_perso/frssdev/test.php</b> on line <b>25</b><br />
```

**Comment by symac** [comment]
i have noticed that using set names utf8mb4 seems to be ok, at least it doesn't return any error message, bug using it in the PDO init string will generate an error.

**Comment by Alkarex** [comment]
Ok, thanks. And when you use `charset=utf8`, what do you get an an output (in particular, the MySQL version)?

**Comment by symac** [comment]
PHP version:    5.5.37
MySQL version:  5.5.46-0+deb7u1-log
Array
(
    [0] => Array
        (
            [VERSION()] => 5.5.46-0+deb7u1-log
        )

)
Array
(
    [0] => Array
        (
            [id] => 1
            [name] => Sans catégorie
        )

)

**Comment by Alkarex** [comment]
Merci. So, now I need to find why utf8mb4 does not work on your instance, despite being > 5.5.3...
BWT, you can alternatively use SQLite...

**Comment by Alkarex** [comment]
Could you please try this new test?

``` php
<?php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

$dbHost = 'localhost';
$dbName = 'freshrss';
$dbUser = 'freshrss';
$dbPassword = 'XXX';
$table = 'freshrss_alex_category';


header('Content-Type: text/plain;charset=UTF-8');

echo "PHP version:\t", PHP_VERSION, "\n";

$db = new PDO('mysql:host=' . $dbHost . ';dbname=' . $dbName . ';charset=utf8',
                $dbUser,
                $dbPassword,
                array(
                    PDO::ATTR_EMULATE_PREPARES => false,
                    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
                )
              );

echo "MySQL version:\t", $db->getAttribute(PDO::ATTR_SERVER_VERSION), "\n";

$stmt = $db->query('SELECT VERSION()');
$results = $stmt->fetchAll(PDO::FETCH_ASSOC);
print_r($results);

$stmt = $db->query("SELECT CHARACTER_SET_NAME AS cs FROM information_schema.CHARACTER_SETS WHERE CHARACTER_SET_NAME LIKE 'utf%'");
$results = $stmt->fetchAll(PDO::FETCH_ASSOC);
print_r($results);

$db = new PDO('mysql:host=' . $dbHost . ';dbname=' . $dbName . ';charset=utf8mb4',
                $dbUser,
                $dbPassword,
                array(
                    PDO::ATTR_EMULATE_PREPARES => false,
                    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
                )
              );

$stmt = $db->query('SELECT * FROM ' . $table);
$results = $stmt->fetchAll(PDO::FETCH_ASSOC);
print_r($results);
```

Voir aussi (il semblerait que vous ayez une solution) :
- https://forum.ovh.com/showthread.php/107195-Drupal-8?s=65873498973217cafc054599e4ce230a&p=656153&viewfull=1#post656153
- https://forum.ovh.com/showthread.php/109560-Changer-l-environnement-d-ex%C3%A9cution-de-vos-h%C3%A9bergements-web-%28drupal8-TLS1-2%29
- https://docs.ovh.com/fr/fr/web/hosting/modifier-lenvironnement-dexecution-de-mon-hebergement-web/
- https://www.howtoforge.com/community/threads/utf8mb4-support-in-mysql-5-5-3-feature-request-patch.66822/

**Comment by symac** [comment]
the utf8mb4 appears in the list but trying to use it as a charset still generates an error :

```
PHP version:    5.5.37
MySQL version:  5.5.46-0+deb7u1-log
Array
(
    [0] => Array
        (
            [VERSION()] => 5.5.46-0+deb7u1-log
        )

)
Array
(
    [0] => Array
        (
            [cs] => utf8
        )

    [1] => Array
        (
            [cs] => utf8mb4
        )

    [2] => Array
        (
            [cs] => utf16
        )

    [3] => Array
        (
            [cs] => utf32
        )

)
<br />
<b>Fatal error</b>:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2019] Can't initialize character set utf8mb4 (path: /usr/share/mysql/charsets/)' in /home/opensour/www/outils_perso/frssdev/test.php:46
Stack trace:
#0 /home/opensour/www/outils_perso/frssdev/test.php(46): PDO-&gt;__construct('mysql:host=mysq...', 'XXXXX
#1 {main}
```

I will give a try to the different links suggested.

**Comment by Alkarex** [comment]
Anything new? Did it work when updating the OVH settings?

**Comment by Alkarex** [comment]
Feel free to re-open if needed.

**Comment by ghost** [comment]
The same for me, after the update (one week ago), impossible to access my freshrss. When installing a new one, it cannot connect to the old mysql database. It's only working with sqlite but in this case i loose my feeds.
Mysql server : 5.1.73
Error message:
"Arf ! Vérifiez les informations d’accès à la base de données. : SQLSTATE[42000] [1115] Unknown character set: 'utf8mb4'"

**Comment by Alkarex** [comment]
@majoux OVH offers the possibility to upgrade to a newer MySQL version supporting `utf8mb4`. See the links a bit higher up https://github.com/FreshRSS/FreshRSS/issues/1243#issuecomment-244941741
https://docs.ovh.com/fr/fr/web/hosting/modifier-lenvironnement-dexecution-de-mon-hebergement-web/

**Comment by Alkarex** [comment]
@majoux Please give a try to https://docs.ovh.com/fr/fr/web/hosting/modifier-lenvironnement-dexecution-de-mon-hebergement-web/ and let me know whether that helps.

**Comment by ghost** [comment]
I'm not using ovh, I use a Debian Squeeze that's why mysql is so old.
My server is in production, I can't change the Debian version easily.

**Comment by Alkarex** [comment]
@majoux Ok. Debian Squeeze is not suited for production anymore as it has passed its end-of-life (February 2016). Concretely, if you cannot upgrade Debian (which seems to be needed anyway), the options are:
- Use SQLite;
- Stick to FreshRSS 1.4.
- Do a little manual patch https://github.com/FreshRSS/FreshRSS/issues/1297#issuecomment-252514892 by replacing `utf8mb4` by `utf8` in the source code.
- Make a manual update of MySQL to a newer version.
- Give a try to PostgreSQL in FreshRSS 1.6 (I have not checked the minimal version of PostgreSQL)

**Comment by Alkarex** [comment]
For reference: https://github.com/FreshRSS/FreshRSS/issues/1153

**Comment by Alkarex** [comment]
Suite de https://github.com/FreshRSS/FreshRSS/issues/1328#issuecomment-255532146
@symac Avez-vous essayé https://docs.ovh.com/fr/fr/web/hosting/modifier-lenvironnement-dexecution-de-mon-hebergement-web/ ?

**Comment by Alkarex** [comment]
@symac Un autre utilisateur a testé avec succès de passer l'environnement OVH de legacy à stable https://github.com/FreshRSS/FreshRSS/issues/1369#issuecomment-259935668
