### ISSUE TITLE
target="_blank" vulnerability

### ISSUE THREAD

**Issue by Cypouz** [FreshRSS/FreshRSS#1245]
As explained [here](https://dev.to/ben/the-targetblank-vulnerability-by-example), it would be nice to use `rel="noopener noreferrer"` with `target="_blank"` in links to avoid any risk of phishing.

**Comment by Alkarex** [comment]
Interesting :+1: 
I will have to check if this not already covered by `<meta name="referrer" content="never" />`
https://github.com/FreshRSS/FreshRSS/pull/1210

**Comment by Alkarex** [comment]
I have quickly checked that `<meta name="referrer" content="never" />` is not enough, and that `rel="noreferrer"` works in Firefox 48, Edge 25, Chrome 53.

**Comment by Alkarex** [comment]
Pull request https://github.com/FreshRSS/FreshRSS/issues/1246

**Comment by Alkarex** [comment]
Should be solved in /dev branch. Please give it a try.
