### ISSUE TITLE
Subscribe URL 

### ISSUE THREAD

**Issue by jwhipp** [FreshRSS/FreshRSS#1247]
I'd like to get FreshRSS working with this tool: 

https://chrome.google.com/webstore/detail/rss-subscription-extensio/nlbjncdgjeocebhnmkbbbdekmmmcbfjd

One of the things required to configure it to work with FreshRSS is a URL for subscriptions as indicated in the image below:

![selection_004](https://cloud.githubusercontent.com/assets/556332/18363030/917b8d1a-75c5-11e6-99ca-3c8dd471691c.png)

What URL beyond https://myfreshrss.example/p/i/ to make this work?

**Comment by Alkarex** [comment]
Without having tried, something like that:
`https://myfreshrss.example/p/i/?c=feed&a=add&url_rss=%s`

P.S.: If you can, try to have your Web server pointing to the `./freshrss/p/` directory instead of `./freshrss/` so your URL becomes `https://myfreshrss.example/i/`

**Comment by jwhipp** [comment]
Ok I tried that and I get this:

The data could not be converted to UTF-8. You MUST have either the iconv or mbstring extension installed. Upgrading to PHP 5.x (which includes iconv) is highly recommended. [http://www.noobslab.com/feeds/posts/default]

I am running PHP 7 so iconv should be in it.   I also installed php-mbstring, to no avail.

If I grab the URL manually and plug it in, it works fine.

**Comment by Alkarex** [comment]
I have just tested this Chrome extension, and it seems to work fine for me, also when testing with `http://www.noobslab.com/`. My setup is running on Ubuntu 16.04 with PHP 7.0.8, and the extensions listed on https://github.com/FreshRSS/FreshRSS/#example-of-full-installation-on-linux-debianubuntu
In particular, try:

``` sh
apt install php-intl php-mbstring
```

Please provide more information about your setup if you still get problems.

**Comment by jwhipp** [comment]
I came across a different URL I wanted to add and it worked => http://feeds.arstechnica.com/arstechnica/index/ 

There must've been something mangling it before, but I am not sure.

PHP 7.0.8-0ubuntu0.16.04.2 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8-0ubuntu0.16.04.2, Copyright (c) 1999-2016, by Zend Technologies

I had already added mbstring and tried it again before I submitted the issue.

**Comment by Alkarex** [comment]
Did you have `php-intl` as well?
I am considering showing the registration address somewhere in the Web configuration https://github.com/Alkarex/FreshRSS/commit/2954292b0afe930511c72548571dfd3b2c7a43c8 but I am not sure that is a good idea (I am afraid it can be confusing)

![link](https://cloud.githubusercontent.com/assets/1008324/18648134/95e81998-7eb9-11e6-93f6-88826a3b8996.png)

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/1292

**Comment by Alkarex** [comment]
Implemented in #1660
