### ISSUE TITLE
PHP Warning:  file_put_contents(./!hub.json): failed to open stream: Permission denied

### ISSUE THREAD

**Issue by StephenAtty** [FreshRSS/FreshRSS#1248]
Everything seems to be running OK but I'm getting:

PHP Warning:  file_put_contents(./!hub.json): failed to open stream: Permission denied in /webstuff/rss/p/api/pshb.php on line 68

in my php error logs

Line  68 is

file_put_contents('./!hub.json', json_encode($hubJson));

I'm running 1.5.0 and this only started happening when I upgraded to 1.5.0 earlier this week.

**Comment by Alkarex** [comment]
Please check the permissions of your folders. FreshRSS (via PHP) must be able to write in all files and sub-folders of `./data/`

Example for Ubuntu / Apache:

```
cd FreshRSS
sudo chown -R :www-data .
sudo chmod -R g+w ./data/
```

**Comment by StephenAtty** [comment]
The thing is that it was working OK - it seemed to have gone wrong when I upgraded using the built in upgrade tool.  The installation check didn't report any problems

I've changed the permissions and it seems to be OK now
