### ISSUE TITLE
Number of RSS items in public URL

### ISSUE THREAD

**Issue by ryancom16** [FreshRSS/FreshRSS#1249]
Related issue: #1018

Currently, the number of items in the public rss matches those shown on the web page. Generally this is not a problem unless the feed has a lot of content.

Request: 
Allow a parameter in the public url that would specify the number of items retrieved in the public rss.

Ex: 
http://Domain/FreshRSS/p/i/?a=rss&get=c_6**&Items=300**&token=xxxxxxx

Reason: 
For feeds that contain a lot of content, The Freshrss web ui is slowed down a lot(Nearly freezes) when that feed is loaded into view. This is made much worse when the number of items per page is increased.

I have an external program that monitors the public FreshRss feeds (at the category level) at regular intervals. There are many feeds in this category and updates can be frequent. In order to make sure that public feed displays all updates, I have set the feed limit per page to a very high number (300). 

This var is global so the feed with a lot of content also gets loaded at 300 per page. This causes massive lag to the system. If the item number could be specified at the public url level, then the global value could be set lower and system integrity and performance would increase dramatically.

**Comment by Alkarex** [comment]
Here is a proposition https://github.com/FreshRSS/FreshRSS/pull/1251
Could you please test it?

**Comment by Alkarex** [comment]
Related: https://github.com/FreshRSS/FreshRSS/issues/848

**Comment by Alkarex** [comment]
Done
