### ISSUE TITLE
CSRF for extensions

### ISSUE THREAD

**Issue by Wanabo** [FreshRSS/FreshRSS#1253]
Currently I use two extensions:
xExtension-CustomCSS
xExtension-ImageProxy

**Problem 1**:
With both extentions I cannot manage the extension. I only can enable or disable them.
Providing input in CustomCSS or ImageProxy and saving causes a direct log out with a warning message:

> Error 403 - Forbidden
> 
> You don’t have permission to access this page [HTTP_REFERER=https://www.nieuwskop.nl/p/i/?c=extension]
> ← Go back to your RSS feeds

**Problem 2**:
xExtension-ImageProxy only works when logged in, not for guests. But especially for my guests I want to get rid of insecure content warnings. :(

**Comment by Alkarex** [comment]
We need to add a CSRF token to all extension forms, e.g. https://github.com/FreshRSS/Extensions/blob/master/xExtension-CustomCSS/configure.phtml

``` html
<input type="hidden" name="_csrf" value="<?php echo FreshRSS_Auth::csrfToken(); ?>" />
```

**Comment by Alkarex** [comment]
@Frenzie This is the issue you describe on https://github.com/FreshRSS/FreshRSS/pull/1198#issuecomment-247989577

**Comment by Frenzie** [comment]
Ah, ok. I can take care of applying the simple fix to all extensions if you like.

Regarding the image proxy, I suppose a simple change to `"type": "system"` might do the trick?

**Comment by Alkarex** [comment]
That would be nice, @Frenzie :+1: 
I do not understand your suggestion with `"type": "system"`

**Comment by Frenzie** [comment]
@Wanabo complained that ImageProxy only works for logged in users, probably on a per-user basis to boot (`"type": "user"` in `metadata.json`; I should've specified that part). Would `"type": "system"` result in the desired behavior? The documentation is quiet under the relevant header. xD

http://doc.freshrss.org/fr/developers/03_Backend/05_Extensions/#fiche-technique-0001-ecriture-dextensions-pour-freshrss

**Comment by Alkarex** [comment]
Yes indeed, `"type": "system"` :-)
https://github.com/FreshRSS/FreshRSS/blob/789d9fc6c8647fa100d80e3ef52727c813f35f16/app/Controllers/extensionController.php#L93

**Comment by Alkarex** [comment]
@Wanabo Could you please try again the new version of the extensions, which @Frenzie has kindly updated?

**Comment by Wanabo** [comment]
Unfortenately it does not make any difference. Guests still see insecure images. When logged in Image Proxy is working.
Difference now is under extentions. Image Proxy is now listed as a system extension instead of a user extension. Further more, disabling and enabling is not possible now.

CSRF token in configure.phtml is the solution for not being able to configure the extension.
Perhaps some additional modification is needed to extension.php.

**Comment by Alkarex** [comment]
Ok @Wanabo . Could you please open a new bug for the specific part of extensions for anonymous users?

**Comment by Wanabo** [comment]
See, #1257
