### ISSUE TITLE
xExtension-ImageProxy does not work for guests

### ISSUE THREAD

**Issue by Wanabo** [FreshRSS/FreshRSS#1257]
xExtension-ImageProxy only works when logged in, not for guests. But especially for my guests I want to get rid of insecure content warnings. :(

Changing metadate.json  "type": "user" to "type": "system" does not seem to do the trick.
Difference now is under extentions. Image Proxy is now listed as a system extension instead of a user extension.
#1253

**Comment by Frenzie** [comment]
I imagine I should change `$user_conf` to `$system_conf` in extension.php and configure.phtml, but since the default behavior should be to use the weserveit proxy server I'm not sure if there's something I can do in the extension itself or if it's something else. It looks like system extensions are loaded without any auth involvement though: https://github.com/FreshRSS/FreshRSS/blob/17c8c039df675b3b0f8d88d14f7316a240eabe76/app/FreshRSS.php#L27-L33

**Comment by Frenzie** [comment]
I'm logging off for today, but perhaps you could test if a global replacement from $user_conf to $system_conf fixes the problem?

**Comment by Alkarex** [comment]
Edit: Removed wrong comment :-)

**Comment by Alkarex** [comment]
Now that the extension is `system`, this line seems to fail https://github.com/FreshRSS/Extensions/blob/e820c338b2a37a4ac01a578722644b32ba927aea/xExtension-ImageProxy/extension.php#L8

> Notice: Trying to get property of non-object in /home/alex/public_html/alexandre.alapetite.fr/s/FreshRSS/extensions/xExtension-ImageProxy/extension.php on line 8

We need to think whether using `system` is the right approach. Maybe we should enable the extensions of the default account for anonymous users https://github.com/FreshRSS/FreshRSS/blob/a180485f9146f22d48470f3ba541317dbc2ee076/app/FreshRSS.php#L52 with something like:

``` php
if (FreshRSS_Auth::hasAccess() || $system_conf->allow_anonymous) {
```

**Comment by Wanabo** [comment]
Just tried replacing $user_conf for $system_conf in extension.php and configure.phtml, but still no "secure" images for guests.

Just tried this in FreshRSS.php, if (FreshRSS_Auth::hasAccess() || $system_conf->allow_anonymous) {
And it seems to work!!! :) :+1: 
Note: extension.php and configure.phtml with $user_conf and metadat.json with   "type": "user"

Will check tomorrow if it still has the wanted behavior.

**Comment by marienfressinaud** [comment]
Mmm, it could be a bug: I think `system` extensions should be enabled even if we are not connected indeed (this part should do the trick: https://github.com/FreshRSS/FreshRSS/blob/a180485f9146f22d48470f3ba541317dbc2ee076/lib/Minz/ExtensionManager.php#L158-L161). What we need to find is why it is not called (I guess `$name` is not part of `self::$ext_auto_enabled` but it should be done at https://github.com/FreshRSS/FreshRSS/blob/a180485f9146f22d48470f3ba541317dbc2ee076/lib/Minz/ExtensionManager.php#L55)

**Comment by Wanabo** [comment]
With this mod
`if (FreshRSS_Auth::hasAccess() || $system_conf->allow_anonymous) {`
All pics are now shown through the image proxy as reported yesterday. I will let the experts figure out if this should be implemented otherwise.
Just one additional remark. It would be nice if urls in force-https.default.txt, force-https.txt and all https feeds would bypass the image proxy. These pictures are all ready secure content and would relief stress from the image proxy service ($proxy_url = 'https://images.weserv.nl/?url='). And it becomes less likely that you hit some limit.

**Comment by Frenzie** [comment]
HTTPS already doesn't go through the proxy, see https://github.com/FreshRSS/Extensions/blob/778d017232259e58ed59dad4b3ad89e0a5ff8879/xExtension-ImageProxy/extension.php#L24-L36 I admit I'm only taking a quick peek atm, but I believe that force-https.txt should be applied long before the ImageProxy gets its hands on anything.

**Comment by Wanabo** [comment]
@Frenzie You're right about https not going through the proxy. My mistake.

**Comment by marienfressinaud** [comment]
@Frenzie > maybe you should change `$user_conf` to `$system_conf` in your extension: `https://github.com/FreshRSS/Extensions/blob/master/xExtension-ImageProxy/extension.php#L8-L9`. I'm not sure if it's the problem but it may be related.

Also, when I activate the extension, I have `Trying to get property of non-object in [...]/extensions/xExtension-ImageProxy/extension.php on line 8`. I didn't search for the reason.

**Comment by Frenzie** [comment]
@marienfressinaud Sure, see my first comment here. But also note https://github.com/FreshRSS/FreshRSS/issues/1257#issuecomment-248128045

Anyway, I'm left without a working instance of FreshRSS atm because my el cheapo VPS apparently quit operations (see [here](https://www.lowendtalk.com/discussion/91478/issues-with-virtwire-evoburst-since-yesterday) in the unlikely case that you're interested).

**Comment by Alkarex** [comment]
I have not followed closely: what is the status?

**Comment by Wanabo** [comment]
For me this is working:

> Just tried this in FreshRSS.php, if (FreshRSS_Auth::hasAccess() || $system_conf->allow_anonymous) {
> And it seems to work!!! :) :+1:
> Note: extension.php and configure.phtml with $user_conf and metadat.json with "type": "user"

**Comment by Frenzie** [comment]
I'm fine changing it back to user.

**Comment by Alkarex** [comment]
I have made a pull request to allow extensions for anonymous use https://github.com/FreshRSS/FreshRSS/pull/1288

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/1288 is merged in /dev

**Comment by Alkarex** [comment]
It would indeed be good to find out whether there is a bug when using type:system, which would be more appropriate for this case.

**Comment by Wanabo** [comment]
Haven't checked using type:system. I'll report back when I tested it.

**Comment by Wanabo** [comment]
type:system works ok.

**Comment by Alkarex** [comment]
All good then?
