### ISSUE TITLE
Auto marking as read and hiding is not woking.

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#1258]
I may being stupid, but the app isn't working as i'd expect. 

I had checked:
Mark article as read… [x] while scrolling 
and
Hide articles after reading  [x]

Then i go to the "reading" mode, and look at the articles, skipping then with j. The old ones wont get hide, even if i reload the page.

Where is the mistake?

**Comment by Alkarex** [comment]
@aledeg Do you think you could have a chance to look at this bug?

**Comment by Alkarex** [comment]
@techmago Could you please try this patch https://github.com/FreshRSS/FreshRSS/pull/1309 and let me know what you think?

**Comment by Alkarex** [comment]
Merged in the /dev branch. Tests welcome :-)
