### ISSUE TITLE
Readability support

### ISSUE THREAD

**Issue by kavillock** [FreshRSS/FreshRSS#1259]
it's posible to add readability feature? (full article plus cleanup) to FRSS? eg arc90 readibility (or smilar?) or readability.com api (but second its buggy, dont support srcset)

**Comment by Alkarex** [comment]
Hello,
Are we talking about a new "share with" entry?
If yes, see an example https://github.com/FreshRSS/FreshRSS/pull/1056/commits/9b842f9909807fb615e5fb52149903272d9ae101

**Comment by GreenLunar** [comment]
I think @kavillock is referring to Arc90 Readability algorithm.  See https://github.com/QupZilla/qupzilla-plugins/wiki/Readability

**Comment by kavillock** [comment]
yes, i referring to Arc90 Readability algorithm.

**Comment by ghost** [comment]
Hi, anything new about readability support ?
Have you @Alkarex ever heard about https://github.com/andreskrey/readability.php ?
Thanks

**Comment by aledeg** [comment]
When you're thinking of that feature, what exactly do you have in mind?
Do you want a toggle like in Firefox bar?
If so, do you want to toggle one article, all articles, other?
Do you want to store modified data in the database?

**Comment by Frenzie** [comment]
Maybe automatic custom article CSS or something?

**Comment by ghost** [comment]
Oops, maybe I was not understandable.
To sum up, the idea behind the "readability" is to retrieve an item from an RSS feed integrally.
It's already implemented as a [plugin in tt-rss](https://git.tt-rss.org/git/tt-rss/src/master/plugins/af_readability/init.php).

Example : the first screenshot is my ttrss instance with af_readability enabled : the article is full (it continues lower, until its end) and at the bottom it is my FreshRSS one looking at the same article.

![ttrss](http://image.noelshack.com/fichiers/2017/46/3/1510782805-screenshot-2017-11-15-66-tiny-tiny-rss.png) ![FreshRSS](http://image.noelshack.com/fichiers/2017/46/3/1510782865-freshrss.png)

**Comment by Frenzie** [comment]
Right, so it's basically an automated attempt at `Articles CSS path on original website`.

**Comment by Alkarex** [comment]
For reference, the current system that we have (not as good, but does the job):
* https://freshrss.github.io/FreshRSS/fr/users/05_Configuration.html#r%C3%A9cup%C3%A9rer-un-flux-tronqu%C3%A9
* https://freshrss.github.io/FreshRSS/en/users/05_Configuration.html#retrieve-a-truncated-stream

Related issues:
* https://github.com/FreshRSS/FreshRSS/issues/947
* https://github.com/FreshRSS/FreshRSS/issues/785
* https://github.com/FreshRSS/FreshRSS/issues/199

**Comment by Frenzie** [comment]
> not as good

Indeed. It's much better. \m/

(Not really kidding. Automatic is cool and all when it works… Anyway, no reason we can't have both I reckon.)

**Comment by helmut72** [comment]
> https://freshrss.github.io/FreshRSS/en/users/05_Configuration.html#retrieve-a-truncated-stream

Thanks, but I don't get it. What filter do I need for following page?
http://www.handelsblatt.com/unternehmen/management/daimler-bmw-telekom-deutschlands-konzerne-sind-so-profitabel-wie-nie/21107000.html

**Comment by Frenzie** [comment]
@helmut72 Presumably `.container_onecolumn_read`.

**Comment by helmut72** [comment]
Thank you, but it doesn't work. Looks like their default RSS:
<img width="939" alt="bildschirmfoto 2018-03-24 um 22 16 32" src="https://user-images.githubusercontent.com/1388751/37869056-16e4a472-2fb1-11e8-8e7b-be7fa69740a5.png">

Is the feed updated immediately or do I have the possibility to add a CSS Path **before** FreshRSS fetches the content for the first time?

**Comment by helmut72** [comment]
> Is the feed updated immediately or do I have the possibility to add a CSS Path before FreshRSS fetches the content for the first time?

Answering my own question. Looks like the feeds will be loaded immediately and it's not possible the set the CSS Path before loading. The newer articles over the night are now correct! It should be possible to test the CSS Path before. Some of me feeds are updated only weekly.

**Comment by cwmke** [comment]
I was just messing around with feedbin and they have a button you click per article that uses the recently open sourced [Mercury Parser](https://github.com/postlight/mercury-parser) that seems to work great. I like individual article parsing but whole feed parsing is useful as well.

**Comment by math-GH** [comment]
How is the status here?
When I use the "Reading View" than Firefox displays the button to switch to the build in Reader View
![grafik](https://user-images.githubusercontent.com/1645099/129480884-7b6df4ac-aa1b-4bc4-9f0d-27830047dbe2.png)

**Comment by math-GH** [comment]
ping @kavillock 
Is it still an issue/feature request?

**Comment by printfuck** [comment]
I still consider it a nice feature, since debugging css filters on steadily changing site layouts is tiring after some time.

Some time ago I've built a small solution as a plugin, but didn't publish it. I've cleaned it up a bit, but it still relies on modifying the source for it to work with selected sites. 

https://git.eris.cc/a3x/readability-addon

I'd still prefer to add readability/mercury support as an option in the feed-configuration menu, but I wouldn't want to force this on any maintainer - especially, if this it's relying wholy on some specialised docker image/software porject, that you don't have any control over.

Instead I'd advocate to add an extension hook, which would allow an extension to add options to each feed-configuration page - would that be possible?
The other way around would be: listing all feeds inside the extension's configuration page and selecting each feed that should  be manipulated/modified - but I don't know how to go on about this. (If you could tell me how/if that ould work, I'd work on that)

Kind regards and thanks for your work.
(Sorry for necrobumping this issue)

**Comment by Frenzie** [comment]
> Instead I'd advocate to add an extension hook, which would allow an extension to add options to each feed-configuration page - would that be possible?

I think that's `menu_configuration_entry`? Can't check atm. :-)

**Comment by printfuck** [comment]
> I think that's `menu_configuration_entry`? Can't check atm. :-)

To my knowledge this refers to the main Configuration Menu (Display, Reading, Archiving, ... ). I specifically meant to add an option to the settings of each feed - not another global menu.

If there only was an example of how this hook can be used :)

**Comment by Frenzie** [comment]
Well, if it's missing it's something that'd make sense to add. ;-)

**Comment by printfuck** [comment]
Hi again.

I'd like to submit my extension, so this issue can finally get resolved. I made it usable and it works as one would expect it to do.

https://github.com/printfuck/xExtension-Readable

I will probably work on it, so it can be controlled from the main configuration menu, but until then it can be easily configured from the extension's config. 

I'd go on submit a pull request against the extension repo, provided there is no reason against it.

**Comment by Alkarex** [comment]
Thanks @printfuck 👍🏻

**Comment by Niehztog** [comment]
As a sidenote, I created an experimental Readability Extension for FreshRSS which does not require Docker containers to run, as not everyone has the luxury of having a fully functional Docker environment on their server. Might perform less accurate than printfuck's extension obviously.

https://github.com/Niehztog/freshrss-af-readability

**Comment by Alkarex** [comment]
@Niehztog Feel free to make a PR to add it to https://github.com/FreshRSS/Extensions/blob/master/repositories.json and to the readme
