### ISSUE TITLE
Feed Builder/Scrapper

### ISSUE THREAD

**Issue by GreenLunar** [FreshRSS/FreshRSS#1262]
Integrated feed generator from pages of websites that do not provide RSS feeds.

See http://createfeed.fivefilters.org/ and https://github.com/sebsauvage/rss-bridge

**Comment by aledeg** [comment]
I think that's not the purpose of FreshRSS. I would let that in https://github.com/RSS-Bridge/rss-bridge.

I don't see the point of having such tool in FreshRSS since there are tools doing that job. I would close that issue.

**Comment by GreenLunar** [comment]
I disagree.

I think it is essential to have a built-in (or plugin) web scrapper to read from websites that do not provide RSS feeds; moreover, Feed Creator of FiveFilters.org is not complete and misses many attributes, and RSS-Bridge has a specific set of supported websites.

**Comment by Alkarex** [comment]
Related to https://github.com/FreshRSS/FreshRSS/issues/785

**Comment by aledeg** [comment]
@GreenLunar in the meantime, if you're not happy with the websites supported by rss-bridge, you can make your own.

**Comment by Alkarex** [comment]
It is indeed easy to host an RSS Bridge instance, and possible to add support for more sites, with many examples already https://github.com/RSS-Bridge/rss-bridge/tree/master/bridges
