### ISSUE TITLE
SimplePie: fail autodiscovery for sites returning text/xml

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#1264]
Some sites such as Tumblr will return a content type of `text/xml` for their HTML content if we send them a request in which text/xml has a higher priority than text/html, which will make the autodiscovery of the feed to fail with our version of SimplePie.
Another example: autodiscovery of the RSS feed of `http://blog.theoldreader.com/`

**Comment by Alkarex** [comment]
Needed for https://github.com/FreshRSS/FreshRSS/issues/1263

**Comment by ghost** [comment]
Hello is this issue really resolve now ? I'm using 1.6.2 with php 7 and I'm still getting error like this

2017/03/06 15:47:48 [error] 19680#19680: *2800 FastCGI sent in stderr: "PHP message: PHP Notice: A feed could not be found at `http://rostylesbonstuyaux.fr/feed/`; the status code is `200` and content-type is `application/octet-stream` in /var/www/freshrss/lib/SimplePie/SimplePie.php on line 1645" while reading response header from upstream, client: xx, server:xx request: "POST /i/?c=feed&a=actualize&id=644&ajax=1 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7-fpm.sock:",

**Comment by Alkarex** [comment]
Hello @prysme01 
This does not seem related to the current ticket (which is implemented, and was for feeds served as "text/xml"). Yours has other problems. But anyway, try using `http://rostylesbonstuyaux.fr/feed/#force_feed` as the address.

**Comment by ghost** [comment]
Thanks Alex, it wasn't the code, I did manage to clean up all my config file, rebuild my setup, and now it's working fine.

**Comment by PauloBoaventura** [comment]
@javerous 

I have the same error but in the .ghtml extension
how would it be done in this case?

**Comment by Alkarex** [comment]
@PauloBoaventura Do you have an example of Web site with that problem?
