### ISSUE TITLE
Feeds sorted with the title not the date

### ISSUE THREAD

**Issue by dawand** [FreshRSS/FreshRSS#1266]
Hello, 

Thank you for this awesome feed aggregator. I have two issues:
1. The feeds are sorted alphabetically based on the title not the date of publication. This happened after I migrated it to my own web server. Does it have to do with broken links of the feeds because I have above 40 feed subscriptions?
2. There are times where the feeds are not actualised. This happened after I dropped the tables in the  database and created them again but after importing the OMPL, the feeds are not fetched anymore! How can I clear the cache if I want to?

Thanks again 👍

**Comment by Alkarex** [comment]
Hello,
Regarding 1, it will work again as expected when you receive new updates, e.g. from a regular cron job.
Regarding 2, there are a couple of options in the settings, to prevent feeds from being updated too often. Typically set to one hour or so.

**Comment by Alkarex** [comment]
After a few refresh, the order should be more natural again.
Furthermore, the initial behaviour will get better when https://github.com/FreshRSS/FreshRSS/issues/530 is implemented.
