### ISSUE TITLE
Authentication token not working

### ISSUE THREAD

**Issue by amereservant** [FreshRSS/FreshRSS#1274]
If I understand this feature correctly, I should be able to access the RSS feed from FreshRSS by specifying an Authentication Token, however this isn't working.

For example, I set a token of 123abc and without any of the checkboxes selected, I click "Submit".
It then reads `Allows access to RSS output of the default user without authentication:  http://localhost/freshrss/p/i?output=rss&token=123abc`

So I should be able to access **http://localhost/freshrss/p/i?output=rss&token=123abc** without being logged in, correct?  Well, it doesn't work.  I get a 403 error.

I'm using version 1.5.0

![authentication freshrss](https://cloud.githubusercontent.com/assets/238008/19011500/fdd4d7ac-875c-11e6-8217-3fbba3a29845.jpg)

**Comment by Alkarex** [comment]
Hello @amereservant 
When you have set the token, just click on the RSS icon on the Web interface of FreshRSS, e.g. while showing a given category.
Should should have a link like `https://rss.example.net/i/?a=rss&get=f_4&token=79a59ee716d7eb4ff32f6d7e64c84580e78c3344&hours=168`.
You are right that the link example seems wrong.

**Comment by amereservant** [comment]
Hey @Alkarex , thanks!  That works for the **Main stream** as well, so it's just an issue of the formatting being wrong in that section.  I really appreciate your help and you can close this unless you want to leave it open as a reminder to fix that section in a future update.

**Comment by Alkarex** [comment]
Fixed in https://github.com/FreshRSS/FreshRSS/pull/1282 . Merged in /dev
