### ISSUE TITLE
Automate export of feeds

### ISSUE THREAD

**Issue by Jucgshu** [FreshRSS/FreshRSS#1277]
Hey guys,

Related to #1240 which is a nice one, I would like to know if we could automate this, via cron or anything else.

Is there a way to call the php function with the CLI ? 

Thanks a lot !

**Comment by Alkarex** [comment]
Not yet, but planned in https://github.com/FreshRSS/FreshRSS/issues/1095 :-)

**Comment by Jucgshu** [comment]
:+1:

**Comment by Alkarex** [comment]
Implemented in https://github.com/FreshRSS/FreshRSS/pull/1338
Comments welcome there
