### ISSUE TITLE
Damn! You lack cURL (php5-curl package)

### ISSUE THREAD

**Issue by nikoss** [FreshRSS/FreshRSS#1283]
You could add the following to troubleshooting or FAQ (might save some ignorant person, like myself, a few hours)
## 
## 

You get the error message that 

> "Damn! You lack cURL (php5-curl package)"

, but you are pretty confident that curl is installed on the shared  host server. 
What do you do?
- Search for curl.so, by executing the following, in a ssh terminal session:

`find / -name "*curl.so*"`

The result might look like this:

```
...
find: `/root/.cache': Permission denied
...
/usr/lib/i386-linux-gnu/libcurl.so.3
...
/usr/local/php-5.6.26/lib/php/20131226/curl.so
/usr/local/php-7.0.11/lib/php/20151012/curl.so
/usr/local/php-5.5.38/lib/php/20121212/curl.so
...
find: `/var/lib/php5': Permission denied
```
- From the produced list, select (and copy) the appropriate path of curl.so, for your version of php. 
  example:
  `/usr/local/php-5.5.38/lib/php/20121212/curl.so`
- Edit the php.ini file, and add the following line (or modify any existing entry)
  `extension=FULL_PATH_TO_curl.so`
  example:
  `extension=/usr/local/php-5.5.38/lib/php/20121212/curl.so`
- Save the php.ini file. 
- Refresh the web page that showed the initial error (F5 key)

Hopefully the error has been corrected.
## 
## 

By the way, you could consider changing the error message, in order to make it a little bit more accurate. For example

> Damn! Can't find cURL (php5-curl package)

Also, the "php5-curl" part might be confusing, because some Linux distros have a "php5-curl" package, some have a "php-curl", and some, like Fedora have just "curl", with no curl.ini .
But, how would you rephrase that? I don't know.

**Comment by Alkarex** [comment]
Thanks for the feedback. It sounds like the package manager of your distribution did not do its job correctly, but it will help having your explanations if someone else faces the same issues.
I have updated the English and French strings by integrating some of your suggestions https://github.com/FreshRSS/FreshRSS/pull/1285
