### ISSUE TITLE
Sharing not working for G+, Twitter, Facebook, Email

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#1289]
Hi,

My version of FreshRSS: V5.0

I am not able anymore to share my rss feeds with the outside.
I get a strange : ##label##

Anyone else ?

Vonv

**Comment by Alkarex** [comment]
Hello,
I cannot reproduce the problem. Could you please check your Web browser console to see whether there is any JavaScript error?

**Comment by ghost** [comment]
![prtscr capture_2](https://cloud.githubusercontent.com/assets/603029/19231684/accf74bc-8edb-11e6-875e-e973e3be10ad.jpg)
![prtscr capture_3](https://cloud.githubusercontent.com/assets/603029/19231686/ace6985e-8edb-11e6-8c16-ae5c43e238d2.jpg)
![prtscr capture_4](https://cloud.githubusercontent.com/assets/603029/19231685/ace26c84-8edb-11e6-940a-8a7b3596139c.jpg)

Nothing in the logs.

**Comment by Alkarex** [comment]
Ah indeed, I can reproduce the problem.

**Comment by Alkarex** [comment]
Should be fixed in https://github.com/FreshRSS/FreshRSS/pull/1300 . Merged in /dev
Please give it a try.

**Comment by ghost** [comment]
Génial, ça marche nickel pour FB, Twit et G+ !!!!
Merci !!!!!!!!!!!!!!!

François Yvon

2016-10-10 22:09 GMT+02:00 Alexandre Alapetite notifications@github.com:
