### ISSUE TITLE
MySQL 5.1: Update to 1.5 crashes setup

### ISSUE THREAD

**Issue by 1770** [FreshRSS/FreshRSS#1297]
Hi there

After update to 1.5 (from 1.4.icantremember) my installation crashes. I got a Fatal Error when I want to open the reader.
The log says: Access to database is denied for `ollrich` (`mysql:host=localhost;dbname=ollrich_reader;charset=utf8mb4`)

I ran FreshRRS with PHP version 5.6.21 and MySQL version 5.1.73-log

I double checked the config.php files but they looking ok.

Thanks in advance for any help
Olli

**Comment by Alkarex** [comment]
Hello,
The minimum requirement when using MySQL is 5.5.3+ (March 2010). Otherwise, we also have support for SQLite, and PostgreSQL (in FreshRSS 1.6 to be released soon).
If you really cannot update to a less old version of MySQL, changing `utf8mb4` to `utf8` in the source code should help.

**Comment by Alkarex** [comment]
For documentation, reference to changelog: https://github.com/FreshRSS/FreshRSS/blob/dev/CHANGELOG.md#2016-08-29-freshrss-150

**Comment by Alkarex** [comment]
Just by curiosity: what system are you running? It is a strange combination with a very old MySQL and a not-so-old PHP. It looks like the only remaining distribution supporting MySQL 5.1 is the old CentOS 6 (CentOS 7 was released in July 2014), but CentOS 6 seems to have PHP 5.3.3 http://distrowatch.com/table.php?distribution=CentOS

**Comment by Alkarex** [comment]
Related: https://github.com/FreshRSS/FreshRSS/issues/1243

**Comment by 1770** [comment]
Hi Alkarex

Thanks for reply. I will try the utf8 change and get back with the results.

The system is a CentOS 6 by my hoster Uberspace. I'm not very familiar with setups like this but I know that Uberspace workin' on CentOS 6 base but tryin' to implement nearly every modern technology.

**Comment by Alkarex** [comment]
Often, hosting companies have an option to chose what database version to run. Did you have a look?

**Comment by 1770** [comment]
Yes, I could check the capabilities to use a higher MySQL version. I've to do a fresh install with updated options.
Thanks, you can close this ticket

**Comment by Alkarex** [comment]
If you start from a fresh install, and if you cannot find an option to upgrade MySQL, I would then recommend to give a try to SQLite (instead of MySQL), so that you do not have to patch anything.

**Comment by ghost** [comment]
It'a very old install so i didn't want to loose everything. I replaced all the utf8mb4 by utf8 and it's done. Everything fine. Thanks !

**Comment by Alkarex** [comment]
For reference: https://github.com/FreshRSS/FreshRSS/issues/1153
