### ISSUE TITLE
SQL error markReadFeed: syntax error

### ISSUE THREAD

**Issue by sublimz** [FreshRSS/FreshRSS#1299]
Since 1.5.0 ;  "Mark as read" doesn't work for me, still unread.
In the log, "SQL error markReadFeed: syntax error"
Installation checking is green. I auto-update from 1.4.0 to 1.5.0.
I'm alone ? Thanks

**Comment by Alkarex** [comment]
Hello,
What OS, what database (e.g. MySQL ?), what versions ?

**Comment by Alkarex** [comment]
And is it only with this request, that you get some errors?

**Comment by sublimz** [comment]
Hello, thanks to reply
Yes, it's the only error i had in 1.5.0.
I use a Synology to host with Nginx, SQLlite3, PHP 5.6.23.
To test, I have done a new fresh install from git 1.5.0, same problem  : "SQL error markReadFeed: syntax error". So new install in 1.4.0 and no mark problem, all is fine in this version.

**Comment by Alkarex** [comment]
I cannot reproduce the error, but I would be interested in identifying the problem:
- Could you please confirm that you are using SQLite (and not MySQL)?
- Did marking a _category_ as read work without error?
- Could you please try either:
  - The current [dev version](https://github.com/FreshRSS/FreshRSS/tree/dev) (which is the almost final version 1.6)
  - Or try again the 1.5 version and change [line 443 of `Models/EntryDAO.php`](https://github.com/FreshRSS/FreshRSS/blob/edd4516178c49f966248d832e63776f5f2f90236/app/Models/EntryDAO.php#L443) with the following one ( https://github.com/FreshRSS/FreshRSS/pull/1302 ), to have a better error message?

``` php
Minz_Log::error('SQL error markReadFeed: ' . $info[2] . ' with SQL: ' . $sql . $search);
```

**Comment by sublimz** [comment]
Hello,
- Yes, i'm really using SQLite
- No, no one works; same problem for all feeds and categories
  -  After install **Dev version : no problem, it's works !**, I can do "Mark as read"
  -  Message after switch the line 443 in 1.5:

```
2016-10-12 09:16:41
SQL error markReadFeed: syntax error with SQL: UPDATE `entry` e SET e.is_read=1 WHERE e.id_feed=? AND e.is_read=0 AND e.id <= ?
```

Thanks Alkarex, I am waiting the 1.6.
(Freshrss become really good !)

**Comment by Alkarex** [comment]
Thanks for the feedback! Good that 1.6-dev works :-)
Based on your error message, I cannot spot why you got an SQL syntax error in 1.5. Mystery...
