### ISSUE TITLE
Sharing configuration not working

### ISSUE THREAD

**Issue by gufertum** [FreshRSS/FreshRSS#1301]
I freshly installed the current release yesterday (git/master) and everything is working fine, but the sharing configuration cannot be changed / saved.
If I add an item (eg: Twitter) and submit, nothing happens and the item is still missing.

How can I add a share item? Where should the sharing-configuration be saved?

**Comment by Alkarex** [comment]
Hello,
The bug has just been fixed in the /dev version https://github.com/FreshRSS/FreshRSS/pull/1300
https://github.com/FreshRSS/FreshRSS/issues/1289

**Comment by gufertum** [comment]
Thanks, I hand-picked the changed files. Everythings working great!

**Comment by Alkarex** [comment]
Please consider giving a try to the /dev version, it is ready for testing before the release of version 1.6 :-)
