### ISSUE TITLE
Sort feeds by date/time

### ISSUE THREAD

**Issue by Jedediah04** [FreshRSS/FreshRSS#1305]
Hello guys :)

On a fresh installation of FreshRSS, my feeds (on the main view) are grouped like this : 
Feed 1
- Article 1
- Article 2
- Article 3
- ...

Feed 2
- Article 1
- Article 2
- Article 3
- ...

Etc

On the screenshots of FreshRSS found on documentation or website, the feeds are alltogether grouped by date. How do you achieve this ?

What I have : https://img.tardisbox.net/vBhrPqrP/VdrNqGn9.png
What I want : https://freshrss.org/images/screenshot.png

Thanks :)

**Comment by Jedediah04** [comment]
Nvm, after a refresh, feeds are sorted correctly.

**Comment by Alkarex** [comment]
Hello,
After a few refresh, the order should be more natural again.
Furthermore, the initial behaviour will get better when https://github.com/FreshRSS/FreshRSS/issues/530 is implemented.
Related: https://github.com/FreshRSS/FreshRSS/issues/1266

**Comment by Jedediah04** [comment]
The order is still not good after 3 days of updates.
I'll wait for your update.

**Comment by Alkarex** [comment]
Could you please send a screenshot?

**Comment by Alkarex** [comment]
P.S. And have you set up a cron job for regular updates?

**Comment by Jedediah04** [comment]
https://img.tardisbox.net/x0w5ZCCE/GJL8adJs.png
Le cron est en place mais j'ai dû mal le mettre car les flux ne s'actualisent pas.

**Comment by Alkarex** [comment]
Laissez tourner votre cron pendant quelques temps (par exemple avec une fréquence de une ou deux fois par heure). Il est normal que les flux ne soient pas mis à jour à chaque fois. L'affichage que vous voyez est le résultat que les mises à jour n'ont pas été faites pendant un bon moment. Voici un exemple de cron pour Debian / Ubuntu :
https://github.com/FreshRSS/FreshRSS/blob/dev/README.fr.md#exemple-pour-debian--ubuntu

**Comment by Alkarex** [comment]
Une implémentation du tri plus naturel est disponible. Tests bienvenus https://github.com/FreshRSS/FreshRSS/pull/1470
