### ISSUE TITLE
Tache CRON php7

### ISSUE THREAD

**Issue by Reylias** [FreshRSS/FreshRSS#1310]
Salut

Quelqu’un pourrait me  donner l’équivalence php5 pour php7 pour le rafraichissement des fluxs.

Sur php5 ça donne : 
# Mise à jour FreshRSS

*/15 \* \* \* \* /usr/bin/php /var/www/FreshRSS/app/actualize_script.php >>/tmp/FreshRSS.log

**Comment by Alkarex** [comment]
C'est exactement pareil pour PHP7
https://github.com/FreshRSS/FreshRSS/blob/dev/README.fr.md#rafra%C3%AEchissement-automatique-des-flux

**Comment by Reylias** [comment]
Merci ça fonctionne.
