### ISSUE TITLE
Call for testing /dev before version 1.6 (second round)

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#1328]
The future version 1.6 of FreshRSS is [ready](https://github.com/FreshRSS/FreshRSS/milestone/19) for testing. Since the [previous version](https://github.com/FreshRSS/FreshRSS/issues/1219), the theme has been to introduce PostgreSQL as an additional database choice, but there is also a number of new features and bug corrections, as visible [in the changelog](https://github.com/FreshRSS/FreshRSS/blob/dev/CHANGELOG.md):
- API
  - Support for editing feeds and categories from client applications [#1254](https://github.com/FreshRSS/FreshRSS/issues/1254)
- Compatibility:
  - Support for PostgreSQL [#416](https://github.com/FreshRSS/FreshRSS/issues/416)
  - New client supporting FreshRSS on Linux: FeedReader 2.0+ [#1252](https://github.com/FreshRSS/FreshRSS/issues/1252)
- Features
  - Rework the “mark as read during scroll” option, enabled by default for new users [#1258](https://github.com/FreshRSS/FreshRSS/issues/1258), [#1309](https://github.com/FreshRSS/FreshRSS/pull/1309)
    - Including a _keep unread_ function [#1327](https://github.com/FreshRSS/FreshRSS/pull/1327)
  - In a multi-user context, take better advantage of other users’ refreshes [#1280](https://github.com/FreshRSS/FreshRSS/pull/1280)
  - Better control of number of entries per page or RSS feed [#1249](https://github.com/FreshRSS/FreshRSS/issues/1249)
    - Since X hours: `https://freshrss.example/i/?a=rss&hours=3`
    - Explicit number: `https://freshrss.example/i/?a=rss&nb=10`
    - Limited by `min_posts_per_rss` and `max_posts_per_rss` in user config
  - Support custom ports `localhost:3306` for database servers [#1241](https://github.com/FreshRSS/FreshRSS/issues/1241)
  - Add date to exported files [#1240](https://github.com/FreshRSS/FreshRSS/issues/1240)
  - Auto-refresh favicons once or twice a month [#1181](https://github.com/FreshRSS/FreshRSS/issues/1181), [#1298](https://github.com/FreshRSS/FreshRSS/issues/1298)
    - Cron updates will also refresh favicons every 2 weeks [#1306](https://github.com/FreshRSS/FreshRSS/pull/1306)
- Bug fixing
  - Correction of bugs related CSRF tokens introduced in version 1.5.0 [#1253](https://github.com/FreshRSS/FreshRSS/issues/1253), [44f22ab](https://github.com/FreshRSS/FreshRSS/pull/1261/commits/d9bf9b2c6f0b2cc9dec3b638841b7e3040dcf46f)
  - Fix bug in Global view introduced in version 1.5.0 [#1269](https://github.com/FreshRSS/FreshRSS/pull/1269)
  - Fix sharing bug [#1289](https://github.com/FreshRSS/FreshRSS/issues/1289)
  - Fix bug in auto-load more articles after marking an article as un-read [#1318](https://github.com/FreshRSS/FreshRSS/issues/1318)
  - Fix bug during import of favourites [#1315](https://github.com/FreshRSS/FreshRSS/pull/1315), [#1312](https://github.com/FreshRSS/FreshRSS/issues/1312)
  - Fix bug not respecting language option for new users [#1273](https://github.com/FreshRSS/FreshRSS/issues/1273)
  - Bug in example of URL for FreshRSS RSS output with token [#1274](https://github.com/FreshRSS/FreshRSS/issues/1274)
- Security
  - Prevent `<a target="_blank">` attacks with `window.opener` [#1245](https://github.com/FreshRSS/FreshRSS/issues/1245)
  - Updated gitignore rules to keep user directories during a `git clean -f -d` [#1307](https://github.com/FreshRSS/FreshRSS/pull/1307)
- Extensions
  - Allow extensions for default account in anonymous mode [#1288](https://github.com/FreshRSS/FreshRSS/pull/1288)
  - Trigger a `freshrss:load-more` JavaScript event to help extensions [#1278](https://github.com/FreshRSS/FreshRSS/issues/1278)
- SQL
  - Slightly modified several SQL requests (MySQL, SQLite) to simplify support of PostgreSQL [#1195](https://github.com/FreshRSS/FreshRSS/pull/1195)
  - Increase performances by removing a superfluous category request [#1316](https://github.com/FreshRSS/FreshRSS/pull/1316)
- UI
  - Download icon 💾 for podcasts [#1236](https://github.com/FreshRSS/FreshRSS/issues/1236)
- SimplePie
  - Fix auto-discovery of RSS feeds in Web pages served as `text/xml` [#1264](https://github.com/FreshRSS/FreshRSS/issues/1264)
- Mics.
  - Removed _resource-priorities_ attributes (`defer`, `lazyload`), deprecated by W3C [#1222](https://github.com/FreshRSS/FreshRSS/pull/1222)

You are all kindly invited to [give a try to the /dev version](https://github.com/FreshRSS/FreshRSS/tree/dev).

Many thanks already to those of you who have been involved in this new version, such as @Damstre, @anayrat, @Frenzie,  @Cypouz, @Alwaysin, @lapineige, @nikoss, @techmago, @sublimz, @gufertum, @Vonv, @abaudot, @Wanabo, @Glaived, @symac, @amereservant, @donlencho, @ryancom16, @EtienneM, @donlencho, @kokaz, @GLLM, etc. 👍

One last thing: if any of you could be interested in writing a little blog post (to appear on e.g. your own blog with a copy on https://freshrss.org/blog.html and/or http://www.planet-libre.org) when there are new FreshRSS releases, let us know :-) @genma maybe? It can be more than one person, and in different languages.

**Comment by Alwaysin** [comment]
That is one hell of a version! Testing right now, will report if I stumble on something.

**Comment by Frenzie** [comment]
Everything seems to be working just fine for me!

**Comment by ghost** [comment]
Share don't work any more :)

See the image.

[image: Images intégrées 1]

​Vonv

2016-10-16 17:01 GMT+02:00 Alexandre Alapetite notifications@github.com:

**Comment by Alkarex** [comment]
@Vonv Could you please create a new bug issue, and put your screenshot there (it was lost from the e-mail)

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/1335

**Comment by ghost** [comment]
Noob question: to get the 1.6 dev version for sure, when i get to the dev branch what do i have to do ? Download ?

**Comment by Alkarex** [comment]
@Vonv Downloading the [/dev version](https://github.com/FreshRSS/FreshRSS/tree/dev) is enough. You can then verify the version in the about menu.

**Comment by ghost** [comment]
Thanks. So i have the right version, and it's working clearly well.

**Comment by Alwaysin** [comment]
When setting up a new instance, when choosing MySQL, you are asked for HTTP password and HTTP username : https://github.com/FreshRSS/FreshRSS/blob/dev/app/i18n/en/install.php#L28

Looks good for FR and DE. Looks bad also for IT. Didn't check the other languages.

**Comment by Alkarex** [comment]
Thanks @Alwaysin . Fixed in https://github.com/FreshRSS/FreshRSS/pull/1339 . Proofreading welcome

**Comment by symac** [comment]
@Alkarex I have been mentioned in this issue so even if the changelog doesn't say anything about issue #1243 I believe it should be fixed, unfortunately trying a clean install on OVH, I still get a blank page and the logs say : 

```
Access to database is denied for `opensourdrup` (`mysql:host=XXXXX;dbname=XXXXXXX;charset=utf8mb4`)
```

Changing utf8mb4 to utf8 in ModelPdo.php is ok but otherwise on OVH it still doesn't work.

**Comment by Alkarex** [comment]
Hello again everybody,
Thanks for the tests so far. I would like to ask for one more round of testing, with the current (i.e. from 5 minutes ago) version of /dev.
In the past days, a few bugs have been fixed, but with the risk of introducing new ones, so a bit more testing would be nice.
Furthermore, I have prepared in parallel a much awaited Command-Line Interface https://github.com/FreshRSS/FreshRSS/tree/dev/cli which was initially planned for the future version 1.7, but since there is already a first working version, I have just merged it in /dev. This required several changes in the core code, in particular regarding install, user management, and import/export.
So please go ahead and pull the latest /dev , which I would like to release by the end of the week ( @marienfressinaud  ).
I hope you will like it!

**Comment by ghost** [comment]
Pour récupérer la version de dev je download ici
https://github.com/FreshRSS/FreshRSS/tree/dev ?

François Yvon

2016-10-20 1:44 GMT+02:00 Alexandre Alapetite notifications@github.com:

**Comment by Alkarex** [comment]
@vonv Downloading the /dev version is enough. You can then verify the
version in the about menu.

**Comment by Alkarex** [comment]
@Vonv Tout à fait. Sinon par git :

``` sh
git clone https://github.com/FreshRSS/FreshRSS.git
cd FreshRSS
git checkout -b dev origin/dev

#Et pour mettre à jour, simplement :
git pull
```

Voir https://github.com/FreshRSS/FreshRSS/tree/dev#example-of-full-installation-on-linux-debianubuntu

**Comment by Alkarex** [comment]
[FreshRSS 1.6.0 is now released](https://github.com/FreshRSS/FreshRSS/releases/tag/1.6.0) :-)
Thanks all!
