### ISSUE TITLE
Share not working on dev version 1.6.0-dev

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#1329]
![vos flux rss freshrss - google chrome](https://cloud.githubusercontent.com/assets/603029/19420436/799b7f72-93eb-11e6-93cb-4ab8be791945.jpg)

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/issues/1328#issuecomment-254068164

**Comment by Alkarex** [comment]
Est-ce que vous pourriez vérifier la configuration, dans le menu des partages ?

**Comment by ghost** [comment]
Elle n'a pas bougé.

[image: Images intégrées 1]

François Yvon

2016-10-16 22:02 GMT+02:00 Alexandre Alapetite notifications@github.com:

**Comment by Alkarex** [comment]
Les images ne passent pas par courriel :-)
Pourriez-vous essayer de sauver à nouveau la configuration ?
Quel navigateur ?

**Comment by ghost** [comment]
L'image:
https://framapic.org/gallery#1akEdx5nMgwo/eJOJnGE34wxK.jpg

J'ai essayé de sauvegarder la conf: KO

François Yvon

2016-10-16 22:07 GMT+02:00 Alexandre Alapetite notifications@github.com:

**Comment by Alkarex** [comment]
Quel ce passe-t'il lorsque vous sauvegardez la configuration ? Une erreur ?

**Comment by ghost** [comment]
Ca fonctionne et rien dans les logs.

François Yvon

2016-10-16 22:20 GMT+02:00 Alexandre Alapetite notifications@github.com:

**Comment by Alkarex** [comment]
Et côté console de navigateur, aucune erreur ? Quel navigateur ?

**Comment by Alkarex** [comment]
Quelques pistes :
- Essayer de mettre `'environment' => 'development',` dans `data/config.php` (pour des messages d'erreur supplémentaires)
- Essayer de ré-appliquer les droits d'accès, par exemple : 

``` sh
cd FreshRSS
sudo chown -R :www-data .
sudo chmod -R g+r .
sudo chmod -R g+w ./data/
```

**Comment by Alkarex** [comment]
Related: https://github.com/FreshRSS/FreshRSS/issues/1289

**Comment by Alkarex** [comment]
Et êtes-vous sûr de bien avoir la version 1.6-dev ?

**Comment by ghost** [comment]
After a reinstall, all works well.
I think it was my mistake, sorry for the issue.

**Comment by ghost** [comment]
Tout est rentré dans l'ordre.
Désolé pour le dérangement.

Mais un grand merci pour ta réactivité !

François Yvon

2016-10-16 23:54 GMT+02:00 Alexandre Alapetite notifications@github.com:
