### ISSUE TITLE
Formatting issues

### ISSUE THREAD

**Issue by Jucgshu** [FreshRSS/FreshRSS#1333]
Hey guys,

I have some issues with some feeds which don't format nicely. I can't say if it's the feeds themselves or the way FreshRSS is displaying them.

What do you think ?

Example of feeds :
- https://bridge.suumitsu.eu/?action=display&bridge=GithubIssue&c=on&u=FreshRSS&p=FreshRSS&format=Atom
- https://bridge.suumitsu.eu/?action=display&bridge=GithubIssue&c=on&u=FreshRSS&p=FreshRSS&format=Mrss

**Comment by Alkarex** [comment]
Could you please post a screenshot of the problem?

**Comment by Jucgshu** [comment]
Yes, sure. 

Here is the FreshRSS view :
![2016-10-19 13_46_39-github - freshrss feeds](https://cloud.githubusercontent.com/assets/3890387/19550576/6118bafc-96aa-11e6-9dd3-0ee6fc204383.jpg)

And the original view :
![2016-10-19 13_47_53-liste des lecteurs rss mobiles issue 328 freshrss_freshrss](https://cloud.githubusercontent.com/assets/3890387/19550600/84d3978c-96aa-11e6-9b9d-12ab1e1c3123.jpg)

The main issue is the scroll bar that pops in FreshRSS (I just tested it in another feed reeder with the same result, so maybe it's coming from the feed itself ?)

**Comment by Alkarex** [comment]
Ok. It is because the RSS feed puts everything into a `<pre>` tag.

```
<content type="html">&lt;pre&gt; &lt;p&gt;Could you please post a screenshot of the problem?&lt;/p&gt; &lt;/pre&gt;</content>
```

You could consider adding a custom CSS for having the text to wrap to the next line
https://developer.mozilla.org/docs/Web/CSS/white-space

As far as I can see, no problem from FreshRSS side :-)

**Comment by Alwaysin** [comment]
Maybe you already know but you can subscribe to Github RSS directly, without a bridge. Even though messages are truncated, I admit.

![chrome_2016-10-20_12-51-31](https://cloud.githubusercontent.com/assets/7189936/19557130/a466e210-96c4-11e6-83a7-4e7bfb7555b8.png)

**Comment by Jucgshu** [comment]
Fine by me.

As always, thank you for your answers :-)

**Comment by Jucgshu** [comment]
@Alwaysin : i missed your answer. Nope, didn't know. 

But I must say the whole feed is better :)
