### ISSUE TITLE
Problème configuration partage

### ISSUE THREAD

**Issue by prolibre** [FreshRSS/FreshRSS#1334]
Bonjour (je me permet le français)

Je viens d'installer la version "master" (git install) sans problème.
Version 1.5.0.  sur debian stable ( Apache2 / PHP 5.6.26 / Mysql )

Par contre, impossible de configurer le moindre "partage".

A chaque tentative d'ajout (et quel qu'il soit : diaspora, courriel etc. ) je reviens sur la page ( `?c=configure&a=sharing` ) mais sans mon nouveau partage.

Dans les logs je trouve à chaque fois : 

```
[Wed Oct 19 16:30:02.577779 2016] [:error] [pid 17193] [client IP:55956] PHP Notice:  Undefined index: share in /DIR_INSTALL/FreshRSS/app/Controllers/configureController.php on line 143
[Wed Oct 19 16:30:02.577813 2016] [:error] [pid 17193] [client IP:55956] PHP Warning:  Invalid argument supplied for foreach() in /DIR_INSTALL/FreshRSS/app/Models/ConfigurationSetter.php on line 125
```

**Comment by Alkarex** [comment]
Bonjour,
Pourriez-vous essayer la branche /dev ? C'est la version 1.6 qui sera proposée dans quelques jours, et plusieurs bugs de partage y ont été corrigés.
https://github.com/FreshRSS/FreshRSS/issues/1289 https://github.com/FreshRSS/FreshRSS/issues/1301

**Comment by prolibre** [comment]
Bonjour @Alkarex ... je vais donc plutôt attendre cette version. Merci pour votre travail.
