### ISSUE TITLE
imageproxy doesn't seem to work

### ISSUE THREAD

**Issue by roryst** [FreshRSS/FreshRSS#1341]
very few images actually show up. i enabled imageproxy and left everything blank. the only thing i see that might be useful is:
[Sun Oct 23 00:01:58.792977 2016] [:error] [pid 3878] [client 98.228.100.186:53070] PHP Notice:  Trying to get property of non-object in /var/www/FreshRSS-master/extensions/xExtension-ImageProxy/extension.php on line 8

i've also tried putting in localhost:3128 as proxy, but the same error/problem would occur.

**Comment by Alkarex** [comment]
Hello @markybob 
Could you please tell which version of FreshRSS and imageproxy extension you are using?
There has been some recent fixes in the [/dev version](https://github.com/FreshRSS/FreshRSS/tree/dev), which will soon be released as version 1.6. It would be nice if you could give it a try, if the version you have is not already the /dev version from today.

Maybe @Frenzie could have a look if the problem is still there in /dev ?

**Comment by roryst** [comment]
1.5 and 0.2. do i just copy over config.php?

**Comment by roryst** [comment]
i downloaded dev and configured it. moved over imageproxy from 1.5 since /dev didn't have one. the extensions page is blank and i cant enable it. the permissions on the dirs are correct. the logs are clear.

**Comment by roryst** [comment]
i found the github for the extensions. downloaded that and moved it over. same issue as before with the apache log 
8016] PHP Notice:  Trying to get property of non-object in /var/www/FreshRSS-dev/extensions/xExtension-ImageProxy/extension.php on line 8

**Comment by Frenzie** [comment]
Could you see what happens when you replace `$user_conf` with `$system_conf` in extension.php? It's still unclear to me what's most desirable but right now there's still a mismatch. But for me it basically works no matter what.

**Comment by roryst** [comment]
in extensions/xExtension-ImageProxy/extension.php, correct? i get the same. 

[Mon Oct 24 09:29:01.759215 2016] [:error] [pid 17262] [client 185.137.18.184:56980] PHP Notice:  Trying to get property of non-object in /var/www/FreshRSS-dev/extensions/xExtension-ImageProxy/extension.php on line 8

**Comment by Frenzie** [comment]
Maybe it's best to return to the basics. What is the URL of the images that don't show up? What is the URL of those that do?

Here's an example of insecure images the URLs of which will be rewritten by ImageProxy:

```
http://www.questionablecontent.net/QCRSS.xml
```

**Comment by roryst** [comment]
here's an example of the image not showing:
![screenshot_2016-11-07_10-33-33](https://cloud.githubusercontent.com/assets/212093/20063613/e2a77200-a4d5-11e6-875b-8c92c01b8e3a.png)

but when i right click on the empty box, copy image location and open it in another tab, it works:
![screenshot_2016-11-07_10-33-57](https://cloud.githubusercontent.com/assets/212093/20063633/f2b27974-a4d5-11e6-968a-e279f782a898.png)

this is with 1.6.1. thanks.

**Comment by Frenzie** [comment]
I haven't noticed any issues in Chromium-based browsers like Vivaldi myself. Do you have any special FreshRSS or Vivaldi settings? For example, lazyload vs. no lazyload in Configuration → Reading or referer (sic.) vs. no referer in Vivaldi.

**Comment by roryst** [comment]
i had lazyload checked. when i unchecked, i couldn't even tell an image was supposed to be there. no empty space even. i dont think i have any weird settings. i tried it on google chrome proper 54.0.2840.90 (Official Build) (64-bit) with the same result. hrm :/

**Comment by roryst** [comment]
thanks for your patience and i'm sorry to have wasted your time. figured it out. it was a stupid Content-Security-Policy for img-src.  appreciate it!

**Comment by Frenzie** [comment]
Could you perhaps clarify a bit more in case someone else has the same issue? You mean a server configuration on your end?

**Comment by roryst** [comment]
yes, it's a server config. in apache it's:
Header always set Content-Security-Policy 
and you need to add images.weserv.nl to img-src or else it won't load it. 

more info here
https://developer.mozilla.org/en-US/docs/Web/Security/CSP

**Comment by Alkarex** [comment]
Please note that FreshRSS also adds some CSP rules, though not on images.
