### ISSUE TITLE
recherche des comptes inactifs

### ISSUE THREAD

**Issue by prolibre** [FreshRSS/FreshRSS#1345]
Bonjour,

Est-il possible de visualiser la date de dernière connexion des utilisateurs ?
J'ai ouvert une instance FreshRSS pour permettre à tout un chacun de tester et d'utiliser l'outil mais j'aimerai pouvoir supprimer les comptes inactif depuis X jours pour éviter l'utilisation inutile de ressources.
Cette option est elle disponible dans la version DEV ?
Merci pour le boulot.

**Comment by Alkarex** [comment]
Bonjour,
Il est possible de voir la dernière activité des utilisateurs par la commande suivante :

``` sh
cd /usr/share/FreshRSS
ls -lh data/users/*/config.php
```

Un `touch()` est effectué sur ce fichier à chaque action d'un utilisateur. Notez que si l'utilisateur ne fait aucune action (comme marquer un article comme lu, ajouter un favori, changer une option...), le `touch()` n'est pas appelé.

Je pourrais ajouter une option dans l'interface en ligne de commande (CLI) pour récupérer cette information de manière plus propre, si cela vous intéresse. https://github.com/FreshRSS/FreshRSS/issues/1095

**Comment by prolibre** [comment]
merci :-) bonne semaine à vous.

**Comment by Alkarex** [comment]
@prolibre Je viens de remarquer que le touch() n'était pas appelé correctement. Aussi, la commande ci-dessus pouvait sous-estimer l'usage. Je suis en train de corriger, et j'ai une API en ligne de commande presque prête.

**Comment by Alkarex** [comment]
@prolibre Corrigé dans https://github.com/FreshRSS/FreshRSS/pull/1358 , ainsi qu'une nouvelle commande :

``` sh
./cli/user-info.php -h --user '*'
```

Exemple de résultat :

``` sh
./cli/user-info.php -h --user '*' | sort -k2 -r
*   admin   2016-11-05T21:32:10+01:00   288.67 MiB
    jean    2016-11-05T19:35:28+01:00   4.63 MiB
    paul    2016-11-04T08:50:50+01:00   34.66 MiB
    pierre  2016-10-24T23:10:06+02:00   4.06 MiB
    jacques 2016-10-16T18:34:12+02:00   8.52 MiB
```

Tests bienvenus :-)
