### ISSUE TITLE
update check 1.6.0

### ISSUE THREAD

**Issue by roryst** [FreshRSS/FreshRSS#1347]
Shouldn't ?c=update&a=check show 1.6.0 and update? 

Your current version of FreshRSS is the 1.5.0.
Last verification: October 30th 2016 at 20:05
Damn! No update to apply

**Comment by Alkarex** [comment]
Hello,
The auto-update mechanism will prompt for a new version in a few days.
Meanwhile, git pull or manual install can already use 1.6.

**Comment by Alkarex** [comment]
@marienfressinaud We should skip 1.6.0 and set the update system directly to 1.6.1 https://github.com/FreshRSS/FreshRSS/releases/tag/1.6.1

**Comment by marienfressinaud** [comment]
Done!
