### ISSUE TITLE
Confirm before mark as read: Impossible to mark as read

### ISSUE THREAD

**Issue by lapineige** [FreshRSS/FreshRSS#1348]
This is the following of bug #1342.

@Alkarex you added the option `disabled` in order to prevent users to activate the mark as read feature before the script is loaded.
In my case, the option never disappears.

I'm wondering if the script is correctly loaded/launched.

Is it still an issue of caching, as I have (see #1342) ?
(the main.js script is cached, and removing the cache change nothing)

Thanks in advance for your help :)

**Comment by Alkarex** [comment]
@lapineige Could you please try this patch? https://github.com/FreshRSS/FreshRSS/pull/1374

Another observation: it looks like YunoHost is injecting a script `ynhpanel.js` in `<head>`, which is not compatible with CSP:

> ynhpanel.js:173 Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à self (« default-src https://yunohost.example.net »).

**Comment by lapineige** [comment]
> @lapineige Could you please try this patch? #1374 

I will do it ASAP, thanks :)

> Another observation: it looks like YunoHost is injecting a script ynhpanel.js in <head>, which is not compatible with CSP:

I know, I didn't take any time to change it, because it's the button to go back to yunohost main screen, I don't need it - it's even a bit annoying (taking a lot of space on phones), so I just don't mind ^^

**Comment by lapineige** [comment]
Ok, patch working, thank you :)
