### ISSUE TITLE
Feed error : PS4Hax

### ISSUE THREAD

**Issue by Draky50110** [FreshRSS/FreshRSS#1352]
Hello.

Error retrieving this feed : http://www.ps4hax.net/dorss.php

FreshRSS log : This XML document is invalid, likely due to invalid characters. XML error: Invalid document end at line 239, column 1, encoding ISO-8859-1, URL: http://www.ps4hax.net/dorss.php [http://www.ps4hax.net/dorss.php]
Version = 1.5.0

Possible to circumvent this or do I need to contact the webmaster ?

**Comment by Alkarex** [comment]
Hello,
No, no way to support this feed, which has too many errors.
In particular, see those warnings included at the end of the feed:

```
<br />
<b>Warning</b>:  mkdir() [<a href='function.mkdir'>function.mkdir</a>]: Permission denied in <b>/home/ps4hax/public_html/includes/caching.php</b> on line <b>110</b><br />
<br />
<b>Warning</b>:  file_put_contents(/home/ps4hax/cache/rss/feed.time) [<a href='function.file-put-contents'>function.file-put-contents</a>]: failed to open stream: No such file or directory in <b>/home/ps4hax/public_html/includes/caching.php</b> on line <b>49</b><br />
<br />
<b>Warning</b>:  file_put_contents(/home/ps4hax/cache/rss/feed.cache) [<a href='function.file-put-contents'>function.file-put-contents</a>]: failed to open stream: No such file or directory in <b>/home/ps4hax/public_html/includes/caching.php</b> on line <b>50</b><br />
```

**Comment by Alkarex** [comment]
https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fwww.ps4hax.net%2Fdorss.php
