### ISSUE TITLE
Curl error 52

### ISSUE THREAD

**Issue by Jean-Mich-Much** [FreshRSS/FreshRSS#1353]
Bonjour,

Depuis une bonne petite semaine il est impossible de récupérer le flux RSS http://www.jeuxvideo.com/rss/rss.xml (log=cURL error 52: Empty reply from server [http://www.jeuxvideo.com/rss/rss.xml]), par contre le flux est lisible dans tous les navigateurs sauf quand il s’agit d'une communication entre serveurs (j'ai essayé manuellement pour voir si c'était uniquement dû à curl, avec d'autres fonctions comme file_get_contents, copy, fopen, stream_context_create : rien n'y fait, j'ai aussi voulu voir si cela venait de mon propre serveur et essayé sur votre serveur demo : erreur identique (cURL error 52). Mon serveur = php 5.6 - Nginx 1.11.5, à noter que j'ai récupéré le flux finalement avec feedburner en lui indiquant l'adresse du flux tout simplement (ce qui prouve que le flux est lisible par un serveur il faut juste trouver pourquoi cela ne fonctionne pas avec freshrss)

**Comment by Alkarex** [comment]
Cela ressemble très fortement à un filtrage par IP :

``` sh
curl -v http://www.jeuxvideo.com/rss/rss.xml
```

fonctionne depuis plusieurs de mes serveurs, mais pas celui que j'ai chez OVH.

Depuis mon serveur OVH, même `lynx http://www.jeuxvideo.com/` ne marche pas.

Idées :
- Les contacter (demander peut-être une raison)
- Passer par un proxy ou un service comme https://superfeedr.com/subscriber

Si c'est dû à des abus sur leurs flux RSS (par exemple trop de gens qui rafraîchissent trop souvent), il y a des solutions (comme utiliser PubSubHubbub et avoir une politique de cache côté serveur, ce qui n'est pas le cas actuellement, ou utiliser un service comme https://superfeedr.com/publisher ). Je conseille volontiers. Voir par exemple le commentaire que j'ai écrit https://blog.genma.fr/?RSS-Message-de-service-et-conseils-pour-l-agregateur-RSS#forum6295

**Comment by Jean-Mich-Much** [comment]
Merci

**Comment by aurmil** [comment]
bonjour,

@Jean-Mich-Much comment avez vous résolu ce problème ?
je vois dans les logs que curl reçoit une 403
je suis aussi sur un mutu OVH

merci

**Comment by Jean-Mich-Much** [comment]
Coucou, je suis passé par feedburner tout simplement

**Comment by aurmil** [comment]
OK merci, j'ai adopté aussi cette solution faute de mieux
