### ISSUE TITLE
Bookmarklet improvements suggestions

### ISSUE THREAD

**Issue by subic** [FreshRSS/FreshRSS#1354]
Bookmarklet integration could be more user friendly:

a) The current link looks like a menu item but is instead the whole bookmarklet code/link. While this serves its purpose, it could better integrated and offer more information to the user (see attached image for a suggestion).

b) I have also included a Firefox integration information in the image for those that prefer it (see Issue #425 ). I think it could be helpful to also include it somewhere (maybe the docs instead).

![bookmarklet](https://cloud.githubusercontent.com/assets/6759483/20008895/9c763508-a2a2-11e6-941e-1211ff3feefe.png)

c) When adding a feed through bookmarklet the "Cancel" button does nothing. It should either:
- Not be present on the page
- Redirect to homepage
- Close the window

I prefer the last solution but either is better than the current button which does nothing.

Let me know what you think and I'll try to whip up a pull request.

**Comment by Alkarex** [comment]
Hello @subic 
This is an excellent suggestion, and your UI sketch looks perfect to me.
Regarding question c), I think any of your propositions would be fine and my least favourite is the first; so the second or the last

**Comment by Alkarex** [comment]
@subic : This was kindly implemented by @aledeg https://github.com/FreshRSS/FreshRSS/issues/1568 . Available in the /dev branch of FreshRSS. Please give it a try :-)
