### ISSUE TITLE
Allow socket as database path

### ISSUE THREAD

**Issue by hrehfeld** [FreshRSS/FreshRSS#1364]
My shared host opens postgres connections only as a socket to /home/$USER/tmp, but the field in the installation doesn't allow me to put in a path; it complains that it's not the right format.

(Hoster doc says that all libs linking to the original postgres lib should be able to deal with filepaths/sockets fine)

**Comment by hrehfeld** [comment]
Work-Around: add slash in regexp here: https://github.com/FreshRSS/FreshRSS/blob/master/app/install.php#L637

**Comment by Alkarex** [comment]
Thanks. Fixed in patch https://github.com/FreshRSS/FreshRSS/pull/1366

**Comment by Alkarex** [comment]
Tests welcome. And I will then merge in /dev

**Comment by hrehfeld** [comment]
thanks!

**Comment by Alkarex** [comment]
Merged in /dev
