### ISSUE TITLE
Czech characters

### ISSUE THREAD

**Issue by theerror** [FreshRSS/FreshRSS#1365]
Please use "Latin extended" `(subset=latin-ext)` version of font, or use some remote or at least make possible to change those by GUI. The those "bold char" would be fixed. There is no too much big difference in size, however it will resolve those unknown characters replaced by default browser font.

![1_396 _rss_kanaly_ _freshrss_-_2016-11-07_15 16 44](https://cloud.githubusercontent.com/assets/4508328/20060808/40190e40-a4fd-11e6-9162-7515d1e5ff17.png)

**Comment by theerror** [comment]
it's not good visible on screenshot, however those czech character are "bolded" and by different font, which looks quite messy.

**Comment by Alkarex** [comment]
Related to https://github.com/FreshRSS/FreshRSS/pull/1032

**Comment by theerror** [comment]
My hot-fix diff:

```
--- p/themes/Pafat/pafat.css.back   2016-11-07 15:47:07.424986247 +0100
+++ p/themes/Pafat/pafat.css    2016-11-07 15:45:09.268575991 +0100
@@ -1,3 +1,4 @@
+@import url('https://fonts.googleapis.com/css?family=Open+Sans&subset=latin-ext');
 @charset "UTF-8";

 /*=== FONTS */
@@ -10,7 +11,7 @@
 /*============*/
 html, body {
    height: 100%;
-   font-family: "OpenSans", "Cantarell", "Helvetica", "Arial", sans-serif;
+   font-family: "Open Sans", "Cantarell", "Helvetica", "Arial", sans-serif;
    background: #fafafa;
    color : #666;
 }
```

**Comment by alfureu** [comment]
Still not working correctly in 1.8.0, see attached screenshot.

![freshrss](https://user-images.githubusercontent.com/10846169/33549540-dd5dd93a-d925-11e7-8837-428313632da2.png)

**Comment by Alkarex** [comment]
Would you be willing to give a try to the /dev version of FreshRSS? https://github.com/FreshRSS/FreshRSS/tree/dev
We have added some more glyphs to the font (in https://github.com/FreshRSS/FreshRSS/pull/1032 ), which should improve the situation.

**Comment by theerror** [comment]
Yea, I have to agree.... it's starting to be a little annoying to fix this every version, especially, when fix is not so hard to implement, or is it so? What's about using remote font as workaround till this will be somehow fixed in internal compilation process or whatever problem is...?

**Comment by alfureu** [comment]
@Alkarex Thanks for this, I am running FreshRSS on a NAS, so the only update option I have is the regular updates. Don't you update the software like 1.8.1, 1.8.2, etc.?

**Comment by Frenzie** [comment]
@DOFfactory Yes, but those are stable. ;-)

**Comment by alfureu** [comment]
@Frenzie @Alkarex ... and fixing the font encoding is actually not a way towards stable sw ... uhum

**Comment by theerror** [comment]
Not tested the rest, but from point of view the text - it's working fine (DEV).

Actual stable:
![rss-font](https://user-images.githubusercontent.com/4508328/33552098-fe709022-d8f3-11e7-9e5f-e8a1a458eccc.png)

DEV one
![rss-font-dev](https://user-images.githubusercontent.com/4508328/33552097-fe565522-d8f3-11e7-94f6-6d59c13592c4.png)

You can test by adding this RSS (Google new for czech rep). There always will be some extended chars. - https://news.google.com/news/rss/?gl=CZ&ned=cs_cz&hl=cs

**Comment by Frenzie** [comment]
@DOFfactory Yes, it will automatically become 1.8.1 or 1.9.0 in due time. ;-)

**Comment by kevinpapst** [comment]
The other workaround would be to install the CustomCSS extension:
https://github.com/FreshRSS/Extensions

And add the following CSS rules:
```
@import url('https://fonts.googleapis.com/css?family=Open+Sans&subset=latin-ext');
 html, body {
  font-family: "Open Sans", "Cantarell", "Helvetica", "Arial", sans-serif !important;
 }
```
This will stay and does not need to be reapplied after an FreshRSS update.

**Comment by Alkarex** [comment]
We will make a new release soon :-)
