### ISSUE TITLE
[FR] Tag category

### ISSUE THREAD

**Issue by anayrat** [FreshRSS/FreshRSS#1367]
Hi,

It will be usefull if we can use tag as category with advanced filter : 

- Main stream
  - Tags
    - Tag 1
    - Tag 2
  - My category 1
    - Feed 1
  - My category 2
    - Feed 2

**Comment by anayrat** [comment]
For information this functionnality is in tinyrss. It is missing for my usage :(

**Comment by Alkarex** [comment]
Related to https://github.com/FreshRSS/FreshRSS/issues/928

**Comment by Alkarex** [comment]
Implemented in https://github.com/FreshRSS/FreshRSS/pull/2027
Tests welcome
