### ISSUE TITLE
OVH: Can't access database after update

### ISSUE THREAD

**Issue by pierrecastor** [FreshRSS/FreshRSS#1369]
I make an update from 1.4 to 1.5, using the auto-update tool.

After this, i can't access to my instance, index.php show me : 

> ### Fatal error! ###
> See logs files.

And the log file : 

`[Thu, 10 Nov 2016 15:29:07 +0100] [error] --- Access to database is denied for `infofaciledb` (`mysql:host=infofaciledb.mysql.db;dbname=infofaciledb;charset=utf8mb4`)`

I tried to delete the FTP directory to make a new installation, but after a successful installation procedure, the same issue occur.

I can access to my database normally with a little php code on my ftp. 

My instance of freshrss run on a OVH shared server with PHP 5.6 and MYSQL.

Ask me for any other information.

Thanks in advance for your help

**Comment by Alkarex** [comment]
Bonsoir,
Pourriez-vous essayer https://docs.ovh.com/fr/fr/web/hosting/modifier-lenvironnement-dexecution-de-mon-hebergement-web/ ?

Sûrement le même bug que https://github.com/FreshRSS/FreshRSS/issues/1243#issuecomment-244941741 parce que votre pilote MySQL est beaucoup trop vieux
