### ISSUE TITLE
PHP Fatal error with favicons in 1.6.1

### ISSUE THREAD

**Issue by Nodd** [FreshRSS/FreshRSS#1370]
I updated from 1.5 to 1.6.1 and since the update the automatic feed update (cron) yields this error:
```
PHP Fatal error:  Call to undefined function Favicon\finfo_open() in /volume1/web/freshrss/lib/Favicon/Favicon.php on line 229
```
I did the update using the auto-update feature.

**Comment by Alkarex** [comment]
Hello,
It is a new feature of 1.6 to update Favicons as part of the cron job. If it fails, it might be that the PHP version used from your command line is not the same as the PHP version used by your Web server.
Could you please try the following command?

``` sh
php -i | grep fileinfo
```

You should get an output like:

```
/etc/php/7.0/cli/conf.d/20-fileinfo.ini,
fileinfo
fileinfo support => enabled
```

**Comment by Nodd** [comment]
There is nothing about `fileinfo` in the output, but the version is different from the one reported by freshrss:
- freshrss uses 5.6.23
- commandline uses 5.6.11
  I can't find where the executable for 5.6.23 is located on my system (I'm on a synology NAS).

**Comment by Alkarex** [comment]
Related: https://github.com/FreshRSS/FreshRSS/issues/1126

**Comment by Nodd** [comment]
`php56` did the trick:

```
$ php56 -i | grep fileinfo
fileinfo
fileinfo support => enabled
```

And everything works fine. Thanks for the support and for the great software !

**Comment by Nodd** [comment]
Just a thought: if the php executable was displayed in the Installation verification page for example, the documentation could refer to this information to setup correctly the cron job.
