### ISSUE TITLE
[Bug] [1.6.1] Articles mark as read by scrolling down

### ISSUE THREAD

**Issue by bonome54** [FreshRSS/FreshRSS#1371]
Since I upgrade to 1.6.1, the articles are mark as read when I scroll down trough them. I made a screencast of the problem.
![vokoscreen-2016-11-14_15-49-05](https://cloud.githubusercontent.com/assets/23456154/20269259/b3eba7ee-aa82-11e6-891d-dfeef4e39045.gif)

**Comment by Alkarex** [comment]
Hello @bonome54 
It is not a bug, but a feature :-)
You can uncheck the option "Mark article as read… while scrolling".
https://github.com/FreshRSS/FreshRSS/blob/1.6.0/CHANGELOG.md
https://github.com/FreshRSS/FreshRSS/pull/1309
