### ISSUE TITLE
category reorganization

### ISSUE THREAD

**Issue by roryst** [FreshRSS/FreshRSS#1378]
is there an easy way to change the category of more than one feed at a time instead of opening each feed individually and selecting a new category?

**Comment by Alkarex** [comment]
Hello,
You can drag&drop the feeds to another category, from the feed management
view.

**Comment by roryst** [comment]
doesnt work here. looks like it's another content-security-policy issue, but this one makes no sense. it says to use 'unsafe-inline' in script-src...but that's already set. 

markybob@bethany:~/Fresh$ curl -v https://dipconsultants.com
* Rebuilt URL to: https://dipconsultants.com/
*   Trying 2a01:7e00::f03c:91ff:fee2:9940...
* TCP_NODELAY set
* Connected to dipconsultants.com (2a01:7e00::f03c:91ff:fee2:9940) port 443 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 696 certificates in /etc/ssl/certs
* ALPN, offering h2
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_256_GCM_SHA384
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: dipconsultants.com (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: CN=dipconsultants.com
* 	 start date: Sun, 06 Nov 2016 11:00:00 GMT
* 	 expire date: Sat, 04 Feb 2017 11:00:00 GMT
* 	 issuer: CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US
* 	 compression: NULL
* ALPN, server accepted to use h2
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55cb40277400)
> GET / HTTP/1.1
> Host: dipconsultants.com
> User-Agent: curl/7.51.0
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200 
< date: Tue, 22 Nov 2016 06:20:22 GMT
< server: Apache
< x-frame-options: sameorigin
< x-content-type-options: nosniff
< x-xss-protection: 1; mode=block
< content-security-policy: default-src 'self' https:; img-src *; style-src 'self' maxcdn.bootstrapcdn.com fonts.googleapis.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' www.google-analytics.com ajax.googleapis.com;font-src 'self' fonts.googleapis.com maxcdn.bootstrapcdn.com;
< strict-transport-security: max-age=15552001; includeSubdomains; preload
< public-key-pins: pin-sha256="YLh1dUR9y6Kja30RrAn7JKnbQG/uEtLMkBgFF2Fuihg="; pin-sha256="47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU="; max-age=2592000; includeSubDomains
< vary: Accept-Encoding
< content-length: 648
< content-type: text/html; charset=UTF-8
< 

and here's the dev console error in the browser:

VM1249:674 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'unsafe-eval' 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-8UwpdwiuqXJty4DoSWEA9W+FMdXW5Ol0a3ZjF7czsyo='), or a nonce ('nonce-...') is required to enable inline execution.
addScript @ VM1249:674fakeFuckAdBlock @ VM1249:945onStart @ VM1249:5096(anonymous function) @ VM1249:5534handlerEvents @ VM1249:5518blockDetect @ VM1249:5773initialize @ VM1249:105(anonymous function) @ VM1249:5780tms_e5647f8a_a053_47e7_9987_c4305e5db687 @ VM1249:5782(anonymous function) @ VM1178:2Aak.name @ VM1249:3(anonymous function) @ VM1249:4(anonymous function) @ VM1249:5783(anonymous function) @ VM1178:2C @ VM1248:58create @ VM1248:66u @ VM1248:15run @ VM1248:15(anonymous function) @ VM1248:67(anonymous function) @ VM1248:67(anonymous function) @ VM1248:67TM_back @ VM1248:68(anonymous function) @ VM1248:68(anonymous function) @ VM1178:2exec_fn @ VM1178:1(anonymous function) @ VM1178:10(anonymous function) @ VM1178:9e @ content.js:6send @ content.js:8next @ content.js:13(anonymous function) @ content.js:25(anonymous function) @ content.js:23sendResponseAndClearCallback @ extensions::messaging:361messageListener @ extensions::messaging:393target.(anonymous function) @ extensions::SafeBuiltins:19EventImpl.dispatchToListener @ extensions::event_bindings:388target.(anonymous function) @ extensions::SafeBuiltins:19publicClassPrototype.(anonymous function) @ extensions::utils:153EventImpl.dispatch_ @ extensions::event_bindings:372EventImpl.dispatch @ extensions::event_bindings:394target.(anonymous function) @ extensions::SafeBuiltins:19publicClassPrototype.(anonymous function) @ extensions::utils:153dispatchOnMessage @ extensions::messaging:334
VM1249:674 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'unsafe-eval' 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-nC1EIFTfIzbc0hgADWC4Eos+jMRdIaPymHrOT/14N2s='), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by Alkarex** [comment]
Would you have the possibility of sending a a screenshot of the page + browser console (cleared just before trying to move a feed)?

**Comment by roryst** [comment]
nothing actually changes in browser console when i try to drag/drop. 

![screenshot_2016-11-22_01-46-02](https://cloud.githubusercontent.com/assets/212093/20515101/8e719cac-b055-11e6-9788-1856daa75501.png)

apache config:
Header always set Content-Security-Policy "default-src 'self' https:; img-src *; style-src 'self' maxcdn.bootstrapcdn.com fonts.googleapis.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' www.google-analytics.com ajax.googleapis.com;font-src 'self' fonts.googleapis.com maxcdn.bootstrapcdn.com;"

**Comment by Alkarex** [comment]
At a first glance, it looks like the CSP errors are not from FreshRSS, but from some other browser extensions.
Would you have the possibility of making me a test account on your instance? If yes, you can send a private e-mail https://alexandre.alapetite.fr/cv/

**Comment by Alkarex** [comment]
Hello again:
1. The drag & drop of feeds seem to work fine (tested with Firefox and Chrome)
![drag-drop](https://cloud.githubusercontent.com/assets/1008324/20534204/929bcf4c-b0e0-11e6-925d-56deb6dcda52.png)
2. Your server sends invalid CSP rules, e.g. with two times a 'default-src' rule. Please note that FreshRSS is already set up to send CSP headers. You can replace them at your server level though, if you need to change them.

```
content-security-policy :"default-src 'self' https:; img-src *; style-src 'self' maxcdn.bootstrapcdn.com fonts.googleapis.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' www.google-analytics.com ajax.googleapis.com;font-src 'self' fonts.googleapis.com maxcdn.bootstrapcdn.com;, default-src 'self'; child-src *; frame-src *; img-src * data:; media-src *"
```

**Comment by roryst** [comment]
thank you very much, that made it work.
