### ISSUE TITLE
Filter isn't working

### ISSUE THREAD

**Issue by Crupuk** [FreshRSS/FreshRSS#1379]
Hi,

I'm new on freshrss and i don't know how to get the filters work correctly.
I try the filter : "date:2015-11 intitle:FreshRSS" ( From the docs ) on the FreshRss.org feed and it doesn't work.

Expected result : 
- Only show one line ( Article from 04-11:2015 ) 

Actual result : 
- Show the full result from FreshRss feed

FreshRss version : 1.6.1

Thanks for your help

**Comment by Alkarex** [comment]
Hello,
I have tried your exact example, which works as expected on my instance.
Just to be sure: you should not have quotes. Here is a screenshot from my side:
![date](https://cloud.githubusercontent.com/assets/1008324/20535913/379ff5ee-b0e7-11e6-81b8-4ebf8eb7010c.png)
Could you send a screenshot illustrating the problem?

**Comment by Alkarex** [comment]
Ah, something else: the `date:` works on the date when the article was discovered by FreshRSS, so it will not work on articles older than your installation. You can try with `pubdate:` which works with the date declared by the articles.

**Comment by Crupuk** [comment]
Hi, @Alkarex  thanks for your reply,

I'm not talking about the search bar but the filter option in freshrss 

http://doc.freshrss.org/en/users/03_Main_view/#filtering-articles

**Comment by Alkarex** [comment]
Filters are using a search. Could you please send a screenshot illustrating the problem?

**Comment by Crupuk** [comment]
Same filter, with the FreshRss feed and with the search bar : 

![freshrss1](https://cloud.githubusercontent.com/assets/670728/20555060/208901a6-b160-11e6-80c7-72fdc02ed2e2.PNG)
![freshrss2](https://cloud.githubusercontent.com/assets/670728/20555061/20a038e4-b160-11e6-819c-a10d2c71a3c2.PNG)
![freshrss3](https://cloud.githubusercontent.com/assets/670728/20555062/20acabec-b160-11e6-9b17-6c297276b09b.PNG)

When i click on this filter option, nothings happen

**Comment by Alkarex** [comment]
Ah, right: try the following:
* Use the search field to filter as you want
* When this is done, use the "add a query" menu
![query](https://cloud.githubusercontent.com/assets/1008324/20555663/5fbfcb4a-b163-11e6-9db1-df49a7eb5bb9.png)
* See the result
![filter](https://cloud.githubusercontent.com/assets/1008324/20555668/6856c9de-b163-11e6-8148-b97e1e264d24.png)

**Comment by Crupuk** [comment]
Ah thanks !!

Could you juste tell me one more thing ?
Is there a way to exclude a word ? 

Like : "intitle:-FreshRss" ?

**Comment by Alkarex** [comment]
We currently do not have exclusion filters, but that would not be very difficult to add.
Could you please create a new issue for that?
Related:
* https://github.com/FreshRSS/FreshRSS/issues/511#issuecomment-45672812
* https://github.com/FreshRSS/FreshRSS/issues/1189

**Comment by tetrisgm** [comment]
I'm trying to make it so my feeds (either specific, or all) mark articles as read when they have some keywords. For example 'deals'. This would be very helpful to filter out some sections from some feeds. Is there a simple way to do this? I've tried going in the settings of each feed and in the filter section, adding one word per line, but the articles still appear and don't get marked as read.
