### ISSUE TITLE
Favicons are not loaded

### ISSUE THREAD

**Issue by thomasrenes** [FreshRSS/FreshRSS#1380]
I have a issue were favicons of some RSS feeds are not loaded in FreshRSS since I've updated to version 1.6.1. For these RSS feeds Chrome displays the "image not found icon" on the place where the favicon of that feed should be. When manually going to to the URL "[domain]/p/f.php?8fff8de3" I don't get any output.

Example RSS Feed:
https://developer.apple.com/news/rss/news.rss

The favicon.ico file does exist:
https://developer.apple.com/favicon.ico

The file is created on the server but is empty:
```
[favicons]# file 8fff8de3.ico
8fff8de3.ico: empty
[favicons]# cat 8fff8de3.txt
https://developer.apple.com/news
```

```
[tmp]# wget https://developer.apple.com/favicon.ico
--2016-11-23 09:29:47--  https://developer.apple.com/favicon.ico
Resolving developer.apple.com... 17.146.1.14
Connecting to developer.apple.com|17.146.1.14|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9062 (8.8K) [image/vnd.microsoft.icon]
Saving to: `favicon.ico'

100%[======================================>] 9,062       --.-K/s   in 0s

2016-11-23 09:29:47 (626 MB/s) - `favicon.ico' saved [9062/9062]

[tmp]# file favicon.ico
favicon.ico: MS Windows icon resource - 4 icons, 32x32, 256-colors
```

The permissions on the folders seems to be correct. I've tried manually removing all .ico and .txt files from the folder but the same feeds will have the same issue after the files are recreated.

This issue seems to be for 5 of the 164 RSS feeds I'm using:
```
[favicons]# find . -size 0 | grep ".ico" | wc -l
5
[favicons]# ls -ail *.ico | wc -l
164
```

**Comment by Alkarex** [comment]
A quick test gives an HTTP error 401:

```php
<?php
$favicon_url = 'https://developer.apple.com/favicon.ico';
$c = curl_init($favicon_url);
curl_setopt($c, CURLOPT_HEADER, false);
curl_setopt($c, CURLOPT_RETURNTRANSFER, true);
curl_setopt($c, CURLOPT_BINARYTRANSFER, true);
$img_raw = curl_exec($c);
$status_code = curl_getinfo($c, CURLINFO_HTTP_CODE);
curl_close($c);
echo $status_code, "\n";
```

I will try to find out why

**Comment by Alkarex** [comment]
Ah, found. The Web site requires a user-agent to be set, e.g.
```php
curl_setopt($c, CURLOPT_USERAGENT, 'curl/7.38.0');
```

**Comment by Alkarex** [comment]
@thomasrenes Should be fixed in https://github.com/FreshRSS/FreshRSS/pull/1385
Could you please give it a try?

**Comment by thomasrenes** [comment]
Great find! I did some testing and it does seem to fix it for 3 out of 5 websites.

The other two webservers only accept it when I set the useragent as a browser:
`curl_setopt($c, CURLOPT_USERAGENT, 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36');`

You can check this with: https://www.sixxs.net/favicon.ico

**Comment by thomasrenes** [comment]
Nevermind, I see you set the useragent to FreshRSS, that works with all URLs. Issue can be closed! Thanks!

**Comment by Alkarex** [comment]
Hooray :-)

**Comment by kevinpapst** [comment]
I had two feeds with broken favicons and both were fixed for me as well.
