### ISSUE TITLE
Exclude words on filter

### ISSUE THREAD

**Issue by Crupuk** [FreshRSS/FreshRSS#1381]
It would be interesting to be able to exclude words in filters

Related : 
https://github.com/FreshRSS/FreshRSS/issues/511#issuecomment-45672812
https://github.com/FreshRSS/FreshRSS/issues/1189

Thanks

**Comment by Alkarex** [comment]
Related to https://github.com/FreshRSS/FreshRSS/issues/879

**Comment by Alkarex** [comment]
Implemented in https://github.com/FreshRSS/FreshRSS/pull/1478
Could you please give it a try, @Crupuk ?
