### ISSUE TITLE
"Mark as read" does'nt work

### ISSUE THREAD

**Issue by noraj** [FreshRSS/FreshRSS#1382]
When clicking on "Mark as read" got an error

```
### Application problem ###
Permission is denied for `/usr/share/nginx/html/rss/data/users/[username]/log.txt`
```

File permissions are:

```
-rw-r--r-- 1 http http 73219 Nov 23 13:42 /usr/share/nginx/html/rss/data/users/[username]/log.txt
```
OS: archlinux
Web server path  /usr/share/nginx/html/
Web server user: http

**Comment by Alkarex** [comment]
Can you try to re-apply the rights? (example below, just adapt the user and the path)

```sh
cd /usr/share/FreshRSS
sudo chown -R :www-data . && sudo chmod -R g+r . && sudo chmod -R g+w ./data/
```

And then browse to the test page of your installation https://freshrss.example.net/i/?c=update&a=checkInstall

**Comment by noraj** [comment]
Now, I know why.

The hard disk drive of my dedicated server crashed and the whole file system passed read-only. So that's why `/usr/share/nginx/html/rss/data/users/[username]/log.txt` was not writable.

My bad, issue can be closed. Sorry for that.
