### ISSUE TITLE
Cache problem ? FreshRss show me 35 new entries and after refresh there is only 3

### ISSUE THREAD

**Issue by Crupuk** [FreshRSS/FreshRSS#1383]
This picture is self explaining i guess : 

When i'm go to freshrss : 

![freshrss-cache](https://cloud.githubusercontent.com/assets/670728/20621404/ab62f1c0-b2fe-11e6-982f-5a4d52bc2bfc.PNG)

After clicking on the blue banner : 

![freshrss-cache2](https://cloud.githubusercontent.com/assets/670728/20621405/ab63154c-b2fe-11e6-85e9-430865af9cc9.PNG)

And if i refresh the page, i still have "35 new entries" ...

Meanwhile Chrome always show me "35 new entries" notifications

Thanks

**Comment by Alkarex** [comment]
Bonjour,
Curieux en effet. Est-ce que vous n'auriez pas plusieurs navigateurs / onglets ouverts avec FreshRSS ? Ou un client mobile où vous faites des actions en même temps ?

* Essayez de ré-appliquer les droits d'accès. Exemple :

```sh
cd /usr/share/FreshRSS
sudo chown -R :www-data . && sudo chmod -R g+r . && sudo chmod -R g+w ./data/
```

* Essayez un coup *Optimiser la base de données* https://freshrss.example.net/i/?c=configure&a=archiving

* Vérifiez l'installation https://freshrss.example.net/i/?c=update&a=checkInstall

* Vérifiez vos logs (FreshRSS et serveur Web)

**Comment by Crupuk** [comment]
Bon, le problème provenait de mon installation.

ModPageSpeed retournait le Json depuis le cache .
Après l'avoir désactivé, il semblerait que ce soit rentré dans l'ordre.

Merci à vous,

**Comment by Crupuk** [comment]
Malheureusement, il semblerait que ça ne soit toujours pas réglé.
Je n'arrive pas à trouver dans le code ou sont défini les headers envoyé pour le refresh  ( ?c=javascript&a=nbUnreadsPerFeed )

Parfois je me retrouve avec les headers suivant : 

```
Cache-Control:max-age=1
Connection:Keep-Alive
Content-Encoding:gzip
Content-Length:134
Content-Type:application/json; charset=UTF-8
Date:Thu, 05 Jan 2017 08:46:05 GMT
Expires:Thu, 05 Jan 2017 08:46:06 GMT
Keep-Alive:timeout=5, max=200
Server:Apache
Vary:Accept-Encoding
```

Et parfois ceux-ci : 

```
Cache-Control:max-age=7200
Content-Encoding:gzip
Content-Length:137
Content-Type:application/json; charset=UTF-8
Date:Thu, 05 Jan 2017 07:34:45 GMT
Expires:Thu, 05 Jan 2017 09:34:45 GMT
Last-Modified:Thu, 05 Jan 2017 07:31:37 GMT
Server:Apache
Vary:Accept-Encoding
```

Quand ce header tombe, je me retrouve avec , pendant deux heures le même nombre de "non lus" .

ModPageSpeed est désactivé, j'ai regardé je ne trouve nul part des ExpiresByType.

Si je modifie la page i/index.php en metant un exit(0) avant l'appel à "$front_controller->run();" je tombe sur un header plus classique : 

```
Cache-Control:max-age=7200
Connection:Keep-Alive
Content-Length:0
Content-Type:text/html; charset=UTF-8
Date:Thu, 05 Jan 2017 08:55:32 GMT
Expires:Thu, 05 Jan 2017 10:55:32 GMT
Keep-Alive:timeout=5, max=199
Server:Apache
```

J'avoue ne plus savoir ou chercher ..

**Comment by Alkarex** [comment]
Bonsoir,
Vous pouvez essayer ce que j'ai écrit un peu plus haut. Vous pouvez aussi
essayer de créer un fichier `data/no-cache.txt` qui désactive le cache HTTP.
Je ne pense pas que les entêtes de deux heures sont envoyés par FreshRSS.
