### ISSUE TITLE
Configurable "Keep me logged in" timeout

### ISSUE THREAD

**Issue by jgeboski** [FreshRSS/FreshRSS#1384]
Could we make the "keep me logged in" timeout configurable? I would ideally like to stay logged in forever, or something much longer than one month.

**Comment by Alkarex** [comment]
Hello @jgeboski 
I have made this patch for you https://github.com/FreshRSS/FreshRSS/pull/1397
Could you please give it a try?

**Comment by Alkarex** [comment]
P.S.: Merged in the /dev branch. Tests welcome

**Comment by jgeboski** [comment]
Appears to work as intended. I tested this via the 1.6.2 release. Thanks for making this happen!

![screenshot_2016-12-26_18-42-01](https://cloud.githubusercontent.com/assets/615378/21489112/c892b270-cb9b-11e6-89bc-5e34e329c71b.png)

**Comment by Alkarex** [comment]
Thanks for the feedback :-)
