### ISSUE TITLE
Need help to develop a new extension

### ISSUE THREAD

**Issue by kevinpapst** [FreshRSS/FreshRSS#1386]
Hi FreshRSS Team!

Thanks for this beautiful piece of software :) just found about it this evening and already see it as a great replacement for ... well, another popular but slow PHP feedreader ... 

Now I'd really like to develop extension(s) for FreshRSS, but have some questions:
1. is there a reason to favor static methods and `array('HelloWorldExtension', 'noMoreFeedsHook')` over using an instance and using `array($this, 'noMoreFeedsHook')`?
2. What is the difference between a user and a system extension?
3. Can you please describe the extension lifecycle - for example when will init() be called?
4. When will the `FreshRSS_Context::$user_conf` be populated?

The reason for all my questions relates to my first try: [FreshRSS youtube extension](https://github.com/kevinpapst/freshrss-youtube) 

If I use a "system" extension, I am not able to read user settings from `init()`, the class FreshRSS_Context is not even loaded at that time. 
When I switch to a "user" extension, I can access the `$user_conf` in `init()` but the hook `entry_before_display` is not executed.

I feel really confused, because you do exactly the same in [ImageProxy](https://github.com/FreshRSS/Extensions/blob/master/xExtension-ImageProxy/extension.php#L8) which is a "system" extension as well.

**Comment by Alkarex** [comment]
Hello @kevinpapst 
Yes, a number of improvement would be desirable.
1. I have not looked much at that part of the code
2. A user extension can be enabled by some users and not by others. Typically for user preferences. A system extension is enabled for every account. It looks like you might have found some bugs (I believe `entry_before_display` should be executed in both cases).
3. and 4. The loading can be seen in https://github.com/FreshRSS/FreshRSS/blob/master/app/FreshRSS.php#L22

Thanks for your work so far :-)

**Comment by kevinpapst** [comment]
I am working on a translation of the [french extension docu](https://github.com/FreshRSS/documentation/blob/master/fr/docs/developers/03_Backend/05_Extensions.md) with the help of google translate ;-) so I will have to dive a little deeper into the system and do some more testing. As you said, I might file a bug or two, as it felt somehow wrong - thats why I raised all these questions.
Thanks for your feedback, I will come back in a couple of days.

**Comment by Alkarex** [comment]
Excellent, thanks !
