### ISSUE TITLE
Update version

### ISSUE THREAD

**Issue by TiCaillou** [FreshRSS/FreshRSS#1387]
I updated automatilly but after I have a message
```
### Application problem ###
See logs files
```
I see files logs and this message
```
[Fri, 02 Dec 2016 15:20:44 +0100] [error] --- Access to database is denied for `user_db` (`mysql:host=hostname_db;dbname=user_db;charset=utf8mb4`)
```
but if I connect on phpmyadmin with user_db and hostname_db it's OK. Why I have this message.

**Comment by Alkarex** [comment]
Hello,
Most likely due to your MySQL server not supporting utf8mb4.
I will give you better links later.
Are you hosted at OVH?
In the meantime, try to search in our recent solved issues for similar
problems.

**Comment by TiCaillou** [comment]
yes i'am hosted at OVH. Thank you ! I'am search.

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/issues/1369

**Comment by TiCaillou** [comment]
OK it's work ! Thank you
