### ISSUE TITLE
Multiuser RSS feeds

### ISSUE THREAD

**Issue by Mayson74** [FreshRSS/FreshRSS#1390]
G'day I must say this is a fantastic application but I have an issue where I have added new users and created new feeds within. When I run the rss feed icon I see the source feed correctly, but when I place it in my reader I get a HTTP ERROR 500 but if I use my admin account and place the rss feed in my reader it works perfectly. Is there a id in the url required for the new users so they will work as the admin urls do.

Cheers guys

**Comment by Mayson74** [comment]
I have activated the authentication token option and its working for the default user, but I get 
Error 403 - Forbidden

You don’t have permission to access this page

if I want to use tokens on additional users are we able to do this to access the rss feed url's for those other users?
example of new user url
http://g2rss.mypressonline.com/p/i/?a=rss&get=c_3&token=delaware&hours=168

**Comment by Alkarex** [comment]
Hello @Mayson74 
The token indeed needs to be improved for multi-user situations. Related issue (in French) https://github.com/FreshRSS/FreshRSS/issues/366 
I have increased its priority, to address it in the next version 1.7.0

**Comment by Alkarex** [comment]
Implemented in https://github.com/FreshRSS/FreshRSS/pull/1493
Tests welcome
