### ISSUE TITLE
[FR] Fatal error après mise à jour vers 1.5

### ISSUE THREAD

**Issue by gouglov** [FreshRSS/FreshRSS#1391]
Bonjour à tous,

Hier soir, j'ai vu qu'il y avait la mise à jour 1.5 de FreshRSS, je l'ai donc lancé.
Après un temps, le processus semble avoir complètement planté puisque maintenant, à la place de la page de login, j'ai une fatal error.

J'ai regardé les logs (qui n'était pas à l'endroit indiqué par le readme, mais de ./data/users/MonUser/log), il semblerait que ce soit du à un problème d'accès à la BDD.

J'ai cependant vérifié ces accès (vérifié l'url, le mdp, le user, la bdd, changer le mdp des deux cotés), rien y fait, je suis continuellement en erreur.

Une idée de comment restauré l'instance ?

Si c'est impossible, comment puis-je obtenir un backup de mes flux (en sachant que j'ai plusieurs utilisateurs de l'instance).

Merci d'avance.

Alexis K

**Comment by Alkarex** [comment]
Si vous utilisez MySQL et êtes hébergés chez OVH, voir dans les tickets
résolus récents un problème similaire.

**Comment by gouglov** [comment]
OK Merci, je vais jetez un oeil.

**Comment by gouglov** [comment]
C'est bon, ça marche. Je ferme.

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/issues/1369
