### ISSUE TITLE
Option to block non-https medias

### ISSUE THREAD

**Issue by NerosTie** [FreshRSS/FreshRSS#1392]
My website is now under HTTPS but some of my feeds use only HTTP for their medias and I don't think is good thing for security and/or privacy. In some cases, even if the RSS feed use HTTPS, the medias can only use HTTP, so it's hard to know before I add them.

**Comment by Alkarex** [comment]
Hello,
* Maybe the image proxy extension can help https://github.com/FreshRSS/Extensions/tree/master/xExtension-ImageProxy
* In the case of Web sites having both HTTP and HTTPS, you can also add them to a `/data/force-https.txt` file. See default file https://github.com/FreshRSS/FreshRSS/blob/master/data/force-https.default.txt

**Comment by NerosTie** [comment]
Tumblr is exactly the one I have an issue with. Even with force-https.default.txt and even with HTTPS Everywhere!

This feed in particular: https://kuvshinov-ilya.tumblr.com/rss

I'll take a look at ImageProxy if it's a good solution or not.

**Comment by Alkarex** [comment]
Your example seems to work fine for me (without proxy, and without HTTPS Everywhere):
![image](https://cloud.githubusercontent.com/assets/1008324/21466753/3c3c38a4-c9d5-11e6-959b-9ddea4f37630.png)
Could you try in a browser without extension?
Which version of FreshRSS are you running?

**Comment by NerosTie** [comment]
This is what I have:

![spectacle x17233](https://cloud.githubusercontent.com/assets/4572452/21789130/02b8a314-d6d3-11e6-8943-100185cd9b9a.png)

It's just an example but it shows that FresshRSS can load a non-https image. And I think it should be blocked by default or embedded in something you need to click to load it.

**Comment by Alkarex** [comment]
Hello,
A "307 Internal Redirect" (fake redirect) is not a request to an external server. It is an internal Chrome behaviour https://plus.google.com/+JohnMueller/posts/E4PqAhRJB2V
Could you please try in a browser without extension (without HTTP Everywhere in particular) and show me the HTML source code with the link to the problematic Tumblr image?

**Comment by math-GH** [comment]
Is it still an actual feature request?

**Comment by NerosTie** [comment]
As the author of the request, I would say no. So feel free de close it or not.

**Comment by Alkarex** [comment]
For the record, we have a list to force HTTPS (for images, videos, iframes…) defined in `./force-https.default.txt` and `./data/force-https.txt`

https://github.com/FreshRSS/FreshRSS/issues/1083
