### ISSUE TITLE
Upgrade check

### ISSUE THREAD

**Issue by azlux** [FreshRSS/FreshRSS#1393]
Hi,
I'm using php7 and the upgrade process crash because of the line 198  
```php
 FreshRSS_Context::$sinceHours = intval(Minz_Request::param('hours', 0));
```
Into php7 there are some changes who a indirect variables is handle : [doc here](https://secure.php.net/manual/en/migration70.incompatible.php#migration70.incompatible.variable-handling.indirect)

The main problem here is that the upgrade process look like well done, after this 500 error, freshrss say he is upgraded. So I suppose there are no check/rollback if the upgrade failed. no ?

**Comment by Alkarex** [comment]
Hello @azlux 
FreshRSS works fine with PHP7. Could you please give the error message, if you have it?
From which to which version are you updating?

**Comment by azlux** [comment]
Sorry but I haven't the version I had before the upgrade.
```
2016/12/20 18:41:04 [error] 22808#0: *28958 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Access to undeclared static property: FreshRSS_Context::$sinceHours in /home/azlux/freshrss/app/Controllers/indexController.php:198
Stack trace:
#0 /home/dmichel/freshrss/app/Controllers/indexController.php(30): FreshRSS_index_Controller->updateContext()
#1 /home/azlux/freshrss/lib/Minz/Dispatcher.php(119): FreshRSS_index_Controller->normalAction()
#2 /home/azlux/freshrss/lib/Minz/Dispatcher.php(48): Minz_Dispatcher->launchAction('normalAction')
#3 /home/azlux/freshrss/lib/Minz/FrontController.php(84): Minz_Dispatcher->run()
#4 /home/azlux/freshrss/p/i/index.php(46): Minz_FrontController->run()
#5 {main}
  thrown in /home/azlux/freshrss/app/Controllers/indexController.php on line 198" while reading response header from upstream, client: 37.18.163.7, server: _, request: "GET /rss/i/ HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "azlux.fr.nf"
```

**Comment by Alkarex** [comment]
Hum, it could be that not all the files have been updated to the new version.
Could you please check that you have the same local version than https://github.com/FreshRSS/FreshRSS/blob/master/app/Models/Context.php#L38

**Comment by azlux** [comment]
This file is the same as mine.
no differences

**Comment by Alkarex** [comment]
Strange. I would suggest you try to re-upload the PHP files

**Comment by azlux** [comment]
Yes I've make a full reinstall. It's ok.
But I think the upgrade method need to be allow to make a rollback in case of failure.

**Comment by Alkarex** [comment]
Ok :-) All good then?
In case of problem, simply uploading the files of the previous version should work.

**Comment by azlux** [comment]
yes all good, it's was just a recommendation for next improvement of the upgrade function.
