### ISSUE TITLE
No Wallabag v2 sharing on 1.6.1

### ISSUE THREAD

**Issue by KillianKemps** [FreshRSS/FreshRSS#1396]
Hello,

I just installed the latest FreshRSS 1.6.1 on my own server with Docker.
I saw in issues #1175 and #1162 that there is a Wallabag v2 support since 1.3.3-dev.

However, looking at the sharing options available I see `wallabag v1`, but no `wallabag v2`.
I still tried the v1 if it worked but of course, it didn't manage to share the article to my Wallabag instance.

Is the wallabag v2 sharing option disabled by default? Or is there a bug?

**Comment by Alkarex** [comment]
Hello @KillianKemps 
Please check that your `data/shares.php` is the same as https://github.com/FreshRSS/FreshRSS/blob/master/data/shares.php#L41

**Comment by KillianKemps** [comment]
Hello, I entered the FreshRSS Docker container and it seems that `/var/www/html/data/shares.php` is quite old as you can see below (a `ls -l` shows last modification of file in September 2015)

```
return array(                                                                                                                                                        
        'shaarli' => array(
                'url' => '~URL~?post=~LINK~&amp;title=~TITLE~&amp;source=FreshRSS',
                'transform' => array('rawurlencode'),
                'help' => 'http://sebsauvage.net/wiki/doku.php?id=php:shaarli',
                'form' => 'advanced',
        ),
        'blogotext' => array(
                'url' => '~URL~/admin/links.php?url=~LINK~',
                'transform' => array(),
                'help' => 'http://lehollandaisvolant.net/blogotext/fr/',
                'form' => 'advanced',
        ),
        'wallabag' => array(
                'url' => '~URL~?action=add&amp;url=~LINK~',
                'transform' => array(
                        'link' => array('base64_encode'),
                        'title' => array(),
                ),
                'help' => 'http://www.wallabag.org/',
                'form' => 'advanced',
        ),
        'diaspora' => array(
                'url' => '~URL~/bookmarklet?url=~LINK~&amp;title=~TITLE~',
                'transform' => array('rawurlencode'),
                'help' => 'https://diasporafoundation.org/',
                'form' => 'advanced',
        ),
        'twitter' => array(
                'url' => 'https://twitter.com/share?url=~LINK~&amp;text=~TITLE~',
                'transform' => array('rawurlencode'),
                'form' => 'simple',
        ),
        'g+' => array(
                'url' => 'https://plus.google.com/share?url=~LINK~',
                'transform' => array('rawurlencode'),
                'form' => 'simple',
        ),
        'facebook' => array(
                'url' => 'https://www.facebook.com/sharer.php?u=~LINK~&amp;t=~TITLE~',
                'transform' => array('rawurlencode'),
                'form' => 'simple',
        ),
        'email' => array(
                'url' => 'mailto:?subject=~TITLE~&amp;body=~LINK~',
                'transform' => array('rawurlencode'),
                'form' => 'simple',
        ),
        'print' => array(
                'url' => '#',
                'transform' => array(),
                'form' => 'simple',
        ),
);
```

One explanation may be that I first used the `kokaz/freshrss:latest` Docker image which was something like version 1.1 when I used it. I have then [opened a PR](https://github.com/kokaz/docker-freshrss/pull/2) to update this Docker image to 1.6.1 and pulled it again under a new tag name `kokaz/freshrss:master`.

However, I checked other files like `CHANGELOG.md` and they are up-to-date. 

My assumption is that this issue is not due to FreshRSS, but to the Docker build of `kokaz/freshrss`. The reason is that when I check `data/shares.php` (and not `/var/www/html`), this time the file is up-to-date.

So, I will check with `kokaz/freshrss`, sorry for the inconvenience!

By the way, it would be nice to have an official and up-to-date Docker image for FreshRSS :)

**Comment by Alkarex** [comment]
Yes. I have not myself looked at the Docker images, so I am not sure of the status, but see
* https://github.com/FreshRSS/docker-freshrss-production
* https://github.com/FreshRSS/docker-freshrss
