### ISSUE TITLE
Getting "Communication Error" when trying to login

### ISSUE THREAD

**Issue by ekianjo** [FreshRSS/FreshRSS#1401]
I have followed all the instructions for the install in the english docs and the pre-install check marked everything in green. The database setup was also successful - but when it comes to login I get "communication error" when I try to log in. No other hint as to what may be wrong - any idea what can cause this issue?

**Comment by Alkarex** [comment]
Hello,
Are you using MySQL? Might be a version problem (lack of support for
utf8mb4). In particular, if you are hosted at OVH, see a solution in the
recent issues

**Comment by Alkarex** [comment]
Closing issue, but feel free to ask again if needed.
