### ISSUE TITLE
Damn! Cannot find the PHP fileinfo library (fileinfo package).

### ISSUE THREAD

**Issue by FordDoctor** [FreshRSS/FreshRSS#1402]
While running the installation, Step 1 I get his error in the list of checks:

**Damn! Cannot find the PHP fileinfo library (fileinfo package).**

Could someone shed some light on what this means and how to correct the issue? Thanx!  :)

**Comment by Alkarex** [comment]
Hello @FordDoctor
See http://php.net/fileinfo
fileinfo is normally included and active in PHP. Not on all platforms though. See for instance the discussion for Synology https://github.com/FreshRSS/FreshRSS/issues/1370
What platform are you using?

**Comment by FordDoctor** [comment]
Apache Version 	2.4.23
PHP Version 	        5.6.29

Is this something I need to ask my hosting co to enable?

**Comment by FordDoctor** [comment]
I have to contact them about something unrelated anyway but to be sure, would phpinfo list this? I looked and did not find it. And no, this is my first attempt to install FreshRSS on my live hosted server. I ran an installation on my home development environment and it worked fine.  

What exact should I ask them for?

**Comment by FordDoctor** [comment]
fileinfo NOK finfo_open NOK finfo_file NOK 

And on my local installation the small icons do work. Version shown in the changelog file is 2016-12-26 FreshRSS 1.6.2

**Comment by Alkarex** [comment]
Hello,
Could you please test this patch? https://github.com/FreshRSS/FreshRSS/pull/1491
Thanks!

**Comment by Alkarex** [comment]
P.S.: It is now in the /dev version, so it would be even better to test https://github.com/FreshRSS/FreshRSS/tree/dev :-)
