### ISSUE TITLE
Tmp folder

### ISSUE THREAD

**Issue by jlelse** [FreshRSS/FreshRSS#1403]
FreshRSS tries to use the System tmp folder ([constants.php](https://github.com/FreshRSS/FreshRSS/blob/master/constants.php)). But this doesn't work for example on VestaCP.
I manually had to change the tmp folder on my installation to the one provided by VestaCP. Is there an PHP option, that finds the allowed tmp-Folders?

**Comment by Alkarex** [comment]
Hello @jlelse 
Did you try to set the value in php.ini?
http://php.net/manual/function.sys-get-temp-dir.php#115199

**Comment by jlelse** [comment]
@Alkarex Oh ok, didn't knew there's this option. But when I have multiple VestaCP users, there might come trouble. So is it possible to add an option in FreshRSS for configuring this path?

**Comment by Alkarex** [comment]
That is the role of constants.php, which you can edit.

**Comment by Alkarex** [comment]
BTW, you can also have a setup with multiple php.ini

**Comment by jlelse** [comment]
Ok thanks!
