### ISSUE TITLE
A bit of help with Docker?

### ISSUE THREAD

**Issue by romu70** [FreshRSS/FreshRSS#1405]
Hello,
I'm trying to setup a Docker image for Fresh-RSS, and I need a bit of help. I followed the instructions given here to write my Dockerfile. But I changed some things to get my Fresh-RSS instance available at the root at the web server. Obviously, I did something wrong because all I get is a 404.

My container is based on a Ubuntu 16.04 image I run for several other containers without any issue.

Any help would be great, the file is not long. It's here: https://github.com/romu70/self-hosting-containers/blob/master/fresh-rss/Dockerfile

Thanks.

**Comment by Alkarex** [comment]
Hello,
It seems to be just a path problem
https://github.com/romu70/self-hosting-containers/blob/master/fresh-rss/conf/fresh-rss#L4

**Comment by romu70** [comment]
Thanks @Alkarex. In the meantime, I did some additionnal testing with the files of the freshrss documentation. I may come back soon with some others questions if I don't manage to get it work.

**Comment by romu70** [comment]
I'm back.
I took the nginx settings file given in the Fresh-RSS documentation. And modified a bit my Dockerfile to put Fresh-RSS in /var/www.

And I can't get anything. I always get the message: ```No input file specified.``` When I check the error log, I see this message: ```"Unable to open primary script: /var/www/pindex.php```. Obviously, a slash is missing here, but I can't figure out what I can do to fix this. I tried to add a trailing slash to the root document variable in the nginx settings file, no change.

Any idea?

**Comment by romu70** [comment]
I'm back.
I took the nginx settings file given in the Fresh-RSS documentation. And modified a bit my Dockerfile to put Fresh-RSS in /var/www.

And I can't get anything. I always get the message: ```No input file specified.``` When I check the error log, I see this message: ```"Unable to open primary script: /var/www/pindex.php```. Obviously, a slash is missing here, but I can't figure out what I can do to fix this. I tried to add a trailing slash to the root document variable in the nginx settings file, no change.

Any idea?

**Comment by romu70** [comment]
I finally managed to get a working Docker container with Fresh-RSS. I stopped dealing with the "p" folder and just put the files in the /var/www and it works. Thanks @Alkarex for the help and everybody is welcome to use my docker container.

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/issues/1579#issuecomment-308304843
