### ISSUE TITLE
Make API fever compatible

### ISSUE THREAD

**Issue by rogierlommers** [FreshRSS/FreshRSS#1406]
Lot's of clients (f.e. Reeder) have Fever support. Fever is an old RSS aggregator which is also self-hosted. It would be great if you guys made the API `fever-compatible`, so we can point or Reeder apps, running on our mobile phones, to FreshRSS.

**Comment by aledeg** [comment]
Do you have a link to the fever api documentation?

**Comment by rogierlommers** [comment]
Unfortunately not, but there is a ttrss plugin which does the same: https://github.com/dasmurphy/tinytinyrss-fever-plugin

**Comment by Alwaysin** [comment]
Looks like it is here : http://www.feedafever.com/api

**Comment by Alkarex** [comment]
Hello,
Would you have examples of good clients supporting this API?
Thanks :-)

**Comment by rogierlommers** [comment]
Well, on iOS it's the Reeder app and Mr. Reader
- http://reederapp.com/ios/
- http://www.curioustimes.de/mrreader/

Top 2 from iOS RSS clients IMHO,

**Comment by Alkarex** [comment]
Ok. Thanks for the feedback

**Comment by Alkarex** [comment]
Related: https://github.com/FreshRSS/FreshRSS/issues/328

**Comment by RowanKaag** [comment]
+1. Grew to not wanting to use Feedly anymore and "Fever" is the only free option to use as sync engine for Reeder app (iOS/macOS)

**Comment by Alkarex** [comment]
If any of you have other examples of Fever clients, please list them here, in particular for Linux, Android, Windows, so I could test myself :-)

**Comment by Alkarex** [comment]
* https://play.google.com/store/apps/details?id=net.phfactor.meltdown
* https://play.google.com/store/apps/details?id=com.carlesgm.calenture

**Comment by cutzenfriend** [comment]
+ 1 for this! Would be awesome! :) 👍

**Comment by sgtcoder** [comment]
This would be awesome too! But, Fever and Press were both abandoned! But, I still have the Press app, so if we could get Fever API integration, I can at least migrate over to FreshRSS and use something that has support.

**Comment by alfureu** [comment]
FreshRSS would be great on mobile. Using the web version in a browser on a mobile device is not ideal.

**Comment by Alkarex** [comment]
@DOFfactory On which platform, in your case? There is already a couple of Android apps.

**Comment by Frenzie** [comment]
Incidentally, the only real reason I use EasyRSS is because it offers a certain degree of (not entirely perfect but generally good enough) offline functionality. Is there anything else about the web version that's "not ideal"?

**Comment by alfureu** [comment]
IMHO the "industry standard" should be the simplicity and functionality of Press, mentioned above. The best reader, no wonder many of us are begging for the Fever implementation, that is the only self-hosted solution with Press. 

I tried to use the web version of FreshRSS on my phone - it is very hard to use, almost impossible, no keyboards shortcuts, really not intuitive. We need an app, and it should be something very close functionality-wise and design-wise to Press.

**Comment by Alkarex** [comment]
Could you share a link to Press?

**Comment by alfureu** [comment]
It is not developed anymore, but luckily it was not removed from our devices (yet). There are some reviews available still, [here](https://lifehacker.com/5971651/press-for-android-is-a-gorgeous-newsreader-for-phones-and-tablets) with a video. It is very close to the iOS Reeder app. You can find it on GooglePlay [here](https://play.google.com/store/apps/details?id=com.twentyfivesquares.press). It's original webpage is not online anymore, [Twitter](https://twitter.com/25squares?lang=en) is rather inactive.

**Comment by sgtcoder** [comment]
I entirely 100 percent agree with @doffactory on everything.

Although @alkarex, thank you for News+ app, it does work and the widget are nice (and a great solution for the time being until we get something really nice). The only issue is the app doesn't get updates so there are scroll issues in Android 7, the UI needs to be refreshed, and it is somewhat bulky needing the app and extra plugins for everything to work. And since it was designed for Android 4, it is missing all the new style design concepts Android now uses.

News+ also has issues with forward slashes in their parameters and that requires a bit of extra complex configuration in the cPanel templates. Press never had issues with anything and was much more intuitive. I really loved Reeder 2 on iOS as well.

Either way, thank you for letting me know about News+ and it does help greatly for the time being. It won't be long before Google updates their Play policy which would require a few responses from the developer, if Google hear's no response, they remove the application. A simple new question not answered removed apps before.

**Comment by Frenzie** [comment]
Sure, that looks like a slightly more polished alternative to EasyRSS. For me personally some abandoned API doesn't sound that interesting but have at it. ;-)

**Comment by sgtcoder** [comment]
@Frenzie was that comment for me?

**Comment by Frenzie** [comment]
It's for anyone but in direct response to the last two messages. My bad though, by "that" I meant "Press" (based on the video).

**Comment by sgtcoder** [comment]
@frenzie well true, but it supported Fever and Google and I think Feedly as well. But, the concept of the app is what we are looking for. News+ is good for now, but Press still topped all the RSS readers for Android. So we aren't asking that we need Fever API support (not a demand), that was more of a possible workaround to use this RSS API with Press (the best Android RSS reader), but an app like Press that works with this API that is still supported.

**Comment by alfureu** [comment]
News+ is not good for me as it does not have an option to ignore SSL certificates. I am still searching for an app...

**Comment by Crupuk** [comment]
@DOFfactory  why don't you use a Let's Encrypt certificate ? ( https://certbot.eff.org/ )

**Comment by helmut72** [comment]
Please add Fever API. It is used on some really good Reader Apps on iOS and macOS (Reeder, Unread, ReadKit, Fiery Feeds). Thank you!

**Comment by alfureu** [comment]
Any update on this request, maybe in the next version?

**Comment by rogierlommers** [comment]
Did you guys checkout Miniflux? It's available as a docker container and has feever support out of the box.

**Comment by alfureu** [comment]
I want to use FreshRSS for other reasons. Mostly desktop. However, on phone fever API would be welcome for app compatibility. I was never successful with using the actual TT-RSS or greader API

**Comment by ices-dev** [comment]
I would love to see Fever Support, too. This would be big news for iOS an Mac users!

**Comment by MaluNoPeleke** [comment]
You could give FeedMe a try: https://play.google.com/store/apps/details?id=com.seazon.feedme
The beta version just got support for FreshRSS

**Comment by Alkarex** [comment]
The FeedMe pull request #1774 is not yet merged in FreshRSS /dev but I will
do so tonight 😊

**Comment by helmut72** [comment]
Nice to have FeedMe integration for Android users. The subject ask for Fever API. Any news on Fever API?

**Comment by kevinpapst** [comment]
I am working on a Fever API for FreshRSS and it’s ready-to-test, so I published a first version at:
https://github.com/kevinpapst/freshrss-fever-api

It was tested with the iOS Apps „Unread“ and „Fiery Feeds“ and the basic features worked for me.

But now I need your help: 
- iOS users please test and leave feedback
- Devs please check the code, there are many possible (performance) improvements 

The state is „work-in-progress“ and I will post again, once I consider it stable for a first release

**Comment by sgtcoder** [comment]
@kevinpapst this is incredible. I am a developer and a user of RSS feeds. I am a former iOS user and I have an iPhone still. I can probably take a look at it on iOS, but I will be mostly testing on Android and I will let you know where the API stands for Android. Unfortunately, most of the best apps for Android have gone away that have the Fever API support for Android.

Does anyone have the Press APK for Android?

Found it: http://www.apkhere.com/app/com.twentyfivesquares.press

I did it through PostMan setting api_key and it logs in, and I set feeds it grabs all the feeds. It's so cool. So I am going to look into why Press is not authenticating, I think it's because the variable name is different, so I will figure that out.

**Comment by sgtcoder** [comment]
@kevinpapst So I did all this work trying to figure out the authentication issue for Press (even packet capturing), then I was going to go over the Fever API, and I saw where it says about the user:pass md5. Then I saw you mentioned it and now I get it. So for greader if we change the password we would have to type in user:pass for the api password. Now I get it.

I was able to login, but I don't think Press is syncing, so if I find some time I will see what the issue is if I can. Kind of hard without the source code.

I think I am going to make calls to the old Fever API and compare results.

**Comment by alfureu** [comment]
Hi guys, very happy for the development in implementing fever API. Tried it with my server, following the instructions, and Press app on android. Unfortunately, although the hash is correct, I cannot log in (Invalid username/password error).

**Comment by sgtcoder** [comment]
@DOFfactory I was able to login.

Set your API password in your FreshRSS to the md5 value of user:pass. Then type your username and password in the Press app. It's your username, not your email.

It does not sync though after login. I think it's an issue with Press though since it hasn't been updated in years.

**Comment by alfureu** [comment]
@codermjb Yes, I did. However, I just played with it a bit, and I would like to warn everybody that the FreshRSS API Password should be all **lowercase**. If it is not lowercase, you cannot log in. I was successful in logging in now. Checking the syncing issue ...

**Comment by sgtcoder** [comment]
@doffactory nice job! Is yours syncing? Mine isn't.

**Comment by alfureu** [comment]
@codermjb Yup, seems there is a continuous try to access the server, no syncing tho ... 😞

**Comment by fearlesschicken** [comment]
Just tested this on Reeder on IOS and had some trouble with password until the suggestion for lowercase from @DOFfactory

Reading one item at a time will sync to the server, using the "Mark all as read" does not work
Starred items work

Edit: should've read the README for features and roadmap :)

**Comment by kevinpapst** [comment]
I have no android device available and can't test it, so for all of you where its not syncing:
please test it with Postman or a similar app.

You need to configure a POST request to the URL http://your-freshrss-url/api/fever.php?api with the body encoded as "form-data" and a key "api_key" with the value "your-password-hash".

Now test the following links (still with the POST and your api_key):
- http://your-freshrss-url/api/fever.php?api&items
- http://your-freshrss-url/api/fever.php?api&feeds
- http://your-freshrss-url/api/fever.php?api&groups

If it doesn't work please check your error logs (webserver/php) and sent me the exception logs.
And please note: I only tested it with PHP 7.1 and with an installation that has roughly 4000 entries, 30 feeds and 60 unread articles, don't know what happens on really old installations with a large database. 
For each call the fever API returns max 50 items but the clients can fetch older articles as well by using other request parameters - see the link https://feedafever.com/api for more infos) probably Press uses that extensively and you just have to wait longer?

Either way, I extended the documentation with debugging/testing infos:  https://github.com/kevinpapst/freshrss-fever-api

**Comment by sgtcoder** [comment]
@kevinpapst already tested it in Postman and it works. That doesn't guarantee the app works with the API though. Many of these apps are obsolete and hasn't been supported in years.

We just need to get the source code to the apps so we can fix them.

**Comment by kevinpapst** [comment]
@codermjb Debugging help would be awesome. But there is no need for packet capturing, simply add this line of PHP to the start of the fever.api file:
```
file_put_contents('/tmp/fever.log', json_encode($_REQUEST), FILE_APPEND);
```
Then perform a refresh in Press and sent me the contents of /tmp/fever.log (replace your password hash before posting).

**Comment by alfureu** [comment]
Did not have yet the time to test and check the logs, but I just noticed that the extension is built on tt-rss extension. When I was playing with tt-rss a while ago, I had to commit [this edit](https://github.com/dasmurphy/tinytinyrss-fever-plugin/pull/25/commits/0b1475d938bdc5f11b255be2156e1451ca240088) to make the articles load into my apps. Maybe this does apply to this extension too?

**Comment by kevinpapst** [comment]
@DOFfactory it was inspired by it, but does not use any of  its logic as FreshRSS is built completely different

For all the Android-Press users, please come over to https://github.com/kevinpapst/freshrss-fever-api/issues/1 and share your insights. I posted a test version that supports the press client (which seems to be quite buggy, so I am not sure that it will get full support).

I also added "marking feeds & categories as read" and did some performance improvements for all clients.

**Comment by alfureu** [comment]
Hi @kevinpapst, just testing this, but I do not see any articles to be downloaded. The links got updated and I am successful in logging in.

**Comment by Alkarex** [comment]
Could you please post here a link to the apps supporting this API?

**Comment by Alkarex** [comment]
@kevinpapst Excellent initiative, which looks promising already. Could you consider making a pull request, so we can more easily comment on the code, and make changes?

In particular, I would like to try to reduce the use of custom SQL, and instead use more of the existing methods (which can be tuned if necessary).

**Comment by sgtcoder** [comment]
@kevinpapst @Alkarex in that case, why don't we have the API password auto generate the Fever API password too. Meaning whenever we type a API password in, it takes the user:api_pass and generates the API password key and value for Fever. That way we can save both API passwords and only need one API password. We could also get all the user information in the database table too.

Also, if Tiny RSS ever had a better widget for Android, I might just work on a TinyRSS plugin for FreshRSS. They seem to still have support going on for their self host option and application, but they definitely need better UI and UX.

I have just picked up a lot more work so I have been busy, but I would love to help.

@Alkarex let me know what I can do with the user data. Right now we are saving them in files and I personally prefer that in a database table. I am a MySQL junkie. But I definitely think we need to get the API password to generate the Fever password as well, which I know what would be ideal for that.

I am all about automation and making things easy for users.

**Comment by Alkarex** [comment]
@codermjb Thank you for your offer to help. We have a nice backlog with many different types of issues, so if not on Fever itself, I am confident you can pick an issue for your taste :-)
See in https://github.com/FreshRSS/FreshRSS/pull/1836 where we are trying to find a solution for the Fever MD5 problem. Regarding user data, I generally like the Unix approach of using files, for its higher interoperability, simplicity, and performance, except when there is a need to make complex SQL requests.

**Comment by Alkarex** [comment]
Fever API has been implemented in https://github.com/FreshRSS/FreshRSS/pull/1836 and available in the /dev branch of FreshRSS. We are looking for testers, so do not hesitate to go ahead and report your experience.

**Comment by isaiasmatewos** [comment]
Hi Guys,

I am the developer of Readably, a modern RSS app for Android, recently it has been updated with Fever API support, I thought might want to check it out. Heres a link:

https://play.google.com/store/apps/details?id=com.isaiasmatewos.readably

Thanks, Isaias

**Comment by sgtcoder** [comment]
This is awesome! Thank you. I will take a look at it.

**Comment by Alkarex** [comment]
Hello @isaiasmatewos and thanks for reaching out. I will give it a try. Did you test with FreshRSS yet? (I can provide you a test account if needed). Let us know if you spot anything on FreshRSS side, which could be improved.
I can see you support Inoreader, which is using the Google Reader API, which FreshRSS supports as well. That API is a lot more powerful and efficient than Fever API. So you could consider using what you already have for Inoreader to talk to FreshRSS. I can provide assistance there as well.
When we have verified that your app is working fine, would that be OK to list Readably in our readme and documentation?

**Comment by isaiasmatewos** [comment]
Hi @Alkarex Thanks, I have tested it with a local installation of FreshRSS, it has worked fine as far as my knowledge. Let me know if you encounter any issues. 

I will consider interfacing with FreshRSS via the Google Reader in the future.

Yes you can definitely list Readably in your readme file.

Thanks

**Comment by sgtcoder** [comment]
That sounds great. Do you happen to know if you will include widgets for this?

**Comment by isaiasmatewos** [comment]
Yes @codermjb widgets are planned.

**Comment by Alkarex** [comment]
@isaiasmatewos https://github.com/FreshRSS/FreshRSS/pull/2264
