### ISSUE TITLE
Not notifying in reading view

### ISSUE THREAD

**Issue by welbert** [FreshRSS/FreshRSS#1407]
If I use 'normal view', I received the notification about news feeds but with the 'reading view' I do not get notification of new feeds.

Browser: Mozilla Firefox 50.1.0

**Comment by pattems** [comment]
@Alkarex I'm trying to track this one down. I've got a dummy test feed that issues a new article every minute, but that 20 minute cooldown between being able to fetch feeds makes it slow-going. Is there any way around this limit for debugging purposes?

**Comment by Alkarex** [comment]
The easiest to debug notifications is to have two windows of FreshRSS, and mark some articles as unread in one of them :-)
And you can even call `refreshUnreads();` manually from the JavaScript console.

**Comment by pattems** [comment]
okay, great! That's getting me somewhere. Thinking out loud: the new-article div was missing from reader view, but adding it isn't enough to trigger it. It triggers fine if I manually toggle the display property in css, so I'm thinking that it not triggering might be related to #545

**Comment by Alkarex** [comment]
Fixed by @pattems in https://github.com/FreshRSS/FreshRSS/pull/2188 and merged in /dev branch. Tests welcome before release of FreshRSS 1.13.0 in a couple of days.
