### ISSUE TITLE
News+ not fetching feeds

### ISSUE THREAD

**Issue by stormgrass** [FreshRSS/FreshRSS#1408]
I've recently started using FreshRSS and quite love it, but I'm having issues with getting it work with News+. While I can connect to my FreshRSS install, and it does pull the categories and the feednames, it simply doesn't pull any actual content (when pulling down to refresh a single feed, I can glimpse something that looks like a 404 error message being sent from my server).

I'd be happy if you could give me any pointers on what I might be doing wrong. For what it's worth, synchronizing with EasyRSS works flawlessly.

Thanks!

**Comment by Zayon** [comment]
Hi,

Take a look at your access log file, for example :
`tail -F /var/log/nginx/fressrss_access.log`
then pull down to fetch feeds on news+, you should see some calls on /api/greader.php

Check that the http code is 200.

You can trying fetching with EasyRSS to compare the logs.

**Comment by stormgrass** [comment]
Hi! I've looked into the logs. I get 200 codes for fetching the tags and the subscription lists, but for the actual content I get this:

`[16/Jan/2017:13:44:06 -0500] "GET /reader/api/greader.php/reader/api/0/stream/contents/user%2F-%2Fstate%2Fcom.google%2Freading-list?client=newsplus&ck=1484592248707&xt=user/-/state/com.google/read&n=1000&r=n HTTP/1.1" 404 577 "-" "gzip"`

**Comment by Alkarex** [comment]
Hello @stormgrass 
Please have a look at the tests in `http://rss.example.net/reader/api/`

**Comment by stormgrass** [comment]
Hi @Alkarex, I'm getting a pass on the one without 2%F support, and a not found on the other. So looking at my log output, newsplus uses 2%F? How do I turn on 2%F support on my server? I'd google it, but naturally, I'm getting no usable results.

**Comment by Alkarex** [comment]
What server do you use, @stormgrass ?

* http://httpd.apache.org/docs/trunk/mod/core.html#allowencodedslashes
* https://github.com/FreshRSS/FreshRSS/issues/443#issuecomment-36666133
* http://doc.freshrss.org/en/users/01_Installation/#nginx-installation

**Comment by stormgrass** [comment]
Thanks, @Alkarex!

I'm using Ubuntu 16.04, with apache2. 
I've set the necessary parameter in my default apache2 conf file and everything works as it should now, News+ is syncing. 

Thanks a lot for your help and your great work on FreshRSS!
