### ISSUE TITLE
Favicon not imported for Korben.info

### ISSUE THREAD

**Issue by Draky50110** [FreshRSS/FreshRSS#1415]
Hello.

I have an empty icon (no icon) for Korben.info website : https://korben.info/favicon-32x32.png

I'm using FreshRSS 1.6.1.

Any idea ?

Thanks.

**Comment by Alkarex** [comment]
Hello @Draky50110 ,
It works fine for me

![image](https://cloud.githubusercontent.com/assets/1008324/22349694/0f991cf8-e411-11e6-90ae-d11c41c6a12c.png)

In my syslogs, I got:

```
apache2: FreshRSS Favicon discovery GET https://korben.info/
apache2: FreshRSS Favicon GET https://korben.info/favicon.ico
```

I suggest you try again. You can also check in `./data/favicons/` the corresponding .txt and .ico. See in the .txt file if you have `https://korben.info/favicon.ico`

**Comment by Draky50110** [comment]
How do you know which tct is for this particular feed ?
They seem "hashed".

And I can"t remember how to clear all favicons to re-download them.

**Comment by Alkarex** [comment]
The easiest to find the address it to look at the URL of the problematic icon from the Web UI.
Otherwise, you can search for it:
```sh
grep -i Korben data/favicons/*.txt
```
You can clear all favicons by doing:
```sh
rm data/favicons/*.ico
```

**Comment by Draky50110** [comment]
Thanks for tip.

Problem still here :/

Host problem maybe.

**Comment by Alkarex** [comment]
Does a curl from your server works?

```sh
curl -vI https://korben.info/favicon.ico
```

**Comment by Draky50110** [comment]
Ok, I think I found the problem.

Here is the file it downloaded : https://gilles.wittezaele.fr/owncloud/index.php/s/aekwyC5qrsom7vd

White on white !

Not the same as the website favicon !
Link : https://korben.info/favicon.ico
But on main site it is black...

The good one : https://korben.info/favicon-32x32.png

Possible to add an option to add manually favicon on site feed config ?

**Comment by Alkarex** [comment]
Héhé. There is currently no option to do that, but you can manually replace the corresponding file in `./data/favicons/` and make it read-only so that it does not get updated.
