### ISSUE TITLE
Can't mark all articles from a category as "read"

### ISSUE THREAD

**Issue by Vincent14** [FreshRSS/FreshRSS#1421]
When I click on "Fin des articles / Tout marquer comme lu", nothing happen, I have to clic on the button on top of the feeds "Marquer comme lu"

**Comment by Alkarex** [comment]
I sounds like a JavaScript error problem. Could you please have a look at your browser console for any warning / error?
Which version of FreshRSS are you using?

**Comment by Vincent14** [comment]
I am using the     1.6.2 version. Here is the JS console:

> 14:21:16,546 Content Security Policy: La directive « frame-src » est obsolète. Veuillez utiliser la directive « child-src » à la place.  (source inconnue)
> 14:21:17,182 FreshRSS waiting for Sticky-kit…  main.js:509:4
> 14:21:17,226 FreshRSS init done.  main.js:1394:3
> 14:21:17,369 Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à self (« default-src http://rss.influence-pc.fr »).  i:1
> 14:21:17,388 Content Security Policy: Les paramètres de la page ont empêché le chargement d’une ressource à self (« default-src http://rss.influence-pc.fr »). i
> 14:21:21,470 Un iframe possédant à la fois allow-scripts et allow-same-origin pour son attribut sandbox peut se retirer du mode bac à sable (sandboxing).  WebRequest.jsm:217:11
> 14:21:22,677 Ce site semble utiliser un effet de positionnement lié au défilement. Cet effet pourrait ne pas fonctionner correctement avec le défilement asynchrone. Consultez https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects pour obtenir davantage de détails ou discuter des outils et des fonctionnalités liés.  i

**Comment by dknx01** [comment]
I've the same problem with V1.6.2. But on my site nothing is shown in the developer tools/console. I recognised that this happens mostly after it loads more articles via Ajax.

**Comment by Alkarex** [comment]
If you are willing to share a link with test account to your FreshRSS instance in private message (email on https://alexandre.alapetite.fr/cv/ ) I could have a look

**Comment by Alkarex** [comment]
Thanks for the account @dknx01 
Seems related to https://github.com/FreshRSS/FreshRSS/issues/1348

**Comment by Alkarex** [comment]
@dknx01 @Vincent14 Could you please try this patch? https://github.com/FreshRSS/FreshRSS/pull/1438

**Comment by Vincent14** [comment]
Problem solved! And so fast! Thank you so much!
