### ISSUE TITLE
Add GNU social share

### ISSUE THREAD

**Issue by gllmhyt** [FreshRSS/FreshRSS#1422]
Is it possible to add GNU Social to the shares available? Unfortunately, I'm not sure how the `transform` bit works.

```
'gnusocial' => array(
		'url' => '~URL~/notice/new?content=~TITLE~ ~LINK~',
		'transform' => array(
			'link' => array(),
			'title' => array(),
		),
		'help' => 'https://gnu.io/social/',
		'form' => 'advanced',
	),
```

The result, for instance, should be like `https://herds.eu/notice/new?content=%23FreshRSS+is+amazing%20https%3A%2F%2Ffreshrss.org`

Thank you. :)

**Comment by Alkarex** [comment]
Hello @postblue 
Could you try the following code?

```php
	'gnusocial' => array(
		'url' => '~URL~/notice/new?content=~TITLE~%20~LINK~',
		'transform' => array('urlencode'),
		'help' => 'https://gnu.io/social/',
		'form' => 'advanced',
	),
```

**Comment by gllmhyt** [comment]
It seems to work.

1. Is it normal it adds "· Site name" next to the "Article title" ?
2. Share name in the dropdown list is gen.share.gnusocial.

**Comment by Alkarex** [comment]
1. Yes, but that could be patched if it is a problem. The code doing it is https://github.com/FreshRSS/FreshRSS/blob/8a776f146182bc6870702cfeb87041e3af66b24b/app/views/helpers/index/normal/entry_bottom.phtml#L48

2. The proper name needs to be added for each language, e.g. for English https://github.com/FreshRSS/FreshRSS/blob/fcc9229fb772be6f99512021454e4a14760301a5/app/i18n/en/gen.php#L155

```php
'gnusocial' => 'GNU social',
```

Could you try to make a pull request on the /dev branch?

**Comment by gllmhyt** [comment]
Made it. :)

**Comment by Alkarex** [comment]
Implemented by @postblue in https://github.com/FreshRSS/FreshRSS/pull/1428
