### ISSUE TITLE
Support for protected config options

### ISSUE THREAD

**Issue by dswd** [FreshRSS/FreshRSS#1424]
I am packaging FreshRSS for Cloudron and ran into the issue that I want to have some settings protected (e.g. database, default user) so that users can't change them (and break the setup).
Currently, I overwrite the `config.php` on each start but that obviously overwrites all other settings and is not very nice.
It would be great if FreshRSS supported protected settings that can not be changed in the interface e.g. in a file like `config.protected.php`. Maybe you can take some code from Dokuwiki as they got a pretty good solution there.

**Comment by Alkarex** [comment]
Hello,
Currently, it is not possible to change the default user and database settings from the Web interface. So it sounds like it is already as you want, isn't it?

**Comment by dswd** [comment]
Oh yes, that was an oversight on my part. However, in Cloudron the database settings could change between app restarts (e.g. when restoring an app from a backup) so I still need a way to change those settings without overwriting all other settings.
Is there a central place in the code that loads the config file? Maybe I could just patch in an overwrite file.

**Comment by Alkarex** [comment]
I would suggest you look at the CLI (command-line interface) https://github.com/FreshRSS/FreshRSS/tree/dev/cli
It would be possible to add missing options there, if any

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/1439
