### ISSUE TITLE
search both the title and the name of the feed

### ISSUE THREAD

**Issue by sant527** [FreshRSS/FreshRSS#1425]
When i search i searches in the title. Is there any chance to also show the feeds whose title also contains that word

**Comment by Alkarex** [comment]
Hello,
I am not sure to understand the question. Do you want to search articles, or feeds?
Currently, when using the search field, it will search in the articles' title and content.
Could you maybe give an example?

**Comment by sant527** [comment]
Apart from the articles title and content is it possible to search the url also. Because I want to check some words were they present in the url

**Comment by Alkarex** [comment]
To search in URL, try this syntax: `inurl:something`
There is also `author:`, `intitle:`, `date:`, `tag:`

**Comment by sant527** [comment]
how can i find all the list of available search options.

I want to find multiple words in in different urls. Is there anything like OR AND

Like: inurl:video OR inurl:story (is not working) but only inurl:video is working

**Comment by Alkarex** [comment]
So far, they are only in the documentation, in the code, and in GitHub issues. A graphical user interface to help with the search functions is planned https://github.com/FreshRSS/FreshRSS/issues/1189
