### ISSUE TITLE
update only a specific group

### ISSUE THREAD

**Issue by sant527** [FreshRSS/FreshRSS#1427]
i have different groups. how to update a particular group

**Comment by Alkarex** [comment]
Hello,
I recommend to set an appropriate refresh frequency in the configuration of each feed. This way, when you refresh either by cron or from the Web interface, only the feeds that are old enough will be refreshed.
You can also manually refresh a single feed from the Web interface, but there is currently no feature to manually refresh only a given category.
I hope this helps.

**Comment by sant527** [comment]
ok
