### ISSUE TITLE
why my feeds are not date sorted  properly

### ISSUE THREAD

**Issue by sant527** [FreshRSS/FreshRSS#1430]
I found my feeds are not date sorted properly.

![screenshot_20170218_230932](https://cloud.githubusercontent.com/assets/6462531/23095474/2a8377ea-f602-11e6-82a8-cf48832eeae1.png)

**Comment by Alkarex** [comment]
Hello,
After a few refresh, the order should be more natural again.
Furthermore, the initial behaviour will get better when https://github.com/FreshRSS/FreshRSS/issues/530 is implemented.
Related: https://github.com/FreshRSS/FreshRSS/issues/1266 https://github.com/FreshRSS/FreshRSS/issues/1305

**Comment by Alkarex** [comment]
An implementation of the more natural order is available. Tests much welcome https://github.com/FreshRSS/FreshRSS/pull/1470
