### ISSUE TITLE
HTTP 403 error in anonymous mode

### ISSUE THREAD

**Issue by fsantiago07044** [FreshRSS/FreshRSS#1431]
What is this message that keeps appearing over my screen each time I expand an article to read?

"A request has failed, it may have been caused by Internet connection problems."

details of my system:

centos 7.3.1611
nginx 1.11.10
php 7.0.16 (w/ php-fpm)
mysql  Ver 15.1 Distrib 5.5.52-MariaDB
server also has redis running

the freshrss logs are empty/non-existent. 

most of the feeds i have subscribed to come from feedburner. 

my site is served via ssl. 

anything else i'm missing? Thanks.

- Fabian S.

**Comment by Alkarex** [comment]
Hello,
This is probably due to an Ajax request failing. When an article is open, a "mark as read" request is sent.
Please have a look at your Web browser console for JavaScript / Security (e.g. CSP) errors.
On the server side, please have a look at your nginx logs: if there is no request, then the HTTP request has not reached FreshRSS.

**Comment by fsantiago07044** [comment]
ok, I found the likely error:

GET https://news.garbage-juice.com/i/?c=error 403 (Forbidden)
(anonymous) @ VM40:2
send @ jquery.min.js?1487606715:4
ajax @ jquery.min.js?1487606715:4
mark_read @ main.js?1487606715:132
toggleContent @ main.js?1487606715:282
(anonymous) @ main.js?1487606715:716
dispatch @ jquery.min.js?1487606715:3
q.handle @ jquery.min.js?1487606715:3
trigger @ jquery.min.js?1487606715:4
(anonymous) @ jquery.min.js?1487606715:4
each @ jquery.min.js?1487606715:2
each @ jquery.min.js?1487606715:2
trigger @ jquery.min.js?1487606715:4
r.fn.(anonymous function) @ jquery.min.js?1487606715:4
(anonymous) @ main.js?1487606715:752
dispatch @ jquery.min.js?1487606715:3
q.handle @ jquery.min.js?1487606715:3

nginx access log shows the same error in the POST / GET request.

also, my freshrss is version 1.6.2.

i have followed the docs suggested nginx config as well.

thanks for your help but where to go from here?

- Fabian S.

**Comment by fsantiago07044** [comment]
here you are.

I'm also serving these feeds anonymously. not sure if error happens when
i'm logged in. testing that now. i don't believe it does. i've also turned
off my ublock origin just in case. errors continued when accessing
anonymously despite this. have seen weird errors on other sites with ublock
turned on, such as on various google product admin sites. thanks.

- Fabian S.

**Comment by Alkarex** [comment]
I do not think attachments work when you answer by e-mail. And if you use any extensions, please try with another browser just to be sure.

**Comment by fsantiago07044** [comment]
see attachments. no extensions enabled or even present. 
<img width="960" alt="console" src="https://cloud.githubusercontent.com/assets/8866211/23215347/0ba23e48-f8e0-11e6-9f18-063e52c29240.png">
<img width="960" alt="network" src="https://cloud.githubusercontent.com/assets/8866211/23215348/0ba74c9e-f8e0-11e6-9fbe-5b80dd17750e.png">

**Comment by Alkarex** [comment]
Ah OK. It seems to be a bug when using the anonymous mode. I have updated the title of the issue accordingly. Could you please confirm that it works fine when you are logged-in?

**Comment by fsantiago07044** [comment]
it does appear to do so. i cannot reproduce error while logged in.

**Comment by Alkarex** [comment]
I will try to fix the bug in anonymous mode.

**Comment by fsantiago07044** [comment]
kewl. thanks.

**Comment by Alkarex** [comment]
@fsantiago07044 In your case, should anonymous users be able to mark articles as read?

**Comment by fsantiago07044** [comment]
On February 25, 2017 4:16:45 AM EST, Alexandre Alapetite <notifications@github.com> wrote:
>@fsantiago07044 In your case, should anonymous users be able to mark
>articles as read?

Either no, or only for their session but no one else's, if that's possible. 
-- 
Thanks.
Fabian S.

**Comment by Alkarex** [comment]
@fsantiago07044 Should be fixed in https://github.com/FreshRSS/FreshRSS/pull/1451 (merged in /dev) Please give it a try

**Comment by fsantiago07044** [comment]
On March 4, 2017 5:27:19 AM EST, Alexandre Alapetite <notifications@github.com> wrote:
>@fsantiago07044 Should be fixed in
>https://github.com/FreshRSS/FreshRSS/pull/1451 (merged in /dev) Please
>give it a try

I'll keep testing but seems to be working just fine. I noticed the article last read stays "white" (in a state appearing to have been read) until you click the next article. Doesn't bother me but just making sure you expect that. Thanks.

Fabe

-- 
Thanks.
Fabian S.

**Comment by ghaisasadvait** [comment]
I have the same issue.
FreshRSS latest version running on Cloudron on top of Ubuntu Server 18
