### ISSUE TITLE
Feedurl is not escaped correctly

### ISSUE THREAD

**Issue by hrehfeld** [FreshRSS/FreshRSS#1434]
If a feed has a weird or relative url, it's not made absolute in the feed list > little settings icon > "see website" link. I could put "myevil/url/delete/feed" in my custom feed...

**Comment by Alkarex** [comment]
Thanks @hrehfeld 
Could you please try this patch https://github.com/FreshRSS/FreshRSS/pull/1441 ?

**Comment by Alkarex** [comment]
Merged in /dev. Feedback welcome.
