### ISSUE TITLE
cant add any feeds with https

### ISSUE THREAD

**Issue by pn86jvr** [FreshRSS/FreshRSS#1442]
Tried  https://www.ucg.org/api/beyond-today/audio-podcast
https://www.factorio.com/blog/rss
and a couple more.

it only gives me.......
2017-02-25 20:57:11
cURL error 60: SSL certificate problem: unable to get local issuer certificate [https://www.factorio.com/blog/rss]
2017-02-25 20:57:10
cURL error 60: SSL certificate problem: unable to get local issuer certificate [http://freshrss.org/feeds/all.atom.xml]

am I doing something wrong?

**Comment by Alkarex** [comment]
Hello,
Probably a problem with local root certificates on your server.
On Debian / Ubuntu, you can try something like:

```sh
sudo update-ca-certificates
```

In any case, try a manual curl:

```sh
curl -v https://www.ucg.org/api/beyond-today/audio-podcast
```

**Comment by pn86jvr** [comment]
Thank you
