### ISSUE TITLE
small issues when configuring FreshRSS from scratch with CLI

### ISSUE THREAD

**Issue by oupala** [FreshRSS/FreshRSS#1445]
There is some more issues when configuring FreshRSS from sratch with CLI.

1. I can't set the general language for FreshRSS at install time. As a consequence, login page is always in english where I'd like to set ot to another language.

2. I can't reuse the login used at install time to create a new user:

```bash
>sudo -u www-data ./cli/do-install.php --default_user myuser --api_enabled --db-type sqlite
FreshRSS install…
• Remember to create the default user: myuser
	./cli/create-user.php --user myuser --password 'password' --more-options
• Remember to re-apply the appropriate access rights, such as:
	sudo chown -R :www-data . && sudo chmod -R g+r . && sudo chmod -R g+w ./data/
Result: success
>sudo -u www-data ./cli/create-user.php --user myuser --password 'myuserpass' --api-password 'api_password' --language fr --email myuser@example.org --token 'longRandomString'
FreshRSS error: username already taken “myuser”
```

3. Importing an opml file generates some notices:

```bash
>sudo -u www-data ./cli/import-for-user.php --user myuser --filename /somewhere/feeds_backup.opml
FreshRSS importing ZIP/OPML/JSON for user “myuser”…
PHP Notice:  Undefined offset: 0 in /home/ops/apps/FreshRSS-cli-install-sqlite/lib/Favicon/Favicon.php on line 92
PHP Notice:  Undefined offset: 0 in /home/ops/apps/FreshRSS-cli-install-sqlite/lib/Favicon/Favicon.php on line 92
PHP Notice:  Undefined offset: 0 in /home/ops/apps/FreshRSS-cli-install-sqlite/lib/Favicon/Favicon.php on line 92
Result: success
```

4. There is some settings missing that we can configure on the web interface but not with CLI. Is it planned to add these settings in the futur? Is it planned to be able to set via the CLI all the settings that we can set from the web interface?

5. An ansible playbook idempotency is mainly based on files, is there a way to tell that FreshRSS is installed or not, that a user is created or not, that an opml file has been imported? It would be great to prevent ansible from trying to reinstall FreshRSS, to recreate the user, and to reimport the opml file...

**Comment by Alkarex** [comment]
1. I will check
2. Damn, this is a new SQLite bug introduced by https://github.com/FreshRSS/FreshRSS/issues/1443
3. I will check. The Favicon library has multiple issues
4. Yes there are some more advanced settings that cannot be set from the CLI, but some of them cannot be set from the Web interface either (e.g. the limits and curl options), only directly in the configuration file.
5. When FreshRSS is installed, the file `data/do-install.txt` does not exist. The list of existing users can be seen from the CLI.

**Comment by oupala** [comment]
Thanks for your answer. I'm close to a fully automated install of FreshRSS via ansible. I'll share the playbook once it works.

For point 4, is it planned to add the possibility of configuring some more parameters via the command line? However, if it's possible to do that via a configuration file, it might be ok. I can see that configuration file are php files with arrays, which are not easy to manipulate. It would have been easier to use **ini** files (which are easy to manipulate via php with [parse_ini_file](http://php.net/manual/fr/function.parse-ini-file.php)).

For point 5, it is great to have the `do-install.txt` file. It is also great that listing users can help to guess if a user has been created or not (and cherry on the cake, the user listing script is returning a good return code whether the user exists or not, great news !). But it would be greate to have the number of subscribed feeds when listing when using `user-info.php` so that if number of subscribed feeds is zero, it means that no feed have been imported yet.

**Comment by oupala** [comment]
6. When importing an opml file twice, the import fails (and this is normal), but the error is not well handled:

```bash
FreshRSS importing ZIP/OPML/JSON for user “myuser”…
PHP Fatal error:  Call to a member function execute() on boolean in /home/ops/apps/FreshRSS-cli-install-sqlite/app/Models/CategoryDAO.php on line 79
```

Tell me if it's better to open one issue per bug, or if it is alright to open one issue for a few linked bugs.

**Comment by Alkarex** [comment]
@oupala Thanks for your tests.
Please check https://github.com/FreshRSS/FreshRSS/pull/1447
It should fix 1, 2, 3.

Regarding 4, the format could be better but it is not that bad. You can edit it like:
```php
$config_array = include('./path/config.php');
$config_array['my_key'] = 'my_value';
file_put_contents('./path/config.php'), "<?php\n return " . var_export($config_array, true) . ";\n");
```
Regarding 5, please open a new issue.
Regarding 6, I cannot immediately reproduce (using the branch https://github.com/FreshRSS/FreshRSS/pull/1447)
Yes, please open different tickets when things are clearly distinct (e.g. 5, 6).

**Comment by oupala** [comment]
I tested this code [Alkarex/FreshRSS/tree/dev](/Alkarex/FreshRSS/tree/dev).

1. seems ok but [cli/README.md](/FreshRSS/FreshRSS/blob/master/cli/README.md) should be updated in consequence (add language possibility, and document `reconfigure.php`)
1. has been partially fixed: I can now create a user after the install, but the user is already listed as existing (see #1448), idempotency is hard until this is fixed
1. importing an opml file **still** generates some notices, not yet fixed
1. I do not really understood your example, can you explain it to me again?
1. I opened another issue #1449 
1. not a bug, forget about it ([PEBKAC](https://en.wiktionary.org/wiki/PEBKAC))

**Comment by Alkarex** [comment]
Thanks!
1. `reconfigure` is already mentioned. I will add the language option.
2.
3. Could you please open another issue, and provide an example of OPML and the corresponding warnings?
4. This is how to read, edit, save the configuration files from a PHP script (alternative to parse_ini_file). Let me know more precisely what is not clear.

**Comment by Alkarex** [comment]
1. is done in https://github.com/Alkarex/FreshRSS/commit/c544f510d26377684aefe8a27b484ee22bbd4f69
2. is done in https://github.com/Alkarex/FreshRSS/commit/ae1bf1f56fcfa920db3d5092cb18dced4cbcb434

**Comment by Alkarex** [comment]
This ticket seems to be mostly completed in https://github.com/FreshRSS/FreshRSS/pull/1447. Tests welcome. Let's open specific tickets if necessary.

**Comment by oupala** [comment]
1. I've set the default language to `fr` but when I display the login page, everything is in english. Note that no user exist at this time. But it looks like the default language `fr` has no effect on login page language.

1b. `do_install.php` is not very consistent with `reconfigure.php`, they should be named `install.php` and `reinstall.php`, or `do_install.php` and `do_reinstall.php`, or `configure.php` and `reconfigure.php`

2. very ok!

3. bug still present, I'll send you my opml file.

4. I will study your solution. But ansible and php have both an easy way to manager ini files. In addition, ini files are made for configuration file. It would be very interesting to migrate nested arrays of configuration properties to ini file. FreshRSS is however usable without that.

**Comment by Alkarex** [comment]
3. Should be fixed in https://github.com/FreshRSS/FreshRSS/pull/1452

**Comment by oupala** [comment]
Status:

- [x] 1. set the general language at install time
- [x] 2. can't reuse the login used at install time to create a new user
- [x] 3. importing an opml file generates some notices
- [x] 4. missing settings not settable with CLI
- [x] 5. ansible playbook idempotency capability
- [ ] ~~6. import fails when done twice (and this is normal), but the error is not well handled~~

All (valid) items fixed.

**Comment by Alkarex** [comment]
Thanks for the feedback :-)
