### ISSUE TITLE
Problem with Synchronization - can't sync manually or automatic

### ISSUE THREAD

**Issue by Paxistatis** [FreshRSS/FreshRSS#1446]
Hello everybody,

first, thank you for this awesome piece of software! 
I'm trying to use it on my webhosting package and I copied all data to my domain (Current master version if i click on download). Also adding feeds is possible.
But I can't refresh the feeds but I know that there should be some new posts! I tried all ways of the documentation which are possible (http://doc.freshrss.org/en/users/03_Main_view/#refreshing-feeds). I can't use cronjobs on my server but webchron or manually update don't work. Specially the update with the click on the button should be possible or?
In the protocoll no errors are logged and I don't know what I should do. 
Also checking the installation shows no error...
Can someone help me? That woudl be great!
I can also add additional information if needed!

Thanks!

**Comment by Alkarex** [comment]
Hello,
Yes, manual refresh should work. Have a look in FreshRSS settings as well as the settings for an individual feed which max refresh value there is (something like 1 hour). It is normal not to be able a given feed more often than this delay.
If this is not the reason, try having a look in FreshRSS logs available from the Web interface.

**Comment by Paxistatis** [comment]
@Alkarex Execuse my stupidity ^^ It was the setting of one hour which limited that refresh. Sorry for this circumstances of an user which was a little im impatient. 
Maybe this information of the refresh value of one hour would be a good idea to add to the documentation? 
But thanks for your really fast answer :+1:  :)!

**Comment by Alkarex** [comment]
I hope you will like it :-)
