### ISSUE TITLE
clue to allow idempotency with ansible

### ISSUE THREAD

**Issue by oupala** [FreshRSS/FreshRSS#1449]
Ansible need clue to allow idempotency.

These scripts are read-only, and hence idempotent by nature:

- `export-zip-for-user.php`
- `export-opml-for-user.php`
- `list-users.php`
- `user-info.php`

These scripts are not safe as there modify FresRSS's internal data:

- `do-install.php` should be launched **only** if `data/do-install.txt` exists (otherwise, installation has already been launched)
- `create-user.php` should be launched only if the user **does not exist** (see `list-users.php` for that)
- `delete-user.php` should be launched only if the user **does exist** (see `list-users.php` for that)
- `import-for-user.php` should be launched only if the user has no feed (**there is no way to check that**)

- `actualize-user.php` returns **0** if there is new articles, **1** if there is no new articles
- `reconfigure.php` is a mystery (as it is **not documented** on [cli/README.md](/FreshRSS/FreshRSS/blob/master/cli/README.md))

**Comment by Alkarex** [comment]
A few responses already:
* `create-user.php` already exits with error code if user exists
* `delete-user.php` already exits with error code if user does not exist
* `import-for-user.php` may be run several times on the same user, e.g. to import new OPML files. I will however provide a way to know how many feeds a user has
* `reconfigure.php` is new and named in the /dev branch https://github.com/FreshRSS/FreshRSS/blob/dev/cli/README.md

**Comment by Alkarex** [comment]
`user-info.php` now returns a lot more information https://github.com/Alkarex/FreshRSS/commit/ada94465e62d5809303afffc636fdae87aff2738

**Comment by Alkarex** [comment]
NB: importing several times an OPML file already imported should do nothing (because categories and feeds already exist)

**Comment by Alkarex** [comment]
`do-install.php` should be fixed in https://github.com/Alkarex/FreshRSS/commit/37957d45b24306f494554ee1e6c911998ca68643

**Comment by Alkarex** [comment]
`actualize-user.php`: isn't it already doing what you ask, @oupala ?
It looks like all is done in https://github.com/FreshRSS/FreshRSS/issues/1447

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/1447 merged in /dev. Tests welcome. Let's open specific issues if needed.

**Comment by oupala** [comment]
Most of the scripts were already working as expected. I was not only asking for some feature, I was also listing the expecting behaviour of some scripts.

Scripts are now quite idempotent. Thanks a lot for the job done!

And the best thing with `user-info.php` would be to allow some more parameters in order to tell what fields to display.

For example:

- `./cli/user-info.php -h --user username --feedsNumber`
- `./cli/user-info.php -h --user username --field "fieldNumber"`

could display only the number of feeds of the user.

It would be easier to parse via bash or ansible, and making CLI more useful and easy to use.

**Comment by Alkarex** [comment]
Thanks for the tests.
Yes, the script could be smarter, but its output is quite easy to parse with `cut -f`. For instance, to get the number of feeds:

```sh
./cli/user-info.php --user alex | cut -f6
155
```

**Comment by oupala** [comment]
You're thinking bash, in which I agree it is easy to parse the result string.

But things are different in ansible. That's why I was asking that...
