### ISSUE TITLE
upgrade check should not need write permission on the whole tree

### ISSUE THREAD

**Issue by oupala** [FreshRSS/FreshRSS#1450]
When trying to check if the last version is installed, I get the following error message:

`Arf ! Veuillez vérifier les droits sur le répertoire /home/user/apps/FreshRSS-dev. Le serveur HTTP doit être capable d’écrire dedans`

Why does the check-last-available-version need to have the *write permission* on the whole tree?

I think it is to write the last check datetime. But this datetime should be stored into the `data` directory, no?

**Comment by Alkarex** [comment]
Related to https://github.com/FreshRSS/FreshRSS/issues/907

**Comment by oupala** [comment]
In any case, last check datetime is not that important. The most important thing is to check if FreshRSS is in the last version. Storing the date when this check happened is useful but not mandatory.

Being unable to write that date should only display a warning, but should allow version checking.

**Comment by oupala** [comment]
There is a large difference between upgrading a software, and just checking if there is a new release available.

I don't want FreshRSS to upgrade itself as my server in manager via ansible. But I want FreshRSS to be able (and to notify me) if a new release is available. I could hence launch a new ansible deployment to upgrade FreshRSS when I want to.

**Comment by Alkarex** [comment]
Implemented in https://github.com/FreshRSS/FreshRSS/pull/1544

**Comment by oupala** [comment]
I'm testing FreshRSS 1.7.0-dev and I still have the error message:

> Arf ! Nouvelle version dev disponible, mais veuillez vérifier les droits sur le répertoire /home/ops/apps/FreshRSS-dev. Le serveur HTTP doit être capable d’écrire dedans

Has the merge request been accepted?

I'll be able to test as soon as it is merged in **dev** branch.

**Comment by Alkarex** [comment]
The message looks good (it seems to be from the new patch). It tells you that there is a new version, but cannot proceed because it does not have the rights.

**Comment by oupala** [comment]
Ok. The problem I see is that I'm getting an error while I just want to know if there is a new version. I think it would be an improvement if it could be a *two-step* process.

1. first checking if there is a new version available (this step should **never** fail, except for a network problem where it display *can't check for a new release*)
2. then, try to update it (but **only** if the user requested to do so), this step could preventively check if the upgrade process is possible (due to permission issue) to determine if it should display the upgrade button or not

As a consequence, messages could be more explicit. Let me give you an example:

- first step:

> [Vérifier les mises à jour] button activated
> Une nouvelle version **1.7.1** est disponible.
> or
> Impossible de vérifier si une nouvelle version est disponible. Une erreur réseau est peut-être survenue.

- second step

> [Mettre à jour FreshRSS vers la version **1.7.1**]
> or
> Impossible de mettre à jour FreshRSS vers une nouvelle version car FreshRSS n'a pas les permissions en ériture sur son propre répertoire. Vous pouvez mettre à jour les permissions si vous voulez bénéficier d'une mise à jour automatisée.

**Comment by oupala** [comment]
And I understand how I got the right error message even if the merge request was not yet merged: I was using **Alkarex/FreshRSS dev** branch!

**Comment by Alkarex** [comment]
Ah @oupala indeed, my own /dev branch contains some patches in advance. This is the branch I actually use myself :-)

**Comment by Alkarex** [comment]
Let's revise this update mechanism as part of https://github.com/FreshRSS/FreshRSS/issues/907
I think the current version does what you need, even if not optimal, doesn't it?

**Comment by oupala** [comment]
Yes, it does the job.

The only problem is that I will always get the error message. And at first, I did not even had a look at the message itself as I was expecting an information or a warning message.

By the way, is there a way to apply this check automatically, at the login process by example? I mean, when the admin user logs in (or maybe when any user logs in), there could be a notification to indicate that a new version is available somewhere on the default interface (something like the already existing "new articles availables" notification).

**Comment by Alkarex** [comment]
Indeed, a UI notification would be nice. Could you please create a new issue for that?

**Comment by oupala** [comment]
I think we could close this issue now.
