### ISSUE TITLE
Stats page not working: there is no graph

### ISSUE THREAD

**Issue by lapineige** [FreshRSS/FreshRSS#1453]
Hello FreshRSS team :)

When I try to load any of the statistics pages, the graphs parts are blank.
The web console only raise the following issue: `TypeError: e.getContext is not a function`
(I can give you the detail of the error if needed)

Do you know what's happening ?
Thanks :)

**Comment by Alkarex** [comment]
Hello,
The statistics are working fine for me. Yes, please provide additional error information.
Please try with another browser without extension. Did you make any change to JavaScript security such as CSP?

**Comment by lapineige** [comment]
Ok I found the issue, I changed by mistake a parameter in CanvasBlocker extension, blocking <canvas> for FreshRSS.
Sorry for the inconvenience.
