### ISSUE TITLE
Custom CSS and JS does not save anything

### ISSUE THREAD

**Issue by Kasad** [FreshRSS/FreshRSS#1456]
Hello everybody,

I'd like to switch from TTRSS to FreshRSS. Some things I really miss, so does the News+ Client not work any longer, but this is another problem ;)

I try to fix the header bar with jQuery, but both Extension (Custom CSS and JS) do not save anything when I click on save... it just return an empty input field.

Is there something wrong with these extensions?

Greetings

**Comment by Alkarex** [comment]
Hello @Kasad ,
(News+ works fine with FreshRSS - I use it intensively).
I have not looked at those extensions lately. I will try to test.

**Comment by Alkarex** [comment]
Related issue https://github.com/FreshRSS/Extensions/issues/13

**Comment by Alkarex** [comment]
@Kasad In order to use News+ with FreshRSS, you need to use this module https://play.google.com/store/apps/details?id=com.noinnion.android.newsplus.extension.google_reader and enable the API in FreshRSS settings

**Comment by Alkarex** [comment]
@Kasad The extension *xExtension-CustomCSS* is saving data in `./extensions/xExtension-CustomCSS/static/`, so it currently requires write access there.
Note for later: We should change this behaviour to save files under `./data/` instead.

**Comment by Frenzie** [comment]
xExtension-CustomJS is basically a direct copy and therefore also affected.

**Comment by Alkarex** [comment]
@Frenzie We now have a `./data/extensions-data/` directory https://github.com/FreshRSS/FreshRSS/pull/1547
