### ISSUE TITLE
Keep folder state (opened / closed)

### ISSUE THREAD

**Issue by Kasad** [FreshRSS/FreshRSS#1457]
Hello everybody,

is there a way to save the collapse state of folders?

Greetings
Kasad

**Comment by Alkarex** [comment]
Hello Kasad,
This is not currently possible. It would be doable with a custom JS though.

**Comment by GeoZzNL** [comment]
Yes it is possible, check the extension: https://github.com/FreshRSS/Extensions

https://github.com/oyox/FreshRSS-extensions/tree/master/xExtension-KeepFolderState

**Comment by aledeg** [comment]
@Kasad I think this extension will solve your problem

**Comment by squromiv** [comment]
I am newbie to FreshRSS, but It seems, that extension does not work on last FreshRSS versions. As soon as I click on a feed, categories become folded. It would be great to see it as standard feature, as in Tiny Tiny RSS and other applications.
![screen_2019 04 06 001](https://user-images.githubusercontent.com/15985877/55673037-b5d39780-58a2-11e9-8404-215a3aa4f9e1.png)

**Comment by Alkarex** [comment]
@squromiv This extension is currently broken. See https://github.com/FreshRSS/FreshRSS/pull/2234#issuecomment-480485232

**Comment by Alkarex** [comment]
Let's reopen here

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/Extensions/pull/47

**Comment by squromiv** [comment]
My vote is for realization in core.

**Comment by squromiv** [comment]
Just another connected issue: #2248

**Comment by Alkarex** [comment]
Implemented natively by https://github.com/FreshRSS/FreshRSS/pull/3185
