### ISSUE TITLE
Repository with my extensions (swipe, fixed-menu, menu-autohide, keep folder state)

### ISSUE THREAD

**Issue by oyox** [FreshRSS/FreshRSS#1458]
Hello Alkarex,
Hello everyone,

I like FreshRSS very much, so I've created a repository with (for now) 4 nice extensions:

https://github.com/oyox/FreshRSS-extensions

Fixed Nav Menu:
- Sets the position of the navigation menu to fixed when scrolling down.

Keep Folder State:
- Stores the state of the folders locally and expand them automatically if necessary. 

Mobile Scroll Menu:
- Automatically hides the header menu on mobile phones, when scrolling down and shows it when scrolling up.

Touch Control:
- Add touch gestures to FreshRSS.

Maybe you want set a link to this repo.

Sincerely
Marco

**Comment by kevinpapst** [comment]
Hey oyox, maybe you want to crate a PR for this repos README:
https://github.com/FreshRSS/Extensions
you could add your link there.

**Comment by Alkarex** [comment]
Implemented in https://github.com/FreshRSS/Extensions/pull/14
