### ISSUE TITLE
window.opener vulnerability?

### ISSUE THREAD

**Issue by matolivier** [FreshRSS/FreshRSS#1459]
Hi,

I'm used to have this website in my feeds : https://blog.nathanaelcherrier.com/

When I middle click on my mouse for opening an post in a new tab, my freshrss tab is redirected to this page : https://blog.nathanaelcherrier.com/phishing/?referrer=rss.website which says:

![fish](https://cloud.githubusercontent.com/assets/18326674/23945945/c3cb9a34-0978-11e7-8e35-adfbed325627.png)

**Comment by Alkarex** [comment]
Bonsoir,
Which version of FreshRSS are you using, and with with browser?
This should have been fixed in FreshRSS 1.6.0 for modern browsers
https://github.com/FreshRSS/FreshRSS/blob/dev/CHANGELOG.md#2016-10-30-freshrss-160
https://github.com/FreshRSS/FreshRSS/issues/1245

**Comment by matolivier** [comment]
Hi Alkarex,

I'm ashamed because I'm still running version 1.4.0...
So I'm going to update it.

Thank you and sorry for the noise. :)

Matthieu

**Comment by Alkarex** [comment]
Please give a try to the brand new version 1.6.3 :-) https://github.com/FreshRSS/FreshRSS/blob/master/CHANGELOG.md
