### ISSUE TITLE
PHP fileinfo problem | Load icons

### ISSUE THREAD

**Issue by duckysec** [FreshRSS/FreshRSS#1461]
Bonjour,

Tout d'abord merci pour votre outil, il est très pratique !

Cependant, après l'installation et la configuration de la plupart de mes flux RSS, j'ai rencontré un problème : l'affiche des icônes. 

- Sur Google Chrome j'obtiens des carrés vides : 
![erreur_chrome](http://img4.hostingpics.net/pics/492531erreuriconechrome.png)

- Sur Mozilla Firefox, j'obtiens un logo identique à tous mes flux (sûrement un logo par défaut ?) : 
![erreur_firefox](http://img4.hostingpics.net/pics/674285erreuriconefirefox.png)

Pour information, mon installation FreshRSS se situe derrière un reverse proxy et j'utilise la branche master de FreshRSS.

J'ai tenté de faire un links en local d'une des erreurs 404 pour le fichier _f.php?id_ et cela me propose bien de télécharger le fichier .ico correspondant : 
`links http://localhost/veille/f.php?3dc0d09f`

Voici un exemple du contenu du répertoire _/usr/share/FreshRSS/data/favicons/_ : 
```
-rw-r--r-- 1 www-data www-data  3639 mars  18 03:07 0533b7c1.ico
-rw-rw-r-- 1 www-data www-data    32 mars  18 00:14 0533b7c1.txt
-rw-r--r-- 1 www-data www-data  1406 mars  18 03:06 0f43593b.ico
-rw-rw-r-- 1 www-data www-data    36 mars  18 00:14 0f43593b.txt
-rw-r--r-- 1 www-data www-data  1150 mars  18 03:36 101f3367.ico
-rw-r--r-- 1 www-data www-data    32 mars  18 01:10 101f3367.txt
```

Dans mon fichier de logs, j'ai plusieurs lignes comme celle ci-dessous : 
`PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20131226/fileinfo.so' - /usr/lib/php5/20131226/fileinfo.so: cannot open shared object file: No such file or directory in Unknown on line 0
`
Il se trouve qu'effectivement il n'y a aucun fichier _/usr/lib/php5/20131226/fileinfo.so_ à cet emplacement. La commande find ne trouve également pas de fichier fileinfo.so .

Pourtant, PHP me répond OK quand je place ces lignes dans mon index.php :
`echo 'fileinfo ', extension_loaded('fileinfo') ? 'OK' : 'NOK', "\n";
echo 'finfo_open ', function_exists('finfo_open') ? 'OK' : 'NOK', "\n";
echo 'finfo_file ', function_exists('finfo_file') ? 'OK' : 'NOK', "\n";`

Si quelqu'un a une idée, je suis preneur de tout test à effectuer.

Merci d'avance,
Baptiste

**Comment by Alkarex** [comment]
Bonjour,
Il semblerait qu'il y ait des plateformes où `fileinfo` est mal installé. Sur quelle plateforme êtes-vous ? De plus, faire attention que PHP en ligne de commande ne donne pas forcément les mêmes résultats que PHP via le serveur Web.
Tickets en relation :
* https://github.com/FreshRSS/FreshRSS/issues/1402
* https://github.com/FreshRSS/FreshRSS/issues/1375

**Comment by duckysec** [comment]
Il s'agit d'une Debian Jessie et de Apache/2.4.10 + PHP 5.6.30-0.
J'avais également fait des recherches mais je n'ai pas réussi à réinstaller fileinfo.so .

**Comment by Alkarex** [comment]
Je vais essayer de regarder. Il serait aussi possible d'essayer de se passer complètement de fileinfo pour les favicons.

**Comment by Alkarex** [comment]
Bonjour,
Pourriez-vous essayer ce patch ? https://github.com/FreshRSS/FreshRSS/pull/1491

**Comment by Alkarex** [comment]
P.S. : pour tester, vous pouvez simplement remplacer ce fichier https://github.com/Alkarex/FreshRSS/blob/a542ab8fff7cd13ef54f5585f029b6c1d2244351/lib/Favicon/Favicon.php

**Comment by Alkarex** [comment]
P.S. : Le patch est maintenant dans la version /dev de FreshRSS, donc il serait encore mieux de tester https://github.com/FreshRSS/FreshRSS/tree/dev :-)
