### ISSUE TITLE
Fermeture pop-up après partage FB

### ISSUE THREAD

**Issue by Draky50110** [FreshRSS/FreshRSS#1462]
Hello.

Dans le flux, je souhaite partager un article, je clique sur le partage Facebook, le popup s'ouvre, je publie mais ça ne se ferme pas mais reste sur une page blanche avec l'URL https://www.facebook.com/dialog/return/close?#_=_

J'utilise une extension anti popup (Tab Mix Plus) mais est-ce dû à ça ?

**Comment by Alkarex** [comment]
Qu'est-ce que cela donne avec un autre navigateur sans extension ?

**Comment by aledeg** [comment]
Je viens de tester le partage, il fonctionne correctement. Si `Tab Mix Plus` était la source du problème, on peut oublier ça car l'extension n'est plus compatible avec les dernières versions de Firefox (depuis la version 57).
Je pense qu'on peut fermer ce ticket.
