### ISSUE TITLE
Improve English Translations

### ISSUE THREAD

**Issue by jlefler** [FreshRSS/FreshRSS#1464]
Some English translations use poor grammar or improper words. This ticket is a placeholder so I can submit a pull request to improve the English translation.

**Comment by Alkarex** [comment]
Merged. Thanks 👍

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/1465/files#r109282131

**Comment by Alkarex** [comment]
Fixed in https://github.com/FreshRSS/FreshRSS/pull/1492
