### ISSUE TITLE
Crypto exception! Error: Invalid salt version:

### ISSUE THREAD

**Issue by giorgioprovenzale** [FreshRSS/FreshRSS#1466]
Hello,
I installed FreshRSS and everything is ok, but when I try to login I receive this error:

Crypto exception! Error: Invalid salt version:

Can you help me, please?

Thanks!

**Comment by Alkarex** [comment]
Hello @giorgioprovenzale 
Could you please provide some information about your server, your browser, and FreshRSS version?
Have you tried with another Web browser?
If you want, you are welcome to send me [by e-mail](https://alexandre.alapetite.fr/cv/) the address of your instance so I can have a look.

**Comment by giorgioprovenzale** [comment]
Hi @Alkarex, thanks for your message.
I use PHP 5.4 with MySQL 5.6.35. I use Chrome.
I think is something related to my config file, the file under dafault user folder.
I send you a email with url and the config file.

Thanks

**Comment by Alkarex** [comment]
It looks like this specific issue is solved.
As discussed by e-mail, for the remaining problems, see https://github.com/FreshRSS/FreshRSS/issues/1243#issuecomment-244941741 or open a new issue.

**Comment by giorgioprovenzale** [comment]
Hello,
Yes I installed everything again and changed my settings on DB. It is ok.

Thanks

Bye!

Il Dom 26 Mar 2017, 15:13 Alexandre Alapetite <notifications@github.com> ha
scritto:
