### ISSUE TITLE
Can't add kodi rss feed

### ISSUE THREAD

**Issue by olivierkeke** [FreshRSS/FreshRSS#1467]
I can't add the feed "https://kodi.tv/feed/" on FreshRSS 1.6.2.
Logs say "Unknown error for feed [https://kodi.tv/feed/]"

**Comment by Alkarex** [comment]
The full error is: A feed could not be found at `https://kodi.tv/feed/`; the status code is `503` and content-type is `text/html; charset=UTF-8`

Could you please try from your server:

```sh
curl -v https://kodi.tv/feed/

curl -v -A 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0' https://kodi.tv/feed/
```

It looks like an IP ban or routing problem. I can reproduce the problem from my server at OVH (both in IPv4 and IPv6) but not from my other servers.

**Comment by olivierkeke** [comment]
My FreshRSS is also on an OVH (shared) server. Since I have no ssh access on this server I don't know how to try your command lines.

**Comment by Alkarex** [comment]
All right. It looks like an OVH routing/peering problem. Not much I can do from my side.
You can use a bridge/proxy hosted elsewhere for this feed.

**Comment by olivierkeke** [comment]
OK I will try this workaround. Thanks !
