### ISSUE TITLE
(Re)Sorting the feeds by publication date ?

### ISSUE THREAD

**Issue by lapineige** [FreshRSS/FreshRSS#1468]
Hello FreshRSS team,

I was wondering if it's possible (as an option) to sort the articles by publication date.

I mean,  when fetching articles from a newly added feed, all of them are put on top of the others. Also when updating the feed list after a long while without doing it (for instance because the computer was shutdown) it makes a lot of "blocks" of articles, from each feed, without any chronological order.
And I found this annoying because it force me to read all the articles from one feed to see the others, while I could just ignore the oldest ones until I'm ready to read them.

Do you think this is a possible addition ?
I don't know if it's better to have a button in the preferences, or an option by default or during each feed addition.

Thanks for your time :)

**Comment by Alkarex** [comment]
Hello @lapineige 
This will be solved by https://github.com/FreshRSS/FreshRSS/issues/530 planned for version 1.7.
In the meantime, the problem can be mitigated by running a refresh cron more often.

**Comment by Alkarex** [comment]
Let's continue in #530.

**Comment by lapineige** [comment]
I've nothing to have, this is coming in the next version, perfect. Thanks for your time :)

**Comment by Alkarex** [comment]
I have just done a candidate implementation https://github.com/FreshRSS/FreshRSS/issues/1470
It is not entirely finished, but tests would be welcome already
