### ISSUE TITLE
should we add "upgrade-insecure-requests" to content security policy?

### ISSUE THREAD

**Issue by oupala** [FreshRSS/FreshRSS#1469]
Should we add "upgrade-insecure-requests" to content security policy?

The attribute "upgrade-insecure-requests" on the content security policy header upgrades all http request to the equivalent request in https.

Should we add it to the content security policy header managed by FreshRSS?

**Comment by Alkarex** [comment]
Could you please provide a bit more details?
There is still plenty of Web sites that do not support HTTPS, and we cannot just rewrite all requests to HTTPS. There is an HTTPS whitelist in `./data/force-https.txt` and `./data/force-https.default.txt`.

**Comment by oupala** [comment]
I was first thinking that it was a good idea. But I was only thinking about assets from FreshRSS.

But when I think a bit more, I realize that FreshRSS is loading and displaying articles from other website which can be loading assets from their own website, which can still be in http and not supporting https.

Adding this header is maybe a bad idea. I was thinking about absolute malformed url to an asset of FreshRSS accessed in http. But there is no such malformed urls in FreshRSS, isn't it? ;-)

**Comment by Alkarex** [comment]
Nope :-)

**Comment by oupala** [comment]
Ok, so forget it...
