### ISSUE TITLE
Bugs with PostgreSQL + PHP 7.1

### ISSUE THREAD

**Issue by tcitworld** [FreshRSS/FreshRSS#1471]
Happening on latest release, master and dev branch.

Items can't be saved.

PHP logs
<details>
<pre>
[Sun Mar 26 12:13:34 2017] ::1:50036 [200]: /p/i/?c=feed&a=actualize&id=2&ajax=1
[Sun Mar 26 12:13:34 2017] PHP Warning:  A non-numeric value encountered in /home/tcit/dev/FreshRSS/lib/SimplePie/SimplePie/Parse/Date.php on line 694
[Sun Mar 26 12:13:34 2017] PHP Stack trace:
[Sun Mar 26 12:13:34 2017] PHP   1. {main}() /home/tcit/dev/FreshRSS/p/i/index.php:0
[Sun Mar 26 12:13:34 2017] PHP   2. Minz_FrontController->run() /home/tcit/dev/FreshRSS/p/i/index.php:46
[Sun Mar 26 12:13:34 2017] PHP   3. Minz_Dispatcher->run() /home/tcit/dev/FreshRSS/lib/Minz/FrontController.php:84
[Sun Mar 26 12:13:34 2017] PHP   4. Minz_Dispatcher->launchAction() /home/tcit/dev/FreshRSS/lib/Minz/Dispatcher.php:48
[Sun Mar 26 12:13:34 2017] PHP   5. FreshRSS_feed_Controller->actualizeAction() /home/tcit/dev/FreshRSS/lib/Minz/Dispatcher.php:119
[Sun Mar 26 12:13:34 2017] PHP   6. FreshRSS_feed_Controller::actualizeFeed() /home/tcit/dev/FreshRSS/app/Controllers/feedController.php:456
[Sun Mar 26 12:13:34 2017] PHP   7. FreshRSS_Feed->load() /home/tcit/dev/FreshRSS/app/Controllers/feedController.php:294
[Sun Mar 26 12:13:34 2017] PHP   8. FreshRSS_Feed->loadEntries() /home/tcit/dev/FreshRSS/app/Models/Feed.php:286
[Sun Mar 26 12:13:34 2017] PHP   9. SimplePie->get_items() /home/tcit/dev/FreshRSS/app/Models/Feed.php:301
[Sun Mar 26 12:13:34 2017] PHP  10. SimplePie_Item->get_date() /home/tcit/dev/FreshRSS/lib/SimplePie/SimplePie.php:3045
[Sun Mar 26 12:13:34 2017] PHP  11. SimplePie_Parse_Date->parse() /home/tcit/dev/FreshRSS/lib/SimplePie/SimplePie/Item.php:797
[Sun Mar 26 12:13:34 2017] PHP  12. SimplePie_Parse_Date->date_w3cdtf() /home/tcit/dev/FreshRSS/lib/SimplePie/SimplePie/Parse/Date.php:603
[Sun Mar 26 12:13:34 2017] PHP Warning:  A non-numeric value encountered in /home/tcit/dev/FreshRSS/lib/SimplePie/SimplePie/Parse/Date.php on line 694
[Sun Mar 26 12:13:34 2017] PHP Stack trace:
[Sun Mar 26 12:13:34 2017] PHP   1. {main}() /home/tcit/dev/FreshRSS/p/i/index.php:0
[Sun Mar 26 12:13:34 2017] PHP   2. Minz_FrontController->run() /home/tcit/dev/FreshRSS/p/i/index.php:46
[Sun Mar 26 12:13:34 2017] PHP   3. Minz_Dispatcher->run() /home/tcit/dev/FreshRSS/lib/Minz/FrontController.php:84
[Sun Mar 26 12:13:34 2017] PHP   4. Minz_Dispatcher->launchAction() /home/tcit/dev/FreshRSS/lib/Minz/Dispatcher.php:48
[Sun Mar 26 12:13:34 2017] PHP   5. FreshRSS_feed_Controller->actualizeAction() /home/tcit/dev/FreshRSS/lib/Minz/Dispatcher.php:119
[Sun Mar 26 12:13:34 2017] PHP   6. FreshRSS_feed_Controller::actualizeFeed() /home/tcit/dev/FreshRSS/app/Controllers/feedController.php:456
[Sun Mar 26 12:13:34 2017] PHP   7. FreshRSS_Feed->load() /home/tcit/dev/FreshRSS/app/Controllers/feedController.php:294
[Sun Mar 26 12:13:34 2017] PHP   8. FreshRSS_Feed->loadEntries() /home/tcit/dev/FreshRSS/app/Models/Feed.php:286
[Sun Mar 26 12:13:34 2017] PHP   9. SimplePie->get_items() /home/tcit/dev/FreshRSS/app/Models/Feed.php:301
[Sun Mar 26 12:13:34 2017] PHP  10. SimplePie_Item->get_date() /home/tcit/dev/FreshRSS/lib/SimplePie/SimplePie.php:3045
[Sun Mar 26 12:13:34 2017] PHP  11. SimplePie_Parse_Date->parse() /home/tcit/dev/FreshRSS/lib/SimplePie/SimplePie/Item.php:797
[Sun Mar 26 12:13:34 2017] PHP  12. SimplePie_Parse_Date->date_w3cdtf() /home/tcit/dev/FreshRSS/lib/SimplePie/SimplePie/Parse/Date.php:603
[Sun Mar 26 12:13:34 2017] PHP Warning:  A non-numeric value encountered in /home/tcit/dev/FreshRSS/lib/SimplePie/SimplePie/Parse/Date.php on line 694
[Sun Mar 26 12:13:34 2017] PHP Stack trace:
[Sun Mar 26 12:13:34 2017] PHP   1. {main}() /home/tcit/dev/FreshRSS/p/i/index.php:0
[Sun Mar 26 12:13:34 2017] PHP   2. Minz_FrontController->run() /home/tcit/dev/FreshRSS/p/i/index.php:46
[Sun Mar 26 12:13:34 2017] PHP   3. Minz_Dispatcher->run() /home/tcit/dev/FreshRSS/lib/Minz/FrontController.php:84
[Sun Mar 26 12:13:34 2017] PHP   4. Minz_Dispatcher->launchAction() /home/tcit/dev/FreshRSS/lib/Minz/Dispatcher.php:48
[Sun Mar 26 12:13:34 2017] PHP   5. FreshRSS_feed_Controller->actualizeAction() /home/tcit/dev/FreshRSS/lib/Minz/Dispatcher.php:119
[Sun Mar 26 12:13:34 2017] PHP   6. FreshRSS_feed_Controller::actualizeFeed() /home/tcit/dev/FreshRSS/app/Controllers/feedController.php:456
[Sun Mar 26 12:13:34 2017] PHP   7. FreshRSS_Feed->load() /home/tcit/dev/FreshRSS/app/Controllers/feedController.php:294
[Sun Mar 26 12:13:34 2017] PHP   8. FreshRSS_Feed->loadEntries() /home/tcit/dev/FreshRSS/app/Models/Feed.php:286
[Sun Mar 26 12:13:34 2017] PHP   9. SimplePie->get_items() /home/tcit/dev/FreshRSS/app/Models/Feed.php:301
[Sun Mar 26 12:13:34 2017] PHP  10. SimplePie_Item->get_date() /home/tcit/dev/FreshRSS/lib/SimplePie/SimplePie.php:3045
[Sun Mar 26 12:13:34 2017] PHP  11. SimplePie_Parse_Date->parse() /home/tcit/dev/FreshRSS/lib/SimplePie/SimplePie/Item.php:797
[Sun Mar 26 12:13:34 2017] PHP  12. SimplePie_Parse_Date->date_w3cdtf() /home/tcit/dev/FreshRSS/lib/SimplePie/SimplePie/Parse/Date.php:603
[Sun Mar 26 12:13:34 2017] PHP Warning:  A non-numeric value encountered in /home/tcit/dev/FreshRSS/lib/SimplePie/SimplePie/Parse/Date.php on line 694
[Sun Mar 26 12:13:34 2017] PHP Stack trace:
[Sun Mar 26 12:13:34 2017] PHP   1. {main}() /home/tcit/dev/FreshRSS/p/i/index.php:0
[Sun Mar 26 12:13:34 2017] PHP   2. Minz_FrontController->run() /home/tcit/dev/FreshRSS/p/i/index.php:46
[Sun Mar 26 12:13:34 2017] PHP   3. Minz_Dispatcher->run() /home/tcit/dev/FreshRSS/lib/Minz/FrontController.php:84
[Sun Mar 26 12:13:34 2017] PHP   4. Minz_Dispatcher->launchAction() /home/tcit/dev/FreshRSS/lib/Minz/Dispatcher.php:48
[Sun Mar 26 12:13:34 2017] PHP   5. FreshRSS_feed_Controller->actualizeAction() /home/tcit/dev/FreshRSS/lib/Minz/Dispatcher.php:119
[Sun Mar 26 12:13:34 2017] PHP   6. FreshRSS_feed_Controller::actualizeFeed() /home/tcit/dev/FreshRSS/app/Controllers/feedController.php:456
[Sun Mar 26 12:13:34 2017] PHP   7. FreshRSS_Feed->load() /home/tcit/dev/FreshRSS/app/Controllers/feedController.php:294
[Sun Mar 26 12:13:34 2017] PHP   8. FreshRSS_Feed->loadEntries() /home/tcit/dev/FreshRSS/app/Models/Feed.php:286
[Sun Mar 26 12:13:34 2017] PHP   9. SimplePie->get_items() /home/tcit/dev/FreshRSS/app/Models/Feed.php:301
[Sun Mar 26 12:13:34 2017] PHP  10. SimplePie_Item->get_date() /home/tcit/dev/FreshRSS/lib/SimplePie/SimplePie.php:3045
[Sun Mar 26 12:13:34 2017] PHP  11. SimplePie_Parse_Date->parse() /home/tcit/dev/FreshRSS/lib/SimplePie/SimplePie/Item.php:797
[Sun Mar 26 12:13:34 2017] PHP  12. SimplePie_Parse_Date->date_w3cdtf() /home/tcit/dev/FreshRSS/lib/SimplePie/SimplePie/Parse/Date.php:603
[Sun Mar 26 12:13:34 2017] PHP Notice:  A non well formed numeric value encountered in /home/tcit/dev/FreshRSS/app/Models/EntryDAO.php on line 161
[Sun Mar 26 12:13:34 2017] PHP Stack trace:
[Sun Mar 26 12:13:34 2017] PHP   1. {main}() /home/tcit/dev/FreshRSS/p/i/index.php:0
[Sun Mar 26 12:13:34 2017] PHP   2. Minz_FrontController->run() /home/tcit/dev/FreshRSS/p/i/index.php:46
[Sun Mar 26 12:13:34 2017] PHP   3. Minz_Dispatcher->run() /home/tcit/dev/FreshRSS/lib/Minz/FrontController.php:84
[Sun Mar 26 12:13:34 2017] PHP   4. Minz_Dispatcher->launchAction() /home/tcit/dev/FreshRSS/lib/Minz/Dispatcher.php:48
[Sun Mar 26 12:13:34 2017] PHP   5. FreshRSS_feed_Controller->actualizeAction() /home/tcit/dev/FreshRSS/lib/Minz/Dispatcher.php:119
[Sun Mar 26 12:13:34 2017] PHP   6. FreshRSS_feed_Controller::actualizeFeed() /home/tcit/dev/FreshRSS/app/Controllers/feedController.php:456
[Sun Mar 26 12:13:34 2017] PHP   7. FreshRSS_EntryDAO->addEntry() /home/tcit/dev/FreshRSS/app/Controllers/feedController.php:374
[Sun Mar 26 12:13:34 2017] PHP Notice:  A non well formed numeric value encountered in /home/tcit/dev/FreshRSS/app/Models/EntryDAO.php on line 161
[Sun Mar 26 12:13:34 2017] PHP Stack trace:
[Sun Mar 26 12:13:34 2017] PHP   1. {main}() /home/tcit/dev/FreshRSS/p/i/index.php:0
[Sun Mar 26 12:13:34 2017] PHP   2. Minz_FrontController->run() /home/tcit/dev/FreshRSS/p/i/index.php:46
[Sun Mar 26 12:13:34 2017] PHP   3. Minz_Dispatcher->run() /home/tcit/dev/FreshRSS/lib/Minz/FrontController.php:84
[Sun Mar 26 12:13:34 2017] PHP   4. Minz_Dispatcher->launchAction() /home/tcit/dev/FreshRSS/lib/Minz/Dispatcher.php:48
[Sun Mar 26 12:13:34 2017] PHP   5. FreshRSS_feed_Controller->actualizeAction() /home/tcit/dev/FreshRSS/lib/Minz/Dispatcher.php:119
[Sun Mar 26 12:13:34 2017] PHP   6. FreshRSS_feed_Controller::actualizeFeed() /home/tcit/dev/FreshRSS/app/Controllers/feedController.php:456
[Sun Mar 26 12:13:34 2017] PHP   7. FreshRSS_EntryDAO->addEntry() /home/tcit/dev/FreshRSS/app/Controllers/feedController.php:374
[Sun Mar 26 12:13:34 2017] PHP Notice:  A non well formed numeric value encountered in /home/tcit/dev/FreshRSS/app/Models/EntryDAO.php on line 161
[Sun Mar 26 12:13:34 2017] PHP Stack trace:
[Sun Mar 26 12:13:34 2017] PHP   1. {main}() /home/tcit/dev/FreshRSS/p/i/index.php:0
[Sun Mar 26 12:13:34 2017] PHP   2. Minz_FrontController->run() /home/tcit/dev/FreshRSS/p/i/index.php:46
[Sun Mar 26 12:13:34 2017] PHP   3. Minz_Dispatcher->run() /home/tcit/dev/FreshRSS/lib/Minz/FrontController.php:84
[Sun Mar 26 12:13:34 2017] PHP   4. Minz_Dispatcher->launchAction() /home/tcit/dev/FreshRSS/lib/Minz/Dispatcher.php:48
[Sun Mar 26 12:13:34 2017] PHP   5. FreshRSS_feed_Controller->actualizeAction() /home/tcit/dev/FreshRSS/lib/Minz/Dispatcher.php:119
[Sun Mar 26 12:13:34 2017] PHP   6. FreshRSS_feed_Controller::actualizeFeed() /home/tcit/dev/FreshRSS/app/Controllers/feedController.php:456
[Sun Mar 26 12:13:34 2017] PHP   7. FreshRSS_EntryDAO->addEntry() /home/tcit/dev/FreshRSS/app/Controllers/feedController.php:374

</pre>
</details>

Postgres logs : 
...
```
INSTRUCTION :  INSERT INTO "freshrss_tcit_entry" (id, guid, title, author, content, link, date, "lastSeen", hash, is_read, is_favorite, id_feed, tags) VALUES($1, $2, $3, $4, $5, $6, $7, $8, decode($9, 'hex'), $10, $11, $12, $13)
ERREUR:  la transaction est annulée, les commandes sont ignorées jusqu'à la fin du bloc
	de la transaction
INSTRUCTION :  UPDATE "freshrss_tcit_feed" SET "cache_nbEntries"=(SELECT COUNT(e1.id) FROM "freshrss_tcit_entry" e1 WHERE e1.id_feed="freshrss_tcit_feed".id),"cache_nbUnreads"=(SELECT COUNT(e2.id) FROM "freshrss_tcit_entry" e2 WHERE e2.id_feed="freshrss_tcit_feed".id AND e2.is_read=0),"lastUpdate"=$1, error=$2 WHERE id=$3
```

**Comment by Alkarex** [comment]
Thanks for the bug report. It seems it is a bug that is triggered by a specific feed, isn't it?
Could you please share the feed URL (your feed number 2)?

**Comment by tcitworld** [comment]
It's `https://github.com/FreshRSS/FreshRSS/releases.atom`... :/

**Comment by Alkarex** [comment]
For reference:
* http://php.net/manual/migration71.php
* https://github.com/FreshRSS/FreshRSS/blob/cb114a341b904799b73e8e7ff1ebeab39d3c21ab/lib/SimplePie/SimplePie/Parse/Date.php#L694
* https://github.com/FreshRSS/FreshRSS/blob/ae5a8572d50fbbd52bdd88cce6bb80b79dbaaf1a/app/Models/EntryDAO.php#L160

**Comment by Alkarex** [comment]
https://github.com/simplepie/simplepie/pull/458

**Comment by Alkarex** [comment]
@tcitworld Could you please test https://github.com/FreshRSS/FreshRSS/pull/1472
Let's continue there.

**Comment by tcitworld** [comment]
With #1472, php warnings are no longer present. However, I'm still having these issues with Postgre : 

> SQL error updateLastUpdate: ERREUR: la transaction est annulée, les commandes sont ignorées jusqu'à la fin du bloc

```
INSTRUCTION :  UPDATE "freshrss_tcit_feed" SET "cache_nbEntries"=(SELECT COUNT(e1.id) FROM "freshrss_tcit_entry" e1 WHERE e1.id_feed="freshrss_tcit_feed".id),"cache_nbUnreads"=(SELECT COUNT(e2.id) FROM "freshrss_tcit_entry" e2 WHERE e2.id_feed="freshrss_tcit_feed".id AND e2.is_read=0),"lastUpdate"=$1, error=$2 WHERE id=$3
ERREUR:  la dernière valeur (lastval) n'est pas encore définie dans cette session
INSTRUCTION :  SELECT LASTVAL()
ERREUR:  la transaction est annulée, les commandes sont ignorées jusqu'à la fin du bloc
	de la transaction
INSTRUCTION :  INSERT INTO "freshrss_tcit_entry" (id, guid, title, author, content, link, date, "lastSeen", hash, is_read, is_favorite, id_feed, tags) VALUES($1, $2, $3, $4, $5, $6, $7, $8, decode($9, 'hex'), $10, $11, $12, $13)
ERREUR:  la transaction est annulée, les commandes sont ignorées jusqu'à la fin du bloc
	de la transaction
INSTRUCTION :  INSERT INTO "freshrss_tcit_entry" (id, guid, title, author, content, link, date, "lastSeen", hash, is_read, is_favorite, id_feed, tags) VALUES($1, $2, $3, $4, $5, $6, $7, $8, decode($9, 'hex'), $10, $11, $12, $13)
ERREUR:  la transaction est annulée, les commandes sont ignorées jusqu'à la fin du bloc
	de la transaction
INSTRUCTION :  INSERT INTO "freshrss_tcit_entry" (id, guid, title, author, content, link, date, "lastSeen", hash, is_read, is_favorite, id_feed, tags) VALUES($1, $2, $3, $4, $5, $6, $7, $8, decode($9, 'hex'), $10, $11, $12, $13)
ERREUR:  la transaction est annulée, les commandes sont ignorées jusqu'à la fin du bloc
	de la transaction
INSTRUCTION :  UPDATE "freshrss_tcit_feed" SET "cache_nbEntries"=(SELECT COUNT(e1.id) FROM "freshrss_tcit_entry" e1 WHERE e1.id_feed="freshrss_tcit_feed".id),"cache_nbUnreads"=(SELECT COUNT(e2.id) FROM "freshrss_tcit_entry" e2 WHERE e2.id_feed="freshrss_tcit_feed".id AND e2.is_read=0),"lastUpdate"=$1, error=$2 WHERE id=$3
```

**Comment by Alkarex** [comment]
* http://php.net/manual/migration71.changed-functions.php#migration71.changed-functions.pdo

**Comment by Alkarex** [comment]
Should be fixed by https://github.com/FreshRSS/FreshRSS/pull/1472/commits/7a6751b50d9c809d2127a154bf811f576a24e4a4
Could you please try again https://github.com/FreshRSS/FreshRSS/pull/1472 ?

**Comment by tcitworld** [comment]
Perfect.

**Comment by Alkarex** [comment]
Thanks for the quick feedback 👍
