### ISSUE TITLE
Survey: Minimal version of PostgreSQL?

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#1473]
PostgreSQL users, I am interested to know which version of the database you are running:
@tcitworld , @PodCol , @Damstre , @anayrat , @ldidry , @Trim , etc.

It is to avoid supporting older PostgreSQL versions if nobody uses them. Indeed, it would be less work if I could use features from PostgreSQL 9.5+ such as `CREATE INDEX IF NOT EXISTS`
https://www.postgresql.org/docs/9.5/static/sql-createindex.html

So please let me know :-)

**Comment by anayrat** [comment]
I use 9.6 but :+1:  for 9.5.

**Comment by anayrat** [comment]
Maybe UPSERT will be usefull : https://wiki.postgresql.org/wiki/What's_new_in_PostgreSQL_9.5#INSERT_..._ON_CONFLICT_DO_NOTHING.2FUPDATE_.28.22UPSERT.22.29
