### ISSUE TITLE
CentOS 6.8 MySQL: Access to database is denied

### ISSUE THREAD

**Issue by uncovery** [FreshRSS/FreshRSS#1474]
I just installed the package, did the MySQL setup, the databases were created, but when I try to login, I get the following error:

```
### Application problem ###
See logs files
```

When I go to /data/users/username/log.txt, I get this here:

`Access to database is denied for `freshrss` (`mysql:host=localhost;dbname=freshrss;charset=utf8mb4`)`

Of course I checked the config file settings, and it seems to be ok. Anyhow, it must have worked during the installation, since the databases were created. What can be wrong?

**Comment by Alkarex** [comment]
It is probably due to utf8mb4. Look in recent issues. Are you hosted at OVH?

**Comment by uncovery** [comment]
I am hosting on my own dedicated server. Can you link me some of those issues? Searching the issues here for utfmb4 does not return any results.

Also, I just changed the database collation to utf8mb4_unicode_ci, still same problem.

Here is some data from my phpMyAdmin home screen:


    Server: uncovery (Localhost via UNIX socket)
    Server type: MySQL
    Server version: 5.5.54-log - MySQL Community Server (GPL)
    Protocol version: 10
    Server charset: UTF-8 Unicode (utf8)

**Comment by Alkarex** [comment]
Please run this little test
https://github.com/FreshRSS/FreshRSS/issues/1243#issuecomment-244941741

Related issues:
* https://github.com/FreshRSS/FreshRSS/issues/1401
* https://github.com/FreshRSS/FreshRSS/issues/1369
* https://github.com/FreshRSS/FreshRSS/issues/1297
* https://github.com/FreshRSS/FreshRSS/issues/1243

**Comment by uncovery** [comment]
Ok, thanks, I changed t oSQLite until I can upgrade my server to a newer MySQL version

**Comment by Alkarex** [comment]
Ok. For the record, which system are you running?

**Comment by uncovery** [comment]
CentOS release 6.8

**Comment by Alkarex** [comment]
Ok. Could please run `mysql --version`?
Example from my machine:
```
mysql  Ver 14.14 Distrib 5.7.17, for Linux (x86_64) using  EditLine wrapper
```
I think the problem is with the client / client libraries, not with the MySQL server.
CentOS 6.8 ships with the very old MySQL 5.1.x branch (2005), and although you have MySQL 5.5.x (manual update?), I am guessing not all dependencies have been updated accordingly.

**Comment by uncovery** [comment]
`mysql  Ver 14.14 Distrib 5.5.54, for Linux (x86_64) using readline 5.1`

**Comment by Alkarex** [comment]
Ok. Thanks. Probably one of the libraries or configuration is not good. See e.g. https://www.drupal.org/project/utf8mb4_convert

**Comment by uncovery** [comment]
hmmm not sure how to use this info to change my server's setup. Will try to find out. I have set the collation of the DB already, and I am not sure if the DB is the issue or the server setup as such.
