### ISSUE TITLE
UI: lowest subscription's popup gets hidden

### ISSUE THREAD

**Issue by psukys** [FreshRSS/FreshRSS#1479]
Steps to reproduce:

1. Have a big (filling whole screen vertically) category of subscribed feeds;
2. Click on wrench (settings) of the lowest subscription;
3. Verify that the popup shows ups, part of it hidden below
4. Verify that attempts to scroll down (specifically using mouse scrolling wheel, keyboard arrows and _Page down_) does not scroll down.

Checked on

-  Chrome: Version 57.0.2987.133 (64-bit)

![screenshot from 2017-04-03 21-11-25](https://cloud.githubusercontent.com/assets/1302529/24626719/806a5dfe-18b2-11e7-92ee-f179a4e2c919.png)

**Comment by Alkarex** [comment]
Yes indeed. I was waiting for someone to complain :-P
A quick fix would probably to give a bit more margin at the bottom of the column of categories.
In the meantime, scrolling down *after* you have opened the menu should work :-)

**Comment by psukys** [comment]
@Alkarex I've downloaded and checked on Firefox and was able to scroll down _after_ opening menu, but in Chrome it does not :/

**Comment by Alkarex** [comment]
Should be fixed in https://github.com/FreshRSS/FreshRSS/pull/1489

**Comment by Alkarex** [comment]
Please test https://github.com/FreshRSS/FreshRSS/pull/1489 or even better, the [/dev version of FreshRSS](https://github.com/FreshRSS/FreshRSS/tree/dev).
