### ISSUE TITLE
Transformer les badges « x non lus » en liens vers la vue « non lu »

### ISSUE THREAD

**Issue by AmauryCarrade** [FreshRSS/FreshRSS#148]
Juste une petite suggestion : transformer les badges « x non lus » en liens vers la vue ne contenant que les éléments non lus du dossier correspondant (pour le badge d'un dossier), du flux correspondant (pour le chiffre entre parenthèses), ou de tous les flux (pour le badge à côté de... « Tous les flux », forcément).

**Comment by aledeg** [comment]
J'ai regardé ça aujourd'hui. Ce n'est pas aussi simple que ça en à l'air.

L'ajout des liens dans le DOM est facile.
La mise en page est assez simple avec l'utilisation de flexbox, même s'il faut porter une attention particulière aux différents thèmes.
Par contre la mise à jour en javascript risque d'être un peu plus compliquée que ce qui est fait actuellement. Il va falloir que je creuse un peu.

**Comment by marienfressinaud** [comment]
This ticket is opened for years, I consider that if nobody developed this feature, it's really not critical. Actually I even think it's better to keep the categories as they are, it's really simpler and I never found it was a missing feature. Maybe some user tests would raise the problem, but I'm closing this ticket for now.
