### ISSUE TITLE
Full article content for any website

### ISSUE THREAD

**Issue by GeoZzNL** [FreshRSS/FreshRSS#1480]
Hi everyone!

I am using FreshRSS for 2 weeks now, i am impressed. Its a great application and very awesome for my mobile webview application. Its fast, Ubuntu friendly and easy to edit. 
But, i really want to know how i can add the full content of an article.

I am using version 1.6.3

Thanks,

Geozznl

**Comment by Alkarex** [comment]
See a rough documentation in "Retrieve a truncated stream" http://doc.freshrss.org/en/users/05_Configuration/
Otherwise, you can use a bridge (can be self-hosted) such as https://github.com/RSS-Bridge/rss-bridge

**Comment by GeoZzNL** [comment]
Thanks, ill try :)

**Comment by GeoZzNL** [comment]
Well, i did this before. This is an update per 1 hour, right? Its not working.... I've tried to add a cron to my normal cron job file, but this is also not working. I am a beginner in Ubuntu server (before Windows server)

thanks,,

**Comment by GeoZzNL** [comment]
The bridge is working awesome! For many things, its a great solution.
