### ISSUE TITLE
Actualising a particular feed is not retrieving all articles

### ISSUE THREAD

**Issue by neuralcpu** [FreshRSS/FreshRSS#1482]
When I actualise the feed http://www.pravdareport.com/export.xml, FreshRSS is not retrieving all articles.

I have checked the validity of the feed:
http://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fwww.pravdareport.com%2Fexport.xml

Which, in summary, presents the following message: "This feed is valid, but interoperability with the widest range of feed readers could be improved by implementing the following recommendations."

I've also checked the feed using Simplepie, which returns said articles:
http://simplepie.org/demo/?feed=http%3A%2F%2Fwww.pravdareport.com%2Fexport.xml

Other feeds on my system are working well.

**Comment by Alkarex** [comment]
Please give a try to this fix: https://github.com/FreshRSS/FreshRSS/pull/1483

It is a feed that provides a GUID (unique identifier per article), but that GUID is blank. In this case, SimplePie should fall-back to the next best option, but is not the case currently, except when forcing the use of a hash (which FreshRSS does not do):
* https://github.com/simplepie/simplepie/blob/9f5e1cd7a477daba9349cf75ef3c8589c0a770b8/library/SimplePie/Item.php#L211
* http://simplepie.org/wiki/reference/simplepie_item/get_id

**Comment by neuralcpu** [comment]
Great work. I'm a bit of a newbie to all this Github stuff so please excuse my resolution method if there's a better way. I copied the code to a new Entry.php and it resolved the problem.

**Comment by Alkarex** [comment]
Yes, there are better approaches, but what you did was fine when it is such as small change.
The changes are available in the [/dev branch](https://github.com/FreshRSS/FreshRSS/tree/dev) of FreshRSS. Please give it a try if you can.
