### ISSUE TITLE
No date sorting

### ISSUE THREAD

**Issue by GeoZzNL** [FreshRSS/FreshRSS#1484]
Hi everyone,

I am using FreshRSS for 2 weeks now. I have more than 400 articles now over more than 20 feeds. 

Issue: date sorting is half-working. Its shorts on date, but the feeds are orginazed in groups. 
See the preview: [http://i.imgur.com/6PafEqu.png]

thanks,

**Comment by Alkarex** [comment]
Hello,
Please give a try at the [/dev version of FreshRSS](https://github.com/FreshRSS/FreshRSS/tree/dev).
A better implementation of what you report has been done in https://github.com/FreshRSS/FreshRSS/issues/530
You can also read there about the more detailed behaviour.

**Comment by GeoZzNL** [comment]
Thank you. The file entry.php is different in /dev and 1.6.3, right?
I tried to change my version to the /dev version but that does not work

**Comment by GeoZzNL** [comment]
But i'll wait for 1.7

thanks

**Comment by Alkarex** [comment]
It would be nice to have testers of this feature in the /dev branch.
If you installed FreshRSS by ZIP then you can try this one https://github.com/FreshRSS/FreshRSS/archive/dev.zip

**Comment by GeoZzNL** [comment]
I only changed the file. I will install en test the dev version and let you know how it goes 👍

**Comment by GeoZzNL** [comment]
I've installed it, and its working! Date sorting is perfect now. But this was the first refresh.
I'll let you soon know how it goes with more feeds and articles 👍

**Comment by Alkarex** [comment]
Thanks for the feedback :-)
