### ISSUE TITLE
Menu is flying

### ISSUE THREAD

**Issue by GeoZzNL** [FreshRSS/FreshRSS#1485]
Hi everyone,

See the preview: ![preview](http://i.imgur.com/6PafEqu.png)
As you can see, my menu is doing strange things 👎 Any solution for this? I tried the extention 'fixed nav menu' but this one have a max height, so its scrolling in-menu, what i dont want. I want you to scroll down the full website to view more of the menu

Thanks

**Comment by Alkarex** [comment]
Looks strange indeed. Could you please give a try with another browser (just to ensure it is not something with your possible browser extensions)

**Comment by GeoZzNL** [comment]
Its in every browser.
This is because the extension 'Sticky Feeds'

Problem solved

**Comment by Alkarex** [comment]
@marienfressinaud I have never tested Sticky Feeds. Isn't it redundant with the now built-in column behaviour?

**Comment by marienfressinaud** [comment]
Yes probably, it is disabled on my instance so I guess I had the same problem!
