### ISSUE TITLE
Android app

### ISSUE THREAD

**Issue by GeoZzNL** [FreshRSS/FreshRSS#1486]
I am working on an android app in android studio. Currently i use a webview client for FreshRSS, but this limit my option. 

How do i make contact with FreshRSS? I've also made a project with the layout i want for FreshRSS Android app.

Thanks

**Comment by Alkarex** [comment]
See an example of Android app compatible with FreshRSS https://github.com/Alkarex/EasyRSS/ (unfortunately, I do not have enough time for it, so help / fork / re-use welcome). It is open source and on F-Droid https://f-droid.org/repository/browse/?fdid=org.freshrss.easyrss. You could consider contributing to this project instead on starting from scratch, or pick some bits for a new app.
You can interact from a client thanks to a FrehshRSS API, which is using the same conventions than Google Reader. See the links at the top of https://github.com/FreshRSS/FreshRSS/blob/master/p/api/greader.php

Related (some of it is in French):
* https://github.com/FreshRSS/FreshRSS/issues/328
* https://github.com/FreshRSS/FreshRSS/issues/443
* https://github.com/FreshRSS/FreshRSS/issues/522
* https://github.com/FreshRSS/FreshRSS/issues/704

**Comment by GeoZzNL** [comment]
Thank you, but i cant use this project in Android Studio.

What program do i need? 

Thanks

**Comment by Alkarex** [comment]
It was initially developed with Eclipse but should works fine in Android Studio too. What is the problem?

**Comment by GeoZzNL** [comment]
I still dont know why Android studio dont regonize this project. I will try it with Eclipse thanks

**Comment by GeoZzNL** [comment]
Eclipse is working 👍

**Comment by Alkarex** [comment]
@GeoZzNL Feel free to report on your progress if you have any :-)

**Comment by Alkarex** [comment]
* Table of compatible apps: https://github.com/FreshRSS/FreshRSS/pull/2942
* EasyRSS updated to Android Studio / Android 10: https://github.com/Alkarex/EasyRSS/pull/48
