### ISSUE TITLE
Affichage vide

### ISSUE THREAD

**Issue by Draky50110** [FreshRSS/FreshRSS#1487]
Hello.

Mon hébergeur a migré de serveur et... plus rien ne s'affiche dans mes instances FRSS.

Exemple : https://www.parisnormandie.eu/frss/p/i/
On voit bien 47 non lus mais rien ne s'affiche.

Le PHPInfo : https://gilles.wittezaele.fr/phpinfo.php

Une idée du souci ?

Merci.

**Comment by Alkarex** [comment]
Essayez de faire archivage / purger, et archivage / optimiser.
Si cela n'aide pas, regarder la base de données directement, en particulier la table _entry.

**Comment by Draky50110** [comment]
Elle est pleine, je veux dire, il faut regarder quoi dedans ?
Je peux faire un dump... cette instance n'est pas trop confidentielle.

Archivage/purge + optimiser n'a rien changé

**Comment by Draky50110** [comment]
Bon, c'est revenu...

Problème de cache ?
Y'a un moyen d'avoir un bouton à cliquer pour vider le cache côté script ?

Merci :)

**Comment by Alkarex** [comment]
* Côté client (navigateur), on peut faire un rafraîchissement forcé (control + F5 dans Firefox).
* Côté serveur (FrehshRSS), la moindre modification (changer un paramètre, marquer un article comme favori, purge...) annulent le cache. (Et dans la version /dev, le bouton rafraîchir de la page principale de FreshRSS fera une mise à jour un peu plus agressive que maintenant - tests de la version /dev appréciés).
* Il peut aussi y avoir des problèmes de cache au niveau de la base de données (le moindre changement type UPDATE ou INSERT devraient les annuler), proxy, etc.
