### ISSUE TITLE
Créer des sous-catégories

### ISSUE THREAD

**Issue by qwertygc** [FreshRSS/FreshRSS#1490]
Bonjour,
une idée dans les flux, c'est créer des sous-catégories. Actuellement, je donne des titres au format suivant : 
```catégorie : sous-catégorie : sous-sous-catégorie```
Je sais pas si c'est possible en OPML.
cordialement,
qwerty

**Comment by Alkarex** [comment]
Bonjour,
Oui, c'est possible en OPML. Mais FreshRSS ne gère pas nativement les sous-catégories et je ne pense pas que cela sera une priorité dans un futur proche. Cela serait un gros travail, pas dénué d'inconvénients (performances, thèmes, compatibilité clients mobiles...), pour des avantages relativement mineurs.  Voir https://github.com/FreshRSS/FreshRSS/issues/229 pour plus de détails

**Comment by squromiv** [comment]
TT RSS has multiple levels of categories (subcategories). 
![screen_2019 03 28 001](https://user-images.githubusercontent.com/15985877/55140383-a33dbd80-5140-11e9-89e1-20d9899085cb.png)

Is there any chance to have such a feature in FreshRSS?
![screen_2019 03 28 0012](https://user-images.githubusercontent.com/15985877/55140516-f0219400-5140-11e9-9010-28ca58890f33.png)

**Comment by Alkarex** [comment]
@squromiv We have discussed that a few times, and I do not think this is something we will do, at least not in the near future.
It would require a significant work, and would have negative impacts on performance, UI, and compatibility with other clients.
However, what we could do is to improve the search features we already have ("user queries"), to group feeds in multiple ways. If that interests you, please open another issue as I do not think we have one for that yet.

**Comment by squromiv** [comment]
It's a pity!
>We have discussed that a few times, and I do not think this is something we will do, at least not in the near future.
>
You wrote something like this some years ago, so I have thought, that the future has come. :-))
> what we could do is to improve the search features we already have ("user queries"), to group feeds in multiple ways.
>
Can you describe, how it would look like?

In addition, what do you think about separate search (live) in feed names?
![screen_2019 03 23 0016666888](https://user-images.githubusercontent.com/15985877/55155879-240cb180-5161-11e9-8796-743af34721d0.jpg)

**Comment by Alkarex** [comment]
It would be a new search facility, like `infeed:7,17,23,31` which allows browsing/searching in a list of feeds, and which can be saved as a user query. Not only for that, we should have a UI to help writing those advanced search queries to better take advantage of the existing search mechanisms we have.

A live search of the content of the page, e.g. the feeds themselves, sounds great. Please open a new issue for that

**Comment by Alkarex** [comment]
> It would be a new search facility, like `infeed:7,17,23,31` which allows browsing/searching in a list of feeds, and which can be saved as a user query.

That part has been implemented in https://github.com/FreshRSS/FreshRSS/pull/2892
