### ISSUE TITLE
Unknown error for feed

### ISSUE THREAD

**Issue by qwertygc** [FreshRSS/FreshRSS#1494]
Bonjour,
dans mes logs, j'ai le message d'erreur suivant  : 
```Unknown error for feed [http://www.metropolitiques.eu/spip.php?page=backend]```. Une idée pour savoir comment corriger ?

**Comment by Alkarex** [comment]
Le flux a quelques problèmes, mais ce n'est pas le cœur du problème
https://validator.w3.org/feed/check.cgi?url=http://www.metropolitiques.eu/spip.php?page=backend
Il semble y avoir un problème de paramètre curl, mais je n'ai pas encore trouvé.

**Comment by kevinpapst** [comment]
This feed works for me with the current dev version, probably was fixed with the change of the UserAgent? Could you retest @qwertygc ?

**Comment by Alkarex** [comment]
Confirmed to work at least in FreshRSS 1.9.0.
