### ISSUE TITLE
Obligé d'actualiser manuellement chaque flux.

### ISSUE THREAD

**Issue by alexandrepa** [FreshRSS/FreshRSS#1496]
Je ne comprend pas exactement pourquoi mais pour certains flux, surtout pour les flux avec lequel j'ai renseigné un sélecteur CSS personnalisé, si je clique sur l’icône actualiser les flux, il me dit que tous les flux sont à jour.
Cependant si je clique sur "actualiser" dans l'option d'un flux précis, il se met bien à jour.
Est-ce un comportement normal ?

Je découvre FreshRSS et tout marche parfaitement à part ce petit point.
Merci

**Comment by Alkarex** [comment]
Bonjour,
En rafraîchissement multiple (soit par cron, recommandé, soit en cliquant sur l'icône pour actualiser), seuls les flux qui n'ont pas été rafraîchis récemment sont considérés. Il y a un réglage global et un réglage par flux pour cette limite.
Lorsque vous actualisez un flux précis, ces réglages ne sont pas utilisés, mais il y a tout de même une limite de ~15 minutes.
Je vous recommande de mettre en place un cron en tâche de fond pour actualiser 1 ou 2 fois par heure https://github.com/FreshRSS/FreshRSS#example-on-debian--ubuntu

**Comment by alexandrepa** [comment]
Merci pour la précision, je voulais être sur de bien comprendre :)
