### ISSUE TITLE
Twitter keyword feed

### ISSUE THREAD

**Issue by GeoZzNL** [FreshRSS/FreshRSS#1499]
Hey everyone,

I'd like to have a twitter stream in my FreshRSS.

I want to have a live feed of a couple keywords like 'north korea' 'volcano' and more. Just because Twitter is the quickest way to share news. Its all uncensored and live.

I dont only want a feed of someones account, but the real search live feed. 

If you know what i mean. 

Greetz

**Comment by GeoZzNL** [comment]
Well, i read something here": https://github.com/RSS-Bridge/rss-bridge

I wil give this a try

**Comment by GeoZzNL** [comment]
Actualy, its working great! With a few bugs.

For Twitter keyword feed (and more): https://github.com/RSS-Bridge/rss-bridge

**Comment by Alkarex** [comment]
Can we close this issue then?

**Comment by GeoZzNL** [comment]
Yes, thanks.
