### ISSUE TITLE
Nasa RSS not working

### ISSUE THREAD

**Issue by GeoZzNL** [FreshRSS/FreshRSS#1500]
HI,

Nasa RSS is not working, what can i do?

https://www.nasa.gov/rss/dyn/breaking_news.rss

Validator:
http://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.nasa.gov%2Frss%2Fdyn%2Fbreaking_news.rss

**Comment by Alkarex** [comment]
This feed works fine on my instance. Please try again, and provide the more precise error message (in the logs) if it still fails.

**Comment by GeoZzNL** [comment]
This is the log: 

cURL error 7: [https://www.nasa.gov/rss/dyn/breaking_news.rss]

**Comment by Alkarex** [comment]
This corresponds to `CURLE_COULDNT_CONNECT`.
Try a `curl -v https://www.nasa.gov/rss/dyn/breaking_news.rss` from your server.

**Comment by GeoZzNL** [comment]
Thats working. I do get the articles via curl -v from my server

**Comment by Alkarex** [comment]
What about:
`curl -v -A 'FreshRSS/1.6.3 (Linux; http://freshrss.org) SimplePie/1.4-dev-FreshRSS' https://www.nasa.gov/rss/dyn/breaking_news.rss`

**Comment by GeoZzNL** [comment]
curl: (7) Couldn't connect to server
Network is not reachable

**Comment by Alkarex** [comment]
Ah, then it could be a symptom of having being banned (combination of IP + user-agent)

**Comment by GeoZzNL** [comment]
Okay, maybe it is because my cron. Its refreshing every 5 minutes.

While i actually never used this rss feed before

**Comment by GeoZzNL** [comment]
curl -v -A 'FreshRSS/1.6.3 (Linux; http://freshrss.org) SimplePie/1.4-dev-FreshRSS' https://www.nasa.gov/rss/dyn/breaking_news.rss 

Is actually working... i typed someting wrong

**Comment by GeoZzNL** [comment]
I have 100 feeds working now.. But many feeds like NASA (without bridge) and https://www.dalfsennet.nl/feed are not working (curl 6 or curl 7 error)

Do you know why i cant add some feeds? Sometime i have to wait a day, and then it works. Like yesterday.. I tried adding https://alarmeringen.nl/feeds/discipline/politie.rss but i get the curl 6 error, until today: its working..... 

Is this an error caused by my server? I guess, know something?

**Comment by Alkarex** [comment]
It is probably some connectivity issues. You can try increasing the `'timeout'` value in `./data/config.php`.
You can also try to (temporarily disable) `CURLOPT_SSL_VERIFYHOST` and `CURLOPT_SSL_VERIFYPEER` at the same place (see example of syntax in `./data/config.default.php`).

**Comment by Pazns** [comment]
@GeoZzNL 
A 5-minutes refresh frequency seems like a bad idea anyway.
It's common for high-traffic servers to have a policy where high-frequency connection attempts are rejected for the sake of public availability.

For example, primarily because of Youtube I update FreshRSS with a cron task only every 2 hours.
I have like 100 Youtube RSS subscriptions, and if I try to update faster than that my server will start to get some rejection errors from time to time.

**Comment by Frenzie** [comment]
@Pazns Just set the feed in question to "Do not automatically refresh more often than" 2h or some such (in "manage"). I have a cron job for… I think every 15 minutes? You can set a global maximum under Configuration → Archiving and the same on a per-feed basis.

![screenshot_2017-05-27_15-46-01](https://cloud.githubusercontent.com/assets/202757/26521866/a482fbcc-42f3-11e7-9a47-0b24646542ea.png)

My global maximum is something like 30 minutes or 1h, with some individual feeds at higher settings. In combination with the cron job that means individual feeds update semi-randomly.

**Comment by GeoZzNL** [comment]
Okay, is there another way to push breaking news? I just don't want to be late.

Thanks for the advice

**Comment by Pazns** [comment]
@GeoZzNL : 
@Frenzie proposition seems pretty good for your case.
Test some intervals and see how low you can go for a problematic feed and set its limit to this, so this feed doesn't mute you any more.

**Comment by marienfressinaud** [comment]
I'm closing this ticket, the problem wasn't one. Considering the question:

> Okay, is there another way to push breaking news? I just don't want to be late.

The only solution is to pass by the WebSub protocol (which FRSS supports), but it's on the behalf of the publisher to configure a hub.
