### ISSUE TITLE
Question: should we keep French documentation?

### ISSUE THREAD

**Issue by marienfressinaud** [FreshRSS/FreshRSS#1503]
This could be a drastic solution, but maintaining (two versions of) documentation is really painful. I'm working on moving https://github.com/FreshRSS/documentation repo under a `/docs` folder of the current repository as we discussed with @Alkarex and I'm questioning myself on the best way to ease future maintenance (as we saw that I was a really bad documenter 😊). Question can be controversial since most of the documentation is written in French.

What's your thoughts on this?

**Comment by marienfressinaud** [comment]
Here is a quick test to see how it will render http://marienfressinaud.github.io/FreshRSS/

Good news: most of the links are working (images included!). The process only has to be adapted and some links to the https://github.com/FreshRSS/documentation repository must be changed.

**Comment by Alkarex** [comment]
It would be nice to have some statistics / feedback to see where our efforts are best spent, but I do not know how to obtain that. Maybe through or renewed communication.
I suggest we put links from one language to another when sections are available in only one language, and re-assess the situation when the new system has been in place for a little while. I hope the new structure will help a bit with the contributions.

**Comment by Alkarex** [comment]
P.S. It looks very good :-)

**Comment by GeoZzNL** [comment]
Hi Alkarex and marienfressinaud,

I am from the Netherlands and use the English documentation. For me, i dont use the French documentation but for French people it might be good. 

If you like, i can translate the English documentation to Dutch, Maybe you like to extend your international reach. I think it's good to have multiple languages 👍 

I am using FreshRSS for a little 2 months now, and i can tell you, you make great stuff, I really like to do something back for you. Maybe there are more people who want to do this in their language

**Comment by Alkarex** [comment]
Thank you for your kind message @GeoZzNL 👍 
Your help would be much welcome in different domains:
* For instance, running the /dev version and reporting bugs is already good.
* Sending patches for the Dutch translation of FreshRSS is also appreciated, especially when there is a need to translate some new things.
* For the documentation, we would also need help to improve the English version. Could you be motivated enough to have a look?
* And finally, yes, if we have enough man-power, translations in other languages would be nice, at least of some main features, but I would rather like to complete an English reference first.

**Comment by marienfressinaud** [comment]
I took a look to the server stats (from awstats) and most of the consulted documentation pages are in English. But after few consideration and a part of my evening working on the new documentation website, I'm a bit more confident on maintaining both versions (English and French).

I changed the theme on http://marienfressinaud.github.io/FreshRSS/, added a link to home page on the title and translated English main page: http://marienfressinaud.github.io/FreshRSS/en/

I would like to work on a simpler structure with less pages than before but first I will try to finish the migration :). Also I should be able to keep the previous URLs alive.

I'll try to find a way to add an automatic link to switch between available languages but I really don't know how to do that… probably through a small Jekyll plugin?

@GeoZzNL you are very welcome to help! :) As @Alkarex said, it would be nice to finish English documentation. And as I wrote few lines above, I would like to work on a simpler documentation's structure (with less pages and, most of all, less "TODO" in the documentation). Can I ask you what you expect from the documentation?

**Comment by GeoZzNL** [comment]
@Alkarex nice, i will try the dev version every time you update it.
I will also try to update the Dutch translation of the website. I will try to get it finished for 1.7.0. Can you give me a hint? Should i translate all English strings or the French? -> Witch one is the most complete? 

@marienfressinaud @Alkarex English is not my mother language. I really want to help you to translate the documentation to English, but i don't think i am the right person to do this. 

What i can do for you: 
- Translate the website to Dutch (Netherlands), Dutch (Belgium)
- Translate the documentation to Dutch (Netherlands), Dutch (Belgium)
- Test the dev version every time you update it 
- Translate EasyRSS (Android app, its yours, right?) to Dutch (Netherlands), Dutch (Belgium)

If you update EasyRSS i will test the dev version

**Comment by psukys** [comment]
This might be a late question, but why not use a documentation service like [readthedocs.io](https://readthedocs.io)? It would minimize the effort needed to maintain the documentation (has a neat approach and gives broad functionality in general)

**Comment by Frenzie** [comment]
Since the French documentation is already there I think it would be a real waste to see it go, but unfortunately I don't yet have any answers for how to internationalize documentation. I will be keeping a close eye on this issue with regard to KOReader, see [here](https://github.com/koreader/koreader/issues/1371#issuecomment-292709199).

The main objection raised to RTD was:

> RTD requires the doc to be written in python tooling and managed by git. In that case, it would be more flexible for us to just setup the automated doc build in gitlab CI.

**Comment by aledeg** [comment]
Not related to the topic directly but as the doc moved here instead of its own repository, couldn't we use the Github wiki pages?

**Comment by Frenzie** [comment]
The only real upside of GH wiki is that it's easy to edit if you have a GH account, which means it's easy for anyone to contribute. But trust me when I say it's pretty terrible to organize.

**Comment by aledeg** [comment]
There is an option to only allows people that have write access to the repository. But if it's a mess, I'd rather stay away from that :)
Thanks for the insight

**Comment by marienfressinaud** [comment]
The idea of moving documentation directly in the main repository was to keep source code and documentation as close as possible (we can create PR including documentation). It is now directly accessible on http://freshrss.github.io/FreshRSS/ (I have to make it accessible through doc.freshrss.org now). I totally agree with @Frenzie on GH wiki ;).

Since GH pages are generated with [Jekyll](https://jekyllrb.com/), I think we can find a way to facilitate navigation between languages.
