### ISSUE TITLE
Problem showing share option

### ISSUE THREAD

**Issue by GeoZzNL** [FreshRSS/FreshRSS#1506]
Hi there,

As you can see, i have some trouble with the share options. Its it out of the screen.

This is not in every width. Its only on phones

![image](https://cloud.githubusercontent.com/assets/12541266/25336070/1ffb9c04-28f6-11e7-8e5b-1ffc6fb911ee.png)

![image](https://cloud.githubusercontent.com/assets/12541266/25336128/625ab742-28f6-11e7-81e0-eef0719892f5.png)

I think it has to do something with a fixed style or something, but i cant find the right code to edit.
I also disabled all extensions, but this does not work.

Do you already know the wrong, and the solution? I maybe know the problem, but cant find the right file to edit

Thanks

**Comment by Alkarex** [comment]
You are almost at the right place. I think it is the style of `.dropdown.menu` that needs to be fixed for mobile views.

![image](https://cloud.githubusercontent.com/assets/1008324/25336551/54931c42-28f8-11e7-9cde-492535994342.png)

**Comment by GeoZzNL** [comment]
I actually already tried that. But when i change the position to fixed, the box is not showing anymore. When i change it to static, this happen: 

![image](https://cloud.githubusercontent.com/assets/12541266/25336764/4ffbfa7c-28f9-11e7-80d8-c7f7a2614dcf.png)

All other positions are not working

**Comment by Alkarex** [comment]
I think one needs to add a rule for small screens (e.g. `@media all and (min-width:XXX) {}`) and redo the styling of the drop-down menu in that case.

**Comment by Alkarex** [comment]
@GeoZzNL Could you please give a try to the /dev version of FreshRSS, or try this patch https://github.com/FreshRSS/FreshRSS/pull/1645 and confirms whether it fixes your problem?
