### ISSUE TITLE
Question : y a-t-il des migrations de BDD à appliquer entre les différentes versions ?

### ISSUE THREAD

**Issue by ddevaux** [FreshRSS/FreshRSS#1507]
Je souhaiterais automatiser les mises à jour de FreshRSS sur mon serveur. Pour cela je compte utiliser un répertoire versionné par git, et faire tourner un cron hebdomadaire.

Or, en plus de mettre à jour les fichiers, faut-il appliquer des migrations à la base de données ? (par exemple, c'est le cas avec Drupal où il faut appeler update.php ou exécuter la commande `drush updatedb` après les montées de version)

Si oui, peut-on le faire en ligne de commande ?

**Comment by Alkarex** [comment]
Bonsoir,
Depuis au moins une douzaine de versions, un simple `git pull` suffit pour faire la mise à jour.
Il n'est pas impossible qu'un script de mise à jour doive être appelé dans le futur, mais si c'est le cas, je compte faire en sorte que ce soit aussi automatique.
Ticket en relation : https://github.com/FreshRSS/FreshRSS/issues/907

**Comment by Alkarex** [comment]
P.S. Il y a la branche /master et la branche /dev . La branche /dev est bien sûr moins stable mais tout à fait utilisable (c'est ce dont je me sers moi-même, et les patchs n'y sont inclus qu'après un minimum de test). De plus, il serait appréciable d'avoir plus de testeurs de /dev :-)

**Comment by ddevaux** [comment]
Merci pour ces précisions
