### ISSUE TITLE
Cron not working after latest dev installation

### ISSUE THREAD

**Issue by GeoZzNL** [FreshRSS/FreshRSS#1509]
I installed the latest dev vesion but now has cron stopped working.

This is the output:

Starting feed actualization at 2017-04-26T17:00:01+02:00
Actualize AdminFreshRSS...
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS/data/users/AdminFreshRSS/log.txt because Permission denied in /var/www/FreshRSS/lib/lib_rss.php on line 292
PHP Warning:  file_put_contents(/var/www/FreshRSS/data/users/AdminFreshRSS/log.txt): failed to open stream: Permission denied in /var/www/FreshRSS/lib/Minz/Log.php on line 73
PHP Warning:  file_put_contents(/var/www/FreshRSS/data/users/AdminFreshRSS/log.txt): failed to open stream: Permission denied in /var/www/FreshRSS/lib/Minz/Log.php on line 73
Results: 
AdminFreshRSS ### Application problem ###<br />
Permission is denied for `/var/www/FreshRSS/data/users/AdminFreshRSS/log.txt`

I tried some commands to change the write/read permission, but those did not work

**Comment by GeoZzNL** [comment]
The log of my users are empty? While i normally get many error from PubHubSubbub

**Comment by Alkarex** [comment]
As you can see, it is a problem with permissions. Remember that your user and the Web server user are typically not the same. I suggest you reset the rights. Example to adapt:

```sh
cd /var/www/FreshRSS
sudo chown -R :www-data . && sudo chmod -R g+r . && sudo chmod -R g+w ./data/
```

**Comment by GeoZzNL** [comment]
Its working! Thanks. I still have to do my linux study 💯

**Comment by GeoZzNL** [comment]
Today, its down again.... the code you send me is working, but after every restart it will be denied

**Comment by Alkarex** [comment]
If you have a cron job, be careful which use is used to run it. Can you show your cron file again?

**Comment by GeoZzNL** [comment]
0,5,10,15,20,25,30,35,40,45,50,55 * * * * www-data php -f /var/www/FreshRSS/app/actualize_script.php > /tmp/FreshRSS.log 2>&1

**Comment by GeoZzNL** [comment]
I just did a cron restart, and restarted my server again, but it is denied again

**Comment by GeoZzNL** [comment]
Remember, this is after the latest dev update

I will set-up a fresh installation of 1.6.3 to check if it is my server or FreshRSS

**Comment by Alkarex** [comment]
When it is not working, please check the rights of the problematic file:
```sh
ls -alh /var/www/FreshRSS/data/users/AdminFreshRSS/
```

**Comment by GeoZzNL** [comment]
Cron is working after complete re-install of mysql, php7, Cron, freshrss dev and 1.6.3.

All working great now. It was a server-side error i guess. But dont exactly know what is was
