### ISSUE TITLE
Cannot login via Edge

### ISSUE THREAD

**Issue by GeoZzNL** [FreshRSS/FreshRSS#1511]
![image](https://cloud.githubusercontent.com/assets/12541266/25482738/50e67640-2b53-11e7-8f2a-7f51f5095a59.png)
![image](https://cloud.githubusercontent.com/assets/12541266/25482751/5a2dc41a-2b53-11e7-9e80-0be4e29a4b22.png)
![image](https://cloud.githubusercontent.com/assets/12541266/25482758/61e61996-2b53-11e7-8f77-b245455af4b8.png)

Logging is does not work in Microsoft Edge. Evey time i press a second letter, the bar turns red

**Comment by Alwaysin** [comment]
Same here.

Error message:

```
You must use this format:
```

(yes, it is empty!)

I also have these errors in the console, which might be linked:

```
CSP14321: Resource violated directive 'default-src 'self'' in Content-Security-Policy: inline style, in http://<freshrss>/i/ at line 3 column 7. The resource will be blocked.
CSP14321: Resource violated directive 'default-src 'self'' in Content-Security-Policy: inline style, in http://<freshrss>/i/ at line 4 column 7. The resource will be blocked.
CSP14321: Resource violated directive 'default-src 'self'' in Content-Security-Policy: inline style, in http://<freshrss>/i/ at line 4 column 7. The resource will be blocked.
```

**Comment by Alkarex** [comment]
I think the bug was introduced in version 1.6.3 https://github.com/FreshRSS/FreshRSS/pull/1423
Patch coming

**Comment by Alkarex** [comment]
* http://stackoverflow.com/questions/22360235/do-browsers-support-different-html5-pattern-regexp-features
* https://connect.microsoft.com/ie/feedback/details/836117/regex-bug-in-pattern-validator

**Comment by Alkarex** [comment]
Should be fixed in https://github.com/FreshRSS/FreshRSS/pull/1512
Please pull newest /dev branch and give it a try.
For the record, it is a IE / Edge bug.

**Comment by GeoZzNL** [comment]
Thanks for the help
