### ISSUE TITLE
Problème avec Easy RSS

### ISSUE THREAD

**Issue by jgachelin** [FreshRSS/FreshRSS#1515]
Bonjour,

J'ai vu beaucoup d'issues différentes à ce sujet, sans réussir à régler le mien : j'ai un problème de connexion avec EasyRSS. Voici les détails : 
- Nginx 1.13.0
- Certificat Let's Encrypt
- Configuration HTTPS [visible ici](https://www.jgachelin.fr/vrac/config_tls.png).
- FreshRSS en version 1.6.3, "Freshment" installé.
- "Allow API Access" -> coché, j'ai vérifié dans data/config.php c'est bien à "true" pour "api_enabled".
- "API Password" -> défini, j'ai vérifié dans data/users/monUser/config.php, il y a bien un hash pour ApiPasswordHash et il change quand il est modifié via l'interface utilisateur.
- Je renseigne bien l'adresse de l'API sur EasyRSS (https://rss.monserver.tld/p/api/greader.php)
- Quand je vais dans /p/api/ **j'ai un problème** : j'ai un 404 not found sur les **2** liens (full et partial). Est-ce que ça joue ?

Lorsque je fais une tentative de connexion via EasyRSS, il me dit un "login failed, please check your username and password". La configuration côté tablette Nexus 7 et identique sur smartphone LG G3 :
- EasyRSS 0.6.06 (depuis F-Droid)
- LineageOS 14.1 (Android 7.1.1)

Mon installation précédente avec VPS Ubuntu + Apache + Let's Encrypt fonctionnait. Là avec un VPS Debian + Nginx + Let's Encrypt, ça ne fonctionne plus. Je me demande si ça pourrait venir du serveur web (la config HTTPS notamment) mais je n'en suis pas sûr.

J'ai vérifié dans /data/users/_/log_api.txt : rien n'apparaît (sauf si je vais avec mon navigateur sur greader.php il me dit que c'est une mauvaise requête, forcément). log.txt du même répertoire est vide. Dans /data/user/monUser/log.txt n'affiche que des erreurs sur certains flux RSS. Et il n'y a absolument aucun message d'erreur dans mon répertoire /var/log/nginx/ à ce propos, et j'ai bien vérifié la configuration de mon sous-domaine, c'est là qu'il écrit les logs d'erreur.

Du coup je n'ai aucune erreur me permettant de trouver une solution à ce problème. Comment faire ? J'espère avoir été assez précis :-)

**Comment by Alkarex** [comment]
Bonjour,
Il semble qu'il y ait deux problèmes différents.

Pour l'API : Si les tests de /p/api/ ne marchent pas, un client ne pourra pas fonctionner. Vérifiez en particulier la partie `fastcgi_param PATH_INFO` de votre configuration nginx. Voir par exemple https://github.com/FreshRSS/FreshRSS/issues/957#issuecomment-134346342

Pour l'HTTPS : Vérifiez si vous avez bien des lignes dans vos logs nginx lorsque vous accédez à `/p/api/` et `/p/api/greader.php` via votre navigateur (note au passage : pointez plutôt votre racine nginx sur le répertoire `./FreshRSS/p/` afin d'avoir des adresses du style `https://rss.monserver.tld/favicon.ico` et `https://rss.monserver.tld/api/greader.php`. Si vous faites des changements manuels, attention de bien corriger `base_url` dans `./FreshRSS/data/config.php`).
Vérifiez que vous pouvez bien accéder à votre FreshRSS par l'interface Web via le navigateur par défaut de votre téléphone (qui s'appelle souvent simplement *Internet*).
Ensuite, lorsque vous essayez depuis EasyRSS, si vous voyez quelque chose dans vos logs, comme une erreur 404, alors ce n'est pas un problème de HTTPS. Si vous ne voyez rien, il y a probablement un problème HTTPS. Pour confirmer, essayez alors d'activer temporairement le HTTP (sans S).

**Comment by jgachelin** [comment]
Bonjour,

J'ai modifié mon fichier Nginx en prenant pour exemple celui présenté par l'issue #957, tout d'abord en ajoutant la ligne : 
`fastcgi_param PATH_INFO $2;`
Qui n'était pas présente, puis en commentant cette ligne : 
`#try_files $uri=404;`
J'obtenais alors un "access denied" en résultat, après rechargement de la configuration. J'ai de nouveau comparé l'exemple de l'autre issue, puis j'ai rajouté la ligne : 
`fastcgi_read_timeout 900s;`
Et j'ai aussi remplacé cette ligne par la suivante : 
`fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;`
`fastcgi_param SCRIPT_FILENAME $document_root$1;`
Et après un rechargement de la configuration, j'obtiens le "PASS" sur les deux tests ainsi que le bon fonctionnement avec l'application EasyRSS !

Je savais que c'était un truc tout bête, et qu'il y avait des chances que ça vienne de ma config Nginx plutôt que de la configuration de FreshRSS en elle-même... 

Pour répondre à l'autre question, j'avais essayé d'accéder avec succès à FreshRSS depuis Firefox sur mon smartphone, car j'avais lu que le problème, sur d'anciennes versions d'Android pouvait venir de l'acceptation de certains certificats, surtout vu que je n'utilise que TLS 1.2.

Merci en tout cas pour l'aide efficace et rapide !

**Comment by Alkarex** [comment]
Super :-) Pour référence, pourriez-vous poster votre configuration nginx finale ?

**Comment by jgachelin** [comment]
Voici ma config Nginx, en prime certifiée A+ en HTTPS par SSLLabs (https://www.ssllabs.com) et CryptCheck (https://tls.imirhil.fr/) : 
```
# HTTP / rss.domaine.tld
server {
	listen 80;
	listen [::]:80;
	server_name rss.domaine.tld;

	#root /home/web/www/domaine.tld/rss;
	#index index.html index.php;

	return 301 https://rss.domaine.tld$request_uri;
}

# HTTPS / rss.domaine.tld
server {
	# Configuration générale
	listen 443 ssl http2; # IPv4
	listen [::]:443 ssl http2; # IPv6
	server_name rss.domaine.tld;
	root /home/web/www/domaine.tld/rss;
	index index.html index.htm index.php;

	# Logs
	access_log /var/log/nginx/rss.domaine.tld.acc.log;
	error_log /var/log/nginx/rss.domaine.tld.err.log;

	# Configuration SSL
	ssl_protocols TLSv1.2;
	ssl_certificate /etc/letsencrypt/live/rss.domaine.tld/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/rss.domaine.tld/privkey.pem;
	ssl_trusted_certificate /etc/letsencrypt/live/rss.domaine.tld/chain.pem;
	ssl_ecdh_curve secp384r1;
	ssl_ciphers EECDH+AESGCM:EECDH+CHACHA20:EECDH+AES;
	ssl_prefer_server_ciphers on;
	ssl_stapling on;
	ssl_stapling_verify on;
	ssl_session_cache shared:SSL:10m;
	ssl_session_timeout 5m;
	ssl_session_tickets on;

	location / {
		try_files $uri $uri/ =404;
	}

	location ~ /\.ht {
		deny all;
	}

	location ~ \.(ht|sql|bat|git|ini|sh|svn[^.]*|tpl)$ {
		deny all;
	}

	location ~ ^(.+?\.php)(/.*)?$ {
		include fastcgi_params;
		fastcgi_pass 127.0.0.1:9000;
		fastcgi_param PATH_INFO $2;
		fastcgi_index index.php;
		fastcgi_param SCRIPT_FILENAME $document_root$1;
		fastcgi_read_timeout 900s;
	}

	location ~ /.well-known {
		allow all;
	}

	# OCSP Stapling
	resolver 80.67.169.12 80.67.169.40 valid=300s;
	resolver_timeout 5s;

	# HSTS
	add_header Strict-Transport-Security "max-age=15552000; includeSubdomains; preload";
}
```
