### ISSUE TITLE
Update Error via Git

### ISSUE THREAD

**Issue by HalfEatenPie** [FreshRSS/FreshRSS#1518]
Howdy!

I'm currently having an issue with the FreshRSS installation.  

We were using 1.3.0 for the longest time.  Recently I updated it via the automated update tool but we hit a snag.

**Background:** Automated update system updated from 1.3.0 to 1.4.0.  

**Problem:** Automated update system had a git error from 1.4.0 to 1.6.3.  

    The update process has encountered an error: Git error: Updating 7bc2ff4..9765654

**Error log shows:**

    error: Your local changes to the following files would be overwritten by merge:

Then multiple files (mostly related to postgreSQL but also others). 

**Environment:**
Base OS is Ubuntu 14.04 64-bit
PHP version is 5.5.9
Datastore is MySQL version 14.14
Using Apache2 with aliases so "/freshrss"

**Additional Information:**
While updating failed with an error, the "current version number" is reported as 1.6.3.  

From my initial glance and search I haven't found any issues related to the automated update system with my problem.  Or have I missed something?  

Thanks!

**Comment by Alkarex** [comment]
Hello,
If you have installed FreshRSS by git, you can also update it via git. Back-up any change you might have done and then run something like:

```sh
cd /usr/share/FreshRSS
sudo git reset --hard
sudo git pull
sudo chown -R :www-data . && sudo chmod -R g+r . && sudo chmod -R g+w ./data/
```

**Comment by Alkarex** [comment]
Closing, but feel free to ask again if needed
