### ISSUE TITLE
notice in apache log

### ISSUE THREAD

**Issue by oupala** [FreshRSS/FreshRSS#1519]
I just noticed a notice in apache log:

```log
[Wed May 03 17:54:33.211576 2017] [:error] [pid 21323] [client 161.106.4.5:64869] PHP Notice:  Undefined index: cookie_duration in /home/user/FreshRSS-1.6.3/app/Controllers/authController.php on line 118
```

**Comment by Alkarex** [comment]
Could you please check that your file `data/config.default.php` contains the corresponding entry, just like:
https://github.com/FreshRSS/FreshRSS/blob/1.6.3/data/config.default.php#L78

Please check also `data/config.php`.

**Comment by oupala** [comment]
On my production instance, there is no cookie parameter in the config file, nor on the template config file.

```bash
FreshRSS-1.6.3/data>grep -i cookie config*
FreshRSS-1.6.3/data>
```

It might be because I upgraded from previous version. Is there something special to do when upgrading the version of FreshRSS?

On my dev instance, I'm reinstalling FreshRSS from scratch on a regular basis. There is some cookie parameters on the template config file, but nothing in the real config file, automatically generated via the install CLI script.

```bash
FreshRSS-1.6.3/data>grep -i cookie config*
config.default.php:		# Duration in seconds of the login cookie.
config.default.php:		'cookie_duration' => 2592000,
```

I don't think these two situations are normal, do you?

**Comment by Alkarex** [comment]
It is fine not to have all values in `config.php`, since default values are taken from `config.default.php`.
But if `config.default.php` does not contain all values, then there has been a problem during update.
Which update method did you use?

**Comment by oupala** [comment]
Ok, two points:

- in order to fix the potential update problem, I just need to overwrite the `config.default.php` from a recent version, right?
- I don't remember exactly how I updated the code, probable erasing the freshrss directory en deploying the new tar (the data directory is symlinked and stored somewhere else). By the way I haven't found in the [documentation](http://doc.freshrss.org/fr/users/01_Installation/) how to upgrade FreshRSS. What is the *standard* way to do this?

**Comment by Alkarex** [comment]
Yes, `config.default.php` is supposed to be updated with new version, so you need to take a newer one if for some reason it was not updated.
There are multiple ways to update FreshRSS:
* I personally update via git as documented in the readme https://github.com/FreshRSS/FreshRSS#example-of-full-installation-on-linux-debianubuntu (see also https://github.com/FreshRSS/FreshRSS/issues/1518#issuecomment-298982817 ) and this will also work from the update menu of the Web interface.
* If installed by FTP / ZIP, then the update menu of the Web interface is offering an automatic ZIP-based update
* There are distributions, e.g. via YunoHost, DPlaform, Cloudron, which have their own update mechanism.

**Comment by oupala** [comment]
In my opinion, if `config.default.php` should be updated with FreshRSS update, it does not belong to user data, and hence **should not be present in `data` directory. It should be along the code**, somewhere else. In my case, the data directory is outside FreshRSS's directory (and symlinked) to that I can update FreshRSS source code without any risk of erasing my user data.

The automatic zip-based update is not working in my case. I get an error displayed on the page:

> Système de mise à jour
> 
> ⓘ Votre version actuelle de FreshRSS est la 1.6.3.
> 
> Dernière vérification : 16 décembre 2015 à 12:27
> 
> Arf ! Veuillez vérifier les droits sur le répertoire /home/ops/apps/FreshRSS-1.6.3. Le serveur HTTP doit être capable d’écrire dedans

And finally, update process is not well documented in the documentation. I think this is an important feature, which should be documented, and is currently lacking.

**Comment by Alkarex** [comment]
Good point with moving `config.default.php` out of the `./data/` folder. Could you please open a new issue for that? The git update process is well documented in the README, the other types of updates not as well.
Related issues: https://github.com/FreshRSS/FreshRSS/issues/861 https://github.com/FreshRSS/FreshRSS/issues/907

**Comment by Alkarex** [comment]
P.S.: The ZIP-based update cannot work if it cannot write in your FreshRSS directory. This is the error you have.

**Comment by oupala** [comment]
I will open a new issue for config file location.

For the update, I understand that FreshRSS should have write access to its own tree in order to update itself. But for checking, it should not require write access on the whole. I already mentionned this issue in #1450 

There is a large difference between upgrading a software, and just checking if there is a new release available.

**Comment by oupala** [comment]
I will open a new issue for config file location.

For the update, I understand that FreshRSS should have write access to its own tree in order to update itself. But for checking, it should not require write access on the whole. I already mentionned this issue in #1450

**Comment by Alkarex** [comment]
I think the original issue is solved. Let's use dedicated issues for any remaining point.
