### ISSUE TITLE
Option to show "No more unread" instead of all unread items

### ISSUE THREAD

**Issue by uncovery** [FreshRSS/FreshRSS#1520]
It would be great if the system could show a message along the lines of "No more unread items" when all newsfeeds are read instead of showing all the unread items. 

This could be a switchable option of course.

**Comment by Alkarex** [comment]
Try to check the "articles to display" option
![image](https://cloud.githubusercontent.com/assets/1008324/25735885/c714dbec-316e-11e7-9049-87f2086e035a.png)

**Comment by uncovery** [comment]
Thanks!
