### ISSUE TITLE
Data folder permission CentOS

### ISSUE THREAD

**Issue by GeoZzNL** [FreshRSS/FreshRSS#1524]
Hi,

Some friends told me to try CentOS instead of Ubuntu because i have some troubles with Ubuntu 16.04. So i am testing it now, but i have a problem with FreshRSS. Download and everything worked, almost everything is the same to ubuntu but i cant get permission to the data folder.

Path to FreshRSS: /var/www/html/FreshRSS
Tried chmod and chown for apache:apache and root:root user:user but none works.

apache is www:data in CentOS.

Error on step 1:
Damn! Check permissions on ./data directory. HTTP server must have rights to write into
Damn! Check permissions on ./data/cache directory. HTTP server must have rights to write into
Damn! Check permissions on ./data/users directory. HTTP server must have rights to write into
Damn! Check permissions on ./data/favicons directory. HTTP server must have rights to write into

**Comment by Alkarex** [comment]
I do not know whether this is the problem, but CentOS has SELinux enabled (Security-Enhanced Linux), which requires a bit more care.
I think @marienfressinaud is using / has used CentOS, and might have some tips.

**Comment by Alkarex** [comment]
https://blog.lysender.com/2015/07/centos-7-selinux-php-apache-cannot-writeaccess-file-no-matter-what/

**Comment by GeoZzNL** [comment]
I already visited this site, but it doesn't work. 
I have a clean install with the error i showed you above and a old installation from ubuntu with this error after loging in:
Permission is denied for `/var/www/html/FreshRSSold/data/users/AdminFreshRSS/log.txt`
i think this is the same error

What should you do in Ubuntu? Maybe can i translate it to CentOS. Its both linux :P

I checked every file, and apache (www-data) is the owner of everything

**Comment by Alkarex** [comment]
On Ubuntu, having write permissions for the Web server user is enough. See e.g.
https://github.com/FreshRSS/FreshRSS#example-of-full-installation-on-linux-debianubuntu
On CentOS, you also have to ensure that SELinux rules are correct.

**Comment by marienfressinaud** [comment]
Ah… I configured my server when disabling SELinux was not shameful. I can't suggest you to do the same since it would mean lowering the security of your server, but that's probably the reason why it works for me ;)

**Comment by GeoZzNL** [comment]
Its been a while for me. I have moved to somewhere else. 
I installed Ubuntu again because CentOS wasn't working. On ubuntu 16.04 is everything fine

**Comment by Alkarex** [comment]
Thanks for the feedback @GeoZzNL 
Let's close it for now, but if someone has the problem / solution, feel free to comment here.

**Comment by ngoomie** [comment]
This may be an unrelated issue that looks the same on the surface, but I was experiencing issues with FreshRSS being able to access the data folder despite having the right permissions on Fedora 35 with nginx + php-fpm, and it seems that, very weirdly, php-fpm being barred from using the net_admin capability is what was causing the issue.

I genuinely don't understand why php-fpm being disallowed from use of net_admin capability is causing this as it seems to be an entirely unrelated capability, with it being related to modifying network settings, but considering granting it net_admin usage fixed everything, I... guess it is? I'll admit I don't have that great of an understanding of Linux capabilities so there could be something I'm missing that makes this make more sense.
