### ISSUE TITLE
Craigslist RSS not working

### ISSUE THREAD

**Issue by am517** [FreshRSS/FreshRSS#1525]
Hello!

I can't get a craigslist rss to work.

http://tokyo.craigslist.jp/search/jjj?format=rss

on the same server these all work:

- wget http://tokyo.craigslist.jp/search/jjj?format=rss
- curl -L http://tokyo.craigslist.jp/search/jjj?format=rss
- curl -L -A 'FreshRSS/1.6.3 (Linux; http://freshrss.org) SimplePie/1.4-dev-FreshRSS' http://tokyo.craigslist.jp/search/jjj?format=rss

I tried changing curl_options in the config.php but only the error changes (I can't see how to make the errors more verbose)

- [Mon, 08 May 2017 01:38:10 +0000] [warning] --- cURL error 28: Operation timed out after 12499 milliseconds with 2730 out of 4518 bytes received [http://tokyo.craigslist.jp/search/jjj?format=rss]
- [Mon, 08 May 2017 02:24:44 +0000] [warning] --- Unknown error for feed [http://tokyo.craigslist.jp/search/jjj?format=rss]

I must be doing something wrong.... any ideas? Thanks :)

edit: I also changed the timeout 10x longer in config.php 
`'timeout' => 150,`

edit 2: there must have been a cache issue? Came home from an errand and now the feed is loading - `'timeout' => 150,` is the only change I kept

**Comment by Alkarex** [comment]
This feed works fine from my server. But it looks like it was a timeout problem indeed.

**Comment by adamrabbit** [comment]
Yes. I have a strange setup - LXC in Virtualbox behind VPN. It's probably not the fastest, but it works. Thanks again!
