### ISSUE TITLE
Display of "There are new available articles..." is inconsistent

### ISSUE THREAD

**Issue by uncovery** [FreshRSS/FreshRSS#1529]
When you have "Articles to display" set to "Adjust showing", and in the background new items are received, a blue bar appears on the top ("There are new available articles...") telling you about it. This is independent if you still have unread items or not.

When you have "Articles to display" set to "Unread", and in the background new items are received, the blue bar is shown while there are still unread items, but not if there are no more. If there are no more items unread, the fact that there are new unread items loaded in the background is only visible by the fact that the browser tab icon shows the number of new unread items. 

It would be great if the blue bar is automatically shown, no matter what the status of unread items is.

**Comment by Alwaysin** [comment]
Same issue in french: https://github.com/FreshRSS/FreshRSS/issues/617

**Comment by math-GH** [comment]
Should be fixed in V.19.0 via #3999

ping: @uncovery  Could you please check?

**Comment by uncovery** [comment]
Sorry, I am not using this anymore, cannot confirm.
