### ISSUE TITLE
config.default.php should be  along the code

### ISSUE THREAD

**Issue by oupala** [FreshRSS/FreshRSS#1531]
In my opinion, if `config.default.php` should be updated with FreshRSS update, it does not belong to user data, and hence **should not be present in `data` directory. It should be along the code**, somewhere else. In my case, the data directory is outside FreshRSS's directory (and symlinked) to that I can update FreshRSS source code without any risk of erasing my user data.

**Comment by Alkarex** [comment]
Addressed in https://github.com/FreshRSS/FreshRSS/pull/1532

**Comment by oupala** [comment]
Great !

You should also mention in the changelog or somewhere in the update instructions to remove the existing `config.default.php` file from the `USERS_PATH`.

**Comment by Alkarex** [comment]
Moving the old files should be done automatically by `git pull` or the future ZIP update.

**Comment by Alkarex** [comment]
There is a note in the changelog https://github.com/Alkarex/FreshRSS/commit/68d3deee1e1d5480bff1a61547188576e13ffcb4

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/issues/1519
