### ISSUE TITLE
exclude inurl keywords seems not working

### ISSUE THREAD

**Issue by disanvparean** [FreshRSS/FreshRSS#1533]
Hello,
First of all, thank you for your amazing piece of work.
It seems from the documentation it's possible to exclude some parameters in search.
For example, if I want to exclure "twitter" inurl the syntax is "-inurl:twitter".
It's not working, It displays all items with twitter in the URL, not the opposite. Am I missing something ?
I tried with ! it's not working neither.
I use the last version. 
Thanks a lot

**Comment by Alkarex** [comment]
Hello @disanvparean 
This is a new feature of the upcoming version 1.7 https://github.com/FreshRSS/FreshRSS/blob/dev/CHANGELOG.md#2017-xx-xx-freshrss-170-dev
https://github.com/FreshRSS/FreshRSS/issues/1381
You are very welcome to give a try to the [/dev version](https://github.com/FreshRSS/FreshRSS/tree/dev), as more testers would be appreciated :-)

**Comment by disanvparean** [comment]
Wow, I didn't know. Thank you, I will try that with pleasure.
