### ISSUE TITLE
Disable unread items

### ISSUE THREAD

**Issue by disanvparean** [FreshRSS/FreshRSS#1534]
Hello,
I hope that question wasn't asked before. Sorry if it's the case.
I want to make a sort of "planet", a public aggregator.
Consequently I don't really care about unread items, especially the counter in Freshrss.
Is there a possibility to disable it that I missed ?
The easy (and dirty but quick) solution would be for me to hide the counter using css (display:none). But maybe someone has a better idea to do it. Especially I want to do a public aggregator but I also want to give users the possibility to have their own account so it could be useful for them to have the counter. Maybe an account based switch to enable/disable counting ? Do you think an extension could do the job ? I just started to use Freshrss and I'm not sure I'm ready to dig the core code.
Thank you

**Comment by aledeg** [comment]
Hi,
I am not sure what you're asking for. Could you provide a screenshot to clarify what you're trying to achieve?

**Comment by disanvparean** [comment]
Thank you for your answer.
In one sentence : I just want to hide (XXX) unread items everywhere in FreshRSS

**Comment by aledeg** [comment]
I see now.

You cannot do exactly that. But there is a workaround that might work for you.
In the configuration, under "Reading" tab, there is the option "Mark article as read… upon reception of the article". If you check that option, articles will be read as soon as they arrive. Thus you won't see (XXX) unread items.

Hope it helps.

**Comment by disanvparean** [comment]
Yeah, this is exactly what I needed. Thanks a lot
