### ISSUE TITLE
Items unread from new feed when using "Mark article as read… upon reception of the article".

### ISSUE THREAD

**Issue by disanvparean** [FreshRSS/FreshRSS#1535]
Hello,
I'm using the option "Mark article as read… upon reception of the article", so all my feeds items should be read.
Nonetheless, when I add a new feed, items are downloaded and they are not read but unread. 
Thank you.
Keep the good work ! :+1:

**Comment by Alkarex** [comment]
Should be fixed in https://github.com/FreshRSS/FreshRSS/pull/1543 (not tested yet).
Could you please give it a try?
