### ISSUE TITLE
Application problem

### ISSUE THREAD

**Issue by nvjacobo** [FreshRSS/FreshRSS#1536]
I have on web 
Application problem
See logs files

Logs:

Got error 'PHP message: PHP Warning:  include(index.html): failed to open stream: No such file or directory in /home/web/index.php on line 3\nPHP message: PHP Warning:  include(): Failed opening 'index.html' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /home/web/index.php on line 3\n'

**Comment by Alkarex** [comment]
Hello,
* Please check that you have not deleted the `./FreshRSS/index.html` file.
* The public root of FreshRSS is `./FreshRSS/p/`. If you have a domain dedicated to FreshRSS, use that folder for your root.

**Comment by nvjacobo** [comment]
Thanks, 

index.html and index.php is on ./FreshRSS/. And i use p/ for root

**Comment by nvjacobo** [comment]
Fixed. It was a problem with data base server(disk space)
