### ISSUE TITLE
Custom Theme?

### ISSUE THREAD

**Issue by Aasemoon** [FreshRSS/FreshRSS#1538]
Hi there,

After creating a new theme [based on what's currently available] I'm having trouble getting the new theme to show up in the list of themes I can choose. How can I get the new theme recognised? [Wasn't able to find anything in the documentation...].

Cheers!

**Comment by aledeg** [comment]
You have to put it in the theme folder and have the same architecture than other themes.
Did you forget to add a metadata.json file?

**Comment by Aasemoon** [comment]
@aledeg Thanks for your response.
That's exactly what I did though. And I did adjust metadata.json as well. That's why I don't understand why it doesn't show up in the list!

**Comment by aledeg** [comment]
Could you share it in a gist for instance? I'll have a look at it later today.

**Comment by Aasemoon** [comment]
Sure... but share what exactly? What I have is pretty much the original theme from here:
https://github.com/FreshRSS/FreshRSS/tree/master/p/themes/Origine
The only difference is what's in metadata.json, mine looks like this:
`{
  "name": "Blue",
  "author": "Aasemoon",
  "description": "A blue theme for FreshRSS",
  "version": 0.1,
  "files": ["_template.css", "origine.css"]
}`

I didn't really get to changing anything yet, was just trying to tweak a couple of colours for starters.

**Comment by aledeg** [comment]
I've tried to create a template and it's working correctly.
Here are the steps I've followed:

1. copy the folder *./p/themes/Origine* to *./p/themes/Aasemoon*,
1. change the content of *./p/theme/Aasemoon/metadata.json* by the one you provided,
1. change the background color for *html* in *./p/themes/Aasemoon/origine.css* to blue,
1. go in the configuration and see that I have now 8 themes instead of 7,
1. select the new theme and apply it to see that the background turned blue.

Did you follow those steps?

**Comment by Aasemoon** [comment]
@aledeg Thanks for your help. The problem seems to have just solved itself, though to be honest I'm not sure exactly how! I originally did all of what you've suggested here. And I was still seeing 7 themes. Now I just went ahead and repeated all of this again, the only thing I did different is that I created a new CSS file as well for the new theme. Now it shows up. Odd! =)

**Comment by marienfressinaud** [comment]
It might be a permission issue, I think server was not able to access your files and/or repository so was not able to show your theme… but I may be wrong as well :).

**Comment by aledeg** [comment]
@Aasemoon could we close that issue?

**Comment by Aasemoon** [comment]
@aledeg Yes, the issue is resolved. Thanks.

**Comment by Alkarex** [comment]
@Aasemoon If you end up with a new theme, please share :-)

**Comment by Aasemoon** [comment]
@Alkarex Sure, if I end up with anything more than a few tweaked colours I'll certainly share it. =)

**Comment by spupuz** [comment]
i'm interested too
