### ISSUE TITLE
possible issue...updating from git?

### ISSUE THREAD

**Issue by fsantiago07044** [FreshRSS/FreshRSS#1542]
hello, i attempted to check my up-to-date'ness with:

git reset --hard
git pull

'already up to date'

kewl. but, when i refreshed my page view of my freshrss site, i was immediately sent back to the step 1 installation screen. luckily it detected i was already installed and allowed me to re-use my prior config and then the site went back to normal and all was well. 

can you tell me what happened? I suspect it was the "reset --hard", and admittedly, i probably need to brush up on my git commands. thanks.

**Comment by aledeg** [comment]
You need to remove the file *data/do-install.txt*. This file is deleted during the installation process.

When you've done the ```git reset --hard```, basically you've told git to reset everything. Including that file.

**Comment by Alkarex** [comment]
I have added some more readme in https://github.com/Alkarex/FreshRSS/blob/update-status/cli/README.md#using-git
