### ISSUE TITLE
Feature Request: "Add to favourites" on Reading View

### ISSUE THREAD

**Issue by Aasemoon** [FreshRSS/FreshRSS#1545]
Hi there,

I have a request for a tiny adjustment. Could you possibly make it so that the "add to favourites" star button shows up for each item on the reading view as well? Would be very helpful I believe.

Cheers!

**Comment by Alkarex** [comment]
Related to https://github.com/FreshRSS/FreshRSS/issues/1400

**Comment by Alkarex** [comment]
Thanks @Aasemoon 
Planned for 1.8.0.

**Comment by Aasemoon** [comment]
@Alkarex Great! Thanks! =)

**Comment by aledeg** [comment]
@Aasemoon Could you check the PR I've just made and tell me if it suits your needs?

**Comment by Aasemoon** [comment]
Hi @aledeg, hmmm I'm not sure exactly what I'm missing, but when I apply the suggested changes to my main.js, I don't see anything different in the reading view. Is that the only file you have changed?

**Comment by aledeg** [comment]
There is nothing different in the view. But you can use the shortcut available in the normal view. I was wondering if that change is enough for you or if we need to go a bit further. Thank you

**Comment by Aasemoon** [comment]
@aledeg , aha, then I guess not. I'd like an "add to favourite" button on the reading view mainly because usually I view my feeds on various tablets. Keyboard shortcuts I've basically never used.

**Comment by aledeg** [comment]
Thank you for your feedback. I'll try to add something in the view. I am not very comfortable with front-end but I'll give it a try.

**Comment by Aasemoon** [comment]
@aledeg Thanks a lot! That would be great. =)

**Comment by aledeg** [comment]
@Aasemoon The PR is merged. Does it covers what you had in mind?
If yes, I suggest we close that issue.
