### ISSUE TITLE
Call for testing /dev before version 1.7

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#1548]
The future version 1.7 of FreshRSS is [ready](https://github.com/FreshRSS/FreshRSS/milestone/20) for testing. This time, the main theme has been to introduce a more more natural order of entries when refreshing feeds, but there is also a number of new features and bug corrections, as visible [in the changelog](https://github.com/FreshRSS/FreshRSS/blob/dev/CHANGELOG.md):

* Features:
	* Deferred insertion of new articles, for better chronological order [#530](https://github.com/FreshRSS/FreshRSS/issues/530)
	* Better search:
		* Possibility to use multiple `intitle:`, `inurl:`, `author:` [#1478](https://github.com/FreshRSS/FreshRSS/pull/1478)
		* Negative searches with `!` or `-` [#1381](https://github.com/FreshRSS/FreshRSS/issues/1381)
			* Examples: `!intitle:unwanted`, `-intitle:unwanted`, `-inurl:unwanted`, `-author:unwanted`, `-#unwanted`, `-unwanted`
		* Allow double-quotes, such as `author:"some name"`, in addition to single-quotes such as `author:'some name'` [#1478](https://github.com/FreshRSS/FreshRSS/pull/1478)
	* Multi-user tokens (to access RSS outputs of any user) [#1390](https://github.com/FreshRSS/FreshRSS/issues/1390)
* Compatibility:
	* Add support for PHP 7.1 [#1471](https://github.com/FreshRSS/FreshRSS/issues/1471)
	* PostgreSQL is not experimental anymore [#1476](https://github.com/FreshRSS/FreshRSS/pull/1476)
* Bug fixing
	* Fix PubSubHubbub bugs when deleting users, and improved behaviour when removing feeds [#1495](https://github.com/FreshRSS/FreshRSS/pull/1495)
	* Fix SQL uniqueness bug with PostgreSQL [#1476](https://github.com/FreshRSS/FreshRSS/pull/1476)
		* (Require manual update for existing installations)
	* Do not require PHP extension `fileinfo` for favicons [#1461](https://github.com/FreshRSS/FreshRSS/issues/1461)
	* Fix UI lowest subscription popup hidden [#1479](https://github.com/FreshRSS/FreshRSS/issues/1479)
	* Fix update system via ZIP archive [#1498](https://github.com/FreshRSS/FreshRSS/pull/1498)
	* Work around for IE / Edge bug in username pattern in version 1.6.3 [#1511](https://github.com/FreshRSS/FreshRSS/issues/1511)
	* Fix *mark as read* articles when adding a new feed [#1535](https://github.com/FreshRSS/FreshRSS/issues/1535)
	* Change load order of CSS and JS to help CustomCSS and CustomJS extensions [Extensions#13](https://github.com/FreshRSS/Extensions/issues/13), [#1547](https://github.com/FreshRSS/FreshRSS/pull/1547)
* UI
	* New option for not closing the article when clicking outside its area [#1539](https://github.com/FreshRSS/FreshRSS/pull/1539)
	* Download icon 💾 for other MIME types (e.g. `application/*`) [#1522](https://github.com/FreshRSS/FreshRSS/pull/1522)
* I18n
	* Simplified Chinese [#1541](https://github.com/FreshRSS/FreshRSS/pull/1541)
	* Improve English [#1465](https://github.com/FreshRSS/FreshRSS/pull/1465)
* Security
	* Do not require write access to check availability of new versions [#1450](https://github.com/FreshRSS/FreshRSS/issues/1450)
* Misc.
	* Move [documentation](/FreshRSS/FreshRSS/tree/dev/docs) into FreshRSS code [#1510](https://github.com/FreshRSS/FreshRSS/pull/1510)
	* Moved `./data/force-https.default.txt` to `./force-https.default.txt`,
		`./data/config.default.php` to `./config.default.php`,
		and `./data/users/_/config.default.php` to `./config-user.default.php` [#1531](https://github.com/FreshRSS/FreshRSS/issues/1531)
	* Fall back to article URL when the article GUID is empty [#1482](https://github.com/FreshRSS/FreshRSS/issues/1482)
	* Rewritten Favicon library using cURL [#1504](https://github.com/FreshRSS/FreshRSS/pull/1504)
	* Fix SimplePie option to disable syslog [#1528](https://github.com/FreshRSS/FreshRSS/pull/1528)

You are all kindly invited to [give a try to the /dev version](https://github.com/FreshRSS/FreshRSS/tree/dev). (@Frenzie, @Vonv, @Wanabo, @lapineige, @ecmu, @danc, @plarus...)

Many thanks already to those of you who have contributed code ( @marienfressinaud, @jlefler, @gsongsong, @cez81, @psukys, @hoilc ), and to those of you who been involved one way or another in this new version, such as @aledeg, @Trim, @Silviojjb, @Pazns, @Jedediah04, @sant527, @lapineige, @tcitworld, @uncovery, @Crupuk, @neuralcpu , @GeoZzNL, @kevinpapst, @FordDoctor, @peugnezb, @Mayson74, @LeapingDragon, @oupala, @disanvparean, @Angristan, @Alwaysin, @gabrielcossette, etc.

**Comment by Frenzie** [comment]
Did something change about system extensions? The ImageProxy extension seems to have stopped working and also can't be enabled/disabled. I won't have any time to look into this myself until Tuesday at the earliest.

Edit: also many of my feeds (but apparently not all) have been duplicated as new. Here's an example screenshot from http://onzetaal.nl/rss/taaladviezen/ It's not immediately obvious to me which change might be responsible. It's fairly minor but suddenly having 154 unread items does stand out a little bit.

![screenshot_2017-05-26_20-04-51-fs8](https://cloud.githubusercontent.com/assets/202757/26507010/ca708ca0-424e-11e7-8aad-af7cddd1c1e9.png)

Edit 2: forgot to mention, I updated from 1.6.3.

**Comment by Alkarex** [comment]
@Frenzie For your duplicates, could it be invalid feeds providing an empty GUID? If this is the case, then FreshRSS behaviour has indeed changed to be more consistent by falling back to article URL, and if URL is empty to an article hash https://github.com/FreshRSS/FreshRSS/pull/1483

**Comment by Frenzie** [comment]
Ah yes, that does look like an important change as a lack of GUID doesn't make a feed invalid and is typically the same as link. However, the `link` hasn't actually changed or anything.

So if I understand correctly, the 1.6.x and earlier entries have their guid set to a hash in the FreshRSS db rather than the link?

**Comment by Frenzie** [comment]
Copied from https://github.com/FreshRSS/Extensions/issues/16#issuecomment-304433714

> The actual problem [with extensions] is that there now seems to be an internal confusion between system and user extensions that didn't exist before. If you have previously enabled a user extension of the same name as a system extension you then can't disable the system extension.

**Comment by Aasemoon** [comment]
The new search capabilities are making me very happy!
And nothing seems to be broken here so far.
Cheers!

**Comment by Frenzie** [comment]
Is "Mark as read" supposed to look extra large compared to the other options?

![screenshot_2017-05-27_13-02-35](https://cloud.githubusercontent.com/assets/202757/26521007/46aeeb06-42de-11e7-88e0-93d6ccf8892e.png)

**Comment by oupala** [comment]
Just testing this new version.

I manually updated the version to version 1.6.3 in `constants.php` :

```php
define('FRESHRSS_VERSION', '1.6.3');
```

And when I check if a new version is available, I have a warning telling me that a new **dev** version is available. In my opinion, I should not have any warning as there is no new version on the **stable** channel.

There will always be a new dev version available, I want to be warned only when a new stable version is available.

**Comment by Frenzie** [comment]
Afaik if last_update.txt is set to `dev` then you're on the "dev channel". Perhaps there should be a more explicit way to choose between the stable and dev update channels (or at least I can't spot one at a quick glance) but I don't think the version number has or should have much of anything to do with it.

**Comment by oupala** [comment]
You seem to be right @Frenzie the *channel* is stored inside the `last_update.txt` file.

I was just following @Alkarex [message](/FreshRSS/FreshRSS/pull/1544#issuecomment-304216852) which do not talk about the `last_update.txt` file.

**Comment by Alkarex** [comment]
The update mechanisms (including changing channel) need to be improved. Some of it is already planned in https://github.com/FreshRSS/FreshRSS/issues/907

**Comment by Frenzie** [comment]
This probably isn't new as I normally just use the program without testing nooks and crannies, but if I try to look at the log then I get this error:

```
[Sun May 28 15:35:49.329070 2017] [:error] [pid 11823] [client asdasdfasdfasdf:39112] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 72 bytes) in /var/www/html/feeds/app/Models/LogDAO.php on line 19
```

I'm guessing this means there might be some recursion going on leading to a memory leak.

Edit: Sorry, I just noticed my log file is slightly hefty at 28 MiB. That probably discounts the memory leak hypothesis, but it does point to a different problem. Since 128 MiB is the standard PHP memory limit, it'd be a good idea to split up or tail the files in such a way that it doesn't happen. Or as a slightly less thorough but presumably mostly adequate solution, simply create a `log.yyyy.mm.txt` file for every month.

**Comment by Wanabo** [comment]
Great to see a new dev version again!

I did a manual update. All went well, but below some remarks. I'll do some further testing and report back.

Perhaps it can be found somewhere but at first glance I could not find changed file locations in the change log. Please log this somewhere to keep the installation as clean as possible.

data\
config.default.php moved to root?
force-https.txt removed?
force-https.default.txt to root?
do-install.txt check for valid database and skip install or present choice to install or go to previous installation. Now I must manually remove this file in order to get the site working again.

data\users\currentuser\log.txt was over 300 Mb. Purge once and a while? Keeping only last 10 ... 50 entries?

**Comment by Frenzie** [comment]
> data\users\currentuser\log.txt was over 300 Mb. Purge once and a while? Keeping only last 10 ... 50 entries?

That sounds rather meager. I'd say you need at least a few hundred lines so you can track down something that didn't happen 10 seconds ago. Let's say 500 KiB as a default.

**Comment by Alkarex** [comment]
Yes @Wanabo and @Frenzie, we need to have some kind of logrotate for the logs. Please open a new issue.

**Comment by Wanabo** [comment]
@Frenzie: Any value is ok by me.

Found an issue on my installation.

Reading sort order, newest first. But as you can see in the image it is not entirely sorted by time.




![sort order](https://cloud.githubusercontent.com/assets/13087022/26529431/f9101aae-43bf-11e7-9ed8-3841f5f3094c.GIF)

Will open a new issue for log rotation.

**Comment by Wanabo** [comment]
Issued log rotation: https://github.com/FreshRSS/FreshRSS/issues/1562

**Comment by Alkarex** [comment]
@Wanabo With the new sort order, articles are sorted by declared date but only within a refresh batch. So if you have a cron job running for instance every 30 minutes, articles found during this process will be sorted by declared date. If the next cron discovers some articles with an older declared date, they will still be appended after the ones of the previous cron. See https://github.com/FreshRSS/FreshRSS/issues/530 for more details.

**Comment by Frenzie** [comment]
@Wanabo @Alkarex And that's good imo. Otherwise new stuff would just get lost at the bottom. You can observe this behavior even better when you add a new feed (or delete an entry directly from the db).

![screenshot_2017-05-28_16-20-18-fs8](https://cloud.githubusercontent.com/assets/202757/26529536/c5cbab16-43c1-11e7-9982-168cd1e49750.png)

❤️

**Comment by Frenzie** [comment]
I haven't come across anything else. Looks good to me. 👍

**Comment by aledeg** [comment]
So far so good :)

**Comment by Alkarex** [comment]
Thank you all for the tests and good feedback. FreshRSS 1.7.0 is released :-)
https://github.com/FreshRSS/FreshRSS/releases/tag/1.7.0
