### ISSUE TITLE
Language nitpick: uppercase May in statistics

### ISSUE THREAD

**Issue by Frenzie** [FreshRSS/FreshRSS#1560]
![screenshot_2017-05-28_12-31-53](https://cloud.githubusercontent.com/assets/202757/26528048/df2cc61e-43a1-11e7-9eca-69c4ab735210.png)

It's debatable which of these is actually wrong in English (as the default is a capitalized first letter), but in any case it's inconsistent.

A quick peek suggests that months all exist in two versions, both abbreviated in spite of what the index suggests:

```php
		'mar' => 'mar',
		'march' => 'Mar',
```

However, because May is already three letters it only exists in an uppercase capacity:
https://github.com/FreshRSS/FreshRSS/blob/be0bcfef7e38f27284ec7b377b342ba389515964/app/i18n/en/gen.php#L82

**Comment by Alkarex** [comment]
I would go for an uppercase everywhere

**Comment by aledeg** [comment]
If we check in the [code](https://github.com/FreshRSS/FreshRSS/blob/master/app/i18n/en/gen.php#L45-L56), we already use the *ucfirst* string but I don't know why.
If it's useless, it's a matter of reusing the strings.

**Comment by Alkarex** [comment]
Should be fixed in https://github.com/FreshRSS/FreshRSS/pull/1617
