### ISSUE TITLE
Add PHP required extension in readme

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/FreshRSS#1563]
In "Required extensions" for PHP, there is also php7-session. I understand it is probably the default on a lot of distributions but in Alpine Linux this was not the case. Just wanted you to know!

**Comment by Alwaysin** [comment]
Same for ctype:

`Blast! Cannot find a required library for character type checking (php-ctype).`

**Comment by Alkarex** [comment]
@Alwaysin Would you mind doing a pull request with those changes?

**Comment by Alkarex** [comment]
Done in https://github.com/FreshRSS/FreshRSS/pull/1572
