### ISSUE TITLE
Installation fails (Fatal error … CategoryDAO.php)

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#1567]
Hi, I downloaded the current master and installed it. Had some problems along the way (could resolve them with GitHub) and am now stucked with the following message:

`Fatal error: Call to a member function execute() on boolean in /var/www/freshrss/app/Models/CategoryDAO.php on line 115`

My setup:
- Debian 8.8
- PHP Version 5.6.30
- Sqlite 3.8.7.1

**Comment by Alkarex** [comment]
Thanks for the bug report. I look at it immediately.
https://github.com/FreshRSS/FreshRSS/issues/1548

**Comment by Alkarex** [comment]
I cannot immediately reproduce the problem, and the install (via CLI or Web interface) works fine for me (tested on Ubuntu 16.04, PHP 7.0, SQLite 3.11).

Could you please give details about the other problems you got as well?

**Comment by Alkarex** [comment]
For the record, it does not look like there has not been any change recently in this part of the code
https://github.com/FreshRSS/FreshRSS/blame/master/app/Models/CategoryDAO.php#L106

**Comment by Alkarex** [comment]
P.S.: And when do you get this error message, more precisely? @hoch1009

**Comment by ghost** [comment]
My problems were related to the requirements (lighttpd, php5, permissions).
Installation was done via CLI.

It might be something related to php/sqlite but the installation did not show that anything is missing.

I am getting the message when opening http://192.168.1.1/freshrss/ (getting redirected to http://192.168.1.1/freshrss/p/i/).

**Comment by Alkarex** [comment]
Could you please show the precise command-line(s) you used for your CLI install?
And if not confidential, maybe you could show the content of your SQLite DB?
https://sqlite.org/cli.html#converting_an_entire_database_to_an_ascii_text_file

**Comment by sjeon87** [comment]
I have the same problem too. I've upgraded FreshRSS from 1.4.0 to 1.7.0 via git. Upgrade has been done via web interface. And I don't think it's related with the contetnt of SQL. The same problem occured when I wiped all data and did fresh install.

    2017/06/04 20:48:52 [error] 8848#8848: *34 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function execute() on boolean in /home/songsong/nginx/FreshRSS/app/Models/CategoryDAO.php:115
    Stack trace:                                                                       
    #0 /home/songsong/nginx/FreshRSS/app/Controllers/indexController.php(164): FreshRSS_CategoryDAO->listCategories()
    #1 /home/songsong/nginx/FreshRSS/app/Controllers/indexController.php(30): FreshRSS_index_Controller->updateContext()
    #2 /home/songsong/nginx/FreshRSS/lib/Minz/Dispatcher.php(119): FreshRSS_index_Controller->normalAction()
    #3 /home/songsong/nginx/FreshRSS/lib/Minz/Dispatcher.php(48): Minz_Dispatcher->launchAction('normalAction')
    #4 /home/songsong/nginx/FreshRSS/lib/Minz/FrontController.php(84): Minz_Dispatcher->run()
    #5 /home/songsong/nginx/FreshRSS/p/i/index.php(46): Minz_FrontController->run() 
    #6 {main}                                                                          
      thrown in /home/songsong/nginx/FreshRSS/app/Models/CategoryDAO.php on line 115" while reading response header from upstream, client: 141.223.84.43, server: songsong.postech.ac.kr, request: "GET /FreshRSS/p/i/index.php HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "songsong.postech.ac.kr"


It's something related to PDO->[prepare()](http://php.net/manual/en/pdo.prepare.php), which returns `FALSE` in case of unsuccessful action. But still couldn't find what causes this. 

I am using nginx, php7, sqlite 3.11. I've checked that web server has a correct ownership and permission for user data directory.

If you need more information, please let me know.

**Comment by Alkarex** [comment]
@gsongsong Interesting. I still cannot reproduce the problem on my side.
Do you say you can reproduce the problem even with a fresh git install?

Could you please try the following command on your server (to be adapted with your paths)?

```sh
cd /usr/share/FreshRSS/
sqlite3 ./data/users/gsongsong/db.sqlite
```

```sql
SELECT c.id AS c_id, c.name AS c_name, f.*
FROM `category` c
LEFT OUTER JOIN `feed` f ON f.category=c.id
GROUP BY f.id, c_id
ORDER BY c.name, f.name;
```

**Comment by sjeon87** [comment]
@Alkarex , `db.sqlite` is literally empty. 0 bytes.
@hoch1009 But I think I found a (possible) reason.

My case, I installed FreshRSS and a server (`lighttpd`, `nginx`, `apache` whatever) is not an owner of FreshRSS, but a group (i.e., `owner: songsong,  group: www-data`). In such a case, it seems that FreshRSS creates `db.sqlite` but its permission is initially set without group write permission (something like `rw-r--r--`). Hence, the file is created, but it could not execute any SQL query, even creating a table. Thus, the file size is 0 bytes with no tables. All further SQL operation will fail.

After I've changed ownership of all files into `www-data:www-data`, everything is ok so far.

But this is just my case. I am not sure the original poster did the same thing.

**Comment by ghost** [comment]
Hi @Alkarex & Hi @gsongsong,

I could solve my problem by downloading the master again and starting the setup via web interface. I would assume that my problem had something to do with the sqlite database not being existent (or the user not having the appropriate rights as suggested by @gsongsong) because the execute command relates to a sql command.

What I do not know is if a database has to be existent prior to starting the setup via CLI or if one will be created in the process?

**Comment by Alkarex** [comment]
No need to create a database in advance.

If you follow the documentation, it should work:
* https://github.com/FreshRSS/FreshRSS#example-of-full-installation-on-linux-debianubuntu

More precise, with CLI:
* https://github.com/FreshRSS/FreshRSS/tree/master/cli#using-git
* https://github.com/FreshRSS/FreshRSS/tree/master/cli#commands

See in particular the access rights:
* https://github.com/FreshRSS/FreshRSS/tree/master/cli#note-on-access-rights

And you can manually check the SQLite database via the `sqlite3` tool.

Examples of CLI commands, which I use on my test machine:

```sh
cd /usr/share/ && \
git clone https://github.com/FreshRSS/FreshRSS.git

cd /usr/share/FreshRSS/ && \
./cli/do-install.php --default_user alexandre --environment development --db-type sqlite --db-user alexandre --db-password alexandre --db-base freshrss --db-prefix freshrss_ && \
./cli/create-user.php --user alexandre --password 'alexandre' && \
./cli/import-for-user.php --user alexandre --filename /home/alexandre/Downloads/opml.xml && \
./cli/actualize-user.php --user alexandre && \
sudo chown -R :www-data . && sudo chmod -R g+r . && sudo chmod -R g+w ./data/
```

**Comment by ghost** [comment]
Hi @Alkarex,

sorry. I just looked at https://github.com/FreshRSS/FreshRSS#installation and thought it'll work but with the detailed instruction everything should work.
