### ISSUE TITLE
Update server don't do anything

### ISSUE THREAD

**Issue by Sp3r4z** [FreshRSS/FreshRSS#1569]
The update process is based on: https://update.freshrss.org/ this website doesn't respond something special: "NO_VERSION_SPECIFIED"!

Is there any problem, something wrong? Is this website who drives upgrading process?

**Comment by Alwaysin** [comment]
This website isn't intended to be used via a browser. It is only used by FreshRSS itself when you go to Settings -> Update.

**Comment by Sp3r4z** [comment]
But it doesn't work from Settings→Update so… 

Try by yourself: https://update.freshrss.org/?v=1.6.3 it returns: "NO_UPDATE 1.6.3" but there is a 1.7.0 released so we can't upgrade? The FreshRSS feed, added on installation process, indicates the release of 1.7.0 version…

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/update.freshrss.org/issues/2

**Comment by Alkarex** [comment]
Will be improved as part of https://github.com/FreshRSS/FreshRSS/issues/907
