### ISSUE TITLE
Do we have an account on Travis?

### ISSUE THREAD

**Issue by aledeg** [FreshRSS/FreshRSS#1570]
If not, could we create one with an email similar to "travis <at> freshrss <dot> org" ?

**Comment by marienfressinaud** [comment]
I can configure Travis through my personal account (and I guess you also can), I'm not sure to understand the need to create a generic account. Otherwise, such address would be a mailing list since it has been configured that way for freshrss.org.

**Comment by aledeg** [comment]
The idea was to decouple a user account from the travis user. This way we can protect ourselves from the [bus factor](https://en.wikipedia.org/wiki/Bus_factor).

**Comment by marienfressinaud** [comment]
Didn't forget the ticket :). Travis is not our weakest point against bus factor, I worry a lot more about the server access! Anyway, all people belonging to FreshRSS organization on GitHub should have the exact same access on Travis, so I don't think we need to create a generic account, do you?

However, we may open the problematic to the different accounts we may have (server, Twitter, etc.)

**Comment by aledeg** [comment]
Are you talking about where each new version are hosted?
If so, maybe we can change that process and use github tags directly in github.

**Comment by marienfressinaud** [comment]
I'm talking about freshrss.org and all its subdomains: demo., rss., update., doc. (but this one will be hosted on GH Pages soon). We don't host any version of FRSS anywere, update.freshrss.org provides a script to download an archive from GH, that's all.

**Comment by Alkarex** [comment]
A bit related to https://github.com/FreshRSS/FreshRSS/issues/907 (which could remove the need for the update server)

**Comment by Frenzie** [comment]
Yeah, Travis doesn't have a bus factor provided there are multiple people with sufficient access in the organization.

**Comment by Alkarex** [comment]
https://travis-ci.org/FreshRSS/FreshRSS
