### ISSUE TITLE
Please check that you are not altering your HTTP REFERER

### ISSUE THREAD

**Issue by paul-mesnilgrente** [FreshRSS/FreshRSS#1573]
Hello,

I just tried to upgrade to the newest version of FreshRSS by executing this lines:

```
sudo git reset --hard
sudo git clean -df .
sudo git pull
sudo chown -R :www-data . && sudo chmod -R g+r . && sudo chmod -R g+w ./data/
```

I did it by command line because the web interface was throwing me an error "Git error : updating ...".

But now when I go on the website and that it is executing the installation Checks, it is printing me that: `Please check that you are not altering your HTTP REFERER.`. A bit strange because it was working before :/

I don't find anything on google or in issues, can you help me?

**Comment by Alkarex** [comment]
Hello,
The git error from the Web interface is typically due to access rights, or local conflicts.
Do you know from which version you were updating? Do you have the same message from another Web browser?
In any case, if it is not from a very old version of FreshRSS, you can skip the install by doing:

```sh
rm data/do-install.txt
```

**Comment by paul-mesnilgrente** [comment]
1. I have deleted data/do-install.txt as you said.
2. Next I was forbidden to access my feed page.
    1. I have changed the `auth_type` to `none` in data/config.php
    2. I have changed my password
    3. I have changed the `auth_type` to `form` in data/config.php
3. It works !

Thank you for the tip, but I still don't know what was the problem for this http referer... When I know go into the "installation checking", everything is ok.
