### ISSUE TITLE
"show only"

### ISSUE THREAD

**Issue by nikoss** [FreshRSS/FreshRSS#1574]
Hi, I will open a couple of issues that are kind of old.

The titles of the buttons, in the main FreshRSS window are misleading.

For example...
They say "Show only read" and "Show only unread".
But if you press both of them you will see both the read and the unread articles.
So, the titles ought to be "Show read" and "Show unread".
The same, I assume, implies for the "Show only favourites" button
(and maybe other buttons, too).

**Comment by Alkarex** [comment]
Yes indeed. If you can, pull requests appreciated.
