### ISSUE TITLE
no way to access configuration through smartphone

### ISSUE THREAD

**Issue by nikoss** [FreshRSS/FreshRSS#1575]
How to reproduce:

+ Log in to your FreshRSS installation.
+ Increase the font size ( CTRL++ ) until the theme will change to a minimal one
+ that's, more or less, how it looks on a smartphone
   - the are no buttons for "Configuration", "Subscription Management",  per feed management (the button that was at the left of every feed name)

**Comment by Alwaysin** [comment]
For reference: #45, #264, #976

**Comment by Alkarex** [comment]
Yes indeed. Duplicate of https://github.com/FreshRSS/FreshRSS/issues/45 (in French) and https://github.com/FreshRSS/FreshRSS/issues/976 (in English).
Let's continue in https://github.com/FreshRSS/FreshRSS/issues/976
