### ISSUE TITLE
[IMPORTANT] Updating from 1.6.* to 1.7.0

### ISSUE THREAD

**Issue by marienfressinaud** [FreshRSS/FreshRSS#1577]
As said in ticket https://github.com/FreshRSS/FreshRSS/issues/1488, you'll need to do a manipulation to be able to update FreshRSS from version 1.6.* to the new 1.7.0.

> […] the `require(UPDATE_FILENAME);` is not available anymore line 196. So to make it works, you'll need to update file `./app/Controllers/updateController.php` and move the `require` to the line 168.

**Comment by Alkarex** [comment]
P.S. This is only when FreshRSS has been installed from a ZIP (and not e.g. from git).

**Comment by zsuiram** [comment]
Is this fixed in 1.7.0 (and onwards) or do we have to change this everytime in future updates?

**Comment by marienfressinaud** [comment]
This is fixed in 1.7.0! Sorry for the inconvenience

**Comment by zsuiram** [comment]
Thanks for your time and work. Much appreciated!
