### ISSUE TITLE
Docker nginx API configuration behind proxy

### ISSUE THREAD

**Issue by abudden** [FreshRSS/FreshRSS#1579]
I have freshrss set up behind an nginx proxy (which provides https certification). nginx is running in a docker container with a setup based on https://hub.docker.com/r/jrcs/letsencrypt-nginx-proxy-companion/

freshrss is set up using a separate docker container based on https://github.com/linuxserver/docker-freshrss

This is working well for normal usage.

If I go to `https://my.server.url/p/api/` I get presented with a page advertising the google reader compatible api and saying my server address is (with a weird port) `https://my.server.url:80/p/api/greader.php`

If I click on **either** of the links, it goes into a redirection loop - I stopped the browser after a few seconds when the url was `https://my.server.url/p/api/greader.php/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/` - every time the page loaded, it added another `/p/` on the end.

Suffice to say that News+ doesn't work

Please can you tell me what to check to see what I might have set up wrong?

**Comment by auricom** [comment]
Hello,
The nginx configuration inside the Freshrss docker image is not correct.
You should try to build your own docker image and replace the /root/defaults/default file by something like the one found on this issue : https://github.com/FreshRSS/FreshRSS/issues/1515

**Comment by abudden** [comment]
Please can you give me an idea of what is not correct in the configuration?

I tried the configuration that you originally posted to this email and it resulted with **any** access to the site going to `https://my.server.url/p/i/i/i/i/i/i/i/` with an ever increasing number of `/i/`s on the end.  I also tried the one in issue #1515 (except without the SSL stuff as it's behind an SSL proxy).  The result was basically the same.

**Comment by auricom** [comment]
I'm sorry but I don't know exactly what exactly is wrong with default configuration :-)

But I experienced the same situation that you describe when I built my custom docker Image, based on linuxserver.io

Here is my final configuration

Freshrss nginx server :

```
 server {
 	listen 80 default_server;
 
 	root /config/www/freshrss/p;
 	index index.html index.htm index.php;
 
 	client_max_body_size 0;
 
 	location / {
 		try_files $uri $uri/ =404;
 	}
 
 	location ~ ^(.+?\.php)(/.*)?$ {
		include /etc/nginx/fastcgi_params;
 		fastcgi_pass 127.0.0.1:9000;
 		fastcgi_index index.php;
 		fastcgi_param PATH_INFO $2;
 		fastcgi_param SCRIPT_FILENAME $document_root$1;
 		fastcgi_read_timeout 900s;
 	}
 }
```

Here is my reverse proxy config :

```
 server {
 	listen 443 ssl http2;
 
 	server_name freshrss.*;
 
     include /config/nginx/ssl/ssl.conf;
 
 	location / {
 		proxy_pass http://freshrss-upstream/;
 		proxy_buffering off;
 		proxy_http_version 1.1;
 		proxy_set_header Host $host;
 		proxy_set_header X-Real-IP $remote_addr;
 		proxy_pass_header X-XSRF-TOKEN;
 		
 	}
 }
```

Works like a charm !

**Comment by Alkarex** [comment]
Thanks for the feedback @auricom 👍

**Comment by Alkarex** [comment]
FreshRSS now has an updated Docker image of its own (based on Alpine Linux), if you want to give it a try at some point. https://github.com/FreshRSS/FreshRSS/pull/1813
https://hub.docker.com/r/freshrss/freshrss/

**Comment by Alkarex** [comment]
Documentation update in https://github.com/FreshRSS/FreshRSS/pull/2151
