### ISSUE TITLE
Update from 1.3.2-beta

### ISSUE THREAD

**Issue by ClementNX** [FreshRSS/FreshRSS#1581]
Hi,

In update page I have this message: "Ok ! FreshRSS va maintenant être mis à jour vers la version 1.3.2-beta." but when I try to update I got this error :  

```
Strict Standards: Only variables should be passed by reference in /home/me/FreshRSS/data/update.php on line 156

Warning: Cannot modify header information - headers already sent by (output started at /home/me/FreshRSS/data/update.php:156) in /home/me/FreshRSS/lib/Minz/Request.php on line 163
```

I hesitate to update manually, what precautions should I take?

Thanks,

I currently use 1.3.2-beta

**Comment by Alkarex** [comment]
Hello,
You should take a backup for your current directory and database (what database are you using)?
Please check the minimal requirements (PHP 5.3.3+, MySQL 5.5.3+ with utf8mb4 or SQLite 3.7.4+).
Then, an in-place update should work, even if jumping over several versions.

**Comment by ClementNX** [comment]
Hi,
I use MySQL. So I just have to copy the new files? Great!

**Comment by ClementNX** [comment]
Hi,
I'm back because now on the update page I have " Votre version actuelle de FreshRSS est la 1.7.0." and "Ok ! FreshRSS va maintenant être mis à jour vers la version 1.3.2-beta." :/
What should I do?

**Comment by Alkarex** [comment]
Bonsoir Clément,
La branche *bêta* a été arrêtée il y a un bon moment. Nous n'avons plus que *master* (branche stable) et *dev* (développement). Avez-vous déployé une nouvelle version par dessus la votre, comme dit plus haut ?
Dans tous les cas, effacez d'éventuels anciens fichiers, comme `./data/last_update.txt` et `./data/update.php`.
Le système de mise à jour sera revu dans la prochaine version.

**Comment by ClementNX** [comment]
Super, je monte ainsi en version 1.8.
Bonne soirée !

**Comment by ClementNX** [comment]
J'ai toujours la même erreur que dans le premier message par contre.
Dois-je monter la version manuellement ?

**Comment by Alkarex** [comment]
Si vous avez bien effacé les fichiers susmentionnés, je ne sais pas trop pourquoi le message de mise à jour n'est pas correct, et il est plus prudent de faire la mise à jour à la main, oui.

**Comment by ClementNX** [comment]
Ok merci.
Bon j'pense qu'il va falloir que je fasse les mises à jours manuellement en attendant le prochain système ^^
