### ISSUE TITLE
Command-line interface for the database maintenance

### ISSUE THREAD

**Issue by lapineige** [FreshRSS/FreshRSS#1583]
Following the discussions here #1582, a CLI tool to do the database maintenance can be useful in case of broken configuration.

**Comment by aledeg** [comment]
What are the feature that we should include in such tool?

**Comment by lapineige** [comment]
In that case it was needed to do the database optimisation from the commandline (the web version always timed out).
That's all I need, but well if you have other ideas that might help in case of broken configuration...

Don't hesitate to ask me if you need any test.

**Comment by Alkarex** [comment]
Related to https://github.com/FreshRSS/FreshRSS/issues/918

**Comment by Alkarex** [comment]
Tests welcome https://github.com/FreshRSS/FreshRSS/pull/1663
