### ISSUE TITLE
PHP 7.1 - PHP Warning:  file_get_contents()

### ISSUE THREAD

**Issue by auricom** [FreshRSS/FreshRSS#1584]
Hello,

When using greader API with PHP 7.1, there is some warning in my nginx error log :

> *31 FastCGI sent in stderr: "PHP message: PHP Warning:  file_get_contents(): Failed to seek to position -1 in the stream in /config/www/freshrss/p/api/greader.php on line 26" while reading response header from upstream, client: 172.17.0.1, server: , request: "GET /api/greader.php/reader/api/0/stream/items/ids?output=json&s=user%2F-%2Fstate%2Fcom.google%2Freading-list&xt=user/-/state/com.google/read&n=10000&r=n HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "xxxx"

With PHP 7.0 this warning don't occur.

It seems that file_get_contents() got updated with PHP 7.1, and FreshRSS php code should be updated : https://github.com/neos/flow-development-collection/pull/821

**Comment by thomasrenes** [comment]
I'm seeing the same error in "/p/api/pshb.php" with PHP 7.1:

> PHP Warning:  file_get_contents(): Failed to seek to position -1 in the stream in /p/api/pshb.php on line 14

**Comment by Alkarex** [comment]
Thanks for the bug reports. Could you please try this fix? https://github.com/FreshRSS/FreshRSS/pull/1585

**Comment by thomasrenes** [comment]
Thanks, the warning messages are gone in my logs after applying the fix.
