### ISSUE TITLE
upgrade check should not warn if there is no new version available

### ISSUE THREAD

**Issue by oupala** [FreshRSS/FreshRSS#1586]
In FreshRSS, when someone check if a new version is available, the answer is displayed as a warning (in red) even if there is no new version available.

![screenshot](https://user-images.githubusercontent.com/13458743/27257103-fcbcb368-53ca-11e7-9e16-de47be35e59b.png)

If there is no new version available, the version used is the last one. Hence it should be a green answer, not a red one.

**Comment by Alkarex** [comment]
Fixed by @kevinpapst in https://github.com/FreshRSS/FreshRSS/pull/1701

**Comment by oupala** [comment]
It works well. Good job!
