### ISSUE TITLE
Invalid JSON input with EasyRSS and v1.7.0

### ISSUE THREAD

**Issue by NerosTie** [FreshRSS/FreshRSS#1587]
Since the release of FreshRSS v1.7.0, I can't synchronize anymore with EasyRSS. 

When I want to synchronize I have the error: `Synchronisation failed: Invalid JSON input`. 

Login for the API is ok, everything is green in the Installation checking, API tests are ok, everything else works… I have no idea where is the issue (it worked well with previous releases).

**Comment by Alkarex** [comment]
Hello @NerosTie 
It seems to work fine for me.
Which version of FreshRSS did you have before?
Did you update anything else on your server? What version of PHP are you running?

**Comment by NerosTie** [comment]
Sorry, I'm late. I didn't know how to fix this bug so I used a backup and it's ok now, with the last update. I think I can close this issue.

**Comment by Alkarex** [comment]
OK, feel free to re-open if the problem arises again
