### ISSUE TITLE
Scrolling Jumps Upon Feed Retrieval (Paging)

### ISSUE THREAD

**Issue by vindicatorr** [FreshRSS/FreshRSS#1588]
FreshRSS: 1.7.0
Chrome: 59.0.3071.86

I'm finding that when I'm scrolling through the feeds, when the next bunch of feeds are retrieved in the browser (paging), the feed position jumps much farther down and I have to scroll back up to find where I was.

**Comment by Alkarex** [comment]
The UI of the list of categories and feeds has been fully reworked in the /dev branch (FreshRSS 1.13.0 will be released in a few days). Tests and feedback much welcome, especially before the stable release.
