### ISSUE TITLE
Closed (folded) articles are drawn open (unfolded).

### ISSUE THREAD

**Issue by sjeon87** [FreshRSS/FreshRSS#1590]
An example feed is http://export.arxiv.org/rss/cs. 

The problem is that body parts of multiple closed (unfolded) articles still appear and I cannot close such articles. Strangely, this feed passes RSS validation: https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fexport.arxiv.org%2Frss%2Fcs

You can check the problem via https://songsong.postech.ac.kr/FreshRSS/i/?get=f_33 without login (or via your own FreshRSS.)

**Comment by aledeg** [comment]
There is probably something in the body that prevent such action. I've experienced such things with other feeds. It was a little bit different though since after a type of article all the other disappear. We should probably add something to render the article content in a safe way.

Good catch

**Comment by sjeon87** [comment]
Yes, I suspect missing tag escape or something (maybe not.) If time allows, I'll look into the issue.

An attachment is the XML feed backup causing the issue.
[cs.zip](https://github.com/FreshRSS/FreshRSS/files/1130143/cs.zip)

**Comment by sjeon87** [comment]
`cs.xml` in the above, I found:

    <dc:creator> &lt;a href=&quot;http://arxiv.org/find/cs/1/au:+Gorbachev_V/0/1/0/all/0/1&quot;&gt;V.N. Gorbachev&lt;/a&gt;, &lt;a href=&quot;http://arxiv.org/find/cs/1/au:+Denisov_L/0/1/0/all/0/1&quot;&gt;L.A. Denisov&lt;/a&gt;, &lt;a href=&quot;http://arxiv.org/find/cs/1/au:+Kaynarova_E/0/1/0/all/0/1&quot;&gt;E.M. Kaynarova&lt;/a&gt;, &lt;a href=&quot;http://arxiv.org/find/cs/1/au:+Metelev_I/0/1/0/all/0/1&quot;&gt;I.K. Metelev&lt;/a&gt;</dc:creator>

When I look into the corresponding article with `RSS feed mode` of FreshRSS:

    <dc:creator>
    <a href="http://arxiv.org/find/cs/1/au:+Gorbachev_V/0/1/0/all/0/1">V.N. Gorbachev</a>, <a href="http://arxiv.org/find/cs/1/au:+Denisov_L/0/1/0/all/0/1">L.A. Denisov</a>, <a href="http://arxiv.org/find/cs/1/au:+Kaynarova_E/0/1/0/all/0/1">E.M. Kaynarova</a</dc:creator>

An `a` tag of the last author isn't closed properly. And this is because **the given string of authors list is 255-letter long. So I guess this is DB related**. More examples can be found.

So my suggestion is:

1. For already collected feed: Before printing authors information, validate tag of authors. If it is invalid, replace text with a sort of *malformed authors information is removed*, whatever.
1. For future fix:
    1. Before pushing to the table, if authors information is too long: just keep text only.
    1. Modify table

I didn't check whether other fields have a similar issue.

The below is `RSS feed mode` data of `cs.xml`
[RssFeedMode.txt](https://github.com/FreshRSS/FreshRSS/files/1133701/RssFeedMode.txt)

**Comment by Alkarex** [comment]
Simple fix in https://github.com/FreshRSS/FreshRSS/pull/1615
Feedback appreciated
