### ISSUE TITLE
Logged Out when using Global View

### ISSUE THREAD

**Issue by redinsight** [FreshRSS/FreshRSS#1591]
When using the global view to view articles and choosing Mark All As Read on the bottom of the page I am immediately logged out and the articles are not marked as read. I do not have this problem in normal view or reading view, in those views everything works as expected.

**Comment by Alkarex** [comment]
Strange. I will try to have a look in a few days.

**Comment by Alkarex** [comment]
Sorry for the delay. Should be fixed in https://github.com/FreshRSS/FreshRSS/pull/1640
