### ISSUE TITLE
Feed menu jumps down to bottom

### ISSUE THREAD

**Issue by thomasrenes** [FreshRSS/FreshRSS#1593]
When using the the keyboard shortcuts to browse through the articles, sometimes the feed menu on the left randomly jumps down to the bottom of the screen.

After jumping to the previous feed (up arrow on keyboard) the menu jumps back up (where it's suppose to be) and stays there, even when going to the next article again.

I'm not able to replicate this issue, it just sometimes (once or twice a week) happen.

![feed_menu](https://user-images.githubusercontent.com/4504804/28104467-793018f4-66db-11e7-9cfc-00b8811706be.png)

FreshRSS Version: 1.7.0
FreshRSS Theme: Flat design
Browser: Chrome 59.0.3071.115 (64-bit) on OS X
Screen Resolution: 1440x900

**Comment by Alkarex** [comment]
I have also noticed the issue occasionally. Let me know whether you find out when it happens a bit more precisely

**Comment by Alkarex** [comment]
Might be the same as https://github.com/FreshRSS/FreshRSS/issues/1588

**Comment by Alkarex** [comment]
@thomasrenes Could you please give a try to this tiny patch? https://github.com/FreshRSS/FreshRSS/pull/1616

**Comment by thomasrenes** [comment]
@Alkarex Have applied the patch and will let you know in a few days if it works.

**Comment by Alkarex** [comment]
Any improvement, @thomasrenes ? :-)

**Comment by thomasrenes** [comment]
Sorry for not responding quicker.

This "jumping" issue has not occurred with the fix, but this seem to introduce some issues with the menu when opening FreshRSS in Chrome on an iPad. When scrolling down the menu disappears and seems to be only available when the browser position is on the top or bottom of the page.

**Comment by thomasrenes** [comment]
One more thing: In the desktop version the top item of the menu (the one below "Favorites") also disappears when scrolling down the news items list, while there is still enough space left to display the full menu. When scrolling up again the menu is fully displayed.

![scrolling_up](https://user-images.githubusercontent.com/4504804/30760638-3bf25e32-9fdb-11e7-974b-eb63bb7793b1.png)

![scrolling_down](https://user-images.githubusercontent.com/4504804/30760639-3bfb1e6e-9fdb-11e7-950a-60acb659f7bd.png)

**Comment by Alkarex** [comment]
The UI of the list of categories and feeds has been fully reworked in the /dev branch (FreshRSS 1.13.0 will be released in a few days). Tests and feedback much welcome, especially before the stable release.
