### ISSUE TITLE
[Feature Request] Auto Refresh/ Append New Articles Automatically

### ISSUE THREAD

**Issue by Eisa01** [FreshRSS/FreshRSS#1596]
Hello,

I like to monitor my subscriptions via a different monitor, however clicking to refresh makes this very hard.

Whenever there is a new article, will it be possible to append it to the current page or for the page to automatically refresh instead of giving us the refresh notification?

This will truly be very helpful,
Thanks!

**Comment by Alkarex** [comment]
Do I understand correctly that you have multiple tabs/windows/browsers opened, each showing a different feed or category?
Showing the new articles automatically is a bit problematic, because they might appear without the user noticing them and might end up being marked as read erroneously.
For the time being, here is already two suggestions:
1. make your browser to auto-refresh the tab regularly (e.g. built-in feature in Opera, or extension in Firefox)
2. or make a FreshRSS extension in JavaScript to auto-reload the page when there is a notification
    * E.g. with https://github.com/FreshRSS/Extensions/tree/master/xExtension-CustomJS

**Comment by Eisa01** [comment]
Thank you for your solutions, while this is somewhat feasible, I must ask if are there any plans to automatically append them.

Showing new feeds automatically won't be problematic, if mark as read on scroll is disabled.

Refreshing the whole page is somewhat problematic, because if the time criteria is met and I was reading an article (it will forcefully refresh closing my currently open article)

If this isn't planned, then perhaps there is another solution that is somewhat close to what I have in mind?

**Comment by Alkarex** [comment]
I do not have a plan to add this feature myself, but an extension would be possible (see e.g. a bit of documentation http://doc.freshrss.org/en/developers/03_Backend/05_Extensions/ or some examples https://github.com/FreshRSS/Extensions ).
I am still unsure on how the user interface would be for your case, even if you do not use "read on scroll". If you automatically add new articles at the top, you may not notice them before clicking "mark all as read" at the bottom or from the menu.

**Comment by Alkarex** [comment]
Ah, maybe you use the descending order, with new articles at the bottom?

**Comment by Eisa01** [comment]
@Alkarex 
Thank you for your response.

Perhaps to make users notice that there are new articles (instead of click to refresh notification) it says (click to scroll up to new articles).

I will see what I can do regarding the extension. Hopefully it is do-able.

Thank you!

**Comment by Eisa01** [comment]
@Alkarex 
I was able to create the extension with the features I had in mind
https://github.com/Eisa01/FreshRSS---Auto-Refresh-Extension

You can link this extension to the third-party extensions list ^ ^

**Comment by Alkarex** [comment]
Congrats :-)
You are welcome to make a pull request to https://github.com/FreshRSS/Extensions/blob/master/README.md to add it to the list if you feel like it
