### ISSUE TITLE
Support for DB usernames longer than 16 characters

### ISSUE THREAD

**Issue by geekafy** [FreshRSS/FreshRSS#1597]
Hello,

I use Virtualmin and when DB users are created, the following format is used:

`username.domain_name`

This can generate long usernames.

Can FreshRSS support usernames longer than 23 characters?

I tried adding the values manually in the config file but the limit was still 23 characters.

Thanks!

**Comment by Alkarex** [comment]
Hello,
We use the user name for a few things, each of which have their constraints.
In particular, the username is used for MySQL / PostgreSQL tables, as well as for folder and file names.
https://dev.mysql.com/doc/refman/5.7/en/identifiers.html

Since FreshRSS version 1.6.3, the check is `/^[0-9a-zA-Z]|[0-9a-zA-Z_]{2,38}$/` so already more than the 23 characters you refer too.

Related: https://github.com/FreshRSS/FreshRSS/pull/1423

**Comment by Alkarex** [comment]
P.S.;
1. Do you say that you need a period `.` in usernames?
2. Are you talking about FreshRSS usernames, or database usernames?

**Comment by Alkarex** [comment]
Ah, sorry, I can see now that you are talking about database usernames, and not FreshRSS usernames, right?

**Comment by Alkarex** [comment]
I do not think FreshRSS makes any check for the maximum length of the DB username. However, databases do have limitations, e.g.
https://dev.mysql.com/doc/refman/5.7/en/user-names.html

**Comment by geekafy** [comment]
That is correct, my current database user (as indicated by MySQL) is 25 char long.

As an indication, when I'm in the setup page, I am unable to enter more than 16 char in the Database username box.

If I add the full username in the FreshRSS config file, it still does not recognize more than 16 char.

I should have named the issue "Support for DB usernames longer than 16 characters" and not 23 - Title is now modified.

Any idea where the limitation is coming from?

**Comment by Alkarex** [comment]
@geekafy Ah, I though you edited `config.php` manually (this should work). In the graphical install, there is indeed a check for a max length
https://github.com/FreshRSS/FreshRSS/blob/master/app/install.php#L634
Is this what you are referring to? If yes, this can be patched

**Comment by Alkarex** [comment]
Patch for the graphical install checks https://github.com/FreshRSS/FreshRSS/pull/1601

**Comment by geekafy** [comment]
Yes, that is it!

I thought it was something more than just the GUI since I did update the `config.php` and it did not work. I must have done something wrong.

Super, can't wait to test it. When will 1.8.0 be published?

Will it work if I change the line in my `install.php` to indicate the following in my 1.2.0 install?

`<input type="text" id="user" name="user" maxlength="30" pattern="[0-9A-Za-z_.-]{1,30}" value="<?php echo isset($_SESSION['bd_user']) ? $_SESSION['bd_user'] : ''; ?>" tabindex="3" />`

Thanks!

**Comment by Alkarex** [comment]
Yes, it should work. I think there will be a 1.7.1 containing this patch (among others) prior to 1.8.0, but the /dev branch is very usable, if you can give it a try.
