### ISSUE TITLE
Call to undefined function need_info_update()

### ISSUE THREAD

**Issue by jmtrivial** [FreshRSS/FreshRSS#1598]
Hi all,

I migrated my FreshRSS instance from a 1.3.0 to a 1.5.0, then a 1.6.3. 
I want to migrate now to a 1.7.0. but it generates an error 500, with the following message in my log file:

```
[20-Jul-2017 22:01:23 Europe/Berlin] PHP Fatal error:  Uncaught Error: Call to undefined function need_info_update() in [...]/rss/app/Controllers/updateController.php:196
Stack trace:
#0 [...]/rss/lib/Minz/Dispatcher.php(119): FreshRSS_update_Controller->applyAction()
#1 [...]/rss/lib/Minz/Dispatcher.php(48): Minz_Dispatcher->launchAction('applyAction')
#2 [...]/rss/lib/Minz/FrontController.php(84): Minz_Dispatcher->run()
#3 [...]/rss/p/i/index.php(46): Minz_FrontController->run()
```

**Comment by Alkarex** [comment]
Hello,
Three options:
1. Please have a look at https://github.com/FreshRSS/FreshRSS/issues/1577
2. or make a manual install (unpack new ZIP version on top of the existing
3. or install from git
In any case, please make a backup of your files :-)

**Comment by jmtrivial** [comment]
Thank you for that. Sorry that I didn't read correctly these messages... 
And thank you for this awsome FreshRSS project!
