### ISSUE TITLE
check for new version available does not report the right version

### ISSUE THREAD

**Issue by oupala** [FreshRSS/FreshRSS#1599]
I'm using FreshRSS v1.7.0 and I'm using the `/freshrss/i/?c=update` link to check for a new available version. It report a wrong version:

> Arf ! Nouvelle version 1.3.0-beta disponible, mais veuillez vérifier les droits sur le répertoire /opt/FreshRSS-1.7.0. Le serveur HTTP doit être capable d’écrire dedans.

I though FreshRSS was able to check for a new version even if it was impossible to write to the whole FreshRSS directory, but it appears to report a wrong available version.

Do you have any explanation about that?

**Comment by Alkarex** [comment]
Hum, strange. Maybe @marienfressinaud might know. In any case, I would like to revise the update mechanism in 1.8.0 https://github.com/FreshRSS/FreshRSS/issues/907

**Comment by oupala** [comment]
Yes, quite strange.

As a clue, I can say that my ansible role (that I'm still planning to contribute when it's stable) leads me to keep my `data` directory. That might explain some things...

**Comment by marienfressinaud** [comment]
You can update to 1.3.0-beta from 1.1.x versions only 🤔 Can you look at the `./constants.php` file for the `FRESHRSS_VERSION` constant?

**Comment by oupala** [comment]
The constant seems ok:

```php
<?php
define('FRESHRSS_VERSION', '1.7.0');
define('FRESHRSS_WEBSITE', 'http://freshrss.org');
```

**Comment by marienfressinaud** [comment]
I just had a look to the source code, you might have a `last_update.txt` and a `update.php` files under `./data`. You should remove both of them and try again

**Comment by oupala** [comment]
Thanks a lot @marienfressinaud , you spotted the right problem.

Removing both files fixed the problem!

It could be a good idea to list the *usual* content of the data directory, so that users can check if their data directory is ok.

**Comment by marienfressinaud** [comment]
Well, usual content is almost listed in https://github.com/FreshRSS/FreshRSS/tree/master/data :). Only `do-install.txt` is removed after first install. All the other files such as log files or `last_update.txt` and `update.php` can be deleted.

Can we close this ticket or do you think there is more to document?

**Comment by oupala** [comment]
Sorry for the delay.

It is (was) fine to close the ticket. Thanks.

The differences between https://github.com/FreshRSS/FreshRSS/tree/master/data and my local data directory are:

- `do-install.txt` has been **removed** (at install time)
- `config.php` has been **added** (at install time)
- `last_update.txt` has been **added** (at new version check)
