### ISSUE TITLE
Can't add a RSS

### ISSUE THREAD

**Issue by IPv777** [FreshRSS/FreshRSS#1607]
Hi, I can't add this RSS : http://homputersecurity.com/feed/
An another person could try please?

**Comment by Raymondcal** [comment]
Doesn't work here, too.
I don't know why, there is no log in FreshRSS either.

**Comment by Alkarex** [comment]
The error message is: `cURL error 22: The requested URL returned error: 400 Bad Request [http://homputersecurity.com/feed/]`

Trying manually, it looks like there is a server-side rule on the user-agent *SimplePie*. Maybe someone has been refreshing that feed too much...

```sh
curl -v -A 'SimplePie/1.5' 'http://homputersecurity.com/feed/'
```

```
HTTP/1.1 400 Bad Request
...
The page you are trying to access is restricted due to a security rule.
```

**Comment by elevatorsimulator** [comment]
I can add `http://homecomputersecurity.com/feed` but not `https://borodust.org/atom.xml`; I get `Unknown error for feed [https://borodust.org/atom.xml]` in the log file.

**Comment by azlux** [comment]
I have contact the creator of homecomputersecurity , that why it's working now. @elevatorsimulator you can send an email to the creator of borodust to remove the filter on the rss.

**Comment by elevatorsimulator** [comment]
Sorry, what filter? I have no trouble borodust's feed to other "rss"
readers (e.g. RSSOwl), so I'm not sure the problem lies with the feed
and not with FreshRSS.

**Comment by Frenzie** [comment]
I have no trouble adding borodust anymore. But the filter would presumably have been for the "SimplePie" user agent, like @Alkarex said.

**Comment by elevatorsimulator** [comment]
You are able to add his feed? What version of FreshRSS are you using? I'm using the latest repo version, and it doesn't work.

I traced back the error message (`Unknown error for feed`). It gets thrown in line 258 of ./app/Models/Feed.php, and it gets thrown because `$mtime = $feed->init()` evaluates to false as a boolean. The object $feed is an instance of SimplePie, and for some reason it fails to initialize.

Update: It now works all of a sudden.

**Comment by Frenzie** [comment]
Actually I never checked before, so "anymore" might be inaccurate. Anyway, I'm using 1.8.

**Comment by Alkarex** [comment]
Confirmed to work in FreshRSS 1.9.0 with the new default (and customisable) user-agent.
