### ISSUE TITLE
Item alignement on login page

### ISSUE THREAD

**Issue by eliemichel** [FreshRSS/FreshRSS#1620]
On login page, the margin on the left on FreshRSS logo is much bigger than the one on the right of the "Login" link:

![freshrss2](https://user-images.githubusercontent.com/5802849/29555961-957920f0-8724-11e7-8dbb-112c935c9c0c.png)

I think the best would be not to use centering to place those element on this view, but just fixed margins. But I don't how much it would affect other things.

**Comment by Alkarex** [comment]
Hello @eliemichel 
If you are able, you are welcome to send a suggestion of CSS patch

**Comment by Alkarex** [comment]
Kindly fixed by @pattems with https://github.com/FreshRSS/FreshRSS/pull/2122
