### ISSUE TITLE
Add a way to mark article as read in reading view

### ISSUE THREAD

**Issue by eliemichel** [FreshRSS/FreshRSS#1621]
When using the reading view (where articles are completely expanded), I did not find any quick way of marking what I'm reading as read (to have it disappear from the feed). Did I just missit? Otherwise it would be a great little UI improvement.

**Comment by Alkarex** [comment]
Related to https://github.com/FreshRSS/FreshRSS/issues/1545

**Comment by aledeg** [comment]
@eliemichel I don't know exactly what you're looking for but if you use the shortcut to mark as read the article and that you check ```Hide articles after reading``` in the configuration ```Reading``` section, articles will disappear from the feed.
Is this something that works for you ?
Do you have something in mind a little bit different ?

**Comment by eliemichel** [comment]
@aledeg I was thinking about a button following the view, but yeah I did not think about using shortcuts. I don't have the reflex of using shortcuts in web apps. This solves my usage then, though it does not prevent somebody else to wonder the same.

**Comment by aledeg** [comment]
Let's reopen that issue if the question arise in the future.

**Comment by aledeg** [comment]
@eliemichel I've tried something #1761. Let me know what you think of that.
