### ISSUE TITLE
"Update server cannot be found" when trying to update from 1.6.3

### ISSUE THREAD

**Issue by tzimail** [FreshRSS/FreshRSS#1624]
Currently running FreshRSS which I installed using Softaculous. Previous updates have worked without issue but now that I'd like to update to 1.7.0 I get the following error when I try to update through the FreshRSS interface: 

"Damn! Update server cannot be found. [https://update.freshrss.org?v=1.6.3]"

The logs show:

"Error during update (HTTP code 0): Failed to connect to update.freshrss.org port 443: Connection refused"

Any ideas on what I can try to get the update to work?

**Comment by Alkarex** [comment]
The server seems to be up. Could you please try again?
If it still fails, could you please give some information about your system (OS version...) as there might be an HTTPS problem for old systems.

**Comment by tzimail** [comment]
Sorry for the late reply. I have tried it a number of times over the last couple of days and still get the same result. 

I have FreshRSS installed through a shared hosting provider. Was installed using Softaculous (cPanel). The OS listed on cPanel is Linux but doesn't say anything more than that.

**Comment by Alkarex** [comment]
Would you be able to try a cURL command from your server?

```sh
curl -v 'https://update.freshrss.org?v=1.6.3'
```

**Comment by aledeg** [comment]
@georgetzimas We are currently in version 1.17.0. I guess there is nothing more we can do at the moment. I am closing this but feel free to reopen if needed.
