### ISSUE TITLE
Combined filtering

### ISSUE THREAD

**Issue by valodiadeseynes** [FreshRSS/FreshRSS#1625]
Hi,

I don't know if this feature doesn't exist or if it exists and I have missed it. I know you can combine filters like this: 

`author:, intitle:, inurl:, #`

It seems to only include articles that match all of those filters at once but what I'd like to do is put a string of filters in the search bar that will show me the articles that match AT LEAST one of the filters. Something like:

`author: OR intitle: OR inurl: OR #`

Is this possible?

**Comment by aledeg** [comment]
Related to #879. I am closing this issue but you should add something in the aforementioned issue.

**Comment by Alkarex** [comment]
Indeed, the existing system combines filters with AND, and there is no OR yet.
