### ISSUE TITLE
I can't consult the FreshRSS log page because of lack of memory

### ISSUE THREAD

**Issue by Massedil** [FreshRSS/FreshRSS#1626]
I don't know what is the recommended max_memory value, but it seems that showing the logs consumes a lot of memory.

> PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32 bytes) in /var/www/FreshRSS/app/Models/LogDAO.php on line 9

Is it normal ?

Config : 
- FreshRSS : 1.7.0
- PHP : 5.6.30
- storage system : SQLite
- size of logs.txt : 44M
- size of db.sqlite : 175M

**Comment by Alkarex** [comment]
Indeed, we have a ticket to do something about the logs, maybe built-in FreshRSS or at least instruct users about how to log_rotate them https://github.com/FreshRSS/FreshRSS/issues/1562

**Comment by Alkarex** [comment]
For now, you can just look at the logs manually and then remove them. They will be re-created and as long as they are small enough, they will be visible from the FreshRSS Web interface.

**Comment by Alkarex** [comment]
To be continued in https://github.com/FreshRSS/FreshRSS/issues/1562
