### ISSUE TITLE
"purge" button in the archiving setting does not delete all articles are supposed to

### ISSUE THREAD

**Issue by giorgiobeggiora** [FreshRSS/FreshRSS#1628]
I tried to set 1 month (please add 0 as valid value) but some old articles remains (scraped with the cron that was using the unsupported php version #1604 ).

@Alkarex you already have my hosting credentials so you can check by yourself.

Thanks a lot.

**Comment by Alkarex** [comment]
Yes, what you observe is the current expected behaviour.
I am preparing a custom DB fix for you. In other similar cases I would suggest exporting the OPML list of articles, deleting and re-creating the user, and re-importing the OPML list. We could add a command-line function to clear all articles, but I would rather not have that in the Web interface.

**Comment by Alkarex** [comment]
So, it should be fixed for your server.

I have run that on your DB:

```sh
sqlite3 db.sqlite
```

```sql
DELETE FROM entry;
VACUUM;
```

And then a DB optimization and a feed refresh from the FreshRSS Web UI.

If you want, there is a copy of the old DB `db0.sqlite` in the same folder. You can delete it when it is not needed anymore.

**Comment by giorgiobeggiora** [comment]
Thank you a lot, I was sharing to help and I was helped XD

**Comment by rezad1393** [comment]
is this still default behavior? because I have the same problem.

**Comment by rezad1393** [comment]
> Yes, what you observe is the current expected behaviour.
> I am preparing a custom DB fix for you. In other similar cases I would suggest exporting the OPML list of articles, deleting and re-creating the user, and re-importing the OPML list. We could add a command-line function to clear all articles, but I would rather not have that in the Web interface.

is this still default behavior? because I have the same problem.

**Comment by Alkarex** [comment]
@rezad1393 Please open a new issue instead and explain your precise problem
