### ISSUE TITLE
1.7.1-dev : no update found even after commit

### ISSUE THREAD

**Issue by Draky50110** [FreshRSS/FreshRSS#1650]
Hello.

Using 1.7.1-dev, I try to look at updates if there is a new commit on GitHub but FRSS keeps telling there is no update.

Is it normal ?

**Comment by Alkarex** [comment]
Hello @Draky50110 
Is your FreshRSS installed by ZIP or by git?

For git, please see https://github.com/FreshRSS/FreshRSS/tree/dev/cli#install-and-updates

**Comment by Draky50110** [comment]
ZIP with wget (SSH)

**Comment by Alkarex** [comment]
Could you please try https://github.com/FreshRSS/FreshRSS/issues/1599#issuecomment-318163430
Otherwise, just deploy a new ZIP on top of the existing installation.
The whole update process needs to be improved https://github.com/FreshRSS/FreshRSS/issues/907

**Comment by Draky50110** [comment]
No "update.php" file, only last_update.txt and deleteing this file does not change anything.

okay for deploying ZIP over installation.

**Comment by marienfressinaud** [comment]
I'll probably have a look, it seems that I have the same problem ;)

**Comment by ghost** [comment]
using the 1.7 zip file
I got the same issue, no update available. Even after removing update.php and lastupdate.txt under ./data/

dropping the new zip and keeping the previous configuration has worked, not convenient but working.

**Comment by marienfressinaud** [comment]
It was a problem on update server, should be fixed now!

**Comment by Draky50110** [comment]
Ok for me :)
I close ;)
