### ISSUE TITLE
DB add JSON field

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#1654]
I suggest adding a JSON field to the feed table, to add custom properties (e.g. user-agent, mark as unread upon update, strip data...) without having to add many new columns.
E.g. useful for:
* https://github.com/FreshRSS/FreshRSS/issues/1627
* https://github.com/FreshRSS/FreshRSS/issues/891

**Comment by Frenzie** [comment]
Also potentially useful for extensions.

**Comment by Alkarex** [comment]
It looks like letting PHP parse and stringify JSON would be the most portable.
Notes, if we wanted to use databases native JSON abilities:
* MySQL 5.7.8+ https://dev.mysql.com/doc/refman/5.7/en/json.html (we so far support MySQL 5.5.3+)
  * In the Ubuntu world, this means 16.04 LTS instead of 12.04 LTS
* PostgreSQL 9.2+ https://www.postgresql.org/docs/9.2/static/functions-json.html
* SQLite requires an extension :-( https://sqlite.org/json1.html

**Comment by Frenzie** [comment]
MariaDB starting with 10.0.16 https://mariadb.com/kb/en/library/connect-json-table-type/ (that means Debian Jessie and Ubuntu 16.04LTS)

I don't know how adding JSON to these databases works, but with any luck someone already created a wrapper function?

**Comment by Alkarex** [comment]
Well, for the needs I foresee, the native JSON functions would have been nice but not really needed. A `varchar` type with JSON parsing / stringifying in PHP should be enough.

**Comment by Frenzie** [comment]
Sure. It's just a performance thing. I don't know if it's a performance thing that *matters* but it just sounds so self-evident that I think a solution must already exist.

**Comment by perrinjerome** [comment]
👍 making it a simple `varchar` column seems enough. I just want to suggest using a column type where there's no limit on the length, such as `text` or `blob`.

**Comment by Alkarex** [comment]
Continues in https://github.com/FreshRSS/FreshRSS/pull/1838
