### ISSUE TITLE
Impossible de finaliser la configuration initiale.

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#1659]
Bonjour,

il m'est impossible de finaliser la configuration initial, il ne prends pas le login et mot de passe et réglage de rétention des articles. Je ne peux passer cette étapes.

J'ai un reverse proxy nginx (TLS + HTTP2) avec un certificat wilcard **auto-signé**. "https://rss.xxxxx.com/"
en local c'est un apache2 (HTTP seulement). "http://XXX.XXX.XXX.XXX/freshrss/"

En local cela fonctionne parfaitement.

Avez-vous déjà rencontré ce cas de figure ?

Configuration faite en local : Ok
Tentative de login depuis le reverse proxy : nOk
![image](https://user-images.githubusercontent.com/1993406/31333233-908ac7b6-ace9-11e7-8492-4fa704f5c12e.png)

En vérifiant les log depuis FreshRSS :
    

> Password mismatch for user=amokrane, nonce=, c=...

La valeur de "c" est différente à chaque tentative.
![image](https://user-images.githubusercontent.com/1993406/31333248-9ee94102-ace9-11e7-9265-3d407df14564.png)

> Avez-vous regardé vos logs du serveur Web, ainsi que la console JavaScript du navigateur ?
Peut-être que vous pourriez m'envoyer l'adresse de votre serveur en message privé.

Merci pour votre réponse ! Oui j'ai supprimé les log déjà existant concernant le sous-domaine rss (j'utilise un fichier log par sous-domaine) puis retenté de m'identifier : aucun log créée :(

Pour la console:
![image](https://user-images.githubusercontent.com/1993406/31333804-ca4a8e8a-aceb-11e7-810a-f3f9381fcacb.png)
et une fois le login +mdp validé
![image](https://user-images.githubusercontent.com/1993406/31334337-30459f98-acee-11e7-9c17-5eb296715310.png)

Voici ma config nginx :

> server {
>     listen 80;
>     return 301 https://$host$request_uri;
> }
> server {
>     listen 443 ssl http2;
>     server_name rss.xxxx.com;
>     ssl_certificate /etc/nginx/server.crt;
>     ssl_certificate_key /etc/nginx/server.key;
>     ssl_session_timeout 1d;
>     ssl_session_cache shared:SSL:50m;
>     ssl_session_tickets off;
>     ssl_protocols TLSv1.2;
>     ssl_ciphers
> 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-$
>     ssl_prefer_server_ciphers on;
>     add_header Strict-Transport-Security max-age=15768000;
>     ssl_stapling on;
>     ssl_stapling_verify on;
>     resolver 80.67.169.12;
>     access_log /var/log/nginx/rss.access.log;
>     location / {
>       proxy_set_header Host $host;
>       proxy_set_header X-Real-IP $remote_addr;
>       proxy_pass_header X-XSRF-TOKEN;
>       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>       proxy_set_header X-Forwarded-Proto $scheme;
>       proxy_pass http://10.0.0.202/freshrss/;
>       proxy_read_timeout 90;
>       proxy_redirect http://10.0.0.202/freshrss/ https://rss.xxxx.com;
>     }
>   }
> 

Je vous envoi le lien vers https://rss.xxxx.com en privé.
Encore une fois un grand **merci** pour votre aide et ce magnifique outil qu'est FreshRSS !

**Comment by ghost** [comment]
_**Update:**_

Depuis la console de Firefox:

![image](https://user-images.githubusercontent.com/1993406/31340595-f64b5896-ad06-11e7-9b69-a6070903792f.png)
![image](https://user-images.githubusercontent.com/1993406/31340631-1a21f522-ad07-11e7-9070-1ec8e204d547.png)

Par contre je n'ai pas trouvé commen vous envoyer un msg privé :(

**Comment by Alkarex** [comment]
Juste un courriel à https://alexandre.alapetite.fr/cv/ :-)

**Comment by Frenzie** [comment]
J'aimerais obtenir un doctorat, mais le financement est très difficile à obtenir. :-(

(Je ne suis pas sûr si je veux tenterai une dernière fois ce janvier.)

**Comment by Alkarex** [comment]
Erreur de message, @Frenzie ? 🤓

**Comment by Frenzie** [comment]
Non, c'est off-topic mais grace a ton cv. ;-)

**Comment by ghost** [comment]
LOL

> Juste un courriel à https://alexandre.alapetite.fr/cv/ :-)

c'est fait !

**Comment by Alkarex** [comment]
@Frenzie 
* http://www.dtu.dk/english/career
* https://en.itu.dk/about-itu/vacancies
* http://diku.dk/english/about/vacancies/
😉

**Comment by Alkarex** [comment]
Le `nonce` vide des les logs indique que la session n'a pas marché. En l’occurrence, l'entête HTTP `Set-Cookie` n'est pas envoyée, et en conséquence, les requêtes HTTP ne comportent pas le `Cookie` nécessaire.
Votre reverse-proxy filtre un peu trop :-P

**Comment by Alkarex** [comment]
P.S. Si vous ne voulez pas de cookie, la connexion par mot de passe HTTP est aussi possible dans FreshRSS.

**Comment by ghost** [comment]
Je vais revoir la partie reverse proxy !
Un grand merci pour votre aide !
:D
