### ISSUE TITLE
Mobile App

### ISSUE THREAD

**Issue by sgtcoder** [FreshRSS/FreshRSS#1664]
I know this is more for an email, but you guys don't have an email option.

Are there any supported Android applications to work with FreshRSS? I liked when Press existed and we had our own application and we can use widgets. I used to use Fever with Press, but both projects were discontinued.

**Comment by Alkarex** [comment]
Hello @codermjb 
Yes, see:
* https://github.com/FreshRSS/FreshRSS/blob/master/README.md#compatible-clients
* https://github.com/FreshRSS/FreshRSS/issues/328 (in French)

I personally use News+ (closed source) and I forked EasyRSS https://github.com/Alkarex/EasyRSS (open source, but I do not currently have time to maintain it much myself - help much welcome).

I hope this helps :-)

**Comment by sgtcoder** [comment]
@Alkarex ahh sorry, I didn't see that bottom part! Yes, News+ (pretty decent design too) with that extension seems to be what I am looking for. I hope either of you don't abandoned these projects like the previous developers!

Let me know if you ever need help or something. Thank you so much! Now time to launch FreshRSS and give it a test drive!

**Comment by Alkarex** [comment]
FreshRSS has an active development :-)
For the clients, News+ does not seem to be much supported but is still working fine, and EasyRSS would need some more blood.

**Comment by codermjb** [comment]
Everytime I check this option and then save it unchecks it: Allow anonymous refresh of the articles

**Comment by codermjb** [comment]
None of the RSS feeds work with FreshRSS.

Example: http://www.atrailrunnersblog.com/feeds/posts/default
