### ISSUE TITLE
Unable to use Web Based CRON JOB

### ISSUE THREAD

**Issue by sgtcoder** [FreshRSS/FreshRSS#1665]
I get a 403 when loading /app/actualize_script.php in Google Chrome. If I remove the contents of the htaccess file, this then loads. I have the anonymous for syncing enabled and that still gives 403 error.

**Comment by sgtcoder** [comment]
Putting this in the app/.htaccess file seemed to keep security the same, but opening it up to be able to do a web based CRON job to sync.

```
<FilesMatch ^"actualize_script.php">
 Order	Allow,Deny
Deny	from all
Satisfy	all
</FilesMatch>
```

**Comment by Alkarex** [comment]
Hello,
This script is for command line, not for Web requests.
I would recommend setting up a normal cron job (non-Web).
There is another issue to track the special need of Web cron https://github.com/FreshRSS/FreshRSS/issues/613

**Comment by sgtcoder** [comment]
I changed the htaccess to run as web, but what is wrong with running it as a Web Cron Job? Everyone does them that way, and the only reason why I do it that way is so I can test my cron job remotely and easily manage all my cron jobs and not have to type out the full server paths to everything.

**Comment by Alkarex** [comment]
A proper Web-cron option will come and there is already a not-that-bad approach https://github.com/FreshRSS/FreshRSS/issues/613 . Reasons to refrain from using a CLI-cron as Web-cron include security (e.g. risks of DOS, leak of usernames and list of feeds, system info leaks, etc.) and performance / stability (Web-cron job are not suited for very long tasks and risk being killed in the middle of an operation).

With the Web root of FreshRSS being `./FreshRSS/p/`, then `./FreshRSS/app/actualize_script.php` is not even supposed to be exposed to the Web (the `.htaccess` was just another protection).
