### ISSUE TITLE
Syncing does not work in mobile apps

### ISSUE THREAD

**Issue by sgtcoder** [FreshRSS/FreshRSS#1666]
I setup syncing with News+ Premium and I get a sync error: https://www.dropbox.com/s/afydz4hbmzr7pb1/Screenshot_20171011-142119.png?dl=0

**Comment by sgtcoder** [comment]
Looks like it's something to do with %2F which is a forward slash encoded.

Any time %2F is passed it gives 404 error not found: http://prntscr.com/gw9qdi

After hours of researching I had to enable encoded slashes, but extra configuration for cPanel.

Enable Slashes: http://blog.simplytestable.com/allowing-slashes-in-url-path-with-apache/
Use this Guide to create a vhost template, apply in VirtualHost: https://documentation.cpanel.net/display/EA/Custom+Templates

Then rebuild config and restart apache: 

/usr/local/cpanel/scripts/rebuildhttpdconf
/usr/local/cpanel/scripts/restartsrv_httpd

Then my sync started working immediately.

**Comment by Alkarex** [comment]
Yes. Our documentation is not that visible, but you should run those tests available in the `/api/` folder from a Web browser.
See more on https://github.com/FreshRSS/FreshRSS/issues/443#issuecomment-36666133

For Apache used with News+, the relevant config is http://httpd.apache.org/docs/trunk/mod/core.html#allowencodedslashes

Furthermore, I can see that you have `/p/` in your public path. I suggest you make the `./FreshRSS/p/` directory the root of your Web server.

**Comment by sgtcoder** [comment]
Please also add this to the documentation as well for cPanel. cPanel requires a template to be made and backed up:
Use this Guide to create a vhost template, apply in VirtualHost: https://documentation.cpanel.net/display/EA/Custom+Templates

Then rebuild config and restart apache:

/usr/local/cpanel/scripts/rebuildhttpdconf
/usr/local/cpanel/scripts/restartsrv_httpd

I will look into only making the p the main path. So the rest of the files can load before? Was that in the documentation? I read something about user data not being public. Talk about security, you got it hardcore on here, and it's only public RSS feeds :-)

**Comment by Alkarex** [comment]
:-)
Documentation is not our strongest asset, but having `./FreshRSS/p/` as the root is suggested there:
* https://github.com/FreshRSS/FreshRSS/blob/master/README.md#installation
* https://freshrss.github.io/FreshRSS/en/users/01_Installation.html (the nginx example)

**Comment by sgtcoder** [comment]
Thank you. You do have more documentation than most, they are just in different locations.

It just sucked having to spend about several hours trying to figure this out yesterday when Fever worked out of the box.

I like your development better though. Fever was discontinued and had lack of full API support. Just need more updates done over time and that News+ developer needs to update for Android 7... what a fantastic app, he did so much with it, but it needs modern updates. In a full completed package, this will then be perfect and I could never complain and it would outperform previous developers work.

This has a lot of potential, Fever also had where you can assign a feed to multiple categories.

I don't know what the userbase for self hosted RSS is. Is it big? I don't know if there are a lot of users and later in development once they get the users on their system and have it polished up, developers find out there aren't millions of users and just abandon everything. Leaving you spend all this money so they can collect then end.

I will get back to you on feedback and other minor things. Maybe I can help contribute some code or code ideas. Honestly, I like where this is headed towards and hope to see it continue in the future.

**Comment by Alkarex** [comment]
I do not know how many FreshRSS users there is out there, but an indication is:
![image](https://user-images.githubusercontent.com/1008324/31514872-741d0c90-af93-11e7-9f3c-8410ef3856aa.png)
There also is a number of smaller as well as larger self-hosted RSS solutions.
