### ISSUE TITLE
Allow anonymous refresh does not save

### ISSUE THREAD

**Issue by sgtcoder** [FreshRSS/FreshRSS#1667]
Everytime I check this option and then save it unchecks it: Allow anonymous refresh of the articles. I was able to manually edit this in the config file.

**Comment by Alkarex** [comment]
~~Indeed. Will be fixed.~~

**Comment by Alkarex** [comment]
Looking at it again, it is because we only allow to enable *anonymous refresh* when *anonymous reading* is enabled.

**Comment by sgtcoder** [comment]
That makes sense now. So what are those features anyways? I thought that was so you could run the cron job.

**Comment by Alkarex** [comment]
They are to enable anonymous users (without login / password), and are not related to the cron.

**Comment by edsu** [comment]
This is super confusing to a new user.

**Comment by plqu** [comment]
Why can't I enable anonymous refresh without allowing anonymous reading? That seems like a huge security hole I don't want other people reading my articles, but there's no worries about leaving access open to refresh so I don't have to deal with authentication for that.

**Comment by Alkarex** [comment]
@plqu It is of course possible to refresh feeds without making your instance public. I am updating the documentation to make it clearer https://github.com/FreshRSS/FreshRSS/pull/4355

See preview https://github.com/FreshRSS/FreshRSS/blob/27436d284e789023c8446919ac6b07de1426dad1/docs/en/users/03_Main_view.md#online-cron
