### ISSUE TITLE
Duplicate images

### ISSUE THREAD

**Issue by Cavabanga** [FreshRSS/FreshRSS#1668]
dup images from https://www.yaplakal.com/news.xml

![222](https://user-images.githubusercontent.com/32729253/31482606-600410d8-af42-11e7-93e9-41d216095c65.PNG)

![111](https://user-images.githubusercontent.com/32729253/31482493-04e15224-af42-11e7-8e66-ccab46a7e37b.PNG)

**Comment by aledeg** [comment]
There's nothing we can do about it. The feed embedded the image and have media files with those same images.
That's why they are displayed twice.

**Comment by Alkarex** [comment]
If we were to do something, it could be to search whether attachments are already in the body of the article

**Comment by thomasrenes** [comment]
I see the same thing with other RSS Feeds, it seems easy to work around this by the solution @Alkarex proposes.

Changing this line in Feed.php:
`if (strpos($mime, 'image/') === 0) {`
to:
`if (strpos($mime, 'image/') === 0 && strpos($content, $elink) !== 0) {`

Do you guys see any problem with this?

**Comment by Alkarex** [comment]
@thomasrenes Yes, your proposition seems quite fine to me, although not super robust (e.g. if the link is not as an image, or in a comment, or in plain text, etc.). Could you please make a pull request with your suggestion, so we can discuss it further?

**Comment by squromiv** [comment]
Could you open it again?Or should i create a new one?

**Comment by Alkarex** [comment]
@squromiv Re-opened :-)

**Comment by serrnovik** [comment]
Is there at least quick workaround to this? The issue has been open for quite a while. At least making preference to show attachments as link vs previews would do the trick to my opinion. 

update: superfast workaround with custom css (before fix)
`
.enclosure
{
   float:left;
}
.enclosure-content
{
   margin:0px; 
   padding:0px;
}
.enclosure-content video
{
   display:none;
}
.enclosure-content img
{
   max-width:40px;
}
`

**Comment by Dreomite** [comment]
This gets even worse with several preview images. (Example: https://backend.deviantart.com/rss.xml?type=deviation&q=by%3Ayuumei+sort%3Atime+meta%3Aall) Is FreshRSS supposed to display all the thumbnails?

<details>
<summary>Screenshot</summary>


![image](https://user-images.githubusercontent.com/35058624/100528590-c65f2100-31ef-11eb-8887-9ab043cd5cce.png)


```xml
<item>
<title>Envision</title>
<link>
https://www.deviantart.com/yuumei/art/Envision-862328723
</link>
<guid isPermaLink="true">
https://www.deviantart.com/yuumei/art/Envision-862328723
</guid>
<pubDate>Thu, 26 Nov 2020 09:40:29 PST</pubDate>
<media:title type="plain">Envision</media:title>
<media:keywords/>
<media:rating>nonadult</media:rating>
<media:category label="Visual Art">visual_art</media:category>
<media:credit role="author" scheme="urn:ebu">yuumei</media:credit>
<media:credit role="author" scheme="urn:ebu">https://a.deviantart.net/avatars/y/u/yuumei.jpg?6</media:credit>
<media:copyright url="https://www.deviantart.com/yuumei">Copyright 2020 yuumei</media:copyright>
<media:description type="html">
<div><span>2020 has been a rough year for everyone. From Covid to the endless wildfires that turned the sky red, sometimes it can feel overwhelming and hopeless. But don't give up, we can envision a better future, and we can bring that vision to life.<br /></span><br /></div><div>For this Thanksgiving, I will be hosting my annual charity art sale to raise money for the environment. Last year we raised $14k in donations and this year MSI&nbsp;will DOUBLE any money we raise! That means if we can raise $15k this year, a total of $30k will be donated! <br /><span></span> </div><div><div><br />The charity sale begins on Nov 27th and will last a whole week. Get 10% off all orders and any print purchase will receive free mystery prints! But best of all is all profits will be donated to charity X2&nbsp;<br /><span>Get your charity art here! </span><span><a href="https://www.deviantart.com/users/outgoing?https://www.yuumeiart.com/shop?fbclid=IwAR28KRLsKTmmmqVgXoinangG125D8d5re-PtQEoIDumvyKAz1hmlLLvgp10"><a class="external" href="https://www.deviantart.com/users/outgoing?https://www.yuumeiart.com/shop">www.yuumeiart.com/shop</a></a></span><br /></div></div><div><div><br />In addition to all that, MSI will also be giving away 6 monitors to anyone who does a good deed (such as helping out the charity sale). Enter here <span><a href="https://www.deviantart.com/users/outgoing?https://us.msi.com/Promotion/yuumei-charity?fbclid=IwAR3w46xxdw9pdKh65IKD35fMGF40DZMXpJeZrrnTxqWukniEDAOl9fi18wM"><a class="external" href="https://www.deviantart.com/users/outgoing?https://us.msi.com/Promotion/yuumei-charity">us.msi.com/Promotion/yuumei-ch&hellip;</a></a></span></div></div>
</media:description>
<media:thumbnail url="https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/454c2ed9-5cc2-484f-8449-167203bd7623/de9ep3n-20a05fc3-c10e-4b4b-8904-4c9c957cb444.jpg/v1/fit/w_150,h_150,q_70,strp/envision_by_yuumei_de9ep3n-150.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOiIsImlzcyI6InVybjphcHA6Iiwib2JqIjpbW3siaGVpZ2h0IjoiPD03MDEiLCJwYXRoIjoiXC9mXC80NTRjMmVkOS01Y2MyLTQ4NGYtODQ0OS0xNjcyMDNiZDc2MjNcL2RlOWVwM24tMjBhMDVmYzMtYzEwZS00YjRiLTg5MDQtNGM5Yzk1N2NiNDQ0LmpwZyIsIndpZHRoIjoiPD0xMjgwIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.WNC1NwPbZQkvPCRSCFoApKUYyGESNJvNE1nyEWzixsE" height="82" width="150"/>
<media:thumbnail url="https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/454c2ed9-5cc2-484f-8449-167203bd7623/de9ep3n-20a05fc3-c10e-4b4b-8904-4c9c957cb444.jpg/v1/fit/w_300,h_701,q_70,strp/envision_by_yuumei_de9ep3n-300w.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOiIsImlzcyI6InVybjphcHA6Iiwib2JqIjpbW3siaGVpZ2h0IjoiPD03MDEiLCJwYXRoIjoiXC9mXC80NTRjMmVkOS01Y2MyLTQ4NGYtODQ0OS0xNjcyMDNiZDc2MjNcL2RlOWVwM24tMjBhMDVmYzMtYzEwZS00YjRiLTg5MDQtNGM5Yzk1N2NiNDQ0LmpwZyIsIndpZHRoIjoiPD0xMjgwIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.WNC1NwPbZQkvPCRSCFoApKUYyGESNJvNE1nyEWzixsE" height="164" width="300"/>
<media:thumbnail url="https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/454c2ed9-5cc2-484f-8449-167203bd7623/de9ep3n-20a05fc3-c10e-4b4b-8904-4c9c957cb444.jpg/v1/fill/w_300,h_164,q_70,strp/envision_by_yuumei_de9ep3n-200h.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOiIsImlzcyI6InVybjphcHA6Iiwib2JqIjpbW3siaGVpZ2h0IjoiPD03MDEiLCJwYXRoIjoiXC9mXC80NTRjMmVkOS01Y2MyLTQ4NGYtODQ0OS0xNjcyMDNiZDc2MjNcL2RlOWVwM24tMjBhMDVmYzMtYzEwZS00YjRiLTg5MDQtNGM5Yzk1N2NiNDQ0LmpwZyIsIndpZHRoIjoiPD0xMjgwIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.WNC1NwPbZQkvPCRSCFoApKUYyGESNJvNE1nyEWzixsE" height="164" width="300"/>
<media:content url="https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/454c2ed9-5cc2-484f-8449-167203bd7623/de9ep3n-20a05fc3-c10e-4b4b-8904-4c9c957cb444.jpg/v1/fill/w_1208,h_661,q_70,strp/envision_by_yuumei_de9ep3n-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOiIsImlzcyI6InVybjphcHA6Iiwib2JqIjpbW3siaGVpZ2h0IjoiPD03MDEiLCJwYXRoIjoiXC9mXC80NTRjMmVkOS01Y2MyLTQ4NGYtODQ0OS0xNjcyMDNiZDc2MjNcL2RlOWVwM24tMjBhMDVmYzMtYzEwZS00YjRiLTg5MDQtNGM5Yzk1N2NiNDQ0LmpwZyIsIndpZHRoIjoiPD0xMjgwIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.WNC1NwPbZQkvPCRSCFoApKUYyGESNJvNE1nyEWzixsE" height="661" width="1208" medium="image"/>
<description>
<div><span>2020 has been a rough year for everyone. From Covid to the endless wildfires that turned the sky red, sometimes it can feel overwhelming and hopeless. But don't give up, we can envision a better future, and we can bring that vision to life.<br /></span><br /></div><div>For this Thanksgiving, I will be hosting my annual charity art sale to raise money for the environment. Last year we raised $14k in donations and this year MSI&nbsp;will DOUBLE any money we raise! That means if we can raise $15k this year, a total of $30k will be donated! <br /><span></span> </div><div><div><br />The charity sale begins on Nov 27th and will last a whole week. Get 10% off all orders and any print purchase will receive free mystery prints! But best of all is all profits will be donated to charity X2&nbsp;<br /><span>Get your charity art here! </span><span><a href="https://www.deviantart.com/users/outgoing?https://www.yuumeiart.com/shop?fbclid=IwAR28KRLsKTmmmqVgXoinangG125D8d5re-PtQEoIDumvyKAz1hmlLLvgp10"><a class="external" href="https://www.deviantart.com/users/outgoing?https://www.yuumeiart.com/shop">www.yuumeiart.com/shop</a></a></span><br /></div></div><div><div><br />In addition to all that, MSI will also be giving away 6 monitors to anyone who does a good deed (such as helping out the charity sale). Enter here <span><a href="https://www.deviantart.com/users/outgoing?https://us.msi.com/Promotion/yuumei-charity?fbclid=IwAR3w46xxdw9pdKh65IKD35fMGF40DZMXpJeZrrnTxqWukniEDAOl9fi18wM"><a class="external" href="https://www.deviantart.com/users/outgoing?https://us.msi.com/Promotion/yuumei-charity">us.msi.com/Promotion/yuumei-ch&hellip;</a></a></span></div></div><br /><div><img src="https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/454c2ed9-5cc2-484f-8449-167203bd7623/de9ep3n-20a05fc3-c10e-4b4b-8904-4c9c957cb444.jpg/v1/fill/w_300,h_164,q_70,strp/envision_by_yuumei_de9ep3n-200h.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOiIsImlzcyI6InVybjphcHA6Iiwib2JqIjpbW3siaGVpZ2h0IjoiPD03MDEiLCJwYXRoIjoiXC9mXC80NTRjMmVkOS01Y2MyLTQ4NGYtODQ0OS0xNjcyMDNiZDc2MjNcL2RlOWVwM24tMjBhMDVmYzMtYzEwZS00YjRiLTg5MDQtNGM5Yzk1N2NiNDQ0LmpwZyIsIndpZHRoIjoiPD0xMjgwIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmltYWdlLm9wZXJhdGlvbnMiXX0.WNC1NwPbZQkvPCRSCFoApKUYyGESNJvNE1nyEWzixsE" alt="thumbnail" /></div>
</description>
</item>
```

</details>

**Comment by squromiv** [comment]
I suffer from this problem for quite a long time. Still waiting for fix. Thanks for attention.

**Comment by math-GH** [comment]
I have the same problem. 
![grafik](https://user-images.githubusercontent.com/1645099/126788747-680fd3d4-72ae-42b2-845e-6009b53aa745.png)

But I cannot see any solution because there is no general rule. The image is hidden/displayed via CSS on the origin website.

What about to wrap the article with a CSS class and a setting field to write some individual CSS code?

**Comment by winteriscariot** [comment]
Is it possible to parse this at the feed level, and not the original website?

for example, wrt DeviantArt, the example feed they give is this: https://backend.deviantart.com/rss.xml?type=deviation&q=by%3Aspyed+sort%3Atime+meta%3Aall

looking at this, you can see all the `media:thumbnail` element that correspond to the additional images that show up in DA feeds. while i don't think it'd make sense to isolate the `media:content` element, because you don't know what other elements you'd want in there, but might it make sense to have an option to *exclude* certain elements in the RSS feed itself? that way a rule could be put in place for `media:thumbnail` elements, or any others you don't want displayed?

**Comment by math-GH** [comment]
In 1.20 it is possible to use CSS selectors to delete elements from the feed. It could be used to remove the duplicate images

**Comment by squromiv** [comment]
Is it possible to develop an option for feeds - to show/not show attachments inline?

**Comment by squromiv** [comment]
RSSBridge similar [issue 2716](https://github.com/RSS-Bridge/rss-bridge/issues/2716) is solved.

**Comment by squromiv** [comment]
Tiny Tiny RSS [issue](https://community.tt-rss.org/t/duplicate-image-attachments/393)

**Comment by squromiv** [comment]
> In 1.20 it is possible to use CSS selectors to delete elements from the feed. It could be used to remove the duplicate images

Smth goes wrong for me. What selector should I set in order to delete dup pictures from this [feed](https://www.yaplakal.com/news.xml)?

**Comment by math-GH** [comment]
> 

I cannot see which picture is duplicated. I would suggest to open a new ticket here, where we can help you much better than here in this long thread

**Comment by squromiv** [comment]
@math-GH 
It is the feed from the first post of discussion. :-) I think, we must partially resolve the issue five years later.

**Comment by Alkarex** [comment]
Will be addressed as part of https://github.com/FreshRSS/FreshRSS/pull/4944

**Comment by squromiv** [comment]
> closed this as completed

@Alkarex There are three pictures now, instead of two, in the feed from the first post. :laughing:

![screenshot 2023-01-08 17-21-37 001](https://user-images.githubusercontent.com/15985877/211201462-f5730c02-ea19-4628-9a81-c289784f41dc.png)

**Comment by Alkarex** [comment]
@squromiv I have just checked the newest posts from https://www.yaplakal.com/news.xml , for instance this article https://www.yaplakal.com/forum7/topic2555301.html

There are two images, but they do not have the same address:
* https://s00.yaplakal.com/pics/pics_preview/9/2/0/17577029.jpg
* https://s00.yaplakal.com/pics/pics_original/9/2/0/17577029.jpg

Our current logic considers them as different.

What could be possible is to have new per-feed preference to display enclosures or not. You are welcome to open a new issue for that.
