### ISSUE TITLE
How to update RSS Feeds automatically?

### ISSUE THREAD

**Issue by davidsciamalai** [FreshRSS/FreshRSS#1676]
How to update RSS Feeds automatically on FreshRSS in less time possible?
What is it the ''Archiving'' Menu?

**Comment by aledeg** [comment]
For the update, read the documentation [here](https://github.com/FreshRSS/FreshRSS#automatic-feed-update).

The archiving menu allows you to configure options regarding the data in the database. How long do you keep it, how much data you keep, and so on.

**Comment by mb12121395** [comment]
hi 
How can I automatically update the feed in Windows 2016?
tnx

**Comment by plqu** [comment]
Man, I just can't make this work. Clear, working step-by-step documentation of how to get the feeds to periodically update themselves without crontab access would really be appreciated. The methods on https://freshrss.github.io/FreshRSS/en/users/03_Main_view.html#online-cron all either require lowering security, or don't work, or both. I really don't want to open up anonymous public read access, and SSHing into my particular host to set up crontab is a giant pain. I'd really like to just have an URL I can call periodically from outside that triggers the update (without having to open my entire account up for public read access), or even better, a plugin or setting in the system where I can just tell it "update every 20 minutes" and set it and forget it.

**Comment by Alkarex** [comment]
@plqu What have you tried? Assuming you are using Web Form authentication, have you tried with the authentication method?
`https://freshrss.example.net/i/?c=feed&a=actualize&user=someone&token=my-token`

**Comment by Alkarex** [comment]
@plqu I am updating the documentation to make it even clearer:
https://github.com/FreshRSS/FreshRSS/blob/27436d284e789023c8446919ac6b07de1426dad1/docs/en/users/03_Main_view.md#online-cron
