### ISSUE TITLE
certains flux se marquent automatiquement comme lu sans le vouloir (résolu)

### ISSUE THREAD

**Issue by mum1989** [FreshRSS/FreshRSS#1679]
Bonjour, 
j'ai mis à jour FreshRSS de la 1.6.x vers la version 1.8.0, 
après avoir eu un soucis de de rafraichissement (il manquait la moitié des flux), 
je suis parti d'une BDD mariadb neuve (60mo l'ancienne)
(mon srv est sous Debian Stretch)

Le rafraichissement fonctionne.

Mais j'ai un bug que ce soit sur Opera ou Firefox, une partie de mes flux (ceux du haut) se marquent lu automatiquement .

Peut être existe-t-il des résidus de l'ancienne version et ça coince ?
je n'ai pas trop d'idée.
Je n'ai pas de tache dans crontab -e pour le refresh auto.
Merci

english :
some news become marked-as-read without my consent.
I don't have any crontab.
Thanks

**Comment by Alkarex** [comment]
Cela semble être l'option marquer comme lu au défilement :
![image](https://user-images.githubusercontent.com/1008324/32107746-d3047c82-bb2f-11e7-9994-4b215e48ad4a.png)

**Comment by mum1989** [comment]
pardon oui autant pour moi
j'avais cette option cochée par défaut
