### ISSUE TITLE
Feed is not updated

### ISSUE THREAD

**Issue by Lokta** [FreshRSS/FreshRSS#1680]
I have an issue with the following feed
http://ceph.com/community/blog/feed/
The feed was added and the 10 articles where added to FreshRSS without any issue but i can not get the feed to refresh.
It only show the 1st 10 articles gathered and never gets the new ones despite the "successful" update.

I tried removing and re-adding the feed and the same 10 entries showed up.
I didn't try to remove lines in the DB yet, but i'm ok doing it if someone tells me what to rm :)

I'm currently running FreshRSS 1.7.0 on a debian 9.2 with php 5.6.30 and MySQL 5.5

thanks for the help !

**Comment by Lokta** [comment]
Updated to 1.8.0, problem is still relevant.

**Comment by Alkarex** [comment]
I am not sure to understand. The original feed has 10 entries. Which entry is it that you are missing?

**Comment by Alkarex** [comment]
Could you please send a screenshot of the entries you have on your side?

**Comment by Frenzie** [comment]
@Alkarex I noticed the feed sends a Last-Modified header that says 12 January 2017 even though it clearly has much more recent entries. Could that be related?

```
$ curl -I http://ceph.com/community/blog/feed/
HTTP/1.1 200 OK
Server: nginx/1.10.3 (Ubuntu)
Date: Wed, 01 Nov 2017 09:10:46 GMT
Content-Type: application/rss+xml; charset=UTF-8
Connection: keep-alive
Last-Modified: Thu, 12 Jan 2017 00:12:01 GMT
ETag: "e9e8f36c97da917ca2c17b413f5f47ec"
X-Robots-Tag: noindex, follow
Link: <http://ceph.com/wp-json/>; rel="https://api.w.org/"
```

**Comment by Alkarex** [comment]
Indeed @Frenzie , if `ETag` and `Last-Modified` are unchanged during updates, this might be a problem.

**Comment by Lokta** [comment]
Hello,

It seems that i only had to complain for my FreshRSS to fear a wipe and to start working properly :p

The issue was that once the feed was added, no update (since august) was picked up.
I had the 10 original entries and no new entries were added when refreshing despite being regularly updated on the ceph.com side.

I only got up to 1.8.0 yesterday so it might be something that was fixed in this update.

Sadly, I didn't see anything in the log files regarding this feed.

I'll keep you updated if I see some similar behaviour in the future.

Thank you !

**Comment by Lokta** [comment]
Hi
turns out this issue is still  relevant.

I'm missing last friday's update and, indeed, ETag and Last-Modified are the same as before

**Comment by Alkarex** [comment]
I have just tested, and they still have an HTTP caching bug: the cache information is not updated:

```
$ curl -I http://ceph.com/community/blog/feed/
HTTP/1.1 200 OK
Server: nginx/1.10.3 (Ubuntu)
Date: Wed, 06 Dec 2017 18:13:20 GMT
Content-Type: application/rss+xml; charset=UTF-8
Connection: keep-alive
Last-Modified: Thu, 12 Jan 2017 00:12:01 GMT
ETag: "e9e8f36c97da917ca2c17b413f5f47ec"
X-Robots-Tag: noindex, follow
Link: <http://ceph.com/wp-json/>; rel="https://api.w.org/"
```

We could make some workarounds, but really, this is a case where the feed itself needs to be fixed.
On your side, you can delete the local cache for that feed as part of your cron.
It is `./FreshRSS/data/cache/[FEED_HASH].spc` where feed hash is the md5 of the feed URL.

```sh
echo -n 'http://ceph.com/community/blog/feed/' | md5sum
4afce85f00958c9de8dedd5032e31653  -
```

You can also grep to find the corresponding cache file:

```sh
grep '<link>http://ceph.com</link>' -r data/cache/
```

**Comment by Lokta** [comment]
I'll see if anyone cares about their broken rss feed on the ceph team, in the meantime i'll use your technic.

Thank you for that !
