### ISSUE TITLE
Content-Security-Policy prevents Cloudflare rocket loader to be used with fresh rss

### ISSUE THREAD

**Issue by alrayyes** [FreshRSS/FreshRSS#1681]
Some logs from the browser console:

```
GET https://rss.example/i/ [HTTP/2.0 200 OK 92ms]
Loading failed for the <script> with source “https://ajax.cloudflare.com/cdn-cgi/scripts/78d64697/cloudflare-static/rocket.min.js”.  i:11
Content Security Policy: The page’s settings blocked the loading of a resource at self (“default-src https://rss.example.com”). Source: (function (ERROR) {

    const V8_STACK_....  i:1
Content Security Policy: The page’s settings blocked the loading of a resource at self (“default-src https://rss.example.com”). Source: ;(function installHook (window) {
  var ....  i:1
Content Security Policy: The page’s settings blocked the loading of a resource at self (“default-src https://rss.example.com”). Source: 
//<![CDATA[
window.__cfRocketOptions = ....  i:6
Content Security Policy: The page’s settings blocked the loading of a resource at https://ajax.cloudflare.com/cdn-cgi/scripts/78d64697/cloudflare-static/rocket.min.js (“default-src https://rss.example.com”).
```
This appears to be hardcoded in the php. It causes all number of werid issues like login not working if using Cloudflare with [Rocket Loader](https://support.cloudflare.com/hc/en-us/articles/200168056-What-does-Rocket-Loader-do-) enabled.

Would be nice if the Content security policy could be overruled in config.php. That would pretty much fix this.

**Comment by Alkarex** [comment]
Ok, added to the back log.
By curiosity, what is the use-case for that? FreshRSS scripts are cached client side, so it is probably not for performance. And allowing third party script injection seems to reduce the security / privacy. Am I missing something?

**Comment by Alkarex** [comment]
P.S. It is also possible to add a rule at Web server level to edit the CSP.

**Comment by alrayyes** [comment]
I personally have a bunch of other stuff hosted on my vps under different
subdomains. So among other apps FreshRSS subdomain is behind Cloudflare as
well. If Cloudflare starts injecting third party scripts into JS hosted on
their cdn they'll be out of business in no time :-). Pros of Cloudflare are
of course speed and privacy.

Putting self hosted apps behind Cloudflare is quite a common user case.
Especially if for example you have you have your personal site on
example.com and freshrss on rss.example.com.

**Comment by oupala** [comment]
FreshRSS is taking care of its own Content Security Policy headers.

If you enable Cloudflare, that aim to bring some security. There should somewhere be a flag to disable security features embedded in FreshRSS as Cloudflare is taking care of it.

So what about a flag to disable security features of FreshRSS?

**Comment by Alkarex** [comment]
@oupala 
1. Such an option can just as well be on Cloudflare's side: do not set CSP rules if the Web application is already providing them.
    * Cloudflare does not have the possibility of knowing what CSP rules to use, which are dependent of the page served (e.g. not the same for the main page, or config pages, or statistics page).
    * This is not the only problem caused by Cloudflare. See e.g. https://github.com/FreshRSS/FreshRSS/issues/1646#issuecomment-355857451
2. It is already possible to edit or remove FreshRSS's HTTP headers at your Web server's level. For instance with Apache's `Header` directive http://httpd.apache.org/docs/trunk/mod/mod_headers.html#header (see `unset` and `edit` in particular).

**Comment by oupala** [comment]
Ok.
