### ISSUE TITLE
Article URL with escaped query parameters is malformed in google reader API

### ISSUE THREAD

**Issue by mappu** [FreshRSS/FreshRSS#1683]
Hi,

Please read: https://github.com/Alkarex/EasyRSS/issues/35 but actually I think this is an issue with FreshRSS itself.

In https://github.com/FreshRSS/FreshRSS/blob/master/p/api/greader.php#L520 you can see the response is served in plain JSON, so XML entity decoding of the `<link>` node content should have already happened, right?

**Comment by mappu** [comment]
Maybe same kind of `html_only_entity_decode` call as at https://github.com/FreshRSS/FreshRSS/blob/master/app/Models/Feed.php#L274 needs to be added at around https://github.com/FreshRSS/FreshRSS/blob/master/app/Models/Feed.php#L306 ? But if elsewhere expects pre-escaped HTML content (e.g. in https://github.com/FreshRSS/FreshRSS/blob/master/app/views/index/rss.phtml#L15 ) this would have disasterous consequences.

**Comment by Alkarex** [comment]
Thanks for the bug report, @mappu 
At a first quick glance, I think that the entity decoding is missing for the link in the API.
All the fields of the `entry` table are supposed to be HTML safe. We must check that this is the case on input, and remember to decode when the output is not HTML.

**Comment by Alkarex** [comment]
Example of quick verification to do:

```
mysql> select count(id) from freshrss_alex_entry where link like '%<%' or link like '%"%';
+-----------+
| count(id) |
+-----------+
|         0 |
+-----------+
1 row in set (1.98 sec)
```

**Comment by Alkarex** [comment]
Indeed, the links from this feed are stored with the expected (HTML-safe) format in FreshRSS database:
```
mysql> select link from freshrss_alex_entry where id_feed = 449 limit 2;
+----------------------------------------------------------------------------------------+
| link                                                                                   |
+----------------------------------------------------------------------------------------+
| http://www.phoronix.com/scan.php?page=news_item&amp;px=73-More-AMDGPU-DC-Patches       |
| http://www.phoronix.com/scan.php?page=news_item&amp;px=Arch-Linux-i686-Ends            |
+----------------------------------------------------------------------------------------+
```

**Comment by Alkarex** [comment]
Example of JSON response currently sent by FreshRSS, with the link attribute still HTML-encoded:

```json
{
	"id" : "00055d93689fd8d0",
	"crawlTimeMsec" : "1510262580435",
	"timestampUsec" : "1510262580435152",
	"published" : 1510050540,
	"title" : "Krita 4.0 Working On Performance Improvements, Benchmark &amp; New Filters",
	"summary" : {
		"content" : "Krita 4.0 remains under development as the next big feature update for this Qt-powered digital painting program and it's brewing a lot of new functionality..."
	},
	"alternate" : [{
			"href" : "http:\/\/www.phoronix.com\/scan.php?page=news_item&amp;px=Krita-4.0-More-Features"
		}
	],
	"categories" : ["user\/-\/state\/com.google\/reading-list", "user\/-\/label\/Sans cat\u00e9gorie"],
	"origin" : {
		"streamId" : "feed\/450",
		"title" : "Phoronix"
	}
}
```

**Comment by Alkarex** [comment]
I am trying to find a reference of how it is supposed to be (encoded or not) in the JSON output, and of course neither the specs nor the various client codes are very clear on the subject :-P
* Undecided http://web.archive.org/web/20130708105542/http://undoc.in:80/stream.html#contents
* Expects decoded https://github.com/davidsun/EasyRSS/blob/07f5086ad306e94dbbac32e0bb38203bbfbcbbf6/src/com/pursuer/reader/easyrss/data/parser/ItemJSONParser.java#L84
* Expects decoded https://github.com/noinnion/newsplus/blob/master/extensions/GoogleReaderCloneExtension/src/com/noinnion/android/newsplus/extension/google_reader/GoogleReaderClient.java#L755
* Expects encoded https://github.com/ericmann/gReader-Library/blob/master/greader.class.php#L140
* Undecided https://developer.feedly.com/v3/streams/

It however looks like the more proper approach is to fix FreshRSS to send the link decoded.

**Comment by Frenzie** [comment]
There are specs? I thought it was one of those typical Google meh whatever things.

**Comment by Alkarex** [comment]
There was actually some Google API documentation, as well as third-party documentation, and third-party code :-)

**Comment by Alkarex** [comment]
@mappu Could you please give a try to https://github.com/FreshRSS/FreshRSS/pull/1686 ?

**Comment by Alkarex** [comment]
@jangernert Quick question: I cannot immediately see from your code whether you expect that each field `title` and `href` is plain text, or HTML-encoded, for e.g. FreshRSS, The Old Reader, and Feedly. `title` is clearly HTML-encoded, but `link` was a bit less clear. I will patch FreshRSS to provide `link` unencoded, and I wanted to check whether that would affect *FeedReader* :-)

https://github.com/jangernert/FeedReader/blob/40411f2dbf99da695900424775f823e73e787faa/plugins/backend/fresh/freshAPI.vala#L259

https://github.com/jangernert/FeedReader/blob/40411f2dbf99da695900424775f823e73e787faa/plugins/backend/feedly/feedlyAPI.vala#L360

https://github.com/jangernert/FeedReader/blob/master/src/Model/Article.vala#L54

**Comment by mappu** [comment]
I applied the patch in #1686 to my 1.8.0 installation. It does resolve the issue for me. Thank you :+1:

**Comment by mappu** [comment]
I am a little concerned about how HTML and XML decoding is performed in FreshRSS.

Ideally:

1. Using a compliant XML parser on the RSS feed should have already decoded the `&amp;` attribute in the `<link>` node.
2. The entry's properties should be stored in the DB unencoded.
3. When the entry is displayed, encode it appropriately for the output context (json / html / ...).

I believe doing it any different way will create more edge cases and possible XSS security issues in the future.

**Comment by Alkarex** [comment]
@mappu It is good to look again and again at encoding matters, as it is such a typical source of problems.
In the `entry` table, we need to store some HTML anyway (e.g. for `entry.content`), for which your steps 1 and 3 would not work. For consistency, all the columns of this table are HTML-safe, so we only need to decode them in the (rare) cases when our output is not HTML.
The values for those different columns are sanitized and provided HTML-escaped by the SimplePie library.
So, as far as I can see, everything is at it should be :-)
