### ISSUE TITLE
Afficher le flux RSS sur la gauche

### ISSUE THREAD

**Issue by yoalor** [FreshRSS/FreshRSS#1685]
Bonjour,

Lors de l'ouverture d'un flux RSS, celui-ci s'affiche en plein milieu de mon écran. Je souhaite savoir comment pourvoir obtenir un affichage forcer sur la gauche.

Cordialement.

**Comment by Frenzie** [comment]
I assume you'll want to change the CSS a little, for example with:

```css
.content { margin-left: 1em; }
```

The easiest way to do that is https://github.com/FreshRSS/Extensions/tree/master/xExtension-CustomCSS

Looks like this:
![screenshot_2017-11-09_21-21-31](https://user-images.githubusercontent.com/202757/32627829-1a0ed3e8-c594-11e7-9fd3-b2b73912961a.png)

**Comment by yoalor** [comment]
Hello,

Now it's works.

Thanks.
