### ISSUE TITLE
Sync issue with greader.php / News+ app on Android

### ISSUE THREAD

**Issue by seyfro** [FreshRSS/FreshRSS#1687]
first thanks for creating FreshRSS - I have been using tt-rss for a long time and am looking for alternatives now - FreshRSS seems the right solution for me.

Unfortunately I have an issue with syncing I kindly ask you to help me with: I used the Android App News+ (Premium) with tt-rss to sync my feeds to my mobile. News+ also has an extension called "Google Reader Clone" which can be used to login providing the API endpoint https://www.harm.co.at/freshrss/p/api/greader.php
If I install this extension and login to with my FreshRSS credentials, the feed list is loaded correctly, unfortunately no articles are loaded and I also do not see the last updated date next to the feed. If I login via web though, FreshRSS works without any issued.

I checked /freshrss/p/api/greader.php/check/compatibility with the result PASS, the other check (freshrss/p/api/greader.php/check%2Fcompatibility) results in not found.

I would really appreciate it if you could help me to get FreshRSS running together with News+ on Android so that I can finally delete tt-rss from my server.

**Comment by Frenzie** [comment]
As a quick sanity check you should try if [EasyRSS](https://f-droid.org/packages/org.freshrss.easyrss/) works. That'll tell you if the problem is something in FreshRSS or in your server configuration.

**Comment by seyfro** [comment]
thanks for the prompt reply - I installed EasyRSS and feeds were synced without any issues. So it must be a News+/Google Reader Clone issue (not sure though how to fix this, so switching to EasyRSS - which seems quite nice - is likely the better option)

**Comment by Frenzie** [comment]
It could also be something FreshRSS does or doesn't do, but at least we know now that there are no configuration issues. :-)

**Comment by Alkarex** [comment]
@robertharm Welcome here :-)
The symptoms you have are a sign that your Web server, probably Apache, does not accept `%2F` characters  in a URL.
Since we cannot fix News+, the only option is to fix it on your side by adding `AllowEncodedSlashes On` in your Apache configuration: http://httpd.apache.org/docs/trunk/mod/core.html#allowencodedslashes

**Comment by Alkarex** [comment]
Note for our documentation: we need to add
https://github.com/FreshRSS/FreshRSS/issues/443#issuecomment-36666133
to
https://freshrss.github.io/FreshRSS/en/users/06_Mobile_access.html

**Comment by seyfro** [comment]
thanks for the info - unfortunately I cannot change this as I am using a shared host

**Comment by aledeg** [comment]
You could probably add that in an ```.htaccess``` file. I haven't tried but usually that the kind of thing supported in that file.

Assuming that you're using Apache :)

**Comment by Alkarex** [comment]
This Apache instruction does not work at `.htaccess` level. Its context is *server config*, *virtual host*

**Comment by Alkarex** [comment]
For the record, we plan to add more APIs, to be compatible with even more clients. For the time being, in your case, EasyRSS seems to be a good bet.
