### ISSUE TITLE
Introduce a new filter for filtering feeds

### ISSUE THREAD

**Issue by husimo** [FreshRSS/FreshRSS#1688]
Hello,
Currently, I can display one feed by clicking on the left menu. If I want to display multiple feeds, I can put them in a category. But I can't put a feed in more than one category.
So it would be useful for me to be able to use filters to display only some feeds.
For example the filter | feed:"Se coucher moins bête" feed:"Le moment Meurice" would only display "Se coucher moins bête" and "Le moment Meurice" based on feed name.
Right now it's possible as a workaround to use the "inurl" filter when all links have the same domain name (example : inurl:secouchermoinsbete.fr works), but it's not the case for example for Shaarli RSS feed (ex : https://husimo.fr/shaarli/rss?do=atom) because link1 is github.com, link2 is devhints.io.
Thank you for your great work :+1:

**Comment by aledeg** [comment]
@Alkarex I think you've addressed that. Right?

**Comment by Alkarex** [comment]
Correct, let's follow up in https://github.com/FreshRSS/FreshRSS/pull/3303

**Comment by Alkarex** [comment]
Sorry, wrong comment :-)
Correct, see https://github.com/FreshRSS/FreshRSS/pull/2892

**Comment by Alkarex** [comment]
Though with a feed ID rather than a feed title
