### ISSUE TITLE
Check install don't see pdo_pgsql after a successful installation on postgreSQL

### ISSUE THREAD

**Issue by blankoworld** [FreshRSS/FreshRSS#1690]
### Problem

After a successful installation on postgreSQL, system don't detect any PDO driver.

### How to reproduce

1. Use php with pdo_pgsql and pgsql extensions. No other one.
2. Install FreshRSS
3. Go to Administration > Vérification de l'installation
4. System say « Vous ne disposez pas de PDO ou d’un des drivers supportés (pdo_mysql, pdo_sqlite, pdo_pgsql). »

**Comment by Alkarex** [comment]
Should be fixed in https://github.com/FreshRSS/FreshRSS/pull/1692
