### ISSUE TITLE
`idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated` in PHP 7.2

### ISSUE THREAD

**Issue by candrews** [FreshRSS/FreshRSS#1699]
```PHP Deprecated:  idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated in FreshRSS/lib/lib_rss.php on line 65```

From https://secure.php.net/manual/en/function.idn-to-ascii.php I believe this change to https://github.com/FreshRSS/FreshRSS/blob/ceda55c75b158fc1cf4813fe0f258527754b9289/lib/lib_rss.php#L65 should work:
`$puny = idn_to_ascii($idn, 0, INTL_IDNA_VARIANT_UTS46);`

**Comment by Alkarex** [comment]
Thanks for the report.
P.S.: `INTL_IDNA_VARIANT_UTS46` seems to be introduced in 5.4.0 (we currently support PHP 5.3.8), so we either have to drop PHP 5.3.x or make a feature test.

**Comment by Alkarex** [comment]
Fixed by @candrews in https://github.com/FreshRSS/FreshRSS/pull/1700

**Comment by udin-ordinary** [comment]
```
	public function valid_email($str)
	{
		if (function_exists('idn_to_ascii') && preg_match('#\A([^@]+)@(.+)\z#', $str, $matches))
		{
			$str = $matches[1].'@'.idn_to_ascii($matches[2],IDNA_NONTRANSITIONAL_TO_ASCII,INTL_IDNA_VARIANT_UTS46);
		}

		return (bool) filter_var($str, FILTER_VALIDATE_EMAIL);
	}
```

**Comment by Alkarex** [comment]
Hello @udin-ordinary , Is your code snippet related to FreshRSS?
