### ISSUE TITLE
Mark as read when updating feeds

### ISSUE THREAD

**Issue by Liandriz** [FreshRSS/FreshRSS#1702]
Hi, just a question to know if a feature is actually feasible, with or without plugin : mark as read all the posts from a feed, when updating them. 

This is for some feeds i archive to search later on them, not reading them when they are published.
So is it possible to do that please?

**Comment by Alkarex** [comment]
Hello @Liandriz 
Yes; see the last option:

![image](https://user-images.githubusercontent.com/1008324/33515516-127b6b4a-d765-11e7-84ef-13c746215a03.png)

**Comment by Alkarex** [comment]
Ah sorry, maybe you meant for only one specific feed?

**Comment by Liandriz** [comment]
Yes, didn't see it cause i didn't check in global options, but this is it, but per feed, is it hard to add by plugin?  👍

**Comment by Alkarex** [comment]
@Liandriz Making an extension is not so difficult.
See the latest one as an example https://github.com/kevinpapst/freshrss-dilbert/blob/master/xExtension-Dilbert/extension.php from @kevinpapst
Different "read" options per feed could become a FreshRSS feature in the future, but it is not something we have right now (easy to do, the main part is to translate the title of the option in the different languages).

**Comment by Liandriz** [comment]
You really don't need any traduction : Just add a section on feed options page, with title "Reading", same that is in global section, and same for options, something like this (maybe not the 4 options) : 
![feed options](https://user-images.githubusercontent.com/563539/33525193-36f63920-d82b-11e7-9244-82ab50c72ace.png)

**Comment by Alkarex** [comment]
Usecase for https://github.com/FreshRSS/FreshRSS/pull/1838
