### ISSUE TITLE
Minz_Extensions and accessing files

### ISSUE THREAD

**Issue by kevinpapst** [FreshRSS/FreshRSS#1709]
While working on https://github.com/FreshRSS/Extensions/pull/23 I stumbled upon this comment https://github.com/FreshRSS/FreshRSS/issues/1456#issuecomment-348797338 by @Alkarex regarding the `./data/extensions-data/` directory.

Some thoughts about that:
- What about adding a second method besides Minz_Extension::getFileUrl() which uses the new path and a deprecation warning for the old one? By now, its unclear where files should be stored.
- What about a helper method like Minz_Extension::getUserPath() which could be consumed by extension authors?
- Maybe some sentences about these directories in the extension docu?

But my main issue is:
I cannot use the new directory due to security limitations in the p/ext.php:
https://github.com/FreshRSS/FreshRSS/blob/master/p/ext.php#L20

The script only allows to access files in the extensions static/ sub-directories

Edit: Probably the old behaviour should be removed in 2.0 completely, as the data/ directory seems to be the place where such file changes should happen exclusively.

**Comment by Alkarex** [comment]
There is indeed a bit of refactoring to do. A few more notes:
1. Only `./data/*` should need write permissions, so if extensions need to update / save some data, it must be under `./data/extensions-data/`.
2. I am a bit undecided as to where to locate the source code of the extensions. It may depend on how they update themselves.
3. I am considering promoting the (semi-)official extensions of `https://github.com/FreshRSS/Extensions/` and put them in FreshRSS repository (still as extensions), in order for to update them more easily, and to synchronise them better with changes in FreshRSS.

Could you explain your concrete examples, so we can maybe start by fixing those needs?

**Comment by kevinpapst** [comment]
I would keep the official extensions were they currently are, but add an update feature for extensions that have the a supported type (like "gh-subdirectory" as in https://github.com/FreshRSS/Extensions/blob/master/extensions.json#L10). 

I think moving the extensions directory into a sub-directory of `./data/` like  `./data/extensions/` could be a good idea, then we have everything in data that depends on the users installation.

Just my point of view:
1. `./data/extensions-data/` should be used to store data for system extensions
2. I would promote the use of `./data/users/kevin/` for storing data in user extensions (like CustomCSS) 
3. There should be a helper method to receive those paths in Minz_Extension
4. Wherever we store the data, it currently can't be used. If I put the CustomCSS file into `./data/extensions/` I cannot consume it in the frontend, as ext.php does not support loading these files

I will open a PR and add some FIXMEs or first ideas, which should make it way more easy to talk about what I want ;-)

**Comment by aledeg** [comment]
@Alkarex What are your thoughts about the `data-extension` folder? Is this folder meant to store extensions?
If I want to store user data related to extension, I think I should write it under the user folder directly. I think we should add methods to do such thing in the extension itself. What do you think?

**Comment by Alkarex** [comment]
It was meant to store extension-specific data (to avoid having to grand write-access outside the `./data/` folder - I cannot remember which extension was writing in its own folder), but under the user folder sounds fine

**Comment by aledeg** [comment]
I wrote such extensions (RedditImage & DateFormat) but since I am digging into the extension system, I am thinking of modifying a few things to make the life of an extension author easier.
See #3397

**Comment by aledeg** [comment]
I think writing in the user data folder is even better since we do not need to add a new folder. Easier to explain! Easier to backup! Easier to document!
