### ISSUE TITLE
Undefined class constant 'MYSQL_ATTR_INIT_COMMAND'  on Synology DSM6

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#1710]
I'm trying to create a cronjob on my synology system using the info provided in [this error report](https://github.com/FreshRSS/FreshRSS/issues/1126)

So, I run this cron job with user root:
php70 /volume1/web/freshrss/app/actualize_script.php > /volume1/web/freshrss/cron.txt 2>&1

And this is the outpot of the logfile:

Starting feed actualization at 2017-12-08T10:08:53+01:00
Actualize YannickV...
PHP Fatal error:  Uncaught Error: Undefined class constant 'MYSQL_ATTR_INIT_COMMAND' in /volume1/web/freshrss/lib/Minz/ModelPdo.php:65
Stack trace:
#0 /volume1/web/freshrss/app/actualize_script.php(62): Minz_ModelPdo->__construct('YannickV')
#1 {main}
  thrown in /volume1/web/freshrss/lib/Minz/ModelPdo.php on line 65
Results: 
YannickV 

The pdo_mysql extension is activated in the options. Anyone with idea's?

Thx!
Yannick

**Comment by Alkarex** [comment]
Hello,
Same issue in French https://github.com/FreshRSS/FreshRSS/issues/1126#issuecomment-203564550
There are potentially multiple versions of PHP on your Synology, and you probably do not use the same in your Web interface and in your cron.

**Comment by ghost** [comment]
I know that, and am using php7.0 in the web interface and in the cronjob. I checked the php.ini and it seems that pdo is not added there. It seems pdo is broken on my system.

**Comment by kevinpapst** [comment]
Does executing
``
php -m |grep pdo``
in your bash display
``pdo_mysql``
?

**Comment by ghost** [comment]
it returned this:

admin@denver:~$ `php -m |grep pdo`
pdo_sqlite


However I need to use the php70 command. 
`php70 -m |grep pdo `
returend nothing.

So I followed [this tutorial](https://blackswan.ch/archives/594), and now I run this:
`/volume1/@appstore/PHP7.0/usr/local/bin/php70 /volume1/web/freshrss/app/actualize_script.php > /volume1/web/freshrss/cron.txt 2>&1`

output:
Starting feed actualization at 2017-12-08T11:44:18+01:00
Actualize YannickV...
Results: 
YannickV 

When run in console:
Starting feed actualization at 2017-12-08T11:47:19+01:00
Actualize YannickV...
Done.
Ending feed actualization at 2017-12-08T11:47:19+01:00
Feed actualizations took 0 day(s), 0 hour(s),  0 minute(s) and 0 seconds for 1 users
Results: 
YannickV OK
End.

**Comment by ghost** [comment]
Seems the command did not work with the tasksheduler from synology. I added a crontab job using this tutorial: http://www.multigesture.net/articles/how-to-use-cron-on-a-synology-nas/

15,45   *    *   *   *  root    /volume1/@appstore/PHP7.0/usr/local/bin/php70 /volume1/web/freshrss/app/actualize_script.php > /volume1/web/freshrss/cron.txt 2>&1

and I got a working output:
Starting feed actualization at 2017-12-08T12:15:01+01:00
Actualize YannickV...
Done.
Ending feed actualization at 2017-12-08T12:15:04+01:00
Feed actualizations took 0 day(s), 0 hour(s),  0 minute(s) and 3 seconds for 1 users
Results: 
YannickV OK
End.

Can be closed :+1:
