### ISSUE TITLE
[Question]How to launch a script when article content is loaded / visibility is toggled

### ISSUE THREAD

**Issue by lapineige** [FreshRSS/FreshRSS#1713]
Hello,
I'm making an extension to convert Youtube videos (embedded in an article) to Hooktube videos.

I need to launch the script when article content is fetched, to replace the iframe source.
Or when an article content visibility is toggle on, it's kind of a waste of resources (because it doesn't need to be replaced several times) but might be easier to implement.

To you know how I can do that ?
Thanks :)

**Comment by kevinpapst** [comment]
The iframe source is not embedded in Youtube RSS feeds, thats why I wrote the Youtube extension:
https://github.com/kevinpapst/freshrss-youtube 

You can fork it and adapt the extension.php to your needs.

**Comment by lapineige** [comment]
I didn't know that.
I'm not using them directly for privacy reasons (I use RSS Bridge for that, example here: https://vps.lapineige.fr/rss-bridge).
However the source is embedded in other feeds (apart from youtube).

I might have to adapt my extension in order to handle your extension's frames. I'll take a look.
(and also to change the default thumbnails from youtube to one coming from hooktube, if possible...)

**Comment by Frenzie** [comment]
Here's an example script I'm using with CustomJS btw.

```js
// all the lame browsers, namely those other than Opera/Presto and Prince, don't
// do CSS generated content on images...

function show_img_titles(img) {
	img.after('<div class="show-img-title">Mouseover title: ' + img.attr('title') + '</div>');
}

function init_show_img_titles() {
	if (window.$) {
		$('img[title]').each(function(){
			show_img_titles($(this));
		});

		var observer = new MutationObserver(function(mutations) {  
			mutations.forEach(function(mutation) {
				for (var i = 0; i < mutation.addedNodes.length; i++) {
					//console.log(mutation.addedNodes[i])
					$(mutation.addedNodes[i]).find('img[title]').each(function(){
						show_img_titles($(this));
					});
				}
			});
		});
		observer.observe(document.querySelector('#stream'), { subtree: true, childList: true });
	}
	else {
		window.setTimeout(init_show_img_titles, 50);
	}
}

init_show_img_titles();
```

**Comment by Alkarex** [comment]
Related to https://github.com/FreshRSS/FreshRSS/issues/1737

**Comment by lapineige** [comment]
Yes, and we seem to be all working with almost the same goal in (not so) different ways.

@Korbak @kevinpapst maybe we can join efforts here ?
I was thinking about making hooktube an option of your extension @kevinpapst, and adding the possibility to replace Youtube frames embedded in feeds content by Hooktube's ones.

That would make it easier to maintain, as it would be just one extension with an additional option + a small function.

At least @Korbak extension is very similar to @kevinpapst's one (a whole new extension for a single modification ^^), and mine is not that different.

**Comment by kevinpapst** [comment]
That would be great! I am planning an update of the Youtube extension to be a more generic video plugin, but I need a little refactoring of FreshRSS for that as well. 
But until then, we could add that feature to the Youtube extension. Just add a user config and a checkbox in the configure.phtml.

**Comment by lapineige** [comment]
I'm closing this, as I no longer plan to do that port (because of some disagreement with Hooktube owner positions).

Thanks anyway for the advices, it might be useful later :)
