### ISSUE TITLE
[Question] How to query MySql to get full content

### ISSUE THREAD

**Issue by rescog** [FreshRSS/FreshRSS#1719]
Hi, I'd like to query the database in MySql in order to export a csv file with my articles. 

I have no problem selecting the columns I need, except for the "content_bin" column in "frxh_admin_entry". 

The content are Blob objects and I understand I have to convert them, but I don't know how.  I've tried to use the CONVERT and CAST functions with no luck. 

My desired output would include just the plaint text content of the articles (without images).

Hope to get some help :)

**Comment by rescog** [comment]
I tried this query and it actually worked:

SELECT UNCOMPRESS(`frxh_admin_entry`.`content_bin`) AS content
FROM frxh_admin_entry

Now I'm getting the text I need in "content" column, although I'm also getting a lot of undesired HTML tags among with the text. I think I can simply search and replace the undesired tags if you don't have a better idea.

Thank you very much Alkarex!

**Comment by aledeg** [comment]
You have to take care of that on your end. What you've got is what FRSS received. So there is not much it can do. If the feed has tags, they are saved in the ```content_bin``` field.
If you need the text only, I can recommend using [pandoc](https://pandoc.org/). It can convert any text format to any other text format. I don't know if you can script it though.

**Comment by rescog** [comment]
Thanks Aledeg, everything's clear now. I'll give a look to pandoc.
