### ISSUE TITLE
Problem with feed

### ISSUE THREAD

**Issue by kevinpapst** [FreshRSS/FreshRSS#1721]
Log states:
`[warning] --- A feed could not be found at `http://www.skydivemag.com/feed/RSS2`; the status code is `200` and content-type is `text/plain; charset=UTF-8` [http://www.skydivemag.com/feed/RSS2]`
That feed was working once, so they site owner misconfigured their server ... but: besides the fact that I could pipe the feed through another tool, can we "fix" that in FreshRSS as well? 

Is there a chance we can force the feed parser to try to read a resource with a valid response code? The xml parser should throw an exception if content is not parseable. Or this a stupid idea? 

Edit: Not related to the dev branch...

**Comment by Alkarex** [comment]
Try to add `#force_feed` as the end of the URL

**Comment by Frenzie** [comment]
Yes, advertising that better (without having to read the manual) and making it easier to use is one of my personal to-do items, but in the "someday" category. I have no direct plans to work on that.

**Comment by kevinpapst** [comment]
Is that mentioned in the docu? I tried to find it, but couldn't... 
Anyway, great trick, solved the problem immediately, thanks :-)
