### ISSUE TITLE
freshrss + rss-bridge = timeout

### ISSUE THREAD

**Issue by kprimice** [FreshRSS/FreshRSS#1722]
I am trying to use FreshRSS with RSS Bridge for Twitter (or Facebook) but it doesn't seem to work on my server.

I temporarily opened the access if you wanna test it : 

> cURL error 28: Connection timed out after 15000 milliseconds [https://rssbridge.posc.in/?action=display&bridge=Twitter&u=elonmusk&format=Atom] 

Both FreshRSS and RSS Bridge are on the same server.

Also, I was on version 1.7.0 and just upgraded to 1.7.1-dev and I still get the same error 28.

**Comment by Alkarex** [comment]
It looks like a networking issue.

Are you able to cURL your RSS bridge manually from your server?
Something like:
```sh
time curl -v -m 20 'https://rssbridge.posc.in/?action=display&bridge=Twitter&u=elonmusk&format=Atom'
```

Can you access it more directly (since it is running on the same server), e.g. without HTTPS, or using localhost?

**Comment by kprimice** [comment]
Thanks for your reply.

I found the problem but not the solution (yet).
freshrss and rssbridge run inside two separate docker containers, on the same network. So if I try to access rssbridge like this:

`time curl -v -m 20 'rssbridge.posc.in/?action=display&bridge=Twitter&u=elonmusk&format=Atom'`

It works because it stays inside the network. But if I add http or https:

`time curl -v -m 20 'https://rssbridge.posc.in/?action=display&bridge=Twitter&u=elonmusk&format=Atom'`

It fails (timeout). So you were right, it's obviously a networking issue.

**Comment by aledeg** [comment]
As it has nothing to do with FRSS, I am closing it.

**Comment by kprimice** [comment]
In case it helps someone else, solution found:

`time curl -v -m 20 http://rssbridge/?action=display&bridge=Twitter&u=elonmusk&format=Atom`
