### ISSUE TITLE
feeds could not be added

### ISSUE THREAD

**Issue by yaute74** [FreshRSS/FreshRSS#1727]
Hello,

I just install FreshRss without errors but I cannot add feeds.
I test several url but it doesn't work, always with the same error "xxx could not be added".
For exemple I test https://www.lequipe.fr/rss/actu_rss.xml who work on other rss reader.
When I go into "installing checking" all is green.
If I open the database I have only one table "freshrss_category". It's normal ?
I search logs into /var/log but I find nothing. Where can I have more information about my error ?

Regards

**Comment by Alkarex** [comment]
Hello,
If you have only one table, then there is something wrong indeed.
What database are you using, version of FreshRSS and PHP, type of server?

**Comment by yaute74** [comment]
I use PHP 7.1 with MySQL 5.7 and FreshRss 1.8.0
I find another error from the configuration menu:
"SQL error addFeed: Table 'freshrss.freshrss_freshrss_feed' doesn't exist"

**Comment by Alkarex** [comment]
If you have a MySQL log, there is probably some errors earlier, during the install.
Do you have enough disk space for your MySQL?
I suggest you drop your FreshRSS database, and restart the install.

**Comment by yaute74** [comment]
Ok, how can I restart install ?
I try http://...app/install.php but I have an error "You don't have permission to access"
Thanks for your help

**Comment by Alkarex** [comment]
If it is a new installation, I suggest you just delete your FreshRSS directory and try again.
How did you install? Via git, or zip?

**Comment by yaute74** [comment]
I restart install and it ok :)
For information:
For my first install I create the database before the installation
For my second I don't create the database before the installation

Thanks for your help
