### ISSUE TITLE
too much spacing on reading view

### ISSUE THREAD

**Issue by jacksnodgrass** [FreshRSS/FreshRSS#1730]
I like the 'reading view' to view articles but on articles with minimal text... the spacing is too much between articles.  I looked at the CSS and can't figure out why. 

It is not just related to one RSS feed.  

- jack 
![selection_071](https://user-images.githubusercontent.com/3471734/34078869-b0b7472e-e2e7-11e7-9b3b-5ad14e37684f.png)

**Comment by aledeg** [comment]
Check https://github.com/FreshRSS/FreshRSS/blob/889888f20eb6f3dd476b78c0f59672f7c7962354/p/themes/base-theme/template.css#L532

**Comment by aledeg** [comment]
@jacksnodgrass If you want to modify that, use the [custom css extension](https://github.com/FreshRSS/Extensions/tree/master/xExtension-CustomCSS) and add your rules in its configuration

**Comment by Frenzie** [comment]
@aledeg If you press <kbd>y</kbd> on GH it automatically sticks the commit hash in the URL so the reference will remain relevant in the future. ;-)

https://github.com/FreshRSS/FreshRSS/blob/889888f20eb6f3dd476b78c0f59672f7c7962354/p/themes/base-theme/template.css#L532

(Also it embeds the linked code in the reply these days.)

**Comment by aledeg** [comment]
Good to know. Thanks

**Comment by math-GH** [comment]
is it already solved so that this issue could be closed?
