### ISSUE TITLE
[Feature request] Pause feeds

### ISSUE THREAD

**Issue by Jucgshu** [FreshRSS/FreshRSS#1738]
Hi guys,

I tried to look for this feature on the issue log, and I'm a little surprised that no one asked for that yet?

I know we can prevent a feed from being displayed on the main stream, but I don't think we can pause a feed (meaning don't display it on the main stream, nor refresh it on feeds sync, nor take it into account it in the categories). Or am I completely wrong?

As always, kudos for your work guys.

-j

**Comment by aledeg** [comment]
In the feed configuration, you can configure if you want to retrieve new articles from the feed. Check the ```Do not automatically refresh more often than``` option in the ```Archiving``` section. Then select ```∞```

For the 2 other topics, you're right.

**Comment by Jucgshu** [comment]
Oww right, will try that.

Thanks @aledeg

**Comment by Alkarex** [comment]
Implemented by @aledeg in https://github.com/FreshRSS/FreshRSS/pull/1750 :-)
