### ISSUE TITLE
Crash de FreshRSS suite à une MAJ

### ISSUE THREAD

**Issue by Nagumo76** [FreshRSS/FreshRSS#1741]
Bonsoir,

J'ai voulu passer de la version 1.4 à la version 1.5.
La MAJ s'est mal passée puisque j'obtiens ceci :

"Warning: require(../../constants.php): failed to open stream: No such file or directory in [adresse]/p/i/index.php on line 21

Fatal error: require(): Failed opening required '../../constants.php' (include_path='.:/home/temporaire/upload:/usr/local/lib/php/:/usr/local/lib/ZFramework') in [adresse]/p/i/index.php on line 21" 

Que me conseillez-vous de faire ? 
Merci par avance de votre aide !

**Comment by Alkarex** [comment]
Bonsoir,
Je vous suggère de :
* Faire une copie / archive de votre répertoire FreshRSS ;
* Télécharger la version actuelle 1.9.0 https://github.com/FreshRSS/FreshRSS/releases/tag/1.9.0 ;
* Décomprimer le ZIP dans votre répertoire FreshRSS ;
* Ré-appliquer les droits d'accès dans tout le répertoire FreshRSS ;
* Ré-essayer d'accéder à FreshRSS depuis votre navigateur.

**Comment by Nagumo76** [comment]
Bonjour,

Je vous remercie de votre réponse.
Je vais essayer de procéder ainsi, mais si ne n'y arrive pas, j'enlèverai tous les fichiers et je ferai une réinstall' avec la dernière version.
Petite question : est-ce qu'il y a un fichier qui me permettrait de retrouver l'ensemble des flux RSS abonnés ?

Merci et bonne journée.

**Comment by Alkarex** [comment]
@Nagumo76 Vos flux sont conservés en base de données. Qu'utilisez-vous ? MySQL, SQLite...

**Comment by Nagumo76** [comment]
Bonsoir,

Désolée pour ma réponse tardive.
J'ai finalement supprimé l'ancien répertoire et réinstallé la dernière version (1.9).
Je vais maintenant réintroduire à la mano l'ensemble des flux RSS car la sauvegarde de ma BD ne semble pas être reconnue.
Ce n'est pas grave, j'ai probablement loupé une étape (mais j'aurais préféré comprendre).

Merci encore pour votre aide.

**Comment by Alkarex** [comment]
Ok :-) Vous pouvez par exemple faire une sauvegarde de votre fichier OPML (liste des flux) de temps en temps, pour une migration ou réinstallation facile.
