### ISSUE TITLE
Problèmes de droits à l'étape 1 de l'installation

### ISSUE THREAD

**Issue by ejrhoffmann** [FreshRSS/FreshRSS#1742]
Bonjour,
Je tente d'installer FreshRSS chez un hébergeur.
À l'étape 1 'Vérifications', j'obtiens le message suivant :
![image](https://user-images.githubusercontent.com/4470284/34210521-8c1a1778-e5af-11e7-84f0-39f20ad01850.png)
J'essaie de modifier les droits sur les répertoires listés, mais je ne trouve pas le bon réglage.
Merci.
Bonne journée,
Éric

**Comment by Alkarex** [comment]
Avez-vous un accès SSH ? Ou seulement un accès (S)FTP ?
Pourriez-vous montrer les droits actuels ?

**Comment by ejrhoffmann** [comment]
Bonjour,
Merci pour votre réponse.
En fouillant dans la doc de l'hébergeur, j'ai trouvé comment faire les bons réglages... Et l'installation s'est terminée sans problème.
Désolé pour le dérangement.
Heureux Noël à tous !
Éric

**Comment by Frenzie** [comment]
No problem. Joyeux Noël!
