### ISSUE TITLE
Unknow error for feed pour Rugbyrama

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#1743]
BOnjour,

Impossible d'ajouter le flux Rugbyrama dans Freshrss, il s'affiche correctement dans firefox, mais si je veux l'ajouter à freshrss j'ai le message suivant les logs :

`Unknown error for feed [https://www.rugbyrama.fr/rugby/rss.xml]`

**Comment by Alkarex** [comment]
Le flux a plusieurs problèmes https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.rugbyrama.fr%2Frugby%2Frss.xml mais le problème principal est que son type MIME est invalide `application/rss%2Bxml; charset=utf-8` à cause d'un problème d'encodage.

Nettoyez le cache (ou attendez ~1h et de nouveaux articles) :

```sh
grep 'rugbyrama' -l -r ./FreshRSS/data/cache/ | xargs rm
```
puis essayez avec `https://www.rugbyrama.fr/rugby/rss.xml#force_feed`

**Comment by ghost** [comment]
Merci beaucoup, avec `https://www.rugbyrama.fr/rugby/rss.xml#force_feed` ça fonctionne
