### ISSUE TITLE
Feed update

### ISSUE THREAD

**Issue by opitux** [FreshRSS/FreshRSS#1748]
Bonjour,

Je viens d'installer Freshrss pour l'essayer. Tout est ok mais je ne parviens pas à mettre à jour mes flux.

Quand je teste l'update par ssh, j'ai la réponse suivante :
```
Starting feed actualization at 2017-12-21T14:57:04+01:00
FreshRSS install failed requirements:
• pdo-mysql
• fileinfo
• dom
• ok
```
Pourtant, quand je vérifie l'installation, tout est ok.
```
Vous disposez de PDO et d’au moins un des drivers supportés (pdo_mysql, pdo_sqlite, pdo_pgsql). 
Vous disposez de la librairie fileinfo.
Vous disposez de la librairie pour parcourir le DOM. 
```
Et tous les droits sont bons. Je dois louper quelques chose :(

Je suis chez Yulpa, ex Web4all, en mutualisé et j'ai installé via FTP...

Merci d'avance pour vos retours :)

**Comment by Alkarex** [comment]
Bonjour,
Le test de vérification de l'installation est par l'interface Web, n'est-ce pas ?
C'est très certainement que vous avez deux versions de PHP (par exemple une version CLI et une version CGI), pas avec les mêmes réglages.

**Comment by opitux** [comment]
Bonjour Alkarex

Merci beaucoup pour ce retour rapide :)

Oui, effectivement, la vérification est faite via l'interface web et il y a bien plusieurs sites sur le serveur dans différentes version de php. Existe-t-il une solution ?

**Comment by Alkarex** [comment]
Essayez de voir si vous pouvez utiliser un autre chemin / exécutable PHP pour votre cron, qui aurait la bonne configuration. Sinon, essayez de voir avec votre hébergeur. En dernière option, il y a des possibilités de faire un cron Web, mais moins bien, et cette fonctionnalité n'est pas encore parfaitement implémentée (mais doit être faite de toute manière).

**Comment by opitux** [comment]
Ok

Bon, je viens de mettre en place un webcron en attendant le retour de mon hébergeur.
Je ferai un retour quand ce sera le cas.

Merci encore :)

**Comment by aledeg** [comment]
Je ferme le ticket car tu as trouvé une solution (temporaire). N'hésite pas à le ré-ouvrir si tu as d'autres questions liées.

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/issues/613
