### ISSUE TITLE
Spinning "Loading" Icon, But Nothing Being Fetched

### ISSUE THREAD

**Issue by vindicatorr** [FreshRSS/FreshRSS#1749]
FreshRSS Version 1.9.0
Chrome Version 63.0.3239.84

I find that there are times when I reach the bottom (not end) of the feeds, and get the spinning "loading" icon, but the rest isn't fetched.
I do not see any consistency with the issue and has not been seen in previous 2 versions.

EG:
In Main Stream
Click to fetch new articles
Scroll/pgdn through articles
*Articles are fetched OR I'm left stuck at the spinning loading icon
(take note of last article at 23:05)
Ctrl-Home to the top and click "There are new available articles..." (or just refresh I guess. just don't mark all as read)
Scroll through all over again
Articles are fetched
(take note that the fetched articles now pass the previous last article at 23:05)
Continue scrolling as usual
Reach end with "There are no more articles" Checkmark icon "Mark all as read"
Click checkmark icon

**Comment by Alkarex** [comment]
It sounds like a network issue, with the request sent but the response is lost.
In your browser, try to check the network developer tab:
![image](https://user-images.githubusercontent.com/1008324/34298987-d2bd725c-e720-11e7-9ffe-4b134bf13a32.png)

From FreshRSS side, we could consider adding a check to resubmit a failed request.

**Comment by Frenzie** [comment]
Or at least some kind of timeout/error handling; not necessarily auto-resubmit since the network might have disappeared or something. 

I do see some .fail on $.ajax but no timeouts and I didn't investigate if there's a .fail on whatever applies here. Just a quick 10-second source search. ;-)

**Comment by vindicatorr** [comment]
Unlikely a network issue. It's on my odroid which is 1 hop away and I might be watching tv over the network at the same time and not see any effect.
Again, only something I have seen with this version.

I have my dev tab open now, so hopefully I'll have something useful to add next time.
I hadn't seen any issues in the logs or journal though.

**Comment by vindicatorr** [comment]
Nothing yet after 2k+ new items, but a thought just came to me...
Whenever there are system updates like php-fpm that might affect freshrss, maybe I have to refresh the web page. Just riffing possibilities here.
Ugh, but then again, I don't think that's it since it would happen while I was going through the feeds (unless I mindlessly updated my server while going through the feeds).

I do know that if I reboot my server, I would have to refresh the web page.

An interesting side-effect though is, after rebooting the server but before refreshing the web page, the web page is somehow authorized to notify there are new feed updates, but if I refresh the web page, I am sent to the login page.

**Comment by Alkarex** [comment]
Could you maybe make an account for me, so I could give it a try?

**Comment by vindicatorr** [comment]
I could, but you still wouldn't be able to access it since my server is inaccessible from the internet.

**Comment by Alkarex** [comment]
Did you manage to see in your logs (client side and/or server side) where the request (if any) is hanging?
P.S. For instance, a screenshot of your browser's network tab together with your Web server latest lines would help.

**Comment by vindicatorr** [comment]
Nothing has changed since my last report.
I suppose this can be closed until which time I encounter the issue and I will submit the needed info.

**Comment by Alkarex** [comment]
Ok :-)

**Comment by vindicatorr** [comment]
To update this issue, I installed some updates which included php-fpm.
The spinning wheel sort of occurred while the updates were happening, specifically boost stuff and took 30-40 seconds to return, but it at least DID return rather than just hang.

Then after I restart the php-fpm service, I can not continue paging through the feeds unless I refresh, yet the jquery nbUnreadsPerFeed keep happening before I refresh which is an oddity in it's own right. Yup, before refreshing, I just got another desktop notification of new feed items.

**Comment by Alkarex** [comment]
The usual things first:
* Please try with another browser without any extension.
* Check whether there is any message in the JavaScript console.

And then, please try to see (and provide a screenshot):
1) If there is a request emitted by your browser (browser developer tools / network);
2) If the request is received by your Web server (HTTP logs).

**Comment by vindicatorr** [comment]
Key point at "**" below.
I didn't use any other browser, but I did use a separate "clean" profile in chrome that has no extensions or any customizations whatsoever.

I went ahead and did a simple test of just restarting the php-fpm service since I was sure that's where the issue stemmed from (the other oddity, not the original "loading" hang, which I still haven't encountered again).

Outside of
```
<link rel=preload> must have a valid `as` value
```
and
```
Refused to display 'http://<server>/themes/icons/grey.gif' in a frame because it set 'X-Frame-Options' to 'deny'.
```
in the browser (only because I didn't use https in this test), there were no problems.

The last error written to the web server log was at 19:22, but I had restarted the service at 19:42.
The last access was just this very moment (which coincides with the browser dev-tools network log).
```
<ip> - - [11/Jan/2018:01:08:48 -0600] "GET /i/?c=javascript&a=nbUnreadsPerFeed HTTP/1.1" 304 0 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
```
And when I had tried to page through later on after the restart:
```
<ip> - - [11/Jan/2018:01:00:17 -0600] "GET /i/?a=normal&next=1515616866295046&state=2&ajax=1 HTTP/1.1" 200 2015 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.84 Safari/537.36"
```
Dev-tools while paging through feeds shows:
(before restart):
```
...
<script src="../scripts/shortcut.js?1513596602" defer="defer" async="async"></script>
<script src="../scripts/main.js?1513596602" defer="defer" async="async"></script>
		<link rel="shortcut icon" id="favicon" type="image/x-icon" sizes="16x16 64x64" href="../favicon.ico" />
...
		<title>(2420) Your RSS feeds · FreshRSS</title>
		<link id="prefetch" rel="next prefetch" href=".?a=normal&amp;next=1515614446491879&amp;state=2&amp;ajax=1" />
		<link rel="alternate" type="application/rss+xml" title="Your RSS feeds | FreshRSS" href=".?a=rss&amp;next=1515616866295046&amp;state=2&amp;ajax=1&amp;hours=168" />
		<meta name="robots" content="noindex,nofollow" />
	</head>
---->>	<body class="normal">
<ul class="nav nav-head nav-login"><li class="item"><img class="icon" src="../themes/icons/logout.svg" alt="🔓" /> <a class="signout" href=".?c=auth&amp;a=logout">Logout</a></li></ul>
<div class="header">
	<div class="item title">
...
```
(after restart):
```
...
<script src="../scripts/shortcut.js?1513596602" defer="defer" async="async"></script>
<script src="../scripts/main.js?1513596602" defer="defer" async="async"></script>
<script src="../scripts/bcrypt.min.js?1513596602" defer="defer" async="async"></script>
		<link rel="shortcut icon" id="favicon" type="image/x-icon" sizes="16x16 64x64" href="../favicon.ico" />
...
<meta name="robots" content="noindex,nofollow" />
	</head>
---->>	<body class="formLogin">
<ul class="nav nav-head nav-login"><li class="item"><img class="icon" src="../themes/icons/login.svg" alt="🔒" /> <a class="signin" href=".?c=auth&amp;a=login">Login</a></li></ul>
<div class="header">
	<div class="item title">
...
```

From this, it can be seen that after restarting php-fpm, paging through looks like it's trying to display the login form, but it doesn't reflect in the browser view. You just see the feeds, but cannot page through any further.

I'll add a couple of other things I tried after the restart:
Clicking on a feed item expands the item, with no visible problems, but dev-tools shows:
```
http://<server>/i/?c=entry&a=read&id=1515628862167184
302 Found
.?c=error
...
http://<server>/i/?c=error
403 Forbidden
```
yet subsequent
```
http://<server>/i/?c=javascript&a=nbUnreadsPerFeed
```
still happens with no errors.

Clicking on a feed group in the list on the left redirects me to the login page.
But clicking an item in the configure-dropdown list returns the freshrss 403 page giving me the option to go back to the RSS feeds while also displaying the Login link at the top right. Clicking the go back to the RSS feeds link redirects to the login form.

**So the takeaway from all of this is to redirect the page to the login page when the paging "next" request returns the login form (or replace the entire page with that returned login form).

I figure it would be a simple test you could try yourself.
1) go to your rss feeds
2) open dev-tools
3) page down to fetch "next" feeds
4) restart php-fpm service
5) try to page down for more feed items
6) crash and burn (or reap debugging info)

**Comment by kevinpapst** [comment]
I can confirm that I have seen similar behaviour a couple of times as well.
I always use the "Kepp me logged in" option and if that login expires, you will not be notified. You can read already fetched articles, but the read state doesn't change. You see the "load more articles" button, but it doesn't work (for me the link disappears and the spinner is removed though).
Just log in and remove the FreshRSS cookies, then try to load more articles.

Probably the script that checks for new articles (and sends the browser notification?) should trigger an event in case of a unauthorized answer. Then we need some event handler that listens here and redirects to the login  page.

@vindicatorr Could you try to check if deleting the cookies has the same result for you than restarting your php-fpm?

**Comment by Frenzie** [comment]
Or perhaps more likely as a regular occurrence, two tabs, log out in one.
