### ISSUE TITLE
Error on fresh install from a zip file

### ISSUE THREAD

**Issue by geogiraux** [FreshRSS/FreshRSS#1763]
Hi
I'm trying a fresh install from a fresh FreshRSS-master.zip file. For information about myself, I've never run FreshRSS before and I'm quite new in running my own webserver
Installation fails on step 3 (after validating a sqlite database) with the following error : Call to undefined function filter_var() in /www1/FreshRSS-master/lib/Minz/Request.php on line 134
But as far as I know I'm running PHP version 5.4 and everything was "green" on the first step
Thanks in advance

**Comment by Alkarex** [comment]
Hello,
Could you please give more information about the precise PHP version, operating system, and Web server?

In case of doubt, you can place a `phpinfo.php` at the root of your Web server, with the content below, and then call it from your browser:

```php
<?php
phpinfo();
```

**Comment by Frenzie** [comment]
According to the manual [filter_var()](https://secure.php.net/manual/en/function.filter-var.php) is defined in PHP 5 >= 5.2.0. I believe you can manually compile PHP without the filter module though.

**Comment by geogiraux** [comment]
Hello
Webserver is lighttpd, and PHP version is 5.4.5.
But running phpinfo() I see '--disable-filter' in the compile option (which I didn't do myself)
I close it, thanks for the help
