### ISSUE TITLE
Advanced search broken?

### ISSUE THREAD

**Issue by Jucgshu** [FreshRSS/FreshRSS#1768]
Hi guys,

Tried the [advanced search](https://freshrss.github.io/FreshRSS/en/users/03_Main_view.html#searching-articles) for the first time today. 

I tried the ```or```condition, which doesn't seem to work as expected : when I perform a search on each criteria, I find articles. But when I try to combine both criteria with ```or```, I end up having no results.

Using last commit from /dev branch and SQLite.

-j

**Comment by Alkarex** [comment]
~~Indeed, I have also just noticed that the `date:` search does not work on my /dev instance https://github.com/FreshRSS/FreshRSS/issues/1770
Will be fixed with high priority~~
Edit: I tested a bit too hastily. date filters seem to work as expected after all.

**Comment by Alkarex** [comment]
Hello @Jucgshu ,
Sorry for the previous message (tested too fast). Everything seems to work as expected, except that we currently only implement implicit AND, as well as negation, but no support for OR yet. See https://github.com/FreshRSS/FreshRSS/issues/879

**Comment by Alkarex** [comment]
I suggest we continue in https://github.com/FreshRSS/FreshRSS/issues/879

**Comment by Jucgshu** [comment]
That's my fault. I read the documentation too fast (damn!) and thought one could use the ```or``` operator.

Thanks for your quick answer @Alkarex
