### ISSUE TITLE
Can't mark all item unread

### ISSUE THREAD

**Issue by Stegemueller** [FreshRSS/FreshRSS#1780]
Hello again

I can't make the button "Mark all as read" work. It is dimmed. I have checked the settings, the config-file and all places I could find something with "Mark read" and "Show only unread". My wish is to just display unread posts, so that I get a good and simple overview over my subscriptions.

I have tried both Firefox and Chrome.

My system: Windows 10 pro, 64 bit. SQL-lite,. When I go to "Installation Checking" all rows are green. "Your PHP version is 5.6.33, which is compatible with FreshRSS.". 

Permissions on data directory are good.
Permissions on cache directory are good.
Permissions on users directory are good.
Permissions on favicons directory are good.
Permissions on tokens directory are good. 

I hope, you can give me some good advice as the system looks cool, and I would really like to get it up and running.

![rss](https://user-images.githubusercontent.com/36283816/36030416-6d318d76-0da7-11e8-9d14-e2fb298a885d.png)

Best regards,
Hanne,
Denmark

**Comment by Alkarex** [comment]
Hello again,
The default setting, visible in Configuration / Reading / Articles to display, is *Adjust showing*, which shows only unread articles (as you want), except in the case when there is no more unread articles, in which case it shows all articles. Maybe this was a source of confusion?

![image](https://user-images.githubusercontent.com/1008324/36034345-1e295fc6-0db4-11e8-9e91-fcaa6fa64de3.png)

Could you please post a screenshot of the "Mark all as read" button when it does not work?

**Comment by Stegemueller** [comment]
Hi Alkarex

I was not aware, that I should answer here and not in the e-mail. So sorry!

I have configured FrehRSS like you suggested. See screen shots. 

![freshrss_1](https://user-images.githubusercontent.com/36283816/36933011-4952a598-1ed2-11e8-8d8f-9281f9188a4f.png)
![freshrss_2](https://user-images.githubusercontent.com/36283816/36933012-4970a6a6-1ed2-11e8-9fac-5e9938bf6260.png)

I don't know if I misunderstand something, but I would so much like to "Mark all as read", but nothing happens, when I click that menu point.

Best regards,
Hanne

**Comment by Alkarex** [comment]
Hej Hanne,
Is the screenshot you show taken after you have tried to click on "Mark all as read"?
If yes, I have not seen this problem before. Can you see anything in the FreshRSS logs (available from the settings menu)?
If you want, you could create me a test account, so I could see by myself.

**Comment by math-GH** [comment]
@Stegemueller Is it still an issue with 1.19/1.20?

**Comment by Stegemueller** [comment]
Thanks math-GH for asking. That is kind of you.

No this is not an issue any more.

Best regards,
Hanne
