### ISSUE TITLE
Movim sharing broken

### ISSUE THREAD

**Issue by poVoq** [FreshRSS/FreshRSS#1781]
Seems like with recent versions of Movim the sharing feature isn't working.

All I get is a giant sharing symbol and some garbled URL on the redirected page in Movim (or a login screen if not logged in before clicking the share link).

I guess something changed on the Movim side of things?

**Comment by Alkarex** [comment]
Maybe something for @edhelas or @aledeg to look at?

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/issues/992

**Comment by aledeg** [comment]
I cannot find documentation on how to share with movim. If someone has better luck than me, it would be nice to share it here.

**Comment by Alkarex** [comment]
Fixed by @pattems in https://github.com/FreshRSS/FreshRSS/pull/2177
Tests welcome
