### ISSUE TITLE
How to make \data\ unaccessible?

### ISSUE THREAD

**Issue by michaelbrendel** [FreshRSS/FreshRSS#1784]
In the installation instructions there is the recommendation not to expose the data directory because of its sensible content. But I have no idea how to prevent access to that directory. Any tipps?
When I try to access config.php by typing the complete URL into my browser, a 403 error occurs. Is that safe enough?

Thanks a lot!
Micha

**Comment by Frenzie** [comment]
There are a few example configs here: https://freshrss.github.io/FreshRSS/en/admins/02_Installation.html

I think there's an issue about linking to more docs directly from the README somewhere but I can't find it atm.

**Comment by marienfressinaud** [comment]
The link doesn't work anymore. To be complete for people ending here, you should set the root path of your webserver to `/path/to/freshrss/p` (the `/p` is important!)

More info here: https://github.com/FreshRSS/FreshRSS/blob/master/docs/en/admins/10_ServerConfig.md
