### ISSUE TITLE
Update generated RSS each day

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [FreshRSS/FreshRSS#1787]
I am using FreshRSS only to aggregate several RSS from different sources to create a single RSS from it that I use with thunderbird.

How do I make the single RSS update daily without having to log in to FreshRSS each day? Is there a cron-job possible?

**Comment by Alkarex** [comment]
@ErfolgreichCharismatisch Yes of course : using a cron is the normal way to get new articles into FreshRSS :-)

See:
* https://github.com/FreshRSS/FreshRSS#automatic-feed-update
* https://freshrss.github.io/FreshRSS/en/users/03_Main_view.html#refreshing-feeds

Do not hesitate to ask again if you get a problem.

Afterwards, if you set a token in your user settings, you can get a RSS feed for any view of FreshRSS (for instance the main view with all articles) without having to log in.

**Comment by ErfolgreichCharismatisch** [comment]
That works!
