### ISSUE TITLE
[Question] How do you sort all articles by date?

### ISSUE THREAD

**Issue by P4tches** [FreshRSS/FreshRSS#1789]
When I sort articles by date it seems to always sort each feed by date and then stack the feeds on top of each other instead of combined. Is there a setting to have a combined sort by date?
![screenshot from 2018-02-18 17 54 40](https://user-images.githubusercontent.com/1151993/36359971-de66ecb4-14d4-11e8-842c-90a9cb6d3230.png)

**Comment by rsverboc** [comment]
Also wondering

**Comment by rsverboc** [comment]
following
