### ISSUE TITLE
still get some Content Security Policy reports

### ISSUE THREAD

**Issue by oupala** [FreshRSS/FreshRSS#1793]
I'm using FreshRSS and it appears that the default Content Security Policy of FreshRSS still generate some reports.

```
{
    "csp-report": {
        "blocked-uri": "data",
        "document-uri": "https://example.org/i/?c=configure&a=system",
        "original-policy": "default-src https://example.org; report-uri https://report.example.org csp_reports/",
        "referrer": "",
        "violated-directive": "default-src https://example.org"
    }
}
```

Is it normal?

**Comment by Alkarex** [comment]
Could you please try to see in your Web browser console if you can reproduce the situation that generates CSP warnings? The most likely is with sites loading iframes or similar things.

**Comment by oupala** [comment]
It might be due to a cached CSP directive.

Give me some time to see if I can reproduce the problem.

**Comment by oupala** [comment]
I confirm that I still get some CSP reports:

```log
2018-10-08 01:27:59 {
    "csp-report": {
        "blocked-uri": "https://example.com/rss/themes/icons/icon.svg",
        "document-uri": "https://example.com/rss/",
        "original-policy": "upgrade-insecure-requests; default-src 'none'; report-uri https://example.com/csp_reports/",
        "referrer": "",
        "violated-directive": "default-src"
    }
}
2018-10-08 01:27:59 {
    "csp-report": {
        "blocked-uri": "https://example.com/rss/themes/p.css",
        "document-uri": "https://example.com/rss/",
        "original-policy": "upgrade-insecure-requests; default-src 'none'; report-uri https://example.com/csp_reports/",
        "referrer": "",
        "violated-directive": "default-src"
    }
}
```

My csp report apache directive is: `Header edit Content-Security-Policy "$" "; report-uri /csp_reports/"` so it should keep the directive set by FreshRSS.

Any idea?

**Comment by Alkarex** [comment]
P.S. Please check that your FreshRSS icons and CSS styles are loaded correctly. If yes, then it should be fine.

**Comment by oupala** [comment]
The CSP report comes when I load the login page, and it occurs before the login page.

In fact, it occurs when the browser loads the first first page `https://example.com/rss/` which is then redirected to `https://example.com/rss/i/`.

I think this first first page does not have CSP enabled. Can you confirm?

**Comment by oupala** [comment]
Here are the traces:

```html
< HTTP/1.1 200 OK
< Date: Sat, 13 Oct 2018 09:46:54 GMT
< Server: Apache
< Strict-Transport-Security: max-age=15768000; includeSubDomains; preload
< Last-Modified: Sun, 09 Sep 2018 11:03:51 GMT
< Accept-Ranges: bytes
< Content-Length: 774
< Vary: Accept-Encoding
< X-Frame-Options: DENY
< X-Xss-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< Referrer-Policy: strict-origin-when-cross-origin
< Content-Security-Policy: upgrade-insecure-requests; default-src 'none'; report-uri /csp_reports/; report-uri /csp_reports/
< Cache-Control: public
< Content-Type: text/html; charset=utf-8
< 
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-GB" lang="en-GB">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="initial-scale=1.0" />
<meta http-equiv="Refresh" content="0; url=i/" />
<title>FreshRSS</title>
<link rel="stylesheet" href="themes/p.css" />
<link rel="shortcut icon" type="image/x-icon" sizes="16x16 64x64" href="favicon.ico" />
<link rel="icon msapplication-TileImage apple-touch-icon" type="image/png" sizes="256x256" href="themes/icons/favicon-256.png" />
<meta name="msapplication-TileColor" content="#FFF" />
<meta name="robots" content="noindex" />
</head>

<body>
<h1><a href="i/">FreshRSS</a></h1>
<p><a href="i/"><img class="logo" width="25%" src="themes/icons/icon.svg" alt="⊚" /></a></p>
</body>
</html>
```

The CSP directive I can see is set by my server, not by FreshRSS.

**Comment by Alkarex** [comment]
The trace you have there is from the HTML redirection page, not from your FreshRSS main view

**Comment by oupala** [comment]
I know, but it is this redirection page that generates CSP reports. I never said that the reports occured in the FreshRSS main view.

**Comment by Alkarex** [comment]
Ah ok, then it is not related to FreshRSS, but purely controlled by your Web server configuration. That redirection page is a simple HTML page with no special rule. It is normal to have images, styles, and scripts to fail with your rule `default-src 'none'`

**Comment by oupala** [comment]
Yes, you're right. I see. And there is no way to set theses headers in the html file.

I'll have to change my default rule to a less strict one.

Thanks @Alkarex for helping to diagnose.

**Comment by oupala** [comment]
Here is my apache config so there is no more CSP reports:

```apache
# this parameter is mandatory to enable access for other clients
# but it does not seem mandatory for EasyRSS
# see https://freshrss.github.io/FreshRSS/fr/users/06_Mobile_access.html
AllowEncodedSlashes On

<Directory /var/www/rss/>
    Header edit Content-Security-Policy "$" "; report-uri /csp_reports/"

    <Files index.html>
        Header set Content-Security-Policy "upgrade-insecure-requests; default-src 'none'; img-src 'self'; style-src 'self'; report-uri /csp_reports/"
    </Files>
</Directory>
```

This could help someone, one day...
