### ISSUE TITLE
Auth failed when using feedme

### ISSUE THREAD

**Issue by mourningsun75** [FreshRSS/FreshRSS#1795]
I cant get it work with feedme (beta) and updated version of freshrss.
On Android i get: auth failed.
In my nginx logs i can see the following error: /var/www/FreshRSS/accounts/ClientLogin" failed (2: No such file or directory)

I dont know what to do....

**Comment by Alkarex** [comment]
Hello,
Did you succeed with other mobile clients (News+, EasyRSS), or is it your first test at using a mobile app?
Please ensure that you have enabled the API in FreshRSS settings, at set an API password.

**Comment by Alkarex** [comment]
Ah, and given the error message that you got, it looks like the address was wrong. Try to add `/p/api/greader.php` at the end.

**Comment by mourningsun75** [comment]
Ah, and given the error message that you got, it looks like the address was wrong. Try to add /p/api/greader.php at the end.

That was the solution! Thank you very much! Solved.
