### ISSUE TITLE
No languages after upgrading to 1.10.0

### ISSUE THREAD

**Issue by ParoTheParrot** [FreshRSS/FreshRSS#1797]
I used Fresh RSS in German with no problems. After upgrading to 1.10.0 the app switched to English an on the configuration -display screen I can't select any language!
I looked via FTP on my server: in freshrss/app/i18n are all directories and files are up to date.
Any ideas? TIA.

**Comment by Frenzie** [comment]
I can't confirm that even though I forgot to test it. Did you check the permissions?

**Comment by aledeg** [comment]
That's weird.
I've upgraded yesterday and I have no problem with the languages. I've updated through the update channel.

I agree with @Frenzie, it looks like a permission problem. How did you upgrade? Do you have any logs that could be helpful?

**Comment by ParoTheParrot** [comment]
@Frenzie . I didn't change anything on the server. I updated through the web-app without any problems.
This is how my "configuration -display" page looks like:
![grafik](https://user-images.githubusercontent.com/5046600/36664555-5b22ba42-1ae5-11e8-80e1-e0c3ededd5d9.png)

**Comment by ParoTheParrot** [comment]
the directory `freshrss/app/i18n` has 705 permission (=other read, execute).
>  How did you upgrade? 

Via web-app
> Do you have any logs that could be helpful?

Which logs are you interested in?

**Comment by Alkarex** [comment]
Try to give permissions to the group (4 instead of 0)

**Comment by ParoTheParrot** [comment]
Sorry, nothing new after changing the attributes of  `/freshrss/app`  and all subdirectories:
![grafik](https://user-images.githubusercontent.com/5046600/36782752-2e7c6736-1c7a-11e8-9415-46e91bba0c19.png)

**Comment by Alkarex** [comment]
Please try to add a line `'environment' => 'development',` in your `./data/config.php` and then look at your FreshRSS logs from the Web interface, as well as your Web server logs (potential PHP errors / warnings)

**Comment by Alkarex** [comment]
If you have an SSH access to your server, could you please post the output of the following command:
```sh
cd ./FreshRSS/
ls -alhR
```

If you are willing to share a temporary access to that server, I can try to make some more debugging from my side. Otherwise, I can send you a couple of PHP scripts to do some more testing.

**Comment by ParoTheParrot** [comment]
@Alkarex : sorry, no ssh access 😞

**Comment by ParoTheParrot** [comment]
> Please try to add a line 'environment' => 'development', in your ./data/config.php and then look at your FreshRSS logs from the Web interface, 

Nothing special in the logs

**Comment by Alkarex** [comment]
I will try to find time to prepare some debug scripts for you, which you can upload to your FreshRSS directory.

**Comment by ParoTheParrot** [comment]
I found an error in the log:

> 2018-03-06 09:40:03 SQL error updateCachedValues: database is locked

**Comment by ParoTheParrot** [comment]
In addition: a fresh installation works as expected!

**Comment by ParoTheParrot** [comment]
I compared some file (new installation vs. my old installation). For example, these were not updated an differ from the new installation:

- freshrss/cli/manipulate.translation,php
- freshrss/cli/i18n/I18nFile.php
- freshrss/cli/i18n/I18nData.php

**Comment by Alkarex** [comment]
Sounds good. It could be that the database was read-only.
The files you have found that differs are not used at runtime and therefore should have no effect in your case.
Is everything working for you know, then?

**Comment by ParoTheParrot** [comment]
> Is everything working for you know, then?

Working - yes (in English). But I still can't change the language on my old installation. During the update something went wrong. The language selector is still empty. That is a little bit annoying.

**Comment by Julkikod** [comment]
Hello, 

first of all, many thanks for this work, it's very cool to see and use what you have done !
It happens the same things to me.
From last version (installed this monday) to 1.11.0 (update yesterday)
=> Today, it's switched from French to English while saving a parameter in display ! Same "nothing-to-choose" in language box.

Did you find something relevant to change/check ?

I workarounded that by going to the "user management" tab and update my password while selecting my preffered language onto the form for create a new user, and it's turn back to French..
Thanks anyway !
Julk

**Comment by Julkikod** [comment]
It seems that the Dilberts plugin block the language to english: 
by de-activate it, I can go back to French.
when i turn it on, and save (button "submit") onto the display tab (where no more language appear) it turn to English.

**Comment by Alkarex** [comment]
@kevinpapst Would you have a change to look at it?
P.S.: My guess is that there is a bug related to `registerTranslates()`

**Comment by kevinpapst** [comment]
I have seen that the plugin stopped working after updating FreshRSS but couldn't find a reason for it (no logs at all). Thats a good hint, let me check ...

**Comment by kevinpapst** [comment]
Sorry guys, I forgot to merge my own PR since December https://github.com/kevinpapst/freshrss-dilbert/pull/1
Dilbert 0.2 is released, it should be shown in your backend once https://github.com/FreshRSS/Extensions/pull/30 is merged. 
That should at least fix the language problem if it came from the call to `handleTranslates()` as @Alkarex suggested

**Comment by Julkikod** [comment]
Work like a charm, many thanks for your quick fix !

**Comment by Alkarex** [comment]
The initial problem was the consequence of a 1) bug in an extension (fixed in https://github.com/kevinpapst/freshrss-dilbert/pull/1) and 2) a lack of test in FreshRSS core (fixed in https://github.com/FreshRSS/FreshRSS/pull/1927).
Will be released in FreshRSS 1.11.1.
