### ISSUE TITLE
1.10 displays _ for author in EasyRSS

### ISSUE THREAD

**Issue by Frenzie** [FreshRSS/FreshRSS#1799]
I suspect it was triggered by #1774

# 1.10
![screenshot_20180227-090116](https://user-images.githubusercontent.com/202757/36750090-f1aaff5c-1bfc-11e8-904e-5586ace189bf.png)

# Some older stuff from 1.9 with author
![screenshot_20180227-090139](https://user-images.githubusercontent.com/202757/36750091-f1ca5334-1bfc-11e8-80a5-84276dbb06fb.png)

**Comment by Alkarex** [comment]
Arg. It is not the author information but the feed name, which is missing apparently.

**Comment by Alkarex** [comment]
Patch coming in FreshRSS

**Comment by Alkarex** [comment]
Fixed in https://github.com/FreshRSS/FreshRSS/pull/1800
