### ISSUE TITLE
No more update when upgraded from 1.0.0 from 1.10.0

### ISSUE THREAD

**Issue by koocotte** [FreshRSS/FreshRSS#1803]
I upgraded my FreshRSS from 1.0.0 to 1.10.0; and since that, feed update does not work anymore.
I unzipped it, copy the /data/ directory from 1.0.0 to the 1.10.0 directory and give write access to all /data/.

I run on Debian with 5.6.30-0+deb8u1 with MariaDB 10.1.26-0+deb9u1; the checkInstall page is all green.

Everything look fine and working, I have old entries, except that I do not have any new entry since the upgrade two days ago (I read http://feeds.feedburner.com/lesnumeriques/news which does have many news everyday).

Apache error log is reporting " [:error] [pid XX] [client XX] PHP Notice:  Undefined index: method in /XX/FreshRSS-1.10.0/app/Models/Share.php on line 27"; it is displayed on many web pages when I set 'environment' => 'development'

- Global update on the website => nothing new
- Force update on a single feed => nothing new
- Crontab update is running hourly => nothing new

Many files in the /cache directory are less than an hour old, so I think part of the update is working.

In users/seb/log.txt, I have some old feeds not working as expected (404...) and an error:
[error] --- SQL error cleanOldEntries: Unknown column 'lastSeen' in 'where clause'

log/cron.log (output of the cron job) report no error:
```
Starting feed actualization at 2018-02-28T14:33:01+01:00
Actualize seb...
Done.
Ending feed actualization at 2018-02-28T14:33:01+01:00
Feed actualizations took 0 day(s), 0 hour(s),  0 minute(s) and 0 seconds for 1 users
Results: 
seb OK
End.
```

**Comment by Alkarex** [comment]
Hello,
It is a big jump from 1.0.0 to 1.10.0, but that should work.

For the warnings regarding *Shares*, please use the current version of `./data/shares.php`, and not the old one.

Could you please try this patch? https://github.com/FreshRSS/FreshRSS/pull/1804

After that, can you see anything else in your FreshRSS logs? I am especially interested in any error code for database errors. I have not tested much with MariaDB, and it could be that there are some subtle differences with MySQL. If we find any, we will fix :-)

In last resort, it will be possible to make a manual check and update of the database.

**Comment by koocotte** [comment]
> It is a big jump from 1.0.0 to 1.10.0

Yes. FreshRSS was working very well, but I was afraid about PHP7 compatibility and I will upgrade in a few days.

Using the last version of data/shares.php resolve errors in Apache log files. I also applied #1804 but can't see any difference about update.

**Comment by marienfressinaud** [comment]
It seems related to https://github.com/FreshRSS/FreshRSS/issues/1595, isn't it?

**Comment by koocotte** [comment]
It looks like. Sorry I did not find it while searching for similar issues.

I seen many differences, but most of them are probably harmless, varchar size, collate and charset.

Really strange: in my "freshrss_seb_entry" table, I have a "hash" column but no "lastSeen". The hash column have probably been added, it's the last column of the table and it's tagged v1.1.1 in the source code.

The "freshrss_seb_entrytmp" table have been created, its tagget v1.7 in the source code, and it's the only table with a utf8mb4 charset.

Digging in the user logs I found:
```
[Mon, 26 Feb 2018 13:23:20 +0100] [warning] --- FreshRSS_EntryDAO::addColumn: hash
[Mon, 26 Feb 2018 13:23:23 +0100] [warning] --- SQL CREATE TABLE entrytmp...
[Mon, 26 Feb 2018 13:23:38 +0100] [error] --- SQL error cleanOldEntries: Unknown column 'lastSeen' in 'where clause'
...
```

The #1804 patch looks bad, I found the following error in the cron.log

```
Starting feed actualization at 2018-03-01T13:33:02+01:00
Actualize seb...
PHP Fatal error:  Call to undefined method FreshRSS_FeedDAO::autoUpdateDb() in /home/web/freshrss/FreshRSS-1.10.0/app/Models/FeedDAO.php on line 375
Results:
```

**Comment by Alkarex** [comment]
@koocotte I have updated https://github.com/FreshRSS/FreshRSS/pull/1804
Could you please give it another try?

**Comment by koocotte** [comment]
Another error 

`PHP Fatal error:  Call to protected method FreshRSS_EntryDAO::autoUpdateDb() from context 'FreshRSS_FeedDAO' in /home/web/freshrss/FreshRSS-1.10.0/app/Models/FeedDAO.php on line 376`

**Comment by Alkarex** [comment]
Arg, damn! New patch on its way

**Comment by Alkarex** [comment]
@koocotte New version https://github.com/FreshRSS/FreshRSS/pull/1804
I will first be able to test this evening, but it would help if you could give it a try already :-)

**Comment by koocotte** [comment]
Ok, it's working now. The missing column have been added and new items are displayed.

Thanks.

**Comment by Alkarex** [comment]
Great. Was the missing column added by the patch, or did you do a manual fix?

**Comment by koocotte** [comment]
Fixed by the patch.
