### ISSUE TITLE
Actualize_script won't start

### ISSUE THREAD

**Issue by atengesdal** [FreshRSS/FreshRSS#1806]
Hi, 

when running the script it does not work. Any tips would be great.

php /usr/share/FreshRSS/app/actualize_script.php 
Starting feed actualization at 2018-03-02T18:10:52+01:00
FreshRSS install failed requirements:
• data
• cache
• users
• favicons
• ok

Results: 
arve@lubuntu:~$ 

The FreeRSS is working fine otherwise.

**Comment by Alkarex** [comment]
Hello,
This is probably because you are running that script from a user, which does not write permission to these directories.
Try to run it instead with the same user as your Web server (often `www-data`) like in our example https://github.com/FreshRSS/FreshRSS#example-on-debian--ubuntu

**Comment by atengesdal** [comment]
Hello, how do I do that? Reason being is that I made a crontab entry but the feeds are not updating so I am sure I messed up somewhere… I know I made it for my own user and not for the www-data user, which I didn’t even realise was a separate user….

The example is missing a few steps to be honest, ie how to make that crontab entry for the right user. Please can you assist in what to do?

**Comment by atengesdal** [comment]
Update, I ran this from cli;
sudo -u www-data php /usr/share/FreshRSS/app/actualize_script.php 
and I got this reply

arve@lubuntu:~$ sudo -u www-data php /usr/share/FreshRSS/app/actualize_script.php 
Starting feed actualization at 2018-03-02T19:29:27+01:00
Actualize arve...
Actualize selam...
Actualize hyl...
Done.
Ending feed actualization at 2018-03-02T19:29:34+01:00
Feed actualizations took 0 day(s), 0 hour(s),  0 minute(s) and 7 seconds for 3 users
Results: 
arve OK
selam OK
hyl OK
End.

So the script is working! Now the problem is how do I make that crontab entry which I now realise I made for my own user and not for the www-data user :-) 
I would like it to run an update every 30 minutes on all categories that I have

**Comment by Alkarex** [comment]
What platform are you using?

**Comment by atengesdal** [comment]
Ubuntu 17.04

**Comment by Alkarex** [comment]
Then it is easy, as it is exactly the example of https://github.com/FreshRSS/FreshRSS#example-on-debian--ubuntu :-)

Create `/etc/cron.d/FreshRSS` (for instance by typing `sudo nano /etc/cron.d/FreshRSS`) with the following content:

```
6,36 * * * * www-data php -f /usr/share/FreshRSS/app/actualize_script.php > /tmp/FreshRSS.log 2>&1
```

**Comment by atengesdal** [comment]
Done! I thought the first asterisk in the crontab represented minutes, as in second meant hour and so and so on, so what does 6,36 mean?

**Comment by Alkarex** [comment]
Every hour at xx:06 and xx:36. Ideally, people should use different, random values, to avoid everybody querying some Web sites at the same time.

**Comment by Alkarex** [comment]
I am not sure, but you may have to restart your cron demon:
```sh
sudo service cron restart
```

**Comment by atengesdal** [comment]
No need, it was updating as it should. However I did it anyway as a restart wouldn’t hurt 💪

Rgds

Arve Tengesdal
arveteng@gmail.com
Ph: +4791658910

**Comment by atengesdal** [comment]
Hello, no I would like to open this again. My understanding was that this script would update all RSS feeds for me? The script does run, however it is not updating at all, I am not sure what it does I do have to manually update by pressing the circle with the arrow on it. I waited 2 hours (means the script had already run 4 times before as it is set to 30 minutes) and no updates. How is it supposed to work?

**Comment by Alkarex** [comment]
Please check the output of your cron (in `/tmp/FreshRSS.log` if you used the same as my example above).
If you have not already done so, please verify the path of your PHP file (was `/usr/share/FreshRSS/app/actualize_script.php` in my example, but might be different in your case).
The cron will only update the feeds that need to be updated, according to their refresh policies defined in the feeds settings in FreshRSS, so not necessarily all of them every time.

**Comment by atengesdal** [comment]
Good morning,
I checked the FreshRSS site this morning and can confirm no updates at all. 
Log output:
arve@lubuntu:~$ sudo -u www-data more /tmp/FreshRSS.log 
[sudo] password for arve: 
/bin/sh: 1: www-data: not found

Location is in the same path as yours.

arve@lubuntu:/usr/share/FreshRSS/app$ pwd
/usr/share/FreshRSS/app
arve@lubuntu:/usr/share/FreshRSS/app$ ls
Controllers  FreshRSS.php  SQL                   i18n        install.php  views
Exceptions   Models        actualize_script.php  index.html  layout

Next step?

**Comment by atengesdal** [comment]
Due to the "not found" above I started to wonder if I actually have the www-data user present, but it is here.
arve@lubuntu:/usr/share/FreshRSS/app$ compgen -u
root
daemon
bin
sys
sync
games
man
lp
mail
news
uucp
proxy
www-data
...and so on

**Comment by Alkarex** [comment]
What Web server are you using?

Please show the output of the following commands:
```sh
php -v
ls -alh /etc/cron.d/F*
cat /etc/cron.d/FreshRSS
ls -alh /tmp/F*
cat /tmp/FreshRSS.log
ls -alh /usr/share/FreshRSS/
```

**Comment by atengesdal** [comment]
arve@lubuntu:~$ apache2 -v
Server version: Apache/2.4.27 (Ubuntu)
Server built:   2017-09-18T15:05:48

arve@lubuntu:~$ php -v
PHP 7.1.11-0ubuntu0.17.10.1 (cli) (built: Nov  1 2017 16:30:52) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.11-0ubuntu0.17.10.1, Copyright (c) 1999-2017, by Zend Technologies

arve@lubuntu:~$ ls -alh /etc/cron.d/F*
-rw-r--r-- 1 root root 97 Mar  2 19:38 /etc/cron.d/FreshRSS
arve@lubuntu:~$ cat /etc/cron.d/FreshRSS
30 * * * * www-data php -f /usr/share/FreshRSS/app/actualize_script.php > /tmp/FreshRSS.log 2>&1
arve@lubuntu:~$ ls -alh /tmp/F*
-rw-rw-r-- 1 arve arve 32 Mar  2 17:36 /tmp/FreshRSS.log
arve@lubuntu:~$ cat /tmp/FreshRSS.log 
/bin/sh: 1: www-data: not found
arve@lubuntu:~$ ls -alh /usr/share/FreshRSS/
total 220K
drwxrwxr-x  11 root www-data 4.0K Feb 28 19:33 .
drwxr-xr-x 316 root root      12K Mar  2 19:11 ..
-rw-rw-r--   1 root www-data  525 Feb 28 19:33 .editorconfig
drwxrwxr-x   8 root www-data 4.0K Mar  1 17:01 .git
-rw-rw-r--   1 root www-data  112 Feb 28 19:33 .gitignore
-rw-rw-r--   1 root www-data  958 Feb 28 19:33 .travis.yml
-rw-rw-r--   1 root www-data  47K Feb 28 19:33 CHANGELOG.md
-rw-rw-r--   1 root www-data 3.4K Feb 28 19:33 CONTRIBUTING.md
-rw-rw-r--   1 root www-data 7.3K Feb 28 19:33 CREDITS.md
-rwxrwxr-x   1 root www-data  34K Feb 28 19:33 LICENSE.txt
-rw-rw-r--   1 root www-data  11K Feb 28 19:33 README.fr.md
-rw-rw-r--   1 root www-data  11K Feb 28 19:33 README.md
drwxrwxr-x   9 root www-data 4.0K Feb 28 19:33 app
drwxrwxr-x   3 root www-data 4.0K Feb 28 19:33 cli
-rw-rw-r--   1 root www-data 2.1K Feb 28 19:33 config-user.default.php
-rw-rw-r--   1 root www-data 4.6K Feb 28 19:33 config.default.php
-rw-rw-r--   1 root www-data 1.8K Feb 28 19:33 constants.php
drwxrwxr-x   8 root www-data 4.0K Mar  1 17:59 data
drwxrwxr-x   7 root www-data 4.0K Feb 28 19:33 docs
drwxrwxr-x  16 root www-data 4.0K Mar  2 18:01 extensions
-rw-rw-r--   1 root www-data  239 Feb 28 19:33 force-https.default.txt
-rw-rw-r--   1 root www-data  308 Feb 28 19:33 index.html
-rw-rw-r--   1 root www-data   64 Feb 28 19:33 index.php
drwxrwxr-x   4 root www-data 4.0K Feb 28 19:33 lib
drwxrwxr-x   6 root www-data 4.0K Feb 28 19:33 p
-rw-rw-r--   1 root www-data 4.7K Feb 28 19:33 phpcs.xml
drwxrwxr-x   3 root www-data 4.0K Feb 28 19:33 tests

**Comment by Alkarex** [comment]
1) Be sure not to have left anything in your user's crontab, otherwise you may see the output of the wrong cron job.
In `/etc/cron.d/FreshRSS`, try to change the path to `/tmp/FreshRSS2.log` to be sure you are not looking at an output produced by one of your earlier attempts.

2) Using `30` in your cron will run once per hour, every xx:30.
Besides that, the syntax looks OK, but maybe you had a bad syntax before, so try to restart your cron service once more.

**Comment by atengesdal** [comment]
Done, I changed path to FreshRSS2.log. Also changed time pattern to 6,36 :-) 
restarted service, lets see.

**Comment by atengesdal** [comment]
Something happened now, 

arve@lubuntu:~$ tail -f /tmp/FreshRSS2.log 
Starting feed actualization at 2018-03-03T12:06:01+01:00
Actualize arve...
Actualize hyl...
Actualize selam...
Done.
Ending feed actualization at 2018-03-03T12:06:30+01:00
Feed actualizations took 0 day(s), 0 hour(s),  0 minute(s) and 29 seconds for 3 users
Results: 
arve OK
hyl OK
selam OK
End.


Not sure what did the trick here? Hope it stays like this now :)
