### ISSUE TITLE
Can't login after upgrade to 1.10.0

### ISSUE THREAD

**Issue by bastien30** [FreshRSS/FreshRSS#1807]
Hello, 

Since the 1.10.0 upgrade I can't login anymore to my FreshRSS instance (using classic javascript authentication).
No error displayed when I'm trying to login, the browser just redirecting to the login page. 

From version 1.9.0, I've tested upgrading via web interface and manually by replacing files (except the data directory), same result.

When I upgrade via web interface, I end up on a 403 Forbidden error, with this line in Apache error_log file : `PHP Strict Standards: Only variables should be passed by reference in /var/www/freshrss/data/update.php on line 156`

I've tried `chmod -R 777` on the FreshRSS directory, before and after upgrade, same result, so it doesn't seems to be a permissions problem.

I've tried to reset the password as described in #1779 but that didn't work either.

I can access my FreshRSS instance only with "auth_type" set to "none" on data/config.php.

I've nothing in Apache error_log, and nothing on FreeshRSS logs, even with "environment" set to "development" on data/config.php (maybe I've done it wrong ?). 

My server run CentOS 6.9 with Apache 2.2.15 and PHP 5.6.33 (remi-php56 repo).

Thanks in advance.

**Comment by Alkarex** [comment]
The manual update (replacing the files) should have worked, at least (we need to rework the auto-update mechanism). Where you using version 1.9.0 before?
Could I by any chance get a temporary SSH login to the server/user? (no problem if it is not possible)
After setting your `auth_type` to `none`, did you try to set your password again and change the login method back from FreshRSS Web interface?
Did you check whether you have any error message in your browser JavaScript console?
What database are you using?

**Comment by bastien30** [comment]
Thanks for the quick answer !

I've found the problem, it's Apache digest authentication in front of FreshRSS.
In my vhost I have :

```
<Directory /var/www/freshrss/p>
  ...
  AuthType             Digest
  AuthName             "Secure Area"
  AuthDigestProvider   file
  AuthUserFile         "/etc/httpd/conf/.auth"
  Require user         admin
</Directory>
```
If I comment out theses lines, I can connect to FreshRSS.

**Comment by Alkarex** [comment]
Ok :-) You can also use the HTTP login method, if you want (the username needs to be the same than an existing FreshRSS user).

**Comment by bastien30** [comment]
I'm using FreshRSS since a long time with this configuration, without problem.
So maybe there is a bug in the v1.10.0 that cause this behaviour ?

I would really prefer two level authentication, if possible (mainly for pratical reasons, I confess :p)

Thanks

**Comment by Alkarex** [comment]
The only relevant change I can think of in FreshRSS 1.10.0 is https://github.com/FreshRSS/FreshRSS/pull/1756
Could you try to comment out this line https://github.com/FreshRSS/FreshRSS/blob/ebe7be4e6b41a115688bc52350470e7f64f949f7/app/Models/Auth.php#L18 ?

**Comment by bastien30** [comment]
Yeah, that's right, commenting that line solves the problem :+1:

**Comment by Alkarex** [comment]
Could you please try the following patch https://github.com/FreshRSS/FreshRSS/pull/1809
(Commenting the line above is not a good solution, it was just to see where the problem was coming from)

**Comment by bastien30** [comment]
Thanks, it works after applying the patch !

**Comment by Alkarex** [comment]
Thanks for testing :-)
FreshRSS 1.10.1 containing this patch will be released during the week-end.

**Comment by bastien30** [comment]
Thanks to you for your reactivity :smiley:
