### ISSUE TITLE
[Feature Request] Allow to ignore SSL certificate errors on a feed

### ISSUE THREAD

**Issue by perrinjerome** [FreshRSS/FreshRSS#1811]
Some feeds are hosted on servers with invalid SSL certificates, it would be nice to be able to configure in the feed parameters that problems with SSL certificate while updating the feed can be ignored.

**Comment by Alkarex** [comment]
Usecase for https://github.com/FreshRSS/FreshRSS/pull/1838

**Comment by papaxris** [comment]
This SSL certificate ignore feature seems to be working.  I consistently had issues with a particular feed because of their invalid certificate.  This has allowed the feed to populate within the FreshRSS feeds.

Logging the SSL issue is still maintained and is not simply ignored (thank you).
