### ISSUE TITLE
Only one element displayed on article view since update

### ISSUE THREAD

**Issue by Ramzus** [FreshRSS/FreshRSS#1824]
I've updated my installation of FreshRSS to 1.10.1 and I've got a problem now with the article view : it's only display one article.

![image](https://user-images.githubusercontent.com/2848257/37036047-c74c3792-214e-11e8-9238-a866b7df5f79.png)

I don't see any issues on this bug (maybe it's cause by something on my installation).
I try to desactivate all the extensions that I have install with no luck.

Any ideas on what to look to identify the problem ?

**Comment by Frenzie** [comment]
Judging by your screenshot, do you mean normal view?

https://github.com/FreshRSS/FreshRSS/blob/5ebeb9e3e5d46195a83211140c1d28d58be19b2a/app/i18n/fr/index.php#L45

**Comment by aledeg** [comment]
Can you see your articles when you select a category or a feed?

**Comment by Ramzus** [comment]
@Frenzie yes, sorry, I mean the normal_view.
@aledeg yes, I see all the articles in the reader view and rss flux output.
![image](https://user-images.githubusercontent.com/2848257/37039026-b7cdc9ea-2156-11e8-93db-9cdea26c22fb.png)

In global view, I see the number of articles by category but when I click on a category, I also only see one article.

**Comment by Ramzus** [comment]
I've tried to modify settings but no luck
![image](https://user-images.githubusercontent.com/2848257/37039207-2bffc6ce-2157-11e8-8886-cf9375f3b74d.png)

**Comment by aledeg** [comment]
I think that it's just a feed config. If you check you feed configuration, the visibility must be ```Visible in its category```. Change that value to ```Show in main stream``` and you should be good.

I am talking about this feed parameter:
![visibility](https://user-images.githubusercontent.com/3056148/37039396-aa984bd2-2157-11e8-88fe-24591cd6bcc7.png)

**Comment by Ramzus** [comment]
I've just checked my principal feeds and visibility is already correct : 
![image](https://user-images.githubusercontent.com/2848257/37041149-c82adddc-215b-11e8-8ed9-d5b5311a7bca.png)

It's really strange as only the most recent article from my news feeds are displayed.

**Comment by Ramzus** [comment]
Find out the problem : in my previous installation, I tried to add a custom share that never worked. Delete this incorrect sharing parameter correct my problem.

Thanks for your help !
