### ISSUE TITLE
Log in gets an error: Permission is denied for log.txt

### ISSUE THREAD

**Issue by BarbarianSSJ** [FreshRSS/FreshRSS#1825]
After trying to log in to my server, i get the message: 
### Application problem ###
Permission is denied for `<<<path>>>/data/users/<USER>/log.txt`

I can log in when doing it from a saved session i have on other web browser and i can't update to the latest version.

**Comment by Alkarex** [comment]
Try to reset the access rights properly, so that `./data/` is writable by your Web server.

For instance (to be adapted to your own case):
```sh
cd ./FreshRSS/
sudo chown -R :www-data . && sudo chmod -R g+r . && sudo chmod -R g+w ./data/
```

**Comment by BarbarianSSJ** [comment]
Thanks! i fixed the .htacces in /data/ to allow all conections and it worked. 

But i can0t update still. i get this text: 

`Ok! FreshRSS will now be updated to the version unknown. `
When i click the button to update, the page goes blank

**Comment by Alkarex** [comment]
The `.htaccess` is not be related to your first problem.
Just upload a new version manually if the auto update does not work.
