### ISSUE TITLE
Connection not secure

### ISSUE THREAD

**Issue by mbnoimi** [FreshRSS/FreshRSS#1826]
Hi, 

When ever I browse https://mydomain/FreshRSS/p/i/ I get a warning message from the browser (Firefox & Chrome) says:
```
Connection is Not Secured
Parts of this page are not secure (such as images).
```
While in case I browse configurations pages ex. https://mydomain/FreshRSS/p/i/?c=configure&a=reading I don't see this error!

How can I fix this issue?!

**Comment by aledeg** [comment]
Probably because some of the articles you're reading embed images or other resources served in http.

**Comment by Alkarex** [comment]
Indeed, it is most likely images or embedded objects coming from other non-HTTPS domains.
In case of domains providing both HTTP and HTTPS, it is possible to force HTTPS in FreshRSS, by creating a file `./data/force-https.txt` using the same model than https://github.com/FreshRSS/FreshRSS/blob/master/force-https.default.txt

**Comment by Frenzie** [comment]
And of course I also wrote this extension to help view the images. ;)

https://github.com/FreshRSS/Extensions/tree/master/xExtension-ImageProxy

**Comment by Frenzie** [comment]
I'll close this now, since there isn't really much that can be done about it besides the two messages above.
