### ISSUE TITLE
Install on SELinux enabled system

### ISSUE THREAD

**Issue by renzo38** [FreshRSS/FreshRSS#1835]
Hello,

I followed the installation steps and I found that on SELinux enabled system the following commands are mandatory:

-  semanage fcontext -a -t httpd_sys_rw_content_t '/usr/share/FreshRSS/data
- semanage fcontext -a -t httpd_sys_rw_content_t '/usr/share/FreshRSS/data/cache'
- semanage fcontext -a -t httpd_sys_rw_content_t '/usr/share/FreshRSS/data/users'
- semanage fcontext -a -t httpd_sys_rw_content_t '/usr/share/FreshRSS/data/favicons'

and **restorecon -Rv /usr/share/FreshRSS/data**

If not, the installation step 2 cannot be validated.

Hope this will help.

**Comment by aledeg** [comment]
Thank you for your help. It is useful to have such information.
I've never used SELinux, so I don't know what those commands do, if I need to run them as root. Do you mind adding a bit more details?

**Comment by renzo38** [comment]
On systems like RHEL / Fedora SELinux acts like an 'application firewall'. For example, the command (running as **root**)

`semanage fcontext -a -t httpd_sys_rw_content_t '/usr/share/FreshRSS/data`

give to the processes httpd the rw right on /usr/share/FreshRSS/data

and the command

`restorecon -Rv /usr/share/FreshRSS/data`

apply pending changes on directory /usr/share/FreshRSS/data

When using Apache, the following 'context' can be modify:
- **httpd_sys_content_t** : Read-only directories and files used by Apache
- **httpd_sys_rw_content_t** : Readable and writable directories and files used by Apache. Assign this to directories where files can be created or modified by your application, or assign it to files directory to allow your application to modify them.
- **httpd_log_t** : Used by Apache to generate and append to web application log files
- **httpd_cache_t** : Assign to a directory used by Apache for caching, if you are using mod_cache

These contexts are created/set by defaults and it is necessary to execute the previous command when adding a new site/webapp/...

**Comment by Alkarex** [comment]
@renzo38 I guess the instructions can be simplified to the following, don't you think?
```sh
semanage fcontext -a -t httpd_sys_rw_content_t '/usr/share/FreshRSS/data(/.*)?'
restorecon -Rv /usr/share/FreshRSS/data
```

**Comment by aledeg** [comment]
@renzo38  Maybe you could add something in the FAQ

**Comment by renzo38** [comment]
Ok, I will do it. I prefer to give the 'rights' httpd_sys_rw_content_t on the concerned directories and not to all data/* ? What do you think about it ?

**Comment by Alkarex** [comment]
@renzo38 The whole `./data/` should be writeable. For instance, `./data/PubSubHubbub/` was forgotten.

**Comment by Alkarex** [comment]
Done in https://github.com/FreshRSS/FreshRSS/pull/1837
