### ISSUE TITLE
[Feature Request] Preview for CSS path fetching

### ISSUE THREAD

**Issue by simonszu** [FreshRSS/FreshRSS#1839]
Although I know the technical background of CSS path fetching, I have some difficulties of setting it up. Currently it is some kind of trial-and-error, where the error only occurs when the feed has new contents.

For that, I want to suggest a feature where you can get a preview of the content freshrss would fetch from the page, maybe as a button next to the CSS path input textbox, which would open a new page with the content of the newest feed item parsed with the CSS path extractor, so that you can tweak the path in short time.

**Comment by Frenzie** [comment]
Could be useful indeed, but what part is it concretely that's error prone? With right click, inspect element, add new rule:

```css
my custom selector {border:5px solid red}
```

It's pretty quick to see what's going on.

**Comment by simonszu** [comment]
I was pretty sure selecting the right content, firebug does exactly this coloring automatically. However, all that freshrss is displaying is the headline, which is part of the original feed, I think. I am trying since Saturday morning, now it's Monday evening and for my own sanity I am thinking about just living with a shortened feed.

I was using miniflux before, which applied some magic on its own to download the full page, but it lacked a decent mobile app, so I switched.

**Comment by Frenzie** [comment]
Firebug shows you which element you're hovering, but it doesn't quite tell you which elements are matched by a certain selector. I can't immediately find what that `$doc->find` does, but if it only returns the first match, for example, you'd want to be more specific. Pinging @Alkarex on that.

https://github.com/FreshRSS/FreshRSS/blob/60f56539c3f30fd3f7ba4f2a3570f7029ac93e5f/app/Models/Entry.php#L182-L204

https://github.com/FreshRSS/FreshRSS/blob/5ebeb9e3e5d46195a83211140c1d28d58be19b2a/lib/lib_rss.php#L248-L271

**Comment by Offerel** [comment]
It would be a amazing feature, to have a preview of what is extracted. So far I could get the correct full content from a handful of shortened feeds. However, I always get only the shortened version from one source, no matter what I do. I try to get the full content of http://www.areamobile.de/svc/xml/news.rss and use `div#ContentLeft article div.docNews`. But all what i get is the shortened feed.

**Comment by Frenzie** [comment]
Why so specific? It looks like just `article` (or `.artikel`) should do the trick? 

That's just a generic comment btw. It looks to me like your selector should work. I just think it seems overcomplicated for its purpose.

**Comment by Offerel** [comment]
I have tried your examples before but had no luck with that page. I have no idea whats the problem. Im really sure, that the path is correct. Maybe the side prevents such requests or it can something block requests... i have no idea. Currently im testing fivefilters solution. They get the feed extracted. It's the only one which makes trouble for me.

**Comment by Frenzie** [comment]
Probably a bug of some sort in the page itself.

**Comment by math-GH** [comment]
There is already a preview
![grafik](https://user-images.githubusercontent.com/1645099/147282480-1b146113-7b5f-4a75-8d4f-e33a4e0e2ac1.png)

@Offerel : is it solved for you?

**Comment by Frenzie** [comment]
Indeed, the issue predates that. Implemented in #2778.

**Comment by Offerel** [comment]
Ohh, i havent checked this function since some time, but indeed. Its solved for me. Works realy good now.
