### ISSUE TITLE
A muted feed gets updated via CLI

### ISSUE THREAD

**Issue by sjeon87** [FreshRSS/FreshRSS#1844]
Could someone please confirm that a muted feed (with a muted speaker icon) gets updated via `cli/actualize-user.php`?

In my case, version `1.9.1-dev` (e70d441), this happens. I am not sure whether this happens when actualizing feeds via web interface.

**Comment by Alkarex** [comment]
The same logic is called from manual (Web) refresh, cron refresh, and CLI. If there is a problem with a feed being actualized when it should not, then there is probably the same problem for all three actualization methods.

I will try to see if I can reproduce the problem.

**Comment by Alkarex** [comment]
Indeed, I can confirm that there is a bug.

**Comment by Alkarex** [comment]
Could you please give a try to https://github.com/FreshRSS/FreshRSS/pull/1845 if you can ?

**Comment by Alkarex** [comment]
@aledeg In addition, we should either remove the refresh menu for muted feeds, or allow manual refresh of muted feeds

**Comment by aledeg** [comment]
@gsongsong good catch. It appears I didn't tested it thoroughly.

@Alkarex That's could be a good idea.

**Comment by sjeon87** [comment]
Checked that the fix works via web interface. Thanks.

(Didn't check whether it wotks in case of manually actualizing a single muted feed)
