### ISSUE TITLE
unknown error for planet-libre feed

### ISSUE THREAD

**Issue by pled** [FreshRSS/FreshRSS#1846]
Hello,
I get this : Unknown error for feed [http://www.planet-libre.org/feed.php?type=rss]
while it looks good checking on https://validator.w3.org/feed .
I am running FreshRSS v1.10.2

**Comment by Frenzie** [comment]
Sorry, I can't reproduce. Maybe just a temporary server hiccup of some sort? :-)

![screenshot_2018-03-26_18-39-16](https://user-images.githubusercontent.com/202757/37919734-0b9f14e2-3125-11e8-92c3-9c9930b9deba.png)

**Comment by Alkarex** [comment]
I myself follow `http://www.planet-libre.org/feed.php?type=atom`, and there is oftentimes some delays and other problems. You can try to increase your timeout in `./data/config.php` (on the model of `./config.default.php`).

I do not think there is anything wrong on FreshRSS side.

Even with 15 seconds, I often have some errors:

```
data/users/alex/log.txt:[Sat, 24 Mar 2018 22:32:57 +0100] [warning] --- cURL error 28: Operation timed out after 15000 milliseconds with 0 bytes received [http://www.planet-libre.org/feed.php?type=atom]
data/users/alex/log.txt:[Sun, 25 Mar 2018 05:33:17 +0200] [warning] --- cURL error 28: Operation timed out after 15000 milliseconds with 0 bytes received [http://www.planet-libre.org/feed.php?type=atom]
data/users/alex/log.txt:[Sun, 25 Mar 2018 06:32:51 +0200] [warning] --- cURL error 28: Connection timed out after 15000 milliseconds [http://www.planet-libre.org/feed.php?type=atom]
data/users/alex/log.txt:[Sun, 25 Mar 2018 07:32:58 +0200] [warning] --- cURL error 28: Connection timed out after 15000 milliseconds [http://www.planet-libre.org/feed.php?type=atom]
```
