### ISSUE TITLE
refresh PubSubHubbub?

### ISSUE THREAD

**Issue by stephenjamieson** [FreshRSS/FreshRSS#1855]
I had an invalid base_url and now I would like my feeds to try and resubscribe.  Is there a way to do this?

**Comment by Alkarex** [comment]
Seems to be related to https://github.com/FreshRSS/FreshRSS/issues/1854

This should be done automatically, but takes a bit of time: FreshRSS waits 23 hours before trying to resubscribe to a feed's PubSubHubbub after an error. This is to limit the number of errors. Resubscription is done during a feed refresh.

If for some reason this is not sufficient, you can try to force the system by deleting the content of `./data/PubSubHubbub/feeds/*/*` and `./data/PubSubHubbub/keys/*.txt`. (Be sure to keep the folders `./data/PubSubHubbub/feeds/` and `./data/PubSubHubbub/keys/` )

**Comment by stephenjamieson** [comment]
Got it, thank you for the information, as long as it will eventually refresh I'm happy.

**Comment by Alkarex** [comment]
Please confirm that it works when you can :-)

**Comment by stephenjamieson** [comment]
👍 worked great, already subscribing after clearing out the keys and feeds dirs
