### ISSUE TITLE
Read articles are marked as unread after the update

### ISSUE THREAD

**Issue by Trapton** [FreshRSS/FreshRSS#1859]
I've be new with FreshRSS and have problems with the following blog:
https://factorio.com/blog/

I marked all articles as read, but after the next update, all articles are marked as unread over and over again. In my other RSS setup (TT-RSS), I dont have problems with it.
Some other sites working fine, but I'm still in the testing phase.

My setup:

Windows Server 2016
IIS 10 with PHP-CGI 7.0.29
MySQL 5.7

**Comment by Frenzie** [comment]
I don't see anything obviously suspicious about it. I assume this is with the latest 1.10.2?

**Comment by Trapton** [comment]
Yes, with the lastest version 1.10.2.
I already tried a reinstallation and changed the refreshrate but same story.

Log (Windows Event Log):
php[3104] SimplePie GET https://www.factorio.com/blog/rss
php[3104] SimplePie MD5 cache no match for https://www.factorio.com/blog/rss

But I get the same entry with a working feed.

**Comment by kevinpapst** [comment]
Probably a problem like mine #1840
Sometimes feeds include dynamic/changing content (like advertisements). In that case FreshRSS detects them as changed and marks them as unread. You can re-configure that behavior.

**Comment by Trapton** [comment]
Thanks mate, I think it work now.
The button was too obvious.
