### ISSUE TITLE
Docker auto update feed issue

### ISSUE THREAD

**Issue by hot123s** [FreshRSS/FreshRSS#1860]
Hello

```
php actualize_script.php > /tmp/FreshRSS.log 2>&1
```
I use above command to enable FreshRss auto update start .But it didn't work.

How can I solve it

Thanks!

**Comment by Frenzie** [comment]
What does it say in the log file? For that matter, why are you even using a log file when you are directly interested in the output? :-)

**Comment by Alkarex** [comment]
Hi @hot123s ,
Could you please give a bit more information about your context? What runs in Docker, what runs on the host?
Did you try the following example? https://github.com/FreshRSS/FreshRSS/blob/master/Docker/README.md#cron-job-to-refresh-feeds

E.g.:

```sh
sudo docker exec --user apache -it freshrss php ./app/actualize_script.php
```

**Comment by hot123s** [comment]
@Alkarex 
Thanks,this work well for my fresh rss server
```
docker exec --user apache -it freshrss php ./app/actualize_script.php
```

**Comment by Frenzie** [comment]
Ah yes, always ascertain the basics first. I'd assumed this was within a `docker exec -it container_name bash` (or something along those lines).
