### ISSUE TITLE
iOS?

### ISSUE THREAD

**Issue by rototom** [FreshRSS/FreshRSS#1861]
Its working with easyrss for android, but I need ios support, too.
Any suggestions?

**Comment by kevinpapst** [comment]
I am working on the Fever API which is supported by many iOS clients: #1836
This is not yet finished. If you want to use it right now, there is a splitoff that works with the latest release: https://github.com/kevinpapst/freshrss-fever-api

**Comment by rototom** [comment]
Thank you, I give it a try.
Whenever I want to set an api password, I get Error 403 - Forbidden.

**Comment by rototom** [comment]
Can I update users api password in a config file, also?

**Comment by rototom** [comment]
Problem solved by using chromium.

**Comment by Frenzie** [comment]
That should not be the solution to any problem. Chromium instead of what?

**Comment by rototom** [comment]
Instead of Firefox. To be true, I found this 'solution' here in one issue that I don't find anymore.

**Comment by Alkarex** [comment]
> Problem solved by using chromium.

Seems to be related to https://github.com/FreshRSS/FreshRSS/issues/1841
I will try to have a look.

**Comment by Alkarex** [comment]
Fever API has been implemented in https://github.com/FreshRSS/FreshRSS/pull/1836 and available in the /dev branch of FreshRSS. We are looking for testers, so do not hesitate to go ahead and report your experience.

Tested with:
- iOS
  - [Fiery Feeds](https://itunes.apple.com/app/fiery-feeds-rss-reader/id1158763303)
  - [Unread](https://itunes.apple.com/app/unread-rss-reader/id1252376153)
