### ISSUE TITLE
i18n - German Translation

### ISSUE THREAD

**Issue by thomase1993** [FreshRSS/FreshRSS#1863]
Hi all,
I saw some //TODO in the translation folder. Can I translate them in the master, beta or dev branch? I am an native German speaker and understand also english well enough :-)

**Comment by kevinpapst** [comment]
Hi @thomase1993,
Development happens in the dev branch: https://github.com/FreshRSS/FreshRSS/tree/dev/app/i18n/de
I recently translated the TODOs in the german files, but have a look at them. Maybe I missed some strings ... or you find better translations, which are always welcome!
