### ISSUE TITLE
Completely disable image loading (well, any loading of external resources)

### ISSUE THREAD

**Issue by TheAssassin** [FreshRSS/FreshRSS#1864]
To improve users' privacy, it would be nice if there was an option to entirely disable the loading of any images in FreshRSS, next to the "lazy loading" checkbox.

Often, the images are customized for a specific article. Whenever an entry is opened in FreshRSS, this image is loaded, and since the image is specific for an article and is loaded from the servers of the RSS provider, they can track when and which articles you read. Tracking which articles are read is not possible with a normal RSS feed however, they just know you read their feed, but they can't know which articles are read.

Another issue is that the RSS feed is fetched from `<server IP>`, but the images are loaded with `<user IP>`, which "ruins" that proxy effect the server has here. This can be fixed to some extent with that "image cache" plugin, though.

**Comment by math-GH** [comment]
You can try https://github.com/Victrid/freshrss-image-cache-plugin as extension
