### ISSUE TITLE
cURL error 47: Maximum (5) redirects followed

### ISSUE THREAD

**Issue by Trapton** [FreshRSS/FreshRSS#1866]
I have this error quite often with me in the protocol and in addition, the update of the feed is also partially delayed.

Normally, something like this is written in the log:
SimplePie GET https: //domain.tld/
SimplePie MD5 cache match for https: //domain.tld/

Only with this website it remains with SimplePie GET https: //domain.tld/

It is this feed:
http://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fmspoweruser.com%2Ffeed%2F

**Comment by Alkarex** [comment]
So far, I cannot spot any problem with this feed, and it seems to work fine on my FreshRSS instance.
It seems that their server is supporting HTTP/2.0 (which is good). Maybe there could be a compatibly problem with your server there (just a guess).
Could you tell a bit more about the server on which you run FreshRSS? (OS version, PHP version...)

**Comment by Trapton** [comment]
Microsoft Server 2016
IIS 10 Webserver
PHP 7.0.29 (64-Bit)
MySQL 5.7.21

Edit: I found that PHP 7.0.x don't support HTTP/2.0, so I only need to update the PHP Version for FreshRSS. FreshRSS supports PHP 7.2?

**Comment by Trapton** [comment]
It's the PHP version, with 7.2.4 no problems with HTTP/2.0.
I only using the newer version for the feed update, the update for the website is on my todo, but now it working fine.
Maybe you can write something in the documentation, first implementation was in PHP version 7.1.

**Comment by Alkarex** [comment]
I am glad to hear that it works for you. But the initial bug is still not clear, and therefore I am not sure what should be written in a documentation. Indeed, a client that does not support HTTP/2.0 will get the feed via HTTP/1.1. So there was maybe a bug in PHP 7.1 with cURL on Windows. My own server runs PHP 7.1 on Linux without problem.

**Comment by Frenzie** [comment]
@Trapton No problems with that feed on PHP `7.0.27-0+deb9u1`. But wouldn't protocol details be abstracted away by libCURL in this case?
