### ISSUE TITLE
[Feature Request] Make feed tags visible by default

### ISSUE THREAD

**Issue by cy7yz2rj** [FreshRSS/FreshRSS#1867]
Hello, I'm sorry if this has been brought up before but it didn't come up in any search.

An option for making the feed tags immediately visible in the bottom line or next to the feed author, or perhaps in a new section specifically made for them, would be much appreciated.

Right now it appears they are only displayed in the Related tags drop-down menu, which requires a mouse-click to open.

**Comment by marienfressinaud** [comment]
I think @skypshot is going to implement your suggestion. It would be better indeed to make the tags feature more accessible, but I don't think we need an option: I would simply move the tags from the bottom to the top of the entry (maybe below the "author" section?)

The tags associated to the article can be listed directly, but I would keep the popup to add a new tag to the article. It is mainly just moving some part of the code but it will probably require a bit of JavaScript to add the new tag to the list. Also, maybe the option "Article tags" from the display option can be removed.

**Comment by Skypshot** [comment]
Hello,
I'll start to check for this issue :)

**Comment by Skypshot** [comment]
Yep, i'll focus on this implement. Thanks for your explanations @marienfressinaud :)

**Comment by aledeg** [comment]
@Skypshot Any news on the implementation?
