### ISSUE TITLE
Include cron in the docker image

### ISSUE THREAD

**Issue by kordianbruck** [FreshRSS/FreshRSS#1869]
I would love to suggest to add the cronjob directly to the docker image, instead of relying on the host to run the job.

It could be as easy as adding the following to the `Dockerfile`:
```
COPY root /var/spool/cron/crontabs/root
CMD crond -l 2 -f
```

File `root` would simply contain our usual job:
```
*/5 * * * * php /usr/share/FreshRSS/app/actualize_script.php > /tmp/FreshRSS.log 2>&1
```

I'll happily work on a PR if this resonates well with you guys.

**Comment by Frenzie** [comment]
I don't know if automatically running cronjobs is necessarily desirable. Admittedly, for me the cronjob is probably one of the biggest reasons for running something like FreshRSS in the first place. It also grabs feeds if you don't open your feedreader for a few days. But it might not be benign, or whatever the right word to use is.

Btw, every 5 minutes might be a bit often.

**Comment by Alkarex** [comment]
Hello @kordianbruck and thanks for the proposition.
I am a bit ambivalent, because it is best to have only a single process running per Docker instance.
On the other hand, having a built-in cron would indeed be more convenient.

There is a number of possible variations though. We could for instance have a single image with the cron job ready but not running, making it possible to run the image twice: once for Apache, once for cron thanks to an additional command parameter. I think I would like this approach better.

**Comment by Alkarex** [comment]
Some references https://gist.github.com/andyshinn/3ae01fa13cb64c9d36e7

**Comment by kordianbruck** [comment]
@Frenzie we are only talking about the docker image here. If you have any arguments against having it in there from the start, please add them. I can only see arguments for bundling the cronjob with alpine.

@Alkarex Yes, absolutely - separation of concerns is certainly a good thing to have. I think in this case it is more a shortcoming of php that does not allow for reoccurring tasks.

A second image would be less desiderable(as in double the space required + need to update both images), but I would love to instead have a ENV variable one can easily pass in from the docker command/kubernetes deployment to enable the cron daemon.

Alternatively we could have two versions of the image: one with cron enable and one without. 

Adding a cronjob externally on my kubernetes cluster is unfortunately not an option, as the cluster might reassign the pod/deployment to another machine inside the cluster.

**Comment by Alkarex** [comment]
I will try to prepare a PR, which should satisfy the different aspects of what we discussed.
* Parameter to control the cron frequency
* Parameter to start the cron process or not
* Possibility of running only the cron process

@Frenzie I meant a single process (not only logical). While not mandatory of course, it is more robust and makes it easier to work with e.g. auto-restart (in case of crash), logs, scaling, etc.

**Comment by Alkarex** [comment]
@kordianbruck Please test https://github.com/FreshRSS/FreshRSS/pull/1871 if you can. Feedback appreciated

**Comment by Alkarex** [comment]
Merged in /dev. Tests welcome
