### ISSUE TITLE
Css Selector HTML tag section

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#1870]
Hello, 

I am trying to figure out how retrieve the full article by using the CSS selector for this feed
https://anotherwhiskyformisterbukowski.com/feed/

it appears that the content is enclosed there
{section class="single-article__content"}

but I've tried with 
.single-article__content
section.single-article__content

and it does not works. Is there any tools that I can use or cli command to test ?
Thanks.

**Comment by ghost** [comment]
thanks I will try with .single-article, but I don't understand why because the classname is .single-article__content

**Comment by Frenzie** [comment]
The other two I mentioned are not equivalent but the parent. If you want `.single-article__content` you should use it. ;-)

**Comment by ghost** [comment]
It does not work (.single-article__content or single-article), I'm still getting the truncated article.

**Comment by Alkarex** [comment]
Merged in the /dev branch. Tests very much welcome.
