### ISSUE TITLE
Cannot add feed the-curious-button.com

### ISSUE THREAD

**Issue by nikaro** [FreshRSS/FreshRSS#1872]
Here is the URL: https://the-curious-button.com/feed/
It seems to be valid: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fthe-curious-button.com%2Ffeed%2F

Here are the logs i have:
```
2018-04-25 17:41:04Unknown error for feed [https://the-curious-button.com/feed/]
2018-04-25 17:38:36A feed could not be found at `https://the-curious-button.com/feed/`; the status code is `200` and content-type is `text/html` [https://the-curious-button.com/feed/]
```

Is there a workaround for that?

**Comment by nikaro** [comment]
Same for https://traceydockree.com/feed/

**Comment by nikaro** [comment]
I re-tried this morning and it still does not work :-/

May be it because i am on a shared hosting (OVH Kimsufi Web) and the connection/performance is too low. Is there somewhere where i can change the timeout?

**Comment by Alkarex** [comment]
Both feeds works fin for me (OVH Kimsufi dedicated server).
For the first one, it does not seem to be a timeout issue, and you seem to get a response (HTML and not RSS though).
Do you have access to SSH? Could you try:

```sh
curl 'https://the-curious-button.com/feed/'
```

**Comment by Alkarex** [comment]
For the record, increasing the timeout can be made in in `./FreshRSS/data/config.php` (see limits / timeout).

**Comment by Vincent14** [comment]
Could it be from the latest release? I also have problems in adding feeds, like this one https://pivotce.com/tag/luneos/feed/ W3C valid as seen from here https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fpivotce.com%2Ftag%2Fluneos%2Ffeed%2F

**Comment by Frenzie** [comment]
@Vincent14 That feed works fine for me on 10.0.1.

**Comment by nikaro** [comment]
Hello, i cannot try cURL, it's a web hosting, not a dedicated server.

But i just tried to increase timeout from 15 to 30, and it seems to work.

Thanks you.

**Comment by Vincent14** [comment]
Something like:

`$ curl https://pivotce.com/tag/luneos/feed/`

```
<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	xmlns:slash="http://purl.org/rss/1.0/modules/slash/"
	>

<channel>
	<title>LuneOS &#8211; pivotCE</title>
...
```

Works fine (?)

I tried again and I succeed to add it. Ok for me :)
