### ISSUE TITLE
Pippa.io podcast feeds cannot be added

### ISSUE THREAD

**Issue by imagoiq** [FreshRSS/FreshRSS#1878]
Hello,

I've tested with two shows and FreshRSS 1.10.1 on PHP 7.1.17:
https://shows.pippa.io/btln
https://shows.pippa.io/brise-glace

Two errors are raised in the logs:

```
Unknown error for feed [https://feed.pippa.io/public/shows/brise-glace]
```
```
A feed could not be found at `https://feed.pippa.io/public/shows/btln`; 
the status code is `200` and content-type is `application/xhtml+xml; charset=utf-8` [https://feed.pippa.io/public/shows/btln]
```

Thanks in advance

**Comment by Frenzie** [comment]
The mimetype is wrong. It should be `application/rss+xml` in this case, `application/atom+xml` for an Atom feed.

You can force add using `#force_feed` (as I found out in #1410). I'll investigate whether there's a way to suggest that to the user in the error message.

**Comment by Frenzie** [comment]
@Alkarex Maybe just adding a little note to the error message here? Something like "to force feed detection in case of an incorrect mimetype, append #force_feed to the URL"

https://github.com/FreshRSS/FreshRSS/blob/fd43ee546e419fc9fbb9a3ad974d2234d94cffaa/lib/SimplePie/SimplePie.php#L1704
