### ISSUE TITLE
not really an issue here but a short feedback

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#1880]
Installed FreshRSS locally swiftly. I enjoy it already. So not really an issue here but a short feedback:
the only  functionality I miss to move completely from Inoreader is the ability to add tags (keywords) to feed items to enable custom made RSS feeds to populate newsletters or sites. 
I also tested Tiny RSS but it requires too much resources on the server.
I'll keep watching FreshRSS updates!

**Comment by Alkarex** [comment]
Implemented in https://github.com/FreshRSS/FreshRSS/pull/2027
Tests welcome

**Comment by Alkarex** [comment]
Landed in the /dev branch
