### ISSUE TITLE
Increase HTTP session expiry time

### ISSUE THREAD

**Issue by m4teh** [FreshRSS/FreshRSS#1881]
I've noticed that the HTTP session expires often well and truly before I'm finished getting through my feeds. Approx 5-10 mins in duration.

The result of this is a login page when clicking anything after this expiration. For example: when clicking 'Mark all as read", you need to log back in and perform that action for it to be successful.

I'm using the **linuxserver/freshrss:latest** docker container. I'm not entirely sure if it's a configuration issue with that container or a FreshRSS app concern.

**Comment by Alkarex** [comment]
When logging in, do you tick the checkbox for staying connected?

**Comment by Alkarex** [comment]
The duration of the session depends very much on the PHP setup. In FreshRSS, there is an automatic background refresh that is supposed to help keeping the session open, especially for servers with short sessions. Please check that there is no JavaScript or HTTP error.

**Comment by m4teh** [comment]
I completely forgot to include that the containers are running behind a Traefik reverse proxy. May or may not be important. I don't have these issues on any other linuxserver container, it just seems to be specific to FreshRSS.

No JS errors and the checkbox is ticked upon logging in.
Do you suggest I get in contact with the maintainer of the linuxserver containers and see if they can determine the possible cause of this?

**Comment by Alkarex** [comment]
@m4teh I think we should perform a few tests on our side first.
* Would you be able to give a try to our own Docker image (the `dev` version), to check if you face the same problem? https://github.com/FreshRSS/FreshRSS/tree/dev/Docker
* We need to check that the FreshRSS refresh request (that is supposed to also extend the session duration) actually comes to PHP and is not cached before
* It would be interesting to print the values for the various relevant parameters from your Docker image, such as `session.gc_maxlifetime`, `session.gc_probability`, etc. http://php.net/manual/session.configuration.php

**Comment by m4teh** [comment]
I will get back to you shortly about that. 
The problem may be with me. It seems to be working as intended on iOS Firefox. 

It may be my PC’s hardened Firefox profile causing inconsistencies. I will do some testing and report back.

**Comment by m4teh** [comment]
The issue was my Firefox profile.

**Comment by Alkarex** [comment]
@m4teh If you can, please give some details about the problem, as this might help others

**Comment by m4teh** [comment]
If you use a hardened Firefox profile (such as the one mentioned in http://12bytes.org/tech/firefox/firefoxgecko-configuration-guide-for-privacy-and-performance-buffs) you may encounter what I did.

Switching to a fresh profile sees the issue unreplicable.
