### ISSUE TITLE
I just can see the 1st article of each folder

### ISSUE THREAD

**Issue by giorgiobeggiora** [FreshRSS/FreshRSS#1884]
I just upgraded from 1.9 to 1.10.1 by clivking on the upgrade button

I have this JS error in console:

	main.js?1526300400:947 Uncaught TypeError: Cannot read property 'length' of undefined
	    at init_notifications (main.js?1526300400:947)
	    at init_afterDOM (main.js?1526300400:1426)
	    at main.js?1526300400:1458
	init_notifications @ main.js?1526300400:947
	init_afterDOM @ main.js?1526300400:1426
	(anonymous) @ main.js?1526300400:1458
	14:23:47.822 

The error is on the "if" in the following code:

	function init_notifications() {
		notification = $("#notification");
	
		notification.find("a.close").click(function () {
			closeNotification();
			return false;
		});
	
		if (notification.find(".msg").html().length > 0) {
			notification_working = true;
			notification_interval = window.setTimeout(closeNotification, 4000);
		}
	}

I'm using the TouchControl extension

**Comment by Alkarex** [comment]
Hello @giorgiobeggiora ,
I have not seen this problem before.
To help isolating the problem, could you please try in another Web browser, and if that is not enough, without the FreshRSS extensions?

**Comment by Alkarex** [comment]
Please check also your PHP and FreshRSS logs

**Comment by Alkarex** [comment]
Might be a similar problem than https://github.com/FreshRSS/FreshRSS/issues/1824

**Comment by giorgiobeggiora** [comment]
Thank you, it was the sharing issue reported in #1824.
I added again my custom sharing code to "app/shares.php" and now it works.
Probably it should be better to implement custom shares in a file that's not overwritten during updates.

Note: my custom share regards getpocket.com. It's one of the most famous bookmark service (it's implemented by default in Firefox). Can you please add it to the default services you implemented? Here is the code:

	'pocket' => array(
		'url' => 'https://getpocket.com/save?url=~LINK~&amp;title=~TITLE~',
		'transform' => array('rawurlencode'),
		'form' => 'simple',
		'method' => 'GET',
	),
