### ISSUE TITLE
Postgresql - unix socket not working

### ISSUE THREAD

**Issue by bartlomiejcieszkowski** [FreshRSS/FreshRSS#1888]
Hi,
I've passed the unix socket path in installation - in the field host:
/var/run/postgresql
and it worked fine, from the db logs I can see that it used the socket, did whole db creation but afterwards in the logs i get that it can't connect to a database:
[Sun, 20 May 2018 16:17:52 +0200] [error] --- Access to database is denied for `freshrss` (`pgsql:host=;dbname=freshrss`)

it seems that the issue is with parse_url, as it returns empty dbServer['host'] instead of keeping it to aforementioned host path.

I did a local workaround in ModelPdo.php for postgresql that uses the original host value if it begins with / and it works fine, the unix socket is used without a problem

**Comment by Alkarex** [comment]
Addressed in https://github.com/FreshRSS/FreshRSS/issues/1889

**Comment by Alkarex** [comment]
Related to https://github.com/FreshRSS/FreshRSS/issues/1364 , https://github.com/FreshRSS/FreshRSS/pull/1366
