### ISSUE TITLE
RGPD broke some RSS (Tumblr)

### ISSUE THREAD

**Issue by Kourai** [FreshRSS/FreshRSS#1894]
Hello!

Because of the new RGPD law in Europe, some RSS flux are now broken. 
My main problem being Tumblr (but I fear we'll face this issue with other sites as well sooner or later) : 
When trying to access this page:
http://funnygamememes.tumblr.com/rss
Then its redirected to this page:
https://www.tumblr.com/privacy/consent?redirect=http%3A%2F%2Ffunnygamememes.tumblr.com%2Frss

Which result in a lot of broken feeds in my FreshRSS...

Is there a way to make a plugin to fix that ?

I know TT-RSS already have a couple of these : https://discourse.tt-rss.org/t/change-on-tumblr-rss-feeds-not-working/1158/ but I know nothing of curl and how to make it work here...

**Comment by Alkarex** [comment]
Hello, and thanks for reporting the issue.
I am aware of it. In the next version of FreshRSS, there will be an option to send custom HTTP headers such as cookies ( https://github.com/FreshRSS/FreshRSS/issues/1627 ), which might help. I am waiting a bit to see how the Tumblr situation stabilises.

**Comment by Alkarex** [comment]
It looks like there is currently a cat/mouse game, as work-arounds for Tumblr only work for a couple of days before failing again :-) Waiting a bit to get a more stable situation.
https://github.com/GregThib/ttrss-tumblr-gdpr

**Comment by Alkarex** [comment]
Implemented in https://github.com/FreshRSS/FreshRSS/pull/1924
Tests welcome

**Comment by Kourai** [comment]
Seems great to me! :)

All my feeds are back!
but I had to perform a 'manual' update to get the extension 
(I update from 1.11.0 to 1.11.1 using the adminstration update button in freshrss, and the extension was not installed... I add it manually, and everything is OK now ! )

**Comment by Kourai** [comment]
Seems great to me! :)

All my feeds are back!
but I had to perform a 'manual' update to get the extension 
(I update from 1.11.0 to 1.11.1 using the adminstration update button in freshrss, and the extension was not installed... I add it manually, and everything is OK now ! )

Thanks a lot! :)

**Comment by Alkarex** [comment]
Ah yes, indeed, the script for the Web update might need a little tweak. Let's remember to look at it (maybe @marienfressinaud ?)

**Comment by marienfressinaud** [comment]
Oh right, I didn't see that this extension was here, I'll try to provide a fix tonight.

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/5457
