### ISSUE TITLE
Erreur bloquante à l'installation

### ISSUE THREAD

**Issue by ClarusAD** [FreshRSS/FreshRSS#1895]
Lors de l'installation avec PHP7 j'ai ce message : "Arf ! Vous ne disposez pas de cURL (paquet php-curl)". Par contre, aucun soucis avec PHP5.

**Comment by Alkarex** [comment]
Bonjour,
Sur quelle plateforme / version êtes-vous ?

Par exemple, avec la version actuelle d'Ubuntu (18.04 LTS), la commande suivante devrait suffire :

```sh
sudo apt install php-curl
```

* https://packages.debian.org/stretch/php-curl
* https://packages.ubuntu.com/bionic/php-curl

Si vous avez deux version de PHP en même temps, il faut éventuellement préciser les numéros de version explicitement. Exemple à adapter en fonction de vos versions :

```sh
sudo apt install php7.2-curl
```

Voir https://github.com/FreshRSS/FreshRSS/#example-of-full-installation-on-linux-debianubuntu

Pareil pour d'autres distributions, comme Alpine :
https://pkgs.alpinelinux.org/packages?name=php*curl&branch=v3.7&arch=x86_64

**Comment by ClarusAD** [comment]
J'essaye d'installer freshRSS sur un serveur mutualisé ; aussi je ne peux pas vraiment savoir quelle est la distro utilisée

**Comment by Alkarex** [comment]
Regardez les détails d'un phpinfo:

```php
<?php
echo phpinfo();
```

**Comment by ClarusAD** [comment]
Est-ce cela que vous cherchez, dès la 1ère ligne. System : "Linux 3.10.0-714.10.2.lve1.5.10.el6h.x86_64 #1 SMP Mon Jan 22 17:29:25 EST 2018 x86_64". Sinon, précisez la clé, je vous donnerai la valeur.

**Comment by Alkarex** [comment]
Il faut regarder les informations cURL.

Exemple de mutualisé chez OVH :
http://pro.ovh.net/infos/
http://fpm7.2-check.cluster003.ovh.net/phpinfo.php

![image](https://user-images.githubusercontent.com/1008324/40565783-272e978c-606e-11e8-9205-bcf4306954bd.png)

Notez qu'il n'y a probablement rien à faire du côté de FreshRSS, car l'extension php-curl lui est essentielle ; il faut donc corriger la configuration du serveur.

**Comment by ClarusAD** [comment]
Vu avec le support technique de mon hébergeur.
Problème résolu, désolé pour le dérangement ^^
