### ISSUE TITLE
Page blanche après mise à jour

### ISSUE THREAD

**Issue by barnabe0057** [FreshRSS/FreshRSS#1897]
Bonjour,

J'ai cliqué sur le bouton vert pour passer de la version 1.3 à la version 1.4
Depuis j'ai une page blanche **https://freshrss.gloomy-zone.ovh/i/**, FreshRSS ne veut plus s'ouvrir.

Je suis sur Raspbian, voilà ma version MySql : 
mysql  Ver 14.14 Distrib 5.5.59, for debian-linux-gnu (armv7l) using readline 6.3

**Comment by Alkarex** [comment]
@barnabe0057 Bien vérifier votre version de PHP. Il me semble que la version actuelle sur Raspbian est PHP 5.6.30. Notez que FreshRSS 1.4 a abandonné PHP 5.2- et que depuis, FreshRSS requiert 5.3.8+.

https://github.com/FreshRSS/FreshRSS/blob/dev/CHANGELOG.md

Votre version de FreshRSS est bien vieille. Je vous suggère de prendre la version actuelle 1.10.2 et de la déployer à la place de la votre (après avoir fait une copie). Copiez votre ancien répertoire `./data/` dans votre nouvelle installation.

Surtout en cas de problème de versions, vous avez aussi la possibilité de déployer [FreshRSS via Docker](https://github.com/FreshRSS/FreshRSS/tree/dev/Docker), ce qui marche bien aussi sur Raspberry Pi.

**Comment by Alkarex** [comment]
P.S. Vous devez probablement avoir des messages dans vos logs du serveur Web et logs de FreshRSS.

**Comment by barnabe0057** [comment]
J'ai suivi vos recommandations, j'ai installé la dernière version, tout s'est bien passé je n'ai rien perdu.
Merci beaucoup pour votre réactivité.

ps : mon log FreshRSS est vide, je n'ai pas vérifié celui de Nginx
