### ISSUE TITLE
actualize_script.php failed since 1.11.0

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#1917]
Since update to 1.11.0 my cron job to actualize feeds is not working anymore
*/30 * * * *    www-data php -f /var/www/freshrss/app/actualize_script.php >/tmp/freshrss-cron.log 2>&1

PHP Fatal error:  Uncaught Error: Call to a member function attributes() on string in /var/www/freshrss/app/Models/Entry.php:197
Stack trace:
#0 /var/www/freshrss/app/Models/Feed.php(395): FreshRSS_Entry->loadCompleteContent('.entry-content')
#1 /var/www/freshrss/app/Models/Feed.php(324): FreshRSS_Feed->loadEntries(Object(SimplePie))
#2 /var/www/freshrss/app/Controllers/feedController.php(311): FreshRSS_Feed->load(false, false)
#3 /var/www/freshrss/app/Controllers/feedController.php(509): FreshRSS_feed_Controller::actualizeFeed(false, false, '1', NULL, false, false)
#4 /var/www/freshrss/lib/Minz/Dispatcher.php(118): FreshRSS_feed_Controller->actualizeAction()
#5 /var/www/freshrss/lib/Minz/Dispatcher.php(47): Minz_Dispatcher->launchAction('actualizeAction')
#6 /var/www/freshrss/lib/Minz/FrontController.php(84): Minz_Dispatcher->run()
#7 /var/www/freshrss/app/actualize_script.php(61): Minz_FrontController->run()
#8 {main}
  thrown in /var/www/freshrss/app/Models/Entry.php on line 197
Results:

**Comment by Alkarex** [comment]
Fix coming

**Comment by Alkarex** [comment]
Could you please test this patch? https://github.com/FreshRSS/FreshRSS/pull/1918
If it helps, I can merge it in /dev.

**Comment by ghost** [comment]
I'm sorry but I don't know how to apply the patch as I am not using the github version of the code.

**Comment by Alkarex** [comment]
Ok. Could you then try to manually replace the following 3 files?
* https://raw.githubusercontent.com/FreshRSS/FreshRSS/dev/app/Models/Entry.php
* https://raw.githubusercontent.com/FreshRSS/FreshRSS/dev/app/Models/Feed.php
* https://raw.githubusercontent.com/FreshRSS/FreshRSS/dev/lib/lib_rss.php

**Comment by ghost** [comment]
ok done, sounds good, no more error.

**Comment by Alkarex** [comment]
Excellent. Please confirm when you have seen that you properly get new update for both normal feeds and feeds fetching full content.

**Comment by ghost** [comment]
I confirm for most of my feed with css selectors. I will have to wait for all of them.
I would be nice to have a test that could validate a css selector when configuring the feed :)

**Comment by Alkarex** [comment]
Thanks for the feedback 👍
