### ISSUE TITLE
Web git update fail

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#1919]
i try to update to the new ver 1.11.0 but it fail. I have this error message : "Git error: Updating 029f4107..c0122003".
i tried to do : 
$ git gc --prune=now
$ git remote prune origin

but still update fail.
anyone can help ?

**Comment by Alkarex** [comment]
Could you please copy-paste the full commands and outputs?

It might be an access right problem.

Assuming your computer user is `deneth` and that you have backed-up any change you might have made to the FreshRSS code:

```sh
cd /usr/share/FreshRSS/
sudo chown -R deneth:www-data .
git pull
sudo chown -R :www-data . && sudo chmod -R g+r . && sudo chmod -R g+w ./data/
```

**Comment by Alkarex** [comment]
For the git update to work from the Web interface, `www-data` (assuming this is the username used by your Web server) needs to have write access to all files underneath `./FreshRSS/` , which might not be the case anymore if you have run some git commands manually from another user.

```sh
cd /usr/share/FreshRSS/
sudo chown -R :www-data . && sudo chmod -R g+rw .
```

**Comment by ghost** [comment]
Thank you, it works.
