### ISSUE TITLE
unable to remove feed - no DELETE button

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#1922]
I don't know if this is due to the latest version 1.11.0. but I can't see the delete button when I edit a feed.
the button is not there anymore.

**Comment by Alkarex** [comment]
Could you please post a screenshot?

E.g. for me:
![image](https://user-images.githubusercontent.com/1008324/41103781-3b253e5c-6a6a-11e8-83a0-24c15f74e92d.png)

**Comment by ghost** [comment]
sure
https://framapic.org/gallery#BfN5On1jgjaW/uwUCRBady0hN.jpg

**Comment by ghost** [comment]
le code est bien la pourtant, mais pas visible dans le browser
`<button class="btn btn-attention confirm" data-str-confirm="Êtes-vous sûr(e) de vouloir continuer ? Vous perdrez les favoris et les filtres associés. Cette action ne peut être annulée !" formaction=".?c=feed&amp;a=delete&amp;id=3" formmethod="post">Supprimer</button>`

**Comment by ghost** [comment]
c'est grisé
https://framapic.org/O3X2mp44FnsS/gtAY403o3eN9.jpg

**Comment by Alkarex** [comment]
Ça alors...

Est-ce que je pourrais voir une vue montrant les règles CSS en même temps ?

![image](https://user-images.githubusercontent.com/1008324/41104773-770192f2-6a6c-11e8-8075-c5d1f0bd56c7.png)

**Comment by Alkarex** [comment]
Pourriez-vous jeter un coup d’œil rapide avec un autre navigateur ?

**Comment by ghost** [comment]
sous Chrome et Edge ca fonctionne, sous firefox 60.x non

**Comment by ghost** [comment]
https://framapic.org/aBWy5lyXoP0q/oa4hRKf3Jg75.jpg

**Comment by Alkarex** [comment]
Fonctionne pour moi avec Firefox 60.0.2 (64 bits).
C'est cette partie qui cause le problème, et ce n'est pas du code de FreshRSS :

![image](https://user-images.githubusercontent.com/1008324/41105506-2d6aa7e4-6a6e-11e8-9c42-672c189c4d5d.png)

Pourriez-vous essayer d'agrandir un peu la zone pour chercher de quel endroit vient cette règle ?

Il y a une référence à *outbrain*. Ce code vient sûrement d'une extension.

**Comment by ghost** [comment]
bon je comprend pas non plus d'ou ca vient, j'ai desactive et reactive des extensions pour trouver laquelle et je reproduis plus ... je cloture, ca vient pas de freshrss, merci.

**Comment by Alkarex** [comment]
@prysme01 Si vous trouvez quelle extension (ou style utilisateur) a causé cela, merci de l'écrire ici

**Comment by ghost** [comment]
J'ai fait plusieurs tests, mais je ne reproduis plus. c'est probablement du au fait de desactiver reactiver des extensions qui ont remis les choses en place.
