### ISSUE TITLE
Plugin stopped working after update

### ISSUE THREAD

**Issue by kevinpapst** [FreshRSS/FreshRSS#1926]
I have a problem with my Dilbert plugin: https://github.com/kevinpapst/freshrss-dilbert

It stopped working after an git pull /dev - but I can't remember exactly when that was.
Strange thing: it works when I delete and re-add the feed http://feeds.feedburner.com/DilbertDailyStrip.

So add the extension, enable it, delete the feed if already present, re-add it => images are shown and title is adjusted.

But it doesn't work when using the cron. So the next day (they publish the images somewhen in the night for European time) the next entry isn't updated, its the plain feed content.

I guess something changed in the cron, probably the hash handling or the call to plugins is not executed? Can anyone point me into a direction from where I could debug?

**Comment by Alkarex** [comment]
Related to https://github.com/FreshRSS/FreshRSS/issues/1797

**Comment by Alkarex** [comment]
I will merge https://github.com/FreshRSS/FreshRSS/pull/1924 , which makes a few changes to the extension mechanism, so that can debug/test both issues at the same time

**Comment by Alkarex** [comment]
Draft of fix https://github.com/FreshRSS/FreshRSS/pull/1932

**Comment by kevinpapst** [comment]
@Alkarex tested with latest dev from yesterday evening => plugin works again! 
Thanks for the quickfix :)

**Comment by Alkarex** [comment]
Hurrah :-)
