### ISSUE TITLE
Fever API - Mark all as read not working

### ISSUE THREAD

**Issue by cutzenfriend** [FreshRSS/FreshRSS#1930]
Hi,
I have the newest version 1.11.0 and tried the new Fever API integration with two iOS Apps: Fiery Feeds and Unread. In both Apps i can‘t mark all Feeds as read, they always get resynced as unread.

If I go into a single feed and mark as read it works for this feed.

**Comment by Alkarex** [comment]
Thanks for the report. Could you please tell what works or not?
* Mark an individual article as read
* Mark a feed as read
* Mark a category as read
* Mark all as read

**Comment by Alkarex** [comment]
Thanks. What database are you using? (MySQL, PostgreSQL, SQLite)

**Comment by Alkarex** [comment]
@cutzenfriend Could you please give a try to https://github.com/FreshRSS/FreshRSS/pull/1931 ? If you did not install by git, the easiest is to just replace `./FreshRSS/p/api/fever.php` with the new version
https://github.com/Alkarex/FreshRSS/blob/4327903c9e03ff6bddd0a83da650f866793d5d26/p/api/fever.php

I do not have any iOS device myself, so not tested.

**Comment by cutzenfriend** [comment]
Hi @Alkarex 
I‘m using this docker image: https://hub.docker.com/r/linuxserver/freshrss/

Tried your fix. Works perfectly 😏 👍🏻

**Comment by Alkarex** [comment]
Thanks for the feedback @cutzenfriend 
The fix is available in the /dev branch. Additional testing much welcome.
