### ISSUE TITLE
Question on sort order

### ISSUE THREAD

**Issue by PhieF** [FreshRSS/FreshRSS#1935]
Hi

I don't really understand the sort order, I've set it to new first

https://framapic.org/yWAlAD2tdxAe/dmPYnA5ThR9c.png

thx !

**Comment by Alkarex** [comment]
The time to the right is the date declared by the original feeds (*published date*), and is often quite different from the discovery / retrieval / crawl time, which is used by FreshRSS for the ordering.
Most other large RSS readers do/did the same, although they often hide, remove, or approximate the published time.

As soon as you let FreshRSS run with regular refresh (best with a cron job), this issue will be minimised.

Please see https://github.com/FreshRSS/FreshRSS/issues/1771 and related threads for additional information, and the rationale for this approach.

**Comment by Alkarex** [comment]
Feel free to open an issue again if needed - or better, continue on some of the existing ones on that topic -
