### ISSUE TITLE
[UI] Feed list tweak

### ISSUE THREAD

**Issue by Liandriz** [FreshRSS/FreshRSS#1936]
In the "Subscriptions management" page, is it possible to change the order of feeds in their categories, with error status feeds at top of each list, to make it easier to find them?  
Thanks.

**Comment by Alkarex** [comment]
This is not a function with have at the moment. This could be written as an extension, though, either server side or client side.

**Comment by aledeg** [comment]
@Alkarex I think we can close this since there is a filter on the aforementioned page for that purpose.

@Liandriz are you aware of said filter? Is this what you had in mind?

**Comment by Alkarex** [comment]
Indeed https://github.com/FreshRSS/FreshRSS/pull/2160
![image](https://user-images.githubusercontent.com/1008324/83923802-43e72e80-a783-11ea-89f6-6e776ba38044.png)
