### ISSUE TITLE
Impossible de rajouter un flux

### ISSUE THREAD

**Issue by qwertygc** [FreshRSS/FreshRSS#1937]
Bonjour,

Impossible de rajouter un flux, je sais pas pourquoi : 
Unknown error for feed [https://feed.pippa.io/public/shows/disruptionpr]
A feed could not be found at `https://feed.pippa.io/public/shows/disruptionpr`; the status code is `200` and content-type is `application/xhtml+xml; charset=utf-8` [https://feed.pippa.io/public/shows/disruptionpr]

**Comment by Alkarex** [comment]
This feed does not look very valid:
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Ffeed.pippa.io%2Fpublic%2Fshows%2Fdisruptionpr

Will look a bit more into it later

**Comment by qwertygc** [comment]
Probably a link for podcast ?

**Comment by Alkarex** [comment]
As the feed is sending back a wrong MIME type, please try with `https://feed.pippa.io/public/shows/disruptionpr#force_feed`

**Comment by qwertygc** [comment]
Thx it's work !
