### ISSUE TITLE
One line title... bad on mobile

### ISSUE THREAD

**Issue by PhieF** [FreshRSS/FreshRSS#1938]
On the feed list we have a constraint to have only one line title.
On mobile a line isn't enough to display the title properly, so I was wondering why limiting to one line

for me, this would be better 
https://framapic.org/kiB7Y54GK6wT/pqvzOPE6dHyG.png

If you want I can pull request that

even because a single line as touch zone isn't enough for big fingers :P 

Thanks !

**Comment by Frenzie** [comment]
You can just stick images here on GH. It's generally more likely to still be there in a few months or whenever someone has time. ;-)

A PR is fine by me, highly welcome even. I'm also using this post to add a cross-reference to #1580 which is mostly unrelated, but see discussion in https://github.com/FreshRSS/FreshRSS/pull/1580#issuecomment-310838942

**Comment by PhieF** [comment]
thanks ! that's right

**Comment by aledeg** [comment]
@PhieF Do you still have the image you've posted? The link is not valid anymore.
Thank you.

**Comment by Frenzie** [comment]
It probably showed something like EasyRSS and the CSS I've been using for quite a while now.

**Comment by marienfressinaud** [comment]
I'm closing this ticket in favor of https://github.com/FreshRSS/FreshRSS/issues/2344 where a (temporary) solution has been discussed. Let's continue the conversation there :)
