### ISSUE TITLE
smooth scroll

### ISSUE THREAD

**Issue by PhieF** [FreshRSS/FreshRSS#1939]

**Comment by Frenzie** [comment]
I don't see how an OS and/or browser setting would be related to FreshRSS?

**Comment by PhieF** [comment]
Sorry I posted by mistake, I'm currently writing it :D

**Comment by PhieF** [comment]
Well just a little suggestion on ui for smoothness 
https://video.anormallostpod.ovh/videos/watch/349f3156-8541-4cf0-97be-cbe73a6828b2
but perhaps I should start making pull requests instead of reports, my mistake
(couldn't post ogv on github)

**Comment by Alkarex** [comment]
Actually, the scroll performance is not very good when the option "mark as read during scroll" is switched.
I actually plan to improve it, and this is quite high on my todo list. With the wish of reducing the resources used on the client side, network, server, and DB.

**Comment by Alkarex** [comment]
Whoah, a PeerTube video :-)
But does not work in my IE6... (Just kidding, tried in Firefox and Chrome without success)
![image](https://user-images.githubusercontent.com/1008324/41490295-ab0ee436-70f3-11e8-9cfd-432ba6ff23e9.png)

**Comment by PhieF** [comment]
The futuuuure is peertube

Well my mistake (again?!) The video was private
This has been the worst "issue" i've ever opened :D

**Comment by Alkarex** [comment]
I forgot of this issue. You are very welcome to make a PR @PhieF 😃 
(Slightly related: I am working on https://github.com/FreshRSS/FreshRSS/pull/2199 to improve performances during scroll)

**Comment by math-GH** [comment]
Does CSS scroll-behavior solve this issue?

https://caniuse.com/?search=scroll-behavior

https://www.w3schools.com/cssref/pr_scroll-behavior.asp

**Comment by Alkarex** [comment]
The scroll performance has already been improved, so maybe that is enough

**Comment by math-GH** [comment]
I would suggest to close this issue
