### ISSUE TITLE
Bug ? Mark all as read on queries results does not work

### ISSUE THREAD

**Issue by GLLM** [FreshRSS/FreshRSS#1944]
Hi all !

I have defined a query (using the new OR boolean in search :-) ) which retrieves articles I find not interesting.

* When I try to mark them all as read using the button available at the bottom of the results
* OR When I use the Mark as read in the toolbar

>> it does not do anything : it displays a message saying : articles have been marked as read, but when i launch the query again : all the articles still appear as unread.

Using freshRSS 1.11.1 on Ubuntu 16.04 LTS / PHP 7.2 / MySQL
My query is simple (and works well)  : intitle:"Bon plan" OR intitle:nintendo OR intitle:"[Promo]" OR intitle:"antivirus" OR intitle:"Bons plans" OR intitle:"concours"

Are you aware of this ?

GLLM

**Comment by Alkarex** [comment]
Thanks for the report.

There is indeed an encoding bug (related to the quotes), as visible below. Will fix.

```sql
SELECT e0.id, e0.guid, e0.title, e0.author, UNCOMPRESS(content_bin) AS content, e0.link, e0.date, e0.is_read, e0.is_favorite, e0.id_feed, e0.tags FROM `freshrss_alex_entry` e0 INNER JOIN (SELECT e.id FROM `freshrss_alex_entry` e INNER JOIN `freshrss_alex_feed` f ON e.id_feed = f.id WHERE f.priority > 0  AND e.is_read=0 AND e.id <= '1527762101674974' AND ((e.title LIKE '%Bon plan%' ) OR (e.title LIKE '%nintendo%' ) OR (e.title LIKE '%[Promo]%' ) OR (e.title LIKE '%antivirus%' ) OR (e.title LIKE '%Bons plans%' ) OR (e.title LIKE '%concours%' ) ) ORDER BY e.id DESC LIMIT 31) e2 ON e2.id=e0.id ORDER BY e0.id DESC

UPDATE `freshrss_alex_entry` e INNER JOIN `freshrss_alex_feed` f ON e.id_feed=f.id SET e.is_read=1 WHERE e.is_read=0 AND e.id <= '1529424180167453' AND f.priority > 0 AND ((CONCAT(e.title,UNCOMPRESS(e.content_bin)) LIKE '%&amp;quot;Bon%' AND CONCAT(e.title,UNCOMPRESS(e.content_bin)) LIKE '%plan&amp;quot;%' ) OR (e.title LIKE '%nintendo%' ) OR (CONCAT(e.title,UNCOMPRESS(e.content_bin)) LIKE '%&amp;quot;[Promo]&amp;quot;%' ) OR (CONCAT(e.title,UNCOMPRESS(e.content_bin)) LIKE '%&amp;quot;antivirus&amp;quot;%' ) OR (CONCAT(e.title,UNCOMPRESS(e.content_bin)) LIKE '%&amp;quot;Bons%' AND CONCAT(e.title,UNCOMPRESS(e.content_bin)) LIKE '%plans&amp;quot;%' ) OR (CONCAT(e.title,UNCOMPRESS(e.content_bin)) LIKE '%&amp;quot;concours&amp;quot;%' ) )
```

**Comment by Alkarex** [comment]
Please try this fix https://github.com/FreshRSS/FreshRSS/pull/1945

**Comment by Alkarex** [comment]
Should be fixed in /dev . Feedback welcome
