### ISSUE TITLE
url for the api

### ISSUE THREAD

**Issue by oupala** [FreshRSS/FreshRSS#1946]
I'm using FreshRSS version 1.10.0 and I'm using a configuration where FreshRSS is available on url `http://example.org/rss/` and where 

```bash
>ls -l /var/www/example.org/rss
lrwxrwxrwx 1 root root 33 mars   1 22:51 /var/www/example.org/rss -> /path/to/FreshRSS-1.10.0/p/
```

When I got to FreshRSS configuration web interface, I can see that the displayed API url (for information) is `https://example.org/rss/i/api/` but in fact the working url is `https://example.org/rss/api/greader.php`.

As you can see, FreshRSS is adding an `i` in the url, it shouldn't.

**Comment by oupala** [comment]
Here it is:

```php
'base_url' => '',
```

**Comment by Alkarex** [comment]
Could you please try this patch? https://github.com/FreshRSS/FreshRSS/pull/2006

**Comment by oupala** [comment]
I tried it on my current FreshRSS 1.10 install, but it does not seem to change anything.

Do I have to reinstall?

**Comment by Alkarex** [comment]
@oupala No, you do not have to re-install anything. But there may be a cache issue. So please make any change (such as marking an article as read), and then go back to the page.

**Comment by oupala** [comment]
After marking an article as read, I still have the old wrong url:

> https://example.org/rss/i/?c=auth&a=login&u=alice&p=1234

**Comment by Alkarex** [comment]
@oupala This URL looks good, doesn't it? It was the first one with `.../rss/i/api/...` that was wrong, but `.../rss/i/?...` and `.../rss/api/...` are expected

**Comment by oupala** [comment]
You're right @Alkarex, I was looking at the wrong page (note for later, the correct page to look at is Configuration > Profil, in the french locale).

Now the link is better: `https://example.org/rss/api/`

But my working url was `https://example.org/rss/api/greader.php`. Is `greader.php` optional or mandatory? I thought it was mandatory, but I might be wrong.

**Comment by oupala** [comment]
If the full url is mandatory, then the full url should be displayed on the config page. Right?

**Comment by Alkarex** [comment]
It is indeed a bit confusing. The full URLs for each of the two APIs that we have (Google Reader and Fever) are displayed when clicking on that link.

**Comment by oupala** [comment]
Oh, it is a bit confusing. Maybe the first page should display both urls.
