### ISSUE TITLE
Auto-merge PR?

### ISSUE THREAD

**Issue by Frenzie** [FreshRSS/FreshRSS#1948]
Something interesting I saw today: https://julien.danjou.info/stop-merging-your-pull-request-manually/

It could auto-merge after, say, three devs approve a PR.

**Comment by Alkarex** [comment]
Hehe, this is a bit over-engineered automation :-)

**Comment by marienfressinaud** [comment]
I'm not sure I like this kind of automation :p I prefer to be able to take a last look at the code. It also doesn't consider cases where we approve a PR, letting last details at the discretion of the developer.

**Comment by Frenzie** [comment]
True, I do leave approvals like that all the time (a bit in between a comment and an approval), but I do mean I approve of the PR being merged as is even if I think it could be better.

But my main reason to second-guess an approach like this is that a computer probably can't judge very well whether to squash or rebase. (Given that @Alkarex has expressed a preference for always squashing that might be a non-issue in this repo.)
