### ISSUE TITLE
new feature hotkey for play / pause embedded media in item

### ISSUE THREAD

**Issue by mdemoss** [FreshRSS/FreshRSS#1952]
I think it should be simple enough to send an event to the audio or video element, provided there's only one.

**Comment by aledeg** [comment]
@Alkarex Do you think this should be in the core?

**Comment by Alkarex** [comment]
Hum yes, that is probably a quite small piece of code

**Comment by aledeg** [comment]
I need that so I'll have a look at it

**Comment by aledeg** [comment]
@mdemoss 2 years later, it's time to test the media shortcut. Test the PR and tell me if this is working properly. I've tried it myself and I am pretty pleased.
