### ISSUE TITLE
Nginx proxy + Dockerised Freshrss

### ISSUE THREAD

**Issue by yk82** [FreshRSS/FreshRSS#1959]
Hi, 
I'm using freshrss in a docker container behind a proxy (also in a container) for encryption.
I can access the container directely on the container exposed port (LAN access). Everything works well.
I got the "Error 403 - Forbidden" when trying to acces freshrss using external adress  "https://<DOMAIN>:<PORT>/URL". The login page is reached but I don't get throw the authentification form. The logs shows "Password mismatch for user=xxxxxx, nonce=, c=$2a$04$xM...".
Did anyone else experience this issue?

Docker image : freshrss/freshrss or linuxserver/freshrss

**Comment by Alkarex** [comment]
Hello,
It looks like you have an empty `nonce`, which is a sign that your PHP session is not working. It is likely an HTTP header problem, with your proxy not allowing cookies or instructions such as `Set-Cookie` (response) or `Cookie` (request).

Similar than https://github.com/FreshRSS/FreshRSS/issues/1659#issuecomment-335577814

**Comment by Alkarex** [comment]
@yk82 Did you found a solution?

**Comment by thomas-gt** [comment]
Had same kind of issue (403 + empty `nonce` in log.txt) with Dockerized FreshRSS behind Nginx Reverse Proxy.
Just tested by adding following instruction into `server` block in Nginx conf file seems solve my problem :
`proxy_cookie_path / "/; HTTPOnly; Secure";`

**Comment by Alkarex** [comment]
@thomas-gt Thanks for the feedback 👍

**Comment by Alkarex** [comment]
@thomas-gt Would you feel like doing a quick PR in the README for that (just adding a line with that comment, or an example of NGINX config)? :-)

* https://github.com/FreshRSS/FreshRSS/tree/dev/Docker#deployment-in-production

**Comment by thomas-gt** [comment]
Done in #2151 😃
