### ISSUE TITLE
[FeatureRequest] recherche sur l'ensemble des articles

### ISSUE THREAD

**Issue by prolibre** [FreshRSS/FreshRSS#1961]
Bonjour,

Je me permets d'écrire en français. Serait il possible de faire en sorte que la recherche d'un mot ou d'un tag s'effectue sur l'ensemble des flux et non pas seulement sur les flux "non lus" (lorsqu'il en reste évidemment :-) )
Parfois je cherche une info et celle ci ne s'affiche pas parce qu'il reste des flux "non lus" et que mon info se situe sur un article déjà "marqué comme lu".
Peut être une case à cocher ou l'affichage différencié (lu/non lu) lors de l'affichage des résultats.

Quoi qu'il en soit merci pour votre travail et pour la qualité de l'outil.

Anthony

**Comment by Alkarex** [comment]
Bonjour,
C'est déjà possible : la recherche s'effectue toujours dans la vue courante.
Affichez les articles lus, puis exécutez votre recherche.

Il y a une icône pour afficher les articles lus :

![image](https://user-images.githubusercontent.com/1008324/42938129-82ff7c9e-8b51-11e8-9f1d-383bb19307e0.png)

**Comment by prolibre** [comment]
un grand merci pour l'aide alors.

Anthony
