### ISSUE TITLE
Entry ID's and 32 bit environment

### ISSUE THREAD

**Issue by Vincentv92** [FreshRSS/FreshRSS#1962]
Recently I ran into an issue when I migrated my FreshRSS installation from a 64 bit environment to a 32 bit environment. Specifically the use case when using the Fever API and the Reeder client for macOS and iOS. 

It appears, that some entry id's for the articles have a very high number, as in for example `1531867867902117` as unique identifier.
For storing these entries on a 32 bit environment when using MariaDB or MySQL works perfectly fine since the `id` column is stored as a `bigint`.
But there are issue's within PHP handling these integers if the environment is 32 bit.
I only ran into issues with the Fever API since that's the only component I currently use extensively.

### The issue
After migration my Reeder client's successfully downloaded the articles but failed to fetch new articles through the Fever API. So I opened up my Nginx access logs to see what happend. I saw I had around hundreds of requests per minute which looked something along the lines of this:
```POST /api/fever.php/?api&items&since_id=1532025245261275 HTTP/1.1" 200 72900 "-" "Reeder/3010.29.01 CFNetwork/902.1 Darwin/17.7.0 (x86_64)"
POST /api/fever.php/?api&items&since_id=1532025245261275 HTTP/1.1" 200 72900 "-" "Reeder/3010.29.01 CFNetwork/902.1 Darwin/17.7.0 (x86_64)"
POST /api/fever.php/?api&items&since_id=1532025245261275 HTTP/1.1" 200 72900 "-" "Reeder/3010.29.01 CFNetwork/902.1 Darwin/17.7.0 (x86_64)"
POST /api/fever.php/?api&items&since_id=1532025245261275 HTTP/1.1" 200 72900 "-" "Reeder/3010.29.01 CFNetwork/902.1 Darwin/17.7.0 (x86_64)"
POST /api/fever.php/?api&items&since_id=1532025245261275 HTTP/1.1" 200 72900 "-" "Reeder/3010.29.01 CFNetwork/902.1 Darwin/17.7.0 (x86_64)"
POST /api/fever.php/?api&items&since_id=1532025245261275 HTTP/1.1" 200 72900 "-" "Reeder/3010.29.01 CFNetwork/902.1 Darwin/17.7.0 (x86_64)"
```

So I went ahead and manually verified the returned data from the Fever API and noticed the `id` `1532025245261275` was the last element from the the Fever API response. At this point I wasn't sure what was happening, I compared this to my previous installation and it worked perfectly fine there. 
The next thing I did was verifying that the `findEntries` function of the `fever.php` file was receiving the id `1532025245261275` and I noticed I saw the [PHP_INT_MAX](http://php.net/manual/en/reserved.constants.php#constant.php-int-max) value `2147483647` 

This is where I got the aha moment. The cause was from [this specific line](https://github.com/FreshRSS/FreshRSS/blob/3306a1679c2570c30d4b662c887b4a71ce147398/p/api/fever.php#L484)

### Possible solutions

The issue is that function `intval()` cannot use the big integers on 32 bit system, so my quick fix was to remove all `intval()` functions from the `fever.php` file to test if it worked again after that.
And yes that worked.

So there are a few solutions to this issue:

1. Don't support 32 bit installations
2. Make the entry_id's 32 bit safe (or configurable)
3. Only validate its a valid integer but pass on the `string` value to the query builder and let the database handle this

So what should be a proper solution for this issue?

PS, I checked if there were more `intval()` usages within the project and noticed there are more references to this. Not all of them handle an `entry id` but this could potentially cause more issue's which haven't been noticed (yet)

**Comment by Frenzie** [comment]
Surely 32-bit safe should be fine as far as the number of IDs goes?

**Comment by Vincentv92** [comment]
Sorry, I don't understand what you are trying to say.
The issue is that the entry id's get by default an insanely high number assigned, which a 32 bit PHP environment cannot handle as an integer.

**Comment by Alkarex** [comment]
Thanks for the bug report. I will try to have a look. The IDs should
probably be handled as string in that case.
The rest of FreshRSS including the Google Reader API should already be fine
in 32 bits.

**Comment by Alkarex** [comment]
@Vincentv92 Could you please give a try to this patch https://github.com/FreshRSS/FreshRSS/pull/1964 (Not tested at all yet)
The rest of the `inval()` in FreshRSS should all be 32-bit safe.

**Comment by Alkarex** [comment]
Merged in the /dev branch. Tests welcome
