### ISSUE TITLE
progressive web app

### ISSUE THREAD

**Issue by qwertygc** [FreshRSS/FreshRSS#1963]
Hello

An idea it's implant progressive web app in fresh idea. Indeed, with the offline mode we can read without internet and we don't need to use third part app.

**Comment by Frenzie** [comment]
It would be nice, although given that there's a multitude of API-compatible clients out there I'd personally peg it at fairly low priority.

**Comment by PhieF** [comment]
Hi ! You could, at first, just put a manifest for us to be able to create standalone shortcuts, like nextcloud did ! even if we don't have an offline access

**Comment by Frenzie** [comment]
I'm curious, which browser lacks such basic functionality?

**Comment by madb1lly** [comment]
Hi all, I just suggested this is Framateam, thanks to @Frenzie for the link.

The benefit of a PWA would be that it can also store downloaded feeds and articles for offline viewing and would generally be lighter-weight than a "native" app. Also, PWAs are cross-platform, so can be deployed by any browser on any plaform that supports it, e.g. Android, Windows, iOS (I think).

Cheers :)

**Comment by Frenzie** [comment]
Unless you're taking a jab at Java, I think most clients are indeed native, not "native." ;-)

**Comment by madb1lly** [comment]
Hi @Frenzie, fair point, I wasn't clear - I just meant that I think the concept of native vs webapps is a bit old-fashioned when considering PWAs and current javascript engines, especially if WASM can be used in some way.

I was thinking about the possibility of a PWA for this a bit more and since for offline use Freshrss would need to have a way of storing articles - I think this may be with the DBs provided by the web browser but maybe it's possible to install others alongside, for a PWA to use. If it depends on the web browser PWA you'd need to decide which articles to store as I imagine you can't store as many with a PWA as you can on the web server or perhaps in a DB for a traditional app.

**Comment by Frenzie** [comment]
I don't think there are any relevant practical limits on a PWA. It might still be slightly more limited out of the box in which case it would ask for more space after reaching certain thresholds.

**Comment by yllekz** [comment]
Did FreshRSS quietly add this? I noticed on iOS if I add the main page of my FreshRSS hosted instance to the iOS home screen, it opens up as its own dedicated app, so I'm wondering if PWA functionality was added in already.

**Comment by Frenzie** [comment]
I suppose that means one answer to my question from https://github.com/FreshRSS/FreshRSS/issues/1963#issuecomment-564522680 would be old iOS Safari.

**Comment by proletarius101** [comment]
Even no offline part is provided, PWA apps are more integrated to the system that they don't have the browser frame, making them look and feel as native apps. Browser shortcuts don't provide such experience.

**Comment by Frenzie** [comment]
Online or offline is unrelated to being able to tell the browser to install a website as an "app" with a shortcut on your desktop. What kind of features specifically are you referring to? Do you perhaps have any examples?

<img src=https://user-images.githubusercontent.com/202757/137475653-f2970243-d7b4-46e3-a966-6c9b10b0f438.png width=45%> <img src=https://user-images.githubusercontent.com/202757/137475054-6f88d6ed-6987-445d-bdae-a2a613669358.png width=45%>

**Comment by proletarius101** [comment]
> Online or offline is unrelated to being able to tell the browser to install a website as an "app" with a shortcut on your desktop. What kind of features specifically are you referring to? Do you perhaps have any examples?
> 
> <img alt="" width="45%" src="https://user-images.githubusercontent.com/202757/137475653-f2970243-d7b4-46e3-a966-6c9b10b0f438.png"> <img alt="" width="45%" src="https://user-images.githubusercontent.com/202757/137475054-6f88d6ed-6987-445d-bdae-a2a613669358.png">

For pwa refer to web apps on mobile platforms. E.g. Twitter.

Firefox or Chrome can only add a shortcut on the main screen if no such manifest

**Comment by Frenzie** [comment]
My Android Chrome and Firefox both offer an "add to home screen" option, which hasn't changed from a couple of years ago when I wrote my comment in https://github.com/FreshRSS/FreshRSS/issues/1963#issuecomment-564522680

**Comment by proletarius101** [comment]
Add to home screen crrates shortcuts showing the browser frame, while the Install (PWA) button crrates shortcuts without the browser frame, which is more native. Also, the latter one has a splash screen.

**Comment by proletarius101** [comment]
You may try install https://mdn.github.io/pwa-examples/a2hs/ on mobile v.s. adding this issue page https://github.com/FreshRSS/FreshRSS/issues/1963 to home screen. Open both of them and you will see the difference

**Comment by Frenzie** [comment]
I see, so I do get to say that you should just just a less crappy browser like Vivaldi after all. ;-)

**Comment by proletarius101** [comment]
Also it will give a separate view stack than the browser one. Pretty important on mobile.

> I see, so I do get to say that you should just just a less crappy browser like Vivaldi after all. ;-)

But not on mobile.

**Comment by Frenzie** [comment]
> But not on mobile.

I'm talking about Vivaldi mobile. Splash screen, no browser chrome. (Although I actually find that rather annoying. Maybe if it opened new links in a proper Vivaldi tab instead of on top.)

**Comment by Frenzie** [comment]
It looks like Vivaldi desktop is in fact a patient of artificial limitationitis.

**Comment by Frenzie** [comment]
Imo this is very much a browser bug, *not* an issue with every single individual website out there. But please feel free to submit a PR with a manifest.json.

**Comment by Frenzie** [comment]
Have fun: https://github.com/FreshRSS/FreshRSS/pull/3889

**Comment by Frenzie** [comment]
In response to the artificial limitations imposed on users with regard to this manifest business, I offer the classic Opera Bork script to paste into your CustomJS extension.

<details>

```js
// http://web.archive.org/web/20050301075735/http://www.opera.com/js/bork/enchefizer.js

/* -*- mode: C++; mode: font-lock; tab-width: 4 -*-
 * 2003-02-10
 *
 * The Enchefizer code is based on a script fetched from 
 *   http://tbrowne.best.vwh.net/chef/
 * written by Andriy Rozeluk <arozeluk@websoup.net>, which is
 * based on a Java version written by Josh Vura-Weis
 * <wtpooh@leland.Stanford.EDU>, which is based on a UNIX version
 * from 1993 written by John Hagerman <hagerman@ece.cmu.edu> and
 * Jeff Allen <jallen@jarthur.claremont.edu>
 *
 * Subsequently hacked by Opera Software to work inside a page by 
 * traversing the DOM tree, and to improve performance. 
 *
 * Typical usage is to add the following text to the bottom of a page:
 *       <script src="enchefizer.js"></script>
 */

const classicOperaBork = () => {
    /* USER CONFIGURATION BEGINS */
    var victim=false;   // false (apply to any page) or regex to match page URL
    //var victim=/^http:\/\/(?:(?:www|msdn).microsoft.com|www.msn.com)/;
    var delay=50;       // ms between replacements, set to 0 to disable waiting
    var units=30;       // number of text nodes to translate each time
    var highlight=true; // highlight the text we're working on
    /* USER CONFIGURATION ENDS */

    var textnodes=[];   // text nodes in the doc
    var nextnode=0;     // next node to process

    function nextWordPos(line)
    {
		var p = line.search(/[ \n\t\\,<.>/?;:\'\"\[{\]}|=+\-_!@#$%^&*()~`]/);
        return p == -1 ? line.length+1 : p;
    }

    function encheferizeLine(line)
    {
		var buff="", word="", t="", out="", wp;

		while(line.length > 0)
		{
			wp = nextWordPos(line);
			word = line.substring(0,wp);
			t = line.charAt(wp);
			line = line.substring(wp+1,line.length);
			out = out + encheferizeWord(word) + t;
		}
		if(t == ".")
		{
	        out = out + "\nBork Bork Bork!";
		}

		return out;
    }

    function encheferizeWord(word)
    {
		if(word.toLowerCase() == "bork") return word;
      
		var letter, count, len, buff, i_seen, isLast;
      
		count=0;
		len=word.length;
		buff=""
		i_seen=false;
      
		while(count<len){
			isLast = count==(len-1);
         
			letter=word.charAt(count);
                  
			if(count==0){ //Beginning-of-word rules
				if(letter=='e'){
					buff=buff + "i";
					count++;
					continue;
				} else if(letter=='E'){
					buff=buff + "I";
					count++;
					continue;
				} else if(letter=='o'){
					buff=buff + "oo";
					count++;
					continue;
				} else if(letter=='O'){
					buff=buff + "Oo";
					count++;
					continue;
				}
			} else {  //End of Beginning-of-word rules, Start of In-Word rules
				if(letter=='e'){
					if(!isLast && word.charAt(count+1)=='w'){
						buff = buff + "oo";
						count+=2;
						continue;
					} else if(isLast){
						buff = buff + "e-a";
						count++;
						continue;
					}
				} else if(letter=='f'){
					buff = buff + "ff";
					count++;
					continue;
				} else if(letter=='i'){
					if(!isLast && word.charAt(count+1)=='r'){
						buff = buff + "ur";
						count+=2;
						continue;
					} else if(!i_seen){
						buff = buff + "ee";
						count++;
						i_seen=true;
						continue;
					}                   
				}else if(letter=='o'){
					if(!isLast && word.charAt(count+1)=='w'){
						buff = buff + "oo";
						count+=2;
						continue;
					} else {
						buff = buff + "u";
						count++;
						continue;
					}
				} else if(count<=len-4 && letter=='t' && word.charAt(count+1)=='i'
						  && word.charAt(count+2)=='o' && word.charAt(count+3)=='n'){
					buff = buff + "shun";
					count+=4;
					continue;
				} else if(letter=='u'){
					buff = buff + "oo";
					count++;
					continue;
				} else if(letter=='U'){
					buff = buff + "Oo";
					count++;
					continue;
				}
			}  //end if In-word rules
			//End if Word-placement rules, Start of Anywhere rules
			if(letter=='A'){
				if(!isLast && word.charAt(count+1)=='n'){
					buff = buff + "Un";
					count=count+2;
					continue;
				} else if(!isLast && word.charAt(count+1)=='u'){
					buff = buff + "Oo";
					count=count+2;
					continue;
				} else if(!isLast){
					buff = buff + "E";
					count++;
					continue;
				}   
			} else if(letter=='a'){
				if(!isLast && word.charAt(count+1)=='n'){
					buff = buff + "un";
					count=count+2;
					continue;
				} else if(!isLast && word.charAt(count+1)=='u'){
					buff = buff + "oo";
					count=count+2;
					continue;
				}else if(!isLast){
					buff = buff + "e";
					count++;
					continue;
				}
			} else if(letter=='e'){
				if(!isLast && word.charAt(count+1)=='n' 
				   && count==len-2){
					buff = buff + "ee";
					count+=2;
					continue;
				} else if(count>0){
               
				} 
			} else if(letter=='t'){
				if(count==len-2 && word.charAt(count+1)=='h'){
					buff = buff + "t";
					count+=2;
					continue;
				} else if(count<=len-3 && word.charAt(count+1)=='h'
						  && word.charAt(count+2)=='e'){
					buff = buff + "zee";
					count+=3;
					continue;
				} 
			} else if(letter=='T' && count<=len-3 && word.charAt(count+1)=='h'
					  && word.charAt(count+2)=='e'){                                                
				buff = buff + "Zee";
				count+=3;
				continue;
			} else if(letter=='v'){
				buff = buff + "f";
				count++;
				continue;
			} else if(letter=='V'){
				buff = buff + "F";
				count++;
				continue;
			} else if(letter=='w'){
				buff = buff + "v";
				count++;
				continue;
			} else if(letter=='W'){
				buff = buff + "V";
				count++;
				continue;
			}
			//End of rules.  Whatever is left stays itself
			buff = buff + letter;
			count++;
		}
		
		return(buff);
    }

    function bork()
    {
		var limit = delay == 0 ? Number.MAX_VALUE : units;
		var start=nextnode;
		var oldc = new Array();
		var n, i, candidate;

		if (highlight)
		{
			for ( n=start, i=0 ; i < limit && n < textnodes.length ; n++, i++ )
			{
				candidate = textnodes[n];
				oldc[i] = candidate.parentNode.style.backgroundColor;
			}

			for ( n=start, i=0 ; i < limit && n < textnodes.length ; n++, i++ )
			{
				candidate = textnodes[n];
				candidate.parentNode.style.backgroundColor = 'red';
			}
		}

		for ( i=0 ; i < limit && nextnode < textnodes.length ; nextnode++, i++ )
		{
			candidate = textnodes[nextnode];
            candidate.replaceData(0,candidate.length,encheferizeLine(candidate.data));
		}

		if (highlight)
		{
			for ( n=start, i=0 ; i < limit && n < textnodes.length ; n++, i++ )
			{
				candidate = textnodes[n];
				candidate.parentNode.style.backgroundColor = oldc[i];
			}
		}

		bork_more();
    }

    function bork_more()
    {
		if (nextnode < textnodes.length)
		{
			setTimeout( bork, delay );
		}
    }

    /* In large docs traversal is a bottleneck at startup; we could
       CPS it or otherwise reify the traversal state to interleave
       traversal with the translation.
	*/
    function find_textnodes(elm, acc)
    {
		if (elm.nodeType == 3)
		{
			if (!elm.data.match(/^[\s\n\r]*$/))
			{
				acc.push(elm);
			}
		}
		else
		{
			var c = elm.childNodes;
			for ( var i=0 ; i < c.length ; i++ )
			{
				find_textnodes(c.item(i),acc);
			}
		}
		return acc;
    }

    /* run page's onload handler, then do our thing */
    var res = false;

    if (typeof old_onload == "function")
	{
		res = old_onload();
	}

    if (/*window == top &&*/ (!victim || window.location.href.match(victim)) )
    {
		textnodes = find_textnodes(document.body, new Array());
		nextnode=0;
		bork_more();
    }
    return res;
}
if (window.navigator.userAgentData.brands.filter(e => e.brand === 'Google Chrome').length > 0) {
    document.addEventListener('DOMContentLoaded', classicOperaBork);
}
```

</details>

Should you accidentally open your instance in Chrome, it will adapt as follows:

![Screenshot_20211015_161211](https://user-images.githubusercontent.com/202757/137501572-48d74244-5a55-4232-b909-84f78ee577b7.png)
