### ISSUE TITLE
Failed to convert extension file list

### ISSUE THREAD

**Issue by Leepic** [FreshRSS/FreshRSS#1965]
Hello,

In the FreshRSS extensions I don't see the list.
In the log file I can see the warning "Failed to convert extension file list". It's because the [json](https://raw.githubusercontent.com/FreshRSS/Extensions/master/extensions.json) for fetching the available extension list is malformated. The function json_decode() in  [FreshRSS/app/Controllers/extensionController.php](https://github.com/FreshRSS/FreshRSS/blob/master/app/Controllers/extensionController.php#L54) return the error 4 (JSON_ERROR_SYNTAX).

I'm using the dev branch version 1.11.2.

**Comment by Alkarex** [comment]
Thanks for the fix in https://github.com/FreshRSS/Extensions/pull/34
