### ISSUE TITLE
[Feature Request] Mark all items (younger than...) as unread

### ISSUE THREAD

**Issue by hrehfeld** [FreshRSS/FreshRSS#1966]
I would like to be able to _mark everything younger than a certain time as unread_. Basically, the same as with "mark read", just inverse. 

I accidently marked 50k posts as read, because even on mobile it's just two misclicks away and notifications get into the way :cry: This should be easy to implement and help slightly.
Thanks a bunch in advance! ;-)

**Comment by Alkarex** [comment]
Implemented in https://github.com/FreshRSS/FreshRSS/pull/1995

**Comment by Alkarex** [comment]
@hrehfeld Could you please try the following patch? https://github.com/FreshRSS/FreshRSS/pull/1995
You can select recent articles with a search like `date:P30d` and then mark them as unread from the drop-down menu.

**Comment by Alkarex** [comment]
@hrehfeld Example to mark as unread articles younger than e.g. 7 days:

![image](https://user-images.githubusercontent.com/1008324/44998991-53d44c00-afba-11e8-862c-fbbe4dced152.png)
