### ISSUE TITLE
How to use the proxy to overturn GFW？

### ISSUE THREAD

**Issue by sqliuchang** [FreshRSS/FreshRSS#1967]
My vps is in China, you know, many websites are blocked by the GFW in China. And the most important is that feedburner provided by Google is unreachable if no proxy.
I don't know how to use the proxy when I choose to install FreshRSS by docker.

**Comment by temberature** [comment]
```
'curl_options' => 
  array (
  	CURLOPT_PROXYTYPE => CURLPROXY_HTTP, 
 	CURLOPT_PROXY => '192.168.10.51', 
 	CURLOPT_PROXYPORT => 7890,
  ),
```
