### ISSUE TITLE
Only one dc:creator is shown as author

### ISSUE THREAD

**Issue by hrehfeld** [FreshRSS/FreshRSS#1968]
Example: https://haukerehfeld.de/feed/index.xml 

(feed validates: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fhaukerehfeld.de%2Ffeed%2Findex.xml, albeit with warnings about other stuff.)

Only the first dc:creator is shown in the feed view.

    <?xml version="1.0" encoding="utf-8"?>
    <rss version="2.0" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:atom="http://www.w3.org/2005/Atom">
      <channel>
        <title>Hauke Rehfeld</title>
        <link>https://haukerehfeld.de/</link>
        <description>Latest posts on Hauke Rehfeld</description>
        <pubDate>Mon, 30 Jul 2018 14:19:30 +0200</pubDate>
        <atom:link href="https://haukerehfeld.de/feed/index.xml" rel="self" type="application/rss+xml"/>
        <item>
          <title>Eindruck einer friedlichen und geruhsamen Ansiedlung</title>
          <link>https://haukerehfeld.de/art/2018-houses</link>
          <guid isPermaLink="true">https://haukerehfeld.de/art/2018-houses</guid>
          <dc:creator>First Author</dc:creator>
          <dc:creator>Second Author</dc:creator>
          <category>art</category>
          <pubDate>Mon, 16 Jul 2018 22:00:00 +0000</pubDate>
          <description><![CDATA[...]]></description>
        </item>
    ...

**Comment by Alkarex** [comment]
Fixed in https://github.com/FreshRSS/FreshRSS/pull/1997 . Tests welcome

**Comment by Alkarex** [comment]
@hrehfeld Only the new ones, or by removing/re-adding a feed
