### ISSUE TITLE
Setting API password: your profile cannot be modified

### ISSUE THREAD

**Issue by uncovery** [FreshRSS/FreshRSS#1969]
Hi,
I enabled the API in the configuration, and I am trying to set an API password in my profile settings.
However, I get a red bar on the top that tells me "Your profile cannot be modified".

I checked, and the config.php for that (admin) user has the right permissions.
As a workaround, I just edited it and copy/pasted the hash from the login pw to the api password field.
But of course this is not the recommended way to do it.

What do I need to do to enable this?

**Comment by Alkarex** [comment]
Hello,
(Sorry for the delay - vacations)
Please make sure that your Web server has the needed write access. On Ubuntu with Apache, it is `www-data`.

For instance:

```sh
cd /usr/share/FreshRSS
sudo chown -R :www-data .
sudo chmod -R g+r .
sudo chmod -R g+w ./data/
```

**Comment by siSSSou** [comment]
Same problem with a fresh install on debian 8 / Nginx : each time I set an API password I get disconnected.
I checked write access and it's OK.

How to set that password ?

**Comment by uncovery** [comment]
FreshRSS is able to write and does write to the user config file. I just checked and the last filewrite was 2 hours ago (w/o my manual interaction). FreshRSS can and does also write to the log.txt in the same directory which has the same file properties. It still does not work.

I found the following now though: There is a strange "users" subfolders: "_".
`
in /data/users/_/log.txt: [Tue, 28 Aug 2018 13:31:43 +0000] [warning] --- Could not save API credentials for fever API`

in the logfile of the actual user there is nothing though for that specific time.

I checked where that error is actually in the code and found the following:
`
$ok = file_put_contents(DATA_PATH . '/fever/.key-' . sha1(FreshRSS_Context::$system_conf->salt) . '-' . $userConfig->feverKey . '.txt', $user) !== false;`

near https://github.com/FreshRSS/FreshRSS/blob/3306a1679c2570c30d4b662c887b4a71ce147398/app/Controllers/userController.php#L76

I always assumed that the datafile in question should be /data/myuser/... I checked on that folder (/data/fever) and there actually the folder permissions were not correct. So I fixed the file permissions and got redirected to this page:

https://spiesshofer.com/freshrss/i/?c=error

> Error 403 - Forbidden
> 
> You don’t have permission to access this page
> ← Go back to your RSS feeds

there was a key file created however in the /data/fever/ directory, the user file is changed and the login seems to be working. Not sure however if the redirect to a 404 is intentional?

**Comment by siSSSou** [comment]
> As a workaround, I just edited it and copy/pasted the hash from the login pw to the api password field.

What is the field name for API password in config.php ?

**Comment by uncovery** [comment]
@siSSSou copy the value from 'passwordHash' to  'apiPasswordHash'

**Comment by Alkarex** [comment]
@siSSSou I guess your problem was not the same. Being disconnected at that step often has to do with badly-behaving password managers, which wrongly autofill the password. See https://github.com/FreshRSS/FreshRSS/issues/1885#issuecomment-390397726

**Comment by Alkarex** [comment]
@uncovery I guess you hit two problems: first some wrong rights, and then a password manager issue (setting the password, even when it is the same than before, will reset the session as well as the API tokens).
Is everything working for you now?

**Comment by uncovery** [comment]
@Alkarex Yeah I would think we can close this one now.
