### ISSUE TITLE
Firefox Subscribe missing FreshRSS port number

### ISSUE THREAD

**Issue by primaeval** [FreshRSS/FreshRSS#1971]
I can't work out how to set the port number for the Firefox RSS Subscribe button.

In the window that shows "Subscribe to this feed using" the FreshRSS option ends up at my server address but without a port.

The value for "browser.contentHandlers.types.6.uri" is "http://userver:8080/i?c=feed&a=add&url_rss=%s" but the "Subscribe Now" button will end up somewhere like "http://userver/i/?c=feed&a=add&url_rss=https%3A%2F%2Fwww.wired.com%2Ffeed%2Frss" without the 8080 port number.

My FreshRSS server is on an Ubuntu Server 18.04 in a docker container at port 8080.

**Comment by primaeval** [comment]
I found the solution. There needs to be a / after the i.
`http://userver:8080/i/?c=feed&a=add&url_rss=%s`
otherwise freshrss redirects but doesn't know it has a docker port mapping.

I was following the example in https://github.com/FreshRSS/FreshRSS/issues/425#issuecomment-258437102

**Comment by Alkarex** [comment]
Sorry for the delay - I was on vacation 😄 - and good you found the solution
