### ISSUE TITLE
Adding Pinboard for Sharing?

### ISSUE THREAD

**Issue by samplereality** [FreshRSS/FreshRSS#1972]
I would love to see Pinboard added to the list of Sharing methods. Pinboard offers a full API, so it's definitely doable, just beyond my skills! Pinboard API: https://pinboard.in/api/.

**Comment by pattems** [comment]
@samplereality I don't have a pinboard account; would you be willing to work with me to test?
https://github.com/pattems/FreshRSS/tree/Issue_1972

**Comment by samplereality** [comment]
Absolutely. Let me know what you need.

**Comment by pattems** [comment]
You can either check out a copy of my repo and use the Issue_1972 branch, or add the following lines in app/shares.php, below the close block for linkedin:
```
	'pinboard' => array(
		'url' => 'https://pinboard.in/add?next=same&amp;url=~LINK~&amp;description=~TITLE~&amp;title=~TITLE~',
		'transform' => array('urlencode'),
		'help' => 'https://pinboard.in/api/',
		'form' => 'simple',
		'method' => 'GET',
	),
```

**Comment by pattems** [comment]
This URL is based off the iPad bookmarklet [here](https://pinboard.in/howto/). They seem to be doing something a little different than the API reference indicates, given that there's not even a title field in the reference, so this is a little iffy.

**Comment by samplereality** [comment]
It works! I modified it slightly, so that the TITLE isn't duplicated in the description field:

```
	'pinboard' => array(
		'url' => 'https://pinboard.in/add?next=same&amp;url=~LINK~&amp;title=~TITLE~',
		'transform' => array('urlencode'),
		'help' => 'https://pinboard.in/api/',
		'form' => 'simple',
		'method' => 'GET',
	),
```

Like the other share options, this opens up a new tab. I wonder if it's possible to pop-up the Pinboard dialogue in a little window, the way the [bookmarklets](https://pinboard.in/howto/) do.

**Comment by pattems** [comment]
Fantastic! I think opening an external page is probably better default behavior, but after the upcoming PR gets merged, perhaps you could open a new issue for popups in sharing? It seems like the sort of thing that would make a great extension, using iframes, maybe.
