### ISSUE TITLE
[Feature Request] Mark articles read on Scrolling (even the last few articles)

### ISSUE THREAD

**Issue by primaeval** [FreshRSS/FreshRSS#1973]
Please could you add some space to the "There are no more articles" section so that you can scroll past the end of the article list and mark them all as read without having to press the button.

This is how Feedly does it even though they managed to break it every summer or two.

**Comment by hharsunen** [comment]
there is also keyboard shortcuts, for this on windows ```shift+r```, see [/i/?c=configure&a=shortcut](https://localhost/i/?c=configure&a=shortcut)

**Comment by primaeval** [comment]
Thanks. I just love the way Feedly does it so I can drink my coffee and eat my sandwich with one hand and just use the mouse to read feeds with the other hand. It saves getting crumbs all over the keyboard. ;)

**Comment by primaeval** [comment]
It might just be this in origine.css
```
#global {
	height: calc(100% - 85px);
}
```

**Comment by primaeval** [comment]
I've proposed a solution in a Pull Request using a 100vh non-breaking space.
https://github.com/FreshRSS/FreshRSS/pull/1974

**Comment by aledeg** [comment]
As mentioned in your PR, I am not sure this should be included in the core. I provided you with a way to handle it in a different way. Please check [my comment](https://github.com/FreshRSS/FreshRSS/pull/1974#discussion_r208945356).

**Comment by Alkarex** [comment]
Should be fixed with https://github.com/FreshRSS/FreshRSS/pull/1980
Tests welcome

**Comment by primaeval** [comment]
Thanks for adding in the fix.
