### ISSUE TITLE
Cannot find library to parse XML & DOM 

### ISSUE THREAD

**Issue by thalhayasir** [FreshRSS/FreshRSS#1981]
I installed the FreshRSS in ubuntu 16.04 when I start the setup i get the following errors in the first screen

Blast! Cannot find a required library to browse the DOM.

Blast! Cannot find the required library to parse XML.

Kindly let me know how I can fix this issue

**Comment by Frenzie** [comment]
That means you're missing the PHP libxml module (and possibly others). On Ubuntu the package name is probably something like `php-xml`.

**Comment by Alkarex** [comment]
@thalhayasir Did you make it work? If not, please see the readme for the list of packages:
https://github.com/FreshRSS/FreshRSS#example-of-full-installation-on-linux-debianubuntu

For Debian / Ubuntu:
```sh
sudo apt install php php-curl php-gmp php-intl php-mbstring php-sqlite3 php-xml php-zip
```

For people with distributions installing even fewer packages by default, see:

https://github.com/FreshRSS/FreshRSS/blob/3306a1679c2570c30d4b662c887b4a71ce147398/Docker/Dockerfile#L5-L6
