### ISSUE TITLE
Auto feed updater script curl error 

### ISSUE THREAD

**Issue by Dryusdan** [FreshRSS/FreshRSS#1982]
Hello :)
It's my third installation of FreshRSS, and this installation and the last, I encounter a problem with auto feeder script. The last installation I found the soluce but I lost these and I not writting where I found it... So I ask you (maybe it's a bug) :) 
I'm on Debian 9, with official packet (no backport), so php version is `7.0.30-0+deb9u1 `.
When I run this command : `php -f /var/www/rss/app/actualize_script.php` the error is printed on terminal : 
```
starting feed actualization at 2018-08-20T15:44:21+02:00
Actualize Dryusdan...
PHP Warning:  curl_setopt() expects parameter 2 to be integer, string given in /var/www/rss.drycat.fr/lib/SimplePie/SimplePie/File.php on line 122
PHP Warning:  curl_setopt() expects parameter 2 to be integer, string given in /var/www/rss.drycat.fr/lib/SimplePie/SimplePie/File.php on line 122
PHP Warning:  curl_setopt() expects parameter 2 to be integer, string given in /var/www/rss.drycat.fr/lib/SimplePie/SimplePie/File.php on line 122
```

But curiously, manual update work fine.

If you have an idea :)

Regard

**Comment by Alkarex** [comment]
Could you please show the `'curl_options'` part of your `./data/config.php` ?

(I am recently back from vacation, and will soon work on FreshRSS again)

**Comment by Dryusdan** [comment]
My curl option is : 
```
'curl_options' => 
  array (
    81 => 0,
    'CURLOPT_SSL_VERIFYPEED' => false,
  ),
```
I'm not sure I have not change this value :thinking:

**Comment by Alkarex** [comment]
Indeed, that looks wrong (the quotes in particular). Please remove the two lines, so it looks like:

```
'curl_options' =>
	array (
	),
```

There is a new mechanism to allow individual feeds to be unsafe, so the those lines are not appropriate any more anyway.

**Comment by Dryusdan** [comment]
Yes, work fine, thank you :D
