### ISSUE TITLE
Feature request : enable more CSS customization on Freshrss header

### ISSUE THREAD

**Issue by GLLM** [FreshRSS/FreshRSS#1983]
Hi all !

I've been tweaking my FreshRSS CSS so that it uses screen estate more reasonably.
I'm still hitting a wall with 2 items : 
* Search box
* Parameters menu

![image](https://user-images.githubusercontent.com/3989573/44350962-f65fdb80-a4a0-11e8-9f29-bc15f62c07c3.png)

I cannot place them on the same level as the main tool bar ... but I'd really like to ( Searchbar & Parameters, in order to get more vertical space for feeds display.

Could something be done on this ?
I believe the way HTML / CSS are currently intertwined makes it impossible to change thoses last 2 elements from the top bar to the one below it.

The logo+title (in blue) could remain here, if _that_ would no _force_ an empty top bar on the right hand side ...

Thanks,
GLLM

Edit : typo and word changes (_italic_)

**Comment by GLLM** [comment]
Hi @Alkarex !
Thanks for flagging my issue :)

A second step could be to be able to change the title + logo location from the top bar to the left side bar

![image](https://user-images.githubusercontent.com/3989573/44572118-2e0da280-a783-11e8-8262-ce150828116c.png)

into

![image](https://user-images.githubusercontent.com/3989573/44572490-3c0ff300-a784-11e8-870d-03a70a0588f9.png)

_Quick mockup. the title background would be balck and the title would be in a light color :)_

This way, no top bar eats screen estate and I can maximize the display !

**Comment by aledeg** [comment]
@GLLM  I like the idea to have the logo as part of the navigation. :+1:

**Comment by Alkarex** [comment]
If you are satisfied by the new theme https://github.com/FreshRSS/FreshRSS/pull/2069 , maybe we can close this ticket?

**Comment by pattems** [comment]
@Alkarex I hope I'm not speaking out of turn here, but I think the idea still has merit. While I'm certainly proud of Swage, it may not be the theme for everyone wanting a more compact header.

I think I've got a pretty good idea about how to go about this that wouldn't involve touching the theme files, and I'll play with it in the upcoming days as I've got time.

**Comment by Alkarex** [comment]
@pattems You are more than welcome. We receive more suggestions than pull requests, so my comment was because we need to prioritise. But with additional help, this feature would be a nice enhancement 😃

**Comment by RichardUUU** [comment]
Does anyone know how to stop the search field from extending/contracting when active/non-active? It's really annoying when trying to edit search terms (in addition to being gimmicky).

**Comment by Frenzie** [comment]
I'm not really sure what I think of it either, but I guess I don't use the search enough to have really paid attention to or thought about it.

For the moment you could put something like this in the CustomCSS extension.
```css
.header .item.search input:focus {
    width: 230px;
}
```
That's for current Origine; it might differ per theme.

**Comment by RichardUUU** [comment]
Thanks Frenzie, before I saw your comment I discovered the CustomCSS extension and found it works when you enter this (to always choose the larger size):

```css
.header > .item.search input {
    width: 350px;
}
```

**Comment by GLLM** [comment]
Solution is fine, thanks. Closing the issue :)
