### ISSUE TITLE
"application/octet-stream" is not working even though w3 says it is valid

### ISSUE THREAD

**Issue by ripley80** [FreshRSS/FreshRSS#1984]
2018-08-22 22:43:08
A feed could not be found at `http://vowe.net/index.rdf`; the status code is `200` and content-type is `application/octet-stream` [http://vowe.net/index.rdf]

I migrated over from TTRSS to FreshRSS. Everything works like a charm besides the above feed. Any ideas?

**Comment by Frenzie** [comment]
Please see https://github.com/FreshRSS/FreshRSS/issues/1721#issuecomment-351204751

**Comment by ripley80** [comment]
Many many thx for your quick reply. Works like a charm :-)
