### ISSUE TITLE
[Request] Wiki : utiliser le CSS pour texte complet

### ISSUE THREAD

**Issue by Draky50110** [FreshRSS/FreshRSS#199]
Salut

La perspective de chopper un flux RSS complet m'intéresse :) mais je n'ai pas trouvé d'explication.

Exemple : http://www.universfreebox.com => dans le code source d'un article, tu as plusieurs fichiers .css, faut prendre lequel ?

Merci :)

**Comment by Alkarex** [comment]
http://doc.freshrss.org/fr/users/05_Configuration/#avance

**Comment by Alkarex** [comment]
* https://freshrss.github.io/FreshRSS/fr/users/05_Configuration.html#r%C3%A9cup%C3%A9rer-un-flux-tronqu%C3%A9
* https://freshrss.github.io/FreshRSS/en/users/05_Configuration.html#retrieve-a-truncated-stream

**Comment by norz** [comment]
> au passage j'ai ajouté une page de wiki :

https://freshrss.github.io/FreshRSS/en/users/04_Subscriptions.html#advanced
