### ISSUE TITLE
Fontname has wrong capitalization

### ISSUE THREAD

**Issue by uncovery** [FreshRSS/FreshRSS#1990]
The code in https://github.com/FreshRSS/FreshRSS/blob/3306a1679c2570c30d4b662c887b4a71ce147398/p/themes/Origine-compact/origine-compact.css#L6

needs to be 
`
	src: url("../fonts/OpenSans.woff") format("woff");`

(capitalized "O") to match the filename in this file: https://github.com/FreshRSS/FreshRSS/blob/master/p/themes/fonts/OpenSans.woff

**Comment by Alkarex** [comment]
Thanks @uncovery 
Would you feel like making a pull request?

I think the whole `@font-face` section below should be just removed, as it is already declared properly in the base theme.

https://github.com/FreshRSS/FreshRSS/blob/3306a1679c2570c30d4b662c887b4a71ce147398/p/themes/Origine-compact/origine-compact.css#L2-L7

**Comment by Alkarex** [comment]
Fixed by @uncovery in https://github.com/FreshRSS/FreshRSS/pull/1992
