### ISSUE TITLE
[Feature Request] Always show unread when showing favorites

### ISSUE THREAD

**Issue by uncovery** [FreshRSS/FreshRSS#1994]
Clicking on the "favorites" star in the main UI should always show unreads and reads as well, or - as a compromise - there should be an option setting where this can be enabled.

**Comment by Alkarex** [comment]
Hello,
Yes, we could add another option (although this might be confusing). Currently, the favourites view obeys the same rule than other views (categories, feeds) controlled by the option *Articles to display*

![image](https://user-images.githubusercontent.com/1008324/44957970-75113b80-aed9-11e8-803d-536e1d2f9d35.png)

**Comment by uncovery** [comment]
The issue here is mainly what happens when you select the favorites on the left menu, not what happens when you click on star in the top menu. While the top menu should surely redefine the "filter" for the currently displayed articles, the left "Favorites" menu entry should show all entries by default. There is the number of favorites written, but when I click on it, it shows only those that are unread. That seems to me a bit like a broken logic.

Even the "EasyRSS" android app does it that way. When you chose "Starred items", it will show all, no matter if read or unread.

**Comment by uncovery** [comment]
So the option should entry should be "Favorites folder displays:" and the options to choose from would be "All favorites", or "read/unread according to top menu" or something along these lines.

I'd love to help with this, but I am afraid I have no idea where to start.

**Comment by uncovery** [comment]
What I figured out that would need to be done so far:

- add a config dropdown here: https://github.com/FreshRSS/FreshRSS/blob/master/app/views/configure/reading.phtml#L49

**Comment by Alkarex** [comment]
@uncovery Yes indeed. Would you like to try to make a PR?

**Comment by uncovery** [comment]
@Alkarex  Well only adding the options will not enable the function, right? What else needs to be done where to change how the favorites folder is displayed?

**Comment by Alkarex** [comment]
@uncovery Haha yes indeed. The feature itself should be quite easy to code, around here:

https://github.com/FreshRSS/FreshRSS/blob/f5215e5966b4bf952bb6d8d4bb3168b78ae5b7d8/app/Controllers/indexController.php#L174-L183

**Comment by rezad1393** [comment]
no update on this?

**Comment by aledeg** [comment]
@rezad1393, @uncovery There is an option in the reading configuration page to achieve that!

![Screen Shot 2020-12-29 at 09 33 50](https://user-images.githubusercontent.com/3056148/103291189-2f85b000-49b9-11eb-9d14-e164aadd0b4e.png)

**Comment by Alkarex** [comment]
Was implemented in 1.16.0 https://github.com/FreshRSS/FreshRSS/pull/2766
