### ISSUE TITLE
QNAP auto refresh and proxy settings

### ISSUE THREAD

**Issue by jeffreyswiggins** [FreshRSS/FreshRSS#1998]
So i installed it as an app from the QNAP Club and got it setup and working fine, but really would like it to auto refresh or "actualize" every 15 minutes.  Also would like to have it run through my privoxy server if possible.

How do I get the auto actualize and proxy setup on a QNAP installation.  I found the directory where the app is locate and ran the actualize_script.php > /tmp/FreshRSS.log 2>&1 and nothing happened.

**Comment by Alkarex** [comment]
Hello,
I am not familiar with QNAP, but I am pleased to see there is a maintained package for FreshRSS:
* https://www.qnapclub.eu/qpkg/370
* http://forum.qnapclub.fr/topic/8888-freshrss/

Could you please try to run the same thing again, but without the redirections, and provide the output?

```sh
cat /tmp/FreshRSS.log
php actualize_script.php
```

**Comment by jeffreyswiggins** [comment]
so i ran the actualize_script.php alone and got this

[/share/CACHEDEV2_DATA/.qpkg/FreshRSS/freshrss/app] # ./actualize_script.php
-sh: ./actualize_script.php: /usr/bin/php: bad interpreter: No such file or directory

maybe i need to install a php interpreter??

**Comment by Alkarex** [comment]
Either PHP is not at the standard path, or it is not available from command line, or it is not installed.

Could you please try:

```sh
which php

php -f actualize_script.php
```

**Comment by jeffreyswiggins** [comment]
So which pho returns nothing.  I had already installed Entware on the NAS so i found an “opkg  install php7” command that installed php7 however the actual ice command still states pop not in the /use/bin directory so my guess is the nature of the NAS being customized UNIX OS the pho is being installed elsewhere.  I really like the web interface of this but I am not going to chase this rabbit any further down the hole.  I have a desktop RSS reader that I have been using for years and since that is my main computer for Hackett, sonar, radar, privoxy and other things I have to remote console it a lot anyways so will just continue using that desktop client for now and if I travel and want to use the ease of FreshRSS webpage i might open it up to my router and then i can see things easier.  Just to much chasing of my tail on other things for this one
