### ISSUE TITLE
[Feature Request] 3 panes view

### ISSUE THREAD

**Issue by nicofrand** [FreshRSS/FreshRSS#2002]
HI,

I am currently using Akregator but would like to switch to a web-based RSS reader and I have been hearing a lot of good of FreshRSS!

One thing that I like a lot in Akregrator is the "3 panes" view, vertically : 1 pane for the list of feeds, 1 for a feed's articles list, 1 for the article content. I would really miss this.

This is an old capture but here is an example:

![3 panes view, vertical](https://news.softpedia.com/images/reviews/large/Akregator_002-large.png)

Some prefer it like this:
![3 panes view, horizontal](https://cn.pling.com/img//hive/content-pre1/15621-1.jpg)

I tried the demo and asked on Twitter etc. but could not find anything about it in FreshRSS (nor any theme like this), hence this feature request. 

Do you think that would be hard to do, for someone who never read the code of FreshRSS? Would that be only a new theme or would it affect the core too?

**Comment by nicofrand** [comment]
Hi @Alkarex,

many thanks for your asnwer and sorry for my late reply! 

I'm having a hard time to see how "just" CSS would do it. I tried a few things though but could not reach something usable.

I'd need the left pane (articles list) and the right pane (article content) to be scrollable independently and I don't see how it could be done (only in CSS) since the content is inserted as a sibling of the title.

I'd be simple to do in JS though (and I'd be ok with it). Can themes insert JS too? Or is it something an extension would do?

Sorry if I ask dumb questions through this ticket, but I don't think there is an IRC channel or Matrix room?

**Comment by nicofrand** [comment]
[Edit]: Actually it seems to allow one to add JS, this could work for me but not for all users (I am probably not the only one wanting a 3 panes view). I'll create an extension though.

I just found https://github.com/FreshRSS/Extensions/tree/master/xExtension-CustomJS I belive this answers my need!

Please feel free to close this ticket, otherwise I'll close it once I found time to create this plugin.

**Comment by Alkarex** [comment]
Hello,
I believe a full new theme would be better (see https://github.com/FreshRSS/FreshRSS/tree/dev/p/themes ) than using the CSS extension.

**Comment by nicofrand** [comment]
That would not be a CSS extension (this cannot be done properly through CSS only) but a JS extension.


Le 21 oct. 2018 21:13, Alexandre Alapetite <notifications@github.com> a écrit :

Hello,
I believe a full new theme would be better (see https://github.com/FreshRSS/FreshRSS/tree/dev/p/themes ) than using the CSS extension.

**Comment by nicofrand** [comment]
Hi @Alkarex,

I gave it a try and managed to get something that fits my needs. This is a bit hacky but it works (did not test really it in production though). It needs javascript to be enabled.

The code: https://framagit.org/nicofrand/xextension-threepanesview

A preview:

![freshrss](https://user-images.githubusercontent.com/3419050/49391457-06d45300-f72c-11e8-891a-f8c9fad1dbf2.png)

**Comment by Alkarex** [comment]
@nicofrand Congrats, this looks very good 👍 
Please submit the URL of your extension to https://github.com/FreshRSS/Extensions/blob/master/extensions.json so it can be advertised in FreshRSS.
It could be nice to mature it a bit an include this view in the core of FreshRSS

**Comment by nicofrand** [comment]
There are things to polish though like disabling it when in reader/global mode.

I am struggling with the BlueLagoon theme though, the header is supposed to take 60px but the image inside it already thakes 60px, + the margin are 0.5 on both top and bottom… This is creating a useless scrollbar and my pane does not have the right height.

Do you know if I could contact its author through IRC or something like that?

**Comment by Alkarex** [comment]
@nicofrand Contact information on https://github.com/FreshRSS/FreshRSS/blob/dev/p/themes/BlueLagoon/README.md . I hope @misterair is still around :-)

**Comment by ghost** [comment]
I don't understand the problem. In the screen the template look great.
(Y'a d'la gueule ce thème. Fier, tout ça...)

You can fork or make a pull request with a fix. Sadely I don't use FreshRSS anymore

**Comment by nicofrand** [comment]
The screen does not show the BlueLagoon theme.
The issue is that the header takes around 80px instead of 55 or 60px like defined in the CSS.

I'll try to make a MR.
