### ISSUE TITLE
Though validated via W3C, SimplePie is not able to find a feed on a specific page.

### ISSUE THREAD

**Issue by chemical1979** [FreshRSS/FreshRSS#2004]
I recently migrated from Feedly to FreshRSS and while moving the feeds, I stumbled on one feed that I read. SimplePie posted in my logs:

`2018-09-07 19:20:44 A feed could not be found at https://vowe.net/index.rdf; the status code is 200 and content-type is application/octet-stream [https://vowe.net/index.rdf]`
`2018-09-07 19:20:35 A feed could not be found at http://vowe.net/index.rdf; the status code is 200 and content-type is application/octet-stream [http://vowe.net/index.rdf]`
`2018-09-07 19:19:49 A feed could not be found at https://vowe.net/; the status code is 200 and content-type is text/html; charset=UTF-8 [https://vowe.net]`

The interesting thing is, that the W3C feed validator [seems to see no real problem](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fvowe.net). (I already got in touch with the site author regarding these minor findings, but the should not cause the issue)

As I'm not really sure if this is a problem of FreshRSS, SimplePie or the web page itself, I start my bug journey here with this issue and maybe someone with more php debugging-abilities can help me :-)

**Comment by chemical1979** [comment]
https://github.com/FreshRSS/FreshRSS/issues/1721#issuecomment-351204751 - adding #force_feed at the end of the URL fixed the issue for me.
Maybe the parser should be a little more relaxed regarding this? :-)

**Comment by Alkarex** [comment]
`https://vowe.net/index.rdf` works fine and without warning/error from my FreshRSS instance. It returns the proper MIME type `application/rss+xml` so my guess is that it was a temporary misconfiguration on the site.

**Comment by chemical1979** [comment]
Indeed I was talking to the site owner and he eventually changed the content type to the recommended value of the W3C feed validator yesterday evening. :-)
