### ISSUE TITLE
Error when updating via built-in updater [1.11.1 => 1.11.2]

### ISSUE THREAD

**Issue by kruug** [FreshRSS/FreshRSS#2012]
Updating from 1.11.1 to 1.11.2.

`The update process has encountered an error: Git error: Updating 3306a167..44bd07e5`

Hosting:
 - Debian 9.4 (stretch)
 - nginx 1.10.3
 - php 7.0.30-0+deb9u1
 - mysql Ver 15.1 Distrib 10.1.26-MariaDB

**Comment by Alkarex** [comment]
Thank you for the bug report @kruug 
My guess is that the git autoupdate was broken by https://github.com/FreshRSS/FreshRSS/issues/1942

Could you please try the following command, and try again?
```sh
cd ./FreshRSS/
rm data/PubSubHubbub/feeds/index.html data/PubSubHubbub/index.html data/PubSubHubbub/keys/index.html data/users/_/index.html
```

If that does not help, could you please provide the output of:

```sh
git status
```

Another approach, which should solve the problem:

```sh
cd ./FreshRSS/
# Clean untracked files (while keeping user files)
sudo git clean -f -d
# Re-apply access rights
sudo chown -R :www-data . && sudo chmod -R g+r . && sudo chmod -R g+w ./data/
```

**Comment by kruug** [comment]
@Alkarex 

`rm data/PubSubHubbub/feeds/index.html data/PubSubHubbub/index.html data/PubSubHubbub/keys/index.html data/users/_/index.html`

This command worked.  Thank you!

**Comment by Alkarex** [comment]
git auto-update now performs a `git clean -f -d -f` to avoid such problems in the future https://github.com/FreshRSS/FreshRSS/pull/2036
