### ISSUE TITLE
Improving user queries

### ISSUE THREAD

**Issue by marienfressinaud** [FreshRSS/FreshRSS#2015]
User queries are generally hard to understand. First, accessing user queries from the "admin" link is very confusing since you are welcomed with a placeholder and no explanations to create a query or even to start to understand what is a user query.

Then, you can't understand what's the purpose of "Add a query" before clicking on it (and even then, it's not totally understandable).

Finally, it's very confusing to click on the "delete" cross next to the user queries, refreshing the page, and see them again (you need to submit before but it's not clear at all!). Same feedback applies to sharing options. The "cancel" button is not very useful neither and we could imagine to drop it.

**Comment by Alkarex** [comment]
One of the improvements I really want is a new UI for the search, to help with advanced search options. Maybe there could be some synergies with user queries.

**Comment by Alkarex** [comment]
It would also be nice to offer more options in user queries, such as with an option to expose them by API.

**Comment by zan73** [comment]
Modification of existing queries and multi-string searches (with OR/AND syntax in the same manner as major search engines) would be very welcome!

**Comment by Alkarex** [comment]
@zan73 `OR` is already supported :-) `AND` is the default. Double quotes are also working, but only for search expressions like `intitle:"Hello World"` (I thought we had them working everywhere, but apparently not - I will have to look back into it, please open a new issue if there is not one already)

**Comment by aledeg** [comment]
See #2216
