### ISSUE TITLE
Unknown error with feed from pipa.io

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#2019]
When I try to add a rss feed from pipa.io, I get an unknown error.
With this one for example : 
https://feed.pippa.io/public/shows/5af9be2f2590f81e4ce2190f

With FreshRSS 1.11.2

**Comment by Alkarex** [comment]
The MIME type of this feed is wrong (`application/xhtml+xml` instead of `application/rss+xml`). This should be fixed on their Web site (maybe you could write them).
In the meantime, please try with `https://feed.pippa.io/public/shows/5af9be2f2590f81e4ce2190f#force_feed`

**Comment by ghost** [comment]
Oh ok I didn't know, thanks for the answer :)
