### ISSUE TITLE
Newbie Faqs -> feedly switcher

### ISSUE THREAD

**Issue by kaktux** [FreshRSS/FreshRSS#2024]
hi there,

i am currently looking for self-hostable alternatives to feedly.
So - as i tried out the demo (btw. - the login data is missing: i found it by searching myself in a twitter of yours) - i got some questions which i couldn't find answers to myself.

1. There is a "favorites" option. Is there also a "read later" option? Favorites in my eyes are "saved" articles - while read later simply is something like "don't want to now".
2. Can you add boards - where you can store interesting news for later - and maybe share those boards with different people/different ways
3. How do filters work i found them when clicking in front of feedname - but couldn't figure out much more
4. Can you label/tag articles? (categorie or so) - guess thats kind of similar to boards
5. You can share (eg mailwallabag linkedin) - but is there a way to publish interesting news (again similar to boards or tag xyz vis rss (open+private) ?

As i could not find a forum or similar - i hope this is the right place to ask

**Comment by Alkarex** [comment]
Hello @kaktux 

I plan to add custom tags pretty soon, hopefully in the next version 1.12. This should help for your points 1, 2, 4, 5.

1. No "read later" currently (custom tags coming soon), but indeed favourites (which is a kind of read-it-later). In personally save and share my important articles in Shaarli.

2. You can access and share any category / feed / search / favourites by RSS (you need to set a token in the configuration to enable this feature for external users). Custom tags will further improve the options.

3. Filters are just some kind of saved searches (e.g. with a combination of keywords, tags, date...).

4. No custom tags yet, but I plan to implement that pretty soon.

5. Sharing via RSS is what we can offer, which will become even more powerful with custom tags.

**Comment by kaktux** [comment]
thx a lot for the answers.

Also i got some suggestions (and another newbie question)

First:
i am currently trying to install freshrss on a linux vm (virtualbox) using turnkey linux core (basically debian 9 with some additions like webmin).

it works fine with the very good documentation at
https://github.com/FreshRSS/FreshRSS (Example of full installation... Debian)

But here are the stuff i am struggeling with and that may need some newbie explaining ;)
1.
"Access control
It is needed for the multi-user mode to limit access to FreshRSS. You can:
use form authentication (needs JavaScript, and PHP 5.5+ recommended)
use HTTP authentication supported by your web server
See Apache documentation
In that case, create a ./p/i/.htaccess file with a matching .htpasswd file."

It probably is overkill to explain in detail what has to be done there - but i am mainly not sure what is meant by "It is needed for the multi-user mode to limit access to FreshRSS". Does it mean it is needed if more then the primary users will use freshrss - and limit their rights not to have admin possibilities?

Another thing is during installation of freshrss:
2. when setting your account the password hast to be entered once. In my opinion a password-check would be a good thing: meaning entering the password twice and checking it for typos.

3. Database settings: i am not really sure what the host line is for and also what the prefix of the db is. I simply created a new database with my user ;) - thats what i know. Couldn't find the prefix for that nor do i know what host i should enter a) if i use a local machine (install is at dhcp-given-ip/FreshRSS) b) if i would install it on a webhost).

Edit - on my vm entering "localhost" in the host line and leaving table prefix empty works.

So you see: newbie.

Anyway - still quite simple to install so far and a quite unusual good howto


This work

**Comment by Alkarex** [comment]
@kaktux 

1. Just pick `form` access - the typical Web form where one types a username+password. This is what most users like. The user you create at install time will have additional rights, while users created later will be simple users.

2. Yes indeed, but low priority because the person installing FreshRSS is always able to manually reset the password in case of error. Plus, password managers are good :-)

3. The easiest is to pick SQLite for a database, so you do not have to worry with database parameters. The performances with SQLite will be fine up to quite many articles, and if you end up with many users, each gets its own SQLite database, so this scales OK.
Anyway, `host` is when your database (MySQL, PostgreSQL) is on another server, and in your case, it is simply `localhost`. `prefix` is to keep a structure when you have several solutions running in the same database (say: FreshRSS and WordPress), and you can put any value you want, with the suggestion being `freshrss_`.

You can also give a try to our Docker image, which is very light and ready to run.

**Comment by Alkarex** [comment]
BTW, I am working on *custom tags* today ;-)

**Comment by kaktux** [comment]
again thx for the fast answer.
I started my switch from feedly today. Freshrss is a bit different - but with playing around i start to find more and more functions.

Finally i have 2 suggestions i found while starting the switch (3/4 there - hardest thing will be the read later from feedly as those can't be simply ompl transferred).

Anyway: my suggestions are a "recently read" list - where you can see something like the last 100 articles you clicked on. I don't know about others - but i have some general news feeds where i mostly only read the title and maybe the first lines - while i got others that i read whole. For the "fast-browse-through" at least i sometimes click to fast and my brain tells me sometime later "maybe that would be nice to read".

Another thing - which is quite on the same topic: magazine view - where you can see and read the headline and the first few lines instead of headline only or whole text - and you can flip+mark read those news fast.

anyway: first day with freshrss - and i like it so far. To be honest it looks better now then the first impression was. 
It runs for now on postgres - but its for the switch - and a local vm install which i will use some time (maybe even transfer that to a vm in a nas (qnap)) - but even if i switch (and/or reinstall) somewhere else and also switch db - it doesn't look like FreshRSS will make it hard to export+import everything i want (unlike feedly...)

**Comment by Alkarex** [comment]
* For the list of "read" articles: (I think we have an issue about that already, but I cannot find it, so feel free to open a new one). This would require that we make it clear when an article is properly read or skipped. A bonus would be to make it work with the mobile applications through our APIs.

* For the *magazine view*: Interesting idea, which might be doable with a new CSS theme. We are also discussing adding other views such as thumbnails.

You can see the work on *custom labels* on https://github.com/FreshRSS/FreshRSS/pull/2027

**Comment by Alkarex** [comment]
Custom labels implemented in https://github.com/FreshRSS/FreshRSS/pull/2027
Tests welcome

**Comment by kaktux** [comment]
thx for the quick replay and your efforts.
btw. - trying around a bit i got a different perspective on read later now.
freshrss should focus on rss features - read later functions can be done by software specific for that. And with e.g. wallabag beeing open source there are already self-hostable options for that.
Same goes for adding content via rss-bridge or similar.

So i would rather add good integration then reinvent the wheel (This also came to me as i recently installed nextcloud and read about the wishes of some users (asking for features that in my opinion are not in the right place). But thats just my opinion.

Anyway - just ended my local "tryout" phase in a vm - and installed freshrss on a webhoster (this time choosing sqlite). Simply read all unread - exported feeds + reimported in new installation. Went smoothly so far.

**Comment by Alkarex** [comment]
Thanks for the feedback :-)
