### ISSUE TITLE
Dev : bookmarklet not working anymore with port 80

### ISSUE THREAD

**Issue by Draky50110** [FreshRSS/FreshRSS#2031]
Hello.
Have updated to "last" dev commit (Latest commit 21e2409 20 hours ago) and bookmarklet gives a loading page and loads nothing.

URL : javascript:(function(){var%20url%20=%20location.href;var%20otherWindow=window.open('about:blank','_blank');otherWindow.opener=null;otherWindow.location='https://www.xxx:80/frss/p/i/?c=feed&a=add&url_rss='+encodeURIComponent(url);})();

Works if I remove the :80 in the URL.

**Comment by Alkarex** [comment]
Could you please check what you have in `./data/config.php` for your `base_url` variable?

**Comment by Draky50110** [comment]
variable is empty : =''

**Comment by Alkarex** [comment]
Do you have a proxy in front of FreshRSS?

**Comment by Draky50110** [comment]
Nope, just normal shared webhost.
Why does FRSS append :80 in this URL in bookmarklet ?
Cron jobs works without it.

**Comment by Alkarex** [comment]
Could you please put this file on your server, and give us the output?

`server-variables.php`:

```php
<pre>
<?php
$keys = array(
	'HTTPS',
	'HTTP_HOST',
	'HTTP_X_FORWARDED_PORT',
	'HTTP_X_FORWARDED_PROTO',
	'REQUEST_SCHEME',
	'REQUEST_URI',
	'SERVER_ADDR',
	'SERVER_NAME',
	'SERVER_PORT',
	'SSL_TLS_SNI',
);
foreach ($keys as $k) {
	echo $k, ' => ', isset($_SERVER[$k]) ? $_SERVER[$k] : null, "\n";
}
```

**Comment by Draky50110** [comment]
https://gilles.wittezaele.fr/server-variables.php

**Comment by Alkarex** [comment]
https://stackoverflow.com/questions/4433229/incorrect-port-number-returned-by-serverserver-port

**Comment by Draky50110** [comment]
https://gilles.wittezaele.fr/phpinfo.php
Using shared webhosting, I just choose the PHP version in admin.

Switched to 7.1.21 with same result.
In fact, any request to http is automatically redirected to httpS, it is an option in webhost.

**Comment by Alkarex** [comment]
Actually, we could maybe guess a little better. I will prepare a patch.

**Comment by Alkarex** [comment]
Before changing your `base_url`, could you please test https://github.com/FreshRSS/FreshRSS/pull/2037 ?
The easiest is to just manually add the following two lines: https://github.com/FreshRSS/FreshRSS/pull/2037/files

**Comment by Alkarex** [comment]
Thanks for the feedback 👍

**Comment by Alkarex** [comment]
Follow-up of https://github.com/FreshRSS/FreshRSS/pull/1013
