### ISSUE TITLE
update via cron : no way

### ISSUE THREAD

**Issue by Unixware** [FreshRSS/FreshRSS#2034]
There is no way to update the feeds from cron, I used both the /etc/cron.d script  even set a crontab as root. I always getting empty feeds then I need to "manually" update from the update button.
System : raspbian w/ nginx 

just to add that update via command line (default user "pi") works , should the crontab be run via that user instead of www-data ? thx

**Comment by Unixware** [comment]
never mind, I figure what's going on. user www-data  has no permission to write on /tmp so job failed, fucking hell

**Comment by Unixware** [comment]
looks like I spoke too soon.. well, crontab script works now, but the update does not bring new feeds -I can see the feed url has articles but no articles are being updated, so update process is bit rubbish

**Comment by Alkarex** [comment]
Hello,
There is a maximum refresh frequency at global level, and at feed level, so not all feeds are necessarily queried at each cron run.

What database are you using?

1. Re-apply the correct access rights. Example:

```sh
cd ./FreshRSS/
sudo chown -R :www-data . && sudo chmod -R g+r . && sudo chmod -R g+w ./data/
```

2. There might be some locks in `/tmp/*.freshrss.lock`, which you can remove

3. Make sure you run with the same user than your Web server (e.g. `www-data`)
    * Example for Debian-like https://github.com/FreshRSS/FreshRSS#example-on-debian--ubuntu

4. Look at your logs (FreshRSS log and cron output)

**Comment by Unixware** [comment]
HI, 

d/base Its MySQL 

>There is a maximum refresh frequency at global level

bingo, do you mean the : 
"Do not automatically refresh more often than ...." option ?
was 1hr by default, I set it to 20min and I have better sync. 
Sorry to say, but Its a bit confusing setting as its located under "Archiving" , well better now I though the OS started to give up the ghost :) , thanks for the help!
