### ISSUE TITLE
Add Feed via Fever API

### ISSUE THREAD

**Issue by Wdavery** [FreshRSS/FreshRSS#2039]
I use FreshRSS almost exclusively from native apps, not the web. However I cannot add feeds from any of those apps which are connect via the Fever API. Is that a limitation of the API?

**Comment by Alkarex** [comment]
Hello,
Our Google Reader API offers this option with compatible clients, but indeed, the Fever API does not seem to expose these features:

https://feedafever.com/api
> The public beta of the API does not provide a way to add, edit or delete feeds or groups

I do not have the possibility to test any Fever-compatible client, so could you please check if any of the apps you have tried offers a user interface to add feeds? If yes, we can easily add the corresponding function on the server side.

**Comment by Alkarex** [comment]
Apps such as Fiery Feeds, Unread, Readkit, and Reeder-3, all already support a Google Reader-like API (for e.g. working with Feedly, The Old Reader...), in addition to the Fever API. https://github.com/FreshRSS/FreshRSS/pull/1836#discussion_r175288194
The developers of those apps would just have to allow setting a custom server, i.e. a relatively minor change, to work with FreshRSS through the more powerful Google Reader-style API.

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/1836#discussion_r175288194

**Comment by Alkarex** [comment]
Maybe Unread could be motivated to do so, if this is not what they already have in preview https://twitter.com/unread_app/status/1039930604559708161

The next version of FreshRSS will also expose custom tags through the Google Reader API (another example of feature not available through Fever API). https://github.com/FreshRSS/FreshRSS/pull/2027

**Comment by Wdavery** [comment]
Reeder 3 is the app I have been using on macOS, I'll contact the developer of that! Thanks for the quick and informative help. FreshRSS has been great for me!
