### ISSUE TITLE
[Dev] Création utilisateur : message impossible mais créé qd même

### ISSUE THREAD

**Issue by Draky50110** [FreshRSS/FreshRSS#2042]
Bonjour.

J'ai voulu créer un utilisateur.
J'ai entré le nom "demo" et j'ai eu un message comme quoi l'utilisateur ne pouvait pas être créé.

Hors, il apparaît bien ensuite dans la liste des utilisateurs pouvant être supprimé.

De plus, si j'essaye de m'identifier, le cookie semble bien créé mais le chargement se lance sans aboutir et rien ne s'affiche...
Je suis obligé de relancer FreshRSS via la navigation privée ou autre navigateur pour supprimer cet utilisateur.

Enfin, il semble impossible d'utiliser par exemple le point pour avoir des utilisateur du genre prenom.nom je ne sais pas si c'est voulu.

Version 1.11.3-dev de ce matin

Merci.

**Comment by Draky50110** [comment]
Pour info, aucun souci sur la 1.11.1 et 1.11.2 (testé sur une autre instance).

**Comment by Alkarex** [comment]
Bonsoir,
Est-ce que c'était par l'interface Web, ou CLI ?
Est-ce que le problème persiste avec d'autres noms d'utilisateurs ?
Est-ce qu'il y a quelque chose dans les logs (de l'utilisateur admin, et/ou de l'utilisateur créé) ?
Voir dans `./FreshRSS/data/users/*/log.txt`

**Comment by Draky50110** [comment]
Alors, il y a un souci MySQL.
Déjà, pas de log dans le répertoire de l'utilisateur créé, juste les fichier config.php et config.php.bak (?) et j'ai un répertoire "_" (underscore) dans le répertoire des "users" (?)...

Côté log.txt dans l'utilisateur principal, voici le message juste après avoir créé l'utilisateur : 

[Sun, 14 Oct 2018 10:07:48 +0200] [error] --- SQL error: Table 'XXX.freshrss_pouetpouet_feed' doesn't exist

L'utilisateur est "pouetpouet" et si j'essaye de me logguer avec, ça charge sans fin.

Création par interface Web.

**Comment by Alkarex** [comment]
@Draky50110 Merci pour le test. Devrait être corrigé dans https://github.com/FreshRSS/FreshRSS/pull/2047

**Comment by Alkarex** [comment]
Fusionné dans /dev. Pourriez-vous réessayer ?

**Comment by Draky50110** [comment]
Testé, tout est ok.

Merci :)

**Comment by Alkarex** [comment]
Super, merci pour le test :-)
