### ISSUE TITLE
Sync Error with iOS App "Fiery Feeds"

### ISSUE THREAD

**Issue by benbeton** [FreshRSS/FreshRSS#2043]
Hi,

I'm using an awesome RSS Reader called "Fiery feeds" on iOS.
After setting up the API password and doing the first sync (this one works) I never get it to sync again.

According to the App dev, the logs from Fiery Feeds shows nothing wrong. 

The only thing I can see Is the following in my error_log_apache:

`[Fri Oct 12 21:21:54 2018] [error] [pid 7222] mod_proxy_fcgi.c(834): [client 134.3.0.0] AH01071: Got error 'PHP message: PHP Notice:  session_start(): ps_files_cleanup_dir: opendir(/var/lib/php-sessions) failed: Permission denied (13) in /.../freshRSS/lib/Minz/Session.php on line 18\n'`

any idea what this could be?
the install check says everything is fine (green)

FreshRSS Master
Fiery Feeds 2.1.1
PHP 7.1.23

**Comment by Alkarex** [comment]
Hello,
I do not think this is related to FreshRSS, but looks more like a PHP configuration issue.
See e.g. https://stackoverflow.com/questions/2904862/issues-with-php-5-3-and-sessions-folder

What OS do you use for your server?
Do you observe a similar problem when logging in and out of your Web interface?

A difference in the case of the API is that we do not use cookies.

https://github.com/FreshRSS/FreshRSS/blob/afa90208be62ba1c4151bc262a74f871da05cbe9/p/api/fever.php#L28-L30

https://github.com/FreshRSS/FreshRSS/blob/afa90208be62ba1c4151bc262a74f871da05cbe9/lib/Minz/Session.php#L17-L18

**Comment by Twilek-de** [comment]
I have seen this happen three times now (I am using almost the same setup. I am using debian testing on the server). I thought that it maybe happened after I reset my passwords (to the same passwords alas). The only thing I could do then is to delete the account in fiery feeds and readd them. Right now they are working again.

**Comment by Twilek-de** [comment]
Nah not the password reset. Just stopped working again. Fiery feed hangs on "Uploading changes". I don´t see apache or FreshRSS errors, it just stops working.

**Comment by Alkarex** [comment]
I do not have any Apple device to test, unfortunately, so additional debug information is welcome.
If possible, try to favour clients using our Google Reader API, which is more efficient and exposes more features.

**Comment by Twilek-de** [comment]
I have contacted the author of Fiery Feeds as the programm explicitly offers FreshRSS support. Maybe he´ll know what´s the problem. Which IOS News Readers do support the Google Reader API??

**Comment by Alkarex** [comment]
I am not aware of any client - let alone open source client - on iOS, which would support the Google Reader API from a custom server. However, many iOS clients do support the Google Reader API but without providing the option to change the server, since it is the type of API used for back-ends such as The Old Reader, Innoreader, Feedly, etc. (with some slight variations). So it would not be so difficult for them to allow the option of typing a custom server.

On my side, I would be interested in more logs. It would be possible to enable more precise logs, inspired from:

https://github.com/FreshRSS/FreshRSS/blob/9897086e8cb4a34aa0b2fedde2f34f52209b238b/p/api/greader.php#L88-L110

(I can prepare something, if you are willing to test a bit more)

I think that it is best to provide a link to a working test instance when contacting the developer of a client, so they do not have to install one themselves to test.

**Comment by Twilek-de** [comment]
Well I will wait what he has to say to the log. If I can test something just tell me what to do and where to send the log data.

**Comment by Alkarex** [comment]
Please check https://github.com/FreshRSS/FreshRSS/pull/2063 , which should generate more logs.
Just paste your logs here (after replacing any confidential information) or [send then to me privately](https://alexandre.alapetite.fr/cv/).

**Comment by Twilek-de** [comment]
I have added the debug code to fever.php. Where should the extra logging info show up? It is not in the log of the admin.

**Comment by Alkarex** [comment]
It is supposed to be in `./FreshRSS/data/users/_/log_api.txt`

**Comment by Twilek-de** [comment]
Found it and as the old AOL saying goes You got mail.

For those logs I deleted the FreshRSS Account in Fieryfeeds and readded it. This initial sync went well. Then I tried to manually resync and it got stuck. So whatever causes the problem should be in there.

**Comment by Twilek-de** [comment]
The author of FF was able to reproduce the behaviour with his own device and is now looking into it.

**Comment by Alkarex** [comment]
It looks like Fiery Feeds enters an infinite loop with `/FreshRSS/api/fever.php/?api&items&since_id=566575407`

It could be related to the fact that this `since_id` looks like a 32-bit integer, while FreshRSS uses 64-bit.

**Comment by Twilek-de** [comment]
I got the answer that that was exactly the problem and that it will be fixed in the next FF update. Thanks again for the excellent support @Alkarex and also to Lukas Burgstaller the author of FF.

**Comment by benbeton** [comment]
thank you all for the help, I'll test the new version when its available on TestFlight!

**Comment by Alkarex** [comment]
Closing, but feedback welcome, when there is any news

**Comment by user858753257** [comment]
Hi , 

Short question :  which settings have you used to get FF working ? 

I used the URL with ....fever.php . 


Which login credentials should I use ? The admin oder the api key ?

**Comment by Twilek-de** [comment]
I used the same URL as to the web interface without any direct reference to a php file and then my username and password.

**Comment by Alkarex** [comment]
@F3000 It should be your API password. Depending on the apps (versions), you might have to provide the full API URL (ending with e.g. greader.php or fever.php depending on the chosen API)

**Comment by user858753257** [comment]
Thanks didn’t work for me : 

@Alkarex shoud I open a new issue for that ? 



I have tried following server URL‘s: 

https://rss55.uber.space/fresh
https://rss55.uber.space/fresh/p/i/  (webui)

When I look into your Doku I should use this : 
https://rss55.uber.space/fresh/api/fever.php



I have tried both with user: admin password : admin password 


And : 

User : admin password : api password 


In FF I get with all combination this error :
![D38FF759-81A6-40F1-AC01-EDD5D464E2D3](https://user-images.githubusercontent.com/8161283/71544016-434ba000-297a-11ea-9be9-f86636ef9384.jpeg)

I hope you can help me

**Comment by user858753257** [comment]
When I click on the little text after the api Passwort field I see following : 
What does the “Key symbol” button on the web ui do ? 

Is this critical ? 

![A5050247-E441-465E-99BC-9BC154A277F0](https://user-images.githubusercontent.com/8161283/71544110-485d1f00-297b-11ea-8cbf-468b7f18a90a.png)

**Comment by Alkarex** [comment]
@F3000 It would be good to fix those warnings. In `./freshrss/data/config.php`, you should have a line like:

```php
'base_url' => 'https://rss55.uber.space/fresh/p/',
```

Currently, your Fever API is https://rss55.uber.space/fresh/p/api/fever.php but if you can, it is better to avoid exposing your `/freshrss/p/` in your URL, and instead use a sub-domain such as https://freshrss.example.net/ or a folder alias such as https://example.net/freshrss/ (instead of ~~https://example.net/freshrss/p/~~ ). Check https://freshrss.github.io/FreshRSS/en/admins/10_ServerConfig.html  and https://freshrss.github.io/FreshRSS/en/admins/03_Installation.html

**Comment by user858753257** [comment]
@Alkarex 

many thanks for helping :)
https://rss55.uber.space/fresh/p/api/fever.php is working fine . 

For the other things I open a separate ticket
