### ISSUE TITLE
Embed.ly not inserted

### ISSUE THREAD

**Issue by alfureu** [FreshRSS/FreshRSS#2050]
I have a strange issue with feeds where there are other media (Twitter posts, YouTube videos, etc.) embedded with the service [Embed.ly ](https://embed.ly/) not showing up in the RSS feed articles. I wonder whether this is a bug at the FreshRSS side or at the website itself... The articles otherwise are presented properly, but the embed.ly content is missing.

**Comment by Alkarex** [comment]
Hello,
Could you please provide an example of RSS feed?
It might be related to CSP rules.

**Comment by alfureu** [comment]
Sure, the feed in my case is [https://444.hu/feed](https://444.hu/feed)

**Comment by Alkarex** [comment]
I believe it should be possible for them to somehow rework their code (with or without Embedly) to use an iframe instead of inline foreign scripts.

**Comment by Alkarex** [comment]
At least they should put a fallback value in their `<a>...</a>` so you can see something and click on a link when Embedly is not working.

**Comment by alfureu** [comment]
Thanks! Much appreciated. Let's see what they will do about it.
