### ISSUE TITLE
Nginx config in documentation not compatible with php7

### ISSUE THREAD

**Issue by Maltimore** [FreshRSS/FreshRSS#2054]
Hi,
I know extremely little about php, or sysadmin in general, and only randomly made this work, so I don't know exactly what the problem is.
But on my debian 9 system, I had to modify the suggested nginx configuration here:

https://freshrss.github.io/FreshRSS/en/admins/02_Installation.html

to set this lock file to /var/run/php/php7.0-fpm.sock instead of /var/run/php5-fpm.sock

**Comment by Alkarex** [comment]
Thanks. Could you please try to edit the following two documents accordingly?

* https://github.com/FreshRSS/FreshRSS/blob/dev/docs/en/admins/02_Installation.md
* https://github.com/FreshRSS/FreshRSS/blob/dev/docs/fr/users/01_Installation.md

**Comment by Maltimore** [comment]
Will do!
