### ISSUE TITLE
Restart gives old already read articles as unread....

### ISSUE THREAD

**Issue by pommetjehorlepiep** [FreshRSS/FreshRSS#2055]
FreshRSS 1.11.2

Normally, I shutdown my computer overnight, and when I start FreshRSS again, I get loads of old articles again which are marked as 'unread' (before refresh).

For example this morning (21 Oct), I got stacks of articles up until 30 september as unread. No newer articles.
After marking them all read, a refresh turns up new articles unread (expected) but again also older already read articles from October.

This behavior only happens after shutting computer down overnight, not if you stop and start FreshRSS during the day.

**Comment by Alkarex** [comment]
Hello,
Do you mean that your stop the computer on which you run FreshRSS (server), or the computer from which you browse FreshRSS (client)? Or maybe it is the same machine.

Some feeds are known to update their old content (e.g. due to dynamic advertisements, etc.), in which case you might want to tune the following options, either in the global settings, or at feed level.

* In Configuration / Reading:
![image](https://user-images.githubusercontent.com/1008324/47265996-64bc2b00-d530-11e8-8709-f63c6a1f39db.png)


* In a feed advanced settings:

![image](https://user-images.githubusercontent.com/1008324/47266004-87e6da80-d530-11e8-94ad-96872716efa7.png)

Do you have examples of feeds, for which old articles are marked unread?

For instance, Le Monde https://www.lemonde.fr/rss/une.xml has such a problem.

**Comment by pommetjehorlepiep** [comment]
Hi @Alkarex,

I run and use FreshRSS on the same computer.

It's definitely not a feed specific issue, since it happens for all feeds. It's like it completely forgot what was read and what wasn't.

Here are the screenshots of my global Configuration Reading and Archiving settings:

![configuration - archiving](https://user-images.githubusercontent.com/8982487/47598756-5a90a580-d9e4-11e8-856d-d51fe0153c84.png)
![configuration - reading](https://user-images.githubusercontent.com/8982487/47598757-5a90a580-d9e4-11e8-8540-980425e3ef45.png)

For none of my feeds I use specific settings....

Some feeds:
http://www.news.com.au/national/rss
https://debian-administration.org/atom.xml
http://feeds.feedburner.com/Phoronix
https://nextcloud.com/blogs/feed//
https://xkcd.com/rss.xml

**Comment by Alkarex** [comment]
Hum, strange. I need some more details.
What database are you using (SQLite, MySQL, PostrgreSQL, ...), and on what
OS?
Please check you have enough disk space where the database is located.
How did you install FreshRSS (ZIP, git, Docker, ...) , and what version do
you run? If not Docker, what Web server and PHP versions? If Docker, what
image?
Does the problem appear if you only restart the browser, or only the Web
server, or only the database (in case of MySQL / PostgreSQL)?
How to you refresh articles (automatically by cron, or manually from the
Web interface)?
Do you access Internet through any kind of proxy?

**Comment by Alkarex** [comment]
P.S. Did you use older versions of FreshRSS, and if yes, did you experience the problem before?

**Comment by pommetjehorlepiep** [comment]
Hi @Alkarex,

I'm running FreshRSS in docker container which I built from scratch.
Container is using Debian 9 as base image.
Database used is MariaDB 10.2, running in a separate docker container.
Host OS: Solus 3.9999.
Docker version: 18.06.1-ce
Webserver:  Caddy v0.11 (running in same container as FreshRSS)
PHP version: 7.0

Haven't checked if restarting individual containers causes the problem.

Refresh is done using systemd which triggers the refresh every 30mins in the docker container.
http internet access goes via Squid, https straight to internet.

I started using FreshRSS as of version 1.11. Can't say for sure if problem was there before.

Cheers

**Comment by Alkarex** [comment]
1. Could you try to run another Docker instance of FreshRSS in parallel, but using our [official Docker image](https://github.com/FreshRSS/FreshRSS/tree/dev/Docker), with SQLite, and its own `./FreshRSS/data/` folder?

2. We need to find out what the changes are, which trigger the modifications. I suggest the following actions before shutdown, and at first boot after the nigh:
    a. Make some screenshots of your Web view for 2-3 different problematic feeds
    b. ZIP your `./FreshRSS/data/cache/` folder
    c. (if you can) SQL dump of the DB, or at least of selected articles.

**Comment by pommetjehorlepiep** [comment]
Hi @Alkarex,

I worked out what the problem was....stupid me was running a database restore at startup of the MariaDB...ouch.

Is all working ok now. Thx.

**Comment by Alkarex** [comment]
Haha ok. Thanks for the feedback.
