### ISSUE TITLE
403 Error when trying to update passwords

### ISSUE THREAD

**Issue by Twilek-de** [FreshRSS/FreshRSS#2056]
Hi all,

my FreshRSS installation seems to work but when I try to update a password I get a 403 You don´t have permission to view this page error (I am logged in as an admin at the time). I have set my environment to development and the log reads "gen.share.Known is not a valid key". I have no idea wether that error is connected to the permission problem or how to fix it.

Regards
Henning

**Comment by Twilek-de** [comment]
Hmm... I have looked at this further. The users config file gets rewritten with new password hashes and the new passwords work. At the same time I get logged out. Is it supposed to work that way? If so, that would be really inelegant.

**Comment by Alkarex** [comment]
Hello,
What browser are you using?
Could you please try again with another browser without password manager / form autocomplete?

**Comment by Twilek-de** [comment]
I am using the latest Firefox. I have just tried Edge and Chrome (both latest versions) with the same result. Always 403 when changing the password. This happens in the "Users" subection as well as in the "Profile" subsection of the settings.

**Comment by Twilek-de** [comment]
The "gen.share.Known is not a valid key" seems to pop up whenever FreshRSS is called and not be linked to the 403 problem.

**Comment by Twilek-de** [comment]
I think I solved the problem with the gen.share.Known" thing. I copied the en.php in cli/i18n/ignore to de.php in the same directory (my user has "de" as a locale) and turned of developement. Now it doesn´t show up any more. This of course does not change the 403 page.

**Comment by Alkarex** [comment]
Sorry, I thought it was when you were changing another user's password from the admin account.
Indeed, when you change your own password, the current behaviour is that you are logged out and need to log in again. The 403 error page is indeed unfortunate, and I will try to improve that.

**Comment by Twilek-de** [comment]
Ah ok, then it is not that much of a deal, it just feels like the wrong behaviour so you start to search for the error. Couldn´t you simple force a logout and return the user to the starting page (whatever a guest user sees)?!

**Comment by Alkarex** [comment]
@Twilek-de Could you please try this patch? https://github.com/FreshRSS/FreshRSS/pull/2057

**Comment by Alkarex** [comment]
@Twilek-de Another patch for the *Known* bug in German: https://github.com/FreshRSS/FreshRSS/pull/2058

**Comment by Alkarex** [comment]
P.S. Could you please try to edit the following line for a better German translation?

https://github.com/FreshRSS/FreshRSS/blob/abc5c344f6ad4035a3a9ac977add3ef4d5d76540/app/i18n/de/gen.php#L170

For reference: https://withknown.com

**Comment by Twilek-de** [comment]
I have edited the file and the error seems to have gone away as far as I can see.

**Comment by Alkarex** [comment]
For *Known*, I meant doing a pull request or online edit in GitHub, if you can find a better text for the German version :-)

**Comment by Twilek-de** [comment]
Oh I see :-D Hmmm I have never heard of "known", what is it? I will see what I can come up with...

**Comment by Alkarex** [comment]
https://withknown.com 
Just a direct translation should be fine. *Sites based on Known*

**Comment by Twilek-de** [comment]
Direct translation would not work very well here, it would sound really awkward. I am trying to find out what known really does to come up with something that is easily understandable.

**Comment by Twilek-de** [comment]
Just to get this straight for me. "Known" is some kind of individual selfhosted facebooktimeline where you can just dump stuff (like a one man forum post) and FreshRSS can read the individual entries and present them like a RSS feed?!

**Comment by Twilek-de** [comment]
Or can you share RSS entries from FreshRSS to a "known" site?

**Comment by Alkarex** [comment]
I am not myself of user of this service, so I am not familiar with the details, but FreshRSS can share articles with it, just like it can with many other services (Facebook, LinkedIn, Shaarli, etc.)

**Comment by Alkarex** [comment]
Either option look fine 👍  Can you please put the variant you best like in
https://github.com/FreshRSS/FreshRSS/blob/abc5c344f6ad4035a3a9ac977add3ef4d5d76540/app/i18n/de/gen.php#L170

P.S. The easiest is just the edit button

**Comment by Twilek-de** [comment]
Wow cool, I think I created my first Git pull request ever :-)

**Comment by Alkarex** [comment]
Indeed, you have 👍 https://github.com/FreshRSS/FreshRSS/pull/2059
