### ISSUE TITLE
[Suggestion] Multi utilisateurs : xxx.yyy

### ISSUE THREAD

**Issue by Draky50110** [FreshRSS/FreshRSS#2061]
Bonjour.

Petite suggestion : serait-il possible d'avoir des noms d'utilisateurs en xxx.yyy pour avoir une forme prenom.nom par exemple ?

A l'heure actuelle, le point "." est interdit.

Merci :)

**Comment by Alkarex** [comment]
Bonsoir,
Je ne me souviens plus pourquoi nous n'avions pas autorisé le point (sûrement pour une compatibilité avec quelque chose). Mais c'est facile à changer.

**Comment by Draky50110** [comment]
C'est ok pour moi avec le point ou l'underscore :)
Nickel, merci.
