### ISSUE TITLE
Question: Help creating a theme?

### ISSUE THREAD

**Issue by filipe-silva** [FreshRSS/FreshRSS#2064]
Hi! I want to ask for help with creating a theme perhaps.
What I want to do is this, have the articles open and based on css media query display in a row about 6 articles. Now when I press arrow for the next article, I want to "jump" to the next row of six. And so on.

If possible, I'd also like to be able to choose per category if it displays the articles by 6 or just one the "normal" way.

Is there any way to achieve this?

**Comment by Alkarex** [comment]
Hello,
Quite a lot should be doable with a new theme, using only CSS.
It might be needed to add a bit of JavasScript and/or some server-side help. I can help with the final integration of those things if needed.
I suggest you start by duplicating one of the existing themes and tweak it to your needs.

**Comment by math-GH** [comment]
See the documentation: https://freshrss.github.io/FreshRSS/en/developers/04_Frontend/02_Design.html
