### ISSUE TITLE
How to I create a public feed, like FreshRSS demo?

### ISSUE THREAD

**Issue by hanan-cohen** [FreshRSS/FreshRSS#2065]
Hello,

I would like to create a public website where everyone will be able to see the feed. 

I didn't find a way to do that.

Any help will be appreciated.

Thanks.

**Comment by Alkarex** [comment]
Hello,
I believe the option you are looking for is: Authentication / Allow anonymous reading of the articles of the default user

**Comment by hanan-cohen** [comment]
Thanks.
