### ISSUE TITLE
Default OPML

### ISSUE THREAD

**Issue by cutariechu** [FreshRSS/FreshRSS#2075]
Hello FreshRSS team,

I have made a web with FreshRSS oriented to scientific journals feeds with at present 40 feeds structured in 4 categories. I would like that feed structure to be default. Anonymous users can see these feeds but, when they create a new account, the feed list is empty. Is there an easy way (other to provide a link to the OPML for import) to establish my OPML as default for new users?
Thanks in advance

**Comment by Alkarex** [comment]
Hello,
If they create their account themselves, then we do not currently have the possibility of auto-loading a custom OPML. But that is a good idea.
If you create their account manually, you can use the `./cli/import-for-user.php` command line
https://github.com/FreshRSS/FreshRSS/tree/dev/cli

**Comment by cutariechu** [comment]
Ok, thank you Alex

**Comment by Alkarex** [comment]
Implemented in https://github.com/FreshRSS/FreshRSS/pull/2627
Tests and feedback welcome
