### ISSUE TITLE
Change label for read shortcut

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/FreshRSS#2086]
https://github.com/FreshRSS/FreshRSS/blob/e04804d0f67dd43fd3f072b9a127768ee7b7b56c/app/i18n/en/conf.php#L161

'r' shortcut marks as read but also marks as unread depending on the current status of the article. The label on the configuration page should reflect this, otherwise one could think there is no shortcut to mark as unread. Or we can create a specific shrtocut 'u' for this purpose.

**Comment by Frenzie** [comment]
Toggle mark as read?

**Comment by Alkarex** [comment]
Anyone for a PR on this? :-)

**Comment by aledeg** [comment]
@Alwaysin available on dev branch
