### ISSUE TITLE
Multiple admins for a larger group of users

### ISSUE THREAD

**Issue by jfmessierdotca** [FreshRSS/FreshRSS#2096]
I implemented an instance of FreshRSS after a meeting of our local Linux user groups. Many participants were interested to use this service to aggregate news feeds. However, when creating the site (was not the first one, but the first for a larger user group than myself), I created myself by default, and became *the* administrator, instead of a more generic userID. Since this will be a shared userid/password with my friend who also manages the site, I had to create someone else with a generic "admin" username and a password, and manually update config.php. 

I would like to see something that could let more than one user be, become, or cease to be, an administrator, with the actual privileges granted by the system. I guess this would mean a different system of rights and flags, instead of a single identified username from the config.php file, as well as slightly different page for the admin when managing users, in that now a user can be granted (or denied) admin rights.

Thank You :-)

**Comment by aledeg** [comment]
@jfmessierdotca Please check aforementioned PR to check if it suits your needs.

**Comment by aledeg** [comment]
@jfmessierdotca the PR is available in the master branch. It will be released in the upcoming version.
