### ISSUE TITLE
Missing php-zip extension

### ISSUE THREAD

**Issue by jfmessierdotca** [FreshRSS/FreshRSS#2097]
I have a rather fresh installation of FreshRSS, and when I try to import a ZIP file containing all my RSS feeds as create by my other FreshRSS install, I get the error message that php-zip is not installed. I indeed installed it, and when setting up FreshRSS, it had no problem with my install. When I do the "sudo apt-get install php-zip", i get that it is already installed. But it is still not detected by FreshRSS. From some other pages, I found the command "php --ini" that lists (I think) all modules for OHO. Indeed, I do not find php-zip in the list. Should I remove and re-install this extension specifically, or is there an ini file I can modify to manually add the php-ini to the list of known modules for PHP ? 

Merci :-)

**Comment by jfmessierdotca** [comment]
I tried an uninstall and re-install of php-zip and the php-ini does not seem to list php-zip more.
Also restarted the apache2 service, reloaded the page, and still the same issue. When running the system check, I still see that php-zip is missing,

**Comment by Alkarex** [comment]
Hello,
Watch out that you might have more than one version of PHP on your system, not all of them necessarily with the same extensions. In particular, PHP in your Web server, and PHP via the command line are typically two different things.
What OS are you using?
You might have to manually restart your Web server, e.g.
```sh
sudo service apache2 restart
```

Try to put a file `phpinfo.php` at your server root and run it via your browser:

```php
<?php
phpinfo();
```

**Comment by jfmessierdotca** [comment]
I am running Ubuntu 16.04 stable version. I have Apache2 installed, and I run WordPress as well. I put the phpinfo() call as you said. It finds a Zip module. So it seems to be enabled fine. At the top of the phpinfo page, I can see that I run "PHP Version 7.0.30-0ubuntu0.16.04.1". Under /etc/php, I see 7.0 and 7.2..

**Comment by jfmessierdotca** [comment]
I tried this, got error messages when importing the .opml.xlm file, as generated from my other install of FreshRSS. I tried to edit it to only contain the http:// rss links, one by line, and got errors, saying that each feed was empty. But when adding a feed by its url, seems to work fine.

**Comment by Alkarex** [comment]
What errors did you get during the OPML import?
If you have done some things by command line, be sure to re-apply the access rights correctly. E.g.:
```sh
cd /usr/share/FreshRSS
sudo chown -R :www-data . && sudo chmod -R g+r . && sudo chmod -R g+w ./data/
```

**Comment by jfmessierdotca** [comment]
I looked at the files to compare my own VPS with the club's one which has the missing zip module, and I see that only own, it has a file named 20-zip.ini that refers to  /etc/php/7.1/mods-available/zip.ini. Fine. On the club's one, there is no ini under the mods-available directory at all, so no 20-zip.ini that can refer to it.

**Comment by jfmessierdotca** [comment]
I do not see a directory named /usr/share/FreshRSS, not on the club's web site. But I see one on my own. But I installed FreshRSS the same way on both systems. How come do I have a FreshRSS on one system, but not on the other one ? What could be the difference ?

**Comment by Alkarex** [comment]
@jfmessierdotca FreshRSS is probably installed in another directory.

Please try this test:

```php
<?php
echo 'ZIP loaded: ' . (extension_loaded('zip') ? 'yes' : 'no');
```

**Comment by jfmessierdotca** [comment]
Returns: no

I checked, and indeed, it is installed differently. ON my own VPS, it is under /usr/share/FreshRSS, with a symlink from /var/www/html/FreshRSS to the real directory. On the other one, I unzipped everything and plainly moved it under /var/www/html/rss. On my own VPS, I use <name>/FreshRSS and on the club one, I use <club>/rss

**Comment by jfmessierdotca** [comment]
Comparing directories, I see different filenames and subdirs. For example, my VPS has robots.txt, the other does not. My VPS doe snot have index.php, the other one does have one. My VPS has a ./api subdir, the other one has a ./app one. OK. Looks like I did not take the set of files from the net. I guess one was downloaded from the web site, the other from github, perhaps.................. but both were ZIP files of some sort. Feel like Ii should get the same ZIP file as I had from my VPS and perhaps re-install.

But before this, one question: When is the php-zip used ? If this is only when importing/exporting feeds, this is not a big issue. I can live with it. But if it is used elsewhere, I may want to redo it all...

**Comment by Alkarex** [comment]
Yes, it is only for importing archives, and you can even extract files yourself and import their non-ZIP version

**Comment by jfmessierdotca** [comment]
Which I tried with no success.......................... I had empty feeds. I tried to strip the XML to contain only the URLs, one per line, same thing. So I give up and I will simply copy/paste the feed urls from one system to another, I'm already half-way done. I will read everything from one, and mar everything as read on the other to start clean...............................

**Comment by Alkarex** [comment]
You are welcome to show your OPML, so I can see if there is any problem handling it

**Comment by jfmessierdotca** [comment]
Here I
[freshrss_2018-10-31_export.zip](https://github.com/FreshRSS/FreshRSS/files/2536285/freshrss_2018-10-31_export.zip)
 attach the ZIP file. as it was created by my installation on my VPS. 

 At this point, I am ready to actually re-install it from [hopefully] the same ZIP file as I used on my own VPS. If I delete the install of the system, preserving perhaps the config.php  file, can I just reconnect to the existing MySQL database and keep all my data as it was ?

**Comment by Alkarex** [comment]
@jfmessierdotca I could import your file in my instance without problem.

3 methods to retry from scratch:

1) Delete feeds one a time in the FreshRSS UI

2) Make a new FreshRSS user, and make tests from that user. You can delete that user and try again. When you are satisfied, you can change your main user in `./data/config.php`

3) Drop the SQL database or relevant tables (after back-up - dangerous if you have other things running on the same server)

**Comment by JannetGen** [comment]
Hey! If php-zip is giving you trouble on the web server side, the easiest workaround is to extract the archive beforehand and import the raw OPML file directly into FreshRSS.
If you don't have a local zip utility handy on your machine, you can quickly unpack the export file [edited to avoid publicity] to get the individual OPML file and upload that instead.
