### ISSUE TITLE
Apostrophe character issue

### ISSUE THREAD

**Issue by meminens** [FreshRSS/FreshRSS#2098]
Some of my feeds have `'` in the title and these are displayed as `&apos;` in the list of articles and feeds. I did confirm that MySQL database is configured for UTF-8 but I don't know what else to check. Perhaps this is a server configuration issue but I'd require your support in any case. Thanks.

`Ubuntu 18.04`

`Apache 2.4.29` 

`PHP 7.2.10` 

`MySQL 5.7`

**Comment by Alkarex** [comment]
Hello,
How did you import your feeds (manually one at a time, or by OPML)?
Could you please provide the URL for such a feed (to help testing).
Doesn't it work when you change the name of the feed from the FreshRSS Web UI?

**Comment by meminens** [comment]
Hey @Alkarex 

I imported several feeds via the OPML file. Example feed: http://feeds2.feedburner.com/itsnicethat/SlXC

But I noticed that the problem went away after I removed the feed and added it back manually (by entering the feed URL in the subcription management page). So it must have been something to do with the OPML file encoding I suppose. And yes I could rename the feed name from the FreshRSS Web UI. Thanks for the tip! Guess we can close this issue (non-issue?).

I double checked the OPML file and indeed the `&amp;` was in the `text` field of the feed. YouTube generated this OPML file I guess they kind of screwed up. Should have verified the file before attempting to import into FreshRSS.

**Edit:** Correction. OPML I imported into FreshRSS is actually exported from ViennaRSS. I'll check their code to see why the apostrophes are rendered incorrectly.

**Comment by Alkarex** [comment]
I cannot reproduce the problem on FreshRSS side.
Could you please show a part of the OPML?

**Comment by meminens** [comment]
@Alkarex I edited my comment above. [Looks like the issue is genereated in ViennaRSS.](https://github.com/ViennaRSS/vienna-rss/issues/1198)

See below:

`<outline htmlUrl="https://www.itsnicethat.com" xmlUrl="http://feeds2.feedburner.com/itsnicethat/SlXC" type="rss" description="" text="It&amp;apos;s Nice That"/>`

**Comment by Alkarex** [comment]
Indeed, there is a double-encoding in the OPML feed title, and FreshRSS is obeying as it should :-)
