### ISSUE TITLE
Problem with Mark All As Read

### ISSUE THREAD

**Issue by Sp3r4z** [FreshRSS/FreshRSS#2101]
Hi,

Since v1.12.0, I've problems with "Mark All As Read", I've logs message "SQL error listWhereRaw: database disk image is malformed". I use SQLite, maybe the problem is here.

I've done a full fresh and clean install, and problem come again after some "feed updates", so I'm quite sad about the situation. My SQLite database file, is totally readable with Adminer/PHP I don't understand.

If someone can help me with.
Thx

**Comment by pavel2001** [comment]
> Regular use of SQLite database leads to large amount of data, which results in the increase of size over the well-defined limit. This is also one of the factors responsible for generating this error SQLite Database Disk Image Is Malformed.
You need export database to SQL file and recreate database to fix that.

**Comment by Alkarex** [comment]
@Sp3r4z Please try the *optimise database* button
![image](https://user-images.githubusercontent.com/1008324/47869550-860df880-de07-11e8-8391-1e9b4b3dd320.png)

What OS and system are you using?

**Comment by Sp3r4z** [comment]
@pavel2001 My SQLite database is about 10M 
![capture d ecran - 01112018 - 19 29 07](https://user-images.githubusercontent.com/3195384/47871493-88268600-de0c-11e8-96aa-0fb11935c81b.png)
So it's really lite… I've done a check_integrity, and rebuild a database, but it's really sad having to do that :/

@Alkarex I've already done that many time… it's really since the v1.12.0, 2 days since update, and it's an everyday problem.
I don't really want to have a database dependency for that purpose.

Maybe FreshRSS should just limit SQLite records, or asking for a real database

**Comment by Alkarex** [comment]
The main new DB change in FreshRSS 1.12.0 is the custom labels.

What OS and system are you using? Is your filesystem on an SD card or a normal hard-disk?

Would you mind sending me your SQLite database?

**Comment by Sp3r4z** [comment]
@Alkarex a web hosting by OVH, PHP-fpm v7.0, SQLite3 (module v7.0.32 & library v3.14.2)

I've deleted the db.sqlite, after the db rebuild… :/

**Comment by Alkarex** [comment]
I would also be interested in your new working DB, so I can run it on my side and try to reproduce your issue

**Comment by Sp3r4z** [comment]
Sure, here it is: https://framadrop.org/r/tzJ1pk5_el#YmnQYCpLwgljS3LdD0MXNKEkUr96CVawAglBNpSq0ds= (delete in 24hours)

**Comment by Alkarex** [comment]
@Sp3r4z I got it, thanks

**Comment by Sp3r4z** [comment]
I know, this new one is totally okay, no integrity problem. If it happens again, I'll give you the "broken db" for sure ;)

By CRON, with "app/actualize_script.php" has it's says in install doc (if I remember well)

**Comment by Alkarex** [comment]
I have tried several times to mark all articles as read / unread, without any problem so far.
Yes, cron is the best. Do you run it with the same user as your Web server?

**Comment by Sp3r4z** [comment]
Don't really know (I think so), it's a shared web hosting from OVH (the cheapest one), before v1.12.0 I've never experimented that problem, really never. even if I've have more or less the same among of feeds to update, from many years now.

No problem yet, I've done the same test, and no problem.

**Comment by Alkarex** [comment]
I will continue testing on my side. If the problem occurs again on your side, maybe you could try to revert to FreshRSS 1.11.2 to check whether the bug was a coincidence or related to the new version 1.12.0.

**Comment by Sp3r4z** [comment]
I'll continue testing with v1.12.0, and rollback to v1.11.2 if problem happens again

**Comment by Alkarex** [comment]
Still running fine with your DB on my side.

**Comment by Sp3r4z** [comment]
Still good here too. Maybe the update from v1.11 to v1.12 was not good for my DB… or something.

I've just quite old (some days/weeks) feeds which are shown as "new articles" but well… not something to problematic

**Comment by Alkarex** [comment]
Closing, but just open a new PR if you face any remaining problem.
