### ISSUE TITLE
Disabling new users from creating themselves

### ISSUE THREAD

**Issue by jfmessierdotca** [FreshRSS/FreshRSS#2102]
In my installation for our club, I noticed (for the first time !) that there is a link for registering as a new user. How can I get this link (and perhaps the functionality) disabled ? I want my FreshRSS to remain limited to the members of the club, and be the one who will create the authorized users.

Thank You :-)

**Comment by Alkarex** [comment]
Hello,
This can be defined in the global limits. Setting a max number below the current number of users will disable new registrations (then, only the admin can make new users).

![image](https://user-images.githubusercontent.com/1008324/47871625-d9367a00-de0c-11e8-8999-5cd28f025379.png)

**Comment by jfmessierdotca** [comment]
OK. Good idea.................... Thanks :-)
