### ISSUE TITLE
Disabling a feed?

### ISSUE THREAD

**Issue by chemical1979** [FreshRSS/FreshRSS#2103]
I checked the menus, but apparently I'm unable to disable a feed. Please give me a quick hint.

I want to disable a feed, but not deleting it (I want to remember this feed). I could make this feed "not visible" in its settings, but it still gets updated in the background, correct? As this feed publishes articles on a 15 min basis, this gets annoying pretty fast and also creates a lot of noise in the db.

Maybe I should just delete the feed. But then again ... ;-)

**Comment by chemical1979** [comment]
Muting is exactly what I was looking for. Thank you!

**Comment by notDavid** [comment]
Hi there, so I'm wondering if 'mute' also stops **fetching** the feeds?

If it does, the wording is a bit misleading. Muting implies it is only 'not displayed' and updates still happen in the background.

What I'm looking for is a way to **disable** a feed, so it does not get fetched. It's unclear whether 'mute' accomplishes this, and i can't find anything in the docs.

Does any body know? Thank you!

**Comment by Luxtech** [comment]
> Hi there, so I'm wondering if 'mute' also stops **fetching** the feeds?
> 
> If it does, the wording is a bit misleading. Muting implies it is only 'not displayed' and updates still happen in the background.
> 
> What I'm looking for is a way to **disable** a feed, so it does not get fetched. It's unclear whether 'mute' accomplishes this, and i can't find anything in the docs.
> 
> Does any body know? Thank you!

This! Could somebody clarify?
