### ISSUE TITLE
Auto Update Feeds and Allow Anonymous Reading?

### ISSUE THREAD

**Issue by Legalien** [FreshRSS/FreshRSS#2105]
Just installed and started using FreshRSS. It's badass. Very good. But I have 2 questions.

Let me just say, I'm a noob :)

1) I tried accessing a feed I created on a browser I wasn't logged in, and I got a 403 FORBIDDEN error. I searched and searched, and found a post on Github where Alkarex said: "**you need to set a token in the configuration to enable this feature for external users**."

So I looked in FreshRSS Settings, and in Authentication method, I enabled "**Allow anonymous reading of the articles of the default user**." That did it, now I could access the feed. But on the **Authentication method** page there is also this setting - "**Allow anonymous refresh of the articles**"

I plan on using this rss feed with IFTTT to get notified via email when the feed gets updated with new content. Do I need to enable "Allow anonymous refresh of the articles" so that IFTTT can work? My logic is that IFTTT is an anonymous service, and it must refresh the articles to see the new ones. I'm probably wrong. What's this for? Do I need to enable this?

2) Which brings me to my second and main problem. How to have the feed update automatically?

In Archiving I set "**Do not automatically refresh more often than**" to 20 minutes. And in the individual feed's settings I set "**Do not automatically refresh more often than**" to 15 minutes.

The feed is of a Twitter account. So I made a tweet. 20 minutes later the feed wasn't updated. I clicked on the "**Actualize**" button, and the feed updated. So I made another tweet and waited 20+ minutes. The feed didn't update. I clicked the "**Actualize**" button, and the feed updated. So clearly the feed doesn't want to update on its own :(

In the feed's settings, under Advanced, I see this - "**Timeout in seconds**" - and it's empty. Where the value could be inserted it says "by default." Is that what defines how often the feed gets updated. I don't think so, but I figured I ask. What's this for?

That said, going through the documentation and stuff, related to auto-updates, I saw cron, and PubSubHubbub, and also in Extensions there is an "AutoRefresh" extension. I'm confused, which to use? I am only using FreshRSS for my personal use. And I am aware that I shouldn't have feeds be auto-updated too fast. I would really like to know how to have the feeds auto-update every X amount of time.

Sorry for the long message, I tried to explain everything as detailed as possible so that hopefully I get a good response.

Thank you :)

**Comment by Frenzie** [comment]
Just a quick note that cron is the recommended means of updating, and you could theoretically run the cron job every second (but that'd be stupid) because FreshRSS will limit the refresh rate all by itself with the "do not automatically refresh more often than…" setting.

The AutoRefresh extension is something different. If you leave the page open for a while you'll get a "new feeds are available" (or some such message), which you can click to reload your display of the page. I like things to stay as they were, but some people prefer to have the webpage automatically refreshed. This doesn't affect anything other than your own browser.

**Comment by Legalien** [comment]
So I'm reading this - https://freshrss.github.io/FreshRSS/en/users/03_Main_view.html

It says:

**With the actualize_script.php script**

**This method is available only if you have access to the installation server scheduled tasks.**

**The script is named actualize_script.php and is located in the app folder. The scheduled task syntax will not be explained here. However, here is a quick introduction to crontab that might help you.**

**Here is an example to trigger article update every hour.**

**0 ..... php /path/to/FreshRSS/app/actualize_script.php > /tmp/FreshRSS.log 2>&1**

I think I have access to the installation server scheduled tasks. I'm self-hosting. So I looked through "**actualize_script.php**" but I can't figure out where to add that code?

**Comment by Frenzie** [comment]
If you have shell access you can run `crontab -e` to paste that into the right document.

It's also possible that there's a web GUI where you can put the path to the actualize_script.

If that's not an option it's not the biggest problem because you can always use some free webcron service.

**Comment by Legalien** [comment]
Oh brother. I don't know if I have shell access, I don't know how to run crontab -e, and I don't know what the right document is (actualize-script.php?), and then I don't know Where in the document I should paste it.

This is embarrassing... :p

I have cPanel, and in there I have Cron Jobs. And I can create Cron jobs in there. But I'm unsure if I have to create a cron job or not. And if I do, what do I put in the "Command:" section of the Cron job. This?

https://MYSERVER/p/i/?c=feed&a=actualize

poker face...

**Comment by Legalien** [comment]
So I created a cron job, set it to 5 minutes just to test, and 5 minutes later I got this email:

**/bin/sh: https://MYSERVER/p/i/?c=feed: No such file or directory**

I'll try again, using this:

https://MYSERVER.com/p/i/?c=feed&a=actualize

If that doesn't work... and it won't :D ... I'll try this:

https://MYSERVER.com/FreshRSS-master/p/i/?c=feed&a=actualize

I'm like a child trying to fly a plane. Ridiculous xD

**Comment by Frenzie** [comment]
No, `crontab -e` would automatically open the right document so you don't have to. ;-)

> And if I do, what do I put in the "Command:" section of the Cron job. This?

No, `/path/to/FreshRSS/app/actualize_script.php`

**Comment by Legalien** [comment]
Okay, so none worked. But that last link, when I visited it manually it did work.

Therefore... that's probably it, but I just need to add something somewhere for my Cron to pick up.

---

Frenzie, would this be it?

/home3/ME/public_html/MYSITE.com/FreshRSS-master/app/actualize_script.php

**Comment by Legalien** [comment]
Okay, I did that. Now we're getting somewhere. Here's the email I received when the Cron ran:

**PHP:  syntax error, unexpected '{' in /home3/ME/php.ini on line 890
X-Powered-By: PHP/5.4.45
Content-type: text/html**

**FreshRSS error: This PHP script may only be invoked from command line!**

What to do?

**Comment by Frenzie** [comment]
It's curious that you'd get that with `/home3/ME/public_html/MYSITE.com/FreshRSS-master/app/actualize_script.php` because you can't reach that location from the web.

If that cron can do HTTP requests, use `https://your.server.net/FreshRSS/p/i/?c=feed&a=actualize` instead. (Or `curl 'https://your.server.net/FreshRSS/p/i/?c=feed&a=actualize'` if it can run commands.)

**Comment by Legalien** [comment]
I tried this - **https://your.server.net/FreshRSS/p/i/?c=feed&a=actualize**

It returned **No such file or directory**

I tried this - **curl 'https://your.server.net/FreshRSS/p/i/?c=feed&a=actualize'**

It returned this:

  **% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current**
                                 **Dload  Upload   Total   Spent    Left  Speed**

  **0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0**
  **0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0**

By the way, I'm adding these under "**Command**" in my cPanel in Cron Job area. Also, I didn't add any code or any edits in the **actualize_script.php** file.

See photo - [Photo Screenshot](https://i.imgur.com/sDXdfdN.png)

Is this it? Does this mean it works? My feed didn't update.

**Comment by Frenzie** [comment]
That looks like it should be working, yes.

Feed updates will always be limited by the global or individual update setting (see Configuration → Archiving for global).

As an aside, what happens if you put something `php /home3/ME/public_html/MYSITE.com/FreshRSS-master/app/actualize_script.php` in your cronjob? It would be (ever so slightly) more efficient than using curl with the web-facing end of the server.

**Comment by Legalien** [comment]
Yes I thought about the Archiving. I have **Archiving** at **30 minutes**, and I have the individual feed's **Do not automatically refresh more often than** at **by default**

Let me test the one. Be right back with report.

**Comment by Legalien** [comment]
Okay, the Cron ran 2 more times, but my feed isn't updated :(

What is the **by default** under **Do not automatically refresh more often than**? Does that then revert to the Global setting for refreshing, or is it defined elsewhere?

I'll change the feed's automatic refresh rate at the lowest - 15 minutes - and see if the feed then updates after at least 4 Cron jobs = 20 minutes.

If you have any ideas let me know. Thanks man.

**Comment by Frenzie** [comment]
> PHP: syntax error, unexpected '{' in /home3/ME/php.ini on line 890

If there's a syntax error in php.ini you'd think nothing would be working. What's in the relevant section of your php.ini?

> Does that then revert to the Global setting for refreshing, or is it defined elsewhere?

The global setting means default there.

**Comment by Legalien** [comment]
So in here - **/home3/ME/php.ini**

Here you go bro, see for yourself - **[Photo Screenshot](https://i.imgur.com/bZc3yUF.png)**

The Cron is running every 5 minutes. I get this each time:

  **% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current**
                                 **Dload  Upload   Total   Spent    Left  Speed**

  **0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0**
  **0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0**

The feed remains not updated.

**Comment by Frenzie** [comment]
That does look like a syntax error. It should be a comment explaining which values you can use, like this:

```ini
; Set to {nocache,private,public,} to determine HTTP caching aspects
; or leave this empty to avoid sending anti-caching headers.
; http://php.net/session.cache-limiter
session.cache_limiter = nocache
```

So then you can set `session.cache_limiter` to one of those three values (or none).

> The feed remains not updated.

Which feed is this?

**Comment by Legalien** [comment]
Okay, the Cron ran 4 times since I last updated it. The feed has not refreshed.

I couldn't help myself, so I just went and clicked the Actualize button in my FreshRSS manually, and the feed updated immediately 👍 💯 🥇 

What to do?

---

> That does look like a syntax error. It should be a comment explaining which values you can use, like this:
> 
> ```ini
> ; Set to {nocache,private,public,} to determine HTTP caching aspects
> ; or leave this empty to avoid sending anti-caching headers.
> ; http://php.net/session.cache-limiter
> session.cache_limiter = nocache
>
> So then you can set `session.cache_limiter` to one of those three values (or none).

Oh 🐙 Um.. this is my Hostgator File Manager main folder. I didn't create any of the files in there. Either Hostgator did or, I don't know, on my first Wordpress site installation it was created. Hm. I'll change it to what you said.

Should I then try this again? **php /home3/ME/public_html/MYSITE.com/FreshRSS-master/app/actualize_script.php**

> Which feed is this?

Well, here you go bro - https://ninomaluri.com/FreshRSS-master/p/i/?a=rss&hours=168

**Comment by Frenzie** [comment]
> Should I then try this again? php /home3/ME/public_html/MYSITE.com/FreshRSS-master/app/actualize_script.php

The `php` part is optional.

> Well, here you go bro - https://ninomaluri.com/FreshRSS-master/p/i/?a=rss&hours=168

I mean which feed isn't updating?

**Comment by Legalien** [comment]
> The `php` part is optional.

Okay, I changed it. I included the php part. Let's see what happens, I can remove it after.

I guess the feed won't update for about another 10 minutes (due to the setting I have for updating the feed minimum 15 minutes).
 
> I mean which feed isn't updating?

Um, isn't that the feed? Maybe it's this - https://ninomaluri.com/rss-bridge-master/?action=display&bridge=Twitter&u=Nino_Maluri&_cache_timeout=300&format=Atom

Thanks for keeping up with me man. I know I'm not making it easy. Sorry :)

**Comment by Frenzie** [comment]
> Failed loading /opt/php56/lib/php/extensions/no-debug-non-zts-20131226/ZendGuardLoader.so: /opt/php56/lib/php/extensions/no-debug-non-zts-20131226/ZendGuardLoader.so: undefined symbol: zend_execute_ex

Hm, weird. If you want CLI PHP to work I'd contact your host, but the curl method will suffice to update FreshRSS. :-)

**Comment by Legalien** [comment]
> But is it on rss-bridge yet?

No, it's not. But it doesn't matter. If I click the Actualize button in FreshRSS, the feed in FreshRSS gets updated. I just need something to click the Actualize. That's what Cron is supposed to do in this case, i think.

I came here from RSS Bridge because RSS Bridge doesn't update the stuff. I don't understand completely, here's what they told me over at RSS Bridge:

"**Basically, if you press F5 in your browser, RSS-Bridge will go and check if the cache timeout has elapsed. If not, it will just return a copy of the cached data. If the cache timeout has elapsed, it loads new contents from the servers (i.e. Twitter). Of course, if you don't press F5, RSS-Bridge does nothing. A feed reader basically takes care of pressing F5 for you.**"

They told me that FreshRSS is a well designed feed reader. And so here I am :)

**Comment by Legalien** [comment]
> Failed loading /opt/php56/lib/php/extensions/no-debug-non-zts-20131226/ZendGuardLoader.so: /opt/php56/lib/php/extensions/no-debug-non-zts-20131226/ZendGuardLoader.so: undefined symbol: zend_execute_ex
> 
> Hm, weird. If you want CLI PHP to work I'd contact your host, but the curl method will suffice to refresh FreshRSS. :-)

Curl? I thought we were doing Cron. OMG...

---

I ran this again -  **curl 'https://ninomaluri.com/FreshRSS-master/p/i/?c=feed&a=actualize'**

**% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current**
                                 **Dload  Upload   Total   Spent    Left  Speed**

  **0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0**
  **0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0**
  **0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0**

FreshRSS didn't update :(

**Comment by Frenzie** [comment]
> That's what Cron is supposed to do in this case, i think.

It does, yes.

> Curl? I thought we were doing Cron. OMG...

Cron is just a means of executing a command at regularly scheduled intervals. That can be a PHP script or it can be a curl command. (Or anything else.) ;-)

> if you press F5 in your browser, RSS-Bridge will go and check if the cache timeout has elapsed. If not, it will just return a copy of the cached data.

Odd, the TwitterBridge timeout is only five minutes:

https://github.com/RSS-Bridge/rss-bridge/blob/2ac2f3dc66a2e0c4ddfc1fdb6c4649a80c388677/bridges/TwitterBridge.php#L5

But either way, you, I, and your FreshRSS have all "pressed F5" on it. When the feed isn't updated, you can't conclude that FreshRSS hasn't updated.

**Comment by Legalien** [comment]
If I go to FreshRSS and click the Actualize button, the feed will update immediately. How do you explain that?

**Comment by Legalien** [comment]
I think there's something wrong with my Cron setup. There's no other explanation. It works 100% when I click it manually, but won't work when Cron runs.

**Comment by Frenzie** [comment]
Miscommunication then. ;-P

The feed link you gave me doesn't show me anything more recent than many hours ago, so there's really nothing to update *from* there.

Anyway, if you check https://freshrss.github.io/FreshRSS/en/users/03_Main_view.html it explains how to fix up your permissions in case authentication is required (e.g., allow anonymous refresh).

**Comment by Legalien** [comment]
But that's the thing, there is something to update.

Check the feeds:

RSS Bridge - https://ninomaluri.com/rss-bridge-master/?action=display&bridge=Twitter&u=Nino_Maluri&_cache_timeout=300&format=Atom

FreshRSS - https://ninomaluri.com/FreshRSS-master/p/i/?a=rss&hours=168

The FreshRSS one has a more recent tweet on it, one that is not displayed on the RSS Bridge feed. See dates on the tweets.

And I made a new tweet 45 minutes ago, and it's not reflected on either feeds yet. However if I go to FreshRSS and click **Actualize**, the new tweet will show on the FreshRSS feed immediately :)

**Comment by Legalien** [comment]
GODDAMNIT BROTHER! I enabled **Allow anonymous refresh of the articles .** Worked! 👍 

  **% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current**
                                 **Dload  Upload   Total   Spent    Left  Speed**

  **0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0**
  **0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0**
  **0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0**
  **0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0**
  **0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0**

After this, my FreshRSS feed updated, as it should <3 <3 <3

Now I will make a new tweet on my Twitter account, and wait to see if/when it updates again. Fingers crossed :)

**Comment by Legalien** [comment]
Oh, if you check my RSS Bridge feed, it's still like 3 tweets behind :)

**Comment by Legalien** [comment]
Okay, 1 Cron ran, no update. According to my FreshRSS settings for this feed, the next update should happen 15 minutes after the previous one. And so, the second or third Cron run from now should update the feed with the new tweet...

**Comment by Legalien** [comment]
Second Cron ran, no update...

**Comment by Legalien** [comment]
Third Cron ran, no update. But it did email me this:

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0

The last (and only) time when the update actually happened, there were numbers other than 0 here. All the other time it was all 0es.

So no update on FreshRSS yet. But let's see the next one.

**Comment by Legalien** [comment]
YESSSSSSSSSSS!!!!!!!!!!!!!!!!!!!!!!!!!! Works. Feed is updated!

Me and you buddy, we're gonna take over the world :D 👍 🗡 🌮 🚶 🔨 🔑 🌍 🤙

**Comment by Legalien** [comment]
I couldn't have done it without you man. I'm really pumped up right now 🦅 🦅 🦅 

Let me know when you're ready to take over the world. I'll be here waitin 😈 😄
