### ISSUE TITLE
figcaption tag issue

### ISSUE THREAD

**Issue by alfureu** [FreshRSS/FreshRSS#2106]
I noticed that the 
```
<figcaption> 
   ... 
</figcaption>
```

tags render strangely in FreshRSS. The desired behaviour would be to render centered under the Figure.

![figcaption](https://user-images.githubusercontent.com/10846169/47910735-09752b80-de94-11e8-94d4-818a0c68f9f7.png)

**Comment by Frenzie** [comment]
Could you share the feed where this happens so the problem won't need to be recreated?

**Comment by alfureu** [comment]
Sure, and thanks in advance! [http://444.hu/feed/](http://444.hu/feed/)

**Comment by Frenzie** [comment]
Ah, it's not the figcaption but the icon that's inside the figcaption.

![screenshot_2018-11-02_11-48-16](https://user-images.githubusercontent.com/202757/47911254-42fa6680-de95-11e8-8f10-44b523f8545e.png)

**Comment by alfureu** [comment]
You are right. Is it possible to remove, or scale the SVG properly?

**Comment by Frenzie** [comment]
You could always add some custom CSS (or JS), but I'm not sure if there's much else you can do aside from prefiltering. Pinging @Alkarex

**Comment by alfureu** [comment]
I think the easiest way would be to remove any icons/pictures from the figcaption tag. However, the most elegant would be to scale it properly to the feed rendering, as I can imagine there might be pictures which can be listed as Creative Commons (with the appropriate logo) and other cases.

**Comment by Alkarex** [comment]
At a quick glance, we need to make the sanitizer more SVG aware. In particular, the URL is wrong (the `xlinl:href` should have been rewritten to an absolute URL like for the other assets) and currently generates an error 404.

**Comment by Alkarex** [comment]
Fixed in https://github.com/FreshRSS/FreshRSS/pull/2135 by removing SVG images for now. Proper SVG support would require custom sanitizing and URL rewriting of xlink:href, and is left for future work.
In this case, the SVG image was solely used for tracking anyway.
Tests welcome.

**Comment by alfureu** [comment]
Thanks @Alkarex, I think you made the right decision. I appreciate the quick resolution of this, I believe we can close this ticket.

**Comment by Frenzie** [comment]
You can close it yourself as well I believe? :-) Anyway, closing.

**Comment by alfureu** [comment]
Oh, was not aware of this. Thanks for pointing this out @Frenzie. Next time will certainly do!
