### ISSUE TITLE
Receive email notification when new items in feed?

### ISSUE THREAD

**Issue by Legalien** [FreshRSS/FreshRSS#2109]
Is there a way to make FreshRSS send me an email every time there's a new item in any of my feeds?

Thanks :)

**Comment by aledeg** [comment]
You could write an extension for that.

**Comment by Alkarex** [comment]
@Legalien Please see https://github.com/FreshRSS/FreshRSS/issues/2051#issuecomment-430339399
We will continue in that ticket. Closing here, as it is a duplicate.

**Comment by Legalien** [comment]
Thanks you guys. I'll check out the other thread.
