### ISSUE TITLE
Can't create new category while adding feed

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/FreshRSS#2115]
When adding a feed, you can quickly create a category by using the dropdown menu before the "+" and typing the name of the category in the box "New category". When doing so, the category is not created and the feed is added to the default one.

**Comment by Alkarex** [comment]
Hum, the UI could be better, but you need to select *New category* in the list.
We should make a little piece of JavaScript, which only shows the new field name when *New category* is selected.

**Comment by Alwaysin** [comment]
Ah, sure. Misleading, but minor indeed!
