### ISSUE TITLE
Selector CSS

### ISSUE THREAD

**Issue by typhoe** [FreshRSS/FreshRSS#2118]
Hi,

I'm trying to understand and use this function that seems great.

I browse the various issues and found a few reference links (some in issues from 2014) but no real documentation clear enough for a neophyte in CSS...

One of the most usefull link I found in the issues is: https://code.google.com/archive/p/phpquery/wikis/Selectors.wiki

How I proceed:
1. When I find that a feed produces truncated articles in FreshRSS, I open the article in a tab of Chrome, hit F12 then scroll over the html lines (sometime I need to click on the little triangle to open more the hierarchy) in the "elements" tab till what is greyed/selected on the web page is  the (full or only) part I want.
2. I then click on the line (to select it) that gets me the result I want, and click on the 3 dots at the beginning of the line, and then in the drop down menu that appears, hit "Copy / Copy selector"
3. Then the hard part... testing... 
For ex, I get something like: #new_issue > div > div.discussion-timeline > div
Which I translated by "#new_issue .discussion-timeline" and put in the field "CSS Selector" in FreshRSS for the feed I want to modify and then.... wait for the feed to get new articles...
4. and do it again if it's not the result I wanted...

Questions:
1. Is there a better way to do all of that?
2. Is there a hidden option to preview the result of a CSS Selector without waiting for new articles in the RSS feed? 
For now, I cheat because my FreshRSS is in a container so I abuse of the snapshot function... but it's not practical).
I tried to delete all the articles in the feed FreshRSS knew and refresh but it doesn't seem to work that way (It doesn't get again the articles in the rss feed).
3. What is the max size of the CSS Selector field? When I try to put 3 very long CSS selectors (separated by a comma), FreshRSS threw an error... 2 selectors (so less long) were ok...
4. Only CSS Selector are ok, no Xpath (sometime, the syntaxe seems shorter/easier to use)?

Thank you

**Comment by Frenzie** [comment]
Sorry, I overlooked this back in November or didn't have time to reply. (Both of which are strongly correlated.)

1. Yes, right click → inspect element will take you straight there.
2. I don't think so, but you can also (ab)use fetchrss.com. If you click on the little gear icon it'll show the selector.
3. Looks to be 511?
https://github.com/FreshRSS/FreshRSS/blob/e04804d0f67dd43fd3f072b9a127768ee7b7b56c/app/SQL/install.sql.mysql.php#L22
4. Just CSS, see:
https://github.com/FreshRSS/FreshRSS/blob/e04804d0f67dd43fd3f072b9a127768ee7b7b56c/app/Models/Entry.php#L249

**Comment by typhoe** [comment]
Thank you for these answers. 

I'll look into them!
