### ISSUE TITLE
Episodes from a newly added feed show up under the today category

### ISSUE THREAD

**Issue by meminens** [FreshRSS/FreshRSS#2119]
I don't know how to better describe it. Perhaps this is per design. See screenshot below:

![image](https://user-images.githubusercontent.com/42714627/48315837-4bdfec00-e5a9-11e8-84ba-9fee7571cd91.png)

I have added the feed `VASAviation` today and even though there are episodes from last month all episodes appear in the today group.

**Comment by pattems** [comment]
This is intended behavior, per #1782.

Edit: also #2083, and https://github.com/FreshRSS/FreshRSS/issues/1771#issuecomment-359195655

**Comment by meminens** [comment]
Thank you both!

**Comment by lilydjwg** [comment]
I don't intend to persuade you to change your design but FYI, the Mastodon distributed social network doesn't sort by received date but by publish date. I don't see a row of new messages on my timeline when I just follow someone who has a few posts in the past.

**Comment by Alkarex** [comment]
For the record, I consider changing a few internal mechanisms to allow sorting entries on other criteria, such as a a potential future hotness

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/7149
