### ISSUE TITLE
Advisory - FreshRSS - Reflected and Stored Cross-site scripting vulnerabilities 

### ISSUE THREAD

**Issue by DanielBishtawi** [FreshRSS/FreshRSS#2121]
Hello,

While testing the Netsparker web application security scanner we identified Reflected and Stored Cross-site scripting vulnerabilities in FreshRSS. Can you please advise whom shall we contact to disclose the vulnerability details so it can be fixed?

Please email me at daniel@netsparker.com for the technical details.

Looking forward to hearing from you.

Regards,

Daniel Bishtawi
Marketing Administrator | Netsparker Web Application Security Scanner

**Comment by Frenzie** [comment]
Pinging @Alkarex

**Comment by Alkarex** [comment]
Thanks @DanielBishtawi 
I have sent an e-mail to you.
