### ISSUE TITLE
[help] cannot get other apps to connect (Laravel Forge, Ubuntu, ngninx, php7.2)

### ISSUE THREAD

**Issue by Gompje** [FreshRSS/FreshRSS#2129]
I've installed the app on my main server. This server is provisioned by Laravel Forge on DO, running Ubuntu 16.x LTS. It's running a bunch of web apps, including our own SaaS app build with Laravel. I realise Nginx is not officially supported. But it works. somewhat.

Install was a breeze - but getting the api to work with other apps is .. well .. I cannot get it to work. I cannot find a clear up to date path to start debugging to find out what is going on. All the build in checks are getting a green mark or a clear PASS. 

I'm in a mac bubble. 

I got the farthest with Readkit. Connection works, authentication works but then it suddenly disconnects again and says "credentials invalid" (but It has gotten some data, be it a list of folders or some feed names). Never posts.

Reeder doesn't say anything. Just empty. Same on iOS (obviously)

I've gotten another message from Fiery Feeds, saying the content is malformed (but then in a longer user friendlier way)

I'm running in circles, it must be something obvious inside the nginx config or some php var. Thinking session stuff might be it? any ideas?

excerpt from nginx:
```
    location ~ ^(.+?\.php)(/.*)?$ {
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        fastcgi_pass unix:/var/run/php/php7.2-fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        
		fastcgi_param PATH_INFO $2;
		fastcgi_param SCRIPT_FILENAME $document_root$1;
		fastcgi_read_timeout 900s;
		
		fastcgi_buffer_size 128k;
        fastcgi_buffers 256 16k;
        fastcgi_busy_buffers_size 256k;
        fastcgi_temp_file_write_size 256k;
    }
```

**Comment by Gompje** [comment]
ok. so off course I now find the debug info again. its here: https://freshrss.github.io/FreshRSS/en/users/06_Fever_API.html

**Comment by Gompje** [comment]
I've done some CURLS, and they all return data. The server is imho correctly configured json-wise; I use it in my own apps constantly. Not sure what is going on. help?

**Comment by Alkarex** [comment]
@Gompje Having nothing Apple myself, my own debugging options are limited. But could you maybe make a temporary FreshRSS test account on your instance for me?

Maybe @kevinpapst - who implemented this API - could have other suggestions.

**Comment by Alkarex** [comment]
By the way, for Mac OS, FreshRSS and the Vienna RSS client are now compatible https://github.com/FreshRSS/FreshRSS/issues/2091
(In the /dev branch, upcoming FreshRSS 1.13.0, using the Google Reader API)

**Comment by kevinpapst** [comment]
I have tried the Fever API successfully with a handful of Apps, all within the Apple ecosystem. I use it daily with Unread on iOs and Reeder on Mac, so there shouldn't be an issue with the API itself. 
But I am running FreshRSS 1.11.2-dev currently... will see if I can do an update and check the latest version from master.

**Comment by Gompje** [comment]
@Alkarex I've send you a test account on your e-mail. I'm running the dev branch. I've forked the repo  to be able to directly pull it from Github to my server with automatic deploy. 

@kevinpapst are you using Apache or Nginx? If your apps are working, it must be a server issue, I guess? I'm running the dev branch of FreshRss as well.

**Comment by kevinpapst** [comment]
You can try `curl -s -F "api_key=sdfgsdfg" 'https://yourDomain/api/fever.php?api'` and check if it shows any result or an general error, there is also some documentation about debugging the API: 
https://freshrss.github.io/FreshRSS/en/users/06_Fever_API.html

**Comment by Alkarex** [comment]
@Gompje I have just tried your server, and the authentication does not seem to work:

```sh
# ??? is the API password
api_key=`echo -n "alexandre:???" | md5sum | cut -d' ' -f1`

# ??? is your server name
curl -s -F "api_key=$api_key" 'https://???.net/api/fever.php?api' | jq .
{
  "api_version": 3,
  "auth": 0
}
```

Could you please try to apply again your read/write access rights on `./data/`, in particular `./data/fever/`, and then change your password (you can put the same password again).

Then, some files should be there, such as:

```sh
ls -alh data/fever/
total 36K
drwxrwxr-x 2 alex www-data 4,0K nov.   4 14:57 .
drwxrwxr-x 9 alex www-data 4,0K nov.  18 12:40 ..
-rw-rw-r-- 1 alex www-data    5 mai   19  2018 .da74a9c0a1d1????????6aa98bc4-91040a0f437???????????ce8a9181f7b8.txt
-rw-rw-r-- 1 alex www-data    5 mai   19  2018 .da74a9c0a1d1????????6aa98bc4-a84a2ab420c?????????????7c0a1b0f80.txt
-rw-rw-r-- 1 alex www-data    6 nov.   4 14:57 .gitignore
-rw-rw-r-- 1 alex www-data  309 nov.   4 14:57 index.html
-rw-rw-r-- 1 alex www-data    7 juin  12 11:17 .key-da74a9c0a1d1????????6aa98bc4-481b8dd86????????????????a52029519.txt
-rw-rw-r-- 1 alex www-data    5 oct.  21 14:24 .key-da74a9c0a1d1????????6aa98bc4-a84a2ab420c?????????????7c0a1b0f80.txt
-rw-rw-r-- 1 alex www-data    9 oct.  30 17:39 .key-da74a9c0a1d1????????6aa98bc4-c1e6369cefd???????????7f9101f588aa.txt
```

Please try also to enable the following two lines:

https://github.com/FreshRSS/FreshRSS/blob/9d703da026345fa47e892c983e7b4a60176cf100/p/api/fever.php#L60-L61

And re-do the curl commands above, and look at the logs in `./data/users/_/log_api.txt`

**Comment by Alkarex** [comment]
For the record, Reeder-4 now supports the Google Reader API (which is better than Fever API) and that seems to work fine with FreshRSS https://github.com/FreshRSS/FreshRSS/pull/2540
I close this old issue, but feel free to ask if there is any remaining problem
