### ISSUE TITLE
Problème de mise à jour de mes flux

### ISSUE THREAD

**Issue by ejrhoffmann** [FreshRSS/FreshRSS#2132]
Description du problème : quand je lance une mise à jour manuelle des flux, le petit pop-up `actualiser` affiche les flux très rapidement, mais aucun flux n'est actualisé.
Ma configuration:

- v1.12.0

- PHP 7.2

- page checkinstall : tout est au vert.

**Comment by Alkarex** [comment]
Historique du bug : https://diasp.eu.com/posts/c5fbc8409bb30136d66b0007cb0b6c8d

Bonsoir @ejrhoffmann ,
Il me faudrait un peu plus d'information, comme :
* Quelle plateforme / OS ?
* Quelle base de données ?
* Que disent les logs ?
    * Logs JavaScript du navigateur
    * Logs FreshRSS
    * Logs du serveur Web
* Avez-vous mis en place un cron de rafraîchissement ?
* Veuillez ré-appliquer les droits d'accès corrects sur votre répertoire FreshRSS et surtout le sous-répertoire ./data/ (droits en écriture pour le serveur Web).

Si ce n'est pas un serveur sensible et que vous pouvez me faire un accès SSH temporaire, je regarde volontiers. Sinon on doit pouvoir trouver la solution avec quelques tests.

**Comment by ejrhoffmann** [comment]
Bonjour,
Voici les renseignements demandés :
Plateforme / OS : hébergement mutualisé / Debian

Base de données : 
Type de serveur : MariaDB 
Version du serveur : 10.2.18-MariaDB-10.2.18+maria~stretch - mariadb.org binary distribution

Log JavaScript du navigateur :
```
[Exception... "Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIContentPermissionRequest.principal]"  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: jar:file:///usr/lib64/firefox/browser/omni.ja!/components/nsBrowserGlue.js :: prompt :: line 2985"  data: no]  (source inconnue)
NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIContentPermissionRequest.cancel]  nsBrowserGlue.js:3009
```
Log FresgRSS :
```
[Tue, 16 Oct 2018 08:17:47 +0200] [warning] --- Error while PubSubHubbub subscribing to http://feeds.feedburner.com/LinuxLiveUSBCreator
[Tue, 16 Oct 2018 08:17:53 +0200] [warning] --- Error while PubSubHubbub subscribing to http://galacteros.over-blog.com/rss
[Tue, 16 Oct 2018 08:17:55 +0200] [warning] --- Error while PubSubHubbub subscribing to http://feeds.feedburner.com/compegps/pcff
[Tue, 16 Oct 2018 08:18:13 +0200] [warning] --- A feed could not be found at `https://blog.cozycloud.cc/feed/atom`; the status code is `200` and content-type is `text/html; charset=utf-8` [https://blog.cozycloud.cc/feed/atom]
[Tue, 16 Oct 2018 08:18:15 +0200] [warning] --- Error while PubSubHubbub subscribing to https://www.lesnumeriques.com/rss.xml
[Tue, 16 Oct 2018 08:18:17 +0200] [warning] --- cURL error 6: Could not resolve host: www.libre974.re [http://www.libre974.re/reunion/spip.php?page=backend]
[Fri, 19 Oct 2018 17:25:32 +0200] [warning] --- cURL error 6: Could not resolve host: www.libre974.re [http://www.libre974.re/reunion/spip.php?page=backend]
[Fri, 19 Oct 2018 17:25:34 +0200] [warning] --- Error while PubSubHubbub subscribing to https://www.lesnumeriques.com/rss.xml
[Fri, 19 Oct 2018 17:25:35 +0200] [warning] --- A feed could not be found at `https://blog.cozycloud.cc/feed/atom`; the status code is `200` and content-type is `text/html; charset=utf-8` [https://blog.cozycloud.cc/feed/atom]
[Fri, 19 Oct 2018 17:25:56 +0200] [warning] --- Error while PubSubHubbub subscribing to http://feeds.feedburner.com/compegps/pcff
[Fri, 19 Oct 2018 17:25:59 +0200] [warning] --- Error while PubSubHubbub subscribing to http://galacteros.over-blog.com/rss
[Fri, 19 Oct 2018 17:26:04 +0200] [warning] --- Error while PubSubHubbub subscribing to http://feeds.feedburner.com/LinuxLiveUSBCreator
[Fri, 19 Oct 2018 17:26:20 +0200] [warning] --- Error while PubSubHubbub subscribing to http://feeds.feedburner.com/packfs
[Fri, 19 Oct 2018 17:26:20 +0200] [warning] --- cURL error 22: The requested URL returned error: 403 Forbidden [http://www.voilesetvoiliers.com/rss=photo/template=rss_feed/]
[Fri, 19 Oct 2018 17:26:23 +0200] [warning] --- Error while PubSubHubbub subscribing to https://medium.com/feed/snips-ai
[Fri, 19 Oct 2018 17:26:25 +0200] [warning] --- cURL error 22: The requested URL returned error: 403 Forbidden [http://www.voilesetvoiliers.com/rss=video/template=rss_feed/]
[Fri, 19 Oct 2018 17:26:25 +0200] [warning] --- cURL error 22: The requested URL returned error: 404 Not Found [http://openstreetmap.fr/rss.xml]
[Fri, 19 Oct 2018 17:26:29 +0200] [warning] --- Error while PubSubHubbub subscribing to http://feeds.feedburner.com/padreblog
[Fri, 19 Oct 2018 17:26:30 +0200] [warning] --- Error while PubSubHubbub subscribing to https://www.blogger.com/feeds/35052505/posts/default
[Fri, 19 Oct 2018 17:26:31 +0200] [warning] --- cURL error 22: The requested URL returned error: 403 Forbidden [http://www.voilesetvoiliers.com/rss=article/template=rss_feed/]
[Fri, 19 Oct 2018 21:33:53 +0200] [warning] --- cURL error 22: The requested URL returned error: 403 Forbidden [http://www.voilesetvoiliers.com/rss=article/template=rss_feed/]
[Fri, 19 Oct 2018 21:33:56 +0200] [warning] --- cURL error 22: The requested URL returned error: 404 Not Found [http://openstreetmap.fr/rss.xml]
[Fri, 19 Oct 2018 21:33:57 +0200] [warning] --- https://medium.com/feed/snips-ai is invalid XML, likely due to invalid characters. XML error: Invalid character at line 28, column 39 [https://medium.com/feed/snips-ai]
[Fri, 19 Oct 2018 21:33:57 +0200] [warning] --- cURL error 22: The requested URL returned error: 403 Forbidden [http://www.voilesetvoiliers.com/rss=video/template=rss_feed/]
[Fri, 19 Oct 2018 21:33:57 +0200] [warning] --- cURL error 22: The requested URL returned error: 403 Forbidden [http://www.voilesetvoiliers.com/rss=photo/template=rss_feed/]
[Fri, 19 Oct 2018 21:34:01 +0200] [warning] --- cURL error 6: Could not resolve host: www.internetsanscrainte.fr [http://www.internetsanscrainte.fr/blog-actu/feed]
[Fri, 19 Oct 2018 21:34:13 +0200] [warning] --- cURL error 7: Failed to connect to f-droid.org port 443: Connection timed out [https://f-droid.org/feed.xml]
[Fri, 19 Oct 2018 21:34:32 +0200] [warning] --- A feed could not be found at `https://blog.cozycloud.cc/feed/atom`; the status code is `200` and content-type is `text/html; charset=utf-8` [https://blog.cozycloud.cc/feed/atom]
[Fri, 19 Oct 2018 21:34:39 +0200] [warning] --- cURL error 6: Could not resolve host: www.libre974.re [http://www.libre974.re/reunion/spip.php?page=backend]
[Wed, 31 Oct 2018 18:39:39 +0100] [warning] --- SQL ALTER GUID case sensitivity...
[Wed, 31 Oct 2018 18:39:40 +0100] [warning] --- SQL CREATE TABLE tag...
[Wed, 31 Oct 2018 19:21:04 +0100] [warning] --- Cannot move feed `77` in the category `1`
[Sat, 10 Nov 2018 04:19:29 +0100] [warning] --- Error while PubSubHubbub subscribing to http://feeds.feedburner.com/padreblog
[Wed, 14 Nov 2018 18:01:01 +0100] [warning] --- Error while PubSubHubbub subscribing to http://feeds.feedburner.com/padreblog
```
Je n’ai pas mis en place de CRON de rafraichissement.

Qu'en pensez-vous ?
Merci.
Bon WE.

**Comment by Alkarex** [comment]
Hum, je ne vois pas de problème particulier.
Avez-vous reçu des nouveaux articles récemment, ou aucun ?

Si aucun, pourriez-vous changer la ligne `environment` dans votre fichier `./FreshRSS/data/config.php` et regarder à nouveau les logs après un rafraîchissement ?

```
'environment' => 'development',
```

Si cela ne donne toujours rien, pourriez-vous éventuellement me faire un compte temporaire sur votre FreshRSS ?

**Comment by ejrhoffmann** [comment]
Bonsoir,
Merci de vous pencher sur mon problème ! 
Ces derniers jours aucun rafraichissement ne fonctionnait. Les choses se déroulent toujours de la même façon : défilement rapide des flux dans la l'affichage en haut et pas de mise à jour.
Ce soir, je viens de lancer un rafraichissement qui a fonctionné. Je n'arrive pas à voir ce qui a changé !
Je vais tenter la modif de config.php. Je vais tester plusieurs jours et reviendrai en rendre compte ici.
En attendant, je vous ai créé un compte sur https://f.hfn.re/p/i/
Id : test
MdP : pourtester
Merci beaucoup pour votre aide !
Bonne soirée,

**Comment by Alkarex** [comment]
@ejrhoffmann Désolé pour le retard. Je suis en train de tester. Je constate déjà une erreur WebSub :
> JSON not found for PubSubHubbub

Cela est très probablement dû à de mauvais droits d'accès sur `./data/` ou ses sous-répertoires.

Pourriez-vous ré-appliquer les droits (exemple à adapter selon votre cas) :

```sh
cd ./FreshRSS/
sudo chown -R :www-data . && sudo chmod -R g+r . && sudo chmod -R g+w ./data/
```

Et puis montrer le contenu de ./data/ :

```sh
cd ./FreshRSS/
ls -alh ./data/
```

**Comment by Alkarex** [comment]
I just received a new update without problem, in the test account :-)

**Comment by ejrhoffmann** [comment]
Bonjour @Alkarex ,

Quelques infos :
Depuis le 27 novembre, la ligne `environnement` du fichier `./FreshRSS/data/config.php` a été modifiée. Cela n'apporte aucun changement sur le comportement de FreshRSS.

Concernant les droits sur /data, je n'ai pas accès directement au serveur, car il s'agit d'un hébergement mutualisé. En revanche, je peux contrôler et modifier les droits via Filezilla sous forme octal.
Je constate que /data et son contenu (répertoires et fichiers) sont majoritairement `750` avec quelques exceptions. Voulez-vous que je passe les droits de /data et son contenu (répertoires et fichiers) à `760` ?

Merci. Bon dimanche !

**Comment by math-GH** [comment]
Is this issue still actual? Could someone please give an English translated summary?

**Comment by Alkarex** [comment]
en: This is an old, forgotten debugging dialogue. Let's close for now.

fr: Fermons, mais n'hésitez pas à ouvrir un nouveau ticket.
