### ISSUE TITLE
Menu jumping

### ISSUE THREAD

**Issue by alfureu** [FreshRSS/FreshRSS#2143]
I have an issue, as seen on the following screenshot, the Menu on the left is jumping as I go through the posts with J and K keys. Sometimes the screen gets 'stuck' in such a state:

![freshrss2](https://user-images.githubusercontent.com/10846169/48770539-f0a3ad00-ecbe-11e8-8ccd-bedc2c120a33.png)

I have enabled the following Extensions, which, I believe, may also affect this behaviour:
- CustomCSS (0.2)
- CustomJS (0.2)
- ImageProxy (0.4)
- StickyFeeds (0.1)
- YouTube (0.7)
- Dilbert (0.3)
- Teem (0.1)
- FixedNavMenu (0.1)
- KeepFolderState (0.1)
- MobileScrollMenu (0.2)
- SmartMobileMenu (0.1)
- TouchControl (0.2)
- AutoRefresh (1)
- RedditImage (0.1)
- ReadingTime (1)

**Comment by Alkarex** [comment]
@DOFfactory I hope this will be fixed by the nice work done by @pattems in https://github.com/FreshRSS/FreshRSS/pull/2117 and hopefully landing soon in the /dev branch.
Related: https://github.com/FreshRSS/FreshRSS/issues/1588 , https://github.com/FreshRSS/FreshRSS/issues/1593

**Comment by alfureu** [comment]
Very happy about reading this @Alkarex. Thanks!

**Comment by Alkarex** [comment]
@DOFfactory Would you be so kind to test the current /dev version, which has reworked this part? Please open a new issue if it is still unresolved, or comment here if solved.

**Comment by alfureu** [comment]
Thanks @Alkarex seems like it is working.

**Comment by Alkarex** [comment]
Great, thanks for the feedback :-)

**Comment by alfureu** [comment]
Hi @Alkarex. I am back again, as requested, with a request for a tweak. The issue is with the Microsoft Edge browser, where the scrollbar (despite the enabled settings in Ease of Access in Windows 10) is not autohiding. See the attached screenshot. It would be great to provide the extra tweaks for Edge, and make the scrollbar completely disappear, or appear only when the left menu is longer than the page size. 
![freshrss slide](https://user-images.githubusercontent.com/10846169/50390039-1e529a80-0732-11e9-9488-0b0b8cb93039.png)

**Comment by pattems** [comment]
Hi there, @DOFfactory. I'm responsible for the refactor PR. Scrollbar auto-hiding when there's no need to scroll works fine for me in Edge, and I'm sorry it doesn't for you! What Windows 10 accessibility feature are you talking about? I'm wondering if that might somehow be affecting the scrollbar's behavior.

Another thought that comes to mind: how much space do you have at the bottom of the list of categories? There's a fairly large amount of space built in at the bottom of the list, to ensure that there's enough room for a configuration dropdown to appear without having to scroll down again after it's opened. If you have a large amount of categories, some of that buffer space might be pushing past the point that you'd need to scroll, causing the scrollbar to appear.

**Comment by alfureu** [comment]
Hi @pattems, thanks for getting back to me. 

Regarding your first comment, please find attached the screenshot of the setting. 
![scrollbar](https://user-images.githubusercontent.com/10846169/50390459-a9825f00-0737-11e9-9479-0f18e7177d95.png)

I think you  might be right with your 2nd comment. There is fairly big space for the left menu, which enables the scrollbar for me. 100% of the time I have these categories collapsed, so no need to have such an extra space. It would be nice to make this smaller.

**Comment by pattems** [comment]
since you use the Custom CSS extension, try setting `.tree-bottom` to `display:none;` and see if that might clear things up for you.

Another Custom CSS option, as long as you never need to scroll, would be to set `#sidebar` to `overflow-y:hidden;`

**Comment by alfureu** [comment]
Hi @pattems, thanks for this, the `.tree-bottom` option worked fine. However, I would prefer a more out-of-the-box version in this, as I do not like extra tweaks like this, it usually breaks things after updates.

On another note, for the attention to @Alkarex, the Custom CSS in the Extensions is showing **Update available**, while I downloaded the v0.2 from git. Might need some look to correct this.

Again, thanks for the quick advice.

**Comment by alfureu** [comment]
Hello guys, in the meantime I came across of the following webpage: [http://www.uxrim.com/slim-scroll/](http://www.uxrim.com/slim-scroll/).

On the Demo page, I wonder whether FreshRSS could implement the 1st option: [https://rawgit.com/venkateshwar/slim-scroll/master/tests/test1/index.html](https://rawgit.com/venkateshwar/slim-scroll/master/tests/test1/index.html)

**Comment by Alkarex** [comment]
Hello @DOFfactory 
The JavaScript has been rewritten in the current /dev (future 1.14.0), and there were many CSS changes in versions 1.13.x. Could you please check again if the problem is still there?

**Comment by alfureu** [comment]
Hi @Alkarex happy to hear this. Unfortunately, I do not have the option to use the /dev as I am running it as an app on a NAS. The latest version it offers is: 1.13.1.
