### ISSUE TITLE
Article cannot be collapsed after marking it as unread

### ISSUE THREAD

**Issue by pieqq** [FreshRSS/FreshRSS#2144]
Hello! First of all, thanks a lot for this great feed reader. I recently switched to it after reading about it on Hacker News and I'm very happy with it! (not to mention it's released under AGPL 3!)

I've noticed an issue when trying to collapse an article after marking it as unread (for instance when you realize the article is way too long and you want to keep it for later). I thought it was a theme problem (I'm using the newly released Swage theme), but it also happens with other themes.

- Version tested: 1.12.0
- Browser used: Firefox 63.0
- OS: Ubuntu Linux 18.04.1

## Steps to reproduce

1. From the default view, open an article
2. Try to close the article by clicking on its title
3. Reopen the article
4. Click on the "Mark as unread" icon (left of the title)
5. Try to close the article like in step 2

## Expected results
In step 2, the article is closed. In step 5, it closes too.

## Actual results

In step 2, the article is closed as expected (OK).

However, in step 5, it does not close (NOK!). Marking it as read again doesn't change anything: from now on, the article cannot be collapsed and you need to refresh the page to do so.

**Comment by Alkarex** [comment]
Hello,
Could you please try our /dev branch ?
This should be fixed already
https://github.com/FreshRSS/FreshRSS/issues/2085
https://github.com/FreshRSS/FreshRSS/pull/2092

**Comment by pieqq** [comment]
That was a quick feedback...

I missed #2085, I didn't use the right keywords when trying to check for duplicates.

I'll try to find time to test this. In the meantime, I'll close this issue.

Thanks a lot!
