### ISSUE TITLE
[feature request] Show all feeds with a warning

### ISSUE THREAD

**Issue by ddeimeke** [FreshRSS/FreshRSS#2146]
I am a heavy RSS user and subscribed to around 600 feeds (reading Twitter via RSS-Bridge).

Would it be possible to get a view in subscription management which shows all feeds with a warning or an error?

**Comment by Alkarex** [comment]
Hello @ddeimeke 
Implemented in https://github.com/FreshRSS/FreshRSS/pull/2160
Tests welcome :-)

![image](https://user-images.githubusercontent.com/1008324/49331243-42d7ae80-f59a-11e8-840d-1d1ba786ad18.png)

**Comment by ddeimeke** [comment]
Can I switch to the development branch and back to stable without any side effects?

**Comment by Frenzie** [comment]
https://github.com/FreshRSS/FreshRSS/compare/e04804d0f67dd43fd3f072b9a127768ee7b7b56c...dev

At a glance I don't see any DB changes, so in this case that might work. I wouldn't do it without a backup though. :-)
