### ISSUE TITLE
Feed can not be updated with DokuWiki feeds

### ISSUE THREAD

**Issue by ddeimeke** [FreshRSS/FreshRSS#2147]
I get the error "feed can not be updated" when using username and password with a DokuWiki feed (adding "?u=USERNAME&p=PASSWORD" to the feed URL.

See https://www.dokuwiki.org/syndication#feeds_and_acls

**Comment by Alkarex** [comment]
Are you sure your feed is using URL parameters for passing credentials, and not HTTP auth?
I have just tried on https://www.dokuwiki.org but their feed is redirected to Feedburner, so I could not test.
Could you please make a temporary account for me so I can test?
If not possible, try to run the following test at least:

```sh
curl -v 'https://docuwiki.example.net/feed.php?u=...'
```

And also the result of https://validator.w3.org/feed/

**Comment by ddeimeke** [comment]
As you might have seen on the DokuWiki-site, it is all in the URL.

Sure I can create a user for you, can you please send your e-mail address to me. You can find mine on d5e.org. Thank you!

**Comment by Alkarex** [comment]
So far, the feed (including URL credentials) seems to work fine for me. I will test a bit more.
On your side, please look in your FreshRSS logs to check whether you have any more precise error message.

**Comment by ddeimeke** [comment]
@Alkarex Thank you.

I don't know why, but it works now. Maybe one of the last updates did the trick and it was a php error beforehand.
