### ISSUE TITLE
Suggestion: CSS Print Styling

### ISSUE THREAD

**Issue by sbrl** [FreshRSS/FreshRSS#2149]
When I use the share -> print option, it appears as if all the CSS is removed. It's be great f I could customise this via CSS, as then I could make it look awesome :D

By using the _CSS Paged Media_ standard, we can change the background colour of the page, add heads and footers, and more! I've got a [basic stylesheet](https://starbeamrainbowlabs.com/theme/basic.css) I've thrown together to experiment with this.

**Comment by aledeg** [comment]
@sbrl I've added a way to transfer css files to the print page. That means you can use the CustomCss extension to do whatever you'd like to change the display of your printed articles.
You can give it a try!
