### ISSUE TITLE
[Feature Request] Add single article

### ISSUE THREAD

**Issue by Pofilo** [FreshRSS/FreshRSS#2150]
Hello !

This tool is amazing, however, sometimes I just want to add an article from a blog and not all the blog (a way to store this particular article to read it later). Am I the only one thinking about something like that ?

Thanks for your read !

**Comment by aledeg** [comment]
I think you should use other tools design for that purpose. Maybe something like Pocket or Wallabag. The purpose of FRSS is to retrieve articles from feeds.

**Comment by Pofilo** [comment]
The main point yeah, but this way I would have everything on the same place ^^

But you're right, thanks for the answer !
