### ISSUE TITLE
New feeds with year date only displayed as read.

### ISSUE THREAD

**Issue by laBecasse** [FreshRSS/FreshRSS#2154]
Hello,

I subscribe to this [feed](https://dblp.org/pers/xs/a/Abiteboul:Serge.rss) one year ago. Since there are new entries in the feed. But there are displayed as read by default in freshrss. 

@Alkarex said that the problem is related to the purge system, in particular the limit date: https://github.com/FreshRSS/FreshRSS/blob/58becd13db93d415608e8e852b35492863af07ed/app/Controllers/feedController.php#L373-L375

How can we improve this ?

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/blob/58becd13db93d415608e8e852b35492863af07ed/app/Controllers/feedController.php#L383-L385

**Comment by ghost** [comment]
I have increased the limit date and it have solved the problem. Feeds are now added as unread :)

**Comment by Alkarex** [comment]
@laBecasse Your case should be fixed in the /dev branch with https://github.com/FreshRSS/FreshRSS/pull/2335
Tests welcome :-)
