### ISSUE TITLE
Blast! This feed has encountered a problem. Please verify that it is always reachable then update it.

### ISSUE THREAD

**Issue by maobaoqi** [FreshRSS/FreshRSS#2155]
Hi, I subscribed a vaild rss source and freshrss will show a invaild icon before this rss source after a while. When I open the rss source edit page, it reminder as the title string. If I delete this source and add it again, the invaild icon disappear. where is wrong?

**Comment by Alkarex** [comment]
I have not fully understood your problem description, but could you please share the address of the problematic feed?

**Comment by Frenzie** [comment]
I would suspect a fluke on the side of the feed in question (temporarily unreachable).

**Comment by maobaoqi** [comment]
ok, there is rss source: http://feed.luobo8.com/

**Comment by Alkarex** [comment]
@maobaoqi This feed seems to work fine for me. Please try again a bit later, and report whether it works again or not (in which case we can test a bit more).

**Comment by maobaoqi** [comment]
eh，It seems not work any more. 
![snipaste_20181129_084714](https://user-images.githubusercontent.com/3353791/49191893-858b6200-f3b3-11e8-8c6d-8a2415d3799e.png)

**Comment by Alkarex** [comment]
It works fine when I test it. I suspect that the feed or the feed's server have occasional problems. Please check the FreshRSS logs when this happens.

**Comment by NanoSector** [comment]
I'm not seeing any issues with that specific feed either.

**Comment by edsu** [comment]
FWIW I've noticed that correcting a broken feed URL with the correct one continues to trigger the "Blast" error message.
