### ISSUE TITLE
Suggestion for improvement of Reader Mode

### ISSUE THREAD

**Issue by pattems** [FreshRSS/FreshRSS#2169]
Perhaps Reader mode should include the sidebar, collapsed by default like in the mobile view, in order to switch feeds without leaving reader mode.

This, with a couple trivial modifications, would also enable favicon & title updating in #2168.

**Comment by Alkarex** [comment]
This sounds like a great idea 👍

**Comment by Alkarex** [comment]
Implemented by @pattems in https://github.com/FreshRSS/FreshRSS/pull/2180
