### ISSUE TITLE
Vimeo feed problem

### ISSUE THREAD

**Issue by taobrad** [FreshRSS/FreshRSS#2171]
I have a number of feeds running which work fine. Vimeo feeds are the only problem.

I'm running the latest version of FreshRSS (updated yesterday).

Here is one of the problem feeds: https://vimeo.com/channels/wnbr/videos/rss

This url works fine on the initial actualization but changes to this right after: https://vimeo.com/channels/wnbr/videos/channels/wnbr/videos/rss

Subsequent efforts to update the feed produce this in the log:
cURL error 22: The requested URL returned error: 404 Not Found [https://vimeo.com/channels/wnbr/videos/channels/wnbr/videos/rss]

Thanks in advance for any suggestions...

**Comment by Alkarex** [comment]
This feed contains a wrong `rel="self"`:

```xml
<atom:link rel="self" href="https://vimeo.com/channels/wnbr/videos/channels/wnbr/videos/rss"/>
```

The best would be more Vimeo to fix their feeds. Otherwise, we need to make a special case like an extension to strip out this part before parsing, or a new FreshRSS per-feed option to disable following `self`.

**Comment by math-GH** [comment]
I checked it. The feed is (right now) a valid feed, but it is a little bit weird, because of empty titles.

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fvimeo.com%2Fchannels%2Fwnbr%2Fvideos%2Frss

@taobrad Is it still an issue for you?

**Comment by taobrad** [comment]
No. Just stopped using Vimeo. Thanks.
