### ISSUE TITLE
Main stream menu scrolls down faster than articles, instead of being pinned at the top

### ISSUE THREAD

**Issue by mrhanman** [FreshRSS/FreshRSS#2173]
The Main stream menu doesn't stay put when scrolling through the articles as expected.  Instead, it moves down off the screen.  This is in the latest release of Chrome on Windows 10.

**Comment by pattems** [comment]
Are you talking about something like is happening with #2143?

If I'm understanding your issue, this will be addressed when #2117 is finished, which will hopefully be soon.

**Comment by mrhanman** [comment]
This is still happening to me with 1.14.0.  Just to be clear, here's a gif of what I'm talking about.

![scroll](https://user-images.githubusercontent.com/2364728/55601913-c4963f00-5728-11e9-88ec-e5d63ddcc73d.gif)

**Comment by Alkarex** [comment]
Hello,
* Do you have any FreshRSS extension? If so, please disable them.
* Could you please post a screenshot of your FreshRSS reading options? 
* Could you please try the current /dev branch?

**Comment by mrhanman** [comment]
Disabling the extensions seems to have fixed it.  I'm not sure which one caused the issue, as I've re-enabled them and it still works.

**Comment by pattems** [comment]
@mrhanman, would you mind letting us know which extensions you're using? Being able to identify which one is causing that might let me submit a patch for it to prevent that from happening for anybody else.

What you were seeing is weird behavior from sticky elements being inside fixed position elements, so it's probably some sidebar extension.

**Comment by Alkarex** [comment]
@mrhanman FreshRSS 1.14.1 has just been released. Please try with that version, without any extension, and let us know. Just open a new issue if the problem is still there.
