### ISSUE TITLE
Setup Issue on database configuration page

### ISSUE THREAD

**Issue by stinkcheese** [FreshRSS/FreshRSS#2175]
So im on the database config page during the initial setup of FreshRSS. I'm using MySQL for the time being and have create the DB called FreshRSS and granted a user permissions for the DB. When i hit continue, im getting an unknown error message. 
I'm sure i am missing something during the setup process but guides that i am finding aren't covering this part of the setup. 
Any information would be helpful. Keep in mind, I'm a Linux noob..

**Comment by Frenzie** [comment]
What's the precise error message? Could you be missing the PHP MySQLi extension, for instance?

**Comment by Alkarex** [comment]
Hello @stinkcheese 
For a first attempt, I would suggest using SQLite, which is much easier, and with fine performance for small installations.
Otherwise with MySQL, it might be easier to let FreshRSS build the database itself, as long as its user is allowed to do so. This is what FreshRSS will do by itself: 

https://github.com/FreshRSS/FreshRSS/blob/26e3805d1ffbba5c923ea6e54eba7a765392f0b1/app/SQL/install.sql.mysql.php#L2

**Comment by stinkcheese** [comment]
> Hello @stinkcheese
> For a first attempt, I would suggest using SQLite, which is much easier, and with fine performance for small installations.
> Otherwise with MySQL, it might be easier to let FreshRSS build the database itself, as long as its user is allowed to do so. This is what FreshRSS will do by itself:
> 
> [FreshRSS/app/SQL/install.sql.mysql.php](https://github.com/FreshRSS/FreshRSS/blob/26e3805d1ffbba5c923ea6e54eba7a765392f0b1/app/SQL/install.sql.mysql.php#L2)
> 
> Line 2 in [26e3805](/FreshRSS/FreshRSS/commit/26e3805d1ffbba5c923ea6e54eba7a765392f0b1)
>  define('SQL_CREATE_DB', 'CREATE DATABASE IF NOT EXISTS `%1$s` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;');

Sorry for the limited information. Before i provide that, is there an actual install script that i can use to setup the whole thing? I tried to run the mysql script that you linked here but it does not want to run.

**Comment by Frenzie** [comment]
That is automatically included by the install script. By itself it would be missing the information that you fill out during the installation process.

**Comment by stinkcheese** [comment]
> That is automatically included by the install script. By itself it would be missing the information that you fill out during the installation process.

Would you be able to tell the location of the install script? I have a feeling im making this harder than it needs to be..

**Comment by Frenzie** [comment]
The install script is in app/install.php, but that in turn is supposed to be included from the regular index:

https://github.com/FreshRSS/FreshRSS/blob/e04804d0f67dd43fd3f072b9a127768ee7b7b56c/p/i/index.php#L26-L27

You can, however, use the CLI to do the same thing without a browser:

https://github.com/FreshRSS/FreshRSS/tree/44bd07e506ade204151c276fdc05994d51efdd7a/cli#commands

Does your phpinfo() include the proper MySQL extensions?

**Comment by math-GH** [comment]
Is this issue still relevant for 1.19/1.20?
