### ISSUE TITLE
FreshRSS not working with FeedMe

### ISSUE THREAD

**Issue by TechArtisanIO** [FreshRSS/FreshRSS#2197]
I've been trying with little success to get my FreshRSS install to sync with the FeedMe app on my Android phone. Things I've done:

- I've gone into the Authentication Settings and enabled Mobile API access. 
- I've also gone to the Profile Settings and tested the server configuration and it says, "Pass". 
- I've copied the corresponding API address and input it in the FeedMe app together with the default username (admin) and my assigned API password. 

When I click the login button in the FeedMe app after inputting the above info, everything appears to work just fine. I get no error messages. However, none of my feeds/subscriptions ever show up and when click the sync button I get the following error, "Authentication expired, please, re-authenticate now!" I've tried to re-authenticate over and over and over again, but the same thing keeps happening. 

What am I doing wrong?

**Comment by pattems** [comment]
Have you updated to 1.13.0 (which just came out today), or are you on 1.12.0?

*edit: There was some greader API stuff that changed in 1.13.0. If you're on the new version, it may be related to that; I can't seem to replicate your issue on 1.12.0, in any case.

*edit the second: I've now tested on 1.13.0, and still can't replicate your issue, so it doesn't appear to be an API issue.

**Comment by Alkarex** [comment]
Hello,
I cannot reproduce the problem either. Work for me with FeedMe v3.9, FreshRSS 1.13.0.

How did you install FreshRSS (git, Docker, ZIP...) and on what platform?

Please make sure that the address you type in FeedMe ends with `greader.php`, like `http://freshrss.example.net/api/greader.php`.

Suggestions:

1. Update your `data/config.php` with the following, to get more debugging information:

```
'environment' => 'development',
```

2. Check your logs:
    * Web server / PHP logs
    * FreshRSS API log in `./data/users/_/log_api.txt`
    * FreshRSS logs in `./data/users/you/log.txt`

If you want, you are welcome to send me a temporary account on your FreshRSS instance [by e-mail](http://alexandre.alapetite.fr/cv/) so I can test from my side. Otherwise, you can also test manually by following the examples at the bottom of:
https://freshrss.github.io/FreshRSS/en/users/06_Mobile_access.html

**Comment by TechArtisanIO** [comment]
I'm still on FreshRSS 1.12.0 and FeedMe v3.8.5. I'm hosting my FreshRSS install on DigitalOcean via Cloudron. 

When I initially put everything in, it take my login information just fine, but then nothing actually loads. I just get the little spinning loading icon, but none of my feeds actually show up. I am running this on a HTTPS enabled domain, so do I need to have the HTTPS connection option checked in FeedMe? I've tried enabling it, but doesn't seem to do anything.

I'm busy this morning, but will check my logs here in a bit. If that fails, then I'll set @Alkarex with a temp account to see what he can find. Thanks for the help!

Here's a photo of the error message I receive after logging in, closing the app, and then reopening it:

![screenshot_20181223-102911](https://user-images.githubusercontent.com/7684997/50385605-ec8ff400-069d-11e9-96ce-290da1e9b057.jpg)

**Comment by Alkarex** [comment]
Other nginx examples:
* https://github.com/FreshRSS/FreshRSS/issues/1515#issuecomment-298258854
* https://github.com/FreshRSS/FreshRSS/issues/1579#issuecomment-308504186

Alternatives include using our Docker deployment, or Apache.

**Comment by ahelton** [comment]
@Alkarex Sent you an email. I'm still having no luck. Everything appears to be setup correctly. I don't see anything of note in the logs.

**Comment by TechArtisanIO** [comment]
@Alkarex This issue has been resolved and can be closed. Thanks!

**Comment by Alkarex** [comment]
Thanks for the fix @gramakri and for the feedback @ahelton 👍

**Comment by bllngr** [comment]
@Alkarex: I'm having the exact same issues using the official docker image. Should I open a new report, and/or send you the ``log_api.txt``?

**Comment by Alkarex** [comment]
@sqrt Would you mind trying the `freshrss/freshrss:dev` version?

**Comment by bllngr** [comment]
After updating to ``freshrss/freshrss:dev``, and setting up the account in FeedMe again (had to remove it first), it seems to work correctly. So I guess it's a case of #2235?

**Comment by Alkarex** [comment]
Thanks for the quick test @sqrt . Yes, most likely.
