### ISSUE TITLE
Gestion des caractères

### ISSUE THREAD

**Issue by Jean-Mich-Much** [FreshRSS/FreshRSS#2211]
Bonjour,

Comme vous avez pu le remarquer le flux rss de Clubic est un cas d'école : entre les caractères qui ne s'affichent pas correctement et les doublons, il y a de quoi s'amuser... pour la gestion des caractères, je vous apporte une solution que j'utilise sur un petit parser maison, elle est tout simple, diablement efficace et rapide à mettre en place :
mb_convert_encoding($title,'HTML-ENTITIES',mb_detect_encoding($title,'UTF-8,UTF-7,ASCII,EUC-JP,SJIS,eucJP-win,SJIS-win,JIS,ISO-2022-JP,ISO-8859-1,UTF-16,UTF-32,ISO-8859-15,CP1252,CP1251'));

mb_convert_encoding a la particularité en forçant la conversion d'encodage en HTML-ENTITIES (important) de reconnaître 99,99% des caractères même les plus fantaisistes et de normaliser la chaîne de caractères (même si la chaîne contient 3 encodages différents, multi-octets ou pas sur des caractères contigus dans un même mot par exemple), vous pouvez l'associer à mb_detect_encoding mais ce n'est pas obligatoire tout comme 'UTF-8,UTF-7,ASCII,EUC-JP... qui peut être remplacé par 'auto'. Pour les doublons, la solution semple être l'utilisation de "array_unique" sur les "link" mais je n'ai pas travaillé dessus et je n'ai donc pas de solution toute prête à vous proposer mais la piste semble intéressante.

En espérant vous avoir aidé, amicalement :)

**Comment by Alkarex** [comment]
Bonsoir,
Est-ce qu'il n'y as pas de problème finalement ? Je n'ai en tout cas pas de problème d'encodage avec Clubic. Si tel est le cas pour vous, pourriez-vous fournir le lien RSS exact ?

**Comment by Jean-Mich-Much** [comment]
Bonjour, j'ai clos parce que je pensais que c'était pas assez important comme bug, oui il y a des petits problèmes sur le flux rss de clubic https://www.clubic.com/articles.rss
Si vous regardez la news "Plus que 24H pour le forfait Free mobile 50Go à 8,99 par mois", vous verrez que le symbole euro n’apparait pas par exemple après 8,99, après avoir essayé un iconv ou un utf8_encode rien n'y fait, sauf avec la solution proposée ci-dessus (trouvé par hasard), si vous ouvrez le flux rss de clubic dans notepad2 ou notepad++ qui permettent d'identifier différents encodages, vous verrez que l'encodage des caractères n'est pas clean du tout (car je voulais comprendre pourquoi ce flux spécifique a tant de petits problèmes). J'avais repéré aussi sur d'autres flux des caractères qui ne s'affichaient pas correctement mais cela devait arriver genre 1 fois par semaine alors que sur Clubic c'est pratiquement tous les jours, du coup j'avais trouvé cette solution avec mb_convert_encoding (voir plus haut) : depuis plus de problèmes ! Contre partie vu que vous convertissez tous les caractères spéciaux ou accentués en HTML-ENTITIES, forcément la base de données est un peu plus lourde mais c'est anecdotique :) Amicalement.

**Comment by Frenzie** [comment]
Voir aussi https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.clubic.com%2Farticles.rss

**Comment by Jean-Mich-Much** [comment]
J'avais vu cela aussi :)

**Comment by Alkarex** [comment]
Leur signe € (par exemple) est codé `C2 80` (dans je ne sais trop quel encodage) au lieu de `E2 82 AC` en UTF-8. Vu que le flux est déclaré en UTF-8 au niveau HTTP, ainsi qu'au niveau XML, envoyé en application/xml (qui a UTF-8 comme encodage par défaut) et qu'une partie du document est clairement en UTF-8 valide, il ne me serait pas possible de corriger ce soucis sans créer d'autres problèmes.

**Comment by Alkarex** [comment]
P.S. : pour les doublons, je compte bientôt ajouter des fonctions de filtrages

**Comment by Jean-Mich-Much** [comment]
Bonjour, pour la gestion des caractères, c'est pas grave surtout que cela concerne uniquement un site et j'ai ma petite astuce de programmeur du dimanche haha, par contre pour la prise en charge des doublons : c'est une bonne chose ! J'en profite pour remercier tous les contributeurs : cet agrégateur est juste le meilleur et j'en ai essayé ! Merci encore :)
