### ISSUE TITLE
actualize_script.php writing to stderr inappropriately

### ISSUE THREAD

**Issue by candrews** [FreshRSS/FreshRSS#2212]
On the `dev` branch in the last few days, `actualize_script.php` (which is run using cron) has been writing non-error information to stderr. In my setup, when a cron job writes to stderr, I get an email. Can you please fix FreshRSS so goes back to only writing error information to stderr?

Here's the output of running  `actualize_script.php`:
```
RESULT CODE: 0

ERROR OUTPUT:
FreshRSS[23415]: FreshRSS Start feeds actualization...
FreshRSS[23415]: SimplePie GET https://github.com/RadeonOpenCompute/ROCm-OpenCL-Driver/releases.atom
FreshRSS[23415]: SimplePie MD5 cache match for https://github.com/RadeonOpenCompute/ROCm-OpenCL-Driver/releases.atom
FreshRSS[23415]: SimplePie GET https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime/releases.atom
FreshRSS[23415]: SimplePie MD5 cache match for https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime/releases.atom
FreshRSS[23415]: FreshRSS feeds actualization done.

STANDARD OUTPUT:
Starting feed actualization at 2019-01-07T14:15:02+00:00
Actualize candrews...
Done.
Ending feed actualization at 2019-01-07T14:15:03+00:00
Feed actualizations took 0 day(s), 0 hour(s), 0 minute(s) and 1 seconds for 1 users
Results:
candrews OK
End.
```

Thank you!

**Comment by Alkarex** [comment]
Hello @candrews 
It is great to have some feedback on the /dev branch 👍 
I will fix. It is due to https://github.com/FreshRSS/FreshRSS/pull/2208 but I will make an option to specify whether one wants to have a copy of the syslog output on stderr or not.

**Comment by Alkarex** [comment]
Should be fixed in https://github.com/FreshRSS/FreshRSS/pull/2213
Not tested yet

**Comment by Alkarex** [comment]
Should be fixed in /dev. Tests welcome.
