### ISSUE TITLE
No more feeds update

### ISSUE THREAD

**Issue by Liandriz** [FreshRSS/FreshRSS#2214]
Hi,
On some FreshRSS install, with some users, i've got one not updating feeds anymore.
I can see new items incoming in *entrytmp table of this user, but i can't do anything with this user as writing.
I can search, view feeds & cat, but can't get feeds update at all, only on this user, all others are ok.
Thanks for your help!

**Comment by Alkarex** [comment]
Please check your FreshRSS logs for any error

**Comment by Liandriz** [comment]
No error relative to this, just some curl & 404 alerts.
MariaDB is fine for other apps, and for other users.

**Comment by Alkarex** [comment]
Ok. Are you able to use the command line (or something like phpMyAdmin)?

Something like the following to connect:
```sh
mysql -u root -p freshrss
```

And then one instruction at a time (replace `alex` by the appropriate username):

```sql
START TRANSACTION;

SET @rank=(SELECT MAX(id) - COUNT(*) FROM `freshrss_alex_entrytmp`);

INSERT IGNORE INTO `freshrss_alex_entry` (id, guid, title, author, content_bin, link, date, `lastSeen`, hash, is_read, is_favorite, id_feed, tags)
    SELECT @rank:=@rank+1 AS id, guid, title, author, content_bin, link, date, `lastSeen`, hash, is_read, is_favorite, id_feed, tags
    FROM `freshrss_alex_entrytmp`
    ORDER BY date;

DELETE FROM `freshrss_alex_entrytmp` WHERE id <= @rank;

UPDATE `freshrss_alex_feed` SET `cache_nbEntries`=(SELECT COUNT(e1.id) FROM `freshrss_alex_entry` e1 WHERE e1.id_feed=`freshrss_alex_feed`.id),
    `cache_nbUnreads`=(SELECT COUNT(e2.id) FROM `freshrss_alex_entry` e2 WHERE e2.id_feed=`freshrss_alex_feed`.id AND e2.is_read=0);

COMMIT;
```

Please report any error.

**Comment by Liandriz** [comment]
For info, creating a new user can reproduce it : all entries stay in entrytmp, 0 in entry.

**Comment by Liandriz** [comment]
Thanks, feels like it worked atm, but entrytmp is still getting entries after, reproducing it.

**Comment by Alkarex** [comment]
So you did not get any error when executing the SQL queries manually?

**Comment by Alkarex** [comment]
Do you refresh your feeds by cron or manually?

**Comment by Liandriz** [comment]
PHP script via cron.

**Comment by Alkarex** [comment]
When you observe this problem, does it make any difference when you hit the refresh button manually?

**Comment by Liandriz** [comment]
Already tried, stopping the PHP script, updating manually, entries still stay in entrytmp.

**Comment by Alkarex** [comment]
When you face the problem, could you please try a request like the following, and tell whether it changes anything?
```
https:// ... /i/?c=feed&a=actualize&id=-1&ajax=1
```

**Comment by Alkarex** [comment]
There is probably a warning/error under a specific condition, which prevents the rest from working. This is what we need to find.

**Comment by Alkarex** [comment]
The request above should return `OK`

**Comment by Liandriz** [comment]
Instant OK.

**Comment by Alkarex** [comment]
And are the entries moved from entrytmp to entry?

**Comment by Liandriz** [comment]
Yep.

**Comment by Alkarex** [comment]
So to recap, when it comes to committing from the entrytmp to the entry table, the manual SQL instructions work, the manual HTTP request works, the cron does not, and could you please confirm that the manual refresh does not work?

**Comment by Liandriz** [comment]
That's it, exactly.

**Comment by Alkarex** [comment]
Would you be able to make me a temporary account on your FreshRSS instance, which exhibits the problem? If that is possible, you can send me the info [by e-mail](https://alexandre.alapetite.fr/cv/).

**Comment by Liandriz** [comment]
Seems OK now, thanks, will keep the code in case it stuck again in the future, but can't see where this problem came from :/
