### ISSUE TITLE
[Feature Request] FeedBin starred/favorites import option

### ISSUE THREAD

**Issue by timothevs** [FreshRSS/FreshRSS#2227]
Hi,
would it be possible to add an option to import favorites/starred articles from FeedBin? The subscriptions were imported without a hitch. But I can't find a way to import the starred.json.

Attached is a sample of their output.

[starred_example.json.txt](https://github.com/FreshRSS/FreshRSS/files/2794198/starred_example.json.txt)

Thank you.

**Comment by Alkarex** [comment]
Merged in the /dev branch

**Comment by timothevs** [comment]
Actually, 👍 but here's an added complication - starred.json will not have a feed_id for feeds that have been deleted from Feedbin. But for feeds that do exist - the setup looks like attached. 

I am sorry I provided an incomplete example. I see that all 20132 entries were imported, but in the category/feed "Import".

[starred_example.json.txt](https://github.com/FreshRSS/FreshRSS/files/2799395/starred_example.json.txt)

**Comment by Alkarex** [comment]
@timothevs Arg, please open a new issue. But `"feed_id": 528906,` is not enough if there is no information about what this refers to. Is there more data in that file, or in another file?

**Comment by timothevs** [comment]
No worries. I studied your code, and wrote a script to pull stuff from FeedBin. They should be ashamed as their starred.json has absolutely no useful information if one wants to set up a mirror on FreshRSS. Thank you for all your help @Alkarex !

**Comment by aniqueta** [comment]
> No worries. I studied your code, and wrote a script to pull stuff from FeedBin. They should be ashamed as their starred.json has absolutely no useful information if one wants to set up a mirror on FreshRSS. Thank you for all your help @Alkarex !

@timothevs I'm running into this same issue migrating from Feedbin. All favorited/starred items are just grouped into an Import feed. Would you mind sharing your script? Thank you.
