### ISSUE TITLE
Drudge Report feed question

### ISSUE THREAD

**Issue by stevegee58** [FreshRSS/FreshRSS#2232]
I've moved all of my feeds from Feedly to FreshRSS and I'm very happy.  However one thing I'd like to improve is the behavior from http://drudgereportfeed.com/.  Instead of showing the article when I open it I get a page with a link to the article.  Right now it's just an inconvenience but Feedly would open the article itself instead of showing the link for me to open manually.
I don't know how Feedly knows to do this for Drudge but I'm looking for a way to do do the same in FreshRSS.  Maybe I could write a new extension to solve my problem?

**Comment by Alkarex** [comment]
Hello,
That RSS feed does not seem to contain article content. While FreshRSS offers to automatically fetch article content (to use sparingly), this feed links to various news sources, which complicates the process. Yes, an extension would be needed, or going through something like https://github.com/RSS-Bridge/rss-bridge

**Comment by aledeg** [comment]
I think this is a job for [RSS-Bridge/rss-bridge](https://github.com/RSS-Bridge/rss-bridge). Maybe a bridge already exists (I haven't checked), but if there is none, it's quite easy to write one.
