### ISSUE TITLE
Unable to complete installation in Docker

### ISSUE THREAD

**Issue by stoinov** [FreshRSS/FreshRSS#2236]
I am using the [docker how-to](https://github.com/FreshRSS/FreshRSS/tree/master/Docker) on my ARM64 machine with the [latest release build](https://github.com/FreshRSS/FreshRSS/releases/tag/1.13.1).
I have the same issue as #817 but I don't see `/var/lib/php/` in the container so I am out of ideas here.
One thig I noticed, is that the user I enter gets created in the `users` folder after each attempt.

**Comment by Alkarex** [comment]
Hello @stoinov ,
Could you please provide the precise commands you have used to build and run your Docker image?
Do you have a reverse proxy in front, and if yes, which? (e.g. Traefik)
And what database are you using?

**Comment by stoinov** [comment]
```
docker pull alpine:3.8
docker build --tag freshrss/freshrss -f Docker/Dockerfile .
```
This creates an ARM64 image that I use to spin up a container using similar configuration to what you provide. I do have Traefic in front which is working fine for a [Linux Server image](https://hub.docker.com/r/lsioarmhf/freshrss). I just tried to follow the instruction for custom made one, since they do not update regularly. I am not able to get to step 3 and select a DB at all.

**Comment by Alkarex** [comment]
Anything in the Docker logs?

```sh
docker logs -f freshrss
```

**Comment by stoinov** [comment]
I get several line over and over again:
```
PHP Warning:  session_start(): open(/tmp/sess_m2lar43gnmvu34b7rg1p8l9b7s, O_RDWR) failed: Permission denied (13) in /var/www/FreshRSS/app/install.php on line 12, referer: https://rss.home.stoinov.com/i/index.php?step=2
PHP Warning:  session_start(): Failed to read session data: files (path: ) in /var/www/FreshRSS/app/install.php on line 12, referer: https://rss.home.stoinov.com/i/index.php?step=2
"GET /i/index.php?step=2 HTTP/1.1" 200 1244 "https://rss.home.stoinov.com/i/index.php?step=2" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/18.17763"
```
I tried accessing it directly without the proxy, and I still get the same problem and logs.

**Comment by stoinov** [comment]
`docker run -d --restart unless-stopped --network name --name rss -h rss -p 8001:80 -v /path/to/rss:/var/www/FreshRSS/data -e CRON_MIN='5,35' freshrss/freshrss
`
I am creating empty folder with rwxrwxr-x permissions and it gets filled by docker.

**Comment by Alkarex** [comment]
I have just tried on a Raspberry Pi without problem:
```sh
docker build --tag freshrss/freshrss -f Docker/Dockerfile .

docker run -d --restart unless-stopped --log-opt max-size=10m \
  -v /home/pi/data:/var/www/FreshRSS/data \
  -e 'CRON_MIN=4,34' \
  -e TZ=Europe/Paris \
  --net freshrss-network \
  --label traefik.port=80 \
  --label traefik.frontend.rule='Host:freshrss.example.net' \
  --label traefik.frontend.headers.forceSTSHeader=true \
  --label traefik.frontend.headers.STSSeconds=31536000 \
  --name freshrss freshrss/freshrss
```

Could you please run the following test commands?

```sh
cat /etc/issue
docker -v
docker exec -it freshrss cat /etc/issue
docker exec -it freshrss php -v
docker exec -it freshrss ls -alh /tmp/
docker exec -it freshrss php -r 'touch("/tmp/test1.txt"); unlink("/tmp/test1.txt"); echo "Done.\n";'
docker exec --user apache -it freshrss php -r 'touch("/tmp/test2.txt"); unlink("/tmp/test2.txt"); echo "Done.\n";'
```

**Comment by Frenzie** [comment]
Could there be some kind of hidden disk space issue? Docker defaults to `/var`, which isn't necessarily the most generously partitioned, at least on my systems. (Regardless whether it's a separate `/var` or as part of `/`.) I've increased my `/` from some 15-20 GB to 60 GB so I don't have to deal with Docker being really weird about alternative image locations.

Not that you'll need gigabytes just for the FreshRSS image of course, but it might be something to keep an eye on with, e.g., `df -h`.

**Comment by stoinov** [comment]
OK so I reinstalled my machine due to seemingly unrelated issues, and now I am able to complete the install using the same commands as before.
