### ISSUE TITLE
Swage theme on Firefox

### ISSUE THREAD

**Issue by nvjacobo** [FreshRSS/FreshRSS#2237]
When zoom in or out on Firefox 60.5.0esr 64-bits with Swage theme some tags disappear to: (...)

Chrome is works well.

**Comment by pattems** [comment]
I'm the theme Author; I'll investigate ASAP.

**Comment by nvjacobo** [comment]
Thanks :) 
Example, here  FreshRSS (1.13.1) :
![freshrss](https://user-images.githubusercontent.com/1041987/52181516-79a78c00-27b8-11e9-892e-444667f6158b.png)

**Comment by aledeg** [comment]
@nvjacobo With FF 65.0.2 it's working as intended. At least, I cannot reproduce.
I am closing for now, but if you need to, you can reopen it.
