### ISSUE TITLE
Fever: Undefined index 'tags' in EntryDAO.php

### ISSUE THREAD

**Issue by NanoSector** [FreshRSS/FreshRSS#2239]
After having sync issues with the Fiery Feeds app, I contacted the dev which supplied me with a log including many instances of the following causing the app to not be able to parse the feeds:

```
Notice:  Undefined index: tags in /var/www/freshrss.nanosector.nl/app/Models/EntryDAO.php on line 1068
```

Disabling errors in PHP itself and muting Notices allows Fiery Feeds to work as intended, but this is obviously not the preferred solution.

Running FreshRSS 1.13.1 on Fedora 29 with Nginx and PHP 7.2. Database is PostgreSQL.

**Comment by Alkarex** [comment]
Thanks for the quick feedback 👍
