### ISSUE TITLE
Fever API: ampersand is escaped in URL

### ISSUE THREAD

**Issue by NanoSector** [FreshRSS/FreshRSS#2241]
For instance if you add the Phoronix feed you will get malformed URLs which break reader modes in clients as can be seen by the attached screenshot.

The &amp; should not be escaped as such.

![72e492c3-5b53-473b-8a03-b29f763d683f](https://user-images.githubusercontent.com/1280380/52247250-73fd9380-28e9-11e9-9e65-af9301e7ce5f.jpeg)

Phoronix feed to test: 
https://www.phoronix.com/rss.php

**Comment by Alkarex** [comment]
Hello @Yoshi2889 and thanks for the bug report.
Could you please try this patch https://github.com/FreshRSS/FreshRSS/pull/2243 (I do not have the possibility of testing Fever clients myself)

**Comment by NanoSector** [comment]
That seems to solve the issue, thanks!

**Comment by Alkarex** [comment]
Super. Can you spot any other encoding issue, e.g. in the category names, feed names, article titles, article authors?

**Comment by NanoSector** [comment]
Do you have any feeds I can test? Mine don't really contain any special characters.

**Comment by Alkarex** [comment]
@Yoshi2889 I have quickly made a test feed: http://test.alapetite.fr/special.rss.xml

**Comment by NanoSector** [comment]
Looks great on my end!

![d7ba20ae-17d1-49ec-bb20-e29840cea1db](https://user-images.githubusercontent.com/1280380/52436559-e605f080-2b14-11e9-96c8-d6be19e882c5.png)

**Comment by Alkarex** [comment]
Thanks for the test! :-)
