### ISSUE TITLE
AGPL License for data output

### ISSUE THREAD

**Issue by Jaafarw2** [FreshRSS/FreshRSS#2244]
Hi,

I need some clarifications about the AGPL license and FreshRss. 

Does the license apply to data the generated with FreshRss? 

For GPL, [this link](https://www.gnu.org/licenses/gpl-faq.html#GPLOutput) says that the license does not apply to the output of a program. What about AGPL?

Thanks for your help.

**Comment by Alkarex** [comment]
Hello,
In the case of the output, I think the most relevant aspect is the potential copyright of the original feeds. For instance, if you retrieve articles from various newspapers, and provide them again publicly via RSS output.

When it comes to FreshRSS itself, the license is mainly relevant when you make changes to the FreshRSS source code. Then your changes need to be made available under the same license. This does not apply to extensions using the build-in extension mechanism.

Does that answer your question?

**Comment by Jaafarw2** [comment]
Hi,

Thanks for your answer, it helps indeed. I will only show titles and a few lines, so I think it is ok for now.  Things can change though with the upcoming European law.

I intend to get the data from FreshRSS database either by using the provided API, by making my own API to only get the data I need, or by accessing the database directly from my app. Hopes that ok.
