### ISSUE TITLE
Access to database is denied

### ISSUE THREAD

**Issue by krispek** [FreshRSS/FreshRSS#2246]
I run FreshRSS and MySQL both in Docker on my NAS. This issue occurred when I upgraded both of them using Watchtower. Both were minor upgrades, so I suspected no issues. 

Situation;
MySQL: 8.0.15 (upgraded from 8.0.12 of 8.0.13)
FreshRSS: 1.13.1 (upgraded from 1.12)

Both are running in (separate) Docker containers. To overcome another login issue, I use 'caching_sha2_password' authentication method. 

After upgrading, I got this error after logging in (the login page works):

> ### Application problem ###
> See logs files

The error message itself states:
> PHP message: PHP Fatal error:  Uncaught Minz_PDOConnectionException: Access to database is denied for `freshrss` (`mysql:host=mysql;dbname=freshrss;charset=utf8mb4`) in /config/www/freshrss/lib/Minz/ModelPdo.php:95
> Stack trace:
> #0 /config/www/freshrss/app/Models/Factory.php(27): Minz_ModelPdo->__construct('username')
> #1 /config/www/freshrss/p/api/fever.php(168): FreshRSS_Factory::createEntryDao()
> #2 /config/www/freshrss/p/api/fever.php(186): FeverAPI->authenticate()
> #3 /config/www/freshrss/p/api/fever.php(595): FeverAPI->isAuthenticatedApiUser()
> #4 {main}
>   thrown in /config/www/freshrss/lib/Minz/ModelPdo.php on line 95" while reading response header from upstream, client: 172.17.0.1, server: _, request: "POST /api/fever.php/?api&unread_item_ids HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.1.2:9200"

This of course relates to the FeverAPI I make use of, but for logging in itself I could not find an error so far. 

This seems to be related to the database, but I can't find out how. 

- My initial research led to #1474 and thus to the encoding set, but I verified that the character set is indeed utf8mb4. 
- I changed the login method back to mysql_native_password, but that did not have any immmediate effect, so I reverted it. 

Does anybody have an idea?

**Comment by Alkarex** [comment]
Hello @krispek and sorry for the delay.
I am not familiar with the system you are running on. I do not think this is an issue with FreshRSS, but more about networking and/or access rights between your two containers. From within the FreshRSS container, can you successfully ping your `mysql` container?
If you do not succeed in doing the MySQL configuration, you can revert to using the built-in SQLite database.

**Comment by aledeg** [comment]
@krispek Do you mean you have a docker container running the database and a docker container running the code with your web server?

**Comment by krispek** [comment]
@aledeg Yep. 

I solved it in the end by running Firefly from another source (I initially ran it via linuxserver, now I use the freshrss/freshrss-version). And I changed the authentication method to the default version again. :)

**Comment by aledeg** [comment]
So maybe your containers are not on the same network. I am not sure how to verify that though.

You mentioned that your problem is solved. Should we close the current issue?

**Comment by Alkarex** [comment]
Let's close, and re-open if needed :-)
