### ISSUE TITLE
automatic CRON feeds updating

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#2247]
Hi,
I cannot get the automatic update of feeds working.
Here is my config;
CRON on server (setup at install time ?): 
php /home/root/www/rss.site.org/app/actualize_script.php > /home/root/www/rss.site.org/data/users/FreshRSS_cron.log 2>&1

I do not receive the CRON automatic email.

On Freshrss config I ticked value to:
Allow anonymous refresh of the articles 
Allow unsafe automatic login using the format: https://site.org/rss/p/i/?c=auth&a=login&u=alice&p=1234

but I can't find how to change the url above which should be:
 https://rss.site.org/p/i/?c=auth&a=login&u=alice&p=1234

If I click "actualize" manually it works.

Thanks if anyone can help

**Comment by Alkarex** [comment]
Hello,
The cron job is just for refreshing feeds (retrieving new articles in FreshRSS), not for sending e-mails (only when there are some cron errors).

What output do you get when you run the cron job manually?

 ```sh
php /home/root/www/rss.site.org/app/actualize_script.php
```

**Comment by ghost** [comment]
Thanks for your response.
The hoster tested the script and said it was OK since it responded: 
```
Starting feed actualization at 2019-02-12T14:14:56+00:00
Actualize web...
```

However no updates of feeds can be seen on the web interface unless I run manually 
`http://rss.site.org/p/i/?c=feed&a=actualize`

**Comment by Tealk** [comment]
Hi @Alkarex

i have the problem that i have the cron running but i still have to click on "Actualize".

The cron log:
```
Starting feed actualization at 2019-02-20T13:55:01+01:00
Actualize Tealk...
Done.
Ending feed actualization at 2019-02-20T13:55:01+01:00
Feed actualizations took 0 day(s), 0 hour(s), 0 minute(s) and 0 seconds for 1 users
Results: 
Tealk OK
End.
```

**Comment by Alkarex** [comment]
@lmjst The output is supposed to be longer and its last line is `End.` so it looks like something is wrong in your cron, or at least truncated.

@Tealk Please check that the cron job is using the same user than your Web server (if you are in doubt, please post your cron job configuration). Please re-apply the correct access rights to your `./FreshRSS/data/` folder. If that is not enough, please edit your `./data/config.php` to have additional debug information:

```php
'environment' => 'production',
```

**Comment by Tealk** [comment]
@Alkarex thank you for your answer. It seems to work now why it took a day I can't explain.

**Comment by squromiv** [comment]
How to run "actualize_script.php" manually with parameter  "/tmp/FreshRSS.log"?
I do in this way, feeds become refreshed, but log-file is nor created, nor written.

![screen_2019 04 21 001](https://user-images.githubusercontent.com/15985877/56463308-bf481e00-63d1-11e9-9b1c-96e1eeccd615.png)

**Comment by Frenzie** [comment]
What you see in the docs is not a parameter, but an output redirect. Normally `actualize_script.php` will just print its output to your terminal, but if you write `actualize_script.php > filename` it'll write (redirect) its output to a file instead. You'll probably want to add `2>&1` at the end to redirect errors to the standard output.

Semi-random search result that looks like it explains things not too badly: https://likegeeks.com/shell-scripting-awesome-guide-part4/
