### ISSUE TITLE
[Feature request] Remember opened categories in the left menu

### ISSUE THREAD

**Issue by adaigre** [FreshRSS/FreshRSS#2248]
Hi !

First of all, thanks to all the contributors of this project ! I was using Feedly before jump to FreshRSS for few weeks now. I've had issues with Fever API warnings who already have been solved (I use the Reeder iOS app).
I'm pretty happy with FreshRSS now. 

However, I find the behavior of left menu irritating. It will be great if the opened categories could be remembered between pages.
Unfortunately, I'm a sysadmin and not a developer (even less frontend Javascript developer).

If someone find some time ;)

**Comment by Frenzie** [comment]
What do you mean by between pages exactly? It seems to be remembered between normal view and reading view.

**Comment by adaigre** [comment]
I mean when the page reloads (eg: if you click on a feed).
When I click on one of my feeds in the left menu, the only category to be unfolded is the feed parent category. For example, Feedly always remember unfolded categories.

**Comment by prashanttholia** [comment]
Hi, I'd like to work on this issue.

**Comment by Alkarex** [comment]
@prashant-tholia You are very welcome 👍

**Comment by prashanttholia** [comment]
Hi @Alkarex, I sincerely apologize for reverting back so late.

I have implemented the feature. I request you to check out the commit I added above and try it out. I implemented it using browser session storage. I considered various options to implement the feature, including implementing using server-browser session, URL query string parameters, cookies, local storage etc, but I picked session storage as it seemed to fulfil the requirements in the smoothest and most perfect way. In particular, using session storage helped me as -
- It is almost entirely browser side implementation.
- It does not require any data to be passed between server & browser.
- And, as session storage gets automatically deleted on tab/browser close, there was no need to implement functionality to reset stored opened categories and the page UI.

I also chose to remember the sidebar scroll position as well. I thought it bettered the user experience.

There is a known behavior in a particular interaction sequence that may not be strictly desirable. It arises when there is a feed selected in the sidebar and I then close its category dropdown. Now, when I refresh the browser page, it would still load with the category open.

I have partially implemented a solution (i.e. reload the page with category close) to this behavior, but it includes removal of setting 'active' CSS classes at the backend and handling it entirely on the frontend. I thought it was a significant change and considered it better to post the solution in its current status first and seek feedback on it.

Thanks & looking forward to the feedback.

**Comment by Alkarex** [comment]
@prashanttholia No worries, and thanks for the draft 👍  
I suggest you make a new branch in your repository, and then send us a pull request of that branch. It makes it easier for us to comment and track. You can always add more changes by just continuing commiting to the same branch.
We will have a few comments, in particular some suggestions of simplification.
