### ISSUE TITLE
[Feature Request] Limit height of "Mark all read" button in the footer

### ISSUE THREAD

**Issue by uncovery** [FreshRSS/FreshRSS#2251]
Currently, the "Mark all read" footer below the article list is stretching 100% until the bottom of the page. Instead, it should be a fixed-height bar/button below the articles.

Why?

- If you have only a few articles unread left in your feed, the whole page essentially becomes a "mark all read" button. 

- This leaves zero space to click on the page to switch between windows without clicking on the button:
![image](https://user-images.githubusercontent.com/583808/52761350-0589a580-304e-11e9-937b-52a042a07ea7.png)

In this scenario, I would instinctively, inadvertently click on "Mark all read" when trying to switch to the browser from Notepad. The white area in a website is usually safe to click. Not in FreshRSS.

- It's poor interface design. Buttons should be easily understood as such and not be a massive white space that occupies the whole page.

**Comment by pattems** [comment]
This functions like it does to give people who use scroll as read enough room to scroll to the last article to mark it read with scrolling, and not click on the giant button. It's not a design choice I personally like, but that was the rationale that was given to me while I was writing my theme. It's on my list of UI areas to take a crack at improving, when I've got time.

**Comment by uncovery** [comment]
thanks for your reply. I get your point and agree the footer should be large, but not the button. I will reword the request to make sure I don't intend to shorten the footer, rather the button size. There could of course be another footer below a button, just without the whole surface being a button.

**Comment by Alkarex** [comment]
All right. We could reduce a bit the width of the active area, to leave a bit of room on both sides for neutral clicks.

**Comment by Alkarex** [comment]
Fixed by @uncovery in https://github.com/FreshRSS/FreshRSS/pull/2301
