### ISSUE TITLE
Articles order mixed up

### ISSUE THREAD

**Issue by adaigre** [FreshRSS/FreshRSS#2252]
Hi !

I've just realized that my feeds are in incorrect order (
![1](https://user-images.githubusercontent.com/803151/52775361-cd7b6600-303f-11e9-8938-6afad844b347.jpg)

Why aren't they sorted by date ? You can see that the first item came yesterday

Thank you !

**Comment by Frenzie** [comment]
The date displayed is likely the one given by the feed in question. Perhaps it was unavailable while the other feeds were being refreshed?

A general discussion can be found here:
https://github.com/FreshRSS/FreshRSS/issues/1782#issuecomment-364560164

**Comment by aledeg** [comment]
As @Frenzie mentioned, we already have that conversation. I am closing this issue for now, but feel free to reopen it if you need more than what was discussed before.
