### ISSUE TITLE
"My Labels" category vanishes when new articles are notified

### ISSUE THREAD

**Issue by sleeksorrow** [FreshRSS/FreshRSS#2256]
Minor UI issue: When new articles are available, and FreshRSS shows the blue banner on top of the page, the category "My Labels" on the left vanishes.
As soon as I reload to show the new content, "My Labels" reappears.

I'm using version 1.13.1 and I'm actively using labels, in case this is important.

**Comment by sleeksorrow** [comment]
Hm I think I need to correct myself. The "My labels" category vanishes just after some time, without new articles banner appearing. It's so hard to really observe it doing this. Sorry for the false initial clue.

**Comment by Alkarex** [comment]
@sleeksorrow Could you please try to send a screenshot when that happens?

**Comment by sleeksorrow** [comment]
Sorry it took me a while.
Here is a screenshot of the "my labels" category missing:
![mylabels_missing](https://user-images.githubusercontent.com/390307/53814264-9b369780-3f5f-11e9-9442-6fe70e00685c.png)

Although the element is still in the tree in DevTools:
![mylabels_elements](https://user-images.githubusercontent.com/390307/53814308-aa1d4a00-3f5f-11e9-9797-391283ec8114.png)

As soon as I reload, the category is back:
![mylables_back](https://user-images.githubusercontent.com/390307/53814412-dafd7f00-3f5f-11e9-9a04-9f7e392cc38d.png)

Maybe important: All articles with labels are marked read.

Other news categories without unread articles are hidden, too, but I think it makes sense that "My labels" is there even without unread articles in it. Maybe there are two mechanisms racing each other here: One decides to show "My labels" because it's special and another hides it after a while because there is no unread article?  Sorry for wild guessing.

**Comment by scharmach** [comment]
I have/ had the same issue. What I've noticed is that "My labels" disappears from the sidebar specifically when this URL here is loaded after some time:

https://xyz.com/p/i/?c=javascript&a=nbUnreadsPerFeed

I'm not using "My labels" anyways, so I'm having this in my Custom RSS to make it hidden all the time:

#sidebar > .tags {
 display: none;
}

(as found here: https://github.com/FreshRSS/FreshRSS/issues/2257#issuecomment-468949360)

and this to not have it displayed at the bottom of actual posts:

.horizontal-list.bottom .item:nth-child(3) {
 display: none;
}

Maybe this is both helpful information for the disappearing "My labels"-issue and for someone simply wanting to hide "My labels" too.

**Comment by math-GH** [comment]
Could you check this PR #4065? Does it solve this issue?

**Comment by scharmach** [comment]
I've tested this just now and to me the PR has fixed the issue, @math-GH.

If you've set the option to only show unread articles, like me, "My labels" is only visible if a labeled article is unread. If all labeled articles are read, "My labels" isn't shown in the sidebar.

And if I click to show all unread articles, "My labels" is shown and stays this way in the sidebar now.

**Comment by math-GH** [comment]
Great! Thanks for your feedback.
This fix is scheduled for 1.19.1
