### ISSUE TITLE
EasyRSS login failed

### ISSUE THREAD

**Issue by cid882016** [FreshRSS/FreshRSS#2272]
Hi, I'm unable to login with the android app EasyRSS to my selfhosted server with https and a letsencrypt certificate. I already checked the API setting to allow apps to login.  I receive the error that the username or password is wrong but I am able to login with the same credential via webbrowser. Any idea what can be the issue?

**Comment by Frenzie** [comment]
You need to set a separate API password in Settings → Profile.

**Comment by cid882016** [comment]
Ok I did that. Still login failed. I used the same username but with the api password. What url should I use? With .../api or without?

**Comment by Alkarex** [comment]
Check your API configuration and addresses in the test page
![image](https://user-images.githubusercontent.com/1008324/54342858-d01cab80-463d-11e9-8517-dd2ec46431f6.png)

**Comment by Alkarex** [comment]
Closing old issue
