### ISSUE TITLE
Entry IDs aren't guaranteed to be unique

### ISSUE THREAD

**Issue by rianhunter** [FreshRSS/FreshRSS#2273]
Basically as title,

in the `entrytmp` table, ids are computed by adding the current usecs to the entry date. this is not guaranteed to be unique.

when adding to the entry table from the `entrytmp` table, ids are computed from the max id of the `entrytm`p table, and incremented. On two runs with the same `max(id) - count(*)` expression, you will have an id collision.

The `entrytmp` table seems to be used to get a `date`-oriented ordering for the `id` column. Why is this necessary? Why not order by the `date` columne in `listWhereRaw()` and `sqlListWhere()`?

**Comment by Alkarex** [comment]
Hello,
The `date` column is the date declared by the feed. It is not reliable and purely informative. It is sometimes several years in the past or in the future. We have had several long discussions on the topic.
Although there is indeed no SQL guarantee of uniqueness, the general logic is supposed to ensure this uniqueness. Have you been hit by a case of non-uniqueness?

**Comment by rianhunter** [comment]
I haven't but seemed like a glaring error. A malicious feed could potentially cause FreshRSS to never update by intentionally reusing old dates to cause a non-uniqueness constraint error when executing the SQL.

Feel free to close if you don't care to fix this, just wanted to bring attention to this.

**Comment by Alkarex** [comment]
The IDs are produced using local server time, in microseconds, and  the data from the feeds has no role in producing IDs. Collisions would be possible if we were to add more than 1M articles per second in average for a long period, which seems quite unlikely.
It is always good to track potential bugs, so thanks for that. For now, I think we are ok-safe here :-)

**Comment by rianhunter** [comment]
> The IDs are produced using local server time, in nanoseconds, and the data from the feeds has no role in producing IDs.

That's not true, this is the flow of how IDs are derived, they clearly originate from the entry date.

https://github.com/FreshRSS/FreshRSS/blob/512d047f02b601dcf21f8c807117ea154967e58f/app/Controllers/feedController.php#L384

https://github.com/FreshRSS/FreshRSS/blob/512d047f02b601dcf21f8c807117ea154967e58f/app/Models/EntryDAO.php#L168

https://github.com/FreshRSS/FreshRSS/blob/512d047f02b601dcf21f8c807117ea154967e58f/app/Models/EntryDAO.php#L214

**Comment by rianhunter** [comment]
Also if the server time is adjusted, e.g. due to daylight savings time, that could cause an ID conflict

https://github.com/FreshRSS/FreshRSS/blob/512d047f02b601dcf21f8c807117ea154967e58f/app/Controllers/feedController.php#L387

**Comment by Alkarex** [comment]
@rianhunter You are indeed correct. This is not for the main case though, but when 1) adding new feeds, and 2) processing entries that are too old. This indeed needs to be corrected.

Regarding server time adjustments, Unix timestamp is not supposed to be affected by time-zones / daylight savings. We should though add a barrier for that as well.

**Comment by rianhunter** [comment]
> Regarding server time adjustments, Unix timestamp is not supposed to be affected by time-zones / daylight savings. We should though add a barrier for that as well.

Ah yes, you're right about that. Saw the `gettimeofday()` call in `uTimeString()` and assumed it was timezone sensitive. I see you use the "sec" index.

EDIT: Just to be thorough this could still be sensitive to time adjustments from, e.g. ntp, while updating the feeds, but it isn't the same security concern as deriving the ID from the entry date and would work itself out over time. In general I wouldn't consider it good practice to derive unique IDs from wall clock time.

**Comment by Alkarex** [comment]
For the two cases above, for a collision to occur, a feed would have to provide a date (in seconds) already existing in database, and then there is 1 chance over 1 million to hit the same microsecond using the server local time. So low risk, but still

**Comment by rianhunter** [comment]
> So low risk, but still

Yup that's why I said to feel free to close :) Though, I can see something like this causing a bug in an obscure way down the line so probably worth it long term to make it 100% solid.

**Comment by aledeg** [comment]
@rianhunter  Do you have any suggestion on how we can fix that?

**Comment by Alkarex** [comment]
In https://github.com/FreshRSS/FreshRSS/pull/2276 I have removed the cases that could generate old IDs.

Remains the case of very unlucky server time change.

With MySQL / SQLite, articles with colliding IDs are ignored, and we would try to add them again with another ID at next update. I think this good enough.

With PostgreSQL, we can either update our requirements to version 9.5+ to take at last advantage of `ON CONFLICT DO NOTHING`, or alter the request with a more complicated expression.
Edit: Done

https://github.com/FreshRSS/FreshRSS/blob/e91ef155d42f9624ef0e5d553b4e5fad70ba1bb5/app/Models/EntryDAOPGSQL.php#L32-L43

P.S.: The last Ubuntu shipping a PostgreSQL < 9.5 is Ubuntu 14.04 LTS, which stops next months. For Debian, it is Jessie 8.0 stopping in May 2020. In the Red Hat family, we need to wait for RHEL/CentOS 8.0 (currently in beta)...

**Comment by Alkarex** [comment]
@aledeg I think the more proper way would be to have a new entry ID column based on auto-increment, and not use the discovery time (our current ID) for uniqueness. But it is a relatively big change for little gains (one such gain would be a possible compatibility with APIs limited to 32-bit integers such as TT-RSS).

**Comment by rianhunter** [comment]
@Alkarex Yeah I agree, I would also avoid the temporary table song and dance.

If you really want date oriented IDs, you can derive the ID like this: (entry_date, unique_id), though I think there might be other constraints on your IDs and the way queries are made from the UI.
