### ISSUE TITLE
Entries' author names are prepended with semicolons in Fever

### ISSUE THREAD

**Issue by fongd** [FreshRSS/FreshRSS#2281]
Author names for feed entries are all being prepended by semicolons in the database, even when there is only a single author for a specific feed entry. FreshRSS renders this fine using the web reader but these semicolons are also being exported via the Fever API (haven't confirmed whether this is also happening with the greader API), which leads to external RSS readers displaying it:

<img width="581" alt="Screen Shot 2019-03-19 at 12 53 54 PM" src="https://user-images.githubusercontent.com/241671/54625662-1743db80-4a46-11e9-8061-d33eb44cb8eb.png">

Incidentally, this screenshot also reveals another issue with the author list, in that there are too many spaces in the comma-separated author list. I'm in the process of migrating from my self-hosted Fever instance to FreshRSS, and do not have these issues there.

FWIW, here is the JSON payload returned by the Fever API call to FreshRSS:

`{"api_version":3,"auth":1,"last_refreshed_on_time":"1552973497","total_items":"3175","items":[{"id":"1552975041339787","feed_id":"107","title":"The Age of Stupid revisited: what's changed on climate change? \u2013\u00a0video","author":";Christopher Cherry\uff0c Franny Armstrong\uff0c Lizzie Gillett\uff0c Jacqueline Edenbrow and Charlie Phillips","html":"\n<p>Ten years after climate movie The Age of Stupid had its green-carpet, solar-powered\u00a0premiere, we follow its director as she revisits people and places from the film and asks: are we still heading for the\u00a0catastrophic future it depicted?\u00a0<\/p> <a href=\"https:\/\/www.theguardian.com\/environment\/video\/2019\/mar\/15\/the-age-of-stupid-revisited-whats-changed-on-climate-change-video\">Continue reading...<\/a>\n<div class=\"enclosure\"><\/div>\n<div class=\"enclosure\"><\/div>\n","url":"https:\/\/www.theguardian.com\/environment\/video\/2019\/mar\/15\/the-age-of-stupid-revisited-whats-changed-on-climate-change-video","is_saved":0,"is_read":0,"created_on_time":1552636620}]}`

Running FreshRSS 1.13.1, PHP 7.2.16, MariaDB 10.2.

**Comment by Alkarex** [comment]
Fixed in https://github.com/FreshRSS/FreshRSS/pull/2283
Please give it a try

**Comment by fongd** [comment]
Looks good, thanks @Alkarex
