### ISSUE TITLE
Extensions don't work on Windows, error 400 (Bad Request)

### ISSUE THREAD

**Issue by squromiv** [FreshRSS/FreshRSS#2287]
Use FreshRSS on localhost, xampp server. I installed some extensions, but they do not function. In browser console I see requests, resulted to error 400 (Bad Request).
![1](https://user-images.githubusercontent.com/15985877/54746829-dbd81700-4bd5-11e9-868a-4e6138d95414.png)

![2](https://user-images.githubusercontent.com/15985877/54746832-de3a7100-4bd5-11e9-876b-4ea3b50a07e9.png)

**Comment by Alkarex** [comment]
Hello @squromiv 
What address do you have in your browser address bar when you observe this problem?

**Comment by squromiv** [comment]
I have made some research. My FreshRSS is situated on address http://localhost/FreshRSS1/p/i/
Scripts, which lead to errors in console, seem to be unvaliable for extension. At first I thought, that the problem is connected with "%2F" encoding to slashes. I added  "AllowEncodedSlashes On" directive to file "httpd-vhosts.conf". But nothing changed. Same errors and extensions don`t work.

**Comment by Alkarex** [comment]
Do you see the corresponding requests in your Apache logs?

**Comment by squromiv** [comment]
The following information is provided in access.log. Only one extension is installed - Threepanesview.

::1 - - [23/Mar/2019:14:21:28 +0300] "GET /FreshRSS-dev/p/i/?c=javascript&a=nbUnreadsPerFeed HTTP/1.1" 304 - "-" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36"

::1 - - [23/Mar/2019:14:21:28 +0300] "GET /FreshRSS1/p/i/ HTTP/1.1" 304 - "-" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36"

::1 - - [23/Mar/2019:14:21:28 +0300] "GET /FreshRSS1/p/ext.php?f=xextension-threepanesview-master%2Fstatic%2Fthreepanesview.css&t=css&1549213160 HTTP/1.1" 400 - "http://localhost/FreshRSS1/p/i/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36"

::1 - - [23/Mar/2019:14:21:28 +0300] "GET /FreshRSS1/p/ext.php?f=xextension-threepanesview-master%2Fstatic%2Fthreepanesview.js&t=js&1549213160 HTTP/1.1" 400 - "http://localhost/FreshRSS1/p/i/" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36"

I also tried another local web-server - AMMPS, but result is the same.

**Comment by squromiv** [comment]
Tried other browsers, nothing changed. Extensions are installed, but do not function.

**Comment by squromiv** [comment]
May be this issue echoes with #994?
I am not a programmer. Can anybody help me?

**Comment by Alkarex** [comment]
I will have a look

**Comment by Alkarex** [comment]
@squromiv Yes, I think you are hitting exactly that problem https://github.com/FreshRSS/FreshRSS/issues/994
Could you please test https://github.com/FreshRSS/FreshRSS/pull/2348 ?

**Comment by Alkarex** [comment]
Available in the /dev branch. Please give it a try

**Comment by squromiv** [comment]
No errors in browser console, extensions finally work. Thanks a lot.

**Comment by Alkarex** [comment]
Thanks for the test. A few more patches have just landed in the /dev branch before the imminent release of [FreshRSS 1.14.1](https://github.com/FreshRSS/FreshRSS/pull/2338). Additional tests welcome on the /dev branch.
