### ISSUE TITLE
Automatic logout

### ISSUE THREAD

**Issue by squromiv** [FreshRSS/FreshRSS#2288]
Is there any way to login account2, opening address FreshRSS/p/i/?c=auth&a=account2&u=login&p=password with automatic logout from previos account1?

**Comment by Alkarex** [comment]
Hello,
Have a look at the unsafe automatic login option:
![image](https://user-images.githubusercontent.com/1008324/54751981-d03c1e80-4bdc-11e9-8248-5721620a002f.png)

**Comment by squromiv** [comment]
I know about it. But **it works only if I manually logout from previous account** in browser
![4](https://user-images.githubusercontent.com/15985877/54752827-15198280-4be8-11e9-96ba-929fa3c9f5dc.png)
.

**Comment by Alkarex** [comment]
Ah, I see. I will look into it

**Comment by Alkarex** [comment]
Would you be able to try https://github.com/FreshRSS/FreshRSS/pull/2290 ?

**Comment by squromiv** [comment]
@Alkarex
Tried. Can not login as an admin and other user at all.
![6](https://user-images.githubusercontent.com/15985877/54830128-8b89b380-4cc0-11e9-933f-e495e2bfd944.png)

Sorry, I closed the issue. I am not a programmer and still not able to work well with github.

**Comment by Alkarex** [comment]
Thanks for the quick test. What method did you use to update the code for the test?

**Comment by squromiv** [comment]
May be I am totally wrong (lack of experience), but I manually downloaded these files from [here](https://github.com/FreshRSS/FreshRSS/pull/2290/commits/99e0d7abd78264078ff046dbd11310c6cc330255): 
userController.php
authController.php
Auth.php
FreshRSS.php
main.js

And placed them into according folders of FreshRSS.

**Comment by Alkarex** [comment]
@squromiv While that might work sometimes, especially at the beginning of the development of a new version, that assumes there is no conflicting change in other files.
To make it a bit easier, I have merged those changes in our development branch, which you can try by downloading https://github.com/FreshRSS/FreshRSS/archive/dev.zip
(All those things are easier when the install is done by git)

**Comment by squromiv** [comment]
@Alkarex 
Thanks a lot. Checked dev version. Works as it should.
