### ISSUE TITLE
[feature] catégories arborescentes ?

### ISSUE THREAD

**Issue by tetraf** [FreshRSS/FreshRSS#229]
Est-il prévu d'avoir des catégories arborescentes pour pouvoir ranger plus facilement et proprement un grand nombre de flux ?

J'ai essayé d'importer un OPML venant d'un logiciel qui les gère (akregator) et du coup le rangement est perdu. Ranger a posteriori est assez lourd (mais reste faisable).
Le problème c'est que ranger quelques dizaines de flux relativement disparates dans des catégories de premier niveau ça fait soit beaucoup de catégories (qu'il faudrait donc ranger ;) soit un rangement assez peu efficace.

L'astuce de faire des catégories nommées en « Catégorie - Sous-catégorie » ne règle pas vraiment le problème (et puis c'est moche, surtout quand on essaye de retrouver 4 niveaux d'arborescence).

**Comment by marienfressinaud** [comment]
Après en avoir discuté avec @Alkarex, nous ne sommes pas vraiment convaincu qu'il serait intéressant d'implémenter cette fonctionnalité. Le cout de travail vs l'intérêt apporté nous semble vraiment limité.

J'ai réfléchi néanmoins à une **potentielle** alternative (j'insiste bien sur potentielle parce qu'il faudra me faire des suggestions pour l'interface, je n'ai pas envie de me casser la tête là-dessus ;)). L'idée serait de faire un peu à la manière des dossiers dans les clients mails : 
- Le nom des dossiers sont sous la forme `Dossier`, `Dossier.Sous-dossier`, `Dossier.Sous-dossier.Sous-sous-dossier`, etc.
- Les sous-dossier **sont** en fait des dossiers à part entière
- La différenciation se fait concrètement au niveau de l'interface utilisateur
- Conséquence : les mails situés dans un dossier enfant ne sont pas visibles depuis le dossier parent puisque concrètement ils n'ont rien en commun sauf le nom.

Remplacez "dossier" par "catégorie" et "mail" par "flux" et vous avez l'idée :). **Pour le moment**, le seul problème que je vois serait d'adapter l'affichage. Puisque les catégories sont ordonnées par ordre alphabétique, ce serait simple. **Par contre**, le jour où il sera possible d'ordonner les catégories différemment ça risque d'être plus compliqué et c'est pour ça que je ne suis pas tout à fait prêt à implémenter cette fonctionnalité (sans compter qu'il faudra revoir l'interface).

Bref, il n'y a pas de solution idéale et le problème est bien plus compliqué qu'il n'en a l'air !

**Comment by Draky50110** [comment]
Plus d'intérêt pour moi.
FRSS marcheplus ou moins bien, je ne lui demande rien d'autre sur les PC où je me connecte.
Au passage dans le navigateur d ebase Android, le fait de "Marquer tout comm lu" recharge la page mais ne les marque pas comme lu.

Bref bon courage pour la suite du développement.

**Comment by Alkarex** [comment]
Je ne pense pas que ce travail sera entrepris dans le futur proche. Du coup je ferme, au moins temporairement, ce ticket.
