### ISSUE TITLE
add optional headers to cli scripts

### ISSUE THREAD

**Issue by oupala** [FreshRSS/FreshRSS#2294]
The script output would be more easily readable if there was headers outputted. It could be an option to output the headers or not (`--headers true` or `--headers false`).

I was thinking about something like that:

```bash
>php cli/user-info.php -h --user myuser --headers false
*	myuser	2019-03-22T22:10:11+01:00	5.77 MiB	4 categories	20 feeds	909 reads	1 unreads	2 favourites

>php cli/user-info.php -h --user myuser --headers true
admin username last update               total space used # of categories # of feeds # of reads posts # of unreads posts # of favorite posts
-----|--------|-------------------------|----------------|---------------|----------|----------------|------------------|-------------------
*     myuser   2019-03-22T22:10:11+01:00 5.77 MiB         4 categories    20 feeds   909 reads        1 unreads          2 favourites
```

**Comment by aledeg** [comment]
@oupala Please check #2296

**Comment by oupala** [comment]
You guys are so fast in fixing issues!

It works well @aledeg.

Just one question: should we user *favorite* or *favourite*?

> Favorite and favourite are different spellings of the same word. Favorite is the preferred spelling in the U.S., while favourite is preferred in all the other main varieties of English ([source](https://grammarist.com/spelling/favorite-favourite/)).

And by the way, could this be extended to some other scripts where it makes sense? (if it does)

**Comment by Frenzie** [comment]
@oupala I'd go for US English myself, but the English in the program consistently goes with favourites. Unless you're proposing to switch or to contribute a second variety of English, I'd say it's not really a question. ;-)

https://github.com/FreshRSS/FreshRSS/blob/8dcdde6251ae4dfc690b1a014488df125c5e5cdc/app/i18n/en/index.php#L24

https://github.com/FreshRSS/FreshRSS/blob/8dcdde6251ae4dfc690b1a014488df125c5e5cdc/app/i18n/en/index.php#L37

https://github.com/FreshRSS/FreshRSS/blob/8dcdde6251ae4dfc690b1a014488df125c5e5cdc/app/i18n/en/index.php#L45

https://github.com/FreshRSS/FreshRSS/blob/8dcdde6251ae4dfc690b1a014488df125c5e5cdc/app/i18n/en/index.php#L53

**Comment by oupala** [comment]
I had no specific opinion between english english, and american english. I was only asking to be sure, and to get consistency.

But what your showing us demonstrate that **there is** consistency.

The last question about this issue and its fix is to decide if this change could also be applied to other scripts, if it makes sense.

**Comment by aledeg** [comment]
I haven't check where this could be applied. Help welcomed!

**Comment by aledeg** [comment]
I've checked quickly and the only other script which could benefit from that kind of change is the ```list-users``` script. I think this script is now obsolete considering that the ```user-info``` script does the same thing but better.
I think we can get rid of the later.

@Alkarex what do you think?

**Comment by Alkarex** [comment]
`list-users` is meant to be just the list of users, to be used e.g. in scripts like `./cli/list-users.php | xargs -n1 something`

**Comment by Alkarex** [comment]
Closing for the release of 1.14.0. Let's open a new issue if there are other scripts where it would make sense to have headers.
