### ISSUE TITLE
Cloudflare: Can't login anymore, 403

### ISSUE THREAD

**Issue by SuperSandro2000** [FreshRSS/FreshRSS#2303]
I can't login in any more with my Chrome. FreshRSS shows a 403 right after the login. It works fine with Edge. I tried it in Incognito without any extensions and the same problem.

``
Chrome Version 73.0.3683.86 (Official Build) (64-bit)
``

nginx acces.log
``log
172.20.0.1 - - [27/Mar/2019:19:21:01 +0100] "POST /i/?c=auth&a=login HTTP/1.1" 403 1728 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36"
``

All other logs are empty.

**Comment by Alkarex** [comment]
Hello,
I cannot reproduce.
I am not completely familiar with nginx log format, but at a quick glance, it looks like your browser referer is wrong. Don't you get a Referer error message in your FreshRSS 403 page?

**Comment by SuperSandro2000** [comment]
I get this error on multiple different browser on different devices.

````
Error 403 - Forbidden
You don’t have permission to access this page
← Go back to your RSS feeds
````

**Comment by Alkarex** [comment]
* What FreshRSS version do you use?
    * (There is version 1.14.0 as release candidate in the /dev branch)
* Have you tried to set a new password? (watch-out if you use a password manager / form autocomplete not to have outdated ones)
* Do you have a reverse proxy or something similar in front?
* Could you make me a temporary test account?

**Comment by SuperSandro2000** [comment]
> What FreshRSS version do you use?

I was using 0.11.0 cause I am using this https://hub.docker.com/r/linuxserver/freshrss/ Docker image and it does not auto update freshrss after the first installation. I am going to forward that to LinuxServer.io

> Have you tried to set a new password? (watch-out if you use a password manager / form autocomplete not to have outdated ones)

Yes.

>Do you have a reverse proxy or something similar in front?

Traefik and Cloudflare. That seems to be the problem cause when I directly connect to freshrss and leave both proxies out everything works like a charm. 

>Could you make me a temporary test account?

I take a look if I can get it to work behind my proxies and get back to you if I need more help.

**Comment by SuperSandro2000** [comment]
Apparently cloudflare stops me from login into freshrss. I am going to investigate that further.
Do you have any ideas why that could be?
Seems to be related to #1681 

Edit: Maybe you should try to implement this https://support.cloudflare.com/hc/en-us/articles/200169436-How-can-I-have-Rocket-Loader-ignore-specific-JavaScripts-

**Comment by Alkarex** [comment]
It makes sense for a Docker image not to auto-update, but rather expect the update to be done via Docker.
We also have a Docker image ready for Træfik https://github.com/FreshRSS/FreshRSS/tree/dev/Docker

Ah, right. Cloudflare is known to cause a bunch of problems, for instance to retrieve RSS feeds that are behind their system. They are making breaking changes, sometimes with man-in-the-middle approaches, and I do not think we should start doing some special cases for them, except if it is based on a Web standard. Cf. my answer https://github.com/FreshRSS/FreshRSS/issues/1681#issuecomment-368221829

**Comment by SuperSandro2000** [comment]
> It makes sense for a Docker image not to auto-update, but rather expect the update to be done via Docker.

Well I am on latest and it does not work and so far they are silent about it. Probably gonna switch on the weekend. I am no longer using arm devices so I have no need to use theirs. Thanks for the heads up.

For now I added a exception for freshrss in my cloudflare and I hope they won't break anything else cause I really need them to protect my server from Chinese spammers.

**Comment by SuperSandro2000** [comment]
I just wanted to inform you about the situation with the LinuxServerio image. I know that you probably won't really care but it makes me feel better completing that thing.
I talked to them that there image is not updating properly for the past months and they first silently ignored me and today banned me. They are unwilling to acknowledge the issue, fix it or inform their users about it. Their image has 5 million pulls on Docker Hub and there are probably a lot more users that use an old version of freshrss and thinking they are up to date. I just wanted to inform you about that issue that you can keep an eye on it and can react to it properly. Probably most people on arm devices use this image and it really hurts your software on the long run.

**Comment by Alkarex** [comment]
@SuperSandro2000 Sorry for the delay, and thanks for the update. On FreshRSS, I have to admit that our update process also needs to be improved (there is a work in progress). I have not talked with linuxserver, so I do not know their motivations. However, I can see that they have some update instructions on https://hub.docker.com/r/linuxserver/freshrss Did you give them a try?
In general for Docker images, it is best to update the Docker image itself (i.e. including other libraries and OS updates) than solely the software within it, so we need to recommend a procedure that does that.

**Comment by SuperSandro2000** [comment]
I always pulled the latest version of that image but they download and install freshrss at runtime (in a docker image) if it isn't installed already and have no update check. You can find the startup script here https://github.com/linuxserver/docker-freshrss/blob/master/root/etc/cont-init.d/40-install#L4 .

So basically you install it once and then you can only update it if you manually delete the installation directory (and this image has 10M downloads!).  Since I noticed that I switched to your image which works flawlessly and updates like it should.

**Comment by Alkarex** [comment]
@SuperSandro2000 Ok, I see. Strange approach indeed... What needs to be persisted in a volume is the data folder only, and it looks like their "config" volume also contains the code.
Related to our update rework: https://github.com/FreshRSS/FreshRSS/pull/1760

**Comment by SuperSandro2000** [comment]
You don't need to explain basic docker stuff to me. I know it very well. I am only a bit frustrated that such work is so popular and it takes me years to notice that bug.

I am not very familiar with php but if anything raises up with the docker image feel free to ping me.

Edit: and I actually found a little improvement. 😉
