### ISSUE TITLE
failed login should display login form again

### ISSUE THREAD

**Issue by oupala** [FreshRSS/FreshRSS#2305]
The current release of FreshRSS displays an error page on failed login.

It is hence necessary to click on back, to display the login form again.

When failed, the login page should display an error message **and** the login form with the focus on the login text-field.

This would make the login very easy when we just made a typo on the login or on the password.

**Comment by squromiv** [comment]
+1

**Comment by oupala** [comment]
It seems that this issue has been resolved in version 1.16.0.

**Comment by Alkarex** [comment]
Thanks for the feedback. This was probably solved by https://github.com/FreshRSS/FreshRSS/pull/2794
