### ISSUE TITLE
[FR] Show current username

### ISSUE THREAD

**Issue by squromiv** [FreshRSS/FreshRSS#2306]
I would like to see username, who currently is logged in. Something like this.
![screen_2019 03 30 00111](https://user-images.githubusercontent.com/15985877/55274146-a326f480-52dd-11e9-9963-457ed383f383.png)

**Comment by math-GH** [comment]
@squromiv Is it still actual?

Your screen shot shows the anonymous mode. Only 1 user is the "default user" that is used for the anonymous mode.

**Comment by Alkarex** [comment]
@math-GH Could you please try to find and link the PR (I believe it is one you did, if I remember correctly), which actually implemented showing the username in the config menu?

**Comment by math-GH** [comment]
it is #3880
