### ISSUE TITLE
Option "Afficher les catégories pliées par défaut"

### ISSUE THREAD

**Issue by Liandriz** [FreshRSS/FreshRSS#2307]
Petite typo je pense, la version FR et EN de l'option se contredisent.  
Avant le dernier update (1.14.0) cochée FreshRSS affichait bien les dossiers de catégories pliés, et maintenant, c'est le fonctionnement inverse, mais le nom de l'option reste le même.

**Comment by Alkarex** [comment]
Effectivement. Patch bienvenu :-)

**Comment by Liandriz** [comment]
Petit détail aussi, c'est moi, ou maintenant en ayant les catégories repliées par défaut, en avançant par catégories, ça déplie automatiquement la catégorie en cours de lecture?

**Comment by Alkarex** [comment]
Devrait être corrigé dans https://github.com/FreshRSS/FreshRSS/pull/2313
Disponible dans la branche /dev
@Liandriz Oui, effectivement, les catégories sont dépliées au fur et à mesure de la navigation. Est-ce un problème ?

**Comment by Alkarex** [comment]
Cf. https://github.com/FreshRSS/FreshRSS/issues/2309

**Comment by Liandriz** [comment]
Personnellement, j'aime bien avoir l’œil sur la liste des catégories et le compte des non lus sur catégories. Tellement de flux dans certaines que les replier puis déplier à chaque changement de catégories devient un enfer visuel :D  
Une option serait bienvenue!

**Comment by Alkarex** [comment]
@Liandriz Pourriez-vous ouvrir un nouveau ticket pour ce point là ?

**Comment by Liandriz** [comment]
Fait, et on peut clore ici du coup 👍
