### ISSUE TITLE
All categories expanded

### ISSUE THREAD

**Issue by Tealk** [FreshRSS/FreshRSS#2309]
Since 1.14 all categories are expanded and I can't find an option to change that.

**Comment by Frenzie** [comment]
I didn't notice anything like that in my testing or I would've mentioned it. :-) Is this with a particular theme?

Edit:
Cross-ref to https://github.com/FreshRSS/FreshRSS/issues/2310#issuecomment-478375335

**Comment by Alkarex** [comment]
Could we a wrong option wording in one of the languages (e.g. https://github.com/FreshRSS/FreshRSS/issues/2307 )
@Tealk Could you please show a screenshot or your FreshRSS reading options?

**Comment by Tealk** [comment]
Here :)
![grafik](https://user-images.githubusercontent.com/12276250/55295787-cdbd9e00-5400-11e9-9288-e55fc1bfeb0e.png)

**Comment by Crupuk** [comment]
Same here...

In french "Afficher les catégories pliées par défaut" need to be unchecked.

It seems like a false check on this configuration.

**Comment by Frenzie** [comment]
Same in Dutch (and presumably most other translations):

https://github.com/FreshRSS/FreshRSS/blob/d413f67dd28738f4a6d8cf036e00714737f757b8/app/i18n/nl/conf.php#L94-L95

**Comment by Tealk** [comment]
Interesting because I didn't change anything in the settings, the setting was either inverted or did nothing before.

**Comment by bastien30** [comment]
Same here.
Like Crupuk said, the option need to be unchecked.
Furthermore, when clicking on a categorie, the categorie expand (that wasn't the case before).

**Comment by Alkarex** [comment]
The name of the option has been fixed in the /dev branch. Tests welcome.
Indeed, the active category / feed gets shown during navigation. Is that annoying? If yes, let's discuss it in a new issue

**Comment by bastien30** [comment]
Thanks @Alkarex, I've opened another issue for the expand problem : #2324
