### ISSUE TITLE
Open in new Tab

### ISSUE THREAD

**Issue by Tealk** [FreshRSS/FreshRSS#2310]
Since i have update to 1.14 and I'm open an article in a new tab it will no longer be marked as read :'(

**Comment by Frenzie** [comment]
It sounds like there's something wrong with your settings somehow. I don't like the unfolded setting and I don't like mark as read when opening on original website, but they both work for me when testing in 1.14.

![Screenshot_2019-03-31_21-55-44](https://user-images.githubusercontent.com/202757/55294248-da8dc200-53ff-11e9-9f4a-740416e0eb31.png)

**Comment by Alkarex** [comment]
What method are you using to open an article in a new tab? Icon, shortcut, control+click?

**Comment by Tealk** [comment]
Middle mouse button
I also noticed that it takes a very long time until an entry is marked as read when I click on the small letter symbol. About 2 seconds. 
![image](https://user-images.githubusercontent.com/12276250/55307713-a5618e00-5458-11e9-82aa-e741b6f1d1f2.png)
This has also changed with the 1.14 because before it was read immediately.

**Comment by Alkarex** [comment]
@Tealk Ok, we will fix the middle-click issue. Regarding the delay, it is because marking as read is now sent in batch, max once per second. You can mark many as read or even scroll down without waiting.

**Comment by aledeg** [comment]
We should have the visual display switched automatically even before the query is sent to the server. This way we will have a quick visual cue and if it fails, we can revert it later.

**Comment by Alkarex** [comment]
Cf. https://github.com/FreshRSS/FreshRSS/issues/2304

**Comment by Alkarex** [comment]
The control+click and middle-click should be fixed with https://github.com/FreshRSS/FreshRSS/pull/2330
Could you please try the /dev branch?

**Comment by Tealk** [comment]
Im on 1.14.1-dev but control+click and middle-click does not work

**Comment by Alkarex** [comment]
@Tealk Did you pull the newest changes from 22:46 ?

**Comment by Tealk** [comment]
It was my mistake because I didn't wait long enough. The new batch system
Thanks :D
