### ISSUE TITLE
Docker container does not start after upgrade

### ISSUE THREAD

**Issue by krispek** [FreshRSS/FreshRSS#2311]
I upgraded to the new version (FreshRSS/FreshRSS:latest) last night (done via WatchTower). However, the container won't startup anymore. It gives this error:

```
Result: success
/bin/sh: 1: crond: not found
```

The Docker container runs in Synology. It's connected to a MySQL database, and the folder /var/www/FreshRSS/data is mounted to a folder outside the container. Everything was running smooth with the former version. Could this somehow be related to the new Docker image?

**Comment by Alkarex** [comment]
Hello,
The image has changed indeed, with a new base (Ubuntu instead of Alpine).
The Alpine flavour is still available https://hub.docker.com/r/freshrss/freshrss/tags
My guess is that your image was somehow not fully updated. Could you try to remove it and add it again?

**Comment by krispek** [comment]
I deleted the container and added it again. I still get this error unfortunately. The Alpine version does work though. For now, I will continue to use that version. 

If I can test anything for you, I'm happy to do so. :)

**Comment by Alkarex** [comment]
Maybe that could be related to https://github.com/FreshRSS/FreshRSS/issues/2319 , just fixed.
Could you please try the `:dev` tag?

**Comment by krispek** [comment]
Checked it, this container gives the same error. I use "CRON_MIN=14,44" to run the CRON. Removing this variable offers another error, which might give a clue:

`/bin/sh: 1: exec: httpd: not found`

It looks like some underlying configuration file is missing, but I lack the skills to determine which one.

Thanks for your help so far, much appreciated!

**Comment by Alkarex** [comment]
It looks like in your case, a new image is used https://github.com/FreshRSS/FreshRSS/blob/dev/Docker/Dockerfile but the old `CMD` is kept https://github.com/FreshRSS/FreshRSS/blob/dev/Docker/Dockerfile-Alpine
There is nothing called `crond` or `httpd` in the new Ubuntu-based image, only in the Alpine flavour.

I think there is some cache / configuration problem with your WatchTower

**Comment by krispek** [comment]
Ah, you're right. Somehow the old CMD is kept. I removed it, and now it's working. I'll check whether I can resolve that issue somewhere else. :)

**Comment by Alkarex** [comment]
Please use the `:dev` tag, as I have just fixed a few Docker issues in it (for the Ubuntu flavour), which will soon be released in `:master` and version 1.14.1.
