### ISSUE TITLE
Ajax loading of next articles fails if articles are sorted "ASC"

### ISSUE THREAD

**Issue by Massedil** [FreshRSS/FreshRSS#2314]
If I call this URL :
https://freshrss.example.com/i/?a=normal&order=ASC

When scrolling down, first XHR call to "https://freshrss.example.com/i/?a=normal&order=ASC&next=123456789&state=2&ajax=1" works and I see the next articles.

But after, it stops.

I see a link "[Charger plus d’articles](https://freshrss.example.com/i/?a=normal&order=ASC&next=12345678910&state=2&ajax=1)" instead of the next articles :

Expected : 
A new pack of articles is loading, like if I call https://freshrss.example.com/i/?a=normal&order=DESC.

FreshRSS version : 1.14.1-dev

**Comment by Alkarex** [comment]
Merci :-)
Could you please test https://github.com/FreshRSS/FreshRSS/pull/2318

**Comment by Alkarex** [comment]
Merged in the /dev branch

**Comment by Massedil** [comment]
> Merci :-)

De rien ! :)

> Could you please test #2318

Yes and it works now ! Thanks !
