### ISSUE TITLE
Can't use arrow keys as shortcuts after update to 1.14.0

### ISSUE THREAD

**Issue by thomasrenes** [FreshRSS/FreshRSS#2316]
Since the last update I'm unable to use the "left" and "right" arrow keys for browsing articles. I have set "Open the next article" to "right" and "Open the previous article" to "left" in the shortcut menu. This did work in the previous version. Other shortcuts for browsing do seem to work (tested "R"-key and "L"-key).

**Comment by Frenzie** [comment]
The keyword `left` was specific to the old shortcut plugin. I suspect ArrowLeft would work, but the PHP side of things currently rejects that.

https://github.com/FreshRSS/FreshRSS/blob/d413f67dd28738f4a6d8cf036e00714737f757b8/app/Controllers/configureController.php#L156-L175

@Alkarex Shall we add the old values to the JS or change the PHP to standard JS?

**Comment by Alkarex** [comment]
Yes, let's change the PHP code to use the standard codes such as `ArrowDown`, and possibly add a conversion in PHP for old configurations.

**Comment by Frenzie** [comment]
Incidentally, the standard names are defined here: https://www.w3.org/TR/uievents-key/

But it's easier to get them from a quick event catcher, e.g., [here](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key#Result).

`PageUp` and `PageDown` also stand out as being different.

**Comment by Alkarex** [comment]
Could you please try https://github.com/FreshRSS/FreshRSS/pull/2320 ?

**Comment by Alkarex** [comment]
Merged in the /dev branch to ease testing

**Comment by thomasrenes** [comment]
> Merged in the /dev branch to ease testing

Thanks for the quick fix! I can confirm the arrow keys are working again for browsing on `/dev`.
