### ISSUE TITLE
[FR] 1.14 - Docker CRONTAB issue

### ISSUE THREAD

**Issue by Balooforever** [FreshRSS/FreshRSS#2319]
Bonjour,

Le CRONTAB (avec la variable "CRON_MIN=*/10") dans l'image Docker ne semble plus fonctionnel avec la base 'Ubuntu'.

Je n'ai aucun log. Je me suis connecté sur l instance Docker et j'ai executé la commande du Docker :
 su apache -s /bin/sh -c 'php /var/www/FreshRSS/app/actualize_script.php' 2>> /proc/1/fd/2 > /tmp/FreshRSS.log

Le retour : No passwd entry for user 'apache'

Si l'on remplace su apache par su root, j'ai bien une actualisation.

Merci

**Comment by Alkarex** [comment]
Merci pour le rapport de bug. Devrait être corrigé dans https://github.com/FreshRSS/FreshRSS/pull/2321

**Comment by Alkarex** [comment]
Disponible dans le tag `:dev`
Tests bienvenus

**Comment by Balooforever** [comment]
La commande fonctionne maintenant avec le nouvel user, par contre ça n a pas l air de tourner. : en 2h aucunes updates alors que j ai spécifié */10
La commande est bien présente avec crontab -l

**Comment by Alkarex** [comment]
Je ne devais pas être bien réveillé. Pourriez-vous réessayer `:dev` ?

**Comment by Balooforever** [comment]
C'est parfait ! :)

**Comment by Alkarex** [comment]
Il y avait un autre problème dans la nouvelle variante Ubuntu, qui devrait être résolu à l'instant dans `:dev` : maintenant, les logs du cron devraient apparaitre dans les logs Docker (lorsque le cron démarre, finit, et engendre des requêtes HTTP). Pourriez-vous vérifier ?

**Comment by Balooforever** [comment]
Ça me semble pas mal :
FreshRSS[98]: FreshRSS Start feeds actualization...
FreshRSS[98]: FreshRSS feeds actualization done.,

**Comment by Alkarex** [comment]
Super, merci pour les tests :-)
