### ISSUE TITLE
Cacher les articles après lecture

### ISSUE THREAD

**Issue by Bedeau69** [FreshRSS/FreshRSS#2323]
Bonjour,

Depuis la version 1.14.0, l'option "Cacher les articles après lecture" ne semble plus fonctionner. J'ai essayé de la décocher puis re-cocher, comportement identique.

Merci
Vincent

**Comment by Alkarex** [comment]
Merci pour le rapport de bug. Sera corrigé

**Comment by techexo** [comment]
Je ne sais pas si c'est lié ou pas (voire si c'est la même chose et que je n'ai pas compris...), mais il y a un comportement bizarre sur mon instance FreshRSS lors du défilement : les articles ne sont pas marqués comme lus (je n'ai pas coché l'option "Marquer comme lu au défilement de la page"), par contre la partie de la liste d'article qui a défilé vers le haut (cachée à l'écran, donc, au moment où on "scroll down") n'est plus affichée lorsque je reviens en haut de page.
Il faut donc que je clique sur le nom de la catégorie/du feed pour tout revoir.

J'essaie de mettre en ligne un screenshot animé ASAP, ce sera plus clair...

Edit: ![GIF Screencast](https://user-images.githubusercontent.com/1850197/55395404-c225c080-5541-11e9-9732-feb8f5d2c423.gif)

On peut aussi voir les espèces de "saut" vers le haut quand je défile vers le bas, qui ne sont pas hyper esthétiques.

**Comment by Alkarex** [comment]
Pourriez-vous essayer cette correction ? https://github.com/FreshRSS/FreshRSS/pull/2334
Edit : Oups, ne marche pas pas dans IE. Je corrige ça plus tard

**Comment by oupala** [comment]
Ca ne semble pas corriger le problème, j'ai le même comportement qu'avant (testé avec Firefox 60 ESR).

**Comment by Alkarex** [comment]
Nouvelle version de https://github.com/FreshRSS/FreshRSS/pull/2334
Pourriez-vous réessayer ?

**Comment by Alkarex** [comment]
Disponible dans la branche /dev
Tests bienvenus

**Comment by techexo** [comment]
@Alkarex S'agissant de mon problème, ça semble être résolu (les articles ne disparaissent plus lors du scroll). 😃 
Il faudrait confirmation de @Bedeau69 pour voir si ça résout également le problème d'origine décrit dans ce ticket.
