### ISSUE TITLE
Active category gets expanded during navigation

### ISSUE THREAD

**Issue by bastien30** [FreshRSS/FreshRSS#2324]
Since FreshRSS 1.14, active category get expanded during navigation.
That wasn't the case before.

This is not practical when you have dozens of feeds in each category : you have to unexpand the category or to scroll to go on the next.

**Comment by bastien30** [comment]
Hi,
Any news ?
This bug annoy me since more than a year now...
Thanks

**Comment by Alkarex** [comment]
Hello,
I have forgotten the context: can you tell which options you use, and how you navigate?
Do you mean that clicking on a category should not expand it? I cannot remember that was possible.
While waiting for something better, you can use the keyboard shortcut <kbd>Alt ⎇</kbd>+<kbd>j</kbd>

**Comment by bastien30** [comment]
Hello,
Below my display and read options :
![image](https://user-images.githubusercontent.com/5484905/78985555-5d744d00-7b29-11ea-8ce0-2f7c6b5ec0fe.png)
![image](https://user-images.githubusercontent.com/5484905/78985584-6fee8680-7b29-11ea-81c6-5836f5071f36.png)

I'm using FreshRSS for a while now, and before version 1.14, categories were never expanded when clicking on it.

I used to navigate by categories.

For example, here is my navigation bar with no categories selected : 
![image](https://user-images.githubusercontent.com/5484905/78986235-1ab37480-7b2b-11ea-8ff8-b4fb9f8848b2.png)

But for example, if I click on a category that have many feeds, here is the result :
![image](https://user-images.githubusercontent.com/5484905/78986321-53534e00-7b2b-11ea-8e7f-987be75e9657.png)

So I've to unexpand the category or scroll down, every time I want to go in a category that is below.

I understand this is not a major issue, but it bothers me everydays.

Thanks

**Comment by Alkarex** [comment]
@bastien30 Could you please test https://github.com/FreshRSS/FreshRSS/pull/2888 ?

**Comment by bastien30** [comment]
It works like a charm ! 👍 
Thank you very much !!
