### ISSUE TITLE
"mark as read" has a ~1sec delay

### ISSUE THREAD

**Issue by sleeksorrow** [FreshRSS/FreshRSS#2332]
After updating to 1.14.0 marking articles as read has a delay of about 1 second until the "eye" icon and the headline turns grey. The other way around, marking as unread, has immediate visual feedback.

Maybe marking as read is not handled asynchronously anymore? Maybe intended?

**Comment by Alkarex** [comment]
Yes, intended, and even more asynchronous than before

https://github.com/FreshRSS/FreshRSS/issues/2310#issuecomment-478465498

> Regarding the delay, it is because marking as read is now sent in batch, max once per second. You can mark many as read or even scroll down without waiting.

We will follow-up in https://github.com/FreshRSS/FreshRSS/issues/2304 *instant visual feedback to users*

**Comment by oupala** [comment]
I'm invitating myself into this issue, sorry if it's not right solution.

I've just updated to version 1.14.0 and it appears that an article does no longer disappear when marked as read. I have to refresh the page (with F5) to see the that the article has disappeared from the unread article list.

Is this the expected behavior?

**Comment by Frenzie** [comment]
@oupala This is with the `Hide article after reading` setting checked? That's in Settings → Reading.

**Comment by Alkarex** [comment]
@oupala Yes, there is a bug to fix https://github.com/FreshRSS/FreshRSS/issues/2323

**Comment by sleeksorrow** [comment]
Thank you for the explanation. I can live with this behavior until #2304 is in place. It's just the impression of unresponsiveness, but after all it's all usable as before.

**Comment by oupala** [comment]
@Frenzie Yes, `Hide article after reading` is checked. I'll check issue #2323.

Sorry for squatting this issue.

**Comment by Alkarex** [comment]
Could you please try https://github.com/FreshRSS/FreshRSS/pull/2349 ?

**Comment by sleeksorrow** [comment]
Applied to dev branch and works like a charm for me. Thank you!

**Comment by Alkarex** [comment]
Thanks for the quick feedback :-)
