### ISSUE TITLE
Ubuntu Docker image cronjob not working

### ISSUE THREAD

**Issue by neur0manc** [FreshRSS/FreshRSS#2339]
Version 1.14.0, SQLite.

In the release notes of 1.14.0 I found your note that the Ubuntu image is much faster then the Alpine one. So I switched, naturally. After the switch to 1.14.0 and Ubuntu I experienced a dramatic reduction in news entries. I figured out that this is due to the fact that cron is not running, only my feeds that support WebSub still appear.

After digging a bit deeper I think it's related to `/var/spool/cron/crontabs/root`, which looks like this: `*/20 su apache -s /bin/sh -c 'php /var/www/FreshRSS/app/actualize_script.php' 2>> /proc/1/fd/2 > /tmp/FreshRSS.log`. The user `apache` is not available on Ubuntu, it should read **www-data**. Fixing it by hand only works until I recreate the container (or `docker-compose up -d`).

**Comment by neur0manc** [comment]
No, it looks like the error is already in the [Dockerfile](https://github.com/FreshRSS/FreshRSS/blob/master/Docker/Dockerfile#L28)

**Comment by neur0manc** [comment]
I created a pull request that does fix it, at least for me. Hope this helps

**Comment by Alkarex** [comment]
Thanks, but it is supposed to be [already fixed](https://github.com/FreshRSS/FreshRSS/issues/2319) in our /dev branch, and [release candidate 1.14.1](https://github.com/FreshRSS/FreshRSS/pull/2338) is open for testing.
Could you please give a try to the `:dev` Docker image?

**Comment by neur0manc** [comment]
Oh well, sorry for the noise then :-)
