### ISSUE TITLE
create a `latest-release` git tag

### ISSUE THREAD

**Issue by hrehfeld** [FreshRSS/FreshRSS#2342]
I update my installation with `git pull && git checkout <latest release tag>`. 

How about we maintain a `latest-release` tag in the git repo that always points to the latest release (e.g. `latest-release -> 1.14.0`), so we can have easy cronjobs like `git pull && git checkout latest-release`?

**Comment by hrehfeld** [comment]
(once the database needs migration, or manual intervention is required, this would most likely break)

**Comment by Frenzie** [comment]
On this repo that's exactly what `git checkout master` would do.

**Comment by Alkarex** [comment]
Like @Frenzie says, this is what the /master branch actually is.
All the development is done in features branches, which are then merged in /dev (which can be seen as a rolling release branch), which is then every 2-3 months merged in /master to form a new release.
Example: https://github.com/FreshRSS/FreshRSS/pull/2338

**Comment by hrehfeld** [comment]
Awesome, sorry for not checking `master` before ;-)

As you added the Documentation label, I'm not gonna close, but feel free to do so!
