### ISSUE TITLE
Flat theme not auto-scrolling

### ISSUE THREAD

**Issue by alfureu** [FreshRSS/FreshRSS#2343]
With the update to the latest version I lost the ability to auto-scroll with the Flat theme to the top of the window, while having the actually reading article (and having the unread/read ones closed). Could you fix it?

**Comment by Alkarex** [comment]
Could you please try the /dev branch?

**Comment by Alkarex** [comment]
We have a [release candidate 1.14.1](https://github.com/FreshRSS/FreshRSS/pull/2338) containing a number of fixes, including something likely addressing your issue

**Comment by alfureu** [comment]
Hi @Alkarex, unfortunately not, as I am using the default release on my NAS from the App Store.

**Comment by Alkarex** [comment]
So I need to be sure I understand your issue more precisely.
By auto-scroll, you mean marking articles as read as you scroll, right?
Or by using keyboard shortcuts?
Please tell what browser you are using and what FreshRSS reading options you are using.
A screeenshot / screencast would help further :-)

**Comment by alfureu** [comment]
Ok, so on mobile I use the extensions TouchControl, where I swipe, and the next unread article opens. Whenever I swipe, the read article moves up (disappears from the screen) and the top of the screen moves the next unread article.

Similarly, I was using the method on Desktop (W10 latest updates, Edge browser). I press the button `J` and it moves to the next unread article. However, with the recent update the whole list of articles does not move to the top of the window, it stays where it is, so as I progress in the list of articles, there is less and less space for the actually opened article's text. 

My Reading settings are:
- Number of articles per page 100  Divided by 2 in the reading view. 
- Sort order: Newest first
- Default view: Normal view
- Articles to display: Show only unread
- [x] Hide categories & feeds with no unread articles (does not work with “Show all articles” configuration) 
- [ ] Show articles unfolded by default 
- [ ] Show categories unfolded by default 
- [x] Stick the article to the top when opened 
- [x] Load more articles at the page bottom 
- [x] Use "lazy load" mode to load pictures 
- [x] Clicking outside of article text area closes the article 
- [x] Display a confirmation dialog on “mark all as read” actions 
- [ ] Hide articles after reading 
- [x] Mark updated articles as unread 
Mark article as read…
- [x] when article is viewed 
- [x] when article is opened on its original website 
- [ ] while scrolling 
- [ ] upon receiving the article 
After “mark all as read”,
- [x] jump to next unread sibling (feed or category) 

My only setting in customCSS is: `#sidebar {overflow-y:hidden}`

**Comment by Alkarex** [comment]
I cannot reproduce. When it is released later this week-end, please try version 1.14.1 without extensions.

What is the reason for that custom CSS rule?

**Comment by alfureu** [comment]
Hi @Alkarex, sorry to hear that you cannot reproduce, However, this does not mean that the issue is non-existent, and I find it a bit unfair that you simply close the report. Please find attached a GIF I made of the issue, proving that this is _very real_. What you can see is that I am moving between posts with hitting the J key, however, the scrollbar on the right is not moving, while I do have enabled option under Settings > Reading > Stick the article to the top when opened (as reported earlier)

Before, all worked fine (1.13.x) Looking forward to the fix. Thanks in advance.


![FreshRSS](https://user-images.githubusercontent.com/10846169/55744940-70e06a00-5a36-11e9-8f14-814943dc68c0.gif)

**Comment by Alkarex** [comment]
@DOFfactory Is the GIF produced with FreshRSS version 1.14.1 without any extension?

**Comment by alfureu** [comment]
No, the latest FresRSS offered under the Update section is 1.14.0. I do have some extensions enabled, you did not mention that they should be disabled. Were there some updates?

**Comment by Alkarex** [comment]
Yes, several issues related to your problem have been corrected in 1.14.1.

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/releases/tag/1.14.1

**Comment by Alkarex** [comment]
What update method do you use?

**Comment by Alkarex** [comment]
Cf. my previous message https://github.com/FreshRSS/FreshRSS/issues/2343#issuecomment-480482632

**Comment by Alkarex** [comment]
If you are looking at updates, FreshRSS 1.14.2 has just been released https://github.com/FreshRSS/FreshRSS/releases/tag/1.14.2 to fix a regression in older PHP versions.

**Comment by alfureu** [comment]
Hi @Alkarex, I finally was successful in updating to 1.14.2. I use the update mechanism offered by FreshRSS, i.e. Settings > Update > Check for update. Sometimes this is slower in finding an update, so I have to wait an extra day or two for getting it. The update was smooth and seamless as always.

Now with the changes made, with the current version I am unable to open _any_ article in Normal view. I can click on the title, it opens the corresponding webpage. However, I cannot open any article itself, just navigate between the categories. After further investigation I noticed that _any_ of the following extensions causes this:

- Touch Control
- Sticky Feeds
- Smart Mobile Menu

As soon as I disable _all_ of these, things start to work. FYI, I am using Microsoft Edge 44.17763.1.0, Microsoft EdgeHTML 18.17763

The question arises: will there be some update to these extensions, as they are rather crucial for mobile usecase, which I would feel uncomfortable with to give up.

**Comment by Alkarex** [comment]
I am glad to read that it seems to work again for you.

Yes, we are aware that some extensions are not working anymore, and I will try to see what we can do.

Related: https://github.com/FreshRSS/FreshRSS/pull/2234#issuecomment-480485232

For the extensions by oyox, they do not seem active anymore, and we should consider adding them in our own repository for getting a chance to fix them. It would help if you could make a PR with the current code: https://github.com/FreshRSS/FreshRSS/pull/2234#issuecomment-480522159
Example: https://github.com/FreshRSS/Extensions/pull/47

**Comment by alfureu** [comment]
Thanks @Alkarex, I checked now on my mobile, and the touch controls work there too, so I suppose there is no further need for Touch Control and the other extensions anymore, I guess. Thanks for the follow-up, I am very happy with all the fixes. 

EDIT: Sorry, I had the Touch Control enabled, so **_except_** Touch Control no other extensions are needed.
