### ISSUE TITLE
"Hide articles after reading" does not work any more

### ISSUE THREAD

**Issue by oupala** [FreshRSS/FreshRSS#2345]
Since version 1.14.0, the option "Hide articles after reading" does not seem to work anymore. I tried to uncheck it and then re-check, identical behavior.

When I click on the *read* envelope, it passes from red to grey after a few seconds, and nothing else happens.

Here what I've found in the web console:

```
TypeError: json is null
main.js:213:1
send_mark_read_queue/req.onload
https://example.com/FreshRSS/p/scripts/main.js:213:1
```

Current version is 1.14.1-dev.

**Comment by Alkarex** [comment]
Are you using the latest /dev branch? What browser? Any FreshRSS extension?
I am preparing a patch to show an error message, but that will not in itself your problem, which seems to be due to a failed request.

**Comment by oupala** [comment]
Last commit is commit 71f93e62193a32da7e2da6acfaea6d5d00192c84

> Merge branch 'master' into dev

My browser is Firefox 60.6.1esr 64 bits for linux debian.

No FreshRSS extension.

When I click on the "read" icon, I can see an http request fired:

https://example.com/FreshRSS/p/i/?c=entry&a=read which return code is 200 OK

And the response content is: "### Application problem ###
Permission is denied for `/data/FreshRSS/data/users/myuser/log.txt`"

I've changed the permissions on the data directory, and I now don't have any error in the content, nor in the web console, but I still get the same bad behavior.

**Comment by Alkarex** [comment]
Patch for showing a warning if there is a bad request https://github.com/FreshRSS/FreshRSS/pull/2346

I believe you might have a read-only problem. Please re-apply the correct right-access on the whole `./data/` directory, e.g.

```sh
cd ./FreshRSS/
sudo chown -R :www-data . && sudo chmod -R g+r . && sudo chmod -R g+w ./data/
```

**Comment by oupala** [comment]
As I told you in my previous message, I changed the permission on the data directory.

Now, I don't have any error in the console, nor I have an error in the http response. I now have: `{"tags":[]}`.

**Comment by Alkarex** [comment]
What database are you using?

**Comment by oupala** [comment]
sqlite3

**Comment by Alkarex** [comment]
Please double-check the access rights of `./FreshRSS/data/users/**you**/db.sqlite`

**Comment by oupala** [comment]
```bash
>ls -al data/users/myuser/db.sqlite 
-rwxrwxrwx 1 ops www-data 6050816 avril  4 22:17 data/users/myuser/db.sqlite
```

I'm really searching what could go wrong, but I can't find it...

**Comment by oupala** [comment]
I took the data directory from my production instance, to copy it to this dev instance. There should be any problem with, should it?

**Comment by Alkarex** [comment]
Nothing in your FreshRSS logs, or Web server logs?

**Comment by Alkarex** [comment]
Ah but sorry, I might have misunderstood your issue. You are able to mark your articles as read, right? It is just that they do not disappear when you expect? Try to scroll further down

**Comment by oupala** [comment]
I am able to mark the article as read, but they do not disappear until I scoll down a little bit. You're right.

Is this the expected behavior?

**Comment by viegelinsch** [comment]
On a iOS 12.2 device (iPhone / iPad) in Safari the articles do not disappear even after scrolling.

**Comment by squromiv** [comment]
I confirm the issue. v.1.13.1 Works as it should. As soon as I click on "mark read" icon, article disappears.
And 1.14.0-dev branch functions like @oupala described.

**Comment by Alkarex** [comment]
Yes, the current behaviour is to remove the read articles, but first when they get out of the view. Is that a problem?

**Comment by Alkarex** [comment]
Cf. also a future option to keep XX read articles before removing them https://github.com/FreshRSS/FreshRSS/issues/2347

**Comment by Alkarex** [comment]
Let's close here for the release of 1.14.1 as the feature works, although with a slightly different behaviour.
Feel free to comment on https://github.com/FreshRSS/FreshRSS/issues/2347 or open a new issue if you really want this instant remove behaviour.

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/issues/2347#issuecomment-480489954

> I want to use  "Hide articles after reading" feature as it works in **v.1.13.1**

![1 13 1](https://user-images.githubusercontent.com/15985877/55667665-9bc49580-585f-11e9-9d88-ec6e30c52161.gif)
**v 1.14.0-dev**
![1 14 0-dev](https://user-images.githubusercontent.com/15985877/55667692-f3fb9780-585f-11e9-9263-cbce325aac9a.gif)

**Comment by Alkarex** [comment]
Could you please try https://github.com/FreshRSS/FreshRSS/pull/2349 ?

**Comment by Alkarex** [comment]
Another fix https://github.com/FreshRSS/FreshRSS/pull/2352

**Comment by Alkarex** [comment]
Merged in the /dev branch
