### ISSUE TITLE
Unable to cli/prepare.php - "Arrays are not allowed as constants" via lib_rss.php

### ISSUE THREAD

**Issue by bhyde** [FreshRSS/FreshRSS#2359]
Shortly after git clone:
```
#$ whoami
root
#$ cd /usr/share
#$ rm -rf FreshRSS
#$ git clone https://github.com/FreshRSS/FreshRSS.git
git clone https://github.com/FreshRSS/FreshRSS.git
Cloning into 'FreshRSS'...
remote: Enumerating objects: 7, done.        
remote: Counting objects: 100% (7/7), done.        
remote: Compressing objects: 100% (7/7), done.        
remote: Total 28694 (delta 1), reused 0 (delta 0), pack-reused 28687        
Receiving objects: 100% (28694/28694), 11.19 MiB | 0 bytes/s, done.
Resolving deltas: 100% (19944/19944), done.
#$ cd FreshRSS
#$ cli/prepare.php 
PHP Fatal error:  Arrays are not allowed as constants in /usr/share/FreshRSS/lib/lib_rss.php on line 559
#$ 
```

**Comment by aledeg** [comment]
The reason is your PHP version. I guess you are running PHP prior to 5.6.

**Comment by bhyde** [comment]
Right you are, no idea how that happened.   Where's my stick?!

**Comment by Frenzie** [comment]
The README does say:

> PHP 5.3.8+ (PHP 5.4+ recommended, and PHP 5.5+ for performance, or PHP 7 for even higher performance)

**Comment by bhyde** [comment]
This is on centos 7.  What I observe is:
```
$ php --version
PHP 5.4.16 (cli) (built: Oct 30 2018 19:30:51) 
```
So that should have been a sufficiently fresh version of php; if the doc Frenzie quotes is accurate.

This is all a pretty fresh install and I got futher yesterday.  Today I was switching to mariadb.

Anyhow - forcing php 7 made things get all better.  Which i did by adding these tasks to my play book.
```yaml
  - yum: {name: epel-release}
  - rpm_key:
      state: present
      key: http://rpms.remirepo.net/RPM-GPG-KEY-remi
  - yum_repository:
      name: remi
      description: Remi YUM repo
      baseurl: http://rpms.remirepo.net/enterprise/$releasever/remi/$basearch/
      gpgcheck: yes
      enabled: yes
  - yum_repository:
      name: remi-php72
      description: Remi YUM repo
      baseurl: http://rpms.remirepo.net/enterprise/$releasever/php72/$basearch/
      gpgcheck: yes
      enabled: yes
  - yum:
      name: [php, php-curl, php-gmp, php-intl, php-mbstring, php-sqlite3, php-xml, php-zip, php-pdo, php-pdo_mysql]
      state: present
```
The last task worked yesterday.

And now my install appear to working.    I think i'm happy.  Thanks for the new toy!

**Comment by aledeg** [comment]
I reopen this issue because as mentioned by @Frenzie, we do support PHP 5.3.8+. Thus this should be working no matter what version you're running.
Except if we drop support for older PHP versions. But it's not for the foreseeable future.

**Comment by Alkarex** [comment]
Arg, that is my fault 😓
Too bad this is not caught by our Travis tests. Any idea of how we could have that? Maybe a `php -l` for all files?

**Comment by Frenzie** [comment]
Would that have thrown an error here? I don't have ancient PHP at hand I'm afraid. If it does, better to add it. :-)

**Comment by Alkarex** [comment]
```sh
cd ./FresshRSS/
sudo docker run -it --rm -v $PWD:/usr/share/FreshRSS php:5.3-cli php -l /usr/share/FreshRSS/lib/lib_rss.php

Fatal error: Arrays are not allowed as constants in /usr/share/FreshRSS/lib/lib_rss.php on line 559
Errors parsing /usr/share/FreshRSS/lib/lib_rss.php
```

**Comment by Alkarex** [comment]
Could you please try this patch with your native PHP 5.4? https://github.com/FreshRSS/FreshRSS/pull/2360

**Comment by Frenzie** [comment]
Excellent! (Also thanks, I didn't know that Docker image existed.)

I'll create a PR for it.

**Comment by Frenzie** [comment]
Btw @Alkarex 

```
No syntax errors detected in p/api/fever.php
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in p/api/greader.php on line 380
```

That's with `git ls-files -z "*.php" | xargs -0 -n1 -P4 php -l`.

**Comment by Alkarex** [comment]
Good catch, yes, `continue 2;` indeed

**Comment by Alkarex** [comment]
@bhyde Fix merged in the /dev branch, if you could please try it with your PHP 5.4.

**Comment by Alkarex** [comment]
FreshRSS 1.14.2 has just been released

**Comment by bittaurus** [comment]
Just a heads up, this bug is present again in the package I installed from today's master.zip, with php 5.4, though a different line number.

I just upgraded to php 7.4 to get past it.

**Comment by Alkarex** [comment]
@bittaurus We have dropped PHP 5.4- with FreshRSS 1.15.0 and now require PHP 5.6+

Quick test:

```sh
docker run --rm -v /path/FreshRSS:/path/FreshRSS php:5.6-cli sh -c 'find /path/FreshRSS -name \*.php -print0 | xargs -0 -n1 -P4 php -l'
```
