### ISSUE TITLE
Feature: Keboard shortcut to go to next category and one to go to next feed

### ISSUE THREAD

**Issue by stevanov** [FreshRSS/FreshRSS#2366]
In Inoreader there is a keyboard shortcut (shift+j i believe, and shift+k) to go to the next feed if you're in single feed mode. Freshrss will jump to the next feed when you are in single feed mode and you mark all as read but i'd like to be able to do this with a keyboard shortcut.

Same goes for when you're in a category view, being able to go to the next/previous category would be very useful,

Inoreader shortcuts: https://blog.inoreader.com/2015/05/inoreader-how-to-save-time-with.html

**Comment by Alkarex** [comment]
Hello,
Try `shift+j` in FreshRSS ;-)

![image](https://user-images.githubusercontent.com/1008324/55724462-bdfb1680-5a0b-11e9-913a-5ebce9b45bf4.png)

**Comment by stevanov** [comment]
My mistake, i wasn't seeing the same behaviour i was used to with inoreader (shift + J) there goes to the next feed but it skips feeds with no unread articles.
