### ISSUE TITLE
[Feature request] Add configuration on category level

### ISSUE THREAD

**Issue by aledeg** [FreshRSS/FreshRSS#2369]
We have configuration on the application level, we have configuration on the feed level. But nothing in between. It could be nice to have configuration on category level to limit the configuration on feed level when all feeds in a category have the same configuration.

At the moment, I can think of the archiving policy or the refresh rate.

**Comment by Alkarex** [comment]
Implemented in https://github.com/FreshRSS/FreshRSS/pull/2410
