### ISSUE TITLE
Keeping focus on current feed

### ISSUE THREAD

**Issue by squromiv** [FreshRSS/FreshRSS#2370]
Every time I open a feed, focus jumps to upper part of feed-list.
![dev](https://user-images.githubusercontent.com/15985877/55792310-a6ca3080-5ac0-11e9-8835-9c65ddbd6771.gif)

**Comment by Alkarex** [comment]
Good idea to fix that

**Comment by Alkarex** [comment]
Fixed by https://github.com/FreshRSS/FreshRSS/pull/3231
