### ISSUE TITLE
[Swage] Rrefresh icon is broken on Firefox 66

### ISSUE THREAD

**Issue by pieqq** [FreshRSS/FreshRSS#2375]
I'm a happy FreshRSS user using the Swage theme. One thing I've noticed for quite a while now is that the Refresh icon is broken on Firefox.

Here is how it looks on Firefox 66.0.2 Desktop (running on Ubuntu Linux 18.04):
![freshrss-firefox-66 0 2-desktop](https://user-images.githubusercontent.com/512471/56194719-211d2680-6066-11e9-91df-8488f1157989.png)

And here is how it looks on Firefox 66.0.2 for Android (running on Android 8.0):
![freshrss-firefox-66 0 2-mobile](https://user-images.githubusercontent.com/512471/56194718-20849000-6066-11e9-8abb-495fe5086da3.png)

For a long time I was wondering what was the meaning of this icon, until I had a look at the source code and find that it was `refresh.svg` and it was actually supposed to be an circle arrow, which is a pretty standard way to represent a Refresh action!

I've tried to import the SVG icon in GIMP and it imports properly, so I'm not sure why it doesn't render properly on Firefox.

cc @pattems who seems to be the author of Swage theme. Thanks in advance!

**Comment by Frenzie** [comment]
If you use spaces instead of commas in the d attribute for the path element it works:
```
M13.5 2.4C12.1 1 10.1 0.1 8 0.1c-4.3 0-7.7 3.5-7.7 7.7s3.5 7.7 7.7 7.7c3.6 0 6.6-2.5 7.5-5.8h-2c-0.8 2.3-2.9 3.9-5.5 3.9 -3.2 0-5.8-2.6-5.8-5.8S4.8 2.1 8 2.1c1.6 0 3 0.7 4.1 1.7L9 6.9h6.8V0.1L13.5 2.4z
```

**Comment by Alkarex** [comment]
Indeed, the `path` `d ` syntax did not work in Firefox or Inkscape.
Could you please try https://github.com/FreshRSS/FreshRSS/pull/2376 ?

Reference: https://www.w3.org/TR/SVG11/paths.html#PathData

**Comment by Alkarex** [comment]
In the SVG `path` `d`, `h-2,c` is not OK: It should be either `h-2 c` or `h-2c`

**Comment by Alkarex** [comment]
Merged in the /dev branch. Tests welcome.
