### ISSUE TITLE
Tip to make it working on termux android

### ISSUE THREAD

**Issue by badrow** [FreshRSS/FreshRSS#2378]
Hi, if someone weird like me want to make it work on a webserver hosted on an android device (termux for example) the feed will not update with "Unknown error" in logs.

To fix it, comment all syslog lines in all php scripts that call this function, and it will be working.

**Comment by Frenzie** [comment]
Sounds more like a server configuration issue. Incidentally, the first search result shows it might be fixed in the next version: https://github.com/termux/termux-packages/blob/master/ndk-patches/syslog.patch

**Comment by Frenzie** [comment]
@adamsson6 Were you able to verify if an updated version works out of the box?

**Comment by Frenzie** [comment]
I'll close this one for the reasons since it's not our bug and probably fixed.
