### ISSUE TITLE
Auto tag For the new entry

### ISSUE THREAD

**Issue by nova2018** [FreshRSS/FreshRSS#2380]
I want to give new entry some user tags by the keyword for the entry. 
I want the tag list showed in the page.
Have any good way ?

**Comment by math-GH** [comment]
@i365star Is it still actual? Could you give some examples to understand this Feature Request better?

**Comment by Alkarex** [comment]
I will try to prioritise this feature. I believe we have other issues about automatic actions, which we should link.

**Comment by math-GH** [comment]
with #4101 (version 1.20) the tags can be displayed above/below the article

**Comment by math-GH** [comment]
auto tagging is asked here too: #2420

**Comment by aledeg** [comment]
Is this a duplicate of #3279?

**Comment by Alkarex** [comment]
Ready for testing https://github.com/FreshRSS/FreshRSS/pull/5954
