### ISSUE TITLE
Error 403 when a new user registers

### ISSUE THREAD

**Issue by Dryusdan** [FreshRSS/FreshRSS#2381]
Hello :)

New user can't registers on my FreshRSS instance.
After test, I encounter this error : 
```
Error 403 - Forbidden

You don’t have permission to access this page [CSRF]
```

But registration module is native with freshrss right ? So I don't forgot update it when I update frashrss ? :sweat_smile: 

So I have FreshRSS version 1.14.2 with Swage theme.

Can you help me ? :)

Regards

**Comment by wangz1yu** [comment]
I also encountered the same situation. @Alkarex

**Comment by aledeg** [comment]
I've made some tests. I can reproduce. I search the code to find where this is triggered. At the moment, I don't know where. It's located deep in Minz because the process does not even enter the called method.
So far I am out of luck!

**Comment by Alkarex** [comment]
@aledeg Could you please tell the sequence to reproduce?

**Comment by aledeg** [comment]
@Alkarex it's very easy. You increase the number of allowed user to be greater than the current number of user. Then you logout and try to create a new user from the login page. And then 403!

**Comment by Alkarex** [comment]
Ah, right. @Dryusdan and @wangz1yu : do you believe it is the same issue you are facing?
In which case, we should probably just change the UI to e.g. remove the registration field when there are too many users already.

**Comment by Dryusdan** [comment]
I'm not remember if I increase number of allowed user.
This value is set to 150 (at the start of my instance there is 100 user allowed). But I have only 41 users registed so... The registeration form does appear.

![Capture d’écran du 2019-06-21 09-17-15](https://user-images.githubusercontent.com/4410431/59905207-ca392200-9405-11e9-8fae-23ef1fba7bb8.png)

I try with 0 in allow user (unlimited so) and I have the same error.

**Comment by aledeg** [comment]
@Alkarex I don't think it's a UI error. You cannot register new users even though there are some spots left.

**Comment by Alkarex** [comment]
Ah, indeed, I can reproduce too

**Comment by Alkarex** [comment]
Here is a candidate fix https://github.com/FreshRSS/FreshRSS/pull/2442
Tests welcome

**Comment by Alkarex** [comment]
Merged in the /dev branch. Tests welcome

**Comment by Dryusdan** [comment]
It's work, thank you ! :D
