### ISSUE TITLE
Make username case insensitive during login

### ISSUE THREAD

**Issue by yani** [FreshRSS/FreshRSS#2384]
During a mobile browser login, the username is not checked in a case insensitive way. I have username `yani` and the browser on my phone was capitalizing it as `Yani` during login. This made the login fail. I suggest making the username lookup case insensitive regardless of database configuration, so login issues will be less of a problem and mobile users will have an easier time logging in.

**Comment by rexbron** [comment]
+1

This can be fixed by adding autocaptialize=off to the <input> tag in the login field.

**Comment by Alkarex** [comment]
@rexbron Good idea. Would you mind sending a pull request?

https://github.com/FreshRSS/FreshRSS/blob/master/app/views/auth/formLogin.phtml

For reference: https://developer.mozilla.org/docs/Web/HTML/Attributs_universels/autocapitalize
