### ISSUE TITLE
Add an option to change/expand behaviour of shift+j

### ISSUE THREAD

**Issue by stevanov** [FreshRSS/FreshRSS#2385]
Currently Shift+J moves to the next feed, however when i have all articles in that next feed marked read and have 'Show unread' selected then its somewhat useless to go to the next 'empty' feed.

Could be solved by the following solutions;

- when 'Shown only unread' is selected, shift+j automatically skips to the next feed that has unreads
- an additonal shortcut such as alt+j or something that skips to the next feed that has unread articles
- a checkbox option in settings that is able to turn off or on the described behaviour of shift+j

I'm a former inoreader user and this is one of the larger differences in user experience i've noticed thusfar.

For me this would be an especially useful function (and probably one that i could solve with the custom JS addon), as long as issue #1979 isn't solved yet

(For clarification, pressing 'Mark all as read' already follows this behavior of switching to the next feed with unread articles)

**Comment by stevanov** [comment]
Not sure if this is good form, but I propose changing line 483 in main.js (the next_feed function)
https://github.com/FreshRSS/FreshRSS/blob/d008b6c1a7488b99e77287ba14f1fff3ec1a116b/p/scripts/main.js#L483
AND 466
https://github.com/FreshRSS/FreshRSS/blob/d008b6c1a7488b99e77287ba14f1fff3ec1a116b/p/scripts/main.js#L466

to something like

`if (found && feed.attributes["data-unread"].textContent !== "0") {  `

I've tested this to work on my local instance of FreshRSS

Ideally, we should add a function to the settings menu so that end users have the choice between the skipping and non-skipping behaviour.

**Comment by Alkarex** [comment]
Sorry for the delay. Your suggestion looks reasonable. `feed.getAttribute('data-unread')` should work. Could you make a pull request?

**Comment by stevanov** [comment]
> Sorry for the delay. Your suggestion looks reasonable. `feed.getAttribute('data-unread')` should work. Could you make a pull request?

No problem, feed.getAttribute('data-unread') seems like a neater solution than mine. 
That just leaves one design choice, adding this hard coded will force this behaviour onto everyone which i don't think is desirable.

So i either need to add a checkmark in the options or add a new modifier key for J and K (ctrl+shift?). I think i personally would prefer the checkmark in the settings but i'd appreciate your input on this decision. 

And if so, i would appreciate a pointer to what are all the files i need to change for the addition of a new settings menu option. I've had a look into those files to create a pull request before but i wasnt able to figure out the things i needed to change.

Thanks

**Comment by Alkarex** [comment]
Any feedback from our Mister shortcuts @aledeg ? :-)

**Comment by aledeg** [comment]
Sorry this late feedback. I am still thinking about it and I don't know yet what will be the best course of action. I'll keep you posted.

**Comment by aledeg** [comment]
@Alkarex I've checked that this morning and I thought that a new modifier could work. I was thinking either `shift` + `alt` or `meta`. I've tried both without success until I found the code that block those combinations. I can understand why `meta` is blocked but I can foresee any reason to block the other.

Do you mind explaining the reason behind this behaviour? Is this something we can remove to allow such key combinations?

**Edit** https://github.com/FreshRSS/FreshRSS/blob/03208771f7d38771f7b9c965b79877d97cce311a/p/scripts/main.js#L719-L722

**Comment by Frenzie** [comment]
Alt+Shift is supposed to switch input. Blocking it would be terrible.

**Comment by aledeg** [comment]
What do you mean by that?

**Comment by Frenzie** [comment]
It's extremely hard to find in Windows 10 (just like any other setting), but under Advanced keyboard settings -> Language bar options:

![2019-11-25 10_33_01-Text Services and Input Languages](https://user-images.githubusercontent.com/202757/69528692-08b3a980-0f6f-11ea-97d8-111c563ac4b5.png)

An input field or textarea is expected to switch between input options.

**Comment by aledeg** [comment]
Ok, I see what you mean. But when I say it's blocked, I mean that FRSS does not use it because it's filtered out. See code above.

**Comment by Frenzie** [comment]
Yes, and I'm saying that's good and it shouldn't. ;-)

**Comment by aledeg** [comment]
OK

**Comment by Alkarex** [comment]
@aledeg Yes, you can without problem move these modifiers further down to allow new combinations.

Like:
https://github.com/FreshRSS/FreshRSS/blob/03208771f7d38771f7b9c965b79877d97cce311a/p/scripts/main.js#L788-L792

Remember to have all possible modifiers for each key.

When you are done expressing the conditions allowing such modifiers, you can filter them out like:
https://github.com/FreshRSS/FreshRSS/blob/03208771f7d38771f7b9c965b79877d97cce311a/p/scripts/main.js#L802-L804

**Comment by Alkarex** [comment]
But as @Frenzie is saying, it is important to only explicitly catch what we need without catching combinations used for other purposes

**Comment by Alkarex** [comment]
By the way, additional API: `keyEvent.location` https://developer.mozilla.org/docs/Web/API/KeyboardEvent/location (even supported by IE9...)

**Comment by aledeg** [comment]
@stevanov Please review attached PR

**Comment by aledeg** [comment]
@stevanov Please review the `dev` branch since the PR has been merged. Closing for now but feel free to reopen it if needed.
