### ISSUE TITLE
"actualize_script.php" running time in log

### ISSUE THREAD

**Issue by squromiv** [FreshRSS/FreshRSS#2386]
After running of  "actualize_script.php", the result, shown on the screen or in log-file, contains time, that does not match the system time. For a example, real time: 10:57 (UTC+3:00), and in log-file I can see: 9:57.
![screen_2019 04 26 001](https://user-images.githubusercontent.com/15985877/56793405-43543880-680c-11e9-8504-274a62159833.png)

**Comment by Fake4d** [comment]
Would love to see that!

**Comment by aledeg** [comment]
I think it depends on your server configuration. You should try to change it to match what you want to see.

**Comment by squromiv** [comment]
@aledeg 
You were right. I use XAMPP server and had to change "date.timezone" parameter in "php.ini" file.

Also I had been misled by digits +02:00 in the end of the string, because it looks like Log (server) time = UTC+time zone. But in fact "+02:00" addition carries only informational, but not arithmetic function.

**Comment by Alkarex** [comment]
So, no issue after all, right?
