### ISSUE TITLE
actualize_script works with php56, fails with php72

### ISSUE THREAD

**Issue by gpion** [FreshRSS/FreshRSS#2394]
Here's a trace of successful run using php56:
```
$ sudo -u http php56 /var/services/web/FreshRSS/app/actualize_script.php
Starting feed actualization at 2019-05-05T08:18:13+02:00
Actualize <user1>...
Actualize <user2>...
Done.
Ending feed actualization at 2019-05-05T08:18:14+02:00
Feed actualizations took 0 day(s), 0 hour(s), 0 minute(s) and 1 seconds for 2 users
Results: 
<user1> OK
<user2> OK
End.
```
and when using php72
```
$ sudo -u http php72 /var/services/web/FreshRSS/app/actualize_script.php
Starting feed actualization at 2019-05-05T08:19:56+02:00
Actualize admin...
PHP Fatal error:  Uncaught Minz_PDOConnectionException: Access to database is denied for `freshrss` (`mysql:host=localhost;dbname=freshrss;charset=utf8mb4`) in /volume1/web/FreshRSS/lib/Minz/ModelPdo.php:95
Stack trace:
#0 /volume1/web/FreshRSS/app/actualize_script.php(61): Minz_ModelPdo->__construct('admin')
#1 {main}
  thrown in /volume1/web/FreshRSS/lib/Minz/ModelPdo.php on line 95
Results: 
```

web server is set is to use php 7.2 by default (confirmed py phpinfo()) and FreshhRSS web access is OK
Using a Synology NAS running DSM 6.2.1.

**Comment by gpion** [comment]
Since I thought it was mysql version related, I've migrated my FreshRSS instance DB from mariadb5 mariadb10
Re made the setup from scratch to be on the safe side
And now I'm getting the error for both php versions !

**Comment by gpion** [comment]
I'm making progress
By "stracing" process, it appears that it tries to connect to /tmp/mysql.sock (non existent since I've stopped mariadb5 instance) instead of localhost:<port>

**Comment by gpion** [comment]
Found a fix:
replaced 
pdo_mysql.default_socket = /tmp/mysql.sock
by
pdo_mysql.default_socket = /var/run/mysqld/mysqld10.sock
in /usr/local/etc/php72/cli/php.ini
I still do not not understand why actualize_script.php do not use all the connections settings defined ./data/config.php (seem to ignore db["host"])

**Comment by Alkarex** [comment]
Hello,
What value do you have in `db["host"]` ?

**Comment by gpion** [comment]
> Hello,
> What value do you have in `db["host"]` ?

In what file this is defined?

Anyway, since I've updated php.ini the problem is gone.

**Comment by Alkarex** [comment]
In the `./data/config.php` file.
Ok, let's reopen if the problems appear again.

**Comment by gpion** [comment]
> In the `./data/config.php` file.


`    'host' => 'localhost:3307',`

Why the app effectively uses the unix socket since it is the TCP socket which is defined in the configuration?
