### ISSUE TITLE
[minor] actualize script give incorrect elapsed time statistics

### ISSUE THREAD

**Issue by gpion** [FreshRSS/FreshRSS#2395]
Log output:
```
Starting feed actualization at 2019-05-07T13:00:03+02:00
Actualize <user1>...
Actualize <user2>..
Done.
Ending feed actualization at 2019-05-07T13:00:03+02:00
Feed actualizations took 0 day(s), 23 hour(s), 59 minute(s) and 59 seconds for 2 users
Results: 
<user1> OK
<user2> OK
End.
```

_"23 hour(s), 59 minute(s) and 59 seconds"_ seem pretty much exagerated :->

**Comment by Frenzie** [comment]
That's pretty funny. :-D

Could it be similar to #2386?

**Comment by Alkarex** [comment]
Hum, I cannot reproduce, and I cannot immediately think of what the problem could be.

Test code:

```php
$begin_date = date_create('2019-05-07T13:00:03+02:00');
$end_date = date_create('2019-05-07T13:00:03+02:00');
$duration = date_diff($end_date, $begin_date);
echo $duration->format('%a day(s), %h hour(s), %i minute(s) and %s seconds');
```

What PHP version do you have and on which system?

**Comment by gpion** [comment]
I don't have the issue anymore, I'm using php 7.2. Her'es my actualise command:
`sudo -u http php72 /var/services/web/FreshRSS/app/actualize_script.php`

**Comment by Alkarex** [comment]
Ok, thanks for the feedback. Well, a mistery
