### ISSUE TITLE
not accessible label input field

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#2396]
Hi, 
I've a problem with labels. Basically I can't used them because the input field at the bottom of an item can't be focused.
Since I was not able to play with it yet I don't know if it's because I've no label to view/select or something else.
attached capture after  "🏷️ My labels " is clicked.

![Screenshot_2019-05-11 wallabag - unread feed · FreshRSS](https://user-images.githubusercontent.com/12174676/57574619-a7960f80-743c-11e9-98a2-733a635fec9e.png)

**Comment by Alkarex** [comment]
Hello @lmjst and sorry for the delay.
I cannot reproduce your issue, so I will need a bit more info, such as FreshRSS version, Web browser, any error in the JavaScript console, Web server logs...
Here is how it looks like when there is no label:
![image](https://user-images.githubusercontent.com/1008324/58628211-6bd2c500-82d9-11e9-8040-e6aa87493204.png)

**Comment by ghost** [comment]
Hello, just tried with Chromium and the issue is the same.  
current version of FreshRSS is 1.14.2
Chromium Version 74.0.3729.169 (Build officiel) Built on Ubuntu , running on Ubuntu 16.04 (64 bits)
Firefox Release 67.0

The javascript console shows no error. 
The link on the "My labels" action is https://rss.site.org/p/i/#close 

Thanks

**Comment by aledeg** [comment]
@lmjst do you have any custom CSS or javascript?

**Comment by ghost** [comment]
I don't know if it's linked but there is in the code
"<a href="#close">❌</a>"
but I can't see it nowhere on the window

**Comment by math-GH** [comment]
Is this issue still relevant with FreshRSS 1.18 ?
Do you use the newest version of the ThreePanesView extension?

**Comment by math-GH** [comment]
@lmjst Is this issue still relevant?
