### ISSUE TITLE
Blast! This feed has encountered a problem ERROR

### ISSUE THREAD

**Issue by zitanix** [FreshRSS/FreshRSS#2397]
hello

please test this feed:

`https://androidrepublic.org/forums/public-mods.24/index.rss`

it working fine in feedly but there is blast error in FreshRSS

thank you

**Comment by Alkarex** [comment]
This feed seems to work fine on my FreshRSS instance. Could you please try again? What error do you get?

**Comment by zitanix** [comment]
hello
thanks for your attention

yes it's fixed now
