### ISSUE TITLE
Label with same title as category 

### ISSUE THREAD

**Issue by felleb** [FreshRSS/FreshRSS#2403]
Hi, I can't add a label/tag that has the same title (name) as an existing category: Let's say there is a category »economy« and when I try to add the same name as a label/tag, the input text in the My labels field just disappears and no tag is added. With other labels (or only added letters/numbers like »economy2«) it works just fine. 

My system:
- Docker container,
- FreshRSS version is 1.14.2, 
- database: MariaDB

Thanks!

**Comment by Alkarex** [comment]
Hello @felleb 
That is correct and is due to a limitation in the Google Reader API that we use for the mobile apps. I cannot immediately think about a good workaround, except using slightly different names.

**Comment by felleb** [comment]
Thank you, @Alkarex for the explanation. I'll go with different names for now.
