### ISSUE TITLE
Official App?

### ISSUE THREAD

**Issue by kaktux** [FreshRSS/FreshRSS#2404]
Hi there,

as i am using freshrss (thx!) on a daily basis for some time now - and from time to time easyrss on a sailfish mobile (via android emulator - which works "ok" - little buggy some time but thats ok). I know easyrss isn't main focus of development (and shouldn't be - freshrss all the way) i am asking myself a question:

I just stumbled upon freshrss app on fdroid:
https://f-droid.org/de/packages/fr.chenry.android.freshrss/

Is this an official app? I couldn't find anything about it mentioned here. But it seems to be new and under development - while easyrss hasn't seen an update in a while. So if this is an addition from someone to freshrss or something official it would be nice to get some more info.

Anyway - i just wanted to leave the link here so maybe others can give it a try to.

thx

**Comment by Frenzie** [comment]
It's not. It's an app that specifically targets FreshRSS but will probably work with various Google Reader API compatible servers, see https://git.feneas.org/christophehenry/freshrss-android

(As an aside, it doesn't seem to quite work for me. I guess I've got too many entries or something.)

**Comment by kaktux** [comment]
thx ;) - still isn't a bad thing to have someone develop another compatible app. I couldn't test it myself as i am currently still using an older/not compatible android version via emulator.

**Comment by Alkarex** [comment]
Like @Frenzie said :-)
Let's hope it will evolve into a perfect app :-P
In the meantime, I plan to make a little table to compare the different mobile app options, with their respective strengths and weaknesses, to supplement the list we have https://github.com/FreshRSS/FreshRSS#apis--native-apps

**Comment by Alkarex** [comment]
Documentation of apps in progress https://github.com/FreshRSS/FreshRSS/pull/2942 and help welcome
