### ISSUE TITLE
PHP modules requirements

### ISSUE THREAD

**Issue by Sp3r4z** [FreshRSS/FreshRSS#2408]
Hi

I think it can be really nice, listing all the PHP modules that FreshRSS want/need.

The listed ones on website is:
- Required: libxml, cURL, DOM, PDO_MySQL
- Recommended: JSON, GMP, Zlib, IDN, mbstring, iconv, Zip

But there is some other, listed in the "Installation checking":
- php-ctype
- php-fileinfo

**FileInfo** doesn't seem *required* but **ctype** is. So maybe add that on documentation.

Thx

**Comment by Alkarex** [comment]
Yes. I think we can just refer to the list in our Dockerfile for Alpine, for which most modules have to be explicitly added:

https://github.com/FreshRSS/FreshRSS/blob/744a9e8cf00aef7dec0acfa5f90f0dcfa2ef8837/Docker/Dockerfile-Alpine#L7-L9

**Comment by Sp3r4z** [comment]
Sure, it's a good thing, something like "For a whole module list, check here" (with a link to the Dockerfile), can be really simple but nice.

**Comment by Alkarex** [comment]
Yes indeed. Would you mind making a PR for that? :-)
The reason the documentation does not list `ctype` nor `fileinfo` so far is because those are modules that are activated by default in PHP, so only custom distributions such as Alpine need to worry about them.

**Comment by Sp3r4z** [comment]
I'll do it, for the website (another Github repository then) and also for here.

It depends on PHP package distribution and composition, for sure. I was trying on Alpine, so yes, it is laking of ctype and fileinfo ;)
