### ISSUE TITLE
Removing tags is not working in Google Reader API

### ISSUE THREAD

**Issue by jbeker** [FreshRSS/FreshRSS#2411]
There is an improper comparison when checking the tag name when removing tags on line: https://github.com/FreshRSS/FreshRSS/blob/master/p/api/greader.php#L350

```php
if ($remove != '' && strpos($remove, 'user/-/label/'))
```

Should be:
```php
if ($remove != '' && strpos($remove, 'user/-/label/') === 0)
```

**Comment by Alkarex** [comment]
Thanks @jbeker 
Could you please double-check https://github.com/FreshRSS/FreshRSS/pull/2412 ?
What client are you using?

**Comment by jbeker** [comment]
The fix in #2412 is the same fix I applied locally so looks 👍🏻

I came across the bug as I am implementing Google Reader API support in [NetNewsWire](https://github.com/brentsimmons/NetNewsWire), but I verified the bug existed in Reeder.app as well.

**Comment by Alkarex** [comment]
Ok. Let us know if you get that software to work with FreshRSS, so we can add it to the list of clients :-)

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/issues/2916
