### ISSUE TITLE
Disable annoying "Read all" beneath feed stream

### ISSUE THREAD

**Issue by toraxmalu** [FreshRSS/FreshRSS#2414]
Hi,

especially on mobile, but also on desktop, it is very easy to hit the "Mark as read"-Button beneath the feed stream. Base on the Theme "Origine" I created an additional theme, witch hiding the button without change of the programming code. (Simple added the attribute "visibility: hidden" to the relevant CSS).

Attached the theme folder. Maybe it's helpful.

[OrigineNoAllRead.zip](https://github.com/FreshRSS/FreshRSS/files/3300499/OrigineNoAllRead.zip)

**Comment by Frenzie** [comment]
Btw, display:none will also take away the space it takes up (if desired).

**Comment by aledeg** [comment]
You can use the css extension for that. I think there is no need for a new theme.

**Comment by toraxmalu** [comment]
@Frenzie thanks for the hint. I included it in the next ZIP.
@aledeg I chose this way to ensure a setting survival even after an update. To often I've seen a broken plugin after an update in the past. [Add: In other projects…]

[OrigineNoAllRead.zip](https://github.com/FreshRSS/FreshRSS/files/3300713/OrigineNoAllRead.zip)

**Comment by Alkarex** [comment]
Hello @toraxmalu ,
For the record, there is an option to ask for a confirmation, in case you often hit this button by accident.
I believe this should either be a FreshRSS option (if there is a significant demand) or indeed a custom CSS rule, instead of a new theme.

**Comment by toraxmalu** [comment]
@Alkarex I agree with you, it should be an UI-Option and also I assume an easy implementation.

Oh sh*t - wasn't my intention to open a full discussion. My suggestion is only my quick-fix to handle my problem without dealing with plugins nor complicating further updates for myself. And the intention of dropping it here is to share and giving back to community…

**Comment by aledeg** [comment]
@toraxmalu regarding the setting survival, I think a proper server backup is enough.
Anyway, thank you for sharing!

**Comment by toraxmalu** [comment]
@aledeg a server backup is only helpting, if you want to remember and deal with each modification you made to the original files. my target was really to have
1. a quick'n'dirty solution without creating a resulting havoc to deal afterwards - especially on updates.
2. not everyone has a shell access to his webspace. My update process is really downloading the zip-archive and overwriting all files with new version, because only access via SFTP… not elegant, but it works

**Comment by math-GH** [comment]
is it still an open issue?
@toraxmalu provided his/her own theme (see download link)
@aledeg suggested to use the custom CSS extension (that works very well): https://github.com/FreshRSS/Extensions/tree/master/xExtension-CustomCSS
@Alkarex suggested to use the " Load more articles at the bottom of the page " option (disable it) to prevent the "Mark as read all" button at the end of list
