### ISSUE TITLE
E-Mail as username not possible during dirst time installation

### ISSUE THREAD

**Issue by Offerel** [FreshRSS/FreshRSS#2418]
With the fix for #2407 i can use a e-mail address as username. This works perfectly, if i add a user in a old installation. However, when i add a new user during first time installation, the @ and dot signs are removed from the username and the user is created without that signs. This prevents the user from logging in.

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/blob/744a9e8cf00aef7dec0acfa5f90f0dcfa2ef8837/app/install.php#L128

**Comment by Alkarex** [comment]
Fix available in https://github.com/FreshRSS/FreshRSS/pull/2421

**Comment by Alkarex** [comment]
@Offerel Could you please test the /dev branch again?

**Comment by Offerel** [comment]
Hi there. Just to be sure to have the latest installation, i cloned the repo again and checked out the dev branch. After that i made a new test vHost with Nginx and created a new user with a email address in first time installation. Only difference to the before done installation is, that i now used SQLite, instead of MySQL. This time, the email user was created successfully and i could login to that installation. For me the issue is solved. 

Is a test with the other DB backends needed? I didn't have PostgreSQL installed on my raspberry pi currently. Most i use MySQL. Do you want, that i do some special security test since you flagged it with "security" label?

**Comment by Alkarex** [comment]
Thanks for the tests @Offerel 👍  I already checked with other databases, but additional testing is always welcome :-)
