### ISSUE TITLE
Sharing options empty in dev

### ISSUE THREAD

**Issue by Offerel** [FreshRSS/FreshRSS#2419]
If i open the options > sharing, the page is empty in dev branch

**Comment by Alkarex** [comment]
Hello,
Could you please attach a screenshot, and also check the logs for any error?

**Comment by Offerel** [comment]
It seems, that this is client specific. In the meantime im back at home from work, and there it works. I see the page as it should. Nothing was in the logs at server side. On Monday, when I'm back at work, i check there the log in Firefox inspector, if i found something.

**Comment by Offerel** [comment]
The problem was uBlock Origin. There was a list active easylist:fanboy-addon/fanboy_social_general_block.txt. If i deactivate that list, the sharing page works.

**Comment by aledeg** [comment]
I've reopened it to add that in the documentation. It might help others.
Thank you for sharing.

**Comment by Offerel** [comment]
One addition: You can leave easylist:fanboy-addon/fanboy_social_general_block.txt active, but deactivate "sharing" for your domain where you installed FreshRSS. So your own installation is excluded from the block. To do so, the user must go to _uBlock Origin_ > _Options_ > _My Filters_ > Add a new line with:
`*sharing,domain=~yourdomain.com`

**Comment by Frenzie** [comment]
Duplicate with #2509, so closing now.

**Comment by aledeg** [comment]
@Offerel Please have a look at #2643 to check if I covered the original problem. Thank you.

**Comment by Offerel** [comment]
I will check this in the dev branch later today. Generally it should work, if there is no http request with "share" or "sharing" from my understanding.
