### ISSUE TITLE
Tag all articles from feed

### ISSUE THREAD

**Issue by husim0** [FreshRSS/FreshRSS#2420]
Hello,

As it seems to be difficult to implement multi categories due to compatibility with API, it would be great to have the possibility to set tags on feed. All articles from a feed would have feed tags.

It would allow to make filtering easier. For example I'm using rss-bridge for Twitter and right now (without tweak) I can't properly hide Twitter feeds from a category. If I could add them a "Twitter" tag, then I would be able to make a filter with : `-#Twitter` that hide them all. 

(Right now to achieve the same functionality I made a custom Twitter Bridge that set "author" to Twitter as I don't use it, and then I'm able to use `-author:Twitter` ; but it's more a workaround that a proper solution.)

Thank you :)

**Comment by Alkarex** [comment]
Yes, that is doable, and we even have some initial code ("action filters") in which we can add such a feature

**Comment by math-GH** [comment]
@aledeg How is the progress?

**Comment by aledeg** [comment]
I haven't work on that for months. Sorry about that

**Comment by husim0** [comment]
I'm still interested, would be a nice addition, thank you @aledeg

**Comment by Alkarex** [comment]
Ready for testing https://github.com/FreshRSS/FreshRSS/pull/5954
