### ISSUE TITLE
Mark as read unseen articles

### ISSUE THREAD

**Issue by Offerel** [FreshRSS/FreshRSS#2429]
I don't know if I just did something wrong, but it seems that all unread articles are marked as read when I click on the button in the menu, even those that are currently not visible.

For example: 12 unread articles are displayed in the list. I click on one of these articles and read it. It will be marked as read. 11 articles remain unread. But while I read article 12, more articles are found, so I have a total of 15 unread articles. The 3 new articles are not shown in the list yet. If I now click on the button "Mark as read" all 15 articles will be marked as read. The 3 new articles will never be displayed.

Is there some way, to mark only the visible articles as read? Or is my workflow wrong?

**Comment by Alkarex** [comment]
Thanks for the bug report @Offerel 
Could you please try this fix? https://github.com/FreshRSS/FreshRSS/pull/2431
I can merge it in our /dev branch if it makes it easier for you to test

**Comment by Offerel** [comment]
Easy small hack for me. I let you know what i have found in some hours.

**Comment by Offerel** [comment]
I can confirm that this is working for me. 

- Had 5 articles new in the list. 
- Disabled "Auto Refresh" Extension. 
- started manually CLI Update with` php /var/www/freshrss/app/actualize_script.php > /var/log/FreshRSS.log 2>&1`
- Firefox Notification popup that new articles are there (6 total)
- Click on "Mark as read"
- Displayed 5 are marked as read
- 1 new is in the list (the one which was new and not visible)

So for me, its fixed.

**Comment by Alkarex** [comment]
Thanks for the quick test 👍

**Comment by Offerel** [comment]
thx for the fast fix.

**Comment by Offerel** [comment]
It seems this issue is back again. I dont know if a new reason is given for that. But after updating to 1.16 i had several seconds ago 7 new articles at the left side in "main feeds" but only 5 displayed. After clicking "Mark all as read", all 7 articles marked as read, not only the 5 in the main frame...
