### ISSUE TITLE
Docker-compose without Traefik

### ISSUE THREAD

**Issue by SecT0uch** [FreshRSS/FreshRSS#2433]
I'm quite new to docker and I would like to setup a docker-compose without Traefik.
My host already have a nginx reverse proxy who redirects any HTTP to HTTPS.
My goal is to setup a docker compose listening only on host local address on port saying 8282 and forward any request to news.example.net to https://127.0.0.1:443.

Giving this nginx.conf:

```
upstream freshrss {
        server 127.0.0.1:8282;
        keepalive 64;
}

server {
    listen 443 ssl http2;
    server_name news.example.net;
    ssl_certificate /etc/nginx/certs/cert.crt;
    ssl_certificate_key /etc/nginx/certs/cert.key;
    proxy_redirect off;
    proxy_cookie_path / "/; HTTPOnly; Secure";

    location / {
                try_files $uri $uri/ =404;
                index index.htm index.html;
        }

    location /freshrss/ {
        proxy_pass https://127.0.0.1:8282;
        add_header X-Frame-Options SAMEORIGIN;
        add_header X-XSS-Protection "1; mode=block";
        proxy_redirect off;
        proxy_buffering off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_read_timeout 90;

        # Forward the Authorization header for the Google Reader API.
        proxy_set_header Authorization $http_authorization;
        proxy_pass_header Authorization;
    }
}
```

What would be the docker-compose.yml for me ?
I wasn't able to setup one working properly.

**Comment by Frenzie** [comment]
You can also just use a command line as shown here:

https://github.com/FreshRSS/FreshRSS/tree/master/Docker#run-freshrss

I don't really know Docker compose yet, but I believe the equivalent of the `-p` flag would be something like: 

```
ports:
      - "8282:80"
```

**Comment by Alkarex** [comment]
Hello @SecT0uch ,
If you already have a reverse proxy running, running the FreshRSS Docker image might be just enough, without Docker Compose. Is your reverse proxy on a Docker network or not?

https://github.com/FreshRSS/FreshRSS/tree/master/Docker#alternative-reverse-proxy-using-nginx

**Comment by SecT0uch** [comment]
Ok I figured out a few of my errors:
First, my conf nginx had an error : `proxy_pass https://127.0.0.1:8282` is wrong, as the docker serves it on HTTP. This is correct : `proxy_pass http://127.0.0.1:8282`
Second, I had issues with the docker run command. I didn't know the postition of the `-p` had an impact: It doesn't work if it's placed at the end of the command (Maybe it would be worthy to precise it in the doc).

So the setup who works well this conf nginx : 
```
upstream freshrss {
        server 127.0.0.1:8282;
        keepalive 64;
}

server {
    listen 443 ssl http2;
    server_name news.example.net;
    ssl_certificate /etc/nginx/certs/nginx-selfsigned.crt;
    ssl_certificate_key /etc/nginx/certs/nginx-selfsigned.key;
    proxy_redirect off;
    proxy_cookie_path / "/; HTTPOnly; Secure";

    location / {
        proxy_pass http://127.0.0.1:8282;
        add_header X-Frame-Options SAMEORIGIN;
        add_header X-XSS-Protection "1; mode=block";
        proxy_redirect off;
        proxy_buffering off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_read_timeout 90;

        # Forward the Authorization header for the Google Reader API.
        proxy_set_header Authorization $http_authorization;
        proxy_pass_header Authorization;
    }
}
```
And this command : 
`sudo docker run -p 127.0.0.1:8282:80 -d --restart unless-stopped --log-opt max-size=10m -v /docker-volumes/freshrss:/var/www/FreshRSS/data -e 'CRON_MIN=4,34' -e TZ=Europe/Paris --net freshrss-network --name freshrss freshrss/freshrss`
OR
This equivalent docker-compose.yml and the answer to my original question:
```json
version: '2.3'

services:
  freshrss:
    container_name: freshrss
    image: freshrss/freshrss:latest
    restart: unless-stopped
    networks:
      - freshrss-network
    volumes:
      - '/docker-volumes/freshrss:/var/www/FreshRSS/data'
    ports:
      - "127.0.0.1:8282:80"
    environment:
      - CRON_MIN="4,34"
      - TZ=Europe/Paris
    logging:
      options:
        max-size: "10M"

networks:
  freshrss-network:
    external: false
```

**Comment by Alkarex** [comment]
It is even better not to have the `-p` option at all and only use Docker networks. This way you do not expose an open port on your host machine.

**Comment by SecT0uch** [comment]
> It is even better not to have the `-p` option at all and only use Docker networks. This way you do not expose an open port on your host machine.

I don't understand how can I get nginx to serve me the service without specifying the port ? Using `proxy_pass http://freshrss/;` like in the example ?
Do you have any ressource that explain the concept ?

It indeed seems to be a very interesting solution. I'm stating to really like Docker :+1:

**Comment by Alkarex** [comment]
Yes, like in the example, and it requires having your reverse proxy running in Docker as well. If it cannot be the case, then you must use the `-p` option.

**Comment by SecT0uch** [comment]
Ok, I get it now. It's very interesting !
Unfortunately my reverse proxy is on the host, not in a container..
Thanks a lot,

SecT0uch.

**Comment by Frenzie** [comment]
@SecT0uch You could write something like `-p 127.0.0.1:8282:80` then.
