### ISSUE TITLE
When reading, post formatting using break tags <br/> is ignored.

### ISSUE THREAD

**Issue by rosiel** [FreshRSS/FreshRSS#2437]
I read a poetry blog. The posts are formatted using break tags within paragraphs, for example:
```
<p>
This is line 1
<br>
This is line 2
<br>
This is line 3
...
</p>
```
But in the reader, most break tags get ignored. Here's a screenshot: 
![broken](https://user-images.githubusercontent.com/1943338/60768538-839d2600-a09b-11e9-87e8-372885126d24.png)

This is caused by [css in the base-theme](https://github.com/FreshRSS/FreshRSS/blob/744a9e8cf00aef7dec0acfa5f90f0dcfa2ef8837/p/themes/base-theme/template.css#L629-L631) that ignores all consecutive break tags after the second. Unfortunately, in the html example above, those break tags are considered consecutive even though there's text between them. According to the [commit message](https://github.com/FreshRSS/FreshRSS/commit/0ef1fd6e4dd55f3626bae585b04b82ad194b8c63), this style bit was added for sites like lemonde.fr, which (5 years ago) put extraneous `<br/>` tags in their posts.

I can fix this on my own installation by installing the Custom CSS plugin and adding the following CSS:
```
br + br + br { 
   display:inline; 
}
```
Which results in:
![fixed](https://user-images.githubusercontent.com/1943338/60768634-9bc17500-a09c-11e9-85d0-777b1e1ab155.png)

Is this bit of style override still necessary? I tried loading lemonde.fr feeds and didn't find any extraneous `<br/>` tags. It's kind of a custom hack for a particular poorly-formatted feed, and causes a bug when breaks are used meaningfully.

**Comment by Alkarex** [comment]
Bonsoir,
Indeed, I think we should get rid of that rule. Would you mind sending a pull request? :-)
