### ISSUE TITLE
[Q] Don't show articles with keyword

### ISSUE THREAD

**Issue by Offerel** [FreshRSS/FreshRSS#2447]
From a particular feed, I don't want articles with a particular keyword to appear in the list of new articles. If I understand this correctly, it should work via the "Filter Action" function of the feed. I have therefore tried to set a "Filter Action" to 
```
Fortnite!
-intitle:Fortnite
```
However, articles with the keyword "Fortnite" will still appear in the list as unread new articles. What can I do?

**Comment by Alkarex** [comment]
Did you you try simply:
`intitle:Fortnite`
