### ISSUE TITLE
MySQL: Article not imported (long content)

### ISSUE THREAD

**Issue by nicofrand** [FreshRSS/FreshRSS#2448]
Hi,

it seems an article cannot be imported if its content is too large:

**STR**

1. Import http://www.madd.fr/feed/atom/

**What happens:**

The article named "Bankass" has a long content (due to embedded inline images) and is rejected due to the following error:

```
[Fri, 19 Jul 2019 12:13:59 +0200] [error] --- SQL error addEntry: 22001: 1406 Data too long for column 'content_bin' at row 1 while adding entry in feed 4 with title: Bankass
```

**What I expect:**:

The article is imported (maybe increase the content_bin column size?).

**Comment by Alkarex** [comment]
Hello,
It looks like you are using MySQL, right? (Alternatively, it works with SQLite and PostgreSQL)
That column is declared as `blob` without any further restriction, so I am not sure what the problem is.

https://github.com/FreshRSS/FreshRSS/blob/caeeeb52cafe105c157f838397ade70bc8609900/app/SQL/install.sql.mysql.php#L72

I would have to investigate further. At a quick glance, the max length can be tuned in the MySQL parameters https://dev.mysql.com/doc/refman/8.0/en/blob.html but the defaults (16MB) are high enough, since your article is only about 374kB.

https://github.com/FreshRSS/FreshRSS/blob/caeeeb52cafe105c157f838397ade70bc8609900/app/Models/EntryDAO.php#L155-L211

**Comment by nicofrand** [comment]
Yes I do use MySQL. On another instance (this one is a dev instance, the other is on a yunohost install still with mysql) the article was imported but without content, but it was imported a long ago with probably an older FreshRSS version.

I thought a `BLOB` was 64Kb and `MEDIUMBLOB` 16MB…

I might have an old mysql version too: `mysql  Ver 14.14 Distrib 5.7.26, for Linux (x86_64) using  EditLine wrapper`.

I'll try to see what length my version allows.

**Comment by Alkarex** [comment]
@nicofrand Ah, I think you are correct. We would need to move to `MEDIUMBLOB` for such long articles. https://dev.mysql.com/doc/refman/8.0/en/storage-requirements.html

**Comment by Alkarex** [comment]
While waiting for a change, you should be able to manually update your `*entry` and `*entrytmp` tables

**Comment by nicofrand** [comment]
I confirm setting both to `MEDIUMBLOB` fixes it.

Thanks!

**Comment by Alkarex** [comment]
@nicofrand Fix just landed in /dev branch https://github.com/FreshRSS/FreshRSS/pull/2551
Additional tests always welcome

**Comment by nicofrand** [comment]
Hi, thank you!

I'll try but I am quite busy at the moment, I don't know when I'll be able to, sorry :/.

**Comment by nicofrand** [comment]
Hi!

Just wanted to confirm the fix on dev branch :+1: 

![image](https://user-images.githubusercontent.com/3419050/66698030-e32e5180-ecda-11e9-95e2-a98087a7425a.png)

**Comment by Alkarex** [comment]
@nicofrand Merci :-)

**Comment by nicofrand** [comment]
Merci à toi !

**Comment by nicofrand** [comment]
@Alkarex Just one question: while testing it I did a hard reset on FreshRSS, recreated a db and when I added the feed it automatically set the feed as read (for each article). Is this a new behaviour or something I should keep an eye on?

**Comment by Alkarex** [comment]
This is probably due to articles being older than your oldest date set in the configuration. There is a PR in progress that will change several aspects https://github.com/FreshRSS/FreshRSS/pull/2335
