### ISSUE TITLE
CLI: ZIP export command informations are display on stderr

### ISSUE THREAD

**Issue by Leepic** [FreshRSS/FreshRSS#2452]
### Explanations

When the CLI export ZIP command for an user is executed, the verbose informations are display on stderr. This is not an error (see below: result sucess), informations must be on stdout instead.

When the command is executed by cron (eg. inside a script), it cause cron to send an email because of stderr.

### Reproduce
`/var/www/html/FreshRSS/cli/export-zip-for-user.php --user Leepic > /tmp/Leepic.zip 2> /tmp/Leepic.stderr`

`cat /tmp/Leepic.stderr`
FreshRSS exporting ZIP for user “Leepic”…
Result: success

### Workaround

Redirect the command to _/dev/null_ or in a file with `>/tmp/Leepic.log 2>&1` but if there is an error in the ZIP export, cron will don't send an email.

### Versions
- FreshRSS: 1.14.3-dev
- PHP: 5.6.40
- MySQL Server 5.5.62
- VPS hosting

**Comment by Alkarex** [comment]
Hello and thanks for the documentation. 
In general, a message on stderr is not a sign of error. The exit code is more robust (0 for success, something else for error).

**Comment by Alkarex** [comment]
I will try to provide you a cron example sending a message in case of error

**Comment by Leepic** [comment]
Hello,

stderr is for errors, diagnostics/debug/help but here it's not the case, based on [this blog post](https://www.jstorimer.com/blogs/workingwithcode/7766119-when-to-use-stderr-instead-of-stdout), I don't know if you'r agree with him :).

I think that this cron example work as expected ([source unix.stackexchange.com](https://unix.stackexchange.com/a/57596)), based on exit code and stderr:

`@daily /usr/local/bin/freshrss-zip-export.sh > /tmp/stdout.log 2> /tmp/stderr.log || cat /tmp/stderr.log; rm /tmp/stderr.log`

So, cron will send an email with the content of /tmp/stderr.log only if the script exit non-zero.
I've try with this example:

* cat /tmp/stderr.sh

```bash
#!/usr/bin/env bash
LANG=C

function getStatusCode() {
	# Get status code of the previous command, display it, then exit with the previous status code
	ret="${?}"
	if [[ "${ret}" -ne 0 ]]; then
		>&2 echo "Status code is '${ret}'"
		exit "${ret}"
	fi
}

# Stdout with status code of 0
echo "result: success stdout"
getStatusCode
>&2 echo "result: failure stderr with exit 2"
# This command have a status code of 2
grep nothing /doesntexists.log
getStatusCode
```

* cron

`* * * * * /tmp/stderr.sh > /tmp/stdout.log 2> /tmp/stderr.log || cat /tmp/stderr.log; rm /tmp/stderr.log`

#### Result

cron send me an email with the content of /tmp/stderr.log:

```
result: failure stderr with exit 2
grep: /doesntexists.log: No such file or directory
Status code is '2'
```

**Comment by Alkarex** [comment]
@Leepic I think I agree :-) Can you spot any contradiction?

Here is a simple example:

File `nok.php` :
```php
<?php
fwrite(STDOUT, '{"Hello":"World"}');	//Data
fwrite(STDERR, 'Some process information and error messages...');	//Info
exit(1);	//Status
```

```sh
php nok.php > /tmp/data.json 2> /tmp/error.txt || cat /tmp/error.txt
```

This last line should do what you want (it might be written more elegantly without a temp file on disk).

I believe your cron will send an e-mail if there is any content, either on STDERR or STDOUT, right?
If not, one can adjust the line above to output on STDERR and even produce an error in the exit code. Something like:

```sh
php nok.php > /tmp/data.json 2> /tmp/error.txt || (cat /tmp/error.txt >&2 ; exit 1)
```

(Might be improved by using the same exit code than the PHP one instead of hardcoded `1`

**Comment by Alkarex** [comment]
@Leepic Would you like to send a pull request to add this piece of information to https://github.com/FreshRSS/FreshRSS/blob/dev/cli/README.md ?

**Comment by Leepic** [comment]
> @Leepic I think I agree :-) Can you spot any contradiction?

Here this is only information message, so it would be on stdout instead, no (because not an error/debug/diagnostics/help message)?

> @Leepic Would you like to send a pull request to add this piece of information to https://github.com/FreshRSS/FreshRSS/blob/dev/cli/README.md ?

Yes, I will submit a PR :).

**Comment by Alkarex** [comment]
STDOUT contains the output itself, e.g. the ZIP file, so it cannot be used
for any other information or error

**Comment by Leepic** [comment]
Yes, you're right, so why don't add an option like --output? It will resolve this issue but I think it's still useful to add this information in the doc.

**Comment by Leepic** [comment]
PR #2457
