### ISSUE TITLE
articles keep opening in new tab

### ISSUE THREAD

**Issue by eliavs** [FreshRSS/FreshRSS#2462]
HI i just installed freshRSS on a server:
when i try reading an article it keeps opening it in a new tab but i want to read it from within 
more issues that seem to be similar is i cannot unfold categories on panel or use keyboard shortcuts
FreshRss. i am not sure what i am doing wrong
Thanks for any help

**Comment by Frenzie** [comment]
Could you describe what you're doing exactly? Normally if you click on the title line it should expand, but if you press space it'll open in a new tab.

**Comment by eliavs** [comment]
@Frenzie  hi thanks for thr response
I cloned the repository of  the dev branch to an Ubuntu 16.04.3 LTS digital ocean droplet.
then i folowed the installation steps using apache shown in the documentation.
i can enter the app using http://[myip]/FreshRSS/ but i cannot use the keyboard shortcuts, cannot unfold categories and articles do not expand.
more information i can give:
I tried adding the three way pane addonn but it does not work
errors i am getting on site:
i am getting an error:`net::ERR_CERT_AUTHORITY_INVALID`
and `Uncaught TypeError: Cannot read property 'documentElement' of null`

**Comment by Frenzie** [comment]
But the demo instance over at https://demo.freshrss.org/i/ works alright? (Just as a quick way to distinguish between browser/system and server.)

> I tried adding the three way pane addonn but it does not work

I'd disable any add-ons for troubleshooting purposes.

**Comment by eliavs** [comment]
the demo works
I disabled all the extensions but still in the same position...

**Comment by Frenzie** [comment]
Right, but it's basic debugging. You want to get rid of other factors as much as possible.

Did you look at installation checking and the logs yet?

**Comment by eliavs** [comment]
I don't know how to check the logs :(

**Comment by Frenzie** [comment]
You can normally just check them through the website (under the top right settings menu), or by adding `?a=logs` to the URL. Alternatively you can find it in the folder, I think in the relevant user subfolder.

**Comment by eliavs** [comment]
Thanks:
most redundant warning is:
[Tue, 23 Jul 2019 18:01:23 +0000] [warning] --- JSON not found for WebSub: [url]/feeds
[Tue, 23 Jul 2019 18:01:23 +0000] [warning] --- Error while WebSub unsubscribing from [url]/feeds

**Comment by Frenzie** [comment]
That's benign, or even if it isn't (e.g., a WebSub implementation bug in FreshRSS) it's just an issue for refreshing that specific feed.

Everything is good in installation checking?
