### ISSUE TITLE
Questions about "By: [link]" present in some entries 

### ISSUE THREAD

**Issue by ArthurHoaro** [FreshRSS/FreshRSS#2466]
I updated my instance, and I noticed that some entries now include "By: [Feed URL]", even though it's not in the actual feed.

Sorry if this has been answered, I don't upgrade often, I couldn't find anything using Github search.

Example:
![screenshot](https://i.imgur.com/AgzEz4d.png)

I have a few questions about it:

   * What's the point of it as I already have the feed name on the right and I can click on it to get its entries?
  * What's up these odd looking slashes `／`?
  * Why does it appear on some entries and not all?
  * Can I disable it?

**Comment by Frenzie** [comment]
In the future it'd be helpful to include a link to the page or feed. ;-)

https://www.ainw.org/links/perso/?do=atom

> even though it's not in the actual feed.

Well… it is though.

```xml
  <author>
    <name>https://www.ainw.org/links/perso/</name>
    <uri>https://www.ainw.org/links/perso/</uri>
  </author>
```

You can hide the author display with the CustomCSS extension using something like `.author{display:none}` but there probably isn't much you can sensibly do against feeds providing weird author names.

**Comment by aledeg** [comment]
So that would be my Shaarli and indeed, the author name is not correct. Probably since I've updated Shaarli to the latest version yesterday.

**Comment by aledeg** [comment]
I think it's a problem on Shaarli's end since I've checked your feed and I have the exact same result.

**Comment by ArthurHoaro** [comment]
> In the future it'd be helpful to include a link to the page or feed

Sorry about that, will do!

> You can hide the author display with the CustomCSS extension

Thank you, it works like a charm.

> So that would be my Shaarli and indeed, the author name is not correct. Probably since I've updated Shaarli to the latest version yesterday.

Okay it uses the author name tag in the feed. I'll update Shaarli to use the instance name instead.
I don't think it's related to the update because I haven't updated mine yet due to a docker issue.

I'll close this issue as it fits my need, but I still think that the conversion of slashes to `&#xFF0F;` is a bit odd.
