### ISSUE TITLE
CSS selector and Lazyloading

### ISSUE THREAD

**Issue by X-dark** [FreshRSS/FreshRSS#2472]
Hi, since their latest website updates, I cannot find how to properly use CSS selector on Les Numeriques website: http://www.lesnumeriques.com/rss.xml

They have added image lazyloading and FreshRSS do not load these images.

Is there any way to make FreshRSS display articles content with images?

I am using latest FreshRSS version.

**Comment by Frenzie** [comment]
Not generically, but in this case it looks like the proper URL is easily found in the `data-srcset` attribute.

**Comment by X-dark** [comment]
So I have seen but I am not sure where to go from there.

**Comment by Frenzie** [comment]
In PHP it'd be very similar to the ImageProxy extension I wrote, see [here](https://github.com/FreshRSS/Extensions/blob/9c34981d7bc986fd12a5a984594e90f19158a88b/xExtension-ImageProxy/extension.php#L49-L70). Except you'd want to go through all the `figure` elements instead.

In pseudo-code, something like this:
```php
		$figures = $doc->getElementsByTagName('figure');
		foreach ($figures as $figure) {
			if ($figure->hasAttribute('data-srcset')) {
// as in the first element of that array; can't recall atm if that's valid PHP syntax this way
				$img = $figure->getElementsByTagName('img')[0];
				$img->setAttribute('src', $figure->getAttribute('data-srcset'));
			}
		}
```

**Comment by math-GH** [comment]
How to proceed here?

**Comment by Frenzie** [comment]
The images in the feed seem to have been fixed, using a regular `src=…` instead of `data-…`.
