### ISSUE TITLE
FreshRSS install  failed requirement - sudo

### ISSUE THREAD

**Issue by wankio** [FreshRSS/FreshRSS#2473]
Without "sudo" 
php /usr/share/FreshRSS/app/actualize_script.php have this problem but with "sudo" it run very well
sudo php /usr/share/FreshRSS/app/actualize_script.php

So how i can fix this ? because 
9 * * * * php /usr/share/FreshRSS/app/actualize_script.php > /tmp/FreshRSS.log 2>&1
seem like not working even when i'm set 9 -> 09minutes so i think sudo is the problem

**Comment by Frenzie** [comment]
You'll need to run it with the right user. The example for Debian/Ubuntu from the README uses the `www-data` user.

https://github.com/FreshRSS/FreshRSS#example-on-debian--ubuntu
```
6,36 * * * * www-data php -f /usr/share/FreshRSS/app/actualize_script.php > /tmp/FreshRSS.log 2>&1
```

**Comment by wankio** [comment]
thank you
actually i'm not ubuntu user, i'm just a windows user using bash env, it confused me a litte bit  :D

**Comment by Frenzie** [comment]
In that case something similar likely applies. [This tutorial](https://react-etc.net/page/installing-wordpress-on-windows-subsystem-for-linux-wsl-ubuntu) suggests the same `www-data` user is involved, which probably makes sense because iirc the WSL uses the Ubuntu userland.

**Comment by Frenzie** [comment]
You should be able to test using `sudo -u www-data php /usr/share/FreshRSS/app/actualize_script.php` to use the `www-data` user instead of the superuser.

**Comment by wankio** [comment]
i'm removed sudo password with sudo visudo, so now i'm just need using 
`sudo -u www-data php /usr/share/FreshRSS/app/actualize_script.php` in crontab -e and save as `/etc/cron.d/FreshRSS`

right ? thank , it's been a very long time from last time i'm used cron to renew ssl on digitalocean

**Comment by Frenzie** [comment]
For cron use I'd just stick with the example I gave above, which tells cron to run the command as the `www-data` user. But either way should work.

**Comment by wankio** [comment]
ok thank, seem like my service cron start is not start yet, i'm just start it with sudo. Maybe next time i will install freshrss on odroid/orange pi or linux/ubuntu server instead using windows.

**Comment by wankio** [comment]
ubuntu/xampp/amazon worked, you can close this issue :)
