### ISSUE TITLE
Show authors next or underneath title

### ISSUE THREAD

**Issue by jkinable** [FreshRSS/FreshRSS#2478]
When clicking on an item, it expands and shows among other things the author information, e.g.:
By: Aleksandrina Goeva · Henry Lam · Huajie Qian · Bo Zhang
Is there a way to show the author information in 'Normal view' in a small font size immediately underneath the title without having to click on the item? Something like:

Optimization-Based Calibration of Simulation Input Models <sub>Aleksandrina Goeva · Henry Lam · Huajie Qian · Bo Zhang</sub>

Ideally the authors should be stated on a new line.

My primary usage of FreshRSS is to read feeds of academic journals. Being able to see the full titles and authors would be super helpful. I use the solution in #2344 to wrap long titles.

**Comment by jkinable** [comment]
First the good news: it is possible:
![image](https://user-images.githubusercontent.com/2742474/62556343-f3f2bf00-b874-11e9-8236-afa3e4b37e44.png)
This looks gorgeous and is exactly what I (and probably various others) need! Unfortunately there are a few issues.

1. I was able to get this to work by 'hacking' the `entry_header.phtml` file. Not only is my 'hack' probably ugly since I know nothing about web-development, my main concern is that my changes will be lost next time FreshRSS updates. In summary, in `entry_header.phtml` I changed this line:
```
<li class="item title"><a target="_blank" rel="noreferrer" href="<?php echo $this->entry->link(); ?>"><?php echo $this->entry->title(); ?></a></li>`
```
to this:
```
<li class="item title"><a target="_blank" rel="noreferrer" href="<?php echo $this->entry->link(); ?>"><?php echo $this->entry->title(); ?></a>
<div style="color: #555; font-size: 11px;font-weight: normal;">
<?php
$authors = $this->entry->authors();
if (is_array($authors)):
        $first = true;
        foreach ($authors as $author):
                echo $first ? $author : ', ' . $author;
                $first = false;
        endforeach;
endif;
?></div>
</li>
```
2. Whenever there are too many authors, it pushes out the date:
![image](https://user-images.githubusercontent.com/2742474/62556810-f6094d80-b875-11e9-8454-c589a4f3fbfb.png)
3. Sometimes the author 'style' is ignored (notice the author font of the first 2 entries vs the small,grey author font of the remaining entries)
![image](https://user-images.githubusercontent.com/2742474/62556968-526c6d00-b876-11e9-9b95-a94ec8e5bbb3.png)

Would anyone be able to help me fix this? I believe this could actually be a very convenient feature for other academics who primarily follow RSS feeds to stay up-to-date wrt. newly published articles. So far FreshRSS is the best reader I could find.

One suggestion would be to let the user 'toggle' on or off whether the author information is printed under the title, similar to: `$topline_date = FreshRSS_Context::$user_conf->topline_date;`

@Frenzie  would you have any idea's?

**Comment by Frenzie** [comment]
@jkinable The visual effect you ultimately want is likely `text-overflow:ellipsis`, but that requires certain width restrictions. For a quick fix it should probably do the trick to stick a `white-space:wrap` on there.

> Not only is my 'hack' probably ugly since I know nothing about web-development

It's not too bad! :-) It may be slightly more semantically appropriate to use `<address class="author">The Author</address>` but the biggest problem from a maintenance perspective is that you used inline styles there. You could look up how classes work if you're interested but for the moment I'm out of time.

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/class

**Comment by jkinable** [comment]
@Frenzie I agree, adding a class would be more appropriate. I'll add the corresponding CSS code under `base-theme/template.css'. Also, adding white-space:normal fixed the issue with the dates being pushed away. The only issue remaining is that for the first 20 articles, my CSS code seems to be ignored or overwritten. See for instance this snippet where I snow articles 19,20,21,22:
![image](https://user-images.githubusercontent.com/2742474/62591337-93dd3680-b8cf-11e9-8dd1-e4958b8128e6.png)
Notice the difference between the author formatting in the first 2 and the last 2 articles (21,22). This has something to do with the fact that the "Number of articles per page" equals 20, i.e. the articles on the first page ignore my css. I'm not sure how to fix this.

Would it make sense to submit a PR once this has been resolved? I'm not sure who manages this repo.

**Comment by Frenzie** [comment]
@jkinable I don't know where that would come from. All modern browsers include decent development tools, so if you right click → inspect element you can see which styles apply and which are overridden.

**Comment by jkinable** [comment]
Fixed the issue. Apparently inline style is not allowed as it violates some CSP security directive. Simply creating a new style class in one of the css files fixed the issue.

**Comment by Frenzie** [comment]
Makes sense in principle, but what about the other lines where the inline styles did work? Allowed because they're added dynamically to the DOM through JS?

**Comment by jkinable** [comment]
This issue only occurred for the first X articles, where X is the number of
articles displayed on a single page (X is a configuration setting). When
using Chrome inspector, I got exactly X times the error "refused to apply
inline style because it violates the following content security policy
directive". I have absolutely no idea why this error does not occur for the
remaining articles. Might be a security flaw, or might have something to do
with the fact that the second batch of X articles is loaded later (lazy
loading)?

**Comment by marienfressinaud** [comment]
To answer

> Would it make sense to submit a PR once this has been resolved?

It seems to me that the "author" is useless most of the times and I would like to keep the entry headers as simple as possible, but I understand that it's useful in your case. To address the problem, I suggest to create an extension in a first time.

If you think it's doable for you to create a pull request on https://github.com/FreshRSS/Extensions, we'll be happy to accept it. But I can also create the extension for you if your code is accessible somewhere, I guess it will be faster for me than for you (it depends on your motivation to learn how to create extensions ^^)

**Comment by Frenzie** [comment]
@marienfressinaud It probably doesn't affect your opinion, but I think the proposal is for a disabled by default option around here:

![Screenshot_20190808_094716](https://user-images.githubusercontent.com/202757/62684860-d848ff00-b9c1-11e9-98d8-fd404b452ccf.png)

**Comment by marienfressinaud** [comment]
Well, that concerns another point that I want to discuss (but not in this ticket): I find the configuration panels are already overloaded with options, I'd like to simplify them ^^. But I also know that's a strength of FreshRSS to have this level of configuration and my opinion is not settled yet. To be clear on my position about a potential option: I'll accept a PR which add such option, but that's not the solution I would go with personally :)

**Comment by Alkarex** [comment]
Implemented in https://github.com/FreshRSS/FreshRSS/pull/2487
