### ISSUE TITLE
Cannot add feed

### ISSUE THREAD

**Issue by nicofrand** [FreshRSS/FreshRSS#2484]
Hi,

I can't add this feed whereas the W3C validator says it is ok: https://ghost.org/blog/rss/.

```
2019-08-08 08:33:21Unknown error for feed [https://ghost.org/blog/rss/]
2019-08-08 08:31:50A feed could not be found at `https://ghost.org/blog/rss/`; the status code is `200` and content-type is `text/plain; charset=UTF-8` [https://ghost.org/blog/rss/]
```

Adding `#force_feed` does not work.

How can I help?

**Comment by aledeg** [comment]
It appears that the feed is not recognized by SimplePie. I don't know if we can do something about it.

See [test results on SimplePie website](https://simplepie.org/demo/?feed=https%3A%2F%2Fghost.org%2Fblog%2Frss%2F)

**Comment by Frenzie** [comment]
It's not recognized because the mimetype is text/plain. Normally #force_feed should do the trick though.

**Comment by Frenzie** [comment]
Actually `https://ghost.org/blog/rss#force_feed` works for me?

**Comment by nicofrand** [comment]
I just tried again and it worked. I double checked the first time with `#force_feed` (even trying with and without end slash) but I guess I made a mistake anyway.

Really sorry about that, thank you for your time anyway.

**Comment by Alkarex** [comment]
Fixed by https://github.com/FreshRSS/FreshRSS/pull/2852
