### ISSUE TITLE
Read articles keep coming up

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#2485]
When I mark feed items as read (manually or in bulk) they keep appearing as unread upon next actualisations of feeds. Is there a way to exclude read articles from feeds ? Thanks

**Comment by Alkarex** [comment]
Hello,
Sorry for the delay. Please try this option under *reading*:
![image](https://user-images.githubusercontent.com/1008324/63499329-ef124a00-c4c7-11e9-92cf-b118567aa137.png)

This might depend on some concrete feeds. Can you share one example, which gives a problem?

**Comment by ghost** [comment]
Hi, 
This is already my default setting. 
Apparently I need to tick "Mark updated articles as unread" under each feed to disable read articles to appear. I guess this has something to do with the original feed format since it's a problem with all Google Blogger feeds for example.

**Comment by siSSSou** [comment]
Many feeds behave as described by lmjst.
"Mark updated articles as read" ("Marquer les articles mis à jour comme non-lus") n'améliore pas la situation.

One feed example : http://radiofrance-podcast.net/podcast09/rss_10078.xml

**Comment by Alkarex** [comment]
@siSSSou Just to be sure, you must *disable* that option.
When your articles are unread again, are the old articles suddenly marked as unread, or do you get new articles? If you get new articles, do they maybe have a new URL?
(I plan to make a new feature to automatically mark as read based on more powerful criteria, such as the same title than a recent article)

**Comment by siSSSou** [comment]
OK ! With that option disabled these feeds don't show as unread anymore !

> When your articles are unread again, are the old articles suddenly marked as unread, or do you get new articles? If you get new articles, do they maybe have a new URL?

Previously, when a feed was updated, all the articles of the feed were marked as unread. URLs were the same.
