### ISSUE TITLE
Modify default reading configuration options

### ISSUE THREAD

**Issue by jkinable** [FreshRSS/FreshRSS#2486]
Under Configuration->Reading, by default the following options are enabled:

- Hide categories & feeds with no unread articles
- Mark article as read while scrolling

Is there a way to disable these options by default for all my users, while still allowing them to enable these options whenever they like?

**Edit**: it seems you can modify `config-user.default.php` to implement this behavior. However, is this intended? For instance, `config.default.php` explicitly states that you are not supposed to edit `config.default.php` directly, but that you are supposed to edit`data/config.php` instead. Similarly, I would expect that one would have to edit `data/config-user.php` but there is no reference to such file in the code.

**Comment by jkinable** [comment]
Any suggestions?

**Comment by marienfressinaud** [comment]
Changing `config-user.default.php` would work, but you will lose your modifications next time you update FreshRSS so it's not recommended indeed. There is no mechanism to override these default values and I don't see any robust way to do it. The best you can do is to overwrite `config-user.default.php` in a plugin I think. Depending on how you update FreshRSS, it might cause you some problems though.

In my opinion, the configuration system is quite strange (I know it, I wrote it :sweat_smile:). I think we can improve it without having to rewrite it completely, and so, we could provide a mechanism to overwrite the default configuration. I'll probably do it in the future but it's not my priority for the moment.

**Comment by jkinable** [comment]
@marienfressinaud I took the liberty to implement support for a data/config-user.php configuration file. Let me know what you think.

Loosely related: is there  a particular reason why user data such as user names, password hashes, email addresses etc are stored in a file as opposed to a database table?

**Comment by marienfressinaud** [comment]
I wouldn't say there is a "particular" reason. It's more like historical, practical and "it works" reasons ^^

**Comment by marienfressinaud** [comment]
It is now merged in `dev` branch, thanks @jkinable! You'll probably have to make a modification to your installation by renaming your file in `data/config-user.custom.php`
