### ISSUE TITLE
Hiding article publication time

### ISSUE THREAD

**Issue by jkinable** [FreshRSS/FreshRSS#2488]
By default, FreshRSS prints a publication date and time for each article entry. I'd like to hide the time component to allow for longer titles. So instead of `August 8th, 2019 at 19:01` I'd like to simply print `August 8th, 2019`, thereby omitting ` at 19:01`.
In this context, the two relevant functions are:

1. In `lib_rss.php`:
```
function timestamptodate ($t, $hour = true) {
	$month = _t('gen.date.' . date('M', $t));
	if ($hour) {
		$date = _t('gen.date.format_date_hour', $month);
	} else {
		$date = _t('gen.date.format_date', $month);
	}

	return @date ($date, $t);
}
```
2. In `Entry.php`:
```
public function date($raw = false) {
    if ($raw) {
                return $this->date;
        } else {
                return timestamptodate($this->date);
        }
}
```

I could simply change `return timestamptodate($this->date);` into `return timestamptodate($this->date,display_publication_time);`, where `display_publication_time` is a boolean variable which the user could set to true or false. I'm however not sure where to add this boolean variable to the settings menu?

Note: in the current implementation of FreshRSS, the date/time format is almost literally hardcoded in the translation files. It would be cleaner to allow the user to specify a desired format e.g.: "DD/MM/YY at HH:MM:SS" or "MM/DD/YY" as part of the configuration, e.g.: https://code.tutsplus.com/tutorials/working-with-date-and-time-in-php--cms-31768

**Comment by Alkarex** [comment]
Indeed, that could be improved. While waiting for a better solution, the date/time column can also be hidden completely:
![image](https://user-images.githubusercontent.com/1008324/63147569-dce36800-bffe-11e9-9381-cd604792bbef.png)

**Comment by Alkarex** [comment]
I think this relates slightly to https://github.com/FreshRSS/FreshRSS/issues/2478 , i.e. allowing user to customise the format of the article top line

**Comment by aledeg** [comment]
@jkinable I think the DateFormat extension I wrote will solve your problem. Could you check it?
See https://github.com/aledeg/FreshRSS-extensions
