### ISSUE TITLE
Being realistic about documentation

### ISSUE THREAD

**Issue by marienfressinaud** [FreshRSS/FreshRSS#2491]
I open a ticket to discuss about documentation (and I created in the mean time a label to identify "discussion" tickets).

FreshRSS had poor documentation for years, and it went more evident to me since I didn't work on it for 3 years. Here's 3 ideas to improve the situation and that I had successfully applied to other projects:

- [x] keep English documentation only, we are not able to maintain French version in parallel (maybe except the "user" documentation?) and it's more difficult for non-French people to contribute (see https://github.com/FreshRSS/FreshRSS/pull/2584)
- [ ] remove the "blank" sections, there are a lot of "TODOs" and it's just discouraging ourselves
- [x] add a "[PR template](https://help.github.com/en/articles/creating-a-pull-request-template-for-your-repository)" containing a list of points to check before merging, including "Document changes" (here's [an example](https://github.com/lessy-community/lessy/blob/master/docs/pull_request_template.md))

I keep this list to 3 tasks since it's always difficult to engage ourselves to more, but feel free to suggest more ideas.

**Comment by marienfressinaud** [comment]
The first point was transformed into "improving our tools to help translating" (https://github.com/FreshRSS/FreshRSS/pull/2590) and, while I was a bit dubious at first, it works pretty well thanks to the work of @Frenzie, great job! :clap: 

I'll find time in the next days to work on the two other points :)

**Comment by math-GH** [comment]
@marienfressinaud @Frenzie @Alkarex 
How do we want proceed here?
Is this topic solved from your side? 

I like the current documentation. (A documentation is never 'complete', but it is growing)

**Comment by Frenzie** [comment]
I wasn't able to quite automate po4a at the time for CI (because I'd have had to compile the latest version every time, give or take some cache) but I'd close this ticket.

**Comment by Alkarex** [comment]
@Frenzie I have forgotten how to sync / update the po4a. Could you please refresh my memory and/or making the corresponding PR?

**Comment by Frenzie** [comment]
You can run update-translations.sh from the docs folder iirc but at the moment it'll require a fair bit of manual effort to fix up because they became out of sync again. (It looks like no one's bothered to do it when updating the translation :-) ).

You need at least 0.56.
