### ISSUE TITLE
blank page on sharing page

### ISSUE THREAD

**Issue by Tealk** [FreshRSS/FreshRSS#2509]
Hello,

if i go to the share settings page(/p/i/?c=configure&a=sharing) in the settings, i only get a blank page.
I don't see an error message (console, log, ...).

**Comment by Frenzie** [comment]
Do you have any sharing already set up?

**Comment by Tealk** [comment]
No, I have currently set up a Mastodon instance and just wanted to see if I can add it.

**Comment by marienfressinaud** [comment]
It's probably due to an adblocker. I had the same issue because the url contains "sharing" :/

**Comment by Tealk** [comment]
I didn't even think about it. Thank you!
uBlock blocked it

**Comment by aledeg** [comment]
I think we should modify something in the code base so it does not trigger adblocker. Or at least, document it.

**Comment by Frenzie** [comment]
Only some of those are "sharing", others are more saving/adding (e.g., Wallabag, Pocket, Pinboard). Perhaps something more generic like `integrations`?

**Comment by Tealk** [comment]
`integration` sounds good

**Comment by Frenzie** [comment]
And in any case what the URL says and what the text says doesn't need to be the same. `?c=configure&a=integration` will do just fine either way.

**Comment by Frenzie** [comment]
To put all info together, copying https://github.com/FreshRSS/FreshRSS/issues/2419#issuecomment-504958716 here.

> One addition: You can leave easylist:fanboy-addon/fanboy_social_general_block.txt active, but deactivate "sharing" for your domain where you installed FreshRSS. So your own installation is excluded from the block. To do so, the user must go to _uBlock Origin_ > _Options_ > _My Filters_ > Add a new line with:
`*sharing,domain=~yourdomain.com`

**Comment by aledeg** [comment]
So what do we do to address that? Do we document or do we change the url?

**Comment by Alkarex** [comment]
I think we should:
1) Try to catch such an error so that we do not show a white page
2) change the URL to something less problematic

**Comment by Frenzie** [comment]
But it's the page itself that's blocked? I suppose you could see if it loads through fetch or something…

**Comment by aledeg** [comment]
@Tealk Please have a look at #2643 to check if I covered the original problem. Thank you.

**Comment by Tealk** [comment]
I downloaded the latest dev branch but it's still called share?

![image](https://user-images.githubusercontent.com/12276250/68477827-4f429d80-0226-11ea-956a-d1fa88e47044.png)

**Comment by Frenzie** [comment]
#2643 isn't merged yet. If you want to download it from GH without using Git, I think this link should work:

https://github.com/aledeg/FreshRSS/archive/hotfix/sharing.zip

**Comment by Tealk** [comment]
Sorry I don't work with git that much, how can you solve that over there?

**Comment by Frenzie** [comment]
What I would do depends on exactly what it is I want to do, as there are many different roads to (roughly) the same result. Your most basic GitHub-centric approach to test a PR would be something like:

```bash
# Assumes you've got an upstream remote set up.
git fetch upstream pull/2643/head
git checkout FETCH_HEAD
```

But if you're collaborating with people like @aledeg a lot, it might be a good idea to set up their fork as a remote:

```
git remote add aledeg git@github.com:aledeg/FreshRSS.git
```

Then you can just quickly checkout their branch.

```
git checkout -b integration-test-thing
git pull aledeg hotfix/sharing
```
