### ISSUE TITLE
Frequent authentication errors when trying to access Google Reader API via Reeder

### ISSUE THREAD

**Issue by CR0CKER** [FreshRSS/FreshRSS#2513]
After initially logging in fine, I keep getting authentication errors later when trying to mark articles as read or sync my feeds via Reeder. Initial sync seems to work well, but later it doesn't. Are there known issues using Reeder with FreshRSS via Google Reader API or is there an additional setting I need to change in FreshRSS to make it work?

**Comment by Alkarex** [comment]
Hello,
I do not have anything Apple, so I cannot test, but I have not heard this problem.

Try to uncomment the following lines, and then show us some logs from `./FreshRSS/data/users/_/log_api.txt`:

https://github.com/FreshRSS/FreshRSS/blob/84f9311fd53f5fa58ae55986ece9bfa7dac455c1/p/api/fever.php#L60-L61

And also your corresponding Web server logs.

What is your setup? OS, PHP, Web server, FreshRSS version...

**Comment by CR0CKER** [comment]
Thanks, @Alkarex  -- here's a copy of the log. FreshRSS is the latest version. PHP 7.1.32, CentOS Linux, Apache web server. Thanks for looking into this!
[log_api.txt](https://github.com/FreshRSS/FreshRSS/files/3613344/log_api.txt)

**Comment by Alkarex** [comment]
@CR0CKER Hello,
I can see you get some `Invalid POST token` errors. Let's try to dig into that. Could you please add one line of debugging information?

Please add the following two lines:

```php
	Minz_Log::warning('POST token should have been: ' . str_pad(sha1(FreshRSS_Context::$system_conf->salt . $user . $conf->apiPasswordHash), 57, 'Z'), API_LOG);
	Minz_Log::warning('For user: ' . $user, API_LOG);
```

just after that line:
https://github.com/FreshRSS/FreshRSS/blob/dev/p/api/greader.php#L223

and just before the `unauthorized();`

**Comment by CR0CKER** [comment]
Here's the result of a failed authorization:
[log.txt](https://github.com/FreshRSS/FreshRSS/files/3618760/log.txt)

**Comment by Alkarex** [comment]
It looks like you have edited the line `Invalid POST token: x`, haven't you? How was the format, and how does it compare to the second line `POST token should have been` ?

**Comment by Alkarex** [comment]
@CR0CKER If you did not yourself changed to `x` in the logs, then Reeder is doing it wrong, but I can provide a compatibility fix

**Comment by CR0CKER** [comment]
No, I haven't changed that line -- it was exactly like this:
[Tue, 17 Sep 2019 15:04:35 +0200] [warning] --- Invalid POST token: x
[Tue, 17 Sep 2019 15:04:35 +0200] [warning] --- POST token should have been: 92ddc58493b5676bfd9d7eb6bb320ec49724e444ZZZZZZZZZZZZZZZZZ

What should it look like instead? Would be great if you could fix the issue. I've also emailed the Reeder author about this, but never received a response :-/

**Comment by Alkarex** [comment]
Allright. Could you please try this potential fix? https://github.com/FreshRSS/FreshRSS/pull/2526 @CR0CKER

**Comment by CR0CKER** [comment]
Sorry, I don't have Git installed. Could you provide me with a binary?

**Comment by Alkarex** [comment]
I think the easiest then is just to replace your file `./FreshRSS/p/api/greader.php` with this one:
https://raw.githubusercontent.com/FreshRSS/FreshRSS/4fe4415f1f3dbab1148e754bed9e47e58255b806/p/api/greader.php

**Comment by CR0CKER** [comment]
Awesome, that seems to have fixed it. Will report back if the issue occurs again. Thanks for the quick fix!

**Comment by Alkarex** [comment]
Thanks for the feedback. Merged in dev

**Comment by Alkarex** [comment]
Just for the record, `T=x` sent by Reeder is wrong. At best it should send the same token it received earlier, and at worst send no token or empty token, but just not a random value such as `x `
