### ISSUE TITLE
Configuring default feeds

### ISSUE THREAD

**Issue by marienfressinaud** [FreshRSS/FreshRSS#2514]
I'd like to allow admins to configure the default feeds. The feeds will be defined in the `data/config.php` file instead of the `app/SQL/install.sql.*.php` files (`SQL_INSERT_FEEDS`).

It's pretty straightforward to implement:

- [x] transform MySQL instructions to work with an array instead of a single SQL string in order to homogenize the code between databases (see [this lines](https://github.com/FreshRSS/FreshRSS/blob/1.14.3/app/Models/UserDAO.php#L32-L47))
- [x] move actual default feeds from the SQL string to the default configuration
  - transform `SQL_INSERT_FEEDS` into a single string which accept `url`, `name`, `website` and `description` "arguments"
  - add a `default_feeds` array to the system configuration
  - iterate on `default_feeds` instead of the `$SQL_INSERT_FEEDS` instructions in the`userDAO->createUser` method
- [x] remove the FRSS website feed since it's now a redirection to the GitHub releases feed
- [x] update the install script

I don't plan to let admins to configure these feeds from the interface yet.

If you see more default feeds to add by default, feel free to suggest them!

References:
- initial feature suggestion: https://github.com/FreshRSS/FreshRSS/issues/859
- FRSS website feed redirection: https://github.com/FreshRSS/freshrss.org/issues/38

**Comment by Frenzie** [comment]
> If you see more default feeds to add by default, feel free to suggest them!

My personal bias would suggest xkcd.

A popular category is news feeds. I don't really see the point of that myself too much. Fwiw, popular default feeds seem to be Ars Technica and Engadget.

One that could be interesting is http://waitbutwhy.com/feed (This is the kind of infrequently updated website that feeds exist for, imo.)

But of course you wouldn't want to overdo it.

**Comment by marienfressinaud** [comment]
Ah, I had something more related to FRSS in mind, which could be directly useful to our users. I think xkcd and news feeds are too "subjective" and we would face a language problem for a lot of users (but we can argue that we actually face it with the FRSS release feed). Not to say that we must not add these feeds (if we think it's pertinent) but my personal opinion is that we should choose something more "neutral".

By the way, I have some other plans to enhance user experience and how to get started at the first use (but it's too fresh in my mind and not yet in my priorities :))

**Comment by Frenzie** [comment]
I realize you're putting scare quotes around the words, but I'm not really sure what you're driving at. I explicitly intended those as generic/neutral suggestions. The value is just to see the program in a fully functional state without having to add feeds, assuming that's a positive thing.

Here's the "The Old Reader" selection:
![Screenshot_2019-09-03_16-19-15](https://user-images.githubusercontent.com/202757/64181369-a0b95f80-ce66-11e9-82bf-d7be1517d52c.png)

**Comment by Alkarex** [comment]
Actually, I believe that giving the option of loading a default OPML might be easiest

**Comment by Alkarex** [comment]
(More later, I am on my way)

**Comment by marienfressinaud** [comment]
> I realize you're putting scare quotes around the words, but I'm not really sure what you're driving at. I explicitly intended those as generic/neutral suggestions.

I used quotes because I think nothing is totally neutral, I didn't want to imply anything more ^^ Your example of "The Old Reader" is a good one because I think I would remove all of them from my subscription list; not because there are bad choices (I know almost none of them), but because it doesn't match with what I usually follow in FRSS. I would avoid the case where the first thing that new users want to do is to unsubscribe from all the default feeds ^^'

Still, I'm not opposed to your suggestions, especially since I realized our current users are very likely people interested in technology, so Ars Technica and Engadget make sense; xkcd to add a touch of humor (even if I find it hard to understand sometimes ;)). I'm not sure about "Wait But Why" though.

> The value is just to see the program in a fully functional state without having to add feeds, assuming that's a positive thing.

I totally agree on this but for me it wasn't the goal of this ticket. Just to give an idea of what I would implement later to enhance the situation: I'd like to allow people to create and share lists of feeds (as OPML files) by topics (politics, sport, digital, etc.). Then we could add the possibility to search and subscribe to these OPML files. So the first thing we could ask to users is "what are your interests?" and present these community suggestions, based on their answers.

It implies a lot of things and it's not the point of this ticket, so I can open another one to discuss it (but the idea is still a bit vague). It's just to let you know that I'm also concerned by the default state of FRSS but I planed to address it in another ticket :)

**Comment by Frenzie** [comment]
I'd also remove them all except for *What If?*. It's not even a matter of whether I would read them, but anything that fills up my feeds with so many entries daily would be on the immediate shortlist for removal. To me *What If?* and *Wait But Why* are the kind of update frequencies that make sense. ;-)
