### ISSUE TITLE
Internet connection problem

### ISSUE THREAD

**Issue by BSP-rainbow** [FreshRSS/FreshRSS#2521]
Hello, 

i a have already for a while a strange problem, when i press the refresh button i get the error:
"A request failed. It may have been caused by internet connection problems".

I did update FreshRSS, and i did reinstall it, nothing helps.

When i do a "Actualize" on the left site for  each subscription there is no problem, the subscription is updating, no error.

When i like to make a article favorite i also get a Internet connection failure...

Can someone help me what the problem is and how to solve the problem?

Working with FreshRSS is 1.14.3.
External server provider.
PHP version is 7.2.15
Installation checking is telling me everything is green/good.

Thanks for helping me.

**Comment by Frenzie** [comment]
Any adblockers/scriptblockers in the browser perhaps?

**Comment by BSP-rainbow** [comment]
> 
> 
> Any adblockers/scriptblockers in the browser perhaps?

Thanks for your help, but that didn't help by turning the blockers of, stil the same error.
I did also other browsers: Opera, Chrome, Firefox, all the same error...

**Comment by Frenzie** [comment]
Did you check the logs?

**Comment by BSP-rainbow** [comment]
> 
> 
> Did you check the logs?

Yes i did,
i see only sometimes a feed having no connection, but that is already a while ago... and did fix by itself..
Nothing about the internet error...

**Comment by Alkarex** [comment]
Please look at your Web browser logs as well

**Comment by BSP-rainbow** [comment]
> 
> 
> Please look at your Web browser logs as well

I have it in all my browsers and did try other computers, same result.
so i don't believe it's a browser problem.. there is something wrong in the installation with FreshRSS, but also reinstall didn't solve the problem....

**Comment by Frenzie** [comment]
The browser logs might offer more information about the precise error.

**Comment by BSP-rainbow** [comment]
> 
> 
> The browser logs might offer more information about the precise error.

Oke, when i have time i will look for it, thanks

**Comment by Alkarex** [comment]
Just in case it is needed, here is how: https://developer.mozilla.org/docs/Tools/Web_Console/Opening_the_Web_Console

**Comment by metbril** [comment]
Same error over here. The console shows this:

![image](https://user-images.githubusercontent.com/559346/153217704-59181758-d15a-4e5d-900d-36f316cab046.png)


![image](https://user-images.githubusercontent.com/559346/153217512-ff87c764-ff80-4de2-a668-bcf908472d66.png)

![image](https://user-images.githubusercontent.com/559346/153217920-7435fc37-f6a1-4bb1-96fc-fa3cb6fd7f55.png)

**Comment by Alkarex** [comment]
@metbril FreshRSS does not return 501 by itself (except in the APIs) so it is probably a problem at the Web server level. It looks like it is running nginx, which is very error prone, and it could be a configuration problem. More logs would be needed (e.g. of the Web server and FreshRSS). (Unrelated, but you are not supposed to expose the `/p/` in the public path; the root is supposed to be **inside** this `/p/` folder, so your public address looks like `https://feeds.example.net/i/`). Please provide the usual information such as how you installed FreshRSS, which platform, versions, etc. You could also consider deploying using our official Docker image, which ensures a good configuration of FreshRSS.

**Comment by metbril** [comment]
> you are not supposed to expose the /p/ in the public path; the root is supposed to be inside this /p/ folder, so your public address looks like https://feeds.example.net/i/

> how you installed FreshRSS

It's running PHP 7.4

FreshRSS version 1.19.2.


I installed FreshRSS through my hosting provider using Softaculous, so I don't have much control over that.

The installation checks are all green:

```
Installatiecontrole
PHP installatie
Uw PHP versie is 7.4.22, welke compatibel is met FreshRSS.

U hebt de cURL uitbreiding.

U hebt PDO en ten minste één van de ondersteunde drivers (pdo_mysql, pdo_sqlite, pdo_pgsql).

U hebt de benodigde bibliotheek voor regular expressions (PCRE).

U hebt de benodigde bibliotheek voor character type checking (ctype).

U hebt de fileinfo uitbreiding.

U hebt de benodigde bibliotheek voor het bladeren van DOM.

U hebt JSON uitbreiding.

De voor Unicode aanbevolen bibliotheek mbstring is gevonden.

U hebt ZIP uitbreiding.

Bestanden installatie
Permissies op de data map zijn in orde.

Permissies van de cache map zijn goed.

Permissies op de users map zijn goed.

Permissies op de favicons map zijn goed.

Permissies op de tokens map zijn goed.
```

**Comment by metbril** [comment]
I can confirm that pasting the link from the refresh button in the browser **does** work.

https://feeds.robertvanbregt.nl/p/i/?c=feed&a=actualize

This does refresh the feeds. The error message is shown **the first time it's clicked** only.

**Comment by metbril** [comment]
I've done some more testing and the same is happening (for me) when I try to star an item or mark as read through the icons at the start of a row.

Clicking an icon will show the error. The link behind the icon (right click, open in new tab) DOES work, however.

Tested with Safari for Mac, iPad and iPhone and Firefox for Mac.

**Comment by metbril** [comment]
```
XHRPOSThttps://feeds.robertvanbregt.nl/p/i/?c=entry&a=bookmark&id=1644603001638318
[HTTP/2 501 Not Implemented 25ms]

	
POST
	
scheme
	https
host
	feeds.robertvanbregt.nl
filename
	/p/i/
c
	entry
a
	bookmark
id
	1644603001638318
Adres
	84.241.177.137:443
Status
501
Not Implemented
VersieHTTP/2
Overgebracht378 B (grootte 196 B)
Referrer-beleidno-referrer

    	
    allow
    	TRACE
    content-length
    	196
    content-type
    	text/html; charset=iso-8859-1
    date
    	Fri, 11 Feb 2022 18:53:03 GMT
    server
    	nginx
    X-Firefox-Spdy
    	h2
    	
    Accept
    	*/*
    Accept-Encoding
    	gzip, deflate, br
    Accept-Language
    	nl,en;q=0.5
    Connection
    	keep-alive
    Content-Length
    	64
    Content-Type
    	application/json
    Cookie
    	FreshRSS=18af0535e3d17e0d8437c4d0067fce3e
    DNT
    	1
    Host
    	feeds.robertvanbregt.nl
    Origin
    	https://feeds.robertvanbregt.nl
    Sec-Fetch-Dest
    	empty
    Sec-Fetch-Mode
    	cors
    Sec-Fetch-Site
    	same-origin
    Sec-GPC
    	1
    TE
    	trailers
    User-Agent
    	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:97.0) Gecko/20100101 Firefox/97.0
```

**Comment by metbril** [comment]
**Request**

```
XHRPOSThttps://feeds.robertvanbregt.nl/p/i/?c=javascript&a=actualize
[HTTP/2 501 Not Implemented 23ms]

JSON	
_csrf	"32862220773524795b0715ec1b314e2095******"
```

**Answer**

```
Not Implemented

POST to /p/i/ not supported.
```

<img width="615" alt="Schermafbeelding 2022-02-11 om 20 02 01" src="https://user-images.githubusercontent.com/559346/153653385-35d5f085-7a87-4696-9ab3-692f75c6562d.png">

<img width="598" alt="Schermafbeelding 2022-02-11 om 20 03 15" src="https://user-images.githubusercontent.com/559346/153653526-84f5c6d7-5d7d-456c-9f19-db6315d17cc8.png">

**Comment by metbril** [comment]
Web server error log

```
[Fri Feb 11 19:44:51.966415 2022] [:error] [pid 77529] [client 83.86.210.134:56478] [client 83.86.210.134] ModSecurity: Access denied with code 501 (phase 2). Match of "rx (?:^(?:application\\\\/x-www-form-urlencoded(?:;(?:\\\\s?charset\\\\s?=\\\\s?[\\\\w\\\\d\\\\-]{1,18})?)??$|multipart/form-data;)|text/xml)" against "REQUEST_HEADERS:content-type" required. [file "/etc/httpd/modsecurity.d/modsecurity_crs_30_http_policy.conf"] [line "69"] [id "960010"] [msg "Request content type is not allowed by policy"] [severity "WARNING"] [tag "POLICY/ENCODING_NOT_ALLOWED"] [hostname "feeds.robertvanbregt.nl"] [uri "/p/i/"] [unique_id "Ygauo5O20oFZnvXM@Um-1gAAAAc"]
[Fri Feb 11 19:44:52.987319 2022] [:error] [pid 102032] [client 83.86.210.134:56484] [client 83.86.210.134] ModSecurity: Access denied with code 501 (phase 2). Match of "rx (?:^(?:application\\\\/x-www-form-urlencoded(?:;(?:\\\\s?charset\\\\s?=\\\\s?[\\\\w\\\\d\\\\-]{1,18})?)??$|multipart/form-data;)|text/xml)" against "REQUEST_HEADERS:content-type" required. [file "/etc/httpd/modsecurity.d/modsecurity_crs_30_http_policy.conf"] [line "69"] [id "960010"] [msg "Request content type is not allowed by policy"] [severity "WARNING"] [tag "POLICY/ENCODING_NOT_ALLOWED"] [hostname "feeds.robertvanbregt.nl"] [uri "/p/i/"] [unique_id "YgaupEPImYxM@DWmjxS4SgAAAAM"]
```

**Comment by Frenzie** [comment]
> ModSecurity: Access denied with code 501

Well, there's your answer. Cf. `https://github.com/coreruleset/coreruleset/issues/1056`. Any way to see which version it is?

**Comment by metbril** [comment]
Which version of what @Frenzie ? FreshRSS, nginx, something else?

**Comment by Frenzie** [comment]
I meant ModSecurity, but the more the merrier. ;-)

**Comment by metbril** [comment]
My hosting provider changed a ModSecurity setting, so my issue is resolved. Not sure if this applies to OP as well.
