### ISSUE TITLE
<content> tag not show

### ISSUE THREAD

**Issue by hrehfeld** [FreshRSS/FreshRSS#2523]
This feed: https://therealmjp.github.io/posts/index.xml only shows the descriptions in the freshrss ui, even though I usually see "full text".

```
<item>
<title>Hello, Hugo</title>
<link>https://therealmjp.github.io/posts/hello-hugo/</link>
<pubDate>Mon, 12 Aug 2019 00:00:00 +0000</pubDate>
<guid>https://therealmjp.github.io/posts/hello-hugo/</guid>
<description>
For the past 11(!) years I&rsquo;ve hosted my blog on wordpress.com, which had a very low barrier to entry. But for a year or two now I&rsquo;ve been itching to move on to something that I actually enjoy working with, and that doesn&rsquo;t leave me locked in to the WordPress platform and hosting services. Over the past two weeks or so I&rsquo;ve been working on setting up this new blog, which is hosted on GitHub pages and is generated as a static site using Hugo.
</description>
<content type="html">
<![CDATA[
<p><img src="/images/hello-hugo/hugo-logo-wide.svg" alt="Hugo logo" /></p> <p>For the past 11(!) years I&rsquo;ve hosted my <a href="https://mynameismjp.wordpress.com/">blog</a> on wordpress.com, which had a very low barrier to entry. But for a year or two now I&rsquo;ve been itching to move on to something that I actual...
```

Not sure what's expected behavior or what the RSS spec says here, but it's annoying. ;-) I could imagine that the feed author  @TheRealMJP would be open to site fixes if this actually violates spec.

**Comment by Frenzie** [comment]
That looks like RSS with Atom. Otoh `<content type="something">` is Atom and `<content:encoded>` is RSS 2.

Edit: confirmed by validator https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Ftherealmjp.github.io%2Fposts%2Findex.xml

**Comment by hrehfeld** [comment]
ping @TheRealMJP can you fix this so I can read fulltext in my rss reader? ;-)

**Comment by TheRealMJP** [comment]
@hrehfeld looks like the RSS template in my Hugo theme wasn't setup correctly. I changed it to use `<content:encoded>` and it now passes the validator, and the full content displays correctly for me in Feedly. Thanks for pointing that out!

**Comment by hrehfeld** [comment]
Awesome, thanks!
