### ISSUE TITLE
Discussion forum or chat

### ISSUE THREAD

**Issue by squromiv** [FreshRSS/FreshRSS#2525]
I think, that users need discussion forum or chat about Fresh RSS for some reasons:
1)  Many issues on Github  are generated as questions by newbies. So users must have more flexible and quick way to know something new about FreshRSS and to discuss it.
2) It also will be helpfull for developers, because Github is not the best place to discuss insignificant features.

So it can be forum on site freshrss.org or any other platform. As an example - telegram group like https://t.me/rsshub   (one of the projects on Githhub). 
Does anybody have any ideas or preferences about this theme?

**Comment by Frenzie** [comment]
It can be found a bit out of the way [here](https://github.com/FreshRSS/FreshRSS/blob/44bd07e506ade204151c276fdc05994d51efdd7a/CONTRIBUTING.md#chat-with-us). That page includes a link to https://framateam.org/freshrss/channels/town-square

I'd propose to feature it a little more prominently, see for example how the [KOReader README](https://github.com/koreader/koreader#koreader-is-a-document-viewer-primarily-aimed-at-e-ink-readers) includes a "chat on gitter" button.

![Screenshot_2019-09-16_17-10-50](https://user-images.githubusercontent.com/202757/64969828-f1887980-d8a4-11e9-92d2-8794311a2c9e.png)

PS Contributing.md is shown as a "helpful resource" when opening a new issue (see the bottom right).

![Screenshot_2019-09-16_17-13-43](https://user-images.githubusercontent.com/202757/64970092-6f4c8500-d8a5-11e9-9c1d-ce0fb8bd3207.png)

**Comment by squromiv** [comment]
> It can be found a bit out of the way [here](https://github.com/FreshRSS/FreshRSS/blob/44bd07e506ade204151c276fdc05994d51efdd7a/CONTRIBUTING.md#chat-with-us). That page includes a link to https://framateam.org/freshrss/channels/town-square

Hm, it is really not so easy for ordinary user to find it. And does this service have any language exept french?

**Comment by Frenzie** [comment]
> Hm, it is really not so easy for ordinary user to find it.

I thought that's what my whole message was about? ;-)

> And does this service have any language exept french?

The language can be set in Paramètres du compte → Affichage (Account settings → Display).

You can additionally use it with any app that supports Mattermost:
https://mattermost.com/download/#mattermostApps

**Comment by squromiv** [comment]
@Frenzie 
Ok. Not the easiest way, but thanks for help.
This method of communication should be added on the main page of FreshRSS project. imho.

**Comment by RichardUUU** [comment]
Why not reddit?

**Comment by marienfressinaud** [comment]
I personally don't use Reddit but I don't mind to add a link to it if there are enough people to provide support on this platform (and I don't know if there's any core-contributor that uses Reddit)

**Comment by Frenzie** [comment]
@marienfressinaud I have an account to which I log in [about once a year](https://www.reddit.com/r/Trackballs/comments/ep1t8m/anyone_getting_the_kensington_pro_fit_ergo/fejc1ao/). (That specific reply was due to https://github.com/FreshRSS/FreshRSS/issues/2770.)

**Comment by RichardUUU** [comment]
Here you go: [https://www.reddit.com/r/freshrss/](https://www.reddit.com/r/freshrss/)

I've noticed a lot of google searches now suggest reddit, and most reddit communities seem helpful e.g. elementor.

Cheers, Richard

**Comment by aledeg** [comment]
If you want the [RSS feed](https://www.reddit.com/r/freshrss/.rss)!

**Comment by math-GH** [comment]
How to discuss or ask question around FreshRSS:
- GitHub: 
  - "issues" section (mainly for feature requests and bug reports)
  - "discussion" section (mainly for questions.)
  - do not be afraid to chose the "wrong" sections. We can move it from one section to another
- Framateam (https://framateam.org/freshrss/channels/town-square?id=e2680d3e3128b9fac8fdb3003b0024ee) here you can chat with the developers

not official subborted, but there is supporting FreshRSS community out there:
- Redit https://www.reddit.com/r/freshrss/
- Mastodon: use the hashtag #freshRSS
