### ISSUE TITLE
No image ? No tags transmitted to Walla ?

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#2532]
I wonder if it's normal or not to have a blank area on page  /?do=picwall
where, I suppose, some thumbnails should be displayed below "Picture Wall - 69 pics" ?

Also I've set up the plugin to share links to my WALLABAG_VERSION · Wallabag API version 2
It works fine except that the Shaarli tags are not transmitted to Wallabag. 

Sorry if my questions are not relevant, I'm quite new here.

Thanks

**Comment by Frenzie** [comment]
I'm not sure where this Picture Wall extension is located?

The Wallabag URL sharing only adds the URL to Wallabag afaik, unless you're talking about something else.

**Comment by math-GH** [comment]
Does it make sense to keep this ticket open?
