### ISSUE TITLE
Unable to add PHPBB Atom feeds

### ISSUE THREAD

**Issue by vonv** [FreshRSS/FreshRSS#2537]
https://www.jdrvirtuel.com/app.php/feed/forum/278

Message:
cURL error 28: Connection timed out after 15000 milliseconds [https://www.jdrvirtuel.com/app.php/feed/forum/278]

**Comment by Alkarex** [comment]
It looks like they are doing some IP filtering. I have tried the following command from two different servers: my home test works, my test from OVH returns a 403 error.

```sh
curl -v 'https://www.jdrvirtuel.com/app.php/feed/forum/278'
```

**Comment by vonv** [comment]
Ok, thank you very much ! I will try something else...
