### ISSUE TITLE
request: share feeds

### ISSUE THREAD

**Issue by yanivz** [FreshRSS/FreshRSS#2538]
I like to have an option to aggregate feed and share them as one mixed RSS feed

**Comment by Alkarex** [comment]
Hello,
One can already do that in FreshRSS. You can re-share a RSS of any view of FreshRSS, e.g. a category, a search, etc.

**Comment by yanivz** [comment]
How?

**Comment by Alkarex** [comment]
Look for this button in your FreshRSS toolbar
![image](https://user-images.githubusercontent.com/1008324/65808110-8c7d2f80-e192-11e9-9107-161d60b09f9f.png)
You might have to define a token in your profile

**Comment by yanivz** [comment]
i saw this its says download rss while i looking to embed this link, also the rss look like nothing i've seen 
https://ibb.co/p0gT0X1 -  what i expect
https://ibb.co/7JqB8YL - what i get now

also when embedding the link in my site i saw the error 
__XML Parsing Error: mismatched tag. Expected: </meta>.
Location: https://www.avren.co.il/get_rss_feed.php?object=sys_page_block&id=1878&member=0
Line Number 22, Column 3:</head>
--^__

**Comment by Frenzie** [comment]
What specifically is the difference between what you see and what you expect? I just see two XML documents. ;-)

I can't see the source of the syntax error on my phone. It could be useful to embed part of the XML in your message.

**Comment by yanivz** [comment]
expected rss:
This XML file does not appear to have any style information associated with it. The document tree is shown below.
        <rss version="2.0"><channel><title>ynet - מבזקים</title><link>http://www.ynet.co.il</link><description>עדכוני SMS ישירות מחדר החדשות של ynet. שילחו את המילים ''התחל חדשות'' למספר 5335 וקבלו 4 עדכוני SMS ביום. השירות בתשלום.</description><copyright>Ynet - news and content from Israel (Yedioth Ahronoth web site)</copyright><language>he</language><pubDate>Sat, 28 Sep 2019 12:27:39 +0200</pubDate><lastBuildDate>Sat, 28 Sep 2019 12:27:39 +0200</lastBuildDate><image><title>Ynet</title><link>http://www.ynet.co.il/home/0,7340,L-1854,00.html</link><url>http://www.ynet.co.il/images/CENTRAL_logo.gif</url></image><item><category>מבזקים</category><title></title><description/><link>http://www.ynet.co.il/articles/0,7340,L-5598867,00.html</link><pubDate>Sat, 28 Sep 2019 11:26:46 +0200</pubDate><guid>http://www.ynet.co.il/articles/0,7340,L-5598867,00.html</guid></item><item><category>מבזקים</category><title>צעיר נפצע קשה מירי באזור עומר</title><description/><link>http://www.ynet.co.il/articles/0,7340,L-5598865,00.html</link><pubDate>Sat, 28 Sep 2019 11:07:29 +0200</pubDate><guid>http://www.ynet.co.il/articles/0,7340,L-5598865,00.html</guid></item><item><category>מבזקים</category><title>פעולות החייאה בגבר שטבע בחוף אלמוג באילת</title><description/><link>http://www.ynet.co.il/articles/0,7340,L-5598848,00.html</link><pubDate>Sat, 28 Sep 2019 10:33:58 +0200</pubDate><guid>http://www.ynet.co.il/articles/0,7340,L-5598848,00.html</guid></item><item><category>מבזקים</category><title>מצרים: חיסלנו 118 מחבלים בכמה מבצעים צבאיים בסיני</title><description/><link>http://www.ynet.co.il/articles/0,7340,L-5598825,00.html</link><pubDate>Sat, 28 Sep 2019 09:56:02 +0200</pubDate><guid>http://www.ynet.co.il/articles/0,7340,L-5598825,00.html</guid></item><item><category>מבזקים</category><title>דרום קוריאה: תשעה פצועים בשריפה במכלית נפט</title><description/><link>http://www.ynet.co.il/articles/0,7340,L-5598807,00.html</link><pubDate>Sat, 28 Sep 2019 08:59:20 +0200</pubDate><guid>http://www.ynet.co.il/articles/0,7340,L-5598807,00.html</guid></item><item><category>מבזקים</category><title>שלושה פצועים בפיצוץ שארע סמוך לקלפי בחירות בדרום אפגניסטן</title><description/><link>http://www.ynet.co.il/articles/0,7340,L-5598786,00.html</link><pubDate>Sat, 28 Sep 2019 07:52:53 +0200</pubDate><guid>http://www.ynet.co.il/articles/0,7340,L-5598786,00.html</guid></item><item><category>מבזקים</category><title>התחזית: ירידה בטמפרטורות</title><description/><link>http://www.ynet.co.il/articles/0,7340,L-5598764,00.html</link><pubDate>Sat, 28 Sep 2019 06:48:42 +0200</pubDate><guid>http://www.ynet.co.il/articles/0,7340,L-5598764,00.html</guid></item><item><category>מבזקים</category><title>אפגניסטן: החלה ההצבעה לנשיאות המדינה תחת אבטחה כבדה</title><description/><link>http://www.ynet.co.il/articles/0,7340,L-5598746,00.html</link><pubDate>Sat, 28 Sep 2019 05:56:01 +0200</pubDate><guid>http://www.ynet.co.il/articles/0,7340,L-5598746,00.html</guid></item><item><category>מבזקים</category><title>דיווח: "טראמפ אמר לרוסים - לא מודאג מהתערבות בבחירות, עשינו זאת בעבר"</title><description/><link>http://www.ynet.co.il/articles/0,7340,L-5598745,00.html</link><pubDate>Sat, 28 Sep 2019 05:33:54 +0200</pubDate><guid>http://www.ynet.co.il/articles/0,7340,L-5598745,00.html</guid></item><item><category>מבזקים</category><title>גורם רשמי בארה"ב מאשר: "השליח לאוקראינה התפטר בצל פרשת טראמפ"</title><description/><link>http://www.ynet.co.il/articles/0,7340,L-5598725,00.html</link><pubDate>Sat, 28 Sep 2019 04:32:20 +0200</pubDate><guid>http://www.ynet.co.il/articles/0,7340,L-5598725,00.html</guid></item></channel></rss>

**Comment by yanivz** [comment]
1. expected rss will look like this: http://www.ynet.co.il/Integration/StoryRss1854.xml
2. what i get: https://send.firefox.com/download/d7b426de0e62f93a/#GpYrn5FH-_p_UxRbtY0oKA
my site can't parse the 2nd and gets the error

**Comment by Frenzie** [comment]
That file you shared randomly ends. (Which, if it came from the server like that, would certainly be a problem.)

**Comment by yanivz** [comment]
it's looks like a bug

**Comment by Frenzie** [comment]
> also when embedding the link in my site i saw the error
XML Parsing Error: mismatched tag. Expected: .
Location: https://www.avren.co.il/get_rss_feed.php?object=sys_page_block&id=1878&member=0
Line Number 22, Column 3:

Note that while I couldn't see it on my phone, there's no XML on the linked page but a note that the page can't be found. Are you using the right URL?

> it's looks like a bug

Nothing but a bug between keyboard & monitor, or rather in trying to deal with copy/paste on a phone, which was probably a stupid idea but I figured I could spare a couple of minutes on the train. The document didn't end and it is well-formed.

**Comment by yanivz** [comment]
i dont understand u, why u cant wait to get home and see it on pc?! i use tiny tiny rss for this purpose and it was fine, the same idea aggregate some feed and post it as one rss. here i getting frustrated becouse i cant get a proper rss.

**Comment by Frenzie** [comment]
> i dont understand u, why u cant wait to get home and see it on pc?!

I was trying to be helpful. All I need is XML, not a PC. To be clear, this is what I asked for, the source behind the XML parsing error on https://www.avren.co.il/get_rss_feed.php?object=sys_page_block&id=1878&member=0

```html
<!DOCTYPE html>
<html lang="en" xml:lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="initial-scale=1.0" />
<script src="/cdn-cgi/apps/head/TCqZq-_W1-rgILVPtZy8JPzMdAg.js"></script><link rel="stylesheet" href="../themes/base-theme/template.css?1569521050" />
<link rel="stylesheet" href="../themes/Origine/origine.css?1569521050" />
<script id="jsonVars" type="application/json">
{"context":{"anonymous":true,"auto_remove_article":false,"hide_posts":true,"display_order":"DESC","auto_mark_article":true,"auto_mark_site":true,"auto_mark_scroll":true,"auto_load_more":true,"auto_actualize_feeds":false,"does_lazyload":true,"sides_close_article":true,"sticky_post":true,"html5_notif_timeout":0,"auth_type":"form","current_view":"index","csrf":"e9d8304f18ffc976b92b201473bf934d8de24a83"},"shortcuts":{"mark_read":"r","mark_favorite":"f","go_website":"Space","prev_entry":"k","next_entry":"j","skip_prev_entry":"p","skip_next_entry":"n","first_entry":"Home","last_entry":"End","collapse_entry":"c","load_more":"m","auto_share":"s","focus_search":"a","user_filter":"u","help":"F1","close_dropdown":"Escape","normal_view":"1","global_view":"2","reading_view":"3","rss_view":"4"},"urls":{"index":".\/","login":".\/?c=auth&amp;a=login","logout":".\/?c=auth&amp;a=logout","help":"https:\/\/freshrss.github.io\/FreshRSS\/"},"i18n":{"confirmation_default":"Are you sure you want to perform this action? It cannot be cancelled!","notif_title_articles":"FreshRSS: new articles!","notif_body_articles":"There are %d new articles to read on FreshRSS.","notif_request_failed":"A request has failed, it may have been caused by Internet connection problems.","category_empty":"Empty category"},"icons":{"read":"%3Cimg%20class%3D%22icon%22%20src%3D%22..%2Fthemes%2Ficons%2Fread.svg%22%20alt%3D%22%E2%98%91%22%20%2F%3E","unread":"%3Cimg%20class%3D%22icon%22%20src%3D%22..%2Fthemes%2Ficons%2Funread.svg%22%20alt%3D%22%E2%98%90%22%20%2F%3E"}}		</script>
<script src="../scripts/main.js?1569521050" defer="defer" async="async"></script>
<script src="../scripts/extra.js?1569521050" defer="defer" async="async"></script>
<link rel="shortcut icon" id="favicon" type="image/x-icon" sizes="16x16 64x64" href="../favicon.ico" />
<link rel="icon msapplication-TileImage apple-touch-icon" type="image/png" sizes="256x256" href="../themes/icons/favicon-256.png" />
<link rel="apple-touch-icon" href="../themes/icons/apple-touch-icon.png" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
<meta name="apple-mobile-web-app-title" content="FreshRSS">
<meta name="msapplication-TileColor" content="#FFF" />
<meta name="referrer" content="never" />
<title>Error 404 - Not found · FreshRSS</title>
<meta name="robots" content="noindex,nofollow" />
</head>
<body class="index">
<ul class="nav nav-head nav-login"><li class="item"><img class="icon" src="../themes/icons/login.svg" alt="🔒" /> <a class="signin" href="./?c=auth&amp;a=login">Login</a></li></ul>
<div class="header">
<div class="item title">
<h1>
<a href="./">
<img class="logo" src="../themes/icons/icon.svg" alt="" />
FreshRSS </a>
</h1>
</div>
<div class="item search">
</div>
<div class="item configure">
<img class="icon" src="../themes/icons/login.svg" alt="🔒" /><a class="signin" href="./?c=auth&amp;a=login">Login</a>
</div>
</div>
<div id="global">
<div class="post">
<div class="alert alert-error">
<h1 class="alert-head">Error 404 - Not found</h1>
<p>
You are looking for a page which doesn’t exist<br />
<a href="./">← Go back to your RSS feeds</a>
</p>
</div>
</div>
</div>
<div id="notification" class="notification closed">
<span class="msg"></span>
<a class="close" href=""><img class="icon" src="../themes/icons/close.svg" alt="❌" /></a>
</div>
</body>
</html>
```

The problem there seems fairly self-explanatory.

> becouse i cant get a proper rss.

The file you linked to in https://github.com/FreshRSS/FreshRSS/issues/2538#issuecomment-536170624 is well-formed and sufficiently valid.

**Comment by Frenzie** [comment]
So I repeat: What specifically is the difference between what you see and what you expect?

**Comment by Frenzie** [comment]
Sample XML file for easier retrieval:
[sample.xml.zip](https://github.com/FreshRSS/FreshRSS/files/3665775/sample.xml.zip)

**Comment by yanivz** [comment]
the sample file is same i sent...
In the end i want the xml will be well read and parsed from a software i use, so like my software reading fine this http://www.ynet.co.il/Integration/StoryRss1854.xml it will be reading fine this 
[sample.xml.zip](https://github.com/FreshRSS/FreshRSS/files/3665782/sample.xml.zip)

**Comment by Frenzie** [comment]
> the sample file is same i sent...

If there *is* a bug then some random outside location is likely to ensure that it can't be analyzed next month. ;-)

> In the end i want the xml will be well read and parsed from a software i use

Are there logs to tell what specifically it's having trouble with? Because we've got a well-formed document here, the only real issue being that it doesn't contain an e-mail address in the `<author>` element.

**Comment by Alkarex** [comment]
Hello,
There is more than one RSS format (RSS 0.9, RSS 1.0, RSS 2.0, ATOM...). The format used for outputs of FreshRSS is RSS 2.0, and the examples you have sent look just good.
But they indeed do not contain any style sheet (neither XSL nor CSS).
Try to put your URL into https://validator.w3.org/feed/ to check.
The error you saw on your page is because it is getting an error 404 from FreshRSS due to a wrong link.

**Comment by yanivz** [comment]
i got this error from validator: 
Sorry

This feed does not validate.

    line 12, column 23: Invalid email address: האוטוריטה (50 occurrences) [help]

        						<author>האוטוריטה</author>
                               ^

In addition, interoperability with the widest range of feed readers could be improved by implementing the following recommendations.

    line 8, column 119: Self reference doesn't match document location [help]

        ... rel="self" type="application/rss+xml" />
                                                     ^

    line 1178, column 0: description should not contain iframe tag (6 occurrences) [help]

        <p><strong>לכתבה לצפייה נרחבת אודות פעילותה : </strong></p>

    line 1275, column 0: description should not contain preload attribute (2 occurrences) [help]

        

    line 1275, column 0: description should not contain controls attribute (2 occurrences) [help]

        

    line 1283, column 0: description should not contain download attribute [help]

        <p>The post <a rel="nofollow" href="https://moreshethabesha.co.il/archives/1 ...

**Comment by Alkarex** [comment]
@yanivz I will try to fix the author issue spotted by the validator, but I do no think it explains the problem you are facing

**Comment by Alkarex** [comment]
Looking a bit more carefully at your previous messages, it looks like you do not have a token in your URL https://rss.avren.co.il/i/?a=rss&get=c_2&hours=168

**Comment by Alkarex** [comment]
Make sure to put a random token in
![image](https://user-images.githubusercontent.com/1008324/65822860-65ceff80-e24b-11e9-9c7c-82be9c69b4c5.png)

**Comment by yanivz** [comment]
what should i put there?

**Comment by yanivz** [comment]
Authentication token was the answer!! 💯
