### ISSUE TITLE
'Keep me logged in' problem

### ISSUE THREAD

**Issue by wankio** [FreshRSS/FreshRSS#2548]
I dont know why but everytime i'm Refresh pi in local network, it required ID and password. Cookies still there.

Pi address: http://192.168.1.14/FreshRSS/i/

AmazonEC2/Localhost(PC) is not required id/password once i'm logged in

**Comment by Frenzie** [comment]
Anything in the log perhaps? A low "Duration to keep logged in" in System configuration?

**Comment by wankio** [comment]
> 
> 2019-09-30 08:20:02SQL error updateCachedValues: database is locked
> 2019-09-30 08:20:02SQL error commitNewEntries: ["HY000",5,"database is locked"]
> 2019-09-28 05:00:01SQL error updateCachedValues: database is locked
> 2019-09-28 05:00:01SQL error commitNewEntries: ["HY000",5,"database is locked"]
> 2019-09-24 07:30:01SQL error updateCachedValues: database is locked
> 2019-09-24 07:30:01SQL error commitNewEntries: ["HY000",5,"database is locked"]
> 

 i dont  see 'duration to keep logged' in freshrss setting, does logged in is required for freshrss to update feeds ? 

Thank

**Comment by Frenzie** [comment]
You don't need to be logged in for feeds to update via cron. Could you please share the solution to your problem?

**Comment by wankio** [comment]
> 
> 
> You don't need to be logged in for feeds to update via cron. Could you please share the solution to your problem?

firefox web browser caused this, clearing cache/cookies, it should work
