### ISSUE TITLE
Cannot add feed

### ISSUE THREAD

**Issue by boblmartens** [FreshRSS/FreshRSS#2550]
I am having issues adding this feed:

https://blog.ayjay.org/feed

I checked the validity and also on SimplePie and it works. Also, I can pull the feed using curl on the VPS itself. What other things can I try?

**Comment by Alkarex** [comment]
Hello,
This feed works fine for me. Maybe just a temporary problem. Please try again.

**Comment by boblmartens** [comment]
I'll try it again later, but I ended up using FeedBurner as the intermediary.
