### ISSUE TITLE
Using systemd timer to refresh feeds

### ISSUE THREAD

**Issue by Offerel** [FreshRSS/FreshRSS#2557]
Hi there. Some system didn't use a cron service, but most of them use systemd. It's easy to use systemd for such cron like features. As example here are 2 services which work together. First you need a freshrss.timer file in /etc/systemd/system/ with the following content:

```
[Unit]
Description=FreshRSS get new content

[Timer]
OnBootSec=30s
OnCalendar=*:0/15

[Install]
WantedBy=timers.target
```
Additionally you need the freshrss.service file in the same directory. Its started 30 seconds after boot and then in a 15 minute interval:

```
[Unit]
Description=FreshRSS get new content
Wants=freshrss.timer

[Service]
User=www-data
Type=simple
ExecStart=/usr/bin/php /path/to/freshrss/app/actualize_script.php > /var/log/FreshRSS.log 2>&1
```
After creating both files, you should reload systemd with `systemctl daeamon-reload` and enable it with `systemctl enable freshrss.timer`. And please make sure, to change the path to your installation in freshrss.service. Maybe this is useful for some people.

**Comment by Alkarex** [comment]
@Offerel Thanks for the info 👍 
Would you feel like making a PR for our documentation with the same content, for instance in the following file or a file next to it with a reference?
https://github.com/FreshRSS/FreshRSS/blob/dev/docs/en/admins/01_Index.md

**Comment by Offerel** [comment]
PR is done. I have tried to make also a PR some days before for my FR #2434

**Comment by Alkarex** [comment]
Implemented in https://github.com/FreshRSS/FreshRSS/pull/2605
