### ISSUE TITLE
Bypass users max inactivity

### ISSUE THREAD

**Issue by xoxys** [FreshRSS/FreshRSS#2560]
I got another question. What does the option `max_inactivity` really do? Why does it exist?

I am a user which mostly uses an Android app with Fever API and it seems this does not "reset" the `max_inactivity` counter.

What will happen with the actualize script? 
https://github.com/FreshRSS/FreshRSS/blob/master/app/actualize_script.php#L43-L50

**Comment by Alkarex** [comment]
The reset is done every time there is a user action, such as login, mark as read, mark as favourite, add feed, etc. This is also the case for the Fever API (which, by the way, is quire inferior to the Google Reader API, so if your app support the later, please switch to it).

Its purpose is to avoid refreshing feeds for users which have not been active in a long time, to save resources.

If it does not work, please check that FreshRSS has write access in `./data/users/*/config.php`

**Comment by xoxys** [comment]
OK that totally make sense. Sadly, there isnt really a good one for Android :/

**Comment by Alkarex** [comment]
On Android, I still personally use News+ with Google Reader extension.
See https://github.com/FreshRSS/FreshRSS/blob/dev/README.md#google-reader-like-api
And another user has a work in progress https://git.feneas.org/christophehenry/freshrss-android

**Comment by Alkarex** [comment]
If it is Readably you are using, the app would just have to expose a server address for the code they already have for Inoreader (which is also using the Google Reader API). You could try to write to them :-)
The Fever API is very poor compared to the Google Reader API.

**Comment by xoxys** [comment]
@Alkarex Thanks for your tip. By the way, is there a chat or something else to discuss general questions?

**Comment by xoxys** [comment]
I don't get it... I've set the cronjob to every 15 minutes. It runs for all users fine and finished without errors but don't find updates. After the last cronjob finished, I hit the sync button in the ui and voilà, there are new articles. Why does this happen?

**Comment by Alkarex** [comment]
See the global and per-feed max refresh frequency configuration. 
For the chat, see https://freshrss.org/#help

**Comment by Alkarex** [comment]
Try a 20min or 30min cron, and let it run a few hours to see how that works

**Comment by xoxys** [comment]
Thanks again!
