### ISSUE TITLE
Call to undefined function _t() in Category.php on line 74

### ISSUE THREAD

**Issue by Leepic** [FreshRSS/FreshRSS#2564]
Since the PR #2522 ([line 74 of Category.php](https://github.com/FreshRSS/FreshRSS/pull/2522/files#diff-4618a3f4bd008df547c9bbc41e2bd145R74)) the gReader API is broken. I've got an HTTP 500 error when I sync my feeds. Here the error in the web server:

`Got error 'PHP message: PHP Fatal error:  Call to undefined function _t() in /var/www/html/FreshRSS/app/Models/Category.php on line 74`

Wordaround:

- Comment those lines:

```php
                //if ($id == FreshRSS_CategoryDAO::DEFAULTCATEGORYID) {
                //      $this->_name(_t('gen.short.default_category'));
                //}

```

Versions:
- 1.14.4-dev
- 5.6.40
- Apache 2.4.10

**Comment by Alkarex** [comment]
@Leepic Thanks for the bug report. Should be fixed with https://github.com/FreshRSS/FreshRSS/pull/2565
Could you please try to update your /dev branch?

**Comment by Leepic** [comment]
@Alkarex it works, thank you!
