### ISSUE TITLE
Reading view Icon broken in Firefox (Swage Theme)

### ISSUE THREAD

**Issue by Offerel** [FreshRSS/FreshRSS#2568]
It seems that the Reading view icon in Firefox is broken:

![Firefox 69.0.3](https://user-images.githubusercontent.com/14041522/66806599-3ea14f00-ef28-11e9-8b56-3eb5a70caa68.jpg "Firefox 69.0.3")
![Chrome](https://user-images.githubusercontent.com/14041522/66806642-57116980-ef28-11e9-992f-aaed308193c2.jpg "Chrome")

**Comment by Alkarex** [comment]
@pattems Could you maybe have a look?

**Comment by Offerel** [comment]
Since im not at my home pc, i could fix the icon with http://petercollingridge.appspot.com/svg-optimiser

i make a PR
