### ISSUE TITLE
SVG feed favicons aren't displayed correctly

### ISSUE THREAD

**Issue by dex6** [FreshRSS/FreshRSS#2572]
Recently one of sites I'm subscribing updated its favicon, switching from PNG to SVG file. FreshRSS correctly downloaded new favicon:

```
[.../FreshRSS/data/favicons] # file 61f3eba2.ico 
61f3eba2.ico: SVG Scalable Vector Graphics image
```
however the favicon is not displayed correctly. When opening its URL directly, Firefox shows _"The image https://.../freshrss/f.php?61f3eba2 cannot be displayed because it contains errors"_. Opera fails in similar way.

I've also discovered bug cause: it's serving SVG image with "Content-Type: image/x-icon" HTTP header. Changing to "image/svg+xml" in the f.php makes both browsers display favicon correctly (but obviously breaks all other favicon types... at least in Opera). Probably instead of hardcoding the content type header, some sort of dynamic discovery should be implemented. 

PS. feed in question for problem reproduction: https://www.chip.pl/feed/

**Comment by Alkarex** [comment]
Yes, we should save the original content type when retrieving the favicon, in the accompanying text file.

**Comment by pcaro90** [comment]
I wrote a fix for SVG favicons, checking if the first 4 characters of the .ico file are "<svg". It works for all of my favicons, but I don't know if there are more image types to have in mind. I'll make a pull request as it is.
