### ISSUE TITLE
Promote Liberapay (e.g, display sponsor button)

### ISSUE THREAD

**Issue by Frenzie** [FreshRSS/FreshRSS#2580]
Since Liberapay has been chosen as the way to go, it can be promoted slightly more efficiently than the "receives 1.49/week" button.

https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository

See https://github.com/WeblateOrg/weblate for what it would look like. I'm basically leaving this here as a note to self. It shouldn't take long but otherwise I might forget about it. ;-)

![Screenshot_2019-10-19_13-26-57](https://user-images.githubusercontent.com/202757/67144172-2ad15200-f274-11e9-9a72-2a09093710de.png)

![Screenshot_2019-10-19_13-27-10](https://user-images.githubusercontent.com/202757/67144173-2b69e880-f274-11e9-8b03-e297110cafd1.png)

**Comment by Alkarex** [comment]
Looks good (except for the parsing error :-) )

**Comment by Alkarex** [comment]
For the record, I have just started trying GitHub Sponsors Beta, to see how it is

**Comment by Frenzie** [comment]
More of a GH error since the syntax is fine.

I'm actually enrolled in the Sponsors beta and the Actions beta but I haven't taken the time to really investigate them yet.

**Comment by Alkarex** [comment]
@Frenzie Mine has just been activated https://github.com/sponsors/Alkarex/

**Comment by Frenzie** [comment]
Me too: https://github.com/sponsors/Frenzie/

Apparently the Stripe account for GitHub Sponsors somehow can't be used for Liberapay… pretty weird & confusing. Especially because even though they're apparently separate, you have to use different e-mails.

**Comment by marienfressinaud** [comment]
I didn't understand why the "sponsor" button didn't appear: I had to check an option in the GitHub settings. It's now enabled :)
