### ISSUE TITLE
Malformed RSS feeds

### ISSUE THREAD

**Issue by Ribero** [FreshRSS/FreshRSS#2597]
Hello,

FreshRSS has tagged some feeds imported by OPML export form Fever as "in error".
When checking the feeds, it's clear that they are not well formed and do not pass the W3C feed validator.

However the exactly same feed keep being well synchronized by Fever while FreshRSS state that the feed is empty and so nothing to push back to user.

Is there a way to "relax" a bit the way FreshRSS import new articles from a feed ? I thought about the "CSS" option of the feed but I did not yet figure out how to use it in this context.

**Comment by Frenzie** [comment]
You can add `#force_feed` at the end. Also see #2524.

**Comment by Ribero** [comment]
Hmmm, tried with `#force_feed` and cleared the cache but no luck. It keep saying the feed is empty.

**Comment by Frenzie** [comment]
Are there any URLs that can be shared?

**Comment by Ribero** [comment]
http://www.atlantico.fr/rss.xml#force_feed

**Comment by Frenzie** [comment]
I think the biggest problem is probably that it's missing the `channel` element. I'm slightly surprised it doesn't work in SimplePie because it feels fairly minor and easy to work around, but on the other hand I've never come across anything like it before. ;-)

https://www.simplepie.org/demo/?feed=http%3A%2F%2Fwww.atlantico.fr%2Frss.xml

https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fwww.atlantico.fr%2Frss.xml%23force_feed

**Comment by Ribero** [comment]
Yes, this feed is really malformed but I never noticed it with fever. I use many different feeds from many different sources for daily newspaper information and many of them are malformed but finally works.

Is there anything I can do at FreshRSS level to circumvent this issue ?

**Comment by Frenzie** [comment]
I'm afraid I don't think there is, besides patching SimplePie that is.

**Comment by Alkarex** [comment]
In general, I am a bit reticent to make too many workarounds for broken feeds, because this is damaging the ecosystem. But I will try to have a look tomorrow

**Comment by Ribero** [comment]
I understand. Of course I asked the provider if he plans to fix his feed before anything. Still waiting an answer 😒

**Comment by Ribero** [comment]
Is there anything I can do/change/configure in FreshRSS setup/config to allow this feed to work ?

**Comment by Frenzie** [comment]
You could probably write a plugin that preprocesses the feed (adding the `channel` element), but imo the easiest workaround would be to use the Filter bridge I wrote for [rss-bridge](https://github.com/rss-bridge/rss-bridge). Except in this case you'd permit all instead of filtering anything.

```
https://yada.yada/rss-bridge/?action=display&bridge=Filter&url=http%3A%2F%2Fwww.atlantico.fr%2Frss.xml&filter=&filter_type=permit&format=Atom
```

**Comment by Ribero** [comment]
Thanks @Frenzie, however I'm afraid this way beyond my skills ! 

By the way, the link you provided does not seems to work. I'm very interested to test it, have you another one ?

**Comment by Frenzie** [comment]
The `https://yada.yada` part isn't supposed to work of course! ;-) Only the `?action=display&bridge=Filter&url=http%3A%2F%2Fwww.atlantico.fr%2Frss.xml&filter=&filter_type=permit&format=Atom` parameters.

**Comment by Ribero** [comment]
Ok I thought there was a sort of test instance to try out 😄 
I need to check this. Thanks

**Comment by math-GH** [comment]
Is this issue still actual?
It looks like that Atlantico.fr works fine with simplepie and the feed validates in the W3C validator.

**Comment by Frenzie** [comment]
Yup, the feed is fixed. Always the better solution.
