### ISSUE TITLE
Max articles should be disabled by default

### ISSUE THREAD

**Issue by Frenzie** [FreshRSS/FreshRSS#2600]
Cf. https://github.com/FreshRSS/FreshRSS/pull/2599#issuecomment-546606015

Most important: it should be disabled for existing installations when upgrading. It's an extremely destructive setting that should not be enabled without user interaction. This goes together with the new 3 months similarly destructive setting.

I'm also strongly opposed making it a default for new installations since it's secretly destructive, but that's a slightly separate discussion from not harming existing installations.

**Comment by Alkarex** [comment]
I agree for existing installations.
I think we should have default max/min/date limits for new installations, but we can discuss the values.

**Comment by Alkarex** [comment]
Fixed by https://github.com/FreshRSS/FreshRSS/pull/2602

**Comment by Frenzie** [comment]
Back in '05 I curiously tried Google Reader. I didn't care for it (besides that it was available everywhere), but the cherry on top was that 30 days later, it had started removing the first entries. I celebrated its demise.

Anyway, it's more about information than about the setting as such.

**Comment by Alkarex** [comment]
Should be good this time https://github.com/FreshRSS/FreshRSS/pull/2607

**Comment by Luxtech** [comment]
Is it possible to disable the max articles limit on a existing installation?
