### ISSUE TITLE
"My labels" arrow dropdown not working

### ISSUE THREAD

**Issue by Frenzie** [FreshRSS/FreshRSS#2601]
Found while testing 1.15 for release, but I'm not entirely sure if it's new or not.

Click on down arrow:
![Screenshot_2019-10-26_17-27-57](https://user-images.githubusercontent.com/202757/67622014-01856880-f816-11e9-955c-1ed79fb8a0ee.png)

Click on "My labels":
![Screenshot_2019-10-26_17-28-13](https://user-images.githubusercontent.com/202757/67622015-021dff00-f816-11e9-99dd-9601ce240038.png)

_Originally posted by @Frenzie in https://github.com/FreshRSS/FreshRSS/pull/2599#issuecomment-546612573_

**Comment by Alkarex** [comment]
Hum, I cannot reproduce. That is the *Origin* theme, right?
On which browser, platform?

**Comment by Frenzie** [comment]
Firefox 68, Debian 10.

But it's the same in Fx 69, Vivaldi/Blink, Opera/Blink, Otter/QtWebKit, etc.

**Comment by aledeg** [comment]
Cannot reproduce either on FF70, Archlinux :/

**Comment by Frenzie** [comment]
To be clear if you're trying after clicking on "My labels," it doesn't happen if you collapse it and then open it again.

**Comment by Frenzie** [comment]
Oh, hold on! It only happens from `Main stream`.

Any feed, category, favorites, etc. and it works.

Or to put it another way, only from `?a=normal`, any `&get=` will make it work.

**Comment by aledeg** [comment]
It does work for me on `Main stream`. That's weird

**Comment by Frenzie** [comment]
The key is that you need to have labels that apply to the current view. For quick filtering only applicable labels will show. When there are no applicable labels, this ugly effect rears its head.

Depending on your perspective the problem is either that the expansion arrow is shown when there are no applicable labels, or that all labels aren't aren't always shown.

Added 1 label to an unread article in the main stream:
![Screenshot_2019-10-26_21-58-22](https://user-images.githubusercontent.com/202757/67625244-e3326380-f83b-11e9-9637-1ddb410d07d7.png)

All labels:
![Screenshot_2019-10-26_21-58-37](https://user-images.githubusercontent.com/202757/67625252-f0e7e900-f83b-11e9-8565-9f80d11d1d37.png)

**Comment by Alkarex** [comment]
Ah, you mean that all the tags should be visible in a "show only unread articles" view, even though there is no tagged article unread?

**Comment by Frenzie** [comment]
Perhaps, but I don't really mean anything more than what it says in the OP.

There's a down arrow, you click it, you get a weird, unexpected result:

![Screenshot_20191027_045415](https://user-images.githubusercontent.com/202757/67629457-fcf09c80-f875-11e9-935a-ff4ebb2f69e9.png)

There are several ways to fix that. You could hide the whole thing, you could hide the down arrow or you could show all labels. Maybe something else still.

**Comment by Alkarex** [comment]
This is not new to 1.15. A proper solution that also works during auto-refresh requires a bit of thinking/work. Let's keep it for 1.16

**Comment by math-GH** [comment]
Will #4065 fix this issue?

**Comment by math-GH** [comment]
I guess it is fixed
