### ISSUE TITLE
Unread style affects entire article

### ISSUE THREAD

**Issue by Frenzie** [FreshRSS/FreshRSS#2604]
v1.15

For a little while after opening an article, it looks like this:
![Screenshot_2019-10-26_21-42-23](https://user-images.githubusercontent.com/202757/67625084-9f3e5f00-f839-11e9-9521-c7a17a14b7fb.png)

**Comment by Alkarex** [comment]
I think it is a duplicate of https://github.com/FreshRSS/FreshRSS/issues/2304

**Comment by Frenzie** [comment]
It's definitely not; this is brand new behavior in 1.15.

#2304 is something I'm fairly ambivalent toward, or possibly slightly opposed to.

**Comment by Frenzie** [comment]
The old behavior was just the icon iirc.

**Comment by Frenzie** [comment]
But you're right, the problem is really something else.

**Comment by Frenzie** [comment]
Old, better look where you could read normally regardless of read status:

![Screenshot_2019-10-27 (1) Your RSS feeds · FreshRSS](https://user-images.githubusercontent.com/202757/67629795-03821280-f87c-11e9-8fa5-8a7aa57a3139.png)

**Comment by Alkarex** [comment]
I have not understood then. Could you please explain the problem again?

**Comment by Alkarex** [comment]
Ok, I think I have understood, but I do not think this is new to 1.15. Checking

**Comment by Frenzie** [comment]
It changed between 1.14 and 1.15. ;-) [That screenshot](https://github.com/FreshRSS/FreshRSS/issues/2604#issuecomment-546661558) is from 1.14, before I upgraded it to test for #2600, after which it changed to the 1.15 situation as in the OP.

**Comment by Alkarex** [comment]
Ok, just checked and seems indeed new

**Comment by Alkarex** [comment]
Hum, I cannot immediately spot a CSS or JavaScript change which could relate to that.

**Comment by Frenzie** [comment]
Perhaps it's my own fault. ;-)

**Comment by Frenzie** [comment]
I did a quick breakfast investigation.

## Also has this issue

- Flat design
- Origine-compact
- Swage (already has this issue in 1.14)

## No problem

- Ansum
- Blue Lagoon
- Dark
- Mapco
- Screwdriver

The fix is likely to look very similar.

**Comment by Frenzie** [comment]
Fixed by #2611 and #2612.
