### ISSUE TITLE
Add Reeder macOS/iOS to documentation

### ISSUE THREAD

**Issue by kmplngj** [FreshRSS/FreshRSS#2608]
Hello,

perhaps you want to add Reeder to the documentation for compatible clients.

https://freshrss.github.io/FreshRSS/en/users/06_Mobile_access.html

https://www.reederapp.com

Thanks
Jan

![Bildschirmfoto 2019-10-27 um 18 58 17](https://user-images.githubusercontent.com/562965/67639080-cfded100-f8eb-11e9-8eba-686ac74da451.png)
![Bildschirmfoto 2019-10-27 um 18 58 19](https://user-images.githubusercontent.com/562965/67639081-d0776780-f8eb-11e9-8157-2113ccbdebc2.png)

**Comment by Frenzie** [comment]
It's listed on https://freshrss.github.io/FreshRSS/en/users/06_Fever_API.html but the Google Reader API is indeed preferable.

**Comment by Alkarex** [comment]
@kmplngj Thanks for the screenshots :-) Reeder is already listed (twice :-) ) in our /dev branch https://github.com/FreshRSS/FreshRSS/blob/dev/docs/en/users/06_Mobile_access.md#compatible-clients which is about to be released by the end of the month

**Comment by Alkarex** [comment]
Related issues for 1.15
* https://github.com/FreshRSS/FreshRSS/pull/2594
* https://github.com/FreshRSS/FreshRSS/pull/2578
* https://github.com/FreshRSS/FreshRSS/pull/2540
* https://github.com/FreshRSS/FreshRSS/pull/2526
* https://github.com/FreshRSS/FreshRSS/issues/2513

**Comment by Frenzie** [comment]
@Alkarex My bad, I knew I'd seen it in the docs but forgot it had been updated. :+1:
