### ISSUE TITLE
Leed URL in README broken

### ISSUE THREAD

**Issue by Frenzie** [FreshRSS/FreshRSS#2613]
http://leed.idleman.fr/ doesn't seem to be working, change to https://github.com/LeedRSS/Leed? Remove?

**Comment by Alkarex** [comment]
The link was up in May http://web.archive.org/web/20190501114819/http://leed.idleman.fr/
Let's give it a couple more days, and otherwise change for the GitHub version

**Comment by aledeg** [comment]
It seems still broken. I've made a PR to address that.
