### ISSUE TITLE
Items are cleared when they aren't visible.

### ISSUE THREAD

**Issue by lebrisg** [FreshRSS/FreshRSS#2617]
Inside a category, I find undesirable the fact that items are deleted when they are no longer visible (because I went down the list of items).

Is it a feature, a bug, or something that you can change in the settings?

I'm currently using Firefox Quantum 60.9.0esr on Windows 10 with FreshRSS-1.14.3 on CentOS 7.6.

**Comment by Frenzie** [comment]
Actual deletion can be set up in settings → Archiving.

But if you're just talking about display, you can toggle the unread envelope at the top.

![Screenshot_2019-10-31_11-59-48](https://user-images.githubusercontent.com/202757/67941474-f6478980-fbd5-11e9-9eee-1cb701b64d73.png)

**Comment by Alkarex** [comment]
I have not fully understood the problem, but please have a look at the reading options

![image](https://user-images.githubusercontent.com/1008324/67943722-fa29da80-fbda-11e9-8e5c-be289f37bf83.png)
