### ISSUE TITLE
Favorite affects whole article display

### ISSUE THREAD

**Issue by Frenzie** [FreshRSS/FreshRSS#2618]
v1.15

Same as #2604. There might also be a minor issue with hover in some circumstances.

**Comment by Alkarex** [comment]
@Frenzie Let's issue a [fast release 1.15.1](https://github.com/FreshRSS/FreshRSS/milestones/1.15.1) for fixing a couple of regressions. It would be nice if that could include this issue

**Comment by Frenzie** [comment]
Sure thing, this shouldn't take long. Not this afternoon though. :)

**Comment by marienfressinaud** [comment]
Do you think you'll have time tonight? :) Otherwise, I'll work on it tomorrow morning so we can release the 1.15.1 in the afternoon or evening

**Comment by Frenzie** [comment]
@marienfressinaud My spare time is fairly occupied until Wednesday (Bill Bailey tomorrow ;-) ), so feel free to go ahead if you want it done tomorrow.
