### ISSUE TITLE
Wonders if I can only export the api access but not include the web interface

### ISSUE THREAD

**Issue by sidkang** [FreshRSS/FreshRSS#2622]
Hi, the FreshRss project is awesome, I would want to forward the port to the public internet. I mainly use the public network access via api, so I was wondering if I can only forward the api access but let the web interface stay in the local network meanwhile? Is there any solution, like using 1 port for the web interface and the api each(2 sum), or some king of settings I can just disable the web page?

**Comment by Alkarex** [comment]
Hello,
I think the easiest is to disallow (or password protect by HTTP Basic Auth) the `/i/` directory.

Assuming you are using an Apache server, to disallow the Web interface, you can put a file like:
https://github.com/FreshRSS/FreshRSS/blob/dev/app/.htaccess
into your `./FreshRSS/p/i/` directory.

But I think using a password protection would be better:
* https://freshrss.github.io/FreshRSS/en/admins/09_AccessControl.html

Example of file `./FreshRSS/p/i/.htaccess` :

```
AuthUserFile /[your-path]/.htpasswd
AuthGroupFile /dev/null
AuthName "Your-site.example.net"
AuthType Basic
Require valid-user
```

Detailed explanation for Apache https://httpd.apache.org/docs/trunk/howto/auth.html

**Comment by Alkarex** [comment]
Closing here, but let us know whether that suites your needs
