### ISSUE TITLE
api Bad Request!

### ISSUE THREAD

**Issue by Tealk** [FreshRSS/FreshRSS#2636]
I'm not quite sure, but I think since the update to 1.15.0 the API doesn't work for me anymore.
I only get the message "Bad Request!

**Comment by Alkarex** [comment]
Hello,
Could you please try our /dev branch?
What FreshRSS installation are you using (e.g. Docker...), on which platform, and with which mobile client?

Potentially the same as https://github.com/FreshRSS/FreshRSS/pull/2621 , https://github.com/FreshRSS/FreshRSS/issues/2620

**Comment by Tealk** [comment]
Debian 10, Apache2, PHP7.3
No docker downloaded via git
I'm using Reeder4 and it didn't show me any updates anymore, when I go to the API address via web I get the message.

**Comment by Alkarex** [comment]
Ok, most likely the same than https://github.com/FreshRSS/FreshRSS/pull/2621
You can checkout the /dev branch by git, or manually patch with https://github.com/FreshRSS/FreshRSS/pull/2621/files
Feedback welcome

**Comment by Tealk** [comment]
Thanks for the help, the dev branch works.

**Comment by Alkarex** [comment]
Thanks for the feedback @Tealk 👍
