### ISSUE TITLE
Category disappeared

### ISSUE THREAD

**Issue by Tealk** [FreshRSS/FreshRSS#2637]
Since the update to 1.15.x I am missing the category "Changelog" if I want to add it again I get the message "The category name already exists".

The feeds that were in "Changelog" are now in "Uncategorized".

Debian 10, Apache2, PHP7.3
downloaded/install via git

**Comment by Alkarex** [comment]
Do you maybe have a tag with that same name?

**Comment by Tealk** [comment]
I never have use Tag's
On the Reeder4 app I see the category, but not on the website.

**Comment by Alkarex** [comment]
Did you maybe change the name of the default category before? ("Uncategorized")
In any case, try to organise the feeds and categories so that they are correct on the Web site.
If this is not synchronised to Reeder, then there is a bug to report to Reeder, but you can try to log out / log in.

**Comment by Tealk** [comment]
So I have these categories, since I have been using FreshRSS for quite some time now, I can't tell if I have renamed a category.
![image](https://user-images.githubusercontent.com/12276250/68298896-69e40d80-0092-11ea-8c84-8daebe1c3bdc.png)

//Edit
relog has no effect.
Reeder4 Shows the category, I didn't want to report it as an error but as information that the API seems to pass it correctly.

**Comment by Alkarex** [comment]
Right, we have removed the possibility of renaming the default category (id=1), but we should have cleared the name of that category, which causes your issue.
I will try to make a fix, but for now you can manually edit the name of category 1 to "Uncategorized" (not important what precise name it is, as long as it does not collide with something else)

**Comment by Tealk** [comment]
Great thanks for the fast help

**Comment by Alkarex** [comment]
Addressed by https://github.com/FreshRSS/FreshRSS/pull/2638
