### ISSUE TITLE
A feed could not be found

### ISSUE THREAD

**Issue by nmaster2042** [FreshRSS/FreshRSS#2641]
I'm a new freshrss user.

I wanted to add french clubic.com RSS and I got an error in the log:

`2019-11-07 16:00:10A feed could not be found at "https://www.clubic.com/feed/news.rss"; the status code is `200` and content-type is `application/xhtml+xml` [https://www.clubic.com/feed/news.rss]`

freshrss  v1.15.1

**Comment by Alkarex** [comment]
Bonjour et bienvenu :-)
Essayez avec `https://www.clubic.com/feed/news.rss#force_feed` (car le flux est invalide)

**Comment by nmaster2042** [comment]
Bonjour, merci cela fonctionne.

Problem solved with #force_feed
