### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by alfureu** [FreshRSS/FreshRSS#2650]
CustomCSS is not working when I load it to the extensions folder. I know after the major version update it was recommended to disable the extensions, which I did, but now I would love to have my extensions back. Are all of these working because at my end they do not load...

**Comment by Alkarex** [comment]
Hum, I cannot reproduce. CustomCSS works fine for me.
Could you please check : your FreshRSS version, your CustomCSS version, and the access rights on the `./extensions/` folder and its children?
Does the extension(s) appear in your FreshRSS configuration page?

**Comment by Alkarex** [comment]
@Frenzie By the way, I suggest that we move CustomCSS and CustomJS to https://github.com/FreshRSS/FreshRSS/tree/master/extensions/ so that they are shipped by default

**Comment by alfureu** [comment]
Hi @Alkarex, I use FreshRSS in a docker, I copied the `xExtension-CustomCSS` to the `./extensions/` folder, as you can see in the screenshot:
![image](https://user-images.githubusercontent.com/10846169/68528632-abc0be00-02f5-11ea-9648-4ea9ba6c1a9e.png)

The issue is that the extension is not recognized by FreshRSS: 
![image](https://user-images.githubusercontent.com/10846169/68528641-c5fa9c00-02f5-11ea-9d80-36c4f7725369.png)

Don't really know what is the issue...

**Comment by Alkarex** [comment]
Ah, this is most likely because it is not *inside* your Docker image / volume.
What docker run / compose are you using?

**Comment by alfureu** [comment]
Actually no, I downloaded and edited this from within, I just have access to the data also to a shared folder for the host. 

Edit: I am using `linuxserver/freshrss:latest`

**Comment by Alkarex** [comment]
@DOFfactory Can you show the `docker run` or `docker compose` command you use, where one can see the shared folder?
From your host, try the following command:
```sh
sudo docker exec -it freshrss ls -alh extensions
```

**Comment by alfureu** [comment]
Hm, weird, when I run the command I get:
```
ls: cannot access 'extensions': No such file or directory
```
EDIT: I definitely have the Tumblr extension installed, as you can see on the screenshot above

**Comment by Alkarex** [comment]
@DOFfactory I do not know whether you have found a solution in the meantime, but I have just pushed a change to our master branch https://github.com/FreshRSS/FreshRSS/pull/2837 that should allow easier volume mounting from Docker. 
See the documentation https://github.com/FreshRSS/FreshRSS/tree/master/Docker#run-freshrss
If you are willing to give a try to our Docker image, your feedback would be welcome (the Docker Hub image should be done building shortly - let me know whether you are interested and I will ping you).

**Comment by Alkarex** [comment]
Docker Hub image ready https://hub.docker.com/r/freshrss/freshrss/
