### ISSUE TITLE
Extension on a per feed basis?

### ISSUE THREAD

**Issue by kour1er** [FreshRSS/FreshRSS#2652]
Sorry if this question has been asked elsewhere (I looked and couldn't see anything) - is it possible to write an extension that can be enabled on a per feed basis?

For example, if I want to write an extension that calls out to an external API to provide full-text content for a specific RSS feed but not all RSS feeds in the FreshRSS installation?

Thanks for any pointers

**Comment by Frenzie** [comment]
It seems to me that there are at least two extensions listed [here](https://github.com/FreshRSS/Extensions) that make explicit reference to a particular website that could serve as an example. ;-)

https://github.com/aledeg/FreshRSS-extensions/blob/f49df8105a91471ce767a0acf828dbcc9d6eed43/xExtension-RedditImage/extension.php#L113-L115

https://github.com/kevinpapst/freshrss-youtube/blob/6aeab284dbe867f143a05339b939cbaea69d69dd/xExtension-YouTube/extension.php#L105-L111

**Comment by kour1er** [comment]
Thanks so much for the pointers. I think I didn't express myself properly...

In the two examples you kindly linked to, they seem to be targeting specific domains from the source code. I was more thinking along the lines of being able to expose to the FreshRSS user a new section in the interface for them to choose what feed in their collection of feeds to apply the functionality of the extension to.

i.e. say the user has five RSS feeds in their FreshRSS installation. Within the FreshRSS interface, the proposed extension provides a new GUI interface to allow them to select feed1 and feed3 to apply the extension to, just with a click.

Is that sort of thing possible? Ideally, it would be great if it would be possible to add an element into the Manage option from the cogwheel icon in the main interface.

**Comment by Frenzie** [comment]
I don't see much difference tbh. The way I'd write it is probably something like:

1. Figure out this external API stuff. This would be the potentially difficult, time-consuming part. I'd probably use one or two hard-coded domains for starters, or some other equivalent simplification.
2. Make that configurable with a few UI elements.

As for step 2, piece of cake to make it configurable within the plugin management view.

It may not currently be possible to do it for the individual feed management page without replacing the entire view, you'd have to check the controller/hooks, but I don't quite understand the concern if you're sufficiently advanced a coder to be able to deal with the API stuff. :-)

**Comment by kour1er** [comment]
Fair enough :) Thanks for the information.

**Comment by kour1er** [comment]
Sorry, one more probably really dumb question - as part of an extension, is it possible to get the feed url and website variables of an rss item (entry)?

I can see that I can get the id for the feed via:
$entry->feed()
as part of the registerHook entry_before_display.

Is there recommended way of doing a database lookup to translate the id_feed from the entry table to feed url and feed website (of the feed table)? thank you for any pointers (again)

**Comment by Frenzie** [comment]
You mean like `$feed->url()` and `$feed->website()`?

https://github.com/FreshRSS/FreshRSS/blob/b2c77d1cb4214265aa85224c58baa28521fea866/app/Controllers/subscriptionController.php#L152-L163

**Comment by kour1er** [comment]
Ah yes - that would be the one :) Cheers!
