### ISSUE TITLE
a lot of errors of WebSub 

### ISSUE THREAD

**Issue by rezad1393** [FreshRSS/FreshRSS#2653]
I am new to freshrss.
I installed it and the log is full of these massages
Error while WebSub subscribing to https://www.blogger.com/feeds/8854346034886329132/posts/default
WebSub lease ends at 2019-11-10T00:13:56+00:00 and needs renewal: https://www.blogger.com/feeds/8854346034886329132/posts/default

and more like that for feedsbuner.

**Comment by Alkarex** [comment]
Hello,
For WebSub to work, your FreshRSS instance needs to be visible from the Internet.
If this is the case, try the demo https://push-pub.appspot.com to check whether that works.
See e.g. https://github.com/FreshRSS/FreshRSS/issues/2595#issuecomment-546517724

**Comment by rezad1393** [comment]
ok?
thank you for answer.
I use the periodic update method with cron and I dont particularly need websub.
is there a way to disable it checking or or in its entirety?

**Comment by Alkarex** [comment]
Response on how to disable WebSub https://github.com/FreshRSS/FreshRSS/issues/2654#issuecomment-552839190
