### ISSUE TITLE
proposal: use https whenever you can

### ISSUE THREAD

**Issue by rezad1393** [FreshRSS/FreshRSS#2657]
I am not talking about the feeds, although that is also important.
as I see it now http without https is dying a slow death(good riddance).

so using https version of websites is better than http version. (I dont know why websites still have http version to be honest. even corporate firewall excuse is no longer valid because all the web is going https).

I am proposing using https version of urls when available by default.
for example in feed checking freshrss uses http://validator.w3.org even though https://validator.w3.org is available.

this is more of a philosophy not a bug, but I dont think high of open source applications that are striving to be secure but use http links instead of https.

**Comment by Alkarex** [comment]
Hello,
We have a default list of domains for which to force HTTPS https://github.com/FreshRSS/FreshRSS/blob/dev/force-https.default.txt and the possibility to load your own list in `./data/force-https.txt`

**Comment by Frenzie** [comment]
Forgot about that. Already in the core then. :-)

**Comment by rezad1393** [comment]
I am talking about the app itself not feeds.
I gave an example for the feed validation option is the app that uses http instead of https.
http://validator.w3.org

**Comment by Frenzie** [comment]
I see what you mean, but a quick search through the source suggests it's more accurate to say it's literally the only example. ;-)

I suppose some code comments could arguably be updated but you can't just sed it (because then you'd get non-working links).

**Comment by rezad1393** [comment]
I know.
that's why I said a proposal whenever you can.
I get sad when programs I use, use http instead of https.

**Comment by Alkarex** [comment]
@rezad1393 Would you like to send a patch with a search & replace `http://validator.w3.org` by `https://validator.w3.org` ?

**Comment by rezad1393** [comment]
I am very new to programing and git and patch are not that familiar to me.
I only used then as copy paste from internet or just using git pull for some programs that I used to compile (openwrt).

but if it can be done easily to get my feet wet I would appreciate any help/small-guide for me to start to do it?

**Comment by Frenzie** [comment]
That's basically all there is to it. 

1. You fork the repo to your own GH account.
2. You clone it (as instructed by GH).
3.
```bash
git checkout dev
git checkout -b my-fix-branch
# edit the relevant file
git add the-relevant-file
git commit
# write a commit message
git push
# follow the instructions to push the branch
```
4. Create a PR.

(Or alternatively, very simple changes can be done though the GH web UI.)

**Comment by rezad1393** [comment]
I am using the github webui.
but I had to create two file change (add.html and update.html).
how do I combine them these two so that I can use just one pull request?

**Comment by Frenzie** [comment]
You should be able to edit files within the same branch.

So you go to a branch (I went to this one more or less at random):
https://github.com/rezad1393/FreshRSS/tree/patch-1

You browse around to the file:
https://github.com/rezad1393/FreshRSS/blob/patch-1/app/views/feed/add.phtml

And the rest should hopefully work itself out from there.

**Comment by rezad1393** [comment]
thanks
I will try that.
the weird thing is that search function doesnt work in my fork and I have to find the files manually.

**Comment by Frenzie** [comment]
It's a GH deficiency I believe, presumably to save resources. GH's added value is really about the PR review workflow and to a lesser extent issue tracking. For pretty much anything else plain Git and local tools are better.

**Comment by rezad1393** [comment]
btw I closed the page the was my pull request.
how do I find it again?

**Comment by Frenzie** [comment]
At the top of the page there's a link to "pull requests" on each repo. Also on github.com there's a little overview of your own recent activity.

PS It's #2662.

**Comment by rezad1393** [comment]
if I didn't bother you too much I have another question.
in this pull request I always have to fork a project to my own account in github right?
then in there what branched should I keep?
for example there are two branches in freshrss one. master and dev.
when I choose master for pull request there were some other changes(files changes) from other so I got scared and tried the dev one and there only changes were my file changes.
if I chosen the master branch to pull request against then I would have messed up?
or was that because I did my first my change from start against dev branch maybe?

**Comment by Frenzie** [comment]
In FreshRSS you should always make changes against the `dev` branch, which means starting from dev and opening the PR against dev. 

Btw @Alkarex I think `dev` should be changed to the default branch in the GH settings.

https://help.github.com/en/github/administering-a-repository/setting-the-default-branch

**Comment by rezad1393** [comment]
many other repos dont have dev and just have master.
on them I should use pull request with master then?

**Comment by Frenzie** [comment]
Usually, yes.

Another example similar to FreshRSS is Elkarte, which uses `development`: https://github.com/elkarte/Elkarte

![Screenshot_2019-11-13_13-05-28](https://user-images.githubusercontent.com/202757/68762350-4bdc5700-0616-11ea-82cf-250526d13496.png)

Except because there it's set as the default branch, you can't accidentally open a PR against master. :-)

**Comment by rezad1393** [comment]
so if as I change a file some other person changes some other files then in my pull request I see their changes too or just my files? or because I forked at that time I changed my files then I have that exact time-locked repo in my personal one?

**Comment by Frenzie** [comment]
If you mean on GitHub, not unless there are so-called conflicts.

**Comment by rezad1393** [comment]
no to what?
when I tried my pull request there was other changes that I didnt do at the top.
like 1.5.3-dev and rtl support.
I didnt try to pull request against that and tried dev branch and that didnt have the changed files of others.

also if I fork a repo (for or PR or any other reason) then I have a snapshot of that time and other changes after that from source repo are not copied to my personal repo.
so if later I want to PR again but I want to do it with respect to current source repo then how do I update my main personal repo to reflect the latest snapshot from source then change file in that?

**Comment by Frenzie** [comment]
Right, you'll see all changes in your branch compared to the branch against which you open a PR.

> how do I update my main personal repo to reflect the latest snapshot from source then change file in that?

I don't know if that's possible through GitHub (except by deleting the fork and reforking).

I use a remote called `upstream` as described [here](http://koreader.rocks/doc/topics/Collaborating_with_Git.md.html).

**Comment by Alkarex** [comment]
To update your local branch to be the same than your remote branch:

```sh
git fetch
git reset --hard FETCH_HEAD
```

To update your own fork (often called *origin*) to be the same than original repository (often called *upstream* ), using the branch `/dev` as example:

```sh
git fetch --all
git reset --hard upstream/dev
```

P.S.: This is automatically set up by e.g. GitHub Desktop. If not:

See your configured branches:

```sh
git remote -v
```

Example of output:

```
origin  https://github.com/Alkarex/FreshRSS.git (fetch)
origin  https://github.com/Alkarex/FreshRSS.git (push)
upstream        https://github.com/FreshRSS/FreshRSS.git (fetch)
upstream        https://github.com/FreshRSS/FreshRSS.git (push)
```

**Comment by rezad1393** [comment]
I only use webui of github, buy maybe I should go a github on my desktop? right?
any suggestions for a selfhosted git ? maybe gitlab on my own computer?
can that sync with github from that? is it easy?

**Comment by aledeg** [comment]
You just need to install `git` software and follow the aforementioned instructions given by @Frenzie and @Alkarex. There is no need for other things locally.

**Comment by Frenzie** [comment]
Git is just a program for version control, which doesn't depend on any servers. You can use it directly (as I do) or through a GUI like GitAhead.

Servers are just to share/collaborate/backup.

**Comment by rezad1393** [comment]
I am asking if I can somehow link gitlab and github so that I can for  example fork from github into gitlab and them gitlab locally to do my thing and then push to github.

**Comment by Frenzie** [comment]
Sure, I do that kind of thing all the time. You can add as many remotes as you like.

**Comment by rezad1393** [comment]
ty
any suggestion for self hosted github equivalent? (with wiki and such) 
I ask this for convenience sake of github UI.
does gitlab or gitea be too much for me or not?

**Comment by Frenzie** [comment]
I may have misunderstood you. I just mean I use my local git repo with multiple remotes. You can set up bidrectional mirroring in GitLab but I'm not quite sure if I understand the purpose. You mean in order to have something like GitLab to collaborate with others but managed by you?

**Comment by rezad1393** [comment]
yes.
on my local computer and selfhosted(just like freshrss vs google reader)

**Comment by Frenzie** [comment]
But I don't understand where GitHub fits in?

**Comment by Frenzie** [comment]
As in "fork from github into gitlab and them gitlab locally to do my thing and then push to github."

**Comment by rezad1393** [comment]
I mean can I fork from github to gitlan (i think i can with standard git commands) but then when I change files in gitlab on my local computer I have to again used command line git or can gitlab connect to github(maybe with a api or plugin) and be integrated with that so that I use my gitlab instance to push to github and other stuff with its webui.

basically I am asking if gitlab(or something like that) can be integrated (or connected) to github and help steamline PR and other git related procedures.

if my question if too vague , then feel free to so say and not answer it.

maybe I need to first mess with gitlab for some time then visit this issue again.

thanks for all the answers.

**Comment by Frenzie** [comment]
Tbh it sounds like a so-called [XY problem](http://xyproblem.info/).

GitLab is something you use to replace or augment GitHub. If you're having some kind of trouble figuring out something Git-related, I should think a GitLab PR is no different than a GitHub PR.

There is GUI software that provides a frontend to Git, like GitAhead and git-cola. The only one I actually sometimes use though is Git GUI.[1] It makes it easier to stage individual lines and offers a more convenient git blame.

Apparently that GitHub Desktop thing also works as a generic Git client? It's listed [here](https://git-scm.com/downloads/guis). That page seems like it's the answer to your actual question, rather than the one you're asking.

[1] And gitk can be nice to view commits, but that basically feels like a part of Git GUI anyway.

**Comment by rezad1393** [comment]
never mind.
but thanks for all the answer and the patience.
have a good day.
