### ISSUE TITLE
Improve logs when an error on profile page happen

### ISSUE THREAD

**Issue by JonathanMM** [FreshRSS/FreshRSS#2663]
On profile page, I tried to define an api password, to use an android application. But, the password was not set, and only a generic error displayed on the page.
After investigation (thanks to Mattermost server!), the issue comes from the folder ./data/fever, which haven't write rights.
It should be great if this information will add on /user/*/log* file, to help to debug :)

**Comment by aledeg** [comment]
There is a log in the ```data\users\_``` folder. It does not show in the interface though.
I've addressed that issue in #2664. If you could test it, it will be appreciated.
