### ISSUE TITLE
Doesn't save selection to only display unread news

### ISSUE THREAD

**Issue by Ner3y** [FreshRSS/FreshRSS#2667]
I set the option on main screen to only show the unread messages. When I go to settings or close the tab and open it again, the read news are also shown again.

Is there some kind of setting to deactivate it general?

**Comment by aledeg** [comment]
There is an option available in the Reading configuration page. Its name is "Articles to display". It can take one of the following values:
- Adjust showing
- Show all articles
- Show only unread

In your case, you want to select the last one.

**Comment by Ner3y** [comment]
Ah.. perfect, thx for the super fast answer! :)

**Comment by aledeg** [comment]
You're welcome :)
