### ISSUE TITLE
addCategory error

### ISSUE THREAD

**Issue by clainguf** [FreshRSS/FreshRSS#2670]
I get an error on the latest version when i try to add a category:
SQL error addCategory: ["21S01",1136,"Column count doesn't match value count at row 1"]

**Comment by Alkarex** [comment]
This seems to be the same than https://hostux.social/@valere/103129380709944691
I did not have the explanation though, besides a MySQL version issue.
More information welcome: type of server (MariaDB, MySQL), version, platform, a `SHOW CREATE TABLE` of the `*category` table for the affected user, whether that comes when using FreshRSS Web interface or via API, any MySQL log if available, etc.

**Comment by clainguf** [comment]
Dear Alexandre

Thank you for your follow up.

Included is a pdf with server info.

**Comment by Alkarex** [comment]
@clainguf The attachment was lost in the process :-) Could you please post it again via the Web interface here?

**Comment by clainguf** [comment]
Dear alexandre,

Upgrade mysql to 5.7.27

Works now.

Met vriendelijke groeten / Meilleures Salutations / Best regards,

Yoni Smits
Chief executive officer
[cid:image001.jpg@01D25AE1.B7371EB0]<http://www.smitsbelgium.be/>

SMITS Belgium
Monnikenhofstraat 298
2040 ANTWERP



T. +32 3 292 67 67
T. +32 3 292 67 65
E. yoni@smitsbelgium.be<mailto:yoni@smitsbelgium.be>
I.  www.smitsbelgium.be<http://www.smitsbelgium.be/>


De informatie opgenomen in dit bericht kan vertrouwelijk zijn en is uitsluitend bestemd voor de geadresseerde. Indien u dit bericht onterecht ontvangt, wordt u verzocht de inhoud niet te gebruiken en de afzender direct te informeren door het bericht te retourneren.
[cid:image002.gif@01D0F079.7F6D6850]Denk aan het milieu, print alleen als het echt nodig is.

**Comment by Alkarex** [comment]
@clainguf Ok. Do you remember which version you had before?

**Comment by clainguf** [comment]
Yes, it was 5.5.41

Met vriendelijke groeten / Meilleures Salutations / Best regards,

Yoni Smits
Chief executive officer
[cid:image001.jpg@01D25AE1.B7371EB0]<http://www.smitsbelgium.be/>

SMITS Belgium
Monnikenhofstraat 298
2040 ANTWERP



T. +32 3 292 67 67
T. +32 3 292 67 65
E. yoni@smitsbelgium.be<mailto:yoni@smitsbelgium.be>
I.  www.smitsbelgium.be<http://www.smitsbelgium.be/>


De informatie opgenomen in dit bericht kan vertrouwelijk zijn en is uitsluitend bestemd voor de geadresseerde. Indien u dit bericht onterecht ontvangt, wordt u verzocht de inhoud niet te gebruiken en de afzender direct te informeren door het bericht te retourneren.
[cid:image002.gif@01D0F079.7F6D6850]Denk aan het milieu, print alleen als het echt nodig is.

**Comment by Alkarex** [comment]
MySQL 5.5 fixed in https://github.com/FreshRSS/FreshRSS/pull/2672
