### ISSUE TITLE
Can't send mail using my own SMTP service.

### ISSUE THREAD

**Issue by fxzxmicah** [FreshRSS/FreshRSS#2674]
For some reasons, I can't use the services in the program to send mail, so I hope I can use custom SMTP to do this. Thanks.

**Comment by marienfressinaud** [comment]
Hello @fxzxmicah! Emails are only used to validate user addresses, is it what you want to do? If so, you'll have to follow the documentation here: https://github.com/FreshRSS/FreshRSS/blob/dev/docs/en/admins/05_Configuring_email_validation.md

Let me know if it's still don't work.

**Comment by fxzxmicah** [comment]
Well, the description of the document is not clear. For example, if I want to send a message with admin@a.com, the password is password, SMTP server is smtp.b.com, port 465, SSL is used, and the sender is Alice, how can I write it? @marienfressinaud

**Comment by marienfressinaud** [comment]
Indeed, the doc can be improved a bit on this. In your case, you'll have to update your `data/config.php` file and change (or add if they don't exist) these options:

```php
	'mailer' => 'smtp',
	'smtp' => array(
		'hostname' => 'a.com',
		'host' => 'smtp.b.com',
		'port' => 465,
		'auth' => true,
		'auth_type' => '',
		'username' => 'alice', // or maybe alice@a.com? But I think you have this info
		'password' => 'password',
		'secure' => 'ssl', // '', 'ssl' or 'tls'
		'from' => 'alice@a.com',
	),
```

Does it help?

**Comment by fxzxmicah** [comment]
Maybe my SMTP server is a little complicated. The SMTP server address is smtp.b.com, the login name is admin@a.com, and the corresponding password is password, but the sender is Alice, that is, the name to be displayed on the email address is Alice, so there is no alice@a.com @marienfressinaud

**Comment by marienfressinaud** [comment]
So just change the username by `admin@a.com` :wink:

**Comment by fxzxmicah** [comment]
OK, thanks for your help. There is another problem. I can't add an RSS source at https://www.cnbeta.com/backend.php. And I successfully added it to one of your test sites. Is it the database? I use SQLite. @marienfressinaud

**Comment by marienfressinaud** [comment]
Could you open another issue about this problem? it's better to organize (and find) information when we need to :) In this new issue, please provide relevant logs (if any) that you can find on the logs page (from the top-right menu)

**Comment by fxzxmicah** [comment]
Ok
