### ISSUE TITLE
Failed to add RSS address

### ISSUE THREAD

**Issue by fxzxmicah** [FreshRSS/FreshRSS#2676]
I can't add an RSS source at https://www.cnbeta.com/backend.php. And I successfully added it to one of your test sites. Is it the database? I use SQLite.
LOG: ' ' is not a valid URL.

**Comment by marienfressinaud** [comment]
I'm not sure how you can end up with a `' ' is not a valid URL.` while adding an URL unless you didn't fill the input. Are you sure it is not an old log?

I don't think it is the database since I can add it, even with a sqlite db.

**Comment by Frenzie** [comment]
To be clear, do you mean you can't add *any* feed or just this particular one?

**Comment by fxzxmicah** [comment]
It seems that this is a common problem, and I don't know where it is. I hope you can solve it as soon as possible. #2677 @marienfressinaud @Frenzie

**Comment by Frenzie** [comment]
So you can't add *any* feed?

**Comment by Alkarex** [comment]
This feed works for me. We would need a bit more information to debug the problem.
What platform (OS, version)? Did you check the write access of `./FreshRSS/data/*` ? Are you able to run a manual test from your server?

```sh
curl -v https://www.cnbeta.com/backend.php
```

**Comment by Alkarex** [comment]
@fxzxmicah Please try https://github.com/FreshRSS/FreshRSS/issues/2677#issuecomment-555727048

**Comment by fxzxmicah** [comment]
I use it on a virtual host and, yes, I can't add any RSS. The environment is PHP 7.1. If you do need phpinfo, I can give it to you later. In addition, there is a very strange question: where is the SQLite database? I can't find it. @Frenzie @marienfressinaud @Alkarex

**Comment by fxzxmicah** [comment]
Oh, OK, I'll try.

**Comment by fxzxmicah** [comment]
`checkUrl 1 http://feeds.feedburner.com/Clamav
checkUrl 2 http://feeds.feedburner.com/Clamav
checkUrl 3 http://feeds.feedburner.com/Clamav
idn_to_puny 1 http://feeds.feedburner.com/Clamav
Array
(
    [scheme] => http
    [host] => feeds.feedburner.com
    [path] => /Clamav
)


Notice:  Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed 'INTL_IDNA_VARIANT_UTS46' in /www/users/HA622438/WEB/tool/rsshub/p/test.php on line 13



Warning:  idn_to_ascii() expects parameter 3 to be integer, string given in /www/users/HA622438/WEB/tool/rsshub/p/test.php on line 13

idn_to_puny 2 http://feeds.feedburner.com/Clamav
idn_to_puny 3 http:///Clamav
checkUrl 4 http:///Clamav
checkUrl 6 http:///Clamav`
It seems that there are some problems. What should I do now?

**Comment by fxzxmicah** [comment]
`
checkUrl 1 http://feeds.feedburner.com/Clamav
checkUrl 2 http://feeds.feedburner.com/Clamav
checkUrl 3 http://feeds.feedburner.com/Clamav
idn_to_puny 1 http://feeds.feedburner.com/Clamav
Array
(
    [scheme] => http
    [host] => feeds.feedburner.com
    [path] => /Clamav
)


Notice:  Use of undefined constant INTL_IDNA_VARIANT_UTS46 - assumed 'INTL_IDNA_VARIANT_UTS46' in /www/users/HA622438/WEB/tool/rsshub/p/test.php on line 13



Warning:  idn_to_ascii() expects parameter 3 to be integer, string given in /www/users/HA622438/WEB/tool/rsshub/p/test.php on line 13

idn_to_puny 2 http://feeds.feedburner.com/Clamav
idn_to_puny 3 http:///Clamav
checkUrl 4 http:///Clamav
checkUrl 6 http:///Clamav
`
It seems that there are some problems. What should I do now?

**Comment by Alkarex** [comment]
Ok, same configuration bug than https://github.com/PrestaShop/PrestaShop/pull/11995
You should update your server accordingly, and we should add a mitigation in FreshRSS

**Comment by Alkarex** [comment]
I will make a patch tomorrow

**Comment by fxzxmicah** [comment]
Well, unfortunately, I use a virtual host, which is not controlled by me, so maybe I can't update the server. It's up to you to solve the problem. Good luck.

**Comment by Alkarex** [comment]
Please try this patch https://github.com/FreshRSS/FreshRSS/pull/2680
