### ISSUE TITLE
Instructions to complete database configuration

### ISSUE THREAD

**Issue by dwayneem** [FreshRSS/FreshRSS#2679]
I get 
**Blast! Verify your database information. : Access to database is denied for `freshrss` (`mysql:host=localhost;charset=utf8mb4`)**
attempting to complete the database configuration at Step 2)

I used (without changing the userid, database name, or password )
```
docker run -d --restart unless-stopped --log-opt max-size=10m \
  -v mysql-data:/var/lib/mysql \
  -e MYSQL_ROOT_PASSWORD=rootpass \
  -e MYSQL_DATABASE=freshrss \
  -e MYSQL_USER=freshrss \
  -e MYSQL_PASSWORD=pass \
  --net freshrss-network \
  --name mysql mysql
```
to create a MySQL instance

what should I put in each of the fields for the database configuration (step 2)
```
Type of database MySQL
Host:  ????
Database username  freshrss
Database password   pass
Database freshrss
Table prefix ???
```

**Comment by dwayneem** [comment]
Same problem occurs if I do a normal install without docker.

In this case I m making the following assumptions:
**Host** should be localhost
**Database username** should be the username specified with:
CREATE USER 'username'@'localhost' IDENTIFIED BY 'userpassword';
**Database password** is  'userpassword' (from above CREATE USER command)
**Database** is the name of the database as specified in the CREATE DATABASE command
CREATE DATABASE `freshrssdb`;

I had also done
GRANT ALL privileges ON `freshrssdb`.* TO 'username'@localhost;
FLUSH PRIVILEGES;

I tried with **Table prefix** blank and as "freshrss_"

**Comment by Alkarex** [comment]
Using Docker:

```
#create shared network
docker network create freshrss-network

#create database storage and database instance
docker volume create mysql-data
docker run -d --restart unless-stopped --log-opt max-size=10m \
  -v mysql-data:/var/lib/mysql \
  -e MYSQL_ROOT_PASSWORD=freshrss \
  -e MYSQL_DATABASE=freshrss \
  -e MYSQL_USER=freshrss \
  -e MYSQL_PASSWORD=freshrss \
  --net freshrss-network \
  --name mysql mysql

#Create FreshRSS storage and FreshRSS instance
docker volume create freshrss-data
docker run -d --restart unless-stopped --log-opt max-size=10m \
  -v freshrss-data:/var/www/FreshRSS/data \
  -e 'CRON_MIN=4,34' \
  -e TZ=Europe/Paris \
  --net freshrss-network \
  --name freshrss freshrss/freshrss
```

Then you can pick *MySQL* as database type, *mysql* as host, *freshrss* as username, *freshrss* as password, *freshrss* as database, nothing for table prefix

**Comment by rhazegh** [comment]
For anyone out there having problems with the latest mysql version:
  - Using mysql:8.0.23 image from Docker hub, there were authentication issues when configuring FreshRSS for the first time.
  - Using mysql:5.7 resolved the issue.

**Comment by Alkarex** [comment]
@rhazegh Our current master branch with PHP8 and our Docker image `freshrss/freshrss:alpine` also work with MySQL 8.

**Comment by rhazegh** [comment]
@Alkarex Thanks for pointing it out. That’s good to know. 

I had used freshrss/freshrss:1.17.0 since that was the latest label available on docker hub. 

I tend to almost always use specific versions of docker images (rather than the one labeled latest) to ensure I can always replicate a setup.

**Comment by Alkarex** [comment]
@rhazegh We will soon have more tag options for our Docker images. However, you can already now use explicit hashes for the images, which are more robust than tags (which might change) when it comes to have strictly replicable setups.
