### ISSUE TITLE
Updated feed items, their hashes and extensions

### ISSUE THREAD

**Issue by kour1er** [FreshRSS/FreshRSS#2688]
If my understanding is correct: when a feed item is updated, that is to say a previously posted item receives new content, an updated hash is created in the database --- reflecting a difference in the feed item.

In the context of an extension, this updated hash item will appear again when using entry_before_insert as the item is, in effect new. Would it be possible to provide to the extension an indication that this is an old updated item, rather than an entirely new one?

**Comment by Alkarex** [comment]
Currently, we emit the `entry_before_insert` event both for new articles (`INSERT`) and modified articles (`UPDATE`). We should differentiate the two cases.
Right now, there is an undocumented trick:
```php
if (entry->id() == null) {
	//updated article
} else {
	//new article
}
```

**Comment by math-GH** [comment]
Is here anything left todo?

**Comment by kour1er** [comment]
The undocumented trick is working great for me - cheers
