### ISSUE TITLE
Extensions and handleConfigureAction

### ISSUE THREAD

**Issue by kour1er** [FreshRSS/FreshRSS#2689]
The documentation mentions that handleConfigureAction() is called when a user loads the extension management panel.

This doesn't always appear to be the case (unless I'm missing something obvious :). For example, in the Custom CSS extension, if I add something to the "Additional CSS rules" text area, click submit, the click to the left to dismiss the panel, then click the manage button again, the old data is in the text area. You can tell that the correct data has actually been saved by looking at the data saved to disk. 

handleConfigureAction appears to only be called again if either you manually reload the whole page, or you click manage on a different extension, then click back onto the original extension.

Curiously, if you call the log function within the particular handleConfigureAction() i.e. Minz_Log::warning("log something"); handleConfigureAction appears to be called every time the Manage button is clicked.

 A minor weird thing but I thought I should mention it in case anyone else sees the behaviour

**Comment by aledeg** [comment]
@kour1er Is this still the case? I cannot reproduce the behavior you described.

**Comment by kour1er** [comment]
@aledeg Just ran some tests. It does indeed appear to be fixed! How odd - I wonder what changed :) Thanks for checking into this, it was driving me crazy!
