### ISSUE TITLE
Add a button to purge all users articles

### ISSUE THREAD

**Issue by adaigre** [FreshRSS/FreshRSS#2691]
Hi there !

It would be nice if we could have a second purge button who apply to all users of the instance.
I share my FreshRSS with a friend and I have to ask him every time I want to clean the database.

Thanks again for your great work !

**Comment by aledeg** [comment]
Please check #2417. This might help you achieve what you want to do.
Comments are welcomed.

**Comment by adaigre** [comment]
Seems like a great update, looking forward to see that !

**Comment by aledeg** [comment]
@adaigre It's been quite some time that #2417 has been release. Does this fulfill what you envisioned?
