### ISSUE TITLE
Application problem after login

### ISSUE THREAD

**Issue by DanielVibuso** [FreshRSS/FreshRSS#2692]
Hello,
I'm trying put the system on my server, but when I'm doing the login int the system, he show me this error : 

> ### Application problem ###
> Permission is denied for `/var/www/html/JCANEWS/data/users/administrador/log.txt`

I tried solve this with the steps of this topic : https://github.com/FreshRSS/FreshRSS/issues/1825
But it doesn't worked to me.

Can someone tell me how can I solve this problem?

**Comment by Alkarex** [comment]
Hello,
What is the output of the following command?

```sh
ls -alh /var/www/html/JCANEWS/data/users/administrador/
```

What Web server do you use, on which platform?

**Comment by DanielVibuso** [comment]
@Alkarex Hello!

This is the output of the command:

> total 640K
> drwxrwxr-x 2 root www-data 4.0K Nov 28 17:02 .
> drwxrwxr-x 8 root www-data 4.0K Nov 28 17:03 ..
> -rw-rw-r-- 1 root www-data 2.4K Nov 28 17:02 config.php
> -rw-rw-r-- 1 root www-data 2.4K Nov 28 17:02 config.php.bak.php
> -rw-rw-r-- 1 root www-data 624K Nov 29 07:09 log.txt


My server is ubuntu 18.10, is an VPS on Digital Ocean.

**Comment by Alkarex** [comment]
This looks fine. Have you tried to refresh the page?

**Comment by DanielVibuso** [comment]
> This looks fine. Have you tried to refresh the page?

@Alkarex Oh I tried it now, but have a new error message

> ### Application problem ###
See logs files

**Comment by DanielVibuso** [comment]
I See! 
The problem was refer to mysql user, that I need change from "root" to my mysql user.
Thank you!
