### ISSUE TITLE
[Wiki] Upgrade to 1.15.3 - “database disk image is malformed”

### ISSUE THREAD

**Issue by Sp3r4z** [FreshRSS/FreshRSS#2693]
Hello

After a migration from 1.15.2 to 1.15.3, my FreshRSS didn't update feeds, I've seek into logs, and this message appeared `FreshRSS_EntryDAO::cleanOldEntries error:["HY000",11,"database disk image is malformed"]`. It's not the first time on migration/upgrade.

I've solved this issue with : 
1. Open malformed database
    - `sqlite3 db.sqlite` (*/[PATH_TO_FRESHRSS]/data/users/[USER]/db.sqlite*)
1. `PRAGMA integrity_check;`
1. Some integrity problems are shown (it confirms FreshRSS logs)
1. Dumping database
    - `sqlite> .mode insert`
    - `sqlite> .output dump.sql`
    - `sqlite> .dump`
1. Open a new database file
    - `sqlite3 clean_db.sqlite`
1. rewrite dump in new database
    - `sqlite> .read dump.sqlite`
Maybe we should add this to WIKI or something, just to help people with the same problem, solving it.

Thanks for attention.

**Comment by thestupidestthing** [comment]
This info just saved my FreshRSS install! Thanks.
