### ISSUE TITLE
Help me with migration

### ISSUE THREAD

**Issue by Legalien** [FreshRSS/FreshRSS#2696]
So I use Freshrss on my hosting with cPanel. Today I changed my hosting and I tried to migrate.

I zipped up and downloaded my Freshrss folder, and I downloaded my SQL database.

Then I uploaded and unzipped my Freshrss folder in the new hosting, I created sql database and user, I uploaded the SQL file, and I changed some info in the config file.

Unfortunately that didn't work. Upon visiting the site I got:

**Application problem
See logs files**

In log files I had:

[Sat, 30 Nov 2019 18:12:52 -0600] [error] --- Access to database is denied for `user_freshrssu` (`mysql:host=27.0.0.1;dbname=user_freshrss;charset=utf8mb4`)

Okay, I didn't expect that to work, but it was worth a shot.

...

So I decided to install a fresh version of Freshrss. Anyway the version I was using was over 1+ year old, and I'm sure there were some updates in the meantime, so I installed the latest version of Freshrss which I downloaded from here - https://freshrss.org/

The version I had was 2.84MB, and the version I downloaded is 3.94MB, so it's surely a more recent version than what I had.

...

Now, I have my old Freshrss files and I have my old sql databases. Is there a way for me to "import" my old settings and feeds and everything?

Thanks :)

**Comment by Legalien** [comment]
So I think I figured it out.

First I went to phpMyAdmin and "dropped" each of the tables. I did it by clicking "SQL" on top of the page, and running this for each table:

**DROP TABLE table_name;** 

Then I imported my previous SQL file, and renamed each of the tables with this:

**ALTER TABLE exampletable RENAME TO new_table_name;**

I had to rename because the prefix changed from my old hosting to my new hosting.

After I did that, All of my old feeds and things were back in Freshrss 👍 

Then I also had to do a few more things, like in Authentication enable:

**Allow anonymous reading of the articles of the default user**
**Allow anonymous refresh of the articles** 

And also in Archiving change "**Do not automatically refresh more often than**" to 30 minutes.

And also (and I have no idea why you guys did this, but it sucks and you should change it) I noticed articles from my feeds disappearing. After a few minutes I realized they disappear after I click them, or after they're marked as read. So I had to go into "Reading" and untick:

**Hide categories & feeds with no unread articles (does not work with “Show all articles” configuration)** 

I don't know why you guys made this be the default, but it's dumb and it confused me and you should change it. Articles should not disappear if read by default, it should be an option sure, but not the default.

So anyway, I continue now to see if my feeds are working and what other settings I may have forgotten, and then to set the cron. I'll ask if I have any other problems.

And if you guys think of anything I may have missed, do tell :)

**Comment by Legalien** [comment]
Oh no... it's still hiding articles that I open, but not on all feeds.

Why is this happening?

**Comment by Legalien** [comment]
Okay okay.

**Reading -> Articles to display -> Show all articles**

Fixed :)

**Comment by aledeg** [comment]
Thank you for your step by step migration description.

**Comment by Legalien** [comment]
Great. Thanks :)

**Comment by Alkarex** [comment]
For the record, I suggest using [`./cli/export-sqlite-for-user.php`](https://github.com/FreshRSS/FreshRSS/blob/dev/cli/README.md) for migrations

**Comment by Legalien** [comment]
Guys, I have a problem. Yesterday I set things up and it was working and then it was finished.

Now I try to visit Freshrss, and I get this error:

**Fatal error: Arrays are not allowed as constants in /home2/user/public_html/FreshRSS/lib/lib_rss.php on line 563**

Any ideas what is the problem?

**Comment by Frenzie** [comment]
I believe that would be related to the minimum requirements:

> PHP 5.6+ (PHP 7+ recommended for higher performance)

Arrays as constants are a PHP 5.6 feature.

**Comment by Legalien** [comment]
Yes, that did it. You're the man always! Many thanks 😄
