### ISSUE TITLE
get_magic_quotes_gpc() is deprecated in PHP 7.4

### ISSUE THREAD

**Issue by candrews** [FreshRSS/FreshRSS#2697]
PHP 7.4 has deprecated `get_magic_quotes_gpc()`:
https://www.php.net/manual/en/function.get-magic-quotes-gpc.php
https://www.php.net/manual/en/security.magicquotes.php

FreshRSS uses this function, resulting in this warning when running `actualize_script.php`:
```
PHP Deprecated:  Function get_magic_quotes_gpc() is deprecated in /var/www/localhost/htdocs/FreshRSS/lib/Minz/Request.php on line 303
```

**Comment by aledeg** [comment]
I'll add that magicquotes are deprecated since PHP 5.4. It's time to make some cleaning.

**Comment by Alkarex** [comment]
We should just delete the `magicQuotesOff()` function

**Comment by Frenzie** [comment]
Yup, apparently completely obsolete since 5.4. Good riddance. ;-)

**Comment by Alkarex** [comment]
Fixed by https://github.com/FreshRSS/FreshRSS/pull/2698
