### ISSUE TITLE
caching favicons

### ISSUE THREAD

**Issue by rezad1393** [FreshRSS/FreshRSS#2711]
can favicons be cached so that they dont get downloaded alot?

alot of messages like this appear in my php-fpm log
FreshRSS Favicon GET https://github.githubassets.com/favicon.ico

**Comment by aledeg** [comment]
@rezad1393 I am pretty sure favicons are cached. Do you still see those logs? Is this still relevant?

**Comment by rezad1393** [comment]
`Feb 16 18:51:25 odroid FreshRSS[16229]: FreshRSS Favicon GET https://www.cyberciti.biz
Feb 16 18:51:26 odroid FreshRSS[31305]: FreshRSS Favicon GET http://esr.ibiblio.org
Feb 16 18:51:28 odroid FreshRSS[16229]: FreshRSS Favicon GET https://www.cyberciti.biz/cms/wp-content/themes/thesis/lib/images/favicon.ico
Feb 16 18:51:31 odroid FreshRSS[31305]: FreshRSS Favicon GET http://esr.ibiblio.org/favicon.ico
Feb 16 18:51:34 odroid FreshRSS[26074]: FreshRSS Favicon GET https://www.bitchute.com/static/v130/images/android-icon-192x192.png
Feb 16 18:51:35 odroid FreshRSS[13775]: FreshRSS Favicon GET https://www.bitchute.com/static/v130/images/android-icon-192x192.png
Feb 16 19:00:56 odroid FreshRSS[31307]: FreshRSS Favicon GET https://pbfcomics.com/
Feb 16 19:01:11 odroid FreshRSS[31307]: FreshRSS Favicon GET https://pbfcomics.com/wp-content/themes/PBF/images/favicon.png
`
so yes. they are still downloaded.

**Comment by aledeg** [comment]
Do you know how often this occurs?

**Comment by aledeg** [comment]
After digging in the code, this must occurs every time your feed is refreshed. That means that its a server process <del>(except if you refresh your feed from the interface)</del>. I guess this is not a real concern but I might be wrong. Let me know what you think!

**Comment by Alkarex** [comment]
Favicons are periodically refreshed from the original feed server, but only every two weeks when refreshing by cron:
https://github.com/FreshRSS/FreshRSS/blob/b3340c32e38e7a4e39a9ac66e3d925386c202390/app/Models/Feed.php#L152-L173

or randomly between 15 and 20 days if the cron did not refresh them already:
https://github.com/FreshRSS/FreshRSS/blob/b3340c32e38e7a4e39a9ac66e3d925386c202390/p/f.php#L27-L44

The rest of the time, a local server cache is served, supplemented by client-side HTTP cache.

However, if the same favicon is fetched more frequently, that is a sign of bad server setup, for instance with write-access issue in `./data/favicons/`

**Comment by math-GH** [comment]
I guess we will not change it, does it?
