### ISSUE TITLE
solved:log of urls that are checked?

### ISSUE THREAD

**Issue by rezad1393** [FreshRSS/FreshRSS#2712]
I thought that simplepie log would show the urls of feeds being checked but it only shows favicons request or when I manually update a feed (the confusing "Actualize" button or the refresh button from main page) .
how can I get the curl access log or something like that and not just for errors but for all the urls checks (All updates that are done via cron update)

UPDATE: nevermind 
it was found in php log ot seems

**Comment by Alkarex** [comment]
Yes, this information is logged through PHP's syslog() call.
In our official Docker image, this is directly visible in the Docker logs.
