### ISSUE TITLE
Misleading switch to blog view

### ISSUE THREAD

**Issue by nical** [FreshRSS/FreshRSS#2714]
Sorry about the the hand-wavy title. When clicking close to an article title but on the column that contains the blog name, freshrss takes you to the list of the articles from that particular source.

![Screenshot from 2019-12-10 14-51-27](https://user-images.githubusercontent.com/264854/70536152-80ccc280-1b5e-11ea-8074-65e644aca7d4.png)

For example in the image above clicking where the cursor is drawn takes you to the list of articles coming from Planet GNOME

This in itself isn't necessarily an issue, however it took me an absurd amount of time to understand that often when clicking very close to the blog title I be would taken to this view, not because of some bug, but because I was actually clicking in the column of the blog names (the blog name being quite a bit further on the left).

It seems obvious in hindsight. I think that what put me in this frame of mind was that the entire row is highlighted when the cursor hovers over it regardless of whether clicking will take you to the article or the blog's article list.

If the visual feedback when hovering the area that takes you to the blog's article list was more explicit (for example by highlighting the blog's title), would (in my humble opinion) lead to less confusion.

I confess that months after figuring out why some clicks were not taking me to where I expected, I still get it wrong sometimes (due to how close to the article title clickable area leading to the blog is).

**Comment by Frenzie** [comment]
Funny, I had almost the exact opposite experience. :-)

**Comment by Frenzie** [comment]
For this particular theme, you'd probably want something like this (except not yellow):
```css
.flux .item:hover {
    background: yellow;
}
```
