### ISSUE TITLE
About directory structure

### ISSUE THREAD

**Issue by fxzxmicah** [FreshRSS/FreshRSS#2715]
I don't quite understand why index.php should be placed so deep in the directory, and it's not easy to access. Why not put it in the root directory?

**Comment by marienfressinaud** [comment]
You can find some explanations in the FAQ: https://github.com/FreshRSS/FreshRSS/blob/dev/docs/en/users/07_Frequently_Asked_Questions.md#what-is-i-at-the-end-of-the-application-url

Why would you have an easy access to it?

**Comment by Alkarex** [comment]
@fxzxmicah In a properly deployed FreshRSS, the landing page is `https://freshrss.example.net/` with an auto-redirection to `https://freshrss.example.net/i/` (for the Web version). Having a subdirectory for credential-protected resources is quite common (e.g. `https://mail.google.com/mail/`), leaving the root for public logic.

Note: you should avoid having the `/p/` appear in your URL (cf. documentation).

Let us know whether that answers your question
