### ISSUE TITLE
question: Cookies

### ISSUE THREAD

**Issue by b1n4ryj4n** [FreshRSS/FreshRSS#2716]
Hi is it possible to use an specific cookie for an rss feed? 
Because i have a feed that works only if im logged in.

Is there a way to set a cookie with a extension for this url via $simplePie ?

**Comment by aledeg** [comment]
No, you can,t. But you can set an HTTP user and an HTTP password on the feed configuration page.

**Comment by marienfressinaud** [comment]
HTTP credentials are only useful for `htpassword`-protected feeds. It's this kind of protected pages:

![Capture d’écran de 2019-12-11 12-00-48](https://user-images.githubusercontent.com/1436309/70616137-11aea700-1c0e-11ea-8fc9-1b8a900adb11.png)

If it's not this kind of protection, I don't see why the feed exists. I think no RSS aggregator is able to fetch it, it's barely useless :thinking:

**Comment by Alkarex** [comment]
@b1n4ryj4n You are welcome to share the feed link, but indeed, if it uses some kind of Web-form login, it would require some custom code (an extension could do it)
