### ISSUE TITLE
Internal server error when configuring mysql database in docker container

### ISSUE THREAD

**Issue by simonszu** [FreshRSS/FreshRSS#2717]
I have a dedicated database server which is accessible from the docker host (a mysql command line operation is successful). I want to run FreshRSS via Docker on the docker host, and let it use the database server.

I have started the docker container, and try to run the installation wizard. I select MySQL as the database backend, enter the credentials, and get an "Internal Server error". This is not very helpful when trying to track down the root of the error, so i am creating this ticket. 

Additional information:
- FreshRSS version: Docker tag `latest` from today
- MySQL version: mariadb-server-10.3 - 1:10.3.18-0+deb10u1 from debian stable. 
- Server OS: Debian Linux
- Related log files: Nothing in the `log.txt`, but `docker logs` shows this:
```
172.19.1.16 - - [12/Dec/2019:11:24:49 +0100] "GET /i/?step=1 HTTP/1.1" 200 1452 "https://rss.simonszu.de/i/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0"
172.19.1.16 - - [12/Dec/2019:11:24:52 +0100] "GET /i/?step=2 HTTP/1.1" 200 1388 "https://rss.simonszu.de/i/?step=1" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0"
```

**Comment by Alkarex** [comment]
Sorry for the delay. I hope you found a solution.
In FreshRSS 1.16.0 - which is just about to be released - there is a more informative error message in case of database problem https://github.com/FreshRSS/FreshRSS/pull/2734
Please feel free to reopen an issue if you still encounter a bug
