### ISSUE TITLE
FreshRSS automatic update not working anymore after running Ubuntu updates

### ISSUE THREAD

**Issue by atengesdal** [FreshRSS/FreshRSS#2719]
Hi,

My FreshRSS has been working flawlessly for almost a year until I discovered it was time to do an update on the Ubuntu system (apt-get update and apt-get upgrade). Some 300 patches or so and a reboot was needed. After this I am no longer able to get automatic feed updating as I had before. I checked the crontab and it was empty. Followed the guideline and did "crontab -e" as root:
10 * * * * www-data php -f /usr/share/FreshRSS/app/actualize_script.php > /tmp/FreshRSS.log 2>&1
is added.

When I check the FreshRSS.log file I get this:
root@lubuntu:/home/arve# more /tmp/FreshRSS.log 
/bin/sh: 1: www-data: not found
Ensuring the www-data user is there,

root@lubuntu:/home/arve# cut -d: -f1 /etc/passwd
root
daemon
bin
sys
sync
games
man
lp
mail
news
uucp
proxy
www-data
.. and so on

Ubuntu version
OS: Ubuntu 18.04.3 LTS i686

Please note, I am not an experienced user of Linux, just basics so please bear with me :)

//Arve

**Comment by atengesdal** [comment]
Forgot to add that manual update of FreshRSS via webGUI works fine so the update is working.

**Comment by atengesdal** [comment]
Trying to run the script manually:
arve@lubuntu:/usr/share/FreshRSS/app$ ./actualize_script.php 
Starting feed actualization at 2019-12-17T12:27:37+01:00
FreshRSS install failed requirements:
• data
• cache
• users
• favicons
• ok

**Comment by ColasNahaboo** [comment]
> Followed the guideline and did "crontab -e" as root:
> 10 * * * * www-data php -f /usr/share/FreshRSS/app/actualize_script.php > /tmp/FreshRSS.log 2>&1

This syntax (having the user "www-data" specified is not the syntax to be used in crontab, it is the syntax for files in the `/etc/cron.d/` directory.

You should either:

1. put your line in a `/etc/cron.d/freshrss` file
2. put the same line without the www-data in the crontab of www-data (crontab -u www-data -e). Caveat: not all Ubuntu setups allow this (using the www-data account directly) by default.

**Comment by ColasNahaboo** [comment]
> Trying to run the script manually:
> arve@lubuntu:/usr/share/FreshRSS/app$ ./actualize_script.php

This will fail because you are trying to run freshRSS under your account, not the web server one ("www-data")

**Comment by aledeg** [comment]
@atengesdal Is this still relevant?

**Comment by atengesdal** [comment]
No
