### ISSUE TITLE
Add make lint and make test targets

### ISSUE THREAD

**Issue by marienfressinaud** [FreshRSS/FreshRSS#2722]
While I was working on https://github.com/FreshRSS/FreshRSS/pull/2721, I tried to add a `make lint` and a `make test` targets but I don't know what could be the best solution. I wanted to run them in Docker since I don't have PHP installed directly on my machine and to ease contributions, but we need to install PHPUnit and PHP_CodeSniffer first. I see 4 options:

- since these programs are each contained in a single file, we could add them to the repository and add simple targets like that:
```makefile
.PHONY: test
test: ## Run the test suite
       docker run \
               --rm \
               --volume $(shell pwd):/var/www/FreshRSS:z \
               --env FRESHRSS_ENV=test \
               --name freshrss-test \
               freshrss/freshrss:$(TAG) \
               php ./bin/phpunit --bootstrap ./tests/bootstrap.php ./tests
```

I don't like this solution because admins would download those files while it's only necessary for developers. Also, Alpine image doesn't work because it misses Phar extension. And it's a lot of new lines not related to FRSS!

- second option is to create a dedicated Docker image containing the programs used in test mode, maybe lighter and based on a PHP image instead of a FreshRSS one
- introduce Composer so we add it to the FRSS images and we can use it to install PHPUnit and PHP_CodeSniffer
- last option is to keep things as they are and let people install the programs by themselves. It's a bit unfriendly for newcomers

I see no "perfect" solutions and each has its drawbacks. Maybe someone can enlight my thougts? :)

**Comment by Frenzie** [comment]
> second option is to create a dedicated Docker image containing the programs used in test mode, maybe lighter and based on a PHP image instead of a FreshRSS one

I'm mostly in favor of that one if you don't see much added value in testing multiple PHP versions. Admittedly the image is very small and even double the size will still be very small, but it's just a bunch of cruft for deployment scenarios. You could just take the deployment image and add a dev layer or something.

Besides making development slightly easier, doing so also facilitates migration from Travis to another equivalent CI system.

**Comment by Alkarex** [comment]
Very quick feedback without having thought about it much:
* In Alpine, adding the PHAR extension would not cost that much https://pkgs.alpinelinux.org/package/edge/community/x86_64/php7-phar
* Can't we have a pre-test rule that downloads the needed files if they do not already exist?

**Comment by marienfressinaud** [comment]
> Can't we have a pre-test rule that downloads the needed files if they do not already exist?

Do you mean in the Makefile? I'd like to avoid an hidden mechanism which install things in the back of developers. But with an explicit rule, it provides an alternative to option 1that I quite like indeed :+1:

Providing a Docker image for testing purposes based on an existing FRSS one would not take a lot of time indeed, and with the cache system it would cost almost no more space.

I'll start with option 1 amended with suggestions, and, if not satisfied, will work on option 2.
