### ISSUE TITLE
Docker: Environment variables for database instance

### ISSUE THREAD

**Issue by intmainreturnzero** [FreshRSS/FreshRSS#2724]
In the README.md, it is suggested to simply link an existing MySQL or PostgreSQL instance via `--link` command, however, when the container is stopped and started, it falls back to installation wizard and we have to enter the database credentials once again interactively.

This is not helpful in cases where automated container upgrades are set up (e.g. with watchtower). There should be environment variable support like most other web service containers provide accepting database host, database user, database password and database name environment variables.

**Comment by Alkarex** [comment]
Hum, I do not think we mention `--link` anywhere, do we?
The database information is kept between container restarts if you follow the suggested deployment with the `frehrss-data` volume https://github.com/FreshRSS/FreshRSS/tree/master/Docker#run-freshrss

**Comment by marienfressinaud** [comment]
Maybe the `data/do-install.txt` is recreated? You should make sure to remove it after an update (I plan to change this system)

**Comment by Alkarex** [comment]
See an implementation in https://github.com/FreshRSS/FreshRSS/pull/3353
