### ISSUE TITLE
Installing with postgresql ignores database name

### ISSUE THREAD

**Issue by PetraOleum** [FreshRSS/FreshRSS#2732]
I tried to install with postgresql username 'nginx' and database name 'freshrss' (through the web interface), but it wouldn't work: the error given in the web interface was unhelpful, implying that the user nginx was denied access, but looking at the postgres logs I got `nginx@nginx FATAL:  database "nginx" does not exist`. Trying it all again with the username and database name matching worked. Guessing there's a mistake in the code where the username is used for the database name and the database name entered is dropped?

(Apologies for the poorly documentation — I only realised I should tell you about this after I had finished the installation)

**Comment by Alkarex** [comment]
@PetraOleum Thanks for the bug report. If you can, could you please try this fix? https://github.com/FreshRSS/FreshRSS/pull/2735
