### ISSUE TITLE
visibility "show in its category" doesn't work 

### ISSUE THREAD

**Issue by user858753257** [FreshRSS/FreshRSS#2736]
For me this option isn't working:

Where should I see a change after editing this option ?

<img width="1306" alt="Bildschirmfoto 2019-12-28 um 22 54 34" src="https://user-images.githubusercontent.com/8161283/71549887-85e69a00-29c5-11ea-98e9-1525fa0496be.png">

**Comment by Alkarex** [comment]
Do you mean in the Web interface, or in a mobile client?

**Comment by user858753257** [comment]
@Alkarex  I mean in the web interface

**Comment by Alkarex** [comment]
Works fine for me. This options hides corresponding articles in the main view. Articles are then only visible when showing the specific category or feed.
