### ISSUE TITLE
feature request for fever api: rename feeds over mobile apps

### ISSUE THREAD

**Issue by user858753257** [FreshRSS/FreshRSS#2738]
like the previous issue . At the moment I can't do that via Fiery Feeds (or over API in general)

**Comment by Alkarex** [comment]
FreshRSS supports that through the Web interface and the Google Reader API.
I do not believe the Fever API exposes this feature https://feedafever.com/api so for more advanced features, it should be via the Google Reader API instead of through the Fever API.
