### ISSUE TITLE
feature request for fever api: tagging of articles over mobile apps not possible

### ISSUE THREAD

**Issue by user858753257** [FreshRSS/FreshRSS#2741]
on your website this is possible "my labels" . But in mobile app until now not  possible

**Comment by Alkarex** [comment]
FreshRSS supports that through the Web interface and the Google Reader API.
I do not believe the Fever API exposes this feature https://feedafever.com/api so for more advanced features, it should be via the Google Reader API instead of through the Fever API.

**Comment by user858753257** [comment]
@Alkarex 

Hmm that’s curios . 

Some weeks ago I have tested Tiny Tiny RSS and also added this service via the fever api into my mobile client . 


Here it is possible for example to add new feeds through the app and I can see it on the webui too .
