### ISSUE TITLE
Can't add a new feed over the mobile website 

### ISSUE THREAD

**Issue by user858753257** [FreshRSS/FreshRSS#2744]
Hi @Alkarex 

I can use all function from the desktop page also on the mobile version except adding a new feed. 

Can you tell me where I can do this ? 

![IMG_0549](https://user-images.githubusercontent.com/8161283/71562274-9f4c1c80-2a7f-11ea-8fe8-588348ecd9c0.jpeg)

**Comment by aledeg** [comment]
Linked to:

- [Mobile : No access to parameters · Issue #1876 · FreshRSS/FreshRSS](https://github.com/FreshRSS/FreshRSS/issues/1876)
- [Show menu on mobile & other tweaks by PhieF · Pull Request #1929 · FreshRSS/FreshRSS](https://github.com/FreshRSS/FreshRSS/pull/1929)

**Comment by math-GH** [comment]
it is already solved:
![grafik](https://user-images.githubusercontent.com/1645099/132404633-105c9b51-fac2-4f09-9966-9fab8c47485e.png)
