### ISSUE TITLE
FreshRSS article much shorter than in raw RSS feed

### ISSUE THREAD

**Issue by kaiengelhardt** [FreshRSS/FreshRSS#2750]
Hi FreshRSS community,

I recently set up my own FreshRSS instance on my Synology disk station and am very satisfied with the features and speed of it. However I have a problem with one of my feeds, where the articles shown inside FreshRSS, are much shorter than the articles in the raw RSS feed.

I attached two screenshots. The first shows what I see in FreshRSS. The article here "The Decade of Swift" is only four lines long. In the second screenshot you can see the raw RSS of this website. The same article spans multiple pages in the raw data.

Is this a bug in FreshRSS or am I missing a setting? Other feed readers I tried don't have this problem and show the full articles for this site.

Here's my technical setup:
FreshRSS running on a Synology DSM 916+ backed by a PostgresSQL database.

The affected RSS feed is https://www.swiftbysundell.com/feed.rss

Thanks in advance for your help!

Kai

![What FreshRSS is showing](https://user-images.githubusercontent.com/966076/71660575-c9d1fa00-2d4b-11ea-9468-88f142501048.png)

![What the RSS feed actually has](https://user-images.githubusercontent.com/966076/71660577-c9d1fa00-2d4b-11ea-9031-25dfd300d15b.png)

**Comment by Frenzie** [comment]
Afaik content is Atom, not RSS, making that element meaningless decoration.

The validator doesn't seem to complain about it though:
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.swiftbysundell.com%2Ffeed.rss

It goes back to SimplePie:
https://www.simplepie.org/demo/?feed=https%3A%2F%2Fwww.swiftbysundell.com%2Ffeed.rss

**Comment by kaiengelhardt** [comment]
Oh, now I see that it is an Atom feed. So FreshRSS is taking the text from the description-tags. Is there anything I can do about this, so that FreshRSS takes the text from the content:encoded-tags?

**Comment by Frenzie** [comment]
It's an RSS feed alright; it's just creatively mixing in Atom parts.

I doubt you can do anything about it without writing an extension. It seems more fruitful to tell the website to fix their broken feed.

**Comment by kaiengelhardt** [comment]
I see, thank you for you help!
