### ISSUE TITLE
 You don’t have permission to access this page

### ISSUE THREAD

**Issue by ishanjain28** [FreshRSS/FreshRSS#2752]
I installed FreshRSS from the latest docker image, Specifically `freshrss/freshrss:alpine`. 

I have checked few similar issues here, #1779 #1224 #960 and I have tried the methods suggested in some of those issues(Like, Changing Authentication to None in config.php, Changing password and then changing it back to form) but none of this has resolved the problem for me.

When I login via the web dashboard, I get the error message and see this in logs. 

```
FreshRSS[283]: [ishan] [Sun, 05 Jan 2020 00:05:49 +0530] [warning] --- Password mismatch for user=ishan, nonce=19dde07fcecf6487138cece5d8039814f6e14008, c=
172.17.0.1 - - [04/Jan/2020:18:35:49 +0000] "POST /i/?c=auth&a=login HTTP/1.0" 403 4251 "-" "Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0"
```

I am 100% sure I am entering the right password but I am still seeing this message in container logs. So, I am not sure what exactly is going wrong here. :/

**Comment by ishanjain28** [comment]
Something doesn't look right here. The `challenge` field is empty. 

```sh
curl 'https://freshrss.xyz/i/?c=auth&a=login --data '_csrf=1aebf9d970e136c429120e224a0f7c9dfab1ed10&username=ishan&challenge='
```

Checking the Login page, 

```html
<form id="crypto-form" method="post" action="./?c=auth&amp;a=login">
		<input type="hidden" name="_csrf" value="5564b71bba9e57e6268756ab51b4ea746946b7e8"/>
		<div>
			<label for="username">Username</label>
			<input type="text" id="username" name="username" autocomplete="username" size="16" required="required" pattern="([0-9a-zA-Z_][0-9a-zA-Z_.@-]{1,38}|[0-9a-zA-Z])" autofocus="autofocus"/>
		</div>
		<div>
			<label for="passwordPlain">Password</label>
				<input type="password" id="passwordPlain" required="required"/>
				<input type="hidden" id="challenge" name="challenge"/><br/>
				<noscript><strong>JavaScript must be enabled</strong></noscript>
		</div>
		<div>
			<label class="checkbox" for="keep_logged_in">
				<input type="checkbox" name="keep_logged_in" id="keep_logged_in" value="1"/>
				Keep me logged in <small>(30 days)</small>			</label>
			<br/>
		</div>
		<div>
			<button id="loginButton" type="submit" class="btn btn-important">Login</button>
		</div>
	</form>
```

If I enter a value in `password` field, The value goes in input with id `passwordPlain`. 

Since, No name attribute was given to this input, When I submit the form, The values that gets sent are, `_csrf`, `username` and `challenge` but there is nothing in `challenge` and there is no `password`. So, I keep getting 403. :/

**Comment by Alkarex** [comment]
Hello,
Could you please tell a bit more about your setup? In particular, do you have any reverse proxy in front?

**Comment by ishanjain28** [comment]
The FreshRSS is spawned from the Docker image, `freshrss/freshrss:alpine`. 

It sits behind an NGINX proxy. 

<details>
<summary>NGINX reverse proxy configuration file</summary>

    server {
      listen ipv4addr:443 ssl http2;
      listen ipv6-addr:443 ssl http2;
      server_name rss.ishanjain.me;

      include snippets/ssl_config.conf;
      include snippets/letsencryptauth.conf;
      include snippets/security_headers.conf;

      ssl_certificate /etc/letsencrypt/live/rss.ishanjain.me-0001/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/rss.ishanjain.me-0001/privkey.pem;

      # Enable Underscores in Headers
      underscores_in_headers on;

      location / {
        proxy_pass http://localhost:4242; // Docker container listens on 127.0.0.1:4242
      }

      access_log /var/log/nginx/rss.ishanjain.me/access.log;
      error_log /var/log/nginx/rss.ishanjain.me/error.log;
    }


    // snippets/ssl_config.conf
    ssl_session_tickets off;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    ssl_stapling on;
    ssl_stapling_verify on;

    // snippets/letsencrypt.conf
    location /.well-known/acme-challenge {
        alias /etc/letsencrypt/webrootauth/.well-known/acme-challenge;
        location ~ /.well-known/acme-challenge/(.*) {
            add_header Content-Type application/jose+json;
        }
    }

    // snippets/securityheaders.conf
    add_header Strict-Transport-Security "max-age=31536000; includeSubdomains" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;

</details>

**Comment by ishanjain28** [comment]
Also, I started the docker container with this,

> docker run -d --name freshrss --restart unless-stopped --log-opt max-size=10m  -p 127.0.0.1:4242:80 -v /home/ishan/freshrss:/var/www/FreshRSS/data   -e 'CRON_MIN=4,34'   -e TZ=Asia/Kolkata freshrss/freshrss:alpine

**Comment by Alkarex** [comment]
nginx servers are very often badly configured. I suggest you try to access FreshRSS directly through a local port just to check whether it works or not, and then again through your nginx

**Comment by Alkarex** [comment]
Cf. https://github.com/FreshRSS/FreshRSS/issues/2731
https://freshrss.github.io/FreshRSS/en/admins/10_ServerConfig.html

**Comment by Alkarex** [comment]
This could also be a JavaScript error client side (due to e.g. extensions or custom settings). Please try with another browser, and check your browser logs

**Comment by ishanjain28** [comment]
> nginx servers are very often badly configured. I suggest you try to access FreshRSS directly through a local port just to check whether it works or not, and then again through your nginx

You are right! I had assumed since freshrss instance was running in a docker container using httpd, I wouldn't have to do much in my nginx reverse proxy configuration. Turns out that is not the case and my configuration is broken somewhere. I'll figure out what's wrong with my nginx configuration. 

Thank you soo much for taking the time to look into this issue. :)

**Comment by ishanjain28** [comment]
In my case, It was the `Content-Security-Policy` that was rejecting some JS scripts in freshrss. Because of this,

1. Freshrss couldn't send the request to `/i?c=javascript&a=nonce&user=<username>` and get the nonce. 
2. Since, It couldn't fetch nonce and the salt, The challenge field in next request to `/i?c=auth&a=login` was empty.

Now, I need to figure out a better/less strict CSP for freshrss.

**Comment by Alkarex** [comment]
CSP rules are already natively emitted by FreshRSS :-)

**Comment by ishanjain28** [comment]
That doesn't sound right. I don't see CSP header when I am sending request directly to Freshrss docker container. 

```bash
turquoise :: ~ » curl 10.11.11.1:4242/i/ --head
HTTP/1.1 200 OK
Date: Wed, 08 Jan 2020 12:03:50 GMT
Server: Apache/2.4.41 (Unix)
X-Powered-By: PHP/7.3.13
Cache-Control: private, must-revalidate, max-age=0
Last-Modified: Wed, 08 Jan 2020 12:03:50 GMT
Etag: "06c656002ff69fc3eb981c8dc597812e"
Set-Cookie: FreshRSS=j6b1ev1pqqipvntj54g1463gfl; path=/i/; HttpOnly; SameSite=Lax
Content-Type: text/html; charset=UTF-8

turquoise :: ~ » curl 10.11.11.1:4242 --head
HTTP/1.1 200 OK
Date: Wed, 08 Jan 2020 12:03:58 GMT
Server: Apache/2.4.41 (Unix)
Last-Modified: Mon, 06 Jan 2020 19:31:16 GMT
Accept-Ranges: bytes
Content-Length: 774
Cache-Control: max-age=2592000, public
Expires: Fri, 07 Feb 2020 12:03:58 GMT
Vary: Accept-Encoding
Content-Type: text/html; charset=utf-8
```

I had checked this earlier when I was setting up the reverse proxy and only added CSP headers because freshrss was not setting them. 

These responses are from the latest version of `freshrss/freshrss:alpine`(5850ed9dc135).

**Comment by Alkarex** [comment]
@ishanjain28 Try `curl -v 'http://10.11.11.1:4242/i/'`

**Comment by ishanjain28** [comment]
@Alkarex 


```bash
turquoise :: ~ » curl -v http://10.11.11.1:4242/i/
*   Trying 10.11.11.1:4242...
* TCP_NODELAY set
* Connected to 10.11.11.1 (10.11.11.1) port 4242 (#0)
> GET /i/ HTTP/1.1
> Host: 10.11.11.1:4242
> User-Agent: curl/7.67.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Wed, 08 Jan 2020 14:41:25 GMT
< Server: Apache/2.4.41 (Unix)
< X-Powered-By: PHP/7.3.13
< Cache-Control: private, must-revalidate, max-age=0
< Last-Modified: Wed, 08 Jan 2020 14:41:25 GMT
< Etag: "cacf28c3b6f6e9ec379448242c8b1ddb"
< Content-Security-Policy: default-src 'self'; frame-src *; img-src * data:; media-src *
< X-Content-Type-Options: nosniff
< Vary: Accept-Encoding
< Set-Cookie: FreshRSS=amu3uc0qnpmeodtgqdbsi9bvvc; path=/i/; HttpOnly; SameSite=Lax
< Transfer-Encoding: chunked
< Content-Type: text/html; charset=UTF-8
<
```

Oh, I am sorry. There it is. :)

**Comment by Alkarex** [comment]
Alternative: `curl -s -D - 'http://10.11.11.1:4242/i/' -o /dev/null`
During a HEAD request (which is different than GET, POST...), FreshRSS stops quite early, and in particular before generating the CSP for a given page.
P.S.: We should maybe produce the whole GET output and discard it, but that seems a bit overkill

**Comment by Alkarex** [comment]
Feel free to open a ticket if you would like the HEAD behaviour to be improved :-)

**Comment by ishanjain28** [comment]
@Alkarex I still have not been able to resolve this issue and the actual problem is something else. 

Now, My FreshRSS instance at `rss.ishanjain.me` is not running behind any proxy. It's just apache2 with the configuration files I got from freshrss documentation. 

Normally, It's accessible. i.e. I can login no problem. 

But, If I enable Cloudflare DNS proxy, I can't login anymore. 

The only difference I have noticed is, Without cloudflare, It loads the scripts in `/scripts/` directory, With cloudflare, It just dosn't. :/ 

Everything else(Including the CSP header) are the same with or without cloudflare.

**Comment by Alkarex** [comment]
@ishanjain28 We have a few users who have reported problems with Cloudflare (which I am not familiar with, except that it looks like they are breaking the Web in various ways). See related issues such as:
https://github.com/FreshRSS/FreshRSS/issues/2303#issuecomment-477533776
https://github.com/FreshRSS/FreshRSS/issues/1681
You can try to remove/edit CSP at Apache level, if security needs to be reduced for Cloudflare

**Comment by ishanjain28** [comment]
I have already tried a different/more open CSP in apache config but that didn't change anything. I am tried of trying to figure this out so I'll remove CSP.
