### ISSUE TITLE
Item title is difficult to read on hover

### ISSUE THREAD

**Issue by nicofrand** [FreshRSS/FreshRSS#2755]
Hi!

Since the last version the item's title is wider and overlaps the date on hover.
But the background being transparent I find it quite difficult to read on small screens:

![image](https://user-images.githubusercontent.com/3419050/71898706-4739a800-315a-11ea-853d-1f5a50da6e4e.png)

Maybe the background could go over the date or something?

Thanks for the hardwork, as always.

**Comment by Alkarex** [comment]
Hi @nicofrand 
Is that the Origine theme? I cannot immediately reproduce the problem. On which browser?
Do you have any FreshRSS extension active?

**Comment by Frenzie** [comment]
Also possibly relevant, which browser are you using?

Edit:  @Alkarex already said that too. :blush:

**Comment by Alkarex** [comment]
Ah, sorry, *on hover*. Bug confirmed then (tested in Firefox), in the theme Origine (and maybe some others)

**Comment by nicofrand** [comment]
Hi,

yup on Firefox at least (but I see no reason it would not happen on other browsers) and the Origine-compact theme. I have my own extension (Third pane view https://framagit.org/nicofrand/xextension-threepanesview) that reduces the width but that will also happen without it on narrow screens/windows.

**Comment by marienfressinaud** [comment]
> Ah, sorry, on hover.

To be even more precise: only with unread articles ^^

It will probably fixed within the patch I'll made for #2344.

**Comment by Alkarex** [comment]
Fixed by https://github.com/FreshRSS/FreshRSS/pull/2882 for all themes except two. Tests (and remaining help) welcome

**Comment by Alkarex** [comment]
Now all themes should be fixed https://github.com/FreshRSS/FreshRSS/pull/2884
