### ISSUE TITLE
Password protected feeds

### ISSUE THREAD

**Issue by westtomato** [FreshRSS/FreshRSS#2757]
Is it not possible to subscribe to password protected feeds?
http://user:pass@domain.tld/feed.rss seems not to be working.

**Comment by marienfressinaud** [comment]
When you add a feed, you can pass your credentials in the popup menu (HTTP authentication):

![Capture d’écran de 2020-01-08 16-45-40](https://user-images.githubusercontent.com/1436309/71992875-70c80180-3236-11ea-97d2-ec65e66ac751.png)

**Comment by westtomato** [comment]
Merci beaucoup!
