### ISSUE TITLE
Unable to configure postgresql as database during setup

### ISSUE THREAD

**Issue by filovitch** [FreshRSS/FreshRSS#2765]
Hello everyone,

I have same issue as #2748 except the password is correctly set in config.php
```php
<?php
 return array (
  'salt' => '6be75d522d96397d4cab8da6d7a114c03b8db2fe',
  'base_url' => 'http://rss.test.be',
  'default_user' => '_',
  'db' => 
  array (
    'type' => 'pgsql',
    'host' => 'localhost',
    'user' => 'freshrss',
    'password' => 'freshrsspwd',
    'base' => 'freshrss',
    'prefix' => '',
    'pdo_options' => 
    array (
    ),
  ),
  'pubsubhubbub_enabled' => true,
);
```
I have tried with 127.0.0.1 as a host and I have the same problem. If I set a wrong password, I have an error message when submitting the information but in my case, every field are blanked and I cannot go further. The database already exist and the freshrss user is the owner. I am on the last version of freshrss. 

Configuration:
* Centos 8
* Postgresql 10
* Nginx
* PHP 7.3

How can I debug this problem?

**Comment by filovitch** [comment]
Found the solution. I had this error in nginx log:
```
2020/01/13 16:28:59 [error] 786#0: *30 FastCGI sent in stderr: "PHP message: PHP Warning:  session_start(): open(/var/lib/php/session/sess_n2qcqemipej3gfqm9ur813p1d1, O_RDWR) failed: Permission denied (13) in /usr/share/FreshRSS/app/install.php on line 12PHP message: PHP Warning:  session_start(): Failed to read session data: files (path: /var/lib/php/session) in /usr/share/FreshRSS/app/install.php on line 12" while reading response header from upstream, client: 192.168.1.107, server: rss.test.be, request: "GET /i/index.php?step=2 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/www.sock:", host: "rss.test.be", referrer: "http://rss.test.be/i/index.php?step=2"
```
When I check the session folder (/var/lib/php/session) it was configured with wrong owner and group. Setting as 'nginx' user and group solved the problem.

**Comment by Alkarex** [comment]
Thanks for returning with the solution :-)

**Comment by Inverle** [comment]
@filovitch

>   'salt' => '6be75d522d96397d4cab8da6d7a114c03b8db2fe',

If you are still using this salt, please generate a new one. Exposing the salt is bad for security.

Command to generate new salt:
```bash
 php -r 'echo bin2hex(random_bytes(20)) . "\n";'
```
