### ISSUE TITLE
Error response from daemon: No such container: freshrss

### ISSUE THREAD

**Issue by blueray453** [FreshRSS/FreshRSS#2768]
```
$ docker pull linuxserver/freshrss
Using default tag: latest
latest: Pulling from linuxserver/freshrss
4b5cbb7c8b36: Pull complete 
72f9af53299a: Pull complete 
1c1c7ad5b9ce: Pull complete 
9cc1d1fd2be6: Pull complete 
9adcb0257cc6: Pull complete 
df54842eb23f: Pull complete 
1134c055a59f: Pull complete 
Digest: sha256:8a253ee335b5faa6cef2c485b7c9572772f9da6e3dd6724cc6ab44423bc406da
Status: Downloaded newer image for linuxserver/freshrss:latest

$ docker start freshrss
Error response from daemon: No such container: freshrss
Error: failed to start containers: freshrss

```
What is wrong here?

**Comment by Frenzie** [comment]
To do that you'd have to name a container (with `--name`). But given that you didn't do any port mapping or anything, quite possibly a whole lot more. See https://github.com/FreshRSS/FreshRSS/tree/master/Docker for sample commands.

**Comment by blueray453** [comment]
@Frenzie I am not very sound with docker. Can you please give me a sample command.

**Comment by blueray453** [comment]
I want to run it on my PC (localhost)

**Comment by blueray453** [comment]
I have tried
```
# First time only
git clone https://github.com/FreshRSS/FreshRSS.git

cd FreshRSS/
git pull
docker build --pull --tag freshrss/freshrss -f Docker/Dockerfile .

docker exec --user www-data -it freshrss php ./cli/list-users.php
```

Now it is saying 

> Error: No such container: freshrss

**Comment by blueray453** [comment]
I am using Linux Mint 19.3

**Comment by Frenzie** [comment]
I'm not entirely sure what you're asking. Please see the link I gave for sample commands.

> Now it is saying

`docker exec` is for running commands in a container that's already running.

So first you'd have to `docker run --name freshrss [more options]` before `docker exec freshrss` could make any sense.

I see you got that command from [here](https://github.com/FreshRSS/FreshRSS/tree/3c099c78537020eae3b6fe060fbe86088e996c83/Docker#command-line) where it doesn't include any explicit warnings about this, but it's nevertheless not quite clear to me why you skipped all of the sample commands to jump down into advanced usage territory. ;-)

**Comment by Frenzie** [comment]
But what do you want to achieve exactly? If you just run `make start` in the FreshRSS repo you'll get a development instance on `localhost:8080` by default.

**Comment by blueray453** [comment]
This worked for me. Thanks.

However, I gave 

```
$ docker volume create freshrss-data
$ docker network create freshrss-network
$ docker run -d --restart unless-stopped --log-opt max-size=10m \
>   -v freshrss-data:/var/www/FreshRSS/data \
>   -e 'CRON_MIN=4,34' \
>   -e TZ=Europe/Paris \
>   --net freshrss-network \
>   --label traefik.port=80 \
>   --label traefik.frontend.rule='Host:freshrss.example.net' \
>   --label traefik.frontend.headers.forceSTSHeader=true \
>   --label traefik.frontend.headers.STSSeconds=31536000 \
>   --name freshrss freshrss/freshrss
c13336be747b208d2d29b73393b3af65f9c3570b88a5e43a84fb27d85250328d
$ docker exec --user www-data -it freshrss php ./cli/list-users.php
Result: success
```

If I want to use docker, then what do I need to do next? I mean, if the `Result: success` then it is probably running somewhere. Can I find it in any particular place?

**Comment by marienfressinaud** [comment]
Your first mistake was that you pulled the `linuxserver/freshrss` image but tried to start `freshrss`: you should have used `linuxserver/freshrss` in both commands.

Anyway, if you're more used to web server + php configuration, I would recommend you to use this instead of Docker. It's easier to run and to manage. But as @Frenzie said, it depends on what you try to achieve.

If you really want to use Docker, I recommend you first to learn basic usage ([here for example](https://docker-curriculum.com/)): I think your questions can find answers very easily on Internet ;)

**Comment by blueray453** [comment]
Thanks
