### ISSUE TITLE
[1.15.3] Slashes in author name are UTF-8 encoded in Search byline

### ISSUE THREAD

**Issue by troyengel** [FreshRSS/FreshRSS#2770]
My setup:
- Server: Debian 10
- FreshRSS: 1.15.3
- `AllowEncodedSlashes On` is set in the Apache vhost (per the setup docs)

I have a workstation which turns out does not have a full UTF-8 character set (my problem) and specifically is missing the "fullwidth solidus" (slash) character in the UTF-8 encodings: https://www.fileformat.info/info/unicode/char/ff0f/index.htm

The reddit RSS feeds supply the `author` element with the username in low-ASCII slashes (char 47), however it appears that FreshRSS is mistakenly UTF-8 encoding those in the author Search injected byline - but not in the Submitted author line in the same post. Visually, with my broken font:

---
![slashfull](https://user-images.githubusercontent.com/402696/72532885-c6ee0380-3839-11ea-96cb-083aef67392b.png)
---

The HTML for each element looks like so, which might be hard to see as it will render with your local font correctly (assuming you don't have a broken font too :)), but the encoded chars are `ef bc 8f` (UTF-8 U+FF0F) before and after the "u" in `/u/DigitalGoomba` in this example:

top:
```
<div class="author">By: <em><a href="./?search=author%3A%EF%BC%8Fu%EF%BC%8FDigitalGoomba">／u／DigitalGoomba</a></em>
```
bottom:
```
submitted by   <a href="https://www.reddit.com/user/DigitalGoomba"> /u/DigitalGoomba </a>
```

I'm of the initial opinion that the encoding of the forward slash into it's UTF-8 variant is a mistake in the Search injected byline, and that they (the author elements) should be presented as low-ASCII characters on the Search byline the same as they are in the Submitted byline.

Thanks!

**Comment by troyengel** [comment]
Looking at the code, I think it's the `safe_utf8()` inline function (which calls the MB function) parsing the author feed when it's grabbing the data: `$valuesTmp['author'] = safe_utf8($valuesTmp['author']);` - why it's only happening in the Search byline and not Submitted byline I haven't figured out yet.

I confirm that the characters are encoded as UTF-8 in the `<user>_entry.author` column in MariaDB, a quick query shows them encoded as high-UTF-8 for the articles, so I think it's happening during data pull and the webUI is just rendering what's in the DB. (at least, looks that way - I'm not a coder by trade)

Hope this helps.

**Comment by Frenzie** [comment]
A full-width solidus (U+FF0F) isn't the same thing as a regular slash/solidus (U+002F). It takes up twice (?) as much space as a regular slash. Could you please include a link to a relevant Reddit feed?

**Comment by Alkarex** [comment]
Quick feedback: A few characters are replaced by Unicode alternatives, such as their full-width version, because no encoding satisfies all clients (some clients expecting an encoded version, while some other clients are expecting a non-encoded version). This is the case of the slash `/` replaced by `／`. See more on:

https://github.com/FreshRSS/FreshRSS/blob/d7ac234036a10f575a902af6fc63bb890f85c7b1/lib/lib_rss.php#L104-L119

https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms

I did a quick test on searching by author and cannot immediately reproduce a problem

**Comment by Frenzie** [comment]
See #2093 for details. This ugly workaround is only for author names if I understood correctly, which must be why I've never really noticed (because I get a regular / in article titles & content for sure).

**Comment by troyengel** [comment]
It appears to be any reddit RSS feed, you can simply add `.rss` to the end of any subreddit URL.  The two which I'm subscribed to are sales areas so the feed makes more sense in RSS than regular reddit browsing (to me :) ).

 - https://www.reddit.com/r/Coins4Sale/.rss
 - https://www.reddit.com/r/Pmsforsale/.rss

It's consistent across both of those feeds - I pulled them down manually real quick to ensure they did not have UTF-8 encoded slashes upstream, they're regular char 47 slashes coming out the RSS pipe.

**Comment by troyengel** [comment]
@Alkarex as a fun aside (not related), your code post shows just how broken this poor font ("Luxi Sans") is when it comes to UTF-8.  I'll definitely be finding a better replacement font on this workstation. :)

![badfont](https://user-images.githubusercontent.com/402696/72547881-20aef780-3853-11ea-9c42-8ecac9e79506.png)

**Comment by Frenzie** [comment]
Yeah, that's supposed to look a little something like this (which perfectly illustrates why those fullwidth characters are so ugly):
![Screenshot_20200116_183120](https://user-images.githubusercontent.com/202757/72548195-8371b480-388e-11ea-94de-ba3d0fdb201e.png)

**Comment by aledeg** [comment]
I've noticed that as well. The character is properly displayed on Ubuntu but not on ArchLinux. So that means that the font used by Ubuntu has a better support for those characters.
So you need to find a font that supports it. I do need to do that too.

**Comment by troyengel** [comment]
@aledeg your update piqued my curiosity, it appears (after a lot of Googling) that a _lot_ of fonts are missing these glyphs (I think that's the correct term); going down the rabbit hole, I think the actual font causing problems for Linux is that it's DejaVu Sans - which is pretty much the only Vera/Verdana metric compatible font we have and is a default on a lot of systems. Ubuntu uses a custom font they created which (according to Wikipedia) was [rejected by Fedora/Debian](https://en.wikipedia.org/wiki/Ubuntu_(typeface)#Ubuntu_Font_Licence) as it has a non-free license of some sort.

I pulled up the Firefox devtools and inspected the HTML of both Github and FreshRSS, it basically computes like this (order listed is how the HTML specifies it):

```
$ for ii in SFMono-Regular Consolas 'Liberation Mono' Menlo monospace; do fc-match "{$ii}"; done;
DejaVuSans.ttf: "DejaVu Sans" "Book"
DejaVuSans.ttf: "DejaVu Sans" "Book"
DejaVuSans.ttf: "DejaVu Sans" "Book"
DejaVuSans.ttf: "DejaVu Sans" "Book"
DejaVuSans.ttf: "DejaVu Sans" "Book"

$ for ii in "OpenSans" "Cantarell" "Helvetica" "Arial" "PingFang SC" "Microsoft YaHei" sans-serif; do fc-match "${ii}"; done;
OpenSans-Regular.ttf: "Open Sans" "Regular"
Cantarell-Regular.otf: "Cantarell" "Regular"
NimbusSans-Regular.otf: "Nimbus Sans" "Regular"
Arimo-Regular.ttf: "Arimo" "Regular"
DejaVuSans.ttf: "DejaVu Sans" "Book"
DejaVuSans.ttf: "DejaVu Sans" "Book"
DejaVuSans.ttf: "DejaVu Sans" "Book"
```

The same site above shows FF0F is missing along with the others: https://www.fileformat.info/info/unicode/font/dejavu_sans/list.htm  A lot of searching and I've not found a metric compatible variation with full UTF-8 support yet (which is FOSS licensed). I end up at a lot of meta posts like this one: https://unix.stackexchange.com/questions/14027/what-fonts-are-good-for-unicode-glyphs

So anyways, I kinda think this is a losing game (chasing fonts) - FreshRSS seems to be injecting the `ef bc 8f` / U+FF0F character, but it appears missing in many standard fonts. It would seem to me it's to work towards just not using that character to increase end-user compatibility with whatever fonts they have installed already. $0.02 USD from the peanut gallery. :)

**Comment by Frenzie** [comment]
According to Firefox, on my Debian install the characters are provided by the `WenQuanYi Zen Hei` font (and the regular characters by `Liberation Mono`). See [here](https://fransdejonge.com/2012/02/debian-international-fonts/#comment-44739) for more details, although I stupidly haven't kept proper track since. Some packages were since transitioned into other fonts iirc.

The tl;dr from my blog post is that you should go to https://en.wikipedia.org/wiki/Help:Multilingual_support_(East_Asian), https://en.wikipedia.org/wiki/Help:Multilingual_support_(Indic) and whatever else interests you for information about a wide variety of operating systems and distros.

On Arch that's `pacman -S adobe-source-han-sans-otc-fonts`.

**Comment by Frenzie** [comment]
> It would seem to me it's to work towards just not using that character to increase end-user compatibility with whatever fonts they have installed already. $0.02 USD from the peanut gallery. :)

I agree with that. Installing support for East Asian languages in Windows and Linux is a personal quirk of mine. (Unless Windows 10 does it by default now?)

Edit: Whoa, they *dropped* it.

> ### Windows Vista, 7, 8
>
>Windows Vista, Windows 7 and Windows 8 include support for East Asian characters in the standard installation.
>
> ### Windows 10
>
>In the standard installation of Windows 10, Dengxian, SimFang, SimHei, SimKai, DFKai, MingLiU, Meiryo, MS Mincho, Ms Gothic, Yu Mincho, Batang, Gungsuh, Dotum and Gulim are no longer included. So when running certain apps on Windows 10, some characters display as a square or rectangular box, or as a box with a dot, question mark or “x” inside. To solve this problem, you must install the optional font feature of the specific language.

**Comment by troyengel** [comment]
> On Arch that's pacman -S adobe-source-han-sans-otc-fonts

Nice, thanks! I just popped that in (77MB!), did a click+refresh on this tab and now all the characters shown in my screenshot above as boxes are rendering as expected. I'm going to guess that very few Western (Latin? Non-Asian?) users have this set of fonts installed or know that it solves this problem. :-/

**Comment by Frenzie** [comment]
Those specific characters still seem to work in standard Windows 10 out of the box, as well as in Mint/Ubuntu. (Actually so does regular Chinese and Japanese? Makes me wonder if the Edge VM *isn't* standard…?) But indeed a lack of CJK seems like a rather unexpected cause for failing to render a `/`.

![Screenshot_2020-01-17_21-42-57](https://user-images.githubusercontent.com/202757/72644877-6d3d2480-3972-11ea-8f8f-80e0c4ee47ac.png)

> (77MB!)

CJK fonts are literally more than half of KOReader's package size at 16.5 MB. There are just so. many. characters. That 77 MB package is probably more complete and nicer than Noto CJK. (We skip the historical/unused Unicode CJK blocks for space saving considerations iirc.)

**Comment by math-GH** [comment]
Is everything solved already in 1.19 or 1.20?

**Comment by math-GH** [comment]
Is it still an issue? Maybe it is solved already?
If it is not solved, could you support here with an feed example?

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/7056
