### ISSUE TITLE
Being able to flush / recompute entry content when changing "article CSS path".

### ISSUE THREAD

**Issue by javerous** [FreshRSS/FreshRSS#2772]
Hello,

I'm playing a bit with "Articles CSS path on original website" advanced features on Feed configuration.

I have some difficulties to use it. Apparently, it's impossible to apply this setting to feed content already fetched, which means:
- It's impossible to fix old articles with their website content.
- It's impossible to fix content fetched when subscribing to a new feed, as articles are fetched right away.

Aside the fact we miss the feature for pre-existing articles, it make it difficult to check if the path is correct, as we need to wait for new articles to be fetched to verify the result.

I didn't find any way to force FreshRSS to "recompute" content, so it updates fetched article according to this setting change. I tried to set to NULL the content field in the database, but it didn't help (FreshRSS doesn't try to re-fetch content in this case).

Wouldn't be nice to be able to force flush content fetched, so this setting had a chance to be re-evaluated ? Or automatically force reapplying this setting to fetched content when it changes ?

Thanks you !

**Comment by Frenzie** [comment]
I think it should redownload (albeit only after 20 minutes) if you "delete all articles".

A preview button next to the CSS selector would be useful, yes. It could probably be almost as simple as an optional parameter to `loadCompleteContent()` to download only the first article.

https://github.com/FreshRSS/FreshRSS/blob/01576e6317a9125133d7352f95bd9011083e0c2d/app/Models/Entry.php#L390-L418

**Comment by javerous** [comment]
@Frenzie It's what I tried to do (delete all articles), but it didn't work. I don't remember exactely what and why, but I think FreshRSS was just not re-downloading old articles (even after the refresh limit delay). Perhaps because it keep some date / IDs pointer to prevent re-inserting articles which are supposed to be already in database ? I don't know, I will retry, it was unclear.

About `loadCompleteContent()`: I will take a look, if you want.

**Comment by Frenzie** [comment]
> About loadCompleteContent(): you mean download the first article but also flush the content, right ? Else it will not try to "curl" the whole article.

I don't mean anything specific other than what's necessary to make it work, maybe it's not simple at all. I've never really looked at this part of the program before. But actually I referenced the wrong function because I wasn't thinking of anything DB-related, more like a new window that shows the scraping result, for example. Perhaps that `get_content_by_parsing` function.

**Comment by javerous** [comment]
Okay, I see. Yes, indeed, having a window which give the ability to test path outside of any DB storage can be a good solution, indeed.
