### ISSUE TITLE
CategoryDAO.php on line 375 every cron

### ISSUE THREAD

**Issue by Tealk** [FreshRSS/FreshRSS#2775]
Hi,

i use PHP 7.4 and get every cron execued this error message in my nginx error.log:
`2020/01/18 18:25:33 [error] 15177#15177: *206124 FastCGI sent in stderr: "PHP message: PHP Notice:  Trying to access array offset on value of type null in WEBPATH/app/Models/CategoryDAO.php on line 375" while reading response header from upstream, client: 93.212.29.209, server: DOMAIN, request: "GET /p/i/?c=javascript&a=nbUnreadsPerFeed HTTP/2.0", upstream: "fastcgi://unix:/var/lib/fastcgi/1-anzah-DOMAIN-php-fpm.socket:", host: "DOMAIN"`

**Comment by Frenzie** [comment]
That's on 1.15.3?

**Comment by Tealk** [comment]
Oh sorry yes its 1.15.3

**Comment by Alkarex** [comment]
@Tealk Please test the /master branch if you can, which includes a fix for this problem https://github.com/FreshRSS/FreshRSS/pull/2780

**Comment by Tealk** [comment]
Looks good, no more error messages.
