### ISSUE TITLE
"Show articles without expanding" option is backwards.

### ISSUE THREAD

**Issue by scarlet-tobar** [FreshRSS/FreshRSS#2779]
Not sure if that's the name of the option in English, but that's what it means in Spanish.
When I mark that option, the articles are expanded and viseversa.
You could change the name of the option to "Show expanded articles" to avoid confusion.

Thanks for reading.

**Comment by Frenzie** [comment]
There's the option called `Show articles unfolded by default`, if that's the one you mean.

**Comment by scarlet-tobar** [comment]
> 
> 
> There's the option called `Show articles unfolded by default`, if that's the one you mean.

that's probably it, thanks

**Comment by Frenzie** [comment]
So should the "sin" be removed or is there more to it? Would you consider submitting a PR with the correction?
https://github.com/FreshRSS/FreshRSS/blob/68863fbac8d0f9346eb3de17b079c84d5ead1b6c/app/i18n/es/conf.php#L105

For that you'd have to browse to https://github.com/FreshRSS/FreshRSS/blob/master/app/i18n/es/conf.php and click the edit icon. Or just use Git if you know how. ;-)
