### ISSUE TITLE
add possibility to convert normal html to rss-feed

### ISSUE THREAD

**Issue by Mannshoch** [FreshRSS/FreshRSS#2785]
feed43.com has a nice tool to create a rss-feed from normal website. Please add such a tool to Fresh.

**Comment by Frenzie** [comment]
I use https://github.com/RSS-Bridge/rss-bridge

I'd consider it out of scope, but something like that could be interesting as an extension.

**Comment by Mannshoch** [comment]
Should I recreate this request into https://github.com/FreshRSS/Extensions ?

**Comment by Frenzie** [comment]
I'll just tag it extension; should be just as good. ;-)

**Comment by alfureu** [comment]
Also worth a notice: https://gitlab.com/stormking/feedropolis
