### ISSUE TITLE
Feature Request: Global Filters

### ISSUE THREAD

**Issue by jamieshaw** [FreshRSS/FreshRSS#2788]
Nice and simple one – a global 'Mark as read' filter.

So I can add rules like `intitle:'deals' OR author:'deals'` to all feeds, rather than individually per feed.

**Comment by aledeg** [comment]
Duplicate of #690

**Comment by Alkarex** [comment]
Implemented at last in https://github.com/FreshRSS/FreshRSS/issues/4999
Feedback welcome
