### ISSUE TITLE
Trouble logging in using Firefox on Android

### ISSUE THREAD

**Issue by nekr0z** [FreshRSS/FreshRSS#2789]
I've started having trouble logging into my FreshRSS installation from my phone today, both with Chrome and with Firefox for Android. I haven't recently updated FreshRSS or tweaked the server, so no obvious thing changed in my setup (other than browsers being updated constantly).

After I updated the FreshRSS installation to current master I am now able to log in on the phone using Chrome, but still get a 403 page using Firefox. Desktop browsers (both Chrome and Firefox) continue to work without any issues.

Logs show that when I attempt to log in from Firefox on Android `nonce` appears empty. I have tried to research similar issues here in the repository, but nothing obviously relevant jumped out.

My setup is somewhat idiosyncratic, and is likely the source of the problem, but I can't seem to figure out where exactly. I'm running a [Known](https://github.com/idno/Known) instance for my blog on a Dreamhost Shared plan ([evgenykuznetsov.org](https://evgenykuznetsov.org)), and have a symlink to FreshRSS's `/p/`in Known's root, so that [evgenykuznetsov.org/freshrss](https://evgenykuznetsov.org/freshrss) points to `/p/`. This setup has been working reliably for about a year now, until today.

I update Known regularly (and did update it yesterday), but there were no changes to root folder's `.htaccess` since September.

Could you please advise me on how to further troubleshoot this? I understand that this issue is most likely with my particular setup, not with FreshRSS itself, but I'm willing to at least contribute to documentation so that the next person with similar setup has it easier, and for that I need to figure out what exactly is causing the issue here.

**Comment by Frenzie** [comment]
The nonce probably comes from JavaScript; could it be something as simple as the NoScript extension?

**Comment by nekr0z** [comment]
It certainly could, but on my phone I only have two extensions installed: uBlock (which was an obvious suspect so I disabled it for testing, not that it made any difference) and the default theme (not sure why it is considered an extension; tried disabling that, too, no difference either). JavaScript itself is enabled, and all JS-related settings in `about:config` seem to be default.

**Comment by Alkarex** [comment]
@nekr0z If you still have the problem, could you make me a temporary account, so that I could try?

**Comment by nekr0z** [comment]
> @nekr0z If you still have the problem, could you make me a temporary account, so that I could try?

I still do. An update to Firefox for Android seemed to have solved it, but the next update reintroduced the issue.

I've sent you the credentials by mail.

**Comment by Alkarex** [comment]
Hello @nekr0z and sorry for the delay. I have just tried the account you sent me and cannot spot any problem, neither from desktop not from mobile (tested with Firefox 68.6b4, Samsung Internet browser, Chrome 80) on Samsung Galaxy S8 running Android 9.
Could you try with the account you just created for me with a couple of different browsers, or even from another phone if you can?
Watch out if you use a password manager, a proxy, or anything else which might introduce a bug in the flow.

**Comment by nekr0z** [comment]
Hello @Alkarex and thank you for your effort. I've consistently been able to log into my own account with Firefox 68.5 from Android for the last three days; and I've been consistently unable to do that for 10 days before that. Chrome always kept working perfectly for me, and so did all the desktop browsers I've tried. So, the only browser I've ever had issues with is Firefox on Android, and the issue being intermittent actually drives me crazy. You can't debug what you can't reliably reproduce, right?

I don't seem to be able to reproduce this issue today on any account, mine or yours. I've been able to reproduce it last week, at least on my account, and I have no idea what changed since then. :-(

**Comment by nekr0z** [comment]
@Alkarex I woke up this morning and I can not login using the very same Firefox 68.5 on Android, neither to my account, nor to yours. Literally, nothing changed on the server, nothing changed on the phone, but now I'm having a 403.

**Comment by Alkarex** [comment]
I have just tested without problem 🙂

**Comment by nekr0z** [comment]
> I have just tested without problem slightly_smiling_face

So it's definitely my browser, because I'm still having the issue. OK, at least I know the culprit now. Thank you so much for your time and effort!

**Comment by Alkarex** [comment]
Keep us informed if you find more precisely what the issue is, or if you need more testing help
