### ISSUE TITLE
WebSub.rocks does not work

### ISSUE THREAD

**Issue by triatic** [FreshRSS/FreshRSS#2796]
Hi, I'm testing out WebSub with the latest FRSS master, but I'm failing to subscribe for some reason.

I'm testing at https://websub.rocks/subscriber/102 and I'm getting this message: 

> There was an error with your subscription request: verification_failed. The callback URL did not confirm the verification request.

In `data/users/_/log_pshb.txt` I'm seeing this:

> [Tue, 11 Feb 2020 11:42:47 +0000] [warning] --- WebSub subscribe to https://websub.rocks/blog/102/ZIDLTIEJhi8VukT8dOEY via hub https://websub.rocks/blog/102/ZIDLTIEJhi8VukT8dOEY/hub with callback https://mydomain/freshrss/api/pshb.php?k=dff59dbd4f9ccaf265a7d93ced0b100c0bd981e1: 400 {"error":"verification_failed","error_description":"The callback URL did not confirm the verification request.","code":0,"callback_response":false,"type":"error"}

(I edited my real domain with "mydomain")

Any idea what's going on here please?

**Comment by math-GH** [comment]
@triatic Is it still actual? I use some feeds via WebSub and they works fine.

**Comment by triatic** [comment]
@math-GH I still receive that error when testing WebSub via that website. Can you confirm that website I am using works so that I have a base to work on?

**Comment by math-GH** [comment]
I have no experience with this website.

What do you want to test? Do you need feeds, that use WebSub techniques?

**Comment by triatic** [comment]
My intention was to implement WebSub on my own application. To begin with I wanted to test that I could get WebSub working with FreshRSS so I came across the websub.rocks website but it does not work for me as outlined in my first post.

**Comment by math-GH** [comment]
I would say, that it is a problem with the website and its feed.
Honestly, I do not understand what websub.rocks does. When I load https://websub.rocks/subscriber/102 there is a endless loading wheel.

**Comment by triatic** [comment]
The loading wheel will stop after you add the given feed URL to FreshRSS.

**Comment by math-GH** [comment]
The feed does not validate
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwebsub.rocks%2Fblog%2F102%2FM2Jrvu0sgZP1AFgWc0NY

**Comment by math-GH** [comment]
I can use it:
![grafik](https://user-images.githubusercontent.com/1645099/147461093-ec4250d0-85d2-4b81-8039-54572ae898fa.png)

And I do not have any error in the log

**Comment by triatic** [comment]
Yes, the feed will add to FreshRSS, but the question is whether the WebSub realtime push functionality is enabled?

**Comment by math-GH** [comment]
I cannot find the option to test it.

Please ask here: https://github.com/aaronpk/websub.rocks/issues

Right now I cannot find a point where FreshRSS could help

**Comment by triatic** [comment]
Once FreshRSS has successfully added the feed, an option to test should appear.

Alternatively, can you supply me with an alternative WebSub feed to test with?

**Comment by math-GH** [comment]
> Once FreshRSS has successfully added the feed, an option to test should appear.

To test what function?

 
> Alternatively, can you supply me with an alternative WebSub feed to test with?

I would say that a lot of wordpress websites have a WebSub feed.
This feed works fine for me: http://feeds.feedburner.com/stadt-bremerhaven/dqXM

**Comment by triatic** [comment]
> To test what function?

I have just tried it again and it works now. I thought it would provide a an ability to push a new article to the reader but it just seems to confirm a successful WebSub subscription.

> I would say that a lot of wordpress websites have a WebSub feed. This feed works fine for me: http://feeds.feedburner.com/stadt-bremerhaven/dqXM

I have now added that feed. So can I set that feed to automatically update once a week whilst still getting new posts in real-time?

**Comment by math-GH** [comment]
> I have now added that feed. So can I set that feed to automatically update once a week whilst still getting new posts in real-time?

In FreshRSS, a blue banner will appear asynchronously of manual feed updates, when a new article is published. (If you use 1.19.0-dev than this issue is fixed: https://github.com/FreshRSS/FreshRSS/pull/3999 )

**Comment by triatic** [comment]
Caschys Blog article from Mon, 27 Dec 2021 11:36:41 +0000 does not seem to have been pushed to FreshRSS via WebSub.

![Screenshot 2021-12-27 114607](https://user-images.githubusercontent.com/42704418/147468952-90304d18-f8fa-42c5-86dd-35218cf13766.png)

**Comment by math-GH** [comment]
I got it. Which FreshRSS version do you use?

**Comment by triatic** [comment]
1.19.0-dev. I have set the feed update frequency to one week to ensure updates are coming via WebSub push and not a normal fetch.

**Comment by math-GH** [comment]
Any log entries?

**Comment by triatic** [comment]
No.

**Comment by triatic** [comment]
I don't suppose running the web server on a port other than 443 is an issue? Reason being I am running a dns-over-https server on port 443. The firewall is fully open to all internet addresses.

**Comment by math-GH** [comment]
It could be an issue. I see some 443 ports hard coded.

**Comment by triatic** [comment]
I suggest that hard coding port 443 rather than detecting and using the actual port in use would be a bug.

**Comment by Frenzie** [comment]
They're not hard-coded in the sense suggested. `listen 443 ssl;` is _suggested_ in server config, but making sure that's correct is a matter of… server config! ;-)

**Comment by triatic** [comment]
'base_url' in data/config.php has my correct server port. The WebSub feed mentioned earlier remains out-of-date ever since I added it to FreshRSS.

**Comment by Frenzie** [comment]
If you can reach it, so can a WebSub server.

**Comment by Alkarex** [comment]
We used to test WebSub with `http://push-pub.appspot.com` but the test is down. Now there is https://pubsubhubbub.appspot.com instead, but more manual.
Otherwise, many other Web sites can be used:
* http://rss.slashdot.org/slashdot/slashdotMain
* http://feeds.feedburner.com/hackaday/LgoM
* http://feeds.arstechnica.com/arstechnica/index
* https://www.blogger.com/feeds/2471378914199150966/posts/default
* ...

**Comment by triatic** [comment]
> If you can reach it, so can a WebSub server.

Unless the server is configured to only accept my IP address.

**Comment by triatic** [comment]
> We used to test WebSub with `http://push-pub.appspot.com` but the test is down. Now there is https://pubsubhubbub.appspot.com instead, but more manual. Otherwise, many other Web sites can be used:

I have added the suggested feeds. Assuming I have no errors in the log after adding, and I set the automatic update frequency to one week, can I assume the articles should appear in FreshRSS as soon as new articles are posted?

**Comment by triatic** [comment]
I am getting new articles from the feeds suggested by @Alkarex via WebSub now, `FeedFetcher-Google` is POSTing to `/freshrss/api/pshb.php`. I am therefore closing the issue. Thanks for all the suggestions.
