### ISSUE TITLE
Sharing Top Article

### ISSUE THREAD

**Issue by Pofilo** [FreshRSS/FreshRSS#2797]
Hello,

In the file `app/views/configure/display.phtml`, I wonder why there is a `bottomline_sharing `but no `topline_sharing `?

Thanks.

**Comment by aledeg** [comment]
Nobody asked for it.

**Comment by Pofilo** [comment]
If I'm the only one to ask for it, maybe adding it to master is not a good idea. 
I tried to do it but not successfully, is there a way to do it easily ?

My use case is to send my article to wallabag without scrolling the article in FreshRSS.

**Comment by Frenzie** [comment]
> If I'm the only one to ask for it

You're certainly not the only one to think of or notice it, but I wasn't driven to action (yet) in part because of the sharing shortcut, <kbd>s</kbd> by default. That makes it pretty much a cellphone-only problem for me, also because on desktop it's a lot easier to reach the bottom.

**Comment by Pofilo** [comment]
I was not using the shortcuts (too many shortcuts on too many softwares is impossible to remember ^^).
However, `s` for Share is quite easy to remember :)

I'm closing the issue.
