### ISSUE TITLE
Loss of functions, Origine theme, low width

### ISSUE THREAD

**Issue by triatic** [FreshRSS/FreshRSS#2799]
When the Origine theme goes below a certain width, there are no buttons to access the Subscription Management and Configuration areas.

**Comment by Frenzie** [comment]
Please see #1876 and linked issues. It's a somewhat delayed WIP.

**Comment by triatic** [comment]
Ah, thanks.

Subscription Management seems to scale fairly well at low width, we just need the button for it. Definitely the Configuration area needs work though.

**Comment by triatic** [comment]
Is this fixed by PR #1929 which is still awaiting review?

**Comment by triatic** [comment]
I've just made PR #2800 which adds the Subscription Management button to the mobile menu. What do you think?

**Comment by math-GH** [comment]
I guess it should be already fixed

FreshRSS 1.18.1:
![grafik](https://user-images.githubusercontent.com/1645099/127048161-c1e1efad-7520-487c-8bf7-26f8a0829e28.png)

**Comment by Frenzie** [comment]
That's the most important part, but it's still true for general configuration.

**Comment by math-GH** [comment]
Access to the configs is available with V1.19 in mobile view.
