### ISSUE TITLE
Uncached feeds take a couple of seconds to load

### ISSUE THREAD

**Issue by SuperSandro2000** [FreshRSS/FreshRSS#2802]
I use the official Docker Image behind Traefik and almost every time I load a feed for the first time I get really long loading times. I used the Chrome network tools to find out that the Queuing takes a couple of seconds instead of ms. I checked the server freshrss is hosted on and disk, cpu and memory usage are normal and freshrss should have enough resources to run on. The server runs on my local network and has an average ping of 3 ms.

Now my question: Do you have any idea/advice how I could improve this? I find it quite annoying and would like to tune it a bit.

![image](https://user-images.githubusercontent.com/7258858/74766589-ab857680-5285-11ea-9117-8aa55422ed1f.png)

**Comment by Alkarex** [comment]
Does that affect icons, or your main page? Could you please try to reproduce the problem with another browser? Do you have a public address I could test?

**Comment by SuperSandro2000** [comment]
It only affects icons but the name and text of feed items are blocked until they are loaded. The login page and the pages itself with the layout load almost instantly but without content.

I tried this in Chrome, Chromium and Firefox. It happens not consistent but every other or third try.

This is how the waterfall then looks:
![image](https://user-images.githubusercontent.com/7258858/75113400-089a7700-564e-11ea-8860-017047c0a8c6.png)

Some pictures load very fast and some take 3 to 6 seconds which I can't explain.

The instance is on freshrss.supersandro.de but registration is closed.

**Comment by SuperSandro2000** [comment]
I am not entirely sure if 1.16.1 and especially #2962 fixed this but it feels a lot better now. If I find a reproducible scenario or some evidence with a benchmarking tool I will open a new issue.
