### ISSUE TITLE
<media:description> tag transforms to <pre class="enclosure-description">

### ISSUE THREAD

**Issue by icolquhoun** [FreshRSS/FreshRSS#2807]
Feeds from the Toronto Star like this one: http://www.thestar.com/content/thestar/feed.RSSManagerServlet.articles.news.gta.rss 

caption photos with a &lt;media:description> tag. FreshRSS translates that to &lt;pre class="enclosure-description"> which is fine for a regular browser, but is problematic when I read my feeds via FeedMe on my phone.

The &lt;pre> is rendered in one big long line causing the caption to scroll horizontally way off the right edge of the screen. This isn't ideal because swipe left is the next article gesture so it takes several swipes to get to the end of the caption and then one more to get to the next article.

I have included a screenshot showing the caption under the photo going off the edge of the screen.
![Screenshot_20200225-120505708](https://user-images.githubusercontent.com/15722127/75272967-e713c980-57cc-11ea-9b38-e67c0ea7e3c1.jpg)

**Comment by Alkarex** [comment]
Hum, yes indeed. The reason for the `<pre>` is that this field is often used with white-space sensitive formatting, e.g. some lyrics on multiple lines (when `type="plain"`, which is the default). This can be seen e.g. in YouTube feeds.
I will have to think a bit about what to do, but we might have to start storing attachments independently to be able to provide them back in different ways.

**Comment by icolquhoun** [comment]
Thanks, that'd be great. The feeds from The Star are the only ones I've encountered the issue with, but it does make reading them rather tedious.

**Comment by Alkarex** [comment]
Could you please try this patch? https://github.com/FreshRSS/FreshRSS/pull/2808
Will only be effective on the articles you will receive after this patch

**Comment by icolquhoun** [comment]
That definitely cleared things up for me when reading with FeedMe. Hopefully it didn't break anything for anyone else, but I'm happy!
