### ISSUE TITLE
Content is suddenly missing, only headlines are displayed

### ISSUE THREAD

**Issue by seyfro** [FreshRSS/FreshRSS#2810]
I´ve been using freshrss for many months now without any issues - thanks for providing such a great tool!

Anyway I experience an issue lately and could not figure out what is causing this and hope for your help: suddenly, only the titles of the feed items are displayed, no actual content anymore:
![grafik](https://user-images.githubusercontent.com/158669/75352536-32e87080-58aa-11ea-82ba-ff63677a1256.png)

The menu "Installation checking" shows everything is ok, also my hoster said there are no issue with the database. Do you have any idea what could be going wrong here?

**Comment by Frenzie** [comment]
That's on all of them, not just a specific feed?

**Comment by seyfro** [comment]
Yes, happens on all items. Also tried overwritting the existing files on the server and running installation again - no change.

**Comment by Alkarex** [comment]
Hello @robertharm ,
What database are you using, and on which system?
Do you have other users, and if yes, are they experiencing the same problem?
Start by doing an OPML export, maybe SQLite export, and other relevant backups, as it could be a sign of database corruption.

**Comment by seyfro** [comment]
Hi @frenzie,
I am using 10.1.41-MariaDB-0+deb9u1 - Debian 9.9, PHP-Version: 7.2.25 
OPML export worked fine without any issue - file contained all feeds and looked ok. 
Created a test user and could reproduce the same issue there too. 
Any additional help would be appreciated!

**Comment by Alkarex** [comment]
Could you please disable all your FreshRSS extension, and also try with another browser?

**Comment by seyfro** [comment]
I only had "Tumbl GDPR" extension active - disabling this extension did not make any difference, neither using latest Firefox, Chrome or IE.

**Comment by seyfro** [comment]
FYI - it now works again. I think it could be related to a config on my server: my hoster set max_allowed_packet to 0 to allow large package sizes - anyway other applications on my server had an issue with this value too, so I asked him to set the value back to 128M. Now freshrss is also showing contents again - I think this is related, not sure though. Anyway ticket can be closed.
Thanks for your help nevertheless!

**Comment by Frenzie** [comment]
…0? Yeah, that'll do it. O-o I doubt it needs much, just a couple MB might potentially suffice, but you need at least a little bit! ;-)

**Comment by Alkarex** [comment]
@robertharm I am glad you found a fix. I was a bit out of ideas :-P
