### ISSUE TITLE
Errors in logs (Share.php)

### ISSUE THREAD

**Issue by prolibre** [FreshRSS/FreshRSS#2812]
I see a lot of lines in my logs (they appear at each page loading) : 

`PHP Warning:  call_user_func() expects parameter 1 to be a valid callback, array must have exactly two members in FreshRSS/app/Models/Share.php on line 263`

FreshRSS 1.15.4-dev
PHP : 7.3 on debian

**Comment by Frenzie** [comment]
When you say 1.15.4-dev, you mean current master?

**Comment by prolibre** [comment]
Hello @Frenzie 

Yes. I do the updates regularly from the web interface and I am indeed in this version.
This is what also appears in https://github.com/FreshRSS/FreshRSS/blob/master/CHANGELOG.md.

Anthony

**Comment by Alkarex** [comment]
@prolibre Could you please provide a screenshot of your configuration page showing the shares?

For reference:
https://github.com/FreshRSS/FreshRSS/blob/8b1ccdac42b5e354a5048b3316d56fce0b5ca194/app/Models/Share.php#L251-L267

**Comment by Alkarex** [comment]
Ah, I can reproduce with e.g. Wallabag
https://github.com/FreshRSS/FreshRSS/blob/8b1ccdac42b5e354a5048b3316d56fce0b5ca194/app/shares.php#L40-L49

**Comment by Alkarex** [comment]
Ping @aledeg

**Comment by Alkarex** [comment]
Could you please try https://github.com/FreshRSS/FreshRSS/pull/2817 ?

**Comment by prolibre** [comment]
@Alkarex good for me ! merci / thanks
