### ISSUE TITLE
High number of requests coming from FreshRSS gets me blocked from hosting

### ISSUE THREAD

**Issue by ltnzr** [FreshRSS/FreshRSS#2819]
Hi,
I don't have a clear view of what is going on, but my FreshRSS install gets me temporarily blocked by the hosting service due to a high number of requests (more than 1000 in 10 secs).
The requests are in the form: "GET /f.php?xxxxxx HTTP/1.1"
Where xxxx is different every time, but for the rest it's the same.
This seem to happen when I'm not even refreshing the feeds. I get the feeling it has to do with the favicons of the feeds / articles because when I open FreshRSS they are not there and they appear progressively.
But could it be that it's checking the favicon of every article (not feed)? I don't have more than 1000 feeds in my instance, so I can only assume it's linked to articles?
If I can do something to help pinpoint the problem, let me know.

**Comment by Frenzie** [comment]
If I load a page there seem to be some 200-300 requests. I'm sure it could have a few more depending on specifics, but note that 99% are cache hits.

**Comment by ltnzr** [comment]
When I log in in my browser, I do see constant "Connecting..." "Waiting..." "Retrieving data..." messages from the browser. Until the server disconnects me.
Favicons are not cached it seems, every time I log in they are not there.
Is there anything else FreshRSS should poll when logging in? It's not updating the list of articles so I'm wondering what else.

**Comment by Alkarex** [comment]
Please try with another browser, to check whether you can reproduce the issue

**Comment by ltnzr** [comment]
I tried with Firefox and Vivaldi. Firefox seem to be more verbose with pop-up messages about what it's doing in the bottom left, but I got blocked with Vivaldi in the same way.
The server admin told me it sent 1311 requests in 10 secs. which the firewall picked up as a potential attack. I have ~150 feeds, but not all of them are refreshed frequently.
Clicking on the manual refresh button gets me blocked for sure after a few dozens feeds. But as stated above, I also got blocked when just logging in and showing the list of articles without updating.

**Comment by Alkarex** [comment]
There appears to be more than one problem.

How many feeds do you have on the page that generates the problem?

Are the 1311 requests all of the form `/f.php?xxxxxx` ? (If not, it can also be images from the articles you are reading, which can be reduced by using the lazy loading option and other related options).

Have you considered upgrading to HTTP/2? With HTTP/2, the issue of the number of requests is not as important as it used to be with HTTP/1.1, and the remaining concern is the total size transferred in bytes, and not so much in how many chunks this was sent.
 
Could you show and example of HTTP response? Here is one from my side:

```
HTTP/2.0 200 OK
cache-control: public, max-age=1468800
content-disposition: inline; filename="df3c6e52.ico"
content-type: image/x-icon
date: Mon, 24 Feb 2020 13:01:33 GMT
etag: "e90647d87c12eda3b923b7fc7259110a"
last-modified: Fri, 14 Feb 2020 00:34:09 GMT
server: Apache/2.4.41 (Ubuntu)
strict-transport-security: max-age=31536000
vary: Accept-Encoding
content-length: 620
X-Firefox-Spdy: h2
```

**Comment by ltnzr** [comment]
I just tried again, it's with the "home" page, so with the unread articles list, and there was just one.
It's not when opening articles, but it might be that they are loading even if they are not displayed, this I don't know. I used the theme Origin Compact, I just tried to switch to Origin, but got blocked after that so I was not able to test this.
For the record, I have been using the FreshRSS install for a while, but the servers settings just changed and the firewall is now stricter, this is why it's blocking now and was not before. Still, it means this unusual number of requests was probably happening before as well but had no consequence for me.
I'll post more info when I get it from the admin.

**Comment by ltnzr** [comment]
Hi,
I don't have the full log, but yes, the admin told me all the requests were of the form `/f.php?xxxxxx`
An example of response:
```
HTTP/1.1 200 OK
Date: Thu, 05 Mar 2020 18:06:30 GMT
Server: Apache/2.4.25
Content-Disposition: inline; filename="c7bd9c12.ico"
Cache-Control: public, max-age=1814400
Last-Modified: Mon, 24 Feb 2020 18:20:13 GMT
Vary: User-Agent
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Pragma: no-cache
Content-Type: image/x-icon
```
I'm being blocked after a few seconds and must wait for the firewall to reallow me so it makes it difficult to test, but I tried changing theme and it seem to me that using the Origin theme instead of Origin compact gave me more time, I was able to actualize all my feeds (~150) whereas with Origin compact it stops after ~30.
On thing that gets me locked every time and immediately is trying to tick / untick an article as a favourite.
My instance is up-to-date I think (1.15.3 from memory), but I thought of doing a clean install to be sure, only the export feature also blocks me immediately so I cannot back-up!

**Comment by Alkarex** [comment]
The proxy is badly configured, and prevents proper caching. Those lines are wrong:

```
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Pragma: no-cache
```

This makes that your browser will have do download the same icons at each request again and again

**Comment by ltnzr** [comment]
OK, thank you for pointing this out, where is this setting coming from then?
On the Apache server?

**Comment by Alkarex** [comment]
It might be at Apache level, yes, or another component in front such as a reverse proxy

**Comment by ltnzr** [comment]
Hi,
As a temporary "fix" if server settings cannot be changed, could I disable something for the favicon requests? Comment something out in f.php?
Just to see if this makes it usable in the meantime or if there is also something else at hand.

**Comment by Alkarex** [comment]
@ltnzr Yes, please try https://github.com/FreshRSS/FreshRSS/pull/2821

**Comment by ltnzr** [comment]
Definitely better, thank you! But, one more place where favicons are displayed is the feed management page. Don't know if it's a good idea to disable them there as well, but I got blocked again after going to the feeds management page.
I'll try to get more info from the admin but I'm also still being blocked when trying to export my feeds. Is there something going on there that would be explainable by a "too large" number of requests?
**Edit:** managed to export the feeds, guess it was blocking before because I did other things before trying that, now just got it working by directly displaying the export page.

**Comment by Alkarex** [comment]
@ltnzr I have just updated https://github.com/FreshRSS/FreshRSS/pull/2821 to include the feed management page. Please give it a try (not tested)

**Comment by ltnzr** [comment]
Merci Alexandre!
Seem to be fine, could not manage to get blocked anymore today!

**Comment by ltnzr** [comment]
Sorry for reopening this, but investigating the initial issue on the server side, it seems that my installation of freshrss is the only thing on the whole server that returns these "no-cache" replies. Different kinds of cache are activated and it's not an issue anywhere else.
Reading a bit about it, it looks like something that would come from the application itself. 
Is this possible?
I was considering doing a clean reinstall to be sure but have not got round to it yet.
I know I initially installed version 1.8, then updated with new versions coming, but was something wrong before, maybe an old config somewhere?
Any idea on your side where this could come from?
Thank you

**Comment by Frenzie** [comment]
Only If you created a data/no-cache.txt file for development purposes, see https://github.com/FreshRSS/FreshRSS/commit/dc2e1dc0817f0818943647d6b005ea35683c9c1b:

https://github.com/FreshRSS/FreshRSS/blob/acc50df0efef8bd9fa937a5d640314c0e78e9117/p/i/index.php#L33

**Comment by ltnzr** [comment]
Hum, nothing like that, no.

**Comment by Alkarex** [comment]
An instruction like `proxy-revalidate` does not appear at all in FreshRSS code base, so I do not think FreshRSS has anything to do with this misconfiguration.
If we do not get more information about the configuration of the server, it is not something we will be able to debug on our side anyway, sorry.
But please do report any finding, or post more information from your server admin
