### ISSUE TITLE
[Feature request] More timestamps for idle feeds statistic page

### ISSUE THREAD

**Issue by arokettu** [FreshRSS/FreshRSS#2827]
I have some feeds that reactivate after a year or two so having only "last year" doesn't help me to find really idle feeds

So my proposal is also add "last 2 years", "last 3 years" and maybe even "last 5 years" if someone is even more patient than me

**Comment by Alkarex** [comment]
That sounds good. 
Would you be able to try to submit a patch?
Everything is in this function:
https://github.com/FreshRSS/FreshRSS/blob/942103092545e0bd90802cccd4eab303ef172158/app/Controllers/statsController.php#L82

**Comment by arokettu** [comment]
I think so, I just need to find some time on it

**Comment by arokettu** [comment]
Ok, that was much simpler than I thought
