### ISSUE TITLE
Support getting feeds from groups.google.com

### ISSUE THREAD

**Issue by C0rn3j** [FreshRSS/FreshRSS#2835]
For example, I want to follow Firefox releases, which are on 
https://groups.google.com/forum/#!forum/mozilla.announce

but FreshRSS doesn't seem to be able to translate this into 
https://groups.google.com/forum/feed/mozilla.announce/msgs/rss.xml

```
2020-03-22 10:22:43
A feed could not be found at `https://groups.google.com/forum/#!forum/mozilla.announce`; the status code is `200` and content-type is `text/html; charset=utf-8` [https://groups.google.com/forum/#!forum/mozilla.announce]
```

**Comment by Frenzie** [comment]
That's because if they wanted that to be detectable, they would have included something like this in the HTML:
```html
<link rel="alternate" type="application/rss+xml" title="RSS 2.0" href="https://groups.google.com/forum/feed/mozilla.announce/msgs/rss.xml">
```
It's a conscious decision by Google. Not a FreshRSS issue.

See https://github.com/cn-tools/cntools_FreshRssExtensions/tree/master/xExtension-YouTubeChannel2RssFeed for a very simple way to work around Google.

**Comment by Alkarex** [comment]
Indeed, that requires an extension.
Here is a quick code snippet, which should do the job:

```php
<?php
class GoogleGroupsExtension extends Minz_Extension {
	public function init() {
		$this->registerHook('check_url_before_add', array('GoogleGroupsExtension', 'findFeed'));
	}

	public static function findFeed($url) {
		return preg_replace('%^(https://groups.google.com/forum)/#!forum/(.+)$%i', '$1/feed/$2/msgs/rss.xml', $url);
	}
}
```

Would you be able to submit a pull request, @C0rn3j ?

**Comment by C0rn3j** [comment]
I've just migrated from tt-rss today (still migrating) and completely unfamiliar with the code base, so am probably not the best person for the job

**Comment by Alkarex** [comment]
Implemented in https://github.com/FreshRSS/FreshRSS/pull/2838
Feedback welcome. I will soon merge in our /master branch, if that can make it easier for you to test @C0rn3j

**Comment by Alkarex** [comment]
Merged in our /master branch. Could you please give it a try, @C0rn3j ?

**Comment by C0rn3j** [comment]
Sadly I'm running off the stable releases, not git.

I see that the 1.16.0 release the fix is in is marked for next week, so I'll happily test when that comes around if that's good enough.

Thanks for a super quick fix!

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/5457
