### ISSUE TITLE
[GReader API] Return the unread articles count for the unlisted feed.

### ISSUE THREAD

**Issue by christophehenry** [FreshRSS/FreshRSS#2839]
The unlisted category (in French it appears as « Sans Catégorie ») appears in the tag list returned by `/reader/api/0/tag/list`:

```json
{
  "tags": [
    {
      "id": "user/-/state/com.google/starred"
    },
    {
      "id": "user/-/label/Sans catégorie",
      "type": "folder"
    },
    {
      "id": "user/-/label/Misc",
      "type": "folder"
    },
    {
      "id": "user/-/label/Vids",
      "type": "folder"
    },
  ]
}
```

but it does not in the labels returned by `/reader/api/0/unread-count`.

```json
{
  "max": 56,
  "unreadcounts": [
    {
      "id": "user/-/label/Misc",
      "count": 35,
      "newestItemTimestampUsec": "1584893731000000"
    },
    {
      "id": "user/-/label/Vids",
      "count": 21,
      "newestItemTimestampUsec": "1584893731000000"
    },
    {
      "id": "user/-/state/com.google/reading-list",
      "count": 56,
      "newestItemTimestampUsec": "1584893731000000"
    }
  ]
}
```

This makes its display inonsistent in FreshRSS Android.

**Comment by Alkarex** [comment]
Hum, indeed, but apparently only in the case when there is no feed in the default category, right?

**Comment by Alkarex** [comment]
@christophehenry Could you please try this fix? https://github.com/FreshRSS/FreshRSS/pull/2840
Both responses should now be consistent, not showing the default category when there is no feed in it, and also making sure that the same default category name is used with proper internationalisation

**Comment by Alkarex** [comment]
P.S. Updated to fix the same inconsistency with `subscription/list` as well

**Comment by Alkarex** [comment]
P.S.: `unread-count` should not be necessary for the type of client you are doing, because it is redundant with some of the other needed requests https://github.com/FreshRSS/FreshRSS/issues/2566#issuecomment-541317776

**Comment by christophehenry** [comment]
In my case, it's a choice. Firstly, because even though there is no paging currently and I always keep every post in DB, it's not excluded it changes in the future. In which case, having a computed unread count could display data that is inconsistant with the server. Secondly because stored data uses less hardware resources than computed data. Which is not luxury considering that many parts of FreshRSS Android could certainly be optimized :/

Can you provide me a diff file I can apply on my server?
**Edit:** forget it. I'l just clone your repo and make the diff myself. Will be faster.

**Edit 2:** Nice. It seem to work! :clap:

**Comment by Alkarex** [comment]
I did not see your edit; thanks for the feedback :-)
Related https://github.com/FreshRSS/FreshRSS/pull/2854
