### ISSUE TITLE
Image disappears when accessing by the web

### ISSUE THREAD

**Issue by andrewsrigom** [FreshRSS/FreshRSS#2846]
On Web

![image](https://user-images.githubusercontent.com/47692441/77425398-6b983e80-6db1-11ea-8509-1da5c6e23e8d.png)

On Localhost

![image](https://user-images.githubusercontent.com/47692441/77425481-8d91c100-6db1-11ea-90cd-7f57b3a4524d.png)

**Comment by Alkarex** [comment]
Please have a look at your Web browser console and networking tools. There are probably some errors there.
I am suspecting a bad proxy configuration.

**Comment by Frenzie** [comment]
@bosconb Did you check if it's the same in another browser, and what errors are there in the console in developer tools?

**Comment by bosconb** [comment]
> @bosconb Did you check if it's the same in another browser, and what errors are there in the console in developer tools?

i think i've find out the problem, yup, you're right,i used to connect host ip instead of site domain, so
chrome informed unsafe,and banned some images url such as 
`http://hostip/FreshRSS/p/f.php?e5e7fc99`

thanks a lot!!
