### ISSUE TITLE
Feeds no longer auto-updating!

### ISSUE THREAD

**Issue by Aasemoon** [FreshRSS/FreshRSS#2849]
Hi there,
For a long time now, I have been auto-updating my feeds via a cron job that runs "actualize_script.php" every half an hour. Recently, the feeds stopped updating [I can only update them manually now]. I use a shared host and they recently upgraded cpanel et al, and I thought that somehow this had broken my cron job. Turns out it hasn't, the cron job is still running every 30 minutes [and I even tried setting up a new one]. Meanwhile there's nothing at all in my error log. 

So does anyone have an idea why auto-updating has suddenly stopped working for me? I'd appreciate any suggestions.

Cheers!

**Comment by Frenzie** [comment]
Not off the top of my head. Is it somehow possible the cron job is executed by a different user?

**Comment by Alkarex** [comment]
In addition to what @Frenzie wrote, it could be that the cron job is run by another PHP version without the same extensions.
I also recommend saving the output of your cron into a file https://freshrss.github.io/FreshRSS/en/admins/08_FeedUpdates.html
@Aasemoon Please try to do so and look at the content of that file. That file should always contain something. For instance:

```sh
sudo docker exec freshrss cat /tmp/FreshRSS.log
```
```
Starting feed actualization at 2020-03-25T20:04:01+01:00
Actualize alex...
Actualize alice...
Done.
Ending feed actualization at 2020-03-25T20:04:24+01:00
Feed actualizations took 0 day(s), 0 hour(s), 0 minute(s) and 22 seconds for 2 users
Results:
alex OK
alice OK
End.
```

**Comment by Aasemoon** [comment]
@Alkarex Sure, I'll try this now and see what I get. 
Thanks for your suggestions!

**Comment by Aasemoon** [comment]
@Alkarex So I have tried what you suggested and I get:
```
Starting feed actualization at 2020-03-26T05:00:02-06:00
Actualize Aasemoon...
Actualize demo...
Actualize Baaroon...
Done.
Ending feed actualization at 2020-03-26T05:00:06-06:00
Feed actualizations took 0 day(s), 0 hour(s),  0 minute(s) and 4 seconds for 3 users
Results: 
Aasemoon OK
demo OK
Baaroon OK
End.
```
Meanwhile I have noticed that the feeds did seemingly get updated, but just once in more than 24 hours!

**Comment by Alkarex** [comment]
@Aasemoon Are you sure that your cron is actually running at the frequency that you expect?
You can double-check that with the last timestamp in the cron output file

**Comment by Aasemoon** [comment]
@Alkarex Yup, fairly certain. I set up an email to send me the output of the cron every time the task is run. I have been receiving the email every half an hour with the appropriate time stamps et al. Since then what I've noticed is that, as I mentioned, the feeds actually do get updated. But the frequency seems to be completely random, and generally no more than once in a day.

**Comment by Alkarex** [comment]
@Aasemoon Please check the max refresh settings:
* At top level
![image](https://user-images.githubusercontent.com/1008324/78241878-60e05680-74e1-11ea-8931-4127ec92f18f.png)
* At feed level
![image](https://user-images.githubusercontent.com/1008324/78241953-84a39c80-74e1-11ea-8b59-86e2b46d7e05.png)

**Comment by aledeg** [comment]
@Aasemoon What is the status on that issue?
If it's solved, could you share how you did it?
If it's still relevant, could you give us more information?

**Comment by Aasemoon** [comment]
@aledeg Yes, this issue has been resolved, but honestly I'm not sure how. The same way the updates stopped randomly, after some time they started again randomly. This was about an installation on a shared host, and I think in the end it may have been something the host was tweaking at the time.

**Comment by aledeg** [comment]
Thank you. Good to know!
