### ISSUE TITLE
Ne pas 'switcher' au nouvelle onglet lors de l'ouverture des liens

### ISSUE THREAD

**Issue by izissise** [FreshRSS/FreshRSS#285]
Lorsque l'on ouvre un lien (avec espace par exemple), le navigateur switch a ce nouvelle onglet (même en ayant désactiver cette fonctionnalité dans le navigateur),
Est'il possible de rajouter une option pour changer ce comportement ?

**Comment by math-GH** [comment]
Is it similar to #1256?
