### ISSUE TITLE
What should I do to cache the media files (pictures, videos) in the feed to the server of freshrss?

### ISSUE THREAD

**Issue by Whichbfj28** [FreshRSS/FreshRSS#2850]
Hello. What should I do to cache the media files (pictures, videos) in the feed to the server of freshrss?

**Comment by Frenzie** [comment]
I wrote an extension that could help facilitate that, whether as inspiration or just by plugging in a caching proxy: https://github.com/FreshRSS/Extensions/tree/ade2979857e91d838c1835f773797fc70cd7145b/xExtension-ImageProxy

**Comment by Whichbfj28** [comment]
> I wrote an extension that could help facilitate that, whether as inspiration or just by plugging in a caching proxy: https://github.com/FreshRSS/Extensions/tree/ade2979857e91d838c1835f773797fc70cd7145b/xExtension-ImageProxy

Can it save me the media files (pictures, videos) in the feed. I want to save it. In case there is a problem with the source URL, you can read the cache. ttrss has such a function

**Comment by Frenzie** [comment]
Not without adapting it or by setting up a caching proxy.

**Comment by Whichbfj28** [comment]
> Not without adapting it or by setting up a caching proxy.

Thank you for your answer. I also read the extension you wrote. I am a novice. I don’t know how to use it

**Comment by Frenzie** [comment]
The extension reroutes images through a proxy. The default proxy will cache those images for a little while, but not indefinitely. There's no facility to do anything what you've asked here unfortunately; I just mean you'd have to figure out the URLs and such in a similar manner.

**Comment by Frenzie** [comment]
Closing in favor of #3798 which goes slightly more in-depth.
