### ISSUE TITLE
Is there anyway to get full-text on my feeds in FreshRSS?

### ISSUE THREAD

**Issue by tdoerrich** [FreshRSS/FreshRSS#2851]
I have tried looking for a plugin or such but I didn't find anything. Does anyone know if I can somehow enable full-text on all my feeds? So I never have to leave my FreshRSS instance to read articles.

**Comment by tdoerrich** [comment]
I just found these, but I'm not sure how to use them togheter with FreshRSS: 

1. https://bitbucket.org/fivefilters/full-text-rss/src/master/
2. https://github.com/RSS-Bridge/rss-bridge

Do I need to install those as well?

**Comment by Frenzie** [comment]
There's the built-in article retrieval under the advanced header in the settings for individual feeds. In the upcoming 1.16 it'll have a preview functionality. Full-Text RSS is similar to that.

rss-bridge is more about websites that don't have feeds but should. For example I use it for the French Wikipedia article of the day.

**Comment by marienfressinaud** [comment]
As pointed out by @Frenzie, I would recommend you to try the built-in feature even if it's a bit painful currently (you can find [the documentation here](https://github.com/FreshRSS/FreshRSS/blob/master/docs/en/users/05_Configuration.md#retrieve-a-truncated-stream-from-within-freshrss))

There's already a (old) [ticket about integrating Full-Text / Graby](https://github.com/FreshRSS/FreshRSS/issues/947) in FRSS so I'm closing this one. Let us know if you need more precisions!
