### ISSUE TITLE
GH link to contributing doc 404s, Website link to same downloads .md

### ISSUE THREAD

**Issue by mrjones-plip** [FreshRSS/FreshRSS#2856]
On the [main GH project page](https://github.com/FreshRSS/FreshRSS) when you're excited to see how to contribute and click on the `Contributor guidelines` link under [Documentation](https://github.com/FreshRSS/FreshRSS#documentation) it goes to `https://freshrss.github.io/FreshRSS/en/contributing.html`.  This page 404s.

Related is that when you're on the [English documentation page](https://freshrss.github.io/FreshRSS/en/) and click on `Contributor guidelines` it goes to `https://freshrss.github.io/FreshRSS/en/contributing.md` which can't be viewed, so for me my browser attempts to download the .md file.

I think these are related and could be fixed by ensuring the .html version that works instead of the .md version. Though...I don't quite know how github.io pages work - shouldn't the .html version already work?

**Comment by mrjones-plip** [comment]
If this can be fixed by a non-member of the project like me, I'll be happy to try and fix it! However, I think that this is some sort of GH issue which you need to kick the .io site build process to restart or something.

**Comment by Frenzie** [comment]
The site build process is automatically initiated by a commit to master. All you need to do is change the link in the file.

**Comment by mrjones-plip** [comment]
Thanks @Frenzie !  I'll submit a PR with a link to the .html shortly then!

**Comment by Frenzie** [comment]
Oh, but hold on. In this case it may just be something in the Page builder action that's misconfigured.

Edit: pinging @Alkarex since I don't have sufficient permissions to check.

**Comment by mrjones-plip** [comment]
@Frenzie  - oh - all good! I'll wait to hear back from Alkarex.

**Comment by Frenzie** [comment]
Well, besides the incorrect link to `.md` anyway. ;-)

**Comment by mrjones-plip** [comment]
Right, so changing the link from `.md` to `.html` should just fix it? I dunno as I don't ever work with github.io pages.  Lemme know! Or I wait to hear back from Alkarex. Or both!

**Comment by Alkarex** [comment]
Related to https://github.com/FreshRSS/FreshRSS/pull/2685#issuecomment-558231186
Hum @Frenzie , we are using the default GitHub pages, so there should not be much special to configure:

![image](https://user-images.githubusercontent.com/1008324/77859637-da8af280-720a-11ea-8e14-f54bac7194cf.png)

I am wondering maybe whether there might be something special with the name `contributing.md`

**Comment by Frenzie** [comment]
Indeed, looks like we have to do this: https://github.com/MasterEx/test-docs/blob/4dff00b8897630ee43ca69523c1efe49cc87f304/docs/_config.yml

**Comment by mrjones-plip** [comment]
oh - cool! Good to know if I bump into this on another project.

**Comment by Alkarex** [comment]
@Frenzie Isn't it easier just to give another name to the file?

**Comment by mrjones-plip** [comment]
\o/ it all works now - thanks you two!
