### ISSUE TITLE
Updating on Linux guide `wget` command doesn't work

### ISSUE THREAD

**Issue by mrjones-plip** [FreshRSS/FreshRSS#2857]
On the [linux update page](https://freshrss.github.io/FreshRSS/en/admins/07_LinuxUpdate.html), there's a command to download the zip file:

`wget -o freshrss.zip https://github.com/FreshRSS/FreshRSS/archive/1.15.3.zip
unzip freshrss.zip`

This however doesn't work because the `-o` flag in wget isn't the same as curl's.  For wget it's:

```
-o logfile
--output-file=logfile
    Log all messages to logfile.  The messages are normally reported to standard error.
```

I think the fix here is to just swap `wget` for `curl`.  Oh, Also, the URL we use is a redirect, so we'll have to pass in a `-L` flag so that curl follows the redirect too.

**Comment by mrjones-plip** [comment]
I'll submit a 4 char PR shortly ;)

**Comment by Alkarex** [comment]
Thanks for the bug report :-)

**Comment by mrjones-plip** [comment]
For sure!  THANK YOU for such amazing software. I use it daily, many times.  This is the least I could do.

**Comment by Alkarex** [comment]
Thanks for the kind words, @Ths2-9Y-LqJt6 👍
