### ISSUE TITLE
Dark Theme navigation buttons on mobile not working

### ISSUE THREAD

**Issue by travnewmatic** [FreshRSS/FreshRSS#2860]
https://github.com/FreshRSS/FreshRSS/tree/master/p/themes/Dark

they're visible, but they seem to be 'behind' the article list
![11692108311766](https://user-images.githubusercontent.com/11083305/77881529-c3431800-7291-11ea-95af-bcdb00047426.jpg)
previously, the buttons were on top of the article list.  now, when i try to press the 'next article' button, it doesnt hit the next article button, i hit the title of the article that's in the way of the button.

seriously love freshrss i use it every day!  thanks so much for all the hard work!  please let me know what other information i can provide :)

Thanks!

**Comment by marienfressinaud** [comment]
Hi! Thanks for pointing out the issue, I take a look :)
