### ISSUE TITLE
Encoding issue with CSS selector

### ISSUE THREAD

**Issue by adaigre** [FreshRSS/FreshRSS#2864]
Hi !

For some time now I have a encoding issue with full text content retrival.
It only happens with France 3 Régions feeds, like [https://france3-regions.francetvinfo.fr/nouvelle-aquitaine/vienne/rss]()

The selector I use is : `.article-style`
Title looks okay but article content has wrong encoding.

![image](https://user-images.githubusercontent.com/803151/77998172-f1c40000-7330-11ea-87ce-a6e111ef4f8e.png)

Thanks for your help !

**Comment by Alkarex** [comment]
Thanks for the bug report. Fixed by https://github.com/FreshRSS/FreshRSS/pull/2867
Tests welcome

**Comment by Alkarex** [comment]
Et bon confinement avec FreshRSS ;-)

**Comment by adaigre** [comment]
Incredibly fast ! I will try the Docker container with "latest" tag tomorrow ;)

Merci pour le travail et bon confinement !
