### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by ddeimeke** [FreshRSS/FreshRSS#2865]
Source of this ticket is the recent change to change the shortcut to mark a feed as read from "shift+r" to "alt+r". @Alkarex asked me to open this ticket to gather some opinions on this.

My opinion:

When it comes to movement "j" jumps to the next article, "shift+j" to the next feed and "alt+j" to the next category.

I would expect to have "mark as read" work the same way. "r" marks the next article as read and moves forward, "shift-r" marks the feed as read and jumps to the next feed, "alt+r" does the same on category level.

**Comment by Alkarex** [comment]
This is related to the introduction of a new shortcut to mark *previous* articles as read https://github.com/FreshRSS/FreshRSS/pull/2843

> The shortcut <kbd>⇧ Shift</kbd>+<kbd>R</kbd> now marks previous articles as read.
The previous action of marking all articles as read is now achieved by <kbd>Alt ⎇</kbd>+<kbd>r</kbd>
So this is a slight breaking change, but I like the logic of the upward-facing <kbd>⇧ Shift</kbd> arrow to hint at previous articles, while <kbd>Alt ⎇</kbd> is more like "all", at least to my eyes :-)

**Comment by Alkarex** [comment]
What do you think @aledeg @marienfressinaud @Frenzie ?

**Comment by aledeg** [comment]
I didn't follow any of the previous discussion so I am not well aware of what's going on. But my thoughts are to always keep things as consistent as possible. So it looks like we should modify the shortcuts to reflect something that is more straight-forward.

**Comment by Alkarex** [comment]
@aledeg I have introduced a new shortcut to mark *previous* articles as read, something that was not possible before:

> The shortcut <kbd>⇧ Shift</kbd>+<kbd>R</kbd> now marks previous articles as read.
The previous action of marking all articles as read is now achieved by <kbd>Alt ⎇</kbd>+<kbd>r</kbd>
So this is a slight breaking change, but I like the logic of the upward-facing <kbd>⇧ Shift</kbd> arrow to hint at previous articles, while <kbd>Alt ⎇</kbd> is more like "all", at least to my eyes :-)

![image](https://user-images.githubusercontent.com/1008324/78158296-540c2600-7441-11ea-88b6-f898dca43831.png)

**Comment by Alkarex** [comment]
@ddeimeke I do not think we have had the ability to have read actions on feeds or on categories, have we? Only on the current article / current view.

**Comment by ddeimeke** [comment]
@Alkarex At least for me "shift+r" was "mark unread articles in current feed as read", maybe I interpreted it the wrong way.

Would it be possible to make it completely configurable? Not only the letter "r", but also "no modifier ke/shift/alt"? Not for 1.16, but maybe for 1.18?

**Comment by marienfressinaud** [comment]
> I like the logic of the upward-facing ⇧ Shift arrow to hint at previous articles, while Alt ⎇ is more like "all", at least to my eyes :-)

While I understand the logic, I think it's pretty unusual and so, hard to understand without the explanation. The initial logic was "r" versus "upper R" → "single toggle read" versus "higher scope toggle read".

Also I don't think it's a good idea to change the behaviour of the "shift + r" like that which, I think, is one of the most used shortcut: we'll probably get a lot of feedback telling us it doesn't work anymore without noticing the change on the shortcut page (which I never open personally). We can see it as consistency over time.

So here, I would instead just add the new shortcut on "alt + r" mapping as an "alternative toggle read".

**Comment by Frenzie** [comment]
My main consideration when I read through the PR was that "previous articles" is a subset of "all articles." You wouldn't accidentally mark all as read because of the change, so it's non-destructive. I neglected to look at similar shortcuts within the program for consistency, and perhaps I didn't give sufficient weight to the principle of not changing things.

I'm still fairly neutral on the matter but the fact that it's been brought up suggests I probably thought too lightly of it.

**Comment by Alkarex** [comment]
For reference, here is the documentation for a few other related software (it looks like the most common for marking everything as read is <kbd>⇧ Shift</kbd>+<kbd>A</kbd>)

* https://www.gtricks.com/google-reader-tricks/shortcut-keys-for-google-reader/
* https://blog.feedly.com/keyboard-shortcuts/
* https://blog.inoreader.com/2015/05/inoreader-how-to-save-time-with.html

If any of you can find references of what is most common (maybe in other, but related type of software such as e-mails, forums...), I would be interested.

If I understand properly @marienfressinaud , you would like:
* <kbd>⇧ Shift</kbd>+<kbd>R</kbd> to mark all articles as read;
* <kbd>Alt ⎇</kbd>+<kbd>r</kbd> to mark previous articles as read.

Right? Is it also what you want @ddeimeke ?

**Comment by Alkarex** [comment]
By the way, it would be nice to have a way to engage our users for small polls once in a while, to get some feedback

**Comment by ddeimeke** [comment]
> For reference, here is the documentation for a few other related software (it looks like the most common for marking everything as read is ⇧ Shift+A)

Yes, and they use "m" for marking a single article as read.

> Right? Is it also what you want @ddeimeke ?

That would be great.

In the end the best way would be to make it completely configurable, including the modifier key like shift or alt. You could even implement the possibility to choose between different "shortcut modes" like Google Reader or Feedly or Innoreader. But, I honestly do not think that very many persons would use this feature.

**Comment by ddeimeke** [comment]
> By the way, it would be nice to have a way to engage our users for small polls once in a while, to get some feedback

What about [Framadate](https://framadate.org/) for polls?

**Comment by Alkarex** [comment]
Should be fixed by https://github.com/FreshRSS/FreshRSS/pull/2881
Tests welcome
