### ISSUE TITLE
Negation for searching by date intervals

### ISSUE THREAD

**Issue by deanishe** [FreshRSS/FreshRSS#2866]
FreshRSS version 1.15.3

Durations are no longer recognised for end filters (i.e. after the slash).

Here, it's showing me an entry from today when it shouldn't be showing anything newer than a week:

![freshrss-broken-filter](https://user-images.githubusercontent.com/747913/78068335-844bba00-7398-11ea-82b1-0f41e937beb4.png)

**Comment by Alkarex** [comment]
@deanishe Did that syntax ever work (at least in FreshRSS)?
This got me confused for a moment :-P
Empty string is like *now*, and the second part is a duration if it starts by `P`, so `date:/P1W` means *from now and one week ahead*.
Just like `date:2020-01-01/P1W` means the first seven days of 2020.

I believe we would need a negation to implement what you ask, like `!date:P1W` (with or without trailing `/`), meaning *not in the past 7 days*.

This is not something we have right now, but that could be added. (Edit: done)

For reference http://en.wikipedia.org/wiki/ISO_8601#Time_intervals

**Comment by deanishe** [comment]
> Did that syntax ever work (at least in FreshRSS)?

I thought so. I was using after our conversation in #2596. Presumably it never was, but I'd already cleaned up by that point and never noticed.

> Could you please give it a try

Works like a charm. Thank you very, very much indeed!
