### ISSUE TITLE
feeds' favicon cannot show up

### ISSUE THREAD

**Issue by bosconb** [FreshRSS/FreshRSS#2872]
same issue as [Image disappears when accessing by the web](https://github.com/FreshRSS/FreshRSS/issues/2846)

my freshRSS version is 1.15.4-dev. and I've checked PHP installation and File installation,everything is OK, what's more, i didnt set any proxy, i've no idea what's wrong.

really appreciated for ur help

![image](https://user-images.githubusercontent.com/47100031/78325180-8173e380-75a9-11ea-9681-6bca74a9e7dd.png)

**Comment by Frenzie** [comment]
You don't need to create a new issue if it's the same. A comment with additional information is fine, preferable in fact because it makes the issues list easier to navigate. So I'll close this one. :-)
