### ISSUE TITLE
Display a wider audio

### ISSUE THREAD

**Issue by Elinvention** [FreshRSS/FreshRSS#2875]
I've been using this excellent software for years (thank you very much), but now I started following a podcast. For me it works good enough, but I'd like the audio element to be wider, because right now it's difficult to skip parts of the audio.

**Comment by aledeg** [comment]
@Elinvention Could you provide such feed so we can see what we can do?

**Comment by Elinvention** [comment]
Sure, this is it http://nihongoconteppei.com/feed/podcast
I also add a screenshot: 
![image](https://user-images.githubusercontent.com/5737945/78453799-75188500-7694-11ea-8500-a10b48369520.png)

As you can see the playback bar is too short, so I usually open Firefox's console and put `width: 100%` on the element. The problem with this is that I have to do it manually for each one, because Firefox doesn't let me add new rules.

**Comment by Alkarex** [comment]
Hello @Elinvention :-)
Ah, I believe I understood `podcasto`, `Arigatō`, and `Patreon` :-P
Would you be able to try this patch? https://github.com/FreshRSS/FreshRSS/pull/2877
