### ISSUE TITLE
Search input box display issue in Safari

### ISSUE THREAD

**Issue by kinoushe** [FreshRSS/FreshRSS#2885]
The search input box doesn't display as expected in Safari, adding the following style rule fixes this issue:

```
.header > .item.search input {
	-webkit-appearance: none;
}
```
![Screen Shot 2020-04-09 at 10 28 14 pm](https://user-images.githubusercontent.com/25278192/78895138-a4bef700-7ab1-11ea-969f-a7d7f85b77e9.png)
![Screen Shot 2020-04-09 at 10 27 23 pm](https://user-images.githubusercontent.com/25278192/78895145-a983ab00-7ab1-11ea-8f28-829a57e562b1.png)

**Comment by javerous** [comment]
@kinoushe I agree on that.

Without talking instead of the core-team, I think you can just create a PR ?

**Comment by Alkarex** [comment]
Yes, PR welcome :-)
In https://github.com/FreshRSS/FreshRSS/blob/master/p/themes/base-theme/template.css and the same in https://github.com/FreshRSS/FreshRSS/blob/master/p/themes/base-theme/template.rtl.css
