### ISSUE TITLE
Enhance the way help elements are displayed

### ISSUE THREAD

**Issue by javerous** [FreshRSS/FreshRSS#2886]
Hello,

I already talked a bit about that on a previous PR, but I think the way the help elements are displayed need to be enhanced.

Currently (at least on Safari), they can look very bogus (not to say messy) :

<img width="345" alt="Screenshot 2020-04-09 at 15 42 31" src="https://user-images.githubusercontent.com/1971659/78923063-e6db3f00-7a97-11ea-8f5a-48dc85a90e4f.png">

<img width="360" alt="Screenshot 2020-04-09 at 15 42 35" src="https://user-images.githubusercontent.com/1971659/78923075-ecd12000-7a97-11ea-819f-8b0a96f5fb1c.png">

<img width="359" alt="Screenshot 2020-04-09 at 15 42 44" src="https://user-images.githubusercontent.com/1971659/78923081-f195d400-7a97-11ea-8347-150c8f034480.png">

→ They are wrapped in an unexpected place.

I would suggest to just show them (in a whole) on the next "line" each time we are using them. I'm not sure it would be the best solution, but for the advantages I see :
- They wouldn't be "stuck" in the right, without any place, specially on side panel : less wrapping.
- They wouldn't wrap in an unexpected place anymore (i.e. they would wrap with alignment to the "help" icon, instead of the associated element as it's currently the case).

Or perhaps the text can just be hidden, and shown as a real tooltip, when the cursor wait a bit (or click) on the "help" icon ?

**Comment by Alkarex** [comment]
This does not bother me, but changes welcome. Maybe it could be done at the same time as making this view more mobile-friendly https://github.com/FreshRSS/FreshRSS/pull/2800

**Comment by Frenzie** [comment]
Underneath would be slightly neater.

**Comment by javerous** [comment]
@Frenzie Okay, I will try a PR this weekend, even if I promised myself I will never-ever touch CSS again :s

Would it make sense to make this a global rule (like "help elements should always be placed underneath"), or should it be something done only in this panel (because restrained in size) ?

@Alkarex Why not, but then it would be far outside my little web skills ;)

**Comment by Alkarex** [comment]
@javerous Just wrapping the info icon and help text into something like `<p class="help">...</p>` might just do the job, even without touching CSS (much). Can you give it a try? :-)

**Comment by javerous** [comment]
@Alkarex Yes, I will try something like this !
