### ISSUE TITLE
[ authentification ] bannir IP

### ISSUE THREAD

**Issue by Cyrixo** [FreshRSS/FreshRSS#2901]
Bonjour,

Je cherche un moyen pour bannir les ip qui font une mauvaise identification.
Je n'ai rien trouvé, j'ai peut-être mal cherché…

Cela est-il possible avec fail2ban ?

**Comment by Alkarex** [comment]
Voir https://github.com/FreshRSS/FreshRSS/issues/1015
C'est devenu un peu plus compliqué après https://github.com/FreshRSS/FreshRSS/pull/2794#discussion_r389319248 mais je vais essayer de remettre un code HTTP d'erreur correct pour faciliter le travail de fail2ban

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/1016

**Comment by Cyrixo** [comment]
Merci d'avance !

**Comment by Alkarex** [comment]
Corrigé avec https://github.com/FreshRSS/FreshRSS/pull/2903
Auriez-vous la possibilité de tester ? Je peux mettre le patch dans notre branche /master si nécessaire.

Voici un exemple de mauvais login :
```
172.xx.xx.xx - - [16/Apr/2020:22:56:58 +0200] "POST /i/?c=auth&a=login HTTP/1.1" 403 5808 "-" "Mozilla/5.0 ..."
```

Du coup une simple règle `fail2ban` normale sur erreur 403 devrait suffire.

Il faut aussi vérifier qu'un login normal se passe bien, et qu'un mauvais mot de passe montre bien un message d'erreur à l'utilisateur et lui permette de réessayer.

**Comment by Cyrixo** [comment]
Je viens de tester mais rien dans le log d'erreur, ni dans l'acces.
Il faut bien juste ajouter la ligne `!ctype_graph($hash) ||` ?

**Comment by Alkarex** [comment]
@Cyrixo Non, cette ligne ne fait rien. C'est le reste du patch https://github.com/FreshRSS/FreshRSS/pull/2903/files qui est intéressant. Est-ce que cela aide si je mets le patch dans notre branche /master
Quel type d'installation avez-vous ? Git, Docker, ZIP... ?

**Comment by Cyrixo** [comment]
Oui je veux bien que vous mettiez le patch dans la branche master.
L'installation est sous raspbian buster 10 avec apache 2.4 et php 7.3

**Comment by Alkarex** [comment]
Voilà, c'est dans /master
Avez-vous installé FreshRSS en dézippant une archive, ou par git, ou par Docker, ou autre ?

**Comment by Cyrixo** [comment]
Oui en dézippant l'archive

**Comment by Cyrixo** [comment]
Super il y a bien un 403 dans access.log. Plus qu'a mettre la règle pour fail2ban.
Encore merci.

**Comment by Cyrixo** [comment]
Cette modification sera présente dans la version stable ?

**Comment by Alkarex** [comment]
Oui, ça sera dans la prochaine version.
