### ISSUE TITLE
validateEmail error page after upgrade

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#2902]
Hi,
I just tried to update manually (unluckily my install doesn't detect availability of new version for automatic update) my freshRSS install to version FreshRSS 1.16.0 and I'm stuck after step 4 of install   with an error message on page /p/i/?c=user&a=validateEmail
Apparently the page tries to redirect indefinitely without success. I've tried to remove the authentication in the config.php file  with :

```
  'allow_anonymous' => true,
  'force_email_validation'  => false,
  'allow_anonymous_refresh' => true,
  'auth_type' => 'form',
  'api_enabled' => false,
  'unsafe_autologin_enabled' => true,
```

but it doesn't change the error message.
I must have done something wrong, but what ??
Thanks

**Comment by marienfressinaud** [comment]
Can you check in your user configuration (`data/users/[your user]/config.php`) if `email_validation_token` is empty?

**Comment by ghost** [comment]
Yes !  Solved after removing the token
 Merci

**Comment by Alkarex** [comment]
@marienfressinaud Is that a bug anyway?

**Comment by marienfressinaud** [comment]
It depends on if @lmjst did activate the `force_email_validation` option at some point?

**Comment by marienfressinaud** [comment]
We could check its value here as well to avoid this kind of situation https://github.com/FreshRSS/FreshRSS/blob/master/app/FreshRSS.php#L138

**Comment by Alkarex** [comment]
It would probably be better to skip this test for admin accounts, don't you think?

**Comment by ghost** [comment]
Hello, I doubt I activated this option.

**Comment by marienfressinaud** [comment]
I created a PR to avoid this issue happens again. If you didn't activate this option, or didn't set the value manually, I can't tell how it has been set since it is done only [in one place](https://github.com/FreshRSS/FreshRSS/blob/master/app/Controllers/userController.php#L28) and we check the option is enabled before… so this is a mystery to me :)
