### ISSUE TITLE
Is there an accessible way to investigate browser crashes?

### ISSUE THREAD

**Issue by Frenzie** [FreshRSS/FreshRSS#2904]
When I try to open FreshRSS in Blink browsers, I often see something like this:

![vivaldi_3ihmqCXiFk](https://user-images.githubusercontent.com/202757/79555415-d894b080-809f-11ea-91bd-efd48be2fa76.png)

This particular screenshot is from Vivaldi, but I've seen it in various Blink browsers.

Unfortunately you can't investigate it using normal tools like a JS Profiler. 

Anyway, I was wondering if any of you guys know of a way to track down what might be causing the crash without getting into Chromium development.

**Comment by Alkarex** [comment]
Hum, I have never experienced that with a FreshRSS page, and I do not know how to debug that...

**Comment by Frenzie** [comment]
It's not a Linux bug or something either, this screenshot was on Windows. I haven't seen it on Android though.

**Comment by rexbron** [comment]
Try opening the developer console for error messages?

**Comment by Frenzie** [comment]
I'm sorry, but you have clearly never encountered a browser crash. Best
case scenario the dev tools will be disconnected from the page, but they
just as lief join the party.

**Comment by Frenzie** [comment]
Sorry, I didn't mean to sound harsh. But anyway, that doesn't work. ;-)

**Comment by Frenzie** [comment]
Anyway, I'll close it as just a Chromium issue. I'll keep an eye out.
