### ISSUE TITLE
Mark as read unseen articles

### ISSUE THREAD

**Issue by Offerel** [FreshRSS/FreshRSS#2905]
I don't know if this is the same as in #2429 but the effect is the same. The issue occurs after updating to the latest release version 1.16.  

For example, i have 7 new articles at the left side in "main feeds" but only 5 displayed in the mainframe. After clicking "Mark all as read" button at the top, all 7 articles marked as read, not only the 5 in the main frame...

**Comment by Alkarex** [comment]
If you are able to reproduce, please send a screenshot. What database are you using?

**Comment by Alkarex** [comment]
And if that happens again, please try to click the "optimize database" button in the archiving options, which recomputes some cached values

**Comment by Offerel** [comment]
OK, i tried your tips and optimized the database. I'm using SQLite, since it's a lot faster on Raspberry Pi as MySQL. After optimize, the issue persists.

![2 Articles in left pane and Mainframe](https://user-images.githubusercontent.com/14041522/79668998-e1c57080-81b8-11ea-9b1d-a9c7670a4662.jpg)
*2 Articles in left pane and Mainframe*

![screenshot_305](https://user-images.githubusercontent.com/14041522/79668997-e0944380-81b8-11ea-8b65-8d945b8b979d.jpg)
*a third article appears at the left, but isnt loaded in mainframe, clicking now "Mark as read"*

![screenshot_306](https://user-images.githubusercontent.com/14041522/79668993-deca8000-81b8-11ea-834a-ed6ed402a999.jpg)
*Page is reloaded and all 3 articles are marked read, instead of only 2 in the mainframe*

**Comment by Alkarex** [comment]
Ah, now I understand what you were saying! I will investigate

**Comment by Alkarex** [comment]
Thanks for the bug report. This is a regression from 1.16.0.
Could you please try this patch? https://github.com/FreshRSS/FreshRSS/pull/2909

**Comment by Offerel** [comment]
I can confirm, this seems to work. Many thx for this fix.

**Comment by Alkarex** [comment]
Thanks for the feedback :-)
