### ISSUE TITLE
Add Proxy per feed in subscriptions management

### ISSUE THREAD

**Issue by mengx8** [FreshRSS/FreshRSS#2908]
`curl_options` in `config.php`，use a proxy for retrieving feeds
but not all feeds need proxy

I would suggest to add proxy settings per feed in subscriptions management

![image](https://user-images.githubusercontent.com/16496935/79670867-7e5b3300-81f8-11ea-9ab9-cd164ccacee2.png)

**Comment by Alkarex** [comment]
We could add an option to bypass the global proxy configuration. That would be easier than adding a proxy configuration at feed level

**Comment by printfuck** [comment]
This is a good idea. But I would go further allow the user to set a **whole list** of `curl_setopt` options per feed.

**Pro:**
- You don't have to check for HTTP or SOCKS proxy types when configuring
- You can add headers or cookies to circumvent GDPR checks

**Contra:**
- It's more complex for the user to configure

**Comment by SuperSandro2000** [comment]
I don't think this should be a user setting because it could be easily vulnerable to command injection if done wrong and I don't know what the implications are when someone has the control how to route the traffic. It shouldn't be that high because he can already control the destination.
