### ISSUE TITLE
Impossible to add a feed even with force_feed

### ISSUE THREAD

**Issue by leguennecj** [FreshRSS/FreshRSS#2910]
Bonjour,

Je souhaiterais ajouté ce feed des marchés publics mais Freshfeed ne l'accepte pas.

https://www.marches-publics.gouv.fr/rssFn.xml

Avez vous une aide à m'apporter ?

Merci 👍

**Comment by Frenzie** [comment]
A peculiar case. The feed returns a 404 not found status code even though it seems to work as intended.

The code presumably assumes (for good reason!) that 404 means failure.

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.marches-publics.gouv.fr%2FrssFn.xml
https://validator.w3.org/feed/docs/error/HttpErrorWithPossibleFeed.html

**Comment by Alkarex** [comment]
Clairement un problème côté serveur. Il faudrait prévenir le site.
Je pense que le plus simple pour vous est de faire un mini proxy exprès pour ce flux

Placez par exemple le fichier suivant quelque part sur votre serveur avec le nom `marches-publics.gouv.fr.xml.php` :

```php
<?php
header('Content-Type: application/rss+xml; charset=utf-8');
$ch = curl_init('https://www.marches-publics.gouv.fr/rssFn.xml');
curl_setopt_array($ch, [
		CURLOPT_TIMEOUT => 15,
		CURLOPT_ENCODING => '',	//Enable all encodings
	]);
curl_exec($ch);
curl_close($ch);
```

Et puis accédez-y via votre navigateur https://votre-serveur.example.net/chemin/marches-publics.gouv.fr.xml.php` et si cela fonctionne, utilisez cette adresse comme flux dans FreshRSS.

**Comment by leguennecj** [comment]
Super ca a fonctionné merci beaucoup !
