### ISSUE TITLE
"Flash Of Unstyled Content" and slow loading in the Firefox because of <script defer>

### ISSUE THREAD

**Issue by krisu5** [FreshRSS/FreshRSS#2912]
FreshRSS version: 1.15.3 (Yunohost build)
Hardware: Raspberry Pi 3B+
Browser: Firefox 75

There has been lot of loading and display issues when browsing FreshRSS with Firefox.

Firefox loads content without styling first, causes lot of stress to Yunohost and often logs out after this happens.

I found the culprit: Firefox doesn't like script tags with "defer" value in them, so it tries to load scripts first then CSS.

There's stupidly easy but slightly hacky solution: add <script> with comment **only** into HTML after CSS styles but before the actual scripts.

Source: https://bugzilla.mozilla.org/show_bug.cgi?id=1404468#c78

Not only this fixes FOUT, it fixes slow loading issues (at least on my side).

Submitting pull request soon.

**Comment by Alkarex** [comment]
Thanks @krisu5  , that is interesting!

Have you checked whether all the JS and CSS is properly cached?
If not too much work, would you be able to make a short screencast of the issue?

On my side, I cannot produce a FOUC, even when lowering down the network connectivity (not using YunoHost though). Would you by any chance be able to test a FreshRSS version 1.16.x (or our master branch)? From 1.16.0, I have changed the loading quite a lot, streaming the data back to the client much faster.

Also, I would be interested in finding out whether this is YunoHost-specific or not. Would you be able to spin an intendant FreshRSS instance? If not, I could at least make you a test account on my own server so you can compare.

**Comment by Frenzie** [comment]
Except for testing, I primarily use FreshRSS with Firefox. I think I've never seen a flash of unstyled content in the past four or five years that I've been using it.

**Comment by krisu5** [comment]
Maybe this is Yunohost issue, I was posting there first, but I wasn't sure. In the Yunohost side, there has been lot of javascript issues with FreshRSS.

**Comment by krisu5** [comment]
I haven't tested other then with my Yunohost build yet, but it's still happening with totally clean reinstalled Firefox (no adblockers even).

Normal: https://streamable.com/3isyp9 (notice how it's getting worse over time, not at the beginning)
With the fix: https://streamable.com/2wnaak

**Comment by Frenzie** [comment]
Yeah, the second one is what it looks like for me. I can't trigger that with Ctrl+F5 either; at most I might see a few hundred ms of white really. :-/

**Comment by Alkarex** [comment]
@krisu5 Thanks for the screencasts 👍 
It should not be detrimental to add this hack, so let's go for it, but please remember to keep an eye on it if you can, to double-check whether it actually makes any difference (maybe tracking this Firefox ticket)

**Comment by krisu5** [comment]
> 
> 
> @krisu5 Thanks for the screencasts 👍
> It should not be detrimental to add this hack, so let's go for it, but please remember to keep an eye on it if you can, to double-check whether it actually makes any difference (maybe tracking this Firefox ticket)

Okay, I follow the situation.

**Comment by shreyasminocha** [comment]
I'm still seeing this with `1.16.2` checked out.

I see 39df5a80419cf7936a2698d2c8fce4679a723868. I tried editing `/app/layout/layout.phtml` to include the script tag and restarting nginx, but to no avail.

**Comment by Alkarex** [comment]
@shreyasminocha Have you checked that your CSS files are properly cached? Can you try to produce a screen recording? How is your system (OS, server, DB...)

**Comment by shreyasminocha** [comment]
@Alkarex Sorry for being vague.

Here's a screenshot of Dev Tools' network tab after requesting two pages (`/i` and `/i/?c=subscription`):

<details>
<summary>Dev tools screenshot</summary>
<img src="https://user-images.githubusercontent.com/11537232/84496835-2d6a3700-ac9d-11ea-852e-597cb783f975.jpg" alt="CSS being cached according to Dev tools" />
</details>

It does look like they're being cached.

---

<details>
<summary>Screen recording</summary>	
<img src="https://user-images.githubusercontent.com/11537232/84497644-bc2b8380-ac9e-11ea-828c-08915b1da055.gif" alt="FOUC demo"/>
</details>

---

- FreshRSS 1.16.2 from the git repo
- Debian 4.19.98-1
- nginx/1.14.2
- MySQL 8.0.20
- PHP 7.3.14-1

My NGINX configuration is practically identical to [the one in the docs](https://freshrss.github.io/FreshRSS/en/admins/10_ServerConfig.html#nginx-configuration). I don't have any extra location blocks or other rules.

- Firefox Quantum 68.6.0esr
- macOS Mojave

I cannot reproduce this in Chromium.

**Comment by Alkarex** [comment]
@shreyasminocha Do you observe the same issue when browsing between pages (as opposed to refreshing the page)?

**Comment by shreyasminocha** [comment]
> Do you observe the same issue when browsing between pages

Yes, unfortunately. @Alkarex

**Comment by shreyasminocha** [comment]
@Alkarex I suddenly can't reproduce these issues any more. I didn't update FreshRSS or do anything else significant. I did fix configuration issues with the greader and fever APIs, but I doubt that has to do anything with this. Regardless, I'm glad it's gone 😄.

**Comment by Alkarex** [comment]
Thanks for the feedback. It might also be due to a special combination of parameters such as network/server speed, response size, buffering at various levels...
