### ISSUE TITLE
Feature Request: Show last login (use) date of a user.

### ISSUE THREAD

**Issue by ddeimeke** [FreshRSS/FreshRSS#2914]
I have a couple of users in my instance. It would be nice to identify inactive users for a cleanup.

**Comment by Alkarex** [comment]
Hello,
At least from command-line, we already have this feature implemented.

https://github.com/FreshRSS/FreshRSS/blob/master/cli/README.md

```sh
 cli/user-info.php -h --header
```

We could add this info into the user list in the admin interface.

Model:
https://github.com/FreshRSS/FreshRSS/blob/f8db9ddd8585a7e0fb90bbb51121bacf1e515254/cli/user-info.php#L58

Insert here as well:
https://github.com/FreshRSS/FreshRSS/blob/f8db9ddd8585a7e0fb90bbb51121bacf1e515254/app/Controllers/userController.php#L605-L621

Show here as well:
https://github.com/FreshRSS/FreshRSS/blob/f8db9ddd8585a7e0fb90bbb51121bacf1e515254/app/views/user/manage.phtml#L69-L97

Would you like to give it a shot?

**Comment by ddeimeke** [comment]
Hi @Alkarex 

The command-line works pretty well.

Thanks a lot.

Cheers

Dirk

**Comment by equinoxmatt** [comment]
@Alkarex congratulations on this great software. I have been using it recently for my RSS feeds. 

Am I right in saying using `FreshRSS_UserDAO::mtime($username)` is going to give you when the user data file was last modified, not when they last logged in?

As far as I understand it, the configuration file is not modified upon user login?

I am considering adding a new field to the user config file, 'last_loggedin' or something similar. Would this be a welcome addition?

**Comment by Alkarex** [comment]
@equinoxmatt `FreshRSS_UserDAO::mtime($username)` can be used to return the last user action, anything that modifies the database (e.g. marking an article as read, adding a feed, etc.). We touch the user configuration file every time a user action with a side effect is happening
