### ISSUE TITLE
User Interface Error with recent Git checkout

### ISSUE THREAD

**Issue by ddeimeke** [FreshRSS/FreshRSS#2915]
When I expand a category with unread articles, I see all feeds with unread articles.

When I click on one feed with unread articles, the category collapses again.

This a new behaviour, before the update I kept seeing all feeds with unread items in the expanded category.

**Comment by Alkarex** [comment]
Might be due to https://github.com/FreshRSS/FreshRSS/pull/2888
Could you please check what settings you have there (before updating them)?

**Comment by ddeimeke** [comment]
I had "Categories to unfold" set to "Active Category".

Now, I switched "Show articles unfolded by default" and it seems to solve my issue.

**Comment by ddeimeke** [comment]
I updated again and deactivated "Show articles unfolded by default" and it works again as wanted.

Thanks @Alkarex
