### ISSUE TITLE
User log file always empty

### ISSUE THREAD

**Issue by triatic** [FreshRSS/FreshRSS#2924]
I've just reinstalled FreshRSS and I've found the log file in Settings > Logs is always empty.

data/users/username/log.txt keeps changing its last modified date but it's always 0 bytes. log.txt **is** writeable by the web server process.

Version is 1.16.1-dev

**Comment by Alkarex** [comment]
Hello,
If the last modified date changes, then it means that FreshRSS can use the file properly (we `touch()` this file for internal cache information).
When there are no errors or warnings, there is nothing in those logs.

You can turn on `'environment' => 'development',` in `./FreshRSS/data/config.php` to have more messages (lower importance warnings and notices). This can also be done through an environment variable (e.g. `-e FRESHRSS_ENV=development` with Docker).

Check also the logs in `./FreshRSS/data/users/_/log*.txt`

So it does not look like there is any problem :-)

**Comment by triatic** [comment]
Ah, I thought I had seen it report non-error messages too before. I edited a URL to intentionally break an update and it did indeed report in the logs.

Thanks for the response. 👍🏻

**Comment by Alkarex** [comment]
We also use `syslog()` for logging outgoing HTTP requests. In our Docker images, it is possible to see all logs consolidated by running `docker logs -f freshrss`

**Comment by triatic** [comment]
Right. SimplePie actualisation logs to syslog (I remember too this behaviour can be toggled).
