### ISSUE TITLE
Cloudflare: authentication problem

### ISSUE THREAD

**Issue by NuggaN85** [FreshRSS/FreshRSS#2926]
good morning,

I have a problem after installation I arrive to put my username and password admin end of installation connection it me but the login is invalid where does the problem come from ?

**Comment by Alkarex** [comment]
Hello,
This is typically a sign of a cookie problem, often-times due to a badly configured reverse proxy.
What setup do you have (OS, Web server, type of FreshRSS installation, proxy...).

https://github.com/FreshRSS/FreshRSS/tree/master/Docker#alternative-reverse-proxy-using-apache-24

**Comment by NuggaN85** [comment]
> Hello,
> This is typically a sign of a cookie problem, often-times due to a badly configured reverse proxy.
> What setup do you have (OS, Web server, type of FreshRSS installation, proxy...).
> 
> https://github.com/FreshRSS/FreshRSS/tree/master/Docker#alternative-reverse-proxy-using-apache-24

ah ok but I don't have a proxy I'm on chrome os apache server centos7 and no proxy I made 2 times a new installation, everything is fine but I can't connect to my admin account.

**Comment by Alkarex** [comment]
Hum, no add blocker or extension that could interfere?

**Comment by Alkarex** [comment]
No password autocomplete in your browser?
Try maybe with another browser

**Comment by NuggaN85** [comment]
> Hum, no add blocker or extension that could interfere?

no extention

**Comment by NuggaN85** [comment]
> No password autocomplete in your browser?
> Try maybe with another browser

ok I'll try with firefox I'll tell you how it works or not thank you for your quick answer.

**Comment by NuggaN85** [comment]
3 new installation 3 different browser and nothing works :/

**Comment by NuggaN85** [comment]
can we talk private here?

**Comment by Alkarex** [comment]
You can find us on Framateam https://freshrss.org/#help or by e-mail. But in my case, first tomorrow (time zone Copenhagen = UTC+2) :-)

**Comment by Alkarex** [comment]
Please check your Web browser error console, your Apache logs, and your FreshRSS logs (in `./FreshRSS/data/users/_/log*.txt` and `./FreshRSS/data/users/your-username/log*.txt`)

**Comment by Alkarex** [comment]
You can also give a try to our ready-to-use Docker image https://github.com/FreshRSS/FreshRSS/blob/master/Docker/README.md#run-freshrss

**Comment by NuggaN85** [comment]
> ./FreshRSS/data/users/_/log*.txt

./FreshRSS/data/users/_/log*.txt = no files and ./FreshRSS/data/users/your-username/log*.txt = [Sun, 26 Apr 2020 13:41:36 +0000] [warning] --- Password mismatch for user=myname, nonce=, c=

console log = POST mysite.fr/FreshRSS/p/i/?c=auth&a=login 403

**Comment by Alkarex** [comment]
An empty nonce is a sign of cookie problem. It means that either your PHP sessions are not working, or that there is a cookie misconfiguration somewhere between the Web server and the Web browser. Could you please post a screenshot of your browser debugging tools, more specifically the POST request, like below?

![image](https://user-images.githubusercontent.com/1008324/80310351-69733680-87da-11ea-97e1-687d3fa1419f.png)

**Comment by Alkarex** [comment]
P.S. You can also search for `nonce` in our old issues

**Comment by NuggaN85** [comment]
vous êtes français vu le logiciel :) quel es votre logiciel pour moi tester car j'ai eu un souci avec mon disque dur de mon autre pc du coup j'ai plus mes logiciel pour merci d'avance.

ps j'ai plusieur site sur mon serveur et c'est le seule au quel j'ai ce souci la.

**Comment by Alkarex** [comment]
@NuggaN85 La capture d'écran provient de Firefox, mais vous trouverez un équivalent dans Chrome, Edge, et consorts. Ces outils de développement sont typiquement accessibles par <kbd>F12</kbd>

**Comment by NuggaN85** [comment]
j'arrive pas a faire comme vous :/ donner moi votre mail je vais vous envoyer le lien car je le trouve vraiment top ce script j'aimerais vraiment bien qu'il marche

**Comment by NuggaN85** [comment]
si non regarder ici effacer le après avoir vus car pas de pv ici

**Comment by Alkarex** [comment]
Vous avez des injections de scripts Cloudflare.
Du point de vue de FreshRSS, c'est vu comme des attaques malveillantes de type MITM, et FreshRSS les bloque comme il se doit. Le JavaScript de FreshRSS ne peut pas s'exécuter, et le login ne fonctionne pas :
![image](https://user-images.githubusercontent.com/1008324/80315973-65a3dc00-87fb-11ea-8b96-5f72b409c789.png)

Options, par ordre de préférence :
1) Enlever Cloudflare
2) Faire une extension FreshRSS pour éditer les HTTPS CSP
3) Éditer les entêtes HTTP CSP au niveau de Apache
4) Passer en login HTTP au lieu de login Web Form, et se servir de FreshRSS sans JavaScript

Vous pouvez chercher Cloudflare dans nos anciens tickets pour d'autres discussions

**Comment by Alkarex** [comment]
Je ferme car ce n'est pas un problème FreshRSS, mais la discussion peut continuer

**Comment by NuggaN85** [comment]
> Vous avez des injections de scripts Cloudflare.
> Du point de vue de FreshRSS, c'est vu comme des attaques malveillantes de type MITM, et FreshRSS les bloque comme il se doit. Le JavaScript de FreshRSS ne peut pas s'exécuter, et le login ne fonctionne pas :
> ![image](https://user-images.githubusercontent.com/1008324/80315973-65a3dc00-87fb-11ea-8b96-5f72b409c789.png)
> 
> Options, par ordre de préférence :
> 
> 1. Enlever Cloudflare
> 2. Faire une extension FreshRSS pour éditer les HTTPS CSP
> 3. Éditer les entêtes HTTP CSP au niveau de Apache
> 4. Passer en login HTTP au lieu de login Web Form, et se servir de FreshRSS sans JavaScript
> 
> Vous pouvez chercher Cloudflare dans nos anciens tickets pour d'autres discussions

D'accord super merci pour votre support je vais créer une autre section sur le serveur a part et tester je vous tiens au courant si j'ai réussi ou pas :)

**Comment by NuggaN85** [comment]
Bon c'étais bien Cloudflare :) je les installer sur une nouvel session et tout marche bien jusqu’à maintenant ;) et le script est top merci encore :)
