### ISSUE TITLE
Feed from shopblogger.de gets not actualized

### ISSUE THREAD

**Issue by bjo81** [FreshRSS/FreshRSS#2929]
https://www.shopblogger.de/blog/feeds/index.rss2 -> FreshRSS is stuck at 20.04.20

**Comment by spackmat** [comment]
This is resolved by adding an option for disabling the cache for broken feeds, see #1020 for details.

I am writing an e-mail to Björn from shopblogger.de right now and tell him about his broken feed (again, as I did that before in 2018).

**Comment by Alkarex** [comment]
Thanks @spackmat 👍
