### ISSUE TITLE
403 Error When Adding RSS Feed

### ISSUE THREAD

**Issue by dwayneem** [FreshRSS/FreshRSS#2930]
For some RSS Feeds I am receiving the following error when I attempt to add them:

`The newsfeed could not be added. Check FreshRSS logs for details.`

The FreshRSS log has the following text:

`cURL error 22: The requested URL returned error: 403 [https://relate.zendesk.com/public/assets/sitemaps/rl/feed.xml]`

Here are two example RSS feeds that exhibit this problem:
https://relate.zendesk.com/public/assets/sitemaps/rl/feed.xml
https://www.zendesk.com/public/assets/sitemaps/en/feed.xml

Both of these feeds load fine in Firefox and Chrome. https://validator.w3.org/feed/ says that both feeds are valid.

**Comment by Alkarex** [comment]
Hello,
Both feeds are working for me.
It looks like a IP blocking if you get a 403.

Where do you host your FreshRSS? If you have the possibility, try from a FreshRSS

Try from your server:

```sh
curl -v 'https://relate.zendesk.com/public/assets/sitemaps/rl/feed.xml'
```

When this happens, you can either move your FreshRSS to a less problematic server (e.g. at home), or make a little proxy hosted elsewhere for the problematic feeds - see example https://github.com/FreshRSS/FreshRSS/issues/2910#issuecomment-616121948

IP blocking / banning typically occurs when the machine (or its network) has made too many requests to the server hosting the RSS.

**Comment by Alkarex** [comment]
P.S. It could also be a temporary error, and it is always a good idea to try again a bit later

**Comment by dwayneem** [comment]
[output.txt](https://github.com/FreshRSS/FreshRSS/files/4546971/output.txt)

output from `curl -v 'https://relate.zendesk.com/public/assets/sitemaps/rl/feed.xml'`

**Comment by Alkarex** [comment]
It looks like it is yet again another Cloudflare problem, breaking the Web. The site seems to use this service, at least for some originating IPs apparently, and it breaks RSS.
On what type of server do your host FreshRSS?
