### ISSUE TITLE
Access to PostgreSQL through Docker

### ISSUE THREAD

**Issue by toketin** [FreshRSS/FreshRSS#2931]
Hi, I've setup Freshrss following the [docker-compose.yml](https://github.com/FreshRSS/FreshRSS/blob/master/Docker/docker-compose.yml) example, the problem is that I can't finalize the setup, since I'm stuck on database configuration ([screen](https://imgur.com/k6vVgZ7)). 

I'm getting this error: 
` Access to database is denied for freshrss: SQLSTATE[08006] [7] could not connect to server: Connection refused Is the server running on host "localhost" (127.0.0.1) and accepting TCP/IP connections on port 5432? could not connect to server: Cannot assign requested address Is the server running on host "localhost" (::1) and accepting TCP/IP connections on port 5432?`

Thanks, 
Marco

**Comment by Alkarex** [comment]
Hello,
From Docker, you can typically not use `localhost`. Instead, you must give the name of your PostgreSQL instance in Docker, typically `postgres`, or in the case of this docker-compose, `docker_freshrss_postgresql_1`

https://github.com/FreshRSS/FreshRSS/tree/master/Docker

P.S.: You can advantageously give a better name to the instance in docker-compose with `container_name`, e.g.:

```yaml
services:
  freshrss_postgresql:
    image: postgres
    container_name: freshrss_postgres
```

**Comment by Alkarex** [comment]
To see the name of your running Docker instance, run: `docker ps`

**Comment by Alkarex** [comment]
@toketin Did that help?

**Comment by toketin** [comment]
Yes thanks @Alkarex you can close!

**Comment by Alkarex** [comment]
Hum, keeping open to add a little note in the documentation. Help welcome ;-)
