### ISSUE TITLE
[greader-api] mixed string and number

### ISSUE THREAD

**Issue by Stunkymonkey** [FreshRSS/FreshRSS#2934]
when making a get request to `/reader/api/0/unread-count` the following is returned:
```
...
    {
      "id": "feed/6",
      "count": 0,
      "newestItemTimestampUsec": 1588269040490890
    },
...
```
when looking at other documentations about google reader api: The `newestItemTimestampUsec` should be a string and not a number.
sources:
- https://feedhq.readthedocs.io/en/latest/api/reference.html#unread-count
- https://web.archive.org/web/20120608040458/http://undoc.in/unread-count.html

**Comment by Alkarex** [comment]
Thanks @Stunkymonkey , you are correct. Could you please try this fix? https://github.com/FreshRSS/FreshRSS/pull/2935

**Comment by Stunkymonkey** [comment]
thanks @Alkarex for the super fast reply/fix. Works perfectly.

Super happy that I switched to FreshRss. Awesome work.
