### ISSUE TITLE
Filter-actions: mark old entries as read

### ISSUE THREAD

**Issue by jdckr** [FreshRSS/FreshRSS#2941]
Hi,
for news feeds I am subscribing to I want entries older than two days to be marked as read.
I tried to use `!date:P2D` in filter actions but this does not work (while it works fine when using it in the search field).
Are the filter-actions applied to already downloaded entries at all? Or does the filter only fire while downloading?
Further more with the filter configured, all new entries are marked as read.

**Comment by Alkarex** [comment]
Hello,
Currently, the filter actions are only applied to the new articles.
More powerful filters and actions are planned to allow e.g. what you ask. While waiting, it is possible to tune archiving options to remove old articles of that feed, or make an extension that can run the query each time this feed is refreshed, or save your search as a *user filter* to allow you to quickly mark as read matching articles.

**Comment by jdckr** [comment]
Thanks for the hint. Was ever wondering how to configure purge policy per feed.
When is purging triggered? I have configured it to 2 days some hours ago, but still see older articles.

**Comment by Alkarex** [comment]
Purge can be either triggered manually in the archiving options of FreshRSS, or randomly triggered after a feed is updated. You also need to specify whether you want to delete unread articles or not. And FreshRSS will at least keep the same number of articles than those that are still in the source RSS feed.

**Comment by jdckr** [comment]
I have configured `Maximum age of articles to keep` to 2 days, but still have articles from 4th of May. When does this random trigger happen?

**Comment by Frenzie** [comment]
Presumably they're still in the original feed?

**Comment by jdckr** [comment]
I just manually purged and they are gone. So looks like they are not.

**Comment by Alkarex** [comment]
The automatic purging happens randomly, in average every 30 times the feed is refreshed
https://github.com/FreshRSS/FreshRSS/blob/be10486f5e45148c78ab0c0a57a4056d5fc2889a/app/Controllers/feedController.php#L412-L420
What you want would best be done with an additional option, or an extension while waiting for it.

**Comment by jdckr** [comment]
Looks like I have no luck getting `1` (-:

Is it enough to call `$feed->cleanOldEntries()` inside the extension? The comment in `Feed.php` tells to call `updateCachedValue()` as well. How can I access that function in `feed_before_actualize` hook of my extension?
As an alternative solution: How can I mark items as read? I started to get the entries with `$feed->entries` but the array is empty. Do I have to call one of the `load()` functions? How would I after that mark an entry as read?

**Comment by Alkarex** [comment]
In an extension, I would call `$entryDAO->markReadEntries(...)` with the appropriate filter.
The filter can be constructed with something like `$filter = new FreshRSS_BooleanSearch('...')`

**Comment by jdckr** [comment]
This works 👍 

Doesn't it make sense to use the same approach within `feedController.php` instead of 
calling `$entry->applyFilterActions();` for each entry inside the loop? This would cover my use case and should still work the same way as before if I didn't miss something.

**Comment by Alkarex** [comment]
It would work indeed, but would be much more computational expensive (whole database instead of just the new articles), and it is not sure that users want those filters applied on existing articles. I will try to add more powerful automatic filtering / labelling features soonish.

**Comment by Alkarex** [comment]
Implemented in https://github.com/FreshRSS/FreshRSS/pull/3303
Tests welcome
