### ISSUE TITLE
suggestion auto publication

### ISSUE THREAD

**Issue by NuggaN85** [FreshRSS/FreshRSS#2949]
Hello,

voila comme je les dis sur un autre poste avec le souci de cookies que j'ai eu tout marche nickel le script est juste top rien a dire il manque juste une chose qui pourrais être magnifique l'auto publication sur les plateforme comme twitter Facebook webhooks pour discord etc pouvoir relier les compte sociaux pour que a chaque nouveau flux sa auto publie sur les compte relier et la votre script serra magnifiquement au top du top :)

**Comment by Alkarex** [comment]
Il n'y a pas de fonction toute automatisée, néanmoins :
* Il y a un menu de partage vers différents services ;
* FreshRSS fait aussi des sorties RSS, qui peuvent être utilisées pour republier vers d'autres systèmes (IFTTT...)
* Il est possible de faire des extensions FreshRSS pour ajouter ce genre d'automatisation

**Comment by aledeg** [comment]
@NuggaN85 Est-ce que cela répond au besoin exprimé ?
