### ISSUE TITLE
Problème avec le cron

### ISSUE THREAD

**Issue by NuggaN85** [FreshRSS/FreshRSS#2951]
Bonjour,

j'ai suivi le tuto pour l'auto actualisation avec cron avec cette ligne de commande mais marche pas je suis obliger d'actualiser moi même pour avoir les nouveau flux.

`8  *  *  *  * php -q /home/mypatch/public_html/app/actualize_script.php > /tmp/FreshRSS.log >/dev/null 2>&1`

PS: a quoi serre c'est 3 ligne la ?  

```
 'allow_robots' => false,
  'allow_referrer' => false,
  'limits' =>
```

**Comment by Alkarex** [comment]
Bonjour,
Votre ligne ne semble pas valide.

Essayez quelque chose du genre :

```
8 * * * * php /home/mypatch/public_html/app/actualize_script.php > /tmp/FreshRSS.log 2>&1
```

Et vérifiez la documentation cron pour votre platforme. Quel OS?

Alternativement, notre image Docker officielle a un cron intégré.

**Comment by Alkarex** [comment]
Voir https://github.com/FreshRSS/FreshRSS/blob/master/config.default.php pour des commentaires sur les différentes options internes. Mais utilisez plutôt les options exposées par l'interface Web.

**Comment by NuggaN85** [comment]
> Bonjour,
> Votre ligne ne semble pas valide.
> 
> Essayez quelque chose du genre :
> 
> ```
> 8 * * * * php /home/mypatch/public_html/app/actualize_script.php > /tmp/FreshRSS.log 2>&1
> ```
> 
> Et vérifiez la documentation cron pour votre platforme. Quel OS?
> 
> Alternativement, notre image Docker officielle a un cron intégré.

je suis sur centos7 je vais tester votre ligne voir si sa marche

et pour ceci pouvez vous me dire a quoi sa serre

  'allow_robots' => false,
  'allow_referrer' => false,

robot je suppose que sais les bot de crawler mais referrer je vois pas

**Comment by Alkarex** [comment]
Voyez https://github.com/FreshRSS/FreshRSS/blob/master/config.default.php pour les explications. Dans l'ensemble, sauf besoin particulier, vous n'avez pas à vous soucier de ces options

**Comment by NuggaN85** [comment]
d'accord merci :)

**Comment by NuggaN85** [comment]
salut,

je reviens pour le cron sa ne marche pas non plus avec votre ligne de commande ce matin j'ai actualiser manuellement et j'avais plus de 30 flux a actualiser donc le cron marche pas

**Comment by aledeg** [comment]
Est-ce que les droits utilisés pour lancer le cron permettent de lancer le script ?
Lancer la commande suivante permettra peut-être d'identifier le problème.
```
env -i php /home/mypatch/public_html/app/actualize_script.php
```

**Comment by NuggaN85** [comment]
> Est-ce que les droits utilisés pour lancer le cron permettent de lancer le script ?
> Lancer la commande suivante permettra peut-être d'identifier le problème.
> 
> ```
> env -i php /home/mypatch/public_html/app/actualize_script.php
> ```

d'accord je vais test je vous tien au courant merci et oui les droits sont mis car j'ai plusieur tache cron et j'ai aucun souci jusque la

**Comment by NuggaN85** [comment]
bon sa marche pas non plus je comprend pas c'est le seule cron qui marche pas sur mon serveur :/

**Comment by Alkarex** [comment]
Veuillez vérifier le contenu de `/tmp/FreshRSS.log` après le passage du cron. Vérifiez aussi les logs dans `./FreshRSS/data/users/*/log*.txt`, et votre syslog

**Comment by NuggaN85** [comment]
Bonjour,

dans data user myuser le log est vide et dans tmp aucun fichier :/ part contre dans mes log j'ai des erreur log avec le feed.php

**Comment by Alkarex** [comment]
S'il n'y a aucun fichier dans `/tmp/FreshRSS.log` , c'est que votre cron n'a pas été lancé du tout.
Le plus probable est que la tâche n'as pas été bien déclarée
https://doc.fedora-fr.org/wiki/CRON_:_Configuration_de_t%C3%A2ches_automatis%C3%A9es
Si vous avez des logs d'erreurs ailleurs, montrez-les.

Considérez utiliser notre image Docker officielle où tout cela est bien configuré de base.

**Comment by NuggaN85** [comment]
pour le moment j'ai plus rien mais je crois que le script a bug tester voir ici https://freshrss.weax.net/ et actualiser manuellement sa me fait sa depuis 2 jours et rien de plus a été changer de mon coté a part le cron qui bug du coup je les retirer

**Comment by math-GH** [comment]
Is this issue still actual? Could someone please give an English translated summary?

**Comment by Frenzie** [comment]
Doesn't look resolved. Also it doesn't look like the script was tried outside of cron at a glance or am I wrong?
