### ISSUE TITLE
Android clients broken?

### ISSUE THREAD

**Issue by alfureu** [FreshRSS/FreshRSS#2959]
I have an issue of logging in to the 1.16.0 version of FreshRSS with _any_ client from Android. 

I tried Readably (force crashes after logging in and trying to sync), FeedMe (reports error: `Auth Failed - Host does not need to include 'fever'`), and Readrops (no fever API support).

I use the respective links to the API: `http://example.com/api/fever.php` and `http://example.com/api/greader.php`, and they both report to be working (see screenshots below):

![image](https://user-images.githubusercontent.com/10846169/81401302-54c66500-912f-11ea-938b-03a18066af0b.png)

![image](https://user-images.githubusercontent.com/10846169/81401218-26488a00-912f-11ea-90b1-9c7ec1a523a2.png)

Also the "native" FreshRSS app from F-Droid cannot connect.

Could anybody provide any help? I am missing out on a lot of reading...

**Comment by Alkarex** [comment]
Please try from your Web browser to browse to https://freshrss.example.net/api/ to check the automatic tests

**Comment by Alkarex** [comment]
Make sure that you have activated the API and given an API password your user in FreshRSS.
Please tell also what platform you use, how you deployed FreshRSS.

**Comment by alfureu** [comment]
OK, run the test and the results are as follows:

```
FreshRSS API endpoints
Google Reader compatible API
Your API address:
https://192.168.0.30:8889/api/greader.php
Google Reader API configuration test:
⚠️ WARN: Probable invalid base URL in ./data/config.php
Fever compatible API
Your API address:
https://192.168.0.30:8889/api/fever.php
Fever API configuration test:
⚠️ WARN: Probable invalid base URL in ./data/config.php
```

What does this mean?

I am running this from the linuxserver.io docker on a NAS. The API and the passwords are set.

**Comment by Alkarex** [comment]
It means that you have probably changed address / URL after your installed FreshRSS, and consequently the `base_url` parameter in your `./data/config.php` is wrong.
It is probably not the (sole) problem though, but try to fix that first to make sure that there is no other problem that the automatic test can find

**Comment by Alkarex** [comment]
FeedMe is using the `/api/greader.php` endpoint. See https://github.com/FreshRSS/FreshRSS/pull/2942#issuecomment-622970265

**Comment by alfureu** [comment]
Hm, I have in the `config.php` the base_url set to `https://192.168.0.30:8889/`, I tried to change it to `http` instead of `https` (container restarted), but to no avail. I did not change anything for months, I think it changed to the upgrade to v1.16

**Comment by Alkarex** [comment]
Is the test passing after your change in `config.php` ?

**Comment by Alkarex** [comment]
If you can, please try the first two `curl` queries from https://freshrss.github.io/FreshRSS/en/users/06_Mobile_access.html#google-reader-compatible-api

**Comment by alfureu** [comment]
> If you can, please try the first two `curl` queries from https://freshrss.github.io/FreshRSS/en/users/06_Mobile_access.html#google-reader-compatible-api

I tested the 2 commands. The 1st provides the `SID`, `LSID`, and `Auth` values as expected, the 2nd command does not do anything. No output, no error, nothing. It just puts me back to the command line.

**Comment by Alkarex** [comment]
Please try the second command with `curl -v` instead of `curl -s` 
Please have a look at your logs in `.FreshRSS/data/users/*/log*.txt` and in particular `./FreshRSS/data/users/_/log_api.txt`

**Comment by alfureu** [comment]
I will have more time testing tomorrow, however, I just changed to `curl -v` as suggested, and this is the output:

```
* Port number ended with 'G'
* Closing connection -1
curl: (3) Port number ended with 'G'
* Protocol " http" not supported or disabled in libcurl
* Closing connection -1
curl: (1) Protocol " http" not supported or disabled in libcurl
```

**Comment by Alkarex** [comment]
Hum, it looks like there is a typo in the command

**Comment by alfureu** [comment]
I cannot see it:

```
curl 'http://192.168.0.30:8889/api/greader.php/accounts/ClientLogin?Email=user&Passwd=Password'
```
results in
> SID=user/SIDCODE
> LSID=null
> Auth=user/SIDCODE

```
curl -v "Authorization:GoogleLogin auth=user/SIDCODE" \ 'http:/
/192.168.0.30:8889/api/greader.php/reader/api/0/subscription/list?output=json'
```
results in
>* Port number ended with 'G'
> * Closing connection -1
> curl: (3) Port number ended with 'G'
> * Protocol " http" not supported or disabled in libcurl
> * Closing connection -1
> curl: (1) Protocol " http" not supported or disabled in libcurl

**Comment by Alkarex** [comment]
Try again without new lines:

```sh
curl -v "Authorization:GoogleLogin auth=user/SIDCODE" 'http://192.168.0.30:8889/api/greader.php/reader/api/0/subscription/list?output=json'
```

**Comment by alfureu** [comment]
> Try again without new lines:
> 
> ```shell
> curl -v "Authorization:GoogleLogin auth=user/SIDCODE" 'http://192.168.0.30:8889/api/greader.php/reader/api/0/subscription/list?output=json'
> ```

Run the command with the following output:

```
$ curl -v "Authorization:GoogleLogin auth=user/SIDCODE" 'http://1
92.168.0.30:8889/api/greader.php/reader/api/0/subscription/list?output=json'
* Port number ended with 'G'
* Closing connection -1
curl: (3) Port number ended with 'G'
*   Trying 192.168.0.30...
* TCP_NODELAY set
* Connected to 192.168.0.30 (192.168.0.30) port 8889 (#0)
> GET /api/greader.php/reader/api/0/subscription/list?output=json HTTP/1.1
> Host: 192.168.0.30:8889
> User-Agent: curl/7.58.0
> Accept: */*
>
< HTTP/1.1 401 Unauthorized
< Server: nginx/1.16.1
< Date: Mon, 11 May 2020 06:37:18 GMT
< Content-Type: text/plain; charset=UTF-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-Powered-By: PHP/7.3.17
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate
< Pragma: no-cache
< Google-Bad-Token: true
<
* Connection #0 to host 192.168.0.30 left intact
Unauthorized!
```

Does this appear as something got changed with the nginx in the linuxserver.io docker image?

**Comment by Alkarex** [comment]
You need to replace user/SIDCODE with the values your got from the first call. Did you so so?

**Comment by Alkarex** [comment]
After this call, please look at `./FreshRSS/data/users/_/log_api.txt`

**Comment by alfureu** [comment]
Hi @Alkarex, of course I run it with the proper user and SIDCODE, I just did not want to share it publicly. Regarding the `log_api.txt` file, there isn't any produced by the linuxserver/freshrss docker image. Does this mean anything? Again, I did set the API password and I did enable the API access.

**Comment by Alkarex** [comment]
If you do not have anything in `./FreshRSS/data/users/_/log_api.txt` , there is probably another problem. 

Try to uncomment those two lines, which will turn logging for all requests (and not only when there is an error).
https://github.com/FreshRSS/FreshRSS/blob/0442243037fc7fb80228790a871328629a1aa882/p/api/greader.php#L919-L920

And then try again, including access via your browser to `https://freshrss.example.net/api/`

You should be able to see some new data in `./FreshRSS/data/users/_/log_api.txt` for each of your requests.

I am not familiar with the `linuxserver/freshrss` Docker image, but you can try ours as an alternative.

**Comment by alfureu** [comment]
Just installed `freshrss/freshrss`, maybe a suggestion for the online documentation that one needs to open the port 80, and if persistent volume is desired then the folder `/var/www/FreshRSS/data` needs to be opened to host as well. Otherwise the installation is standard. The fever and greader APIs work, however Readably is still crashing (FeedMe and FreshRSS android app works though). Closing this ticket.
