### ISSUE TITLE
There is any way to remove user older than 365 days ?

### ISSUE THREAD

**Issue by Dryusdan** [FreshRSS/FreshRSS#2967]
Hello 

I host a FreshRSS instance and the size of the database is constantly increasing (logic).
But, I suspect some users are registering to test FreshRSS and import some (or many) and there are no remove there accounts. (I have more user registered than access on front web).
So FreshRSS get rss for unused user, consume ressource and use space in DB.

I research a way to remove users who don't connect on front web or who don't get there rss feed after x days.
It is possible ?

Thank :)

**Comment by Alkarex** [comment]
Hello,
FreshRSS has a command line interface, which offers user status and the possibility to delete them.

https://github.com/FreshRSS/FreshRSS/tree/master/cli

Try e.g.

```
./cli/user-info.php -h --header
```

So you could have a cron job to run a little logic regularly.

I was planning to make a JSON output to ease parsing

**Comment by Dryusdan** [comment]
Hooo, I can't see that ! 

Thank :D

So `the date/time of last user action` Accessing the rss of the account without logging in via the interface is considered as an action. ?

**Comment by Alkarex** [comment]
No, I have tried to count only *significant* actions, that are most likely not automatic (but some double-check on this part would be nice). See e.g. https://github.com/FreshRSS/FreshRSS/pull/2936#issuecomment-622933327

**Comment by Alkarex** [comment]
See https://github.com/FreshRSS/FreshRSS/pull/2968 , it should help.

```sh
./cli/user-info.php --json | jq .
```

```json
[
  {
    "is_default": true,
    "user": "alex",
    "last_user_activity": "2020-05-12T17:45:29+02:00",
    "database_size": 422281216,
    "categories": "20",
    "feeds": 196,
    "reads": 128747,
    "unreads": 833,
    "favourites": 274,
    "tags": "18",
    "lang": "fr",
    "mail_login": "alexandre@example.net"
  },
  {
    "is_default": false,
    "user": "alice",
    "last_user_activity": "2020-01-06T20:40:41+01:00",
    "database_size": 221184,
    "categories": "1",
    "feeds": 1,
    "reads": 2,
    "unreads": 9,
    "favourites": 0,
    "tags": "0",
    "lang": "fr",
    "mail_login": ""
  }
]
```

**Comment by Alkarex** [comment]
Example of user selection with `jq`:

```sh
./cli/user-info.php --json 2> /dev/null | jq '.[] | select(.last_user_activity < "2020-04-30") | .user'
"alice"
"thomas"
```

**Comment by Dryusdan** [comment]
Hooo ~I think I'll wait for that MR.
It must be more pratical to parse json than parse with awk ^^ 

Thank !

**Comment by Alkarex** [comment]
I have added a few examples to filter on date https://github.com/FreshRSS/FreshRSS/pull/2968

**Comment by Alkarex** [comment]
Merged in master. Feedback welcome

**Comment by Dryusdan** [comment]
It's work ! 

Thank you ! :D
