### ISSUE TITLE
Partage de flux hors plateforme

### ISSUE THREAD

**Issue by mammichu** [FreshRSS/FreshRSS#2969]
Bonjour,
La fonction partage utilise des plateformes parfois propriétaire qui finalement enferment le contenu. Serait il possible d'envisager le partage d'une sélection d'articles, tout simplement à partir d'un dossier qui disposerait d'un flux public, cela peut être une config pour le dossier favori. De cette manière il est possible d'inclure ce flux partout. Pour ma part c'est pour partager une veille en mode collaboratif et le réimporter ailleurs ; Merci pour votre retour sur cette suggestion.

**Comment by Alkarex** [comment]
Bonjour,
Commencez par mettre un token dans votre profil, et ensuite chaque vue FreshRSS peut être accédée via RSS sans login 

![image](https://user-images.githubusercontent.com/1008324/81852403-41663000-955b-11ea-8688-73243bebe374.png)

Dans le futur, je compte ajouter la possibilité d'avoir multiple tokens, pour plus facilement en révoquer 

Ensuite, vous trouverez le lien du RSS via la petite icône idoine 

![image](https://user-images.githubusercontent.com/1008324/81852329-24316180-955b-11ea-99e3-e066bb275bb8.png)

Il est possible de changer les paramètres pour limiter la longueur du flux RSS (par date et/ou en nombre)

**Comment by Alkarex** [comment]
Dans le futur, je compte aussi ajouter une sortie HTML des mêmes flux

**Comment by mammichu** [comment]
Bonjour
Je ne trouvais pas où paramétrer le token ... merci !!
