### ISSUE TITLE
PHPMailer bump to 6.1.5

### ISSUE THREAD

**Issue by BrookeDot** [FreshRSS/FreshRSS#2971]
Are there any changes made to PHPMailer preventing an update from 6.0.7 to 6.1.5?
https://github.com/PHPMailer/PHPMailer/releases/tag/v6.1.5

**Comment by Alkarex** [comment]
Hello @BrookeDot 
Would you feel like sending a PR with the new version?

**Comment by Frenzie** [comment]
But please don't forget to check first if the minimum supported PHP version changed and if that would have any consequences. :+1:

**Comment by BrookeDot** [comment]
@Frenzie are we still sticking with PHP 5.6+ for now?

**Comment by Alkarex** [comment]
> @Frenzie are we still sticking with PHP 5.6+ for now?

Yes, at least for the upcoming release
