### ISSUE TITLE
android client

### ISSUE THREAD

**Issue by doniomm** [FreshRSS/FreshRSS#2977]
hello 

I have easyrss (android) installed...

as URL I have: http://1XX.XXX.XXX.XXX/freshrss/api/greader.php
Username: XXXX
Password: API password

- Allow API access (required for mobile apps) is true
- API password (e.g., for mobile apps) is set

FreshRSS API endpoints
Google Reader compatible API
Your API address:
    http://1XX.XXX.XXX.XXX/freshrss/api/greader.php
Google Reader API configuration test:
    ✔️ PASS

Fever compatible API
Your API address:
    http://1XX.XXX.XXX.XXX/freshrss/api/fever.php
Fever API configuration test:
    ✔️ PASS 

Version of FreshRSS is 1.16.1-dev. 

but the app told me wrong login/password...
the log.txt is empty...

**Comment by Alkarex** [comment]
Hello,
Try the [latest EasyRSS version](https://f-droid.org/packages/org.freshrss.easyrss/) and/or to manually purge its data in Android settings (or uninstall/install app), as there are some cases of old logins that might interfere.
You are supposed to get some logs in `./FreshRSS/data/users/_/log_api.txt`

**Comment by Alkarex** [comment]
P.S. It looks like you are using a local IP address for your FreshRSS server, which will not work if your mobile client is not on the same network

**Comment by doniomm** [comment]
okay... with the last version it works... 

issue can be closed :-)

THX
