### ISSUE TITLE
import opml from Handy News Reader

### ISSUE THREAD

**Issue by doniomm** [FreshRSS/FreshRSS#2981]
Hello,

how can I import opml feeds from handy news reader (opml format)?

In the section import it will not work :-( is there a log: 

[Thu, 14 May 2020 21:48:57 +0200] [warning] --- Body can contain only outline elements
[Thu, 14 May 2020 21:48:57 +0200] [warning] --- Error during OPML import
[Thu, 14 May 2020 21:49:46 +0200] [warning] --- Body can contain only outline elements
[Thu, 14 May 2020 21:49:46 +0200] [warning] --- Error during OPML import
[Fri, 15 May 2020 05:28:38 +0200] [warning] --- Body can contain only outline elements
[Fri, 15 May 2020 05:28:38 +0200] [warning] --- Error during OPML import
[Fri, 15 May 2020 17:46:54 +0200] [warning] --- Body can contain only outline elements
[Fri, 15 May 2020 17:46:54 +0200] [warning] --- Error during OPML import
[Fri, 15 May 2020 18:07:41 +0200] [error] --- SQL error addCategory: ["23000",1062,"Duplicate entry 'Computer' for key 'name'"]
[Fri, 15 May 2020 22:22:53 +0200] [warning] --- Body can contain only outline elements
[Fri, 15 May 2020 22:22:53 +0200] [warning] --- Error during OPML import

**Comment by Alkarex** [comment]
Hello,
OPML import should work fine, but maybe there is something special with your OPML file.
Could you please share (a part of) your OPML file?

**Comment by doniomm** [comment]
ok i have sent it as txt...
[HandyNewsReader_auto_backup.txt](https://github.com/FreshRSS/FreshRSS/files/4638158/HandyNewsReader_auto_backup.txt)

**Comment by Alkarex** [comment]
Could you please try https://github.com/FreshRSS/FreshRSS/pull/2983 ?

**Comment by doniomm** [comment]
ok, how I do it?

**Comment by doniomm** [comment]
mmmhh i have done a update... but nothing is import, error log is still the same

**Comment by doniomm** [comment]
ok, i have it...
i comment out the lines... and now it works...
 [Sat, 16 May 2020 15:55:24 +0200] [warning] --- Feed has invalid GUIDs: http://v2.schmiededaseisen.de/rss/forum/322292
[Sat, 16 May 2020 15:55:35 +0200] [warning] --- Feed has invalid GUIDs: http://juris.bundesgerichtshof.de/rechtsprechung/bgh/feed.xml
[Sat, 16 May 2020 15:57:49 +0200] [warning] --- Feed has invalid GUIDs: https://www.sportschau.de//sportschauindex100~_type-rss.feed 

with this warnings....

**Comment by Alkarex** [comment]
Yes, some feeds are not fully correct, e.g.
* https://validator.w3.org/feed/check.cgi?url=http%3A%2F
%2Fv2.schmiededaseisen.de%2Frss%2Fforum%2F322292
* https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fjuris.bundesgerichtshof.de%2Frechtsprechung%2Fbgh%2Ffeed.xml

**Comment by Alkarex** [comment]
So, did the import worked for you?

**Comment by doniomm** [comment]
yes @Alkarex thx you very much
