### ISSUE TITLE
how to filter feed

### ISSUE THREAD

**Issue by yanivz** [FreshRSS/FreshRSS#2988]
I've added a feed and it's working fine, now i want the items to be aggregate by filter, so in the end out of 100 items those whos been filter (by me) by the the keyword 'foo' will be displayed only.

**Comment by Alkarex** [comment]
Hello,
You can use the search field to do that. If it is used frequently, the search query can be saved as user query. The resulting view can also be shared by RSS. See the bottom of https://freshrss.github.io/FreshRSS/en/users/03_Main_view.html
I will also soon add an auto-labelling feature to automatically add multiple labels to articles.

**Comment by yanivz** [comment]
Thank you for responding. I will share with you a [screenshot ](https://send.firefox.com/download/921008144ed7600e/#VBJVckOvQXZCD_i0pQeSAw).
Please tell me the steps as i saw in [your link](https://freshrss.github.io/FreshRSS/en/users/03_Main_view.html)
I want to use this intitle:keyword. Where do i put this line in order to filter my feed to this keyword in title for ever.

**Comment by Alkarex** [comment]
If you click on your saved user query, it will show you the articles filtered as you defined.
Another option we have right now is to automatically mark as read articles that are not relevant for you. Maybe this is what you want? You can find this option on a given feed's settings.

**Comment by Alkarex** [comment]
So in your case, the filter to automatically mark as read would be on articles that do not contain your keyword in the title, like `!intitle:keyword`

**Comment by yanivz** [comment]
I want a permanent filter to specific feed (or better category) so it will filter out on the fly showing only things i like, it's not about read/unread but display/remove. i want to share also this feed without many non realvent things in it.

**Comment by math-GH** [comment]
I guess you could solve your wish with the [default user](https://freshrss.github.io/FreshRSS/en/admins/13_Default_user.html) and the generated feed of the user query.

**Comment by Jorenar** [comment]
> I guess you could solve your wish with the [default user](https://freshrss.github.io/FreshRSS/en/admins/13_Default_user.html) and the generated feed of the user query.

How can I generate feed of a query?

**Comment by math-GH** [comment]
Create/Select a query and take the RSS feed.

![grafik](https://user-images.githubusercontent.com/1645099/199222195-9fb98f1e-860d-4cc0-8a78-47337412175b.png)

Does it work for you?

**Comment by Jorenar** [comment]
It's a bit convoluted way of filtering, ~~but I can work with this. Thanks!~~

I really don't feel comfortable with sharing the feeds to everybody.  
Is there any way to keep the query feed private?

**Comment by sotn3m** [comment]
> Create/Select a query and take the RSS feed.
> 
> ![grafik](https://user-images.githubusercontent.com/1645099/199222195-9fb98f1e-860d-4cc0-8a78-47337412175b.png)
> 
> Does it work for you?

I was trying to create a feed for both search criteria and saved search. While both seem to generate proper links (ie. https://freshrss.local/i/?a=rss&amp;search=label%3ACalibre&amp;rid=6633a1924d007&amp;state=3&amp;hours=168), when I open the link in a browser it presents a totally unfiltered list of items... Is there anything I am missing?
Version 1.23.1 via docker.

**Comment by math-GH** [comment]
Please wait for 1.24.0 release. There will be a new feature for user query sharing via RSS feed. Maybe it will help you

**Comment by Alkarex** [comment]
> Please wait for 1.24.0 release.

I would like to actually invite you to try and test our rolling release (edge branch) in which the feature is already available.

See https://freshrss.github.io/FreshRSS/en/users/user_queries.html

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/6052

**Comment by sotn3m** [comment]
`edge` creates proper RSS feed for my use case. Thank you.
