### ISSUE TITLE
small display bug

### ISSUE THREAD

**Issue by prolibre** [FreshRSS/FreshRSS#2992]
FreshRSS Version 1.16.1-dev
Firefox and firefox dev (latest version in windows)

![bug](https://user-images.githubusercontent.com/17174902/82540361-3b6de180-9b4f-11ea-973f-72ffeffcd2a1.png)

since a few updates I have this little bug (only when all items are marked as seen).

Have a nice day.

**Comment by Alkarex** [comment]
Thanks for testing the master branch 👍 
Please try this fix https://github.com/FreshRSS/FreshRSS/pull/2990

**Comment by prolibre** [comment]
Sorry but I don't know how to test without breaking everything :-) I don't know much about git.
How can I try your fix and then go back ? (what git commands ?)

**Comment by Frenzie** [comment]
@prolibre 

What I'd personally do is something along these lines:

```sh
git fetch pull/2990/head
git checkout FETCH_HEAD
# see if it works
# now go back to master
git checkout master
```

But there are many ways to Rome. Some people prefer to work with patches and git apply for example.

**Comment by Alkarex** [comment]
And now I have just merged in the master branch, so please give it a try from there :-)

**Comment by prolibre** [comment]
Thank you, it's working great.
And thank you @Frenzie I now have the method for next time!
Have a nice day.
