### ISSUE TITLE
Fatal Error In Installation On Windows Server

### ISSUE THREAD

**Issue by Dustin-Jiang** [FreshRSS/FreshRSS#2998]
I had tried to install this service on my Windows Server but it falied. 
There was a fatal error after I set the default user name and password. 
The error message was: 
```

Fatal error: Uncaught Error: Call to a member function fetchAll() on bool in C:\inetpub\wwwroot\FreshRSS\app\Models\FeedDAO.php:300 Stack trace: #0 C:\inetpub\wwwroot\FreshRSS\app\Controllers\importExportController.php(250): FreshRSS_FeedDAO->listFeeds() #1 C:\inetpub\wwwroot\FreshRSS\app\Controllers\importExportController.php(237): FreshRSS_importExport_Controller->addOpmlElements(Array) #2 C:\inetpub\wwwroot\FreshRSS\app\Controllers\importExportController.php(102): FreshRSS_importExport_Controller->importOpml('<?xml version="...') #3 C:\inetpub\wwwroot\FreshRSS\app\Controllers\userController.php(251): FreshRSS_importExport_Controller->importFile('C:\\inetpub\\wwwr...', 'C:\\inetpub\\wwwr...', 'Dustin') #4 C:\inetpub\wwwroot\FreshRSS\app\install.php(225): FreshRSS_user_Controller::createUser('This is User Name:)', '', 'This is Password:)', Array) #5 C:\inetpub\wwwroot\FreshRSS\app\install.php(671): saveStep3() #6 C:\inetpub\wwwroot\FreshRSS\p\i\index.php(27): require('C:\\inetpub\\wwwr...') #7 {main} thrown in C:\inetpub\wwwroot\FreshRSS\app\Models\FeedDAO.php on line 300
```
Server Info: 
- Windows Server 2019 1809
- IIS 10
- PHP 7.4.2 on CLI
- MySQL 8.0.19

**Comment by Alkarex** [comment]
Hello,
Which version of FreshRSS are you trying?
Could you try whether you get the same error using SQLite as a database?
Do you install through command line or Web interface?

**Comment by Dustin-Jiang** [comment]
Thank you. 
I am using the latest release of FreshRSS, and I tried to install it via web interface. 
I'll try SQLite later probably because my website uses MySQL :(

**Comment by Alkarex** [comment]
There is no need to install anything to try SQLite

**Comment by Dustin-Jiang** [comment]
All Right. 
But I have tried reinstalling FreshRSS and I didn't know why my original configurations were still there though I've replaced files with new ones…… And I couldn't choose any other databases except MySQL……
![图片](https://user-images.githubusercontent.com/56217843/82732859-9ca9d680-9d42-11ea-8418-d7be275dd845.png)
*Please ignore Chinese Interface……*
Could you please tell me how I can remove the old configurations and reinstall it completely?

**Comment by Frenzie** [comment]
Is SQLite shown in your phpinfo? Otherwise you simply don't have the extension enabled. (In Windows probably something like php_sqlite.dll but don't quote me on that.)

**Comment by Dustin-Jiang** [comment]
Thank You Everyone!
I've installed sucessfully by changing to SQLite. 
> Should I close this issue?

**Comment by Alkarex** [comment]
Just for the record, the MySQL record visible in the screenshot is due to a change of default settings in MySQL 8.0 https://stackoverflow.com/questions/49083573/php-7-2-2-mysql-8-0-pdo-gives-authentication-method-unknown-to-the-client-ca

@Dustin-Jiang Ideally, before closing, we should test whether the installation works under IIS + MySQL
