### ISSUE TITLE
Partage d'article par courriel (gestion avancée)

### ISSUE THREAD

**Issue by aledeg** [FreshRSS/FreshRSS#300]
Le partage par courriel actuel fonctionne correctement mais est un peu limité.
Il pourrait être automatique en configurant un serveur de courriel.
Il pourrait envoyer le contenu de l'article en plus de son lien.
Il pourrait contenir un en-tête et une signature paramétrables pour l'envoi automatique.
Et si les options sus mentionnées ne fonctionnent pas, il reste la solution existante.

**Comment by marienfressinaud** [comment]
Juste pour prévenir que c'est désormais implémenté de manière basique dans une extension :) https://github.com/FreshRSS/Extensions/tree/master/xExtension-ShareByEmail
