### ISSUE TITLE
OpenID Connect AuthN

### ISSUE THREAD

**Issue by schuerg** [FreshRSS/FreshRSS#3001]
Since FreshRSS supports different authentication methods, I wonder if OpenID Connect (OIDC) authentication is planned for future versions? To authenticate against a OIDC providers like Keycloak, ORY Hydra, Okta, Auth0 etc.

**Comment by Alkarex** [comment]
Hello,
This is not on the roadmap, but would be a nice contribution.
See e.g. https://github.com/FreshRSS/FreshRSS/issues/2428

**Comment by prohand** [comment]
Hello,

Do you have a date to communicate for the implementation of this feature please?

Thanks

**Comment by Alkarex** [comment]
Hello,
This is not on my own roadmap at the moment, so the date would be whenever someone feels like implementing it.
You are welcome to send a PR if you can.

**Comment by prohand** [comment]
Thank you for your reply.
Unfortunately I'm just a simple user and not a developer :(

**Comment by Alkarex** [comment]
Done in https://github.com/FreshRSS/FreshRSS/pull/5351
