### ISSUE TITLE
Convert NZB RSS to audio podcast feed

### ISSUE THREAD

**Issue by TD540** [FreshRSS/FreshRSS#3002]
Looking for a solution, if it even exists, to convert an NZB RSS feed to a feed I could subscribe to in my podcast app. Currently running FreshRSS and NZBGet in @linuxserver's Docker containers.

Could FreshRSS somehow be extended so it can tell NZBGet to download NZB enclosures to a shared volume and publish a feed where `<enclosure url="https_link_to_nzb_download" type="application/x-nzb"/>` from the original feed gets converted to to `<enclosure url="http://ip_of_freshrss/nzb_download.mp3" type="audio/mpeg"/>`?

**Comment by Frenzie** [comment]
The first thing to try is to write the maintainers of the website to see if they'll change the `type` attribute to something more meaningful. They just might. ;-)

If that doesn't work out, you can probably write an extension tapping into SimplePie or some such; I think that should probably be possible on `entry_before_insert`. You can use functions like `$enclosure->get_link()`, `$enclosure->get_type()` and `$enclosure->get_link()` (or whatever the relevant variable name is there). So then you'd act on if type === 'x-nzb' etc.
