### ISSUE TITLE
Docker not refreshing?

### ISSUE THREAD

**Issue by alfureu** [FreshRSS/FreshRSS#3007]
Do I need to add a special cron job for refreshing FreshRSS in docker (container `freshrss/freshrss`). It seems the feeds are not refreshing, there is no cron job defined in the crontab file. I thought once we set under Archiving the setting "Do not automatically refresh more often than 1h" it will refresh every 1h... The documentation pages for docker are not clear about this

**Comment by Alkarex** [comment]
Please show your docker run command, and make sure to check:

* https://github.com/FreshRSS/FreshRSS/blob/master/Docker/README.md#run-freshrss
* https://github.com/FreshRSS/FreshRSS/blob/master/Docker/README.md#cron-job-to-automatically-refresh-feeds

**Comment by alfureu** [comment]
Thanks for these, I was unaware of these docker Readme files. I tried the default documentation and I could not find anything. I was missing the CRON_MIN environment. Maybe an idea, to have it set to the default as listed in the links above?

**Comment by Alkarex** [comment]
I have not yet found how to tell Docker Hub to use the proper `README.md` file during an auto-build. If you happen to find out, please let me know :-)
I tried that https://github.com/FreshRSS/FreshRSS/blob/master/Docker/hooks/post_checkout but without success

**Comment by alfureu** [comment]
I was looking more on this site: https://freshrss.github.io/FreshRSS/en/users/03_Main_view.html#refreshing-feeds

This is the first site when one types into Google "FreshRSS documentation"

**Comment by Alkarex** [comment]
Would you feel like making a quick edit to point to our Docker doc?

From:
* https://github.com/FreshRSS/FreshRSS/blob/master/docs/en/users/03_Main_view.md
* https://github.com/FreshRSS/FreshRSS/blob/master/docs/fr/users/03_Main_view.md

To:
* https://github.com/FreshRSS/FreshRSS/blob/master/Docker/README.md

**Comment by alfureu** [comment]
Maybe editing https://github.com/FreshRSS/FreshRSS/blob/master/docs/en/admins/03_Installation.md for adding a subheading for docker deployment with the link would be helpful?

**Comment by Alkarex** [comment]
Yes @DOFfactory , exactly :-)

**Comment by alfureu** [comment]
Done: https://github.com/FreshRSS/FreshRSS/commit/9e29a982b636715752829e238bcf968dd70ebfa3

**Comment by Alkarex** [comment]
@DOFfactory Could you please make a pull request with your additions?
