### ISSUE TITLE
Support Gemini protocol for fetching feeds

### ISSUE THREAD

**Issue by tastytea** [FreshRSS/FreshRSS#3011]
Hi, it would be great if you could support the [Gemini](https://gemini.circumlunar.space/) [protocol](https://gemini.circumlunar.space/docs/spec-spec.txt). It's pretty easy, to get a file you just have to send the URI over a TLS connection, like this:

``` shell
echo -en 'gemini://example.com/atom.xml\r\n' | openssl s_client -connect example.com:1965 -quiet
```

And you get back:

``` xml
20      text/xml
<?xml version='1.0' encoding='UTF-8'?>
[…]
```

The response header has this format: `<STATUS><SPACE><META><CR><LF>`. `<SPACE>` can be more than 1 space.

The important response codes are:

`2*`:  SUCCESS (`<META>` is the mime type)
`3*`: REDIRECT (`<META>` is the new URI)
`4*`: TEMPORARY FAILURE
`5*`: PERMANENT FAILURE

**Comment by Alkarex** [comment]
Hello,
I have never heard of it, but it sounds more like a job for a bridge than a feature to put in the core of FreshRSS. Either a manual bridge (see below), one integrated into a set of bridges such as https://github.com/RSS-Bridge/rss-bridge , or as a FreshRSS extension.

Here is an example of minimal proxy using curl for HTTP, where curl should be replaced by a library that understand your protocol.

```php
<?php
header('Content-Type: application/rss+xml; charset=utf-8');
$ch = curl_init('https://example.com/rss.xml');
curl_exec($ch);
curl_close($ch);
```
