### ISSUE TITLE
Re: The "Stick the article to the top when opened" option

### ISSUE THREAD

**Issue by cwldev** [FreshRSS/FreshRSS#3012]
Thanks for the great FreshRSS! 

I do have a challenge, perhaps not so much as a bug, but I know I would like this to be better. The option "Stick the article to the top when opened" essentially controls all this.

So, when "Stick the article to the top when opened" is enabled, it has the effect of keeping articles at a specific eye-level, which is great. Easier for reading. 

Now, there are some issues with this, first notice how the top bar (including the freshrss logo) scroll out of view. I wish the article only scrolled and not the entire interface. The challenge for me here though is its bouncing all over trying to keep things centered as I open and close articles. This is a little nuanced, but I have to re-center what I'm looking at after opening and article (the O button for me) and then going to the next article (the N button for me). 

But, now with your new inclusion of ALT + Modifier, I can mark previous articles as read. Really useful because then I could maybe control the scrolling and reading better. So, I go and turn off "Stick the article to the top when opened" and start scrolling through the list with my modifier (it's n for me). While scrolling, the highlighted article goes past the interface and never scrolls the articles up while I'm progressing.

So, while the list never moves, I have to manually do something like press page down or try and figure out where I am. Naturally, I'd like the article list to either stick somewhere (maybe stay at the bottom and continue scrolling)... or something like that. 

Indeed, also making that "Stick the article to the top when opened" a little clear or splitting it out into some other options. I don't expect this scrolling stuff is easy to work with or implement.

But mostly, I hope some of this makes sense. FreshRSS is awesome of course.. Thank you again.

**Comment by cwldev** [comment]
Also, the left sidebar. Is there a way to hide that? Maybe a hotkey that could be used to hide it (I think that was U in the old Google Reader). Would would make reading longer titles easier.

**Comment by math-GH** [comment]
Is this issue still actual for you @cwldev ?
The links to your screen prints are not valid anymore.

**Comment by cwldev** [comment]
Hi @math-GH - I'm no longer using FreshRSS.. I'll remove these links and see if I can find the screens so I can re-post the images.

**Comment by Alkarex** [comment]
Maybe related to https://github.com/FreshRSS/FreshRSS/issues/4069 and the fix https://github.com/FreshRSS/FreshRSS/pull/4071
