### ISSUE TITLE
Download link on FreshRSS website

### ISSUE THREAD

**Issue by triatic** [FreshRSS/FreshRSS#3016]
Curious to know, why does the download link on freshrss.org point to the master branch and not the latest stable release? Doesn't this defeat the point of having stable releases?

**Comment by Alkarex** [comment]
I do not know whether there is a direct link to download the latest release as ZIP.
There is https://github.com/FreshRSS/FreshRSS/releases/latest but it is not a direct download link.
If you find out, you are welcome to send a PR to https://github.com/FreshRSS/freshrss.org
But we should probably link to multiple options. There are indeed multiple installation methods (git, Docker, YunoHost...) and a few branches for each.
The master branch is a kind of rolling release, and it is also important that some people are using it.
By the way, 1.16.1 is just out https://github.com/FreshRSS/FreshRSS/releases

**Comment by triatic** [comment]
There's already a link to GitHub which will give more download options.

As for the blue download button pictured below. you believe it should point to the latest stable release? 

![image](https://user-images.githubusercontent.com/42704418/83329977-47ab1a80-a284-11ea-9102-1829a4c666bf.png)

**Comment by Alkarex** [comment]
We would rather avoid having to change this button at each release. So ideally it should contain a link like https://github.com/FreshRSS/FreshRSS/releases/latest/....zip but I am not aware of such a possibility in GitHub.

**Comment by triatic** [comment]
I can understand that. I'll have a look around to see if there are any solutions for this.

**Comment by triatic** [comment]
Apparently GitHub can do this as long as the asset name is kept the same across releases.

Watch how the URL changes after clicking this link: https://github.com/FreshRSS/FreshRSS/releases/latest/download/FreshRSS.zip

You could change to this asset naming convention?

**Comment by Frenzie** [comment]
The assets are named by GitHub based on the tag. The only way to change that would be to needlessly duplicate the asset.

We could consider adding a little script in there that requests the latest tag name and updates the download link. Without JS it could just link to https://github.com/FreshRSS/FreshRSS/releases/latest

**Comment by triatic** [comment]
https://github.com/FreshRSS/FreshRSS/releases/latest is good too, as long as you don't mind linking to a page as opposed to a file.

Also "_needlessly_ duplicate the asset" is debatable, as it would at least enable the static stable download URL to function, so the duplicate file would be serving a purpose at least.

**Comment by triatic** [comment]
FreshRSS/freshrss.org#46 created. Added bonus being that people can choose to download a zip or tarball as is their preference.

**Comment by 1001Musik** [comment]
I'm using Freshrss on a Qnap with Docker.
I have currently created a filter with many terms. Thus I can display and delete all articles with one application of the filter.
However, it is cumbersome to expand one filter further and further with OR intitle:. It would make sense here if there was a window in which the terms can be listed one below the other.
Furthermore, I would like the filter to work automatically and to mark the articles as read or delete them.

Is there a chance of implementation here in the future?

**Comment by Alkarex** [comment]
@1001Musik Could you please move your comment to a new issue, or even better, an existing one on the topic such as https://github.com/FreshRSS/FreshRSS/issues/3279

**Comment by math-GH** [comment]
done via https://github.com/FreshRSS/freshrss.org/pull/46
