### ISSUE TITLE
1.16.1: reading a feed folds its category in the left pane

### ISSUE THREAD

**Issue by ColasNahaboo** [FreshRSS/FreshRSS#3017]
I upgraded my 1.16.0 version to 1.16.1 (server: Debian linux, Client Firefox 76.0.1 unbuntu), and found an UI bug that made me downgrade to 1.16.0:

When unfolding a category in the left column (CSS class: "tree-folder category"), clicking a feed to read it instantly folds back the category.
Reverting back to 1.16.0 restored the normal behaviour of leaving the category unfolded.

It happens with Firefox (76.0.1 (64-bit)) 
and Chrome (Version 81.0.4044.138 (Official Build) (64-bit)), both on Ubuntu Linux.

**Comment by Alkarex** [comment]
Please check the new options to see whether one one them is as you want
![image](https://user-images.githubusercontent.com/1008324/83335401-d9c71900-a2ac-11ea-8eb4-f2332d02b665.png)

**Comment by Alkarex** [comment]
P.S. Could you please send a screenshot of your display options in 1.16.0?

**Comment by ColasNahaboo** [comment]
Here they are:

![Screenshot from 2020-05-30 19-59-52](https://user-images.githubusercontent.com/6825607/83335900-2f50f500-a2b0-11ea-91cf-7882ab38901a.png)

**Comment by ColasNahaboo** [comment]
I have upgraded to the last version (1.16.2-dev)

Same bug as 1.16.1

Here are the reading options in 1.16.2-dev:
![Screenshot from 2020-05-30 20-02-28](https://user-images.githubusercontent.com/6825607/83335953-92428c00-a2b0-11ea-8659-2dac705c1512.png)

**Comment by ColasNahaboo** [comment]
Ah OK, it works now.

I had to go to the Reading prefs, and then save the prefs without changing anything. I guess you added a new pref that has to be saved?

**Comment by Alkarex** [comment]
If you have not changed your options yet, I meant a screenshot of your reading options in 1.16.0.

**Comment by ColasNahaboo** [comment]
Ah too late. My first screenshot was of the Display prefs, not the Reading ones.
I could fetch you some file from my backups if it can help you to see what the state of my options were in 1.16.0.

PS: I just downgraded to 1.16.1, to stay on an official release, and the behavior is still correct now.

**Comment by Alkarex** [comment]
If you have a copy of your `./data/users/you/config.php` from 1.16.0, please show the line for `display_categories`.

For reference:
* https://github.com/FreshRSS/FreshRSS/pull/2888
* https://github.com/FreshRSS/FreshRSS/issues/2915

The code for compatibility with options coming from < 1.16.1

https://github.com/FreshRSS/FreshRSS/blob/5910009c212faee64d8d8f18e95854e2313eb49e/app/Models/ConfigurationSetter.php#L185-L190

**Comment by Alkarex** [comment]
I can reproduce the migration bug

**Comment by ColasNahaboo** [comment]
In my 1.16.0, I had:
  ```'display_categories' => false,```

**Comment by ColasNahaboo** [comment]
Thanks for your quick response, I guess we can close the issue!

**Comment by Alkarex** [comment]
Fixed by https://github.com/FreshRSS/FreshRSS/pull/3018
