### ISSUE TITLE
Docker Ubuntu version decision

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#3026]
Ubuntu 19.10 is supported until July, so if by then the bugs in Ubuntu 20.04 LTS are not fixed, we might have to revert back to the previous Ubuntu LTS, i.e. Ubuntu 18.04 LTS.
https://wiki.ubuntu.com/Releases

Main bug: https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1867675
* https://github.com/FreshRSS/FreshRSS/pull/2943
* https://github.com/FreshRSS/FreshRSS/issues/2939

**Comment by Alkarex** [comment]
Another possibility would be to base our ARM image on Alpine instead of Ubuntu.

**Comment by SuperSandro2000** [comment]
I just tested this and the bug only happens while building the Image on my Pi 3b from a Dockerfile. Not reproducable with binfmt or interactively.

I see two additional solutions:
- Only switch arm back to at least
- check if Debian has that bug, too and if not switch to Debian. Configuration should be almost identical


Ps if you don't have the hardware to test this feel free to ping me.

**Comment by Alkarex** [comment]
I still cannot get Ubuntu 20.04 base image to work on ARM (Raspberry Pi).
Debian 10 Buster seems to works fine: `FROM arm32v7/debian:buster` instead of `FROM arm32v7/ubuntu:19.10`.

```
sudo docker image ls
REPOSITORY                   TAG                 IMAGE ID            CREATED              SIZE
freshrss/freshrss            alpine-3.12         ade670ca716a        2 hours ago          824MB
freshrss/freshrss            debian-10-slim      d659fee8c2ad        44 seconds ago       933MB
freshrss/freshrss            ubuntu-19.10        f30a8ab58e76        25 seconds ago       942MB
freshrss/freshrss            ubuntu-20.04        e6e53dbf8901        2 hours ago          944MB
freshrss/freshrss            debian-10           45531b845162        2 minutes ago        983MB
```

I think the smoothest path is to move to Debian 10 Buster (Slim variant) instead of our current Ubuntu 19.10 (which is based on Debian 10 Buster).
https://askubuntu.com/questions/445487/what-debian-version-are-the-different-ubuntu-versions-based-on/445496#445496
