### ISSUE TITLE
Symlinking /p/api does not work

### ISSUE THREAD

**Issue by nebulade** [FreshRSS/FreshRSS#3030]
Hi,

for the [Cloudron package](https://cloudron.io/store/org.freshrss.cloudronapp.html) we have found that symlinking the `/p/api/` breaks with:
```
18:03:42 - [Wed Jun 03 16:03:42.893568 2020] [php7:warn] [pid 61] [client 172.18.0.1:60898] PHP Warning:  require(/app/data/p-api/../../constants.php): failed to open stream: No such file or directory in /app/data/p-api/index.php on line 11
18:03:42 - [Wed Jun 03 16:03:42.894994 2020] [php7:error] [pid 61] [client 172.18.0.1:60898] PHP Fatal error:  require(): Failed opening required '/app/data/p-api/../../constants.php' (include_path='.:/usr/share/php') in /app/data/p-api/index.php on line 11
```
 In this case the symlink points to `/app/data/p-api/` which contains the same content as the original `/p/api/` folder. The reason for the symlink is that on Cloudron apps run mostly in a read-only filesystem, however to be able to enable the TinyTinyRSS extension (which comes as a system extension) that api folder needs to be written to.

Some time back my colleague had created a pull request to fix a similar issue https://github.com/FreshRSS/FreshRSS/pull/1911 and I wanted to check in here if it may also be feasible to fix this upstream and if so, maybe the devs here could point me to the right code location to start with and possibly give some hints what needs to be fixed.

Thanks a lot,
Johannes

**Comment by Alkarex** [comment]
Hello,
First question is whether it is worth supporting the TinyTinyRSS extension at this stage. It has never been completed (see https://github.com/FreshRSS/FreshRSS/pull/1526 ) and I am not sure there is any client that works well and demands it. If you know one, please let me know. A list of know clients is available in https://github.com/FreshRSS/FreshRSS#apis--native-apps

**Comment by nebulade** [comment]
Ah ok, I was not aware of that fact. So if that extension would be gone, is there any other code/extension which needs to write to that `/p/api/` folder?

**Comment by Alkarex** [comment]
No, I do not think so

**Comment by Alkarex** [comment]
Good then? :-)

**Comment by nebulade** [comment]
yes, thanks for the quick responses and clarification!

**Comment by Alkarex** [comment]
By the way, since [1.16.0](https://github.com/FreshRSS/FreshRSS/releases/tag/1.16.0) we have tried to make it easier to add third-party extensions

> * Move core extensions (shipped with FreshRSS) to their own directory, so that `./extensions/` is solely for third-party extensions [#2837](https://github.com/FreshRSS/FreshRSS/pull/2837)
>    * This allows mounting `./extensions/` as a Docker volume, to ease adding third-party extensions

**Comment by rikmendes** [comment]
There are plenty of apps able to use Tiny Tiny RSS API to use for FreshRSS like http://levelupstudio.com/en/palabre, really sad if this extension is abandoned :/
