### ISSUE TITLE
Reeder 4 hiccups and broken login

### ISSUE THREAD

**Issue by gruberb** [FreshRSS/FreshRSS#3031]
I am running into a few problems when using FreshRSS on a Ubuntu 18.04 installation with Reeder 4 for iOS.

The initial login and fetching the Feeds works. however:
- Adding a new feed within Reeder fails (error screen "could not add feed"). When I close and open the app, the feed is there
- I can't put new feeds into folder when adding them in Reeder and have to do so manually after I "fail added" (adding, error, closing app, opening app) the new feed
- After every refresh, I have to login manually again because the login fails ("Request Failed, Pleaes re-authorize this account")

There are no logs in `/var/log/apache2`.

Login via the browser, adding feeds etc. works perfectly fine.

**Comment by Alkarex** [comment]
Hello,
Please check the logs in `./FreshRSS/data/users/_/log_api.txt` and share the parts related to those errors if you can.

To enable more logging (also of successful requests), you can uncomment the following two lines:
https://github.com/FreshRSS/FreshRSS/blob/27f0b614189c090028dfb9a56d1b21f1adf263d4/p/api/greader.php#L919-L920

I do not have any Apple product to test by myself.

**Comment by ishanjain28** [comment]
I am running freshrss(commit, 0085b5e0c1eb8d9d50fc264c86865329c09e877e) on arch linux.

I haven't been able to replicate any of the issues. It seems to be working perfectly for me. 

@gruberb, Have you already tried clearing data/reinstalling the app?

**Comment by gruberb** [comment]
Yeah the logs show no errors and I re-installed everything 3 or more times now.

Seems like an internal Reeder problem maybe. No apache logs and no Reeder logs.

**Comment by Alkarex** [comment]
Do you say that you do not have any log at all in your Web server logs and API log? If that is really the case, it might be that the request does not even arrive

**Comment by maurice-schleussinger** [comment]
I can confirm this. I just installed FreshRSS via Docker and added an account to the Reeder 4 Mac app. 

Adding feeds always works, but also always generates an error message.
After basically doing anything that changes feeds, folders and so on I get the alert that I need to login again and it fails. After restarting the app, everything works fine again.
**But**, I believe it only occurs if I am also logged in via web at the same time. I will continue to monitor this and report. 🙂

**Comment by kour1er** [comment]
I'm also seeing hiccups with subscribing to new feeds with the latest Reeder. I get a "unable to subscribe" error on Reeder (macOS) but FreshRSS has actually subscribed. Any better information I could provide to help track it down?

**Comment by Alkarex** [comment]
@kour1er If the client is using the `quickadd` method, I have just made some changes to it https://github.com/FreshRSS/FreshRSS/pull/3051 so you might want to try the latest /master version of FreshRSS.
In any case, it would be helpful to have at least the trace of the last calls made by Reeder, so that we can reproduce them and ensure that the response is correct. See https://github.com/FreshRSS/FreshRSS/issues/3031#issuecomment-638661211

**Comment by kour1er** [comment]
@Alkarex Thanks for the quick suggestion! I'm currently on the mainstream release (1.16.2). I'll switch to master this afternoon and do some testing

**Comment by kour1er** [comment]
@Alkarex so tried to capture something useful in the logs before switching to master, tried a couple subscribe actions but nothing was showing in the logs. Have now just switched to master, tried the same subscribe action and it worked perfectly. Will do some more testing and report back if I see any other issues. Thank you!

**Comment by kour1er** [comment]
@Alkarex Just to follow up on this issue - I'm seeing a minor thing when I try to subscribe to a feed via Reeder's Safari extension (so I assume this is using quickadd). If I just subscribe to a feed it works great but if at the point of subscribing, I also select to which category the feed should be added, FreshRSS doesn't seem to correctly process the category selection, only the feed.

I've looked in the log_api.txt and I see a warning:

> [Sat, 20 Jun 2020 08:29:18 +0000] [warning] --- badRequest() Array

but everything else looked ok - i.e. in the _POST => Array I am seeing the [a] => user/-/label/apple category being picked up.

Can I provide any more useful information? (this is using the latest master git pull from this morning)

**Comment by Alkarex** [comment]
@kour1er Could you please show the rest of the log regarding the warning / badRequest ?

**Comment by kour1er** [comment]
Sure - I've redacted the token and a couple of TLD bits for privacy (sorry about the formatting GitHub doesn't seem to like me):

---
```
[Sat, 20 Jun 2020 08:29:18 +0000] [warning] --- badRequest() Array
(
    [date] => 2020-06-20T08:29:18+00:00
    [headers] => Array
        (
            [Host] => [domain_redacted]
            [Content-Type] => application/x-www-form-urlencoded
            [User-Agent] => Reeder/4020.59.05 CFNetwork/1126 Darwin/19.5.0 (x86_64)
            [Connection] => keep-alive
            [Accept] => */*
            [Accept-Language] => en-gb
            [Content-Length] => 114
            [Accept-Encoding] => gzip, deflate, br
            [Authorization] => GoogleLogin auth=[token_redacted]
        )

    [_SERVER] => Array
        (
            [SCRIPT_URL] => /api/greader.php/reader/api/0/subscription/edit
            [SCRIPT_URI] => https://[domain_redacted]/api/greader.php/reader/api/0/subscription/edit
            [HTTP_AUTHORIZATION] => GoogleLogin auth=[token_redacted]
            [HTTPS] => on
            [SSL_TLS_SNI] => [domain_redacted]
            [HTTP_HOST] => [domain_redacted]
            [CONTENT_TYPE] => application/x-www-form-urlencoded
            [HTTP_USER_AGENT] => Reeder/4020.59.05 CFNetwork/1126 Darwin/19.5.0 (x86_64)
            [HTTP_CONNECTION] => keep-alive
            [HTTP_ACCEPT] => */*
            [HTTP_ACCEPT_LANGUAGE] => en-gb
            [CONTENT_LENGTH] => 114
            [HTTP_ACCEPT_ENCODING] => gzip, deflate, br
            [PATH] => /usr/bin:/bin:/usr/sbin:/sbin
            [SERVER_SIGNATURE] => 
            [SERVER_SOFTWARE] => Apache/2.4.43 (Unix) OpenSSL/1.1.1g PHP/7.4.6
            [SERVER_NAME] => [domain_redacted]
            [SERVER_ADDR] => 10.0.0.2
            [SERVER_PORT] => 443
            [REMOTE_ADDR] => 86.25.129.56
            [DOCUMENT_ROOT] => [path_redacted]/FreshRss/p/
            [REQUEST_SCHEME] => https
            [CONTEXT_PREFIX] => 
            [CONTEXT_DOCUMENT_ROOT] => [path_redacted]/FreshRss/p/
            [SERVER_ADMIN] => [user_redacted]
            [SCRIPT_FILENAME] => [path_redacted]/FreshRss/p/api/greader.php
            [REMOTE_PORT] => 56076
            [GATEWAY_INTERFACE] => CGI/1.1
            [SERVER_PROTOCOL] => HTTP/1.1
            [REQUEST_METHOD] => POST
            [QUERY_STRING] => 
            [REQUEST_URI] => /api/greader.php/reader/api/0/subscription/edit
            [SCRIPT_NAME] => /api/greader.php
            [PATH_INFO] => /reader/api/0/subscription/edit
            [PATH_TRANSLATED] => [path_redacted]/FreshRss/p/reader/api/0/subscription/edit
            [PHP_SELF] => /api/greader.php/reader/api/0/subscription/edit
            [REQUEST_TIME_FLOAT] => 1592641758.386
            [REQUEST_TIME] => 1592641758
        )

    [_GET] => Array
        (
        )

    [_POST] => Array
        (
            [T] => [token_redacted]
            [a] => user/-/label/mac
            [s] => feed/feed/247
            [ac] => edit
        )

    [_COOKIE] => Array
        (
        )

    [INPUT] => T=[token_redacted]&a=user%2F-%2Flabel%2Fmac&s=feed%2Ffeed%2F247&ac=edit
)
```
---

**Comment by Frenzie** [comment]
I edited it to use:
````
```
code block
```
````

**Comment by Alkarex** [comment]
@kour1er Please try this patch https://github.com/FreshRSS/FreshRSS/pull/3073

**Comment by kour1er** [comment]
@Alkarex nice! Tested the patch on three feeds so far, both with adding a category and not, and the patch is working great! Great work 👍

**Comment by Alkarex** [comment]
Great, thanks for the feedback @kour1er All good then?
And in our table https://github.com/FreshRSS/FreshRSS#apis--native-apps can please you confirm that Reeder is able to manage feeds then (and double-check the other columns)?

**Comment by kour1er** [comment]
All good here - I will let you know if I see any other subscribe related issues. 

Yes Reeder is indeed able to manage feeds. I've tested:
Subscribe
Subscribe + set category
Change category
Unsubscribe

As to the other columns: 
Uncertain as to what 'fetch more in individual views' means. Reeder does have the native ability to do a full text extraction via Mercury hosted by the Feedbin guy but that's not touching FreshRSS.
Reeder doesn't have the concept of Labels as far as I'm aware, nor Podcasts.
