### ISSUE TITLE
Export raw list of links/articles?

### ISSUE THREAD

**Issue by winteriscariot** [FreshRSS/FreshRSS#3033]
I want to feed the links from FreshRSS into an archiver (archivebox) in order to properly get around paywalls. I know FreshRSS has native support for "css paths" in order to pull the full article, but I'd like to rely on a external program for extended archiving functions. Unfortunately I haven't been able to find any CLI functions for exporting articles, only lists of feeds.

Is there a way that I can export a list of unread articles? This way I can feed it directly to my archiver. Even if they were exported in some markup i could parse it with grep and find what I need.

Even if I just exported a list of articles every time FreshRSS refreshes, that could work too (thereby capturing everything). 

Thanks!

**Comment by aledeg** [comment]
Have you tried with the API? You might be able to access what you need with the proper call.

**Comment by Alkarex** [comment]
See https://freshrss.github.io/FreshRSS/en/users/06_Mobile_access.html

* The Fever API is easier but not so efficient or feature-rich: https://feedafever.com/api
* The Google Reader API is better but more complicated: see e.g. https://feedhq.readthedocs.io/en/latest/api/index.html , https://www.inoreader.com/developers/

**Comment by aledeg** [comment]
@Alkarex while reading the documentation, I came across [streams](https://feedhq.readthedocs.io/en/latest/api/terminology.html#streams) and the API should allow to list all unread messages with one call. I've tried it and it does not work.

Here is the call I made:
```
curl -s -H 'Authorization:GoogleLogin auth=xxxx/xxxx' 'http://localhost:8080/api/greader.php/reader/api/0/stream/contents/user/-/state/com.google/kept-unread?output=js'
```

Is this implemented or did I missed something?

**Comment by Alkarex** [comment]
@aledeg In FreshRSS, there is no concept of *kept-unread*. We only have read/not-read, starred, and various labels.

Example if you would like to retrieve the 10 newest unread articles:

```sh
curl -s -H "Authorization:GoogleLogin auth=xxxx/xxxx" 'https://freshrss.example.net/api/greader.php/reader/api/0/stream/contents/reading-list?n=10&xt=user/-/state/com.google/read'
```

See also
* https://freshrss.github.io/FreshRSS/en/users/06_Mobile_access.html
* https://www.inoreader.com/developers/stream-contents

**Comment by winteriscariot** [comment]
Thanks for all the info! I'll probably try playing with the API, but for my purposes the zip export does enough at the CLI for me to feed into my archiver. Closing.

**Comment by Alkarex** [comment]
You can also check the SQLite export via CLI
