### ISSUE TITLE
Provide docker release tag

### ISSUE THREAD

**Issue by wollew** [FreshRSS/FreshRSS#3039]
Hi, I like to automatically check for updates of my docker containers but I don't really want to use "latest" because this seems to be the development branch. So it would be nice to have a release tag, that always points to the latest release version.

**Comment by Alkarex** [comment]
Will do https://github.com/FreshRSS/FreshRSS/discussions/3296

**Comment by Alkarex** [comment]
Done:

* `freshrss/freshrss:latest` = latest release based on Debian
* `freshrss/freshrss:latest-alpine` = latest release based on Alpine Linux
* `freshrss/freshrss:latest-arm` = latest release based on Debian for ARM

* `freshrss/freshrss:edge` = git build rolling release based on Debian
* `freshrss/freshrss:edge-alpine` = git build rolling release based on Alpine Linux
* `freshrss/freshrss:edge-arm` = git build rolling release based on Debian for ARM

I will document as part of https://github.com/FreshRSS/FreshRSS/issues/3351
