### ISSUE TITLE
Feature: Cacher les articles comportant certains mots

### ISSUE THREAD

**Issue by mathieumd** [FreshRSS/FreshRSS#304]
Une des fonctionnalités très pratiques au quotidien de Newsblur c'est « l'Intelligence Trainer ». Basé sur des mots (catégories, keywords, auteurs, etc.) que l'on a notés positivement ou négativement, cela permet :
- de cacher les articles à priori non intéressants (car contenant des mots notés négativement) ;
- ou de n'afficher que les articles à priori intéressants (mots notés positivement).

FreshRSS est déjà excellent tel quel (_à quand un widget Flattr sur le site?_), mais pour les gros consommateurs de feeds, ça peut être une fonctionnalité intéressante.

**Comment by math-GH** [comment]
Should we keep this as an open FR?

**Comment by Alkarex** [comment]
We can now automatically mark as read articles matching certain rules for a given feed
