### ISSUE TITLE
United States English (en-us) Localization 

### ISSUE THREAD

**Issue by ewsandor** [FreshRSS/FreshRSS#3041]
Hi,

I have recently started using FreshRSS and have been very happy with it so far.  One minor nuisance I had was the international spelling of 'Favourite' on the home page.  

I 'fixed' this on my personal instance by adding an i18n localization to use United States English (en-us) spellings using the instructions at https://freshrss.github.io/FreshRSS/en/internationalization.html.

I have done an initial pass of this localization on my personal instance.  If there is interest, I'd be willing to refine my localization and help contribute this to the main FreshRSS repository.

Examples of spelling changes:
favourite -> favorite
optimise -> optimize
occured -> occurred
labelled -> labeled

This is my first contribution to this project, so any advice or guidance is appreciated to meet the projects standards.

**Comment by aledeg** [comment]
Hi @ewsandor, if you want to make such localization you need to create a new language and translate all the entries that need your attention. To do so, there are CLI tools to help you do that. Once done, you can make a pull request so we can test it and evaluate its content.
Thank you!

**Comment by Frenzie** [comment]
@ewsandor 
> occured -> occurred

That's just a mistake, not British English.

@aledeg 
I wonder if we should implement some kind of whitelist for this scenario or is that already supported? Besides a few spelling differences like favorite/favourite and possibly the occasional preference for past perfect over simple past or something, the vast majority of strings will be exactly the same.

Something similar would apply for language varieties in general, like Belgian Dutch vs Netherlandic Dutch, European French vs Canadian French, perhaps also European vs Brazilian Portuguese.

**Comment by aledeg** [comment]
@Frenzie There is no whitelist at the moment but I am not sure there is a need for that. Even if languages are pretty similar, I think it is better to keep them separated even if there is a lot of thing in common. What we are missing right now is a way of generating a new language based on an existing one. At the moment, the new language is created from English.
This is not a big deal for this use case but could be bothersome for other languages.

**Comment by ewsandor** [comment]
So far, on my personal instance:
1. I have added a language (en-us) using the CLI tool.
2. I have gone through with a en-us spell checker to catch international spellings.
3. I added a new key to the language list to give a friendly name in the setting's menu.
4. I ran the CLI format tool to sanitize and cleanup the translation files.

At this point I've been pretty happy for my own use ('favourite' was the main thing annoying me :) ). 

Before I call it done though, I plan to do the following:

5. Change any grammatical differences such as @Frenzie mentioned.
6. Change any vocab differences I find.  I don't expect many in this context, but a classic example is pants/trousers.
7. Use the CLI tool to 'ignore' the remaining entries.
8. If we agree 'occured' is wrong, I can fix this for default English too while I'm thinking about it

If these steps sound reasonable, I can proceed and send a pull request when ready.

I expect likely 90% of translations will be untouched as most of the differences are subtle.  I did notice some spelling is split in the default English translation, e.g. some places 'favourite' is used and other places 'favorite' is used for both keys and strings.  After separating the English varieties, it may make sense to fix inconsistencies, though probably a separate issue from this one.

**Comment by aledeg** [comment]
Your plan is reasonable. For the inconsistencies, there is already a separate issue (#1783). You can either add your thoughts there or even create a PR to address that. Any help is welcomed.

Anyway, thank you for your help! It's appreciated.

**Comment by Frenzie** [comment]
@aledeg 
> What we are missing right now is a way of generating a new language based on an existing one.

I'd say that's called copy, paste, rename. Not sure you need a tool for that, but feel free. ;-)

**Comment by aledeg** [comment]
@Frenzie There is already a tool for that but the starting point is always the English language. I just need to add a parameter to select a starting language.

**Comment by Frenzie** [comment]
@ewsandor 
> Change any grammatical differences such as @Frenzie mentioned.

Note that any grammatical or stylistic oddities in the program are significantly more likely to be Frenglish (or is that Franglais) than British English, and that they should therefore be corrected tout court. "Subscriptions management" would be the most noticeable example of that. I was merely mentioning that theoretically speaking, one could envision minor preferences for one grammatical construction over another in different varieties of English.
