### ISSUE TITLE
[greader-api] subscription/quickadd

### ISSUE THREAD

**Issue by Stunkymonkey** [FreshRSS/FreshRSS#3049]
I think the `subscription/quickadd` is not really returning what it should return.
When looking at [feedhq](https://feedhq.readthedocs.io/en/latest/api/reference.html#subscription-quickadd)

the `quickadd` is not well documented, but currently it returns something like:
```
{
  "numResults": 1,
  "streamId": 225
}
```
looking all over the api-specs returning an integer here does not make sense at all since google reader ids are always like this: e.g. "feed/http://feeds.feedburner.com/alistapart/main"

aside from that, the `query` is completely omitted and should be added as well.

Sorry for being pedantic about the APIs, but currently the integer IDs does not make sense to me at all.

**Comment by Frenzie** [comment]
It may be that the line should read `'feed/' . $feed->id()`. Pinging @Alkarex.

**Comment by Stunkymonkey** [comment]
> It may be that the line should read `'feed/' . $feed->id()`. Pinging @Alkarex.

yes this sounds good for me

**Comment by Alkarex** [comment]
> It may be that the line should read `'feed/' . $feed->id()`. Pinging @Alkarex.

Indeed @Frenzie and @Stunkymonkey , that was an error. https://github.com/FreshRSS/FreshRSS/pull/3051

**Comment by Alkarex** [comment]
I will look into the `query` part as well

**Comment by Alkarex** [comment]
@Stunkymonkey Please check https://github.com/FreshRSS/FreshRSS/pull/3051

**Comment by Stunkymonkey** [comment]
the `streamName` is not needed, but does not hurt.
Other then that it looks good to me, but I have not yet tested it.

**Comment by Alkarex** [comment]
`streamName` is for better compatibility with https://www.inoreader.com/developers/add-subscription
