### ISSUE TITLE
Add information about the Reeder 4 date fix to README

### ISSUE THREAD

**Issue by maurice-schleussinger** [FreshRSS/FreshRSS#3052]
Hello 🙂 

I just installed FreshRSS and was wondering why all new feed entries in Reeder 4 are wrongly dated. After skimming trough this lengthy discussion https://github.com/FreshRSS/FreshRSS/issues/2759 it is my understanding that this won't be changed as it is open to interpretation if this is a correct implementation of the Google Reader API or not.

From a more casual user perspective this is an irritating experience overall. I would suggest adding a **very visible** line or footnote about the need to install https://github.com/javerous/freshrss-greader-redate if one wishes to use FreshRSS and Reeder and have correct dates. https://github.com/FreshRSS/FreshRSS/blob/master/README.md#apis--native-apps seems like a good place for that.

Thank you for taking the time to work on this awesome software! 🥳

**Comment by johnnykang** [comment]
Hi, just wonder if the extension still works with Reeder 4.2.5? I installed the extension but the api endpoint still returns the wrong date (as discussed in the #2759). I am sure the extension is loaded.

Thought?

**Comment by maurice-schleussinger** [comment]
@johnnykang I am using it with the iOS Reeder App (v4.2.5) right now. Dates are correctly formatted.

Does you extension configuration show a screen like this?
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/1615089/91634521-57580d80-e9f1-11ea-8516-2fef0b48f97d.png">

**Comment by Daniel15** [comment]
I know this is old, but thanks for posting it!! I was having the same issue in FeedMe and this issue pointed me to the GReader Redate extension. Works perfectly!
