### ISSUE TITLE
500 Internal Server Error after logging in

### ISSUE THREAD

**Issue by mangenehm** [FreshRSS/FreshRSS#3054]
### Setup
FreshRSS version 1.16.3-dev
PHP Version 7.2.31
MariaDB 10.3

### Issue
After log in FreshRSS responses with an 500 Internal Server Error. The PHP log show the following error:

> [13-Jun-2020 18:30:45] WARNING: [pool www] child 967 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Call to a member function bindValue() on boolean in /var/www/virtual/maez/FreshRSS-master/app/Models/EntryDAO.php:1087"
> [13-Jun-2020 18:30:45] WARNING: [pool www] child 967 said into stderr: "Stack trace:"
> [13-Jun-2020 18:30:45] WARNING: [pool www] child 967 said into stderr: "#0 /var/www/virtual/maez/FreshRSS-master/app/Controllers/indexController.php(188): FreshRSS_EntryDAO->countUnreadReadFavorites()"
> [13-Jun-2020 18:30:45] WARNING: [pool www] child 967 said into stderr: "#1 /var/www/virtual/maez/FreshRSS-master/app/Controllers/indexController.php(30): FreshRSS_index_Controller->updateContext()"
> [13-Jun-2020 18:30:45] WARNING: [pool www] child 967 said into stderr: "#2 /var/www/virtual/maez/FreshRSS-master/lib/Minz/Dispatcher.php(119): FreshRSS_index_Controller->normalAction()"
> [13-Jun-2020 18:30:45] WARNING: [pool www] child 967 said into stderr: "#3 /var/www/virtual/maez/FreshRSS-master/lib/Minz/Dispatcher.php(47): Minz_Dispatcher->launchAction('normalAction')"
> [13-Jun-2020 18:30:45] WARNING: [pool www] child 967 said into stderr: "#4 /var/www/virtual/maez/FreshRSS-master/lib/Minz/FrontController.php(84): Minz_Dispatcher->run()"
> [13-Jun-2020 18:30:45] WARNING: [pool www] child 967 said into stderr: "#5 /var/www/virtual/maez/FreshRSS-master/p/i/index.php(48): Minz_FrontController->run()"
> [13-Jun-2020 18:30:45] WARNING: [pool www] child 967 said into stderr: "#6 {main}"
> [13-Jun-2020 18:30:45] WARNING: [pool www] child 967 said into stderr: "  thrown in /var/www/virtual/maez/FreshRSS-master/app/Models/EntryDAO.php on line 1087"

When trying to access over via FeedMe (Android App) the log shows the following:

> [13-Jun-2020 16:13:13] WARNING: [pool www] child 14094 said into stderr: "NOTICE: PHP message: PHP Warning:  Invalid argument supplied for foreach() in /var/www/virtual/maez/FreshRSS-master/p/api/greader.php on line 255"
> [13-Jun-2020 16:13:13] WARNING: [pool www] child 14094 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Call to a member function execute() on boolean in /var/www/virtual/maez/FreshRSS-master/app/Models/EntryDAO.php:969"
> [13-Jun-2020 16:13:13] WARNING: [pool www] child 14094 said into stderr: "Stack trace:"
> [13-Jun-2020 16:13:13] WARNING: [pool www] child 14094 said into stderr: "#0 /var/www/virtual/maez/FreshRSS-master/p/api/greader.php(699): FreshRSS_EntryDAO->listIdsWhere('A', 'user/-/state/co...', 2, 'DESC', 100, '', Object(FreshRSS_BooleanSearch))"
> [13-Jun-2020 16:13:13] WARNING: [pool www] child 14094 said into stderr: "#1 /var/www/virtual/maez/FreshRSS-master/p/api/greader.php(1018): streamContentsItemsIds('user/-/state/co...', 0, 0, 100, 'd', '', 'user/-/state/co...', '')"
> [13-Jun-2020 16:13:13] WARNING: [pool www] child 14094 said into stderr: "#2 {main}"
> [13-Jun-2020 16:13:13] WARNING: [pool www] child 14094 said into stderr: "  thrown in /var/www/virtual/maez/FreshRSS-master/app/Models/EntryDAO.php on line 969"

FreshRSS log shows the same issue over and over again ([log.txt](https://github.com/FreshRSS/FreshRSS/files/4775039/log.txt)):

> [Sat, 13 Jun 2020 18:25:05 +0200] [error] --- SQL error addEntry: HY000: 1033 Incorrect information in file: './maez_freshrss/freshrss_mangenehm_entrytmp.frm' while adding entry in feed 26 with title: Schulunterricht soll nach den Sommerferien normal laufen

**Comment by Alkarex** [comment]
Hello,
I cannot reproduce and I am afraid it is not due to FreshRSS but most likely a DB corruption (e.g. disk error). What type of server are you running on?
Please update to the latest FreshRSS /master in which I have added a log message https://github.com/FreshRSS/FreshRSS/pull/3055 to help finding the exact problem.

**Comment by Alkarex** [comment]
P.S. See https://mariadb.com/kb/en/mysqlcheck/

**Comment by mangenehm** [comment]
Thanks, @Alkarex! It was indeed the DB which was corrupt. Luckily my hoster does a daily dump so I was able to recreate the DB and now everything's looking good again. Thanks for the prompt help!
