### ISSUE TITLE
The actual version of the extension is different from the version displayed on the admin page

### ISSUE THREAD

**Issue by imkuang** [FreshRSS/FreshRSS#3064]
These days I have noticed that there are some updates to the extensions in [FreshRSS/Extensions](https://github.com/FreshRSS/Extensions), and the Image Proxy extension has been upgraded to version 0.5, you can check the [metadata.json](https://github.com/FreshRSS/Extensions/blob/master/xExtension-ImageProxy/metadata.json) for this information.

So I reinstalled it, but I found that the version displayed on the admin page is still 0.4, as shown below
![WjsE.png](https://img.xirikm.net/images/WjsE.png)

When I enable it, I can see the current version is 0.5 on its management interface.
![WP1z.png](https://img.xirikm.net/images/WP1z.png)

I don’t know how the program gets the versions of each extension, but now the version of Image Proxy is obviously wrong. Although this is not a serious problem, it is better to fix it if possible.

**Comment by imkuang** [comment]
When I submitted this issues, I received a 500 error from github, so I resubmitted it, and then I found that this issues has also been posted. So I will close it.

**Comment by Frenzie** [comment]
That's because it wasn't updated [here](https://github.com/FreshRSS/Extensions/blob/e9616f7cbe91a5e6346e560a66d64a8bc7c0eb07/extensions.json#L20-L27). It'll be fixed in a more sustainable manner by https://github.com/FreshRSS/Extensions/pull/83.
