### ISSUE TITLE
Share feeds between users?

### ISSUE THREAD

**Issue by LVerneyPEReN** [FreshRSS/FreshRSS#3066]
Hi,

First of all, thanks for this very nice software! I have a slightly particular use case though, which involves a kind of cooperation between users.

Ideally, I'd like any user to be able to pick feeds from any other user's account and add it to its account (my users all share the same interestes), to help improve discoverability of RSS feeds.

Is there anything which could help me achieve this? Or is there any "dirty hack" solution which could achieve this (or alternatively pre-filling a list of RSS feeds for new user accounts)?

Otherwise, what would it require (in terms of development) to add such a feature in FreshRSS?

Thanks!
Best,

**Comment by Alkarex** [comment]
Hello,
It is not something we have at the moment, but it would both be possible to find some workarounds, and/or add new features.
This needs to be done with respect for users privacy.
A couple of quick ideas already:
* Share articles (via FreshRSS RSS feed, for instance limited to a label *Shared*) between users; 
* Make some users export their OPML list of feeds (with or without further manual edits), to use as a reference for new users (FreshRSS can be given a local OPML to be automatically applied for new users);

**Comment by LVerneyPEReN** [comment]
> Share articles (via FreshRSS RSS feed, for instance limited to a label Shared) between users;

This would be really nice, but accessing FreshRSS RSS feed is only limited to the current user, isn't it? This would be perfect to address a semi-related use case which is sharing articles between users.

> Make some users export their OPML list of feeds (with or without further manual edits), to use as a reference for new users (FreshRSS can be given a local OPML to be automatically applied for new users);

This would be very nice as a workaround my initial use case. How can I provide a local OPML to apply automatically for new users? (did not find it in the doc or in the config)

Thanks

**Comment by aledeg** [comment]
Check #2627

**Comment by Alkarex** [comment]
@LucasVerneyDGE 

> This would be really nice, but accessing FreshRSS RSS feed is only limited to the current user, isn't it? This would be perfect to address a semi-related use case which is sharing articles between users.

Any user can re-share by RSS their FreshRSS views (e.g. a label). They just need to specify a token (but watch out, I need to rework this part to allow a token to be limited to only a view, and to have multiple tokens).

> This would be very nice as a workaround my initial use case. How can I provide a local OPML to apply automatically for new users? (did not find it in the doc or in the config)

As @aledeg wrote, this is indeed possible by creating a `./FreshRSS/data/opml.xml`

**Comment by LVerneyPEReN** [comment]
> Any user can re-share by RSS their FreshRSS views (e.g. a label). They just need to specify a token (but watch out, I need to rework this part to allow a token to be limited to only a view, and to have multiple tokens).

This could definitely be a match! Plus, if I read correctly the token can be configured as default for new users: https://github.com/FreshRSS/FreshRSS/blob/master/config-user.default.php#L21 (I'm in a specific context where I want to operate FreshRSS as a way to ease news reviewing between a private group of non tech-savvy users).


> As @aledeg wrote, this is indeed possible by creating a ./FreshRSS/data/opml.xml

Thanks for the info! I think this might be worth mentioning in the doc since it's very hard to discover this feature (since it lives outside of the main config files).

**Comment by aledeg** [comment]
> Thanks for the info! I think this might be worth mentioning in the doc since it's very hard to discover this feature (since it lives outside of the main config files).

PR welcomed :)

**Comment by Alkarex** [comment]
As it is now, the token was not meant to be used for sharing widely (but rather for other tools), because the same token can be used for any view. That is why we need to rework the token system to be at least per-view. So let's wait a bit before promoting this feature too much :-)

**Comment by aledeg** [comment]
Related to #3178

**Comment by Jieiku** [comment]
A simple solution would be to have a shared feed list.

Anytime a user adds a feed, they could check a box to add it to the shared feed list.

Have an option for shared by default, and the user would have to uncheck it instead if they wanted to keep it private.

Any feed in the shared feed list could be visible to all users, etc.

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/6052
