### ISSUE TITLE
Title of feeds not refreshed when imported from .opml without field for titles

### ISSUE THREAD

**Issue by felixbinder** [FreshRSS/FreshRSS#3067]
I've imported my many subscriptions from an opml from theoldreader. The import worked fine, but the new subscription have neither title nor description, which is of course very inconvenient. I'd prefer to not have to go through manually and update all the descriptions. Expected behavior is for the titles and descriptions to be pulled from the website if the field is empty during import

An excerpt from the opml file:
` <body>
    <outline type="rss" xmlUrl="http://mcmansionhell.com/rss"/>
    <outline type="rss" xmlUrl="http://lukependergrass.work/blog?format=RSS"/>
    <outline type="rss" xmlUrl="https://medium.com/feed/map-and-territory"/>
    <outline type="rss" xmlUrl="http://yudkowsky.tumblr.com/rss"/>`

Importing with the title contained in the opml worked fine

**Comment by Alkarex** [comment]
@felixbinder Could you please try this patch? https://github.com/FreshRSS/FreshRSS/pull/3071
You can just refresh your existing feeds or restart from a blank user.

**Comment by Alkarex** [comment]
@felixbinder The patch has just been merged, so you can just try the latest /master branch. Feedback welcome
