### ISSUE TITLE
GReader API returns 200 OK

### ISSUE THREAD

**Issue by jakem72360** [FreshRSS/FreshRSS#3076]
As the title says, attempting to login using the GReader API returns the message `OK`, and nothing else. No authentication token is returned. Because of this, login on the FreshRSS app isn't working either.

```
$ curl 'https://[REDACTED]/api/greader.php/accounts/ClientLogin' -d 'Email=[REDACTED]' -d 'Passwd=[REDACTED]'
OK
```

`/api` page:
![5c957285](https://user-images.githubusercontent.com/7912205/85232711-67c59800-b444-11ea-85ff-e23ae70487f4.png)

It's worth noting that the result is the same regardless of the credentials supplied (or their validity). I'd provide logs, but an `api_log` doesn't seem to have been created, and the user, nginx and PHP logs are all empty.

OS: Arch Linux
php-fpm: 7.4.7
nginx: 1.19.0
mariadb: 10.4.13
freshrss: 1.16.3-dev

nginx config:
```
# vim: et:sw=4

server {
    listen       80;
    server_name  [REDACTED];
    return 301 https://$host$request_uri;
}

server {
    listen       443 ssl http2;
    server_name [REDACTED];

    ssl_certificate     /etc/letsencrypt/live/[REDACTED]/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/[REDACTED]/privkey.pem;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    root /srv/http/freshrss/p/;

    index index.php index.html index.htm;

    # PHP files handling
    # this regex is mandatory because of the API
    location ~ ^.+?\.php(/.*)?$ {
        try_files $fastcgi_script_name = 404;

        include fastcgi_params;

        fastcgi_pass            unix:/run/php-fpm/php-fpm.sock;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        fastcgi_index           index.php;
        fastcgi_buffers         8 16k;
        fastcgi_buffer_size     32k;

        # By default, the variable PATH_INFO is not set under PHP-FPM
        # But FreshRSS API greader.php need it. If you have a “Bad Request” error, double check this var!
        fastcgi_param PATH_INFO $fastcgi_path_info;

        fastcgi_param DOCUMENT_ROOT $realpath_root;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
    }

    location / {
        try_files $uri $uri/ index.php;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
```

**Comment by Frenzie** [comment]
@Alkarex is more familiar with this, but in the meantime you could also uncomment these lines to see what happens. The data will be in `data/users/_/log_api.txt` iirc.

https://github.com/FreshRSS/FreshRSS/blob/051f1649f705dd77febd39c8f4a53c97f4c1115f/p/api/greader.php#L929-L930

**Comment by Alkarex** [comment]
Hello,
The `OK` is misleading, but the automatic test does show a ❌ indicating a configuration error (I will try to fix that). So you must first obtain a ✔️.
Using nginx is most of the time the source of error. This looks like a `PATH_INFO` misconfiguration.
I cannot immediately spot an error, but please double-check against https://freshrss.github.io/FreshRSS/en/admins/10_ServerConfig.html

As @Frenzie suggests, please share the extended logs so we might narrow down the issue, and potentially improve the automatic test.

Manual test: Try with a `phpinfo.php` file:

```php
<?php
phpinfo();
```

And then access it using your browser at the address `https://your-server.example.net/phpinfo.php/hello` and you should see something like:

![image](https://user-images.githubusercontent.com/1008324/85235467-6466e800-b415-11ea-9a7a-35d0e35d038f.png)

Alternatively, we have a Docker image or an Apache configuration.

**Comment by jakem72360** [comment]
Nevermind. `PATH_INFO` wasn't being set, apparently due to a [seven year-old nginx bug](https://trac.nginx.org/nginx/ticket/321)

Adding this to my config seems to have fixed the issue (might be worth updating the official config).
```
set $path_info $fastcgi_path_info;
fastcgi_param PATH_INFO $path_info;
```

**Comment by Alkarex** [comment]
@jakem72360 Thanks for tracking down the issue!
Would you have time to propose edits to:
* https://github.com/FreshRSS/FreshRSS/blob/master/docs/en/admins/10_ServerConfig.md#nginx-configuration
* https://github.com/FreshRSS/FreshRSS/blob/master/docs/fr/users/01_Installation.md#installation-sur-nginx
