### ISSUE TITLE
Show website name when opening article

### ISSUE THREAD

**Issue by Massedil** [FreshRSS/FreshRSS#3079]
This CSS rule remove the website name, but it seems that no rule display it elsewhere  :

```
.item.website span
{
    display: none;
}
```

Expected : We can see the website name with mobile view

**Comment by Alkarex** [comment]
You can override the behaviour using e.g. the CustomCSS extension.
The original rule is:
https://github.com/FreshRSS/FreshRSS/blob/d7d39f07368379e7ef1619e52cc50c0920ce8351/p/themes/base-theme/template.css#L1236-L1243

**Comment by Massedil** [comment]
For me, sometimes, I can't easily know from which website come the information and I have to long click on the link to see what is the website from the URL.

I think it can be interesting to see it before or after the `<div class="author">`.

> You can override the behaviour using e.g. the CustomCSS extension.

Thanks !

Don't you think it can be interesting for everyone to keep access to this information ?

**Comment by Alkarex** [comment]
I misunderstood your question: I thought you were referring to the FreshRSS logo / site name...
But you can still override the behaviour with a CustomCSS rule.
In mobile view, I do not believe that there is not enough space to show the site title in the list view, but we do show the site favicon. There is also the possibility the browse to specific categories or feeds, to be sure about what you read.
Maybe we should show the Web site title when opening an article though.

**Comment by Alkarex** [comment]
Yes, so as you suggest, showing the Web site inside the article would be a possible option

**Comment by Massedil** [comment]
> I misunderstood your question: I thought you were referring to the FreshRSS logo / site name...

Just to be more precise for everyone reading this.

In large width view :

![](https://user-images.githubusercontent.com/20357783/85739283-f23a2000-b700-11ea-8a13-708cc009b74a.png)

In small width view the website name disappears and I suggest to move it near the author zone (or to keep it somewhere near the top of the article) :

![](https://user-images.githubusercontent.com/20357783/85739396-0aaa3a80-b701-11ea-936c-4d14647903a6.png)

The same problem occurs for the publication date and it can maybe also be moved near the author zone.

**Comment by Alkarex** [comment]
@Massedil Please check https://github.com/FreshRSS/FreshRSS/pull/3081

**Comment by Massedil** [comment]
> Please check #3081

Checked ! Works fine and solve my reported problem ! Thanks !

1. In the same time, what do you think about also adding the publication date ?

2. And to better formulate the line, something like "Publié le 31 mai 2020 à 22:33 sur [FreshRSS]() par [Alkarex]()".

3. And, I think, to light the view, we maybe can remove the redundant favicon from this sentence because it is always displayed above.

---
Desktop :

![](https://user-images.githubusercontent.com/20357783/85847364-8959b300-b7a7-11ea-9533-b2d738a3204a.png)

Mobile (no publication date) : 

![](https://user-images.githubusercontent.com/20357783/85848017-ba86b300-b7a8-11ea-8a4d-761e67657654.png)

**Comment by Alkarex** [comment]
@Massedil Done in https://github.com/FreshRSS/FreshRSS/pull/3081#issuecomment-657045402 Tests welcome, also with the various FreshRSS themes

**Comment by Massedil** [comment]
> Tests welcome

Updated to latest master version and works fine for me with the default theme. Thanks.

**Comment by Massedil** [comment]
I don't know if you care but there is some unwanted spaces around some sentences : 

![](https://user-images.githubusercontent.com/20357783/87682585-483e3880-c780-11ea-95f9-78fde29e1285.png)
