### ISSUE TITLE
Youtube Feed Bug ?

### ISSUE THREAD

**Issue by ddmunhoz** [FreshRSS/FreshRSS#3083]
Hey guys, is this a bug ? I'm trying to create a feed from a YouTube channel.
So I added it normally, just like any other feed.
It created the feed list fine, but when I click on the FloppyDisk button inside the article, it sends me to the wrong URL:

Correct link: https://www.youtube.com/watch?v=ZLyDvABxGF0
Wrong Link created by FreshRSS: https://www.youtube.com/v/ZLyDvABxGF0?version=3

**Comment by Frenzie** [comment]
I assume you subscribed to https://www.youtube.com/channel/UCBJycsmduvYEL83R_U4JriQ which resolves itself to https://www.youtube.com/feeds/videos.xml?channel_id=UCBJycsmduvYEL83R_U4JriQ? In any case, that is indeed simply a part of the feed. But

```xml
<media:content url="https://www.youtube.com/v/ZLyDvABxGF0?version=3" type="application/x-shockwave-flash" width="640" height="390"/>
```

But since the link element indicates the regular URL, all the usual ways of getting there work as you'd expect.

```xml
<link rel="alternate" href="https://www.youtube.com/watch?v=ZLyDvABxGF0"/>
```

**Comment by ddmunhoz** [comment]
Hi Frenzie, thanks for the explanation. But I'm still not getting. Should I change anything ? Because the way it is right now its not working.

I subscribed to this https://www.youtube.com/user/marquesbrownlee. But the links come out like this  https://www.youtube.com/v/ZLyDvABxGF0?version=3 which doesn't work.

I mean, I could pull the source code and change that URL to the correct format /watch?=

But before doing so I'm trying to understand if I'm doing something wrong and if there's already a way to make it work.

**Comment by Frenzie** [comment]
The floppy disk icon will only change if YouTube updates their feeds or if you write an extension to change it. But I mean you can just click on the title or on the follow link icon at the top right. Or press space.

**Comment by ddmunhoz** [comment]
Yep, but the problem is that when I'm using Reeder for IOS it only shows the Floppy disk icon. So I guess its time to brush my PHP skills and write something to fix that :)

Thanks for your help on this matter Frenzie!

**Comment by Alkarex** [comment]
I have not read the whole thread, but have you checked one of our YouTube extensions?
https://github.com/FreshRSS/Extensions
