### ISSUE TITLE
Save media files automatically？

### ISSUE THREAD

**Issue by Whichbfj28** [FreshRSS/FreshRSS#3084]
Hope to add a function:
Can automatically save media files (pictures, videos) in the feed to the server

**Comment by aledeg** [comment]
That's a good idea but will probably need a dedicated extension to do that.

**Comment by Whichbfj28** [comment]
If freshrss has this function, it would be perfect

**Comment by Whichbfj28** [comment]
不知道这个功能是否实现

**Comment by math-GH** [comment]
> 不知道这个功能是否实现

The English translation is: "I don't know if this function is implemented" (translated with Google)

**Comment by math-GH** [comment]
This extension https://github.com/Victrid/freshrss-image-cache-plugin could help you with the images.

Videos are quite difficult to download and store.
