### ISSUE TITLE
Docker "unhealthy" after latest container

### ISSUE THREAD

**Issue by alfureu** [FreshRSS/FreshRSS#3085]
I updated FreshRSS with the latest container and it shows as "unhealthy" with the following logs:

```
Result: success
[Sun Jun 28 07:15:40.396977 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
[Sun Jun 28 07:15:40.397108 2020] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
127.0.0.1 - - [28/Jun/2020:07:16:13 +0000] "GET /i/ HTTP/1.0" 200 5706 "-" "-"
127.0.0.1 - - [28/Jun/2020:07:17:05 +0000] "GET /i/ HTTP/1.0" 200 5706 "-" "-"
127.0.0.1 - - [28/Jun/2020:07:17:47 +0000] "GET /i/ HTTP/1.0" 200 5706 "-" "-"
```

Does anybody have a guess what can this be and how to fix it?

**Comment by Frenzie** [comment]
Whether it's "healthy" has to do with the HEALTHCHECK as defined in the Dockerfile. I don't know the specifics but I'm guessing this command took more than 5 seconds or failed in some other manner.
https://github.com/FreshRSS/FreshRSS/blob/27f0b614189c090028dfb9a56d1b21f1adf263d4/Docker/Dockerfile-Alpine#L58-L59

**Comment by Alkarex** [comment]
Hello,
I cannot reproduce the error. Could you please tell on which platform you are running?
Could you please try also with our Alpine image? (we have one image based on Ubuntu, and one based on Alpine)

**Comment by alfureu** [comment]
> Whether it's "healthy" has to do with the HEALTHCHECK as defined in the Dockerfile. I don't know the specifics but I'm guessing this command took more than 5 seconds or failed in some other manner.
> https://github.com/FreshRSS/FreshRSS/blob/27f0b614189c090028dfb9a56d1b21f1adf263d4/Docker/Dockerfile-Alpine#L58-L59

I think you are right with this analysis. After 1h on my NAS the status changed to healthy again. I wonder, whether it is worth changing/removing this healthcheck, as some of us are using the docker container on devices that lack the power of i5 or i7 processors (e.g. NAS, rapsberry). In short: what does the "health" refer to in the case of FRESHRSS docker container?

**Comment by Frenzie** [comment]
I don't think being on a Raspberry Pi means it should take more than a few 100 ms generally speaking (except for complex search queries). But you can override the interval and timeout values in your `docker run` command.

**Comment by Frenzie** [comment]
Health as you can see just means that it checks if it can load the main page. If it takes more than a few 100 ms to send over the main page then normally speaking that would be "unhealthy" even on a Raspberry Pi afaik. On "the power of an i5 or i7" I would expect it to be rather significantly less (think more in the direction of <20 ms). ;-)

**Comment by alfureu** [comment]
IMHO the issue is that the NAS has a 1.4GHz CPU and it has 2x8TB HDDs. So as soon as it starts, it runs all the checks, loads all the apps, then loads all the containers, the containers load their own respective processes. Swapping starts, etc. etc. If I would have SSDs then maybe my results would be below 100ms but this whole things takes longer than that. 

Please note that this is not the scenario when I stop-start the container, I am talking about overall NAS startup. So maybe it is worth to take into consideration in the health check calculation script...

**Comment by Alkarex** [comment]
I have been running that on low-end Raspberry Pi without problem. The timeout being 5 seconds (for just serving the login or default page), it might actually be good to report of status on unhealthy for anything longer than that. My guess is that it has to do with the start period (20s + 3×37s, i.e. over 2 minutes after the start of the container), which might be too short in your case. It would be nice to double-check.
As @Frenzie says, the default HEALTHCHECK can be overriden.

**Comment by alfureu** [comment]
It would be better, if the HEALTCHECK could be turned off as an ENV setting. I use portainer and changing the docker run command is quite difficult there.

**Comment by SuperSandro2000** [comment]
> HEALTCHECK could be turned off as an ENV setting

Just remove it from the docker-compose file or overwrite it with true.

**Comment by alfureu** [comment]
@SuperSandro2000, sure, but this I would need to do every single time I update the container, while I use Portainer and an ENV setting would be set-and-forget

**Comment by SuperSandro2000** [comment]
And it would be feature creep. If you pull a new image you just up or run the old container with the same command you created it initially and then you don't need to do any extra work.

**Comment by Alkarex** [comment]
We should maybe discuss whether we should keep the default `HEALTHCHECK` at all. I do not see many other images using it.
https://docs.docker.com/engine/reference/builder/#healthcheck
As an example of impact, it makes restarting the service slower behind a reverse-proxy such as Traefik, because Traefik will wait for the container to be healthy because rooting requests, which is good in some cases (e.g. multiple instances of the service) but not other (e.g. single instance).

**Comment by Frenzie** [comment]
I wasn't aware of it prior to seeing it used here, but I think the whole HEALTHCHECK concept seems like a pretty good idea. That being said, it might be more important for something like the MySQL/PostgreSQL container than for the FreshRSS one?

> because Traefik will wait for the container to be healthy because rooting requests, which is good in some cases (e.g. multiple instances of the service) but not other (e.g. single instance).

Perhaps that's not an argument against it as much as for making the start period a bit shorter, maybe subsequent intervals too, with a few more retries to keep the overall time similar?

**Comment by Alkarex** [comment]
@Frenzie Ideally, I would like to wait a couple of seconds, then test fast (like every ~2s) until healthy, and then test slowly (like every ~30s), but I do not think the parameters allow such a scheme

**Comment by Frenzie** [comment]
I suppose you could work around it with a script to prevent an entire round trip to the DB, but that does sound awkward.

**Comment by SuperSandro2000** [comment]
I am in favor of removing the default healthcgheck because it makes restarting take so much more time and I did the same with all my containers a while ago because of that.

**Comment by Alkarex** [comment]
@SuperSandro2000 Could you please open a PR for that, and we will finish the discussion / decision there

**Comment by Jucgshu** [comment]
Hi guys,

Just bumped into this problem 2 days ago. I guess I changed something server side, but suddlenly I can't get FreshRSS to run more than 2 hours as it shuts down with the unhealthy tag (Traefik, Swarm).

**Comment by Alkarex** [comment]
Hello,
* Do you have anything in FreshRSS Docker logs which could hint at a problem?
* If you remove the health check, does it then work as intended?

**Comment by Jucgshu** [comment]
The end of the logs goes like this:
```
my-server_freshrss.2.w3js3w8xfxde@my-server.eu    | 127.0.0.1 - - [28/Aug/2020:09:14:33 +0200] "GET /i/ HTTP/1.0" 200 5731 "-" "-"
my-server_freshrss.2.w3js3w8xfxde@my-server.eu    | 127.0.0.1 - - [28/Aug/2020:09:15:10 +0200] "GET /i/ HTTP/1.0" 200 5731 "-" "-"
my-server_freshrss.2.w3js3w8xfxde@my-server.eu    | 127.0.0.1 - - [28/Aug/2020:09:15:48 +0200] "GET /i/ HTTP/1.0" 200 5731 "-" "-"
my-server_freshrss.2.w3js3w8xfxde@my-server.eu    | 127.0.0.1 - - [28/Aug/2020:09:16:25 +0200] "GET /i/ HTTP/1.0" 200 5731 "-" "-"
my-server_freshrss.2.w3js3w8xfxde@my-server.eu    | 127.0.0.1 - - [28/Aug/2020:09:17:03 +0200] "GET /i/ HTTP/1.0" 200 5731 "-" "-"
my-server_freshrss.2.w3js3w8xfxde@my-server.eu    | 127.0.0.1 - - [28/Aug/2020:09:17:40 +0200] "GET /i/ HTTP/1.0" 200 5731 "-" "-"
my-server_freshrss.2.w3js3w8xfxde@my-server.eu    | 127.0.0.1 - - [28/Aug/2020:09:18:18 +0200] "GET /i/ HTTP/1.0" 200 5731 "-" "-"
my-server_freshrss.2.w3js3w8xfxde@my-server.eu    | 127.0.0.1 - - [28/Aug/2020:09:18:55 +0200] "GET /i/ HTTP/1.0" 200 5731 "-" "-"
my-server_freshrss.2.w3js3w8xfxde@my-server.eu    | 127.0.0.1 - - [28/Aug/2020:09:19:33 +0200] "GET /i/ HTTP/1.0" 200 5731 "-" "-"
my-server_freshrss.2.w3js3w8xfxde@my-server.eu    | 127.0.0.1 - - [28/Aug/2020:09:20:10 +0200] "GET /i/ HTTP/1.0" 200 5731 "-" "-"
my-server_freshrss.2.w3js3w8xfxde@my-server.eu    | 127.0.0.1 - - [28/Aug/2020:09:20:52 +0200] "GET /i/ HTTP/1.0" 200 5731 "-" "-"
my-server_freshrss.2.w3js3w8xfxde@my-server.eu    | 127.0.0.1 - - [28/Aug/2020:09:21:34 +0200] "GET /i/ HTTP/1.0" 200 5731 "-" "-"
my-server_freshrss.2.w3js3w8xfxde@my-server.eu    | [Fri Aug 28 09:21:41.307890 2020] [mpm_prefork:notice] [pid 1] AH00169: caught SIGTERM, shutting down
```
Will try to remove the healthcheck tomorrow (can it be done from a compose file? only from the docker file?).

**Comment by Alkarex** [comment]
In Docker Compose, see https://docs.docker.com/compose/compose-file/#healthcheck (section about disabling)
I am curious to hear why it fails though. What database do you use? Is your server sometimes overloaded?
We might just remove the healthcheck from our Dockerfile, see comment higher up, PR welcome https://github.com/FreshRSS/FreshRSS/issues/3085#issuecomment-653760917

**Comment by Jucgshu** [comment]
Db is sqlite. Server is not overloaded (although I will look a bit deeper into that just in case because I didn't have any pb with the healthcheck tag 3 days ago).

Anyway, I ditched the health checks now. I'll keep you posted.

As for removing the tag at all, first I would ask what's the goal of it. If there's a real functional reason, why not keeping it if it can be manually disabled? If there's no real reason (apart from 'it's recommended so you should do it by law', then I agree it should be removed).

**Comment by Alkarex** [comment]
@Jucgshu The idea is to allow e.g. auto-restarting the container in case of problem. However, I have never observed such a need.

**Comment by Jucgshu** [comment]
FreshRSS has not quit unexpectedly for the past 12 hours. Removing the healh check tag worked. Once again, thanks @Alkarex !

**Comment by Alkarex** [comment]
@Jucgshu Could you please send a PR removing the healthcheck?
