### ISSUE TITLE
duplicate key value violates unique constraint "freshrss_user_entry_id_feed_guid_key"

### ISSUE THREAD

**Issue by SuperSandro2000** [FreshRSS/FreshRSS#3086]
I noticed this error while searching for another bug. The feed url belongs to the [chromium blog](https://blog.chromium.org/) which has the feed url https://blog.chromium.org/feeds/posts/default. After a while it changes to ``https://www.blogger.com/feeds/2471378914199150966/posts/default`` for some reason.

This might also be related to some strange behavior I found with the actualize button. I have the cron on a 5 minute interval but everytime I use the actualize button on the web all my feeds get updated even if I run the script manually before.

```
2020-06-27 15:50:41.333 CEST [278775] ERROR:  duplicate key value violates unique constraint "freshrss_user_entry_id_feed_guid_key"
2020-06-27 15:50:41.333 CEST [278775] DETAIL:  Key (id_feed, guid)=(88, tag:github.com,2008:PushEvent/12751781620) already exists.
2020-06-27 15:50:41.333 CEST [278775] CONTEXT:  SQL statement "INSERT INTO "freshrss_user_entry"
                        (id, guid, title, author, content, link, date, "lastSeen", hash, is_read, is_favorite, id_feed, tags)
                        (SELECT rank + row_number() OVER(ORDER BY date) AS id, guid, title, author, content,
                                link, date, "lastSeen", hash, is_read, is_favorite, id_feed, tags
                                FROM "freshrss_user_entrytmp" AS etmp
                                WHERE NOT EXISTS (
                                        SELECT 1 FROM "freshrss_user_entry" AS ereal
                                        WHERE (etmp.id = ereal.id) OR (etmp.id_feed = ereal.id_feed AND etmp.guid = ereal.guid))
                                ORDER BY date)"
        PL/pgSQL function inline_code_block line 6 at SQL statement
2020-06-27 15:50:41.333 CEST [278775] STATEMENT:  DO $$
        DECLARE
        maxrank bigint := (SELECT MAX(id) FROM "freshrss_user_entrytmp");
        rank bigint := (SELECT maxrank - COUNT(*) FROM "freshrss_user_entrytmp");
        BEGIN
                INSERT INTO "freshrss_user_entry"
                        (id, guid, title, author, content, link, date, "lastSeen", hash, is_read, is_favorite, id_feed, tags)
                        (SELECT rank + row_number() OVER(ORDER BY date) AS id, guid, title, author, content,
                                link, date, "lastSeen", hash, is_read, is_favorite, id_feed, tags
                                FROM "freshrss_user_entrytmp" AS etmp
                                WHERE NOT EXISTS (
                                        SELECT 1 FROM "freshrss_user_entry" AS ereal
                                        WHERE (etmp.id = ereal.id) OR (etmp.id_feed = ereal.id_feed AND etmp.guid = ereal.guid))
                                ORDER BY date);
                DELETE FROM "freshrss_user_entrytmp" WHERE id <= maxrank;
        END $$;
2020-06-27 15:50:41.335 CEST [278775] ERROR:  current transaction is aborted, commands ignored until end of transaction block
2020-06-27 15:50:41.335 CEST [278775] STATEMENT:  UPDATE "freshrss_user_feed" SET "cache_nbEntries"=(SELECT COUNT(e1.id) FROM "freshrss_user_entry" e1 WHERE e1.id_feed="freshrss_user_feed".id),"cache_nbUnreads"=(SELECT COUNT(e2.id) FROM "freshrss_user_entry" e2 WHERE e2.id_feed="freshrss_user_feed".id AND e2.is_read=0)
2020-06-27 21:05:12.161 CEST [280693] ERROR:  duplicate key value violates unique constraint "freshrss_user_feed_url_key"
2020-06-27 21:05:12.161 CEST [280693] DETAIL:  Key (url)=(https://www.blogger.com/feeds/2471378914199150966/posts/default) already exists.
2020-06-27 21:05:12.161 CEST [280693] STATEMENT:  UPDATE "freshrss_user_feed" SET "url"=$1 WHERE id=$2
```

**Comment by Frenzie** [comment]
That's what it says its canonical URL is.
```xml
<link rel='self' type='application/atom+xml' href='https://www.blogger.com/feeds/2471378914199150966/posts/default'/>
```

**Comment by SuperSandro2000** [comment]
Can I turn that off? I do not wish for feeds to auto change their links.

**Comment by Frenzie** [comment]
See discussion in https://github.com/FreshRSS/FreshRSS/issues/2654#issuecomment-554522657 (and above)

**Comment by SuperSandro2000** [comment]
Thanks. The postgres error still persists.

**Comment by lukasleitsch** [comment]
I have the same or a similar error. In the logs the following messages appear:

```
SQL error markRead 1: ERROR: duplicate key value violates unique constraint "freshrss_lukas_entry_id_feed_guid_key"
```

Docker-Image: freshrss/freshrss:latest
FreshRSS-Version: 1.17.1-dev
Postgres-Docker-Image: postgres:13-alpine

When this error appears I'm clean up the duplications manual in the database. With this command I find the entries with the duplicated guid.

```mysql
SELECT guid, count(guid) from freshrss_lukas_entry GROUP BY guid HAVING count(guid) > 1;
```

After the cleanup everything works great and the entries disappears in the clients and in the web interface. After a while the duplications came back. As far as I can see it's the same duplication that I removed before. It seems that Fresh RSS fetching already exiting entries again and add it to the database. These duplications appear in the web interface but I can't remove them and the duplicate key value error appears.

How can I help to debug this error?

**Comment by Alkarex** [comment]
@lukasleitsch Thanks for the bug report. Could you please post some examples of entries with duplicated guids?

It is most likely related to the original bug report, but I am surprised by the `SQL error markRead 1` which is triggered when an article is marked as read/unread and should not trigger uniqueness constraints:

https://github.com/FreshRSS/FreshRSS/blob/886b8e484ce7d580fa7ad416a643630b9c21ecd1/app/Models/EntryDAOSQLite.php#L121-L130

Did you run with PostgreSQL 12 before?

**Comment by lukasleitsch** [comment]
> Could you please post some examples of entries with duplicated guids?

I'll give you an update if the duplications appears again. Currently, I removed it from the database.

> Did you run with PostgreSQL 12 before?

Yes, I updated from PostgresSQL 12 to PostgresSQL 13 some weeks ago. And yes this could be the start of the duplications  issue.

**Comment by lukasleitsch** [comment]
I exported my data to a SQLite file with the [CLI](https://github.com/FreshRSS/FreshRSS/tree/master/cli/), purge the Postgres Database and import the data from the SQLite file.

My duplication issue have not occurred for a week. Seems that this way solves my issue.
