### ISSUE TITLE
Monitor keyword and trigger webhook, api workarounds

### ISSUE THREAD

**Issue by Coriakin** [FreshRSS/FreshRSS#3090]
Hi!

So I am moving away from Inoreader to FreshRSS since it seems to work really well and I prefer self hosting these things.

What I want to do is to monitor items, and if they contain a certain key then I want to trigger some action. Perhaps a webhook which could do all sorts of things, send me an email, call some other api in turn etc etc.

I presume I could accomplish this using the API and some small helper script/application that I run periodically to check new items.

I am trying to fetch only items newer than a certain timestamp, as written about here: https://blog.martindoms.com/2009/10/16/using-the-google-reader-api-part-2#feed

But I get nothing back from the call, I am thinking if FreshRSS even implements this feature. If so would someone mind posting a curl-snippet?

Thanks in advance!

**Comment by Frenzie** [comment]
I believe that's implemented. To be clear, you've tested "simpler" API calls?

There are some samples around here: https://github.com/FreshRSS/FreshRSS/issues/1754#issuecomment-353861376 (Or perhaps rather https://freshrss.github.io/FreshRSS/en/users/06_Mobile_access.html)

**Comment by Coriakin** [comment]
Sorry guys, I'm an idiot. I should not do these things if I'm tired.
The API does indeed support "ot", and even sorting e.g. 

`api/0/stream/contents/reading-list?r=d&n=10&ot=1593511486`

I do not know how but a hidden character had snuck onto my terminal line.

Thank you Frenzie!
