### ISSUE TITLE
Question regarding the html5 notification

### ISSUE THREAD

**Issue by Offerel** [FreshRSS/FreshRSS#3091]
This has nothing directly to do with FreshRSS, nor is it a FreshRSS issue. But hopefully someone here can help me.

Currently i try to implement push notifications in my own app (https://github.com/Offerel/SyncMarks). It's in its earlier steps, but i can't get it to work the way i want. The code isn't online right now. The main problem is, that i can click the incoming push notification and it opens the url in a new tab in Chrome as expected. However, if i do not click the notification, it is send to the Windows 10 Action Center automatically, like the notification in FreshRSS also. 

If i click now the notification in the Windows 10 Action Center using the notification from FreshRSS, it open the FreshRSS page as expected. But not so with my notification. It goes only away and no page is opened. It opens in my case only, when i click the notification, before it goes to the Action Center.

Any idea whats wrong with my implementation?

Here is my current code so far:

```javascript
self.addEventListener("push", function(event) {
  if (event.data) {
    showLocalNotification('Title for notification', event.data.text(),  self.registration);
  } else {
    console.log("Error: Wrong data");
  }
});

const showLocalNotification = (title, body, swRegistration) => {
	const options = {
		body,
		icon: './images/bookmarks.ico',
		tag: 'SyncMarks',
		renotify: false
	};
	swRegistration.showNotification(title, options);
};

self.addEventListener('notificationclick', function(event) {
	console.log('On notification click: ', event.notification);
	event.notification.close();
	clients.openWindow(event.notification.body);
});
```

**Comment by Alkarex** [comment]
The FreshRSS code is the following:
https://github.com/FreshRSS/FreshRSS/blob/d7d39f07368379e7ef1619e52cc50c0920ce8351/p/scripts/main.js#L1304-L1350

Have you tried the `onclick` event?

**Comment by Offerel** [comment]
after some investigation, i found that this issue is plaguing user in windows 10 a long time. It seems to be a Windows issue, not a browser or API issue. There are rumors that this is fixed in the may 2020 update, but i cant confirm this. there are 2 workarounds for now, either turn off the WIndows Action Center notifications and enable legacy notifications in Chrome or sending the push 2 time with the same tag, because if there are multiple pushes with the same tag (at least 2), the latest one opens the tab/page.

I will try to send the push 2 times, hopefully this will fix the issue. Many thx for trying to help. Hopefully i can commit the changes in my project the next days.
