### ISSUE TITLE
Unknown error for feed if using password

### ISSUE THREAD

**Issue by JosephDeFazio** [FreshRSS/FreshRSS#3097]
I use RSS-Bridge for creating some RSS feeds and I have it behind an htpasswd. When I try to add the feed to FreshRSS with the login details, I receive "Unknown error for feed" in the log. If I enter the wrong password, it gives "401 Unauthorized" as it should, so it seems login is working correctly.

However, if I disable htpasswd on the site so that no password is required to access it, I am able to successfully add the feed to FreshRSS - no errors. The issue is only occurring when using a password.

**Comment by Alkarex** [comment]
To avoid cache issues while developing, use various versions like `https://rss-bridge.example.net/?action=display&bridge=Example&format=Atom&2` , `https://rss-bridge.example.net/?action=display&bridge=Example&format=Atom&3`

**Comment by JosephDeFazio** [comment]
> To avoid cache issues while developing, use various versions like `https://rss-bridge.example.net/?action=display&bridge=Example&format=Atom&2` , `https://rss-bridge.example.net/?action=display&bridge=Example&format=Atom&3`

If the rss-bridge has an htpasswd, I still get the "unknown error for feed" message with &2/3 added to the feed URL.

**Comment by Alkarex** [comment]
Would you have the possibility of [sending me](https://alexandre.alapetite.fr/cv/) a test RSS from your RSS Bridge?

**Comment by Alkarex** [comment]
@iGeekFace Could you please try this patch? https://github.com/FreshRSS/FreshRSS/pull/3098
Which version of FreshRSS are you using?

**Comment by JosephDeFazio** [comment]
@Alkarex Yup, it's working. Thanks!

**Comment by JosephDeFazio** [comment]
@Alkarex it seems that it's broken when adding login details to an existing feed. It only works when adding a new feed. Also, when adding a new feed, the password field has a space character as the default value instead of it being empty, so the password will be incorrect if the user doesn't first delete the space.

**Comment by Alkarex** [comment]
@iGeekFace Thanks for the feedback. I will look into it. The space was in fact on purpose, to prevent aggressive non-standard password auto-completion in some browsers, which generated lots of trouble, but the situation might have improved, so we need to double-check (I was also considering trimming the password for blanks).

**Comment by Alkarex** [comment]
@iGeekFace I cannot reproduce any problem changing the password of an existing feed. Could you please try again, and if there is still a problem, provide a few more details about your current version and flow?
