### ISSUE TITLE
I cannot find "SQLite" selection during installation.

### ISSUE THREAD

**Issue by MoegiMugi** [FreshRSS/FreshRSS#3101]
Hi, I managed to launch FreshRSS, but I cannot find "SQLite" selection during installation step 2 on the browser. 
![Screenshot from 2020-07-07 22-22-30](https://user-images.githubusercontent.com/47764745/86788324-00912000-c0a1-11ea-8d10-960bbca1a718.png)
How should I do??

**Comment by Alkarex** [comment]
It is probably that you are lacking the `php-sqlite3` package, or its equivalent on your platform. Which OS are you using?
See example of packages for Debian / Ubuntu
https://github.com/FreshRSS/FreshRSS/blob/3f9518b377c88ec4ce8fe538975f26b361e3dd65/Docker/Dockerfile#L11-L12

**Comment by MoegiMugi** [comment]
My environment is Ubuntu 18.04 LTS CLI (on VPS) and not using Docker.
Required packages are all installed.

**Comment by Frenzie** [comment]
If you create a php file with `phpinfo() ` in it you can load it up in a browser and see if the extension's loaded.

**Comment by MoegiMugi** [comment]
It seems I've loaded it up.

> ubuntu@ubuntu /u/share> php -m
> [PHP Modules]
> calendar
> Core
> ctype
> curl
> date
> dom
> exif
> fileinfo
> filter
> ftp
> gd
> gettext
> gmp
> hash
> iconv
> imagick
> intl
> json
> libxml
> mbstring
> mysqli
> mysqlnd
> openssl
> pcntl
> pcre
> PDO
> pdo_mysql
> pdo_pgsql
> pdo_sqlite
> pgsql
> Phar
> posix
> readline
> Reflection
> session
> shmop
> SimpleXML
> sockets
> sodium
> SPL
> sqlite3
> standard
> sysvmsg
> sysvsem
> sysvshm
> tidy
> tokenizer
> wddx
> xml
> xmlreader
> xmlwriter
> xsl
> Zend OPcache
> zip
> zlib

**Comment by MoegiMugi** [comment]
It seems I've loaded it up.

> ubuntu@ubuntu /u/share> php -m
> [PHP Modules]
> calendar
> Core
> ctype
> curl
> date
> dom
> exif
> fileinfo
> filter
> ftp
> gd
> gettext
> gmp
> hash
> iconv
> imagick
> intl
> json
> libxml
> mbstring
> mysqli
> mysqlnd
> openssl
> pcntl
> pcre
> PDO
> pdo_mysql
> pdo_pgsql
> pdo_sqlite
> pgsql
> Phar
> posix
> readline
> Reflection
> session
> shmop
> SimpleXML
> sockets
> sodium
> SPL
> sqlite3
> standard
> sysvmsg
> sysvsem
> sysvshm
> tidy
> tokenizer
> wddx
> xml
> xmlreader
> xmlwriter
> xsl
> Zend OPcache
> zip
> zlib

**Comment by MoegiMugi** [comment]
Well, I'm not sure why, but after restarting apache2, I could choose SQLite!!
Thank You!!!
