### ISSUE TITLE
docker: freshrss install wizard ends with error about do-install.txt

### ISSUE THREAD

**Issue by Germs2004** [FreshRSS/FreshRSS#3104]
I'm a new user, trying out FreshRSS.  I installed using the official [docker-compose.yml](https://github.com/FreshRSS/FreshRSS/blob/master/Docker/docker-compose.yml) file.  The FreshRSS install wizard started with some health checks, and everything passed.  After entering my database connection info, the wizard went to a page that said:

"Blast! Something went wrong; you must delete the file /var/www/FreshRSS/data/do-install.txt manually."

Ideally, the official docker version of FreshRSS should have the permissions and things configured automatically to avoid this error and extra manual step.

**Comment by 360fun** [comment]
same with a normal install:
![image](https://user-images.githubusercontent.com/844090/87332860-8ea35580-c53c-11ea-8089-e813e6673793.png)

**Comment by Alkarex** [comment]
Hello,
Especially when new to FreshRSS, please favour our official releases, e.g. `1.16.2` at the moment, both for Docker and for more manual install https://github.com/FreshRSS/FreshRSS/releases

But thank you for testing the development version / rolling release. I am looking into it.

**Comment by Alkarex** [comment]
I can confirm the bug in the development branch (`:latest` on Docker Hub) but it works fine with our newest release (`:1.16.2`)

**Comment by 360fun** [comment]
oh...just realised that I'm on dev 🙄 how can I change the channel without reinstalling it?

**Comment by Alkarex** [comment]
@marienfressinaud This seems to be a regression due to https://github.com/FreshRSS/FreshRSS/pull/2760 Could you please have a look?

**Comment by Alkarex** [comment]
@360fun How did you install? Docker, git, ZIP...

**Comment by Alkarex** [comment]
@Germs2004 For now, you can edit the `docker-compose.yml` compose file with something like:

```yaml
...
  freshrss:
    image: freshrss/freshrss:1.16.2
...
```

**Comment by Germs2004** [comment]
Thank you.  I just fixed it manually with the below command, but I wanted to let you know about the issue so you could fix it in the official image for everyone.

`docker run -it --rm -v freshrss_freshrss_data:/vol busybox rm /vol/do-install.txt`

**Comment by Alkarex** [comment]
Yes, thanks for the feedback @Germs2004 👍

**Comment by Germs2004** [comment]
> I can confirm the bug in the development branch (`:latest` on Docker Hub) but it works fine with our newest release (`:1.16.2`)

May I share a tip I noticed from other dockerhub projects?  They have a "latest" tag, which is the most recent **tested** release.  They also offer a "dev" tag, which is the latest alpha release or daily build.  Making your "latest" tag work this way lets us safely automate the updates of our docker containers using WatchTower, so we'll always have your latest tested code.  Thank you!

**Comment by Alkarex** [comment]
Indeed @Germs2004 , we should maybe adopt something like that. Could you please open a new ticker for that?

**Comment by 360fun** [comment]
> @360fun How did you install? Docker, git, ZIP...

I followed [the guide](https://freshrss.github.io/FreshRSS/en/admins/06_LinuxInstall.html), using ** git clone** 🙄  
That's how I've got the "dev" version...but seems you found the problem ;)

**Comment by Alkarex** [comment]
@360fun From the state you are in, you can go back to the latest release 1.16.2 using for instance this command:

```sh
git reset --hard 1.16.2
```

P.S. and to jump forward again to the latest commit:

```sh
git fetch
git reset --hard FETCH_HEAD
```

**Comment by 360fun** [comment]
> @360fun From the state you are in, you can go back to the latest release 1.16.2 using for instance this command:
> 
> ```shell
> git reset --hard 1.16.2
> ```
> 
> P.S. and to jump forward again to the latest commit:
> 
> ```shell
> git fetch
> git reset --hard FETCH_HEAD
> ```

Thank you, I did it:
```
root@host:~# cd /usr/share/FreshRSS/
root@host:/usr/share/FreshRSS# git reset --hard 1.16.2
HEAD is now at 38802f6f Release FreshRSS 1.16.2
root@host:/usr/share/FreshRSS# git fetch
root@host:/usr/share/FreshRSS# git reset --hard FETCH_HEAD
HEAD is now at b7fd6d2d Show feed name inside the article (#3081)
```

when I finished I've got the wizard, so I deleted again the **do-install.txt** to be able to login...but the version is still "dev" :(
![image](https://user-images.githubusercontent.com/844090/87363878-6cc4c580-c572-11ea-88c4-6b4422d9b976.png)

**Comment by marienfressinaud** [comment]
Ok I've found the bug, it was indeed due to the new migration system. We test the value returned by [`setupMigrations()`](https://github.com/FreshRSS/FreshRSS/blob/master/lib/lib_install.php#L130) which is actually `0` because we have no migrations yet and there is nothing to write in the `applied_migrations.txt` file yet.

**Comment by Alkarex** [comment]
@360fun To check your version, please look in the *About* section instead

**Comment by 360fun** [comment]
> @360fun To check your version, please look in the _About_ section instead

same 🤔 

![image](https://user-images.githubusercontent.com/844090/87410881-2cdbfd80-c5c7-11ea-9b03-f9f772901e17.png)

**Comment by Alkarex** [comment]
A, well, sure, you ran a `git reset --hard FETCH_HEAD` apparently, which moves back to the most recent commit.

**Comment by 360fun** [comment]
> A, well, sure, you ran a `git reset --hard FETCH_HEAD` apparently, which moves back to the most recent commit.

I followed the instructions you gave me, what I should do instead?

**Comment by Alkarex** [comment]
@360fun Please see https://github.com/FreshRSS/FreshRSS/issues/3104#issuecomment-657800827
The first part is to go back to a stable release. The second part is to jump forward again to the latest development point :-)

**Comment by 360fun** [comment]
> @360fun Please see [#3104 (comment)](https://github.com/FreshRSS/FreshRSS/issues/3104#issuecomment-657800827)
> The first part is to go back to a stable release. The second part is to jump forward again to the latest development point :-)

Thank you, it's a long time that I don't use git commands 😅  now works! 😸

**Comment by Alkarex** [comment]
No worries :-)

Just for the record, going forward (including to the latest /master) is always fine, while going backwards is not always supported, for instance in case of change of database structure (which has not been the case recently, but happens).

Furthermore, since the latest /master has just been fixed, it is fine to pick the very latest again:

```sh
git fetch
git reset --hard FETCH_HEAD
```

**Comment by marienfressinaud** [comment]
But I would advise you to always stay on the latest stable (`git reset --hard 1.16.2` ) if you don't like surprises (such this one ;))

**Comment by 360fun** [comment]
> But I would advise you to always stay on the latest stable (`git reset --hard 1.16.2` ) if you don't like surprises (such this one ;))

I'll stay on stable and wait the next version on the update system! ;)
