### ISSUE TITLE
REQ: allow specifying db info via env variables in docker-compose

### ISSUE THREAD

**Issue by Germs2004** [FreshRSS/FreshRSS#3105]
It would be convenient if the docker-compose.yml file would automatically configure the freshrss docker image to connect to the postgres database so that the user would not have to enter any database connection info into the FreshRSS installation wizard.  The docker-compose file already lets us specify the database name, username, and password for the "freshrss_postgresql" container, so all the necessary information could be similarly injected into the "freshrss" container, letting docker users skip the database setup page of the wizard.

Example of another project that uses the docker-compose to configure the database settings in the app:
`https://git.tt-rss.org/fox/ttrss-docker-compose/src/master/docker-compose.yml`.  Notice how each container that requires database access has environment variables for the db username and password.  It should also have a variable for the database hostname in case the user wants to use a different database hostname.

**Comment by Alkarex** [comment]
Hello,
This could be achieved thanks to [our CLI](https://github.com/FreshRSS/FreshRSS/blob/master/cli/README.md) (command line interface API).
Something like:

```sh
docker exec -it --user apache freshrss_dev ./cli/do-install.php --default_user freshrss --environment development --language fr --api_enabled --db-type pgsql --db-host postgres --db-user freshrss_user --db-password freshrss_pass --db-base freshrss_db
```

Default passwords are dangerous though, so at least a minimum should be edited, or a random password generated / asked

**Comment by Alkarex** [comment]
See an implementation in https://github.com/FreshRSS/FreshRSS/pull/3353
