### ISSUE TITLE
REQ: add tooltips and highlighting to clickable elements

### ISSUE THREAD

**Issue by Germs2004** [FreshRSS/FreshRSS#3111]
I'm trying out FreshRSS for the first time and found a small rough edge while testing.

All these elements in the screenshot below are clickable, but it's not intuitive what they do.  The top nav-menu has tooltips for its buttons already, but please consider adding tooltips for these other clickable icons and buttons that describe what they do if we click them.

![image](https://user-images.githubusercontent.com/5519340/87358142-32880380-c533-11ea-91a3-e380c6fc5e35.png)

It would also be nice if there were hover-over effects that highlight any clickable elements that the cursor is over.  You have nice highlighting in the sidebar on the left, but not on the icons in the article headers.  Highlighting the icons helps reinforce to the user that the element is actionable/clickable.

Thank you!

**Comment by Alkarex** [comment]
@aledeg 's work https://github.com/FreshRSS/FreshRSS/pull/3115 is addressing a part of it. Maybe we should have a CSS `:hover` rule as well?

**Comment by math-GH** [comment]
As I see the tooltips are implemented. 
The highlighting is part of the theme.
Which theme should be imroved (beside Origine theme)?

**Comment by Frenzie** [comment]
Seems fine to me.
