### ISSUE TITLE
(Docker) Create a theme ?

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#3119]
Hello,

I searched on Docker on all folders, but I didn't found Themes folder to create my theme. Is it inclueded in Docker version ?

![image](https://user-images.githubusercontent.com/206181/87589220-33609700-c6e5-11ea-9785-e1cc90c6e201.png)

![image](https://user-images.githubusercontent.com/206181/87589249-39ef0e80-c6e5-11ea-8132-4180559a07b3.png)

Thank you

**Comment by aledeg** [comment]
Themes are located in ```p/themes```

**Comment by ghost** [comment]
I use the Linuxserve image: https://hub.docker.com/r/linuxserver/freshrss
I'll try with the official docker image.

**Comment by ghost** [comment]
Same with the official image, I can't access to the themes folder

On the docker version /p/ seems not exposed (left: local / right : docker) : 

![image](https://user-images.githubusercontent.com/206181/87873915-b32c8100-c9c5-11ea-80bd-f647b39ee56f.png)

**Comment by Alkarex** [comment]
In your Docker run command, or docker-compose, you can mount your folder theme with something like:

```
...
  -v /home/you/my-theme/:/var/www/FreshRSS/p/themes/my-theme/
...
```

The left side being the path to the folder on your machine with your theme.
