### ISSUE TITLE
PubSubHubbub

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#312]
Considérer ajouter le support du protocole PubSubHubbub pour récupérer et/ou diffuser les flux.
http://code.google.com/p/pubsubhubbub/
http://en.wikipedia.org/wiki/PubSubHubbub

**Comment by olafleur** [comment]
Cela semble intéressant : l'objectif est que le serveur FreshRSS soit automatiquement notifié lorsqu'un fil RSS est mis à jour? (je ne suis pas sur de comprendre l'aspect diffusion @Alkarex )

Si je comprends bien, on pourrait utiliser le code du PHP subscriber que tu as mis, puisqu'il est sous licence Apache 2, right?

Bref, si vous considérez que cette feature est souhaitable, je me lancerais bien là-dessus à temps perdu. @marienfressinaud peux-tu confirmer que je peux commencer à travailler sur cette fonctionnalité où tu préférais terminer ton refactoring?

Je ne promets rien, j'explorerai comment ce protocole fonctionne, en même temps. ;-)

**Comment by marienfressinaud** [comment]
@olafleur > ce serait effectivement une super idée que de gérer PubSubHubbub ! Ce que tu peux essayer de faire c'est de gérer ça à travers une extension. Il y a un début de doc ici : https://github.com/FreshRSS/documentation/blob/master/fr/02_Documentation_d%C3%A9veloppeurs/03_Backend/05_%C3%89criture_d%27extensions.md et un exemple d'extension là : https://github.com/FreshRSS/xExtension-HelloWorld

Si tu as besoin de plus de choses n'hésite pas, je ne suis pas trop dispo jusqu'à lundi soir mais ça ira mieux après.

**Comment by olafleur** [comment]
Ok, je vais regarder comment les extensions FreshRSS fonctionnent et je me lance là-dedans. Juste pour être sûr : qu'est-ce qui fait la différence entre une fonctionnalité qui est dans une extension et une qui est dans le "core"?

**Comment by olafleur** [comment]
Ah OK, je viens de lire le document explicatif sur les extensions. C'était bien expliqué. ;-)

**Comment by olafleur** [comment]
Je ne connais pas beaucoup PubSubHubbub, mais il me semble que ce pourrait être intéressant d'avoir cette fonctionnalité dans le "core", non? De ce que je comprends, ça ne fait que recevoir les nouveaux articles plus rapidement lorsque c'est implémenté dans le blog. Bref, qui ne voudrait pas ça? Les gens qui ne voudraient pas qu'il y ait trop souvent des requêtes?

Anyway, je regarde tout ça dans les prochains jours. ;-)

**Comment by marienfressinaud** [comment]
Oui, tellement intéressant que ce serait bien de pouvoir l'ajouter aussi dans les versions de FRSS qui sont déjà sorties :). Si l'extension fonctionne bien il est très probable qu'elle soit intégrée dans le cœur de FRSS donc pas de soucis. Il suffira d'ajouter une option pour désactiver PubSubHubbub pour ceux qui n'en veulent pas ;).

**Comment by olafleur** [comment]
Ok, super!

**Comment by julien51** [comment]
@olafleur Ca ne fait pas plus de requetes (même moins)... en fait c'est un systeme de webhook. Dès que le flux est mise à jour, une request POST est envoyé au lecteur de flux...

**Comment by marienfressinaud** [comment]
Merci @julien51 d'avoir posté ici, ça m'a fait tomber sur le blog de Superfeedr et sur ton article [à propos de PubSubHubbub](http://blog.superfeedr.com/howto-pubsubhubbub/). Ça pourrait aider @olafleur :). J'ai cherché ce genre d'info pendant un moment !

**Comment by julien51** [comment]
De rien! Merci à vous de produire @FreshRSS! On a besoin de plus de feed readers :)

**Comment by Alkarex** [comment]
@julien51 Je commence à regarder l'ajout de PubSubHubbub dans FreshRSS ~~avec la librairie https://github.com/pfefferle/php-pubsubhubbub~~
Commentaires bienvenus (genre compatibilité avec SuperFeedr).

**Comment by Alkarex** [comment]
I am glad to announce a [branch for testing PubSubHubbub](https://github.com/Alkarex/FreshRSS/tree/PubSubHubbub), and the associated pull-request https://github.com/FreshRSS/FreshRSS/pull/831 :-)

To recap, this standard protocol allows receiving instant push notifications for new articles of compatible feeds.

For this early testing, there is a [protection based on a white list](https://github.com/Alkarex/FreshRSS/blob/18831a89efadf8a05fcc3285fa6af0051e41df2b/app/Controllers/feedController.php#L428), currently only accepting the test service http://push-pub.appspot.com. You are welcome to manually add more URLs to the list, which will be removed as soon as we have verified that we are good PubSubHubbub citizens :-P

This version does not make any change to the database and is only using the file-system. This may change in the future depending on the feedback and the needs.

This implementation of PubSubHubbub is multi-user. The same push notification is visible by all users who are subscribed to this feed.

How to test:
- Back-up your data.
- First, update to the latest /dev branch and check that things are working.
- ~~Then, use the experimental PubSubHubbub branch:~~ (Now available in /dev branch)
- Set your environment to `development` in your [data/config.php](https://github.com/Alkarex/FreshRSS/blob/18831a89efadf8a05fcc3285fa6af0051e41df2b/data/config.default.php#L9) to get more messages in your logs.
- Specify your `base_url` in your [data/config.php](https://github.com/Alkarex/FreshRSS/blob/18831a89efadf8a05fcc3285fa6af0051e41df2b/data/config.default.php#L19). This is needed to build the callback URL. It needs to be a publicly accessible IP/URL. E.g. https://example.net/FreshRSS/p/
- Add http://push-pub.appspot.com/feed to your feeds.
- (Optional) Delete `data/cache/6834e65457c5654e1bdbdba44be8079c.spc` to remove the SimplePie cache and being able to refresh immediately. Or wait 20 minutes.
- Refresh this http://push-pub.appspot.com feed (the PubSubHubbub logic is currently only when refreshing feeds, not yet when adding them).
- In the FreshRSS logs of your user account, you should get various messages, as well as in `data/users/_/log_pshb.txt`.
- Add some entries on http://push-pub.appspot.com/
- The new entries should be received near-instantly by FreshRSS. You have to wait up to three minutes to receive an HTML5 notification and see them in the Web interface of FreshRSS, or just click anywhere in FreshRSS to see them appear.

Happy testing, and I am looking forward to your feedback!

**Comment by julien51** [comment]
+1! Thanks @Alkarex

**Comment by Alkarex** [comment]
There is apparently a problem with the feed http://rss.slashdot.org/Slashdot/slashdot, which uses the hub http://pubsubhubbub.appspot.com/ . I receive a "204" status code during the subscription, which is fine, but then never receive any post.

Edit: According to https://pubsubhubbub.appspot.com/topic-details?hub.url=http://rss.slashdot.org/Slashdot/slashdot , there has not been any ping since 2013... We will need a way to detect such bad feeds... :-/

Edit 2: Even worse with http://rss.slashdot.org/slashdot/slashdotMain , for which appspot returns a 204 although nothing is to be found there https://pubsubhubbub.appspot.com/topic-details?hub.url=http://rss.slashdot.org/slashdot/slashdotMain

**Comment by Alkarex** [comment]
Given the example of broken push above, I now assume that push is not working, until we receive the first successful push notification https://github.com/Alkarex/FreshRSS/commit/001c713f030d51b74a860e20014153c6b4d9661f and as soon as we discover by pull an article that was not received by push, we assume again that push is not working until the reception of the next successful push notification.

**Comment by julien51** [comment]
@Alkarex That's a fair approach. Some publishers do indeed "forget" to implement the ping part of the protocol.

**Comment by Alkarex** [comment]
The PubSubHubbub code is now merged in /dev to start testing towards the next FreshRSS version 1.1.2 due in about one month. Please create new issues referring to this one for new bugs/features.
