### ISSUE TITLE
Cannot authenticate with fever API

### ISSUE THREAD

**Issue by ctechols** [FreshRSS/FreshRSS#3123]
I'm using the freshRSS docker image of version 1.16.2
Everything is green on the "Installation Checking" page.
I've enabled the Mobile API and set an API password.
The /api/ screen reports 'PASS' for both greader and fever APIs
I've successfully used the FeedMe android app to download my feeds (using the FreshRSS menu option).

I've been trying (and failing) to configure a fever based client to talk to freshRSS (It's a combination of elfeed and elfeed-protocol under emacs).

I was following the instructions on [this page](https://freshrss.github.io/FreshRSS/en/users/06_Fever_API.html) to diagnose the fever API.  When I use postman to POST to /api/fever.php?api, I get the correct response.  However, when I include the api_key form data with the hashed <username>:<password> combo,  it does not inclued the `"auth": 1` or `last_refreshed_on_time` fields in the response.

I've looked in <data dir>/users/_log_api.txt and the only relevant log messages are:
`Fever API: wrong credentials! <md5sum>`

I've changed my api password several times, and I still get the same message.

**Comment by ctechols** [comment]
I just discovered <data_dir>/users/<username>/config.php.

The desired user does have a feverKey property, but it's value is *not* what I get when I run
$ echo <username>:<password> | md5sum

If I grab feverKey's value from config.php, and use it as postman's api_key value, I can authenticate successfully.

**Comment by Alkarex** [comment]
Please try:

```php
<?php
echo md5('you:password'), "\n";
```

**Comment by Alkarex** [comment]
Or

```sh
php -r 'echo md5("you:password"), "\n";'
```

**Comment by Alkarex** [comment]
It is supposed to give the same output though. But mind the new lines / white spaces:

```
$ echo -n 'you:password' | md5sum
a3df5790fe75b096f2b016cb2ad825c7-

$ php -r 'echo md5("you:password"), "\n";'
a3df5790fe75b096f2b016cb2ad825c7 
```

**Comment by ctechols** [comment]
Ugh.  I was leaving off the '-n' from echo.  You can't imagine how many times I read the instructions and did not catch that.

Sorry for the false alarm, and thank you for your help :)
