### ISSUE TITLE
Deleting several feeds at the same time.

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#3127]
Hi! 
It seems that it is not yet possible to delete several feeds at the same time. Does anyone plans to implement this soon? 
Thanks!

**Comment by Alkarex** [comment]
Hello,
This is not possible at the moment from the Web interface. It is possible through the API though.
Contributions welcome

**Comment by ghost** [comment]
Thanks, could you please explain how I can do it with the API? I would like to delete these feeds from the command line.

**Comment by Alkarex** [comment]
For the API, see e.g. the following (same Google Reader API than what FreshRSS implements):
* https://www.inoreader.com/developers/edit-subscription
* https://feedhq.readthedocs.io/en/latest/api/reference.html#subscription-edit

Furthermore, it is possible to remove all the feeds of a given category from FreshRSS Web interface.
