### ISSUE TITLE
Responsive is broken with a table inside a feed (a global scroll bar appears)

### ISSUE THREAD

**Issue by Massedil** [FreshRSS/FreshRSS#3129]
**Reproduce :**

Subscribe to : 
https://btrfs.wiki.kernel.org/index.php?title=Special:RecentChanges&feed=atom

Look a the "24 juillet 2020 à 14:21" article.

|---|---|
|---|---|
![](https://user-images.githubusercontent.com/20357783/88554936-68df7b80-d027-11ea-97d1-45033e9ca40a.png) | ![](https://user-images.githubusercontent.com/20357783/88555368-05098280-d028-11ea-8d1d-6d64616c9680.png)

**Expected :**

The `<table>` is inside a `overflow: auto;` element. Maybe the `<div class="text">` enclosing the `<table>` element can take the `overflow: auto;` CSS property.

![](https://user-images.githubusercontent.com/20357783/88555701-6c273700-d028-11ea-8c48-043cc2e46715.png)

**Comment by Alkarex** [comment]
PR welcome
