### ISSUE TITLE
Article Previews [Idea]

### ISSUE THREAD

**Issue by SZanlongo** [FreshRSS/FreshRSS#3135]
Would it be possible to have a display mode similar to Feedly where the header image and first few lines of text are visible (but not the whole article)? Reading mode displays the entire article, and also hides the sidebar which is not ideal.

**Comment by PAHXO** [comment]
I'm working on this view. Let me know if you're interested.
![Screenshot 2021-01-11 191149](https://user-images.githubusercontent.com/9639436/104206746-f6315380-5440-11eb-817d-037e3a1a8c63.jpg)

But it has a drawback it is so adjusted to my liking. Also, I have an RTL interface.

**Comment by Frenzie** [comment]
I'm not sure if rtlcss can do the RTL to LTR automatically. It might need manual porting to LTR. :-/ (Luckily, it shouldn't be too many lines?)

https://github.com/FreshRSS/FreshRSS/blob/6e610e501d10776d117f7e40225d6f083a6f71b1/Makefile#L160-L162

**Comment by PAHXO** [comment]
#3360

**Comment by aledeg** [comment]
Linked to #2038

**Comment by math-GH** [comment]
Should be done with #3805, is not it?
