### ISSUE TITLE
Trying to get property 'language' of non-object in /rss/app/FreshRSS.php on line 94

### ISSUE THREAD

**Issue by ZoomStop** [FreshRSS/FreshRSS#3136]
Tried everything I can think of before opening an issue. Previously working installation for a number of months suddenly started giving `Error 403 - Forbidden` and `You don’t have permission to access this page [HTTP_REFERER=https://doman.com:443/]` errors when trying to mark articles as read (and trying to update user settings). 

The webserver (nginx) error log says:
`PHP message: PHP Notice:  Trying to get property 'language' of non-object in /rss/app/FreshRSS.php on line 94`

I've double checked all my file and folder permissions, all looks OK. `checkInstall` shows all green for the checks. Is anyone else having this issue or seen it before?

**Comment by ZoomStop** [comment]
Closing this issue. It appears to have been a cookies or cache issue that resolved itself today.

**Comment by aledeg** [comment]
Thank you for your feedback
