### ISSUE TITLE
When on mobile, article titles are very (too) short because of four icons per line taking up almost half the space available

### ISSUE THREAD

**Issue by 2VRyLXwuPXpvxz7F** [FreshRSS/FreshRSS#3137]
Hi all,

Thanks a lot for FreshRSS. I really like using it to read all my news sources.
However, there is one thing that is bugging me, and I wonder if it is something others have experienced too, or that there is a way to "fix" this already, that I don't yet know about.

When on mobile (Firefox on iPhone), the article titles are really very (too) short because of the four icons per line taking up almost half the space available. I'm talking about the envelope icon, the star icon and the source icon on the left, and then the "world" icon on the far right. I understand why they're there, but still...
I would really like to be able to see more of the article title, and wouldn't mind if there was a way to view the article list with (besides the article titles) just the star icon and the source icon. So that would be a view without the envelope icon and the "world" icon.

Or... Other idea... Leave the icons as they are, but allow for multi line article titles in the mobile view. Maybe that would even better!

Anyone any thoughts on this?

Thanks!

**Comment by Frenzie** [comment]
It'll come eventually, but for the moment you can use this extension https://github.com/FreshRSS/Extensions/tree/ad61438c3d26f312d85c7d9da2668c8816996939/xExtension-TitleWrap

**Comment by 2VRyLXwuPXpvxz7F** [comment]
Brilliant. Absolutely brilliant. Just what I needed. Many thanks from a FreshRSS newbie :)

Solved.

**Comment by ghost** [comment]
To hide some icons when you use your mobile (in addition to Title Wrap extension), you could also use the Custom CSS extension (available here: https://github.com/FreshRSS/Extensions ) and then write something like this:

```
@media (max-width: 840px) 
{
	.flux .website .favicon, .flux_header .item.manage
	{
    		display:none;
	}
}
```

For example, here it is my customized CSS used with the Flat theme:

```
@media (max-width: 840px) 
{
	.flux_header .item.website
	{
		width:20%;
		padding:3px;
	}

	.flux .website .favicon, .flux_header .item.manage
	{
    		display:none;
	}
	
	
	.flux_header .item.website span
	{
		display:inline;
		font-size:0.7rem;
	}
}
```
Hope it helps!

**Comment by aledeg** [comment]
@sotys Would you mind adding a PR for the CSS extension with your example? You could add a description of your use case and how you solve it here -> https://github.com/FreshRSS/Extensions/blob/master/xExtension-CustomCSS/README.md. That would be helpful to others! Thank you.
