### ISSUE TITLE
Limit number of articles to keep per feed

### ISSUE THREAD

**Issue by simondrake** [FreshRSS/FreshRSS#3138]
I'm setting up FreshRSS on my homelab, but I seem to be missing something as I cannot configure it to keep X number of articles per feed. 

I first went to Settings > Archiving and set `Maximum number of articles to keep` to 5 and `Minimum number of articles to keep by feed` to 1.

I then added an RSS feed ([The official Go blog](https://blog.golang.org/feed.atom)), and set the `Purge policy` to default, but it's showing 10 articles. 

If I remove it and set the same options on the feed itself, it still shows 10 articles. 

While not a massive issue for *this* specific RSS feed, some of the ones I want to add have hundreds of articles and I only want the 5 latest. 

Is this not something I can do with FreshRSS?

Note: I'm using the LinuxServer.io docker image with a Postgress DB backend.

**Comment by Alkarex** [comment]
Hello,
It is not possible to keep that few articles, because otherwise older articles still available in the original RSS feed would keep coming back. Furthermore, the maximum number of articles is something that is only enforced as regular automatic maintenance jobs, so you cannot expect to have always precisely that number.
However, depending on what you ultimately want to achieve, other settings could do the job. What is your end goal?

**Comment by simondrake** [comment]
Hi @Alkarex - ultimately, I don't want a flood of articles in my RSS feed (some of the feeds I want to consume have hundreds of articles). 

Ideally I'd just keep the five latest articles. 

Is that possible?

**Comment by rezad1393** [comment]
> Hello,
> It is not possible to keep that few articles, because otherwise older articles still available in the original RSS feed would keep coming back. Furthermore, the maximum number of articles is something that is only enforced as regular automatic maintenance jobs, so you cannot expect to have always precisely that number.
> However, depending on what you ultimately want to achieve, other settings could do the job. What is your end goal?

can you say how many is the minimum that I can put in the  "Maximum number of articles to keep"  and "Minimum number of articles to keep by feed" ?

**Comment by math-GH** [comment]
@simondrake Any news here?

**Comment by Alkarex** [comment]
Was implemented in 1.19.0 with https://github.com/FreshRSS/FreshRSS/pull/3303
Slightly related new option in 1.20.0 https://github.com/FreshRSS/FreshRSS/pull/4426
