### ISSUE TITLE
Strange display | Feed items title list

### ISSUE THREAD

**Issue by siSSSou** [FreshRSS/FreshRSS#3139]
This is how feed titles are displayed :
![Screenshot_2020-08-11 Vos flux RSS · FreshRSS](https://user-images.githubusercontent.com/16271116/89869076-22a42380-dbb4-11ea-88f1-8cebdf9ba144.png)

"**<1m| <1m| <1m|**" or "**1m| 1m| 1m|**" is displayed before the title.
This problem occured right after the install.

FreshRSS version : 1.16.3-dev

**Comment by SuperSandro2000** [comment]
This is a problem with https://framagit.org/Lapineige/FreshRSS_Extension-ReadingTime/ . For me it occurs every time a new block of feeds is loaded.

**Comment by siSSSou** [comment]
You're right, display is OK once this extension disabled !
Thanks !

**Comment by aledeg** [comment]
The third party extension was causing some trouble but does the official one works for you?
Please consider switching extension and opening an issue in https://github.com/FreshRSS/Extensions if you still encounter the problem.
