### ISSUE TITLE
Reeder 4 is not working with FreshRSS

### ISSUE THREAD

**Issue by chemical1979** [FreshRSS/FreshRSS#3143]
I got the information that the otherwise expense app Reeder 4 is available for free today in the Apple App store. https://apps.apple.com/de/app/reeder-4/id1449412357

I am using Reeder 3 with FreshRSS dev and it works perfectly for me since a long time. So I gave Reeder 4 a try, because - why not? Unfortunately, although it is offering "FreshRSS self-hosted" as a default provider config, it is not working correctly. It fetches the names of the feeds, but no contents of the feeds, "Not synced yet" and "No unread items". 

I tried removing and re-adding several times, but it stayed the same. I am unsure if I do something wrong or not, but Reeder 3 is still working perfectly (Reeder 4 installs next to it, it is a different app).

In my apache this error pops up:

`[Fri Aug 14 23:13:33.911690 2020] [php7:error] [pid 7460] [client 192.168.110.118:49642] PHP Fatal error:  Uncaught Error: Call to undefined function gmp_strval() in /usr/share/FreshRSS/p/api/greader.php:36\nStack trace:\n#0 /usr/share/FreshRSS/p/api/greader.php(745): hex2dec('0005acbcf2c6f9d...')\n#1 /usr/share/FreshRSS/p/api/greader.php(1031): streamContentsItems(Array, 'd')\n#2 {main}\n  thrown in /usr/share/FreshRSS/p/api/greader.php on line 36
`

FreshRSS runs on raspbian buster, "Your PHP version (7.3.19-1~deb10u1) is compatible with FreshRSS."

**Comment by chemical1979** [comment]
Fixed by installing a missing module:

`apt install php-gmp`

and restarting apache2.

The installation check was all green before, maybe it is missing the check for this module.  Please consider adding it. Thank you :)

**Comment by Alkarex** [comment]
Thanks for the feedback. GMP is only needed for the API and only for 32-bit platforms, but we could indeed add a check in the global tests.

Currently, the test is performed in the API check, which you can find when browsing to `https://freshrss.example.net/api/`

PR welcome. Example:
https://github.com/FreshRSS/FreshRSS/blob/ee31722072a8b114beaf074193b7a7a6fd65fd30/p/api/greader.php#L137-L139
