### ISSUE TITLE
Traefik cannot pass the cookie

### ISSUE THREAD

**Issue by hanj0415** [FreshRSS/FreshRSS#3145]
I'm using traefik as a reverse proxy, but since FreshRSS is using web form to be authenticated, and traefik cannot pass the cookie to the backend, I always have login failed. If I don't use reverse proxy, I can login.
I'm using google oauth middleware in the traefik, so I don't need the authentication by FreshRSS. If I disable authentication from FreshRSS, I can login but I cannot use API authentication which means I cannot use mobile app such as reeder.
Can I use API authentication without webform authentication enabled?

**Comment by Alkarex** [comment]
Hello,
FreshRSS also supports HTTP Basic Auth.

Could you try to create a file in your `./FreshRSS/p/phpinfo.php` with the following content:

```php
<?php
phpinfo();
```

Access it through your browser via Traefik.

Then, what I am interested in is `REMOTE_USER` or `REDIRECT_REMOTE_USER` or similar, containing your login username from Traefik.

**Comment by math-GH** [comment]
@hanj0415 Any news regarding this ticket?

**Comment by Alkarex** [comment]
There is [now](https://github.com/FreshRSS/FreshRSS/pull/4320) a more detailed documentation for Traefik
https://github.com/FreshRSS/FreshRSS/tree/edge/Docker#use-tr%C3%A6fik-reverse-proxy
