### ISSUE TITLE
Expired certificate error on https://500ish.com/feed

### ISSUE THREAD

**Issue by drewkerr** [FreshRSS/FreshRSS#3146]
This is a medium.com blog so maybe they are doing something weird but the certificate is fine in the browser (October 2020) and it parses on the [SimplePie demo](https://www.simplepie.org/demo/?feed=https%3A%2F%2F500ish.com%2Ffeed). cURL in the Mac Terminal give no complaints. I tried setting 'Verify SSL security' to no. Any ideas?

**Log**
cURL error 60: SSL certificate problem: certificate has expired [https://500ish.com/feed]

**Version**
1.16.2

**Config is all green**

PHP installation
Your PHP version is 7.3.21, which is compatible with FreshRSS.
You have the Minz framework.
You have the cURL library.
You have PDO and at least one of the supported drivers (pdo_mysql, pdo_sqlite, pdo_pgsql).
You have the required library for regular expressions (PCRE).
You have the required library for character type checking (ctype).
You have the fileinfo library.
You have the required library to browse the DOM.
You have JSON extension.
You have the recommended library mbstring for Unicode.
You have ZIP extension.

File installation
Permissions on data directory are good.
Permissions on cache directory are good.
Permissions on users directory are good.
Permissions on favicons directory are good.
Permissions on tokens directory are good.

**Comment by Alkarex** [comment]
Hello,
This feed works for me. Could you try again? Maybe it was just a temporary failure.
For the record, it is going through Cloudflare, which sometimes creates problem (in this case, I get a 307 redirect followed by 302 redirect with a temporary token)

**Comment by drewkerr** [comment]
Yes, it does seem to be intermittent. I changed back to http, set 'Verify SSL security' to no and this time the feed loaded with only these errors in the log:

Error while WebSub subscribing to https://500ish.com/feed
Error while WebSub unsubscribing from http://500ish.com/feed
JSON not found for WebSub: http://500ish.com/feed

Happy to close the issue and chalk it up to Medium being weird.
