### ISSUE TITLE
Youtube Export subscriptions OPML Import does not work.

### ISSUE THREAD

**Issue by Luxtech** [FreshRSS/FreshRSS#3147]
Youtube cancelled there email subscription service the I always used, so I taught I change my Youtube alerts over to FreshRSS.
Youtube has an OPML export option:
https://support.google.com/youtube/answer/6224202?hl=en 

In FreshRSS I tried to import the Youtube OPML export file, but no extra category or feed has been created. 
I cant find any Youtube feed between my existing feeds.

Is this the right way to add Youtube subscription functionality to FreshRSS?
I saw you can add individual channels to FreshRSS but that is not really convenient to add a new feed every time you subscribe to a new channel.

**Comment by Luxtech** [comment]
Fixed,

When you download the export file from Youtube it has no extension.
If you manually add the .opml extension FreshRSS imports the file correctly.

Maybe it is an idea if FreshRSS gives you a warning when importing an file without extension.
The logs where also empty.

**Comment by Alkarex** [comment]
Indeed, good idea, PR welcome
