### ISSUE TITLE
Correct way to use postgresql with self-hosted freshrss

### ISSUE THREAD

**Issue by shrysr** [FreshRSS/FreshRSS#3151]
I am running freshrss with Apache on a self-hosted VPS. I have reached the web setup point of setting up the database. I would like to use postgres as it is available.

I have changed 'type' => 'pgsql' in config.default.php, however, I only have mySQL in the dropdown box.

**Comment by Frenzie** [comment]
Besides the database itself you'll also need the relevant driver for PHP: https://www.php.net/pdo-pgsql

(And restart Apache after installing it.)

**Comment by shrysr** [comment]
Thanks for the quick response. I have enabled extension=pdo_pgsql as well as extension=pgsql in my php.ini and restarted Apache. I still have the same status. Am I missing something?

**Comment by Frenzie** [comment]
See https://github.com/FreshRSS/FreshRSS/issues/3145#issuecomment-675048929 for how to check if it's indeed properly enabled.

**Comment by shrysr** [comment]
I am able to access phpinfo inline with the advice there :  https://rss.ragavan.co/p/phpinfo.php

**Comment by Frenzie** [comment]
It doesn't look like you have the extension loaded. Could it be that you edited the php.ini for command line PHP rather than the one for Apache? It may also be that you'd need to add a `.so` at the end. But I'm also a touch confused: shouldn't installing the `php-pgsql` package on Debian take care of that automatically?

**Comment by shrysr** [comment]
Yes. Sorry - I am quite new to PHP and LAMP. I got some help from IRC and used php-pgsql on debian to use phpenmod and have it enabled now. Thanks very much for your prompt help!

**Comment by Frenzie** [comment]
Btw, don't forget to delete that file. ;-)
