### ISSUE TITLE
Confusing documentation on filter actions → mark an article as read…

### ISSUE THREAD

**Issue by jk** [FreshRSS/FreshRSS#3152]
I've a hard time understanding the filter actions → »mark an atricle as read…« section in the subscription management  of a feed. I've already found https://freshrss.github.io/FreshRSS/en/users/03_Main_view.html - for me that's just targeting the search query in reader/feed view. In that view I'm able to filter with `intitle:'deals'` like the documentation says. Nontheless, when I'm using the same queries in »Mark an article as read…« and wait for new entries that should match, nothings happens. Those entries aren't marked as read.

Can someone spot some light on this feature?

<img width="637" alt="2020-08-19 at 11 43 56 Firefox Subscription management · FreshRSS" src="https://user-images.githubusercontent.com/40043/90619238-46e5ad00-e211-11ea-946d-67d23e1dde3d.png">

**Comment by Alkarex** [comment]
Hum, that should work. Maybe some bug with the special characters. Could you try with some simpler strings?
Could you give an example of feed and the plain text version of your filters?

**Comment by Alkarex** [comment]
P.S. Which version of FreshRSS are you running?

**Comment by mada199122** [comment]
for me the same behaviour...

with this rule in Macrumors feed 

![Screenshot 2021-01-29 at 15 10 30](https://user-images.githubusercontent.com/61902329/106284973-2ac84c00-6244-11eb-988c-9a5903e4ff11.jpg)

I get no automatic read article...
![Screenshot 2021-01-29 at 15 13 12](https://user-images.githubusercontent.com/61902329/106285271-914d6a00-6244-11eb-9717-db858cc3944d.jpg)

if I used it the query as a filter it works so the query is right.

Thanks

I'm using the 1.17.1-dev in docker

**Comment by aledeg** [comment]
The filter is applied when new articles are retrieved. It does not work on articles already in the system.

**Comment by mada199122** [comment]
Ah ok thank you for the clarifications...

**Comment by aledeg** [comment]
I've opened an issue to add maintenance hooks #3398. If it is added, we might be able to apply filters with that type of feature. You could add your voice there!

**Comment by pniewiadowski** [comment]
@aledeg I've seen this has been marge to 1.18.0, how to use it to filter feed after refresh?

**Comment by aledeg** [comment]
@pniewiadowski You will need to create an extension to use that hook and filter the way you want.

**Comment by math-GH** [comment]
Is here work left or could we close this issue?

**Comment by Frenzie** [comment]
It should hopefully be at least a little bit clearer. :sweat:
