### ISSUE TITLE
Items marked as read keep returning

### ISSUE THREAD

**Issue by paulmorabito** [FreshRSS/FreshRSS#3153]
Hi,

I'm relatively new to FreshRSS having moved from another reader. It's absolutely fantastic so a huge thanks to the developers.

The only issue I am noticing is that I regularly mark a feed as read and then after update, the same feed items return as unrea again. This occurs on many feeds so does not seem specific to any single feed. Likewise, there is no errors in the logs or other issues. The mark as read request is confirmed with the notification confirming the action.

I'm using the latest docker image on a Linux host. If there is anything else you need to debug then please let me know.

**Comment by Alkarex** [comment]
Try to disable that option:
![image](https://user-images.githubusercontent.com/1008324/90514798-f400ec80-e161-11ea-9363-3486b4e95a1c.png)

**Comment by Alkarex** [comment]
P.S. There is both a global and a per-feed option

**Comment by paulmorabito** [comment]
Thanks. I've set it at global level and will monitor. I'll re-open if the issue keeps occurring.
