### ISSUE TITLE
Filter feeds - only show portion?

### ISSUE THREAD

**Issue by kaktux** [FreshRSS/FreshRSS#3155]
Hi there,

i am trying to find out if its somehow possible to filter a feed before you get the results in your reader.
e.g. i want to subscribe to a feed about ebikes - but the news source only has only a general feed about all bikes.
So - in the browser the feed shows all articles on "domain.com" - but i only want to read those on "domain.com/ebike".

I found the filter option - but this only seems to filter after already downloading the feeds.
Is this possible?

**Comment by Frenzie** [comment]
I don't think that's possible directly in FreshRSS, but about a decade ago I wrote <https://github.com/RSS-Bridge/rss-bridge/blob/07c71b3b36242e2913eadf1da191edd59edd6048/bridges/FilterBridge.php> (or its predecessor) for that purpose. Support for filtering by item URL would need to be added though.

**Comment by Mte90** [comment]
I was looking for something at the opposite, like ignore all the titles that includes some terms

**Comment by Alkarex** [comment]
It is possible to add rules to automatically mark as read articles that are matching various rules
![image](https://user-images.githubusercontent.com/1008324/184714532-1c628c6f-33ff-4249-94e6-d1554315aee1.png)

**Comment by Mte90** [comment]
Where it is that settings? I am not able to find it...
