### ISSUE TITLE
Google Reader compatible API return 404

### ISSUE THREAD

**Issue by Dryusdan** [FreshRSS/FreshRSS#3156]
Hello

I encounter a problem with my FreshRSS instance.
When I access on `/api`, the "Google Reader compatible API" return a `FAIL: HTTP error 404 Not Found`.

I don't know when it started. I running the latest version : 1.16.3-dev. 
The `/api/greader.php/check/compatibility` URL return a 404.

My nginx conf : 

```
server {
	listen 80 ;
server_name  rss.drycat.fr ;




client_max_body_size 10M;


	root /var/www/rss_drycat_fr/www/p/;
        index index.php index.html;

	access_log /var/log/nginx/rss.drycat.fr.access.log combined buffer=20m flush=5m;
	error_log /var/log/nginx/rss.drycat.fr.error.log warn;

	
	
	
		location = /robots.txt {
	allow all;
	log_not_found off;
	access_log /dev/null;
}
location = /favicon.ico {
	log_not_found off;
	access_log /dev/null;
}
	    	location / {
       try_files $uri $uri/ index.php;
    }
    location ^~ /data {
      deny all;
    }

	
	location ~ \.php$ {
                try_files $uri =404;
                fastcgi_pass unix:/run/php/rss.drycat.fr.sock;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                                include fastcgi_params;
        }
}
```
I removing the `try_files $uri =404`, added `fastcgi_split_path_info ^(.+\.php)(/.*)$;`  and `set $path_info $fastcgi_path_info;` but the error still here.

Can you help me ? 

Thank :)

**Comment by Alkarex** [comment]
Hello,
nginx is very error prone. Please double check our documentation https://freshrss.github.io/FreshRSS/en/admins/10_ServerConfig.html
Alternatively, we have a configuration for Apache, and also a ready-to-use Docker image.

**Comment by Dryusdan** [comment]
Ho write, the error is located here : `location ~ ^.+?\.php(/.*)?$ {` 

Thank :)
