### ISSUE TITLE
View with excerpt of article

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#3157]
Hi everyone!

Would it be possible to have a view that displays just a few lines of the article and not everything, as it is the case now?

Thanks!

**Comment by aledeg** [comment]
@maxclac Is this a duplicate of #3135?

**Comment by ghost** [comment]
Ha yes! Sorry, I haven't seen it.

**Comment by aledeg** [comment]
Perfect, closing this one!
