### ISSUE TITLE
Docker Hub: Take advantage of multi-platform builds

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#3160]
Multi-arch seems to have landed in Docker Hub

* https://www.docker.com/blog/multi-platform-docker-builds/
* `--platform` https://docs.docker.com/engine/reference/commandline/build/

**Comment by math-GH** [comment]
How is the current state here?

**Comment by Alkarex** [comment]
Implemented by https://github.com/FreshRSS/FreshRSS/pull/5808
