### ISSUE TITLE
FeedMe (API access): Only 20 articles in list, despite higher count of unread articles

### ISSUE THREAD

**Issue by nurunet** [FreshRSS/FreshRSS#3166]
Hi!

I switched from Bazqux to a self-hosted instance of FreshRSS yesterday. I added it to FeedMe on Android (using an API password), and all looked fine, but today I realized that the article list in FeedMe only lists the 20 newest articles, despite the number of unread articles being higher. Marking some articles as read in FeedMe and re-syncing gives me extra articles (for a total of 20 again).

I already changed "Number of articles per page" in FreshRSS' display settings to a higher value, so far to no avail. Any idea how to fix this?

Cheers
Ben

**Comment by nurunet** [comment]
I just tried EasyRSS and Readrops, and cannot reproduce the issue. So I now assume it is related to FeedMe rather than FreshRSS.

**Comment by Alkarex** [comment]
Hello and welcome,
"Number of articles per page" in FreshRSS does not have any impact on the API used by mobile clients.

In FeedMe's parameters:
* Under synchronisation, pick "all" for synchronisation mode;
* Under cache, try to increase all values

**Comment by nurunet** [comment]
Thanks a lot. To be honest, I played a lot with the settings yesterday, to no avail. This morning, I suddenly was able to see view beyond the 20th item in FeedMe. No idea what did the trick. But very happy about how it works now.
