### ISSUE TITLE
SQL Export on Cloudron

### ISSUE THREAD

**Issue by ghaisasadvait** [FreshRSS/FreshRSS#3172]
How should I export the entire database from CLI.
What are the commands for the same?

**Comment by SuperSandro2000** [comment]
You can easily research this yourself using a search engine like google.

https://goo.gl/search/how+to+dump+mysql

**Comment by ghaisasadvait** [comment]
Thank you for the reply.
Im using FreshRSS on Cloudron and when i use the following command: mysqldump -u username -p dbname > filename.sql. , the console gives me an erro stating the directory is read only.Any idea how to directly export the database remotely?

**Comment by Alkarex** [comment]
Try the SQLite export above, and set the filename path to somewhere on your home directory where you are allowed to write, or maybe to `/tmp/ ` as in my example

**Comment by ghaisasadvait** [comment]
I was able to get into a write directory.however another error popped up.

 ./cli/export-sqlite-for-user.php --user admin --filename /app/code/db.sqlite


FreshRSS exporting database to SQLite for user “admin”…
Error while initialising SQLite copy: SQLSTATE[HY000] [14] unable to open database file
Result: faile

**Comment by Alkarex** [comment]
Are you allowed to write in `/app/code/` ?
To test, you can try

```sh
ls -alh /app/code/
touch /app/code/test.txt
```

**Comment by ghaisasadvait** [comment]
I successfully backed up using:

mysqldump --user=${CLOUDRON_MYSQL_USERNAME} --password=${CLOUDRON_MYSQL_PASSWORD} --host=${CLOUDRON_MYSQL_HOST} ${CLOUDRON_MYSQL_DATABASE} > /tmp/backup.sql


Thank you so much!

**Comment by ghaisasadvait** [comment]
I imported the sql database in to phpMyAdmin.

Why is the date formatting like this:  1597169640 ?

**Comment by Alkarex** [comment]
It is a Unix timestamp

**Comment by ghaisasadvait** [comment]
Got it! Thank you for such patient and to the point responses!
