### ISSUE TITLE
How to install if 1 directory down?

### ISSUE THREAD

**Issue by github-yuzer** [FreshRSS/FreshRSS#3174]
My shared host has me setup with the main domain we have and all other domain in that folder
So my main site is in /www and any other domain are in the folder. For example:

/www/
/www/example.com

So if I put freshnews at / then when i go to my site example.com, how does it know to go up 2 directories? Also do I go to example.com or example.com/p?

Sorry, for asking but the manual instructions said to post here for questions.

**Comment by Alkarex** [comment]
Hello,
I am not sure how your hosting works.

But if you upload the FreshRSS folder in a way that you have `/www/example.com/FreshRSS/p/` then you need to access it with `https://example.com/FreshRSS/p/`

If you upload the content of the FreshRSS folder in a way that you have  `/www/example.com/p/` then you need to access it with `https://example.com/p/`

In both cases, there are automatic redirections.

But when possible , it is better to expose solely the `/p/` folder of FreshRSS.
