### ISSUE TITLE
FreshRSS error: unknown options: api_password

### ISSUE THREAD

**Issue by oupala** [FreshRSS/FreshRSS#3177]
I am trying to create a new user by the CLI. I'm surprised to get an error: `FreshRSS error: unknown options: api_password`.

When I'm looking at the [documentation](https://github.com/FreshRSS/FreshRSS/tree/5389dd5ddb4a164d0df5e2144442b136ec4fe947/cli#commands), I can see that the option should exist:

```bash
./cli/create-user.php --user username [ --password 'password' --api_password 'api_password' --language en --email user@example.net --token 'longRandomString' --no_default_feeds --purge_after_months 3 --feed_min_articles_default 50 --feed_ttl_default 3600 --since_hours_posts_per_rss 168 --max_posts_per_rss 400 ]
```

Is it linked in a way or another to merge request #2675?

**Comment by oupala** [comment]
The documentation seems outdated. When I run the `create-user.php` script, I get another *inlined* documentation:

> FreshRSS error: unknown options: api_password
Usage: create-user.php --user username ( --password 'password' --language en --email user@example.net --token 'longRandomString'--no_default_feeds --purge_after_months 3 --feed_min_articles_default 50 --feed_ttl_default 3600 --since_hours_posts_per_rss 168 --max_posts_per_rss 400 )

There is no more `api_password` parameter.

Is there some documentation about this change somewhere? How can I set the api password using the cli? Is the `token` replacing the api_password?

By the way, there is a typo in the inlined documentation, there is a missing space: `'longRandomString'--no_default_feeds`.

**Comment by Alkarex** [comment]
@oupala Indeed, you are correct that it is due to https://github.com/FreshRSS/FreshRSS/pull/2675
I had forgotten about it, but I now recall that I had a plan to re-introduce it (I am not sure why @marienfressinaud did not put it back during the same refactoring) but did not come to it...

**Comment by Alkarex** [comment]
@oupala Could you please try this fix? https://github.com/FreshRSS/FreshRSS/pull/3179
(I can merge in /master if that helps testing)

**Comment by oupala** [comment]
I tried the fix and I validate it.

This fix is restoring the old CLI api.

Thanks for this fast fix.

I'm now waiting for a new release of FreshRSS. Can you tell me when do you plan to release it?

**Comment by Alkarex** [comment]
Thanks for the test! Next release hopefully within a few days
