### ISSUE TITLE
What files/folders can be ignored for an typical shared php server install?

### ISSUE THREAD

**Issue by github-yuzer** [FreshRSS/FreshRSS#3182]
Trying to keep my web directory clean as the way this is setup I have to dump it above the root and there is already a lot there. 

I see a bunch of files starting with . and I assume since this is going on a self hosted server, these are not needed as they arent .htaccess or anything.

Some other files that might be omitted?
- Makefile
- cli

Also the folders:
- .github
- Docker
- tests

dont seem like they are needed either.

**Comment by aledeg** [comment]
I suggest you put everything in a folder and configure your web server to serve that folder. Your message suggests that you are asking for a disaster. If I understand correctly, you have one folder with everything in it. If so, there is a chance that 2 projects have the exact same file. In that case, what will you do?

**Comment by github-yuzer** [comment]
Thanks for reading & responding.

Well the problem is how my shared host has setup

lets say / is the webroot
lets say my main site is ubuntu.org and is at /www/
my shared hosts puts all other domains/subdomains in
- /www/example.com/
- /www/linuxmint.com/
- /www/subdomain.ubuntu.org/

So ideally I'd like to put stuff above the root at /freshrss/ and have everything from /www/example.com/p or the contents of "p" at /www/example.com point into ../freshrss/ or ../../freshrss/ for all the required files and keep things neat

But I dont see a way to point to /freshrss/ which is 2 directories above in the configuration, since its kind of hardcoded to look 1 directory up for multiple folders

I'm thinking the only way around this is to just dump everything into /www/example.com/ and use htaccess files to protect the folders the documentation suggests should be above the root for protection. then I can just access example.com/p for my feeds. 

I can't use my main domain name, so I have to put it the files 2 directories below at minimum

**Comment by Alkarex** [comment]
@github-yuzer If you put everything into your `/www/freshrss.example.net/` then your public address will be https://freshrss.example.net/p/ which is OK (but not optimal). The non-public directories are already protected by `.htaccess` (assuming you have them enabled in your Apache - make sure to double-check and test).

If you really want to delete some files manually (which I do not recommend):
* .dockerignore
* .editorconfig
* .gitattributes
* .github/
* .gitignore
* .hadolint.yaml
* .jshintignore
* .jshintrc
* .markdownlint.json
* .stylelintignore
* .stylelintrc
* .travis.yml
* CHANGELOG.md
* CONTRIBUTING.md
* Docker/
* Makefile
* README.fr.md
* docs/
* phpcs.xml
* tests/

**Comment by github-yuzer** [comment]
Ok, I guess I didn't notice the .htaccess files already in certain folders. I just read the installation docs and it said to put it above the webroot, so I took that to mean, that was a hard rule.

Maybe the docs should mention it will still be safe in a public directory but for maximum security put it above the webroot.

Thanks. I've been using this offline for testing/setup and look forward to installing it on my server in a few days. :)
