### ISSUE TITLE
Add option to hide subtitle row

### ISSUE THREAD

**Issue by joshas** [FreshRSS/FreshRSS#3189]
In latest release (version 1.17.0) a new subtitle row appears after post title in normal view. Most of the information provided in subtitle is already available in top line (or bottom, depending on configuration). It would be nice to have an option to hide this new subtitle to save some vertical space and reduce clutter introduced by feed icons.

Here's the "subtitle" I'm talking about, using Blue Lagoon theme:
![Screenshot from 2020-09-24 23-37-37](https://user-images.githubusercontent.com/79141/94197988-39ca7680-febf-11ea-84a5-60da788bb6b8.png)

**Comment by math-GH** [comment]
Have you already checked the "Display" settings?

![grafik](https://user-images.githubusercontent.com/1645099/129493337-50e7b219-4f55-46c2-aa88-11bf57d3c038.png)

It should solve your issue.

Another solution could be to disable the row with CSS via the extension "Custom CSS".
