### ISSUE TITLE
Changer le fonctionnement de récupération des flux tronqués ?

### ISSUE THREAD

**Issue by marienfressinaud** [FreshRSS/FreshRSS#319]
Le fonctionnement actuel ne me convient pas du tout (pas intuitif et pénible même pour moi). Je viens de tomber sur https://github.com/memiks/readityourself qui permettrait de faciliter le fonctionnement (je pense que c'est à peu près le même fonctionnement pour poche)

Ça permettrait de se contenter d'une case à cocher "Récupérer le flux tronqué" :)

**Comment by Alkarex** [comment]
Penser à tester le nouveau système avec
- [ ] https://github.com/FreshRSS/FreshRSS/issues/661
- [ ] https://github.com/FreshRSS/FreshRSS/issues/877

**Comment by math-GH** [comment]
Is it fine now with the css-selectors?

**Comment by marienfressinaud** [comment]
The ticket was about the CSS selector not being practical. It's still my opinion, but as @Alkarex suggested it would be better in an extension. Also, I don't think it's too problematic and I think we can close this ticket.
