### ISSUE TITLE
Docker: support MySQL 8+

### ISSUE THREAD

**Issue by tvlpirb** [FreshRSS/FreshRSS#3191]
I'm on the installation page in the web interface, when entering my database details I get 
`Blast! Verify your database configuration. : Access to database is denied for `freshrss`: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client`

I am running FreshRSS following the docker instructions and hence used the following commands to create the database:
```
$ docker volume create mysql-data
$ docker run -d --restart unless-stopped --log-opt max-size=10m \
  -v mysql-data:/var/lib/mysql \
  -e MYSQL_ROOT_PASSWORD=example \
  -e MYSQL_DATABASE=freshrss \
  -e MYSQL_USER=freshrss \
  -e MYSQL_PASSWORD=example \
  --net freshrss-network \
  --name mysql mysql
```

On the web interface I have entered the following details host = mysql, username = freshrss, password as the one I changed it to, database = freshrss and database prefix is left blank.

I've tried to exec into the docker container and was able to use mysql cli. Is there anything I'm missing?

**Comment by Alkarex** [comment]
Sorry for the delay, this went under my radar during a busy period. This is a sign of MySQL version (8+) that is too recent compared to the PHP version in our current Docker images (7.3.x), which does not support `caching_sha2_password` (requires PHP 7.4.0+ and best 7.4.4+, which should soon be in Alpine 3.13 and Debian 11 Bullseye).

* https://php.net/ref.pdo-mysql
* https://github.com/FreshRSS/FreshRSS/issues/2998#issuecomment-633116735
* https://www.php.net/ChangeLog-7.php#7.4.3
* https://bugs.php.net/bug.php?id=79011

https://php.net/mysqli.requirements

> This is because MySQL 8 defaults to caching_sha2_password, a plugin that is not recognized by the older PHP (mysqlnd) releases. Instead, change it by setting default_authentication_plugin=mysql_native_password in my.cnf. The caching_sha2_password plugin will be supported in a future PHP release.

Here is an example of configuration for MySQL 8.0:

```sh
docker run -d --restart unless-stopped --log-opt max-size=10m \
  -v mysql-data:/var/lib/mysql \
  -e MYSQL_ROOT_PASSWORD=freshrss_root_pass \
  -e MYSQL_DATABASE=freshrss_db \
  -e MYSQL_USER=freshrss_user \
  -e MYSQL_PASSWORD=freshrss_pass \
  --net freshrss-network \
  --name mysql mysql --default-authentication-plugin=mysql_native_password
```

Alternatives include using MySQL 7, MariaDB, PostgreSQL, SQLite.

**Comment by Alkarex** [comment]
Here is a Dockerfile with PHP 8 to test with MySQL 8+ (requires manual docker build) https://github.com/FreshRSS/FreshRSS/pull/3294

**Comment by Alkarex** [comment]
Our Alpine-based Docker image is ready. The default Debian-based Docker image will have to wait for Debian 11, later this year https://lists.debian.org/debian-devel-announce/2021/01/msg00002.html
