### ISSUE TITLE
Feature: add/remove feeds on fever api server

### ISSUE THREAD

**Issue by ryanmccool** [FreshRSS/FreshRSS#3193]
The feedly interaction provides the ability to add/remove feeds. Would love the ability to do similar on a self/hosted FreshRSS(fever) implementation.

**Comment by Alkarex** [comment]
The Fever API does not support that. However, clients using the Google Reader API offer that possibility (supported by FreshRSS) :-)
See a list of supported clients https://github.com/FreshRSS/FreshRSS#apis--native-apps
