### ISSUE TITLE
can't enter next step when installing

### ISSUE THREAD

**Issue by caoruijuan13** [FreshRSS/FreshRSS#3200]
Can't enter the next step when I click 'submit' button in Database configuration page when installing.
(SQLite version 3.26.0)

and I try Mysql, submit success, then refresh this database configuration page, no error, but can't enter next step(General configuration)

Environment: fedora + nginx

Need some help, thanks a lot

**Comment by caoruijuan13** [comment]
Then I replaced nginx with apache2, it succeeded directly😓

**Comment by Frenzie** [comment]
Perhaps your nginx isn't loading the relevant php-pdo module or some such? I'm not sufficiently familiar with Fedora, but if you check your yum for package names along those lines the answer might present itself.

**Comment by Frenzie** [comment]
Also see https://github.com/FreshRSS/FreshRSS/issues/3151 for a similar discussion.
