### ISSUE TITLE
Various questions (switching from Tiny Tiny RSS to FreshRSS)

### ISSUE THREAD

**Issue by killerkarnickel404** [FreshRSS/FreshRSS#3202]
Hello,

I am currently in the process of switching from Tiny Tiny RSS to FreshRSS. 
I was really surprised how much fast FreshRSS is. 👍
Although both run on the same webspace FreshRSS is much faster. 

Now I have some questions.

1.
Can I turn off the display of the attached pictures?
Example https://static.winfuture.de/feeds/WinFuture-News-rss2.0.xml

Here the image is always displayed twice.
Because the same picture is once in the article and then again in the attachment. 

2.
Is it possible to adjust the size of the picture?
So that pictures do not need so much space? 

3.
You can set that all articles are displayed unfolded by default.
Can you also set this for categories?

So category A always unfolded 
Category B not folded out. 

4:  
Is there a possibility to delete several feeds at once?
So to remove all feeds in category xy. with little effort? 

Thanks!

**Comment by aledeg** [comment]
1. There is an open issue (#1668) for that.
1. You can with the use of the CustomCSS extension.
1. It's not possible at the moment. Feel free to open an issue for that.
1. There is an open issue (#3127) for that.
