### ISSUE TITLE
How to use CURLOPT_PROXY in docker?

### ISSUE THREAD

**Issue by gd4Ark** [FreshRSS/FreshRSS#3203]
I need to use an http proxy to circumvention GFW, however I can only find out how to configure it in `config.default.php`: 

https://github.com/FreshRSS/FreshRSS/blob/a0256023a19c524c5880b91ad08651eca33dc221/config.default.php#L120-L131

but I couldn't find how to use them in docker.

I'm using the template here: [docker-compose.yml](https://github.com/FreshRSS/FreshRSS/blob/master/Docker/docker-compose.yml)

thanks!

**Comment by Alkarex** [comment]
Hello, please edit `./data/config.php` and not `./config.default.php`.

Your `./data/config.php` is in a Docker volume.

There are multiple options. Here is one:

1) Find the name of that Docker volume with:

```sh
docker volume ls
```

2) Then find the physical location of that volume

```sh
docker volume inspect ???-data
```

3) Then edit your file:

```sh
nano /var/lib/docker/volumes/???-data/_data/config.php
```

**Comment by gd4Ark** [comment]
> Hello, please edit `./data/config.php` and not `./config.default.php`.
> 
> Your `./data/config.php` is in a Docker volume.
> 
> There are multiple options. Here is one:
> 
> 1. Find the name of that Docker volume with:
> 
> ```shell
> docker volume ls
> ```
> 
> 1. Then find the physical location of that volume
> 
> ```shell
> docker volume inspect ???-data
> ```
> 
> 1. Then edit your file:
> 
> ```shell
> nano /var/lib/docker/volumes/???-data/_data/config.php
> ```
thanks!
