### ISSUE TITLE
Can I sort my feed by date of publication by default?

### ISSUE THREAD

**Issue by vorant94** [FreshRSS/FreshRSS#3204]
HI there, I am new to rss feeds and so on. I've found this app, hosted it on my server and added a couple of feeds. The app is great but I noticed that in main feed articles are not sorted by date of publication but by date of adding them to the app... is there a way to switch this behaviour to use date of publication?

![screenshot](https://i.ibb.co/sQjWqrv/Screen-Shot-2020-10-02-at-16-24-24.png)

P.S. I've read the contributing guidelines and about your chat... but haven't succeeded to register there since I don't know the French and got there some errors I don't understand... So I decided to contact you here

**Comment by aledeg** [comment]
Short answer. No you can't.
Long answer, check those issues and their comments (especially @Alkarex answers):
- [How do I tell FreshRSS to sort articles by publication date, not date added? · Issue #2596 · FreshRSS/FreshRSS](https://github.com/FreshRSS/FreshRSS/issues/2596)
- [Need help for changing the feed sort order from lastSeen to the publish date · Issue #2083 · FreshRSS/FreshRSS](https://github.com/FreshRSS/FreshRSS/issues/2083)

**Comment by vorant94** [comment]
Thanks. Sorry for questioning something that was discussed so many times😅

**Comment by aledeg** [comment]
Don't worry. If you check closely, in one of the aforementioned issues, there is a documentation tag. That means we need to add it in the documentation. But nobody took the time to do that.

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/7149
