### ISSUE TITLE
Feed List Jumps to Top When Selecting Feeds Near the Bottom of the Sidebar

### ISSUE THREAD

**Issue by clobber88** [FreshRSS/FreshRSS#3209]
I have ~100 feeds in the left sidebar. Sometimes I want to start viewing a feed near the bottom of the list (for example #75),  so I scroll down and select it. The feed articles are displayed properly, but the feed list in the sidebar jumps back to the top. I would expect the selected feed name to remain visible in the sidebar at all times.

**Comment by mourdrim** [comment]
Thats something that also happens to me, frankly quite annoying...

There are also a couple more annoyances:
- Scrolling of left column and main window are sometimes synched (they shouldn't be).
- Cropped right click menu when selecting the bottom feeds.

**Comment by Alkarex** [comment]
Could you give a try to https://github.com/FreshRSS/FreshRSS/pull/3231 ?

**Comment by clobber88** [comment]
I'm using a docker container that is currently on 1.17. When it updates to 1.18 I will try it

**Comment by Alkarex** [comment]
@clobber88 You can already try the `freshrss/freshrss:latest` image

**Comment by clobber88** [comment]
Hi have tried to convert from my current docker configuration to the freshrss/freshrss:latest image, but I was not successful. When combined with all the nginx-proxy, database, and customization it seems like I am best off just waiting for the container I am using to update.
