### ISSUE TITLE
cURL error 22: The requested URL returned error: 403 Forbidden

### ISSUE THREAD

**Issue by jpatlab** [FreshRSS/FreshRSS#3216]
Hello,
I found a similar issue in this support forum but it didn't help me. I have this error (_cURL error 22: The requested URL returned error: 403 Forbidden_) when I try to add a feed. I assume the feed has some kind of security against to many refreshes, but it can be accessed publicly and I even can read it through others online RSS parser services. I tried `#force_feed` in the URL, no change. Everything else works fine in my FreshRSS, config is OK.
Any help?
Thanks.

**Comment by Alkarex** [comment]
What is the feed URL?
Try to post the output of `curl -v 'https://example.net/rss.xml'` from the same server.
It can be that you get banned by IP, by User-agent, or something else.

**Comment by jpatlab** [comment]
Hi Alexandre,
The feed: https://www.ouest-france.fr/rss.xml?insee=35
The output: `<p id="cmsg">Please enable JS and disable any ad blocker</p><script>var dd={'cid':'AHrlqAAAAAMAKbKAaq2N9RwAm4WEQQ==','hsh':'B7635473208DC5390ED099BCFA4D90','t':'fe','s':61,'host':'geo.captcha-delivery.com'}</script><script src="https://ct.captcha-delivery.com/c.js">`

Looks like they extended their Adblock detection to their feeds by mistake...?  Or a geo-blocking?

**Comment by Alkarex** [comment]
This feed works for me, both in FreshRSS and via curl, and from two different servers (France and Denmark).
Check from another server. It might be an IP or IP range that is banned.
