### ISSUE TITLE
[Feature] Email user on broken feed

### ISSUE THREAD

**Issue by troyengel** [FreshRSS/FreshRSS#3217]
Apologies if this is already somewhere in the user interface and I cannot find it.

I access my feeds primarily over the mobile web interface (with the Smart Mobile Menu extension active); as such I don't tend to see the left hand column on the left side of the webUI which has a red X if a feed is broken.  I logged in this morning to upgrade my installation to 1.17.0 and noticed a broken feed, they had updated their URL (`.../rss` -> `.../rss.xml`) but it's been broken for a month or more on my side in FreshRSS (they don't post very often, last time was July so it just went unnoticed by me).

Is there a way or could we add a way to send an email alert to the user when one of the operational feeds which was working starts to break?  I see that the `config.php` has the setup to use the local mailer but don't seem to locate anything in `config-user.php` which would align to a webUI element to send mail on a broken feed... so I think it's just not a feature yet, the current mail is for the account creation login stuff only from what I observe at a high level as a user.

Thank you for listening! :)
-te

**Comment by troyengel** [comment]
(disclaimer: not a programmer)

Thinking through this, the "best" user setup is probably a User level (not Feed) setting for "Email on Failure: [x]" and the frequency be one day email digest (not every actualize, not each feed singular). From this view, in code I _think_:

1. In `FreshRSS_feed_Controller::actualizeFeed()` we need to know who the `$user` is; walking the code from `actualize-cli.php` it appears abstracted in such a way that we either need to give this method the user object, _or_ return from this method a new member of the array which indicates there were refresh failures (but I like it better passing the $user into this method, so that webUI and CLI can both use it - de-dupe code)
2. Right around (currently) line 449 in the `elseif` for checking the feed results, it's basically built around expecting a 301 redirect; in my case, it's a 404 which I imagine would have to come "back" from the web hit as part of the simplePie object which is tested next for it's not-null (content) state (someone somewhere has that HTTP 404 code stashed?)

 ```
			$url = $feed->url();	//For detection of HTTP 301
...
			} elseif ($feed->url() !== $url) {	// HTTP 301 Moved Permanently
				Minz_Log::notice('Feed ' . $url . ' moved permanently to ' . $feed->url(false));
				$feedProperties['url'] = $feed->url();
			}

			if ($simplePie != null) {
...
```

(insert programmer magic) so in the above we detect $url() has failed with a bad HTTP error (4xx, 5xx) "around here" and we can now use the $user object to inject a record of what has failed (de-duped - so it if fails 10 times today, it's one line item - maybe a counter++ column next to it?).

The next time an actualize is run (cli or web or API) with > 24hrs since last email, we send the email then clean up (delete the records? set counters to 0?) in preparation for the next 24hrs for failures (not sure what is good here). I would imagine these emails are all $user object methods which we just call (`$user->doDailyThings()`) - all that actualizeFeed is doing is marking them in the DB for the user() use later. We don't junk up actualizeFeed with user code beyond the very basics.

Something like that, but with more actual programmer skill. :)  I do understand that it looks rather more complicated than I had first thought before looking at the existing code - how often to email, how to clean up to prevent stale records, etc.. Sorry about that.

**Comment by nehalvpatel** [comment]
+1 to this.

There is a method called `inError()` on Feed objects and a method called `hasFeedsWithError()` on Category objects. (#984)


## Proposal:

We could have a daily task that checks for feeds that return `true` for `inError()`.
- **If you have it set to alert you daily**:
  - Send an email with the errored feeds.
- **If you have it set to alert after a feed is broken for `n` amount of days**:
  - It increments a running counter of consecutive `errored_days` for each feed that returned `true`.
  - For all the feeds that had an `errored_days` > `0`, but are now returning `false`:
    - Set the respective `errored_days` to `0`.
  - Accumulate each feed that now has `errored_days` >= `n`:
    - Send an email with the errored feeds.
    - Set their `errored_days` to `0`.

If we can't do a daily task, then we can use a hook after each feed crawl session. Within the hook, check if it has been 24 hours since the last time we ran the "task". If it has, run the above steps (the "task").

## To the maintainers:

Is this functionality desired in the base server? If so, I can take a crack at it. If not, I can work on an extension that does this.

**Comment by math-GH** [comment]
Does it really make sense to send an email? An email is a media discontinuity. Right now FreshRSS has a proper mobile view for small screens. 
Maybe a visible warning icon/button would solve the information need, doesn't it?

**Comment by troyengel** [comment]
My apologies, I forgot this was open but it's no longer relevant to me - I'll close it out and help clean up the project from stale issues.
