### ISSUE TITLE
nginx: Unable to login from another device

### ISSUE THREAD

**Issue by vorant94** [FreshRSS/FreshRSS#3218]
Hi, recently I started using FreshRSS.

Everything works fine: I've installed FreshRSS on my VPS in DigitalOcean, set up reverse proxy via Nginx and so on; I can easily login there, manage subscriptions; I've also created API password and successfully getting updates from my Reeder app.

But when I try to login to system either from my phone, from incognito mode on my Google Chrome or simply from another computer I got "Login is invalid" error. I am 100% it is valid since I can logout and login again from my main Mac via the same Google Chrome just without incognito mode...

What can cause this behaviour?

**Comment by Alkarex** [comment]
Hello,
Try to check your FreshRSS logs for additional information.
From the browser in which it works, watch out if you are using a password manager / autocompletion, to be sure which password is actually used. The most likely is incorrect username / password.
You can also try to make another account in FreshRSS to test.

**Comment by vorant94** [comment]
in logs I get this
```
2020-10-11 19:46:58
Password mismatch for user=vorant94, nonce=, c=$2a$04$bkXXxHzb5IvrRFA8LNa31ui2tcCGq/a0U9C7kAgtAKdrZgKkM4G72
```
It obviously says that password is wrong, but it is not😭

I am not using any kind of password manager for freshRSS (neither Chrome built-in one, neither some extension). I started to just copy-paste the password from notepad to be 100% sure it is the same one. no effect...

I've also created the second user following your advice. The effect is the same: I can login from regular Chrome mode, but not from incognito

**Comment by Alkarex** [comment]
@vorant94 The logs show that the nonce is empty. So I am actually surprised that it works in any browser.
This is a sign of server misconfiguration (not handing cookies properly). nginx is very error prone, which is one of the reasons why I recommand Apache for a Web server, and Traefic for a reverse proxy.
See similar issues https://github.com/FreshRSS/FreshRSS/issues/2731#issuecomment-568532273

**Comment by vorant94** [comment]
Yes, it seems you are right about cookies. I turned firewall off and succeeded on logging in if I enter the server straightforward  without proxy. So I decided to follow your advice and switch from nginx to apache2... but I got the same problem (can login from regular chrome, cannot login from incognito, nonce equals nothing in logs)...

here is my 000-default.conf. I just cut off all default comments and commented out "RequestHeader set X-Forwarded-Proto "https"" since I am not using https (but the result is the same even with this row uncommented)
```
<VirtualHost *:80>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        ProxyPreserveHost On

        <Location /freshrss/>
                ProxyPass http://127.0.0.1:81/
                ProxyPassReverse http://127.0.0.1:81/
                RequestHeader set X-Forwarded-Prefix "/freshrss"
#               RequestHeader set X-Forwarded-Proto "https"
                Require all granted
                Options none
        </Location>
</VirtualHost>
```

**Comment by vorant94** [comment]
thanks, I switched from nginx to apache2 and it worked... not immediately, but I am sure I messed up somewhere. now it is alive)))
