### ISSUE TITLE
Time out while adding several feeds

### ISSUE THREAD

**Issue by tonitonae** [FreshRSS/FreshRSS#3220]
Hi.

I recently installed FreshRSS to move self-hosted from Feedly. I exported my list of subscriptions from the latter and then imported the OPML file into FreshRSS, only to discover that most of my feeds, that were working in Feedly, are not working in FreshRSS (a warning icon and a message saying "Blast! This feed has encountered a problem. Please verify that it is always reachable then update it.").

I then checked the feeds, which are working properly. Then I decided to remove and readd all the failing feeds, one by one. With few of them I had luck and they were added but for most of them I keep getting "Unknown errors" and "Time out after XX seconds". The thing is that those feeds can be accessed without a trouble from my laptop and also from the machine where FreshRSS is being hosted (a Synology NAS).

To provide some more context, I am using the Docker container in my Synology NAS, with reverse proxy provided by DSM. The web interface can be accessed without troubles and the mobile API is also working (it is just that I can not see all my feeds because of the the problems I have described).

Finally, just in case it might help, these are some of the failing feeds:

http://feeds.weblogssl.com/genbeta
http://feeds.weblogssl.com/xataka2
http://feeds.feedburner.com/blogspot/wvqp
http://www.historiasdelaciencia.com/?feed=rss2
http://col2.com/feed

Any clues  to what might be going on will be appreciated.

Thanks!

**Comment by Alkarex** [comment]
Works for me, both from FreshRSS and from curl.
Could be a temporary issue, or some IP-based filtering.
Try a `time curl -v 'http://feeds.weblogssl.com/genbeta'` from the same server and post the results.

**Comment by tonitonae** [comment]
Thanks for the prompt reply.

The time from the NAS is:

real    0m0.315s
user    0m0.014s
sys     0m0.010s

I can not run it from within the docker container (no time command in /bin and I do not find the curl command neither :/).

I tried to add again the feed. Still the same  time out...

The docker container uses its own network, as per the instructions:

docker network create freshrss-network

Could that be creating some sort of problem? I am out of ideas...

Thnks again!

**Comment by Alkarex** [comment]
Try something like `sudo docker exec freshrss php -r "readfile('http://feeds.weblogssl.com/genbeta');"`
Please check your FreshRSS logs as well.

**Comment by tonitonae** [comment]
Hi again.

If I run the readfile command I get a timeout:

> sudo docker exec freshrss php -r "readfile('http://feeds.weblogssl.com/genbeta');"
PHP Warning:  readfile(http://feeds.weblogssl.com/genbeta): failed to open stream: Connection timed out in Command line code on line 1

Also, in the logs I got plenty of lines such as the following one, with timeouts:

[Sun, 11 Oct 2020 15:38:30 +0200] [warning] --- cURL error 28: Connection timed out after 15001 milliseconds [http://feeds.feedburner.com/HistoriasDeLaHistoria]

It seems that, for some reason, the connection from the container does not work properly (though it does work sometimes because I got some entries retrieved from some sources).

Any ideas on how to debug this? I am pretty new to Docker.

Thanks again for your help.

**Comment by Alkarex** [comment]
It looks like a local networking issue indeed. Maybe a DNS resolution issue.
You can also try to increase the timeout value in your global FreshRSS `./data/config.php` or per feed.

**Comment by tonitonae** [comment]
Hi again.

My mistake... A couple of days ago I was messing with the Firewall of the Synology and that seemed to be the problem. It seems that I missunderstood how rules are applied and DNS queries were being blocked (actually, I think that every outgoing connection was being blocked).

With it disabled, I can run: php -r "readfile('http://feeds.weblogssl.com/genbeta');" successfully.

No time now to add feeds again. I will try it later and report back.

Sorry for the inconveniencies.

**Comment by tonitonae** [comment]
Just to confirm: everything seems to be working with firewall disabled. Now I have to figure out how to configure that properly.

Sorry for the noise!

**Comment by aledeg** [comment]
@tonitonae Might be worth some entry in the FAQ when you figure out how to configure that.

**Comment by tonitonae** [comment]
Hi @aledeg.

I just figured out how to configure Synology's firewall. It might have been my mistake, because I thought that the rules that I was configuring were all for inbound connections (Synology allows you to select among a set of running applications) but they were applied for both inbound and outbound connections. To allow Docker containers outbound connections to ports blocked by some other rule, explicit rules must be added to allow those connections for each of the subnets of the affected containers, with a higher priority than the blocking one.

I do not know if this can fit in the FAQ as it was my mistake configuring the firewall (althought I am not the first one with this problems: https://www.reddit.com/r/synology/comments/8fo2sj/ds918_firewall_blocking_outgoing_traffic_from/).

Let me know if you want to put that in the FAQ and if you need help to write it.

Cheers.

**Comment by aledeg** [comment]
Here is how I would like you make a documentation PR. I'll write an empty shell example you can follow.

-----

If you have the error ..., it might be because of ....
To identify the problem, here are the steps to follow:
 - step 1: ...
 - step 2: ...
 - ...
Then to fix it, you need to do ....

-----

In your case, the problem was coming from the firewall configuration.
The steps to identify the problem are common to all firewalls.
The fix is also common to all firewall and can be as simple as "fix the firewall configuration".
To help others, you could add something like "When using synology, check the following resources..."

**Comment by tonitonae** [comment]
Would something like this be ok?

If you have the error "Blast! This feed has encountered a problem. Please verify that it is always reachable then update it.", it might be because of a firewall misconfiguration.

To identify the problem, here are the steps to follow:

- step 1: Try to reach the feed locally to discard a problem with the feed itself. You can use your browser to this purpose.
- step 2: Try to reach the feed from the host in which FreshRSS is installed. Something like `time curl -v 'http://myfeed.com'` should make the deal. If you are running FreshRSS within a Docker container, then you can check connectivity from within the container itself with something similar to `sudo docker exec freshrss php -r "readfile('http://myfeed.com');"`. If none of this works, then it might be a problem with your firewall.

Then to fix it, you need to do check your firewall configuration and ensure that you are not blocking connections to IPs and/or ports in which your feeds are located. If using iptables and you are blocking inbound connections to ports 80/443, check that the rules are properly configured and you are not also blocking outbound connections to the very same ports.

For example, when using the firewall provided by Synology, you can block traffic for certain applications (i.e., ports). One could think that these rules would be applied only to incoming connections but specifying * for the originating host of the requests will also include your local networks. To deal with this issue, you will have to add exceptions for your local networks to be able to access those ports with a higher priority than the one blocking incoming connections. This could be similar for other frontends to iptables. Please check the following discussion about a similar issue: https://www.reddit.com/r/synology/comments/8fo2sj/ds918_firewall_blocking_outgoing_traffic_from/.

**Comment by aledeg** [comment]
@tonitonae that's perfect. Could you can add that to the FAQ file from the documentation?
Thank you for taking the time to write that! That's greatly appreciated.
