### ISSUE TITLE
Unable to remove or edit feed once added.

### ISSUE THREAD

**Issue by bittaurus** [FreshRSS/FreshRSS#3221]
After adding [redacted feed url] feed to FreshRSS, when I attempt to manage the feed, it processes the href link in the feeds description when I click on the edit boxes, it won't save, and I can't remove it.

**Comment by Alkarex** [comment]
Thanks for the bug report. Fix coming

**Comment by Alkarex** [comment]
Should be fixed by https://github.com/FreshRSS/FreshRSS/pull/3222
Could you please test the latest version from the master branch?

**Comment by bittaurus** [comment]
Updated to current dev and it seems happy. Thanks.
