### ISSUE TITLE
### Application problem ### See logs files : log_pshb.txt ?

### ISSUE THREAD

**Issue by siSSSou** [FreshRSS/FreshRSS#3227]
Access to FreshRSS (up to date) is broken : 
```
### Application problem ###
See logs files
```
Logs : 
`[Wed, 14 Oct 2020 15:20:25 +0200] [error] --- Permission is denied for /var/www/FreshRSS/data/users/_/log_pshb.txt`

"log_pshb.txt`" is writable by the web server. chmod 777 with no result. File is 1Mo big.

I don't know what to do with that ;-(
Anyone has an idea ?

**Comment by Alkarex** [comment]
P.S. And do you have a cron or similar command-line, which might fail to use the same user than your Web server?

**Comment by siSSSou** [comment]
Thanks for your answer !
```
ls -alh /var/www/FreshRSS/data/users/_/
drwxrwxr-x 2 www-data www-data  4,0K oct.  14 16:23 .
drwxrwxr-x 4 www-data www-data  4,0K août  11 08:59 ..
-rw-r--r-- 1 www-data www-data     0 oct.  14 16:24 config.php
-rw-r--r-- 1 www-data www-data     0 août  11 08:59 .gitignore
-rw-r--r-- 1 www-data www-data   309 août  11 08:59 index.html
-rw-r--r-- 1 www-data www-data  5,3K août   2 10:56 log_api.txt
-rwxrwxrwx 1 www-data www-data 1020K oct.  14 16:46 log_pshb.txt
-rw-r--r-- 1 www-data www-data  2,2K oct.  14 16:46 log.txt
```
chown and chmod parts are OK !
Feed updates with cron are OK (as displayed in nginx logs) : 
`*/20 * * * * php -f /var/www/FreshRSS/app/actualize_script.php > /tmp/FreshRSS.log 2>&1`

But looking at these logs I found out the culprit : system partition is full !
```
PHP Warning:  file_put_contents(): Only 0 of 20135 bytes written, possibly out of free disk space in /var/www/FreshRSS/lib/SimplePie/SimplePie/Cache/File.php on line 112
PHP Warning:  /var/www/FreshRSS/data/cache is not writable. Make sure you've set the correct relative or absolute path, and that the location is server-writable. in /var/www/FreshRSS/lib/SimplePie/SimplePie.php on line 1533
PHP Warning:  file_put_contents(): Only 0 of 147 bytes written, possibly out of free disk space in /var/www/FreshRSS/lib/Minz/Log.php on line 72
Results: 
### Application problem ###<br />
```
So it's not a problem with FreshRSS !
