### ISSUE TITLE
Feed title sorting in LEFT COLUMN shoudn't be case sensitive

### ISSUE THREAD

**Issue by mourdrim** [FreshRSS/FreshRSS#3228]
![](https://user-images.githubusercontent.com/69729502/90318747-fae0f280-df08-11ea-85ad-21965b8b1904.jpg)

Feed title sorting in LEFT COLUMN shouldn't be case sensitive.
As you can see all uppercase feeds are sorted before the lowercase ones. It would be best to keep them all sorted as case insensitive, respecting alphabetical order.

This is what I meant in https://github.com/FreshRSS/FreshRSS/issues/3144, but being a new user I didn't know correct terminology. I thought that fixing one would fix the other, but apparently that's not the case.

FreshRSS 1.17.0

**Comment by aledeg** [comment]
That's weird!
Feeds are properly sorted on my instance :/

**Comment by mourdrim** [comment]
> That's weird!
> Feeds are properly sorted on my instance :/

Any ideas?
I'm using linuxserver docker v1.17.0, tried various browsers and computers, cleared cache, etc, without success.

In the subscription management page everything is correctly sorted.
