### ISSUE TITLE
User Restrictions

### ISSUE THREAD

**Issue by TBJSBigJohn** [FreshRSS/FreshRSS#3232]
Without going into the long details, is there a way to prevent a user from deleting rss addresses / feeds? Could it be possible to restrict the Subscription Management for a user? I tried looking into the extensions, but nothing there seems to be what I am looking for.

    Thank you for your time,

       John

**Comment by Alkarex** [comment]
Hello,
At the moment, there is the anonymous mode, which does some of what you are asking. This mode can be enabled in the FreshRSS settings, and does not require login (you can always add an HTTP Basic Auth protection if you like).

**Comment by math-GH** [comment]
I would suggest the anonymous mode too. It should match with your use case.
Ready to close this issue?
