### ISSUE TITLE
Easier way to add Filters? 

### ISSUE THREAD

**Issue by genem2** [FreshRSS/FreshRSS#3238]
New FreshRSS user, and this is fulfilling most everything I'd be looking for; nice job folks. 

However, as I read my feeds (especially when you're new and have very few filters), I want to stop seeing some entries, so I need another filter. Depending on the app|device|browser you're on, you might not have access to the feed's property, or at least  you're several clicks to navigate into the feed's property to create the filter. 

It would be kick-ass if there was a way to do this directly. Something like: Similar to tie icon to few the article in the browser, have another that lets me set a new filter. Perhaps it would pop up a dialogue box with the article's title and the user could just edit that down to the proper +/-ignore string and just add from there!

I've searched around and don't think this exists natively or with a plug-in. If it does, please advise.

Update: I came across Global Filters #2788. This will help tremendously with my migration from tt_rss. Anxious awaiting 1.18! There also appears to be some additional filter creation enhancements on the horizon; maybe I should just close this one.

**Comment by math-GH** [comment]
A config icon is available in the user query drop down menu now.

![grafik](https://user-images.githubusercontent.com/1645099/187075691-f9931a7d-9bcc-4cb5-ae38-83b03af58396.png)

@genem2 does it solve your Feature Request?

**Comment by genem2** [comment]
Just noticed this comment today, sorry.
I was really hoping not to run a UI-query every time.
I think I should just close this issue and monitor [2278](https://github.com/FreshRSS/FreshRSS/issues/2788).
