### ISSUE TITLE
Password mismatch on new install

### ISSUE THREAD

**Issue by github-yuzer** [FreshRSS/FreshRSS#3239]
Everything installed successfully, but I can't login. I even tried this twice, copied my password and pasted it elsewhere. Even when it and redid my password in the config with bcrypt to reset it. Again I tried several times. I dont know what the issue is.

In the log.txt I have
user=admin, nonce=, c=............(edited this part out)

Using version 1.17.1-dev

**Comment by Alkarex** [comment]
Hello,
How did you install FreshRSS, which version, and on which server platform, and using which browser?

**Comment by github-yuzer** [comment]
uploaded files onto server in main folder mysite.example.com
used version 1.17.1-dev
linux server
firefox v81.0.2, even tried vivaldi v3.1.1929.45

**Comment by Alkarex** [comment]
I have just tried from a blank setup and cannot reproduce any problem.
Please try with a a password with no special character, just to remove this risk. Please check the errors in your browser console, in your Web server logs, and in the FreshRSS logs `./FreshRSS/data/users/*/log*.txt`

**Comment by Alkarex** [comment]
And what Linux server more precisely?

**Comment by github-yuzer** [comment]
Ok I see I'm getting a 403 on https://mysite.example.com/p/i/?c=auth&a=login for some reason

Architecture | x86_64
Operating System | linux
Kernel Version | 4.14.146-225.ELK.el6.x86_64

I'm not sure what kind of Linux, I tried to find out but only got that information above as I'm on shared hosting. But have never had problems doing crons, running scripts, etc.

**Comment by Alkarex** [comment]
Do you have anything in your browser logs and FreshRSS logs?

**Comment by github-yuzer** [comment]
Same thing as before:
Password mismatch for user=admin, nonce=, c=....

PHP Version 5.6.38

---
POST https://mysite.example.com/p/i/?c=auth&a=login
[HTTP/2 403 Forbidden 373ms]

POST
	
scheme
	https
host
	mysite.example.com
filename
	/p/i/
c
	auth
a
	login
Address
	0.0.0.0:443
Status403
Forbidden
VersionHTTP/2
Transferred2.61 KB (5.37 KB size)

	
cache-control
	private, must-revalidate, max-age=0
content-encoding
	gzip
content-length
	2287
content-security-policy
	default-src 'self'
content-type
	text/html; charset=UTF-8
date
	Tue, 03 Nov 2020 17:11:02 GMT
last-modified
	Tue, 03 Nov 2020 17:11:02 GMT
server
	Apache
vary
	Accept-Encoding
x-content-type-options
	nosniff
X-Firefox-Spdy
	h2

**Comment by Alkarex** [comment]
Not that: your browser logs (= JavaScript console) and the FreshRSS logs (= text files)

**Comment by github-yuzer** [comment]
The 403 happens in the JavaScript Console

I also have warnings like
Cookie “__gads” will be soon treated as cross-site cookie against “https://mysite.example.com/p/i/?c=auth&a=login” because the scheme does not match.
Cookie “FreshRSS” will be soon treated as cross-site cookie against “https://mysite.example.com/p/i/?c=auth&a=login” because the scheme does not match.

**Comment by Alkarex** [comment]
Try to change in `data/config.php` for using `'auth_type' => 'none',`
Then change your password in the FreshRSS interface, and then change the authentication method back to *Form* in the FreshRSS interface.
You are welcome to send me a test account if you like

**Comment by github-yuzer** [comment]
I set it to 'none', then tried to change the password in FreshRSS and it gives me this error

`Error 403 - Forbidden

You don’t have permission to access this page [CSRF]`

Its from the URL https://mysite.example.com/p/i/?c=error&rid=5fa4bc1dc0055

**Comment by github-yuzer** [comment]
> 
> 
> Try to change in `data/config.php` for using `'auth_type' => 'none',`
> Then change your password in the FreshRSS interface, and then change the authentication method back to _Form_ in the FreshRSS interface.
> You are welcome to send me a test account if you like

How do I send you a test account?

**Comment by Alkarex** [comment]
@github-yuzer You are welcome to [drop me an e-mail](https://alexandre.alapetite.fr/cv/)

**Comment by Alkarex** [comment]
Sorry for the delay. I cannot spot any problem on the login page, so the problem must be on the back-end side.
Did you try with our [last release 1.17.0](https://github.com/FreshRSS/FreshRSS/releases/tag/1.17.0) (and not 1.17.1-dev)?

**Comment by Detao-Zhang** [comment]
Hi,
I also found this issue on my docker installation. I tried the 1.17.0 image but still unable to login.
I am running on ubuntu 20.04 with Nginx as frontend. I found some old issues about Nginx incompatibilities and re-setup the server with the recommandations you gave but the issue still exists.

**Comment by Detao-Zhang** [comment]
Oh, the confusing part is that I can login in the first two days and suddenly I found the issue, with same browser (Safari 14) and server setup.

**Comment by Alkarex** [comment]
There was indeed a bug for PHP 7.1 and older, fixed in https://github.com/FreshRSS/FreshRSS/pull/3273
Tests welcome
