### ISSUE TITLE
User migration with sqldump?

### ISSUE THREAD

**Issue by bittaurus** [FreshRSS/FreshRSS#3242]
I installed FreshRSS on a new instance with the same sql backend.  I intended to migrate to this new machine.  I exported my FreshRSS database with mysqldump from the old instance.  Installed and initialized the FreshRSS on the new machine.  Then imported the database with the script generated by mysqldump.

The users data is in the database, and actualize is operating on them, but the users don't show up on the User list in the management UI.

What am I doing wrong?

**Comment by Alkarex** [comment]
Hello,
You also need to move the content of your `./FreshRSS/data/` folder.
For migration, I recommand using our export to SQLite, and import from SQLite functionality from command line (after creating the users from command line as well). See https://github.com/FreshRSS/FreshRSS/tree/master/cli
