### ISSUE TITLE
Permission mismatch after upgrade to 1.17.1-dev

### ISSUE THREAD

**Issue by derdide** [FreshRSS/FreshRSS#3246]
Hi,
I updated to 1.17.1-dev last night (no issue encountered) and since then I seem to have a permission issue:
* when I'm trying to mark individual items as Read, it doesn't work and I get this error message: A request has failed, it may have been caused by internet connection problems.
* when I'm trying to mark all items as Read, it doesn't work either and I end up on the Error 403 page

In the Settings menu, installation check is all green, incl. permissions. So I don't know what's wrong...

**Comment by Alkarex** [comment]
Please post your corresponding Web server logs, FreshRSS logs, and Web
browser console

**Comment by Alkarex** [comment]
And details about your setup, e.g. database type

**Comment by derdide** [comment]
Database is a MariaDB on a Synology NAS. FreshRSS is installed on a nginx webserver running on a Raspberry Pi 3. The webconcole is attached. 
Web server logs are empty - I don't know why, logging is enabled but log files are empty.
Web console says:
`Cookie “FreshRSS” will be soon treated as cross-site cookie against “http://XXX.net:8080/i/” because the scheme does not match. i
Cookie “FreshRSS” will be soon treated as cross-site cookie against “http://XXX.net:8080/i/” because the scheme does not match. i
ThreePanesView FreshRSS extension detected ext.php:3:13
ThreePanesView FreshRSS extension waiting for FreshRSS to be initialized ext.php:8:21
Cookie “FreshRSS” will be soon treated as cross-site cookie against “http://XXX.net:8080/ext.php?f=xextension-threepanesview-master%2Fstatic%2Fthreepanesview.js&t=js&1588150368” because the scheme does not match. ext.php
Cookie “FreshRSS” will be soon treated as cross-site cookie against “http://XXX.net:8080/scripts/main.js?1604956190” because the scheme does not match. main.js
FreshRSS main init done. main.js:1632:11
The Notification permission may only be requested in a secure context. i
Cookie “FreshRSS” will be soon treated as cross-site cookie against “http://XXX.net:8080/themes/icons/favicon-256.png” because the scheme does not match. favicon-256.png
An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can remove its sandboxing. i
Cookie “FreshRSS” will be soon treated as cross-site cookie against “http://XXX.net:8080/themes/icons/grey.gif” because the scheme does not match. 2 grey.gif`

FreshRSS log is irrelevant to the issue but I put it here just in case (I wanted to post another issue about these two problems, I don't understand why these feeds end up in error)
`[Mon, 09 Nov 2020 20:40:02 +0000] [warning] --- cURL error 22: The requested URL returned error: 503 Service Temporarily Unavailable [https://www.lecourrierdesstrateges.fr/feed/atom/]
[Mon, 09 Nov 2020 21:20:53 +0000] [warning] --- cURL error 60: SSL certificate problem: unable to get local issuer certificate [https://photoetmac.com/feed/]
[Mon, 09 Nov 2020 22:00:01 +0000] [warning] --- cURL error 22: The requested URL returned error: 503 Service Temporarily Unavailable [https://www.lecourrierdesstrateges.fr/feed/]
[Mon, 09 Nov 2020 22:40:07 +0000] [warning] --- cURL error 22: The requested URL returned error: 500 Internal Server Error [http://lepetitpoussoir.fr/feed]
[Mon, 09 Nov 2020 22:40:53 +0000] [warning] --- cURL error 60: SSL certificate problem: unable to get local issuer certificate [https://photoetmac.com/feed/]
[Mon, 09 Nov 2020 23:20:02 +0000] [warning] --- cURL error 22: The requested URL returned error: 503 Service Temporarily Unavailable [https://www.lecourrierdesstrateges.fr/feed/]
[Tue, 10 Nov 2020 00:00:37 +0000] [warning] --- cURL error 60: SSL certificate problem: unable to get local issuer certificate [https://photoetmac.com/feed/]
[Tue, 10 Nov 2020 00:40:02 +0000] [warning] --- cURL error 22: The requested URL returned error: 503 Service Temporarily Unavailable [https://www.lecourrierdesstrateges.fr/feed/]
[Tue, 10 Nov 2020 01:20:28 +0000] [warning] --- cURL error 60: SSL certificate problem: unable to get local issuer certificate [https://photoetmac.com/feed/]
[Tue, 10 Nov 2020 02:00:02 +0000] [warning] --- cURL error 22: The requested URL returned error: 503 Service Temporarily Unavailable [https://www.lecourrierdesstrateges.fr/feed/]
[Tue, 10 Nov 2020 02:40:29 +0000] [warning] --- cURL error 60: SSL certificate problem: unable to get local issuer certificate [https://photoetmac.com/feed/]
[Tue, 10 Nov 2020 03:20:02 +0000] [warning] --- cURL error 22: The requested URL returned error: 503 Service Temporarily Unavailable [https://www.lecourrierdesstrateges.fr/feed/]
[Tue, 10 Nov 2020 04:00:30 +0000] [warning] --- cURL error 60: SSL certificate problem: unable to get local issuer certificate [https://photoetmac.com/feed/]
[Tue, 10 Nov 2020 04:40:01 +0000] [warning] --- cURL error 22: The requested URL returned error: 503 Service Temporarily Unavailable [https://www.lecourrierdesstrateges.fr/feed/]
[Tue, 10 Nov 2020 05:20:30 +0000] [warning] --- cURL error 60: SSL certificate problem: unable to get local issuer certificate [https://photoetmac.com/feed/]
[Tue, 10 Nov 2020 06:00:01 +0000] [warning] --- cURL error 22: The requested URL returned error: 503 Service Temporarily Unavailable [https://www.lecourrierdesstrateges.fr/feed/]
[Tue, 10 Nov 2020 06:40:27 +0000] [warning] --- cURL error 60: SSL certificate problem: unable to get local issuer certificate [https://photoetmac.com/feed/]
[Tue, 10 Nov 2020 07:20:01 +0000] [warning] --- cURL error 22: The requested URL returned error: 503 Service Temporarily Unavailable [https://www.lecourrierdesstrateges.fr/feed/]`

**Comment by derdide** [comment]
Some more from the Web console (filtering on errors)
The Notification permission may only be requested in a secure context. i
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”). 2 main.js:1463:19

**Comment by derdide** [comment]
Ah, I tried on a second browser (Edge instead of FF) and couldn't login. So I went back to FF and cleared all site data. And now I can't log back into it either...

**Comment by derdide** [comment]
I reinstalled FreshRSS. Install procedure worked well through the wizard. But login is blocked again. Web console:
POST http://XXX.net:8080/i/?c=auth&a=login [HTTP/1.1 403 Forbidden 31ms]

**Comment by derdide** [comment]
The nginx config is a the same than in documentation. I don't know where else to look now

**Comment by derdide** [comment]
I'm still on using PHP5.6, still mentioned as compatible.

**Comment by Frenzie** [comment]
What do the nginx logs say about the internal server error?

**Comment by derdide** [comment]
I've disabled the authentication and solved my nginx logs issue. Now I get something there:
`2020/11/11 13:08:17 [error] 20801#0: *99 FastCGI sent in stderr: "PHP message: PHP Notice:  Trying to get property of non-object in /home/pi/FreshRSS/app/FreshRSS.php on line 93
PHP message: PHP Notice:  Trying to get property of non-object in /home/pi/FreshRSS/app/FreshRSS.php on line 94" while reading response header from upstream, client: 212.4.88.210, server: *.XXX.net, request: "POST /i/?c=javascript&a=actualize HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "XXX.net:8080"
`

**Comment by Frenzie** [comment]
That line's from https://github.com/FreshRSS/FreshRSS/pull/3022 (1.17). What version did you upgrade from?

**Comment by derdide** [comment]
I don't remember... sorry!

**Comment by derdide** [comment]
Just to clarify from your answer: my understanding is that #3022 is a new feature, and my upgrade path has somehow broken that feature, as something required by this new feature went missing. Am I correct? 

If yes, how do I solve this? Because I have to admit that when reading through the #3022 thread, the answer is not obvious to me :-)

**Comment by Frenzie** [comment]
At this time I only mean the lines that are returning an error were introduced in #3022. Incidentally, a search also produces https://github.com/FreshRSS/FreshRSS/issues/3136
```
Trying to get property of non-object in /home/pi/FreshRSS/app/FreshRSS.php on line 93
Trying to get property of non-object in /home/pi/FreshRSS/app/FreshRSS.php on line 94
```

**Comment by derdide** [comment]
I already tried deleting cache & cookies, even before logging the issue. I'm pretty sure that the issue will end up being trivial - once it is found...

**Comment by Alkarex** [comment]
@derdide There is probably another FreshRSS log in `/FreshRSS/data/users/derdide/log.txt`
Could you please check?

Did you try to re-apply the file permissions fully?

Something like (adapt to your Web server username):

```sh
cd FreshRSS
chown -R :www-data .
chmod -R g+r .
chmod -R g+w ./data/
```

**Comment by Alkarex** [comment]
I am looking into the PHP errors

**Comment by derdide** [comment]
@Alkarex : the log.txt file has been reinitialized after the new install. It just mentions password mismatches. That explains why I can't login (I'm very surprised about the mismatch but when I'm trying to reset the password, I encounter the same error 403 error). 
Permissions I did, multiple times. using these precise commands from the documentation. I did it again tonight after your message. Still same result.

Thanks for looking. If it wasn't for the existing data, I'd reinstall fully. I even tried the export feature but that one doesn't work either

**Comment by Alkarex** [comment]
Don't worry, the data should be safe. I am looking into fixing the dev branch. How did you install FreshRSS? With git?

**Comment by derdide** [comment]
I'm not worried about the data. But I wouldn't want to restart everything from scratch on an empty database and re-add all feeds one by one. I know ways to workaround this, but this is still last resort. The first install, I did by downloading the ZIP, and updated through the admin panel when I thought about it. 
The new install this morning I did using git

**Comment by Alkarex** [comment]
@derdide Please try the latest dev version (with git, you can just `git pull`). It will probably not fix your core problem, but likely show another more relevant problem

**Comment by derdide** [comment]
I just did - 1.17.1-dev. No change. 
Web console:

```
08:00:32.111`

XHRGEThttp://derdide.net:8080/i/?c=error&rid=5facdd8f3ab00
[HTTP/1.1 403 Forbidden 37ms]

08:00:34.207 Navigated to http://derdide.net:8080/i/
08:00:34.683 The Notification permission may only be requested in a secure context.`
```

FreshRSS log empty
nginx log empty

These two logs being empty while encountering errors make me wonder: is there any setting I should to get more verbose logs?

**Comment by derdide** [comment]
I just restarted the server (yes, I know, I should have tried it earlier...). Now nginx log shows something:
`2020/11/12 07:05:57 [crit] 877#0: *1 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 212.4.88.210, server: *.derdide.net, request: "GET /i/?c=javascript&a=nbUnreadsPerFeed HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "derdide.net:8080"
`

**Comment by Alkarex** [comment]
Hum, this looks like an nginx misconfiguration...

**Comment by derdide** [comment]
Yes, I thought so but I don't understand why... Here is the PHP part of the nginx config file:
```
        location ~ ^.+?\.php(/.*)?$ {
                fastcgi_pass unix:/var/run/php5-fpm.sock;
                fastcgi_split_path_info ^(.+\.php)(/.*)$;
                # By default, the variable PATH_INFO is not set under PHP-FPM
                # But FreshRSS API greader.php need it. If you have a “Bad Request” error, double check this var!
                fastcgi_param PATH_INFO $fastcgi_path_info;
                include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }


```

**Comment by derdide** [comment]
nginx error log:
```
2020/11/12 09:02:52 [error] 876#0: *339 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 49.145.142.185, server: *.XXX.net, request: "GET /currentsetting.htm HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "xxx.xxx.xxx.xxx"
2020/11/12 12:41:20 [error] 878#0: *470 FastCGI sent in stderr: "PHP message: PHP Warning:  file_put_contents(./!hub.json): failed to open stream: Permission denied in /home/pi/FreshRSS/p/api/pshb.php on line 84" while reading response header from upstream, client: 192.0.89.89, server: *.XXX.net, request: "GET /api/pshb.php?k=b6c325e25822f37965de9e9a98742da6e2fbe470&hub.lease_seconds=$
2```

**Comment by derdide** [comment]
I tried to install another instance (same server, different folder, different port, different nginx config file, different database). Installation process went smoothly but same issues occur then. 

nginx log:
```
2020/11/23 16:38:13 [error] 18937#0: *123 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 192.168.0.124, server: *.XXX.net, request: "GET /i/?c=javascript&a=nbUnreadsPerFeed HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "192.168.0.203:8081"
2020/11/23 16:40:02 [error] 18937#0: *135 FastCGI sent in stderr: "PHP message: PHP Warning:  file_put_contents(./!hub.json): failed to open stream: Permission denied in /home/pi/FreshRSS/p/api/pshb.php on line 84" while reading response header from upstream, client: 66.249.93.70, server: *.XXX.net, request: "GET /api/pshb.php?k=fc81e7f30fb28e3545d09ebe2fb17e979b288c9a&hub.topic=https://lecourrierdesstrateges.fr/feed/&hub.chal$
2020/11/23 16:41:33 [error] 18937#0: *139 FastCGI sent in stderr: "PHP message: PHP Notice:  A session had already been started - ignoring session_start() in /var/www/html/rss/lib/Minz/Session.php on line 72" while reading response header from upstream, client: 192.168.0.124, server: *.XXX.net, request: "GET /i/index.php?step=2 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "192.168.0.203:8081", referrer:$
2020/11/23 16:42:58 [error] 18937#0: *148 FastCGI sent in stderr: "PHP message: PHP Notice:  A session had already been started - ignoring session_start() in /var/www/html/rss/lib/Minz/Session.php on line 72" while reading response header from upstream, client: 192.168.0.124, server: *.XXX.net, request: "POST /i/index.php?step=2 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "192.168.0.203:8081", referrer$
```

I don't know what to do now...

**Comment by Alkarex** [comment]
Hello,
Could you by any chance try on another test server to reproduce the problem?
Can you confirm whether it works or not with version 1.17.0?
Did you make sure to give write access to `./data/` and its sub-folders, in particular `./data/PubSubHubbub/`?
Any chance of trying another Web server such as Apache?

**Comment by derdide** [comment]
Hi, I don't have another server available on this. Maybe I'll do a complete fresh install of the server... Permissions on './data' are correct. 

Quick question on version: which one should I install? I'm a bit confused. And how can I install another version than the current one?

**Comment by Alkarex** [comment]
While you are welcome to test the current development version (master branch), I recommend that for a first installation you pick our latest release https://github.com/FreshRSS/FreshRSS/releases/latest (currently 1.17.0). How to install it depends on which method you want (git, Docker, ZIP...). Releases contain a downloadable ZIP, and a git tag.

**Comment by derdide** [comment]
I just installed the 1.17.0 on the same server, using same nginx settings and the same database - I just changed the symlink in `/var/www` to the newly downloaded FreshRSS-1.17.0 folder, launched the install wizard and pointed it to the same DB. 

Everything is working properly again...
