### ISSUE TITLE
Reeder not working with FreshRSS greader API

### ISSUE THREAD

**Issue by jim3ma** [FreshRSS/FreshRSS#3247]
FreshRSS Version: 1.17.1-dev

When use greader API, Reeder can not get any items.

I have found some decode errors in Console for Reeder.
```
syncer error Optional(Swift.DecodingError.typeMismatch(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "continuation", intValue: nil)], debugDescription: "Expected to decode String but found a number instead.", underlyingError: nil)))
```

but fever API is ok in Reeder.

**Comment by Alkarex** [comment]
Thanks for the bug report. Could you please try with our latest release 1.17.0?

**Comment by jim3ma** [comment]
@Alkarex Same issue with freshrss/freshrss:1.17.0.

**Comment by Alkarex** [comment]
@jim3ma Could you please test this patch? https://github.com/FreshRSS/FreshRSS/pull/3250

**Comment by jim3ma** [comment]
> @jim3ma Could you please test this patch? #3250

It works.
Thanks!
