### ISSUE TITLE
Buttons for user queries and oldest/newest are the same

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/FreshRSS#3251]
Hello everyone, just a minor issue which didn't bother me on PC screen but started to confuse me on a mobile screen:

![Sans titre](https://user-images.githubusercontent.com/7189936/98913169-4a629a80-24c7-11eb-9bf1-8c6a06056202.png)

The buttons are the same! Maybe we could find something else for one of them?

**Comment by Alwaysin** [comment]
I didn't even notice the third one! Three buttons with the same icon to do three different things.
But it's going to be difficult because each theme has its own icons... So we'll have to update everyone of them.

What about standardizing the icons and just change the color depending on what is needed by the theme? By using something like fontawesome. But yeah it's easy to say it but not easy to do I know!

**Comment by Alkarex** [comment]
We share some (not all) icons (SVG) between themes

**Comment by aledeg** [comment]
As I mentioned in #3447, I think we should use a bookmark icon for the user queries.
We should use different icons for the sorting button like [this](https://fontawesome.com/icons/sort-numeric-down-alt?style=solid) and [this](https://fontawesome.com/icons/sort-numeric-up?style=solid).
For the drowp-down, I'll keep the one we have at the moment.

**Comment by squromiv** [comment]
Noticed this problem a long time ago. It is really very confusing.

**Comment by Alwaysin** [comment]
Thank you very much @math-GH!
