### ISSUE TITLE
Can't update feeds.

### ISSUE THREAD

**Issue by lebrisg** [FreshRSS/FreshRSS#3253]
CentOS 7.9, nginx 1.18.0, php-fpm 7.3.24, php 7.3.24, MariaDB 5.5.68

I have been using freshrss 1.14.3 successfully for 1 year.
Suddenly it stopped automatic updates (actualize_script.php) with the following messages:
===========================================
FreshRSS starting feeds actualization at 2020-11-12T22:57:28+01:00
FreshRSS actualize user...
PHP Warning:  Error while sending STMT_EXECUTE packet. PID=8293 in /var/www/html/freshrss/app/Models/EntryDAO.php on line 133
FreshRSS actualization done for 1 users, using 20.00 MiB of memory, in 0 day(s), 0 hour(s), 0 minute(s) and 6 seconds.
Results:
user OK
End.
===========================================
I upgraded to 1.17.0 without any success.

**Comment by Frenzie** [comment]
That's a MariaDB error. Bit strange that the script still seems to return `OK` afterward.

I'd start at the basics. Do you still have space available, does restarting MariaDB do anything, etc. Incidentally, MariaDB isn't or wasn't very clever about recovering from disk space-related issues, see <https://fransdejonge.com/2018/02/mariadb-fix-cant-init-tc-log-error/>.

**Comment by lebrisg** [comment]
I've got no database space problem (1.5GB still available in /var).
I restarted MariaDB without any changes. I even upgraded the package to the latest version 5.5.68.
I checked the MariaDB logs without seeing any errors.
I just ran the mysqltuner.pl script to see if my default MariaDB configuration was source of trouble: nothing special.

I don't know what the EntryDAO.php file is about. Could it be a compatibility problem between MySQL and MariaDB?
Knowing what this file does could help guide my research.

**Comment by Frenzie** [comment]
That's just an abstraction. lib/Minz/ModelPdo.php or something along those lines would probably be more relevant wrt error handling here.

Is the MariaDB instance overloaded? Any damaged tables?

**Comment by lebrisg** [comment]
The instance isn't overloaded: I'm the only one to use it.
There doesn't seem any table damaged.

**Comment by lebrisg** [comment]
I just ran the mysqlcheck command without any error message which seems to eliminate a MariaDB error.

**Comment by lebrisg** [comment]
In my quest to find a solution, I checked the php-fpm logs and found in the /var/log/php-fpm/www-error.log file the following content:
PHP Warning:  file_put_contents(./!hub.json): failed to open stream: Permission denied in /var/www/html/freshrss/p/api/pshb.php on line 84
I have no idea if there is a connection to my problem.

**Comment by Frenzie** [comment]
That error in and of itself probably not, but I suppose it could point to a more general issue with your permissions. The original error is definitely related to the communication with the database though.

**Comment by Alkarex** [comment]
Hum, could be an article that is too large for some local MySQL settings. What is e.g. your `max_packet_length` in MySQL?

**Comment by lebrisg** [comment]
I finally found the culprit.
I recently added an RSS feed associated with this website: https://blog.rossbrigoli.com
As the RSS feed link has got an unusual form "https://blog.rossbrigoli.com/feeds/posts/default?alt=rss", I certainly didn't enter it correctly. At least, the system accepted it.
Then, you already know what kind of problems I encountered.
To find the problem, I added the --log=file argument to my MariaDB systemd unit file and was able to log all the queries.
The problem was not a direct database problem (there were no error messages in the logs) but an indirect one: some queries couldn't be executed.
Thanks for your time.

**Comment by Frenzie** [comment]
I'm not sure I quite understand what caused the problem based on your description. You manually entered `https://blog.rossbrigoli.com/feeds/posts/default?alt=rss` but made a mistake along the way, and somehow this led to issues? It sounds like there's some kind of bug to be fixed then, but we'd have to know how to reproduce it first. :-)

**Comment by lebrisg** [comment]
I tried to reproduce it but until now I can't.
