### ISSUE TITLE
Old (read) articles are displayed again (as new)

### ISSUE THREAD

**Issue by cryptosteve2** [FreshRSS/FreshRSS#3255]
Hi,

Again and again I get articles (that I have already read or marked as read) displayed as new and they do not fit the date of the display. 

The installation is about 3 days old.

Example feed: https://www.buchholz.de/portal/rss.xml
example screenshot: https://adler.crashmail.de/~stell/freshrss.png

As you can see the entries No 4 and 5 are quite old and do not fit into the category "Gestern" (=yesterday) and I have no idea why they show up. Options -> Readings -> "[ ] Mark updated articles as unread" is unset.

I do not have this entries as new in ttrss and in a free Inoreader account. Any ideas? Thanks in advance.

**Comment by cryptosteve2** [comment]
Btw, I found an option in ttrss:

`Maximum age of fresh articles: 24 hours`

Is there something similar in FreshRSS?

**Comment by Alkarex** [comment]
Not at the moment, but I am planning to introduce several automatic filtering options based on e.g. similar title, similar link, date, etc.
For this specific feed, it would be nice to keep multiple copies of https://www.buchholz.de/portal/rss.xml with a timestamp to do some debugging

**Comment by cryptosteve2** [comment]
This problem can be solved by implementing a feature not to recognize articles older than 24 hours (e.g.) or are feed related (broken feeds shows up old articles again due to changes).

I'm saved the feed daily for about 10 days now but - of cause - the problem did not show up again. This issue is closed for the moment. Thanks for your help.
