### ISSUE TITLE
enhancements: show "show only feeds with errors" at top  and only if errors exist?

### ISSUE THREAD

**Issue by rezad1393** [FreshRSS/FreshRSS#3257]
can the "show only feeds with errors" be shown at top?
I have too scroll to bottom with is to long because of the quantity of feeds I have.
also it would be nicer to show that only if a feed (or feeds) has errors.

**Comment by math-GH** [comment]
@rezad1393 I would be happy to get some feedback from you in #3893

**Comment by rezad1393** [comment]
> @rezad1393 I would be happy to get some feedback from you in #3893

thank you for your work.

right now I cant install any git or diff, because to be honest I am a bit tired of testing my setup and messing it up.
recently I had to convert back from btrfs to ext4 a 8tb drive because I am noob and don't understand btrfs and it seemed to make freshrss sqlite operations  slower.

so right now I cant really test anything for a while, at least until I have concluded that btrfs was the issue with my slow freshrss (which seems to be for at least till now) 

but I looked at the pictures and I love the changes.
just a point I like to point out:
if it is possible make  "show only feeds with errors"  only if errors exists?

also if I can burden you with more suggestion, can something be implemented that the users doesnt have to updates feeds manually if errors exist (maybe because of network issues at the time of last update).
right now I have to open every feed separately and just click update (most my errors are network timeout because of bad internet)
if it is possible add a button that user just clicks and all the erroneous feeds just update?

**Comment by math-GH** [comment]
> 
> but I looked at the pictures and I love the changes. just a point I like to point out: if it is possible make "show only feeds with errors" only if errors exists?


It is implemented :)  See PR text
![grafik](https://user-images.githubusercontent.com/1645099/137583175-08f79de7-235a-4051-9155-0a554565a410.png)

> 
> also if I can burden you with more suggestion, can something be implemented that the users doesnt have to updates feeds manually if errors exist (maybe because of network issues at the time of last update). right now I have to open every feed separately and just click update (most my errors are network timeout because of bad internet) if it is possible add a button that user just clicks and all the erroneous feeds just update?

It will be another FR/PR.
Quick solution: Press the update button
![grafik](https://user-images.githubusercontent.com/1645099/137583233-fce35e77-9422-40da-b147-6fbaa2cb78c3.png)

**Comment by rezad1393** [comment]
does that update(refresh) button also tries the erroneous feeds too?
because when I use that it only work on feeds that missed the update, like when I changed the permission on data folder and that caused the cron php update to fail.
then I used fresh button and it fetched the missed feeds.
but I have not tested with erroneous feeds that have failed because of network issues.

also if that button tries the failed feeds again why you added "It will be another FR/PR."
wouldnt have refresh button be enough?

update:
I tested but the refresh button doesnt refresh/update my erroneous feeds.
 it just says "There are no feeds to refresh"

**Comment by rezad1393** [comment]
should I wait for that PR to land and a release be done to request the second part of this issue?
the part about updating feeds that has errors with just one click.
or can I open a separate issue right now and it mention there that it is for after that PR?

**Comment by math-GH** [comment]
both is possible

**Comment by rezad1393** [comment]
> both is possible

what?
I literally can't do both.
either I wait or I don't.

should I create an issue after release is done, or should I open one now and mention that I am requesting an enhancement against the main branch (not the current release that doesnt have the last PR merged)?
i didnt encounter this situation before.

**Comment by math-GH** [comment]
@rezad1393: It is up to you to write the improvement feature request right now or wait till the release.
