### ISSUE TITLE
Problems with automatic feed update via Cron (Error 403)

### ISSUE THREAD

**Issue by MartinWe13** [FreshRSS/FreshRSS#3260]
Hello everyone,

I have the problem that I can't manage to update the feeds FreshRSS via cronjob on the server.

I use the registration via webform. I have activated the option "Allow API access" under "Authentication method". Also I have created an "Authentication token" under "Profile". See screenshots:

https://i.ibb.co/jW6CRCW/Bildschirmfoto-2020-11-14-um-02-34-26.jpg

https://i.ibb.co/Y3FTqm3/Bildschirmfoto-2020-11-14-um-02-34-37.jpg

My URL looks like this:

https://my.domain.de/i/?c=feed&a=actualize&token=MYTOKEN

But this gives me an Error 404. If I add the folder "/p/", my URL looks like this

https://my.domain.de/p/i/?c=feed&a=actualize&token=MYTOKEN

If I call the URL in my browser (logged out or incognito mode), I get the error message "Error 403 - Forbidden" with the remark that I do not have the permission to access this page. The same by the way with the link that is shown to me under the "Authentication token" under "Profile".

https://i.ibb.co/1RDmDcs/Bildschirmfoto-2020-11-14-um-02-49-01.png

Does anybody have an idea? I don't really know any more. :-/

Many greetings
Martin

**Comment by Barrnet** [comment]
I don't think you need use any token. There is a script that can update all feed and you can execute it directly with PHP. Is under app/actualize_script.php

**Comment by math-GH** [comment]
@MartinWe13 Is it still an issue? Will https://freshrss.github.io/FreshRSS/en/admins/08_FeedUpdates.html help you?
