### ISSUE TITLE
Optional STDERR output for cli/export-opml-for-user.php

### ISSUE THREAD

**Issue by dmitryzykov** [FreshRSS/FreshRSS#3261]
Hi there.

I'm trying to export opml, as part of backup procedure, from outside of docker container by command:
`docker exec -it freshrss_freshrss_1 php /var/www/FreshRSS/cli/export-opml-for-user.php --user username`
and I got an invalid xml as an output, because that script will add extra output information to STDERR at beginning and end of script.
```
docker exec -it freshrss_freshrss_1 php /var/www/FreshRSS/cli/export-opml-for-user.php --user dmitry
FreshRSS exporting OPML for user “dmitry”…
<?xml version="1.0" encoding="UTF-8"?>
<opml version="2.0">
  ...
</opml>
Result: success
```

- Is that possible to change cli behavior to output to STDERR only when the error really happen? 
And don't print: `FreshRSS exporting OPML for user “dmitry”…` and `Result: success`
- Or keep current output with `--verbose` 
- Or at least implement `-q` or `--quite` to disable any msgs, except opml output?

**Comment by Alkarex** [comment]
The OPML is on STDOUT, while the other information is on STDERR. Success/Error can be determined by exit code.

Try:

```sh
docker exec freshrss_freshrss_1 cli/export-opml-for-user.php --user dmitry 2>/dev/null
```

**Comment by dmitryzykov** [comment]
@Alkarex 
Thanks for solution. It helped me. 

I'll keep command, might be helpful if someone get there:
daily cron which export opml file to object storage like s3 (I'm using oracle cloud with always free 20gb tier) 
```bash
02 4 * * * docker exec -it freshrss_freshrss_1 php /var/www/FreshRSS/cli/export-opml-for-user.php --user username | curl -X PUT -d@- https://objectstorage.cloudprovider/bucket/path/to/opml.xml
```
