### ISSUE TITLE
[Feature Request] "Show all" default option for labels

### ISSUE THREAD

**Issue by Maeglin73** [FreshRSS/FreshRSS#3263]
There's already an option to default to showing all articles when viewing favorites. Would it be possible to add a similar option for labels as well? Coming from Feedly, I like having unread-only as the default view and use favorites to save articles, but then I categorize those favorites using labels, or what Feedly calls "boards".

**Comment by Alkarex** [comment]
Good idea. PR welcome

**Comment by aledeg** [comment]
Should we link the 2 with one option or should we have 2 separate options?
I feel that it will be more understandable if the behavior is identical for favorites and labels.

**Comment by Maeglin73** [comment]
That would work for me, at least. Don't know about others.

**Comment by Alkarex** [comment]
> 
> 
> Should we link the 2 with one option or should we have 2 separate options?
> I feel that it will be more understandable if the behavior is identical for favorites and labels.

@aledeg Indeed, I think so too, and also limits the growing number of options...
