### ISSUE TITLE
1.17.0: optimisation : error 503 

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#3264]
Hi,
Since I've upgraded to 1.17.0 :
1/ click on "optimiser la base de données"  p/i/?c=entry&a=optimize leads to an error 503. 
2/ click on "purger maintenant" doesn't purge anything (but no error message displayed). Does it normally purge everything or does it check the "archivage" rules to comply with it ?

I can't find a log for this.

Thanks

**Comment by Alkarex** [comment]
Hello,
What database do you use, on which system? Do you have some kind of proxy in front of FreshRSS?
This error is probably due to a timeout.

*Purger maintenant* complies with archiving rules (which are otherwise randomly executed during refresh).

**Comment by ghost** [comment]
Hi,
Voici les détails de l'installation sur un serveur mutualisé :

    Serveur : Localhost via UNIX socket
    Type de serveur : MariaDB
    Version du serveur : 10.3.27-MariaDB - MariaDB Server
    Version du protocole : 10
    Jeu de caractères du serveur : cp1252 West European (latin1)
 Version du client de base de données : libmysql - 5.6.43
Extension PHP : mysqli curl  mbstring 
Version de PHP : 7.3.6 

Je n'ai pas trouvé de log et à ma connaissance il n'y a pas de proxy

Merci

**Comment by Alkarex** [comment]
I could not reproduce the error.
What server are you using? How long time before you get the error after you click on the button?

**Comment by aledeg** [comment]
@lmjst Is this issue still relevant? The version 1.18 has been release recently, it might fix your problem.

**Comment by ghost** [comment]
Hi, yes I've still the issue with version 1.18. It may be a problem of rights on p/i/?c=entry&a=optimize but I don't know why.
Otherwise the new version has speed up the application. It's really much faster for feeds updating 
Thanks

**Comment by Alkarex** [comment]
I cannot reproduce with MariaDB.
Are you using Apache, nginx, something else?
Maybe you could check whether you do not hit a memory exhaustion or timeout?

**Comment by math-GH** [comment]
any news from @lmjst ?

**Comment by ghost** [comment]
Long time, 
anyway with  FreshRSS 1.19.2. I don't have the error anymore (and I've changed hosting)
