### ISSUE TITLE
does freshrss keep removed feeds and their post?

### ISSUE THREAD

**Issue by rezad1393** [FreshRSS/FreshRSS#3265]
description :
I have removed a youtube channel feed from freshrss.
I have a bad internet connection (shared td-lte with low speed) and I use a proxy to get to blocked sites like youtube, so many times the feeds timeout.

now after sometime I added the same feed back.
first time I added it gave a network error (which is on my net fault) but next time is succeeded and added the feed.
but the feeds post are from a month ago (last time I had that feed) and also using actualize doesn't get the new posts but doesn't give errors either so from freshrss user perspective the feed doesn't have new post but that feed actually does have new post.

now there are two issues.
why the freshrss doesn't remove deleted feed's post from DB and also why the actualize button (please change this button name to get new feeds or something better) doesn't get new posts?

**Comment by Alkarex** [comment]
Hello,
Articles and feed are immediately removed from database. However, there is also a local disk cache (shared between users) that lasts between 15min and 2h by default. In your case, there is maybe a problem with cache logic, either due to a local bug or a combination with problematic upstream HTTP headers. That would require a bit of debugging (starting with a `curl -v` of your proxy response).

Note that you can increase timeout value in FreshRSS feed settings (also available when adding a new feed).

*Actualize* is already fixed in https://github.com/FreshRSS/FreshRSS/pull/3248

**Comment by rezad1393** [comment]
> Hello,
> Articles and feed are immediately removed from database. However, there is also a local disk cache (shared between users) that lasts between 15min and 2h by default. In your case, there is maybe a problem with cache logic, either due to a local bug or a combination with problematic upstream HTTP headers. That would require a bit of debugging (starting with a `curl -v` of your proxy response).
> 
> Note that you can increase timeout value in FreshRSS feed settings (also available when adding a new feed).
> 
> _Actualize_ is already fixed in #3248

is there a way to remove that cache? is is this ?freshrss/data/cache/ 
can I remove this?
I see this bug with more than one feed (actually all the feeds that I removed and added) 

also what about the second part? "also using actualize doesn't get the new posts but doesn't give errors either so from freshrss user perspective the feed doesn't have new post but that feed actually does have new post." or is it the same bug from cache?

update:removed the cache and it fixed it.

**Comment by rezad1393** [comment]
update on this.
does freshrss use database purge automatically? what about database optimization?
I see them in archiving section but they are manual.

**Comment by Alkarex** [comment]
@rezad1393 At the moment, the purge is automatic, database optimisation is not

**Comment by Alkarex** [comment]
P.S. We have a command line method for database optimisation, see https://github.com/FreshRSS/FreshRSS/tree/master/cli

**Comment by math-GH** [comment]
@rezad1393 : Are your questions answered?

**Comment by rezad1393** [comment]
> @rezad1393 : Are your questions answered?

whatever it was I dont get it I think.
so ....
