### ISSUE TITLE
How to stop using the dev version?

### ISSUE THREAD

**Issue by uraza** [FreshRSS/FreshRSS#3267]
Hi.

For some reason, I installed FreshRSS version 1.17.1-dev.
I probably went too fast and downloaded the zip from the repo instead of the "Releases" page.
Although I did not encounter any issue so far, I would prefer to use the "stable" version instead. :)

What is the easiest way to get back to a "stable" version : can I just wait until the next "stable" version is released?
I am worried that the integrated update management tool will always suggest dev versions.

Thanks for your inputs.

Jérémy

**Comment by siSSSou** [comment]
I also do wonder how to get back to stable branch with git ? I mainly ask if I can break anything when I revert back...

**Comment by Alkarex** [comment]
@siSSSou The best is to stay as you are until the next release (1.18.0).
Otherwise you can just checkout the tag '1.17.0' from git (it should be safe to go back to 1.17.0 but it safer to stay as you are if you are not experiencing any bug)

**Comment by siSSSou** [comment]
> @siSSSou The best is to stay as you are until the next release (1.18.0).
> Otherwise you can just checkout the tag '1.17.0' from git (it should be safe to go back to 1.17.0 but it safer to stay as you are if you are not experiencing any bug)

OK thanks for the tip ;-)
