### ISSUE TITLE
[solved]bug? I get a lot of "cURL error 6: Could not resolve host"

### ISSUE THREAD

**Issue by rezad1393** [FreshRSS/FreshRSS#3270]
for example:
cURL error 6: Could not resolve host: www.ghacks.net [https://www.ghacks.net/feed/]
I get it for a lot of sites. even websites that I set to get feeds at one hour intervals.
I use openwrt and I dont get server not found on firefox which I use a lot.
how can I be sure this is not a freshrss bug. because I installed     1.17.1-dev for testing parallel connection feature.

can it be this feature's bug?

update:
I think it was systemd-resolved fault
disabled that and I dont get this error anymore

**Comment by Alkarex** [comment]
Thanks for the feedback. Sorry for the delay but indeed, this is not a type of bug due to FreshRSS. Good that you found a fix
