### ISSUE TITLE
Automatic Feed Updating issue on Synology NAS

### ISSUE THREAD

**Issue by nmo-nollivier** [FreshRSS/FreshRSS#3277]
Hello, 

I installed FreshRSS on my Synology NAS and it works well, except an issue with the Automatic Feed Updating. 

I used the Synology native Task scheduler to execute the cron every 20 minutes, with the script below. The task is executed by the root user. 

`sudo -u http /path-my-php /volume1/path-to-my-site-root/FreshRSS/app/actualize_script.php`

But with these settings, the execution returns the error following error for each feed updated. 

> /bin/cp: cannot create regular file '/tmp/synoproxy.conf': Permission denied

I tried to removing `sudo -u http` from my script so the cron is executed as root, and like that is works well. 

Here is the complete output when it goes wrong: 

> Tâche : FreshRSS Feed Update
Heure de début : Sun, 13 Dec 2020 17:20:07 GMT
Heure d’arrêt : Sun, 13 Dec 2020 17:20:21 GMT
État actuel : 0 (Normal)
Sortie standard/erreur :
FreshRSS starting feeds actualization at 2020-12-13T16:20:09+00:00
FreshRSS actualize user1...
/bin/cp: cannot create regular file '/tmp/synoproxy.conf': Permission denied
FreshRSS actualize user2...
/bin/cp: cannot create regular file '/tmp/synoproxy.conf': Permission denied
/bin/cp: cannot create regular file '/tmp/synoproxy.conf': Permission denied
/bin/cp: cannot create regular file '/tmp/synoproxy.conf': Permission denied
/bin/cp: cannot create regular file '/tmp/synoproxy.conf': Permission denied
/bin/cp: cannot create regular file '/tmp/synoproxy.conf': Permission denied
/bin/cp: cannot create regular file '/tmp/synoproxy.conf': Permission denied
/bin/cp: cannot create regular file '/tmp/synoproxy.conf': Permission denied
/bin/cp: cannot create regular file '/tmp/synoproxy.conf': Permission denied
/bin/cp: cannot create regular file '/tmp/synoproxy.conf': Permission denied
/bin/cp: cannot create regular file '/tmp/synoproxy.conf': Permission denied
/bin/cp: cannot create regular file '/tmp/synoproxy.conf': Permission denied
/bin/cp: cannot create regular file '/tmp/synoproxy.conf': Permission denied
/bin/cp: cannot create regular file '/tmp/synoproxy.conf': Permission denied
FreshRSS actualize user3...
FreshRSS actualization done for 3 users, using 6.00 MiB of memory, in 0 day(s), 0 hour(s), 0 minute(s) and 11 seconds.
Results: 
user1 OK
user2 OK
user3 OK
End.

--
Precision: 
Synology DSM comes with more than one PHP instance and if using the classic php command, it execute php 5.6 included in DSM, not the PHP version and settings defined for each PHP profile created in Web Station. So I used the attached method in order to user the good PHP profile. 

This method works well with the Nextcloud CLI for instance. 
Could that be the cause of my issue, or is there anything else wrong? 

[How to fix PHP 7 bash error to update Nextcloud on Synology- - Hackabee.pdf](https://github.com/FreshRSS/FreshRSS/files/5685034/How.to.fix.PHP.7.bash.error.to.update.Nextcloud.on.Synology-.-.Hackabee.pdf)

Thanks 🙏

**Comment by Alkarex** [comment]
Hum, neither the `cp` command nor the `synoproxy.conf` file come from FreshRSS.
But despite the errors in the output, does the job actually work (new articles retrieved)?

An idea: it could potentially be related to a problematic `syslog`.
See `./FreshRSS/constants.php` (some values can be redefined in `./FreshRSS/constants.local.php`)

**Comment by nmo-nollivier** [comment]
Hello, 

> But despite the errors in the output, does the job actually work (new articles retrieved)?

Yes, the feeds are updated despite the error. 

I will look at what you suggest. 

Thanks

**Comment by nmo-nollivier** [comment]
Hello, 

I look further into my issue, and I don't figure out which values should I change in `./FreshRSS/constants.local.php`. 

But what I saw is that, the error _/bin/cp: cannot create regular file '/tmp/synoproxy.conf': Permission denied_ occurs only when a feed is successfully updated. When a feed update fails, for instance because of an issue with URL or the XML from de website, the Update script output details it explicitly. Moreover, when no feed are updated — because they are not due to be updated —, there's no error. 

So I think it is with Web Station or Synology built in proxy that something goes wrong. 🤔

**Comment by nmo-nollivier** [comment]
Hum… I will check in few days, but it seems the last Synology DSM Update I installed this afternoon, has actually solved the issue. 🧐

**Comment by nmo-nollivier** [comment]
I confirme: the issue is solved since the last DSM update (DSM 6.2 Update 3)!

**Comment by Alkarex** [comment]
@nollivier Super, merci pour le retour 🎄
