### ISSUE TITLE
Automatic actualize

### ISSUE THREAD

**Issue by wankio** [FreshRSS/FreshRSS#3278]
Well, i'm just running FreshRSS on windows with Xampp (Apache Service installed, so i dont need to start Xampp

I can access http://localhost/FreshRSS-master , manual actualize or using custom js and let that tab opened, so it will clicked on actualize.btn 5mins each. But it still need web browser opened, can it automatic actualize without web browser opened ? 

Thank

**Comment by Alkarex** [comment]
For automatic update, you need to set up a background cron job. In other words, we have a command-line method, which can be called by a scheduled task in your operative system (in your case, see *Windows Task Scheduler*).
We also have some Docker images, which should run fine on Windows, and contain everything (also Apache and automatic refresh).

https://freshrss.github.io/FreshRSS/en/admins/08_FeedUpdates.html
or https://github.com/FreshRSS/FreshRSS/tree/master/cli
