### ISSUE TITLE
Assign labels automatically based on article title, content, and tags

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#3279]
Hello,

Is it possible to assign labels automatically based on title, content, and tags?

For example: News article with 'Games' in the title > Assign it automatically to label 'Games'.
I think this feature is really important. I can't organize my RSS feeds without this.

**Comment by Alkarex** [comment]
Hello,
This is not yet possible without doing an extension, but this is a feature I also want/need, so it will come :-)

**Comment by 1001Musik** [comment]
I'm using Freshrss on a Qnap with Docker.
I have currently created a filter with many terms. Thus I can display and delete all articles with one application of the filter.

However, it is cumbersome to expand one filter further and further with OR intitle:. It would make sense here if there was a window in which the terms can be listed one below the other.
Furthermore, I would like the filter to work automatically and to mark the articles as read or delete them.
After importing the RSS addresses, I have to go to the subscriber administration and change all 500 feeds. For many of them, I don't want them to appear in the main feed.
Is there a chance of implementation here in the future?
My filter currently looks like this and should be expanded.
intitle:android OR intitle:whatsapp OR intitle:Nintendo OR intitle:Apple OR intitle:Netflix OR intitle:Podcast OR intitle:iPhone OR intitle:Podcast OR intitle:Xiaomi OR intitle:Oneplus OR intitle:Smartwatch OR intitle:tefal OR intitle:Google Fotos OR intitle:Motorola OR intitle:Honor OR intitle:Harry Potter OR intitle:xbox OR intitle:Kurzfilm OR intitle:Pixel OR intitle:itunes OR intitle:Corona

**Comment by Alkarex** [comment]
Ready for testing https://github.com/FreshRSS/FreshRSS/pull/5954
