### ISSUE TITLE
Liste des lecteurs RSS mobiles

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#328]
> Pour utiliser l'API, lire https://github.com/FreshRSS/FreshRSS/issues/443#issuecomment-36666133

Pour aider l'écriture de l'API FreshRSS https://github.com/FreshRSS/FreshRSS/issues/13, faire une liste des lecteurs RSS mobiles (par exemple sous Android https://github.com/FreshRSS/FreshRSS/issues/200, iOS), et en particulier les applications permettant l'utilisation d'une source auto-hébergée :
- News+ https://github.com/noinnion/newsplus
  - https://play.google.com/store/apps/details?id=com.noinnion.android.newsplus
  - gReader https://play.google.com/store/apps/details?id=com.noinnion.android.greader.reader
- PaperBoy https://play.google.com/store/apps/details?id=com.dottedcircle.paperboy
- FeedMe https://play.google.com/store/apps/details?id=com.seazon.feedme
- NewsFeed https://play.google.com/store/apps/details?id=com.smedilepaolo.newsfeed
- Sismics Reader https://play.google.com/store/apps/details?id=com.sismics.reader

**Comment by yafp** [comment]
Hi,
my french is very limited - what clients would you recommend for Android?

Best regards

**Comment by Alkarex** [comment]
@macfidelity I personally use News+ (https://play.google.com/store/apps/details?id=com.noinnion.android.newsplus.extension.google_reader with https://play.google.com/store/apps/details?id=com.noinnion.android.newsplus )

**Comment by wilfried18** [comment]
@macfidelity J'utilise depuis le début easyrss , et je le trouve trés bien (opensource) alors que news+ @Alkarex me contredira si ce n'est pas vrai , mais il semblerais que se soit une application privatrice

**Comment by Alkarex** [comment]
@wilfried18 Yes indeed, News+ is not open source, while my EasyRSS fork is fully open source and without any tracking / advertisement / unneeded permission. EasyRSS is though not (yet) as good, for instance with a less efficient synchronisation mechanism.

**Comment by yafp** [comment]
Thanks for the responses.

Regarding EasyRSS - somehow i dont understand how to set that android application up. It asks just for a "google Reader Account" and a "password" - while i would expect something like
- server
- username
- password

**Comment by marienfressinaud** [comment]
@macfidelity > for EasyRSS you have to use the fork by @Alkarex. It is available at https://github.com/Alkarex/EasyRSS/tree/master/Release

**Comment by yafp** [comment]
Bonjour tout le mondes

@marienfressinaud
Thanks i got the forked version of EasyRSS now

@all:
am i assuming right that i should only allow API access using an account with administrative rights - and after that all users should be allowed to access the installation using the android client mentioned above? or do i need to set additional settings in FreshRSS for enabling client-access?

Thanks in advance

**Comment by marienfressinaud** [comment]
You're almost right! You also need to set a new (API) password on the profile page. You should also have a look to [explanations of @Alkarex](https://github.com/FreshRSS/FreshRSS/issues/443#issuecomment-36666133).

By the way, there is no "s" at "tout le monde" ^^ (one of the many French difficulties!)

**Comment by yafp** [comment]
@marienfressinaud: merci - got it working now

**Comment by wilfried18** [comment]
@Alkarex Concernant ton envie de publier sur Fdroid , si tu n'a toujours pas de retours du devs , tu devrais pas renommé ton application (histoire qu'on sache que c'est bien toi qui en est a l'origine (pas trop difficile de trouver un nom ?)

**Comment by Alkarex** [comment]
@wilfried18 Oui, il faut que je m'en occupe https://github.com/Alkarex/EasyRSS/issues/4 Je propose "InnocentRSS" :-)

**Comment by Draky50110** [comment]
"FreshRSS Mobile" ?
FreshMobile ?
:)

**Comment by Alkarex** [comment]
@Alwaysin I have just made a [new version of EasyRSS](https://github.com/Alkarex/EasyRSS) with support for TLSv1.1 and TLSv1.2 in Android 4.1+

**Comment by Alwaysin** [comment]
Thanks, will give it a try when I have time :D

**Comment by Alkarex** [comment]
@wilfried18 @konfiot @Draky50110 I have started the process of publishing to F-Droid https://github.com/Alkarex/EasyRSS/issues/4
Any help/comment welcome.

**Comment by Draky50110** [comment]
My webhost doesn't pass the test (which in another issue ?) so... will not test.

**Comment by Alkarex** [comment]
@Draky50110 Feel free to open another ticket to try to solve the issue with your Web host.

**Comment by Alkarex** [comment]
EasyRSS is now available in F-Droid :-)
https://f-droid.org/repository/browse/?fdid=org.freshrss.easyrss

**Comment by yafp** [comment]
@Alkarex 
Thanks for the update

**Comment by nikaro** [comment]
Hello,

What do you think about publishing EasyRSS on the Play Store ?

**Comment by Alkarex** [comment]
@nikaro Yes, this is possible. I was hopping the original author could do that, but it does not look like he is coming back.

**Comment by Draky50110** [comment]
Just give a new name like EasyRSS 2 and publish it ?

**Comment by Kaishiyoku** [comment]
Hi, is there any RSS app compatible with the FreshRSS API?

**Comment by Alkarex** [comment]
@Kaishiyoku See a bit higher up https://github.com/FreshRSS/FreshRSS/issues/328#issuecomment-71374644
News+, EasyRSS, and probably some more (FreshRSS has an API compatible with Google Reader, and an extension compatible with TT-RSS, so clients for these APIs should work)

**Comment by Kaishiyoku** [comment]
Thank you. Where can I get News+? I can’t find it in the Google Play Store.

**Comment by Alwaysin** [comment]
Here it is : https://play.google.com/store/apps/details?id=com.noinnion.android.newsplus

You will also need the "Google Reader Clone" extension : https://play.google.com/store/apps/details?id=com.noinnion.android.newsplus.extension.google_reader

**Comment by Draky50110** [comment]
Just tested News+ with extension but failed at login.
What is the URL of my server ?
http://domain.com/freshrss/ or do we need to add something like "/p/i" or something else ?
Was working ok with EasyRSS fork but don't remember which URL I used...

**Comment by Alkarex** [comment]
@Draky50110 https://github.com/FreshRSS/FreshRSS/issues/957#issuecomment-133581712

**Comment by Alwaysin** [comment]
Does someone know a working application on an iOS device?

**Comment by Alkarex** [comment]
@Alwaysin I have not looked (I do not own anything Apple), but you could search for (open source) clients for iOS with support for Google Reader API. These ones comes up, but not tested http://www.chebinliu.com/projects/iphone/feeddler-rss-reader/ , http://reederapp.com/ . More on http://alternativeto.net/software/feeddler-rss-reader/?platform=iphone . I would be interested to know, and I can tune the FreshRSS API if some bits are lacking to support a client.

**Comment by Alwaysin** [comment]
First one has dropped support for Google Reader, second one is paid (and doesn't seem to have Google Reader syncing ability), and I haven't found anything suitable on alternativeto.net website :(

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/issues/1406

**Comment by Alkarex** [comment]
FeedMe compatibility https://github.com/FreshRSS/FreshRSS/pull/1774

**Comment by GLLM** [comment]
Hi all,

just wondering if anyone has found a new Android client (ideally opensource) ? Just curious ...
i'm still stuck on EasyRSS which works btu is buggy at times, and could really undergo some reshaping/designing :)

Thanks
GLLM

**Comment by Frenzie** [comment]
How is it buggy precisely?

**Comment by marienfressinaud** [comment]
Actually, @AugierLe42e is working on a new app :) https://diaspodon.fr/@AugierLe42e/101516534315204663

**Comment by Frenzie** [comment]
Actually never mind my question, sometimes the "unread" view in EasyRSS becomes a little… odd and you have to resync a bit. It didn't even bother me enough to look at the code, haha.

**Comment by gpion** [comment]
Since that thread is rather old, I was wondering what Android clients are recommended today.
I just tried Feedme but I'm unable to configure it (ref : https://github.com/seazon/FeedMe/issues/688)

**Comment by Frenzie** [comment]
I still like EasyRSS but there's a big list in the readme these days! ;-)

**Comment by gpion** [comment]
> I still like EasyRSS

Thanks, will test it!
 _edit_
Looks not updated since 3 years, still alive?

**Comment by gpion** [comment]
Seem dead : https://pursuer.me/2024/01/14/retriring-easyrss/

**Comment by Frenzie** [comment]
The relevant EasyRSS is <https://github.com/Alkarex/EasyRSS/tree/master>, <https://f-droid.org/packages/org.freshrss.easyrss/>, sorry about that.

> Looks not updated since 3 years, still alive?

Things that work don't need to be updated.

**Comment by gpion** [comment]
> Things that work don't need to be updated.

Unfortunately, do not work for me 😕
In the service URL field I've tried with the main URL and the API URL without success (connexion failed)
(and the password is OK since I connect with it on the web interface)

**Comment by Frenzie** [comment]
Apparently there's one minor issue with EasyRSS: it won't show you your currently configured API URL.

Anyway, I believe you should put the address ending with `api/greader.php`.

> (and the password is OK since I connect with it on the web interface)

That might be the problem. You need to set a separate API password. This dialog is under Settings → Profile.
![image](https://github.com/FreshRSS/FreshRSS/assets/202757/b0a63642-36f3-47f7-9c5b-536d06bca34e)

**Comment by gpion** [comment]
> Apparently there's one minor issue with EasyRSS: it won't show you your currently configured API URL.
> 
> Anyway, I believe you should put the address ending with `api/greader.php`.

My FreshRSS WEB acces URL is https://\<_fqdn_\>/FreshRSS/
In the address field I've put https://\<_fqdn_\>/FreshRSS/api/greader.php (which give a HTTP 404 error BTW)


> 
> You need to set a separate API password. 

that what I've done too (I even reset the API password and tested with the new one)

**Comment by gpion** [comment]
I had forgot the "/p/ in the API url (now replaced with https://\<_fqdn_\>.myds.me/FreshRSS/p/api/greader.php, no more HTTP 404, just displays "OK")
But same error after adding it

**Comment by Frenzie** [comment]
The exact address is listed on the API page (under where you set the API password).

Edit: but "OK" is OK.  GH hadn't shown me the second reply.

**Comment by gpion** [comment]
> The exact address is listed on the API page (under where you set the API password).

That one doesn't ends "api/greader.php" as you told me it should.

**Comment by Frenzie** [comment]
> That one doesn't ends "api/greader.php" as you told me it should.

No, I mean if you click that link it will state the exact address. In principle it should be identical to the same thing with `greader.php` at the end but what's there will be the exact and proper address. But anyway, that doesn't matter because if it says OK you have the correct address already.

**Comment by gpion** [comment]
Anyway whatever URL I put in the field it fails.

**Comment by Frenzie** [comment]
Maybe @Alkarex has any ideas, but he probably won't reply this week.

But fails how?

**Comment by gpion** [comment]
> But fails how?
 
![iMarkup_20240324_194516.png](https://github.com/FreshRSS/FreshRSS/assets/2971216/53b0e804-c1e7-4189-b39e-c8cdc21283b0)

**Comment by gpion** [comment]
![iMarkup_20240324_194516.png](https://github.com/FreshRSS/FreshRSS/assets/2971216/26ba9725-14c8-41d3-bd27-19836368e239)

**Comment by gpion** [comment]
> But fails how?

![iMarkup_20240324_194516.png](https://github.com/FreshRSS/FreshRSS/assets/2971216/50dfc979-f944-4f1b-aebd-d702eb7f9d22)

**Comment by Draky50110** [comment]
FeedMe and the fork of EasyRSS are those I tested some monthes ago and still working.
