### ISSUE TITLE
why problem in new FreshRSS

### ISSUE THREAD

**Issue by panumpornnon** [FreshRSS/FreshRSS#3280]
problem in 2 version( [1] localhost for test before to real host, [2] real host)
[1] my after install FreshRSS new version (FreshRSS 1.17.0)  
- show php warning : 
![03-step-2-Screenshot_2020-12-23 Installation · FreshRSS](https://user-images.githubusercontent.com/22130038/102947077-0ebee580-44f5-11eb-9247-ff65baaa7b26.png)

- resources localhost
 Windows 10 Pro
 apache httpd-2.4.35
 mysql-5.7.24
 php 7.2.19

[2] and FreshRSS is 1.15.4-dev.)
Blast! Update server cannot be found. [https://update.freshrss.org?v=1.15.4-dev]  
show php warning :
PHP Warning:  Invalid argument supplied for foreach() in C:\web\www\frss2021\app\Models\CategoryDAO.php on line 354
PHP Warning:  Invalid argument supplied for foreach() in C:\web\www\frss2021\app\Controllers\indexController.php on line 58
PHP Warning:  Invalid argument supplied for foreach() in C:\web\www\frss2021\app\layout\aside_feed.phtml on line 58
PHP Warning:  Invalid argument supplied for foreach() in C:\web\www\frss2021\app\layout\aside_feed.phtml on line 73
- my edit {folder freshrss}\lib\lib_install.php
by insert  error_reporting(error_reporting() & ~E_NOTICE & ~E_WARNING);  top code for hidden warning.
- result
![01-01-Screenshot_2020-12-23 Your RSS feeds · egp-2020-suratcity go th](https://user-images.githubusercontent.com/22130038/102947026-f222ad80-44f4-11eb-9f7f-6943be89a35f.png)

- have data 
![01-02-Screenshot_2020-12-23 www suratcity go th localhost frss2020 freshrss_admin3_entry phpMyAdmin 5 0 2](https://user-images.githubusercontent.com/22130038/102947040-f949bb80-44f4-11eb-861f-c1cd6ca393d8.png)

- resouces server
Windows Server 2016 Standard
MariaDB 5.5.5-10.2.8
php 7.4.4
micosoft-iis/10.0

[1] and [2]
in update feed
PHP Fatal error:  Uncaught Error: Call to a member function bindParam() on bool in {folder freshrss}\app\Models\FeedDAO.php:263
Stack trace:
#0 C:\web\www\frss2021\app\Models\Entry.php(118): FreshRSS_FeedDAO->searchById()
#1 C:\web\www\frss2021\app\views\index\normal.phtml(35): FreshRSS_Entry->feed()
#2 C:\web\www\frss2021\lib\Minz\View.php(88): include('C:\\web\\www\\frss...')
#3 C:\web\www\frss2021\lib\Minz\View.php(110): Minz_View->includeFile()
#4 C:\web\www\frss2021\app\layout\layout.phtml(55): Minz_View->render()
#5 C:\web\www\frss2021\lib\Minz\View.php(88): include('C:\\web\\www\\frss...')
#6 C:\web\www\frss2021\lib\Minz\View.php(101): Minz_View->includeFile()
#7 C:\web\www\frss2021\lib\Minz\View.php(68): Minz_View->buildLayout()
#8 C:\web\www\frss2021\lib\Minz\Dispatcher.php(54): Minz_View->build()
#9 C:\web\www\frss2021\lib\Minz\FrontController.php(84): Minz_Dispatcher->run()
#10 C:\web\www\frss2021\p\i\index.php(69): Minz_FrontController->run()
#11 {main}
  thrown in {folder freshrss}\app\Models\FeedDAO.php on line 263

define : db setting:  mysql, user, password is correct.
how to freshrss work!
thank you.

**Comment by Alkarex** [comment]
Hello,
How did you install FreshRSS, on which platform, and which database?

**Comment by math-GH** [comment]
8 months later.... no answer. Close it?
