### ISSUE TITLE
Client didn't get new articles (nginx nonce)

### ISSUE THREAD

**Issue by Offerel** [FreshRSS/FreshRSS#3282]
I have this configuration now since some months without any issue. But starting as of today the mobile client im using (FeedMe) didn't get new articles anymore. However the FreshRSS web client displays all articles fine.

Asca workaround, I have removed some articles in FreshRSS. After that, FeedMe could download new articles again.

I think, something is send via API calls in some wrong way.

It's there some way to identify the issue a little bit better, so that we can create a fix? I didn't find any useful information in current logfiles.

**Comment by Alkarex** [comment]
Hello,
Could it be that you have a greater number of (unread) articles now?
Check your Web server logs for any error. See also the API logs in `./FreshRSS/data/users/_/log_api.txt`
To enable API debug logs, you can uncomment the following two lines:

https://github.com/FreshRSS/FreshRSS/blob/abfbeb6b71a5144145bd39beb6b774e1fce0c94b/p/api/greader.php#L930-L931

**Comment by Offerel** [comment]
If I remember correctly, I could find in FreshRSS on the web, approximately the number to be expected, unread articles. After deleting individual articles, they were synchronized again to FeedMe. 

The file `./FreshRSS/data/users/_/log_api.txt` is empty at 0 bytes, before i uncomented both lines. 

```
/media/stick/www/freshrss/data/users/_ # ls -lah
-rw-rw-r-- 1 www-data www-data    0 Jul 25  2019 .gitignore
-rw-rw-r-- 1 www-data www-data  309 Jul 25  2019 index.html
-rw-r--r-- 1 www-data www-data    0 Dez 24 07:49 log_api.txt
-rw-r--r-- 1 www-data www-data  587 Dez 24 11:45 log_pshb.txt
-rw-r--r-- 1 www-data www-data    0 Dez 24 07:49 log.txt
```

The nginx error.log is empty for today and access.log contains nothing special regarding FreshRSS. PHP error.log is also empty. There are only some fragments of test for for https://github.com/Offerel/SyncMarks-Webapp/tree/dev, but nothing regarding FreshRSS. 

Currently, synchronization works again without any issues. I have uncommented your recommended lines now and will check tomorrow, if the issue comes up again.

**Comment by Offerel** [comment]
Some minutes ago, I had the same issue again. Both lines are uncommented, but log_api.txt is empty.

But there is a folder ./FreshRSS/data.back/users/_/ with the same file, which has 40kb. Timestamp is from 24.12, today we 26.12...

If you wish, I can send the file privately to you. Is there some private way to do that?

I can also try to simulate the App request, maybe I can see what I get as response. Is it possible that you maybe know, how I have to formate such a request?

**Comment by Alkarex** [comment]
@Offerel You can find [my e-mail address there](https://alexandre.alapetite.fr/cv/).

You can see examples of accessing the API via curl at the bottom of https://freshrss.github.io/FreshRSS/en/users/06_Mobile_access.html

And then adapt to do the same than FeedMe according to log_api.txt

**Comment by Alkarex** [comment]
Just to debug, could you try with another client (using the GReader API) to check whether there is the same problem?
https://github.com/FreshRSS/FreshRSS#apis--native-apps (e.g. News+ , first line)

**Comment by Alkarex** [comment]
I can seen in the logs that we are generating an invalid JSON. I need to find out how that is possible, despite using `json_encode()`.

Example of wrong JSON (invalid quote)

```json
{
	"id": "tag:google.com,2005:reader/item/0005b75a7b885c80",
	"crawlTimeMsec": "1608974131027",
	"timestampUsec": "1608974131027072",
	"published": 1608973200,
	"title": "Xiaomi kopiert Apple schon wieder – diesmal zu unserem Nachteil",
	"summary": {
		"content": "<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\" \"http://www.w3.org/TR/REC-html40/loose.dtd\">\n<html><body><figure><img width=\"1500\" height=\"900\" src=\"https://images.weserv.nl/?url=i2.wp.com%2Fwww.smartdroid.de%2Fwp-content%2Fuploads%2F2020%2F12%2Fxiaomi-mi-11-blau.jpg%3Ffit%3D1500%252C900%26ssl%3D1\" alt=\"Xiaomi Mi 11 Blau\" loading=\"lazy\"></figure><p>Xiaomi ist mit seinen Marktanteilen auf jeden Fall <a href=\"https://www.smartdroid.de/ist-es-gar-nicht-xiaomi-die-stark-vom-huawei-untergang-profitieren/\">auf einem guten Weg</a>, wirklich langfristig mit Apple und Samsung konkurrieren zu k&ouml;nnen. Jedenfalls beim Blick auf die nackten Zahlen. Derweil versucht Xiaomi weiterhin genau abzuschauen, was die Konkurrenz eigentlich macht und probiert dann im Anschluss, die guten Dinge schnell zu &uuml;bernehmen. Und selbstverst&auml;ndlich fehlt mit dem kommenden Mi 11 nicht der Schritt hin zu einem Smartphone allein in seiner Verpackung.</p>\n<p>Xiaomi hat aber nicht nur die Verpackung des <a href=\"https://www.smartdroid.de/tag/xiaomi-mi-11\">Mi 11</a> enth&uuml;llt, sondern ein <a href=\"https://weibo.com/2202387347/JAe2y5jlT?from=page_1006062202387347_profile&amp;wvr=6&amp;mod=weibotime&amp;type=comment\" target=\"_blank\" rel=\"noopener\">weiteres Detail</a> zum Lieferumfang. Wie schon Apple vorgemacht hat, folgt auch <a href=\"https://www.smartdroid.de/tag/xiaomi\">Xiaomi</a> dem Beispiel kein Ladeger&auml;t dazuzugeben. Heute h&auml;tte jeder Smartphone-Nutzer bereits eine hohe Anzahl an Ladeger&auml;ten daheim, da braucht es nicht noch weitere. Oder eigentlich erst dann, wenn Nutzer die verbesserten Schnelllade-Funktionen neuer Ger&auml;te nutzen wollen.</p>\n<h2>Xiaomi: Erst gelacht, dann nachgemacht</h2>\n<div><!--[if lt IE 9]><script nonce=" 5hjOoxPr3T1I / D15h + Cp + uifN8mcNQxfhgksK5b + qHY = ">document.createElement('video');</script><![endif]-->\n<video width=\"780\" height=\"439\" preload=\"none\" controls=\"controls\"><source type=\"video/mp4\" src=\"https://www.smartdroid.de/wp-content/uploads/2020/12/xiaomi-mi-11-verpackung-video.mp4?_=1\"></source><a href=\"https://www.smartdroid.de/wp-content/uploads/2020/12/xiaomi-mi-11-verpackung-video.mp4\">https://www.smartdroid.de/wp-content/uploads/2020/12/xiaomi-mi-11-verpackung-video.mp4</a></video></div>\n<p>Nat&uuml;rlich hatte sich auch Xiaomi im Oktober noch lustig dar&uuml;ber gemacht, dass Apple f&uuml;r seine neuen iPhones keine Ladeger&auml;te mehr im Lieferumfang anbietet. Samsung geh&ouml;rte mit zu denen, die ihre damals billigen Lacher <a href=\"https://www.smartdroid.de/laecherlich-samsungs-ladegeraet-witze-werden-zum-boomerang-schon-wieder/\">heute wohl eher bereuen</a>. Man d&uuml;rfte auch bei Xiaomi bereuen, sich &uuml;ber andere lustig gemacht zu haben, nur um deren Schritte dann einfach zwei Monate sp&auml;ter zu kopieren. Es geh&ouml;rt heute aber leider dazu, immer erst mal die Klappe aufzumachen, statt erst den Kopf einzuschalten.</p>\n<blockquote data-width=\"550\" data-dnt=\"true\">\n<p lang=\"en\" dir=\"ltr\"><a href=\"https://twitter.com/hashtag/AppleEvent?src=hash&amp;ref_src=twsrc%5Etfw\">#AppleEvent</a>  <img src=\"https://images.weserv.nl/?url=s.w.org%2Fimages%2Fcore%2Femoji%2F13.0.1%2F72x72%2F1f602.png\" alt=\"&#128514;\"></p>\n<p>It's funny, but I'm willing to bet almost all companies will start following Apple and ditching chargers in the boxes by 2022 <a href=\"https://t.co/wYWzjBryUf\">pic.twitter.com/wYWzjBryUf</a></p>\n<p>&mdash; Arun Maini (@Mrwhosetheboss) <a href=\"https://twitter.com/Mrwhosetheboss/status/1316324163032932352?ref_src=twsrc%5Etfw\">October 14, 2020</a></p></blockquote>\n<p></p>\n<h2>Warum werden Ladeger&auml;te gestrichen?</h2>\n<p>Tats&auml;chlich ist heute davon auszugehen, dass jeder ein Smartphone besitzt und entsprechende Ladeger&auml;te zuhause hat. Das gilt in der Android-Welt nat&uuml;rlich f&uuml;r Ger&auml;te mit USB-C, die seit ein paar Jahren g&auml;ngiger Standard sind. Um Ladeger&auml;te sinnlos mitzuliefern, was unterm Strich nur die Menge an Elektroschrott erh&ouml;ht, werden in Zukunft weitere Smartphone-Hersteller dem Beispiel von Apple folgen. Und wieder hat es keiner gewagt, diesen Schritt eher zu gehen. L&auml;cherlich.</p>\n<blockquote data-secret=\"E2INuirKYJ\"><p><a href=\"https://www.smartdroid.de/laecherlich-samsungs-ladegeraet-witze-werden-zum-boomerang-schon-wieder/\">L&auml;cherlich! Samsungs Ladeger&auml;t-Witze werden zum Boomerang &ndash; schon wieder</a></p></blockquote>\n<p><iframe sandbox=\"allow-scripts allow-same-origin\" security=\"restricted\" title=\"&bdquo;L&auml;cherlich! Samsungs Ladeger&auml;t-Witze werden zum Boomerang &ndash; schon wieder&ldquo; &mdash; SmartDroid.de\" src=\"https://www.smartdroid.de/laecherlich-samsungs-ladegeraet-witze-werden-zum-boomerang-schon-wieder/embed/#?secret=E2INuirKYJ\" data-secret=\"E2INuirKYJ\" width=\"600\" height=\"338\" frameborder=\"0\" marginwidth=\"0\" marginheight=\"0\" scrolling=\"no\"></iframe></p><div class=\"enclosure\"><p class=\"enclosure-content\"><video preload=\"none\" src=\"https://www.smartdroid.de/wp-content/uploads/2020/12/xiaomi-mi-11-verpackung-video.mp4\" data-length=\"891065\" data-type=\"video/mp4\" controls=\"controls\"></video><a download=\"\" href=\"https://www.smartdroid.de/wp-content/uploads/2020/12/xiaomi-mi-11-verpackung-video.mp4\">&#128190;</a></p></div></body></html>\n"
	},
	"alternate": [{
			"href": "https://www.smartdroid.de/xiaomi-kopiert-apple-schon-wieder-diesmal-zu-unserem-nachteil/"
		}
	],
	"categories": ["user/-/state/com.google/reading-list", "user/-/label/Mobil", "user/-/state/com.google/read"],
	"origin": {
		"streamId": "feed/82",
		"title": "SmartDroid.de"
	},
	"enclosure": [{
			"href": "https://www.smartdroid.de/wp-content/uploads/2020/12/xiaomi-mi-11-verpackung-video.mp4",
			"type": "video/mp4",
			"length": 891065
		}
	],
	"author": "Denny Fischer"
}
```

**Comment by Alkarex** [comment]
Hum, @Offerel , could you tell a bit about your setup?
I fear again an nginx bug. This code seems to be generated by a middleware between FreshRSS and the client:

`nonce=" 5hjOoxPr3T1I / D15h + Cp + uifN8mcNQxfhgksK5b + qHY = "`

**Comment by Frenzie** [comment]
Iirc you need to take care of escaping double quotes for PHP's json_encode yourself.

**Comment by Alkarex** [comment]
@Frenzie `json_encode` looks fine. My guess is that something else is adding a `script nonce` in a wrong way after the output of FreshRSS

**Comment by Alkarex** [comment]
Apparently nginx can be compiled to blindly inject CSP nonces https://scotthelme.co.uk/csp-nonce-support-in-nginx/ ...
Such an approach cannot work safely, and is very error prone, just like editing HTML with regex is not a good idea. It reminds me of this famous answer https://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags/1732454#1732454
I guess something like that is the culprit here. Closing, but more information / confirmation would be nice.

**Comment by Offerel** [comment]
Yes, you are right. I'm using a slightly edited version of https://melkfl.es/article/2018/05/csp-nonce/ in my setup. I try to exclude it for the API url. After that, i will watching if the issue will come up again. Hopefully not.

**Comment by Alkarex** [comment]
What I believe is an nginx configuration bug (and a wrong approach) seems to be (mainly) with HTML comments.
We do not actually need to keep HTML comments, so here is a patch https://github.com/FreshRSS/FreshRSS/pull/3288
Please give it a try (will only work for newly retrieved articles)

**Comment by Offerel** [comment]
I have added additionally the patch #3288 to my setup. Currently there are no new article with an embedded script tag, but i will retry, if the named feed will have a new one. I check the output with `curl -s -H "Authorization:GoogleLogin auth=my@mail.com/fsdfsdf9fsdfsdff" 'https://mydomain.de/news/api/greader.php/reader/api/0/stream/contents/reading-list' > articles.json` and the resulting JSON with https://jsonlint.com/. If i find something, i will comment here.

**Comment by Alkarex** [comment]
@Offerel https://www.smartdroid.de/feed/ is an example with `<script` (you can reload the articles in the feed's parameters)
To check JSON validity from command line, `jq` is quite good, e.g. `cat test.json | jq .`
