### ISSUE TITLE
Marquer les articles précédents comme lus

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#329]
Insérer un lien "marquer les articles précédents comme lus" lors du défilement vers le bas avant le chargement d'une nouvelle page d'articles.

Sismics Reader le fait par exemple.

**Comment by Alkarex** [comment]
Less important now that the “mark as read during scroll” option has been reworked, and enabled by default. https://github.com/FreshRSS/FreshRSS/pull/1309

**Comment by math-GH** [comment]
what is left to do here?

**Comment by math-GH** [comment]
ping @Alkarex

**Comment by Alkarex** [comment]
Let's come back to it if we some day add a context menu to entries, with several actions
