### ISSUE TITLE
Support rss to liferea

### ISSUE THREAD

**Issue by christrt9** [FreshRSS/FreshRSS#3291]
I create a FreshRSS and i want to read it like RSS from liferea. I am missing something? 
I try to add it like a source but it said 403 - Forbidden.

**Comment by Alkarex** [comment]
@r00t9 See this comment, which I believe is still correct:
https://github.com/FreshRSS/FreshRSS/pull/2126#discussion_r234439656

I would love to see Liferea add an option for self-hosted systems based on Google Reader API. They already support that API but hard-code the server for e.g. The Old Reader.

**Comment by christrt9** [comment]
@Alkarex  thanks :)

**Comment by math-GH** [comment]
Any updates here about liferea?

Maybe @lwindolf could have a look here, who is maintaining the liferea app on https://github.com/lwindolf/liferea

**Comment by Alkarex** [comment]
Let's test:

* https://github.com/lwindolf/liferea/issues/962#issuecomment-1193186062
* https://github.com/lwindolf/liferea/issues/1113#issuecomment-1193185933

**Comment by math-GH** [comment]
ping @r00t9

**Comment by Alkarex** [comment]
Liferea first version to support FreshRSS is 1.13.9.
The deb files I could find, despite saying 1.13.9, were actually 1.13.8 https://lzone.de/liferea/install.htm
Too many missing dependencies when trying to compile from source on my system.
Feedback from other testers welcome, or ping me when a binary version of 1.13.9 is available.

**Comment by math-GH** [comment]
Any update here?

**Comment by lwindolf** [comment]
@math-GH Recent Liferea versions have generic "Google Reader API" as a source which does allow subscribing to FreshRSS

**Comment by math-GH** [comment]
good to know. It means that we could close this ticket?

**Comment by lwindolf** [comment]
I would say yes.

**Comment by Frenzie** [comment]
Probably should be added here?
https://github.com/FreshRSS/FreshRSS?tab=readme-ov-file#apis--native-apps
