### ISSUE TITLE
Cron Update SQL error: listFeedsOrderUpdate: Malformed communication packet

### ISSUE THREAD

**Issue by rom-1** [FreshRSS/FreshRSS#3293]
Hi,

I am currently switching from TTRSS to FreshRSS, and set up a new FreshRSS install (using MySQL) on my shared hosting webserver. So far everything went well.

The last problem I have is, that when I am trying to run my update cronjob "FreshRSS/app/actualize_script.php" via crontab or manually via CLI, there is no feed updated. I can update the feeds manually using the browser "Update" Button without any issues. Running the php file via CLI also outputs no error ("Results: user OK. End."), but runs really fast (instantly!). In the browser error log I can find the following issues: 
**SQL error listfeedsOrderUpdate: Malformed communication packet**
Screenshot here: [https://i.imgur.com/AowbMSL.png](https://i.imgur.com/AowbMSL.png)

I have no idea where to look for a solution, as updating the feeds manually using the Web GUI seem to work flaweless.

Thanks for any help

**Comment by Alkarex** [comment]
Hello,
Could you give a try with the built-in SQLite instead of MySQL?
Please tell system details: OS version, PHP version, database version.
Try to make sure that you are using the same PHP version / configuration from the browse and from the command line.

**Comment by rom-1** [comment]
Thanks for pointing me into the right direction. Indeed, the CLI/CRONJOB runs with PHP 7.2 and my webserver runs PHP 7.4. Unfortunately I cannot find a binary with PHP 7.4 yet (just opened a support ticket at webhoster) but I found a php7.3 binary which runs fine. 

Problem solved: Switching to a newer PHP Version (7.3/7.4) seems to run without any issues. Thanks a lot.

**Comment by Alkarex** [comment]
Related: https://github.com/FreshRSS/FreshRSS/issues/3191
