### ISSUE TITLE
Issue after latest in application update...

### ISSUE THREAD

**Issue by quella** [FreshRSS/FreshRSS#3300]
I have been running the software for a few months (Chrome) and using the built-in web application update tool in the settings.  Today when I did an update and apply, I was logged out of the application's web interface.  I tried to access to application again using retry, but I kept getting an Error 500.  I opened the web interface again in a different browser (Safari) where I was prompted with the login screen.  Once logged in, I was only presented with a blank white page, no feed or other data on the page.  I did an update to my Pi OS, reboot, and still get the same behavior of a blank screen after I login to the application.  I cleared the cookie on Chrome and seem to not be able to get past the issue after the update was applied; the system only runs FreshRSS, no other software.

I tried to do a CLI export of my feeds using the CLI but I get an error shown below.  Happy to blow away the setup and start fresh, but I would need to first get an export.  Help with either to get me back up would be welcomed.  

Following this CLI info from Git: https://github.com/FreshRSS/FreshRSS/blob/master/cli/README.md

When doing a CLI export I get the following:

> FreshRSS exporting OPML for user “quella”…
PHP Notice:  Undefined offset: 1 in /var/www/freshrss/lib/autoload.php on line 50
PHP Fatal error:  Uncaught Error: Class 'MinzPdo' not found in /var/www/freshrss/lib/Minz/PdoMysql.php:8
Stack trace:
#0 /var/www/freshrss/lib/autoload.php(24): require()
#1 [internal function]: ClassLoader->loadClass('Minz_PdoMysql')
#2 /var/www/freshrss/lib/Minz/ModelPdo.php(67): spl_autoload_call('Minz_PdoMysql')
#3 /var/www/freshrss/app/Services/ExportService.php(30): Minz_ModelPdo->__construct('quella')
#4 /var/www/freshrss/cli/export-opml-for-user.php(19): FreshRSS_Export_Service->__construct('quella')
#5 {main}
  thrown in /var/www/freshrss/lib/Minz/PdoMysql.php on line 8

**Comment by aledeg** [comment]
@quella I've changed recently the auto-loading process. It might be a cache related problem.
I've run the following command without problem:
```docker exec freshrss-dev ./cli/export-opml-for-user.php --user alexis```

Could you try again after clearing your cache?

**Comment by Alkarex** [comment]
Hello @quella 
Thanks for the report and helping us testing the development version.

If you have installed via git, you can revert to a slightly older point, such as da4121cb6cd7700212a935fbb38e9f2a567d3609

Otherwise, fix coming soon :-)

@aledeg I can reproduce:

```sh
docker exec freshrss ./cli/export-opml-for-user.php --user freshrss
```

**Comment by aledeg** [comment]
@Alkarex I tried with your command and I cannot reproduce. Could you clear your cache and restart your container?

**Comment by quella** [comment]
I did clear my cache in Safari and I get the same results after applying the latest update.  I can do an "About" from the login page and I seems to have access to some of the functions (update included), but a few (Archive) and the feeds show only a blank white screen.  Here are a few screen shots if they are helpful.  

<img width="1475" alt="Screen Shot 2020-12-28 at 1 12 15 PM" src="https://user-images.githubusercontent.com/823352/103234972-ed079900-490e-11eb-954e-8786229b762e.png">

<img width="1495" alt="Screen Shot 2020-12-28 at 1 11 47 PM" src="https://user-images.githubusercontent.com/823352/103234992-f7c22e00-490e-11eb-83b9-cc142183cc9a.png">


White Screen when looking any feeds or archive...

<img width="1481" alt="Screen Shot 2020-12-28 at 1 12 01 PM" src="https://user-images.githubusercontent.com/823352/103235008-0577b380-490f-11eb-92ce-e7b745d6e873.png">

**Comment by aledeg** [comment]
@quella Oh! I mean the application cache, not the one in your browser. Sorry, I was not clear.
Please remove everything from the `data/cache` folder with the exception of the `index.html` file.

**Comment by Alkarex** [comment]
@aledeg I suggest we revert https://github.com/FreshRSS/FreshRSS/pull/3283 for now, and make a new test including your upcoming changes https://github.com/FreshRSS/FreshRSS/pull/3299

**Comment by aledeg** [comment]
@Alkarex If you want to, I have no problem. But it works after clearing the cache and restarting docker.

**Comment by quella** [comment]
So I did clear out a number of .spc files in the application's cache folder leaving the index.html intact.  Only thing in that directory.  I did a logout, login from the web browser and I sill seem to get the same behavior of the clean screen after I authenticate correctly to the application.  

After clearing the cache directory, do you want me to reboot the system as well?  Again, it is the only thing running on this Pi.  Happy to troubleshoot or try any suggestions.

**Comment by Alkarex** [comment]
@aledeg It seems to fail consistently with at least MySQL. Seems to work with SQLite.
Here is a fresh new Docker + volume:

```
172.18.0.1 - - [28/Dec/2020:18:37:18 +0000] "GET /i/?c=javascript&a=nbUnreadsPerFeed HTTP/1.1" 200 1135 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
[Mon Dec 28 18:37:28.136339 2020] [php:warn] [pid 19] [client 172.18.0.1:59990] PHP Warning:  Undefined array key 1 in /var/www/FreshRSS/lib/autoload.php on line 50, referer: http://localhost:8080/i/index.php?step=2
[Mon Dec 28 18:37:28.136634 2020] [php:error] [pid 19] [client 172.18.0.1:59990] PHP Fatal error:  Uncaught Error: Class "MinzPdo" not found in /var/www/FreshRSS/lib/Minz/PdoMysql.php:8\nStack trace:\n#0 /var/www/FreshRSS/lib/autoload.php(24): require()\n#1 /var/www/FreshRSS/lib/Minz/ModelPdo.php(67): ClassLoader->loadClass()\n#2 /var/www/FreshRSS/app/Models/Factory.php(73): Minz_ModelPdo->__construct()\n#3 /var/www/FreshRSS/lib/lib_install.php(99): FreshRSS_Factory::createDatabaseDAO()\n#4 /var/www/FreshRSS/app/install.php(168): initDb()\n#5 /var/www/FreshRSS/app/install.php(669): saveStep2()\n#6 /var/www/FreshRSS/p/i/index.php(27): require('...')\n#7 {main}\n  thrown in /var/www/FreshRSS/lib/Minz/PdoMysql.php on line 8, referer: http://localhost:8080/i/index.php?step=2
172.18.0.1 - - [28/Dec/2020:18:37:28 +0000] "POST /i/index.php?step=2 HTTP/1.1" 500 - "http://localhost:8080/i/index.php?step=2" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0"
```

P.S.: And I only tested your PR with SQLite

**Comment by Alkarex** [comment]
Actually https://github.com/FreshRSS/FreshRSS/pull/3297 needs to be reverted to.
Let's revert to a working state and re-introduce those changes more carefully :-)

Edit: done

**Comment by Alkarex** [comment]
@quella Could you please try again with the very latest code?

**Comment by quella** [comment]
If we did a revert, I can try doing one update from the application screen or via cli git.  Just let me know when ready.

**Comment by Alkarex** [comment]
It is ready. Try the same way you did the previous update, if that works

**Comment by quella** [comment]
I'm back up and running after doing an Update.  Thanks Guys!

**Comment by Alkarex** [comment]
Good :-)
Let's close here, and could you please resubmit your PRs @aledeg when ready (sorry for the extra work), starting with the safest bits such as extracting the classes in their own files

**Comment by aledeg** [comment]
@Alkarex I've found out the problem. There was a typo in MysqlPdo. I think we could revert the reverts.
and just fix the typo

**Comment by aledeg** [comment]
or do you want me to resubmit those PR completely ?

**Comment by Alkarex** [comment]
@aledeg Nice that you found the problem :-) The error messages were also quite cryptic (e.g. `Undefined array key 1 in /var/www/FreshRSS/lib/autoload.php on line 50`), something to test as well.
