### ISSUE TITLE
How to add custom code in the middle of < head > < / head >?

### ISSUE THREAD

**Issue by a644326772** [FreshRSS/FreshRSS#3309]
How to add custom code in the middle of < head > < / head >? I didn't find the relevant documents. Please guide me. Thank you.

**Comment by Frenzie** [comment]
You may be looking for this?
https://freshrss.github.io/FreshRSS/en/developers/03_Backend/05_Extensions.html

**Comment by math-GH** [comment]
Can I close this ticket?
