### ISSUE TITLE
Install check that temp path is writeable

### ISSUE THREAD

**Issue by henrythefifth2** [FreshRSS/FreshRSS#3310]
I'm running XAMPP 7.4.11 on Mac OS 10.15.7.

FreshRSS will not load feeds. This appears due to line 62 in the FreshRSS/constants.php file, where:

//Directory used for feed mutex with *.freshrss.lock files. Must be writable.
safe_define('TMP_PATH', sys_get_temp_dir());

directs to a non-writeable hidden system file outside XAMPP - in this case:

/var/folders/7x/sdw9rlr1573fwbdw96lwkg7r0000gp/T.

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/issues/2723
