### ISSUE TITLE
Installation without symlink?

### ISSUE THREAD

**Issue by edent** [FreshRSS/FreshRSS#3311]
My webhost doesn't allow symlinks to be user created. Is there a way to safely install FreshRSS without this?

I guess I can install it in `~/www/FreshRSS` but I don't know if there are any security risks in doing that.

Thanks!

**Comment by Alkarex** [comment]
Hello,
That is fine, assuming you set your DocumentRoot to `.../www/FreshRSS/p/`
Do not use `~` but the full path.

**Comment by edent** [comment]
Perfect, thanks!

**Comment by Alkarex** [comment]
If you cannot change the DocumentRoot, make sure that the `.htaccess` are working, and check in particular that you cannot browse the `./data/` folder
