### ISSUE TITLE
Accessibility - Low Contrast on Origine

### ISSUE THREAD

**Issue by edent** [FreshRSS/FreshRSS#3313]
I find the alert text hard to read on the Origine theme:

![Low contrast HTML warning](https://user-images.githubusercontent.com/837136/103446810-a2be4900-4c7b-11eb-959d-a431aef5b52b.png)

Caused by the CSS in

https://github.com/FreshRSS/FreshRSS/blob/ce9eb7b14c378526d9488f0eb20e663580e9f429/p/themes/Origine/origine.css#L424

Are you interested in a PR to help address this?

**Comment by edent** [comment]
I'd suggest `#710808` to get it to AAA contrast, while still being orangey-red-ish.

**Comment by aledeg** [comment]
@edent Thank you for your report.
Of course we are interested in a PR.
While you're at it, maybe you could make the same check for other themes.

Before sending your PR, maybe you could share a screenshot.

**Comment by math-GH** [comment]
in the install routine step 2 there are the same issues with low contrast

![grafik](https://user-images.githubusercontent.com/1645099/127040882-020c60dc-0923-4380-8e38-a122bbb6460b.png)

I will create a PR
