### ISSUE TITLE
[SUGGESTION] German Translation: Renaming "Send" Button to "Save"

### ISSUE THREAD

**Issue by rom-1** [FreshRSS/FreshRSS#3319]
Reference: https://github.com/FreshRSS/FreshRSS/blob/082ef9854c41d0d4ef9a36ee2fa657311bd2f44f/app/i18n/de/gen.php#L27

Hi,

I just want to throw in a little suggestion: Currently the submit button in the user interface is translated to "send" (Abschicken) in German. While this is technically correct (because it is a html form which is sending a http request) it is very confusing for non-technical end users. In Germany, most of the UI's are working with a "SAVE" Button, so my suggestion would be to rename it to "Speichern" (Saving) which people are VERY familiar with. If this does not fit, alternatively, the button could be renamed to a more general "OK". But "sending" something just feels plain wrong in the german language if you don't really transmitting something particular.

I do not speak french, but the current translation seems to be "valider", which seems to be translating to "Confirm", so it seems like you guys are also not "submitting data" to the webserver in your language. ;)

Because this is a somewhat major change, I am not submitting a pull request, but open an issue for discussion.

Thanks

**Comment by Frenzie** [comment]
I agree that something like `Update` or `Save` might be better than `Submit`, but not quite for the reason you state. `Update` is an action you can perform repeatedly, while `Submit` has a certain implied finality to it. But it's submitting in a similar sense as submitting a proposal. *How* you do that (i.e., by delivering it in person, by sending it with the mail, over HTTP, etc.) is not the relevant aspect here.

In German that could be `senden`/`abschicken`/`absenden`, but it could also be something like `einreichen`, `melden`, `updaten`/`aktualisieren`, `eintragen`, `zur Verfügung stellen` or as you said `speichern`. None of that affects the original English.

> I do not speak french, but the current translation seems to be "valider", which seems to be translating to "Confirm", so it seems like you guys are also not "submitting data" to the webserver in your language. ;)

`Valider` is a regular French way of localizing `Submit`, `OK` or even `Login` in this kind of context. Also see what I wrote above. ^_^

**Comment by rom-1** [comment]
I guess having "Update" (Aktualisieren) instead of "Save" (Speichern) would also be acceptable, as well as "OK". Just from my experience with German UI, all the other examples you brought up are almost never used in that context we have here in FreshRSS, e.g. updating the feed settings.

My main concern when changing this -> I don't know if it really fits literally everywhere. There might be some admin view in FreshRSS in which "Update"/"Save" does not fit properly. This button text might be used on a dozen occasions. Though my wild guess is that the change should improve the user experience almost in every context.

**Comment by Frenzie** [comment]
Possibly, but funnily enough I think the user admin page may be the only one that uses different phrases like `Create` and `Update`.

**Comment by rom-1** [comment]
...and the Login Screen ;)
