### ISSUE TITLE
Introduce stable docker image tags for latest released tags

### ISSUE THREAD

**Issue by jk** [FreshRSS/FreshRSS#3324]
At the moment there are general purpose tags: `latest`, `alpine` and `arm` which refers to the latest push to the `master` branch. Besides there are version-specific tags down to the patch-level `1.17.0` opposed to `1.17` and `1`, etc.

As https://github.com/FreshRSS/FreshRSS/issues/3323 shows, people use the general purpose tags (i.e. `latest`) together with automatic container rotation tools like [Watchtower](https://github.com/containrrr/watchtower) and [Ouroboros](https://github.com/pyouroboros/ouroboros) which results in breaking those instances, I suppose not everyone uses `latest` in the meaning of "latest changes to master". I pretty sure most users think it's latest released version tag.

## Suggestion
Introduce a stable tag for the latest taged version. Although there are several alternatives to achive this:

a. `stable` → `1.17.0`, continue using `latest` for latest changes in `master`
b. `latest` → `1.17.0`, introduce `preview` or `development` for latest changes in `master`
c. `latest` → `1.17.0`, introduce new tags for every branch name. So `master` will contain the latest changes to `master`.

Bonus points for introducing tags for major and minor versions: `1` → `1.x.y`, `1.17` → `1.17.y`.

### Disclaimer
The `arm` and `alpine` tags are included in each case. So `latest` also means `latest-arm` and `latest-alpine`, etc.

**Comment by Frenzie** [comment]
See https://github.com/FreshRSS/FreshRSS/discussions/3296

**Comment by jk** [comment]
Ah, I'm still confused by the new discussion tab on GitHub. Nevermind.
