### ISSUE TITLE
[FEATURE REQUEST] Add WebShare API to Sharing for mobile view

### ISSUE THREAD

**Issue by rom-1** [FreshRSS/FreshRSS#3332]
As there is no official FreshRSS App, a lot of people are using the FreshRSS Web Interface with their Mobile Phone (e.g. Chrome on Android). One of the features they are missing here is native sharing a link/article with other apps. To make this a little bit easier, I suggest to add a new sharing option (/i/?c=configure&a=integration), which enables sharing with "Apps". 

--> Add "Share with Mobile Apps" as a Sharing Target, and use the Web Share API, see here: 
- https://web.dev/web-share/
- https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share

_Originally posted in https://github.com/FreshRSS/FreshRSS/discussions/3327_

**Comment by aledeg** [comment]
I was trying to play with that. It's not as easy as it sounds.
It only works in https environments and might need some permissions.
For further informations:
- [dom-examples/index.html at master · mdn/dom-examples](https://github.com/mdn/dom-examples/blob/master/web-share/index.html)
- [Web Share API](https://w3c.github.io/web-share/)
- [Web Share API - Security and privacy considerations](https://w3c.github.io/web-share/#security-and-privacy-considerations)

**Comment by rom-1** [comment]
strange, it looked quite easy to implement in the code examples. just my 2 cents:

- https is imho the new standard for about any website, thanks to lets encrypt. I am hosting freshrss using SSL. 
- are you talking about a chrome permissions popup? if yes, this should not be a problem. FreshRSS already triggers some chrome permissions when visiting the website: "do you want to allow this website to send notifications?"

**Comment by aledeg** [comment]
It is easy to implement. I've tested the MDN example and it works both on Firefox and Chrome.
But the problem is the FreshRSS dev environnement. Either we need to support SSL in it or I need to learn how to use it properly.
But you're right. I am too hosting FreshRSS with SSL so it won't be a problem per se. But I think we need to upgrade our dev environnement prior to develop that feature.

**Comment by Frenzie** [comment]
Are you sure it doesn't already work with the current nginx config if you
just type https? (With the requisite warnings about verification.)

**Comment by aledeg** [comment]
Yes, I tried!

**Comment by Frenzie** [comment]
Probably just a one or two line change then. :-P

**Comment by aledeg** [comment]
Probably!

**Comment by math-GH** [comment]
@rom-1 Please check the current `edge` (V1.20.0-dev). The web sharing API is implemented with #4271.
While I read this issue here I realized, that the implementation was not tested with `http`. I checked only `https` and `http://localhost`

**Comment by rom-1** [comment]
@math-GH Thanks a lot, works like a charm :)
