### ISSUE TITLE
Attach to existing non-docker MySQL?

### ISSUE THREAD

**Issue by McMac** [FreshRSS/FreshRSS#3340]
I have a MySQL running somewhere else so I would need to connect only via host/user/pwd - is this supported? 
(Also would help to have a way (=sql scripts) to execute on said installation to prepare the db)

Thanks!

Edit: little detail, starting from a freshrss docker image

**Comment by Frenzie** [comment]
Port forwarding should just work, shouldn't it? Depending on the scenario you might also be able to use `host.docker.internal` where you'd normally use `localhost`.

**Comment by Alkarex** [comment]
@McMac Sure, you just give the address of your MySQL server and that should work.
You can either make a user will full permissions (easiest), in which case FreshRSS will automatically create the database and its tables, or create a user restricted to a manually-created database, in which case will FreshRSS automatically create the tables.
If you want to create the database manually, here is a suggestion:

```sql
CREATE DATABASE IF NOT EXISTS `freshrss` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
```

From:
https://github.com/FreshRSS/FreshRSS/blob/9aa3c038443a0807032d10657f841c8de0eb78d8/app/SQL/install.sql.mysql.php#L3

**Comment by McMac** [comment]
> Port forwarding should just work, shouldn't it? Depending on the scenario you might also be able to use `host.docker.internal` where you'd normally use `localhost`.

Hmm, not sure I follow, where would I specify this? You mean building the image from scratch? None of the db stuff can be provided via env vars. 🤔

**Comment by McMac** [comment]
As in #3341 described to modify the config after launch to point to physical instance of MySQL but having trouble launching the docker as is.

**Comment by Frenzie** [comment]
> Hmm, not sure I follow, where would I specify this? You mean building the image from scratch? None of the db stuff can be provided via env vars. thinking

I don't mean much other than that it's a Docker question. FreshRSS supports connecting to databases at IPs and ports like anything else. ^_^ A quick test shows, for example:

```sh
docker run --network host -it freshrss/freshrss bash

apt update
apt install netcat

root@frenzie-desktop:/var/www/FreshRSS# nc -vz localhost 80
localhost [127.0.0.1] 80 (?) open
# That port isn't listening in my Docker container, but on the host.
```

NB That may not be the recommended way to do it.

**Comment by McMac** [comment]
> @McMac Sure, you just give the address of your MySQL server and that should work.

Well, that was my question, where do I "just give the address"?

**Comment by aledeg** [comment]
Either during install or by modifying your `config.php` file (the one that sits in the `data` folder).
Make sure that your containers can communicate with each other beforehand.

**Comment by Alkarex** [comment]
Related: https://github.com/FreshRSS/FreshRSS/issues/3341

**Comment by Asara** [comment]
My issue is similar enough to this that I think its worth asking here.  I am currently trying to migrate my FreshRSS build to docker (in Nomad if it maters).

Since most of the data is in a DB anyways, is there any way to pass in these values via environment files:
```
Language

DB:
  Host
  Username
  Password
  DB
  Table Prefix

Default User:
  Name
  Auth
  Password
```

These are all asked during the initial setup.  I am currently running a centralized database and would love to be able to pass these values in and not have to worry about which host my FreshRSS install lives on.

I am able to enter these manually and everything works fine, but that is an annoyance when nomad schedules the docker container on a different host.

Let me know if this is possible, and thanks for the awesome work!

**Comment by Alkarex** [comment]
@Asara It is not currently possible, but that is a good idea, so please open a dedicated issue

**Comment by McMac** [comment]
Was expecting that, as one specifies the mysql service on the docker-compose e.g., that it would be done the same way for the connection to an external mysql instance. However RTFM, the connection is configured and established during the setup process. 
Hence closing this issue.
Thanks!

**Comment by aledeg** [comment]
@McMac you said RTFM. Is this clear enough in the documentation or do we need to address that?
