### ISSUE TITLE
Bootstrap FreshRSS entirely via environment variables

### ISSUE THREAD

**Issue by Asara** [FreshRSS/FreshRSS#3349]
Copying most of: https://github.com/FreshRSS/FreshRSS/issues/3340#issuecomment-756963805

Since most of the data is in a DB, is there any way to pass in the following values via environment files:

```
Language
DB:
  Host
  Username
  Password
  DB
  Table Prefix
Default User:
  Name
  Auth
  Password
```

These are all asked during the initial setup. I am currently running a centralized database and would love to be able to pass these values in and not have to worry about which host my FreshRSS install lives on since its mostly running in docker with an orchestrator. 

I am able to enter these manually and everything works fine, but that is an annoyance when nomad schedules the docker container on a different host.

Let me know if this is possible, and thanks for the awesome work!

**Comment by Alkarex** [comment]
@Asara See there https://github.com/FreshRSS/FreshRSS/pull/3353 Would such a syntax work for you?

**Comment by Asara** [comment]
@Alkarex I'd personally prefer individual environment variables but this would do the trick! So I can't say I mind it :)

**Comment by Alkarex** [comment]
@Asara Thanks for the feedback. Please give it a try and let us know. Will be available via Docker Hub shortly
There are potentially many FreshRSS / database options, and the advantage of doing it this way is that we can directly use our existing CLI without having to duplicate all the options as environment variables.

**Comment by Asara** [comment]
Hey, just wanted to give an update.
This works great, but as a note, if you already have a user set up in the DB, the `FRESHRSS_USER`  env var will cause the docker container to bomb out. So I just had to add `FRESHRSS_INSTALL` for it to work.

**Comment by Alkarex** [comment]
@Asara There is a few things to improve. Could you please open a new issues with a bit more info for this example?
