### ISSUE TITLE
Revise Docker documentation

### ISSUE THREAD

**Issue by aledeg** [FreshRSS/FreshRSS#3351]
See the following issues for more information:
- [x] #3341 
- [x] #3340 
- [x] #3353

**Comment by Alkarex** [comment]
Also https://github.com/FreshRSS/FreshRSS/pull/3353

**Comment by Alkarex** [comment]
- [x] https://github.com/FreshRSS/FreshRSS/issues/2679
- [x] https://github.com/FreshRSS/FreshRSS/issues/2918#issuecomment-616668682
- [x] https://github.com/FreshRSS/FreshRSS/issues/3203
- [x] https://github.com/FreshRSS/FreshRSS/issues/3269

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/4320
