### ISSUE TITLE
no pictures in display of the feed of 'Le Monde' newspaper

### ISSUE THREAD

**Issue by niels-borne** [FreshRSS/FreshRSS#3358]
Hi,

The feed 
https://www.lemonde.fr/rss/une.xml
is not fully displayed: only the title and text do appear, but the pictures don't. 

With my previous rss reader, it was working properly.

Thanks for all the good work !

**Comment by Frenzie** [comment]
Semi-related: https://github.com/FreshRSS/FreshRSS/issues/1668

Except here it's not an `<enclosure/>`.
```
<media:content url="https://img.lemde.fr/2021/01/11/391/0/3500/1750/644/322/60/0/c4db4de_fw1-health-coronavirus-china-who-0111-1a.JPG" width="644" height="322">
```

**Comment by Alkarex** [comment]
@niels-borne Can you try this fix? https://github.com/FreshRSS/FreshRSS/pull/3361

**Comment by Alkarex** [comment]
P.S. If you do not know how to test, let us know with which method you installed FreshRSS

**Comment by Alkarex** [comment]
The fix is available in the git master branch and on Docker Hub `freshrss/freshrss:latest`
Feedback welcome

**Comment by niels-borne** [comment]
Thanks,

I tried to update via 

docker pull freshrss/freshrss
then 
docker run ...

as indicated in the README. But I am not sure I got the right (latest version) though.

Version
1.17.1-dev

Is this what I should do ?

**Comment by Alkarex** [comment]
@niels-borne Yes, looks good.
You can verify your more precise version with e.g. a command like:

```sh
docker inspect --format='{{.Name}} {{.Image}} {{index .Config.Labels "org.opencontainers.image.revision"}}' freshrss
```

**Comment by niels-borne** [comment]
I can confirm the images are now correctly displayed. Thank you very much !
(Minor remark: it wasn't the case at first, I mean for the 'old' feeds,which led me to ask the question about the current version. But once 'new' feeds appeared there where fully displayed).
