### ISSUE TITLE
Periodical crashes (?)

### ISSUE THREAD

**Issue by oatmealm** [FreshRSS/FreshRSS#3370]
I'm not sure if it's the server crashing or some other issue, but I need to periodically clear out the cache and restart the server (docker)...

Error in browser:

`### Fatal error! ###`

`rm -rf www/freshrss/data/cache/*.spc`

**Comment by aledeg** [comment]
Do you have more information than that? Maybe some logs, the FreshRSS version, your database flavor!

**Comment by Alkarex** [comment]
Please share your docker run / docker-compose

**Comment by oatmealm** [comment]
Yes, of course. My apologies.

This seems to happen randomly and the server is not accessible from browser or clients (Reedeer of iOS).

Server is run using docker CLI like so [on raspberry 3+], using the default sqlite backend:
https://github.com/linuxserver/docker-freshrss/blob/master/Dockerfile.armhf

```
docker run -d \
    --name=freshrss
    -e PUID=1000
    -e PGID=1000
    -e TZ=Europe/Zurich
    -p 7070:80
    -v /media/SAMSUNG150GB/HTPC/freshrss:/config
    --restart unless-stopped
    ghcr.io/linuxserver/freshrss

```

**Comment by Alkarex** [comment]
Ah, this is not our official Docker image @oatmealm so I am not familiar with it.
Ours is `freshrss/freshrss:1.17.0` and you are welcome to giving it a try, @oatmealm 
But obviously finding out what is wrong with the other one would also be interesting

**Comment by oatmealm** [comment]
Thanks. How can I produce a log/trace that might be helpful?

**Comment by Alkarex** [comment]
I would first be interested in knowing whether you can observe that problem with the official image or not

**Comment by oatmealm** [comment]
> I would first be interested in knowing whether you can observe that problem with the official image or not

Trying the official container. See if problem reproduces. Thanks.

**Comment by oatmealm** [comment]
Yes. Seems to crash. Looks like it's happening when I'm forcing a refresh from Reeder (pull down to refresh). Seeing exactly the same error.

**Comment by Alkarex** [comment]
Please show the file permissions just after you observe an error, e.g.:

```sh
docker exec freshrss ls -alh data/cache/
docker exec freshrss ls -alh data/users/oatmealm/
```

**Comment by oatmealm** [comment]
Per the instructions on the wiki. Looking at the logs though looks like the external disk where data is stored becomes r/o for some reason. I don't think it has anything to do with freshrss.
