### ISSUE TITLE
Docker version crashes after start (standard_init_linux.go:219: exec user process caused: exec format error)

### ISSUE THREAD

**Issue by LeLunZ** [FreshRSS/FreshRSS#3371]
I am trying to become a new user of FreshRSS.

I have a running Traefik v2 system.
And I am trying to add the FreshRSS to it.

But after adding FreshRSS to my docker-compose it won't even start.
It just gives this error:

> standard_init_linux.go:219: exec user process caused: exec format error

I have one guess. I saw this [merge](https://github.com/FreshRSS/FreshRSS/pull/3343).
Because I already have a container running on port 80 (in this docker network), I tried to switch LISTEN to another port.

Is this already on docker-hub? I used the FreshRSS:latest image.

Or could it be something else?

**Comment by LeLunZ** [comment]
Stupid. I used the wrong docker image. used amd64 instead of arm.

**Comment by Alkarex** [comment]
We could have a better manifest for automatic architecture detection, but last time I checked, it was not easy to do with automatic builds on Docker Hub. Updates welcome

**Comment by Frenzie** [comment]
I've never tried it myself, but there's some info here:
https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

**Comment by Alkarex** [comment]
@Frenzie It is better than last time I looked at it, but not so mature yet. The dependency of the tutorial is already archived https://github.com/marketplace/actions/docker-buildx
I was hoping to see a solution directly on Docker Hub
