### ISSUE TITLE
request for documentation of "archiving" section

### ISSUE THREAD

**Issue by rezad1393** [FreshRSS/FreshRSS#3374]
can someone explain the archiving section?
I have 274 feeds. because I removed and added many feeds the number that is shows for adding new feeds ( for example like this  freshrssdomain//i/?c=subscription&id=1283 ) is now in 1300.
I have set 

Purge policy(By default)Maximum number of articles to keep 8
Maximum age of articles to keep: 1 month
Never delete favourites:  yes
Never delete labels: yes 
Never delete unread articles: yes
Minimum number of articles to keep per feed: 5

I have read that the first one doesn't count if it is too low.
I also have zero unread articles.
and I don't know what label articles are so I ignore that.

but even setting all this and having 300 favorite items and using purge , I still have this:
Maintenance Current user
4 644 articles (23.11 MiB)

how do I still have 4644 articles?
(Minimum number of articles to keep per feed=5) * 247 feeds + 300 favs = at most 1600

can someone explain this section in simple terms and show when they overlap what happens?
maybe with an example with numbers?

**Comment by Alkarex** [comment]
Hello,
FreshRSS will at least keep the articles that are still on the original servers, which is often 10, 20, 50 articles per feed. The idea is more to mark articles as read (that can soon be done automatically https://github.com/FreshRSS/FreshRSS/pull/3303 ) rather than deleting them so aggressively. I do not recommend values below 100 for maximum number of articles per feed.

**Comment by rezad1393** [comment]
> Hello,
> FreshRSS will at least keep the articles that are still on the original servers, which is often 10, 20, 50 articles per feed. The idea is more to mark articles as read (that can soon be done automatically #3303 ) rather than deleting them so aggressively. I do not recommend values below 100 for maximum number of articles per feed.

1-why?
freshrss uses sqlite correct?
then having more articles decreases the performance right?
maybe I am missiong something.

2-so all my questions about articles not deleted are related to the "FreshRSS will at least keep the articles that are still on the original servers," part?
that is necessary for feed update check to diff the data and cant be changed, correct?

3-100 is too much. but if I put a number like 20 for global minimum per feed then feeds that I higher that that on update, they just ignore this limit right?


UPDATE: never mind. I tested and this not global sum but per feed.
maybe this should be put in text of option that this is per feed.
4- is the "Maximum number of articles to keep" is a global limit for sum of  all articles for all feeds that if for example I put 100000 on it and remove the time limit then it will not remove articles until sum of all them execs 100000?:

UPDATE:this also is not relevant because the option was not global sum as I initially  thought.
5-so in your opinion I am better served with just disabling "Maximum number of articles to keep" options and keep the date limit?
is that a good idea for general use for me? I usually read my every feed at most every month and mark them as read.

6-
unrelated: can I disable tags? 
also any plan to allow user to assign more than one category to a feed?

**Comment by Alkarex** [comment]
1. FreshRSS supports SQLite, but also PostgreSQL, and MariaDB / MySQL.
Indeed an empty database is faster than one with some content, but even with SQLite, a few tens of thousands of articles is still little. I regularly have 400.000+ articles for a single user in SQLite on Raspberry Pi 4 with nothing to complain about performance. There are some proper indexes in place, and retrieving unread articles is efficient, even when you have a large amount of read ones.

2. It makes the logic indeed simple, for instance to detect new articles, changed articles, vanished articles...

3. Correct

We indeed need to reformulate those options to make them clearer.

You cannot disable labels (the ones that are user-defined) nor tags (the ones defined by the articles), but you can just not use them.

No plan to assign more than one category to a feed, but soon some options to automatically assign multiple labels automatically.
