### ISSUE TITLE
Not able to setup with a remote postgresql server

### ISSUE THREAD

**Issue by snugglej** [FreshRSS/FreshRSS#3376]
So I'm trying to get this setup inside azure with a azure postgresql server. I can connect to the postgres through the freshrss web server command line without any problem. But when I try to setup the connection in the configuration file for FreshRSS, I'm unable to do so. 

It looks like I can't specify the correct username, due to some sanity check of the format? From Azure's suggestion for PHP this is what I should configure for the fields:
host={servername}.postgres.database.azure.com 
dbname=freshrss 
user=freshrss@{servername}
password={your_password} 

![image](https://user-images.githubusercontent.com/17776110/104833702-57ea2700-5860-11eb-8897-0dad4c1c5e1b.png)

When I got to type in that user I get a warning that says the format is invalid. But there is no suggestion how I'm supposed to format this properly.

Thanks.

**Comment by Alkarex** [comment]
Which version of FreshRSS are you using?
Please see
https://github.com/FreshRSS/FreshRSS/pull/3241

**Comment by snugglej** [comment]
@Alkarex 

Thanks for that information, I'm using the **latest** version of stable release so only 1.17.0. 

So I will need to get a newer version for this to work.

Thanks for the quick reply.

**Comment by snugglej** [comment]
Hot fixed 1.17.0 with the change for 1.18 and it all working!

**Comment by Alkarex** [comment]
Thanks for the feedback @snugglej !
