### ISSUE TITLE
minor CURLOPT problem

### ISSUE THREAD

**Issue by printfuck** [FreshRSS/FreshRSS#3378]
I was testing the CURLOPT merge and found a really dumb flaw. I really should've seen it earlier.

https://github.com/FreshRSS/FreshRSS/blob/ee175dd6169a016fc898fac62d046e22c205dec0/lib/lib_rss.php#L190-L195

line 192 should obviously be:
```
$curl_options[$co] = $v; 
```

**Comment by Alkarex** [comment]
Ah indeed. Please send a PR if you can 👍🏻
