### ISSUE TITLE
Unexpected behaviour with Keyboard shortcut "Open next article" 

### ISSUE THREAD

**Issue by rom-1** [FreshRSS/FreshRSS#3387]
The keyboard shortcut "open the next article" existed in Google Reader and Tiny Tiny RSS. Pressing this shortcut in these tools, it always jumped to the next article in the article list based on my **current** view. Means: If I scroll down the article list using my mouse wheel (and marking articles as read automatically by scrolling), then pressing the Keyboard Shortcut, I expect the list to jump _down_ to the next article _below_ my current active view. 

But what happens is, that the list scrolls back _upwards_ to the article I pressed the shortcut the last time. Is this considered as expected behaviour?

Attached my "Reading" Options as screenshot:
![2021-01-19_20h43_59](https://user-images.githubusercontent.com/37835829/105084734-1099ab80-5a97-11eb-91a3-1da302e6d3ac.png)

**Comment by Alkarex** [comment]
Maybe something for @aledeg ?

**Comment by aledeg** [comment]
That's how it works. Might not be the better way.
We might need to improve that.

I've notice that too but as I never use the scroll marking, it never bugged me :)

**Comment by rom-1** [comment]
Another idea, which may be a lot of easier to implement: Maybe jump to the next **unread** article?

Edit: actually, I guess this is how other tools work. not based on scroll view, but based on unread state.

**Comment by aledeg** [comment]
I thought about it and I think we should keep the behavior as it is. Here is my reasoning behind that.
For me, the 2 things you've mentioned are unrelated. One is for navigation purpose and the other one is for marking, thus they shouldn't be linked.
If the shortcut jumps from unread article to unread article, how do you navigate through the read articles? How can you tell whether the user wants to navigate to the next unread article or to the next article?

**Comment by rom-1** [comment]
Good point - though in my workflow I don't need to navigate between (hidden) read articles, Usually I want to see the unread articles. So... maybe I should add a Feature request for a **new** Keyboard Shortcut: "Next unread article"?

**Comment by rom-1** [comment]
Adding a feature requests for new keyboard shortcut "next unread article"
