### ISSUE TITLE
[Feature Request] New Keyboard Shortcut "next unread article"

### ISSUE THREAD

**Issue by rom-1** [FreshRSS/FreshRSS#3393]
The keyboard shortcut "next article" is currently not based on the read state, or on the current "view" of the user (scroll position). Instead, it probably scrolls upwards to the article the shortcut has been pressed before. See discussion here: https://github.com/FreshRSS/FreshRSS/issues/3387

As some users may want to have an option to simply jump from last read article to next unread article, I suggest to add an additional keyboard shortcut to jump to the next "unread" article in the current view, so that these users can navigate only by keyboard through their list.

**Comment by stysebae** [comment]
Hello, I am working on this issue and I think I have already found a (pretty simple) solution (I am checking if all it is okay and then I will submit a PR). However, it also requires a translation work for integrating this new feature/option for all the available languages.

![Screenshot from 2021-10-15 12-46-26](https://user-images.githubusercontent.com/32852093/137475699-6b4e653f-775d-44fd-845f-38b246a8f3f0.png)
