### ISSUE TITLE
Unknown error for feed

### ISSUE THREAD

**Issue by dumprop** [FreshRSS/FreshRSS#3395]
FreshRSS: 1.17.1-dev logs:
2021-01-24 12:17:45
Unknown error for feed [https://xlab.tencent.com/en/atom.xml]
2021-01-24 12:17:20
Unknown error for feed [https://deniable.org/index.xml] <- there invalid certificate, so http works
2021-01-24 12:16:21
Invalid action name for controller FreshRSS_index_Controller
2021-01-24 12:16:12
Invalid action name for controller FreshRSS_index_Controller
2021-01-24 12:16:08
Unknown error for feed [https://arielkoren.com/blog/feed/]
2021-01-24 12:16:03
Invalid action name for controller FreshRSS_subscription_Controller

https://validator.w3.org/feed/check.cgi and https://github.com/Ranchero-Software/NetNewsWire/issues/2759 validated it

**Comment by Alkarex** [comment]
* https://xlab.tencent.com/en/atom.xml works for me
* https://arielkoren.com/blog/feed/ works for me

I cannot reproduce your errors. Please update to the latest version of FreshRSS 1.17.1-dev just to make sure we are testing the same thing. And please tell about your setup (OS, server, type of deployment, versions...).

Try also to `curl -v https://xlab.tencent.com/en/atom.xml` from your server

**Comment by Alkarex** [comment]
Double-check that the access rights are correct: the Web server must be able to write in `./FreshRSS/data/` and all its sub-directories.
Show the output of a `ls -alh data/cache/`

**Comment by dumprop** [comment]
> * https://xlab.tencent.com/en/atom.xml works for me
> * https://arielkoren.com/blog/feed/ works for me
> 
> I cannot reproduce your errors. Please update to the latest version of FreshRSS 1.17.1-dev just to make sure we are testing the same thing. And please tell about your setup (OS, server, type of deployment, versions...).
> 
> Try also to `curl -v https://xlab.tencent.com/en/atom.xml` from your server

```
* SSL: no alternative certificate subject name matches target host name 'xlab.tencent.com'
* Closing connection 0
* TLSv1.3 (OUT), TLS alert, close notify (256):
curl: (60) SSL: no alternative certificate subject name matches target host name 'xlab.tencent.com'
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
My bad, problem in dns/certs on server, fixed
Also
```
curl -v https://arielkoren.com/blog/feed
*   Trying 192.185.128.95...
* TCP_NODELAY set
```
(hangs out, seems like server ip in block list, seems no way to fix it, proxy?)


But IDK how to deal w/ https://pinkysplanet.net/rss/
```
*   Trying 2606:4700:3033::6815:2238:443...
* TCP_NODELAY set
* Connected to pinkysplanet.net (2606:4700:3033::6815:2238) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=CA; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: Sep  3 00:00:00 2020 GMT
*  expire date: Sep  3 12:00:00 2021 GMT
*  subjectAltName: host "pinkysplanet.net" matched cert's "pinkysplanet.net"
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55740f4c3df0)
> GET /rss/ HTTP/2
> Host: pinkysplanet.net
> user-agent: curl/7.68.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
< HTTP/2 200 
< date: Sun, 24 Jan 2021 18:27:37 GMT
< content-type: text/xml; charset=utf-8
< set-cookie: __cfduid=<redacted>; expires=Tue, 23-Feb-21 18:27:36 GMT; path=/; domain=.pinkysplanet.net; HttpOnly; SameSite=Lax; Secure
< x-powered-by: Express
< cache-control: public, max-age=0
< etag: W/"fecd-Sh/tq8+mnJouR/58uh5gOApaK8E"
< vary: Accept-Encoding
< cf-cache-status: DYNAMIC
< cf-request-id: <redacted>
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< report-to: {"group":"cf-nel","endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report?s=<redacted>%<redacted>%<redacted>%2Fiyo8E%2Bvw47%2F0limV%<redacted>"}],"max_age":604800}
< nel: {"report_to":"cf-nel","max_age":604800}
< strict-transport-security: max-age=0; includeSubDomains
< x-content-type-options: nosniff
< server: cloudflare
< cf-ray: 616bcf3a0f241f3d-FRA
< 
<?xml version="1.0" encoding="UTF-8"?>...(there all rss data)
```

Cache output: https://pastebin.com/rPpqyPQn

I've checked it on w3 and that didnt pass
```
This feed does not validate.
line 12, column 1335: XML parsing error: <unknown>:12:1335: not well-formed (invalid token) 
```
But NNW parsed it, maybe is possible to add this feed?

**Comment by Alkarex** [comment]
That feed has some invalid XML characters (NUL). You can place the following file somewhere on your Web server, and use it as the address in your FreshRSS. It will act as a mini proxy, fixing the feed.

`https://example.net/pinkysplanet.rss.php`:

```php
<?php
$url = 'https://pinkysplanet.net/rss/';

header('Content-Type: application/rss+xml; charset=utf-8');

$ch = curl_init($url);
curl_setopt_array($ch, [
	CURLOPT_HTTPHEADER => [
		'Accept: application/atom+xml, application/rss+xml, application/rdf+xml;q=0.9, application/xml;q=0.8, text/xml;q=0.7, */*;q=0.1',
	],
	CURLOPT_FOLLOWLOCATION => true,
	CURLOPT_MAXREDIRS => 3,
	CURLOPT_RETURNTRANSFER => true,
	CURLOPT_TIMEOUT => 15,
	CURLOPT_ENCODING => '',	//Enable all encodings
]);
$xml = curl_exec($ch);
curl_close($ch);

echo str_replace("\0", '', $xml);
```

Similar than https://github.com/FreshRSS/FreshRSS/issues/2910#issuecomment-616121948

**Comment by aledeg** [comment]
@Alkarex Do you think it would be a nice addition to list all the validation we could do on a feed to check if it is valid or not. Either as a documentation or as a CLI tool.

**Comment by Alkarex** [comment]
Indeed. We already have the link to the W3C Feed Validator, but more errors can be due to local problems such as banned IPs, banned user-agent, certificate and other HTTPS problems, proxy issues, Cloudflare, IPv4 / IPv6, etc.

**Comment by temberature** [comment]
https://github.com/FreshRSS/FreshRSS/issues/1967
