### ISSUE TITLE
[Feature request] Add maintenance hooks

### ISSUE THREAD

**Issue by aledeg** [FreshRSS/FreshRSS#3398]
I think it could be useful to introduce new hooks for the extension system.
I am thinking hooks that can be use for maintenance purposes. It could be at the system level (perform a vacuum on sqlite databases), at the user level (remove useless configuration), or at the feed level (modify existing article content).

At the moment, we have the `feed_before_insert` hook which could be used for the feed level but it is triggered (as far as I understand) only when the feed is updated.
We also have the `freshrss_init` hook which could be used for the system level but it is trigger for every calls. It's probably too much for a maintenance task.

What I envisioned is hooks that are triggered only during the `actualize_script.php` process. In the file itself, we could have the hook at the system level and the hook at the user level. The hook at the feed level would have to be in the `feedController.php` process.

I suggest the following names:
- `freshrss_system_maintenance`
- `freshrss_user_maintenance`
- `freshrss_feed_maintenance`

**Comment by Alkarex** [comment]
Sounds good!

**Comment by aledeg** [comment]
Well, the user hook was straightforward to write.
But I don't know how the system hook could work. I've tried a few different things without success.
For the feed hook, I am reconsidering it since the `feed_before_actualize` could almost fulfill the same role.
