### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by 123gratitude123** [FreshRSS/FreshRSS#3405]
Hi,
I just installed freshrss, everything checked ok during installation, but after I loged in, it took me to a 404 page. Any ideas what went wrong?
Thanks.

**Comment by Frenzie** [comment]
You'll have to provide a few more details at least, like which HTTP and SQL server. ;-)

My first instinct would be some `.htaccess` issue for example, but if there's no Apache involved…

**Comment by 123gratitude123** [comment]
Mysql database and I verified that the database has been created by the script (6 tables). php version 7.4. As per script, I go to page http://www.xxxx.com/freshrss/p/i/index.php which shows the page properly, i enter my login credentials, but then it takes me to a 404 page. Thanks.

**Comment by 123gratitude123** [comment]
above, i replaced the real website anme with xxxx. so do not try that link that it will take you nowhere.

**Comment by Alkarex** [comment]
Hello,
How did you install FreshRSS, and which version, more precisely?

**Comment by 123gratitude123** [comment]
I installed it yesterday, so it's yesterday's version? the file was called Freshrss-master

**Comment by 123gratitude123** [comment]
i followed the directions in the readme.md

**Comment by 123gratitude123** [comment]
i git it from https://freshrss.org, from Download button

**Comment by 123gratitude123** [comment]
I entered a .htaccess in freshrss folder, with one line "DirectoryIndex index.php". Now when i log in it takes me to http://www.xxxx.com/freshrss/p/i/?c=auth&a=login in a loop. If i enter a wrong username, it shows a 403 Error page (as expected). The folder where i installed it "fressrss" is a folder under http://www.xxxx.com domain.

**Comment by 123gratitude123** [comment]
what the heck. I have been trying on Safari (i have a macbook laptop), with the errors i mentioned here. I tried on Firefox few minutes ago, when i got into it - seems to run properly on Firefox. Does anybody know how to make it run on Safari browser?

**Comment by Alkarex** [comment]
@123gratitude123 Could you please edit the following line in your `./FreshRSS/data/config.php` to produce more logs:

```php
'environment' => 'development',
```

And then please try again after clearing your cache in Safari and check for errors/warnings in your browser console, Web server logs, and FreshRSS logs (located in `./FreshRSS/data/users/*/log*.txt`)

**Comment by ldv8434** [comment]
I'm experiencing the same issue with 403 loops. Interestingly, a correct set of credentials doesn't come to a 403 page but Firefox dev tools do show a 403 POST request. 
Also Chromium works but Firefox does not. Both browsers are using a shared password manager. 

Enabling logs, clearing cache, and logging in results in:
```
[Tue, 16 Mar 2021 15:22:43 -0400] [debug] --- Invalid credential parameters: user=greywolver, challenge=$2a$04$GKqJzTPIMou1ZW.OTibZeemG6SyhVQaf7Rc75T3ICk5jI25rZ1he., nonce=
[Tue, 16 Mar 2021 15:22:43 -0400] [warning] --- Password mismatch for user=greywolver, nonce=, c=$2a$04$GKqJzTPIMou1ZW.OTibZeemG6SyhVQaf7Rc75T3ICk5jI25rZ1he.
```
Logging in with incorrect credentials results in no output. 
---
Also of note: Firefox's dev tools gave me the following message in reference to line 62 of extra.js (which seems to be related to sending the username and nonce):
```
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/
```
I don't know if that has anything to do with the issue, but I figured it is better to mention it than not.

**Comment by Alkarex** [comment]
@ldv8434 An empty nonce (`nonce=`) is a sign of bad cookie and/or session configuration, so you need to tell more about your setup.

**Comment by ldv8434** [comment]
Sure, though I'm not sure what you're looking for exactly.
Browser: Firefox 86.0.1 (64-bit)
all security/privacy related extensions disabled for testing
"Extended Tracking Protection" set to standard
"Do Not Track" set to always 

This issue started after installing FreshRSS 1.18.0. No changes were made to the Firefox installation besides updates.

**Comment by Alkarex** [comment]
@ldv8434 I meant the server configuration

**Comment by ldv8434** [comment]
Oh! My bad. 
OS: Ubuntu 18.04
Web server: Apache/2.4.29
PHP: 7.2.24-0ubuntu0.18.04.7
FreshRSS: 1.18.0

Server config: 
```
<?php
return array (
  'environment' => 'development',
  'salt' => 'REDACTED',
  'base_url' => 'https://lvacula.com/freshrss',
  'auto_update_url' => 'https://update.freshrss.org',
  'language' => 'en',
  'title' => 'FreshRSS',
  'meta_description' => '',
  'default_user' => 'greywolver',
  'force_email_validation' => false,
  'allow_anonymous' => false,
  'allow_anonymous_refresh' => false,
  'auth_type' => 'form',
  'http_auth_auto_register' => true,
  'http_auth_auto_register_email_field' => '',
  'api_enabled' => true,
  'unsafe_autologin_enabled' => false,
  'simplepie_syslog_enabled' => true,
  'pubsubhubbub_enabled' => true,
  'allow_robots' => false,
  'allow_referrer' => false,
  'limits' => 
  array (
    'cookie_duration' => 2592000,
    'cache_duration' => 800,
    'timeout' => 15,
    'max_inactivity' => 9223372036854775807,
    'max_feeds' => 16384,
    'max_categories' => 16384,
    'max_registrations' => 1,
  ),
  'curl_options' => 
  array (
  ),
  'db' => 
  array (
    'type' => 'mysql',
    'host' => 'localhost',
    'user' => 'freshrss',
    'password' => 'REDACTED',
    'base' => 'freshrssdb',
    'prefix' => 'freshrss_',
    'connection_uri_params' => '',
    'pdo_options' => 
    array (
    ),
  ),
  'mailer' => 'mail',
  'smtp' => 
  array (
    'hostname' => '',
    'host' => 'localhost',
    'port' => 25,
    'auth' => false,
    'auth_type' => '',
    'username' => '',
    'password' => '',
    'secure' => '',
    'from' => 'root@localhost',
  ),
  'extensions_enabled' => 
  array (
    'Google-Groups' => true,
    'Tumblr-GDPR' => true,
  ),
  'disable_update' => false,
);
```

**Comment by Alkarex** [comment]
@ldv8434  Can you also please show you user's `config.php`? In particular:

```php
	'enabled' => true,
	'is_admin' => true,
```

**Comment by ldv8434** [comment]
```
  'enabled' => true,
  'is_admin' => true,
```

**Comment by Alkarex** [comment]
@ldv8434 Would you be able to make me a temporary test account on your FreshRSS instance?

**Comment by ldv8434** [comment]
Sure! 
https://lvacula.com/freshrss
User: alkarex
Pass: SamplePass1
I can make the account an admin as soon as you've confirmed you've logged in and changed the password.

**Comment by Alkarex** [comment]
@ldv8434 Thanks. I have been able to log in once and change the password, but cannot log back again. Can we try again? This time, please send the password by e-mail https://alexandre.alapetite.fr/cv/

**Comment by ldv8434** [comment]
I'm now getting 403 errors when adding a new user with the message "You don’t have permission to access this page [CSRF]".

**Comment by Alkarex** [comment]
@ldv8434 That really sounds like a cookie/session issue either on server side or client side. If you cannot log into your own account, you can temporarily set the following in your `./data/config.php` to disable the login for the main user:

```
'auth_type' => 'none',
```

**Comment by ldv8434** [comment]
This issue is only appearing when trying to add a user.
At this point, I think it would be better to backup my feeds and create the instance from scratch in case the issue came from the update to 1.18.0.

**Comment by ldv8434** [comment]
After installing on local server, the issue is resolved.

**Comment by math-GH** [comment]
I guess this issue could be closed
