### ISSUE TITLE
Relative image source to content

### ISSUE THREAD

**Issue by patdavid** [FreshRSS/FreshRSS#3411]
I'm seeing an issue from a user where the `<description>` in an item has HTML image tags that are sourced local to the content (see https://librearts.org/index.xml for our example).

Some of the content has HTML image tags that have a src that is relative to the content, ie:
```
...<img src="siril-0-99-7.webp" alt="Siril 0.99.7">...
```

This works fine as expected in an HTML page (https://librearts.org/2021/01/foss-in-2021-preview/), but fails to render the images in FreshRSS.  In a couple of other RSS readers I've tested (Feedly and Thunderbird namely) they _do_ handle the relative linking, but not here.

Is this something that could be handled on the reader side (build the absolute URL from the item `<link>` if it's a relative asset?

**Comment by math-GH** [comment]
@patdavid Could you please check if it is still an issue?
As far as I can see the src changed from relative to absolute paths

**Comment by Alkarex** [comment]
Probably fixed by https://github.com/FreshRSS/FreshRSS/pull/4565
