### ISSUE TITLE
Sync with Vienna is not working

### ISSUE THREAD

**Issue by fabiosirna** [FreshRSS/FreshRSS#3417]
Hi,
I've configured FreshRSS on a docker container and via web works really well.
However, I'd like to use a desktop reader like Vienna but I'm not able to sync it via the greader API.

A test I did via terminal:

```
#curl 'http://192.168.1.2:60040/api/greader.php/accounts/ClientLogin?Email=fabio&Passwd=cijvax2pExrefotcah'

SID=fabio/975db1b731c02f74270740db330222c77790e022
LSID=null
Auth=fabio/975db1b731c02f74270740db330222c77790e022


#curl -s -H "Authorization:GoogleLogin auth=fabio/975db1b731c02f74270740db330222c77790e022" \
  'http://192.168.1.2:60040/api/greader.php/reader/api/0/stream/contents/reading-list' | jq .
```

After the second command I'm able to get a JSON with a list.

I'm using the same parameters on Vienna preferences panel:

<img width="512" alt="Screenshot 2021-02-04 at 00 52 07" src="https://user-images.githubusercontent.com/2249234/106826551-6f5e4800-6687-11eb-82c2-8657156ca26f.png">

For the password I tried everything:
- user pass
- mobile token
- some token you can see in the terminal command

I always get this:

<img width="272" alt="Screenshot 2021-02-04 at 01 24 29" src="https://user-images.githubusercontent.com/2249234/106826779-e398eb80-6687-11eb-851e-6939ce224792.png">

and if I remove the http I get an SSL error like this:

<img width="271" alt="Screenshot 2021-02-04 at 01 26 24" src="https://user-images.githubusercontent.com/2249234/106826848-04f9d780-6688-11eb-9f64-a93dec0725f1.png">

Is there anything I can do to get it working?

I'm looking also for suggestions about a IOS mobile app that can work with FreshRSS (the web ui via mobile doesn't have a good ux).

Thanks!

**Comment by aledeg** [comment]
Have you checked #2573 and #2091?

**Comment by Alkarex** [comment]
In addition to @aledeg 's suggestions, please check your Web server logs, and `./FreshRSS/data/users/_/log_api.txt`
Please give also some details about your setup (OS, Web server, versions, proxy, type of FreshRSS installation...)

**Comment by math-GH** [comment]
@fabiosirna 
Is it still an issue?
Maybe you could help with your experiences and help to update our apps list on https://github.com/FreshRSS/FreshRSS/blob/edge/README.md

**Comment by fabiosirna** [comment]
Hi @math-GH,
I gave up with Vienna, and I'm currently using NetNewsWire on both Mac OS and IOS and works without any issues so far!

After your comment, I downloaded that latest version of Vienna, and still not working. I don't know why, I think it's a Vienna issue.

**Comment by Alkarex** [comment]
Is there anyone else with an Apple device who could try Vienna?

@barijaona If you are around, did you have a chance to test FreshRSS lately? Let me know if I can facilitate with anything, e.g. test account.

**Comment by barijaona** [comment]
> @barijaona If you are around, did you have a chance to test FreshRSS lately? Let me know if I can facilitate with anything, e.g. test account.

Hi @Alkarex. Yes, I'd like a test account.
You can email me : barijaona / Gmail.com

**Comment by Alkarex** [comment]
@barijaona Done :-)

**Comment by barijaona** [comment]
There are two parts to this problem:

- current version of Vienna does not make clear that you should input hostname and path without any scheme (in the aforementioned case `192.168.1.2:60040/api/greader.php` without `http://` or `https//`). I will fix this.
- For security reasons, Vienna requires the use of https

**Comment by Alkarex** [comment]
Thanks for the feedback @barijaona 👍🏻 
Can you confirm that it otherwise works with my test instance?

HTTPS might be overkill for a local network such as `192.168.x.x` ;-)

**Comment by Alkarex** [comment]
Follow-up in https://github.com/ViennaRSS/vienna-rss/issues/1615

**Comment by barijaona** [comment]
> Thanks for the feedback @barijaona 👍🏻 Can you confirm that it otherwise works with my test instance?
> 

Yeah, everything I tried seemed OK.

**Comment by Alkarex** [comment]
@barijaona Could you help filling some of the columns related to Vienna features?
https://github.com/FreshRSS/FreshRSS/blob/edge/README.md#apis--native-apps

**Comment by barijaona** [comment]
> @barijaona Could you help filling some of the columns related to Vienna features?

What do you mean by FastSync ?
Does making text available but not images / videos qualify to "works offline" ?

**Comment by Alkarex** [comment]
@barijaona 

> What do you mean by FastSync ?

I mean that it should be fast (in seconds) and efficient (few and light requests) to sync. My rule of thumb on mobile: ~5 seconds max to re-sync against a database with 5k+ unread articles and 1k+ favourites, using < 10 HTTP requests.

Some clients are literally sending hundreds of HTTP requests in such a scenario, taking sometime over a minute, draining the battery and wasting (server) resources (others circumvent the problem by only synchronising a little number of articles).

See for instance my recommendation for the synchronisation strategy:
https://github.com/FreshRSS/FreshRSS/issues/2566#issuecomment-541317776

> Does making text available but not images / videos qualify to "works offline" ?

Yes, offline is mostly for the following scenario: continue reading, marking as read/unread, (un-)marking as favourite, adding labels while offline, with the ability to sync again when the connectivity is restored. No images / videos requirements.
