### ISSUE TITLE
Update information about Fluent Reader Lite

### ISSUE THREAD

**Issue by dumprop** [FreshRSS/FreshRSS#3418]
Currently Fluent Reader ([from v0.9.0 Beta](https://github.com/yang991178/fluent-reader-lite/releases)) supports Google Reader API

Also it have [android/ios](https://github.com/yang991178/fluent-reader-lite) platform 

Currently I use FreshRSS through Fluent Reader on my mac/ios and it seems stable (but I had some crashes on iOS, so maybe it more beta version)

**Comment by math-GH** [comment]
@dumprop is it still an issue or already updated in https://github.com/FreshRSS/FreshRSS/blob/edge/README.md ?

**Comment by dumprop** [comment]
> @dumprop is it still an issue or already updated in https://github.com/FreshRSS/FreshRSS/blob/edge/README.md ?

It's still an issue because there no link for iOS version of fluent reader ( https://github.com/yang991178/fluent-reader-lite )
Maybe add it in row with fluent reader as link of iOS?
