### ISSUE TITLE
Failed to add feed

### ISSUE THREAD

**Issue by dumprop** [FreshRSS/FreshRSS#3420]
https://j00ru.vexillium.org/feed/

w3:
Congratulations!
[Valid RSS] This is a valid RSS feed.

FreshRSS:
2021-02-05 09:56:56
Unknown error for feed [https://j00ru.vexillium.org/feed/]
2021-02-05 09:56:16
Invalid action name for controller FreshRSS_index_Controller

Setup all are ok:
FreshRSS: 1.17.1-dev.
5 February 2021 at 09:57

**Comment by Alkarex** [comment]
Works for me. Please try from your server:

```sh
curl -v 'https://j00ru.vexillium.org/feed/'
```

**Comment by Frenzie** [comment]
Works for me in 1.17.0 but I can't test dev right now.

**Comment by dumprop** [comment]
There all are ok w/ connection
Added, sometimes the feed is not added on the first try, strange

**Comment by Alkarex** [comment]
I am trying to reproduce the warning I see in your logs: `Invalid action name for controller FreshRSS_index_Controller`
Can you tell a bit more how you added the feed? Simply by the default UI method?

![image](https://user-images.githubusercontent.com/1008324/107078682-f24de280-67ee-11eb-86d3-79ec3a051ad0.png)

**Comment by dumprop** [comment]
I usually add the feed via the NNW, after that I try to add in default UI, so sometimes it stuck and gets that error via NNW and UI too for multiple times 
After sometime the feed successfully added (I had that for multiple times)

When I add a lot of feeds, it gets stuck on some of them and can add it only after sometime (looks like that once it failed w/ getting a feed information and uses that corrupted result for sometime)

I think this can be caught only w/ detailed debugging information because the error occurs rarely

**Comment by dumprop** [comment]
Seems like I figured out that problem

I use RSSHub extension
So, from default UI all are ok
From extension - got problem

One more feed w/ that problem: https://rsshub.app/telegram/channel/hacker_sanctuary

RSSHub generate that link: https://myfreshrss/i/?c=feed&a=add&url_rss=http://rsshub.app/telegram/channel/hacker_sanctuary
There I got problem, from default UI all are ok


Check that, please

**Comment by Alkarex** [comment]
@dumprop https://rsshub.app/telegram/channel/hacker_sanctuary works for me. Maybe a temporary problem, please try again. If it still fails, try to curl from your server.

**Comment by dumprop** [comment]
No, I mean

**Comment by leochen-g** [comment]
same problem for me.
freshRSS version: 1.21.0
