### ISSUE TITLE
[Feature Request] OPML Import/Export via GReader API

### ISSUE THREAD

**Issue by kunalsood** [FreshRSS/FreshRSS#3421]
I'm working on adding FreshRSS integration to my RSS Reader, and found that import and export endpoints are not implemented in FreshRSS' `greader.php` file. Just wondering if there is any plan to support either of these.

I can generate a OPML file myself using my app's local cache/db, so I can get away without access to an export endpoint, but, an import endpoint would be nice to have.

I understand different services implement the import endpoint differently (i.e. BazQux vs FeedHQ), so, maybe there is not an agreed upon standard way of doing this. Either way, I just thought I would bring this up, just in case there is any interest.

**Comment by Alkarex** [comment]
Hello,
If you have seen seen feature elsewhere in a product using the Google Reader API, can you link to a description of the API part to do so (or to a couple of variants if you have them) and we will implement

**Comment by kunalsood** [comment]
Sure thing.

Here is **FeedHQ**'s API documentation for their export endpoint: https://feedhq.readthedocs.io/en/latest/api/reference.html#subscription-export
Here is an excerpt from it:
```
Returns the list of subscriptions in OPML (XML) format.

URL: /reader/api/0/subscription/export
Method: GET
Supported formats: XML (OPML)
```

And, this is the documentation for FeedHQ's import endpoint: https://feedhq.readthedocs.io/en/latest/api/reference.html#subscription-import
Here is an excerpt from it:
```
Imports all subscriptions from an OPML file.

URL: /reader/api/0/subscription/import
Method: POST
Supported formats: Returns “OK: <count>” in plain text

Instead of form data, this API call expects the contents of the OPML file to be provided directly in the request body.
```

**The Old Reader** seems to only implement the export endpoint, you can find their documentation at https://github.com/theoldreader/api
Here is an excerpt about the export endpoint from their documentation:
```
Subscriptions OPML

GET https://theoldreader.com/reader/subscriptions/export
```

And, finally, **BazQux**, their API documentation is available at https://github.com/bazqux/bazqux-api
Here is an excerpt about the export endpoint from BazQux's documentation:
```
Subscriptions OPML

https://bazqux.com/reader/subscriptions/export
```

And, here is an excerpt about the import endpoint from BazQux's documentation:
```
Subscriptions import

NB: This method is an extension to GR API.

https://bazqux.com/reader/api/0/import/opml

Post OPML data in opml parameter (in usual application/x-www-form-urlencoded form). It will return percent of feeds currently processed (integer number in plain text).

You can then poll (each 3 seconds for example)

https://bazqux.com/reader/api/0/import/percent-complete

till it return "100".
```

**Comment by Alkarex** [comment]
@kunalsood Would you be able to test this patch? https://github.com/FreshRSS/FreshRSS/pull/3424

**Comment by kunalsood** [comment]
@Alkarex It works perfectly (i.e. both import & export), and exactly like FeedHQ's implementation.

The only thing I would add to your API documentation is to tell users that the import endpoint can take a while to return a response especially if they are trying to import a lot of new feeds, as it runs `actualizeFeed` after the import which happens synchronously (I think?). I had to increase the timeout interval for the requests I was making to the import endpoint.

Either way, this is awesome. Thanks so much for the quick turnaround.

PS: I have an iOS & macOS app called **lire** (http://lireapp.com) that I'm working on, to add FreshRSS support, implementation for the iOS app is complete, but, I'll wait for this patch to be merged before pushing the first test build to my testers. If you have any Apple device & would be interested in testing this, I would be happy to include you, please let me know.

**Comment by Alkarex** [comment]
Thanks for testing @kunalsood 
Indeed, the feeds are then fetched synchronously. (Ideally, I would have liked to have two distinct calls for importing an OPML, and for refreshing the feeds).

I do not have any Apple device to test.

We have a list of known compatible clients:
https://github.com/FreshRSS/FreshRSS/blob/master/README.md#apis--native-apps
Some criteria are clear, while some others are more a manual assessment, slightly subjective.
My baseline for performance & synchronisation strategy is the old News+ (top of the table - you are welcome to compare yourself if you have an Android device), using a database of at least 100k+ articles with 5k+ unread articles, 500+ favourites. I could make you an account on a test server, as I cannot test myself, to generate a log / trace.
Please open a new issue to add your client to our table.
