### ISSUE TITLE
Suddenly Feed is not retrieved when using css selector

### ISSUE THREAD

**Issue by rom-1** [FreshRSS/FreshRSS#3425]
Hi,

There is a very popular german IT News Page offering a feed with the url: _https://www.heise.de/rss/heise-atom.xml_
According to validator.w3.org this feed is valid. 

Since 48 hours FreshRSS is not able to retrieve new posts when using CSS Selectors. I am using the following CSS Selectors in my Feed config: 
`#meldung .article-content, #meldung p.a-article-header__lead, #meldung .article-image`
Testing the selectors (using the "test button") with the existing posts is working fine, there seem to be no issues. 

I have no idea whats going wrong, as the error log in FreshRSS is empty, no errors are shown. FreshRSS is able to pull new posts of that feed without any problems once I delete the CSS Selectors. But once I input them again, there are no new feed posts fetched at all. 

Deleting the feed cache and reload all articles seem to do something (long load times), but then I only see an empty feed.

Any idea whats going wrong here?

Edit: This feed was running fine in the last few weeks. I did not change anything on my end, so probably sth. is changed on the feed XML itself. But I have no clues what could cause this behaviour with FreshRSS.

**Comment by rom-1** [comment]
found the culprit: my shared webhosting service updated my production environment without telling me, and dropped (deleted!) some php binaries which I am using for the update cronjob. 🤬🤬🤬

sorry for any inconvenience

**Comment by aledeg** [comment]
How did you find out? Is there a process you used to narrow it down?

**Comment by rom-1** [comment]
not really. I just noticed after 24h, that all my feeds did not pull any new articles/posts. That's when I started investigating if my cronjob was still running, which should update all my feeds every 20 minutes:
`/usr/bin/php7.4 [web_root]/rss.rootdir.net/FreshRSS/app/actualize_script.php > /tmp/FreshRSS.log 2>&1`

When I run this command manually in a ssh console, got an error message that /usr/bin/php7.4 was not found. Switched to /usr/bin/php8.0, and all problems are gone. 

In my tests before I just deleted the feed from FreshRSS, and readded it as a new feed (without css selectors), which seems to pull all articles manually without running the cronjob.

**Comment by aledeg** [comment]
I am trying to figure out how we could automate those test to help users to pinpoint what's wrong with their system before they reach us here. If you have such ideas, let me know!

**Comment by rom-1** [comment]
Ask and you shall receive, just my 2 cents/suggestion:

FreshRSS supports hosting outside of a controlled docker environment, e.g. on foreign webservers, or shared hosting with strange PHP Versions, linux distributions, windows OS/IIS Webserver, maybe strange environment variables, strange paths, and so on... **it is almost impossible for you guys** to automatically check for the "correct" setup of the feed-update-process in this scenario. I mean, you even offer 2 different options for updating feeds (cron, systemd), so you have no idea how the end user is going to set up his feed update process.

So, I would consider a different non-technical approach to counter this: As FreshRSS is mostly a "News" Reader, I guess it is in everyone's interest that it updates all feeds on a regular basis. For a good RSS Reader to be useful, the application should at least trigger a feed update once every 24hours - if it does not, something is wrong. So my suggestion would be, that 

- your script "actualize_script.php" should update a "last successfully run" or "last successfully updated" timestamp within the database
- IF the current timestamp (now) is > 24hours to the last successfully update, the user interface in the main window should show a yellow warning bar (on the top, [see mockup screenshot](https://user-images.githubusercontent.com/37835829/107129413-9013e100-68c5-11eb-8fac-81c7fa111a07.gif)) to the end user saying "**Warning: Last feed update was more than 24 hours ago, consider to check your [Feed Update Process](https://freshrss.github.io/FreshRSS/en/admins/08_FeedUpdates.html)**"
- when the timestamp is not set (yet!) right after a clean/fresh install, there should be no warning because the update script is not set up yet/never run before
- There should be an option within "options" to "disable warning about feed update time" if somebody really wants to update his feeds in an 48h cycle (which does not make sense, but well, maybe sb wants to have this)

This would inform the user that something is wrong with his feed update process, and he will take a look into that before posting here.

Edit: Of course, that 24h timeframe is debatable. For my personal setup, I would love to lower that to 6hours, and having a lower value might possibly even further decrease the post frequency here. ;)

**Comment by Frenzie** [comment]
I think that broadly makes sense.

**Comment by aledeg** [comment]
Thank you for your insight! I think what you are proposing makes sense and is doable. Do you mind open a dedicated issue with that?
