### ISSUE TITLE
How to add feed from rss generator inside docker-compose

### ISSUE THREAD

**Issue by vorant94** [FreshRSS/FreshRSS#3428]
Hi, there!

I have FreshRSS running on my VPS for some time. In order to get feeds from some sites that are not providing it by their own I also deployed RSSHub instance. As for now both FreshRSS and RSSHub are open outside through reverse proxy, so to get my feed from RSSHub I need to use its domain name and so on (`rsshub.example.com/telegram/channel/{some_channel_name}`)

Since RSSHub and FreshRSS in my case are deployed by one `docker-compose.yml` I wonder if I can get things from RSSHub into FreshRSS without opening RSSHub itself outside Docker? I tried to add feed by url like `{rsshub_container_hostname}/telegram/channel/{some_channel_name}`, but I get an error `Unknown error for feed [https://{rsshub_container_hostname}/telegram/channel/some_channel_name]`

So in the end I wanted to ask is it possible to get generated RSS feed from other Docker container without opening its generator container to outside world like FreshRSS itself? If so where do I make a mistake?

**Comment by Alkarex** [comment]
Your RSSHub and FreshRSS must be on the same Docker network.
Then, do not use https but `http://rsshub_container_hostname/...`
Share your docker-compose for more info

**Comment by vorant94** [comment]
sorry, my bad... docker-compose creates network automatically, so this was not the issue. the issue was to set up **hostname** and also **port** of RSSHub correctly
