### ISSUE TITLE
Error 500 after system update

### ISSUE THREAD

**Issue by GaspardBoutry** [FreshRSS/FreshRSS#3434]
Hello,

I am using FreshRSS on my PC, running on Manjaro. Yesterday, I made a huge update (>250 packets).
This morning, FreshRSS could not load, because httpd could not start. I figured that the issue was a renaming of modules (php7_module.conf became php_module.conf, libphp7.so became libphp.so...), and I was able to start httpd.

Now, I still can't start FreshRSS. My error log gives the following :
`[Wed Feb 10 09:03:16.772746 2021] [php:error] [pid 3586] [client 127.0.0.1:42206] PHP Fatal error:  Uncaught Error: Call to undefined function get_magic_quotes_gpc() in /srv/http/FreshRSS-master/lib/Minz/Request.php:303\nStack trace:\n#0 /srv/http/FreshRSS-master/lib/Minz/Request.php(103): Minz_Request::magicQuotesOff()\n#1 /srv/http/FreshRSS-master/lib/Minz/FrontController.php(39): Minz_Request::init()\n#2 /srv/http/FreshRSS-master/p/i/index.php(46): Minz_FrontController->__construct()\n#3 {main}\n  thrown in /srv/http/FreshRSS-master/lib/Minz/Request.php on line 303`

Thanks for your help

**Comment by Frenzie** [comment]
That most likely means you're using an older version of FreshRSS. That should already have been removed a while ago, for version 1.16: https://github.com/FreshRSS/FreshRSS/pull/2698

However, if you've updated to PHP 8 then you'd need current master, rather than 1.17.

**Comment by GaspardBoutry** [comment]
Oh yes, it seems I am using 1.15.2 of FreshRSS, and I indeed got PHP8 installed.
I did the update to the master, and now it works fine
Many thanks!
