### ISSUE TITLE
Rename the "tag management" settings page to "label management"

### ISSUE THREAD

**Issue by hesch** [FreshRSS/FreshRSS#3444]
Maybe I am just confused, but doesn't the tag management settings page actually manage labels? My current understanding of tags vs labels is the following:
- Tags can be included in the RSS-Feed inside of `<category></category>`
- Labels are user defined and can be applied to single news items (and there are plans to label them automatically)

If this is correct, we should rename tag management to label management!

**Comment by Alkarex** [comment]
Indeed, good point
