### ISSUE TITLE
[Bug] Blue Lagoon and Screwdriver themes are removing the menu headers

### ISSUE THREAD

**Issue by aledeg** [FreshRSS/FreshRSS#3447]
This behavior is mostly fine but it removes also important items from the user query menu.
In that menu, there is a direct link to the user query management page which is not displayed.

**EDIT**
There is only 3 occurrences of the use of the `dropdown-header` class. One is for the `user query` menu, one is for the `configuration` menu, one is for the `administration` menu.

There is 2 ways of handling that. Either we remove the rule from the themes or we change the layout.

I think, the most robust way is the later. I suggest we add an edit button on each query as @rom-1 suggested, and we remove the edit (the `cog` icon) from the header. We should also add information on the menu button when hovering to help user understand it. It might be interesting to also change the icon and use a bookmark icon (something like [this one](https://fontawesome.com/icons/bookmark?style=solid)) instead of the one in use at the moment.

**Comment by aledeg** [comment]
@Frenzie @Alkarex could you review my suggestions and tell me if you think I should proceed the way I've described to address that issue?

**Comment by Frenzie** [comment]
The icon (or something like it) looks fine, but without grepping the source I'm not immediately sure which interface elements you're talking about?

(I don't have the FreshRSS source on my work laptop — easy to remedy of course but it means I can't give you my full thoughts right now. :-) )

**Comment by aledeg** [comment]
![Screen Shot 2021-02-17 at 06 57 02](https://user-images.githubusercontent.com/3056148/108201944-6db46b80-70ee-11eb-997d-35ea35e5bc36.png)
I am talking about the first line in that drop-down.

**Comment by Frenzie** [comment]
The edit cog is a difficult one. Easier editing vs. needing to avoid part of what looks like the clickable area. I'm not too fond of getting rid of the explanatory header though. :-/

**Comment by Alkarex** [comment]
I think the themes should indeed be edited to include this header
