### ISSUE TITLE
[Feature] 3 columns view possible?

### ISSUE THREAD

**Issue by gnrmarcel** [FreshRSS/FreshRSS#3449]
I switched from Tiny RSS to Fresh RSS and am especially impressed with the speed. I use the Reeder app on macOS a lot, but every now and then I read my feeds in the browser.

So my question, is it possible to switch to a 3-column view like in Tiny RSS - possibly via CSS? See screenshot?

![image](https://user-images.githubusercontent.com/886146/107880166-65d1ad00-6edd-11eb-8091-aa4f016dbe16.png)

**Comment by aledeg** [comment]
At the moment, it is not possible. PR are welcomed though!

**Comment by erraticallyefficient** [comment]
Hey @gnrmarcel , have you seen the [ThreePanesView](https://framagit.org/nicofrand/xextension-threepanesview) extension? 
I haven't used it, but it looks like it does what you're looking for.

**Comment by gnrmarcel** [comment]
Thx! @erraticallyefficient

**Comment by math-GH** [comment]
ThreePanesView does it how you like it.

I guess we could close this "issue"

**Comment by nhan000** [comment]
Hi, how can I install the ThreePaneView extension if I'm using flossboxin via Edge browser? In the Configuration there is [ThreePanesView](https://framagit.org/nicofrand/xextension-threepanesview) but I don't know how to install it? 

![image](https://github.com/FreshRSS/Extensions/assets/85216095/3cf93a19-4a85-43f7-97a9-998494535570)

Thank you!

**Comment by math-GH** [comment]
@nhan000 : You need access to the source code on your server. For more information, please read the manual: https://freshrss.github.io/FreshRSS/en/admins/15_extensions.html
