### ISSUE TITLE
[Feature request] Add a parameter to either replace or update article content while using a CSS selector

### ISSUE THREAD

**Issue by aledeg** [FreshRSS/FreshRSS#3451]
By default, the parameter would replace the content.

Some feeds have valuable information even though it's partial. The idea is then to use the CSS selector to grab the complete data. But if the data provided is slightly different from the feed itself, the data from the feed is lost.

To work around that limitation, my only solution is to have an extension grabbing the content for those feeds. It's not really scalable since I have to write an extension per feed.
A parameter would be easier.

**Comment by aledeg** [comment]
@Alkarex Where would you add that parameter? As a new table field or a new attribute value?
I've made some test with hard-coded values with success!

**Comment by Alkarex** [comment]
@aledeg As an attribute :-)
