### ISSUE TITLE
Not all RSS feeds are updated

### ISSUE THREAD

**Issue by gnrmarcel** [FreshRSS/FreshRSS#3452]
I'm new to FreshRSS and am actually very happy, except with the RSS feed update.

FreshRSS is installed on a normal web hosting package and there I have set up a cron job that runs every 15 minutes. The URL is: https://meine-rss-domain.de/p/i/?c=feed&a=actualize&token=meintoken

But I have the problem that feeds are sometimes not updated for 1-2h, although there are definitely new articles there. What is the reason for this? What am I doing wrong that not all RSS feeds are updated in FreshRSS?

If I update the feeds manually in FreshRSS, all 60 feeds run through very quickly and are then also updated displayed.

**Comment by gnrmarcel** [comment]
Sorry, it was my mistake. I had not saved the authorization token correctly.

**Comment by Alkarex** [comment]
Ok. If possible, try to favour a proper local cron job instead of Web cron job
