### ISSUE TITLE
How to quote a "+" char in filter query?

### ISSUE THREAD

**Issue by sleeksorrow** [FreshRSS/FreshRSS#3454]
I have a feed from german IT news portal "Heise", that has some articles that are behind paywalls. Those articles are prefixed with the string "heise+" in title.

Sadly when filtering for that, with query "intitle:heise+", it always matches any article with "heise" in it, ignoring that "+" char completely. I assume the plus char has some syntax meaning which I need to disable. I tried escaping, single quoting, double quoting, but nothing helps.

Example screenshot when filtering for "intitle:heise+" with every syntax mentioned above:
![Screenshot_20210216_195604](https://user-images.githubusercontent.com/390307/108108728-4a0f0800-7091-11eb-806e-5c98dfb91886.png)

**Comment by aledeg** [comment]
Try using `intitle:"heise+"`

**Comment by sleeksorrow** [comment]
That's the variant "double quote" that I mentioned above. No change in behavior.

**Comment by aledeg** [comment]
actually, you've mentioned `"intitle:heise+"` and I mentioned `intitle:"heise+"`. The first quote is not located at the same place. But I do not know if that make a difference.

**Comment by aledeg** [comment]
Ok, I found out that it wont work. There is something in the code that is trimming the `+` character.
https://github.com/FreshRSS/FreshRSS/blob/fe1fba9828ad4d68a3cc93ed5f8e361f34e5a873/app/Models/Search.php#L165

I guess it's to remove spaces from the URL. I think that this should be addressed in a different way not only to accommodate your use-case but to be more precise with what we are doing. I have no idea how though!

**Comment by Frenzie** [comment]
Shouldn't something like urlencode on the one side and urldecode on the other take care of that?

**Comment by aledeg** [comment]
Probably! But I never read that code before and I do not want to break it :)

**Comment by sleeksorrow** [comment]
Thanks for all of you looking into that.
Regarding the quotes: The `"intitle:heise+"` actually meant, that I was using as query, what's _inside_ the double quotes. And the "double quote" method I mentioned later meant that I was putting the search term in double quotes like you did. I understand that my wording was misleading. Thanks for verifying it in spite of that.

**Comment by sleeksorrow** [comment]
Regarding the replacement of "+" with whitespaces, I think the documentation gives a hint on why this is used. I think it's for the `#tag+with+whitespace` syntax.
https://freshrss.github.io/FreshRSS/en/users/03_Main_view.html#filtering-articles

**Comment by aledeg** [comment]
@Alkarex According to our documentation, there is 2 ways of searching for spaces. Either to enclose the search string between quotes or using the `+` sign. The later is described to be used for tags while the former for other string searches.
But the code does not reflect that. The use of `+` is allowed everywhere while the use of quotes is allowed everywhere except for tags.

I think we should remove the use of `+` for everything except for the tags (even for that, I am not sure). I find it confusing to have 2 different ways of handling the same thing.

I think the first step to address that is to remove the use of the `decodeSpaces` method for every method except the one handling the tags. The second optional step will be to change the behavior for the tag as well (including the documentation).

What do you think?

**Comment by Alkarex** [comment]
Yes @aledeg , I agree.

We need to double-check, but PHP should be doing the GET decoding automatically:
* Raw input `X+Y` must be converted to `X Y`
* Raw input `X%20Y` must be converted to `X Y`
* Raw input `Y%2BY` must be converted to `X+Y`

Yes also to first fix everything except the tags.

Just a quick thought, maybe the `X\ Y` syntax could do the job, i.e. backslash in front of a meaningful space for e.g. tags and other unquoted strings. This is quite standard in several tools.

**Comment by Alkarex** [comment]
More details on the suggestion:
Use the `X\ Y` syntax for the input. Upon reception, convert `\ ` to `U+00A0` (non-breaking space) for the rest of the processing (splitting, etc.). Convert `U+00A0` back to `U+0020` (normal space) when getting the values for the actual request in DB.

**Comment by aledeg** [comment]
@Alkarex I'd rather keep the search with space using quotation for now. Maybe we can add the unbreakable space later on.
