### ISSUE TITLE
Update Travis for PHP 7.4 and PHP 8

### ISSUE THREAD

**Issue by BrookeDot** [FreshRSS/FreshRSS#3458]
Currently Travis runs tests on PHP 5.6 and 7.3. Should these tests be upgraded for PHP 7.4 and PHP 8.0?

**Comment by Frenzie** [comment]
Definitely not. That 5.6 is paramount. It should always be the lowest supported version. But that 7.3 can be switched to 7.4 and/or 8.x.

**Comment by BrookeDot** [comment]
Thanks for the feedback @Frenzie I created a PR that adds both PHP 7.4 and 8.0 allowing failures for 8.0 (for now) #3459. 

Right now tests are run on:
- 7.3
- 7.1
- 5.6

It sounds like maybe you are suggesting:
- 8.0 (allow failures) 
- 7.4
- 5.6

Or would you like to keep 7.1 and 7.3 around? And in that case should 7.2 be added?

**Comment by Frenzie** [comment]
> Or would you like to keep 7.1 and 7.3 around? And in that case should 7.2 be added?

I don't know if it's worthwhile to run them on *all* versions or if that's just wasting electricity, but I do think it should run on several different versions. See https://github.com/FreshRSS/FreshRSS/pull/2721 for some discussion.

**Comment by Alkarex** [comment]
Indeed, I suggest we only test the oldest and newest versions we support
