### ISSUE TITLE
Update Zip functions to use the Object API

### ISSUE THREAD

**Issue by BrookeDot** [FreshRSS/FreshRSS#3460]
While looking into updating the tests for PHP 8.0 (#3458) The first set of tests ran for PHP 8 and the deprecation of the `zip_` functions was flagged. 

```
FILE: FreshRSS/FreshRSS/app/Controllers/importExportController.php

--------------------------------------------------------------------------------
FOUND 6 ERRORS AFFECTING 6 LINES
--------------------------------------------------------------------------------
 68 | ERROR | Function zip_open() has been deprecated
 73 | ERROR | Function zip_read() has been deprecated
 78 | ERROR | Function zip_entry_name() has been deprecated
 80 | ERROR | Function zip_entry_read() has been deprecated
 82 | ERROR | Function zip_entry_filesize() has been deprecated
 87 | ERROR | Function zip_close() has been deprecated
--------------------------------------------------------------------------------
```

I did limited research but it appears these should be replaced with the Object API:

For example: `zip_open()` replaced with `ZipArchive::open` 

`zip_open` : https://www.php.net/manual/en/function.zip-open.php
`ZipArchive::open` : https://www.php.net/manual/en/ziparchive.open.php

**Comment by Alkarex** [comment]
Indeed, we should update the whole ZIP extension from https://php.net/ref.zip (deprecated) to https://php.net/class.ziparchive (supported for all our PHP versions).
