### ISSUE TITLE
Feed works well on other reader but doesn't work on FreshRSS

### ISSUE THREAD

**Issue by starsareintherose** [FreshRSS/FreshRSS#3467]
The RSS source can work well in Fluent Reader (Windows 10), but I try it on the FreshRSS, it doesn't work.  Many sources face the situation, some of them pass the valid test and some of them are not.
https://rsshub.malacology.net/zhishifenzi/news/biology
CentOS7, PHP7.4 MySQL5.5.62
Best regards
Guoyi

**Comment by Frenzie** [comment]
There are a few warnings in the validator https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Frsshub.malacology.net%2Fzhishifenzi%2Fnews%2Fbiology

But… it works for me?

![Screenshot_2021-02-20_10-54-22](https://user-images.githubusercontent.com/202757/108591634-0c003580-736a-11eb-9ae9-acd56ff578a3.png)

**Comment by starsareintherose** [comment]
It's too strange. The status of this and that are the same on my plate. Is it related to openlog command?
https://rsshub.malacology.net/guokr/scientific
https://www.tandfonline.com/feed/rss/tmos20
![image](https://user-images.githubusercontent.com/37733075/108591730-2572a300-73a5-11eb-903d-1ab3f87eaf90.png)
![image](https://user-images.githubusercontent.com/37733075/108591741-34595580-73a5-11eb-88b5-2d73bb75e3ac.png)

**Comment by Frenzie** [comment]
Is there any sort of error message in your logs? Maybe the server just had a temporary hiccup.

**Comment by starsareintherose** [comment]
No, there were no error messages. But I don't know how to access to my logs. And no photos can be loaded. It's not a temporary hiccup.

**Comment by Frenzie** [comment]
There are multiple places you could look for logs, but I specifically meant the FreshRSS ones you can find here:
![Screenshot_2021-02-20_11-46-58](https://user-images.githubusercontent.com/202757/108592997-6b157880-7371-11eb-9e70-560725ce8a8e.png)

Here are some sample errors:
![Screenshot_2021-02-20_11-48-04](https://user-images.githubusercontent.com/202757/108593025-85e7ed00-7371-11eb-8f10-6c1edddfe9d5.png)

**Comment by starsareintherose** [comment]
2021-02-20 17:44:23
image_proxy_url_encode does not exist in configuration
2021-02-20 17:44:23
image_proxy_scheme_include does not exist in configuration
2021-02-20 17:44:23
image_proxy_scheme_default does not exist in configuration
2021-02-20 17:44:23
image_proxy_force does not exist in configuration
2021-02-20 17:44:23
image_proxy_scheme_https does not exist in configuration
2021-02-20 17:44:23
image_proxy_scheme_http does not exist in configuration
2021-02-20 17:44:23
image_proxy_url does not exist in configuration
2021-02-20 17:02:24
Unknown error for feed [https://rsshub.app/zhishifenzi/news/biology]
2021-02-20 16:54:31
cURL error 28: Failed to connect to rsshub.app port 443: Connection timed out [https://rsshub.app/jianshu/user/d27c7f02a323]
2021-02-20 16:54:30
cURL error 28: Failed to connect to rsshub.app port 443: Connection timed out [https://rsshub.app/jianshu/user/740f4b0f11e9]
2021-02-20 16:54:30
cURL error 28: Failed to connect to rsshub.app port 443: Connection timed out [https://rsshub.app/jianshu/user/619b87e54936]
2021-02-20 16:54:29
cURL error 28: Failed to connect to rsshub.app port 443: Connection timed out [https://rsshub.app/blogs/wordpress/breure.wordpress.com]
2021-02-20 16:54:23
cURL error 28: Failed to connect to rsshub.app port 443: Connection timed out [https://rsshub.app/stork/keyword/1268102/vUD9LOHG1f]
2021-02-20 16:54:23
cURL error 28: Failed to connect to rsshub.app port 443: Connection timed out [https://rsshub.app/guokr/scientific]
2021-02-20 16:54:23
cURL error 28: Failed to connect to rsshub.app port 443: Connection timed out [https://rsshub.app/zhihu/hotlist]
2021-02-20 16:54:23
cURL error 28: Failed to connect to rsshub.app port 443: Connection timed out [https://rsshub.app/zhihu/hot/school]
2021-02-20 16:54:23
SQL error updateTTL 2: Duplicate column name 'ttl' ALTER TABLE `_feed` ADD COLUMN ttl INT NOT NULL DEFAULT 0
2021-02-20 16:54:23
SQL warning updateTTL 1: Deadlock found when trying to get lock; try restarting transaction UPDATE `_feed` SET ttl=:new_value WHERE ttl=:old_value
2021-02-20 16:54:22
cURL error 35: OpenSSL SSL_connect: Connection reset by peer in connection to enaliarctos7th.blogspot.com:443 [https://enaliarctos7th.blogspot.com/feeds/posts/default?alt=rss]
2021-02-20 16:54:22
cURL error 28: Failed to connect to rsshub.app port 443: Connection timed out [https://rsshub.app/zhihu/hot/science]
2021-02-20 16:54:21
cURL error 28: Failed to connect to rsshub.app port 443: Connection timed out [https://rsshub.app/zhishifenzi/news/biology]
2021-02-20 16:54:21
cURL error 22: The requested URL returned error: 403 Forbidden [https://www.tandfonline.com/feed/rss/tmos20]
2021-02-20 16:54:21
cURL error 35: OpenSSL SSL_connect: Connection reset by peer in connection to rsshub.app:443 [https://rsshub.app/citavi]
2021-02-20 16:54:14
SQL error updateTTL 2: Duplicate column name 'ttl' ALTER TABLE `_feed` ADD COLUMN ttl INT NOT NULL DEFAULT 0
2021-02-20 16:54:14
SQL error updateTTL 2: Duplicate column name 'ttl' ALTER TABLE `_feed` ADD COLUMN ttl INT NOT NULL DEFAULT 0
2021-02-20 16:54:14
SQL error updateTTL 2: Duplicate column name 'ttl' ALTER TABLE `_feed` ADD COLUMN ttl INT NOT NULL DEFAULT 0
2021-02-20 16:54:14
SQL warning updateTTL 1: Lock wait timeout exceeded; try restarting transaction UPDATE `_feed` SET ttl=:new_value WHERE ttl=:old_value
2021-02-20 16:54:14
SQL warning updateTTL 1: Lock wait timeout exceeded; try restarting transaction UPDATE `_feed` SET ttl=:new_value WHERE ttl=:old_value
2021-02-20 16:53:23
SQL warning updateTTL 1: Deadlock found when trying to get lock; try restarting transaction UPDATE `_feed` SET ttl=:new_value WHERE ttl=:old_value
2021-02-20 16:53:07
File cannot be uploaded. Error code: 4
2021-02-20 16:44:40
Minz_Mailer cannot send a message: Could not instantiate mail function.
2021-02-20 16:36:54
Password mismatch for user=starsareintherose, nonce=66b761ebb344c4fb37453689a55714445dee654d, c=
2021-02-20 16:31:23
Password mismatch for user=starsareintherose, nonce=a480172433948d2031c8d708a5fe3182f05d4bdf, c=
2021-02-20 16:30:38
Password mismatch for user=starsareintherose, nonce=254fd28450e783ee0474be8fb3db65cf30181366, c=
2021-02-20 16:30:32
Password mismatch for user=starsareintherose, nonce=6f28570fd46304543cef77cefb17e910df9fe9e7, c=

**Comment by Frenzie** [comment]
Nothing related to `https://rsshub.malacology.net/zhishifenzi/news/biology`? I do notice this one, which looks somewhat similar:

```
Unknown error for feed [https://rsshub.app/zhishifenzi/news/biology]
2021-02-20 16:54:31
cURL error 28: Failed to connect to rsshub.app port 443: Connection timed out [https://rsshub.app/jianshu/user/d27c7f02a323]
```

For me that one does load, but a bit slowly.

I'm not sure what could cause the connection to time out so much, but I'm thinking the cause might be related more to your server or its connection than to anything else. Maybe try SSH-ing into it. A command like `mtr rsshub.malacology.net` would give you some information about where packet loss occurs. In my case I get 0 packet loss in Europe, but the connection between Europe and China specifically on IP `202.97.89.109` shows a rather disturbing more than 50 % packet loss.

From how I understand the Chinese internet you shouldn't have that problem within China though.

**Comment by starsareintherose** [comment]
Right, https://rsshub.app/zhishifenzi/news/biology can be also used as https://rsshub.malacology.net/zhishifenzi/news/biology. I use Chinese Cloud, it also doesn't work, but it can work in Europea, it's too strange.

**Comment by andreascschmidt** [comment]
I have had some feed adding issues with pages that are behind Cloudflare. Fetching from there results always into a challenge.  What I have noted is that my servers IP seems to be in a "poor IP range list" So from home it works fine from another testserver in the US too, but my main one is getting rejected. Might this be the issue here?

**Comment by DarrienG** [comment]
I'm getting similar issues here. When I try to add the BBC RSS feed, I get:

```
2021-02-28 21:19:49Unknown error for feed [https://feeds.bbci.co.uk/news/world/rss.xml#]
```

I can confirm the validity of this RSS feed: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Ffeeds.bbci.co.uk%2Fnews%2Fworld%2Frss.xml%23

I am from the US, and set a gracious timeout.

This is a new installation mind you, and it seems to happen with any feed I try to add. Using SQLite installation + Docker.

Edit: This may be an issue with my self hosted solution. Trying out another RSS reader has posed similar issues. Investigating...

**Comment by Alkarex** [comment]
@DarrienG https://feeds.bbci.co.uk/news/world/rss.xml works for me with FreshRSS. Try from your server:

```sh
curl -v 'https://feeds.bbci.co.uk/news/world/rss.xml'
```

**Comment by DarrienG** [comment]
Apologies, something is wrong with my docker installation. Changing to using the host network fixes it, so this is on my end. I appreciate the quick response.

**Comment by aledeg** [comment]
Thank you for the feed back. In the meantime, if you find that something is not well presented in the documentation, feel free to update it. That would be appreciated.
