### ISSUE TITLE
(Mobile display style): Is it possible to display the full title in two/three lines on mobile devices?

### ISSUE THREAD

**Issue by stillli** [FreshRSS/FreshRSS#3474]
![image](https://user-images.githubusercontent.com/5086318/108639474-b196d000-7462-11eb-9140-4f15cda6f355.jpeg)

Hi team: I want to read as much information as possible through the title. Is it possible to display two lines or three lines title when text overflow?

**Comment by aledeg** [comment]
Use `TitleWrap` extension to display the full title.
