### ISSUE TITLE
Shortcuts: unicode characters not allowed

### ISSUE THREAD

**Issue by minami-o** [FreshRSS/FreshRSS#3481]
Hi,
I’m using the French bépo keyboard layout and it seems keys like "é" or ".", which are easily accessible, cannot be assigned as shortcuts: when I validate the shortcuts after setting them, they revert to the default value.
Is there a way such characters could be considered as valid by FreshRSS?
Thanks!

**Comment by aledeg** [comment]
There is a list of accepted characters. This one is not in the list.
The course of action is either add new characters to the validation process or remove the validation process.
Any way, PR welcomed.

**Comment by minami-o** [comment]
Thanks for your prompt feedback!
Can’t promise anything, but I’ll see what I can do!

**Comment by aledeg** [comment]
Look there for the definition and the validation of the supported shortcuts:
https://github.com/FreshRSS/FreshRSS/blob/064288ed6228d3d56b2231aadd507eb62ae8662c/lib/lib_rss.php#L527-L562

Look here for the view update:
https://github.com/FreshRSS/FreshRSS/blob/064288ed6228d3d56b2231aadd507eb62ae8662c/app/Controllers/configureController.php#L177

Look here for the template use:
https://github.com/FreshRSS/FreshRSS/blob/064288ed6228d3d56b2231aadd507eb62ae8662c/app/views/configure/shortcut.phtml#L6-L10

**Comment by aledeg** [comment]
I am thinking that maybe we do not need a validation.

**Comment by Frenzie** [comment]
Perhaps the thought is something like maximum compatibility between different systems? But indeed I don't see a clear reason to.

**Comment by minami-o** [comment]
My understanding, from the PHP side, is that there is no need to have a list of authorized keys: an exclusion list for most control characters might work out just fine. This is based off this document: https://w3c.github.io/uievents-key/
The capture of key presses is done in js, though, if I’m not mistaken, but I haven’t check this side yet – not sure if it has any impact.

**Comment by Frenzie** [comment]
I mean in the sense that allowing `é` might've been regarded as a shooting yourself in the foot situation. You might not be easily able to type `é` on systems that aren't your own. But I'm just armchair philosophizing; maybe the commit message says. ;-)

**Comment by aledeg** [comment]
@minami-o Please test the linked PR.
