### ISSUE TITLE
[Feature] Allow setting custom user-agent when retrieving particular feeds

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#3493]
**Is your feature request related to a problem? Please describe.**
Many websites use Google's FeedBurner to serve their public feeds. This allows Google to track you when you use the feed, and also makes it impossible to fetch full article content with FreshRSS.

**Describe the solution you'd like**
Publishers create FeedBurner feeds from normal RSS feeds. However, in many cases the original feed is only accessible with a user-agent of `FeedBurner` (https://support.google.com/feedburner/answer/78464). Adding an option to have FreshRSS request these feeds using a `FeedBurner` user agent would allow users to read the original version of these feeds in FreshRSS.

**Comment by Alkarex** [comment]
After https://github.com/FreshRSS/FreshRSS/pull/3367 has prepared the ability to have some custom cURL parameters per feed, this is an easy thing to add (`CURLOPT_USERAGENT`). PR welcome!
