### ISSUE TITLE
Docker /var/www/FreshRSS not writable

### ISSUE THREAD

**Issue by daberlin** [FreshRSS/FreshRSS#3495]
**Describe the bug**
Run "docker-compose -f docker-compose.yml up"
Perform setup
Go to Settings -> Update, click button.
Error message: Directory /var/www/FreshRSS not writable.

**To Reproduce**
See above.

**Expected behavior**
Directory should be writable.

**Screenshots**
none

**Environment information (please complete the following information):**
Docker

**Additional context**
It works, withe the following Dockerfile:

FROM freshrss/freshrss:latest
WORKDIR /var/www/FreshRSS
RUN chown :www-data .
RUN chmod g+w .

**Comment by Alkarex** [comment]
Yes, this is one of the many things that is awaiting a rewrite of our update process https://github.com/FreshRSS/FreshRSS/pull/1760

More precisely here, when inside Docker, we are not supposed to use FreshRSS' own update mechanism, as this is supposed to be best done at Docker level. I have fixed that https://github.com/FreshRSS/FreshRSS/pull/3496 (an option originally made for YunoHost, which has similar requirements). Allowing the Web server to write over all the directories is not so nice, not least for security reasons.

Although not recommended, it will still be possible to manually allow FreshRSS' own update mechanism by doing something similar to what you have done, and by setting `'disable_update' => false,` in `./data/config.php`.
