### ISSUE TITLE
[Feature Request] Mark articles as read with filter actions on category level

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#3497]
Hello,

Sorry if it's not really the right place to ask my question. Is it possible to ban/hide some words ? Like "Bons plans", "promo", etc ? I searched in administration but not found, maybe I missed the setting ?

Thank you

**Comment by Alkarex** [comment]
Hello,
We have a function to auto mark as read articles matching various keywords.
Right now and in the upcoming version 1.18.0 it is at feed-level, but in version 1.19.0 it will be possible to do that at category or global level as well.
Example:

![image](https://user-images.githubusercontent.com/1008324/110202964-f1e74c80-7e6b-11eb-8e55-7208deab88dc.png)

Note: it will only be applied to *new* articles.

**Comment by githupper** [comment]
@Alkarex would this global level filter be automatically compared and marked as read upon downloading or must be manually run by user?

**Comment by Alkarex** [comment]
Automatic

**Comment by githupper** [comment]
Great news! I can't wait for the new version to be out fast enough as I got tons of articles to remove

**Comment by WestXu** [comment]
A [ttrss-alike filter system](https://tt-rss.org/wiki/ContentFilters) would be great.

**Comment by ghost** [comment]
> 
> 
> Hello,
> We have a function to auto mark as read articles matching various keywords.
> Right now and in the upcoming version 1.18.0 it is at feed-level, but in version 1.19.0 it will be possible to do that at category or global level as well.
> Example:
> 
> ![image](https://user-images.githubusercontent.com/1008324/110202964-f1e74c80-7e6b-11eb-8e55-7208deab88dc.png)
> 
> Note: it will only be applied to _new_ articles.

Never responded, I'm sorry, thank you ! I hope it will be included in 1.19. I'm sick of seeing "hot deals" and "promotions" everywhere.

**Comment by githupper** [comment]
It has been 5 months since the issue was first raised. Any chance this function can be added in a 1.18.x version instead of 1.19.0?

**Comment by KatyPurry** [comment]
Is it still planed to 1.19 ? Im' tired of seeing sponsored / good deals / VPN deal links in my feed.

**Comment by Alkarex** [comment]
@Zazou49 In 1.18.0 you can already do that at feed level

**Comment by KatyPurry** [comment]
Thank you, didn't see. I have a lot of feed, I hop it will be global level!

**Comment by math-GH** [comment]
Current situation of a filter on category level: It is not implemented in 1.19. Version 1.20 knocks on the door and is not implemented yet.

**Comment by ericmwalk** [comment]
Just curious the status of this as filtering at the Feed level is great but for somethings at the category or global would be great! Thanks.

**Comment by math-GH** [comment]
No updates here

**Comment by killermouse0** [comment]
Would love to see this feature implemented. Is there a tentative implementation already? I'm not sure I can help, but would like to try.

**Comment by pax0707** [comment]
I would love this on a global level.
Doing this for usual suspects on per feed level is ... time-consuming.

**Comment by Alkarex** [comment]
I have just added filter actions (auto mark as read) at category level in https://github.com/FreshRSS/FreshRSS/pull/5942
Tests welcome

**Comment by Alkarex** [comment]
Filter actions (auto mark as read) at global level is also available in https://github.com/FreshRSS/FreshRSS/pull/5942
Tests welcome

**Comment by pax0707** [comment]
@Alkarex Think that merge to edge didn't go through.

**Comment by Alkarex** [comment]
@pax0707 It is not merged yet - waiting a bit for more tests / feedback. Let me know if you need tips on how to check a PR (remember to tell which type of installation you have, e.g. Docker, git, ZIP...).

**Comment by pax0707** [comment]
Sure @Alkarex.
Docker.
Currently using freshrss/freshrss:edge image.

**Comment by Alkarex** [comment]
To try a PR, if you can, try to instruct your Docker or docker-compose to build from git:

```yml
  freshrss:
    image: freshrss/freshrss:pr5942
    build:
      context: https://github.com/Alkarex/FreshRSS.git#filter-actions-categories
      dockerfile: Docker/Dockerfile-Alpine
    ...
```

* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/freshrss/docker-compose.yml
* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md#build-custom-docker-image

**Comment by pax0707** [comment]
@Alkarex 

Intitle filters working in both category and global. 

Broken: in normal view clicking on a feed link (/i/?get=f_xxx) does not open that feed in the left categories menu.

**Comment by Alkarex** [comment]
@pax0707 Thanks for the tests. Fixed. Please try again. You need to `docker-compose build --pull` and `docker-compose up ...`

**Comment by pax0707** [comment]
Filters working, feeds fixed.

**Comment by Alkarex** [comment]
Excellent :-) Thanks for the feedback. Merged in `edge`
