### ISSUE TITLE
[BUG] feed at slate isn't working

### ISSUE THREAD

**Issue by sdenaro** [FreshRSS/FreshRSS#3499]
**Describe the bug**

RSS feed at Slate is not working. I've used this feed with tt-rss and with vienna rss locally and it works with both

https://slate.com/feeds/news-and-politics.rss

**To Reproduce**
Add feed https://slate.com/feeds/news-and-politics.rss
Click on the error to go to log

note error

```
2021-03-06 16:04:31
A feed could not be found at `https://slate.com/feeds/news-and-politics.rss`; the status code is `200` and content-type is `text/rss+xml; charset=utf-8` [https://slate.com/feeds/news-and-politics.rss]
```

**Expected behavior**
I've expect the feed to work. I've been using Slate feeds since google reader days.

**Screenshots**

**Environment information (please complete the following information):**
 - Database version: [e.g. Mysql 5.7]
pgsql 10
 - PHP version: [e.g. PHP 7.4]
nginx, php 7.4

**Additional context**

**Comment by Alkarex** [comment]
Hello,
This feed is not valid (enough) https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fslate.com%2Ffeeds%2Fnews-and-politics.rss
The content-type `text/rss+xml` does not exist; it should be `application/rss+xml`.
But you can try with `https://slate.com/feeds/news-and-politics.rss#force_feed` , which makes it work, and please consider writing to the webmaster to fix the feed.
