### ISSUE TITLE
[BUG] Fever API cannot login from Android client

### ISSUE THREAD

**Issue by alfureu** [FreshRSS/FreshRSS#3510]
**Describe the bug**
I upgraded to the dockerized version of FreshRSS 1.17.1-dev. My Android client (Readably) lost access to the server, although the address, login, and password are correct. I tried both the normal password, as well as the md5 hash option. None works. Is the Fever API broken?

When I check the path: `https://example.com/api/fever.php`, I receive the usual output:

```
{"api_version":3,"auth":0}
```

**Expected behavior**
It should log me in, as earlier it worked. I cannot find in the 1.17.1-dev version anymore the separate API password and web-based password either.

**Environment information (please complete the following information):**
 - Device: Android
 - OS: docker (official FreshRSS)
 - Browser: N/A
 - FreshRSS version: 1.17.1-dev
 - Database version: MariaDB
 - PHP version: PHP 7.4
 - Installation type: docker

**Comment by Alkarex** [comment]
Please check that your automatic API test is working:

`https://example.com/api/`

Check in authentication:
![image](https://user-images.githubusercontent.com/1008324/110502709-be225600-80fb-11eb-874e-1817014c667d.png)

Check in your profile:
![image](https://user-images.githubusercontent.com/1008324/110502601-a21eb480-80fb-11eb-8b83-bce78bfb0040.png)

**Comment by alfureu** [comment]
Ah, apologies, I did not check under the Profile for the API password. I knew it was somewhere but I was looking for it under users and Authentication sections. My bad. Sorry again.
