### ISSUE TITLE
[BUG] Scrolling the list of unread items will mark them as read

### ISSUE THREAD

**Issue by rhazegh** [FreshRSS/FreshRSS#3513]
**Describe the bug**
Scrolling the list of unread items will mark them as read

**To Reproduce**
1. Open the "Main Stream" to see list of unread items.
2. Scroll up (monitor the unread items that are past the top of the screen).
3. Scroll back down and you will see that the unread items that are past the top of the screen are now marked as read.

**Expected behavior**
Items should not be marked as read when you scroll up and down.

**Screenshots**
Mind the unread items:

<img width="1637" alt="Screen Shot 2021-03-09 at 16 19 32 " src="https://user-images.githubusercontent.com/2200559/110541214-6ed92700-80f5-11eb-988e-abf3562a695b.png">

Scroll up:

<img width="1638" alt="Screen Shot 2021-03-09 at 16 19 47 " src="https://user-images.githubusercontent.com/2200559/110541230-76003500-80f5-11eb-8fd7-84bacb40b6e4.png">

Scroll back down: (they are now marked as read)

<img width="1644" alt="Screen Shot 2021-03-09 at 16 21 43 " src="https://user-images.githubusercontent.com/2200559/110541247-7ac4e900-80f5-11eb-803e-97c6ac5593be.png">

**Environment information (please complete the following information):**
 - Device: MacBook Pro
 - OS: Catalina 10.15.7
 - Browser: Firefox 86.0
 - FreshRSS version: 1.17.1-dev
 - Database version:  Mysql 8.0.23
 - PHP version: Not sure (installed the docker image)
 - Installation type: docker image: freshrss/freshrss:alpine@sha256:6fd0851e7ad7750b877eba2f32a5b01d93d5c27f554af1f29dcc4182984e131d

**Comment by aledeg** [comment]
It looks like you have the "Mark an article as read" option set to "while scrolling".
Check the display configuration!

**Comment by rhazegh** [comment]
@aledeg Thank you. You are right. 

I don't remember setting this option. If this is the default setting, it can be very confusing. 

I am not sure if the average user expects the unread items be marked as read when they scroll up.

**Comment by aledeg** [comment]
As you can see [here](https://github.com/FreshRSS/FreshRSS/blob/master/config-user.default.php#L50-L55), it's the default configuration.
For the confusion, I guess it depends of the users. It's nearly impossible to find defaults values that suits everyone's needs.

**Comment by rhazegh** [comment]
Thanks for the clarification. I am going to close this issue then :)

**Comment by nfriedly** [comment]
This just confused the heck out of me too... I think it would make sense for views that show the contents of the articles, but when just scrolling down a list of headlines (the default view), I wouldn't expect it to mark the entire article as read.
