### ISSUE TITLE
cURL error 22: The requested URL returned error: 403

### ISSUE THREAD

**Issue by iLLiac4** [FreshRSS/FreshRSS#3515]
Hi.

I am trying to add this rss feed https://fitgirl-repacks.site/feed/ and it does not work. Same with #force_feed
What can be the cause?

**Comment by Frenzie** [comment]
There's some kind of DDoS protection in place (`https://ddos-guard.net/`) that returns 403 forbidden.

That probably makes this similar to https://github.com/FreshRSS/FreshRSS/issues/1646. Maybe searching for cURL in combination wtih DDoS Guard will yield some results.

**Comment by Alkarex** [comment]
Indeed. This feed cannot be supported. You can try to reach out to the Web masters.
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Ffitgirl-repacks.site%2Ffeed%2F
