### ISSUE TITLE
Update button doesn't update to 1.18.0

### ISSUE THREAD

**Issue by stevegee58** [FreshRSS/FreshRSS#3526]
I am currently running 1.17.1-dev but the update button doesn't update to the recently released 1.18.0.

Click Update, message says "Blast! No update to apply"

**Environment information (please complete the following information):**
 - Device: Cloud server
 - OS: Ubuntu 18.04
 - Browser: Firefox 86.0.1
 - FreshRSS version: 1.17.1-dev
 - Database version: Mysql 5.7
 - PHP version: PHP 7.2.24
 - Installation type: Digital Ocean

**Comment by Frenzie** [comment]
Does the log say anything? Also note that if it's in a Docker container you should update the container itself.

**Comment by stevegee58** [comment]
It's not in a Docker container.
Which log should I look in?  The update button has always worked in the past.

**Comment by prolibre** [comment]
idem for me @stevegee58

**Comment by Frenzie** [comment]
Maybe it has something to do with CDNs? It's normal for it to take a little while, but it worked for me an hour ago.

**Comment by Alkarex** [comment]
Try to delete `./FresRSS/data/last_update.txt`

**Comment by stevegee58** [comment]
> 
> 
> Try to delete `./FresRSS/data/last_update.txt`

That didn't work.  Still the same message.

**Comment by stevegee58** [comment]
I think update doesn't work for me is because I have version "1.17.1-dev" which isn't recognized by update.freshrss.org.  It looks like I somehow got an untagged/unofficial version.

**Comment by prolibre** [comment]
@stevegee58 

I have the same version as you and I can't get the update.

However https://update.freshrss.org/?v=1.17.1-dev 
does not send me back that my version does not exist.

I don't really understand how the update works : update.freshrss.org ? git ?

**Comment by Frenzie** [comment]
That depends on how you installed it.

**Comment by Alkarex** [comment]
Ping @marienfressinaud

**Comment by marienfressinaud** [comment]
I'll have to take a closer look this afternoon. I checked again the update server and it looks good to me. Can you tell me the content of your `./FresRSS/data/last_update.txt` file? (I assume it should be empty) Also can you confirm the form to add a feed does NOT look like? https://github.com/FreshRSS/FreshRSS/pull/3516 (at `your-server.com/i/?c=subscription&a=add`)

**Comment by stevegee58** [comment]
last_update.txt is always empty.  Every time I try to update the file's timestamp changes to the current time/date.
My "Add a feed or category" page always shows the Advanced section and never hides it.

I agree with @prolibre that the update query for 1.17.1-dev doesn't return 1.18.0 but the query for 1.17.0 *does* return 1.18.0.

I originally installed FreshRSS by doing git clone in /usr/share and it's been working fine ever since.

**Comment by Alkarex** [comment]
@stevegee58 If you installed by git, and normally update via the Web interface, try the following from FreshRSS directory:

```sh
sudo -u www-data git fetch
sudo -u www-data git checkout -b edge origin/edge
sudo -u www-data git branch -D master
```

**Comment by stevegee58** [comment]
OK, that seemed to work.  My FreshRSS install still works and it reports version 1.18.1-dev.

On thing I noticed is git status reports the following file is deleted:
deleted:    data/do-install.txt

Not sure if that's important.

**Comment by prolibre** [comment]
ok for me : 1.17.1-dev > 1.18.1-dev
thanks / merci @Alkarex

**Comment by marienfressinaud** [comment]
Ok, so it's due to the update process on the FRSS part, not on the update server! :) @Alkarex I don't know how the git update works, but can we release a version to change the branch if on `master`, and reintroduce a `master` tag on this release?

Just to answer few questions:

> I agree with prolibre that the update query for 1.17.1-dev doesn't return 1.18.0 but the query for 1.17.0 does return 1.18.0.

Yes, that's expected: `*-dev` versions always update to `dev` version (which correspond to the git `edge` branch)

> On thing I noticed is git status reports the following file is deleted:
> deleted: data/do-install.txt

That's also expected: the file presence triggers the (re)installation of FRSS. I should have changed the behavior for the 1.18 so we don't need this file anymore, but I was working on some other stuff; I'll do it for 1.19.

**Comment by Alkarex** [comment]
> Ok, so it's due to the update process on the FRSS part, not on the update server! :) @Alkarex I don't know how the git update works, but can we release a version to change the branch if on `master`, and reintroduce a `master` tag on this release?

@marienfressinaud Yes, that is possible

**Comment by Alkarex** [comment]
I have re-created a `master` branch (same content than `edge`) to ease the update.

**Comment by uraza** [comment]
Hi.
How does the Web-based update mechanism work?
I had to install the latest version through a zip archive because the "Check for updates" button was not showing up: I have the proper group write permissions on the files, but the last update check was marked as November 24 for some reason (probably when I first installed FreshRSS).
After installing 1.18.0, the update paghe was still suggestion to update to 1.17.1-dev.
I tried to delete the data/last-update.txt file and now it shows that it is going to update to version "unknown".

**Comment by dylanbob** [comment]
Hi. I had the same problem until today (update web page saying 1.17 was the latest release). I installed freshrss using git (follozirg the documentation guide) very recently on the master branch detaching HEAD at the 1.17 tag. I was able to update to 1.18.1-dev by checking out on master at the latest commit.
However, I would like to only update at each release and not get the intermediary dev builds. How can I do so ?

**Comment by Alkarex** [comment]
@dylanbob In git and in Docker Hub, we now have a `latest` tag, which always tracks the latest release. The Web-based update mechanism needs to be be reworked (if anyone is motivated, help welcome https://github.com/FreshRSS/FreshRSS/pull/1760 )

**Comment by math-GH** [comment]
Is this issue still relevant?
