### ISSUE TITLE
Disable the dark theme brightness and contrast image filter

### ISSUE THREAD

**Issue by pigmonkey** [FreshRSS/FreshRSS#3529]
I use the dark theme. I upgraded to 1.18.0 this weekend and dislike the brightness and contrast image filter introduced by #3356. How can I disable it?

I tried installing the Custom CSS extension and adding the following additional CSS rule, but it does not seem to have any effect:

    body img, body video { filter: brightness(1) contrast(1); }

Is there some other way I can disable this, short of overwriting the `dark.css` file?

**Comment by aledeg** [comment]
Have you tried to use `unset`? See [on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/filter)
Something like:
```
body img, body video { filter: unset; }
```

I haven't tried it.

**Comment by scharmach** [comment]
The filter wasn't appealing for me too and I also wanted to disable it. Was surprised to see that there isn't an option for this and that it's being forced upon dark theme-users.

@aledeg, added your code via the Custom CSS-extension to my instance and it works. Thanks for the snippet!

But yeah, what about making this optionable in the settings? Under "Display", where the theme is set, would make sense to me.

**Comment by aledeg** [comment]
@scharmach @pigmonkey I've started working on a different system for themes that will allow to have some configuration. It's going slowly but you can follow that work #3383

**Comment by pigmonkey** [comment]
I figured out that there was a problem with the CustomCSS extension on my instance. I've fixed that, and now I'm able to successfully override the CSS and revert images to normal brightness.

Adding support for theme configuration will be great, but I'll close this issue for now since CustomCSS provides a workaround.
