### ISSUE TITLE
Old articles are always displayed as unread

### ISSUE THREAD

**Issue by killerkarnickel404** [FreshRSS/FreshRSS#3532]
Hello, 

I have a problem with this feed.

https://www.test.de/rss/tests/

Again and again articles that are several weeks old are displayed as unread. 

Mostly this happens after 1 day. 
What can be the reason for this?

I already have:
"Mark updated articles as unread" to "No". 

I also adjusted the archiving.

![grafik](https://user-images.githubusercontent.com/72160647/111351036-08b74b80-8683-11eb-9238-19d177a3e2cb.png)

But when I click on "Delete all articles" and then on Update I have again articles that are several weeks old. 
Shouldn't this be prevented with the archiving adjustment?

I would be very happy if someone could give me a tip on how to solve the problem.

**Comment by Alkarex** [comment]
Try to increase the minimum number of articles to keep, and increase the maximum age.
When articles are deleted from database (instead of being kept as read), it is more difficult to know whether  an article is new or not.

**Comment by killerkarnickel404** [comment]
Hello,

thank you for the quick reply. 

I have adjusted archiving to 
Maximum 1000 items 
Minimum 500 items 
and 4 years

After that I reloaded the feed. 

Unfortunately it still happens. Currently there are 333 articles in the archive.

When I compare the new articles with the old ones, there are no duplicate entries in the archive.

I have now for comparison the feed also times in Thunderbird Aboniert here no old articles are displayed again.

**Comment by Alkarex** [comment]
I will have a look

**Comment by Alkarex** [comment]
I see. This feed seems to randomly(?) show some articles, not seen before, with an old publication date.
While waiting for something more dedicated, you can try to add the following filter in the settings of that feed:

```
!pubdate:P3d
```

It will automatically mark as read new articles, with a publication date older than 3 days.

![image](https://user-images.githubusercontent.com/1008324/111752315-d6ca0300-8895-11eb-933e-adaa4356907b.png)

**Comment by Frenzie** [comment]
>  This feed seems to randomly(?) show some articles, not seen before, with an old publication date.

Probably a minor correction like a typo, or a small update with some new info.

**Comment by ArthurSmoke** [comment]
I have the some issue here，and add `!pubdate:P3d` seems not help
sample feed is `https://blog.csdn.net/weixin_41033105/rss/list`

**Comment by kurzpc** [comment]
> 
> 
> I see. This feed seems to randomly(?) show some articles, not seen before, with an old publication date.
> While waiting for something more dedicated, you can try to add the following filter in the settings of that feed:
> 
> ```
> !pubdate:P3d
> ```
> 
> It will automatically mark as read new articles, with a publication date older than 3 days.
> 
> ![image](https://user-images.githubusercontent.com/1008324/111752315-d6ca0300-8895-11eb-933e-adaa4356907b.png)

Thank you that helped me.

**Comment by killerkarnickel404** [comment]
> 
> 
> I see. This feed seems to randomly(?) show some articles, not seen before, with an old publication date.
> While waiting for something more dedicated, you can try to add the following filter in the settings of that feed:
> 
> ```
> !pubdate:P3d
> ```
> 
> It will automatically mark as read new articles, with a publication date older than 3 days.
> 
> ![image](https://user-images.githubusercontent.com/1008324/111752315-d6ca0300-8895-11eb-933e-adaa4356907b.png)

Thank you that helped me.

**Comment by ArthurSmoke** [comment]
> > I see. This feed seems to randomly(?) show some articles, not seen before, with an old publication date.
> > While waiting for something more dedicated, you can try to add the following filter in the settings of that feed:
> > ```
> > !pubdate:P3d
> > ```
> > 
> > 
> > It will automatically mark as read new articles, with a publication date older than 3 days.
> > ![image](https://user-images.githubusercontent.com/1008324/111752315-d6ca0300-8895-11eb-933e-adaa4356907b.png)
> 
> Thank you that helped me.

thank you for your reply.
actually i solve this by uncheck the option in `Configuration - > Reading -> Mark updated articles as unread`
