### ISSUE TITLE
Feed Update troubleshooting

### ISSUE THREAD

**Issue by Zeik0s** [FreshRSS/FreshRSS#3534]
Does someone have ideas, what i can look for to troubleshoot my 1.18 docker container on a raspi 4? The strange situation is, some feeds are updated with the cronjob inside the container, some are not, but i see no error message or something similar in any log. Not in data/_/*.txt, not in data/user/*.txt And the refresh button on top does nothing, it only collects articles when i click refresh on an individual feed in the sidebar. 
I checked the feeds, that are not refreshing, they are valid and reachable rss feeds. 
I' using sqlite in the container, the data is in a volume and Nginx is in front as reverseproxy for the requests.

**Comment by aledeg** [comment]
When the cronjob is running, not all feeds are refresh at once. That's the reason why only a few feeds are refreshing in your setup. Nothing is wrong, it's done this way to avoid overloading rss-feed providers with countless queries.
Wait a few refresh to see if the problem still occurs. If it does, you will need to share more information about your setup to help troubleshoot.
But my guess is everything will be as it supposed to be. Keep us posted.

**Comment by Zeik0s** [comment]
I understand, but my cronjob is scheduled for every 30 minutes and i looked into it a few minutes ago, there was now on manual refresh an article showing up from 19:38, where there were several executions.

**Comment by Frenzie** [comment]
Mainly see settings → don't automatically refresh more often than … . A cron job will simply say "nothing to do here" depending on the global and individual feed refresh rate settings.
![Screenshot_2021-03-17_09-19-46](https://user-images.githubusercontent.com/202757/111436159-f16b7300-8701-11eb-8c9a-ef092f2ab313.png)

**Comment by Zeik0s** [comment]
@Frenzie changed it, will observe if this changes things, but on first sight it does, because the actualize button did refresh all feeds. 
Thanks a lot, i thought this option is related to check if archiving should be done and not be related to refreshing feeds.

**Comment by Zeik0s** [comment]
works now as i expected it!
