### ISSUE TITLE
[BUG] Gzip XML Feed 

### ISSUE THREAD

**Issue by dylanarmstrong** [FreshRSS/FreshRSS#3543]
**Describe the bug**
Having issues loading a gzip feed. The response headers on the resource may be wrong.

**URLs**
Feed: https://monsoondiaries.com/feed/
Blog: https://monsoondiaries.com/blog/
Validator: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fmonsoondiaries.com%2Fblog%2F

**To Reproduce**
1. Go to Subscription Management
2. Click on Add Feed
3. Add this feed
4. Get invalid feed

**Expected behavior**
Feed would be decompressed automatically, or an option would be available that would force decompression, and it would work.

**Screenshots**
N/A

**Environment information (please complete the following information):**
 - Browser: Safari 14
 - FreshRSS version: 1.18.1-dev
 - Database version: Sqlite 3.31
 - PHP version: 7.4
 - Installation type: Local without docker

My environment accessing FreshRSS is running MacOS, but FreshRSS is running on Linux.

**Additional context**
This is an odd feed, I'm not quite sure what's wrong with it. I don't know if there's an issue with FreshRSS, but there's room for a feature in adding a force decompression option.

To get file:
```
curl https://monsoondiaries.com/feed/ -o feed.xml.gz
```

If there's a possible workaround with this too, that'd be nice.

**Comment by Alkarex** [comment]
We have recently introduced some custom cURL options per feed (though not that one), so if you find a cURL command that works with that feed, we could support it.
If not, then that would be the job of an extension. Extensions can catch the feed's response and transform it before further processing by FreshRSS

**Comment by dylanarmstrong** [comment]
Thanks @Alkarex I will take a look into curl options this weekend.

**Comment by klausenbusk** [comment]
Did you reach out to the blog?

The server is flat-out lying, sending `content-type: text/html; charset=UTF-8` but the body is binary data. Just adding a query parameter seems to work though, ex `https://monsoondiaries.com/feed/?1`.

**Comment by dylanarmstrong** [comment]
Thanks @klausenbusk, I fixed it locally by adding the query parameter, thanks for that!
I reached out to the blog, and am going to close this issue as it seems to just be a site-specific issue.
And @Alkarex I didn't find any curl options that would handle this.
