### ISSUE TITLE
[Feature] extended keyword filtering

### ISSUE THREAD

**Issue by abelbabel** [FreshRSS/FreshRSS#3549]
Hi,

is it possible to use **wildcards or some kind of regular expressions in keywords** when filtering? The problem is that I want to get all posts of a certain topic. The topic is not only defined by a single keyword, but by a list of keywords and by keywords that can be similar.

For example for getting posts about Jakob Ludwig Felix Mendelssohn Bartholdy, I want to use a filter like this
'(Jakob )(Ludwig )Felix (Mendelssohn |M. )Bartholdy'
instead of
'Jakob Ludwig Felix Mendelsohn Bartholdy' OR 'Jakob Ludwig Felix M. Bartholdy' OR 'Ludwig Felix Mendelsohn Bartholdy' OR 'Ludwig Felix M. Bartholdy' OR ... 'Felix Bartholdy'

Another question/feature request: Is it possible to **combine logical AND and OR**?
For example to get posts about a person in certain citys, I want to use a filter like
(Berlin OR D(ü|ue)sseldorf OR Frankfurt OR Leipzig) 'Felix (Mendelsohn )Bartholdy'

Kind regards,
abelbabel

**Comment by Alkarex** [comment]
We do not have regex at the moment, and we do not have parentheses. But combination of AND and OR is possible, although for your example, at the moment one must repeat the *and* close, e.g. `a z OR b z OR c z`

**Comment by Alkarex** [comment]
P.S. We could relatively easily add support for what is supported by SQL's `LIKE` operator:
* https://dev.mysql.com/doc/refman/8.0/en/string-comparison-functions.html#operator_like
* https://www.postgresql.org/docs/current/functions-matching.html#FUNCTIONS-LIKE
* https://sqlite.org/lang_corefunc.html#like

**Comment by nishantbb** [comment]
Chiming in to add motivation for regex. I'm using FreshRSS to follow releases on GitHub, but the title words are usually not separated by spaces. So to filter "unstable" releases, I think I'd need to use **-intitle:.\*unstable.\*** or something of the sort.

**Comment by Alkarex** [comment]
@nishantbb `-intitle:unstable` should work, already now

**Comment by githubjsorg** [comment]
I too find the existing filter mechanism too limited. I have feeds that I subscribe too that I would like to filter based on specific patterns in the title. For example:
![image](https://user-images.githubusercontent.com/12621019/136882126-86e4e650-87e5-46d3-b708-82b69bc83491.png)
I would like to create a filter to automatically mark as read the first item but not the second item. Which would be super simple with a regex.

This is a super simple example and I have several other feeds that would need more complicated regex patterns but which are completely impossible without regex.

**Comment by i300220** [comment]
I use a tampermonkey script I wrote to hide items I do not want.  It uses regex on the titles.  I'll be happy to share if someone is interested.

**Comment by Alkarex** [comment]
Regarding regex, here is a bit of info about the REGEXP operator for the three databases we support, if/when we start implementing it:
* https://www.sqlite.org/lang_expr.html#regexp
    * Requires [an extension](https://sqlite.org/src/file/ext/misc/regexp.c) or a [user-defined function](https://renenyffenegger.ch/notes/development/web/php/snippets/sqlite/regular-expressions/index).
* https://www.postgresql.org/docs/14/functions-matching.html#FUNCTIONS-POSIX-REGEXP
* https://dev.mysql.com/doc/refman/8.0/en/regexp.html

**Comment by githubjsorg** [comment]
Are you saying that we can use these Regex in our filters depending on the database backend?

**Comment by Alkarex** [comment]
> Are you saying that we can use these Regex in our filters depending on the database backend?

@githubjsorg No, unfortunately, we first need to add support inside our search expressions and in the SQL search queries we generate

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/discussions/5445#discussioncomment-8489285

**Comment by Tywele** [comment]
I just want to add my vote for regex support for filter actions

**Comment by Alkarex** [comment]
To add regex to filter actions faster, we could consider adding them only there first (which is in PHP, so easy) while waiting for adding regex to the search function later (harder, as it requires adding support in SQLite, PosgreSQL, MySQL + MariaDB).
PR welcome

**Comment by githubjsorg** [comment]
Adding to "filter actions" would be great. That would fulfill my needs already.

**Comment by Alkarex** [comment]
@githubjsorg Would you be able to help testing this PR implementing what you ask? https://github.com/FreshRSS/FreshRSS/pull/6706

**Comment by githubjsorg** [comment]
> @githubjsorg Would you be able to help testing this PR implementing what you ask? #6706

Last time I tried to update FreshRSS everything broke and I had to do a snapshot rollback. Maybe part of the problem is I have it installed through Yuno?

I am assuming I wouldn't be able to install this update through Yuno? Would I need to install a separate fresh install?

**Comment by Alkarex** [comment]
I do not know what is the best procedure to test using your current setup, but patching files should not be that difficult. Otherwise just run our Docker image, or git clone.

**Comment by mtalexan** [comment]
@Alkarex I'd be happy to help test.  I'm migrating from another platform and I need regex support to be able to replicate some of my filters.  

I already grabbed your `#regex` branch using the `Dockerfile-Alpine` in a docker-compose `build`.  I have ~1500 articles across ~50 RSS sources with the system up and working.
