### ISSUE TITLE
[BUG] filter action ampersand encoding problem

### ISSUE THREAD

**Issue by mdemoss** [FreshRSS/FreshRSS#3562]
Every time filter action with `&` or `&amp;` is saved, another `&amp;` gets added. Also it doesn't seem to mark expected items as read.

**To Reproduce**
1. Go to subscription management pane > filter management
2. Enter one or more tags containing `&`
3. Submit
4. Submit again.
5. observe

**Expected behavior**
Encoding & decoding should be consistent. 

**Screenshots**
![image](https://user-images.githubusercontent.com/702004/112601085-6583d600-8de8-11eb-8f6c-c6b193044dad.png)

**Environment information (please complete the following information):**
 - FreshRSS version: forked from 1.18.0 with local changes, this was also a problem in 1.14.0
 - Database version: Ver 15.1 Distrib 10.3.27-MariaDB
 - PHP version: PHP 7.2.24 (fpm-fcgi)

**Comment by Alkarex** [comment]
For the encoding bug, could you please try https://github.com/FreshRSS/FreshRSS/pull/3563 ?
For the behaviour, filters are only applied to new articles, not on the ones already in database. Please check when new articles arrive.

**Comment by mdemoss** [comment]
I cherry-picked `49f920e` and this fixed the double-encoding on submit issue.

I'm still investigating as a separate issue possible differences between what the search box will match and what the filter lines will match. As a work-around, I had tried `#Movies` in place of `#Movies & TV`. This matched the expected articles when used in the search box but did not seem to mark incoming articles as read.
