### ISSUE TITLE
[BUG] Seeing floppy disk download image button instead of article image

### ISSUE THREAD

**Issue by Hukuma1** [FreshRSS/FreshRSS#3564]
**Describe the bug**
Seeing a floppy disk image placeholder instead of the actual article image in articles.
<img width="767" alt="thumb1" src="https://user-images.githubusercontent.com/54511555/112730768-97805f80-8ef0-11eb-87ba-842e40273098.png">

**To Reproduce**
Variety (no image in article) RSS feed URL: https://variety.com/feed/
Macrumors (proper image in article) RSS feed URL: http://feeds.macrumors.com/MacRumors-Front

**Expected behavior**
Show image that's embedded in article.
<img width="758" alt="thumb2" src="https://user-images.githubusercontent.com/54511555/112730773-9bac7d00-8ef0-11eb-9c4e-0e6f4ffd9177.png">

**Environment information (please complete the following information):**
 - Device: Windows 10
 - OS: Docker Container
 - Browser: Chrome latest
 - FreshRSS version: 1.18.0
 - Database version: [e.g. Mysql 5.7]
 - PHP version: 7.4.15
 - Installation type: Docker

**Additional context**
I have a few feeds that exhibit this behavior, would love to make them compatible to show the image properly! Or if there is some workaround to get them compatible with FreshRSS please let me know. Thanks in advance.

**Comment by Alkarex** [comment]
Could you please test this patch? https://github.com/FreshRSS/FreshRSS/pull/3565

**Comment by Alkarex** [comment]
@Hukuma1 The fix is available in the *edge* variants of our Docker images as well, e.g. `freshrss/freshrss:edge`. Please give it a try

**Comment by Hukuma1** [comment]
Thanks! Seems to be working. I've been using LXIO images, should I switch to official? (For the time being I just overwrote the changed `Feed.php` file)

**Comment by Alkarex** [comment]
I am not familiar with LXIO images, so I cannot tell, but it depends on your needs.
