### ISSUE TITLE
[BUG] wrong permission for './Freshrss/data' (I use docker)

### ISSUE THREAD

**Issue by mengxi-ream** [FreshRSS/FreshRSS#3566]
**Describe the bug**

When restart some of my docker containers, then can't get into freshrss and get the message said wrong permission for './Freshrss/data'

**Expected behavior**
No error message

**Screenshots**

**Environment information (please complete the following information):**
 - Device: [e.g. iPhone6] CentOS 7
 - OS: [e.g. Ubuntu 20.04] CentOS 7
 - Browser: [e.g. Firefox 86]
 - FreshRSS version: [e.g. 1.17.1]
 - Database version: [e.g. Mysql 5.7] postgres
 - PHP version: [e.g. PHP 7.4]
 - Installation type: [e.g. Yunohost] docker

**Additional context**

**Comment by mengxi-ream** [comment]
I solved this bug.

The reason of this bug was that the IP address of Postgres database has changed when I stopped and restarted a list of containers of docker (include freshrss and Postgres for it).

So the solution is to correct the database IP address as the new one.

Use this to find the new address IP
```
docker inspect [Postgres Container ID]
```
![image](https://user-images.githubusercontent.com/38809606/112754662-b1649400-900f-11eb-8a27-1741ff4cebf6.png)

In my case, it's `172.25.0.2`

Then go to freshrss config.php, because I installed it by docker, so it's in 'freshrss/data'

```
cd freshrss/data
vim config.php
```

find some code like this and change the host to the new IP address, save the file
![image](https://user-images.githubusercontent.com/38809606/112754583-45822b80-900f-11eb-861c-bc05f3b77f07.png)

The problem should be solved in this way.

**Comment by Alkarex** [comment]
The good approach when using docker is just to use the image name instead of the IP, like `'postgres'`.
You are welcome to post your docker-compose or docker run for additional tips.

**Comment by mengxi-ream** [comment]
> The good approach when using docker is just to use the image name instead of the IP, like `'postgres'`.
> You are welcome to post your docker-compose or docker run for additional tips.

Cool! I use the image name `freshrss-db`, it works!
