### ISSUE TITLE
[BUG] Can't subscribe the url `https://rsshub.app/pcr/news` which can be used in inoreader

### ISSUE THREAD

**Issue by mengxi-ream** [FreshRSS/FreshRSS#3567]
**Describe the bug**

Can't subscribe the RSS `https://rsshub.app/pcr/news`

I can subscribe it in other software like inoreader, but can't subscribe it in Freshrss. Not only this URL, this problem also appear when I use some other url.

**To Reproduce**
1. log in freshrss
2. add feed 'https://rsshub.app/pcr/news'
3. can't add it
4. get the message 
```
2021-03-28 22:11:13
Unknown error for subscribing [https://rsshub.app/pcr/news]
```

**Expected behavior**
successfully subscribe the RSS

**Screenshots**

**Environment information (please complete the following information):**
 - Device: [e.g. iPhone6] MacOS
 - OS: [e.g. Ubuntu 20.04] CentOS 7
 - Browser: [e.g. Firefox 86] Safari and Chrome
 - FreshRSS version: [e.g. 1.17.1]  1.18.0
 - Database version: [e.g. Mysql 5.7] PostgreSQL 13
 - PHP version: [e.g. PHP 7.4] 7.3.27-1~deb10u1
 - Installation type: [e.g. Yunohost] docker

**Additional context**

**Comment by mengxi-ream** [comment]
Found the reason. It's because the great firewall (GFW) of China.......

I deployed freshrss in the server in China, but the address `rsshub.app` has been blocked by GFW. 
😥

**Comment by mengxi-ream** [comment]
maybe the `unknown error` message should be clear like `connection time out`?
because when I first saw the message `unknown error`, it couldn't help me to debug. And because the network on my Mac is different from the network on my server, so I couldn't figure this out at the first time.

**Comment by Frenzie** [comment]
> maybe the unknown error message should be clear like connection time out?

Could you clarify that? That'd be a known error, not an unknown error.

**Comment by Alkarex** [comment]
@Crayon-ShinChan Could you please provide the output of the following command, from the same server, so I can see which errors you get?

```sh
curl -v 'https://rsshub.app/pcr/news'
```

**Comment by mengxi-ream** [comment]
> @Crayon-ShinChan Could you please provide the output of the following command, from the same server, so I can see which errors you get?
> 
> ```shell
> curl -v 'https://rsshub.app/pcr/news'
> ```

The result for `curl -v 'https://rsshub.app/pcr/news'` is 

```
[root@VM-12-4-centos ~]# curl -v 'https://rsshub.app/pcr/news'
* About to connect() to rsshub.app port 443 (#0)
*   Trying 31.13.86.16...
* Connection timed out
*   Trying 2001::45ab:f01b...
* No route to host
* Failed connect to rsshub.app:443; No route to host
* Closing connection 0
curl: (7) Failed connect to rsshub.app:443; No route to host
```

And today I tried to subscribe the url again. I found that the first time I got the error 
```
2021-03-29 09:54:52
cURL error 28: Connection timed out after 15000 milliseconds [https://rsshub.app/pcr/news]
```
The second time to subscribe and got
```
2021-03-29 09:55:17
Unknown error for feed [https://rsshub.app/pcr/news]
```
Then I tried to subscribe again again and again, the error messages are always unknown error

![image](https://user-images.githubusercontent.com/38809606/112777801-ae9c8a00-9075-11eb-9313-b8bdb51892a9.png)


It seems the later error messages are wrong?

**Comment by mengxi-ream** [comment]
By the way, the url `https://rsshub.app/pcr/news` is from the open source project [RSSHub](https://github.com/DIYgod/RSSHub)

I tried to deploy RSSHub in my server and subscribed the RSS url that was generated by the local RSSHub which is in the same server as FreshRSS I use. Then I successfully done it. Additionally, I know that the great firewall (GFW) blocks rsshub.app so I'm pretty sure it's because of it that I can't subscribe the original url `https://rsshub.app/pcr/news`.

**Comment by Frenzie** [comment]
> It seems the later error messages are wrong?

I don't have time to check, but I suspect the cURL error followed by unknown error might be something like FreshRSS followed by SimplePie respectively.

**Comment by Alkarex** [comment]
Indeed, the error is cached to avoid too many queries, but the actual error status/message is lost

**Comment by meowIAmAUser** [comment]
If it is due to China's blocking, you could try using a Proxy.
Here is a Proxy from me using RSS-Bridge:
https://dhusch.de/rss-bridge/#bridge-Proxy
Downsides: Caches for one hour, removes the whole article, only leaving the description (doesn't affect this Feed, as only description is given...)

Please let me know if this helped

**Comment by mengxi-ream** [comment]
> If it is due to China's blocking, you could try using a Proxy.
> Here is a Proxy from me using RSS-Bridge:
> https://dhusch.de/rss-bridge/#bridge-Proxy
> Downsides: Caches for one hour, removes the whole article, only leaving the description (doesn't affect this Feed, as only description is given...)
> 
> Please let me know if this helped

I deployed Clash for my RSS server ([RSSHub Project](https://github.com/DIYgod/RSSHub)). RSSHub has the build-in features to use Clash or other similar services. This perfectly solved my problem.

If anyone meets China's blocking, using Clash + RSSHub + FreshRSS can be a very good solution.
