### ISSUE TITLE
[BUG] "Share" PopUp Window Blocked or Unslectable

### ISSUE THREAD

**Issue by quella** [FreshRSS/FreshRSS#3572]
**Describe the bug**
Currently running latest Dev build and I noticed recently that when I attempt to use the "Share" button at the bottom of a feed it is blocked by the current window; screenshot below.  I'm using latest build of Chrome and previous releases in the same environment worked when I shared prior to latest build.  I only have a single sharable item via Pocket.

**To Reproduce**
Attempting to share the window to select the shareable location (Pocket in my example) is hidden behind the background window.

**Expected behavior**
Previously this share window would be on top of the other items allowing me to select my Pocket share.

**Screenshots**
![Screen Shot 2021-04-01 at 11 11 37 AM](https://user-images.githubusercontent.com/823352/113319170-2a4d3f80-92df-11eb-8b13-8cd9b5634978.png)

![Screen Shot 2021-04-01 at 11 08 18 AM](https://user-images.githubusercontent.com/823352/113319201-30dbb700-92df-11eb-8500-62d86459a40f.png)

**Environment information (please complete the following information):**
 - Device: Macbook Pro
 - OS: Big Sur
 - Browser: Latest Chrome (v89.0.4389.114)
 - FreshRSS version: 1.18-Dev
 - Database version: [e.g. Mysql 5.7]
 - PHP version: [e.g. PHP 7.4]
 - Installation type: Raspberry Pi

**Additional context**

**Comment by Alkarex** [comment]
Hello,
I cannot reproduce the problem.
* Do you only have the problem with the "Alternative Dark" theme, or all themes?
* Can you try with another browser (e.g. Firefox)?
* Do you have some FreshRSS extensions enabled?
* Is there any error in the Web browser console?

**Comment by quella** [comment]
Just some follow up details.  It seems to work fine in Safari (14.0.3) and Firefox (87.0) but not in Chrome.  I may do a reload/refresh of Chrome data.  Seems to be only a Chrome thing at this time, so I will say the issue is closed.  

**Safari**:
<img width="300" alt="Screen Shot 2021-04-01 at 1 23 37 PM" src="https://user-images.githubusercontent.com/823352/113331364-e0b82100-92ed-11eb-848a-e616c73368fc.png">

**Firefox**:
<img width="276" alt="Screen Shot 2021-04-01 at 1 22 39 PM" src="https://user-images.githubusercontent.com/823352/113331392-eca3e300-92ed-11eb-8ad9-bb28cbc16571.png">

**Comment by Alkarex** [comment]
I cannot reproduce the problem in Chromium 89 on Linux Ubuntu, Chrome 90 or Edge 89 on Windows either.

**Comment by quella** [comment]
Seems like it was an automatic enable of the Ad Block Plus Extension installed in Chrome.  I previously had all blockers disabled for this webUI, but when I changed my home IP Scope this past week, it seems that Ad Block Plus kicked back in, saw the new URL as a different site with blocking enabled, and was causing the odd behavior with the in ability to pop up the Share window.  More a heads up if other experience this as problem well.  Thanks for the testing and feedback.
