### ISSUE TITLE
FreshRSS on Android

### ISSUE THREAD

**Issue by dugs951** [FreshRSS/FreshRSS#3573]
How i can use FreshRSS on Andrid.

I activate API on my FreshRSS, but he show me 
http://192.168.188.56/p/api/
Dont show me my domain and when i put domain and username und pw dont work.
How i can Use FreshRSS on Phone?

**Comment by Frenzie** [comment]
The API has a separate password.

**Comment by dugs951** [comment]
I know but how i can use it on my phone?

**Comment by Frenzie** [comment]
I think it depends on the app. You might have to write `your.domain/api/greader.php`.

**Comment by Frenzie** [comment]
Which app are you trying to use? Also see https://github.com/FreshRSS/FreshRSS#apis--native-apps
