### ISSUE TITLE
Parse HTML in feed

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#3576]
Hi,

I'm a big fan of FreshRSS but there is an issue I have with my most important feeds and I'm not sure how to solve it. For reference, the feeds I am mentioning are the arXiv feeds of which an example can be seen here: [http://export.arxiv.org/rss/hep-th](http://export.arxiv.org/rss/hep-th).

As you can see, the issue is the presence of HTML tags inside the dc:creator and the description tags. Any idea how to remove these? Is there any way to parse the feed when fetched? I am going to try using the customJS extension to take care of these, but I wanted to check if there's any other option than adding more JS to my setup.

From what I can see, one way would be to allow us to "disable" the link to search authors so that the links can actually point to their arXiv target here.

**Comment by Frenzie** [comment]
NB It's not HTML, it's `<dc:creator> &lt;a href=&quot;http://arxiv.org/find/hep-ph/1/au:+Cyncynates_D/0/1/0/all/0/1&quot;&gt;David Cyncynates&lt;/a&gt;, &lt;a href=&quot;http://arxiv.org/find/hep-ph/1/au:+Giurgica_Tiron_T/0/1/0/all/0/1&quot;&gt;Tudor Giurgica-Tiron&lt;/a&gt;</dc:creator>`.

You could run [html_entity_decode()](https://www.php.net/manual/en/function.html-entity-decode.php) on that in an extension, presumably both on insert and on display are possible, but don't forget to shoot them a mail before putting in any effort. ;-)

**Comment by ghost** [comment]
Thank you so much! Definitely will do and at least I have some hint on where to start now!

**Comment by Alkarex** [comment]
`<dc:creator>` is supposed to contain plain text, so I think FreshRSS does what it should there.

See `<atom:author>` instead for richer information.

See also https://www.crossref.org/wp/labs/whitepapers/rss-best-practice/

You could make a very simple FreshRSS extension for arXiv, to fix their feeds by reprocessing the author information.

Closing for now, but feel free to post more information
