### ISSUE TITLE
[Feature] actualize_script.php - warn about unavailable feeds

### ISSUE THREAD

**Issue by squromiv** [FreshRSS/FreshRSS#3580]
It is not possible now to determine which feeds are unavailable/defective during update with "actualize_script.php". It is very important for me not to miss something necessary. And there is no such an info in "actualize.log" and "errors.log" files.

**Comment by aledeg** [comment]
If I understand correctly what you are asking, I see 2 ways to do what you want:
1. check idle feeds in the statistics page.
2. show the feeds with errors in the subscription management page (it is hidden at the bottom of the page)

If this does not suit your need, please add more information to help us understand. Thank you!

**Comment by Alkarex** [comment]
To supplement what @aledeg just wrote, there are also some logs that can be analysed.
See `./FreshRSS/data/users/*/log*.txt` and your syslog.

**Comment by squromiv** [comment]
> * check idle feeds in the statistics page.
> * show the feeds with errors in the subscription management page (it is hidden at the bottom of the page)

It is not the best way to keep feeds alive, when an update occurs in background. I need to know about failed feeds without interacting with FreshRSS GUI.

> FreshRSS/data/users/*/log*.txt

Yep. It seems to be a solution. So I have to monitor size of "log.txt"-file by CRON. And if there is any mismatching from 0 bytes, it means, that there are some troubles with certain feeds. Am I right? Or it can be also false alarm?

**Comment by Alkarex** [comment]
Try for instance:

```sh
grep -i error users/*/log*.txt
```

We could also add a command-line script to return the feeds status for any given user.

**Comment by squromiv** [comment]
> grep -i error users/*/log*.txt

Not the solution, because there is also a warning (not error) like that:
![screen_2021 04 13](https://user-images.githubusercontent.com/15985877/114509422-2524b480-9c3e-11eb-8d7e-78bc28ae1247.png)

To my mind, one of these ways will be better, using "actualize_script.php":
1) **not to create empty log.txt-files during update**, if there is no warning/error
2) to create separate files like "error.log" for every user, if there is any warning/error

**Comment by Alkarex** [comment]
The grep example above was only illustrative. You can adapt to the cases you are interested in catching, e.g.

```sh
grep -iE '(error|warning).*feed' users/*/log*.txt
```

**Comment by squromiv** [comment]
>The grep example above was only illustrative. You can adapt to the cases you are interested in

Oh, it is my shame. I use FreshRSS on "Open server" in Windows and my tech skills in Linux are very low. 

And I still do not understand for what reason empty "log.txt" files are created. There is no data inside.
Nonetheless, it will be better for me not to parse such a file, but to find more optimized and logic method.

**Comment by squromiv** [comment]
@aledeg Finally, I use "zero-bytes" method. If size of log.txt file is greater than zero, then I check what happened wrong. It works for my purposes. Let`s close the issue.
