### ISSUE TITLE
Can't login ambiguously!

### ISSUE THREAD

**Issue by 0zd3m1r** [FreshRSS/FreshRSS#3581]
![image](https://user-images.githubusercontent.com/18439783/114662852-0c7dd280-9d02-11eb-93d4-4d043eb4d249.png)

When I try to login I am getting this error indefinitely. I got all the checks but could not find the solution. Could I be getting this error due to memory leak? 

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04

`● apache2.service - The Apache HTTP Server
     Loaded: loaded (/lib/systemd/system/apache2.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2021-04-13 08:46:53 +03; 24h ago
       Docs: https://httpd.apache.org/docs/2.4/
    Process: 917 ExecStart=/usr/sbin/apachectl start (code=exited, status=0/SUCCESS)
    Process: 37897 ExecReload=/usr/sbin/apachectl graceful (code=exited, status=0/SUCCESS)
   Main PID: 951 (apache2)
      Tasks: 11 (limit: 1073)
     Memory: 54.8M
     CGroup: /system.slice/apache2.service
             ├─  951 /usr/sbin/apache2 -k start
             ├─37912 /usr/sbin/apache2 -k start
             ├─37913 /usr/sbin/apache2 -k start
             ├─37915 /usr/sbin/apache2 -k start
             ├─37916 /usr/sbin/apache2 -k start
             ├─40755 /usr/sbin/apache2 -k start
             ├─57301 /usr/sbin/apache2 -k start
             ├─57302 /usr/sbin/apache2 -k start
             ├─57303 /usr/sbin/apache2 -k start
             ├─57304 /usr/sbin/apache2 -k start
             └─58118 /usr/sbin/apache2 -k start

Apr 13 08:46:52 XXX systemd[1]: Starting The Apache HTTP Server...
Apr 13 08:46:53 XXX  systemd[1]: Started The Apache HTTP Server.
Apr 14 00:00:11 XXX  systemd[1]: Reloading The Apache HTTP Server.
Apr 14 00:00:11 XXX  systemd[1]: Reloaded The Apache HTTP Server.`

**Comment by Alkarex** [comment]
Hello,
How did you deploy and install FreshRSS? Has it worked before?
Did you try to re-apply the rights?

```sh
cd ./FreshRSS/
sudo chown -R :www-data . && sudo chmod -R g+r . && sudo chmod -R g+w ./data/
```

**Comment by 0zd3m1r** [comment]
Hi Alkarex,
I had installed by git. It was working normally. Sometimes I was getting an error like this again. When I restart the server, it works again for a while, then I get this error. 
Yes, i tried to re-apply the rights now again. Still the same problem.

> total 352
drwxrwxr-x 13  0 33   4096 Mar 17 10:46 .
drwxr-xr-x  3  0  0   4096 Apr 11 12:34 ..
drwxrwxr-x 13  0 33   4096 Mar 17 10:46 app
-rw-r--r--  1 33 33 113811 Mar 17 10:46 CHANGELOG.md
drwxrwxr-x  3  0 33   4096 Mar 17 10:46 cli
-rw-r--r--  1 33 33   6403 Mar 17 10:46 config.default.php
-rw-r--r--  1 33 33   2664 Mar 17 10:46 config-user.default.php
-rw-r--r--  1 33 33   2411 Mar 17 10:46 constants.php
-rw-r--r--  1 33 33   3198 Mar 17 10:46 CONTRIBUTING.md
-rw-r--r--  1 33 33  19588 Mar 17 10:46 CREDITS.md
drwxrwxr-x  9 33 33   4096 Mar 26 09:51 data
drwxrwxr-x  3  0 33   4096 Mar 17 10:46 Docker
-rw-r--r--  1 33 33     69 Mar 17 10:46 .dockerignore
drwxrwxr-x  8  0 33   4096 Mar 17 10:46 docs
-rw-r--r--  1 33 33    525 Mar 17 10:46 .editorconfig
drwxrwxr-x  2  0 33   4096 Mar 17 10:46 extensions
-rw-r--r--  1 33 33    262 Mar 17 10:46 force-https.default.txt
drwxrwxr-x  8  0 33   4096 Mar 26 09:51 .git
-rw-r--r--  1 33 33     58 Mar 17 10:46 .gitattributes
drwxrwxr-x  3  0 33   4096 Mar 17 10:46 .github
-rw-r--r--  1 33 33    166 Mar 17 10:46 .gitignore
-rw-r--r--  1 33 33     93 Mar 17 10:46 .hadolint.yaml
-rw-r--r--  1 33 33    308 Mar 17 10:46 index.html
-rw-r--r--  1 33 33     64 Mar 17 10:46 index.php
-rw-r--r--  1 33 33     85 Mar 17 10:46 .jshintignore
-rw-r--r--  1 33 33     95 Mar 17 10:46 .jshintrc
drwxrwxr-x  6  0 33   4096 Mar 17 10:46 lib
-rw-r--r--  1 33 33  34523 Mar 17 10:46 LICENSE.txt
-rw-r--r--  1 33 33   5203 Mar 17 10:46 Makefile
-rw-r--r--  1 33 33    263 Mar 17 10:46 .markdownlint.json
-rw-r--r--  1 33 33    548 Mar 17 10:46 opml.default.xml
drwxrwxr-x  6  0 33   4096 Mar 17 10:46 p
-rw-r--r--  1 33 33   5148 Mar 17 10:46 phpcs.xml
-rw-r--r--  1 33 33  20264 Mar 17 10:46 README.fr.md
-rw-r--r--  1 33 33  14561 Mar 17 10:46 README.md
-rw-r--r--  1 33 33    136 Mar 17 10:46 .stylelintignore
-rw-r--r--  1 33 33   1970 Mar 17 10:46 .stylelintrc
drwxrwxr-x  5  0 33   4096 Mar 17 10:46 tests
-rw-r--r--  1 33 33   1966 Mar 17 10:46 .travis.yml

**Comment by Alkarex** [comment]
You have strange permissions with those unknown user / group `33`.
Try to give full write access to everybody, at least during the time for debugging:

```sh
cd ./FreshRSS/
sudo chmod -R ugo+rw ./data/
```

**Comment by 0zd3m1r** [comment]
grep 33 /etc/group 
> www-data:x:33:

sudo chmod -R ugo+rw ./data/
> drwxrwxrwx  9 33 33   4096 Mar 26 09:51 data

**Comment by 0zd3m1r** [comment]
I login again without getting an error now. But I haven't found cause of problem yet. 

Edit: I still get an error.

**Comment by 0zd3m1r** [comment]
My problem did not solved!

Log: 2021-04-20 22:13:21 Access to database is denied for `tiny_user`: SQLSTATE[HY000] [2002] No such file or directory

**Comment by 0zd3m1r** [comment]
I guess I solved problem.The problem’s source config.php file in data folder. I will test it a few days.
