### ISSUE TITLE
[BUG] Need Some Fix Anti-crawl Strategy

### ISSUE THREAD

**Issue by maquedexiju** [FreshRSS/FreshRSS#3582]
**Describe the bug**
I can't subscribe the https://www.v2ex.com/index.xml 

**To Reproduce**
I tried in two places using two different computers with `curl -v 'https://www.v2ex.com/index.xml '` and got:

```
*   Trying 162.125.32.12:443...
* TCP_NODELAY set
# No Response Any More
```

And I tried `curl -A "Chrome" ...` but no luck, too.

The link can be opened in browser and be subscribed using reeder5, so I think the problem may be caused by curl

**Expected behavior**
Succeed to subcribe

**Environment information (please complete the following information):**
 - OS: Ubuntu 18.04
 - FreshRSS version: last
 - PHP version: PHP 7.2
 - Installation type: Manual

**Comment by Alkarex** [comment]
Hello,
This feed works fine for me, from FreshRSS and from cURL. I believe your IP might be filtered / banned. Try from another IP range or with a proxy.

![image](https://user-images.githubusercontent.com/1008324/114705772-65606180-9d28-11eb-9256-2a7a1d20efa0.png)

I do not think we can do more from FreshRSS side

**Comment by Alkarex** [comment]
P.S.: Check that the DNS is correct. It works both with IPv6 and IPv4 for me, but that does not give the same IP than you:

```
curl -v 'https://www.v2ex.com/index.xml'
*   Trying 2606:4700:10::6814:9da:443...

curl -v -4 'https://www.v2ex.com/index.xml'
*   Trying 172.67.3.188:443...
```

**Comment by maquedexiju** [comment]
Yes, you're right, I tried adding a proxy and finally succeeded. Thanks for your help.
