### ISSUE TITLE
[BUG] Authentication token not showing

### ISSUE THREAD

**Issue by maquedexiju** [FreshRSS/FreshRSS#3583]
**Describe the bug**
The Authentication token is not showing

**To Reproduce**
1. Just go to "Authentication" page

**Expected behavior**
"Authentication token" showing here

**Screenshots**

![image](https://user-images.githubusercontent.com/6948576/114846763-923b7400-9e0f-11eb-9953-9444f6db6686.png)

**Environment information (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - FreshRSS version: 1.18
 - PHP version: PHP 7.2
 - Installation type: Manual

**Comment by maquedexiju** [comment]
The setting is found in "Profile Settings", so I think the doc needs to be updated now

**Comment by maquedexiju** [comment]
Yes, I saw the description here. Going to close this issue

**Comment by tobip** [comment]
Sorry to bump this ticket, but this page still needs to get updated:
https://freshrss.github.io/FreshRSS/en/users/09_refreshing_feeds.html#for-form-authentication

**Comment by Frenzie** [comment]
What needs to be updated how precisely?

**Comment by tobip** [comment]
Ah, what I wanted to say:

The documentation at this link is showing an old screenshot of the "Authentication" tab, suggesting that I can set up my Authentication token there, which is not true any more, because this part of configuration got moved to the "Profile" tab.
