### ISSUE TITLE
[BUG] Can't Fresh the Feed

### ISSUE THREAD

**Issue by maquedexiju** [FreshRSS/FreshRSS#3584]
**Describe the bug**

The feed can't be freshed using the "fresh" button, or command line

**To Reproduce**
1 Restart my server
2 The "Do not automatically refresh more often than" is set to 20 min
3 Installation Check all green
3 wait more than 20 min
4 click the "Update" button but failed
5 tried `/php ../FreshRSS/app/actualize_script.php` and get "OK", the task spend 0 seconds to finish, but no feed freshed
6 open the Chrome and visit "https://..." and get "OK", but no feed freshed
7 Update the individual feed and got the feed freshed
8 Check the log and I got the error repeatedly

`Invalid action name for controller FreshRSS_configure_Controller`
`Invalid action name for controller FreshRSS_index_Controller`

**Expected behavior**
Feed Freshed

**Environment information (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chrome
 - FreshRSS version: 1.8.1
 - PHP version: PHP 7.2
 - Installation type: Manual

**Comment by maquedexiju** [comment]
Restart again, and fixed, but

**Comment by maquedexiju** [comment]
Restart again, the Updating seems to be working now, but the errors still appear in the log repeatedly

```
Invalid action name for controller FreshRSS_configure_Controller
Invalid action name for controller FreshRSS_index_Controller
```

**Comment by Alkarex** [comment]
Hello,
You write your FreshRSS version is 1.8.1. Do you maybe mean 1.18.1-dev?

**Comment by Alkarex** [comment]
To get more debugging information, could you please replace line 4 of

https://github.com/FreshRSS/FreshRSS/blob/edge/lib/Minz/ActionException.php#L4

with

```php
$message = "Invalid action name $action_name for controller $controller_name";
```

**Comment by Alkarex** [comment]
Patch implementing my previous message https://github.com/FreshRSS/FreshRSS/pull/3624

**Comment by maquedexiju** [comment]
The `Invalid action name for controller FreshRSS_configure_Controller` is gone now, I can't reproduce the bug now, but I have changed the code on line 4, hope I can get more information next time.
