### ISSUE TITLE
Fatal Error on Startup

### ISSUE THREAD

**Issue by henrythefifth2** [FreshRSS/FreshRSS#3585]
I'm running the latest version of FreshRSS (at 4/16/2021) off the 'edge' branch on XAMPP 7.4.11 running on a Macbook Pro 10.15.7.

I receive the following error on my browser:

<br/>
<b>Fatal error</b>
:  Uncaught Error: Call to undefined function safe_define() in /Applications/XAMPP/xamppfiles/htdocs/ourpage/FreshRSS/constants.local.php:5
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/ourpage/FreshRSS/constants.php(25): include()
#1 /Applications/XAMPP/xamppfiles/htdocs/ourpage/FreshRSS/p/i/index.php(23): require('/Applications/X...')
#2 {main}
  thrown in 
<b>/Applications/XAMPP/xamppfiles/htdocs/ourpage/FreshRSS/constants.local.php</b>
 on line 
<b>5</b>
<br/>

I opened permissions on the data/Temp directory. The error persists. Any thoughts?

Thanks!

**Comment by Alkarex** [comment]
Hello,
Could you please try to update your `constants.local.php` to use `define('xxx')` instead of `safe_define('xxx')` ?

Related to https://github.com/FreshRSS/FreshRSS/pull/3577

**Comment by henrythefifth2** [comment]
That works!!

Thanks!!
