### ISSUE TITLE
[BUG] "the status code is `302` and content-type is `text/html`" error with a feed which responds with 200 OK elsewhere

### ISSUE THREAD

**Issue by amateurdetout** [FreshRSS/FreshRSS#3592]
Hi,
I've been encounting this issue for months but still can't figure out why.

hope I can get some help.

Thanks.

**Describe the bug**
Any feed from the domain https://brunch.co.kr encounters same errors that read "A feed could not be found at [feed URL]; the status code is `302` and content-type is `text/html`"
but the feed url
- responds with '200 OK' code to ssh command line curl from the sever where my copy of FreshRSS is installed or to web browsers of my PCs
- and works fine with some other feed reader (I've tested with [Feedbro, a Firefox addon](https://addons.mozilla.org/ko/firefox/addon/feedbroreader/))

**To Reproduce**
1. Try to register or update feeds from https://brunch.co.kr e.g. **https://brunch.co.kr/rss/@@2xr**

**Expected behavior**
The feeds shoud be registered or updated.

**Environment information **

 - FreshRSS version: 1.18.0 (I met this issue first time in Nov. 2020 but not sure what version I was using then)
 - Database version: Mysql 5.7
 - PHP version: 7.2.34

**Comment by math-GH** [comment]
@amateurdetout 
I added https://brunch.co.kr/rss/@@2xr into my FreshRSS. Today it works fine.
