### ISSUE TITLE
[BUG] Rss feed being formatted strangely. Single code sections appear in the text; Umlauts are not displayed.

### ISSUE THREAD

**Issue by kjboa** [FreshRSS/FreshRSS#3593]
**Describe the bug**
Hi, i'm new to fresh rss and just started my instance. I added a few feeds but one doesn't seem to be processed properly. The Text seems to be in raw code format and umlauts are replaced with combinations of numbers. Strangely enough, the fluent reader app and feedly can process the feed.

**To Reproduce**
1. Go to https://katapult-magazin.de/de or the English version: https://katapult-magazin.de/en
2. Copy the rss url in their header (https://katapult-magazin.de/feed/rss)
3. Add it as a feed in Freshrss

**Expected behavior**
The text should be shown as in the app screenshot below

**Screenshots**
Web Ui Error: 
![grafik](https://user-images.githubusercontent.com/65646265/115405496-93ddb100-a1ee-11eb-825d-fafe8a5b03c5.png)
Fluent Reader App:
![grafik](https://user-images.githubusercontent.com/65646265/115405538-9f30dc80-a1ee-11eb-9fa6-aab0aaddeda1.png)

**Environment information (please complete the following information):**
 - Browser/Device: Firefox Nightly 90 / Android 10 with fluentreader/feedly app
 - FreshRSS version: 1.18.0
 - Installation type: linuxsever.io docker image on raspberry pi 4

**Additional context**
I also installed the Latex Support Extension from https://github.com/aledeg/xExtension-LatexSupport hoping it would fix my problem which it didn't. Am i missing some setting or is the feed just incompatible? 
Help would be greatly appreciated.

**Comment by aledeg** [comment]
The Latex Support Extension recognize only a few patterns to replace some content with its LaTeX counterpart. For instance, something enclosed in $ signs will be converted.
The use of that extension will not fix the current issue.

**Comment by Frenzie** [comment]
What's displayed is exactly what it asks for. Fluent Reader actually deals with that heap of nonsense JSON?

**Comment by kjboa** [comment]
> What's displayed is exactly what it asks for. Fluent Reader actually deals with that heap of nonsense JSON?

Yeah it does. tried some other clients aswell but fluent reader is the only one that is able to read the text. Feedly sometimes shows it for like a split second then it's gone.

**Comment by Frenzie** [comment]
That sounds like an anti-feature to me if true. But also I can't confirm, here's Fluent Reader:
![Screenshot_20210420_172420](https://user-images.githubusercontent.com/202757/115422587-56cceb00-a1fd-11eb-801d-2660089b25e2.png)
![Screenshot_20210420_172440](https://user-images.githubusercontent.com/202757/115422590-57fe1800-a1fd-11eb-8b3d-2550a1c009f6.png)

**Comment by kjboa** [comment]
https://user-images.githubusercontent.com/65646265/115423905-7dd7ec80-a1fe-11eb-97f8-323dc301fdba.mp4
 Mobile not desktop, maybe there's an option like this on desktop too, i don't know

**Comment by math-GH** [comment]
For me Katapult feed works fine

![grafik](https://user-images.githubusercontent.com/1645099/147359983-d868d71b-fa56-47c0-a740-a1b2c0005764.png)

@kjboa : Could we close this issue?

**Comment by Frenzie** [comment]
The feed no longer contains JSON as content. I'd also propose to close it.

If we want to use it as an example in some way, see http://web.archive.org/web/20210408164638/https://katapult-magazin.de/feed/rss for how it was at the time this issue was opened.

**Comment by kjboa** [comment]
Yeah the problem seems to be fixed
