### ISSUE TITLE
[BUG] Content-Security-Policy header not sent any more

### ISSUE THREAD

**Issue by oupala** [FreshRSS/FreshRSS#3594]
**Describe the bug**
I am testing FreshRSS 1.18.0 (upgrading from 1.16.0) and surprisingly the Content-Security-Policy header is not sent any more.

Do you have an idea of  this behaviour? I am upgrading from raspbian jessie to raspbian buster and I discovered this new limitation.

**To Reproduce**
The issue might be hard to reproduce as it might be dependant from my server configuration.

**Expected behavior**
FreshRSS is self-managing its own Content-Security-Policy header.

**Environment information (please complete the following information):**
 - Device: raspberrypi 1
 - OS: raspbian/debian buster
 - Browser: n/a
 - FreshRSS 1.18.0
 - Database version: n/a
 - PHP version: 7.3 (see below)
 - Installation type: home made, using ansible

```
PHP 7.3.27-1~deb10u1 (cli) (built: Feb 13 2021 16:31:40) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.27, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.27-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies
```

**Comment by Alkarex** [comment]
Hello,
What Web server? Any proxy?

**Comment by oupala** [comment]
Oups, sorry for omitting important informations...

My http server is apache:

> Server version: Apache/2.4.38 (Raspbian)
Server built:   2020-08-25T20:08:29

There is no specific proxy between my raspberry and my laptop (they're both in my local network, behind my router).

The only thing interesting is that I wanted to enable http/2 and I had to enable some apache module to do that:

- mod_proxy_fcgi
- mod_setenvif (altough it is already enabled by default)

I added no specific configuration except enabling http/2 in the configuration of the virtual host:

```
    # enable HTTP/2, if available
    Protocols h2 http/1.1
```

I can try to disable http/2 in order to check if this changes anything.

**Comment by oupala** [comment]
I tried to disable the http2 module, and theproxy_fcgi module.

I also explicitly commented the http/2 enable in the apache configuration:

```
    # enable HTTP/2, if available
    #Protocols h2 http/1.1
```

And I tried to enable and disable the following directive:

```
Header setifempty Content-Security-Policy "upgrade-insecure-requests; default-src 'none'; frame-ancestors 'none'; report-uri /csp_reports/"
```

When the header is commented, it seems that no `Content-Security-Policy` is being sent by FreshRSS.

Can you confirm the bug on another environment?

**Comment by oupala** [comment]
In fact, I was using `curl -I` to test the behavior of the Content-Security-Policy header, and FreshRSS does not send this header when using the `-I` option of `curl`.

Prefer to use the following command: `curl -v <url> > /dev/null` in order to get the real headers.

**Comment by oupala** [comment]
The explanation is that a regular curl request uses the `GET` verb while a [`curl -I` uses a `HEAD`](https://curl.se/docs/manpage.html#-I).

I think FreshRSS has been set to send specific `Content-Security-Policy` for some pages, for some verbs. And in my opinion, `HEAD` verbs should be treated as `GET` verbs: the same headers should be returned in both cases. That's the way the [`HEAD` verb has been designed](https://www.pragmaticapi.com/blog/2013/02/14/restful-patterns-for-the-head-verb/).

**Comment by Alkarex** [comment]
Ah indeed. We cannot generate all GET headers in HEAD at the moment, but most of the useful ones e.g. for existence. It would require generating the full response and then discarding it - we do not have a mechanism for that at the moment, and it also would defeat the lightweight mission of HEAD.

**Comment by Alkarex** [comment]
Feel free to open another issue for HEAD if you find it important

**Comment by oupala** [comment]
For `HEAD` verb, headers are important because headers are what we want to receive and analyse. This is **the purpose** of `HEAD`. So in my opinion, that would not defeat the lightweight mission of `HEAD`. Some headers will always be lighter than content.

I'm ok to open another separate issue, but only of you find it makes sense for you.

**Comment by Alkarex** [comment]
Please open a new issue, so we can collect the needs

**Comment by oupala** [comment]
Done.

**Comment by Alkarex** [comment]
@oupala FreshRSS sends some default CSP headers by PHP. You are then free to do what you want at Web server or proxy level. You can try our official Docker image if you have any trouble with your setup.


```
curl -s http://localhost/FreshRSS/p/i/phpinfo.php | grep -i 'Server API'
<tr><td class="e">Server API </td><td class="v">FPM/FastCGI </td></tr>
<tr><td class="e">Server API (SAPI) Abstraction Layer </td><td class="v">Andi Gutmans, Shane Caraveo, Zeev Suraski </td></tr>
```

```
curl -v 'http://localhost/FreshRSS/p/i/'
*   Trying 127.0.0.1:80...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 80 (#0)
> GET /FreshRSS/p/i/ HTTP/1.1
> Host: localhost
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Sat, 15 May 2021 11:14:51 GMT
< Server: Apache/2.4.46 (Ubuntu)
< Cache-Control: private, must-revalidate, max-age=0
< Content-Security-Policy: default-src 'self'
< X-Content-Type-Options: nosniff
< Set-Cookie: FreshRSS=fmn5ee69t6tt3v385ts3krdfu1; path=/FreshRSS/p/i/; HttpOnly
< Upgrade: h2,h2c
< Connection: Upgrade
< Last-Modified: Sat, 15 May 2021 11:14:51 GMT
< Etag: "7d6ccb94b9c9247e19cd33da76675c58"
< Vary: Accept-Encoding
< Transfer-Encoding: chunked
< Content-Type: text/html; charset=UTF-8
```

**Comment by oupala** [comment]
Thank you for the working example of the docker image. It is very helpful to have a working example in order to compare both configurations. And as I was also using apache and php in mode *FPM/FastCGI*, it was more than helpful to me.

In fact, as I am using php in a proxy mode, and as I am configuring the `Content-Security-Policy` in apache configuration files, I have to set the headers in a specific way in apache. This is explicitly detailed in the [documentation of `mod_header`](https://httpd.apache.org/docs/2.4/en/mod/mod_headers.html#header):

> You're modifying or removing a header generated by a CGI script or by [`mod_proxy_fcgi`](https://httpd.apache.org/docs/2.4/en/mod/mod_proxy_fcgi.html), in which case the CGI scripts' headers are in the table corresponding to `always` and not in the default table.

As a consequence, I had to use the `always` keyword in all of my *Header* directives.

For example, I wanted to add a *Content-Security-Policy report* to the `Content-Security-Policy` header:

```apache
Header always edit Content-Security-Policy "$" "; report-uri /csp-report/"
```

With the `always` header, everything is working well.

The issue was not directly related to FreshRSS, but to apache who I switch to `mod_proxy_fcgi` in order to enable http/2.

Thanks for your help!
