### ISSUE TITLE
Caddy with FreshRSS

### ISSUE THREAD

**Issue by cnkmmk** [FreshRSS/FreshRSS#3596]
I want use caddy reverse_proxy visit FreshRSS.

Caddyfile
```
{
  order webdav last
  auto_https off
}
(global) {
    encode gzip zstd
    file_server
    log {
        format single_field common_log
        output file /var/logs/caddy/caddy.log
    }
}
(rdpath) {
    redir /FreshRSS /FreshRSS/
    handle /FreshRSS/* {
        uri strip_prefix /FreshRSS
        reverse_proxy http://127.0.0.1:8082 {
            header_up X-Script-Name /FreshRSS
            header_up Host {http.request.host}
            header_up X-Real-IP {http.request.remote}
            header_up X-Forwarded-For {http.request.remote}
            header_up X-Forwarded-Port {http.request.port}
            header_up X-Forwarded-Proto {http.request.scheme}
        }
    }
}

:80 {
    import global
    root * /var/www/html
    import rdpath
}
:8082 {
    import global
    php_fastcgi 172.19.0.5:9005
    root * /var/www/FreshRSS/p
    log {
        format single_field common_log
        output file /var/logs/caddy/FreshRSS.log
    }
}
```

I can open http://192.168.1.1/FreshRSS/, then I click "Submit", but the page open the "http://192.168.1.1/FreshRSS/i/index.php?step=0".

the LOGS is:
```
127.0.0.1 - - [22/Apr/2021:23:57:49 +0800] "GET /i/ HTTP/1.1" 200 1023
127.0.0.1 - - [22/Apr/2021:23:57:52 +0800] "POST /i/index.php?step=0 HTTP/1.1" 302 1110
127.0.0.1 - - [22/Apr/2021:23:57:53 +0800] "GET /i/index.php?step=1 HTTP/1.1" 302 948
127.0.0.1 - - [22/Apr/2021:23:57:53 +0800] "GET /i/index.php?step=0 HTTP/1.1" 200 1023
```

I can not install FreshRSS.
please help me.

**Comment by Alkarex** [comment]
Hello,
I am not familiar with Caddy (I can provide an example for Traefik though), but try to remove `uri strip_prefix /FreshRSS` and remove `header_up X-Script-Name /FreshRSS` (if you want such a thing, FreshRSS supports `X-Forwarded-Prefix`). Check the FreshRSS logs in `./FreshRSS/data/users/*/log*.txt`. It looks like a cookie/session misconfiguration. Maybe Caddy requires explicit instructions to forward cookies?

**Comment by cnkmmk** [comment]
Thank you soo much.
I try to access FreshRSS directly through a local port, no problem.
so this issues is reverse_proxy configuration has broken somewhere.  I'll figure out what's wrong with it.

**Comment by asdofindia** [comment]
I could get caddy to work with the following configuration. Maybe can be added to docs:

```
feeds.free.gen.in {
    root * /srv/FreshRSS/p
    php_fastcgi unix//run/php/php7.4-fpm.sock
    file_server
}
```
Uses the https://caddyserver.com/docs/caddyfile/directives/php_fastcgi directive

**Comment by math-GH** [comment]
@Alkarex could you please set the "Documentation" label?

**Comment by OceanApart** [comment]
> Thank you soo much. I try to access FreshRSS directly through a local port, no problem. so this issues is reverse_proxy configuration has broken somewhere. I'll figure out what's wrong with it.

Any progress here? I'm stuck on caddy reverse_proxy too.

**Comment by Alkarex** [comment]
@OceanApart Did you check the solution proposed a bit higher? https://github.com/FreshRSS/FreshRSS/issues/3596#issuecomment-880786248
I do not think there is much we can do at FreshRSS level

**Comment by OceanApart** [comment]
> @OceanApart Did you check the solution proposed a bit higher? [#3596 (comment)](https://github.com/FreshRSS/FreshRSS/issues/3596#issuecomment-880786248) I do not think there is much we can do at FreshRSS level

Agreed. FreshRSS is just fine. And asdofindia's solution doesn't fit docker I think.

This is my Caddyfile.

```
mydomain.com {
        redir /fresh /fresh/
        handle /fresh/* {
                reverse_proxy 127.0.0.1:38080 {
                        header_up X-Forwarded-Prefix /fresh
                }
        }
}
```

The first visit to `mydomain.com/fresh/` after installation, got 404. Very confused about caddy, while others niginx works with proper `X-Forwarded-Prefix`.

```
"GET /fresh/ HTTP/1.1" 404 196 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36"
```

**Comment by OceanApart** [comment]
Sadly, I've tried nginx config as [README.md](https://github.com/FreshRSS/FreshRSS/blob/master/Docker/README.md#hosted-in-a-subdirectory) described. `http://mydomain.com/freshrss/` still got 404 as same as caddy with `freshrss/freshrss:latest` docker image.

**Comment by Alkarex** [comment]
@OceanApart Try first to reach FreshRSS directly (without the reverse proxy), using the local IP. Does that work?

**Comment by OceanApart** [comment]
> @OceanApart Try first to reach FreshRSS directly (without the reverse proxy), using the local IP. Does that work?

thx for help. localhost works fine.

```
# curl localhost:38080
﻿<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-GB" lang="en-GB">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="initial-scale=1.0" />
<meta http-equiv="Refresh" content="0; url=i/" />
<title>FreshRSS</title>
<link rel="stylesheet" href="themes/p.css" />
<link rel="shortcut icon" type="image/x-icon" sizes="16x16 64x64" href="favicon.ico" />
<link rel="icon msapplication-TileImage apple-touch-icon" type="image/png" sizes="256x256" href="themes/icons/favicon-256.png" />
<meta name="msapplication-TileColor" content="#FFF" />
<meta name="robots" content="noindex" />
</head>

<body>
<h1><a href="i/">FreshRSS</a></h1>
<p><a href="i/"><img class="logo" width="25%" src="themes/icons/icon.svg" alt="⊚" /></a></p>
</body>
</html>
```

**Comment by alexjmccoy** [comment]
Struggling with Caddy, too. Localhost works. I'm using the provided `docker-compose.yml` file.

**Comment by Alkarex** [comment]
Please check the FreshRSS Docker logs (something like `docker logs -f freshrss` ) to make sure FreshRSS at least receives the requests. If not, this is a reverse proxy / Caddy issue, which I cannot help with. I might be able to help with Traefik instead.

**Comment by alexjmccoy** [comment]
> Please check the FreshRSS Docker logs (something like `docker logs -f freshrss` ) to make sure FreshRSS at least receives the requests. If not, this is a reverse proxy / Caddy issue, which I cannot help with. I might be able to help with Traefik instead.

Thanks for the comment. FreshRSS does not see the request (I see the requests when I access FreshRSS via localhost or http://machine.local:8083) so it's some issue with Caddy. Been scratching my head all day over it...

**Comment by fawqsir** [comment]
> 



> Hello, I am not familiar with Caddy (I can provide an example for Traefik though), but try to remove `uri strip_prefix /FreshRSS` and remove `header_up X-Script-Name /FreshRSS` (if you want such a thing, FreshRSS supports `X-Forwarded-Prefix`).

I would love to see an example of this.... This is the exact issue I am having only with traefik.

**Comment by Alkarex** [comment]
Examples for Traefik:
* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md#use-tr%C3%A6fik-reverse-proxy
* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/freshrss/docker-compose-proxy.yml
