### ISSUE TITLE
[BUG] HEAD requests should return the same headers as GET requests

### ISSUE THREAD

**Issue by oupala** [FreshRSS/FreshRSS#3603]
**Describe the bug**

As described in #3594, using `HEAD` verbs in requests do not return the same headers as when using `GET` verbs.

**To Reproduce**
1. make a `HEAD` curl request `curl -I <url>` to a resource of FreshRSS (for example : `https://example.org/freshrss/i/`)
1. make a `GET` curl request `curl -v <url> > /dev/null` to the same resource of FreshRSS
1. compare headers of both requests
1. for example, there is no `Content-Security-Policy` header with the first request while there is one with the second request

**Expected behavior**

Same headers should be returned with both requests as `HEAD` verbs should be treated as `GET` verbs: the same headers should be returned in both cases. That's the way the [`HEAD` verb has been designed](https://www.pragmaticapi.com/blog/2013/02/14/restful-patterns-for-the-head-verb/).

**Environment information (please complete the following information):**

 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - FreshRSS version: N/A
 - Database version: N/A
 - PHP version: N/A
 - Installation type: N/A

**Additional context**

N/A

**Comment by math-GH** [comment]
Checked with FreshRSS1.19.2 on demo.freshrss.org via https://reqbin.com/req/c-tmyvmbgu/curl-head-request-example

HEAD request:
![grafik](https://user-images.githubusercontent.com/1645099/187071369-28588841-4065-4c31-a7c7-96c0bd7b2e1e.png)

GET request:
![grafik](https://user-images.githubusercontent.com/1645099/187071382-d6edc560-58c1-4333-be82-4195536a9aa7.png)

Same headers except `Transfer-Encoding: chunked`

**Comment by oupala** [comment]
I agree with you @math-GH. Things must have changed since the opening of this issue.

I have the same behavior on my personal instance of FreshRSS, which is also version 1.19.2, and is also using `content-security-policy` headers.
