### ISSUE TITLE
[BUG] Memory Limit error

### ISSUE THREAD

**Issue by AndreaB321** [FreshRSS/FreshRSS#3605]
**Describe the bug**
Hi there, after having moved my FreshRss to a new raspberry pi (it was installed on a different one), I'm facing a memory limit error even if everything looks good to me:

pi@raspinas:/usr/share/FreshRSS/data/users/andrea sudo -u www-data php -f /usr/share/FreshRSS/app/actualize_script.php
FreshRSS starting feeds actualization at 2021-05-05T11:01:37+01:00
FreshRSS actualize _...
FreshRSS actualize andrea...
PHP Fatal error:  Allowed memory size of 2097152 bytes exhausted (tried to allocate 32768 bytes) in /usr/share/FreshRSS/lib/SimplePie/SimplePie/Misc.php on line 804

pi@raspinas:/usr/share/FreshRSS/data/users/andrea sudo php -i | grep memory_limit
memory_limit => 512MB => 512MB

**To Reproduce**
1. sudo -u www-data php -f /usr/share/FreshRSS/app/actualize_script.php

**Expected behavior**
Feeds to be updated correctly

**Environment information (please complete the following information):**
 - Device: Raspberry Pi 4 4GB
 - OS: Ubuntu
 - FreshRSS version: 1.18.1-dev1
 - Database version: sqlite
 - PHP version: PHP 7.3.27-1~deb10u1

**Comment by Alkarex** [comment]
*Allowed memory size of 2097152 bytes* does not correspond to 512MB. There is maybe something wrong there. Try to use the same user and absolute php path.

**Comment by AndreaB321** [comment]
Sorry, I meant to put the correct output:

pi@raspinas:~ sudo -u www-data php -i | grep memory_limit
memory_limit => 512MB => 512MB

pi@raspinas:~ sudo -u www-data /usr/bin/php -i | grep memory_limit
memory_limit => 512MB => 512MB

pi@raspinas:~ sudo -u www-data /usr/bin/php7.3 -i | grep memory_limit
memory_limit => 512MB => 512MB

pi@raspinas:~ sudo -u www-data /usr/bin/php -f /usr/share/FreshRSS/app/actualize_script.php
FreshRSS starting feeds actualization at 2021-05-05T11:31:26+01:00
FreshRSS actualize _...
FreshRSS actualize andrea...
PHP Fatal error:  Allowed memory size of 2097152 bytes exhausted (tried to allocate 32768 bytes) in /usr/share/FreshRSS/lib/SimplePie/SimplePie/Misc.php on line 1306

I know there is something wrong, but php.ini is quite simple to configure

Anything else I can try?

**Comment by Alkarex** [comment]
Try to locate your actual `php.ini`:

```sh
sudo -u www-data php -i | grep .ini
```

Should be something like `/etc/php/7.3/cli/php.ini`

Then put `-1` in that file for `memory_limit`

Try again, and check the amount of actual memory used with another tool such as `htop`.

**Comment by Alkarex** [comment]
FYI, we also have a Docker image for Raspberry Pi, e.g.: `freshrss/freshrss:arm`

**Comment by AndreaB321** [comment]
So... memory_limit = -1 does work, but it's not the best. Memory consumption doesn't spike up though.

**Comment by Alkarex** [comment]
It looks like a bug in the definition of `memory_limit` either in your configuration or in that PHP version in CLI mode.
