### ISSUE TITLE
[Feature] To make some options available to non-admin accounts

### ISSUE THREAD

**Issue by squromiv** [FreshRSS/FreshRSS#3611]
There are settings, which are hidden for non-admin accounts. For example, "disable SSL verification" in the advanced feed options.
It will be cool to manage such features for all users.

**Comment by Alkarex** [comment]
Would be OK thanks to the patch preventing feed cache pollution https://github.com/FreshRSS/FreshRSS/pull/3502

**Comment by squromiv** [comment]
@Alkarex Thank you. Looks as fixed.
