### ISSUE TITLE
[BUG] Login Button doesn't work after installation

### ISSUE THREAD

**Issue by littabird** [FreshRSS/FreshRSS#3617]
So, I have installed like 5 times, same issue... The login button just wouldn't work after putting the right username/password.

It looks like javascript can't run or something like that?

The thing is I have installed 2-3 times on other domains using the same server before, they just worked.

I read somewhere about 'auth_type' => 'form', which I changed, still can't make it work.

I asked the hosting guy, he said he doesn't know FreshRSS.

Please help.

**Comment by littabird** [comment]
I found your answer, it works and it doesn't  > https://github.com/FreshRSS/FreshRSS/issues/1779

Edited ./FreshRSS/data/config.php and set 'auth_type' => 'none',
 > I could get in . and then 
go to Configuration / Profile, and change your password
go to Administration / Authentication, and change the Authentication method back to Web Form
> After this, same thing > Button Doesn't Work at all.

check the logs: > How?

Possible errors include wrong file permissions on the server and JavaScript errors
> YES. But how do I know?

If login via Web Form cannot work for you, it is also possible to login via HTTP Auth.
> How to do this?

Thanks in advance.

**Comment by littabird** [comment]
Finally found this > The solution is mentioned as follow:-

@plopoyop The fix I did for Yunohost HTTP login #1756 introduced a bug for people using double authentication (HTTP login + Web form), which should be fixed with this patch. Let me know if you get a chance to give it a try.
By the way, if you have not yet updated the Yunohost package to 1.10.0, you can skip it and go directly for 1.10.1, which I will try to release during the week-end :-)

Where is the patch... I don't know where to find it? And what do I do with the patch ... just upload?

**Comment by littabird** [comment]
After days, we finally found out what's the problem?

It's appear my problem is Cloudfare's Rocket Loader™ https://support.cloudflare.com/hc/en-us/articles/200168056-What-does-Rocket-Loader-do-

I could log in after switching off Rocket Loader™

Meaning it's obvious there is conflict between you and cloudfare. It seems there is solution > 

**If you have a Content Security Policy, you will need to update it to allow Rocket Loader to run: What is Content Security Policy (CSP), and how can I use it with Cloudflare?** 
https://support.cloudflare.com/hc/en-us/articles/216537517-What-is-Content-Security-Policy-CSP-and-how-can-I-use-it-with-Cloudflare-

Can you take a look if I can switch back on the  Rocket Loader™?

**Comment by Alkarex** [comment]
Hello,
The problems due to Cloudflare have already been discussed. See e.g. https://github.com/FreshRSS/FreshRSS/issues/1681#issuecomment-368221829
Cloudflare is breaking pages due to script injection, which are appropriately blocked by the default CSP rules in FreshRSS. You can either switch off those Cloudflare options, or reduce the the security by removing CSP rules at your Web server level.
Nothing wrong on FreshRSS side as far as I can see. For the record, Cloudflare is breaking the Web in several ways (see e.g. https://github.com/FreshRSS/FreshRSS/issues/1646#issuecomment-355857451 ) and it would not be a good time investment for FreshRSS to implement workarounds for their non-standard products.

**Comment by littabird** [comment]
https://github.com/FreshRSS/FreshRSS/issues/3617#issuecomment-841795350 > You can either switch off those Cloudflare options, or reduce the the security by removing CSP rules at your Web server level.

1.  switch off those Cloudflare options is NOT an option as I needed the speed for not only the main site, but also the subdomains -- all don't seem to have problem with Cloudfare.
So, 
2.  reduce the the security by removing CSP rules at your Web server level. -- This must be my only fix but I don't how?
CSP compatibility with Cloudflare Rocket Loader:
_**script-src 'self' ajax.cloudflare.com;**_
> **Where do I put/change this line of code?**

3. What about making an **Open** FreshRSS (with backend administration)?
- Pretty sure this will resolve the Cloudfare conflict as well (as I am yet to see a website script having conflict with Cloudfare)?

**Comment by Alkarex** [comment]
Sorry, this is not a problem with FreshRSS but with Cloudflare (injecting some bad code) so please ask their support or lookup a Web server administration tutorial (e.g. Apache). Hint, this has already been discussed in our tickets (e.g., https://github.com/FreshRSS/FreshRSS/issues/1075#issuecomment-832338116 ). FreshRSS is as open as it can be, as opposed to Cloudflare.

**Comment by littabird** [comment]
https://github.com/FreshRSS/FreshRSS/issues/3617#issuecomment-841876457 > not a problem with FreshRSS but with Cloudflare
- Fair enough and I will respect that . 

**UPDATE: Cloudfare provides an easy fix  > Create a Page Rule to match sub.example.com/ to set Rocket Loader to Off.**

NEXT... Lets Make FreshRSS Greater

> FreshRSS is as open as it can be, as opposed to Cloudflare.
-  It sounds like you're pissed off with Cloudfare? Take it easy, I wasn't pitching FreshRSS vs. Cloudfare. 
- When I said "OPEN", I mean not only to have a FreshRSS that **doesn't require login**. But also designed for the public to read in mind. Of course I know how to switch on anonymous browsing... that's good. 
- However, I wish the UX can be improved a little so that it's more webmaster-friendly eg. make a simple admin section for managing the feeds meant for the public to read vs. for me to read alone --  which requires slightly different settings eg. allowing readers to do something while not others. Basically, let readers have a bit more functions to make their viewing more enjoyable eg. Read/Unread etc (right now, there's virtually nothing they can do, not even starring or sharing).
- Apart from sharing feeds, FreshRSS canbe easily be transformed into a social network eg. allow sharing everywhere including mobile apps using this buttons https://www.addtoany.com/ (hosted mobile workers script enabling web to interact with cellphone). 

I'd be happy to contribute if you wanna take a look... I seriously think an "open" version can help take FreshRSS to another level ... perhaps FreshRSS will replace WordPress someday? Give it a thought.

**Comment by Alkarex** [comment]
Ah, I misunderstood what you meant with *open*. The reason you might not have observed problems with other scripts is that not all scripts have default security settings, but FreshRSS does has some (e.g. CSP), which is a good practice (but can be overridden by a system admin).
We already have a "share with" option for articles, also on mobile, although maybe not as advanced as what you want.

**Comment by littabird** [comment]
https://github.com/FreshRSS/FreshRSS/issues/3617#issuecomment-841883202 > UPDATE Cloudfare provides an easy fix > Create a Page Rule to match sub.example.com/ to set Rocket Loader to Off.
Unfortunately this doesn't fix all the problem. While the frontpage seems to work after the Rocket Loader was disabled using the Page Rule. But I just found out functions provided by **Extension** eg. Title Wrap or Mobile Swipe etc. are **NOT working** at all.
I am trying to get further help from Cloudfare, but I am not that optimistic there is more fix other then shutting Cloudfare altogether?

**Comment by littabird** [comment]
Alkarex, 

Following the Update https://github.com/FreshRSS/FreshRSS/issues/3617#issuecomment-842617187 ... I seriously think you should consider to make a website script for FreshRSS.

1. One of the reasons is the existing script is it's NOT cacheable -- this alone means FreshRSS is NOT suitable for public viewing becos it will take up too much resources (if there is significant traffics).

While I'd still use FreshRSS for personal reading (which I can easily share with thousands more, if only it's a open web app like WordPress), I sincerely hope you will make an open FreshRSS that is free from the Cloudfare conflicts.

2. One way to do that is to ride on an established CMS like WordPress > I believe FreshRSS can be easily wrapped in a plugin. That way, not only you don't need any CSP, WordPress has all the plugins that will provide all the functions you can only dream of... eg. Caching is one, security like WordFence is another... There are millions of option, many with millions of installed base.

3.  > We already have a "share with" option

Yes. But the listed options are far from useful. Beside FB and Twitter, you have listed all the sharing apps that no one uses? I can see you are "Fediverse" person, but the truth is hardly anyone use things like Wallabag, Sharti, or social platforms from EU like Movim etc. 

Other than FB/Twitter, folks usually use Messenger, Whatsapp, Telegram, Reddit, email, and **cellphone apps,**, which you can never invoke with web script, you need to host worker script like this guy https://www.addtoany.com/ (they already have more than 500,000 installs)

I am ready to contribute... Just ping me when you're ready to make a "Open" FreshRSS. I feel you can easily garner hundreds of thousand installs if you make a plugin for WordPress. Forget about the "decentralized" hype, Elon Musk just ran way from Bitcoin... It's time to make something for non-programmers. Make an Open FreshRSS.
