### ISSUE TITLE
[BUG] Possible file manipulation vulnerability 

### ISSUE THREAD

**Issue by enferas** [FreshRSS/FreshRSS#3619]
Hello,

I would like to report for a possible path manipulation vulnerability.

In file FreshRSS\app\Controllers\javascriptController.php

line 31
```php
// the source
$user = isset($_GET['user']) ? $_GET['user'] : '';
if (FreshRSS_Context::initUser($user)) { // inside this function there is Minz_Session::_param('currentUser', $username); then the source in the session
    // ....
} else {
    Minz_Log::notice('Nonce failure due to invalid username!');
}
```

in the log.php line 128
```php
public static function notice($msg, $file_name = null) {
		self::record($msg, LOG_NOTICE, $file_name);
	}
``` 

in the log.php line 22
```php
public static function record ($information, $level, $file_name = null) {
	//...
		$username = Minz_Session::param('currentUser', ''); // the source will return back from the session
       // ...
                $file_name = join_path(USERS_PATH, $username, 'log.txt'); // this function will join all the arguments together.
       //....
       // the sink in line 70 with the source in $file_name
                 if (file_put_contents($file_name, $log, FILE_APPEND | LOCK_EX) === false) {
				//....
			}
```

in file lib_rss.php line 24
```php
function join_path() {
	$path_parts = func_get_args();
	return join(DIRECTORY_SEPARATOR, $path_parts);
}
```

Note: I checked this vulnerability statically, I didn't deploy the project.

**Comment by Frenzie** [comment]
I'm not sure if I fully understand what you're getting at. To be clear, the username does not allow for Bobby Tables type situations (or in this case something like `./../../../etc/passwd`, I suppose?).

https://github.com/FreshRSS/FreshRSS/blob/1f24a5d50eba30dcdbf26106f539c6c47eea439f/app/Controllers/userController.php#L11-L15

**Comment by enferas** [comment]
Thank you for you response.

It is true that there is check for the user name that I didn't attention to it.
