### ISSUE TITLE
[Feature] Is there a way to restrict adding feeds to a pre-defined list of sites?

### ISSUE THREAD

**Issue by tareefdev** [FreshRSS/FreshRSS#3622]
**Is your feature request related to a problem? Please describe.**
I'm wondering if there is a way (like a plugin) to restrict adding feeds to a pre-defined list of sites. Say I have a list of 100 sites and want to make the user able only to follow sites from this list.

**Comment by Alkarex** [comment]
Hello,
No, this is not something we have at the moment. However, it would be possible to make a little FreshRSS extension for that. There is an API hook `check_url_before_add` https://freshrss.github.io/FreshRSS/en/developers/03_Backend/05_Extensions.html

**Comment by aledeg** [comment]
As a side note, this would be a system extension so the user cannot modify that list.

**Comment by tareefdev** [comment]
Thanks, this fits my needs, you could close this issue.

**Comment by aledeg** [comment]
Are you going to build an extension? How is your question answered?
I would like to know how your question has been addressed.
Thank you!

**Comment by tareefdev** [comment]
I mean that having the `check_url_before_add` hook could meet my needs. I'm evaluating several RSS aggregators to see which one I will go with, this process considering several criteria. If I'll go with FreshRSS I could try to write an extension myself first (though I did not use PHP before) or seeking help.

**Comment by aledeg** [comment]
I found your challenge interesting so I started writing an extension. But the core of FreshRss was missing a few things to make it work properly. So I've opened #3629 and #3626.

**Comment by aledeg** [comment]
@tareefdev I have a working extension to check url on a white list. It's not usable until #3626 is merged.
I've checked exact feeds for now but the rule can be enhance to be more flexible.

**Comment by aledeg** [comment]
The white list extension is available [here](https://github.com/aledeg/xExtension-WhiteList). It is not yet visible in the extension page but can still be installed.
It is a bit rough around the edges but it works.

We might just close that issue now.
