### ISSUE TITLE
[Feature] JavaScript support for themes

### ISSUE THREAD

**Issue by Offerel** [FreshRSS/FreshRSS#3625]
I would like to create my own custom theme. Creating and inserting the css files is no problem, this works so far. But i have also 2 JavaScript functions, which i want to insert with my theme. These functions are not possible with pure css. Is there a way to add a JavaScript file along with a theme in metadata.json, so that, when the user select the theme, he also inserts this Javascript file?

**Comment by aledeg** [comment]
Not at the moment. As a workaround, you can use CustomJS extension to add your JS code (not file).
If you need to add files, you could create an extension loading those files. You can check what is done on one of the existing extensions.

**Comment by Offerel** [comment]
After some struggling, i could made this to work with pure css (the css file changes a little bit more as only the movable panel). My goal was it, that i could resize the left panel. For this, I have extended the Swage theme. If someone find this useful, feel free to use it.

At least in my case, i have saved this as a own theme, so i can select it easier from the Web GUI.
[extend.css.txt](https://github.com/FreshRSS/FreshRSS/files/6500686/extend.css.txt)

**Comment by Offerel** [comment]
From my point of view, we can close this issue. But im not sure, if you want to add this as some sort of feature request for a later release.

**Comment by math-GH** [comment]
It is done with #3739 (will shipped with the next release)

**Comment by math-GH** [comment]
Please close this ticket @aledeg . It is solved.
