### ISSUE TITLE
[BUG] Port not respected in "iconUrl" property

### ISSUE THREAD

**Issue by martinrotter** [FreshRSS/FreshRSS#3628]
**Describe the bug**
When calling greader API endpoint `reader/api/0/subscription/list?output=json`, then resulting "iconUrl" properties do not respect server's port. For example:

```json
    {
      "id": "feed/134",
      "title": "  Bartosz Milewski's Programming Cafe",
      "categories": [
        {
          "id": "user/-/label/Personal Blogs",
          "label": "Personal Blogs"
        }
      ],
      "url": "https://bartoszmilewski.com/feed/",
      "htmlUrl": "http://bartoszmilewski.com/",
      "iconUrl": "http://192.168.2.168/f.php?506c4f68"
    }
```

I have configured FreshRSS to run with source port `10100`, so it is accessible in this local address in my network: `http://192.168.2.168:10100`, therefore `iconUrl` should be rather `http://192.168.2.168:10100/f.php?506c4f68`.

This bug impacts RSS Guard and slows down fetching of "favicons" of feeds, slowing down feeds synchronization process.

**Comment by aledeg** [comment]
Could you provide the values of all the headers? My guess is there might be a problem while extracting them from the request.

**Comment by martinrotter** [comment]
@aledeg You mean HTTP/request headers?

**Comment by aledeg** [comment]
Yes! You have them displayed in the server live log (at least, I have them on my local dev environment).

**Comment by martinrotter** [comment]
[freshtest.txt](https://github.com/FreshRSS/FreshRSS/files/6522140/freshtest.txt)

**Comment by aledeg** [comment]
Thank you!
Could you also provide the server envvars? You should see them in the server live log. I wasn't really precise with my previous request. They are displayed when you check for the API compatibility.
Here is what I have when I launch that on my dev serveur.

```
FreshRSS[25]: [_] [Fri, 21 May 2021 11:25:46 +0000] [warning] --- checkCompatibility() Array
FreshRSS[25]: (
FreshRSS[25]:     [date] => 2021-05-21T11:25:46+00:00
FreshRSS[25]:     [headers] => Array
FreshRSS[25]:         (
FreshRSS[25]:             [Host] => localhost:8080
FreshRSS[25]:             [User-Agent] => Mozilla/5.0 (X11; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0
FreshRSS[25]:             [Accept] => */*
FreshRSS[25]:             [Accept-Language] => en-US,en;q=0.5
FreshRSS[25]:             [Accept-Encoding] => gzip, deflate
FreshRSS[25]:             [Authorization] => GoogleLogin auth=test/1
FreshRSS[25]:             [Connection] => keep-alive
FreshRSS[25]:             [Referer] => http://localhost:8080/api/
FreshRSS[25]:             [DNT] => 1
FreshRSS[25]:             [Sec-GPC] => 1
FreshRSS[25]:         )
FreshRSS[25]: 
FreshRSS[25]:     [_SERVER] => Array
172.17.0.1 - - [21/May/2021:11:25:46 +0000] "GET /api/fever.php?api HTTP/1.1" 200 26 "http://localhost:8080/api/" "Mozilla/5.0 (X11; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0"
FreshRSS[25]:         (
FreshRSS[25]:             [HTTP_AUTHORIZATION] => GoogleLogin auth=test/1
FreshRSS[25]:             [HTTP_HOST] => localhost:8080
FreshRSS[25]:             [HTTP_USER_AGENT] => Mozilla/5.0 (X11; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0
FreshRSS[25]:             [HTTP_ACCEPT] => */*
FreshRSS[25]:             [HTTP_ACCEPT_LANGUAGE] => en-US,en;q=0.5
FreshRSS[25]:             [HTTP_ACCEPT_ENCODING] => gzip, deflate
FreshRSS[25]:             [HTTP_CONNECTION] => keep-alive
FreshRSS[25]:             [HTTP_REFERER] => http://localhost:8080/api/
FreshRSS[25]:             [HTTP_DNT] => 1
FreshRSS[25]:             [HTTP_SEC_GPC] => 1
FreshRSS[25]:             [PATH] => /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
FreshRSS[25]:             [SERVER_SIGNATURE] => <address>Apache/2.4.46 (Unix) Server at localhost Port 8080</address>
FreshRSS[25]: 
FreshRSS[25]:             [SERVER_SOFTWARE] => Apache/2.4.46 (Unix)
FreshRSS[25]:             [SERVER_NAME] => localhost
FreshRSS[25]:             [SERVER_ADDR] => 172.17.0.2
FreshRSS[25]:             [SERVER_PORT] => 8080
FreshRSS[25]:             [REMOTE_ADDR] => 172.17.0.1
FreshRSS[25]:             [DOCUMENT_ROOT] => /var/www/FreshRSS/p/
FreshRSS[25]:             [REQUEST_SCHEME] => http
FreshRSS[25]:             [CONTEXT_PREFIX] => 
FreshRSS[25]:             [CONTEXT_DOCUMENT_ROOT] => /var/www/FreshRSS/p/
FreshRSS[25]:             [SERVER_ADMIN] => you@example.com
FreshRSS[25]:             [SCRIPT_FILENAME] => /var/www/FreshRSS/p/api/greader.php
FreshRSS[25]:             [REMOTE_PORT] => 50472
FreshRSS[25]:             [GATEWAY_INTERFACE] => CGI/1.1
FreshRSS[25]:             [SERVER_PROTOCOL] => HTTP/1.1
FreshRSS[25]:             [REQUEST_METHOD] => GET
FreshRSS[25]:             [QUERY_STRING] => 
FreshRSS[25]:             [REQUEST_URI] => /api/greader.php/check/compatibility
FreshRSS[25]:             [SCRIPT_NAME] => /api/greader.php
FreshRSS[25]:             [PATH_INFO] => /check/compatibility
FreshRSS[25]:             [PATH_TRANSLATED] => /var/www/FreshRSS/p/check/compatibility
FreshRSS[25]:             [PHP_SELF] => /api/greader.php/check/compatibility
FreshRSS[25]:             [REQUEST_TIME_FLOAT] => 1621596346.5956
FreshRSS[25]:             [REQUEST_TIME] => 1621596346
FreshRSS[25]:         )
FreshRSS[25]: 
FreshRSS[25]:     [_GET] => Array
FreshRSS[25]:         (
FreshRSS[25]:         )
FreshRSS[25]: 
FreshRSS[25]:     [_POST] => Array
FreshRSS[25]:         (
FreshRSS[25]:         )
FreshRSS[25]: 
FreshRSS[25]:     [_COOKIE] => Array
FreshRSS[25]:         (
FreshRSS[25]:         )
FreshRSS[25]: 
FreshRSS[25]:     [INPUT] => 
FreshRSS[25]: )
```

**Comment by martinrotter** [comment]
I wrote some extra info in the other ticket, I will continue only there as it seems these two issues have same cause.

Btw, I run Freshrss from this: https://hub.docker.com/r/linuxserver/freshrss

Not sure how to get the above output when running via docker image.

**Comment by martinrotter** [comment]
Btw, the port is of course confused by docker setting "-p 8888:80" but FreshRSS should probably respect "Host" HTTP header which discovers "real" "WAN" port in this context.

**Comment by aledeg** [comment]
I think there is something else since I've change the port in my config file and my output has not changed. I still have the right port. I cannot put my finger on it though :/

**Comment by martinrotter** [comment]
> 
> 
> I think there is something else since I've change the port in my config file and my output has not changed. I still have the right port. I cannot put my finger on it though :/

What I basically did was:

1. "docker pull" https://hub.docker.com/r/linuxserver/freshrss
2. Go to freshrss address and finalize installation.
3. Restart docker to make sure it now gets different IP address from gateway.
4. Test.

Here is the command used to run docker image: 
![image](https://user-images.githubusercontent.com/1255302/119134293-4185ef00-ba3d-11eb-900b-7e219239b9e8.png)

**Comment by aledeg** [comment]
My bad, my test was flawed. When I changed the base URL, it has impacted my output.
If you add the port in there, you'll have the proper URL.
I know that's not ideal since you might end up with a different URL when reconnecting to your DHCP server.

@Alkarex any thoughts?

**Comment by aledeg** [comment]
When calling the compatibility page, the values seems to be extracted directly from the server itself and seems to not use the baseurl from the file. We might want to replicate this behavior in the API.

**Comment by martinrotter** [comment]
@aledeg I believe that `HOST` header should be honored as it really makes no sense to not use it, especially if it differs from `base_url`.

I also believe that guy who reported https://github.com/martinrotter/rssguard/issues/413 actually bumped into this very bug, so his environment is setup in a similar fashion as my testing environment.

**Comment by Alkarex** [comment]
I cannot reproduce any problem. Everything seems to work as expected.
If you still believe there is any bug, please try first with one of our official Docker images: https://hub.docker.com/r/freshrss/freshrss/

## Test with default setup
The base URL is detected during the initial setup with the following value: `'base_url' => 'http://localhost:8080',`.
The port seems to work well:

```sh
curl -s -H "Authorization:GoogleLogin auth=freshrss/13d63c47c2a470eec88a440a626f964ab2ecd479" 'http://localhost:8080/api/greader.php/reader/api/0/subscription/list?output=json' | jq .
```

```json
{
  "subscriptions": [
    {
      "id": "feed/1",
      "title": "FreshRSS releases",
      "categories": [
        {
          "id": "user/-/label/Sans catégorie",
          "label": "Sans catégorie"
        }
      ],
      "url": "https://github.com/FreshRSS/FreshRSS/releases.atom",
      "htmlUrl": "https://github.com/FreshRSS/FreshRSS/",
      "iconUrl": "http://localhost:8080/f.php?23713db5"
    }
  ]
}
```

## Test with manual override
After manually overriding the base URL to `'base_url' => 'http://example.net:8082',`:


```sh
{
  "subscriptions": [
    {
      "id": "feed/1",
      "title": "FreshRSS releases",
      "categories": [
        {
          "id": "user/-/label/Sans catégorie",
          "label": "Sans catégorie"
        }
      ],
      "url": "https://github.com/FreshRSS/FreshRSS/releases.atom",
      "htmlUrl": "https://github.com/FreshRSS/FreshRSS/",
      "iconUrl": "http://example.net:8082/f.php?23713db5"
    }
  ]
}
```

## Test with automatic base URL
After manually overriding the base URL to `'base_url' => '',` (which forces a permanent detection of the base URL, which is not a good idea - slower and breaks some features such as WebSub for cron job)

```
{
  "subscriptions": [
    {
      "id": "feed/1",
      "title": "FreshRSS releases",
      "categories": [
        {
          "id": "user/-/label/Sans catégorie",
          "label": "Sans catégorie"
        }
      ],
      "url": "https://github.com/FreshRSS/FreshRSS/releases.atom",
      "htmlUrl": "https://github.com/FreshRSS/FreshRSS/",
      "iconUrl": "http://localhost:8080/api/greader.php/reader/api/0/f.php?23713db5"
    }
  ]
}
```
