### ISSUE TITLE
[BUG] 500 error thrown when accessing freshrss with readrops

### ISSUE THREAD

**Issue by tinruufu** [FreshRSS/FreshRSS#3630]
**Describe the bug**
i'm getting a 500 error on my freshrss instance whenever i try to use it from [readrops](https://github.com/readrops/Readrops)

**To Reproduce**
1. install readrops on an android device from f-droid
2. authenticate on your freshrss instance
3. try to load your feeds
4. readrops, despite having successfully authenticated, shows that the server is responding with a 500
5. the server logs  `PHP Notice:  Undefined offset: 0 in /usr/local/share/FreshRSS/app/Models/TagDAO.php on line 352` and `PHP Notice:  Undefined offset: 0 in /usr/local/share/FreshRSS/app/Models/TagDAO.php on line 356`, and then:

```
PHP Fatal error:  Uncaught Error: Object of class FreshRSS_Entry could not be converted to string in /usr/local/share/FreshRSS/app/Models/TagDAO.php:368\nStack trace:\n#0 /usr/local/share/FreshRSS/app/Models/TagDAO.php(368): PDOStatement->execute()\n#1 /usr/local/share/FreshRSS/app/Models/TagDAO.php(347): FreshRSS_TagDAO->getTagsForEntries()\n#2 /usr/local/share/FreshRSS/app/Models/TagDAO.php(383): FreshRSS_TagDAO->getTagsForEntries()\n#3 /usr/local/share/FreshRSS/p/api/greader.php(508): FreshRSS_TagDAO->getEntryIdsTagNames()\n#4 /usr/local/share/FreshRSS/p/api/greader.php(688): entriesToArray()\n#5 /usr/local/share/FreshRSS/p/api/greader.php(1046): streamContents()\n#6 {main}\n  thrown in /usr/local/share/FreshRSS/app/Models/TagDAO.php on line 368
```

**Expected behavior**
the feeds all load in readrops

**Environment information**
 - OS: Ubuntu 20.04.2
 - FreshRSS version: 1.18.1-dev
 - Database version: mysql 8.0
 - PHP version: PHP 7.4.3

**Additional context**
if it was throwing anything other than a 500, i'd be blaming readrops for this, but it's an unhandled exception so it seems like it should belong here. if it helps, readrops is 1.2.1 (12) from f-droid, and it's hitting `/api/greader.php/reader/api/0/stream/contents/user/-/state/com.google/reading-list?xt=user%2F-%2Fstate%2Fcom.google%2Fread&n=500` to generate the 500. i have tried disabling all extensions, and it still happens. other clients (netnewswire, easyrss, "freshrss" on f-droid) work fine, but they're hitting a different url

**Comment by Alkarex** [comment]
Thanks for the bug report. Could you please try this fix? https://github.com/FreshRSS/FreshRSS/pull/3631
(I do not have time to test myself tonight)

**Comment by tinruufu** [comment]
yes, that seemed to sort it; feeds are loading in readrops after checking out that branch. thank you for the very quick response!

**Comment by Alkarex** [comment]
@tinruufu Thanks for the quick test
