### ISSUE TITLE
[Feature] Automatic Refresh via Webhook

### ISSUE THREAD

**Issue by marcohald** [FreshRSS/FreshRSS#3634]
**Is your feature request related to a problem? Please describe.**
I use a shared hoster where i can not confiugre Cronjobs.
However i would like to automatically refresh my Subscriptions

**Describe the solution you'd like**
Call the ./app/actualize_script.php via HTTP

A direct call via HTTP get me to this error
FreshRSS error: This PHP script may only be invoked from command line!

**Comment by Frenzie** [comment]
Please see https://freshrss.github.io/FreshRSS/en/users/03_Main_view.html#online-cron

**Comment by aledeg** [comment]
Maybe the documentation is missing something if that kind of question arise

**Comment by Frenzie** [comment]
Perhaps the command line scripts could provide an extra contextual error message?
