### ISSUE TITLE
[BUG] Error updating via Web UI

### ISSUE THREAD

**Issue by FuturePilot** [FreshRSS/FreshRSS#3638]
**Describe the bug**
Can't update via the Web UI because of git error

**To Reproduce**
1. Got to Administration -> Update
2. Click on Apply
3. Error message says `The update process has encountered an error: Git error: HEAD is now at c3074d67 Add rssguard to french readme too (#3632)`

**Expected behavior**
Update should be applied successfully

**Environment information (please complete the following information):**
 - Device: Any
 - OS: (server) Debian 10.9
 - Browser: Any
 - FreshRSS version: 1.18.1-dev
 - Database version: MariaDB 10.3.27-0+deb10u1
 - PHP version: PHP 7.3
 - Installation type: VPS

**Additional context**
The FreshRSS log shows 
`[Wed, 26 May 2021 12:42:29 -0400] [warning] --- Git error:Error during git checkout to edge branch. Please change branch manually!`
I tried a git reset and git pull but it says it is up to date. Do I need to change branches?

**Comment by Alkarex** [comment]
Indeed, the old *master* and *dev* branches have been renamed to *edge*

**Comment by FuturePilot** [comment]
I'm still getting this error but I do appear to be on the edge branch
```
git status
On branch edge
Your branch is up to date with 'origin/edge'.

nothing to commit, working tree clean
```
