### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by Jacob-zh** [FreshRSS/FreshRSS#3640]
<p>
As shown below,<br>
When the installation starts, there is no Next button.
‘Go to the next step’<br>
What should I do?
</p>

![](https://jacobs-public-static-resources.oss-cn-hangzhou.aliyuncs.com/gallery/20210529174817.png?x-oss-process=style/webp)

**Comment by Frenzie** [comment]
I'm not sure if I quite follow. Are you saying that submit isn't working?

**Comment by Jacob-zh** [comment]
> I'm not sure if I quite follow. Are you saying that submit isn't working?

This is the first step of the installation. After selecting the language, the installation cannot proceed to the next step.
Even if I click submit, it is only on the current page and cannot perform the next steps.

**Comment by Alkarex** [comment]
@Jacob-zh Please check any error in your browser console, Web server logs, and FreshRSS logs. Remember to provide information about your system when submitting bugs (OS, versions, type of FreshRSS installation and deployment...).
It looks like a problem with cookies and/or PHP sessions.
