### ISSUE TITLE
[BUG] errors from the browser console: font errors

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#3641]
**Describe the bug**
Login screen, see browser console
![image](https://user-images.githubusercontent.com/1645099/120074316-87c1fa80-c09c-11eb-90e5-83027fcb551c.png)

after login on the feed overview page
![image](https://user-images.githubusercontent.com/1645099/120074391-f1420900-c09c-11eb-932e-45d2ecd4315f.png)

**Expected behavior**
no errors

**Environment information (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 88
 - FreshRSS version: 1.18.0

**Additional context**
strict browser privacy
![image](https://user-images.githubusercontent.com/1645099/120074426-28b0b580-c09d-11eb-8cf9-1662aa5418da.png)

**Comment by Alkarex** [comment]
The two warnings regarding the fonts might be something for us to address, but the rest is normal and not coming from us but from some blocked third-part content coming from some articles

**Comment by Alkarex** [comment]
P.S. There is nothing called jquery-3.1.0.min.js in FreshRSS, and we only use jQuery (but not that file) for the statistics view

**Comment by Alkarex** [comment]
P.P.S: Make sure it is not coming from a FreshRSS extension

**Comment by math-GH** [comment]
> 
> 
> P.S. There is nothing called jquery-3.1.0.min.js in FreshRSS, and we only use jQuery (but not that file) for the statistics view

OK. Thanks for that hint. I deinstalled all extensions and opened FreshRSS in private browser mode. The jQuery errors disappeared.
You are right, it is not an FreshRSS issue. Now I have to investigate where it comes from.

**Comment by math-GH** [comment]
> The two warnings regarding the fonts might be something for us to address, but the rest is normal and not coming from us but from some blocked third-part content coming from some articles

It boils down this issue to this errors.

**Comment by aledeg** [comment]
What theme are you using. I can not reproduce the font errors. It might be related to a theme I am not using. Thank you!

**Comment by math-GH** [comment]
> 
> 
> What theme are you using. I can not reproduce the font errors. It might be related to a theme I am not using. Thank you!

Origine — By: Marien Fressinaud
Le thème par défaut pour FreshRSS

**Comment by aledeg** [comment]
Thank you. I can reproduce.

**Comment by aledeg** [comment]
After some digging, it seems that it's a Firefox issue and they do not intend to fix it.
See https://bugzilla.mozilla.org/show_bug.cgi?id=1185685

**Comment by math-GH** [comment]
> 
> 
> After some digging, it seems that it's a Firefox issue and they do not intend to fix it.
> See https://bugzilla.mozilla.org/show_bug.cgi?id=1185685

thanks for investigation

**Comment by aledeg** [comment]
There's nothing that we can do on our side. I am closing.
