### ISSUE TITLE
[BUG] add some feeds -> link to wrong page

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#3642]
**To Reproduce**
![image](https://user-images.githubusercontent.com/1645099/120074990-bf7e7180-c09f-11eb-98af-2cc081a2d955.png)
links to subscription management
![image](https://user-images.githubusercontent.com/1645099/120075008-d6bd5f00-c09f-11eb-95d5-5f04ebb98408.png)

**Expected behavior**
links to "Add a feed or category", because I clicked to add a feed. management has no adding option.

**Environment information (please complete the following information):**
 - FreshRSS version: 1.18.0

**Comment by math-GH** [comment]
yes, I know the yellow text "Feed and category creation has been moved here. It is also accessible from the menu on the left and from the ✚ icon available on the main page. "

**Comment by aledeg** [comment]
@mathContao  Please check the linked PR. Thank you!
