### ISSUE TITLE
[Feature] use HTML5 tags

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#3643]
**Is your feature request related to a problem? Please describe.**
I would like to read the feeds with the Browser reader
Firefox Reader View: https://support.mozilla.org/en-US/kb/firefox-reader-view-clutter-free-web-pages

**Describe the solution you'd like**
One of the reasons is, that the HTML5 tags <header> <main> <footer> and <nav> are not used.

**Additional context**
It could also help for users with a screen reader to navigate through the page

**Comment by Alkarex** [comment]
Could you please be more precise about what tags / elements would be needed and for which parts?

**Comment by math-GH** [comment]
@Alkarex I created a PR. It explains what I mean
