### ISSUE TITLE
[BUG] update error

### ISSUE THREAD

**Issue by prolibre** [FreshRSS/FreshRSS#3644]
**Version: 1.18.1-dev.** 

When I update from the web interface I get an error message: "The update encountered a problem: Git error: HEAD is now at 319d7dc1 Minor whitespace (#3639)". Then it asks me again to apply the update. If I do "Apply the update" I get the error message again.
I already had an error with the previous update.

If I do a git pull in console it tells me that my version is already up to date. I deleted the file "/data/update.php" to make the message "Apply the update" disappear.

---

**Version :  1.18.1-dev.** 

Quand je fais une mise à jour depuis l'interface web j'ai un message d'erreur qui apparait : "La mise à jour a rencontré un problème : Git error: HEAD is now at 319d7dc1 Minor whitespace (#3639)". Ensuite il me demande à nouveau d'appliquer la mise à jour. Si je fais "Appliquer la mise à jour" j'ai à nouveau le message d'erreur.
J'avais déjà une erreur lors de la précédente mise à jour.

Si je fais un "git pull" en console il me dit que ma version est déjà à jour. J'ai supprimé le fichier "/data/update.php" pour faire disparaitre le message "Appliquer la mise à jour".

**Comment by Alkarex** [comment]
Thanks for the bug report.
The error message should be fixed by https://github.com/FreshRSS/FreshRSS/pull/3645
You should then still get an error, but at least with the correct message :-)

**Comment by Alkarex** [comment]
Could you please try again?
You will then probably have the same message than https://github.com/FreshRSS/FreshRSS/issues/3638

**Comment by prolibre** [comment]
Sorry, I'm a bit late. Yes I have the message: 

La mise à jour a rencontré un problème : Git error: Error during git checkout to edge branch. Please change branch manually!

Have a good day @Alkarex
