### ISSUE TITLE
documentation: what is a default user

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#3646]
Hi,

I cannot find information about "What is a 'default user'" in the documentation.

As I see it is by default the first created user.
- What is the benefit to be a default user?
- What happens if I delete the user?
- How can I change and upgrade another user to default user?

Here (https://freshrss.github.io/FreshRSS/en/admins/04_Frequently_Asked_Questions.html) it is written, that only one user can be the admin (in the CLI the command is "default_user"), but I have 2 admins

![image](https://user-images.githubusercontent.com/1645099/120116677-92a68900-c189-11eb-8698-4d1ff8eef46f.png)

could we clarify it and add information to the docs? Thanks a lot

**Comment by Frenzie** [comment]
That should be removed.
https://github.com/FreshRSS/FreshRSS/pull/2709

**Comment by Alkarex** [comment]
Indeed, the documentation should be updated. There can be multiple admins (additional rights). The default user is in particular relevant when using the anonymous mode (without login)

**Comment by math-GH** [comment]
> 
> 
> Indeed, the documentation should be updated. There can be multiple admins (additional rights). The default user is in particular relevant when using the anonymous mode (without login)

What will happen when I delete this user?

**Comment by math-GH** [comment]
Documentation is done via #4083
