### ISSUE TITLE
[BUG] user create: without a passwort -> redirect to start page

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#3648]
**Describe the bug**
When I try to create a user without a password, than I will redirected to the start page without an error and without creating a new user

**To Reproduce**
go to "create new user",
input a user name (1), leave the password empty (2) and klick "submit" (3)
![image](https://user-images.githubusercontent.com/1645099/120117660-8a9d1800-c18e-11eb-8984-0d3f489d3bc4.png)

**Expected behavior**
a hint, that the password input field is empty. 
Do not expect a redirect to the start page

**Environment information (please complete the following information):**
 - Browser: Firefox 88
 - FreshRSS version: 1.18.0

**Comment by math-GH** [comment]
the same happens when I try to create the same username twice.

**Comment by aledeg** [comment]
@mathContao Check if #3656 fixes this problem.

**Comment by aledeg** [comment]
@Alkarex If I understand correctly this issue, I think I fixed it with #3656.
