### ISSUE TITLE
[BUG] installation routine: favicon missed

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#3657]
**Describe the bug**
in the installation routine there is the favicon.ico missed

**To Reproduce**
fresh FreshRSS, step 0 installation

**Expected behavior**
no error in the console

**Screenshots**
![image](https://user-images.githubusercontent.com/1645099/120380724-d0d6b080-c321-11eb-93fe-fd22fec19614.png)

**Environment information (please complete the following information):**
 - Browser: Firefox 88
 - FreshRSS version: tested with edge-branch, but I think it will be also in 1.18.0

**Comment by Frenzie** [comment]
> Expected behavior
no error in the console

I don't think that's true. ;-)

**Comment by math-GH** [comment]
how to fix it?

**Comment by Frenzie** [comment]
That's the thing, you can't. Microsoft decided back in '99 that they were always going to request favicon.ico and by the early 2000s all other browsers followed suit. It's the expected unexpected behavior.

**Comment by math-GH** [comment]
why is in the installing routine no favicon.ico and after the installing it is there?

**Comment by Frenzie** [comment]
That's a good point. :-D

Presumably this stuff is either not there or somehow broken. Let's see if I can quickly check.

```
		<link rel="shortcut icon" id="favicon" type="image/x-icon" sizes="16x16 64x64" href="../favicon.ico" />
		<link rel="icon msapplication-TileImage apple-touch-icon" type="image/png" sizes="256x256" href="../themes/icons/favicon-256.png" />
		<link rel="apple-touch-icon" href="../themes/icons/apple-touch-icon.png" />
```

**Comment by Frenzie** [comment]
Actually I can't seem to confirm with the Docker image. But you could try if this helps?

```diff
diff --git a/app/install.php b/app/install.php
index 5a4f3359..08d3e706 100644
--- a/app/install.php
+++ b/app/install.php
@@ -656,6 +656,13 @@ if (_t('gen.dir') === 'rtl') {
                <meta name="viewport" content="initial-scale=1.0" />
                <script id="jsonVars" type="application/json">{}</script>
                <title><?= _t('install.title') ?></title>
+               <link rel="shortcut icon" id="favicon" type="image/x-icon" sizes="16x16 64x64" href="<?= Minz_Url::display('/favicon.ico') ?>" />
+               <link rel="icon msapplication-TileImage apple-touch-icon" type="image/png" sizes="256x256" href="<?= Minz_Url::display('/themes/icons/favicon-256.png') ?>" />
+               <link rel="apple-touch-icon" href="<?= Minz_Url::display('/themes/icons/apple-touch-icon.png') ?>" />
+               <meta name="apple-mobile-web-app-capable" content="yes" />
+               <meta name="apple-mobile-web-app-status-bar-style" content="black" />
+               <meta name="apple-mobile-web-app-title" content="<?= FreshRSS_Context::$system_conf->title ?>">
+               <meta name="msapplication-TileColor" content="#FFF" />
                <link rel="stylesheet" href="../themes/base-theme/template.css?<?= @filemtime(PUBLIC_PATH . '/themes/base-theme/template.css') ?>" />
                <link rel="stylesheet" href="../themes/Origine/origine.css?<?= @filemtime(PUBLIC_PATH . '/themes/Origine/origine.css') ?>" />
                <meta name="robots" content="noindex,nofollow" />
```

**Comment by Alkarex** [comment]
Strange indeed, as we do have a https://github.com/FreshRSS/FreshRSS/blob/edge/p/favicon.ico
What is the corresponding server-side error in the logs, if any?

**Comment by math-GH** [comment]
with a fresh 1.18.1 installation:
here a insight from the step2 of the install routine
![grafik](https://user-images.githubusercontent.com/1645099/123324321-f7f65b80-d536-11eb-9479-f62819fdf334.png)

**Comment by math-GH** [comment]
> 
> 
> Actually I can't seem to confirm with the Docker image. But you could try if this helps?
> 
> ```diff
> diff --git a/app/install.php b/app/install.php
> index 5a4f3359..08d3e706 100644
> --- a/app/install.php
> +++ b/app/install.php
> @@ -656,6 +656,13 @@ if (_t('gen.dir') === 'rtl') {
>                 <meta name="viewport" content="initial-scale=1.0" />
>                 <script id="jsonVars" type="application/json">{}</script>
>                 <title><?= _t('install.title') ?></title>
> +               <link rel="shortcut icon" id="favicon" type="image/x-icon" sizes="16x16 64x64" href="<?= Minz_Url::display('/favicon.ico') ?>" />
> +               <link rel="icon msapplication-TileImage apple-touch-icon" type="image/png" sizes="256x256" href="<?= Minz_Url::display('/themes/icons/favicon-256.png') ?>" />
> +               <link rel="apple-touch-icon" href="<?= Minz_Url::display('/themes/icons/apple-touch-icon.png') ?>" />
> +               <meta name="apple-mobile-web-app-capable" content="yes" />
> +               <meta name="apple-mobile-web-app-status-bar-style" content="black" />
> +               <meta name="apple-mobile-web-app-title" content="<?= FreshRSS_Context::$system_conf->title ?>">
> +               <meta name="msapplication-TileColor" content="#FFF" />
>                 <link rel="stylesheet" href="../themes/base-theme/template.css?<?= @filemtime(PUBLIC_PATH . '/themes/base-theme/template.css') ?>" />
>                 <link rel="stylesheet" href="../themes/Origine/origine.css?<?= @filemtime(PUBLIC_PATH . '/themes/Origine/origine.css') ?>" />
>                 <meta name="robots" content="noindex,nofollow" />
> ```

yepp, that fix this issue

**Comment by math-GH** [comment]
OK, I guess I found the issue. It is a missconfiguration of my settings.

**Comment by Frenzie** [comment]
What was it precisely? :)

**Comment by math-GH** [comment]
the domain did not point to /p. It pointed to the root, where no favicon is stored.

So this PR is absolete.
But I will open a new issue to improve security

**Comment by Frenzie** [comment]
While it's a really minor issue, on reflection I'm not sure if that reasoning holds up. It's probably fairly normal to expose it as something like `domain.com/freshrss` rather than directly at the root.

**Comment by math-GH** [comment]
> While it's a really minor issue, on reflection I'm not sure if that reasoning holds up. It's probably fairly normal to expose it as something like `domain.com/freshrss` rather than directly at the root.

Alkarex added this also to #3679
