### ISSUE TITLE
Token multi-utilisateur

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#366]
Considérer permettre aussi aux utilisateurs autre que l'utilisateur par défaut d'utiliser un token pour accéder aux sorties RSS sans identification

**Comment by Alkarex** [comment]
Implémenté dans https://github.com/FreshRSS/FreshRSS/pull/1493
Tests bienvenus

**Comment by Vincent14** [comment]
Is it in production by now? In 1.6.3, the /i/?c=auth page give a way to use tokens that doesn't seem to be up to date (I didn't found myself the correct needed set of parameters by reading your commit)

**Comment by Alkarex** [comment]
@Vincent14 It is in the upcoming 1.7.0. Tests of the /dev branch welcome.
