### ISSUE TITLE
Running in Heroku (free/hobby mode) with mysql on clear DB, system reintialises on every restart.

### ISSUE THREAD

**Issue by pperrin** [FreshRSS/FreshRSS#3660]
I have setup FreshRSS on Heroku, and set up a mysql database on clearDB. it seems to work fine for a while, but when I leave it for a time and get back to it, FreshRSS requires me provide the database info again and start from scratch.

I am guessing that this info isn't being persisted between dyno restarts.

Can anyone tell me how to fix this?

Thanks

**Comment by Alkarex** [comment]
See https://github.com/FreshRSS/FreshRSS/pull/3555#issuecomment-841861577

**Comment by pperrin** [comment]
> See [#3555 (comment)](https://github.com/FreshRSS/FreshRSS/pull/3555#issuecomment-841861577)

Cheers, seems to be the identical issue - sorry that I couldn't find it earlier. Heroku creates an environmental  variable for its database connections, I will look to modifying the freshrss code to look for this variable before it does it am other stuff...

**Comment by pthall** [comment]
Hi @pperrin this was the hacky way I parse the environment vars, with a minor change in `lib/Minz/ModelPdo.php`

```
       private function dbConnect() {
               $db = Minz_Configuration::get('system')->db;
                # support heroku DATABASE_URL env string
               $db = parse_url(getenv("DATABASE_URL"));
               $db["base"] = ltrim($db["path"], "/");
               $db["type"] = "pgsql";
               $db["password"] = $db["pass"];
               $db["prefix"] = "";
                # end heroku changes
```

There are other major drawbacks with using Heroku. Anything changed under `data/` - `config.php` and `users` directory, for example, will be overwritten when heroku periodically cycles the web dyno. So, I committed and pushed any of those file changes to heroku.

**Comment by math-GH** [comment]
@pperrin Is it solved?

**Comment by Alkarex** [comment]
Slightly related PR https://github.com/FreshRSS/FreshRSS/pull/4497 , https://github.com/FreshRSS/FreshRSS/discussions/4494
Related discussion https://github.com/FreshRSS/FreshRSS/pull/3555#issuecomment-841861577
I guess we have an issue somewhere to consider storing user's config in database, which would reduce some of those problems. However, even with that, the platform does not seem to be the best match at the moment.

**Comment by pperrin** [comment]
Hi,

Sorry for not updating sooner...

Thanks @pthall for the suggestion.

In the end I got a Raspberry Pi on my home network to handle all my personal, light weight, Internet server requirements and it works fine.

It seems heroku is just not an ideal platform  for this software.
