### ISSUE TITLE
[BUG]  anonymous Reading: 403 Error while mark all as read

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#3661]
**Describe the bug**
403 error

**To Reproduce**

1. anonymous Reading (not logged in)
2. scroll to the end of feed list:
2. https://demo.freshrss.org/i/?a=normal&get=f_3 
![grafik](https://user-images.githubusercontent.com/1645099/120896578-8a839900-c622-11eb-8515-233484883214.png)

3. click on "Märk all as read"
4. get the error 403 
![grafik](https://user-images.githubusercontent.com/1645099/120896647-c4549f80-c622-11eb-9056-c1ea24cf2db3.png)

"Sie haben nicht die Berechtigung, diese Seite aufzurufen [CSRF]" => You do not have the permission to open this page [CSRF]

I do not have a clue why it is in German but the rest of texts are in English

**Expected behavior**
no Error message. If I am not allowed to mark all as read than the button should not appear,

**Environment information (please complete the following information):**
 - Browser: Firefox 89
 - FreshRSS version: 1.18.0 demo.freshrss.org

**Comment by Alkarex** [comment]
We should discuss what to do with the "mark as as read" button in anonymous mode (allow or not).
The more straightforward and consistent would be to hide the button.
