### ISSUE TITLE
Error during git checkput to edge...

### ISSUE THREAD

**Issue by quella** [FreshRSS/FreshRSS#3665]
I am currently running the v1-18-1 and over the past few days I have tried doing an update from the GUI.  Previous updates have gone via the GUI well and when a major release has been made available I use the new ZIP process in the documentation.  

Wondering if the error is related to some configuration or a git issue when trying to apply the updates.  Screenshot attached below if this is helpful.

![Screen Shot 2021-06-07 at 6 19 17 AM (2)](https://user-images.githubusercontent.com/823352/121024405-3091e900-c772-11eb-8b39-851843135e59.png)

**Comment by Alkarex** [comment]
We have changed git branch name (from `master` or `dev` to `edge`), and the automatic attempt to change branch has not worked.
Please try manually, and I am interested in seeing any error or warning you might get along the way.

Assuming `www-data` is your Web server username:

```sh
cd ./FreshRSS/
sudo -u www-data git remote -v
sudo -u www-data git fetch --prune
sudo -u www-data git checkout edge --guess -f
sudo -u www-data git reset --hard FETCH_HEAD
sudo -u www-data git branch -v
```

Please post the output.

**Comment by quella** [comment]
Thank you sir for the information.  Below is the output and I received no errors.  If you think I can try to update via the GUI after this, I'm happy to try.

OUTPUT: 
```
pi@raspberrypi:/var/www/freshrss $ sudo -u www-data git remote -v
origin	https://github.com/FreshRSS/FreshRSS.git (fetch)
origin	https://github.com/FreshRSS/FreshRSS.git (push)
pi@raspberrypi:/var/www/freshrss $ sudo -u www-data git fetch --prune
pi@raspberrypi:/var/www/freshrss $ sudo -u www-data git checkout edge --guess -f
Branch 'edge' set up to track remote branch 'edge' from 'origin'.
Switched to a new branch 'edge'
pi@raspberrypi:/var/www/freshrss $ sudo -u www-data git reset --hard FETCH_HEAD
HEAD is now at c785cdfb Release 1.18.1
pi@raspberrypi:/var/www/freshrss $ sudo -u www-data git branch -v
* edge   c785cdfb Release 1.18.1
  master c785cdfb Release 1.18.1
pi@raspberrypi:/var/www/freshrss $ 
```

**Comment by Alkarex** [comment]
Thanks for the feedback and yes, you can try again the Web update

**Comment by quella** [comment]
I seem to be getting the same error as before when I upgrade from the GUI, any other thoughts or ideas?  All is working apart from the upgrade process.  Recommend re-installing via the latest ZIP?

New Check after commands...
![Screen Shot 2021-06-07 at 10 56 16 AM (2)](https://user-images.githubusercontent.com/823352/121039919-7f924b00-c77f-11eb-8693-3a54ecb15df5.png)

**Comment by Alkarex** [comment]
No, git is the best installation. Could you please provide a few more tests?

```sh
cd ./FreshRSS/
ls -alh
git branch --show-current
```

**Comment by quella** [comment]
Thanks again for the assistance.  I could not execute "git branch --show-current" in sudo or not.  I also did not see this in the man page.  So, I did execute "git branch".  Note, I had previously installed the major updates via the ZIP method if that has any impact.  I have always used the GUI Update command for branch updates.

OUTPUT:

```sh
pi@raspberrypi:/var/www/freshrss $ ls -alh
total 356K
drwxrwxr-x 13 root     www-data 4.0K Jun  7 10:56 .
drwxr-xr-x  4 root     root     4.0K Aug 23  2020 ..
drwxrwxr-x 13 root     www-data 4.0K Mar 29 13:02 app
-rw-r--r--  1 www-data www-data 116K Jun  7 10:56 CHANGELOG.md
drwxrwxr-x  3 root     www-data 4.0K Mar 29 13:02 cli
-rw-r--r--  1 www-data www-data 6.3K Mar 17 13:41 config.default.php
-rw-r--r--  1 www-data www-data 2.7K Mar 17 13:41 config-user.default.php
-rw-r--r--  1 www-data www-data 2.7K Jun  7 10:56 constants.php
-rw-r--r--  1 www-data www-data 3.2K Mar 17 13:41 CONTRIBUTING.md
-rw-r--r--  1 www-data www-data  20K Jun  7 06:18 CREDITS.md
drwxrwxr-x  9 root     www-data 4.0K May 19 13:43 data
drwxrwxr-x  3 root     www-data 4.0K Mar 17 13:41 Docker
-rw-r--r--  1 www-data www-data   69 Mar 17 13:41 .dockerignore
drwxrwxr-x  8 root     www-data 4.0K Mar 17 13:41 docs
-rw-r--r--  1 www-data www-data  525 Mar 17 13:41 .editorconfig
drwxrwxr-x  2 root     www-data 4.0K Mar 17 13:41 extensions
-rw-r--r--  1 www-data www-data  262 Mar 17 13:41 force-https.default.txt
drwxrwxr-x  8 root     www-data 4.0K Jun  7 10:56 .git
-rw-r--r--  1 www-data www-data   58 Mar 17 13:41 .gitattributes
drwxrwxr-x  4 root     www-data 4.0K Mar 29 13:02 .github
-rw-r--r--  1 www-data www-data  166 Mar 17 13:41 .gitignore
-rw-r--r--  1 www-data www-data   93 Mar 17 13:41 .hadolint.yaml
-rw-r--r--  1 www-data www-data  308 Mar 17 13:41 index.html
-rw-r--r--  1 www-data www-data   64 Mar 17 13:41 index.php
-rw-r--r--  1 www-data www-data   85 Mar 17 13:41 .jshintignore
-rw-r--r--  1 www-data www-data   95 Mar 17 13:41 .jshintrc
drwxrwxr-x  6 root     www-data 4.0K May 16 06:26 lib
-rw-r--r--  1 www-data www-data  34K Mar 17 13:41 LICENSE.txt
-rw-r--r--  1 www-data www-data 5.1K Mar 17 13:41 Makefile
-rw-r--r--  1 www-data www-data  263 Mar 17 13:41 .markdownlint.json
-rw-r--r--  1 www-data www-data  548 Mar 17 13:41 opml.default.xml
drwxrwxr-x  6 root     www-data 4.0K Mar 17 13:41 p
-rw-r--r--  1 www-data www-data 5.1K Mar 17 13:41 phpcs.xml
-rw-r--r--  1 www-data www-data  20K Jun  6 16:01 README.fr.md
-rw-r--r--  1 www-data www-data  15K May 19 13:43 README.md
-rw-r--r--  1 www-data www-data  136 Mar 17 13:41 .stylelintignore
-rw-r--r--  1 www-data www-data 2.0K Mar 17 13:41 .stylelintrc
drwxrwxr-x  5 root     www-data 4.0K Mar 17 13:41 tests
-rw-r--r--  1 www-data www-data 2.0K Mar 17 13:41 .travis.yml

pi@raspberrypi:/var/www/freshrss $ git branch
* edge
  master

pi@raspberrypi:/var/www/freshrss $ 
```

**Comment by Alkarex** [comment]
> I could not execute "git branch --show-current" in sudo or not.

Ah, that might be the error then... I can see that it was introduced in Git 2.22 in 2019. My bad I did not spot that it was so recent.

Try:

```sh
cat /etc/issue
git --version
```

**Comment by quella** [comment]
```
pi@raspberrypi:/var/www/freshrss $ cat /etc/issue
Raspbian GNU/Linux 10 \n \l

pi@raspberrypi:/var/www/freshrss $ git --version
git version 2.20.1
pi@raspberrypi:/var/www/freshrss $ 
```

**Comment by Alkarex** [comment]
Yes, I can reproduce the problem on Raspberry Pi. I will try to provide a patch for older systems. Currently, it works with e.g. Ubuntu 20.04+, Debian 11 Bullseye.

**Comment by Frenzie** [comment]
My Debian 10 probably still has Git 2.20 (but 2.29 is available in backports).

**Comment by Alkarex** [comment]
Should be fixed. Could you please try:

```sh
cd ./FreshRSS/
sudo -u www-data git pull
```

and then try the Web update again?

**Comment by quella** [comment]
Glad I can help find a bug using the great tool, but sorry it may be extra work for you.  

Thanks for the help.  Everything is working well, just not able to update until it is corrected.  

Scott

**Comment by quella** [comment]
pi@raspberrypi:/var/www/freshrss $ sudo -u www-data git pull
remote: Enumerating objects: 31, done.
remote: Counting objects: 100% (31/31), done.
remote: Compressing objects: 100% (13/13), done.
remote: Total 31 (delta 19), reused 21 (delta 18), pack-reused 0
Unpacking objects: 100% (31/31), done.
From https://github.com/FreshRSS/FreshRSS
   32d25875..c5ca7370  edge       -> origin/edge
   c785cdfb..c5ca7370  master     -> origin/master
Updating 32d25875..c5ca7370
Fast-forward
 .travis.yml                          |  4 ++--
 CHANGELOG.md                         |  7 ++++++-
 Docker/Dockerfile-Oldest             | 11 ++++++-----
 README.fr.md                         |  4 ++--
 README.md                            |  2 +-
 app/Controllers/updateController.php |  3 ++-
 app/i18n/de/sub.php                  |  4 ++--
 constants.php                        |  4 ++--
 docs/en/admins/02_Prerequisites.md   |  6 ++----
 docs/fr/users/01_Installation.md     |  4 ++--
 10 files changed, 27 insertions(+), 22 deletions(-)

**Comment by quella** [comment]
Worked like a charm sir.  Thank you.

Running 1.19.0-dev.
