### ISSUE TITLE
I USE The docker to build FRESHRSS, How could change my time zone

### ISSUE THREAD

**Issue by Gikkingenhanaya** [FreshRSS/FreshRSS#3671]
I USE The docker to build FRESHRSS, How could change my time zone

**Comment by Alkarex** [comment]
Try to pass an environment variable to your docker run or docker-compose, like

`-e TZ=Europe/Paris`

or

```
environment:
  TZ: Europe/Paris
```

See https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md

(I will soon update the Docker documentation)
