### ISSUE TITLE
New install error

### ISSUE THREAD

**Issue by dougbrose** [FreshRSS/FreshRSS#3675]
Hi FreshRSS,

I have a working install on this same server, but when I try to create a new install with a different domain name I'm getting a 500 error and a strange error in the apache logs?

AH01071: Got error 'PHP message: PHP Fatal error: Cannot redeclare errorMessage() in /var/www/podcasts/lib/lib_rss.php on line 550', referer: https://podcasts.dslindex.com/

Thank you for any help.

**Comment by Alkarex** [comment]
Can you please tell a bit more about the procedure you use to install FreshRSS and on which system?

**Comment by math-GH** [comment]
@dougbrose I guess you issue is already solved?

**Comment by Alkarex** [comment]
This strange error was fixed in https://github.com/FreshRSS/FreshRSS/pull/4289
Same than https://github.com/FreshRSS/FreshRSS/issues/4284
