### ISSUE TITLE
[BUG] A feed could not be found at

### ISSUE THREAD

**Issue by ffuentese** [FreshRSS/FreshRSS#3686]
FreshRSS doesn't seem to detect the content type of certain feeds

**To Reproduce**
1. Go to the Add Subscription dialog
2. Add this feed https://daily.bandcamp.com/feed/ or https://daily.bandcamp.com/feed/rss.xml
3. The feed will display an error and won't get added

> A feed could not be found at `https://daily.bandcamp.com/feed/`; the status code is `200` and content-type is `` [https://daily.bandcamp.com/feed/]

**Expected behavior**

Add the blog's feed to my account and retrieve its entries.

**Screenshots**

**Environment information (please complete the following information):**

Versión
    1.19.0-dev
Performed from the web interface. 
FreshRSS is installed on a Raspberry Pi with Debian Buster.

**Comment by Frenzie** [comment]
The bug is with the feeds. They're not served correctly, as indicated by the error message.

```
HTTP/1.1 200 OK
Connection: keep-alive
Server: nginx
Set-Cookie: client_id=B92CE32F9E8CB8612A565EEA9F0DA31723F2050F0C523910EECC061863AE0AD3; domain=.bandcamp.com; path=/; expires=Sat, 05 Jul 2031 19:44:30 -0000; secure; HttpOnly; SameSite=None
Referrer-Policy: no-referrer-when-downgrade
Content-Security-Policy: base-uri 'none'; object-src 'none'; report-uri https://bandcamp.com/api/cspreport/1/violation; script-src http: https: 'nonce-eoIbgbG1RdYa/RTACusqNQ==' 'report-sample' 'strict-dynamic' 'unsafe-eval' 'unsafe-inline'
Set-Cookie: BACKENDID=red-78b9-10; path=/; Secure
Accept-Ranges: bytes
Date: Mon, 05 Jul 2021 19:44:30 GMT
Via: 1.1 varnish
X-Served-By: cache-ams21063-AMS
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1625514270.071733,VS0,VE350
transfer-encoding: chunked
```

By comparison, how it should be (`content-type: application/rss+xml`):
```
[…]
content-type: application/rss+xml; charset=UTF-8
```

But as the error message also indicates, you can force a bad feed by adding `#force_feed` to the URL.

**Comment by ffuentese** [comment]
>But as the error message also indicates,

I'm not getting that message

**Comment by Frenzie** [comment]
Not the one you quoted from the error log, but the one that told you to check the error log for more information. ^_^

**Comment by ffuentese** [comment]
I just get a pink error message with a link to go back to my log. Might that be a translation error? 
![imagen](https://user-images.githubusercontent.com/332615/124518949-e07c6580-ddb5-11eb-9146-a305bff9fcfb.png)

**Comment by Frenzie** [comment]
Indeed it is. It's probably an error introduced before we had the translation management script. That's the text from before… 1.15 or something, but don't quote me on the version. ;-) An extra sentence was added.

**Comment by math-GH** [comment]
`https://daily.bandcamp.com/feed/rss.xml#force_feed` works fine.

We can close this issue.

Some languages do not have the information about '#force_feed'. We will solve it within #3687

**Comment by mbnoimi** [comment]
Same issue occurs with me although other feed readers works fine!
```
 A feed could not be found at `https://turkiye.gov.tr/rss`; the status code is `200` and content-type is `application/xml,text/xml;charset=UTF-8` [https://turkiye.gov.tr/rss] 
 ```

**Comment by Frenzie** [comment]
`application/xml,text/xml;charset=UTF-8` is not a valid value. That should be either `application/xml; charset=UTF-8` or `text/xml; charset=UTF-8`

Anyway, adding `#force_feed` does the trick.

**Comment by math-GH** [comment]
please use https://turkiye.gov.tr/rss#force_feed

**Comment by mbnoimi** [comment]
Thank you guys @Frenzie @math-GH 
`#force_feed` did the trick
