### ISSUE TITLE
Update translation(s) for feed error message

### ISSUE THREAD

**Issue by Frenzie** [FreshRSS/FreshRSS#3687]
I'd look into it right now, but it's almost midnight.

<hr>

I just get a pink error message with a link to go back to my log. Might that be a translation error? 
![imagen](https://user-images.githubusercontent.com/332615/124518949-e07c6580-ddb5-11eb-9146-a305bff9fcfb.png)

_Originally posted by @ffuentese in https://github.com/FreshRSS/FreshRSS/issues/3686#issuecomment-874336822_

**Comment by math-GH** [comment]
I can reproduce the error message, but I do not understand the issue with the translation. For me it looks correct

![grafik](https://user-images.githubusercontent.com/1645099/144717318-84dbb6c3-467e-4094-bbeb-9dfc656c03f4.png)

I used https://daily.bandcamp.com/feed/rss.xml and the log shows
![grafik](https://user-images.githubusercontent.com/1645099/144717368-b3d74692-2433-43a8-a2bb-2098b3537dbe.png)

**Comment by math-GH** [comment]
The sentence `You can try force adding by appending <code>#force_feed</code> to the URL.` is not in every language. Also not in Spanish.
