### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Bravoboss** [FreshRSS/FreshRSS#3691]
**Describe the bug**
I got this error during installation check( raspberry pi  )

**Screenshots**
![IMG_20210710_022817.jpg](https://user-images.githubusercontent.com/68810220/125144730-7520f380-e127-11eb-80f1-ae0d20158750.jpg)

![IMG_20210710_022510.jpg](https://user-images.githubusercontent.com/68810220/125144745-7f42f200-e127-11eb-8f13-0b9306208182.jpg)

**Environment information (please complete the following information):**
 - Device: raspberry pi
 - OS: raspberry pi lite os
 - PHP version: 7.3.29
 - Installation type: Manual

**Comment by Alkarex** [comment]
Try:

```sh
cd /usr/share/FreshRSS/data/
sudo chown www-data:www-data -R .
```

**Comment by Bravoboss** [comment]
Nothing changed.
![IMG_20210711_005503.jpg](https://user-images.githubusercontent.com/68810220/125177222-a6122e80-e1e2-11eb-96c4-51a3e41713bf.jpg)
