### ISSUE TITLE
[Feature] Log failed login inside the mounted volume for a better implementation with Fail2Ban

### ISSUE THREAD

**Issue by mada199122** [FreshRSS/FreshRSS#3692]
Could you please create a log file inside the mounted container (/var/www/FreshRSS/data) with the failed login?

Using a separated log file outside the reverse proxy log is cleaner and easier to manage.

With a separate log I can create specific rules just for FreshRSS in Fail2Ban.

Thanks

**Comment by Alkarex** [comment]
Hello,
Currently, this information can already be extracted from two log sources:
* The Web server log (e.g. Apache) with lines such as `2a05:f6c7:XXX - - [10/Jul/2021:21:57:16 +0200] "POST /i/?c=auth&a=login HTTP/1.1" 403 5671` . This is the most standard way to implement fail2ban or similar protections, based on the standard HTTP 403 responses.
* The user logs in `./FreshRSS/data/users/*/log.txt` with lines such as `Password mismatch for user`

**Comment by mada199122** [comment]
@Alkarex I'm using SWAG as reverse proxy that has already Fail2ban integrated.
How can I mount the first log source to that container?

Thanks

**Comment by math-GH** [comment]
@mada199122 Is your issue already solved? Could we close this ticket?
