### ISSUE TITLE
[Feature] Proxy Per Categories

### ISSUE THREAD

**Issue by zero77** [FreshRSS/FreshRSS#3693]
**Is your feature request related to a problem? Please describe.**
Dependent on how many feeds there are, at the moment it can be very slow to add proxy support to each.

**Describe the solution you'd like**
Instead can you give the option to set a proxy for all feeds in a category.

**Describe alternatives you've considered**

**Additional context**

**Comment by aledeg** [comment]
I think that most configuration should be at the user level, the category level and the feed level. This way, it could be very flexible.
To do so, we should probably rework the whole thing to have one configuration object built with all those configuration. This way, it will be easier to deal with all the actions to do by just querying that object without thinking about where the code is and which configuration it has to use.

**Comment by zero77** [comment]
@aledeg
Is there any way to add new feeds to a category with a proxy set, using cli as then it could be scripted.

**Comment by aledeg** [comment]
Not at the moment
