### ISSUE TITLE
Error during installation check 

### ISSUE THREAD

**Issue by Bravoboss** [FreshRSS/FreshRSS#3694]
**Describe the bug**
I got this error during installation check(raspberry pi)  #3691

**Screenshots**
![IMG_20210711_005503.jpg](https://user-images.githubusercontent.com/68810220/125329379-f5687400-e334-11eb-9d5e-96088afa596a.jpg)

![IMG_20210710_022817.jpg](https://user-images.githubusercontent.com/68810220/125329404-fac5be80-e334-11eb-8600-30a486b5d7de.jpg)

**Environment information (please complete the following information):**
 - Device: raspberry pi
 - OS: raspberry pi lite os
 - PHP version: 7.3.29
 - Installation type :manual

**Comment by Frenzie** [comment]
As @Alkarex said, run `sudo chown www-data:www-data -R .` in that folder.

**Comment by Bravoboss** [comment]
> As @Alkarex said, run `sudo chown www-data:www-data -R .` in that folder.

I tried ,nothing changed.

**Comment by Frenzie** [comment]
Nothing changed how?

```
$ ls -alh
total 0
drwxr-xr-x  2 frans frans 100 Jul 12 20:20 .
drwxrwxrwt 31 root  root  860 Jul 12 20:20 ..
-rw-r--r--  1 frans frans   0 Jul 12 20:20 a
-rw-r--r--  1 frans frans   0 Jul 12 20:20 b
-rw-r--r--  1 frans frans   0 Jul 12 20:20 c
```

```
$ sudo chown www-data:www-data -R .
```

```
$ ls -alh
total 0
drwxr-xr-x  2 www-data www-data 100 Jul 12 20:20 .
drwxrwxrwt 31 root     root     860 Jul 12 20:21 ..
-rw-r--r--  1 www-data www-data   0 Jul 12 20:20 a
-rw-r--r--  1 www-data www-data   0 Jul 12 20:20 b
-rw-r--r--  1 www-data www-data   0 Jul 12 20:20 c
```

**Comment by Bravoboss** [comment]
![22](https://user-images.githubusercontent.com/68810220/125339013-6f522a80-e340-11eb-8e0d-f3724a91bd9c.png)
![11](https://user-images.githubusercontent.com/68810220/125339023-71b48480-e340-11eb-8e8d-ef9f98b24017.png)

**Comment by Frenzie** [comment]
You seem to be showing `/usr/share/FreshRSS/data` while the message is about `/var/www/etc`. Are these folders actually related?
