### ISSUE TITLE
How to insert <script> in FreshhRSS?

### ISSUE THREAD

**Issue by littabird** [FreshRSS/FreshRSS#3698]
I must insert this <script src="../wp-content/plugins/advanced-iframe/js/ai_external.js"></script> in order to achieve "autoheight" as I intend to wrap the script in an iframe in the main site.

I placed the <script> in every single index.php/html except the one in the "i" folder as this will crash the site.

However, NONE WORK as if there is something in the script blocking code from being executed  (I place a simple banner code <img> on the same files before, also nothing displayed).

**What am I missing?
Which file is the one displaying the frontpage? And how should the code be inserted?** (I asked becos it crashed if teh <script> is pasted in the index.php in the "i" folder).

Please help as I have tried asking everywhere... no one seems understand how does FreshRSS work.

**Comment by aledeg** [comment]
I think the best way would be to make an extension to handle that for you.
Check other extension to check how it is done. For instance, the Latex extension is a good example.

**Comment by littabird** [comment]
> make an extension

Thanks. But how to make an extension when I don't even know where to paste a line of <script>?

Also, xExtension-LatexSupport
-- When enabled, it will load Mathjax to render LaTeX content.
I downloaded the files... Unfortunately, couldn't even understand a single line in it... let alone doing anything on it.

Can you help to make one? Please.

**Comment by littabird** [comment]
Can someone tell me where can I find this file?

**https://github.com/FreshRSS/FreshRSS/blob/edge/app/layout/layout.phtml**

This is what I was told:-

_So if you like to add Javascript to this page I recommend you simply ask the developers of this script where to place such code. Or read their documentation. Most likely it is explained there. Maybe they have a subfolder with templates where you can add such things. If I check github https://github.com/FreshRSS/FreshRSS/blob/edge/app/layout/layout.phtml could be the right place._

**Comment by Frenzie** [comment]
That's app/layout/layout.phtml from the root. But you'll just want to copy https://framagit.org/Lapineige/FreshRSS_Extension-ReadingTime or something. Except for this one line: https://framagit.org/Lapineige/FreshRSS_Extension-ReadingTime/-/blob/29a744a8ab950f41e6f8bd3dbaa830e0ec91c189/extension.php#L4

**Comment by littabird** [comment]
Thanks Frenzie.
Unfortunately, I couldn't figure it out what to do with the two links.
Do you mind to package the extension for me (just place <script>JS link here</script> in the file)?
NB: That's app/layout/layout.phtml from the root -- I couldn't find the file phtml in my install directory. Is this the "Frontpage" in the "/i" folder?

**Comment by Alkarex** [comment]
You will find the file you ask in `./FreshRSS/app/layout/layout.phtml`
If you edit any file, make sure to check for any error/warning in your Web browser console, and in your Web browser logs.

**Comment by littabird** [comment]
Alkarex, thanks but I really couldn't find this file ./FreshRSS/app/layout/layout.phtml in my install directory???
-- Did the file changed after installed?
Not only the file, I also don't see the folder ...app/layout/... ?  What am I missing?
_NB: I think if I can locate this file, it may work as it is a "html"._

**Comment by Alkarex** [comment]
How did you install FreshRSS and on which system? Please post a screenshot of your install directory

**Comment by littabird** [comment]
> `./FreshRSS/app/layout/layout.phtml`
> any error/warning 

First my apologies, I finally found the all important "layout.phtml" ... No idea why I didn't see it before? My bad.
Second, I pasted the <script>...</script> and a banner just to see what happen? The banner loads OK but the <script> got error...
-- The script couldn't be loaded... you have something blocking the <script> from loading?

Below is the error message:-
**Failed to load resource: the server responded with a status of 404 ()**
main.js?1623002088:213 FreshRSS main init done.

I tried to place the <script> just below <body> or near the closing </body>... same.
Please advise what can I do?

**Comment by Alkarex** [comment]
Please show your exact code, and remember to provide information about your system (Web server, OS, type of installation, etc.).
A 404 is simply that the file cannot be found at that address so try first to access it directly from your Web browser.

**Comment by littabird** [comment]
> Please show your exact code, and remember to provide information about your system (Web server, OS, type of installation, etc.).

This is what I pasted in the layout.phtml: -

```
`<body class="<?= Minz_Request::actionName() ?>">`
<img class="alignnone size-medium" src="https://cdn.pixabay.com/photo/2017/06/16/22/47/tape-2410588__340.png" width="680" height="340" />
<script src=”https://bonology.com/wp-content/plugins/advanced-iframe/js/ai_external.js”></script>
```

Server? 
This one -- FastCloud Extra @ https://www.fastcomet.com/pricing (installed by cPanel/Softaculous ... Linux Server)

> A 404 is simply that the file cannot be found at that address so try first to access it directly from your Web browser.
Seems loading okay?  -- https://bonology.com/wp-content/plugins/advanced-iframe/js/ai_external.js

**Comment by Alkarex** [comment]
You have the wrong quotes in your `src` attribute it seems... `”` is not the same than `"`
Make sure to first check your Web browser logs (network tab) and Web server logs to debug such things...

**Comment by littabird** [comment]
Thanks Alkarex. Fixed teh quote and I get an even more severe error message

`Refused to load the script 'https://bonology.com/wp-content/plugins/advanced-iframe/js/ai_external.js' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'default-src' is used as a fallback.`

> Make sure to first check your Web browser logs (network tab) and Web server logs to debug such things...
No idea what's this... And I see nothing "interesting" under the Network Tab. 

Can you help me to take a look?

**Comment by Alkarex** [comment]
FreshRSS uses CSP to prevent various attacks. In your case, either you need to host the JavaScript files on the same server, or alter the CSP HTTP headers. You can read about CSP on https://developer.mozilla.org/docs/Web/HTTP/CSP

**Comment by littabird** [comment]
alter the CSP HTTP headers.   >  Can I bypass the CSP with htaccess file?
If so, please provide a sample...
If not,  host the JavaScript files > How to host this file? I imagine I
gotta script a line or two in the same layout.phtml file?
Thanks

**Comment by Alkarex** [comment]
@littabird Please search for some tutorials online; those are quite basic things.
For editing CSP, see e.g. https://github.com/FreshRSS/FreshRSS/issues/1075#issuecomment-832338116
