### ISSUE TITLE
[BUG] cURL error 6: Could not resolve host

### ISSUE THREAD

**Issue by clmbmb** [FreshRSS/FreshRSS#3699]
**Describe the bug**
Using linuxserver docker image for about a year. After the last upgrade/pull - I'm not sure what version I had before - no feed is being refreshed. Checking the logs I see the error in the description.

**To Reproduce**
1. Log in to FreshRSS instance.
2. No feeds have new articles.

**Expected behavior**
Feeds are refreshed.

**Environment information (please complete the following information):**
 - OS: Debian 10 (buster)
 - Browser: Firefox 90
 - FreshRSS version: 1.18.1
 - Database version: sqlite
 - PHP version: 7.4.21
 - Installation type: linuxserver.io docker image

**Additional context**
I know it's not the official image, but I'd like some help on how to debug the issue. All other docker containers I have - which use the same DNS server - have no problems resolving domains.

**Comment by Alkarex** [comment]
Try to exec into your container and cURL from there to be able to distinguish between a FreshRSS error and a container or host error

**Comment by Alkarex** [comment]
That image is based on Alpine, so you might have to `apk add --no-cache curl` or something like that:

```sh
docker exec -it freshrss sh
apk add --no-cache curl
curl -v 'https://example.net/feed.rss.xml'
```

**Comment by clmbmb** [comment]
Thanks for the suggestions. `curl` is already installed on the image, but something is not right with networking in there. I am able to fetch any feed on the host, but not in this container - and it worked for almost a year without issues. I will try the your image(s) to see if it will work.

**Comment by ghost** [comment]
@clmbmb I experienced this problem recently. I'm using a pihole container as my DNS server. I found I had to add the host IP address to the pihole docker port binding:
    ports:
      - 192.168.1.100:53:53/udp
      - 192.168.1.100:53:53/tcp
I don't know why my setup requires this now, but didn't before. Curl now works inside the FreshRSS container, and my feeds can update. Maybe this will help you if you're using a containerized DNS server.

**Comment by clmbmb** [comment]
@creardon90 What do you mean? My pihole container already has the ports enabled and I'm using `cap_add: NET_ADMIN`, so it should have the port open on all interfaces. Looking at `netstat -nlp` I have

    tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      -
    udp        0      0 0.0.0.0:53              0.0.0.0:*                           -

**Comment by Alkarex** [comment]
Closing at it is not related to FreshRSS, but you are welcome to continue the conversation :-)

**Comment by ghost** [comment]
@clmbmb Sure, it should work with those settings. I just found that one day it stopped working (first thing I noticed was my FreshRSS feeds wouldn't update, but then I realised none of my containers could receive from the DNS server). 
In portainer, I had just mapped the pihole ports like this:
![udp53](https://user-images.githubusercontent.com/10163890/126884873-fcd1daf7-67ce-4580-9db3-04ec6c4aea86.png)

And netstat shows:
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      -                                     
udp        0      0 0.0.0.0:53              0.0.0.0:*                           -

To get DNS to work in my containers, I had to change the pihole container configuration to this:
![udp](https://user-images.githubusercontent.com/10163890/126884897-8ac2c5f7-d2a1-46dd-bea4-846a4759bcd5.png)

Now netstat shows:
tcp        0      0 192.168.1.100:53        0.0.0.0:*               LISTEN      -                                      
udp        0      0 192.168.1.100:53        0.0.0.0:*                           -

And DNS is working again. I don't know what changed in my environment to require those configuration changes. I may have upgraded docker. Maybe this is unrelated to your problem, but it's worth a try.

**Comment by clmbmb** [comment]
@creardon90 WOW! Thanks a lot! I have it working now. Thanks @Alkarex for letting the discussion continue.
