### ISSUE TITLE
[Feature] Search for one or more labels in a query

### ISSUE THREAD

**Issue by ko** [FreshRSS/FreshRSS#3704]
**Is your feature request related to a problem? Please describe.**
As a user who applies granular labels on articles for easier future lookup, I would like to create user query filters or search for multiple labels at once. An example is the below screenshot where I would create tags for 2 entities, separately:

![image](https://user-images.githubusercontent.com/142929/126574241-675ad3ad-a941-4694-b40e-bd3c479a7bb1.png)

But I want to later lookup articles that contain both entities or tags. I am not aware of how to search for labels in the search bar, however. 

![image](https://user-images.githubusercontent.com/142929/126574341-70b2734a-228a-42a9-a9cc-5d42a09c655a.png)

![image](https://user-images.githubusercontent.com/142929/126574354-5f905e9e-fb3f-4992-bd4d-946d439f52d2.png)

I am also unable to select more than one label from the feed list, where the labels reside:

![image](https://user-images.githubusercontent.com/142929/126574426-d80d8c7e-2398-4245-9301-6d598abcfe71.png)

I look at tags as the closest analogy, where multiple tags in a single search query are supported. 

![image](https://user-images.githubusercontent.com/142929/126574074-b015f3bc-13c5-4b42-9e2e-b91e9ad9aa4b.png)

**Describe the solution you'd like**
I'd like to be able to create search queries and user queries where multiple labels are selected. This would allow me to create user query filters, or simply perform ad-hoc searches in the future.

**Describe alternatives you've considered**

I am currently creating tags for combinations of tags. In this example, that would be a tag named `aaa_entity_foo + aaa_entity_bar`, but this is not a scalable solution.

**Additional context**
I am hoping this is simply user error.

**Comment by Alkarex** [comment]
@ko Please test this patch https://github.com/FreshRSS/FreshRSS/pull/3709
