### ISSUE TITLE
[BUG] login screen: UI changed after finding out an account

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#3706]
I am not sure if it could be a security issue (but is not urgent).

the default user uses the default template.
![grafik](https://user-images.githubusercontent.com/1645099/126634379-577c1e07-99bf-4765-9a3b-54b8e1a0f6a3.png)

If the username is correct but the password is incorrect than the theme of this user is used for the login screen:
![grafik](https://user-images.githubusercontent.com/1645099/126634520-6ce73150-7400-4a5f-9c6f-7fd35a1e64c1.png)

So it is a clear sign that you find out a valid user name. Now you need "just" to try out the password.

**To Reproduce**
1. Go to login screen
2. try out an random username and a random password: the UI will not change after submitting
3. use a valid username (this user does not use the default thema) and a random password: after submitting the UI will change to the user's theme

**Expected behavior**
keep the default UI

**Environment information (please complete the following information):**
 - Browser: Firefox 90
 - FreshRSS version: 1.18.1

**Comment by aledeg** [comment]
It related to #3057
