### ISSUE TITLE
[This url is not correct]

### ISSUE THREAD

**Issue by Bravoboss** [FreshRSS/FreshRSS#3708]
**Describe the bug**
All other readers worked except freshrss reader, i don't know why ,always tell me this url is not correct .
Thank you 

**Screenshots**
![IMG_20210722_180845.jpg](https://user-images.githubusercontent.com/68810220/126662782-98ce8322-9d57-44a8-993b-8bab44aebc5a.jpg)

**Environment information (please complete the following information):**
 - Device:android
 - OS: 11
 - Installation type: Manuel 
**Additional context**

**Comment by Frenzie** [comment]
Are you referring to <https://git.feneas.org/christophehenry/freshrss-android/-/issues>? If so, report it there. ;-)
