### ISSUE TITLE
[BUG] Browser's default margin around <figure>

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#3732]
The browser's default margin around <figure> (yellow)
![grafik](https://user-images.githubusercontent.com/1645099/127394041-e6c56614-be9d-4109-91a4-71c8acd29a68.png)

would it make sense to set the margin to 0px?
![grafik](https://user-images.githubusercontent.com/1645099/127395283-78dc295b-a3ea-4219-b1d5-87add6325a23.png)

In origine.css or base-theme/template.css? Or should we leave it as it is (use the browser default) and set it via custom css?

**Environment information (please complete the following information):**
 - Browser: Firefox 90 + Microsoft Edge
 - FreshRSS version: 1.18.1

**Comment by Frenzie** [comment]
On the smallest sizes maybe, otherwise seems fine to me.
