### ISSUE TITLE
[BUG] Origine line-height with units

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#3733]
@Frenzie does not like the line-height with units (see: https://github.com/FreshRSS/FreshRSS/pull/3731#discussion_r678652289)

![grafik](https://user-images.githubusercontent.com/1645099/127398508-b58c91b8-4e7c-4206-ba73-6d0dfd89628f.png)

Why it would make sense: https://css-tricks.com/almanac/properties/l/line-height/#unitless-line-heights

**Expected behavior**
no units

**Environment information (please complete the following information):**
 - FreshRSS version: 1.18.1

**Comment by Frenzie** [comment]
To illustrate the problem:

```html
<!DOCTYPE html>
<style>
div {
	font-size: x-small;
	line-height: 2em;
}
p {font-size: 2rem}
.proper {
	line-height: 2;
}
</style>
<div>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
	<p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>
</div>
<div class="proper">"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
	<p>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>
</div>
```

![Screenshot_2021-07-29 Screenshot](https://user-images.githubusercontent.com/202757/127463891-2cdeedcf-593d-4a4f-8408-a294b91af38a.png)

As you can see 2 and 2em are identical for the intended target, but it blows up for descending elements, even if in practice usually less dramatically. In fact it's very well possible that most of the line-height declarations above only needed declaring in the first place because of this mistake.

**Comment by math-GH** [comment]
Are there differences between `line-height: 2` and `line-height: 200%`?

**Comment by Frenzie** [comment]
Yes, 200% is the same as 2em. That's what causes the problem above. If 200% is 60px, it's *always* 60px. It's a one time declaration of the value, it doesn't become "200%" for children. For children it's whatever 200% turned out to be.

**Comment by math-GH** [comment]
I see that the base-theme has the same issue, that line-height has `em` or `px` :/
