### ISSUE TITLE
[Feature] Support for Raspberry Pi 

### ISSUE THREAD

**Issue by vorant94** [FreshRSS/FreshRSS#3734]
**Is your feature request related to a problem? Please describe.**
Hi, there. I ran FreshRSS on my cloud VPS for a couple of months and everything worked fine. After some time I decided to buy Raspberry Pi and move all my cloud self-hosted services there. I had some issues even with PostgreSQL but found [a solution](https://blog.samcater.com/fix-workaround-rpi4-docker-libseccomp2-docker-20/) that fixed that issue. Regardless of it FreshRSS app still can't start (I am running it in a container, `docker-compose.yml` is taken from [here](https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/docker-compose.yml) without additional proxies or other stuff)...
```
CONTAINER ID   IMAGE                       COMMAND                  CREATED          STATUS                         PORTS                                                                            NAMES
33ab4f55a320   freshrss/freshrss:latest    "./Docker/entrypoint…"   25 seconds ago   Restarting (1) 6 seconds ago                                                                                    freshrss-app
f5dafa34d425   postgres:12-alpine          "docker-entrypoint.s…"   27 seconds ago   Up 25 seconds                  0.0.0.0:5432->5432/tcp                                                           freshrss-db
```

Here are logs of FreshRSS app:
```
Attaching to freshrss-app
freshrss-app    | standard_init_linux.go:219: exec user process caused: exec format error
freshrss-app    | standard_init_linux.go:219: exec user process caused: exec format error
freshrss-app    | standard_init_linux.go:219: exec user process caused: exec format error
freshrss-app    | standard_init_linux.go:219: exec user process caused: exec format error
freshrss-app    | standard_init_linux.go:219: exec user process caused: exec format error
freshrss-app    | standard_init_linux.go:219: exec user process caused: exec format error
freshrss-app    | standard_init_linux.go:219: exec user process caused: exec format error
```

**Describe the solution you'd like**
It would be nice to have FreshRSS app able to run on Raspberry Pi since it is common platform for serving different services at home.

**Additional context**
Since I'm pretty sure it is not problem with FreshRSS app itself, but some underlying stuff with linux and so on (which I'm not so familiar with) I considered this GitHub issue to be a feature request and not bug. In the end it would be useful to have the solution written in the documentation. So it is like cry for a help plus documentation feature request😅

**Comment by Frenzie** [comment]
You should use `:latest-arm` as detailed [here](https://github.com/FreshRSS/FreshRSS/tree/c1eb260f4491d5b550383ed705f23ac41cafdefa/Docker), not `:latest`.

**Comment by vorant94** [comment]
sorry, my bad. thanks)
