### ISSUE TITLE
[BUG] greader.php : HTTP error 500 because trying to write in a wrong file

### ISSUE THREAD

**Issue by Massedil** [FreshRSS/FreshRSS#3735]
Just trying this call without an alice user result in a HTTP error 500 :
https://freshrss.example.net/api/greader.php/accounts/ClientLogin?Email=alice&Passwd=Abcdef123456

It looks like the user existence is not well checked before doing some logging in the user data folder.

```
Got error 'PHP message: PHP Warning:  file_put_contents(FreshRSS/data/users/alice/log.txt): failed to open stream: No such file or directory in FreshRSS/lib/Minz/Log.php on line 70PHP message: PHP Fatal error:  Uncaught Minz_PermissionDeniedException: Permission is denied for `FreshRSS/data/users/alice/log.txt` in FreshRSS/lib/Minz/Log.php:71\nStack trace:\n#0 FreshRSS/lib/Minz/Log.php(132): Minz_Log::record('Password API mi...', 4, '/var/www/feed.m...')\n#1 FreshRSS/p/api/greader.php(197): Minz_Log::warning('Password API mi...')\n#2 FreshRSS/p/api/greader.php(987): clientLogin('alice', 'Abcdef123456')\n#3 {main}\n  thrown in FreshRSS/lib/Minz/Log.php on line 71'
```

**Comment by Alkarex** [comment]
@Massedil Could you please try this patch? https://github.com/FreshRSS/FreshRSS/pull/3751
In addition to the API, we need to double-check the Web Form login, the CLI, the FreshRSS install process, and creating a new user.

**Comment by Massedil** [comment]
I don't have an access to a computer now (and may be not until some days) to try your patch on my server. I inform you as soon as I can try. Thanks.
