### ISSUE TITLE
[BUG] greader.php : Allowed memory size exhausted (HTTP error 500)

### ISSUE THREAD

**Issue by Massedil** [FreshRSS/FreshRSS#3736]
I try to use a mobile app for reading my FreshRSS articles.

Here HTTP logs with Readrops from F-droid :

```
"GET /api/greader.php/reader/api/0/tag/list?output=json HTTP/1.1" 200 7852 "-" "okhttp/4.9.1"
"GET /api/greader.php/reader/api/0/subscription/list?output=json HTTP/1.1" 200 151146 "-" "okhttp/4.9.1"
"GET /api/greader.php/reader/api/0/stream/contents/user/-/state/com.google/reading-list?xt=user%2F-%2Fstate%2Fcom.google%2Fread&xt=user%2F-%2Fstate%2Fcom.google%2Fstarred&n=5000 HTTP/1.1" 500 240 "-" "okhttp/4.9.1"
```

Detail of the HTTP error 500 :

```
Got error 'PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 39280640 bytes) in FreshRSS/p/api/greader.php on line 707'
```

It seems that it is the json_encode function which fails : 
https://github.com/FreshRSS/FreshRSS/blob/master/p/api/greader.php#L707

What can I do to solve this ?

**Comment by Frenzie** [comment]
Either make the app not ask for so many things all at once,[1] or increase the memory limit.

[1] Cf. https://github.com/FreshRSS/FreshRSS/issues/2566#issuecomment-541317776

**Comment by Massedil** [comment]
Thanks !
