### ISSUE TITLE
[BUG] Update via API not occuring, invalid API authorisation for user

### ISSUE THREAD

**Issue by shedtepherd** [FreshRSS/FreshRSS#3738]
**Describe the bug**
I am unable to update my feeds using Reeder 4 on iOS. The automated cron job and manual update button on the website function, but updating via API does not. I am able to log in using my username and API password, pull down feeds that are already in the db, and favorite articles on the mobile device. I am seeing "Invalid API authorisation for user" in that users log.txt file.

**To Reproduce**
1. Log into Reeder 4
2. Log into FreshRSS account using username and API password
3. Pull down to update feeds

**Expected behavior**
I expect FreshRSS to check feeds for new articles at that moment.

**Environment information (please complete the following information):**
 - Device: iPhone 8
 - OS: Ubuntu 20.04
 - Browser: Firefox 90.0.2
 - FreshRSS version: 1.19.0-dev (although I git cloned the master branch, I don't know why it is showing the edge branch)
 - Database version: sqlite (I don't know the version, it is what ever version comes with FreshRSS, as I did not install a db)
 - PHP version: PHP 7.4.3
 - Installation type: VPS, following instructions from the FreshRSS documentation, updating commands for newer version of OS

**Additional context**

FreshRSS API endpoints
Google Reader compatible API

Your API address:
    https://[REDACTED]/api/greader.php
Google Reader API configuration test:
    ✔️ PASS

Fever compatible API

Your API address:
    https://[REDACTED]/api/fever.php
Fever API configuration test:
    ✔️ PASS 

```
tail /usr/share/FreshRSS/data/users/ted/log.txt
[Fri, 30 Jul 2021 05:07:05 +0000] [warning] --- Invalid API authorisation for user ted: 958a0e3c988aee293ecad9db7a3290c5cd3b0763
[Fri, 30 Jul 2021 05:08:19 +0000] [warning] --- Invalid API authorisation for user ted: 958a0e3c988aee293ecad9db7a3290c5cd3b0763
[Fri, 30 Jul 2021 05:08:34 +0000] [warning] --- Invalid API authorisation for user ted: 958a0e3c988aee293ecad9db7a3290c5cd3b0763
[Fri, 30 Jul 2021 05:14:34 +0000] [warning] --- Invalid API authorisation for user ted: b00777b2eebd64cfe6d31a0e86bfac727676e214
[Fri, 30 Jul 2021 05:27:54 +0000] [warning] --- Invalid API authorisation for user ted: e108ad417d3b6eb3cdc238f954a0eb9135e47ef7
```

```
root@freshrss:~# curl 'https://[REDACTED]/api/greader.php/accounts/ClientLogin?Email=ted&Passwd=[REDACTED]'
SID=ted/8c8dd1b2e9151fb74ca92408871e4489038aeafb
LSID=null
Auth=ted/8c8dd1b2e9151fb74ca92408871e4489038aeafb
root@freshrss:~# curl -v -H "Authorization:GoogleLogin auth=ted/8c8dd1b2e9151fb74ca92408871e4489038aeafb" 'https://[REDACTED]/api/greader.php/reader/api/0/user-info?output=json'
*   Trying 147.182.201.112:443...
* TCP_NODELAY set
* Connected to [REDACTED] ([REDACTED]) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: CN=[REDACTED]
*  start date: Jul 30 00:41:21 2021 GMT
*  expire date: Oct 28 00:41:19 2021 GMT
*  subjectAltName: host "[REDACTED]" matched cert's "[REDACTED]"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
> GET /api/greader.php/reader/api/0/user-info?output=json HTTP/1.1
> Host: [REDACTED]
> User-Agent: curl/7.68.0
> Accept: */*
> Authorization:GoogleLogin auth=ted/8c8dd1b2e9151fb74ca92408871e4489038aeafb
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Fri, 30 Jul 2021 15:15:34 GMT
< Server: Apache/2.4.41 (Ubuntu)
< Vary: Accept-Encoding
< Content-Length: 70
< Content-Type: text/html; charset=UTF-8
<
* Connection #0 to host [REDACTED] left intact
{"userId":"ted","userName":"ted","userProfileId":"ted","userEmail":""}
```

**Comment by Alkarex** [comment]
Hello,
At the moment, our GReader API does not support refreshing articles, but we could add this feature, if we can document which calls are made by clients. Could you check your logs in `data/users/_/log_api.txt` and try to find a section corresponding to that call?

**Comment by shedtepherd** [comment]
> 
> 
> Hello,
> At the moment, our GReader API does not support refreshing articles, but we could add this feature, if we can document which calls are made by clients. Could you check your logs in `data/users/_/log_api.txt` and try to find a section corresponding to that call?

The following is a section of the log_api.txt files that cooresponds to Reeder 4 making an API call to refresh articles.

```
[Fri, 30 Jul 2021 05:27:54 +0000] [warning] --- Invalid API authorisation for user ted: e108ad417d3b6eb3cdc238f954a0eb9135e47ef7
[Fri, 30 Jul 2021 05:27:54 +0000] [warning] --- unauthorized() Array
(
    [date] => 2021-07-30T05:27:54+00:00
    [headers] => Array
        (
            [Host] => [REDACTED]
            [Connection] => keep-alive
            [Accept] => */*
            [User-Agent] => Reeder/4020.89.01 CFNetwork/1240.0.4 Darwin/20.5.0
            [Accept-Language] => en-us
            [Authorization] => GoogleLogin auth=ted/e108ad417d3b6eb3cdc238f954a0eb9135e47ef7
            [Accept-Encoding] => gzip, deflate, br
        )

    [_SERVER] => Array
        (
            [HTTP_AUTHORIZATION] => GoogleLogin auth=ted/e108ad417d3b6eb3cdc238f954a0eb9135e47ef7
            [HTTPS] => on
            [SSL_TLS_SNI] => [REDACTED]
            [HTTP_HOST] => [REDACTED]
            [HTTP_CONNECTION] => keep-alive
            [HTTP_ACCEPT] => */*
            [HTTP_USER_AGENT] => Reeder/4020.89.01 CFNetwork/1240.0.4 Darwin/20.5.0
            [HTTP_ACCEPT_LANGUAGE] => en-us
            [HTTP_ACCEPT_ENCODING] => gzip, deflate, br
            [PATH] => /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
            [SERVER_SIGNATURE] => <address>Apache/2.4.41 (Ubuntu) Server at [REDACTED] Port 443</address>

            [SERVER_SOFTWARE] => Apache/2.4.41 (Ubuntu)
            [SERVER_NAME] => [REDACTED]
            [SERVER_ADDR] => [REDACTED]
            [SERVER_PORT] => 443
            [REMOTE_ADDR] => [REDACTED]
            [DOCUMENT_ROOT] => /var/www/html/p
            [REQUEST_SCHEME] => https
            [CONTEXT_PREFIX] =>
            [CONTEXT_DOCUMENT_ROOT] => /var/www/html/p
            [SERVER_ADMIN] => [no address given]
            [SCRIPT_FILENAME] => /var/www/html/p/api/greader.php
            [REMOTE_PORT] => 56005
            [GATEWAY_INTERFACE] => CGI/1.1
            [SERVER_PROTOCOL] => HTTP/1.1
            [REQUEST_METHOD] => GET
            [QUERY_STRING] => output=json
            [REQUEST_URI] => /api/greader.php/reader/api/0/subscription/list?output=json
            [SCRIPT_NAME] => /api/greader.php
            [PATH_INFO] => /reader/api/0/subscription/list
            [PATH_TRANSLATED] => /var/www/html/p/reader/api/0/subscription/list
            [PHP_SELF] => /api/greader.php/reader/api/0/subscription/list
            [REQUEST_TIME_FLOAT] => 1627622874.927
            [REQUEST_TIME] => 1627622874
        )

    [_GET] => Array
        (
            [output] => json
        )

    [_POST] => Array
        (
        )

    [_COOKIE] => Array
        (
        )

    [INPUT] =>
)
```

Thank you

**Comment by shedtepherd** [comment]
I understand that this is not in the scope of the project at the time. I'll close this issue out.

**Comment by Alkarex** [comment]
Sorry for not answering your previous message. For the record, the log shows a call for retrieving the list of feeds (`/reader/api/0/subscription/list?output=json`) and not for refreshing the feeds. If any clients implements an explicit feed refresh call, I will be happy to add support for it

**Comment by shedtepherd** [comment]
@Alkarex 

> Sorry for not answering your previous message. For the record, the log shows a call for retrieving the list of feeds (`/reader/api/0/subscription/list?output=json`) and not for refreshing the feeds. If any clients implements an explicit feed refresh call, I will be happy to add support for it

Thank you for clarifying. When I opened this ticket I was super new to FreshRSS and didn't realize that this was an issue on the application side. I will reach out to the application developer to see if this is something they can implement in their application.

Thank you for your time and work on FreshRSS.
