### ISSUE TITLE
Update Continuous Integration

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#3744]
[Travis](https://travis-ci.org) have changed their terms of service and the current CI pipeline does not work.
We need to move to https://travis-ci.com and/or perform (some of) the tests thanks to [GitHub Actions](https://github.com/FreshRSS/FreshRSS/actions)

**Comment by math-GH** [comment]
I would say that this topic is already solved, isn't it @Alkarex ?

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/3920
