### ISSUE TITLE
[Feature] Find inactive feed? (To find feed and pages that have not published new articles for a long time)

### ISSUE THREAD

**Issue by killerkarnickel404** [FreshRSS/FreshRSS#3750]
It would be great if there would be a function to find feed corpses. 

I mean websites that you have subscribed to but haven't published any new articles for xx Months.

Or is there already a solution for this that I have overlooked.

**Comment by aledeg** [comment]
You can find those in the statistics page. There is an "idle feed" entry in the menu.

**Comment by killerkarnickel404** [comment]
> 
> 
> You can find those in the statistics page. There is an "idle feed" entry in the menu.

Perfect thanks, that's exactly what I was looking for.
