### ISSUE TITLE
[BUG] demo.freshrss.org 502 Bad Gateway

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#3757]
![grafik](https://user-images.githubusercontent.com/1645099/128906120-bab84dbf-3cf6-4e25-947e-cadac7b77c2f.png)

**Expected behavior**
see the demo app

**Comment by math-GH** [comment]
If someone is interested in a demo app: see https://github.com/FreshRSS/FreshRSS/discussions/3770

**Comment by Alkarex** [comment]
Ping @marienfressinaud ;-)

**Comment by marienfressinaud** [comment]
Thanks for the heads up! It's now up and running and I monitor the domain :)
