### ISSUE TITLE
[Feature] Add Youtube channel /user in the title 

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#3773]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'm following few channels on Youtube and channel / user isn't inclueded in the feed. It's hard to know.

**Describe alternatives you've considered**
Clic & discover

**Additional context**
![image](https://user-images.githubusercontent.com/206181/129606203-75c3da50-b7d3-4dc4-8200-5aa2e633f609.png)

**Comment by Alkarex** [comment]
Hello,
Is that with a Youtube extension?

**Comment by ghost** [comment]
Hey,
No I don't use Youtube extension. Just custom CSS and Custom JS.

**Comment by math-GH** [comment]
Wow, I like that theme. Could you share your CSS and JS (f.e. within a GIST)?

**Comment by Alkarex** [comment]
I cannot reproduce the problem.
* Do you have the same problem with other feeds, or only YouTube?
* Could you try with another theme?
* Could you share a minimal OPML export?

**Comment by ghost** [comment]
> 
> 
> I cannot reproduce the problem.
> 
>     * Do you have the same problem with other feeds, or only YouTube?
> 
>     * Could you try with another theme?
> 
>     * Could you share a minimal OPML export?

Oh, I remember I did this in custom CSS :
`li.item.website  span {
display: none !important;
}`
Sorry, I'll try to found another solution to display user channel

**Comment by ghost** [comment]
> 
> 
> Wow, I like that theme. Could you share your CSS and JS (f.e. within a GIST)?

Mostly CSS, I use JS only to open in new tab instead of inline : https://gist.github.com/Zazou89/ef0bb3038047760bc781adbed4361c3b

**Comment by math-GH** [comment]
> Mostly CSS, I use JS only to open in new tab instead of inline : https://gist.github.com/Zazou89/ef0bb3038047760bc781adbed4361c3b

Which theme do you use? With Origine it does not match 100%

**Comment by ghost** [comment]
Mapco

**Comment by Alkarex** [comment]
Pull request for theme welcome

**Comment by i-iooi-i** [comment]
Very beautiful, hope to have a real theme

**Comment by math-GH** [comment]
@ghost / @Zazou89 (it is a deleted user right now):
You can enable the author in the top line (see settings: display. Top line). It will add the author's name next to the title.
Another solution could be to change the name of the feed.

But the user is now not active anymore here on GitHub I would suggest to close this ticket. Unfortunately the gist with his beautiful theme is also gone
