### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by satheeshsoft** [FreshRSS/FreshRSS#3775]
****Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment information (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04]
 - Browser: [e.g. Firefox 86]
 - FreshRSS version: [e.g. 1.17.1]
 - Database version: [e.g. Mysql 5.7]
 - PHP version: [e.g. PHP 7.4]
 - Installation type: [e.g. Yunohost]

**Additional context**

Hi,
     My name is Satheesh. My website is https://softcleaner.in its a software related website. Its using cPanel (i think linux). Through cPanel i use wordpress. Today 18-8-2021 i install your RSS feed from wordpress. After installing i gone to my website main page ie https://softcleaner.in. The whole contents in the main page as well as other pages too gone/not showing. (pages are available on the wordpress but not visible now). 

The main page is showing rss feed login page instead of my description there. 
So i though to uninstall the FreshRSS and clicked to uninstall. It shown some directory also needed to delete fore ever.  I feared and unchecked those directories and done uninstall. It uninstalled.

Then also the webpages are not showing anything.

So i thought to again re-install and uninstall those directories as per your software saying. Again installed and uninstalled without unchecking those directories during the uninstall time.

Now also same nothing is showing in the webpages. 
What can i do?
Regards,
Satheesh 
My website was working properly before.
**

**Comment by math-GH** [comment]
Could you please:

- use the Bug template and fill out the imporant sections?
- summarize your issue within some words and write it in the title
- make clear what you mean with "i install your RSS feed from wordpress"? Which RSS feed (link)?
- add to your text some screenshots

Are you sure, that you want publish your email address?

**Comment by Frenzie** [comment]
Whoops, forgot to edit out the email here. See https://github.com/FreshRSS/FreshRSS/discussions/3778 for discussion.

**Comment by satheeshsoft** [comment]
Screenshots? and now? 
If you seen the webpage on the day i written here, you could have seen the entire website down only showing your login page. During these days we are restoring the entire directories. I have paid too for this. Also wordpress too now cannot working or i can't login. Before FreshRSS install, it was working fine without any issues. I do not complain but you have to modify your app. I thought if i get the remedy on that day or next day it was somewhat successful. Publishing email address is the job of email provider you can ask.
Thanks

**Comment by Frenzie** [comment]
There's nothing to modify on this end. We cannot prevent someone from overwriting their files with our files. We are not cPanel.
