### ISSUE TITLE
[BUG] Importing generated OPML as per documentation leaves the title empty

### ISSUE THREAD

**Issue by tonyrulez** [FreshRSS/FreshRSS#3776]
**Describe the bug**
When creating an OPML from URLs with a [generator](https://opml-gen.ovh/) listed in the [documentation](https://freshrss.github.io/FreshRSS/en/users/04_Subscriptions.html), the title of these imported feeds are empty. I can't automatically update the titles, and since it doesn't have a title, I can't even click to select a feed (since the title is what should be clicked)
Happened when I tried to import my Youtube subscriptions.

**To Reproduce**
1. Get a list of Youtube channel URLs
2. Generate OPML with [opml-gen.ovh](https://opml-gen.ovh/)
3. Import the OPML to FreshRSS

**Expected behavior**
If no title is present in the OPML, automatically fetch the title. If I manually add these URLs, the title appears instantly. However adding 100+ feed manually is tiresome and a lot of time.

**Screenshots**
![kép](https://user-images.githubusercontent.com/27233005/129887655-66d474d0-8988-4766-b973-9147ac77cc19.png)

**Environment information (please complete the following information):**
 - Device: PC
 - OS: Windows 10
 - Browser: Firefox 91
 - FreshRSS version: 1.18.1
 - PHP version: PHP 7.4
 - Installation type: Ubuntu Server

**Comment by Alkarex** [comment]
Could you please paste here an example of generated OPML?

**Comment by tonyrulez** [comment]
Sample OPML output by opml-gen.ovh: [https://pastebin.com/m1cQtuQp](https://pastebin.com/m1cQtuQp)

**Comment by Alkarex** [comment]
```xml
<outline xmlUrl='https://www.youtube.com/user/112PressNA' />
```

**Comment by Alkarex** [comment]
@tonyrulez https://github.com/FreshRSS/FreshRSS/pull/3787 should already provide a minimal fix for existing feeds with blank titles

**Comment by Alkarex** [comment]
Ah, right, the URLs are not pointing to valid feeds, so the titles cannot be retrieved.
Otherwise, it was already fixed by https://github.com/FreshRSS/FreshRSS/pull/3071 / https://github.com/FreshRSS/FreshRSS/issues/3067
