### ISSUE TITLE
How to improve cookie handling for Cloudflare?

### ISSUE THREAD

**Issue by robotfx** [FreshRSS/FreshRSS#3779]
Hi,

I'm trying to optimize the site as good as I can and right now I have 2 issues:
1. I'd like to get rid of the FreshRSS cookie that is set for each browser session, but I cannot find how. This will be useful for me to get the pages cached by Cloudflare, which otherwise does not cache pages that set cookies. Where to look, what lines to modify/delete? Thx
2. Still about optimizing, I have set the following code on top of the /p/index.php, because I want the server to push the static files on the first visit:
```
    if (isset($_COOKIE['1st_time_visitor'])) {
    } else {
header("Link: </main.css>; as=style; rel=preload", false);
header("Link: </scripts/main.js>; as=script; rel=preload", false);
header("Link: </actualitate.webp>; rel=preload; as=image", false);
setcookie( "1st_time_visitor", 1, strtotime( '+1 year' ) );
//        echo '1st time';
    }
```
The cookie part works, but the push part does not. In the Chrome dev panel, the static files are initiated by the page itself. If the http2 push would work (a I can see on my other sites, using the same code), the Chrome dev's Initiator (Network) should display 'Other', not the page address. What is wrong with it?

Thanks for this great script

**Comment by math-GH** [comment]
Could you please optimize the headline of this issue report? 
f.e.: "Improve Cookie handling for Cloudflare"

It could help to have a better overview in the issue link

**Comment by Frenzie** [comment]
Isn't that a Cloudflare setting to ignore and/or cache specific cookies? I.e., bypass cache for `FreshRSS_login`, cache for `FreshRSS`.

**Comment by math-GH** [comment]
Is here any progress? Or how can we help?
