### ISSUE TITLE
Support filtering by category (Native RSS tag)

### ISSUE THREAD

**Issue by ninboy** [FreshRSS/FreshRSS#3788]
RSS feeds have a `<category>` tag, which I can't find in the documentation for searching: https://freshrss.github.io/FreshRSS/en/users/03_Main_view.html#with-the-search-field

There are specific filters for titles, authors, url, dates and others, but a `category` option is missing. Also, it seems not supported in the code either: https://github.com/FreshRSS/FreshRSS/blob/edge/app/Models/Entry.php#L231

As an example, take this feed from TechCrunch: https://techcrunch.com/feed/

Each item's has categories (`<category><![CDATA[Venture Capital]]></category>`) that can´t be filtered by. When adding this feed to FreshRSS, the categories exported are still there.

Would it be possible to add this new filter?

**Comment by Alkarex** [comment]
Hello,
Categories are what is called *tag* in FreshRSS.

![image](https://user-images.githubusercontent.com/1008324/130295372-ac070946-8294-4cb5-a47c-bc2469dbb0e3.png)

--

![image](https://user-images.githubusercontent.com/1008324/130295266-4582f9f6-4090-4d5b-b455-dabf77608966.png)

**Comment by ninboy** [comment]
Thank you so much @Alkarex !
