### ISSUE TITLE
[Feature] Image caching

### ISSUE THREAD

**Issue by hrehfeld** [FreshRSS/FreshRSS#3798]
- I follow a bunch of twitter accounts via nitter. Nitter instances are often rate limited by the twitter api after a certain time, so they might not be "up" when I read the rss posts. So all images in the posts (and I follow photography/art/design mainly) are missing. 
- Archived posts with images where the original site is removed also have missing images.

Is it possible to cache linked images (or media up to a size?) in the db so that they  are fetched when the rss is up and I can see them when I look at the archive?

**Comment by Frenzie** [comment]
If you use [the image proxy extension](https://github.com/FreshRSS/Extensions/tree/master/xExtension-ImageProxy) you can see some examples to set up your own. It wouldn't be in the DB but it would be on your own server.

**Comment by hrehfeld** [comment]
Thanks for your quick response! 

However, can you explain? I don't see how that solves the problems of:

- put images into the db when FressRSS is accessing the feed initially (when I view the feed the next time, images are already "down")
- still requires a separate (indefinitely) caching proxy

**Comment by Frenzie** [comment]
I'm afraid you'd have to take it as a starting point — well, you don't have to, of course, but something like [this](https://github.com/FreshRSS/Extensions/blob/210b867bbf5f5b164fcb727b3b63c5342e1cb252/xExtension-ImageProxy/extension.php#L116-L126) would have to be part of the code either way.

> still requires a separate (indefinitely) caching proxy

It solves the problem of this is what you can set up in a couple of minutes. ;-) Also my instinct would go against storing a lot of such data in a DB regardless but I could be wrong about that.

**Comment by math-GH** [comment]
could we link this issue https://github.com/FreshRSS/FreshRSS/issues/2850 ?

**Comment by hrehfeld** [comment]
Oh, sorry for the duplicate, I didn't find that when I checked the issues. The other issue needs the word "image" somewhere, I guess.

27 Aug 2021 13:32:37 maTh ***@***.***>:

**Comment by math-GH** [comment]
> 
> Oh, sorry for the duplicate, I didn't find that when I checked the issues. The other issue needs the word "image" somewhere, I guess. 

Don't mind. it is just a link, so that both issues are now connected eachother.

**Comment by xmt328** [comment]
Image Proxy will only cache when actively visiting, but I want to cache images when RSS is fetching
According to the information on the Internet, the algorithm of TTRSS is to map the image url to the local cache after sha1 hashing.

**Comment by Alkarex** [comment]
See https://github.com/FreshRSS/Extensions/pull/139
