### ISSUE TITLE
[BUG] Remove information about old Firefox RSS function

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#3820]
I would suggest to remove this section

![grafik](https://user-images.githubusercontent.com/1645099/131739856-ab76f4d0-0034-47cb-add5-183d4a0f740a.png)

Firefox 63 was published 3 years ago (October 2018).
Firefox 64 was published some weeks later in December 2018.

Firefox 91 is the newest today.

Also the Firefox ESR:
Firefox 91 ESR is today the newest.
Previous: Firefox 78 ESR had also the RSS not included anymore.

I do not see any reason to keep this information in FreshRSS.

**Comment by Frenzie** [comment]
Yes, that's fine now.
