### ISSUE TITLE
refresh interval for multiple feed customize or for whole category possible?

### ISSUE THREAD

**Issue by killerkarnickel404** [FreshRSS/FreshRSS#3829]
Hello,

I have a lot of YouTube Channels feeds in FreshRSS. 
For a few weeks I have the problem that Google blocks my IP address again and again temporarily. 

I refresh the feeds every 20 minutes. 

Now I would like to increase the refresh interval for all YouTube feeds. 

Is there any way to do this?
I don't want to change the default value because the other feeds should stay at 20 minutes. 

Can I set the interval for a category?
Or edit multiple feeds at once?
I would like to customize over 100 Youtube feeds.

**Comment by zoredache** [comment]
> Is there any way to do this?

Not in the interface, but you could open the database, and change the ttl. 

A query like this might work to set to a 1d interval. You need to replace the zoredache with your username. You'll have to look at the tables in your database to see what it is.

    UPDATE `zoredache_feed`
    set ttl=86400
    WHERE `url` LIKE 'https://www.youtube.com%'

**Comment by Alkarex** [comment]
We will soon have more shared feed settings at category level, but this is not currently available. For now, see @zoredache 's answer.

**Comment by killerkarnickel404** [comment]
> 
> 
> > Is there any way to do this?
> 
> Not in the interface, but you could open the database, and change the ttl.
> 
> A query like this might work to set to a 1d interval. You need to replace the zoredache with your username. You'll have to look at the tables in your database to see what it is.
> 
> ```
> UPDATE `zoredache_feed`
> set ttl=86400
> WHERE `url` LIKE 'https://www.youtube.com%'
> ```

Thank you very much.
Worked flawlessly.
