### ISSUE TITLE
[BUG] theme switcher unusable if folder not exists

### ISSUE THREAD

**Issue by casiosmu** [FreshRSS/FreshRSS#3835]
**Describe the bug**
If the folder of the currently selected theme gets deleted, the switcher gui is rendered as completely empty frame and without navigation options (left/right).
After the folder is copied back or the language is switched in the gui (as reported [here](https://github.com/FreshRSS/FreshRSS/issues/3670#issue-914454450)), the theme switcher is usable again.

**To Reproduce**
1. Delete or rename the folder of the current theme.
2. Open Configuration->Display

**Expected behavior**
Theme switcher displayed and usable.

**Environment information (please complete the following information):**
 - Device: Smartphone, PC
 - OS: Android, openSuse
 - Browser: Firefor (Android/Linux, current version)
 - FreshRSS version: 1.18 and later
 - Database version: [e.g. Mysql 5.7]
 - PHP version: 7.3.29
 - Installation type: Raspi

**Comment by math-GH** [comment]
I can reproduce it.

Technical reason:
In the slider there is in this case no checked hidden radio input.

But I cannot find the JS where I could fix it, when no radio input is given.

**Comment by math-GH** [comment]
btw: very nice solution of this slider, that does not need any JS. I needed some time to understand it. It is very smart!
