### ISSUE TITLE
[BUG] duplicate entries on some feeds

### ISSUE THREAD

**Issue by mdemoss** [FreshRSS/FreshRSS#3836]
I'm on a fork of 1.18.0 with added shuffle functionality. Some feeds seem to add duplicate entries with each update.
One feed that exhibits this issue is https://tapas.io/rss/series/211572

If you could point me toward where in the code FreshRSS checks for duplicates, I'd be happy to take a look myself because it could very well be a problem I introduced in my fork.

```SQL
select *, sha(concat(
		guid,
		title,
		author,
		content_bin,
		link,
		date,
		hash,
		tags
	))
	from matt_entry where id_feed = 577 order by title;
```

|sha(concat(guid, title, author, content_bin, link, date, hash, tags))|id|guid|title|author|content_bin|link|date|lastSeen|hash|is_read|is_favorite|id_feed|tags|
|-------------------------------------------------------------------------------------------------|--|----|-----|------|-----------|----|----|--------|----|-------|-----------|-------|----|
|07458e776f81e77609dd4992fd55da9a572e21d1|1631095922497032|https://tapas.io/episode/2230541|Adult|;Ronnie||https://tapas.io/episode/2230541|1626445860|1631095922||1|0|577||
|07458e776f81e77609dd4992fd55da9a572e21d1|1628485923906072|https://tapas.io/episode/2230541|Adult|;Ronnie||https://tapas.io/episode/2230541|1626445860|1628485922||1|0|577||
|07458e776f81e77609dd4992fd55da9a572e21d1|1627702923388960|https://tapas.io/episode/2230541|Adult|;Ronnie||https://tapas.io/episode/2230541|1626445860|1627702922||1|0|577||
|07458e776f81e77609dd4992fd55da9a572e21d1|1629268934077767|https://tapas.io/episode/2230541|Adult|;Ronnie||https://tapas.io/episode/2230541|1626445860|1629268922||1|0|577||
|07458e776f81e77609dd4992fd55da9a572e21d1|1626659296405335|https://tapas.io/episode/2230541|Adult|;Ronnie||https://tapas.io/episode/2230541|1626445860|1626658922||1|0|577||
|07458e776f81e77609dd4992fd55da9a572e21d1|1627180924224203|https://tapas.io/episode/2230541|Adult|;Ronnie||https://tapas.io/episode/2230541|1626445860|1627180922||1|0|577||
|07458e776f81e77609dd4992fd55da9a572e21d1|1630312927186681|https://tapas.io/episode/2230541|Adult|;Ronnie||https://tapas.io/episode/2230541|1626445860|1630312927||1|0|577||
|233a0dd6c0f0fd9bb402a12f4b99b2f83df61fe8|1631095922497034|https://tapas.io/episode/2246396|Chef|;Ronnie||https://tapas.io/episode/2246396|1627673280|1631095922||1|0|577||
|233a0dd6c0f0fd9bb402a12f4b99b2f83df61fe8|1628485923906074|https://tapas.io/episode/2246396|Chef|;Ronnie||https://tapas.io/episode/2246396|1627673280|1628485922||1|0|577||
|233a0dd6c0f0fd9bb402a12f4b99b2f83df61fe8|1627702923388962|https://tapas.io/episode/2246396|Chef|;Ronnie||https://tapas.io/episode/2246396|1627673280|1627702922||1|0|577||
|233a0dd6c0f0fd9bb402a12f4b99b2f83df61fe8|1629268934077769|https://tapas.io/episode/2246396|Chef|;Ronnie||https://tapas.io/episode/2246396|1627673280|1629268922||1|0|577||
|233a0dd6c0f0fd9bb402a12f4b99b2f83df61fe8|1630312927186683|https://tapas.io/episode/2246396|Chef|;Ronnie||https://tapas.io/episode/2246396|1627673280|1630312927||1|0|577||
|4e8e7e0e2f25f9a23b2a2778cb8a0d49545b1465|1631095922497036|https://tapas.io/episode/2264977|Demands|;Ronnie||https://tapas.io/episode/2264977|1629222300|1631095922||1|0|577||
|4e8e7e0e2f25f9a23b2a2778cb8a0d49545b1465|1629268934077772|https://tapas.io/episode/2264977|Demands|;Ronnie||https://tapas.io/episode/2264977|1629222300|1629268922||1|0|577||
|4e8e7e0e2f25f9a23b2a2778cb8a0d49545b1465|1630312927186685|https://tapas.io/episode/2264977|Demands|;Ronnie||https://tapas.io/episode/2264977|1629222300|1630312927||1|0|577||
|603e6cab29dc65ae913717443b4a88e75d70e818|1631095922497037|https://tapas.io/episode/2275540|Drive|;Ronnie||https://tapas.io/episode/2275540|1630084140|1631095922||1|0|577||
|603e6cab29dc65ae913717443b4a88e75d70e818|1630312927186686|https://tapas.io/episode/2275540|Drive|;Ronnie||https://tapas.io/episode/2275540|1630084140|1630312927||1|0|577||
|69540c42694aaa465fc7c3076489189df0b0cdf4|1631095922497033|https://tapas.io/episode/2237564|Big|;Ronnie||https://tapas.io/episode/2237564|1626986220|1631095922||1|0|577||
|69540c42694aaa465fc7c3076489189df0b0cdf4|1628485923906073|https://tapas.io/episode/2237564|Big|;Ronnie||https://tapas.io/episode/2237564|1626986220|1628485922||1|0|577||
|69540c42694aaa465fc7c3076489189df0b0cdf4|1627702923388961|https://tapas.io/episode/2237564|Big|;Ronnie||https://tapas.io/episode/2237564|1626986220|1627702922||1|0|577||
|69540c42694aaa465fc7c3076489189df0b0cdf4|1629268934077768|https://tapas.io/episode/2237564|Big|;Ronnie||https://tapas.io/episode/2237564|1626986220|1629268922||1|0|577||
|69540c42694aaa465fc7c3076489189df0b0cdf4|1627180924224204|https://tapas.io/episode/2237564|Big|;Ronnie||https://tapas.io/episode/2237564|1626986220|1627180922||1|0|577||
|69540c42694aaa465fc7c3076489189df0b0cdf4|1630312927186682|https://tapas.io/episode/2237564|Big|;Ronnie||https://tapas.io/episode/2237564|1626986220|1630312927||1|0|577||
|9b296fab4b4dda596d58ddd8f3a4b76c2adf055a|1631095922497031|https://tapas.io/episode/2221342|Juveniles|;Ronnie||https://tapas.io/episode/2221342|1625781600|1631095922||1|0|577||
|9b296fab4b4dda596d58ddd8f3a4b76c2adf055a|1628485923906071|https://tapas.io/episode/2221342|Juveniles|;Ronnie||https://tapas.io/episode/2221342|1625781600|1628485922||1|0|577||
|9b296fab4b4dda596d58ddd8f3a4b76c2adf055a|1627702923388959|https://tapas.io/episode/2221342|Juveniles|;Ronnie||https://tapas.io/episode/2221342|1625781600|1627702922||1|0|577||
|9b296fab4b4dda596d58ddd8f3a4b76c2adf055a|1629268934077766|https://tapas.io/episode/2221342|Juveniles|;Ronnie||https://tapas.io/episode/2221342|1625781600|1629268922||1|0|577||
|9b296fab4b4dda596d58ddd8f3a4b76c2adf055a|1626659296405334|https://tapas.io/episode/2221342|Juveniles|;Ronnie||https://tapas.io/episode/2221342|1625781600|1626658922||1|0|577||
|9b296fab4b4dda596d58ddd8f3a4b76c2adf055a|1625875923118493|https://tapas.io/episode/2221342|Juveniles|;Ronnie||https://tapas.io/episode/2221342|1625781600|1625875922||1|0|577||
|9b296fab4b4dda596d58ddd8f3a4b76c2adf055a|1627180924224202|https://tapas.io/episode/2221342|Juveniles|;Ronnie||https://tapas.io/episode/2221342|1625781600|1627180922||1|0|577||
|9b296fab4b4dda596d58ddd8f3a4b76c2adf055a|1630312927186680|https://tapas.io/episode/2221342|Juveniles|;Ronnie||https://tapas.io/episode/2221342|1625781600|1630312927||1|0|577||
|9b4ca5fb1d91fd5199f16950a09b4050ee2424bd|1631095922497030|https://tapas.io/episode/2213744|First Contact|;Ronnie||https://tapas.io/episode/2213744|1625139600|1631095922||1|0|577||
|9b4ca5fb1d91fd5199f16950a09b4050ee2424bd|1628485923906070|https://tapas.io/episode/2213744|First Contact|;Ronnie||https://tapas.io/episode/2213744|1625139600|1628485922||1|0|577||
|9b4ca5fb1d91fd5199f16950a09b4050ee2424bd|1627702923388958|https://tapas.io/episode/2213744|First Contact|;Ronnie||https://tapas.io/episode/2213744|1625139600|1627702922||1|0|577||
|9b4ca5fb1d91fd5199f16950a09b4050ee2424bd|1629268934077765|https://tapas.io/episode/2213744|First Contact|;Ronnie||https://tapas.io/episode/2213744|1625139600|1629268922||1|0|577||
|9b4ca5fb1d91fd5199f16950a09b4050ee2424bd|1626659296405333|https://tapas.io/episode/2213744|First Contact|;Ronnie||https://tapas.io/episode/2213744|1625139600|1626658922||1|0|577||
|9b4ca5fb1d91fd5199f16950a09b4050ee2424bd|1625875923118492|https://tapas.io/episode/2213744|First Contact|;Ronnie||https://tapas.io/episode/2213744|1625139600|1625875922||1|0|577||
|9b4ca5fb1d91fd5199f16950a09b4050ee2424bd|1625614921862343|https://tapas.io/episode/2213744|First Contact|;Ronnie||https://tapas.io/episode/2213744|1625139600|1625614921||1|0|577||
|9b4ca5fb1d91fd5199f16950a09b4050ee2424bd|1627180924224201|https://tapas.io/episode/2213744|First Contact|;Ronnie||https://tapas.io/episode/2213744|1625139600|1627180922||1|0|577||
|9b4ca5fb1d91fd5199f16950a09b4050ee2424bd|1625355113652182|https://tapas.io/episode/2213744|First Contact|;Ronnie||https://tapas.io/episode/2213744|1625139600|1625355113||1|0|577||
|9b4ca5fb1d91fd5199f16950a09b4050ee2424bd|1630312927186679|https://tapas.io/episode/2213744|First Contact|;Ronnie||https://tapas.io/episode/2213744|1625139600|1630312927||1|0|577||
|ba4a2faf9b318feb07e7f673d2073166552e32a0|1631095922497035|https://tapas.io/episode/2255464|Alert|;Ronnie||https://tapas.io/episode/2255464|1628442720|1631095922||1|0|577||
|ba4a2faf9b318feb07e7f673d2073166552e32a0|1628485923906075|https://tapas.io/episode/2255464|Alert|;Ronnie||https://tapas.io/episode/2255464|1628442720|1628485922||1|0|577||
|ba4a2faf9b318feb07e7f673d2073166552e32a0|1629268934077770|https://tapas.io/episode/2255464|Alert|;Ronnie||https://tapas.io/episode/2255464|1628442720|1629268922||1|0|577||
|ba4a2faf9b318feb07e7f673d2073166552e32a0|1630312927186684|https://tapas.io/episode/2255464|Alert|;Ronnie||https://tapas.io/episode/2255464|1628442720|1630312927||1|0|577||
|c028e463f0a41bb26f18f35b34c18e2f74706d82|1631095922497038|https://tapas.io/episode/2285046|Reaction|;Ronnie||https://tapas.io/episode/2285046|1630886880|1631095922||1|0|577||

**Comment by mdemoss** [comment]
This problem might be peculiar to me. I'm lacking ```UNIQUE KEY (`id_feed`,`guid`)``` on my `_entry` table. Maybe a left-over problem from a past DB migration. I'm not sure why I didn't notice until now.

**Comment by Alkarex** [comment]
Which database are you using?

**Comment by Alkarex** [comment]
See also
https://github.com/FreshRSS/FreshRSS/blob/42a9383fe6dc4765ec4267e44913366206162116/app/Controllers/feedController.php#L374

**Comment by mdemoss** [comment]
I'm using `10.3.28-MariaDB` now, `10.0.38-MariaDB` previously, and `SQLite` before that. Seems likely I missed something during one or two of those migrations. For some reason, I hadn't been seeing a lot of duplicates before re-basing my fork on `1.18.0`.

Anyhow, I don't think there's any FreshRSS bug here.
