### ISSUE TITLE
[Feature] Enable reusable/global 'Filter actions'

### ISSUE THREAD

**Issue by GLLM** [FreshRSS/FreshRSS#3837]
Hi !

Long time user of FreshRSS here !

I recently discovered the Filter Actions setting in the feeds setting : it is wonderful to be able to automatically mark as read items in feeds based on those filters.

However, I've come to notice that I'm using the same filter for many (like ~10) feeds .. all related to the main interest. For example, I'd use the same Actions filters for Tech feeds, another one for Photog feeds etc ...
And what is frustrating is that whenever I enrich the Filter actions for a given feed, I then need to update all the other one. THey do not sync :)

What would be wonderful would be to enable the creation of Action filter sets that you can use
* either at category level or even better : at feed setting level, 
* or at feed level, set to inherit this Filter Actions and oervcharge it with additional filter entries.
To do so, I believe that a Filter Actions setup page would be needed, where you define a filter action name and the filter content.
You should be able to enrich it from this page and all feeds (or categories) using it would inherit the changes.
In case the user attemps to remove a filter in use : either block it or warn that the feed using it will not use it anymore.
What do you think ?

Thanks ... and again, a huge thanks for  FreshRSS !

GLLM
-

**Comment by Alkarex** [comment]
I have quite high on my TODO to have filter actions at category + global level. I think there is an issue somewhere

**Comment by math-GH** [comment]
Is it solved with #5942 shipped in FreshRSS 1.23?
