### ISSUE TITLE
[BUG] jQuery still used?

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#3845]
Is jQuery still in usage in FreshRSS, except that it is included in `./p/scripts`?

If the core does not need it anymore, let's create it as an extension.

**Comment by Frenzie** [comment]
Yes, it's used by the statistics display. Remember, rg/grep/git grep is your friend. ;-)

**Comment by math-GH** [comment]
It is loaded there, but is it also used?
I searched for `$(` and could not find any relevant results.

**Comment by Frenzie** [comment]
Comment it out, see if it works, if it does delete it asap. ;-p

**Comment by aledeg** [comment]
If you remove it, it will break the stats. We should move to a different library or to plain old javascript to remove that dependency.

**Comment by math-GH** [comment]
> 
> 
> If you remove it, it will break the stats. We should move to a different library or to plain old javascript to remove that dependency.

where it will break the stats?

for me it looks fine without jquery
![grafik](https://user-images.githubusercontent.com/1645099/132992024-9ceba64a-5490-4610-8cb4-0bf67663e0cb.png)

**Comment by Alkarex** [comment]
It does look like the version of Flotr2 that we have can indeed display the graphs we need without jQuery.
`jquery` appears in the code but it does not seem to be for anything significant https://github.com/EnterpriseDB/Flotr2/blob/master/flotr2.js#L1427
Related to https://github.com/FreshRSS/FreshRSS/pull/3800
