### ISSUE TITLE
[BUG] Exclude filtering problems for multiple keywords

### ISSUE THREAD

**Issue by nanhualyq** [FreshRSS/FreshRSS#3915]
**Describe the bug**
Filter actions:
`intitle:google OR intitle:apple` is working
`!intitle:google` is working
`!intitle:apple` is working
`!intitle:google OR !intitle:apple` not working

**Environment information (please complete the following information):**
 - FreshRSS version: 1.18.1
 - PHP version: 7.4.24
 - Installation type: lscr.io/linuxserver/freshrss

If this is not a bug, how should I do it, I tried `!allintitle:google apple` and it didn’t work

Poor english, please forgive me

**Comment by math-GH** [comment]
I guess it is the same like #3236

Try `AND` instead of `OR`. For explanation see my point in #3236

**Comment by math-GH** [comment]
@nanhualyq  BTW another topic. Could you help us with Chinese translations? Please see https://github.com/FreshRSS/FreshRSS/issues/3898

**Comment by nanhualyq** [comment]
Indeed, `AND` can do, Thanks a lot.

**Comment by math-GH** [comment]
For documentation:

the reason for this solution: https://en.wikipedia.org/wiki/De_Morgan%27s_laws
