### ISSUE TITLE
[BUG] Shortcut for help (F1) does not work

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#3921]
**Describe the bug**
The default shortcut to open the help is `F1`, but it does not open the help.
All `F_` does not work for me. But a letter (f.e. `9`) works fine.

**To Reproduce**
1. Go to 'shortcuts config page' and check the help shortcut (set it to `F1`)
2. Go to 'normal view' and run the shortcut
3. nothing will happen
4. repeat from 1 and change the shortcut to `9`, than the help will open in step 3

**Expected behavior**
`F_` keys are usable as shortcuts

**Environment information (please complete the following information):**
- Browser: Firefox 93
- FreshRSS version: 1.18.1
- Operating system: Windows 10

**Comment by Alkarex** [comment]
Hello,
It seems to work fine for me with Firefox on Windows.
What type of keyboard do you have, and are you sure there is no Fn-Lock problem?
As a test, does F5 refresh the page?

**Comment by math-GH** [comment]
You are right. I used another keyboard.

It works fine. Sorry :/
