### ISSUE TITLE
[BUG] Shortcut: some keys create a warning for preg_match()

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#3922]
**Describe the bug**
some keys for the shortcuts create a warning, f.e. `?` or `/` or `\`

![grafik](https://user-images.githubusercontent.com/1645099/138573913-52c59c87-73b1-423f-8600-540455b0d005.png)

**To Reproduce**
1. run your application in development mode (data/config.php => L3: `'environment' => 'development',`
2. Go to 'shortcuts config page'
2. edit the shortcuts to `?` or `/` or `\`
3. See warning

**Environment information (please complete the following information):**
- FreshRSS version: 1.18.1

**Comment by Alkarex** [comment]
Reference https://github.com/FreshRSS/FreshRSS/issues/3548

**Comment by Alkarex** [comment]
Hot fix in https://github.com/FreshRSS/FreshRSS/pull/3924
Tests welcome
