### ISSUE TITLE
[BUG] [FR] Flux invalide Mac4ever

### ISSUE THREAD

**Issue by KatyPurry** [FreshRSS/FreshRSS#3942]
**Describe the bug**
Je ne sais pas pourquoi mais le nouveau flux de Mac4ever ne fonctionne pas avec FreshRSS. Une erreur est retournée sur FreshRSS.

La page des flux : https://www.mac4ever.com/flux
Par exemple un flux qui ne fonctionne pas : https://www.mac4ever.com/flux/rss/content/actu

**To Reproduce**
Ajouter le flux

**Expected behavior**
Que ça fonctionne

**Environment information (please complete the following information):**
- Device: Desktop
- OS: Windows 11
- Browser: FF 91
- FreshRSS version: 1.18.1
- Installation type: Docker

**Comment by Alkarex** [comment]
Le flux est envoyé en tant que HTML (content-type: application/xhtml+xml) au lieu de RSS.
Essayez avec `https://www.mac4ever.com/flux/rss/content/actu#force_feed`

**Comment by KatyPurry** [comment]
Effectivement cela semble fonctionner comme ça ! Merci :)
