### ISSUE TITLE
Supporter PostgreSQL

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#416]
Certains ont PostgreSQL et non MySQL d'installé sur leur serveur/hébergement. Postgre en plus de MySQL et sqlite, et le monde entier sera ravi :+1:

**Comment by aledeg** [comment]
Peut-être faudrait il attendre la fin de #732 ?

**Comment by marienfressinaud** [comment]
Je pense aussi (attendre le début aussi d'ailleurs :p)

**Comment by Damstre** [comment]
salut, utilisant postgresql j'ai fait quelques modifs pour que freshrss tourne sur mon serveur. Pour mon utilisation ça fonctionne.
Est ce que ça peut vous être utile ou j'attend aussi pour la fin du #732 ?

**Comment by Alkarex** [comment]
@Damstre C'est intéressant, merci :-) N'hésitez pas à envoyer un patch.

**Comment by Damstre** [comment]
J'ai encore un souci, il ne me compte pas les lus/non lus, je vais d'abord régler ça.

Et je n'ai plus le support de mysql dans la foulée, il faut que je m'en occupe avent d'envoyer un patch...

**Comment by Alkarex** [comment]
Ok. Le mieux est de regarder comment nous avons supporté SQLite en plus de MySQL, et de faire pareil (héritage de classes en PHP pour redéfinir les requêtes qui doivent changer). N'hésitez pas à demander.

**Comment by Damstre** [comment]
Soit ça, soit je modifie juste les commandes sql qui changent, je devrais m'en sortir.
J'ai encore un comportement bizarre avec les lus/non lus, par contre !
Dans les stats c'est bon, il me compte bien les lus non lus, comme spécifié dans la bdd. En revanche en vue normale il me fait n'importe quoi... grosso modo il me les marque tout le temps non lus mais il ne les affichent pas (j'ai l'option pour n'afficher que les non lus), ils ne sont pas comptés comme ce devrait être le cas non plus.

Si j'en marque un, ou plusieurs, lu, puis non lu, il me les affiche correctement, mais dès que je change de page, ça revient comme avant...
c'est assez étrange, j'ai rien dans les logs de ma bdd, je ne sais pas trop ce qu'il se passe...

**Comment by Alkarex** [comment]
Cela pourrait en partie être un problème de cache (BD ou HTTP). Vérifiez que vos requêtes SQL sont bien lancées. Cette ligne doit être appelée (cela devrait déjà être le cas) lorsqu'une requête SQL de modification est faite : https://github.com/FreshRSS/FreshRSS/blob/9b512b82e2e65c6ca18199ed328de2645a7bc84e/lib/Minz/ModelPdo.php#L122

**Comment by Damstre** [comment]
c'est le cas, elle est lancée. j'ai ma requête d'update. la bdd est à jour au passage, c'est vraiment l'interface qui me fait des misères.

**Comment by Alkarex** [comment]
Pendant le développement, essayez de créer un fichier vide
“./data/no-cache.txt”
Voir
https://github.com/FreshRSS/FreshRSS/blame/2520368db459cda1745431a887d5218b316113df/CHANGELOG.md#L363

S'il y a un problème avec l'interface Web, utilisez les outils de
développement de votre navigateur pour voir les requêtes HTTP (en
particulier pour vérifier que certaines pages ne sont pas en cache).

**Comment by Damstre** [comment]
pas mieux pas mieux...
où est ce qu'il récupère le nombre de non lus pour afficher dans l'interface ? je comprends pas pourquoi il a le bon nombre dans les stats et pas en direct....

**Comment by Alkarex** [comment]
Le nombre de lus/non-lus n'est modifié que lorsqu'il y a des changements,
et il est mis en cache dans
https://github.com/FreshRSS/FreshRSS/blob/9f0b8ce70d84182676eab89e1c681e5d8bbf7539/app/SQL/install.sql.mysql.php#L25

Peut-être qu'une de ces fonctions a un problème avec PostgreSQL :
*
https://github.com/FreshRSS/FreshRSS/blob/6b7d94626656674b60d6f970bd4ada46383dde1e/app/Models/EntryDAO.php#L200
*
https://github.com/FreshRSS/FreshRSS/blob/6b7d94626656674b60d6f970bd4ada46383dde1e/app/Models/EntryDAO.php#L270
*
https://github.com/FreshRSS/FreshRSS/blob/217c191a1ba3ac03b847d261a32e19975380fcad/app/Models/FeedDAO.php#L85

**Comment by Damstre** [comment]
quand je fais des modifs, ça fonctionne, si j'en marque en non lus puis lus de nouveau, le compteur augmente mais dès que je change de page ça revient à 0. Le nombre de lus non lus au départ vient d'où du coup ? et pourquoi il est réinitialisé quand je change/recharge ma page ?

Dans ma bdd le cache_nbunreads est bon, mais c'est possible que le problème vienne de là. Je mets ce cache à jour via postgresql directement, il faut peut-être que je vire les fonctions d'update qui ne servent du coup plus à rien.

**Comment by Damstre** [comment]
en fait je vais regarder plus en détail celle ci : 
 https://github.com/FreshRSS/FreshRSS/blob/6b7d94626656674b60d6f970bd4ada46383dde1e/app/Models/EntryDAO.php#L200

je ne me souviens pas avoir eu de problèmes avec mais vu sa tête il se peut que le comportement soit bizarre avec postgresql....

**Comment by Damstre** [comment]
en effet elle ne passe pas, par contre dans freshrss elle n'est jamais appelée chez moi...

**Comment by Alkarex** [comment]
Cette fonction est seulement appelée lorsque de multiples articles ont été
d'un coup ajoutés/supprimés ou ont été marqués comme lus/non-lus.

**Comment by Damstre** [comment]
C'est bon ça tourne ! un problème de casse sur les noms de colonnes, maintenant tout à l'air de rouler. Je vais faire le tour, voir s'il n'y a pas d'autres endroits où cela peut poser des problèmes, je nettoie le code et je vous envoie ça.

Quelques questions au passage, concernant le cache_nbUnread et les stats en général, pourquoi on ne crée pas une vue directement dans la bdd qui les conserve ?
J'ai eu la flemme de réécrire les requêtes d'update en postgresql, du coup je fais l'update avec des triggers, ça marche mais je trouve ça un peu bourrin...

**Comment by Damstre** [comment]
j'ai forké et commité mes modifs :
https://github.com/Damstre/FreshRSS

ça tourne chez moi, j'ai rien testé si ce n'est via mon utilisation personnelle. Je voulais faire une pull request mais ça m'embête un peu, grosso modo j'ai rajouté des DAOpgsql dans les models, mais c'est des copies de ce qui est fait pour mysql avec quelques modifs pour que les requêtes passent. Mais ça fait beaucoup de code dupliqué... c'est pas terrible terrible.

**Comment by Alkarex** [comment]
Merci @Damstre , c'est un bon début :+1:  https://github.com/FreshRSS/FreshRSS/compare/master...Damstre:master

Si possible, n'hésitez pas à faire un patch, mais sur la branche /dev de FreshRSS (là votre code est sur /master). C'est plus facile de faire des commentaires ainsi.
Je pense que cela peut être énormément simplifié sans trop d'efforts.

Quelques points :
- [ ] Je voudrais éviter l'usage des ˋ (accent graves) qui marchent avec MySQL mais pas avec PostgreSQL, ce qui simplifiera la compatibilité. Pistes : voir si on peut le remplacer par `"` (vérifier dans MySQL, SQLite, PostgreSQL).
- [ ] Uniformiser `false` / `0` et `true` / `1` : MySQL supporte les deux. Vérifier dans SQLite et PostgreSQL. Le plus simple serait sûrement de garder `0` et `1` si PostgreSQL le supporte.
- [x] `FreshRSS_CategoryDAOpgSQL` ne devrait du coup pas être nécessaire.
- [x] `FreshRSS_Factory::createCategoryDAO()` de devrait du coup plus être nécessaire non plus.
- [x] `FreshRSS_DatabaseDAOpgSQL` devrait hériter de `FreshRSS_DatabaseDAO` et ne redéfinir que ce qui change (à la manière de `FreshRSS_DatabaseDAOSQLite`).
- [x] Vérifier cette ligne https://github.com/Damstre/FreshRSS/blob/f9a7028a4bb54b50bbeb013b9cb38d05eca102e0/app/Models/EntryDAOpgSQL.php#L72 qui est `. ($this->hasNativeHex() ? 'X?' : '?')` en MySQL (noter le `X` pour indiquer que c'est de l'hexadécimal). Vérifier la compatibilité avec PostgreSQL. Si PostgreSQL ne supporte pas, alors modifier https://github.com/Damstre/FreshRSS/blob/f9a7028a4bb54b50bbeb013b9cb38d05eca102e0/app/Models/EntryDAO.php#L10 pour retourner `false` dans le cas de PostgreSQL.
- [ ] Pourquoi `'t' : 'f'`. Essayer de préférer `1 : 0`. Voir le point plus haut à propos des booléens. https://github.com/Damstre/FreshRSS/blob/f9a7028a4bb54b50bbeb013b9cb38d05eca102e0/app/Models/EntryDAOpgSQL.php#L87
- [x] Faire hériter `FreshRSS_EntryDAOpgSQL` de `FreshRSS_EntryDAO` (sur le modèle de `FreshRSS_EntryDAOSQLite`) et ne ré-écrire que les changements (qui devraient sûrement être limités à https://github.com/Damstre/FreshRSS/blob/f9a7028a4bb54b50bbeb013b9cb38d05eca102e0/app/Models/EntryDAOpgSQL.php#L697 après avoir uniformisé les ˋ et booléens).
- [ ] Faire hériter `FreshRSS_FeedDAOpgSQL` de `FreshRSS_FeedDAO` et ne redéfinir que les changements (sur le modèle de `FreshRSS_FeedDAOSQLite`).
- [x] Idem pour `FreshRSS_StatsDAOpgSQL`

**Comment by Damstre** [comment]
ok.

Pour les histoires de booléens avec 0 et 1, je vais voir ça, je sais comment faire, ce n'est pas forcément plus simple mais c'est générique.

l'histoire du hash en héxa j'avoue que j'ai pas bien compris. ce que j'ai là ne me donne pas d'erreur sur la bdd mais je ne sais pas si c'est le bon comportment... C'est sensé fonctionner comment cette affaire ?

Enfin pour les "`" à mon avis il faut les virer partout, ça ne sert à rien. Pour les noms des tables et des colonnes c'est fixé dans le code et les valeurs passées sont gérées via le prepare(), du coup je ne saisis pas trop l'intérêt...

**Comment by Damstre** [comment]
je reviens à la charge pour les "`". On peut faire en sorte que mysql supporte les """ de la même façon que postgresql (cf http://dev.mysql.com/doc/refman/5.0/en/sql-mode.html), mais bon je ne suis pas sûr de l'intérêt. D'autant plus que, dans mon cas, la seule différence se fait sur les colonnes cache_nbUnreads et cache_nbEntries, du fait de la majuscule. Mais pour corriger ça il faut mettre des quotes autour des noms de colonnes aussi, et ça peut être long...
Dans l'autre sens, si on vire les quote dans mysql on se prive des noms réservés et/ou avec des caractères spéciaux et on ne peut pas avoir deux utilisateurs avec seulement une différence de casse dans le nom, mais c'est beaucoup plus vite fait...

**Comment by Alkarex** [comment]
Ok. Je suggère du coup de faire un appel de fonction, qui dépendra de la base de données.

Exemple de code actuel : 

``` php
'UPDATE `' . $this->prefix . 'feed` f '
```

À remplacer par quelque chose du genre

``` php
'UPDATE ' . column('feed') . ' f '
```

**Comment by Damstre** [comment]
j'ai commité les changements que j'ai fait. En remplacant les backtick par des double quote ça simplifie déjà pas mal !
J'ai passé les noms de tous les champs en minuscules aussi. Sinon il faut mettre des quotes à chaque fois c'est trop lourd.

Je viens de voir que j'ai un souci d'update par contre je vais essayer de régler ça, mais pour l'instant ça ne fonctionne pas. Je pense que c'est le hash qui foire... Je suis toujours preneur d'infos pour savoir comment on est sensé l'utiliser.

**Comment by Damstre** [comment]
avec mes derniers commits tout à l'air de fonctionner sous postgresql.

J'ai pas testé avec les autres bdd.

**Comment by Alkarex** [comment]
Merci @Damstre :+1:  Je vais regarder ça.
Pourriez-vous faire une pull request sur la branche /dev ?

**Comment by mro** [comment]
a quick summary for the non-francophones? Is it near?

**Comment by Alkarex** [comment]
@mro It looks like @Damstre 's version can run on PostgreSQL, but there are still a few changes needed before it can be merged in the main branch

**Comment by mro** [comment]
thx!

**Comment by anayrat** [comment]
:+1:  merci pour le travail!

**Comment by Alkarex** [comment]
@Damstre Je viens de commencer un patch pour PostgreSQL basé sur votre travail, partant de la branche /dev actuelle, et en essayant de limiter le nombre de changements https://github.com/Alkarex/FreshRSS/tree/PostgreSQL Je n'ai pas encore testé.
Commentaires, contributions, et tests bienvenus dans https://github.com/FreshRSS/FreshRSS/pull/1195

**Comment by Alkarex** [comment]
PostgreSQL has landed in the dev branch of FreshRSS :-) Tests welcome!

**Comment by marienfressinaud** [comment]
\o/

**Comment by Alkarex** [comment]
En plus de PostgreSQL, il faut aussi vérifier qu'il n'y a pas de nouveau bug avec MySQL et SQLite, donc les tests sont aussi bienvenus pour ces bases de données

**Comment by Alkarex** [comment]
For the PostgreSQL testers of the /dev version, I would particularly be interested in feedback about:
- Performances
- Tests with full-text search (https://github.com/FreshRSS/FreshRSS/issues/302)
  - when adding a GIN index https://www.postgresql.org/docs/current/static/textsearch-indexes.html
  - https://www.depesz.com/2011/02/19/waiting-for-9-1-faster-likeilike/
- The minimum version of PostgreSQL
