### ISSUE TITLE
[BUG] 1.19.1-arm - Wrong Date/Time using Docker / docker-compose, high cpu-usage

### ISSUE THREAD

**Issue by mattias88** [FreshRSS/FreshRSS#4198]
**Describe the bug**
Since i updated to FreshRSS 1.19.1-arm on my Raspberry Pi 4 something went wrong setting the time zone / date.
<pre> 192.168.178.22 - - [15/Apr/1935:18:21:53 +0100] "POST /api/fever.php?api&groups HTTP/1.1" 200 212 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0</pre>

Furthermore, the cron job on my raspberry uses one core to 100%. I think that is related to the wrong Date-Settings.

Problem persists with 1.19.2, downgrading to 1.18.1-arm fixes the problem.

**Docker-compose Env-Settings**
<pre>
    environment:
      CRON_MIN: '*/20'
      TZ: Europe/Berlin
</pre>

**Expected behavior**
Time / Date is correct (Europe/Berlin) and CPU-usage is back to normal

**Screenshots**
![cpu-usage](https://user-images.githubusercontent.com/30684437/152639858-982b45f6-a8a0-42d9-befd-272c8e9fad21.png)

**Environment information (please complete the following information):**
- Device: Raspberry Pi 4
- OS: Raspbian GNU/Linux 10 (buster)
- FreshRSS version:  1.19.1-arm / 1.19.2-arm
- Database version: Postgres
- Installation type: Docker

**Comment by Alkarex** [comment]
Could you please try the following commands on your server?

```sh
date
sudo docker exec freshrss date
sudo docker exec freshrss crontab -l
sudo docker exec freshrss cat /tmp/FreshRSS.log
sudo docker logs freshrss 1> /dev/null
sudo docker logs freshrss 2>&1 | grep -i Error
```

**Comment by mattias88** [comment]
Thanks for the quick reply :+1: 
<pre>
pi@raspi4  ~  date                                    
Sa 5. Feb 16:43:04 CET 2022

pi@raspi4  ~ sudo docker exec freshrss-app date      
Thu Jan  1 01:00:00 CET 1970

pi@raspi4  ~ sudo docker exec freshrss-app crontab -l
*/20 * * * * . /var/www/FreshRSS/Docker/env.txt;                su www-data -s /bin/sh -c 'php 
 var/www/FreshRSS/app/actualize_script.php'              2>> /proc/1/fd/2 > /tmp/FreshRSS.log

pi@raspi4  ~  sudo docker exec freshrss-app cat /tmp/FreshRSS.log
Results: 
mattias OK
End.

pi@raspi4  ~  sudo docker logs freshrss-app 1> /dev/null        
[Sun Jan 00 00:00:00.000000 1900] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.52 (Debian) configured -- resuming normal operations
[Wed Jun 05 11:52:45.'''(*, 1935] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'

pi@raspi4 ~  sudo docker logs freshrss-app 2>&1 | grep -i Error
pi@raspi4  ~  
</pre>

**Comment by Frenzie** [comment]
To the best of my knowledge the clock of the container should be the same as that of the host (give or take timezones). That's very strange. O.o

**Comment by Alkarex** [comment]
That is indeed quite strange. A couple of suggestions for debugging:

1. Try with a newer image `freshrss/freshrss:edge-arm`
2. Try without the TZ parameter

**Comment by mattias88** [comment]
Unfortunately no success with the suggested changes BUT succeeded with  my own Image

- tried newer image as suggested (edge-arm)
- removed TZ parameter

Also tried to mount local timezone as mentioned [here](https://serverfault.com/questions/683605/docker-container-time-timezone-will-not-reflect-changes), but no avail.
<pre>
volumes:
    - "/etc/timezone:/etc/timezone:ro"
    - "/etc/localtime:/etc/localtime:ro"
</pre>

As 1.18.1 works flawless, i assume the reason for the different behavior could be in the Base-Image.  For 1.19.0 there was an update from Debian 10 to 11.

**Building my own Image based on Debian 10 works ok. Date / Time is now correct.**

Building the Image with Debian 11 fails:
<pre>
pi@raspi4  ~/FreshRSS  master ±  docker build --pull --tag freshrss/freshrss-mw-debian11 -f Docker/Dockerfile .
Sending build context to Docker daemon  7.628MB
Step 1/23 : FROM debian:11-slim
11-slim: Pulling from library/debian
Digest: sha256:4c25ffa6ef572cf0d57da8c634769a08ae94529f7de5be5587ec8ce7b9b50f9c
Status: Image is up to date for debian:11-slim
 ---> 8b6ab260f294
Step 2/23 : ENV TZ UTC
 ---> Using cache
 ---> ee9f394410bc
Step 3/23 : SHELL ["/bin/bash", "-o", "pipefail", "-c"]
 ---> Using cache
 ---> d5f0f713a60c
Step 4/23 : RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
 ---> Using cache
 ---> daf1f6e8133b
Step 5/23 : RUN apt-get update &&       apt-get install --no-install-recommends -y      ca-certificates cron    apache2 libapache2-mod-php      php-curl php-gmp php-intl php-mbstring php-xml php-zip  php-sqlite3 php-mysql php-pgsql &&      rm -rf /var/lib/apt/lists/*
 ---> Running in bee458153b91
Get:1 http://security.debian.org/debian-security bullseye-security InRelease [44.1 kB]
Get:2 http://deb.debian.org/debian bullseye InRelease [116 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [39.4 kB]
Err:1 http://security.debian.org/debian-security bullseye-security InRelease
  At least one invalid signature was encountered.
Err:2 http://deb.debian.org/debian bullseye InRelease
  At least one invalid signature was encountered.
Err:3 http://deb.debian.org/debian bullseye-updates InRelease
  At least one invalid signature was encountered.
Reading package lists...
W: GPG error: http://security.debian.org/debian-security bullseye-security InRelease: At least one invalid signature was encountered.
E: The repository 'http://security.debian.org/debian-security bullseye-security InRelease' is not signed.
W: GPG error: http://deb.debian.org/debian bullseye InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian bullseye InRelease' is not signed.
W: GPG error: http://deb.debian.org/debian bullseye-updates InRelease: At least one invalid signature was encountered.
E: The repository 'http://deb.debian.org/debian bullseye-updates InRelease' is not signed.
The command '/bin/bash -o pipefail -c apt-get update &&         apt-get install --no-install-recommends -y      ca-certificates cron    apache2 libapache2-mod-php     php-curl php-gmp php-intl php-mbstring php-xml php-zip   php-sqlite3 php-mysql php-pgsql &&      rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

</pre>

**Comment by Alkarex** [comment]
The local build of our Debian 11 image on Raspberry Pi works fine for me. Which versions of Docker do you have?

```console
pi@raspberrypi:~ $ docker -v
Docker version 20.10.12, build e91ed57
pi@raspberrypi:~ $ docker-compose -v
docker-compose version 1.25.0, build unknown
pi@raspberrypi:~ $ cat /etc/issue.net
Raspbian GNU/Linux 11
```

And what OS more precisely do you run on that Raspberry Pi?

Could you try a build based on our Alpine image? `Docker/Dockerfile-Alpine`

**Comment by Alkarex** [comment]
Could you also try this image I have built locally based on Debian 11? `freshrss/freshrss:edge-arm-local`

**Comment by mattias88** [comment]
Thanks for looking into that :+1: 

> Which versions of Docker do you have?

```zsh
pi@raspi4  ~/FreshRSS/Docker   master ±  docker -v
Docker version 20.10.12, build e91ed57

pi@raspi4  ~/FreshRSS/Docker  master ±  docker-compose -v
docker-compose version 1.29.2, build unknown

pi@raspi4  ~/FreshRSS/Docker   master ±  cat /etc/issue.net 
Raspbian GNU/Linux 10
```

> And what OS more precisely do you run on that Raspberry Pi?
```zsh
pi@raspi4  ~/FreshRSS/Docker  master ±  cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

> Could you also try this image I have built locally based on Debian 11? freshrss/freshrss:edge-arm-local  

Done, same issue

> Could you try a build based on our Alpine image? Docker/Dockerfile-Alpine

Build fails with missing packages. Saw the 'temporary error' for the Alpine-CDN. cURL on the URL from the raspberry works
```zsh
pi@raspi4  ~/FreshRSS  master ±  docker build --pull --tag freshrss/freshrss-mw-alpine -f Docker/Dockerfile-Alpine .
Sending build context to Docker daemon  7.628MB
Step 1/21 : FROM alpine:3.15
3.15: Pulling from library/alpine
Digest: sha256:21a3deaa0d32a8057914f36584b5288d2e5ecc984380bc0118285c70fa8c9300
Status: Image is up to date for alpine:3.15
 ---> 78571b13081b
Step 2/21 : ENV TZ UTC
 ---> Using cache
 ---> 453f1edf7f2d
Step 3/21 : SHELL ["/bin/ash", "-eo", "pipefail", "-c"]
 ---> Using cache
 ---> fa270f1e41ea
Step 4/21 : RUN apk add --no-cache      apache2 php8-apache2    php8 php8-curl php8-gmp php8-intl php8-mbstring php8-xml php8-zip       php8-ctype php8-dom php8-fileinfo php8-iconv php8-json php8-opcache php8-phar php8-session php8-simplexml php8-xmlreader php8-xmlwriter php8-tokenizer php8-zlib        php8-pdo_sqlite php8-pdo_mysql php8-pdo_pgsql
 ---> Running in b3cca1f24561
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/armv7/APKINDEX.tar.gz
WARNING: fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/armv7/APKINDEX.tar.gz
Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.15/main: temporary error (try again later)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.15/community: temporary error (try again later)
ERROR: unable to select packages:
  apache2 (no such package):
    required by: world[apache2]
  php8 (no such package):
    required by: world[php8]
...
The command '/bin/ash -eo pipefail -c apk add --no-cache        apache2 php8-apache2    php8 php8-curl php8-gmp php8-intl php8-mbstring php8-xml php8-zip       php8-ctype php8-dom php8-fileinfo php8-iconv php8-json php8-opcache php8-phar php8-session php8-simplexml php8-xmlreader php8-xmlwriter php8-tokenizer php8-zlib        php8-pdo_sqlite php8-pdo_mysql php8-pdo_pgsql' returned a non-zero code: 25
```

**Comment by Alkarex** [comment]
Hum, it could be a kernel issue, your Raspberry Pi running Debian 10. Raspberry Pi OS (Raspbian) based on Debian 11 is available. Maybe you could try again after an update.

**Comment by mattias88** [comment]
Will give it a try. But would be kind of weird if that is the reason for my problems.

**Comment by mattias88** [comment]
Update took quite some time. But after updating to bullseye everything works like expected. Using the provided Image 1.19.2  
 now  :smile: 

I still didn't understand what had caused the problems :disappointed: 

But anyway - it works.  Thanks for the help. Very much appreciated :+1:

**Comment by Alkarex** [comment]
Seems to be a known issue https://github.com/moby/moby/issues/40734

**Comment by Alkarex** [comment]
https://serverfault.com/questions/1037146/docker-container-with-random-date
