### ISSUE TITLE
Problem using Fever API since FreshRSS 1.19.2

### ISSUE THREAD

**Issue by gdirch** [FreshRSS/FreshRSS#4200]
I'm using the app Fiery Feeds using the Fever API on iOS and macOS to read RSS based news using FreshRSS. Since upgrading to FreshRSS 1.19.2 the app Fiery Feeds no longer gets any results from FreshRSS. The changelog of FreshRSS does not mention any changes of the Fever API. The logfile of FreshRSS does not show any errors. Is there anything else I can do to analyse a possible problem with the latest version of FreshRSS?

**Comment by Alkarex** [comment]
Hello,
Which version of FreshRSS was the last working for you? How do you install FreshRSS, on which platform (and versions, e.g. of PHP)?

Additional logs can be found in `./FreshRSS/data/users/_/log_api.txt`

And debugging information can be enabled by uncommenting the following two lines:

https://github.com/FreshRSS/FreshRSS/blob/fe880d1a98d8224682036e44520bb92b2ed417aa/p/api/fever.php#L60-L61

**Comment by gdirch** [comment]
I'm using a self maintained Docker image based on Alpine 3.15.0 with PHP 8.0.14 and MariaDB 10.6.4. The latest working version of FreshRSS was 1.19.1. If I copy the file /app-release/www/p/api/fever.php used in version 1.19.1 to version 1.19.2 everything is running fine.

In the logfile ./FreshRSS/data/users/_/log_api.txt I cannot find any actual hints.

I've enabled the debugging by uncommenting the two mentioned lines but I cannot find a file containing the log ...

**Comment by Alkarex** [comment]
On a 32-bit system, right? Probably a regression from https://github.com/FreshRSS/FreshRSS/pull/4110 , not allowing 64-bit integers as string for 32-bit systems.
Fix coming.

**Comment by Alkarex** [comment]
Could you please try this patch https://github.com/FreshRSS/FreshRSS/pull/4201 on the edge (main) branch?

**Comment by gdirch** [comment]
Using your patched fever.php file, I'm getting an uncaught TypeError:
2022/02/06 13:23:23 [error] 52#52: *7 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: FeverDAO::findEntries(): Argument #3 ($max_id) must be of type string, null given, called in /app-release/www/p/api/fever.php on line 476 and defined in /app-release/www/p/api/fever.php:78

Removing the type definitions in line 78 my FreshRSS is working as expected:
public function findEntries(array $feed_ids, array $entry_ids, $max_id, $since_id) {

Currently I'm not using a git clone of FreshRSS to build the Docker image. Instead I'm using the latest stable version of FreshRSS by downloading https://github.com/FreshRSS/FreshRSS/archive/refs/heads/master.zip. To test your patch I've downloaded the file edge.zip and patched the above mentioned file fever.php only. Can this be the cause for the TypeError? Do I have to patch all files referenced in your commit last night?

**Comment by Alkarex** [comment]
If you are not using git, the easiest is to download an archive including the patch. One of:
* https://github.com/Alkarex/FreshRSS/archive/refs/heads/phpstan_fix_32bit_fever.tar.gz
* https://github.com/Alkarex/FreshRSS/archive/refs/heads/phpstan_fix_32bit_fever.zip

**Comment by Alkarex** [comment]
But hold on, let me patch the bug you found first.

**Comment by Alkarex** [comment]
Ready for new test.

**Comment by gdirch** [comment]
Great, your fix is working! Many thanks for your very fast response. Now I'm waiting for 1.20.0 ;-)

I think this issue can be closed now.

**Comment by Alkarex** [comment]
Merged into our edge branch (the default branch) https://github.com/FreshRSS/FreshRSS
You are welcome to use this version, which is a rolling release, as we need more testers

**Comment by Alkarex** [comment]
@gdirch I have found a couple more issues. Could you please try https://github.com/FreshRSS/FreshRSS/pull/4202 ?
* https://github.com/Alkarex/FreshRSS/archive/refs/heads/fever_more_type_hints.zip

**Comment by Alkarex** [comment]
In particular marking feeds and categories as read

**Comment by gdirch** [comment]
I've taken the latest  https://github.com/FreshRSS/FreshRSS/archive/refs/heads/edge.zip and had no problems marking specific feeds or whole categories as read/unread.

**Comment by Alkarex** [comment]
Thanks for the feedback :-)

**Comment by gdirch** [comment]
Hello Alexandre,

I’ve enabled my docker image to to be used in a stable (1.19.2) and a development (1.20.0-dev) environment. The logfile in the development version shows many error messages like the following one:

172.18.0.13 - (null) [08/Feb/2022:21:06:13 +0100] "POST /api/fever.php?api HTTP/1.0" 503 20 "-" "Fiery Feeds/2.5.11 (iPhone; iOS 15.3; Scale/2.00)“

These messages are thrown after marking a whole category as read multiple times. I cannot see a correlation between the number of articles marked as read an the number of 503 error messages.

Best regards,
Dirk
