### ISSUE TITLE
[Feature] create RTL CSS files via Github Actions

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#4213]
It costs a lot of time to create the RTL CSS files.

This tool could help us:
https://rtlcss.com/learn/usage-guide/install/

What do you think? Is it possible?

(I am not familar with GitHub Actions and NPM)

**Comment by aledeg** [comment]
I do not know that tool nor if it will completely support what we need but if it helps us do what we need, I am all for it. Our time is better spent doing something that cannot be automated.

**Comment by Alkarex** [comment]
@math-GH We already have that. Please give a shot at `make fix-all` if you have not tried yet ;-)

**Comment by Alkarex** [comment]
Or for this specific subset, `npm run rtlcss`

**Comment by Alkarex** [comment]
P.S. and also `make test-all` (which is just testing everything, not changing anything)

**Comment by math-GH** [comment]
I wish I could use `make` as Windows user.....

**Comment by Alkarex** [comment]
You can of course. WSL is your friend ;-) I will send more info later

**Comment by Alkarex** [comment]
* https://ubuntu.com/wsl
* https://docs.microsoft.com/windows/wsl/install-win10

And check your e-mail for a little guide @math-GH :-)
