### ISSUE TITLE
Single Items showing up even when more are avaiable in Normal View

### ISSUE THREAD

**Issue by quella** [FreshRSS/FreshRSS#4215]
I have been on the development track from 1.17 -> 1.20 and all have been great until the latest update in 1.20.0-dev.  Thank you devs for all you do to keep the application innovative and adding such great features.  

The issue I have recently run into is my 'Main Stream'  or any of the sub groups only shows a single item only even when there are many other unread items using the Normal View pane.  Wondering if I'm missing something obvious here.  I tried the top buttons to select unread/read, unstarred, stared, etc. to no eval.  I mostly access the application using a third-part reader so it is not a big issue at this time, but was not sure if this effects others.  

Setup:
FreshRss running on RasberryPi
Browser accessing is Chrome (98.0.4758)

Attached images to show what I'm saying above.
![Screen Shot 2022-02-09 at 10 02 15 AM](https://user-images.githubusercontent.com/823352/153228386-6408cb84-c97f-42cf-b59a-e00feb16bd50.png)
![Screen Shot 2022-02-09 at 9 48 55 AM](https://user-images.githubusercontent.com/823352/153228391-9f15ebf9-638f-4fd3-91f6-02e3da05ac84.png)

**Comment by WillPresley** [comment]
For what it's worth, I was having this issue on the Edge branch as well the last couple of days. There is a service worker error of some sort in the JS console, but I didn't have time to dig into it. I changed my branch to master and pulled down, all is well again. It's definitely something introduced since the last stable update. I tried clearing caches, data, cookies, etc. and tried in other browsers (Chrome, FF, Edge) as well.

**Comment by quella** [comment]
Will, thanks for the confirmation that you are also seeing this behavior in Edge as well.  I assumed it was something I missed on the latest update or a new button I needed to push.  I will see what the dev team comes back with and I can wait until an update due to my use of the third party client (Reeder).

**Comment by quella** [comment]
I tried this in Firefox and Safari on a Mac as well just to confirm a browser issue or not.  What I did notice is that there is an indented feed source at the very bottom where the list stops displaying.  See the attached image.  36 articles in the feed group but only 6 show in the reader pane and then you get the indented one at the bottom and everything stops.
![Screen Shot 2022-02-09 at 3 13 50 PM](https://user-images.githubusercontent.com/823352/153283062-94ffb0fe-9152-4083-a481-ea365a86ae26.png)

**Comment by Frenzie** [comment]
What are your settings under Reading? I don't see anything like this in <del>Edge</del>any browser. Any extensions?

**Comment by quella** [comment]
I'm on a Mac, but I get the same in Chrome, Firefox, and Safari (without any extensions).  Was working prior to the last few updates.  Here is my "Reading" configuration page if something is amiss here.  

![Screen Shot 2022-02-09 at 3 58 38 PM](https://user-images.githubusercontent.com/823352/153289127-2285afdc-ba0f-4c42-b62f-415d853fc052.png)
![Screen Shot 2022-02-09 at 4 01 09 PM](https://user-images.githubusercontent.com/823352/153289326-7d3b7f6b-f3b3-4c58-9e7d-e96444f9b9ad.png)

**Comment by WillPresley** [comment]
@Frenzie @Alkarex 
I flipped back over to the edge branch to grab this screenshot. It looks like it may have something to do with browser notifications? I still haven't really looked into it, sorry, but I wanted to drop this here if it would help. Rolling back to master fixes it up right away.
![freshrss-issue-4215_willpresley](https://user-images.githubusercontent.com/5607733/153289849-26084e2b-2878-4ddb-b6f4-a953d03770d1.png)

**Comment by Frenzie** [comment]
Sorry, I meant FreshRSS extensions.

Notifications? In that case I'll take a closer look at https://github.com/FreshRSS/FreshRSS/pull/4193, https://github.com/FreshRSS/FreshRSS/pull/4023 and https://github.com/FreshRSS/FreshRSS/pull/4006.

**Comment by quella** [comment]
I have not added any new extensions to the application myself, and using a third-party (google API) reader, it works fine.  For me, it seems like it is an issue in displaying in a browser.

**Comment by Frenzie** [comment]
Hold on, which theme are you guys using?

**Comment by WillPresley** [comment]
I am using AD's Dark.

**Comment by quella** [comment]
I have the default theme but in dark mode.  Me as well

**Comment by Frenzie** [comment]
For me it definitely all contains:
```html
<div id="notification" class="notification closed">
	<span class="msg"></span>
	<a class="close" href=""><img class="icon" src="../themes/icons/close.svg" alt="?" /></a>
</div>
```

**Comment by WillPresley** [comment]
That block gets added to the DOM for me when running master, but not edge. The very last line of HTML when having the error is `<li class="item thumbnail landscape small">`, could this actually have something to do with the new inline images and whatnot? It is, all the same, only an issue stemming from commits since the last stable release.

**Comment by Alkarex** [comment]
Could you please check your Web server logs and FreshRSS logs for any warning / error?
`./FreshRSS/data/users/*/log*.txt`

**Comment by Frenzie** [comment]
I'm testing on the edge branch (latest commit 133e0d61db4d316806686243e735961166113e1c).

> The very last line of HTML when having the error is `<li class="item thumbnail landscape small">`

So you mean it's actually a PHP error? As @Alkarex said, that should show in the log.

**Comment by Frenzie** [comment]
PS Inline images?

**Comment by quella** [comment]
I do see these in my recent logs.

[Sun, 06 Feb 2022 22:02:40 -0500] [warning] --- cURL error 28: Connection timed out after 15000 milliseconds [https://thycotic.com/feed/?%2F]
[Mon, 07 Feb 2022 03:21:38 -0500] [warning] --- cURL error 22: The requested URL returned error: 503  [https://live.paloaltonetworks.com/twzvq
79624/rss/board?board.id=CommunityBlog]
[Mon, 07 Feb 2022 10:03:42 -0500] [warning] --- cURL error 28: Operation timed out after 15001 milliseconds with 0 out of 0 bytes received [ht
tps://www.oodaloop.com/feed/]
[Mon, 07 Feb 2022 11:20:43 -0500] [warning] --- A feed could not be found at `https://geekdad.com/feed/`; the status code is `200` and content
-type is `text/html; charset=utf-8` [https://geekdad.com/feed/]
[Mon, 07 Feb 2022 20:41:17 -0500] [warning] --- cURL error 28: Operation timed out after 15000 milliseconds with 0 bytes received [https://www
.psfk.com/feeds/psfk]
[Mon, 07 Feb 2022 22:01:36 -0500] [warning] --- cURL error 28: Operation timed out after 15001 milliseconds with 0 bytes received [https://www
.cnet.com/rss/news/]
[Tue, 08 Feb 2022 08:42:19 -0500] [warning] --- cURL error 28: Connection timed out after 15001 milliseconds [http://www.2600.com/rss.xml]
[Tue, 08 Feb 2022 08:43:45 -0500] [warning] --- Feed has invalid GUIDs: https://whdh.com/feed/
[Tue, 08 Feb 2022 10:00:58 -0500] [warning] --- https://stratechery.com/feed/ is invalid XML, likely due to invalid characters. XML error: Inv
alid character at line 43, column 37 [https://stratechery.com/feed/]
[Tue, 08 Feb 2022 10:02:16 -0500] [warning] --- cURL error 28: Connection timed out after 15001 milliseconds [http://www.2600.com/rss.xml]
[Tue, 08 Feb 2022 10:03:49 -0500] [warning] --- Feed has valid GUIDs again: https://whdh.com/feed/
[Tue, 08 Feb 2022 11:21:14 -0500] [warning] --- cURL error 22: The requested URL returned error: 503 Service Unavailable [http://feeds.laughin
gsquid.com/laughingsquid]
[Tue, 08 Feb 2022 11:21:24 -0500] [warning] --- https://stratechery.com/feed/ is invalid XML, likely due to invalid characters. XML error: Inv
alid character at line 43, column 37 [https://stratechery.com/feed/]
[Tue, 08 Feb 2022 11:22:35 -0500] [warning] --- cURL error 28: Connection timed out after 15001 milliseconds [http://www.2600.com/rss.xml]
[Tue, 08 Feb 2022 12:40:50 -0500] [warning] --- https://stratechery.com/feed/ is invalid XML, likely due to invalid characters. XML error: Inv
alid character at line 43, column 37 [https://stratechery.com/feed/]
[Tue, 08 Feb 2022 12:42:03 -0500] [warning] --- cURL error 28: Connection timed out after 15000 milliseconds [http://www.2600.com/rss.xml]
[Tue, 08 Feb 2022 12:43:44 -0500] [warning] --- cURL error 28: Operation timed out after 15000 milliseconds with 12288 out of 295204 bytes rec
eived [https://www.expositoryparenting.org/blog?format=rss]
[Tue, 08 Feb 2022 14:00:49 -0500] [warning] --- https://stratechery.com/feed/ is invalid XML, likely due to invalid characters. XML error: Inv
alid character at line 43, column 37 [https://stratechery.com/feed/]
[Tue, 08 Feb 2022 15:20:57 -0500] [warning] --- https://stratechery.com/feed/ is invalid XML, likely due to invalid characters. XML error: Inv
alid character at line 43, column 37 [https://stratechery.com/feed/]
[Tue, 08 Feb 2022 15:23:37 -0500] [warning] --- A feed could not be found at `https://theoatmeal.com/feed/rss`; the status code is `200` and c
ontent-type is `application/xml; charset=ISO-8859-1; filename=feed.xml` [https://theoatmeal.com/feed/rss]
[Tue, 08 Feb 2022 15:23:47 -0500] [warning] --- A feed could not be found at `https://www.artstation.com/wlop.rss`. Empty body. [https://www.a
rtstation.com/wlop.rss]
[Tue, 08 Feb 2022 16:41:10 -0500] [warning] --- https://stratechery.com/feed/ is invalid XML, likely due to invalid characters. XML error: Inv
alid character at line 43, column 37 [https://stratechery.com/feed/]
[Tue, 08 Feb 2022 18:00:50 -0500] [warning] --- https://stratechery.com/feed/ is invalid XML, likely due to invalid characters. XML error: Inv
alid character at line 43, column 37 [https://stratechery.com/feed/]
[Tue, 08 Feb 2022 20:42:46 -0500] [warning] --- cURL error 28: Operation timed out after 15000 milliseconds with 0 bytes received [https://www
.thefamilygamers.com/feed/]
[Tue, 08 Feb 2022 22:02:00 -0500] [warning] --- cURL error 28: Operation timed out after 15001 milliseconds with 0 bytes received [https://the
cripplegate.com/feed/]
[Wed, 09 Feb 2022 10:00:54 -0500] [warning] --- cURL error 28: Operation timed out after 15000 milliseconds with 0 bytes received [https://www
.jwz.org/blog/feed/]
[Wed, 09 Feb 2022 11:21:26 -0500] [warning] --- cURL error 22: The requested URL returned error: 500 Internal Server Error [https://www.psfk.c
om/feeds/psfk]
[Wed, 09 Feb 2022 11:21:41 -0500] [warning] --- cURL error 28: Operation timed out after 15000 milliseconds with 1998839 out of 3100108 bytes 
received [https://www.trustedreviews.com/feed]
[Wed, 09 Feb 2022 12:43:53 -0500] [warning] --- Feed has invalid GUIDs: https://whdh.com/feed/
[Wed, 09 Feb 2022 14:03:44 -0500] [warning] --- Feed has valid GUIDs again: https://whdh.com/feed/
[Wed, 09 Feb 2022 15:23:15 -0500] [warning] --- Feed has invalid GUIDs: https://whdh.com/feed/

**Comment by quella** [comment]
Here is my browser inspect as well when I try to display the MAIN STREAM.  Only one ERROR shown.

![Screen Shot 2022-02-09 at 4 30 39 PM](https://user-images.githubusercontent.com/823352/153293435-4afab56b-0265-4628-a5f5-31ab1f3c77a1.png)

**Comment by Frenzie** [comment]
If you use the left hand categories, are you able to narrow it down to a specific feed?

**Comment by quella** [comment]
It looks like most feeds and feed groups give the same error.  I did found a feed that shows two new items and no errors.  Screenshots below.

![Screen Shot 2022-02-09 at 4 41 04 PM](https://user-images.githubusercontent.com/823352/153294909-23f9a081-f8cd-4b62-be2a-5a2bc86a39e0.png)

![Screen Shot 2022-02-09 at 4 40 49 PM](https://user-images.githubusercontent.com/823352/153294941-92867dca-d750-4882-9786-d5b77d5f0592.png)

**Comment by Alkarex** [comment]
There are probably more messages in your Web **server** logs. Could you have a look?

**Comment by quella** [comment]
I do see these in the freshrss.error.logs

```
2022/02/09 16:43:38 [error] 540#540: *6758 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Return value of FreshRSS_
Entry::thumbnail() must be of the type string, array returned in /var/www/freshrss/app/Models/Entry.php:131
Stack trace:
#0 /var/www/freshrss/app/views/helpers/index/normal/entry_header.phtml(43): FreshRSS_Entry->thumbnail()
#1 /var/www/freshrss/lib/Minz/View.php(88): include('/var/www/freshr...')
#2 /var/www/freshrss/lib/Minz/View.php(132): Minz_View->includeFile('/views/helpers/...')
#3 /var/www/freshrss/app/views/index/normal.phtml(71): Minz_View->renderHelper('index/normal/en...')
#4 /var/www/freshrss/lib/Minz/View.php(88): include('/var/www/freshr...')
#5 /var/www/freshrss/lib/Minz/View.php(110): Minz_View->includeFile('/views/index/no...')
#6 /var/www/freshrss/app/layout/layout.phtml(60): Minz_View->render()
#7 /var/www/freshrss/lib/Minz/View.php(88): include('/var/www/freshr...')
#8 /var/www/freshrss/lib/Minz/View.php(101): Minz_View->includeFile('/layout/layout....')
#9 /var/www/freshrss/lib/Minz/View.php(68): Minz" while reading upstream, client: 192.168.99.78, server: localhost, request: "GET /i/?a=normal&g
et=f_1455 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "192.168.99.54"
2022/02/09 16:43:39 [error] 540#540: *6758 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Return value of FreshRSS_
Entry::thumbnail() must be of the type string, array returne" while reading upstream, client: 192.168.99.78, server: localhost, request: "GET /i
/?a=normal&get=f_1457 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "192.168.99.54"
2022/02/09 16:43:39 [error] 540#540: *6758 FastCGI sent in stderr: "d in /var/www/freshrss/app/Models/Entry.php:131
Stack trace:
#0 /var/www/freshrss/app/views/helpers/index/normal/entry_header.phtml(43): FreshRSS_Entry->thumbnail()
#1 /var/www/freshrss/lib/Minz/View.php(88): include('/var/www/freshr...')
#2 /var/www/freshrss/lib/Minz/View.php(132): Minz_View->includeFile('/views/helpers/...')
#3 /var/www/freshrss/app/views/index/normal.phtml(71): Minz_View->renderHelper('index/normal/en...')
#4 /var/www/freshrss/lib/Minz/View.php(88): include('/var/www/freshr...')
#5 /var/www/freshrss/lib/Minz/View.php(110): Minz_View->includeFile('/views/index/no...')
#6 /var/www/freshrss/app/layout/layout.phtml(60): Minz_View->render()
#7 /var/www/freshrss/lib/Minz/View.php(88): include('/var/www/freshr...')
#8 /var/www/freshrss/lib/Minz/View.php(101): Minz_View->includeFile('/layout/layout....')
#9 /var/www/freshrss/lib/Minz/View.php(68): Minz" while reading upstream, client: 192.168.99.78, server: localhost, request: "GET /i/?a=normal&g
et=f_1457 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "192.168.99.54"
2022/02/09 16:43:41 [error] 540#540: *6758 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Return value of FreshRSS_
Entry::thumbnail() must be of the type string, array returned in /var/www/freshrss/app/Models/Entry.php:131
Stack trace:
#0 /var/www/freshrss/app/views/helpers/index/normal/entry_header.phtml(43): FreshRSS_Entry->thumbnail()
#1 /var/www/freshrss/lib/Minz/View.php(88): include('/var/www/freshr...')
#2 /var/www/freshrss/lib/Minz/View.php(132): Minz_View->includeFile('/views/helpers/...')
#3 /var/www/freshrss/app/views/index/normal.phtml(71): Minz_View->renderHelper('index/normal/en...')
#4 /var/www/freshrss/lib/Minz/View.php(88): include('/var/www/freshr...')
#5 /var/www/freshrss/lib/Minz/View.php(110): Minz_View->includeFile('/views/index/no...')
#6 /var/www/freshrss/app/layout/layout.phtml(60): Minz_View->render()
#7 /var/www/freshrss/lib/Minz/View.php(88): include('/var/www/freshr...')
#8 /var/www/freshrss/lib/Minz/View.php(101): Minz_View->includeFile('/layout/layout....')
#9 /var/www/freshrss/lib/Minz/View.php(68): Minz" while reading upstream, client: 192.168.99.78, server: localhost, request: "GET /i/?a=normal&g
et=f_1450 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "192.168.99.54"
2022/02/09 16:43:46 [error] 540#540: *6758 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Return value of FreshRSS_
Entry::thumbnail() must be of the type string, array returned in /var/www/freshrss/app/Models/Entry.php:131
Stack trace:
#0 /var/www/freshrss/app/views/helpers/index/normal/entry_header.phtml(43): FreshRSS_Entry->thumbnail()
#1 /var/www/freshrss/lib/Minz/View.php(88): include('/var/www/freshr...')
#2 /var/www/freshrss/lib/Minz/View.php(132): Minz_View->includeFile('/views/helpers/...')
#3 /var/www/freshrss/app/views/index/normal.phtml(71): Minz_View->renderHelper('index/normal/en...')
#4 /var/www/freshrss/lib/Minz/View.php(88): include('/var/www/freshr...')
#5 /var/www/freshrss/lib/Minz/View.php(110): Minz_View->includeFile('/views/index/no...')
#6 /var/www/freshrss/app/layout/layout.phtml(60): Minz_View->render()
#7 /var/www/freshrss/lib/Minz/View.php(88): include('/var/www/freshr...')
#8 /var/www/freshrss/lib/Minz/View.php(101): Minz_View->includeFile('/layout/layout....')
#9 /var/www/freshrss/lib/Minz/View.php(68): Minz" while reading upstream, client: 192.168.99.78, server: localhost, request: "GET /i/?a=normal&g
et=c_36 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "192.168.99.54"
2022/02/09 16:43:50 [error] 540#540: *6756 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Return value of FreshRSS_
Entry::thumbnail() must be of the type string, array returned in /var/www/freshrss/app/Models/Entry.php:131
Stack trace:
#0 /var/www/freshrss/app/views/helpers/index/normal/entry_header.phtml(43): FreshRSS_Entry->thumbnail()
#1 /var/www/freshrss/lib/Minz/View.php(88): include('/var/www/freshr...')
#2 /var/www/freshrss/lib/Minz/View.php(132): Minz_View->includeFile('/views/helpers/...')
#3 /var/www/freshrss/app/views/index/normal.phtml(71): Minz_View->renderHelper('index/normal/en...')
#4 /var/www/freshrss/lib/Minz/View.php(88): include('/var/www/freshr...')
#5 /var/www/freshrss/lib/Minz/View.php(110): Minz_View->includeFile('/views/index/no...')
#6 /var/www/freshrss/app/layout/layout.phtml(60): Minz_View->render()
#7 /var/www/freshrss/lib/Minz/View.php(88): include('/var/www/freshr...')
#8 /var/www/freshrss/lib/Minz/View.php(101): Minz_View->includeFile('/layout/layout....')
#9 /var/www/freshrss/lib/Minz/View.php(68): Minz" while reading upstream, client: 192.168.99.78, server: localhost, request: "GET /i/?a=normal&g
et=f_1431 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "192.168.99.54"
2022/02/09 16:43:52 [error] 540#540: *6756 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Return value of FreshRSS_
Entry::thumbnail() must be of the type string, array returned in /var/www/freshrss/app/Models/Entry.php:131
Stack trace:
#0 /var/www/freshrss/app/views/helpers/index/normal/entry_header.phtml(43): FreshRSS_Entry->thumbnail()
#1 /var/www/freshrss/lib/Minz/View.php(88): include('/var/www/freshr...')
#2 /var/www/freshrss/lib/Minz/View.php(132): Minz_View->includeFile('/views/helpers/...')
#3 /var/www/freshrss/app/views/index/normal.phtml(71): Minz_View->renderHelper('index/normal/en...')
#4 /var/www/freshrss/lib/Minz/View.php(88): include('/var/www/freshr...')
#5 /var/www/freshrss/lib/Minz/View.php(110): Minz_View->includeFile('/views/index/no...')
#6 /var/www/freshrss/app/layout/layout.phtml(60): Minz_View->render()
#7 /var/www/freshrss/lib/Minz/View.php(88): include('/var/www/freshr...')
#8 /var/www/freshrss/lib/Minz/View.php(101): Minz_View->includeFile('/layout/layout....')
#9 /var/www/freshrss/lib/Minz/View.php(68): Minz" while reading upstream, client: 192.168.99.78, server: localhost, request: "GET /i/?a=normal&g
et=f_1432 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "192.168.99.54"
2022/02/09 16:43:55 [error] 540#540: *6756 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Return value of FreshRSS_
Entry::thumbnail() must be of the type string, array returned in /var/www/freshrss/app/Models/Entry.php:131
Stack trace:
#0 /var/www/freshrss/app/views/helpers/index/normal/entry_header.phtml(43): FreshRSS_Entry->thumbnail()
#1 /var/www/freshrss/lib/Minz/View.php(88): include('/var/www/freshr...')
#2 /var/www/freshrss/lib/Minz/View.php(132): Minz_View->includeFile('/views/helpers/...')
#3 /var/www/freshrss/app/views/index/normal.phtml(71): Minz_View->renderHelper('index/normal/en...')
#4 /var/www/freshrss/lib/Minz/View.php(88): include('/var/www/freshr...')
#5 /var/www/freshrss/lib/Minz/View.php(110): Minz_View->includeFile('/views/index/no...')
#6 /var/www/freshrss/app/layout/layout.phtml(60): Minz_View->render()
#7 /var/www/freshrss/lib/Minz/View.php(88): include('/var/www/freshr...')
#8 /var/www/freshrss/lib/Minz/View.php(101): Minz_View->includeFile('/layout/layout....')
#9 /var/www/freshrss/lib/Minz/View.php(68): Minz" while reading upstream, client: 192.168.99.78, server: localhost, request: "GET /i/?a=normal&g
et=f_1431 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "192.168.99.54"
2022/02/09 16:43:59 [error] 540#540: *6756 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Return value of FreshRSS_
Entry::thumbnail() must be of the type string, array returned in /var/www/freshrss/app/Models/Entry.php:131
Stack trace:
#0 /var/www/freshrss/app/views/helpers/index/normal/entry_header.phtml(43): FreshRSS_Entry->thumbnail()
#1 /var/www/freshrss/lib/Minz/View.php(88): include('/var/www/freshr...')
#2 /var/www/freshrss/lib/Minz/View.php(132): Minz_View->includeFile('/views/helpers/...')
#3 /var/www/freshrss/app/views/index/normal.phtml(71): Minz_View->renderHelper('index/normal/en...')
#4 /var/www/freshrss/lib/Minz/View.php(88): include('/var/www/freshr...')
#5 /var/www/freshrss/lib/Minz/View.php(110): Minz_View->includeFile('/views/index/no...')
#6 /var/www/freshrss/app/layout/layout.phtml(60): Minz_View->render()
#7 /var/www/freshrss/lib/Minz/View.php(88): include('/var/www/freshr...')
#8 /var/www/freshrss/lib/Minz/View.php(101): Minz_View->includeFile('/layout/layout....')
#9 /var/www/freshrss/lib/Minz/View.php(68): Minz" while reading upstream, client: 192.168.99.78, server: localhost, request: "GET /i/?a=normal&g
et=f_1432 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "192.168.99.54"
2022/02/09 16:44:03 [error] 540#540: *6756 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Return value of FreshRSS_
Entry::thumbnail() must be of the type string, array returned in /var/www/freshrss/app/Models/Entry.php:131
Stack trace:
#0 /var/www/freshrss/app/views/helpers/index/normal/entry_header.phtml(43): FreshRSS_Entry->thumbnail()
#1 /var/www/freshrss/lib/Minz/View.php(88): include('/var/www/freshr...')
#2 /var/www/freshrss/lib/Minz/View.php(132): Minz_View->includeFile('/views/helpers/...')
#3 /var/www/freshrss/app/views/index/normal.phtml(71): Minz_View->renderHelper('index/normal/en...')
#4 /var/www/freshrss/lib/Minz/View.php(88): include('/var/www/freshr...')
#5 /var/www/freshrss/lib/Minz/View.php(110): Minz_View->includeFile('/views/index/no...')
#6 /var/www/freshrss/app/layout/layout.phtml(60): Minz_View->render()
#7 /var/www/freshrss/lib/Minz/View.php(88): include('/var/www/freshr...')
#8 /var/www/freshrss/lib/Minz/View.php(101): Minz_View->includeFile('/layout/layout....')
#9 /var/www/freshrss/lib/Minz/View.php(68): Minz" while reading upstream, client: 192.168.99.78, server: localhost, request: "GET /i/?a=normal&g
et=f_1431 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "192.168.99.54"
```

**Comment by math-GH** [comment]
I had that error too. Something is broken there and I had to reinstall my instance. I thought that I broke it.

You can see in the first screenshots, that the title and date of the article is not shown anymore, because the error appears while fetching the article.
You would see the error in the frontend, when you switch from production mode to development mode (data/config.php)

**Comment by Alkarex** [comment]
Fix coming

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/4216

**Comment by Alkarex** [comment]
Please update your edge branch and report

**Comment by WillPresley** [comment]
@Alkarex Updated edge, and it's all working well again! Thank you for the fix. Sorry to have not been around there to give logs, day-job took over.

**Comment by Alkarex** [comment]
Thanks for the feedback. It is very valuable to have tests of the edge branch with various configurations

**Comment by quella** [comment]
Sorry for the delay in my reply as well...  Work always gets in the way.  Things are back to normal once again after an update!  Thank you all.
