### ISSUE TITLE
[BUG] Long list of items for a category getting cut off in folder tree when filtering for a specific feed

### ISSUE THREAD

**Issue by Poorchop** [FreshRSS/FreshRSS#4217]
**Describe the bug**
When clicking the website/favicon in the main view in order to filter for a specific feed, a long list of feeds will be partially obscured beneath other folder items in the category tree. This only happens when the category is automatically expanded after filtering for a feed. It does not happen when manually expanding a category by clicking the dropdown toggle.

**To Reproduce**
1. Create a category with a very large number of feeds. I have 171 feeds in the category in question, so ~170 feeds should suffice. Name this category something like “A” so that it appears above other categories in the category tree.
2. Ensure that you have other categories that appear below the aforementioned category, i.e. “B”, “C”, “D”, etc.
3. Navigate to the main stream view. Click on a website title or favicon for one of the feeds so that it is filtered.
4. Category “A” will automatically expand in the category tree. A number of feeds will be obscured by categories “B”, “C”, “D”, ...

**Expected behavior**
The behavior should be the same as manually expanding a specific category by clicking on the dropdown toggle—all feeds for category “A” should be visible.

**Environment information (please complete the following information):**
- OS: OpenBSD 7.0 (happened in 6.9 as well)
- Browser: Firefox 97 (happened in earlier releases)
- FreshRSS version: 1.19.2 (bug occurred in earlier releases)
- Database version: postgres (PostgreSQL) 13.5
- PHP version: 8.0.14
- Installation type: Originally cloned from GitHub and updated several times using the built-in updater in the web interface

**Additional context**
The problem seems to stem entirely from [this line of CSS](https://github.com/FreshRSS/FreshRSS/blob/133e0d61db4d316806686243e735961166113e1c/p/themes/base-theme/template.css#L651). I'm not sure why this rule exists at all since deleting it doesn't cause any adverse issues while fixing the problem described here.

When manually clicking the dropdown toggle, an inline `max-height` rule is applied in order to accommodate the large number of items in the category. This rule appears to be calculated and it works fine, but it does not get applied when the category is automatically expanded by filtering for a specific feed. Perhaps this is because [this code](https://github.com/FreshRSS/FreshRSS/blob/dfee46792f91cc357f697f35e7429c0c196f6a16/p/scripts/main.js#L801) does not get executed when filtering for a feed, only when clicking the dropdown toggle?

**Comment by math-GH** [comment]
Could you support us with a screen shot and which theme you use?

**Comment by math-GH** [comment]
And could you support us with a OPML export? I would help us to create a 150+ feeds category ;)

**Comment by Poorchop** [comment]
It's going to take me some time especially since I'll have to edit the OPML file to remove anything that might be potentially controversial, but I'll try to post something when I can find some time.

**Comment by Poorchop** [comment]
I'm going to need some more time to prepare the OPML file but I am attaching screenshots in the meantime. The first screenshot shows the bug in action—I have filtered for a blog, which automatically expanded the “Blogs” category but causes part of it to be obscured by the other pictured categories. The rest of the blogs category continues uninterrupted beneath the “Videos” category.

<img width="289" alt="screen1" src="https://user-images.githubusercontent.com/5256208/153984425-66e84c36-9382-4e33-9d63-54a287230ca6.png">

The second screenshot shows what the “Blogs” category looks like when I manually click the dropdown arrow. The category items are not obscured by the other categories, which correctly appear below the last item in “Blogs”.

<img width="289" alt="screen2" src="https://user-images.githubusercontent.com/5256208/153984599-f411a444-76fd-412e-921a-04629178385c.png">

I am using the Alternative Dark theme with some custom CSS. I disabled the custom CSS extension and I tried the Origine and Origine-compact themes, but the bug is present in spite of the theme used.

**Comment by math-GH** [comment]
@Poorchop Could you please give us an update?

In the last month a new feature was implemented in V1.20.0-dev: #4347 Please check if it solves your issue

**Comment by Poorchop** [comment]
Sorry that I haven't provided an OPML file yet. I had this on the agenda but I just haven't found the time to manually prepare the file. I also don't know if I quite have the resources to set up the developer release on my server.

Looking at the patch however, it doesn't seem to address the issue. This seems to purely be a client-side issue with the line I mentioned above not getting executed under this one circumstance. It's just a bit hard to prepare the file because there are some feeds that I would like to keep private but I'm also not sure how many feeds I can safely remove to still allow the bug to be replicated.

**Comment by Alkarex** [comment]
Here is an example of long OPML with fake feeds. I cannot reproduce the problem
[long.opml.xml.zip](https://github.com/FreshRSS/FreshRSS/files/9228698/long.opml.xml.zip)

**Comment by Poorchop** [comment]
That feed list doesn't replicate the environment that leads to this bug because it only has one legitimate feed so only one category appears on the side bar.

I found a [long list of feeds](http://www.superkuh.com/2022-04-27-feedlist.opml) that you can try. I tried creating a test user to import these feeds but it crashed my database and used up all of my remaining disk space, so I can't actually test this file. It looks like "Computing but not spammy" has enough feeds to reproduce.

Import the OPML, then in the main feed stream, click on the favicon for one of the feeds that is categorized under "Computing but not spammy." Hopefully that will reproduce the problem.

**Comment by Alkarex** [comment]
Indeed @Poorchop , your fix seems fine https://github.com/FreshRSS/FreshRSS/pull/4502
More tests welcome
