### ISSUE TITLE
[BUG] actualize_script.php introuvable sous synology

### ISSUE THREAD

**Issue by widowild1** [FreshRSS/FreshRSS#4222]
Bonjour,
J’utilise freshrss avec docker sous synology DSM 7.0.1. J’aimerai bien ajouter une synchronisation de mes flux RSS mais je ne trouve pas le fichier actualize_script.php, mise à part des dossiers de btrfs comme dans l’image, 
![1FAA0C0E-8F32-436B-BC09-F0879334755C](https://user-images.githubusercontent.com/11516275/154127389-7cdcb55f-99b6-458d-a0a5-d174a9eaded5.png)
Je n’ai pas trop d’idée pour arriver à mes fins.
cordialement.

**Comment by Frenzie** [comment]
The Docker image should do it by itself. You didn't say which Docker image you're using though? From the image's perspective it'll be in `/var/www/FreshRSS/app/actualize_script.php`.

**Comment by widowild1** [comment]
Docker: https://hub.docker.com/r/freshrss/freshrss/

I followed the tutorial:

https://lofurol.fr/joomla/logiciels-libres/304-nas-syno-installation-de-l-application-de-freshrss

And

https://zatoufly.fr/installer-freshrss-avec-docker/
![B8327365-269D-4E7D-B59E-F11F6D5CE683](https://user-images.githubusercontent.com/11516275/154164026-65b42860-7c03-46a2-abf6-58beaf471e75.jpeg)
![68FD24AF-F648-47C8-9301-5E2496936FBB](https://user-images.githubusercontent.com/11516275/154164274-2b82f698-b1be-4971-ab37-92c0f295e151.jpeg)
![3205296C-7494-481E-B7C3-A32475A52212](https://user-images.githubusercontent.com/11516275/154164284-eb4090f2-503b-41f9-9b7d-23fb9821161c.jpeg)

**Comment by Frenzie** [comment]
Please see https://github.com/FreshRSS/FreshRSS/blob/9dbbe924c5e54b5dbe486873a9b31a28127c8e62/Docker/README.md#cron-job-to-automatically-refresh-feeds

**Comment by widowild1** [comment]
Thanks you frenzie.

**Comment by math-GH** [comment]
@widowild1 is it still an issue?

**Comment by math-GH** [comment]
@widowild1 is it still an issue with the current 1.22.1?
