### ISSUE TITLE
[BUG] Docker container on raspberry pi: having an issue to sync system date/time

### ISSUE THREAD

**Issue by st406** [FreshRSS/FreshRSS#4225]
**Describe the bug**
Docker container on raspberry pi (freshrss/freshrss:arm) having an issue to sync system date/time

**Environment information (please complete the following information):**
- Docker version 18.09.1, build 4c52b90
- OS: Raspbian GNU/Linux 10 (buster)
- FreshRSS version: [e.g. 1.19.2]

**Comment by Alkarex** [comment]
Hello,
Maybe a duplicate of https://github.com/FreshRSS/FreshRSS/issues/4198
Easiest solution: update your Raspbian / kernel to current version

**Comment by math-GH** [comment]
@st406 Is it still an issue with 1.19.2 or 1.20.0-dev?
