### ISSUE TITLE
Cron for "actualizing" RSS feeds shows nothing after Results: and does not update feeds on Synology

### ISSUE THREAD

**Issue by AdFisch** [FreshRSS/FreshRSS#4230]
Hello everyone,

I am new to FreshRSS (thanks for this awesome piece of software!) and finally got it set up on my Synology NAS. The only thing that just does not want to work is the automatic feed update using a cron job. Any help would be much appreciated! :-)

Here is some background information:

- FreshRSS 1.19.2 is installed on Synology's Web Station (not in a Docker).
- It runs on a virtual host with Apache 2.4 and PHP 7.4.
- There is a custom PHP profile in place to provide the required modules (and also restrict not required functions etc.).
- It is connected to the Maria DB 10 packet.
- For web access, htpasswd as well as user level protection is enabled.
- Feed updates work perfectly when initiated using the web interface.

Using Synology's task scheduler, the following script is run every hour by an admin user with sufficient R/W capabilities:

```
#!/bin/bash
PHP_INI_SCAN_DIR=.:/usr/local/etc/php74/:/var/packages/WebStation/etc/php_profile/<PROFILE_ID>/conf.d/
export PHP_INI_SCAN_DIR
php74 /<PATH_TO_FRESHRSS>/app/actualize_script.php >> /<PATH_TO_FRESHRSS>/cron/cron.log 2>&1
```

Although the script is executed, feeds are not updated. The output log shows the following information:

```
FreshRSS starting feeds actualization at 2022-02-22T22:08:56+00:00
Results: 
```

Does anyone have an idea why the updates do not work? Thank you very much in advance!

**Comment by Frenzie** [comment]
Note that feeds won't update more than once every half hour or so by default to prevent DDOSing a server.

**Comment by AdFisch** [comment]
Hi Frenzie, thanks for your feedback. The feeds had not been updated for longer, thus there should have been results.

**Comment by math-GH** [comment]
is it similar with #4222 ?

**Comment by AdFisch** [comment]
Hey everyone,
thanks for your help. It seems to work now and probably was to the DDOS protection (so Frenzie was right). At the beginning I could not tell because some articles are missing. But it seems they are reliably read now. Thanks again and sorry for any inconveniences!
