### ISSUE TITLE
[BUG] Config "Clicking outside of article text area closes the article" makes JavaScript error

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#4231]
**Describe the bug**
If "Clicking outside of article text area closes the article" is enabled
![grafik](https://user-images.githubusercontent.com/1645099/155408627-e3c11b9c-db0d-494b-9202-4e90536024d3.png)

and the user clicks in the reading view on the area left or right of the article, than a error message in the console appears
![grafik](https://user-images.githubusercontent.com/1645099/155408765-13d8b8a2-7761-4b5d-960a-ddd05e32f475.png)

If user clicks on the not-first (f.e. second or third) article left/right area, than the article "jumps" to the top of screen
![grafik](https://user-images.githubusercontent.com/1645099/155410170-f5e613b1-2c29-4a84-be56-3ceeded02d5b.png)

**Expected behavior**
option "Clicking outside of article text area closes the article" has no effect on reading view

**Environment information (please complete the following information):**
- Browser: Firefox 97
- FreshRSS version: 1.20.0-dev

**Comment by aidistan** [comment]
I found it still closes the article even if I uncheck the config on the edge version. Does this relate to this issue? Is there a PR draft working on fixing this config?

**Comment by math-GH** [comment]
> I found it still closes the article even if I uncheck the config on the edge version. Does this relate to this issue? Is there a PR draft working on fixing this config?

It is still an issue.

**Comment by aidistan** [comment]
@math-GH #4541 fix both issues, please refer to its comment

**Comment by math-GH** [comment]
Sorry, it was my fault. I had not the newest `edge`. It works fine now.
