### ISSUE TITLE
Coding STYLE PHP PSR-12

### ISSUE THREAD

**Issue by ColonelMoutarde** [FreshRSS/FreshRSS#4233]
For a unification of the style in the coding, the FIG has proposed for many years the PSR-1, then the PSR-2 and finally the PSR-12. I suggest changing the coding style to match the PSR-12 standards. FIG is commonly used in the PHP industry. 

Here are the rules to follow https://www.php-fig.org/psr/psr-12/

So modern IDEs are apparently comfortable with the PSR rules

**Comment by math-GH** [comment]
How is the status right now?
How far is the current code away from PSR-12?
What is the benefit to invest time?

**Comment by Frenzie** [comment]
Hard no. You don't mess with commit history for the sake of personal preference.

**Comment by ColonelMoutarde** [comment]
Hello,
The psr conventions are easy to set up. They also allow new contributors to focus on their code and less on the form.

**Comment by Frenzie** [comment]
There's an https://editorconfig.org/ configuration and automated style checking tools (phpcs). No one ever needs to worry about form. [Here](https://three29.com/set-up-php-codesniffer-in-visual-studio-code/)'s a random tutorial for how to set up phpcs in VS Code.


<kbd><img src=https://user-images.githubusercontent.com/202757/155860329-85e6b126-abf0-4dc8-a945-95123f439e13.png width=45%><img src=https://user-images.githubusercontent.com/202757/155860328-0ca52d09-b16b-4888-976e-f2772f5f90f6.png width=45%></kbd>

**Comment by Alkarex** [comment]
Indeed, we have explicit definitions for consistency that can be automatically picked-up by most modern editors.
* https://github.com/FreshRSS/FreshRSS/blob/edge/.editorconfig
* https://github.com/FreshRSS/FreshRSS/blob/edge/phpcs.xml
* And other similar files for our JS, CSS, etc.

While it would make sense for a new project, I would see such reformatting more as negative than positive.
