### ISSUE TITLE
[BUG] Upgrading from 1.18.1 to 1.19.2 from admin interface indicated success (no errors) which was misleading because PHP code was not updated in place which resulted in various write failures

### ISSUE THREAD

**Issue by posita** [FreshRSS/FreshRSS#4242]
I used the admin interface to upgrade my installation.

Marking posts or feeds as read produces no user error, but has no effect. Upon refreshing any page, the item(s) marked as read appear as unread. I am seeing a ton of these in the logs:

`SQL error markRead: Prepared statement needs to be re-prepared`

_UPDATE: Feed updates don't work either. This is the second of two attempts that my upgrading through the admin interface has bricked my installation (i.e., while my sample size is very small, upgrading has rendered my installation unusable 100% of the time, but presented no error). Are upgrades tested?_

**Comment by posita** [comment]
I'm also seeing these:

```
2022-03-01 05:36:48
SQL error updateTTL 2: Duplicate column name 'ttl' ALTER TABLE `_feed` ADD COLUMN ttl INT NOT NULL DEFAULT 0
2022-03-01 05:36:48
SQL warning updateTTL 1: Prepared statement needs to be re-prepared UPDATE `_feed` SET ttl=:new_value WHERE ttl=:old_value
…
2022-03-01 05:30:15
SQL error updateFeed: Prepared statement needs to be re-prepared for feed 11
2022-03-01 05:30:15
SQL error updateLastUpdate: Prepared statement needs to be re-prepared
2022-03-01 05:30:15
SQL error updateLastSeen: HY000: 1615 Prepared statement needs to be re-prepared while updating feed 11
2022-03-01 05:30:15
SQL error updateEntry: HY000: 1615 Prepared statement needs to be re-prepared while updating entry with GUID … in feed 11
2022-03-01 05:30:15
SQL error updateEntry: HY000: 1615 Prepared statement needs to be re-prepared while updating entry with GUID … in feed 11
…
```

**Comment by math-GH** [comment]
Please give us more information about your setup:

**Environment information (please complete the following information):**
- Device: [e.g. iPhone6]
- OS: [e.g. Ubuntu 20.04]
- Browser: [e.g. Firefox 86]
- FreshRSS version: [e.g. 1.17.1]
- Database version: [e.g. Mysql 5.7]
- PHP version: [e.g. PHP 7.4]
- Installation type: [e.g. Yunohost]

**Comment by Alkarex** [comment]
> Are upgrades tested?

In addition to the developers' own testing, there is a call to test release candidates, e.g. https://github.com/FreshRSS/FreshRSS/issues/4179
This is when you are welcome to give it a try a report for any problem with your own setup

**Comment by posita** [comment]
Client Device: MBP
Client OS: OS X 11.6.4
Server Device: Hosted (DreamHost)
Server OS: `uname -a` -> `Linux … 4.14.117-grsec-grsec+ #1 SMP Fri May 10 17:15:47 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux`
Browser: Version 1.35.101 Chromium: 98.0.4758.87 (Official Build) (x86_64)
FreshRSS version: 1.18.1 -> 1.19.2
Database version: MySQL 8.0.26-0ubuntu0.20.04.2
PHP version: 7.4.15
Installation type: tar file (admin interface upgrade "finished" without error)

**Comment by Alkarex** [comment]
@posita What database is that? MySQL?

**Comment by posita** [comment]
> @posita What database is that? MySQL?

Yup! Sorry. (Fixed.)

I was able to restore functionality by grabbing the latest 1.19.2 tar file, unpacking on my hosting provider, moving my `data` folder over and pointing my domain at the new folder. Does upgrading via the admin interface not also upgrade the code in place? I'm super confused. The admin interface provided zero errors (and indicated the upgrade was successful.) Does upgrading from the admin interface not also update the code? If it's supposed to, why weren't there any errors? Are there no pre-flight checks to ensure code can safely be moved into place after being downloaded? (I'm making a lot of assumptions here about how upgrading works.)

How could it have upgraded my data model without also updating the corresponding PHP? How can I verify whether my data model has been successfully upgraded?

**Comment by Alkarex** [comment]
There has been no change of data model between 1.18.1 and 1.19.2.
The Web+ZIP update method is the least robust of several options we are offering (e.g. built-in Web+git, Docker).

I have just tried with *MySQL Ver 8.0.28 for Linux on x86_64 (MySQL Community Server - GPL)* with no apparent problem.
There might be more info in some Web server logs / FreshRSS logs for finding the root cause.

We offer an export from all supported databases to SQLite, and import again to any supported database, which is mostly for making backups, but which is also useful to reconstruct the database for a given user if it has been corrupted for some reason.

Good that you found a solution.

**Comment by posita** [comment]
To be precise, I found a _work-around_, not a solution. The issue (which I renamed) is that the admin interface indicated success when the upgrade _wasn't_ successful. That's the bug, which is still present. (I've seen it twice, now.)

> We offer an export from all supported databases to SQLite, and import again to any supported database, which is mostly for making backups, but which is also useful to reconstruct the database for a given user if it has been corrupted for some reason.

Maybe this feature should be exposed in the admin upgrade path? (I.E., present the user with an option to export prior to attempting to upgrade?)

**Comment by posita** [comment]
> The Web+ZIP update method is the least robust of several options we are offering (e.g. built-in Web+git, Docker).

If you can't make it robust, then don't offer it? Consider removing the feature from the admin console if it doesn't work reliably, and instead pointing admins to preferred mechanisms. Otherwise, it's just holding itself out there as the easiest viable option to end users. Some users may not even know or remember there are other (better) options.

**Comment by Frenzie** [comment]
For the record, I've been using that method for about 8 years now.

**Comment by Frenzie** [comment]
It's very strange that it would indicate success (or even get started in the first place if it's a permissions issue). In all my testing it's always properly failed when permissions were wrong, so I'm not immediately sure where to start looking.

Is it possible that disk space was near capacity?

**Comment by posita** [comment]
> For the record, I've been using that method for about 8 years now.

Apologies. I'm merely going off of @Alkarex's assertion that the Web+ZIP update method was the least robust, which reflects my own experience.

Regarding disk space, there are 300+ GB available, so probably not that. My guess is that it's most likely a permissions issue, but the update interface presented no indication of any failure. (In fact, it said the upgrade was successful.)

**Comment by Frenzie** [comment]
A quick glance at the upgrade controller suggests that in advance it only checks permissions on the installation directory without also recursively looking at the subdirectories (or in any case PUBLIC_PATH, LIB_PATH and APP_PATH) when it tells you everything is good to go. I don't think that should affect what happens later on though. We'll need to play around a bit with upgrading while putting in place some weird permissions on relevant subdirectories to make doubly sure I suppose.

https://github.com/FreshRSS/FreshRSS/blob/b127777887969617ed8358912876af962edde139/app/Controllers/updateController.php#L121-L134

**Comment by posita** [comment]
I'm now seeing these pretty regularly (I haven't touched the install at all since my repair of the upgrade several days ago):

```
[Fri, 04 Mar 2022 04:55:05 -0800] [error] --- SQL error listCategories: ["HY000",1615,"Prepared statement needs to be re-prepared"]
[Fri, 04 Mar 2022 04:55:05 -0800] [error] --- SQL error listCategories: ["HY000",1615,"Prepared statement needs to be re-prepared"]
[Fri, 04 Mar 2022 04:55:05 -0800] [error] --- SQL error listCategories: ["HY000",1615,"Prepared statement needs to be re-prepared"]
[Fri, 04 Mar 2022 04:55:05 -0800] [error] --- SQL error listTags: Prepared statement needs to be re-prepared
[Fri, 04 Mar 2022 04:55:05 -0800] [error] --- SQL error listWhereRaw: Prepared statement needs to be re-prepared
[Fri, 04 Mar 2022 04:55:20 -0800] [error] --- SQL warning updateTTL 1: Prepared statement needs to be re-prepared UPDATE `_feed` SET ttl=:new_value WHERE ttl=:old_value
[Fri, 04 Mar 2022 04:55:20 -0800] [error] --- SQL error updateTTL 2: Duplicate column name 'ttl' ALTER TABLE `_feed` ADD COLUMN ttl INT NOT NULL DEFAULT 0
[Fri, 04 Mar 2022 04:55:21 -0800] [error] --- SQL error updateLastUpdate: Prepared statement needs to be re-prepared
[Fri, 04 Mar 2022 04:55:22 -0800] [error] --- SQL error updateLastUpdate: Prepared statement needs to be re-prepared
[Fri, 04 Mar 2022 04:55:22 -0800] [error] --- SQL error updateLastUpdate: Prepared statement needs to be re-prepared
[Fri, 04 Mar 2022 04:55:22 -0800] [error] --- SQL error updateLastUpdate: Prepared statement needs to be re-prepared
[Fri, 04 Mar 2022 04:55:22 -0800] [error] --- SQL error updateLastUpdate: Prepared statement needs to be re-prepared
[Fri, 04 Mar 2022 04:55:22 -0800] [error] --- SQL error updateLastUpdate: Prepared statement needs to be re-prepared
[Fri, 04 Mar 2022 04:57:53 -0800] [error] --- SQL error markRead: Prepared statement needs to be re-prepared
[Fri, 04 Mar 2022 04:57:54 -0800] [error] --- SQL error markRead: Prepared statement needs to be re-prepared
[Fri, 04 Mar 2022 04:57:58 -0800] [error] --- SQL error markRead: Prepared statement needs to be re-prepared
[Fri, 04 Mar 2022 04:58:12 -0800] [error] --- SQL error markRead: Prepared statement needs to be re-prepared
[Fri, 04 Mar 2022 04:58:14 -0800] [error] --- SQL error markRead: Prepared statement needs to be re-prepared
[Fri, 04 Mar 2022 04:58:39 -0800] [error] --- SQL error markRead: Prepared statement needs to be re-prepared
```

> A quick glance at the upgrade controller suggests that in advance it only checks permissions on the installation directory without also recursively looking at the subdirectories (or in any case PUBLIC_PATH, LIB_PATH and APP_PATH) when it tells you everything is good to go. I don't think that should affect what happens later on though. We'll need to play around a bit with upgrading while putting in place some weird permissions on relevant subdirectories to make doubly sure I suppose.

Should this be reopened (or another issue filed)?

**Comment by Frenzie** [comment]
No need, see https://github.com/FreshRSS/FreshRSS/discussions/4251
