### ISSUE TITLE
[BUG] XPath Web Scraping: Tags

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#4245]
I try to scrap the GitHub issues:
![grafik](https://user-images.githubusercontent.com/1645099/156221055-46d58ec4-6d52-400f-a48f-55b0607699a7.png)

XPath for: feed title `"FreshRSS issues"`

XPath for: finding news items: `//div[contains(concat(' ', @class, ' '), 'js-issue-row')]`

XPath (relative to item) for: item title: `descendant::a[contains(concat(' ', @class, ' '), 'h4')]`

XPath (relative to item) for: item content: `descendant::a[contains(concat(' ', @class, ' '), 'Link--muted')]/span[contains(concat(' ', @class, ' '), 'text-small')]`

XPath (relative to item) for: item link (URL): `descendant::a/@href`

Thumbnail: empty

XPath (relative to item) for: item author: `descendant::div[@data-hovercard-type="user"]`

XPath (relative to item) for: item date: `descendant::relative-time/@datetime` (does not work)

XPath (relative to item) for: items tags: `descendant::a[contains(concat(' ', @class, ' '), 'IssueLabel')]`

I guess that the tags are not correct working:
![grafik](https://user-images.githubusercontent.com/1645099/156221113-20d9dfc9-9b21-477a-a889-606e18f10a89.png)

XPath (relative to item) for: items tags: `descendant::a[contains(concat(' ', @class, ' '), 'IssueLabel')]`

Each FreshRSS article has the same tags (usually only 1 tag is assigned)
![grafik](https://user-images.githubusercontent.com/1645099/156221239-1d0360be-73fa-4740-9600-4309a03085a8.png)

Expected:
- the correct tag is assigned to the correct article (mostly 0 or 1 tag)

**Environment information:**
- FreshRSS version: 1.20.0 (incl. #4220)

**Comment by Frenzie** [comment]
See https://stackoverflow.com/questions/1390568/how-can-i-match-on-an-attribute-that-contains-a-certain-string/1390680#1390680 since I wrote that one from memory and it seemed to work in that specific scenario.

**Comment by math-GH** [comment]
I guess it is a variable that needs a reset after scraping each item. Or it scraps not relative to the content:

![grafik](https://user-images.githubusercontent.com/1645099/156233972-9e686400-fda2-466f-87dc-38ce9742b10f.png)

![grafik](https://user-images.githubusercontent.com/1645099/156233988-818fcc61-e00f-4f7c-adda-798739f68969.png)

**Comment by Frenzie** [comment]
A quick search gave me this tool which could be *very* helpful to get results faster.

https://css2xpath.github.io/

**Comment by Alkarex** [comment]
Please try this fix https://github.com/FreshRSS/FreshRSS/pull/4246

**Comment by Alkarex** [comment]
And thanks for the good tests 👍🏻
