### ISSUE TITLE
[BUG] XPath: empty Thumbnail

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#4248]
The thumbnail setting is empty:
![grafik](https://user-images.githubusercontent.com/1645099/156426202-1c324721-33bd-4841-b185-8443b5c1f698.png)

But the thumbnail is broken
![grafik](https://user-images.githubusercontent.com/1645099/156426131-45706a9b-ca3b-4ba6-9cfe-6071d9330d92.png)

because the base URL is used, also when there is no image
![grafik](https://user-images.githubusercontent.com/1645099/156426376-86fef12e-7b7c-456e-bdb8-423a1737e76d.png)

Display the thumbnails:
![grafik](https://user-images.githubusercontent.com/1645099/156426765-ce555753-fd94-4597-a020-73fdcf62579c.png)

**To Reproduce**
1. All settings see: #4245
2. see the thumbnail in normal view

**Expected behavior**
No thumbnail image

**Environment information:**
- FreshRSS version: 1.20.0-dev

**Comment by Alkarex** [comment]
Good catch! Please try https://github.com/FreshRSS/FreshRSS/pull/4250
