### ISSUE TITLE
[BUG] Article CSS selector: respect base URL

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#4252]
When the content of article via CSS selector is crawled, than it does not respect the `<base>` URL for included images.

**To Reproduce**
(maybe there is a better example page but I found this issue with this steps)

1. Crawl the page (configs: https://yopad.eu/p/xpath-365days) via XPath (it will scrap also the correct thumbnail!)
2. (feed configuration) set the article CSS selector to `.newsSingle`
3. (feed configuration) reload articles (see button in the configuration)
4. go to normal view

![grafik](https://user-images.githubusercontent.com/1645099/156648595-f31c3ec3-b125-4044-be99-150b49efc91f.png)

**the technical issue**
image `src` = URL +relative path (wrong)
image `src` = base URL +relative path (correct)

**Expected behavior**
thumbnail and image is shown

**Environment information (please complete the following information):**
- FreshRSS version: 1.20.0

**Comment by Alkarex** [comment]
Please check https://github.com/FreshRSS/FreshRSS/pull/4260

**Comment by Alkarex** [comment]
Superseded by https://github.com/FreshRSS/FreshRSS/pull/4261
