### ISSUE TITLE
[BUG] Path scrapping: title

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#4253]
from: https://github.com/FreshRSS/FreshRSS/pull/4220#issuecomment-1049134469

the XPath for feed title is used only once: when the feed is added new to the system.

When the feed config is changed it does not have any affect on the title anymore
![grafik](https://user-images.githubusercontent.com/1645099/155393213-81165a97-fc95-4953-a5d8-5bd5a7e74555.png)

**Comment by math-GH** [comment]
I would delete this input in the feed settings.

And would replace the `<textarea>` with a simple `<input>` without any XPath magic

![grafik](https://user-images.githubusercontent.com/1645099/156650478-cb7c3252-d044-4f1d-9ed7-0d9c9297b6a0.png)

**Comment by Alkarex** [comment]
@math-GH I like the XPath title when adding a feed, but I agree that it does not make much sense to keep it in the subscription update view, so I have removed it from there https://github.com/FreshRSS/FreshRSS/pull/4259

**Comment by Frenzie** [comment]
@Alkarex Maybe prefill it with `//title` or make it so that clicking on it fills the box with the example or something?

**Comment by Alkarex** [comment]
> Maybe prefill it with `//title` or make it so that clicking on it fills the box with the example or something?

@Frenzie Done https://github.com/FreshRSS/FreshRSS/pull/4259/commits/7efb6511a761756cfa9ad1145308d19f692cb4c4
