### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by seoconsultant** [FreshRSS/FreshRSS#4264]
Am getting this issue after installation
Error during context user init!
please how to resolve it?
and furthermore, I want to reinstall it but using the ./usr/share/ folder am contacting my HOST to provide a directory path as I cannot find it on my server, I feel installing both the files in the same folder is an issue for installation error? Please advise, thanks.

**Comment by math-GH** [comment]
Could you please use the bug template to give us needed information (f.e. screenshots, steps, environment information)?
The template appeared when you started to write a bug issue.

The template

```
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '…'
2. Click on '…'
3. Scroll down to '…'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment information (please complete the following information):**
- Device: [e.g. iPhone6]
- OS: [e.g. Ubuntu 20.04]
- Browser: [e.g. Firefox 86]
- FreshRSS version: [e.g. 1.17.1]
- Database version: [e.g. Mysql 5.7]
- PHP version: [e.g. PHP 7.4]
- Installation type: [e.g. Yunohost]

**Additional context**
Add any other context about the problem here.

```

**Comment by seoconsultant** [comment]
is there no other way to install this application without the /user/share folder
has the error still persist you can visit
https://www.seowebanalyst.com/blog/admin/rss/p to see the error

**Comment by Alkarex** [comment]
Hello,
You can put the FreshRSS folder wherever you want, as long as your Web server can see it.
You must not manually move the files/folders contained within the FreshRSS folder, which must remain intact.

**Comment by seoconsultant** [comment]
Ok, then why the error
Error during context user init!
following one of your suggestions to another user with a similar issue: Could you please try to check your Web browser logs and also FreshRSS logs ./FreshRSS/data/users/*/log*.txt for additional information?
this is what I found
[Sun, 06 Mar 2022 20:45:01 -0500] [error] --- FreshRSS_UserDAO::createUser error: ["42601",7,"ERROR:  syntax error at or near \"NOT\"\nLINE 1: CREATE TABLE IF NOT EXISTS \"freshrss_SEOWebAnalyst_category\"...\n                        ^"]

**Comment by seoconsultant** [comment]
I have reinstalled it...The issue was with using postgreSQL as database reinstalled and used MYSQL everything working.

**Comment by seoconsultant** [comment]
Where to remove the logo and the login page, I already have mine.

**Comment by Alkarex** [comment]
You can make your own theme or tweak an existing one (see the `./p/themes/` folder) and you can either use the HTTP Authentication mechanism to delegate the login to something else, or use the anonymous mode,

**Comment by seoconsultant** [comment]
Is their a user end url to access the feedrss without having to see the
login as the admin?

**Comment by seoconsultant** [comment]
Pardon my inquisitive nature, but I also want to know if their is a way end
user can actually automate the RSS post they get in their feed to other
attached social network (I see them listed in share)
Like syndication...auto post/schedule this feed content to respective
social network eg Facebook, LinkedIn, blogger, WordPress, live journal etc

**Comment by seoconsultant** [comment]
yes issue is solved
