### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by seoconsultant** [FreshRSS/FreshRSS#4265]
**Describe the bug**
When I visit the path where the installation is located I get the error
Error during context user init!

**To Reproduce**
1. Go to '[…](https://www.seowebanalyst.com/blog/admin/rss/p/i/?rid=622605bfdbba8)'
2. Click on '…'
3. Scroll down to '…'
Sun, 06 Mar 2022 20:45:01 -0500] [error] --- FreshRSS_UserDAO::createUser error: ["42601",7,"ERROR:  syntax error at or near \"NOT\"\nLINE 1: CREATE TABLE IF NOT EXISTS \"freshrss_SEOWebAnalyst_category\"...\n                        ^"]

**Expected behavior**
Was expecting the login page

**Screenshots**
I am not sure but I placed the p folder in the FRESHRSS folder (renamed the folder)
Later on, I read the issue of placing the FressRSS folder outside /usr/share the public folder
and only placing p folder in the public. I uploaded the folder in a sub-subdirectory
that is why the URL string is quite long.

**Environment information (please complete the following information):**
- Device: [e.g. postgreSQL]
- OS: [Apache]
- Browser: [Chrome]
- FreshRSS version: [1.19.2]
- Database version: [Mysql 5.6.43]
- PHP version: [ PHP 7.3.32]
- Installation type: [ ]

**Additional context**
Sun, 06 Mar 2022 20:45:01 -0500] [error] --- FreshRSS_UserDAO::createUser error: ["42601",7,"ERROR:  syntax error at or near \"NOT\"\nLINE 1: CREATE TABLE IF NOT EXISTS \"freshrss_SEOWebAnalyst_category\"...\n                        ^"]

**Comment by math-GH** [comment]
Related to #4264

**Comment by math-GH** [comment]
Is this issue solved?

**Comment by seoconsultant** [comment]
yep
