### ISSUE TITLE
[BUG] manipulate.translation.php and masked " chars

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#4268]
**Describe the bug**
I want run on my CLI:
`> php .\manipulate.translation.php -a add -k conf.key.subkey -v "long String text <a href=\"https://url.url/path\" title=\"title text\" target=\"_blank\">link text</a>."`

the result:
`'subkey' => '"long String text <a href=" https://url.url/path\\',	// TODO`

**Expected behavior**

**Screenshots**

**Environment information (please complete the following information):**
- Device: Powershell
- OS: Windows 10
- FreshRSS version: 1.20.0-dev
- PHP version: PHP 7.4

**Comment by math-GH** [comment]
ping @Alkarex

**Comment by math-GH** [comment]
ping @aledeg

**Comment by Frenzie** [comment]
I can't confirm. The result looks like this for me:

```diff
diff --git a/app/i18n/cz/conf.php b/app/i18n/cz/conf.php
index f25382a3..dd70751e 100644
--- a/app/i18n/cz/conf.php
+++ b/app/i18n/cz/conf.php
@@ -66,6 +66,9 @@ return array(
                        'thin' => 'Úzká',
                ),
        ),
+       'key' => array(
+               'subkey' => 'long String text <a href="https://url.url/path" title="title text" target="_blank">link text</a>.',        // TODO
+       ),
        'profile' => array(
                '_' => 'Správa profilu',
                'api' => 'Správa API',
```

PowerShell issue?

**Comment by math-GH** [comment]
ok, sometimes it is useful to think "loud"....

Now I found the solution:
use `'` instead of `"` for the whole string.
Keep the `\"` for the inside strings.

**Comment by Frenzie** [comment]
Yup, PowerShell issue.

```diff
diff --git a/app/i18n/cz/conf.php b/app/i18n/cz/conf.php
index f25382a3..6e36ad1e 100644
--- a/app/i18n/cz/conf.php
+++ b/app/i18n/cz/conf.php
@@ -66,6 +66,12 @@ return array(
                        'thin' => 'Úzká',
                ),
        ),
+       'key' => array(
+               'subkey' => array(
+                       '_' => 'long String text <a href="https://url.url/path" title="title text" target="_blank">link text</a>.',     // TODO
+                       'bla' => 'long String text <a href=\\', // TODO
+               ),
+       ),
        'profile' => array(
                '_' => 'Správa profilu',
                'api' => 'Správa API',
```

**Comment by Frenzie** [comment]
> Now I found the solution:
use ' instead of " for the whole string.
Keep the \" for the inside strings.

I'm not sure why you didn't do that in the first place. I would've never noticed this odd behavior of PowerShell's. ^_^ But tl;dr just use a better shell than that pwsh contraption and it's not an issue. :-P

**Comment by math-GH** [comment]
I use too seldom the CLI

**Comment by math-GH** [comment]
Nice learning to add it to the documentation

**Comment by Frenzie** [comment]
@math-GH Actually you escaped it incorrectly. In PowerShell, it should look more like this, with \`", not `\"`:

```
./manipulate.translation.php  -a add -k conf.key.subkey.lala -v "long String text <a href=`"https://url.url/path`" title=`"title text`" target=`"_blank`">link text</a>."
```

Result as expected:

* _ = the original command in Bash/POSIX-ish shells in general
* bla = the original command in pwsh
* lala = the correctly escaped command in pwsh
```diff
diff --git a/app/i18n/cz/conf.php b/app/i18n/cz/conf.php
index f25382a3..44b98ddf 100644
--- a/app/i18n/cz/conf.php
+++ b/app/i18n/cz/conf.php
@@ -66,6 +66,13 @@ return array(
                        'thin' => 'Úzká',
                ),
        ),
+       'key' => array(
+               'subkey' => array(
+                       '_' => 'long String text <a href="https://url.url/path" title="title text" target="_blank">link text</a>.',     // TODO
+                       'bla' => 'long String text <a href=\\', // TODO
+                       'lala' => 'long String text <a href=https://url.url/path title=title',  // TODO
+               ),
+       ),
        'profile' => array(
                '_' => 'Správa profilu',
                'api' => 'Správa API',
```

Edit: not 100% correct obviously but I can't really be bothered to figure out the exact thing we want out of it.

**Comment by Frenzie** [comment]
This feels too convoluted, but the result is correct:
```
./manipulate.translation.php  -a add -k conf.key.subkey.lala4 -v "long String text <a href=\`"https://url.url/path\`" title=\`"title text\`" target=\`"_blank\`">link text</a>."
```

**Comment by aledeg** [comment]
Does this need to be addressed by a fix or by some documentation?

**Comment by Frenzie** [comment]
It's just basic pwsh; the reason I had to look up how to escape in pwsh is because I don't or barely know pwsh. But I believe simply `'bla "stuff in double quotes" bla'` should work just as well there without any need for escaping. I suppose you could try to mention something about single vs double quote and escaping in different types of shells if you expect anyone to actually read it.

**Comment by aledeg** [comment]
I don't expect anyone to read it. So I guess we can just close this.

**Comment by aledeg** [comment]
I guess we can close it.
