### ISSUE TITLE
[BUG] New Log layout

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#4272]
![image](https://user-images.githubusercontent.com/1008324/158270580-28ecab6b-bc5e-4e85-8e8e-4a832e512ee9.png)

```
Notice: Undefined index: debug in /var/www/FreshRSS/app/Models/Themes.php on line 114
```

And missing horizontal scrollbar.

@Frenzie WebSub issue on your site? :-) Or is it a bug in my FreshRSS instance?

_Originally posted by @Alkarex in https://github.com/FreshRSS/FreshRSS/issues/4204#issuecomment-1067360873_

**Comment by math-GH** [comment]
@Alkarex Is the warning also visible in the frontend before the PR was merged?

**Comment by Alkarex** [comment]
> Is the warning also visible in the frontend before the PR was merged?

@math-GH No, the warning was a regression (now fixed)
