### ISSUE TITLE
[BUG]  <meta name="[theme-color]" content="#FFF" /> can not change white color for android status bar

### ISSUE THREAD

**Issue by siSSSou** [FreshRSS/FreshRSS#4274]
**Describe the bug**
I use FreshRSS as progressive app on Android, and I want my Android status bat to be black, as the FreshRSS theme I use (Mapco).
Where can I modify this line  'meta name="[theme-color]" content="#FFF" ' in <head> section ?
Default color is white for all themes !

I want to replace "FFF" with "000" ;-)

**To Reproduce**
1. Display FreshRSS app source code
2. Notice the line ' meta name="theme-color" content="#FFF" '
3. If you use FreshRSS as a progressive app on Android, your status bar will be displayed in white

**Expected behavior**
I would like to display black color in statusbar

**Screenshots**
Notice the white zone : white icons on white background !

![Screenshot_20220316-190930_Firefox](https://user-images.githubusercontent.com/16271116/158658484-51d864b5-a590-493b-b3ae-cf79abfec14e.png)

**Environment information (please complete the following information):**
- Device: Xiaomi MI A3 / Android 11

- FreshRSS version: FreshRSS 1.19.2
- Database version: MariaDB
- PHP version: PHP 7.4
- Installation type: Debian

**Comment by Frenzie** [comment]
Fixed in #4254. ^_^

**Comment by siSSSou** [comment]
To change to black color, modify [app/layout/layout.phtml](https://github.com/FreshRSS/FreshRSS/blob/1fe66ad020ca8f0560bb9c6e311852ed77228f78/app/layout/layout.phtml)

But indeed Firefox doesn't use the meta name="theme-color" ;-(
Firefox bug : https://github.com/mozilla-mobile/fenix/issues/8812
