### ISSUE TITLE
[BUG] TypeError in lib_phpQuery.php when updating feeds

### ISSUE THREAD

**Issue by yoyoyonas** [FreshRSS/FreshRSS#4279]
**Describe the bug**
Since a few weeks (but not immediately after updating to 1.19.2) I get the following error when trying to update feed via CLI as described in the [CLI Readme](https://github.com/FreshRSS/FreshRSS/blob/edge/cli/README.md) and in the [docs](https://freshrss.github.io/FreshRSS/en/admins/08_FeedUpdates.html).

`./cli/actualize-user.php --user $user` leads to

```
FreshRSS actualizing user “$user”…
PHP Fatal error:  Uncaught TypeError: Return value of phpQueryObject::matchClasses() must be of the type bool, none returned in /var/www/FreshRSS/lib/lib_phpQuery.php:1742
Stack trace:
#0 /var/www/FreshRSS/lib/lib_phpQuery.php(1793): phpQueryObject->matchClasses()
#1 /var/www/FreshRSS/lib/lib_phpQuery.php(1916): phpQueryObject->runQuery()
#2 /var/www/FreshRSS/app/Models/Entry.php(482): phpQueryObject->find()
#3 /var/www/FreshRSS/app/Models/Entry.php(508): FreshRSS_Entry::getContentByParsing()
#4 /var/www/FreshRSS/app/Models/Feed.php(475): FreshRSS_Entry->loadCompleteContent()
#5 /var/www/FreshRSS/app/Controllers/feedController.php(381): FreshRSS_Feed->loadEntries()
#6 /var/www/FreshRSS/cli/actualize-user.php(21): FreshRSS_feed_Controller::actualizeFeed()
#7 {main}
  thrown in /var/www/FreshRSS/lib/lib_phpQuery.php on line 1742
```
Feeds are not updated.  
Same Problem occurs when using `./app/actualize_script.php`; Updating feeds via the web however still works.

**To Reproduce**
1. Update feeds via `actualize_script.php` or `actualize-user.php`.
2. See error.

**Expected behavior**
Feed update script finishes without errors, only displaying notices about invalid feeds.

**Environment information (please complete the following information):**
- Ubuntu 18.05
- FreshRSS 1.19.2
- MariaDB 10.5.15
- PHP 7.4
- Manual Installation

**Additional context**
* I recently started using CSS selectors. Might be related, might be coincidence.
* I noticed `lib_phpQuery.php` got replaced on the `edge` branch, so this issue might already be fixed with the next release.

**Comment by Alkarex** [comment]
Could you please try our latest `edge` version? This whole code has been completely modified.

**Comment by yoyoyonas** [comment]
Sure. With the latest version (a89fce27), `actualize-user.php` at some point exits with  
`PHP Fatal error:  Maximum execution time of 300 seconds exceeded in /var/www/FreshRSS-edge/lib/SimplePie/SimplePie/Misc.php on line 2254`.

I noticed various `@set_time_limit(300);` in `app/Controllers/` possibly overwriting `max_execution_time = 0` in the CLI-`php.ini`, but I don't know what action takes that long execution time.

---
Before, additionally to the expected warnings about invalid feeds, multiple new warnings were printed in the form
```
PHP Warning:  file_put_contents(/var/www/FreshRSS-edge/data/PubSubHubbub/feeds/$very_long_string/!hub.json): failed to open stream: File name too long in /var/www/FreshRSS-edge/app/Models/Feed.php on line 893
PHP Warning:  touch(): Unable to create file /var/www/FreshRSS-edge/data/PubSubHubbub/feeds/$very_long_string/$user.txt because File name too long in /var/www/FreshRSS-edge/app/Models/Feed.php on line 902
```
But I guess that's not releated (?).

**Comment by Alkarex** [comment]
Indeed, those other problems do not seem related.
If you are willing to share the user's list of feeds, or at least the problematic feeds, I would be interested in looking into it.
Also this `very_long_string`, I would be interested in seeing a more precise example,

**Comment by yoyoyonas** [comment]
Can you advice on how to figure out which feeds cause the problem? I couldn't find something like a debug option in the docs and already checked `data/users/$user/log.txt`.

**Comment by Alkarex** [comment]
When you run for instance `cli/actualize-user.php --user alice` there should be a standard output / error output of what is happening. Where it stops (e.g. the last feed) would be a good indication of a likely culprit.

**Comment by yoyoyonas** [comment]
I think I found the cause of the first error. Initially I was under the misconception that the full CSS path was needed as selector, leading to very long, cumberstone selectors like e.g.  
`html.v2 body.loading div.content div.content-outer div.fauxborder-left.content-fauxborder-left div.content-inner div.main-outer div.fauxborder-left.main-fauxborder-left div.region-inner.main-inner div.columns.fauxcolumns div.columns-inner div.column-center-outer div.column-center-inner div#main.main.section div#Blog1.widget.Blog div.blog-posts.hfeed div.date-outer div.date-posts div.post-outer div.post.hentry.uncustomized-post-template`  
for `https://dasfahrradblog.blogspot.com/feeds/posts/default?alt=rss`.
After removing all instances of such selectors, 1.19.2 fetches feeds again until it runs into the same timeout error as the `edge` version - so I assume those two errors are not even related. 

I was not able to determine the feed(s) that cause the problem yet. Is there an easy way to let the update script echo _every_ feed to stdout when it starts working on that feed, _before_ any error occur? 

---- 
Regarding the long file names issue: This affects feeds of certain Wordpress instances that I can not disclose (running the latest WP version 5.9.2).  
Instead of encoding just the feed URL as in all other folder names in `data/PubSubHubbub/feeds`, the base64 encoded string `data/PubSubHubbub/feeds/$string` for this feeds `https://$wphost/feed/` reads:  
`<https://pubsubhubbub.appspot.com>; rel=hub, <https://pubsubhubbub.superfeedr.com>; rel=hub, <https://websubhub.com/hub>; rel=hub, https://$wphost/feed/, <https://$wphost/wp-json/>; rel=https://api.w.org/`  
I am a bit surprised to find URLs of external PubSubHubbub hubs here.
This is true for the edge and for the 1.19.2 version.

**Comment by Alkarex** [comment]
The long filename issue should be fixed with https://github.com/FreshRSS/FreshRSS/pull/4282 (not tested yet, feedback welcome).
But the fact that the URL contains several fragments still needs fixing.
Could you maybe post an example of how this is declared in `https://$wphost/feed/` (towards the top)?

**Comment by Alkarex** [comment]
Ah, I have found an example of our own (thanks @Frenzie ) with the same problem: https://fransdejonge.com/feed/

**Comment by Frenzie** [comment]
Are you saying it's related to that error we noticed recently we (or at least I) haven't really investigated yet?

**Comment by Alkarex** [comment]
@Frenzie Yes :-) So potentially two fixes at once. So good that you were using this feature

**Comment by Alkarex** [comment]
Multiple hubs declared:

```xml
<link rel="hub" href="https://pubsubhubbub.appspot.com" />
<link rel="hub" href="https://pubsubhubbub.superfeedr.com" />
<link rel="hub" href="https://websubhub.com/hub" />
```

I am not sure of what to do with that, actually (currently just picking the first), so links to relevant spec section appreciated, if anyone finds

**Comment by Frenzie** [comment]
That's simply the default configuration of https://wordpress.org/plugins/pubsubhubbub/

https://github.com/pubsubhubbub/wordpress-pubsubhubbub/blob/eaab6fbbebee1e4ebeeb26794e0df547359b4aa4/includes/class-pubsubhubbub-publisher.php#L119-L126

**Comment by Alkarex** [comment]
Ah, actually it is due to the HTTP Header:

```
link: <https://pubsubhubbub.appspot.com>; rel="hub", <https://pubsubhubbub.superfeedr.com>; rel="hub", <https://websubhub.com/hub>; rel="hub", <https://fransdejonge.com/feed/>; rel="self", <https://fransdejonge.com/wp-json/>; rel="https://api.w.org/"
```

**Comment by Frenzie** [comment]
As in multiple `<link>`s in the header aren't parsed properly at the moment?

**Comment by Alkarex** [comment]
SimplePie bug addressed in https://github.com/FreshRSS/FreshRSS/pull/4283

**Comment by Alkarex** [comment]
@yoyoyonas Please try again with the latest edge, which has two new fixes, hopefully solving the problems you observed

**Comment by yoyoyonas** [comment]
The fixes do work for me, thank you very much!

I was also able solved the timeout problem by changing all instances of `set_time_limit(300)` in `feedController.php` from `300` to `900`, so I assume the problem was just one feed with lots of entries on a slow webserver that CSS selectors were applied to.
