### ISSUE TITLE
[Survey] Which theme do you use?

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#4295]
FreshRSS supports 11 themes. 

Question: 
`Which one do you use?`
and
`Why do you like it?`

1. Alternative Dark
2. Ansum
3. Blue Lagoon
4. Dark 
5. Flat
6. Mapco
7. Origine
8. Origine-compact
9. Pafat
10. Screwdriver
11. Swage

(While FreshRSS respects your privacy the FreshRSS application does not collect any information about user's preferences)

Why do I ask?
While I look over the themes I see a lot of small issues in the themes but it I cannot fix all themes because of my available time and I do not know the "story"/"idea" behind the themes. I would like to focus my time for fixing the themes on most used themes.

**Comment by Alkarex** [comment]
I personally use *Pafat*, mostly because all the others have at least one thing that I am not found of.
When I make an account for someone else, I typically chose one of the others though, depending on my guess of their preference.

**Comment by Frenzie** [comment]
I mostly just use the default Origine (with some custom CSS).

**Comment by math-GH** [comment]
I use Origine because I do not like the other themes

**Comment by miicat** [comment]
I like the Alternative Dark theme

**Comment by stefangehn** [comment]
Mapco since elements have good contrast and no need for additional borders which IMHO makes Origine look even busier.
(I'm currently thinking of creating my own to see if I can `display: none` UI elements I don't use while reading, too many buttons)

**Comment by Zeik0s** [comment]
Mapco. In general because the theme is designed not too flat, but also not too elevated. Second to Mapco is Swage, but there the buttons are sometimes a bit too small for my taste and too sharp. 

My Mapco take, a bit adapted: 

```
.content h1.title a, .content h1 a, .content.thin h1.title a, .content.thin h1 a 
{
	color: #303136;
	font-family: "spectral", serif;
```
I don't like the serif font for headings. 🤷‍♂️

**Comment by triatic** [comment]
Alternative Dark, I prefer dark themes and this one looks the nicest to me.

**Comment by andreymal** [comment]
Mapco because is looks more modern and lightweight than other themes
I also use a bit of custom CSS+JS to make the reader view more contrast and to collapse long articles https://i.imgur.com/oqJ3uRl.png

**Comment by IcerOut** [comment]
The normal Dark one. I prefer dark themes and I prefer Dark's colors over Alternative Dark's ones (the shades of gray, the white borders on buttons, etc)

Although, wouldn't a strawpoll or something be better for this? Or a google form, to easily gather up the results instead of looking through a bunch of comments.

**Comment by zheyiyuezhuo** [comment]
Alternative Dark，I'm used to it

**Comment by douglasriper** [comment]
Pafat, I don't know why but it's the one I preferred when I chose it.

**Comment by math-GH** [comment]
Just an overview to see which themes have 0 fans.
1. Alternative Dark (3)
2. Ansum (0)
3. Blue Lagoon (0)
4. Dark (1)
5. Flat (0)
6. Mapco (3)
7. Origine (2)
8. Origine-compact (0)
9. Pafat (2)
10. Screwdriver (0)
11. Swage (0)

**Comment by cn-tools** [comment]
Swage

**Comment by Alkarex** [comment]
New theme! https://github.com/FreshRSS/FreshRSS/pull/4311

**Comment by cweiske** [comment]
I use Origine-compact

**Comment by FFDA** [comment]
> Which one do you use?

Origine

> Why do you like it?

When I installed FressRSS I tried a few of them, but soon came back to Origine and forgot that there are different themes until I read this question. So, I guess it's good enough that I didn't look for alternative.

Thank you for FreshRSS!

**Comment by joelchrono12** [comment]
I use my own theme, based on the Nord color scheme. I think I will make a PR to finally add it now. https://github.com/joelchrono12/freshrss-nord-theme

**Comment by vonguyenkhang** [comment]
`Which one do you use?` **_1. Alternative Dark_**
`Why do you like it?` I prefer dark themes, but **_4. Dark_**'s buttons are not distinct enough (they're kind of blended into the background), so the only option left is **_1. Alternative Dark_**

**Comment by gu1ll0me** [comment]
Alternative Dark

**Comment by clupasq** [comment]
I use MapCo and I love it!

**Comment by krisu5** [comment]
_Ansum_, it has best typography of all the themes.

Basically same as Mapco, but I don't like dark colors that much, so that why _Ansum_.

**Comment by math-GH** [comment]
updated list:

- Alternative Dark (5)
- Ansum (1)
- Blue Lagoon (0)
- Dark (1)
- Flat (0)
- Mapco (4)
- Origine (3)
- Origine-compact (1)
- Pafat (2)
- Screwdriver (0)
- Swage (1)

The new themes that will come with next releasae will not count in this list.

**Comment by Qeynos** [comment]
Swage

**Comment by aidistan** [comment]
Origine-compact which has the highest information density.

**Comment by Offerel** [comment]
Mostly my own theme, based on Swage. Since its messy hack, i have no idea, if i should make a PR for this:

![image](https://user-images.githubusercontent.com/14041522/181012441-6d4c7390-e185-4522-b0ff-c36f3d07dab0.png)

Most changes are the colors and that you can resize the sidebar in width + some mouse hover effects.

Edit: Created a Pull Request in #4462. Hopefully this is the right way to do that.

**Comment by XSBen** [comment]
Swage

**Comment by Aevrin** [comment]
#4

**Comment by helmut72** [comment]
Origine. Don't use/need FreshRSS webinterface that much. Most of the time it's clients like Reeder (iOS/macOS) and FeedMe (Android).

**Comment by i-iooi-i** [comment]
When can I add a clean and tidy theme? The current styles look like frame structures with high similarity and some influence on reading.I prefer this theme. More planar, easier to read, no visual interference：https://github.com/levito/tt-rss-feedly-theme

**Comment by math-GH** [comment]
> When can I add a clean and tidy theme? The current styles look like frame structures with high similarity and some influence on reading.I prefer this theme. More planar, easier to read, no visual interference：https://github.com/levito/tt-rss-feedly-theme

Let us discuss it in #4543, so we can keep this thread clean for the theme survey.

**Comment by beerisgood** [comment]
> Question: `Which one do you use?` and `Why do you like it?`
> 
Alternative Dark
best dark version but sadly not best buttons color and also not fully optimized for mobile.

**Comment by math-GH** [comment]
@Poorchop uses Alternative Dark too (see #4601)

**Comment by math-GH** [comment]
@foureight84 uses Mapco (see #4691)

**Comment by ngoomie** [comment]
Origine-compact. I usually like using dark themes, but in this case I'm not just because any of the currently-available dark themes feel too big in terms of used screen space. I might make my own dark theme based off of it at some point, or maybe a low-contrast light theme. I'll admit I actually really don't mind it as-is though, it manages to be pretty easy on my eyes for a light theme!

**Comment by squromiv** [comment]
8. Origine-compact + Dark Theme extensions in browsers.

I prefer compact view of feed titles in FreshRSS, as well as dark background. But native FreshRSS dark themes looks not so tiny as Origine-compact. I forced to turn on browser addons in desktop Windows PC, in order to use these features simultaneously. Do not use android apps for rss,  so there is the same setup in smartphone.

**Comment by Juijote** [comment]
Alternative Dark , this night mode is more comfortable than .

**Comment by math-GH** [comment]
updated list:

- Alternative Dark (8)
- Ansum (1)
- Blue Lagoon (0)
- Dark (2)
- Flat (0)
- Mapco (5)
- Origine (4)
- Origine-compact (4)
- Pafat (2)
- Screwdriver (0)
- Swage (3)
- own theme (1)

**Comment by notDavid** [comment]
I use the 'Nord' theme. Please consider adding it to the list above, as it is now merged :-)

**Comment by ko** [comment]
Another tally for Ansum. 

I tried a few of the themes early on, and landed on this one as the least annoying. Honestly forgot there were other theme choices, too, until seeing this.

**Comment by daffydock** [comment]
I really like Nord and albeit I am an avid, daily user of FreshRss on a number of different kit, mobile takes the lead and Dark, along with a couple of CSS tweaks fits me just fine. Since I prefer a lot of info on my available real estate.  

I did see that someone has requested for Nord to get a bit tighter so I am looking forward to see how that comes out.

**Comment by yllekz** [comment]
Alternative Dark — By: Ghost

Seems to the be least noisy and no-nonsense dark theme in the bunch.

**Comment by math-GH** [comment]
updated list:

- Alternative Dark (9)
- Ansum (2)
- Blue Lagoon (0)
- Dark (2)
- Flat (0)
- Mapco (5)
- Nord (2)
- Origine (4)
- Origine-compact (4)
- Pafat (2)
- Screwdriver (0)
- Swage (3)
- own theme (1)

**Comment by ghost** [comment]
I switch back and forth between Origin and Origine-compact. Will you fix the problems in these two topics in your spare time? Thank you~

**Comment by IndrekHaav** [comment]
Flat. Looks nice and doesn't get in the way of the content.

**Comment by gingerbeardman** [comment]
Until now I've used: Origine-compact

Trying out Swage from now on.

But mostly my consumption is through apps, so I only use FreshRSS for some admin tasks, like adding new filters to a feed.

**Comment by rocka** [comment]
I've personally used "Flat" theme for a long time. Seeing it has been marked as deprecated in #4807 , I'm kind of interested in maintaining it. How can I get started? Is it enough to just submit some pull requests, or maybe maintaining a fork elsewhere?

**Comment by Frenzie** [comment]
I think some PRs would be fine. What specifically are the kind of issues making them outdated @math-GH?

**Comment by Alkarex** [comment]
> I've personally used "Flat" theme for a long time. Seeing it has been marked as deprecated in #4807 , I'm kind of interested in maintaining it. How can I get started? Is it enough to just submit some pull requests, or maybe maintaining a fork elsewhere?

@rocka Yes, like @Frenzie says, some PRs would be welcome, so do not hesitate. I think a good start would be to check the updates that have been made recently to the other themes (e.g. the use of CSS variables) and do the same

**Comment by andris155** [comment]
Which one do you use?
I use Alternative Dark theme.

Why do you like it?
Because I like this dark theme.

**Comment by Zaczero** [comment]
I use alternative dark because I love dark reader themes and the normal dark is too low contrast for me. Alternative dark is a lot easier to navigate. The only downside is that there is too little color in this theme. Too much white-grey-black. I personally enjoy nicely color coded elements.

**Comment by math-GH** [comment]
@Zaczero : please have a look into #5205

**Comment by alexjp** [comment]
Sorry ... very new freshrss user ...

Using:
 "Flat design, by Marien Fressinaud".

Why:
Its beautifull :) I love Screwdriver too (maybe as much or more) but screwdriver theme does "read/unread" by bolding/not bolding text, and I prefer changing the backgroud also (which "Flat Design" does but Screwdriver doesn't.)

**Comment by math-GH** [comment]
Thanks for your answers. After 1 year I will close this ticket. It helped to find out which themes are not so popular anymore.

**Comment by NealPierceGH** [comment]
`Flat` is by far the best looking for me and the most usable/readable. `Origin` is nice but uses a bit more space than I'd like. `Flat` is compact, condensed, sufficiently colored and contrasted so one can easily spot everything on screen at a glance. There are few colors here and there that leave something to be desired but I can live with that, so please keep `Flat` 😄
