### ISSUE TITLE
[Feature] End to end encryption

### ISSUE THREAD

**Issue by trymeouteh** [FreshRSS/FreshRSS#4296]
**Is your feature request related to a problem? Please describe.
To add privacy for users of a FressRSS instance, having E2EE will ensure the host (instance) cannot see users feeds and subscriptions.

**Describe the solution you’d like**
Adding E2EE were all of your RSS feeds and subscriptions are encrypted and the server cannot see your feed or subscriptions. And having the connection between the browser or RSS client to the server encrypted.

Such a feature will make this service as private as it can be.

**Describe alternatives you’ve considered**
Subscription are encrypted for each user, but the instance will subscribe to a feed if one or more users are subscribed to the feed and will keep up to date on the feed. A decoy to prevent the host from knowing what users are subscribe to what but allowing feeds to stay synced and up to date.

**Additional context**
There are no private open source RSS feeds out there. There are encrypted email providers such as ProtonMail, Tutanota and CTemplar, there are encrypted calendar and contacts syncing services like EteSync, and there are encrypted cloud storage services such as Sync.com and Filen. Why not an encrypted RSS feed for privacy?

**Comment by Alkarex** [comment]
Hello,
I am not sure of which architecture you are thinking about, more precisely.
End-to-end encryption would require - among other things - that the original feeds encrypt their content (with each of of the readers public key?) - which seems quite unlikely.

**Comment by spaetz** [comment]
Given that a server ooerator can always see to which hosts a network connection is being made, I do not think there is much to be gained. RSS feeds are just not designed for E2E. Although the architecture would have to jump through some very tricky hoops to have server operators not see the user's feeds. Finally, given that server operators can always install a non-E2E version without the users knowledge, you have to trust your server operator in any case.

**Comment by Alkarex** [comment]
Indeed @spaetz 👍🏻
