### ISSUE TITLE
[BUG] deprecation warning with PHP 8.1: Passing null to parameter #2 ($code) of type int is deprecated in app/Models/Feed.php on line 350

### ISSUE THREAD

**Issue by candrews** [FreshRSS/FreshRSS#4299]
**Describe the bug**
Running `/app/actualize_script.php` results in this:
```
PHP Deprecated:  Exception::__construct(): Passing null to parameter #2 ($code) of type int is deprecated in /var/www/localhost/htdocs/FreshRSS/app/Models/Feed.php on line 350
```

**To Reproduce**
1. Run  `/app/actualize_script.php`

**Expected behavior**
There shouldn't be any warning.

**Screenshots**
n/a

**Environment information (please complete the following information):**
- Device: Linux server
- OS: Gentoo
- Browser: n/a
- FreshRSS version: current `edge`: ab7d9c34ee7f22c3dc23a0c9265a971bdbe8173e
- Database version: n/a
- PHP version: PHP 8.1.4
- Installation type: ?

**Additional context**

**Comment by Alkarex** [comment]
Should be fixed with https://github.com/FreshRSS/FreshRSS/pull/4301
Tests welcome
