### ISSUE TITLE
[Feature] @tempnam in ExportService.php

### ISSUE THREAD

**Issue by geelinsir** [FreshRSS/FreshRSS#4304]
I don't know if this closing error prompt is necessary,But at least it had an impact on my troubleshooting of environmental errors,Please evaluate whether you need to remove the '@'.
be located ./app/Services/ExportService.php:170
`$zip_file = @tempnam('/tmp', 'zip');`

**Comment by Alkarex** [comment]
Indeed, that could advantageously be removed, I believe. PR welcome :-)

**Comment by harshad389** [comment]
@Alkarex Can i work on this issue?

**Comment by Alkarex** [comment]
> @Alkarex Can i work on this issue?

Sure! :-)

**Comment by harshad389** [comment]
Hi @Alkarex, I have submitted PR. Can you please review it?
