### ISSUE TITLE
[BUG] anonym. mode: my labels error

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#4305]
**To Reproduce**
1. use FreshRSS in anonym. mode
2. open an article
3. click on "my labels"
4. see browser console (error displayed)
5. see the empty label list

![grafik](https://user-images.githubusercontent.com/1645099/161436824-33258b0b-3eee-4eb4-8be8-cba504797c14.png)

**Expected behavior**

- No error
- show added labels

**Environment information (please complete the following information):**
- Browser: Firefox 98
- FreshRSS version: 1.19.2 (see demo.freshrss.org), 1.20.0-dev

**Comment by math-GH** [comment]
Still relevant in 1.20.0-dev

**Comment by Alkarex** [comment]
Fixed in https://github.com/FreshRSS/FreshRSS/pull/5650
Tests welcome
