### ISSUE TITLE
Traefik guide in /Docker/Readme.md is for v1

### ISSUE THREAD

**Issue by gbakeman** [FreshRSS/FreshRSS#4308]
**Describe the bug**
I'm a little new to Traefik so I apologize if I'm off base here. I'm going through the guide and setting up FreshRSS in Docker+Traefikv2.7(r.c-something at the moment). The [FreshRSS run command](https://github.com/FreshRSS/FreshRSS/tree/edge/Docker#run-freshrss) portion of the documentation uses strange label names to me. From what I can tell, [they're from version 1](https://doc.traefik.io/traefik/migration/v1-to-v2/) of Traefik and not applicable to version 2. _Edit: Just realized the documentation is tagged v1.7 so it is for an older verison._

I've tinkered around with the labels, and here's what I propose we change them to on the documentation:

_`  --label traefik.port=80 \`_
**`--label traefik.http.services.freshrss.loadbalancer.server.port=80 \`**

_`  --label traefik.frontend.rule='Host:freshrss.example.net' \`_
**`--label traefik.http.routers.freshrss.rule=Host(``freshrss.example.net``)`** _(I don't know how to escape backticks... Pretend they aren't doubled)_

If you use Prefixes:
**`--label traefik.http.routers.freshrss.rule=Host(``freshrss.example.net``) && PathPrefix(``/freshrss``)`**
**`--label traefik.http.middlewares.freshrss-stripprefix.stripprefix.prefixes=/freshrss \`**
**`--label traefik.http.routers.freshrss.middlewares=freshrss-stripprefix@docker \`**

I need someone else to confirm the STS labels as I haven't played with those yet.

**Comment by Alkarex** [comment]
Yes, working on an update today. https://github.com/FreshRSS/FreshRSS/issues/3351
Draft: https://github.com/FreshRSS/FreshRSS/issues/2918#issuecomment-616668682

**Comment by Alkarex** [comment]
@gbakeman Please see https://github.com/FreshRSS/FreshRSS/pull/4320 and in particular the Traefik section, including the [docker-compose example](https://github.com/FreshRSS/FreshRSS/blob/d7f04412139c89b06c02fc96596be1d9b4566238/Docker/freshrss/docker-compose-proxy.yml).
Feedback welcome

**Comment by gbakeman** [comment]
Sorry, I left my comment [on your pull request](https://github.com/FreshRSS/FreshRSS/pull/4320#issuecomment-1101497983) when I meant to leave it here, but TL;DR looks great. Thanks!
