### ISSUE TITLE
Useless data transfer for loading articles

### ISSUE THREAD

**Issue by yzqzss** [FreshRSS/FreshRSS#4309]
When ajax requests a new article, the article data is contained in a complete html file. For example: `https://domain.ltd/i/?a=normal&rid=xxx&next=xxx&state=3&ajax=1`

But this html will contain a lot of useless parts(html nodes) other than the actual data of the article. Especially when I subscribe to a lot of feeds, The `<ul id="sidebar" class="tree">` tree can get particularly large. While Gzip can compress this part to a few tens of KiB, users frequently swipe the screen to load new article, and these useless tens of KiB are repeatedly transferred.

And to generate these useless parts adds a little bit of performance consumption, I guess.

**Comment by Alkarex** [comment]
Good point. Could you please test this fix? https://github.com/FreshRSS/FreshRSS/pull/4310

**Comment by Alkarex** [comment]
Merged in our `edge` branch. Feedback welcome
