### ISSUE TITLE
Anonymize logs output

### ISSUE THREAD

**Issue by jonatasbaldin** [FreshRSS/FreshRSS#4316]
Hi there, how are you doing?

Is there a way to completely anonymize the logs output? By default, there are logs like:

```
freshrss_1  | FreshRSS[630645]: [*username-here*] [Sat, 16 Apr 2022 22:20:02 +0200] [warning] --- WebSub lease ends at 2022-04-17T21:20:01+02:00 and needs renewal: https://www.blogger.com/feeds/3697776799325889805/posts/default
```

And I'd like to remove the `*username-here*` here and in all occasions to have zero knowledge privacy.

Is it possible?

**Comment by Alkarex** [comment]
Hello,
There is no such option at the moment, but it would not be so challenging to code it.
However, the privacy you are asking is probably an illusion, because the same server has all the usernames, the list of feeds, etc. so basically all and more than what is visible in the logs.

**Comment by Frenzie** [comment]
> However, the privacy you are asking is probably an illusion

Agreed, but nevertheless it might be a good idea to remove some information for ease of sharing some logs for debugging and troubleshooting purposes, for example?

Also there's a case to be made that even if you delete those accounts, the logs might linger on for significantly longer.

Put another way, is the username actively useful or is it just kind of there?

PS I'm not trying to argue in favor; these aren't rhetorical questions. :-)

**Comment by Alkarex** [comment]
@Frenzie The usernames in the logs does help finding where problems are, for FreshRSS instances with multiple users

**Comment by Frenzie** [comment]
You mean when multiple users have the same feed or something?

Anyway, that's good enough for me. ;-)

**Comment by Alkarex** [comment]
> You mean when multiple users have the same feed or something?

Indeed, or login problems, WebSub problems, etc.

**Comment by jonatasbaldin** [comment]
thanks for all the answers, it is not a really a needed thing for me, was wondering how hard that could be :)
