### ISSUE TITLE
[BUG] Feed "not readable" but it is

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#4324]
**Describe the bug**
Feed "not readable" but it is.

**To Reproduce**

Feed URI: https://brilliantplanet.org/feed/

Validator: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fbrilliantplanet.org%2Ffeed%2F

**Screenshots**

![202204211313](https://user-images.githubusercontent.com/58190287/164446444-0592a88c-4a66-474e-a6a0-96656ddf173e.jpg)

**Comment by Alkarex** [comment]
Hello,
This feeds works fine in my FreshRSS instance. Maybe a temporary failure, so please try again.
If the problem persists for more than 2 hours, try from your server:

```sh
curl -v 'https://brilliantplanet.org/feed/'
```

**Comment by ghost** [comment]
>  Maybe a temporary failure

That's exactly what it was - thanks 😀
