### ISSUE TITLE
[BUG] Only 500 items can be displayed in readers clients.

### ISSUE THREAD

**Issue by guillaumesoucy94** [FreshRSS/FreshRSS#4328]
**Describe the bug**
Hello, 

Why only 500 items can be displayed in Linux Mint based reader/clients. Tries 3 different readers and I can reproduce the issue in all of them. 

On my iPhone, my reader is displaying all the articles. 

I need help please. 

With regards, 

Guillaume.

**To Reproduce**
1. Add your FreshRSS account to your favorite reader.
2. Look, only 500 items are there.

**Expected behavior**
All the items should be there.

**Screenshots**
![Screenshot at 2022-04-24 21-10-08](https://user-images.githubusercontent.com/22561876/165005420-0e39713a-01de-4662-9634-68a823f2cc33.png)
![Screenshot at 2022-04-24 21-10-40](https://user-images.githubusercontent.com/22561876/165005437-2dba7e4e-5fa3-46d4-a377-e436bf414cb4.png)

**Environment information (please complete the following information):**
- Device: [e.g. Computer]
- OS: [e.g. Linux Mint 20.3 Una]
- Browser: [e.g. Firefox 99.0.1]
- FreshRSS version: [e.g. 1.19.0]
- Database version: [e.g. Mysql 5.7]
- PHP version: [e.g. PHP 7.4]
- Installation type: [e.g. Selfhosted]

**Additional context**

**Comment by Frenzie** [comment]
It seems that you left out the most important information. ;-)

**Comment by Alkarex** [comment]
Hello,
Like @Frenzie says, I cannot recognise which client you are trying just from the screenshot. On FreshRSS side, there is no limit in the API. So what you observe is probably a setting (or a hardcoded limit) in the client.

**Comment by guillaumesoucy94** [comment]
@Frenzie Oh sorry. Tried, Liferea and QuiteRSS.

@Alkarex I'd took a screenshot of the Reading settings. Yes, it set at 500 but, I can't put a larger value, it won't let me.
![Screenshot at 2022-04-25 10-41-59](https://user-images.githubusercontent.com/22561876/165113029-c8be8b3e-f339-4c1a-97d7-eedf861cd4a2.png)

Thank-you!

Guillaume

**Comment by Alkarex** [comment]
@guillaumesoucy94 Your last screenshot is regarding the Web interface of FreshRSS and is not related to the internal settings of a client. You should revert back to a smaller (and therefore faster) value of about 30. I will give a try to the clients

**Comment by Alkarex** [comment]
I have not managed to use Liferea with FreshRSS and this functionality does not seem to be supported just yet. I am guessing you exported your main view into an RSS feed, and registered it into Liferea. While this works to some extent, it is not a way to synchronise the feeds :-)

The issue to implement (you can vote on it and/or propose some implementation help): https://github.com/lwindolf/liferea/issues/962
Your question on the other side: https://github.com/lwindolf/liferea/issues/1113

**Comment by Alkarex** [comment]
QuiteRSS does not seem to support synchronisation with a server. Take a look at our list of clients:
https://github.com/FreshRSS/FreshRSS#apis--native-apps
