### ISSUE TITLE
[BUG] Long Feed URLs get truncated 

### ISSUE THREAD

**Issue by aauro** [FreshRSS/FreshRSS#4338]
**Describe the bug**
I am using RSSBridge to generate some feeds. RSSBridge can produce lengthy URLs. I create one feed url composed of 482 characters but when used in FreshRSS it gets truncated to 475 characters. I noticed the mysql database field allows 511 as length. Somewhere else in the code, the feed url is being truncated. I have manually pasted the url in mysql and the feed works.

**To Reproduce**
1. Produce a url with more than 475 characters
2. create a new feed
3. After creation, check feed url to see that it gets truncated.

**Expected behavior**
Feed URL will get truncated to 475 characters

**Environment information (please complete the following information):**
- Device: x86 pc
- OS: Ubuntu 20.04
- Browser: Firefox
- FreshRSS version: 1.19.2
- Database version: 10.3.34-MariaDB
- PHP version: 7.4

**Suggestion**
Solve truncation problem and possibly increase length of Feed URL for compatibility with the useful RSSBridge

**Comment by Alkarex** [comment]
Initially, this constraint was to support MySQL, which was not able to have a unicity constraint on longer strings.
We need to check what the current situation is with MySQL + MariaDB, SQLite, PostgreSQL (and from which versions). Input welcome

**Comment by BlueWhale235** [comment]
I think you can creat a php(xxx.php) file and your new rss url is example.com/xxx.php
php file content includes:
<code> file_get_contents(__long_rss_url__) </code>

**Comment by fatuuse** [comment]
Same problem for me. eg. rss-bridge with xpathbridge url. One atom url for me i 519 chars.

**Comment by aledeg** [comment]
> Initially, this constraint was to support MySQL, which was not able to have a unicity constraint on longer strings. We need to check what the current situation is with MySQL + MariaDB, SQLite, PostgreSQL (and from which versions). Input welcome

Maybe we can use a hash of the feed URL to validate unicity. This way we will have always the same length no matter the feed URL length. We could store it along side the feed URL.

**Comment by Alkarex** [comment]
Please check https://github.com/FreshRSS/FreshRSS/pull/5038
