### ISSUE TITLE
can't add this rss : https://nicole.express/feed.xml

### ISSUE THREAD

**Issue by rezad1393** [FreshRSS/FreshRSS#4339]
when I try to add this feed gives this error:
Unknown error for feed [https://nicole.express/feed.xml]

**Comment by Alkarex** [comment]
Hello,
This feeds works fine in my FreshRSS instance. Maybe a temporary failure, so please try again.
If the problem persists for more than 2 hours, try from your server:

```sh
curl -v 'https://nicole.express/feed.xml'
```

**Comment by rezad1393** [comment]
this is weird.
the feed works in firefox but in curl doesn't.
I am from Iran so it may be network issues (government messes with network a LOT)

I dont know why firefox opens xml and website but curl cant.

**Comment by rezad1393** [comment]
Update:
yep.
government fuckery.
I cant connect with simple curl.
but if I add "--tlsv1.2 --tls-max 1.2" I can connect.

but in firefox it connects with tls1.3 (at least IndicateTLS addon shows that).

**Comment by Alkarex** [comment]
You can tweak the cURL settings used by FreshRSS in `./data/config.php` and a few cURL settings are exposed at feed level. And if there is a need of another cURL preference at feed level, it would be possible to implement it.

**Comment by Alkarex** [comment]
Did you try with another user-agent string (e.g. the same than your Firefox)?

**Comment by rezad1393** [comment]
> Did you try with another user-agent string (e.g. the same than your Firefox)?

I am not that pro with curl.



> You can tweak the cURL settings used by FreshRSS in `./data/config.php` and a few cURL settings are exposed at feed level. And if there is a need of another cURL preference at feed level, it would be possible to implement it.

can you point me to an example?

**Comment by Alkarex** [comment]
See for instance https://www.cyberciti.biz/faq/curl-set-user-agent-command-linux-unix/ to start with

**Comment by rezad1393** [comment]
> See for instance https://www.cyberciti.biz/faq/curl-set-user-agent-command-linux-unix/ to start with


I meant for feed setting.

btw I tested with user agent addition too,
didnt work,
I maybe take a network trace compatible with wireshark and compare the diff between them.

**Comment by math-GH** [comment]
@rezad1393 @Alkarex : is this ticket still relevant?
