### ISSUE TITLE
[BUG] CheckBox in main page is not running correctly.

### ISSUE THREAD

**Issue by BlueWhale235** [FreshRSS/FreshRSS#4341]
**Describe the bug**
CheckBox (id: use_default_purge_options)  in main page is not running correctly.

**To Reproduce**
![msedge_0WIEymdGTp](https://user-images.githubusercontent.com/35369979/166134311-dfa500e2-d52c-4cc1-a10f-3959aab01d1c.gif)

**Expected behavior**
![xNqt4ap6qc](https://user-images.githubusercontent.com/35369979/166134431-604db9d8-2dd8-4cc7-99ac-96130a30f174.gif)

**Screenshots**

**Environment information (please complete the following information):**
- Device:  PC
- OS: WIN10
- Browser: Edge 101.0.1210.32
- FreshRSS version: 1.20.0-dev
- Database version: Mysql 5.7
- PHP version: PHP 8.0
- Installation type: General Installation

**Additional context**
I fixed it by loading category.js and executed archiving(). But the console showed a error when I loaded category.js. This is a small problem, and I'm not sure what the authors think of it.
![屏幕截图 2022-05-01 141316](https://user-images.githubusercontent.com/35369979/166134564-a0e63687-7dcb-4a66-ac05-25955384fc8b.png)

**Comment by math-GH** [comment]
Thanks for your bug report.
It is a known issue. The fix is in discussion, see #4291

**Comment by Alkarex** [comment]
@BuleWhale https://github.com/FreshRSS/FreshRSS/pull/4291 is ready for testing. Feedback welcome

**Comment by BlueWhale235** [comment]
> @BuleWhale #4291 is ready for testing. Feedback welcome

Great! It works in my server!
