### ISSUE TITLE
Sharing fonctionnality

### ISSUE THREAD

**Issue by phardouin** [FreshRSS/FreshRSS#4354]
Hello,
what is the procedure for setting up sharing to a mastodon instance?
I can't find this point explained in the documentation.
best regards,
Patrice

**Comment by Frenzie** [comment]
There isn't really anything to explain with any of these. You simply give the URL.

**Comment by math-GH** [comment]
@phardouin : Does it work fine now?

**Comment by phardouin** [comment]
Yes, it's good, it works very well now. It was just related to the fact that copying and pasting the key from Mastodon left a space at the end. Once the space was removed there was no problem.

**Comment by Frenzie** [comment]
Aha, a trim is in order then. :-)

**Comment by math-GH** [comment]
How can I reproduce this issue? @phardouin
