### ISSUE TITLE
[BUG] syntax error at or near "(" at character 72 when showing users and editing a user

### ISSUE THREAD

**Issue by raro42** [FreshRSS/FreshRSS#4367]
**Describe the bug**

error message in logs:
------------------------------
freshrss-db  | 2022-05-15T12:55:30.834481046Z 2022-05-15 12:55:30.833 UTC [153] ERROR:  syntax error at or near "(" at character 72

Details:
------------------------------
Cloned freshRSS from github <code>git clone git@github.com:FreshRSS/FreshRSS.git</code>
Added Ports to docker-compose.yml
Started <code>docker-compose -f docker-compose.yml -f docker-compose-local.yml -f docker-compose-db.yml up -d --remove-orphans</code>
Open Browser at http://localhost:8080/ ... followed first configuration ... created Administration user "raro"
Added some feeds. All good. Feeds are coming in.

When editing users at URL <code>http://localhost:8080/i/?c=user&a=manage</code>

Logs <code>/var/www/github_FreshRSS/Docker/freshrss$ docker-compose logs -f --tail 500 --timestamps</code> show :

<pre>
freshrss-db  | 2022-05-15T12:55:30.834481046Z 2022-05-15 12:55:30.833 UTC [153] ERROR:  syntax error at or near "(" at character 72
freshrss-db  | 2022-05-15T12:55:30.834536895Z 2022-05-15 12:55:30.833 UTC [153] STATEMENT:  SELECT
freshrss-db  | 2022-05-15T12:55:30.834571801Z   pg_total_relation_size('"raro_category"')
freshrss-db  | 2022-05-15T12:55:30.834605031Z   pg_total_relation_size('"raro_feed"')
freshrss-db  | 2022-05-15T12:55:30.835308450Z   pg_total_relation_size('"raro_entry"')
freshrss-db  | 2022-05-15T12:55:30.835345869Z   pg_total_relation_size('"raro_entrytmp"')
freshrss-db  | 2022-05-15T12:55:30.835379657Z   pg_total_relation_size('"raro_tag"')
freshrss-db  | 2022-05-15T12:55:30.835412608Z   pg_total_relation_size('"raro_entrytag"')
freshrss     | 2022-05-15T12:55:30.841132108Z 172.25.0.1 - - [15/May/2022:14:55:30 +0200] "GET /i/?c=user&a=manage HTTP/1.1" 200 3735 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36"
</pre>

**Expected behavior**
I would like to understand if the error msg can be ignored.

**Environment information (please complete the following information):**
- Device: Windows Desktop
- OS: Ubuntu 20.04.1 LTS \n \l
- Browser: Chrome 100, FF 100
- FreshRSS version: 2022-02-04 FreshRSS 1.19.2
- Database version: Postgres from docker-compose-db.yml
- PHP version: PHP 7.4.25
- Installation type: docker-compose

**Comment by Alkarex** [comment]
Fixed in https://github.com/FreshRSS/FreshRSS/pull/4249
Could you please try our edge version?
