### ISSUE TITLE
[BUG] Manage feed slider

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#4373]
**Describe the bug**
I guess it comes from ##4291

When there is no unread feed in the stream, than the "manage" link does not open the slider. It opens the manage feed in a new page

**To Reproduce**
Prerequisite: Not all feeds are included in the main stream.

1. Go to normal view, go to main stream
2. mark all feeds as read
3. (The message "There are no articles to show." is shown)
4. open the sub menu of a feed
5. click on manage
6. the options are opened in a new page

![grafik](https://user-images.githubusercontent.com/1645099/168682075-cd27aacd-817e-4069-aea4-176065ad70be.png)

![grafik](https://user-images.githubusercontent.com/1645099/168682191-bb83901b-0767-4ab8-b92b-5a6fd019e0e5.png)

**Expected behavior**
The slider is opened to edit the feed

**Environment information (please complete the following information):**
- FreshRSS version: 1.20.0-dev

**Comment by Alkarex** [comment]
Good catch! Quick fix https://github.com/FreshRSS/FreshRSS/pull/4375
