### ISSUE TITLE
[Feature] Remaining reading time

### ISSUE THREAD

**Issue by BlueWhale235** [FreshRSS/FreshRSS#4381]
**Describe the solution you’d like**
Some articles are too long to read when I am busy. I would like to add a line which likes ``Total xxx words, remaining reading time xxx minutes.`` to the article. 

**Additional context**
I recommend this feature to be displayed on the front end, because some Android readers have this feature.

**Comment by Frenzie** [comment]
I think there's already an extension for that, isn't there? :)

**Comment by BlueWhale235** [comment]
I'm so sorry, I didn't see it.😞

**Comment by Frenzie** [comment]
Don't worry about it. ;-)

**Comment by Alkarex** [comment]
* https://github.com/FreshRSS/Extensions
* https://framagit.org/Lapineige/FreshRSS_Extension-ReadingTime

I have not tried it recently though, so feedback welcome

**Comment by BlueWhale235** [comment]
> * https://github.com/FreshRSS/Extensions
> * https://framagit.org/Lapineige/FreshRSS_Extension-ReadingTime
> 
> I have not tried it recently though, so feedback welcome

Ok👌. There is something wrong in my server, I will test it a few days later.
