### ISSUE TITLE
[BUG] Unknown Error with Feed that usually works

### ISSUE THREAD

**Issue by kjboa** [FreshRSS/FreshRSS#4384]
**Describe the bug**
The Katapult Magazin Feed (https://katapult-magazin.de/feed/rss) throws an unknown error. Other Rss Reader solutions I tried all pick up this feed

**Environment information (please complete the following information):**
- Installation type: Linuxserver Docker Image

**Comment by Frenzie** [comment]
Given the blatant XML parsing error, perhaps that was merely a coincidence? I.e., perhaps it works most of the time?

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fkatapult-magazin.de%2Ffeed%2Frss

![Screenshot 2022-05-22 at 13-20-50 Feed Validator Results https __katapult-magazin de_feed_rss](https://user-images.githubusercontent.com/202757/169692682-59301914-992e-4934-8eda-d1482c8a64b7.png)

**Comment by math-GH** [comment]
This feed works fine already.
