### ISSUE TITLE
[BUG]safari auth error after just login on docker lastest freshrss @ Debian

### ISSUE THREAD

**Issue by pisheng** [FreshRSS/FreshRSS#4388]
**Describe the bug**
In safari, freshrss will automatic logout after just login when language set to English.
In edge browser with  English language, no such issue.
In safari with Chinese language, no such issue.

**Screenshots**
![SCR-20220524-r8n](https://user-images.githubusercontent.com/700580/170026224-9bb32cc6-231a-471b-aef6-d2e2af5414dd.png)

**Environment information (please complete the following information):**
- OS: Mac os
- FreshRSS version: docker:latest
- Database version: sqlite

**Comment by math-GH** [comment]
Is it still an issue with the current 1.22.1?
If yes, which Docker image do you use?

**Comment by Alkarex** [comment]
Let's re-open if there if it becomes relevant again
