### ISSUE TITLE
[BUG] mark-as-read seems to be done "automatically" just by scrolling

### ISSUE THREAD

**Issue by hermannkm** [FreshRSS/FreshRSS#4392]
**Describe the bug**
When listing a feed, marking all as unread (manually) scrolling down leaves all items as read without any other action.

**To Reproduce**
1. List a feed with unread items
2. Scroll down to the end without any other action like clicking on an item
3. Scroll up again
4. See: all items are marked as read

**Expected behavior**
No change in read-status is expected.

**Screenshots**

**Environment information (please complete the following information):**
- Device: iPad (iOS 15.5), Macbook (macOS 11.6.6)
- Browser: [Safari]
- FreshRSS version: [e.g. 1.20]
- Database version: [e.g. Mariadb]
- PHP version: [e.g. PHP 7.3]
- Installation type: [e.g. self hosted]

**Additional context**

**Comment by Frenzie** [comment]
There's a setting for that. I think it's disabled by default but I'm not completely sure. It's one of the checkmarks in settings, reading at the bottom.

**Comment by hermannkm** [comment]
You are right -- found this setting which was enabled by default. Unsetting yielded the behavior I was expecting.
Sorry, absolute newbie, couldn't imagine this to be feature :-). Thanks for the fast response!

**Comment by Frenzie** [comment]
If it's by default I'll just say I'm not a fan of that default. ^_^
