### ISSUE TITLE
[BUG]update server is not found

### ISSUE THREAD

**Issue by seyfro** [FreshRSS/FreshRSS#4395]
The update server is not found, when accessing through the settings interface.

**To Reproduce**
1. Go to Settings
2. Click on Update
3. See error

**Expected behavior**
Availablilty of new version should be displayed.

**Screenshots**
![freshrss](https://user-images.githubusercontent.com/158669/170828109-5254116d-3b9c-4033-a4d3-6d48f8c31dfd.PNG)

**Environment information (please complete the following information):**
- Device: Windows 10
- Browser: Firefox 100
- FreshRSS version: reproduced with 1.9.1 and 1.9.2
- Database version: Mysql
- PHP version: PHP 7.4.28

**Comment by math-GH** [comment]
>     * FreshRSS version: reproduced with 1.9.1 and 1.9.2

Do you mean `1.19.1` and `1.19.2`? Or do you really mean version 1.9 (it is a very very old version)?

**Comment by seyfro** [comment]
Sorry, of course 1.19.1 and 1.19.2 (typo)

**Comment by Alkarex** [comment]
@robertharm I cannot reproduce the bug, but would you be able to try this patch? https://github.com/FreshRSS/FreshRSS/pull/4399

**Comment by seyfro** [comment]
@Alkarex: thanks for the proposed fix - unfortunately this was not the reason of my issue. I did some more research and found that SSL verification seemed to have been the issue. After  I change 
`curl_setopt($c, CURLOPT_SSL_VERIFYPEER, true);`
to
`curl_setopt($c, CURLOPT_SSL_VERIFYPEER, false);`
update notifications worked again on my server.

Not sure what is causing this though - probably the configuration of my server, as according to ssllabs.com your server has a A+ configuration, while mine has some issues. I will contat my hoster to verify this. 

Anyway thanks for your support & making freshress available as open source - I have been using it for years & really like it!
