### ISSUE TITLE
[BUG] docker update version error

### ISSUE THREAD

**Issue by chenbihao** [FreshRSS/FreshRSS#4398]
**Describe the bug**

An error occurred in upgrading from the old version to the new version:

1.18.1 -> [latest](https://hub.docker.com/layers/freshrss/freshrss/freshrss/latest/images/sha256-09e379a4c6046e29c26272d135abfb9b5078bbeb19eba0826741afe3f6f21815?context=explore)

latest and edge error:
```
 Could not initialize random number generator
```
latest-alpine and edge-alpine error:

```
 Apache/2.4.53 (Unix) PHP/8.0.19 configured -- resuming normal operations
[Mon May 30 11:29:47.693460 2022] [core:notice] [pid 1] AH00094: Command line: 'httpd -D FOREGROUND'
```

**To Reproduce**

```
# Rebuild an image (see build section below) or get a new online version:
docker pull freshrss/freshrss
# And then
docker stop freshrss
docker rename freshrss freshrss_old
# See the run section above for the full command

docker run -d --restart unless-stopped --log-opt max-size=10m \
  -v ~/dockerFile/freshRSS/data:/var/www/FreshRSS/data \
  -v ~/dockerFile/freshRSS/extensions:/var/www/FreshRSS/extensions \
  -e 'CRON_MIN=4,34' \
  -e TZ=Asia/Shanghai \
  -p 1280:80 \
  --name freshrss freshrss/freshrss:latest

```

**Expected behavior**

everything is working

**Screenshots**
![image](https://user-images.githubusercontent.com/21167262/170984987-c372bd81-c819-4965-90e8-bfef8f6d0244.png)
![image](https://user-images.githubusercontent.com/21167262/170985121-d22623cd-565c-4f66-b15f-914a2fbd3db2.png)

**Environment information (please complete the following information):**

CentOS Linux release 7.3.1611 (Core)

Linux version 3.10.0-514.26.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Tue Jul 4 15:04:05 UTC 2017

Docker version 19.03.11, build 42e35e61f3

**Additional context**

**Comment by Alkarex** [comment]
Hello,
Do I understand correctly that the Alpine version is working but not the default (Debian) one?

**Comment by Alkarex** [comment]
It seems to be a duplicate of https://github.com/FreshRSS/FreshRSS/issues/4162

**Comment by chenbihao** [comment]
> 

after switching to the latest-alpine tag it not worked.

There are other errors:
```
 Apache/2.4.53 (Unix) PHP/8.0.19 configured -- resuming normal operations
[Mon May 30 11:29:47.693460 2022] [core:notice] [pid 1] AH00094: Command line: 'httpd -D FOREGROUND'
```

**Comment by chenbihao** [comment]
> is working

I'm sorry, I read it wrong, it works normally
