### ISSUE TITLE
Raspberry pi installation permissions

### ISSUE THREAD

**Issue by ryanfox** [FreshRSS/FreshRSS#4402]
I ran into an issue installing FreshRSS on my raspberry pi, via the prebuilt docker image.
I have found a workaround, but fixing it in the upstream image could be helpful.

TL;DR: I had to modify permissions on two directories inside the container to get it to work:
```
chown www-data:www-data /var/lib/php/sessions
chmod 1777 /tmp
```

# Full report

I am running the latest stable Raspberry Pi OS. I tried to install FreshRSS via docker, per the instructions [in the readme.](https://github.com/FreshRSS/FreshRSS/tree/master/Docker#deploy-freshrss-with-docker)

After installing the prerequisites and creating the necessary volumes, I started the container:
```
docker run [...] freshrss/freshrss-arm
```

When I navigated to the webpage to complete the setup, I couldn't progress past the first step. I would select English as the language, hit submit, and the same page reloaded.

`docker logs` gave the following information:
```
PHP Warning:  session_start(): open(/var/lib/php/sessions/[...], O_RDWR) failed: Permission denied (13) in /var/www/FreshRSS/lib/Minz/Session.php on line 74
PHP Warning:  session_start(): Failed to read session data: files (path: /var/lib/php/sessions) in /var/www/FreshRSS/lib/Minz/Session.php on line 74
```

I had to modify two things in the container to complete the install. I started a shell inside the container via
```
docker exec -it freshrss bash
```

I changed two things:
```
chown www-data:www-data /var/lib/php/sessions
chmod 1777 /tmp
```

After that, the installation was able to proceed normally.

**Comment by Alkarex** [comment]
Hello and sorry for the delay.
I cannot immediately reproduce the problem.

Example of test without problem on a Raspberry Pi 4:

```sh
docker run -it --rm -p 8082:80 freshrss/freshrss:arm
```

or for the rolling release:

```sh
docker run -it --rm -p 8082:80 freshrss/freshrss:edge-arm
```

Could you provide a few more details about the exact `docker run` command you used and volumes?
And maybe try one of my test commands above to narrow down the problem?

**Comment by ryanfox** [comment]
I get the same behavior whether I run it with a freshrss-data volume or not. My usual command to run it is this:

```
sudo docker run -d --restart unless-stopped --log-opt max-size=10m -v freshrss-extensions:/var/www/FreshRSS/extensions   -e 'CRON_MIN=8,38'   -e TZ=America/Chicago   --net freshrss-network   -p 0.0.0.0:8081:80   --name freshrss2 freshrss/freshrss:arm
```

I also get the same running
```
docker run -it --rm -p 8082:80 freshrss/freshrss:arm
```

I see the correct behavior however when I run
```
docker run -it --rm -p 8082:80 freshrss/freshrss:edge-arm
```

I am running it on a raspberry pi model 3B+, if that makes a difference.

**Comment by Alkarex** [comment]
Does it mean that the `freshrss/freshrss:edge-arm` image is not affected by the problem?
If that is the case, then the problem is solved, because `freshrss/freshrss:edge-arm` is the base for our next stable release

**Comment by ryanfox** [comment]
It appears that way, yes.
