### ISSUE TITLE
[BUG] Items not keeping sort by date after a new subscription is added

### ISSUE THREAD

**Issue by pabsi** [FreshRSS/FreshRSS#4405]
**Describe the bug**
I have several subscriptions. Whenever I add a new one, it fetches all latest RSS entries in this feed.
But in the main stream, it only shows this latest subscription, instead of "mixing" its publications with the existing feeds.

**To Reproduce**
1. Have several different feeds
2. Add a new feed
3. Go to main stream and you'll only see the latest feed posts, despite some of them being older than existing ones on your main stream

**Expected behavior**
The entries in the main stream are sorted by published date, not by "subscription added date" (presumably, when FreshRSS fetched the article is the date it uses to sort by "newest").

**Screenshots**
![image](https://user-images.githubusercontent.com/5247611/172175897-0c5662a1-d2db-4da9-b692-bcce8ae1fc13.png)

**Environment information (please complete the following information):**
Latest docker image at the time of writing.

**Additional context**
I am sorry if there is an option in the interface to sort this out, I just didn't find it :\

**Comment by denppa** [comment]
I also have this problem, the feed is sorted by its added date instead of its published date:
![image](https://i.imgur.com/d7NpZ2e.png)

**Comment by Thoreas** [comment]
Encountered the same issue again today:

![image](https://user-images.githubusercontent.com/44213940/179071310-4d002c81-fb81-44bf-b70c-a4ad6c25ef71.png)

**Comment by EasternPA** [comment]
Just installed today and I'm wondering if this is what I'm seeing. Items in my Main Feed are grouped by provider, not sorted by date published. What can I expect on future refreshes? Will the entries gradually become commingled or will the Main Feed always group all new entries together by provider?

**Comment by Alkarex** [comment]
As for now, this is per design, and if you let the system run for some time (especially with an automated cron job to get new articles), it will look more natural.
Multiple duplicates:
* https://github.com/FreshRSS/FreshRSS/issues/2596#issuecomment-546586703
* https://github.com/FreshRSS/FreshRSS/issues/2083#issuecomment-433622668
* https://github.com/FreshRSS/FreshRSS/issues/1771#issuecomment-359195655
* Etc.

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/7149
