### ISSUE TITLE
[BUG] Installation could not pass step 1 (step0)

### ISSUE THREAD

**Issue by rom1v** [FreshRSS/FreshRSS#4408]
**Describe the bug**
When I go to `rss.mydomain.com` to start the installation, I get this page (with url `http://rss.mydomain.com/i/index.php?step=0`):

![freshrss_step0](https://user-images.githubusercontent.com/543275/172586968-ce1b6e9b-28b9-4d13-8042-cfec28819ee2.png)

If I click on `Valider` (OK), then I am redirected to the very same page again and again, I can't pass this step.

**To Reproduce**
1. Git clone FreshRSS and checkout tag 1.19.2 to `/home/debian/FreshRSS`
2. Create a symlink from `/home/debian/FreshRSS/p` to `/var/www/rss`
3. Configure nginx to expose a site `rss.mydomain.com` which point to `/var/www/rss` (see below)
4. Open `http://rss.mydomain.com`
5. See error → Impossible to pass step 1 (step0 in the url)

**Expected behavior**
It should be possible to pass the first step.

**Environment information (please complete the following information):**
- Device: Laptop
- OS: Debian 11
- Browser: Firefox 100
- FreshRSS version: 1.19.2 (git tag)
- Database version: psql
- PHP version: phh 7.4
- Installation type: git clone

Here is my nginx conf for this site (`/etc/nginx/sites-enabled/rss.mydomain.com`)
```
server {
	listen 80;
	listen [::]:80;

	server_name rss.mydomain.com;

	root /var/www/rss;
	index index.html index.php;

	access_log /var/log/nginx/rss.access.log;
	error_log /var/log/nginx/rss.error.log;

	location ~ \.php$ {
		include snippets/fastcgi-php.conf;
	
		# With php-fpm (or other unix sockets):
		fastcgi_pass unix:/var/run/php/php-fpm.sock;
	}
}
```

**Comment by rom1v** [comment]
> Browser: Firefox 100

Oh, i tested with chromium, I can pass this step :open_mouth:

**Comment by Alkarex** [comment]
This is typically a sign of cookie / session problem, either on server side or on client side. Please check you Web browser logs and your Web server logs

**Comment by rom1v** [comment]
Thank you for your response.

> This is typically a sign of cookie / session problem, either on server side or on client side. Please check you Web browser logs and your Web server logs

OK, possibly. I also had this problem in settings (clicking a button did nothing).
I was migrating (in fact, performing a fresh install) from a server to another (with the same URL), so that's probably that.
