### ISSUE TITLE
[BUG] PHP 8.1 Deprecated error

### ISSUE THREAD

**Issue by triatic** [FreshRSS/FreshRSS#4410]
**Describe the bug**
PHP 8.1 error - PHP Deprecated:  htmlspecialchars() is triggered when opening feed settings.

[Sat Jun 11 16:36:47.643857 2022] [proxy_fcgi:error] [pid 25292:tid 140616258250304] [client x.x.x.x:58381] AH01071: Got error 'PHP message: PHP Deprecated:  htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /home/ubuntu/FreshRSS/lib/Minz/Helper.php on line 20'

**To Reproduce**
1. Go to Subscription management page
2. Click on the cog next to any feed
3. Check the PHP error log for the message

**Expected behavior**
No error.

**Comment by Alkarex** [comment]
Could you please try this fix? https://github.com/FreshRSS/FreshRSS/pull/4411

**Comment by triatic** [comment]
Thanks. I'm seeing a new error now:

`[Sat Jun 11 18:28:09.305214 2022] [proxy_fcgi:error] [pid 25293:tid 140616233072192] [client x.x.x.x:50486] AH01071: Got error 'PHP message: PHP Deprecated:  htmlspecialchars_decode(): Passing null to parameter #1 ($string) of type string is deprecated in /home/ubuntu/FreshRSS/app/layout/header.phtml on line 19'`

**Comment by Alkarex** [comment]
Please try again

**Comment by triatic** [comment]
Thank you, no errors this time.
