### ISSUE TITLE
[Feature] OVH hosting, cannot add feed because of captcha

### ISSUE THREAD

**Issue by Fabiensk** [FreshRSS/FreshRSS#4412]
**Describe the bug**
When FreshRSS is hosted on a mutualized hosting from OVH, some sites don't return the actual RSS feed, but a HTML captcha page. 

Sites with issue:
* https://www.anticor.org/feed/
* https://lehollandaisvolant.net/rss.php

No problem with the same version of FreshRSS installed on my local machine.

**To Reproduce**
1. Install FreshRSS on a mutualized web hosting from OVH (I suspect that it happens with any hosting IP from OVH; OVH is also my ISP and I don't have the issue from my home connection).
2. Add the feed, an error message is displayed:

> The newsfeed could not be added. Check FreshRSS logs for details. You can try force adding by appending #force_feed to the URL.

 and in the logs page of FreshRSS:

> A feed could not be found at `https://www.anticor.org/feed/`; the status code is `200` and content-type is `text/html`

In the page (dumped by modifying `SimplePie.php`), I can see

```
<h4 id="text">www.anticor.org</h4>
<p class="cap_note cap_text count_down">
is protected by Imunify360
</p>
```
and
```We have noticed an unusual activity from your <b>IP [REDACTED, OVH IP]</b> and blocked access to this website.```

**Expected behavior**
It's expected that FreshRSS cannot load a webpage that is not a feed, but it would be nice either:
* to have a way to identify that response is a captcha page in order to help the investigation
* to display/log a part of the response, and/or the size of the response (in my case it was not at all the same than the request done on my local machine).
Or it could be useful to mention that in the FAQ.

**Screenshots**

**Environment information (please complete the following information):**
- Device: N/A
- OS: Linux, OVH hosting
- Browser: Firefox 101.0.1
- FreshRSS version: 1.19.2
- Database version: Mysql 8.1.0 
- PHP version: 8.1.0
- Installation type: github source installed in OVH mutualized machine

**Comment by Alkarex** [comment]
Hello,
Regarding those two specific feeds, could you try to cURL them from your server and check whether you get a better response than in FreshRSS? If that works, you might be able to change the user-agent or another cURL setting for those feeds in FreshRSS.

```sh
curl -v 'https://www.anticor.org/feed/'
```

I have just tried from 4 different OVH servers (Kimsufi + VPS) without problem.

**Comment by Fabiensk** [comment]
Hi Alkarex, now it works from the FreshRSS installed on my web hosting. I guess that the Imunify360 protection stopped detecting abuses from the IP of my web server or its IP range.
The owner of lehollandaisvolant.net added the IP reported as suspicious to a white list and then it started working (I guess it could stop at any time because I don't know if such IPs are fixed).
I cannot use the curl executable there because it's not a rented server, but only a web hosting (I can only access using sftp and with the HTML/PHP apps I install on my account).
