### ISSUE TITLE
API: Improve Google Reader API level 2 compatibility

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#443]
More specific follow up of https://github.com/FreshRSS/FreshRSS/issues/13 and https://github.com/FreshRSS/FreshRSS/issues/328

FreshRSS already supports quite well [News+](https://play.google.com/store/apps/details?id=com.noinnion.android.newsplus) (https://github.com/noinnion/newsplus ).

It was also tested against a [modified version](https://github.com/Alkarex/gReader-Library) of https://github.com/ericmann/gReader-Library

It is currently being tested (~~alpha~~ beta quality) against a [fork of EasyRSS](https://github.com/Alkarex/EasyRSS) (https://play.google.com/store/apps/details?id=com.pursuer.reader.easyrss).

To improve compatibility, it would be nice to check with additional clients.

See [how to get started with the API](https://github.com/FreshRSS/FreshRSS/issues/443#issuecomment-36666133)

**Comment by ghost** [comment]
I try to login with News+ and the forked EasyRSS. With both apps, I receive a failed login.

I'm running the dev branch, LAMP, http, checked successfully the API, generated the API key, enabled the API, etc... There are NO logs in data/logs.

Please help!?

**Comment by ghost** [comment]
FYI: I use this info:

http://my.serv.er/p/api/greader.php
jeroen
theAPIkey

**Comment by Alkarex** [comment]
@jeroenpraat If you are running /dev, please have a look at the logs into `FreshRSS/data/users/_/log_api.txt`. Also, do you have any error code shown in News+ (e.g. 401).

**Comment by ghost** [comment]
There is no log_api.txt there. Only log.txt and that had one or two feed errors. The error code in News+ is 'login failure' and the error code in EasyRSS was something like 'wrong username and/or password'.

**Comment by Alkarex** [comment]
Please be sure to set your API password in `/p/i/?c=user&a=profile` for the username you are trying to log into from the mobile app. This is the password to use in the mobile apps.
If this is not enough,  then please test greader.php from your browser. The expected answer is "Bad Request!", which should also be written in the `FreshRSS/data/users/_/log_api.txt`. Please check that you have this underscore directory under users, that your web server is allowed to write there, and check if there is no error in your PHP/Apache log.

**Comment by ghost** [comment]
Oh I'm sorry, looked indeed in the directory of the default user and not with the underscore. There is indeed an api log in there. Where to look for?

**Comment by ghost** [comment]
```
User =>
clientLogin(jeroen)
unauthorized()
Array
(
```

```
    [_POST] => Array
        (
            [Email] => jeroen
            [Passwd] => xxxxxxxxxxxxxxxxxx
            [accountType] => GOOGLE
            [service] => reader
            [source] => Sun-EasyRSS
        )
```

**Comment by Alkarex** [comment]
@jeroenpraat  Please double-check that you are using the user's API password and not the user's main password. See `/p/i/?c=user&a=profile`

**Comment by ghost** [comment]
It works! I copied and pasted the api-password from the logs and pasted it in Password API under profile. I don't know why this was not set in the first place. Oh well, nevermind. And thanks for your help!

**Comment by ghost** [comment]
Oh BTW. The fork of easyRSS is great! Should be made the default freshRSS if I was the one to decide.

**Comment by Alwaysin** [comment]
Looks like News+ does not require "AllowEncodedSlashes On" anymore ; I've managed to synchronise without this option.

**Comment by Alkarex** [comment]
@Alwaysin I have just checked, and News+ still encodes the slashes to `%2F`, which may, or may not be accepted by your Web server depending on the version and [configuration](http://httpd.apache.org/docs/trunk/mod/core.html#allowencodedslashes).

**Comment by ghost** [comment]
As far as `getallheaders` is concerned, would it be possible to use one of the approaches described here to resolve the issue?

https://secure.php.net/getallheaders

**Comment by Alkarex** [comment]
@squarefractal Which issue / problem are you talking about?

**Comment by ghost** [comment]
@Alkarex:
The Google reader API fails to work on configurations using php-fpm due to the absence of `getallheaders()`, so, would it be possible to add one of the implementations discussed in the comments section of [this page](https://secure.php.net/getallheaders) to work around this issue?

**Comment by Alkarex** [comment]
@squarefractal Ok. Could you please create a new dedicated issue for that?

**Comment by ghost** [comment]
Opened #1127 as per @Alkarex's request

**Comment by Alkarex** [comment]
Completed with:
- https://github.com/FreshRSS/FreshRSS/issues/1252
- https://github.com/FreshRSS/FreshRSS/issues/1254
- https://github.com/FreshRSS/FreshRSS/pull/1261
