### ISSUE TITLE
[BUG] feed doesnt get added

### ISSUE THREAD

**Issue by rezad1393** [FreshRSS/FreshRSS#4440]
**Describe the bug**

**To Reproduce**
1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

**Expected behavior**

**Screenshots**

**Environment information (please complete the following information):**
- OS: [e.g. Ubuntu 20.04]
- Browser: [e.g. Firefox 86]
- FreshRSS version: [e.g. 1.17.1]
- Database version: [e.g. Mysql 5.7]
- PHP version: [e.g. PHP 7.4]
- Installation type: [e.g. Yunohost]

**Additional context**

**Comment by Frenzie** [comment]
See #4441

**Comment by rezad1393** [comment]
this was a miss-click of enter key.
