### ISSUE TITLE
[BUG] feed doesnt get added "https://libertarianinstitute.org/feed/"

### ISSUE THREAD

**Issue by rezad1393** [FreshRSS/FreshRSS#4441]
I have version 1.19.2 installed on my lan.
this feed just give unknown error.

I also have a wan domain on internet that has  1.20.0-dev  installed .
on that instance it gets added.
is this a bug that gets fixed in the master version?
should I wait for that or can I fix it now?

**Comment by Frenzie** [comment]
It works on my 1.19.2. Does the log say anything more?

**Comment by rezad1393** [comment]
so...
it may be my network.
in my country (iran) government does a lot of stuff to net that causes it to behave weird.
for example this,
```
curl -v https://libertarianinstitute.org/feed
*   Trying 68.183.249.226:443...
* Connected to libertarianinstitute.org (68.183.249.226) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):


```

it just times out.
but in firefox it opens.

**Comment by rezad1393** [comment]
so it is not this software issue.

**Comment by Frenzie** [comment]
Strange, but good to know the cause.

**Comment by rezad1393** [comment]
probably a middlebox for censorship is acting messing with it.
I had this issue before with some other website too but forgot to compare it with wireshark to see what is the diff between firefox and curl.
