### ISSUE TITLE
[BUG] "Hide after read" and "mark on scroll" clears the whole list feed by feed.

### ISSUE THREAD

**Issue by einmueller** [FreshRSS/FreshRSS#4446]
**Describe the bug**
I like the feature of "mark read on scroll" and "hide read articles" because I can scroll the list for interesting
articles, stop and going on later with only unseen items.

But when I activate both options, the top article gets marked as read even if it  only some pixels are out of screen. (That happens, when scrolling with the mouse wheel.) When the article is marked as read, it gets hidden, the next one is above, gets marked read, gets hidden and so on... The whole list gets marked one by one.

**To Reproduce**
1. enable "hide after read" and "mark on scroll"
2. got to article list
3. Scroll down with mouse wheel with some stops, like if you try to read the headlines.

**Expected behavior**
The article should be marked as read if it is fully out of screen (or perhaps if the next one is out of screen, 
perhaps easier to implement and so extra security for fast scrollers)

**Screenshots**
would have to be a movie ;-)

**Environment information (please complete the following information):**
- Device: Desktop 
- OS: seen on Manjaro and Windows 10
- Browser: Firefox 91.11.0esr and 102.0.1 and Chromium 103.0.5060.114 
- FreshRSS version: 1.19.2 (latest docker, default setup)
- Database version: sqlite
- PHP version: ... don't know what is used i docker
- Installation type: docker-compose like mentioned on freshrss documentation

**Additional context**

**Comment by math-GH** [comment]
I can confirm this bug.

**Comment by math-GH** [comment]
@einmueller please check #4471
