### ISSUE TITLE
Nord theme: loads every article

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#4447]
I think there's definetly a problem with this theme. On latest Chrome version on Windows, my tab of FreshRSS uses less than 200Mo of memory. When I switch to this theme, it uses circa 1Go. That's probably why it sometimes don't show the banner.
It is even more visible on a mobile phone, everything is so slow.

EDIT: Got it, the theme is loading EVERY article. I have 14000+ unread, so yeah.

_Originally posted by @Alwaysin in https://github.com/FreshRSS/FreshRSS/issues/4400#issuecomment-1186154075_

**Comment by math-GH** [comment]
I can confirm it with Firefox on Windows too

**Comment by Frenzie** [comment]
Which specific combination of FreshRSS settings is required for that?

**Comment by math-GH** [comment]
Theme: Nord theme
version: 1.20.0-dev
Config: Configs -> Reading -> Load more articles at the bottom of page

How to test it:
1. go to normal view
2. have a long list of articles in the list (use the filter to create a long list)
3. see the length of scroll bar
4. scroll a little bit down
5. see the length of scroll bar (there you will see that the list became very long)

**Comment by Frenzie** [comment]
That's the default config and that's what I did. I don't see any trouble. The scrollbar grows the normal amount.

**Comment by Frenzie** [comment]
I.e., there's something else. :-)

**Comment by Alwaysin** [comment]
@Frenzie Trying with a brand new installation of FreshRSS, just unchecking "mark as read while scrolling" and it does it, see the video:

https://imgur.com/1A75jdC

See how on default theme the scrollbar doesn't move until going way down and how on Nord, it charges new articles every tiny scroll down.

**Comment by Frenzie** [comment]
Yes, I get the idea, but I can't reproduce that.

**Comment by Alwaysin** [comment]
Same behaviour on latest Chrome and Firefox on Windows.
FreshRSS is running on PHP 8.1 on Ubuntu 22.04 if that may help.

Settings really are the defaults, I attached them if you want to have a look (this is the brand new test instance):
[config.txt](https://github.com/FreshRSS/FreshRSS/files/9127340/config.txt)
[user-config.txt](https://github.com/FreshRSS/FreshRSS/files/9127341/user-config.txt)

**Comment by Frenzie** [comment]
The config is identical as expected, save for the password and such of course, and **the language**. Changing the language to French reproduces the problem.

**Comment by Frenzie** [comment]
The problem lies in this line:
https://github.com/FreshRSS/FreshRSS/blob/4f32939ec3500d08a2b68cf02cb7a7b49f2b7dee/p/themes/Nord/nord.css#L471

**Comment by Frenzie** [comment]
Could you confirm if this fixes it?

```diff
diff --git a/p/themes/Nord/nord.css b/p/themes/Nord/nord.css
index 428e0195..22f9fb19 100644
--- a/p/themes/Nord/nord.css
+++ b/p/themes/Nord/nord.css
@@ -468,7 +468,7 @@ img.favicon {
 
 /*=== Body */
 #global {
-       height: calc(100% - 85px);
+       height: calc(100vh - 85px);
 }
 
 .aside {
```

**Comment by Alwaysin** [comment]
Good catch for the language!

Just changing this line apparently is not enough though :(

**Comment by Frenzie** [comment]
It solves the problem for me. :-/ Did you make sure to Ctrl+F5/Ctrl+Shift+R/however one torpedoes the cache?

**Comment by math-GH** [comment]
For me, it does not solve it too.

I wonder why `#global` is needed in this theme. I deleted it and cannot find any difference.

**Comment by Frenzie** [comment]
It's simply a line copied from Origine or perhaps some other theme. It's working around some issue although I'm not completely sure what the issue might be.

https://github.com/FreshRSS/FreshRSS/commit/0878b32fafb0deccb11b1bcbaa44e04724a2200e

The header height no longer seems to exist in Origine though? Maybe it's no longer necessary.

Edit: the entire thing should be rewritten in grid and/or flex sometime really, but I don't have time to.

**Comment by math-GH** [comment]
Got it.

@Frenzie @Alwaysin : Please check #4451

**Comment by Alwaysin** [comment]
Thanks @math-GH ! It works this way!
