### ISSUE TITLE
[Feature] force update time for WebSub feeds

### ISSUE THREAD

**Issue by yzqzss** [FreshRSS/FreshRSS#4448]
If FreshRSS is offline while WebSub is pushing updates, you will never(I'm not sure) receive missed articles unless you go to subscription manage to manually update or wait for the next WebSub push.

Also, sometimes some websites may not push WebSub under certain circumstances (eg: migrating website, importing database, modifying articles directly in the database, recovering from a misconfiguration, etc).

---
Maybe it is possible to offer an special automatic refresh time for WebSub, which can be longer than the general feeds refresh time, such as 1~3 days?

**Comment by Alkarex** [comment]
Hello,
By default, feeds with a working WebSub will be pulled once every day anyway. If articles are discovered that were not received by WebSub, the WebSub status is set to *not working*, and a normal pull frequency will be used until the next article is received by WebSub, which will be used to signal that the WebSub of that feed is working.

**Comment by yzqzss** [comment]
> Hello, By default, feeds with a working WebSub will be pulled once every day anyway. If articles are discovered that were not received by WebSub, the WebSub status is set to _not working_, and a normal pull frequency will be used until the next article is received by WebSub, which will be used to signal that the WebSub of that feed is working.

Thanks for your answer.🥲
