### ISSUE TITLE
[BUG] youtube feed gets replaces with https://www.scriptbarrel.com/xml.cgi?channel_id=

### ISSUE THREAD

**Issue by rezad1393** [FreshRSS/FreshRSS#4454]
**Describe the bug**
when I add a youtube channel feed I get this as feed url
https://www.scriptbarrel.com/xml.cgi?channel_id=cahnnelid

**Comment by Alkarex** [comment]
Hello,
Do you use any YouTube extension in FreshRSS?

Without any YouTube extension, when I try to subscribe to e.g. https://www.youtube.com/c/tennistv it works properly.

**Comment by rezad1393** [comment]
you are absolutely right.
I had this 
YouTubeChannel2RssFeed
