### ISSUE TITLE
[BUG] Impossible d'ajouter un flux 

### ISSUE THREAD

**Issue by Jagounet** [FreshRSS/FreshRSS#4458]
Bonjour, 

Il m'est impossible d'ajouter ce flux : https://rappel.conso.gouv.fr/rss?categorie=01

J'obtiens le message d'erreur suivant : Le flux ne peut pas être ajouté. [Consulter les logs de FreshRSS](https://www.EEE.com/rss/p/i/?a=logs) pour plus de détails. Vous pouvez essayer de forcer l’ajout par addition de #force_feed à l’URL.

- FreshRSS version: 1.19.2
- Database version: SQLite
- PHP version: 8.1.7
- Installation type: mutualisé ovh

Comment faire s'il vous plait ?

**Comment by Frenzie** [comment]
Ça marche pour moi, donc ce que disent ces logs est probablement très important. ;-)

**Comment by Jagounet** [comment]
2022-07-23 10:32:01
Unknown error for feed [https://rappel.conso.gouv.fr/rss?categorie=01]

**Comment by Frenzie** [comment]
Hm, not a very helpful error message. Are you able to run curl on that server? E.g., a simple `curl -v 'https://rappel.conso.gouv.fr/rss?categorie=01'` for starters.

**Comment by Jagounet** [comment]
Sorry I don't know anything about all this... I'm sure with shared hosting!
How do we do?
 (Google trad !)

**Comment by Frenzie** [comment]
There's no need to write in English, at least for my benefit. :-) I speak French, but of course that doesn't apply to everyone who might read along. But writing French takes a lot more mental energy than reading it. 

@Alkarex do you have any troubleshooting suggestions for shared hosting?

**Comment by Jagounet** [comment]
Personne pour m'aider ?

**Comment by Alkarex** [comment]
@Jagounet Essayez de mettre ce fichier sur votre serveur, par exemple dans le répertoire `/p/` de FreshRSS, soit `/p/test.php` :

```php
<?php
$url =  'https://rappel.conso.gouv.fr/rss?categorie=01';

$ch = curl_init($url);
curl_setopt_array($ch, [
		CURLOPT_RETURNTRANSFER => true,
		CURLOPT_TIMEOUT => 15,
		CURLOPT_ENCODING => '',	//Enable all encodings
	]);
$c_response = curl_exec($ch);
$c_info = curl_getinfo($ch);
$c_error = curl_error($ch);
curl_close($ch);

header('X-Curl-Info: ' . json_encode($c_info));
header('X-Curl-Error: ' . json_encode($c_error));

header('Content-Type: application/rss+xml; charset=utf-8');
echo $c_response;
```

et puis de l'appeler :

```
curl -v 'https://votre-freshrss.example.net/test.php'
```

**Comment by Jagounet** [comment]
Bonjour, 

J'ai un probleme avec `curl -v 'https://votre-freshrss.example.net/test.php`

Je le met dans la barre d'adresse ca me fait une recherche sur google !

**Comment by Alkarex** [comment]
@youknow0 Il faut remplacer par votre propre adresse.
Vous pouvez essayer de coller juste l'adresse dans votre navigateur, mais la commande complète avec cURL se met dans un terminal (ligne de commande / console).

**Comment by Jagounet** [comment]
Je sais bien pour mon adresse, 

Direct j'obtiens ca : `<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
</body></html>`

Sinon en ligne de commande je veux bien mais ou ? Comment faire ? c'est un herbgement mutu

**Comment by Alkarex** [comment]
@Jagounet En ligne de commande, dans n'importe quel terminal (ligne de commande / console), par exemple sur votre ordinateur local.

**Comment by Jagounet** [comment]
Bonjour, 

J'obtiens ceci avec l'invite de commande sur windows : `* Closing connection -1
curl: (3) URL using bad/illegal format or missing URL`

**Comment by benborges** [comment]
> @Jagounet Essayez de mettre ce fichier sur votre serveur, par exemple dans le répertoire `/p/` de FreshRSS, soit `/p/test.php` :
> 
> ```
> <?php
> $url =  'https://rappel.conso.gouv.fr/rss?categorie=01';
> 
> $ch = curl_init($url);
> curl_setopt_array($ch, [
> 		CURLOPT_RETURNTRANSFER => true,
> 		CURLOPT_TIMEOUT => 15,
> 		CURLOPT_ENCODING => '',	//Enable all encodings
> 	]);
> $c_response = curl_exec($ch);
> $c_info = curl_getinfo($ch);
> $c_error = curl_error($ch);
> curl_close($ch);
> 
> header('X-Curl-Info: ' . json_encode($c_info));
> header('X-Curl-Error: ' . json_encode($c_error));
> 
> header('Content-Type: application/rss+xml; charset=utf-8');
> echo $c_response;
> ```
> 
> et puis de l'appeler :
> 
> ```
> curl -v 'https://votre-freshrss.example.net/test.php'
> ```

 

Bonjour, comment je peux tester ça (j'ai le même problème avec un autre flux) mais dans mon stack docker où /p/ n'est pas possible en écriture. Si je met test.php à la racine de mon container, curl ne trouve pas le fichier

log SQL error updateFeed: Data too long for column 'website' at row 1 for feed 58

le flux que j'essaie d'ajouter est : https://amplifyukraine.eu/category/belarus/feed/ mais sans succès alors que https://amplifyukraine.eu/feed/ fonctionne très bien..

![image](https://user-images.githubusercontent.com/10617712/182120717-f647ded0-818c-4228-870b-e4bbf0136e65.png)

**Comment by Jagounet** [comment]
J'ai laissé tomber, si j'ai trouvé une solution plus simple si ca peut aider... Quand un flux fonctionne pas avec Fresh je passe par https://feedfry.com pour avoir un lien rss qui fonctionne dans fresh.

**Comment by Alkarex** [comment]
Je ne peux pas reproduire de problème avec ce flux.
Dans Docker, la racine de FreshRSS se trouve à `/var/www/FreshRSS/p/`
