### ISSUE TITLE
Minify CSS and JS files

### ISSUE THREAD

**Issue by aledeg** [FreshRSS/FreshRSS#446]
To continue the optimization process started here => #341, I think it will be a good idea to minify CSS and JS files.

There is many tools available online, here is a few:
- http://closure-compiler.appspot.com/home
- http://jscompress.com/
- http://refresh-sf.com/yui/
- http://cssminifier.com/

**Comment by math-GH** [comment]
Could we include a minifier into our pipeline?

**Comment by Alkarex** [comment]
> Could we include a minifier into our pipeline?

I am not so found of it. Our JavaScript / CSS code is relatively short (compared to other applications / Web sites nowadays), and the build-in gzip compress already does a good job, supplemented by HTTP caching.
It would only increase obscurity, barrier to entry, and difficulty to debug.

**Comment by math-GH** [comment]
You are right. Then I vote for to close this ticket
