### ISSUE TITLE
Advice / Help needed. FeedFetcher-Google

### ISSUE THREAD

**Issue by SenorDuende** [FreshRSS/FreshRSS#4461]
I've a self hosted version of FreshRSS running for a years or so. Admin and one user. 85ish feeds. Running perfectly fine until a week ago when bandwidth spiked from a few meg per day to 2Gb in a day. 

viewing logs there is just an endless stream of hits to:
66.249.93.79 - - [25/Jul/2022:08:33:33 -0400] "POST /freshrss/p/api/pshb.php?k=f1744c440a97cdee7a03d05e720da32a588e9cce HTTP/1.1" 410 721 "-" "FeedFetcher-Google; (+http://www.google.com/feedfetcher.html)"
66.249.93.79 - - [25/Jul/2022:08:33:35 -0400] "POST /freshrss/p/api/pshb.php?k=f1744c440a97cdee7a03d05e720da32a588e9cce HTTP/1.1" 410 721 "-" "FeedFetcher-Google; (+http://www.google.com/feedfetcher.html)"
66.249.93.79 - - [25/Jul/2022:08:33:35 -0400] "POST /freshrss/p/api/pshb.php?k=f1744c440a97cdee7a03d05e720da32a588e9cce HTTP/1.1" 410 721 "-" "FeedFetcher-Google; (+http://www.google.com/feedfetcher.html)"
66.249.93.79 - - [25/Jul/2022:08:33:36 -0400] "POST /freshrss/p/api/pshb.php?k=f1744c440a97cdee7a03d05e720da32a588e9cce HTTP/1.1" 410 721 "-" "FeedFetcher-Google; (+http://www.google.com/feedfetcher.html)"
66.249.93.79 - - [25/Jul/2022:08:33:39 -0400] "POST /freshrss/p/api/pshb.php?k=f1744c440a97cdee7a03d05e720da32a588e9cce 

From what I can ascertain FeedFetcher-Google is trying to retrieve a feed from the site. But there are no posts on this site, nothing is shared. 

Would really appreciate some guidance on what to do. Thanks in advance.

SD

**Comment by Frenzie** [comment]
Google is DDOSing you, huh? I'm not really sure what to do with that I'm afraid. o.O

**Comment by math-GH** [comment]
You could block the IP address (f.e. via .htdocs if you use Apache)

**Comment by Alkarex** [comment]
Hello,
Which version of FreshRSS are you running?
According to the logs, FreshRSS is returning `HTTP/1.1 410 Gone`, which is the standard to inform the hub not to continue sending updates https://www.w3.org/TR/websub/#content-distribution
It looks like a bug on one of Google's Hubs.
To reduce traffic, adding a deny rule at HTTP level would not change much (almost same amount of data compared to an HTTP 410 response, maybe even a bit more), but a deny rule at IP level could be a mitigation.
For instance with `ufw deny from 66.249.93.79` for a few days

**Comment by SenorDuende** [comment]
Hi all, thanks for the input.

FreshRSS version 1.19.2
Installation check passes all tests

have put in IP blocks in htaccess , but as you say @Alkarex it has little impact. So next is at IP level.

also

RewriteCond %{HTTP_USER_AGENT} Feedfetcher-Google
RewriteRule .* - [F] 

I've suspended user in the interim. 

Continue to seek a solution

Regards

SD

**Comment by math-GH** [comment]
Do you have an active `default` user, so that there is a public RSS feed?
Disable the default user, so that there is no public RSS feed and the Google Feedfetcher should stop to crawl your feed.

**Comment by marienfressinaud** [comment]
Google FeedFetcher is not actually fetching a feed, it sends notifications for new content for a feed served over WebSub (ex PubSubHubbub): logs are showing `POST` requests on `pshb.php` which is the endpoint for Websub requests. I don't know why it's behaving like this though.

**Comment by Alkarex** [comment]
Indeed, this is a WebSub push, not a pull, and not related to a default user or having a feed exposed

**Comment by SenorDuende** [comment]
@math-GH  > Do you have an active `default` user, so that there is a public RSS feed? Disable the default user, so that there is no public RSS feed and the Google Feedfetcher should stop to crawl your feed.

Not clear what you mean by active `default` user. I understand that the default user is the one at initial installation, the admin account and "The default user is always an administrator. It is impossible to demote or disable the user."  There in one other user, this is the one that all my feeds for reading are on. To the best of my knowledge nothing is exposed.

@marienfressinaud & @Alkarex if this is push then it's even more confusing. Any idea what would trigger this type of request? More importantly, how does one disable it? 

The account is now in suspension for exceeding bandwidth but from the logs the hits from Google Feedfetcher are still almost continuous & uninterupted (every few seconds)
![Screenshot 2022-07-28](https://user-images.githubusercontent.com/109974653/181496175-1ab41f0b-a878-45c7-b13f-5dafc9d8b457.png)

**Comment by marienfressinaud** [comment]
This happens because one of the feed that you or your user follows is served over Websub / PubSubHubbub. You can try to improve things by disabling it by setting `'pubsubhubbub_enabled' => false` in your `data/config.php` file. Note that Google will probably not stop immediately to ping your server, but hopefully it will stop in few hours or days.

At least, this is not your user fault and he has nothing to do with that, so you can reactive his account.

As suggested by @Alkarex, your best option is to block the Google IP at a firewall level:

>  For instance with `ufw deny from 66.249.93.79` for a few days

Edit: note that Websub should NOT produce this kind of behaviour from hubs, the issue comes from Google.

**Comment by Alkarex** [comment]
Disabling the user, disabling pubsubhubbub, or adding HTTP deny rules will probably not help at this stage and might even do more harm than good, at least on the trafic (and the proper response to stop is 410, not 404 or 403), so my suggestion is still to block the IP for a few days and check again later.
As stated higher up, this is quite clearly a bug in one of Google's hubs.

But in order to get more information for debugging, it would be nice to log the payload that is received. This can be done by un-commenting this line:

https://github.com/FreshRSS/FreshRSS/blob/edge/p/api/pshb.php#L15

and then check `./freshrss/data/users_/log_pshb.txt`

We might be able to reproduce the problem with the same feed, report the bug upstream, and/or add workarounds in FreshRSS, for instance by unsubscribing multiple times.

**Comment by marienfressinaud** [comment]
It took me a moment before realising that I had the same issue (my Nginx logs don't show Googlebot useragent).

I had to block the following IPs:

- 66.102.8.192
- 66.102.8.194
- 66.102.8.196

I sent an email to report abuse at network-abuse(at)google.com but I don't expect any answer.

Here are my [Websub logs](https://github.com/FreshRSS/FreshRSS/files/9222145/log.txt). It seems the bot is only noticing me about content at https://security.googleblog.com/

**Comment by Frenzie** [comment]
Btw, you guys probably saw https://drewdevault.com/2022/05/25/Google-has-been-DDoSing-sourcehut.html but just in case you didn't.

**Comment by SenorDuende** [comment]
Resolved. 

From the input I was able to understand, albeit minimally, what PubSubHubbub is and what was happening. Went through the server logs and FreshRSS logs and found four instances of requests from PubSubHubbub that also corresponded to the dates when traffic increased. Two are shown below:

An article was discovered by pull although we use PubSubHubbub!: Feed http://feeds.feedburner.com/UasVision GUID https://www.uasvision.com/?p=86078

An article was discovered by pull although we use PubSubHubbub!: Feed http://feeds.feedburner.com/m2mworldnews GUID https://iotbusinessnews.com/?p=38077

Deleted each of these feeds and some hours later the traffic from Google Feedfetcher dropped off significantly and then stopped all together. Traffic returned to normal levels and has remained so for the past 3 days. 

Thank you all for your contribution and help, much appreciated.

**Comment by Alkarex** [comment]
@marienfressinaud Is it the same payload sent again and again? Are those feeds you are still subscribed to?

**Comment by Alkarex** [comment]
I can reproduce the behaviour with https://security.googleblog.com/ after having just subscribed to it.
It seems to also push old articles, in loop

**Comment by Alkarex** [comment]
Any idea on how to contact someone from http://www.google.com/feedfetcher.html ?

**Comment by marienfressinaud** [comment]
> @marienfressinaud Is it the same payload sent again and again? Are those feeds you are still subscribed to?

It seems to only be the feed from Google Security blog (subscribe to by one of my user). What bothers me is that the payload is always changing (on 6 records, I have a `content-length` of 90994, 108092, 22484, 161559, 45986 and 348783). It seems the articles are not always the same in the payload.

> Any idea on how to contact someone from http://www.google.com/feedfetcher.html ?

I tried `googlebot(at)googlebot.com` (indicated in the `From` header) and `network-abuse(at)google.com` from `whois`, but the first no longer exists and I got an automatic answer from the second saying to pass by https://about.google/contact-google/ (which is very generic)

We may try to reach them by Twitter, but I don't know why, I feel like it would be useless :)

**Edit:** I tried https://twitter.com/FreshRSS/status/1554532248493248512

> I had to block the following IPs: […]

Other IPs have taken over and Google has probably more IPs than I have time to block each of them, so I fear it's not a solution either.

**Comment by SenorDuende** [comment]
@marienfressinaud blocking the IP seemed to have little impact in my case either. Google Feedfetcher  just switched to another IP. 
66.249.93.79
66.249.93.81
66.249.93.83
74.125.210.111
74.125.210.113
74.125.210.115
66.249.93.95
66.249.93.71
66.249.93.65

**Comment by laBecasse** [comment]
Hello :) 
I am facing the same problem with half of the traffic generated by the GoogleFetcher bot. Even if the HTTP requests are accepted in my case, they are ways too frequent. So I decided to use fail2ban to reduce the traffic : 

the filter
```
[Definition]

failregex = ^<HOST> \- \S+ \[\] \"POST /api/pshb\.php.+ \"FeedFetcher-Google; \S+\".*$

ignoreregex = 

datepattern = {^LN-BEG}%%ExY(?P<_sep>[-/.])%%m(?P=_sep)%%d[T ]%%H:%%M:%%S(?:[.,]%%f)?(?:\s*%%z)?
              ^[^\[]*\[({DATE})
              {^LN-BEG}

```

the configuration 
```
[nginx-googlefetcher]
enabled = true
logpath=/var/log/nginx/cheredeprince.net/rss.access.log
maxretry = 6
bantime = 1h
```
