### ISSUE TITLE
[Feature] Know which feed is in error / down

### ISSUE THREAD

**Issue by KatyPurry** [FreshRSS/FreshRSS#4464]
**Is your feature request related to a problem? Please describe.**
I have a non-functional RSS feed but I don't know which one it is.

![image](https://user-images.githubusercontent.com/89610869/181082859-ecd4d8e3-d0be-4f2e-8a30-c59191fafbd1.png)

**Describe the solution you’d like**
Indicate by an icon which one is not working.

**Describe alternatives you’ve considered**
Search.

**Comment by Frenzie** [comment]
Perhaps the issue is simply that it doesn't have anything unread, but it could be the theme is broken in that regard. Which theme is it?

You can also always see in subscription management.

**Comment by KatyPurry** [comment]
Hello, it's Mapco. 

Apparently this is a problem with https://www.01net.com/actualites/feed/

**Comment by Frenzie** [comment]
The Mapco sidebar link styling seems to override the (very slight) color difference there, but not in subscription management.

**Comment by math-GH** [comment]
Which version of FreshRSS do you use?

**Comment by Alkarex** [comment]
Indeed, I can confirm the bug with Mapco, current edge version:

![image](https://user-images.githubusercontent.com/1008324/181502125-ee874f32-90c1-4469-a1c3-a492e6dbfe04.png)

compared with default Origine theme:

![image](https://user-images.githubusercontent.com/1008324/181502310-2f71c823-2c61-4aa0-879c-06ad45237ad5.png)

**Comment by Alkarex** [comment]
@Zazou49 Hint: you can also use the feed management view and filter by broken feed:

`https://freshrss.example.net/i/?c=subscription&error=1`

**Comment by Alkarex** [comment]
![image](https://user-images.githubusercontent.com/1008324/181502807-8d9b80c6-783c-43ea-bb81-c7c9b581cf84.png)

**Comment by KatyPurry** [comment]
> Which version of FreshRSS do you use?

1.19.2 

> @Zazou49 Hint: you can also use the feed management view and filter by broken feed:
> 
> `https://freshrss.example.net/i/?c=subscription&error=1`

Thank you, it worked with this link

> ![image](https://user-images.githubusercontent.com/1008324/181502807-8d9b80c6-783c-43ea-bb81-c7c9b581cf84.png)

This button seems not present in Mapco.

**Comment by math-GH** [comment]
The button is not shown when there is no error

**Comment by math-GH** [comment]
ref #4478
