### ISSUE TITLE
[BUG] "Delete articles" broken

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#4473]
**Describe the bug**
I want to clear a feed and want to delete all articles. But it does not delete the articles

**To Reproduce**
1. Go to subscription management
2. edit a feed
3. Scroll down to "Archiving"
4. click on "Delete all articles"
5. the same amount of articles

**Expected behavior**
0 articles

**Screenshots**
![grafik](https://user-images.githubusercontent.com/1645099/181822949-dfb9ef5e-bfd7-41d1-ab2f-7531d5f62a64.png)

**Environment information (please complete the following information):**
- FreshRSS version: 1.20.0-dev

Tested on the demo: it is not an issue in 1.19.2

**Comment by Alkarex** [comment]
With which database did you experience the bug?

**Comment by math-GH** [comment]
> With which database did you experience the bug?

SQlight

**Comment by Alkarex** [comment]
Ok thanks, bug reproduced

**Comment by Alkarex** [comment]
Due to https://github.com/FreshRSS/FreshRSS/pull/4416
Fix in https://github.com/FreshRSS/FreshRSS/pull/4479 , not tested, feedback welcome
