### ISSUE TITLE
[BUG]504 Gateway Time-out at i/?c=extension

### ISSUE THREAD

**Issue by rezad1393** [FreshRSS/FreshRSS#4484]
when I open the extension page it timeouts after  trying for a while.

2022/08/03 03:29:16 [error] 518#518: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 192.168.1.10, server: odroid, request: "GET /i/?c=extension HTTP/2.0", upstream: "fastcgi://unix:/run/php-fpm/php-fpm.sock", host: "myhost:1083"

**Comment by math-GH** [comment]
Please give us the information, that are asked in the bug template:

**Environment information (please complete the following information):**
- Device: [e.g. iPhone6]
- OS: [e.g. Ubuntu 20.04]
- Browser: [e.g. Firefox 86]
- FreshRSS version: [e.g. 1.17.1]
- Database version: [e.g. Mysql 5.7]
- PHP version: [e.g. PHP 7.4]
- Installation type: [e.g. Yunohost]

**Comment by rezad1393** [comment]
sorry 
i was in a hurry.
device: archlinux armv7l odroid
browser firefox 103.0.1 (64-bit)
 FreshRSS 1.19.2 
Database version 
php-sqlite 8.1.8-1
local/sqlite 3.39.1-1

php 8.1.8
Installation type ?? manual unzip?

**Comment by rezad1393** [comment]
I don't know what was the cause but the error is gone.
