### ISSUE TITLE
[BUG] feed is missing newest items

### ISSUE THREAD

**Issue by fabsenet** [FreshRSS/FreshRSS#4485]
**Describe the bug**
I subscribed to a feed and it is missing the newest 2 items and I cannot figure out why.

**To Reproduce**
1. subscribe to https://www.blackmagicdesign.com/rss
2. latest article is from july 27:
![image](https://user-images.githubusercontent.com/2065705/182802459-3629d85a-2351-4233-92fd-133fbc6e01ee.png)
3. download rss file manually and observe (at the bottom):
```xml
...snipped 2723 lines...
      <item>
        <guid isPermaLink="false">b09922bb99d345a08ee59e4bd4cbbec6</guid>
        <title>Blackmagic Cloud now available in Australia, New Zealand and Singapore!</title>
        <link>https://www.blackmagicdesign.com/products/davinciresolve/collaboration</link>
        <description>...snip...</description>
        <pubDate>Tue, 26 Jul 2022 18:32:31 -0700</pubDate>
      </item>
<!-- the next two items are missing -->
      <item>
        <guid isPermaLink="false">0cbe950526c04c008461a3616e21eb93</guid>
        <title>New Blackmagic Camera 7.9.1 Update!</title>
        <link>https://www.blackmagicdesign.com/support/family/professional-cameras</link>
        <description>...snip...</description>
        <pubDate>Wed, 27 Jul 2022 18:17:10 -0700</pubDate>
      </item>
      <item>
        <guid isPermaLink="false">b911e9d3753043a6a6301430ead43ea1</guid>
        <title>New Cloud Store 1.0.3 update!</title>
        <link>https://www.blackmagicdesign.com/products/blackmagiccloudstore</link>
        <description>...snip...</description>
        <pubDate>Wed, 03 Aug 2022 22:41:08 -0700</pubDate>
      </item>
  </channel>
</rss>
```

**Expected behavior**
two variants:
- it just works and shows the latest articles
- it provides better insights in what is happening so i can maybe fix things

**Environment information:**
- Device: random notebook
- OS: Windows 10
- Browser: firefox 103
- FreshRSS version: 1.19.2 
- Database version: sqlite (maybe? I do not know, did not change it)
- PHP version: 7.4.25
- Installation type: docker like in the manual. it is only some days old

**Comment by fabsenet** [comment]
_unrelated_

**Comment by Frenzie** [comment]
Not a case of a lack of refresh, I can confirm it happens when adding the feed brand new. It's not clear to me why at a glance; SimplePie doesn't seem to do it. There could be some relation to duplicate guids (which shouldn't be in the feed) but the specific ones involved don't seem to be duplicates.

**Comment by fabsenet** [comment]
It works with the demo?

https://simplepie.org/demo/?feed=https%3A%2F%2Fwww.blackmagicdesign.com%2Frss

![image](https://user-images.githubusercontent.com/2065705/182815775-3f972946-0c89-40c8-8187-e4720004a65d.png)

**Comment by Frenzie** [comment]
Exactly.

**Comment by Alkarex** [comment]
It might be a bug related to `<link>https://www.blackmagicdesign.com/products/blackmagiccloudstore</link>` not being unique, although there is a `<guid isPermaLink="false">b911e9d3753043a6a6301430ead43ea1</guid>`, which looks unique

**Comment by Alkarex** [comment]
I have just had a quick look. That feed has invalid GUIDs because they are not unique (e.g. `01aa2ca87c1846e1b6908cd37715b88c`) so we are falling back to our bad-GUID mode for which we use the link as item identifier, but the link is not unique either, so some articles are believed to be duplicates.
This would require changing our logic on how we handle wrong GUIDs and/or how we determine unicity in general.

**Comment by Frenzie** [comment]
I hadn't anticipated the lack of unique links.

**Comment by Alkarex** [comment]
Suggestion https://github.com/FreshRSS/FreshRSS/pull/4487

**Comment by fabsenet** [comment]
your speed here is promising. 👍 

I contacted blackmagicdesign so they at least know, their feed is broken. Maybe they fix it? 🤷‍♂️

**Comment by BeyondVertical** [comment]
Sorry to dig up this old issue, but I have the same feed and it is not showing the latest entries in FreshRSS, when the feed is updated. I would really like a solution for that, maybe some sort of workaround?
Thanks for your help and for your work on FreshRSS. I really like it!

**Comment by Alkarex** [comment]
If there is anyone around interested in testing the new possibility to control the unicity policy of a problematic feed, your feedback would be welcome https://github.com/FreshRSS/FreshRSS/pull/4487
