### ISSUE TITLE
[BUG] Feeds with relative paths get wrong URLs

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/FreshRSS#4499]
**Describe the bug**

When a feed uses relative URLS, such as:

`<p><img src="/images/stories/_cpu/5nm_amd/amd-ryzen-7000-packaging-vdcz.jpg" alt="amd ryzen 7000 packaging vdcz"></p>`

the URL is malformed in FreshRSS, leading to wrong links like `<FreshRSS-URL>/images/etc` : links are not working and images do not display.

I am using a CSS selector, maybe it is why.

**To Reproduce**

Add this feed: https://www.comptoir-hardware.com/home.xml and use CSS selector: .prout (sorry for french people :))

**Expected behavior**
URLs and images working

**Environment information (please complete the following information):**
- Device: Laptop
- OS: Windows 11
- Browser: Chrome 104
- FreshRSS version: latest edge
- Database version: MariaDB
- PHP version: 8-ish
- Installation type: git

**Comment by Frenzie** [comment]
This will indeed be unique to CSS selectors. In some form the opposite issue exists in #4481.

**Comment by Alkarex** [comment]
Could you try https://github.com/FreshRSS/FreshRSS/pull/4500 ?

**Comment by Alwaysin** [comment]
Thanks Alkarex, I will try later, but by having a quick look, will it really work because it is not only the protocol missing but also the domain name, ie. `/example` and not `//www.example.net/example`

Also, wouldn't that pose a problem for HTTP-only websites?

**Comment by Alkarex** [comment]
> Thanks Alkarex, I will try later, but by having a quick look, will it really work because it is not only the protocol missing but also the domain name, ie. `/example` and not `//www.example.net/example`

Should be fine. It relates to the use of `<base href="..." />` 

> Also, wouldn't that pose a problem for HTTP-only websites?

Prototol-relative addresses are typically used on Web sites supporting both HTTP and HTTPS, so should be good, but indeed, I could guess the protocol.

Edit: Done

**Comment by Alwaysin** [comment]
@Alkarex I can confirm that your PR works 👍
