### ISSUE TITLE
Permettre de configurer FreshRSS en vue mobile

### ISSUE THREAD

**Issue by Vincent14** [FreshRSS/FreshRSS#45]
Il manque éventuellement la possibilité d'ajouter un flux et de gérer son installation depuis un mobile, ce qui peut s'avérer utile sur la vue Responsive.

Le Design responsive semble vraiment excellent (en Vue Adaptative sous Firefox en tout cas il me parait tout simplement parfait), il va être difficile de faire un choix ergonomique pour cette requête.

**Comment by Alkarex** [comment]
Continues in English in https://github.com/FreshRSS/FreshRSS/issues/976
