### ISSUE TITLE
cannot find "force installation file" to be removed after upgrading

### ISSUE THREAD

**Issue by s1nnerman89** [FreshRSS/FreshRSS#4510]
Hi, sorry if this is a dumb or obvious question, but for the life of me i can't find the file which i am supposed to remove after manually upgrading FreshRSS using the latest zip release. 

I followed the official documentation to the letter but i am stuck on this passage; i can load the site just fine but i am stuck on the installation page. In the documentation there is no mentioning of this file that i'm supposed to delete, and i tried to look into the other tutorials and guides to see if it was mentioned somewhere else, but no luck. 

Hope somebody can help me out.

**Comment by math-GH** [comment]
Could you please support a screenshot?

**Comment by s1nnerman89** [comment]
Sure, this is the section of the guide where this "force installation file" is mentioned:
![Screenshot from 2022-08-19 13-36-03](https://user-images.githubusercontent.com/31391405/185610201-fb4c9a33-31f2-44e0-88dc-ea31c990a261.png)

And these are the contents of my Freshrss folder after doing "ls -la":

total 596
drwxr-xr-x 12 www-data www-data   4096 ago 18 13:08 .
drwxr-xr-x 18 www-data www-data   4096 ago 18 12:29 ..
drwxr-xr-x 13 www-data www-data   4096 ago 18 12:33 app
-rw-r--r--  1 www-data www-data 133829 ago 18 12:51 CHANGELOG.md
drwxr-xr-x  3 www-data www-data   4096 ago 13  2020 cli
-rw-r--r--  1 www-data www-data   1450 ago 18 12:51 composer.json
-rw-r--r--  1 www-data www-data  80127 ago 18 12:51 composer.lock
-rw-r--r--  1 www-data www-data   6411 ago 18 12:51 config.default.php
-rw-r--r--  1 www-data www-data   2837 ago 18 12:51 config-user.default.php
-rw-r--r--  1 www-data www-data   2702 ago 18 12:51 constants.php
-rw-r--r--  1 www-data www-data   3310 ago 18 12:51 CONTRIBUTING.md
-rw-r--r--  1 www-data www-data  23760 ago 18 12:51 CREDITS.md
drwxrwxr-x 10 www-data www-data   4096 ago 18 13:08 data
drwxr-xr-x 10 www-data www-data   4096 ago 13  2020 data.back
drwxr-xr-x  3 www-data www-data   4096 ago 18 12:33 Docker
-rw-r--r--  1 www-data www-data     27 mag 26  2019 .dockerignore
drwxr-xr-x  8 www-data www-data   4096 ago 18 12:33 docs
-rw-r--r--  1 www-data www-data    525 mag 26  2019 .editorconfig
drwxr-xr-x  3 www-data www-data   4096 apr  5  2020 extensions
-rw-r--r--  1 www-data www-data    262 ago 18 12:51 force-https.default.txt
-rw-r--r--  1 www-data www-data    133 mag 26  2019 .gitignore
-rw-r--r--  1 www-data www-data    308 ago 18 12:51 index.html
-rw-r--r--  1 www-data www-data     64 ago 18 12:51 index.php
-rw-r--r--  1 www-data www-data     85 mag 26  2019 .jshintignore
-rw-r--r--  1 www-data www-data     95 mag 26  2019 .jshintrc
drwxr-xr-x  6 www-data www-data   4096 ago 13  2020 lib
-rw-r--r--  1 www-data www-data  34523 ago 18 12:51 LICENSE.txt
-rw-r--r--  1 www-data www-data   6038 ago 18 12:51 Makefile
-rw-r--r--  1 www-data www-data    548 ago 18 12:51 opml.default.xml
drwxr-xr-x  6 www-data www-data   4096 ago 18 13:07 p
-rw-r--r--  1 www-data www-data   1518 ago 18 12:51 package.json
-rw-r--r--  1 www-data www-data 150469 ago 18 12:51 package-lock.json
-rw-r--r--  1 www-data www-data   5384 ago 18 12:51 phpcs.xml
-rw-r--r--  1 www-data www-data    494 ago 18 12:51 phpstan.neon
-rw-r--r--  1 www-data www-data  20399 ago 18 12:51 README.fr.md
-rw-r--r--  1 www-data www-data  14679 ago 18 12:51 README.md
-rw-r--r--  1 www-data www-data    105 ago 18 12:51 SECURITY.md
drwxr-xr-x  5 www-data www-data   4096 ago 18 12:33 tests
-rw-r--r--  1 www-data www-data   1281 mag 26  2019 .travis.yml

**Comment by Alkarex** [comment]
Hello,
This documentation is not completely up to date after https://github.com/FreshRSS/FreshRSS/pull/3555 but it should not be a big problem.
Is your FreshRSS instance running fine now?

Updating via the manual ZIP method is the least robust method of our different options. If you can, other methods such as git or Docker are better.

**Comment by s1nnerman89** [comment]
> Is your FreshRSS instance running fine now?

No, i updated my Ubuntu server (on which FreshRSS was installed) to 22.04, which bumped PHP to 8.1, and the old version of FreshRSS i was running was not compatible with it, so since i could not reach the web interface updater i manually updated with the ZIP method, but now i'm stuck at this step.

Is there really no way to exit the installation loop i'm stuck in?

**Comment by marienfressinaud** [comment]
You should probably create the file `data/applied_migrations.txt`, for instance:

```console
$ touch data/applied_migrations.txt
$ chown www-data:www-data data/applied_migrations.txt
```

You may have to adapt the `chown` command.

**Comment by marienfressinaud** [comment]
Btw, you probably upgraded two many versions of FreshRSS at once. If you were, let's say, at version 1.17.0, you should have upgraded to 1.18.1 before 1.19.2. This recommendation may be missing from the documentation as well.

**Comment by s1nnerman89** [comment]
@marienfressinaud Thank you, creating the `applied_migrations.txt` file worked, now i can access my FreshRSS instance like before the distro upgrade.
You can mark this issue as closed.
