### ISSUE TITLE
Export docs improvement

### ISSUE THREAD

**Issue by gingerbeardman** [FreshRSS/FreshRSS#4518]
In the docs it mentions Export as OPML is available on the web interface. But I can't find it?

I've seen screenshots of it in other issues. 

It would be good for the docs to be updated to describe where this option can be found. Thanks

**Comment by Alkarex** [comment]
1. ![image](https://user-images.githubusercontent.com/1008324/185813832-f04810f0-5f48-4285-8f8f-2d3481d16d68.png)


2. ![image](https://user-images.githubusercontent.com/1008324/185813804-2b4c2c88-f473-4a61-abb5-5f5f2a44c038.png)

**Comment by gingerbeardman** [comment]
OK! I was on mobile so things were not so obvious.

With your screenshots as hint, I can find it.

I have to do this:
1. folder icon
2. Subscription management blue button
3. folder icon (looks the same but is different)
4. Import/export

Thanks!
