### ISSUE TITLE
[BUG]Says no more articles, even though I can see hundres of articles appearing under the categories as unread.

### ISSUE THREAD

**Issue by Patriot2407** [FreshRSS/FreshRSS#4521]
**Describe the bug**
Says no more articles, even though I can see hundreds of articles appearing under the categories as unread.

**To Reproduce**
On reading page (main page) see no more articles
**Expected behavior**
there should be articles

**Screenshots**
![image](https://user-images.githubusercontent.com/30630518/185928009-8a7e9ea3-3546-4575-a333-c6f84097e492.png)

**Environment information (please complete the following information):**
- Device: Docker container on unraid
- OS: Unraid 6.10.3
- Browser: Any
- FreshRSS version: 1.19.2
- Database version: MariaDB 06.07.21 (whatever latest official docker is, this pulls from that)
- PHP version:
- Installation type: docker on unraid

**Additional context**

**Comment by Alkarex** [comment]
Hello,
It could be a database corruption. In *Settings / Archiving*, could you please try to click on:

![image](https://user-images.githubusercontent.com/1008324/185932214-f47c1ea6-7712-4e2d-891a-db0fd9b9e86c.png)

**Comment by Patriot2407** [comment]
I ran that as requested, and there was no change in the issue.

**Comment by Patriot2407** [comment]
However, it does say 0 articles...
![image](https://user-images.githubusercontent.com/30630518/185980343-4e979266-ae5a-44eb-a569-09556028ccd3.png)

**Comment by Patriot2407** [comment]
I was able to resolved, this was not due to any fault of freshrss, I recently switched to a cache drive on unraid, and it messed up the database, i was able to export feeds opml, and rebuild from scratch, now works perfectly

**Comment by Alkarex** [comment]
We also have a command line (CLI) to export from any database to SQLite, and import again in any database, which can be useful for repairing (and for backups).
