### ISSUE TITLE
[Improvement] i18n: upgrade our translations. 18 languages available. Ready for 1.20.0

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#4526]
Dear community,

[Version 1.20 knocks on the door](https://github.com/FreshRSS/FreshRSS/discussions/4517).

FreshRSS user interface is translated into 18 languages. Not all languages are covered by active developers.

Available languages:
- [ ] CZ: Czech (some phrases need a translation EN -> CZ; 91.8% complete) 🇨🇿
- [x] DE: German (active supported. 100% is translated) 🇩🇪🇦🇹🇨🇭
- [x] EN: British English (active supported. 100% is translated) 🇬🇧
- [x] EN_US: USA English (active supported. 100% is translated) 🇺🇸
- [ ] ES: Spanish (some phrases need a translation EN -> ES; 91.6% is translated) 🇪🇸🇲🇽
- [x] FR: French (active supported. 100% is translated) 🇫🇷
- [ ] HE: Hebrew (some phrases need a translation EN -> HE; 55.3% is translated) 🇮🇱
- [ ] IT: Italian (some phrases need a translation EN -> IT; 69.2% is translated) 🇮🇹
- [ ] JA: Japanese (Some less phrases need a translation EN -> JA; 91.8% is translated)
- [x] KO: Korean (some less phrases need a translation EN -> KO; 91.8% is translated) 🇰🇷🇰🇵
- [x] NL: Dutch (active supported. 91.8% is translated)🇳🇱
- [x] OC: Occitan (some phrases need a translation EN -> OC;  91.8% is translated)🇫🇷🇮🇹
- [x] PL: Polish (some phrases need a translation EN -> PL; 97.4% is translated)🇵🇱
- [ ] PT_BR: Brazil Portuguese  (some phrases need a translation EN -> PT_BR;  91.8% is translated) 🇧🇷
- [ ] RU: Russian (some phrases need a translation EN -> RU;  96.4% is translated) 🇷🇺
- [x] SK: Slovakian (100%) 🇸🇰
- [ ] TR: Turkish (some phrases need a translation EN -> TR;  90.0% is translated) 🇹🇷
- [ ] ZH_CN: Chinese (some last phrases need a translation EN -> ZH_CN;  99.6% is translated)🇨🇳

The language files are PHP files in this folder: https://github.com/FreshRSS/FreshRSS/tree/edge/app/i18n

Do you miss your favorite language? Feel free to add it to our supported languages.

Please send us a Pull Request or use the comments below to improve the translations.

**Comment by math-GH** [comment]
Ping @natastro for Spanish translation :)

**Comment by math-GH** [comment]
I call @id-konstantin-stepanov for Russian support

**Comment by math-GH** [comment]
@Nainor, could you help here again?

**Comment by math-GH** [comment]
@OctopusET, your translation support could help the Korean community

**Comment by math-GH** [comment]
@Frenzie, I bet you can do the Dutch translations very easily

**Comment by math-GH** [comment]
@giannidsp could bumb the Italian translations back to 100%

**Comment by math-GH** [comment]
@312k, please support us with your Japanese translation skills

**Comment by math-GH** [comment]
@wolfpld, could you support us again for the Polish i18n?

**Comment by math-GH** [comment]
Hey @mat-mo, could you support us with the Hebraic translations?

**Comment by math-GH** [comment]
It would be a pleasure for us to have the newest Occitan translations made by @Mejans

**Comment by OctopusET** [comment]
I just started working. However, I have a work to do for two days. So I think I can send PR on Friday or Saturday.

**Comment by ghost** [comment]
> @312k, please support us with your Japanese translation skills

Sorry, I'm not sure how long it will take me to get this done.
I am not going to be able to tackle this until around early September.
If I can get my work done quickly, I may be able to tackle it, but for now I can't.

**Comment by math-GH** [comment]
@312k Thanks for your feedback. If you cannot translate it till 1.20.0 it will not be an issue. Then we will ship the Japanese translation with an later bugfix release.

**Comment by OctopusET** [comment]
Korean translation is resolved on #4572

**Comment by math-GH** [comment]
This ticket is closed, but do not hesitate to help us with the translations. They will shipped with the next version or bugfix release
