### ISSUE TITLE
[Feature] Request to add way to open articles using archive.ph

### ISSUE THREAD

**Issue by Patriot2407** [FreshRSS/FreshRSS#4527]
**Is your feature request related to a problem? Please describe.**
I would like to open up articles such as NY Times articles using archive.ph

**Describe the solution you’d like**
I would like to open up articles such as NY Times articles using archive.ph

**Describe alternatives you’ve considered**
Could be a custom share

**Additional context**
N/A

**Comment by Patriot2407** [comment]
just need to append the URL of the article to https://archive.ph/<article_URL>

**Comment by math-GH** [comment]
@czebiniak Test is welcome in #4530

**Comment by Patriot2407** [comment]
Sure, how can I pull this into my live docker image? Haven't ever tried to pull in a github commit into a docker before.

**Comment by math-GH** [comment]
@Alkarex @Frenzie could you help here?

**Comment by Patriot2407** [comment]
I don't think I can test in an already built docker image, would have to create a new docker image with the new commit, and rebuild entire image

**Comment by Alkarex** [comment]
@czebiniak You can try to pull a new `freshrss/freshrss:edge` image ~(will be ready in 15min from now)~ (edit: ready)

**Comment by Patriot2407** [comment]
Okay thanks, I did create a second docker for the freshrss:edge tag for testing, and it works wonderfully, thank you!
