### ISSUE TITLE
[BUG] SQLite warning after upgrading to v. 1.20.0-dev 

### ISSUE THREAD

**Issue by squromiv** [FreshRSS/FreshRSS#4534]
**Describe the bug**
I have upgraded FreshRSS from 1.19 to 1.20.0-dev and there are such warnings in logs of every user now.
![screen_2022 08 25](https://user-images.githubusercontent.com/15985877/186596581-07d9e06f-336f-4c6d-9576-1cbc875a1bf8.jpg)
**Environment information:**
- FreshRSS version: [e.g. 1.20.0-dev]
- Installation type: Open Server
- Database version: SQLite
- PHP version: [7.4]
- Apache: [2.4]
- MariaDB: [10.3]

**Comment by Alkarex** [comment]
Hello,
That looks just fine. It indicates new columns automatically added. It should only occur once per user though, so a sign of problem is first if they are repeated

**Comment by squromiv** [comment]
I deleted log files, restarted server and tried to update test feeds. And I there are such records in logs.

User1
![screen_2022 08 25 001_2](https://user-images.githubusercontent.com/15985877/186613935-04023d46-9a35-4d22-8c69-271fd74465d7.jpg)

User2
![screen_2022 08 25 001_3](https://user-images.githubusercontent.com/15985877/186615266-c4382d54-de67-4f19-ae09-6a713f8a0634.jpg)

When I return to previous version of FreshRSS, there is no problem.

**Comment by Alkarex** [comment]
I have just tested and there does not seem to be any problem with SQLite from 1.19.2 to 1.20.0-dev.
Please make sure your SQLite database is writeable by the Web server after you are done with your update.

**Comment by squromiv** [comment]
The issue went away after choosing Settings->Archiving->Optimize for every "problematic" database. Don`t know what was the reason.
