### ISSUE TITLE
MariaDB case-sensitive regression

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/FreshRSS#4535]
**Describe the bug**
Since https://github.com/FreshRSS/FreshRSS/pull/4505, a 'composed keyword' search - or a single keyword with quotes - makes it case-sensitive, so that searching "toto tutu" would not match "Toto Tutu". It used to be the case before this PR.

If it's on purpose that's fine (I find it logical at least when you have only one word), but is there a switch to indicate we want the search to be case sensitive or not when searching for a particular order of words?

**Comment by Alkarex** [comment]
With what database are you testing?

**Comment by Alwaysin** [comment]
> With what database are you testing?

MariaDB 10.6.7

**Comment by Alkarex** [comment]
Could you please try https://github.com/FreshRSS/FreshRSS/pull/4537 ?
Also with negations and Unicode characters if possible

**Comment by Alwaysin** [comment]
Thank you for the quick fix! It worked for my usecase, and also with negations and unicode.

It felt way slower, confirmed - before #4505:
<img width="476" alt="chrome_2022-08-25_21-22-53" src="https://user-images.githubusercontent.com/7189936/186751265-3077661e-68f9-4181-8d69-1d7e0ee64687.png">

On edge with the fix (maybe another change is involved!):
<img width="482" alt="chrome_2022-08-25_21-24-15" src="https://user-images.githubusercontent.com/7189936/186751319-1c6dd353-35d5-492b-bb7e-59d04537d6b0.png">

Maybe it's time I switch to PostgreSQL :)

**Comment by Alkarex** [comment]
Hum, all right for the speed, I will try another fix, ~~but not today~~

**Comment by Alwaysin** [comment]
If you feel it is important, but as far as I'm concerned this is no big deal. It was more of a FYI.

**Comment by Alkarex** [comment]
New patch ready. Please try again

**Comment by Alwaysin** [comment]
I don't remember which search I did the test with, but with different ones I can see gains of 100 to 200ms with the new patch compared to the previous one so it definitely is better! Still working with unicode and negation.

**Comment by Alkarex** [comment]
Thanks for the tests 🙂
