### ISSUE TITLE
[Feature] Automatic update via URL while not allowing anonymous viewing of articles

### ISSUE THREAD

**Issue by MarcelVersteeg** [FreshRSS/FreshRSS#4540]
In the configuration page in the section Administration > Authentication one can select whether anonymous reading of the default user's articles is allowed and whether anonymous refresh of the articles is allowed. It seems that the latter is not allowed when the first is not set.

I have the situation where I do not want anonymous reading of the articles (one needs to be logged in), which also means the login page is always shown by default. However, since I host FreshRSS on a shared hosting service where I can only perform scheduled tasks based on a web request, I need to be able to execute the url http://example.com/i/?c=feed&amp;a=actualize to update the feeds of all users regularly. This does not work in combination with the requirement to disallow anonymous access.

Is there maybe another option to allow anonymous updates via a single web request?

**Comment by Frenzie** [comment]
What do you mean by "It seems that the latter is not allowed when the first is not set."? That there is a discrepancy between the UI and what it actually does?

**Comment by MarcelVersteeg** [comment]
What I see is the following:

1. Select only "Allow anonymous refresh of the articles" (leave "Allow anonymous reading of the default user’s articles" unchecked)
2. Click submit
3. A message appears "Configuration has been updated" and the checkmark before "Allow anonymous refresh of the articles" is gone. There is no indication that this option cannot be checked if the "Allow anonymous reading of the default user’s articles" option is unchecked.

However, my actual feature request says: I want to be able to set this checkmark, of have another way to update all user's feeds via an HTTP request without the need to login.

**Comment by Frenzie** [comment]
Which version is that?

**Comment by MarcelVersteeg** [comment]
Version 1.19.2

**Comment by Alkarex** [comment]
See https://freshrss.github.io/FreshRSS/en/users/03_Main_view.html#refreshing-feeds#for-form-authentication

```
https://freshrss.example.net/i/?c=feed&a=actualize&maxFeeds=10&ajax=1&user=someone&token=my-token
```

**Comment by MarcelVersteeg** [comment]
That works!

Thank you for the hint.

**Comment by MarcelVersteeg** [comment]
Still one thing that I noticed. Passing the following URL in my browser updates all the feeds for all users:
`/i/?c=feed&a=actualize&force=1&ajax=1&maxFeeds=1000&token=<token>`

However, for the ease of use, I created a rewrite rule on my webserver (being IIS 10.0), where a different shorter URL is rewritten to the URL shown above. It however seems, that when I use this shorter URL, the updates do not work. I notice this by performing the following steps:

1. Have a tab open with the main view of any user and make sure all items are marked read.
2. Request the shorter URL in my browser (rewritten by the server to the URL above) in another tab on the browser (or a different browser). The server returns "OK" very quickly
4. Refresh the tab that contains the main view opened in step 1: no new messages are listed.
5. Immediately request the URL as given above in another tab of the browser. Now it takes a little bit more time for the server to respond with "OK"
6. Again refresh the tab that contains the main view opened in step 1: now new messages are listed.

Any idea what could be causing this difference?

**Comment by Alkarex** [comment]
The rewritten URL might not pass the same cookies. You might need to include the `&user=` in the targetted URL as in the example above

**Comment by MarcelVersteeg** [comment]
I have looked at it in a little more detail and found out some things that make the proposed mechanism unusable for a cron-update using a web URL. I at least found out that the addition of the `&user=` does not make a difference whether it works or not. The problem is with the cookies handling.

When I am not logged in on the web site (my version requires users to log in) and I execute the URL
`/i/?c=feed&=actualize&force=1&ajax=1&maxFeeds=1000&token=<token>&user=<user>`
the server returns with an "OK" very quickly. However, no updates have been executed at all. It does set a cookie. Refreshing the page multiple times does not update any feeds.
Then, when I log in (using the same browser, on a different tab), not necessarily with the user who's token I use in the given URL, and then refresh the tab with the update URL, then the update suddenly happens.

When I want to use the update-URL in a cron-like job (I only have the possibility to schedule web requests on my hosting provider), I need the update URL to work even if there are no cookies set and nobody is logged in via that same scheduled job (only one URL per job possible).

So, is there another way to overcome this issue, making it possible to even update all feeds of all users from a fresh (no cookies, no history) web session?

**Comment by MarcelVersteeg** [comment]
I am still struggling with a general URL that can be used to update the feeds of all users. Currently using the following URL:
`/i/?c=feed&a=actualize&force=1&ajax=1&maxFeeds=1000&token=<token>`

In this URL, the token is the token of the administrator user. Next to the administrator user, I have two other users defined, `user1` and `user2`.

Now, when I open a fresh browser session (no cookies set), and load the URL above, it might be that the administrator feeds are updated. But since the administrator only has the feed containing the updates for FreshRSS, I did not check that thoroughly.

However, when I am logged in as `user1` or `user2`, and I load the URL above (note that the token is for the administrator user!!), the feeds of the logged in user are updated, but NOT the feeds of any of the other users (noticed that, because the FreshRSS release-feed was not updated for the administrator when loading that URL and logging in as the administrator afterwards).

So my original question remains:
How can I update the feeds of ALL registered users by loading **one** single URL (that I can schedule at my hosting provider).

**Comment by Alkarex** [comment]
Hello,
There is no Web end-point to refresh all users at once. For that, only a cron job is available.
If a cron job is not possible, then you need one Web refresh per user. In any case, refreshing many users from the same Web request would most likely time out.

**Comment by MarcelVersteeg** [comment]
> If a cron job is not possible, then you need one Web refresh per user

Hmm.... that is too bad. It also makes it not very usable. It would mean that each user needs to add an API key to their profile, but also that the web server admin needs to add a scheduled web request for each new user to have their feeds automatically updated, as the Fresh RSS users do not have any access to the web server's scheduler (which is intended of course).

**Comment by Alkarex** [comment]
Yes, multi-user FreshRSS instances are best installed on a server with access to cron job.
