### ISSUE TITLE
How do I close the error message prompt on the home page？

### ISSUE THREAD

**Issue by i-iooi-i** [FreshRSS/FreshRSS#4542]
![image](https://user-images.githubusercontent.com/1827701/187028872-c9e0061b-d05a-4993-9fbf-75e7b0e361eb.png)

How do I turn off such an error message?
Some websites are just unstable and not really ineffective.
Such frequent red reminders are not only unsightly, but also easy to cause anxiety.
If it can be turned off, or even put this function on the settings page as a reminder, it may be better.

**Comment by math-GH** [comment]
Right now there is no option to hide this warning icon.

If you do not like it, you can tweak it with the extension [CustomCSS](https://github.com/FreshRSS/Extensions/tree/master/xExtension-CustomCSS) and add the wished result via CSS code lines.

**Comment by i-iooi-i** [comment]
> Right now there is option to hide this warning icon.
> 
> If you do not like it, you can tweak it with the extension [CustomCSS](https://github.com/FreshRSS/Extensions/tree/master/xExtension-CustomCSS) and add the wished result via CSS code lines.

Hello, can you describe it in detail? Can I close these error icons without using plug-ins? It is hoped that such a function can be provided by default, because such a display mode will cause anxiety.😂😂😂

**Comment by math-GH** [comment]
Can you describe what you mean with " a display mode will cause anxiety"?

(Sorry, I forget a very important "no" in my sentence. There is NO option right now to hide it. You need to tweak it with CSS)

**Comment by Alwaysin** [comment]
@i-iooi-i I am no expert, but with the extension CustomCSS, if you add this rule it works:

```css
.item.share.error a::after, .category .title.error::before, .item.feed.error .item-title::before {
display: none;
}
```

The feed name will still be red, but no warning sign on neither the category nor the feed name.

**Comment by i-iooi-i** [comment]
> @i-iooi-i I am no expert, but with the extension CustomCSS, if you add this rule it works:
> 
> ```css
> .item.share.error a::after, .category .title.error::before, .item.feed.error .item-title::before {
> display: none;
> }
> ```
> 
> The feed name will still be red, but no warning sign on neither the category nor the feed name.

Thank you for your help. It's a success. The page looks much cleaner and tidy. 👍👍👍
