### ISSUE TITLE
When can I add a clean and tidy theme?

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#4543]
When can I add a clean and tidy theme? The current styles look like frame structures with high similarity and some influence on reading.I prefer this theme. More planar, easier to read, no visual interference：https://github.com/levito/tt-rss-feedly-theme

_Originally posted by @i-iooi-i in https://github.com/FreshRSS/FreshRSS/issues/4295#issuecomment-1229165164_

**Comment by math-GH** [comment]
You can create your own theme and copy it to the `/p/themes/nameOfYourTheme`. You can copy a given theme and configure it how you like it. You could also create a theme from the scratch.

See manual: https://freshrss.github.io/FreshRSS/en/developers/04_Frontend/02_Design.html

You are welcome to present your theme here or/and share your source code with us.

**Comment by i-iooi-i** [comment]
> You can create your own theme and copy it to the `/p/themes/nameOfYourTheme`. You can copy a given theme and configure it how you like it. You could also create a theme from the scratch.
> 
> See manual: https://freshrss.github.io/FreshRSS/en/developers/04_Frontend/02_Design.html
> 
> You are welcome to present your theme here or/and share your source code with us.

Thank you for your help. I'm ready to try it. 💕

**Comment by pcmike** [comment]
Did this theme ever get added or posted somewhere?
