### ISSUE TITLE
Ansum theme: disabled input/select + headline sizes / Label management: Rename+Delete section when 0 labels

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#4545]
(about: Ansum theme)

Not really specific to this one but it feels even "odder" with it, is the label page when you don't have any:
<img width="282" alt="chrome_2022-08-25_22-08-42" src="https://user-images.githubusercontent.com/7189936/186758921-70c036ed-35f2-4219-84cf-10ddfb44ccb9.png">
Maybe there should be some logic to not display the "rename" and "delete" parts when there is no label. Also, in the URL it is called "tag" but then everywhere else it's "labels" but that's another story 😅 

Something else that strikes me as odd is that h1 and h2 titles look very similar.

_Originally posted by @Alwaysin in https://github.com/FreshRSS/FreshRSS/issues/4538#issuecomment-1227718921_

**Comment by math-GH** [comment]
Thanks for your thoughts. Let us divide it in some topics:

1) Ansum theme: disabled input/select are less/not visible 
2) Hide "rename" and "delete" section, when there is no label
3) `h1` and `h2` have the same size
4) "tag" vs "labels"

Have I overseen an idea/comment?

**Comment by math-GH** [comment]
My comments:

to 1): oh, nice finding. That needs an fix. Good catch!

to 2): yes, good idea, I think it is worth to improve it.

to 3): I did not wanted to change the style made by the origin author of Ansum theme. But you are right, here we need an improvement.

PRs will come.

**Comment by math-GH** [comment]
to 4): I guess that it has some historic reasons within FreshRSS. Right now we have the "labels" feature (individually user's tagging feature) and the "Article tags" feature (tags given by the article, cannot be changed by the user). Both are "tags". I guess that the "label" feature was implemented first and got the internal "tags" name, that you still can see in the URL

**Comment by Alwaysin** [comment]
> Have I overseen an idea/comment?

You got everything! Thanks for taking care of this!
