### ISSUE TITLE
[BUG] Swage and Flat themes : manage icon of extensions is white on white

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/FreshRSS#4547]
Origine:
<img width="158" alt="chrome_2022-08-27_22-40-06" src="https://user-images.githubusercontent.com/7189936/187047308-9a878060-a428-4f48-bd7d-cbd4ac2646d9.png">

Swage:
<img width="153" alt="chrome_2022-08-27_22-41-10" src="https://user-images.githubusercontent.com/7189936/187047312-8e56c6d3-d0e9-48bd-81ad-561bd102e0d6.png">

I haven't checked the other themes.

**Comment by Alwaysin** [comment]
I've checked all the themes and it also happens on "Flat design".
All the others are good except maybe for "Dark" where it is a bit hard to spot.

**Comment by math-GH** [comment]
Please do not forget to give the FreshRSS version ;)
Is it 1.19.2 or 1.20.0-dev (from edge)?

**Comment by Alwaysin** [comment]
Sorry, I'm always on edge!

**Comment by math-GH** [comment]
Created a fix for Swage theme (see #4551)

The "Flat" theme needs a clean-up like Swage, Ansum and Mapco that I did in the last weeks. I am not sure if I can improve/fix "Flat" theme till the release [1.20.0](https://github.com/FreshRSS/FreshRSS/discussions/4517). "Flat" theme is not very popular ([see little survey](https://github.com/FreshRSS/FreshRSS/issues/4295)) so it is not on my prio todo list.
