### ISSUE TITLE
[BUG] Content subscribed with RSSHub is repeatedly marked unread

### ISSUE THREAD

**Issue by i-iooi-i** [FreshRSS/FreshRSS#4552]
I installed the latest docker version on synology.

For example, I mark some articles as read. After 20 minutes, the content is refreshed automatically, and the articles marked as read appear in the unread list.

Mark as read again, and after 20 minutes, the same content will appear unread again. over and over.

I tried to delete these websites and subscribe to them again. The problem still exists.

I use RSSHub（https://github.com/DIYgod/RSSHub-Radar） to subscribe to some websites, such as Twitter.

After I subscribed to many websites, the article content of some websites was repeatedly subscribed. 

These problems only exist in websites subscribed to by RSSHub. At first, I thought it was the problem of RSSHub. Later, I transferred these subscriptions (. OPML) to Tiny Tiny RSS and Fluent. Their performance was stable, and there was no situation that the content was repeatedly marked as read.

I try to turn it on or off: Mark updated articles as unread. It seems that the problem is only alleviated, but it will still occur.

**Comment by math-GH** [comment]
Could you please give us an example RSS feed from RSSHub?

**Comment by i-iooi-i** [comment]
> Could you please give us an example RSS feed from RSSHub?

https://rsshub.app/ncm/djradio/73002

👆This is a test link. Because there are many users, the link is not stable. You may need to try to add it several times.

After adding successfully, please mark all contents as read. After a few weeks, this link will update the content, and the hundreds of items marked as read will become unread. 🙁

**Comment by Alkarex** [comment]
Ok, this feed look fine at a first glance but very long. Might be a similar issue as https://github.com/FreshRSS/FreshRSS/issues/4401
fixed in https://github.com/FreshRSS/FreshRSS/pull/4422
Could you try our current edge version of FreshRSS?

**Comment by Alkarex** [comment]
I am pretty sure it is the same issue that has already been fixed. Closing but feedback welcome
