### ISSUE TITLE
[BUG] Anchors wrongly computed

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/FreshRSS#4562]
On edge branch, it looks like anchors are resolved against the website's URL as opposed to the article's.

E.g. feed ```https://about.gitlab.com/atom.xml```, "Website URL" is ```https://about.gitlab.com/blog/```
The last article (```https://about.gitlab.com/releases/2022/08/30/critical-security-release-gitlab-15-3-2-released``` - "GitLab Critical Security Release: 15.3.2, 15.2.4 and 15.1.6") has in its source code:
```
<a href="#remote-command-execution-via-github-import">Remote Command Execution via GitHub import</a>
```
Browser's interpretation on the page converts it to ```https://about.gitlab.com/releases/2022/08/30/critical-security-release-gitlab-15-3-2-released/#remote-command-execution-via-github-import``` (working), FreshRSS hard-codes it to ```https://about.gitlab.com/blog/#remote-command-execution-via-github-import``` (obviously not working)

**Comment by math-GH** [comment]
I can confirm this issue, but I am not sure if it is a bug of FreshRSS or an issue of Gitlab's feed.

Line 7 of the feed:
```
<link href='[https://about.gitlab.com/blog/](view-source:https://about.gitlab.com/blog/)' />
```

This is used as `base` URL

That is why SimplePie/FreshRSS convert it to `https://about.gitlab.com/blog/#remote-command-execution-via-github-import`

**Comment by Alwaysin** [comment]
The link of the entry is good. You are pointing to the link of the feed. Feed link and entry links are expected to be different.

This is similar to a certain extent to #4499  where the whole url is not provided either.

**Comment by Frenzie** [comment]
> I can confirm this issue, but I am not sure if it is a bug of FreshRSS or an issue of Gitlab's feed.

None of that base URL stuff is applicable if it's just a hash, so definitely a bug.

**Comment by Alkarex** [comment]
SimplePie bug (cf. https://simplepie.org/demo/?feed=https%3A%2F%2Fabout.gitlab.com%2Fatom.xml )
Patch coming

**Comment by Alkarex** [comment]
@Alwaysin Please try https://github.com/FreshRSS/FreshRSS/pull/4565
If you are able to test thoroughly, we could include this patch in 1.20.0, otherwise it will have to wait till 1.21.0.
This means testing with several examples of Atom, RSS 1.0, RSS 2.0 feeds.

**Comment by Alwaysin** [comment]
Thank you very much and sorry for the delay!
It indeed looks like it is working with all my feeds :D
