### ISSUE TITLE
[BUG] Readrops error message when updating

### ISSUE THREAD

**Issue by Tealk** [FreshRSS/FreshRSS#4567]
**Describe the bug**
Since the update, I get the following error message on the Readrops app when updating the feed:
Expected END_OBJECT ut was NAME at path $.items[0].alternate[0].href

**To Reproduce**
1. Open Readrops 
2. Press the refresh button

**Expected behavior**
the latest feeds are downloaded

**Screenshots**
![Screenshot_20220831-112053.png](https://user-images.githubusercontent.com/12276250/187646577-d851a688-d40e-485f-8879-f812ad8fda6a.png)

**Environment information (please complete the following information):**
- Device: Pixel 6
- OS: CalixOS
- FreshRSS version: 1.20.0-dev
- Database version: MariaDB
- PHP version: 8.1.9
- Installation type: git

**Comment by Alkarex** [comment]
Related to https://github.com/readrops/Readrops/issues/162
Might be due to the refactoring of https://github.com/FreshRSS/FreshRSS/pull/4490

**Comment by Alkarex** [comment]
Bug in Readrops. Patch suggestion (not tested - no compile environment set up) https://github.com/readrops/Readrops/pull/163

**Comment by Alkarex** [comment]
Workaround https://github.com/FreshRSS/FreshRSS/pull/4568 while waiting for Readrops fix.

**Comment by Alkarex** [comment]
Please try the latest `edge` version of FreshRSS. Feedback welcome.

**Comment by Tealk** [comment]
Works again, thank you
