### ISSUE TITLE
[BUG] extension list:  file_get_contents(https://raw.githubusercontent.com/FreshRSS/Extensions/master/extensions.json): Failed to open stream:

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#4569]
**Describe the bug**

menu: Config -> Extensions

FreshRSS in offline mode (disconnected from the internet).

Mode: development

```
Warning: file_get_contents(): php_network_getaddresses: getaddrinfo failed: Der angegebene Host ist unbekannt. in......\app\Controllers\extensionController.php on line 45

Warning: file_get_contents(https://raw.githubusercontent.com/FreshRSS/Extensions/master/extensions.json): Failed to open stream: php_network_getaddresses: getaddrinfo failed: Der angegebene Host ist unbekannt. in .....\app\Controllers\extensionController.php on line 45
```

("Der angegebene Host ist unbekannt" = "unknown host")

![grafik](https://user-images.githubusercontent.com/1645099/187753877-2463b053-9292-455f-8a39-1c7ca4a6dfe9.png)

**Expected behavior**
No warning.

**Environment information (please complete the following information):**
- FreshRSS version: 1.20.0-dev
- PHP version: PHP 7.4 (that is important for this bug!)

**Additional context**
from https://www.php.net/manual/en/function.file-get-contents.php
```
Errors/Exceptions

An E_WARNING level error is generated if filename cannot be found, length is less than zero, or if seeking to the specified offset in the stream fails.

When file_get_contents() is called on a directory, an E_WARNING level error is generated on Windows, and as of PHP 7.4 on other operating systems as well.
```

https://github.com/FreshRSS/FreshRSS/blob/a8353e4b4c9cd17c94fa63792f4ce23a3040284a/app/Controllers/extensionController.php#L43-L51

Could a try-except block solve this warning?

`$json === false` is correct, but the warning is already triggered while calling `file_get_contents()`

**Comment by Alkarex** [comment]
Try `@file_get_contents(...)`
