### ISSUE TITLE
[Feature] enable/disable the list of available extensions

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#4570]
**Is your feature request related to a problem? Please describe.**
menu: Config -> extensions

The extensions list is called directly from github via `https://raw.githubusercontent.com/FreshRSS/Extensions/master/extensions.json` (in `\app\Controllers\extensionController.php on line 45`)

I am not so happy that always I call the extension config page a request is started to GitHub.

It costs resources (time, energy, privacy).

**Describe the solution you’d like**
- An option to decide: call GitHub and show me the list of available extensions or not
- cache the extensions.json, so that not every page load calls GitHub (f.e. cache it for 1 day)

**Comment by Alkarex** [comment]
Small improvement with caching https://github.com/FreshRSS/FreshRSS/pull/6767
