### ISSUE TITLE
[BUG] Space key opens an empty tab

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#4579]
When you press the `space` key somewhere an empty tab will be opened

**Expected behavior**
no tab. 
The defined shortcut action.

**Environment information (please complete the following information):**

- FreshRSS version: 1.19.2 + 1.20.0-dev

**Comment by math-GH** [comment]
For the records:
A console error is shown

![grafik](https://user-images.githubusercontent.com/1645099/188319012-f6c75fa3-0177-49a9-99eb-7e72db8714ac.png)

**Comment by Frenzie** [comment]
Yeah, it should simply return at that point.
