### ISSUE TITLE
[BUG] problem subscribing to feed

### ISSUE THREAD

**Issue by alexandru** [FreshRSS/FreshRSS#4580]
**Describe the bug**
Cannot parse feed — FreshRSS should be more tolerant.

**To Reproduce**
Try to subscribe to <https://degoes.net/feed.xml> (with or without #force_feed)

**Expected behavior**
Subscription should work, feed should be valid.

Note, it does have some validation problems, [see validator.w3.org](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fdegoes.net%2Ffeed.xml). But those look like minor issues, and I checked with other 2 RSS/Atom readers which seem fine with it.

**Screenshots**
<img width="617" alt="Screenshot 2022-09-04 14 02 29" src="https://user-images.githubusercontent.com/11753/188310059-1920dcd9-c05c-47eb-a589-32caac00c50b.png">

**Environment information (please complete the following information):**
- FreshRSS version: 1.19.2 via the Docker `freshrss/freshrss:latest` image

**Comment by Frenzie** [comment]
Basically upstream SimplePie.

But note that it's only all the other errors that are insignificant. The first error is quite significant. It should say http, not https.

**Comment by Alkarex** [comment]
Indeed, this is not a valid feed. See also https://simplepie.org/demo/?feed=https%3A%2F%2Fdegoes.net%2Ffeed.xml
This would require making a special logic for this feed in the upstream SimplePie library. If we were to see this specific error in many feeds, this could justify the efforts, but for just one feed, I suggest making a workaround with a FreshRSS extension instead, or going through a bridge to fix it such as RSS-Bridge.
Of course, the best approach is to write to the Web master of https://degoes.net/feed.xml and ask them to fix their feed.

**Comment by Alkarex** [comment]
P.S. One can also use our new Web Scraping feature to get the news from the HTML page, just like if there were no RSS feed.

**Comment by alexandru** [comment]
Thanks for replying. I'll definitely contact the website's author.
