### ISSUE TITLE
[Feature] option to have ./data in different location

### ISSUE THREAD

**Issue by Stunkymonkey** [FreshRSS/FreshRSS#4582]
This is more like a question. If the answer it is not possible, I would like this a a feature. Otherwise I hope to get an explanation.

**Is your feature request related to a problem? Please describe.**
Not really, bu I am trying to pack this programm for `nixpkgs`.

**Describe the solution you’d like**
For `nix` the ideal setting is to have the whole application in a "read-only" directory and the `./data ` (e.g.`/var/lib/freshrss`) is separated. Is this possible to set via `constants.local.php`?

And while the application is running the data-path is read from an env-var?

**Describe alternatives you’ve considered**
Otherwise I would delete everything in the folder an copy everything over again except the `data`-folder. This is a bit ugly and can produce problems.

**Additional context**
I know that the web-updater will not work this way, but this is intended and wanted with nix.

**Comment by Alkarex** [comment]
Hello,
Indeed, a `./constants.local.php` file with the following content should do the job:

```php
<?php
define('DATA_PATH', '/var/lib/freshrss');
```

**Comment by Stunkymonkey** [comment]
Thanks for the quick reply.

will something like `define('DATA_PATH', getenv('FRESHRSS_DATA_PATH'));` work as well?

Because the nix-package does not allow any modification after it is "packed".

And it would be nice to offer the option to modify the path as well. Otherwise having it hard coded is ok, but not perfect.

**Comment by Alkarex** [comment]
> will something like `define('DATA_PATH', getenv('FRESHRSS_DATA_PATH'));` work as well?

Yes, that should work too. We could even add it to the core.

And maybe you could consider making a symlink from `./data/` to `/var/lib/freshrss/` so that users familiar with the native structure will easily find it.

**Comment by Stunkymonkey** [comment]
The problem with symlink: For Nix the package is "compiled" (in your case only unzip), ... and then saved as "read-only". So the path has to be known before the "compilation".
This would result in very easy and short code, but the path could never be changed after packing the package. Therefore the Path has to be injected in other ways e.g. env-vars
I would like to have it in the core, but hopefully this is not too much work. I already got it working. But it would totally make sense to split the application and data.

Currently I am getting the error message seems a bit of to me (specially the first red one):
![Screenshot-2022-09-04_223548](https://user-images.githubusercontent.com/1315818/188332418-aa22544c-8660-44de-91d1-f78ecd22fc41.png)

**Comment by Alkarex** [comment]
The errors you see seem to be due to the Web server (typically `www-data`) not being allowed to read and/or write in your new data location (`/var/lib/freshrss/`)
What Unix rights do you have on that folder?

**Comment by Stunkymonkey** [comment]
I created a new user called `freshrss`:
```
[root@newton:/var/lib/freshrss]# ls -la
total 44
drwxrwxr-x 10 freshrss freshrss 4096 Sep  4 22:23 .
drwxr-xr-x 22 root     root     4096 Sep  4 22:21 ..
drwxrwx---  2 freshrss freshrss 4096 Sep  4 22:23 cache
drwxrwxr-x  9 freshrss freshrss 4096 Sep  4 22:23 data
drwxrwx---  2 freshrss freshrss 4096 Sep  4 22:23 extensions-data
drwxrwx---  2 freshrss freshrss 4096 Sep  4 22:23 favicons
drwxrwx---  2 freshrss freshrss 4096 Sep  4 22:23 fever
-rw-rw-rw-  1 freshrss freshrss  174 Sep  4 22:52 .htaccess
-rw-rw-rw-  1 freshrss freshrss    0 Sep  4 22:52 index.html
drwxrwx---  4 freshrss freshrss 4096 Sep  4 22:23 PubSubHubbub
drwxrwx---  2 freshrss freshrss 4096 Sep  4 22:23 tokens
drwxrwx---  3 freshrss freshrss 4096 Sep  4 22:23 users
```

**Comment by Alkarex** [comment]
> I created a new user called `freshrss`:

Please check parent folders rights as well that the user is allowed to traverse, as well as PHP security configuration options such as [`open_basedir`](https://php.net/ini.core#ini.open-basedir).
We are testing with a straight-forward [`is_writable()`](https://php.net/is-writable)

**Comment by Stunkymonkey** [comment]
you want to know this:?
```bash
$ namei -mo /var/lib/freshrss/
f: /var/lib/freshrss/
 drwxr-xr-x root     root     /
 drwxr-xr-x root     root     var
 drwxr-xr-x root     root     lib
 drwxrwxr-x freshrss freshrss freshrss
```

**Comment by Stunkymonkey** [comment]
I already got this far to execute the `do-install.php` and `create-user.php` (and also having a timer which executes the `actualize_script.php`).
But the problem is, that the installation screen is still shown... `Blast! Check permissions on the directory for freshrss user. The HTTP server must have write permission.`
Are there any files in the root, that indicate an installation?
Or is it based on the permissions?

**Comment by Alkarex** [comment]
After your installation, you should have a file `applied_migrations.txt` in your data folder.
But I would recommend to try first the installation through the Web interface before doing it through the CLI.
Did you check your [open_basedir](https://php.net/ini.core#ini.open-basedir) settings and are you sure your Web server uses the right account?

**Comment by Stunkymonkey** [comment]
`applied_migrations.txt` exists.
Sure, but there I am stuck on "Installation · FreshRSS: step 2".
I am not sure entirely sure about `open_basedir` but I never set it anywhere. (And I am unable to set it, because I am stupid)
Not sure if this is an permission error, because even with 777 for all files in the data-folder the error is the same.

**Comment by Stunkymonkey** [comment]
If I set `open_basedir` I am getting: `No input file specified with an 404 error. So not sure why I need it.
So I reverted it. If you want to try something: have a look at https://news.buehler.rocks/i/ which is my current testing location

**Comment by Stunkymonkey** [comment]
could you please guide me where to set the `open_basedir`?
Freshrss is in: /nix/store/zj48jdmjys68p5dgpni89nvka39gpiya-FreshRSS-1.19.2
and the data in: /var/lib/freshrss/
I tried it setting in the phpfpm setting with `"php_admin_value[open_basedir]" = "${cfg.package}:${cfg.dataDir}:/tmp";`, the website seemed fine, but the permissions messages are still there. So for me there seems no change.
(without /tmp I am unable to get to the second check step)

**Comment by Alkarex** [comment]
I am not sure `open_basedir` is the problem in your case, but it could be. It is typically defined in your php.ini or where you otherwise define your other PHP settings.

You could try to make a very basic test file such as:

```php
<?php
file_put_contents('/var/lib/freshrss/hello.txt', 'world');
```

and see whether that works from your Web browser

**Comment by Stunkymonkey** [comment]
I put this file in the freshrss folder at `freshrss/p/testing.php`
then i called https://news.buehler.rocks/testing.php which gave me a blank site.
the file is written as well. So i guess the permissions look fine to me.
```
[root@server:/var/lib/freshrss]# cat hello.txt 
world
```

**Comment by Alkarex** [comment]
Looking at your screenshots again, it looks like the `DATA_PATH` constant is empty / blank.
So the rights are probably correct after all, but the definition of `DATA_PATH` failed. Can you try to hardcode it instead of using getenv, just for debugging?

**Comment by Stunkymonkey** [comment]
If I hard code the settings everything works perfectly fine :tada: .

**Comment by Stunkymonkey** [comment]
when I pass the variable to the `phpfpm` as well it works as well. :tada: 
So now I have to polish it up. But I can confirm everything is working perfectly.

So I guess in the next days I will prepare the package for NixOS.

If you have nothing against it I will close this issue, because all my questions and beyond are answered. Thanks again for you help.

PS: I just saw that in the README the Newsflash with greader-API is marked as not supported. It is now supported, so I will file open a PR for it.

Keep up the great work. :+1:

**Comment by Stunkymonkey** [comment]
Using the greader-API is not release yet. Therefor updating the README would reflect some not released features. So I will wat with the update.

**Comment by Alkarex** [comment]
> Using the greader-API is not release yet. Therefor updating the README would reflect some not released features. So I will wat with the update.

I have not understood your comment. The GReader API has been available in FreshRSS for years

**Comment by Stunkymonkey** [comment]
Yes but not in Newsflash the RSS-Reader.

**Comment by Alkarex** [comment]
Ah ok, I had not understood that it was referring to your "P.S." a bit higher up

**Comment by Stunkymonkey** [comment]
Sorry to reopen the "issue"/question.
```
Sep 15 21:00:00 newton systemd[1]: Starting FreshRSS feed updater...
Sep 15 21:00:00 newton FreshRSS[407962]: FreshRSS starting feeds actualization at 2022-09-15T19:00:00+00:00
Sep 15 21:00:00 newton php[407962]: FreshRSS starting feeds actualization at 2022-09-15T19:00:00+00:00
Sep 15 21:00:00 newton FreshRSS[407962]: FreshRSS actualize felix…
Sep 15 21:00:00 newton php[407962]: FreshRSS actualize felix…
Sep 15 21:00:00 newton FreshRSS[407962]: SimplePie GET https://rss.golem.de/rss.php?feed=ATOM1.0
Sep 15 21:00:00 newton FreshRSS[407962]: FreshRSS actualization done for 1 users, using 6.00 MiB of memory, in 0 day(s), 0 hour(s), 0 minute(s) and 0 seconds.
Sep 15 21:00:00 newton php[407962]: FreshRSS actualization done for 1 users, using 6.00 MiB of memory, in 0 day(s), 0 hour(s), 0 minute(s) and 0 seconds.
Sep 15 21:00:00 newton php[407962]: Results:
Sep 15 21:00:00 newton php[407962]: felix OK
Sep 15 21:00:00 newton php[407962]: End.
Sep 15 21:00:00 newton systemd[1]: freshrss-updater.service: Deactivated successfully.
Sep 15 21:00:00 newton systemd[1]: Finished FreshRSS feed updater.
```
II am facing some minor issues with the `cli/[actualize-user.php](https://github.com/FreshRSS/FreshRSS/blob/edge/cli/actualize-user.php)`
The script is executed without any warnings/errors, but in the Web-UI the fee is marked red with `Blast! This feed has encountered a problem. Please verify that it is always reachable then update it.`
And it therefore never gets any updates.
Any idea why? When pressing `update feeds` int the UI it works perfectly.

**Comment by Alkarex** [comment]
It might be a feed randomly failing. Please check over a longer period. Mind also the refresh period of the feed.
Please open another issue if the problem persists, as it is not related to the `./data/` location

**Comment by Alkarex** [comment]
New `DATA_PATH` environment variable implemented in https://github.com/FreshRSS/FreshRSS/pull/5423
