### ISSUE TITLE
[BUG] Feeds stopped refreshing automatically

### ISSUE THREAD

**Issue by InterferencePattern** [FreshRSS/FreshRSS#4588]
**Describe the bug**
Since switching from the "latest" branch to the "edge" Docker container, my feeds no longer automatically refresh. It may be a settings issue, but I have not found any settings that would resolve the issue.

Therefore, to get refreshed feeds in the [FreshRSS Android app](https://gitlab.com/christophehenry/freshrss-android), I need to first use a web browser and hit the refresh button in the web UI. ~It would be helpful if the mobile app's refresh function would trigger a query to all RSS feeds, but I can create a feature request on the android app for that separately.~

**To Reproduce**
1. Wait 24 hours...
2. Feeds do not refresh

**Expected behavior**
Feeds would automatically refresh according to max. refresh rate setting ("Do not automatically refresh more often than `1h` (By default)")

**Screenshots**
N/A

**Environment information (please complete the following information):**
- Device: Synology NAS
- OS: DSM7
- Browser: Firefox 104.0
- FreshRSS version: 1.20.0-dev 
- Database version: Unknown
- PHP version: Unknown
- Installation type: Docker

**Additional context**
The logs only show an error with 1 out of ~20 feeds.
Logs also show an authentication error with the android app, even though the app shows no trouble fetching from server.

**Comment by Alkarex** [comment]
Hello,
What type of cron job do you have to automatically refresh your feeds?

**Comment by InterferencePattern** [comment]
Apologies- I switched from the linuxserver docker container and expected similar default refresh behavior. However, that container had provided a cron job by default, whereas this one does not.

**Comment by Alkarex** [comment]
We do have a built-in cron job in our official Docker images. See example:
https://github.com/FreshRSS/FreshRSS/tree/edge/Docker#quick-run

**Comment by InterferencePattern** [comment]
Yes, I see that now. Since the documentation is fragmented across separate READMEs for the base install and Docker install as well a GitHub Pages, I hadn't found the cron instructions for docker until now.
