### ISSUE TITLE
Change color of feed when unread items exist

### ISSUE THREAD

**Issue by bonifacio123** [FreshRSS/FreshRSS#4589]
When lots of feeds exist within a category it can be difficult to identify the ones with unread items - especially with large screens. Looking for the unread item count isn't quick. This could be alleviated by changing the feed name color when unread items exist. Thank you.

![image](https://user-images.githubusercontent.com/15472847/188935357-54907291-6585-4607-8628-ccbeeedd66f9.png)

**Comment by aledeg** [comment]
I think you can do that by configuring properly the CustomCSS extension.

**Comment by bonifacio123** [comment]
Excellent - I will check it out. Thank you.

**Comment by math-GH** [comment]
With 1.20.0 release there is an improvement. The numbers will be better visible:

![grafik](https://user-images.githubusercontent.com/1645099/189076861-144f37f5-b85f-45dc-b2b4-fc61174c7096.png)

**Comment by bonifacio123** [comment]
Nice. Looking forward to the next release. Thanks for sharing this.
