### ISSUE TITLE
[BUG] using Check for new updates doesnt show any new version

### ISSUE THREAD

**Issue by rezad1393** [FreshRSS/FreshRSS#4599]
I am on 1.19.2 version.
when I check for update it say
```
Update system

ⓘ Your current version of FreshRSS is 1.19.2.

Last verification: 10 September 2022 at 22:48 
```
am I missing something?

**Comment by aledeg** [comment]
The tag has been made but it's not yet deployed on the update server. It should arrive soon.

**Comment by rezad1393** [comment]
oh. I thought it got it from github.
is it just a zip file from github?

**Comment by aledeg** [comment]
There is an ongoing work in-progress to change how new version will be offered to stop relying on the manual process to update the server.
It's still not completed but your help is welcome.

**Comment by rezad1393** [comment]
I am too retarded to do computer stuff.

**Comment by aledeg** [comment]
Not that much if you're hosting FreshRSS

**Comment by rezad1393** [comment]
I am using a local installed freshrss but I don't want to use manual download and unzip the release.
the automatic way is way easier for me.

I wait for it.
thank you.

**Comment by Alkarex** [comment]
You can always update by git, either manually or through the Web interface (requires having downloaded FreshRSS this way).

Ping @marienfressinaud for the auto-update via ZIP.

**Comment by rezad1393** [comment]
you mean if I install freshrss from scratch from git then when I use web interface update then it check the git? didn't another user just say that the download is not from github?
would not that git way also become dependent on manual config update of another site for my instance to see it?

also is the update not available still from the web interface for 1.20?

**Comment by Alkarex** [comment]
Yes, if you install by git, you can then update by git, either through command line or from the Web interface

**Comment by marienfressinaud** [comment]
The server is updated, you should be able to update now.
