### ISSUE TITLE
Postgresql rollbacks after actualize_script.php

### ISSUE THREAD

**Issue by Dual-0** [FreshRSS/FreshRSS#4600]
Hello,

since 1.20 I've got a "Postgresql high rollback rate" from my prometheus monitoring system.
`Ratio of transactions being aborted compared to committed is > 2 % VALUE = 0.1124031007751938`

When I run `/usr/bin/php /var/www/freshrss/1.20.0/app/actualize_script.php` the PostgreSQL DB metrics show an increase of rollbacks by 30.

<img width="553" alt="image" src="https://user-images.githubusercontent.com/37346547/189526388-c33a79a5-94af-444f-8266-da786898f4b5.png">

Environment 
- OS: Ubuntu 22.04
- FreshRSS version: 1.20.0
- Database version: PostgreSQL 14
- PHP version: PHP 8.1

I'am not a postgresql pro so I hope someone can help.

thanks in advance

**Comment by Alkarex** [comment]
Hello,
Do you have any error logs from PostgreSQL or FreshRSS? And have you noticed anything not working?

**Comment by Dual-0** [comment]
> Hello, Do you have any error logs from PostgreSQL or FreshRSS? And have you noticed anything not working?

Yes of course. PostgreSQL is huge so here a little excerpt:
~~https://pastebin.com/1NB8rpF0~~

FreshRSS Log shows no errors and works as usual.

edit: PostgreSQL shows a lot of errors like:
`current transaction is aborted, commands ignored until end of transaction block`

**Comment by Alkarex** [comment]
Do you have many users on your instance? Do you keep observing the same symptoms for users who have used the Web interface? (I am guessing there could be a problem for passive users, which have only been refreshed by cron job since the update)

**Comment by Dual-0** [comment]
I have informed all users to log on to the web.
I have the feeling it is better but the rollbacks on every cron run are not all gone.

![image](https://user-images.githubusercontent.com/37346547/190892131-264af0fd-d40e-43ef-a073-f67077440f80.png)

**Comment by Alkarex** [comment]
Do you keep observing the same symptoms for users who have used the Web interface?

**Comment by Dual-0** [comment]
Finally! After all users have login once after the update the errors have disappeared. Thanks for the hint.

**Comment by Alkarex** [comment]
Thanks for the feedback. It is still a bug though. I will try to see if I can fix

**Comment by Alkarex** [comment]
Should be fixed by https://github.com/FreshRSS/FreshRSS/pull/4622
Feedback welcome if you can
