### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Undefined constant "LOG_FILENAME"

### ISSUE THREAD

**Issue by MatzeKitt** [FreshRSS/FreshRSS#4605]
**Describe the bug**
After pressing the button to update from 1.19.2 to 1.20.0 via admin interface, I just got a blank page. The following error message is logged:

```
2022/09/12 16:49:43 [error] 1446#1446: *2719094 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Undefined constant "LOG_FILENAME" in /customers/kittmedia/home/rss.kittmedia.com/lib/Minz/Log.php:39
Stack trace:
#0 /customers/kittmedia/home/rss.kittmedia.com/lib/Minz/Log.php(121): Minz_Log::record()
#1 /customers/kittmedia/home/rss.kittmedia.com/lib/Minz/Configuration.php(179): Minz_Log::warning()
#2 /customers/kittmedia/home/rss.kittmedia.com/lib/Minz/Configuration.php(188): Minz_Configuration->param()
#3 /customers/kittmedia/home/rss.kittmedia.com/app/FreshRSS.php(35): Minz_Configuration->__get()
#4 /customers/kittmedia/home/rss.kittmedia.com/p/i/index.php(55): FreshRSS->init()
#5 {main}
  thrown in /customers/kittmedia/home/rss.kittmedia.com/lib/Minz/Log.php on line 39" while reading response header from upstream, client: 2001:16b8:249d:e100:4c6a:8c93:aad7:5c35, server: rss.kittmedia.com, request: "GET /i/?c=update&a=apply&post_conf=1&rid=631f470697782 HTTP/2.0", upstream: "fastcgi://127.0.0.1:9013", host: "rss.kittmedia.com"
```

However, the update seems to be successful.

**To Reproduce**
1. Go to update screen
2. Press update

**Expected behavior**
There is no error message and no blank screen.

**Environment information (please complete the following information):**
- Device: MacBook Pro
- OS: macOS 12.5.1
- Browser: Safari 15.6.1
- FreshRSS version: 1.19.2/1.20.0
- Database version: MariaDB 10.3
- PHP version: 8.0
- Installation type: manual

**Comment by math-GH** [comment]
Related PR that causes the error: #4465

**Comment by Alkarex** [comment]
Should be fixed by https://github.com/FreshRSS/FreshRSS/pull/4629 and https://github.com/FreshRSS/update.freshrss.org/pull/4
