### ISSUE TITLE
[BUG] Mark All As Read redirects to wrong page

### ISSUE THREAD

**Issue by jan-vandenberg** [FreshRSS/FreshRSS#4610]
**Describe the bug**
When I click Mark All As Read on a feed I get redirected to a random blog post on my site (always the same blogpost)

My FreshRSS runs on /rss of my website. My blog runs on the top level domain.

**To Reproduce**
1. Go to any feed
2. Click on Mark All As Read
3. See error

**Expected behavior**
I should be redirected to the next available unread feed.

**Screenshots**
None

**Environment information (please complete the following information):**
- OS: Windows 10
- Browser: [Versie 1.43.89 Chromium: 105.0.5195.102]
- FreshRSS version: 1.20.0
- Database version: [10.3.34-MariaDB-0+deb10u1 - Debian 10]
- PHP version: [PHP 7.4]
- Installation type: []

**Additional context**
This is part of my access log (deleted my IP address) what happens when I click the Mark All as Read:
```
2001:9e0:: - - [13/Sep/2022:09:39:03 +0200] "POST /rss/p/i/?c=entry&a=read&get=f_272&nextGet=f_483&idMax=1663054741000000&search=&state=2 HTTP/1.1" 302 477 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
2001:9e0:: - - [13/Sep/2022:09:39:03 +0200] "GET /rss/FreshRSS-master/p/i/?get=f_483&rid=632033977ea6d HTTP/1.1" 301 492 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
2001:9e0:: - - [13/Sep/2022:09:39:03 +0200] "GET /2020/05/12/i-robot-isaac-asimov/?get=f_483&rid=632033977ea6d HTTP/1.1" 200 14325 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
```

**Comment by Alkarex** [comment]
That is quite strange. Could you try to check in your Web browser development tools, in the network view, what responses you get (in particular the redirection)?

Can you try to see what `base_url` you have in `./data/config.php` ?

**Comment by jan-vandenberg** [comment]
Weirdly it is/was:   
`'base_url' => 'https://j11g.com/rss/FreshRSS-master/p' `
and has been since 2018 according to the file timestamp.
I changed it to 
`https://j11g.com/rss/` 
but the problem persists.

**Comment by Alkarex** [comment]
Could you please tell where your Web root is in your local file structure (for instance `/var/www/FreshRSS/p/`), and what home page URL you have?
What Web server are you running?

**Comment by jan-vandenberg** [comment]
The main thing is that my FreshRSS installation is UNDER a WordPress installation:

```
myurl.com = WordPress site
myurl.com/rss = FreshRSS install
```

This has worked for many years, I am aware there is a .htaccess file in the root of my webfolder, and when I remove the following lines (commented out)
```
# BEGIN WordPress
# The directives (lines) between "BEGIN WordPress" and "END WordPress" are
# dynamically generated, and should only be modified via WordPress filters.
# Any changes to the directives between these markers will be overwritten.
<IfModule mod_rewrite.c>
#RewriteEngine On
#RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
#RewriteBase /
#RewriteRule ^index\.php$ - [L]
#RewriteCond %{REQUEST_FILENAME} !-f
#RewriteCond %{REQUEST_FILENAME} !-d
#RewriteRule . /index.php [L]
</IfModule>

# END WordPress
````

AND change the path as stated in https://github.com/FreshRSS/FreshRSS/issues/4610#issuecomment-1245164215

Then it works again.

HOWEVER: this breaks my WordPress installation. So this is a problem (and it never was a problem before).

**Comment by Alkarex** [comment]
Does it work again for you?
With your setup, I believe your `base_url` is supposed to be `https://j11g.com/rss/p/`

**Comment by jan-vandenberg** [comment]
Yes for now it works, still strange though something must have changed with the redirects etc. (I've been running the same FreshRSS config for many years and upgrading was never a problem).

Thanks for reaching out and helping, I guess we can close this issue.

**Comment by Alkarex** [comment]
Yes, a new explicit redirection has been added https://github.com/FreshRSS/FreshRSS/pull/4167 to work-around some problems with some reverse-proxy setups
But now, some configuration bugs (in `base_url`) have become more apparent...
