### ISSUE TITLE
[BUG]: Infinite redirects "ERR_TOO_MANY_REDIRECTS"

### ISSUE THREAD

**Issue by oliversum-ch** [FreshRSS/FreshRSS#4611]
**Describe the bug**

**To Reproduce**
1. I updated to 1.20.0
2. In the settings, I deactivated "Clicking outside of article text area closes the article"
3. I clicked on "submit"
4. I got a "ERR_TOO_MANY_REDIRECTS" error. 
5. Whatever I do, I get this error.
6. I can see that FreshRSS adds "https://freshrss.maydomain.com/freshrss/p/i/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/" to the URL. Correct would be "https://freshrss.maydomain.com/p/i/"

**Expected behavior**
No ERR_TOO_MANY_REDIRECTS.

**Screenshots**

**Environment information (please complete the following information):**
- Device: Windows, Android
- OS: Windows 10, Android 9
- Browser: Sidekick 102.26.1.23369 (127.2.0), Chrome 107.0.5297.1 (Official Build) canary-dcheck (64-bit)
- FreshRSS version: 1.20.0
- Database version: not sure, sorry
- PHP version: 7.4.30
- Installation type: Cpanel, Update via FreshRSS settings

**Additional context**
log.txt:
[Tue, 13 Sep 2022 08:37:01 +0100] [warning] --- FreshRSS_CategoryDAO::addColumn: kind
[Tue, 13 Sep 2022 08:37:01 +0100] [warning] --- FreshRSS_CategoryDAO::addColumn: lastUpdate
[Tue, 13 Sep 2022 08:37:01 +0100] [warning] --- FreshRSS_CategoryDAO::addColumn: error
[Tue, 13 Sep 2022 08:37:01 +0100] [warning] --- FreshRSS_EntryDAO::addColumn: attributes

**Comment by Alkarex** [comment]
Might be a regression due to https://github.com/FreshRSS/FreshRSS/pull/4167 for https://github.com/FreshRSS/FreshRSS/issues/4126
Maybe similar to https://github.com/FreshRSS/FreshRSS/issues/4221
Maybe related to https://github.com/FreshRSS/FreshRSS/issues/4610

Could you check what `base_url` you have in your `./data/config.php` ?

Ideally, there should be no `/p/` in your URL, so the main page should be on `https://freshrss.example.net/i/`

**Comment by oliversum-ch** [comment]
Thanks for your reply!
You're right, the `base_url` was wrong - no idea why, I didn't change anything and FreshRSS was working smoothly for more than one year with these settings.
It wonly works with `https://freshrss.example.net/p/` though, I immediately get an infinite redirect with `https://freshrss.example.net/i/`.

**Comment by Alkarex** [comment]
Could you please tell where your Web root is in your local file structure (for instance `/var/www/FreshRSS/p/`), what working URL you have, and what `base_url` you have?

**Comment by oliversum-ch** [comment]
Sure!
Root: `/home/sites/7b/0/09ec7hg48d/public_html/FreshRSS/`
Working URL (I assume that's the URL I'm using to access FreshRSS): `https://freshrss.mydomain.com/`
`'base_url' => 'https://freshrss.mydomain.com/p/'`

**Comment by Alkarex** [comment]
Can you try with the opposite:
* Root: `/home/sites/7b/0/09ec7hg48d/public_html/FreshRSS/p/`
* Base URL: `https://freshrss.example.net/`

**Comment by oliversum-ch** [comment]
That seems to work, thank you!
Interesting, I installed FreshRSS using Cpanel - looks like their installation paths were wrong.
Thank you!

**Comment by Alkarex** [comment]
@oliversum-ch Could you try to reach-out to Cpanel?

**Comment by oliversum-ch** [comment]
I'm using shared hosting with Cpanel. Let me contact my hoster, but I fear I cannot directly contact Cpanel...

**Comment by aledeg** [comment]
@oliversum-ch any new development on that issue?

**Comment by oliversum-ch** [comment]
> @oliversum-ch any new development on that issue?

No - my shared hosting promised it to forward it to Cpanel, but I don't expect any further answer...

**Comment by Alkarex** [comment]
I cannot reproduce any problem at the moment, even with slightly wrong settings.
It might have been a combination of browser cache and wrong settings.
