### ISSUE TITLE
[BUG] 1.20.0 changed broke editing feed using for existing feeds.

### ISSUE THREAD

**Issue by zoredache** [FreshRSS/FreshRSS#4612]
**Describe the bug**
In earlier versions if you used a bookmarklet on a feed that already exists, you would go to the edit page for that subscription.  Now you only get a notice 'You have already subscribed to ...'

**To Reproduce**

- Use the bookmarklet to on some page/feed that already exists.

**Expected behavior**
Getting the the ability to edit the feed by just clicking the bookmarklet was very useful in my opinion. Displaying only the you are already subscribed is annoying.  I would prefer to have it go back to the feed editing screen like before.  Or if that isn't an option, make the 'You have already subscribed to ...' notice actually be a link to the edit form for that feed, or a link to the articles to that feed or something.

**Environment information (please complete the following information):**
- Web interface
- Browser: Seems to happen in any browser.
- FreshRSS version: 1.20.0
- Self-hosted via Docker using image: `freshrss/freshrss:latest` checksum: 578f38339513

**Additional context**

This new behavior is also impacts newly added feeds.

When adding a new feed, I would often use the bookmarklet, choose the category, click submit.  After clicking submit I would get the edit form and I could change the advance settings like the refresh frequency,  filter actions, archiving and so on.  You could also click the 'filter' link and immediately go the list of articles for that newly added feed, where you might mark a bunch of the stuff as read, and possibly favorite/label the article that inspired add the feed.

Now after adding a new feed, you immediately 'Subscription management' page with the 'You have already subscribed to ...' displayed. You don't get any links to the newly added feed.

Anyway, this changed behavior is a downgrade to usability in my opinion.

**Comment by zoredache** [comment]
I am not sure I fully understand what changed caused the problem. Or how it was doing the right thing before.  But making this change seems to restore the previous behavior. 

    diff --git a/app/Controllers/feedController.php b/app/Controllers/feedController.php
    index 00759bd1..7030c27c 100755
    --- a/app/Controllers/feedController.php
    +++ b/app/Controllers/feedController.php
    @@ -240,7 +240,7 @@ class FreshRSS_feed_Controller extends FreshRSS_ActionController {
                            }
    
                            // Entries are in DB, we redirect to feed configuration page.
    -                       $url_redirect['a'] = 'index';
    +                       $url_redirect['a'] = 'feed';
                            $url_redirect['params']['id'] = '' . $feed->id();
                            Minz_Request::good(_t('feedback.sub.feed.added', $feed->name()), $url_redirect);
                    } else {
    @@ -261,7 +261,7 @@ class FreshRSS_feed_Controller extends FreshRSS_ActionController {
                            $feed = $feedDAO->searchByUrl($this->view->feed->url());
                            if ($feed) {
                                    // Already subscribe so we redirect to the feed configuration page.
    -                               $url_redirect['a'] = 'index';
    +                               $url_redirect['a'] = 'feed';
                                    $url_redirect['params']['id'] = $feed->id();
                                    Minz_Request::good(_t('feedback.sub.feed.already_subscribed', $feed->name()), $url_redirect);
                            }

**Comment by Alkarex** [comment]
Your suggestion of patch looks fine. Could you please send a pull request?
