### ISSUE TITLE
[BUG] not sure update went fine

### ISSUE THREAD

**Issue by gpion** [FreshRSS/FreshRSS#4614]
**Describe the bug**

Update to version 1.20.0 using the "update" page doesn't produce any viewable result.

- On "update" page, message _"Okay! FreshRSS will now be updated to the version 1.20.0."_ is displayed
- I clicked _"Apply"_ button
- Nothing happened apparently but "about" page indicate that site is now running version "1.20.0"
- the "logs" page contains only those 4 events:
  - FreshRSS_EntryDAO::addColumn: attributes
  - FreshRSS_CategoryDAO::addColumn: error
  - FreshRSS_CategoryDAO::addColumn: lastUpdate
  - FreshRSS_CategoryDAO::addColumn: kind

**To Reproduce**
Unable to reproduce

**Expected behavior**
Update acknowledge ("updated successfuly" message) 

**Screenshots**
N/A

**Environment information (please complete the following information):**
- Device: Synology NAS DS213j
- OS: DSM 7.1.1-42962
- Browser: Chrome, latest version
- FreshRSS version: 1.20.0.
- Database version: MariaDB  10.3.32
- PHP version:  7.2.34 
- Installation type: don't knw what this is

**Additional context**

according to "Installation check" page everything is OK

**Comment by tobip** [comment]
I got the exact same outcome. So far freshrss seems to work fine though.
