### ISSUE TITLE
[BUG?] Feeds not updated with online cron and php8 or php8.1

### ISSUE THREAD

**Issue by kiwi-x** [FreshRSS/FreshRSS#4615]
**Description**

I have to use the online cron whcih is described here
https://freshrss.github.io/FreshRSS/en/users/03_Main_view.html#online-cron

Anyhting works fine when I use php7.4.

When I switch to php8.0 or php8.1 the feeds won't get updated.
And it looks like it's not working correct, if I press on the update 
feed button in web ui.

Do I something wrong or is it a knoen issue with php8|8.1

I wouldn't mind, but HostEurope will stop php7.4 support in november 2022.

**To Reproduce**

Setup you environment to use php8 or php8.1
1. Go to homepage
2. Click on 'Refresh'

or use an external cron job and call

https://freshrss.example.com/i/?c=feed&a=actualize&force=1&ajax=1&token=*********************

**Expected behavior**
Feeds should be updated :)

**Environment information (please complete the following information):**
- FreshRSS version: 1.20
- Database version: Mysql ?
- PHP version: PHP 8.0|8.1
- Installation type: Custom installation at HostEurope

**Comment by Alkarex** [comment]
Hello,
Can you check whether you have any message in your FreshRSS logs or Web server logs?

**Comment by kiwi-x** [comment]
Hi,

I like to support as far as I can, so I've just checked it. 

I switched my installation to PHP Version 8.1 (8.1.10-he.0)

At installaction check any item is okay/green.

Clicked (multiple times) on the Refresh Button.

The FreshRSS Protokoll remains empty.

IIn the access lot I can see the entries like this
IPv6ADDR - - [15/Sep/2022:23:00:36 +0200] "POST /i/?c=feed&a=actualize&id=-1&ajax=1 HTTP/1.1" 200 3 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36 OPR/90.0.4480.84" "my.domain.tld"

PHP error log remains empty, too

But no new  - while on my old feed aggregator has 10 new entries.

Every time I click on the refresh button - it checks all 100+ feeds (very fast all are interated in less then 2 seconds). 
It now never says that there is no feed to update (like before)

So for me it looks like the feeds aren't processed.

Could I check anything else?

Chers
kiwi-x

**Comment by Alkarex** [comment]
It can also simply be that your feeds have been refreshed too recently. Can you try to leave your installation as it is, with PHP 8, and try again to refresh 2 hours later?

**Comment by kiwi-x** [comment]
Yes. I will let php8.1 enabled till tomrrow and then we will see.

**Comment by kiwi-x** [comment]
Okay 

I did a second installation on a lxc container and there anything works like expected.

Today it seems to work at HostEurope, too.
There's still a problem with the console tools, which knows the database but not the password (which is in the same file).

So now I think that's Issue of HostEurope and of FreshRSS.

So thanks for your support,
Excuse the opened issue here

Cheers
kiwi-x
