### ISSUE TITLE
[BUG] Can't update, white screen

### ISSUE THREAD

**Issue by cameradoppia** [FreshRSS/FreshRSS#4624]
Hi there, awsome project!

When we try to update via interface update-button to the latest version (1.20.0) a blank page appears at https://mysite.com/newsfeed/p/i/?c=update&a=apply

No errors in server logs. Any ideas?

Thanks in advance and best regards 
Dan

- Device: Mac / Win / mobile
- OS: Debian 10.13
- Browser: Firefox / Chrome
- FreshRSS version: 1.19.2
- Database version: 10.3.36-MariaDB
- PHP version: PHP 7.3.33
- Installation type: Linux / Cpanel 3.10.0-1160.66.1.el7.x86_64

**Comment by Alkarex** [comment]
Maybe a similar problem than this cpanel user 
https://github.com/FreshRSS/FreshRSS/issues/4611#issuecomment-1245117944

But please double check your Web server and FreshRSS logs, maybe MariaDB logs

**Comment by cameradoppia** [comment]
Ok, we are checking that out, thanks!

**Comment by Alkarex** [comment]
Probably fixed by https://github.com/FreshRSS/FreshRSS/pull/4629 and https://github.com/FreshRSS/update.freshrss.org/pull/4
But for the time being, does it work if you try again?

**Comment by cameradoppia** [comment]
Nope, same white screen. 
We actually have a new folder called data.back and one new zip: update_package.zip, guess that's a first step :)

**Comment by Alkarex** [comment]
Try to delete:
* `./freshrss/data/update.php`
* `./freshrss/data/last_update.txt`
* The new files / folders you have mentioned

And try again.

If that still does not work, you will have to unpack the current version on top of your existing one.
The Web update using ZIP archives is less robust than updates using git or Docker. So if you can, another time, deploy by git instead.

**Comment by cameradoppia** [comment]
OK Alkarex, we will follow your instructions. 

Thank you very much for your time and attention,
all the best!
Dan

**Comment by Alkarex** [comment]
I think the update bugs have been fixed
