### ISSUE TITLE
[BUG] ./app/actualize_script.php does not update

### ISSUE THREAD

**Issue by Stunkymonkey** [FreshRSS/FreshRSS#4626]
followup #4582

**Describe the bug**
Running 
`ExecStart=/nix/store/gawjg0jivpy3b0qxyqmbpqw25r7ar90m-php-with-extensions-8.0.22/bin/php ./app/actualize_script.php (code=exited, status=0/SUCCESS)` always suceeds, but never updates.

```
Sep 19 20:20:01 newton systemd[1]: Starting FreshRSS feed updater...
Sep 19 20:20:01 newton FreshRSS[430403]: FreshRSS starting feeds actualization at 2022-09-19T18:20:01+00:00
Sep 19 20:20:01 newton php[430403]: FreshRSS starting feeds actualization at 2022-09-19T18:20:01+00:00
Sep 19 20:20:01 newton FreshRSS[430403]: FreshRSS actualize felix…
Sep 19 20:20:01 newton php[430403]: FreshRSS actualize felix…
Sep 19 20:20:01 newton FreshRSS[430403]: SimplePie GET https://rss.golem.de/rss.php?feed=ATOM1.0
Sep 19 20:20:01 newton FreshRSS[430403]: FreshRSS actualization done for 1 users, using 6.00 MiB of memory, in 0 day(s), 0 hour(s), 0 minute(s) and 0 seconds.
Sep 19 20:20:01 newton php[430403]: FreshRSS actualization done for 1 users, using 6.00 MiB of memory, in 0 day(s), 0 hour(s), 0 minute(s) and 0 seconds.
Sep 19 20:20:01 newton php[430403]: Results:
Sep 19 20:20:01 newton php[430403]: felix OK
Sep 19 20:20:01 newton php[430403]: End.
Sep 19 20:20:01 newton systemd[1]: freshrss-updater.service: Deactivated successfully.
Sep 19 20:20:01 newton systemd[1]: Finished FreshRSS feed updater.
```

**To Reproduce**
1. I am currently working on bringing it to NixOS, thereby I am moving the data folder to another location (`/var/lib/freshrss/`).
2. Add feeds
3. Wait
4. See warning

**Expected behavior**
The feeds should update.

**Screenshots**
![Screenshot-2022-09-19_201646](https://user-images.githubusercontent.com/1315818/191086187-319ea222-67b5-45c3-ac0d-d7b77f7c7d5d.png)

**Environment information (please complete the following information):**
- Device: [e.g. VM]
- OS: [e.g. NixOS 22.05]
- Browser: [e.g. Firefox 104]
- FreshRSS version: [e.g. 1.20.0]
- Database version: [e.g. SQlite]
- PHP version: [e.g. PHP 8.0.22]
- Installation type: [e.g. Custom]

**Additional context**
I do not find any error. phpfpm, systemd-timer and systemd-service seems fine. Not sure where else to look.

**Comment by Alkarex** [comment]
Could you please try to put `'environment' => 'development',` in your `./data/config.php` to hopefully get a few more logs?

**Comment by Stunkymonkey** [comment]
could you please tell me what logs are most interesting?
the phpfpm is exactly the same as yesterday...
the actualize_script.php service has nothing interesting...

**Comment by Alkarex** [comment]
Please look in `./freshrss/data/users/*/log*.txt`

**Comment by Stunkymonkey** [comment]
nevermind the systemd service was limited too much, and then it stopped working.
