### ISSUE TITLE
[BUG] ./data/cache with 6700+ files 2+GB

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#4627]
While I backed up my server I see that the /data/cache folder has more than 6700 files that need more than 2GB storage.

The files are created between August 20nd 2022 and September 19th 2022 (today).

Biggest files:
![grafik](https://user-images.githubusercontent.com/1645099/191102689-3d3d99f0-9942-4f76-aabd-f06a34addac6.png)

Most files are `html` files, that are a copy from websites for CSS selector that retrieves truncated RSS feeds.
And `spc` files that are JSON files.

Does it makes sense to keep this cache files for 1 month?
Would it be possible to use less storage?

**Environment information (please complete the following information):**
- FreshRSS version: 1.20.0-dev (before updating to 1.20.0)

**Comment by Alkarex** [comment]
I am guessing this is on Windows, right?

**Comment by Alkarex** [comment]
Could you try to do a bit of tracing / debugging of:

https://github.com/FreshRSS/FreshRSS/blob/412b60ca8380dd760225574746207cf8e90a2b43/lib/lib_rss.php#L334-L345

Maybe an issue with `GLOB_BRACE` not available on some platforms according to the documentation

**Comment by math-GH** [comment]
> I am guessing this is on Windows, right?

No, it is a simple webspace. Some Linux. Do you need more information from phpinfo()?

**Comment by Alkarex** [comment]
Could you please try https://github.com/FreshRSS/FreshRSS/pull/4628 ?

**Comment by Alkarex** [comment]
Yes please, more platform info would be nice. What Linux more precisely?

**Comment by math-GH** [comment]
> Yes please, more platform info would be nice. What Linux more precisely?

Does it help?
![grafik](https://user-images.githubusercontent.com/1645099/191117117-4915f39a-7c5c-4b67-91c8-710a0ea61d70.png)

**Comment by Alkarex** [comment]
Hum, not really. Is it a GNU Linux? And not e.g. Solaris or Alpine Linux. See https://php.net/glob

**Comment by math-GH** [comment]
> Could you try to do a bit of tracing / debugging of:
> 
> https://github.com/FreshRSS/FreshRSS/blob/412b60ca8380dd760225574746207cf8e90a2b43/lib/lib_rss.php#L334-L345
> 
> Maybe an issue with `GLOB_BRACE` not available on some platforms according to the documentation

I tried
``` php
function cleanCache(int $hours = 720) {
	$files = glob(CACHE_PATH . '/*.{html,spc}', GLOB_BRACE | GLOB_NOSORT);
	Minz_Log::error('Start cleanCache');
	foreach ($files as $file) {
		Minz_Log::error('File '.$file);
		if (substr($file, -10) === 'index.html') {
			continue;
		}
		$cacheMtime = @filemtime($file);
		if ($cacheMtime !== false && $cacheMtime < time() - (3600 * $hours)) {
			Minz_Log::error('unlink '.$file);
			unlink($file);
		}
	}
	Minz_Log::error('End cleanCache');
}
```

But cannot find any log entry. I updated the feeds. How is cleanCache() triggered?

**Comment by Alkarex** [comment]
Please try with this patch https://github.com/FreshRSS/FreshRSS/pull/4628

`cleanCache()` is called randomly:

https://github.com/FreshRSS/FreshRSS/blob/6813e16e95c631084029cc84f786acd87495c063/lib/lib_rss.php#L396-L398

You can try to copy this call elsewhere

**Comment by math-GH** [comment]
> Hum, not really. Is it a GNU Linux? And not e.g. Solaris or Alpine Linux. See https://php.net/glob

Looks like GNU Linux. I cannot find more information.
![grafik](https://user-images.githubusercontent.com/1645099/191122517-8c021c96-e68b-4d65-82b6-ead88e7f33a7.png)

**Comment by math-GH** [comment]
Will try tomorrow

**Comment by math-GH** [comment]
Btw `$hours = 720` =30 days. It keeps the files for 30 days (August 30th - September 19th).

So it worked fine. But does it make sense to keep the cached files for 1 month? 24 hours would be enough?

**Comment by Alkarex** [comment]
The cache is not only about downloading, but also to check if anything has changed since the last query, saving resources.
I have many feeds set up to refresh only every few days.
There is also the case of setups with multiple users, which might not refresh at the same time.
But alright, 30 days might be a bit too much by default. Maybe 1 week so.

**Comment by Frenzie** [comment]
Shouldn't it delete the old cache once there's a new one? Or are there 6700 distinct feeds involved?

**Comment by Alkarex** [comment]
> Shouldn't it delete the old cache once there's a new one? Or are there 6700 distinct feeds involved?

@Frenzie I guess the HTML files are from individual Web pages retrieved by CSS selector. We could consider having a shorter cache for `*.html` than for `*.spc`

**Comment by audech** [comment]
Sorry for piggybacking, but I have the same issue on shared webhosting. I admit having lots of feeds expanded by CSS selector. In order to tailor to my needs: is $cacheMtime under "Archiving" settings or would that need to be set separately?
Or to rephrase: any way caching is mirroring the archiving settings, i.e. deleting more frequently but keeping starred and and unread articles if set so there? Or would that not matter?
Because my cache is >2GB with oldest files dated 19 January, but the archiving page says 144.5 MB occupied.

**Comment by Alkarex** [comment]
@audech At the moment, we have no customisable setting for that. 

This line must be modified with a shorter duration, while waiting for a more customisable functionality:

https://github.com/FreshRSS/FreshRSS/blob/f3216b61b9d02531dad0d4244563c0d44cdc89ba/lib/lib_rss.php#L366
