### ISSUE TITLE
ByetHost: Can't auth with API

### ISSUE THREAD

**Issue by AlexBromum** [FreshRSS/FreshRSS#4630]
**Describe the bug**
Every time when I try to auth in any app or program, there is download errors (or just can't get feeds). However, GReader configuration tests are "PASS", API and API password enabled.

**To Reproduce**
1. Go to any app
2. Auth with path to API, my login and password
3. See errors:
"JSON parse error" in FeedMe
"Error while downloading new articles" in FocusReader
"use jsonreader.setlenient true to accept malformed json at path $" in Readrops
empty folders in RSS Guard

**Screenshots**
![изображение](https://user-images.githubusercontent.com/110740859/191122927-5a322e82-f972-4598-8994-528e5c6cfc96.png)
![изображение](https://user-images.githubusercontent.com/110740859/191122933-c2b74189-660d-4823-8e86-b9715b604340.png)
![изображение](https://user-images.githubusercontent.com/110740859/191122941-a4918975-ba79-4903-be5b-52284b4a6fb8.png)

**Environment information (please complete the following information):**
- OS: Android 11, Windows 10
- Browser: FreshRSS in Firefox 104.0.2
- FreshRSS version: 1.20.0
- Database version: IDK
- PHP version: PHP 7.0
- Installation type: Softaculous on byet host

**Comment by Alkarex** [comment]
Would you be able to try from your computer's command line?
https://freshrss.github.io/FreshRSS/en/developers/06_GoogleReader_API.html#google-reader-compatible-api

**Comment by AlexBromum** [comment]
> Would you be able to try from your computer's command line? https://freshrss.github.io/FreshRSS/en/developers/06_GoogleReader_API.html#google-reader-compatible-api

I can only "Initial login, using API password" and get

```
StatusCode        : 200
StatusDescription : OK
Content           : <html><body><script>document.cookie="_test=3cd5b1537ddf09492d22dd546cbeff3d ; expires=Thu, 31-Dec-37 23:55:55 GMT; path=/"
                     ;document.location.href="http://trignarek.byethost17.com/home/vol11_8/byethos...
RawContent        : HTTP/1.1 200 OK
                    Connection: keep-alive
                    Vary: Accept-Encoding
                    Content-Length: 324
                    Cache-Control: no-cache
                    Content-Type: text/html
                    Date: Mon, 19 Sep 2022 22:16:05 GMT
                    Expires: Thu, 01 Jan 1970 00...
Forms             :
Headers           : {[Connection, keep-alive], [Vary, Accept-Encoding], [Content-Length, 324], [Cache-Control, no-cache]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        :
RawContentLength  : 324
```

I don't understand how I can use others.

**Comment by Alkarex** [comment]
It looks like you are receiving an HTML document instead of the response from the API, which explains why the clients are failing.

What does the following command return? (It is supposed to return 'OK')

```sh
curl -v 'https://freshrss.example.net/api/greader.php'
```

**Comment by AlexBromum** [comment]
It returned:
```shell
StatusCode        : 200
StatusDescription : OK
Content           : <html><body><script>document.cookie="_test=3cd5b1537ddf09492d22dd546cbeff3d ; expires=Thu, 31-Dec-37 23:55:55 GMT; path=/"
                     ;document.location.href="http://trignarek.byethost17.com/home/vol11_8/byethos...
RawContent        : HTTP/1.1 200 OK
                    Connection: keep-alive
                    Vary: Accept-Encoding
                    Content-Length: 256
                    Cache-Control: no-cache
                    Content-Type: text/html
                    Date: Mon, 19 Sep 2022 23:40:21 GMT
                    Expires: Thu, 01 Jan 1970 00...
Forms             :
Headers           : {[Connection, keep-alive], [Vary, Accept-Encoding], [Content-Length, 256], [Cache-Control, no-cache]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        :
RawContentLength  : 256
```

> It looks like you are receiving an HTML document instead of the response from the API, which explains why the clients are failing.
> 

That's strange. How I can fix it?

**Comment by Alkarex** [comment]
That is not the output of a standard curl command, is it?

Anyway, it looks like the URL you are trying is either wrong, or hosting another conflicting Web service, or is being filtered somehow.

**Comment by samolukadjo** [comment]
It seems I'm having basically the same problem.

And we're both using Byethost… I feel like it probably has something to do with that.

**Comment by samolukadjo** [comment]
It returns the expected “OK” only when opened in the browser. I believe it's possible they might have some kind of measure against non-browser access or a measure against something else that just so happens to break non-browser access like this.

**Comment by Frenzie** [comment]
Setting a cookie through JS and redirecting through JS would filter out some low-level bots… and also many perfectly regular applications.

**Comment by Alkarex** [comment]
@samolukadjo What is the output of your `curl -v 'https://freshrss.example.net/api/greader.php'` ?
You might have some settings on your host to control network filtering.

**Comment by samolukadjo** [comment]
```
* Host myfreshrss.byethost13.com:80 was resolved.
* IPv6: (none)
* IPv4: 185.27.134.116
*   Trying 185.27.134.116:80...
* Connected to myfreshrss.byethost13.com (185.27.134.116) port 80
> GET /p/api/greader.php HTTP/1.1
> Host: myfreshrss.byethost13.com
> User-Agent: curl/8.5.0
> Accept: */*
> 
* Empty reply from server
* Closing connection
curl: (52) Empty reply from server
```

I've been getting "Empty reply from server" for some time now, and I don't think the host will let me change this.

**Comment by Alkarex** [comment]
Even curling the root of your Web server seems to fail.
And by the way, the HTTPS version (which you should use) fails even more due to a problem in the chain of certificates (ZeroSSL):

```console
$ curl 'https://myfreshrss.byethost13.com/'
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the webpage mentioned above.
```

If you cannot modify the hosting settings, no way this will work, so will need to host elsewhere.

**Comment by Alkarex** [comment]
This host suffers from more than one problem...

https://www.ssllabs.com/ssltest/analyze.html?d=myfreshrss.byethost13.com

![image](https://github.com/user-attachments/assets/aa3146f5-f409-4cf4-a741-621aba4cefd2)

![image](https://github.com/user-attachments/assets/4f4e47fa-42e4-4fce-8b63-ee318a56854f)
