### ISSUE TITLE
[BUG] OPML blizzard icon: not shown

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#4634]
**Describe the bug**
The OPML blizzard icon is not shown (see environment)
![grafik](https://user-images.githubusercontent.com/1645099/191564968-3ce3854b-faa0-44f2-9997-079a79e8a26e.png)

**To Reproduce**
1. go to subscription management
2. edit a category

**Expected behavior**
see the blizzard icon

**Environment information (please complete the following information):**
- Device: Mobile Phone
- OS: Android 10
- Browser: Firefox 106 (Nightly)
- FreshRSS version: 1.21.0-dev

**Comment by Alkarex** [comment]
Can you see the following sign from the same platform? 🗲

**Comment by math-GH** [comment]
> Can you see the following sign from the same platform? 🗲

The same: it is just a grey box. Tested it on `Firefox` and `Firefox Klar/Focus` on Android. Both use the same rendering engine.

**Comment by Alkarex** [comment]
I actually have the same lack on my old Android 9 with Firefox / Chrome / Samsung Internet.
And I have just tested on another phone with Android 12, also same lack.

**Comment by Alkarex** [comment]
🗲 is supposed to be in Unicode 7.0 from 2014... https://emojipedia.org/lightning-mood/
The closest is ⚡ https://emojipedia.org/high-voltage/ but I prefer the current 🗲

**Comment by Frenzie** [comment]
It doesn't show on my Android 12 phone here either.

**Comment by NicolasPereira** [comment]
I'm open a PR fix this problem
