### ISSUE TITLE
[BUG] "Keep me logged in" only works for one day

### ISSUE THREAD

**Issue by rixx** [FreshRSS/FreshRSS#4637]
Since updating FreshRss to 1.20.0, "keep me logged in" only seems to work for one day (calendar day, I think?) for me, even when I tick the "Keep me logged in" checkbox. It works perfectly during that one day, but on the next day, I have to log in again.

I was able to stay logged in before the update – though I'm afraid I updated across multiple versions, so I can't point at the actual problem.

**Environment information (please complete the following information):**
- OS: Arch Linux
- Browser: Firefox 106.0a1
- FreshRSS version: 1.20.0
- Database version: Postgresql 14.5
- PHP version: 8.1.10
- Installation type: Source install

Happy to provide any logs that could be useful. Browser console only shows to CSP errors and two font download errors which don't seem to impact this process (as I can log in, after all).

**Comment by math-GH** [comment]
Could you please give an insight of the cookies settings?
Please open in the developer bar the web storage tab.

Example: 
![grafik](https://user-images.githubusercontent.com/1645099/191975799-7ab254dc-9575-4498-a39b-79d0997b4144.png)

Can you please check it also with another browser (Chrome, Edge etc.)? I am not sure if this issue comes from strong privacy settings in Firefox.

**Comment by rixx** [comment]
Of course! This screenshot is from when I found myself logged out today. I only have a single cookie, and you can see its expiry is set to "Session". Logging in under Chrome has similar results, and I'll check back to see if I'm staying logged in there.
![2022-09-23T16:08:43+02:00](https://user-images.githubusercontent.com/2657547/191992977-a01cc93a-cae6-4e84-8f08-970587677a11.png)

**Comment by rixx** [comment]
Update: Yes, Chrome also logs me out, took less than a day this time. (But I can stay logged in across browser re-starts, so it's not that.)

**Comment by math-GH** [comment]
Please screen shot when you are logged in. 
path `/i/` = valid for the session
path `/i` = 90 days cookie

**Comment by rixx** [comment]
Here is a screenshot from when I'm logged in. Looks correct to me.
![2022-09-23T20:44:27+02:00](https://user-images.githubusercontent.com/2657547/192036229-375f9522-2a0b-4b78-8450-7e485ee88a79.png)
![2022-09-23T20:45:21+02:00](https://user-images.githubusercontent.com/2657547/192036237-27346fef-8b71-4a42-8878-4b045fa17279.png)

**Comment by rixx** [comment]
Hm. I don't get logged out anymore. I swear this happened for three or four days after the update before I even opened this issue, and then twice more, but it seems gone now. Sorry for the noise.
