### ISSUE TITLE
[BUG] Wrong unread message icon size

### ISSUE THREAD

**Issue by wolfpld** [FreshRSS/FreshRSS#4645]
After upgrading to 1.20.0, when using the Mapco theme, the unread message icon (the blue one on the right side on the screen below) has wrong aspect ratio. It seems that the icon height is stretched to be uniform with the read message icon height, as shown on the screenshot below.

![obraz](https://user-images.githubusercontent.com/600573/192472206-b391b8ce-459b-42c2-b934-a71c16d1481d.png)

Random screenshot showing that icons didn't had the same height in previous versions: https://www.glovbox.com/wp-content/uploads/2021/07/screenshot-rocks.png

May be caused by #4353?

**Comment by Frenzie** [comment]
I think it's a global issue.
