### ISSUE TITLE
[i18n] Translation Italian (IT) 🇮🇹 - Hacktoberfest Task

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#4658]
Dear Hacktoberfest-Community,

please help us to improve our 🇮🇹 Italian translations.

While we develop our [FreshRSS ](https://freshrss.org/) app we cannot support the translations in all 15+ languages. 

## About the FreshRSS app
FreshRSS is a free, self-hostable feed aggregator licenced by [GNU AGPL 3](https://github.com/FreshRSS/FreshRSS/blob/edge/LICENSE.txt). These days we celebrate the 10th birthday!

## Actual Status
Right now about 70% of our text is translated into 🇮🇹 Italian .

## How to support us
How to do it:
1) it is very simple
2) all files are stored in `https://github.com/FreshRSS/FreshRSS/tree/edge/app/i18n/cz` ([Link](https://github.com/FreshRSS/FreshRSS/tree/edge/app/i18n/cz))
3) each untranslated text has an inline comment `//  TODO`
4) When the text is translated, just delete the comment
5) If the English term fits as well, please change the comment from `//  TODO` to `//  IGNORE`
6) open a Pull Request and link to this ticket

## Thanks
Thanks a lot. It will help our very international community of users and developers. Your submitted PRs will be published with our next release version 1.20.1 or 1.21.0

**Comment by Pyr0x1** [comment]
Hello, I can work on this issue if not taken yet

**Comment by math-GH** [comment]
> Hello, I can work on this issue if not taken yet

Nice :) PRs are welcome :)

**Comment by sarequl** [comment]
Can I translate this to bn-BD?

**Comment by Frenzie** [comment]
To whatever you want (just maybe hold off on Klingon ;-P)

**Comment by math-GH** [comment]
@Pyr0x1 Thanks a lot for your contribution. Could you please have a short second look onto this 2 lines, that are not translated into Italian?

https://github.com/FreshRSS/FreshRSS/blob/65837de0e1d18aebb5f3b5664a925b8a19e0b214/app/i18n/it/sub.php#L101-L104

Thanks a lot.
