### ISSUE TITLE
[i18n] Translation Russian (RU) 🇷🇺 - Hacktoberfest Task

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#4661]
Dear Hacktoberfest-Community,

please help us to improve our 🇷🇺 Russian translations.

While we develop our [FreshRSS ](https://freshrss.org/) app we cannot support the translations in all 15+ languages. 

## About the FreshRSS app
FreshRSS is a free, self-hostable feed aggregator licenced by [GNU AGPL 3](https://github.com/FreshRSS/FreshRSS/blob/edge/LICENSE.txt). These days we celebrate the 10th birthday!

## Actual Status
Right now about 90% of our text is translated into 🇷🇺 Russian.

## How to support us
How to do it:
1) it is very simple
2) all files are stored in `https://github.com/FreshRSS/FreshRSS/tree/edge/app/i18n/ru` ([Link](https://github.com/FreshRSS/FreshRSS/tree/edge/app/i18n/ru))
3) each untranslated text has an inline comment `//  TODO`
4) When the text is translated, just delete the comment
5) If the English term fits as well, please change the comment from `//  TODO` to `//  IGNORE`
6) open a Pull Request and link to this ticket

## Thanks
Thanks a lot. It will help our very international community of users and developers. Your submitted PRs will be published with our next release version 1.20.1 or 1.21.0

----
We do not support the Russian war in the Ukraine! We value free speech and free information. 🕊️ Stop war - make peace! ☮️

**Comment by aroramrinaal** [comment]
Hey @math-GH ,
Can I work on this issue?

**Comment by math-GH** [comment]
> Hey @math-GH , Can I work on this issue?

yes, of course :) PRs are welcome :)

**Comment by math-GH** [comment]
@aroramrinaal How is the progress? Do you need support?

**Comment by gulyapulya** [comment]
Hello @math-GH, if it is still available, I would love to contribute to this issue. This is my first Hacktoberfest, I will go through the files line by line and translate where possible. I am trilingual but I know Russian on the native level. 

PS: I also think you got the wrong link in your issue description and it should be https://github.com/FreshRSS/FreshRSS/tree/edge/app/i18n/ru 
for Russian instead of https://github.com/FreshRSS/FreshRSS/tree/edge/app/i18n/cz.

**Comment by gulyapulya** [comment]
Is there any way I can check any examples of the usage of the specific line of translation (ie how it is supposed to be used in a sentence or in the app)? I checked out [Contributing to internationalization (i18n)](https://github.com/FreshRSS/FreshRSS/blob/edge/docs/en/internationalization.md) but I am still wondering.

**Comment by math-GH** [comment]
> PS: I also think you got the wrong link in your issue description and it should be https://github.com/FreshRSS/FreshRSS/tree/edge/app/i18n/ru for Russian instead of https://github.com/FreshRSS/FreshRSS/tree/edge/app/i18n/cz.

fixed

**Comment by math-GH** [comment]
> Is there any way I can check any examples of the usage of the specific line of translation (ie how it is supposed to be used in a sentence or in the app)? I checked out [Contributing to internationalization (i18n)](https://github.com/FreshRSS/FreshRSS/blob/edge/docs/en/internationalization.md) but I am still wondering.

Almost (99%: ever) the texts are used standalone.

You could use demo.freshrss.org and switch the UI to Russian (go to the config via the cog button top right corner and chose "display").
In the UI you can see English texts if they are not translated.

**Comment by math-GH** [comment]
f.e. https://demo.freshrss.org/i/?c=subscription#slider and select via the cog icon a feed:
![grafik](https://user-images.githubusercontent.com/1645099/194481229-19a80b41-57ae-4bf0-aeac-401e708896b5.png)

![grafik](https://user-images.githubusercontent.com/1645099/194481368-a3497415-c8ba-47ed-8925-8401653dc80a.png)

https://demo.freshrss.org/i/?c=configure&a=reading
![grafik](https://user-images.githubusercontent.com/1645099/194481595-80674919-b9e8-4ea2-ac2d-bb89d150b257.png)

**Comment by gulyapulya** [comment]
Thanks for the detailed explanation, @math-GH! I have completed all translations that were labeled as TODO in the Russian folder. I referred to the demo website to better understand the use case and followed the previous translations for consistency.
