### ISSUE TITLE
[i18n] Translation Turkish (TR) 🇹🇷 - Hacktoberfest Task

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#4662]
Dear Hacktoberfest-Community,

please help us to improve our 🇹🇷 Turkish translations.

While we develop our [FreshRSS ](https://freshrss.org/) app we cannot support the translations in all 15+ languages. 

## About the FreshRSS app
FreshRSS is a free, self-hostable feed aggregator licenced by [GNU AGPL 3](https://github.com/FreshRSS/FreshRSS/blob/edge/LICENSE.txt). These days we celebrate the 10th birthday!

## Actual Status
Right now about 90% of our text is translated into 🇹🇷 Turkish.

## How to support us
How to do it:
1) it is very simple
2) all files are stored in `https://github.com/FreshRSS/FreshRSS/tree/edge/app/i18n/tr` ([Link](https://github.com/FreshRSS/FreshRSS/tree/edge/app/i18n/tr))
3) each untranslated text has an inline comment `//  TODO`
4) When the text is translated, just delete the comment
5) If the English term fits as well, please change the comment from `//  TODO` to `//  IGNORE`
6) open a Pull Request and link to this ticket

## Thanks
Thanks a lot. It will help our very international community of users and developers. Your submitted PRs will be published with our next release version 1.20.1 or 1.21.0

**Comment by holiq** [comment]
Can I make a pr for Indonesian translation?

**Comment by math-GH** [comment]
> Can I make a pr for Indonesian translation?

Yes, new languages are welcome :)

**Comment by holiq** [comment]
> Yes, new languages are welcome :)

Thanks, i will make it

**Comment by amrulizwan** [comment]
Can I make a pr for Indonesian translation?

**Comment by math-GH** [comment]
@holiq Any news here?

**Comment by amrulizwan** [comment]
Can i make it?

**Comment by math-GH** [comment]
> Can i make it?

Yes :) PR is welcome :)

**Comment by marienfressinaud** [comment]
(just a side note @math-GH: the license is not GNU3, but GNU AGPL 3 (or AGPL3), not a problem since you linked to the file :))

**Comment by holiq** [comment]
@math-GH I will give @amrulizwan to translate it

**Comment by CilgaIscan** [comment]
Hi, I am a Turkish native speaker and interested in the translation of this app :) I will be very happy if you could assign me to this issue.

**Comment by Alkarex** [comment]
@amrulizwan @CilgaIscan @holiq Maybe you could coordinate to find out who translates what. I suggest that anyone who starts translating sends a draft pull request, so that it is easier to monitor the status and the progress

**Comment by math-GH** [comment]
@amrulizwan @holiq translated/wanted to translate FreshRSS to Bahasa Indonesia (see PR #4706)

@CilgaIscan is the first one who wants to improve the Turkish translation :) You are welcome. We do not have any official assignment to issues.
