### ISSUE TITLE
Changer la catégorie de plusieurs flux

### ISSUE THREAD

**Issue by Cypouz** [FreshRSS/FreshRSS#468]
Salut la compagnie !

Je profite de ce message pour vous féliciter et remercier à nouveau pour tout le boulot accompli. J'utilise multi-quotidiennement FreshRSS et je le trouve toujours aussi génial. Je suis content de pouvoir me connecter sans _Persona_ et d'avoir vu pris en compte l'ensemble de mes requêtes. C'est beau le logiciel libre (petite larme).

L'une de mes catégorie commençant à devenir quelque peu buissonnante, j'en ai créé une autre (à défaut de pouvoir créer une sous-catégorie, cf. #229). Je n'ai pas trouvé la possibilité de sélectionner les flux à déplacer d'une catégorie à une autre. Il m'a donc fallu répéter l'opération pour chaque flux, l'un après l'autre.

Serait-il possible de faire quelque-chose ? Genre des cases à cocher pour sélectionner les flux désirés, puis un menu déroulant _« déplacer vers... »_, ou bien un système de _drag & drop_, ou autre...

Une autre possibilité est que la fonctionnalité existe déjà et qu'elle ne m'ait pas sautée au yeux :)

**Comment by aledeg** [comment]
Le drag&drop a pas mal amélioré la situation. Il serait possible de faire du drag&drop multiple, sans avoir recours a des checkboxes.

Il y a ce plugin de jQuery qui permet de faire ça => http://threedubmedia.com/code/event/drag. C'est distribué sous licence MIT. Une petite démo ici => http://threedubmedia.com/code/event/drag/demo/multi

Il y a probablement d'autres bibliothèques disponibles.

**Comment by SansGuidon** [comment]
Je crois que j'utilise déjà quelque chose similaire via jQuery, quelque chose comme http://jqueryui.com/draggable/ ou http://jqueryui.com/sortable/ , pas eu besoin de plugin et ça marche vraiment bien :) (et je l'ai déjà implémenté dans ma version locale de FreshRSS pour organiser les flux... me restait à le faire pour les catégories encore mais pas très long :) )

**Comment by aledeg** [comment]
le plugin dont je parle permet de faire ça pour plusieurs éléments simultanément. Il me semble que ce dont tu parles ne permette que d'un seul élément à la fois.
Corrige moi si je me trompe.

**Comment by SansGuidon** [comment]
Tu as raison mais je n'ai pas besoin de fonctions si étendues pour corriger de temps en temps les catégories ^^ car selon moi à moins d'avoir souvent à changer plusieurs flux d'un coup (ce qui me semble plus rare que de devoir corriger de temps en temps la catégorie d'un flux), utiliser les features par défaut de jQuery me suffit pas mal, et ça fonctionne bien (ergonomiquement) autant dans l'interface de lecture que de gestion ^^ de ce que j'ai expérimenté, et qui ne nécessite pas de sélection multiple en + du drag'n drop (moins de clics = + facile à utiliser via mobile aussi)

**Comment by marienfressinaud** [comment]
While the situation can be improved, this ticket was opened for years. I don't think a multi-selection would fit nicely in the actual interface and I'm starting to think that this drag&drop feature was maybe not the best solution. I would work with an UX designer to do it better though. Since nobody complained for a while now, I'm closing this ticket, let's open a new one in English if it's still a problem :)
