### ISSUE TITLE
alignments of icons

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#4683]
@math-GH Could you please check: after the recent changes with `line-height`, `vertical-align` combined with `display: online-block` makes some icons alignments too low (I am not sure which PR made this regression):

![image](https://user-images.githubusercontent.com/1008324/193756723-6e871508-5da1-45d0-aa7b-2b50a1c49997.png)

_Originally posted by @Alkarex in https://github.com/FreshRSS/FreshRSS/issues/4673#issuecomment-1266504494_

**Comment by math-GH** [comment]
Firefox on Windows 10, `edge` branch looks like this:

![grafik](https://user-images.githubusercontent.com/1645099/193773834-3d01ebe8-879f-4068-867c-3a26a548f1ae.png)

The button does not look broken for me.
I will check the blizzard icon.

**Comment by Alkarex** [comment]
I should have mentioned that it was using the Pafat theme.

Here is using Origin, with Firefox on Windows 11, with which the arrow look OK-ish but the⚡is a bit too low (which I believe is a sign of potential general alignment bug with icons):
![image](https://user-images.githubusercontent.com/1008324/193848631-f2ef3a5d-d506-4946-81e9-c52d1d46cf86.png)

To illustrate the alignment of the icon in the title, I have manually added an inline copy:

![image](https://user-images.githubusercontent.com/1008324/193849392-ce35754e-5f2d-496e-8d7a-14a64d6519c8.png)

**Comment by math-GH** [comment]
I have a question to the blizzard "icon".

Right now it is `_i('opml-dyn')` used. While there is no icon in `/p/themes/icon` the UTF8 symbol from `Themes::alt($name)` is used. Usallay the UTF8 symbol is used for the `alt` parameter.

Why is the OPML icon (`p/themes/icons/opml.svg`) not used?

**Comment by Alkarex** [comment]
> Why is the OPML icon (`p/themes/icons/opml.svg`) not used?

See my comment on https://github.com/FreshRSS/FreshRSS/pull/4407#issuecomment-1159706227

But as we have changed from 🗲 to ⚡ (which I do not like quite as much) in https://github.com/FreshRSS/FreshRSS/pull/4673 , I do not mind as much anymore
