### ISSUE TITLE
[BUG] New articles banner is chunky

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/FreshRSS#4686]
On edge, and at least on origine/origine-compact (I have not checked other themes) new articles banner is chunkier than it used to be. It doesn't really bother me that much, but it looks like it hasn't been changed on purpose.

![image](https://user-images.githubusercontent.com/7189936/193859390-d7041a44-a092-4776-8e74-b160e531ff24.png)

It's even more prominent on mobile:

![image](https://user-images.githubusercontent.com/7189936/193859345-49fd2295-4165-4439-a08d-9e67eba0d7d9.png)

**Comment by aledeg** [comment]
@Alwaysin Please check attached PR. Thank you.

**Comment by Alwaysin** [comment]
I can confirm this is way better, thank you!

On a side note, when manually running actualize_script.php from CLI, I noticed _again_ (I do believe I quickly mentionned it somewhere a few days ago) that there is sometimes a huge delay, at least on Chrome, displaying this banner. Am I the only one noticing this? I'm not too sure there is an actual issue and I don't have that much time to try and reproduce it to make a detailed issue about it.

**Comment by aledeg** [comment]
> On a side note, when manually running actualize_script.php from CLI, I noticed _again_ (I do believe I quickly mentionned it somewhere a few days ago) that there is sometimes a huge delay, at least on Chrome, displaying this banner. Am I the only one noticing this? I'm not too sure there is an actual issue and I don't have that much time to try and reproduce it to make a detailed issue about it.

It depends on what kind of delay we are talking about. I don't know what is the refresh rate for that banner but if you're unlucky, you'll have to way the whole refresh rate time if the script ends just after a refresh.

**Edit** I checked the refresh rate and it's every 2 minutes. If your wait is longer than that it might be a warning sign for a bigger problem. If not, you're in the normal operational zone.

**Comment by Alwaysin** [comment]
> > On a side note, when manually running actualize_script.php from CLI, I noticed _again_ (I do believe I quickly mentionned it somewhere a few days ago) that there is sometimes a huge delay, at least on Chrome, displaying this banner. Am I the only one noticing this? I'm not too sure there is an actual issue and I don't have that much time to try and reproduce it to make a detailed issue about it.
> 
> It depends on what kind of delay we are talking about. I don't know what is the refresh rate for that banner but if you're unlucky, you'll have to way the whole refresh rate time if the script ends just after a refresh.
> 
> **Edit** I checked the refresh rate and it's every 2 minutes. If your wait is longer than that it might be a warning sign for a bigger problem. If not, you're in the normal operational zone.

Oh, okay, then it is perfectly normal! I did not time it but is looks like I was in this 2min range. I thought it should be immediate.

**Comment by Alwaysin** [comment]
This issue has reappeared. I'm currently on "Dark" theme but I suspect more themes are impacted.
