### ISSUE TITLE
default styles for <pre> and <code>

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#4689]
Hi,

in Origine there is some styling for `<pre>` and `<code>`, when it is placed in an article
https://github.com/FreshRSS/FreshRSS/blob/8f31827e035686f46546a9c01fe5d48b3eed8a81/p/themes/Origine/origine.css#L801-L823

I would suggest to set a default style to all themes (and not define it just in Origine).

Which style (light or dark background? Mono spaced font?) would you expect?

**Comment by Alkarex** [comment]
Some other themes also have styles for that as well, e.g. Pafat:

![image](https://user-images.githubusercontent.com/1008324/193929911-b23878c2-513e-46e9-ba82-ff2a513c232f.png)

I find it fine
