### ISSUE TITLE
[BUG] Can't distinguish links on mapco theme

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/FreshRSS#4695]
Example:

<img width="281" alt="chrome_2022-10-06_14-25-50" src="https://user-images.githubusercontent.com/7189936/194352482-a69691cf-046c-4d0f-be52-a2097f9f9b54.png">

<img width="283" alt="chrome_2022-10-06_14-26-04" src="https://user-images.githubusercontent.com/7189936/194352534-c62e504a-0099-4a8d-99c5-86bd966b2e40.png">

You just know there's a link there if you hover over it. Maybe a slightly darker blue would do the trick.

But the fact that everything is overrided by blue is a bit disturbing, for example:

<img width="610" alt="chrome_2022-10-06_17-24-14" src="https://user-images.githubusercontent.com/7189936/194353744-3b06d614-bd89-49cf-891b-0eb789617194.png">

You lose information compared to the original with another theme:

<img width="613" alt="chrome_2022-10-06_17-23-36" src="https://user-images.githubusercontent.com/7189936/194353861-4d481bbf-3830-4917-bcee-0d8b99a51741.png">

**Comment by math-GH** [comment]
Does it make sense to have blue font color for the whole article text?

I would purpose to have black text and blue links.

What do you think @patjennings (the creator of Mapco&Ansum)?

**Comment by batchennings** [comment]
I assume this problem occur on the article body, visible after a click on a main list item 

> Does it make sense to have blue font color for the whole article text?
>
> I would purpose to have black text and blue links.

Totally agree @math-GH, and as far as i can see myself, this is the case. I can't reproduce the bug : here's what i've got currently.

<img width="1133" alt="Capture d’écran 2022-10-07 à 22 54 49" src="https://user-images.githubusercontent.com/6574956/194650991-96fa145f-0f64-4592-9c74-ac1cef0406ef.png">


@Alwaysin does this behaviour occur everywher else, or just on some articles ?

**Comment by math-GH** [comment]
@patjennings Are you using Mapco theme? It looks like Origine.

How it looks like with Mapco theme:
![grafik](https://user-images.githubusercontent.com/1645099/194653666-e2076ec7-1e1e-46b7-9c8e-c24127ae8abd.png)

The same feed article like @patjennings 
![grafik](https://user-images.githubusercontent.com/1645099/194654364-e9769f98-7876-4a96-8ec3-86109a6bc540.png)

**Comment by batchennings** [comment]
> @patjennings Are you using Mapco theme? It looks like Origine.
You were right @math-GH , was on the wrong theme 😅

**Comment by Alwaysin** [comment]
I think the solution to switch everything to black is not optimal. It sure corrects the problem of the undistinguishable links but see the last two screenshots in the issue, it switched from all blue to all black whereas other themes do not override the red text.
What do you think @math-GH @patjennings ?

**Comment by batchennings** [comment]
@Alwaysin Agree with that. I improved this on a PR that is coming.
