### ISSUE TITLE
Regression: lines jumping

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#4698]
The lines are jumping for me also. It is doing it on Mapco also (not tested all the themes), but only in Chrome and not in Firefox for this theme. For origine and Pafat, it does it on both browsers.

_Originally posted by @Alwaysin in https://github.com/FreshRSS/FreshRSS/issues/4693#issuecomment-1270549717_

**Comment by Alkarex** [comment]
It might be when the notification about new articles is active at the top

**Comment by math-GH** [comment]
It drives me crazy. In Firefox it works fine, in Chrome not. We are talking here about `top: 2px` (works fine in Firefox) and `top: 4px` (works fine in Chromium). So I try now to use the same `bottom` number. See PR.

**Comment by Alkarex** [comment]
@Alwaysin Does this still happen to you now?

**Comment by Alwaysin** [comment]
@Alkarex yes the lines are still jumping. Up-to-date edge branch, doing it on Chrome and Firefox

**Comment by math-GH** [comment]
> @Alkarex yes the lines are still jumping. Up-to-date edge branch, doing it on Chrome and Firefox

which theme?

**Comment by Alwaysin** [comment]
> > @Alkarex yes the lines are still jumping. Up-to-date edge branch, doing it on Chrome and Firefox
> 
> which theme?

On nearly all themes but with discrepancies in the behaviour. I've already described this but for example:
- origine-compact: all lines
- alternative dark: one out of every two lines
- ansum: 4th and 7th lines,...
- blue lagoon: 1st, 3rd, 4th, 6th, 7th, 9th, 10th,...
- ...

**Comment by math-GH** [comment]
could you please check:
1) does it jump, when no article is expanded?
2) does it jump, when 1 article is expanded?

**Comment by Alwaysin** [comment]
On origine-compact at least, the fact that an article is expanded as no effect on the jumping.

**Comment by math-GH** [comment]
> On origine-compact at least, the fact that an article is expanded as no effect on the jumping.

cannot reproduce it.

Lines jumps for me only, when a article is expanded. (tested with Chromium, Origine&Origine compact, lines below the expanded article jumps).
And I have no clue why.

**Comment by Alwaysin** [comment]
Please install a brand new FreshRSS, some specific configuration might be at play here. On a brand new install I still have the problem, tested on origine and origine-compact on this video:

https://user-images.githubusercontent.com/7189936/197863561-39f34362-060c-4775-8554-6c1bad77ec46.mp4

**Comment by math-GH** [comment]
Do you use Windows 10? Do you have a 100% or 150% zoom by default?

**Comment by Alwaysin** [comment]
Windows 11, 150% zoom whch is the default and recommended settings.

Just tried 100% zoom and indeed it loks like lines are not jumping anymore... d'oh!

**Comment by Alkarex** [comment]
At 100%, Firefox, Windows 10, the following themes have lines jumping for me (without having to open any article): Ansum, Blue Lagoon, Mapco, Nord theme, Screwdriver
