### ISSUE TITLE
[Question] XPath scrapping: can you choose the date format?

### ISSUE THREAD

**Issue by axeleroy** [FreshRSS/FreshRSS#4701]
Hello,

When using the XPath scrapping feature, there does not seem to have a way to set the date format, resulting in incorrectly parsed dates: in my case, the date of articles is formatted as `dd/MM/YY` but is parsed as `MM/dd/YY`.

So my question is: is there a way to set the date format used by `strtotime()`?

**Comment by math-GH** [comment]
Right now it is not possible to set the format

**Comment by Alkarex** [comment]
Ref https://github.com/FreshRSS/FreshRSS/pull/4220
It is very easy to add a parameter to support the same formats than https://php.net/datetime.createfromformat
However, when it comes to text dates, I do not believe it supports anything else than English

**Comment by axeleroy** [comment]
Well, in my case the issue comes from a British website, I believe only
north-americans use the MM/d/YY format

**Comment by Alkarex** [comment]
Quick patch, not tested https://github.com/FreshRSS/FreshRSS/pull/4703
Could you give it a try?

**Comment by axeleroy** [comment]
I just tried your patch, it works perfectly!
![image](https://user-images.githubusercontent.com/3141536/194759794-9574c516-a4c2-444c-8b1f-1193fe4731c5.png)
![image](https://user-images.githubusercontent.com/3141536/194759785-c16df443-7e1d-4cd0-a291-ad7ac76c00e6.png)

**Comment by Alkarex** [comment]
Excellent :-) Thanks for the feedback!
