### ISSUE TITLE
OPML import of some proprietary attributes doesn't work

### ISSUE THREAD

**Issue by mrnoname1000** [FreshRSS/FreshRSS#4704]
When importing an OPML file with xpath selectors for website scraping or css selectors for element deletion, the values in FreshRSS are replaced with the string "Array". Exporting works fine the first time, but exporting again results in those fields missing from the OPML output.
I can only get it to happen with categories other than Uncategorized while testing but when I first noticed it, feeds with or without categories all had the same issue.
[Example OPML](https://0x0.st/ot8D.opml.xml)

**Comment by Alkarex** [comment]
Should be fixed with https://github.com/FreshRSS/FreshRSS/pull/4708
Would you be able to test?

**Comment by mrnoname1000** [comment]
Can confirm #4708 fixes the issue.
