### ISSUE TITLE
[BUG] Encoding CSS filter

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#4705]
Regression #4501

My input: `footer[data-area="footer"]`.
After saving:
![grafik](https://user-images.githubusercontent.com/1645099/194728328-0dd21fd6-b05e-4ced-9b9e-a338f7f64c25.png)

**Environment information (please complete the following information):**
- FreshRSS version: edge branch

**Comment by Alkarex** [comment]
Fixed by https://github.com/FreshRSS/FreshRSS/pull/4707

**Comment by Alkarex** [comment]
@math-GH Could you please double-check that is works for you?

**Comment by math-GH** [comment]
> @math-GH Could you please double-check that is works for you?

it works fine for me
