### ISSUE TITLE
[BUG] Opening certain links brings you to a broken page

### ISSUE THREAD

**Issue by mrnoname1000** [FreshRSS/FreshRSS#4726]
**Describe the bug**
Sometimes when opening links to manage feeds/categories you will be brought to a broken page with limited content.
This happens in two places I've found:
1. When opening author links on feeds that have been loaded in, e.g. https://freshrss.example.org/i/?a=normal&get=f_340&state=3&rid=****&next=1663357740187152&ajax=1&search=author%3A%22jwz%22
2. When opening the manage link for a category in a new tab, e.g. https://freshrss.example.org/i/?c=subscription&a=category&id=1

**To Reproduce**
- Author links:
1. Open a feed that has more articles than fit on the page
3. Scroll down to load more articles
4. Click an author link in one of the loaded articles
- Category links:
1. Go to the Manage Subscriptions page
2. Right click the gear to manage a category and open in a new tab

**Expected behavior**
- Author links:
A search page should be loaded for the author's name
- Category links:
A new tab should be opened with either the Manage Category sliding window attached to the side or taking up the body of the page

**Screenshots**
![screenshot 2022-10-13 17:21:40 cropped](https://user-images.githubusercontent.com/8191535/195723400-5e575f90-621b-4d24-ac79-9c837cb4ec07.png)
![screenshot 2022-10-13 17:21:54 cropped](https://user-images.githubusercontent.com/8191535/195723420-6e9e019c-12df-4878-8c60-2ca9b2d8ce65.png)

**Environment information (please complete the following information):**
- Device: ThinkPad A485
- OS: Void Linux
- Browser: Firefox 104.0.2
- FreshRSS version: 1.20.0
- Database version: Postgres 13+225 (from Debian 11.5)
- PHP version: PHP 7.4.30
- Installation type: My own VPS running Debian 11.5, no Docker container

**Additional context**

**Comment by aledeg** [comment]
I've experienced the same bug. I found out how to reproduce it.
The problem is in the `&ajax=1` part of the URL.
It happens when one clicks on the author link on articles loaded with AJAX.
Without said section, the URL is working properly.

I think we should always filter the `&ajax=1` part of the URL.

**Comment by aledeg** [comment]
I've just noticed that you mentioned something about the categories. It's related to #4727.
I think we should work on that in the other issue.
