### ISSUE TITLE
[BUG] Adding new feeds no longer redirects to feed options

### ISSUE THREAD

**Issue by mrnoname1000** [FreshRSS/FreshRSS#4727]
**Describe the bug**
In 1.19, when adding a new feed, FreshRSS would redirect to the settings page for that feed. 1.20.0 seems to have removed that feature and redirects to the Subscription management page. I find this annoying, as I like to configure my feeds after adding them (e.g. renaming, changing visibility, clicking "Filter" to bring me to the articles).

**To Reproduce**
1. Add a feed
2. You will be redirected to the Subscription management page

**Expected behavior**
After adding a feed, FreshRSS should redirect to the settings page for the new feed

**Environment information (please complete the following information):**
Device: ThinkPad A485
OS: Void Linux
Browser: Firefox 104.0.2
FreshRSS version: 1.20.0
Database version: Postgres 13+225 (from Debian 11.5)
PHP version: PHP 7.4.30
Installation type: My own VPS running Debian 11.5, no Docker container

**Comment by Frenzie** [comment]
Strange, I thought I'd seen something a few weeks ago saying that had been fixed?

**Comment by Alkarex** [comment]
I can also reproduce several problems of this type with the new dynamic menu to the right

**Comment by mrnoname1000** [comment]
Actually, just tested edge and in the case I tested it does seem to redirect to the settings menu, albeit taking up the whole body instead of being attached to the right.

**Comment by aledeg** [comment]
The problem at hand is 2 folds:

1. http://localhost:8080/i/?c=subscription&a=feed&id=236 is the URL used after adding a feed. This shows a standalone feed configuration. This configuration cannot be reach through a menu item. It takes the whole width of the panel (no slider).
2. http://localhost:8080/i/?c=subscription&id=236 was the URL used after adding a feed. This URL is not working anymore. The `id` part of the URL has no effect. The slider does not appear.

**Comment by aledeg** [comment]
Item `#1` was introduced by #4631. At the moment, I cannot find where the problem is with item `#2`. I think if we fix what is the root cause of item `#2`, we could revert #4631.
