### ISSUE TITLE
unique id is maybe not unique?

### ISSUE THREAD

**Issue by Emporea** [FreshRSS/FreshRSS#4758]
I stumbled over the postgresql database and was wondering why the column "id" (which should be unique) uses a microsecond based epoch bigint.

I have a lot of entrys that are just one microsecond away (considering i am not mistaken and we are actually talking about epoch)

Here some ID's of the database.
```
1666305625858214
                                   +2µs
1666305625858216
                                   +1µs
1666305625858217
                                   +1µs
1666305625858218
```

What happens if a new entry is added in the same microsecond? Will it get abonded?
Did I miss out on some RSS items?

Is there somehow guaranteed that these "id's" are unique?

**Comment by Alkarex** [comment]
No risk of duplicate;

https://github.com/FreshRSS/FreshRSS/blob/1f4e347cae51667e7cf5772aef55d274a39c8023/app/SQL/install.sql.pgsql.php#L38-L39

**Comment by Emporea** [comment]
wow that was a quick answer. thanks.
So will it add +1 or something if its not unique because its declared as primary key?

**Comment by Alkarex** [comment]
The way it works is that when the is a batch of new entries to add, for instance during a full refresh of multiple feeds, the new articles are first stored in a temporary table, then they are sorted by declared date, and then they are inserted in the main table of entries.

Here is the logic for PostgreSQL, where you can see the +1 in the form of `rank + row_number()`:

https://github.com/FreshRSS/FreshRSS/blob/1f4e347cae51667e7cf5772aef55d274a39c8023/app/Models/EntryDAOPGSQL.php#L43-L61

By the way, there is a TODO there, so patch welcome ;-)

**Comment by Emporea** [comment]
Okey thanks so far.
I want to use freshrss to archive feeds and do some research on them later. Had to make sure they are unique.

I might have a look into the TODO.

**Comment by Emporea** [comment]
Closed.

**Comment by Emporea** [comment]
Got another question not worth opening another issue i think.
I tested the same setup with mariadb just out of curiosity, but the "content" column is now called "content_bin" and is a byte object. Why? 

I dont even know yet how to decode it. Doesnt work with utf-8.

Here an example.

`b'6\x00\x00\x00x\x9csT\xc8K-W\x08\xc9/\xaaT\xc8IMLI-RH\xccKQ\x08\xf0U(\xcf\xcc\xc9QHJUH\xce\xc8/N\xcdSH\xaaT0\xb2P\xf0O.\xc9OJ-\xd2\x03\x00\xf3\x96\x12\x17'
`

This content should be 
```

The search for a new Conservative Party leader is under way, following the resignation of Liz Truss as prime minister.

Her replacement will become the fifth Tory prime minister in six years.
```

I picked the newsitem with the shortest content in length. Has no intention to bash against britian ^^


Edit:
I dont understand why its called "content_bin" in mysql and "content" (also plain text, not some weird byte object) in sqlite and pgsql.
https://github.com/FreshRSS/FreshRSS/blob/1f4e347cae51667e7cf5772aef55d274a39c8023/app/Models/EntryDAO.php#L52

**Comment by Alkarex** [comment]
`content_bin` is used when the application compresses the content. At the moment, it is only used with MySQL. It comes from before there were good native support for compression in MySQL. We should make a new model for MySQL / MariaDB to take better advantage of some of the new features.
