### ISSUE TITLE
[GReader] mark-all-as-read

### ISSUE THREAD

**Issue by jangernert** [FreshRSS/FreshRSS#4762]
I'm trying to mark streams as read via the greader API. No matter what I do the API call returns `OK` but nothing is marked as read afterwards. The FreshRSS instance isn't mine. So I have no access to the server logs or anything.

I tried tons of combinations, but this is one CURL example:

```
curl --request POST \
  --url 'https://$URL/api/greader.php/reader/api/0/mark-all-as-read?s=feed%2F1&T=ea32c2ca06d35c73ffcb7f4633af15b1138827beZZZZZZZZZZZZZZZZZ' \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --header 'authorization: GoogleLogin auth=demo/ea32c2ca06d35c73ffcb7f4633af15b1138827be'
```

What I also don't understand is the `ts` parameter. It should be the timestamp of the newest article, but the code variable name suggests its the newest article id. But article ids sometimes have the form of timestamp in usec and sometimes they look like this `tag:google.com,2005:reader/item/0005e959d9fd1e74`.

Any suggestion what I am doing wrong here?

- FreshRSS version: 1.19.2 
- Database version: ?
- PHP version: ?
- Installation type: ?

**Comment by Alkarex** [comment]
Hello,
Quick answer already, and I will be back later.

Here is a bit of documentation:

* https://feedhq.readthedocs.io/en/latest/api/reference.html#mark-all-as-read
* https://www.inoreader.com/developers/mark-all-as-read
* https://github.com/theoldreader/api#marking-all-as-read
* https://github.com/bazqux/bazqux-api#marking-all-as-read

https://github.com/FreshRSS/FreshRSS/blob/e96b6266b592681e2c19d892d313779c96a7302a/p/api/greader.php#L1105-L1113

https://github.com/FreshRSS/FreshRSS/blob/e96b6266b592681e2c19d892d313779c96a7302a/p/api/greader.php#L877-L901

**Comment by jangernert** [comment]
@Alkarex thanks. I already took a look at the code you posted and still can't figure it out. Marking feeds/categories as read works fine on inoreader with almost the same code (with the differences being auth).

**Comment by jangernert** [comment]
I set up a minimal instance locally and tried (1.20.0):

```
curl --request POST \
  --url 'http://localhost:8080/api/greader.php/reader/api/0/mark-all-as-read?T=99a55bd7f894d0a2203f4368f0c86ef3659f7c5bZZZZZZZZZZZZZZZZZ&s=feed%2F1' \
  --header 'authorization: GoogleLogin auth=demo/99a55bd7f894d0a2203f4368f0c86ef3659f7c5b'
```

Apparently the parameter `s` could not be found:

```
freshrss    | [Sat Oct 22 19:34:14.589696 2022] [php7:notice] [pid 21] [client 10.89.0.1:55204] PHP Notice:  Undefined index: s in /var/www/FreshRSS/p/api/greader.php on line 1108
freshrss    | 10.89.0.1 - - [22/Oct/2022:19:34:14 +0200] "POST /api/greader.php/reader/api/0/mark-all-as-read?T=99a55bd7f894d0a2203f4368f0c86ef3659f7c5bZZZZZZZZZZZZZZZZZ&s=feed%2F1 HTTP/1.1" 200 2 "-" "insomnia/2022.4.2"
```

As far as I can tell it is clearly set though.

**Comment by jangernert** [comment]
Got it.

For future readers - a combination of things need to be in place:
- `content-type` needs to be `application/x-www-form-urlencoded`
- authorization header same as other api calls
- form parameter T aka post token can be omitted due to [workarounds](https://github.com/FreshRSS/FreshRSS/blob/e96b6266b592681e2c19d892d313779c96a7302a/p/api/greader.php#L226) for other clients
- and `s` aka streamId needs to sent as part of forms instead of query

**Comment by Alkarex** [comment]
Please check https://github.com/FreshRSS/FreshRSS/pull/4763
