### ISSUE TITLE
[Question] - Dynamic OPML

### ISSUE THREAD

**Issue by stanthewizzard** [FreshRSS/FreshRSS#4765]
Hello

I'm a bit lost with dynamic OPML.
Could I use DOPML with feedly (for ex) and have FreshRSS sync with it ?

Thanks for help

**Comment by Alkarex** [comment]
FreshRSS supports continuously exporting and importing OPML (making it dynamic), in a similar way than an RSS/ATOM feed, meaning that the side exporting it must make it available as an HTTP resource with an URL.

For your scenario to work, the other side needs also to support dynamic OPML. Have you seen anything of this type in Feedly?

Note that FreshRSS also supports exporting and importing RSS/ATOM, for instance to re-export a feed, category, user label...
