### ISSUE TITLE
[BUG] [error] 7052#7052: *1 upstream sent invalid header: "HTTP\x20..." while reading response header from upstream

### ISSUE THREAD

**Issue by Richard-Rogalski** [FreshRSS/FreshRSS#4766]
**Describe the bug**
My freshrss installation worked yesterday. I rebooted my machine, believe to have started all needed services, and I get a 502 error in nginx. Yesterday I had this, but it was because I hadn't set up cgi and it couldn't find the socket. Setting that up fixed it. However, I am seeing a very different error today:
```
2022/10/23 10:33:02 [error] 7052#7052: *1 upstream sent invalid header: "HTTP\x20..." while reading response header from upstream, client: 192.168.1.1, server: freshrss.my.domain, request: "GET /i/?rid=63555cde8a57b HTTP/1.1", upstream: "fastcgi://unix:/var/run/cgi-php.socket-1:", host: "freshrss.my.domain"
```
Will attach my nginx config at the bottom.

**To Reproduce**
Start nginx
Started `FastCGI application php ...spawn-fcgi`
Try to use freshrss in my browser

**Environment information (please complete the following information):**
- Device: [***SPARC64*** T4-2 server]
- OS: [Gentoo unstable]
- Browser: [Firefox 105.0]
- FreshRSS version: [1.20.0]
- Database version: [postgres 14.5]
- PHP version:
```
sparcy ~ # php --version
PHP 7.4.30 (cli) (built: Sep  7 2022 16:19:33) ( ZTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.30, Copyright (c), by Zend Technologies
sparcy ~ # php-cgi --version
PHP 8.1.11 (cgi-fcgi) (built: Oct 21 2022 22:35:51)
Copyright (c) The PHP Group
Zend Engine v4.1.11, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.11, Copyright (c), by Zend Technologies
sparcy ~ # php-fpm --version
PHP 7.4.30 (fpm-fcgi) (built: Sep  7 2022 16:27:17)
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.30, Copyright (c), by Zend Technologies
```
Just realized the above ^ . Could this be the problem?
- Installation type: [no containers]

**Additional context** nginx config
```
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name freshrss.my.domain;

    #access_log /var/log/nginx/rss.example.com_log main;
    error_log  /var/log/nginx/rss.rrogal.ski_log warn;

    ssl_certificate /etc/letsencrypt/live/rrogal.ski/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/rrogal.ski/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # the folder p of your FreshRSS installation
    root /usr/share/webapps/freshrss/1.20.0/htdocs/p;

    index index.php index.html index.htm;

    # php files handling
    # this regex is mandatory because of the API
    location ~ ^.+?\.php(/.*)?$ {
        fastcgi_pass unix:/var/run/cgi-php.socket-1;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        # By default, the variable PATH_INFO is not set under PHP-FPM
        # But FreshRSS API greader.php need it. If you have a “Bad Request” error, double check this var!
        fastcgi_param PATH_INFO $fastcgi_path_info;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location / {
        try_files $uri $uri/ index.php;
    }
}
```

**Comment by Richard-Rogalski** [comment]
The magic of ✨ <sup>clearing cookies</sup> ✨

**Comment by Richard-Rogalski** [comment]
Nevermind. The issue happens when logging into my account. Did I bork my account somehow? Maybe it rebooted during an operation?

**Comment by Alkarex** [comment]
I believe this is a regression due to https://github.com/FreshRSS/FreshRSS/pull/4654
More precisely this line:

https://github.com/FreshRSS/FreshRSS/pull/4654/files#diff-49280171b6e7964e21a0270427e56eacb47b8ac562593a01ad4bc74b49f840c7R163

Could you have a look if you can @aledeg ?

**Comment by Alkarex** [comment]
@Richard-Rogalski Could it be that you are using version 1.20.1-dev of FreshRSS (which is good :-)) and not 1.20.0?

**Comment by aledeg** [comment]
@Richard-Rogalski could you check #4778 and see if this fixed it.

**Comment by Richard-Rogalski** [comment]
I backported #4778 to 1.20.0, did not work. Trying the dev version now :)

**Comment by Alkarex** [comment]
@Richard-Rogalski Let us know when you have tested

**Comment by t0stiman** [comment]
Did you manage to solve this issue? I'm running into it on version 1.21.0

**Comment by Richard-Rogalski** [comment]
I moved machines, new machine was 1.21 and i exported + reimported my postgres. I suppose you can try that? Sorry, not much help

**Comment by lllvvv** [comment]
I'm still seeing this with 1.21.0, nginx 1.24.0, php-fpm 8.2.7 and postgresql 14.6. Any clue on what's happening or what could fix it?

**Comment by missblit** [comment]
FWIW I got this error message after upgrading Debian. My best guess is my Debian upgrade inadvertently uninstalled sqlite3.

Things fixed themselves after I made sure all dependencies were installed, and regenerated my user (the existing sqlite database file worked fine, so it was nothing wrong with that, I just had to recreate my user for some reason and then plug it back in)

I think the only way to debug this deeper would be to dump HTTP responses to figure out what the heck nginx didn't like about the... presumably some sort of error page? I'm not sure that space is supposed to be there after "HTTP" (normally it'd be "HTTP/1.1" or something) so maybe something low level messed it up. I tried to figure out how to do that but it's probably tricky when everything goes over a FastCGI socket.

**Comment by NaeiKinDus** [comment]
I had the same issue and found that the issue is an invalid HTTP header called by the Minz lib.
To fix it you can edit `lib/Minz/FrontController.php` this way:
```
diff --git a/lib/Minz/FrontController.php b/lib/Minz/FrontController.php
index a5f73b59..e6fbc154 100644
--- a/lib/Minz/FrontController.php
+++ b/lib/Minz/FrontController.php
@@ -82,7 +82,7 @@ class Minz_FrontController {
         * Kills the programme
         */
        public static function killApp($txt = '') {
-               header('HTTP 1.1 500 Internal Server Error', true, 500);
+               header('HTTP/1.1 500 Internal Server Error', true, 500);
                if (function_exists('errorMessageInfo')) {
                        //If the application has defined a custom error message function
                        die(errorMessageInfo('Application problem', $txt));
```

It seems to happen every time the app encounters an issue and has to print a custom HTTP 500 error (in my case, a downed DB).
