### ISSUE TITLE
Pafat regression

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#4776]
The Pafat theme has become much more compact and the number of articles for each category are not vertically centred anymore

1.20.0
![image](https://user-images.githubusercontent.com/1008324/197887482-2bff4fea-d605-4664-af0d-e1e4258379c3.png)

Edge
![image](https://user-images.githubusercontent.com/1008324/197891116-80de1c0d-e35b-49bc-b967-f503dc45196f.png)

_Originally posted by @Alkarex in https://github.com/FreshRSS/FreshRSS/issues/4775#issuecomment-1291190837_

**Comment by math-GH** [comment]
need to wait for merging this PR #4782 to check this issue

**Comment by Alkarex** [comment]
It is fine again.

Minor thing: the distance between the star and the name of the feed has become a bit short and asymmetric:

![image](https://user-images.githubusercontent.com/1008324/198851296-a39ce7f4-ff6d-46a9-b019-e54be1209b74.png)
