### ISSUE TITLE
[BUG] check if (data) directory is writable fails on NFS

### ISSUE THREAD

**Issue by nwhirschfeld** [FreshRSS/FreshRSS#4779]
After installing FreshRSS in my environment I had several problems with features blocked due to "missing write permissions" of my __data__ directory. This happened whenever my data directory was located on a mounted __NFS__ share. The problem occured in several places of the application:

- during the initial setup using the web interface
- in the _"Installation check"_ view
- when calling _"app/actualize_script.php"_ 

It is possible, that other parts of the application and other checked directories are also affected.

**To Reproduce**
1. install FreshRSS
2. use a NFS mount for the data directory
3. try to open  _"Installation check"_ or to run  _"app/actualize_script.php"_ 

**Expected behavior**
If the permissions are set correctly and the application is able to write in the data directory the check should not fail.

**Environment information (please complete the following information):**
- Host-OS: CentOS Stream 8
- FreshRSS version: freshrss/freshrss:edge (0c13c07b9581)
- NFS-Server: Synology

**Root cause analysis and possible solution**
I was able to track the problem down to the PHP function _is_writable_, which is known not to work on NFS shares. Nextcloud had a similar problem a few years ago [ Php v7 filesystem check bug with nfs v3 mount from synology #7124 ](https://github.com/nextcloud/server/issues/7124).

They solved the problem by trying to write an actial file, if _is_writable_ fails. [Commit with the workaround in Nextcloud](https://github.com/nextcloud/server/commit/ff4dc3b66b03c7153c26b5313a639bbd114dfb46)

Based on that I already tested to solve the problem using this function:

```php
// workaround, as is_writable does not work on NFS shares
function checkWritable($path) {
	if (!is_writable($path)){
		$testFile = sprintf('%s/%s.tmp', $path, uniqid('data_dir_writability_test_'));
		$handle = fopen($testFile, 'w');
		if (!$handle || fwrite($handle, 'Test write operation') === FALSE) {
			return false;
		} else {
			fclose($handle);
			unlink($testFile);
		}
	}
	return true;
}
```
and then replaced _is_writable()_ with _checkWritable()_ in various places, what worked fine for me.

As I'm not a good PHP developer, I have not created a pull request yet. 

If you say that bug should be solved, give me an advice in which file the wrapped function should live (I used _lib/lib_install.php_ during my tests) and if replacing all occurrences of _is_writable()_, even if I had no problems with the part of the code so far, seems to be a good idea, I'm happy to provide the pull request soon.

**Comment by Alkarex** [comment]
Is it also a problem when checking a write access on a file, or it is only a problem for directories?

Example for a file:

https://github.com/FreshRSS/FreshRSS/blob/4ec602e8e3e4a1a9410ffcf0730cddf67b5f27f0/app/install.php#L308

**Comment by Alkarex** [comment]
If needed, for write access on a file, I think we can just change `is_writable()` by `touch()`

**Comment by nwhirschfeld** [comment]
It seems like file access is checked correctly:

```shell
$ docker exec -u www-data freshrss_frontend php -r 'echo is_writable("/var/www/FreshRSS/data/config.php")? "WRITEABLE\n":"NOT_WRITEABLE\n";'
WRITEABLE
$ docker exec -u www-data freshrss_frontend php -r 'echo is_writable("/var/www/FreshRSS/data/")? "WRITEABLE\n":"NOT_WRITEABLE\n";'
NOT_WRITEABLE
$
```

**Comment by Alkarex** [comment]
Please test this patch https://github.com/FreshRSS/FreshRSS/pull/4780

**Comment by nwhirschfeld** [comment]
Wow, that was fast!

I haven't tested it so far but it looks, as it should work in most (real world) cases but as you just check a single existing file in every directory, only the permissions for that one file is checked, not the permission for the folder.

so with the following existing files
```
root@e290201c7230:/var/www/FreshRSS/data# ls -lah demo*
-rw-r--r--. 1 root     root     0 Oct 27 00:10 demotest
-rw-r--r--. 1 www-data www-data 0 Oct 27 00:17 demotoast
```

your solution using touch will do something like that:

```
$ docker exec -u www-data freshrss_frontend php -r 'echo touch("/var/www/FreshRSS/data/demotest")? "TOUCHABLE\n":"NOT_TOUCHABLE\n";'
PHP Warning:  touch(): Utime failed: Permission denied in Command line code on line 1
NOT_TOUCHABLE
$ docker exec -u www-data freshrss_frontend php -r 'echo touch("/var/www/FreshRSS/data/demotoast")? "TOUCHABLE\n":"NOT_TOUCHABLE\n";'
TOUCHABLE
```

While as long as a new file is created touch should work.

**Comment by nwhirschfeld** [comment]
maybe something like this is more precise:

```php
// workaround, as is_writable does not work on NFS shares
function checkWritable($path) {
	if (!is_writable($path)){ 
		// as is_writable seems to work for files even on NFS shares we can be sure this is a folder
		$testFile = sprintf('%s/%s.tmp', $path, uniqid('data_dir_writability_test_')); //unique named test file
		if (!touch($testFile)) {
			return false;
		} else {
			// cleanup if touch was successful
			unlink($testFile);
		}
	}
	return true;
}
```

**Comment by Alkarex** [comment]
Yes, but we were not testing all cases anyway, for instance not recursively (which I think would be overkill and wasting IO).
Those tests are mostly hints and not guarantees that it will work (for instance if there is not enough disk space).
So I would rather keep it simple.
