### ISSUE TITLE
[BUG] SSL Security toggle has no apparent effect on XPath feed

### ISSUE THREAD

**Issue by danburd** [FreshRSS/FreshRSS#4781]
**Describe the bug**
FreshRSS won't use XPath to scrape a website that has SSL issues, regardless of whether the "Verify SSL Security" setting is on or off.

**To Reproduce**
1. Set up an XPath feed using the following settings:

![image](https://user-images.githubusercontent.com/4601223/198276872-df3d31ae-5f8f-460d-874d-8bacea3f28e2.png)

![image](https://user-images.githubusercontent.com/4601223/198276993-f247af2e-cc21-4530-8890-9ed22d7824a6.png)

![image](https://user-images.githubusercontent.com/4601223/198277136-e2a84c07-486b-4c0a-b4ae-0237993650b5.png)

- Finding news items:
    - ```//div[contains(@class,'FeedCard')]```
- Item title:
    - ```descendant::h2```
- Item content:
    - ```descendant::p```
- Item link:
    - ```descendant::a/@href```
- Item author:
    - ```descendant::span[contains(@class,'bylines')]```
- Item date:
    - ```descendant::span/@data-source```

2. Get the error: "Blast! This feed has encountered a problem. Please verify that it is always reachable then update it."
3. Run the command ```curl -v https://apnews.com/hub/world-news``` to verify that there is an SSL error on the website.
4. Run the command ```curl -v -k https://apnews.com/hub/world-news``` to verify that using cURL to ignore the SSL error scrapes the website successfully.

**Expected behavior**
FreshRSS would scrape the website normally once the "Verify SSL Security" toggle was turned off.

**Environment information (please complete the following information):**
- Device: Intel NUC
- OS: Fedora 36
- Browser: N/A
- FreshRSS version: 1.20.0 
- Database version: Unknown (Docker image)
- PHP version: Unknown (Docker image)
- Installation type: Docker image

**Additional context**
This "feed" worked as recently as 24 hours ago, presumably because the website's SSL settings were correctly set up at that time, though I hadn't bothered to test cURL until it stopped working about 12 hours ago.

**Comment by danburd** [comment]
**Update**: The SSL settings on this website have apparently resolved for the time being, but I would guess that a user could still verify this bug if they can find another page to test this on.

**Comment by Alkarex** [comment]
Could you please try our current edge version?
Should be fixed with https://github.com/FreshRSS/FreshRSS/pull/4759

**Comment by danburd** [comment]
I'm on Docker and not sufficiently knowledgeable or capable to upgrade to an edge version. Sorry. ☹️

But if you believe you fixed it, then I believe that it's fixed too. 🙂 Thank you!

**Comment by Alkarex** [comment]
@danburd If you are using our Docker image `freshrss/freshrss` or `freshrss/freshrss:latest` or `freshrss/freshrss:1.20.0`, you can just change it to `freshrss/freshrss:edge`
