### ISSUE TITLE
CSS Filtering on RSS-Feeds

### ISSUE THREAD

**Issue by Tone866** [FreshRSS/FreshRSS#4784]
I want to remove certain css-elements from the feed.
I've noticed there is already an feature for exactly that, but for my understanding it only works if I parse the website and not for rss-feeds.

This is the feed:
[http://stadt-bremerhaven.de/feed](http://stadt-bremerhaven.de/feed)
And I want to remove the class `aawp`

I've also tried to manipulate the feed by myself and added `display:none;` to the aawp-class. But this entry will be removed from freshrss. Not exactly sure why.
This is my feed:
`<div class="aawp" style="display:none;">`
and the feed in freshrss:
`<div data-sanitized-class="aawp">`
Maybe there should be an option to not manipulate the feed.

**Comment by aledeg** [comment]
You could use the customCss extension to target those elements and add custom rules on them.

**Comment by Tone866** [comment]
In my opinion this is kinda dirty. There could be class names used by multiple feeds or freshrss itself. 
And in my use case this wouldn't work because I primary read my feeds over reeder and only sync reeder with freshrss.

**Comment by Frenzie** [comment]
When I suggested something like data-sanitized-class I'm pretty sure I suggested including something like frss-[0-9]-class, where [0-9] is the feed id. ;-)

**Comment by Frenzie** [comment]
Oh, but I just remembered I think the reasoning was you can use a selector like `[data-feed="95"][data-sanitized-class="aawp"]` for the the same end result.

**Comment by math-GH** [comment]
I cannot exclude HTML with CSS selectors too, when it is "just" the feed content.

**Comment by Frenzie** [comment]
Yeah, so I'd say go with my original suggestion of `data-sanitized-class="frss-21-aawp"` instead. Or possibly two of them: one original and one prefixed, in which case the prefixed one could potentially just be a `class="frss-21-aawp"`.

**Comment by math-GH** [comment]
I think it is a bug, because the setting does not look like, that it is only valid for scrapped web content.

**Comment by Frenzie** [comment]
Oh, I just realized you were talking about something complete different. I thought you were talking about what you get in, for example, the RSS export. (Sorry, I was very tired from 3 days of like 7:30 to 19:00 in Brussels.) Then you get the data-sanitized-class thing but you can't properly match it.

**Comment by math-GH** [comment]
Are we talking about this?
![grafik](https://user-images.githubusercontent.com/1645099/201544359-f82115dc-998d-4e32-8e3c-eb278d57bdc4.png)

**Comment by Tone866** [comment]
> Are we talking about this?
> ![grafik](https://user-images.githubusercontent.com/1645099/201544359-f82115dc-998d-4e32-8e3c-eb278d57bdc4.png)

Yes

**Comment by Alkarex** [comment]
Implemented https://github.com/FreshRSS/FreshRSS/pull/6786
