### ISSUE TITLE
[BUG] Global view: feeds not alphabetically ordered

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#4790]
**Describe the bug**
The feed order in subscription management (strictly alphabetically ordered)
![grafik](https://user-images.githubusercontent.com/1645099/198854630-135bd167-1dc6-464b-80a6-3c8656155c30.png)

is not used in global view
![grafik](https://user-images.githubusercontent.com/1645099/198854656-e84a5b60-d6ec-4127-8780-8c142bf720b9.png)

**Expected behavior**
Same order

**Environment information (please complete the following information):**
- FreshRSS version: 1.20.1-dev (current edge) + 1.20.1-dev (demo.freshrss.org)

**Comment by aledeg** [comment]
Actually, the order is applied only in the subscription view. The global view and the normal view are not ordered.
