### ISSUE TITLE
[BUG] sub.category.new

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#4808]
`sub.category.new` key does not exist

When using `/i/?c=feed&a=add&url_rss=%s`

And the option to add a new category at the same time does not seem to work (I cannot remember whether it was purposely removed, never worked, or is a regression)

Found when testing https://github.com/FreshRSS/FreshRSS/issues/4767

**Comment by math-GH** [comment]
I can reproduce it.

![grafik](https://user-images.githubusercontent.com/1645099/199827051-ea904e07-591e-4dd9-a0b5-60dddee05fae.png)

But I do not understand why there is an input, that is hidden

**Comment by math-GH** [comment]
`sub.category.new` was removed from the i18n files within #3027

**Comment by math-GH** [comment]
this PR #4808 did not clean completely the i18n String.
