### ISSUE TITLE
[BUG] Characters unauthorized into database name and SSL issue

### ISSUE THREAD

**Issue by pokemaster974** [FreshRSS/FreshRSS#4821]
**Describe the bug**
I've already FressRSS self-hosted into my NAS with a sqlite database.
I'm trying to install it on a no self-hosted setup.

So, I've deployed the docker container via fly.io
I think fly.io could use a sqlite database into the volume linked, but I want to use an external database because in case of migration I couldn't export fly.io volume.
No issue with deployment.

For the database, I've choosen bit.io because it offers 3GB space whereas it's only hundred of MB with other offers.
I saw 2 issues : 
- my db name is `myusername/freshrss` but fresshrss doesn't accept my database name because it contains a `/` (like the issue #937 but it was for an hyphen)

- when trying to use the host `db.bit.io` or `db.bit.io:5432` it gives me connection errors because of ssl. The exact error displayed is
> Blast! Verify your database configuration. : Access to database is denied for `myusername`: SQLSTATE[08006] [7] connection to server at "db.bit.io" (34.160.91.144), port 5432 failed: FATAL: Invalid credentials DETAIL: Password or database name is wrong connection to server at "db.bit.io" (34.160.91.144), port 5432 failed: FATAL: Must use SSL DETAIL: https://docs.bit.io/docs/connecting-via-ssl HINT: Add ?sslmode=require to your connection string

**To Reproduce**
1. Install freshrss
2. Go into configuration page
3. Try to use an external database

**Expected behavior**
I don't know if we can use an external database or if we must use a local database -> I think we can use
I don't know if freshrss is supposed to work on fly.io or service like this -> it seems to work because if I don't use MySQL or PostgreSQL (so if I choose SQLite) I can go into the dashboard :
![image](https://user-images.githubusercontent.com/28442699/200164157-f3a6dbc2-8873-4755-9017-4d85fa6884b0.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/28442699/200164033-42b75606-f72b-4b26-b319-15e987a58950.png)
![image](https://user-images.githubusercontent.com/28442699/200164072-3d970c27-02f9-4562-9c53-4cb5debfec20.png)
![image](https://user-images.githubusercontent.com/28442699/200164097-8e96cc62-0084-498a-8121-c4c89c833467.png)

**Environment information (please complete the following information):**
- Browser: Firefox 106.0.5
- FreshRSS version: 1.20.0
- Database version: PostgreSQL 14.5 on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
- PHP version: PHP 8.0.22

**Additional context**

**Comment by math-GH** [comment]
Is it still an issue?

**Comment by pokemaster974** [comment]
Sorry, can't confirm or not if this issue is still here.
I change the setup since there was no solution when posting the issue.
You can close it if you feel issue was fixed.
