### ISSUE TITLE
[BUG] On folded view click on the article title do not open the article but redirect to the article URL

### ISSUE THREAD

**Issue by 9pr19** [FreshRSS/FreshRSS#4826]
**Describe the bug**
On folded view left click on the article title do not open the article in freshrss but redirect to the article URL in new tab.

**To Reproduce**
Left Click on article title and you get redirected in new tab to the website instead of opening the article inside freshrss.

**Expected behavior**
Open the article in FreshRSS like I’m use to.

**Screenshots**
![image](https://user-images.githubusercontent.com/25961602/200320314-ef42398f-4f2e-466f-bc53-3293ab36e58e.png)

**Environment information (please complete the following information):**
- Device: Computer
- OS: [e.g. Windows 10
- Browser: Firefox 108a1
- FreshRSS version: Sunday 6th november
- Database version: MariaDB
- PHP version: 
- Installation type: linuxserver/freshrss (adapted to use last commit and not last release)

**Additional context**
It seems that in private mode I do not have the issue.

**Comment by Alkarex** [comment]
Hello,
This typically happen when the JavaScript code has not been loaded or has been blocked.
Check your browser logs / developer console / network tools to find out.
Try also with another browser, as it might be a badly configured extension or browser settings.

**Comment by 9pr19** [comment]
@Alkarex ,
Indeed it seems to be working in another browser.

In the one where I have the problem here is the JS log:

![image](https://user-images.githubusercontent.com/25961602/200330396-721c86ce-9bbb-4785-b1ff-cf9f8284457d.png)

Thank you very much for your time.

**Comment by Alkarex** [comment]
Could you please try this patch? https://github.com/FreshRSS/FreshRSS/pull/4827

**Comment by 9pr19** [comment]
> Could you please try this patch? #4827

Will try tonight. Thank you four your faster than light patch.

**Comment by 9pr19** [comment]
@Alkarex 
I confirm this patch solved the problem. 
I tried with and I’m not redirected anymore then removed the patch and redirected again.
Thank you for your very quick fix

**Comment by Alkarex** [comment]
Thanks for the feedback 👍🏻
