### ISSUE TITLE
[Feature] Hide feed title in normal view

### ISSUE THREAD

**Issue by squromiv** [FreshRSS/FreshRSS#4838]
I need to hide repeated feed titles in order to save reading space. I guess it could be made by Custom CSS extension, but not sure and have zero coding knowledge. So how to achieve this?
![1](https://user-images.githubusercontent.com/15985877/200935591-1ab9d595-16bb-4e54-8d44-2b909a6d8e59.jpg)

**Comment by Alkarex** [comment]
You can hide this column with something like:

```css
.flux .item.website {
	display: none;
}
```

We could add a class to make it easier to style only in feed views and not in categories or global views.

**Comment by math-GH** [comment]
I have it also hidden. This code keeps the favicon and hide the text:

```
.flux .item.website {
 width: 3rem;
}

.flux .item.website span {
 display:none;
}
```

**Comment by squromiv** [comment]
> We could add a class to make it easier to style

Not bad. Cause I am not the only person, using this option, as @math-GH has noted.

**Comment by squromiv** [comment]
UPD
How to apply this setting for all users now? CSS extension creates separate configs.

**Comment by math-GH** [comment]
> UPD How to apply this setting for all users now? CSS extension creates separate configs.

right now it is not implemented to have this setting
