### ISSUE TITLE
[BUG] greader API latest Docker Dev Build

### ISSUE THREAD

**Issue by quella** [FreshRSS/FreshRSS#4854]
**Describe the bug**
After installing the latest ARM Docker Dev build 1.21-0-Dev an the previous build, my third-party Reeder application on MacOS and iOS no longer works/syncs to the application.  I do not see anything when I look at the logs for FreshRSS, and the Reeder app does not have any logs I can see.  When I try to sync, it immediately completes the sync as if there is not a connection.   Is there a way test or validate the API that previously worked on the earlier docker builds. With the latest I was able to sync once but viewing in the Reeder Application did not update the application with any changes.  

UPDATE: I changed the API password in the FreshRSS web UI and updated it in the reeder application.  Once I did that, I was able to start a sync as normal.  However, the mark as read and any sync attempts afterwards fail.  I can get the same results if I change the API password again, but the connection seems lost after the first connection.  

**To Reproduce**
Attempting to sync with the gReader API no longer works with Reeder App after latest upgrade to the Docker ARM Dev package

**Expected behavior**
Two way sync and marking as read as previously functioned in earlier builds

**Screenshots**

**Environment information (please complete the following information):**
-Reeder App on both iOS, PadOS and MacOS

**Additional context**
I can try to rebuild the API connection as if new to see if this corrects the problem.  Happy for any other recommendations.

**Comment by quella** [comment]
I did have to update the API password field  under the profile and then all started to sync again.  I had not had to do that with previous upgrades, so just making you aware.  Thanks for all you do!

**Comment by quella** [comment]
So, it seems there is still some issue with the gReader API.  I did update the password in the Profile API and was able to get a sync.  I started to view the feeds on the Reeder App (both Mac and iOS), but the sync in the FreshRSS web GUI does not reflect the mark as read, etc.  After the initial sync, the Reeder application no longer syncs and immediately stops without warnings.  I am currently using the latest ARM Dev Docker  image.  Seems the previous image also had an issue as I tried to update to see if it fixed the problem and it did not.  Happy to give any additional data I can to assist.

**Comment by Alkarex** [comment]
Should be fixed by https://github.com/FreshRSS/FreshRSS/pull/4855

**Comment by quella** [comment]
Awesome.  Just using the Web UI now but will be happy when it is fixed.  :)  Thanks again for the great tool.

**Comment by Alkarex** [comment]
New Docker images pushed. Please try again and let us know @quella

**Comment by Alkarex** [comment]
P.S. Thanks for using the edge images 👍🏻

**Comment by quella** [comment]
All Good with the latest update and connections and sync appear to be working as expected.  Thanks!

**Comment by Zeik0s** [comment]
Affected by the same issue and building it new (as i'm already using armv8) solved it, as @quella already wrote. Thx for creating this issue, less work for me. 😄
