### ISSUE TITLE
Framed articles seem like a bad idea for mobile

### ISSUE THREAD

**Issue by myuki** [FreshRSS/FreshRSS#4864]
I found #4653 and #4663 in v1.20.1 add framed articles for all theme. But it seems like a terrible idea on my OnePlus 9R. It wastes so much display area and make the articles text become narrow.

![Screenshot_2022-11-17-09-25-58-17_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/27203797/202331948-52bd7f13-df5a-42e8-9c35-03353e1675b1.jpg)

**Comment by aledeg** [comment]
@math-GH Could you have a look on that and add some kind of screen size detection to apply such thing?

**Comment by math-GH** [comment]
You can fix this issue with CustomCSS extension:

```
@media (max-width: 840px) {
	.reader .flux .content {
		padding: 1rem;
	}
}
```

**Comment by Alkarex** [comment]
Please test again now that this patch has landed https://github.com/FreshRSS/FreshRSS/pull/4868
