### ISSUE TITLE
[BUG] Theme origin-compact: everything (mainly fonts) is bigger since 1.20.1

### ISSUE THREAD

**Issue by nicofrand** [FreshRSS/FreshRSS#4866]
**Describe the bug**

Since the version 1.20.1 everything is bigger on the origin-compact theme. 
I don't know what exactly but I suspect the root font size is bigger.
I don't have access to 1.20.0 though so I can't compare. I hope you'd know what changed.

**To Reproduce**

Compare 1.20.0 and 1.20.1.

**Expected behavior**

A compact theme with a font size smaller than the current one.

**Screenshots**

![image](https://user-images.githubusercontent.com/3419050/202467306-a740d0f4-bba1-45ca-b99f-6070722406c3.png)

**Environment information (please complete the following information):**
- Browser: Firefox 108 (but also on Chrome)
- FreshRSS version: 1.20.1

**Comment by math-GH** [comment]
Origine Compact theme:
Before (till 1.20.0): 80% of your browser standard font size
Now (1.20.1): 90% of your browser standard font size. It is the default for the most themes.

It is up to you how you defined the browser standard font size. Standard is often 16px.

It is very difficult to maintain themes with smaller font sizes. I had a lot of troubles with "jumping lines" in the last weeks.

There is a general compact mode on my roadmap (see #4794)

**Comment by nicofrand** [comment]
Oh ok, thanks for the information.
I might just use CustomCSS if I can't adapt then!

Great to hear about the general compact mode, nice work!
