### ISSUE TITLE
OPML category is a text field

### ISSUE THREAD

**Issue by Frenzie** [FreshRSS/FreshRSS#4870]
**Describe the bug**
Category is an input

**To Reproduce**
1. Go to add subscription or category

**Expected behavior**
It should be a drop down

**Screenshots**
![image](https://user-images.githubusercontent.com/202757/202704850-a1e3f667-f644-4f15-85ef-22da89204c90.png)

**Environment information (please complete the following information):**
- FreshRSS version: 1.20.0

**Comment by Alkarex** [comment]
That field is for the name of the new category associated to the dynamic OPML, but I can see that the naming of the field could/should be improved

**Comment by math-GH** [comment]
An empty category is needed, isn't it?

**Comment by Alkarex** [comment]
> An empty category is needed, isn't it?

Yes, a new category of that name will be created to host the dynamic OPML

**Comment by math-GH** [comment]
How to proceed here?

**Comment by Frenzie** [comment]
Is a *unique* type of category required or merely an *empty* category?

**Comment by Alkarex** [comment]
A non-existing category name is expected at the moment

**Comment by math-GH** [comment]
What is expected to change here @Frenzie ?

**Comment by Frenzie** [comment]
Primarily the string since it's confusing. Perhaps that could be as simple as something like `Category name for OPML` or `OPML category`. Or maybe the string can stay, but it could have some help text. Just like how the URL says it's dynamic, the category help text could say it's uniquely for OPML.

Ideally you'd also want to reject existing category names before even submitting. At the simplest a dynamic negative lookahead pattern would probably do the trick, though you'd want to set a custom rejection message.

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/7053
