### ISSUE TITLE
How do I turn off article highlighting？

### ISSUE THREAD

**Issue by i-iooi-i** [FreshRSS/FreshRSS#4871]
![动画](https://user-images.githubusercontent.com/1827701/202851895-ef1ab709-005b-4271-8e90-620f22345729.gif)

I don't like this strong contrast flicker very much. Is there any way to turn off this display?
Or you can provide a CSS method 😂
Thanks~ 💕

**Comment by aledeg** [comment]
You can add a custom CSS rule with customCSS extension

**Comment by math-GH** [comment]
#4874 would fix it. Please have a look

**Comment by i-iooi-i** [comment]
> 



> #4874 would fix it. Please have a look

Thanks for your reply. I hope you can add a switch to let the user decide. Just in the dark mode, this high contrast frequent flashing really affects the reading experience.

**Comment by i-iooi-i** [comment]
> You can add a custom CSS rule with customCSS extension

Sorry, I can't write CSS. I just want to feedback this question. 😂

**Comment by math-GH** [comment]
> > You can add a custom CSS rule with customCSS extension
> 
> Sorry, I can't write CSS. I just want to feedback this question. 😂

We can help you.

When you are using CustomCSS extension just add these lines:

```
flux:hover:not(.active) {
background: none;
}
```

(tested on Dark Pink theme, It should solve it for the most themes. Origine/Origine compact needs more lines)

**Comment by math-GH** [comment]
> > 
> 
> > #4874 would fix it. Please have a look
> 
> Thanks for your reply. I hope you can add a switch to let the user decide. Just in the dark mode, this high contrast frequent flashing really affects the reading experience.

I see the actual behaviour as a bad UX, because it does not make sense to change the background for a big area while hovering. It reduces the contrast too.
The PR will fix it in general.

**Comment by Frenzie** [comment]
> I see the actual behaviour as a bad UX

I thought it was a regression? (Which is also bad UX, but still. ;-) )

**Comment by math-GH** [comment]
It is a duplicate from #3982 (also created by @i-iooi-i 😆  ), claimed in V1.18

**Comment by i-iooi-i** [comment]
> It is a duplicate from #3982 (also created by @i-iooi-i 😆 ), claimed in V1.18

Yes, because this question has been bothering me. As an obsessive-compulsive disorder, I have to continue to ask questions one year later. Yes, it's been a whole year, and time is really fast. 🤣🤣🤣
