### ISSUE TITLE
Unable to auto refresh feed

### ISSUE THREAD

**Issue by yumeng426** [FreshRSS/FreshRSS#4876]
Can anyone help me on this? I have the freshrss running fine. I can manually refresh feed by clicking the button in toolbar. But I have trouble setting up auto refresh feed. I followed the guide to call actualize_script.php to refresh, but I have failed requirements. I checked that all my Installation check passed. 

<img width="665" alt="image" src="https://user-images.githubusercontent.com/11802847/202886556-0fd0f3d4-2fc4-4ae1-a5ac-a6af65c2903f.png">

This is the error when calling the script.  
```
root@localhost:~# /var/lib/docker/volumes/root_freshrss_usr/_data/bin/php /var/lib/docker/volumes/root_freshrss/_data/app/actualize_script.php
FreshRSS starting feeds actualization at 2022-11-19T18:08:41+00:00
FreshRSS failed requirements:
• curl
• pdo-sqlite
• dom
• xml
• mbstring
```

**Comment by Frenzie** [comment]
What do you mean by the guide in this context?

**Comment by aledeg** [comment]
I think your problem is because you're calling the refresh script with the PHP CLI and not through the web-server. You have multiple PHP configurations and they are not identical. The PHP configuration used through the web-server meet all the requirements while the PHP configuration used through the CLI does not.

**Comment by yumeng426** [comment]
> guide

[This one](https://freshrss.github.io/FreshRSS/en/admins/08_FeedUpdates.html)

**Comment by yumeng426** [comment]
> I think your problem is because you're calling the refresh script with the PHP CLI and not through the web-server. You have multiple PHP configurations and they are not identical. The PHP configuration used through the web-server meet all the requirements while the PHP configuration used through the CLI does not.

I suspect the same thing. But I cannot figure out where to find the php configuration file. Is this a `.ini` file? I tried to use the same php instead of the one in the system by exposing the `etc` and `usr` from freshrss by 
  ```
volumes: 
    - freshrss:/var/www/FreshRSS
    - freshrss_etc:/etc
    - freshrss_usr:/usr
```
Then I call the php from freshrss  by 
```
/var/lib/docker/volumes/root_freshrss_usr/_data/bin/php /var/lib/docker/volumes/root_freshrss/_data/app/actualize_script.php
```

**Comment by Frenzie** [comment]
For the Docker image you can simply set the `CRON_MIN` environment variable.

**Comment by yumeng426** [comment]
> For the Docker image you can simply set the `CRON_MIN` environment variable.

I do have this set in docker-compose `CRON_MIN = 3,33`, but it never refreshed. Is there any other work need to do to enable it?

**Comment by Frenzie** [comment]
If that's not a typo, note that there should be no spaces in there.

**Comment by yumeng426** [comment]
> If that's not a typo, note that there should be no spaces in there.

I have tried these syntax in environment to get it refreshed. But none of them worked so far. 

```
environment:
      - 'CRON_MIN=3,33'
      - CRON_MIN=3,33
      - CRON_MIN = 3,33
      - CRON_MIN='3,33'
      CRON_MIN: '3,33'
```

**Comment by Frenzie** [comment]
As I said, `- CRON_MIN = 3,33` can't work unless Docker does additional parsing on top of YAML.

All of the others should probably work; you'd have to give it a try. `docker exec container_name /usr/bin/env` will tell you.

Here's the known working sample:
https://github.com/FreshRSS/FreshRSS/blob/9b674e7e9390d19c1a9686710d78164a41ad31d1/Docker/freshrss/docker-compose.yml

**Comment by Alkarex** [comment]
For Docker and docker-compose, see additional documentation: https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md
