### ISSUE TITLE
[Feature] Allow filtering by tags (exact match)

### ISSUE THREAD

**Issue by alex2702** [FreshRSS/FreshRSS#4877]
**Is your feature request related to a problem? Please describe.**
Filtering by a tag (using `#tag`) currently returns all items that are assigned a tag **containing the searched tag**, i.e. even substring matches. In other words, searching for `#tech` will return items with tags `tech`, `technology`, `biotech`, and `nontechnical`.

This behavior limits the usability of tag search. For example, I use tags a lot to mark irrelevant items as read automatically. However, the substring approach causes lots of false positives, marking articles as read that I may actually be interested in.

**Describe the solution you’d like**
This may just be me, but I've always understood tags as "fixed keywords", as in either an item has a tag or it does not. This would mean that searching for `#tech` would only return items that have that precise tag assigned to them.

In addition, a new filter named `intag:` could be introduced that behaves like `#tag` currently does. 

Furthermore, I suggest adding a note explaining the current behavior to the docs.

**Describe alternatives you’ve considered**
Of course, switching around functionality like this would cause problems with existing saved searches, so maybe the old behavior should stay in place and a new filter could add the "exact match" functionality.

**Comment by Alkarex** [comment]
Please try #4882 
Should be tested also with tags containing spaces (coded as `+`) such as `#Robotics+&+AI`

**Comment by alex2702** [comment]
Wow, thanks for the quick reaction and the fix! Sorry, I just got around to testing this, but it looks great. :grinning:

**Comment by Alkarex** [comment]
Thanks for the feedback 👍🏻
