### ISSUE TITLE
Run a PHP security scanner

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#489]
http://rips-scanner.sourceforge.net

Inspired by http://www.crowd42.info/auditer-securite-code-php-ave-rips

**Comment by aledeg** [comment]
The open source version of RIPS is not supported anymore. There is a new tool but it isn't open-source nor free.
See [here](https://www.ripstech.com/next-generation/)

**Comment by math-GH** [comment]
I used to work with Sonarqube in the past. I like it. But I would not call it a Security Scanner. It is a static code analyzer, similar to PHPstan

**Comment by Alkarex** [comment]
Done with GitHub + Snyk
