### ISSUE TITLE
[BUG] Broken link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by hippothomas** [FreshRSS/FreshRSS#4895]
**Describe the bug**

The link for "our coding style recommendations" in CONTRIBUTING.md is broken :

"If you have to write code, please follow [our coding style recommendations](https://freshrss.github.io/FreshRSS/en/developers/01_First_steps.html)."

It should be changed from 
https://freshrss.github.io/FreshRSS/en/developers/01_First_steps.html
to
https://freshrss.github.io/FreshRSS/en/developers/02_First_steps.html

Is this ok if I fix this issue as my first contribution ?

**Comment by Frenzie** [comment]
Go ahead!

**Comment by hippothomas** [comment]
Thanks @Frenzie 

If I find a bug/issue that I can fix, is this better to open an issue first or just send a pull request with the fix ?

**Comment by Frenzie** [comment]
That depends a bit, but generally speaking just describing the issue description in the PR should be fine, preferable even in my eyes.
