### ISSUE TITLE
[BUG] Article summary: part of the next line after the cut off is visible

### ISSUE THREAD

**Issue by struq** [FreshRSS/FreshRSS#4901]
**Describe the bug**
Previously in the list of articles, if summary is enabled, the first two lines of the article content is shown below the title of the article. But after updating to version 1.20.1, now a small part of the third line (seems to be about 1-2 pixels) is also visible below that. Screenshot is attached with the issue marked in red rectangles.

**To Reproduce**
1. Go to 'Configuration-Display', in 'Article icons', enable 'Top line - Summary' 
2. Go back to any feed (or category or 'Main stream') in Normal view
3. See error

**Expected behavior**
Only the first two lines of the article is shown in the summary, not part of the next line.

**Screenshots**
<img width="839" alt="screenshot" src="https://user-images.githubusercontent.com/2097707/204162975-b34f6566-6242-4e12-9ed1-5a5bab3a1876.png">

**Environment information (please complete the following information):**
- Device: Desktop
- OS: macOS 12.6.1 or Linux
- Browser: Firefox 107 or Chrome 107
- FreshRSS version: 1.20.1
- Database & PHP version: built-in version in the official Docker image
- Installation type: Docker

**Additional context**
This seems to be related to #4666. I tried to look at this with Firefox's Page Inspector. It suggests adding a `overflow: hidden` rule, citing https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow. After temporarily adding this in the Inspector, the extra line becomes indeed hidden.

**Comment by math-GH** [comment]
I can confirm. It is very strange..... I thought it will crop all lines
