### ISSUE TITLE
FreshRSS Feeds running on MariaDB will not update automatically, even after setting a cron job

### ISSUE THREAD

**Issue by S0ulf3re** [FreshRSS/FreshRSS#4902]
I have setup FreshRSS on 2 different 512MB droplets to try and diagnose an issue where my feeds won't update unless I manually refresh them, and this issue has affected both of them. Most of my feeds have been imported straight from an OPML file and the "There are no feeds to refresh" error makes it even harder to update my feeds. The "Do not automatically refresh more often than" option is set to 1 hour, and I set up my latest instance 8 hours ago. But im still not seeing new things.

**Comment by Alkarex** [comment]
Did you find a solution to your problem?
