### ISSUE TITLE
[BUG] Some feeds contain articles that are not properly sorted

### ISSUE THREAD

**Issue by cskwrd** [FreshRSS/FreshRSS#4908]
**Describe the bug**
I have a feed that isn't sorting articles correctly as far as I can tell.

**To Reproduce**
1. Add problematic feed: https://www.linuxserver.io/blog.rss
2. Get articles.
3. View articles for feed.
4. Observe most recent article is sorted last if sorting by newest articles first, or sorted first if articles are sorted oldest first.

**Expected behavior**
Newest article is in proper order

**Screenshots**
-

**Environment information (please complete the following information):**
- Device: Laptop
- OS: Fedora 35
- Browser: Firefox 106.0.4
- FreshRSS version: 7.4.26
- Database version: Pretty sure sqlite in docker container
- PHP version: Docker
- Installation type: Docker

**Additional context**
-

**Comment by Alkarex** [comment]
Hello,
I cannot reproduce the problem. The feeds does have some dates `<pubDate>Sat, 01 Oct 2022 11:01:50 +0100</pubDate>`, which all look correct in my FreshRSS:

![image](https://user-images.githubusercontent.com/1008324/204656621-3939fde1-1e98-4b77-af00-b4ef3babc2a0.png)

Maybe a temporary feed bug. Could you try to delete it and add it again?
If there is still a problem, what Docker image are you using more precisely? I just tested with `freshrss/freshrss:edge`

**Comment by cskwrd** [comment]
@Alkarex, delete the whole feed or just the articles?

I am using the container at: `lscr.io/linuxserver/freshrss:latest`

**Comment by Alkarex** [comment]
I meant deleting the whole feed.
Alternatively, to be sure there is no cache problem, you can try with a modification in the URL such as https://www.linuxserver.io/blog.rss?v2

**Comment by cskwrd** [comment]
Deleting the feed and recreating it appears to resolve the issue.

Thank you!
