### ISSUE TITLE
[BUG] Missing part of original website URL available in the ATOM feed

### ISSUE THREAD

**Issue by jaketri** [FreshRSS/FreshRSS#4916]
**Describe the bug**
Part of the URL from the ATOM feed are lost during processing.

**To Reproduce**
1. Go to any Arch AUR package details page - As example I'll use the FreshRSS package page https://aur.archlinux.org/packages/freshrss
2. Copy the "View Changes" URL from the right side of the page. The URL for my package example was https://aur.archlinux.org/cgit/aur.git/log/?h=freshrss
3. Use the URL provided https://aur.archlinux.org/cgit/aur.git/log/?h=freshrss to add a new feed to the local FreshRSS installation 
4. Refresh the feed and open a feed article.
5. Click the 'See the original website' link to see the original web page
6. aurweb page display an error about "Repository seems to be empty" due to URL without the branch identifier &h=...

Here is a concrete example: the URL for the change to update package to freshrss 1.20.1-1 in the ATOM feed is:

https://aur.archlinux.org/cgit/aur.git/commit/?id=135f143e7d8afa09ae8383d50b609ccdb2bb659a&h=freshrss

While the URL provided for accessing the "original website" look like this and is missing the "**&h**" part used to select the git branch:

https://aur.archlinux.org/cgit/aur.git/commit/?id=135f143e7d8afa09ae8383d50b609ccdb2bb659a=freshrss

**Expected behavior**
Expected to see the git commit details when clicking the original website link but see the error page about "Repository seems to be empty" due to malformed URL.

**Environment information (please complete the following information):**
- Docker image from [freshrss/freshrss](https://hub.docker.com/r/freshrss/freshrss)
- FreshRSS version: 1.20.1
- Database version: SQLite

**Comment by Frenzie** [comment]
The feed is broken. That should read `&amp;h=freshrss`.

**Comment by jaketri** [comment]
Sound strange to me for a link href URL to be escaped. It make sense to escape content but not the URL itself. 

`<link rel='alternate' type='text/html' href='https://aur.archlinux.org/cgit/aur.git/commit/?id=135f143e7d8afa09ae8383d50b609ccdb2bb659a&h=freshrss'/>`

**Comment by jaketri** [comment]
I agree that feed in general is broken so I'm closing the issue. 
However, I'm still unsure about the need to escape the URL for a link.

**Comment by Frenzie** [comment]
It's XML. `&somecharacters` is an entity. (Well, actually it's a syntax error because there's no `;` at the end but an unexpected `=`.) To write & in XML or HTML without intending a special meaning, you always have to write `&amp;`. Actually I'm surprised it works at all without needing to use `#force_feed`.

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Faur.archlinux.org%2Fcgit%2Faur.git%2Fcommit%2F%3Fid%3D135f143e7d8afa09ae8383d50b609ccdb2bb659a%26h%3Dfreshrss
