### ISSUE TITLE
[BUG] README 

### ISSUE THREAD

**Issue by money8203** [FreshRSS/FreshRSS#4920]
**Describe the bug**
FreshRSS logo and screenshots are not available on the readme section. Sometimes the alt text appears instead of images and sometimes  it shows blank space.

**To Reproduce**
1. Go to 'README.md'
2. See 'Screenshot'
3. click o alt text '…'

**Expected behavior**
Instead a clear and crystal image should present there. Please assign me this task to complete it .

**Screenshots**
![Screenshot (138)](https://user-images.githubusercontent.com/89864818/205513293-21821203-3b94-4979-8ca7-0df40bc60392.png)
![Screenshot (136)](https://user-images.githubusercontent.com/89864818/205513331-bca47e8c-5f39-4d8f-8db5-c6bf0f043e2b.png)

![Screenshot (137)](https://user-images.githubusercontent.com/89864818/205513303-c5176957-a689-4610-9616-3996665051e1.png)

**Additional context**
Provide me with the screenshots and image logo to be uploaded I will be more than happy to contribute to the readme improvement.

**Comment by math-GH** [comment]
I cannot reproduce it. The images are shown

![grafik](https://user-images.githubusercontent.com/1645099/205734891-0feb989e-5648-4626-84ed-d670bcda0cf9.png)

**Comment by Frenzie** [comment]
My guess would be a temporary GH server or connection issue. Looks like the alt text could maybe be a bit better though. :smile:

**Comment by money8203** [comment]
oh, okay no worries 😂.I just saw so thought of informing
