### ISSUE TITLE
[Feature] support cookies for xpath scraping

### ISSUE THREAD

**Issue by SettingDust** [FreshRSS/FreshRSS#4926]
**Is your feature request related to a problem? Please describe.**
Some website can't access without cookies

**Describe the solution you’d like**
support cookies for xpath scraping

**Comment by Alkarex** [comment]
Hello,
What FreshRSS version are you running?
Could you try our edge branch? This should have been fixed by https://github.com/FreshRSS/FreshRSS/pull/4759

**Comment by SettingDust** [comment]
> Hello,
> What FreshRSS version are you running?
> Could you try our edge branch? This should have been fixed by https://github.com/FreshRSS/FreshRSS/pull/4759

1.20.1
~~It's running in docker that updating with watchtower. And there are some users. So I can't update right now~~
It's seems it is merged in 1.20.1

After looking into the code. It's should be working in the 1.20.1. May caused by the cookie isn't enough for target website. This issue is invalid. Maybe we need debug info for xpath html
