### ISSUE TITLE
Ancien flux

### ISSUE THREAD

**Issue by wilfried18** [FreshRSS/FreshRSS#493]
Décidement avec moi vous avez des soucis 

Depuis quel que jours/semaines , a chaque fois que j'ouvre freshrss , j'ai des vieux acticles , 2011-2012-2013 qui réapparaisse , 
Ce n'est peut-étre pas un soucis , mais je voulais vous en faire part.

**Comment by Alkarex** [comment]
The purge mechanism will be improved as part of https://github.com/FreshRSS/FreshRSS/issues/798#issuecomment-89541445

**Comment by Alkarex** [comment]
@wilfried18 La [branche /dev](https://github.com/FreshRSS/FreshRSS/tree/dev) implémente maintenant un système plus robuste de mise à jour des articles, qui devrait régler ces problèmes.
Commentaires bienvenus, et n'hésitez pas à rouvrir le bug ou en créer un autre au besoin.

**Comment by Alwaysin** [comment]
Je crois que j'ai le même bug... ça ne m'était jamais arrivé avant. J'ai des articles de la journée qui reviennent.

J'attends de voir un peu dans les heures/jours qui suivent comment ça se comporte, j'ouvrirais un nouveau ticket au besoin.

**Comment by Alkarex** [comment]
@Alwaysin Est-ce avec la version /dev < 5 jours ? Si ce sont des articles de la même journée, ce n'est pas le même problème. Vérifier que la nouvelle option _Marquer les articles mis à jour comme non-lus_ n'est pas activée https://github.com/FreshRSS/FreshRSS/issues/798#issuecomment-100643276

**Comment by Alwaysin** [comment]
Ha oui j'avais oublié ça ! C'est cette fameuse option, merci ^^

Je me permets du coup de mettre mon commentaire de l'époque où on en discutait : https://github.com/FreshRSS/FreshRSS/issues/798#issuecomment-88886642
Un petit indicateur pour la mise à jour serait parfait je pense :)

EDIT : Aussi j'aurais bien vu les articles mis à jour tout en haut, limite mis en évidence par rapport aux autres (probablement seulement lorsqu'ils ont été lus, sinon on s'en fiche). Parce que les retrouver tout enfouis parmi d'autres, c'est pas terrible.

**Comment by Alkarex** [comment]
@Alwaysin Ok, je vais essayer de réfléchir pour un indicateur. Bouger les articles ailleurs serait un peu plus problématique (problème de synchronisation en particulier) sans parler des flux qui "mettent à jour" tout le temps, genre lemonde.fr à cause de changements aléatoires (techniques) dans leurs articles. Continuons la conversation dans le bug dédié au besoin https://github.com/FreshRSS/FreshRSS/issues/798
