### ISSUE TITLE
[BUG]Possible phishing detected on user login by Google Websmaster

### ISSUE THREAD

**Issue by leongfuture** [FreshRSS/FreshRSS#4931]
Description
Error message produce by google webmaster
These pages attempt to trick users into doing something dangerous, such as installing unwanted software or revealing personal information. [Learn more](https://support.google.com/webmasters/answer/9044101#phising)
Sample URLs
https://bayu260.com/m/feed
https://bayu260.com/m/feed/
https://bayu260.com/m/feed/p
https://bayu260.com/m/feed/p/
https://bayu260.com/m/feed/p/i/?rid=6391b5fbbfd94
https://bayu260.com/m/feed/p/i/?rid=6391b5ffe2c9a
https://bayu260.com/m/feed/p/i/?rid=6391b6014acd8
https://bayu260.com/m/feed/p/i/?rid=6391b61109759Description
These pages attempt to trick users into doing something dangerous, such as installing unwanted software or revealing personal information. [Learn more](https://support.google.com/webmasters/answer/9044101#phising)
Sample URLs
https://bayu260.com/m/feed
https://bayu260.com/m/feed/
https://bayu260.com/m/feed/p
https://bayu260.com/m/feed/p/
https://bayu260.com/m/feed/p/i/?rid=6391b5fbbfd94
https://bayu260.com/m/feed/p/i/?rid=6391b5ffe2c9a
https://bayu260.com/m/feed/p/i/?rid=6391b6014acd8
https://bayu260.com/m/feed/p/i/?rid=6391b61109759

**Comment by Frenzie** [comment]
Reported the user for spam. Brand new account with this as a profile pic:

<details>
<summary>profile pic</summary>

![image](https://user-images.githubusercontent.com/202757/206540804-7baa8cd5-671c-4a8d-b44d-618cd2caa37b.png)

</details>

**Comment by Rekhyt** [comment]
While the account of the OP may be a spam account, I encounter the same issue. I didn't find anything on my web server, nor will Google give me any specifics as to why the site is detected as malicious / possibly phishing.

I'm running FreshRSS from a Docker container, MySQL running on a separate container, at: https://rss.damage-report.net

Anyone else ever encountered this before?

**Comment by Alkarex** [comment]
@Rekhyt My first comment would be that you could reconsider whether you actually need the public/anonymous mode. Note that the anonymous mode can also be set behind an HTTP password

**Comment by Rekhyt** [comment]
@Alkarex Thank you for the suggestion. Since I was using it as an RSS aggregator for a dashboard I figured I'd keep it simple. The dashboard does fetch the data, so for me it's working. I might try putting it behind basic auth though, as you're suggesting, hoping the dashboard (saas) can work with user:pass@... links.

So, running FreshRSS openly in the internet is not an intended use-case for FreshRSS, did I get that right?
