### ISSUE TITLE
[BUG] Unable to Update to 1.20.2

### ISSUE THREAD

**Issue by pageuppagedown** [FreshRSS/FreshRSS#4932]
**Describe the bug**

An update has been released today, but FreshRSS doesn't see that it's available.

**To Reproduce**
1. Go to Settings.
2. Go to Update under the Administration section.
3. Click on Check for new updates.
4. See that 1.20.1 is the latest version.

**Expected behavior**

I'm expecting to be able to upgrade to 1.20.2.

**Screenshots**

The current screenshot shows that 1.20.1 is available -- not 1.20.2. The time is in the US Eastern Time zone.

<img width="432" alt="Screenshot 2022-12-08 at 9 47 15 AM" src="https://user-images.githubusercontent.com/10445792/206476812-f3569d83-34c2-4c74-bb47-44bc63ddcc94.png">

**Environment information (please complete the following information):**
- Device: Mac
- OS: macOS
- Browser: Safari 16.1
- FreshRSS version: 1.20.1
- Database version: sqlite
- PHP version: 7.4.30
- Installation type: Linode Instance

**Additional context**

N/A

**Comment by aledeg** [comment]
Give it some time. It hasn't been deployed to the server yet.
If you're in a hurry, you can do that with git.

FYI @marienfressinaud

**Comment by Alkarex** [comment]
@marienfressinaud has promised to update the update server tonight.

@pageuppagedown If you are interested in faster releases and also more flexibility, FreshRSS can also be installed by git clone instead of ZIP archive.

Edit: Ah, @aledeg said so already :-)

**Comment by marienfressinaud** [comment]
It should be good now!

**Comment by aledeg** [comment]
Confirmed. It's available!

**Comment by pageuppagedown** [comment]
Thank you so much!
