### ISSUE TITLE
Move to New Domain

### ISSUE THREAD

**Issue by faridalizade** [FreshRSS/FreshRSS#4934]
Hello,

I want to duplicate my old FreshRSS from 1domain.com to 2domain.com.. 

I did it but it seems 500 error appears. 

What am I missed?

Thank you.

**Comment by UPuXA** [comment]
Hello
i think you need to change a config file in the main (not p) FreshRSS directory.

I changed the root of my apache (domain.net/p -> domain.net/)  and had to change this . The setting should be near to the top and the file ist called config something.
