### ISSUE TITLE
Liste des articles blanches

### ISSUE THREAD

**Issue by ClementNX** [FreshRSS/FreshRSS#495]
Depuis quelques temps lors de la connexion j'ai aucun article d'affiché.
Lorsque je clique sur la première catégorie j'ai bien les articles et mais pas sur la seconde.

J'ai essayé en navigation privée (pour le cache etc) : ça ne change rien. Mais des fois ça fonctionne, étrange.

**Comment by ClementNX** [comment]
Je viens à nouveau d'avoir ce bug, sur la dernière version master que j'ai donc mis à jour à la dernière version beta mais il est toujours présent.
Je suis en sens de lecture normal (plus récent au plus vieux).
Il n'y a que quelques flux qui posent ce problème : http://sametmax.com/feed/ (NSFW possible) et http://feeds.feedburner.com/KorbensBlog-UpgradeYourMind. Ils ne posaient pas problème avant, du coup j'ai pensé à un article mal balisé mais le validator W3C semble dire que non :/.

**Comment by Draky50110** [comment]
Ça fait un bail que je n'ai plus ça moi.

**Comment by marienfressinaud** [comment]
@X3Ndotfr > je n'ai pas ce problème personnellement en ayant ces deux flux dans FreshRSS (enfin j'utilise https://korben.info/feed plutôt que de passer par FeedBurner)
