### ISSUE TITLE
[BUG] Favicon retrieval doesn't respect curl_options

### ISSUE THREAD

**Issue by vrachnis** [FreshRSS/FreshRSS#4951]
**Describe the bug**
When `data/config.php` includes `curl_options`,  those settings are not used when FreshRSS retrieves a feed's favicon. For instance, if `CURLOPT_PROXY` is defined, the proxy is not used, and a direct HTTP connection is made.

**To Reproduce**
1. Define `curl_options` in `config.php`. The following example will work if privoxy is running on the same host as FreshRSS.

```
  'curl_options' => 
  array (
                  CURLOPT_PROXYTYPE => CURLPROXY_HTTP,
                  CURLOPT_PROXY => 'localhost',
                  CURLOPT_PROXYPORT => 8118,
                  CURLOPT_RETURNTRANSFER => true,
  ),
```
2. Try to add a new feed.
3. The feed's icon is not requested through the proxy as indicated by the lack of activity in the proxy's log file.

**Expected behavior**
The settings in the config file should be respected, and the request should go through the proxy.

**Screenshots**
N/A

**Environment information (please complete the following information):**
- Device: N/A, happens from all devices
- OS: FreeBSD
- Browser: N/A, happens in all browsers
- FreshRSS version: 1.20.2
- Database version: PostgreSQL
- PHP version: PHP 8.0
- Installation type: Manual install

**Additional context**
It seems that the issue is with the implementation of the function `downloadHttp` in `favicons.php`. The following diff seems to fix it for me locally:

```diff
--- a/lib/favicons.php
+++ b/lib/favicons.php
@@ -28,6 +28,8 @@ function downloadHttp(&$url, $curlOptions = array()) {
                return '';
        }
        $ch = curl_init($url);
+       FreshRSS_Context::initSystem();
+       curl_setopt_array($ch, FreshRSS_Context::$system_conf->curl_options);
        curl_setopt_array($ch, [
                        CURLOPT_RETURNTRANSFER => true,
                        CURLOPT_TIMEOUT => 15,
```

**Comment by Alkarex** [comment]
Sorry @vrachnis , this went under my radar.
Your patch looks fine. If you are still around, could you please send a PR?

**Comment by vrachnis** [comment]
No problem at all.

I can send a PR with the shown diff, but the main thing that held me back originally is that my PHP coding experience is close to non-existent, and specifically my unfamiliarity around how I would add some unit tests for this use case to ensure it keeps working.

If you can give me some references I can come back (probably in about a week or so) with a proper PR; otherwise I can submit the PR with the diff as-is, without new unit tests.

**Comment by Alkarex** [comment]
Just send a PR as-is. To test that would require mocking a back-end, which we do not have at the moment.

**Comment by vrachnis** [comment]
I opened #5421 with a slightly tweaked implementation, in order to make PHPStan happy with the new code, and stop it from complaining with:

```
 ------ ---------------------------------------------------------------------------- 
  Line   lib/favicons.php                                                            
 ------ ---------------------------------------------------------------------------- 
  38     Cannot access property $curl_options on FreshRSS_SystemConfiguration|null.  
 ------ ---------------------------------------------------------------------------- 
```
