### ISSUE TITLE
Can't follow docs for Installation on Ubuntu 20.04

### ISSUE THREAD

**Issue by 96312** [FreshRSS/FreshRSS#4954]
Your community documentation at https://freshrss.github.io/FreshRSS/en/admins/06_LinuxInstall.html is non-helpful. Following it down-to-a-T leads to two errors on MySQL and Apache restart steps. FWIW, I've attached the error screenshots below.

1.  `service mysql-server restart `
Failed to restart mysql-server.service: Unit mysql-server.service not found.

2.  `service apache2 restart`
![image](https://user-images.githubusercontent.com/34262180/209334075-efed8059-a1c2-4235-b7ec-10e4ec0f384b.png)

**Comment by Frenzie** [comment]
I don't think those errors can originate from the linked document since it doesn't mention any `/path/to` placeholders (which should be replaced by a real path).

But yes, it's possible that `mysql-server` is now `mysqld` or something.

**Comment by 96312** [comment]
If those errors can't originate from the linked document, then maybe a version of me in the parallel universe snuck in and wrote something in my terminal when I wasn't looking.

**Comment by Frenzie** [comment]
As I said you should replace `/path/to` with an actual path.

**Comment by 96312** [comment]
Ok
