### ISSUE TITLE
Installation on Debian 9

### ISSUE THREAD

**Issue by vdias** [FreshRSS/FreshRSS#4955]
I think Installation on Debian 9 is not quite correct...

"ln -s /usr/share/FreshRSS/p /var/www/html/"

With this you servir URL is not "http://<your_server>/" is "http://<your_server>/p/"

**Comment by Frenzie** [comment]
As written perhaps it assumes you'd delete the folder first in order to create a symlink. But yeah, you're right.

**Comment by vdias** [comment]
> As written perhaps it assumes you'd delete the folder first in order to create a symlink. But yeah, you're right.

Delete folder???

**Comment by Frenzie** [comment]
It's an inconsistent behavior from `ln`.

If `/var/www/html/` exists, then `ln -s /usr/share/FreshRSS/p /var/www/html/` creates a symlink in `/var/www/html/p`. But if it doesn't, it'll create a symlink in `/var/www/html/`.

**Comment by vdias** [comment]
i think there is a cleaner solution for this...

Create a apache dedicated configuration file:

/etc/apache2/sites-available/freshrss.conf
_<VirtualHost *:80>
DocumentRoot /usr/share/FreshRSS/p
</VirtualHost>_

and disable the "000-default.conf".

**Comment by Frenzie** [comment]
Of course.

**Comment by math-GH** [comment]
What should happen with this ticket here?
