### ISSUE TITLE
Misalignment of "There are no articles to show" bow in Mapco theme

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/FreshRSS#4957]
**Describe the bug**

<img width="959" alt="chrome_2022-12-26_21-15-03" src="https://user-images.githubusercontent.com/7189936/209580918-097bde68-0d13-497c-90ad-938f98ef70c1.png">

I have not tested all themes but it looks isolated (not on Pafat, origine-compact, Nord pink)

**Comment by math-GH** [comment]
Thanks for reporting this bug. It is "just" Ansum and Mapco. Will fix it

**Comment by Alwaysin** [comment]
@math-GH thanks for this quick fix (will try it out when merged)! I think there is another problem that looks to happen only on Ansum and Mapco, and when ```icons_as_emojis``` is set as ```true``` in user config file:
![chrome_2022-12-28_10-15-14](https://user-images.githubusercontent.com/7189936/209788573-3bab1a0b-4d83-4514-a3a9-6932ec167dc4.gif)


Maybe you can take advantage of this issue to fix it as well?

**Comment by math-GH** [comment]
This additional issue is now #4965 and its PR #4966

**Comment by Alwaysin** [comment]
@math-GH a new PR broke it again

**Comment by math-GH** [comment]
@Alwaysin Fix is merged. Thank you very much for your issue report
