### ISSUE TITLE
[Feature] Roadmap Website

### ISSUE THREAD

**Issue by Xyz00777** [FreshRSS/FreshRSS#4963]
**Is your feature request related to a problem? Please describe.**
I dont know what you plan next to integrate

**Describe the solution you’d like**
I would like to see a roadmap or milestones of requested features what you try to implement into the next release :)

**Describe alternatives you’ve considered**
🤷

**Additional context**
it would be nice if you would more with milestones or a roadmap so users who use the software knows what could come next, becuase i seen a feature request i really would like to see but the last update it had war a year ago, so i really dont know when it comes :/ or on what priority order it is to get implemented...

**Comment by aledeg** [comment]
You mean [that](https://github.com/FreshRSS/FreshRSS/milestones)?

**Comment by Xyz00777** [comment]
Okay it looks like I'm blind, thanks :) have nice holiday days :)
Greetings
