### ISSUE TITLE
[BUG] Enclosures: Youtube: Thumbnail + download icon, that is just a link

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#4970]
**Describe the bug**
Feed: https://www.youtube.com/feeds/videos.xml?channel_id=UCnCikd0s4i9KoDtaHPlK-JA

The floppy disc icon is not a download, it is just a link to the youtube video
![grafik](https://user-images.githubusercontent.com/1645099/210076671-6c3d3761-c7e6-4c48-b0a1-fff650e22a8b.png)

**Expected behavior**
No download = no download floppy disc icon

**Environment information (please complete the following information):**
- FreshRSS version: 1.21.0-dev

**Comment by math-GH** [comment]
Ref. to #4944

**Comment by Alkarex** [comment]
Indeed, but that is because this is generic to all enclosures. Downloading from YouTube requires completely different approaches outside the realm of FreshRSS (at least for the core)
