### ISSUE TITLE
[BUG] Enclosure shows only 1 image of many

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#4974]
**Describe the bug**
Example feed: https://raw.githubusercontent.com/math-GH/testfeed/main/test-feed.xml

"News 4" has 2 images
![grafik](https://user-images.githubusercontent.com/1645099/210115351-d7157511-f167-44bf-959e-687015809102.png)

but only 1 image is shown
![grafik](https://user-images.githubusercontent.com/1645099/210115399-c13a8d61-b36e-44a8-8505-b2b3b4c55eb4.png)

**Environment information (please complete the following information):**
- FreshRSS version: 1.20.0-dev

**Comment by math-GH** [comment]
Ref. #4944

**Comment by Alkarex** [comment]
SimplePie bug, should be fixed by https://github.com/Alkarex/FreshRSS/commit/60e973609050060ed0d9ec9ae9224f2c9200bb4b

**Comment by math-GH** [comment]
I can confirm that #4944 will fix this issue

**Comment by Alkarex** [comment]
Upstream PR https://github.com/simplepie/simplepie/pull/769
