### ISSUE TITLE
[Feature]ctrl+left click on manage button on feed management should open in new tab.

### ISSUE THREAD

**Issue by rezad1393** [FreshRSS/FreshRSS#4977]
when user opens feed management and I try to open a feed management in new tab, I either have to right click on it and select to open in new tab, or middle-click.
but everywhere else (even in other part of freshrss) ctrl+clicking on a link (or button) opens it in new tab.
can this be fixed?
right now it opens it in a sliding page not a new page which happens with just clicking also.

**Comment by Frenzie** [comment]
Makes sense to avoid that behavior with ctrl and shift.

**Comment by rezad1393** [comment]
> Makes sense to avoid that behavior with ctrl and shift.

I dont understand?
are u saying a thing in my favor or against it?
all I am saying is that in only that case it doesn't work (in freshrss I mean).

**Comment by Frenzie** [comment]
I think makes sense is usually in favor. ;-)

**Comment by math-GH** [comment]
To be honest, I do not understand what you need. Could you please support 1 or 2 examples?

**Comment by Frenzie** [comment]
If you click manage in this menu:
![image](https://user-images.githubusercontent.com/202757/210177764-3cde3346-54ed-4c47-9eb2-6978bfd982a2.png)

Btw, is "Mark as read" supposed to be so large? That's with the latest edge, Nord theme.

**Comment by Frenzie** [comment]
Anyway, this is what the OP would like:
```diff
diff --git a/p/scripts/extra.js b/p/scripts/extra.js
index 52a480c9..c068a998 100644
--- a/p/scripts/extra.js
+++ b/p/scripts/extra.js
@@ -145,6 +145,9 @@ function init_archiving(parent) {
 const freshrssSliderLoadEvent = new Event('freshrss:slider-load');
 
 function open_slider_listener(ev) {
+       if (ev.ctrlKey || ev.shiftKey) {
+               return;
+       }
        const a = ev.target.closest('.open-slider');
        if (a) {
                if (!context.ajax_loading) {
```
