### ISSUE TITLE
[BUG] PHP 8 disabled function behavior has changed

### ISSUE THREAD

**Issue by nico3333fr** [FreshRSS/FreshRSS#4982]
**Describe the bug**
Some feeds are displayed like having issues, are not refreshed. Impossible to refresh them or re-add them.

**To Reproduce**
- get a feed with this issue
- try to refresh it or re-add it

**Expected behavior**
I guess FreshRSS should fetch new posts.

**Screenshots**
![image](https://user-images.githubusercontent.com/2578321/210368015-e59bdac6-eef1-47c4-9449-2ee8ca063932.png)

![image](https://user-images.githubusercontent.com/2578321/210368043-2de08d2b-9641-452b-bb3d-c1721f4a8474.png)

![image](https://user-images.githubusercontent.com/2578321/210368468-c24ed62b-0877-41a2-933a-eb95fa958086.png)
Feed is valid and reachable.

I did try to delete it and re-add it, i just get a blank page:

![image](https://user-images.githubusercontent.com/2578321/210374719-31088ca7-8e86-4ed8-9542-8572528b2dde.png)

**Environment information (please complete the following information):**
- PHP version: 8.0.25 on a self hosted infomaniak website

Everything seems ok from hosting pov
![image](https://user-images.githubusercontent.com/2578321/210375210-34fdd781-dea0-48c2-940c-41e142bbed71.png)

**Additional context**
Anything I could provide, don't hesitate to ask.

**Comment by Frenzie** [comment]
My guess would be it did have an (intermittent) problem and that was cached while it probably shouldn't be.

**Comment by nico3333fr** [comment]
How could I refresh it to check it's not happening again?

**Comment by Frenzie** [comment]
You'd have to delete the cache manually; I don't recall the exact path otoh, data/cache maybe?

**Comment by nico3333fr** [comment]
I did try, not working. 

Seems that even if I try to add any feed (like https://www.nicolas-hoffmann.net/rss/commentaires.php?id_news=1714) nothing is working. Do I have to reinstall everything?

**Comment by Frenzie** [comment]
Nah, in that case it just means my hunch must've been wrong. ;-)

**Comment by nico3333fr** [comment]
Okay, I did a fresh install, tried to add Smashing magazine feed https://www.smashingmagazine.com/feed/ and got a blank page. 
Is Fresh Rss compatible with PHP8.0.25?

**Comment by nico3333fr** [comment]
It seems I don't have something more recent in my feeds than 28th of November.

**Comment by Frenzie** [comment]
> Is Fresh Rss compatible with PHP8.0.25?

Yes (unless it's very specifically 8.0.25 that has a problem), I see no issues with that feed.
![image](https://user-images.githubusercontent.com/202757/210409724-e70228a0-a9fd-42da-b647-2fb9b68e5090.png)

![image](https://user-images.githubusercontent.com/202757/210409871-2c5d701a-2cc4-4021-be9c-d2579f05c275.png)

**Comment by Frenzie** [comment]
What do your logs say?

**Comment by nico3333fr** [comment]
Something like:

```
WEBSITE [Tue Jan 03 18:38:23.560021 2023] [-:error] [pid 8612:tid 139885700622080] [client 185.159.157.200:0] FastCGI: server "/home/WEBSITE/.fpm/php5.external" stderr: #1 /home/WEBSITE/web/HIDDEN_URL/lib/Minz/Dispatcher.php(119): FreshRSS_feed_Controller->addAction()
WEBSITE [Tue Jan 03 18:38:23.560026 2023] [-:error] [pid 8612:tid 139885700622080] [client 185.159.157.200:0] FastCGI: server "/home/WEBSITE/.fpm/php5.external" stderr: #2 /home/WEBSITE/web/HIDDEN_URL/lib/Minz/Dispatcher.php(48): Minz_Dispatcher->launchAction('addAction')
WEBSITE [Tue Jan 03 18:38:23.560032 2023] [-:error] [pid 8612:tid 139885700622080] [client 185.159.157.200:0] FastCGI: server "/home/WEBSITE/.fpm/php5.external" stderr: #3 /home/WEBSITE/web/HIDDEN_URL/lib/Minz/FrontController.php(58): Minz_Dispatcher->run()
WEBSITE [Tue Jan 03 18:38:23.560037 2023] [-:error] [pid 8612:tid 139885700622080] [client 185.159.157.200:0] FastCGI: server "/home/WEBSITE/.fpm/php5.external" stderr: #4 /home/WEBSITE/web/HIDDEN_URL/p/i/index.php(57): Minz_FrontController->run()
WEBSITE [Tue Jan 03 18:38:23.560041 2023] [-:error] [pid 8612:tid 139885700622080] [client 185.159.157.200:0] FastCGI: server "/home/WEBSITE/.fpm/php5.external" stderr: #5 {main}
WEBSITE [Tue Jan 03 18:38:23.560275 2023] [fastcgi:error] [pid 8612:tid 139885700622080] [client 185.159.157.200:0] FastCGI: server "/home/WEBSITE/.fpm/php5.external" stderr:   thrown in /home/WEBSITE/web/HIDDEN_URL/app/Controllers/feedController.php on li.../web/HIDDEN_URL/app/Controllers/feedController.php:43
```

Not sure if it helps

**Comment by nico3333fr** [comment]
Maybe these:

```
WEBSITE [Tue Jan 03 18:38:23.559969 2023] [-:error] [pid 8612:tid 139885700622080] [client 185.159.157.200:0] FastCGI: server "/home/WEBSITE/.config/apache/WEBSITE/.fpm/php5.external" stderr: PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function set_time_limit() in /home/WEBSITE/web/<FRESH_RSS_URL>/app/Controllers/feedController.php:43
WEBSITE [Tue Jan 03 18:38:23.559998 2023] [-:error] [pid 8612:tid 139885700622080] [client 185.159.157.200:0] FastCGI: server "/home/WEBSITE/.config/apache/WEBSITE/.fpm/php5.external" stderr: Stack trace:
WEBSITE [Tue Jan 03 18:38:23.560016 2023] [-:error] [pid 8612:tid 139885700622080] [client 185.159.157.200:0] FastCGI: server "/home/WEBSITE/.config/apache/WEBSITE/.fpm/php5.external" stderr: #0 /home/WEBSITE/web/<FRESH_RSS_URL>/app/Controllers/feedController.php(224): FreshRSS_feed_Controller::addFeed('https://www.sma...', '', '2', '', '', Array, '0')
```

**Comment by nico3333fr** [comment]
OMG, I've just found. Infomaniak disabled `set_time_limit` in PHP, and once I reactivated it, it worked. 

![image](https://user-images.githubusercontent.com/2578321/210413886-f89a1028-d15b-4366-8770-27275e79bb7b.png)

Sorry for noise.

**Comment by Frenzie** [comment]
Apparently PHP changed its behavior when functions are disabled, so it is a compatibility issue. 
https://php.watch/versions/8.0/disable_functions-redeclare

Presumably we'd want to change them to something along these lines, or maybe @Alkarex has a better idea:
```php
if (function_exists('random_int')) {
    @set_time_limit(300);
}
```

**Comment by nico3333fr** [comment]
Anyway, thanks for your help :)

**Comment by nico3333fr** [comment]
@Frenzie do you want me to close or do we keep it opened?

**Comment by Frenzie** [comment]
The code as written fails silently in PHP <8 and we're okay with that but in PHP 8 an expected function can sometimes be undefined.

I'm not 100% sure if we should regard it as a compatibility issue though since in principle I believe you can disable any (internal) function. That is, it's not fundamentally different than not having the required ctype library or something. But also this one's a bit of a special case in that it doesn't really matter much if it's disabled or not.

<https://www.php.net/manual/en/ini.core.php#ini.disable-functions>

@nico3333fr Please leave it open. It could be interesting to do something with `ini_get('disable_functions')` on the installation check page, although I don't know what exactly. We can hardly check for every single function used, but perhaps it'd make sense for a few potentially commonly disabled ones like `curl_exec()` for example.

**Comment by Alkarex** [comment]
I do not know how common it is to disable this core function, but it looks like the SMTP library we use has a special handling 

https://github.com/FreshRSS/FreshRSS/blob/92d1b0cda731b7c4ce244f4cd3f759056a2f1534/lib/phpmailer/phpmailer/src/SMTP.php#L430-L439

I think this code is overkill, but we could maybe just wrap the call in a try/catch if that is sufficient
