### ISSUE TITLE
[BUG] Unable to use parentheses in search/queries

### ISSUE THREAD

**Issue by jamieshaw** [FreshRSS/FreshRSS#4987]
**Describe the bug**
When composing a search, feed rule, or user query — it is no longer possible to use parentheses `()` to match title strings (instead, they are favoured for rule grouping).

**To Reproduce**
1. Find an article that contains a string in parentheses.
2. Attempt to build a query using `intitle:({{ string }})`
3. Observe more articles are returned than expected.

**Expected behavior**
Only the articles matching the exact query string should be returned.

**Screenshots**
Attempting to search articles with `(sponsor)` in the title, but other, incorrect matches are returned.
![image](https://user-images.githubusercontent.com/16481433/211029512-4d57b4b4-1ec8-400c-82e6-7ed06d698722.png)

**Environment information (please complete the following information):**
- Device: MacBook Pro (16-inch, 2021)
- OS: macOS 12.6
- Browser: Safari 16.1
- FreshRSS version: 1.20.2
- Database version: MariaDB 10.6
- PHP version: PHP 8.1.2
- Installation type: Self-host, Ubuntu 22.04 VM under ESXi 7.0

**Comment by Alkarex** [comment]
Would you be able to test https://github.com/FreshRSS/FreshRSS/pull/4989 ?

**Comment by jamieshaw** [comment]
> Would you be able to test #4989 ?

Seems to be working for search queries. Happy.
(First screenshot shows unescaped characters for reference).

![image](https://user-images.githubusercontent.com/16481433/211191374-60625a94-3b56-441e-a317-2eec2aebcb36.png)
![image](https://user-images.githubusercontent.com/16481433/211191376-0b5819e1-6df0-4302-a49a-23992b94e3dc.png)
