### ISSUE TITLE
Automatic dark mode status

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/FreshRSS#5000]
Following #4843, when I put "Automatic dark mode (beta)" to "Auto" and submit, it automatically switches back to "No" (but still the dark theme is applied as expected). Then when I try to move away it says I have unsaved changes. See the video below

![chrome_2023-01-09_11-25-28](https://user-images.githubusercontent.com/7189936/211287228-31f18e9f-04b3-49bc-831d-b5dd30aa22a9.gif)

**Comment by math-GH** [comment]
Very good catch for a very stupid bug. Thanks! Fixed with #5002
