### ISSUE TITLE
How are feed updates handled?

### ISSUE THREAD

**Issue by Panja0** [FreshRSS/FreshRSS#5007]
I'm using a cron job to do a web update (curl 127.0.0.1/i/etcetcetc) for 1 particular feed.
This feeds get a lot of new articles and needs to be updated frequently so I've set the cron job for every 2 minutes (*/2).
But articles can sometimes take 10 - 20 minutes before they show up in my FreshRSS instance.

Is this normal? If so can it be changed?

**Comment by math-GH** [comment]
You can set the default minimum time in the config (minimum 20 minutes) :
![image](https://user-images.githubusercontent.com/1645099/212132168-76fe5cea-5108-4f12-807c-279e3ae141cb.png)

In the feed settings itself you can change it too (minimum: 15 minutes):
![image](https://user-images.githubusercontent.com/1645099/212132471-b609ab5a-6810-4041-a27c-4f50a9790661.png)

**Comment by Panja0** [comment]
Thanks for the reply. 

But what does the web update via cron do than? I’ve set that to every 2 minutes. 

This particular feeds needs regular updating. Once per 15 min won’t work in this case.

**Comment by math-GH** [comment]
The cron checks the feeds, whether they should be updated next (check last update date and calculate the next refresh date).

If there is no feed to be updated, then the cron will do nothing

**Comment by Panja0** [comment]
Ok. How would I proceed if I want to check one particular feed every 2 minutes?

**Comment by math-GH** [comment]
What is your use case to fetch every 2 minutes a RSS feed?

**Comment by Panja0** [comment]
I’m using Full-Text RSS to get the full article from the RSS feed. Though the feed limits full articles to 2 articles per time. They post regular updates, sometimes a few per minute. 

There for I need faster updates otherwise I’ll lose articles. Does that make sense?

**Comment by Alwaysin** [comment]
If I'm not mistaken, FreshRSS has a hard-coded minimum value for feeds retrieval so as not to harm website owners (who can then block tools like FreshRSS if they see too many requests, which is bad for everyone !). If you want to change it, you'll have to manually update the source code.

I think for this use case it is best to use WebSub which is supported by FreshRSS. Maybe you could talk about it to the site owner?
