### ISSUE TITLE
[Feature] use local timezone set for host as the one used by log section.

### ISSUE THREAD

**Issue by rezad1393** [FreshRSS/FreshRSS#5011]
**Is your feature request related to a problem? Please describe.**
when I use the log in freshrss (not the text log of php) the date is in UTC.

**Describe the solution you’d like**
the time should be the local TZ used by system.

**Comment by rezad1393** [comment]
the new update with timezone setting resolved this issue.

**Comment by Alkarex** [comment]
Thanks for following-up!
https://github.com/FreshRSS/FreshRSS/pull/4906
https://github.com/FreshRSS/FreshRSS/pull/4903
