### ISSUE TITLE
[BUG] Lemmy share produce an incorrect url

### ISSUE THREAD

**Issue by FrancescoCeliento** [FreshRSS/FreshRSS#5018]
**Describe the bug**
When I share to a Lemmy instance, the "name" attribute should be called "title" to populate the title of the post

**To Reproduce**
1. Go to Main app
2. Click on an article
3. Scroll down to end of article
4. Click on share
5. Select the lemmy instance
6. See the new post with Title empty because "title" attribute is not set

**Expected behavior**
The product link should not be this one
- https://lemmy.ml/create_post?url=[URL]&name=[TITLE]
but this one
- https://lemmy.ml/create_post?url=[URL]&title=[TITLE]

**Screenshots**
![Immagine.png](https://i.ibb.co/5xJYQgf/Immagine.png)
![Immagine.png](https://i.ibb.co/hKbK2Jd/Immagine.png)

**Environment information (please complete the following information):**
- Device: Web
- OS: Windows 10/Manjaro
- Browser: Firefox 109.0
- FreshRSS version: 1.18.1-dev
- Database version: Mysql 5.7
- PHP version: PHP 7.4
- Installation type: CPanel

**Additional context**
None

**Comment by math-GH** [comment]
That is a bit strange, because the API documents no "title" parameter.

See API documentation: https://join-lemmy.org/api/classes/CreatePost.html#name
See source code: https://github.com/LemmyNet/lemmy-js-client/blob/b685a3480b7a1fe2ed72901fb2aeecadc9ac015d/src/interfaces/api/post.ts#L14-L23


Side note: It would be very helpful for the best support that you would have the actual FreshRSS version 1.20.2

**Comment by Frenzie** [comment]
While confusing that it's different, presumably the API isn't directly relevant here. The OP is confirmed by e.g. https://codeberg.org/Jeremmy/fedishare/src/commit/1b8dd14c4a18e9e992788e15d0f6bd210ee14d14/src/lib/instances.ts#L49-L54

```ts
export const lemmy: Instance = {
  name: 'Lemmy',
  post: '/create_post?url=Url&title=Title',
  icon: 'comments',
  host: 'https://lemmy.glasgow.social',
};
```

**Comment by math-GH** [comment]
@FrancescoCeliento Could you please check if the PR #5020 will fix it?

**Comment by FrancescoCeliento** [comment]
I apologize for the delay, I had not got the notification from github. I confirm that with version 1.21.0-dev it works correctly. Thanks for the support
