### ISSUE TITLE
[BUG] Nord Theme - Misaligned site icons

### ISSUE THREAD

**Issue by sdkane** [FreshRSS/FreshRSS#5019]
With the 1.20.* releases of FreshRSS using Firefox on mobile, the Nord Theme has misaligned site icons on the left hand side of each item in the list. Each icon is off center to the text. 

![Screenshot_20230118-103739](https://user-images.githubusercontent.com/26040245/213216041-1edbf452-be48-4e0d-bdbb-5508fd593e1f.png)

Before the 1.20.* releases, the icon was centered on the text. All other themes have the icons centered on the text. I'd imagine this is a simple css error, but I am unfortunately not at all skilled in css.  

- Device: Pixel 5a
- OS: Android 13
- Browser: Firefox 108.2
- FreshRSS version: 1.20.2
- Database version: SQLite 
- PHP version: 8.0.25
- Installation type: Linux server docker on personal server

**Comment by math-GH** [comment]
Do you have the chance to check the current developer branch of FreshRSS?

For me the 1.21.0-dev looks like this in Firefox on Windows 10
![grafik](https://user-images.githubusercontent.com/1645099/213262419-73f27c9f-0d27-480c-bffd-e37c6d2376c8.png)

**Comment by sdkane** [comment]
I installed a clean version of the docker edge branch (1.21.0-dev) and the issue is not present there.

**Comment by Frenzie** [comment]
Already fixed then. :-)
