### ISSUE TITLE
RSS feeds behind Self certified SSL certificate not working

### ISSUE THREAD

**Issue by karibuTW** [FreshRSS/FreshRSS#502]
Hi guys,

I want to add a RSS feed that is using HTTPS connection (But through a self certified certificate). FreshRSS refuse to use it (Most probably it need to force the self certified certificate acceptance). If I use HTTP, no use tho.

Any chance to correct this?

Thank you!

**Comment by Alkarex** [comment]
See https://github.com/simplepie/simplepie/pull/407
