### ISSUE TITLE
New installation - No input file specified.

### ISSUE THREAD

**Issue by SkysCrystal** [FreshRSS/FreshRSS#5027]
**Describe the bug**
After I uploaded files (FreshRSS 1.20.2) to vps, I set Nginx-root to `p` folder and changed all files to owner `www`.

I added the following codes to Nginx:
```
location ~ ^.+?\.php(/.*)?$ {
        fastcgi_pass unix:/tmp/php-cgi.sock;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        # By default, the variable PATH_INFO is not set under PHP-FPM
        # But FreshRSS API greader.php need it. If you have a “Bad Request” error, double check this var!
        # NOTE: the separate $path_info variable is required. For more details, see:
        # https://trac.nginx.org/nginx/ticket/321
        set $path_info $fastcgi_path_info;
        fastcgi_param PATH_INFO $path_info;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    } 

    location / {
        try_files $uri $uri/ index.php;
    }
```

**To Reproduce**
Visiting my website, it shows `No input file specified.` or `Http error 500`. 

How can I solve this problem? Thanks!

**Expected behavior**
Can visit site and set db.

**Screenshots**
None.

**Environment information (please complete the following information):**
- Device: [VPS]
- OS: [Debian 11]
- Browser: [Chrome]
- FreshRSS version: [1.20.2]
- Database version: [Mysql 8.0.30]
- PHP version: [PHP 8.1.7]
- Installation type: [Git download]

**Additional context**
None.

**Comment by SkysCrystal** [comment]
php error log

```
[22-Jan-2023 13:49:26] WARNING: [pool www] child 549932 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function openlog() in /home/wwwroot/mysite/lib/lib_rss.php:23"
[22-Jan-2023 13:49:26] WARNING: [pool www] child 549932 said into stderr: "Stack trace:"
[22-Jan-2023 13:49:26] WARNING: [pool www] child 549932 said into stderr: "#0 /home/wwwroot/mysite/p/i/index.php(24): require()"
[22-Jan-2023 13:49:26] WARNING: [pool www] child 549932 said into stderr: "#1 {main}"
[22-Jan-2023 13:49:26] WARNING: [pool www] child 549932 said into stderr: "  thrown in /home/wwwroot/mysite/lib/lib_rss.php on line 23"
```

**Comment by SkysCrystal** [comment]
openlog( ) is diabled on my VPS. Problem is solved.

**Comment by Alkarex** [comment]
By curiosity, was `syslog()` also disabled?

**Comment by SkysCrystal** [comment]
> By curiosity, was `syslog()` also disabled?

Yes, `syslog()` was also disabled.  It forbade me from refreshing RSS. I have also fixed this.

[FreshRSS Installation based on LNMP 中文博客 Chinese Blog](https://www.dsuper.xyz/article/freshrss_installation)

**Comment by Alkarex** [comment]
Workaround patch https://github.com/FreshRSS/FreshRSS/pull/5054
