### ISSUE TITLE
[BUG] Error while running `app/actualize_script.php`

### ISSUE THREAD

**Issue by daniporr** [FreshRSS/FreshRSS#5033]
**Describe the bug**

While running `app/actualize_script.php`, I got this error:

> PHP Parse error:  syntax error, unexpected ':', expecting '{' in .../lib/lib_rss.php on line 14

**To Reproduce**
1. Run `app/actualize_script.php`

**Expected behavior**

No errors

**Environment information (please complete the following information):**
- OS: Linux
- FreshRSS version: 1.20.2
- PHP version: 8.2.1

**Comment by daniporr** [comment]
If I remove `: bool`, I get this other error:

> PHP Parse error:  syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in .../lib/lib_rss.php on line 32

Could this be a problem with the PHP version?

**Comment by Frenzie** [comment]
How are you running it?

**Comment by daniporr** [comment]
The server (I installed it via Softaculous) is running it using the following command:

> php .../app/actualize_script.php > .../data/users/FreshRSS_cron.log 2>&1

Maybe it is picking the wrong version of PHP (an not the one I selected), could that be?

**Comment by Frenzie** [comment]
Could you verify what it says if you try this?
```
$ php --version
PHP 8.2.1 (cli) (built: Jan  6 2023 15:12:40) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.1, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.1, Copyright (c), by Zend Technologies
$ php -l lib/lib_rss.php 
No syntax errors detected in lib/lib_rss.php
```

**Comment by daniporr** [comment]
Unfortunately I cannot run commands on that server, but I have been able to tweak the cron job and I forced it to run PHP 8.

Now it works as expected (or, at least, it does not print any errors in output).

Thank you very much for your help!
(we can close this issue)

**Comment by Frenzie** [comment]
I can only assume it must've defaulted to some old version of PHP 5.x instead? Strange though.
