### ISSUE TITLE
[BUG] Notification

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#5041]
**Describe the bug**
Regression from #5022 

The HTML browser notification's text is now (number as example):
  There are %34 new articles to read on FreshRSS. (unread: %55)

The `%` is shown in plain.

![grafik](https://user-images.githubusercontent.com/1645099/214433959-6e08536f-4f8e-4c6d-a6a7-a6b840a21ce3.png)

**To Reproduce**
1. see the browser notification

**Expected behavior**
No `%`

**Environment information (please complete the following information):**
- FreshRSS version: 1.21.0-dev

**Comment by Alkarex** [comment]
Please try https://github.com/FreshRSS/FreshRSS/pull/5042
