### ISSUE TITLE
[BUG] Impossible to add some feeds

### ISSUE THREAD

**Issue by Ritooon** [FreshRSS/FreshRSS#5047]
**Describe the bug**
I tried to add 3 feeds. One working, 2 not.
Working : https://www.jeuxvideo.com/rss/rss.xml
Not working : https://rappel.conso.gouv.fr/rss And https://www.01net.com/actualites/feed/

**To Reproduce**
1. Try to add a feed
2. Got an error
3. Go to logs

**Expected behavior**
Feeds were working before. Then stopped working. So tried to remove/add again. Should have worked.

**Screenshots**
![image](https://user-images.githubusercontent.com/2474167/215054385-72e31e93-d0b0-42d9-a1f5-8f71ecb6756b.png)

**Environment information (please complete the following information):**
- Browser: Chrome
- FreshRSS version: 1.20.2

**Comment by math-GH** [comment]
I can add both feeds without any issues.

![grafik](https://user-images.githubusercontent.com/1645099/215353660-d0646278-3da8-4d45-ba03-23ba50491c3b.png)

![grafik](https://user-images.githubusercontent.com/1645099/215353842-d01693af-bcfb-44e1-8dd2-7de42c1f2b7f.png)

**Comment by Alkarex** [comment]
Try a `curl -v 'https://www.jeuxvideo.com/rss/rss.xml'` from your server and check whether it works. If not, your IP and/or user-agent may be banned.

**Comment by Ritooon** [comment]
> Try a `curl -v 'https://www.jeuxvideo.com/rss/rss.xml'` from your server and check whether it works. If not, your IP and/or user-agent may be banned.

This feed is working, so I get a HTTP 200. 

Tried this command with : 
` curl -v 'https://rappel.conso.gouv.fr/rss'`

Got : 

```
* About to connect() to rappel.conso.gouv.fr port 443 (#0)
*   Trying 185.24.187.242...
* Connected to rappel.conso.gouv.fr (185.24.187.242) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: serialNumber=S232930416,CN=rappel.conso.gouv.fr,OU=0002 12002503600035,O=DIR GEN CONCUR CONSOM REPRES FRAUDES DGCCRF,L=PARIS,C=FR
*       start date: avril 10 22:00:00 2022 GMT
*       expire date: avril 10 21:59:59 2023 GMT
*       common name: rappel.conso.gouv.fr
*       issuer: CN=Certigna Services CA,OID.2.5.4.97=NTRFR-48146308100036,OU=0002 48146308100036,O=DHIMYOTIS,C=FR
> GET /rss HTTP/1.1
> User-Agent: curl/7.29.0
> Host: rappel.conso.gouv.fr
> Accept: */*
>
< HTTP/1.1 403 Forbidden
< Date: Mon, 30 Jan 2023 08:25:59 GMT
< Content-Length: 199
< Content-Type: text/html; charset=iso-8859-1
<
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
</body></html>
* Connection #0 to host rappel.conso.gouv.fr left intact
```

This feed is working on Inoreader. Does this 403 means my IP is banned?

**Comment by Alkarex** [comment]
`403` typically means that either your IP, IP range, user agent, or a combination of those, is banned.
You can try from another IP and/or by changing the user agent string.

**Comment by Ritooon** [comment]
Just tried with my laptop browser user-agent (When adding the feed in FreshRSS interface). Still 403. 
So my IP seems to be banned ? Is there a way to prevent this ? My refresh task was maybe too small ?

**Comment by Alkarex** [comment]
Refreshing too often can lead to be banned, but sometimes it can also be the full IP range of e.g. a data centre, which gets banned.
For that specific feed, you can host a little proxy somewhere else (it can be a real proxy or a simple PHP script as below).

Another user got the same problem from OVH mutu:
See https://github.com/FreshRSS/FreshRSS/issues/4458#issuecomment-1193313689

**Comment by Ritooon** [comment]
Hum yeah, same feed :) 
Ok I'll try the proxy solution maybe.

Thanks !
