### ISSUE TITLE
[Feature] Add "My Labels" without opening the feeds

### ISSUE THREAD

**Issue by Alpaca0x0** [FreshRSS/FreshRSS#5051]
**Is your feature request related to a problem? Please describe.**
I always star the feeds I like to prevent them from being deleted due to the maximum number of feeds, then using labels to group them, and using the `My Label` button has become a headache. I have to **open** every feed and **scroll down to the bottom** to see the `My Label` button. 
(The most painful thing is when the **description of this feed is very long**)

**Describe the solution you’d like**
**Describe alternatives you’ve considered**
I can only think of three options:
1. Set the `My Label` button at the top of the feed, or add labels without opening the feed.
2. Make it possible to set not to capture the `<description>` tag, or to limit the length of the text to be captured.
3. When the text length reaches the set value, only part of the content will be displayed. If user wants to view all the content, click the "Read More" button.

**Additional context**

https://user-images.githubusercontent.com/58300460/215288544-71ab23b4-8aac-4797-a2ec-e18591825abd.mp4

**Comment by math-GH** [comment]
Would a keyboard shortcut also help?

**Comment by Alpaca0x0** [comment]
@math-GH Maybe, but the shortcut key is invalid on the mobile side user :(

**Comment by ParoTheParrot** [comment]
+1 for „Set the My Label button at the top of the feed„

**Comment by math-GH** [comment]
It is on my todo list. See https://github.com/FreshRSS/FreshRSS/pull/6395#issuecomment-2084595602

**Comment by math-GH** [comment]
@Alpaca0x0 @ParoTheParrot If you can please have a look into the PR #6984

**Comment by Alpaca0x0** [comment]
@math-GH u r amazing, thx for updating ✨
