### ISSUE TITLE
openlog error after update to php 8.1

### ISSUE THREAD

**Issue by tobip** [FreshRSS/FreshRSS#5053]
**Describe the bug**
I upgraded php version from 7.2 to 8.1. After this the freshrss page breaks, showing this error in my server log:
```
mod_fcgid: stderr: PHP Fatal error:  Uncaught Error: Call to undefined function openlog() in freshrss/lib/lib_rss.php:23
mod_fcgid: stderr: Stack trace:
mod_fcgid: stderr: #0 freshrss/p/index.php(3): require()
mod_fcgid: stderr: #1 {main}
mod_fcgid: stderr:   thrown in freshrss/lib/lib_rss.php on line 23
```

**Expected behavior**
-

**Environment information (please complete the following information):**
- Device: pc
- OS: Manjaro
- Browser: Chrome, Firefox
- FreshRSS version: 1.20.2
- Database version: mysql
- PHP version: 7.2 / 8.1
- Installation type: shared hosting

**Additional context**
Downgrade of php back to version 7.x solves the problem.

**Comment by Frenzie** [comment]
openlog exists in PHP 8. Disabled in php.ini perhaps?

**Comment by Alkarex** [comment]
Similar issue: https://github.com/FreshRSS/FreshRSS/issues/5027

**Comment by tobip** [comment]
True, `openlog` and `syslog` are disabled in my php.ini and as far as I can tell I am not allowed to enable them. 
Is there a workaround from the freshrss side of view to get it running without the need of these functions?

**Comment by Alkarex** [comment]
It would require a patch to implement a workaround for systems without syslog, which we do not have at the moment

**Comment by Alkarex** [comment]
For PHP 8+, the workaround would be easy to implement https://php.watch/versions/8.0/disable_functions-redeclare

**Comment by Alkarex** [comment]
@tobip Could you please try this patch? https://github.com/FreshRSS/FreshRSS/pull/5054

**Comment by tobip** [comment]
Awesome! It works under php 8.1, although I get following message in my logs:

```
[fcgid:warn] mod_fcgid: stderr: PHP Warning:  syslog() has been disabled for security reasons in freshrss/lib/SimplePie/SimplePie.php on line 1727
[fcgid:warn] mod_fcgid: stderr: PHP Fatal error:  Cannot redeclare syslog() in freshrss/lib/lib_rss.php on line 24
```

**Comment by Alkarex** [comment]
@tobip Are you sure those warning/error logs are when running your PHP 8.1?

**Comment by tobip** [comment]
Whops sorry, I think those errors were still there from when I was running php 7.
Everything seems to be fine.
