### ISSUE TITLE
[Feature] Allow setting of custom icon for each subscription

### ISSUE THREAD

**Issue by pstn** [FreshRSS/FreshRSS#5061]
**Is your feature request related to a problem? Please describe.**
For example when following a lot of youtube feeds via freshrss, all the icons of the feeds are the youtube icon, making them a bit useless.

**Describe the solution you’d like**
Have a field in the subscription manager of each subscription that allows a user to upload a custom image file as an icon for the feed that will be used in all places where currently the automatically fetched icon is used.

**Describe alternatives you’ve considered**
Have a logic that automatically fetches channel icons on youtube and have similar functionality on other big sites with the same issue.

**Additional context**
I don't think this feature is really urgent but I sure would find it nice to have.

**Comment by math-GH** [comment]
Similar to #3789
