### ISSUE TITLE
[BUG] RSS standard: multiple credits not shown

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#5066]
**Describe the bug**
Only the first credit of enclosures is shown of the 5th example of https://www.rssboard.org/media-rss#examples (as RSS feed: https://raw.githubusercontent.com/math-GH/testfeed/main/rssboard.org/example5.xml)

![grafik](https://user-images.githubusercontent.com/1645099/216778884-609f6afe-38a4-4278-86a1-8a22b3a809d9.png)

That is the source:
![grafik](https://user-images.githubusercontent.com/1645099/216778814-39896752-d53c-4f95-a976-35c01929f1e2.png)

**To Reproduce**
1. subscribe to https://raw.githubusercontent.com/math-GH/testfeed/main/rssboard.org/example5.xml
2. see that only the first credit is shown

**Expected behavior**
Both credits are shown

**Environment information (please complete the following information):**
- FreshRSS version: 1.21.0-dev

**Comment by Alkarex** [comment]
Please try https://github.com/FreshRSS/FreshRSS/pull/6272
