### ISSUE TITLE
[BUG] time zone default value is empty

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#5069]
**Describe the bug**
The default zone value is empty on demo.freshrss.org
![grafik](https://user-images.githubusercontent.com/1645099/216814353-4f9f65df-252b-4ec4-b6b2-af3a4d79852b.png)

expected (screen shot from my instance):
![grafik](https://user-images.githubusercontent.com/1645099/216814361-f47e79d8-7b23-4042-a9d7-cd05220df7d1.png)

**Comment by Frenzie** [comment]
Is that still an issue on the latest? See #5021.

**Comment by math-GH** [comment]
maybe.

@marienfressinaud Could you please update the demo with the newest edge branch? (I do not know what is the currents state/date of the demo)

**Comment by marienfressinaud** [comment]
It's now updated, and the issue is indeed fixed :+1:
