### ISSUE TITLE
[Feature] Allow to disable global proxy in specific feeds

### ISSUE THREAD

**Issue by rc2dev** [FreshRSS/FreshRSS#5081]
First of all, thanks for FreshRSS!

I have a proxy set on my instalation, on `config.php`. However, AFAIK, there isn't a way to disable it for specific feeds.

In the feed configuration, selecting "NONE" has no effect (will still use that global proxy), and I'm left with overriding that proxy address with another one.

My current workaround is to install a small proxy server on the same host and override the proxy address on those specific feeds configuration.

This feature may be useful, for example, to access resources on the same host (such as RSS Bridge), or if that feed doesn't play well with the proxy.

Best regards!

**Comment by Alkarex** [comment]
Could you please try https://github.com/FreshRSS/FreshRSS/pull/5082

**Comment by rc2dev** [comment]
Hi, Alexandre.

That's great! Selecting "NONE" now disables the proxy for the feed.
