### ISSUE TITLE
[Feature] header keep white 

### ISSUE THREAD

**Issue by boncuk10** [FreshRSS/FreshRSS#5088]
Hi,

when I open the mobile site of FreshRSS  then the header keep white and don’t turn in dark:

![AAE41887-C309-443F-B6D0-1FD0C4B86DB5](https://user-images.githubusercontent.com/54523503/218011045-5a8088cb-5973-4acf-b2e6-93365cb8d399.jpeg)

For example in google everything turns in dark:
![FA3D272C-B310-4410-8043-33CDD26C4672](https://user-images.githubusercontent.com/54523503/218011411-2f910711-2f79-4707-b2eb-8dae54ff2f91.jpeg)

**Comment by math-GH** [comment]
Hi,
Please give us more information to your setup:
- FreshRSS version?
- Operating system: Android/iOS?
- Browser?

Could you please test also demo.freshrss.org?

**Comment by boncuk10** [comment]
Hi,

it’s:

FreshRSS 1.20.2
iOS 16.3 , iPhone 13 mini
Safari 

it’s also the same on the demo website:

![6AB6120C-6946-4B9B-B964-628E7AFF70D8](https://user-images.githubusercontent.com/54523503/218045612-f53d1c6d-3161-45b2-928d-e7b0b1e7ed64.png)

**Comment by Frenzie** [comment]
It might need this (which I don't think can be done via CSS unfortunately).
```
<meta name="theme-color" media="(prefers-color-scheme: light)" content="cyan" />
<meta name="theme-color" media="(prefers-color-scheme: dark)" content="black" />
```
<https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color>

**Comment by math-GH** [comment]
@boncuk10 could you please have a look into this PR, if possible? #5105
