### ISSUE TITLE
Change actualize script visibility?

### ISSUE THREAD

**Issue by aledeg** [FreshRSS/FreshRSS#509]
Yesterday when I was writing documentation, I was trying to refresh the feeds with a curl command. Unfortunately, the script is not reachable and using the script from the web interface is impossible.
It would be nice to be able to call the actualize script from anywhere for people who wants to automate the refresh process with no access to the cron tasks.

Maybe a refactoring could be done to use only one method to refresh from the interface or from the command line.

**Comment by saurabhgayali** [comment]
My hosting service doesnt allow '?' symbol in the cron jobs list.
and I am not allowed curl.

What should I do.
Currently I refresh it daily once.
I want to automate the process every hour

**Comment by Alkarex** [comment]
@saurabhgayali You could try making an URL rewrite in Apache http://httpd.apache.org/docs/trunk/rewrite/
