### ISSUE TITLE
Add a filter option

### ISSUE THREAD

**Issue by aledeg** [FreshRSS/FreshRSS#511]
As we have support for intitle, inurl and author, it could be neat to support for search by date.
It would support different key words with different options. For example:
- date keyword that support anything that can be converted to a date according to the php documentation  (SQL equivalent: =)
- date-range keyword that support two dates between square brackets with the same format as the date keyword (SQL equivalent: BETWEEN)
- date-list keyword that support a list of individual dates with the same format as the date keyword (SQL equivalent: IN)

**Comment by Alkarex** [comment]
`date:` has been implemented for a while (0.7.2). Let's close this issue and reopen more specific ones as needed

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/issues/1189

**Comment by Alkarex** [comment]
Negative searches implemented in https://github.com/FreshRSS/FreshRSS/issues/1478
