### ISSUE TITLE
[Feature] sorting by the publication date of the feed articles

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#5114]
Hello, developer, do you have any plans to support sorting by the publication date of the feed articles or displaying the collection date of FreshRSS?
Whether the sorting of FreshRSS will be supported. The background settings are based on
1. Sort by the publication time of the feed article.
2. FreshRSS collection time.
Will these two sorting methods be supported? thank you

**Comment by math-GH** [comment]
hi, 
right now there are no concrete plans for it.
Similar feature requests are collected in the label "FR: sort articles": https://github.com/FreshRSS/FreshRSS/labels/FR%3A%20sort%20articles
