### ISSUE TITLE
Hello, developer, is FreshRSS planning to support Google's reCAPTCHA verification code?

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#5115]
Hello, developer, do you have any plans to support sorting by the publication date of the feed articles or displaying the collection date of FreshRSS?
Whether the sorting of FreshRSS will be supported. The background settings are based on
1. Sort by the publication time of the feed article.
2. FreshRSS collection time.
Will these two sorting methods be supported? thank you

**Comment by daffydock** [comment]
Hi. You copy/pasted the wrong text. Your text here is the same as #5114

**Comment by math-GH** [comment]
@ixiaoxiao please open a new ticket that describes it. This ticket has a duplicate content.
