### ISSUE TITLE
Hello, the developer's manual refresh and automatic refresh occasionally refresh the articles that have been marked as read!

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#5117]
Hello, developer, I use FreshRSS. The subscribed content is entirely in Chinese. Search the search engine Google and Bing for "refresh the articles you have read" to find FreshRSS users with the same problems as me.
The problem is that articles that have been marked as read often appear after I refresh the feed manually or regularly.
I sincerely hope that developers can test this problem and fix it! Thank you. I'm sorry to bother you. This problem has a great impact on your use. thank you!

**Comment by ixiaoxiao** [comment]
Add: This problem has been found in the v2ex forum for 20 years. For more information, developers can check the post entitled "FreshRSS automatic refresh problem, please help rss experts" on v2ex: [For the problem of automatic refreshing of FreshRSS, please ask rss experts for help](https://v2ex.com/t/719751) Thank you.

**Comment by Frenzie** [comment]
There are generally two reasons something might be marked as unread.

Presumably you already checked, but there's Settings → Reading → Mark updated articles as unread. I believe that's disabled by default, but perhaps it was enabled.

The second reason can't really be helped. That's if the same text is published with a different guid/permalink. A sample feed or sample feed content from two relevant points in time would be needed to say more.

**Comment by ghost** [comment]
After closing the "updated article as read" two days ago, there has been no problem. Thank you, good evening.

**Comment by aledeg** [comment]
Can we close this issue then?
