### ISSUE TITLE
[Feature] Support for 2FA

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#5118]
Hello, developer, because FreshRSS has no available verification code measures on login/registration and sending email verification code, my FreshRSS has recently been frantically tried to brute force cracking and registered account with script. Now I have closed my registration, but login is still being frantically brute force cracking.
I like that developers can join Google's reCAPTCHA or Cloudflare Turnstile verification code for human-machine verification of login/registration and email verification code to protect the account security and server security of FreshRSS. Thank you.

**Comment by Alkarex** [comment]
Feedback welcome for https://github.com/FreshRSS/FreshRSS/pull/5351
