### ISSUE TITLE
The feeds I have subscribed to often have these problems, and then it will be better after a period of time!

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#5126]
First question: cURL error 28: Failed to connect to nine-lie.com port 443: Connection timed out[ https://nine-lie.com/feed/ ]
Second question: cURL error 35: OpenSSL SSL_ connect: Connection reset by peer in connection to forbetty.com:443 [ https://forbetty.com/feed ]
Third question: cURL error 28: Operation timed out after 15000 milliseconds with 0 bytes received[ https://nine-lie.com/feed/ ]
Fourth question: cURL error 6: Could not resolve: seersu.me (Could not contact DNS servers)[ https://seersu.me/index.xml ]
The errors recorded in my logs are cURL error 28, cURL error 35, and cURL error 6.
Strangely, these problems will cause all messages after manual refresh, and such problems will always occur in automatic refresh. Very strange.

**Comment by math-GH** [comment]
closed, because the user is deleted now (ghost)
