### ISSUE TITLE
[BUG] Can't add feed https://www.gcores.com/rss

### ISSUE THREAD

**Issue by frishcat** [FreshRSS/FreshRSS#5127]
Hello fressRSS,

I can't add feed of `https://www.gcores.com/rss`

**When add, notification:**
The newsfeed could not be added. [Check FreshRSS logs](https://rss.mydomain.com/i/?a=logs) for details. You can try force adding by appending #force_feed to the URL

**logs:**
  | 2023-02-22 01:50:35 | Unknown error for feed [https://www.gcores.com/rss]
  | 2023-02-22 01:47:52 | Unknown error for feed [https://www.gcores.com/rss]

**Installation check**
All green, no error

**Test connection for the feed**(seems all right)

> curl -v https://www.gcores.com/rss
> *   Trying 60.205.211.246:443...
> * TCP_NODELAY set
> * Connected to www.gcores.com (60.205.211.246) port 443 (#0)
> * ALPN, offering h2
> * ALPN, offering http/1.1
> * successfully set certificate verify locations:
> *   CAfile: /etc/ssl/certs/ca-certificates.crt
>   CApath: /etc/ssl/certs
> * TLSv1.3 (OUT), TLS handshake, Client hello (1):
> * TLSv1.3 (IN), TLS handshake, Server hello (2):
> * TLSv1.2 (IN), TLS handshake, Certificate (11):
> * TLSv1.2 (IN), TLS handshake, Server key exchange (12):
> * TLSv1.2 (IN), TLS handshake, Server finished (14):
> * TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
> * TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
> * TLSv1.2 (OUT), TLS handshake, Finished (20):
> * TLSv1.2 (IN), TLS handshake, Finished (20):
> * SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
> * ALPN, server accepted to use http/1.1
> * Server certificate:
> *  subject: CN=*.gcores.com
> *  start date: Aug 23 09:04:42 2022 GMT
> *  expire date: Sep 22 09:04:41 2023 GMT
> *  subjectAltName: host "www.gcores.com" matched cert's "*.gcores.com"
> *  issuer: C=CN; O=Beijing Xinchacha Credit Management Co., Ltd.; CN=Xcc Trust DV SSL CA
> *  SSL certificate verify ok.
> > GET /rss HTTP/1.1
> > Host: www.gcores.com
> > User-Agent: curl/7.68.0
> > Accept: */*

**Environment information (please complete the following information):**
- FreshRSS version: 1.20.2

**Additional context**
- In reeder app from my freshRSS server, it also can't subscription
- But in reeder app without my freshRSS server ( use reeder directly ), it add subscription all good

Thanks !

**Comment by Frenzie** [comment]
I can't confirm; it adds for me. Do the logs say anything else?

![image](https://user-images.githubusercontent.com/202757/220597917-a80d4e6b-3f84-468b-81c2-2250ffb48138.png)

**Comment by frishcat** [comment]
Hi Frenzie,

Logs please see below.

Today I tried this on my other server, It works .
And I try `curl` the feed in my CLI, It really lag. So I think maybe it caused by a connection problem, some timeout issue.

Thanks 🙏

> 

  | 2023-02-22 12:11:58 | Unknown error for feed [https://www.gcores.com/rss]
-- | -- | --
  | 2023-02-22 12:11:57 | Unknown error for feed [https://www.gcores.com/rss]
  | 2023-02-22 12:11:55 | Unknown error for feed [https://www.gcores.com/rss]
  | 2023-02-22 12:11:53 | Unknown error for feed [https://www.gcores.com/rss]
  | 2023-02-22 12:11:51 | Unknown error for feed [https://www.gcores.com/rss]
  | 2023-02-22 12:11:50 | Unknown error for feed [https://www.gcores.com/rss]
  | 2023-02-22 12:11:48 | Unknown error for feed [https://www.gcores.com/rss]
  | 2023-02-22 12:11:46 | Unknown error for feed [https://www.gcores.com/rss]
  | 2023-02-22 12:11:44 | Unknown error for feed [https://www.gcores.com/rss]
  | 2023-02-22 12:11:43 | Unknown error for feed [https://www.gcores.com/rss]
  | 2023-02-22 12:11:41 | Unknown error for feed [https://www.gcores.com/rss]
  | 2023-02-22 12:11:40 | Unknown error for feed [https://www.gcores.com/rss]
  | 2023-02-22 12:11:37 | Unknown error for feed [https://www.gcores.com/rss]
  | 2023-02-22 12:11:34 | cURL error 28: Operation timed out after 15000 milliseconds with 0 out of 0 bytes received [https://www.gcores.com/rss]

**Comment by Frenzie** [comment]
Is it giving an error every second or two due to you specifically repeating the action? Otherwise that seems a bit weird.

I suppose you could try setting a higher timeout, but it sounds like they may be dropping your packets in the firewall?

**Comment by Alkarex** [comment]
Indeed, as Frenzy is saying, try to increase the timeout in the feed's settings, and avoid refreshing too often

**Comment by math-GH** [comment]
(for me it works fine too)

**Comment by frishcat** [comment]
> Is it giving an error every second or two due to you specifically repeating the action? Otherwise that seems a bit weird.
> 
> I suppose you could try setting a higher timeout, but it sounds like they may be dropping your packets in the firewall?

Hi Frenzie. after setting a higher timeout, it finally works. Thank you so much. This issue can be closed. :)
