### ISSUE TITLE
"Error during context user init!" and "Row size too large."

### ISSUE THREAD

**Issue by realex64** [FreshRSS/FreshRSS#5128]
Hi folks,

i have a clean fresh install of freshrss on ubuntu 22.04 (no docker).  There is a mysql catabase called freshrss, a database user, also called freshrss.

```cd /usr/share 
git clone https://github.com/FreshRSS/FreshRSS.git freshrss
cd freshrss
cli/access-permissions.sh
ln -s /usr/share/freshrss/p /var/www
```

In my browser (i tested firefox and chromium) i can reach the initial configuration page, everything is green, no warning.

After the last step for completing installation, the browser only show "Error during context user init!"

There is no log for my default_user, but a user called "\_" have this entry in /usr/share/freshrss/data/users/_/log.txt:

`[Wed, 22 Feb 2023 10:49:54 +0100] [error] --- FreshRSS_UserDAO::createUser error: ["42000",1118,"Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs"]
`

If i try to add my default_user with cli, a new line is added in /usr/share/freshrss/data/users/_/log.txt. Same as above.

Please let me know any hints to resolve my problem.

Thank you very much.

Kind regard,

Alex

**Comment by Alkarex** [comment]
Hello,
Hum, do you have anything special in the username (special characters or too long username)? We should filter out those cases but maybe one case has been forgotten.
You are not importing anything during the creation, are you?

**Comment by realex64** [comment]
Hi Alkarex,

thank you for your advice.

I did again a clean install with clean database.

In step 4 i used "garfield" for user name and "garfield123" for password.

I checked the log file for user "_" and there is the same error message.

And no, i did not importing anything...


Kind regards


Alex

**Comment by Alkarex** [comment]
Could you please try this patch? https://github.com/FreshRSS/FreshRSS/pull/5132

**Comment by realex64** [comment]
Hi Alkarex,

your patch solved the problem.  Now installation works as expected.

Thank you for this quick help and the patching!

Kind regards

Alex
