### ISSUE TITLE
Is the documentation for `frss:xPathItemTitle` correct?

### ISSUE THREAD

**Issue by mincerafter42** [FreshRSS/FreshRSS#5133]
In [the FreshRSS OPML extension documentation](https://github.com/FreshRSS/FreshRSS/blob/edge/docs/en/developers/OPML.md), the `frss:xPathItemTitle` attribute is specified as being the "XPath expression for extracting the feed title from the source page." Was "source page" meant to be "item context" like most of the other XPath attributes defined there?  
The example given for `frss:xPathItemTitle`'s value is `descendant::h2`, which, if it really were relative to the source page, would return *every* `<h2>` element on the source page, which does not seem like the most helpful example.

**Comment by Frenzie** [comment]
> Was "source page" meant to be "item context" like most of the other XPath attributes defined there?

That wouldn't make any sense. ;-)

Presumably it's merely an oversight and it'd need a `[1]` at the end or something, assuming you mean you're writing this because you saw a crazy long string as a result.

**Comment by mincerafter42** [comment]
> assuming you mean you're writing this because you saw a crazy long string as a result.

No, I didn't check how it was implemented in FreshRSS itself; I'm just pointing out the description and example don't seem consistent with each other. It could indeed be that the example should be changed rather than the description.

**Comment by Alkarex** [comment]
Indeed @mincerafter42 , `xPathItemTitle` is from the item context. Would you feel like sending a PR with the documentation fix?

**Comment by Frenzie** [comment]
@Alkarex But how could you possibly get the *feed* title from the *item* context?

**Comment by Frenzie** [comment]
That's what I mean by it not making any sense to even propose as the intended meaning.

**Comment by Alkarex** [comment]
`frss:xPathItemTitle`: XPath expression for extracting the item’s title from the item context.

**Comment by Frenzie** [comment]
Item title being the operative word. The rest follows logically. ;-)

**Comment by mincerafter42** [comment]
> Would you feel like sending a PR with the documentation fix?

documentation fix in #5140.
