### ISSUE TITLE
GUI Configuration Complains About Not Having Write Permissions

### ISSUE THREAD

**Issue by jsphnecclia** [FreshRSS/FreshRSS#5134]
Unable to reach step 2 of the configuration process, the GUI says the several files and directories do not have group write permissions for group www-data. See image here:

![Screenshot 2023-02-23 at 1 04 01 AM](https://user-images.githubusercontent.com/51343659/220840990-88dc37e9-e466-48e2-8a00-0501774bb9f7.png)

 
However, the TMP directory is not among the directories whose group write permissions are ignored. It appears the difference might be in the use of touch instead of is_writable? I don't know. These are the permissions:

![Screenshot 2023-02-23 at 1 15 33 AM](https://user-images.githubusercontent.com/51343659/220841568-94703b00-cb88-48d3-a61b-bffe26f1ee8e.png)

**Comment by math-GH** [comment]
Not always is the 'vistor' user the same like the admin/FTP/SSH user

**Comment by jsphnecclia** [comment]
Im not sure what you mean. What would the visitor user be if not www-data? Should I change the user (or group)? or should I chmod o=rw ?

**Comment by Alkarex** [comment]
Please tell more about your setup: OS, type of storage, how you deployed and installed FreshRSS, versions...

**Comment by jsphnecclia** [comment]
Arch Linux, postgres, I followed the general installation (https://freshrss.github.io/FreshRSS/en/admins/03_Installation.html) with some help from "Installation on Debian 9/Ubuntu 16.04", running nginx. Let me know if you need to see any specific configs or logs!

I think Math-GH's solution seems to be what would fix my problem, but I dont fully understood what was meant. Do I need to have a dedicated freshrss user? And how would I go about setting that up?

**Comment by Alkarex** [comment]
Could you try to run `./cli/access-permissions.sh` (first available in our current edge version of FreshRSS)

**Comment by jsphnecclia** [comment]
maybe this might help: I dont think I have the edge version, however I do see the access-permissions.sh script. However, my FreshRSS folder is in /usr/share/FreshRSS, while in /srv/http/ I only have a link to p.

I ran the ./cli/access-permissions.sh, it did not complain, however, it also didn't fix the issue. It  appears the same as in my previous screenshots.

**Comment by jsphnecclia** [comment]
> Not always is the 'vistor' user the same like the admin/FTP/SSH user

What do you mean by this?

**Comment by jsphnecclia** [comment]
> However, the TMP directory is not among the directories whose group write permissions are ignored. It appears the difference might be in the use of touch instead of is_writable? I don't know.

This wasnt the problem -- I replaced the cases of `touch(... . '/index.html')` with `is_writable(...)`, and I'm receiving the same errors

**Comment by math-GH** [comment]
Let me try to explain it with my situation:

This is a screen shot from my FTP application:

![grafik](https://user-images.githubusercontent.com/1645099/227803487-5c80df31-73aa-449f-89c8-05a2120f2d7d.png)

Have a look into the last column `Owner / Group`.
When I upload the files via FTP, the `Owner` of the file is the FTP user (`ftp2xxxxxx9`).
I had to change the owner to the "server" user (`10xxxxx5`). My web hoster has a GUI to change the user.
Both users are member of the same group (`site10xxxxxx5`)

I hope it helps
