### ISSUE TITLE
[BUG] constants.local.php - Warning: Constant PUBLIC_TO_INDEX_PATH already defined in .\constants.local.php

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#5143]
**Describe the bug**
I created the file `./constants.local.php` (as described in `./constants.php`)

content of the file:
```
<?php
define('PUBLIC_TO_INDEX_PATH', '/x');
```

Warning message:
`Warning: Constant PUBLIC_TO_INDEX_PATH already defined in ....\constants.local.php on line 2`

**Environment information (please complete the following information):**
- FreshRSS version: 1.21.0-dev

**Comment by Alkarex** [comment]
That constant is not in the list of customisable ones:

https://github.com/FreshRSS/FreshRSS/blob/67647586581c9e706013a4b7692261dc6bcf0831/constants.php#L4-L22

**Comment by math-GH** [comment]
oh, I misunderstand it. Thanks.
