### ISSUE TITLE
[BUG] Not actualizing feed for "Der Postillon"

### ISSUE THREAD

**Issue by causa-prima** [FreshRSS/FreshRSS#5149]
**Describe the bug**
I am migrating from TTRSS, and am not able to get the feed for "[Der Postillion](https://www.der-postillon.com/)" (German "The Onion") to actualize. They do not provide the feed themselves, but use [follow.it](https://follow.it). The first sync works fine, but afterwards, no new articles are shown in FreshRSS and there is no indication in the log that something went wrong.

All other feeds shown new articles.

**To Reproduce**
1. Add a subscription for "Der Postillon" (https://follow.it/der-postillon2)
2. Wait for the initial sync.
3. Wait for new articles to be posted and the actualization to trigger.

**Expected behavior**
All new articles should be shown.

**Screenshots**
No new articles are shown.

**Environment information (please complete the following information):**
- Device: Desktop & Android
- OS: FreshRSS is installed on a Shared Hoster that uses CentOS
- Browser: Firefox (Desktop), Vivaldi (Android)
- FreshRSS version: 1.20.2
- Database version: MariaDB 10.6
- PHP version: PHP 8.0.28
- Installation type: ?

**Additional context**
-

**Comment by Frenzie** [comment]
What kind of time period do you mean by afterwards?

**Comment by Frenzie** [comment]
That is, if you mean up to 30 minutes or so that's simply the default minimum interval to avoid too many requests.

**Comment by causa-prima** [comment]
They post multiple new articles per day. I've waited for days already, and while all other feeds get updates, this one doesn't. I still have TTRSS running to compare, and the new articles show up there.

**Comment by Frenzie** [comment]
I'll see what happens tomorrow morning.

**Comment by math-GH** [comment]
I do not have any issues with this feed. I update it regularly hourly

**Comment by causa-prima** [comment]
Okay, then it is probably a misconfiguration on my side, though I don't think I did anything special. Here are the feeds' settings as well as the archiving settings - please let me know what I need to change or what else I should check:
![grafik](https://user-images.githubusercontent.com/2970704/222063839-11647773-adb4-4772-829c-89b57137978d.png)
![grafik](https://user-images.githubusercontent.com/2970704/222063987-97e4f9be-cd4e-4484-806c-12218b1bd902.png)

**Comment by Frenzie** [comment]
Taking a look just now I notied the feed says it hasn't changed since last week: **last-modified: Thu, 23 Feb 2023 13:00:14 GMT**. Presumably the rest follows logically. No change means the cached response is still up to date with no need to refresh it.

```
$ curl -I https://follow.it/der-postillon2
HTTP/2 200 
date: Wed, 01 Mar 2023 12:23:15 GMT
content-type: text/xml;charset=UTF-8
vary: Accept-Encoding
vary: Accept-Encoding
last-modified: Thu, 23 Feb 2023 13:00:14 GMT
x-frame-options: DENY
content-security-policy: frame-ancestors 'self';
x-content-type-options: nosniff
strict-transport-security: max-age=600; includeSubdomains;
cf-cache-status: DYNAMIC
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=t1Asz%2B8lZPuR1KPBfkt3fRRYXWsPnbTx0I%2BcArbnGMdYq09HHWD5e9%2F2IoJCju%2B8NoU7TgHhdEHWde5%2FGvCuGmCglMFvQs5DtT8%2FTO%2BUCy36y6Wv1jwb3NM%2BCHTKUCPE8UAKTu0ngQ%3D%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
server: cloudflare
cf-ray: 7a115ec2e9fd83e3-BRU
```

**Comment by math-GH** [comment]
> I do not have any issues with this feed. I update it regularly hourly

I see, that I have subscribed an "older" feed link for this page: https://www.blogger.com/feeds/746298260979647434/posts/default?redirect=false
Now the RSS feed was replaced with the follow.it service.

**Comment by Frenzie** [comment]
Yup, that one says last modified earlier today (presumably at the same time as the latest article), **last-modified: Wed, 01 Mar 2023 13:25:22 GMT**.
```
$ curl -I https://www.blogger.com/feeds/746298260979647434/posts/default?redirect=false
HTTP/2 200 
p3p: CP="This is not a P3P policy! See https://www.google.com/support/accounts/bin/answer.py?hl=en&answer=151657 for more info."
content-security-policy: script-src   'self' *.google.com *.google-analytics.com 'unsafe-inline'   'unsafe-eval' *.gstatic.com *.googlesyndication.com *.blogger.com   *.googleapis.com uds.googleusercontent.com https://s.ytimg.com   https://i18n-cloud.appspot.com   https://www.youtube.com   www-onepick-opensocial.googleusercontent.com   www-bloggervideo-opensocial.googleusercontent.com   www-blogger-opensocial.googleusercontent.com https://www.blogblog.com; report-uri /cspreport
cross-origin-resource-policy: cross-origin
content-type: application/atom+xml; charset=UTF-8
expires: Wed, 01 Mar 2023 15:08:13 GMT
date: Wed, 01 Mar 2023 15:08:13 GMT
cache-control: private, max-age=0, must-revalidate, no-transform
vary: Accept, X-GData-Authorization, GData-Version
gdata-version: 1.0
last-modified: Wed, 01 Mar 2023 13:25:22 GMT
content-length: 0
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
server: GSE
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
```

**Comment by causa-prima** [comment]
Just to point out again: TTRSS doesn't seem to have the same problem. My config there:
![grafik](https://user-images.githubusercontent.com/2970704/222184873-c992e33c-e4ce-4385-bb41-361f5477569d.png)
(Note that the differing URL doesn't matter. I have a subscription in FreshRSS with that URL as well, with the same behavior: no updates).

Either TTRSS has implemented a workaround (for follow.it or a more general case), or there is a bug in FreshRSS that causes this.

**Comment by Frenzie** [comment]
As I stated above, the feed explicitly says it was last updated a week ago when asked. So that could be either missing functionality (a "workaround") or a bug on the TTRSS side. Either way, it's the feed that's borked.

**Comment by Frenzie** [comment]
@Alkarex That being said, does it make sense to keep the cache for more than, I don't know, 24 or 48 hours?

Edit: or perhaps even as low as 1 or 2 hours.

**Comment by causa-prima** [comment]
Okay, got it, the feed is borked, so it's not a bug in FreshRSS. I now solved it by using the URL that @math-GH uses.

**Comment by Frenzie** [comment]
Yup, basically SimplePie does something like this:

```
$ curl -I --header 'If-Modified-Since: Thu, 23 Feb 2023 13:00:14 GMT' https://follow.it/der-postillon2
HTTP/2 304 
date: Thu, 02 Mar 2023 08:36:25 GMT
last-modified: Thu, 23 Feb 2023 13:00:14 GMT
etag: "63f7635e-6d8b"
x-frame-options: DENY
content-security-policy: frame-ancestors 'self';
x-content-type-options: nosniff
strict-transport-security: max-age=600; includeSubdomains;
cf-cache-status: DYNAMIC
[…]
```

That 304 response there from the server means `Not Modified`.

Edit:

Specifically, here:
https://github.com/FreshRSS/FreshRSS/blob/4f957dfc4c38c418e5b46a2dc8d34a9bdabb31db/lib/SimplePie/SimplePie.php#L1691-L1714

**Comment by Alkarex** [comment]
For the record, last time I checked TT-RSS (many years ago), it had very little support for network optimisations and caching, meaning that it is often wasting resources.
