### ISSUE TITLE
[BUG] Open "Subscription management" writes nothing in log.txt

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#5155]
**Describe the bug**
Open "Subscription management" writes nothing in log.txt, but changes the "last changed" date.

![grafik](https://user-images.githubusercontent.com/1645099/222695369-956002ad-644b-4852-b76b-d095152fa096.png)

![grafik](https://user-images.githubusercontent.com/1645099/222695839-ee6fa480-b5a0-4bbc-acd5-a97660f24e40.png)

**To Reproduce**
1. Open "Subscription management"
2. go to \data\users\[username]\
3. see the last change date of the file `log.txt`
4. open the `log.txt`
5. see that there is no new entry

**Expected behavior**
Is there a log entry missed?
Or: do not change the last changed date if there is nothing to add.

**Environment information (please complete the following information):**
- FreshRSS version: 1.21.0-dev
- Installation type: XAMP on Windows10

**Comment by Alkarex** [comment]
That is expected. Changing modification date is used for some actions for which we likely will want to invalidate the HTTP cache

**Comment by Alkarex** [comment]
Hum sorry, the user's `config.php` is supposed to be touched by design. We need to check what touches `log.txt`

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/blob/d2cc5ad3f8e4e01168fd52735ca18071edb20091/lib/lib_rss.php#L547-L557

https://github.com/FreshRSS/FreshRSS/blob/d2cc5ad3f8e4e01168fd52735ca18071edb20091/p/i/index.php#L37-L39
