### ISSUE TITLE
[BUG] Fatal error: Uncaught Error: Call to a member function bindParam() on bool

### ISSUE THREAD

**Issue by bnjbvr** [FreshRSS/FreshRSS#5156]
**Describe the bug**

The actualize_script.php fails with an hard error:

```
PHP Fatal error:  Uncaught Error: Call to a member function bindParam() on bool in /var/www/FreshRSS/app/Models/FeedDAO.php:438
Stack trace:
#0 /var/www/FreshRSS/app/Controllers/feedController.php(522): FreshRSS_FeedDAO->updateCachedValues()
#1 /var/www/FreshRSS/app/Controllers/feedController.php(647): FreshRSS_feed_Controller::actualizeFeed()
#2 /var/www/FreshRSS/lib/Minz/Dispatcher.php(119): FreshRSS_feed_Controller->actualizeAction()
#3 /var/www/FreshRSS/lib/Minz/Dispatcher.php(48): Minz_Dispatcher->launchAction()
#4 /var/www/FreshRSS/lib/Minz/FrontController.php(58): Minz_Dispatcher->run()
#5 /var/www/FreshRSS/app/actualize_script.php(83): Minz_FrontController->run()
#6 {main}
  thrown in /var/www/FreshRSS/app/Models/FeedDAO.php on line 438
```

**To Reproduce**

I'm not too sure, but I think this happens when parsing the following feed, because the error shows up everytime _after_ parsing this feed, in the `actualize_script.php` output: https://www.cisa.gov/cybersecurity-advisories/analysis-reports.xml

---

**Environment information (please complete the following information):**
- Device: [e.g. iPhone6] n/a
- OS: [e.g. Ubuntu 20.04] latest stable Ubuntu
- Browser: [e.g. Firefox 86] n/a
- FreshRSS version: [e.g. 1.17.1] 1.20.2
- Database version: [e.g. Mysql 5.7] I think Postgres, not so sure which version
- PHP version: [e.g. PHP 7.4] 7.4.33
- Installation type: [e.g. Yunohost] Docker

**Additional context**
Thanks for all the hard work here 😊

**Comment by Frenzie** [comment]
Could be similar to #4822

**Comment by Alkarex** [comment]
Hello @bnjbvr 
What Docker image are you using, more precisely?
I have made a fix, which should provide a better error message https://github.com/FreshRSS/FreshRSS/pull/5158

**Comment by bnjbvr** [comment]
I'm using the "official" docker image `freshrss/freshrss` (default tag), with id `16c4280b8b1d`.

**Comment by Alkarex** [comment]
I have made a special test image for this issue. Could you try the image `freshrss/freshrss:5156` ?

**Comment by Alkarex** [comment]
The fix is now available in `freshrss/freshrss:edge`. Please give it a try. You are supposed to get a better error message, which should help finding the root cause

**Comment by bnjbvr** [comment]
Thanks! I've set up the 5156 image yesterday evening, so I should get a better message on the next failure.

**Comment by bnjbvr** [comment]
I've restarted the feeds fetching manually, and I'm now seeing lots of `Mysql server has gone away`. Apparently I'm using MySQL and not Postgres as I hoped :/. Is there anything that FreshRSS can do to avoid that error? https://dev.mysql.com/doc/refman/8.0/en/gone-away.html suggests it's possible to ping mysql to not close the connection. In the meanwhile, I'll look into tweaking the mysql settings to disable timeouts or raise the thresholds.

Also we're using Mysql 5.7; looking into upgrading to latest Mysql instead.

**Comment by Alkarex** [comment]
Let's continue in a new issue https://github.com/FreshRSS/FreshRSS/issues/5159
We should try to find a fix, but just for the record, FreshRSS has also built-in support for SQLite, which works fine and with excellent performance for most cases
