### ISSUE TITLE
Update process git error

### ISSUE THREAD

**Issue by zero77** [FreshRSS/FreshRSS#5165]
**Describe the bug**
Before 1.21.0 stable release the dev updates worked correctly now they fail to update.
After clicking apply the following error is displayed and the update fails.

**To Reproduce**
1. Go to settings
2. Click on Apply under updates
3. Updates fail and show an error message

**Expected behavior**

**Screenshots**

![Screenshot](https://user-images.githubusercontent.com/16563034/222966699-343b165e-317c-4a3b-adfc-6cef3dda6b30.png)

**Environment information (please complete the following information):**
- Device: Firefox for Linux
- OS: Debian 11
- Browser: Firefox 102.8.0
- FreshRSS version: 1.21.0-dev
- Database version: [e.g. Mysql 5.7]
- PHP version: 7.4.33
- Installation type: Apache

**Additional context**

**Comment by Alkarex** [comment]
Could you please provide the following information from your FreshRSS directory?

```sh
git remote -v
git status
ls -alh .git
```

The most likely is a write access problem to the .git repository

**Comment by zero77** [comment]
@Alkarex 
Thanks for the suggestion, i have updated the permissions of the FreshRSS directory and now the update works.
