### ISSUE TITLE
Adding feed fails with curl error 28

### ISSUE THREAD

**Issue by wdaniel** [FreshRSS/FreshRSS#5167]
Trying to add "https://acoup.blog/feed/" 

Error message: "The newsfeed could not be added. [Check FreshRSS logs](https://feeds.wdaniel.de/i/?a=logs) for details. You can try force adding by appending #force_feed to the URL."

Log has: cURL error 28: Failed to connect to acoup.blog port 443: Connection timed out [https://acoup.blog/feed/]

adding #force_feed does not change behaviour

curl -v "https://acoup.blog/feed/"  >feed.txt 2>&1         works ok
feed.txt is attached
[feed.txt](https://github.com/FreshRSS/FreshRSS/files/10892398/feed.txt)

freshrss version 1.21.1-dev, installed via "update" menu item
Debian 11 (bullseye) on ARM (5.4.225-odroidxu4)
PHP 8.0.27
mysql  Ver 15.1 Distrib 10.5.18-MariaDB, for debian-linux-gnueabihf (armv8l)

**Comment by Alkarex** [comment]
This feed works for me. Try again in a couple of hours, potentially increasing the timeout in the advanced settings when adding the feed.

**Comment by wdaniel** [comment]
set "accept cookies" --> works now

Thanks for the quick response, @Alkarex
