### ISSUE TITLE
[BUG] Preview images from YouTube feeds no longer working after updating to 1.21

### ISSUE THREAD

**Issue by stefs** [FreshRSS/FreshRSS#5170]
**Describe the bug**
Preview images of YouTube videos thumbnails are not displayed anymore after updating from 1.20 to 1.21.0

**To Reproduce**
1. Add any YouTube feed, eg. `https://www.youtube.com/@tested`
2. Enable preview images in display settings in any format
3. View "article" list of the YouTube feed (video list)
4. No preview images are displayed

**Expected behavior**
The YouTube video thumbnails are displayed as preview images.

**Screenshots**
Most YouTube feeds look like this, no preview images
![broken in version 1.21](https://user-images.githubusercontent.com/7479956/222982663-3c0b4897-fb97-41c6-be46-cd378f4cd450.png)
For some YouTube feeds previews are still visible
![working in version 1.20](https://user-images.githubusercontent.com/7479956/222982660-77e9db16-0dbf-4b0f-a11c-f7dfa0b4c0aa.png)

**Environment information (please complete the following information):**
- Device: Desktop computer
- OS: Fedora Linux 37 (Workstation Edition)
- Browser: Firefox 110.0
- FreshRSS version: 1.21.0 (docker)
- Database version: Not sure, see [freshrss-docker-container-inspect.txt](https://github.com/FreshRSS/FreshRSS/files/10892835/freshrss-docker-container-inspect.txt)
- PHP version: Not sure, see [freshrss-docker-container-inspect.txt](https://github.com/FreshRSS/FreshRSS/files/10892835/freshrss-docker-container-inspect.txt)
- Installation type: Not sure, see [freshrss-docker-container-inspect.txt](https://github.com/FreshRSS/FreshRSS/files/10892835/freshrss-docker-container-inspect.txt)

**Additional context**
I upgraded the version like described [here](https://github.com/FreshRSS/FreshRSS/tree/edge/Docker#how-to-update) and then the images were no longer working for most feeds.
Let me know if you need any more info.

**Comment by math-GH** [comment]
it could be connected with this PR: #4944

**Comment by jessejoe** [comment]
Also noticed this after upgrading from 1.20.2 to 1.21. Thumbnails are missing from the Slickdeals RSS feed, example to reproduce - https://slickdeals.net/newsearch.php?mode=frontpage&searcharea=deals&searchin=first&rss=1

**Comment by andris155** [comment]
I hope this gets fixed at some point. This is a useful FreshRSS feature for those who follow YouTube channels with FreshRSS.

**Comment by stefs** [comment]
I'm also still on 1.20 because of this, but I understand it's all voluntary work.

**Comment by Alkarex** [comment]
Fixed in https://github.com/FreshRSS/FreshRSS/pull/5806
Any of you willing to test?

![image](https://github.com/FreshRSS/FreshRSS/assets/1008324/cb4f0e7e-068a-4ebf-92fc-37aa6625abaa)

**Comment by Alkarex** [comment]
Merged in our `edge` branch to ease testing

**Comment by math-GH** [comment]
Works fine for me

**Comment by andris155** [comment]
Works perfectly. Thank you!
