### ISSUE TITLE
[Feature] [Docker] Listening for IPv6 connections

### ISSUE THREAD

**Issue by Rufubi** [FreshRSS/FreshRSS#5178]
I noticed that the FreshRSS web server in Docker does not accept incoming connections via IPv6 by default.
This is because the web server currently only binds to `0.0.0.0:80`:
https://github.com/FreshRSS/FreshRSS/blob/1c502aaac2d53ca652e21c4e3ccd47362812626b/Docker/FreshRSS.Apache.conf#L2
I suggest adding the `Listen [::]:80` directive by default, so that the web server accepts both IPv4 and IPv6 connections.
(sorry if there is already this issue here, but I couldn't find it)

**Comment by Alkarex** [comment]
Hello,
You can override that with our LISTEN environment variable https://github.com/FreshRSS/FreshRSS/tree/edge/Docker#environment-variables
But in production, this is typically something that will be handled by a reverse proxy in front https://github.com/FreshRSS/FreshRSS/tree/edge/Docker#run-in-production

**Comment by Rufubi** [comment]
If I change `LISTEN` variable value to `[::]:80`, the web server will only listen to IPv6. Apache needs 2 `Listen` directives to make the double stack work. As I understand from the logic of entrypoint.sh, `Listen` changes, but you can't add another directive

**Comment by Alkarex** [comment]
> As I understand from the logic of entrypoint.sh, `Listen` changes, but you can't add another directive

Indeed. That could be something to be improved. PR welcome. Reference https://httpd.apache.org/docs/current/mod/mpm_common.html#listen

I tend to recall that there were some issues (maybe just some warnings in logs) with the default Apache `Listen`, but that was a long time ago https://github.com/FreshRSS/FreshRSS/pull/1813
Tests welcome on both our Debian and Alpine based Docker images for adding IPv6
