### ISSUE TITLE
Feeds do not update, error when running feeds actualization

### ISSUE THREAD

**Issue by panamayellow** [FreshRSS/FreshRSS#5179]
**Describe the bug**
When either automatic or manual feed actualization is attempted, feed(s) do not update and an error is written to tmp/FreshRSS.log

**To Reproduce**
1. In the webUI, click the "Update Feeds" button
2. <or> allow FreshRSS server to attempt a periodic feeds update
3. See error in tmp/FreshRSS.log:

BEGIN LOG ENTRIES>>

FreshRSS starting feeds actualization at 2023-03-07T12:30:00-08:00
FreshRSS actualize tom…
PHP Warning:  DOMDocument::loadXML(): Start tag expected, '<' not found in Entity, line: 1 in /app/www/lib/marienfressinaud/lib_opml/src/LibOpml/LibOpml.php on line 151
PHP Fatal error:  Uncaught Error: Call to a member function getAttribute() on null in /app/www/lib/marienfressinaud/lib_opml/src/LibOpml/LibOpml.php:175
Stack trace:
#0 /app/www/app/Services/ImportService.php(43): marienfressinaud\LibOpml\LibOpml->parseString()
#1 /app/www/app/Models/Category.php(198): FreshRSS_Import_Service->importOpml()
#2 /app/www/app/Controllers/categoryController.php(250): FreshRSS_Category->refreshDynamicOpml()
#3 /app/www/app/Controllers/feedController.php(652): FreshRSS_category_Controller::refreshDynamicOpmls()
#4 /app/www/lib/Minz/Dispatcher.php(119): FreshRSS_feed_Controller->actualizeAction()
#5 /app/www/lib/Minz/Dispatcher.php(48): Minz_Dispatcher->launchAction()
#6 /app/www/lib/Minz/FrontController.php(58): Minz_Dispatcher->run()
#7 /app/www/app/actualize_script.php(83): Minz_FrontController->run()
#8 {main}
  thrown in /app/www/lib/marienfressinaud/lib_opml/src/LibOpml/LibOpml.php on line 175
Results: 

<<END LOG ENTRIES

**Expected behavior**
Feeds are updated

**Screenshots**

**Environment information (please complete the following information):**
- Device: Synology DS918+ 
- OS: DSM 7.1.1
- Browser: Safari 16.3
- FreshRSS version: 1.21.0
- Database version: SQLite (version unknown)
- PHP version: 8.1.16 (zend engine v4.1.16)
- Installation type: Docker 20-10-3-1308 (Synology build)

**Additional context**

**Comment by Frenzie** [comment]
Do you happen to know which dynamic OPML feed you're following?

**Comment by panamayellow** [comment]
I don't (newby), how do I learn that?

**Comment by Frenzie** [comment]
Someone would've added it under `Subscription management` → `Add a feed` and it should be listed under subscription management.
![image](https://user-images.githubusercontent.com/202757/223559641-e47ba897-3f60-4aab-970c-6d78679287d3.png)

The error message is not the most helpful, maybe @marienfressinaud knows more about it, but my guess would be that the OPML in question is no longer returning valid XML.

**Comment by panamayellow** [comment]
No, I don’t. I am a newbie. How can I learn which dynamic OPML feed I am using?When in doubt, mumble.On Mar 7, 2023, at 1:31 PM, Frans de Jonge ***@***.***> wrote:﻿
Do you happen to know which dynamic OPML feed you're following?

**Comment by panamayellow** [comment]
Subscription Management -> Add looks like this:

￼
…no OPML listed

Do I have a broken FreshRSS Docker image, I wonder?

**Comment by panamayellow** [comment]
Thank you for your responses and help.

I’m just going to recreate the docler container using the freshrss/freshrss image.

Cheers and thanks again...

**Comment by marienfressinaud** [comment]
There is indeed a bug in the lib_opml, but I cannot reproduce it. It's easy to fix though (see https://framagit.org/marienfressinaud/lib_opml/-/commit/8479c63aad3deab20a45a1826e9fe73da2790ce8), but it would be nice to have the failing OPML. I'm wondering how `DOMDocument::loadXML` can generate a warning saying the XML is invalid (i.e. `Start tag expected, '<' not found in Entity, line: 1`) and still returning a `DOMDocument` :thinking: (I'm already testing the case where the OPML is empty btw).

**Comment by Frenzie** [comment]
@marienfressinaud Maybe it's only a warning?
