### ISSUE TITLE
[BUG] fever does not work as intended

### ISSUE THREAD

**Issue by seraphyn** [FreshRSS/FreshRSS#5183]
**Describe the bug**
I use Unread my feeds.
Since the last majorupdate the function mark all as read does not work anymore
On the webserver side the command is acknowledged with a HTTP code 200 and does not throw an error.
As soon as I do a refresh the unread items are present again.

**To Reproduce**
1. Go to a Folder with any feeds and unread articles in it
2. Mark the all as read
3. Refresh feeds again on the client
4. the unread items/acticles are here again

**Expected behavior**
Arcticles should be marked as read and do not come back as unread arcticles after refresh.

**Environment information (please complete the following information):**
- Device: iPhone OS 16.3.1 / iPad OS 16.3.1
- OS: Debian 11 Bullseye
- Browser: Not needed
- FreshRSS version: 1.21.0
- Database version: SQLite
- PHP version: PHP 8.0.28
- Installation type: manualy

<img width="1182" alt="Bildschirm­foto 2023-03-09 um 15 12 03" src="https://user-images.githubusercontent.com/140527/224051014-ab73129e-6639-49c6-94a1-c2cd408de04f.png">

**Additional context**
After copying the old fever.php from the last stable Release into /var/www/html/freshrss/p/api it works as intended again.

**Comment by Alkarex** [comment]
Hello and thanks for the bug report.
Do you observe other bugs, for instance when marking a single article as read, or a feed, or a category?
What platform are you running FreshRSS on? Is it maybe a 32-bit platform?

**Comment by seraphyn** [comment]
64Bit as platform with Debian ;)

It only happens when I use Fevers API.
If I use another reader, e.g. greader (Reeder on iOs), or Fiery Feeds ( iOS and iPadOS) directly with the API of FreshRSS the error does not occur.
Same for the Webfrontend. No errors here, too.

I have chosen other apps for the tests, which I do not normally use, in order to exclude the error.

Unfortunately, no error messages appear in the Apachelog.
Here the contact is always entered friendly with a code 200.

I have this behavior only since the upgrade to this major version. Here there was probably a change in the fever.php , which has this effect

**Comment by Alkarex** [comment]
Thanks. I just found the bug. PR coming in 5min

**Comment by Alkarex** [comment]
Would you be able to try this patch? https://github.com/FreshRSS/FreshRSS/pull/5185

**Comment by seraphyn** [comment]
Works like a charm now.
IMO we could close this Issue and have a working patch.

Thanks @Alkarex 

Stay healthy

**Comment by Alkarex** [comment]
Thanks for the feedback!
