### ISSUE TITLE
[Feature]Please make a XPath Example / https://status.office.com

### ISSUE THREAD

**Issue by PaddyPat** [FreshRSS/FreshRSS#5184]
Could you please make an XPATH Example for converting html page to rss feed in freshrss?

Example:
https://status.office.com

div.cardTitle
iframe

xpath:
.card

**Comment by Frenzie** [comment]
That's unlikely to be sanely possible. The site is JavaScript-based and requests numerous separate things to fill it up, for example:

* https://status.office.com/api/posts/mac
* https://status.office.com/api/posts/ppac
* https://status.office.com/api/posts/azure

Those then return a JSON response with some status info.
```json
{"Id":null,"AuthoredDateTime":"2023-03-09T17:31:00.6058424+00:00","InternalDateTime":"0001-01-01T00:00:00+00:00","LastUpdatedTime":"2023-03-09T17:31:00.6058424+00:00","Message":"No Azure issues detected at this time. For more details, please visit the link below.","Status":"Available"}
```

You could in principle scrape those links I gave and hope they won't change them tomorrow, I suppose.

**Comment by Alkarex** [comment]
The site offers some RSS feeds:

![image](https://user-images.githubusercontent.com/1008324/224115810-cee21e33-d19d-41cd-8f3b-2a1324cae403.png)

**Comment by Frenzie** [comment]
And in plain view too, lol. I didn't notice because that too is loaded in
through JS (plus it's not added in a way that the normal RSS symbol shows
up)..
