### ISSUE TITLE
Automatic refresh with PHP file

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#5190]
Hi,

I have a CRON (CRON on hosting, limited functions) that only accepts PHP files. I gives the PHP file, run time and saves.

Access to the actualize_script.php file is blocked, it returns:

> Forbidden
> You don't have permission to access this resource.

Is there any way to update the feeds through the PHP file?

**Comment by Alkarex** [comment]
Hello,
This is exactly what `app/actualize_script.php` does. The error seems to be specific to your hosting, and would require some debugging. For instance, you can try to make your own PHP file that does nothing, just to check how your permissions work.
