### ISSUE TITLE
docs: fix nginx configuration

### ISSUE THREAD

**Issue by witchcraze** [FreshRSS/FreshRSS#5193]
**Describe the bug**

I tried `Hosted in a subdirectory` type.
https://github.com/FreshRSS/FreshRSS/tree/edge/Docker#hosted-in-a-subdirectory

With using sample nginx configuration, apache will recieve request with `/freshrss/`

```
$ docker compose logs freshrss -f
freshrss  | [Sun Mar 12 13:30:50.843823 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.54 (Debian) configured -- resuming normal operations
freshrss  | [Sun Mar 12 13:30:50.843892 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
freshrss  | 122.26.52.129 - - [12/Mar/2023:13:30:52 +0900] "GET /freshrss/ HTTP/1.0" 404 196 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"
freshrss  | 122.26.52.129 - - [12/Mar/2023:13:30:52 +0900] "GET /freshrss/ HTTP/1.0" 404 196 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36"
```

**To Reproduce**
1.  apply https://github.com/FreshRSS/FreshRSS/tree/edge/Docker#hosted-in-a-subdirectory

**Expected behavior**

apache will recieve request with `/`

**Additional context**

Aftre updating format, It seems go well

As-Is
`proxy_pass http://freshrss;`
To-Be
`proxy_pass http://freshrss/;`

**Comment by Alkarex** [comment]
Hello,
Can you please send a PR?
