### ISSUE TITLE
Documenter Dockerfile

### ISSUE THREAD

**Issue by marienfressinaud** [FreshRSS/FreshRSS#520]
J'ai créé un Dockerfile pour les personnes qui utilisent Docker : 
- Le [dépôt Github](https://github.com/marienfressinaud/docker-freshrss/)
- Le [dépôt Docker](https://registry.hub.docker.com/u/marienfressinaud/freshrss/) (branché au dépôt Github)

Ça peut permettre de faciliter la mise en place d'un environnement de test. C'est ce que j'utilise personnellement.

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/issues/1579#issuecomment-308304843
