### ISSUE TITLE
[BUG] Images in enclosure in the Fever API

### ISSUE THREAD

**Issue by voidstern** [FreshRSS/FreshRSS#5209]
**Describe the bug**
The `html` field of articles in the Fever API had image enclosure attached to the article content, for feeds that had images as enclosures, but not in the content.

This is no longer the case for articles fetched after upgrading to 1.21.0, when syncing with the Fever API, but still works when syncing with the Google Reader API.

**To Reproduce**
- Refresh the feed on 1.21.0
- Sync with Fever API

**Expected behavior**
The article content should be the same in the FreshRSS and Google Reader APIs.

**Environment information (please complete the following information):**
- Example feed: https://www.digi24.ro/rss
- FreshRSS version: 1.21.0

**Additional context**
Fiery Feeds dev here - I'm going to switch to the Google Reader API soonish, if that is relevant for prioritisation :)

**Comment by Alkarex** [comment]
Thanks for the feedback. I will check.

And sounds good with Google Reader API! Get in touch if you would like any sparing.
In particular, please do read https://freshrss.github.io/FreshRSS/en/developers/06_GoogleReader_API.html#synchronisation-strategy about the synchronisation strategy

**Comment by voidstern** [comment]
Thanks, I have it already working. I'm mostly reusing my BazQux implementation with minor adjustments :)

**Comment by Alkarex** [comment]
Should be fixed with https://github.com/FreshRSS/FreshRSS/pull/5214
Tests welcome
