### ISSUE TITLE
[Question] Is running FreshRSS safe on a personal machine, and if so, how do I make it as secure as possible?

### ISSUE THREAD

**Issue by Opening-Button-8988** [FreshRSS/FreshRSS#5226]
I ran a private FreshRSS server last year for a while on Arch Linux. I have since moved to Fedora, and I'm looking to use FreshRSS again. I've been using a public server since then, but unfortunately their servers lost data recently.

I looked at Docker's documentation but I came across some warnings that warn against using Docker on a personal machine. Now, I was okay with this back on Arch but I have since become more strict with my desktop security and I want to make sure there are no holes. I will not be exposing it to the internet (intentionally), but I believe I could still make a mistake somewhere and I want to avoid that.

My question is: is deploying FreshRSS on a personal machine safe if you're not exposing it to the internet? Is there anything I need to know to make sure I keep it secure? 

I am behind a Protectli vault firewall, but my networking knowledge is still basic and I'm still learning. In the future I intend to dedicate a system to this sort of thing, and I'll be putting it on a separate isolated network, so this is just a temporary solution until I get that.

**Comment by Frenzie** [comment]
Hard to judge what they say if you don't link to what they say. ;-) But I'll point out there's no need to use Docker for anything.

**Comment by Opening-Button-8988** [comment]
@Frenzie Apologies, you're right. I can't exactly remember what it said but it was referring to namespaces and cfgroups or something along those lines.

I realize this was probably not the best place to ask this question as it can be answered by communities more generally related to self hosting and docker. Thanks!
