### ISSUE TITLE
[BUG] Unmask chars in OPML export

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#5240]
**Describe the bug**

I added some `"` in the feed settings. The chars are not masked in the OPML export

![grafik](https://user-images.githubusercontent.com/1645099/228634333-936ec7d5-19f5-4c64-ab6f-4ef93bd1f5fe.png)

**To Reproduce**
1. Go to feed settings
2. add `"` chars
3. save the settings
4. go to export page
5. export the OPML
6. see the OPML export file

**Expected behavior**
masked special chars

**Environment information (please complete the following information):**
- FreshRSS version: 1.21.1-dev

**Comment by Alkarex** [comment]
Looks all good to me. Please check raw XML text, not a styled rendering

**Comment by math-GH** [comment]
oh, you are right.... I appologize
