### ISSUE TITLE
[BUG] CSS selector behaves differently than browsers when <img src="..."> has line feeds

### ISSUE THREAD

**Issue by Dan-Q** [FreshRSS/FreshRSS#5241]
**Describe the bug**
When an `<img>`'s `src` attribute contains carriage return/line feed characters, browsers silently ignore these. However, when FreshRSS's CSS selector comes across them, it attempts to encode the CR/LF characters as encoded entities, which breaks the image URL. The result is an image that works when you view the page, but not in FreshRSS.

**To Reproduce**
1. Visit https://danq.me/wp-content/uploads/freshrss-css-selector-img-crlf-demo/ and see both listed pages ([1.html](https://danq.me/wp-content/uploads/freshrss-css-selector-img-crlf-demo/1.html) and [2.html](https://danq.me/wp-content/uploads/freshrss-css-selector-img-crlf-demo/2.html)): the pages appear correctly and the images load.
2. Subscribe to the RSS feed for these pages https://danq.me/wp-content/uploads/freshrss-css-selector-img-crlf-demo/rss.xml in FreshRSS. This feed only provides summary content in the description.
3. Set the "Article CSS Selector" to `#content`, which you would expect would make the content show in FreshRSS. Use "Reload Articles" to force a reload.
4. View the articles in FreshRSS and note that the images are "broken". Inspect the DOM to see that the encoded character `%0A` has been injected into the image URL in place of the line feed character.

Note that this is not an entirely-academic example. When subscribing to the Forward webcomic [using XPath as described here](https://danq.me/2023/03/28/forward-comic-freshrss-xpath/) this problem occurs because these images all have that problem. E.g. see http://forwardcomic.com/archive.php?num=258, view source, and search for `alt='Comic!'`.

**Expected behavior**
Carriage returns and line feeds should be ignored by the CSS selector and not converted into encoded entities.

**Screenshots**
![image](https://user-images.githubusercontent.com/53293/228657740-c73da202-5636-4bfe-baff-95bd95f87d0f.png)

**Environment information (please complete the following information):**
- Browser: Firefox 111.0.1
- FreshRSS version: 1.20.2

**Comment by Alkarex** [comment]
Hum, I cannot reproduce the bug in my test instance with FreshRSS 1.21.1-dev and the images are showing up just fine. I will give a shot tomorrow at 1.20.2.
Such subtleties might vary with platforms / PHP versions. Could you tell details about that?

**Comment by Dan-Q** [comment]
Interesting! This copy's running from the [linuxserver/freshrss](https://hub.docker.com/r/linuxserver/freshrss/) Docker image, so PHP 8.0.25 on Alpine. There was an update to the Docker image 7 days ago, so I just applied that... and the problem's fixed. So whatever it was, it wasn't your doing at all but something this container maintainer was doing.

I should switch to using `git` to stay up-to-date. Sorry for the false report! Closing issue.

**Comment by Alkarex** [comment]
Sounds good :-)
There are multiple way to use the latest code. Our git branch `edge` is a relatively stable rolling release. Examples of use:

1) The Docker images `freshrss/freshrss:edge` and `freshrss/freshrss:edge-alpine` are tracking that rolling release.
2) It is possible to indicate to Docker or Docker Compose to rebuild from git (pick `#edge`) https://github.com/FreshRSS/FreshRSS/blob/c9d5fe2da12cbc3a071ebf9a518afe2789bb3d61/Docker/freshrss/docker-compose.yml#L12-L15
3) You can mount the git source code in a Docker image, like we do for development https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md#development-mode
4) Without Docker, just a normal git deployment in e.g. Apache, and in this case, it is even possible to use to built-in Web-based auto-update
