### ISSUE TITLE
[BUG] Instance update base_url

### ISSUE THREAD

**Issue by TicTac9k1** [FreshRSS/FreshRSS#5246]
I migrated my dockerized FreshRSS instance, migration works fine but the base_url still points to the server where it was initially configured on

Migrate docker data to new server and run the instance on a new server

**Expected behavior**
base_url recognizing that it has been changed or a way to configure base_url from the webpage

**Comment by Alkarex** [comment]
> way to configure base_url from the webpage

We should indeed offer this option

**Comment by samc1213** [comment]
I am going to try to take this one
