### ISSUE TITLE
[Feature] bouton partage pour toustes /  Share button for all

### ISSUE THREAD

**Issue by filougeeknick** [FreshRSS/FreshRSS#5248]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I’m always frustrated when […]

FR : Le bouton partage n'est pas visible en non connecté
En utilisation Planet le fait que les lecteurs et lectrices puissent aussi  partager les articles serait un plus

The share button is not visible when not connected
In use Planet the fact that readers can also share articles would be a plus

**Describe the solution you’d like**

FR : Rendre les partages via les réseaux asociaux possible par tous et toutes.

Make sharing via asocial networks possible by all.

**Describe alternatives you’ve considered**
A clear and concise description of any alternative solutions or features you’ve considered.
I don't now
**Additional context**

**Comment by math-GH** [comment]
I do not understand the point. You can configure the sharing services.

**Comment by filougeeknick** [comment]
Yes I made the setting here
![image](https://user-images.githubusercontent.com/6025686/229858834-3889bdde-3eb5-4022-a415-0bb8ba7d6fe3.png)
Here's the view when I'm logged in
![image](https://user-images.githubusercontent.com/6025686/229875005-cea57684-0a1c-47d0-abd7-5147e8534698.png)
Here's the view when I'm logged on
![image](https://user-images.githubusercontent.com/6025686/229875638-8d953be0-44d9-42ae-be18-5adf7f2fd820.png)

Of course this questioning only appears on a public FreshRss session (in Planet mode so)

**Comment by Alkarex** [comment]
Please try this PR https://github.com/FreshRSS/FreshRSS/pull/5261
We should review the security implications

**Comment by Alkarex** [comment]
@filougeeknick tests welcome for https://github.com/FreshRSS/FreshRSS/pull/5261
