### ISSUE TITLE
[Feature] Suprimer un article facilement /  Delete an article easily

### ISSUE THREAD

**Issue by filougeeknick** [FreshRSS/FreshRSS#5249]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I’m always frustrated when […]

FR : Certains articles du flux RSS ne sont pas pertinants

Some articles in the RSS feed are not relevant

**Describe the solution you’d like**
FR : Dans une utilisation Planet, il est bien de presenter un flux ciblé. 
Certains articles du flux RSS peuvent ne pas être pertinants.
Pouvoir les supprimer facilement directement sur l'article d'un clic serait très utile.

In a Planet use, it is good to present a targeted flow. 
Some articles in the RSS feed may not be relevant.
Being able to easily delete them directly on the article with one click would be very useful.

**Describe alternatives you’ve considered**
A clear and concise description of any alternative solutions or features you’ve considered.
FR : Peut-être contourné en empéchant la mise automatique en lu dans "Marquer les articles comme lus" puis basculer les articles a cacher pour les lecteurs, manuellement en lus

**Additional context**

**Comment by math-GH** [comment]
I would say, that deleting an article is not the use case of an RSS aggregator. 

You could mark this articles as read (f.e. via a filter) and just read your stream in the "show only unread articles" mode.

**Comment by filougeeknick** [comment]
Thanks for the reply
Yes indeed, in the case of public flow this way of doing things, does the job.
Once understood my request for functionality is no longer of interest.

FR : Merci pour  la réponse
Oui effectivement, dans le cas de flux publique cette façon de faire, fait le job.
Une fois compris, ma demande de fonctionalité n'a plus d'interest.
