### ISSUE TITLE
[BUG] Subscription to feeds not possible anymore

### ISSUE THREAD

**Issue by ddeimeke** [FreshRSS/FreshRSS#5252]
**Describe the bug**
It is not possible to add any new feeds.

**To Reproduce**
Try to add/subscribe a feed via subscription management.

**Expected behavior**
Feed should be subscribed.

**Screenshots**

**Environment information (please complete the following information):**
- Device: Arch Linux Desktop
- OS: Ubuntu 20.04.6
- Browser: Firefox 111.0.1
- FreshRSS version: Your current version of FreshRSS is 1.21.1-dev. 
- Database version: MariaDB 10.3.38
- PHP version: 7.4.3
- Installation type: Git Development Version

**Comment by Alkarex** [comment]
Thanks for the bug report. Fixed by https://github.com/FreshRSS/FreshRSS/pull/5253
