### ISSUE TITLE
[BUG] fever.api - Mark group as read does not mark items as read

### ISSUE THREAD

**Issue by MartinJura** [FreshRSS/FreshRSS#5255]
**Describe the bug**
I am using the Unread app, connected via Fever API to FreshRSS. Since the last update of FreshRSS to 1.21.0 the "mark all items as read" isn't working any more. After refresh of the item list in Unread all previous seen items are back again.

**To Reproduce**
1. Unread app: enter "Unread Articles"
2. Unread app: Scroll down to bottom, pull up to "mark all read"
3. Unread app: enter "Unread Articles" again
4. Unread app: pull down to refresh

**Expected behavior**
No more unread items

**Screenshots**
I enabled fever.log as described in the FreshRSS documentation for the API
An API request is sent to mark all items as read:
`"Unread%202/304009 CFNetwork/1406.0.4 Darwin/22.4.0: {"api":"","api_key":"xyz","as":"read","before":"1680539009","id":"0","mark":"group"}"`

**Environment information (please complete the following information):**
- Device: iPhone 11
- OS: iOS 16.4
- FreshRSS version: 1.21.0
- Database version: MariaDB 10.6.8
- PHP version: PHP 8.2- Installation type: [e.g. Yunohost]

**Additional context**
A single item is marked as read when read in Unread. This works as expected.

**Comment by Alkarex** [comment]
Hello,
Could you please try our edge version?

Fixed by https://github.com/FreshRSS/FreshRSS/pull/5185
Duplicate of https://github.com/FreshRSS/FreshRSS/issues/5183

**Comment by MartinJura** [comment]
Hello,

super, that's fixed it! Issue closed.

Thanks!
