### ISSUE TITLE
[BUG] Blast! The web server seems to be incorrectly configured for cookies required for PHP sessions! 

### ISSUE THREAD

**Issue by meditec-github** [FreshRSS/FreshRSS#5259]
**Describe the bug**
Want to try out FreshRSS and just installed it as Azure Container App using latest docker image
Citizen developer at work  - Need directions regarding correct configurations to fix it.

**To Reproduce**
After new login get the following error
Blast! The web server seems to be incorrectly configured for cookies required for PHP sessions! 
The app starts over with the installation. The initial installation check was successful.
Redoing intallation passes all checks, too but all previous work is lost.

**Screenshots**
![image](https://user-images.githubusercontent.com/129148082/229796764-95936ca4-b7c8-47b2-8a8c-78c628fb5dce.png)
![image](https://user-images.githubusercontent.com/129148082/229799163-352bcd19-71df-4a16-b168-210bd835564b.png)

**Environment information (please complete the following information):**
- Azure Container App
- SQLite database

**Comment by meditec-github** [comment]
Made a fresh installation on Azure Servive rather than Container App. Looks good now.

**Comment by meditec-github** [comment]
Made a fresh installation on Azure Servive rather than Container App. Looks good now.

**Comment by Alkarex** [comment]
Just for the record, the typical culprit for such a problem is a badly configured reverse proxy, which is not forwarding HTTP headers for cookies properly.
Cf. e.g. https://github.com/FreshRSS/FreshRSS/issues/3198#issuecomment-776529101

**Comment by hervehobbes** [comment]
Hello,
I have this error message but I'm not using reverse proxy, any idea?

**Comment by Alkarex** [comment]
@hervehobbes Please open a new issue, providing information about your setup, and we will find out 🎄
