### ISSUE TITLE
[BUG] postgres database has grown to 3.5 GB - (two users) 

### ISSUE THREAD

**Issue by karcio** [FreshRSS/FreshRSS#5262]
**Describe the bug**
Hi, there is nothing wrong with freshrss self hosted, but I noticed that my database is now 3.5 GB big. This instance using just two users. I wonder what can I do to fix this issue

**To Reproduce**
1. Go to 'freshrss instance'
2. Click on login as admin
3. Check database size

**Expected behavior**
Some workaround for database size

**Screenshots**

**Environment information (please complete the following information):**
- OS: Debian 11
- Browser: Firefox 111.0.1
- FreshRSS version: 1.21.0
- Database version: postgres 13
- PHP version: PHP 7.4
- Installation type: Self hosted

**Comment by Alkarex** [comment]
Try the following command for more details:

```sh
cd ./FreshRSS/
./cli/user-info.php --header -h
```

**Comment by karcio** [comment]
Hi @Alkarex 
I can find two location of file 

```
root@localhost:~# find / -name user-info.php 
/root/rss/rss/cli/user-info.php
/var/www/html/rss/cli/user-info.php
root@localhost:~# 
```
Server is running on `/var/www/html/rss/` with user www-data. 

When I try:
```
karcio@localhost:~$ php -f /var/www/html/rss/cli/user-info.php 
*       | karcio               | *     | *       | 1680690281                | 45776896        | 10         | 30         | 1201       | 17         | 4          | 1          | en    |           
        | lucyna               |       | *       | 1680644489                | 24412160        | 2          | 6          | 266        | 284        | 0          | 0          | en    |           
karcio@localhost:~$ 
```
when I try use `--header -h` this command does not work for me, 

If I try run exactly command you provide but in in this second location:
```
root@localhost:~# cd /root/rss/rss/
root@localhost:~/rss/rss# ./cli/user-info.php --header -h 
default | user                 | admin | enabled | last user activity        | space used      | categories | feeds      | reads      | unreads    | favourites | tags       | lang  | email     
root@localhost:~/rss/rss# 
```

**Comment by Alkarex** [comment]
If you have two paths, it is probably that you have installed FreshRSS in two locations.
If the CLI parameters do not work in one of the locations, it is probably an old version of FreshRSS.

It is indeed quite large for so few users with so few articles, except if you have extremely long articles. To know more, that would require a bit of investigation in your PostgreSQL database.

To ensure to have a clean database, you can take advantage of our `./cli/export-sqlite-for-user.php` to export the full data of a user and then import it again. This is also good for backups. You will also be able to see the size of the exported SQLite file.

And especially for so few feed and articles, you could also consider using our built-in SQLite instead of PostgreSQL.

**Comment by karcio** [comment]
Hi @Alkarex, I have a problem with run command you suggest. 

```
karcio@localhost:~$ sudo php -f /var/www/html/rss/cli/export-sqlite-for-user.php --user karcio --filename /tmp/db.backup
Error in argument 3, char 2: no argument for option -
Usage: php [options] [-f] <file> [--] [args...]
   php [options] -r <code> [--] [args...]
   php [options] [-B <begin_code>] -R <code> [-E <end_code>] [--] [args...]
   php [options] [-B <begin_code>] -F <file> [-E <end_code>] [--] [args...]
   php [options] -S <addr>:<port> [-t docroot] [router]
   php [options] -- [args...]
   php [options] -a
```

**Comment by karcio** [comment]
hi @Alkarex finally I was able to run command 
```
karcio@localhost:~$ sudo php /var/www/html/rss/cli/export-sqlite-for-user.php --user karcio --filename db.sqlite
FreshRSS exporting database to SQLite for user “karcio”…
Start SQL copy…
730/730
```

base is small 
```
karcio@localhost:~$ ls -lh
total 7.7M
-rw-r--r-- 1 root root 3.6M Apr  7 18:19 dbkarcio.sqlite
-rw-r--r-- 1 root root 588K Apr  7 18:19 dblucyna.sqlite
```

Could you please share information how can I switch from postgres to sqlite?

**Comment by math-GH** [comment]
What are your top3 database tables with that needs the most storage?

**Comment by Alkarex** [comment]
To migrate to SQLite:
1) Export each user using the `cli/export-sqlite-for-user.php` (already done)
2) For each user, e.g. "alice", place the export in `./FreshRSS/data/users/alice/db.sqlite` and make sure the Web server has read/write access to that file
3) In `./data/config.php`, in the `db` section, set `'type' => 'sqlite',`

**Comment by karcio** [comment]
Hi @Alkarex could you please describe section 2? `place export`

**Comment by Alkarex** [comment]
Just move the files you have exported to the users' respective folders, with the name `db.sqlite`

**Comment by karcio** [comment]
Just checked tables and looks like following are little big

```
freerssdb=# select pg_relation_size('freshrss_karcio_entry');
 pg_relation_size
------------------
           860160
(1 row)

freerssdb=# select pg_relation_size('freshrss_karcio_entrytmp');
 pg_relation_size
------------------
           204800
(1 row)

freerssdb=# select pg_relation_size('freshrss_lucyna_entry');
 pg_relation_size
------------------
         11493376
(1 row)

freerssdb=# select pg_relation_size('freshrss_lucyna_entrytmp');
 pg_relation_size
------------------
           229376
(1 row)

freerssdb=# select pg_relation_size('freshrss_lucyna_feed');
 pg_relation_size
------------------
            57344
(1 row)
```
Added also to crontab following task to avoid big database, 
```

10 2 * * * php /var/www/html/rss/cli/db-optimize.php --user karcio
20 2 * * * php /var/www/html/rss/cli/db-optimize.php --user lucyna
```

**Comment by karcio** [comment]
hi @Alkarex 
Thank you, could you please share sample db config 
```

'db' =>
  array (
    'type' => 'pgsql',
    'host' => 'localhost:5432',
    'user' => 'fruser',
    'password' => 'password',
    'base' => 'freerssdb',
    'prefix' => 'freshrss_',
    'connection_uri_params' => '',
    'pdo_options' =>
    array (
    ),
```

**Comment by karcio** [comment]
Hi @Alkarex 

I've switched to sqlite - I think I will wait few days and then I will close this issue.
