### ISSUE TITLE
share for buffer app has url with superfluous text [BUG]

### ISSUE THREAD

**Issue by sdenaro** [FreshRSS/FreshRSS#5285]
**Describe the bug**
When adding a share and choosing "Known Sites" and picking "buffer" the URL that is provided leads to a share that looks like 
![image](https://user-images.githubusercontent.com/270809/231039258-8e100457-f84f-4e41-a875-6de935e7b43b.png)

When you use a URL of this format

https://publish.buffer.com/compose?url=~LINK~&text=~TITLE~

You end up with this URL

`https://publish.buffer.com/compose?url=https%3A%2F%2Fwww.macrumors.com%2F2023%2F04%2F10%2Fapp-store-developer-site-outage%2F&text=Apple%27s%20App%20Store%2C%20Developer%20Site%2C%20TestFlight%2C%20Apple%20Music%20and%20More%20Experiencing%20Outage%20%C2%B7%20MacRumors%20%3A%20Mac%20News%20and%20Rumors`

You have a share that looks like 

![image](https://user-images.githubusercontent.com/270809/231039689-c013cf29-5984-4f58-a420-47f9a0aead85.png)

**To Reproduce**
1. Go to settings. Pick "sharing" 
![image](https://user-images.githubusercontent.com/270809/231039892-edc872d9-7626-4c2e-86dc-70d809e855fd.png)

2. Scroll down to "Add a sharing method" and add a share using "Known Sites"
3.  Add buffer and the Buffer URL  
![image](https://user-images.githubusercontent.com/270809/231040196-1222dbc5-4f4a-47c8-a78c-8a8ae79982d3.png)

4. Share an article and pick "Buffer"
5. Confirm the text editing area has superfluous text. 

**Expected behavior**

The edit should look like this:

![image](https://user-images.githubusercontent.com/270809/231039689-c013cf29-5984-4f58-a420-47f9a0aead85.png)

**Screenshots**

See above.

**Environment information (please complete the following information):**
- Device: MacBook 
- OS: MacOS Ventura
- Browser: Chrome 112
- FreshRSS version: 1.21.1-dev
- Database version: Postgres 13.9
- PHP version: 7.4 
- Installation type: hardcore mode git check out 

**Additional context**

**Comment by math-GH** [comment]
Hi,
`Known based sites` is not Buffer.com ;)

This is the `Known` system, that is expected behind the URL input: https://withknown.com/

Here is an overview of the sharing services: https://freshrss.github.io/FreshRSS/en/users/08_sharing_services.html

With the PR #5286, I created Buffer.com as sharing service. Please have a look there, if possible
