### ISSUE TITLE
[BUG] adding feeds from youtube with single quotes in description fail.

### ISSUE THREAD

**Issue by ieperlingetje** [FreshRSS/FreshRSS#5302]
(I'm unable to add the content of the xml in this issue, so you'll have to view the media description from the urls provided)

I'm trying to import all my subscriptions from youtube. This works well for most of the channels, even when they contain weird characters. For example a channel like MrBeast (https://www.youtube.com/feeds/videos.xml?channel_id=UCX6OQ3DkcsbYNE6H8uQQuVA) that has sometimes strange formatting in the description encounters no issues. 

But from the moment there's a single quote in the description, the feed fails to be imported. This can be seen in the following examples:

- Megaprojects:  https://www.youtube.com/feeds/videos.xml?channel_id=UC0woBco6Dgcxt0h8SwyyOmw
- Technology connections: https://www.youtube.com/feeds/videos.xml?channel_id=UCy0tKL1T7wFoYcxCe0xjN6Q

The only error message in the log is: _Unknown error for feed_

I'm using Freshrss 1.21.0

**Comment by math-GH** [comment]
I can import both feeds without any issues on current `edge` branch ( FreshRSS 1.21.1-dev)

![grafik](https://user-images.githubusercontent.com/1645099/232255654-eb88b5f3-6efd-4d06-84f5-b133754fab44.png)

**Comment by ieperlingetje** [comment]
If the issue does not occur on the edge branch this issue can be closed. I can wait until the next stable release.
