### ISSUE TITLE
[BUG]Feed won't update after upgrade docker

### ISSUE THREAD

**Issue by marseillai** [FreshRSS/FreshRSS#5306]
**Describe the bug**
I'm changinf my nas and transfer my freshrss to new NAS. I transfered database and create a new Container. Old was 1.18.0 and everything was Ok (still is).
I'm using Linuxserver Image.
The new is 1.21.0. I can update a feed manually by clicking on "update feed". But no auto update is done and when i ask to update feed the is this error : 
"Une requête a échoué, cela peut être dû à des problèmes de connexion à Internet."
as I can manually update feed and there is no network configuration I doubt that this is a network problem.
In the docker console I've this error in /tmp/FreshRSS.log :                                                                                                                                                            
/bin/ash: /usr/bin/php7: not found
in /docker/freshrss/config/log/nginx/error.log I've this message : 
2023/04/16 19:16:48 [error] 265#265: *44 FastCGI sent in stderr: "PHP message: PHP Warning:  session_start(): open(/tmp/sess_mt2cv95cd2h5njt78if45r24da, O_RDWR) failed: Permission denied (13) in /app/www/lib/Minz/Session.php on line 50PHP message: PHP Warning:  session_start(): Failed to read session data: files (path: ) in /app/www/lib/Minz/Session.php on line 50" while reading response header from upstream, client: 172.17.0.1, server: _, request: "GET /i/?c=javascript&a=nbUnreadsPerFeed HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "mydnshostadress:32080"

**Environment information (please complete the following information):**
- Device: Synology Nas
- OS: Docker
- Browser: Firefox 111
- FreshRSS version: [e.g. 1.21.1]
- Database version: [e.g. Postgre]
- Installation type: Docker

**Comment by Alkarex** [comment]
Hello,
I am not familiar with the Linuxserver version. Our image is https://hub.docker.com/r/freshrss/freshrss/
However, it should also work with their image. It looks like two different bugs:
* The cron job to refresh feeds seems to call `/usr/bin/php7`, which is not found
* The PHP session mechanism depends on writing to `/tmp` (inside the container, if you have not mounted anything there) and it looks like there is a permission problem.

For now, I suggest two things in parallel:
1) Report the bug(s) to Linuxserver (and let me know if there is any problem coming from FreshRSS itself) https://github.com/linuxserver/docker-freshrss
2) Give a try to our image `freshrss/freshrss` to see whether it works for you https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md

**Comment by marseillai** [comment]
Thansk for your answer.
I think I've solved my issuez just after filling the issues (beside searching for a day).
I had to scratch my /config dir and redo the install process. Now everything seems OK.
