### ISSUE TITLE
Unable to access web page to finish installation

### ISSUE THREAD

**Issue by jsphnecclia** [FreshRSS/FreshRSS#5321]
Hi, Im unable to complete installation of FreshRSS. When I try to access p/i/ on the web browser I get the error "File not found".

in my error logs, I keep getting the error `FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream`.

I wasn't able to find any results on the internet, so I imagine its a problem between computer and chair.

I can provide any necessary information. Here is my nginx site config:

```
server {
	listen 	    80;
	listen	    443 ssl http2 default_server;
        listen      [::]:443 ssl http2 default_server;

        ssl on;
        ssl_certificate       /etc/ssl/freshrss_server_cert.pem;
        ssl_certificate_key   /etc/ssl/freshrss_server_key.pem;

        #charset koi8-r;
        #access_log  /var/log/nginx/wallabag.access.log;
        #error_log   /var/log/nginx/wallabag.error.log;
        #access_log  logs/host.access.log  main;
        root   /srv/http/p/;


        # nginx log files
	access_log /var/log/nginx/rss.access.log;
	error_log /var/log/nginx/rss.error.log;

	# php files handling
	# this regex is mandatory because of the API
	location ~ ^.+?\.php(/.*)?$ {
		fastcgi_pass unix:/run/php-fpm/php-fpm.sock;
		fastcgi_split_path_info ^(.+\.php)(/.*)$;
		# By default, the variable PATH_INFO is not set under PHP-FPM
		# But FreshRSS API greader.php need it. If you have a “Bad Request” error, double check this var!
		# NOTE: the separate $path_info variable is required. For more details, see:
		# https://trac.nginx.org/nginx/ticket/321
		set $path_info $fastcgi_path_info;
		fastcgi_param PATH_INFO $path_info;
		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	}

	location / {
		# try_files $uri $uri/ index.php;
		try_files $uri index.php;
	}
    }
```

**Comment by Alkarex** [comment]
Hello,
First, did you try our documentation?

* https://freshrss.github.io/FreshRSS/en/admins/03_Installation.html
* https://freshrss.github.io/FreshRSS/en/admins/10_ServerConfig.html

See also a similar question on https://stackoverflow.com/questions/35261922/how-to-debug-fastcgi-sent-in-stderr-primary-script-unknown-while-reading-respo

Second, nginx is very error prone (most of our help requests are related to nginx misconfiguration), so you can consider alternatives:

* We have some ready-to-use Docker images https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md
* Apache works better (in particular out the box), with reduced risks of errors and better error messages, at least in my opinion

**Comment by jsphnecclia** [comment]
I have followed the documentation, including the links you sent. However, I figured it out.

My nginx.conf was missing `index index.php index.html index.htm`!!

But now I have a permissions error. I've made sure all the files have the correct permissions, I've run cli/access-permissions.sh several times (it appears to exit successfully, but nothing is changed), here is the error and my ls -l:

<img width="684" alt="Screenshot 2023-04-20 at 8 35 38 PM" src="https://user-images.githubusercontent.com/51343659/233520749-8e785209-22b5-43f4-a9b2-c6365abb9e37.png">

<img width="526" alt="Screenshot 2023-04-20 at 8 40 37 PM" src="https://user-images.githubusercontent.com/51343659/233520776-6ba3d30c-767f-4990-b1d0-499c63102a1e.png">

If theres anything else I can provide, let me know.

PS Here is the rss.error.log. Probably helpful? The error `PHP message: PHP Warning: touch(): Utime failed: Read-only file system in /usr/share/FreshRSS/lib/lib_install.php on line 44` Seems to be the root of the problem.

<img width="1390" alt="Screenshot 2023-04-20 at 9 08 57 PM" src="https://user-images.githubusercontent.com/51343659/233524422-e5b43289-4adf-443a-a658-267dbd56c703.png">

Do I need to change the permissions for the /usr as well as /usr/share folders? How would I safely do so?

**Comment by Alkarex** [comment]
Could you please check the rights inside your `./data/` folder?

**Comment by jsphnecclia** [comment]
Thank you for the response.

It looks normal to me?

<img width="443" alt="Screenshot 2023-04-21 at 2 10 04 AM" src="https://user-images.githubusercontent.com/51343659/233566302-db52a848-4ee7-4e4c-b6c1-d46ba0e8671e.png">

**Comment by Alkarex** [comment]
Then it might be that the file-system is actually read-only, as shown in the error message, at least for the http user. You do not happen to use SELinux or something like that?

**Comment by jsphnecclia** [comment]
No, the filesystem is the same as I use all over my system. I'm running vanilla arch, no SELinux or anything. I have /srv/http/p linked to /usr/share/FreshRSS/p but I don't think that would produce this error... 

./data is not inside the /p folder. Is it supposed to be?

<img width="430" alt="Screenshot 2023-04-21 at 12 44 15 PM" src="https://user-images.githubusercontent.com/51343659/233701315-74484a72-0b8f-44e2-b2c6-c6bdf7943e8b.png">

Here I tried to touch a file in data as http user, and it was successful?
<img width="754" alt="Screenshot 2023-04-21 at 12 46 58 PM" src="https://user-images.githubusercontent.com/51343659/233701846-0fccf590-866f-4098-9538-d0098cf43453.png">

**Comment by Alkarex** [comment]
No, the data folder must not be under the p folder. The symlink might be
the problem. I can send a little test later.

Le ven. 21 avr. 2023 à 19:48, Parker McGowan ***@***.***> a
écrit :

**Comment by Alkarex** [comment]
Here is a little test. Please put in in `./FreshRSS/p/test-write.php`

```php
<pre>
<?php
require(__DIR__ . '/../constants.php');
echo DATA_PATH, "\n";
echo 'Realpath: ', realpath(DATA_PATH), "\n";
echo 'Is writeable? ', is_writable(DATA_PATH) ? 'OK' : 'NOK', "\n";
echo 'Touch? ', touch(DATA_PATH . '/index.html') ? 'OK' : 'NOK', "\n";
```

And then call it via e.g. https://freshrss.example.net/test-write.php

Example of correct output:

```txt
/var/www/FreshRSS/data
Realpath: /var/www/FreshRSS/data
Is writeable? OK
Touch? OK
```

**Comment by jsphnecclia** [comment]
:/ bad results:

```
/usr/share/FreshRSS/data
Realpath: /usr/share/FreshRSS/data
Is writeable? NOK
Touch? NOK
```

**Comment by Alkarex** [comment]
Try to check the rights for parent folders, for `r` and `x`

**Comment by jsphnecclia** [comment]
Success! I had confused what exposing a folder to the web was! 

Having FreshRSS in /usr/share/FreshRSS would be a bad idea, as the whole directory tree (?) would have to be owned by/ in group http!

I was also confused as to what "exposing only p" meant. I thought this meant only having /p accessible by the http user. But what it really meant was what to set the 'root' on the webserver to be.: ` root /srv/http/FreshRSS/p/`

So what I did was install FreshRSS to /srv/http/FreshRSS. Now the errors are gone!
