### ISSUE TITLE
[BUG] Incorrect URLs used in place of <link> tag

### ISSUE THREAD

**Issue by jeauxlb** [FreshRSS/FreshRSS#5323]
**Describe the bug**
RSS feed items can have multiple URLs associated with them, including their images, alongside the main article link. FreshRSS is sometimes confusing which link deserves primacy, and is not always using the `<link>` tag as the primary link for an article.

**To Reproduce**
Example feed: <https://www.theatlantic.com/feed/all/>
1. Add this feed to FreshRSS
2. Click on an article heading from this feed within FreshRSS or an API client. The user will be taken to a cover image for the article in their web browser.

**Expected behavior**
When clicking on the article heading, the user should be taken to the article in the feed item's `<link>` tag.

**Environment information**
- FreshRSS version: 1.21.0
- Installation type: Docker

**Additional context**
I have verified that the expected behaviour works in other RSS readers.

**Comment by Alkarex** [comment]
It looks like a bug in SimplePie (the library we are using for parsing the feeds). I will try to do some bug hunting

**Comment by Alkarex** [comment]
I check the problem:

* First, the feed respond with various formats (Atom, RSS 2.0) depending on HTTP Accept header.

To get the version received by FreshRSS:

```sh
curl -v -A 'FreshRSS/1.21.1-dev (Linux; https://freshrss.org)' -H 'Accept: application/atom+xml, application/rss+xml, application/rdf+xml;q=0.9, application/xml;q=0.8, text/xml;q=0.8, text/html;q=0.7, unknown/unknown;q=0.1, application/unknown;q=0.1, */*;q=0.1' 'https://www.theatlantic.com/feed/all/'
```

* Second, while the Atom version is fine, the RSS 2.0 version is broken, using a wrong link construct (I have replaced all the content with generic test strings):

```xml
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0"
 xmlns:media="http://search.yahoo.com/mrss/"
 xmlns:atom="http://www.w3.org/2005/Atom">
	<channel>
		<title>A feed title</title>
		<link>http://example.net/</link>
		<atom:link rel="self" href="http://example.net/a-feed.xml"/>
		<item>
			<guid isPermaLink="false">guid:123</guid>
			<!-- The line below is not RSS 2.0 compliant: -->
			<link href="http://example.net/a-link-alternate" rel="alternate"/>
			<title type="html">An HTML item title</title>
			<media:content url="http://example.net/a-media-content.jpg"/>
		</item>
	</channel>
</rss>
```

![image](https://user-images.githubusercontent.com/1008324/233643069-4b2c09fa-6805-4b3e-b20c-48f8623fb96e.png)

So the upstream feed is broken, and I am not sure we should support this bug. Maybe you could try to propose your patch to https://github.com/simplepie/simplepie to see what other people think of it. (We do have a local version of SimplePie, so we are able to ship custom patches though)

What we should do on FreshRSS side in any case is to allow custom HTTP headers in the advanced sections of feeds, for instance to override the default HTTP Accept header or other headers.

**Comment by Alkarex** [comment]
By the way, PR welcome for a new textarea in the advanced settings of a feed to override HTTP headers.

**Comment by gjimish** [comment]
@Alkarex Sure, I love to do it. Do we have documented  requirements somewhere to override HTTP headers?

**Comment by Alkarex** [comment]
No, nothing is done yet. We do have an implementation to override the HTTP user-agent though, which can be taken as an example

**Comment by Alkarex** [comment]
P.S. One can search `useragent` in our code-base (excluding third-party library SimplePie) for a starting point https://github.com/search?q=repo%3AFreshRSS%2FFreshRSS%20useragent&type=code

**Comment by gjimish** [comment]
> By the way, PR welcome for a new textarea in the advanced settings of a feed to override HTTP headers.

Currently no room to configure headers.
https://github.com/FreshRSS/FreshRSS/blob/cc03cee746c158eb38e13758e378b2d1ace20629/lib/SimplePie/SimplePie.php#L1698-L1700

Do you want me to update SimplePie lib? However I have requested for it [issue#833](https://github.com/simplepie/simplepie/issues/833).

@Alkarex  Can you create issue so we can move all our discussion over there?

**Comment by gjimish** [comment]
> By the way, PR welcome for a new textarea in the advanced settings of a feed to override HTTP headers.

SimplePie's currently available version does not support changing the HEADER. Although I have made a feature request, it appears that the functionality has already been the subject of a PR.

https://github.com/simplepie/simplepie/issues/833#issuecomment-1521338681

@Alkarex Would you mind opening an issue for this feature so we can talk about it more?

**Comment by brevilo** [comment]
Sorry, I should have posted my [comment](https://github.com/FreshRSS/FreshRSS/pull/5324#issuecomment-1540348921) in this (parent) issue, not the subsequent MR.

**Comment by Alkarex** [comment]
@gjimish I mean a PR for FreshRSS. We do have the mechanisms in place to modify whatever curl parameters we want

**Comment by Alkarex** [comment]
This feed seems to work now, AND we support custom HTTP Headers https://github.com/FreshRSS/FreshRSS/pull/6820
