### ISSUE TITLE
[BUG] Category options links lead to broken page

### ISSUE THREAD

**Issue by mrnoname1000** [FreshRSS/FreshRSS#5330]
**Describe the bug**
In `Subscription management` the cogs on each category have a link. When JS is disabled or the link is opened manually, the resulting page is a bare HTML page with no styling or JS.

**To Reproduce**
1. Go to 'Subscription management'
2. Right-click the cog by a category and open in a new tab OR disable JS and click the cog
3. See barren page: e.g. /i/?c=subscription&a=category&id=1

**Expected behavior**
The link should lead to a populated page.

**Screenshots**
![screenshot 2023-04-23 20:43:45](https://user-images.githubusercontent.com/8191535/233884976-ddd4e792-99cd-438b-a7d3-af2b5136fb45.png)

**Environment information (please complete the following information):**
- Device: ThinkPad A485
- OS: Void Linux
- Browser: Firefox 112
- FreshRSS version: edge [11572462]
- Database version: PostgreSQL 13.9
- PHP version: PHP 7.4
- Installation type: Self-hosted [Debian 11.6]

**Additional context**
This is related to an older issue I posted: #4726

**Comment by Alkarex** [comment]
Maybe for @math-GH ?

**Comment by math-GH** [comment]
Right now there is no common default behavior in the app when you open a manage link (via cog icon) in a new tab.

@mrnoname1000 Could you please explain a bit, why it is important for you to open the configuration in a new tab instead of in the right hand side slider?

**Comment by mrnoname1000** [comment]
When I'm editing several categories at once, it's faster to open all their manage tabs at once in the background, so I can Ctrl+tab and click 'Remove', add a priority, etc. for each one. It's so much faster that I still do this even though the page is broken. Opening the cog or `Manage` link for a _feed_ has the expected behavior, i.e. a rendered page with the manage panel open.

Also worth noting, submitting the category redirects to a rendered page, this is more like what I expect the link to send me to.

Here's a table of the various manage tabs:
| | Manage/cog href | Submit+redirect |
| --- | ---- | --- |
| Category | ❌ `?c=subscription&a=category&id=1` | ✔️ `?c=subscription&id=1&type=category&rid=456def#slider` |
| Feed | ⚠️ `?c=subscription&a=feed&id=1` | ✔️ `?c=subscription&id=1&rid=123abc#slider` |

I've labeled the broken manage page with ❌, full-screen manage pages with ⚠️, and slider manage pages with ✔️ because this is consistent with the JS interface. It's up to you guys whether the full-screen or slider interface is desired.

**Comment by Alkarex** [comment]
This seems to be fixed in `edge`. Please check :-)
