### ISSUE TITLE
[BUG] PHP Fatal error:  Uncaught TypeError: FreshRSS_Entry::__construct() ...

### ISSUE THREAD

**Issue by ryan-thompson-1984** [FreshRSS/FreshRSS#5331]
**Describe the bug**
The `$is_starred` variable in the importJson function of importExportController.php is null when it passed to the FreshRSS_Entry constructor on line [433](https://github.com/FreshRSS/FreshRSS/blame/latest/app/Controllers/importExportController.php#L433).  The constructor expects a boolean, and since null is not a boolean, it throws an error.

**To Reproduce**
1. Create a new directory for the fresh installation at `/var/freshrss`
2. Download the most recent release of FreshRSS from "https://codeload.github.com/FreshRSS/FreshRSS/tar.gz/refs/tags/1.21.0"
3. Unarchieve it to `/var/freshrss`
4. Change `./data` and `./p` directories to be owned by the www-data user
5. Run `./cli/prepare.php`
6. Run `./cli/do-install.php --default_user admin --environment production --base_url $URL --api_enabled --db-type mysql --db-host localhost:3306 --db-user $SQL_USER --db-password $SQL_PASSWD --db-base freshrss`
7. Fix permissions `./cli/access-permissions.sh`
8. Create admin user `./cli/create-user.php --user admin --password $ADMIN_RSS_PASSWD --api_password $ADMIN_RSS_API_PASSWD --email $ADMIN_RSS_EMAIL --no_default_feeds`
9. Create non-admin user `./cli/create-user.php --user raindrop-fan --password $RSS_PASSWD --api_password $RSS_API_PASSWD --email $RSS_EMAIL --no_default_feeds`
10. Attempt to import zip-archieve for non-admin user `./cli/import-for-user.php --user raindrop-fan --filename /tmp/freshrss_backup_raindrop-fan.zip`
11. See error

**Expected behavior**
An export from an instance running version 1.21.0 should import without error to an instance running 1.21.0.

**Environment information (please complete the following information):**
- Device: LXC Container, running on desktop
- OS: Debain 11
- FreshRSS version: 1.21.0
- Database version: MariaDB 10.5.18
- PHP version: PHP 8.0.28
- Installation type: Manual Install

**Additional context**
- I created the export earlier today from another instance of FreshRSS, also which is running 1.21.0.  The environments for the two instances are near identical (they are both LXC containers running on the same machine).

- Console output:
```
root@ansible-6:/var/freshrss# ./cli/import-for-user.php --user raindrop-fan --filename /tmp/freshrss_backup_raindrop-fan.zip 
FreshRSS importing ZIP/OPML/JSON for user “raindrop-fan”…
PHP Fatal error:  Uncaught TypeError: FreshRSS_Entry::__construct(): Argument #9 ($is_favorite) must be of type bool, null given, called in /var/freshrss/app/Controllers/importExportController.php on line 434 and defined in /var/freshrss/app/Models/Entry.php:54
Stack trace:
#0 /var/freshrss/app/Controllers/importExportController.php(434): FreshRSS_Entry->__construct()
#1 /var/freshrss/app/Controllers/importExportController.php(121): FreshRSS_importExport_Controller->importJson()
#2 /var/freshrss/cli/import-for-user.php(31): FreshRSS_importExport_Controller->importFile()
#3 {main}
  thrown in /var/freshrss/app/Models/Entry.php on line 54
```

- My exported .zip file that is failing to import.  Please, try to import it on your machine to see if you get the same error:
[raindrop-fan.zip](https://github.com/FreshRSS/FreshRSS/files/11305738/raindrop-fan.zip)

- I was able to patch this on my machine by adding
```
if ($is_starred == null) { $is_starred = false; }
```
on line 432.  However, this might have additional implications.  `$is_starred` is instantiated on line [366](https://github.com/FreshRSS/FreshRSS/blame/latest/app/Controllers/importExportController.php#L366).  It looks like this  variable used to be instantiated as false, and this was changed to be instantiated as null 8 months ago, per 82ac1d1e676f93b1567eba608c00c6edaf401a9e

Seems like either an issue with the FreshRSS_Entry constructor being too strict or needing a null check prior to passing `$is_starred` to the constructor.

**Comment by Alkarex** [comment]
Thanks for the very thorough bug report 👍🏻 
Should be fixed by https://github.com/FreshRSS/FreshRSS/pull/5332
Tests welcome.

**Comment by squromiv** [comment]
Smth is wrong with ImportExport feature. I am testing the last dev version of FreshRSS.

> `\cli\import-for-user.php" --user User --filename "file.zip"
> FreshRSS importing ZIP/OPML/JSON for user “User”…
> 
> Fatal error: Uncaught TypeError: sanitizeHTML(): Argument #1 ($data) must be of type string, array given, called in W:\domains\loca
> lhost\fresh\f1\app\Controllers\importExportController.php on line 442 and defined in W:\domains\localhost\fresh\f1\lib\lib_rss.php:
> 334
> Stack trace:
> #0 W:\domains\localhost\fresh\f1\app\Controllers\importExportController.php(442): sanitizeHTML()
> #1 W:\domains\localhost\fresh\f1\app\Controllers\importExportController.php(139): FreshRSS_importExport_Controller->importJson()
> #2 W:\domains\localhost\fresh\f1\cli\import-for-user.php(31): FreshRSS_importExport_Controller->importFile()
> #3 {main}
>   thrown in W:\domains\localhost\fresh\f1\lib\lib_rss.php on line 334`

**Comment by Alkarex** [comment]
@squromiv Thanks for the bug report. Could you please open a new issue?

**Comment by squromiv** [comment]
@Alkarex Done #5622
