### ISSUE TITLE
[BUG] Filter not showing all expected results

### ISSUE THREAD

**Issue by p-vitt** [FreshRSS/FreshRSS#5333]
**Describe the bug**
Due to the fact that I can't create nested categories and there is no way to tag all items from a feed, I started to mimic those features by creating user querys that hide specific feeds. I started to use this feature some days before and until today, it worked fine (at least I think, perhaps I just didn't see the problem until today). Today I recognized that the filter somehow seems to be broken. The filter exists of several _!f:n_ clauses. But also articles from feeds not matched by the filter are not shown. Additionally, when I remove one clause, e.g. _!f:62_, the mistakenly filtered articles from three feeds now show up (the feed ids are 67, 68, and 80).

Today I removed a feed, perhaps this confused the filter logic!? 

**To Reproduce (at least what I did)**
1. Create a user query hiding several feeds: _!f:1 !f:10 !f:20 ..._
2. Remove a feed from FreshRSS
3. Open the user query result view
4. See that there are unread items that don't show up in the user query result view.

**Expected behavior**
See all unread articles from all feeds that are not _hidden_ by the ilter.

**Screenshots**
Screenshot 1 shows the filter result, screenshot 2 one feed (with the ID in the url) that should show up in the filter result.
![1](https://user-images.githubusercontent.com/7194859/233970772-80f7eb98-c7ff-40c4-9ccb-e31efff09568.PNG)
![2](https://user-images.githubusercontent.com/7194859/233970799-ab0a67cb-6716-4f34-8719-0f58535af568.PNG)

**Environment information (please complete the following information):**
- OS: Windows 10
- Browser: Firefox 112.0.1
- FreshRSS version: 1.21.0
- Database version: MariaDB 10.3
- PHP version: Can't check from remote, is 8.x.
- Installation type: [like here](https://lab.uberspace.de/guide_freshrss/?highlight=freshrss)

**Comment by Alkarex** [comment]
Hello,
I have not been able to reproduce the problem so far.
Could you please send a screenshot of the problem again, in which one can see the URL parameters like you have in your second screenshot?

**Comment by Alkarex** [comment]
And does this other syntax change anything? `!f6,7,37`

**Comment by p-vitt** [comment]
This is the URL for the first screenshot:
.../freshrss/i/?search=%21f%3A6+%21f%3A7+%21f%3A37+%21f%3A45+%21f%3A61+%21f%3A62+%21f%3A102&state=2&order=ASC

Using the filter `!f:6,7,37,45,61,62,102` fixes th problem.

**Comment by Alkarex** [comment]
Seems to work fine for me on `edge` branch
