### ISSUE TITLE
Mirror to Codeberg

### ISSUE THREAD

**Issue by foxxy432** [FreshRSS/FreshRSS#5334]
### Summary

We should mirror our repos to Codeberg because:

Codeberg is libre, free, open-source, privacy-friendly, non-profit
GitHub is privacy-invasive, proprietary
People on Codeberg like me can contribute to the project
GitHub can take down your repos

FAQ

Q: - GitHub Actions -- this is a huge time saver for me
- Forcing all contributors to modify their current setup and move to another hosting -- we may just lose contributors in the end

A: As I said, we only just mirror. The repo will be available and contributable on both sites.

Q: - Transferring issues -- is this possible? Issues here represent a technical knowledge base we can't live without
- Transferring wiki and all edit history -- possible?

A: Yes, it is possible.
a. Example for issues:

Migration to independent platform for provision of source code andersju/webbkoll#35
https://codeberg.org/dataskydd.net/webbkoll/issues/35
[UI/UX] Simplification of the user interface for non-technical people andersju/webbkoll#33
https://codeberg.org/dataskydd.net/webbkoll/issues/33

Framed answers? - Locations zyachel/quetre#7
https://codeberg.org/zyachel/quetre/issues/7

b. Example for commits:

https://codeberg.org/dataskydd.net/webbkoll/commit/6ddfbc6c71ab92f754252dd4904cf49fb19672a6
andersju/webbkoll@6ddfbc6

c. Example for wiki:

https://github.com/Freeyourgadget/Gadgetbridge/wiki/Home/_history?page=2
https://codeberg.org/Freeyourgadget/Gadgetbridge/wiki/Home?action=_revision

Q: Despite having mirror/s, the project will still continue to be operated from GitHub for development, so having yet another mirror doesn't solve anything.

A: You can create issues, contribute, view the repos on there without going to GitHub! Example:

https://github.com/libredirect/libredirect
https://codeberg.org/LibRedirect/libredirect
https://github.com/zyachel/quetre
https://codeberg.org/zyachel/quetre

Q: How does Codeberg mirror comments from GitHub?

A: It uses Access Token.

Q: My repos are very bandwidth-intensive projects, and I have my doubts as to whether the owner(s) of Codeberg would be prepared for such a massive bandwidth rate increase. I've also had individual projects be disabled on small sites before due to taking too much bandwidth.

A: Oh.. I think you should directly ask https://docs.codeberg.org/contact/ about if they are ready for massive bandwidth rate increase.

### What benefits does this feature provide?

Codeberg is libre, free, open-source, privacy-friendly, non-profit
GitHub is privacy-invasive, proprietary
People on Codeberg like me can contribute to the project
GitHub can take down your repos

**Comment by math-GH** [comment]
I will close this issue here. The discussion is ongoing in the discussion section: [#5335](https://github.com/FreshRSS/FreshRSS/discussions/5335)
