### ISSUE TITLE
Titres qui dansent / en gras

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/FreshRSS#534]
Bonjour,

Je viens de mettre à jour mon installation FreshRSS avec la branche dev, et je vois qu'au passage sur un article, les titres "dansent", ie. se décalent vers le bas pour se re-décaler vers le haut quand on n'a plus la souris dessus. Est-ce un comportement voulu ?
Car je n'aime pas du tout ^^ En plus il n'y a ça que sur les thèmes flat design et original, pas sur le dark.

De plus, l'écriture des titres a changée. Ils sont en gras, voire de taille supérieure, et il y a peut-être même eu un changement de police ?

/Adrien.

**Comment by Alwaysin** [comment]
Dancing titles are back on Chrome 41 on Linux :)

**Comment by Alkarex** [comment]
@Alwaysin I have not tested yet, but is it the same problem with all themes? And no problem with Firefox in your case?

**Comment by Alwaysin** [comment]
Yes, the same with all 6 themes and not happening in Firefox.

**Comment by Alkarex** [comment]
@Alwaysin I cannot reproduce the problem... So please double-check that you are using the /dev branch, and with the current version of Chrome (43).

I have just tested on Ubuntu 15.04 (virtual machine):
- Firefox 38 (default browser): all good
- Chromium 41: no mouse-hover effect at all (even on other Web sites), so no _dancing_
- Google Chrome 43 (manual install, because it is not in the repositories): all good
- Web Epiphany 3.14.2: all good
- Midori 0.4.3: all good

And on Windows 8:
- Internet Explorer 11 (default browser): [several problems](https://github.com/FreshRSS/FreshRSS/issues/772), but fine regarding mouse-hover
- Firefox 38: all good
- Chrome 43: all good
- Opera 29: all good

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/issues/845

**Comment by Alwaysin** [comment]
I've just updated using the automatic system : 

```
Your current version of FreshRSS is the 1.2-dev.
Last verification: May 19th 2015 at 21:40
```

I've also tested on Win8.1 with Chrome 43 and again I got the dancing titles.

I have no extensions.

I made a diff on p/themes/base/ folder and a css of a theme (local files with GitHub files) and there is no change, so it shouldn't be from something I could have changed here (if there are other files I should check please tell me).

Next step is to try with a new FreshRSS installation I guess. I had planned to do it for testing beta 1.1.1 anyway, so let's give it a try :)

**Comment by Alkarex** [comment]
I have to admit that I have not looked at how the automatic update system is working. Do you have the same files as https://github.com/FreshRSS/FreshRSS/tree/dev/p/themes ?

**Comment by Alwaysin** [comment]
Positive for the subfolders icons/ fonts/ base-theme/ and Origine/, the theme I'm using right now (others shouldn't be able to screw things when not using their theme, right?). All files last modified May 19th at 21:40 (tending towards the fact they haven't been modified).

I've just tried with IE and it does it also.

But contrary to the initial post, it does not go downwards when the mouse is over and then goes back to the initial position when the mouse goes out, but it is reversed : it goes upwards then downwards when moving the mouse out of the title.

**Comment by Alwaysin** [comment]
I couldn't reproduce this behaviour on a fresh installation. Problem "solved" I guess :)
I've probably tampered with something on my old installation...

**Comment by Alwaysin** [comment]
What is strange is that this beahviour is always coming back. When I do a fresh installation it is not there, but always comes back with time even though I do not touch anything server-side...

**Comment by Alkarex** [comment]
@Alwaysin Quel navigateur / plateforme / thème / version de FreshRSS ?

**Comment by Alwaysin** [comment]
Sur Chrome, IE 11 et Edge sous Windows 10. Ne se produit pas sur Firefox. J'ai essayé tous les thèmes et le problème était toujours là. Je suis sur /dev à jour des derniers commits.

**Comment by Alkarex** [comment]
@Alwaysin Je n'arrive pas à reproduire le problème (testé sous Chrome, IE11, Edge sous Windows 10). Pourriez-vous faire une petite vidéo / gif, et/ou m'envoyer par courriel une adresse où je pourrai voir le problème ?

**Comment by Alwaysin** [comment]
Chrome : 

![freshrss_dancing_titles_chrome](https://cloud.githubusercontent.com/assets/7189936/19619242/a3970f28-9862-11e6-9a2d-9726d8eb8c19.gif)

Firefox :

![freshrss_dancing_titles_firefox](https://cloud.githubusercontent.com/assets/7189936/19619243/a39a75b4-9862-11e6-9d4c-190bc4d98776.gif)

Email envoyé :)

**Comment by Alkarex** [comment]
J'ai réussi à reproduire le problème : c'est quand les dates sont en anglais, à cause des exposants

**Comment by Alkarex** [comment]
Je pense que j'ai trouvé une solution https://github.com/FreshRSS/FreshRSS/pull/1340
Pourriez-vous tester ?

**Comment by Alwaysin** [comment]
Je confirme que ça fonctionne bien, merci beaucoup 👍

**Comment by Alwaysin** [comment]
Je disais que c'était pas si important que ça mais ça repose beaucoup les yeux finalement :D
