### ISSUE TITLE
[BUG] github updated post doesnt get marked as unread.

### ISSUE THREAD

**Issue by rezad1393** [FreshRSS/FreshRSS#5347]
I have this rss in freshrss:
https://github.com/0x90d/videoduplicatefinder/releases.atom
as you can see in the webpage it says:
`Note: These are daily builds. Attachments are automatically created and replaced on every new commit. Regardless of what the message above says. If you experience upgrade issues you may need to delete your 'ScannedFiles.db' file in VDF folder.`

and if I open the rss with firefox I get :
```
3.0.x
Tuesday, **April 18, 2023** 9:08:27 AM
github-actions[bot]
```

but in my freshrss I still have :
```
[3.0.x](https://github.com/0x90d/videoduplicatefinder/releases/tag/3.0.x)
✇videoduplicatefinder
**1 February 2023 at 03:20**

Note: These are daily builds. Attachments are automatically created and replaced on every new commit. Regardless of what the message above says. If you experience upgrade issues you may need to delete your 'ScannedFiles.db' file in VDF folder.
```

so the link is the same for that post for 3.0.x but it gets updated (from Feb to Apr).
and I have set :

`Mark updated articles as unread:yes`

why I dont get an unread post at April?

**Comment by math-GH** [comment]
Unfortunately you ignored the bug issue template that asked for information about your FreshRSS instance.

Which version do you use? How to reproduce it?
Screenshot could help us to understand it too

**Comment by rezad1393** [comment]
sorry.'

**To Reproduce**
Steps to reproduce the behavior:
add this feed
https://github.com/0x90d/videoduplicatefinder/releases.atom
it has a daily (but it is not daily) build with the same link repeated , like this https://github.com/0x90d/videoduplicatefinder/releases/tag/3.0.x
its post time  gets updated when there is a git commit. 
so for example last commit was from 17 Apr and the post time got updated to "Tuesday, April 18, 2023 9:08:27 AM"
but in freshrss checking for update doesn't change the post to unread. and it stays on the last time that post was added (or when the feed was added to freshrss) so in my case that is in Feb.






**Expected behavior**
the post should change to unread.



**Environment information (please complete the following information):**
- Device: arm odroid xu4
- OS: archlinux-arm
- Browser: firefox
- FreshRSS version:  1.21.0 
php-sqlite 8.2.5-1
sqlite 3.41.2-1

- PHP version: 8.2.5
- Installation type: self-hosted







when frehsrss has the option to make a post as unread if updated does that include checking for change of time for post too?

**Comment by math-GH** [comment]
Discussion is ongoing here: #6443
