### ISSUE TITLE
[Feature] Filter articles by category

### ISSUE THREAD

**Issue by Tone866** [FreshRSS/FreshRSS#5372]
**Is your feature request related to a problem? Please describe.**
I have a feed which uses categories for every article. 
e.g.: 
```
Article1, category: news, flowers
Article2, category: it
```
I want to use the search-filter for this categories and e.g. mark every article with category it as read.
I did not found in solution with the existing filters, but I indeed don't fully understand the search by tag and label-name filters.
Is there an rss-element called tag and label? I didn't find one in the spec. 
Maybe it could be solved with this.

**Describe the solution you’d like**
Creating a search filter based on the element category

**Comment by math-GH** [comment]
Do you know the documentation, that lists all search parameters? http://freshrss.github.io/FreshRSS/en/users/10_filter.html#with-the-search-field

**Comment by Tone866** [comment]
Yes, I‘ve read the documentation.
I have not found a filter for category.
My problem with tag is that I don‘t know (and also not found in the documentation) which element on the rss-feed they refer to.
I did not found a tag element in the rss-spec.
Probably I think too complicated.

And I don’t unterstand how label-name works. Would it filter the article by pure existance of the element category?
I mean I could say label:category but not lable:category=it right?

**Comment by math-GH** [comment]
You can use a list of feeds `f:123,234,345` (a specific category search key is not implemented yet as far as I know)
Search for tags (given by the article): `#tag` or `#tag+with+whitespace`

**Comment by Tone866** [comment]
nevermind, tag works, thank you!
