### ISSUE TITLE
Documentation: Page "Changing the source code" is empty

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#5390]
> I saw this: https://freshrss.github.io/FreshRSS/en/developers/03_Backend/04_Changing_source_code.html and this and it was very disappointing...

_Originally posted by @hydrian in https://github.com/FreshRSS/FreshRSS/issues/1053#issuecomment-1542509958_

**Comment by math-GH** [comment]
same for the French documentation: https://freshrss.github.io/FreshRSS/fr/developers/03_Backend/04_Changing_source_code.html

It would be better to delete this page instead of keep this useless, wouldn't be?

**Comment by Alkarex** [comment]
Yes, I think so too

**Comment by Frenzie** [comment]
There might be an implication there that I disagree with (i.e., deleting things just because they say to-do :-) ) but I agree it doesn't seem that page serves much purpose. Unlike writing an extension you have to actually dive into the code to change the code anyway.
