### ISSUE TITLE
White page after adding / create new user 

### ISSUE THREAD

**Issue by ParoTheParrot** [FreshRSS/FreshRSS#5407]
I can't add a new user. neither from form (?c=auth&a=register ) nor from the admin page (?c=user&a=manage).
I always  get a blank page (i/?c=user&a=create) and the user wasn't created

- FreshRSS version: 1.21.0
- Database version: sqlite
- PHP version: 7.3.33

**Comment by math-GH** [comment]
Do you have any log entries?

**Comment by ParoTheParrot** [comment]
First thanks for the quick response.
"/p/i/?a=logs" says nothing

**Comment by ParoTheParrot** [comment]
after deleting the `data/config-user.custom.php `I can add new users!

**Comment by Alkarex** [comment]
Hello,
Your `data/config-user.custom.php` probably had an invalid syntax. If you still have a copy, feel free to paste it here.
