### ISSUE TITLE
[BUG] Create user - error message "You must accept the Terms of Service to be able to register."

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#5409]
**Describe the bug**
I tried to reproduce #5407 and wanted to create a new user in the back end, but I got the error message `You must accept the Terms of Service to be able to register.`
![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/0632415b-0db7-4ef7-9d62-0f75d614eef1)

**To Reproduce**
1. Have TOS activated
2. Go to 'Manage User'
3. Create a user
4. see the error message
5. user was not created

**Expected behavior**
No error. User is created

**Environment information (please complete the following information):**
- FreshRSS version: 1.21.1-dev
- Database version: sqlite

**Comment by Alkarex** [comment]
Has this ever worked in previous FreshRSS versions?
I have never used TOS myself, but what should be the process when a user is created by an admin? Automatically accept the terms of service?

**Comment by math-GH** [comment]
I have no idea and I guess that it has never worked before.
The simplest solution would be to have a checkbox in the admin form too.

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/6269
