### ISSUE TITLE
[BUG] Unusual Fatal Error, happening almost every 2nd day

### ISSUE THREAD

**Issue by vdbhb59** [FreshRSS/FreshRSS#5417]
**Describe the bug**
The below error happens almost every 2nd day and at around 12:30-13:30 my timezone, and then automatically corrects itself after around 70-90 minutes from the timeline (around 14:40-15:00).

```
Fatal error: Uncaught Error: Call to a member function bindParam() on bool in /PATH/feeds/app/Models/FeedDAO.php:293
Stack trace:
#0 /PATH/feeds/app/Models/Entry.php(340): FreshRSS_FeedDAO->searchById(29)
#1 /PATH/feeds/app/views/index/normal.phtml(43): FreshRSS_Entry->feed()
#2 /PATH/feeds/lib/Minz/View.php(88): include('/PATH/...')
#3 /PATH/feeds/lib/Minz/View.php(110): Minz_View->includeFile('/views/index/no...')
#4 /PATH/feeds/app/layout/layout.phtml(69): Minz_View->render()
#5 /PATH/feeds/lib/Minz/View.php(88): include('/PATH/...')
#6 /PATH/feeds/lib/Minz/View.php(101): Minz_View->includeFile('/layout/layout....')
#7 /PATH/feeds/lib/Minz/View.php(68): Minz_View->buildLayout()
#8 /PATH/feeds/lib/Minz/Dispatcher.php(56): Minz_View->build()
#9 /PATH/feeds/lib/Minz/FrontController.php(58): Minz_Dispatcher->run()
#10 /PATH/feeds/p/i/index.php(57): Minz_FrontController->run()
#11 {main} thrown in **/PATH/feeds/app/Models/FeedDAO.php on line 293**
```

**To Reproduce**
No idea how to reproduce, as this happens automatically without me doing anything.

**Expected behavior**
This error should not happen and my feeds instance and feeds should show, instead I get just this error and no feeds show up.

**Screenshots**
![image](https://github.com/FreshRSS/FreshRSS/assets/60728004/3fb8094c-43b0-4345-90c2-ed46ec58021b)

**Environment information (please complete the following information):**
- Device: [Laptop/Mobile]
- OS: [W11 / MX Linux 21.3 April]
- Browser: [LibreWolf 113.0-3 / EinkBro 10.6.3 / Mull 113.1.0#21131020]
- FreshRSS version: [1.21.0]
- Database version: [Mysql 5.7.41-cll-lve]
- PHP version: [PHP 8.0 (ea-php80)]
- Installation type: [cPanel]

**Additional context**

**Comment by Alkarex** [comment]
It it always the same error you get? And is it only when you navigate to a given feed or do you also get an exception when you try to access a category or the main view?
It looks like a temporary database problem.
If you can, try to use our current rolling release 1.21.1-dev, which has changed some related handling of errors.

**Comment by vdbhb59** [comment]
> It it always the same error you get? And is it only when you navigate to a given feed or do you also get an exception when you try to access a category or the main view? It looks like a temporary database problem. If you can, try to use our current rolling release 1.21.1-dev, which has changed some related handling of errors.

Hi Mate,
Sorry for the late reply.
I get the same error every time, same path, same file, same line.
I get it randomly, does not matter if it is main view, or a feed, or even a category. It just throws this same error randomly.
Temp Database Error: Probably.
Rolling release: How do I set it? I have a file "/data/config.php", where the value is: 'environment' => 'development', and something under it as "Salt" (I presume is some sort of encrypted connection value), which I am not sharing here. But how do I switch to the current rolling release, directly from the app itself, please? Cause even if I set it to "production", there is "Blast! No update to apply". Sorry for being a novice mate.

**Comment by vdbhb59** [comment]
@Alkarex mate, closing out for now, as I have not been getting this error for almost more than a week now.
