### ISSUE TITLE
[BUG] Code tags in extensions options/buttons

### ISSUE THREAD

**Issue by roughnecks** [FreshRSS/FreshRSS#5419]
**Describe the bug**
In extensions pages, menu or buttons are named after the their code tags.

**To Reproduce**
1) Enable some extension
2) go to its options by clicking on the gear icon

**Expected behavior**
I'd expect to see clear names for menu/options/buttons

**Screenshots**
https://i.imgur.com/alYb34a.jpeg
https://i.imgur.com/Yh0zKR1.jpeg

**Environment information (please complete the following information):**
- Device: Desktop PC
- OS: Windows 10 x64 fully up to date
- Browser: Chrome x64
- FreshRSS version: 1.21.0
- Database version: sqlite3
- PHP version: PHP 7.4
- Installation type: Debian 11, manual install

**Comment by Alkarex** [comment]
Can you reproduce @math-GH or @aledeg ? I could not (only brief test)

**Comment by Alkarex** [comment]
@roughnecks Using what language?

**Comment by roughnecks** [comment]
> @roughnecks Using what language?

Italian

**Comment by roughnecks** [comment]
I just checked and in English it's fine.

**Comment by Alkarex** [comment]
Right, it is the fallback to English (when a translation inside the extension is not available), which seems to fail.
E.g. for CustomCSS: https://github.com/FreshRSS/Extensions/blob/master/xExtension-CustomCSS/i18n/en/ext.php

@aledeg Do you know whether that has ever worked?

**Comment by roughnecks** [comment]
English (United States) has the same bug for me.

**Comment by Alkarex** [comment]
Yes, the [example of the CustomCSS extension](https://github.com/FreshRSS/Extensions/blob/master/xExtension-CustomCSS/i18n/en/ext.php) has `de, fr, en` and all other locates are failing

**Comment by math-GH** [comment]
could you please check #5426? Does it fix the issue?

**Comment by roughnecks** [comment]
> could you please check #5426? Does it fix the issue?

I have installed the latest release [FreshRSS 1.21.0](https://github.com/FreshRSS/FreshRSS/releases/tag/1.21.0)
How do I try your PR?

**Comment by math-GH** [comment]
> > could you please check #5426? Does it fix the issue?
> 
> I have installed the latest release [FreshRSS 1.21.0](https://github.com/FreshRSS/FreshRSS/releases/tag/1.21.0) How do I try your PR?

The PR is already merged, it means that it was tested and the code is now in the `main` branch, so it is ready for the next release that follows after 1.21.0
