### ISSUE TITLE
[BUG] Theme preview under displays is missing/broken

### ISSUE THREAD

**Issue by vdbhb59** [FreshRSS/FreshRSS#5424]
**Describe the bug**
The Theme Selector displays no **preview** under Settings > Display, irrespective of the theme chosen.

**To Reproduce**
1. Go to 'Settings (Click the clog wheel icon)'
2. Click on 'Display'
3. Theme preview should be shown
4. Instead it shows a blank screen (like a broken image) (see snap)

**Expected behavior**
Theme preview should be shown for each and every theme.

**Screenshots**
See attached image below...

**Environment information (please complete the following information):**
- Device: [Laptop/Mobile]
- OS: [W11 / MX Linux 21.3 April]
- Browser: [LibreWolf 113.0-3 / EinkBro 10.6.3 / Mull 113.1.0#21131020]
- FreshRSS version: [1.21.0]
- Database version: [Mysql 5.7.41-cll-lve]
- PHP version: [PHP 8.0 (ea-php80)]
- Installation type: [cPanel]

**Additional context**
I have checked it with few users who are using other instances too, and on the same version (I have checked it myself), this issue is there. But I am not sure of the other instances are using the same setup, or similar setup. This may not even be a bug and maybe some permission issue, but I am not aware, if that indeed is the case.

Loaded code via inspect shows this for the below example snapshot: < img src=" ../themes/Origine-compact/thumbs/original.png " loading="lazy" >

Example snapshot:

![image](https://github.com/FreshRSS/FreshRSS/assets/60728004/db2d18e3-e5c2-4251-ad09-8a21a4594e1d)

**Comment by math-GH** [comment]
Can you access the file `/p/themes/Origine-compact/thumbs/original.png`?

**Comment by vdbhb59** [comment]
> Can you access the file `/p/themes/Origine-compact/thumbs/original.png`?

By access you mean via a file manager or via URL? Via URL I get a 403.

**Comment by Alkarex** [comment]
If you get a 403, that is the explanation for the problem.
You probably have another rule / configuration that prevent access to this file or to PNG files.
Check your Web server logs for clues.
That does not seem related to FreshRSS

**Comment by math-GH** [comment]
Which server do you use? Apache or nginx?

**Comment by vdbhb59** [comment]
Yeah looks like access issue. Though when I check permission, all are set as should be. 0644 for that file.
I use cPanel, and it runs apache.

**Comment by vdbhb59** [comment]
My bad (I closed without commenting as to why I closed the ticket). I just realized, my hosting has a hotlink option, and that is why I was getting the issue. The hotlinking protection is ON. I have made exceptions for my instances, and it is fine now. :) Sincere apologies, as it got overlooked from my end.
