### ISSUE TITLE
[BUG]Custom CSS shows ext.custom_css.permission_problem

### ISSUE THREAD

**Issue by JamYiz** [FreshRSS/FreshRSS#5425]
**Describe the bug**
[BUG]Custom CSS shows ext.custom_css.permission_problem，can't save custom css.

**To Reproduce**
1. Go to 'Extension'
2. Click on 'Custom CSS'
3. Scroll down to the bottom

**Expected behavior**
Can successfully use custom css 

**Screenshots**
![Snipaste_2023-05-27_15-55-30](https://github.com/FreshRSS/FreshRSS/assets/44351690/b6283ed0-a922-4f13-8d23-0342174b42e8)

**Environment information (please complete the following information):**
- Device:Lenovo Yoga14s[e.g. iPhone6]
- OS: windows11[e.g. Ubuntu 20.04]
- Browser:Firefox 113 [e.g. Firefox 86]
- FreshRSS version:1.20.2  [e.g. 1.17.1]
- Database version:Sqlite [e.g. Mysql 5.7]

- PHP version:7.4.33 [e.g. PHP 7.4]
- Installation type:Docker [e.g. Yunohost]

**Additional context**

**Comment by math-GH** [comment]
Which language do you use?

I guess it is the same issue like #5419

see the comment too
https://github.com/FreshRSS/FreshRSS/issues/5419#issuecomment-1557123005

**Comment by JamYiz** [comment]
> Which language do you use?
> 
> I guess it is the same issue like #5419
> 
> see the comment too [#5419 (comment)](https://github.com/FreshRSS/FreshRSS/issues/5419#issuecomment-1557123005)

My language is Chinese.When I switch English,It shows the error "Your CSS file is not writable, please change the file permissions for xExtension-CustomCSS/static/".

**Comment by math-GH** [comment]
Do you need help here or is it clear how to solve the writing permission issue?

**Comment by JamYiz** [comment]
> Do you need help here or is it clear how to solve the writing permission issue?

I have been solved it. After I increase the permissions, the plugin can run successfully.Thanks.

**Comment by matthewdphilip** [comment]
hello，jamyiz，meet same problem here，can you share the solution of how to increase the permission？thx

**Comment by JamYiz** [comment]
> hello，jamyiz，meet same problem here，can you share the solution of how to increase the permission？thx

Sorry, I almost forgot how I solved this problem. Maybe you can try increasing the permissions for reading and writing files.

**Comment by math-GH** [comment]
Please make sure that you use the newes FreshRSS version (1.22.0 was released yesterday).
Please check the install setup and have a look into:
![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/f661acd2-434c-47b4-8186-3d75955f2dc6)

There should be everything "green"
