### ISSUE TITLE
[BUG]Using XPath to crawl web URL will lack the & symbol

### ISSUE THREAD

**Issue by JamYiz** [FreshRSS/FreshRSS#5430]
**Describe the bug**
When I use Xpath to crawl the web, the link can't crawl correctly, It lacks the '&'.

**To Reproduce**
1. Go to 'Type of feed source'
2. Enter 'https://website/forum.php?mod=viewthread&tid='
3. Open the feed crawl URL.
4. See the error

**Expected behavior**
I want it to show the URL correctly.
**Screenshots**
Even though I use concat to connect it, it still can't show  &.
![Snipaste_2023-05-29_19-03-05](https://github.com/FreshRSS/FreshRSS/assets/44351690/ba4e420d-c05e-47ba-9f36-44c3176f2678)
You can see the & symbol is missing.
![7G8Z$%2XISJH%T9H6ZI8E_C](https://github.com/FreshRSS/FreshRSS/assets/44351690/02e1f824-18cf-4f42-81f7-d95b28c03915)

**Environment information (please complete the following information):**
- OS: [e.g. Ubuntu 20.04]
- Browser: Firefox 113.0.2[e.g. Firefox 86]
- FreshRSS version:1.20.2  [e.g. 1.17.1]
- Database version: [e.g. Mysql 5.7]
- PHP version: [e.g. PHP 7.4]
- Installation type: [e.g. Yunohost]

**Additional context**

**Comment by math-GH** [comment]
Could you please update to the current FreshRSS 1.21.0 and test it again?

**Comment by HernandoR** [comment]
update:  remains at 1.21.1-dev

**Comment by Alkarex** [comment]
Please try this patch https://github.com/FreshRSS/FreshRSS/pull/5912
