### ISSUE TITLE
[Feature] Update Linkding sharing to pass title

### ISSUE THREAD

**Issue by acbgbca** [FreshRSS/FreshRSS#5432]
**Is your feature request related to a problem? Please describe.**
Linkding now supports passing the title to new bookmarks, following this PR: https://github.com/sissbruecker/linkding/pull/479

**Describe the solution you’d like**
The Linkding sharing integration should now pass the title to new bookmarks

**Describe alternatives you’ve considered**
N/A

**Additional context**
I'll create a PR shortly, just wanted a ticket number for the change

**Comment by Alkarex** [comment]
Thanks! You can directly send a PR, no need for an issue before
