### ISSUE TITLE
[Feature]different colors for different feeds post entries ?

### ISSUE THREAD

**Issue by rezad1393** [FreshRSS/FreshRSS#5441]
**Is your feature request related to a problem? Please describe.**
right now all the post from all feeds have the color. so in a list of post in a catogories I dont see which is for which feed based on color.
and because sort of post right now is not good (no sort based on publication nor feeds) it gets confusing. specially on my android phone that feeds titles are hidden and only post titles are there.

**Describe the solution you’d like**
different color for post belonging to different feeds when more than one feeds is shown. 
though it may not be completely possible when showing more than 5 feeds.

**Describe alternatives you’ve considered**
A clear and concise description of any alternative solutions or features you’ve considered.

**Additional context**

**Comment by math-GH** [comment]
Are you familiar with CSS?
With the extension CustomCSS, it is possible to configure it as you wish. Each line has a `data-feed` attribute with the ID of the feed.
With something like `.flux[data-feed=123] ...... {background-color: lightpink}` you could colour each feed
