### ISSUE TITLE
[BUG] "New articles" banner is chunky

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/FreshRSS#5443]
I am on edge, Chrome latest stable.

Following #4686, this issue has reappeared but on other themes.

There is a chunky banner on some of them.

Impacted:
Ansum
Dark
Mapco

Not impacted:
Alternative-Dark
Dark pink
Nord
Origine
Origine-compact
Pafat
Swage

I did not test deprecated themes.

**Comment by math-GH** [comment]
Cannot reproduce this issue with Dark theme:

![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/2c29fabd-52af-40ac-a6ef-d5d96fac0c6c)
