### ISSUE TITLE
[bug] automatic refresh does not work properly

### ISSUE THREAD

**Issue by aledeg** [FreshRSS/FreshRSS#545]
When the script that gets the information on new article, there is a header showing that there is new article.
However, if you are reading a category with no new article, the header does not show while you see new article counter changing. I did not try while reading a feed, but my guess is I will have the same problem.

**Comment by Alwaysin** [comment]
From what I understand, the actual behaviour is "the header is showing only if there is new articles in the current view".
But on my instance when I am on the main stream, it show me the blue header even if there is an article in a category which is not displayed in the main stream (this is what I went complaining about).

**Comment by math-GH** [comment]
I guess I fixed it with #3999

**Comment by math-GH** [comment]
@aledeg Could you please check if this bug is fixed in V1.19?
