### ISSUE TITLE
[BUG] https://daringfireball.net/feeds/main feed won't get processed

### ISSUE THREAD

**Issue by farcaller** [FreshRSS/FreshRSS#5450]
**Describe the bug**
A feed at https://daringfireball.net/feeds/main stopped getting updates. Re-adding this feed won't pull any articles. The [validator](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fdaringfireball.net%2Ffeeds%2Fmain) thinks the feed is sound.

It definitely fetches the feed fine as it's able to pull in the title and other metadata, but something breaks in the parsing step, as the lockfile (`/tmp/eeba08f0.freshrss.lock` in my case) is never removed, so after the first fetch attempt the parser is stuck at `Feed already being actualized: https://daringfireball.net/feeds/main`. Removing the lockfile manually doesn't help.

**To Reproduce**
1. Add https://daringfireball.net/feeds/main
2. Refresh it

**Expected behavior**
The feed loads.

**Screenshots**
N/A

**Environment information (please complete the following information):**
- Device: N/A
- OS: N/A
- Browser: N/A
- FreshRSS version: Docker's freshrss latest (verified on both 1.21.0 and 1.20.2).
- Database version: N/A
- PHP version: N/A
- Installation type: official docker image.

**Additional context**

**Comment by farcaller** [comment]
Further trying to debug, it was https://github.com/aledeg/xExtension-RedditImage:

```
PHP Fatal error:  Uncaught Error: Typed property RedditImage\Content::$contentLink must not be accessed before initialization in /var/www/FreshRSS/extensions/xExtension-RedditImage/Content.php:34
Stack trace:
#0 /var/www/FreshRSS/extensions/xExtension-RedditImage/Transformer/InsertTransformer.php(28): RedditImage\Content->getContentLink()
#1 /var/www/FreshRSS/lib/Minz/ExtensionManager.php(338): RedditImage\Transformer\InsertTransformer->transform()
#2 /var/www/FreshRSS/lib/Minz/ExtensionManager.php(309): Minz_ExtensionManager::callOneToOne()
#3 /var/www/FreshRSS/app/Controllers/feedController.php(477): Minz_ExtensionManager::callHook()
#4 /var/www/FreshRSS/app/Controllers/feedController.php(647): FreshRSS_feed_Controller::actualizeFeed()
#5 /var/www/FreshRSS/lib/Minz/Dispatcher.php(119): FreshRSS_feed_Controller->actualizeAction()
#6 /var/www/FreshRSS/lib/Minz/Dispatcher.php(48): Minz_Dispatcher->launchAction()
#7 /var/www/FreshRSS/lib/Minz/FrontController.php(58): Minz_Dispatcher->run()
#8 /var/www/FreshRSS/app/actualize_script.php(83): Minz_FrontController->run()
#9 {main}
  thrown in /var/www/FreshRSS/extensions/xExtension-RedditImage/Content.php on line 34
```

**Comment by farcaller** [comment]
@aledeg given you're poked in here – do I still need to reopen this against the correct repo?

**Comment by aledeg** [comment]
@farcaller , please do. It's easier to keep track of it

**Comment by aledeg** [comment]
But looking at the debug message (thank you for that), I think you should consider updating the extension. I've basically rewrote it last month to avoid such things. It is probably not perfect but it's better, especially it degrades gracefully when encountering some exceptions.
