### ISSUE TITLE
[BUG] Feed works in other reader but not in FreshRSS

### ISSUE THREAD

**Issue by fabiosirna** [FreshRSS/FreshRSS#5454]
**Describe the bug**
This feed https://www.anthropocenemagazine.org/feed/ works on others reader (e.g. NetNewsWire) but for some reasons it's not visible on FreshRSS. 
A bit of context: I added this feed in the past and I reinstalled freshRSS reimporting my feeds from an OPML list. There are a lot of errors and I have to manually refresh one by one. This is a bit of a frustration.

**To Reproduce**
1. Add https://www.anthropocenemagazine.org/feed/ or https://www.anthropocenemagazine.org/feed/#force_feed

**Expected behavior**
Even if the feed is not fully validated I'd expect to add the feed.

**Screenshots**

**Environment information (please complete the following information):**
- Browser: Firefox lates
- FreshRSS version: 1.21.0 
- Database version: SQLlite
- Installation type: self-hosted with docker compose

**Additional context**

Logs

```
https://www.anthropocenemagazine.org/feed/ is invalid XML, likely due to invalid characters. XML error: Invalid character at line 257, column 37 [https://www.anthropocenemagazine.org/feed/#force_feed] 
```

**Comment by Frenzie** [comment]
For reference, this is the invalid character:
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.anthropocenemagazine.org%2Ffeed%2F
```
This feed does not validate.

[line 391](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.anthropocenemagazine.org%2Ffeed%2F#l391), column 174: XML parsing error: <unknown>:391:174: not well-formed (invalid token) [[help](https://validator.w3.org/feed/docs/error/SAXError.html)]

... age" title="Popularity of nuclear power closing between democrats and r ...
                                             ^
In addition, interoperability with the widest range of feed readers could be improved by implementing the following recommendations.

[line 41](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.anthropocenemagazine.org%2Ffeed%2F#l41), column 0: content:encoded should not contain style tag (2 occurrences) [[help](https://validator.w3.org/feed/docs/warning/SecurityRisk.html)]

					<description><![CDATA[One pattern that emerged: beef, rice, and soybean ...
[line 41](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.anthropocenemagazine.org%2Ffeed%2F#l41), column 0: style attribute contains potentially dangerous content: background-image:url(https://www.anthropocenemagazine.org/wp-content/uploads/2018/07/mouse-and-wheat-stalks-285x188.jpg); (2 occurrences) [[help](https://validator.w3.org/feed/docs/warning/DangerousStyleAttr.html)]

					<description><![CDATA[One pattern that emerged: beef, rice, and soybean ...
[line 120](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.anthropocenemagazine.org%2Ffeed%2F#l120), column 0: Invalid HTML: Unexpected end tag (p). Ignored. (2 occurrences) [[help](https://validator.w3.org/feed/docs/warning/NotHtml.html)]

										<content:encoded><![CDATA[<p>Granite and soapstone likely conjure  ...
```

**Comment by fabiosirna** [comment]
as @Frenzie pointed out: U+0003 : ```<control> END OF TEXT [ETX]``` is the character.

**Comment by fabiosirna** [comment]
I'm closing this issue. Looks like the feed has been fixed now, and I was able to add the feed again. Thanks for your help.
