### ISSUE TITLE
[Feature] Add support for XPath 2.0

### ISSUE THREAD

**Issue by landonepps** [FreshRSS/FreshRSS#5467]
**Is your feature request related to a problem? Please describe.**
I want to parse Medium links which may or may not have garbage at the end that changes between accesses, making the URLs different and resulting in duplicate articles showing up.

For instance, take this URL:
```
https://fatbobman.medium.com/wwdc-23-first-impressions-of-swiftui-5-and-swiftdata-85d16df77e2c?source=user_profile---------3----------------------------
```
and this URL:
```
https://fatbobman.medium.com/wwdc-23-first-impressions-of-swiftui-5-and-swiftdata-85d16df77e2c
```

I want to be able to write an XPath that strips everything after the `?`, but to my knowledge there's no way to handle both the above cases.
The following works for the first URL, but it returns an empty string for the second.
```
substring-before(descendant::a[contains(@aria-label, 'Post Preview Title')]/@href, '?')
```

If FreshRSS had support for XPath 2.0, I could do something like this:
```
if (contains(descendant::a[contains(@aria-label, 'Post Preview Title')]/@href, '?')) 
then substring-before(descendant::a[contains(@aria-label, 'Post Preview Title')]/@href, '?') 
else descendant::a[contains(@aria-label, 'Post Preview Title')]/@href
```

**Describe the solution you’d like**
FreshRSS adds XPath 2.0 support, allowing us to write much more powerful expressions.

**Describe alternatives you’ve considered**
I realize that, unlike XPath 1.0, 2.0 support is not built into PHP. However, I think XPath 2.0 is probably an easier thing to support than adding scripting capability around XPath 1.0 to support these edge cases.

For the example above, I can probably use the article title as the ID. And maybe that's enough, since it's unlikely that 2 different articles will have the same title.

**Comment by Alkarex** [comment]
Not tested at all, but try something like:

```
substring-before(concat(descendant::a[contains(@aria-label, 'Post Preview Title')]/@href, '?'), '?')
```

XPath 2.0 will most likely not happen until it lands in PHP. For more complex cases, it is also easy to make a PHP extension, which gives access to the full PHP language.

**Comment by landonepps** [comment]
> substring-before(concat(descendant::a[contains(@aria-label, 'Post Preview Title')]/@href, '?'), '?')

Oh, nice. This should definitely work for me. I should have thought a bit more out of the box here.

> it is also easy to make a PHP extension with gives access to the full PHP language.

Yeah, actually that would be amazing and even better for handling edge cases than XPath 2.0.
I didn't know this was even on the table.

**Comment by Alkarex** [comment]
Yes, we already have good support for extensions in FreshRSS:
* https://freshrss.github.io/FreshRSS/en/developers/03_Backend/05_Extensions.html
* https://github.com/FreshRSS/Extensions

**Comment by K4LCIFER** [comment]
> XPath 2.0 will most likely not happen until it lands in PHP.

I came across [this](https://github.com/bseddon/XPath20).

**Comment by Alkarex** [comment]
> I came across [this](https://github.com/bseddon/XPath20).

Interesting. If anyone is motivated, this could be considered as a FreshRSS extension
