### ISSUE TITLE
Error log: "cURL error 22: The requested URL returned error: 503" [https://domain.tld/.rss] 

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#5479]
cURL errors appears with additional `"`

![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/0ba9b6a7-ec5c-4ca8-8f67-c7d5d13cd44e)

This could be the root, but it is not the reason for this additional character in the log
https://github.com/FreshRSS/FreshRSS/blob/723f7577d0a388a90779930754c5aacb9f66b168/lib/SimplePie/SimplePie/File.php#L127-L131

**Comment by Alkarex** [comment]
Please test https://github.com/FreshRSS/FreshRSS/pull/5480
