### ISSUE TITLE
[BUG] weird error for writings.stephenwolfram.com

### ISSUE THREAD

**Issue by daniporr** [FreshRSS/FreshRSS#5482]
Hi, after I added the following feed:

> https://writings.stephenwolfram.com/feed

I started to get the following error (at each update):

> PHP Notice: A feed could not be found at `https://writings.stephenwolfram.com/feed/`. Empty body. in [...]/lib/SimplePie/SimplePie.php on line 1518

but the feed is valid, as you can see here

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwritings.stephenwolfram.com%2Ffeed%2F

and I also got 12 articles when I added it (so, it was able to retrieve them at least once).

Why is this happening?
How can I fix it?

**Comment by Alwaysin** [comment]
It looks like it can be quite long to load the feed, try by setting something like 10 seconds for "Timeout in seconds" in the feed setting.

**Comment by daniporr** [comment]
Thank you for your quick answer.

I have tried that and will let you know as soon as it refreshes.

**Comment by daniporr** [comment]
Unfortunately it did not work.

Should I try an higher value? (something like 20 seconds)

**Comment by daniporr** [comment]
Now I am getting the following error:

> PHP Notice: A feed could not be found at `https://writings.stephenwolfram.com/`; the status code is `200` and content-type is `text/html; charset=UTF-8` in [...]/lib/SimplePie/SimplePie.php on line 1829

I noticed that this refers to the base URL (and not the feed one), so I checked the "Feed URL" parameter and now it contains:

> https://writings.stephenwolfram.com/

but if I try to change it to `https://writings.stephenwolfram.com/feed/`, when I click the "Submit" button, it (automatically) gets back to `https://writings.stephenwolfram.com/`.

Do you know what is going on here?

**Comment by math-GH** [comment]
I cannot confirm this issue.

@daniporr : which FreshRSS version do you use? With a database (f.e. MySQL) or SQlite?

**Comment by daniporr** [comment]
I have investigated this further, and I discovered that I had this feed twice (I do not know how that is possible, FreshRSS usually tells you when you are trying to subscribe to an existing RSS Feed).

That was probably the reason why I was not able to modify the URL and why I was getting two different errors.

I removed one of them.
I think this should solve the problem.
I am closing the issue now (I will re-open if it reappears).

Thank you everyone for your help!

**Comment by Alkarex** [comment]
There is a known problem if you add a feed A and a feed B, and then later feed A gets redirected to feed B, then feed A breaks because feed B already exists. The difference between A and B can be quite minor, e.g. http vs. https, with or without trailing slash...
