### ISSUE TITLE
[BUG] Clicking article titles in the feed opens them in a new tab immediately, in Safari only

### ISSUE THREAD

**Issue by kemayo** [FreshRSS/FreshRSS#5487]
**Describe the bug**
When viewing the article stream, you need to click on the titles of articles to open them. In Safari, if you click on the actual text in the title, it immediately (a) expands the article, and (b) follows the article link in a new tab. If you click not directly on the linked title text it will only expand the article.

**To Reproduce**
1. Use Safari
2. Go to the main stream
3. Click on any article title
4. Observe that it has opened in a new tab

**Expected behavior**
As in other browsers, the article should only have opened.

**Environment information (please complete the following information):**
- Device: MacBook Pro
- OS: macOS 13.4.1
- Browser: Safari 16.5.1
- FreshRSS version: 1.21.0
- Database version: Ver 15.1 Distrib 10.3.39-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
- PHP version: 7.3.31-1~deb10u3
- Installation type: git checkout of the 1.21.0 tag

**Comment by Alkarex** [comment]
The most likely reason is that the JavaScript is not loaded at all.
Check your Web browser logs for errors / warnings, and your Web browser settings / extensions.

**Comment by kemayo** [comment]
You are quite right, thank you -- I had thought it probably wasn't an extension because I'd tried it without content blockers enabled, but it turns out that this is StopTheMadness's "stop link trackers" option interfering in some way. I'll go submit bug feedback to them instead. 👍🏻
