### ISSUE TITLE
[Feature] Fetch full articles as an option or by default

### ISSUE THREAD

**Issue by iSaluki** [FreshRSS/FreshRSS#5488]
I find it frustrating when I only get a small snippet of an article in my reader, so is it possible to fetch full articles? I have looked through lots of issues and forum posts related to doing this in FreshRSS and haven't found a solution that works yet. 

And if not, is it something that can be added in future?

**Comment by math-GH** [comment]
First things first to understand the background:
It is the decision of the feed owner which information are given by the feed. Some of them give just the teaser, others give the whole article. It is their choice. RSS readers read just the feed content and display it. That is how FreshRSS works too.

But it is possible to scrap the given link from the RSS feed. That is possible in FreshRSS too. But it is not so simple to know what is the main article of a website full of content. Not everything is from the article. It needs some configuration. That is possible in FreshRSS.

The question could be: Is there any library, that could help to detect the "main" content directly? There are some apps that can scrap the full text from website.

**Comment by iSaluki** [comment]
I have just used CSS selectors and it *seems* to be working fine. Another solution would be nicer but this does do the job.

**Comment by toketin** [comment]
Hi, can you explain me please how have you achieved the full articles?

**Comment by hkcomori** [comment]
I want to get the full article, even with HTML + XPATH Scraping.
In most cases, only the title and URL of each article can be retrieved from the scraped page.
Just being able to apply XPATH again for each URL page would be very useful.

This is a just idea, but what about adding a axis of dialects (eg: `freshrss-item`) to [XPath Axes](https://developer.mozilla.org/en-US/docs/Web/XPath/Axes)?

```XPATH.
freshrss-item::div[@class="main"]/article
```

With this axes, the same interface can be used to extract author and date from item pages too.

**Comment by math-GH** [comment]
If you need support to set up a CSS selector or the XPATH web scrapping then please use our discussion board here.
Please open a new thread for each website.

Here is the discussion board: https://github.com/FreshRSS/FreshRSS/discussions

**Comment by hkcomori** [comment]
@math-GH 
Sorry if I misunderstood.

I read the following statement to mean that it is technically possible with FreshRSS (but only if some features are added).

> But it is possible to scrap the given link from the RSS feed. That is possible in FreshRSS too. But it is not so simple to know what is the main article of a website full of content. Not everything is from the article. It needs some configuration. That is possible in FreshRSS.

If not, does it mean that the current version of FreshRSS can retrieve articles from each item's page, just by configuration?
If so, that certainly misses the point of the feature request, so I'll move on to the discussion.

**Comment by hkcomori** [comment]
Sorry, I was wrong.

I found that the [Readable extension](https://github.com/printfuck/xExtension-Readable) can be used [here](https://github.com/FreshRSS/FreshRSS/discussions/5990) to retrieve the full text.
Some pages do not get it right and cannot be adjusted on the user side, but generally it seems to work well.

**Comment by hkcomori** [comment]
I found that articles are always unread when both Readable and 'Mark updated articles as unread' are used.

Readable uses `entry_before_insert` to replace the entry content with the full article.
On the other hand, FreshRSS uses the original content to determine updated.
It always misidentifies it as updated because it compares the hash of the original content and the full article.

I don't think there is any solution on the extension side, because there is no suitable hook other than `entry_before_insert`.

**Comment by Alkarex** [comment]
Undocumented trick, while waiting for something better: https://github.com/FreshRSS/FreshRSS/issues/2688#issuecomment-560268673

**Comment by hkcomori** [comment]
> I have just used CSS selectors and it seems to be working fine.

Ah.., sorry. Above mentioned was referring to [this feature](https://freshrss.github.io/FreshRSS/en/users/04_Subscriptions.html#retrieve-a-truncated-feed-from-within-freshrss). I found it at last.
My misunderstanding of the description of the settings view made me think it was for a completely different purpose.

@Alkarex
My problem is that an existing entry with no updates is determined to have been updated.
But with [this feature](https://freshrss.github.io/FreshRSS/en/users/04_Subscriptions.html#retrieve-a-truncated-feed-from-within-freshrss), the content will be replaced with the full article before the update determination is made, so I think there is not problem.

Thank you.

**Comment by Alkarex** [comment]
> so I think there is not problem.

Just to be sure: is the problem solved, then? If not, please explain again what remains to be solved

**Comment by hkcomori** [comment]
My problem was solved. [CSS selector](https://freshrss.github.io/FreshRSS/en/users/04_Subscriptions.html#retrieve-a-truncated-feed-from-within-freshrss) is enough for me.
I guess that author's problem has been solved too, because he said below:
https://github.com/FreshRSS/FreshRSS/issues/5488#issuecomment-1605414598
