### ISSUE TITLE
[BUG] Feed moved moved permanently - SQL error FreshRSS_FeedDAO::updateFeed

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#5491]
**Describe the bug**

After a long time I updated the feeds that I imported via the dyn. OPML: https://raw.githubusercontent.com/kilimchoi/engineering-blogs/master/engineering_blogs.opml

It generated a lot of log entries:

![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/01f97cfc-7ee5-4289-bd32-744e1fb0294e)

`SQL error FreshRSS_FeedDAO::updateFeed["23000",19,"UNIQUE constraint failed: feed.url"] for feed 1893 `

**Environment information (please complete the following information):**
- FreshRSS version: 1.21.1-dev
- database: SQlite

**Comment by Alkarex** [comment]
Do you have another subscription to e.g. https://8thlight.com/insights/feed/atom.xml ?

**Comment by math-GH** [comment]
(I updated the description to be more clear)

**Comment by math-GH** [comment]
How the dyn. OPML looks like:
![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/519be051-7030-4815-b16b-4a593c68ff34)


I have this feeds only once imported (via the OPML)

**Comment by Alkarex** [comment]
What do you mean more precisely by *I updated the feeds that I imported via the dyn. OPML*?

**Comment by math-GH** [comment]
I mean:
Some month ago I added the dyn. OPML: https://raw.githubusercontent.com/kilimchoi/engineering-blogs/master/engineering_blogs.opml to a feed category.
June 19th: I hit the "update feed" button first time for a long time.
It created the log entries.

**Comment by math-GH** [comment]
same issue with the current 1.23.2-dev edge.

**Comment by Alkarex** [comment]
With SQLite, could you try https://github.com/FreshRSS/FreshRSS/issues/4229#issuecomment-2083544557

**Comment by Alkarex** [comment]
Same than https://github.com/FreshRSS/FreshRSS/issues/4229

**Comment by math-GH** [comment]
The SQlite update via
```
./cli/db-backup.php
./cli/db-restore.php --force-overwrite
```

fixed this bug
