### ISSUE TITLE
[BUG] Muting a feed forces its refresh value

### ISSUE THREAD

**Issue by Epy** [FreshRSS/FreshRSS#5506]
**Describe the bug**
Hello
When I mute a feed to avoid it being refreshed, its value for "Don't refresh more often than.." is forced to 8 hours despite using "Default"
If I try to change it while muted, it goes back to 8 hours on validation. 8 hours is my global setting it could be linked to this value.

**To Reproduce**
(Sorry if text is not the exact one, I'm using french WUI)
1. Go to 'Feeds management'
2. Pick one feed and "manage"
3. Change to "Disable"
4. Validate
5. Value of limit to refresh has changed to "8h"
6. Try to change it back
7. Validate
8. It goes back to "8h"
9. Re-enable the feed
10. It stays on 8h

**Expected behavior**
As I'm managing the refresh limit globally unless I absolutely need to limit a feed to something less frequent, I'd like this setting to stay on "default" this way I can later still change this value globally and not going on every feed to change it back to default.
Just changing the global value twice to other values can create asynchronous feed retrieval.

**Screenshots**
![image](https://github.com/FreshRSS/FreshRSS/assets/450856/7865e33f-e9bd-41ba-9754-b32124c7ae7d)

**Environment information (please complete the following information):**
- Device: PC
- OS: Debian 11
- Browser: Firefox 102.12
- FreshRSS version: 1.21 (problem appeared on older version but I forgot to create an issue)
- Database version: PostgreSQL 15
- PHP version: 7.4.33
- Installation type: Manual

Thanks !

**Comment by Epy** [comment]
It seems to be fixed ? At least in 1.24.3 but it's been a while I didn't try

**Comment by Alkarex** [comment]
Thanks for the feedback. Probably fixed by https://github.com/FreshRSS/FreshRSS/pull/6115
