### ISSUE TITLE
[BUG] Editing user queries deletes the feed information

### ISSUE THREAD

**Issue by robhuen** [FreshRSS/FreshRSS#5514]
**Describe the bug**
Editing user queries deletes the feed information ('Display "..." feed')  and it cannot added again via the "type" dropdown menu. 

**To Reproduce**

1. Create a query by
* Selecting a feed
* Searching
* Using the function "bookmark current query"

-- the result is as expected. 

2. Edit the query
* Go to 'User queries'
* Edit the query and change e.g. only the name
* Click Submit

-- the information on which feed the query shall be performed on is deleted. 

**Environment information: **
- Device: Mac
- OS: Ventura 13.4.1
- Browser: Chrome  114.0.5735.198
- FreshRSS version: 1.21.1-dev [6f4c6f8]
- Database version: SQLite
- PHP version: 8.2.7
- Installation type:

**Comment by robhuen** [comment]
One more note: 

After switching the branch from edge to latest the function works as expected.

**Comment by Alkarex** [comment]
Thanks for the bug report!
Would you be able to test https://github.com/FreshRSS/FreshRSS/pull/5515 ?

**Comment by robhuen** [comment]
Thank you for the quick help.

I switched back to edge ([6f4c6f8](https://github.com/FreshRSS/FreshRSS/commit/6f4c6f89938d625eb70a11765d99290e1f6d6243)) and applied https://github.com/FreshRSS/FreshRSS/pull/5515 .

--Result: Editing user queries  works as expected.

**Comment by Alkarex** [comment]
Thanks for the feedback 👍🏻
