### ISSUE TITLE
[BUG] Cannot read particular feed

### ISSUE THREAD

**Issue by techexo** [FreshRSS/FreshRSS#5517]
Hello,

I have troubles adding the following feed to FreshRSS 1.21.0: https://www.science.org/blogs/pipeline/feed
associated with this website: https://www.science.org/blogs/pipeline

In the logs:

> Unknown error for feed [https://www.science.org/blogs/pipeline/feed]
> cURL error 22: The requested URL returned error: 403 [https://www.science.org/blogs/pipeline/feed]

Opening the feed in a browser seems to work, however.

Any idea? :-)

Thanks in advance,
Eloi

**Comment by math-GH** [comment]
The feed is delivered by HTTP/3 and the current implementation with curl does not check HTTP/3 only the older ones.

ping @Alkarex for more background information

**Comment by Frenzie** [comment]
It's just Cloudflare protection getting in the way. See https://github.com/FreshRSS/FreshRSS/issues/5296 etc.

**Comment by Frenzie** [comment]
> The feed is delivered by HTTP/3 and the current implementation with curl does not check HTTP/3 only the older ones.

Cloudflare is perfectly happy serving HTTP/2 or HTTP 1.x ftr. In my Firefox it's not even using HTTP/3 for that matter? It does however somehow realize that it's cURL (and I don't just mean by user agent).

**Comment by Alkarex** [comment]
Long delay here, but works for me out of the box from two different servers
![image](https://github.com/FreshRSS/FreshRSS/assets/1008324/02b5f8a9-7ac6-432f-ab49-f10856c0b50c)
