### ISSUE TITLE
demo.freshrss.org has an uncategorized porn feed on it

### ISSUE THREAD

**Issue by invicticide** [FreshRSS/FreshRSS#5530]
It's a reddit feed called "submitted by ChanceEconomy1702".

I feel like that is probably unintended, yeah?

**Comment by Frenzie** [comment]
I think it's automatically reset every x hours. Pinging @marienfressinaud

**Comment by math-GH** [comment]
Thanks for reporting. I deleted the feed yesterday

**Comment by marienfressinaud** [comment]
Thanks for reporting and @math-GH for deleting the feed!

I've increased the frequency of the cron task: the demo will be reset every two hours now.
