### ISSUE TITLE
Is it possible to get a HTML+XPath feed from a Twitter page

### ISSUE THREAD

**Issue by Altdarkzodiac** [FreshRSS/FreshRSS#5532]
### Discussed in https://github.com/FreshRSS/FreshRSS/discussions/5498

<div type='discussions-op-text'>

<sup>Originally posted by **richard3840** June 27, 2023</sup>
I have been experimenting with HTML + XPath (Web scraping), and have identified all the necessary queries to get the data needed for a complete feed of a Twitter page in FreshRSS.

I have tested them in the browser inspector and console to correctly return the content for all the different feed data types. Below are the queries.

```
XPath for: feed title
.//div[@data-testid="UserName"]

XPath for: finding news items (most important)
//article[@data-testid="tweet"]

XPath (relative to item) for: item title
.//div[@data-testid="tweetText"]

XPath (relative to item) for: item content
.//div[@class="news-content"]

XPath (relative to item) for: item link (URL)
.//div[@data-testid="User-Name"]//time/parent::*/@href

XPath (relative to item) for: item thumbnail
.//div[@data-testid="Tweet-User-Avatar"]//img/@src

XPath (relative to item) for: item author
.//div[@data-testid="User-Name"]/child::*[1]

XPath (relative to item) for: item date
.//div[@data-testid="User-Name"]//time/@datetime

XPath (relative to item) for: item unique ID
.//div[@data-testid="tweetText"]/@id
```

They were tested in the browser console with the following code:

```
//var xpath_query = '//div[@itemtype="http://schema.org/NewsArticle"]/@id'
//var xpath_query = '//time'
//var xpath_query = './/div[@data-testid="User-Name"]//time/parent::*/@href'
//var xpath_query = './/div[@data-testid="Tweet-User-Avatar"]//img/@src'
//var xpath_query = './/div[@data-testid="User-Name"]//time/@datetime'
var xpath_query = './/div[@data-testid="tweetText"]/@id'

var nodes = document.evaluate(xpath_query, document, null, XPathResult.ANY_TYPE, null);
var result = nodes.iterateNext();
while (result) {
  console.log(result.value);
  console.log(result.textContent);
  result = nodes.iterateNext();
}
```

However when i put it in FreshRSS, it fails to add the feed. The log file ("data\users\(user)\log.txt") shows the following error:

```
[Tue, 27 Jun 2023 18:14:31 +0200] [warning] --- Error fetching content: HTTP code 302: Maximum (4) redirects followed https://twitter.com/RetrogradeTom
[Tue, 27 Jun 2023 18:14:31 +0200] [warning] --- HTML+XPath Web scraping failed for [https://twitter.com/RetrogradeTom]
```

So my question is whether anyone has had any success getting HTML + XPath to work with a Twitter page, and if there is something i can do to get it working.

</div>

// Edit by math-gh: Spam lines deleted

**Comment by Altdarkzodiac** [comment]
Yes, it is possible to get an XHTML page from Twitter. [XHTML is a term that was historically used to describe HTML documents written to conform with XML syntax rules](https://developer.mozilla.org/en-US/docs/Glossary/XHTML)¹. Here is an example of an XHTML document with a minimum of required tags²:

```html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML [1](https://developer.mozilla.org/en-US/docs/Glossary/XHTML).1//EN"
"http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title> Title of document </title>
</head>
<body>
</body>
</html>
```

I hope that helps! Let me know if you have any other questions.

**Comment by math-GH** [comment]
To make it short: Twitter locked the public reading. I do not see any chance anymore to scrap the content.
