### ISSUE TITLE
[BUG] Regression in b438d8bb3d4b3dea6d28d0b0c73da9393c9d8299

### ISSUE THREAD

**Issue by nicofrand** [FreshRSS/FreshRSS#5537]
**Describe the bug**

ThreePanesView detect legacy FreshRSS that did not have the 'openArticle' event yet by checking `window.freshrssOpenArticleEvent` (introduced in  https://github.com/FreshRSS/FreshRSS/commit/da4a80b88a64855bd62d996baabaaf25497c5f42#diff-86db6bc50f24e839f927bdd2262ce6d58c450fb23b13f8e9e5501b047add9bbaR240)

See https://framagit.org/nicofrand/xextension-threepanesview/-/blob/master/static/threepanesview.js#L155

The commit https://github.com/FreshRSS/FreshRSS/commit/b438d8bb3d4b3dea6d28d0b0c73da9393c9d8299#diff-86db6bc50f24e839f927bdd2262ce6d58c450fb23b13f8e9e5501b047add9bba replaced `var` with `const` which makes this variable not available on the global object.

Should I remove the support of legacy versions, in which case is there a way to check FreshRSS version on the client side?
Or should this be fixed in FreshRSS?

**Comment by Frenzie** [comment]
I think it's fair enough to say use the old version for old and the new version for new. That being said, I see a freshrssOpenArticleEvent on window in 1.21.0?

**Comment by nicofrand** [comment]
I did not understand sorry. Which old version for which old?

I do  not have different versions of the plugin based on the freshrss version.

Is there a version available on the current side I can rely on to check it? Otherwise I will have to remove legacy support (I won't maintain several versions with fixes to backport etc).

Did you try on the demo for example for the window variable?

Le 18 juillet 2023 13:29:11 GMT+02:00, Frans de Jonge ***@***.***> a écrit :

**Comment by nicofrand** [comment]
Hm, `freshrssOpenArticleEvent` is still available on the global scope, just not on window, I guess I can shift to that…

**Comment by Frenzie** [comment]
Huh, I thought window was the global scope (in the browser). Whatever's going on here is new to me.

**Comment by nicofrand** [comment]
It is but `const`, unlike `var` are not attached to `window`. It seems to still be available directly though (no closure etc.), without prefixing with `window`.

**Comment by Frenzie** [comment]
Yes, that's what I'd tested assuming it was the same. :-)

**Comment by nicofrand** [comment]
I can close this issue as I have a workaround but I might not be the only extension dev meeting the issue, and also, having the version on the client side could be nice, it would allow to act accordingly.

I don't think there is a way to mark an extension as only compatible with version <= x => ?

**Comment by Alkarex** [comment]
> having the version on the client side could be nice, it would allow to act accordingly

Implemented in https://github.com/FreshRSS/FreshRSS/pull/5902 Feedback welcome
