### ISSUE TITLE
[BUG] RSS feed (rss.phtml) does not contain enclosures

### ISSUE THREAD

**Issue by J4kubS** [FreshRSS/FreshRSS#5539]
**Describe the bug**
The RSS feed generated by `rss.phtml` does not contain enclosures. The issue seems to be caused by [this](https://github.com/FreshRSS/FreshRSS/blob/edge/app/views/index/rss.phtml#L51) `is_array` condition, which always fails because `$item->enclosures(false)` returns a generator [here](https://github.com/FreshRSS/FreshRSS/blob/edge/app/Models/Entry.php#L240).

**To Reproduce**
1. Add a feed with enclosures (for example [Arch Linux releases](https://archlinux.org/feeds/releases/))
2. Open the feed
3. Open an article to check that the enclosures were loaded from the original RSS feed
4. Click on 'RSS feed'
5. The enclosures are missing 

**Expected behavior**
The RSS feed should contain enclosures from the original RSS feed.

**Environment information (please complete the following information):**
- FreshRSS version: 1.21.0
- Database version: PostgreSQL 10.4
- Installation type: `freshrss/freshrss:alpine` Docker image

**Comment by Alkarex** [comment]
Thanks for the bug report. Would you be able to test https://github.com/FreshRSS/FreshRSS/pull/5540 ?

**Comment by J4kubS** [comment]
Just tested the `fix_yield_enclosures` branch with a similar Docker setup. The feed now contains a `<media:content ...></media:content>` element for every enclosure in the source feed.

**Comment by Alkarex** [comment]
Thanks for the quick feedback 👍🏻
