### ISSUE TITLE
[Suggestion] Improve the theme selector

### ISSUE THREAD

**Issue by brihuang99** [FreshRSS/FreshRSS#5556]
**Is your feature request related to a problem? Please describe.**
I've been using FreshRSS and only realized that there were themes I could select under 'Display'... I do partially feel dumb about it, but I do think that there could be some benefit in making it clearer in the UI that there were multiple themes to choose from, as the arrows for the "slide-container" do not appear unless you hover over it. 

![Screenshot_20230801_155800](https://github.com/FreshRSS/FreshRSS/assets/122472324/805f8c6a-cd4c-4b7d-ab9a-b8281c6ba026)

**Describe the solution you’d like**
I think that exposing a handful of themes in a grid-like format could make it clear that there are multiple themes to choose from and clearly indicate which one has been selected. Here's a screenshot of what Gmail does for reference:

![Screenshot_20230801_155851](https://github.com/FreshRSS/FreshRSS/assets/122472324/3bfef026-eec6-45ce-8a4b-f7943ad07135)

**Describe alternatives you’ve considered**
If we're concerned about space, maybe having the arrows appear at all times could help users understand that the "slide-container" area is interactive, or we could consider using a drop down of some sort.

**Comment by math-GH** [comment]
Good point!
