### ISSUE TITLE
Importing personalized youtube feed from self hosted RSShub into Freshrss (curl error 28)

### ISSUE THREAD

**Issue by SecondaryH** [FreshRSS/FreshRSS#5565]
Hello,

I'm currently running FreshRSS and RSShub on a server both through their own docker (compose). I made a personalized youtube feed through RSShub which I want to import in my FreshRSS instance.

Upon trying to import the feed into FreshRSS it returns a curl error 28
![firefox_9BMgoFcxAz](https://github.com/FreshRSS/FreshRSS/assets/76407423/6ec4d732-5962-490e-872d-2690c1f081ad)

I've tried adjusting the timeout to see if that would make a difference but to no avail. 

Importing it into feeder.co does work and shows the proper feed so I'm assuming its related to something else.

I took a look at #3428 but that issue was regarding running both services through 1 docker compose which is not the case for me.

- OS: ubuntu 20.04
- Browser: Firefox 115.0.3
- FreshRSS version: 1.21.0
- PHP version: PHP 7.4.3 
- Installation type: Docker Compose

**Comment by SecondaryH** [comment]
Solved by opening ports!

Please close this issue

**Comment by Frenzie** [comment]
You can too (on your own issues). ^_^
