### ISSUE TITLE
[BUG] I keep getting read feeds marked as unread again

### ISSUE THREAD

**Issue by karhima** [FreshRSS/FreshRSS#5568]
Several of my feeds show entries I've read and entries that are months and even years old again and again as unread. It's not all feeds and it doesn't happen every day, but with some feeds it never happens at all. I have unchecked "Mark updated articles as unread" if that matters.

**To Reproduce**
Cannot reproduce it consistently. Sometimes it works, then they keep coming back.
One of them coming back with the same 10 entries is FreshRSS Releases for example.

**Expected behavior**
Once marked as read, entries and feeds should remain read.

**Environment information (please complete the following information):**
- Device: PC
- OS: Linux Mint 21.2 Cinnamon
- Browser: Firefox 116.0
- FreshRSS version: 1.21.0
- Database version: where can I find that
- PHP version: where can I find that
- Installation type: https://feeds.flossboxin.org.in

**Comment by math-GH** [comment]
Could you please have a look into the logs (`?a=logs`)?

**Comment by karhima** [comment]
Sorry for the late reply, haven't used it in a while.
I'm getting tons of errors in the log:

2023-08-31 02:31:26 | image_cache_access_token does not exist in configuration
 2023-08-31 02:31:26 | Log rotate.
 2023-08-31 02:31:26 | image_cache_post_url does not exist in configuration
 2023-08-31 02:31:26 | Log rotate.

2023-08-31 08:55:43 | in_player_instance does not exist in configuration
 2023-08-31 08:55:43 | in_show_content does not exist in configuration
 2023-08-31 08:55:43 | in_player_height does not exist in configuration
 2023-08-31 08:55:43 | in_player_width does not exist in configuration

Should I try a different public instance?

**Comment by raev33** [comment]
I have the same issue, but I think it's with all my feeds, where month old entries keeps reapering. I'm also using a public instance, and the log writes the following error over and over again:

  | 2023-09-01 10:12:09 | in_player_instance does not exist in configuration
-- | -- | --
  | 2023-09-01 10:12:09 | in_show_content does not exist in configuration
  | 2023-09-01 10:12:09 | in_player_height does not exist in configuration
  | 2023-09-01 10:12:09 | in_player_width does not exist in configuration
  | 2023-09-01 10:12:09 | in_player_instance does not exist in configuration
  | 2023-09-01 10:12:09 | in_show_content does not exist in configuration
  | 2023-09-01 10:12:09 | in_player_height does not exist in configuration
  | 2023-09-01 10:12:09 | in_player_width does not exist in configuration
  | 2023-09-01 10:12:09 | in_player_instance does not exist in configuration
  | 2023-09-01 10:12:09 | in_show_content does not exist in configuration

**Comment by Alkarex** [comment]
Hello,
Messages such as `in_show_content` do not come from the core of FreshRSS, but most likely an extension

**Comment by raev33** [comment]
The instance I use flossboxin.org.in has 6 extensions enabled that I can't disable. Is there any other way I can't help to locate the problem?

**Comment by math-GH** [comment]
Could you please share a screenshot of the extension page?

**Comment by raev33** [comment]
This are the extensions enabeld.
![IMG_20230904_224856](https://github.com/FreshRSS/FreshRSS/assets/15526972/2eb02183-fde1-44a3-aa97-00888710fc0d)

**Comment by karhima** [comment]
For me the same extensions are enabled and cannot be disabled.

**Comment by math-GH** [comment]
The Google Groups and Tumblr GDPR extension will be delivered by default. The other extensions are not official supported (exept the TTRSS API).

Please contact your instance adminstrator to make it possible to disable the system extensions.

**Comment by raev33** [comment]
I tried to switch to an instance that has fewer extensions enable, I don't know if the extensions are the issue, but I'm no longer getting old entries marked as unread.

**Comment by MortRainey** [comment]
Same issue here. No extensions enabled. :-(

**Comment by Alkarex** [comment]
@MortRainey 

* What FreshRSS version? (be sure to be using 1.22.1 or edge)
* Check also what settings you have for *Mark updated articles as unread*:
![image](https://github.com/FreshRSS/FreshRSS/assets/1008324/455e7fc5-6668-4728-93a1-83e8a48489c4)
* Do you end up with several copies of the same article (typically a sign that the upstream feed has republished an article with e.g. a new URL / guid), or with the same article, that gets marked as unread?
* Do you have an example of feed, for which it occurs?

**Comment by MortRainey** [comment]
Version is 1.22.1

for example its https://www.trackawesomelist.com/rss.xml 

My log only shows some errors that a feed couldn't be refreshed. Nothing more.

Every time there ist a new entry the old news are also marked as unread. I don't think they get updated every time. But i will try disabling the option and keep an eye on it. 

Thank you @Alkarex

**Comment by MortRainey** [comment]
@Alkarex the option did the trick. Today i got a new entry for awesome selfhost and the old news did not get marked as unread. So it looks like somthing is changed in the old ones that lead to freshrss marking it as updated article. 

Thanks for your help!
