### ISSUE TITLE
[BUG] FreshRSS showing no articles in subscription lists

### ISSUE THREAD

**Issue by Emagelle** [FreshRSS/FreshRSS#5575]
**Describe the bug**
FreshRSS showing no articles. During syncing it had the correct number for unread article same as the web, but cannot load any (only categories are showing). I had tried using VPN global on my phone and China mode in app. Didn't help.

**To Reproduce**
1. Setup api password on rss.rssforever.com
2. Click on FeedMe app
3. Add service freshrss (host: https://rss.rssforever.com/api/greader.php with username and passowrd)
4. login sucessfully and tap sync button (will show the correct unread article number same as website)
5. see all categories with no feeds.

**Expected behavior**
seeing all unread and read articles that I can click on.

**Screenshots**
![image](https://github.com/FreshRSS/FreshRSS/assets/49598414/74fa85bf-8d3b-435e-8458-f71793e798ad)

**Environment information (please complete the following information):**
- Device: RMX3569 (Realme GT Neo 3)
- OS: Android 13
- FreshRSS version: 1.20.2
- app version: gplay 3.20.14

**Additional context**

**Comment by Emagelle** [comment]
![Screenshot_2023-08-09-13-42-38-72_547cb517dbc67c82fd4f9b8f2ef91c95.jpg](https://github.com/FreshRSS/FreshRSS/assets/49598414/1ee08593-d18b-4394-bf31-4d723ab657a7)

**Comment by Emagelle** [comment]
sorry, this probably should be posted on FeedMe.

**Comment by Alkarex** [comment]
For info, works for me. Tested with the edge version of FreshRSS and the latest FeedMe, after hitting the refresh button in FeedMe.

**Comment by Emagelle** [comment]
> For info, works for me. Tested with the edge version of FreshRSS and the latest FeedMe, after hitting the refresh button in FeedMe.

I dont' know why, I've tried both on my android 11 tab and my phone, FeedMe can't get any articles. But same info put into FluentReader on my PC, it can get everything just fine.

**Comment by Alkarex** [comment]
Please try with the edge version of FreshRSS if you have not done so already.
Furthermore, you can look at your Web server logs and FreshRSS logs to see what requests are coming from your client.

**Comment by Emagelle** [comment]
> Please try with the edge version of FreshRSS if you have not done so already. Furthermore, you can look at your Web server logs and FreshRSS logs to see what requests are coming from your client.

Oh, thank you. I've found the root reason causing this were "GReader Redate plugin" under extention option in FreshRSS. For info, this is how to solve it.
https://github.com/seazon/FeedMe/issues/579#issuecomment-1671140559

**Comment by Alkarex** [comment]
Ping @javerous

**Comment by Alkarex** [comment]
It might be worth opening an issue (or even a pull request if you can) in https://github.com/javerous/freshrss-greader-redate

**Comment by javerous** [comment]
@Alkarex Thanks for the ping. I didn't notice issues on my side (and I still use FreshRSS and my extension very frequently), but I didn't install the updated versions of my own extension which included FeedMe #shame…

I will try to figure out what is the issue.

(Perhaps related to https://github.com/javerous/freshrss-greader-redate/issues/4 — I didn't have the time to check :/)

**Comment by javerous** [comment]
@Emagelle I think it's fixed, if you want to take a look.

- HEAD of `https://github.com/javerous/freshrss-greader-redate` / `master`
or
- [xExtension-GReaderRedate.tgz](https://github.com/FreshRSS/FreshRSS/files/12306810/xExtension-GReaderRedate.tgz)

**Comment by Alkarex** [comment]
Updated as well on https://github.com/FreshRSS/Extensions/commit/048d559707fe95d508f600a624ef08422bae3d2a
