### ISSUE TITLE
[BUG] RSS feed containing html in the content is escaped 

### ISSUE THREAD

**Issue by RichyHBM** [FreshRSS/FreshRSS#5585]
**Describe the bug**
RSS feed containing html in the content is escaped, meaning the html formatting is lost.
I am using an RSS feed that scrapes content from github releases, this keeps all the html tags used for formatting the content in the feed, however as html elements are escaped this means the content in freshrss is not formatted

**To Reproduce**
Add https://selfh.st/releases/feed/latest/project/freshrss.xml as feed, see entries

**Expected behavior**
Remove HTML elements from content, or better yet render them as part of the page to keep full formatting. Ideally this would be an advanced toggle as by default we may not want this to be enabled (for security)

**Screenshots**
![image](https://github.com/FreshRSS/FreshRSS/assets/5472275/8639169e-2362-4937-9579-072b32b015e8)
![image](https://github.com/FreshRSS/FreshRSS/assets/5472275/f21a4460-c8d0-4b90-a1f9-604c44bfedd7)

How it currently looks, vs how it could look using js:
`var text = document.getElementsByClassName('text')`
`text[0].innerHTML = text[0].textContent`

**Environment information (please complete the following information):**
- Device: FreshRSS 1.21.0
- OS: LinuxServer FreshRSS Docker
- Browser: Latest Brave
- FreshRSS version: 1.21.0
- Installation type: Docker

**Additional context**

**Comment by math-GH** [comment]
The feed does not validate good:
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fselfh.st%2Freleases%2Ffeed%2Flatest%2Fproject%2Ffreshrss.xml

![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/d0cd3e20-20ec-4fe2-bf42-8df7e21ca2f0)

**Comment by Frenzie** [comment]
Indeed, crucially compare it with (presumably?) the original at https://github.com/FreshRSS/FreshRSS/releases.atom


```xml
<content type="html">&lt;ul&gt;
&lt;li&gt;&lt;a href=&quot;https://github.com/FreshRSS/FreshRSS/milestones/1.21.0&quot;&gt;Milestone&lt;/a&gt;&lt;/li&gt;
&lt;/ul&gt;
&lt;p&gt;A few highlights &lt;g-emoji class=&quot;g-emoji&quot; alias=&quot;sparkles&quot; fallback-src=&quot;https://github.githubassets.com/images/icons/emoji/unicode/2728.png&quot;&gt;✨&lt;/g-emoji&gt;:&lt;/p&gt;
&lt;ul&gt;
```

The `type="html"` has been stripped, as also pointed out by the validator.

![image](https://github.com/FreshRSS/FreshRSS/assets/202757/eefcca8d-8677-4d53-9563-94db1f7d3598)

**Comment by Alkarex** [comment]
Indeed, as @Frenzie is indicating, FreshRSS seems to do exactly what it should by displaying plain text in absence of `type="html"` attribute.
Closing but feel free to add more information

**Comment by RichyHBM** [comment]
This sounds good, I have let the holster of these feeds know, so hopefully it's a simple fix
