### ISSUE TITLE
[BUG] CSS Selector Retrieves Garbled Text

### ISSUE THREAD

**Issue by LinxHex** [FreshRSS/FreshRSS#5586]
**Describe the bug**
I am currently subscribing to an RSS feed with the following address: https://rsseverything.com/feed/36a9c080-82fd-44ed-83e8-b286df24e249.xml. I’ve been attempting to use a CSS selector in FreshRSS to extract the article content. I used the selector div.news_text, but the content I obtained was incorrect. When I access the article webpage through my browser, it displays correctly. Despite trying various methods, I haven’t been able to resolve the issue. Could you please assist me? Thank you.

**To Reproduce**
error

**Expected behavior**
Get the content of the article normally

**Screenshots**
![IMG_1796](https://github.com/FreshRSS/FreshRSS/assets/92703641/69e56cd0-4086-462c-986b-55cc8d67a8ee)
![IMG_1797](https://github.com/FreshRSS/FreshRSS/assets/92703641/995901f3-f126-4908-80f0-01cf612c96c5)

**Environment information (please complete the following information):**
- Device: iPad Air 5
- OS: iPadOS
- Browser: Safari
- FreshRSS version: 1.21.0
- PHP version: PHP 7.4.33
- Installation type: Docker

**Additional context**

**Comment by math-GH** [comment]
I can confirm that there is an encoding/decoding issue

![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/c3c7779a-885e-4816-8f8f-9f0b8df4d406)
![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/fbec1784-6a98-4b9d-99e0-60bc2ca9cd1f)
![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/7a9a9ae7-02e0-40e2-84d3-00d49d7ea4c8)

**Comment by math-GH** [comment]
@KawausoJyou Do you have other examples, where it works fine and where it does not work?

**Comment by LinxHex** [comment]
> @KawausoJyou Do you have other examples, where it works fine and where it does not work?

https://peterwunder.de/projects/achievements/atom.xml
This one has the same situation. When I use FreshRSS, it will appear garbled codes, and when I use other RSS readers, there will be no garbled codes.

**Comment by math-GH** [comment]
> > @KawausoJyou Do you have other examples, where it works fine and where it does not work?
> 
> https://peterwunder.de/projects/achievements/atom.xml This one has the same situation. When I use FreshRSS, it will appear garbled codes, and when I use other RSS readers, there will be no garbled codes.

Thanks for adding this feed. It is very akward, because this feed has issues already without the CSS selector.

**Comment by math-GH** [comment]
> https://peterwunder.de/projects/achievements/atom.xml This one has the same situation. When I use FreshRSS, it will appear garbled codes, and when I use other RSS readers, there will be no garbled codes.

This feed does not validate: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fpeterwunder.de%2Fprojects%2Fachievements%2Fatom.xml

SimplePie demo has garbled code too: https://simplepie.org/demo/?feed=https%3A%2F%2Fpeterwunder.de%2Fprojects%2Fachievements%2Fatom.xml

@Alkarex : Could you dive into the SimplePie code please?

**Comment by Frenzie** [comment]
I would assume the feed (and SimplePie) to be completely irrelevant? For this purpose it's just a list of links to pages that are then downloaded and processed.

**Comment by Frenzie** [comment]
Unless you're saying that the OP has a problem for CSS selectors and this other feed has a completely unrelated problem related to the feed itself.

**Comment by Frenzie** [comment]
> This feed does not validate: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fpeterwunder.de%2Fprojects%2Fachievements%2Fatom.xml

That feed says content type=CDATA when it means type=html. Not a bug.

**Comment by Alkarex** [comment]
For the upstream CDATA bug, see https://github.com/FreshRSS/FreshRSS/pull/6181 and https://github.com/lkiesow/python-feedgen/pull/123

**Comment by Alkarex** [comment]
I believe we face the same encoding error as the W3C validator https://validator.w3.org/nu/?doc=https%3A%2F%2Fkimetsu.com%2Fanime%2Fnews%2F%3Fid%3D65156

![image](https://github.com/FreshRSS/FreshRSS/assets/1008324/31011106-7e9f-4c7f-9df8-708a3d4b8255)

We might be able to find a workaround, though

**Comment by Alkarex** [comment]
Please try https://github.com/FreshRSS/FreshRSS/pull/6271

**Comment by math-GH** [comment]
> Please try #6271

Looks good now
