### ISSUE TITLE
[BUG] <pre> blocks not visible in dark mode

### ISSUE THREAD

**Issue by alexklapheke** [FreshRSS/FreshRSS#5587]
**Describe the bug**
When using the Origine[-compact] theme with dark mode enabled, `<pre>` blocks have the same font color as their background color.

**Screenshots**
Light mode (left), dark mode (right)
![](https://github.com/FreshRSS/FreshRSS/assets/8935863/df40836e-04b9-40ab-bb72-2835fe209c68)

**Environment information (please complete the following information):**
- Browser: Firefox 116.0.2 (also tested on iOS 15)
- FreshRSS version: 1.21.0
- PHP version: 8.1.21

**Comment by math-GH** [comment]
Could you please support us with an example RSS feed? It would help to fix it.

**Comment by alexklapheke** [comment]
Sure, try this one: https://tangpoetry.substack.com/feed

**Comment by math-GH** [comment]
@alexklapheke : Could you please have a look onto this PR, if possible? #5603

**Comment by alexklapheke** [comment]
@math-GH Looks good, thanks!

**Comment by Alwaysin** [comment]
Same problem on origine-compact, if @math-GH you can take a look :-D

**Comment by math-GH** [comment]
The fix for Origine fixes the Origine compact as well. Please check the edge.

**Comment by Alwaysin** [comment]
@math-GH I'm always on edge. Please check with this feed: https://about.gitlab.com/atom.xml, first article "Remediating vulnerabilities with GitLab's security insights and AI":
![Screenshot_2023-09-03-11-51-48-79_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/FreshRSS/FreshRSS/assets/7189936/5675c971-0530-4f67-bfc4-c25ec822acbb)
![Screenshot_2023-09-03-11-51-51-72_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/FreshRSS/FreshRSS/assets/7189936/621d0fb9-ddd8-4c8c-ab86-549b4c833afa)
```
$ git log
commit da405ceee628dca739a12b234a6094a8ebae9c94 (HEAD -> edge, origin/edge)
[...]
commit 3b4a865ce635543370bae831807e12c0458d7453
Author: maTh <snip>
Date:   Tue Aug 22 00:37:42 2023 +0200

    Fix background color of <pre> in Dark mode (#5603)

```

**Comment by math-GH** [comment]
Cannot confirm. How it looks like for me:
![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/fd31da70-0a18-43b5-af2d-9253e7bada79)

(Please do not publish my email address that is given in the git log)

**Comment by Alwaysin** [comment]
> (Please do not publish my email address that is given in the git log)

Sorry about that, I hadn't thought about it!

As for the issue, I guess it's on my side then, but I don't see what. Anyway, it doesn't really matter!

**Comment by math-GH** [comment]
Maybe it is edge of your fork and not of origin?

Your fork here is 300+ commits behind: https://github.com/Alwaysin/FreshRSS

**Comment by Alwaysin** [comment]
Could have been but nope!

**Comment by math-GH** [comment]
@marienfressinaud Could you please update demo.freshrss.org to the current edge? It would be useful to have a common instance to check this issue

**Comment by marienfressinaud** [comment]
Sorry for the delay, I've just updated demo.freshrss.org!

**Comment by math-GH** [comment]
@Alwaysin could you please try it on demo.freshrss.org? Can you reproduce your finding?

**Comment by Alwaysin** [comment]
I'm having a "Error during context user init!" error message on the website

**Comment by math-GH** [comment]
> I'm having a "Error during context user init!" error message on the website

me too

ping @marienfressinaud

**Comment by marienfressinaud** [comment]
Fixed! There was a bug in the `cli/create-user.php` script, I'll open a PR to fix it.

Edit: reference https://github.com/FreshRSS/FreshRSS/pull/5667

**Comment by Alwaysin** [comment]
Ok so my .git folder was in the parent directory. I don't know why it appeared to still be working (git pulls) but yet I wasn't getting the changes... or at least not all of them??!
Anyway problem solved!
