### ISSUE TITLE
[BUG] Article CSS selector grabbing HTML strings and subsequent JavaScript code inside script tag

### ISSUE THREAD

**Issue by nfriedly** [FreshRSS/FreshRSS#5588]
**Describe the bug**
The HTML parser appears to become confused and includes part of the JavaScript code as if it were part of the article text on a website with a `<script>` tag inline with an article's contents, e.g.

```
<div id="TGN_site_Article_body" class="TGN_site_Article_body">
  <!-- ... -->
  <script type="text/javascript">
    // ...
    $('.InlineImageGalleryText').html("<div class='IIGcountIcon'><i class='galleryicon icon-gallery_2'></i></div><div class='IIGcount'>" + (mainIIG + 1) + "&nbsp;&nbsp;of&nbsp;&nbsp;" + listOfObjects.length + "</div><span class='IIGheadline'>" + capt01 + " <span class='IIGheadline2'>" + capt02 + "</span></span>");
    // ...
  </script>
  <p><!-- article text here -->
```

**To Reproduce**
1. Add the feed https://www.gatesnotes.com/RSS
2. Set 'Article CSS selector on original website' to `#TGN_site_Article_body`
3. Click the "eyeball button" to show a preview of the scraped content
4. Observe that it begins with a bunch of JavaScript code

**Expected behavior**
Everything from `<script>` to `</script>` should be excluded from the scraped content

**Screenshots**

<img width="904" alt="Screenshot 2023-08-14 at 2 53 29 PM" src="https://github.com/FreshRSS/FreshRSS/assets/114976/e5532c01-0de6-4b62-8788-9881a9d2d9b1">
<img width="892" alt="Screenshot 2023-08-14 at 2 53 44 PM" src="https://github.com/FreshRSS/FreshRSS/assets/114976/7ea777a4-6580-4a16-b66d-73924eb39dc1">

**Environment information (please complete the following information):**
- Device: 
  - Client: M1 MacBook Pro
  - Server: cobbled together home file server
- OS: 
  - Client: macOS Ventura 13.5
  - Server: lscr.io/linuxserver/freshrss docker image running atop Unraid 6.9.2 (based on Slackware Linux)
- Browser: Firefox 115.0.3
- FreshRSS version: 1.21.0
- Database version: SQLite, unsure of the version
- PHP version: 8.2.8
- Installation type: docker on unraid, single user

**Additional context**

I was able to work around the problem by setting the selector to `#TGN_site_Article_body>p, #TGN_site_Article_body iframe`, but figured you all would still want to know about the issue.

**Comment by math-GH** [comment]
I can confirm this issue. There is HTML in the JavaScript code that is interpreted first before removing the `<script>` or it does not remove the `<script>` properly.

![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/5bc46e04-b41e-4dbe-a38c-f863148a20c8)
![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/8c60c30a-4bd8-47f9-b845-c4ae30f05978)

@Alkarex Could you please have a look here? I guess it is an issue with/of SimplePie

**Comment by Frenzie** [comment]
SimplePie isn't involved there, but indeed that's probably a security problem to be solved in a similar manner to however SimplePie does it.

**Comment by Alkarex** [comment]
We are already using SimplePie to sanitize this content, including removing script and style sections. But the HTML input is not strictly valid, as it contains unescaped `<` and `>` characters (inside the script section). They should be escaped like `&lt;` and `&gt;`, or better, put the whole script section in ` <![CDATA[ ... ]]>`. While most modern browsers cope with those errors, SimplePie does not contain a full browser with all quirks.

The script content is not evaluated, so there does not seem to be a security problem there. I do not think this is something we can easily fix.
