### ISSUE TITLE
[BUG] .stylelintrc.json: deprecated instuctions

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#5592]
Stylelint version 15.0.0 ([published in February 2023](https://github.com/stylelint/stylelint/releases/tag/15.0.0)) marked some instructions as deprecated: https://stylelint.io/migration-guide/to-15

```
Deprecation warnings:
 - The "at-rule-name-space-after" rule is deprecated.
 - The "block-closing-brace-newline-after" rule is deprecated.
 - The "block-closing-brace-newline-before" rule is deprecated.
 - The "block-opening-brace-newline-after" rule is deprecated.
 - The "block-opening-brace-space-before" rule is deprecated.
 - The "color-hex-case" rule is deprecated.
 - The "declaration-colon-space-after" rule is deprecated.
 - The "declaration-colon-space-before" rule is deprecated.
 - The "no-eol-whitespace" rule is deprecated.
 - The "indentation" rule is deprecated.
```

Who wants to introduce Prettier?

**Comment by Alkarex** [comment]
The problem with Prettier is that last time I checked, it was not possible to chose the rules, and I do not like several of their choices

**Comment by Frenzie** [comment]
Agreed, big thumbs down on Prettier.

**Comment by marienfressinaud** [comment]
There is a Stylelint plugin that bring back stylistic rules: https://github.com/elirasza/stylelint-stylistic
