### ISSUE TITLE
[Feature]  Firefox Extension that auto detects RSS Links for Subscribing

### ISSUE THREAD

**Issue by monksy** [FreshRSS/FreshRSS#5596]
**Is your feature request related to a problem? Please describe.**

I'm frustrated when it comes to adding an RSS feed from a web page to my instance. The problem is that the RSS link isn't always visible, or sometimes it's hidden in the page it's self's links. I want a plugin that would change colors when an RSS feed is available in the website, and when pressed it would show you the RSS feeds linked to on the page + allow for you to click to add it to your configured instance. 

**Describe the solution you’d like**

I would like for an extension that monitors pages in Firefox for links to RSS feeds, and presents the user with an option if it's present and to automatically add it to your instance. This would save me time from searching or the RSS url or links.

**Describe alternatives you’ve considered**

I've looked at the firefox extensions that are currently in the firefox extension gallery. They only off the ability to monitor your instance. Not to automate the addition of feeds.

**Comment by Frenzie** [comment]
I'm not entirely sure if I understand. Is there something about https://addons.mozilla.org/en-US/firefox/addon/feed-indicator/ and similar you're not happy with?

**Comment by Alkarex** [comment]
I personally use https://addons.mozilla.org/firefox/addon/want-my-rss/ and I am happy with it.
https://github.com/Reeywhaar/want-my-rss
