### ISSUE TITLE
[Feature] Automatic assignment of labels during feed refresh

### ISSUE THREAD

**Issue by sesom42** [FreshRSS/FreshRSS#5599]
**Is your feature request related to a problem? Please describe.**
Often people want to be informed quickly about a certain topic. Until now, you always had to use the search, possibly with saved searches.

**Describe the solution you’d like**
It would be much more comfortable if there was a way to automatically assign labels during feed refresh. Possibly with the same syntax that the search already offers now.

**Describe alternatives you’ve considered**
An alternative would be to display the saved searches in the menu on the left. However, I think it could be resource-intensive to run all searches again and again to display e.g. the number of found items in the menu.

**Comment by Alkarex** [comment]
> Automatic tagging is high on my own todo-list, so it will come
https://github.com/FreshRSS/FreshRSS/discussions/3857#discussioncomment-6760242

We might already have some other issues open on the topic. Making a search and listing there here would help.

**Comment by Alkarex** [comment]
Ah yes, we have a tag: https://github.com/FreshRSS/FreshRSS/labels/FR%3A%20Auto%20Tagging
I would personally prefer to have one main issue

**Comment by sesom42** [comment]
Thank you. I have not found that.

Duplicate of #2380

**Comment by Alkarex** [comment]
Ready for testing https://github.com/FreshRSS/FreshRSS/pull/5954
