### ISSUE TITLE
Disable YouTube video description on normal and reading view [Feature]

### ISSUE THREAD

**Issue by cocowash** [FreshRSS/FreshRSS#5607]
**Is your feature request related to a problem? Please describe.**
I would love to filter YouTube description in reading and normal view. [It would be cleaner to scroll down, only viewing the title and the image]

**Describe the solution you’d like**
It would be great to have an option for any YouTube channel, like a checkbox or something that could be handled from the category to disable the description in any feed that it's on that category. 

**Describe alternatives you’ve considered**
I tried doing it individually with the option CSS selector of the elements to remove, but I could not get a positive result.
Another option would be to do it by each feed individually. In this case, could anyone guide me a way to hide the description by filtering the CSS selector? I read the similar threads here, but I couldn't find any specific information to do this. 

Thanks.

**Comment by math-GH** [comment]
For individual feeds, it would be better to develop an extension for this use case.

**Comment by math-GH** [comment]
This CSS could help you to use it in CustomCSS. Please replace `1991` with your feed ID
```
div.flux[data-feed="1991"] figcaption.enclosure-description {
display: none;
}
```

**Comment by cocowash** [comment]
@math-GH, sorry to bother you, but how do I find the feed ID of any of my feeds? On the documentation center, it explains that I can filter by the feed ID, but doesn't explain how to get it. Thanks for your response btw

**Comment by Frenzie** [comment]
If you click on a feed the URL will end in something like `?a=normal&get=f_189`. That's the number. Where in the documentation does it say this btw?

**Comment by cocowash** [comment]
It appears in [https://freshrss.github.io/FreshRSS/en/users/10_filter.html](https://freshrss.github.io/FreshRSS/en/users/10_filter.html) on the search field section. 
Let's take for example this random ID from a YouTube channel: https://www.youtube.com/feeds/videos.xml?channel_id=UCOfS7qqO7eFQrN0BwBBQrSA
If I try to use the filter with  "UCOfS7qqO7eFQrN0BwBBQrSA" nothing is shown.

**Comment by math-GH** [comment]
The feedID is a number and given by FreshRSS.

Open a single feed in the normal list view (1) and then see the URL (2). The number behind the `f_` ist the feed ID (`f` = "feed"). In this example it is feedID= 1

![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/148d71ae-591d-4a9e-a5a8-9bcd76b34352)
