### ISSUE TITLE
[BUG] importJson() leaves $is_starred=null in most cases and crashes then.

### ISSUE THREAD

**Issue by robertdahlem** [FreshRSS/FreshRSS#5613]
**Describe the bug**
I am writing my own exporter for TT-RSS to migrate all articles from TT-RSS to FreshRSS. Yes, I will open source it. :-)
Naturally this data runs through `importJson()` in `importExportController.php`.

It looks like this function typically never sets `$is_starred=false`, which leads to
`Argument 9 passed to FreshRSS_Entry::__construct() must be of the type bool, null given, called in /var/www/fresh/app/Controllers/importExportController.php on line 450`
The line is a bit off because I added several debugging lines. What's meant is the call to `FreshRSS_Entry()`, where `$is_starred` is the 9th argument.

When `importJson()` is called with `$starred=false`, then there is literally no path where `$is_starred` can get `false`. When it is called with `$starred=true` then a label starting with `"user/-/label/"` must be provided for `$is_starred` to get `false` (which doesn't make any sense at all).

To sum up: it means you can't import not-starred articles without trickery.

**To Reproduce**
1. Provide a file 00000000.json:
```
{
  "items": [
    {
      "categories": [
        "user/-/state/com.google/read"
      ],
      "guid": "http://www.whatever.net/?p=12345",
      "origin": {
        "title": "Whatever News",
        "feedUrl": "http://www.whatever.net/feed/"
      },
      "author": "bornheim",
      "url": "http://www.whatever.net/2023/08/25/interesting-arcticle/",
      "title": "You will never believe what happens next",
      "content": "<p>Interesting stuff</p>",
      "published": "2023-08-25 12:36:00"
    }
  ]
}
```
2. Import this file
3. Exception thrown as described above.
4. Rename file to 00000000_starred.json to run `importJson()` with `$starred=true`
5. Exception thrown as described above.

**Expected behavior**
Article gets imported as unstarred.

**Remedy**
Leave the file name with `starred`, but insert a random category starting with `"user/-/label/"` into the file. Example:
```
{
  "items": [
    {
      "categories": [
        "user/-/label/bornheim/starred_or_not",
        "user/-/state/com.google/read"
      ],
...
```

**Environment information (please complete the following information):**
- Device: random virtual host
- OS: Debian 11
- Browser: Chrome 116.0.5845.111 on Windows
- FreshRSS version: 1.21.0
- Database version: MariaDB 10.5
- PHP version: 7.4.33
- Installation type: manual install

**Additional context**
I started writing my own TT-RSS exporter because I did not find any path to migrate articles from TT-RSS to FreshRSS. This works nicely already and I would be happy to open source it on GitHub or donate it to this project - whatever fits best. It just needs some finishing touches.

**Comment by Alkarex** [comment]
Hello,
See also this work-in-progress https://github.com/FreshRSS/FreshRSS/pull/5584

**Comment by Alkarex** [comment]
In `importJson()`, articles are not stared by default (except if passing `$starred = true`, in which case they are all stared), and they get stared only if they have the right label:

https://github.com/FreshRSS/FreshRSS/blob/dd91fe164d474a87106acb3dc3c8fd7339361b20/app/Controllers/importExportController.php#L400-L401

Furthermore, argument 9 of `FreshRSS_Entry::__construct()` is of type ` bool|int|null`:
https://github.com/FreshRSS/FreshRSS/blob/dd91fe164d474a87106acb3dc3c8fd7339361b20/app/Models/Entry.php#L43-L50

I do not see any bug there. But it might be easier to see if you share a branch / PR.

**Comment by Alkarex** [comment]
P.S.: If you have an example of JSON file that produces a crash with the current edge branch, please share.

**Comment by robertdahlem** [comment]
> P.S.: If you have an example of JSON file that produces a crash with the current edge branch, please share.

I did try edge and it did not crash anymore. I think this is because `__construct()` no longer declares a type for `$is_favorite`, so `null` is tolerated.

To sum it up: FreshRSS until 1.21 needs a file with "`starred`" in the name and a bogus label. Current edge needs a file **without** "`starred`" in the name. In both cases the articles are imported with the correct "starred" status.
