### ISSUE TITLE
[BUG] PHP Fatal error: Uncaught TypeError sanitizeHTML(): Argument #1 ($data)

### ISSUE THREAD

**Issue by squromiv** [FreshRSS/FreshRSS#5622]
**Describe the bug**
Exported feeds with cli/export-zip-for-user.php
Try to import with cli/import-for-user.php to another user

Result in console

> `\cli\import-for-user.php" --user User --filename "file.zip"
>     FreshRSS importing ZIP/OPML/JSON for user “User”…
> 
>     Fatal error: Uncaught TypeError: sanitizeHTML(): Argument https://github.com/FreshRSS/FreshRSS/issues/1 ($data) must be of type string, array given, called in W:\domains\loca
>     lhost\fresh\f1\app\Controllers\importExportController.php on line 442 and defined in W:\domains\localhost\fresh\f1\lib\lib_rss.php:
>     334
>     Stack trace:
>     #0 W:\domains\localhost\fresh\f1\app\Controllers\importExportController.php(442): sanitizeHTML()
>     https://github.com/FreshRSS/FreshRSS/issues/1 W:\domains\localhost\fresh\f1\app\Controllers\importExportController.php(139): FreshRSS_importExport_Controller->importJson()
>     https://github.com/FreshRSS/FreshRSS/issues/2 W:\domains\localhost\fresh\f1\cli\import-for-user.php(31): FreshRSS_importExport_Controller->importFile()
>     https://github.com/FreshRSS/FreshRSS/issues/3 {main}
>     thrown in W:\domains\localhost\fresh\f1\lib\lib_rss.php on line 334`

FreshRSS edge dev vesrion
PHP 8.0

**Comment by Alkarex** [comment]
Could you please test this patch? https://github.com/FreshRSS/FreshRSS/pull/5626

**Comment by squromiv** [comment]
> Could you please test this patch?

Process of import is going without errors now. But there are thousands of labels which I did not create before.

![screen_2023 09 01 002](https://github.com/FreshRSS/FreshRSS/assets/15985877/c278783d-d232-4495-962e-ac9c9df16fce)

**Comment by Alkarex** [comment]
@squromiv I have found and fixed some errors both in export and import https://github.com/FreshRSS/FreshRSS/pull/5626
If you have the possibility to export again, try that.

**Comment by squromiv** [comment]
> try that

Have tried. Everything is OK now. Thanks a lot.
