### ISSUE TITLE
[BUG] Mark as read... does not work with the "+" character in the search text

### ISSUE THREAD

**Issue by sesom42** [FreshRSS/FreshRSS#5632]
**Describe the bug**
I read a feed where I want to automatically set the articles with `(g+)` in the title to read. In search `intitle:'\(g+\)'` works, in "Mark as read..." in the feed settings does not.

**To Reproduce**
1. Add a new feed with this URL: https://rss.golem.de/rss.php?feed=ATOM1.0
2. Add `intitle:'\(g+\)'` to "Mark as read..." at the feed you just added.
3. After fetching the feed, articles with `(g+)` in the title are still displayed as unread.

**Expected behavior**
Articles with (g+) in the title should automatically be marked as read.

**Environment information (please complete the following information):**
- OS: Debian 11.7
- FreshRSS version: 1.21.1-dev
- Database version: MariaDB 10.5.19
- PHP version: PHP 7.4.33

**Comment by Alkarex** [comment]
Thanks for the bug report. Actually, the bug was due to parentheses, not the plus sign.
Would you be able to try this patch? https://github.com/FreshRSS/FreshRSS/pull/5633

**Comment by sesom42** [comment]
Works for me. Thank you!
