### ISSUE TITLE
Configuration example for MySQL Unix socket needed

### ISSUE THREAD

**Issue by Offerel** [FreshRSS/FreshRSS#5634]
**Describe the bug**
I try to switch to MySQL from SQLite and have therefore installed FreshRSS with SQLite. Now i will switch the DB backend to MySQL and reconfigure the db connection. But i fail...

**To Reproduce**
1. open config.php
2. search for db configuration
3. Exchange:
```
'db' => 
  array (
    'type' => 'sqlite',
    'host' => '',
    'user' => '',
    'password' => '',
    'base' => '',
    'prefix' => '',
    'connection_uri_params' => '',
    'pdo_options' => 
    array (
    ),
  ),
```
with 
```
'db' => 
  array (
    'type' => 'mysql',
    'host' => '/run/mysqld/mysqld.sock',
    'user' => 'freshrss',
    'password' => 'mysupersecretpassword',
    'base' => 'freshrss',
    'prefix' => '',
    'connection_uri_params' => '',
    'pdo_options' => 
    array (
    ),
  ),
```

`[Tue, 05 Sep 2023 14:26:58 +0200] [error] --- Access to database is denied for `freshrss`: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for /run/mysqld/mysqld.sock failed: Name or service not known`

**Expected behavior**
Please give me some example how to change the config file to work with a mysql db available via unix socket.

**Environment information (please complete the following information):**
- Device: Rasperry Pi
- OS: Debian 12
- Browser: Chromium, Firefox
- FreshRSS version: 1.21.0
- Database version: Mysql 5.7
- PHP version: PHP 8.2
- Installation type: GIT clone

**Comment by Alkarex** [comment]
Please try with the edge version of FreshRSS.
Cf. https://github.com/FreshRSS/FreshRSS/pull/5166

**Comment by Offerel** [comment]
Many thx. I have made manually the changes in ModelPdo.php and they worked as expected. Many thx. This will help until the next release.
