### ISSUE TITLE
[BUG] Fail to add a specific xml feed (from Oxford Academic)

### ISSUE THREAD

**Issue by Gullumluvl** [FreshRSS/FreshRSS#5635]
Sorry if this is overspecific: I cannot add this feed: https://academic.oup.com/rss/site_5325/3191.xml.

The website home is: https://academic.oup.com/mbe

The log says:

> A feed could not be found at `https://academic.oup.com/rss/site_5325/3191.xml`; the status code is `200` and content-type is `text/html` [https://academic.oup.com/rss/site_5325/3191.xml]

If also fails when appending `#force_feed`, but then the log says `This does not appear to be a valid RSS or Atom feed`.

The validator says it is valid, but gives warnings:
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Facademic.oup.com%2Frss%2Fsite_5325%2F3191.xml

Maybe this warning in particular is relevant: 

> Use of unknown namespace: http://purl.org/rss/1.0/modules/prism/

**Environment information**

- FreshRSS version: 1.21.1-dev

I am not hosting the server myself.

**Comment by Frenzie** [comment]
> Sorry if this is overspecific: I cannot add this feed: https://academic.oup.com/rss/site_5325/3191.xml.

On the contrary! :-) A feed to illustrate the problem is exactly what we like to see.

But it's probably the same as https://github.com/FreshRSS/FreshRSS/issues/5059#issuecomment-1409887498

**Comment by Gullumluvl** [comment]
Indeed, same source of feed!

I tried the user-agent fix, without success.

I am not sure that it is an IP blocking problem, because it obtains the HTML return code 200 (success, right?).

I can ask the host of my FreshRSS server about it.

**Comment by Frenzie** [comment]
I would suspect that despite the status code being 200 it returns some HTML that looks absolutely nothing like the XML you see in the validator.

**Comment by Frenzie** [comment]
As an aside, cURL gives me a 403 with the following content, but HTTPie just returns the feed. Apparently they haven't blocked that user agent yet.

```
<html><body><h1>403 Forbidden</h1>
Request forbidden by administrative rules.
</body></html>
```

**Comment by Alkarex** [comment]
Indeed, this feed seems to return some garbage depending on IP + User-Agent
