### ISSUE TITLE
[BUG]item tags (static string) are not available in HTML + XPath mode

### ISSUE THREAD

**Issue by KevinZhx** [FreshRSS/FreshRSS#5651]
**Describe the bug**
Item tags are not available when using static string in HTML + XPath mode.

**To Reproduce**
1. Go to 'Add a feed'
2. Type of feed source option select 'HTML + XPath'
3. Fill in the item tags column with 'tag demo'
4. See error: Article tags does not add the custom tag 'tag demo'

**Expected behavior**
In HTML + XPath mode, item tags should support static string like other items (such as item author)

**Environment information (please complete the following information):**
- Device: PC
- OS: windows 11
- Browser: edge 116
- FreshRSS version: 1.21.0
- Database version: MySQL 5.7.40
- PHP version: PHP 7.4
- Installation type: web

**Comment by Alkarex** [comment]
Thanks for the bug report. Would you be able to test this patch? https://github.com/FreshRSS/FreshRSS/pull/5653

**Comment by KevinZhx** [comment]
Thanks for the fix, sorry for not replying in time.

**Comment by Alkarex** [comment]
No worries @KevinZhx . Does it work for you then?
