### ISSUE TITLE
[Feature] Dark theme for login page (auto switch to light with system)

### ISSUE THREAD

**Issue by update-freak** [FreshRSS/FreshRSS#5659]
**Is your feature request related to a problem? Please describe.**
When I use FreshRSS in the night it would be good to have also a dark login site (site which appears when going to the FreshRSS-instance before I'm logged in) instead of the white login site.

**Describe the solution you’d like**
Best would be the possibility to select an theme that automatically switch between light/dark with the system settings.

**Comment by Alkarex** [comment]
Related https://github.com/FreshRSS/FreshRSS/pull/5582

**Comment by math-GH** [comment]
The root of this issue is:

`FreshRSS_Context::$user_conf->darkMode` is on the login page (`app/layout/layout.phtml`) always `no` and does not respect the config of the anonym. user

**Comment by Alkarex** [comment]
Relates to:
* https://github.com/FreshRSS/FreshRSS/issues/3057
* https://github.com/FreshRSS/FreshRSS/pull/4621

We need to agree on the desired behaviour: show the default theme and settings, or use the settings of the default user.

But a solution to the current issue could simply be:
* https://github.com/FreshRSS/FreshRSS/pull/5582

**Comment by Alkarex** [comment]
For the record, the line responsible for discarding the default user's setting and instead use the default settings is:

https://github.com/FreshRSS/FreshRSS/blob/0beabc333f06c71797a1cbf457455c4ca51efec5/app/Controllers/authController.php#L72

**Comment by math-GH** [comment]
> We need to agree on the desired behaviour: show the default theme and settings, or use the settings of the default user.
> 

IMHO I would prefer to use the theme preferences of the default user. Always in the "guest mode" (= user is not logged in).

With reference to #3706: Do not use the theme of the user, that is not logged in.

**Comment by Frenzie** [comment]
> IMHO I would prefer to use the theme preferences of the default user. Always in the "guest mode" (= user is not logged in).

I agree. That more or less sounds like the point of having one. ;-)

**Comment by update-freak** [comment]
ok, then I think I can close this topic, right?

**Comment by Frenzie** [comment]
I don't think https://github.com/FreshRSS/FreshRSS/pull/5582 resolves this. Or in any case I think the correct behavior is to use the default user's settings. And if the default user is simply the first registered user then that's the problem, if probably one that's really hard to fix.
