### ISSUE TITLE
Enhancement : Add an exclude option in css selector

### ISSUE THREAD

**Issue by prysme01** [FreshRSS/FreshRSS#566]
Hello, 

I'm playing with the CSS selector to retrieve the full article on my feed.
this is working great so far, but I would to know if it could be possible to add a feature to remove a part of the content based on a CSS selector.

Some part of the content retrieved with the selector is not relevant depending on the website, and I would to see an exclude option to specify which content to not retrieve. a kind of substraction option to remove unrelevant content of the selected content.

I hope I'm clear enough.

An example on www.lesnumeriques.com
I select the class="text clearfix" and I don't want to keep the class="mini-product" because it doesn't display well.

thank you for your answer and for your time on making a such great product.
Emmanuel.

**Comment by cwmke** [comment]
I think this should be reopened as a feature request. Adding an additional option to remove some of what's retrieved with CSS selectors would be a great addition.
