### ISSUE TITLE
[BUG] "Feed DAO is not loaded in UserQuery" error when filtering search results by user query

### ISSUE THREAD

**Issue by Totaxe** [FreshRSS/FreshRSS#5668]
**Describe the bug**
If I use the search field to filter results by user query (saved search) that has a feed or a category in it, the browser displays an error "Feed DAO is not loaded in UserQuery".

**To Reproduce**
1. Create a new user query with any expression, and select any feed or category in the Type list (see screenshot below). Note the id of the query, e.g. 1
2. Go to "Main stream" page and type in "S:1" in the search field
3. The browser displays an error "HTTP 500: Application problem (Feed DAO is not loaded in UserQuery)"

**Expected behavior**
The search results should be filtered according to the user query.

**Screenshots**
![freshrss](https://github.com/FreshRSS/FreshRSS/assets/11377001/84168f36-459d-4c8d-b20b-4fe5368567ff)

**Environment information:**
- Device: PC
- OS: Windows 11
- Browser: Microsoft Edge 117
- FreshRSS version: 1.21.0
- Database version: SQLite
- PHP version: PHP 7.4.33
- Installation type: Image from Docker Hub freshrss/freshrss:latest

**Comment by Alkarex** [comment]
Thanks for the bug report 👍🏻 
Would you be able to test https://github.com/FreshRSS/FreshRSS/pull/5669 ?

If you use docker-compose, here is an option:

Edit your docker-compose on the model of https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/freshrss/docker-compose.yml with the following information:

```yml
    build:
      context: https://github.com/Alkarex/FreshRSS.git#fix-search-query
      dockerfile: Docker/Dockerfile-Alpine
```

And then execute a `docker-compose up` just like you normally do.

See also https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md#build-custom-docker-image

**Comment by Totaxe** [comment]
Now everything is ok, there is no error. However, search by user query with a specific feed works a bit strange. All feeds from the Main stream are displayed in the search results, but not this particular feed.

Example:
1. Set "FreshRSS releases" feed visibility to "Show in its category"
![msedge_35LfeystYQ](https://github.com/FreshRSS/FreshRSS/assets/11377001/7c794246-0fe7-4486-905a-4415345c1f9f)
2. Create a user query with this feed and expression "muting"
![msedge_b0xMzOhsn1](https://github.com/FreshRSS/FreshRSS/assets/11377001/f161cdcd-eb0d-407e-901a-816d901dda3e)
3. Go to the main page
4. Type "S:1" to the search field.
No articles found.
Expected behavior: one article from FreshRSS releases feed was found.

Not sure if this is a bug. Then I can close this issue.

**Comment by Alkarex** [comment]
This is another bug, so let's make another issue: https://github.com/FreshRSS/FreshRSS/issues/5674
