### ISSUE TITLE
Chinese fonts are prioritized when displaying Japanese

### ISSUE THREAD

**Issue by superuser7777** [FreshRSS/FreshRSS#5670]
https://github.com/FreshRSS/FreshRSS/blob/86d713478b25816340aebeeacca704f3aeee17af/p/themes/base-theme/base.css#L10C36-L10C36

Please consider changing the CSS as shown below.
This modification improves display readability for Japanese people.

Add
`"Osaka",`

Change before
`font-family: "OpenSans", "Cantarell", "Helvetica", "Arial", "PingFang SC", "Microsoft YaHei", sans-serif;`

After change
`font-family: "OpenSans", "Cantarell", "Helvetica", "Arial", "Osaka", "PingFang SC", "Microsoft YaHei", sans-serif;`

The Chinese fonts such as "PingFang SC" and "Microsoft YaHei" can be displayed like Japanese, but the kanji are greatly broken down, making them difficult for Japanese people to read.

--
Thank you for the great software!
I've migrated all my RSS readers to FreshRSS!

**Comment by Alkarex** [comment]
Would you mind proposing a pull request?
