### ISSUE TITLE
[BUG] Password mismatch on new install

### ISSUE THREAD

**Issue by UltraBlackLinux** [FreshRSS/FreshRSS#5673]
I'm gonna make this short. Exactly the same behavior as #3239 
I tried changing the password and creating a new user via the cli, but I'm facing the same exact problem: "Password mismatch"

**Environment information (please complete the following information):**
- Device: PC
- OS: Arch Linux
- Browser: Firefox Latest
- FreshRSS version: 1.21.1
- Database version: integrated sqlite
- PHP version: ?
- Installation type: Docker

**Comment by Alkarex** [comment]
Hello,
Did you set up FreshRSS through the Web interface or through CLI?

**Comment by UltraBlackLinux** [comment]
I really just installed the docker image and connected to the webinterface. I didn't even know you could do the setup via the cli

**Comment by Alkarex** [comment]
My current hypothesis is that a password manager comes in the way.
Could you try again with (another) blank Web browser without auto-filling the password fields?

**Comment by UltraBlackLinux** [comment]
I'm not auto filling the password fields.

**Comment by Alkarex** [comment]
What Docker image are you using exactly, and could you try with `freshrss/freshrss:edge`?

**Comment by UltraBlackLinux** [comment]
edge also doesn't work.

Edit: I just tried another fresh install with nothing but the `path` changed, and again I'm greeted with a "password mismatch"

I just noticed something peculiar: This exact change breaks the login credentials. As soon as I enable a custom path, the login breaks entirely

Edit: I just found https://github.com/FreshRSS/FreshRSS/pull/2151/files/c845d48879c6c3b761970bee2a42db13357dbc99 but proxy_cookie_path got removed from the readme. Was it fixed? I'm currently using caddy with a simple proxy_pass to freshrss

Edit: I just found out that nextcloud also has an rss reader. I'm switching to that because it works and can integrate with nextcloud's login system. I'm keeping this open for anyone else that is facing this issue.
Feel free to close it though.

**Comment by Andy-Voigt** [comment]
Same problem for me.  Using Caddy:

```
  route /freshrss/* {
     uri strip_prefix /freshrss
     reverse_proxy http://freshrss
  }
```

and changes the base_url in the config.php to https:///....../freshrss . The login is broken.

**Comment by Alkarex** [comment]
@Andy-Voigt Please provide the usual information: install type, version, type of login (Web form?), etc. Have you tried whether the login works with a direct connection without passing by your proxy? Anything in your logs (Web server logs, FreshRSS logs...)

**Comment by Andy-Voigt** [comment]
Installation Type: Docker
Version: Edge
Type of login: from (with none it also works with the proxy in the middle)
Direct Connection: Works

Screenshot from login:


![Screenshot_20231204_091434](https://github.com/FreshRSS/FreshRSS/assets/2019823/dac87045-f87f-45a2-bdd6-9fdf68bb50c3)


Maybe the path inside the cookie is wrong?


`set-cookie | FreshRSS=97hbln1oabkiramm6d9k8p15pm; path=/i/; secure; HttpOnly; SameSite=Lax`

**Comment by Alkarex** [comment]
@Andy-Voigt I can see in your logs that you have an empty `nonce`, which is a sign of wrong proxy setup (wrong session).
Related: https://github.com/FreshRSS/FreshRSS/issues/2731#issuecomment-568532273

Yes indeed, it could be that your cookie proxying is wrong, leading to the session being broken.
This might be due to lack or invalid `X-Forwarded-Prefix` (and `X-Forwarded-Proto`, `X-Forwarded-Host`, `X-Forwarded-Port`, `X-Forwarded-For`) headers

**Comment by Andy-Voigt** [comment]
This works for me right now:

```
  route /rss/* {
     uri strip_prefix /rss
     reverse_proxy http://freshrss {
         header_up X-Forwarded-Prefix /rss
         header_up X-Script-Name /rss
     }
  }
```
plus edit data/config base_url to http://my.domain/rss

I think the bug can be closed.

**Comment by Alkarex** [comment]
@Andy-Voigt Sounds good. Could you consider making adding this configuration example to our documentation readme https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md#alternative-reverse-proxy-configurations (just below the nginx section)?
