### ISSUE TITLE
add FreshRSS to the list of firefox readers (simple)

### ISSUE THREAD

**Issue by ckiw** [FreshRSS/FreshRSS#568]
https://developer.mozilla.org/en-US/docs/Adding_feed_readers_to_Firefox

simply execute this function (with the modified path)

navigator.registerContentHandler("application/vnd.mozilla.maybe.feed",
                                 "https://www.example.com/path/p/i/?c=feed&a=add&url_rss=%s",
                                 "FreshRSS");

I tested it (copy-paste in the scratchpad) and it worked well.

Alexis

**Comment by ghost** [comment]
Actually you can unregister a feed application in Firefox. Just go to options > applications > search for 'feed' > click on the pull down menu > application details.
