### ISSUE TITLE
Why million of unread articles took so long to load

### ISSUE THREAD

**Issue by wankio** [FreshRSS/FreshRSS#5696]
Today i just bring the whole FreshRSS folder in XAMPP windows to **Orange pi pc**/armbian/64GB sandisk 100MB/s.
At first, need to tweak some permissions

```
sudo chown www-data:www-data /var/www/freshrss/FreshRSS-1.21.0/data/users/username
sudo chown www-data:www-data /var/www/freshrss/FreshRSS-1.21.0/data/users/username/db.sqlite
sudo chmod 755 /var/www/freshrss/FreshRSS-1.21.0/data/users/test_username
sudo chmod 644 /var/www/freshrss/FreshRSS-1.21.0/data/users/test_username/db.sqlite
sudo systemctl restart apache2
```

But i don't realized 1,1-1,3 millions of unread article will make main page have 5-10mins loading, even timeout when i trying to mark all as read,etc...  
so i need to go back to localhost xampp, mark all as read and then import database again, now it work much faster than before

**Comment by Alkarex** [comment]
Could you please try with our current edge version of FreshRSS?

**Comment by wankio** [comment]
If i'm remember i already tried that edge version before, even not sudo chown/chmod db.sqlite yet, it still took 4-5 mins for main page loaded, and when scroll down to load more content, it just not load more content instantly, everything in main page is incredibly slow, setting page is much faster, but some option still slow.

" 192.168.1.17 -> 192.168.1.17/p -> 192.168.1.17/p/i -> login page " <fast 
but once i'm logged with old db.sqlite have million of unread articles 
" 192.168.1.17 -> 192.168.1.17/p -> 192.168.1.17/p/i -> main page" - very slow, but very fast with new user/new database

the one i downloaded that time : https://github.com/FreshRSS/FreshRSS/archive/master.zip

i think we should have new php function in .\cli which will "mark all as read" so if someone have millions of unread, they may try that.

Once there's no unread articles, my /var/www/freshrss/FreshRSS-1.21.0 is so fast, it's even much faster than http://localhost/FreshRSS-1.21.0/p/i/ on windows with 1-1.3mil unread articles, db.sqlite in SSD or HDD
