### ISSUE TITLE
[BUG] Max number of articles to keep unread not being respected for small numbers

### ISSUE THREAD

**Issue by GwyndolynMarchant** [FreshRSS/FreshRSS#5702]
**Describe the bug**
The filter action "Max number of articles to keep unread" does not work on feeds when set to the number "10"

**To Reproduce**
1. Set the "Max number of articles to keep unread" filter on a feed to "10"
2. Wait long enough for the feed to update (feed-dependent)
3. More than 10 articles will appear unread.

**Expected behavior**
The feed should cap at 10 unread articles.

**Screenshots**
![image](https://github.com/FreshRSS/FreshRSS/assets/59987656/b9ab6505-68ad-4ace-87fa-d434f7da6151)
![image](https://github.com/FreshRSS/FreshRSS/assets/59987656/14150bb7-7d8a-4b62-b361-7e614dde584a)
![image](https://github.com/FreshRSS/FreshRSS/assets/59987656/1a2e21ab-130c-4ebe-88e6-572c86be48a4)

**Environment information:**
- Device: Shared Web Host
- OS: Linux (Distribution information unavailable)
- Browser: Firefox 118.0.1 (Although problem is present regardless of client)
- FreshRSS version: 1.21.0
- Database version: MySQL 10.3.39-MariaDB-log-cll-lve
- PHP version: PHP 8.2.10
- Installation type: Softaculous

**Additional context**
Problem is present on feeds from any source

**Comment by Alkarex** [comment]
Sorry for the delay.
At the moment, that option is applied to existing articles *before* the insertion of new articles. Could that maybe explain what you are observing?

**Comment by Alkarex** [comment]
Refactoring coming

**Comment by GwyndolynMarchant** [comment]
That could possibly be the problem! It would certainly explain the odd behaviour, as it does seem to stay _near_ the requested value, usually floating around 20-30. Thanks for the response, looking forward to seeing the refactor 😃

**Comment by Alkarex** [comment]
Please test the `edge` version of FreshRSS. Feedback welcome
