### ISSUE TITLE
Re-design de la sélection des thèmes

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/FreshRSS#571]
Bonsoir,

En marge de la proposition d'Alkarex sur #557 (qui serait plutôt un site externe présentant les thèmes, de ce que j'ai compris), il serait intéressant d'avoir un visuel lors du choix d'un thème.
Je joins un montage réalisé très rapidement (les noms des thèmes sont les mêmes, les captures sont moches, etc, mais c'est pour montrer l'idée).

![2014-08-08 23_11_14-affichage freshrss](https://cloud.githubusercontent.com/assets/7189936/3862980/2d138f66-1f42-11e4-94ae-e8eed55ffad6.png)

Et là on voit par exemple que j'aurais sélectionné le premier thème ^^
Qu'en pensez-vous ?

**Comment by marienfressinaud** [comment]
Je ferme ce ticket pour le moment. S'il y a besoin d'améliorations on ouvrira un autre ticket ;)
