### ISSUE TITLE
Administrator Documentation 404

### ISSUE THREAD

**Issue by roughnecks** [FreshRSS/FreshRSS#5721]
hello,

all of the admin docu gives 404.

**Comment by XtremeOwnageDotCom** [comment]
Can confirm.

![image](https://github.com/FreshRSS/FreshRSS/assets/5262735/9c80e881-b4a6-42ea-a986-fb9e00a395fd)

**Comment by XtremeOwnageDotCom** [comment]
Will note, if you are looking for the OIDC documentation: https://github.com/FreshRSS/FreshRSS/blob/1.22.0/docs/en/admins/09_AccessControl.md

**Comment by Alkarex** [comment]
Thanks for the heads-up. Should be fixed by https://github.com/FreshRSS/FreshRSS/commit/58cf2f058f7dc355b2aac6382aa8d2808cf294a0 (was due to bug in https://github.com/FreshRSS/FreshRSS/pull/5681)

https://freshrss.github.io/FreshRSS/en/admins/16_OpenID-Connect.html is up again
