### ISSUE TITLE
Mark article as read after focus using hotkeys n/p

### ISSUE THREAD

**Issue by passbe** [FreshRSS/FreshRSS#5723]
Hi team, great work on the project. There is one item preventing me from switching to FreshRSS from Feedly and wondering how hard it would be to implement.

When using the focus next (n) / previous (p) shortcuts, would it be possible to mark the article as read (without opening the article).

I usually wake up with 1000's of unread items and base what I read on the title. I've looked into creating an extension for this functionality but don't believe the hooks are available to achieve it. Would appreciate anyone's feedback on this.

**Comment by math-GH** [comment]
Have you tried this settings here?

![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/bd296d89-d822-401e-8e70-5763fa22bc74)

**Comment by passbe** [comment]
If you are referring to the "Mark an article as read.... while scrolling" I have. Unfortunately not the same functionality.
