### ISSUE TITLE
[BUG] Reset after upgrade Docker Version

### ISSUE THREAD

**Issue by Limoniak** [FreshRSS/FreshRSS#5725]
**Describe the bug**
Reset after upgrade Docker Version

After an update last night Freshrss is now on the setup page.
I checked the rights and restarted the container.
I see files from the old config like the user file in /data/users but no link is made with

**Environment information**
- OS: [Debian 12]
- FreshRSS version: [1.22.0 ]
- Installation type: [Docker]

**Comment by math-GH** [comment]
Please support you Docker FreshRSS version/repository

**Comment by Limoniak** [comment]
freshrss/freshrss:latest

**Comment by Alkarex** [comment]
Hello,
How did you perform the update?
Are you using docker-compose, or a manual Docker command?
In any case, please share the relevant part of your configuration.
The most likely is that you have started a new instance mapping to another location

**Comment by Limoniak** [comment]
Hello, 
Update with watchtower auto
Docker-compose 
`version: '3.3'`
`services:`
    `freshrss:`
        `restart: unless-stopped`
        `logging:`
            `options:`
                `max-size: 10m`
        `ports:`
           ` - '***:80'`
        `environment:`
           ` - TZ=Europe/Paris`
           ` - 'CRON_MIN=1,31'`
        `volumes:`
            `- /home/****/docker/freshrss/data:/var/www/FreshRSS/data'`
           ` - /home/****/docker/freshrss/extensions:/var/www/FreshRSS/extensions'`
        `container_name: freshrss`
        `image: freshrss/freshrss`

**Comment by Alkarex** [comment]
It looks like you have a single quote at the end of your volumes lines, which is wrong

**Comment by Limoniak** [comment]
Thank you, I hadn't paid attention, it's been more than a year since the container has been running without problems
