### ISSUE TITLE
Can the function of adding tags be enhanced? 

### ISSUE THREAD

**Issue by mapleshadow** [FreshRSS/FreshRSS#5728]
When refreshing the source, if a predefined word is found in the title or content, then automatically assign a specific tag attribute to this piece of news. This would greatly facilitate management and categorization when dealing with a large number of news articles.

**Comment by Alkarex** [comment]
Not yet, but will come soon :-) See https://github.com/FreshRSS/FreshRSS/issues/2380

@math-GH I would prefer to point to a single issue, in this case https://github.com/FreshRSS/FreshRSS/issues/2380, instead of labels

**Comment by Alkarex** [comment]
Ready for testing https://github.com/FreshRSS/FreshRSS/pull/5954
