### ISSUE TITLE
[BUG] Language kept englisch when changing to german

### ISSUE THREAD

**Issue by update-freak** [FreshRSS/FreshRSS#5734]
**Describe the bug**
I recognized that with the new version 1.22 the layout is now in englisch instead of german (like before the update).
Also the language setting is correct (=german) as you can see in the picture.
![2023-10-24 18_59_47-Display · FreshRSS](https://github.com/FreshRSS/FreshRSS/assets/40196995/8ed69b0b-d109-4f00-bc35-f0c2d5aa50e3)
I use this release https://github.com/linuxserver/docker-freshrss/releases/tag/1.22.0-ls199 in Docker on Synology NAS.

**To Reproduce**
1.  Login
2. See that the language is englisch and not german (as the language setting)

**Expected behavior**
Everything is displayed in german language.

**Environment information (please complete the following information):**
- Device: Synology NAS
- OS: DSM 7.2.1
- Browser: Chrome (latest)
- FreshRSS version: 1.22

**Comment by Alkarex** [comment]
Probably same as https://github.com/FreshRSS/FreshRSS/issues/5724

**Comment by roughnecks** [comment]
Hi, it's the same for Italian.

**Comment by Alkarex** [comment]
> Hi, it's the same for Italian.

Yes, it seems to happen when there is an extension enabled, which does not have the desired language. The extension falls back to English, but the bug is that the rest of the interface also falls back to English...

**Comment by roughnecks** [comment]
Disabled Invidious Extension and my language is back

**Comment by Alkarex** [comment]
Patch https://github.com/FreshRSS/FreshRSS/pull/5752
Tests welcome

**Comment by Alkarex** [comment]
Could you try again with `freshrss/freshrss:edge` or `freshrss/freshrss:edge-alpine`?
