### ISSUE TITLE
[BUG] Read articles won't display since 1.22.0 upgrade

### ISSUE THREAD

**Issue by Jucgshu** [FreshRSS/FreshRSS#5735]
**Describe the bug**
Hi guys, kudos on the new release. Since I upgraded to  1.22.0, I cannot display read articles when pressing the little red envelop icon, after I finished reading the articles.

**To Reproduce**
Simply press the display read / unread articles button.

**Expected behavior**
Display the already read articles as expected.

**Environment information (please complete the following information):**
- Device: Mobile & laptop
- OS: Archlinux
- Browser: Firefox 118.0.2
- FreshRSS version:  1.22.0
- Installation type: Docker (freshrss/freshrss)

Thanks !

**Comment by Alkarex** [comment]
Hello,
Could you provide a screenshot illustrating the problem?

**Comment by Jucgshu** [comment]
Sure, there you go (unread button just got pressed).

![Capture d’écran du 2023-10-24 20-08-23](https://github.com/FreshRSS/FreshRSS/assets/3890387/17b32522-bfc8-4a7f-9c89-f914cb2800c9)

**Comment by Frenzie** [comment]
Pinging @math-GH

**Comment by math-GH** [comment]
I am not sure that I understand 100% the reported issue.

I see, that with `Origine ` theme with dark mode (`Automatic dark mode (beta)` = `Auto`), it is not visible if the buttons are activated or not.

Could you please disable the dark mode (`Automatic dark mode (beta)` = `No`) and check your issue again?

**Comment by Jucgshu** [comment]
Yup, same happens with the automatic dark mode disabled.

**Comment by math-GH** [comment]
How is your setting here? 
![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/e77206e6-23cb-44ae-a274-49e6b149346e)

**Comment by Jucgshu** [comment]
Display unread articles.

**Comment by math-GH** [comment]
Are you sure that you have unread articles? The main stream has 0 unread articles (no number is shown)
![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/931f788a-da29-4462-bd20-cd7937296d4a)

**Comment by Jucgshu** [comment]
Oww I missed the title of the issue. It is the *already* read articles I can't display since the upgrade when pressing the red icon. My bad. Will update 1st post.

**Comment by Frenzie** [comment]
Oops, I misread. Sorry for the ping @math-GH ^_^

**Comment by math-GH** [comment]
Then:
See the URL parameters: `state = 0` means default. Your default is: Display unread articles.
If you change it to `state = 1` then only read articles will be displayed

![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/ba801615-266e-4356-9a16-a75af2e26340)

**Comment by Jucgshu** [comment]
Yup, works.

So the default behaviour changed with the upgrade and we have to change the settings to switch between articles state views (or by changing the url manually)?

Why not keep the old behaviour and switch between state views by clicking the envelop icon?

**Comment by math-GH** [comment]
The configs should not be changed while upgrading.

How did you update?
(I am not familar with Docker. Ping @Alkarex @Frenzie for help)

**Comment by Alkarex** [comment]
In your case, you need to click on **the first** envelope, to display the read articles. I do not believe anything has changed since last version

**Comment by Jucgshu** [comment]
I feel a little bit stupid now. Works ok.

Although I'm pretty sure I've never used the left icon before.

Thanks @Alkarex
