### ISSUE TITLE
[BUG] get cURL error since 1.22.0

### ISSUE THREAD

**Issue by isokaze04** [FreshRSS/FreshRSS#5739]
**Describe the bug**
get "cURL error 6: getaddrinfo() thread failed to start ...."  error when fetching rss content or adding a new feed.
1.21.0 works fine.

**To Reproduce**
1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

**Expected behavior**

**Screenshots**

**Environment information (please complete the following information):**
- OS: Ubuntu 16.04.3 LTS
- FreshRSS version: 1.22.0
- Installation type: docker (freshrss/freshrss)

**Additional context**

**Comment by Alkarex** [comment]
Could you try with `freshrss/freshrss:alpine`?
It could be due to Ubuntu 16.04 being too old for hosting our Debian 12 image.

**Comment by isokaze04** [comment]
Thanks @Alkarex it works. This issue can be closed now.

**Comment by Alkarex** [comment]
Could you please try one more time with `freshrss/freshrss:edge` just to confirm the problem?
