### ISSUE TITLE
[BUG] web updater doesn't find latest 1.22.0

### ISSUE THREAD

**Issue by samuelhaeussler** [FreshRSS/FreshRSS#5763]
**Describe the bug**
Expecting to find the latest version in the web update.

**To Reproduce**
1. Go to settings
2. Click on update
3. no error, just doesn't find new version

**Expected behavior**
Find version 1.22.0 to update.

**Environment information (please complete the following information):**
- FreshRSS version: 1.21.0
- Database version: Sqlite
- PHP version: 8.0

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/discussions/5751#discussioncomment-7394960

**Comment by Alkarex** [comment]
@marienfressinaud 1.22.1 looks good https://github.com/FreshRSS/FreshRSS/milestone/59

**Comment by ADMECA** [comment]
Hi, it can't find the version either 1.22.1

**Comment by marienfressinaud** [comment]
You should now be able to update to FreshRSS 1.22.1

**Comment by ADMECA** [comment]
Great, many thanks for your work.
