### ISSUE TITLE
Automated test (Travis + PHPUnit)

### ISSUE THREAD

**Issue by marienfressinaud** [FreshRSS/FreshRSS#577]
I was thinking today it would be awesome to have a strong test suite. I think PHPUnit is a good framework for our tests (at least, the best known). Travis CI could be used as continuous integration platform to test automatically commits and PR. The best would be to check test coverage!

I know it's a lot of works but it can help to not lose too much time to find bugs and regressions. And it's a really good for communication :D

**Comment by aledeg** [comment]
I am trying to test the class FreshRSS_Share and I wonder the reason for a private constructor and static methods. It makes testing hard and I am not sure if we can not split the class in 2.

I think the static methods are related to a Shares class which will own a Share collection. Any thoughts?

**Comment by marienfressinaud** [comment]
Yes probably but I would like to avoid this kind of changes before the release of the 1.0.

**Comment by aledeg** [comment]
I am now trying to test the Category class but it is highly coupled. My guess is that most of the code of FreshRSS is build the same way. If we want to be able to test properly, I think we need to refactor again the code by introducing more dependency injection and making the functions into classes.
I don't say we need to do everything in one big refactoring but I think it will be a good thing if we want to make it testable.

**Comment by marienfressinaud** [comment]
I would like to try to set up travis-ci with FRSS. We'll need a .travis.yml file but I can already try to enable the Travis switch button to see what happens :).

**Comment by aledeg** [comment]
I think in the future, with a nice test suite, we should consider using [humbug](https://github.com/padraic/humbug) for mutation testing.

**Comment by Frenzie** [comment]
Copying this from my inadvertent duplicate:

It looks like FreshRSS isn't making the most of GitHub integration yet. Here are some hopefully helpful suggestions to get started.

* [Scrutinizer](https://scrutinizer-ci.com/tour/eliminate-bugs-before-they-hit-production) (code quality)
* [Codacy](https://en.wikipedia.org/wiki/Codacy) (code quality)
* [CircleCI](https://circleci.com/) (or Travis, for running unit tests and custom coding style/quality tests)
  See [rss-bridge](https://github.com/RSS-Bridge/rss-bridge/blob/8ed4812e00e6f6bb55a3ee6ab374a4642b135a62/.travis.yml#L12-L13) and [Elkarte](https://github.com/elkarte/Elkarte/tree/8cac408e6726a64ee81294a915b3d80962cb829c/tests)

Of course I'm willing to help think about and implement these.

**Comment by Alkarex** [comment]
@Frenzie Help very much welcome :-)

**Comment by Alkarex** [comment]
Travis added by @Frenzie https://github.com/FreshRSS/FreshRSS/pull/1619

**Comment by Frenzie** [comment]
It'll still need to be extended from mere linting to actual unit tests of course. But yes, with some basic setup out of the way it'll be much easier to keep adding things incrementally. ;-)
