### ISSUE TITLE
[BUG] Database access not working for cron script

### ISSUE THREAD

**Issue by yaleman** [FreshRSS/FreshRSS#5770]
**Describe the bug**

Feeds are not updating and this error appears in the logs:

I recently upgraded to 1.22.0 and migrated from sqlite to postgres. Reading and marking existing posts read works, but the cron script is throwing errors about being unable to connect to the database:

```text
FreshRSS[2127]: [yaleman] [Sat, 28 Oct 2023 06:41:11 +1000] [error] --- Access to database is denied for ``: SQLSTATE[08006] [7] could not translate host name ":" to address: Name or service not known
```

And no updates are happening to feeds since the upgrade - until I exec into the container and run the actualize script manually.

**To Reproduce**

Using the following docker container:

```
    Image:           freshrss/freshrss:1.22.0-arm
    Image ID:        docker.io/freshrss/freshrss@sha256:108cfbb097b96f4b893752a257d39a676b122eacef4ba3527b5c769c6b0a1f96
```

Config db section:

```php
  'db' =>
  array (
    'type' => 'pgsql',
    'host' => getenv('FRESHRSS_POSTGRESQL_PORT_5432_TCP_ADDR').":".getenv('FRESHRSS_POSTGRESQL_PORT_5432_TCP_PORT'),
    'user' => getenv("DB_USER"),
    'password' => getenv("DB_PASSWORD"),
    'base' => getenv("DB_BASE"),
    'prefix' => false,
    'connection_uri_params' => '',
    'pdo_options' =>
    array (
    ),
  ),
```

The environment variables are confirmed to be working otherwise no data would appear - but the reader functionality and marking them read works.

**Expected behavior**

Feeds to be updated automatically with the cron timer.

**Screenshots**

n/a

**Environment information (please complete the following information):**
- Device: linux
- OS: docker container
- Browser: n/a
- FreshRSS version: 1.22.0
- Database version: postgresql (docker postgres:15.4)
- PHP version: the one in the container (PHP 8.2.7 (cli) (built: Jun  9 2023 19:37:27) (NTS))
- Installation type: k8s, container

**Additional context**

The error would indicate that it's somehow loading the configuration but not getting the environment variables from the container? They need to come from there because it's running in kubernetes and are dynamically set on startup to point at the DB.

**Comment by yaleman** [comment]
Running it manually in the container works fine:

```shell
root@freshrss-8477cdcbbc-9lwt7:/var/www/FreshRSS# . /var/www/FreshRSS/Docker/env.txt; \
                su www-data -s /bin/sh -c 'php /var/www/FreshRSS/app/actualize_script.php' \
                2>> /proc/1/fd/2 > /tmp/FreshRSS.log
root@freshrss-8477cdcbbc-9lwt7:/var/www/FreshRSS# cat /tmp/FreshRSS.log
Results:
yaleman OK
End.
```

(And there's fresh updates in my feed)

**Comment by Alkarex** [comment]
I have made a patch https://github.com/FreshRSS/FreshRSS/pull/5772
Would you be able to test? I have made a test image `freshrss/freshrss:pr5772`

**Comment by Alkarex** [comment]
Merged. Tests of `freshrss/freshrss:edge` and `freshrss/freshrss:edge-alpine` and `freshrss/freshrss:edge-arm` welcome

**Comment by Alkarex** [comment]
@yaleman Maybe you could also give hints to https://github.com/FreshRSS/FreshRSS/pull/5748
