### ISSUE TITLE
[BUG]Feed from German website does not work

### ISSUE THREAD

**Issue by RonnyB74** [FreshRSS/FreshRSS#5779]
Feed from German website:
[https://www.naturparkmagazin.de/geo-naturpark-frau-holle-land/feed/](https://www.naturparkmagazin.de/geo-naturpark-frau-holle-land/feed/)
does not work.

The following error is displayed:
`Verdammt! Dieser Feed ist auf ein Problem gestoßen. Bitte stellen Sie sicher, dass er immer lesbar ist und aktualisieren Sie ihn dann.`

Under TTRSS, which I used before, this page went down without a problem. Can this problem be fixed?

Thanks, Ronny

**Comment by Frenzie** [comment]
The feed is broken. Perhaps it wasn't a few days ago.
```
bla:56: parser error : StartTag: invalid element name
<1536x1536>https://www.naturparkmagazin.de/geo-naturpark-frau-holle-land/wp-cont
 ^
bla:56: parser error : expected '>'
ds/sites/48/Hessischer-Landschaftspflegetag-2023-c-Konstantin-Mennecke-HNA.png</
                                                                               ^
bla:56: parser error : Opening and ending tag mismatch: thumbs line 51 and unparsable
ds/sites/48/Hessischer-Landschaftspflegetag-2023-c-Konstantin-Mennecke-HNA.png</
                                                                               ^
bla:57: parser error : StartTag: invalid element name
<2048x2048>https://www.naturparkmagazin.de/geo-naturpark-frau-holle-land/wp-cont
 ^
bla:57: parser error : expected '>'
ds/sites/48/Hessischer-Landschaftspflegetag-2023-c-Konstantin-Mennecke-HNA.png</
                                                                               ^
bla:57: parser error : Opening and ending tag mismatch: item line 22 and unparsable
ds/sites/48/Hessischer-Landschaftspflegetag-2023-c-Konstantin-Mennecke-HNA.png</
                                                                               ^
bla:75: parser error : Opening and ending tag mismatch: channel line 10 and thumbs
</thumbs>
         ^
bla:76: parser error : Opening and ending tag mismatch: rss line 1 and item
        </item>
               ^
bla:77: parser error : Extra content at the end of the document
                <item>
                ^

```

**Comment by RonnyB74** [comment]
Then the site has always been broken. I switched to FreshRSS at the end of 2022. This page was the only one that didn't work in FreshRSS from the beginning, but worked perfectly in TTRSS. I had hoped that the problem would solve itself. Other feed readers seem to be more generous when it comes to these errors. The page is also displayed in the RSS view in the Vivaldi browser.

Do you have any idea how I can work around the problem in FreshRSS, or is the only option left to me to report the errors to the site operator?

**Comment by Frenzie** [comment]
In that case Vivaldi's probably using their HTML parser on it. In this case the problem is that XML elements are not allowed to start with a number.

> or is the only option left to me to report the errors to the site operator?

That's better regardless. But you might be able to fix relatively inoffensive errors like these with DOMParser or Tidy in an extension. Though on the flip side they may well think it's perfectly fine.

**Comment by RonnyB74** [comment]
I have informed the operator of the site, and I am waiting for an answer. According to my research, this is about the default image sizes
"default-image-sizes" of WordPress.

The question is whether this is a bug on WordPress, or whether the name of the two image sizes is defined by the user.

**Comment by Frenzie** [comment]
I don't think this is something Wordpress does all by itself, though WordPress 6.1.4 (which is what it says) does happen to be a few versions older than the present 6.3.2.

**Comment by RonnyB74** [comment]
The website operator has adapted the XML identifiers in the RSS feed. Nevertheless, FreshRSS has encountered a problem when loading the feed. Apparently there is another error in the XML?

**Comment by Frenzie** [comment]
It works for me. Is that on the latest version?

As an aside, the W3 Feed Validator was down a few days ago, hence why I didn't link it, but it does still show some minor issues.
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.naturparkmagazin.de%2Fgeo-naturpark-frau-holle-land%2Ffeed%2F

**Comment by RonnyB74** [comment]
I have now set the polling interval back to standard and cancelled the mute function for the feed. Now the feed works for me too. Before, I still got the error message when I reloaded it.
Thanks for the help!
