### ISSUE TITLE
[BUG] OIDC uses HTTP redirect URI instead of HTTPS

### ISSUE THREAD

**Issue by mark-monteiro** [FreshRSS/FreshRSS#5780]
**Describe the bug**
The redirect URI used by FreshRSS is `http` instead of `https`, which makes it impossible to authenticate.

**To Reproduce**
1. Set up a FreshRSS docker install with OIDC configured to domain `freshrss.example.com` and OIDC domain at `auth.example.com` (I am using Authelia)
2. Navigate to site, which redirects to `https://auth.example.com/api/oidc/authorization?response_type=code&scope=openid%20profile%20email&client_id=freshrss&state=xxxx&redirect_uri=http%3A%2F%2Ffreshrss.example.com%2Fi%2Foidc%2F&nonce=xxxx` (note that the redirect_url is `http://freshrss.example.com/i/oidc/`)

**Expected behavior**
OIDC authentication should use HTTPS as the scheme in the redirect URL. I would not make this configurable. Redirecting to an HTTP URL should not be supported at all as it would expose the tokens returned from the authentication provider.

**Screenshots**

**Environment information (please complete the following information):**
- Device: Desktop Web
- OS: Windows
- Browser: Firefox
- FreshRSS version: 1.22.0
- Database version: SqlLite
- PHP version: unsure
- Installation type: Docker 

**Additional context**
Workarounds I tried:

1. Update the redirect URL in the original request to use HTTPS. This does not work of course because the redirect URL does not match the one generated by the server. This results in the following error message in the FreshRSS log file:

```
response contained an "error_description" entry with value: ""The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client. The 'redirect_uri' from this request does not match the one from the authorize request."", referer: https://example.markmonteiro.info/
```

2. Update the authentication provider (Authelia) to support the http redirect url. This does not work because an HTTP redirect URL is (correctly) not supported. This results in the following error message being displayed in the web UI when being redirected back to FreshRSS:

   ```
   The request is missing a required parameter, includes an invalid parameter value, includes a parameter more than once, or is
   otherwise malformed. Redirect URL is using an insecure protocol, http is only allowed for hosts with suffix 'localhost', for example:
   http://myapp.localhost/.
   ```

**Comment by Alkarex** [comment]
Hello,
Do you have a proxy or anything in front? Maybe the detection of the scheme does not work as expected.

It seems to work with HTTPS for @XtremeOwnageDotCom according to https://freshrss.github.io/FreshRSS/en/admins/16_OpenID-Connect-Authentik.html

Maybe a solution https://github.com/OpenIDC/mod_auth_openidc/discussions/1043

**Comment by XtremeOwnageDotCom** [comment]
> Hello, Do you have a proxy or anything in front? Maybe the detection of the scheme does not work as expected.
> 
> It seems to work with HTTPS for @XtremeOwnageDotCom according to https://freshrss.github.io/FreshRSS/en/admins/16_OpenID-Connect-Authentik.html
> 
> Maybe a solution [OpenIDC/mod_auth_openidc#1043](https://github.com/OpenIDC/mod_auth_openidc/discussions/1043)

I actually did run into this issue. I assumed it was something odd on my side, and just added http versions of the redirect URIs on the authentik side.

![image](https://github.com/FreshRSS/FreshRSS/assets/5262735/bb74f29e-3d20-4dc8-b322-800fe49bdc36)

Functionally, everything gets automatically redirected to HTTPs regardless, so, it wasn't a huge issue to work-around on my side. I didn't think twice about it.

@Alkarex  I imagine the issue, is because the pod itself, listens on HTTP, while the HTTPs is terminated by the upstream ingress/load balancer.

**Comment by mark-monteiro** [comment]
> Do you have a proxy or anything in front? Maybe the detection of the scheme does not work as expected.

Yes, I am using [Caddy](https://caddyserver.com/) as my reverse proxy. My understanding is that there should be no scheme detection involved. Only HTTPS should be supported, since using an unencrypted callback URL would expose the security tokens.

> Functionally, everything gets automatically redirected to HTTPs regardless, so, it wasn't a huge issue to work-around on my side. I didn't think twice about it.

In case it wasn't clear, I just want to point out that this is a security issue. If you're redirecting the OAuth callback from HTTP to HTTPS, the authentication tokens in the callback will be exposed unencrypted in the original HTTP request even though it's redirected to HTTPS.

**Comment by Alkarex** [comment]
I am not sure whether it is used by `mod_auth_openidc`, but do you properly forward scheme information, e.g. through `X-Forwarded-Proto` HTTP header?

**Comment by mark-monteiro** [comment]
> I am not sure whether it is used by `mod_auth_openidc`, but do you properly forward scheme information, e.g. through `X-Forwarded-Proto` HTTP header?

Thanks for the tip. I set `OIDC_X_FORWARDED_HEADERS` to `X-Forwarded-Proto` and everything worked as expected. I misread the documentation and didn't realize it was required when running behind a reverse proxy

**Comment by p4block** [comment]
I was fighting this and saw here that I just needed to match the URL in the browser console 400 error with the Provider setting in Authentik. Funnily, I was just missing the trailing `/`
When everything is setup "correctly" behind the reverse proxy the format is just like this:
`https://our.domain:443/i/oidc/`

You only need this one. The Authentik docs could probably have a note about it.
