### ISSUE TITLE
[BUG] Uncaught Typeerror when open the "remove" dropdown menu of labels

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#5784]
**To Reproduce**
Open the "remove" dropdown menu of a label in the feed menu

![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/5917e3e4-24c8-4ddd-85c4-462c0cdfb205)

![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/a9f391ff-2c24-420b-897b-18eb7732dff9)

**Environment information (please complete the following information):**
- Browser: Firefox 119
- FreshRSS version: 1.22.1

**Comment by Frenzie** [comment]
@math-GH That milestone means you're going to work on it?

**Comment by math-GH** [comment]
That assigned milestone means, that we should work on it and deliver it in the next release.

If I would fix it right now, I would open a PR instead of writing a ticket ;) So please feel free to find a fix :)

**Comment by Alkarex** [comment]
Seems related to https://github.com/FreshRSS/FreshRSS/pull/4258

**Comment by Frenzie** [comment]
This would fix it, but I'm not really sure what all that code is about at a glance (i.e., if there's a better way).
```diff
diff --git a/p/scripts/main.js b/p/scripts/main.js
index 93aac281..833bfe35 100644
--- a/p/scripts/main.js
+++ b/p/scripts/main.js
@@ -863,7 +863,7 @@ function init_column_categories() {
                                a.href = '#dropdown-' + id;
                                div.querySelector('.dropdown-target').id = 'dropdown-' + id;
                                div.insertAdjacentHTML('beforeend', template);
-                               if (feed_web.length < 1) {
+                               if (feed_web && feed_web.length < 1) {
                                        div.querySelector('.item.link.website').remove();
                                }
                                const b = div.querySelector('button.confirm');
```

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/5785
