### ISSUE TITLE
[BUG] Freshrss 1.22.1 , 500 internal server errror while starting installation on Apache/2.2.34

### ISSUE THREAD

**Issue by prbt2016** [FreshRSS/FreshRSS#5790]
**Describe the bug**

Hello,

I was in the process of manual installation of Freshrss 1.22.1 on Centos 7 with  PHP 7.4, Apache 2.2.34, MYSQL 5.5. 

However I see a blank page with 500 internal server error for URL http://example.com/freshrss1221/p/i/ under browser's network console .

So to debug further I checked with Apache logs and it shows : 

`/{{PATH}}/{{TO}}/{{FRESHRSS}}/p/.htaccess: Invalid command 'SetEnvIfExpr', perhaps misspelled or defined by a module not included in the server configuration.`

What could be the issue ?. 

Could you please replicate this on your server with Apache 2.2 and fix this? . 

I checked the requirements here in the following URL'S and it's mentioned that script  is compatible with Apache 2  : 

https://freshrss.github.io/FreshRSS/en/admins/02_Prerequisites.html
https://github.com/FreshRSS/FreshRSS#requirements

**To Reproduce**
1. Go to 'http://example.com/freshrss1221/p/i/'
2. See error in browser console

**Expected behavior**
Freshrss installation should have been started.

**Environment information (please complete the following information):**
- OS: [e.g. Ubuntu 20.04] - CentOS Linux release 7.6.1810 (Core)
- Browser: [e.g. Firefox 86] - Firefox 115.4.0esr (64-bit)
- FreshRSS version: [e.g. 1.17.1] - 1.22.1
- Database version: [e.g. Mysql 5.7] - MYSQL 5.5
- PHP version: [e.g. PHP 7.4] - PHP 7.4.25
- Installation type: Shared hosting

**Comment by Alkarex** [comment]
Indeed, Apache 2.2 (which has been end-of-lifed for over 6 years) does not support `setenvifexpr`
https://httpd.apache.org/docs/2.2/mod/mod_setenvif.html#setenvifexpr
It was first introduced in Apache 2.4 for 17 years ago. We should at least update the documentation about minimal Apache version.
CentOS 7 seems to have Apache 2.4 https://distrowatch.com/table.php?distribution=centos

In the meantime, you can manually replace:

https://github.com/FreshRSS/FreshRSS/blob/ad8bae5acadcda0291c3a6ca579303dbd4053f04/p/.htaccess#L39-L48

by:

```apache
# Provide the true IP address of the connection (e.g. last proxy), even when using mod_remoteip
<IfModule mod_rewrite.c>
	RewriteEngine on
	RewriteRule .* - [E=CONN_REMOTE_ADDR:%{CONN_REMOTE_ADDR}]
</IfModule>
```

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/5791

**Comment by Alkarex** [comment]
Section replaced by 

```apache
# Provide the true IP address of the connection (e.g. last proxy), even when using mod_remoteip
<IfModule mod_setenvif.c>
	<IfVersion >= 2.4>
		# If you run an old Apache 2.2-, disable mod_setenvif and enable mod_rewrite, or edit manually
		SetEnvIfExpr "%{CONN_REMOTE_ADDR} =~ /(.*)/" CONN_REMOTE_ADDR=$1
	</IfVersion>
</IfModule>
<IfModule !mod_setenvif.c>
	<IfModule mod_rewrite.c>
		RewriteEngine on
		RewriteRule .* - [E=CONN_REMOTE_ADDR:%{CONN_REMOTE_ADDR}]
	</IfModule>
</IfModule>
```

**Comment by Alkarex** [comment]
@prbt2016 Could you please try again our edge branch? I have just merged additional changes https://github.com/FreshRSS/FreshRSS/pull/5804

**Comment by prbt2016** [comment]
Hello @Alkarex ,

I have checked with the edge branch i.e 1.22.2-dev . It works fine on Apache 2.2 without any issues.

Regards.

**Comment by Alkarex** [comment]
> I have checked with the edge branch i.e 1.22.2-dev . It works fine on Apache 2.2 without any issues.

Thanks for the feedback! It requires `mod_rewrite` to be enabled or/and `mod_setenvif` to be disabled for Apache 2.2 not to crash.

**Comment by prbt2016** [comment]
Hello @Alkarex ,

>Thanks for the feedback! It requires mod_rewrite to be enabled or/and mod_setenvif to be disabled for Apache 2.2 not to crash.

Thanks for letting me know regarding that. Any ETA for 1.23.0 ?. 

Kindly let me know.

Regards.

**Comment by Alkarex** [comment]
No date just yet for 1.23.0, but you can already use our `edge` branch, which is the rolling release.
Make sure to follow our RSS feed https://freshrss.org/feeds/all.atom.xml for updates :-)

**Comment by prbt2016** [comment]
Hello @Alkarex ,

>Make sure to follow our RSS feed https://freshrss.org/feeds/all.atom.xml for updates :-)

Sure thanks .

**Comment by Alkarex** [comment]
Anyone here still running Apache 2.2? Asking for https://github.com/FreshRSS/FreshRSS/pull/7419
