### ISSUE TITLE
[BUG] Minz/Translate.cpp regression: lang_name unset

### ISSUE THREAD

**Issue by aristeu** [FreshRSS/FreshRSS#5797]
**Describe the bug**
[Tue Oct 31 17:00:23.817149 2023] [php7:error] [pid 10994] [client 192.168.72.19:54254] PHP Fatal error:  Uncaught Error: Typed static property Minz_T
ranslate::$lang_name must not be accessed before initialization in /www/freshrss/FreshRSS/lib/Minz/Translate.php:126\nStack trace:\n#0 /www/freshrss/FreshRSS/lib/Minz/Translate.php(117): Minz_Translate::loadLang()\n#1 /www/freshrss/FreshRSS/lib/Minz/Extension.php(206): Minz_Translate::registerPath()
\n#2 /www/freshrss/FreshRSS/extensions/xExtension-Invidious/extension.php(39): Minz_Extension->registerTranslates()\n#3 /www/freshrss/FreshRSS/lib/Minz/ExtensionManager.php(262): InvidiousExtension->init()\n#4 /www/freshrss/FreshRSS/lib/Minz/ExtensionManager.php(235): Minz_ExtensionManager::enable()
\n#5 /www/freshrss/FreshRSS/lib/Minz/ExtensionManager.php(161): Minz_ExtensionManager::register()\n#6 /www/freshrss/FreshRSS/app/FreshRSS.php(44): Minz_ExtensionManager::init()\n#7 /www/freshrss/FreshRSS/p/i/index.php(55): FreshRSS->init()\n#8 {main}\n  thrown in /www/freshrss/FreshRSS/lib/Minz/Tran
slate.php on line 126                                                      

**To Reproduce**
1. Follow edge
2. Try accessing the server
3. See error

Likely introduced by 506fe3f44c280c8b42b9a7735e52360f5d2ee4aa as it removes $lang_name initialization.

**Comment by Alkarex** [comment]
Thanks for the bug report. Fixed in edge
