### ISSUE TITLE
Apache IfVersion bug

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#5803]
I updated from 1.22.1-dev to 1.22.2-dev and got this error that leads to a HTTP500 Internal Server Error: 
`/freshRSS/p/.htaccess: Invalid command '<IfVersion', perhaps misspelled or defined by a module not included in the server configuration`

_Originally posted by @math-GH in https://github.com/FreshRSS/FreshRSS/pull/5791#discussion_r1378713878_

**Comment by vdbhb59** [comment]
Also, is the below issue linked to this? If not, should I raise as a bug?
I updated to 1.22.1 via [ZIP ](https://codeload.github.com/FreshRSS/FreshRSS/zip/1.22.1)file, but my update page still says update available to 1.22.1, your current version 1.22.1

![image](https://github.com/FreshRSS/FreshRSS/assets/60728004/bf92c882-72a3-4015-8828-47e223109306)

**Comment by Alkarex** [comment]
@vdbhb59 Your bug seems more related to https://github.com/FreshRSS/FreshRSS/pull/5802

**Comment by Frenzie** [comment]
No, Apache config stuff is unrelated. I can't confirm on my end.

![image](https://github.com/FreshRSS/FreshRSS/assets/202757/20eb2c3d-1709-45d4-8847-471b9b31364b)

**Comment by vdbhb59** [comment]
> @vdbhb59 Your bug seems more related to #5802

Hope so, cause I checked with every theme, and I still get there is an update available. I even have production and not development as my branch.
I do not have logs as well unfortunately to share.
Anyways, I can see you have added it to a pr for fix. :)

**Comment by Alkarex** [comment]
Fixed in https://github.com/FreshRSS/FreshRSS/pull/5804
