### ISSUE TITLE
Errors in log for WebSub and JSON

### ISSUE THREAD

**Issue by kour1er** [FreshRSS/FreshRSS#5822]
**Describe the bug**
On certain RSS feeds I'm seeing repeating errors in the FreshRSS logs:

> Error while WebSub subscribing to [feed]

> JSON not found for WebSub [feed]

A few example feeds where this is happening to me: 
1. https://eclecticlight.co/feed/
2. https://derflounder.wordpress.com/feed/
3. https://500ish.com/feed

According to websub.rocks, examples 1 and 2 aren't valid websub feeds and 3 is. FreshRSS is updating all three example feeds (i.e. I get new posts from those feeds) but I get the errors listed above over and over.

**Environment information:**
- Device: iPhone 15 pro and Mac Studio for clients (Reeder)
- OS: macOS Sonoma
- Browser: Safari 17.1
- FreshRSS version: 1.22.1
- Database version: Maria 11.1.2
- PHP version: PHP 8.1

PHP, MariaDB and Apache are installed via Brew.

**Additional context**
I've also tried this on a Docker install and am seeing the same issue. Have I misconfigured something? Any pointers would be most appreciated.

**Comment by Alkarex** [comment]
Hello,
Check first that your *Base URL* is correct:

![image](https://github.com/FreshRSS/FreshRSS/assets/1008324/0f919f88-a519-4808-94b7-cee56d66c874)

**Comment by Alkarex** [comment]
Regarding https://500ish.com/feed

```
WebSub subscribe to https://500ish.com/feed via hub http://medium.superfeedr.com/ with callback https://freshrss.example.net/api/pshb.php?k=?????: 422 We could not verify your callback Error: certificate has expired
```

Seems to be related to https://github.com/superfeedr/documentation/issues/155

https://derflounder.wordpress.com/feed/ and https://eclecticlight.co/feed/ seem to work, at a quick glance (need to wait for a push update).

If you get errors with those feeds, double-check the permissions in `./data/PubSubHubbub/` and its subfolders, but the errors you are showing could indicate that some files here have been removed (if this is the case, they will be automatically re-created)

**Comment by Alkarex** [comment]
@kour1er Check also your logs in `data/users/_/log_pshb.txt` for additional details

**Comment by kour1er** [comment]
Thanks for the quick and exactly right response! The permissions in my ./data directory had got screwed up - I have *no* idea how! All working great again.

Very interesting about the superfeedr issue - I wonder how they'll address it.

Thanks again
