### ISSUE TITLE
making items unique in HTML+XPath

### ISSUE THREAD

**Issue by rezad1393** [FreshRSS/FreshRSS#5823]
I have this feed with type HTML+XPath:

```
      <outline text="Youth in Cinema" type="HTML+XPath" xmlUrl="https://www.youthincinema.com/index.php" htmlUrl="https://www.youthincinema.com/index.php" description="RSS feed of Youth in Cinema" frss:xPathItem="//div[@class=&quot;movieinfo&quot;]" frss:xPathItemTitle="descendant::b[1]/a" frss:xPathItemContent="." frss:xPathItemUri="descendant::a/@href" frss:xPathItemTimestamp="descendant::b[contains(text(),'Movie added at')]/following-sibling::text()[1]" frss:xPathItemThumbnail="descendant::img/@src"/>
    </outline>
```

I fine tuned it to have date extracted from post and so on.

but every time a new items gets added all of max number of post on the page get shown as new post.

how I can make freshrss not show past posts as new ones?
is it related to 
```
XPath (relative to item) for:
item unique ID
```

I remember that when I was trying to fine tune the feed and I would put a wrong one for titles it would show something like 
URN:hash-a-lot-of-characters

is that a hash?
of the post?

can I use that for unique ids?

does anyone here has experience with this xpath feature of freshrss that can guide me?

**Comment by Alkarex** [comment]
Quick answer already: make sure to fill the *item unique ID* field. You can use the same expression as for your *item link (URL)*. This will help existing posts not being added again.
