### ISSUE TITLE
Installing on subdomain

### ISSUE THREAD

**Issue by Draky50110** [FreshRSS/FreshRSS#5836]
Hello.

I previously installed a FreshRSS instance on http://www.domain.com/freshrss and all worked ok.

Now, I create a subdomain on my webhost to link http://rss.domain.com to http://www.domain.com/frss and I changed config variable "base_url" from "http://www.domain.com/freshrss/p" to "http://rss.domain.com/p" but now if I enter the website, it display http://rss.domain.com normally but clicking on webpage title it tries to open... this : 

http://rss.domain.com/p/i/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/p/ and it adds "/p" ever and ever.

Did I miss something ?

Thanks.

**Comment by Alkarex** [comment]
Might be the same issue than https://github.com/FreshRSS/FreshRSS/issues/5817
I need to look into it. Could you already try adding a slash at the end of your path?

**Comment by Draky50110** [comment]
Just tried : same result.
Changed "base_url" from "http://rss.domain.com/p" to "http://rss.domain.com/p/" without success.

**Comment by Alkarex** [comment]
I cannot immediately reproduce a problem.
But make sure your `http://rss.example.net/` points in your file structure to something like `/srv/FreshRSS/p/` including the `/p/`
Try also from another browser to make sure you do not have any redirection cached

**Comment by Draky50110** [comment]
I might have found an explanation, not very funny : http://rss.domain.com (and base_url = "http://rss.domain.com/p") is full okay with Firefox, but is a problem with Chrome.

Tested on Chrome 109 (last Win7 compatible version) and Firefox 115.3.1 ESR.

Will test @home with more recent versions on Ubuntu.

On Chrome, beyond the /p/p/p and so problem, if I don't click on the page, it tries to refresh itself (don't know how many minutes between refresh) but it displays the red message banner that it failed because of an Internet problem.
If I click on the webpage logo, it tries to go to /p/p/p etc URL and if I enter the URL manually, it displays all new RSS news correctly.
And it goes mad after next refresh and so.
So cronjob is ok, only displaying webpage is not ok.

Another fact : webpage logo goes to /p/i and if I enter manually http://rss.domain.com/p/i Chrome goes mad but if I enter http://rss.domain.com/p all is ok with ID append at the end of URL which becomes http://rss.domain.com/p/i/?rid=654e051de5501 automatically.

Entering manually /p/i in Firefox is ok though.

I still don't know why there is a red banner error message.

**Comment by Alkarex** [comment]
Try with another Chrome or with a clean cache

**Comment by Draky50110** [comment]
Can't use a newer Chrome for now (blocked with Win7 at work for now).
Will try a newer at home.

Will also try to clean cache on this old Chrome.

EDIT : OMG cleaning Chrome cache works ! How is it possible !
Will test this at home though...

**Comment by Draky50110** [comment]
All is ok now, thanks for the tip.
