### ISSUE TITLE
[BUG] Renaming Label with error

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#5840]
**Describe the bug**
`SQL error FreshRSS_TagDAO::updateTagName["HY093",null,null] ` when renaming a label

**To Reproduce**
1. Go to 'Label management'
2. Rename a label
3. The notification shows, that the renaming was successful
4. Check the label list: it was not renamed
5. check the log: see the error log entry

**Expected behavior**
If there is an error, than I expect an error notification instead a success message.
Of course I would expect that there is no error ;)

**Screenshots**
![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/25576374-7bbe-46fc-93f7-aa26a9c0c8ff)

![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/748c0ddf-d264-45b2-b37f-89c8c8fb2e15)

![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/6ac4a7ed-19dd-412c-bc0d-abe2578a9507)

**Environment information (please complete the following information):**
- FreshRSS version: 1.22.2-dev
- Database version: MySQL + SQlite

**Comment by Alkarex** [comment]
Please try https://github.com/FreshRSS/FreshRSS/pull/5842
