### ISSUE TITLE
[BUG] YouTube description formatting not maintained in external RSS Readers

### ISSUE THREAD

**Issue by FireFingers21** [FreshRSS/FreshRSS#5844]
**Describe the bug**
Descriptions for YouTube videos don't include linebreaks when viewing FreshRSS articles in a third-party RSS reader. They are just a single line of text which readers wrap to fill the content space. Viewing articles from the FreshRSS web view does not have this problem.

**To Reproduce**
I have synced my FreshRSS feed with NetNewsWire on macOS and iOS as well as Vienna RSS on macOS. The issue appears on every platform. Copy/pasting all the text from the description in a plaintext editor indicates there's just a single line of text.

**Expected behavior**
The text from the video description should match the formatting on YouTube itself, regardless of whether you're viewing from the web or a third-party RSS reader.

**Screenshots**
Here is what a YouTube video from FreshRSS currently looks like on NetNewsWire for macOS. It's very hard to read and parse what's going on:
<img width="546" alt="BugReport1" src="https://github.com/FreshRSS/FreshRSS/assets/88227593/63f8d7ec-7b61-4c04-85f1-37c4b8277d80">

**Environment information**
- FreshRSS version: 1.22.1
- Installation type: Docker
- Installed extensions: [Clickable Links](https://github.com/kapdap/freshrss-extensions)

**Comment by Frenzie** [comment]
Sample feed link?

**Comment by Alkarex** [comment]
We need to put a `<pre>...</pre>` inside our `<figcaption>...</figcaption>` and adjust the styling slightly.
Any taker?

**Comment by Frenzie** [comment]
> We need to put a `\<pre\>...\</pre\>` inside our `<figcaption>...</figcaption>` and adjust the styling slightly. Any taker?

Always or would that just coincidentally be nice here?

**Comment by Alkarex** [comment]
> Always or would that just coincidentally be nice here?

Always, I would say

**Comment by FireFingers21** [comment]
> We need to put a `\<pre\>...\</pre\>` inside our `<figcaption>...</figcaption>` and adjust the styling slightly. Any taker?

Putting a `<pre></pre>` tag in the `<figcaption></figcaption>` seems to just turn the description into a scrollable box. Now that you've given me an idea of where the issue lies, I found that using the `nl2br()` function on `$description` to replace newline characters with `<br>` tags properly maintains linebreaks for the API. You just need to remove the call for the `enclosure-description` class and remove it from the css files, otherwise the web view will display duplicate linebreaks.

Does this seem like a better solution?

**Comment by Frenzie** [comment]
> Does this seem like a better solution?

That's implicitly what I meant above ftr.

**Comment by FireFingers21** [comment]
Cool, I'm going to look at the CONTRIBUTING.md and figure out how pull requests work. I'm excited to contribute something!
