### ISSUE TITLE
[BUG] freshrss/freshrss:arm removed?

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#5851]
Might be related to #5832, but arm tag seems to be missing.
```
pi@raspberry:~# docker pull freshrss/freshrss:arm
Error response from daemon: manifest for freshrss/freshrss:arm not found: manifest unknown: manifest unknown
```

**Comment by Alkarex** [comment]
Yes, we have transitioned to multi-architecture images. Please try `freshrss/freshrss:edge` or `freshrss/freshrss:1.21.1-arm`.

`freshrss/freshrss` will work again for ARM from next release
