### ISSUE TITLE
[BUG] Cannot Update Feed or Mark as Read

### ISSUE THREAD

**Issue by jsphnecclia** [FreshRSS/FreshRSS#5855]
I managed to break a working installation somehow.

Lots of broken functionality -- Cannot Update Feed or Feeds or Mark anything as read.

Everything is green on the installation check page.

When I click to refresh feeds it says 'There are no feeds to refresh'. When I click Mark all as Read, It says "The selected articles have been marked as read", but does nothing.

My first thought is that it is a permissions error, but I checked that (and the installation check page permissions section is all green)

**Comment by Alkarex** [comment]
What database are you using?
Check the write access rights in the data folder and subfolders, in particular `data/users/you/*`
