### ISSUE TITLE
The Google Reader Api Problem 

### ISSUE THREAD

**Issue by pipuwong** [FreshRSS/FreshRSS#5856]
The Google Reader Api Problem ：

FreshRSS API endpoints
Google Reader compatible API
Your API address:
https://rss.example.com/p/api/greader.php
Google Reader API configuration test:
❌ OK
Fever compatible API
Your API address:
https://rss.example.com/p/api/fever.php
Fever API configuration test:
✔️ PASS

My Setup：
os：debian 12
php: 8.2.10
FreshRSS is the latest version ( 1.22.1 )
nginx web server

My installation method:
 put the directory by downloading the source code, and then access the domain name

![CleanShot 2023-11-11 at 10 40 39@2x](https://github.com/FreshRSS/FreshRSS/assets/53525622/ae09e368-b564-4a62-aee9-85f616b32f56)
![CleanShot 2023-11-11 at 10 39 59@2x](https://github.com/FreshRSS/FreshRSS/assets/53525622/1ca68dc5-82ac-4551-bbf9-cc168b262bda)

**Comment by klsdfjo** [comment]
![CleanShot 2023-11-11 at 11 46 28@2x](https://github.com/FreshRSS/FreshRSS/assets/53525622/4eddbf3c-6b20-4e0a-86a9-175d88e38bbe)

**Comment by klsdfjo** [comment]
![Uploading CleanShot 2023-11-11 at 11.47.22@2x.png…]()

**Comment by pipuwong** [comment]
everything is ok
![CleanShot 2023-11-11 at 11 47 22@2x](https://github.com/FreshRSS/FreshRSS/assets/53525622/e5817957-9694-443e-a704-808c08401c38)

**Comment by Alkarex** [comment]
Hello,
Have you checked our documentation for nginx?
https://freshrss.github.io/FreshRSS/en/admins/10_ServerConfig.html#nginx-configuration

Note in particular the `root` instruction, which points **inside** the `p/` folder, and the regex of the `location` instruction

**Comment by Alkarex** [comment]
Alternatively, consider using our ready-to-use Docker image https://hub.docker.com/r/freshrss/freshrss/

**Comment by gpion** [comment]
Hello

I'm not using Nginx neither any kind of reverse proxy, but I'm getting the same error.
Strangely directly typing the greader URL API in a browser returns a blank page with only "OK" text in it
And I'm unable to login using a comptible Android client "error : Auth Failed"
Nothing is displayed in freshRSS logs.

**Comment by Frenzie** [comment]
The OK is not strange, but a means to distinguish from not OK.

You need to set a separate API password.

**Comment by gpion** [comment]
> You need to set a separate API password.

Yes I've set it (and even changed it recently)

**Comment by gpion** [comment]
Just changed it again but something is strange, after having entered the new API password in the UI and pressing _"submit"_ there  is no visible acknowledgement that it has effectively been reset (something like _"API password successfully changed"_ for instance)
And trying to configure my Android client with this new password stills fails.

**Comment by gpion** [comment]
Cleared both user and system log, tried again, still getting "auth failed" and logs are still empty

**Comment by gpion** [comment]
I've found that error in the web server log (anonymised)

`2024/03/26 08:12:41 [error] 1307#1307: *269931 open() "/var/services/web/FreshRSS/p/api/greader.php/api/greader.php/accounts/ClientLogin" failed (20: Not a directory), client: 2a01:e0a:382:c820:9d96:87a9:6f51:4b49, server: , request: "POST /FreshRSS/p/api/greader.php/api/greader.php/accounts/ClientLogin?Email=<USER>&Passwd=<PASS> HTTP/1.1", host: "<HOST>"
`

**Comment by gpion** [comment]
Calling the API with curl is successfull (response "OK") *even* when using an invalid password!

**Comment by Frenzie** [comment]
> I've found that error in the web server log (anonymised)
> 
> `2024/03/26 08:12:41 [error] 1307#1307: *269931 open() "/var/services/web/FreshRSS/p/api/greader.php/api/greader.php/accounts/ClientLogin" failed (20: Not a directory), client: 2a01:e0a:382:c820:9d96:87a9:6f51:4b49, server: , request: "POST /FreshRSS/p/api/greader.php/api/greader.php/accounts/ClientLogin?Email=<USER>&Passwd=<PASS> HTTP/1.1", host: "<HOST>" `

Clearly the client is adding `api/greader.php` at the end.

> Calling the API with curl is successfull (response "OK") _even_ when using an invalid password!

Define calling the API. ;-)

**Comment by gpion** [comment]
> Define calling the API. ;-)

'curl -v 'https://\<FQDN\>/p/api/greader.php?Email=\<user\>&Passwd=\<pass\>'

**Comment by Frenzie** [comment]
It might indeed be better if it returned 401 or similar in that case, but that's merely the API endpoint. See https://freshrss.github.io/FreshRSS/en/developers/06_GoogleReader_API.html for some API samples. (Also without asking @Alkarex I typically don't know if something is a minor niggle in FreshRSS or some important part of being properly compatible with the GReader API, weirdness included. :-)

**Comment by gpion** [comment]
> Clearly the client is adding api/greader.php at the end.

The client I'm trying to use is [FeedMe](https://github.com/seazon/FeedMe) BTW
It seems very bugged regarding connections to a Greader compatible service
I'm totally ok to select another one if suggested.

**Comment by Frenzie** [comment]
Like I said above, presumably it should work if you remove the `api/greader.php` from the end.

**Comment by gpion** [comment]
> it should work if you remove the `api/greader.php` from the end.

not it doesn't, 

I've kept the correct host but put a random subdomain ("xxxxxx") in  the field

And here's what I get in the web server log, as if "greader.php" was a directory : 

`2024/03/26 10:04:12 [error] 1308#1308: *295104 open() "/var/services/web/xxxxxx/api/greader.php/accounts/ClientLogin" failed (2: No such file or directory), client: <IP>, server: , request: "POST /xxxxxx/api/greader.php/accounts/ClientLogin?Email=<user>&Passwd=<pass>HTTP/1.1", host: "<fqdn>"`

**Comment by gpion** [comment]
I'm switching to another approach with option _"Allows access to RSS output of the default user without authentication"_ with a secure unique token.
That allow to usa any RSS client. The downside is that I'm loosing FressRSS categories.

**Comment by Frenzie** [comment]
> And here's what I get in the web server log, as if "greader.php" was a directory :

That is how the API works.

**Comment by gpion** [comment]
> > And here's what I get in the web server log, as if "greader.php" was a directory :
> 
> That is how the API works.

Maybe but it in my case it fails with that "not a directory" error:

`2024/03/26 11:06:33 [error] 1308#1308: *309822 open() "/var/services/web/FreshRSS/p/api/greader.php/accounts/ClientLogin" failed (20: Not a directory)"`

**Comment by Frenzie** [comment]
You said you weren't using nginx, but what are you using instead?

On a properly configured server these are the two return states:
```
$ http 'http://localhost:8080/api/greader.php/accounts/ClientLogin?Email=Frenzie&Passwd='
HTTP/1.1 401 Unauthorized
Connection: Keep-Alive
Content-Length: 13
Content-Type: text/plain; charset=UTF-8
Date: Tue, 26 Mar 2024 20:02:59 GMT
Google-Bad-Token: true
Keep-Alive: timeout=5, max=100
Server: Apache/2.4.54 (Unix)
X-Powered-By: PHP/8.0.26

Unauthorized!
```

```
$ http 'http://localhost:8080/api/greader.php/accounts/ClientLogin?Email=Frenzie&Passwd=1234567'
HTTP/1.1 200 OK
Connection: Keep-Alive
Content-Length: 117
Content-Type: text/plain; charset=UTF-8
Date: Tue, 26 Mar 2024 20:02:32 GMT
Keep-Alive: timeout=5, max=100
Server: Apache/2.4.54 (Unix)
X-Powered-By: PHP/8.0.26

SID=Frenzie/2f11f24e4555b541c6d5712b94b7ad626ff34649
LSID=null
Auth=Frenzie/2f11f24e4555b541c6d5712b94b7ad626ff34649
```

**Comment by gpion** [comment]
> You said you weren't using nginx, but what are you using instead?

Sorry my bad, it's nginx which is running my host (a Synology NAS) web server.  

> On a properly configured server these are the two return states:

on my FreshRSS instance the "api" subdirectory is not at root of the site but inside the "p" subdirectory
So instead of 
`'http://localhost:8080/api/greader.php/accounts/ClientLogin?Email=Frenzie&Passwd='`
I should probably use :
`'http://localhost/FreshRSS/p/api/greader.php/accounts/ClientLogin?Email=Frenzie&Passwd='`

Anyway, on my installed FreshRSS site, in each case (correct or incorrect password) the HTTP return status is 'HTTP/1.1 404 Not Found'
Meanwhile, the web interface to FreshRSS runs fine though.

In the nginx log, when I use "/api/greader.php/accounts/ClientLogin?Email..." the error is _"no such file or directory"_ and with "/p/api/greader.php/accounts/ClientLogin?Email..." it is _"Not a directory"_ 
Which I think make sense since there is no "api" directory at the root of the site for the first url, and "greader.php" is a file and not a directory for the second.

**Comment by Frenzie** [comment]
nginx does require some special configuration for the API, see a sample here: https://freshrss.github.io/FreshRSS/en/admins/10_ServerConfig.html

**Comment by gpion** [comment]
Since I didn't wanted to take the risk of messing up nginx configuration of my NAS (since it's shared by several system components) I've decided to go with the Docker method (nginx being pre-configured there).
And it worked.
I remember having made this work long time ago without Docker (which did'nt even existed at that time) but I'm not sure how I had managed to set it up.
