### ISSUE TITLE
[BUG] can't find translation for "The post" and "appeared first on"

### ISSUE THREAD

**Issue by igor17721** [FreshRSS/FreshRSS#5869]
I'm using a russian translation of the "freshRSS" and it partially missed a translation for these two bits at the bottom of articles: "**The post**" and "**appeared first on**".

I've checked every file inside **/usr/share/FreshRSS/app/i18n/ru**, but didn't find these values. Can you tell me exact file location and row where I can manually translate them myself? Thanks!

![Capture](https://github.com/FreshRSS/FreshRSS/assets/108469300/4bd030cb-6e72-4a9b-bd25-540bd128d998)

**Comment by Alkarex** [comment]
Hello,
This looks like some content coming from the feed, and not from FreshRSS itself, so not something you can translate

**Comment by igor17721** [comment]
> Hello, This looks like some content coming from the feed, and not from FreshRSS itself, so not something you can translate

Thanks! One more question, please!

Which PHP file generates these tags below an article? Could you please share pathway to the file and indicate a row number, so I can delete it from the code? 

![Capture](https://github.com/FreshRSS/FreshRSS/assets/108469300/ecff6ebd-7618-42f1-8596-afd39dd45e05)

**Comment by Frenzie** [comment]
You could do that, but it's probably a lot easier in settings → display → disable article tags. ;-)

![image](https://github.com/FreshRSS/FreshRSS/assets/202757/a7f62adb-f2de-4046-a37c-046fc87cf74c)

**Comment by igor17721** [comment]
> You could do that, but it's probably a lot easier in settings → display → disable article tags. ;-)

it's still visible after removing tickmarks from the settings on your screenshot above

**Comment by Frenzie** [comment]
The my labels thing can't be toggled? That sounds like an oversight.

**Comment by Alkarex** [comment]
Ah, indeed. PR welcome
