### ISSUE TITLE
[BUG] "Max number of articles to keep unread" does not work on cron updates

### ISSUE THREAD

**Issue by matejdro** [FreshRSS/FreshRSS#5870]
**Describe the bug**

It seems like per-feed "Max number of articles to keep unread" option only works when user manually refreshes the feed. When feed is updated automatically (via `app/actualize_script.php`), this option is ignored.

**To Reproduce**
1. Have a feed that will receive lots of unread articles after refresh
2. Set "Max number of articles to keep unread" to lower number than number of unread articles in the feed
3. Call `app/actualize_script.php`

**Expected behavior**

After cron update, only last N articles (where N = "Max number of articles to keep unread") should remain unread.

**Environment information (please complete the following information):**
- Device: Desktop
- OS: Arch Linux
- Browser: Firefox 119.0.1
- FreshRSS version:  1.22.1 
- Database version: Postgres
- PHP version: One included in official docker image
- Installation type: Docker

**Additional context**

/

**Comment by matejdro** [comment]
Possibly related to #5702?

**Comment by Alkarex** [comment]
Try first to check for how long your feed has not been cleaned.

This option is not strictly enforced at each refresh, because it is a bit resource intensive, so to save energy, this is done once every 30 times a given feed is refreshed, in average:

https://github.com/FreshRSS/FreshRSS/blob/9eba8726ac08d75730a9ed5fd26047f502007dfd/app/Controllers/feedController.php#L559-L567

So for instance with a feed refreshed every hour, the cleaning will be done about once per day.

**Comment by Alkarex** [comment]
Ah, sorry, this is not the same option... Let me check

**Comment by Alkarex** [comment]
At the moment, that option is applied to existing articles *before* the insertion of new articles. Could that maybe explain what you are observing? I do not believe there is any difference between the cron and manual updates.

**Comment by matejdro** [comment]
I've did a bit of testing and this is what I got:

1. Max number of articles to keep unread was set to 20, with 25 existing unread items in this feed
1. I made a backup of the database (So I could reproduce the same conditions every time)
2. I did manual refresh (refresh button in UI). After the refresh, I got 19 unread items (not sure why 19 instead of 20, but this is besides the point) - option seems to work
3. I've restored the backup to point 1 and now refreshed with `actualize_script.php` and after refresh finished, I got 30 unread items. It appears that option did not work this time.

If desired, you can give me some pointers for extra logging that I can add and re-test for more info.

>  that option is applied to existing articles before the insertion of new articles. 

Yeah, I would argue that this is not how the option should work. If I set the option to keep 20 unread articles and then refresh generates 30 unread articles (after insertion), I would expect to still only get 20 most recent unread.

**Comment by Alkarex** [comment]
To be a bit more precise, the current implementation can at max mark all the current articles as read, so if there are more new articles than the threshold, the difference will first be marked as read during the next refresh.

Ok, I will try to investigate a bit.

The relevant code is: https://github.com/search?q=repo%3AFreshRSS%2FFreshRSS%20keepMaxUnread&type=code

**Comment by Alkarex** [comment]
Refactoring coming

**Comment by Alkarex** [comment]
Please test the `edge` version of FreshRSS. Feedback welcome

**Comment by matejdro** [comment]
After some initial testing, I can confirm that the bug seems to be resolved. Thanks!

**Comment by Alkarex** [comment]
Excellent! Thanks for the feedback :-)
