### ISSUE TITLE
[BUG] Stopped updating

### ISSUE THREAD

**Issue by gingerbeardman** [FreshRSS/FreshRSS#5888]
**Describe the bug**
I just had to restart FreshRSS container to get it to update feeds. 

It had stopped updating late Tuesday 14th. 2 days ago. 

Logging into FreshRSS was possible, but nothing appeared to be wrong. 

Refreshing All brought in no new articles. 

Restarting docker container and then doing a refresh brought 59 new articles. 

**To Reproduce**
n/a

**Expected behavior**
- feeds should continue to update
- error message should be shown prominently

**Screenshots**

![image](https://github.com/FreshRSS/FreshRSS/assets/49612/abfe952d-d05a-4815-9952-6daac29a0ce9)

**Environment information (please complete the following information):**
- Device: Synology NAS
- OS: Synology DSM 6.2.3
- Browser: Safari
- FreshRSS version: 1.22.1
- Database version: PDO +1
- PHP version: 8.2.12
- Installation type: docker container

**Additional context**
- please ask me and give me directions to provide additional info

**Comment by Alkarex** [comment]
Hello,
What Docker image are you using?
If you use our normal (Debian based) Docker image, try our Alpine version, or vice versa

**Comment by Alkarex** [comment]
Quick note: this is unrelated to FreshRSS but is a sign of networking problem, possibly at Docker network level

**Comment by gingerbeardman** [comment]
Interesting...

Docker image is: `lscr.io/linuxserver/freshrss:latest` which I believe is Alpine?

If this isn't the official one, I apologise, and I'll try to switch to an official one if that will improve things when I can, assuming all my data will remain. Here's my data folder:

![Screen shot 2023-11-17 at 16 31 05](https://github.com/FreshRSS/FreshRSS/assets/49612/9e88d21a-2741-4602-b3d6-3ef0ceceb43e)

Regarding network connectivity, ~~I cannot say for certain whether network has been down or not (it's at a remote location, so let's say there is a chance)~~

There was some down time either side of midnight from 15th going into 16th. Maybe it's the same event, it's difficult to say when the last refresh happened from memory. The logs are so full with errors they don't go back far enough.

![image](https://github.com/FreshRSS/FreshRSS/assets/49612/a6641ea7-44fd-4dee-a3c9-8db8b2d4a68f)

But of course network was back up at the time I logged in to check and try a refresh (to no avail) and just before I did the restart of the container. Anyway, this would imply that a docker network level interruption is enough to put FreshRSS in this state (where no updates are received and a restart of the container is required)? Or do I misunderstand?

**Comment by math-GH** [comment]
That is our official Docker repository: https://hub.docker.com/r/freshrss/freshrss

**Comment by Alkarex** [comment]
> Anyway, this would imply that a docker network level interruption is enough to put FreshRSS in this state (where no updates are received and a restart of the container is required)? Or do I misunderstand?

By far in most cases, the service will resume just fine after a network restart or server restart.

But Docker is known to have some (rare) networking instabilities, which are independent of our code (i.e. there is no improvement that we can do on FreshRSS side; and also affecting other services than FreshRSS). Docker has also regularly some new versions, which might fix but also introduce some bugs, so this also depends on your Docker version (I personally prefer the one shipping with Debian or Ubuntu).
I have personally experienced Docker network connectivity issues a few times over the years on different servers (never for FreshRSS), and it is hard to tell, but in my case it seemed to have been in relation with other system updates on the same machine, network reconfigurations, or cluster reconfigurations in the data centre.

**Comment by gingerbeardman** [comment]
Absolutely! I understand. 

I need to do an upgrade my system somewhat comprehensively. Currently some things are lagging. 

Closing.
