### ISSUE TITLE
[Feature] A way to see more of the title with a mobile device

### ISSUE THREAD

**Issue by rakoo** [FreshRSS/FreshRSS#5899]
First of all, thank you very much for FreshRSS !

**Is your feature request related to a problem? Please describe.**
I use FreshRSS with the web interface both on desktop and mobile with the normal view. On desktop everything is great. On mobile because the screen isn't super wide I only see a small part of the title. My problem is that the title is the main data point that tells me whether I will read the content or not, so right now I kind of have to open everything.

**Describe the solution you’d like**
If the title were on a second line, or on multiple lines, I could see all of it.

**Describe alternatives you’ve considered**
I'm trying the reading view, but by design it shows me the full content for all articles and I can't quickly scroll to the next item

**Additional context**
Here's a screenshot to see what it looks like. You can see some context is missing to understand what the item is talking about.

![Screenshot_20231122-173851_Mull_1](https://github.com/FreshRSS/FreshRSS/assets/501707/af024d17-867c-4ded-9a86-1fca60778c5d)

**Comment by Frenzie** [comment]
I'd like to make it the default, but for now see https://github.com/FreshRSS/Extensions/tree/a86467db48d5283cac19818e93a26a1097d026af/xExtension-TitleWrap

**Comment by Alkarex** [comment]
@Frenzie See https://github.com/FreshRSS/FreshRSS/discussions/5900

**Comment by math-GH** [comment]
see #4857 too

**Comment by rakoo** [comment]
Since it's being worked on I guess it's OK to close this issue, I'll be waiting for progress :)
