### ISSUE TITLE
[BUG] Medium.com RSS feeds have new articles every day, even if those articles are old

### ISSUE THREAD

**Issue by benlk** [FreshRSS/FreshRSS#5909]
**Describe the bug**
A Medium feed presents its entries as "new" each day, though the publication and updated dates in the feed are unchanged.

**To Reproduce**
1. Add https://sghardin.medium.com/feed
3. Mark all items in that feed as read.
4. Wait until the next day
5. See the bug: Though there are no new articles on the blog, every single article on it is presented as new items.

**Expected behavior**

I would expect that after being marked read, the article remains read.

**Screenshots**

**Environment information (please complete the following information):**
- Device: Phones and desktops
- OS: Android 13, Ubuntu 23.04 and 23.10, MacOS current
- Browser: Firefox, Chrome, Firefox for Android
- FreshRSS version: 1.21
- Database version: [e.g. Mysql 5.7]
- PHP version: PHP 7.3 (I know)
- Installation type: Softaculous

**Additional context**

This behavior is not exhibited by any other non-Medium feed. I haven't tried adding any other Medium feeds.

**Comment by Alkarex** [comment]
The way to debug is:
* Save the XML document today https://sghardin.medium.com/feed
* Save the XML document tomorrow (or when the next update arrives)
* Compare and show the differences

**Comment by benlk** [comment]
Today: [feed-2023-11-27.xml.txt](https://github.com/FreshRSS/FreshRSS/files/13478719/feed-2023-11-27.xml.txt)

**Comment by benlk** [comment]
Today: [feed-2023-11-28.xml.txt](https://github.com/FreshRSS/FreshRSS/files/13493645/feed-2023-11-28.xml.txt)

```
$ diff feed-2023-11-27.xml.txt feed-2023-11-28.xml.txt 
12c12
<         <lastBuildDate>Mon, 27 Nov 2023 18:09:50 GMT</lastBuildDate>
---
>         <lastBuildDate>Tue, 28 Nov 2023 22:00:38 GMT</lastBuildDate>
```

The only difference between yesterday and today is the `lastBuildDate`. There aren't any new items in the feeds.

**Comment by Alkarex** [comment]
And what was the outcome for you today: were your existing articles unread again, or did new articles appear?

**Comment by benlk** [comment]
Today: [feed-2023-11-29.xml.txt](https://github.com/FreshRSS/FreshRSS/files/13501640/feed-2023-11-29.xml.txt)

```
$ diff feed-2023-11-28.xml.txt feed-2023-11-29.xml.txt 
12c12
<         <lastBuildDate>Tue, 28 Nov 2023 22:00:38 GMT</lastBuildDate>
---
>         <lastBuildDate>Wed, 29 Nov 2023 14:26:54 GMT</lastBuildDate>
```

With that difference between yesterday's feed and today's, the four existing articles were again presented as unread: 

![Screenshot 2023-11-29 at 09 29 10](https://github.com/FreshRSS/FreshRSS/assets/1754187/2008328b-0c50-46df-88f7-86b4332bd918)

**Comment by benlk** [comment]
If it's of any relevance, this RSS feed is imported as part of an OPML file: https://github.com/benlk/columbus-misc-rss/blob/trunk/subscriptions.opml

The OPML file hasn't changed since yesterday.

**Comment by Alkarex** [comment]
> is imported as part of an OPML file

Via Dynamic OPML, or just a manual OPML import?

**Comment by benlk** [comment]
Dynamic OPML. I'll add another RSS feed via direct RSS import (https://doctorow.medium.com/feed) to see if the problems reproduce there.

**Comment by benlk** [comment]
Inaccurate results in today's test; the Doctorow feed actually posted updates today.

**Comment by benlk** [comment]
Oh, here's an interesting complication: The Medium feed which has been showing up every day has been duplicating its subscription, though that's not in the OPML:

![Screenshot 2023-12-01 at 21 50 33](https://github.com/FreshRSS/FreshRSS/assets/1754187/2cd001b2-9a69-4b93-9d8c-44f85f80b9b4)

**Comment by Alkarex** [comment]
What are the URLs of all those feeds?

**Comment by benlk** [comment]
The URLs are the same: https://medium.com/feed/@sghardin

**Comment by Alkarex** [comment]
So this is the only feed with that problem, among those of that Dynamic OPML?
What database are you using?

**Comment by Alkarex** [comment]
It might be due to the `@` sign in the URL. I will try to investigate
Edit: no, that does not seem to be that

**Comment by Alkarex** [comment]
Could you try to apply this patch https://github.com/FreshRSS/FreshRSS/pull/5917 to get more debug logs?

**Comment by benlk** [comment]
I haven't been able to apply that patch yet (perhaps this weekend) but I did see this in the logs:

```
  | 2023-12-07 08:04:39 | Error while WebSub subscribing to https://medium.com/@sghardin/feed
  | 2023-12-07 08:04:39 | Error while WebSub unsubscribing from https://medium.com/feed/@sghardin
  | 2023-12-07 08:04:39 | JSON not found for WebSub: https://medium.com/feed/@sghardin
```

**Comment by Alkarex** [comment]
The WebSub warnings are another issue, which I do not believe influence the results we see here (and I am also working on making some improvements, including reaching out to the WebSub hubs generating some of the errors).

**Comment by MarcusWolschon** [comment]
Same problem with
https://www.heise.de/rss/heise-atom.xml
Both have identical links
```<updated>2024-09-25T08:50:00+02:00</updated>
 <published>2024-09-25T08:50:00+02:00</published>```
The current entry has yesterday as it's date but is shown in today and in yesterday.

![grafik](https://github.com/user-attachments/assets/d25ee3bd-09dd-44c5-9987-c1e3f82cd61e)

**Comment by MarcusWolschon** [comment]
(With code in the posting, the image isn't shown)
![grafik](https://github.com/user-attachments/assets/3e336efa-d5cc-47b2-9437-8af4df5dd917)

**Comment by Alkarex** [comment]
@MarcusWolschon Please keep a copy of the RSS feed of a few days and post them back here when you notice a problem.
Check our FAQ https://github.com/FreshRSS/FreshRSS/discussions/6101

**Comment by MarcusWolschon** [comment]
Oh, looks like it has 2 DB entries with the GUID and with the URL as GUID in the DB.
![grafik](https://github.com/user-attachments/assets/89b50ca7-34f2-4c3c-a727-ed428070f2eb)

@benlk can you see the same with your newly unread entries in the " freshrss_<user>_entry" DB table?
`SELECT *, COUNT(hash) FROM freshrss_<user>_entry GROUP BY hash HAVING COUNT(hash) > 1; `
should find them all.

In my case it finds only that one, duplicate entry as older instances of this happening (sometimes hundreds of postings from that feed) are too old now.

**Comment by Alkarex** [comment]
@MarcusWolschon Having two types of GUIDs is likely due to the feed having had bad GUIDs (i.e. multiple articles with the same GUID inside the same feed) during a period and then good GUIDs again (or the other way around). Check in your logs, you might have had a notice about that.

I will actually very soon change this behaviour as part of https://github.com/FreshRSS/FreshRSS/pull/4487#issuecomment-2380659748 not to automatically change the GUID policy back to normal after a feed has broken it, and also by adding an option to manually set a GUID policy for non-compliant feeds (e.g. using the article link as unique identifier, or a few other options).
