### ISSUE TITLE
[Feature] RSS FEED as a link

### ISSUE THREAD

**Issue by RogueGhost93** [FreshRSS/FreshRSS#5919]
Is it possible to have RSS Feed as a link instead of dowloaded file of all of my news in freshrss? To integrate it with self hosted apps like Homarr.
 Thanks

**Comment by Alkarex** [comment]
I have not understood the question.
Can you try to reformulate? Maybe giving examples

**Comment by math-GH** [comment]
Try right click on the RSS icon and chose "copy link"
