### ISSUE TITLE
[BUG] This feed is empty. Please verify that it is still maintained.

### ISSUE THREAD

**Issue by igor17721** [FreshRSS/FreshRSS#5922]
I'm using the latest version of FreshRSS and I get this error while trying to add this feed - https://novayagazeta.eu/feed/rss

The validator says everything is ok, but fetching articles from the rss still not working. 

![Untitled](https://github.com/FreshRSS/FreshRSS/assets/108469300/adfcc234-5551-40ff-946b-3953257da223)

**Comment by Frenzie** [comment]
I think that misleading error message was improved recently.

But that aside, I can't confirm any issues on my end. Could you check with curl from the server?
![image](https://github.com/FreshRSS/FreshRSS/assets/202757/e2aa8609-0e1a-461c-ada6-250c34605424)

**Comment by igor17721** [comment]
> I think that misleading error message was improved recently.
> 
> But that aside, I can't confirm any issues on my end. Could you check with curl from the server? ![image](https://private-user-images.githubusercontent.com/202757/287551039-e2aa8609-0e1a-461c-ada6-250c34605424.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNDc2NDUsIm5iZiI6MTcwMjI0NzM0NSwicGF0aCI6Ii8yMDI3NTcvMjg3NTUxMDM5LWUyYWE4NjA5LTBlMWEtNDYxYy1hZGE2LTI1MGMzNDYwNTQyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMFQyMjI5MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YTIwZDgzYjA3YTI0NWY2MWUzMDk0MzNjNGIxN2QxNTkxYjgwM2IwMWQ0ZTUyNTk0MWM5ODUwYmRmOWJjYjNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eO2idjinoNVzKqagE6ZPDtv6OdY-wZtXZN0YOJ1JHcY)

Can you explain what do I need to do, please? Do I need to update my FreshRSS or what? It worked okay before I made a post on github about this. But something went wrong either on my server or else, and FreshRSS stopped fetching articles from that source. It's still doesn't work, while other news sources are fetching without a problem.

I tried:

curl -Is https://novayagazeta.eu/feed/rss | head -n 1

and the server responses with:

HTTP/2 200

**Comment by Frenzie** [comment]
I was thinking of #5827. Do you know otoh if this one is similarly misleading @Alkarex?

> and the server responses with:
> 
> HTTP/2 200

It can respond 200 and still be empty. But you should also try curl with a FreshRSS user agent to see if it's blocked (something like `-A 'FreshRSS/1.22.1'`), or alternatively try a different one in the feed config.

**Comment by igor17721** [comment]
> It can respond 200 and still be empty. But you should also try curl with a FreshRSS user agent to see if it's blocked (something like `-A 'FreshRSS/1.22.1'`), or alternatively try a different one in the feed config.

Thanks for the reply! I found the problem and it was the server. I moved to another one and feed from the website has been added without any problems.
