### ISSUE TITLE
[BUG] Number of articles in "if an identical title already exists in the top n newest articles" resets to 1

### ISSUE THREAD

**Issue by pax0707** [FreshRSS/FreshRSS#5936]
**Describe the bug**
Whatever number you put under "Mark an article as read…  if an identical title already exists in the top n newest articles" is set to "1" after submit.

**To Reproduce**
Settings
Reading 
Enable Mark an article as read… if an identical title already exists in the top n newest articles
Put in any number.
Submit
1

Also - when you disable the option entry goes back to 25.

**Expected behavior**
Keep the set number of articles.

**Screenshots**

**Environment information (please complete the following information):**
<html>
<body>

IMAGE | freshrss/freshrss:edge@sha256:b9fcea6c4fce9597f9c909cd2e439841d369c3322851efdb3bc17fbedb43c85f
Chrome/Fireefox

**Comment by Alkarex** [comment]
Fixed by https://github.com/FreshRSS/FreshRSS/pull/5937
Please try again. Feedback welcome

**Comment by pax0707** [comment]
Confirming fixed.
