### ISSUE TITLE
[BUG] RSS Feed doesnt work - only problem on FreshRSS (Kuketz Blog)

### ISSUE THREAD

**Issue by shruggie1** [FreshRSS/FreshRSS#5949]
**Describe the bug**
A popular feed for IT security doesnt work with FreshRSS. Other readers can read the feed with no problem. The FreshRSS GUI shows only an error.

**To Reproduce**
1. Add https://www.kuketz-blog.de/feed/ to your feeds and wait
2. Error shows after a few minutes

**Expected behavior**
The blog should shown in the FreshRSS GUI, like on other readers like: https://rssatom.de/rssatom?reader=https://www.kuketz-blog.de/feed/

**Screenshots**
<img width="734" alt="Bildschirmfoto 2023-12-17 um 09 52 06" src="https://github.com/FreshRSS/FreshRSS/assets/154050806/b8ca7f27-8c9a-45a4-a43a-f9b469cc618f">
<img width="868" alt="Bildschirmfoto 2023-12-17 um 09 52 26" src="https://github.com/FreshRSS/FreshRSS/assets/154050806/09b0ae52-9ecb-4bb9-8807-cb37c5323e7f">

**Environment information (please complete the following information):**
- Device: iMac 24" M1
- OS: macOS 13.6.3
- Browser: Firefox 120.0.1
- FreshRSS version: 1.22.2-dev
- Database version: ?
- PHP version: ?
- Installation type: ?

**Additional context**
I use the FreshRSS instance from https://frss.adminforge.de/

**Comment by Alkarex** [comment]
This feed works fine for me.

If you can, try to curl from your server (or ask the admin):

```sh
curl -v 'https://www.kuketz-blog.de/feed/'
```

The most likely is that your IP has been blocked (your server, or the IP range of your data centre).

If that is the case, you have two main options:
* Move your FreshRSS instance to another IP, for instance at home;
* Use a proxy for your (problematic) feeds, the proxy being hosted elsewhere.

**Comment by shruggie1** [comment]
Great, thank you!

The admin from the instance said there was an Ipv6 problem in the docker container. He fixed it and now it works!
