### ISSUE TITLE
[BUG] OIDC_X_FORWARDED_HEADERS with multiple values breaks either the auto refresh cron job or the apache configuration

### ISSUE THREAD

**Issue by sidewinder94** [FreshRSS/FreshRSS#5956]
**Describe the bug**

When setting `OIDC_X_FORWARDED_HEADERS` with multiple values either the periodic refresh crashes when sourcing the env.txt file, or the apache server crashes because of misconfiguration

**To Reproduce**

I've setup my freshrss instance to use OIDC with the following environment variables.

```
OIDC_ENABLED=1
OIDC_PROVIDER_METADATA_URL=<uri>
OIDC_CLIENT_ID=freshrss
OIDC_CLIENT_SECRET=<secret>
OIDC_CLIENT_CRYPTO_KEY=<key>
OIDC_REMOTE_USER_CLAIM=preferred_username
OIDC_SCOPES=openid profile
OIDC_X_FORWARDED_HEADERS=X-Forwarded-Host X-Forwarded-Port X-Forwarded-Proto
```

My particular issues revolves around `OIDC_X_FORWARDED_HEADERS` in which you are supposed to be able to define one, several, or all of the options available.

Issue is : 

If the value is surrounded with double quotes like : `OIDC_X_FORWARDED_HEADERS="X-Forwarded-Host X-Forwarded-Port X-Forwarded-Proto"` this makes the apache config crash with the following error :

```
déc. 20 16:42:48 matrix-server systemd[1]: Starting FreshRSS (mash-freshrss)...
déc. 20 16:42:49 matrix-server mash-freshrss[2838603]: e8820354d66e020d192ed4a403ff1841fb1af7e0ec5d47f2605574ee8f6ba398
déc. 20 16:42:49 matrix-server systemd[1]: Started FreshRSS (mash-freshrss).
déc. 20 16:42:49 matrix-server mash-freshrss[2838625]: Enabling module auth_openidc.
déc. 20 16:42:56 matrix-server mash-freshrss[2838625]: apache2: Syntax error on line 225 of /etc/apache2/apache2.conf: Syntax error on line 51 of /etc/apache2/sites-enabled/FreshRSS.Apache.conf: Define takes 1-2 arguments, Define a variable, optionally to a value.  Same as passing -D to the command line.
```

If not, as far as I can tell, the apache config is correct but it breaks the CRON jonb used to automatically refresh the feeds.

Below what happens if I manually execute the CRON expression in container in that case : 
```
root@3cf257dc5145:/var/www/FreshRSS# . /var/www/FreshRSS/Docker/env.txt;                su www-data -s /bin/sh -c 'php /var/www/FreshRSS/app/actualize_script.php'              2>> /proc/1/fd/2 > /tmp/FreshRSS.log
bash: export: `X-Forwarded-Port': not a valid identifier
bash: export: `X-Forwarded-Proto': not a valid identifier
```

**Expected behavior**
The container starts (no apache misconfiguration error) and the crontab expression can be executed.

**Screenshots**
N/A

**Environment information (please complete the following information):**
- Device: N/A
- OS: Ubuntu 22.04 LTS
- Browser: N/A
- FreshRSS version: 1.22.1
- Database version: Postgres 16.1
- PHP version: From Docker Image
- Installation type: Self-Hosted at home as a docker container

**Additional context**
N/A

**Comment by Alkarex** [comment]
Could you please try with our `edge` version?
Some related bugs have already been fixed, e.g. https://github.com/FreshRSS/FreshRSS/pull/5795

**Comment by sidewinder94** [comment]
the edge version indeed fixes the issue.

Unrelated to the current issue, but related to the cron job execution, when executing 
`root@48cadfd65516:/var/www/FreshRSS# . /var/www/FreshRSS/Docker/env.txt;                su www-data -s /bin/sh -c 'php /var/www/FreshRSS/app/actualize_script.php'` in-container, I now get the following error : `           su: cannot set groups: Operation not permitted`

Now obviously, this is not related to the current issue. But is this problem known already ?

If not I'll open another issue with more details (and hopefully it's a misconfiguration on my end), if it is I'll just follow the issue waiting for the resolution

**Comment by Alkarex** [comment]
I cannot reproduce the problem.
Could you try with both `freshrss/freshrss:edge` and `freshrss/freshrss:edge-alpine`?
What platform are you running on?

Can you also try:

```sh
ls -alh /bin/su
```

**Comment by sidewinder94** [comment]
on `freshrss/freshrss:edge`

```
root@48cadfd65516:/var/www/FreshRSS# ls -alh /bin/su 
-rwsr-xr-x 1 root root 71K Mar 23  2023 /bin/su
```

As for the platform, I'm running in docker on Ubuntu 22.04 LTS

edge-alpine fails with permission issues.
```
déc. 21 11:48:22 matrix-server systemd[1]: Starting FreshRSS (mash-freshrss)...
déc. 21 11:48:22 matrix-server mash-freshrss[3414216]: 9ba1f8dbeddd5f5141ad83c7233851785bbc48f6a29bcc8d2f3b1a1c8eca0cc2
déc. 21 11:48:22 matrix-server systemd[1]: Started FreshRSS (mash-freshrss).
déc. 21 11:48:23 matrix-server mash-freshrss[3414238]: mv: can't rename '/etc/apache2/conf.d/mod-auth-openidc.conf.bak': No such file or directory
déc. 21 11:48:23 matrix-server mash-freshrss[3414238]: chown: ./Docker/Dockerfile: Operation not permitted
déc. 21 11:48:23 matrix-server mash-freshrss[3414238]: chown: ./Docker/Dockerfile-Alpine: Operation not permitted
déc. 21 11:48:23 matrix-server mash-freshrss[3414238]: chown: ./Docker/Dockerfile-Oldest: Operation not permitted
[...]
```

Additional info, the container is managed using systemd, the service file looks like : 

```
[Unit]
Description=FreshRSS (mash-freshrss)
Requires=docker.service
After=docker.service
Requires=mash-postgres.service
After=mash-postgres.service
DefaultDependencies=no

[Service]
Type=simple
Environment="HOME=/root"
ExecStartPre=-/usr/bin/env sh -c '/usr/bin/env docker kill mash-freshrss 2>/dev/null || true'
ExecStartPre=-/usr/bin/env sh -c '/usr/bin/env docker rm mash-freshrss 2>/dev/null || true'

ExecStartPre=/usr/bin/env docker create \
			--rm \
			--name=mash-freshrss \
			--log-driver=none \
			--network=mash-freshrss \
			--user=0:33 \
			--cap-drop=ALL \
			--env-file=/mash/freshrss/env \
			--label-file=/mash/freshrss/labels \
			--mount type=bind,src=/mash/freshrss/data,dst=/var/www/FreshRSS/data \
			--mount type=bind,src=/mash/freshrss/extensions,dst=/var/www/FreshRSS/extensions \
			--tmpfs=/tmp:rw,noexec,nosuid,size=512m \
			registry.hub.docker.com/freshrss/freshrss:edge

ExecStartPre=/usr/bin/env docker network connect traefik mash-freshrss
ExecStartPre=/usr/bin/env docker network connect mash-postgres mash-freshrss

ExecStart=/usr/bin/env docker start --attach mash-freshrss

ExecStop=-/usr/bin/env sh -c '/usr/bin/env docker kill mash-freshrss 2>/dev/null || true'
ExecStop=-/usr/bin/env sh -c '/usr/bin/env docker rm mash-freshrss 2>/dev/null || true'

Restart=always
RestartSec=30
SyslogIdentifier=mash-freshrss

[Install]
WantedBy=multi-user.target

```

**Comment by Alkarex** [comment]
Ah sorry, I forgot that `OIDC` has not landed in Alpine yet.
What I meant with platform is : x86-64, ARM64... ?
Could you try manually without systemd to see whether you can reproduce the problem?

**Comment by sidewinder94** [comment]
x86_64 here.

I can try, though with the same commands, i expect the result to stay the same.

I'll come back to you tomorrow on the result of that

**Comment by sidewinder94** [comment]
I think I found out the issue, in the systemd service file, there is an option on the container creation command line : `--cap-drop=ALL` which prevents the use of su (because it needs the setuid capability?).

If I do remove the option removing the capabilities, I can run the crontab expression properly

Could the container be started as user 33 (www-data) to not have the need to su into www-data ?

**Comment by sidewinder94** [comment]
So from my limited testing, the container needs the following capabilities to function as is :
- SETGID
- SETUID
- FOWNER
- CHOWN
