### ISSUE TITLE
Getting a blank page after sign in on the latest docker release[BUG]

### ISSUE THREAD

**Issue by Aevrin** [FreshRSS/FreshRSS#5970]
**Describe the bug**
When I go to the website, I get a sign in page, then after signing in, it get a blank page, most elements are missing in source.

**To Reproduce**
1. Go to 'my website'
2. Click on 'put in username/password'
3. Click 'Sign in'
4. See Blackness

**Expected behavior**
The normal freshrss interface

**Screenshots**

**Environment information (please complete the following information):**
- OS: docker-edge on Ubuntu 22.04.3
- Browser: Firefox and Chrome, latest for both
- FreshRSS version: 1.22.2-dev 
- Database version: sqlite
- PHP version: [e.g. PHP 7.4]
- Installation type: self hosted, docker-edge

**Additional context**
This happened with both users I have setup, one admin with no feeds, one limited with ~200 feeds.

To fix it I restored the prior version of /var/www/FreshRSS/lib/Minz/Extension.php
I shelled into the container, removed the old version, added the new version, all good now.

Docker log:
```
[Fri Dec 22 20:02:16.921423 2023] [php:error] [pid 44] [client -.-.-.-:0]
PHP Fatal error:  Uncaught Error: Typed property Minz_Extension::$user_configuration must not be accessed before initialization in /var/www/FreshRSS/lib/Minz/Extension.php:286
Stack trace:
#0 /var/www/FreshRSS/extensions/xExtension-AutoRefresh/extension.php(32): Minz_Extension->getUserConfigurationValue()
#1 /var/www/FreshRSS/extensions/xExtension-AutoRefresh/extension.php(14): AutoRefreshExtension->getRefreshRate()
#2 /var/www/FreshRSS/lib/Minz/ExtensionManager.php(374): AutoRefreshExtension->addVariables()
#3 /var/www/FreshRSS/lib/Minz/ExtensionManager.php(344): Minz_ExtensionManager::callOneToOne()
#4 /var/www/FreshRSS/app/views/helpers/javascript_vars.phtml(6): Minz_ExtensionManager::callHook()
#5 /var/www/FreshRSS/lib/Minz/View.php(93): include('...')
#6 /var/www/FreshRSS/lib/Minz/View.php(143): Minz_View->includeFile()
#7 /var/www/FreshRSS/app/layout/layout.phtml(20): Minz_View->renderHelper()
#8 /var/www/FreshRSS/lib/Minz/View.php(93): include('...')
#9 /var/www/FreshRSS/lib/Minz/View.php(106): Minz_View->includeFile()
#10 /var/www/FreshRSS/lib/Minz/View.php(73): Minz_View->buildLayout()
#11 /var/www/FreshRSS/lib/Minz/Dispatcher.php(59): Minz_View->build()
#12 /var/www/FreshRSS/lib/Minz/FrontController.php(61): Minz_Dispatcher->run()
#13 /var/www/FreshRSS/p/i/index.php(59): Minz_FrontController->run()
#14 {main}\n  thrown in /var/www/FreshRSS/lib/Minz/Extension.php on line 286
```

**Comment by Alkarex** [comment]
Should be fixed. Could you please try again?

**Comment by Aevrin** [comment]
Looks good, thanks.
