### ISSUE TITLE
[BUG] Error during git checkout to edge branch

### ISSUE THREAD

**Issue by wael-t** [FreshRSS/FreshRSS#5974]
**Describe the bug**
When I try to update through the GUI, I am getting this message: " The update process has encountered an error: Git error: Error during git checkout to edge branch. Please change branch manually! ❌"

**To Reproduce**
1. Go to my FreshRSS domain URL
2. Click on the settings gear
3. Scroll down to update and click on it
4. click on start update
5. I get this message: " The update process has encountered an error: Git error: Error during git checkout to edge branch. Please change branch manually! ❌" 

**Expected behavior**
A normal update to the app when I click on start update.

**Screenshots**
![Screenshot from 2023-12-25 16-48-25](https://github.com/FreshRSS/FreshRSS/assets/78669714/db9eae3a-c65c-4450-8c35-5e19bbe7fb21)

**Environment information (please complete the following information):**
- Device: Thinkpad X13 Gen4 AMD
- OS: Fedora 39
- Browser: Firefox 121.0
- FreshRSS version: 1.23.1-dev
- Database version: Postgres 14.10
- PHP version: PHP8.2
- Installation type: VPS Ubuntu 22, nginx.

**Comment by wael-t** [comment]
I tried the suggested solution in a similar issue #3665 reported in 20221, but when I execute the proposed git commands in the /FreshRSS I get `fatal: not a git repository (or any of the parent directories): .git`. 
I am quite sure when I installed it I used the git method!

**Comment by Alkarex** [comment]
@wael-t Go to your FreshRSS folder and type:

```sh
ls -alh
git status
```

If there is no `.git/` folder, it is probably that you installed through another method or that it was deleted. But this can be fixed :-)

```sh
cd ./FreshRSS/
git init
git remote add origin https://github.com/FreshRSS/FreshRSS.git
git fetch
git checkout -f -b edge origin/edge
git clean -f -d
```

and then you can resume your git operations:

```sh
git pull --ff-only
sudo cli/access-permissions.sh
```
