### ISSUE TITLE
[BUG] after update: not all unread entries displayed

### ISSUE THREAD

**Issue by ParoTheParrot** [FreshRSS/FreshRSS#5975]
After update to 1.23.0 I see only **one** unread article instead all!
This behavior is in  main view and in the catagories.

The bottom bar "mark as read" is missing (see screenshot).

Clicking on the unread article does **not** open the article, just marked an read.

**To Reproduce**
Steps to reproduce the behavior: install 1.23.0 ;-)

**Expected behavior**
All unread entries should be shown in the list.

**Screenshots**
See attachment 

**Environment information:**
- Device: iPhone, iPad 
- OS: newest ios 
- Browser: newest Firefox ios
- FreshRSS version: 1.23.0
- Database version: sqlite
- PHP version: 8.1.26

**Comment by ParoTheParrot** [comment]
![image](https://github.com/FreshRSS/FreshRSS/assets/5046600/25c4e03a-c941-485e-904b-4a925477d0f8)

**Comment by ParoTheParrot** [comment]
not all  feeds are effected. Some work nornal
<img width="896" alt="image" src="https://github.com/FreshRSS/FreshRSS/assets/5046600/fb384f27-c472-4a70-a737-1fa738bc521d">

Very strange behavior!

**Comment by squromiv** [comment]
Have the same problem. See some errors in console of browsers (Firefox and Chrome). 

![image](https://github.com/FreshRSS/FreshRSS/assets/15985877/f8d8a815-28a8-4f2a-b1ca-c91abb87039f)

![image](https://github.com/FreshRSS/FreshRSS/assets/15985877/3b639ea7-1fb9-4f5a-b8f0-bda1a3126d6e)

**Comment by TopoDiFogna** [comment]
> Have the same problem. See some errors in console of browsers (Firefox and Chrome).
> 
> ![image](https://private-user-images.githubusercontent.com/15985877/292778993-f8d8a815-28a8-4f2a-b1ca-c91abb87039f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MzkzOTgsIm5iZiI6MTcwMzUzOTA5OCwicGF0aCI6Ii8xNTk4NTg3Ny8yOTI3Nzg5OTMtZjhkOGE4MTUtMjhhOC00ZjJhLWIxY2EtYzkxYWJiODcwMzlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDIxMTgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhZDdiYzNjM2Q4NzEyOTc1ODlhNTBiY2EyYzM3OTA3YzliYjM2YjFjYWI3MWZkNTc0Y2FkMDQwMmUxMzMyNGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6AvWVmcqzjq4h9u1YC_Y5bFCLaW6E3jqMSI5RlWdLDg)
> 
> ![image](https://private-user-images.githubusercontent.com/15985877/292778854-3b639ea7-1fb9-4f5a-b8f0-bda1a3126d6e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MzkzOTgsIm5iZiI6MTcwMzUzOTA5OCwicGF0aCI6Ii8xNTk4NTg3Ny8yOTI3Nzg4NTQtM2I2MzllYTctMWZiOS00ZjVhLWI4ZjAtYmRhMWEzMTI2ZDZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDIxMTgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhZjQyMTZmNjYyOGVhMTMzMzA1ZDQzYWI0NTAxYjcyYjllZWZiN2E4NjMzMGY4NmI1MjQzNzgxZjNkOTU1MGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZrZph2E5jSq6nUEg1-CPVczRtdSIz5DU_w5fog-lyNw)

I have only the error in the second image

**Comment by Alkarex** [comment]
Could you please check your server-side logs (Web server logs, FreshRSS logs)?

**Comment by squromiv** [comment]
@Alkarex 
PHP 8.0

```
[26-Dec-2023] PHP Fatal error: 
Uncaught TypeError: array_slice(): Argument #3 ($length) must be of type ?int, string given in W:\domains\localhost\fresh\app\views\index\normal.phtml:89
Stack trace:
#0 W:\domains\localhost\fresh\app\views\index\normal.phtml(89): array_slice()
#1 W:\domains\localhost\fresh\lib\Minz\View.php(93): include('W:\\domains\\loca...')
#2 W:\domains\localhost\fresh\lib\Minz\View.php(115): Minz_View->includeFile()
#3 W:\domains\localhost\fresh\app\layout\layout.phtml(73): Minz_View->render()
#4 W:\domains\localhost\fresh\lib\Minz\View.php(93): include('W:\\domains\\loca...')
#5 W:\domains\localhost\fresh\lib\Minz\View.php(106): Minz_View->includeFile()
#6 W:\domains\localhost\fresh\lib\Minz\View.php(73): Minz_View->buildLayout()
#7 W:\domains\localhost\fresh\lib\Minz\Dispatcher.php(59): Minz_View->build()
#8 W:\domains\localhost\fresh\lib\Minz\FrontController.php(61): Minz_Dispatcher->run()
#9 W:\domains\localhost\fresh\p\i\index.php(59): Minz_FrontController->run()
#10 {main}
  thrown in W:\domains\localhost\fresh\app\views\index\normal.phtml on line 89
```

**Comment by Alkarex** [comment]
Thanks @squromiv 
Would you be able to try this patch? https://github.com/FreshRSS/FreshRSS/pull/5978

**Comment by squromiv** [comment]
> this patch? #5978

Have checked. It looks like the issue is gone now.

**Comment by Alkarex** [comment]
Great! Thanks for the feedback
