### ISSUE TITLE
[BUG] Not working after update to 1.23.0

### ISSUE THREAD

**Issue by gpl34** [FreshRSS/FreshRSS#5976]
**Describe the bug**
Blank page after update.

**Environment information (please complete the following information):**
- Device: Web
- Browser: Firefox 212
- FreshRSS version: 1.23.0
- PHP version: PHP 7.4
- Installation type: own

**Additional context**
Message in Apache error log: 

```
[Mon Dec 25 20:08:36.718115 2023] [php7:error] [pid 21386] [client xxxxxxx] PHP Fatal error: 
Uncaught TypeError: Argument 1 passed to Minz_ExtensionManager::enable() must be of the type string,
int given, called in /home/xxxxxxx/FreshRSS-master/lib/Minz/ExtensionManager.php on line 279
and defined in /home/xxxxxxx/FreshRSS-master/lib/Minz/ExtensionManager.php:248
Stack trace:
#0 /home/xxxxxxx/FreshRSS-master/lib/Minz/ExtensionManager.php(279): Minz_ExtensionManager::enable()
#1 /home/xxxxxxx/FreshRSS-master/app/FreshRSS.php(63): Minz_ExtensionManager::enableByList()
#2 /home/xxxxxxx/FreshRSS-master/p/i/index.php(57): FreshRSS->init()
#3 {main}\n  thrown in /home/xxxxxxx/FreshRSS-master/lib/Minz/ExtensionManager.php on line 248
```

**Comment by Alkarex** [comment]
Hello,
Could you please check your `./data/config.php`, and show the sections `extensions_enabled` and `extensions`?
It might be related to an old way of storing the list of enabled extensions.

**Comment by lapineige** [comment]
Referencing this : https://github.com/YunoHost-Apps/freshrss_ynh/pull/176#issuecomment-1869447901

Is there a way to fix that syntax then ?

**Comment by Alkarex** [comment]
Would you be able to try this patch? https://github.com/FreshRSS/FreshRSS/pull/5979

**Comment by lapineige** [comment]
It's working ! :tada:

**Comment by Alkarex** [comment]
@lapineige Super. Could you please check that your extensions are working?

**Comment by lapineige** [comment]
I'm trying it right now :)

**Comment by gpl34** [comment]
> Hello, Could you please check your `./data/config.php`, and show the sections `extensions_enabled` and `extensions`? It might be related to an old way of storing the list of enabled extensions.

Here it is:
```
  'extensions_enabled' => 
  array (
    'Tumblr-GDPR' => false,
  ),
  'extensions' => 
  array (
  ),
```

**Comment by gpl34** [comment]
> Would you be able to try this patch? #5979

It’s working!

Thank you.

**Comment by gramakri** [comment]
Cloudron package hit this as well - https://forum.cloudron.io/topic/10726/package-1-20-0-1-broke . 

@Alkarex so the fix will be in 1.23.1 ? Thanks!

**Comment by Alkarex** [comment]
@gramakri Yes, will be fixed in 1.23.1 very soon. I could not reproduce the same bug on my side though, so I would be interested in seeing a `data/config.php` and `data/users/someone/config.php` for someone facing the bug, in particular the sections `extensions_enabled` and `extensions`

**Comment by Alkarex** [comment]
@gramakri Do you have the possibility to test FreshRSS `edge` version before imminent release of 1.23.1?

**Comment by Alkarex** [comment]
@gramakri And you did not get more information, did you?

**Comment by gramakri** [comment]
@Alkarex I didn't face the issue myself but was reported by a user in our forum. But let me quickly check if I can reproduce this.

**Comment by gramakri** [comment]
I tried updating all the way from 1.22.0 and cannot reproduce it. But this was just an empty FreshRSS upgraded step by step. I am trying now with some extensions enabled.

**Comment by gramakri** [comment]
I tested with the built-in extensions enabled and it seems fine as well :thinking: . Maybe I need to install some custom extensions, let me try that too.

The extensions variables are just empty arrays with the built-in extensions it seems:

```
  'extensions_enabled' =>
  array (
  ),
  'extensions' =>
  array (
  ),

```

![image](https://github.com/FreshRSS/FreshRSS/assets/82041/6494c389-63e3-4f74-8bb6-28eae844d70f)

**Comment by gramakri** [comment]
@Alkarex I tried with Invidious extension. The config.json had below:

```
  'extensions_enabled' =>
  array (
    'Invidious Video Feed' => true,
  ),
  'extensions' =>
  array (
  ),
```

The update worked fine. If I am reading the fix correctly, somehow extensions_enabled has a non-string. I wonder who this can happen. I will ask the user in the forum as to what his config.php but I cannot reproduce this.

Edit: dont' know if it matters but in earlier version of FreshRSS, the extensions property was not there at all. But it appears only in the recent version.

**Comment by jacobkiers** [comment]
Hi, I have a many years old FreshRSS installation, and I hit this bug with the following excerpt from config.php:

```php
 'extensions_enabled' => 
  array (
    'Google-Groups' => true,
    'Tumblr-GDPR' => true,
    0 => 'Dilberts Daily Comic',
  ),
```

and in the user-specific config:

```php
  'extensions_enabled' => 
  array (
    0 => 'WallabagAPI',
  ),
```

**Comment by jacobkiers** [comment]
Manually going to the extensions page for my user, and re-enabling the WallabagAPI extension changes it into this:

```php
  'extensions_enabled' => 
  array (
    'WallabagAPI' => true,
  ),
```

I don't know how to do that for the global extensions in `/data/config.php` though.

**Comment by gramakri** [comment]
Ah, so @Alkarex maybe the 0 index is the source of the bug?

**Comment by Alkarex** [comment]
Thanks for the feedback and yes, that was the problem. We must have had some versions, which saved the array this way. I am not sure from which to which version, though.
