### ISSUE TITLE
[BUG] Blank Subscriptions page after update

### ISSUE THREAD

**Issue by vdbhb59** [FreshRSS/FreshRSS#5980]
**Describe the bug**
After update (manual via zip) to current version, the subscriptions page is not loading at all, and gives blank.

**To Reproduce**
1. Click on 'Subscriptions tab on the upper left side'
2. Page redirects
3. Loads blank page

**Expected behavior**
Subscriptions page should load with details of he subscriptions.

**Screenshots**
![image](https://github.com/FreshRSS/FreshRSS/assets/60728004/a0968ca8-3cef-49bf-86ee-4aa3f192074c)

**Environment information (please complete the following information):**
- Device: Laptop / Smartphone
- OS: Windows 11 / Zorin 17 / Android 13
- Browser: [Librewolf 121.0-1 / Mull 121.X]
- FreshRSS version: [1.23.0]
- Database version: [5.7.44 - MySQL Community Server (GPL)]
- PHP version: [PHP 8.1]
- Installation type: [e.g. cPanel Shared Hosting]

**Additional context**
Another BUG is also being raised of feed posts not loading beyond 24 hours time separately.
Extensions currently active are:
'TinyTinyRSS API' => true,
'Invidious Video Feed' => true,
'Black List' => false,
'RSS-Bridge' => true,
'Comics in feed' => false,

**Comment by Alkarex** [comment]
Could you please check your logs (Web server logs, FreshRSS logs)?

**Comment by vdbhb59** [comment]
> Could you please check your logs (Web server logs, FreshRSS logs)?

I checked, but there is no logs for this one at all. I even cleared all logs, all cache and re-did the steps before logging the bug here.
I am doing the steps once more.
Edit: Same result.

Edit: I removed all extensions, including the index file for it, and the subscriptions page is now loading. I had the previous extensions as well (1.22.1 & <), due to which this was happening. But not sure for which exact extensions though.

**Comment by squromiv** [comment]
@vdbhb59
Is there any info in browser console?

**Comment by vdbhb59** [comment]
> @vdbhb59 Is there any info in browser console?

Now that this is not happening, I cannot see any errors. I had cleared and closed out all tabs and cookies before retrying this issue. But this certainly was due to some extension which somehow seems is not compatible with the current version.

**Comment by Alkarex** [comment]
Closing for now. Please try with `edge` if you can. Let us know if you spot anything else

**Comment by exusiaiwei** [comment]
I have reproduced this issue, and fortunately, I found the extension that caused this error, it's "**Feed Priority Shortcut**"! 

If anyone else is facing the same issue, I hope this can help you.

**Comment by Alkarex** [comment]
Thanks @exusiaiwei 
Might be the same than https://github.com/aidistan/freshrss-extensions/issues/5
But if there is still a problem with the newest version of that extension, could you please post an issue on https://github.com/aidistan/freshrss-extensions/issues ?

**Comment by exusiaiwei** [comment]
My apologies @Alkarex 
My FreshRSS is deployed in Docker, making extensions upgrades rather troublesome, so I overlooked the fact that my Feed Priority Shortcut extension is still on version 1.0.2. According to the information you provided, the issue should have been fixed in the newer version of the extension. 
Anyway, if anyone else encounters this problem, updating this plugin should solve it.
