### ISSUE TITLE
[BUG] Feeds not loading beyond certain time (24 hours)

### ISSUE THREAD

**Issue by vdbhb59** [FreshRSS/FreshRSS#5981]
**Describe the bug**
The feeds / posts are not loading beyond the last 24 hours since update to 1.23.0

**To Reproduce**
1. Go to 'Home page/feed page'
2. Scroll down to 'show feeds / auto load'
3. See feeds not loading beyond 24 hours.

**Expected behavior**
Feeds always auto load upon scrolling down, all the time, till the end of scrolling.

**Screenshots**
![image](https://github.com/FreshRSS/FreshRSS/assets/60728004/995e93a8-89b2-4353-87c7-5b00eed38a10)

**Environment information (please complete the following information):**
- Device: Laptop / Smartphone
- OS: Windows 11 / Zorin 17 / Android 13
- Browser: [Librewolf 121.0-1 / Mull 121.X]
- FreshRSS version: [1.23.0]
- Database version: [5.7.44 - MySQL Community Server (GPL)]
- PHP version: [PHP 8.1]
- Installation type: [e.g. cPanel Shared Hosting]

**Additional context**
Extensions currently active are:
'TinyTinyRSS API' => true,
'Invidious Video Feed' => true,
'Black List' => false,
'RSS-Bridge' => true,
'Comics in feed' => false,

Logs give me this:
SQL error searchById|category|toGReader|include ["HY000",2014,"Cannot execute queries while other unbuffered queries are active. Consider using PDOStatement::fetchAll(). Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute."] 

More details: This is happening only in the following themes > Origine & Origine-Compact. No other theme is giving this error.

**Comment by Alkarex** [comment]
Hum, the `toGReader()` is not supposed to be called from this view. Could you please try to disable your FreshRSS extensions and compare?

**Comment by vdbhb59** [comment]
Without extensions it is working intermittently. I removed all extensions, even the only ones which are shown under compatible. Then it is not giving this issue every time, but otherwise it is back to same 24 hours stoppage. Also, it is happening mostly for those 2 themes Origine & Origine-Compact only with and without extensions.

**Comment by Alkarex** [comment]
Would you be able to add a debug line in the code?

Insert the following line between lines 106 and 107 (inside the `if`):

```php
Minz_Log::warning(json_encode(debug_backtrace(), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
```

of `./FreshRSS/app/Models/Feed.php`:

https://github.com/FreshRSS/FreshRSS/blob/e9689645383d37231afa9dbbcd9bd765b804046d/app/Models/Feed.php#L104-L110

Likely the same root problem than https://github.com/FreshRSS/FreshRSS/issues/5982

**Comment by Alkarex** [comment]
After the test above (I am interested in the logs, if possible), would you be able to try the `edge` version? I have made some changes, which might hopefully help https://github.com/FreshRSS/FreshRSS/pull/5986

**Comment by vdbhb59** [comment]
Answered on the other BUG topic.

**Comment by squromiv** [comment]
Faced to the issue with 1.23.1-dev. Firefox browser console:

![image](https://github.com/FreshRSS/FreshRSS/assets/15985877/0433fa09-3293-42dc-981f-a238316f510b)

PHP 8.0 log

> [28-Dec-2023 00:00:00] PHP Fatal error:  Uncaught TypeError: array_slice(): Argument #3 ($length) must be of type ?int, string given in server\app\views\index\normal.phtml:89
> 
> Stack trace:
> #0 server\app\views\index\normal.phtml(89): array_slice()
> #1 server\lib\Minz\View.php(93): include('W:\\domains\\loca...')
> #2 server\lib\Minz\View.php(115): Minz_View->includeFile()
> #3 server\app\layout\layout.phtml(73): Minz_View->render()
> #4 server\lib\Minz\View.php(93): include('W:\\domains\\loca...')
> #5 server\lib\Minz\View.php(106): Minz_View->includeFile()
> #6 server\lib\Minz\View.php(73): Minz_View->buildLayout()
> #7 server\lib\Minz\Dispatcher.php(59): Minz_View->build()
> #8 server\lib\Minz\FrontController.php(61): Minz_Dispatcher->run()
> #9 server\p\i\index.php(59): Minz_FrontController->run()
> #10 {main}
>   thrown in server\app\views\index\normal.phtml on line 89
>

**Comment by squromiv** [comment]
> to try the `edge` version

Have tried. It resolves the problem in my instance.

**Comment by vdbhb59** [comment]
This is solved for me with the edge yesterday and works on today's patch as well.

**Comment by Alkarex** [comment]
Thanks for the feedback :-)
