### ISSUE TITLE
[BUG] "Could not initialize random number generator" and/or "There are no articles to show."

### ISSUE THREAD

**Issue by juanbretti** [FreshRSS/FreshRSS#5985]
**Describe the bug**
Problems installing the application using `Docker`.

**To Reproduce**
Clean install.
Using a Synology NAS.
Using "Container Manager" (Docker containers manager)
* Getting the `freshrss/freshrss:latest` image
* Setting port 80 to a hostname
* Setting volumes:
  * `/volumen1/docker/freshrss/data:/var/www/FreshRSS/data:rw`
  * `/volumen1/docker/freshrss/extensions:/var/www/FreshRSS/extensions:rw`
* TZ: `Europe/Madrid`
* CRON_MIN: `*/20`

![image](https://github.com/FreshRSS/FreshRSS/assets/10165911/a16e478c-71d3-4d48-8039-caeb6aca8c8d)

Try to go to the application, but no response.
The Docker logs an error:
```log
[Wed Dec 27 12:10:26.880345 2023] [:crit] [pid 1] (38)Function not implemented: AH00141: Could not initialize random number generator
```
The Docker is not running, because it crashes after the previous error.

**Expected behavior**
The application should remain running. But it crashes/stops.

**Environment information:**
- Device: Synology DiskStation 7.2.1 Update 3
- Browser: Edge and Firefox, Windows
- FreshRSS version: Docker, `freshrss/freshrss:latest` and `freshrss/freshrss:alpine` 
- Database version: SQLlite
- Installation type: Docker

**Additional context**
Files are being generated on the storage.

![image](https://github.com/FreshRSS/FreshRSS/assets/10165911/04ff5f2b-b3a3-4fae-bb93-cc8ea0ce0a2b)

I tried the following solution: https://github.com/FreshRSS/FreshRSS/issues/4162. Using `freshrss/freshrss:alpine`.
But it does not work because of something different.

`freshrss/freshrss:alpine` does not work, because I do not get any entries.
The feeds are not updating at all.
Steps I can do:
* Go to the installed URL
* Set up a username and password.
* Set to use SQLlite database.
* Login into the application.
* I see the default feed from FreshRSS
But I got no entries. I got a message that says "There are no articles to show."
The statistics about the feed shows `-1` entries.

![image](https://github.com/FreshRSS/FreshRSS/assets/10165911/f68c6249-9c60-47dd-944e-1b50b15094d3)

The file `db.sqlite` is created inside the username folder. The DB contains the list of feeds.

Also tried the following https://github.com/FreshRSS/FreshRSS/issues/3100#issuecomment-657023419, and I get the response from `https://jointheteem.com/feed/`.
Using the code:
```sh
 sudo docker exec freshrss php -r "readfile('https://jointheteem.com/feed/');"
```

**Comment by Alkarex** [comment]
Hello,
Which Docker version do you run, and which Linux kernel?

Likely the same than:
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=978045
* https://github.com/docker-library/wordpress/issues/630#issuecomment-902044264

Options include:
* Update your Linux kernel
* Trying some older images. I actually maintain an [old Dockerfile](https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/Dockerfile-Oldest) for test purposes, which you might be able to use with our newest FreshRSS code:

```yml
  freshrss:
    image: freshrss/freshrss:oldest
    build:
      context: https://github.com/FreshRSS/FreshRSS.git#edge
      dockerfile: Docker/Dockerfile-Oldest
    ...
```

* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/freshrss/docker-compose.yml
* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md#build-custom-docker-image
