### ISSUE TITLE
[Feature] Disable unused PHP modules in Docker image

### ISSUE THREAD

**Issue by daberlin** [FreshRSS/FreshRSS#5993]
**Is your feature request related to a problem? Please describe.**
PHP in the Docker image loads several modules that are not needed and (1) consume memory and (2) enlarge the attack surface security-wise.

**Describe the solution you’d like**
```
RUN phpdismod calendar exif ftp gettext gmp iconv intl phar posix readline shmop sockets \
              sysvmsg sysvshm tokenizer xmlreader xmlwriter xsl

```

**Describe alternatives you’ve considered**
None

**Additional context**
None

**Comment by Frenzie** [comment]
I don't know about all of those but most of them are definitely needed. Strictly speaking some aren't needed in the sense that things will mostly work without but purposefully installing them and then disabling them is a bit backwards. ;-D And yes, I'm pretty sure we do indeed want to also install the optional ones like iconv.

https://github.com/FreshRSS/FreshRSS/blob/08345d0a95cf2435c24e3d40b196cd87aea46d0b/.devcontainer/Dockerfile#L6-L12

**Comment by Alkarex** [comment]
Debian version:

https://github.com/FreshRSS/FreshRSS/blob/2bd9f6303014f67537230d507416df7460817f7f/Docker/Dockerfile#L12-L13

Alpine version:

https://github.com/FreshRSS/FreshRSS/blob/2bd9f6303014f67537230d507416df7460817f7f/Docker/Dockerfile-Alpine#L9-L11


1) As Frenzie is writing already, I do not believe we install any package that we do not need;
2) but we might want to disable some extensions though (especially in Debian, which has more extensions enabled by default)

Concrete PR welcome so we can discuss the details

**Comment by Alkarex** [comment]
Please check https://github.com/FreshRSS/FreshRSS/pull/5994
