### ISSUE TITLE
[BUG] Backup restored, flux stopped

### ISSUE THREAD

**Issue by Machou** [FreshRSS/FreshRSS#6006]
**Describe the bug**

I restored a backup of FluxRSS, after my VM crashed, so I restarted my Docker and restored my feeds via the interface and now they don't refresh.

I don't know if it's a bug or if it's normal, but after some searching I couldn't find how to restart the update.

**Environment information (please complete the following information):**
- Device: PC
- OS: Debian 12
- Browser: Firefox 121
- FreshRSS version: 1.23.1
- Database version: Docker
- PHP version: Docker
- Installation type: Docker

**Comment by Alkarex** [comment]
Hello,
Anything in your logs (Web server, FreshRSS)?
What kind of archive are you restoring?
What do you mean by *they don't refresh*?

**Comment by Machou** [comment]
I've been looking for a solution since I posted my issue, and I just realized that I applied the wrong user rights (**chown**) and reversed 2 users during my restore.

I've just reapplied the good rights, re-installed FreshRSS, and it's working again.

_Sorry for the inconvenience, I'm an idiot sometimes._
