### ISSUE TITLE
[BUG]xExtension-Copy2Clipboard - Fatal error for version number

### ISSUE THREAD

**Issue by vdbhb59** [FreshRSS/FreshRSS#6015]
I am getting this error for xExtension-Copy2Clipboard:

```
Copy the destination links of all visible entries into clipboard
Fatal error: Uncaught TypeError: version_compare() expects parameter 2 to be string, float given in
/PATH/feeds/app/views/extension/index.phtml:64 Stack trace: #0
/PATH/feeds/app/views/extension/index.phtml(64): version_compare('0.4', 0.4) FreshRSS/Extensions#1
/PATH/feeds/lib/Minz/View.php(93): include('/home/USER1/...') FreshRSS/Extensions#2
/PATH/feeds/lib/Minz/View.php(115): Minz_View->includeFile('/views/extensio...') FreshRSS/Extensions#3
/PATH/feeds/app/layout/layout.phtml(73): Minz_View->render() FreshRSS/Extensions#4
/PATH/feeds/lib/Minz/View.php(93): include('/home/USER1...') FreshRSS/Extensions#5
/PATH/feeds/lib/Minz/View.php(106): Minz_View->includeFile('/layout/layout....') FreshRSS/Extensions#6
/PATH/feeds/lib/Minz/View.php(73): Minz_View->buildLayout() FreshRSS/Extensions#7
/PATH
/PATH/feeds/app/views/extension/index.phtml on line 64
```

Extension is downloaded from the provided one here: https://github.com/cn-tools/cntools_FreshRssExtensions/tree/master/xExtension-Copy2Clipboard

![image](https://github.com/FreshRSS/Extensions/assets/60728004/ae7ac13b-f428-4a39-babf-2259e4fefc27)

**Comment by Alkarex** [comment]
Thanks for the bug report.
Would you be able to test this patch? https://github.com/FreshRSS/FreshRSS/pull/6016
(Regression due to https://github.com/FreshRSS/FreshRSS/pull/5830)

**Comment by vdbhb59** [comment]
> Thanks for the bug report. Would you be able to test this patch? #6016 (Regression due to #5830)

Anytime. Give me few hours. Will test and revert.

**Comment by vdbhb59** [comment]
> Thanks for the bug report. Would you be able to test this patch? #6016 (Regression due to #5830)

Perfect solved the issue and also solved other installed + available extensions not showing up earlier.
Earlier under: Available community extensions
It would only show 4-5, now it shows all available as well as installed ones.
