### ISSUE TITLE
[BUG]Manual deletion of users via manage users, creates multiple entries of SQL table trying to find the user!

### ISSUE THREAD

**Issue by vdbhb59** [FreshRSS/FreshRSS#6024]
**Describe the bug**
Every time a user is manually removed via "Manage Users" screen, the logs has duplicate entry, at times even 3 or 4 similar entries, of trying to find the user in SQL table. I am not sure if this is a bug or what, but have seen this several times, so raising here.

**To Reproduce**
1. Go to 'dropdown configure'
2. Click on 'Manage Users'
3. Manually remove individual users
4. Navigate to GUI Logs section
5. See multiple entries of SQL trying to locate the user
6. At times the same entry is even 3 times, or 4 times too

**Expected behavior**
I am not sure if this is something that should happen, or if it even is a bug or not. But in my understanding, should it not be just trying to locate once and not 2, 3 or 4 times?

**Screenshots**

```
Log Level 	Timestamp 	Log Message
❌		2024-01-04 15:25:28 	SQL error count|retrieveUserDetails|manageAction|launchAction ["42S02",1146,"Table 'XX_XX.XX_screwball2023_entry' doesn't exist"]
❌		2024-01-04 15:25:22 	SQL error count|retrieveUserDetails|manageAction|launchAction ["42S02",1146,"Table 'XX_XX.XX_screwball2023_entry' doesn't exist"]
❌		2024-01-04 15:25:22 	SQL error count|retrieveUserDetails|manageAction|launchAction ["42S02",1146,"Table 'XX_XX.XX_samhans_entry' doesn't exist"]
❌		2024-01-04 15:24:41 	SQL error count|retrieveUserDetails|manageAction|launchAction ["42S02",1146,"Table 'XX_XX.XX_pmtnm_entry' doesn't exist"]
❌		2024-01-04 15:24:35 	SQL error count|retrieveUserDetails|manageAction|launchAction ["42S02",1146,"Table 'XX_XX.XX_pmtnm_entry' doesn't exist"]
❌		2024-01-04 15:24:35 	SQL error count|retrieveUserDetails|manageAction|launchAction ["42S02",1146,"Table 'XX_XX.XX_pi_entry' doesn't exist"]
❌		2024-01-04 15:24:19 	SQL error count|retrieveUserDetails|manageAction|launchAction ["42S02",1146,"Table 'XX_XX.XX_moooni_entry' doesn't exist"]
❌		2024-01-04 15:24:19 	SQL error count|retrieveUserDetails|manageAction|launchAction ["42S02",1146,"Table 'XX_XX.XX_mooni_entry' doesn't exist"]
❌		2024-01-04 15:24:19 	SQL error count|retrieveUserDetails|manageAction|launchAction ["42S02",1146,"Table 'XX_XX.XX_moooni_entry' doesn't exist"]
❌		2024-01-04 15:23:24 	SQL error count|retrieveUserDetails|manageAction|launchAction ["42S02",1146,"Table 'XX_XX.XX_lza_entry' doesn't exist"]
❌		2024-01-04 15:23:23 	SQL error count|retrieveUserDetails|manageAction|launchAction ["42S02",1146,"Table 'XX_XX.XX_lza_entry' doesn't exist"]
❌		2024-01-04 15:23:23 	SQL error count|retrieveUserDetails|manageAction|launchAction ["42S02",1146,"Table 'XX_XX.XX_lza_entry' doesn't exist"]
❌		2024-01-04 15:23:22 	SQL error count|retrieveUserDetails|manageAction|launchAction ["42S02",1146,"Table 'XX_XX.XX_honestly_entry' doesn't exist"]
❌		2024-01-04 15:23:22 	SQL error count|retrieveUserDetails|manageAction|launchAction ["42S02",1146,"Table 'XX_XX.XX_honestly_entry' doesn't exist"]
❌		2024-01-04 15:23:21 	SQL error count|retrieveUserDetails|manageAction|launchAction ["42S02",1146,"Table 'XX_XX.XX_blondjesus_entry' doesn't exist"] 
```
![image](https://github.com/FreshRSS/FreshRSS/assets/60728004/1fc10d83-5bc0-4e2e-ab4b-9eeac8ef519e)

**Environment information (please complete the following information):**
- Device: Agnostic
- OS: Agnostic
- Browser: Agnostic
- FreshRSS version: Agnostic, but I took notice only from > 1.20.0 onward and it is ongoing till date
- Database version: MySQL 5.7.44
- PHP version: PHP 7.4 / 8.0.X / 8.1.0
- Installation type: ZIP / Manual / Git

**Additional context**
Again, I am not sure if this is a FRSS bug or MySQL bug, or even if a BUG, but I thought, it should be raised to make aware of.

**Comment by Alkarex** [comment]
Hello,
A first thought is that those users have been deleted, but not completely, maybe due to access rights.
Could you check whether they still exist in `./FreshRSS/data/users/` and what the content of those folders are, along with access permissions?

**Comment by vdbhb59** [comment]
So, I cross checked, and can see that the /data/users/ folders are not present for any removed user.
I am just not sure if this indeed is a bug or indeed is not what is expected in reality from MySQL or FRSS. :confused:

**Comment by math-GH** [comment]
Could you please check your `php_error_log`? And are you able to test the current `edge`? In the last days there were some bugs fixed around user deleting

**Comment by vdbhb59** [comment]
I no longer run the instance nor use FRSS. Rather no RSS anymore. Maybe close this or ask someone to run a regression?
