### ISSUE TITLE
Rendre le mode lecture plus fonctionnel

### ISSUE THREAD

**Issue by qwertygc** [FreshRSS/FreshRSS#603]
Bonjour,
Comment marquer "comme lu" en mode lecture, afin d'avoir un truc qui ressemble à Leed ?
Cordialement,

**Comment by aledeg** [comment]
Il n'y a pas de moyen visuel de voir qu'un article est lu. Cependant, le raccourci fonctionne correctement.
Une fois la page rafraîchie, l'article n'est plus là. Il faudrait ajouter une règle qui le fait disparaître de la page.

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/issues/1400
https://github.com/FreshRSS/FreshRSS/issues/1545

**Comment by Alkarex** [comment]
Implémenté dans FreshRSS 1.10.0 :-)
