### ISSUE TITLE
[BUG] filfre (The Digital Antiquarian) RSS is not working

### ISSUE THREAD

**Issue by lucamanga** [FreshRSS/FreshRSS#6032]
**Describe the bug**
FreshRSS is unable to download articles of the feed from https://www.filfre.net/feed/

**Comment by Frenzie** [comment]
I can't confirm. What does the error log say precisely? Also check with curl from your server.

![image](https://github.com/FreshRSS/FreshRSS/assets/202757/46de8cb9-7243-40c0-a724-447a1e327d3a)

**Comment by Alkarex** [comment]
Note for later: we should write a doc about how to debug a non-working feed

**Comment by Frenzie** [comment]
"Put Sushi in the sink and turn on the garbage disposal to test if the feed is functional."

**Comment by Frenzie** [comment]
(Zak McKracken in-joke; @lucamanga will get it ;-)

**Comment by math-GH** [comment]
Let's start with the basics:

Which FreshRSS version do you use?
Any log entries that could be useful here?

**Comment by lucamanga** [comment]
Hello and sorry for my late.

I'm using the FreeRSS hosted here: https://feeds.flossboxin.org.in

and I added / removed the feed yesterday multiple times, it was not working (it was not pulling the articles, neither after 20 minutes).

Today I tried it again and it worked instantly! Yaaaah!

Sorry for the mess.
