### ISSUE TITLE
Last-Modified, If-Modified-Since, and cache handling behaviors

### ISSUE THREAD

**Issue by cbiffle** [FreshRSS/FreshRSS#6056]
Hi! I am not a FreshRSS user, but I operate a website and appear to have many readers using FreshRSS, at least judging by user-agent. (Good for you! People seem to like it.)

I've noticed a couple of properties of at least _some_ of these users and wanted to ask some questions to help clarify my understanding of what's going on.

The requests are tending to miss cache (return a 200 rather than a 304 on my side). This is the only reason they came to my attention -- because some users are transferring 4 MiB of unmodified RSS XML per day. I enabled more logging for some of the heavier users and what I'm seeing is

- Their connections don't seem to be doing ETag at all (i.e. they are never sending the `if-none-match` header), and
- While they are sending `if-modified-since`, the date they're sending in the header appears arbitrary.

For context, my webserver implements `if-modified-since` using exact match -- so if the date sent in `if-modified-since` is the one I last handed out in `last-modified`, we get a 304, otherwise it's a 200. (This behavior is explicitly permitted in the HTTP spec, and all browsers I've tested conform to it.)

The dates I'm getting from connections claiming to be FreshRSS appear arbitrary and aren't related to my `last-modified` dates, which is causing the 200. They're always within a few days of my date, but are never a date I would have sent.

Concrete example: my RSS feed is currently sending the `last-modified` date of `Thu, 18 Jan 2024 19:24:29 GMT`. Before that it was modified on `13 Jan`. However, the date I'm getting from a user identified as `FreshRSS/1.23.1` is `Mon, 15 Jan 2024 18:31:01 GMT`, which is a date I never would have sent -- and a date that is older than the current modification date. This user has been doing this hourly for the past day or so.

I read through your code, and it looks like you're trying to record modification dates per-resource and send them with requests (particularly SimplePie seems to go to some effort to do this). This is good! I wonder if some versions of this might have a bug, or if some users might have configuration issues that cause the wrong date to be sent?

I'm not entirely sure what to do about these users, since even if I patched the server to not require exact date match, they are still sending dates in the past as though their cache is pulling the wrong dates.

Anyway, thanks in advance for any insights you can offer.

**Comment by Alkarex** [comment]
Hello and thank for the heads up.
Yes, the intention is to support HTTP conditional requests, also when using an exact match of the `If-Modified-Since`.
Let me try to do a bit of debugging there.
And kudos for using HTTP conditional requests on your side (it is quite rare for RSS feeds)

**Comment by cbiffle** [comment]
>  And kudos for using HTTP conditional requests on your side (it is quite rare for RSS feeds)

Well, thank you for sending them! I'm surprised to hear that a lot of RSS feeds don't handle them properly, but that might explain why I've had to reach out to several RSS readers about their implementations!

Let me know if I can do anything to help (e.g. turning on more request logging, tweaking settings).

Also, thank you for using `accept-encoding`, it reduces the bandwidth cost of these cache misses by 93% (since you're using brotli). Many RSS readers do not.

**Comment by Frenzie** [comment]
> And kudos for using HTTP conditional requests on your side (it is quite rare for RSS feeds)

Is it? :-) Any Wordpress feed returns 304 (or should) for if-modified-since equal to or higher than last-modified. Some quick testing suggests the same for various non-Wordpress feeds as well, including several of your fashionable statically generated feeds served by nginx. In fact I wasn't able to find any that didn't do it in my sampling; even the rss-bridge feeds I tried do.

**Comment by Alkarex** [comment]
Ah, thanks for the examples, @Frenzie , I am glad to read that. I could just remember (several years ago) when I last looked at it, that there was a low percentage in my own feeds.

**Comment by Alkarex** [comment]
A quick test on my own statically served RSS feed (Apache) does seem to properly return a 304:

```
alexandre.alapetite.fr 172.20.0.5 - - [23/Jan/2024:22:37:09 +0000] "GET /blog/rss.rdf.fr.xml HTTP/1.1" 304 360 "https://alexandre.alapetite.fr/blog/rss.rdf.fr.xml" "FreshRSS/1.23.2-dev (Linux; https://freshrss.org)" 1542us
```

And from FreshRSS side, I have just modified the logs and refreshed against a list of test feeds, for which it seems to work fine:

```
GET 304 http://blog.idleman.fr/feed/
GET 304 http://faire-ca-soi-meme.fr/feed/
GET 304 http://intertwingly.net/blog/index.atom
GET 304 http://www.imaygine.com/feed/
GET 304 https://alexandre.alapetite.fr/blog/rss.rdf.en.xml
GET 304 https://alexandre.alapetite.fr/blog/rss.rdf.fr.xml
GET 304 https://bits.debian.org/feeds/atom.xml
GET 304 https://blog.mozilla.org/en/feed/
GET 304 https://blog.ouseful.info/feed/
GET 304 https://blog.seboss666.info/feed/
GET 304 https://blog.zanorg.com/rss/fil_rss.xml
GET 304 https://blogs.windows.com/msedgedev/feed/
GET 304 https://blogs.windows.com/windowsexperience/feed/
GET 304 https://danq.me/feed/?kind=article
GET 304 https://derflounder.wordpress.com/feed/
GET 304 https://devblogs.microsoft.com/dotnet/feed/
GET 304 https://feed.ctrl.blog/latest.atom
GET 304 https://feedpress.me/frandroid
GET 304 https://fransdejonge.com/feed/
GET 304 https://gate21.dk/feed/atom/
GET 304 https://github.com/Alkarex.atom
GET 304 https://github.com/FreshRSS/FreshRSS/releases.atom
GET 304 https://github.com/WebBluetoothCG/web-bluetooth/commits/gh-pages.atom
GET 304 https://github.com/lwthiker/curl-impersonate/releases.atom
GET 304 https://gizmodo.com/rss
GET 304 https://gts-net.dk/feed/
GET 304 https://hacks.mozilla.org/feed/atom/
GET 304 https://ing.dk/rss
GET 304 https://korben.info/feed
GET 304 https://learn.microsoft.com/en-us/archive/blogs/sysinternals/feed.xml
GET 304 https://lord.re/index.xml
GET 304 https://menace-theoriste.fr/feed/
GET 304 https://mes-questions-reponses.nathan.fr/feed/
GET 304 https://rss.sciencedirect.com/publication/science/10715819
GET 304 https://techcrunch.com/feed/
GET 304 https://www.01net.com/feed/
GET 304 https://www.bortzmeyer.org/feed.atom
GET 304 https://www.cert.ssi.gouv.fr/feed/
GET 304 https://www.clubic.com/articles.rss
GET 304 https://www.commitstrip.com/fr/feed/
GET 304 https://www.factcheck.org/feed/
GET 304 https://www.filfre.net/feed/
GET 304 https://www.francetvinfo.fr/vrai-ou-fake.atom
GET 304 https://www.futura-sciences.com/rss/actualites.xml
GET 304 https://www.hinnerup.net/feed/rdf/
GET 304 https://www.journalduhacker.net/rss
GET 304 https://www.lalanguefrancaise.com/flux.rss
GET 304 https://www.maitre-eolas.fr/feed/atom
GET 304 https://www.oxfamfrance.org/feed/
GET 304 https://www.presse-citron.net/feed/
GET 304 https://www.rockmadeinfrance.com/feed/
GET 304 https://www.standblog.org/blog/feed/atom
GET 304 https://www.theverge.com/rss/index.xml
GET 304 https://www.trackawesomelist.com/rss.xml
GET 304 https://xkcd.com/atom.xml
```

So all seems good.

@cbiffle Could you provide a test feed I could add to my FreshRSS instance? And what is the full user-agent of the problematic FreshRSS clients?

**Comment by Alkarex** [comment]
P.S. Edited with a few more feeds, including @Frenzie 's :-)

**Comment by cbiffle** [comment]
> @cbiffle Could you provide a test feed I could add to my FreshRSS instance?

https://cliffle.com/rss.xml is the feed where I noticed this behavior. It is not served by Apache and its behavior will differ somewhat -- the server expects exact-match, whereas Apache will parse dates and compare.

> And what is the full user-agent of the problematic FreshRSS clients?

`FreshRSS/1.23.1 (Linux; https://freshrss.org)` is the full text of the one I'm monitoring.

Weirdly, this client is also sending `referer` of the feed URL itself -- the same URL it's fetching repeatedly.

**Comment by cbiffle** [comment]
In case this is helpful, here is a log extract of three requests _claiming to be_ FreshRSS today. These are all from an IP address I've marked for more detailed logging.

```
GET, cid: 513, rid: 0, uri: https://cliffle.com/rss.xml, version: HTTP/2.0, user-agent: "FreshRSS/1.23.1 (Linux; https://freshrss.org)", referrer: "https://cliffle.com/rss.xml", accept-encoding: "deflate, gzip, br, zstd", if-modified-since: "Mon, 15 Jan 2024 18:31:01 GMT"
GET, cid: 525, rid: 0, uri: https://cliffle.com/rss.xml, version: HTTP/2.0, user-agent: "FreshRSS/1.23.1 (Linux; https://freshrss.org)", referrer: "https://cliffle.com/rss.xml", accept-encoding: "deflate, gzip, br, zstd", if-modified-since: "Mon, 15 Jan 2024 18:31:01 GMT"
GET, cid: 537, rid: 0, uri: https://cliffle.com/rss.xml, version: HTTP/2.0, user-agent: "FreshRSS/1.23.1 (Linux; https://freshrss.org)", referrer: "https://cliffle.com/rss.xml", accept-encoding: "deflate, gzip, br, zstd", if-modified-since: "Mon, 15 Jan 2024 18:31:01 GMT"
```

Things to note there:
- Each request gets a copy of `rss.xml` with a `Mon 18 Jan ...` `last-modified` date (you can test it yourself by loading it from my server, if you like)
- And yet, it keeps calling back with this `15 Jan` date. Not only is this a date I've never sent, it's also three days older than the content I'm serving. So even on Apache, the content would get re-served.
- There is no `if-none-match` header for an ETag, which would also probably fix the issue if implemented.
- There's the odd referer I mentioned too.

At this point, I almost expect this to turn out to be a single user who's accidentally set their filesystem read-only or something, since it sounds like FreshRSS in general is _trying_ to do the correct thing here.

**Comment by Alkarex** [comment]
So I have put your feed in my instance and let it run. It seems to properly get 304s:

```
2024-01-24T00:44:39.126731717Z FreshRSS[42]: SimplePie GET 200 https://cliffle.com/rss.xml
2024-01-24T01:06:24.707314226Z FreshRSS[453]: SimplePie GET 304 https://cliffle.com/rss.xml
2024-01-24T01:36:29.583724169Z FreshRSS[632]: SimplePie GET 304 https://cliffle.com/rss.xml
2024-01-24T02:07:35.782000612Z FreshRSS[831]: SimplePie GET 304 https://cliffle.com/rss.xml
2024-01-24T02:36:17.761245303Z FreshRSS[1047]: SimplePie GET 304 https://cliffle.com/rss.xml
2024-01-24T03:06:47.580212258Z FreshRSS[1218]: SimplePie GET 304 https://cliffle.com/rss.xml
2024-01-24T03:36:17.133037007Z FreshRSS[1435]: SimplePie GET 304 https://cliffle.com/rss.xml
2024-01-24T04:06:32.163615314Z FreshRSS[1617]: SimplePie GET 304 https://cliffle.com/rss.xml
2024-01-24T04:36:44.301542428Z FreshRSS[1809]: SimplePie GET 304 https://cliffle.com/rss.xml
2024-01-24T05:06:20.544071640Z FreshRSS[2005]: SimplePie GET 304 https://cliffle.com/rss.xml
2024-01-24T05:37:13.076165803Z FreshRSS[2200]: SimplePie GET 304 https://cliffle.com/rss.xml
2024-01-24T06:06:24.850738102Z FreshRSS[2470]: SimplePie GET 304 https://cliffle.com/rss.xml
2024-01-24T06:36:39.227737779Z FreshRSS[2650]: SimplePie GET 304 https://cliffle.com/rss.xml
2024-01-24T07:06:50.767960727Z FreshRSS[2820]: SimplePie GET 304 https://cliffle.com/rss.xml
2024-01-24T07:36:48.074684085Z FreshRSS[3035]: SimplePie GET 304 https://cliffle.com/rss.xml
2024-01-24T08:06:31.122027895Z FreshRSS[3232]: SimplePie GET 304 https://cliffle.com/rss.xml
2024-01-24T08:36:20.992533048Z FreshRSS[3425]: SimplePie GET 304 https://cliffle.com/rss.xml
2024-01-24T09:07:27.438666747Z FreshRSS[3612]: SimplePie GET 304 https://cliffle.com/rss.xml
```

If the problem is limited to a single IP, maybe you could try to compare with some of the known multi-user instances https://freshrss.org/cloud-providers.html and/or try to get more info with a `whois`. You could even consider serving a custom RSS feed to that IP with message asking for a contact :-)

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/6061

**Comment by cbiffle** [comment]
Alright, thank you for testing -- I will assume these are users with either a misconfiguration, an old version, or software that is pretending to be FreshRSS.

> You could even consider serving a custom RSS feed to that IP with message asking for a contact :-)

This is my plan, actually -- advise users that I'm seeing something weird and ask them to drop me a line.

**Comment by Alkarex** [comment]
One explanation might be an instance, which is very frequently deleting the cache.
Related discussion https://github.com/FreshRSS/FreshRSS/issues/5913

**Comment by cbiffle** [comment]
Could be, particularly if FreshRSS sends a cache-wide "last modified" date. (If the cache were cleared, I would normally expect _no_ last-modified date.)

**Comment by Alkarex** [comment]
> Could be, particularly if FreshRSS sends a cache-wide "last modified" date. (If the cache were cleared, I would normally expect _no_ last-modified date.)

Indeed, I do not believe we ever send a self-constructed `If-Modified-Since`, so it should be blank.

**Comment by cbiffle** [comment]
So that's interesting, since the date I'm receiving doesn't match any date I ever transmitted -- it's being constructed by _something_ on the user's side. I am beginning to wonder if this user is spoofing your user-agent.

Thanks for the additional info.

**Comment by Frenzie** [comment]
Would it be possible for something like an nginx reverse proxy to mess that up somehow?

I'm thinking broadly of something like described in https://github.com/FreshRSS/FreshRSS/tree/86631d24b9b41e35cd915d253a2040bdb8dbbfba/Docker#alternative-reverse-proxy-using-nginx but with different (incorrect) configuration.

**Comment by Alkarex** [comment]
> Would it be possible for something like an nginx reverse proxy to mess that up somehow?

As it is related to outgoing requests, I do not think it is likely, but maybe.

**Comment by cbiffle** [comment]
It's certainly possible -- if you configure nginx badly enough, it can do _anything_ -- but I agree with @Alkarex that I'm not sure how likely it is. I'll just plan on handling this user like any other high-bandwidth user, by inserting a note in their feed. If they reach out, maybe we can find out how they've configured things!

**Comment by Frenzie** [comment]
I certainly agree it's very unlikely — I'm just at a loss to explain it. In any case I haven't seen any suspicious if-modified-since values either.

**Comment by cbiffle** [comment]
Hm. FWIW, I've had another user appear reporting the same FreshRSS UA string (1.23.1) and sending similarly weird requests. From the IPv4 info this one appears to be an individual user in Switzerland. I've tagged their IP block for more detailed logging and will let you know if anything useful appears, but, this does not seem to be a _totally_ isolated incident.
