### ISSUE TITLE
[BUG] Categories disappeared from left bar after upgrade

### ISSUE THREAD

**Issue by sarmong** [FreshRSS/FreshRSS#6057]
I just updated the version from 1.18.1 to 1.23.1 and there is no more categories on the left.

![image](https://github.com/FreshRSS/FreshRSS/assets/42828375/f2b0ba93-82a7-4898-ac1c-2c3bde4de294)

**Comment by sarmong** [comment]
![image](https://github.com/FreshRSS/FreshRSS/assets/42828375/23171d14-b098-4d25-861f-e36aa7c3ea4d)

**Comment by Alkarex** [comment]
Hello,
What database are you using?
Could you try to perform other operations such as refreshing a feed or adding a feed? (this should trigger an auto-update of the database)

**Comment by joshuabach** [comment]
I had the same problem, also after updating from 1.18 to 1.23. Same message in the log also. 

Fixed it by clicking "Update feeds" in the top bar, then everything was back to normal.

**Comment by neobrain** [comment]
Updating from 1.18.1 to 1.27.1, I ran into the same issue with a similar (though different) error message. Clicking `Update feeds` did not help.

Instead, I had to manually alter the SQLite database to add a missing `kind` column to the `feed` table. If anyone's coming across this, here are the operations I executed after opening db.sqlite in `sqlite3` (obviously create a backup of the file first):
```
CREATE TABLE `feed_new` (
    `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    `url` VARCHAR(32768) NOT NULL,
    `kind` SMALLINT DEFAULT 0, -- 1.20.0
    `category` SMALLINT DEFAULT 0, -- 1.20.0
    `name` VARCHAR(191) NOT NULL,
    `website` VARCHAR(32768),
    `description` TEXT,
    `lastUpdate` INT(11) DEFAULT 0,
    `priority` TINYINT(2) NOT NULL DEFAULT 10,
    `pathEntries` VARCHAR(4096) DEFAULT NULL,
    `httpAuth` VARCHAR(1024) DEFAULT NULL,
    `error` BOOLEAN DEFAULT 0,
    `ttl` INT NOT NULL DEFAULT 0,
    `attributes` TEXT, -- 1.11.0
    `cache_nbEntries` INT DEFAULT 0,
    `cache_nbUnreads` INT DEFAULT 0,
    FOREIGN KEY (`category`) REFERENCES `category`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    UNIQUE (`url`)
);

INSERT INTO `feed_new` (
    `id`, `url`, `kind`, `category`, `name`, `website`, `description`,
    `lastUpdate`, `priority`, `pathEntries`, `httpAuth`, `error`, `ttl`,
    `attributes`, `cache_nbEntries`, `cache_nbUnreads`
)
SELECT
    `id`, `url`, 0 AS `kind`, `category`, `name`, `website`, `description`,
    `lastUpdate`, `priority`, `pathEntries`, `httpAuth`, `error`, `ttl`,
    `attributes`, `cache_nbEntries`, `cache_nbUnreads`
FROM `feed`;

DROP TABLE `feed`;
ALTER TABLE `feed_new` RENAME TO `feed`;
```

That made the categories show up again, but each feed would display an error icon. To fix *that*, I had to go through each feed *individually* and update them by selecting "Update feeds" in the menu opened by clicking the gear icon in the left bar. ("Update feeds" from the *top bar* did not work!).

**Comment by Alkarex** [comment]
@neobrain This has been fixed in https://github.com/FreshRSS/FreshRSS/pull/8148
Just making any change to any feed would have been sufficient to trigger an auto-update of that field. But good that you found a solution anyway :-)

P.S.: Alternatively, for people coming from even older versions, an export and import is also a good possibility.
* https://freshrss.github.io/FreshRSS/en/admins/05_Backup.html (using `./cli/db-restore.php` or `./cli/import-sqlite-for-user.php`)

**Comment by Alkarex** [comment]
@neobrain Looking at your manual changes, it does not look like you have recreated the indexes (I am not sure whether they are persisted from the old table or dropped), so the performance risk to suffer.

I suggest you run `./cli/export-sqlite-for-user.php` and then either use the output as your new SQLite file or run `./cli/import-sqlite-for-user.php`

**Comment by neobrain** [comment]
> This has been fixed in https://github.com/FreshRSS/FreshRSS/pull/8148
> Just making any change to any feed would have been sufficient to trigger an auto-update of that field. But good that you found a solution anyway :-)

Ah, even better then. At least it was a fun exercise :)

Since you mentioned potential problems, I restored the database from my pre-update backup and cherry-picked your linked patch into 1.27.1. Indeed that fixed all problems without any manual intervention required.

Thanks for the pointers and for working on such a cool and useful project!
