### ISSUE TITLE
[BUG] Updating the "ungategorized" Category deletes the title

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#6071]
**Describe the bug**
Edit the `uncategorized` category, save it and the title will be empty

**To Reproduce**
Edit the `uncategorized` category
![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/b4ee1407-e96b-4dc9-a9c6-561f8adb6bf5)

Click the submit button
![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/baab1fe7-7dfd-4442-844c-97f441fbca60)

The category title is now empty
![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/f0a8eb4d-468e-46e7-81f9-bf3753686ac3)

![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/bc8acdce-eba0-46ce-a49b-fd0fd5b2a0a4)

**Expected behavior**
The title of the uncategoried categorie will keept untouched.

**Environment information (please complete the following information):**
- FreshRSS version: 1.23.2-dev (reproduceable on demo.freshrss.org)

**Additional context**
The field `name` is `disabled` that will submit an empty string that will saved as empty title

**Comment by Alkarex** [comment]
Tests welcome https://github.com/FreshRSS/FreshRSS/pull/6073
