### ISSUE TITLE
Marquer une recherche comme lue

### ISSUE THREAD

**Issue by juzam51** [FreshRSS/FreshRSS#608]
Bonjour,

Quand je fais une recherche sur un terme particulier, freshrss m'affiche les articles non lus. 
Jusque là tout va bien.
Par contre, quand je veux les marquer commu lu, il me marque tous les flux comme lu et pas juste les articles de ma recherche.

Est-ce un comportement normal ?

**Comment by Alkarex** [comment]
Corrigé (enfin !) dans https://github.com/FreshRSS/FreshRSS/pull/1218
