### ISSUE TITLE
[BUG] Chronological order not respected

### ISSUE THREAD

**Issue by GrosMatou27** [FreshRSS/FreshRSS#6080]
New freshRSS installation with a "one-click install" on Infomaniak

The chronological order is not respected, and I can't understand the logic followed (see example)

![image](https://github.com/FreshRSS/FreshRSS/assets/138433289/73133e1f-e1c4-4c64-ba08-cb083840bae2)

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/discussions/5865

**Comment by GrosMatou27** [comment]
Thanks.
Sorry I didn't notice that on my old installation.
