### ISSUE TITLE
[BUG] User Queries settings page hangs if recursive query added

### ISSUE THREAD

**Issue by jonsmy** [FreshRSS/FreshRSS#6086]
**Describe the bug**
The user queries settings page will hang if the user adds a recursive user query.

**To Reproduce**
1. Add a user queries. The offending query only used `intitle`
2. Add a second user query that uses the previously created user query. i.e: `search:"Query A"`
3. The user queries page should now hang and prevent the user from editing or removing any user queries.

**Environment information (please complete the following information):**
- FreshRSS version: 1.22.1 (also tested on 1.23.1)
- Database version: SQLite 3.34.1
- PHP version: 8.3
- Installation type: Manual

**Additional context**
Manually editing the user's `config.php` to remove the recursive user query will fix the problem

**Comment by Alkarex** [comment]
I will try to fix as part of https://github.com/FreshRSS/FreshRSS/pull/6052

**Comment by Alkarex** [comment]
Tests welcome of https://github.com/FreshRSS/FreshRSS/pull/6052
