### ISSUE TITLE
[BUG] FreshRSS doesn't automatically update the feeds anymore

### ISSUE THREAD

**Issue by oliversum-ch** [FreshRSS/FreshRSS#6089]
**Describe the bug**
FreshRSS has worked very well for more than 18 months. But within the last few days, it didn't automatically update the feeds anymore, although I didn't change anything. 
I'm executing actualize_script.php every 20 minutes using my hoster's cronjobs. 

The cronjobs seem to work, I get results as the one below:

> FreshRSS starting feeds actualization at 2024-02-03T06:00:14+00:00
> FreshRSS actualize myfreshrssusername…
> PHP Notice: A feed could not be found at `http://domain.com/index.php?format=feed&type=rss`; the status code is `200` and content-type is `text/html; charset=utf-8` in /home/sites/hiddenpath/public_html/freshrss/lib/SimplePie/SimplePie.php on line 1829
> PHP Notice: A feed could not be found at `https://domain.co.uk/feed/`; the status code is `200` and content-type is `text/html` in /home/sites/hiddenpath/public_html/freshrss/lib/SimplePie/SimplePie.php on line 1829
> PHP Notice: A feed could not be found at `https://blog.domain.de/feed/`; the status code is `200` and content-type is `text/html;charset=UTF-8` in /home/sites/hiddenpath/public_html/freshrss/lib/SimplePie/SimplePie.php on line 1829

However, I don't see the latest posts anymore, unless I manually refresh the feeds:
![image](https://github.com/FreshRSS/FreshRSS/assets/75724465/54cf8104-ddc3-410e-b15e-c5c8a276b820)

I already checked the user-related, system-related, and application logs, but there are no new entries.

I have no idea what else I could check. Does anyone have any input? Thanks a lot!

**Environment information (please complete the following information):**
- Device: PC
- OS: Windows 11
- Browser: Chrome 121.0.6167.87 (Official Build) (64-bit)
- FreshRSS version: 1.23.1
- Database version: MySQL, but I don't know the version
- PHP version: PHP 7.4.33 and 8.1, I tested both
- Installation type: Shared hosting

**Comment by math-GH** [comment]
Are there any log entries?
Have you contacted your shared hoster? Maybe there is a known issue with the crons.

**Comment by oliversum-ch** [comment]
Thanks for your reply!

The system related log file is empty, in the user related log file are some warnings:

> [Fri, 02 Feb 2024 11:21:07 +0000] [warning] --- cURL error 22: The requested URL returned error: 429 [https://feeds.feedburner.com/blogname]
> [Fri, 02 Feb 2024 11:21:07 +0000] [warning] --- cURL error 22: The requested URL returned error: 429 [http://feeds.feedburner.com/blogname2]

I haven't contacted the hoster yet as it looks like they're executing the crons on time.

**Comment by Alkarex** [comment]
In your cron logs, do you see a message like *FreshRSS actualization done* ?
If not, it might indicate that the cron job is not reaching the end, for instance because of a timeout defined by the hoster.
When the cron job is killed before the end, new entries are not commited to the main article table and therefore not visible.
You can try to remove your dead feeds, and also to decrease the refresh frequency of some feeds, so that not too many feeds are update each time.

**Comment by oliversum-ch** [comment]
Thanks @Alkarex!
That's probably it, there are entries like 
> Cron <cron@cron11> /usr/bin/timeout --signal=HUP 60m /usr/bin/php81 /home/path_to/freshrss/app/actualize_script.php

I fear that only my hoster can change that...
Thank you!

**Comment by Alkarex** [comment]
60 minutes should be more than enough. There might be something else. Try with `edge` version of FreshRSS if you can, and my other suggestions.

**Comment by oliversum-ch** [comment]
Hm, but it appears to be 60m:

> Cron [cron@cron11](mailto:cron@cron11) /usr/bin/timeout --signal=HUP **60m** /usr/bin/php81 /home/path_to/freshrss/app/actualize_script.php

**Comment by ddubnyk** [comment]
I want to add to this.  Is there some sort of change in the last month or so that would prevent updates if a single rss feed failed?  

I ask because I've had, on occasion, single feeds that will fail for a few hours, which seems to prevent the entire set of feeds to update to my rss client. Once they start to be available again, everything comes through. 

If I've removed that single feed, everyman suddenly comes through. Coincidence? I'm not 100%sure

**Comment by Alkarex** [comment]
@ddubnyk I am not aware of any change that could explain that. I am myself running several instances, each with multiple broken feeds, and without problem.
Try to look at your logs.

**Comment by Frenzie** [comment]
Same. That issues icon all over the place is a bit annoying really. ;-)

**Comment by Slomo17** [comment]
Same issue for me since a few weeks no automatic updates, i host freshrss via docker on my home server, but i didn't change anything related to freshrss.

**Comment by TheRealBenForce** [comment]
Same issue but update to :edge has fixed it for me.

**Comment by Slomo17** [comment]
I think i solved my problem, for some reason cron had no permission to write to the log file, (at least that is what the docker log said) so i deleted the log file and let cron recreate it, now it seams to work again.

**Comment by Alkarex** [comment]
> Same. That issues icon all over the place is a bit annoying really. ;-)

@Frenzie I am not sure I understood your comment. Do you also have a related problem?

**Comment by Frenzie** [comment]
@Alkarex No problem at all. The same I'm referring to is:

> I am myself running several instances, each with multiple broken feeds, and without problem.

I keep around a number of feeds that once were for various reasons, as a random example `http://feeds.feedburner.com/carbonbrief`. (Once in a while one returns after a hiatus of years!) That shows up as a lot of warnings that I'm not particularly interested in from the main interface.

<img src=https://github.com/FreshRSS/FreshRSS/assets/202757/acb75c4f-9e28-407f-bdce-910d30373699 width=200>

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/issues/6113

**Comment by TheRealBenForce** [comment]
@Alkarex , what was the root cause of this issue? Is a resolution available now in :latest?

**Comment by Alkarex** [comment]
> what was the root cause of this issue?

I do not know. This would have required more debugging on the instances with problems. I am not aware of any concrete bug, nor related change. Maybe https://github.com/FreshRSS/FreshRSS/issues/6089#issuecomment-1951324830

**Comment by oliversum-ch** [comment]
@Alkarex It seems to work when I set "Do not automatically refresh more often than" to 3h, and the feeds with the most posts up to 24h. However, that's just a workaround... 
#6089 isn't relevant to me, as I never had permission issues.

**Comment by TheRealBenForce** [comment]
> > what was the root cause of this issue?
> 
> I do not know. This would have required more debugging on the instances with problems. I am not aware of any concrete bug, nor related change. Maybe https://github.com/FreshRSS/FreshRSS/issues/6089#issuecomment-1951324830

No worries, just wanted to learn a bit and read the commit history. I appreciate all the work you are doing, it's an awesome service!

**Comment by Alkarex** [comment]
This patch might help https://github.com/FreshRSS/FreshRSS/pull/6117
It will in particular commit articles from the previous cron if it timed out.
Tests welcome
