### ISSUE TITLE
Would it be possible to apply labels only after the scraping process ended?

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#6090]
During my tests I came across one issue: I am scraping some feeds with the readable plugin. Would it be possible to apply labels only after the scraping process ended? The current solution cannot apply labels which depend on the content of scraped articles.

The same problem I encountered under "subscription management -> filter actions -> mark an article as read...". A filter which is applied on a scraped article doesn't work as labels seem to be applied before the scraped content becomes available.

The same filter under user queries works flawlessly.

_Originally posted by @domalex in https://github.com/FreshRSS/FreshRSS/discussions/3857#discussioncomment-8061749_

**Comment by Alkarex** [comment]
In your case, what is probably needed is to first run the extensions before applying the filter actions.
Could you try https://github.com/FreshRSS/FreshRSS/pull/6091 ? (not tested at all)

Note however that we currently do not run the filter actions again on *modified* articles, as it would re-apply the labels multiple times, preventing users from e.g. manually removing articles.

**Comment by domalex** [comment]
How can I help you testing it? My git knowledge is only basic. Are the changes in the current edge version available?

**Comment by Alkarex** [comment]
How have you currently deployed FreshRSS? git, Docker, ZIP, ...
Yes, the patch is built on the current edge version, so all recent changes are included

**Comment by domalex** [comment]
I have got a docker installation running the freshrss:edge image - currently 1.23.2-dev. Does this build include the changes required that I can test tagging with the latest changes?

**Comment by Alkarex** [comment]
With Docker + git, here is an approach:

```yml
  freshrss:
    image: freshrss/freshrss:pr6091
    build:
      context: https://github.com/Alkarex/FreshRSS.git#extensions-applyFilterActions
      dockerfile: Docker/Dockerfile-Alpine
    ...
```

* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/freshrss/docker-compose.yml
* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md#build-custom-docker-image

**Comment by domalex** [comment]
This bug is fixed. I can confirm that filters behave now the same way in "user queries" and "my labels". They both are able to apply filters on scraped text. I tested with the freshrss:edge image available on Docker Hub. Thank you so much for adding the label feature and allowing it to access scraped text. This is huge!

**Comment by Alkarex** [comment]
Thanks for the feedback. The patch is merged. Please pull again from `freshrss/freshrss:edge`
