### ISSUE TITLE
[BUG] Text encoding looks broken for Italian YT links

### ISSUE THREAD

**Issue by roughnecks** [FreshRSS/FreshRSS#6092]
**Describe the bug**
I cannot read Italian accented letters in youtube feeds

**To Reproduce**
1. Add the feed for this channel: https://www.youtube.com/channel/UCWvaO5qbph2r5yob1ZGLgfQ
2. Fetch News
3. Watch some titles with accented letters

**Expected behavior**
I should be able to read everything correctly

**Screenshots**
https://i.imgur.com/ENcqetv.jpeg

**Environment information (please complete the following information):**
- Device: Desktop PC With Windows 10
- Browser: [Chrome 121.0.6167.140 (Build ufficiale) (a 64 bit)]
- FreshRSS version: [1.23.1]
- Database version: [sqlite 3.40.1-2 Debian Stable]
- PHP version: [8.2.7-1~deb12u1]
- Installation type: [Manual Install]

**Additional Info**
I'm using:

YouTubeChannel2RssFeed (0.3) — Abilitata
Transfer YouTube Channel URL into RSS Feed URL. — di: CNTools | Clemens Neubauer

**Comment by math-GH** [comment]
Please update your extension:
YouTubeChannel2RssFeed is available in v0.4

ping @cn-tools

**Comment by roughnecks** [comment]
Just upgraded, but looking at old news, they're still the same. Should I wait for something new in my feed?

Thanks

**Comment by math-GH** [comment]
yes, you need to wait for the next articles. Or try this option "reload articles" in the feed's settings:
![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/ac8d1a0f-7ed7-4641-82f1-f4c14cbfa2f2)

**Comment by roughnecks** [comment]
I tried that, but.. https://i.imgur.com/xP44A77.jpeg

**Comment by roughnecks** [comment]
This is a new article: https://i.imgur.com/X5nZEht.jpeg

**Comment by Frenzie** [comment]
Does a direct https://www.youtube.com/feeds/videos.xml?channel_id=UCWvaO5qbph2r5yob1ZGLgfQ show the same behavior?

**Comment by roughnecks** [comment]
All good with the direct link: https://i.imgur.com/ahF6w4b.jpeg

**Comment by cn-tools** [comment]
sorry for the late reaction - i will have a look

**Comment by cn-tools** [comment]
Could you try the newest version v0.6.0-alpha please?
There is no longer a third party call involved by default and therefore i hope it will function right.

[https://imgur.com/a/ksry7K1](https://imgur.com/a/ksry7K1)

**Comment by roughnecks** [comment]
Updated and it works now. Thanks
