### ISSUE TITLE
[Feature] Anonymous reading from the API

### ISSUE THREAD

**Issue by JanHitako** [FreshRSS/FreshRSS#6097]
**Is your feature request related to a problem? Please describe.**
I'm trying to figure out if it is possible for the fever or google api to allow anonymous reading of the default user feed (no authentification required) but prevent deletion/moditication/... api calls  ? I'm specifically talking about the api only, not the web-based interface which I know have an option for this.

**Additional context**
We have a student made app for our university in which we would like to integrate a news section that is an aggregation of all of the department RSS news feeds, the app is freely accessed by all students and doesn't require any login and we would like to keep it that way. We are exploring the use of freshRSS as the backend actual aggregator that do the heavy job, and use the api to get the news from the app but seemingly, we cannot find a public read-only access api for the aggregated articles.

**Comment by Alkarex** [comment]
May I suggest another approach: FreshRSS is able to republish as a single RSS any view, including the aggregation of other feeds as you ask.
This has been possible for a long time in FreshRSS using an access token, but I have something better coming: see https://github.com/FreshRSS/FreshRSS/pull/6052
This new PR is able to republish as RSS and HTML any search in FreshRSS (e.g. a category containing your aggregated feeds).

**Comment by JanHitako** [comment]
I tried to look the first option but I cannot find the relevant documentation regarding it. Specifically, where and how to access the republished RSS and how can the repubilshed RSS feed be programmatically loaded for pagination purposes and such.  How to republish a feed is probably very obvious but I genuinly cannot find it unfortunately.

[#6052](https://github.com/FreshRSS/FreshRSS/pull/6052) on the other hand seems on first glance to be very in-line with what we were looking for, so we will look further into it tomorrow.

Thanks a lot @Alkarex!

**Comment by JanHitako** [comment]
Hi @Alkarex , not sure if I should ask this here or start a discussion regarding this, but we don't understand how the "next" parameter work. By observing the webpage calls, we understand this is what is used for pagination but we don't get how it work expect that it is timestamp based.

For example, in this link : https://[demo.freshrss.org/i/?a=rss&rid=65ccbe5651df0&next=1707915606977849](https://demo.freshrss.org/i/?a=rss&rid=65ccbe5651df0&next=1707915606977849) , the timestamp convert into Wednesday, February 14, 2024 1:00:06.977 PM which is correct but the articles in the output RSS are dated from December 2023 to Apr 2023 somehow and the article past December are completely left out. Do you have any insight on how this work? Also is there a way to somehow have a pagination call that output the same amount x of article each time chronologically sorted?

We do realize our usage may possibly be out of scope for FreshRSS so if it is indeed the case, feel free to tell us as maybe this kind of discussion shouldn't be present here.

**Comment by Alkarex** [comment]
`next` is an internal parameter used for pagination. What you want is probably the parameters `nb` and/or `hours`.

* Since X hours: `https://freshrss.example/i/?a=rss&hours=3`
* Explicit number: `https://freshrss.example/i/?a=rss&nb=10`
* Limited by `min_posts_per_rss` and `max_posts_per_rss` in user config

(this requires the `token` and `user` parameters for accessing the data in non-anonymous setups)

But I still recommend starting by having a look at https://github.com/FreshRSS/FreshRSS/pull/6052 (what lacks before completion is actually the pagination)

**Comment by Alkarex** [comment]
See https://freshrss.github.io/FreshRSS/en/users/user_queries.html
