### ISSUE TITLE
[BUG] HTTP+XPATH scraping retrieves garbled feeds from non UTF-8 contents

### ISSUE THREAD

**Issue by hkcomori** [FreshRSS/FreshRSS#6106]
**Describe the bug**
Scraping HTML encoded in non-UTF-8 with XPATH gives unreadable results.

**To Reproduce**
1. Add feed: https://www.xfree.ne.jp/support/news.php (EUC-JP encoded)
2. Got unreadable result

**Expected behavior**

I want results that follow the encoding information of the content (e.g. `<meta charset="EUC-JP">`).
From the [example site](https://www.xfree.ne.jp/support/news.php), the following output is obtained, just as it would be seen in a browser.

> - 2024/02/01    サービスの事業会社変更に伴う利用規約改定のお知らせ
> - 2024/01/30    「SSH接続」など9種類の機能追加のお知らせ
> - 2024/01/30    契約情報やサーバー設定に対して用途を記載できるメモ欄追加のお知らせ
> - 2024/01/16    申し込みの増加に伴う『シン・クラウド for Free』の一時的な新規受付停止のお知らせ
> ...

**Screenshots**

Add feed:
![image](https://github.com/FreshRSS/FreshRSS/assets/11016036/381765f8-3880-40ca-aeea-e1bcb4cf9d3e)

Got unreadable result:
![image](https://github.com/FreshRSS/FreshRSS/assets/11016036/e5b5e7a0-aa5a-4514-a540-ea25be86a3c8)

**Environment information (please complete the following information):**
- Device: PC
- OS: Windows 10 Version 22H2 (Build 19045.4046)
- Browser: Vivaldi 6.5.3206.63
- Server OS: Ubuntu 22.04
- FreshRSS version: 1.23.1
- Database version: SQLite
- PHP version: PHP 8.2.7
- Installation type: Docker

**Additional context**

**Comment by Alkarex** [comment]
Would you be able to test this patch? https://github.com/FreshRSS/FreshRSS/pull/6112

To try a PR, if you can, try to instruct your Docker or docker-compose to build from git:

```yml
  freshrss:
    image: freshrss/freshrss:pr6112
    build:
      context: https://github.com/Alkarex/FreshRSS.git#EUC-JP
      dockerfile: Docker/Dockerfile-Alpine
    ...
```

* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/freshrss/docker-compose.yml
* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md#build-custom-docker-image

**Comment by hkcomori** [comment]
It works fine! Thank you!
![image](https://github.com/FreshRSS/FreshRSS/assets/11016036/b2f447de-bc29-4352-86e3-e0adaae245dc)

**Comment by Alkarex** [comment]
Thanks for the feedback :-)
