### ISSUE TITLE
[BUG] Wrong Japanese translation

### ISSUE THREAD

**Issue by hkcomori** [FreshRSS/FreshRSS#6107]
**Describe the bug**
I think [this](https://github.com/FreshRSS/FreshRSS/blob/2989470e881a48fd1176ca0587bdd2d4678e4424/app/i18n/ja/sub.php#L231) is wrong translation.

**To Reproduce**
1. Set language: 'Japanese'

**Expected behavior**

This means "Add feed or category", so it should be translated that:

```diff
-		'add' => 'フィード化カテゴリを追加します',
+		'add' => 'フィードあるいはカテゴリを追加します',
```

**Screenshots**

**Environment information (please complete the following information):**
- Device: PC
- OS: Windows 10 Version 22H2 (Build 19045.4046)
- Browser: Vivaldi 6.5.3206.63
- Server OS: Ubuntu 22.04
- FreshRSS version: 1.23.1
- Database version: SQLite
- PHP version: PHP 8.2.7
- Installation type: Docker

**Additional context**
I [fixed](https://github.com/hkcomori/FreshRSS/commit/82f729e09be9dfa02c7f67d931aef1a943757d23) this, but only posted an issue because I don't have an environment where I can easily test it.

**Comment by Frenzie** [comment]
I can't speak as to the Japanese, but that'll be the right location. Could you put it in a PR? (Incidentally it's also much easier to test from a PR with something like `git fetch upstream pull/1234/head`, where `1234` is the ID.)

![image](https://github.com/FreshRSS/FreshRSS/assets/202757/dbb367a5-8334-4546-ac11-576fee053116)

**Comment by hkcomori** [comment]
@Frenzie Thank you. That's the display I expected.
