### ISSUE TITLE
Equal Filters in "user queries" and "my labels" do not reliably produce the same results

### ISSUE THREAD

**Issue by domalex** [FreshRSS/FreshRSS#6109]
**Description**

I am testing the new "my labels" feature. Therefore I copied working filters from "user queries" to "my labels". By comparing the results during the last 2 days I realized that the same filter doesn't produce constantly the same results.

**To Reproduce**

1. Create a subscription | Website URL: https://www.nzz.ch/startseite/, Category: Tageszeitung
2. Create another subscription | Website URL: https://www.srf.ch/news/, Category: Tageszeitung
3. Create a "user query" | Name: Wissenschaft, Expression: inurl:nzz.ch/wissenschaft/ OR inurl:srf.ch/wissen/, Type: Tageszeitung
4. Create a "my labels" | Name: Wissenschaft, Filter actions: inurl:nzz.ch/wissenschaft/ OR inurl:srf.ch/wissen/

**Expected behavior**

The same filter lists the same feeds under "user queries" and "my labels".

**Screenshots**

[My labels](https://www.dropbox.com/scl/fi/pvn5sp8hi0cvaki10gjgl/my-filters.jpg?rlkey=4oi97rpadb2ct4vy2ipml8jtd&dl=0)

[User queries](https://www.dropbox.com/scl/fi/mvag34ui5hdu4g3nwmvlt/user-queries.jpg?rlkey=c5aqfsenf48npdz51dv1451jc&dl=0)

**Environment information:**

- Raspberry-Pi 4, 8 GB
- Docker image freshrss/freshrss:edge - currently 1.23.2-dev
- Docker image postgres:16-alpine

**Additional context**

The above is just an example. The bug has been reproduced with other filters.

**Comment by Alkarex** [comment]
Quick thought already: make sure you display both read and unread articles

**Comment by domalex** [comment]
Thank you for your quick response. Even with read and unread function enabled I have got the same result. The query doesn't show the same result.

**Comment by math-GH** [comment]
I guess: The user query search for ALL articles. The "my labels" searches only in new articles.

**Comment by domalex** [comment]
The source for the articles is the same and whether searching for read and/or unread articles doesn't matter.

**Comment by domalex** [comment]
The problem is that the label was not reliably applied to all articles matching the filter. Hence, they don't show under the relevant label.

**Comment by Alkarex** [comment]
This patch might help https://github.com/FreshRSS/FreshRSS/pull/6117 (in particular, we might have had some counting issues when combined with automatically marking as read some articles)
Tests welcome

**Comment by domalex** [comment]
I will try to figure out how I can build the referenced image. Never done it before.

**Comment by domalex** [comment]
I just can't get the image built. I tried this:

```
  freshrss:
    image: freshrss/freshrss:pr6117
    build:
      context: https://github.com/Alkarex/FreshRSS.git#improvedRefresh
      dockerfile: Docker/Dockerfile-Alpine
    ...
```

This result in the following:

```
 ! freshrss Warning                                                                                                                                                                                          2.3s
[+] Building 0.5s (1/1) FINISHED                                                                                                                                                                   docker:default
 => ERROR [freshrss internal] load git source https://github.com/Alkarex/FreshRSS.git#improveRefresh                                                                                                         0.4s
------
 > [freshrss internal] load git source https://github.com/Alkarex/FreshRSS.git#improveRefresh:
------
failed to solve: failed to read dockerfile: failed to load cache key: repository does not contain ref improveRefresh, output: ""
alarm@aarch ~/data/docker/freshrss $
```

**Comment by Alkarex** [comment]
@domalex Did you forget the `d` in `improvedRefresh`?

**Comment by domalex** [comment]
You're right! That was my mistake. Thank  for the hint. I have now the new version including the patch up and running. I'll come back to you as soon I've tested it out.

**Comment by domalex** [comment]
I tested it for 2 days and it works now. I have equal results.

**Comment by domalex** [comment]
I tested it for 2 days and have equal results. According to my tests it is working now.

**Comment by Alkarex** [comment]
Excellent, thanks for the feedback :-)
