### ISSUE TITLE
The search function doesn't find "my labels" (tags)

### ISSUE THREAD

**Issue by domalex** [FreshRSS/FreshRSS#6110]
**Description**

I am testing the new "my labels" feature. The search feature doesn't find feeds with the appropriate "my label" (tag).

**To Reproduce**

1. Create a subscription | Website URL: https://www.tagesanzeiger.ch/, Category: Tageszeitung
2. Create a "my labels" | Name: tagi, Filter actions: inurl:tagesanzeiger.ch/ !Abonnent:in?
4. Enter tagi in the search field

**Expected behavior**

The search result lists all feeds labled with tagi.

**Environment information:**

- Raspberry-Pi 4, 8 GB
- Docker image freshrss/freshrss:edge - currently 1.23.2-dev
- Docker image postgres:16-alpine

**Additional context**

The above is just an example. The bug has been reproduced with other "my labels" (tags).

**Comment by math-GH** [comment]
could you please give a working feed?  https://www.tagesanzeiger.ch/ is not a feed and I cannot find a RSS/Atom feed there

**Comment by domalex** [comment]
This is the feed address to the website above: https://partner-feeds.publishing.tamedia.ch/rss/tagesanzeiger/front. Let me know should you require any further information.

**Comment by Alkarex** [comment]
I am not sure I got the problem/question right, but if you want to search for articles with a given label,

* `label:"Hello World"` (by label name)
* `l:10` (by label ID)

Check the doc https://freshrss.github.io/FreshRSS/en/users/10_filter.html#with-the-search-field
