### ISSUE TITLE
Muted feeds cannot be altered

### ISSUE THREAD

**Issue by domalex** [FreshRSS/FreshRSS#6111]
**Description**

Changes in a muted feed configuration cannot be saved.

**To Reproduce**

1. mute a feed
2. change the automatic refresh rate
4. submit change

**Expected behavior**

The changes are saved.

**Environment information:**

- Raspberry-Pi 4, 8 GB
- Docker image freshrss/freshrss:edge - currently 1.23.2-dev
- Docker image postgres:16-alpine

**Comment by Alkarex** [comment]
Hello,
I cannot reproduce the bug. Could you check your Docker logs and Web browser logs for any hint?

**Comment by domalex** [comment]
I checked the freshrss log. Nothing is registered when I am doing the changes. However, I realize that this only happens when trying to change back form a value to "By default". Other values do register.

**Comment by Alkarex** [comment]
Please try https://github.com/FreshRSS/FreshRSS/pull/6115

**Comment by domalex** [comment]
Thank you. It is now working on the edge image.
