### ISSUE TITLE
MariaDB 11.3 error: Access to database is denied

### ISSUE THREAD

**Issue by cipriani14** [FreshRSS/FreshRSS#6118]
**Describe the bug**
I can visit my install's landing page, but when trying to login I get this error message:

Access to database is denied for `freshrss`: SQLSTATE[HY000] [2054] Server sent charset (0) unknown to the client.

The logs for the freshrss_db show: 

```
Version: '11.3.2-MariaDB-1:11.3.2+maria~ubu2204'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
2024-02-21  7:13:24 0 [Note] InnoDB: Buffer pool(s) load completed at 240221  7:13:24
2024-02-21  7:14:18 3 [Warning] Aborted connection 3 to db: 'unconnected' user: 'unauthenticated' host: '192.168.48.3' (This connection closed normally without authentication)
2024-02-21  7:14:31 4 [Warning] Aborted connection 4 to db: 'unconnected' user: 'unauthenticated' host: '192.168.48.3' (This connection closed normally without authentication)
2024-02-21  7:15:00 5 [Warning] Aborted connection 5 to db: 'unconnected' user: 'unauthenticated' host: '192.168.48.3' (This connection closed normally without authentication)
2024-02-21  7:17:41 6 [Warning] Aborted connection 6 to db: 'unconnected' user: 'unauthenticated' host: '192.168.48.3' (This connection closed normally without authentication)
2024-02-21  7:17:46 7 [Warning] Aborted connection 7 to db: 'unconnected' user: 'unauthenticated' host: '192.168.48.3' (This connection closed normally without authentication)

```
**Screenshots**

**Environment information (please complete the following information):**
- Device: Doesn't matter
- OS: Docker image installed on Synology NAS
- Browser: Safari
- FreshRSS version: 1.23.1
- Database version: I think? 11.3.2
- PHP version: not sure where to find this
- Installation type: Docker

**Additional context**

**Comment by Alkarex** [comment]
Hello,
It looks like you are using MariaDB, and there seems to be a problem with it.
You can always use the built-in SQLite database, which is simpler and with good (sometimes better) performances.
If you can, check the database credentials in `./data/config.php` of your Docker volume for FreshRSS. Full path in the container is `/var/www/FreshRSS/data/config.php`

**Comment by cipriani14** [comment]
Adding this here, as well, in case it helps: 

```
2024/02/21 07:14:18 [error] 289#289: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Minz_PDOConnectionException: Access to database is denied for `freshrss`: SQLSTATE[HY000] [2054] Server sent charset (0) unknown to the client. Please, report to the developers in /app/www/lib/Minz/ModelPdo.php:131
Stack trace:
#0 /app/www/app/Models/Factory.php(47): Minz_ModelPdo->__construct()
#1 /app/www/p/api/greader.php(824): FreshRSS_Factory::createEntryDao()
#2 /app/www/p/api/greader.php(1170): GReaderAPI::editTag()
#3 /app/www/p/api/greader.php(1210): GReaderAPI::parse()
#4 {main}
  thrown in /app/www/lib/Minz/ModelPdo.php on line 131" while reading response header from upstream, client: 192.168.48.1, server: _, request: "POST /api/greader.php/reader/api/0/edit-tag HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "xx.xxx.com"
```

**Comment by fl0wfr** [comment]
Same issue here since this morning... (update to 1.23.1)
Moving to SQLite is not a solution as some of us are already using a populated database on MariaDB.
Credentials are okay in settings, I also checked the connection from container by installing mysql-client and trying to connect to database, no error.

**Comment by Alkarex** [comment]
@fl0wfr What setup do you have in your case? Also Docker on Synology?

**Comment by fl0wfr** [comment]
No, Docker running on a Rocky Linux server.
Docker version is 25.0.3
I tried rolling back to 1.22.0, same error, and 1.21.0 I get a 502 Bad Gateway after authenticating.
According to the logs, it looks like FreshRSS is trying to connect to MariaDB without authentication.

**Comment by Alkarex** [comment]
Could you try with `freshrss/freshrss:edge` and/or `freshrss/freshrss:edge-alpine`?
What architecture? x86_64?
Have you had any update on MariaDB side? There has not been any change on our side that I can think of.

**Comment by fl0wfr** [comment]
> Could you try with `freshrss/freshrss:edge` and/or `freshrss/freshrss:edge-alpine`? What architecture? x86_64? Have you had any update on MariaDB side? There has not been any change on our side that I can think of.

Exact same issue with 2 tags. I'm running x86_64.
You were right, after downgrading the mariadb container to version 10, it works again. Thank you @Alkarex !

**Comment by fl0wfr** [comment]
Issue reported on MariaDB GitHub: https://github.com/MariaDB/mariadb-docker/issues/563

**Comment by cipriani14** [comment]
that fixed it for me as well. thank you!

**Comment by Alkarex** [comment]
Let's keep an eye on the following issues:
* https://github.com/MariaDB/mariadb-docker/issues/560
* https://github.com/php/php-src/issues/13452

**Comment by golfhou** [comment]
I am having the same issue since this morning, but I am not using any external DB/MariaDB.  I also went back to earlier version, and then edge, and no go.  I had a backup of the docker volumes and deployed on a different server and get the same issue on both servers now.  Any idea in this case?

FreshRSS[43]: [admin] [Wed, 21 Feb 2024 22:44:50 -0600] [error] --- Access to database is denied for `root`: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for DB failed: Temporary failure in name resolution

**Comment by golfhou** [comment]
on my first server I did have an external MariaDB, they just pushed an update 12 minutes ago, and now it is working on my first server (the one that went offline this morning).

**Comment by Alkarex** [comment]
MariaDB 11.3 Docker images have been patched - https://github.com/MariaDB/mariadb-docker/commit/d7a950d41e9347ac94ad2d2f28469bff74858db7

_Originally posted by @mvorisek in https://github.com/php/php-src/pull/13470#discussion_r1498914478_
