### ISSUE TITLE
[BUG] "Mark previous read" shortcut no longer working

### ISSUE THREAD

**Issue by jsspen** [FreshRSS/FreshRSS#6120]
**Describe the bug**
The shortcut to "Mark previous read" no longer works. It had worked without issue but that might have been when I was still using Chrome a few months ago and I can't remember for sure when exactly it last worked. It seems like the ALT key is being ignored and as far as I can tell there is no way to actually change the whole shortcut keybinding outside of the 'r' aspect (i.e. I can change it to ALT + B but not SHIFT + B). I'm also not aware of any alternative way in the UI to mark previous read.

**To Reproduce**
1. Go to a feed, expand any entry other than the first
2. Press ALT + R to "Mark previous read"
3. Previous articles remain unread
4. The currently focused article toggles between read/unread as if ALT key is being ignored

**Expected behavior**
Pressing ALT + R should mark all previous (articles above currently focused entry) as read

**Environment information (please complete the following information):**
- Device: Desktop
- OS: Linux Mint 21.2 Xfce
- Browser: LibreWolf 122.0-1 and Firefox 122.0 (64-bit)
- FreshRSS version: 1.23.1
- Database version: mysql Ver 15.1 Distrib 10.5.23-MariaDB, for debian-linux-gnu (aarch64) using  EditLine wrapper
- PHP version: PHP 8.3
- Installation type: self-hosting LinuxServer provided image via Docker-Compose managed with Portainer

**Additional context**
The shortcut for marking all read, SHIFT + R, still works as expected.

Slipping in a little feature request: It would be nice to be able to fully edit the key combo for the shortcut and/or if there was a "Mark previous read" option added to the "Mark as read" dropdown in the UI.

**Comment by Alkarex** [comment]
Hello,
I cannot reproduce on Ubuntu with Firefox, and on Windows with Firefox or Edge or Chrome.
Do you have anything in your Web browser console?
If you can, try to use your Web browser JavaScript debugger to find out whether you reach this code:

https://github.com/FreshRSS/FreshRSS/blob/84d88d4b5dbd12130344a02fa8dd2cfb2b55b96a/p/scripts/main.js#L982-L984

Maybe you have some shortcuts at OS or browser level interfering.
Additional tests welcome.

**Comment by jsspen** [comment]
![Screenshot_2024-02-22_11-22-00](https://github.com/FreshRSS/FreshRSS/assets/70607838/b4db5c4e-bc7c-41a8-8fa6-6f32f941f3e9)

Yes, I'm making it to that part of the script just fine and as I expected it seems it's not picking up on the ALT key being depressed. Strange that it still picks up the 'R', though. Hm...

I've just tested again in Firefox and it worked (I could have sworn when I tested yesterday it didn't!) so it _must_ be something with LibreWolf and all of it's various protections & modifications.

And yes, I really should have checked sooner, there do appear to be some problems in the console:
```
Content-Security-Policy: The page’s settings blocked the loading of a resource at inline (“default-src”)
downloadable font: kern: Too large subtable (font-family: "OpenSans" style:normal weight:400 stretch:100 src index:2) source: http://192.xxx.xx.xxx:xxxx/themes/fonts/OpenSans.woff2
downloadable font: Table discarded (font-family: "OpenSans" style:normal weight:400 stretch:100 src index:2) source: http://192.xxx.xx.xxx:xxxx/themes/fonts/OpenSans.woff2
Feature Policy: Skipping unsupported feature name “autoplay”.
Feature Policy: Skipping unsupported feature name “encrypted-media”.
Feature Policy: Skipping unsupported feature name “clipboard-write”.
Feature Policy: Skipping unsupported feature name “picture-in-picture”.
Feature Policy: Skipping unsupported feature name “accelerometer”.
Feature Policy: Skipping unsupported feature name “gyroscope”.
The Notification permission may only be requested in a secure context.
An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can remove its sandboxing.
```
The only one of those that I still see in Firefox is the Notification permission error. Looks like I'm going to have to do some digging into LibreWolf.

**Comment by jsspen** [comment]
Alright, got it! Looks like I had to disable ResistFingerprinting in the LibreWolf preferences. WebGL can stay disabled and canvas access requests can still be silently blocked. I installed the CanvasBlocker extension as suggested when disabling ResistFingerprinting and the extension doesn't appear to break anything like the built-in did.
