### ISSUE TITLE
[BUG] Updating feeds crashes FreshRSS on GoDaddy server

### ISSUE THREAD

**Issue by daveschroeter** [FreshRSS/FreshRSS#6123]
**Describe the bug**
Smooth installation and usage until I refresh feeds (I have ~350). FreshRSS updates ~40 of them, then crashes (like, Site Can't Be Reached). On reloading, those 40 or so are updated, so I can do the next 40 or so until complete.

**To Reproduce**
1. Click on the Update Feeds Icon
2. Wait for the crash

**Expected behavior**
A full feed update without crashing

**Environment information (please complete the following information):**
- Browser: Chrome 121.0.6167.185
- FreshRSS version: 1.23.1
- Database version: sqlite
- PHP version: 8.1.27
- Installation type: Manual GoDaddy server install

**Additional context**
I am on an ancient (8 years old?) GoDaddy server.
95% of my feeds are YouTube channels.
FreshRSS Logs are clean.
When the crash happens, it takes my entire server section down for ~30 seconds.

**Comment by Alkarex** [comment]
How do you refresh the feeds? By cron or Web interface?
What Web server, and what do you have in your Web server logs?
How much memory left is there on your server just before it crashes?

**Comment by daveschroeter** [comment]
I'm just refreshing by clicking the icon in the web interface.
I'm a layman here but it's a GoDaddy server running Apache version 2.4.58. I'm not sure what logs I'm looking for. The only way I know to check RAM usage is through CPanel, and that crashes when FreshRSS does. I do know it's only 512M and hovers around 13% usage under normal conditions.

**Comment by Alkarex** [comment]
Would you be able to change the value from 10 to 2 in:
https://github.com/FreshRSS/FreshRSS/blob/2d18da1a7dfd8cf32ed0f73f3b75a7015d1b1f3d/p/scripts/main.js#L1451

**Comment by daveschroeter** [comment]
Sure! That makes refreshing go a little slower and a little more stably; now gets through over a hundred or so feeds before crashing. Progress!

**Comment by Alkarex** [comment]
OK, so it could be worth making an option for that, then.

**Comment by Alkarex** [comment]
@daveschroeter Would you be able to test https://github.com/FreshRSS/FreshRSS/pull/6124 ?

**Comment by daveschroeter** [comment]
On more testing, I set the parallel feed update to just one and I'm still getting crashes. Because it is much slower, I'm able to refresh cPanel and am not noticing a spike in RAM use or processing.

**Comment by Alkarex** [comment]
I would need some kind of additional information like logs or similar. What Web server is used? Apache? It might not be a crash but maybe the Web server config not allowing more connections until the existing ones are completed.

**Comment by daveschroeter** [comment]
GoDaddy server running Apache version 2.4.58.

Again, I'm a layman; I'm not sure where to find the appropriate logs. FreshRSS logs don't show any errors.
