### ISSUE TITLE
[BUG] app/Mailers/UserMailer: PHP Deprecated:  Creation of dynamic property

### ISSUE THREAD

**Issue by wonderfulShrineMaidenOfParadise** [FreshRSS/FreshRSS#6129]
**Describe the bug**
https://www.php.net/manual/en/migration82.deprecated.php
https://github.com/FreshRSS/FreshRSS/blob/edge/app/Mailers/UserMailer.php#L19-L21

**To Reproduce**
1. Enable `force_email_validation`
2. Go to "Profile"
3. Add an email address
4. Click "Resend the email"
5. See error

**Expected behavior**
Email is sent.

**Screenshots**
![Screenshot 2024-02-27 at 15-45-33 Email address validation · FreshRSS](https://github.com/FreshRSS/FreshRSS/assets/86928419/ddc53a2b-1271-49d1-b8e5-97799715b492)

**Environment information (please complete the following information):**
- Device:
- OS: postmarketOS v23.12 / Alpine 3.19
- Browser:
- FreshRSS version: 1.23.1
- Database version:
  mariadb  Ver 15.1 Distrib 10.11.6-MariaDB, for Linux (aarch64) using readline 5.1
- PHP version:
  PHP 8.2.16 (fpm-fcgi) (built: Feb 16 2024 01:31:55)
  Copyright (c) The PHP Group
  Zend Engine v4.2.16, Copyright (c) Zend Technologies
  with Zend OPcache v8.2.16, Copyright (c), by Zend Technologies
- Installation type: `apk add freshrss`

**Additional context**
```
2024/02/27 15:45:32 [error] 15935#15935: *2255 FastCGI sent in stderr: "
PHP message: PHP Deprecated:  Creation of dynamic property Minz_View::$username is deprecated in /usr/share/webapps/freshrss/app/Mailers/UserMailer.php on line 19;
PHP message: PHP Deprecated:  Creation of dynamic property Minz_View::$site_title is deprecated in /usr/share/webapps/freshrss/app/Mailers/UserMailer.php on line 20;
PHP message: PHP Deprecated:  Creation of dynamic property Minz_View::$validation_url is deprecated in /usr/share/webapps/freshrss/app/Mailers/UserMailer.php on line 21"
while reading response header from upstream, client: 192.168.1.100, server: localhost, request: "POST /i/?c=user&a=sendValidationEmail HTTP/2.0", upstream: "fastcgi://unix:/run/php-fpm82/freshrss.sock:", host: "localhost"
```

**Comment by Alkarex** [comment]
Thanks for the bug report. Would you be able to test https://github.com/FreshRSS/FreshRSS/pull/6130 (untested)?

Interesting with `apk add freshrss`; I had seen some work in progress some time ago but did not know it was available :-) Feedback welcome on that, as well as PR to add it in our documentation:

* https://github.com/FreshRSS/FreshRSS/blob/edge/README.md#installation
* https://github.com/FreshRSS/FreshRSS/tree/edge/docs/en/admins

**Comment by wonderfulShrineMaidenOfParadise** [comment]
It works. Thank you for the quick fix.

By the way FreshRSS has been packaged in Alpine apk, but only on edge, so I am not sure whether it's fine to add this.
https://gitlab.alpinelinux.org/alpine/aports/-/tree/master/testing/freshrss
Hope that we can do `apk add freshrss` on 3.19 or newer stable branches someday.
