### ISSUE TITLE
Invalid char in most of articles [FULL CONTENT via CSS selector] (SimplePie problem converting to UTF-8)

### ISSUE THREAD

**Issue by ZicPL** [FreshRSS/FreshRSS#6133]
hi,
I'm not a dev, so please forgive my lack of jargon. Freshrss is wonderful :)
Unfortunately, I'm experiencing inconsistent character encoding issues.. It's possible that I set FreshRSS incorrectly. In my case, the website I'm getting the full article content from uses ISO-8859-2 encoding. From what I understand, freshrss only uses UTF-8 and there is no option to choose the encoding for a specific feed.

**My settings for RSS**
Title: TwojePC.pl
Description: info about HW
Website URL: http://twojepc.pl
Feed URL: https://twojepc.pl/news_rss.php
Type of feed source: RSS / Atom (default)
Article CSS selector on original website: tr:nth-child(2)>td.txt
CSS selector of the elements to remove: table
"Always clear cache" option checked

**To Reproduce**
1. Create an RSS feed as described in "My RSS settings" above;
2. click the "Update feeds" button;
3. Go back to Main stream;
4. Check all feeds (articles with full text) for character encoding.
5. See error: Most articles will have character encoding errors.

**Expected behavior**
Articles should have the correct characters. If the character conversion fails, there should be information about it on the application log page.

**Screenshots**
![Screenshot_wrong_characters](https://github.com/FreshRSS/FreshRSS/assets/55097497/542e389a-479c-4870-9b13-8b9e84217f9c)

**more info**
- Hosting SSD NVMe (provider hitme.pl my plan E-BIZNES)
- OS: Linux (debian - no info about version)
- Browser: Firefox 123
- FreshRSS version: 1.23.1 
- Database version: mysql  Ver 15.1 Distrib 10.6.16-MariaDB, for Linux (x86_64) using readline 5.1
- PHP version: 8.1
- Installation type: Apache 2.4

**Additional context**
I think that twojepc.pl is not the only website that has information about character encoding in the meta tag. For better protection against unexpected encoding, font, and other similar issues, it is recommended to implement a new feature: In the "Manage" section for each RSS feed, a new advanced option could be added: "Enable feed's meta tag for content." This would allow users to customize how FreshRSS retrieves article content.

**Comment by Alkarex** [comment]
Maybe fixed by https://github.com/FreshRSS/FreshRSS/pull/6112
Please try the edge version of FreshRSS

**Comment by ZicPL** [comment]
The fix solved the problem. Thanks for your support =)
