### ISSUE TITLE
[BUG] Subscription is hidden from the UI, and is unable to be removed from Subscription Management if you add a feed as an empty XPath + HTML.

### ISSUE THREAD

**Issue by K4LCIFER** [FreshRSS/FreshRSS#6134]
**Describe the bug**
A feed URL was added as an XPath + HTML but with no configuration options beyond the title. The Feed doesn't appear in the feed list, or in subscription management. The only place that it shows is in the backup tab. This results in the feed not being able to be removed, and when you try to add it agin you get an error of "Subscription already exists".

**To Reproduce**
1. Grab a link (doesn't necessarily have to be a valid feed)
2. Go to create a subscription
3. Add the URL to "Feed URL"
4. Add a title to feed title. `"Feed title"` would suffice.
5. Click "Add"
6. Observe that the feed doesn't exist under Main Stream
7. Observe that the feed doesn't show up in Subscription Management
8. Observe that the feed does show up in Subscription Management > Import & Export > Export 

**Expected behavior**
I would just expect an empty feed to show up.

**Screenshots**
N/A

**Environment information (please complete the following information):**
- Device: Desktop
- OS: Arch Linux
- Browser: Firefox v123.0
- FreshRSS version: v1.23.1
- Database version: SQLite (Not sure how to find the version)
- PHP version: Unknown
- Installation type: Docker

**Additional context**
None.

**Comment by Alkarex** [comment]
I cannot immediately reproduce the problem.
Could you check your Docker logs for FreshRSS?
And could you try with the edge version of FreshRSS? `freshrss/freshrss:ege`

**Comment by math-GH** [comment]
@K4LCIFER  Can you reproduce it on https://demo.freshrss.org?

**Comment by K4LCIFER** [comment]
Hm, I appear to not be able to reproduce it on my server. I'm not sure what glitched out, but it was quite a pain to remedy — I had to go into the database and remove the entry manually.

**Comment by Alkarex** [comment]
Could you try to stress test the system a bit using the current `edge` version to see whether you might be able to reproduce the bug?
