### ISSUE TITLE
"Mark an article as read… if an identical title already exists in the top n newest articles" at category level

### ISSUE THREAD

**Issue by K4LCIFER** [FreshRSS/FreshRSS#6143]
**Describe the bug**
With the setting that marks duplicates as read if a duplicate exists in the top n articles enabled, duplicate articles are still showing up.

**To Reproduce**
1. Enable the setting mentioned in the title
2. Get a feed with duplicate titles, observe that the duplicates aren't marked as read.

**Expected behavior**
I would expect the duplicates to be marked as read.

**Screenshots**
The setting:
![image](https://github.com/FreshRSS/FreshRSS/assets/7829231/6802166c-72c0-4c9c-8b82-76722f74f756)

The duplicates:
![image](https://github.com/FreshRSS/FreshRSS/assets/7829231/294985dc-4680-4e27-99d3-75c9ef5651ec)

**Environment information (please complete the following information):**
- Device: Deskop
- OS: Arch Linux (Desktop), Ubuntu Server (FreshRSS server)
- Browser: Firefox v123.0
- FreshRSS version: v123.1
- Database version: SQLite3
- PHP version: —
- Installation type: Docker

**Additional context**
Perhaps the issues is because of the proximity in the times of the two articles? It may not be able to flag them because they appear to arrive at the same time.

**Comment by math-GH** [comment]
Please support here with one or two example feeds. It would help to reproduce this issue

**Comment by K4LCIFER** [comment]
Sure. Here's the two feeds for the example mentioned in the post:
- https://globalnews.ca/feed/
- https://globalnews.ca/bc/feed/

Here's another example:
![image](https://github.com/FreshRSS/FreshRSS/assets/7829231/0bc20e04-0075-4eeb-a966-1f0c83fcf1c5)
- https://www.theverge.com/rss/index.xml
- https://www.theverge.com/tech/rss/index.xml

And another example:
![image](https://github.com/FreshRSS/FreshRSS/assets/7829231/0225d256-d706-43ba-8b8a-7a676468fb0a)
- https://www.polygon.com/rss/front-page/index.xml
- https://www.polygon.com/rss/gaming/index.xml

**Comment by Alkarex** [comment]
At the moment, the check is solely done inside each individual feed. I believe we already have another issue open to do the same at category level and possibly at global level.

**Comment by Alkarex** [comment]
Implemented in https://github.com/FreshRSS/FreshRSS/pull/6922
Tests welcome
