### ISSUE TITLE
[BUG] FreshRSS can't subscribe to RSS feed that sometimes requests JavaScript and cookies

### ISSUE THREAD

**Issue by danburd** [FreshRSS/FreshRSS#6147]
**Describe the bug**
Politico RSS feed no longer works: https://www.politico.com/rss/politicopicks.xml

**To Reproduce**
1. Subscribe to https://www.politico.com/rss/politicopicks.xml
2. Receive error "Blast! This feed has encountered a problem.

**Expected behavior**
Subscription would continue working, as it had before 2/28/2024 at 6:19 AM EST.

**Screenshots**

**Environment information (please complete the following information):**
- Device: PC
- OS: Fedora 39
- Browser: Firefox 123.0
- FreshRSS version: 1.23.1
- Database version: Unknown
- PHP version: Unknown
- Installation type: Docker

**Additional context**
I can perform ```curl -v https://www.politico.com/rss/politicopicks.xml``` and receive the feed correctly; however, [the W3 validator shows an error](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.politico.com%2Frss%2Fpoliticopicks.xml). [Using the RSS Board validator](https://www.rssboard.org/rss-validator/check.cgi?url=https%3A%2F%2Fwww.politico.com%2Frss%2Fpoliticopicks.xml), we get a clue why - it seems to be asking for Javascript and cookies. Instead of the feed, the URL will load a webpage saying "Just a moment..." and then, "Enable JavaScript and cookies to continue."

This is similar to my issue in #5947 in that there seems to be an anti-scraping service in place. However, in this case, cURL actually works, but FreshRSS doesn't. Also in this case, it's an RSS feed and not XPath scraping. It is infuriating that these increasingly-common anti-scraping services don't make an exception for RSS URL's.

**Comment by math-GH** [comment]
Could you please check via curl if it makes a difference while using IPv4 and IPv6?

**Comment by danburd** [comment]
On my end, ```curl -v -4 https://www.politico.com/rss/politicopicks.xml``` successfully loads the feed. ```curl -v -6 https://www.politico.com/rss/politicopicks.xml``` results in a ```Network is unreachable``` error.

**Comment by math-GH** [comment]
Which Docker image do you use from which source?

**Comment by danburd** [comment]
linuxserver.io: https://fleet.linuxserver.io/image?name=linuxserver/freshrss

**Comment by Alkarex** [comment]
Try to use `curl` as user-agent (available in the advanced settings when adding the feed)

**Comment by danburd** [comment]
Thank you. Setting the user agent as ```curl/8.21``` fixed the issue. I have no idea why a website would allow curl to access their website without enabling javascript or cookies, but not other user agents. Nevertheless, I appreciate your help.
