### ISSUE TITLE
[BUG Security][Feature] Delete old articles & Limit for Update feed

### ISSUE THREAD

**Issue by ZicPL** [FreshRSS/FreshRSS#6149]
**Describe the bug/Feature**
do I set 1 month in archiving for:
1. The creation time of the article, which is a condition for downloading? ("Update feeds")
2. How long does it take to delete an article after it has been downloaded by me?
See screenshot below:

If your answer is 2, is it possible to implement a "downloading articles from the feed" section? Of course, after downloading by the user, this section may show that there are more articles available for download, e.g. 12(downloaded)/25(total), but the end user could decide:
- I'm interested (I change the date) - I'm downloading again,
- it's too old - I don't download it.

The date of creation of the article is very important to me. Current FreshRSS shows the dates of creation of articles by default (upper right corner after clicking on the article).
If the current FreshRSS application does not have this feature, it would be great to have this feature implemented in the next version <3

**To Reproduce**
archiving Section or new Section

**Expected behavior**
New Feature "downloading articles from the feed" section.

**Screenshots**
![feed](https://github.com/FreshRSS/FreshRSS/assets/55097497/a90affd9-912c-4213-b5ac-1b8dbb9beb9b)

, Best regards

**Comment by TesterEU** [comment]
Good idea. Controlling news downloads (date of article creation) in the user's "Manage" feed would allow for better management of FreshRSS content.

I'd like two features in the new version of FreshRSS:
1. Removing individual articles from the Feed. Now there is only "Delete all articles". I guess this would require adding a new behavior: "mark" on clicking an article in the "Main stream".
2. Create a new field in left panel: "Trash" next to "Main stream", "Favourites" and "My labels". "Trash" could have its own Manage.

@Frenzie @Alkarex Can you tell us what you think about the above three features?

**Comment by Frenzie** [comment]
Personally I'm very much in favor of trash, as quite distinct from read. But its absence clearly hasn't bothered me quite enough to implement it or anything, so there's that.

Discussion is in https://github.com/FreshRSS/FreshRSS/issues/2018, I left some opinions in https://github.com/FreshRSS/FreshRSS/issues/2018#issuecomment-480578542

A technical proposal of sorts exists in https://github.com/FreshRSS/FreshRSS/issues/1167#issuecomment-480534184

I don't think anybody ever got around to evaluating the performance impact though. :-)

**Comment by TesterEU** [comment]
I read this long discussion. @Frenzie  Do you think there is a chance to implement this feature in the next version?

**Comment by Frenzie** [comment]
It's a significant time investment, so I wouldn't count on it in the near future.

**Comment by ZicPL** [comment]
@TesterEU and @Frenzie Thanks for the answers.
I corrected the topic (it was too general).
I think I've been misunderstood. Let me write in more detail what I think needs improvement:

After adding the RSS feed, I can download new articles -> Manage -> Update feeds. "New" is a relative term. You both focused on managing the downloaded content. This is a great idea for the future, but my request to you related to the Update feeds event.

**What is the real problem.**
I'm the administrator of my freshrss instance. I 've set it to download FULL articles. I'm using a css selector. Full articles take up a bit more space on my disk space (my hosting plan is basic). Saving space is the first reason. The second reason is the mess: If I remove all articles from the feed (all of them have been read by me), my Cron "actualize_script.php" downloads them back. Yes, I like to be organized and I don't want to keep the articles I have read.
The error I wrote about is that I can't control what I download (I don't want to turn off Cron). The current options will quickly delete articles (1 hour), and my Cron (does Update feed every 25 min) - a loop is created.

**Do I have to download everything from the RSS feed?**

I'm asking you to tell me: How to download part of an RSS feed. If this is impossible, please explain to me why not. Maybe my thinking is wrong. If it is possible, but this feature needs to be implemented, will the new version of FreshRSS have it?

**Comment by Frenzie** [comment]
If you delete something there's no record of it, so it will be readded by logical necessity. The only way around that is some kind of trash feature, regardless what motivates it. But your "second reason" is quite literally the entire motivation for everything I wrote. ;-)

**Comment by ZicPL** [comment]
> If you delete something there's no record of it, so it will be readded by logical necessity. The only way around that is some kind of trash feature, regardless what motivates it. But your "second reason" is quite literally the entire motivation for everything I wrote. ;-)

I still don't understand how the "Update feeds" button works. I think there's something wrong with me. I know that "Update feeds" triggers an event on the server identical to refresh. Could the code/script responsible for the operation (downloading the article) be defined by the user? Now its action is "download everything"

**Comment by Frenzie** [comment]
I think database insertion by time sounds more like something for an extension. Though @Alkarex given the nature of full article download it might make sense to implement some kind of optional limit there as part of the core?

**Comment by TereyagiTR** [comment]
Wait, it downloads all full articles from the RSS feed which I add? Laughing.. @ZicPL  I will make a fake website for you :) There're hundreds of posts with several thousand characters and graphics in RSS feed. Let me know if your FreshRSS installation crashes during the update feed from my website 🤣

**Comment by Frenzie** [comment]
> Wait, it downloads all full articles from the RSS feed which I add?

If settings such as these are optionally used. Not by default.

![image](https://github.com/FreshRSS/FreshRSS/assets/202757/a6301d45-a749-4278-bfcb-fa535ef49756)

**Comment by ZicPL** [comment]
> If settings such as these are optionally used. Not by default.

These optional settings are used by me and I guess, by many other people as well. I see now, the problem in question is also related to security. It would be sad to drop this optional setting. This option helps me a lot <3 Drop this option due to the risk of the instance crashing or its instability will be an unpleasant necessity.

**Comment by Frenzie** [comment]
Generally speaking I think the risk is that your server (and possibly FreshRSS user agents in general) would be banned.

**Comment by ZicPL** [comment]
@Frenzie, I think that You know more than me about this solution and other risk. You wrote above "make sense to implement some kind of optional limit". Is this 'download limit' a good idea? Will it take a long time to implement 'download limit'? Please @Frenzie and @Alkarex let me know, ok?

**Comment by Alkarex** [comment]
I have not read the full thread in details, but to make sure to answer the original post: the archiving is based on the date when the article was received, not the "publication date", which is just some informative metadata. You can however search for older publication dates or even mark them as read automatically using something like `pubdate:P30d` (see e.g. https://github.com/FreshRSS/FreshRSS/discussions/6101#discussioncomment-8479032)
There is no condition for downloading, as we cannot download a partial RSS feed. However, if you talk about retrieving full content (which is always to be used with parsimony), it is not done again if the RSS article already exists in FreshRSS database and has not changed. I am considering adding conditions for retrieving full content, maybe in combination with automatic user labels.

**Comment by ZicPL** [comment]
> There is no condition for downloading, as we cannot download a partial RSS feed.

ohh :( I understood that FreshRSS can only process an RSS stream after it has been completely downloaded.
You wrote about the FreshRSS database:

> (..) it is not done again if the RSS article already exists in FreshRSS database and has not changed.

Could you **add a new "dedicated" record in the database** that will pretend that an article exists?
Here is my explanation for the above suggestion:

In the example I discuss only one and the same RSS feed.
1. The user clicked "Update feeds" or refresh;
2. All articles have been downloaded;
3. In the panel on the left side (with the name) of the RSS channel, the following indicator appeared: (5/5). The number of new articles is given before the / sign. After the / sign, the number of old articles is given;
4. The user has read all articles;
5. User clicked "Delete all articles" -> (0/0);
6. The database records which articles were deleted in a new record.

[After 6 days. RSS feed still has no new articles]

7. the user clicked "Update feeds".

Application backend:
- FreshRSS downloads articles from RSS and checks the database.
- I quote you: "article already exists in FreshRSS database and has not changed", because the new "dedicated" record saved a characteristic element (heading, author, etc.) from each deleted article.
_Note: The new "dedicated" record is like a cache for the RSS feed._
The new and old elements being compared are identical and now I quote you: "(..) and has not changed".

8. The user has no new articles in the RSS feed. He only sees the indicator: (0/5) instead (0/0).
9. Optionally, you can add a button, e.g. "Reupdate deleted feeds", this will cancel the comparison of elements from the database and work as it is now.

@aledeg / @Frenzie Do you have any questions about my plan? Could I have missed something?
Do you think the above plan is possible to implement?

I really Thank You for wanting to help me 🥇

**Comment by Jeroslav** [comment]
Creating a cache in DB for manage articles from RSS feeds is a good idea ☻

**Comment by MarkusDeland** [comment]
What is position on @ZicPL proposal?

**Comment by 5murfete** [comment]
@Alkarex

**Comment by Alkarex** [comment]
Copying answer from duplicated thread: https://github.com/FreshRSS/FreshRSS/discussions/7078

> Hello, That thread contains a mix of discussions and clarifications, so I am not sure what your specific need or use-case is. But I have already answered [#6149 (comment)](https://github.com/FreshRSS/FreshRSS/issues/6149#issuecomment-1977430867) You are welcome to send a pull request for _adding conditions for retrieving full content_. The specific post you link to (after my answer) is quite far from the way FreshRSS works, and does not take into account the previous post. Let's close here, if there is nothing new. I will copy my answer in the original thread.

**Comment by ZicPL** [comment]
sometimes I receive notification from this thread, which shows interest.
@Alkarex I agree with You - in this issue I didn't focus only on my request (bc I needed to understand app work). I think that "discussion channel" is a better place to define this feature and present possibility of its implementation. I created this issue in a hurry - I should have used the discussion channel first, so I'm closing this issue and will clarify the concept in the linked discussion.

**Comment by Alkarex** [comment]
There is now a [new option](https://github.com/FreshRSS/FreshRSS/commit/33fd07f6f26310d4806077cc87bcdf9b8b940e35#commitcomment-150152171) to add a condition to retrieving full content:

![image](https://github.com/user-attachments/assets/08181b06-3d83-4585-9bee-0db08a254ad8)

**Comment by Alkarex** [comment]
I realise that some people in this thread may not be aware with some of the existing functionalities, so make sure to experiment with the existing ways to show / hide and classify articles: *read / unread / starred (favourites) / labelled (tagged)*

As well as the following option:
![image](https://github.com/user-attachments/assets/a7b7f249-7ea9-4ec6-94dc-f8b1bd86b5a4)

**Comment by Alkarex** [comment]
Related PR https://github.com/FreshRSS/FreshRSS/pull/7088. Tests welcome
