### ISSUE TITLE
Bandeau des nouveaux articles ne s'affiche pas lorsque l'on affiche uniquement les non-lus

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/FreshRSS#617]
Voilà, tout est dans le titre, j'ai mis la nouvelle option qui permet d'avoir "Il n’y a aucun article à afficher. Vous pouvez ajouter des flux." lorsque tous les articles sont non-lus au lieu d'avoir les articles lus, et lorsque j'ai de nouveaux articles non-lus via la notification chrome, je n'ai pas le bandeau bleu habituel que j'avais en mode "adaptatif".

**Comment by Alwaysin** [comment]
These three things affect usability and should be made into next stable imo.

(not asking nor urging you to do it of course)

**Comment by math-GH** [comment]
What is the status here? We are already in V1.19. Is everything here solved?
What is left to do?

**Comment by Frenzie** [comment]
Probably fixed, but in any case it's a duplicate of #1529 so closing in favor of that one. ^_^
