### ISSUE TITLE
wallabag shairing

### ISSUE THREAD

**Issue by proline** [FreshRSS/FreshRSS#6182]
Hello,

I am trying to connect my freshrss to my wallabag.
But I don't understand how to do it, When I enter the service as describe here 
https://freshrss.github.io/FreshRSS/en/users/08_sharing_services.html
Nothing happen.
I tried with the extension https://github.com/youknow0/freshrss-wallabag but I have an error in the log.txt
[warning] --- wallabag_api_username does not exist in configuration
I don't know what to do.

**Comment by Frenzie** [comment]
Whatever it says where you access Wallabag (`https://your.server/wallabag`) is what you should enter in there.

**Comment by proline** [comment]
I did this but after I don't see anything different

**Comment by proline** [comment]
Ok I found how to use it, thanks.
