### ISSUE TITLE
[BUG] Error 403 with many operations

### ISSUE THREAD

**Issue by Arnoud-B** [FreshRSS/FreshRSS#6187]
**Describe the bug**
Getting Error 403 with many operations (while logged in as admin), for instance when exporting, optimizing the database or creating a new user.

I see no errors in the log that may be related. I logged out and back in to make sure it wasn't an auth issue.

Installation check reports 2 issues:
- Cannot find the PHP fileinfo library (fileinfo package).
- Cannot find the ZIP extension (php-zip package).

**To Reproduce**
1. Go to /p/i/?c=configure&a=archiving
2. Click on Optimize database
3. See error:
> Error 403 - Forbidden
> You don’t have permission to access this page [CSRF]

**Expected behavior**
No error.

**Environment information (please complete the following information):**
- Device/OS: macOS Sonoma
- Browser: Orion
- FreshRSS version: 1.23.1 (same error on 1.22)
- Database version: MySQL 10.6.16-MariaDB-cll-lve
- PHP version: 8.2.16
- Installation type: Shared Cpanel hosting

**Comment by Alkarex** [comment]
Would you be able to try our `edge` version of FreshRSS?

**Comment by Arnoud-B** [comment]
Just updated to edge, but it doesn't allow me to go to step 3 (database config) in the installation. When I updated to 1.23.1 yesterday, it detected a previous install and I reverted to that.

Edit: Nevermind, forced the next step via the URL.

After install, still getting 403 error when optimizing the database (as test). Even changing the theme leads to a 403 error.

**Comment by Alkarex** [comment]
> forced the next step via the URL

This is a sign that there is something wrong with your setup, for instance a wrong PHP session configuration, or wrong cookies configuration (at Web server level or at your Web browser level)

**Comment by Arnoud-B** [comment]
Thanks for the hint. I removed the config and then successfully installed it via another browser. No 403 errors in the other browser either.

FYI, I ran into these issues with Orion. Turning on Compatibility Mode seems to fix it in that browser too.
