### ISSUE TITLE
[BUG] Latex-Support plugin doesn't implement CSP rules

### ISSUE THREAD

**Issue by sherlcok314159** [FreshRSS/FreshRSS#6200]
**Describe the bug**
 Latex-Support plugin does not work. It seems like the old latex plugin does not consider CSP rules.

<img width="1272" alt="图片" src="https://github.com/FreshRSS/FreshRSS/assets/76043326/fabd13ef-55ca-4655-a54e-b208bcd2a5e1">

**To Reproduce**
Just install the latex plugin at [here](https://github.com/aledeg/xExtension-LatexSupport) and then you will find the error.

**Expected behavior**
It should work smoothly.

**Screenshots**
None of latex is rendered.

<img width="627" alt="图片" src="https://github.com/FreshRSS/FreshRSS/assets/76043326/9fe5e57c-b48b-4aa5-a9b4-f71202d32a7f">

**Environment information (please complete the following information):**
- Device: MacOS
- OS: Ubuntu 20.04
- Browser: Firefox / Edge
- FreshRSS version: 1.23.1
- PHP version: 8.2.7
- Installation type: Docker-compose

**Comment by math-GH** [comment]
Thanks for bringing up this issue. Please use the issue tracker of this extension: https://github.com/aledeg/xExtension-LatexSupport/issues

(Ping @aledeg  )

**Comment by sherlcok314159** [comment]
Hi! I am not intended to use this issue tracker. However, the latest commit of that plugin is 3 years ago. I have no way but to ask here. And this issue can be general for others who developing plugins or inserting something. I hope you can answer it if available.

**Comment by math-GH** [comment]
I thought that the issue tracker of this extension is available for everyone. I apologize.

This extension uses inline code that is prohibited by the CSP (Content security policy) of FreshRSS. It is an important security layer. The fix needs to be done by the extension itself.

Could you please give some example feeds with LaTeX code? It would help to understand the issue better.

**Comment by sherlcok314159** [comment]
Fine. You can try this [feed](https://kexue.fm/feed) with a CSS selector as `#PostContent`. Thanks for the quick response.

**Comment by Frenzie** [comment]
(I rather doubt I have any special permissions there, opened one at <https://github.com/aledeg/xExtension-LatexSupport/issues/3>.)

**Comment by sherlcok314159** [comment]
any help?

**Comment by aledeg** [comment]
I'll look into that

**Comment by aledeg** [comment]
> Hi! I am not intended to use this issue tracker. However, the latest commit of that plugin is 3 years ago. I have no way but to ask here. And this issue can be general for others who developing plugins or inserting something. I hope you can answer it if available.

There was no issue so far. There is no need to change when it's working. That's why there was no commit.

**Comment by sherlcok314159** [comment]
Sorry. I beg to differ. Have you tried my feed yet? How could you say there was no issue? The console errors are almost bombarded. Or are you using very old freshrss?

**Comment by aledeg** [comment]
There was no issue so far. I will look into your feed.
I am not saying that there is no error in your feed. Just that nobody had problem in the past.

**Comment by aledeg** [comment]
Please paste your feed configuration (screenshot for instance). I cannot add it on my instance with the limited information I have.

**Comment by sherlcok314159** [comment]
> Fine. You can try this [feed](https://kexue.fm/feed) with a CSS selector as `#PostContent`. Thanks for the quick response.

Here. Tks!

**Comment by aledeg** [comment]
It's not really a CSP problem. It's how extensions add scripts. Mathjax scripts load other scripts by using their relative paths. That not how extensions work in FreshRSS.
I need to find a way to fix that.

The file html.js is not loaded. I guess that nobody had a problem with that before. I certainly don't.

It's under investigation.

**Comment by aledeg** [comment]
Here is a working example:
![Screen Shot 2024-03-19 at 23 32 51](https://github.com/FreshRSS/FreshRSS/assets/3056148/17690be7-fc59-416e-94d6-9d8f77c17e2a)

The extension works most of the time.

**Comment by sherlcok314159** [comment]
The problem may lie in the loading order. When I use feeds with full-article selector, it almost fails. For instance, this feed is not working either.

<img width="1086" alt="图片" src="https://github.com/FreshRSS/FreshRSS/assets/76043326/67eaca49-56ae-4049-903e-35973cc73084">

The feed is `https://lilianweng.github.io/index.xml` with CSS selector as ".post-single".

**Comment by aledeg** [comment]
@Alkarex Is there a way to alter the CSP from an extension? I can make this extension work but I need to tweak the CSP rules. Thank you

**Comment by sherlcok314159** [comment]
Thanks for your help! If we fail to alter the CSP by an extension, can the user alter the CSP by rewriting the `FreshRSS.php` and replacing the one in the container? For instance,

```yml
    volumes:
      - ./FreshRSS.php:/var/www/FreshRSS/app/FreshRSS.php
 ```

**Comment by Alkarex** [comment]
> can the user alter the CSP

@sherlcok314159 The user way to alter the CSP is at Web server level (e.g. Apache), not at PHP level, which will fail at each FreshRSS update.

@aledeg So far, controllers have access to a method to redefine CSP:

https://github.com/FreshRSS/FreshRSS/blob/b5445e1e56497f8bdc1de35a8325418c44b96d37/lib/Minz/ActionController.php#L75-L95

I have not checked how practical this is for extensions, but that could be extended if needed (I will be with intermittent Internet connectivity the coming two weeks)

**Comment by aledeg** [comment]
Thank you for your answer.
I've seen that method but I can figure out how to use it from an extension. I need to dig a little bit.

**Comment by sherlcok314159** [comment]
Thanks for your help again!!!

**Comment by sherlcok314159** [comment]
Hi, aledeg, any update? Is there anything I can help with? :-)

**Comment by aledeg** [comment]
> Hi, aledeg, any update? Is there anything I can help with? :-)

I did not have time to look into it. But I will.

@Alkarex I think we might need something to interact with the CSP directly from the extension. Probably a hook is a way to go. If you think this is a good idea, I can work on that. If you don't, what do you have in mind? Thank you!

**Comment by Alkarex** [comment]
@aledeg A hook sounds like a possibility, yes. Another approach could be to add a method to the base extension class, if needed.

**Comment by aledeg** [comment]
@sherlcok314159 there is a fix to use the library from a CDN. You need the `edge` branch for FreshRSS and the last release of the extension. Let me know if this works for you.

**Comment by sherlcok314159** [comment]
Hi! I try the edge branch and the latest extension. It did not work.

```yml
services:

  freshrss:
    image: freshrss/freshrss:edge
    # Optional build section if you want to build the image locally:
    # build:
    #   # Pick #latest (stable release) or #edge (rolling release) or a specific release like #1.21.0
    #   context: https://github.com/FreshRSS/FreshRSS.git#edge
    #   dockerfile: Docker/Dockerfile-Alpine
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
```

And the console screenshot is below (edge):

![Snipaste_2024-03-31_14-31-19](https://github.com/FreshRSS/FreshRSS/assets/76043326/88efbb78-4879-4b62-a58f-9fbf37781553)

Here is the screenshot for firefox:

<img width="1014" alt="图片" src="https://github.com/FreshRSS/FreshRSS/assets/76043326/8c79fbb2-e061-4043-a95b-7a3ae0a8b87f">

**Comment by aledeg** [comment]
While I do have some errors, the content is properly modified. See capture
![Screen Shot 2024-03-31 at 07 03 35](https://github.com/FreshRSS/FreshRSS/assets/3056148/7e4922c7-73c9-4a83-98d0-8dd13c75e3d8)

When I am fixing errors, the content disappears. I have no idea why.

**Comment by aledeg** [comment]
![Screen Shot 2024-03-31 at 07 26 55](https://github.com/FreshRSS/FreshRSS/assets/3056148/ef194202-d68b-444f-9e27-839f9a686246)
Same entry when `unsafe-inline` is authorized and there are no more errors. There are a lot of warnings though. All related to styling.

**Comment by Frenzie** [comment]
The LaTeX JS probably requires inline styles to render the math and the CSP rules disable that. I'm not really sure what disabling inline styles is good for at all tbh, but that aside. But what doesn't work about unsafe-inline exactly?

**Comment by aledeg** [comment]
That's the weird thing. When the rules are not authorized it works (see first capture). But it does not work when the rules are authorized (see second capture). I am lost :)

**Comment by sherlcok314159** [comment]
Can we just let the user decide whether to open these CSP rules? If nothing is blocked, things should be fine.

**Comment by sherlcok314159** [comment]
Any update please?

**Comment by math-GH** [comment]
> Can we just let the user decide whether to open these CSP rules? If nothing is blocked, things should be fine.

see https://github.com/FreshRSS/FreshRSS/issues/6437#issuecomment-2097497770

**Comment by sherlcok314159** [comment]
For anyone who wants to display equation well in the freshrss, here are two steps for you:

1. Modify `var/www/FreshRSS/app/layout/layout.phtml` to replace CSP rules. Note that the below rules can be unsafe. Use it carefully.

```
<?php
	declare(strict_types=1);
	/** @var FreshRSS_View $this */
	FreshRSS::preLayout();
	header("Content-Security-Policy: default-src 'self' https: data: 'unsafe-inline' 'unsafe-eval' 'unsafe-hashes'"); 
?>
```

2. I quit using freshrss plugin to solve this. I borrow code from one Tampermonkey script and modify some places for correct font size and equation reference.

```
// ==UserScript==
// @name         MathJax For All
// @namespace    http://tampermonkey.net/
// @version      1.0
// @description  Load MathJax and Polyfills on specified pages
// @author       Apricity
// @match        http*://*/*
// @grant        none
// ==/UserScript==

if (window.MathJax === undefined) {
    var mjscr = document.createElement("script");
    mjscr.type = "text/javascript";
    mjscr.async = true;
    mjscr.src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js";
    mjscr.text = 'MathJax.Hub.Config({extensions:["tex2jax.js"],'+"tex2jax:{inlineMath:[['$','$']]"
        +',skipTags:["script","noscript","pre","code"]},jax:["input/TeX","output/CommonHTML"],CommonHTML: {minScaleAdjust:120},'
        +'TeX:{extensions:["autoload-all.js","noUndefined.js"], equationNumbers: { autoNumber: "AMS" }}'
        +'});MathJax.Hub.Startup.onload();';
    document.getElementsByTagName("head")[0].appendChild(mjscr);

    (new MutationObserver(function(mutationsList, observer) {
        let el = [];
        for (const mutation of mutationsList) {
            const node = mutation.addedNodes.item(0);
            if (node === null || node.nodeType !== 1 || node.className == "MathJax_Preview" || node.id.substring(0,7) == "MathJax" || node.className.substring(0,4) == "mjx-" || node.isContentEditable) break;
            if (node.offsetParent !== null && node.innerText != "") el.push(node);
        }
        if (el.length != 0) MathJax.Hub.Queue(["Typeset", MathJax.Hub,el,{}]);
    })).observe(document,{subtree: true, childList: true});
```

Then, everything is fine.

<img width="987" alt="图片" src="https://github.com/FreshRSS/FreshRSS/assets/76043326/19a11ffd-3d98-4ea9-98d3-54999cf350a5">

**Comment by Frenzie** [comment]
Unsafe is overstating it a bit imho. :-) All `<script>` tags (and much more) are filtered from feeds before database insertion.
