### ISSUE TITLE
[BUG] Install process PHP fatal error

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#6204]
**Describe the bug**
Step 1 in the install process: There is an fatal error at the end of page.
![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/63449327-f6a9-4109-815e-c3a089e71bae)
![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/63b6459f-3b2a-4a2e-b31b-3de7be5957e1)

```
Fatal error:  Uncaught Minz_FileNotExistException: File not found: `.../data/users/_/config.php`
in ...\lib\Minz\Configuration.php:51
Stack trace:
#0 ...\lib\Minz\Configuration.php(122): Minz_Configuration::load('...')
#1 ...\lib\Minz\Configuration.php(35): Minz_Configuration->__construct('user', '...', NULL, NULL)
#2 ...\app\Models\UserConfiguration.php(80): Minz_Configuration::register('user', '...', NULL)
#3 ...\app\install.php(303): FreshRSS_UserConfiguration::init('.....')
#4 ...\app\install.php(478): freshrss_already_installed()
#5 ...\app\install.php(818): printStep1()
#6 ...\p\i\index.php(32): require('...')
#7 {main}
  thrown in ...\lib\Minz\Configuration.php on line 51
```

**Environment information (please complete the following information):**

- FreshRSS version: 1.23.2-dev

**Comment by Alkarex** [comment]
I cannot immediately reproduce. Did you maybe have a partial install before?

**Comment by Alkarex** [comment]
Bug found. It is a regression due to https://github.com/FreshRSS/FreshRSS/pull/5511

**Comment by Alkarex** [comment]
Please try again

**Comment by math-GH** [comment]
Thanks for the quick response.

Tested. It is fixed now.
