### ISSUE TITLE
[BUG] TitleWrap Not working since latest commit

### ISSUE THREAD

**Issue by ampfinger** [FreshRSS/FreshRSS#6207]
**Describe the bug**
Extension TitleWrap on mobile View is not working anymore

**To Reproduce**
1. Show overview of all rss titles
2. Titles are showing completely without line break

**Expected behavior**
Titles are wraped and are showing in multiple lines

**Environment information (please complete the following information):**
- Device: Google Pixel 7
- OS: Android
- Browser: latest Chrome version
- FreshRSS version: latest edge version (pulled yesterday)

**Additional context**
Page was working since March 13th (my instance is updated every night), then it stopped working.
I think it has to do with this commit:

https://github.com/FreshRSS/FreshRSS/commit/c0db581f2b8cf7bcf8aa43b5a51599a56544d864

No other extensions are installed.

**Comment by math-GH** [comment]
@ampfinger Could you please test this fix here? https://github.com/FreshRSS/Extensions/pull/221

**Comment by ampfinger** [comment]
I can confirm this is working!
Thanks for your great work!
