### ISSUE TITLE
Feed items with no title

### ISSUE THREAD

**Issue by thecptrgod** [FreshRSS/FreshRSS#6218]
**Describe the bug**
Feed items that have no title parse with a random string of the URL instead of just displaying the first line of text.  (As far as I know title is not required in the RSS spec.)

**To Reproduce**
Subscribe to a feed that doesn’t have titles for some or all feed items such as scripting.com’s feed. Then look at the feed in the reader.

**Expected behavior**
Ignore the empty title and just put body text in there. 

**Screenshots**
Current behavior:
![IMG_2921](https://github.com/FreshRSS/FreshRSS/assets/46567891/f1d448f0-eeb2-42d6-8f01-7e3c0c6e7db8)

Example of expected behavior (NetNewsWire on iPhone)
![IMG_2920](https://github.com/FreshRSS/FreshRSS/assets/46567891/c2a83506-986e-4d91-b09d-245da3c4ebd5)

**Environment information (please complete the following information):**
FreshRSS running via Docker on a RasPi 400. Accessed either through the web client on Chrome or through NetNewsWire syncing on my phone.

**Comment by Alkarex** [comment]
The fallback for now when there is no title is GUID or URL.
The body can also be blank (quite typical for e.g. image-oriented feeds)

**Comment by math-GH** [comment]
Ref #4946

**Comment by math-GH** [comment]
@thecptrgod How does it look like in FreshRSS? Your screenshots are from a mobile app.

**Comment by thecptrgod** [comment]
> @thecptrgod How does it look like in FreshRSS? Your screenshots are from a mobile app.

![Screenshot_20240322_045541](https://github.com/FreshRSS/FreshRSS/assets/46567891/6b15e0d1-f7ba-44e8-a22b-83d3703934d6)

FreshRSS web

![Screenshot_20240322_045756](https://github.com/FreshRSS/FreshRSS/assets/46567891/6f9dd484-1fff-4992-8b48-20c71a5dbad0)

Feedly for comparison

**Comment by math-GH** [comment]
Feedback to this PR is welcome: #6240
