### ISSUE TITLE
[BUG] Article selector is HTML escaped

### ISSUE THREAD

**Issue by mrnoname1000** [FreshRSS/FreshRSS#6229]
**Describe the bug**
The article CSS selector is being passed to CSSXPath with some characters encoded as XML entities. The selector `[id="main"]` becomes `[id=&quot;main&quot;]` which is converted to `.//*[@id="&quot;main&quot;")]`

**To Reproduce**
1. Input an Article CSS Selector with double quotes
2. Submit due to #6228
3. Click the preview button by the selector
4. CSSXpath has now been passed a mangled selector (I debugged by adding an `error_log` statement to Translator.php)

**Expected behavior**
The selector should be unescaped by the time it reaches CSSXpath.

**Environment information (please complete the following information):**
- Device: ThinkPad A485
- OS: Void Linux
- Browser: Firefox 124.0
- FreshRSS version: 1.23.2-dev 1c0b8a7
- Database version: PostgreSQL 16.2
- PHP version: 8.2.7
- Installation type: Docker self hosted

**Comment by Alkarex** [comment]
Please try https://github.com/FreshRSS/FreshRSS/pull/6426
