### ISSUE TITLE
[BUG] Valid RSS feed fails to load

### ISSUE THREAD

**Issue by JustSid** [FreshRSS/FreshRSS#6233]
**Describe the bug**
The feed for the Chips and Cheese blog used to work for the longest time but recently, about ~3 weeks ago, stopped working. Presumably something happened to the feed, but I don't know how it used to look unfortunately. The w3 validator says the feed is valid, while fresh-rss says `Blast! This feed has encountered a problem. Please verify that it is always reachable then update it.`

**To Reproduce**
1. Subscribe to `https://chipsandcheese.com/feed`
2. That's it.
3. Check [w3 feed validator](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fchipsandcheese.com%2Ffeed)

**Comment by Frenzie** [comment]
It's Cloudflare, see https://github.com/FreshRSS/FreshRSS/issues/5296#issuecomment-1510392559 for potential workarounds.

**Comment by JustSid** [comment]
Of course it is... Thanks a bunch, I really appreciate it.

It'd be nice if fresh-rss would more properly show what issue it encounters, since it wasn't entirely clear why exactly the feed failed.

**Comment by Frenzie** [comment]
Indeed, that error message is overly generic. I always forget about it when I have more time than it takes to just run a quick curl command. :blush:
