### ISSUE TITLE
[Bug] User deleting: notification "User cannot be deleted" 

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#6275]
### Describe the bug

The user "newUser" was deleted by the admin.
But a red notification "User newUser cannot be deleted" is shown.
But the user "newUser" is disappeared from the user list.
![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/a18a894a-fab1-402c-8cee-83fe366362c9)

But the folder "data/newUser" is still available.

![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/f6e438dd-11a2-43ca-a4bc-6f565f55242c)

php_error_log:
```
[08-Apr-2024 16:31:06 Europe/Berlin] PHP Warning:  unlink(.../data\users\newUser/db.sqlite): Resource temporarily unavailable in ...\lib\lib_rss.php on line 892
[08-Apr-2024 16:31:06 Europe/Berlin] PHP Warning:  rmdir(.../data\users\newUser): Directory not empty in ...\lib\lib_rss.php on line 896

```

### To Reproduce

1. Go to 'user management'
2. delete a user

### Expected behavior

If the user cannot be deleted, then I expect to have the account still in the list.

### FreshRSS version

1.23.2-dev (latest)

### Environment information

- Database version: SQLite
- PHP version: PHP8.0
- Installation type: XAMP stack
-Web server type: Apache

**Comment by math-GH** [comment]
same php_error_log entry like #3970

**Comment by Alkarex** [comment]
That is on Windows natively and without using WSL, right?

**Comment by Alkarex** [comment]
Please try https://github.com/FreshRSS/FreshRSS/pull/6285

**Comment by math-GH** [comment]
> That is on Windows natively and without using WSL, right?

yes, it is Win10 with XAMPP natively.

**Comment by math-GH** [comment]
> Please try #6285

Same error as before :/
