### ISSUE TITLE
I cannot launch FreshRSS after initial install on my Synology NAS (used Portainer to build it)

### ISSUE THREAD

**Issue by cleverestx** [FreshRSS/FreshRSS#6293]
### Describe the bug

Error during context user init! when first launching the docker container (after installation).  I've restarted it and deleted the container to re-UP it again. I get the same issue.  

![image](https://github.com/FreshRSS/FreshRSS/assets/28905253/4ef5e40f-67cb-409e-a2c9-67d7d2ed8e7c)

I followed this guide: https://mariushosting.com/how-to-install-freshrss-on-your-synology-nas/

### To Reproduce

Install Portainer (compose)
launching into a local IP:Port to access it.

### Expected behavior

I expect it to launch for the first time.

### FreshRSS version

1.23.1

### Environment information

- Database version: Latest Compose build
- PHP version: Latest Compose build
- Installation type:  Docker-Compose
-Web server type: Using local IP through browser only
- Device: Synology DS1621+
- OS:  DSM 7
- Browser: FireFox, Chrome

### Additional context

My Compose (built via Portainer)

version: "3.9"
services:
  freshrss:
    image: ghcr.io/linuxserver/freshrss:latest
    container_name: FreshRSS
    hostname: freshrss
    mem_limit: 3g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: curl -f http://localhost:80/ || exit 1
    ports:
      - 9009:80
    volumes:
      - /volume1/docker/freshrss:/config:rw
    environment:
      TZ: America/Chicago
      PUID: 1029
      PGID: 101
    restart: on-failure:5

**Comment by math-GH** [comment]
3 days ago another Portainer issue spawned: #6283

**Comment by Alkarex** [comment]
Hello,
* Our official Docker image is https://hub.docker.com/r/freshrss/freshrss (I am not familiar with third-party ones such as Linuxserver, but they do not use the same paths)
* You probably have other logs. Please check your Docker logs in particular.
* I can see you are using a local IP (192.xxx). Did you install successfully using the same address, and don't you plan to use another address (with public IP + DNS + HTTPS)?
* The most likely reasons are related to wrong volumes (bad access rights), or setups changed after install and with wrong information in `data/config.php`

**Comment by cleverestx** [comment]
> * https://hub.docker.com/r/freshrss/freshrss

1. I used this because it's part of this guide; his guides are normally great, but if something is broken I'll be sure to let him know if I can get this working... https://mariushosting.com/synology-install-freshrss-with-portainer/

2. Logs only show one concerning line at the end, "warning: state file /config/log/logrotate.status is world-readable and thus can be locked from other unprivileged users. Skipping lock acquisition..." which I'm not sure why...I have 90 other containers running fine using the same UID and GID.  I restarted it, same error, but now that line is GONE the second time around (still won't load though)

3. I like to use local IP whenever possible, but if FreshRSS requires a RP/internet address I can switch to that? It did seem to install fine, but I just can't get it to launch, it shows the Image logo and then gives that error above each time.

4. This is a fresh install. Nothing was changed file or post-permission wise after the install using the compose via the guide above in Portainer (as a stack), this is the actual compose part:

version: "3.9"
services:
  freshrss:
    image: ghcr.io/linuxserver/freshrss:latest
    container_name: FreshRSS
    hostname: freshrss
    mem_limit: 3g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: curl -f http://localhost:80/ || exit 1
    ports:
      - 9009:80
    volumes:
      - /volume1/docker/freshrss:/config:rw
    environment:
      TZ: America/Chicago
      PUID: 1029
      PGID: 101
    restart: on-failure:5

**I will try to change the image SOURCE as you mentioned and see if it does the same thing. Do you see any other obvious issues in my compose?**

**Comment by cleverestx** [comment]
It suddenly started working today. (HTTP) No idea why.
