### ISSUE TITLE
[Bug] Reading view: Search for an author by clicking on the author name

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#6296]
### Describe the bug

If the user clicks on an author user name (with firstname and family name) the search engine cannot find any results

### To Reproduce

(Screens from demo.freshrss.org)
Click on the author's name:
![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/3f93322f-9667-4c65-8c23-dba55c002a50)

Search engine searches but cannot find any article:
![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/61a86b4b-9030-4f7c-9b66-51f6bc67e9f2)

Search for the first name: it works:
![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/2b97aa8e-45cb-42cb-8df6-5e5f59ba5c3d)

Search for the familiy name: it works:
![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/f0f4b8a8-4252-41a9-a7e6-fd7c66686a8c)

### Expected behavior

minimum expected, that the article is found where the user comes from

### FreshRSS version

1.23.2-dev (latest)

### Environment information

1) demo.freshrss.org
2) XAMPP on Win10 (PHP8.0)

**Comment by Alkarex** [comment]
This exact example https://hacks.mozilla.org/feed/atom/ works for me.
Watch out that you do not have filtered your view like showing only unread articles, or not showing that feed, or something like that. What is the URL you obtain when you click on the author's name?

**Comment by math-GH** [comment]
ahhh. I see.

This bug will just happen if you click on the author's name in the `reading view`.
In the normal view it is fine. The search string includes the quotes there.

![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/e1852bf0-5b7f-42b1-9cc8-c62579e5c02c)

**Comment by math-GH** [comment]
will be fixed with #6289
