### ISSUE TITLE
Use STDOUT instead of STDERR for successful command outputs

### ISSUE THREAD

**Issue by Emporea** [FreshRSS/FreshRSS#6316]
https://github.com/FreshRSS/FreshRSS/blob/0ffcf41f9371b9321856d2c709cf7bcb4f7c3c60/cli/export-opml-for-user.php#L23

Successful command outputs should be sent to STDOUT, not STDERR.

I encountered this problem because a trap ERR command caused a bash script to report an error, even though the opml was successfully exported.

**Comment by Frenzie** [comment]
The output goes to STDOUT, which can be piped etc. That message should not go there. STDERR is for diagnostic messages. Exit status is for exit status.

I'm fairly sure that trap ERR only triggers on a non-zero exit status.

**Comment by Emporea** [comment]
?
`fwrite(STDERR, ...)`? This goes to STDERR.

**Comment by Alkarex** [comment]
This is for consistency with other commands, some of which are meant for piping. This is a diagnostic message, for which STDERR is appropriate.
If you want a comparison with a more standard Linux tool, try to see what comes on STDOUT and STDERR during a:

```sh
curl -v 'https://freshrss.org/'
```

Edit: Just to be clear, STDERR is not only for errors, unlike what the name may lead to believe

**Comment by Frenzie** [comment]
> ?
> `fwrite(STDERR, ...)`? This goes to STDERR.

Yes, and *that's not output*.

**Comment by Emporea** [comment]
Ok lesson learned. Thanks for the clarification. 
So the better approach to catching only "real" errors is to look only at exit codes instead of monitoring STDERR?

**Comment by Emporea** [comment]
Closing as not directly an issue of freshrss.

**Comment by Frenzie** [comment]
> Ok lesson learned. So the better approach to only catch "real errors" is by only looking at the exit codes instead of monitoring STDERR?

That's right, but as stated that's what trap ERR already does.


```sh
#!/bin/bash

cleanup() {
    echo "trappity trap cleanup"
}

trap cleanup ERR

echo "This command will succeed"
ls / 

>&2 echo "This command outputs to STDERR"

echo "This command will fail"
ls /nonexistentdirectory

>&2 echo "This command also outputs to STDERR"
```

```
# everything
$ bash bla.sh 
This command will succeed
bin  bin.usr-is-merged  boot  cdrom  dev  etc  home  lib  lib32  lib64  lib.usr-is-merged  libx32  lost+found  media  mnt  opt  proc  root  run  sbin  sbin.usr-is-merged  snap  srv  swapfile  sys  tmp  usr  var
This command outputs to STDERR
This command will fail
ls: cannot access '/nonexistentdirectory': No such file or directory
trappity trap cleanup
This command also outputs to STDERR
```

```
# hide STDERR
$ bash bla.sh 2>/dev/null
This command will succeed
bin  bin.usr-is-merged  boot  cdrom  dev  etc  home  lib  lib32  lib64  lib.usr-is-merged  libx32  lost+found  media  mnt  opt  proc  root  run  sbin  sbin.usr-is-merged  snap  srv  swapfile  sys  tmp  usr  var
This command will fail
trappity trap cleanup
```

```
# hide STDOUT
$ bash bla.sh 1>/dev/null
This command outputs to STDERR
ls: cannot access '/nonexistentdirectory': No such file or directory
This command also outputs to STDERR
```
