### ISSUE TITLE
[i18n] Translation Italian (IT) 🇮🇹 needs translators

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#6323]
Dear FreshRSS-Community,

please help us to improve our Italian translations.

While the core developer and many other contributors develop our [FreshRSS ](https://freshrss.org/) app we cannot support the translations in all 20+ languages. 

## Actual Status
Right now about 90% of our text is translated into Italian.

## How to support us
How to do it:
1) it is very simple
2) all files are stored in `https://github.com/FreshRSS/FreshRSS/tree/edge/app/i18n/it` ([Link](https://github.com/FreshRSS/FreshRSS/tree/edge/app/i18n/it))
3) each untranslated text has an inline comment `//  TODO`
4) When the text is translated, just delete the comment
5) If the English term fits as well, please change the comment from `//  TODO` to `//  IGNORE`
6) open a Pull Request and link to this ticket

## Thanks
Thanks a lot. It will help our very international community of users and developers. Your submitted PRs will be published with our next release version [1.24.0](https://github.com/FreshRSS/FreshRSS/milestones) or later

**Comment by math-GH** [comment]
Ping @marcomrc @giannidsp @Pyr0x1 @loviuz
Could you assist us once more with translating this into Italian?
Potresti aiutarci ancora una volta con la traduzione in italiano?

**Comment by loviuz** [comment]
Just translated :-)

It could be useful to receive notification, just as transifex.com or similar services. Otherwise, I cannot keep updated when you will need new translations, or you could tag me in the future, just like now ;-)

**Comment by Frenzie** [comment]
@Alkarex We should be able to apply for Weblate for such a purpose, see https://docs.weblate.org/en/latest/formats/php.html

Though note that https://github.com/koreader/koreader-translations is a separate repo due to the enormous number of commits. (But I think that should be less of an issue here.)

**Comment by Alkarex** [comment]
Let's discuss that in another issue but yes, we might be able to improve the process. Meanwhile, tagging potential translators once in a while when relevant has worked ok

**Comment by math-GH** [comment]
In a while there are some new untranslated phrases added. It would be nice to have it in Italian too :)

**Comment by Pyr0x1** [comment]
> In a while there are some new untranslated phrases added. It would be nice to have it in Italian too :)

Sure 😊
