### ISSUE TITLE
[i18n] Translation Turkish (TR) 🇹🇷 needs translators

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#6325]
Dear FreshRSS-Community,

please help us to improve our Turkish translations.

While the core developer and many other contributors develop our [FreshRSS ](https://freshrss.org/) app we cannot support the translations in all 20+ languages. 

## Actual Status
Right now about 90% of our text is translated into Turkish.

## How to support us
How to do it:
1) it is very simple
2) all files are stored in `https://github.com/FreshRSS/FreshRSS/tree/edge/app/i18n/tr` ([Link](https://github.com/FreshRSS/FreshRSS/tree/edge/app/i18n/tr))
3) each untranslated text has an inline comment `//  TODO`
4) When the text is translated, just delete the comment
5) If the English term fits as well, please change the comment from `//  TODO` to `//  IGNORE`
6) open a Pull Request and link to this ticket

## Thanks
Thanks a lot. It will help our very international community of users and developers. Your submitted PRs will be published with our next release version [1.24.0](https://github.com/FreshRSS/FreshRSS/milestones) or later

**Comment by math-GH** [comment]
Ping @hckweb @CilgaIscan
Could you assist us once more with translating this into Turkish?
Bunu Türkçeye çevirmemizde bize bir kez daha yardımcı olabilir misiniz?

**Comment by CilgaIscan** [comment]
> Ping @hckweb @CilgaIscan Could you assist us once more with translating this into Turkish? Bunu Türkçeye çevirmemizde bize bir kez daha yardımcı olabilir misiniz?

I can help
