### ISSUE TITLE
Apply *mark as read* to updated articles too

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#6331]
### Discussed in https://github.com/FreshRSS/FreshRSS/discussions/6330

<div type='discussions-op-text'>

<sup>Originally posted by **hkcomori** April 18, 2024</sup>
When 'Mark updated articles as unread' triggered, the filter action is not applied.
In my usecase, I set it for articles not wanted to see, so I expect only articles that were not filtered to be unread.

How about your use cases?</div>

**Comment by Alkarex** [comment]
@hkcomori Would you be able to test https://github.com/FreshRSS/FreshRSS/pull/6334 ?

**Comment by hkcomori** [comment]
It worked fine. Thank you!
