### ISSUE TITLE
[Bug] User Queries: different displays - depends on selecting main stream or not

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#6360]
### Describe the bug

While trying to reproduce #5674 I found following bug:

main stream selected: user query box is "empty" (`no filter`)
![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/a660cfbc-9d23-4f45-a462-8a79331e71b9)

selecting another stream: user query box lists the parameters
![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/7be7e7e9-a9e0-4473-a602-6d16429a3619)

### To Reproduce

1. Go to User Queries
2. chose the type
3. submit
4. see the box in the user queries overview page

### Expected behavior

minimum the `expression` is listed in the overview.

`no filter` message only if nothing is selected like this example (screen shot from demo.freshrss.org, that has an older version than the current 1.23.2-dev):
![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/95031144-0c05-415c-bbb2-28158d6cd841)

### FreshRSS version

1.23.2-dev (latest)

### Environment information

- Database version: SQLite
- PHP version: PHP 8.0

**Comment by Alkarex** [comment]
Could you try https://github.com/FreshRSS/FreshRSS/pull/6421 @math-GH ?
