### ISSUE TITLE
youtube video cannot open youtube website

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#638]
Hi, 

I would to raise this bug about youtube embedded video in freshrss.
Video can be played well in freshrss but when you click on a youtube video title that is supposed to bring you on the youtube website, but instead the video just disapears from the article.

thanks.

**Comment by Alkarex** [comment]
Rewrite URLs to use HTTPS for known services https://github.com/FreshRSS/FreshRSS/issues/1083

**Comment by Alkarex** [comment]
Please check again /dev after https://github.com/FreshRSS/FreshRSS/issues/1087 and reopen if still needed
