### ISSUE TITLE
native apps list: News+ is very out of time

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#6382]
News+ repository: https://github.com/noinnion/newsplus/

(Last code commit was 10 years ago. The repo seems to be unmaintained. See https://github.com/noinnion/newsplus/issues/107 too)

The [website](https://noinnion.com/newsplus/) itself is unusable, so I guess nobody is maintaining this.

I would suggest to be honest to the reader of our native apps list. We should not have this app on row number 1 on our list anymore.

**Comment by Frenzie** [comment]
That seems fair.

**Comment by Alkarex** [comment]
Yes, we need to update the list.
I have been using News+ until a few weeks ago when I changed my 7-year old phone (I keep my devices for a long time). It can still be installed and work perfectly fine on Android devices as long as they are not using an Android version that is too new (I believe Android 14 is the version that introduces a voluntary break of older apps, even when they work).
For newer devices, it requires development mode to be installed.
The reason I kept News+ as number one is that so far, I am not aware of any other app that ticks all the boxes when it comes to FreshRSS features: offline, favourites, user labels, fast sync even with many unread articles. So as of today, it is still to me the best app (I have it on my tablet).
Ideally, I would like to promote another app, but I am not sure which. It would be great to make a new test of the main candidates, using a clear methodology.

**Comment by daffydock** [comment]
As a side note, exchanged a couple of quick words with the Dev for Readrops, and he is doing a rewrite of his app. It won't be ready for a few months unless something else changes, but hey, just putting that here as a heads up for when that happens. 

The current app works but it lacks some bells and whistles.   

Back to topic, too bad about News+ I had tried it on my old Android 7.0 phone and it worked well enough.

**Comment by Alkarex** [comment]
Good to know regarding have Readrops 👍🏻 Related: https://github.com/readrops/Readrops/issues/54

**Comment by positiveque** [comment]
I am currently using [**ReadYou**](https://github.com/Ashinch/ReadYou) for Android 14 and I must say it works really well. Also, it has a beautiful design which is a bonus.

**Comment by Alkarex** [comment]
@positiveque Yes, although ReadYou is lacking support for labels https://github.com/Ashinch/ReadYou/issues/546

**Comment by Alkarex** [comment]
New Android client https://github.com/jocmp/capyreader

Edit:
* [X] https://github.com/jocmp/capyreader/discussions/492
* [ ] https://github.com/jocmp/capyreader/discussions/531
* [ ] https://github.com/jocmp/capyreader/discussions/532
* [ ] https://github.com/jocmp/capyreader/discussions/533

**Comment by Alkarex** [comment]
Let's resume here. Help welcome: please write some comments about the app(s) you are using or have tested.
I have just tested CapyReader, which despite being the newest seems to also be one of the best and with missing features such as user labels coming https://github.com/jocmp/capyreader/discussions/492#discussioncomment-11323467

**Comment by Frenzie** [comment]
I don't understand capyreader. It's asking for an email+password?

**Comment by Alkarex** [comment]
> I don't understand capyreader. It's asking for an email+password?

Just put your FreshRSS username

**Comment by Frenzie** [comment]
I did, but the first time I tried it gave an error. Now it worked.

**Comment by Alkarex** [comment]
List of Android clients updated in https://github.com/FreshRSS/FreshRSS/pull/7034
Help welcome to test the apps some more.

In particular, we need to do a round of updates for Apple / iOS apps (I have no hardware for that) (see also https://github.com/FreshRSS/FreshRSS/issues/6941) and for Linux and Windows apps.
Help welcome!
