### ISSUE TITLE
[Bug] The use of "(" mark as a filter for articles as read, filters everything

### ISSUE THREAD

**Issue by beerisgood** [FreshRSS/FreshRSS#6386]
### Describe the bug

For most feeds, I use various words as filters for articles that do not interest me.
I enter each word individually in a line - as according to the documentation.

However, if I now use filters like "(Google", all articles will be filtered, even if they do not contain a "(" or also not "Google" in the name.

With "[Google" there is no problem.

### To Reproduce

1. Go to 'feed'
2. Click on 'manage feed'
3. Scroll down to 'filter actions'
4. add '(Test' to "mark article as read" part
5. scroll a little bit down to archive and clear all articles
6. scroll to bottom and reload articles
7. all articles from that feed are marked as read

### Expected behavior

Only articles with specific filter words should be marked as read

### FreshRSS version

1.23.1

### Environment information

- PHP version: [8.3.6]
- Installation type: [manual via zip archive]
- Uberspace v7

### Additional context

used installation guide: https://lab.uberspace.de/guide_freshrss/

**Comment by Alkarex** [comment]
The parenthesis is a special character in search expressions, meant to be used like `this OR (that there)`.
To be used without this special meaning, they need to be escaped like `\(something`
We do not have at the moment any search expression validation with a UI (but neither has e.g. Google Search).

**Comment by beerisgood** [comment]
Thanks. This solved it.
