### ISSUE TITLE
[Bug] File Zip from Export is corrupted

### ISSUE THREAD

**Issue by Machou** [FreshRSS/FreshRSS#6388]
### Describe the bug

When i export my RSS, the file Zip is corrupted.

Like:

![](https://i.ibb.co/99bJvrC/Sans-titre.png)

### To Reproduce

My Abo > Import / Export > Export (all)

Export the file Zip

### FreshRSS version

1.23.1

### Environment information

- Database version: SQLite
- PHP version: PHP 8.3
- Installation type: Docker image source
- Web server type: Apache
- OS: Debian
- Browser: Firefox 125

**Comment by math-GH** [comment]
I can reproduce it with 1.23.2-dev. No log warnings, just this notice in php_error_log:
`[27-Apr-2024 18:51:21 Europe/Berlin] PHP Notice:  tempnam(): file created in the system's temporary directory in ...\app\Services\ExportService.php on line 157`
The size of the ZIP looks correct (in my case: 114KB)

SQLite, PHP8.0

**Comment by math-GH** [comment]
Strange. Same happens with `1.22.0` and `1.23.0` on my setup too

**Comment by Machou** [comment]
> I can reproduce it with 1.23.2-dev. No log warnings, just this notice in php_error_log: `[27-Apr-2024 18:51:21 Europe/Berlin] PHP Notice: tempnam(): file created in the system's temporary directory in ...\app\Services\ExportService.php on line 157` The size of the ZIP looks correct (in my case: 114KB)
> 
> SQLite, PHP8.0

Exactly :) thx for error log !

**Comment by Alkarex** [comment]
I cannot reproduce any problem on my side. Can you open the ZIP file with something else such as 7-zip? When opening the ZIP file in a text editor, is there any string indicating an error / warning?

**Comment by Alkarex** [comment]
We had a similar issue, which was fixed a long time ago https://github.com/FreshRSS/FreshRSS/pull/2134

**Comment by math-GH** [comment]
On my web server it works fine (current edge). Linux, MariaDB, PHP8.1(?)

**Comment by math-GH** [comment]
> I cannot reproduce any problem on my side. Can you open the ZIP file with something else such as 7-zip? When opening the ZIP file in a text editor, is there any string indicating an error / warning?

Windows10 default ZIP tool cannot open it neither. 

Did you test it with SQlite too?

**Comment by Alkarex** [comment]
Can you try with https://github.com/FreshRSS/FreshRSS/pull/6392

**Comment by Alkarex** [comment]
Yes, I tested with SQLite.
When opening the ZIP file in a text editor, is there any string indicating an error / warning?

**Comment by math-GH** [comment]
> Yes, I tested with SQLite. When opening the ZIP file in a text editor, is there any string indicating an error / warning?

yes, it is. (Sorry, forget to do it). There is the PHP notice as mentioned above
