### ISSUE TITLE
[Bug] Muted feeds

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#6407]
### Describe the bug

If a feed is muted
![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/9b41db61-f372-47d3-aa93-e7170f21c14d)

and the user choose the "update feed" menu entry
![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/2b8120de-205f-4917-a9fb-015e7903d486)

The message is not correct
![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/de4397b5-5e58-47ce-aeb2-402626a82224)

### To Reproduce

1. mute a feed
2. wait some time (till next article is available)
3. click "update feeds" in the sub menu
4. see the message
5. no new article is listed

### Expected behavior

A) "update feeds" should not be there. (let's discuss what is expected to be there)
B) the notification message should say, that the feed is muted and cannot be updated
C) maybe it will be possible to update muted feeds manually

### FreshRSS version

1.23.2-dev (latest)

### Environment information

- Database version:  SQLite
- PHP version: PHP 8.0

**Comment by math-GH** [comment]
double check:

Feed unmuted
![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/b15f757a-937e-4fda-b324-c96d944e81c0)

and updated. It has new articles
![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/e5fecc81-a9e9-448c-a0dd-7b8807d8ad0f)

**Comment by Alkarex** [comment]
The easiest might be to allow an explicit manual update even on muted feeds

**Comment by Frenzie** [comment]
That also makes the most sense regardless if it's easy. When you click update I imagine you expect it to update, not to go through some weird "unmute, update, mute" dance.

**Comment by Alkarex** [comment]
Untested: could you give a try to https://github.com/FreshRSS/FreshRSS/pull/6408 @math-GH ?
