### ISSUE TITLE
[Feature] Being able to add an icon for each feed category

### ISSUE THREAD

**Issue by Fluidetom** [FreshRSS/FreshRSS#6425]
**Describe the solution you’d like**
I'm using a self-hosted instance of FreshRSS on my Synology NAS in a container.
I've been converting more and more of my friends and co-workers to ditch their social media addiction and "go back to the basics" ... RSS ;-)

One small cosmetic improvement idea that came up, is the possibility to add an icon in front of a category name.
This would make the navigation easier when dealing with multiple categories.

This idea came up when one of my friends showed me an online shared bookmarks manager called raindrop.io.
Bookmarks can be organised in different categories, a little bit like in FreshRSS with feeds.

This is a screenshot of our shared raindrop.io account.
I find the colourful icons really a plus in terms of ease of navigation.

Would be great if this kind of feature could be integrated in FreshRSS too.

Thanks in advance for that, and thanks already for all your hard work on FreshRSS.
This is much much appreciated.

![FR-Icons](https://github.com/FreshRSS/FreshRSS/assets/87716809/35b4200b-39ee-44ee-adc9-f667311424e3)

**Comment by math-GH** [comment]
A first workaround could be to use UTF8 icons as first character of your category name.

🌹 Garden
⚽Soccer
⛅Weather

**Comment by Fluidetom** [comment]
> A first workaround could be to use UTF8 icons as first character of your category name.
> 
> 🌹 Garden ⚽Soccer ⛅Weather

Hi,

Thanks for the reply.
Yes indeed, that works, thanks !
But it seems to mess the alphabetic sorting order.

![2024-05-02_21-48](https://github.com/FreshRSS/FreshRSS/assets/87716809/0205b3bb-ae88-46a0-9a1f-bb13de8ebb83)

So I'll have to come up with something smart.
Like "Green" could be named **G - "UTF-8 icon" Green** and "News" would be "**N - UTF-8 icon News**".
So this would keep the alphabetical order while allowing to add more categories in the future.

This works for me as a workaround for the moment

**Comment by math-GH** [comment]
`display position` is made for manual order :)

![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/4141f605-ff94-4eca-886a-2b2a7c86bdaf)

**Comment by Alkarex** [comment]
You can override the sorting position of the categories in their settings
