### ISSUE TITLE
Small issues on NOrd Theme

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/FreshRSS#6429]
### Describe the bug

1/ There is a strange padding at the end of each category:
<img width="227" alt="chrome_rIUryLewQ6" src="https://github.com/FreshRSS/FreshRSS/assets/7189936/dd36b320-157b-463f-a1ef-30c8b092ea29">

2/ When you click on a cogwheel, either the one for the menu at top right, or one to configure a feed in the feed list, or the arrow right to "Mark as read", all colours change. I understand the logic of it, you often have a dimmed background when opening another windows at the foreground, but it feels off in this case or at least in the way it currently is, you can't distinguish the two states, really, you just see colours changing.
Not clicked:
<img width="312" alt="chrome_WZJ6NivZOw" src="https://github.com/FreshRSS/FreshRSS/assets/7189936/76b10f4c-d9af-4d29-9938-9b9dc1459629">
Clicked:
<img width="266" alt="chrome_j9moMASKcJ" src="https://github.com/FreshRSS/FreshRSS/assets/7189936/bf4c8ae9-bc97-47c3-978d-799c45af724c">

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

### FreshRSS version

edge

### Environment information

Database version: MariaDB 10.11
PHP version: PHP 8.2
Installation type: git
-Web server type: Apache
Device: Laptop
OS: Win11
Browser: Chrome 124

**Comment by math-GH** [comment]
1) it is the color of the scrolling bar. The track and the handle have the same colors as used in the side menu. I would say that choosing a color is a question of taste.

The used CSS variables:
```
--frss-scrollbar-handle: #0002;
--frss-scrollbar-handle-hover: var(--nord1-polarnight);
--frss-scrollbar-track: transparent;
--frss-scrollbar-track-hover: transparent;
```

If you want you can optimize it as you want with the CustomCSS extension. Maybe you want to share your improvement too, so we could discuss to take over.

2) I do not understand your described issue or cannot reproduce it.
How it looks like for me (Firefox on Win10):
![sub-mngmt-button-nord-theme](https://github.com/FreshRSS/FreshRSS/assets/1645099/98d58c0f-4551-4961-a9e2-613f40231428)

**Comment by Alwaysin** [comment]
1/ I'm talking about padding at the bottom, not colors.

<img width="182" alt="image" src="https://github.com/FreshRSS/FreshRSS/assets/7189936/52b3401c-56bd-47a1-b863-fe52d501b024">

2/ I'm talking about colors of the whole page, the whole background, not colors of "Subscription management" when hovered/clicked. Please do as described: click on the cogwheel on top right, you will see the whole page changing colours.

**Comment by math-GH** [comment]
Ah ok. Thanks for clarification.

Both thinks works as intended.

1) The paddings gives some space to the next category.

The CSS code, that you could change with the CustomCSS extension:
```
aside_feed .tree-folder-items.active {
  padding-bottom: 2rem;
}
```

2) it is a CSS `backdrop-filter` that grays out the inactive area. It brings the opened dropdown menu in focus.
The CSS-Code:

```
.dropdown-close {
  backdrop-filter: grayscale(25%) brightness(0.9);
}
```

This resets the backdrop-filter

```
.dropdown-close {
  backdrop-filter: none;
}
```

**Comment by Alwaysin** [comment]
Thank you for the hints to changes in the CSS to make it behave more like I was seeing it!

> It brings the opened dropdown menu in focus.


That's the intended effect yes, but in practice it does not work because we are unable to tell apart the two states, it is just confusing to see colours changing slightly.
In the end, I agree it is essentially personal preferences so I'm closing this.

**Comment by math-GH** [comment]
Please feel free to give feedback and improvement ideas
