### ISSUE TITLE
[Bug] Filter for keywords with quotes not working

### ISSUE THREAD

**Issue by nousernameavailableanymore** [FreshRSS/FreshRSS#6432]
### Describe the bug

I have set up a filter like this:
'"name of TV show"'
intitle: '"name of TV show"'

The TV show is always referred to with those double quotes, as without the double quotes it would be a normal term that could be used in other context which I do not want to filter out.
So I only want to filter the search term when it appears in double quotes (signalling that the TV show is referenced, not the "normal" use of the words).

However, despite the filter, articles with that search term are still shown in my feed.

(also: how do you filter TV shows that already contain a single quote like "Let's Dance"?)

### To Reproduce

-

### FreshRSS version

1.23.1 

### Environment information

- Database version: SQLite
- Installation type: Docker

**Comment by Alkarex** [comment]
Try escaping the double-quotes like `\"`

**Comment by nousernameavailableanymore** [comment]
> Try escaping the double-quotes like `\"`

That also did not work.

![image](https://github.com/FreshRSS/FreshRSS/assets/45376324/0bd562f4-de32-4990-a552-ed01fd11cc14)

**Comment by Alkarex** [comment]
Sorry, the syntax supposed to work is `intitle:'"name of TV show"'` but watch out, without space after the colon.
If it does not work, please provide a link to the feed to ease testing.

**Comment by nousernameavailableanymore** [comment]
> Sorry, the syntax supposed to work is `intitle:'"name of TV show"'` but watch out, without space after the colon. If it does not work, please provide a link to the feed to ease testing.

This is what I used at first and did not work, which is why I opened this request here.
An affected feed-URL is for example this one:
https://www.n-tv.de/rss


As a side question: when just filtering for a keyword like:
'keyword'
this filter does NOT seem to apply when the keyword is in the title.
So I had to add two lines for each entry, one with `'keyword'` and a second one with `intitle:'keyword'`.
Is this intended or should `'keyword'` also filter for the keyword in the title?

**Comment by Alkarex** [comment]
`'keyword'` is also supposed to apply to the title, so if that does not work, this is another bug

**Comment by nousernameavailableanymore** [comment]
> `'keyword'` is also supposed to apply to the title, so if that does not work, this is another bug

Thank you for the clarification.
I need to test this again. Could be that I confused it with this issue here.

You added this to 1.25. Have you been able to confirm / reproduce the behavior with the quotes or find out what the issue was?

**Comment by Alkarex** [comment]
Several fixes and improvements have been made to the search functions in the `edge` rolling release. If you are around, please give it a try and report whether there is any remaining bug

**Comment by Alkarex** [comment]
Seems to work fine for me in `edge`
