### ISSUE TITLE
[Bug] CustomJS can not bypass content-security rules

### ISSUE THREAD

**Issue by sherlcok314159** [FreshRSS/FreshRSS#6437]
### Describe the bug

When I use CustomJS with the following js, console just throws errors: Content-Security-Policy：it breaks：“default-src 'nonce-f23caecacc0f410df2bd0ab02c15a3b8' 'self'”，此页面来自 https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/tex-chtml-full.js 的脚本（script-src-elem）无法执行

```js
// 独立JavaScript文件内容
const mathJaxConfig = {
    loader: {
      load: ['[tex]/boldsymbol']
    },
    tex: {
      tags: "all",
      inlineMath: [['$','$'], ['\\(','\\)']],
      displayMath: [['$$','$$']],
      processEscapes: true,
      processEnvironments: true,
      packages: {
        '[+]': ['boldsymbol']
      }
    }
  };
  
  // 确保在全局作用域中设置MathJax配置
  window.MathJax = mathJaxConfig;
  
  // 接下来，你需要引入MathJax库，这可以通过动态创建一个<script>标签来实现
  (function() {
    var script = document.createElement('script');
    script.src = 'https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/tex-chtml-full.js';
    script.integrity = 'sha256-kbAFUDxdHwlYv01zraGjvjNZayxKtdoiJ38bDTFJtaQ=';
    script.crossorigin = 'anonymous';
    document.head.appendChild(script);
  })();
```

### To Reproduce

Just do as the above.

### FreshRSS version

latest

### Environment information

    Device: MacOS
    OS: Ubuntu 20.04
    Browser: Firefox / Edge
    FreshRSS version: 1.23.1
    PHP version: 8.2.7
    Installation type: Docker-compose

**Comment by math-GH** [comment]
It is not a bug, it is a security feature ;)

You could integrate the JS file into your extension, so the JS file is stored on your server. Than everything is fine and will work

**Comment by Alkarex** [comment]
Another possibility is to override the CSP HTTP headers at Web server or proxy level.
E.g. for Apache https://httpd.apache.org/docs/trunk/en/mod/mod_headers.html#header

See related discussions such as
* https://github.com/FreshRSS/FreshRSS/issues/1075#issuecomment-832338116
* https://github.com/FreshRSS/FreshRSS/issues/3594#issuecomment-841880341
* https://github.com/FreshRSS/FreshRSS/discussions/4348#discussioncomment-2705733
