### ISSUE TITLE
[Bug] Export Import OPML file: PROXY_TYPE is not imported

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#6438]
### Describe the bug

Export - Import feed settings via OPML lose the proxy address.

### To Reproduce

Feed settings. Have a proxy with protocol and address.
![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/79960367-e5b2-45cc-b79c-d38e16f0b8bf)

Export it via OPML file.

`frss:CURLOPT_PROXYTYPE` is in the OPML file

![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/8de3f79e-ccae-4426-a8c3-de5543b837db)

Import this OPML file (before: delete to feed, so that you can import it again)

Address is given, but the protocol is lost:
![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/3ae1ec30-e2e7-4ece-aed8-23e97b543983)

save the settings via `save` button.

Address is lost too, because the protocol select list was empty

![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/0626ee5a-b278-41e6-8cdb-c5201b8e90df)

### Expected behavior

after import: proxy address is restored

### FreshRSS version

1.23.2-dev (latest)

### Environment information

- Database version: SQLite
- PHP version: PHP 8.0

**Comment by Alkarex** [comment]
Please try https://github.com/FreshRSS/FreshRSS/pull/6439 (untested)
