### ISSUE TITLE
[Bug] Importing from InoReader, seeing errors on certain feeds

### ISSUE THREAD

**Issue by riverofjanuary** [FreshRSS/FreshRSS#6440]
### Describe the bug

Thanks for this fabulous software, was able to quickly install and setup based on instructions.  I exported an OPML file from InoReader and exported into the newest version of FreshRSS.  Most thing went through but some things did not.  Here are some logging notes:

[Wed, 08 May 2024 17:02:51 +0000] [warning] --- A feed could not be found at `https://www.lrb.co.uk/feeds/rss`; the status code is `200` and content-type is `xml` [https://www.lrb.co.uk/feeds/rss]

[Wed, 08 May 2024 17:02:51 +0000] [warning] --- JSON not found for WebSub: https://www.elsalvadorperspectives.com/feeds/posts/default

### To Reproduce

Imported an OPML

### Expected behavior

In InoReader these two (among others) work fine. But in FreshRSS they don't work. Any thoughts on how to mitigate/fix?

### FreshRSS version

1.23.1

### Environment information

- Database version: [MariaDB]
- PHP version: [PHP 8.2]
- Installation type: [git]
-Web server type: [Apache]

### Additional context

I also see an error 'icon' next to these category, but there is no hover or information to this icon, so I'm assuming what I've pasted is the issue, and could not find an explanation in any documentation so help here would be great. 
![image](https://github.com/FreshRSS/FreshRSS/assets/1587594/79d028ab-befe-44bb-be1e-0389cb66e5f1)

**Comment by math-GH** [comment]
> [Wed, 08 May 2024 17:02:51 +0000] [warning] --- A feed could not be found at `https://www.lrb.co.uk/feeds/rss`; the status code is `200` and content-type is `xml` [https://www.lrb.co.uk/feeds/rss]

Please check the feeds via https://validator.w3.org/feed/
In this case: the servers delivers the feed as plain text and not as xml (media type is wrong).

You could try to add this feed manually while adding `#force_feed` at the end of the URL

**Comment by math-GH** [comment]
> [Wed, 08 May 2024 17:02:51 +0000] [warning] --- JSON not found for WebSub: https://www.elsalvadorperspectives.com/feeds/posts/default

I can add this feed manually on current edge (1.23.2-dev). I do not know if it would work on 1.23.1

If there are some troubles, please check corresponding feed with the W3C validator (see link above) and add the feed manually to your freshrss instance. If it does not work try to add `#force_feed`, it can overrule some incompatibilities. 

If this does not work, then check the logs.

**Comment by riverofjanuary** [comment]
I see thank you. Yes it seems like the error ones are all not valid feeds. How come Inoreader was able to read them (and then export them)? The #force_feed didn't work unfortunately.

**Comment by math-GH** [comment]
> I also see an error 'icon' next to these category, but there is no hover or information to this icon, so I'm assuming what I've pasted is the issue, and could not find an explanation in any documentation so help here would be great. ![image](https://private-user-images.githubusercontent.com/1587594/328978700-79d028ab-befe-44bb-be1e-0389cb66e5f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxODk2MTksIm5iZiI6MTcxNTE4OTMxOSwicGF0aCI6Ii8xNTg3NTk0LzMyODk3ODcwMC03OWQwMjhhYi1iZWZlLTQ0YmItYmUxZS0wMzg5Y2I2NmU1ZjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDhUMTcyODM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDBjZjgwZTlkZjBlN2VhOTQ4NTQ3MjFmODYyYTliNDgyMzQzY2IxZjVmZjFiYjA0YTViYTA1NDNjMzVhMGFhYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.oAl2GAibjAqYKyKrq8t7rWfoSboKKBTYxAEWEgIn4rY)

This red icon marks the category. When you expand the category the corresponding feed will be marked as well with an red icon. In the feeds settings you can see the issue.

**Comment by math-GH** [comment]
> I see thank you. Yes it seems like the error ones are all not valid feeds. How come Inoreader was able to read them (and then export them)? The #force_feed didn't work unfortunately.

Different software handles errors differently ;)

**Comment by math-GH** [comment]
> I see thank you. Yes it seems like the error ones are all not valid feeds. How come Inoreader was able to read them (and then export them)? The #force_feed didn't work unfortunately.

for me it worked (on 1.23.2-dev) `https://www.lrb.co.uk/feeds/rss#force_feed`

**Comment by riverofjanuary** [comment]
Ah! Its complicated but force_feed did work! I had to:

1. Update the Feed URL and click Submit
2. Go down to the bottom and click Clear Cache
3. I still saw an error, so in the reader view, had to click the gear and click Update Feed

That worked! Just a confusing set of things; as each step above should theoretically clear cache and try to "help" user. Thank you!

**Comment by riverofjanuary** [comment]
But there are other errors with other feeds. Here's one that [returns as valid](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fpaddlingmag.com%2Frss): https://paddlingmag.com/rss

But I get an error when importing (both with and without force_feed)

```
[Wed, 08 May 2024 17:41:15 +0000] [warning] --- A feed could not be found at `https://paddlingmag.com/rss`. This does not appear to be a valid RSS or Atom feed. [https://paddlingmag.com/rss#force_feed]
[Wed, 08 May 2024 17:41:25 +0000] [warning] --- Unknown error for feed [https://paddlingmag.com/rss#force_feed]
```

**Comment by math-GH** [comment]
> But there are other errors with other feeds. Here's one that [returns as valid](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fpaddlingmag.com%2Frss): https://paddlingmag.com/rss
> 
> But I get an error when importing (both with and without force_feed)
> 
> ```
> [Wed, 08 May 2024 17:41:15 +0000] [warning] --- A feed could not be found at `https://paddlingmag.com/rss`. This does not appear to be a valid RSS or Atom feed. [https://paddlingmag.com/rss#force_feed]
> [Wed, 08 May 2024 17:41:25 +0000] [warning] --- Unknown error for feed [https://paddlingmag.com/rss#force_feed]
> ```

strange. The W3C validator says that it is valid. But it is very broken. I cannot add open this feed with another feed reader that I use. Under the hood of FreshRSS the library SimplePie is doing a lot of feed fetching. It cannot read the feed. See: https://simplepie.org/demo/?feed=https%3A%2F%2Fpaddlingmag.com%2Frss

The error from another used RSS reader (sorry for the German text, but says the same as SimplePie):
![grafik](https://github.com/FreshRSS/FreshRSS/assets/1645099/84c014ce-7d82-46ef-9101-4d899c05ad6f)


SimplePie error
`https://paddlingmag.com/rss is invalid XML, likely due to invalid characters. XML error: Mismatched tag at line 3, column 96`

**Comment by riverofjanuary** [comment]
OK got it, thanks. It looks like Inoreader basically does some 'hacking' behind the scenes to make invalid feeds valid by specialized cases. I'll keep trying on my end. Thank you for an excellent free product.

**Comment by math-GH** [comment]
I will close this ticket. If any question left, you could write here. The ticket is not locked.
