### ISSUE TITLE
[Feature] Some sites block scraping content without javascript.

### ISSUE THREAD

**Issue by sherlcok314159** [FreshRSS/FreshRSS#6447]
Some sites can not be scraped without javascript. And I tried different useragents such as curl/8.21. All the useragents failed.

Site: https://rsshub.app/zhubai/posts/havefun

**Comment by Alkarex** [comment]
You can try with https://github.com/lwthiker/curl-impersonate/ , which sometimes help.
Otherwise you will need a more sophisticated system.

**Comment by sherlcok314159** [comment]
Thanks. But how can I combine this with freshrss?

**Comment by Alkarex** [comment]
A typical way is to use a system such as [RSS Bridge](https://github.com/RSS-Bridge/rss-bridge), which outputs an RSS feed, which can be consumed by FreshRSS.
But first step is to find an approach that works manually.

**Comment by squromiv** [comment]
> Some sites can not be scraped without javascript

Try [feedless](https://github.com/damoeb/feedless) tool. It can help in some cases.

**Comment by sherlcok314159** [comment]
Thanks for the above replies. My solution is to use a local headless browser to handle this by python. It is quite light.

**Comment by haroldrandom** [comment]
@sherlcok314159 May I ask  how to integrate the content that scrape from Headless browser with FreshRSS database?
