### ISSUE TITLE
Mise en page des images et flottants

### ISSUE THREAD

**Issue by Cypouz** [FreshRSS/FreshRSS#645]
Salut !

Les images des articles et le texte qui les suit sont rarement bien mis en page dans FRSS. Les images sont collées entre-elles et le texte qui les suit également, à leur pied droit.

Un espace systématique (`margin: 1em;` ?) entre les images serait plus esthétique, et forcer le retour à la ligne du texte qui suit améliorerait la lisibilité (`clear: both;` ? `display: block;` ?). Cf. capture d'écran ci-dessous.

![capture du 2014-09-30 10 16 39](https://cloud.githubusercontent.com/assets/4980075/4455359/4c76d2b8-487e-11e4-9050-8c7354ed074a.png)

**Comment by math-GH** [comment]
Is it still a relevant issue?
