### ISSUE TITLE
[Bug] No more title / date in headline

### ISSUE THREAD

**Issue by airbete** [FreshRSS/FreshRSS#6463]
### Describe the bug

Since commit aac3b21a, title and date are not shown anymore in the headline of articles.

Before commit 
![before_commit](https://github.com/FreshRSS/FreshRSS/assets/10148399/eb65cff7-c303-471f-b0e3-78c5494aebb6)

After commit
![after_commit](https://github.com/FreshRSS/FreshRSS/assets/10148399/d7188fe6-1a7b-4ed1-9275-3a12aab4d26f)

Collapsed mode is now useless.

### To Reproduce

1. Click on a any feed
2. Observe the headline of any article

### Expected behavior

Title and date should appear in the headline.

### FreshRSS version

git as of bb1a6caf

### Environment information

- Database version: SQLite
- PHP 8.2.18
- Installation type: git
- Web server: Apache
- Device: Desktop
- OS: Fedora 38
- Firefox 126 and Chrome 124.0.6367.118

**Comment by Alkarex** [comment]
Could you please force refresh and/or try with another Web browser?

**Comment by airbete** [comment]
I forced refresh, restarted Firefox and tried with chrome. No change.

**Comment by Alkarex** [comment]
That's odd. Could you please `git fetch && git reset --hard origin/edge` just to make sure that there is nothing wrong there?
Otherwise, please try to DOM inspect from your Web browser, to make sure that the text content is actually there:

![image](https://github.com/FreshRSS/FreshRSS/assets/1008324/a938ab79-6c58-456a-8f9c-3a4a35eb4006)

**Comment by math-GH** [comment]
Which extensions are installed? TitleWrap too? Could you please update this extension?

**Comment by airbete** [comment]
@math-GH, you found it!

I forgot I had extensions activated. It's been a long time since I installed them and I haven't updated them since then. Updating is not as straight forward as "git pull"...

Updating (or disabling) TitleWrap gets everything back to normal. Thank you! very much.
