### ISSUE TITLE
[Bug] Minor typo in docs: en/admins/09_AccessControl.html

### ISSUE THREAD

**Issue by aredshift** [FreshRSS/FreshRSS#6465]
### Describe the bug

> It is never advisable to not use any form of authentication, but **never** _chose_ this option on a server that is able to be accessed outside of your home network.

Should read:

> It is never advisable to not use any form of authentication, but **never** _choose_ this option on a server that is able to be accessed outside of your home network.

I think the intention is to use the imperative form of the verb to instruct the reader (choose), rather than past tense (chose).

### To Reproduce

Head to https://freshrss.github.io/FreshRSS/en/admins/09_AccessControl.html and read the "No Authentication" section

or see here: https://github.com/FreshRSS/FreshRSS/blob/bb1a6cafb63de1aaca2cbfbb32d2fcd93c09e1dd/docs/en/admins/09_AccessControl.md?plain=1#L60

### FreshRSS version

Irrelevant

### Environment information

Irrelevant

**Comment by aredshift** [comment]
I'd be happy to make a quick PR to fix this.

**Comment by Frenzie** [comment]
I'd say that would've been faster than the bug report, heh. Please do! :-)

**Comment by aredshift** [comment]
Sorry, first time here! Contributing guidelines had me thinking an Issue was necessary for a PR to get attention. Will just open a PR if I find something this minor again.
