### ISSUE TITLE
[Feature request] Multiple catogories on individual feeds

### ISSUE THREAD

**Issue by Jucgshu** [FreshRSS/FreshRSS#647]
Don't take this as feature request per se, but rather as an item to add as an idea to the todo #646.

Il could be great to assign multiple categories to one individual feed.

(I think) Feedly has this nice feature : an individual feed can appear in one or multiple categories and be marked as read when read in one or the other category.

**Comment by Alkarex** [comment]
Just to clean a bit the open issues. This one is quite unlikely to be implemented in the foreseeable future, so I close the issue for now.
