### ISSUE TITLE
[Bug] There is an error when setting the filter conditions for the feed.

### ISSUE THREAD

**Issue by ayasechan** [FreshRSS/FreshRSS#6478]
### Describe the bug

Errors may occur when including certain characters, such as the character "薅," in the filter conditions for setting up the feed.

### To Reproduce

see here
https://files.catbox.moe/qo96he.mp4

### FreshRSS version

latest

### Environment information

Run by docker.
the docker image is freshrss/freshrss:latest.

**Comment by Alkarex** [comment]
Could you please try with our rolling release `freshrss/freshrss:edge` ?

**Comment by Alkarex** [comment]
Similar than https://github.com/FreshRSS/FreshRSS/issues/6236
It should have been fixed already by https://github.com/FreshRSS/FreshRSS/pull/6247

**Comment by ayasechan** [comment]
> Could you please try with our rolling release `freshrss/freshrss:edge` ?

This version can run properly!
