### ISSUE TITLE
[Bug] DB Name with upercase letters fails with Postgresql

### ISSUE THREAD

**Issue by Kilill** [FreshRSS/FreshRSS#6479]
### Describe the bug

Database install step mangles database name into lower case

### To Reproduce

1. Create a postgresql data base containing uppercase letters for example : FreshRss
2. Verify from command line that access to database/user succeeds
3. Go to install page and use above credentials on data base definition page (step 2 ?) 
4. Verify that this step fails
5. Rename data base to all lower case
6. Install step now passes

### Expected behavior

Install step should not manipulate the data base name and take it as entered

### FreshRSS version

1.24.1

### Environment information

- Database version: Postgresql 14
- PHP version: 8.3
- Installation type: git
- Web server type: Apache
- OS: Ubuntu 22.04
- Browser: brave

**Comment by Alkarex** [comment]
Could you please test this patch? https://github.com/FreshRSS/FreshRSS/pull/6482

**Comment by Kilill** [comment]
Yes! That works so much better!
