### ISSUE TITLE
[Bug] missing articles titles in 1.24.0

### ISSUE THREAD

**Issue by typhoe** [FreshRSS/FreshRSS#6481]
### Describe the bug

after freshrss update to 1.24.0 (docker), I'm missing the article titles
![image](https://github.com/FreshRSS/FreshRSS/assets/881171/6d496a7a-8bd8-433c-920b-f1ff10ee5c5c)

If I change my settings to also display a summary, they appear again (along the summary)
![image](https://github.com/FreshRSS/FreshRSS/assets/881171/402e099f-678a-4b3b-b785-df01cfef8214)
titles in bold in the screenshot
![image](https://github.com/FreshRSS/FreshRSS/assets/881171/dc5a3aa1-3281-47ff-9aa7-444a9d1a08fb)

Am I missing a new setting to get the titles ?
Thank you

### To Reproduce

my display settings
![image](https://github.com/FreshRSS/FreshRSS/assets/881171/619e65a8-4b0a-4885-8d85-2621d0b12f98)

### Expected behavior

get the titles of the articles on the list

### FreshRSS version

1.24.0

### Environment information

docker install
Chrome last version in Manjaro linux

**Comment by Alkarex** [comment]
Please update your FreshRSS extensions as well

**Comment by Alkarex** [comment]
Duplicate of https://github.com/FreshRSS/FreshRSS/issues/6463

**Comment by typhoe** [comment]
Indeed, forgot my extensions dir was a specific volume and they weren't updated each time.
Thanks, everything working now
