### ISSUE TITLE
Update process git error

### ISSUE THREAD

**Issue by i300220** [FreshRSS/FreshRSS#6483]
### Discussed in https://github.com/FreshRSS/FreshRSS/discussions/5174

<div type='discussions-op-text'>

<sup>Originally posted by **zero77** March  5, 2023</sup>
**Describe the bug**
Before 1.21.0 stable release the dev updates worked correctly now they fail to update.
After clicking apply the following error is displayed and the update fails.

**To Reproduce**
1. Go to settings
2. Click on Apply under updates
3. Updates fail and show an error message

**Expected behavior**

**Screenshots**

![Screenshot](https://user-images.githubusercontent.com/16563034/222966699-343b165e-317c-4a3b-adfc-6cef3dda6b30.png)

**Environment information (please complete the following information):**
- Device: Firefox for Linux
- OS: Debian 11
- Browser: Firefox 102.8.0
- FreshRSS version: 1.21.0-dev
- Database version: [e.g. Mysql 5.7]
- PHP version: 7.4.33
- Installation type: Apache

**Additional context**

</div>

**Comment by Alkarex** [comment]
Hello,
I have added better git error messages and suggestions of fixes in https://github.com/FreshRSS/FreshRSS/pull/6496

Please give it a try if you can.

The most likely problem you faced is:

```console
$ git symbolic-ref --short HEAD
fatal: detected dubious ownership in repository at '/var/www/FreshRSS'
```

And the proposed solution is: Reapply `chown www-data:www-data -R /var/www/FreshRSS/`

**Comment by i300220** [comment]
Hi @Alkarex 

Looks fine here with the current ownership:

```
$ git symbolic-ref --short HEAD
latest

```
Taking note of your proposed solution though.

Not sure your better error messages would help me, I've never been able to see any log messages related to Minz.  Only those related to Simplepie shows in the logs.  Found absolutely nothing in the GUI or in the config files pointing me to a solution.

Maybe better checkinstall would do it - https://FreshRSS/p/i/?c=update&a=checkInstall ?

**Comment by Alkarex** [comment]
The error messages will be shown in the on-screen pop-up just like you have in your screenshot

**Comment by Alkarex** [comment]
P.S. You manual test is likely working because it is not the same user (typically `www-data`) than what PHP runs.
