### ISSUE TITLE
[Bug]  Russian feeds corrupted even RSS feeds are valid.

### ISSUE THREAD

**Issue by aligundogar** [FreshRSS/FreshRSS#6484]
### Describe the bug

Russian RSS feeds broked. Title is fine but cant read descriptions. 
![image](https://github.com/FreshRSS/FreshRSS/assets/48637822/f048624a-09b3-4edc-b983-9b34fd4c6ba8)
![image](https://github.com/FreshRSS/FreshRSS/assets/48637822/0769f552-7c50-44d0-b44a-f1c54e7e44aa)

Example feeds:
https://rss-bridge.org/bridge01/?action=display&bridge=TelegramBridge&username=zedigital&format=Atom
https://www.obozrevatel.com/out/rss/lastnews.xml

### To Reproduce

![image](https://github.com/FreshRSS/FreshRSS/assets/48637822/6c2a4d15-0215-4641-8571-3c82354e0419)

### Expected behavior

I wanted to see feeds as cyrillic alphabet. Its been not workin since reinstallation.

### FreshRSS version

I'm using docker image 	freshrss/freshrss:latest, 1.23.1

### Environment information

- Installation type: Docker Container.
- Device: Windows 11 & Debian 12
- OS: Docker 
- Browser: Opera & Google

**Comment by Alkarex** [comment]
Hello,
I cannot reproduce the problem.
Could you try to update your `freshrss/freshrss:latest` to 1.24.0 or try `freshrss/freshrss:edge` ?

**Comment by aligundogar** [comment]
oh its completely gone now. I Restarted container, at first its took port then lost again.

![image](https://github.com/FreshRSS/FreshRSS/assets/48637822/f5b4afce-44ad-4ae0-857b-7e92348384de)
![image](https://github.com/FreshRSS/FreshRSS/assets/48637822/6a687d58-7a15-4036-b388-2fc2b62c6f9a)

**Comment by aligundogar** [comment]
![image](https://github.com/FreshRSS/FreshRSS/assets/48637822/c26b65e2-30db-438f-a73e-06903a8c987e)

**Comment by aligundogar** [comment]
Okey I updated my configuration with https://hub.docker.com/r/freshrss/freshrss docker compose developer file.
Then Deleted every database, mapping, container and stack in my server. Setup from scratch then converted edge img to latest one. Problem fixed. Now I'm in 1.24 version. Thanks for contributing.
