### ISSUE TITLE
[Bug] Docker issue - ERROR: for freshrss  'ContainerConfig'

### ISSUE THREAD

**Issue by jacksnodgrass** [FreshRSS/FreshRSS#6488]
### Describe the bug

Not sure where to post this... ask for help... etc.  I use docker to run freshrss.  I've been doing: 

docker-compose stop
docker-compose pull && docker-compose up -d 

and my docker-compose.yml file had: 
version: "2"
services:
  freshrss:
    #image: linuxserver/freshrss
    image: freshrss/freshrss:latest
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - CRON_MIN=*/10
    volumes:
      - /data/freshrss:/var/www/FreshRSS/data
    ports:
      - 8008:80
    restart: unless-stopped

now... with the latest 1.24.0 version, this docker-compose stop|pull|up no longer work. 

Recreating freshrss ... 

ERROR: for freshrss  'ContainerConfig'

ERROR: for freshrss  'ContainerConfig'
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

not sure where to ask for help with this... figure I'd start here and see if anyone could point me in the right direction. 

### To Reproduce

1. docker-compose pull && docker-compose up -d 

Gets: 
Recreating freshrss ... 

ERROR: for freshrss  'ContainerConfig'

ERROR: for freshrss  'ContainerConfig'

### Expected behavior

starts normally and runs without this startup error

### FreshRSS version

1.24.0

### Environment information

Fedor 39 with 
rpm -qa | grep -i docker
```
python3-docker-6.1.3-1.fc39.noarch
python3-docker+ssh-6.1.3-1.fc39.noarch
python3-dockerpty-0.4.1-29.fc39.noarch
python3-docker-pycreds-0.4.0-17.fc39.noarch
docker-compose-1.29.2-10.fc39.noarch
docker-compose-plugin-2.27.0-1.fc39.x86_64
docker-buildx-plugin-0.14.0-1.fc39.x86_64
docker-ce-cli-26.1.3-1.fc39.x86_64
docker-ce-rootless-extras-26.1.3-1.fc39.x86_64
docker-ce-26.1.3-1.fc39.x86_64
```

**Comment by Alkarex** [comment]
Maybe: https://askubuntu.com/questions/1508129/docker-compose-giving-containerconfig-errors-after-update-today

**Comment by marcinbojko** [comment]
@jacksnodgrass - you could try to drop docker-compose in favor of 'docker compose'.
Same syntax, no need for extra python script.
Works without any issues
```
 docker info
Client: Docker Engine - Community
 Version:    26.1.3
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.14.0
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.27.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose
  scan: Docker Scan (Docker Inc.)
    Version:  v0.23.0
    Path:     /usr/libexec/docker/cli-plugins/docker-scan
```

**Comment by Alkarex** [comment]
> in favor of 'docker compose'

On Debian / Ubuntu, the package is `docker-compose-v2`

**Comment by marcinbojko** [comment]
Seems it's Fedora :) Anyway - works (1.24.1)
