### ISSUE TITLE
[Bug] 1.24.0 broke cookie transmission

### ISSUE THREAD

**Issue by rom-1** [FreshRSS/FreshRSS#6491]
### Describe the bug

Hi, 
since updating to 1.24.0 one of my feeds (the only one that needs "consent" cookies) is not working anymore. I am using CSS Selectors for filtering the content. Since the update, the only page that is visible to the scraper is the consent banner. I had these problems with the feed in the past, and figured out that I only need the Cookie "golem_consent20=cmp|220101" to make the banner disappear. That is still the case as of today with that website, but somehow FreshRSS seems to not transfer the cookie anymore.

Feed URL: https://rss.golem.de/rss.php?feed=RSS2.0
Article CSS selector: header.cluster-header figure.hero, header.cluster-header p, .formatted
Use Cookies when fetching: golem_consent20=cmp|220101
Accept cookies = disabled, not neccessary
Feed-Export: [f_12 Golem.de.opml.zip](https://github.com/FreshRSS/FreshRSS/files/15442366/f_12.Golem.de.opml.zip)

### To Reproduce

1. Import attached file
2. Click on Preview next to the Article CSS selectors
3. Preview states: cannot find the selectors 
4. If I limit my selectors to "body" I can see the cookie banner in the preview

### Expected behavior

Article scraping should work. 

### FreshRSS version

1.24.0

### Environment information

Not relevant

**Comment by Alkarex** [comment]
Could you please try https://github.com/FreshRSS/FreshRSS/pull/6492 ?

**Comment by rom-1** [comment]
uploaded your changes to app/Models/Entry.php, works like a charm now. Thanks so much for the quick help! ♥️
