### ISSUE TITLE
[Bug] Web updater doesn't find the newest release 1.24.0

### ISSUE THREAD

**Issue by escuco** [FreshRSS/FreshRSS#6494]
### Describe the bug

Hello!

When I check for the latest release via web updater, the system doesn't find the version 1.24.0 (I'm now on 1.23.1)
![Screenshot_20240524_113137](https://github.com/FreshRSS/FreshRSS/assets/1647405/8e4f380b-e6d9-4c64-b481-c242edb0dade)

Instance: https://escuco.de/freshrss/

### To Reproduce

1. go to 'settings'
2. go to 'aktualisieren' (update)
3. check for a new update

### FreshRSS version

1.23.1

### Environment information

The installation check doesn't show any errors:

Installationsüberprüfung
PHP-Installation

Ihre PHP-Version ist 8.1.28, welche kompatibel mit FreshRSS ist.

Sie haben die cURL-Erweiterung.

Sie haben PDO und mindestens einen der unterstützten Treiber (pdo_mysql, pdo_sqlite, pdo_pgsql).

Sie haben die benötigte Bibliothek für reguläre Ausdrücke (PCRE).

Sie haben die benötigte Bibliothek für die Überprüfung von Zeichentypen (ctype).

Sie haben die fileinfo-Erweiterung.

Sie haben die benötigte Bibliothek um DOM zu durchstöbern.

Sie haben die JSON-Erweiterung.

Sie haben die empfohlene mbstring-Bliothek für Unicode.

Sie haben die ZIP-Erweiterung.
Datei-Installation

Die Berechtigungen des Verzeichnisses ./data sind in Ordnung.

Die Berechtigungen des Verzeichnisses ./data/cache sind in Ordnung.

Die Berechtigungen des Verzeichnisses ./data/users sind in Ordnung.

Die Berechtigungen des Verzeichnisses ./data/favicons sind in Ordnung.

Die Berechtigungen des Verzeichnisses ./data/tokens sind in Ordnung.

**Comment by Alkarex** [comment]
The Web update using the *ZIP*  method is always postponed a few days.
Methods, which are immediately available include Web update with git, manual git, manual ZIP, Docker.

**Comment by escuco** [comment]
Ok, thank you. Then I'll wait for the update, until it appears.

**Comment by math-GH** [comment]
This question appears after a release often. Should we add a information into the release note? https://github.com/FreshRSS/FreshRSS/releases/tag/1.24.0
