### ISSUE TITLE
[Feature] Change it so that the colors of each category match on both of the pie charts in the statistics tab

### ISSUE THREAD

**Issue by K4LCIFER** [FreshRSS/FreshRSS#6497]
**Is your feature request related to a problem? Please describe.**
Currently, the statistics page pie charts don't match the color between the two pie charts, so, when looking at them, it can be a bit misleading as to what slice corresponds to what, unless you hover your mouse over the individual segments to see what they are or look at the list at the bottom.

**Describe the solution you’d like**
Change it so that the colors for each category are the same on both pie charts.

**Describe alternatives you’ve considered**
None.

**Additional context**

You can see in the following image that the colors for each category don't match on both pie charts.
![image](https://github.com/FreshRSS/FreshRSS/assets/7829231/e6d618ed-41c3-4938-804f-771e5d364524)

**Comment by Manitosh-Paul** [comment]
Hello Team, I am new to open source and want to contribute. But, I am not able to relocate the file where I can find this issue.
Files I checked for this issue:
app/Models
p/scripts/vendor/chart.min.js
p/scripts/feed.js
All files under p/scripts

Can anyone help me out!

**Comment by Alkarex** [comment]
Hello @Manitosh-Paul and welcome 👍🏻 
Have a look at https://github.com/FreshRSS/FreshRSS/blob/edge/app/views/stats/index.phtml

**Comment by kwarraich** [comment]
hi @Alkarex I want to make a PR for this issue! Could you assign it to me please? 

Thank you
