### ISSUE TITLE
image and description on user query share

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#6538]
### Discussed in https://github.com/FreshRSS/FreshRSS/discussions/6537

<div type='discussions-op-text'>

<sup>Originally posted by **TomW1605** June  4, 2024</sup>
hi
is there a way to add a description and feed image to the rss feed from a user query?

i am using FreshRSS to process the patreon feeds of some podcasts to split out normal and patreon episodes so they are different feeds in my podcast app. unfortunatly they dont have the image or description of the input feed and that makes them quite hard to tell apart.

i understand this is not at all the intended usecase for FreshRSS but other than this issue it is something it works extreemly well for so if there was a way to do this it would be basicaly perfect.
thanks</div>

**Comment by TomW1605** [comment]
if i can find some time (and remember how to write PHP) i might take a shot at this.

before i do though, what do you think is the better way to do it?
just fields for description and image url or pulling all the metadata tags from a specified feed? the fields is probably a lot easier but pulling the metadata will also get things like language, authers, explicit tags, catagories and other things that would be extensive to implement as fields

**Comment by Alkarex** [comment]
Super @TomW1605 👍🏻 
I think first step should be very simple:
1. Add description field to shared user query
![image](https://github.com/FreshRSS/FreshRSS/assets/1008324/f6a78e00-842b-494d-b13d-bb462620dbea)

2. Use it to customise the `<description>` field of the RSS output (and also HTML and OPML outputs)

```xml
<channel>
	<title>User query ABC</title>
	<link>https://freshrss.example.net/api/query.php?user=alice&amp;t=1234&amp;f=html</link>
	<description>The new customised description</description>
	<!-- ... -->
</channel>
```

3. Consider doing the same with a new field for image URL

**Comment by TomW1605** [comment]
thanks for your help, i got it working with both description and image url. unfortunatly the image url in the patreon feed is timestamped and i expect it will expire pretty fast but grabing the image file and rehosting it isnt that hard considering i already have a server running for this

now i just need to pull the files off my server and work out what i changed so i can do a PR

![image](https://github.com/FreshRSS/FreshRSS/assets/17092573/46e3cac8-6f14-4da3-8b9a-1eca934ad4f6)

**Comment by TomW1605** [comment]
i also can't do translations for anything (i have put the strings in for english) unless you are ok with google translate.

it is only 2 new strings, Description and Image URL, for the field labels

**Comment by TomW1605** [comment]
PR submitted
