### ISSUE TITLE
[Bug] cURL error 6: Could not resolve host

### ISSUE THREAD

**Issue by roughnecks** [FreshRSS/FreshRSS#6539]
### Describe the bug

I see a triangle near a few feeds recently and then looking at the logs panel, I find a lot of lines stating what I wrote in title: `cURL error 6: Could not resolve host <hostname>[feed_url]`

I can `curl <feed_address>` just fine from the server terminal and dig host also resolves.
Also, it looks to me it actually does fetch news, even when there are failed attempts.

### To Reproduce

Just let it fetch news as you always do. No particular steps needed.

### Expected behavior

It should get news without errors or "not get" news with actual errors.

### FreshRSS version

1.24.0

### Environment information

- Versione PHP 8.2.18
- Installation type: release from git
- Web server type: nginx
- Windows 10 desktop PC
- Browser: chrome 125.0.6422.113

**Comment by Alkarex** [comment]
Is it for all the feeds, or only some of the feeds?

**Comment by roughnecks** [comment]
> Is it for all the feeds, or only some of the feeds?

It's not all, but several. Those one have repeated entries in logs.

**Comment by roughnecks** [comment]
One thing that could matter, now that I think about it, was me switching from nextdns to cloudflare in resolved.conf.
I have 2 entries for v4 and 2 for v6 and also `DNSOverTLS=yes`

**Comment by roughnecks** [comment]
Sorry for the many messages, but I'm also seeing this kind of issue:

`cURL error 28: Operation timed out after 20001`

**Comment by Alkarex** [comment]
This is most likely unrelated to FreshRSS but instead due to an unreliable DNS / network setup or configuration.

Test a basic connection by creating a file `./FreshRSS/p/test.php`

```php
<?php
$ch = curl_init('https://freshrss.org/');
curl_setopt_array($ch, [
		CURLOPT_TIMEOUT => 15,
		CURLOPT_ENCODING => '',	//Enable all encodings
		CURLOPT_VERBOSE => 1,	// To debug sent HTTP headers
	]);
curl_exec($ch);
echo curl_errno($ch), ' (', curl_strerror(curl_errno($ch)), '). ', curl_error($ch);
curl_close($ch);
```

And then access it via your Web browser https://freshrss.example.net/test.php
Try multiple times, and try to change the URL from https://freshrss.org/ to other examples.

**Comment by roughnecks** [comment]
I tried multiple times with a few sites, it always reports `0 (No error)`

**Comment by roughnecks** [comment]
Changed server in resolved.conf from 1.1.1.1 to NextDNS and it looks like it's way more stable now.
Not sure if to close the issue or not, I'll let you decide.
