### ISSUE TITLE
CSS not loading

### ISSUE THREAD

**Issue by xNiika** [FreshRSS/FreshRSS#6540]
I've just set up FreshRSS for the first time and everything worked without problems. 

After I completed the manual set up, CSS styles are no longer applied to the site, but it worked fine during the setup.

![Screenshot_20240604-131337.png](https://github.com/FreshRSS/FreshRSS/assets/54737733/eaca5899-8d7a-4267-a1a5-3049347bb072)

What could be the problem?

The issue persists after logging in.

**Comment by Alkarex** [comment]
Please tell how you installed FreshRSS and on which platform

**Comment by Alkarex** [comment]
Please look also in your Web browser developer tools, under "network", which will likely indicate some errors.
Likewise, look into your Web server logs.
A likely reason is a wrong setup of the Web root in your Web server setup.

**Comment by xNiika** [comment]
Thanks for the quick response.

I manually installed FreshRSS on a Debian 12 Server with NGINX and PHP 8.1. (Through the guide when visiting the site for the first time)

There are no errors in the console and the network tab is fine as well (all responses are 200).

If I open the display settings of FreshRSS on the website, I noticed that it's not showing any themes/layouts. There is just one checkbox select, which says that the theme "Origine" is no longer available and I have to choose a different theme. (Which I can't)

**Comment by xNiika** [comment]
I probably found my issue. I will try to fix it when I'm home.

**Comment by xNiika** [comment]
Alright, I found the issue and fixed it!

**Comment by Alkarex** [comment]
Maybe you could post of few tips here, in case someone faces similar symptoms

**Comment by xNiika** [comment]
It was my own mistake. I renamed the "p" directory at the beginning and forgot about that.
