### ISSUE TITLE
Integration with Readeck

### ISSUE THREAD

**Issue by t34wrj** [FreshRSS/FreshRSS#6552]
It would be great if integration with [Readeck](https://readeck.org/en/) (a self-hosted Pocket, in effect) could be added. 

EDIT: I've found the following on the documents contained in my Readeck self-hosted instance - not sure if it's any help:

_Readeck API 1.0.0
Introduction
The Readeck API provides REST endpoints that can be used for any purpose, should it be a mobile application, a script, you name it.

API Endpoint
You can access this API on https://readeck.REDACTED.com/api.

Most of your requests and responses are using JSON as the exchange format.

Authentication
To use the API, you first need to create an authentication token. You can then use your new token using the Bearer HTTP authorization scheme.

For example, you first request will look like:

curl -H "Authorization: Bearer <TOKEN>" https://readeck.REDACTED.com/api/bookmarks
Or, in NodeJS:

fetch("https://readeck.REDACTED.com/api/bookmarks", {
  headers: {
    "Authorization": "Bearer <TOKEN>",
  },
})
First time authentication
While you can create an authentication token from Readeck, you can also get one directly from the API. This provides a mechanism to ask for user credentials and obtain a token for your app only.

Please refer to POST /auth for more information.

Test the API
On this documentation, you can test every route.

If you don't provide an API token in Authentication, you can still test all the routes but note that the given curl examples only work with an API token._

**Comment by t34wrj** [comment]
I have raised the API issue with the developer and his comments are here: [https://codeberg.org/readeck/readeck/issues/166](https://codeberg.org/readeck/readeck/issues/166)

**Comment by Alkarex** [comment]
It looks like a workflow could be to open the link in a tab and use a browser extension to save the page in Readeck, as it seems to be the recommended way to save pages, including those requiring login, JavaScript, etc.

**Comment by mustaruhtinas** [comment]
With almost no relevant knowledge I managed to adapt a script originally intended for Pocket to use with Newsboat.  It was basically a POST request using an auth token, article title and url, and readeck instance url. Most likely a crude hack, but it did work.
I was not able to modify it in order to work directly with FreshRSS.
There is, however, a miniflux plugin that may perhaps serve as a starting point.

**Comment by Joedmin** [comment]
Hello, I am looking forward this feature

**Comment by Joedmin** [comment]
Okay, I've taken matters in my own hand and created an extention https://github.com/Joedmin/xExtension-readeck-button

**Comment by Alkarex** [comment]
Ref https://github.com/FreshRSS/Extensions/pull/245
