### ISSUE TITLE
Curl Timed out...

### ISSUE THREAD

**Issue by barbuslex** [FreshRSS/FreshRSS#656]
Hi,

How can i solve this log error  ?

```
2014-10-05 21:10:36
cURL error 28: Operation timed out after 10002 milliseconds with 0 bytes received [http://www.easytutoriel.com/feed/]
```

Thanks

**Comment by Alkarex** [comment]
https://github.com/simplepie/simplepie/pull/407

**Comment by Alkarex** [comment]
If anyone lands on this page, since FreshRSS 0.9.2 (October 2014), there is an option in `data/config.php` to control the timeout value
https://github.com/FreshRSS/FreshRSS/blob/1.1.1/data/config.default.php#L65
https://github.com/FreshRSS/FreshRSS/commit/2e5d4d97c989f55c3506ceb918126eaf9c68f1d6
