### ISSUE TITLE
[Bug] "&" is being converted to "&amp;" and breaking the url

### ISSUE THREAD

**Issue by TatoTech** [FreshRSS/FreshRSS#6575]
### Describe the bug

The ampersands within a Last.fm API url are being converted/expanded to &amp; causing FreshRSS to fail as the URL doesn't actually exist.

For example:

I'll enter `https://ws.audioscrobbler.com/2.0/?api_key=[REDACTED]&method=user.getrecenttracks&user=rj&format=json&limit=10&extended=1` and it will be changed to `https://ws.audioscrobbler.com/2.0/?api_key=[REDACTED]&amp;method=user.getrecenttracks&amp;user=rj&amp;format=json&amp;limit=10&amp;extended=1` which is apparently invalid.

This does not happen with other URL's I've used as sources.

### To Reproduce

1. Go to 'Add a new subsciption'
2. Paste feed URL into Feed URL textbox
3. Click 'Type of feed source' and change to JSON (dot notation)
4. Configure dot notation accordingly
5. Click 'Add'
6. Update the feed
7.  Log files show `JSON dot notation parsing failed for [https://ws.audioscrobbler.com/2.0/?api_key=[REDACTED]&amp;method=user.getrecenttracks&amp;user=rj&amp;format=json&amp;limit=10&amp;extended=1] `

### Expected behavior

It should not convert & to &amp;  in order for FreshRSS to access the URL correctly.

### FreshRSS version

1.24.1

### Environment information

- Database version: Postgres
- PHP version: PHP 8.2.18
- Installation type: Docker (freshrss/freshrss:latest)
- Web server type: Existing Apache install
- Device: Desktop
- OS: Windows 11
- Browser: Firefox 127

### Additional context

API docs are [here](https://www.last.fm/api/show/user.getRecentTracks)
API key its self is a 32 character alphanumeric string

**Comment by Alkarex** [comment]
I believe the bug is only in the logs (wrongly double escaping the URL) and not in the actual request.
The most likely is that the JSON dot notation was wrong

**Comment by TatoTech** [comment]
Yep that was the issue.

Thanks for the help!
