### ISSUE TITLE
[BUG] Replacing feed content using article css selector has stopped working (1.24.0 to 1.24.1)

### ISSUE THREAD

**Issue by gingerbeardman** [FreshRSS/FreshRSS#6588]
### Describe the bug

Posts in some feeds can be partial/truncated.

So I use the advanced feature of FreshRSS to replace the main content using CSS selector. 

- With 1.24.1 this stopped working. 
- I've checked the website and the HTML hasn't changed. 
- And rolling back to 1.24.0 has things working as it should do.

I'm just seeing the truncated content that comes with the feed as standard. 

### To Reproduce

1. Feed URL: https://www.timeextension.com/feeds/latest
1. Type: RSS/Atom
1. Advanced: 
    - Article CSS Selector: `.article-text`

### Expected behavior

- content from main page should be used to replace feed content. 

### Workaround

- Downgrading to 1.24.0 brings back the correct behaviour.

### FreshRSS version

- 1.24.1

### Environment information

- Database version: would be good to be able to see this in installation check page
- PHP version: 8.3.8
- Installation type: Docker, [lscr.io/linuxserver/freshrss:latest](https://hub.docker.com/r/linuxserver/freshrss) (see Additional context below as to why)
- Web server type: nginx
- Device: Synology
- OS: DSM 6.2.3
- Browser: n/a

### Additional context

I can't use the official docker container because of this issue:

> [Mon Jun 24 14:57:19.012050 2024] [:crit] [pid 1] (38)Function not implemented: AH00141: Could not initialize random number generator

Upstream: https://github.com/shinsenter/php/issues/28

And related discussion: https://github.com/FreshRSS/FreshRSS/discussions/5987

**Comment by math-GH** [comment]
I cannot see any issues there.

What do you expect?
What is the current status?

Could you please pick an article and make screenshots how it looks like and what you expect?

**Comment by gingerbeardman** [comment]
The current status is that I am now using 1.24.0 which does not have the issue

----

If I go back to 1.24.1, here are my results

## For the most recent item as I type, I see this:

> **Currently only available to Patreon subscribers.**
> 
> **Update :** The port is now available to the general public.
> 
> * * *
> 
> **Original Story :** Infidelity, the talent behind NES-to-SNES ports of games such as [Contra](https://www.timeextension.com/news/2024/03/run-and-gun-classic-contra-has-been-ported-to-snes) and [Mega Man](https://www.timeextension.com/news/2024/02/a-fanmade-mega-man-port-for-snes-has-just-been-released), has just revealed his next project – bringing [Zelda II: The Adventure of Link](https://www.timeextension.com/games/nes/zelda_ii_the_adventure_of_link) to Nintendo's 16-bit system.
> 
> Read the [full article on timeextension.com](https://www.timeextension.com/news/2024/06/zelda-ii-has-been-ported-to-the-snes)


## Where I would expect to see something like this:

> Currently only available to Patreon subscribers
> 
> [![Zelda II Has Been Ported To The SNES 1](https://images.timeextension.com/d9f34a65c7128/zelda-ii-has-been-ported-to-the-snes-1.900x.jpg)](https://images.timeextension.com/d9f34a65c7128/zelda-ii-has-been-ported-to-the-snes-1.large.jpg "Zelda II Has Been Ported To The SNES 1")
> 
> _Image: Nintendo_
> 
> **Update \[Fri 28th Jun, 2024 16:00 BST\]:** The port is now available to the general public.
> 
> * * *
> 
> **Original Story \[Fri 21st Jun, 2024 10:00 BST\]:** Infidelity, the talent behind NES-to-SNES ports of games such as [Contra](news/2024/03/run-and-gun-classic-contra-has-been-ported-to-snes) and [Mega Man](news/2024/02/a-fanmade-mega-man-port-for-snes-has-just-been-released), has just revealed his next project – bringing [Zelda II: The Adventure of Link](games/nes/zelda_ii_the_adventure_of_link) to Nintendo's 16-bit system.
> 
> The port is currently only available to Infidelity's Patreon subscribers and is in beta.
> 
> "It's playable from beginning to end, but please read the included readme file, for the laundry list of known issues that I still need to tackle," adds the developer.
> 
> > To my port Patreon subscribers, come try out the very first beta of my Zelda II SNES port!  
> >   
> > It's playable from beginning to end, but please read the included readme file, for the laundry list of known issues that I still need to tackle. [pic.twitter.com/HG70SArxsF](https://t.co/HG70SArxsF)— infidelity (@infidelity\_nes) [June 20, 2024](https://twitter.com/infidelity_nes/status/1803911581304263154?ref_src=twsrc%5Etfw)
> 
> Released in Japan for the Famicom Disk System in 1987, Zelda II: The Adventure of Link would come to the West in a more traditional cartridge format the following year.
> 
> A notable departure from the original game, Zelda II introduces a side-on perspective when exploring towns and taking part in combat, and even features experience points – something that has never been seen in any other Zelda outing.
> 
> While it was a commercial success and still has its fans, Zelda II is arguably one of the less-acclaimed entries in the long-running series; [it was ranked 31st out of 33 in Nintendo Life's list of the best Zelda games](https://www.nintendolife.com/guides/best-zelda-games-of-all-time).

**Comment by math-GH** [comment]
Please check demo.freshrss.org: https://demo.freshrss.org/i/?get=f_10 (demo.freshrss.org is on `1.24.2-dev` / `edge)`

**Comment by gingerbeardman** [comment]
Everything works as expected on the demo installation. Which is good to know. 

So, I'll try to get some error logs from 1.24.1 on my setup.

**Comment by math-GH** [comment]
Could you please export the OPML of your feed (button is available in 1.24.1 at the bottom of feed settings) and share it here?

**Comment by gingerbeardman** [comment]
I'm still running 1.24.0
[Edit: OPML sent]

**Comment by Alkarex** [comment]
Works for me, with the newest `freshrss/freshrss:edge`:
![image](https://github.com/user-attachments/assets/674e4184-7d58-46d8-92fc-99efd0fb6903)

But I can see that the requests are filtered by Cloudflare, so there might be an anti-robot response coming for some of your requests.

What happens when you click the CSS selector preview?
![image](https://github.com/user-attachments/assets/071134dc-1bd4-4b8d-bee8-af4ba2142bf8)

You are supposed to get something like:
![image](https://github.com/user-attachments/assets/206e700f-4da8-49a0-bca1-555f9cb251e2)

**Comment by gingerbeardman** [comment]
I updated to `lscr.io/linuxserver/freshrss:latest` which is currently at [1.24.1-ls241](https://github.com/linuxserver/docker-freshrss/releases/tag/1.24.1-ls241) and all seems to be working again, which is nice!

**Comment by gingerbeardman** [comment]
This had kept happening regularly since this issue. 

The only workaround I have is to: delete all items in the feed, clear the cache, and redownload. 

So the question is, why would this fail sometimes?

**Comment by Alkarex** [comment]
> What happens when you click the CSS selector preview?

And try to check your syslogs for the status code of the Web requests towards the corresponding domain

**Comment by gingerbeardman** [comment]
I'll check next time I see it.

**Comment by gingerbeardman** [comment]
Have changed my server which allows me to run the latest official docker image. 

It was still an issue on my old setup, but it's not on my new setup.
