### ISSUE TITLE
[Bug] cURL error 22 / 403 error on feed import attempt

### ISSUE THREAD

**Issue by colinstu12** [FreshRSS/FreshRSS#6597]
### Describe the bug

I am attempting to add a feed with URL of: https://www.aav.org/members/blog_rss.asp?id=[redacted]&rss=EEBq4Jc8
(where redacted is a simple numeric user ID) into FreshRSS. 
This gets logged: 
 cURL error 22: The requested URL returned error: 403 [https://www.aav.org/members/blog_rss.asp?id=[redacted]&amp;rss=EEBq4Jc8] 

I see there's bug #6575 already but it sounds like the "&amp;" is simply a display error and not actually what's being parsed/passed-in. 

I am able to successfully access this RSS XML via any web browser / any device within the same network, no credentials or cookies needed, I am not being presented CAPTCHA or anything like that, it just loads and renders like any other raw RSS feed. 

I'm not sure which exact cURL parameters that FreshRSS is using but I attempted to cURL it with a simple cURL -O 'https://www.aav.org/members/blog_rss.asp?id=[redacted]&rss=EEBq4Jc8' and it seems to just sit there trying to download a file forever, if I break out of it and less the .asp page it downloads, it seems to be about requiring javascript and it's trying to do a captcha test. For some reason when I disable JS in any number of webbrowsers and go to that page I'm not presented with any issues and it still pulls the raw RSS as expected, so maybe my cURL parameters are incorrect or FreshRSS is doing some magic ontop of that. 

### To Reproduce

1. Go to 'Add a feed or category'
2. Scroll down to 'Add a feed'
3. Paste in the Feed URL (with correct ID), press Add
4. Presented with the error

### Expected behavior

The feed to be added successfully

### FreshRSS version

1.23.1-dev

### Environment information

- Database version: postgresql 16.3-1
- PHP version: PHP 8.2.20-1
- Installation type: Debian 12 LXC container
- Web server type: Apache
- Device: Any (desktop/laptop/phone)
- OS: Any (Win11/macOS latest/iOS)
- Browser: Chrome 126 / Firefox 127

**Comment by jcolfej** [comment]
Hi @colinstu12 !

The site you're trying to add is protected by an anti-bot system (Datadome) that blocks FreshRSS.

```
> curl 'https://www.aav.org/members/blog_rss.asp?id=1743625&rss=EEBq4Jc8'
<html><head><title>aav.org</title><style>#cmsg{animation: A 1.5s;}@keyframes A{0%{opacity:0;}99%{opacity:0;}100%{opacity:1;}}</style></head><body style="margin:0"><p id="cmsg">Please enable JS and disable any ad blocker</p><script data-cfasync="false">var dd={'rt':'c','cid':'AHrlqAAAAAMAMrchOJo8h1QAHyccZg==','hsh':'2CF1354F5D33C04234B753357EE0F0','t':'bv','s':18464,'e':'aa7c97f687eb478eb30fb3d28748907b94e7dbb4024b7974105334961af092ef','host':'geo.captcha-delivery.com'}</script><script data-cfasync="false" src="https://ct.captcha-delivery.com/c.js"></script></body></html>
```

Unfortunately, without bypass system, you won't be able to add these RSS feeds...

**Comment by colinstu12** [comment]
> Unfortunately, without bypass system, you won't be able to add these RSS feeds...

Is there a way to bypass?

**Comment by jcolfej** [comment]
Unfortunately, I don't know of any free solution for bypassing Datadome...
But there are paid services: https://www.zenrows.com/ or https://www.scraperapi.com/

**Comment by colinstu12** [comment]
Closing issue, not using paid services to resolve this.

**Comment by Alkarex** [comment]
You could consider writing to aav.org to ask them to remove the JavaScript filter on their RSS feeds, which effectively prevent them from working...
