### ISSUE TITLE
[Bug] ./cli/db-backup.php does not work, subsequently migration to other DB server cannot be done

### ISSUE THREAD

**Issue by MacLemon** [FreshRSS/FreshRSS#6602]
### Describe the bug

Following the [documentation for database and restore](https://freshrss.github.io/FreshRSS/en/admins/05_Backup.html):

Backing ip the MySQL/MariaDB database doesn't work. As a consequence, it's not possible to migrate to a new DB server, or restore from backup in case of failure.

Ways to migrate from an old MySQL server to a new MariaDB 10.11 LTS server.
The simple way, that I would have expected to work:
- stop FreshRSS
- stop autoupdate `cron`
- Dump SQL database on old MySQL server with `mysqldump --set-gtid-purged=OFF --master-data --skip-comments --disable-keys --user=root --password --result-file=freshrss.dump.sql --databases freshrss`
  - `LOCK` freshrss user on MySQL, so I can be certain, that it's connecting to the correct database
- restore the database dump into the new MariaDB server
- `GRANT` all privileges to the freshrss database
- reconfigure FreshRSS DB connection to the new MariaDB Server
- start the FreshRSS service

Then load the webpage, login to FreshRSS and find out that *all* subscriptions are gone. Login works fine though, but no feeds are shown.

- stop FreshRSS service, for good measure.
- double check the database on the new MariaDB server and it seems that all the tables are there, yet it doesn't work.

I now know that this is *not* the way the documentation describes, yet it's *really* unexpected that this doesn't work. Because had I only done a normal database backup for the application I must assume, that I would have lost all user's data when trying to restore the DB.

---

Checked the documentation for backup and restore. Follow it exactly, see errors as described below.

Doesn't work either.

### To Reproduce

1. on the server `cd` into freshrss directory
2. deactivate the autoupdate `cron` job
3. stop the `php-fpm` service
4. Try to backup the database as per documentation: ./cli/db-backup.php

A `backup.sqlite` file is in fact created for every user in their respective directory.
They are all `57344` bytes in size and they *all* have the same checksum, hence they're identical. They certainly do not contain all user data for *any* user.

```
SHA256(backup.sqlite)= f97aa0a64956238ba927a29dc440fcb2be4a1eaec00b673c2286663e3d83a670
```

### Expected behavior

The database backups do get created in `./data/users/*/backup.sqlite` and I can use that data to restore to the new MariaDB server.

Actual result:

`./cli/db-backup.php`

For each user I get:

```php
FreshRSS backup database to SQLite for user “MacLemon”…
Start SQL copy…
Error during SQLite copy of categories!
```

script return value is `1`.

### FreshRSS version

1.24.1

### Environment information

- Database version:
  - Old MySQL Server: 5.7.44
  - New MariaDB Server: 10.11.8
- PHP version: PHP 8.2.20
- Installation type: `git`
-Web server type: `nginx 1.25.4` (doesn't seem relevant, since the whole process takes place without any web connections)
- Device: Any Client
- OS: Server: FreeBSD 13.2-p11
- Browser: n/a (Verified that I can login and there are no feeds with Firefox 127.0.2, Google Chrome 126.0.6478.127,)
  - In any case, everything is shown when using the old DB server, no feeds after trying to migrate to the new DB server.

**Comment by Alkarex** [comment]
Hello,
Could you check whether you might have a category and a user label with the same name?

**Comment by Alkarex** [comment]
Could you try https://github.com/FreshRSS/FreshRSS/pull/6638 ?

**Comment by Alkarex** [comment]
There should be some entries in your FreshRSS logs with `SQL error`. Could you try:

```sh
cd FreshRSS
sudo grep -i 'SQL error' -r data/
```

**Comment by MacLemon** [comment]
> Hello, Could you check whether you might have a category and a user label with the same name?

As far as I can tell, no.

**Comment by MacLemon** [comment]
> There should be some entries in your FreshRSS logs with `SQL error`. Could you try:
> 
> ```shell
> cd FreshRSS
> sudo grep -i 'SQL error' -r data/
> ```

```log
data/users/MacLemon/log.txt:[Mon, 22 Jul 2024 19:58:28 +0000] [error] --- SQL error FreshRSS_CategoryDAO::addCategory["HY000",1,"no such table: tag"]
data/users/MacLemon/log.txt:[Mon, 22 Jul 2024 20:00:26 +0000] [error] --- SQL error FreshRSS_CategoryDAO::addCategory["HY000",1,"no such table: tag"]
```

**Comment by Alkarex** [comment]
* Could you please send me one of your `.sqlite` exported files?
* And also check if you can spot any other relevant log lines
* And also check that your local `app/SQL/install.sql.sqlite.php` contains those lines:
https://github.com/FreshRSS/FreshRSS/blob/0eeac4a669e46fb6521ae1765b23656c9afc43de/app/SQL/install.sql.sqlite.php#L86-L91

**Comment by MacLemon** [comment]
- Sure, here's [a download link](https://blackmoor.maclemon.at/s/3JDEMq5rZ4KajQM) of the created file. (SHA256: `f97aa0a64956238ba927a29dc440fcb2be4a1eaec00b673c2286663e3d83a670`)
- Shell output during the backup process
```sh
FreshRSS backup database to SQLite for user “MacLemon”…
Start SQL copy…
Error during SQLite copy of categories!
```

Lines logged during the backup process
```log
data/users/MacLemon/log.txt:[Mon, 05 Aug 2024 12:26:10 +0000] [error] --- SQL error FreshRSS_CategoryDAO::addCategory["HY000",1,"no such table: tag"]
data/cache/a12173fbb78b783ef7e1f50985536c9e9a8802e8.spc:<li>Better stack trace for SQL errors <a href="https://github.com/FreshRSS/FreshRSS/pull/5916" data-hovercard-type="pull_request" data-hovercard-url="/FreshRSS/FreshRSS/pull/5916/hovercard">#5916</a></li>
data/cache/ec39ccb8c30a441e13574fb6efc17da24860c5f8.spc:  <li><strong>CE/EE:</strong> Fix order of steps to prevent PostgreSQL errors when running migration. (<a href="https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/3355">!3355</a>)</li>
data/cache/ec39ccb8c30a441e13574fb6efc17da24860c5f8.spc:  <li><strong>CE/EE:</strong> Fix sorting issues by votes on the groups issues page results in SQL errors. (<a href="https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/3333">!3333</a>)</li>
```
- I can confirm that the quoted code snippet exists verbatim in `app/SQL/install.sql.sqlite.php`.

Since all the log lines reference this cache file `data/cache/ec39ccb8c30a441e13574fb6efc17da24860c5f8.spc`, here's the content of that file. (Justin case this may help.)

```spc
a:6:{s:5:"child";a:1:{s:27:"http://www.w3.org/2005/Atom";a:1:{s:4:"feed";a:1:{i:0;a:6:{s:4:"data";s:762:"
```

**Comment by Alkarex** [comment]
Strange, your SQLite initialisation seems to have stopped just before:

https://github.com/FreshRSS/FreshRSS/blob/b034ce2ccbc3363127d96fdc3ede298374f2c5bc/app/SQL/install.sql.sqlite.php#L63

Could you please try to move that line higher up, to line 16, and try again.
It will likely fail as well, but I am interested in seeing whether there is any difference in the resulting SQLite file.

**Comment by MacLemon** [comment]
Moving that SQL Statement from line 63 to line 16 does affect the backup process, but not the endresult.

The resulting [`backup.sqlite`](https://blackmoor.maclemon.at/s/4N3aC27K9A9bjqB) file after the SQL change is again identical for all accounts and exactly 16kB in size.
`SHA256(backup.sqlite)= 964e9445328e3af6f51adfe14b5e04247ef7494543711810a356ae3f764bf93b`

Shell output during the process stays identical:

```sh
FreshRSS backup database to SQLite for user “MacLemon”…
Start SQL copy…
Error during SQLite copy of categories!
```

Log output during the backup:

```log
data/users/MacLemon/log.txt:[Thu, 08 Aug 2024 13:43:53 +0000] [error] --- SQL error FreshRSS_CategoryDAO::addCategory["HY000",1,"no such table: tag"]
data/cache/a12173fbb78b783ef7e1f50985536c9e9a8802e8.spc:<li>Better stack trace for SQL errors <a href="https://github.com/FreshRSS/FreshRSS/pull/5916" data-hovercard-type="pull_request" data-hovercard-url="/FreshRSS/FreshRSS/pull/5916/hovercard">#5916</a></li>
data/cache/ec39ccb8c30a441e13574fb6efc17da24860c5f8.spc:  <li><strong>CE/EE:</strong> Fix order of steps to prevent PostgreSQL errors when running migration. (<a href="https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/3355">!3355</a>)</li>
data/cache/ec39ccb8c30a441e13574fb6efc17da24860c5f8.spc:  <li><strong>CE/EE:</strong> Fix sorting issues by votes on the groups issues page results in SQL errors. (<a href="https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/3333">!3333</a>)</li>
```


Sidenote: I've updated to PHP 8.2.22 in the meantime. (Normal server maintenance.)

**Comment by Alkarex** [comment]
Could you please try this patch? https://github.com/FreshRSS/FreshRSS/pull/6701

While SQLite is supposed to support double-quotes for strings, my guess is that for some reason it does not work on your FreeBSD system. Changed to single-quote anyway, as this is the ANSI standard.

**Comment by Alkarex** [comment]
Merged in `edge` branch. Feedback welcome

**Comment by Alkarex** [comment]
FreeBSD seems to override the default SQLite behaviour (DQS): 
* https://www.reddit.com/r/freebsd/comments/1chb82b/sqlite3_pkg_just_became_stricter_with_quoting/
* https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=270064

Interesting move, but it looks like FreeBSD users have been hit by several (backup) failures due to that: 
* https://forum.duplicati.com/t/problems-with-local-database-repair-fails/17972
* https://github.com/qutebrowser/qutebrowser/issues/7596
* https://github.com/Tautulli/Tautulli/issues/2015
