### ISSUE TITLE
Gestion des caracteres accentues avec un flux precis

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#661]
J'ai un probleme avec ce flux
http://graphism.fr/feed/atom/

Les caracteres accentues ne sont pas affiche correctement, est ce un probleme avec freshrss ou avec le flux atom ?

RÃ©alisÃ© par Elliptic Labs, voici le nouveau systÃ¨me duÂ Moto X,
au lieu de
Réalisé par Elliptic Labs, voici le nouveau système du Moto X

**Comment by Alkarex** [comment]
Je ferme ici, mais j'ai mis une note de rappel dans https://github.com/FreshRSS/FreshRSS/issues/319
