### ISSUE TITLE
[Bug] User disabled by admin still able to use FreshRSS

### ISSUE THREAD

**Issue by roughnecks** [FreshRSS/FreshRSS#6611]
### Describe the bug

non-admin user who has been disabled from "manage users' UI" is still able to do everything.

### To Reproduce

I am admin of an Instance.

1. Added a non-admin user
2. logged in with that user
3. disabled it from user-managing page:  `/i/?c=user&a=manage`
4. went back to FreshRSS for that user, he's still logged in and can add feeds, read them, everything.

### Expected behavior

Disabled users should not be able to use FreshRSS anymore.

### FreshRSS version

1.24.1

### Environment information

- Database version: SQLite
- PHP version: 8.2.20-1~deb12u1
- Installation type: release tarball
- Web server type: nginx
- OS: Debian 12 server - Win10 client
- Browser: Chrome Versione 126.0.6478.127 (Build ufficiale) (a 64 bit)

**Comment by Alkarex** [comment]
Thanks for the bug report.
Would you be able to test this fix? https://github.com/FreshRSS/FreshRSS/pull/6612

**Comment by roughnecks** [comment]
> Thanks for the bug report. Would you be able to test this fix? #6612

Looks like it's working. When user refreshed page he was logged out and if he tried to login got a 403 - login is invalid.
Hope I have patched those files correctly :-)

Thanks
