### ISSUE TITLE
Option to deactivate notifications

### ISSUE THREAD

**Issue by marienfressinaud** [FreshRSS/FreshRSS#662]
Some users are complaining about notifications (HTML5 notifications and/or favicon). An option to deactivate notifications could be great for them! (only one for both notifications and favicons).

**Comment by Alkarex** [comment]
Feel free to re-open if needed. As far as I can see, this is already provided by the HTML5 standard and implemented in the browsers' UI.

**Comment by cdemi** [comment]
Hi all, do you know if HTML 5 Push Notifications are still working in the latest FreshRSS and Google Chrome? I am having problems described in #2733
