### ISSUE TITLE
[Bug] Max number unread takes multiple feed updates to work

### ISSUE THREAD

**Issue by glottisfaun0000** [FreshRSS/FreshRSS#6620]
### Describe the bug

I'm puzzled by how the "Max number of articles to keep unread" setting is intended to function. I tried it on a high-volume feed expecting only the latest n number of items to appear in my feed unread, but when the feed refreshes all of the new articles are marked unread. If I manually update the feed, it's cut down to the number I entered. Then it seems like when the feed refreshes again it'll pull older articles- can't quite tell, really unpredictable behavior.

I'm not sure that I'm experiencing what's described in https://github.com/FreshRSS/FreshRSS/issues/5702 but per that issue is the described rework (https://github.com/FreshRSS/FreshRSS/issues/5702#issuecomment-1837566893) now merged into :latest ? 

### To Reproduce

1. Add frequently updated feed
2. Set the "Max number of articles to keep unread" in feed settings
3. Refresh feed and observe number kept upread
4. If >n, update feed and number will reduce
5. Wait for feed to repopulate
6. Updating the feed again makes more than n number of articles unread
7. Manually updating feed again reduces unread to setting

### Expected behavior

My expectation is that this would always cap the unread count for a feed and effectively mark everything older than the n most recent articles as read

### FreshRSS version

 1.24.1 

### Environment information

- Docker install

**Comment by Alkarex** [comment]
Hello,
What Docker image are you using, more precisely?

Could you share the feed URL and the settings you are using?

Do you have the option to mark modified articles as unread? Check https://github.com/FreshRSS/FreshRSS/discussions/6101

**Comment by glottisfaun0000** [comment]
linuxserver/freshrss, so up-to-date with :latest

Here's an example feed: `https://www.resetera.com/forums/gaming-headlines.54/index.rss`

Set to 5 max number to keep unread and update once every 12hr. 33 unread when it last updated for me, cuts down to 5 when manually updated from ⚙️ > Update feeds in sidebar

**Comment by Alkarex** [comment]
Patch https://github.com/FreshRSS/FreshRSS/pull/6632
Tests welcome
