### ISSUE TITLE
Ajout de flux multiples

### ISSUE THREAD

**Issue by Glaived** [FreshRSS/FreshRSS#663]
Il serait bon d'avoir une fonctionnalité qui permet l'ajout de plusieurs flux d'un coup, y aurais deux méthodologie que j'ai en tête:
- Une textarea, un flux par ligne, une catégorie pour tous les flux.
- Ajout de flux multiple dynamique, on nous affiche deux lignes (à chaque fois, un champ pour le flux, et un select pour la catégorie), si les deux lignes sont remplies, on affiche une 3ème ligne vierge, prêt à être rempli, etc etc

**Comment by aledeg** [comment]
Je me demande si on ne pourrait pas fermer ce ticket et cela pour deux raisons. La première est qu'il est très ancien et qu'il n'a pas reçu de commentaires depuis 2014. La seconde est qu'il existe des convertisseurs de texte en OPML. Ils doivent fonctionner beaucoup mieux que tout ce que l'on pourrait faire et ça fera moins de chose à supporter.
Pour info, voici ce que j'ai trouvé :
 - [OPML generator](https://opml-gen.ovh/) (en ligne).
 - [Pandoc - About pandoc](https://pandoc.org/) (à installer).
 - [txt2opml - Convert from txt to opml - Alterfiles](https://alterfiles.com/convert/txt/opml) (en ligne).

Si ça a du sens de conserver ce genre d'information, on peut ajouter un bloc dans la documentation.

**Comment by Alkarex** [comment]
Effectivement @aledeg 👍
