### ISSUE TITLE
[Feature] Use filters actions to favourite/bookmark incoming articles

### ISSUE THREAD

**Issue by Tywele** [FreshRSS/FreshRSS#6639]
**Is your feature request related to a problem? Please describe.**
Right now it seems like it's only possible to mark articles as read depending with filter actions either globally, per category or per feed.

**Describe the solution you’d like**
It would be really nice if we could use filter actions to mark articles as favourite/bookmark articles to make it easier to organise incoming articles.

**Comment by Alkarex** [comment]
At the moment, what we can offer is some automated labelling:
https://github.com/FreshRSS/FreshRSS/pull/5954

**Comment by Tywele** [comment]
I think my suggestion would mostly help for people who use FreshRSS in Android or iOS apps where the labels don't help much since you can't view them really when in other apps. I almost never read my articles in FreshRSS directly.

**Comment by Alkarex** [comment]
New global option implemented in https://github.com/FreshRSS/FreshRSS/pull/6648
If @Tywele or someone else is willing to test it carefully, then we can target FreshRSS 1.24.2, otherwise it will wait till 1.25.

**Comment by Alkarex** [comment]
Tested fine so far. Merged in `edge` branch for wider testing
