### ISSUE TITLE
[Feature] Add more options in 'Mark as read' drop-down menu

### ISSUE THREAD

**Issue by arseru** [FreshRSS/FreshRSS#6643]
**Is your feature request related to a problem? Please describe.**
The drop-down menu has 2 options for marking items as read older than: one day, or one week.
![freshrss](https://github.com/user-attachments/assets/ca30e3a0-7d89-4b33-8ac9-87e55a43020d)

**Describe the solution you’d like**
I'd like to request if it would be possible for the developers to add more options to that menu, e.g. similar to what I can find in inoreader:
![inoreader](https://github.com/user-attachments/assets/d8947b5c-a8f8-4e94-9730-3ebea6c271a5)

**Describe alternatives you’ve considered**
Maybe an alternative could be to only add a new menu item where you can enter the number of custom days (`Older than N days`), but I'm more in favor of the approach above.

**Additional context**
I just wanted to use this section to thank the developers of FreshRSS for all their work - I've tried many different self-hosted news aggregators and FreshRSS is by far my favorite! I'd like to contribute code in the future, but I'm no PHP expert yet :see_no_evil:

**Comment by Alkarex** [comment]
Hello and thanks for your message.
Regarding your question, PR welcome. In the meantime, you can save a *user query* to search for articles older than some days and then mark them as read. Example: `!date:P30d` (articles not in the last 30 days)
https://freshrss.github.io/FreshRSS/en/users/10_filter.html#with-the-search-field

**Comment by arseru** [comment]
Nice, I didn't know I could do this and it does the trick, thanks a lot!

I'm closing the issue to avoid adding extra backlog to the project, but once I find the time I'll try to create a PR for it myself :)

**Comment by Alkarex** [comment]
* https://github.com/FreshRSS/FreshRSS/pull/8383
