### ISSUE TITLE
[Bug] Can't update rss flux on 2 web  sites H2 and CERT

### ISSUE THREAD

**Issue by piradix** [FreshRSS/FreshRSS#6658]
### Describe the bug

IT has read rss flux from this 2 sites. But know, it don't read new articles
This rss flux are :

- https://www.cert.ssi.gouv.fr/alerte/feed/
- https://h2database.com/html/newsfeed-rss.xml

### To Reproduce

There are no error on log !

### Expected behavior

show article missing

### FreshRSS version

1.24.1

### Environment information

- Database version: [e.g. Mysql 5.7, SQLite]
- PHP version: [e.g. PHP 8.1]
- Installation type: [e.g. Docker, Docker image source, git, Yunohost]
-Web server type: [e.g. Apache, nginx]
- Device: [e.g. iPhone13]
- OS: [e.g. Ubuntu 22.04, Win10, MacOS14]
- Browser: [e.g. Firefox 124]

**Comment by Alkarex** [comment]
What articles are missing, more precisely?

**Comment by piradix** [comment]
>What articles are missing, more precisely?
all new articles

The first import was ok, but now it don't import anything

**Comment by Alkarex** [comment]
For the first feed, have you received *[Vulnérabilité dans OpenSSH (01 juillet 2024)](https://www.cert.ssi.gouv.fr/alerte/CERTFR-2024-ALE-009/)*? If yes, all is good. The feed has not been updated since 1st of July, but you might want to try https://www.cert.ssi.gouv.fr/feed/

For the second feed, it is a different case. The feed declares the same link for all articles. We used to have a workaround for such feeds, also for broken feeds with deplicated GUIDs, but that workaround does not seem to work anymore. I will try to fix.

**Comment by piradix** [comment]
When I read the rss of  https://www.cert.ssi.gouv.fr/feed/ the date of 
last item  is "Wed, 24 Jul 2024 08:53:11 +0000" (today), but I don't see 
it .
<item>
<title>
Multiples vulnérabilités Microsoft GroupMe (24 juillet 2024)
</title>
<link>
https://www.cert.ssi.gouv.fr/avis/CERTFR-2024-AVI-0623/
</link>
<description>
De multiples vulnérabilités ont été découvertes dans les produits 
Microsoft. Elles permettent à un attaquant de provoquer une élévation de 
privilèges.
</description>
<guid isPermaLink="true">
https://www.cert.ssi.gouv.fr/avis/CERTFR-2024-AVI-0623/
</guid>
<pubDate>Wed, 24 Jul 2024 08:53:11 +0000</pubDate>
</item>


>For the second feed, it is a different case. The feed declares the same 
link for all articles. We used to have a workaround for such feeds, also 
for broken feeds with deplicated GUIDs, but that workaround does not seem 
to work >anymore. I will try to fix.
merci. 
If there's anything I can do ....






From:   "Alexandre Alapetite" ***@***.***>
To:     "FreshRSS/FreshRSS" ***@***.***>
Cc:     "Piradix" ***@***.***>, "Author" 
***@***.***>
Date:   24/07/2024 16:46
Subject:        Re: [FreshRSS/FreshRSS] [Bug] Can't update rss flux on 2 
web  sites H2 and CERT (Issue #6658)



For the first feed, have you received Vulnérabilité dans OpenSSH (01 
juillet 2024)? If yes, all is good. The feed has not been updated since 
1st of July, but you might want to try https://www.cert.ssi.gouv.fr/feed/
For the second feed, it is a different case. The feed declares the same 
link for all articles. We used to have a workaround for such feeds, also 
for broken feeds with deplicated GUIDs, but that workaround does not seem 
to work anymore. I will try to fix.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: 
***@***.***>

**Comment by Alkarex** [comment]
Internal note (for h2database, the other one seems to work as it should): I do not think it is a regression, but a case of a feed without guid AND non-unique links, which I do not believe we ever supported. Related to https://github.com/FreshRSS/FreshRSS/pull/4487

**Comment by Alkarex** [comment]
Same as https://github.com/FreshRSS/FreshRSS/issues/4485#issuecomment-1205199595

**Comment by piradix** [comment]
>Internal note (for h2database, the other one seems to work as it should): 
I do not think it is a regression, but a case of a feed without guid AND 
non-unique links, which I do not believe we ever supported. Related to 
#4487
As it's not available, I looked and found another rss feed, of the atom 
type:  :https://h2database.com/html/newsfeed-atom.xml
it work correctly
Consider problem H2 solved

thank you for time



It rest the problem of : https://www.cert.ssi.gouv.fr/feed/
it was updated today, (look the last item)

**Comment by Alkarex** [comment]
If there is anyone around interested in testing the new possibility to control the unicity policy of a problematic feed, your feedback would be welcome https://github.com/FreshRSS/FreshRSS/pull/4487
