### ISSUE TITLE
[Bug] deactivated feed (désactivé in FR) is not honored in 1.24.1

### ISSUE THREAD

**Issue by danc** [FreshRSS/FreshRSS#6669]
### Describe the bug

deactivated feeds (see screenshot) now are scraped and presented in the articles list
![Capture d’écran 2024-07-31 à 11 17 39](https://github.com/user-attachments/assets/07d86f80-5429-4168-ac72-47b9ba5fdf1e)

### To Reproduce

1. Go to feed management
2. Click on 'désactivé'

### Expected behavior

corresponding feeds should not be scraped and their articles not displayed

### FreshRSS version

1.24.1

### Environment information

- Database version: ?
- PHP version: ?
- Installation type: ?
-Web server type: ?
- Device: macbook
- OS:  MacOS14
- Browser: Firefox 127

**Comment by Alkarex** [comment]
The bug is related to feeds updated by WebSub.

@danc Est-ce que vous pourriez tester ce patch? https://github.com/FreshRSS/FreshRSS/pull/6671

**Comment by danc** [comment]
Désolé, je n'ai pas accès au serveur.
