### ISSUE TITLE
Cannot re-login after logout

### ISSUE THREAD

**Issue by barbuslex** [FreshRSS/FreshRSS#667]
Hi,

Sometimes when i logout my session in FreshRSS, i cannot relog me.
When i click on "Login" button in home page, the page is refreshed but i'm not logged.
My username and password is correct.

I wait a little time and after quit/launch my browser it's work.

Anyone has the same problem ?

Thanks

**Comment by marienfressinaud** [comment]
I think this bug was related to https://github.com/FreshRSS/FreshRSS/issues/700 which is now fixed. Code has so much changed since 0.8.1 that I think this ticket is no longer relevant anyway. I close it.
