### ISSUE TITLE
[Bug] Unexpected http requests from FreshRSS  front-end

### ISSUE THREAD

**Issue by toyo2333** [FreshRSS/FreshRSS#6696]
### Describe the bug

after add  this:    https://www.v2ex.com/feed/vxna.xml to FreshRSS 

there are a lot of http request were send from my computer (found in F12 Console of chrome) when i open freshRSS

some succesed and some failed with error "403" or "CORS Error"

why FreshRSS front-end send http request even if i did NOT open the feed content and did NOT click those links,WHY?

### To Reproduce

after add https://www.v2ex.com/feed/vxna.xml to FreshRSS

there are a lot of http request were send from my computer (found in F12 Console of chrome) 

some succesed and some failed with error "403" or "CORS Error"

why FreshRSS front-end send http request even if i did NOT open the feed content and did NOT click those links,WHY?

### Expected behavior

what if some links has malicious code （a safety hazard）？or big size content （Waste of my bandwidth data）

### FreshRSS version

latest

### Environment information

- Installation type: docker
-Web server type: [e.g. Apache, nginx]

- OS: win11
- Browser: Chrome latest version

### Additional context

some feed with images has the same problem

**Comment by Alkarex** [comment]
Hello,
I cannot reproduce any problem with that feed. What are the requests more precisely? Provide details and screenshots.
What Docker image are you using, more precisely?

**Comment by Frenzie** [comment]
I don't see anything odd after adding that feed either.

In addition to what @Alkarex said, for any specific request you can look for "Initiator".
![Screenshot_20240805_094345](https://github.com/user-attachments/assets/025b7ece-2461-4bd5-ba1f-673696e7a7f9)

**Comment by toyo2333** [comment]
> Hello, I cannot reproduce any problem with that feed. What are the requests more precisely? Provide details and screenshots. What Docker image are you using, more precisely?


![zzz](https://github.com/user-attachments/assets/4e5aa33b-6371-4e83-9e31-d5a83e07c661)

image: freshrss/freshrss:latest

1. add https://www.v2ex.com/feed/vxna.xml t to FreshRSS
2. go to “VXAN” from Left navigation bar menu in FreshRSS
3. open F12 go to network-ALL，F5 refresh
4. the ERROR above appear out there

@Frenzie @Alkarex

**Comment by Frenzie** [comment]
That's not from FreshRSS. I suspect that's a Chrome extension.

**Comment by toyo2333** [comment]
> That's not from FreshRSS. I suspect that's a Chrome extension.

yes ，thanks

it is from a feed sniff extension。ERROR has gone after i disable it
