### ISSUE TITLE
[Feature] Undo "Mark All As Read" for short time afterwards

### ISSUE THREAD

**Issue by Danie10** [FreshRSS/FreshRSS#6697]
**Is your feature request related to a problem? Please describe.**
I sometimes mark a category as read and realise a second or two afterwards I'd actually like to read the last item. 

**Describe the solution you’d like**
Would be great if there was a 5 sec or so option to undo that.

**Describe alternatives you’ve considered**
Nothing else available inside the app.

**Additional context**
Just to say Gmail and similar do offer an unsend for a few seconds after you send a mail.

I saw request https://github.com/FreshRSS/FreshRSS/issues/945 but that was for an undo for a long period. This request is for a few seconds only.

**Comment by felipem775** [comment]
I hope this feature someday

**Comment by math-GH** [comment]
This option in reading config is made for this to think 2 seconds more ;)

![grafik](https://github.com/user-attachments/assets/2ac7a865-f041-4283-ab26-f7dc2e4328c2)

**Comment by Alkarex** [comment]
We could keep a column with the information of when an article has been modified (e.g. changed state) and then propose an option to sort by modification time. This will have to wait till we have a more generic way to sort articles https://github.com/FreshRSS/FreshRSS/issues/2596#issuecomment-1541934281

**Comment by Danie10** [comment]
Actually, thanks to both the above posters, it sparked me to check something else, and I realised that in fact we can just toggle on to see read articles again at the top (I did it on the category as the feed itself was hidden after marking it read). 
![image](https://github.com/user-attachments/assets/ec37f806-c39f-4caa-91bb-37c41090a1de)
So technically this would work as an 'undo' as you can still go and check the items you marked as read. They are not actually deleted, just hidden.

So I'm happy to otherwise close this, unless @Alkarex it is a function that still wants to be added?

**Comment by Alkarex** [comment]
Let's close it for now then. My suggestion requires some significant changes, which will come over time anyway

**Comment by noperator** [comment]
"Confirmation dialog" should be enabled by default 😉

**Comment by Alkarex** [comment]
@noperator PR welcome
https://github.com/FreshRSS/FreshRSS/blob/8b73573a32b23be89b6a8da63bab471480d5b6d0/config-user.default.php#L49
