### ISSUE TITLE
Curl Timeout

### ISSUE THREAD

**Issue by nobicycle** [FreshRSS/FreshRSS#670]
I am sure this issue has little to do with FreshRSS 0.9.1, but I get this in the error log for new subscriptions (However the first subscription worked OK):

cURL error 28: Operation timed out after 10000 milliseconds with 85667 bytes received 

I tried to find a solution, such as 
"curl_setopt($ch, CURLOPT_TIMEOUT,500); // 500 seconds"
,
but have not been successful.
Thanks for the app.
Best wishes

**Comment by Alkarex** [comment]
https://github.com/simplepie/simplepie/pull/407
