### ISSUE TITLE
[Bug] Old posts in feeds revert to unread status

### ISSUE THREAD

**Issue by toyo2333** [FreshRSS/FreshRSS#6700]
### Describe the bug

I've recently noticed that some of the older posts from feeds I've been subscribed to for a long time have gone back to unread status. I've actually marked these feeds as "all read", like this one, which was all read before, but today I realized that all the posts from 2023 have become unread.
![zzz](https://github.com/user-attachments/assets/157c172a-cfc2-471c-980f-7a0e8adc6257)

### To Reproduce

There's no pattern to it. Not all feeds are like this. Most feeds update normally, but individual feeds, all of a sudden, have a bunch of unread articles, go to check them, and realize they're all old articles

### FreshRSS version

latest

### Environment information

- Database version: [built-in SQLite database?]
- Installation type: [ Docker]
-Web server type: [Caddy]
- Device: [PC]
- OS: [win11]
- Browser: [Chrome latest]

**Comment by Alkarex** [comment]
Please check some common reasons for this behaviour https://github.com/FreshRSS/FreshRSS/discussions/6101
A little bit of debugging with that actual feed would be needed to explain what is going on

**Comment by christ4k** [comment]
Since version [1.24.2](https://github.com/FreshRSS/FreshRSS/releases/tag/1.24.2) I have the same problem. My feed has become unreadable because of this... I read the same titles all the time.

**Comment by Alkarex** [comment]
@christ4k Please check https://github.com/FreshRSS/FreshRSS/discussions/6101

**Comment by christ4k** [comment]
> @christ4k Please check #6101

Ok following these directions, I think I solved my problem.
Thank you @Alkarex!

**Comment by Alkarex** [comment]
Excellent. Feel free to summarize what you have done here, in case it might help someone else.

**Comment by christ4k** [comment]
I return after days due to excessive workload. I would be happy to help with something, but I just followed the instructions mentioned above
