### ISSUE TITLE
[Bug] Redirects not being followed in 'Type of feed source'

### ISSUE THREAD

**Issue by jstride** [FreshRSS/FreshRSS#6703]
### Describe the bug

The Google News RSS feed (http://news.google.com/rss?hl=en-AU&gl=AU&ceid=AU:en) will redirect to the source website when opened in a browser, however adding a selector, removing the limit on redirects and setting a user agent all seem to fail to fetch the full content:

![image](https://github.com/user-attachments/assets/284f765b-ab3d-43fd-b803-afa6ceda6849)

This fetches just the RSS:

![image](https://github.com/user-attachments/assets/07dc15c2-a925-4da4-8f59-b49464ed596b)

Even though the link loads the full source:

![image](https://github.com/user-attachments/assets/82adb579-0449-4ab7-9f84-0370a739f324)

### To Reproduce

Add a feed with the following RSS (http://news.google.com/rss?hl=en-AU&gl=AU&ceid=AU:en) source and selectors:

![image](https://github.com/user-attachments/assets/284f765b-ab3d-43fd-b803-afa6ceda6849)

### Expected behavior

This fetches just the RSS truncated text:

![image](https://github.com/user-attachments/assets/07dc15c2-a925-4da4-8f59-b49464ed596b)

Expected behaviour - load the full text in FreshRss from the link loads the full source:

![image](https://github.com/user-attachments/assets/82adb579-0449-4ab7-9f84-0370a739f324)

### FreshRSS version

1.24.1

### Environment information

Running in Docker:

Your PHP version (8.2.18) is compatible with FreshRSS.

You have the cURL library.

You have PDO and at least one of the supported drivers (pdo_mysql, pdo_sqlite, pdo_pgsql).

You have the required library for regular expressions (PCRE).

You have the required library for character type checking (ctype).

You have the fileinfo library.

You have the required library to browse the DOM.

You have the JSON extension.

You have the recommended mbstring library for Unicode.

You have the ZIP extension.

File installation
Permissions on the data directory are good.

Permissions on the cache directory are good.

Permissions on the users directory are good.

Permissions on the favicons directory are good.

Permissions on the tokens directory are good.

**Comment by Alkarex** [comment]
At a quick glance, the redirection goes through a page, which requires JavaScript (which FreshRSS does not support natively).
Try for instance [the first link](https://news.google.com/rss/articles/CBMi4AFBVV95cUxOOHd2WWM4VGxNdUdjSjU5eUlrbHcxcEtWSTZnTFcwZy0wZVJQeGZtcl9WLWtrRXFOVmNtVnQwSTFWYTlfUHA1V3JET0ozODZIb1VCRHBuSHJ6MkhZTldzVGZSbDhES05QeGFOMnNDUld5bTRraGhVa1RseFQ3ZGRCOUJfSWhBdWkzakhwb1RteUVIM0dGdi13c1FJc1hJdXozVkdKZzNIUVJyTm1ka0hVQ0hIeDJ3SlJZWWVnY3I5YW9GT1BnUHdGMzdCYXYwQ0hQUnZGLTl4NDlKdUJoRi1hONIBeEFVX3lxTE84cUVpQXpCN0tVYndvZml0c2gwSjlnOVV2MFlQLW01eDV4SGJWa0ZWS2ZrNm5YT3RVTndfaGRBdVlQMXhvNE5XUlNHU1J2WUVLUGsyXzM1eTc1RmU2cGlQbnpqYzU1ZFQ0V283SWtGRXE3SVRjS2k2Sw?oc=5) in a Web browser with JavaScript disabled: it leads to a blank page.
That would require a FreshRSS extension or another piece of software to deal with it

**Comment by jstride** [comment]
Ah JavaScript, yes you're right. I'll see if I can find something in extensions. Thanks.

**Comment by jstride** [comment]
I can confirm this is a javascript issue
