### ISSUE TITLE
[Feature] bad IMS/INM values?

### ISSUE THREAD

**Issue by jan-vandenberg** [FreshRSS/FreshRSS#6712]
**Is your feature request related to a problem? Please describe.**
I read this post (and the previous posts about RSS readers) and FreshRSS gets some critique:

_Quote: "FreshRSS/1.24.0. This one latched bad IMS/INM values back in *May* and is still sending them. Hella broken."_ 

https://rachelbythebay.com/w/2024/08/02/fs/ 

**Describe the solution you’d like**
I know too little about this, to know if this a serious thing that needs to be fixed (maybe it is only a specific user problem)?

**Describe alternatives you’ve considered**
None! I love FreshRSS and if this is a chance to make it better, than I am all for it.

**Comment by Alkarex** [comment]
Hello,
There is not much information there. I can happily look into a problem if there is some kind of log or debugging information, but this is not usable. What does that even mean *bad IMS/INM values*? If those values do not match, the server will send a new response.

**Comment by Alkarex** [comment]
P.S. If you are interested in helping, please host a static RSS file on a Web server, subscribe to it in FreshRSS, and check the Web server logs (Responses should be 200, and then a series of 304). This way, you might be able to confirm / refute that article.

**Comment by Alkarex** [comment]
Here is a log from my own server, where one can see that FreshRSS gets an HTTP 304 response back as it should, and at the demanded frequency (in this case, 30 minutes):

```
2024-08-16T09:35:23.245059503Z alexandre.alapetite.fr XX.XX.XX.XX - - [16/Aug/2024:09:35:23 +0000] "GET /blog/rss.rdf.fr.xml HTTP/1.1" 304 360 "https://alexandre.alapetite.fr/blog/rss.rdf.fr.xml" "FreshRSS/1.24.2-dev (Linux; https://freshrss.org)" 1321us
2024-08-16T10:05:31.450814828Z alexandre.alapetite.fr XX.XX.XX.XX - - [16/Aug/2024:10:05:31 +0000] "GET /blog/rss.rdf.fr.xml HTTP/1.1" 304 360 "https://alexandre.alapetite.fr/blog/rss.rdf.fr.xml" "FreshRSS/1.24.2-dev (Linux; https://freshrss.org)" 1465us
2024-08-16T10:35:25.032815160Z alexandre.alapetite.fr XX.XX.XX.XX - - [16/Aug/2024:10:35:25 +0000] "GET /blog/rss.rdf.fr.xml HTTP/1.1" 304 360 "https://alexandre.alapetite.fr/blog/rss.rdf.fr.xml" "FreshRSS/1.24.2-dev (Linux; https://freshrss.org)" 1444us
2024-08-16T11:06:06.343184466Z alexandre.alapetite.fr XX.XX.XX.XX - - [16/Aug/2024:11:06:06 +0000] "GET /blog/rss.rdf.fr.xml HTTP/1.1" 304 360 "https://alexandre.alapetite.fr/blog/rss.rdf.fr.xml" "FreshRSS/1.24.2-dev (Linux; https://freshrss.org)" 1400us
2024-08-16T11:35:28.902072349Z alexandre.alapetite.fr XX.XX.XX.XX - - [16/Aug/2024:11:35:28 +0000] "GET /blog/rss.rdf.fr.xml HTTP/1.1" 304 360 "https://alexandre.alapetite.fr/blog/rss.rdf.fr.xml" "FreshRSS/1.24.2-dev (Linux; https://freshrss.org)" 1662us
```

Additional information much welcome, otherwise I will consider the bug report bogus.

I quickly manually checked https://rachelbythebay.com/w/atom.xml and got a 429 response at the second request... One strong hypothesis, which could explain why the author observes so many software misbehaving is that there is something wrong with the server...

**Comment by Frenzie** [comment]
The server indeed returns 429 as soon as you do a second request, in combination with `Retry-After: 86400` (24 hours). A possible hypothesis is that this value isn't honored, or in any case it doesn't seem to be in our source at a (very!) quick glance, which if combined with the 24 hour period resetting after each request could lead to an eternal loop of querying every half hour with no result, and hence retaining an IMS value from May. I think this is worth investigating, but I'm not sure if I have the time.

```
Slow down your request rate.
---
Unconditional requests: at most once per 24 hour period.
Conditional requests: at most once per 60 minute period.
```

A quick search on the site shows that number is [on purpose](https://rachelbythebay.com/w/2024/05/27/feed/). Which is fine, but it does mean it's more of a trickster server (which is highly desirable for testing) than something that accurately reflects typical behavior. That matters insofar as the OP link gave me the impression that it was just a boring standard Apache seeing very strange behaviors, but maybe that's on me.

>  A while back, I added a "Retry-After: " header to the feed. Anyone who gets a 429 will also get intel on when they should try back. It's in seconds, so it'll be something like 3600 or 86400 depending on which kind of request was sent in the first place.
>
> There are feed services which will actually reset their countdowns every time someone trips a 429. **I'm not doing that. Yet.** (emphasis added)
>
> This is why noticing and honoring that header matters.

**Comment by Alkarex** [comment]
Nice investigation @Frenzie 👍🏻
Retry-after (which we do not support) is not related to conditional requests (which we do support correctly according to my tests and in contradiction to the blog post claims).
We could consider supporting it, but I would be curious to find at least a could of other feeds supporting it...
Furthermore, the server should/could support WebSub for pushing responses, which would automatically reduce FreshRSS polling frequency to once daily

**Comment by Frenzie** [comment]
> We could consider supporting it, but I would be curious to find at least a could of other feeds supporting it...

I'm not sure I've ever seen values above 120 seconds or so in the wild myself (not that I'm on the lookout for it so that may not even qualify as n=1), which would easily be covered by the much higher default maximum refresh frequency.

Setting aside `429`, however, `Retry-After` is sometimes used in the wild for `503` (to prevent `404` during downtime). I doubt you'd see any values lower than 10 minutes or so for that, and 24 hours would be perhaps unusual but nevertheless unsurprising in that case.

**Comment by Alkarex** [comment]
We could also consider reacting somehow to "HTTP/1.1 429 Too Many Requests", but this is not trivial, because it might just as well be due to many requests coming other clients than the given FreshRSS instance, for instance sharing the same IP or proxy. For now, it is just considered an error by FreshRSS, just like 404 or 500.

**Comment by Alkarex** [comment]
And FreshRSS has a hard-coded minimum period of 15min at feed level, and 20 minutes at global level - despite some users asking for 1 minute - to preserve the ecosystem.

**Comment by Alkarex** [comment]
@jan-vandenberg If you know the author of the blog, you are welcome to forward an invite to this thread

**Comment by jan-vandenberg** [comment]
(I think Rachel is a she) I dropped her a line via her blog, I don't have any other contact info. I am not sure if she is inclined / has time to give some pointers. FYI the blog is pretty well read/known and often shares insightful tech stories.

**Comment by Frenzie** [comment]
> We could consider supporting it, but I would be curious to find at least a could of other feeds supporting it...

Speaking in untested pseudocode, would anything more than something like this be needed to support it?

```diff
diff --git a/lib/SimplePie/SimplePie.php b/lib/SimplePie/SimplePie.php
index 25dcc7fa..25cc4569 100644
--- a/lib/SimplePie/SimplePie.php
+++ b/lib/SimplePie/SimplePie.php
@@ -1721,7 +1721,14 @@ class SimplePie
                                        else
                                        {
                                                $this->check_modified = false;
-                                               $cache->touch();
+                                               if (($file->status_code === 429 || $file->status_code === 503) && isset($this->data['headers']['retry-after']))
+                                               {
+                                                       $parser = $this->registry->call('Parse_Date', 'get');
+                                                       $cache->touch($parser->parse($this->data['headers']['retry-after']));
+                                               }
+                                               else {
+                                                       $cache->touch();
+                                               }
                                                $this->error = $file->error;
                                                return !empty($this->data);
                                        }
```

**Comment by Alkarex** [comment]
That could be an idea @Frenzie 
I quickly looked at the feed, expecting some kind of standard way to express the servers' refresh preferences, but there was none...
For instance [`ttl`](https://www.rssboard.org/rss-specification#ltttlgtSubelementOfLtchannelgt) (which we do not support yet, but [we should](https://github.com/FreshRSS/FreshRSS/issues/6721)), or [`sy:updateFrequency`](http://purl.org/rss/1.0/modules/syndication/)

**Comment by Frenzie** [comment]
There's also the factor missing in what I wrote above that no matter what the site says, is it fruitful to honor a value higher than a week or so, maybe a month? At some point it starts to either defeat the purpose or the site is misconfigured.

But if you combined `Retry-After` with a regular 200 (which this site does not) it could serve as a decent way to indicate such a preference.

**Comment by jan-vandenberg** [comment]
Rachel made a follow up post (I think it is specifically referring to this closed (?) thread): 

https://rachelbythebay.com/w/2024/08/17/hash/

**Comment by Alkarex** [comment]
Interesting, at last there is a bit of information (the first blog post was not usable at all), even though that is really a circumvoluted way of reporting bugs.
There is actually a related work-in-progress rewrite of that part in https://github.com/FreshRSS/FreshRSS/pull/4374

**Comment by Frenzie** [comment]
I'm somewhat surprised the `if-last-modified` seems to taken from a cached `last-modified` instead of simply using the time the cache itself was touched. I assume that's to work around certain servers? Because if not that strikes me as overengineering that increases the chance of failure. But indeed if it can't be simplified, last-modified should be part of the md5 hash.

**Comment by jan-vandenberg** [comment]
Is it useful to re-open this issue?

**Comment by Alkarex** [comment]
I have a PR coming. But that is really a niche issue.

**Comment by Alkarex** [comment]
See https://github.com/FreshRSS/FreshRSS/pull/6723
Additional tests welcome

**Comment by Alkarex** [comment]
> instead of simply using the time the cache itself was touched

@Frenzie For clients, `if-last-modified` is typically passed as string from the last copy of `last-modified` without any attempt of converting that to a date. Meanwhile, servers are often making a simple string exact-match, and not an actual date comparison.

https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.25

      Note: If-Modified-Since times are interpreted by the server, whose
      clock might not be synchronized with the client.

      Note: When handling an If-Modified-Since header field, some
      servers will use an exact date comparison function, rather than a
      less-than function, for deciding whether to send a 304 (Not
      Modified) response. To get best results when sending an If-
      Modified-Since header field for cache validation, clients are
      advised to use the exact date string received in a previous Last-
      Modified header field whenever possible.

Slightly reformulated in https://www.rfc-editor.org/rfc/rfc7232#section-3.3 but same result

**Comment by Frenzie** [comment]
Though the 1994 date in the example does make you wonder what behavior actually is in 2024. :-) But indeed, it's easily done.

**Comment by Alkarex** [comment]
Help welcome to test this PR https://github.com/FreshRSS/FreshRSS/pull/4374

**Comment by jan-vandenberg** [comment]
FreshRSS got mentioned again?

https://rachelbythebay.com/w/2025/03/03/feed/

> There are also two FreshRSS instances which are both sending 100% unconditionals. What happened here? Over and over, it's just this sort of request:
> 
> ```
> Host: <redacted>
> User-Agent: FreshRSS/1.26.1-dev (Linux; https://freshrss.org)
> Accept: */*
> Accept-Encoding: deflate, gzip, br, zstd
> ```
> I just don't understand.

**Comment by Alkarex** [comment]
Thanks for the heads up.
I do not believe we have FreshRSS requests sending `Accept: */*` (except for favicon) so I am not sure what those requests are.
I will try to look a bit more into it.

**Comment by Frenzie** [comment]
That kind of makes me wonder if that's just a curl -A or equivalent. cURL doesn't send an accept-encoding header at all if you don't set one, does it?

https://github.com/FreshRSS/FreshRSS/blob/03aec8b54e03a767282f6c886113df35bac9cf00/lib/simplepie/simplepie/src/File.php#L200-L202

Edit: though that could also be a Caddy or Nginx proxy I suppose.

**Comment by Alkarex** [comment]
My quick tests indicate that everything seems to work as expected, except for Rachel's server. I have written to her.
Tests welcome on other servers. @Frenzie you could maybe check in your logs for https://fransdejonge.com/feed/ whether conditional requests are working as expected.

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/simplepie/pull/33

**Comment by Alkarex** [comment]
Tests welcome https://github.com/FreshRSS/FreshRSS/pull/7403

**Comment by Frenzie** [comment]
> @Frenzie you could maybe check in your logs

I saw 304 from FreshRSS when I just checked fwiw and a regular 200 needn't really mean anything, but I don't think I have any logs of request headers.

**Comment by Alkarex** [comment]
Related: Tests and feedback welcome:
* https://github.com/FreshRSS/FreshRSS/pull/7760
