### ISSUE TITLE
Fever API items call, ids should be integers but are strings

### ISSUE THREAD

**Issue by Shinokuni** [FreshRSS/FreshRSS#6716]
### Describe the bug

I'm working on Fever API implementation in [Readrops](https://github.com/readrops/Readrops) and ran into an issue when comparing FreshRSS implementation and Miniflux one. FreshRSS returns item ids as strings and Miniflux integers.

Based on [this](https://web.archive.org/web/20221221112459/https://feedafever.com/api) which seems to be the official documentation, it is stated that item ids should be integers and not strings.

Could you take a look at this?

Thanks!

### To Reproduce

Make an `/api/fever.php/?items` call.

### FreshRSS version

1.24.0

### Environment information

- Database version: Mysql 15.1
- PHP version:  8.2.12
- Installation type: git
- Web server type: Apache

**Comment by Alkarex** [comment]
Hello,
I will take a look. But if possible, please concentrate on the GReader API. The Fever API is pure legacy, being less efficient and with fewer features.

**Comment by Alkarex** [comment]
All right, our article IDs are 64-bit integers, so to ensure that they can be safely produced by 32-bit servers and consumed by 32-bit clients, they are serialised as numeric strings. This is also the approach taken by the GReader API, by the way.
It is a big problem for you to accept both numeric strings and native (64-bit) integers?

**Comment by Shinokuni** [comment]
Not at all, I can handle this. But some clients might break as they would expect only integer ids.

**Comment by Alkarex** [comment]
> Not at all, I can handle this. But some clients might break as they would expect only integer ids.

Excellent then. Let's keep it as it is so. Many clients have been working fine already, so that does not seem to be a problem.
Thanks for the feedback anyway.
