### ISSUE TITLE
About favorites display

### ISSUE THREAD

**Issue by Jucgshu** [FreshRSS/FreshRSS#672]
As of today, favorites follow global configuration : articles are shown if unread or if unread articles is selected as opton in the configuration.

In most cases, I mark as favorites articles that are already read or articles I want to read later. In any case, every articles I mark as favorites end up read in FFRS.

What do you think about :
- Display favorites no matter what they are read _or_ unread ?
- Keep categories behavior according to the option selected in the configuration (i.e. : adapt the "adjust showing" option which is a little weird when favorites are selected) ?

**Comment by marcomrc** [comment]
In Archiving menù there's the option to remove articles after X months.

Theres's the possibility to delete all after X months except favorites/starred articles?

Thanks

**Comment by marienfressinaud** [comment]
@marcomrc > that's already the case: we keep starred articles safe from the "remove after X months" option.

**Comment by bit101** [comment]
To clarify my suggestion: I'd like to see an extra dropdown in Reading settings:

Articles to Display in Main Stream: adjust showing / show all articles / show only unread
Articles to Display in Favorites: adjust showing / show all articles / show only unread

**Comment by Alkarex** [comment]
@bit101 Did you try using the "Adjust showing" option of "Articles to display"? It sounds like it could work well for your workflow

**Comment by bit101** [comment]
Interesting. "Adjust showing" does seem to do what I want now. Initially when I tried that mode, it was not. Where is there a description of what this mode is supposed to do? The name is not very descriptive. At any rate, this is great. Just what I wanted, thanks.
- update: I see now. It shows unread unless all are unread, in which case, it shows all. That's what confused me before.

**Comment by marienfressinaud** [comment]
I think [this PR](https://github.com/FreshRSS/FreshRSS/pull/2766) addressed the initial issue, I close the ticket. @Jucgshu if you continue to use FRSS 5 years later, you'll find an option in the next release that does what you wanted ;)
