### ISSUE TITLE
[Bug] Docker documentation for ports incorrect

### ISSUE THREAD

**Issue by mtalexan** [FreshRSS/FreshRSS#6727]
### Describe the bug

Apache within Docker has a well known limitation that it doesn't work properly when a published port is remapped, i.e. `-p 8080:80` doesn't work.  This exact non-working case is used all thru the Dockerfile documentation.

Instead, implementation needs to not remap the port, and change the Apache listening port, i.e. `-p 8080:8080 -e LISTEN=0.0.0.0:8080`.

### To Reproduce

1. Copy the default docker-compose file
2. Start the docker compose file
3. Connect to `http://127.0.0.1:8080`
4. The FreshRSS web page loads as a blank white page

### Expected behavior

The FreshRSS web page loads with content

### FreshRSS version

1.24.2-dev  (current `:edge` docker image)

### Environment information

- Database version: SQLite (docker image default)
- PHP version: docker image default
- Installation type: Docker
-Web server type: Apache (docker default)
- Device: x86_64 server
- OS: Linux (Opensuse MicroOS)
- Browser: Firefox 129

### Additional context

This is a well documented issue when running Apache within a container. Many containers serving active websites suffer from it.

This purely impacts the current documentation, but would be impossible to overcome if I didn't already know about the Apache limitation.

**Comment by mtalexan** [comment]
I'm in the process of submitting a PR to fix this documentation.

**Comment by Frenzie** [comment]
What does "doesn't work properly" mean?

**Comment by mtalexan** [comment]
> What does "doesn't work properly" mean?

The Apache web server within the container will fail to load anything but a blank page when the published port and the listening port aren't matched. I don't understand the technical details myself, but it's a well documented issue.

The solution is that the published port and the listening port need to be set to match.  It can still be changed to whatever port you want, they just have to be changed together.

**Comment by mtalexan** [comment]
I discovered this problem while setting up a new instance that's running the `:edge` container image in a docker-compose configuration.  
I was able to reach the site just fine, but no matter what I did it would always just come up as a blank page. By happenstance, I've deployed other services somewhat recently that document this problem/limitation, so I gave the fix a try and confirmed it does in fact immediately fix the blank page issue (I only changed the inner port of the exposed port and listening port to match the outer port and suddenly everything was working as expected).

**Comment by Alkarex** [comment]
Hello, 
I have been using the current approach without problem for years, on multiple systems including Ubuntu, WSL, Debian, and on different architectures. Is it specific to Suse?
What Docker version?
Do you happen to have a link to a bug report at Docker or Apache level?

**Comment by Frenzie** [comment]
Well documented by whom? Where? I haven't noticed any issues in well over a decade.

Dev image sample but it's the same for all:
![image](https://github.com/user-attachments/assets/a3740c11-d26f-4a3a-abae-ca1951af1041)

**Comment by Frenzie** [comment]
PS Only Ubuntu and Debian for me, but that does include Ubuntu on arm64 as well.

**Comment by mtalexan** [comment]
Maybe I'm mistaken about how "well documented" it is, or it's relationship to Apache specifically.  I never would have thought of it but there were a handful of service deployment documents for Linuxserver.io services that are very explicit that you cannot remap certain ports you're exposing on certain services, and you have to match the exposed port to an environment variable that configures the port of the service inside the container as well.

>  Is it specific to Suse?

Almost certainly not, but I can't prove it conclusively. This is within a docker container, which abstracts away most of the distro-specific variations.  I've also been running dozens of other services on this same SUSE server for years without any other issues, often doing port remapping within them (though none of them use an Apache web server within the container).  

---

Given all the pushback here, I'm going to do a bit more due dillegence on this.

I'd initially assumed that given some of the disorganization of the Docker/README.md and docker-compose files in that folder, this change was just "obvious" to those in-the-know (I've seen that on a lot of projects).  So when I tried this single change (switching only `LISTEN=0.0.0.0:80` to `LISTEN=0.0.0.0:8080` and the port mapping from `8080:80` to `8080:8080`) and it suddenly started working, and I could reproduce the problem and solution consistently by switching back and forth (wiping all data in between each time), I assumed that was evidence for my assumptions about the documentation.

**Comment by mtalexan** [comment]
Ok, I slowly rebuilt my setup step by step from scratch.  I'm not back to the exact configuration that was consistently failing, but now it works as expected ¯\_(ツ)_/¯.

I started from a bare `docker run`, worked my way up to a docker-compose of increasing complexity, and even threw in my custom private network.  Every step kept working.

There's nothing at all different that I can find between the config that was failing consistently before, and the one that's working now.  But I guess it must have been _something_ I did.

Closing, along with the unnecessary PR.

**Comment by mtalexan** [comment]
FWIW, I did some digging for references on the "well documented issue", and it wasn't actually for the Apache server in a container. It was a handful of other webservices, some provided by Linuxserver.io and others just discussed on the Unraid forums.  Some of them happen to use Apache, but clearly it's not specific to it.

**Comment by Alkarex** [comment]
My guess is that you might have changed the default type of Docker network to *host networking* mode, or something like that
https://docs.docker.com/engine/network/drivers/host/

**Comment by Frenzie** [comment]
> I'd initially assumed that given some of the disorganization of the Docker/README.md and docker-compose files in that folder, this change was just "obvious" to those in-the-know (I've seen that on a lot of projects).

It's "obvious" that it's just a random (or perhaps far too common) sample port, but that's about the end of it. :-)

**Comment by mtalexan** [comment]
> guess is that you might have changed the default type of Docker network to _host networking_ mode, or something like that
> https://docs.docker.com/engine/network/drivers/host/

I don't _think_ it was that. Until I had my networking setup properly I couldn't even connect to the page to get a blank white result. But maybe it was related.

**Comment by mtalexan** [comment]
> > I'd initially assumed that given some of the disorganization of the Docker/README.md and docker-compose files in that folder, this change was just "obvious" to those in-the-know (I've seen that on a lot of projects).
> 
> It's "obvious" that it's just a random (or perhaps far too common) sample port, but that's about the end of it. :-)

I meant more that I've seen a lot of projects where docker documentation will have mistakes in it. Depending on your level of expertise reading the documents, you may or may not realize it needs to be corrected. Sometimes that's even a pretty esoteric issue that experts would miss, but people familiar with the specific project have learned to fix in their personal setup.

Glad that's not the case here though.

**Comment by pancho-villa** [comment]
I had the same issue and fixed it using @mtalexan fix suggested in the initial post. I'm running Ubuntu 25.04 and docker version 26.1.4, build 5650f9b. It also affected my ubuntu server 24.04 running docker version 20.10.14, build a224086. Initially I ran the docker run command in the docs and got a blank page. I couldn't troubleshoot my way out of it, then I found this post and the suggestion worked a treat.

I think there is value in adding a small warning to the documentation that gives people a heads up if they get a blank page on startup to add this variable "-e LISTEN=0.0.0.0:8080", and try again. I'll make a pull request if y'all agree this is a reasonable change to the docs.

Thanks

**Comment by Alkarex** [comment]
@pancho-villa This should not be needed, except in the rare cases when people have modified their local Docker networks and I cannot recommend changing the `LISTEN` environment variable, except for advanced users.
https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md#environment-variables

What command did you try, more precisely, and did you find out why it was not working?

Again, for the vast majority of users, the current doc should work fine out of the box (both Docker, and Docker Compose variants). The only change would be to modify 8080 to another available port if 8080 is already used locally by another service. But no need to change `LISTEN` for that. Note that the `-p` option is not intended for production systems, because ports are not supposed to be exposed locally at all, but instead be routed through a proxy that is also doing HTTPS termination, etc.

**Comment by pancho-villa** [comment]
You're right, I screwed up my docker run command and mangled the ports when I was scripting it. The default works fine, sorry for the confusion.
