### ISSUE TITLE
[Bug] OIDC Redirect URL is http for a Proxied web app

### ISSUE THREAD

**Issue by DraviaVemal** [FreshRSS/FreshRSS#6729]
### Describe the bug

The OIDC redirect url request in http mode when the app is applied with SSL via proxy

### To Reproduce

Setup localhost based freshRSS expose the app using proxy that adds the SSL layer
configure the OIDC
the redirect URL request is set as http://custom-url.com instead of https://custom-url.com

### FreshRSS version

1.24.2

### Environment information

I'm using default docker latest image

**Comment by Alkarex** [comment]
Hello,
You need to provide a bit more information about your setup.
The redirect URL is not controlled by FreshRSS.
Have you checked https://freshrss.github.io/FreshRSS/en/admins/16_OpenID-Connect.html and https://freshrss.github.io/FreshRSS/en/admins/16_OpenID-Connect-Authentik.html ?

**Comment by DraviaVemal** [comment]
Sorry for the delay
I will provide the info over the weekend 
As far as my memory 
In setting i can see
https://rss.custom-domain.com
But in my oidc redirect request its expecting 
http://rss.custom-domain.com

Will attach screenshot and further details I find by weekend
