### ISSUE TITLE
[Bug] Unable to 'mark as read' results of some queries

### ISSUE THREAD

**Issue by raqua** [FreshRSS/FreshRSS#6732]
### Describe the bug

I have many feeds and there is content that I am not interested in so I have created and saved multiple queries to filter out the stuff I don't want to read and then I use those to mark that as read.
Some (not all) of those queries can not be marked as read. I will push the button, I get the popup saying that it was marked as read, but the articles remain unread. 
There is nothing in logs, docker logs, user logs that would show any issue. 
I even enabled development profile in config.php hoping to get some log messages, but I still didn't.

When I do the query and get the results, I can copy the query string from search field, click the FreshRss logo to get out of the query results and then paste the query again to search filed, marking as read works, so it should not be an issue with the query itself, but somehow with the saved query ?

### To Reproduce

Example of what does not work for me currently:
Feed: https://www.xda-developers.com/feed/
Query:
```
inurl:xda-developers and
(
  (inurl:'-vs-') or
  (inurl:'how-to-install') or
  (inurl:'how-install-') or
  (intitle:'Windows 11') or
  (intitle:'How to install') or
  (
    (intitle:'best') and
      ( (intitle:'case') or
        (intitle:'protector') or
        (intitle:'band') or
        (intitle:'docking') or
        (intitle:'ssd') or
        (intitle:'graphics') or
        (intitle:'screen protectors') or
        (intitle:'cooler') or
        (intitle:'cpu') or
        (intitle:'monitors') or
        (intitle:'headsets') or
        (intitle:'accessories') or
        (intitle:'earbuds') or
        (intitle:'headphones') or
        (intitle:'chargers') or
        (intitle:'routers') or
        (intitle:'deals') or
        (intitle:'vpn') or
        (intitle:'memory') or
        (intitle:'laptop')
      )
  )
) or
(author:'Mahmoud Itani') or
(author:'João Carrasqueira') or
(author:'Timi Cantisano') or
(author:'Tathagata Biswas') or
(author:'Ayush Pande') or
(author:'Rich Woods') or
(author:'Arif Bacchus') or
(author:'Tanveer Singh') or
(author:'Karthik Iyer') or
(author:'Nimish Sawant') or
(author:'Ben Smith') or
(author:'Pranob Mehrotra') or
(author:'Hassam Nasir') or
(author:'Chris Hachey') or
(author:'Samuel Martinez') or
(author:'Team XDA') or
(author:'Rich Edmonds') or
(author:'Rahul Naskar') or
(author:'Christine Persaud') or
(author:'Ruben Circelli') or
(author:'Tathagata Biswas') or
(author:'Oyewale Damilare') or
(author:'Usama Jawad') or
(author:'Brady Snyder') or
(author:'Cale Hunt') or
(author:'Christopher Burke') or
(author:'Samuel Contreras') or
(author:'Simon Batt') or
(author:'Skanda Hazarika') or
(author:'Asad Khan') or
(author:'Roydon Cerejo') or
(author:'Georgie Peru') or
(author:'Parth Shah') or
(author:'Usama Jawad') or
(author:'Kristen Hilderman') or
(author:'Skanda Hazarika') or
(author:'Karthik Iyer') or
(author:'Zak Khan') or
(author:'Matt Malmlund') or
(author:'Joe Rice-Jones') or
(author:'Richard Devine') or
(author:'Dylan Turck') or
(author:'Michael Bizzaco') or
(author:'Aaron Greenbaum') or
(author:'Ahmad Rafiq')
```

I also have another query that does not work for me, but this is filtering across all my feeds, so I have no specific feed to provide:
```
intitle:'Home Automation Hangout' OR
intitle:'JSBM newsletter' OR
intitle:'Stock Market Analysis Latest' OR
intitle:'NAY Android Roka' OR
intitle:'dostáva Android' OR
intitle:'Smart Banka' OR
intitle:'Mandalorian' OR
intitle:'Daily telescope' OR
intitle:'Engadget Podcast' OR
intitle:'Meilleurs moments' OR
intitle:'Mejores Momentos' OR
intitle:'Hoogtepunten van de race' OR
intitle:'Unikli zábery' OR
(inurl:youtube.com intitle:'shorts') OR
intitle:'Rebel Moon' OR
intitle:'Doctor Who' OR
intitle:'Aquaman' OR
intitle:'One Piece' OR
intitle:'Boba Fett' OR
intitle:'Godzilla' OR
intitle:'X-Men' OR
intitle:'3 Body Problem' OR
intitle:'Mandalorian' OR
intitle:'Fallout' OR
intitle:'Deadpool' OR
intitle:'Suicide Squad' OR
intitle:'Beyond the Grid' OR
intitle:'Daredevil' OR
intitle:'Star Wars' OR
intitle:'Chasing The Dream' OR
intitle:'Best' OR
intitle:'deals' OR
intitle:'F1 Sim Racing' OR
intitle:'Android game and app price drops' OR
intitle:'linuxtoday' OR
intitle:'The best'
```

### Expected behavior

Articles that are returned by the saved query are marked as read when I click that button.

### FreshRSS version

1.24.2

### Environment information

- Database version: SQLite
- PHP version: Whatever version is in the latest Docker image from you
- Installation type: Official Docker image
-Web server type: Apache
- Device: PC, Android phone ... 
- OS: I think Docker image uses Debian, right? 
- Browser: Firefox 129.0.2 on Linux, Firefox on Android

### Additional context

This is not new in the 1.24.2 version, the issue was present also in previous versions.

**Comment by Alkarex** [comment]
Hello,
I suspect there is a confusion regarding how we handle multiple lines, so please send a screenshot.

Regarding your second query in particular, it is to be used with one query per line, without the `OR` like:

```
intitle:'Home Automation Hangout'
intitle:'JSBM newsletter'
```

Same for the first query. You can put all your conditions on a different line.
The first `inurl:xda-developers` should be on a single line, and mind that there is no `AND` operator. `AND` is just the default combination when there is no `OR`.

**Comment by raqua** [comment]
Thank you for your response @Alkarex!
I am not sure I understand it correctly though.

>  I suspect there is a confusion regarding how we handle multiple lines, so please send a screenshot.

Screenshot of what should I send ? 


For the rest of you post ... are you suggesting that I should not be using the ORs in my second query ? 
Because I just tested that and it does not work for me, I get no results.

See my current feed:
![image](https://github.com/user-attachments/assets/050f1209-669e-4d41-8df9-e40d6cb329f6)
When I query for:
```
intitle:'Norris'
intitle:'Haas'
```
... I get no results.

When I query:
```
intitle:'Norris' OR
intitle:'Haas'
```
... I get the result as expected.


Also, please note that my queries do work as expected in terms of getting the results. The filtration does work, just marking the results of the query as read does not.

**Comment by Alkarex** [comment]
Please a screenshot of where you type the queries. It is not the same for the auto-mark-as-read feature (which has multiple lines) than in the search field, which is  a single line.
I am confused by the fact that you show a query on multiple lines

**Comment by raqua** [comment]
Aha, now I see. 
I put the queries to the standard search field that can be seen in the screenshot in my previous comment. I do not use the auto mark as read feature. 
I have the queries saved as multiline because they are easier to work with.

**Comment by Alkarex** [comment]
Ok, then please send an example of not-working query on single line, along with a screenshot

**Comment by raqua** [comment]
I am not sure how I should screenshot it not working, so I made 2 videos instead. Github won't let me upload them here, so I am sharing them through my Google Drive. 

I did not think that it makes difference whether the query is on one line or multiple, but I went and did as you wanted me to anyway. So I took the query for XDA, which I already posted above and modified it to be single line.
Here it is:
```
inurl:xda-developers and(  (inurl:'-vs-') or  (inurl:'how-to-install') or  (inurl:'how-install-') or  (intitle:'Windows 11') or  (intitle:'How to install') or  (    (intitle:'best') and      ( (intitle:'case') or        (intitle:'protector') or        (intitle:'band') or        (intitle:'docking') or        (intitle:'ssd') or        (intitle:'graphics') or        (intitle:'screen protectors') or        (intitle:'cooler') or        (intitle:'cpu') or        (intitle:'monitors') or        (intitle:'headsets') or        (intitle:'accessories') or        (intitle:'earbuds') or        (intitle:'headphones') or        (intitle:'chargers') or        (intitle:'routers') or        (intitle:'deals') or        (intitle:'vpn') or        (intitle:'memory') or        (intitle:'laptop')      )  )) or(author:'Mahmoud Itani') or(author:'João Carrasqueira') or(author:'Timi Cantisano') or(author:'Tathagata Biswas') or(author:'Ayush Pande') or(author:'Rich Woods') or(author:'Arif Bacchus') or(author:'Tanveer Singh') or(author:'Karthik Iyer') or(author:'Nimish Sawant') or(author:'Ben Smith') or(author:'Pranob Mehrotra') or(author:'Hassam Nasir') or(author:'Chris Hachey') or(author:'Samuel Martinez') or(author:'Team XDA') or(author:'Rich Edmonds') or(author:'Rahul Naskar') or(author:'Christine Persaud') or(author:'Ruben Circelli') or(author:'Tathagata Biswas') or(author:'Oyewale Damilare') or(author:'Usama Jawad') or(author:'Brady Snyder') or(author:'Cale Hunt') or(author:'Christopher Burke') or(author:'Samuel Contreras') or(author:'Simon Batt') or(author:'Skanda Hazarika') or(author:'Asad Khan') or(author:'Roydon Cerejo') or(author:'Georgie Peru') or(author:'Parth Shah') or(author:'Usama Jawad') or(author:'Kristen Hilderman') or(author:'Skanda Hazarika') or(author:'Karthik Iyer') or(author:'Zak Khan') or(author:'Matt Malmlund') or(author:'Joe Rice-Jones') or(author:'Richard Devine') or(author:'Dylan Turck') or(author:'Michael Bizzaco') or(author:'Aaron Greenbaum') or(author:'Ahmad Rafiq')
```

It behaves the same way as when I used that query while it was multiline.
I have bookmarked that query as Query No6.

![image](https://github.com/user-attachments/assets/edbd624f-f468-4539-9eab-844a765605f8)



Now please have a look at the first video.
https://drive.google.com/file/d/1a4qlO2yMmxCY7lSgziyYQPqgA4GcyQ02/view?usp=sharing

What I did there:

- I have used that bookmarked query to filter out articles, this worked as expected
- I had 188 unread articles in total in my FreshRss
- I tried to mark the result of this query as read
- I was told it was success
- The number of articles unread is still 188, doing the same query again still returns the articles and they are still unread. So it did not work.
 

Now the second video.
https://drive.google.com/file/d/16O3OEVcu5Ol8UMIg1f7NTD8maOe67a1C/view?usp=sharing

What I did there:

- I have at first tried to do the same as in the first video, so did the query, tried to mark as read. No success.
- Then I again run the bookmarked query and copied it from the search field on top of the screen
- I clicked FreshRss logo, to refresh the screen and empty the search field
- I have pasted the query again to the search field and run it, got results as expected
- I clicked the "Mark as read" button again and this time it worked
- There is 162 remaining unread articles now
- When I retry the bookmarked query, there is no result this time, as expected

I hope this makes it clear.

**Comment by Alkarex** [comment]
I can see it still had some `and`, which need to be removed

**Comment by Alkarex** [comment]
It would be a help if you could try to find a shorter query, but still exhibiting the same bug. It would make the debugging easier.

**Comment by raqua** [comment]
I have removed the 2 "and" from the query and re-tested. Although I only had single article that the query will fetch now, it still behaves the same and the article is not marked as read. 
I can try to find shorter query, but usually the short ones do work and when they work, I need to wait until I again have something to filter on. So it will likely take also very long, if even.

**Comment by raqua** [comment]
I have actually managed to find such query on the first attempt. :) 

Query:
```
intitle:'deals' OR intitle:'Android game and app price drops'
```

Feed: https://9to5google.com/feed/

I believe articles fitting this query are posted daily.

**Comment by Alkarex** [comment]
Thanks @raqua , that is helpful, and I can reproduce the bug

**Comment by Alkarex** [comment]
Would you be able to test this patch? https://github.com/FreshRSS/FreshRSS/pull/6738

**Comment by raqua** [comment]
I am running FreshRss in Docker, would it be possible to build a container with it? 
Or maybe a clear instructions how to apply the patch inside container? I have no knowledge of PHP.

**Comment by Alkarex** [comment]
To test a PR, you need to point your Docker or Docker Compose to the right PR, as such:

```yml
  freshrss:
    image: freshrss/freshrss:6738
    build:
      context: https://github.com/Alkarex/FreshRSS.git#fix-quer-mark-as-read
      dockerfile: Docker/Dockerfile-Alpine
    ...
```

* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/freshrss/docker-compose.yml
* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md#build-custom-docker-image

And by the way, PR welcome to add some tips [to our documentation](https://github.com/FreshRSS/FreshRSS/blob/edge/docs/en/contributing.md) on how to test patches

**Comment by Alkarex** [comment]
Merged in `edge` to ease testing. Feedback welcome

**Comment by raqua** [comment]
I have not managed to build the container with the specific commit you mentioned above with the compose example. 
I though that maybe I was doing something wrong. 

But I was able to build the edge version and test it successfully, not sure why the commit did not work, here is how it went:
![2024-08-27_19-43](https://github.com/user-attachments/assets/c40993f8-f17e-4d3a-a3fa-a157422137e1)

The edge version seems to work as expected and I was able to mark the filtered results as read.
Thank you.

**Comment by Alkarex** [comment]
Great, thanks for the feedback!
Once the PR is merged, its branch is removed, so it is normal that it was not working anymore.
But the edge branch needs not be built manually as it is available as our *rolling release* image `freshrss/freshrss:edge`
