### ISSUE TITLE
[Bug] 1.24.2 - Shortcut keys for moving between categories don't work

### ISSUE THREAD

**Issue by mrboring** [FreshRSS/FreshRSS#6737]
### Describe the bug

After upgrading to `1.24.2` the shortcut keys for moving between categories (`Alt+j` and `Alt+k`) have stopped working.

### To Reproduce

1. Open FreshRSS
2. Make sure there are some Categories with unread articles
3. Click on the first Category, then do `Alt+j`
4. Nothing happens

### Expected behavior

I expected I would be moved to the next Category with unread articles.

### FreshRSS version

1.24.2

### Environment information

- Database version: Postgres don't know what version
- PHP version: 8.2.18
- Installation type: TrueNAS app
-Web server type: Whatever TrueNAS uses for apps
- Device: Windows 10 PC
- OS: Hosted on TrueNAS Dragonfish-24.04.2, Client Win10
- Browser: Firefox 129.0.2, LibreWolf 129.0.2-1, Brave 1.69.153, Edge 128.0.2739.42

### Additional context

If I revert back to `1.24.1` the problem goes away.

**Comment by Alkarex** [comment]
@math-GH Regression from https://github.com/FreshRSS/FreshRSS/pull/6446

**Comment by Alkarex** [comment]
@mrboring This has just been fixed https://github.com/FreshRSS/FreshRSS/pull/6741 in our `edge` branch. Could you give it a try?

**Comment by mrboring** [comment]
@Alkarex I could not test it on TrueNAS, but was able to test it on Windows 10 and was able to navigate categories using the shortcut keys. Problem fixed. Thanks.
