### ISSUE TITLE
[Bug] Search query not finding author with special character in name

### ISSUE THREAD

**Issue by raqua** [FreshRSS/FreshRSS#6749]
### Describe the bug

I filter XDA feed by authors and articles by author João Carrasqueira can not be filtered out, the result is empty. 
Other authors in that feed can be filtered. 

### To Reproduce

1. Set up feed https://www.xda-developers.com/feed/ in FreshRSS
2. Try to use query: author:'Sherri L. Smith'
3. See that some results are returned
4. Try to use query: author:'João Carrasqueira'
5. No results are returned, but there are articles from him in the feed. For example this one: https://www.xda-developers.com/projects-can-breathe-new-life-into-old-tablet/

### FreshRSS version

Has been there for couple of versions, 2 days old edge build still has it.

### Environment information

- Database version: SQLite
- PHP version: The one used in Docker container
- Installation type: Docker, edge image
-Web server type: What docker uses
- Device: Firefox on Linux
- OS: Arch Linux, Linux Mint
- Browser: Firefox 129.0.2

**Comment by math-GH** [comment]
Currently there is no author with special characters in this feed so I cannot confirm it as a bug

**Comment by raqua** [comment]
The author I mentioned definitely posted yesterday. Not sure about today. But he posts often.

**Comment by Frenzie** [comment]
> Currently there is no author with special characters in this feed so I cannot confirm it as a bug

There is, but it's the feed's bug:

```xml
<dc:creator><![CDATA[Joo Carrasqueira]]></dc:creator>
```

**Comment by Frenzie** [comment]
For example you'll see that this feed, which actually includes the character, shows and searches for João just fine.
https://journals.openedition.org/spp/backend?format=rssdocuments&type=review

**Comment by Frenzie** [comment]
@Alkarex Do we have a "not our bug" type label? The feed itself filtered out the characters before it ever reached the wider internet.

**Comment by raqua** [comment]
@Frenzie Understood, thanks for explaining! I guess this can be closed then.

**Comment by Alkarex** [comment]
> Do we have a "not our bug" type label?

Not so specific, be that role is mostly taken by https://github.com/FreshRSS/FreshRSS/labels/Feed%20problem%20%3Anewspaper_roll%3A

**Comment by Frenzie** [comment]
Right, though I feel that normally stands for something that could theoretically be worked around, even if we don't want to (e.g., working around Cloudflare would be without end, so why waste time in the first place). Ah well, the distinction probably isn't important enough for a separate label.
