### ISSUE TITLE
Proxy server support

### ISSUE THREAD

**Issue by alcoralcor** [FreshRSS/FreshRSS#675]
cUrl does not use OS env vars to detect if proxy is needed to query outside local network.
It would be very useful to add Proxy Preferences (proxy URL, optional user/password, HTTP/SOCKS, exclusions) and use cUrl options to set up WAN connexions filtered by a proxy. 

http://stackoverflow.com/questions/5211887/how-to-use-curl-via-a-proxy

**Comment by georgem1971** [comment]
I really look forward for this proxy preferences with or without password (can setup additional squid proxy to be transparent as workaround user/password request)

**Comment by Alkarex** [comment]
See also https://github.com/simplepie/simplepie/issues/19
https://github.com/simplepie/simplepie/pull/359
https://github.com/simplepie/simplepie/pull/360

**Comment by Alkarex** [comment]
https://github.com/simplepie/simplepie/pull/407

**Comment by Alkarex** [comment]
Will be implemented with https://github.com/FreshRSS/FreshRSS/issues/897

**Comment by Alkarex** [comment]
@alcoralcor and @georgem1971 : Proxy support will be merged in FreshRSS /dev very soon (https://github.com/FreshRSS/FreshRSS/pull/898 and https://github.com/FreshRSS/FreshRSS/pull/899) and in the upcoming beta 1.1.2.
It would be great if you could test this functionality. I will update this thread when it is merged in /dev, and in the meantime, it can be tested from my own /dev branch https://github.com/Alkarex/FreshRSS
To enable the use of a proxy, you can edit `data/config.php` and add something like (see model in `data/config.default.php`):

``` php
'curl_options' => array(
    //CURLOPT_PROXYTYPE => CURLPROXY_HTTP,
    //CURLOPT_PROXY => '127.0.0.1',
    //CURLOPT_PROXYPORT => 8080,
    //CURLOPT_PROXYAUTH => CURLAUTH_BASIC,
    //CURLOPT_PROXYUSERPWD => 'user:password',
),
```

**Comment by Alkarex** [comment]
Now merged in /dev

**Comment by georgem1971** [comment]
I come back with news as soon as I test the new functionality. Many thanks!

**Comment by georgem1971** [comment]
Port number inside quotes is necessary ?

**Comment by Alkarex** [comment]
@georgem1971 I have tested with success using a number without quotes for the port number. Please let us know if this does not work for you.

Here is the exact config I just have tested:

``` php
'curl_options' => array(
    CURLOPT_PROXYTYPE => CURLPROXY_HTTP,
    CURLOPT_PROXY => 'localhost',
    CURLOPT_PROXYPORT => 8080,
),
```

**Comment by alcoralcor** [comment]
Sorry for replying late but this work fine for me.
I use a squid proxy without auth.

Nice work !

**Comment by Alkarex** [comment]
Thanks for the feedback @alcoralcor

**Comment by petrk94** [comment]
@Alkarex 
I have a question. Is it possible to add the proxy settings as a menu in the settings on FreshRSS ?
How it would affect the function?
I have it installed on a VPS and a friend from china want to access it, due the photos which are in the RSS will be blocked because they are from news pages which are blocked. Is it possible to avoid this issue?
Thanks

**Comment by Alkarex** [comment]
@petrk94 For your case, it is not the same type of proxying than discussed in this issue. See https://github.com/FreshRSS/FreshRSS/issues/1215 instead and the suggested extension https://github.com/FreshRSS/Extensions/tree/master/xExtension-ImageProxy
