### ISSUE TITLE
[Bug] `inurl:` search term doesn't work with quotes

### ISSUE THREAD

**Issue by mtalexan** [FreshRSS/FreshRSS#6750]
### Describe the bug

The `inurl:'term'` format always produces no results.

### To Reproduce

1. Find a single word `term` with `inurl:term` that finds matches
2. Change it to `inurl:'term'`
3. Notice it now has no matches

### Expected behavior

`inurl:term` and `inurl:'term'` should find the same thing for a single word match and `inurl:'term'` should run the search with the `'` characters removed.

### FreshRSS version

1.24.2-dev  (current `:edge` docker image)

### Environment information

- Database version: Postgres 16.4
- PHP version: 8.3.10
- Installation type: Docker
- Web server type: Apache
- Device: Linux server
- OS: (irrelevant) OpenSuse MicroOS
- Browser: Firefox 129.0.1

### Additional context

A build of the latest `edge` exhibits the same behavior

**Comment by Alkarex** [comment]
Fixed in https://github.com/FreshRSS/FreshRSS/pull/6706
