### ISSUE TITLE
[Bug] API wrong path from configuration link

### ISSUE THREAD

**Issue by Draky50110** [FreshRSS/FreshRSS#6757]
### Describe the bug

Hello.

I tested FeedMe android app with Greader API config.

It returns "auth failed" message.

In web, FreshRSS I click on API link to test and got error 500.

Strange thing : double "path dir" : 
Your API address:
    https://subdomaine.domain.com/frss/p/api/api/greader.php
Google Reader API configuration test:
    ❌ FAIL: HTTP error 500 

But API is on /p/api not on /p/api/api

Do you think wrong path problem is linked to auth failed on FeedMe ?

### To Reproduce

Try to use FeedMe entering link given on profile page.

Try to click on link given.

### FreshRSS version

1.24.2

### Environment information

MySQL

**Comment by math-GH** [comment]
Is the API enabled (Administration -> Authentication)?
![grafik](https://github.com/user-attachments/assets/2b83be0a-5320-4ab4-a888-0252b3f22797)

more information: https://freshrss.github.io/FreshRSS/en/users/06_Mobile_access.html

**Comment by math-GH** [comment]
And please give more information about your environment.

The default environment information that are very useful:
```
- Database version: [e.g. Mysql 5.7, SQLite]
- PHP version: [e.g. PHP 8.1]
- Installation type: [e.g. Docker, Docker image source, git, Yunohost] <=== needed to help you
-Web server type: [e.g. Apache, nginx] <=== needed to help you
- Device: [e.g. iPhone13]
- OS: [e.g. Ubuntu 22.04, Win10, MacOS14]
- Browser: [e.g. Firefox 124]
```

**Comment by Draky50110** [comment]
Yes, API is enabled.

Tested on Firefox (last) and FeedMe app.

MariaDB = 10.11
PHP : 8.1

**Comment by Alkarex** [comment]
What FreshRSS installation type do you have?
Please check `base_url` in your `./data/config.php`

**Comment by Draky50110** [comment]
Base URL is set to :
  'base_url' => '',

EDIT : changed to 'https://subdomain.xxx.com/frss/p' and all is ok now, thanks.

**Comment by Alkarex** [comment]
The root cause might be that you are not supposed to have the `/p/` in your public URL
