### ISSUE TITLE
[Bug] quoted tag search terms don't work

### ISSUE THREAD

**Issue by mtalexan** [FreshRSS/FreshRSS#6761]
### Describe the bug

Using quotes on a search term for a tag doesn't work.

### To Reproduce

1. Find a feed and term that can be searched for with a filter like `#term1`
2. Change the filter to `#'term1'`
3. Notice nothing is matched anymore

### Expected behavior

Searching for `#term1` or `#'term1'` (or `#"term1"`) should all work the same, except quoting allows the term to contain spaces.

### FreshRSS version

1.24.2-dev  (current `:edge` docker image)

### Environment information

- Database version: SQLite
- PHP version: 8.3.10
- Installation type: Docker
- Web server type: Apache
- Device: Linux server
- OS: (irrelevant) OpenSuse MicroOS
- Browser: Firefox 129.0.1

### Additional context

This is an identical bug to https://github.com/FreshRSS/FreshRSS/issues/6750, except for the tag search/filter (`#`) rather than the URL search/filter (`inurl`).

**Comment by Alkarex** [comment]
Should be fixed with https://github.com/Alkarex/FreshRSS/commit/7125782af8032263601d3fa6d6d74055172841ba in https://github.com/FreshRSS/FreshRSS/pull/6706 (not tested)
