### ISSUE TITLE
[Bug] Incorrect character encoding in description field (but not title)

### ISSUE THREAD

**Issue by markturner** [FreshRSS/FreshRSS#6763]
### Describe the bug

This issue is affecting all feeds that I add, and affects readability quite badly in some cases.

See the issue in the following screenshot:
<img width="602" alt="Screenshot 2024-09-02 at 15 42 52" src="https://github.com/user-attachments/assets/65c839d1-5c88-4c66-8937-4e9d6995f1f3">

The source rss feed does not have this problem (at least, as shown in the browser):
<img width="1443" alt="Screenshot 2024-09-02 at 15 42 38" src="https://github.com/user-attachments/assets/4c889803-d932-4eb5-a4b5-391c34fc2d2a">

The "installation check" page shows "You have the required library for character type checking (ctype)." and no other warnings or anything (all green).

Thanks in advance for your help!

### To Reproduce

Adding any feed displays this issue.

### Expected behavior

Special characters displayed correctly in the description.

### FreshRSS version

1.24.2

### Environment information

- Database version: SQLite (I assume)
- PHP version: 8.3.10
- Installation type: Docker
- Web server type: nginx
- Device: browser
- OS: Mac OS 14.5
- Browser: Brave 1.68.128 Chromium: 127.0.6533.73 (Official Build) (x86_64) - but any browser is affected

**Comment by Alkarex** [comment]
Can you please provide the URL of the feed?

**Comment by markturner** [comment]
Not that one specifically as it's locally generated, but it affects all feeds, so here is a public one you can see: https://daringfireball.net/feeds/main

The most recent entry (dated September 3) includes this excerpt:
<img width="1413" alt="Screenshot 2024-09-03 at 09 56 19" src="https://github.com/user-attachments/assets/5b9ea590-90f9-40ba-a8dd-75ebddb371a0">
<img width="568" alt="Screenshot 2024-09-03 at 09 55 58" src="https://github.com/user-attachments/assets/d940e789-e00e-45df-bc17-6ff5a1b2b9c2">

**Comment by Alkarex** [comment]
Works fine for me:

![image](https://github.com/user-attachments/assets/9213f6c8-5134-4825-ba6d-b822a854f60d)

* Do you have any FreshRSS extension?
* Have you added any rule to fetch full content for that feed?

**Comment by markturner** [comment]
I'm using a couple of extensions but I don't think they would have this effect. I have tried turning them off and I'm pretty sure this behaviour started before I installed any of them.

I don't have any full content behaviour for that feed, or several others that show the same issue (as I said, all feeds have the issue).

I presume it's something peculiar to my setup, but I am at a loss, there seems to be no way to change character encoding options and this only affects FreshRSS, not any of my other docker containers.

**Comment by Alkarex** [comment]
What Docker image are you using, more precisely?
You write you have an nginx in front. Could you try to bypass it?

**Comment by markturner** [comment]
I don't have nginx in front, I just inferred that the container was using nginx by looking in the config files. I could have that wrong though!

I'm using the latest version of the linuxserver/freshrss image.

**Comment by Alkarex** [comment]
If you are able to run another instance, give a try to one of our official images such as [`freshrss/freshrss`](https://hub.docker.com/r/freshrss/freshrss/)
I cannot think of why the LinuxServer image should behave differently regarding encoding, though...

**Comment by markturner** [comment]
Well I have spun up a new instance of it as you suggest and I _don't_ see the same issue on that one, so I'm not sure what has gone wrong with the first one but this at least gives me an avenue to explore, thanks for your help 👍

**Comment by Alkarex** [comment]
Closing, but feel free to report your findings

**Comment by markturner** [comment]
I set up a new instance and abandoned the old one, this issue has not recurred 👍
