### ISSUE TITLE
[Support] 404 after updating to 1.24.2 on shared hosting

### ISSUE THREAD

**Issue by mrlars** [FreshRSS/FreshRSS#6764]
### Describe the bug

Hi, after many years of successful usage, yesterday I had my very first issue with FreshRSS. 

I updated with the internal tool and the result is now a 404 message.
It was not the first update done in this way, in this infrastructure.

### To Reproduce

1. go to update
2. click the update button

### Expected behavior

To access the updated software

### FreshRSS version

1.24.1 > 1.24.2

### Environment information

- Database version: 10.6.18 MariaDB
- PHP version: PHP 8.3.9
- Installation type: Softaculous 
- Web server type: LiteSpeed
- Device: [e.g. iPhone13]
- OS: [e.g. Ubuntu 22.04, Win10, MacOS14]
- Browser: [e.g. Firefox /Safari]

### Additional context

In the user log, I don’t find anything at all... what else can I provide?

**Comment by Alkarex** [comment]
I am not familiar with Softaculous, but the issue might be there. 
A 404 indicates that some files may be missing

**Comment by mrlars** [comment]
> I am not familiar with Softaculous, but the issue might be there. 
nothing more than a "normal" shared hosting install

> A 404 indicates that some files may be missing
I’m going to check for the presence of all the files

**Comment by Alkarex** [comment]
> nothing more than a "normal" shared hosting install

What FreshRSS install method do you use, then? (git, Docker, ZIP...)

**Comment by mrlars** [comment]
> > nothing more than a "normal" shared hosting install
> 
> What FreshRSS install method do you use, then? (git, Docker, ZIP...)

zip

Indeed, during the update process, some files were not copied correctly. 
Is there a way to copy the files from the zip again while retaining only what is necessary for the instance to function as it is currently configured? (data folder, config.php ecc)

**Comment by Frenzie** [comment]
Make a backup just in case and simply overwrite it?

**Comment by Alkarex** [comment]
As @Frenzie said. Otherwise if `git` is available to you, it is a more robust method to install and update, change branch, etc.

**Comment by Alkarex** [comment]
Here is a way to update from ZIP to git method, on the latest branch:

```sh
cd FreshRSS/
git init
git remote add origin https://github.com/FreshRSS/FreshRSS.git
git fetch
git checkout -f -b latest origin/latest
```

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/discussions/6769

**Comment by mrlars** [comment]
I cannot use git in this environment

> Make a backup just in case and simply overwrite it?

it was the idea, this is why I asked what i have to preserve of the backup

**Comment by Frenzie** [comment]
Just the config.php and data is fine, maybe extensions, but it's not like it's large enough to worry about saving a few bytes imo.

**Comment by mrlars** [comment]
> Just the config.php and data is fine, maybe extensions, but it's not like it's large enough to worry about saving a few bytes imo.

Many thanks! it's working again

**Comment by mrlars** [comment]
Sorry, last question (I hope): in the update area I find that the version is the last (correct: 1.24.2) but the system is telling me that have to update.
I guess that the interrupted update process left some rubbish... where can i search? in /data/last_update.txt I just find "1.24.2". Thank you again!

**Comment by Alkarex** [comment]
1.24.3 should be available to you in the coming days https://github.com/FreshRSS/update.freshrss.org/pull/17 so try that
