### ISSUE TITLE
[Bug] Retrieve content from a specific website 

### ISSUE THREAD

**Issue by RonnyB74** [FreshRSS/FreshRSS#6773]
### Describe the bug

For some time now, no article content has been retrieved from the website [TV-Spielfilm](https://www.tvspielfilm.de/tv-programm/rss/tipps.xml), error message `The selector didn’t match anything. As a fallback the original feed text will be displayed instead.`. I also get the same error message in the [Demo](https://demo.freshrss.org/i).

### To Reproduce

Feed URL: https://www.tvspielfilm.de/tv-programm/rss/tipps.xml
Type: RSS/Atom
Advanced:
Article CSS Selector: .broadcast-detail

### Expected behavior

content from main page should be replace the feed content.

### FreshRSS version

1.24.3-dev

### Environment information

- PHP version: 7.4.33
- Installation type: git
- Web server type: Apache
- OS: Debian Linux
- Browser: Vivaldi

**Comment by Alkarex** [comment]
Would you be able to test https://github.com/FreshRSS/FreshRSS/pull/6774 ?

**Comment by Alkarex** [comment]
Merged in the `edge` branch. Tests welcome

**Comment by RonnyB74** [comment]
Seems to work well, thank you!

**Comment by Alkarex** [comment]
Excellent, please keep an eye on the other feeds for which you use full content retrieval, to make sure this has not caused regressions
