### ISSUE TITLE
[Bug] Filters not working correctly when one of the words is an URL

### ISSUE THREAD

**Issue by iPaulis** [FreshRSS/FreshRSS#6775]
### Describe the bug

Example article URL that contains the text that should be filtered: https://www.genbeta.com/actualidad/jornada-laboral-cuatro-dias-fracasa-japon-pais-necesita-mejorar-productividad-reduciendo-horas-trabajo

The target text is in the body, so we use free-text filter, and the aim is to filter by: 'Vía | Xataka'
The problem seems to be that in the body, part of the keywords are text, but another part is actually an URL, like this: Vía | [Xataka](https://www.xataka.com/empresas-y-economia/japon-necesitaba-acabar-su-modelo-trabajo-excesivo-esperanza-era-jornada-laboral-cuatro-dias-esta-fracasando)

`<p>Vía | <a href="https://www.xataka.com/empresas-y-economia/japon-necesitaba-acabar-su-modelo-trabajo-excesivo-esperanza-era-jornada-laboral-cuatro-dias-esta-fracasando">Xataka</a></p>`

So the filter does not give any results.

I noticed that if I search for an URL in free-text mode, it does find matches inside the article body, even if the URL is not explicitly shown as text in the body, it does search hyperlinks in the body, such as 'https://www.xataka.com'.
So I tried filtering by 'Vía | https://www.xataka.com' but it also does not work.
It also finds the keywords that contain an hyperlink correctly, but if you add any previous preceding or succeeding keyword to the search, it gives no results.

I hope you can reproduce the issue with this feed or any other feed in this circumstances.
Thank you in advance for your help.

### To Reproduce

1. Add a test feed article like the one provided, or one with 
2. Go to 'Search bar'
3. Search for 'Vía | Xataka'
4. See error, it does not filter the mentioned article that contains that text.

### Expected behavior

I expected the article to get filtered.

### FreshRSS version

1.24.2

### Environment information

- Browser: [Firefox 129]

**Comment by Alkarex** [comment]
Quick feedback already: The search is performed as free text, not with an HTML text extraction.
However, there is a work-in-progress to support regex https://github.com/FreshRSS/FreshRSS/pull/6706, which might help

**Comment by iPaulis** [comment]
Thanks for the quick reply.
However, the issue here seems to be that the filter finds the keywords that contain an hyperlink correctly, but if you add any preceding or succeeding keyword that is not part of the hyperlink to the search, it gives no results.

So, for a very specific example with only a unique result, in this article: https://www.xatakamovil.com/huawei/plegable-triple-huawei-tiene-fecha-presentacion-esto-que-sabemos-movil-que-quiere-quitarle-protagonismo-al-iphone

There is this sentence:
Ahora busca [quitarle protagonismo a los iPhone 16](https://www.xatakamovil.com/huawei/plegable-triple-huawei-tiene-fecha-presentacion-esto-que-sabemos-movil-que-quiere-quitarle-protagonismo-al-iphone) de Apple, pero no hace falta esperar más para verlo en acción.

This filter works: 'protagonismo a los iPhone'
This filter works: 'quitarle protagonismo a los iPhone 16'
This filter does not work: 'busca quitarle protagonismo a los iPhone 16'
This filter does not work: 'quitarle protagonismo a los iPhone 16 de'

So filters that find a match in an hyperlink work, but filters that are part regular text and part hyperlink text don't work.
English is not my first language, sorry if I'm not explaining myself clearly.

**Comment by Alkarex** [comment]
I understand the problem. During the search, HTML code is seen as text, so you cannot search for `Vía | Xataka` and will instead have to search for something like `/Vía \| .*?>Xataka/` using the new regex search engine (I still have to fix some encodings to allow searching for `>`)
What database are you using?

**Comment by iPaulis** [comment]
I don't know, I was testing one of the free cloud instances when I found the issue: https://freshrss.prodottoinrete.com
Is there a way to bypass the limitation with the current search engine (non regex)? or should I wait for a fix in the current or future engine?

Some more context; I also tried filters like 'Vía | <a href', but also didn't work.

The weirdest part for me is how this gets results from the article body 'Vía | ', and this other search also gets matches from the article body 'https://www.xataka.com/', and they even work with AND logic 'Vía | ' AND 'https://www.xataka.com/', but combine them together to exactly match the text I'd like to target 'Vía | https://www.xataka.com/', and it fails.

**Comment by Alkarex** [comment]
There is no `AND`, which is implicit, so what you can try now is for instance `"Vía | " "xataka.com"`

I have just fixed https://github.com/FreshRSS/FreshRSS/pull/6706 which is ready for testing searching within HTML code such as `/Hello <span>world<\/span>/`

To test now, you need to deploy your own instance.

**Comment by mtalexan** [comment]
@iPaulis I brought up this identical issue as well.  You're not actually performing the search on what you see, instead you're performing a search on the literal HTML code.  So the body you're trying to match contains the literal `<p>Vía | <a href="https://www.xataka.com/empresas-y-economia/japon-necesitaba-acabar-su-modelo-trabajo-excesivo-esperanza-era-jornada-laboral-cuatro-dias-esta-fracasando">Xataka</a></p>` rather than what you see that looks like `Via | Xataka`.  

When you do a search like `'Via | Xataka'` it won't match because that doesn't appear in the HTML code it's looking at.  It instead has all kinds of extra HTMl code around the `Xataka` part.  As Alkarex said, you would have to look for each string separately like `'Via |' 'Xataka'` which matches if both the string `Via |` and `Xataka` each separately appear in the HTML code.

This isn't ergonomic at all, but doing anything to change it is a massive undertaking that would involve changing the database schema and running a partial HTML rendering of every article when it's first received.  Probably not feasible any time soon from what I'm told.

Another work around, is Alkarex's in-progess work that is adding Regex support.  That would let you do something like `/Via | .*Xataka/` that would allow anything to appear immediately before the word `Xataka` in the HTML code.

**Comment by iPaulis** [comment]
I know AND is implicit, so the results doing 'Vía | ' AND 'https://www.xataka.com/' or 'Vía | ' 'https://www.xataka.com/' are the same, they work, but it is not the filter I need. I don't have my hardware/system ready to deploy yet, that's why I was testing in another instance. It would be probably faster if someone testing the new branch could try to reproduce this issue and see if it is fixed.

Thanks for the explanation @mtalexan. I tried searching a match in HTML too, but the search engine does not seem to work that way. 
I can't get the results I want from searching the terms separately as there are way too many false positives. The only correct way is to filter both parts together; the terms need to be followed by one another, not anywhere separately in the article.

It is good to know there will be future filtering improvements, it seems this is the right tool for me. Thank you.

**Comment by Alkarex** [comment]
No, the results are not necessarily the same: when you add `' AND '`, it will search for the `' AND '` string.

How did you test the regex search? (from which branch?) I have just merged https://github.com/FreshRSS/FreshRSS/pull/6706 in the `edge` branch a few minutes ago.

**Comment by iPaulis** [comment]
I didn't test anything new, I'm not ready to deploy freshrss. 
I was just trying to understand how filters work in the current build in that cloud instance.

**Comment by iPaulis** [comment]
I just came back to say this was fixed with the new regex filter engine, thanks.
