### ISSUE TITLE
[Feature] Setting Request Headers like Authorization Headers

### ISSUE THREAD

**Issue by atsai1220** [FreshRSS/FreshRSS#6784]
**Is your feature request related to a problem? Please describe.**
I'm looking to subscribe to GitHub repositories as feeds. I am required to set the following headers
- `X-GitHub-Api-Version: 2022-11-28`
- `Accept: application/atom+xml`
- `Authorization: Bearer <TOKEN>`

However, I do not see the ability to set headers when adding a feed. Any help would be appreciated.
<img width="1189" alt="image" src="https://github.com/user-attachments/assets/291e1c39-36a4-4349-89cb-a335600a3a6e">

**Describe the solution you’d like**
I would love to have built-in fields to add headers when making GET requests to feeds.

**Describe alternatives you’ve considered**
I've considered deploying a proxy in between to add those headers but it would be great if it is part of the FreshRSS application.

**Comment by Alkarex** [comment]
Yes, we should add more options to customise the HTTP request. Help welcome.
Is it for private GitHub repositories?

**Comment by ev-gor** [comment]
@Alkarex  Should it be an input field where a user can enter any arbitrary header or a set of predefined headers or some sort of combination: list of standart headers plus a field for custom ones?

**Comment by Alkarex** [comment]
I think a basic textarea for arbitrary headers would be fine.

```
X-GitHub-Api-Version: 2022-11-28
Accept: application/atom+xml
Authorization: Bearer <TOKEN>
```

**Comment by atsai1220** [comment]
> Is it for private GitHub repositories?

That's right! E-mails are great but RSS/Atom feeds are great as well. But I thought to expand to any `headers` as a general function.

**Comment by Alkarex** [comment]
@ev-gor Would you feel like trying to send a PR?

**Comment by ev-gor** [comment]
@Alkarex I will
