### ISSUE TITLE
[Bug] Mark as read not working on tag generated from scraped content

### ISSUE THREAD

**Issue by prank-arum** [FreshRSS/FreshRSS#6788]
### Describe the bug

I am scraping the site https://magdalene.substack.com/archive. Although it does have a feed, there is no way to differentiate between paid and free content so I have included the following:
xpath for finding news items: //div[@class='portable-archive-list']/div/div/div/div
xpath for item tags: concat("#paid_is_", boolean(descendant::svg[contains(@class, 'lucide lucide-lock ')]))
This assigns #paid_is_true to articles that are paid, and #paid_is_false to articles that are free. It works as expected.

If I search on #paid_is_true, or use it as a user query, the paid articles are found correctly. However, if I put the same tag in Mark as Read, all of the articles come through. Is there some way to generate a tag via scraping and have it searched on when loading articles? 

### To Reproduce

Input feed as described. 

![Screenshot 2024-09-08 at 8 00 35 AM](https://github.com/user-attachments/assets/ce9eab7e-38b8-4d65-9878-10912128f956)
![Screenshot 2024-09-08 at 8 01 31 AM](https://github.com/user-attachments/assets/695d87bd-d036-4656-a418-88ac148d2aca)
![Screenshot 2024-09-08 at 8 02 07 AM](https://github.com/user-attachments/assets/ce353356-9478-4ae1-8fe0-b911d4dc3063)
![Screenshot 2024-09-08 at 8 02 39 AM](https://github.com/user-attachments/assets/902dcd24-125e-45c8-a837-3db04d29cb94)

### Expected behavior

Paid articles should be marked as read but they are not. Additionally, I have tired negating the #paid_is_false tag. This marks all as read, which seems to suggest that FreshRSS does not see these tags.

### FreshRSS version

1.24.3

### Environment information

- Database version: [e.g. Mysql 5.7, SQLite]
- PHP version: [e.g. PHP 8.1]
- Installation type: [e.g. Docker, Docker image source, git, Yunohost]
-Web server type: [e.g. Apache, nginx]
- Device: [e.g. iPhone13]
- OS: [e.g. Ubuntu 22.04, Win10, MacOS14]
- Browser: [e.g. Firefox 124]

**Comment by Alkarex** [comment]
If possible, please provide an XML copy of your feed's settings, by clicking on the corresponding button (see below) so I do not have to type them by hand:
![image](https://github.com/user-attachments/assets/a3fa342b-d2ed-4f12-bb4d-3fc5c5065b74)

Edit: Not needed anymore

**Comment by Alkarex** [comment]
Please try this patch https://github.com/FreshRSS/FreshRSS/pull/6790

**Comment by prank-arum** [comment]
Thanks for the quick response. With that patch I get the following error:

Fatal error: Uncaught Error: Call to undefined method FreshRSS_Search::getAuthorRegex() in /home/MYUSERNAME/public_html/freshrss/app/Models/Entry.php:634 Stack trace: #0 /home/MYUSERNAME/public_html/freshrss/app/Models/FilterActionsTrait.php(128): FreshRSS_Entry->matches() #1 /home/MYUSERNAME/public_html/freshrss/app/Models/Entry.php(786): FreshRSS_UserConfiguration->applyFilterActions() #2 /home/MYUSERNAME/public_html/freshrss/app/Controllers/feedController.php(613): FreshRSS_Entry->applyFilterActions() #3 /home/MYUSERNAME/public_html/freshrss/app/Controllers/feedController.php(855): FreshRSS_feed_Controller::actualizeFeeds() #4 /home/MYUSERNAME/public_html/freshrss/lib/Minz/Dispatcher.php(120): FreshRSS_feed_Controller->actualizeAction() #5 /home/MYUSERNAME/public_html/freshrss/lib/Minz/Dispatcher.php(51): Minz_Dispatcher->launchAction() #6 /home/MYUSERNAME/public_html/freshrss/lib/Minz/FrontController.php(61): Minz_Dispatcher->run() #7 /home/MYUSERNAME/public_html/freshrss/p/i/index.php(59): Minz_FrontController->run() #8 {main} thrown in /home/MYUSERNAME/public_html/freshrss/app/Models/Entry.php on line 634

**Comment by Alkarex** [comment]
Ah, it looks like you have not fully checked out the branch, but maybe only manually changed a single file? 
That does not work because there has been other changes in our rolling release `edge` since the version you seem to be using

**Comment by Alkarex** [comment]
I have merged the fix in our rolling release `edge` to make it easier to test. Feedback welcome

**Comment by prank-arum** [comment]
This works perfectly. Many thanks, I can’t believe how quickly you got that done!On Sep 9, 2024, at 4:38 AM, Alexandre Alapetite ***@***.***> wrote:﻿
I have merged the fix in our rolling release edge to make it easier to test. Feedback welcome

**Comment by Alkarex** [comment]
Thanks for the feedback :-)
