### ISSUE TITLE
[Bug]  slow hdd causes timeout in update and causes a update loop

### ISSUE THREAD

**Issue by rezad1393** [FreshRSS/FreshRSS#6789]
### Describe the bug

slow hdd causes timeout in update and causes a update loop

### To Reproduce

when I use update after a while webpage says timeout and I have to back.
and it says I am on newest version but still there is an update with the same version.

I have a slow hdd  or at least copying data to data.back takes a long time because of 240MB cache folder. so in the update process I see that in data.back the cache folder gets slowly filled up but before almost being complete the timeout occurs.

I moved the cache file out of data folder and then try update process and it fixes the issue and update occurs correctly.

so maybe (for at least copying the data to data.back ) process part of update, the timeout be increased or the data to data.back be separated and internally done and not depend on web php process so that it doesn't timeout.

### Expected behavior

not timeout

### FreshRSS version

any version

### Environment information

    Database version: [s SQLite] sqlite 3.46.1
    PHP version: [e.g. PHP 8.1] php 8.3.11
    Installation type: [e.g. Docker, Docker image source, git, Yunohost] zip release and updates
    -Web server type: [e.g. Apache, nginx] nginx
    Device: [e.g. iPhone13] laptop
    OS: [e.g. Ubuntu 22.04, Win10, MacOS14] archlinux
    Browser: [e.g. Firefox 124] firefox 124

**Comment by Alkarex** [comment]
Please consider using another install/update method, such as git.
Here is a short guide on how to migrate https://github.com/FreshRSS/FreshRSS/discussions/6769
The ZIP install/update method is really the last resort when there is nothing else better available

**Comment by rezad1393** [comment]
> Please consider using another install/update method, such as git. Here is a short guide on how to migrate #6769 The ZIP install/update method is really the last resort when there is nothing else better available

zip?
I use the update process used by the web app itself, you know from here
https://host/i/?c=update

**Comment by Alkarex** [comment]
Yes, but your first install was probably by ZIP. Updates done through the Web interface depend on how the system was installed.

**Comment by rezad1393** [comment]
> Yes, but your first install was probably by ZIP. Updates done through the Web interface depend on how the system was installed.

thanks for quick answers.

but I need some more info:

1-can I change it now (the web one) to git without re-installation?

2- does this app separate all change files (or added files) a data folder?
I mean can user just backup data folder and then remove freshrss folder and (this is important) without using the installation process just copy zip or git folder and then copy data folder back and it would be like user has the old installation back?
my gut tell me yes cause I don't think this app writes data anywhere else but I want to be sure.

2- I have basic knowledge about git and I know it tracks file changes in its database (in .git folder) so does that mean that my personal data (data folder) is also tracked? so when I update from web-app does git track that too and that is why you recommend it? because it makes going back (for even suer data) easy?

**Comment by Alkarex** [comment]
1. Yes
2. The git update does not touch the data folder
3. No, the tracking is only on the software files, not your own files

**Comment by rezad1393** [comment]
so it just uses git ignore (if I remember correctly) for data folder?

my second question was two fold.
first does git track data folder which you say it doesn't.
the second question was, after using git or zip and unziping does all the other changes after that are written to data forlder?
so that all the other folders are the original ones? I mean is any preferences saved to any other places other than data folder?


in git case after clicking apply update, the back up of data folder to data.back still happens right?
then my bug still happens because the webapp will still timeout.


btw where I can check if the update has switched to git?
also how the system knows what to use?
just the  .git folder with its content make updater use git?

**Comment by Alkarex** [comment]
1. There is already a `.gitignore`
2.
    a. No
    b. the git update is applied to the local software files and does not touch your existing data files
   c. No other preferences affected
3. No `data.back`, which is an artefact due to the limitations of the ZIP update. As mentioned already, your existing data files are not touched...

Just make a backup and try by yourself to see the details

**Comment by rezad1393** [comment]
thank you for other answers.

> Just make a backup and try by yourself to see the details

I already have done the git commnads you put in the link.

1-I want to know how the app knows which method to use.
my guess is that the update process check to see if the folder is a git folder? I mean there is no preferences set to switch to git (As you said all the setting are in data folder) so the updater would itself check every time to see if it is git or not (zip then)?

2-
the bug that I created this post for can still happen because the git update may be slow.
though that may be rare cause if it is too slow the git it self would timeout.

**Comment by Alkarex** [comment]
Yes, git is auto detected
