### ISSUE TITLE
Possibilité de création de compte

### ISSUE THREAD

**Issue by ldidry** [FreshRSS/FreshRSS#679]
À moins que je ne me trompe, il faut obligatoirement que l'admin crée le compte des nouveaux utilisateurs. Serait-il possible d'avoir une option permettant des inscriptions ouvertes ? 

Comment je vois les choses :
- [x] une option d'admin pour permettre la création de compte depuis la page de login
- [x] toujours dans l'admin, un champ number pour déterminer le nombre max de comptes possibles. Au-delà, la création de comptes est bloquée
- [x] un bouton "suppression de mon compte" dans l'interface de configuration de chaque utilisateur. Ce bouton activerait une popup de confirmation. Il y aurait une vérification pour que le dernier admin (il faut qu'il y en ait au moins un :stuck_out_tongue: ) ne puisse pas supprimer son compte.

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/issues/833

**Comment by marienfressinaud** [comment]
J'ai commencé dans une branche dédiée : https://github.com/marienfressinaud/FreshRSS/tree/679-create-accounts

Je ne passerai pas par une extension par contre...

**Comment by Alkarex** [comment]
:+1:

**Comment by marienfressinaud** [comment]
L'état d'avancement de ma branche permet de réaliser les trois points listés. Ce qu'il me reste à faire : 
- [x] Les traductions !
- [x] Demander le mot de passe utilisateur lorsqu'il souhaite supprimer son propre compte.
- [ ] Améliorer le code pour le rendre plus modulaire (@todo !). Cela fera l'objet d'un autre ticket.
- [ ] Répondre aux demandes supplémentaires s'il y a :)

**Comment by marienfressinaud** [comment]
J'ai créé ma PR, je ne pensais pas que je coderai tout d'un coup mais c'est complet vis-à-vis de la demande :).

@ldidry n'hésite pas à tester et faire des retours si jamais. Si tu veux juste tester sans installer FRSS je peux te faire une instance de test.

**Comment by Alkarex** [comment]
@marienfressinaud Est-ce que tu penses que ça peut relativement vite être assez mur, et du coup viser la [1.1.2-beta](https://github.com/FreshRSS/FreshRSS/milestones/1.1.2) ou pas ? Si oui, je pense qu'il faut l'intégrer dans /dev pour avoir une chance d'avoir des retours. Si non, je suggère d'attendre juste après la sortie de la 1.1.2-beta pour le passer dans /dev.
Alternativement, on peut fusionner la /dev actuelle dans /beta tout de suite et attendre d'avoir les derniers patchs pour sortir (c.a.d. tag git) la 1.1.2-beta.

**Comment by marienfressinaud** [comment]
Je pense que oui. Mon plus gros soucis serait de potentielles créations de comptes fantômes par des robots mais à part ça je ne vois pas. De toutes façons la limite des comptes a été placée à 1 par défaut (qui correspond au compte admin) et je ne pense pas m'être planté dans la fonction qui teste si on a atteint la limite des comptes.

Il y aura par contre du refactoring à faire. Par exemple il serait temps de réfléchir à un objet `User` qui gèrerait le gros de l'initialisation d'un utilisateur, son nettoyage lorsqu'il est supprimé et le déplacement de la fonction `listUsers` (et son optimisation pour éviter de relister à chaque appel). J'ai essayé de mettre quelques TODO là où j'en voyais le besoin mais je ne voulais pas m'en occuper dans cette PR.

Donc OK pour la 1.1.2-beta (qu'il va falloir annoncer / sortir dans pas trop longtemps d'ailleurs).

**Comment by marienfressinaud** [comment]
J'ai oublié le CHANGELOG évidemment, il faut garder ce ticket ouvert le temps que je m'en occupe.
