### ISSUE TITLE
[Bug] Auth with unsecure URL applies htmlspecialchars() escape before username/password comparison

### ISSUE THREAD

**Issue by Draky50110** [FreshRSS/FreshRSS#6796]
### Describe the bug

Hello.

I tried the "unsecure" method to login : https://subdomain.domain.fr/frss/p/i/?c=auth&a=login&u=USER&p=PASSWORD

It works perfectly if password is without special char inside like "Toto1234" but changing it to "Toto&1234" will not work anywork and gives a "invalid ID" error message.

How could I use this method with a more secure password ?

Thanks

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

### Expected behavior

Use a password with special char inside.
Tested with "&".

### FreshRSS version

1.24.3

### Environment information

PHP 8.2
MariaDB 10.11
Apache 2.4.59

**Comment by Frenzie** [comment]
In that context you'd have to encode it as `%26`, because `&` is a special character in the URL for query parameters. You can run `encodeURIComponent()` in your browser to do it for you.

**Comment by Draky50110** [comment]
No, it does not work.
I tried this : https://xxx.com/frss/p/i/?c=auth&a=login&u=user.test&p=MyPassWord%26 and it gives me an invalid ID message.

Log shows : Unsafe password mismatch for user user.test

**Comment by Frenzie** [comment]
It seems to have been turned into `&amp;`. Somewhere a `htmlspecialchars_utf8()` must be applied that shouldn't be.

**Comment by Frenzie** [comment]
As a workaround, it should suffice to avoid `&`, `"`, `'`, `<`, and `>`. Anything else should be left alone.

Pinging @Alkarex in case he knows where to fix this without investigating in depth.

**Comment by Frenzie** [comment]
> Anything else should be left alone.

But other characters relevant to URLs like `#` will of course still have to be encoded as `%23`, or they won't reach the server at all.

**Comment by Draky50110** [comment]
Ok, thanks for all.

Will change password AND wait for a fix ;)

**Comment by Alkarex** [comment]
Please try https://github.com/FreshRSS/FreshRSS/pull/6797

**Comment by Draky50110** [comment]
Sorry, still not working.

**Comment by Alkarex** [comment]
Tested to work with password `a<&>"Z'` which gives
`https://freshrss.example.net/?c=auth&a=login&u=alice&p=a%3C%26%3E%22Z%27%0A`
