### ISSUE TITLE
Issue with freshrss data

### ISSUE THREAD

**Issue by rmvpress** [FreshRSS/FreshRSS#6798]
Hello.  I'm hoping for help with my issue regarding my data.  I went to update freshrss via the Linux server guide and it seems I messed up the update.  Luckily I can still see that my data is in /var/lib/docker/volumes/freshrss_data/_data, but when I tried linking this folder to the new freshrss install it seems it isn't loading that data or what have you. I'm hoping there's a way to link the old data to the new install since there's some feeds that I don't remember the addresses of.  If there's a way to simply access the feed URLs so I can manually add them that would work too. My user account is still in the old users directory along with everything else in that _data folder if that helps. Thank you.

**Comment by Alkarex** [comment]
Hello,
I am not sure what you mean with Linux server guide when using Docker, but show the output of `docker volume ls` and `docker ps -a` and your docker-compose or equivalent docker run
