### ISSUE TITLE
Limitation du nombre de flux par utilisateur

### ISSUE THREAD

**Issue by ldidry** [FreshRSS/FreshRSS#680]
Il serait utile de pouvoir définir un nombre max de flux par utilisateur, surtout s'il y a beaucoup d'utilisateurs :smile: 

= 0 => open bar

!= 0 => limité à x flux par utilisateur

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/issues/833

**Comment by Alkarex** [comment]
The work for the UI continues in https://github.com/FreshRSS/FreshRSS/issues/892 and for the install process in https://github.com/FreshRSS/FreshRSS/issues/890
