### ISSUE TITLE
[Bug] actualize not reliable anymore after update to 1.25.0-dev 

### ISSUE THREAD

**Issue by Arnoud-B** [FreshRSS/FreshRSS#6802]
### Describe the bug

After updating from 1.23 to 1.25.0-dev a few days ago, the actualize script is not working reliably anymore. It only seems to update 1 feed. A manual update in the web interface works fine.

I've tested with these cron jobs, both showing no error when ran manually (and FreshRSS.log remains empty):
`*/15 * * * * /opt/alt/php74/usr/bin/php /home/me/public_html/domain/freshrss/app/actualize_script.php > /home/me/var/FreshRSS.log 2>&1`
`*/15 * * * * /bin/curl https://example.org/freshrss/p/i/?c=feed&a=actualize&force=1&token=******* > /home/me/var/FreshRSS.log 2>&1`

Also the logs in the web app show nothing related.

Let me know if I can supply any further information that would help pinpoint the issue.

### To Reproduce

See description.

### Expected behavior

All feeds updating when the cron job runs.

### FreshRSS version

1.25.0-dev

### Environment information

- Database version: 10.6.18-MariaDB-cll-lve
- PHP version: 8.3.10
- Installation type: Shared hosting
- Web server type: Apache 2.4.62

**Comment by Alkarex** [comment]
Watch out that `1.25.0-dev` requires PHP 8.1+ and you seem to run PHP 7.4. What OS is used on your shared hosting? PHP 7.4 is mostly not supported anymore.
https://github.com/FreshRSS/FreshRSS/blob/edge/CHANGELOG.md

You are supposed to get some errors in your logs, though.
Finally, when you run locally, make sure to use `actualize_script.php` and not via curl.

**Comment by Arnoud-B** [comment]
The server is running PHP 8.3.10. However, I see now that the cron is running the actualize script using 7.4. Updated the cron job to use 8.3, and it seems to work again. FreshRSS.log is not empty anymore either. Thanks for the pointer!
