### ISSUE TITLE
Ne pas rafraîchir les flux des utilisateurs non logués depuis x jours/semaines/mois

### ISSUE THREAD

**Issue by ldidry** [FreshRSS/FreshRSS#681]
Les utilisateurs n'utilisant pas le service depuis un certain temps ne devraient pas avoir leur flux rafraîchis. Cela utilise des ressources inutilement.

Dans l'interface d'admin, un champ number fera l'affaire :

= 0 => openbar

!= 0 => pas de rafraîchissement si pas logué depuis X jours

**Comment by Alkarex** [comment]
@ldidry Avez-vous eu l'occasion d'essayer l'option `max_inactivity` introduite il y a quelques mois en réponse à votre demande ?

**Comment by Alkarex** [comment]
A priori, il ne manque qu'une interface Web pour modifier les limites plus facilement. Voir https://github.com/FreshRSS/FreshRSS/issues/680 pour la suite.
