### ISSUE TITLE
[Bug] FreshRSS is sending a referrer when there is none

### ISSUE THREAD

**Issue by markcellus** [FreshRSS/FreshRSS#6811]
### Describe the bug

I'm a provider of RSS feeds and FreshRSS is populating the `referrer` header of each feed request with the host domain of the feed. There is no referrer when making a request and it's value is not correct. The `referrer` header should be empty in these cases.

### To Reproduce

1. Get the app to make a request to an RSS feed on a server
2. Look at the `referrer` request header in the request logs on the server
3. Notice that the `referrer` is populated with the host server of the RSS feed

### Expected behavior

The `referrer` request header to be empty.

### FreshRSS version

1.2x

### Environment information

- Database version: [e.g. Mysql 5.7, SQLite]
- PHP version: [e.g. PHP 8.1]
- Installation type: [e.g. Docker, Docker image source, git, Yunohost]
-Web server type: [e.g. Apache, nginx]
- Device: [e.g. iPhone13]
- OS: [e.g. Ubuntu 22.04, Win10, MacOS14]
- Browser: [e.g. Firefox 124]

**Comment by Alkarex** [comment]
Related to https://github.com/FreshRSS/FreshRSS/pull/6523#issuecomment-2351158362
Could you please explain what problem it makes to you?
P.S. And what is the Referer value in this problematic case?

**Comment by markcellus** [comment]
As mentioned earlier, the referrer value in this case is the host of the RSS feed to which FreshRSS is making the request.

The `referrer` header is used for our internal debugging purposes, logging, and to evaluate potentially malicious traffic. Also identified in [RFC 9110](https://httpwg.org/specs/rfc9110.html#field.referer).

What is the reason FreshRSS is populating this header at all, opposed to just being empty?

**Comment by Alkarex** [comment]
The Referrer comes from the [underlying library SimplePie](https://github.com/simplepie/simplepie). Plenty of servers are filtering requests on various HTTP headers (including User-Agent, Referer...) and might reject requests when not populated with something expected. Now I have not build up statistics recently on servers rejecting requests due to lack of Referer, but I have seen some in the past. On the contrary, it has been rare to hear problems for having a Referer field ([1 example](https://github.com/simplepie/simplepie/issues/224)).
The problem with those headers is that they have been misused, and it is just as wrong to assume an empty or not-empty value.
I am not against removing this Referer header, but before that, I would need some statistics on many feeds, and the discussion should best take place upstream https://github.com/simplepie/simplepie

**Comment by Alkarex** [comment]
By the way, now that you are here, you might be interested in having a look at my work-in-progress to add long-due support for HTTP cache headers https://github.com/FreshRSS/simplepie/pull/26

**Comment by markcellus** [comment]
If there are sites that rejecting requests if the field isn't populated, my recommendation is to set the header explicitly for those sites and leave it unset for all other rss feed requests. 

> The problem with those headers is that they have been misused, and it is just as wrong to assume an empty or not-empty value.

I'm not quite sure what you mean here. According to the RFC 9110 I linked to above, FreshRSS is misusing the `referrer` header. That's why I opened this issue. 

Using mysite.com (a ficticious site) as an example, we are seeing that FreshRSS is sending `mysite.com` as the `referrer` when making a request to the same site's RSS feed at `mysite.com/rss/feed.xml`. 

Based on the RFC specification, this is not a correct use of the header. Not specifying a `referrer` at all is more appropriate for these cases.

Unfortunately my time is limited, so I can't engage in any further upstream discussion about it. But FreshRSS is likely to continue to trigger malicious bot detection and potentially be blocked if the `referrer` header continues to be populated with an invalid value.

**Comment by Alkarex** [comment]
> According to the RFC 9110 I linked to above, FreshRSS is misusing the `referrer` header.

Could you please quote what more precise part of that RFC you are referring to? Best if it is a *MUST NOT* rule. 
I do not immediately find any corresponding statement.

**Comment by Alkarex** [comment]
I plan to make a test with the set of test feeds I have (~200) and see whether any of them complain. If not, we could try to delete the Referer at the same time as we will be adding the possibility to add custom HTTP headers https://github.com/FreshRSS/FreshRSS/issues/6784

**Comment by Alkarex** [comment]
Custom HTTP headers added https://github.com/FreshRSS/FreshRSS/pull/6820

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/6822
