### ISSUE TITLE
[Bug] Article content recently showing ASCII Codes (#xxx) in the web UI or via Sync Client

### ISSUE THREAD

**Issue by quella** [FreshRSS/FreshRSS#6813]
### Describe the bug

I am running the latest developer (edge) version via Docker.  In the past few days I have started noticing a few of my more common news sites that often leverage more special characters such as the single quote (') are instead showing [word #039 s].  For example, England #039 s instead of "England's", etc.  I assumed this would be reported and corrected, but as of this post it is still being observed.  

### To Reproduce

No real reproduction as this is occurring with all special character sets on all feed articles that contain them.

### Expected behavior

Instead of showing the ASCII markdown codes (#039) the returned character should show the proper character such as the single quote [']

### FreshRSS version

Latest Edge Docker Build

### Environment information

- Database version: Default
- PHP version: Default
- Installation type: Docker EDGE (latest Development)
-Web server type: Default
- Device: Web UI
- OS: Ubuntu 24.04 Docker
- Browser: Chrome, but also in a sync with apps like Reeder

### Additional context

Attached is an example screenshot from the main reader page from the Web UI so better show the issue.  

![Screenshot 2024-09-16 at 9 30 46 AM](https://github.com/user-attachments/assets/8006b4b5-f72d-47d5-aaa3-6fd0ade08b4b)

**Comment by Alkarex** [comment]
Hello, 
Please provide some examples of feeds exhibiting this problem

**Comment by quella** [comment]
@Alkarex, thank you for asking as this has helped me to see that the issue does not appear to be with FreshRSS, but instead with the "Full Feed RSS" application that attempts to pull the article's full feed details.  The ones I'm seeing that have the reported issue with inserted ASCII character values all seem to be ones that also are being processed by the Full Feed RSS tool.  Sorry for the open report prior to fully understanding that this was from the third-party tool.  I will close this bug report and reach out to the other application's team.
