### ISSUE TITLE
[Bug] Shortcut "s" for sharing does not work

### ISSUE THREAD

**Issue by ddeimeke** [FreshRSS/FreshRSS#6815]
### Describe the bug

In former times, I was able to share articles to my Wallabag installation, using the hotkey "s"-

### To Reproduce

Go to any article and press "s".

### Expected behavior

Open the configured sharing service.

### FreshRSS version

1.25.0-dev 

### Environment information

- Database version: MariaDB 10.6.18
- PHP version: 8.1.29
- Installation type: Git
-Web server type: Apache
- Device: Desktop
- OS: Arch Linux
- Browser: Firefox

**Comment by Alkarex** [comment]
I am guessing it might be a regression due to https://github.com/FreshRSS/FreshRSS/pull/6751

**Comment by Frenzie** [comment]
Confirmed, it doesn't work anymore and it did not too long ago.
