### ISSUE TITLE
Utilisation de sprites CSS pour les icônes

### ISSUE THREAD

**Issue by ldidry** [FreshRSS/FreshRSS#682]
L'utilisation de sprites CSS allège le chargement d'une page, et donc accélère le chargement :-)

Pour en créer facilement : http://www.spritecow.com/

Attention, j'ai pas dit pour les favicons, non, mais pour les icônes des boutons (lu, non-lu, etc)

**Comment by PapsOu** [comment]
Et pourquoi ne pas utiliser http://fortawesome.github.io/Font-Awesome/icons/ ?

**Comment by marienfressinaud** [comment]
J'étais justement en train d'y réfléchir ! Je me demande juste si Gnome ne propose pas une font similaire pour les icones que l'on utilise (ce ne serait pas impossible), j'y jetterai un œil à l'occasion.

**Comment by PapsOu** [comment]
En tout cas fontawesome est très facile à intégrer et offre une collection d'icônes plutôt riche. Le poids n'est pas énorme et c'est hyper simple à utiliser : 

``` html
<i class="fa fa-globe"></i>
```

**Comment by aledeg** [comment]
C'est amusant car je suis tombé dessus aujourd'hui. Il y a même moyen de n'en intégrer qu'une portion. La technique est décrite [ici](http://www.alsacreations.com/astuce/lire/1661-accelerez-vos-polices-d-icones.html)

**Comment by ldidry** [comment]
Pour ne choisir que les icônes qu'on veut, le plus simple est d'aller sur http://fontello.com/, qui permet d'utiliser aussi d'autres polices que font awesome.

**Comment by aledeg** [comment]
Encore un exemple pour l'utilisation de sprite en SVG. http://www.sitepoint.com/use-svg-image-sprites/
Il faudrait savoir dans quel navigateur cela fonctionne et quel navigateurs on laisse tomber.
Ça fonctionne dans FF35 sur Win7, dans FF36 sur Archlinux

**Comment by marienfressinaud** [comment]
On peut aussi créer nos fonts ou un sprite SVG sur https://icomoon.io/app et donc réutiliser les icônes actuelles (Fontello ne permet que de créer les fonts il me semble). Il faut effectivement comparer les pour et contre des deux solutions font et sprite.

**Comment by aledeg** [comment]
Je viens d'essayer avec les sprites SVG mais ça ne règle pas le problème des connexions.
Il y a toujours une connexion effectuée par id. Si besoin, je peux faire une branche publique avec mon test.

**Comment by Alkarex** [comment]
@aledeg Avec quelle syntaxe as-tu essayé ? À noter que le HTTP/2, qui est en train de se déployer très vite, résout nativement une bonne partie du problème.

**Comment by aledeg** [comment]
J'ai utilisé la syntaxe avec les identifiants de fragments en suivant la documentation que j'avais donné un peu plus haut

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/issues/833

**Comment by marienfressinaud** [comment]
J'ai commencé à bosser dessus ce matin. J'ai choisi la méthode https://icomoon.io/app : 
- J'ai chargé les anciens icônes dans IcoMoon
- J'ai généré les fonts qui-vont-bien et je les ai importées dans FRSS
- J'ai modifié `FreshRSS_Themes::icon()` pour qu'il retourne le code HTML qu'il faut
- J'ai ajouté dans `base-theme/template.css` le code qu'il faut

Avec un minimum de manipulation donc, j'ai déjà un truc qui fonctionne : 
![capture d ecran de 2015-07-16 10-37-50](https://cloud.githubusercontent.com/assets/1436309/8718779/3e5ee74e-2ba7-11e5-9473-de3b0624686a.png)

Avantages : 
- On a plus qu'un seul fichier à charger, celui de la font (c'est quand même loin d'être négligeable)
- On peut changer les couleurs des icônes dynamiquement, on est donc bien plus flexibles (voir la capture d'écran avec les favoris et non-lus)

Désavantages : 
- On perd en accessibilité vu qu'on n'a plus les "alts" qui viennent remplacer les images si elles ne sont pas chargées. Perso je ne pense pas que ça soit dramatique, non pas parce que je me fiche de l'accessibilité (au contraire), mais plutôt que je pense qu'on devrait réfléchir à une interface alternative optimisée pour l'accessibilité.
- On perd en flexibilité pour la création de thèmes alternatifs puisqu'il faut recréer les fonts entièrement juste pour changer une seul icône. Je pense que vu les avantages, on peut faire avec.
- Il va falloir passer un peu de temps pour s'assurer de réparer les trucs cassés (par exemple les prefetch des icônes qui ne sont plus utiles ou le changement dynamique des lus / non-lus, favoris / non-favoris lorsqu'on change le statut des articles).

**Comment by Alkarex** [comment]
Pourquoi les SVG fragments? Je n'aime pas le détournement des `<span>` ou autres `<i>` :-(

**Comment by marienfressinaud** [comment]
Et bien parce que je galérais à le mettre en place mais maintenant c'est bon :). Je regarde ça ;).

**Comment by Alkarex** [comment]
Ok :-)
Si nous allons du côté des polices, il serait possible de conserver nos caractères alternatifs Unicodes comme ☑ ou ☆, et de les redéfinir dans la police. Ça serait, je pense, le plus léger et robuste.
Sinon, en cas de `<span>` ou `<i>`, je trouve qu'il faudrait au moins conserver le caractère alternatif en Unicode, et le cacher après chargement de la police, histoire d'avoir au moins quelque chose si le chargement de la police ne marche pas ou prend trop longtemps.

**Comment by marienfressinaud** [comment]
Bon en fait je m'en sors pas tant que ça : le SVG généré arrive à fonctionner avec la syntaxe 

``` svg
<svg>
  <use xlink:href="../icons.svg#add"></use>
<svg>
```

Mais pas avec une `<img />` :-/. Je ne sais pas si @aledeg a encore le sprite qu'il avait utilisé quand il a essayé, sinon je ferai à la main parce que je ne trouve pas d'outil pour générer ce que je veux :(

**Comment by aledeg** [comment]
Je crois que je l'ai encore, je vais essayer de le charger ce soir dans une branche.
Arrive tu à ne faire qu'une seule requête vers le serveur avec ton sprite? De mon côté, quand j'avais essayé, ça ne changeait rien de ce côté là.

**Comment by marienfressinaud** [comment]
Avec ma syntaxe oui, mais avec `<img />` ça semble vouloir en faire plusieurs malheureusement...

**Comment by aledeg** [comment]
Regarde https://github.com/aledeg/FreshRSS/tree/sprite, j'y ai inclus ce que j'avais fait pour tester les sprites.
J'avais fait les sprites à la main en collant chaque élément dans un svg.

**Comment by marienfressinaud** [comment]
Ok merci, je regarderai ça :)

**Comment by marienfressinaud** [comment]
Alors oui ça marche et oui des requêtes multiples sont effectuées dans Firefox... mais il s'agit [apparemment d'un bug](http://stackoverflow.com/questions/27714853/svg-stacking-anchor-elements-and-http-fetching) ([ticket ouvert sur Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1121693)). Du coup c'est un peu chiant vu que le but était justement de réduire le nombre de requêtes...

Sinon, bug étrange dans Epiphany (Web), toutes (ou presque) les icônes sont décalées d'un cran : 

![capture d ecran de 2015-07-17 09-40-15](https://cloud.githubusercontent.com/assets/1436309/8742653/dfe5cf68-2c67-11e5-900d-e84b366bc708.png)

**Comment by Alkarex** [comment]
Voir HTTP/2 https://github.com/FreshRSS/FreshRSS/issues/1089

**Comment by aledeg** [comment]
I don't know if we're going to do that one day. But if we do, this [tool](https://libresprite.github.io/) might come handy.

**Comment by Alkarex** [comment]
I think the combination of HTTP/2 and lazy loading have greatly reduced the need for that

**Comment by aledeg** [comment]
Here is another [online tool](https://spritegen.website-performance.org/)

**Comment by Frenzie** [comment]
I agree with @Alkarex.

**Comment by aledeg** [comment]
So it might be better to close this issue to reduce the noise. It hasn't been addressed for the past 7 years, I think it's time to let go :)
