### ISSUE TITLE
[Bug] 1.24.2 has been republished to Docker Hub

### ISSUE THREAD

**Issue by brhahlen** [FreshRSS/FreshRSS#6829]
### Describe the bug

On Docker Hub, 1.24.2 is now regarded as _latest_, while 1.24.3 is not anymore.

### To Reproduce

1. Go to https://hub.docker.com/r/freshrss/freshrss/tags

### Expected behavior

1.24.3 should be latest

### FreshRSS version

1.24.3

### Environment information

- Installation type: Docker

**Comment by Alkarex** [comment]
Thanks for the heads up! This was indeed not intentional. I changed a typo to the release message of 1.24.2 yesterday and did not expect that this would trigger a new push to Docker Hub...
I am re-pushing 1.24.3 immediately
