### ISSUE TITLE
Add sharing service for Telegram

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#6837]
Do you know how could I achieve the same sharing functionality you added for Whatsapp, but for Telegram?

_Originally posted by @arseru in https://github.com/FreshRSS/FreshRSS/issues/6395#issuecomment-2373915643_

**Comment by math-GH** [comment]
ping @arseru

1) please have a look into #6838. Does it work for you? Test are welcome.
2) you can use the "default sharing" service. It will use your system default sharing that enables the sharing with all installed apps

**Comment by arseru** [comment]
Hi @math-GH, thanks for this, I can confirm it works fine on my end! Here are a few screenshots when sharing via Telegram the item <https://github.com/FreshRSS/FreshRSS/releases/tag/1.24.3> from the default feed included in a new docker installation - clicking the "Telegram" share button send me to [this t.me link](https://t.me/share/url?url=https://github.com/FreshRSS/FreshRSS/releases/tag/1.24.3&text=FreshRSS%201.24.3%20-%20Release%20notes%20from%20FreshRSS%20(Alkarex)):

![image](https://github.com/user-attachments/assets/38321002-6ed8-4367-91ea-bcd495e8fafa)

Which finally gets sent as:

![image](https://github.com/user-attachments/assets/023d9bfb-8e67-41a2-bbe4-07649f65aaef)
