### ISSUE TITLE
[Feature] Tag filtering for ignoring articles

### ISSUE THREAD

**Issue by Redsandro** [FreshRSS/FreshRSS#6843]
**Is your feature request related to a problem? Please describe.**

I’m always frustrated when I need to dig through articles I don't care about, for example sports in a news feed.

**Describe the solution you’d like**

I would like a simple to use method for ignoring or removing or marking as "read" such articles using tags that news sites often apply to the html article:

```html
<meta content="sports, football, game" property="og:article:tag">
```

In this case, I would like to trash or mark as read **if og:article:tag contains sports**.

**Describe alternatives you’ve considered**
I haven't figured out a way to do this within FreshRSS, but I tried to write a selector in the developer console:

```javascript
document.querySelector('meta[property="og:article:tag"]').getAttribute('content').includes('sports')
# true
```

```javascript
['sports', 'football', 'politics'].some(tag => 
    document.querySelector('meta[property="og:article:tag"]')?.getAttribute('content')?.includes(tag)
)
# true
```

**Additional context**

**Comment by math-GH** [comment]
Have you tried this feature already?
It is in the feed configs.

![grafik](https://github.com/user-attachments/assets/b17821b8-8373-4171-8bef-59f21091129f)

**Comment by Redsandro** [comment]
@math-GH Now that you mention it, I do remember struggling with this some time ago, and I thought it was too limited. It would make my day if you can tell me I'm wrong. 

I thought it only works with predefined google-like searches such as `intitle` and I don't really understand the [documentation](https://freshrss.github.io/FreshRSS/en/users/10_filter.html#with-the-search-field): What does it search? Only predefined filters? Literal meta tags? The graph? 

How do you use a colon in the meta-tag if the meta-tag goes before the colon, i.e. `og:article:tag:sports`? 

Does #tag only search `<meta name="keywords"` or also `<meta property="og:article:tag"`? ~~Also, space implies `AND`, but many tags I want to filter contain spaces. Such as `#FC Twente`.~~

I couldn't get it to work. Is it case sensitive? Do I need to try again? It's difficult to test matches, because you need to wait until a matching article is published. It would be helpful if there was a match test, similar to "Advanced" -> "Article CSS selector on original website" -> eyeball.

**Update:**

> by tag: #tag **or #tag+with+whitespace or #'tag with whitespace'**

I will set some simple tags with both small case and Upper case, and see if they match OpenGraph tags as well as meta keywords. It will take some time before I know if it works. Thanks for reminding me.
