### ISSUE TITLE
[i18n] Translation Spanish (ES) 🇪🇸 - Hacktoberfest Task

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#6845]
Dear Hacktoberfest-Community,

please help us to improve our Greek translations.

While we develop our [FreshRSS ](https://freshrss.org/) app we cannot support the translations in all 20+ languages. 

## About the FreshRSS app
FreshRSS is a free, self-hostable feed aggregator licenced by [GNU3.0](https://github.com/FreshRSS/FreshRSS/blob/edge/LICENSE.txt). These days we celebrate the 11th birthday!

## Actual Status
Right now only 4 phrases are not translated into Spanish.

```
'greader' => 'Shareable link to the GReader JSON'
'when' => 'Mark an article as favourite…'
'http_headers_help' => 'Headers are separated by a newline, and the name and value of a header are separated by a colon (e.g: <kbd><code>Accept: application/atom+xml<br />Authorization: Bearer some-token</code></kbd>).'
'http_headers' => 'HTTP Headers'
```

## How to support us
How to do it:
1) it is very simple
2) all files are stored in `https://github.com/FreshRSS/FreshRSS/tree/edge/app/i18n/es` ([Link](https://github.com/FreshRSS/FreshRSS/tree/edge/app/i18n/es))
3) each untranslated text has an inline comment `//  TODO`
4) When the text is translated, just delete the comment
5) If the English term fits as well, please change the comment from `//  TODO` to `//  IGNORE`
6) open a Pull Request and link to this ticket

## Thanks
Thanks a lot. It will help our very international community of users and developers. Your submitted PRs will be published with our next release version 1.25.0

**Comment by DevGrohl** [comment]
I got this one, please assign it to me

**Comment by DevGrohl** [comment]
https://github.com/FreshRSS/FreshRSS/pull/6894
