### ISSUE TITLE
[Feature] Delayed User Query resolution filter option

### ISSUE THREAD

**Issue by mtalexan** [FreshRSS/FreshRSS#6849]
**Is your feature request related to a problem? Please describe.** 
 
I would like to be able to define a set of filter patterns and use it in Labels, and/or multiple per-RSS feed mark-as-read filters, but also be able to update the definition used in all the locations by changing the global definition. 

**Describe the solution you’d like**

The current `search:` keyword is very close, except when you save a label or per-feed mark-as-read pattern it immediately substitutes the current definition of that user query into the pattern. If I discover I need to go back and tweak the user query, I have to go everywhere I put the `search:`, delete the substitution, and re-add the `search` keyword so it re-substitutes with the updated definition.    

I'd like to instead be able to do something like `searchref:` and leave it unresolved until the actual filtering occurs. Whatever the definition is at that point gets used, but the saved Label or per-feed mark-as-read pattern keeps the `searchref:` syntax in it. That would allow me to make tweaks to the global pattern and not have to go update all locations I've referenced it any time it changes. 

**Describe alternatives you’ve considered**

A completely separate workflow that can set global filters and actions, selecting across a range of feeds to apply the filter to (or not), and define custom actions to take when the filter is matched? I know there's some discussion of something like this in the long term, but it would be great to have a stop gap in the shorter term.

**Additional context**

I would guess this would also impact the directly entered queries, the user could theoretically enter `searchref:AName` if they wanted to and it would do the search but the pattern in the search box would remain unchanged. I don't know why they'd want to do that, but they could I guess.

**Comment by Alkarex** [comment]
Could you try https://github.com/FreshRSS/FreshRSS/pull/6851 ?
Note that recursive and transitive calls (searches calling searches calling searches...) are not supported

**Comment by mtalexan** [comment]
> Could you try #6851 ? Note that recursive and transitive calls (searches calling searches calling searches...) are not supported

That code looks like it adds depth 1 nesting of search in search, no?  
Did I miss where it also deferred resolution of the search into it's underlying pattern?  
Or is there some other way it could be used to solve my issue?

**Comment by Alkarex** [comment]
If I am not mistaken, the proposed patch should solve your issue:
You can define a user query with name `A` and use it in multiple other user queries or filters like `search:A something more` without observing the replacement as was the previous behaviour

**Comment by mtalexan** [comment]
It's doing exactly what I was looking for, thank you.

**Comment by Alkarex** [comment]
Excellent. Merged in `edge`. Please continue testing some more for any bug
