### ISSUE TITLE
[Bug] Article Titles Open in New Tab Instead of Expanding

### ISSUE THREAD

**Issue by calbeeb-grape** [FreshRSS/FreshRSS#6861]
### Describe the bug

When viewing the article stream, clicking on an article title should expand the article content below. However, I'm consistently experiencing an issue where clicking on the article title opens the article's origin website in a new tab.

To expand the article, I have to click on the timestamp located to the right of the article title.

### To Reproduce

1. Go to 'main stream' (or any label)
2. Click on 'any article title'
3. Observe that it has opened in a new tab to the 3rd party site as the hyperlink suggested

### Expected behavior

The article should have expanded

### FreshRSS version

1.24.3

### Environment information

- Database version: SQLite
- PHP version: 8.2.20
- Installation type: Docker
-Web server type:
- Device: PC
- OS: Win11
- Browser: Edge 128, Chrome 129, Firefox 130

### Additional context

I have confirmed that this issue is not related to browser extensions. I have tested in a clean installation of both Chrome and Firefox, and the same behavior persists.

**Comment by Alkarex** [comment]
Hello,
This is typically a sign of JavaScript error due to some kind of interference. What Docker image are you using more precisely, and with which type of deployment (proxy...)?
Please check your Web browser console for warnings / errors.
You are also expected to see the message "_FreshRSS main init done_." relatively fast after navigating to a FreshRSS page. If not, something is wrong.

**Comment by calbeeb-grape** [comment]
Thank you for your prompt response!

I'm using the f877e0c7c6df Docker image and have deployed FreshRSS using Cloudflare Tunnel.

As you suggested, I checked my browser console and found the following messages:

```
main.js?1725643442:1913 FreshRSS waiting for content…
main.js?1725643442:1971 FreshRSS waiting for DOMContentLoaded…
grey.gif:1 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
grey.gif:1 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
main.js?1725643442:1961 FreshRSS main init done.
i/:1 <meta name="apple-mobile-web-app-capable" content="yes"> is deprecated. Please include <meta name="mobile-web-app-capable" content="yes">
```
However, I'm still experiencing the issue where clicking on article titles opens the article's origin website in a new tab.

Could you please provide any additional troubleshooting steps or potential solutions based on this information?

**Comment by Alkarex** [comment]
> deployed FreshRSS using Cloudflare Tunnel

That is a likely culprit. Do you have any possibility to try directly without this tunnel?

And would you be able to make me a test account on your FreshRSS instance?

**Comment by calbeeb-grape** [comment]
I believe I've identified the root cause of the issue. It seems that the '[Pocket Button](https://github.com/christian-putzke/freshrss-pocket-button)' plugin was interfering with the article expansion functionality. After disabling it, I'm able to expand articles as expected.

Thank you so much for your assistance!!

**Comment by Alkarex** [comment]
@calbeeb-grape Ok, please open an issue there then https://github.com/christian-putzke/freshrss-pocket-button/issues

**Comment by Alkarex** [comment]
https://github.com/christian-putzke/freshrss-pocket-button/issues/4#issuecomment-2395002072
https://github.com/FreshRSS/Extensions/pull/253

**Comment by Wendigogo** [comment]
Hi,

Sorry to pop up this issue but I got the exact same problem with the "Readeck Button" extension.
I'll open an issue [https://github.com/Joedmin/xExtension-readeck-button/issues](https://github.com/Joedmin/xExtension-readeck-button/issues) hoping it will fixed too.

Just FYI.

Enjoy !

EDIT : opened issue : [https://github.com/Joedmin/xExtension-readeck-button/issues/2](https://github.com/Joedmin/xExtension-readeck-button/issues/2). I hope that the copy-paste of this issue as bug description doesn't hurt anyone.
