### ISSUE TITLE
[Bug] Space shotcut get white background before redirect

### ISSUE THREAD

**Issue by czf1009** [FreshRSS/FreshRSS#6862]
### Describe the bug

I am using docker version.

If i use shotcut "space" to open in new tab, it will first open a white background page before redirect, but if use mouse left click title, it become dark background page.

Browser use dark mode, other page is normal dark background.

Use "space" shotcut:
![image](https://github.com/user-attachments/assets/91c444bf-5ce5-4423-8910-757d3ab81fb5)

Use left click title:
![image](https://github.com/user-attachments/assets/426aefa7-24f6-4321-9263-5dd4fe0688c7)

### To Reproduce

Use "space" to open a new tab.

### Expected behavior

As same as left click

### FreshRSS version

1.24.3

### Environment information

Docker image: freshrss/freshrss:latest

**Comment by Alkarex** [comment]
Slightly related to https://github.com/FreshRSS/FreshRSS/pull/5146 , maybe for @Frenzie

**Comment by Alkarex** [comment]
I think the culprit is this code. It is probably a regression due to https://github.com/FreshRSS/FreshRSS/pull/2506 so ideas about how to do it better would be welcome

https://github.com/FreshRSS/FreshRSS/blob/2489b6259ad334407c023eb60722c9746d973542/p/scripts/main.js#L1080-L1085

**Comment by Alkarex** [comment]
Should be updated with `noopener` https://stackoverflow.com/questions/40593632/use-window-open-but-block-use-of-window-opener/46958731#46958731
PR welcome

**Comment by Frenzie** [comment]
Also mentioned in https://github.com/FreshRSS/FreshRSS/pull/2506#discussion_r316109370

**Comment by Alkarex** [comment]
Yes, but 5 years later, we can hope for the support to have improved :-)

**Comment by Frenzie** [comment]
Yes, old IE and even pre-Chromium Edge is no longer relevant, so for all intents and purposes it's been widely supported for four years now, roughly since that PR. I'd say you need at least a year of margin but even that's three years past now.

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/7077
tests welcome

**Comment by czf1009** [comment]
Updated the docker image and it worked! Thanks a lot!
