### ISSUE TITLE
Allow Mark as read to move to the next peer on Labels

### ISSUE THREAD

**Issue by mtalexan** [FreshRSS/FreshRSS#6867]
### Describe the bug

Unlike categories and feeds, marking everything in a Label as read isn't moving to the next peer Label.

### To Reproduce

1. Go to the first label with unread articles in it
2. Have a second label following it with its own unique unread articles in it
3. Scroll to the bottom of the article list and click the "mark all as read" checkbox
4. Notice the view doesn't move to the next label with unread articles

### Expected behavior

The mark all as read moves to the next peer label just like how it moves to the next unread feed when marking a feed as read, or to the next category when marking a category as read.

### FreshRSS version

1.25.0-dev (current edge)

### Environment information

- Database version: SQLite
- PHP version: 8.3.10
- Installation type: Docker (using official Alpine Dockerfile from edge)
-Web server type: Apache
- Device: Android Pixel Fold
- OS: OpenSUSE MicroOS Server
- Browser: Firefox 131.0

### Additional context

This is the same when using the Mark as Read button from the top bar.  

Maybe there's some worry about knowing what the next peer label is with unread articles in it since the same articles can appear in multiple labels and if you justarked those as read in the current label, the next peer label with unread articles can change after the "mark as read"?

**Comment by math-GH** [comment]
That is why there is written "feed or category". It works only there.
![grafik](https://github.com/user-attachments/assets/db28d749-9973-465d-a7e9-638daabaf0da)

As todo I see that the second sentence should be not visible in the labels view
![grafik](https://github.com/user-attachments/assets/721d8bba-1a8c-49a1-bbe1-1704aabdf9a6)

**Comment by mtalexan** [comment]
Maybe I should turn this into a feature request then?
