### ISSUE TITLE
[Feature] Sharing article to Wallabag with its API feature

### ISSUE THREAD

**Issue by Wendigogo** [FreshRSS/FreshRSS#6874]
Hi,

I just want to know if it's possible to share an article with Wallabag (V2) API apps.
And if not, is it possible to add this feature

I already generated an API app on Wallabag but in FreshRSS, there is nowhere to set thesr credentials.

The only way I found is from the sharing option but I need to log in my wallabag instance with my user profile instead of the API app.

The Readeck sharing extension do exactly what I expect.

Thanks for this amazing project anyway.

**Comment by Joedmin** [comment]
I am willing to write it, I'll just reuse the code for Readeck

**Comment by Joedmin** [comment]
The extension is available at https://github.com/Joedmin/xExtension-wallabag-button, will open a PR in the Extensions repository

**Comment by Joedmin** [comment]
See https://github.com/FreshRSS/Extensions/pull/254

**Comment by Wendigogo** [comment]
Thank you so much for this extension !
