### ISSUE TITLE
[Feature] Enabling of srcset as a provider of article images

### ISSUE THREAD

**Issue by nbgibson** [FreshRSS/FreshRSS#6875]
**Is your feature request related to a problem? Please describe.**
I use the "HTML + XPATH" feature set to "encourage" websites that do not provide feeds to play nice with FRSS and my preferred reader. Recently one of these sites moved over to using <srcset> tags which has broken the ability of FRSS to pull thumbnail images in. This is bothersome as eyeballing the images was my preferred way of determining if a given article in the feed was something I'd like to examine closer.

[This appears to be a deliberate restriction](https://github.com/FreshRSS/FreshRSS/blob/b30a8fa652018025f8ccc6b361823486d04cf390/lib/lib_rss.php#L318) though I'm not sure why; though that's entirely of my own ignorance I'll be the first to admit.

**Describe the solution you’d like**
I'd like a reexamination of why srcset was added as an attribute strip and a determination if it can be practically re-added as a source. Failing that, I'd appreciate any suggestions for a potential workaround.

**Describe alternatives you’ve considered**
I've been playing with different XPATH configurations to see if some other means can be achieved to get the blasted images, but none have worked so far. I've also investigated using 3rd party solutions to create a feed from the target website but they have not provided a viable solution thus far.

**Additional context**
Target "feed" in question: https://www.nytimes.com/wirecutter/deals/
Yes, I'm *still* mad that they pulled the actual factual feed for this after the NYT acquisition.

**Comment by Frenzie** [comment]
See https://github.com/FreshRSS/FreshRSS/pull/5154

**Comment by nbgibson** [comment]
Closing as this is a known matter.
