### ISSUE TITLE
[Bug] Articles not marked as read despite fulfilling rule

### ISSUE THREAD

**Issue by Tywele** [FreshRSS/FreshRSS#6877]
### Describe the bug

One of my feeds seems to ignore the filters I have set to mark certain articles as read automatically.

I have set `#Film+&+TV+-+Reality+&+Casting` to set all articles with that tag to be markeda as read (in the feed settings; not globally). When I search for them in the search with the same rule I find all articles with the tag but they don't get marked as read automatically. The feed in question is https://www.queer.de/rss/newsticker2.0.komplett.xml. Other rules like `#Gewinnspiel` or `#Musik+-+Aktuell` are working.

### To Reproduce

1. Subscribe to the aforementioned feed (https://www.queer.de/rss/newsticker2.0.komplett.xml)
2. Set `#Film+&+TV+-+Reality+&+Casting` as the rule for marking articles as read in the feed settings
3. Wait for an article with that tag to come in
4. See that the article is not marked as read

### Expected behavior

 I expect articles with that tag to be marked as read automatically.

### FreshRSS version

1.24.3

### Environment information

- Database version: SQLite
- Installation type: Docker

**Comment by Alkarex** [comment]
Hello,
I believe this is fixed in our rolling release `edge`. Could you give it a try?
If you use our official Docker image, you can just change to `freshrss/freshrss:edge`

**Comment by Tywele** [comment]
I can try that.

**Comment by Tywele** [comment]
I have tried it now with version 1.25.0-dev but I'm still seeing articles not marked as read automatically with certain filter rules.

**Comment by Alkarex** [comment]
What are your rules, that are not working?
Edit: Note that the rules will only be applied to new articles, not to existing articles

**Comment by Tywele** [comment]
These are I think some if not all the rules that don't work: 

#Film+&+TV+-+Serien
#Film+&+TV+-+Reality+&+Casting
#Film+&+TV+-+Dramen
#Film+&+TV+-+Aktuell
#Film+&+TV+-+Dokumentationen

I'm aware that it only applies to new articles.

**Comment by Alkarex** [comment]
Quick test with your filters on https://www.queer.de/rss/newsticker2.0.komplett.xml after removing all articles and refreshing the feed:

![image](https://github.com/user-attachments/assets/f4b796cf-aeee-4dc4-9661-daf7cfa48adf)

![image](https://github.com/user-attachments/assets/d5665750-068c-4276-86a3-e8ebbd72d210)

Seems to work as it should, as far as I can see

**Comment by Tywele** [comment]
Maybe I just needed to clear all articles from this feed once to make it work correctly again. Nevertheless it's seems to be working now on v1.25.0-dev
