### ISSUE TITLE
[Bug] 403 Forbidden with OIDC setup

### ISSUE THREAD

**Issue by tyrossel** [FreshRSS/FreshRSS#6890]
### Describe the bug

When using the `edge` docker image, I cannot use the webapp with OIDC due to 403 error on the `/i/oidc` endpoint. 

It works well when switching back to `latest` image.

### To Reproduce

1. Open the main page `https://rss.example.com/`
2. Get redirected to `https://rss.example.com/i/oidc/?code=...&iss=...&scope=openid+profile&state=...`
3. Get a 403 error

### Expected behavior

Login works correctly and we should land on the main page with unread items.

### FreshRSS version

freshrss/freshrss:edge

### Environment information

- Database version: `postgres:16-alpine`
- PHP version: 
- Installation type: Docker
-Web server type: traefik
- Device: all
- OS: all
- Browser: all

### Logs

```
> docker compose logs -f freshrss
freshrss  | 192.168.XXX.XXX - - [13/Oct/2024:13:33:27 +0200] "GET /i/?rid=<redacted> HTTP/1.1" 302 461 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0"
freshrss  | [Sun Oct 13 13:33:28.110057 2024] [authz_core:error] [pid 48:tid 48] [client 192.168.XXX.XXX:0] AH01630: client denied by server configuration: /var/www/FreshRSS/p/i/oidc
freshrss  | 192.168.XXX.XXX - - [13/Oct/2024:13:33:28 +0200] "GET /i/oidc/?code=<redacted>&iss=https%3A%2F%2Fauth.example.ccom&scope=openid+profile&state=
<redacted> HTTP/1.1" 403 199 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0"
```

### Somewhat related Docker env vars:

```bash
TRUSTED_PROXY='10.0.0.0/16'
OIDC_ENABLED=1
# Authelia
OIDC_PROVIDER_METADATA_URL=https://auth.example.com/.well-known/openid-configuration
OIDC_CLIENT_ID=freshrss
OIDC_CLIENT_SECRET=<redacted>
OIDC_CLIENT_CRYPTO_KEY=<redacted>
OIDC_X_FORWARDED_HEADERS="X-Forwarded-Host X-Forwarded-Proto"
OIDC_SCOPES="openid profile"
```

**Comment by Alkarex** [comment]
Might be a regression due to https://github.com/FreshRSS/FreshRSS/pull/6881
Can you confirm you are using `freshrss/freshrss:edge` ?

**Comment by Alkarex** [comment]
Would you be able to try https://github.com/FreshRSS/FreshRSS/pull/6893 ?

To test a PR, you need to point your Docker or Docker Compose to the right PR, as such:

```yml
  freshrss:
    image: freshrss/freshrss:6893
    build:
      context: https://github.com/Alkarex/FreshRSS.git#allow-oidc
      dockerfile: Docker/Dockerfile
    ...
```

* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/freshrss/docker-compose.yml
* https://github.com/FreshRSS/FreshRSS/blob/edge/Docker/README.md#build-custom-docker-image

**Comment by tyrossel** [comment]
I confirm that the problem occured with the `freshrss/freshrss:edge` image only.

It is working again in the `freshrss/freshrss:6893` image, thanks for the quick fix !
