### ISSUE TITLE
[Bug] aria-hidden elements within post text are affected by css rule intended for UI elements

### ISSUE THREAD

**Issue by PetraOleum** [FreshRSS/FreshRSS#6909]
### Describe the bug

Pandoc (and potentially other software) marks image captions with `aria-hidden="true"` to avoid screen reader software from reading duplicated text between the caption and the alt text of the image itself - see [Pandoc#6491](https://github.com/jgm/pandoc/issues/6491). Ironically when a post generated like this is loaded into freshrss (either via a fulltext feed or a css selector) the rule at [frss.css#L412](https://github.com/FreshRSS/FreshRSS/blob/e04f0b3493b313dd47ef9fd93de1ccf023379dc7/p/themes/base-theme/frss.css#L412) applies overzelously and causes a user relying on sight (rather than a screen reader) to not see the caption at all.

### To Reproduce

1. Load a feed containing posts generated via pandoc 2.x (e.g. [mine](https://petras.space/atom.xml), which is what I'm testing - pardon my everything) that contain figcaption tags
2. Inspect element on an image that is supposed to have a caption containing its alt text
3. Observe that the figcaption element is greyed out

![Figure construct in devtools in firefox](https://github.com/user-attachments/assets/e1480daf-11fb-41b2-8163-6bc4dc41e51f)

This works even if the `<figcaption>` is transformed into a regular `<p>` tag or similar changes - it's the `aria-hidden="true"` that is causing the issue. 

### Expected behavior

aria-hidden is supposed to hide an element and its children from screen readers, but not from visual inspection. The caption should be visible.

### FreshRSS version

1.24.3

### Environment information

I expect this won't matter, but:

- Database version: Mysql 15.1
- PHP version: PHP 8.1
- Installation type: git
- Web server type: nginx
- OS: Manjaro rolling
- Browser: Firefox 131

**Comment by Alkarex** [comment]
Would you be able to test this patch? https://github.com/FreshRSS/FreshRSS/pull/6910 (~~not tested yet~~)

~~We need to ensure to not introduce regressions in e.g. (maybe obsolete) https://github.com/FreshRSS/FreshRSS/pull/2176~~

**Comment by Alkarex** [comment]
Tested. Seems fine

**Comment by Alkarex** [comment]
![image](https://github.com/user-attachments/assets/1a56a1b3-0d73-49f5-bdd9-b35605f8c95f)

**Comment by PetraOleum** [comment]
Tested and it works for me - thanks! I couldn't also test if the change affected the issue in #2115 as the relevant UI has changed too much.
