### ISSUE TITLE
[Bug] Installation Stuck on Step 3

### ISSUE THREAD

**Issue by dxman** [FreshRSS/FreshRSS#6911]
### Describe the bug

I'm trying to set up a fresh install in Docker on my NAS. Initially, everything appears to be working. No errors in the Docker logs, etc, so I begin to follow the web installation. Step 2 reports that all checks are green. On step 3, I enter the information for my MariaDB container and click Submit, but nothing happens. The page is not stuck loading or anything like that (it returns immediately), no visual feedback on the page to indicate any kind of error.

Things I checked:
- Nothing shown in the Docker log
- Firefox Dev Tools shows a PHP error, which appears when the page initially loaded (see screenshot below)
- There is an error in the container's NGINX log, indicating a permissions issue:
`2024/10/16 16:21:22 [error] 294#294: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  file_put_contents(/app/www/data/config.php): Failed to open stream: Permission denied in /app/www/app/install.php on line 150" while reading response header from upstream, client: 172.20.30.254, server: _, request: "POST /i/index.php?step=2 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "freshrss.mydomain.com", referrer: "https://freshrss.mydomain.com/i/index.php?step=2"`
- Attempting to track down the above error, I SSH-ed into my NAS and checked the permissions of the container's `/app/www/data/` directory and found that it was set to not be writable by anyone, including the owner (see screenshot below).

I'm pretty sure that the permission error is the cause, but I'm uncertain whether the issue is with FreshRSS itself, or if the issue is specific to the LinuxServer image. The offending directory was created by the container, so I don't believe it's a configuration issue on my part.

If there's any other info I can provide, just let me know. Thanks for your assistance!

_Firefox Dev Tools:_
![2024-10-16 16_48_08-Window](https://github.com/user-attachments/assets/40a698ba-34c3-4f92-a5fd-9e6ae758213e)

_Permissions of /app/www/data:_
![2024-10-16 16_48_41-Window](https://github.com/user-attachments/assets/8a400dfa-2879-4b02-ba79-fee83da0a514)

### To Reproduce

1. Use Docker Compose to start new FreshRSS container
2. Open web browser to begin installation process
3. Follow all prompts, up through Step 3
4. Click Submit on Step 3, nothing happens

### Expected behavior

Installation either advances to Step 4 or reports some kind of error

### FreshRSS version

1.24.3

### Environment information

- Database version: MariaDB 10.11.8
- PHP version: 8.3.12 (included in Docker image)
- Installation type: Docker (LinuxServer image)
-Web server type: nginx (included in Docker image)
- Device: Docker running on Synology NAS, accessed from client PC
- OS: Windows 10
- Browser: Firefox 131

### Additional context

My Docker Compose file (variables sourced from a corresponding ENV file):
```dockercompose
services:
  freshrss-app:
    container_name: freshrss-app
    image: ghcr.io/linuxserver/freshrss:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    depends_on:
      - freshrss-db
    networks:
      - freshrss-net
      - traefik-proxy-net
    # ports:
    #   - 80:80
    volumes:
      - ${DOCKER_APPDATA_DIR}/freshrss/config:/config
    environment:
      - PUID=${DOCKER_UID}
      - PGID=${DOCKER_GID}
      - TZ=${TZ}
    # labels for Traefik etc removed for brevity
  freshrss-db:
    container_name: freshrss-db
    image: ghcr.io/linuxserver/mariadb:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - freshrss-net
    volumes:
      - ${DOCKER_APPDATA_DIR}/freshrss/mysql-data:/config
    environment:
      - PUID=${DOCKER_UID}
      - PGID=${DOCKER_GID}
      - TZ=${TZ}
      - MYSQL_ROOT_PASSWORD=${FRESHRSS_MYSQL_PASSWORD}
      - MYSQL_DATABASE=${FRESHRSS_MYSQL_DB}
      - MYSQL_USER=${FRESHRSS_MYSQL_USERNAME}
      - MYSQL_PASSWORD=${FRESHRSS_MYSQL_PASSWORD}
networks:
  freshrss-net:
    name: freshrss-net
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.7.0/24
          ip_range: 172.30.7.0/24
          gateway: 172.30.7.254
    internal: true
  traefik-proxy-net:
    external: true
```

**Comment by Alkarex** [comment]
Hello,
This is not from one of our official Docker images. Ours auto-fix some of the most typical access rights issues.
The linuxserver images uses other paths / conventions / approaches, which I am not familiar with.

**Comment by Alkarex** [comment]
Closing here because most likely not related to our code / distributions, but feel free to add more information if anything relevant emerges

**Comment by dxman** [comment]
OK, thanks for confirming. I'll report over on the LinuxServer repo.
