### ISSUE TITLE
[Bug] `make fix-all` and `make test-all` are broken

### ISSUE THREAD

**Issue by mtalexan** [FreshRSS/FreshRSS#6912]
### Describe the bug

Running `make fix-all` or `make test-all` in a VSCode devcontainer tries to symlink in php files from outside the repo that don't exist, and is missing the `bin/composer` dependency on some of the targets that call it.

### To Reproduce

1. Open the `edge` branch
2. Enter the devcontainer
3. Run either `make fix-all` or `make test-all`
4. See the build errors

### Expected behavior

It completes the build successfully

### FreshRSS version

1.25.1-dev (current edge)

### Environment information

- Database version: N/A
- PHP version: N/A
- Installation type: N/A
- Web server type: N/A
- Device: N/A
- OS: N/A
- Browser: N/A

**Comment by mtalexan** [comment]
I found the issues during the fixing and testing of https://github.com/FreshRSS/FreshRSS/pull/6886, and pulled it out into it's own Bug + PR here as requested.

**Comment by Alkarex** [comment]
P.S. No need to open an issue if you have a PR coming immediately :-)

**Comment by mtalexan** [comment]
> P.S. No need to open an issue if you have a PR coming immediately :-)

Good to know, thanks. Some projects want an Issue with every PR, so I did it just to be safe.

**Comment by Frenzie** [comment]
> P.S. No need to open an issue if you have a PR coming immediately :-)

To be fair sometimes you open an issue and then proceed to fix it. (Though I doubt it could've been done in a mere two minutes.)
