### ISSUE TITLE
[Bug] Issue with updating favicon when website changes

### ISSUE THREAD

**Issue by nfriedly** [FreshRSS/FreshRSS#6927]
### Describe the bug

This isn't a big deal, but I noticed my employer's RSS feed had a GitHub favicon, and it turned out to be because they hadn't specified the website URL, so it was defaulting to the github page of the library that generated the feed.

I pointed it out and they fixed it, but then it took me a bunch of trial and error to get FreshRSS to update to the new icon. 

I tried refreshing the feed and clearing the cache, but then I noticed that the Website URL field in FreshRSS still had the old value. So I manually corrected that and then cleared the cache and refreshed again, but the icon *still* didn't update. Finally, on a whim, I added a `?` to the end of the Feed URL and was moderately surprised to see that fixed the issue. 

Even more surprising, when I took the `?` away, it went back to the old favicon, even though nothing in the feed or settings would now point to it. 

So, I'm guessing this is some kind of caching issue? Like maybe the icon is pulled from the Website URL, then cached with the key based on the Feed URL?

### To Reproduce

1. Create an RSS feed with a website that has one favicon, add it to FreshRSS
2. Edit the feed to point to a new website with a new favicon
3. Update FreshRSS settings to also know about the new website
4. Observe that the icon does not change
5. Make an inconsequential change to the Feed URL in FreshRSS, such as adding a `?` to the URL
6. Observe that the icon now changes
7. Revert step 5
8. Observe that the icon also reverts

### Expected behavior

I'd expect the icon to be solely tied to the Website URL and for the Feed URL to have no effect on it when the Website URL is set.

(I'd also prefer to see the website url updated automatically, but that's somewhat beside the point.)

### FreshRSS version

1.24.3

### Environment information

- Database version: SQLite (I think. It doesn't seem to say anywhere in the settings?)
- PHP version: 8.3.12
- Installation type: lscr.io/linuxserver/freshrss Docker
- Web server type: Headers say `server: openresty`, but the logs mention a couple of nginx config files, so I'm not sure. Maybe both? It's whatever comes with the docker image. I also have Nginx Proxy Manager in front of it, handling SSL and port mapping.
- Device: Macbook pro
- OS: Unraid (Slackware Linux)
- Browser: Firefox 131.0.2

**Comment by Frenzie** [comment]
You can delete it from `./FreshRSS/data/favicons/` to force an update. It'll be updated eventually by itself, but I don't recall how often otoh.

**Comment by nfriedly** [comment]
> You can delete it from ./FreshRSS/data/favicons/ to force an update. It'll be updated eventually by itself, but I don't recall how often otoh.

That's good to know. Perhaps the Clear cache button in the feed settings should also delete the favicon, then?

**Comment by Frenzie** [comment]
Perhaps. ;-)
