### ISSUE TITLE
Bug d'affichage dans la vue globale

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#695]
Dans la lightbox de la vue globale plus rien ne s'affiche depuis la dernière maj. Testé avec divers thèmes, toujours le même vide...

**Comment by ClementNX** [comment]
J'ai mis à jour avec la dernière version béta, et certains flux donne toujours une page blanche, ainsi que les favoris sur Firefox (version à jour, en navigation privée). Cependant, aucun problème sous Chromium.

**Comment by Alkarex** [comment]
@X3Ndotfr Pourrais-je avoir un exemple de flux problématique? Éventuellement le code source de la page planche (s'il n'est pas vide), et éventuellement une copie de la console d'erreur du navigateur.

**Comment by ClementNX** [comment]
La console : 
FreshRSS immediate init…
FreshRSS init done.

Le code HTML de la page : http://pastebin.com/fRfJxD52

Le flux : https://korben.info/feed

**Comment by Alkarex** [comment]
@X3Ndotfr Je n'arrive pas à reproduire le problème avec ce flux. Semble similaire à https://github.com/FreshRSS/FreshRSS/issues/495 Le code HTML que vous m'avez donné est celui d'une page de login à FreshRSS ; pourriez-vous réessayer ? Vérifiez que vous n'utilisez pas la fonction "sélecteur CSS" pour ce flux (dans les réglages du flux, section "Avancé").

**Comment by ClementNX** [comment]
Yep c'est la même issue, désolé ^^.
Pas de sélecteur CSS pour ce flux.
Effectivement un Ctrl+U donne toujours la page de login, j'ai fais un Ctrl+S pour récupérer ça : http://pastebin.com/NwEj7CWy

**Comment by Alkarex** [comment]
Effectivement, il manque la section des articles... Il doit certainement y avoir une erreur PHP. Pourriez-vous mettre `'environment' => 'development',` (pas une nouvelle ligne, mais changer la ligne `environment` existante) dans `./data/config.php` et ensuite regarder les logs FreshRSS (en particulier `./data/users/votre-utilisateur/log.txt`) ainsi que les logs de votre serveur Web ?

**Comment by ClementNX** [comment]
J'ai une 60ène de ligne avec ça (en une fois) : 
[Sat, 06 Jun 2015 00:44:42 +0200] [warning] --- simplepie_syslog_enabled does not exist in configuration

**Comment by Alkarex** [comment]
@X3Ndotfr Pour le `simplepie_syslog_enabled`, une mise à jour n'a pas dû être bien faite. Ajouter la ligne suivante dans `data/config.php` (voir modèle dans `./data/config.default.php`):

``` php
'simplepie_syslog_enabled' => true,
```

Mais ce n'est pas la cause de votre problème. Rien d'autre dans les logs de FreshRSS ou du serveur Web après avoir activé le mode `development` ?

**Comment by ClementNX** [comment]
Rien dans les logs de FreshRSS et rien d'intéressant dans mon serveur web :/.

J'ai l'impression que ça vient de mon navigateur, mais rien de plus précis que ça.
