### ISSUE TITLE
All feeds no longer resolve hostnames after updating to 1.24.3 on docker

### ISSUE THREAD

**Issue by binarydad** [FreshRSS/FreshRSS#6951]
### Describe the bug

I noticed after updating to this version, I get the error logs below. 

![image](https://github.com/user-attachments/assets/7c146dd3-1b7c-489c-ad58-c213feca4b8d)

I can ping the hosts fine when I shell into the container. 

![image](https://github.com/user-attachments/assets/866a6889-b1eb-48f0-a7f0-44d01dce0de0)

### To Reproduce

Here is my deployment script, which has worked for a long while now. The DNS servers are internal and used by many other containers on the network. 

```shell
sudo docker pull lscr.io/linuxserver/freshrss:latest
sudo docker container stop freshrss
sudo docker container rm freshrss

sudo docker run -d \
    --name freshrss \
    --dns 192.168.1.130 --dns 192.168.1.131 \
    -e PUID=1000 \
    -e PGID=1000 \
    -e TZ=America/New_York \
    -l 'traefik.http.routers.freshrss.rule=Host(`rss.binarydad.com`)' \
    -v /sites/freshrss:/config \
    --restart unless-stopped \
    lscr.io/linuxserver/freshrss:latest
```

### FreshRSS version

1.24.3

### Environment information

This is running on Ubuntu 24 (latest patches) and Docker 27.3.1, build ce12230.

**Comment by Alkarex** [comment]
Hello,
This seems to be a LinuxServer Docker image, and not one of [our official images](https://hub.docker.com/r/freshrss/freshrss/).
In any case, the most probable is that it is unrelated to FreshRSS but due to a wrong Docker networking settings or state. In particular, I see some fishy `--dns` parameters.

**Comment by Alkarex** [comment]
You are welcome to post additional information when you have done a bit more debugging.
By the way, sometimes the Docker networks can benefit from a full restart of Docker and/or the machine
