### ISSUE TITLE
Liste de catégorie longue = scroll impossible à cause du loading des articles

### ISSUE THREAD

**Issue by Draky50110** [FreshRSS/FreshRSS#697]
Salut

J'ai un souci sur la version de dév.

J'ai une grosse liste de catégorie.
J'affiche 50 non lus et quand je scrolle en bas de la liste des flux non lus, logiquement, il se met à charger la suite.

Sauf que si je veux scroller la page pour atteindre le bas de la liste des catégories... bahje ne peux pas l'atteindre ou cliquer sur une catégorie du bas car il se met à charger la liste des flux (lus ou non lus).

Seule solution : cliquer sur une catégorie avec - de 50 flux affichés non lus, comme ça le scroll vers la fin de la liste des catégorie ne déclenche pas le chargement de flux supplémentaires.

Je ne sais pas si c'est clair mais c'est embêtant :-(

**Comment by marienfressinaud** [comment]
Corrigé. La marche à suivre : 
- Mettre à jour FRSS ce qui aura pour effet de supprimer l'effet "sticky".
- Récupérer l'extension StickyFeeds dans https://github.com/FreshRSS/Extensions et l'uploader dans le répertoire `./extensions`
- Activer l'extension dans l'interface utilisateur.

**Comment by Alwaysin** [comment]
Le comportement est assez bizarre quand même :/

**Comment by marienfressinaud** [comment]
Ah ? Normalement c'est le même avec juste une barre de scroll en plus…

**Comment by Draky50110** [comment]
Bon, c'est bizarre parce que la barre de scroll n'est pas présente en permanence.
C'est possible de l'avoir en permanence ? Histoire de pouvoir remonter en haut de la liste des catégories tout en étant plus bas dans la liste des flux ? D
[/mode chieur off]
Sinon ça marche ;)

**Comment by marienfressinaud** [comment]
Ah tu veux dire qu'elle n'est pas là lorsque tu n'as pas scrollé ou pas suffisamment pour que le bouton "Flux principal" se trouve en haut ?

**Comment by Draky50110** [comment]
Je préfèrerais qu'elle soit toujours là, que j'ai scrollé les flux vers le bas ou non.

**Comment by marienfressinaud** [comment]
Oui oui je comprends, c'est juste que je n'avais pas fait attention à ce cas-là, je corrigerai.

**Comment by marienfressinaud** [comment]
Normalement c'est bon maintenant. La mise à jour des extensions se fait à la main par contre et il n'y aura pas de système pour mettre à jour automatiquement (sauf en passant par Git). La solution pour corriger cette histoire de barre de défilement était plus embêtant que prévu mais d'un point de vue utilisateur ça ne devrait pas trop se faire ressentir ;).

**Comment by Draky50110** [comment]
C'est bon pour la barre de scroll, par contre quand je vais dans une catégorie, y'a un GROS souci à l'affichage :D 
Screen : https://imgur.com/tC7wZaD

**Comment by marienfressinaud** [comment]
Ça ne te le fait que en sélectionnant une catégorie ? Je n'arrive pas à reproduire le problème même si je sais où il se situe. Ce truc me prend la tête depuis le début ><

**Comment by Alwaysin** [comment]
Ca me le fait aussi, quand je déroule une catégorie seulement.

**Comment by Draky50110** [comment]
Comme @Alwaysin : seulement quand on déroule/sélectionne une catégorie, que les flux soit non-lus ou lus.

**Comment by marienfressinaud** [comment]
La conversation continue sur #753
