### ISSUE TITLE
[Feature] Redirect to shortcut page on pressing '?' (or show shortcut info)

### ISSUE THREAD

**Issue by AbelLykens** [FreshRSS/FreshRSS#6975]
**Is your feature request related to a problem? Please describe.**
Using shortcuts is useful and nice. But remembering them is not easy. 

**Describe the solution you’d like**
In other web apps I am used to a popup/information about shortcuts when pressing `?`. 
It would be very useful if a `?` press would either (1) show a popup with shortcuts or (2) redirect to the shortcuts page.

**Describe alternatives you’ve considered**
Of course I can navigate to the shortcut page using the mouse. But who uses the mouse these days... 😜

**Additional context**
Many other (web) apps support the `?` button. Intuitively I tried it on FreshRSS too, but no luck 😊.

**Comment by math-GH** [comment]
I have this also in my back head. Good to know that someone else wants to have it too :)

**Comment by oshaposhnyk** [comment]
@Alkarex Hi, can I take the issue?

**Comment by Alkarex** [comment]
> can I take the issue?

@oshaposhnyk Sure, go ahead 👍🏻

**Comment by AbelLykens** [comment]
Nice work!!
