### ISSUE TITLE
Impossible de rajouter un flux valide

### ISSUE THREAD

**Issue by Humfred** [FreshRSS/FreshRSS#698]
Salut.
Ce flux ne peut pas être rajouté à FreshRSS : http://webseriesmag.blogs.liberation.fr/we/atom.xml alors qu'il est valide : http://validator.w3.org/feed/check.cgi?url=http%3A//webseriesmag.blogs.liberation.fr/we/atom.xml

Le log indique:
"A feed could not be found at http://webseriesmag.blogs.liberation.fr/we/atom.xml. A feed with an invalid mime type may fall victim to this error, or SimplePie was unable to auto-discover it.. Use force_feed() if you are certain this URL is a real feed. [http://webseriesmag.blogs.liberation.fr/we/atom.xml]"

**Comment by aledeg** [comment]
Est ce que ce problème est encore d'actualité? Si oui, merci de le mettre à jour et de nous donner des informations complémentaires. Si non, il faudrait le cloturer.

**Comment by Humfred** [comment]
J'avais oublié ce pb avec ce flux...
Je viens de réessayer avec FreshRSS 1.1.0 et il n'y a plus de problème: ce flux est valide maintenant.

**Comment by aledeg** [comment]
Parfait, je cloture dans ce cas.

**Comment by Alkarex** [comment]
https://github.com/simplepie/simplepie/pull/402
