### ISSUE TITLE
[Feed problem] repology with `@` symbol as parameter

### ISSUE THREAD

**Issue by Stunkymonkey** [FreshRSS/FreshRSS#6987]
### Feed URL

https://repology.org/maintainer/account@buehler.rocks/feed-for-repo/nix_unstable/atom

### Describe the problem

unable to use this feed

shows: `Blast! This feed has encountered a problem. Please verify that it is always reachable then update it.`

### Log messages

```
⚠️		2024-11-10 11:10:23 	cURL error 35: OpenSSL/1.0.2k-fips: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version [https://repology.org/maintainer/account%40buehler.rocks/feed-for-repo/nix_unstable/atom]
⚠️		2024-11-10 10:10:24 	cURL error 35: OpenSSL/1.0.2k-fips: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version [https://repology.org/maintainer/account%40buehler.rocks/feed-for-repo/nix_unstable/atom]
⚠️		2024-11-10 09:00:35 	cURL error 35: OpenSSL/1.0.2k-fips: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version [https://repology.org/maintainer/account%40buehler.rocks/feed-for-repo/nix_unstable/atom]
⚠️		2024-11-10 08:20:25 	cURL error 35: OpenSSL/1.0.2k-fips: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version [https://repology.org/maintainer/account%40buehler.rocks/feed-for-repo/nix_unstable/atom]
```

### W3C Validator

works: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Frepology.org%2Fmaintainer%2Faccount%40buehler.rocks%2Ffeed-for-repo%2Fnix_unstable%2Fatom

does not work: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Frepology.org%2Fmaintainer%2Faccount%2540buehler.rocks%2Ffeed-for-repo%2Fnix_unstable%2Fatom

### FreshRSS version

1.24.3

### Environment information

- Database version: MariaDB 10.6.19
- PHP version: PHP 8.2
- Installation type: git
- Web server type: Apache
- Device: Lenovo Laptop
- OS: CenOS 8
- Browser: Firefox 132

### Additional context

one time the `@` symbol is `%40` (works) and one time `%2540` (does not work)

**Comment by Frenzie** [comment]
Does it work for you if you run something like this from the server?
```
curl -A "FreshRSS/1.24.3 (Linux; https://freshrss.org)" "https://repology.org/maintainer/account@buehler.rocks/feed-for-repo/nix_unstable/atom"
```

**Comment by Frenzie** [comment]
Also I forgot about it while I wrote that, but you may be able to work around it under advanced:
![image](https://github.com/user-attachments/assets/1b00cee3-6a3f-401f-8ca0-7ed160ed0eb1)

**Comment by Stunkymonkey** [comment]
> `curl -A "FreshRSS/1.24.3 (Linux; https://freshrss.org)" "https://repology.org/maintainer/account@buehler.rocks/feed-for-repo/nix_unstable/atom"`

on my server:

```bash
 $ curl -A "FreshRSS/1.24.3 (Linux; https://freshrss.org)" "https://repology.org/maintainer/account@buehler.rocks/feed-for-repo/nix_unstable/atom"
curl: (35) OpenSSL/1.0.2k-fips: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
$ curl --version
curl 8.9.1 (x86_64-pc-linux-gnu) libcurl/8.9.1 OpenSSL/1.0.2k-fips zlib/1.2.7 brotli/1.0.9 libidn2/2.3.7 libpsl/0.7.0 (+libicu/50.1.2) libssh2/1.10.0 nghttp2/1.33.0 OpenLDAP/2.4.44
Release-Date: 2024-07-31
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns ldap ldaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTPS-proxy IDN IPv6 Largefile libz NTLM PSL SSL threadsafe UnixSockets
```

<details><summary>on my laptop:</summary>

```bash
$ curl -A "FreshRSS/1.24.3 (Linux; https://freshrss.org)" "https://repology.org/maintainer/account@buehler.rocks/feed-for-repo/nix_unstable/atom"
<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
	<title>Repology feed for account@buehler.rocks</title>
	<icon>/static/repology40x40.v1.png</icon>
	<link href="https://repology.org/maintainer/account@buehler.rocks/feed-for-repo/nix_unstable/atom" rel="self" type="application/atom+xml" />
	<link href="https://repology.org/maintainer/account@buehler.rocks/feed-for-repo/nix_unstable" rel="alternate" type="text/html" />
	<author><name>Repology</name><uri>https://repology.org/</uri></author>
	<id>tag:repology.org,2018-04-25:maintainer-repo:account@buehler.rocks:nix_unstable</id>
	<updated>2024-10-15T16:07:44+00:00</updated>
	<entry>
		<id>tag:repology.org,2018-04-25:maintainer-repo:account@buehler.rocks:nix_unstable:27531251</id>
		<updated>2024-10-15T16:07:44+00:00</updated>
		<link href="https://repology.org/project/mediaelch/versions#nix_unstable" />
		<title>mediaelch 2.12.0 is up to date</title>
		<content>Package mediaelch version 2.12.0 in nixpkgs unstable is up to date</content>
		<category term="uptodate" label="Package is up to date" />
	</entry>
	<entry>
		<id>tag:repology.org,2018-04-25:maintainer-repo:account@buehler.rocks:nix_unstable:27516154</id>
		<updated>2024-10-13T17:44:13+00:00</updated>
		<link href="https://repology.org/project/mediaelch/versions#nix_unstable" />
		<title>mediaelch 2.10.6 is outdated by 2.12.0</title>
		<content>Package mediaelch version 2.10.6 in nixpkgs unstable is outdated by 2.12.0</content>
		<category term="outdated" label="Package is outdated" />
	</entry>
$ curl --version
curl 8.7.1 (x86_64-pc-linux-gnu) libcurl/8.7.1 OpenSSL/3.0.14 zlib/1.3.1 brotli/1.1.0 zstd/1.5.6 libidn2/2.3.7 libpsl/0.21.5 libssh2/1.11.0 nghttp2/1.61.0
Release-Date: 2024-03-27
Protocols: dict file ftp ftps gopher gophers http https imap imaps ipfs ipns mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM PSL SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd
```
</details>

**Comment by Stunkymonkey** [comment]
> Also I forgot about it while I wrote that, but you may be able to work around it under advanced: ![image](https://private-user-images.githubusercontent.com/202757/384686846-1b00cee3-6a3f-401f-8ca0-7ed160ed0eb1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNTU5NjgsIm5iZiI6MTczMTI1NTY2OCwicGF0aCI6Ii8yMDI3NTcvMzg0Njg2ODQ2LTFiMDBjZWUzLTZhM2YtNDAxZi04Y2EwLTdlZDE2MGVkMGViMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQxNjIxMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYWQwMzZhMWYyNjJkYjRjOWZlMjY2ZTdlMDNmOTc1MDVlNWNjNzVkNzAzMzE0NzI1NTQ2NGI2NjNhYWQwOWEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WV_rlSuQf1gHjUYEoODe9dNwxHG9ClvQB0ZuMM2fs0A)

sadly the same result.

It is a public feed. So maybe you can test it as well.

**Comment by Stunkymonkey** [comment]
is `curl` my problem?

**Comment by Frenzie** [comment]
I figure it's more likely to be related to OpenSSL, but there are some other things you could potentially try like `curl --tlsv1.2 etc.` (also `--tlsv1.3`)

**Comment by Stunkymonkey** [comment]
sadly does not help.

with tls1.3:
```
curl: (4) OpenSSL was built without TLS 1.3 support
```

so i guess CentOS 8 with a openssl from 2017 is broken...

I am closing. Not something that can/should be fixed in freshrss.

@Frenzie thanks for your help

**Comment by Frenzie** [comment]
According to https://en.m.wikipedia.org/wiki/Transport_Layer_Security 1.3 dates from 2018.
