### ISSUE TITLE
Afficher le n° de version proposé en mise à jour

### ISSUE THREAD

**Issue by Vincent14** [FreshRSS/FreshRSS#699]
Hello,

Sur la page /i/?c=update il serait cool de rappeler le n° de version présentement installée et d'afficher la version disponible à l'update

**Comment by marienfressinaud** [comment]
Quelques trucs que je vais faire : 
- [x] Afficher le numéro de version actuel
- [ ] Lors de la récupération du fichier de mise à jour, stocker le fichier entier (dont la première ligne qui renseigne sur le numéro de version qui met à jour et qui n'est actuellement pas gardé)
- [ ] Lors de l'exécution, séparer la première ligne du reste vu qu'elle est génante pour l'exécution.
- [ ] Et bien sûr, si le fichier data/update.php est présent, récupérer la première ligne, trouver le numéro de version et l'afficher ;)

**Comment by marienfressinaud** [comment]
J'ai fait plus simple en fait : j'ai gardé le comportement précédent mais seulement j'ai sauvegardé le numéro de version dans le fichier `data/last_update.txt` qui était déjà utilisé pour sauvegarder la date de dernière mise à jour. Cette date est maintenant récupéré par la date de dernière modification du fichier (fonction `filemtime()`).

Ça devrait s'afficher désormais (version de dev évidemment pour le moment).
