### ISSUE TITLE
[Feed problem] Blurry images loading from feed

### ISSUE THREAD

**Issue by johansvedberg** [FreshRSS/FreshRSS#6993]
### Feed URL

https://fridalund.elle.se/feed/

### Describe the problem

I'm trying to use a couple of feeds from the Elle Sweden, where the images looks like this:
```
<figure class="image">
    <picture
        ><source
            media="(max-width: 767px)"
            type="image/webp"
            data-srcset="https://files-aller-blogger-platform.aws.aller.com/uploads/sites/37/2024/11/IMG_0894_2.PNG?w=430&fit=max&fm=webp 1x, https://files-aller-blogger-platform.aws.aller.com/uploads/sites/37/2024/11/IMG_0894_2.PNG?w=430&fit=max&fm=webp&dpr=2 2x" />
        <source
            media="(max-width: 767px)"
            type="image/jpg"
            data-srcset="https://files-aller-blogger-platform.aws.aller.com/uploads/sites/37/2024/11/IMG_0894_2.PNG?w=430&fit=max&fm=jpg&dpr=2 1x, https://files-aller-blogger-platform.aws.aller.com/uploads/sites/37/2024/11/IMG_0894_2.PNG?w=430&fit=max&fm=jpg&dpr=2 2x" />
        <source
            media="(min-width: 768px) and (max-width: 991px)"
            type="image/webp"
            data-srcset="https://files-aller-blogger-platform.aws.aller.com/uploads/sites/37/2024/11/IMG_0894_2.PNG?w=696&fit=max&fm=webp 1x, https://files-aller-blogger-platform.aws.aller.com/uploads/sites/37/2024/11/IMG_0894_2.PNG?w=696&fit=max&fm=webp&dpr=2 2x" />
        <source
            media="(min-width: 768px) and (max-width: 991px)"
            type="image/jpg"
            data-srcset="https://files-aller-blogger-platform.aws.aller.com/uploads/sites/37/2024/11/IMG_0894_2.PNG?w=696&fit=max&fm=jpg&dpr=2 1x, https://files-aller-blogger-platform.aws.aller.com/uploads/sites/37/2024/11/IMG_0894_2.PNG?w=696&fit=max&fm=jpg&dpr=2 2x" />
        <source
            media="(min-width: 992px)"
            type="image/webp"
            data-srcset="https://files-aller-blogger-platform.aws.aller.com/uploads/sites/37/2024/11/IMG_0894_2.PNG?w=850&fit=max&fm=webp 1x, https://files-aller-blogger-platform.aws.aller.com/uploads/sites/37/2024/11/IMG_0894_2.PNG?w=850&fit=max&fm=webp&dpr=2 2x" />
        <source
            media="(min-width: 992px)"
            type="image/jpg"
            data-srcset="https://files-aller-blogger-platform.aws.aller.com/uploads/sites/37/2024/11/IMG_0894_2.PNG?w=850&fit=max&fm=jpg&dpr=2 1x, https://files-aller-blogger-platform.aws.aller.com/uploads/sites/37/2024/11/IMG_0894_2.PNG?w=850&fit=max&fm=jpg&dpr=2 2x" />
        <img
            src="https://files-aller-blogger-platform.aws.aller.com/uploads/sites/37/2024/11/IMG_0894_2.PNG?w=850&fit=max&auto=format&px=16&blur=100&q=0&colorquant=16"
            data-src="https://files-aller-blogger-platform.aws.aller.com/uploads/sites/37/2024/11/IMG_0894_2.PNG?w=850&fit=max&auto=format 1x"
            width="850"
            class="lazyload"
    /></picture>
</figure>
```
FreshRSS uses the last image (b/c of no screen-resolution maybe?) - which leads to images that look like this:

<img width="702" alt="Screenshot 2024-11-12 at 19 36 57" src="https://github.com/user-attachments/assets/6a7c7f3f-e549-4a31-97a9-e95dc732a124">

I'm guessing those are supposed to be holder while loading or something along those lines, but it makes the feeds unusable. 

Has anybody encountered a problem like this before, and is there a way to configure around the issue?

Thanks!

### Log messages

Nothing

### W3C Validator

https://validator.w3.org/feed/check.cgi?url=https://fridalund.elle.se/feed/

Nothing out of the ordinary.

### FreshRSS version

1.24.3

### Environment information

Database version: [e.g. Mysql 5.7, SQLite]
- PHP version: 8.2.20
- Installation type: PikaPods
- Device: Macbook M1Pro
- OS: MacOS15.1
- Browser: Arc 1.69.0 (55716)-RC

**Comment by Frenzie** [comment]
See https://github.com/FreshRSS/FreshRSS/issues/3823#issuecomment-913041986 for something similar. `data-anything` is only meant for use with JS; it's meaningless in principle. But the workaround from https://github.com/FreshRSS/FreshRSS/pull/3805/files#diff-318f03d8ac66816058c42f26b8ed4c5ff71306b6250d7096ad25e0a15813e8efR89 makes a lot of sense for this scenario too I'd say.

**Comment by johansvedberg** [comment]
Different frontends render the images differently - found one that works like I expected here.

https://readkit.app/
