### ISSUE TITLE
Connnexion en GET cassée

### ISSUE THREAD

**Issue by Vincent14** [FreshRSS/FreshRSS#700]
En 0.8.1, j'utilise l'accès via l'URL /i/?a=formLogin&u=login&p=password et ça ne marche plus :'(

**Comment by Vincent14** [comment]
J'ai posé le log de la ligne 158 à la ligne 161 (il y avait une ligne vide)

[Sat, 03 Jan 2015 16:35:21 +0100] [debug] --- Entrée dans loginAction
[Sat, 03 Jan 2015 16:35:21 +0100] [debug] --- Entrée dans formLoginAction
[Sat, 03 Jan 2015 16:35:21 +0100] [debug] --- Entrée dans le système unsafeAutoLogin
[Sat, 03 Jan 2015 16:35:21 +0100] [debug] --- Vérification mot de passe : 1

Edit : le login est réparé sous Firefox desktop mais toujours cassé sur mobile ainsi que dans Chromium desktop

**Comment by marienfressinaud** [comment]
Ok donc tout ce qui est vérification est ok. Le problème vient plus probablement du `giveAccess` après. Je regarderai ça plus tard.

**Comment by Vincent14** [comment]
OK, de toute façon cet aprem ça marche plus non plus sous Firefox Desktop -_-"

**Comment by marienfressinaud** [comment]
Il est possible que j'ai détecté le bug. Je vais le corriger dans la branche sur laquelle je bosse actuellement car j'y ai changé tant de chose que le merge risque d'être pénible. J'espère la merger d'ici demain ou après-demain ;)

**Comment by marienfressinaud** [comment]
Je me suis peut-être fourvoyé. M'enfin on verra ;).

**Comment by Vincent14** [comment]
I notice that :)

**Comment by marienfressinaud** [comment]
S'il t'est possible de tester la version de dev, possible que le bug soit désormais corrigé mais je ne peux pas en être certain…

**Comment by Vincent14** [comment]
Je suis en 0.9.3, je n'ai pas de MAJ proposée, je passe par une réinstall comme la dernière fois ? :)

**Comment by marienfressinaud** [comment]
C'est l'idée ^^ Ça m'embête de te demander ça mais vu que tu es le seul à reproduire le bug facilement, j'ai pas le choix ;)

**Comment by Vincent14** [comment]
Non non bien au contraire je suis très content d'aider ! tu n'imagines pas à quel point ton projet me permet d'optimiser mon temps de surf dans la journée :) (je l'utilise uniquement sur mobile)

J'ai mis à jour avec https://github.com/FreshRSS/FreshRSS/tree/dev et pour l'heure j'ai une "### Fatal error! ###"

**Comment by marienfressinaud** [comment]
Arf arf oui, c'était pas une màj que tu aurais dû faire en fait (ma faute) mais une installation à côté : y a pas mal de choses qui ont changé dans le répertoire `./data` et ça risque d'être un peu pénible de le faire à la main :s

**Comment by Vincent14** [comment]
Aucun problème, j'ai restauré mon freshrss.old3/ en attendant :D

**Comment by Vincent14** [comment]
Le 15 approche j'espère qu'on aura l'occaz de patcher ça pour la 1.0 :$ 

/se fait tout petit

**Comment by marienfressinaud** [comment]
Bin je veux bien mais il faut que tu testes la version de dev si tu veux être sûr que ça soit corrigé. Moi j'ai fait des trucs dans la branche dev, ça marche en local (comme avant) mais faut voir chez toi. Sinon tu attends la version 0.9.4 jeudi.

**Comment by Vincent14** [comment]
Avec migration des données intégrée ? :D

**Comment by marienfressinaud** [comment]
Oui oui la migration des données est prévue pour la 0.9.4.

**Comment by Vincent14** [comment]
Félicitations, le bug est résolu sur tous mes navigateurs de test ! :)

**Comment by marienfressinaud** [comment]
Cool ! \o/

**Comment by Vincent14** [comment]
NON ! Bon sang c'est fou ça recommence !

**Comment by marienfressinaud** [comment]
Toujours pas de logs intéressants par hasard ?

**Comment by marienfressinaud** [comment]
"Bonne" nouvelle : j'arrive à reproduire le bug en local, je vais pouvoir bosser dessus

**Comment by marienfressinaud** [comment]
Ok j'ai à peu près repéré le bug mais il est très bizarre. Il est lié aux sessions et à leurs identifiants : 

La première fois qu'on se connecte, on a une session A. La connexion réussit, il y a un paramètre de session (loginOk) qui est mis à "true", on est content.

Là tu fermes le navigateur et tu le rouvre : tu as une session B. Cette session n'étant pas initialisée, loginOk n'est pas à true donc tu n'es pas connecté. Là arrive le bug car, lorsque tu essaye d'accéder à la page ?c=auth&login&u=username&p=password, ce n'est pas la session B qui est utilisée mais la session A qui retourne que loginOk est true (donc il considère que tu ES connecté !). Comme tu es connecté, FRSS te redirige vers la page d'index pour que tu puisses lire tes flux… sauf qu'on repasse sur la session B à ce moment là et donc tu n'es plus connecté. Tadam!

Alors comment ça se passe ? Si je ne dis pas trop de bêtises, normalement le navigateur donne l'identifiant de session à utiliser en précisant dans un en-tête COOKIE : `FreshRSS=B; […]` (B étant l'identifiant de la session). Sur toutes les pages ça marche bien à priori sauf évidemment sur la page mentionnée où le COOKIE envoyé est de la forme : `FreshRSS=A; FreshRSS=B; […]`. FRSS prend donc de son côté le premier identifiant qu'il trouve.

Là j'avoue que je sèche sur le pourquoi du comment ça se passe comme ça. Peut-être que @Alkarex a une idée de son côté sinon je chercherai plus tard ;)

**Comment by marienfressinaud** [comment]
Ça y est j'ai compris le bug ! Il était particulièrement tordu mais j'ai compris : 

Pour reproduire : 
- Bookmarker (ou copier/coller) l'adresse en ?c=auth&a=login&u=username&p=password
- S'assurer que la page de FRSS est **fermée** avant de fermer le navigateur à son tour (pour qu'il oublie les cookies de session)
- Rouvrir le navigateur et se rendre **directement** à l'adresse bookmarkée ! (surtout pas de passage par la page d'accueil)
- Un cookie de session est alors créé (nouvelle session oblige) mais UNIQUEMENT pour le chemin (= l'adresse) précisé. La connexion se passe correctement si les identifiants sont bons et on est redirigé vers la page d'accueil.
- Arrivé à la page d'accueil, le navigateur cherche un cookie de session pour le chemin précisé : il n'y en a pas et en créé donc un **deuxième** pour la page incriminée. Ce nouveau cookie n'est pas associé à une session valide donc pas connecté.
- En essayant de se reconnecter avec l'adresse bookmarkée, le premier cookie est valide donc FRSS considère que l'on est connecté.

Le problème vient du fait qu'on attribue un chemin trop précis (avec `session_set_cookie_params`) pour les cookies de session, chose que l'on a effectivement introduite il y a peu (avec le système de maintien de session en fait).

Ma question à @Alkarex du coup vu qu'il me semble que tu es plus à jour que moi là-dessus : y aurait-il des problèmes en définissant un chemin plus global (par exemple /p/i que l'on pourrait extraire soit en supprimant `index.php` de $_SERVER['SCRIPT_NAME'] soit en supprimant la query_string de l'actuel request_uri) ?

**Comment by Alkarex** [comment]
Oui, le chemin ./p/i/ me semble être le mieux

**Comment by marienfressinaud** [comment]
Corrigé. Cette fois-ci je suis sûr que le bug n'est plus là donc je ferme le ticket. Je crois que c'est le bug le plus tordu auquel j'ai eu faire jusque-là ! :)

@Vincent14 > si tu veux corriger le bug à la main en attendant la sortie de la prochaine version, c'est juste deux lignes dans le fichier `./lib/Minz/Session.php`, tu n'as que reproduire mon fix https://github.com/FreshRSS/FreshRSS/commit/eec95ffb6a414f00f0ddd6cb1f81ac7ee55d4f6b

**Comment by Vincent14** [comment]
Vous êtes l'équipe la plus ouf que j'ai jamais vu ! :D Mon calvaire prend fin \o/ MERCI ! <3 (c'est la journée du câlin il parait, vous en avez un chacun)

**Comment by Alkarex** [comment]
Merci @Vincent14 :-)

**Comment by Flaburgan** [comment]
GG les gars :D
