### ISSUE TITLE
[Feature] Extension events for post feed data fetch

### ISSUE THREAD

**Issue by pe1uca** [FreshRSS/FreshRSS#7006]
**Is your feature request related to a problem? Please describe.**
I'm trying to implement something suggested in #6556  
A `sleep` or some sort of pause to the update is a simple solution but has little to no flexibility.  
I'm thinking on processing the potential headers some sites send to improve how many feeds can be updated in a given period of time.  

**Describe the solution you’d like**
An event `feed_after_actualize` or `simplepie_after_init` which should allow me to get the headers of the request made to the feed.  

**Describe alternatives you’ve considered**
Since the extension would already be using `feed_before_actualize` to cancel the update, also could be to manually call the feed's URL to process the headers in this event.  

**Additional context**
None.

**Comment by Alkarex** [comment]
What HTTP headers would that be? We already support HTTP cache headers and conditional headers.

Quick idea: you could make an extension listening to `feed_before_actualize`, extract the domain name from the URL, and sleep a minimum amount of time since the last time the same domain was queried.

**Comment by pe1uca** [comment]
It depends on the site what header is used to give the information about how many requests remain and/or when the rate limit expires, so for better support the extension would need to read all the headers to hand pick the necessary ones.  

---   

Yes, a way to sleep is what I started with, but it's not a good solution even for my 1 user instance.   

For one site I have 120 feeds, and for another I have 30, which means the update for just my user will take 25minutes with 10 second sleep.  
(~~By default the~~ The recommended docker deploy has a 30 minutes update, but the default config of FreshRSS allows as low as 15)  
Even with 5 seconds it becomes a problem after 360 feeds or 180 if the user expects the feeds to be fetched as they configured their deployment.  
And with multi-user deployments with each user adding different feeds for the same site, as is with forums or video platforms, this can quickly overwhelm the `actualize_script`.  


One of these sites uses `x-ratelimit-remaining` and `x-ratelimit-reset` which could be used to improve this behavior.  
Right now it seems it allows 100 request every 10 minutes, so for this single site we can get 300 updates without blocking other sites. (This might require changing the cron configuration tho)  
For other sites they might use the more standard header [Retry-After](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After) or any other custom one which might allow more requests or even less for that specific site.  

---  

Reading the headers after a request might also allow to prevent the HTTP code `429` (or any other depending on the site) for any further feed, and being muted by FreshRSS.  
Right now I have several with the message `Blast! This feed has encountered a problem. Please verify that it is always reachable then update it.`, and based on the logs and the DB seems they haven't been automatically retried since the log shows a 429.

**Comment by pe1uca** [comment]
I'm currently progressing in implementing a custom rate limit instead of a shift/sleep for the updates.  

One potential optimization when having an "after update" event is also I'm right now counting every feed update towards the limit, but I see in the logs this message: `SimplePie MD5 cache match for <feed>`.  
So if I can also check if the update was made from cache instead of the actual request the extension can squeeze a bit more requests in multi-user instances (depending on how FreshRSS handles having the same feed for more than one user).

**Comment by Alkarex** [comment]
I will add such a hook.
By the way, if you work on a new extension, check for instance https://github.com/Joedmin/xExtension-wallabag-button/pull/1 on how to ensure code compatibility with FreshRSS thanks to automated tests

**Comment by Alkarex** [comment]
@pe1uca Check https://github.com/FreshRSS/FreshRSS/pull/7007
