### ISSUE TITLE
[Bug] Some feeds say "encounter a problem"

### ISSUE THREAD

**Issue by nilsbeck** [FreshRSS/FreshRSS#7010]
### Describe the bug

I have seen it with several feeds that they cannot be updated because "a problem was encountered". I will center on one specific example that shows this.

this is the feed: http://valenciasecreta.com/feed/

the error message that shows is: "Blast! This feed has encountered a problem. Please verify that it is always reachable then update it."

Why do I believe there is something not right?
- the feed has worked flawlessly with feedly for me in the past for years
- when I add the url as feed there is a "check validity of the feed" button. this button lets w3 validate the feed. and it says it is a valid rss feed (though with some recommendations)
- it does not seem to be general availability or server problem. I can _always_ download the feed without problems, and I can _never_ add it to freshrss 

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

### Expected behavior

The feed should update and read the articles.

### FreshRSS version

1.24.3 

### Environment information

- Database version: SQLite
- PHP version: 8.2.20
- Installation type: Docker
-Web server type: Apache
- Device: Mac M1
- OS: MacOS 15.1
- Browser: Firefox 132.0.1 

### Additional context

Other feeds do work on my setup, like engadget.com and more. But then there are many that do not work like the one mentioned.

It seems to me that the error message is at least misleading and for some reason the "wrong" message is returned.

**Comment by Frenzie** [comment]
It's Cloudfront. See e.g. https://github.com/FreshRSS/FreshRSS/issues/6533#issuecomment-2145762885 (Cloudflare is a competitor to Cloudfront, but the effect is likely the same.)

```
$ curl --verbose http://valenciasecreta.com/feed/
*   Trying 18.239.83.91:80...
* Connected to valenciasecreta.com (18.239.83.91) port 80 (#0)
> GET /feed/ HTTP/1.1
> Host: valenciasecreta.com
> User-Agent: curl/7.88.1
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Server: CloudFront
< Date: Wed, 20 Nov 2024 20:54:01 GMT
< Content-Type: text/html
< Content-Length: 167
< Connection: keep-alive
< Location: https://valenciasecreta.com/feed/
< X-Cache: Redirect from cloudfront
< Via: 1.1 97f993f9d41d16f3f36b8c466857e2d6.cloudfront.net (CloudFront)
< X-Amz-Cf-Pop: AMS58-P5
< Alt-Svc: h3=":443"; ma=86400
< X-Amz-Cf-Id: 8j8W84cwdKBlBwAbuBVUeM8y4ywfmIGs3kSZScCHrxU6dPK_oMk-vQ==
< 
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>CloudFront</center>
</body>
</html>
* Connection #0 to host valenciasecreta.com left intact
```

**Comment by Alkarex** [comment]
You can try to go through https://feedburner.google.com or another proxy

**Comment by Alkarex** [comment]
P.S. https://valenciasecreta.com/feed/ works fine in my FreshRSS, but as Frenzie wrote, it might depend on e.g. your IP.
You can try to run from your server:

```sh
curl -v 'https://valenciasecreta.com/feed/'
```

**Comment by nilsbeck** [comment]
Thank you all for the very fast responses. And sorry for declaring this a bug, had not seen the `Feed problem` tag.
I will try and see what I can do to get around this....For me this would be enough to close since it is not directly related to FreshRSS. Unless you want to keep it open to improve the error message maybe? If there is a somewhat reliable way to detect this by reading the headers?

**Comment by Frenzie** [comment]
> P.S. https://valenciasecreta.com/feed/ works fine in my FreshRSS

Same for me, but if such a system decides there's something suspicious it can turn around quickly.

**Comment by Alkarex** [comment]
This feed seems to work through https://feedburner.google.com/ (just click on *add proxy*) so that is probably the easiest for you now, besides changing IP or contacting the Web master to make them modify their feed settings.
