### ISSUE TITLE
[Bug] Unable to Retrieve All Feed Items

### ISSUE THREAD

**Issue by LinxHex** [FreshRSS/FreshRSS#7012]
### Describe the bug

When I added this feed:
https://rsshub.pseudoyu.com/xiaohongshu/user/6552fa8600000000020352e3/notes

I noticed that FreshRSS only retrieves the last (bottom-most) item in the feed. However, other RSS readers do not have this issue. Could you please help me resolve this problem? Thank you.

### To Reproduce

1. Add the feed URL: https://rsshub.pseudoyu.com/xiaohongshu/user/6552fa8600000000020352e3/notes to FreshRSS.
2. Open the newly added feed in FreshRSS.
3. Check the list of retrieved items.
4. Observe that only the last (bottom-most) item is displayed.
![image](https://github.com/user-attachments/assets/671cedfa-a7bb-494d-8b80-f4a673b44e49)

### Expected behavior

FreshRSS should retrieve and display all feed items from the provided feed URL, similar to how other RSS readers handle it.

### FreshRSS version

1.24.3

### Environment information

- PHP version: 8.2.20
- Installation type: Docker
- Web server type: nginx
- Device: Windows
- OS: Win11
- Browser: Chrome 130

**Comment by Frenzie** [comment]
I can't confirm. Could it be they've already been read?
![image](https://github.com/user-attachments/assets/a4d391fb-9cdb-4414-95a0-37910734ca49)

**Comment by LinxHex** [comment]
> I can't confirm. Could it be they've already been read? ![image](https://private-user-images.githubusercontent.com/202757/388426741-a4d391fb-9cdb-4414-95a0-37910734ca49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxNzk4MjUsIm5iZiI6MTczMjE3OTUyNSwicGF0aCI6Ii8yMDI3NTcvMzg4NDI2NzQxLWE0ZDM5MWZiLTljZGItNDQxNC05NWEwLTM3OTEwNzM0Y2E0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMVQwODU4NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Y2JjMGNhZWEzOWVlNGIzMDFjNDliY2FjYTQzOTRlMGVmZDk0MTM3NzQ3Y2ZiNTkzYTMxMWIyY2IyZGZhMDc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QOuXsmLoWj7NFMjjiTTcnyUHUDHlZZnYdfOyc7gD6IQ)

This is really strange. When I add the feed, only one item is retrieved, and I’m certain that there is only one item in total, combining both unread and read entries.

However, I noticed the following log entry:
Feed has valid GUIDs again: https://rsshub.pseudoyu.com/xiaohongshu/user/6552fa8600000000020352e3/notes
I’m not sure if this is related to the issue.

**Comment by Frenzie** [comment]
The feed was valid (or close enough) when I checked. If it was invalid temporarily it should presumably pick up the other entries when refreshing?

**Comment by LinxHex** [comment]
> The feed was valid (or close enough) when I checked. If it was invalid temporarily it should presumably pick up the other entries when refreshing?

Unfortunately, even after observing for several days, I am still unable to retrieve new entries when the feed updates with new content.

**Comment by LinxHex** [comment]
> The feed was valid (or close enough) when I checked. If it was invalid temporarily it should presumably pick up the other entries when refreshing?

Perhaps I can provide you with a FreshRSS account that I’ve set up so you can try it yourself?

**Comment by LinxHex** [comment]
I just updated FreshRSS from the latest version to the edge version, and unexpectedly, the issue is resolved. Although I’m not sure which change fixed the problem.

**Comment by Frenzie** [comment]
Probably https://github.com/FreshRSS/FreshRSS/pull/4487 then.

**Comment by Alkarex** [comment]
@KawausoJyou Check in the feed's settings for the unicity criteria:
![image](https://github.com/user-attachments/assets/3cad7f4a-34e8-4e15-86d1-2bb3b6484bc5)
