### ISSUE TITLE
[Bug] GReader API: adding multiple feeds w/ categories

### ISSUE THREAD

**Issue by bhj** [FreshRSS/FreshRSS#7013]
### Describe the bug

Hey, thank you for all your work. I noticed that when adding multiple feeds in a single request it's not possible to assign a category to both. For example, only the 2nd feed will be assigned to `testtag2` (the 1st feed will be uncategorized) given the following:

```
curl 'https://rss.mysite.com/api/greader.php/reader/api/0/subscription/edit' \
  --data-raw 'ac=subscribe&s=feed%2Fhttps%3A%2F%2Ffeeds.arstechnica.com%2Farstechnica%2Ftechnology-lab&t=ars+techlab&a=user%2F-%2Flabel%2Ftesttag1&s=feed%2Fhttps%3A%2F%2Ffeeds.arstechnica.com%2Farstechnica%2Fgadgets&t=ars+gadets&a=user%2F-%2Flabel%2Ftesttag2'
```

Same behavior if only one `a` param is sent.

### To Reproduce

cURL provided above

### Expected behavior

Ideally, the `a` (category) param would be treated as an array, similar to `$streamNames` and `$titles`. I suppose the next best thing would be to at least be able to apply a single category to all feeds in the request, though that feels a bit inconsistent.

### FreshRSS version

1.24.3

### Environment information

- Installation type: Docker

**Comment by Alkarex** [comment]
That should be easy to add.
By curiosity, are you working on a client?
And do you know other clients supporting this type of call?

**Comment by Alkarex** [comment]
> I suppose the next best thing would be to at least be able to apply a single category to all feeds in the request

I will go with that approach because the original GReader API seemed to allow multiple values to the `a` parameter but to apply multiple categories identically to each of the feeds in the request, not a different category to the respective feeds.
Since FreshRSS only supports a single category per feed, we cannot accept multiple `a` values, but we should still apply that category to all feeds in the request.

Reference: https://github.com/mihaip/google-reader-api/blob/master/wiki/ApiSubscriptionEdit.wiki

> I noticed that when adding multiple feeds in a single request it's not possible to assign a category to both. For example, only the 2nd feed will be assigned to testtag2 (the 1st feed will be uncategorized)

Did you notice the error of uncategorized feed when adding feeds to a non-existing category, or also when adding feeds to existing categories?

Would you be able to test https://github.com/FreshRSS/FreshRSS/pull/7017 ? (not tested yet)

**Comment by bhj** [comment]
> By curiosity, are you working on a client?

Eventually ;) but starting with a TypeScript library for the API that aims to make it a bit less painful to use. Will link it here once I create the repo. Testing with FreshRSS has been very helpful!

> And do you know other clients supporting this type of call?

No, in fact I was surprised that the endpoint even supported multiple stream IDs at all.

> the original GReader API seemed to allow multiple values to the a parameter but to apply multiple categories identically to each of the feeds in the request, not a different category to the respective feeds.

Makes sense, though I wonder, if the current behavior is incorrect and no one has noticed - maybe an improvement to the API could be made in this case... e.g. if count of `a` matches `s`, associate them (like with title), if only a single `a`, assign the same category to all, otherwise... `400`? Hah, just a thought - some of the other API tweaks like the `type` property on `tag/list` are really handy.

> Did you notice the error of uncategorized feed when adding feeds to a non-existing category, or also when adding feeds to existing categories?

Have not gotten that far, but I did notice it'd be an issue in edit mode too, which it looks like your fix addresses. I will try to test in the next week or so.

Tangentially related, it would be so fun to help develop a "real" API that could become a standard across the ecosystem to replace this (very aptly versioned v0) GReader API. FreshRSS would be a great place to do it. Thanks again for all your work!

**Comment by Alkarex** [comment]
> Eventually ;)

Then please make sure you have checked https://freshrss.github.io/FreshRSS/en/developers/06_GoogleReader_API.html#google-reader-compatible-api , in particular the *Synchronisation strategy* part (e.g., https://github.com/FreshRSS/FreshRSS/issues/2566#issuecomment-541317776)

I have also just written additional thoughts in
https://github.com/jocmp/capyreader/discussions/533#discussioncomment-11341808

> some of the other API tweaks like the `type` property on `tag/list` are really handy

👍🏻

**Comment by bhj** [comment]
Hey, one semi-related question: on the `tag/list` endpoint, it seems labels of the "folder" type (categories) are not included if no feeds are "in" them, whereas labels of the "tag" type are always included, even if not assigned to any items.

Is there a historical reason for that?

**Comment by Alkarex** [comment]
> on the `tag/list` endpoint, it seems labels of the "folder" type (categories) are not included if no feeds are "in" them, whereas labels of the "tag" type are always included, even if not assigned to any items.

The idea was to not return the default category when there is no feed in it:
* https://github.com/FreshRSS/FreshRSS/pull/2840
* https://github.com/FreshRSS/FreshRSS/issues/2839

But now that I think again about it, I am not sure it was a good idea.
Please try to the following PR and let we know what you think:
* https://github.com/FreshRSS/FreshRSS/pull/7020

**Comment by bhj** [comment]
For reference, here's my aforementioned [TypeScript library for the Google Reader API](https://github.com/bhj/libseymour)
