### ISSUE TITLE
[Feature] Support keybinding option for "There are new articles available, click to refresh the page." banner

### ISSUE THREAD

**Issue by gvoysey** [FreshRSS/FreshRSS#7018]
I am able to configure a keyboard shortcut for "Update Feeds" in settings: 
![2024_21_Nov_113216](https://github.com/user-attachments/assets/928cff5e-337b-4c20-a82f-c504f9b46b9b)

but i am unable to do so for the related operation of actually refreshing the display when new content becomes available, with or without a manual feed refresh.  Instead, this banner is displayed and must be clicked: 

![2024_21_Nov_113036](https://github.com/user-attachments/assets/84a0a724-8807-41ab-9656-ea03f4efe778)

**Describe the solution you’d like**
I would like a way to configure a keyboard shortcut which, when used, would have the same effect as refreshing the page to see new articles. 

**Additional context**
I'm self-hosting freshRSS, currently on 1.23.0

**Comment by math-GH** [comment]
Clicking on the banner is the same as refresh the page. `Ctrl` + `R`or `F5` is doing the same

**Comment by gvoysey** [comment]
well don't i feel silly! 

i'll close this, but feel free to reopen if you see fit.
