### ISSUE TITLE
Brave: Fail with synchronous XHRs

### ISSUE THREAD

**Issue by captainepoch** [FreshRSS/FreshRSS#7019]
### Describe the bug

Every time I try to login into my FreshRSS instance, I got this message:

<img width="660" alt="Captura de pantalla 2024-11-23 a las 6 30 12" src="https://github.com/user-attachments/assets/eece8970-210d-45ac-ac0a-bd8c8f203973">

Tried LibreWolf on the same computer and it works.

### To Reproduce

1. Go to your instance.
2. Try to login.

### Expected behavior

I can login.

### FreshRSS version

1.24.3

### Environment information

- Database version: PostgreSQL 15 (latest stable)
- PHP version: whatever it is in the Docker container
- Installation type: Docker with the image provided by FreshRSS.
- Web server type: Nginx
- Device: MacBook Pro
- OS: macOS 13 (latest)
- Browser: Brave 1.73.91 Chromium: 131.0.6778.85 (Build oficial) (x86_64)

### Additional context

Brave has all the permissions, globally, blocked for every single website, and the Shields are in Aggresive. Those are enabled on a needed basis. Third-party cookies are also blocked, although FreshRSS doesn't use that.

**Comment by Alkarex** [comment]
Hello,
This is most likely due to Brave wrongly blocking a request, a script, or a session cookie.
I do not believe this is something that should be fixed on FreshRSS side, but try to check in your Web browser logs what it might be. Additional debugging welcome

**Comment by captainepoch** [comment]
I tried to allow every permission and disable Shields and other extensions, and it kept failing.

It says this:

```
extra.js?1725604397:52 [Violation] Permissions policy violation: Synchronous requests are disabled by permissions policy.
crypto_form.onsubmit @ extra.js?1725604397:52
extra.js?1725604397:52 Uncaught NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://<domain>/i/?c=javascript&a=nonce&user=<user>'.
    at crypto_form.onsubmit (/scripts/extra.js?1725604397:52:7)
crypto_form.onsubmit @ extra.js?1725604397:52
```

It might have something to do with, maybe, something Brave does before compiling the browser. I'll try to setup PHP Sessions and try again.

**Comment by Alkarex** [comment]
> 'll try to setup PHP Sessions

It if works with other Web browsers, then your PHP sessions are already working.

I believe it is due to the following line, which should be changed to an asynchronous call. But in this case, we do want the synchronous blocking, so there is a need to think a bit about how to change it:

https://github.com/FreshRSS/FreshRSS/blob/3d8dd6e1fa86538c467cb919235f78fd740c800c/p/scripts/extra.js#L48

See https://developer.chrome.com/blog/getting-rid-of-synchronous-xhrs

**Comment by Frenzie** [comment]
It's not done during page unloads.

In any case, changing that looks simple if it's desired.

**Comment by Alkarex** [comment]
@captainepoch Would you be able to try the following patch?
https://github.com/FreshRSS/FreshRSS/pull/7023

**Comment by captainepoch** [comment]
@Alkarex Is it possible to deploy, somehow, with the Docker image? I wouldn't know how to test it.

**Comment by captainepoch** [comment]
Thank you very much for the fix, @Alkarex, I'll wait until the next release to test this!

**Comment by Alkarex** [comment]
@captainepoch Please give a try to `freshrss/freshrss:edge`

**Comment by captainepoch** [comment]
Sure, give me a few minutes, please.

**Comment by captainepoch** [comment]
It seems to be working, thank you very much!

**Comment by Alkarex** [comment]
Excellent. Thanks for the feedback
