### ISSUE TITLE
[Bug] #force_feed doesn’t remain after url

### ISSUE THREAD

**Issue by Fletch-99** [FreshRSS/FreshRSS#7021]
### Describe the bug

One url, even though it has an rss feed, only works with #force_feed. After adding the url it works fine, but the #force_feed  does not remain after the rss feed url so it has to be manually added every time for updating the feed or else it gives an error. 

### To Reproduce

1. Go to 'any rss url'
2. Click on ‘url and add #force_feed'
3. Refresh/update the feed, everything works
4. Log out and log in after some time. Go to the feed. The #force_feed next to the rss feed is gone and the feed produces an error and it’s not updated. 

### Expected behavior

Force_feed should remain when it’s added.

### FreshRSS version

1.23.4

### Environment information

- Database version: [SQLite]
- PHP version: [PHP 8.3.13]
- Installation type: [e.g. Docker Linux server.io]
-Web server type: [e.g. Apache, nginx]
- Device: [Web interface]
- OS: [any]
- Browser: [Brave and Safari]

**Comment by Alkarex** [comment]
Would you be able to share the URL of that problematic feed?

**Comment by Fletch-99** [comment]
Sure, it’s https://oneman.gr/feed

**Comment by math-GH** [comment]
> FreshRSS version
>
> 1.23.4

could you please check your FreshRSS version? If it is 1.23, could you please update it to the newest one?

**Comment by Frenzie** [comment]
Could be it disappears when redirecting or some such? Can't test atm.

**Comment by Fletch-99** [comment]
> > FreshRSS version
> > 1.23.4
> 
> could you please check your FreshRSS version? If it is 1.23, could you please update it to the newest one?

It’s 1.24.3

**Comment by Alkarex** [comment]
I think it is simply a case of not using the correct feed URL, which gets redirected to the correct address, but which happens to be served with a wrong content type.

Could you try with `https://www.oneman.gr/feed/#force_feed` instead, @Fletch-99 ?

**Comment by Fletch-99** [comment]
Thank you, it’s working!
