### ISSUE TITLE
[Feature] Bulk remove feeds with errors

### ISSUE THREAD

**Issue by thompcha** [FreshRSS/FreshRSS#7025]
**Is your feature request related to a problem? Please describe.**
I recently imported an OPML file with about 400 feeds in it. About half of them are defunct. I love that FreshRSS provides an indication when the feed url can't be reached, but it would take a lot of time and effort to go through and individually remove each bad feed.

**Describe the solution you’d like**
I would be very helpful if I could get a button next to the `Show only feeds with errors` button that let's me remove all feeds with errors.

<img width="674" alt="Screenshot 2024-11-26 at 10 09 35 AM" src="https://github.com/user-attachments/assets/35173dfb-2a0c-425d-b103-2127cf57bfde">

**Describe alternatives you’ve considered**
If there is some way I can do this in the database I'm open to it. Also, I would consider some type of tool the checks all the links my OPML file and removes broken ones.

**Comment by Alkarex** [comment]
It is possible to bulk delete all feeds of a given category, if than can help.

Otherwise by SQL (do a backup and/or export before):

```sql
DELETE FROM thompcha_feed WHERE error = 1;
```

**Comment by Alkarex** [comment]
I have added a new button for you: *Delete feeds in error*, in the settings of categories

See https://github.com/FreshRSS/FreshRSS/pull/7030
Tests welcome

**Comment by pe1uca** [comment]
Can a bulk reset error button be added in here? Or should be better to create a new feature request?  

Similar situation, added an OPML with a lot of feeds, got rate limited and now basically all the feed has errors which I know are temporary.  
Also happened when my PC lost internet connection, the requests timed out and all feeds had errors.  

The way to reset the error (AFAIK) is to update the feed, which requires extra steps with extensions like AutoTTL which prevents the feed from being updated.  

I had to go to the DB and ran `update feed set error=0 where category=<id>`

**Comment by Alkarex** [comment]
@pe1uca When feeds have such errors, no need to do anything special: they will be retried at the next refresh, according to the refresh policy (minimum 15 minutes later)

**Comment by pe1uca** [comment]
Oh, the message makes me believe I need to get to each feed  
`Blast! This feed has encountered a problem. Please verify that it is always reachable then update it.`

**Comment by Frenzie** [comment]
Perhaps an "if this problem persists," should be added there.

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/7049
