### ISSUE TITLE
Aide pour API Google Reader

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#704]
@cmtm78 writes: Hello, I am trying to build my own reader client on FreshRss (tinder like interface).
EasyRSS connects well to my FreshRSS server.
On my app, I can not pass the "token" phase of the API.

"http://www.acacis.com/p/api/greader.php/reader/api/0/token" where acacis.com is where my freshrss is located

In the log I have HTTP_AUTHORIZATION set but empty.
my ".htaccess" is 

<IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteRule .\* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
</IfModule>

Server is a shared server at One.com.

What is wrong ? As easyRSS works fine, I suppose it is not my server. I must miss something.

Thanks for your help

**Comment by cmtm78** [comment]
Bonjour Alexandre

Je cherche maintenant à modifier la version que je me suis installée de FreshRSS pour ne garder en base que des entries qui contiennent une img. 

Je voudrai intervenir à la source mais je ne vois pas dans quelle partie du code se fait l'actualisation de la base entry (je prévois simplement de ne pas enregistrer les entrées dans lesquelles je ne trouve pas de photo au parsing du champs content).

Peux tu m'indiquer ou je dois intervenir ?

Merci pour ton aide

T

**Comment by Alkarex** [comment]
Les nouveaux articles sont préparés avant ajout en base de données via la fonction `loadEntries()` https://github.com/FreshRSS/FreshRSS/blob/beta/app/Models/Feed.php#L264
Vous pouvez voir quelques ligne plus bas la gestion des `enclosure` ou pièces jointes des flux (images, vidéos, sons), bien que dans certains cas ces liens soient directement dans le corps HTML de l'article. Pour sauter un article, il ne faut pas l'ajouter à `$entries[]` https://github.com/FreshRSS/FreshRSS/blob/beta/app/Models/Feed.php#L315

Une autre option est d'ajouter tous les articles en base de données, mais de les filtrer en sortie.

Dans les deux cas, je vous suggère de regarder les discussions actuelles sur le mécanisme d'extension (plug-ins) en cours de développement, qui me semblerait bien adapté à votre besoin.

**Comment by Alkarex** [comment]
Je ferme ce ticket qui ne semble plus actif (j'espère que vous avez eu les informations nécessaires), mais n'hésitez pas à le rouvrir au besoin ou d'en créer un nouveau.

**Comment by Purexo** [comment]
Bonjour je reviens vers vous (après un long moment)
j'ai beau chercher, je ne trouve pas de doc lisible des apis de FreshRSS

Pour les versions future de mon Addon, j'aurais besoins de récuperer le nombre d'article non lu, ça c'est OK : 

```
GET /p/api/greader.php/reader/api/0/unread-count?output=json (avec le header d'authetification)
Authorization:GoogleLogin auth=TOKEN
```

Et surtout, une liste des (5) derniers flux non lu avec
le titre, le lien du flux, et son contenu (si possible un petit résumé plutot que le contenu complet)

Aussi, est il possible pour l'authentification d'utiliser le cookie de FreshRSS, plutot que d'utiliser une requete en GET, avec le login et le mot de passe en clair à l'interieur pour récuperer un token d'authetification.

Sinon j'ai vraiment mal cherché, ou la doc du greader est imbitable ?

J'ai trouvé une [doc lisible](https://github.com/theoldreader/api#item-contents) mais je bute sur item-contents, ça fait toujours des badrequest.

Pour mes test j'utilise l'addon firefox "http requester" qui est pratique pour former des requetes

Donc : 
- Unread : /p/api/greader.php/reader/api/0/unread-count?output=json OK
- ListID : /p/api/greader.php/reader/api/0/stream/items/ids?output=json OK
  - s=user/-/state/com.google/reading-list
  - n=5
- ItemContent : /p/api/greader.php/reader/api/0/stream/items/contents?output=json BAD
  - i=tag:google.com,2005:reader/item/00157a17b192950b65be3791
  - i=reader/item/00157a17b192950b65be3791
  - i=00157a17b192950b65be3791

ItemContent, ça marche pour aucun des cas. :(

**Comment by Alkarex** [comment]
@purexo Voir les commentaires en tête de https://github.com/FreshRSS/FreshRSS/blob/beta/p/api/greader.php pour une liste des documentations que j'ai pu trouver. Regardez aussi les commentaires dans le reste du fichier.

Pour vos 5 articles les plus récents non-lus, essayez quelque-chose comme :

```
GET /p/api/greader.php/reader/api/0/stream/contents/user%2F-%2Fstate%2Fcom.google%2Freading-list?xt=user/-/state/com.google/read&n=5&r=n
```

Pour l'instant, il y a un mot de passe API différent du mot de passe principal à cause du fait que ce mot de passe risque d'être stocké par les applications, et qu'il est transmis en dépendant entièrement de HTTPS (aucune protection dans le cas de HTTP).

P.S. : D'une manière générale, c'est une bonne idée de regarder dans les logs de votre serveur Web les requêtes faites par un client de référence, comme News+ ou EasyRSS.

**Comment by Purexo** [comment]
Merci, j'avais vraiment galéré longtemps avant d'abandonner et espérer une réponse.
Après avoir testé, votre requete est pas tout à fait bonne en voici la correction :

```
POST /p/api/greader.php/reader/api/0/stream/contents/reading-list
output=json
xt=user/-/state/com.google/read
n=5
r=n
```

Je met en POST pour plus de lisibilité (et ça fonctionne) mais GET fonctionne aussi.
C'est pas tout a fait les critère qu'il me faut, mais je me débrouillerai avec du code.
Mais dans l'idée, j'ai besoin d'afficher 5 items. en priorité les non lu. Ensuite les déja lu pour completer si besoin les slots manquant.

Concernant la partie de l'authetification, justement, peut-on utiliser le cookie de FreshRSS (quand on ce co normalement à son site pour lire les flux) dans un addon, et si oui, comment ça ce passe au niveau des requetes. Cela afin d'éviter un password en clair qui ce balade partout.

**Comment by Purexo** [comment]
J'arrive pas à sélectionner juste les flux lu, et suite à la lecture du code de greader.php ça ne m’étonne pas, mais c'est vraiment dommage :(

greader.php - ligne 360 - function streamContents

``` php
    switch ($exclude_target) {
        case 'user/-/state/com.google/read':
            $state = FreshRSS_Entry::STATE_NOT_READ;
            break;
        default:
            $state = FreshRSS_Entry::STATE_ALL;
            break;
    }
```

il serait intéressant d'ajouter :

``` php
case 'user/-/state/com.google/unread':
    $state = FreshRSS_Entry::STATE_READ;
    break;
```

Et pourquoi pas d'autres états encore

je viens de faire une [PR](https://github.com/FreshRSS/FreshRSS/pull/1033), suite à un test rapide sur mon serveur, je peux maintenant faire : 

```
GET /p/api/greader.php/reader/api/0/stream/contents/user/-/state/com.google/reading-list?xt=user%2F-%2Fstate%2Fcom.google%2Funread&n=5
```

et je récupère ainsi les 5 derniers flux lu

**Comment by Purexo** [comment]
Maintenant que mon Addon Firefox est fonctionnel, je me disais que ça pourrai intéresser des gens.

Ou dois-je signaler ça ?
pour l'info il est disponible ici : https://github.com/purexo/FreshRSS-Notify  
et en attente de review ici : https://addons.mozilla.org/fr/firefox/addon/freshrss-notify/  
tant qu'il n'est pas vérifié, il n'apparaitra pas. Même avec le lien :-(

**Comment by Alkarex** [comment]
@purexo Votre extension semble avoir été acceptée, non ?

**Comment by Purexo** [comment]
Oui. Et les trucs qui me restent à faire attendront plus tard (passer au système 'universel' chrome, revoir le système d'authentification : cad utiliser le système de cookie pour ce logger à l'api si possible, pour ne pas avoir à demander de password)

Les prochaines versions ce sera essentiellement du bugfixes (si j'en trouve).
