### ISSUE TITLE
[Improvement] API management / information

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#7041]
Currently the API management has not a good UX.

The admin can disable/enable the API (todo: the API is used not only for the apps anymore, the user query sharing uses the API toggle too)
![grafik](https://github.com/user-attachments/assets/caaa7ba5-3f43-4260-a494-393b21aa9672)

The password for the app API will be set in the user profile page for each user. The password field is only available if the API is enabled. The user cannot read any hint if the API is disabled.

![grafik](https://github.com/user-attachments/assets/29d05c94-f578-4201-aba7-53641ba2c8c5)

Would it make sense to give a hint to the user that the API is disabled? (i.e. the password field is readonly/visible but disabled + text message). A link to known apps list is not given. (When I read the Mastodon posts that ask for recommended apps I know that they do not know the provided apps list)

The user query does it other way around: The options for sharing are enabled - independent of an enabled/disabled API. Would it make sense to have the options there readonly/visible but disabled + text message?

![grafik](https://github.com/user-attachments/assets/be43ad2a-8d1e-4b85-86b8-09370f6de6af)

**Comment by Alkarex** [comment]
Good ideas 👍🏻
