### ISSUE TITLE
[Bug] GReader API: edit-tag w/ multiple labels

### ISSUE THREAD

**Issue by bhj** [FreshRSS/FreshRSS#7057]
### Describe the bug

Hey again :) This is similar to #7017, but dealing with items. When multiple labels are specified (i.e. the `a` or `r` param is repeated) only the last param is applied. From what I [can](https://feedhq.readthedocs.io/en/latest/api/reference.html#edit-tag) [gather](https://web.archive.org/web/20120204201356/http://code.google.com/p/google-reader-api/wiki/ApiEditTags), it should be possible to add/remove multiple labels at once.

It's a minor thing, but I noticed multiple `i` params are already supported, so ideally this could be improved to more closely align with "the spec".

### To Reproduce

curl 'https://example.com/api/greader.php/reader/api/0/edit-tag' \
  --data-raw 'i=tag%3Agoogle.com%2C2005%3Areader%2Fitem%2F0006265cbcf0ab7c&a=user%2F-%2Flabel%2Ftestlabel1&a=user%2F-%2Flabel%2Ftestlabel2'

### Expected behavior

Both labels are applied

### FreshRSS version

1.24.3

### Environment information

- Installation type: Docker

**Comment by Alkarex** [comment]
Could you please try https://github.com/FreshRSS/FreshRSS/pull/7060 ?

**Comment by Alkarex** [comment]
P.S. Nice to see someone looking into the API in such depth 👍🏻

**Comment by Alkarex** [comment]
Related documentation effort https://github.com/FreshRSS/FreshRSS/discussions/7326
