### ISSUE TITLE
Flux ne marchant pas alors que valide

### ISSUE THREAD

**Issue by qwertygc** [FreshRSS/FreshRSS#706]
Hello !
- le flux suivant existe : http://news.jesuislibre.net/mediapart-economie.rss
- Il est valide
  et il marche pas "Arf ! Ce flux a rencontré un problème. Veuillez vérifier qu’il est toujours accessible puis actualisez-le."
  Une idée ?

**Comment by Alkarex** [comment]
https://github.com/simplepie/simplepie/pull/396
