### ISSUE TITLE
[Bug] Login with wrong user name: error message "The web server seems to be incorrectly configured for cookies required for PHP sessions!"

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#7061]
### Describe the bug

(https://mastodon.social/@ts-new@hub.tschlotfeldt.de/113596516493945482 made me aware of this bug)

Login procedure: If the user name is NOT correct the error message is strange/wrong in that case.

(Not correct means also that the user name is case sensitiv!)

The error message: "The web server seems to be incorrectly configured for cookies required for PHP sessions!"

![grafik](https://github.com/user-attachments/assets/6ffdaa8c-a291-46e0-88c5-0eb0abbf59c6)
(screen shot from demo.freshrss.org - user name -> I tried `demos` instead of `demo`)

### To Reproduce

1. Go to login page
2. try to login with a non existing user
3. see the misleading error message

(reproduce-able on demo.freshrss.org too)

### Expected behavior

I would expect a message like: "Wrong user name or password".
And I would not expect that there is an issue with the case sensitivity of the user name

### FreshRSS version

1.25.0-dev

### Environment information

- Database version: ~SQLite~ MySQL
- PHP version: PHP 8.1
- Installation type: git
-Web server type:  Apache

**Comment by math-GH** [comment]
link #5973
link #6195

**Comment by Frenzie** [comment]
* Valid username, invalid password: login is invalid
* Non-existent username: 403 forbidden with login is invalid message
* Nearly valid username (wrong case): cookies message

**Comment by Alkarex** [comment]
Please try https://github.com/FreshRSS/FreshRSS/pull/7066
