### ISSUE TITLE
Marquer comme lu au défilement de la page pour les articles pliés

### ISSUE THREAD

**Issue by gu1ll0me** [FreshRSS/FreshRSS#707]
Appliquer le principe "Marquer comme lu au défilement de la page" pour les articles pliés.

**Comment by Alkarex** [comment]
C'est implémenté dans la branche /dev (future version 1.6 qui sortira dans quelques jours). Tests bienvenus :-)

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/1309

**Comment by gu1ll0me** [comment]
Ça fonctionne à merveille!
Merci beaucoup.

**Comment by Alkarex** [comment]
@michaudg Merci pour le test :-)
