### ISSUE TITLE
Some feeds are not accepted with "unknown error" ?

### ISSUE THREAD

**Issue by greguti** [FreshRSS/FreshRSS#7076]
https://www.lemonde.fr/politique/rss_full.xml and some other french news RSS can't be added to my FreshRSS account, the log shows the error message: `Unknown error for feed [https://www.lemonde.fr/politique/rss_full.xml]` 

I'm curating a database of around 200 RSS feeds and it works fine for almost all of it, excepted for these ones.

**Comment by Alkarex** [comment]
Le flux https://www.lemonde.fr/politique/rss_full.xml marche bien pour moi.
Lorsque un flux ne fonctionne pas, essayez à nouveau une heure ou deux plus tard.
Si vous avez *Unknown error* dans vos logs, il y a probablement un message plus précis plus tôt dans les logs.
Vous pouvez aussi essayer `curl -v 'https://www.lemonde.fr/politique/rss_full.xml'` depuis votre serveur pour aider à diagnostiquer le problème.

**Comment by greguti** [comment]
J'ai retenté et ça ne fonctionne toujours pas. Quand je précise l'adresse dans la page "Ajouter un flux/une catégorie", j'ai le message _"Le flux ne peut pas être ajouté. [Consulter les logs de FreshRSS] pour plus de détails. Vous pouvez essayer de forcer l’ajout par addition de #force_feed à l’URL."_

Dans les logs, `Unknown error for feed [https://www.lemonde.fr/politique/rss_full.xml]`

Parmi les logs, j'ai aussi ça : `cURL error 22: The requested URL returned error: 403 [https://www.lemonde.fr/politique/rss_full.xml]`

L'ajout de #force_feed ne permet pas de réparer ça.

**Comment by Alkarex** [comment]
`403` signifie interdit. Que donne `curl -v 'https://www.lemonde.fr/politique/rss_full.xml'` depuis votre serveur ?
Cela pourrait être que votre adresse IP est bannie

**Comment by Alkarex** [comment]
Si c'est que votre adresse IP est bannie, essayez de passer par https://feedburner.google.com

**Comment by greguti** [comment]
Thanks, ça fonctionne bien en passant par feedburner !
