### ISSUE TITLE
[Feature] Put the read/unread and favourite buttons at the bottom of articles in reader view

### ISSUE THREAD

**Issue by Tywele** [FreshRSS/FreshRSS#7115]
**Is your feature request related to a problem? Please describe.**
When I read articles in reader view it's annoying to scroll back up to the top of the article to mark the article as read and/or unfavourite it.

**Describe the solution you’d like**
Putting both buttons at the bottom would solve this problem.

**Additional context**
![grafik](https://github.com/user-attachments/assets/06bb6ae5-d734-45eb-9f20-3b156dcafd28)

**Comment by Alkarex** [comment]
Yes, good suggestion

**Comment by Frenzie** [comment]
Didn't @math-GH add this recently?

Edit: never mind, reading view is a bit different.

**Comment by math-GH** [comment]
Reading view misses some buttons/features.

I will put it on my todo list. I think is is very useful to have these buttons at the bottom too.

**Comment by math-GH** [comment]
Tests are welcome: #7133
I guess it will not be shipped with 1.25.0 these days but later.
