### ISSUE TITLE
[Bug] Missing Subscription Button

### ISSUE THREAD

**Issue by karnos1000** [FreshRSS/FreshRSS#7118]
### Describe the bug

I don't have a Subscription Button. I am using FreshRSS 1.24.3 installed on TrueNAS ElectricEel-24.10.0.2. It's running as a docker container. I have tried this on multiple computers, in multiple browsers, and multiple versions of both TrueNAS and FreshRSS.  I had the button when I first installed the app, but after I added my first feed, it disappeared. I don't have it in Normal View or Reading View.

### To Reproduce

Please see attached image
![FreshRSS](https://github.com/user-attachments/assets/97f849b7-4082-43ee-9705-f3c202ad9595)

### FreshRSS version

1.24.3

### Environment information

- Database version: TrueNAS ElectricEel-24.10.0.2
- PHP version: Unknown
- Installation type: Docker
-Web server type: Unknown
- Device: Desktop using Vivaldi, Edge, Firefox, Samsung Galaxy Note Using Duck Duck Go
- OS: Windows 10, Latest Android
- Browser: Vivaldi 6.7.3329.31, Edge, Firefox,

**Comment by Alkarex** [comment]
Hello,
It looks like your are not logged in and are in anonymous mode.
