### ISSUE TITLE
[Bug] normal user does not have access to the privacy configs

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/FreshRSS#7123]
### Describe the bug

Regression: #4603

![grafik](https://github.com/user-attachments/assets/855dcb78-b00e-48d1-a8ba-5387b79ccefe)

![grafik](https://github.com/user-attachments/assets/4f1a156c-eeea-427d-8cca-596ddb34d152)

### To Reproduce

Have a non-admin user

go to `Privacy`

see the 403 error

### Expected behavior

Privacy setting is available.

### FreshRSS version

1.25.0-dev

### Environment information

- Database version: SQLite
- PHP version: PHP 8.1
- Installation type: manual
- Web server type: Apache

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/7132
