### ISSUE TITLE
[Bug] cURL error 22 for the website GBAtemp

### ISSUE THREAD

**Issue by update-freak** [FreshRSS/FreshRSS#7126]
### Describe the bug

When I add the RSS-Feed from the website GBAtemp it raises the error:
`cURL error 22: The requested URL returned error: 403 [https://gbatemp.net/forums/gbatemp-scene-news.101/index.rss]`

I tried the following URLs but no one of this is working (Source: https://gbatemp.net/threads/is-there-an-rss-feed-for-the-news-forum-page.549667/)
- https://gbatemp.net/forums/gbatemp-scene-news.101/index.rss
- https://gbatemp.net/forums/gbatemp-scene-news.101.rss

### To Reproduce

1. Try to add https://gbatemp.net/forums/gbatemp-scene-news.101/index.rss as RSS-Feed

### FreshRSS version

1.24.3

### Environment information

- PHP version: 8.3.14, 
- Installation type: Docker
- Device: DELL Laptop, Samsung Galaxy S23
- OS: Windows 11
- Browser: Chrome

### Additional context

Not sure if it's a bug from FreshRSS or from the RSS-feed of GBAtemp

**Comment by Frenzie** [comment]
Trying that in cURL results in a webpage that tells you to enable JavaScript.

**Comment by Alkarex** [comment]
Indeed. Those feeds are blocked server side, and this is not due to FreshRSS.
See for instance https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fgbatemp.net%2Fforums%2Fgbatemp-scene-news.101%2Findex.rss
