### ISSUE TITLE
Make it clearer in the documentation that OIDC login support only works on apache

### ISSUE THREAD

**Issue by aftix** [FreshRSS/FreshRSS#7134]
The OIDC support seems to be implemented using a module in apache. This is not at all obvious directly from the documentation.

**Comment by Alkarex** [comment]
https://freshrss.github.io/FreshRSS/en/admins/16_OpenID-Connect.html

![image](https://github.com/user-attachments/assets/e1a73ab9-b8f7-4920-9328-fe9e71bf0a07)

**Comment by aftix** [comment]
Yes, that's the page I was pouring over for an hour and a half. As someone who is not at all familiar with apache or php programming in general, it was not clear at all that mod_auth_openidc was an apache plugin and not a php package or something.

- There was no reason to click on that hyperlink and read the project's README to see it is an apache module
- The hyperlinks directly to the auth_openidc.conf file in the mod_auth_openidc repo take you directly to a scrolled down, commented configuration file. This file is well written and immediately contains all the information you would have clicked on the link for, so there no reason to clicking through the repo to see the README
- freshrss's documentation in general uses Apache for the example configurations, so there is nothing off about apache configuration options being on the page. There is nothing obvious about why on this page in particular you can't translate the .htaccess configuration setup to nginx or whatever you're using, when on every other documentation page it's perfectly fine to do so

**Comment by Alkarex** [comment]
PR welcome to make the documentation clearer.
As of now, this documentation page explains how to use OpenID Connect using our official Docker image or using an Apache installation, and nothing else. You could also implement the same in nginx if it supports OpenID Connect in one way or another.
