### ISSUE TITLE
[Bug] 'Open Menu' -> 'Manage' from feedlist opens the settings of the wrong feed

### ISSUE THREAD

**Issue by RonnyB74** [FreshRSS/FreshRSS#7154]
### Describe the bug

When editing a feed, an incorrect feed is opened for editing:

![Auswahl_008](https://github.com/user-attachments/assets/899652a1-1b86-42a2-a8fe-ad9926ec33be)
![Auswahl_007](https://github.com/user-attachments/assets/fd242e58-bc7c-410f-8cb5-056a65db79f2)

### To Reproduce

1. Go to feedlist
2. Click on 'Gear wheel' -> 'Manage'
3. The wrong feed is opened for editing.

### FreshRSS version

1.25.1-dev from 28.12.2024

### Environment information

- Database version: mysql  Ver 15.1 Distrib 10.11.6-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper
- PHP version: PHP 8.2.26 (cli) (built: Nov 25 2024 17:21:51) (NTS)
- Installation type: git
- Web server type: Apache
- OS: Debian stable
- Browser: Vivaldi

**Comment by Alkarex** [comment]
Thanks for the bug report. I have also just noticed it. It is a recent regression. 
Will fix tonight

**Comment by math-GH** [comment]
Regression #7131

**Comment by math-GH** [comment]
same in feed management

**Comment by Alkarex** [comment]
Quick tests welcome https://github.com/FreshRSS/FreshRSS/pull/7155
