### ISSUE TITLE
[Bug] authz_core:error triggers fail2ban

### ISSUE THREAD

**Issue by Arrappathor** [FreshRSS/FreshRSS#7157]
### Describe the bug

When using Firefox mobile (version 133.0.3) on the web-ui toogleing read/unread-buttons or change to submenu and return triggers fail2ban: 
`[authz_core:error] [pid 12119:tid 12119] [client 00.000.00.00:60236] AH01630: client denied by server configuration: /path/to/fresh/p/themes/manifest.json` 
This happens since upgrade to 1.25.0, used theme is mapco.

### To Reproduce

1. Have fail2ban installed to stop maliciuos login attempts.
2. Use FirefoxMobile on Android.
3. Toogle read/unread or change to side/submenu/settings.
4. Fail2ban is triggerd and bans my ip.

### Expected behavior

Fail2ban isn't triggerd and server stays accesible.

### FreshRSS version

1.25.0

### Environment information

- Database version: MariaDB 10.5
- PHP version: PHP 8.2.7
- Installation type: Installed from ZIP few years ago, upgraded via build-in updater
- Web server type: Apache
- Server/OS: Raspberrypi OS/Debian Bookworm 12.8
- Device/OS: Android 13 StockROM on Samsung SM-T500 as well as LineageOS on Moto G7 power
- Browser: FirefoxMobile 133.0.3

### Additional context

This happens since upgrading to 1.25.0.

**Comment by Alkarex** [comment]
Fixed in https://github.com/FreshRSS/FreshRSS/pull/7158
Tests welcome
