### ISSUE TITLE
Problème de focus lié au chargement des images

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#717]
Je fonctionne en passant les articles en faisant j. La plupart du temps ça marche, sauf que le logiciel va charger parfois des images et on se retrouve avec un décalage sur le focus donc l'article n'est pas calé au début mais n'importe où

**Comment by Alkarex** [comment]
Je ferme, mais n'hésitez pas à signaler si le problème n'est pas réglé.
