### ISSUE TITLE
Problème de focus lié au chargement des nouveaux articles

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#720]
Quand j'appuie sur j un certain nombre de fois, il arrive à la limite et donc affiche le chargement. Je retrouve le même problème de focus avec un décalage. A noter que depuis que j'ai viré le flux à grosses images, je n'ai plus le problème, uniquement celui-ci.

**Comment by mlaily** [comment]
Ca me parait être un bug non ? Pas un changement optionnel qui nécessite une extension...

Ne serait il pas préférable de corriger le problème à la source, et charger les articles suivants lors du scroll infini plus tôt, avant d'arriver à la toute fin ?

**Comment by marienfressinaud** [comment]
Pas vraiment un bug non. Il ne s'agit que d'une histoire de fenêtre pas assez grande en fait. Charger les articles plus tôt n'est pas suffisant dans au moins deux autres cas : 
- Pas plus d'article
- Chargement automatique désactivé

Ma solution serait de rajouter autant de padding que nécessaire en bas de l'écran pour permettre à l'article de se trouver en haut de page. Dans un premier temps je corrigerai le problème dans une extension (notamment pour les versions <= 1.1.0), et si la solution fonctionne bien, ce sera intégré par défaut.

**Comment by mlaily** [comment]
Pour moi le premier cas n'est pas un problème : si il n'y a plus d'article et que le dernier est entièrement visible, même s'il est trop court, alors tout va bien.
Je ne suis pas sûr de comprednre le 2eme cas. Cela ramène au premier cas non ? (Fin de page réelle) Si c'est cela, alors je pense que ce n'est pas un problème non plus.

Il n'y a que pour le cas inital, ou on est en interrompu dans notre lecture continue par un article mal aligné au milieu du reste que cela me gêne...

**Comment by math-GH** [comment]
Is this issue still actual? Could someone please give an English translated summary?
