### ISSUE TITLE
Moving user data

### ISSUE THREAD

**Issue by marienfressinaud** [FreshRSS/FreshRSS#729]
I suggest to move all the user data from `./data` to `./data/users/name_user/`. I would move:
- configuration files (and renaming them in `config.php`)
- SQLite databases (and renaming them in `db.sqlite`)
- user log files (and renaming them in `log.log`?)

**Comment by aledeg** [comment]
Should we drop the folder log?

**Comment by marienfressinaud** [comment]
I have tested the update script:
- dev -> dev ok
- 0.8.1 -> 0.9.4 (dev) ok
- 0.9.3 -> 0.9.4 (dev) ok

I close this ticket, if you detect bugs related to the new user data location, please open a new ticket.
