### ISSUE TITLE
Improve configuration system

### ISSUE THREAD

**Issue by marienfressinaud** [FreshRSS/FreshRSS#730]
**Edit (configuration system implemented):**

I have finished my work on the new configuration system (I hope!). I planned to merge it tomorrow so I can continue to work on the extension system.

When it will be available, PLEASE REMEMBER TO UPDATE YOUR CONF FILE AFTER PULLING. Instructions have been given in https://github.com/FreshRSS/FreshRSS/commit/d3a93ea2905ae50a2365d293f9f3ef3e51bf5f30

Here are some explanations of the new system:
- The configuration is handled by only one generic class (`Minz_Configuration`). All is documented in the `./lib/Minz/Configuration.php` file.
- Current user configuration is accessible with `FreshRSS_Context::$user_conf`, system configuration with `FreshRSS_Context::$system_conf`.
- If you need to create a temporary configuration for another user, please use the lib function: `get_user_conf($username)`.
- If `FreshRSS_Context` is not initialized yet (so no access to generic user and system confs) you can use instead `Minz_Configuration::get('user')` and `Minz_Configuration::get('system')` to get the related configuration. You should use this `get()` method in `./lib/lib_rss.php` because we cannot know if `FreshRSS_Context` has been initialized in these functions.
- You can access conf parameters directly (e.g. `$allow = $conf->allow_anonymous;` and `$conf->allow_anonymous = $allow;`).
- Checks on the values are done at the setting time by the `FreshRSS_ConfigurationSetter` object (in `./app/Models/ConfigurationSetter.php`). To test a new param, only add the corresponding method. For instance, if you add in the system configuration a new parameter `timezone` and you want to test its value, add the following method:

``` php
// If param is "timezone", the "_timezone()" method is called automatically
// $data must be passed by reference.
private function _timezone(&$data, $value) {
    // It's just an example, don't do that at home!
    if ($value != 'Europe/Paris') {
        $value = 'Europe/Paris';
    }
    $data['timezone'] = $value;
}
```

I guess it was all I have to say :).

---

**First message (does not correspond to the current implementation):**

This suggestion is based on #729 and on #252 

When extensions will be available, it could be really great to give them the possibility to store their own configuration values. For now it's a bit difficult and we have two configuration systems (a global one managed by Minz and a user one managed by FRSS). I suggest to keep only one system (the Minz one) and improve it. This ticket is higly opened to discussions!

I imagine a sort of namespace system which could work as following.

First, we will need to initialize configuration system (in the FRSS FrontController). The idea is to map a namespace to a configuration file:

``` php
Minz_Configuration::init(array(
    'global.basic' => DATA_PATH . '/config.php',
    'global.extension.$1' => DATA_PATH . '/config.$1.php',
    'users.$1.basic' => DATA_PATH . '/users/$1/config.php',
    'users.$1.extension.$2' => DATA_PATH . '/users/$1/config.$2.php',
));
```

Next, to get the corresponding configuration. For the global configuration:

``` php
$namespace = 'global.basic';
$global_conf = Minz_Configuration::getConf($namespace);
$name_default_user = $global_conf->default_user;
```

For a user configuration:

``` php
$namespace = 'users.' . $user_name . '.basic';
$current_user_conf = Minz_Configuration::getConf($namespace);
$default_view = $current_user_conf->default_view;
```

For a system extension:

``` php
$namespace = 'global.extension.' . $name_extension;
…
```

For a user extension:

``` php
$namespace = 'users.' . $user_name . '.extension.' . $name_extension;
…
```

This system must be very generic so we will to forget about specifying keys one by one with their own getter and setter. Here is a very basic structure of my future `Minz_Configuration`:

``` php
class Minz_Configuration {
    // Initialize Minz_Configuration to map namespace to a conf file
    public static function init($map);
    // Return an instance of Minz_Configuration for the given $namespace
    public static function getConf($namespace);

    // Parse the file configuration
    private function parse();
    // Add or modify a conf key with a given value
    public function register($key, $value);
    // Return the current value for the given key
    public function get($key, $default=false);
    // Remove a key
    public function remove($key);
    // Save the conf file
    public function save();
}
```

What do you think? Is it too complicated? Have you some ideas to improve my suggestion?

**Comment by marienfressinaud** [comment]
I have began this work in a new branch (current status is not working good). I have changed some methods and ideas but I'm facing new problems:
- How to handle configuration param verifications? (i.e. check auth_type
  is a value from none, http_auth, persona or form)
- We must use `$conf = Minz_Configuration::get('system'); $general_conf = $conf->general;`
  to access global system configuration which is quite annoying. How to change that?

I have still to work on that and current code is not definitive at all!

**Comment by Alkarex** [comment]
Sorry for not being very active lately. This looks good, and I like the planned removal of specific setters/getters, which I hope will simplify the code (and hopefully may be an opportunity to improve performances too).

I think the parameters should be verified at least at write time. Then, I suggest using a lazy approach by not validating them at read time (leave it to the calling code), or validating them just-in-time (for the parameters accessed intensively, we should be careful not to call the validation too often).

In any case, a generic approach to validation would be to use a schema (for instance http://json-schema.org - I have not tried this one myself before - there is a PHP library).

**Comment by marienfressinaud** [comment]
Actually, I'm pretty sure performances are not better and I don't like to call `Minz_Configuration::get('system');` each time I need to get a system configuration parameter but I prefer that to the previous static methods. Maybe we can add the system configuration to the `Context` object such as the user configuration. So we can access them through `FreshRSS_Context::$user_conf` and `FreshRSS_Context::$system_conf`.

The most problematic point is the `general` array in the system configuration. To access parameters like `allow_anonymous` we have to do like that:

``` php
$conf = Minz_Configuration::get('system');
$allow = $conf->general['allow_anonymous'];
// instead of
$conf = Minz_Configuration::get('system');
$allow = $conf->allow_anonymous;
```

A solution could be to remove the `general` array but it means actual configurations will not be valid anymore and so the update script will need to take this in consideration (and I'm afraid it will not be easy).

I wanted to verify parameters only at the write time too but I'm not convinced by the json schema: I would like to test directly the PHP code. A solution could be to "inject" an (optional) "schema model" at the configuration registration time.

**Comment by marienfressinaud** [comment]
Please have a look to instructions from my previous commit to fix your config file if you use the `730-improve_configuration` branch (I have finally removed the general array).

**Comment by aledeg** [comment]
I was also thinking of the share object

**Comment by marienfressinaud** [comment]
I am currently rewriting the `FreshRSS_Share` object to have a better way to handle sharing. It will be easier to manipulate, especially for the extensions.

**Comment by marienfressinaud** [comment]
[Done](https://github.com/FreshRSS/FreshRSS/blob/0140448a562b97859be0b9a6e480e1f6aa4d1b1d/app/Models/Share.php)

**Comment by marienfressinaud** [comment]
I have finished my work on the new configuration system (I hope!). I planned to merge it tomorrow so I can continue to work on the extension system.

When it will be available, PLEASE REMEMBER TO UPDATE YOUR CONF FILE AFTER PULLING. Instructions have been given in https://github.com/FreshRSS/FreshRSS/commit/d3a93ea2905ae50a2365d293f9f3ef3e51bf5f30

Here are some explanations of the new system:
- The configuration is handled by only one generic class (`Minz_Configuration`). All is documented in the `./lib/Minz/Configuration.php` file.
- Current user configuration is accessible with `FreshRSS_Context::$user_conf`, system configuration with `FreshRSS_Context::$system_conf`.
- If you need to create a temporary configuration for another user, please use the lib function: `get_user_conf($username)`.
- If `FreshRSS_Context` is not initialized yet (so no access to generic user and system confs) you can use instead `Minz_Configuration::get('user')` and `Minz_Configuration::get('system')` to get the related configuration. You should use this `get()` method in `./lib/lib_rss.php` because we cannot know if `FreshRSS_Context` has been initialized in these functions.
- You can access conf parameters directly (e.g. `$allow = $conf->allow_anonymous;` and `$conf->allow_anonymous = $allow;`).
- Checks on the values are done at the setting time by the `FreshRSS_ConfigurationSetter` object (in `./app/Models/ConfigurationSetter.php`). To test a new param, only add the corresponding method. For instance, if you add in the system configuration a new parameter `timezone` and you want to test its value, add the following method:

``` php
// If param is "timezone", the "_timezone()" method is called automatically
// $data must be passed by reference.
private function _timezone(&$data, $value) {
    // It's just an example, don't do that at home!
    if ($value != 'Europe/Paris') {
        $value = 'Europe/Paris';
    }
    $data['timezone'] = $value;
}
```

I guess it was all I have to say :).

**Comment by marienfressinaud** [comment]
@Alwaysin and @Draky50110 > I know you are using the update system with the dev branch: please note it will not work this time! Some files will not be available and the configuration file have to be updated manually as explained in https://github.com/FreshRSS/FreshRSS/commit/d3a93ea2905ae50a2365d293f9f3ef3e51bf5f30

I'll work on that.

**Comment by marienfressinaud** [comment]
Update scripts are now ok but in the dev branch you still need to update the `./data/config.php` file by removing `general` array (but you have to keep values inside the array).

I now have to update the install script (totally forgot!).

**Comment by marienfressinaud** [comment]
All should work fine now. I cannot test the API actually but I'm quite confident in the fact it will work.

I close this ticket, if you detect bugs please open new ones.

**Comment by Alwaysin** [comment]
Thanks for the warning!
Just tried the update and it worked : 
- launched update from the interface (got an "Error 404 - Not found" page but the update worked)
- went to data/config.php and deleted lines 3 (**'general' =>**), 4 (**array (**) and 15 (**),**)
- went to the interface, and tadaaa! Working.

(I precise what I've done because I had forgotten line 15 ^^')

I do not have the knowledge to understand what you've done but I see it was a lot of work. So thanks for that!

Also, please note I've just tested the API and it works well, as you expected.

EDIT : I do not have the "limits" array, but I guess it is not important.

**Comment by marienfressinaud** [comment]
It's not a problem if limits array is not present: default values (from `./data/config.default.php`) are considered instead.

**Comment by Draky50110** [comment]
Help.

I'm completely fucked :( 

Here is my config.php renamed to config.default.php in data/ : XXXX

But now it displays "404/Error".

---

After tries : ok now, had to add the "limits" array and rename config.php to config.default.php

**Comment by Draky50110** [comment]
By the way, what should be the correct name of the config file now ?
config.default.php ?
config.php ?
Uername.config.php ?

**Comment by marienfressinaud** [comment]
You should NOT touch to the `config.default.php` file. The correct file to use is [this one](https://github.com/FreshRSS/FreshRSS/blob/dev/data/config.default.php) (if yours is different, download the file). You just had to keep your `config.php` file and follow instructions given above (those of @Alwaysin are very precise).

There are four kind of config files:
- `./data/config.default.php` contains default values for system config
- `./data/config.php` contains your specific values. If one parameter is not present in this file, the value is taken from the default file.
- `./data/users/_/config.default.php` contains default values for user configurations
- `./data/users/*/config.php` contains the user specific values

**Comment by Draky50110** [comment]
Ok, I understand.
So downloaded the correct config.default.php :) and corrected the config.php file.
Seems to work.

@marienfressinaud can you confirm that my config.php is definitively correct ?
http://gilles.wittezaele.fr/paste/?ab0fa564a733100e#nTxOFKa8RemEJD+SjJ0Wpy7UkmwHeF5IHXxkLXOJqLw

**Comment by marienfressinaud** [comment]
It seems good ;)

**Comment by Draky50110** [comment]
Nice :)
Thanks for the work ;)
