### ISSUE TITLE
Give possibility to manipulate database easily

### ISSUE THREAD

**Issue by marienfressinaud** [FreshRSS/FreshRSS#732]
We need an abstract way to add / remove / update tables or columns. It will be helpful for repairing database during an update but also for extensions which can need to update the database schema.

It will begin to look like an ORM system but it's a very interesting feature for developers!

**Comment by marienfressinaud** [comment]
In fact, I would like to refactor the DAO level before implementing such a system. I'm really not fan of the actual implementation. Since it is a big and long work, this ticket has been planned after the 1.0 release.

**Comment by aledeg** [comment]
Agreed.
I think the way of filtering entries is a nightmare to maintain for instance. That's why I add few things yesterday in the context object.

**Comment by marienfressinaud** [comment]
I'm no longer sure that is really needed. SQL is not that complicated, and it is more powerful than an abstraction. It would give a more integrated and nice interface to the database, but I would no longer say it's "important". At least, it is too complicated to add an ORM now.
