### ISSUE TITLE
Unhide password in setup

### ISSUE THREAD

**Issue by Phyks** [FreshRSS/FreshRSS#734]
Hi,

When clicking the "unhide password" button during initial setup, there seems to be no way to hide it again. This can be a bit surprising for the end user.

EDIT : My bad, it's hidden again on focus / unfocus event on the field. But this is not the initial way I was thinking it was working. I keep the issue open so that you can be aware that some users might get lost with this, but feel free to close as it's not a bug.

**Comment by marienfressinaud** [comment]
Fixed.
