### ISSUE TITLE
Articles lus rapidement = articles marqués comme lus mais ne disparaissent pas

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/FreshRSS#738]
Bonjour,

Avec l'option "Cacher les articles après lecture" activée, en ouvrant les articles très rapidement, ceux-ci sont marqués comme lus, ce qui est normal, mais ne disparaissent pas, ce qui n'est pas normal.

Bon je suis d'accord que ce n'est pas forcément quelque chose que l'on devrait rencontrer souvent, mais peut-être qu'il n'est question que d'un petit truc bête comme un bout de code à remonter pour qu'il soit éxecuté plus vite ou un truc dans le genre !

**Comment by Draky50110** [comment]
Ce n'est pas un souci côté hébergement ?
Genre tu vas plus vite que les données transmises ?
Moi avec une connexion pourrie au travail, si je clique sur l'icone de mise en "lu" (enveloppe rouge en début de flux), si je vais trop vite ça ne prend pas en compte car ma connexion n'envoie pas l'info assez vite.

**Comment by marienfressinaud** [comment]
Ce n'est pas tant un problème de l'hébergeur que de FRSS : si la connexion est lente, les requêtes peuvent effectivement échouer. Désormais il devrait y avoir un message indiquant ce genre de problème. 

Par contre dans le cas où l'article est bien marqué comme lu, il doit aussi disparaître. J'avoue que je ne sais pas trop quoi faire de ce ticket : ce n'est pas moi qui me suis occupé de cette fonctionnalité (ping @aledeg) et je ne la trouve pas particulièrement critique. Néanmoins elle reste génante. Je considère que si c'est corrigé pour la 1.0 tant mieux, sinon tant pis, ça attendra encore un peu ;).

**Comment by aledeg** [comment]
J'arrive à reproduire le comportement mais je ne sais pas comment le corriger pour le moment. Je regarde une méthode à peu près intelligente pour faire ça.

**Comment by marienfressinaud** [comment]
Devrait avoir été corrigé par #794

**Comment by Alwaysin** [comment]
Merci ! J'aurais aimé vérifier mais FreshRSS me dit qu'il n'y a pas d'update ?

"Your current version of FreshRSS is the 1.2-dev.
Last verification: February 17th 2015 at 20:53
Damn! No update to apply"

C'était le 3 février la dernière fois que j'avais update.

**Comment by marienfressinaud** [comment]
Désolé, j'avais oublié de mettre à jour update.freshrss.org. Mais en fait je me rends compte que le problème est toujours là (dans une moindre mesure par contre). Je rouvre le ticket.

**Comment by aledeg** [comment]
Dans quel contexte le problème apparait encore? J'aimerais un peu plus d'informations pour essayer de reproduire le problème.

**Comment by Alwaysin** [comment]
Pour moi le problème est corrigé, je n'ai pas réussi à le reproduire même en allant exagérement très vite.

**Comment by aledeg** [comment]
Tant mieux!

**Comment by marienfressinaud** [comment]
Le problème survient chez moi en allant spécialement très vite. Ce n'est absolument pas dramatique et en fait je me dis qu'on peut refermer ce ticket, c'est le genre de choses qui pourrait être corrigé durant une potentielle refonte du JavaScript.
