### ISSUE TITLE
Prévenir utilisateur quand changement non validé dans la configuration ou enlever bouton "valider"

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/FreshRSS#739]
Prenons pour exemple l'écran lecture. Selon les tailles d'écran, on ne voit pas le bouton en bas "valider". On pourrait donc penser qu'il n'y en a pas ou en tout cas, lorsqu'un changement est fait, oublier de scroller et de valider, et cliquer directement sur le logo de FreshRSS en haut à gauche pour revenir au flux et voir le changement par exemple. Sauf que frustration : le changement n'a pas été fait.

Je propose donc de prévenir l'utilisateur qui a fait un changement mais ne l'a pas validé, lorsqu'il change de page. Il me semble que c'est assez courant et je l'ai déjà vu sur de "gros sites".
Après on peut aller plus loin et dire que chaque changement se fait dès qu'il est actionné par l'utilisateur, dès qu'on coche ou déoche une case par exemple.

**Comment by marienfressinaud** [comment]
Je me suis effectivement fait plusieurs fois cette remarque. La deuxième solution me paraît plus sympathique, néanmoins plus compliqué à mettre en place (comment mettre en place l'annulation des actions par exemple ?). Intéressant mais pas pour tout de suite néanmoins.

**Comment by aledeg** [comment]
J'ai mis en place un système d'alerte au moment où l'utilisateur quitte la page. C'est la méthode la plus simple à mettre en place. En plus, je ne suis pas sur que la seconde solution avancée soit judicieuse, et ce pour la même raison avancée par @marienfressinaud.

**Comment by aledeg** [comment]
@Alwaysin time to test the dev branch :)

**Comment by Alwaysin** [comment]
Great! Thanks for that :)

It appears not to be working when adding/deleting sharing options, but apart this all seems OK!

**Comment by aledeg** [comment]
That's normal, since I haven't done anything to prevent that :). I might do it in the future but it is a bit more complicated. We'll see!

**Comment by Alwaysin** [comment]
Ok. Then maybe we can close the ticket?

For me it's OK :)

**Comment by Alwaysin** [comment]
Hmmm this function is not working anymore, is it?

**Comment by Alkarex** [comment]
@Alwaysin It works for me. Tested with Firefox on the current /dev. Can you tell a bit more about your test?

**Comment by Alwaysin** [comment]
It indeed works with Firefox, but not with Chrome. But I'm on 41 (Ubuntu repo), I'll try with the latest (43) later.

**Comment by Alkarex** [comment]
@aledeg Could you have a chance to look at it?

**Comment by Alwaysin** [comment]
Same with Chrome 43!

**Comment by Alkarex** [comment]
@Alwaysin Could you test my patch?

**Comment by Alwaysin** [comment]
Sure!

It appears not to be working after a CTRL+F5 : same behaviour. Same when logging from private window :(

**Comment by Alkarex** [comment]
Could you please double-check that the source code of main.js received by your browser contains the patch? (The patch is not yet merged in the /dev branch)

**Comment by Alwaysin** [comment]
EDIT : so sorry... I thought we were talking about dancing titles in Chrome.

I paid a little bit more attention now and indeed your patch resolves the issue stated in this thread ^^'

Thanks :D

**Comment by Alkarex** [comment]
Ok, thanks for testing. Now merged in /dev

**Comment by aledeg** [comment]
@Alkarex sorry I wasn't available to verify the behavior.

**Comment by Alkarex** [comment]
@aledeg No worries. I hope it works now :-)
