### ISSUE TITLE
Favicon supprimés après màj dev ?

### ISSUE THREAD

**Issue by Draky50110** [FreshRSS/FreshRSS#743]
Salut

Je viens de mettre à jour ma version "dev" et ça s'est fini en 404 / erreur et quand je retourne sur la page principale, plus de favicon, y'a juste un favicon bleu pour tous les flux...

Une idée du souci ?

**Comment by Draky50110** [comment]
Bon, après mise à jour des flux, ça revient, mais pas tous avec le bon favicon o.O

**Comment by Alwaysin** [comment]
As-tu bien supprimé la ligne 15 de ton fichier de configuration ?

https://github.com/FreshRSS/FreshRSS/issues/730#issuecomment-69168732

J'avais eu pareil et il me semble qu'en supprimant cette ligne c'est revenu.

**Comment by marienfressinaud** [comment]
Les favicons ne sont pas liés du tout à #730. En revanche j'ai changé la méthode de récupération des favicons et il est possible que le cache des précédents favicons soit arrivé à expiration. Quand tu dis que ce ne sont pas les bons favicons, c'est qu'ils sont inversés avec d'autres flux ou c'est complétement autre chose ?

**Comment by Draky50110** [comment]
Finalement, après le cafouillage du config.php c'est bon maintenant.
Peut-être un souci de cache.
