### ISSUE TITLE
FRSS cannot find a url with two slashes

### ISSUE THREAD

**Issue by marienfressinaud** [FreshRSS/FreshRSS#744]
For instance, http://marienfressinaud.fr//feed.php?rss cannot be added. It may be a server configuration problem since http://simplepie.org/demo/ find the feed.

**Comment by Alkarex** [comment]
Could be related to
https://github.com/simplepie/simplepie/pull/371
https://github.com/simplepie/simplepie/pull/367
https://github.com/simplepie/simplepie/issues/366
If you look at the log of SimplePie requests (https://github.com/FreshRSS/FreshRSS/pull/815), in my case it tries to query `http://?#`

**Comment by Alkarex** [comment]
Same bug report in SimplePie https://github.com/simplepie/simplepie/issues/257

**Comment by marienfressinaud** [comment]
I think this is no longer a problem, I cannot reproduce it.
