### ISSUE TITLE
Options pas prises en compte

### ISSUE THREAD

**Issue by Draky50110** [FreshRSS/FreshRSS#746]
Salut

J'ai un souci depuis la grosse mise à jour #730 !

J'ai mes options "réglées" comme il faut.
Mais quand je me rend sur mon FRSS après "un certain temps", les options ne sont plus réglées comme prévues, jusqu'à ce que je reclique sur le mot FRSS en haut à gauche.

En gros, je me tape l'anglais et un affichage qui ne correspond pas, de plus les raccourcis clavier sont ceux par défaut au lieu de cuex que j'ai réglé...

**Comment by Alwaysin** [comment]
Met à jour pour avoir #745 et ça devrait être bon !

**Comment by Draky50110** [comment]
Merci !
