### ISSUE TITLE
API - user does not exist in configuration

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/FreshRSS#747]
Bonjour,

Sur une installation toute fraîche de FreshRSS j'ai un problème pour accéder à l'API. L'accès a bien été activé, le mot de passe créé, et pourtant News+ me jette avec une erreur 401 (Authentication fails). J'ai bien vérifié que l'utilisateur et le mot de passe sont bons et api/greader.php/check%2Fcompatibility est à PASS.

Logs Apache : 
88.120.xx.xx - - [11/Jan/2015:23:28:33 +0100] "POST /api/greader.php/accounts/ClientLogin HTTP/1.1" 200 609 "-" "gzip"
88.120.xx.xx - - [11/Jan/2015:23:28:33 +0100] "GET /api/greader.php/reader/api/0/tag/list?client=newsplus&output=json&ck=1421034313355 HTTP/1.1" 401 574 "-" "gzip"

Logs FreshRSS : 
[Sun, 11 Jan 2015 23:28:33 +0100] [warning] --- user does not exist in configuration

Je manque probablement une étape de configuration... je ne vois pas laquelle ?

EDIT : je suis passé d'Apache 2.2.22 (sous Debian) à 2.4.10 (sous Ubuntu), possible d'un problème à ce niveau ?

**Comment by marienfressinaud** [comment]
Je ne pense pas que ça vienne d'un problème de version Apache, il semble juste ne pas trouver l'utilisateur (problème de session peut-être). Je regarde ça mais je n'ai pas eu de soucis avec EasyRSS

**Comment by marienfressinaud** [comment]
Ça marche aussi pour moi avec News+ :s as-tu toujours le problème et si oui as-tu des informations dans data/users/_/log_api.txt ?

**Comment by Alwaysin** [comment]
Oui j'ai toujours le problème. Je viens de réessayer et j'ai ça qui se génère dans les logs :

```
User =>
unauthorized()
Array
(
    [date] => 2015-01-13T13:56:45+01:00
    [headers] => Array
        (
            [Authorization] => GoogleLogin auth=alwaysin/d6adb0a543067d81019e12535813165b23e86047
            [User-agent] => gzip
            [Accept-Encoding] => gzip
            [Host] => freshrss.alwaysin.fr
            [Connection] => Keep-Alive
        )

    [_SERVER] => Array
        (
            [HTTP_USER_AGENT] => gzip
            [HTTP_ACCEPT_ENCODING] => gzip
            [HTTP_HOST] => freshrss.alwaysin.fr
            [HTTP_CONNECTION] => Keep-Alive
            [PATH] => /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
            [SERVER_SIGNATURE] => <address>Apache/2.4.10 (Ubuntu) Server at freshrss.alwaysin.fr Port 80</address>

            [SERVER_SOFTWARE] => Apache/2.4.10 (Ubuntu)
            [SERVER_NAME] => freshrss.alwaysin.fr
            [SERVER_ADDR] => 62.210.69.103
            [SERVER_PORT] => 80
            [REMOTE_ADDR] => 94.126.119.20
            [DOCUMENT_ROOT] => /var/www/freshrss/p/
            [REQUEST_SCHEME] => http
            [CONTEXT_PREFIX] =>
            [CONTEXT_DOCUMENT_ROOT] => /var/www/freshrss/p/
            [SERVER_ADMIN] => [no address given]
            [SCRIPT_FILENAME] => /var/www/freshrss/p/api/greader.php
            [REMOTE_PORT] => 56827
            [GATEWAY_INTERFACE] => CGI/1.1
            [SERVER_PROTOCOL] => HTTP/1.1
            [REQUEST_METHOD] => GET
            [QUERY_STRING] => client=newsplus&output=json&ck=1421153803114
            [REQUEST_URI] => /api/greader.php/reader/api/0/tag/list?client=newsplus&output=json&ck=1421153803114
            [SCRIPT_NAME] => /api/greader.php
            [PATH_INFO] => /reader/api/0/tag/list
            [PATH_TRANSLATED] => /var/www/freshrss/p/reader/api/0/tag/list
            [PHP_SELF] => /api/greader.php/reader/api/0/tag/list
            [REQUEST_TIME_FLOAT] => 1421153805.979
            [REQUEST_TIME] => 1421153805
        )

    [_GET] => Array
        (
            [client] => newsplus
            [output] => json
            [ck] => 1421153803114
        )

    [_POST] => Array
        (
        )

    [_COOKIE] => Array
        (
        )

    [INPUT] =>
```

**Comment by marienfressinaud** [comment]
Je viens d'ajouter une ligne de log là où je pense qu'il y a un problème. Pourrais-tu mettre à jour (dev) et réessayer voir si c'est bien l'endroit que je pense. Normalement une ligne `Invalid configuration API file for user alwaysin` devrait apparaître dans api_log.txt.

**Comment by Alwaysin** [comment]
J'ai toujours : 

[Tue, 13 Jan 2015 14:29:44 +0100] [warning] --- user does not exist in configuration

dans data/users/_/log.txt 

Et les mêmes liignes dans data/users/_/log_api.txt

**Comment by marienfressinaud** [comment]
Arf, je sais pas trop :s Je viens de repérer un bug : il est possible que tu aies un fichier `./data/users/log.txt` aussi.

@Alkarex a peut-être plus d'idées mais il n'est pas trop dispo en ce moment malheureusement.

**Comment by marienfressinaud** [comment]
J'ai encore ajouté une ligne que j'avais oublié. Je suis (quasiment) sûr que tu dois avoir un truc soit dans `./data/users/log.txt`, soit `./data/users/_/log.txt`

**Comment by marienfressinaud** [comment]
Ah non ! Au temps pour moi j'ai trouvé le bug, je corrige immédiatement !

**Comment by Alwaysin** [comment]
Oui j'ai un /data/users/log.txt mais qui ne contient pas d'infos récentes.

Y'a des logs un peu partout d'ailleurs, j'ai du mal à m'y repérer lol

Ok j'essaierai quand je pourrais faire une autre maj, je suis bloqué par les une heure là :(

**Comment by Alkarex** [comment]
Je veux bien regarder, si le problème persiste

**Comment by Alwaysin** [comment]
Maintenant j'ai : 

[Tue, 13 Jan 2015 15:25:31 +0100] [warning] --- Invalid API authorisation for user alwaysin: d6adb0a543067d81019e12535813165b23e86047

(Merci Alkarex :D)

**Comment by marienfressinaud** [comment]
Tu as mis à jour trop vite, je viens de finir de corriger :p Ça doit marcher maintenant.

Merci @Alkarex mais c'était une erreur de ma part (introduit par #730) : j'ai supprimé le `$conf->user` et j'ai oublié de modifier comme il faut l'API. Le problème venait des confs complètement à jour qui ne comportaient plus le paramètre `user`. Ma conf à moi n'était pas totalement à jour et possédait encore ce paramètre ;). Maintenant le nom utilisateur est récupéré via une variable de session plutôt que via la conf.

@Alwaysin si tu veux remettre à jour dans l'heure il te suffit de supprimer le fichier `./data/last_update.txt`, ça n'a aucune autre incidence :)

**Comment by Alwaysin** [comment]
Merciiiiiiiii !! J'ai dû supprimer et remettre le compte dans News+ et ça marche (j'ai aussi re-validé les paramètres API de FreshRSS mais je ne sais pas si c'était nécessaire).

Maintenant ça fonctionne :)

**Comment by Alwaysin** [comment]
Les problèmes au niveau de l'API ne semblent pas définitivement réglés : les articles ne sont plus marqués comme lus.

**Comment by marienfressinaud** [comment]
Arf oui je confirme :( Je regarde ça de plus près.

**Comment by marienfressinaud** [comment]
(au passage j'ai bossé sur une extension aujourd'hui pour implémenter l'API de TTRSS et ça commence à rendre pas mal :))

**Comment by Alwaysin** [comment]
Qu'est-ce que cela va apporter ? Ce sera + simple à utiliser et on pourra se servir des applis qui sont conçues pour TTRSS c'est ça ?

Ca peut être pas mal :)

**Comment by marienfressinaud** [comment]
Ça apportera qu'il y aura deux API possibles donc oui, possibilité d'utiliser les applis conçues pour TTRSS :).

J'ai regardé pour le problème des articles marqués comme lus, ce qui est surprenant c'est que, à priori, cette partie ne devrait pas avoir changé. Si j'ai bien compris ce qu'il se passe, pour marquer un article comme lu on passe dans la fonction `editTag()` (@Alkarex tu peux me confirmer ?). Ça c'est bon mais je vois pas pourquoi ça marque pas comme lu. Je vais approfondir mes recherches pour comprendre.

**Comment by Alkarex** [comment]
Vérifier d'abord si ce n'est pas ce bug connu de News+ https://github.com/noinnion/newsplus/issues/84#issuecomment-57834632

**Comment by marienfressinaud** [comment]
Ah j'ai trouvé une piste très prometteuse : dans les logs `./data/users/_/log.txt` j'ai un joli "SQL error markRead 1: syntax error".

**Comment by marienfressinaud** [comment]
Ça m'agace : le problème vient vraisemblablement de https://github.com/FreshRSS/FreshRSS/blob/dev/app/Models/EntryDAOSQLite.php#L63 et donc de la requête SQL (sqlite seulement, il faudrait tester sur un MariaDB/MySQL) mais :
1. Pourquoi ça marchait avant et que ça ne marche plus maintenant ?
2. Pourquoi le problème ne se produit qu'au niveau de l'API ? (un préfixe de table qui viendrait casser la requête ? mouais…)
3. Pourquoi l'erreur est logguée dans `./data/users/_/log.txt` et non pas le fichier utilisateur ? On dirait qu'il ne trouve pas le nom d'utilisateur actuel mais ça devrait poser d'autres problèmes dans ce cas-là (et surtout ça ne devrait pas arriver jusque-là dans le processus !).

Là je n'ai pas les moyens de tester plus que ça (jonglage de téléphones et connexion Internet pas pratique) mais je considère que ça bloque la sortie de la 0.9.4 pour le moment.

**Comment by Alwaysin** [comment]
@Alkarex je ne pense pas que ce soit le bug de News+ décrit car ça marchait bien avant avec un autre serveur FreshRSS, mais pourquoi pas ; à tester sur EasyRSS mais je crois que @marienfressinaud l'a déjà fait ?

Moi dans les logs j'ai ça, dans le même fichier que toi : 

[Wed, 14 Jan 2015 19:39:58 +0100] [error] --- SQL error markRead: Table 'freshrss.freshrss___entry' doesn't exist
[Wed, 14 Jan 2015 19:39:58 +0100] [error] --- SQL error markRead: Table 'freshrss.freshrss___entry' doesn't exist

A chaque fois en deux exemplaires.

Ha et je n'utilise pas sqlite mais MySQL.

**Comment by marienfressinaud** [comment]
Ah bah oui je vois ça, c'est bien un problème de préfixe de table et plus particulièrement de nom utilisateur ! Merci pour les logs :)

**Comment by Alwaysin** [comment]
Pas de soucis ! C'était bien lié à 730 alors ?

**Comment by marienfressinaud** [comment]
Oh punaise >< Oui et j'ai honte… La correction arrive prochainement. Désolé pour ça !

**Comment by Alwaysin** [comment]
Pas de quoi avoir honte, c'est un gros boulot que tu as fait, un petit side-effect c'est normal :)

**Comment by marienfressinaud** [comment]
Ouais mais quand même :p En tout cas ça explique pas mal de choses ;) En fait les appels à `token()` et `checkToken()` modifiaient la valeur du nom utilisateur courant donc l'API ne trouvait plus ses petits. Corrigé normalement (je te laisse tester avant de clore le ticket).

**Comment by Alwaysin** [comment]
Affirmatif !

Merci :)

**Comment by marienfressinaud** [comment]
Au passage, l'API TTRSS est dispo en tant qu'extension : https://github.com/FreshRSS/Extensions/tree/master/xExtension-TTRSS_API

Elle n'est pas encore terminée, il y a plein de trucs que je n'ai pas fait mais elle est fonctionnelle pour des applis comme FeedSpider sur FirefoxOS. Surtout ça m'a permis de mieux comprendre le système d'API de Google Reader ^^.

**Comment by Alwaysin** [comment]
Cool ! J'ai voulu tester mais l'extension n'apparaît pas dans la liste sur l'interface. J'ai bien changé les droits pourtant :/

**Comment by marienfressinaud** [comment]
Oui normal, faut mettre à jour FRSS (oui ça évolue vite :p). J'ai fait une petite amélioration dans l'API extension.

**Comment by Alwaysin** [comment]
Oh la la ça va trop vite, j'ai du mal à suivre ^^

Bon ça ne marche pas j'ai des erreurs qui se génèrent.
J'ouvre un nouveau ticket ? Ou j'attends que tu ai finis l'implémentation ? ^^

**Comment by marienfressinaud** [comment]
Je préférerais que tu attendes, là c'est vraiment à titre expérimental que j'ai ajouté ça ;) Note : il faut que le serveur ait les droits d'écriture sur le répertoire `./p/api`. Puis y a un problème lors de la mise à jour : faut désactiver / réactiver l'extension :D
