### ISSUE TITLE
FreshRSS stops working correctly if an ajax request results in a 403

### ISSUE THREAD

**Issue by mlaily** [FreshRSS/FreshRSS#751]
I have mod_evasive installed to prevent my web server from being DoSed too easily : if someone issue too many requests, they get a 403 for a short while.

If I keep pressing j or k to navigate through the articles, I end up triggering the DoS protection, and the "mark as read" ajax request fails with a 403 Forbidden error.

The problem is, this 403 error is probably not handled by FreshRSS, and it prevents any more ajax requests from working at all.

All the buttons depending on ajax then become completely useless until I refresh the whole page.

**Comment by marienfressinaud** [comment]
I can't avoid your 403 error but now, if a request fails a feedback is given and it should not lock the interface.

**Comment by mlaily** [comment]
Just what I was hoping for! thanks.
(I'll wait for the change to make it to the beta branch before I test it though)
