### ISSUE TITLE
Branche dev, mise à jour, plus d'accès au fichier config de l'user.

### ISSUE THREAD

**Issue by iGormilhit** [FreshRSS/FreshRSS#752]
Bonjour,

Je suis sur la branch dev. J'ai vu passer le billet de blog de Dada et j'ai donc voulu mettre à jour avec un git pull.
Depuis, mon interface est en anglais et tous mes paramètres personnels ne sont plus en vigeur. Si je cherche à enregistrer de nouveau paramètres, rien ne se passe. Tout se passe comme s'il n'était plus possible de lire ou d'écrire dans le fichier igor_user.php, ou en tout cas c'est le sentiment que j'ai.

Si je cherche à atteindre FreshRSS depuis un autre navigateur, où je ne suis pas déjà connecté donc, je découvre un FreshRSS totalement vide, sans login.

Le fichier log de mon utilisateur n'est pas très parlant, rien à signaler depuis le 20 décembre 2014.

J'ai un backup de l'install, c'est pas trop le problème, mais je me demandais ce que j'avais bien pu faire de faux...

edit : j'aurais dû commencer par là. Il y a pas mal d'erreur dans le apache error.log : https://id-libre.org/ZeroBin/?0ca1c50d53e892e9#khAx/REBVr5//hU7RiyyZ6IHEO66vJCwWmXfbYhGJX0=

**Comment by marienfressinaud** [comment]
Ça c'est parce que tu utilises la version de dev ! Il y a eu de gros changements qui ne peuvent être automatisés que dans le script de mise à jour. J'aimerais éviter ce genre de tickets par les personnes qui utilisent la version de dev parce que j'ai mis en garde contre son utilisation. Je te demanderai au moins de suivre [le flux RSS des commits de la dev](https://github.com/FreshRSS/FreshRSS/commits/dev.atom) : lorsqu'il y a des choses cassées je préviens par un "Breaking feature" dans le commit avec les explications de comment réparer. Le mieux restant tout de même d'utiliser la version bêta vu que j'assure un minimum de support derrière.

Deux choses à corriger donc : 
1. Les fichiers utilisateurs ont été déplacés : voir https://github.com/FreshRSS/FreshRSS/commit/b5bee8560345e4123432a8bd3bcd63b938549ef9
2. Il faut mettre à jour le fichier `./data/config.php` : voir https://github.com/FreshRSS/FreshRSS/commit/d3a93ea2905ae50a2365d293f9f3ef3e51bf5f30

**Comment by iGormilhit** [comment]
Ok. Merci beaucoup pour ta réponse. Je vais mieux m'informer désormais. Vraiment désolé pour le dérangement.
