### ISSUE TITLE
StickyFeeds extension : long feed name break the left column's width

### ISSUE THREAD

**Issue by mlaily** [FreshRSS/FreshRSS#753]
I have StickyFeeds enabled and it works great, except I have some feeds with a very long name, and it breaks FreshRSS:
![clipboard-1](https://cloud.githubusercontent.com/assets/1535823/5788110/cfb3cb44-9e24-11e4-9043-d6103b181ef5.png)

(P.S. I'm not sure where this issue should be reported, but as the extension's bug tracker is almost empty, I went with the FreshRSS one...)

**Comment by mlaily** [comment]
I think an acceptable solution would be either to set a fixed width to the column, so the long names would never be visible (and maybe add a title/popup on the names?), or to fix the column's width most of the time but to allow it to grow to its desired size when the mouse is over it.
What do you think?

**Comment by marienfressinaud** [comment]
Problem is already known (see #697 last comments) but the conversation continues here.

Your suggestion seems good but… this is already the case! Since column width can change in the different themes, width of `#aside_feed .tree` is set in JavaScript with width of `#aside_feed`… but it seems to not work correctly (however it works fine for me! I should test with more browsers).

BTW, do you know you can see C&H comics directly in FRSS by setting the "CSS selector" at `#main-comic` in advanced settings of the C&H feed? :)

**Comment by Draky50110** [comment]
@yaurthek Ok with the first one :) : fixed width + mouse hover = name but width should be a % on a screen size detection maybe...

**Comment by marienfressinaud** [comment]
My bad, it is the `min-width` which is set. Problem probably comes from this but I used this because a mobile problem. Actually, I cannot manage to reproduce the bug so try with this ;)

Edit: forget me: I CAN reproduce the mobile problem so witdh size is not the solution

**Comment by mlaily** [comment]
I'm using Firefox (ehm, [Waterfox](https://www.waterfoxproject.org/) actually, but it should not matter). 

I tried replacing `min-width` with just `width` and it seems to work. I don't see any issue with the responsive design (is that what you meant by mobile?) : the menu folds correctly when I resize my browser. Any thought?

(And thanks for the tip using the css selector, it's awesome! But it only works on new articles? Those already in the cache are not refreshed with the new setting?)

**Comment by marienfressinaud** [comment]
There is a problem if you follow these steps:
1. Resize the window so the aside disappear
2. Reload the page (aside must be closed!)
3. Open the aside: categories don't appear because at the reload `#aside_feed` width was 0.

I have another and probably better idea ;)

**Comment by marienfressinaud** [comment]
It should work better now. I changed a lot of things but finally I found the `window.matchMedia()` function in JavaScript which helped me a lot to fix mobile view. Tell me if it's work as expected (you have to download again the extension)

**Comment by Draky50110** [comment]
Nearly perfect.

Problem : the 3 buttons at the bottom of the cat frame are hiding the bottom of the scroll bar.
Of course, you can scroll the bar down with the mouse but you can't click on the bottom arrow :D

Solution : reduce the "3 icons" to permit to see the full scrollbar.

**Comment by mlaily** [comment]
Yep. Long feed names no longer break the left column width, but something is wrong with the height of the column, the 3 button at the bottom, and the scrollbar, especially when resizing the browser window...

**Comment by marienfressinaud** [comment]
Wow, strange, I fixed that earlier. I'll have a look.

**Comment by marienfressinaud** [comment]
It might be fixed. I hope. _sigh_

**Comment by mlaily** [comment]
The 3 buttons at the bottom are always on top but the feed list doesn't resize properly when the browser windows is resized. :/

**Comment by marienfressinaud** [comment]
I don't plan to fix aside at the window resizing: that's probably not something you do regularly. Eventually on mobile but sticky feed don't apply.

Can you do a screenshot when the scrollbar is at the bottom? I can't reproduce your problem...

**Comment by mlaily** [comment]
The only problem I noticed is when I resize the browser window.
If you don't want to fix it (I can understand), then everything is alright!

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/1172
