### ISSUE TITLE
Facebook's RSSes aren't displayed correctly

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#754]
One picture is worth a thousand words :

![frss](https://cloud.githubusercontent.com/assets/3429231/5789235/8f046156-9e62-11e4-94f2-030cb8c7db89.png)

Here is the RSS that causes problems :

https://www.facebook.com/feeds/page.php?format=rss20&id=166081103477984

**Comment by aledeg** [comment]
It looks like an encoding problem. When I open the feed with Firefox, I have the same problem. I think it is not specific to FRSS.
I checked also the feed on the W3C validator and it is not valid. It is enough valid to be parsed though.

**Comment by marienfressinaud** [comment]
> It is enough valid to be parsed though.

Yes and SimplePie demo and Liferea work great: that's why I ask @AugierLe42e to open a ticket. I didn't inspect code deeper but it could be a problem from FRSS. By the way, this problem reminds me another but I cannot find it in ticket archive.

**Comment by Alwaysin** [comment]
Maybe this one : #661 ? It is still opened.

**Comment by Alkarex** [comment]
This RSS2 feed uses a [CDATA container](http://en.wikipedia.org/wiki/CDATA#Issues_with_encoding) together with HTML-entities in the `<title>` section which is [supposed to be text-only](http://validator.w3.org/feed/docs/warning/ContainsHTML.html) (see comment below), not HTML. As far as I can see, the result in FrehsRSS is as per the specifications (XML, RSS2).
Note however that I cannot immediately find an official reference stating explicitly that `<title>` is text-only and not HTML (except the note from the W3C validator, which is already quite a good reference). This is what I lack to be sure.
If `<title>` is indeed text-only, then I do not believe it is possible to support this feed without breaking other valid feeds and without doing an exception for Facebook.

There is also the Atom 1.0 version of the same feed: https://www.facebook.com/feeds/page.php?format=atom10&id=166081103477984
In this case it is clear, and the Facebook Atom feed is wrong: http://tools.ietf.org/html/rfc4287#section-3.1.1

> If the "type" attribute is not provided, Atom Processors MUST behave as though it were present with a value of "text"

**Comment by ghost** [comment]
Here is another one causing problem :

http://www.atterres.org/rss.xml

**Comment by Alkarex** [comment]
Similar problem with http://www.atterres.org/rss.xml : among the many errors, this feed is using HTML in `<title>`. http://validator.w3.org/feed/check.cgi?url=http://www.atterres.org/rss.xml

**Comment by ghost** [comment]
Would this be difficult to detect and sanitize the title ? E.g by using regexp ?

**Comment by Alkarex** [comment]
@AugierLe42e The problem would be to avoid breaking other valid feeds (it is a valid use-case to want to write e.g. `&amp;` in a title, and this would not be possible anymore if we blindly decoded everything). Currently, what I am lacking is an authoritative reference of whether RSS2's `<title>` is plain-text or HTML, in addition to what is told by the validator.

**Comment by ghost** [comment]
Any news from this ? This is really annoying.

**Comment by Alkarex** [comment]
I will look at it. For reference, it relates to SIMPLEPIE_CONSTRUCT_MAYBE_HTML in SimplePie https://github.com/FreshRSS/FreshRSS/blob/beta/lib/SimplePie/SimplePie/Sanitize.php#L250

**Comment by Alkarex** [comment]
Here is a patch: https://github.com/FreshRSS/FreshRSS/issues/813
Please give it a try.
We will have to check with many feeds to ensure that this change has not broken any previously-supported valid feed.

**Comment by ghost** [comment]
I just made the change. I'll let you know when I have feeds update if it worked. Thanks.

**Edit** : Change was successful.

![github3](https://cloud.githubusercontent.com/assets/3429231/6676377/98c9a0d2-cc27-11e4-93f4-28bdc5533b18.png)

**Comment by Alkarex** [comment]
@AugierLe42e I have made a new version, which now always decode XML-escaped content of type _SIMPLEPIE_CONSTRUCT_MAYBE_HTML_. It should have a more stable and predictable behaviour. Please test if you can https://github.com/FreshRSS/FreshRSS/pull/813#issuecomment-84331198

**Comment by Alkarex** [comment]
BTW, there is a bug report in SimplePie https://github.com/simplepie/simplepie/issues/350 so we could consider sending this patch upstream if it works well.

**Comment by Alkarex** [comment]
So, it seems to work fine, but feel free to re-open in case of problem.

**Comment by Alkarex** [comment]
https://github.com/simplepie/simplepie/pull/400

**Comment by ghost** [comment]
Yeah, work fine now. Thanks  !
