### ISSUE TITLE
Valider le form d'édition d'un flux créé une erreur

### ISSUE THREAD

**Issue by Vincent14** [FreshRSS/FreshRSS#755]
J'ai fait une modif et j'ai cliqué 2x sur le bouton pour valider, et j'ai vu apparaître :
"feedback.sub.error"

ça se produit si on a rien changé au form apparemment

**Comment by marienfressinaud** [comment]
À priori ça arrive lorsque ça n'arrive pas à enregistrer en base de données. Messages de logs ?

Par contre le message de feedback aurait dû être traduit, je regarde ça.

**Comment by Vincent14** [comment]
2015-01-18 00:37:02
feedback.sub.error is not a valid key

**Comment by marienfressinaud** [comment]
J'ai corrigé ça hier soir (https://github.com/FreshRSS/FreshRSS/commit/fa2254cd313f538d74850a67bc062f24626d009d). Et des logs PHP ?

**Comment by Vincent14** [comment]
Mrs logs sont étrangement vierges, tant ceux du virtualhost Nginx que deux de php

**Comment by marienfressinaud** [comment]
Ok c'était tout bête : je n'avais pas réussi à reproduire le bug parce qu'il ne survenait qu'avec MariaDB/MySQL. C'est corrigé dans la version de dev. Merci pour avoir remonté le problème ;)

**Comment by Vincent14** [comment]
Bien vu !
