### ISSUE TITLE
[UI] Truncated dates

### ISSUE THREAD

**Issue by mlaily** [FreshRSS/FreshRSS#756]
If the date of an item is too big (more than 145px, as specified in the css), it is truncated.
![clipboard-1](https://cloud.githubusercontent.com/assets/1535823/5791945/ce34a58c-9efa-11e4-92ba-3586fb3621d1.png)

**Comment by marienfressinaud** [comment]
I fixed that by enlarging the box (155px instead of 145px). I know this is not the best solution and I would prefer a dynamic width but there are some CSS constraints here. I don't plan to fix width better than that.
