### ISSUE TITLE
Affichage cassé avec un article spécifique d'un flux

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/FreshRSS#757]
Bonjour,

Le problème est du côté du flux je pense, mais peut-être que ça peut être catché par FreshRSS.

L'article "Eurosport : vers une exclusivité CanalSat ?" (19 janvier - 09h36) du flux : http://www.universfreebox.com/backend.php casse tout l'affichage : il est le seul à être vu dans le flux principal, il faut que je le marque comme lu pour voir les autres articles. Et quand je vais sur l'affichage de ce flux seulement, la vue se met en vue lecture.

**Comment by marienfressinaud** [comment]
Tu utilises le système pour récupérer les flux tronqués non ? Parce que je n'ai pas ce soucis personnellement.

**Comment by Alwaysin** [comment]
Oups. Effectivement, autant pour moi, j'avais mis un sélecteur CSS pour tester et j'ai oublié... Merci ^^
