### ISSUE TITLE
Unable to import TT-RSS Feeds via OPML

### ISSUE THREAD

**Issue by tapsiturtle** [FreshRSS/FreshRSS#758]
Hi,

i try to import my Feeds from TinyTiny RSS via OPML. But i get this error message:
"Your feeds have been imported but some errors occurred"

After that, there are no feeds. These are the Versions i have installed:
TT-RSS: 1.15
FreshRSS: 0.10-dev

**Comment by yafp** [comment]
Hi,

same issue here - using FreshRSS 0.8.1.
any advice?
Is there some kind of error log?

**Comment by Alkarex** [comment]
Should block https://github.com/FreshRSS/FreshRSS/issues/759

**Comment by Alkarex** [comment]
Should block https://github.com/FreshRSS/FreshRSS/issues/733

**Comment by marienfressinaud** [comment]
Ok, I see where the problem occurs, it will be fixed!

**Comment by marienfressinaud** [comment]
Fixed in the dev branch. For now you just have to edit your OPML file by removing the TTRSS specific lines (outlines `tt-rss-prefs` and its children, `tt-rss-labels` and `tt-rss-filters`) wich are not supported by FRSS anyway.

**Comment by tapsiturtle** [comment]
Thanks. I just imported my TT-RSS Feeds without Problems. Nice Work.

**Comment by yafp** [comment]
Thanks for the hint. removing those in my opml solved the problem -> in other words: 0.8.1 was able to import it.

**Comment by marienfressinaud** [comment]
In fact, OPML files from TTRSS use OPML 1 (where text attributes were not required) while my library to parse OPML was not up to date and supported only OPML 2. Removing line not containing text attribute resolves the problem. In the next version of FreshRSS, the OPML lib is able to parse OPML 1 too so no problem.

By the way, I'm not even sure TTRSS files are valid but it's another problem ;).
