### ISSUE TITLE
Actualisation des flux pour les utilisateurs standards

### ISSUE THREAD

**Issue by gu1ll0me** [FreshRSS/FreshRSS#759]
Je fais face à un problème depuis la version 0.9.4. Les flux des utilisateurs (autre que celui créé lors de l'installation) ne s'actualisent plus automatiquement. L'actualisation fonctionne bien si l'utilisateur le fait manuellement à l'aide du bouton "Actualisation" de la page principale. Rien d'anormal du côté de l'utilisateur par défaut, les flux s'actualisent correctement.

La sortie du script actualize_script.php ne semble pas être anormale en dehors des avertissements d'accès PHP. Un OK s'affiche même à côté des autres utilisateurs. Lorsque lancé manuellement, le script bloque à Actualize [utilisateur par défaut]... et passe rapidement sur les autres utilisateurs.

Starting feed actualization at 2015-01-20T12:15:28-05:00
PHP Warning:  file_exists(): open_basedir restriction in effect. File(/usr/share/webapps/freshrss/extensions/.gitignore/metadata.json) is not within the allowed path(s): (/srv/http/:/home/:/tmp/:/usr/share/pear/:/usr/share/webapps/) in /usr/share/webapps/freshrss/lib/Minz/ExtensionManager.php on line 62
PHP Warning:  file_exists(): open_basedir restriction in effect. File(/usr/share/webapps/freshrss/extensions/README.md/metadata.json) is not within the allowed path(s): (/srv/http/:/home/:/tmp/:/usr/share/pear/:/usr/share/webapps/) in /usr/share/webapps/freshrss/lib/Minz/ExtensionManager.php on line 62
PHP Notice:  Undefined index: allow_anonymous in /usr/share/webapps/freshrss/app/Models/ConfigurationSetter.php on line 284
Actualize [défaut]...
Actualize [user1]...
Actualize [user2]...
Done.
Ending feed actualization at 2015-01-20T12:15:29-05:00
Feed actualizations took 0 day(s), 0 hour(s),  0 minute(s) and 1 seconds for 3 users
Results: 
[défaut] OK
[user1] OK
[user2] OK
End.

**Comment by Alkarex** [comment]
Should block https://github.com/FreshRSS/FreshRSS/issues/759

**Comment by Alkarex** [comment]
Should block https://github.com/FreshRSS/FreshRSS/issues/733

**Comment by Alkarex** [comment]
I have made a fix https://github.com/FreshRSS/FreshRSS/commit/12081f7ba2089c8046dacac23ebe44ea843d7ef1
A cleaner approach should be taken later, by improving the FreshRSS constructor/init to allow changing user (which does not seem to be possible anymore after the refactoring of the configuration system).
Anyway, it should work now in the /dev branch, or you can manually apply the patch (this one-line `new Minz_ModelPdo($user);` should be enough https://github.com/FreshRSS/FreshRSS/commit/12081f7ba2089c8046dacac23ebe44ea843d7ef1#diff-816c57ffccf077227e8272bdac0cdeedR58 )

**Comment by gu1ll0me** [comment]
Fix appliqué et problème réglé. La mise à jour automatique de tous les utilisateurs se fait maintenant normalement. Merci.

**Comment by Alkarex** [comment]
Discussion for the FreshRSS constructor/init in https://github.com/FreshRSS/FreshRSS/issues/763
