### ISSUE TITLE
Perte des favicons après MAJ 0.8.1 vers 0.9.4

### ISSUE THREAD

**Issue by barbuslex** [FreshRSS/FreshRSS#760]
Bonjour,

Après la mise à jour de mon FreshRSS je n'ai plus les favicons des Flux:
http://www.world-lolo.com/images/uploads/image.num1421780807.of.world-lolo.com.jpg

Quelqu'un peut il m'aider ?

J'ai essayé en déplaçant l'ancier dossier data/favicons vers le nouveau dossier data/favicons et cela ne résoud rien.

Merci d'avance pour votre aide,
++

**Comment by Alkarex** [comment]
Voir https://github.com/FreshRSS/FreshRSS/issues/290#issuecomment-68244137
C'est d'ores-et-déjà corrigé :-)
Le service dont FreshRSS dépendait n'est plus opérationnel et la dépendance à un service externe à été supprimée

**Comment by barbuslex** [comment]
C'est justement avec la version 0.9.4 que j'ai le soucis... et cette version a le correctif intégré malheureusement.

**Comment by Alkarex** [comment]
Désolé, j'avais mal lu. Vous êtes déjà en version 0.9.4 qui devrait fonctionner. C'est peut-être un problème de droits d'accès. Vous pouvez essayer de relancer le script d'installation/mise-à-jour en créant un fichier vide `./data/do-install.txt`

**Comment by marienfressinaud** [comment]
Je n'ai pas compris ce que tu as fait en "déplaçant l'ancier dossier data/favicons vers le nouveau dossier data/favicons". Rien n'a changé à ce niveau-là. J'essayerai de reproduire le bug dans la journée (j'ai ajouté le ticket à #733)

**Comment by barbuslex** [comment]
En fait, j'ai récupéré l'ancien dossier data/favicons de ma version 0.8.1 et je l'ai copier dans la nouvelle install dans le dossier data/favicons de ma version 0.9.4 et cela n'a pas marché donc j'ai tout clean.

Après avoir laisser tourner FreshRSS 24h les favicons sont réapparus mais par contre j'ai toujours des erreurs dans la console développeur:
http://imageswl.fr/i/BECBIDJAAEL

Le fichier f.php fait toujours pointer vers des URL 404 apparamment..

**Comment by barbuslex** [comment]
Petite correction, pas toutes les favicons sont revenus. Certaines restent encore en erreurs : 
http://imageswl.fr/i/BECBIDJJEFL

**Comment by marienfressinaud** [comment]
Ok j'ai compris : ton FreshRSS est derrière un Cloudflare qui gère lui-même les erreurs 404 (comportement non prévu et je ne considère pas que ça soit à FRSS de le faire). Les favicons qui ne peuvent pas être récupérés (parce que pas déclarés, pas trouvés, pas pu être téléchargés, etc.) sont servis avec une image par défaut et le code retour 404. Sauf que comme Cloudflare se charge de servir les erreurs 404, l'image par défaut n'est pas servie.

Je ne sais pas si toi de ton côté tu peux paramétrer Cloudlare pour laisser FRSS servir les erreurs 404.

**Comment by marienfressinaud** [comment]
Bon finalement j'ai décidé de servir le favicon par défaut avec un code HTTP 200. Le problème devrait être corrigé.
