### ISSUE TITLE
freshrss-0.9.4 won't let me log in -> invalid user

### ISSUE THREAD

**Issue by jlec** [FreshRSS/FreshRSS#761]
I just checked out the 0.9.4 tag and now I cannot log in anymore with "Invalid user". I am using the same user and password as for 0.9.3

**Comment by Alkarex** [comment]
I have not followed in which version exactly the new user structure has appeared, and what the status of the update script is ( @marienfressinaud knows ). Did you run the update (install) script? You may have to follow https://github.com/FreshRSS/FreshRSS/issues/752#issuecomment-70362153 (i.e. follow instructions on https://github.com/FreshRSS/FreshRSS/commit/b5bee8560345e4123432a8bd3bcd63b938549ef9 and https://github.com/FreshRSS/FreshRSS/commit/d3a93ea2905ae50a2365d293f9f3ef3e51bf5f30 )

**Comment by jlec** [comment]
The easy thing first, perhaps it would be good to mention Braking changes in the ChangeLog.

I did the config modification before filing the bug. The file move has been overlooked. I moved now the user config and the log. There is no db as I am using MySQL as backend db. Anything I need to do there?

**Comment by marienfressinaud** [comment]
Should block #733 

Can we have the structure of your `./data/users` directory? It may also be a right access problem.

**Comment by jlec** [comment]
# ll data/users/justin/

total 20K
drwxr-xr-x 2 web10 web10 4.0K Jan 21 09:09 .
drwxr-xr-x 4 web10 web10 4.0K Jan 21 08:00 ..
-rw------- 1 web10 web10 1.7K Jan 19 13:56 config.php
-rw------- 1 web10 web10 4.3K Jan 21 10:32 log.txt

**Comment by marienfressinaud** [comment]
It seems good. Have you any FRSS or PHP related logs? You may have to set `environment` to the `development` value in `./data/config.php`...

**Comment by jlec** [comment]
new fact, on an other browser I wasn't logged out, so I don't need to log in again. This instance is still working as expected.

**Comment by jlec** [comment]
I updated my password and now I can again log in from other browser again.

**Comment by marienfressinaud** [comment]
That's a strange behaviour. The password may have disappeared during your update but I don't understand how. Can we close this ticket?

**Comment by jlec** [comment]
sure.
