### ISSUE TITLE
Actualisation des comptes secondaires

### ISSUE THREAD

**Issue by auieauie** [FreshRSS/FreshRSS#764]
Salut,

Depuis la mise à jour  0.9.4. le cron freshrss n'actualise plus les autres utilisateurs de mon instance, pourtant le log n'a pas l'air de s'affoller :  

> cat /tmp/FreshRSS.log 
> Starting feed actualization at 2015-01-21T16:40:01+01:00
>    Actualize user1...
>    Actualize user2...
>    PHP Notice: A feed could not be found at `http://calibre-ebook.com/feeds/changelog/`; the status code is `200` and content-type is `application/octet-stream` in /srv/harinezumi/freshrss/lib/SimplePie/SimplePie.php on line 1594
>    Actualize user3...
>    Done.
>    Ending feed actualization at 2015-01-21T16:41:34+01:00
>    Feed actualizations took 0 day(s), 0 hour(s),  1 minute(s) and 33 seconds for 3 users
>    Results: 
>    user1 OK
>    user2 OK
>    user3 OK
>    End.

Dans l'onglet « vérification de l'installation » tout est au vert, l'user1 est admin.
L'actualisation manuelle se passe bien.

Une idée / besoin de compléments ?

**Comment by marienfressinaud** [comment]
Bug déjà remonté et déjà résolu dans la version de dev : https://github.com/FreshRSS/FreshRSS/issues/759. Si tu veux corriger le problème il faut faire les modifications de https://github.com/FreshRSS/FreshRSS/commit/12081f7ba2089c8046dacac23ebe44ea843d7ef1
