### ISSUE TITLE
Use a template system instead of HTML/PHP code

### ISSUE THREAD

**Issue by marienfressinaud** [FreshRSS/FreshRSS#765]
Views are really hard to maintain or to adapt for new themes. I think it would be better to improve view system with a template system (for new comers and for us).

Obviously, it is a huge task and it's only an idea to implement later ;). For the moment we can discuss of technologies to use (e.g. [RainTPL](http://rainphp.github.io/raintpl/)).

**Comment by aledeg** [comment]
I think that is a really good idea and the proper way to do. That goes with the unit testing to make the application more reliable.
Twig is a good choice as well. Bonus with this solution, there is a linter for templates.

**Comment by aledeg** [comment]
Using a template system will help for RTL writings like Hebrew or Arabic

**Comment by Frenzie** [comment]
@aledeg Could you please clarify in what way it helps with RTL?

**Comment by aledeg** [comment]
@Frenzie You're digging an old comment :) I don't remember why I thought it was a good idea at the time. Three years after, I cannot think of any reasons.
If I think of something, I'll let you know.

**Comment by aledeg** [comment]
Just dropping [this](https://en.wikipedia.org/wiki/Comparison_of_web_template_engines) for reference

**Comment by marienfressinaud** [comment]
I'm closing this ticket. I'm pretty sure we'll never switch, there are too many files!
