### ISSUE TITLE
Ce flux est vide. Veuillez vérifier qu’il est toujours maintenu.

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/FreshRSS#768]
Pour ce flux : http://www.unix-ninja.com/feed/rss/

http://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fwww.unix-ninja.com%2Ffeed%2Frss%2F détecte des erreurs mais est-ce "normal" qu'il soit considéré comme vide par FreshRSS ?

**Comment by aledeg** [comment]
Ce n'est pas un problème de FreshRSS. C'est SimplePie qui ne trouve rien.
Voir la demo ici => http://www.simplepie.org/demo/?feed=http%3A%2F%2Fwww.unix-ninja.com%2Ffeed%2Frss%2F

**Comment by Alwaysin** [comment]
Arf et donc dans ce cas y'a aucun moyen que je puisse récupérer ce flux ? :(

**Comment by aledeg** [comment]
Peut-être avec l'option de forçage, mais ce n'est pas garanti.
Ajoute #force_feed à la fin de ton URL. Si ça ne marche pas, il va falloir que tu communiques avec le site et que tu leur demandes de générer un RSS valide.

**Comment by Alwaysin** [comment]
Pas mieux avec force feed :(

Merci pour l'auide en tout cas :)

**Comment by Alkarex** [comment]
J'ai essayé en faisant un proxy RSS dans Yahoo! Pipes, et cela ne marche pas non plus
- http://pipes.yahoo.com/pipes/pipe.run?_id=79ee10f4fc2e7baaea2ee3ffd67b802e&_render=rss&url=http://www.unix-ninja.com/feed/rss/

Il faudrait essayer en passant par https://superfeedr.com par exemple (gratuit tant qu'on ne fait pas trop de requêtes).

Sinon il faut faire une extension ou proxy pour corriger le flux.
