### ISSUE TITLE
Wrong format for the password

### ISSUE THREAD

**Issue by dhoko** [FreshRSS/FreshRSS#769]
Hello, 

When I try to create an account i've got an error about the password. Invalid pasword format, ok but nothing explain how to format my password cf: 

![capture du 2015-01-25 19 04 01](https://cloud.githubusercontent.com/assets/713283/5892586/18467bbc-a4c5-11e4-854b-0a277b1c4cb2.png)

**Comment by marienfressinaud** [comment]
Fixed. By the way @ealdraed, is it possible to confirm "mindestens 7 Zeichen" is the correct translation of "At least 7 characters"?

**Comment by ealdraed** [comment]
@marienfressinaud 
Confirmed ;)

But I think the fix should also be added in the following places:

app/i18n/<lang>/admin.php:
app/i18n/<lang>/conf.php:
app/views/user/manage.phtml
app/views/user/profile.phtml

**Comment by marienfressinaud** [comment]
Thanks!

user/manage and user/profile are fixed now. By the way, there are other places to add such information (e.g. database fields during install process). I'll open a dedicated ticket but I will don't have the time to fix it.
