### ISSUE TITLE
Impossible de déplier les articles sous Firefox OS 1.3

### ISSUE THREAD

**Issue by Vincent14** [FreshRSS/FreshRSS#771]
Je suis sur le canal Alpha à priori, et euh voilà tout est dans le titre, mais c'est juste à titre informatif et pas forcément un bug de FreshRSS. Ca marchait avant, si le code JS a évolué peut être que c'est une API trop récente pour avoir été implémentée dans ce vieux gecko mais ça me parait étrange. Si vous avez un mobile, pouvez vous tester et rapporter ce que cela donne svp ?

**Comment by marienfressinaud** [comment]
Pas de problème sous FirefoxOS 2.1, donc je suppose que le problème ne vient pas de FRSS. As-tu installé [l'extension StickyFeed](https://github.com/FreshRSS/Extensions) ?

**Comment by Vincent14** [comment]
Non pas que je sache, bon bah ca partira lors des prochaines MAJ rien d'important dans ce cas :)
