### ISSUE TITLE
Notifications sur Firefox OS 2

### ISSUE THREAD

**Issue by zamasp** [FreshRSS/FreshRSS#774]
Les notifications sur Firefox OS 2 apparaissent sans icone et la sélection de la notification est sans effet sinon de fermer la zone de notifications : aucune ouverture du navigateur après la fermeture de la zone de notifications.

**Comment by marienfressinaud** [comment]
Je suis déjà au courant mais je suis moyennement pour essayer de corriger des bugs sur un système qui est lui-même sujet à de nombreux bugs (voir par exemple un bug de FFOS 1.3 https://github.com/FreshRSS/FreshRSS/issues/771). Typiquement, comme ce bug n'est pas présent sur desktop, je ne pense pas chercher plus que ça ;).

**Comment by zamasp** [comment]
C'est pas plus grave que ça... on fera avec !

**Comment by marienfressinaud** [comment]
Je peux confirmer que le logo est là dans la version 2.2. Pour l'ouverture du navigateur, pareil, je ne peux rien faire de plus donc je ferme le ticket ;).

**Comment by zamasp** [comment]
Ok. Merci.
