### ISSUE TITLE
Erreur lors du marquage en "Tout lu" :  Un problème est survenu et la requête a échoué. ❌ 

### ISSUE THREAD

**Issue by Draky50110** [FreshRSS/FreshRSS#775]
Salut

Par défaut, quand j'ai des flux non lus, ils sont les seuls à s'afficher.
Je fait donc ma tambouille et je clique en bas sur "Marquer en tout lu".

Et j'ai ce joli message :  Un problème est survenu et la requête a échoué. ❌ 

Sauf que ça marche quand même et tout est bien marqué "Lu".
On peut savoir la requête qui échoue ?

**Comment by marienfressinaud** [comment]
Alors ça c'est un nouveau message qui s'affiche seulement lorsque tu marques un (et un seul) article en lu ou favori. De ce que tu évoques dans #738 ça ne me paraît pas aberrant que ce message s'affiche chez toi mais par contre il ne doit pas s'afficher lorsque tu cliques sur le bouton "Marquer comme lu" qui s'applique à tous les articles.

Par contre je me rends compte que le message n'est pas suffisamment explicite, je vais changer en "Une requête a échoué, cela peut être dû à des problèmes de connexion à Internet".

**Comment by Draky50110** [comment]
Je teste mais ça me le fait presqu'à chaque fois.

**Comment by ealdraed** [comment]
@marienfressinaud: Please change line 100 to
'request_failed' => 'Eine Anfrage ist fehlgeschlagen, dies könnte durch Probleme mit der Internetverbindung verursacht worden sein.',

**Comment by marienfressinaud** [comment]
Done :).

**Comment by Alkarex** [comment]
@Draky50110 Est-ce que ce problème est toujours d'actualité ? Tester si possible avec la branche /dev.

**Comment by Draky50110** [comment]
@Alkarex J'ai mis à jour, je dirai si ça foire encore...
