### ISSUE TITLE
UX très frustrante pour l'ajout d'un nouveau flux

### ISSUE THREAD

**Issue by mlaily** [FreshRSS/FreshRSS#777]
Il faut SEPT clicks pour ajouter un flux en lui attribuant une catégorie.
A la longue c'est très frustrant.
Peut être le principal problème est la taille du champ d'ajout beaucoup trop petit, et qui se redimensionne lorsque il a le focus. C'est assez insupportable et fait qu'on est obligé de cliquer dans le vide pour pouvoir cliquer sur le bouton de validation ou pour dérouler le drop down de choix d'une catégorie...
Peut être que cela a déja changé dans la version dev ? Je ne suis que sur la branche beta.

**Comment by Alwaysin** [comment]
MERCI pour ce ticket! Je pense exactement pareil mais j'avais peur d'encore passer pour un chieur avec toutes mes demandes :p

La taille du champ d'ajout est effectivement le principal élément frustrant, il y est toujours sur la version dev.

**Comment by marienfressinaud** [comment]
J'essaye de voir ça demain. Effectivement ça peut être largement amélioré mais comme j'utilise quasiment jamais ce champ pour ajouter des articles je ne m'étais pas fait la remarque >< (enfin si, le champ qui se redimensionne a bien dû me perturber quand même :s)

**Comment by mlaily** [comment]
> j'utilise quasiment jamais ce champ pour ajouter des articles

Il y a un autre moyen, ou tu voulais juste dire que tu n'ajoutes pas des flux tous les jours ?

**Comment by aledeg** [comment]
tu peux utiliser le bookmarklet pour ajouter des flux

**Comment by mlaily** [comment]
ah merci, je n'avais même pas remarqué qu'il y en avait un !

**Comment by marienfressinaud** [comment]
J'ai changé le comportement : le champ sera long par défaut donc plus besoin de cliquer ailleurs pour qu'il retrouve sa taille "normale". Il y aurait probablement d'autres améliorations à faire (je garde donc le ticket ouvert) mais je pense que c'est moins urgent ;).

**Comment by Alwaysin** [comment]
Merci, ça soulage beaucoup !

Après on peut aller plus loin en mettant le champ d'ajout directement sur la page principale, soit en-dessous de gestion des abonnements soit à la place de "gestion des abonnements", ce dernier prenant la place du bouton import/export (je ne pense pas qu'il soit utile de l'avoir à portée de mains, étant donné qu'on ne doit pas s'en servir très souvent). Mais ce n'est qu'une proposition, ça ne me gêne pas si ça reste comme ça !

**Comment by marienfressinaud** [comment]
On verra ça plus tard :p

**Comment by julien51** [comment]
Si ca peut aider, peut etre est-ce que le bouton [SubToMe](https://www.subtome.com/#/) peut etre une solution? c'est ce que j'utilise avec un autre reader et je n'ai plus qu'un seul clic dans mon navigateur, sans avoir besoin de chercher l'URL du flux!

**Comment by aledeg** [comment]
@mlaily @Alwaysin 
5 years later, something changed. Please review my PR to check if this is more usable for you. Thank you for your support.

**Comment by mlaily** [comment]
Ha! thank you for *your* support! :p
