### ISSUE TITLE
Titre en entier et barre du bas activable ou non

### ISSUE THREAD

**Issue by tetsumaki** [FreshRSS/FreshRSS#778]
Bonjour,

Je pense qu'il pourrait être sympa (pour moi :)) d'ajouter une petite option à cocher pour les thèmes :

A savoir :
1. Ne pas afficher la barre du bas (bah oui je préfère scroller et pas forcément tout déplier)
2. Afficher l'integralité du sujet (ce qui implique plusieurs lignes si le sujet est long)

Pour vous donner une petite idée :

Sur Leed on a les sujets en entier :
http://img11.hostingpics.net/pics/534135Screenshot20150129204821.png

Sur FreshRSS on a les sujets coupés et une ligne en bas :
http://img11.hostingpics.net/pics/843191Screenshot20150129204837.png

Et voilà !

**Comment by marienfressinaud** [comment]
Noté… pour après la 1.0 ;)

**Comment by aledeg** [comment]
I think that issue has been addressed.

**Comment by marienfressinaud** [comment]
Via https://github.com/FreshRSS/Extensions/tree/master/xExtension-TitleWrap, indeed

**Comment by Alkarex** [comment]
@marienfressinaud This is pretty small, don't you think it could be promoted to a core option if it works well?

**Comment by Frenzie** [comment]
The issue was closed the other day, but that was the intent. ;-)

https://github.com/FreshRSS/FreshRSS/issues/2344#issuecomment-575235774

**Comment by Alkarex** [comment]
Ok, so the current extension only works for some given themes, right?

**Comment by Frenzie** [comment]
I think @marienfressinaud was referring to Flus or some other private theme.

**Comment by marienfressinaud** [comment]
Indeed @Frenzie, unfortunately the Flus theme is differing quite a lot from the other themes. But I agree it could be integrated in the core. It could even be the default behavior.
