### ISSUE TITLE
Inquiétude au niveau de la récupération des favicons

### ISSUE THREAD

**Issue by mlaily** [FreshRSS/FreshRSS#779]
Toutes les favicons de tous les flux rss ajoutés sont requêtées systématiquements à chaque rafraichissement de FreshRSS (appel sur f.php).
J'ai dernièrement ajouté un certain nombre de flux, ce qui fait que à chaque actualisation de la home page de FreshRSS, mon navigateur effectue environ 350 requetes http ^^'.

Dans mon cas particulier, étant donné que mon serveur dispose d'une protection DoS, cela pose problème, puisque les 3/4 des requêtes finissent en 403 et FreshRSS est à moitié inutilisable, mais c'est un cas assez spécial. (cette protection m'a d'ailleurs déja posé problème par le passé (voir #751 )...)

Je ne suis toujours pas certain de si ce nombre impressionnant est un problème en soit dans le cas général, mais il me parait tout de même anormal...

Etant donné que toutes les requêtes de favicon sont déja centralisées sur un script php plutôt que récupérées directement sur le site d'origine, ne serait il pas envisageable de réduire le nombre de requêtes d'une façon ou d'une autre ?
(Plusieurs idées me viennent, pas forcément pertinentes : génération d'un sprite, mise en cache d'une façon différente pour les demander moins souvent, inclure les images dans le html en base64...)

Désolé pour cette issue un peu vague, un peu longue, pas forcément très critique, et potentiellement impossible à satisfaire...

**Comment by Alkarex** [comment]
Première réponse rapide : les favicons sont servis avec une information HTTP de mise en cache. Si cette information n'est pas altérée par un proxy quelconque et que le navigateur fait bien son travail, elles ne devraient que rarement être re-téléchargées.
J'ai personnellement constaté un problème après certaines mises-à-jour de Firefox, où la politique de cache était soudainement visiblement corrompue ; problème que j'ai résolu en vidant le cache de Firefox.
Essayez de vider le cache de votre navigateur, éventuellement comparer avec un autre navigateur, et regarder dans les outils de développement du navigateur quelles sont les entêtes HTTP exactes reçues (n'hésitez pas à demander de l'aide si nécessaire).

**Comment by mlaily** [comment]
Le problème n'est pas que les favicons ne sont pas effectivement re-téléchargées ou non, mais qu'une requête http est faite de toute manière par le navigateur pour demander si il a besoin de la re-télécharger. Le cache fonctionne puisque la plupart des requêtes résultent en un 304 Not Modified.

(Vérifié sur Firefox et Chrome)

**Comment by mlaily** [comment]
Sur Chrome, 244 requêtes sont effectuées en 2.20s.
J'ai une excellence connexion (fibre optique, ~30ms de latence vers mon serveur), mais je pense que sur une connexion plus classique, voire sur mobile, cela pourrait vite devenir désastreux pour les performances de chargement de la page, non pas à cause du volume des données (seulement 282ko transférés puisque le reste était en cache), mais à cause de la latence.

**Comment by Alkarex** [comment]
Si les entêtes HTTP sont bien reçues, et que le navigateur fait bien son travail, il n'est pas sensé y avoir de requête très souvent (ni même de requête conditionnelle résultant dans un 304).
Voir mon précédent message pour essayer de trouver/corriger le problème.
Exemple de réponse chez moi :

```
HTTP/1.1 200 OK
Date: Wed, 28 Jan 2015 16:44:03 GMT
Server: Apache/2.4.7 (Ubuntu)
X-Powered-By: PHP/5.5.9-1ubuntu4.5
Content-Disposition: inline; filename="1651a7fd.ico"
Cache-Control: public, max-age=2592000
Last-Modified: Mon, 26 Jan 2015 15:11:21 GMT
Etag: "683f759449626e4458ab13d929e3b839"
Content-Length: 7886
Content-Type: image/x-icon
```

Remarquez `max-age` (qui permet d'éviter complètement les requêtes tant que ce fichier est présent dans le cache du navigateur et pour au maximum 30 jours) et que la dernière requête à ce favicon dans mon cas a été faite il y a plus de 2 jours alors que je m'en suis servi pas mal depuis.
(Testé en regardant les propriétés de l'image, onglet "entêtes" fourni par [https://addons.mozilla.org/fr/firefox/addon/live-http-headers/](LiveHTTPHeaders)).

**Comment by mlaily** [comment]
J'ai effectué quelques tests après avoir désactivé le module de protection DoS sur Apache (mod_evasive).

Comme prévu les erreurs 403 ont disparues, mais le nombre de requêtes est approximativement toujours le même :/

Voici les headers envoyés et reçus sur 3 navigateurs différents pour la même favicon, après avoir vidé le cache, puis chargé la page deux fois de suite afin d'être dans les conditions "normales" ou le cache devrait fonctionner.

Firefox (Waterfox):
![waterfox](https://cloud.githubusercontent.com/assets/1535823/5982521/2dabc194-a8c4-11e4-9ac9-04a6437fa8ca.png)

Chrome:
![chrome](https://cloud.githubusercontent.com/assets/1535823/5982527/342475d4-a8c4-11e4-9f36-211d8e1b1d29.png)

Internet Explorer 11:
![ie](https://cloud.githubusercontent.com/assets/1535823/5982539/453f08d4-a8c4-11e4-8b74-6c337ee59369.png)

Suite à ces résultats, soit j'ai un problème de configuration qui reste à déterminer, soit le cache ne fonctionne pas comme il est supposé.
Qu'en pensez vous ?

**Comment by mlaily** [comment]
Après avoir forcé la désactivation du cache navigateur dans les outils de dev Chrome, voici les headers transmis, qui sont donc en principe ceux reçus lors de la première demande d'une favicon:
![chrome2](https://cloud.githubusercontent.com/assets/1535823/5982659/913afef4-a8c5-11e4-8938-fb355f0fb9a5.png)

Les paramètres de cache me semblent bien présents correctement...

**Comment by mlaily** [comment]
Ok je crois que j'ai enfin compris ce qu'il se passe.

J'ai réalisé tous mes tests jusqu'à maintenant en rafraichissant le navigateur en appuyant sur F5 ou le bouton de refresh.
D'après la doc de Mozilla ici https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching_FAQ une revalidation de cache est déclenchée en cas de rafraichissement de la page par l'utilisateur.

Si la navigation s'effectue de façon "naturelle", les objets en cache toujours "fresh" ne sont pas revalidés.

J'ai effectivement vérifié ce comportement en naviguant vers FreshRSS depuis une autre page avec les outils de debugs activés. Si les favicons sont déja en cache, aucune requête n'est effectuée. :)

Je ne ferme pas cette issue car je trouve tout de même que plusieurs centaines de requêtes pour charger une page est anormal, mais le problème est moindre que ce que je craignais. A vous de décider pour la suite...

**Comment by Alkarex** [comment]
Ok, cela me semble donc fonctionner comme prévu.
Effectivement, il serait très souhaitable de réduire le nombre de requêtes, mais je n'ai pas de solution évidente pour les favicons (voir https://github.com/FreshRSS/FreshRSS/issues/682 pour les autres icônes) - les alternatives que je vois ajoutent pas mal de complexité pour un gain incertain.
Il faut noter néanmoins que le nombre de connexions (ce sont elles qui sont vraiment coûteuses) est bien moindre que le nombre de requêtes grâce au `Keep-Alive`, et que la page est chargée et utilisable même avant d'avoir récupéré tous les favicons.

**Comment by marienfressinaud** [comment]
Je suis d'accord que le nombre de requêtes est assez (voire trop) important. J'y ai réfléchi vaguement par le passé mais la seule solution qui me paraît efficace est la génération d'un sprite. Je voyais ça à travers le système de web-cron #613 (ou cron tout court) : regénérer un sprite de favicons toutes les 2 semaines par exemple. Reste la question de comment gérer ça à l'affichage.

On pourrait aussi regarder comment les favicons sont gérés par TTRSS.

On peut garder ce ticket ouvert en tout cas car dans un contexte multi-utilisateurs, bien gérer ça me paraît important.

**Comment by aledeg** [comment]
On pourrait utiliser le mécanisme de cache introduit par HTML5.
Voir ici => http://sametmax.com/mode-le-manifeste-du-cache-du-mode-hors-ligne-pour-html5/

**Comment by marienfressinaud** [comment]
@aledeg > voir https://github.com/FreshRSS/FreshRSS/issues/714. J'aimerais quand même un autre mécanisme par dessus (ne serait-ce qu'une option permettant de désactiver les favicons !)

**Comment by Alkarex** [comment]
@aledeg Je ne pense pas que le cache HTML5 en question soit d'une quelconque utilité (voir https://github.com/FreshRSS/FreshRSS/issues/714#issuecomment-65207250 ). D'une part FreshRSS change d'URL à la navigation (ce qui ne me semble pas approprié pour ce type de cache), d'autre part les favicons sont déjà en cache (HTTP). Le cache HTML5 n'est pas infini non plus. La seule amélioration que je vois (sauf à utiliser HTTP 2 / SPDY) est de consolider les favicons en un seul fichier, mais cela risque d'augmenter sensiblement la complexité pour un gain pas évident.

**Comment by Alkarex** [comment]
HTTP/2 moving forward: http://www.theregister.co.uk/2015/05/15/http2_is_now_utterly_officially_official/

**Comment by Alkarex** [comment]
Apache 2.4.17 (13 octobre 2015) intègre mod_http2 par défaut
http://www.apache.org/dist/httpd/CHANGES_2.4.17
https://httpd.apache.org/docs/trunk/mod/mod_http2.html

**Comment by Alkarex** [comment]
https://www.smashingmagazine.com/2016/02/getting-ready-for-http2/#turning-multiple-image-files-into-sprites

**Comment by Alkarex** [comment]
La prochaine Ubuntu 16.04 LTS aura Apache 2.4.18 avec HTTP/2.

**Comment by Alkarex** [comment]
Je ferme ce ticket pour se concentrer sur l'optimisation via HTTP/2 qui adressera les problèmes rapportés dans ce ticket. La suite dans https://github.com/FreshRSS/FreshRSS/issues/1089
