### ISSUE TITLE
Le chargement des articles suivants en scroll infini se déclenche trop tard

### ISSUE THREAD

**Issue by mlaily** [FreshRSS/FreshRSS#781]
J'ai l'impression que le chargement des articles suivants ne se déclenche que quand on arrive sur le dernier article chargé.
Cela fait que quand on navigue au clavier et qu'on arrive en bas de page, l'article suivant (je n'ai pas réussi à déterminer si il s'agit du dernier article chargé, ou du suivant qui vient de se charger) n'est pas positionné en haut de page. Cela est probablement dû au fait que les nouveaux articles suivants n'étant pas chargés, c'est la position maximum de scroll qu'on puisse atteindre.

La solution serait sans doute de charger les articles suivants plus tôt, plutot que d'attendre le dernier moment, voire même de charger un nouvel article à chaque fois qu'on en passe un ?
Une autre solution serait d'ajouter un espace vide à la fin de la page, afin que le dernier article puisse être aligné en haut de l'écran. Cela règlerait le problème de l'article pas aligné, mais pas le problème sous jacent de chargement trop tard...

**Comment by marienfressinaud** [comment]
Déjà remonté : https://github.com/FreshRSS/FreshRSS/issues/720 :)

J'essayerai de faire une extension pour régler le problème dans un premier temps mais pas le temps pour le moment.
