### ISSUE TITLE
Problème mise à jour automatique de 0.8.1 vers 1.0

### ISSUE THREAD

**Issue by ejrhoffmann** [FreshRSS/FreshRSS#782]
Bonjour,
Je fais fonctionner FreshRSS 0.8.1 sur un serveur Debian hébergé.
La page 'Système de mise à jour' m'indique qu'une mise à jour est disponible.
Après avoir appuyé sur le bouton de mise à jour, j'obtiens le message suivant et le processus ne se termine : 
![erreur maj rogne](https://cloud.githubusercontent.com/assets/4470284/5992357/ad606422-aa3f-11e4-812e-10856c7b4afe.png)
Bonne journée,
Eric

**Comment by marienfressinaud** [comment]
Que tu sois en 0.8.0 ou 0.8.1, il devrait essayer de télécharger l'archive 1.0.0. Apparemment tu dois avoir un vieux script de mise à jour sur le serveur. Je pense qu'en supprimant simplement le fichier `./data/update.php` tu devrais pouvoir relancer la procédure (un bug a été résolu depuis).

**Comment by ejrhoffmann** [comment]
Ca marche. Merci.
Maintenant je suis en 1.0.0.

Eric

**Comment by marienfressinaud** [comment]
Parfait !
