### ISSUE TITLE
New CONTRIBUTING file

### ISSUE THREAD

**Issue by marienfressinaud** [FreshRSS/FreshRSS#783]
We need a CONTRIBUTING(.md) file to be more opened to contributions!

**Comment by marienfressinaud** [comment]
First draft for CONTRIBUTING.md file: https://github.com/FreshRSS/FreshRSS/blob/783-contributing-file/CONTRIBUTING.md

**Comment by olafleur** [comment]
Super !

**Comment by marienfressinaud** [comment]
Contributing file has been merged in dev branch!
