### ISSUE TITLE
Problème avec certains flux.

### ISSUE THREAD

**Issue by AlexisKNope** [FreshRSS/FreshRSS#784]
Je viens de passer en 1.0 et je remarque que certain flux sont affiché comme éronné. (L'exemple que j'ai en tête est le flux RSS du site Reflets.info).

Pourtant, lorsque je vérifie la validité du flux, il n'y a pas de soucis, tout est OK.
De même, lorsque je vérifie le lien, c'est bien celui du site que je fournis.

Le problème vient-il de FreshRSS ou du site en question ?

**Comment by aledeg** [comment]
J'ai aussi le flux de Reflets.info dans mes flux. Par contre, je n'ai pas de problèmes liés.
J'utilise pour ma part la version 1.1.0.
As tu quelque chose d'indiqué dans les logs?

**Comment by AlexisKNope** [comment]
Rien dans les logs :/
Juste, la v1.1.0, c'est une beta ? Parce que j'ai tenté de mettre à jour, mais ça affiche que le lecteur est à jour.
![refletsbug](https://cloud.githubusercontent.com/assets/9071266/6041674/ce16ad02-ac7e-11e4-9d4f-b7c274040396.PNG)

**Comment by aledeg** [comment]
Oui la 1.1.0 est une béta. Mais elle est quand même assez stable.
Par contre, je ne sais pas comment passer ta version de stable à béta depuis l'installeur. Il faudrait que je regarde ou que @marienfressinaud nous indique comment faire.

**Comment by aledeg** [comment]
As tu essayé sur la demo de [FRSS](http://demo.freshrss.org)?

**Comment by marienfressinaud** [comment]
J'ai parfois des soucis aussi avec certains flux (dont Reflets). Ils sont marqués en erreur lorsque SimplePie n'arrive pas à accéder à la source du flux, probablement un timeout "aléatoire". Si tu veux avoir plus d'infos, tu peux éditer dans le fichier `data/config.php` la valeur de 'environment' en changeant 'production' en 'development', ça activera les logs plus verbeux (que tu pourras ensuite voir dans les logs FreshRSS).

Il n'y a aucune bénéfice à passer en bêta actuellement puisque les deux (1.0.0 et 1.1.0) sont absolument identiques. Plus tard si tu souhaites passer en bêta, change juste la valeur de FRESHRSS_VERSION dans `./constants.php` en 1.1.0, tu bénéficieras alors des màj de la branche bêta ;).

**Comment by aledeg** [comment]
J'aurai appris quelque chose aujourd'hui :P

**Comment by AlexisKNope** [comment]
Je ne souhaite pas spécialement passer en béta, mais je garde le conseil sous la main pour plus tard. En attendant, je vais essayer de changer le fichier de config. P-e que je pourrais avoir accès aux articles de reflets de cette manière.
Au passage, le lecteur est hébergé sur un serveur mutualisé OVH avec une base MySQL. Je sais pas si ça joue dans mon problème.

Je vous tient au courant de l'évolution du problème dans le prochain jours

**Comment by marienfressinaud** [comment]
@aledeg > à noter un jour dans la doc :p 

@AlexisKNope > tu n'auras pas plus accès au flux mais tu auras probablement des logs plus verbeux donc on pourra savoir d'où vient le problème (je suis quasi certain que c'est un timeout qui ne survient pas tout le temps)

**Comment by AlexisKNope** [comment]
Bon, du coup, en mettant à jour le flux, j'obtiens ça dans les logs :

```
2015-02-04 15:20:52A feed could not be found at `http://reflets.info/feed/`; the status code is `403` and content-type is `text/html; charset=iso-8859-1` [http://reflets.info/feed/]
```

Là, je sais pas trop comment corriger le soucis :/

**Comment by marienfressinaud** [comment]
Ah, bah je me suis trompé ^^ le code "403" c'est interdiction d'accéder à la ressource, ça veut probablement dire que le serveur de Reflets te bloque. Je ne sais pas trop pourquoi mais tu peux éventuellement les pinguer par mail en pointant ce ticket.

**Comment by AlexisKNope** [comment]
Ok. Je vais les contacter pour leur signaler le problème.
Merci de votre aide à tous les deux :)
Je clos le sujet quand j'ai une réponse de leur part.

**Comment by Alkarex** [comment]
Le flux fonctionne bien depuis chez moi.
Voir des petits tests à faire pour déterminer la nature du blocage https://github.com/FreshRSS/FreshRSS/issues/456#issuecomment-61821397
Il faudrait que nous rajoutions cela à la documentation. Exemple de cas similaire https://github.com/FreshRSS/FreshRSS/issues/809

**Comment by AlexisKNope** [comment]
Merci de l'info ! Je me pencherais sur la question quand j'aurai un peu plus de temps. Je vous tiens au courant dès que c'est fait. (Au passage, l'équipe de Reflets n'as pas répondu à ma requête. D'où la non-mise à jour ce topic).

**Comment by Alkarex** [comment]
Ok :-)
