### ISSUE TITLE
full article content

### ISSUE THREAD

**Issue by Fshamri** [FreshRSS/FreshRSS#785]
Hi,
i found it great application..... but does it support full article content extraction? 

Thanks

**Comment by Alwaysin** [comment]
Hi,

Yes it does! The process is described in https://github.com/FreshRSS/FreshRSS/issues/199#issuecomment-26408922 but it is in french ; should be the time to translate it!

Waiting for someone to do so, you can play with the setting "Articles CSS path on original website" at the bottom of the configuration of a feed, if you have some knowledge you might be able to manage making it working :)

**Comment by aledeg** [comment]
There is an other option which is to use [rss-bridge](https://github.com/sebsauvage/rss-bridge) project. This way, you can separate your concerns.
That's what I do for some feeds.
I think it is more flexible

**Comment by Alwaysin** [comment]
Or also http://code.fivefilters.org/full-text-rss

**Comment by mbe-financial-com** [comment]
Flym is one of the better-known RSS readers on Android, and I noticed it does a pretty good job of fetching full articles without any extra configuration, which would be pretty near impossible anyway for a source such as Google News that links to all sorts of publications. It's in these two pieces of code that basically apply a whole bunch of regexes:
https://github.com/FredJul/Flym/blob/master/app/src/main/java/net/frju/flym/service/FetcherService.kt (function `mobilizeAllEntries()`) and
https://github.com/FredJul/Flym/blob/master/app/src/main/java/net/frju/flym/utils/HtmlUtils.kt (function `improveHtmlContent()`).
Not pretty but fairly effective. I might try porting that, what do you think?

**Comment by Frenzie** [comment]
That first one doesn't really seem to do anything at a glance, it just passes it on to `Readability4JExtended()`? An equivalent library will doubtless be somewhere in Wallabag, possibly too tightly integrated, as well as [here](https://github.com/andreskrey/readability.php) (andreskrey/readability.php).

**Comment by Alkarex** [comment]
@mbe-financial-com Our current way to fetch full content is pretty obsolete, so new possibilities would be much welcome. As @Frenzie writes, we need to clarify whether those methods depend on third-party services or not, and we could even offer more than one option

**Comment by sbrl** [comment]
Sounds like a readability thing you're talking about @mbe-financial-com. Firefox has a reader view built in - perhaps the code there could be used as a base? or maybe someone has already done this and published on packagist?

**Comment by simon-wessel** [comment]
I am migrating from Tiny Tiny RSS and was missing this feature. I built an extension that uses [Mercury Parser](https://github.com/postlight/mercury-parser). You'll need to set up their server for this, since the extension simply uses the Mercury Parser API.

You can find it here, if you're interested: https://github.com/simon-wessel/freshrss-mercury-parser

**Comment by aledeg** [comment]
@Alkarex You've added the tag `documentation` on that issue. What needs to be done so we can close it?

**Comment by Alkarex** [comment]
@aledeg Maybe just a suggestion of using RSS Bridge in some more advanced situations

**Comment by aledeg** [comment]
Ok so we can close it since there is a mention of RSS bridge and Full-text RSS in the documentation. I've just checked in the master branch.
https://github.com/FreshRSS/FreshRSS/blob/064288ed6228d3d56b2231aadd507eb62ae8662c/docs/en/users/04_Subscriptions.md#L80-L83

**Comment by i-iooi-i** [comment]
So up to now, there is no simple and intuitive method to obtain the full text?

**Comment by iSaluki** [comment]
> So up to now, there is no simple and intuitive method to obtain the full text?

This feels like something that should be included out of the box with a modern reader.

**Comment by Alkarex** [comment]
> This feels like something that should be included out of the box with a modern reader.

@iSaluki This issue is obsolete and some parts have been reworked since. Please open a new issue if still relevant (we have built-in CSS selector to fetch full content)
