### ISSUE TITLE
FreshRSS database schema  ?

### ISSUE THREAD

**Issue by dhoko** [FreshRSS/FreshRSS#786]
Hello, 

Do you have a database shema ? I didn't find one. It will be usefull to understand how does freshRSS works.

**Comment by Alkarex** [comment]
Not really a schema, but see https://github.com/FreshRSS/FreshRSS/blob/beta/app/SQL/install.sql.mysql.php

**Comment by dhoko** [comment]
![057e5384af77d9888417b9c20704511dd80d31bd73d97cc018363901eb3b62b0](https://cloud.githubusercontent.com/assets/713283/6097644/112b9ab8-afc6-11e4-8754-db5f082f03da.jpg)

Thank you :)
