### ISSUE TITLE
Add more options to use Twitter share

### ISSUE THREAD

**Issue by KillianKemps** [FreshRSS/FreshRSS#787]
In the parameters, when trying to set a new sharing service. It does function for Diaspora, Blogotext, Wallabag, Shaarli.
However trying to add Google +, Facebook, Twitter, Courriel and Imprimer just adds a red cross without a text input.

In fact, it seems that they are the services positioned after Diaspora on the list.

As you see on the attached image.
![freshrsssharingbugscreenshot](https://cloud.githubusercontent.com/assets/6884630/6098589/f5203fac-afdb-11e4-8e15-367c3ce3f8f0.png)

**Comment by Alwaysin** [comment]
I don't think an input is necessary for those sharing options, it works without the need of inputting something.

**Comment by KillianKemps** [comment]
Oh I see, you are right.
I thought I could tweet directly clicking on the share button from the post.
In fact, it opens a new tab on Twitter to edit the message and where you need to be logged in.
My apologies.

**Comment by Alwaysin** [comment]
The page could be redesigned so that it does not confuse the user, because I admit it can be confusing.

For example, why can we only choose a name for a share that uses a self-hosted service?

**Comment by aledeg** [comment]
Ideas are welcome :)
I do not use twitter, facebook nor google+ so I don't know how it will make it better. So if you can share your ideas, that would be great.

**Comment by Alwaysin** [comment]
I don't use them either, but from the screenshot given byKillianKemps, I think we should at least add the input which lets you rename the sharing option to every option. Maybe even add the second box, but greyed out, and labeled as "not applicable".

**Comment by KillianKemps** [comment]
In my case for Twitter I would prefer to have a link that tweets directly the message with the link of the article and to have another link which lets me edit the message before publishing it. It could be better to merge the two links into one but it has to be fast to publish the default message.

As I don't like to be logged in on Twitter in the same window as FreshRSS, it could be useful to just add FreshRSS as a Twitter application, so it got the rights to publish without I have to login.

I know there is also quite lot of people who are using several Twitter accounts, so it should be easy for them to choose on which one to publish.

**Comment by aledeg** [comment]
Do you have a link to the documentation that allows to register an application as a Twitter application?

**Comment by KillianKemps** [comment]
To register a Twitter application, you need to log in a Twitter account and to create it at this link https://apps.twitter.com/ 

I already created a Twitter app in the past, but now they changed their documentation (for their Fabric framework) so I don't find anymore where it is explained. However the Twitter documentation is at this link https://dev.twitter.com/rest/public 

I hope you will able to get what you need ;).

**Comment by aledeg** [comment]
I will have a look

**Comment by marienfressinaud** [comment]
Don't we need a « API token » or something like that to be able to use the API? I'm not a big fan of transforming FRSS into a Twitter application. I know it is a bit limited actually, but FRSS is not destined to be a « social » app (i.e. it's not its job to support full sharing functionalities).

If someone has a « code proposition », I will have a look at it anyway ;).

**Comment by aledeg** [comment]
Maybe we can close this one. I don't think we should add more things to configure Twitter.
If they really wants to interact with other, they will be using a open API.

**Comment by aledeg** [comment]
Any more thoughts?

**Comment by Alwaysin** [comment]
I think you can indeed close this issue.
