### ISSUE TITLE
Vue avec image du flux et description

### ISSUE THREAD

**Issue by barbuslex** [FreshRSS/FreshRSS#788]
Bonjour,

Une idée qui me paraissait sympas pour les futurs améliorations de FreshRSS.
Une vue avec l'image de l'item du flux ainsi que sa description serait tip top (voir ci-dessous) : 
http://imageswl.fr/i/BECDEHFJAEL

Qu'en pensez vous ?

++

**Comment by Alkarex** [comment]
Oui, ça serait bien. Voir https://github.com/FreshRSS/FreshRSS/issues/561 pour la suite de la discussion.
