### ISSUE TITLE
Can't login with Midori

### ISSUE THREAD

**Issue by tcitworld** [FreshRSS/FreshRSS#790]
FreshRSS Version 1.0.0
Authentification Method : Regular (JS)
Error message : `Communication error!`

Using :
midori 0.5.9 (inside Elementary OS, so the package's called midori-granite)
Works with Firefox

**Comment by tcitworld** [comment]
JS Console doesn't show much (init, waiting for JS, init done) and nothing more when I click login.

**Comment by aledeg** [comment]
I tried with the exact same version both vanilla and granite. They are both running fine. I can authenticate with JS form.
I use it in Awesome WM on Archlinux. I don't know if this make a difference.

**Comment by tcitworld** [comment]
I've disabled all the extensions, without success.
Anyway I can get some debug information ?

I will create another instance to test if there's something to do with existing content/sessions/...

In the meantime, you can test my current instance at rss.tcit.fr, login/pass : debug/debugdebug

**Comment by aledeg** [comment]
I tried to connect but midori raise an **error granting trust**

**Comment by tcitworld** [comment]
And is it okay with another browser ?

**Comment by marienfressinaud** [comment]
@aledeg > I don't know how you had the "error granting trust" problem but here what Midori says about this error (in their FAQ):

> Error granting trust: Couldn't find a place to store the imported certificate
> 
> No key store is available or it's incorrectly setup. By default GNOME keyring can do this. Under Xfce it is recommended to enable “GNOME services” under “Session and Startup settings”. To make sure, that the output of “gnome-keyring –startup” is correctly sent to the environment, you can add “export `gnome-keyring-daemon –start`” to .xinitrc.

Actually I have no problem with Midori and my personal instances of FRSS but problem happens on your instance @tcitworld. Could you try on http://demo.freshrss.org/i/?c=auth&a=login with demo/demodemo?

**Comment by aledeg** [comment]
@marienfressinaud probably because I don't have gnome keyring installed. I had no problem using midori in http on my current install. Probably a faulty certificate...
@tcitworld It was ok with firefox

**Comment by tcitworld** [comment]
Okay it works with the demo server and it works also with my own server with https (self signed certificate, that's why you failed).
Still having an issue with regular http. I will create a new instance to see how it goes.

**Comment by tcitworld** [comment]
OK. It works now. I will not search to understand.
