### ISSUE TITLE
PubSubHubbub support?

### ISSUE THREAD

**Issue by julien51** [FreshRSS/FreshRSS#791]
Adding PubSubHubbub would reduce the need for polling, while still propagate updates in realtime. It's free, open, decentralized and easy to implement! (and you can/should still failover to regular polling).

Check this [PubSubHubbub Getting started](http://blog.superfeedr.com/howto-pubsubhubbub/) tutorial for more details!

**Comment by aledeg** [comment]
Duplicate of #312

**Comment by julien51** [comment]
Oups! (désolé...)
