### ISSUE TITLE
Marquer comme lu le résultat d'une recherche / mark as read search result

### ISSUE THREAD

**Issue by techexo** [FreshRSS/FreshRSS#797]
Bonjour,
Je ne sais pas si je suis totalement handicapé ou si l'option n'existe pas, mais je n'arrive pas à marquer comme lu tous les articles sélectionnés par une recherche. J'utilise FreshRSS pour suivre les publications scientifiques, et si je veux par exemple virer tout ce qui contient le mot "nano", je n'arrive pas à le faire en faisant une recherche "intitle:nano" puis en mettant Marquer comme lu.

L'option existe-t-elle quelque part ? Sera-t-il possible à terme de faire des filtres qui permettent de marquer comme lu tout ce qui contient le mot "nano", par exemple ?
## Merci !

Hi everyone,
I can't find in FreshRSS a way to mark as read all the articles whose title contains an expression, say "nano". If I search for "intitle:nano" and then click "mark as read", all the feed is dismissed instead of just the selected articles.

Am I doing it wrong, is that a missing feature or is it a bug in the mark as read function?

Thanks
Eloi

**Comment by aledeg** [comment]
It is not possible at the moment. It is a duplicate of #608.
It will be done in the future.
