### ISSUE TITLE
[bug] flickr feeds can not be used

### ISSUE THREAD

**Issue by aledeg** [FreshRSS/FreshRSS#805]
Here is [a link](http://api.flickr.com/services/feeds/photos_public.gne?id=30452866@N06&amp;lang=fr-fr&amp;format=rss_200) to try.

I tested it with the [SimplePie demo](http://www.simplepie.org/demo/?feed=http%3A%2F%2Fapi.flickr.com%2Fservices%2Ffeeds%2Fphotos_public.gne%3Fid%3D30452866%40N06%26amp%3Blang%3Dfr-fr%26amp%3Bformat%3Drss_200) and I [validated it](http://validator.w3.org/feed/check.cgi?url=http://api.flickr.com/services/feeds/photos_public.gne?id=30452866@N06&amp;lang=fr-fr&amp;format=rss_200).
It does not validate but SimplePie can read it. So I should be able to retrieve its content.

I try to add it in the demo and I got the following error:

```
`` is not a valid URL
```

**Comment by Alkarex** [comment]
This feed works fine on my FreshRSS instance (/dev from about a month ago).

**Comment by aledeg** [comment]
I have the beta on my server and this feed was on my instance prior to the past beta update.
When I click on the links in the feed configuration, I can see the feed itself but it is not updated. I don't know since when though.

**Comment by Alkarex** [comment]
If it is a version of FreshRSS that does not report the HTTP response
status code in the logs, you can have a quick check manually:
https://github.com/FreshRSS/FreshRSS/issues/456#issuecomment-61821397

**Comment by aledeg** [comment]
I am not sure what to do.
I did the tests with the two php files. The first one is ok. With the second one, I got the following error:

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /feed was not found on this server.</p>
<p>Additionally, a 404 Not Found
error was encountered while trying to use an ErrorDocument to handle the request.</p>
</body></html>
```

What should I do next?

**Comment by Alkarex** [comment]
You could try with a different string for the user-agent (script #2) and/or
from another IP.

**Comment by aledeg** [comment]
From an other IP it is working :\
That means that accessing it from dreamhost, is no longer possible. I'll contact dreamhost support to see why and how I can change that.
I'll keep that open for the moment to add more information if I have a solution.
Thank you for your help

**Comment by Alkarex** [comment]
You said that the first script was working, so it is probably a bit more
subtle.
Have you tried the script #2 with `curl_setopt($ch, CURLOPT_USERAGENT,
$_SERVER['HTTP_USER_AGENT']);` ?

I have a suspicion that a specific pattern (e.g. user-agent + IP) may have
been banned for excessive requests. At what frequency was this feed set up
to be refreshed?

**Comment by aledeg** [comment]
The frequency is one call per hour. But I have multiple feeds from Flickr. That might be the reason.

I tried the script with the commented line uncommented and I have the same error.

**Comment by Alkarex** [comment]
Ok, did you comment out the second line `curl_setopt($ch, CURLOPT_USERAGENT, 'FreshRSS/0.10-dev...` ?

**Comment by aledeg** [comment]
Yep

**Comment by Alkarex** [comment]
And unfortunately, it does not look like Flickr is supporting
PubSubHubbub...
I do not think we have a bug for that yet, but in order to help avoiding
FreshRSS instances being banned, I would like to implement an automatic
tuning of the refresh frequency, based on the past frequency of
publications, couple with maybe 2 or 3 personal parameters such as "auto
(important)", "auto (normal)", and "auto (save resources)", in addition to
the explicit settings in minutes/hours...

**Comment by aledeg** [comment]
That would be nice.

**Comment by marienfressinaud** [comment]
Good idea but I think priority should be given to support PubSubHubbub (#312)

**Comment by Alkarex** [comment]
It this bug still needed? It looks like it is a host-specific issue, isn't it?

**Comment by aledeg** [comment]
The new version solved the problem.

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/issues/968
