### ISSUE TITLE
[Référencement] Noms des liens

### ISSUE THREAD

**Issue by oussemos** [FreshRSS/FreshRSS#806]
Bonjour,

Ça serait plus apprécié en terme de référencement de renommer les liens selon le nom de la source

Par exemple

http://demo.freshrss.org/i/?get=lifehacker

Au lieu de: http://demo.freshrss.org/i/?get=f_22

Salutations

**Comment by marienfressinaud** [comment]
Ça pose malheureusement des soucis par exemple si un site possède plusieurs flux RSS, comment choisir le bon flux ? D'autant plus que les instances FreshRSS ne sont pas référencées par défaut (voir le robot.txt) et donc cela n'a pas beaucoup d'influence.

**Comment by aledeg** [comment]
Pour moi, il faudrait faire du "URL rewriting" dans la configuration du serveur web. Si il y a de la demande, il serait envisageable de faire un outil qui permette la génération de cette configuration. À voir!
