### ISSUE TITLE
Favicons momentarily disappear when switching tabs on Firefox

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/FreshRSS#808]
Most of the time, I find FreshRSS like that (seems some days/weeks only, probably relative to either a new Firefox update or a recent commit):

![untitled](https://cloud.githubusercontent.com/assets/7189936/6547357/bf231928-c5d5-11e4-990c-1849ef9e606e.png)

When I switch tab and come back. I just have to make the mouse move in the window and the favicons come back immediately. I am unable to test on different browsers for now to see if it is a behaviour of Firefox.

**Comment by marienfressinaud** [comment]
Yes, I have the same problem but I suspect a bug from Firefox 36.0. I noticed several problems since this last update coming from different persons, that's the reason I was waiting the next FF update.

**Comment by aledeg** [comment]
Same here with FF36.0.1, my guess is that it's a FF issue.

**Comment by Alwaysin** [comment]
Still there on 36.0.4.

**Comment by marienfressinaud** [comment]
It seems the bug has disappeared since Firefox 37, hasn't it?

**Comment by Alwaysin** [comment]
Correct! I had totally forget this bug as it wasn't happening anymore.

**Comment by Alkarex** [comment]
Indeed, same with me, I had not noticed :-)
