### ISSUE TITLE
Erreur HTTP/406 avec un flux

### ISSUE THREAD

**Issue by samdolt** [FreshRSS/FreshRSS#809]
Le flux en question: http://fablab-neuch.ch/feed/atom/
![capture d ecran 2015-03-11 a 19 18 22](https://cloud.githubusercontent.com/assets/6305913/6603604/70262720-c823-11e4-8d26-def8eb064bf5.png)

Le flux s'affiche sans avertissemenet avec le lecteur intégré de Firefox

**Comment by aledeg** [comment]
Le problème vient de SimplePie. Si tu essayes ton flux [ici](http://www.simplepie.org/demo/?feed=http%3A%2F%2Ffablab-neuch.ch%2Ffeed%2Fatom%2F), il te renverra la même erreur.

Le flux est bien [valide selon le W3C](http://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Ffablab-neuch.ch%2Ffeed%2Fatom%2F) mais SimplePie refuse de le lire.

Tu devrais soumettre cette demande à l'équipe de SimplePie.

Même si on ne peut rien faire directement dans FreshRSS pour corriger ça, je laisse le ticket ouvert pour que tu puisses nous faire part de tes retours.

**Comment by samdolt** [comment]
J'ai ouvert le ticket chez SimplePie.

https://github.com/simplepie/simplepie/issues/393

Et merci à l'équipe FreshRSS pour ce merveilleux lecteur RSS :+1:

**Comment by Alkarex** [comment]
Le site fablab-neuch.ch semble avoir filtré SimplePie (si c'est volontaire, cela peut être à cause d'utilisateurs qui font trop de requêtes).

``` php
<?php
header('Content-Type: application/xml; charset=UTF-8');

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, 'http://fablab-neuch.ch/feed/atom/');

curl_setopt($ch, CURLOPT_USERAGENT, 'FreshRSS'); //Semble fonctionner
//curl_setopt($ch, CURLOPT_USERAGENT, 'FreshRSS/SimplePie'); //Ne semble pas fonctionner

curl_exec($ch);
curl_close($ch);
```

Vous pouvez essayer de les contacter, ou essayer de manuellement changer l'agent utilisateur utilisé par FreshRSS :
https://github.com/FreshRSS/FreshRSS/blob/01a1179b1ae0ee92234a0ef0a67c3e5d6d0b3c7e/lib/lib_rss.php#L125

Ça m'intéresserait de savoir si c'est volontaire ou pas de la part de fablab-neuch.ch.

Si c'est volontaire, vous pourriez leur suggérer le code `HTTP 429 Too Many Requests` plutôt que le 406 qui est inapproprié et m'a fait perdre un peu de temps dans ma recherche de la cause
http://tools.ietf.org/html/rfc6585#section-4

Dans tous les cas, évitez de mettre une fréquence de rafraîchissement trop importante. Pour un tel flux qui semble avoir moins d'une mise à jour par mois, une fréquence d'une fois tous les 1 ou 2 jours me semble largement suffisante.

De notre côté, le cas me semble clos, et je vous suggère de fermer le bug SimplePie aussi.

**Comment by samdolt** [comment]
Je vais essayer de les contacter pour demander si c'est volontaire.
