### ISSUE TITLE
Display a more reliable message in the notification

### ISSUE THREAD

**Issue by aledeg** [FreshRSS/FreshRSS#810]
At the moment, the notification displays the number of unread articles in the main stream.
The information is not correct because we should either change the wording to `number of unread article in the main stream` or change the calculation method.

For me the later is preferred.

I think we should display the number of new articles regardless of the unread articles already there and regardless of the main stream.

**Comment by Alkarex** [comment]
Do you mean the dynamic favicon and/or the HTML5 notification pop-up?
Fine for me to show the total number of unread articles in both places.

**Comment by aledeg** [comment]
What I mean is if I have 10 unread articles and I get 10 new articles from the update, the message says that I have 20 new articles. It would be nice to have the message saying that I have 10 new articles.

And I was talking about the notifications (HTML5 and webpage). The total number should still be displayed.

**Comment by math-GH** [comment]
@aledeg please have a look into #4193
