### ISSUE TITLE
i18n: Add Czech translation

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#814]
FreshRSS is not available in Czech (yet).

Website told me to open a ticket, so I signed up for github. I'd like to help. Right now, I've translated most of the non-admin part of FreshRSS 1.0. I'll try to « Fix a bug » as suggested.

**Comment by Alkarex** [comment]
Thanks. We look forward to receiving your contribution :-)

**Comment by aledeg** [comment]
:+1:

**Comment by ghost** [comment]
Uh, guys? I need help...
I have the files translated and ready. I even managed to upload them to the right branch of my fork (made a new one, named "814-i18n-czech-translation").
But during test install, instead of "Czech", there was "gen.lang.cz" in the language menu. I'm new to git and have zero knowledge of PHP, so before I try to "pull request" I want to ask if it's OK. Does it need to be (re)generated somehow?
Sorry for my incompetence. I don't want to break anything...

**Comment by aledeg** [comment]
That's because you need to add the Czech language in the appropriate file.
In the i18n/*/gen.php files, you have the list of languages available. Add a new item for Czech in every gen.php files. At the moment, you need to edit 3 files (fr, en, de).
Let me know if it works.

**Comment by ghost** [comment]
That was it! Thank you. Now I'm going to do that "pull request".

**Comment by Alkarex** [comment]
Any news @Tets42 ? Do you need help for the pull request?

**Comment by ghost** [comment]
Sorry, I have been busy the last two weeks, neglecting most of the 
emails. I'll do that tomorrow morning. Also, git is a bit confusing :-D

**Comment by Alkarex** [comment]
No problem :-) I just wanted to ensure that you were not blocked with a
technical problem.
