### ISSUE TITLE
Can't install FreshRSS

### ISSUE THREAD

**Issue by floflo73b** [FreshRSS/FreshRSS#817]
Hi,

I can't go further than the step 2.
It always ask me for an username and a password.
I've nginx/php/mariadb installed.
Does anyone have an idea for solve my problem?
Thanks

**Comment by floflo73b** [comment]
Sorry for the post it was just a own pb
/var/lib/php/ wasn't owned by the group/user of my php server

**Comment by stoinov** [comment]
I have the same issue and I am using the [docker how-to](https://github.com/FreshRSS/FreshRSS/tree/master/Docker) on my ARM64 machine with the [latest release build](https://github.com/FreshRSS/FreshRSS/releases/tag/1.13.1). I don't see `/var/lib/php/` in the container so I am out of ideas here.
One thig I noticed, is that the user get created in the `users` folder after each attempt.

**Comment by Alkarex** [comment]
Hello @stoinov ,
Could you please provide the precise commands you have used to build and run your Docker image?
Do you have a reverse proxy in front, and if yes, which? (e.g. Traefik)
And what database are you using?
