### ISSUE TITLE
[Bug] Page 403 ne peut s'afficher si Translate n'est pas instancié avant

### ISSUE THREAD

**Issue by rivetchip** [FreshRSS/FreshRSS#821]
Bonjour,

Voici une erreur légère, principalement de logique :smile:  
Fichier `app/FreshRSS.php` : `initAuth()` ne peut pas appeler `_t()` si Translate n'est pas instancié avant lui.

Reproduire : retirer l'envoie de l'en-tête HTTP_REFERER, se rendre sur la page de connexion.
Résultat : `Fatal error:  Call to undefined function _t() in FreshRSS.php on line 69`
au lieu d'un affichage de page '403' comme le prévoie la suite du code.

FreshRSS Version : 1.1.0

Salutations.

**Comment by Alkarex** [comment]
Merci, c'est corrigé dans la [branche /dev](https://github.com/FreshRSS/FreshRSS/tree/dev). N'hésitez pas à essayer et à confirmer si possible.
