### ISSUE TITLE
adding upgrade instructions to readme.md

### ISSUE THREAD

**Issue by yafp** [FreshRSS/FreshRSS#822]
I guess adding upgrade instructions to readme.md could be a useful additional step for most users.

**Comment by yafp** [comment]
The following issue is a dupe - #861

**Comment by Alkarex** [comment]
@yafp Thanks. I have added some minimal information in the README https://github.com/FreshRSS/FreshRSS/blob/beta/README.md#example-of-full-installation-on-linux-debianubuntu for manual update (git). The automatic process will help, but we will wait for Marien to be back.

**Comment by Alkarex** [comment]
Continues in https://github.com/FreshRSS/FreshRSS/issues/861
