### ISSUE TITLE
SQL: Search problem

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#823]
Somewhere during a recent refactoring, the search behaviour has been changed. It does not seem possible anymore to search for multiple independent keywords.

Now when searching for e.g. `employee stack`, the SQL is `LIKE '%employee stack%'`, meaning that the search input is treated like it had quotes `"employee stack"`.

**Comment by aledeg** [comment]
I will have a look at that

**Comment by Alkarex** [comment]
Thanks :-) BTW, it would be nice to be able to search for `"employee stack"` too, in the future

**Comment by aledeg** [comment]
that's my plan :)

**Comment by Alkarex** [comment]
FWIW, the latest version of Ubuntu (15.04) ships with MySQL 5.6, first version of MySQL to support full-text indexes on InnoDB http://dev.mysql.com/doc/refman/5.6/en/fulltext-search.html
https://github.com/FreshRSS/FreshRSS/issues/302

**Comment by Alkarex** [comment]
Solved by @aledeg
