### ISSUE TITLE
SQLite: Error refreshing feeds

### ISSUE THREAD

**Issue by Jucgshu** [FreshRSS/FreshRSS#830]
Tried updating FreshRSS with dev branch yesterday and wasn't able to refresh anything since then.

Here's an error thrown in /tmp/FreshRSS.log
`PHP Fatal error:  Call to a member function bindParam() on boolean in /FreshRSS/app/Models/FeedDAO.php on line 335`

And another one in data/users/my-user/log.txt
`[error] --- SQL error addEntry: :  syntax error while adding entry in feed 70 with title: blablabla`

Is it just me ?
- Php 5.6.8
- Sqlite 3.8.9

**Comment by Alkarex** [comment]
I will look at it tonight. For SQLite, there is already a pending patch https://github.com/FreshRSS/FreshRSS/pull/828 but you found another problem.

**Comment by Alkarex** [comment]
Sorry for the bug. In the meantime, this version from a few days ago should work with SQLite https://github.com/FreshRSS/FreshRSS/tree/d229216cccbd746b46630a44fa508ef0367ea1a1

**Comment by Jucgshu** [comment]
No worries, I can wait until you have the time to look at it. Tell me if you need more logs or anything :-)

**Comment by Alkarex** [comment]
@Jucgshu I can see that there were a few compatibility problems with SQLite and the new update mode, mainly when updating from a previous version. My current patch https://github.com/FreshRSS/FreshRSS/issues/828 ( https://github.com/Alkarex/FreshRSS/tree/sqliteBug ) seems to work, including the update from previous versions (no need to run the installer, should be automatic).
It is not very well tested yet, so please make a backup of anything valuable before :-)

**Comment by Jucgshu** [comment]
Just did a git pull and the first feeds refresh went ok. 

I still have some errors in /temp/FreshRSS.log but I'm not sure it's related :

``PHP Warning:  DOMDocument::loadXML(): XML declaration allowed only at the start of the document in Entity, line: 9 in FreshRSS/lib/SimplePie/SimplePie/Parser.php on line 145

PHP Warning:  DOMDocument::loadXML(): XML declaration allowed only at the start of the document in Entity, line: 9 in FreshRSS/lib/SimplePie/SimplePie/Parser.php on line 145

PHP Warning:  DOMDocument::loadXML(): CData section not finished
A lazy desktop for lazy people! GNOME Foundation r in Entity, line: 38 in FreshRSS/lib/SimplePie/SimplePie/Parser.php on line 145

PHP Warning:  DOMDocument::loadXML(): Premature end of data in tag description line 38 in Entity, line: 38 in FreshRSS/lib/SimplePie/SimplePie/Parser.php on line 145

PHP Warning:  DOMDocument::loadXML(): Premature end of data in tag item line 28 in Entity, line: 38 in FreshRSS/lib/SimplePie/SimplePie/Parser.php on line 145

PHP Warning:  DOMDocument::loadXML(): Premature end of data in tag channel line 18 in Entity, line: 38 in FreshRSS/lib/SimplePie/SimplePie/Parser.php on line 145

PHP Warning:  DOMDocument::loadXML(): Premature end of data in tag rss line 9 in Entity, line: 38 in FreshRSS/lib/SimplePie/SimplePie/Parser.php on line 145

PHP Warning:  DOMDocument::loadXML(): XML declaration allowed only at the start of the document in Entity, line: 9 in FreshRSS/lib/SimplePie/SimplePie/Parser.php on line 145

PHP Notice: This XML document is invalid, likely due to invalid characters. XML error: Reserved XML Name at line 2, column 39 in FreshRSS/lib/SimplePie/SimplePie.php on line 1461``

**Comment by Alkarex** [comment]
Thanks for testing :-) Those other errors are indeed not related, and occur when RSS feeds are not fully valid.

**Comment by Alkarex** [comment]
Seems to be fixed. Now merged in the normal /dev branch. Please let me know if you notice any problem, @Jucgshu.

**Comment by Jucgshu** [comment]
@Alkarex 

I switched back to the regular dev branch. Everything seems ok. I'll let you know if anything goes wrong.

Thanx for having fixed this nasty bug :-)
