### ISSUE TITLE
Framasoft

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#833]
(En français, vue la cible)

Méta-bug pour suivre les tâches et discussions relatives au développement d'une solution proposée à [Framasoft](http://www.framasoft.net).

FreshRSS a déjà eu l'honneur d'être mentionné sur http://degooglisons-internet.org mais doit s'améliorer pour poursuivre dans cette voie.
![libristest](http://degooglisons-internet.org/img/carte-full.jpg) 

Voir aussi le [tag Framasoft](https://github.com/FreshRSS/FreshRSS/labels/Framasoft) dédié.

**Comment by aledeg** [comment]
C'est une bonne idée d'avoir ajouté ce tag

**Comment by lapineige** [comment]
Content de voir que Framasoft envisage de proposer ce service :)

On va pouvoir en faire encore plus la promotion ;)

**Comment by Alkarex** [comment]
@lapineige C'est beaucoup s'avancer que de dire que Framasoft envisage de proposer ce service. Plus humblement, ce tag regroupe les fonctions qui ont été plus ou moins demandées pour aller dans ce sens là. C'est potentiellement aussi utile pour, par exemple, Yunohost, et [CHATONS](https://chatons.org/).

**Comment by lapineige** [comment]
Ah, c'est ce que j'avais cru comprendre, un peu trop enthousiaste peut-être ^^

> C'est potentiellement aussi utile pour, par exemple, Yunohost, et CHATONS.

Alors c'est une bonne chose :D

**Comment by marienfressinaud** [comment]
Je ferme le ticket : la plupart des demandes qui avaient été identifiées ont été résolues et de toutes façons il n'est clairement plus question de ça, on va même fermer Framanews ;)
