### ISSUE TITLE
Question....

### ISSUE THREAD

**Issue by ReneMuetti** [FreshRSS/FreshRSS#846]
Hello

I think the Super Pusher. Seeking something similar for a very long time.
Could you please give me the necessary information, I can create me a similar Notifigation service.
many Thanks

**Comment by Alkarex** [comment]
Hello @ReneMuetti ,
I am not sure to understand your question, but maybe the upcoming push feature will have your interest: https://github.com/FreshRSS/FreshRSS/issues/312#issuecomment-102414760
https://github.com/FreshRSS/FreshRSS/pull/831

**Comment by Alkarex** [comment]
Feel free to re-open the question if my previous answer was not enough.
