### ISSUE TITLE
Number of entries in stream

### ISSUE THREAD

**Issue by subzero79** [FreshRSS/FreshRSS#848]
I've looked around issues but i couldn't find my answer.

I am trying to get a rss stream with a number of entries greater than 20, i tried to add n=50 to the URL but it didn't work.
http://server.com/freshrss/p/i/?a=rss&n=50&get=f_2

Can someone enlighten me how's this achieved? in tt-rss this can be done with the &limit= appended to the URL.

**Comment by Alkarex** [comment]
Hello @subzero79,
We use the `nb` parameter, as such: `http://example.com/freshrss/p/i/?a=rss&nb=50&get=f_2`.
If it is not at the end, it will return n+1 entries.

While looking at your question, I have found a small bug in the `self` attribute of the generated feed, which will soon be corrected in the /dev branch https://github.com/Alkarex/FreshRSS/commit/27d2b88a19345dfc665dc086d3c2b2e4547e1b7f

**Comment by subzero79** [comment]
Thanks very much @Alkarex . It works now. 
BTW great project.

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/pull/1251
