### ISSUE TITLE
Export function with "export favorites" is broken

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/FreshRSS#850]
Having "Export your favourites" checked and no favourites, when trying to export I'm provided with a blank page. Unchecking "Export your favourites" resulted in a successful download of the file.

EDIT : same with a favourite.

**Comment by Alkarex** [comment]
Thanks. Should be corrected in /dev https://github.com/FreshRSS/FreshRSS/commit/9d55ee5ae9e41fe460ff82b4d51bf1673fb1b836

**Comment by Alwaysin** [comment]
Positive :+1:
