### ISSUE TITLE
FreshRSS : how to change the database ?

### ISSUE THREAD

**Issue by cmtm78** [FreshRSS/FreshRSS#852]
Hello

I have FreshRSS running on a serveur a database..

I'd like to continue use Fresh RSS without reinstalling all but changing the database (other name, other password).

What should I do ? Where are the name of the database and its password coded ?

Thank you for your help.

T

**Comment by Alkarex** [comment]
Hello,
This information is stored in `./data/config.php`, and you can change the database host, user, password there. You may want to use something like `mysqldump` to export your current database. See more on https://github.com/FreshRSS/FreshRSS/blob/beta/README.md#backup

**Comment by cmtm78** [comment]
It worked perfectly

Thanks

T

**Comment by Alkarex** [comment]
:-)
