### ISSUE TITLE
Date/Time Formatting Enhancements

### ISSUE THREAD

**Issue by jgeboski** [FreshRSS/FreshRSS#853]
Two simple suggestions for the date/time formatting:
- Add support for 12-hour time
- Add support for local time

**Comment by Alkarex** [comment]
@jgeboski When you say local time, do you mean an option to specify the user's timezone that is different than the timezone on the server hosting this user? Currently (if there is no mistake), the time is shown according to the timezone settings on the server hosting FreshRSS (php.ini, date.timezone).

**Comment by jgeboski** [comment]
Correct, I am referring to the time zone present within the browsing session.

**Comment by aledeg** [comment]
I leave [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset) here for information.

**Comment by Frenzie** [comment]
Note that where it says
```html
<li class="item date">September 1<sup>st</sup> 2017 at 14:56&nbsp;</li>
```
It should be changed to something like
```html
<li class="item date"><time datetime="2017-09-01 14:56">September 1<sup>st</sup> 2017 at 14:56</time>&nbsp;</li>

Then you can easily do whatever you want with it.

**Comment by Alkarex** [comment]
Good idea @Frenzie

**Comment by aledeg** [comment]
@jgeboski I've just added an extension to customize how dates are displayed. It's available [here](https://github.com/aledeg/FreshRSS-extensions/tree/master/xExtension-DateFormat). Let me know what you think.

**Comment by aledeg** [comment]
The issue has been addressed, there is no feedback from @jgeboski. I think it's time we close this.

**Comment by Alkarex** [comment]
@aledeg You extension does not offer different time zone per user, does it? Maybe we could keep an issue for this aspect

**Comment by aledeg** [comment]
@Alkarex You're right, it does not support different timezone per user. But this is not what was requested at the first place. I think you get confused with issue #2754.
This one is only about formatting the date. The other is for the timezone support.

**Comment by Alkarex** [comment]
Ok, let's continue in https://github.com/FreshRSS/FreshRSS/issues/2754 for the timezone part
