### ISSUE TITLE
Frustrating behaviour with keyboard navigation during installation

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/FreshRSS#855]
As stated there : https://github.com/FreshRSS/FreshRSS/issues/845#issuecomment-104945935

> On step 2 of configuration, the field "Authentication method" is very frustrating when navigating with the keyboard. It automatically teleport you to the next field when trying to select the authentication you want.

**Comment by aledeg** [comment]
Could you provide a little more information? I tried to replicate a weird behavior on that field but everything seems normal.
I am using FF38 on ArchLinux and it is working fine.
I need a more detailed description to continue working on that!

Thanks

**Comment by Alwaysin** [comment]
Indeed in Firefox no problem, but in Chrome and Internet Explorer (all latest versions) there is the behaviour I've described.

**Comment by aledeg** [comment]
Ok, I'll look at that.

**Comment by aledeg** [comment]
I reproduced the behavior and it's indeed frustrating. I removed the auto-focus because there is no value to it in the install process.

**Comment by Alwaysin** [comment]
Thanks!
