### ISSUE TITLE
Automatically change strings when changing language

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/FreshRSS#857]
As stated here : https://github.com/FreshRSS/FreshRSS/issues/845#issuecomment-104421126

> it could be nice to automatically change the strings to the language selected so that no one will be lost if they do not speak French

This was considering there was a bug which made the default language picked up being French. However if for some reason the auto-detection is not working or the user is using a browser in a different language than theirs, changing the language of the page "on-the-fly" when selected could be great.

Feel free to close if not interesting/not feasible.

**Comment by aledeg** [comment]
As mentioned by @Alkarex, this will add a similar problem as the one encountered in #855. That's the reason I closed #866.

I think there is no real value of working on that. I suggest we close that issue.

**Comment by Alwaysin** [comment]
As you want, it was just a suggestion ^^

**Comment by Alkarex** [comment]
I have just checked: with a Web browser that is set up with English as the preferred language, or with a list of language that does not contain any language known by FreshRSS, then English is automatically used. So it seems to work as expected.

@Alwaysin You probably had French higher than English in your list of languages in the parameters of your Web browser. Feel free to re-open if you still believe there is a bug, but then please provide the HTTP headers sent by your browser, such as `Accept-Language: fr-FR,fr;q=0.8,en-GB;q=0.6,en;q=0.4,da;q=0.2`. You can for instance see them with https://addons.mozilla.org/firefox/addon/live-http-headers/ or other Web programming tools.
