### ISSUE TITLE
Remove "title" field when installing

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/FreshRSS#858]
As stated here : https://github.com/FreshRSS/FreshRSS/issues/845#issuecomment-104421126

> Not sure about "Installation · FreshRSS" field. I think it is the name which will then be used in the title but it could be more descriptive.

I think this field is confusing and has no real usefulness.

**Comment by aledeg** [comment]
The name is confusing but there is a real use of it.
When you want to have a specific name for your installation (like for Framasoft), it is useful to name it the way you want.
I agree we need a better name since I had to make the full install to understand what was the use of it.

Maybe we could rename it to **Instance name** or something similar.

**Comment by Alkarex** [comment]
I think we could keep the functionality, but remove it from the install process since it is not an essential feature, just like many other settings we have.

**Comment by aledeg** [comment]
I think the more we can add in the installation process, the better.
We can argue why, but it is only what I feel. I hate when a software has a lot of steps after installation to finish configuration. I like the way of Symfony that has a hook on composer that allows to configure the application at the end of installation. There is default values if you don't want to configure after installation.

We could have either default values for all non mandatory fields or have 2 path of installation (regular and custom).

**Comment by aledeg** [comment]
Any insight for that?
I just checked the interface and I can't find where to modify this value. Is it available somewhere I am not aware of?

**Comment by Alkarex** [comment]
It is the first field of step 2. But the translation of the label `install.title` is misleading indeed:
![clipboard01](https://cloud.githubusercontent.com/assets/1008324/8023426/6444b826-0d0c-11e5-963d-8306d67ae70b.png)

**Comment by aledeg** [comment]
I got that one. I was wandering after install, is there a way to change it from the interface. So far I found only the value in the configuration file.

**Comment by Alkarex** [comment]
Indeed, after install, it can only be changed from the config file.

**Comment by aledeg** [comment]
So I guess we should keep it during install.

**Comment by marienfressinaud** [comment]
I feel like @Alkarex that we don't need this information during installation (such as the "remove articles after…"). But it still can be useful to administrators who want to have specific configuration so I suggest to ask the user at the end if he wants to continue to configure additional options.

**Comment by aledeg** [comment]
@marienfressinaud Or we can add it in the new "system configuration" page.
Let me know what you think, so I can include that in #958

**Comment by marienfressinaud** [comment]
Let's go! I'm not sure if it's useful but since several persons asked for it, I think we can include it.

**Comment by aledeg** [comment]
OK, I'll do that tonight!

**Comment by Alwaysin** [comment]
I think we can now close? EDIT: still there, was it included in #958? EDIT#2: strange think I had to update on a new installation to have the latest commits. (have used `wget https://github.com/marienfressinaud/FreshRSS/archive/dev.zip`)

Also, quick suggestion which probably does not need a new issue: when on the first step (vérifications), why not add a "reload" or "re-check" button when not all is green?

**Comment by Alkarex** [comment]
@Alwaysin The  official repository for /dev is https://github.com/FreshRSS/FreshRSS/archive/dev.zip
Good suggestion with _reload_. Could you please create a new ticket?

**Comment by Alwaysin** [comment]
Whoop, sorry for the mistake!
Ok done: #964

**Comment by Alwaysin** [comment]
By the way, I still don't understand why there is "submit" and "go to the next step" on the first installation page.

**Comment by Alkarex** [comment]
Please test https://github.com/FreshRSS/FreshRSS/pull/1012
