### ISSUE TITLE
Add a feed by default

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/FreshRSS#859]
As stated here : https://github.com/FreshRSS/FreshRSS/issues/845#issuecomment-104421126

> why not maybe add a feed by default? Marien spoke about a specific feed for FreshRSS news that he wants to create, if I recall correctly.

**Comment by Alkarex** [comment]
Suggestion in https://github.com/FreshRSS/FreshRSS/pull/886

**Comment by marienfressinaud** [comment]
Merged. I don't think we need to add more feeds by default, what do you think?

**Comment by Alkarex** [comment]
I think it is good enough, indeed.
