### ISSUE TITLE
Sticky Feeds looks broken with latest pull

### ISSUE THREAD

**Issue by Jucgshu** [FreshRSS/FreshRSS#862]
Sticky Feeds looks broken with last commits. 

I dont' use the other two extensions, so I can't tell whether the problem is the Sticky Feeds extension or the extensions themselves.

Don't hesitate to ask for logs/whatever :-)

**Comment by Alkarex** [comment]
Reference https://github.com/FreshRSS/Extensions/tree/master/xExtension-StickyFeeds

**Comment by marienfressinaud** [comment]
All the extensions which use additional script / style files are broken. Bug is in https://github.com/FreshRSS/FreshRSS/blob/beta/lib/Minz/Extension.php#L171 and it has been highlighted by https://github.com/FreshRSS/FreshRSS/commit/a5a24108 (but the patch was incomplete :p)

I'm writing the complete patch.

**Comment by Alkarex** [comment]
@Jucgshu Could you please test again the current /dev ?

**Comment by Jucgshu** [comment]
Yup, it's working.

Thanx guys !
