### ISSUE TITLE
PubSubHubbub: base_url

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#865]
https://github.com/FreshRSS/FreshRSS/issues/312#issuecomment-102414760
- [x] Generate `base_url` during install
- [x] Check if `base_url` is public? (optional)
- [ ] Documentation

**Comment by Alkarex** [comment]
Needs https://github.com/FreshRSS/FreshRSS/issues/890

**Comment by Alkarex** [comment]
If `base_url` is not public, then PubSubHubbub should not try to subscribe.
Probably, if `base_url` is not public, we should just leave it empty (or add another option/flag).

**Comment by marienfressinaud** [comment]
I would prefer to add a flag since a user can change the config himself

**Comment by marienfressinaud** [comment]
I wrote a very basic test at https://github.com/marienfressinaud/FreshRSS/commit/339e32424fa60fc0c99a4c10890abef139444f6d but I'm not sure where I should use `enable_pubsubhubbub` (`Feed->pubSubHubbubEnabled`? `Feed->pubSubHubbubSubscribe`? `feedController`?)

**Comment by Alkarex** [comment]
Two possibilities:
- https://github.com/marienfressinaud/FreshRSS/blob/339e32424fa60fc0c99a4c10890abef139444f6d/app/Controllers/feedController.php#L445
- https://github.com/marienfressinaud/FreshRSS/blob/339e32424fa60fc0c99a4c10890abef139444f6d/app/Models/Feed.php#L391

In both cases, just before the `if` or as the first statement of the `if`.
It depends if you think it is better to have this test in a controller or in a model.
Probably doing the test in the controller (first option) is cleaner, but I do not have strong feelings either way.

P.S.: Indeed, now that we have another option to turn PubSubHubbub on/off, it could be good to be clear about the role of `pubSubHubbubEnabled()`: it checks that the system is in place, has worked, and has not expired. Maybe this function could be renamed to e.g. `pubSubHubbubWorking()` or something.

**Comment by Alkarex** [comment]
If done in the controller, for performance, it would be good to add a check on https://github.com/marienfressinaud/FreshRSS/blob/339e32424fa60fc0c99a4c10890abef139444f6d/app/Controllers/feedController.php#L305 : get the configuration flag before the loop, and do not call `pubSubHubbubEnabled()´ if PubSubHubbub is disabled in the configuration

**Comment by marienfressinaud** [comment]
PR opened at https://github.com/FreshRSS/FreshRSS/pull/917 but I think we can improve it.

Note we will have to generate `base_url` and set `pubsubhubbub_enabled` during an update too.

**Comment by Alkarex** [comment]
Not very important/urgent, but due to the new option to disable PubSubHubbub, we should maybe update the UI. Currently, when a user changes the config from enabled to disabled, this UI will remain active until PubSubHubbub expires - typically a few days - (which also makes sense, because we will continue receiving updates even when the option is off, because we currently do not unsubscribe when the config changes)
![p](https://cloud.githubusercontent.com/assets/1008324/8850413/3b2c8558-3148-11e5-9242-e20378a1b437.png)

**Comment by marienfressinaud** [comment]
What do you think we should do? Since we can still receive articles, it's fine for me to let it unchanged.

**Comment by Alkarex** [comment]
Fine indeed, at least for 1.1.2.
