### ISSUE TITLE
MySQL over SSL

### ISSUE THREAD

**Issue by nikaro** [FreshRSS/FreshRSS#868]
Hello,

It would be nice to add the support of MySQL database connection over SSL/TLS. Otherwise, if you use a remote SQL server, the connection is not secure.

Thanks :smiley:

**Comment by Alkarex** [comment]
For reference http://php.net/ref.pdo-mysql#103501

**Comment by Alkarex** [comment]
@NicolasKAROLAK Are you using client keys like in the example below?

``` php
array (
    PDO::MYSQL_ATTR_SSL_KEY     => '/path/to/client-key.pem',
    PDO::MYSQL_ATTR_SSL_CERT    => '/path/to/client-cert.pem',
    PDO::MYSQL_ATTR_SSL_CA      => '/path/to/ca-cert.pem',
)
```

**Comment by aledeg** [comment]
:+1:

**Comment by Alkarex** [comment]
@aledeg Is it also this mechanism with the certificate that you would like?

**Comment by nikaro** [comment]
@Alkarex yes I am.

**Comment by aledeg** [comment]
@Alkarex Actually I don't need it but I think it is a good idea :)

**Comment by Alkarex** [comment]
See my suggestion (not tested at all): https://github.com/FreshRSS/FreshRSS/pull/869
In your `data/config.php`, you should be able to have something like:

``` php
'db' => array(
    'type' => 'mysql',

    ...,

    'pdo_options' => array(
        PDO::MYSQL_ATTR_SSL_KEY     => '/path/to/client-key.pem',
        PDO::MYSQL_ATTR_SSL_CERT    => '/path/to/client-cert.pem',
        PDO::MYSQL_ATTR_SSL_CA      => '/path/to/ca-cert.pem',
    ),
),
```

**Comment by nikaro** [comment]
Just tested it, and... it works ! :smile: 
Thanks.

**Comment by Alkarex** [comment]
The work about loading the existing config continues in https://github.com/FreshRSS/FreshRSS/issues/890 and if there is a need to have a UI, it can be another issue too.
