### ISSUE TITLE
Wrong character encoding after auto-load of following articles (UTF-8?)

### ISSUE THREAD

**Issue by minami-o** [FreshRSS/FreshRSS#870]
Hi there, and thanks for the hard work!
I noticed in version 1.1.0 an issue with the "auto-load of following articles" feature: all accentuated & exotic characters displayed on the page (ie. header, whole article but also hardcoded parts) after you have reached the bottom of your screen and remaining articles are auto-loaded are wrong, shown as if character encoding were no longer correct.
I'm sure this didn't happen with earlier versions and I don't think it is related to my own setup.
Well, I recently upgraded my Apache webserver from 2.2 to 2.4, but I'm pretty sure it's unrelated, as I didn't observe such behaviour in any of the other services it handles.
Pic1: first two articles were directly displayed, last two articles were displayed by the auto-load feature. Note that non-article, "hardcoded" texts are also concerned by the bug, like the date.
![image](https://cloud.githubusercontent.com/assets/3458254/7982865/f01e3a42-0aba-11e5-982c-f95069f96538.png)

Pic2: same articles, after I have read an article on top of them and reloaded the page (all articles shifted by 1). This demonstrate that it's not the article/feed which is wrong, but really the auto-load feature.
![image](https://cloud.githubusercontent.com/assets/3458254/7982888/2a5f7248-0abb-11e5-8105-8025476473db.png)

I have all green in the installation check, and for the sake of completeness I'm running:
- FreshRSS 1.1.0
- PHP 5.5.9-1ubuntu4.9
- apache 2.4.7 (Ubuntu)
- MariaDB (latest version available on ubuntu 14.10, can't check right now)
- on an ubuntu server 14.10 hosted externally (vps) .

I found no logs for this specific auto-load action.

To reproduce this issue:
- check that the auto-load checkbox is ticked in the Reading menu (5th box)
- set the number of articles to display to a small number
- make sure you have accentuated/exotic characters present in at least one of your feeds or feeds' header

Any help appreciated!

Edit: this bug was only seen on Chromium for W7 until now, it might or not be specific to Chrome/Chromium or W7...

**Comment by Alkarex** [comment]
@minami-o Thanks for the bug report. I cannot reproduce your bug on my system. Could you please try this little patch? https://github.com/FreshRSS/FreshRSS/pull/873

**Comment by Alkarex** [comment]
If this is not enough, please send me the HTTP header logs received by your browser (for instance by using this extension https://addons.mozilla.org/firefox/addon/live-http-headers/ )

**Comment by minami-o** [comment]
Many thanks for your quick help, that dit the trick!
Now that you mention it, I happened to see this bug only in Chromium for Windows 7 (v44.0.2395.0/64bits), amongst the different setups I had the occasion to test (Firefox on gentoo & W7, Chromium on W7).
I'll edit the OP to specify this.
Thanks again!
