### ISSUE TITLE
Augmentation du nombre d'article chargés

### ISSUE THREAD

**Issue by Draky50110** [FreshRSS/FreshRSS#872]
Salut

Depuis je ne sais plus quelle version, l'affichage est limité à 50 articles.
Est-ce possible d'augmenter la limite ?
Genre 999 ?
Ou 500 ?

Merci.

**Comment by Alkarex** [comment]
@Draky50110 Avez-vous essayé l'option "Charger les articles suivants en bas de page" ?

**Comment by Draky50110** [comment]
Je connais ça.
Je voudrais que justement ça se charge directement.
J'ai un flux de disons... 700 entrées non lues.
Avec une connexion Internet plus lente que le Minitel.
Au final, il me faut un gros bout de temps pour tout charger sachant que je dois les lire/parcourir depuis le début des non lues.
Et c'était possible "avant" car j'avais mis 150 je crois de mémoire ce qui permet de "charger plus" seulement 2 ou 3 fois alors que là ce matin pour afficher mes 700 j'ai mis 30 minutes :/

**Comment by Alkarex** [comment]
Ok, je vois. C'est fait (500) dans /dev https://github.com/FreshRSS/FreshRSS/commit/ff9091e4a0373fc2b8331fe1672f784cec6cc666

**Comment by Draky50110** [comment]
Merci :)
