### ISSUE TITLE
Get articles full content including images with data-src

### ISSUE THREAD

**Issue by imagoiq** [FreshRSS/FreshRSS#877]
Hi,
I've the feed rue89 in my freshrss and I used the "flux tronqué" feature which documented here (with the same example) : http://doc.freshrss.org/doku.php?id=fr:users:configuration:feeds
I get the full article but the pictures don't show up (just have a big space inbetween).
When I look at the code it seems that it produce wrong base64 image.
#### The code on my freshrss

```
<img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-src="http://rue89.nouvelobs.com/sites/news/files/styles/asset_img_full/public/assets/image/2015/06/lunettes-soleil-futuristes.jpg" alt="" lazyload="" postpone="" width="464" height="290">
```
#### The code on rue89 website

```
<img src="http://rue89.nouvelobs.com/sites/news/files/styles/asset_img_full/public/assets/image/2015/06/lunettes-soleil-futuristes.jpg" alt="" width="464" height="290">
```

Can you help me ? Thanks in advance

**Comment by Alkarex** [comment]
Bonjour (en français, petite exception :-p),
Quelle version de FreshRSS est-ce que vous utilisez ? Je pense que c'est un problème de `data-src` utilisé pour le chargement différé des images (les versions récentes de FreshRSS sont un peu différentes). Veuillez vérifier que vous n'avez pas d'erreur JavaScript (console du navigateur). Vous pouvez aussi essayer de désactiver le chargement différé des images dans les préférences de FreshRSS.

Pour info, @marienfressinaud a prévu de refondre le système de récupération du contenu (que je n'utilise pas moi-même donc je ne le connais pas bien) https://github.com/FreshRSS/FreshRSS/issues/661#issuecomment-59077713 https://github.com/FreshRSS/FreshRSS/issues/319

**Comment by imagoiq** [comment]
Hello, j'ai actuellement la 1.1.1 béta, mais j'avais le même problème avec la 1.0
Je n'ai aucune erreur javascript et il semble que désactiver le chargement différé ne change pas le comportement sur les nouveaux articles.
Oui, j'ai vu le #319, mais comme ça date un peu, je ne sais pas trop pour quand c'est prévu.
Bref, il me reste plus qu'à attendre, je crois ?

Merci

**Comment by marienfressinaud** [comment]
Pour quand c'est prévu... Mmm, aucune idée ! Il n'y a pas de date, juste une attente de temps disponible et de motivation ;)

**Comment by Alkarex** [comment]
@Pangolun Je vais essayer de tester. Ce `data-src` ne devrait plus être présent dans les versions récentes de FreshRSS (comme la 1.1.1 béta). Piste : peut-être un problème de mise à jour.

**Comment by Alkarex** [comment]
I have just checked again, and the `data-src` comes from the original Web site (you must look at the original source code, not the DOM inspect code, which might have been modified by JavaScript). Here is your example:

``` html
<div class="image fullsize">
<a href="http://rue89.nouvelobs.com/sites/news/files/assets/image/2015/06/lunettes-soleil-futuristes.jpg" class="colorbox cboxElement" title="Lunettes de soleil futuristes">
<img src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" onload="lzld(this)" data-src="http://rue89.nouvelobs.com/sites/news/files/styles/asset_img_full/public/assets/image/2015/06/lunettes-soleil-futuristes.jpg" width="464" height="290" alt="" /></a>
<br />
<p class="legend">Lunettes de soleil futuristes <a href="http://commons.wikimedia.org/wiki/File:Herman_den_Blijker.jpg">(Wim de Jong/Wikimedia Commons/CC)</a></p>
</div>
```

I will try to do something anyway.

**Comment by Alkarex** [comment]
@Pangolun Here is a patch https://github.com/FreshRSS/FreshRSS/issues/888
Please let me know if you could test it.
P.S. If you are not familiar with git, you can just replace manually `./lib/lib_rss.php` with https://github.com/Alkarex/FreshRSS/blob/fullContentDataSrc/lib/lib_rss.php

**Comment by imagoiq** [comment]
I tested with new articles and it seems all the pictures are showing correctly now! Thanks!
