### ISSUE TITLE
Translation mistake - Actualise in english

### ISSUE THREAD

**Issue by yafp** [FreshRSS/FreshRSS#878]
Hi,

i installed FreshRSS (1.1.1-beta) yesterday again on a host - setup language is english.
If i do fetch for new articles the notification displays the string "Actualise".
The rest of the notification is properly translated into english.

**Comment by Alkarex** [comment]
What is the problem? "actualise" is proper (British) English. It could be with a 'z' to follow Oxford's convention, but 's' is fine too. https://en.wiktionary.org/wiki/actualise#Verb Do you maybe suggest using the present participle instead? (actualising)

**Comment by yafp** [comment]
doh - my stupid brain forwarded my to french  - you are 100% right.
Sorry for the unneeded issue.

I'll close it asap.

Sidenote: 
"updating" or "fetching" would still match better from my point of view - but thats another story.

**Comment by Alkarex** [comment]
Ok :-) Feel free to send a pull request with another suggestion, so that we can consider it.
