### ISSUE TITLE
Boolean search operators

### ISSUE THREAD

**Issue by subzero79** [FreshRSS/FreshRSS#879]
Are advanced search filter ops supported? I was looking for OR (like |) or NOT (like ! or -) but none of them worked, switched to beta to find that quoted strings work but the others not.

Thanks

**Comment by Alkarex** [comment]
Hello @subzero79 
All search parameters (e.g. tag searching, title, url, author, date...) are currently implicitly AND. We do not have OR or NOT, but it would be a welcome addition.

**Comment by subzero79** [comment]
Ok. Thanks very much for the response. I'll wait until it comes. 
Thanks again for the response

**Comment by aledeg** [comment]
Any idea how we could support that?

If we write something like

```
intitle:blabla -inurl:bla
```

it's easy to understand that we want to match title and do not match on url.

But if we write something like

```
intitle:blabla |inurl:bla blablabla
```

how will the OR apply?

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/issues/1189

**Comment by Alkarex** [comment]
Negative searches implemented in https://github.com/FreshRSS/FreshRSS/issues/1478

**Comment by GLLM** [comment]
Praying for the day the OR arrives :) :) :)

**Comment by Alkarex** [comment]
You are welcome to test https://github.com/FreshRSS/FreshRSS/pull/1828
