### ISSUE TITLE
Allow to set the category of a feed before validating

### ISSUE THREAD

**Issue by ZeHiro** [FreshRSS/FreshRSS#882]
Hi,

when adding a feed to feedly, it is necessary to : 
- Go to the manage feed section
- Pasty the feed url
- Validate the import
- Set the category
- Validate the new category

To remove one click, it would be nice to be able to set the category of the feed before validating the import. This would gain a click

Enventually, it could be nice to have an automatic redirection to the main feed once a feed is added (but this is only the behaviour I would prefer)

**Comment by Alkarex** [comment]
Hello @ZeHiro 
It is already possible to select the category at the same time than when adding the feed :-)

![category](https://cloud.githubusercontent.com/assets/1008324/8507248/846a2792-223a-11e5-9b7b-442b6f2c8eb3.png)

**Comment by ZeHiro** [comment]
OK perfect :)
