### ISSUE TITLE
Marquer automatiquement les articles comme lu

### ISSUE THREAD

**Issue by hashtagpaul** [FreshRSS/FreshRSS#883]
Bonjour,

Je cherche à marquer comme lu tous les articles après 24 heures sans lecture.

Si pas possible peut-on le faire via cron ?

**Comment by Alwaysin** [comment]
Voir #824 qui est la même chose.

Actuellement ce n'est possible que manuellement avec le menu "marquer comme lu, plus d'un jour".

**Comment by hashtagpaul** [comment]
oui effectivement !

Est-ce qu'il est possible de lancer le script "marquer comme lu, plus d'un jour" via le serveur en cron ?

**Comment by Alwaysin** [comment]
Si j'en crois la réponse d'Alkarex dans le thread mentionné, non. Ce n'est pas un script à proprement parler, mais ce doit être une fonction dans le code. Peut-être qu'il serait possible d'appeler cette fonction à partir d'un script que tu lançerai en cron effectivement, mais il faut regarder le code. Je ne suis pas développeur donc je ne pourrais pas t'aider plus malheureusement.

**Comment by hashtagpaul** [comment]
dac merci !

**Comment by Alkarex** [comment]
@hashtagpaul Effectivement, comme le dit @Alwaysin, ce n'est pas intégré actuellement, même s'il serait possible de formuler une requête cURL pointant sur `http://freshrss.example/i/?c=entry&a=read&get=a&nextGet=a&idMax=1435010400000000` où 1435010400000000 est calculée pour être la date maximale (en millisecondes) à marquer comme lue, et en passant un _Referer_ valide, et un login valide (facile dans le cas d'un login HTTP). Le mieux serait via une extension (pas encore possible).
Je ferme le ticket car c'est un doublon de https://github.com/FreshRSS/FreshRSS/issues/824 et là conversation peut continuer là-bas.
