### ISSUE TITLE
Problème de connexion aux flux

### ISSUE THREAD

**Issue by ToEvenStay** [FreshRSS/FreshRSS#884]
Bonjour ;
Depuis quelque jour , quand je veaux ajouter des flux , sa fonctionne au début puis apres il se met en rouge . J'avais donc fait hier soir une nouvelle base de donnée et en éffacant les fichiers pour tout remettre comme il faut et faire une propre installation , mais même en fesant cela j'ai toujours cette erreur mais avec tout les flux que j'ai ajouter . Je vous montre une capture d'écran . 
Si vous pouviez m'aider merci d'avance . Bonne journée .
![capture5](https://cloud.githubusercontent.com/assets/13045598/8349499/ca91c85c-1b1d-11e5-9453-bd1fb7f14094.PNG)

**Comment by ToEvenStay** [comment]
Personne ne peut m'aider ?

**Comment by Alkarex** [comment]
Bonjour @ToEvenStay ,
Cela ressemble à un problème de connexion depuis votre serveur, plutôt qu'un problème de FreshRSS.

Quel type de serveur est-ce ?

Pourriez-vous essayer les tests suivants : 

Si la ligne de commande est disponible, essayer

``` sh
curl -v https://alexandre.alapetite.fr/tag/socialRSS
```

Dans tous les cas, faire deux tests PHP, et y accéder depuis votre navigateur :

1) Créer `readfile.php` avec ce contenu :

``` php
<?php
header('Content-Type: application/xml; charset=UTF-8');
readfile('https://alexandre.alapetite.fr/tag/socialRSS');
```

2) Créer `curl.php` avec ce contenu :

``` php
<?php
header('Content-Type: application/xml; charset=UTF-8');

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, 'https://alexandre.alapetite.fr/tag/socialRSS');
curl_setopt($ch, CURLOPT_HEADER, 0);

//curl_setopt($ch, CURLOPT_USERAGENT, $_SERVER['HTTP_USER_AGENT']);
curl_setopt($ch, CURLOPT_USERAGENT, 'FreshRSS/1.1.2-dev (Linux; http://freshrss.org) SimplePie/1.4-dev-FreshRSS');

curl_exec($ch);
curl_close($ch);
```

**Comment by ToEvenStay** [comment]
Bonsoir c'est un serveur vps qui tourne avec Plesk sous Debian 7
1.La ligne de commande à fonctionner 
2.Voici le lien avec readfile.php : http://flux.toevenstay.com/readfile.php
3.Voici le lien avec curl.php : http://flux.toevenstay.com/curl.php

Ce qui est étrange c'est que en important mon ancienne base de donnée les anciens fonctionnaient mais pas les nouveaux meme sur l'ancien serveur mutu et ici sur le vps en refesant une nouvelle bd sa ne fonctionne pas non plus . Merci d'avance bonne soirée .

**Comment by Alkarex** [comment]
Bonsoir,
Pourriez-vous essayer de cliquer sur le bouton "Vérifier la validité du flux" pour un ou deux flux ?

![monde](https://cloud.githubusercontent.com/assets/1008324/8415480/519202ca-1e9f-11e5-8a24-b72c03598262.png)

Est-ce que vous avez des messages dans les logs de FreshRSS ? (Menu en haut à droite)

**Comment by ToEvenStay** [comment]
Non aucun message dans les logs 
Pour korben : http://validator.w3.org/feed/check.cgi?url=http://korben.info/feed
Overclocking Made in France : http://validator.w3.org/feed/check.cgi?url=http://www.overclockingmadeinfrance.com/feed/

**Comment by Alkarex** [comment]
Pourriez-vous regarder le système de diagnostic disponible dans le menu en haut à droite, "Vérification de l’installation" ?

**Comment by ToEvenStay** [comment]
Tout est ok : 
![capture7](https://cloud.githubusercontent.com/assets/13045598/8416453/2b760b48-1ea6-11e5-8500-a17a9f9c7c5f.PNG)

**Comment by Alkarex** [comment]
Cela pourrait être un problème de droits. Est-ce que vous pourriez exécuter cela depuis le répertoire de FreshRSS ?

``` sh
ls -lh ./data/cache/
```

Est-ce que vous avez fait une mise à jour par cron ?

Est-ce qu'une mise à jour manuelle fonctionne ? (depuis l'interface Web)

**Comment by ToEvenStay** [comment]
La commande à fonctionner .
Non pas de mise à jour par cron .

**Comment by Alkarex** [comment]
Pourriez-vous montrer le début du résultat que la commande a donné ? Je suis en particulier intéressé par les droits et les tailles des fichiers.

**Comment by ToEvenStay** [comment]
Voici le résultat : 
"total 2.3M
-rw-r--r-- 1 toevenstay psacln 208K Jun 24 18:15 0529865ff58c7ea55982e918ebff4d9d.spc
-rw-r--r-- 1 toevenstay psacln  73K Jun 24 18:39 1634f5a3eee01aee7a73e6eafde1ed23.spc
-rw-r--r-- 1 toevenstay psacln  33K Jun 24 18:25 306a45c5de024bacca31cde910d4419d.spc
-rw-r--r-- 1 toevenstay psacln  42K Jun 24 18:28 32f5cb47d5b0e6b71ff7ed48eb90f450.spc
-rw-r--r-- 1 toevenstay psacln  42K Jun 24 18:29 3b1dc942e1ebbeaa0c1622c1d6367b39.spc
-rw-r--r-- 1 toevenstay psacln 175K Jun 24 18:38 4681e4d6f558dcc5ab636b0c21e4f884.spc
-rw-r--r-- 1 toevenstay psacln  79K Jun 24 18:29 49e90f91de6651bc3d25af25747053d8.spc
-rw-r--r-- 1 toevenstay psacln  32K Jun 24 18:42 543ff582fa02b9ef9391bdec540d67ba.spc
-rw-r--r-- 1 toevenstay psacln 277K Jun 24 18:22 58a8a20c6f55b7d8dbb153be76e6e38b.spc
-rw-r--r-- 1 toevenstay psacln  87K Jun 24 18:38 5f169049d57950c5a17bd33bce58867c.spc
-rw-r--r-- 1 toevenstay psacln 297K Jun 24 18:26 6f28a0f29d4455870d49c9112fbcedd9.spc
-rw-r--r-- 1 toevenstay psacln  78K Jun 24 18:44 73a32827499c7172bf2c5e8aa82aa785.spc
-rw-r--r-- 1 toevenstay psacln  43K Jun 24 18:16 7c5340b52323c5678831d6d6e5baeff8.spc
-rw-r--r-- 1 toevenstay psacln 108K Jun 24 18:37 835023be3741740f4e31813bf23119ab.spc
-rw-r--r-- 1 toevenstay psacln  62K Jun 24 18:16 83fc9e4397d7b09017a15bf56b1c1239.spc
-rw-r--r-- 1 toevenstay psacln  62K Jun 24 18:27 9b5c267df7b781e691f830332e4996f9.spc
-rw-r--r-- 1 toevenstay psacln    0 Jun 24 18:49 a0aa7bdbaaa8f1ec48d8611b409fc57a.spc
-rw-r--r-- 1 toevenstay psacln  40K Jun 24 18:23 a1cfd9b1e012946247044b8d544e484d.spc
-rw-r--r-- 1 toevenstay psacln  34K Jun 24 18:20 a22d8e113cf195478281815f5bb790b9.spc
-rw-r--r-- 1 toevenstay psacln  78K Jun 24 18:28 b1c67113d76bd554113b723364939565.spc
-rw-r--r-- 1 toevenstay psacln  17K Jun 24 18:30 b20e08859e19a817df5d0b569934c8d9.spc
-rw-r--r-- 1 toevenstay psacln  76K Jun 24 18:30 c6667f79619733416fe507023b838416.spc
-rw-r--r-- 1 toevenstay psacln  91K Jun 24 18:23 eb378aeee2ea09e204ff7f1e6656a4bc.spc
-rw-r--r-- 1 toevenstay psacln 256K Jun 24 18:22 f289871dc884830d62a17e838949f223.spc
-rw-r--r-- 1 toevenstay psacln    0 Jun 29 15:41 f35147b88c3b5689cab06dd2c2d52f1b.spc
-rw-r--r-- 1 root       root    309 Jun 24 18:06 index.html"

**Comment by Alkarex** [comment]
Donc le propriétaire des fichiers est `toevenstay` et le groupe `psacln`. Je ne suis pas familier de Plesk, mais si votre serveur Web n'est pas lancé avec l'utilisateur `toevenstay`, il ne sera pas possible d'écrire dans ces fichiers comme nécessaire.

Pourriez-vous essayer la commande suivante depuis le répertoire de FreshRSS, et réessayer un rafraichissement ?

``` sh
chmod a+rw -R ./data/
```

**Comment by ToEvenStay** [comment]
Même avec cette commande cela n'a pas fonctionné .

**Comment by Alkarex** [comment]
C'est tout de même curieux que vous n'ayez rien dans les logs FreshRSS et/ou PHP (serveur Web). C'est presque obligé que ce soit le cas.

Vous pouvez voir la liste des fichiers logs de FreshRSS avec la commande

``` sh
ls -lh ./data/users/*/log*
```

Quand vous dites que vous avez fait une nouvelle base de données, pourriez-vous expliquer plus précisément votre opération ? Utilisez-vous MySQL ou SQLite ? Dans le cas de MySQL, il se pourrait qu'il y ait un problème de droits (par exemple si l'utilisateur n'a pas les droits `ALTER` pour modifier les tables). Vous pourriez faire un essai avec SQLite si ce n'est pas déjà ce que vous utilisez.

Si cela ne suffit toujours pas, je n'ai pas trop d'autres idées, mais je veux bien essayer de regarder le serveur si vous me faites un accès temporaire (FTP et/ou SSH).

**Comment by ToEvenStay** [comment]
Le fichier log.txt est vide rien dedans .
J'utilise mysql et les droits sont bien appliqués . 
Je vais plutôt vous donnez l’accès si vous pouviez me dire comment vous les donner .
Merci d'avance .

**Comment by Alkarex** [comment]
@ToEvenStay Vous pouvez m'envoyer un courriel (voir adresse en haut de http://alexandre.alapetite.fr/cv/ ) avec l'adresse Web de votre FreshRSS et le compte utilisateur FreshRSS que vous voulez tester, ainsi qu'un accès SSH (ça suffit avec les droits pour lire/écrire les fichiers du répertoire FreshRSS) et/ou FTP. Je ne pense rien casser, mais juste par soucis de sécurité, pensez à sauvegarder vos données avant :-)

**Comment by ToEvenStay** [comment]
Je viens de vous envoyé un mail merci d'avance vous pouvez y aller rien est important sur le serveur .

**Comment by Alkarex** [comment]
Cela devrait marcher maintenant. C'était dû à https://github.com/FreshRSS/FreshRSS/issues/880 et j'ai appliqué manuellement le patch https://github.com/FreshRSS/FreshRSS/pull/881
J'ai aussi nettoyé la base de données en conséquence.
En gros, tous les flux avaient un mot de passe, à cause du fait que le mot de passe pour vous connecter à flux.toevenstay.com était enregistré dans votre navigateur (qui doit être un de ceux qui ne respectent plus _force autocomplete off_), qui du coup avait pré-rempli le champ mot de passe pour chaque flux...

**Comment by ToEvenStay** [comment]
Un grand merci donc ce n'etait pas un problème serveur mais plutôt du navigateur ?Cela pourrait se reproduire ? Merci beaucoup

**Comment by Alkarex** [comment]
En quelque sorte un problème de navigateur, oui. Le patch que j'ai appliqué (qui sera inclus dans la prochaine bêta) empêche cela. Dans tous les cas, l'utilisateur doit faire attention (pas seulement dans FreshRSS) que le navigateur ne remplisse pas automatiquement un champ de mot de passe tout seul avant de soumettre le formulaire, surtout depuis que Chrome et Firefox ne respectent plus le `<form autocomplete="off">`

**Comment by ToEvenStay** [comment]
Et bien un grand merci pour votre aide et je tiens à vous dire que FreshRss est excellent ne l'abandonner pas . Bonne nuit .

**Comment by Alkarex** [comment]
Pas de quoi, et plein de bonnes choses à venir pour FreshRSS :-)
