### ISSUE TITLE
Support PHP 7

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#889]
This is a meta issue to track changes and bugs related to the upcoming PHP 7.

The major expectation is to be about twice as fast. Many fatal errors are now Exceptions, and many deprecated features are removed.
The first beta is ~~expected in a few days~~ [there](http://php.net/archive/2015.php#id2015-07-10-4) (July), and the final version before the end of the year (2015).

https://wiki.php.net/todo/php70#timetable
http://php7.zend.com

**Comment by Alkarex** [comment]
PHP 7 beta 1 released :-) http://php.net/archive/2015.php#id2015-07-10-4

**Comment by Alkarex** [comment]
First quick test of FreshRSS with PHP 7 beta 1, using SQLite, and all good so far :-)

**Comment by marienfressinaud** [comment]
With better performance? :)

**Comment by Alkarex** [comment]
I have not compared the performances yet, but will soon do so :-)

**Comment by Alkarex** [comment]
Here is a quick performance test :-)
- The setup with PHP7 is about **70% faster** than the setup with PHP5 (all included);
- Given that a good part of the request time is SSL + HTTP (with logging) + database request (with logging), the speed improvement of PHP7 is even higher.

Methodology:
- Using PHP7 beta1 from http://php7.zend.com/repo.php
- Using php.ini from https://wiki.php.net/phpng
- Using a script in localhost, to minimise the effect of the network, and the MySQL database request will be cached
- Having set the number of articles to display per page to 115 in FreshRSS (this is the number of favourites I currently have) to have a page that is a bit heavy.
- Repeat the request 50 times
- Testing PHP5, then PHP7, then PHP5 again, then PHP7 again

Results (rounded to the nearest half second):
- About 17.5 seconds (all included) for PHP5;
- About 10 seconds (all included) for PHP7;

Details:

``` bash
time for i in {1..50}; do curl -u alex:xxx 'https://rss.example.net/i/?get=s&'$i > /dev/null; done

#PHP5
real    0m17.479s
user    0m3.256s
sys     0m1.076s

#PHP7
real    0m10.158s
user    0m3.276s
sys     0m1.080s

#PHP5
real    0m17.466s
user    0m3.280s
sys     0m1.076s

#PHP7
real    0m10.286s
user    0m3.268s
sys     0m1.104s
```

Example of cURL output:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  740k    0  740k    0     0  4564k      0 --:--:-- --:--:-- --:--:-- 4596k
```

**Comment by Alkarex** [comment]
Well, not much more to say: it just works (also with all errors/warnings enabled) :-) https://github.com/FreshRSS/FreshRSS/issues/903

**Comment by Alkarex** [comment]
`split()` https://github.com/FreshRSS/FreshRSS/blob/1d25121d84a683fee237ae05c789e5548ecccab4/lib/lib_phpQuery.php#L4209 is not compatible PHP7, but I have not checked whether it is actually used.
