### ISSUE TITLE
hex2bin() not available with PHP < 5.4

### ISSUE THREAD

**Issue by marienfressinaud** [FreshRSS/FreshRSS#894]
`hex2bin` function is used twice in `app/Models/EntryDAO.php` but is not available before PHP 5.4. Since we should be compatible at least with PHP 5.3, we have to find a solution.

See http://stackoverflow.com/a/17963343

Log example:

```
PHP Fatal error:  Call to undefined function hex2bin() in /var/www/html/app/Models/EntryDAO.php on line 80, referer: http://localhost/p/i/
```

**Comment by Alkarex** [comment]
`hex2bin()` is used to support SQLite, and we support SQLite 3.7.4+, which implies PHP 5.3.6+ http://php.net/ChangeLog-5.php#5.3.6
So to keep the existing compatibility, we need to support MySQL with PHP 5.2.1+ and SQLite with PHP 5.3.6+

**Comment by marienfressinaud** [comment]
Yes but PHP 5.3.6 < 5.4 and `hex2bin` is only >= 5.4 so it doesn't change anything ;).

**Comment by Alkarex** [comment]
Yes, it was just for the record

**Comment by Alkarex** [comment]
Patch available https://github.com/FreshRSS/FreshRSS/issues/895

**Comment by Alkarex** [comment]
Just for reference, link to another commit for PHP 5.2 compatibility https://github.com/Alkarex/FreshRSS/commit/214a5cc9a4c2b821961bc21f22b4b08e34b5be68

**Comment by Alkarex** [comment]
Done.
