### ISSUE TITLE
List of SimplePie pull requests to consider

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#896]
https://github.com/simplepie/simplepie/pulls?q=is%3Aopen+is%3Apr

**Comment by Alkarex** [comment]
- [ ] Sanitize: superfluous entities https://github.com/simplepie/simplepie/pull/388

Requires PHP 5.3.6+ due to http://php.net/domdocument.savehtml
http://w3techs.com/technologies/details/pl-php/all/all
http://w3techs.com/technologies/details/pl-php/5/all
http://w3techs.com/technologies/details/pl-php/5.3/all

**Comment by Alkarex** [comment]
- [ ] Memory Consumption https://github.com/simplepie/simplepie/pull/287

http://stackoverflow.com/questions/14337179/why-am-i-getting-memory-leaks-in-simplepie-when-using-item-get-permalink/

**Comment by Alkarex** [comment]
See https://github.com/FreshRSS/FreshRSS/pull/898

**Comment by math-GH** [comment]
Is it still worth to keep this ticket open?
