### ISSUE TITLE
Give indications to change the password

### ISSUE THREAD

**Issue by marienfressinaud** [FreshRSS/FreshRSS#901]
Sometimes, people send emails to ask how to change the password because they forgot the initial one. We should write a small how-to.

**Comment by marienfressinaud** [comment]
See some comments in https://github.com/FreshRSS/FreshRSS/issues/676

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/issues/960

**Comment by aledeg** [comment]
#1765
