### ISSUE TITLE
User Registration

### ISSUE THREAD

**Issue by h0ek** [FreshRSS/FreshRSS#905]
Hello,

FreshRSS script is great! Good job.
Is there an option allow user to register their own accounts?
I would like to allow users to create account and use my self hosted FreshRSS script.
Any plugin or special config line to add?
Could you add this feature?

Thanks,
Hoek

**Comment by marienfressinaud** [comment]
Thanks :)

A ticket is already opened for this feature (https://github.com/FreshRSS/FreshRSS/issues/679) but in French so I keep this one opened for English-speaking persons.

Registration is planned but we (i.e. the FreshRSS team) don't have a lot of time to work on it.

**Comment by h0ek** [comment]
Great news!
Awesome!
I can't wait.
Thank you.
Have you got some BTC address for donations?

**Comment by marienfressinaud** [comment]
And here is the PR to fix this ticket https://github.com/FreshRSS/FreshRSS/pull/914 :).

**Comment by marienfressinaud** [comment]
BTW, we don't have any BTC address. I had a Flattr account thought but I don't use it anymore. In fact, I don't know what to do with this money :p

**Comment by Alkarex** [comment]
@marienfressinaud Do you know if there is an English version of https://soutenir.framasoft.org ?

**Comment by marienfressinaud** [comment]
I don't think so but I can ask ;)

**Comment by marienfressinaud** [comment]
It is now in the /dev branch and will be in the next beta version in few days / weeks :).

**Comment by Alkarex** [comment]
Little bug https://github.com/FreshRSS/FreshRSS/issues/923
