### ISSUE TITLE
Add links to the documentation from the different readme sections

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#908]
See https://github.com/FreshRSS/FreshRSS/issues/890#issuecomment-122309779

**Comment by aledeg** [comment]
Could you add more info here?
I was trying to figure out what this means to work on it. But I failed.

**Comment by Alkarex** [comment]
Yes: the idea was to add a few some links from the different sections of https://github.com/FreshRSS/FreshRSS/blob/master/README.md to the corresponding sections of our online documentation https://freshrss.github.io/FreshRSS/

**Comment by Frenzie** [comment]
You mean something like not duplicating https://freshrss.github.io/FreshRSS/en/users/01_Installation.html but linking straight to https://github.com/FreshRSS/FreshRSS/blob/master/README.md#requirements ?

**Comment by aledeg** [comment]
I am still confuse. The idea is to do what @Frenzie said or the other way around ?

**Comment by Alkarex** [comment]
I would suggest keeping the readme more or less as it is for now, and just add some links for additional information. We can then see if any information would better be removed from the readme.

**Comment by aledeg** [comment]
So if I understand correctly, you mean adding links in the README file. Those links referencing sections in the documentation.
