### ISSUE TITLE
Perform VACUUM on SQLite db

### ISSUE THREAD

**Issue by marienfressinaud** [FreshRSS/FreshRSS#918]
We have an "Optimize DB" button but there is nothing behind when using SQLite (https://github.com/FreshRSS/FreshRSS/blob/beta/app/Models/EntryDAOSQLite.php#L183). An idea would be to implement a VACUUM action BUT WAIT, we have to discuss about it first!

I don't have time to write a proper explanation about benefits and drawbacks of VACUUM so I let two interesting links:
- An article from Jim Nelson about SQLite in Geary software: https://blogs.gnome.org/jnelson/2015/01/06/sqlite-vacuum-and-auto_vacuum/
- And an article about Liferea's startup performance: http://jeff.ecchi.ca/blog/2011/12/24/investigating-lifereas-startup-performance/

Both are interesting and should be read before trying to implement a solution.

**Comment by Alkarex** [comment]
See https://github.com/FreshRSS/FreshRSS/pull/1663
