### ISSUE TITLE
Call for testing /dev before 1.1.2-beta

### ISSUE THREAD

**Issue by marienfressinaud** [FreshRSS/FreshRSS#919]
Hello everybody,

with some delay, it's time to release a new version. 1.1.2-beta is very interesting since it introduces some nice features wanted for a long time:
- **Support of PubSubHubbub**
- Support proxy configuration
- Allow anonymous users to create new accounts
- Some improvements during the installation

What do we need before this new release:
- [ ] A clear documentation about PubSubHubbub
- [x] To write an appropriate script to update from 1.1.1 (note dev script must be updated to create PubSubHubbub folders in `./data` too)
- [x] To write an article for http://freshrss.org/blog.html, focused on PubSubHubbub support because I think it is a very great feature that we should highlight
- [x] Could be great to translate last non-translated strings in German and Czech

I would like to release this version on **30th July**.

Thanks to all contributors for testing! :)

Ping @Alkarex @aledeg @Alwaysin @Jucgshu

**Comment by aledeg** [comment]
30th June? but what year?
I guess it's a typo :)

**Comment by marienfressinaud** [comment]
Yep, typo :p It's fixed now ;)

**Comment by Alkarex** [comment]
Link to [milestone 1.1.2](https://github.com/FreshRSS/FreshRSS/milestones/1.1.2)
Already testing; so far so good :-)

**Comment by marienfressinaud** [comment]
I updated the dev automatic update script (see https://github.com/FreshRSS/update.freshrss.org/commit/83371f236ea947be467cee30eee437cc1b263c2e) and wrote the script for version 1.1.2-beta (see https://github.com/FreshRSS/update.freshrss.org/commit/6b633e4a2ad9f5c351a439d5c57b37693f720a1e). It's not on the server yet, I have to test first ;).

**Comment by Alkarex** [comment]
By the way @marienfressinaud , do you have any idea on when you would like to release the next /master (1.2?). I was initially planning to have [1.1.2-beta](https://github.com/FreshRSS/FreshRSS/milestones/1.1.2) for some big new features, [1.1.3-beta](https://github.com/FreshRSS/FreshRSS/milestones/1.1.3-beta) for consolidation, and then 1.2 (master). But if 1.1.2 gets well tested and proves to be stable enough, the schedule could be different.

**Comment by marienfressinaud** [comment]
We can see this during the dev of 1.1.3-beta: if we consider 1.1.2 is well-tested, we can plan to release 1.2 and 1.3-beta in one month ;).

**Comment by marienfressinaud** [comment]
Let's go for the release: I started a page of documentation about PubSubHubbub and I will write article later.

Edit: and I tried the update script which is working :)

**Comment by marienfressinaud** [comment]
We should keep this ticket opened until the article.

**Comment by Alkarex** [comment]
Can we close this issue? I suggest we release 1.1.3-beta soon, which [already contains a few important bug fixes and nice improvements](https://github.com/FreshRSS/FreshRSS/blob/dev/CHANGELOG.md). We can move the [remaining tickets](https://github.com/FreshRSS/FreshRSS/milestones/1.1.3-beta) to e.g. 1.1.4-beta (or 1.3.0-beta if there is a 1.2-master release in between).

**Comment by aledeg** [comment]
I am good with that!

**Comment by marienfressinaud** [comment]
I agree with that: I planned the next version for tomorrow but we may delay the release to the end of the  week. I'm not sure if I will have a lot of time for that but I can try.
