### ISSUE TITLE
White page when syntax problem in config.php

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#920]
Now that is becomes more likely for users to edit their `data/config.php` then it would be nice to show an error message when there is a syntax error.
Currently, a syntax error in `config.php` will result in an error 500 with a white page.

A central piece of code is https://github.com/FreshRSS/FreshRSS/blob/12081f7ba2089c8046dacac23ebe44ea843d7ef1/lib/Minz/Configuration.php#L118

**Comment by Alkarex** [comment]
Maybe to consider for 1.1.2-beta but not crucial https://github.com/FreshRSS/FreshRSS/issues/919

**Comment by marienfressinaud** [comment]
It's trickier than what I expected. Two possibilities
- Catching syntax error during including. Problem: we can't http://stackoverflow.com/a/1900224 (or with some tricks I want to avoid)
- Check PHP syntax of the file. Problem: `php_check_syntax` [has been removed](http://php.net/manual/en/function.php-check-syntax.php) and the only way is to execute the command line (which is also a trick I want to avoid)

I don't know if you have any other idea how to handle these errors.

**Comment by Alkarex** [comment]
I think we should stick to something very basic indeed. Maybe removing a few `@`, removing a few try/catch if they are problematic (or re-throw the exception), and test if `include` returns false to at least `die()` properly with a message that there is a problem in `config.php` and/or `config.default.php`.

**Comment by Alkarex** [comment]
Slightly related to https://github.com/FreshRSS/FreshRSS/issues/923 https://github.com/FreshRSS/FreshRSS/pull/926

**Comment by marienfressinaud** [comment]
Problem is if you have a syntax error in `config.php`, there is nothing to do (not even `die()`) because I guess `exit()` or a similar function is called at this moment. You can just register a function thanks to `register_shutdown_function` and I don't like this idea...

**Comment by Alkarex** [comment]
I think it would be a good enough to just let the default warning being displayed.

Here is a little test:
- index.php

``` php
<?php
echo 'Hello', "\n";
$who = include('./who.php');
print_r($who);
echo 'Bye.';
```
- who.php

``` php
<?php
return array (
        'who' => 'world,        //Wrong syntax
);
```

If the syntax error is not corrected, here is the output:

``` sh
alex@srv3$ php index.php
Hello
PHP Parse error:  syntax error, unexpected ''world,' (T_ENCAPSED_AND_WHITESPACE) in /home/alex/.../include/who.php on line 3
```

If the syntax error is corrected, here is the output:

``` sh
alex@srv3$ php index.php
Hello
Array
(
    [who] => world
)
Bye.
```

**Comment by marienfressinaud** [comment]
Fixed by https://github.com/FreshRSS/FreshRSS/pull/929
