### ISSUE TITLE
What settings to change view as demo

### ISSUE THREAD

**Issue by Wanabo** [FreshRSS/FreshRSS#921]
I like my FressRSS install to be public viewable like the demo on http://demo.freshrss.org/i/
But all configuration options must only be accessible for an admin with login.

What settings do I need to change or what files to mod??

**Comment by Alkarex** [comment]
Hello @Wanabo,
1. Ensure that you have an authentification method such as Web Form (and not HTTP or None);
2. Click the checkbox _Allow anonymous reading_

![f](https://cloud.githubusercontent.com/assets/1008324/8891045/495216c6-3318-11e5-8d70-fa8731ba0118.png)

**Comment by Wanabo** [comment]
Hi Alkarex, that does the trick! Thanks!
