### ISSUE TITLE
Adding some functionality

### ISSUE THREAD

**Issue by rolero** [FreshRSS/FreshRSS#922]
I am looking into FreshRSS and trying to add some functionality. I want to be able to use the product for selecting rss items to publish to: 1. website and 2. newsletter.  My French is everything besides good and I am not familiar with MINZ :( The idea is to add two new RSS items booleans: "is_website"  and "is_newsletter". Based on this selection I filter out the one I need and integrate them with 1. a website, 2. Mailchimp. Mailchimp as the option to do RSS driven campaigns.

The concept is that several employee from on company can select RSS items they like and chose if should be on the website and offered in the company newsletter. (Yes a approval process also needs to be added...next step :) ) When the boolean is set the items are accessible through FreshRSS (using APi, RSS, XML...) 

I am willing to support this project 400 EUR if this functionality can be added and the offer to participate in the business that is will be opened through this functionality. If interested please contact me. I will use the Freelancer platform to get the job done and do the payment.

I already did the db changes in the table fresrss_admin_entry. Also added the booleans and two other columns (isapproved, newsletterid) into the Model. Currently working on the controller but here thing sget a little bit complicated for me.

**Comment by Alkarex** [comment]
Hello @rolero ,
To be sure that I understand right: you would like to use FreshRSS to read articles coming from different RSS feeds, and republish a selection of them in two different categories as an RSS feed?
To be relevant for the FreshRSS project, a functionality would need to appeal to a larger audience.
As a first suggestion, it seems that your need could be generalised by adding a possibility to tag articles in FreshRSS, and then display the tags like virtual categories.
Thank you for your offer of sponsoring some of the development. We will see with @marienfressinaud and come back to you.

**Comment by Alkarex** [comment]
The technical discussion continues in https://github.com/FreshRSS/FreshRSS/issues/928 and @marienfressinaud will provide more details.

**Comment by Alkarex** [comment]
@rolero Sorry for the delay, due to holidays. We would like to respond positively to your offer. Our approach would be to take a slightly more general angle https://github.com/FreshRSS/FreshRSS/issues/928 We do not have a time estimate right now, but please let us know whether you are still interested, and whether you have any calendar constraint.

**Comment by rolero** [comment]
No problem. Same here although it is more work then holiday :)  I read the approach and also already shared my view. I added it as a comment at #928. Calendar constraint is in about 5 a 6 months.

**Comment by Frenzie** [comment]
This seems to have been implemented in https://github.com/FreshRSS/FreshRSS/pull/2027

Pinging @Alkarex

**Comment by Alkarex** [comment]
Indeed @Frenzie :-)

**Comment by Alkarex** [comment]
@rolero If you are still around, I believe the feature you asked was added at last, in October 2018
