### ISSUE TITLE
Minz: Bug loading config.default for array values

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#923]
If arrays such as `limits` exist in `config.php`, their values always come from `config.php` even when they do not exist, which create an _undefined index_ exception.

For instance, I do not have the new `max_registrations` value (https://github.com/FreshRSS/FreshRSS/issues/905) in my `config.php` (but it is in my `config.default.php`), which generates a 
- Notice: Undefined index: max_registrations in ./FreshRSS/app/views/user/manage.phtml on line 12
- Notice: Undefined index: max_registrations in ./FreshRSS/lib/lib_rss.php on line 305

Reference https://github.com/FreshRSS/FreshRSS/blob/dev/lib/Minz/Configuration.php
https://github.com/FreshRSS/FreshRSS/issues/919

**Comment by Alkarex** [comment]
I suggest loading `config.default.php` and replacing its values with `config.php` by calling http://php.net/array-replace-recursive

**Comment by marienfressinaud** [comment]
Yes sure! I don't even know why I didn't do this in first place ><...

**Comment by marienfressinaud** [comment]
Fixed by https://github.com/FreshRSS/FreshRSS/pull/926
