### ISSUE TITLE
Minz: Session cookie bug (nginx?)

### ISSUE THREAD

**Issue by ToEvenStay** [FreshRSS/FreshRSS#924]
Bonjour ,
Depuis ma nouvelle installation de FreshRSS sur mon serveur je ne peut plus me connecter depuis un smartphone ou une tablette Android . 
Lorsque je me connecte il charge la page mais revient automatiquement sur la page pour se connecte sans message d'erreur ni rien d'autre . Le mot de passe est bon j'ai vérifié .
J'ai donc été ensuite dans les paramètres change le mode d'authentification pour ne rien mettre bien évidement cela à fonctionner . 
Aussi je n'ai aucun problème pour me connecter depuis d'autre pc plusieurs navigateurs essayer .
Par contre sur mobile j'ai essayer touts les navigateurs du Play Store mais cela n'a rien changé .
Voici les terminaux sur lequel j'ai essayé : Galaxy S6 - Galaxy Note4 -Galaxy Note10.1 tous de Samsung mais je ne pense pas que cela vient de la marque tous aussi sont sur Android Lollipop ce qui n'avait posé aucun problème avant .
Alors sur mon serveur je suis sur Debian 8 avec ispconfig3 et Nginx .
Je suis sur la dernière version bêta de FreshRSS comme avant .
Je ne sais pas vous donnez quoi d'autre comme info dans les logs il a ceci à chaque fois que je veux me connecter depuis mon mobile : 
Password mismatch for user=ToEvenStay, nonce=, c=$2a$04$ccKM/O9bitvzuN/hAYP3COYtJLaME53SFxCGBjtZNPiaq21z7Y2J6
Merci d'avance de votre aide .

**Comment by Alkarex** [comment]
Je vais essayer de trouver un moment pour regarder. `nonce` ne devrait pas être vide. Pas d'autres messages dans les logs PHP ou de FreshRSS ? Pas de bloqueur JavaScript sur la tablette ?

**Comment by ToEvenStay** [comment]
Non pas d'autre message et pas de bloqueur sur la tablette . Merci d'avance .

**Comment by Alkarex** [comment]
Ok. Pour avoir plus de logs, on peut se mettre en mode `development` dans `data/config.php`.

**Comment by ToEvenStay** [comment]
J'ai ceci en plus maintenant dans les logs : 
Invalid credential parameters: user=ToEvenStay challenge=$2a$04$7kdYvasmxxBSvxHR1ydT4espUvHYE7EvIeox72b6TKdZXUNt7jYWe nonce=

**Comment by ToEvenStay** [comment]
Que puis-je faire d'autre ?

**Comment by Alkarex** [comment]
Je viens de tester avec Firefox Mobile 40.0 et avec le navigateur _Internet_ par défaut sur Samsung Galaxy S4 (Android 5.0.1), sans problème.
- Pourriez-vous essayer avec la version /dev de FreshRSS ? Sinon, quelle version exacte de FreshRSS avez-vous ?
- Avez-vous essayé avec Firefox Mobile ?
- Avez-vous des erreurs JavaScript ?
- Si cela n'aide toujours pas, pourriez-vous peut-être m'[envoyer en privé](http://alexandre.alapetite.fr/cv/) l'adresse où je pourrais tester le problème ?

**Comment by ToEvenStay** [comment]
.J'ai la version 1.1.1-beta 
.J'ai essayé touts les navigateurs mobile sur chaque mobile différent .
.Je ne pense avoir d'erreur JavaScript
.Je vous ai envoyé mon accès au flux .
Merci d'avance .

**Comment by Alkarex** [comment]
Pour info, /dev testé à l'instant sur une Samsung Galaxy Tab S 10.5 (Android 5.0.2) avec le navigateur par défaut, sans problème.

**Comment by ToEvenStay** [comment]
Le problème reste le meme meme en dev

**Comment by Alkarex** [comment]
Il y a apparemment un problème de cookies avec votre configuration : les clients mobiles n'envoient pas de cookie de session. J'ai mis quelques messages de débogage supplémentaire sur votre instance, mais il faut que je fasse une pause maintenant. Je reprendrai plus tard.

**Comment by ToEvenStay** [comment]
D'accord merci

**Comment by ToEvenStay** [comment]
Bonsoir , je sais pas si les maj on réglé le problème ?

**Comment by Alkarex** [comment]
Voici un log des entêtes HTTP lors de la connexion sur votre système. Il semble y avoir deux lignes `Set-Cookie`, ~~ce qui pourrait être la source du problème. C'est peut-être spécifique à nginx~~:

```
GET /p/i/?c=javascript&a=nonce&user=ToEvenStay HTTP/1.1
Host: example.com
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
X-Requested-With: XMLHttpRequest
Referer: http://example.com/p/i/
Connection: keep-alive

HTTP/1.1 200 OK
Server: nginx/1.6.2
Date: Thu, 30 Jul 2015 20:23:50 GMT
Content-Type: application/json; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: FreshRSS=octj8rrqulcrg52m0vvnmhejv6; path=/flux/p/i
Set-Cookie: FreshRSS_login=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0
Etag: "b2007f7bf153d138d8d25c7810eedc5c"
Last-Modified: Thu, 30 Jul 2015 20:23:50 GMT
Expires: 0
Cache-Control: private, no-cache, no-store, must-revalidate
Pragma: no-cache
```

**Comment by ToEvenStay** [comment]
Je peux donc faire quoi pour le résoudre ?

**Comment by Alkarex** [comment]
J'ai dit une bêtise : j'ai bien deux lignes sous Apache aussi dans ce cas là.
Ben pour résoudre, il faudrait commencer par récupérer les entêtes HTTP sur mobile. Il serait aussi bien de trouver quelqu'un d'autre avec le même problème, ou d'arriver à le reproduire sur nos machines. Ma meilleure piste actuellement me semble être un problème de configuration de cookies dans nginx.

**Comment by Alkarex** [comment]
Je suis en train de regarder un peu plus

**Comment by ToEvenStay** [comment]
Merci , en plus je pars en vacance samedi donc j'aimerais bien avoir mes flux en vacances :( voulez-vous le tuto que j'ai pris pour installé mon serveur ?

**Comment by Alkarex** [comment]
Trouvé, c'est un bug dans Minz

**Comment by ToEvenStay** [comment]
Ah bonne nouvelle alors . Merci .

**Comment by Alkarex** [comment]
Bon, ça marche chez vous là.
Mais j'ai fait pas mal de changements par ci, par là, aussi il serait bien d'installer la /dev actuelle, et de changer la fonction suivante dans `lib/Minz/Session.php`. Je vais préparer un patch aussi.

``` php
    public static function keepCookie($l) {
            // Get the script_name (e.g. /p/i/index.php) and keep only the path.
            $cookie_dir = dirname(empty($_SERVER['REQUEST_URI']) ? '/' : dirname($_SERVER['REQUEST_URI']));
            session_set_cookie_params($l, $cookie_dir, '', false, false);
    }
```

C'était le `path` de `Set-Cookie` qui n'était pas bon (`path=/flux/p/i` au lieu de `path=/p/i`) à cause de l'utilisation de `SCRIPT_NAME` au lieu de `REQUEST_URI`

**Comment by ToEvenStay** [comment]
Un grand merci de votre aide

**Comment by Alkarex** [comment]
Un peu tard pour intégrer ce correctif dans la bêta 1.1.2, mais pour référence https://github.com/FreshRSS/FreshRSS/issues/919

**Comment by ToEvenStay** [comment]
Voilà j'ai bien ajouté le code à la fin du fichier mais maintenant j'ai un erreur 500 : 
ERROR 500 - Internal Server Error!

The following error occurred:

The requested URL caused an internal server error.

If you get this message repeatedly please contact the webmaster.

**Comment by ToEvenStay** [comment]
Problème réglé merci

**Comment by Alkarex** [comment]
@ToEvenStay Je viens de faire un patch. Ça serait bien si vous pouviez tester cette version
https://github.com/FreshRSS/FreshRSS/pull/936

``` php
    public static function keepCookie($l) {
        // Get the script_name (e.g. /p/i/index.php) and keep only the path.
        $cookie_dir = empty($_SERVER['REQUEST_URI']) ? '/' : $_SERVER['REQUEST_URI'];
        if (substr($cookie_dir, -1) !== '/') {
            $cookie_dir = dirname($cookie_dir) . '/';
        }
        session_set_cookie_params($l, $cookie_dir, '', false, false);
    }
```

**Comment by ToEvenStay** [comment]
Pas de problème toujours en /dev ?

**Comment by Alkarex** [comment]
Oui :-)

**Comment by ToEvenStay** [comment]
Il me met que vous n'avez rien modifié depuis 9heures : 
![capture](https://cloud.githubusercontent.com/assets/13045598/8997398/31ed7824-3721-11e5-8e65-8b4fd5c71e17.PNG)

**Comment by Alkarex** [comment]
Le patch n'est pas encore dans /dev : il est en phase de test / relecture.
Seule la fonction ci-dessus a changé. Vous pouvez soit changer la fonction à la main comme tout à l'heure, soit utiliser le branche du patch #936

**Comment by ToEvenStay** [comment]
Oui cela fonctionne bien vous pouvez tester aussi de chez vous avec mon flux si vous voulez .

**Comment by ToEvenStay** [comment]
Bonjour , beaucoup d'erreur dans les logs . Pouvez y jeter un œil pour voir si c'est normal ? Merci .

**Comment by Alkarex** [comment]
Quelles erreurs plus précisément ?
Pour PubSubHubbub, voir https://freshrss.org/freshrss-supports-pubsubhubbub.html

**Comment by Alkarex** [comment]
Le patch est dans /dev N'hésitez pas à confirmer que cela marche (ou pas...)
