### ISSUE TITLE
Add custom tags to articles, and show custom tags as virtual categories

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#928]
See https://github.com/FreshRSS/FreshRSS/issues/922#issuecomment-124880593

**Comment by Alkarex** [comment]
I believe the main needs will be:
1. add new tag to existing article (entry);
2. retrieve the list of articles matching a tag (virtual category);
   - Requires an index on the tag
3. show all tags for an article;
   - Requires an index on the article or article reference

There are several approaches for the SQL model, with different advantages/drawbacks.

Here is the variant 1, in which tags are referenced by an integer. It offers the easy possibility of changing the name of the tag, and using a long tag name should not affect performances. Articles (entries) can have several tags.

``` SQL
CREATE TABLE IF NOT EXISTS `tag` (
    `id` SMALLINT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY (`name`)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci
ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS `tags` (
    `id_tag` SMALLINT NOT NULL,
    `id_entry` BIGINT NOT NULL,
    FOREIGN KEY (`id_tag`) REFERENCES `tag`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (`id_entry`) REFERENCES `entry`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
    INDEX (`id_entry`),
    UNIQUE KEY (`id_tag`,`id_entry`)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci
ENGINE = INNODB;
```

**Comment by Alkarex** [comment]
We also need to decide what to do with the tags provided by the RSS feed:
1. Keep them in the `entry` table as they are now;
2. Merge them with the new tagging system, with a flag to distinguish custom tags;

**Comment by rolero** [comment]
I would keep the existing tags and add a flag for custom tags. The tags provided by the RSS feed item tells something about the content of the feed item while the "custom" tag set by the user, can also be used to initiate workflows. For example. RSS item is received with tag "x", User reads the articles and makes the conclusion it should be used on the website. Therefor the user adds the tag "candidate for website". After one week the user selects all the articles with the tag "candidate for website and re-publish them. In the future and extension could be added to select RSS items by tag and push them into an automated workflow. You could integrate FreshRSS for example with ifttt.com or Mailchimp to generate newsletters.

**Comment by rolero** [comment]
Another solution would not to use the tag system but the existing sharing solution for it. Maybe a general approach where you can add new share options as an extension. Instead of sharing to Facebook or Twitter you share to an extension. The extension takes care of everything while FreshRSS just provides an general way of pushing the data forward.

**Comment by Alkarex** [comment]
http://tagging.pui.ch/post/37027745720/tags-database-schemas
http://tagging.pui.ch/post/37027746608/tagsystems-performance-tests

**Comment by Alkarex** [comment]
Implemented in https://github.com/FreshRSS/FreshRSS/pull/2027
Tests welcome
