### ISSUE TITLE
[Mobile] "Marquer tous les articles lus" ne marche pas sur navigateur par défaut Android 4.2

### ISSUE THREAD

**Issue by Draky50110** [FreshRSS/FreshRSS#932]
Salut

Parfois, sur mon androphone (Android 4.2.x), j'utilise le navigateur par défaut pour aller sur mon FreshRSS.
Je suis connecté.
Ne s'affichent que les non lus (car parm.comme cela).

Ca marche bien sauf si je clique sur "Marquer tous les articles lus" en bas de la page : ça recharche la page mais les articles sont toujours marqués comme non lus !

**Comment by Alkarex** [comment]
Je n'arrive pas à reproduire le problème. Ça serait bien d'avoir les logs HTTP et FreshRSS lors du clic pour marquer comme lu, ainsi que la requête suivante. Si vous utilisez MySQL, ça serait aussi bien d'activer les logs MySQL pour avoir les quelques requêtes effectuées à ce moment là.

**Comment by Draky50110** [comment]
Mmm en fait ça ne le fait qu'avec le navigateur de base donc...

**Comment by Alkarex** [comment]
Testé avec le navigateur _Internet_ par défaut d'un Samsung Galaxy S4 (Android 5.0.1) sans problème. Je serais tout de même intéressé par les logs si vous en avez la possibilité.

**Comment by Draky50110** [comment]
Et comment je vois ça comment sous mobile ?

**Comment by Alkarex** [comment]
Ça m'intéressait déjà d'avoir les logs côté serveur (HTTP, FreshRSS, et eventuellement MySQL) sans avoir à regarder côté mobile (juste les lignes correspondant au clic problématique)

**Comment by Draky50110** [comment]
M'a trompé de bouton.
Bon... côté logs internes de FRSS, pas de signalement, c'est vide.
Par contre, je serai bien en peine de donner les logs HTTP ou MySQL car je ne sais pas comment les obtenir...

**Comment by Alkarex** [comment]
Ok, on pourra rouvrir si le besoin se représente. Les logs HTTP, se sont les logs du serveur Web (genre Apache), typiquement quelque part dans `/var/log/`
