### ISSUE TITLE
Themes 1.1.2-beta

### ISSUE THREAD

**Issue by Liandriz** [FreshRSS/FreshRSS#934]
Salut, un petit retour sur la dernière maj, que je viens d'appliquer.
Apparement, plus aucune possibilité de changer de thème, ceux-ci ne s'affichant pas dans la partie options/affichage.
De plus, ajouter le backup des thèmes 3rd party avant une màj pourrait le faire, vive le backup récupérer mon thème modifié :0

**Comment by Liandriz** [comment]
Ok, restorer le thème 3rd party fait réapparaitre la liste des thèmes, MB.

**Comment by marienfressinaud** [comment]
Tiens bizarre, je n'ai pas ce soucis de mon côté :s. Les thèmes sont bien présents dans `./p/themes/` avec des fichiers `metadata.json` ? Tu n'as pas vu d'erreur apparaître lors de la mise à jour ? Je pourrais avoir un screenshot pour voir à quoi ressemble la page ?

Pour le thème custom... ça oui par contre il va falloir qu'on fasse quelque chose dans le script pour éviter ce problème !

**Comment by marienfressinaud** [comment]
Ah tant mieux alors, mais ce bug était étrange, je vais essayer de le reproduire de mon côté.

**Comment by Liandriz** [comment]
Au final, juste le fait que le thème soit supprimé qui ai provoqué ça (sinon, toujours aussi fluide avec presque 400k articles :+1: ).
