### ISSUE TITLE
Keep custom themes during update

### ISSUE THREAD

**Issue by marienfressinaud** [FreshRSS/FreshRSS#935]
For now, custom themes are deleted during update process.

See https://github.com/FreshRSS/FreshRSS/issues/934
Related to https://github.com/FreshRSS/FreshRSS/issues/907

**Comment by Liandriz** [comment]
Je reconfirme pour la 1.1.3 :0

**Comment by marienfressinaud** [comment]
@Liandriz > pour la prochaine mise à jour, renommes le dossier de ton thème pour le faire commencer par `xTheme-` et normalement il ne sera pas supprimé ;).

**Comment by marienfressinaud** [comment]
To keep a custom theme during an update, it should start by `xTheme-`. For instance: `xTheme-my_super_cool_custom_theme`

**Comment by Liandriz** [comment]
Renommé, en attente de la mise à jour pour tester du coup, merci :0
