### ISSUE TITLE
SEO (robots, meta)

### ISSUE THREAD

**Issue by Wanabo** [FreshRSS/FreshRSS#938]
I think FreshRSS is build for personal use (Robots: noindex,nofollow), but I would like to use FreshRSS for the public.
To become a successful website with the use of FreshRSS SEO is a must!
Not only Robots: noindex,nofollow has to be changed (easy enough to do myself), but at least meta description and meta keywords are needed. Best dynamically generated from articles, categories, tags, titles etc.

I'm setting up a new website and love to use FreshRSS, but SEO is missing.
Will SEO ever be implemented?

Regards

**Comment by Alkarex** [comment]
Hello @Wanabo 
We do not currently have a plan to add SEO, put it may be doable depending on the amount of work.
Adding a control for the `robots` directive would not be a problem:

``` html
<meta name="robots" content="xxx" />
```

and adding a meta description for the feeds would also be easy:

``` html
<meta name="description" content="Description given by the feed" />
```

Would that be useful for you?
For other, more advanced, behaviours, I would rather see that in an extension.
BTW, I do not think any major search engine uses the meta keyword for anything.

**Comment by Wanabo** [comment]
[quote]BTW, I do not think any major search engine uses the meta keyword for anything.[/quote]
Personally I am not convinced that is the case. When there are no description or keywords set google is quite capable to generate their own description. Setting them yourself will certainly help to be found in google for specific articles, tags and the like.

I've changed in layout.phtml

meta name="robots" content="noindex,nofollow"

to

meta name="robots" content="index,follow"

All though in my opinion    meta name="robots" content="index,follow" can be removed all together. 

Do you mean for meta name="description" content="Description given by the feed" to have this in the xml? Now it is description>RSS feed of Your RSS feeds | FreshRSS</description
That would be nice!

I have a website with Rnews 1.01 (http://nieuwskop.nl and modded some own seo), but for my new website, http://nieuwskop.be I would like to try an other self hosted RSS software and see if that is more successful. I have setup two possible candidates. FreshRSS: http://www.nieuwskop.be/fr/p/i/ and Selfoss: http://www.nieuwskop.be/ 

With SEO would have my preference.

Regards.

**Comment by Alwaysin** [comment]
> BTW, I do not think any major search engine uses the meta keyword for anything.
> 
> > Personally I am not convinced that is the case. 

Alkarex is right, Google does not use it : https://www.youtube.com/watch?v=jK7IPbnmvVU and from latest news I heard, Bing even considers only spammers use this metatag.

My 2 cts.

**Comment by Wanabo** [comment]
Well any way I have chosen to continue using FreshRSS. So I hope SEO will come in the future. I see it is added as a milestone to 1.1.3-beta.

I have almost completed a Dutch translation and planning to submit it to Github. Or can I submit it elsewhere?

**Comment by Wanabo** [comment]
Well any way I have chosen to continue using FreshRSS. So I hope SEO will come in the future. I see it is added as a milestone to 1.1.3-beta.

I have almost completed a Dutch translation and planning to submit it to Github. Or can I submit it elsewhere?

Edit: I've completed the Dutch translation and can be found here: https://github.com/Wanabo/FreshRSS-Dutch-translation

**Comment by Alkarex** [comment]
Hello @Wanabo,
Please test https://github.com/FreshRSS/FreshRSS/pull/1011 if you can.
There is a new option `allow_robots` which you can add to your `data/config.php`.

**Comment by Alkarex** [comment]
Related to https://github.com/FreshRSS/FreshRSS/issues/985 and https://github.com/FreshRSS/FreshRSS/issues/986

**Comment by Wanabo** [comment]
Hi Alkarex.

Downloaded DEV 1.1.4 and manually updated the download with https://github.com/FreshRSS/FreshRSS/pull/1011/files?diff=unified
- Switch allow_robots true/false is working correctly.
- The description only seems to work correctly when selecting a category and a feed name. When selecting an article the description is not updated to the title and some of the content of the article, it keeps the feed name description.
- A category shows "Description: Actualité | ", but should read "Description: Actualité | Some description entered in subscription management for the category"
- The start page shows "Description: Your RSS feeds | ", but should read "Description: Title of site | Some description entered in System configuration below Instance name for description"

Thanks for your effort! I think it is a great start for better seo. Hope you agree with my comments.
If extracting keywords is not to much trouble I would welcome that very much.

Regards Wanabo.

**Comment by Wanabo** [comment]
You posted:
`<title>Planet Libre · FreshRSS</title>
<link id="prefetch" rel="next prefetch" href=".?a=normal&amp;get=f_105&amp;next=1469100755988349&amp;ajax=1" />
<link rel="alternate" type="application/rss+xml" title="Planet Libre | FreshRSS" href=".?a=rss&amp;get=f_105" />
<meta name="referrer" content="origin" />
<meta name="description" content="Planet Libre | Communauté du Libre partage" />`

My output: (note the empty part after | which should be generated by FreshRSS_Context::$description)
`<title>(49) Column · NieuwsKoppen</title>
        <link id="prefetch" rel="next prefetch" href=".?a=normal&amp;get=c_22&amp;next=1470930523391479&amp;ajax=1" />
        <link rel="alternate" type="application/rss+xml" title="Column | NieuwsKoppen" href=".?a=rss&amp;get=c_22" />
        <meta name="description" content="Column | " />`

Tried another theme but has the same problems.

**Comment by Alkarex** [comment]
Try on a feed that has a description

**Comment by Wanabo** [comment]
Update: found the problem. My descriptions are empty. They were not ex- imported with opml.

**Comment by Alkarex** [comment]
It looks like this issue is done, and the remaining discussion is in https://github.com/FreshRSS/FreshRSS/issues/1105
