### ISSUE TITLE
1.1.2-beta : actualisation lente en cas d'erreur PubSubHubbub

### ISSUE THREAD

**Issue by Humfred** [FreshRSS/FreshRSS#939]
Bonjour,
Depuis la dernière mise à jour, l'actualisation est très lente : plus de cinq minutes pour une cinquantaine de flux.
Il y a des erreurs liées à pubsubhubbub dans les logs:

```
[Mon, 03 Aug 2015 11:53:07 +0200] [warning] --- Error while PubSubHubbub subscribing to http://feeds.feedburner.com/Axolot
[Mon, 03 Aug 2015 11:53:12 +0200] [warning] --- Error while PubSubHubbub subscribing to http://liquidlove.fr/feed/
[Mon, 03 Aug 2015 11:53:18 +0200] [warning] --- Error while PubSubHubbub subscribing to https://sciencetonnante.wordpress.com/feed/
[Mon, 03 Aug 2015 11:53:20 +0200] [warning] --- A feed could not be found at `http://www.cafe-sciences.org/feed/`; the status code is `500` and content-type is `text/html; charset=utf-8` [http://www.cafe-sciences.org/feed/]
[Mon, 03 Aug 2015 11:53:26 +0200] [warning] --- Error while PubSubHubbub subscribing to http://lesoufflenumerique.com/feed/
[Mon, 03 Aug 2015 11:53:49 +0200] [warning] --- Error while PubSubHubbub subscribing to https://www.blogger.com/feeds/1879199009612029553/posts/default
[Mon, 03 Aug 2015 11:54:10 +0200] [warning] --- Error while PubSubHubbub subscribing to http://feeds.feedburner.com/lafeuillerss
[Mon, 03 Aug 2015 11:54:32 +0200] [warning] --- Error while PubSubHubbub subscribing to https://www.blogger.com/feeds/849439270710857663/posts/default
[Mon, 03 Aug 2015 11:54:55 +0200] [warning] --- Error while PubSubHubbub subscribing to http://feeds.feedburner.com/DrGoulu
[Mon, 03 Aug 2015 11:54:59 +0200] [warning] --- Error while PubSubHubbub subscribing to http://figoblog.org/feed/
[Mon, 03 Aug 2015 11:55:02 +0200] [warning] --- Error while PubSubHubbub subscribing to https://scienceetconscience.wordpress.com/feed/
[Mon, 03 Aug 2015 11:55:06 +0200] [warning] --- A feed could not be found at `http://sciences.blogs.liberation.fr/home/rss.xml`; the status code is `403` and content-type is `text/html; charset=UTF-8` [http://sciences.blogs.liberation.fr/home/rss.xml]
[Mon, 03 Aug 2015 11:55:29 +0200] [warning] --- Error while PubSubHubbub subscribing to http://feeds.feedburner.com/chefnini
[Mon, 03 Aug 2015 11:55:50 +0200] [warning] --- Error while PubSubHubbub subscribing to http://feeds.feedburner.com/PodcastScience
[Mon, 03 Aug 2015 11:57:51 +0200] [warning] --- Error while PubSubHubbub subscribing to http://feedpress.me/frandroid
[Mon, 03 Aug 2015 11:58:14 +0200] [warning] --- Error while PubSubHubbub subscribing to http://feeds.feedburner.com/hominides
[Mon, 03 Aug 2015 11:58:15 +0200] [warning] --- A feed could not be found at `http://webinet.cafe-sciences.org/feed/`; the status code is `500` and content-type is `text/html; charset=utf-8` [http://webinet.cafe-sciences.org/feed/]
[Mon, 03 Aug 2015 11:58:36 +0200] [warning] --- Error while PubSubHubbub subscribing to https://www.blogger.com/feeds/24292134/posts/default
[Mon, 03 Aug 2015 11:59:01 +0200] [warning] --- Error while PubSubHubbub subscribing to http://feeds.feedburner.com/LesDcouvertesArchologiques
[Mon, 03 Aug 2015 11:59:22 +0200] [warning] --- Error while PubSubHubbub subscribing to http://feeds.feedburner.com/typepad/OEkF
[Mon, 03 Aug 2015 11:59:43 +0200] [warning] --- Error while PubSubHubbub subscribing to http://feeds.feedburner.com/NiouTaik
```

**Comment by Alkarex** [comment]
Qu'est-ce que ca donne en désactivant PubSubHubbub ? (Dans `config.php`)

**Comment by Humfred** [comment]
En désactivant PubSubHubbub, la vitesse d'actualisation est redevenu normale.

**Comment by Alkarex** [comment]
Est-ce que vous avez des logs dans `data/users/_/log_pshb.txt` ?

**Comment by Alkarex** [comment]
J'ai fait un patch pour votre cas, qui évite d'essayer trop souvent (une fois par jour maximum) de s'abonner au PubSubHubbub d'un flux en cas d'erreur
https://github.com/FreshRSS/FreshRSS/issues/940
https://github.com/Alkarex/FreshRSS/tree/PshbErrorManagement
Ça serait gentil si vous pouviez essayer ce patch en réactivant PubSubHubbub : les erreurs devraient toujours être là, mais au maximum une fois par jour.
C'est indépendant du fait qu'il faut trouver pourquoi PubSubHubbub ne marche pas chez vous : probablement à cause d'un mauvais `base_url` dans `config.php`.

**Comment by Humfred** [comment]
Je n'ai pas de fichier log_pshb.txt dans data/users/xxx/
Je testerai votre patch cet après midi. 
Pour info dans mon config.php  j'ai: 'base_url' => 'https://monsite.net:80/FRSS/p'

**Comment by Alkarex** [comment]
Pour le fichier log, c'est le répertoire spécial avec un tiret bas : `./data/users/_/log_pshb.txt`.
Pourriez vous tester votre site HTTPS avec https://www.ssllabs.com/ssltest/analyze.html ?

**Comment by Alkarex** [comment]
Ça me semble curieux le HTTPS avec port 80. Est-ce bien voulu ?

**Comment by Humfred** [comment]
Bon j'ai fait un test en virant la redirection vers HTTPS de mon .htaccess et en modifiant base_url en le pointant vers http://monsite.net/FRSS/p. Dans ce cas je n'ai plus de problème de vitesse,  par contre j'ai toujours des erreurs dans le fichier log du type "Error while PubSubHubbub subscribing to http://lesoufflenumerique.com/feed/".
En fait, je pense que ma config ou ma base mysql doit deconner : lors de l'actualisation des flux Freshrss m'indique que j'ai 68 flux alors que j'en ai 54.
Je vais donc réinstaller Freshrss avec une base mysql neuve.

**Comment by Alkarex** [comment]
Je ferme le ticket, mais n'hésitez pas à écrire s'il y a du nouveau de votre côté.
