### ISSUE TITLE
Erreur d'ajout

### ISSUE THREAD

**Issue by Draky50110** [FreshRSS/FreshRSS#941]
Salut

Pas possible d'ajouter https://n.survol.fr/feed/
Et l'erreur dans les log = cURL error 35: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure [https://n.survol.fr/feed]

**Comment by Alkarex** [comment]
Le certificat du site n'est pas valide https://www.ssllabs.com/ssltest/analyze.html?d=spirale.io _Certificate name mismatch_
Mais cette erreur semble curieusement uniquement présente lors de la première connexion. Je n'ai pas beaucoup plus cherché, mais ce n'est pas côté FreshRSS (essayer à la main dans différents navigateurs).
Il est aussi possible depuis FreshRSS 1.1.2-beta de désactiver certaines vérifications de certificat, dans `config.php` (voir modèle dans `config.default.php` https://github.com/Alkarex/FreshRSS/blob/26ed0e5c9571dfdaac22f147bda793cc25c9e661/data/config.default.php#L84 )

**Comment by Draky50110** [comment]
Ok, merci pour l'info.
C'est toujours sympa de dire aux gens "Venez che zmoi en HTTPS" sans vrai certificat...
Du coup, j'ai décommenté ça : 
CURLOPT_SSL_VERIFYHOST => 0,
CURLOPT_SSL_VERIFYPEER => false,

Je vais voir si ça passe mieux.

**Comment by Draky50110** [comment]
Bon, toujours la même erreur, pas sur spirale.io mais sur n.survol.fr (j'ai changé le flux foireux après donc l'email a pas montré le bon lien :p)
cf premier message

**Comment by Alkarex** [comment]
Voir https://www.ssllabs.com/ssltest/analyze.html?d=n.survol.fr
Selon la version d'OpenSSL de votre serveur (< 1.0), cela risque de ne pas marcher.
Essayer un cURL depuis la ligne de commande de votre serveur.

**Comment by Draky50110** [comment]
Voici ce que ça donne : 
draky@ssh:~$ curl https://n.survol.fr/feed/
curl: (35) error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handsh
ake failure
draky@ssh:~$ openssl version
OpenSSL 0.9.8o 01 Jun 2010

Du coup, vais tenter de rajouter une option à curl, en faisant comme indiqué ici : 
http://stackoverflow.com/a/28649569

Ce qui donne un config.php avec ça dedans : 

``` php
'curl_options' => array(
        # Options to disable SSL/TLS certificate check (e.g. for self-signed HTTPS)
        CURLOPT_SSL_VERIFYHOST => 0,
        CURLOPT_SSL_VERIFYPEER => false,
        CURLOPT_SSL_CIPHER_LIST => 'TLSv1',

        # Options to use a proxy for retrieving feeds.
        //CURLOPT_PROXYTYPE => CURLPROXY_HTTP,
        //CURLOPT_PROXY => '127.0.0.1',
        //CURLOPT_PROXYPORT => 8080,
        //CURLOPT_PROXYAUTH => CURLAUTH_BASIC,
        //CURLOPT_PROXYUSERPWD => 'user:password',
    ),
```

**Comment by Alkarex** [comment]
Voilà, comme soupçonné, c'est par ce que ce site n'est pas compatible avec OpenSSL < 1.0 (_Protocol or cipher suite mismatch_), ce qui est le cas de votre serveur.

**Comment by Draky50110** [comment]
Ok.
Je vais demander à mon hébergeur et en plus le support de openSSL <1.x fini cette année.
Merci :)

**Comment by Alkarex** [comment]
Juste pour être sûr d'avoir été compris : c'est votre serveur qui doit mettre à jour OpenSSL pour une version > 1.0 pour supporter ce site.

**Comment by Draky50110** [comment]
Oui, mon serveur est en 0.9.8 :/
