### ISSUE TITLE
Stubborn feed 

### ISSUE THREAD

**Issue by subzero79** [FreshRSS/FreshRSS#942]
I have at the moment a very stubborn feed that doesn't update with freshrss. Logs in freshrss indicate 

"Feed already being actualized: http***" 

Regarding the log, is a feed with a private api key i cannot post the feed here. 

I've appended to the source feed URL the "#force_feed" trigger, after that i run actualize and the feed gets updated. But after that i check with manage the feed URL and force_feed is gone from the URL.

Freshrss version is 1.1.2-beta
PHP version is 5.6.9

Questions:

Is there a way of getting more debug log, besides development in config.php? This is to know why freshrss thinks my feed is already actualized

Is normal than the #force_feed disappears from the URL after update (actualize)?

**Comment by Alkarex** [comment]
Ok, I believe there is a bug in some situations for the force feed feature. I will try to have a look in the coming days.
Regarding the feed already being actualized, it is something that happens if the previous attempt has crashed less than ~1 hour before (if I remember well). You can manually delete the lock file in /var/tmp/

**Comment by subzero79** [comment]
Thanks for lock tip, in my case it was at /tmp folder. After removing the lock file, and pressing actualize the feed updated. I'll keep watching the cron curl for hourly updates.

This an openelec 5.95 beta install (static read only rootfs) with lamp stack addon, just in case someone else finds this useful.

**Comment by Alkarex** [comment]
The issue seems to be solved, isn't it?

**Comment by subzero79** [comment]
Yes is solved. Thanks for the clarification.
