### ISSUE TITLE
Favicon : URL du site plutôt que URL du feed

### ISSUE THREAD

**Issue by Draky50110** [FreshRSS/FreshRSS#943]
Salut

Je suppose que le favicon est récupéré depuis l'URL du feed, non ?
Est-ce possible de le récupérer par l'URL du site (la case au-dessus dans la gestion d'un flux).

Parce que pour certains sites, je passe par https://github.com/sebsauvage/rss-bridge qui délivre un flux complet et non tronqué.
Hors FreshRSS m'affiche donc le favicon du site qui héberge l'instance de RSS-Bridge...

Merci :)

Ou une case / ligne en plus pour entrer à la main...

**Comment by aledeg** [comment]
Je viens de commencer à regarder et c'est déjà ce qui est fait. Je pense que le problème vient de la manière dont le favicon est recherché sur le site.

J'ai fait le test avec http://cyrille-borne.com/veille/ et j'ai le même problème.

**Comment by aledeg** [comment]
J'ai un peu avancé sur le problème pour le cas spécifique de la veille de Cyrille Borne.
Le serveur renvoie une réponse vide. J'ai fait le test avec les valeurs que j'intercepte lors de l'appel.
Voici le code que j'ai utilisé :

``` php
$favicon_url = 'http://cyrille-borne.com/themes/defaut/img/favicon.png';

$c = curl_init($favicon_url);
curl_setopt($c, CURLOPT_HEADER, true);
curl_setopt($c, CURLOPT_RETURNTRANSFER, true);
curl_setopt($c, CURLOPT_BINARYTRANSFER, true);
curl_setopt($c, CURLOPT_VERBOSE, true);
$img_raw = curl_exec($c);

var_dump($img_raw);
```

Et voila la réponse que j'obtiens

```
*   Trying 109.234.160.19...
* Connected to cyrille-borne.com (109.234.160.19) port 80 (#0)
> GET /themes/defaut/img/favicon.png HTTP/1.1
Host: cyrille-borne.com
Accept: */*

* Empty reply from server
* Connection #0 to host cyrille-borne.com left intact
bool(false)

```

Par contre, quand je fais le test avec cURL en ligne de commande, ça fonctionne correctement.

**Comment by aledeg** [comment]
J'ai remarqué aussi que la recherche du favicon remonte jusqu'à l'URL de base. Ce qui n'est pas toujours approprié (cf: la veille de Cyrille Borne qui va chercher le favicon du site et non pas de la veille).

Dans un autre registre, il est également possible de supprimer l'option **CURLOPT_BINARYTRANSFER** car elle n'a plus d'utilité depuis PHP5.1.3 quand on utilise l'option **CURLOPT_RETURNTRANSFER**.

**Comment by Alkarex** [comment]
Curieux. Avez-vous essayé de varier les entêtes ? Par exemple `Accept`, `User-agent`, etc.?

**Comment by Alkarex** [comment]
Je viens d’essayer avec un RSS Bridge, et cela semble fonctionner correctement (il faut peut-être faire un rafraîchissement de la favicon dans le navigateur). N'hésitez pas à rouvrir avec un exemple de flux qui ne marche pas comme il faut.

![favicon](https://cloud.githubusercontent.com/assets/1008324/17648330/a0d43410-6210-11e6-902b-3049ca5dbad6.png)
