### ISSUE TITLE
Support <media:*> tags

### ISSUE THREAD

**Issue by JD557** [FreshRSS/FreshRSS#944]
It would be nice to have support for the [RSS media specification](http://www.rssboard.org/media-rss), which allows feeds to have multimedia content such videos without having them directly embedded on the content HTML.

I'm not sure how easy it would be to add the `media:content` fields (I'm not sure if using an `<embed>` tag works for all cases), but supporting descriptions and thumbnails should be easy enough, and would make youtube feeds much better.

**Comment by Alkarex** [comment]
Could you please provide an example of feed, which is currently not working (optimally)?

**Comment by JD557** [comment]
[Example](https://www.youtube.com/feeds/videos.xml?channel_id=UCy1Ms_5qBTawC-k7PVjHXKQ)

Note that most relevant info (thumbnail, video and description) are actually in media tags and not in the normal tags.

**Comment by Alkarex** [comment]
Implemented - at last! - in https://github.com/FreshRSS/FreshRSS/pull/1920
