### ISSUE TITLE
Is there a way to undo "mark all as read"?

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/FreshRSS#945]
I know it is a bit off-topic, but does one know how to undo a "mark as read"? I've messed with a mobile client and lost my unread articles :(

I'm using SQlite, is there such a thing as revert from some queries ahead or something like that?

Please feel free to close if necessary :)

Thanks !

**Comment by Alkarex** [comment]
Hey @Alwaysin,
There is no built-in way to do that in FreshRSS. However, doing it via an SQL query is not so difficult, if you just want to mark as unread all articles between two given dates (or all articles of a given category/feed). Would that help?

**Comment by Alwaysin** [comment]
Thanks Alkarex for the reply! Unfortunately it wouldn't help as my unread articles were spread along a time-line of approximately 3 months but mixed with read articles : I just kept unread those I wanted to read later :(

**Comment by Alkarex** [comment]
Ok, then there is no way, except a backup...

> I just kept unread those I wanted to read later

For that, I believe putting a star (favourite) is better.

**Comment by Alwaysin** [comment]
Ok, that's what I thought :(

Thanks anyway, I wanted to be sure about it!

Indeed, I'll try to use stars or export those articles to Wallabag.
