### ISSUE TITLE
Mozilla Social API integration

### ISSUE THREAD

**Issue by tifredfr** [FreshRSS/FreshRSS#946]
Pourquoi ne pas proposer en plus du bookmark la possibilité d'utiliser le service de partage de Firefox. J'ai découvert ceci via Shaarli il y a quelques jours et c'est plutôt cool, ça allège surtout ma barre des signets.

Shaarli issue : https://github.com/shaarli/Shaarli/issues/101

**Comment by marienfressinaud** [comment]
Oh tu fais bien d'ouvrir un ticket ! J'avais demandé des infos à @wallabag l'autre jour et j'ai oublié d'ouvrir le ticket-qui-va-bien.

Plus d'infos ici : 
- https://github.com/wallabag/wallabag/commit/090957fe3e12ffe23d2f847f6007c72eb9ca072d
- https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Social_API/Guide/Bookmarks
- https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Social_API/Manifest

Autant dire que je pense que c'est une très bonne idée :)

**Comment by Frenzie** [comment]
This has been obsoleted and removed from Gecko 51.

**Comment by Alkarex** [comment]
Indeed :-( Thanks for the heads-up, @Frenzie
