### ISSUE TITLE
Suggestions + Dutch translation

### ISSUE THREAD

**Issue by Wanabo** [FreshRSS/FreshRSS#949]
Share link below an article is now a drop down menu. Please show share icons directly below the article (without drop down menu).

Suggested tags from articles are not matching any category names although they sometimes are close to category names. Suggestion to match tags first to categories and/then to similar articles. Are tags generated for all articles? If so then please match them for related articles.

Use generated tags from articles as meta keywords in header.

Currently using version 1.1.2-beta
I've completed a Dutch translation for version 1.0.0 and 1.1.2-beta beta and can be found here: https://github.com/Wanabo/FreshRSS-Dutch-translation

**Comment by Alkarex** [comment]
Hello @Wanabo,
Thanks for the translation; following the git workflow, I have transformed it in a pull request https://github.com/FreshRSS/FreshRSS/pull/950

The tags are provided by the original feeds (i.e., the original author of a given article), not generated by FreshRSS. See also this related discussion https://github.com/FreshRSS/FreshRSS/issues/928

See this other related discussion for meta keywords (SEO) https://github.com/FreshRSS/FreshRSS/issues/938

**Comment by Wanabo** [comment]
I'm making my fist steps on Github. Should I do anything regarding the pull request?

**Comment by Alkarex** [comment]
@Wanabo This time, I have prepared the pull request, so you do not have anything more to do. We will give it some time so that the other collaborators may have a chance to look at it, before one of us merge it in the development branch. Thanks again.

**Comment by marienfressinaud** [comment]
i.e. when I will have a decent Internet connection :)
