### ISSUE TITLE
Actualizing problem in user profile

### ISSUE THREAD

**Issue by mekin** [FreshRSS/FreshRSS#951]
When the main stream is actualized in an user profile (not admin), the actualizing pane seems but after finishing it, the page automatically logouts the user!

**Comment by Alkarex** [comment]
@mpesen How long does it take, more or less, before you are logged out?

**Comment by mekin** [comment]
It lasts up to yellow bar disappearing. Whenever yellow bar disappearing, you log out suddenly. One more thing. But this problem occurs at admin profile too (since a few days). It's very strange... Also main RSS feed also does not refresh itself during that time.

**Comment by aledeg** [comment]
@mekin I've checked with the latest version of FRSS. It seems to work properly. It might have been fixed during those past 5 years.
I close it and if the problem still occurs, feel free to reopen the current issue.
