### ISSUE TITLE
Feature Suggestion: Two-Factor Authenticaton For Login

### ISSUE THREAD

**Issue by mekin** [FreshRSS/FreshRSS#952]
There are some free 2FA/OTP application such as Google Authenticator and Microsoft Auhenticator. For example, you can easily implement Google Authenticator in WordPress admin login. I think, you can also add such a feature to FressRSS' login page.

**Comment by Alkarex** [comment]
If you can, you are welcome to send a patch @mpesen, but please without external dependency (no request to another domain).

**Comment by Draky50110** [comment]
There is no such need (access to external domain).
OTP password config gives you a "secret key" to enter in a compatible smartphone app (like Google Auth or other).
Then when app is configured with secret key, next time you log in your website, it asks you for a secret code, given by the smartphone app.
This secret code is 1 minute available.
That's all.
I don't know how to develop it of course but there are PHP library which are devoted to this I think.

@Alkarex you can look at this : https://github.com/PHPGangsta/GoogleAuthenticator/
It is for Google auth but I think it is compatible with other apps because OTP is a standard.

**Comment by Alkarex** [comment]
Looks doable :-)
If you can, do not hesitate to try to send a pull request, @Draky50110

**Comment by Draky50110** [comment]
I even don't know how to write an hello world in PHP ;)

**Comment by sbrl** [comment]
I'd probably recommend implementing either TOTP ([this library looks like it'll do the job at a quick look](https://packagist.org/packages/spomky-labs/otphp)) or U2F / FIDO2 (which I don't much development experience with, but they are the protocols behind hardware security keys and passwordless login etc.).

**Comment by Alkarex** [comment]
Regarding FIDO, I am considering adding a login option based on WebAuthn https://developer.mozilla.org/docs/Web/API/Web_Authentication_API

**Comment by sbrl** [comment]
@Alkarex: That would be awesome! That should work with my new [Solo](https://solokeys.com) that's just arrived :D

Happy test it - I use Firefox

**Comment by ArbiterGR** [comment]
Hello, any news about 2fa for login? This should be  top on the list, security-wize.

**Comment by Alkarex** [comment]
@ArbiterGR Nothing new yet, but contributions welcome

**Comment by Alkarex** [comment]
Feedback welcome for https://github.com/FreshRSS/FreshRSS/pull/5351

**Comment by sunjam** [comment]
Hi, is two factor actually available?  I see no mention of it in documentation.

**Comment by Alkarex** [comment]
@sunjam We support OpenID Connect and proxy delegation, so you can use one of those solutions to enable two-factor. For instance: Authentik, Authelia, Keycloak.

* https://freshrss.github.io/FreshRSS/en/admins/09_AccessControl.html
* https://freshrss.github.io/FreshRSS/en/admins/16_OpenID-Connect-Authentik.html

**Comment by brevilo** [comment]
@Alkarex 
> Feedback welcome for [#5351](https://github.com/FreshRSS/FreshRSS/pull/5351)

IMHO, OpenID Connect is orthogonal to the original feature request asking for 2FA/OTP. Sure, an external auth provider *can* also offer 2FA but that means you first need to have one in the first place. Not everyone can or wants to. Don't get me wrong, OpenID Connect is certainly *also* a very useful addition to FreshRSS but I argue it doesn't fulfill the 2FA/OTP needs for those who want to secure their simple user/pass-based local login.

Any chance we could reopen this issue with the original goal of supporting TOTP for local logins?

To kickstart things I recommend [otphp](https://github.com/Spomky-Labs/otphp) instead which seems to be the [canonical](https://packagist.org/packages/spomky-labs/otphp?query=totp) PHP library for TOTP nowadays and is very actively maintained. Join that with [bacon-qr-code](https://packagist.org/packages/bacon/bacon-qr-code) (or [endroid/qr-code](https://packagist.org/packages/endroid/qr-code)) and you're good to go.

Thanks

**Comment by Alkarex** [comment]
Let's open a new ticket @brevilo 
I think I would like to add some hooks to implement such a thing as an extension, as I am not so keen on adding some large libraries to the core.

**Comment by brevilo** [comment]
> Let's open a new ticket [@brevilo](https://github.com/brevilo) I think I would like to add some hooks to implement such a thing as an extension, as I am not so keen on adding some large libraries to the core.

Done: #8931
