### ISSUE TITLE
Add description of feed in Div

### ISSUE THREAD

**Issue by Kirill** [FreshRSS/FreshRSS#953]
For now in div section of each flux exist class "flux  [not]read" and id with flux_id. Feed id exist in deeper section as link to open only feed. For customizing such this
https://userstyles.org/styles/90012/inoreader-colorful-feeds
https://userstyles.org/styles/105540/inoreader-colorful-feeds-2014
https://userstyles.org/styles/93412/inoreader-colorized-feed-posts
needs add feed id in this div section.
![2015-08-21 09_20_55](https://cloud.githubusercontent.com/assets/302940/9403290/000c82de-47e6-11e5-992c-7b957870e15e.png)

**Comment by Alkarex** [comment]
We could add a `data-feed="f_123"` in the `<div>` for instance. Would that help?

**Comment by Kirill** [comment]
Yes. Such as in Inoreader.

**Comment by Alkarex** [comment]
You can give a try to https://github.com/FreshRSS/FreshRSS/pull/954
Feedback welcome.

**Comment by Kirill** [comment]
Yes. It's work
![2015-08-21 12_40_50](https://cloud.githubusercontent.com/assets/302940/9406563/e864560e-4801-11e5-9a81-f2b4b9dbf13e.png)
