### ISSUE TITLE
AnonymousReferer should anonymize all links

### ISSUE THREAD

**Issue by oupala** [FreshRSS/FreshRSS#955]
Marien started to write an extension called AnonymousReferer.

This extension aims at deleting the http referrer when the FreshRSS user click on a post to see it on the original website. The http referrer is deleted by the use of an anonymous redirection service known as **anonym.to**, deleting the referrer is as simple as adding the `http://anonym.to/?` prefix to each link. The extension is available for [download](http://marienfressinaud.fr/data/files/upload/xExtension-AnonymousReferer.zip).

Unfortunately, the extension is not as complete as the original extension that came from KrissFeed. The extension only deletes the referrer for the link to the original post while ignoring all links inside the post.

The extension from KrissFeed has the following options :
- leave the configuration field empty to not modify the behaviour (leave links as is)
- fill-in the field with `http://anonym.to/?` to use the **anonym.to** service (what is _partially_ done by the actual extension)
- fill-in the url of another service which API si similar (in case **anonym.to** would be blacklisted by your ISP)
- fill-in `noreferrer` to use the html5 property

The KrissFeed extension does only change links (but **all** links) and not other media files which are then downloaded directly (images and others).

**Comment by Alkarex** [comment]
See https://www.w3.org/TR/referrer-policy/
https://developer.mozilla.org/en/docs/Web/Security/CSP/CSP_policy_directives#referrer

``` http
​Content-Security-Policy: default-src 'self'; referrer origin; ...
```

http://caniuse.com/#search=referrer

**Comment by JD557** [comment]
I don't see any extension for this. Does it exists?

Anyway, can't we just add `<meta name="referrer" content="no-referrer" />` to all pages (or add an option to insert this)?

https://w3c.github.io/webappsec-referrer-policy/#referrer-policy-delivery-meta

**Comment by Alkarex** [comment]
@JD557 See my comment just above yours. You should be able to use a CSP rule in your Web server configuration

**Comment by Alkarex** [comment]
P.S. @JD557 No, no extension exists

**Comment by Alkarex** [comment]
I will make a patch directly in FreshRSS

**Comment by Alkarex** [comment]
The appropriate directive would be `same-origin` https://www.w3.org/TR/referrer-policy/#referrer-policy-same-origin but:
- In Mozilla Firefox 48:
  - `<meta name="referrer" content="same-origin" />` also blocks the same-origin Referer for Ajax calls, which breaks FreshRSS security check https://github.com/FreshRSS/FreshRSS/issues/565 ; https://bugzilla.mozilla.org/show_bug.cgi?id=1276836
  - `Referrer-Policy: same-origin` is not recognised;
- In Chrome 53:
  - `Referrer-Policy: same-origin` is not recognised; https://bugs.chromium.org/p/chromium/issues/detail?id=627968

Is seems like only `<meta name="referrer" content="origin" />` is stable so far.

**Comment by Alkarex** [comment]
@JD557 I have made a patch https://github.com/FreshRSS/FreshRSS/pull/1198 included in the /dev branch. Feedback welcome.

same-origin referrer is currently needed https://github.com/FreshRSS/FreshRSS/issues/565 but could be avoided after implementing security tokens https://github.com/FreshRSS/FreshRSS/issues/570

**Comment by Alkarex** [comment]
After testing for a few days, I do not like the behaviour for `<meta name="referrer" content="origin" />` and will probably change to `Referrer-Policy: same-origin`, but which will only work for upcoming browsers.

**Comment by Alkarex** [comment]
I am implementing the security tokens https://github.com/FreshRSS/FreshRSS/issues/570 to properly solve this issue

**Comment by Alkarex** [comment]
`<meta name="referrer" content="never" />` is now implemented natively in FreshRSS: https://github.com/FreshRSS/FreshRSS/issues/1210
@oupala @JD557 Tests welcome of the /dev branch

**Comment by oupala** [comment]
I've just updated my FreshRSS instance to version 1.6.2 and I'll be welcome to test that.

How can I test that as any link is opened in a new tab and this new tab does not have the network debug tab opened?

**Comment by Alkarex** [comment]
@oupala The most robust way is to have an RSS and some content on a server you control, and check the received headers. Otherwise with an extension such as LiveHTTPHeaders https://addons.mozilla.org/firefox/addon/live-http-headers/ or another network inspection tool.

**Comment by oupala** [comment]
I tried LiveHTTPHeaders and it works well. I can see that the `Referrer` header is never sent for none of the http requests (even for request to get FreshRSS resources).

I can't see the `never` value in the [Referrer policy](https://w3c.github.io/webappsec-referrer-policy/#referrer-policy-no-referrer). I can see the [same-origin policy](https://w3c.github.io/webappsec-referrer-policy/#referrer-policy-same-origin) which would maybe be more appropriate.

What do you think?

**Comment by Alkarex** [comment]
See comments https://github.com/FreshRSS/FreshRSS/issues/955#issuecomment-239631870 and higher up for the explanations. It may be revised with new browser updates.

**Comment by oupala** [comment]
Ok, I've read the thread.

So for now, it's working.
