### ISSUE TITLE
Documentation API Google Reader (nginx)

### ISSUE THREAD

**Issue by nervx** [FreshRSS/FreshRSS#957]
Bonjour à tous,

Premierement bravo pour votre travail, Je fais ce post car je rencontre quelques difficultés à faire marcher FreshRSS avec differentes APP Android (News+ ou EasyRSS). J'ai fait quelques recherches et je me trouve bloquer.. je ne comprends pas trop qu'il faut faire :/..

Actuellement j'en suis à rentrer ca comme URL http://adresse_serveur/p/api/ puis je clique sur l'un des liens et je me retrouve avec un jolie "File not found. " . Pour info EasyRSS ou News+ me renvoi que mes identifiants sont invalides.

J'ai essayé differentes choses qui sont indiquées sur le forum etc.. mais sans succès. 

Si quelqu'un est motivé d'aider un pauvre homme qu bataille depuis plus de 6h devant son pc.. ^^

**Comment by Alkarex** [comment]
La documentation laisse à désirer, effectivement...
Suivre les étapes de https://github.com/FreshRSS/FreshRSS/issues/443#issuecomment-36666133
L'adresse à utiliser dans les clients est `http://adresse_serveur/p/api/greader.php`.

Illustrations :
1. Activer l'API
   ![1](https://cloud.githubusercontent.com/assets/1008324/9420432/f0920b96-4865-11e5-916a-9e5845b0f7ad.png)
2. Mettre un mot de passe API pour l'utilisateur concerné
   ![2](https://cloud.githubusercontent.com/assets/1008324/9420433/f4bb6212-4865-11e5-92c5-9dafc305115b.png)
3. Vérifier dans un navigateur que cela marche
   ![3](https://cloud.githubusercontent.com/assets/1008324/9420434/f8707334-4865-11e5-8722-598b58de95e1.png)
4. Ça marche si ça affiche `PASS`. Sinon voir https://github.com/FreshRSS/FreshRSS/issues/443#issuecomment-36666133
   ![4](https://cloud.githubusercontent.com/assets/1008324/9420436/fb519eca-4865-11e5-84b6-be0d50f6de6d.png)
5. Essayer depuis un client en utilisant l'adresse `https://example.net/FreshRSS/p/api/greader.php`, et le mot de passe API créé à l'étape 2.

En cas de problème, voir les logs API dans `./FreshRSS/data/users/_/log_api.txt`

N'hésitez pas à redemander.

**Comment by Alkarex** [comment]
Comme expliqué dans https://github.com/FreshRSS/FreshRSS/issues/443#issuecomment-36666133 , si vous avez une erreur 404 (fichier non trouvé) lors de l'étape de test, et que vous êtes sous Apache, voir http://httpd.apache.org/docs/trunk/mod/core.html#allowencodedslashes qu'il faut activer pour utiliser News+ (facultatif pour EasyRSS qui devrait fonctionner dès lors que vous obtenez un `PASS` au test _Check partial server configuration_).

**Comment by nervx** [comment]
C'est tout de suite beaucoup plus clair, je te remercie.

Donc j'ai effectué les étapes 1 et 2 sans problème.

Concernant la 3 et la 4, je me retrouve avec un "File not found" (avec le full et le partial).
Et si je rentre l'url http://info.theknight.fr/p/api/greader.php j'ai un "Bad Request ".

J'ai donc parcouru le fichier log_api.txt et je me retrouve en effet avec un PATH_INFO qui est vide (cest cette partie où j'ai vraiment du mal à comprendre ce qui ne marche pas et surtout ce qu'il faut faire)

log_api.txt :

```
User =>
badRequest()
Array
(
    [date] => 2015-08-21T17:55:45-05:00
    [headers] => Array
        (
            [Host] => info.theknight.fr
            [User-Agent] => Mozilla/5.0 (Windows NT 10.0; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0
            [Accept] => text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
            [Accept-Language] => fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
            [Accept-Encoding] => gzip, deflate
            [Cookie] => PHPSESSID=0mtmpegp1f32cmidkacbakfvq0; FreshRSS=bdv0q0tc1rr7ek5s8ejj0im7d1
            [Connection] => keep-alive
        )

    [_SERVER] => Array
        (
            [USER] => www-data
            [HOME] => /var/www
            [FCGI_ROLE] => RESPONDER
            [QUERY_STRING] =>
            [REQUEST_METHOD] => GET
            [CONTENT_TYPE] =>
            [CONTENT_LENGTH] =>
            [SCRIPT_FILENAME] => /var/www/freshrss/p/api/greader.php
            [SCRIPT_NAME] => /p/api/greader.php
            [PATH_INFO] =>
            [REQUEST_URI] => /p/api/greader.php
            [DOCUMENT_URI] => /p/api/greader.php
            [DOCUMENT_ROOT] => /var/www/freshrss
            [SERVER_PROTOCOL] => HTTP/1.1
            [GATEWAY_INTERFACE] => CGI/1.1
            [SERVER_SOFTWARE] => nginx/1.4.6
            [REMOTE_ADDR] => Mon_IP
            [REMOTE_PORT] => 26668
            [SERVER_ADDR] => IP_SERVEUR
            [SERVER_PORT] => 80
            [SERVER_NAME] => IP_SERVEUR
            [REDIRECT_STATUS] => 200
            [HTTP_HOST] => IP_SERVEUR
            [HTTP_USER_AGENT] => Mozilla/5.0 (Windows NT 10.0; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0
            [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
            [HTTP_ACCEPT_LANGUAGE] => fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
            [HTTP_ACCEPT_ENCODING] => gzip, deflate
            [HTTP_COOKIE] => PHPSESSID=0mtmpegp1f32cmidkacbakfvq0; FreshRSS=bdv0q0tc1rr7ek5s8ejj0im7d1
            [HTTP_CONNECTION] => keep-alive
            [PHP_SELF] => /p/api/greader.php
            [REQUEST_TIME_FLOAT] => 1440197745.8247
            [REQUEST_TIME] => 1440197745
        )

    [_GET] => Array
        (
        )

    [_POST] => Array
        (
        )

    [_COOKIE] => Array
        (
            [PHPSESSID] => 0mtmpegp1f32cmidkacbakfvq0
            [FreshRSS] => bdv0q0tc1rr7ek5s8ejj0im7d1
        )

    [INPUT] =>
)
```

En esperant que ca te parle plus qu'à moi :)

Pour info, je suis sur nginx.

**Comment by Alkarex** [comment]
Sur nginx, assurez-vous d'avoir bien configuré PATH_INFO et le `split_path_info`
http://wiki.nginx.org/PHPFcgiExample
http://kbeezie.com/nginx-configuration-examples/

**Comment by nervx** [comment]
Donc voici ce que j'ai fait :

-Verification de /etc/nginx/fastcgi_params 
-Suppression d'un "$" dans mon vhost (make sure $ does not exist after .php or /index.php/some/path/ will not match):)
Suite à cette suppression quand je clique sur les liens afin de vérifier la compatibilité je n'ai plus de message mais une page blanche (et rien n'apparait dans les logs)
-Ajout de cette ligne "fastcgi_split_path_info ^(.+?.php)(/.*)$;" dans mon vhost
Cela n'a rien changé

Mon Vhost ressemble à ceci pour le moment :

server {
  listen 80;
  server_name ADRESSE_SERVEUR;

  root /var/www/freshrss;

  index index.php index.html;

  access_log /var/log/nginx/freshrss-access.log;
  error_log /var/log/nginx/freshrss-error.log;

 location ^~ /data {
      deny all;}

   location / {

```
    try_files $uri $uri/ index.php;  }
```

   location ~\* .php {
        include /etc/nginx/fastcgi_params;
        fastcgi_split_path_info ^(.+?.php)(/.*)$;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param PATH_TRANSLATED  $document_root$fastcgi_path_info; }

}

Je sais pas si vous disposez d'un vhost déjà paramétré.. car je suis pas très à l'aise avec ca, il se peut que le problème vienne de là.

**Comment by Alkarex** [comment]
Avez-vous essayé la même syntaxe que sur http://wiki.nginx.org/PHPFcgiExample ?

```
location ~ [^/]\.php(/|$) {
  fastcgi_split_path_info ^(.+?\.php)(/.*)$;
  ...
}
```

**Comment by nervx** [comment]
Oui j'ai essayé beaucoups de choses sans succès, voici ci dessous mon fichier vhost pour le moment.

```
server
{
  listen 80;
  server_name  SERVEUR_ADRESSE;
  root /var/www/freshrss/;
  index index.php index.html index.htm;

                location ~ [^/]\.php(/|$)
                {
                fastcgi_split_path_info ^(.+?\.php)(/.*)$;
                if (!-f $document_root$fastcgi_script_name) 
                       {
                        return 404;
                        }
                fastcgi_pass 127.0.0.1:9000;
                fastcgi_index index.php;
                include fastcgi_params;
               }
}
```

Et j'obtiens une page blanche, aucun log dans nginx ni dans log_api.txt.

**Comment by Alkarex** [comment]
Peut-être qu'un de nos utilisateurs nginx aurait une idée et/ou partager sa configuration nginx?
@mathieumd, @izissise, @ToEvenStay, @Jucgshu, @Biniou180, @dkmatt0...

**Comment by dkmatt0** [comment]
Voici le mien :

```
upstream php-fpm {
    server unix:/var/run/php5-fpm.sock;
}
server {
    listen  80;
    listen  [::]:80;
    server_name  SERVEUR_ADRESSE;

    root  /data/freshrss;
    index index.html index.php;

    location ~ \.php$ {
            fastcgi_pass php-fpm;
            include fastcgi.conf;
    }
}
```

En espérant que cela t'aide :)

**Comment by Alkarex** [comment]
@dkmatt0 Merci. Utilisez-vous l'API (pour l'accès depuis une application Android)?

**Comment by dkmatt0** [comment]
Arf non, j'ai donc répondu trop vite... Désolé
Cela dit, la conf recommandé pour owncloud peut aider (au niveau du location) car c'est le même type d'url (machin.php/autrechose): https://doc.owncloud.org/server/7.0/admin_manual/installation/nginx_configuration.html

**Comment by Biniou180** [comment]
Bonjour bonjour!
Intéressant ce bug, j'avais testé easyRSS sans succès, je me demandais pourquoi, mais j'avais lâché l'affaire (pas trop le besoin...j'accede au site en responsive) :-)

Alors pour ma part, mon Nginx:

```
server {
    listen         80;
    server_name    rss.monserveur.org;
    rewrite        ^ https://$server_name$request_uri? permanent;
}

server {
    listen 443 ssl;
    server_name rss.monserveur.org;
    root /srv/http/freshRSS/;

    access_log     /var/log/nginx/rss.access.log;
    error_log      /var/log/nginx/rss.error.log;

    index  index.html  index.php;

    ssl_certificate /root/certificats_ssl/rss_chain.crt;
    ssl_certificate_key /root/certificats_ssl/webserver.ssl.private.key;

    location ~ ^(.+?\.php)(/.*)?$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$1;
        fastcgi_param PATH_INFO $2;
        fastcgi_pass unix:/run/php-fpm/php-fpm.sock;
        fastcgi_read_timeout 900s;
    }
}
```

...ça m'a permis de corriger une erreur de config en passant! :-)

J'ai retesté avec l'appli EasyRSS, ca marche. Ca n'a pas été sans mal (une extension oubliée par ci, un mauvais reglage nginx par là...) mais avec les instructions de @Alkarex c'est passé.

**Note importante**: j'ai galéré un bon quart d'heure à sans comprendre pourquoi easyRSS me refusait le mot de passe... jusqu'à ce que je kille l'application et la redémare, et la ca passe comme un charme. (je pense que c'est dû à un cache de l'appli...)

Note aussi qui m'a fait tiquer: dans mes vérifications, j'ai été voir les logs `./FreshRSS/data/users/_/log_api.txt` et j'y ai vu mes dernieres tentatives de connexion... avec le mot de passe en clair (**!**) :

```
    [_POST] => Array
        (
            [Email] => monuser
            [Passwd] => blablabla
            [accountType] => GOOGLE
            [service] => reader
            [source] => Sun-EasyRSS
        )

    [_COOKIE] => Array
        (
        )

    [INPUT] => Email=monuser&Passwd=blablabla&accountType=GOOGLE&service=reader&source=Sun-EasyRSS
```

...ca me chagrine un peu pour une URL accessible sans avoir besoin de se connecter :-/ peut etre faudrait-il protéger un peu mieux l'acces au log?

**Comment by Alkarex** [comment]
@Biniou180 Merci pour le retour détaillé. Pour le log, plusieurs choses :
- Le log n'est pas destiné à rester si verbeux
- Tout le répertoire `./data/` n'est pas sensé être exposé au Web
  - Seul le répertoire `./p/` est sensé être public
    - Donc `root` dans la configuration nginx devrait pouvoir être `root /srv/http/freshRSS/p/`
  - Le répertoire `./data/` est protégé par un `.htaccess` dans le cas d'Apache

**Comment by Biniou180** [comment]
Merci pour l'info!

> Le log n'est pas destiné à rester si verbeux

Dans de futures versions il sera moins verbeux, ou y a-t-il un paramètre pour régler la verbosité?

> Tout le répertoire ./data/ n'est pas sensé être exposé au Web

Au temps pour moi... du coup il suffit de bloquer son accès. Pour les gens qui passeraient par là, nginx peut s'en occuper comme cela: 

```
    # Deny access to the directory data
    location ~* /data {
            deny all;
            return 404;
    }
```

> Seul le répertoire ./p/ est sensé être public 

En fait, je pensais avoir fait une erreur dans ma config en ayant laissé `root /srv/http/freshRSS/p/;` initialement, et j'avais corrigé en `root /srv/http/freshRSS/;`, mais c'était bon... au final, pas besoin de faire un deny sur data, j'ai reconfiguré le root correctement.
(j'avais eu des logs bizarres où il cherchait /p/p/, d'où ma correction, mais ca semble ne plus être le cas).
Avec le root comme ca, l'adresse dans easyRSS devient `https://rss.monserveur.org/api/greader.php` (sans le `p/`), ca marche de mon côté.

**Comment by nervx** [comment]
Je vous remercie de votre aide, malheuresement je tombe sur une page blanche. Je vais donc procéder à une réinstallaton de certains packages. 

Si j'ai des changements positifs, je vous tiendrais au courant.

**Comment by Alkarex** [comment]
@Biniou180 Merci pour les détails supplémentaires.
Dans la version actuelle de FreshRSS en beta ou dev, le log API est beaucoup moins verbeux, parce que la ligne `logMe(debugInfo());` est commentée https://github.com/FreshRSS/FreshRSS/blob/10d98e0ce97d15882a06865b894136d3c0444d79/p/api/greader.php#L542

**Comment by nervx** [comment]
Tout d'abord un GRAND merci à vous ! 

Cela a marché quand j'ai tout simplement téléchargé la denière version de FreshRSS (beta)
https://github.com/FreshRSS/FreshRSS/archive/beta.zip

J'ai également pris exemple sur le vhost de @Biniou180.

```
server
 {
    listen         80;
    server_name    info.theknight.fr;
    #rewrite        ^ https://$server_name$request_uri? permanent;

    root /var/www/freshrss/p;

    access_log     /var/log/nginx/rss.access.log;
    error_log      /var/log/nginx/rss.error.log;

    index  index.html  index.php;


    location ~ ^(.+?\.php)(/.*)?$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$1;
        fastcgi_param PATH_INFO $2;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_read_timeout 900s;
    }
}
```

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/documentation/pull/10

**Comment by derdide** [comment]
Hi,
I'm using FreshRSS on a Synology. It works well, but I cannot get EasyRSS to work. When I use the greader.php URL in a browser, I get a "Bad Request". I'm currently testing inside my LAN hence the 192.168.x.x IP addresses:

The log gives following feedback:

```
 2016-07-08T08:21:51+02:00  badRequest()
 2016-07-08T08:21:51+02:00  Array
 (
     [date] => 2016-07-08T08:21:51+02:00
     [headers] => Array
         (
             [Host] => nas1:8080
             [User-Agent] => Mozilla/5.0 (Windows NT 10.0; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0
             [Accept] => text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
             [Accept-Language] => en-US,en;q=0.5
             [Accept-Encoding] => gzip, deflate
             [Cookie] => stay_login=1; did=lYF9JuLTTJrI0lo7AFhnR9Vlc3m9dJewjHBWlihp4mwRyo0CvUcMiAsNCUu7NansSGVRSbeGYsVYJptHA8CxXNhu5FiXvRZssRZQtLys0bKBQ8DsOrwQRqFvIm82IcG; id=Qv4xx8WppSrO61540M4N824800
             [Connection] => keep-alive
         )
     [_SERVER] => Array
         (
             [USER] => http
             [HOME] => /var/services/web
             [FCGI_ROLE] => RESPONDER
             [SCRIPT_FILENAME] => /volume1/web/freshrss/p/api/greader.php
             [QUERY_STRING] => 
             [REQUEST_METHOD] => GET
             [CONTENT_TYPE] => 
             [CONTENT_LENGTH] => 
             [SCRIPT_NAME] => /p/api/greader.php
             [REQUEST_URI] => /p/api/greader.php
             [DOCUMENT_URI] => /p/api/greader.php
             [DOCUMENT_ROOT] => /volume1/web/freshrss
             [SERVER_PROTOCOL] => HTTP/1.1
             [REQUEST_SCHEME] => http
             [GATEWAY_INTERFACE] => CGI/1.1
             [SERVER_SOFTWARE] => nginx/1.9.11
             [REMOTE_ADDR] => 192.168.1.123
             [REMOTE_PORT] => 64026
             [SERVER_ADDR] => 192.168.1.141
             [SERVER_PORT] => 8080
             [SERVER_NAME] => _
             [REDIRECT_STATUS] => 200
             [HTTP_HOST] => nas1:8080
             [HTTP_USER_AGENT] => Mozilla/5.0 (Windows NT 10.0; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0
             [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
             [HTTP_ACCEPT_LANGUAGE] => en-US,en;q=0.5
             [HTTP_ACCEPT_ENCODING] => gzip, deflate
             [HTTP_COOKIE] => stay_login=1; did=lYF9JuLTTJrI0lo7AFhnR9Vlc3m9dJewjHBWlihp4mwRyo0CvUcMiAsNCUu7NansSGVRSbeGYsVYJptHA8CxXNhu5FiXvRZssRZQtLys0bKBQ8DsOrwQRqFvIm82IcG; id=Qv4xx8WppSrO61540M4N824800
             [HTTP_CONNECTION] => keep-alive
             [PHP_SELF] => /p/api/greader.php
             [REQUEST_TIME_FLOAT] => 1467958911.9335
             [REQUEST_TIME] => 1467958911
         )

     [_GET] => Array
         (
         )

     [_POST] => Array
         (
         )

     [_COOKIE] => Array
         (
             [stay_login] => 1
             [did] => lYF9JuLTTJrI0lo7AFhnR9Vlc3m9dJewjHBWlihp4mwRyo0CvUcMiAsNCUu7NansSGVRSbeGYsVYJptHA8CxXNhu5FiXvRZssRZQtLys0bKBQ8DsOrwQRqFvIm82IcG
             [id] => Qv4xx8WppSrO61540M4N824800
         )

     [INPUT] => 
 )
```

My nginx conf looks as follows (auto-generated from Synology web station app, not sure how to change it):

```
    root    /volume1/web/freshrss;
    index    index.html  index.htm  index.cgi  index.php  index.php5 ;
    error_page 400 401 402 403 404 405 406 407 408 500 501 502 503 504 505 @error_page;

    location @error_page {
        root /var/packages/WebStation/target/error_page;
        rewrite ^ /$status.html break;
    }

    location ^~ /_webstation_/ {
        alias    /var/packages/WebStation/target/error_page/;
    }

    location ~* \.php$ {
        fastcgi_pass unix:/run/php-fpm/php56-fpm.sock;

        include fastcgi.conf;
    }

}
```

**Comment by Alkarex** [comment]
Hello @derdide 
Did you try theses steps: https://github.com/FreshRSS/FreshRSS/issues/443#issuecomment-36666133
Do you achieve a PASS?

**Comment by derdide** [comment]
Hello @Alkarex 
Yes, I tried - I found how to update the nginx conf files. No PASS, only Bad request when getting greader.php...

**Comment by Alkarex** [comment]
@derdide As long as you do not get a PASS in a browser, it is not worth trying with a mobile client (e.g. EasyRSS). You can try some of the nginx settings proposed by other users higher up https://github.com/FreshRSS/FreshRSS/issues/957#issuecomment-134346342 and post your debugging information again. As explained in https://github.com/FreshRSS/FreshRSS/issues/443#issuecomment-36666133 , a Bad Request is probably the sign of a bad nginx configuration for `PATH_INFO`
