### ISSUE TITLE
UI: Can you add preference for personal css-options

### ISSUE THREAD

**Issue by Kirill** [FreshRSS/FreshRSS#959]
Can you add options in preference, where user can add some custom styles. And user don't need to install Stylish or other addons.
In Tiny Tiny RSS this function present (sorry for russian, I don't found quick where change to english)
![2015-08-24 10_00_53](https://cloud.githubusercontent.com/assets/302940/9435347/51371224-4a47-11e5-9921-bfbfd7e6ba67.png)

**Comment by marienfressinaud** [comment]
You can try CustomCSS extension, I think it's what you need :) https://github.com/FreshRSS/Extensions

**Comment by Kirill** [comment]
**It's will be great, but...**

**This before Submit**
![2015-08-24 20_12_14](https://cloud.githubusercontent.com/assets/302940/9448419/cde22ef8-4a9c-11e5-99b3-2976e5c5af13.png)
**This after submit**
![2015-08-24 20_12_26](https://cloud.githubusercontent.com/assets/302940/9448425/d6dbf660-4a9c-11e5-9100-4545ce97f79c.png)
**It's files in folder static**
![2015-08-24 20_12_59](https://cloud.githubusercontent.com/assets/302940/9448433/e62d7aee-4a9c-11e5-87c6-151e569fefa4.png)
**But nothing on rss**
![2015-08-24 20_13_47](https://cloud.githubusercontent.com/assets/302940/9448444/f7ab7546-4a9c-11e5-961e-a8eea16e49c6.png)
**And if I open manage css again - it's empty**
![2015-08-24 20_16_36](https://cloud.githubusercontent.com/assets/302940/9448459/1d9210c6-4a9d-11e5-9c4e-3fb41d970e8c.png)

**Comment by Kirill** [comment]
In style.krak.css all quotes replace with &quot; and not working. I replace in file for correct symbol and I see rss correctly.

**Comment by Kirill** [comment]
Thanks. It's work.

**Comment by Alkarex** [comment]
Thanks for the feedback :+1:
