### ISSUE TITLE
[feature] Add reset user password for admin

### ISSUE THREAD

**Issue by aledeg** [FreshRSS/FreshRSS#960]
It would be nice to have a way to reset the user password as an admin. Maybe also the email address.
Because at the moment action on user management are pretty limited.

**Comment by Alkarex** [comment]
https://github.com/FreshRSS/FreshRSS/issues/901

**Comment by blankoworld** [comment]
What's about non-admin users?

I got a user that don't have any way to reset the password. And admin interface don't permit to change its password.

What should I do for this user?

**Comment by Frenzie** [comment]
I'm pretty sure the FR is for an admin to change any user's password. :-)

**Comment by Alkarex** [comment]
@blankoworld For the time being, the easiest is if you are able to use the command-line, then you can use:
```sh
./cli/update-user.php --user username --password 'password' --api_password 'api_password'
```
https://github.com/FreshRSS/FreshRSS/blob/master/cli/README.md#commands
