### ISSUE TITLE
Unable to log in from Easyrss on Android but can log in from browser

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#962]
When attempting to log in from the easyrss app on Android (lastest F-Droid build), the error "Login failed, please check your username and password" is displayed. However, I can log in from a browser on the same device as well as on a desktop machine.

Looking at the error log for the webserver (apache2), there is a error:
File does not exist: /var/www/freshrss/p/accounts

Indeed, when I look in the directory /var/www/freshrss/p, the accounts directory is missing. The /var/www/freshrss/p directory has user/group as www-data:www-data and can be written by the user.

**Comment by Alkarex** [comment]
Hello @markbrown778 ,
You are probably using the wrong address for the FreshRSS API end-point. It must be the full path to your `greader.php` file (documentation https://github.com/Alkarex/EasyRSS#compatible-rss-services ), like `https://your.server.example/FreshRSS/p/api/greader.php` or `https://your.server.example/api/greader.php` depending on your settings. Remember also that the API password is not the same as the Web password.

More information:
- In French https://github.com/FreshRSS/FreshRSS/issues/957#issuecomment-133581712
- In English https://github.com/FreshRSS/FreshRSS/issues/443#issuecomment-36666133 , https://github.com/Alkarex/EasyRSS/issues/13#issuecomment-106428059

**Comment by ghost** [comment]
Thank you Alkarex, for your very quick response.
I used https://your.server.example/api/greader.php and errors no longer appear in the apache error.log file; however, I still can't log in from the easyrss app.

## Checking the data/users/_/log_api.txt file, every time I attempt to log in the text

serviceUnavailable()
is appended to the log.

Would be grateful for your help.

**Comment by Alkarex** [comment]
`serviceUnavailable()` indicates that you have not activated the API, as explained in step 1: https://github.com/FreshRSS/FreshRSS/issues/443#issuecomment-36666133

**Comment by ghost** [comment]
Thank you, I got it working with your help!
I checked the "Allow API Access" in the "Authentication page" and also set the API password to be the same as the web access password. That fixed the problem.

Many thanks once again for your help and for a great program!
