### ISSUE TITLE
Reload button when installation checking is red

### ISSUE THREAD

**Issue by Alwaysin** [FreshRSS/FreshRSS#964]
When on the first step (vérifications), why not add a "reload" or "re-check" button when not all is green?

**Comment by aledeg** [comment]
<img src="http://i3.kym-cdn.com/photos/images/original/000/976/824/913.gif" />
There is the F5 button to do that. I really think it's unnecessary to spend time on that.

**Comment by Alwaysin** [comment]
It was just a suggestion!
It could be a little smoother, someone might feel "lost" when seeing nothing can be done from the website directly.
