### ISSUE TITLE
Erreur Apache2 avec Persona : "audience mismatch: domain mismatch"

### ISSUE THREAD

**Issue by Leepic** [FreshRSS/FreshRSS#969]
Bonjour,

Lorsque je tente de me connecter avec Persona depuis mon réseau local (10.0.0.50) j'obtiens l'erreur
`L'identifiant est invalide` sur l'UI FreshRSS.
Dans les logs de FreshRSS j'ai `[warning] --- audience mismatch: domain mismatch`

Cette erreur se produit uniquement quand j'essai de me connecter en local. À distance ou avec un VPN aucun problème.

**Comment by Alkarex** [comment]
Je pense que cela devrait aller si vous utilisez bien le DNS / IP externe de votre site.

**Comment by Leepic** [comment]
Mon instance est auto-hébergé avec un DNS Dynamique mais en local ça m'affiche cette erreur. En utilisant le DNS hébergé sur la même machine ou par exemple ceux du FAI/FDN ça ne change rien non plus.

**Comment by Alkarex** [comment]
Utilisez-vous bien exactement la même adresse (y compris HTTP(S))?
Suggestion pour débogger : placer un fichier `phpinfo.php` sur votre serveur avec le contenu ci-dessous, y accéder depuis votre réseau local puis à distance, et comparer les résultats (en particulier les champs _host_) :

``` php
<?php
phpinfo();
```

**Comment by Leepic** [comment]
Oui, j'utilise toujours la même URL et je n'ai pas d'HTTPS.

Les champs qui changent sont :
- `_SERVER["HTTP_HOST"]`
- `_SERVER["SERVER_NAME"]`

Résultat pour les deux variables :
En local (hosts non modifié) : IP du serveur (10.0.0.50),
En local (hosts modifié) : URL du site
À distance : URL du site

J'ai remarqué que sur ma machine qui tente de se connecter, si le nom du site web fait la correspondance avec l'IP local 10.0.0.50, ça ne pose plus de problème.
Dans ce cas les deux variables ci-dessus sont les mêmes qu'une connexion à distance.

Je suppose donc que le souci vient de la variable `_SERVER["SERVER_NAME"]` ?

Edit: Visiblement c'est bien cette variable : https://github.com/mozilla/mod_authnz_persona#how-it-works

Edit n°2 : J'ai testé sur ma machine en local, en me connectant dessus avec un autre périphérique depuis le réseau local, je reproduis le problème à partir de la version 1.1.2-bêta de FreshRSS. Dans la version 1.0.0 stable, aucun souci.

**Comment by Alkarex** [comment]
Côté Apache, vérifier vos paramètres pour :
http://httpd.apache.org/docs/trunk/mod/core.html#servername
http://httpd.apache.org/docs/trunk/mod/core.html#usecanonicalname

Pourriez-vous insérer la ligne de déboggage suivante à la ligne 214 de `authController.php` https://github.com/FreshRSS/FreshRSS/blob/f148e3938cc8daaaef1c71853594fbe142a1329e/app/Controllers/authController.php#L212 et regarder ensuite dans les logs FreshRSS

``` php
Minz_Log::error('Persona verify: ' . $params);
```

**Comment by Leepic** [comment]
Désolé pour le délais de réponse mais je ne pouvais pas tester sur le serveur localement, n'étant pas à domicile.

J'ai regardé et testé les paramètres comme vous m'avez indiqué mais ça n'a rien changé, toujours le même problème.

Après avoir inséré la ligne de déboggage, à la suite de `audience=`, j'ai le nom de domaine de mon instance de FreshRSS qui s'affiche tout le temps.
Pourtant la variable PHP `$_SERVER['HTTP_HOST']` change, soit mon IP locale soit le nom de domaine de mon instance.

**Comment by Alkarex** [comment]
Bon, ça sentait déjà le sapin, mais maintenant une date est connue : le service Persona fermera complètement le 30 novembre
- https://wiki.mozilla.org/Identity/Persona_Shutdown_Guidelines_for_Reliers
- https://groups.google.com/forum/#!msg/mozilla.dev.identity/mibOQrD6K0c/kt0NdMWbEQAJ
