### ISSUE TITLE
Error search link in related tags

### ISSUE THREAD

**Issue by marcomrc** [FreshRSS/FreshRSS#970]
If you click on a tag in related tags menù the link generated is (for example): http://demo.freshrss.org/i/?search=%2523Python

The term searched is:

%23Python

so:

There is no article to show.

**Comment by Alkarex** [comment]
Thanks for the bug report. Fixed in https://github.com/FreshRSS/FreshRSS/pull/973
Test welcome (there is another bug for tags with white spaces).

**Comment by Alkarex** [comment]
The fixed has been merged in the /dev branch. Feedback welcome https://github.com/FreshRSS/FreshRSS/issues/974
