### ISSUE TITLE
Change default rss in new user account

### ISSUE THREAD

**Issue by marcomrc** [FreshRSS/FreshRSS#972]
Creating a new user account by default there are the feedrss of freshrss e github.

It's possible to add/change the default rss when a user create an account?

Thanks

**Comment by Alkarex** [comment]
Currently, you would have to change the MySQL and SQLite files, e.g.
https://github.com/FreshRSS/FreshRSS/blob/d073331d2496d427dad972b9e024f247015e50ce/app/SQL/install.sql.mysql.php#L60
It could indeed be nice with a configuration for that.

**Comment by marcomrc** [comment]
Thanks, I added my default rss successfully
