### ISSUE TITLE
Call for testing /dev before 1.1.3-beta

### ISSUE THREAD

**Issue by Alkarex** [FreshRSS/FreshRSS#974]
Hello everybody,
[Beta 1.1.3](https://github.com/FreshRSS/FreshRSS/milestones/1.1.3-beta) is ready and only lacks some of your testing to get released.
So all feedback welcome regarding the current /dev branch :-)

https://github.com/FreshRSS/FreshRSS/issues/919

**Comment by Alkarex** [comment]
Ping @marienfressinaud @aledeg @Alwaysin @Jucgshu @Humfred @ToEvenStay @Wanabo @marcomrc

**Comment by marienfressinaud** [comment]
Update done to the latest dev version :)

**Comment by Wanabo** [comment]
Is this the right link for 1.1.3-beta?, https://github.com/FreshRSS/FreshRSS/tree/dev
I'll test a.s.a.p.

**Comment by aledeg** [comment]
The right link is https://github.com/FreshRSS/FreshRSS/milestones/1.1.3-beta

**Comment by Alkarex** [comment]
@Wanabo Yes :-) And if you are using the ZIP file, here is it https://github.com/FreshRSS/FreshRSS/archive/dev.zip

**Comment by Alwaysin** [comment]
Updated as well, I'll report if I find any problem!

**Comment by Jucgshu** [comment]
No problem so far on latest dev branch !

Gr8 work as always :-)

**Comment by Wanabo** [comment]
Just overwrite my old files with new 1.1.3-beta. But now it wants me to install again!
How to keep my existing installation?

**Comment by Wanabo** [comment]
Ok, everything is working well. But had to add and remove some lines in the Dutch translation.
Rechecked all Dutch language files and gave them their own branch, https://github.com/Wanabo/FreshRSS-Dutch-translation/tree/1.1.3-de

**Comment by marcomrc** [comment]
I'm testing new beta version, thanks

**Comment by marienfressinaud** [comment]
We should fix https://github.com/FreshRSS/FreshRSS/issues/980

**Comment by aledeg** [comment]
Apart from the bug I found and fixed, so far so good.

**Comment by Wanabo** [comment]
No entries found in error.log. No errors found in FreshRSS.log.
Website is running correctly.
Running FreshRSS 1.1.3-dev on this server setup:
KVM VPS
5 GB RAM
Apache 2.4.12
Php-FPM 5.6.8
MariaDB 5.5.41
DirectAdmin 1.48.3

Still using SQLite as database (file). Tried to install with MySQL (MariaDB) with the previous version, but the installer could not connect to the database. I think this was all ready mentioned somewhere that underscores and other special characters prevent this. Unfortunately DirectAdmin uses underscores by default in the database names. Not tested with 1.1.3-dev
But I am pleasantly surprised by the performance of the SQLite database and intent to keep using it.

**Comment by marienfressinaud** [comment]
Thanks @Wanabo for your feedback! :)

@Alkarex > if you want I have some time today to release the new version ;)

**Comment by Alkarex** [comment]
@marienfressinaud Ok, go ahead! :-)

**Comment by marienfressinaud** [comment]
Done! https://github.com/FreshRSS/FreshRSS/releases/tag/1.1.3-beta

**Comment by marienfressinaud** [comment]
Thanks everyone for the work and feedback :).
