### ISSUE TITLE
base_url is not correct when FreshRSS is behind SSL backed reverse proxy

### ISSUE THREAD

**Issue by zirkome** [FreshRSS/FreshRSS#975]
Hi,

I'm actually using FreshRSS on Apache2.4 and put it behind an NGINX reverse proxy. I set my reverse proxy to use SSL and redirect traffic to my Apache. The problem is that the traffic between Nginx and Apache is HTTP (port 80) so when `config.php` is created `base_url` is totally wrong: `http` + port 80 at the end. When redirecting traffic like that there is a variable set in `$_SERVER` which take in account the front protocol: `HTTP_X_FORWARDED_PROTO`.

I think adding a check for that variable must be included in `install.php` to use the right port and right protocol: the real ones :)

**Comment by Alkarex** [comment]
Hello @kokaz,
Could you please give a try to this patch? https://github.com/FreshRSS/FreshRSS/pull/1013
