### ISSUE TITLE
Responsive layout: access configuration from mobile

### ISSUE THREAD

**Issue by marcomrc** [FreshRSS/FreshRSS#976]
In responsive layout is not displayed configuration button and site name/logo.

**Comment by Alwaysin** [comment]
Duplicate of #45 (but in French).

Anyway, +1, much wanted here :)

**Comment by Alkarex** [comment]
Now this is the main ticket. See https://github.com/FreshRSS/FreshRSS/issues/45 for background discussion in French.

**Comment by marienfressinaud** [comment]
I'm closing this ticket in favour of #1876 which contains more discussions.
