### ISSUE TITLE
[bug] account limit for account creation is not working

### ISSUE THREAD

**Issue by aledeg** [FreshRSS/FreshRSS#981]
When I set up a account limit with a positive value in the system configuration page, it has no effect on the account creation.
The expect behavior is to actually limit the number of account I am able to create.

**Comment by marienfressinaud** [comment]
That's on purpose: I consider an administrator should be able to create new accounts even if the limit has been reached. Simple usecase: you don't want to open registrations to anyone but you want to host a friend, that's a simple way to be sure no one will register unless your friend.

**Comment by aledeg** [comment]
In that case, it should be mentioned somewhere on the interface. Because, if you're like me and you try this for the first time, it's quite confusing.
Maybe we could add some description along with the existing text. Or at least have an entry in the documentation to explain that behavior.

**Comment by psukys** [comment]
This could be solved by changing the wording, instead of
```Max number of accounts```
use something like
```Max allowed registrations```
with a comment ```Registration is open until this amount of accounts is reached```

**Comment by math-GH** [comment]
is it still a valid bug?

in 1.18.1 the setting looks like:
![grafik](https://user-images.githubusercontent.com/1645099/129491348-8fa87e9a-2adb-4279-bdfb-42ce78dd0ffd.png)

For me it is clear what happens

**Comment by Frenzie** [comment]
Nothing has changed.
