### ISSUE TITLE
track visitors with a statistics program

### ISSUE THREAD

**Issue by Wanabo** [FreshRSS/FreshRSS#985]
I would like to track click activity from my visitors, where they came from, what search phrases were used.

I use BBClone for this purpose. But it does not register javascript links for example the links from articles. It only registers the categories people visit.

In layout.phtml I have added these lines of code:

``` php
/* BBClone */
define("_BBC_PAGE_NAME", ' · '.str_replace(' · '.FreshRSS_Context::$system_conf->title, '',htmlspecialchars_decode(substr(self::title(), ($pos = strpos(self::title(), ')')) !== false ? $pos + 1 : 0))));
define("_BBCLONE_DIR", $_SERVER['DOCUMENT_ROOT']."/bbclone/");
define("COUNTER", _BBCLONE_DIR."mark_page.php");
if (is_readable(COUNTER)) include_once(COUNTER);
```

How to track article clicks?

**Comment by Alkarex** [comment]
Related to https://github.com/FreshRSS/FreshRSS/issues/938 and https://github.com/FreshRSS/FreshRSS/issues/986
