### ISSUE TITLE
Scroll not always mark post as read

### ISSUE THREAD

**Issue by Kirill** [FreshRSS/FreshRSS#987]
**FreshRSS 1.1.3-dev**

When scroll down fast (not interesting post), they don't mark as read.

I return to top and see that post not read:
![I return to top and see that post not read](https://cloud.githubusercontent.com/assets/302940/9878969/a235cece-5bc5-11e5-86df-f85c87c35f45.png)

Video with test:
https://youtu.be/vgQG-b2R1lc

**Comment by aledeg** [comment]
Thank you for reporting this

**Comment by Alkarex** [comment]
This bug was a bit forgotten, but some improvements have been made in the /dev branch https://github.com/FreshRSS/FreshRSS/issues/1123 which I should have fixed this issue. Feel free to re-open if needed
