### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by Liandriz** [FreshRSS/FreshRSS#988]
Is is possible to auto cleanup pubsub logs, in "/data/users/_/log_pshb.txt" when cleaning profile logs?
Just see that this file was over 1G, rhaaaaa.

And for user log, any way to contain it under a sizelimit? Got blank page when visiting "i/?a=logs", had to manually delete my log file.

**Comment by Alkarex** [comment]
@Liandriz Please test this patch if you can https://github.com/FreshRSS/FreshRSS/issues/1010

**Comment by Liandriz** [comment]
Both log_api.txt and log_pshb.txt cleared when personal admin logs cleared.
Tried an update to beta dev from this one, still got my theme wiped :0

**Comment by Alkarex** [comment]
Thanks for testing. The theme bug is another issue https://github.com/FreshRSS/FreshRSS/issues/935
