### ISSUE TITLE
Flux « À toi les étoiles »

### ISSUE THREAD

**Issue by Cypouz** [FreshRSS/FreshRSS#989]
Salut !

Ce flux ne fonctionne pas dans FreshRSS v1.0. Firefox l'affiche quant à lui plutôt correctement. URL : http://franck.futura-sciences.com/podcast.xml

**Comment by aledeg** [comment]
Je viens d'essayer avec la dernière beta et ça fonctionne
correctement.
Si tu n'a pas de problèmes pour mettre à jour FreshRSS, je
te conseille de le faire.
Sinon, il faudra regarder plus en détail. 

Le
2015-09-24 13:08, Cypouz a écrit : 

> Salut ! 
> 
> Ce flux ne
> fonctionne pas dans FreshRSS v1.0. Firefox l'affiche quant à lui plutôt
> correctement. URL : http://franck.futura-sciences.com/podcast.xml [1] 
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [2].

## Links:

[1] http://franck.futura-sciences.com/podcast.xml
[2]
https://github.com/FreshRSS/FreshRSS/issues/989

**Comment by aledeg** [comment]
Après des tests plus poussés, FreshRSS ne charge que les 2 premiers
articles. As tu la même chose avec la version 1.0? 

Apparement, ce
n'est pas un problème de SimplePie car il trouve l'ensemble des
articles.
J'ai voulu le tester sur la démo malheureusement, il n'y a pas
de moyen de se connecter et d'ajouter des flux. 

Le 2015-09-24 13:08,
Cypouz a écrit : 

> Salut ! 
> 
> Ce flux ne fonctionne pas dans
> FreshRSS v1.0. Firefox l'affiche quant à lui plutôt correctement. URL :
> http://franck.futura-sciences.com/podcast.xml [1] 
> 
> ## 
> 
> Reply to
> this email directly or view it on GitHub [2].

## Links:

[1]
http://franck.futura-sciences.com/podcast.xml
[2]
https://github.com/FreshRSS/FreshRSS/issues/989

**Comment by Cypouz** [comment]
Oui, seulement deux articles de mon coté aussi. Mais ce ne sont pas les deux premiers. L'un est du 19 janvier 2005 et l'autre du 15 août 2012.

**Comment by aledeg** [comment]
C'est vraiment étrange. Il faudra regarder ça plus en détail.
Je
n'avais pas fait attention à la date des articles. J'ai du probablement
charger les même articles que les tiens. 

J'ai testé le xml dans le
validateur du W3C et il n'est pas valide. Il faut peut-être regarder de
ce coté.
À moins que ce soit à cause des médias présents dans le XML.

Le 2015-09-24 13:57, Cypouz a écrit : 

> Oui, seulement deux articles
> de mon coté aussi. Mais ce ne sont pas les deux premiers. L'un est du 19
> janvier 2005 et l'autre du 15 août 2012. 
> 
> ## 
> 
> Reply to this email
> directly or view it on GitHub [1].

## Links:

[1]
https://github.com/FreshRSS/FreshRSS/issues/989#issuecomment-143004704

**Comment by Alkarex** [comment]
Le flux est malheureusement très invalide. Les articles n'ont pas de GUID (utilisé pour identifier les articles de manière unique). Et tous les liens `<link>`sont identiques. Une approche serait de forcer la génération d'un hash basé sur { titre, link, date } dans les paramètres de SimplePie, mais cela engendrerait d'autres problèmes.

**Comment by Cypouz** [comment]
Comment Firefox s'en sort-il pour les afficher correctement ?

**Comment by Alkarex** [comment]
Firefox affiche simplement tout le flux. Dans notre cas, il faut être capable d’interpréter le flux, par exemple pour savoir quel article est nouveau.

**Comment by Alkarex** [comment]
Plus d'informations sur http://simplepie.org/wiki/reference/simplepie_item/get_id
Nous utilisons le paramètre par défaut, à savoir `false`, comme dit plus haut, au lieu de forcer un hash.

**Comment by Alkarex** [comment]
P.S. Vous pouvez expérimenter en mettant
`$item->get_id(true),`
https://github.com/FreshRSS/FreshRSS/blob/9e43937f8c7f51c1bcd4e8009c6d1233868d5479/app/Models/Feed.php#L325
mais au risque de vous retrouver avec de plus nombreux doublons.

**Comment by Cypouz** [comment]
Je suis en contact avec le webmaster, qui a ajouté un GUID aux éléments du flux. Du coup, c'est tout bon !

**Comment by aledeg** [comment]
:+1:
