### ISSUE TITLE
Flux Planning Université

### ISSUE THREAD

**Issue by qwertygc** [FreshRSS/FreshRSS#990]
Salut !
Dans mes logs, j'ai une erreur : "Feed error []".

Une idée comment résoudre ?

**Comment by Alwaysin** [comment]
Ben en se rendant sur le feed on se rend compte qu'il ne marche pas ; rien à voir avec FreshRSS. Il faut voir avec le gestionnaire du flux.

**Comment by aledeg** [comment]
On peut fermer ce ticket?

**Comment by Alkarex** [comment]
@qwertygc Merci de réouvrir avec plus d'informations, si le problème est toujours d'actualité
