### ISSUE TITLE
Favicons not generated

### ISSUE THREAD

**Issue by marcomrc** [FreshRSS/FreshRSS#991]
I use FreshRSS 1.1.3-beta and Favicons are not generated, in the folder data/favicons there are only a "world image" 

How I can debug this problem? 

thanks in advance for support

**Comment by laurent-angeli** [comment]
is php_fileinfo module activated ?

**Comment by marcomrc** [comment]
I don't know, but I try to install FreshRSS 1.1.3-beta on an other server and favicon are generated, so I suppose It depends by hosting provider config.

**Comment by Alkarex** [comment]
Does `./data/favicons` contain any `.txt` file?

**Comment by marcomrc** [comment]
Yes, I solved: on my hosting provider CURL wasn't enabled by default.
Now favicons are generated automatically

Thanks
