### ISSUE TITLE
Partage avec Movim

### ISSUE THREAD

**Issue by essembeh** [FreshRSS/FreshRSS#992]
Movim est un réseau social libre qui propose de partager des contenus avec ses contacts.

Ce serait bien que FreshRSS permette de partager des articles dans Movim comme avec Wallabag, Diaspora & co.

**Comment by aledeg** [comment]
Bonne idée! 

J'ai rapidement cherché dans la documentation de Movim
comment faire cela, mais je n'ai rien trouvé.
As tu une documentation
qui explique comment faire? ou des examples? ou les deux? 

Merci 

Le
2015-10-06 10:44, Sébastien M-B a écrit : 

> Movim est un réseau social
> libre qui propose de partager des contenus avec ses contacts. 
> 
> Ce
> serait bien que FreshRSS permette de partager des articles dans Movim
> comme avec Wallabag, Diaspora & co. 
> 
> ## 
> 
> Reply to this email
> directly or view it on GitHub [1].

## Links:

[1]
https://github.com/FreshRSS/FreshRSS/issues/992

**Comment by essembeh** [comment]
Pas vraiment lu la doc, je découvre Movim justement.
Ils proposent un _bookmarklet_ (il me semble que c'est comme ca que ca s'appelle)

```
javascript:(function(){location.href='https://pod.movim.eu/index.php/share&url='+encodeURIComponent(location.href);})();
```

Après il faudra surement mettre l'URL du _pod_ (ici pod.movim.eu) customizable dans les préférences comme pour les autres services.

**Comment by aledeg** [comment]
Super. Je pense que ça suffira pour tester. Je vais regarder ça!

Le 2015-10-06 11:51, Sébastien M-B a écrit : 

> Pas vraiment lu la
> doc, je découvre Movim justement.
> Ils proposent une _bookmarklet_ (il
> me semble que c'est comme ca que ca s'appelle) 
> 
> javascript:(function(){location.href='https://pod.movim.eu/index.php/share&url='+encodeURIComponent(location.href);})();
> 
> Après il faudra surement mettre l'URL du _pod_ (ici pod.movim.eu)
> customizable dans les préférences comme pour les autres services. 
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].

## Links:

[1]
https://github.com/FreshRSS/FreshRSS/issues/992#issuecomment-145907570

**Comment by marienfressinaud** [comment]
:+1:

**Comment by aledeg** [comment]
Je viens de coder ce partage dans mon repository. Tu peux le tester ici https://github.com/aledeg/FreshRSS/tree/movim. Je ne l'ai pas testé car je n'ai pas de compte Movim.

Les retours sont bienvenus!

**Comment by essembeh** [comment]
Je viens de tester ta branche @aledeg 
La mauvaise nouvelle c'est que j'ai une erreur 404 coté Movim.

```
https://pod.movim.eu//index.php/share?url=%2F%2Ffreshrss.org%2Ffreshrss-supports-pubsubhubbub.html
```

La bonne nouvelle c'est que _j'avais_ exactement la même erreur avec le bookmarklet :)
Ils avaient un ticket qui a été fermé il y a quelques jours dessus (https://github.com/edhelas/movim/issues/52). Le bookmarlet remarche maintenant, son code a changé:

```
javascript:(function(){location.href='https://pod.movim.eu/index.php/share/'+escape(encodeURIComponent(location.href));})();
```

Voici une URL obtenue avec le bookmarklet qui marche:

```
https://pod.movim.eu/index.php/share/http%253A%252F%252Ffreshrss.org%252Ffreshrss-supports-pubsubhubbub.html
```

Je remarque trois choses:
- Il faut adapter l'URL, et enlever le le paramètre url=
- les caratères sont pas échapés de la même manière (%2F vs %252F), je ne sais pas si ca a un impact 
- il faut que l'URL partagée commence par http:// (encodé), je viens de tester sans et j'ai une erreur 'URL non valide', il faut donc que FreshRSS l'ajoute.

Merci en tout cas ;)

**Comment by aledeg** [comment]
Je vais modifier ça ce soir pour un nouvel essai

**Comment by aledeg** [comment]
Je viens de mettre à jour ma branche. J'espère que ça fonctionne. Le lien créé a l'air de ressembler au lien du bookmarklet.
Tiens moi au courant !

**Comment by essembeh** [comment]
Bon je viens de tester, on s'approche :)

l'URL construite est la suivante

```
https://pod.movim.eu//index.php/share/%252F%252Ffreshrss.org%252Ffreshrss-supports-pubsubhubbub.html
```

Il manque juste 
- le _http_ (ou _https_ si la source est en https)
- le ':' encodé en %253A

Si je les rajoute à la main, ca marche :)
Pour info il faudrait que l'URL soit:

```
https://pod.movim.eu//index.php/share/http%253A%252F%252Ffreshrss.org%252Ffreshrss-supports-pubsubhubbub.html
```

**Comment by aledeg** [comment]
Ce sont des informations que je n'ai pas quand j'accède à la variable ~LINK~. Il va falloir voir pourquoi je n'ai pas ces informations. En tout cas, c'est étrange que le lien doive être encodé 2 fois.

**Comment by essembeh** [comment]
Bon je viens de faire le test et il n'est pas nécessaire d'encoder l'URL deux fois.
C'est ce que le bookmarlet fait (en fait un _encode_ puis un _escape_)

C'est dommage de pas avoir le protocole (http, https ...) dans ~LINK~ ou une autre (peut etre faudrait il ajouter ~LINK_PROTOCOL~?).
Sinon une première solution bien Q'n'D serait de forcer http, ce doit être le protocole de 99% des articles chez la plupart des gens...

**Comment by aledeg** [comment]
En fait, il n'y a rien à faire pour le protocole. Je pense que ça vient du RSS directement. Si tu prends d'autres RSS, le http ou https apparaissent. Essaye avec un autre RSS pour voir !

Je vais enlever un des deux encodages ce soir.

**Comment by marienfressinaud** [comment]
Arf oui, le flux de freshrss.org n'inclue pas le protocole :s En fait à la base, comme c'est un site statique, c'était pour que ça soit portable, sauf qu'au niveau du RSS on ne peut pas faire ça. Bref, je regarderai pour forcer le protocole

**Comment by essembeh** [comment]
En effet avec le flux de Numerama, aucun problème, le protocole est présent et le partage fonctionne.

Si ca se trouve le flux de freshrss.org est l'exception qui ne contient pas de protocole parmis tous mes flux :)

**Comment by aledeg** [comment]
Super, alors je vais faire un PR

**Comment by Alkarex** [comment]
Est-ce que le double encodage de https://github.com/FreshRSS/FreshRSS/pull/1000 est donc bien ce qu'il faut ?

**Comment by Alkarex** [comment]
P.S. Bravo pour le 1000ème ticket, @aledeg ;-)

**Comment by aledeg** [comment]
:), je ne sais pas pour le double encodage. Il n'est utile que pour avoir la même sortie que le bookmarklet de Movim.
Je ne sais pas si c'est utile de le conserver en l'état, mais comme je n'ai pas de compte Movim, je ne peux pas vraiment tester.
