### ISSUE TITLE
Impossible de faire l'installation

### ISSUE THREAD

**Issue by ToEvenStay** [FreshRSS/FreshRSS#993]
Bonjour ,
Voilà donc le vps à été reinstallé (debian , ispconfig3 , nginx , mysql)
Et je suis bloqué à l'installation de freshrss . Je na'rrive pas à aller plus que la page ou l'on doit renseigner la configuration générale . Une fois cliquer sur passez à l'étape suivante , sa recharge la même page . Et je ne sais pas aller voir les logs pour savoir de quoi cela vient.
Merci d'avance de votre aide .

**Comment by Alkarex** [comment]
Bonjour,
Quelle version de FreshRSS ?
Que donnent les logs nginx / PHP ?
P.S.: Ah, j'avais lu trop vite votre message à propos des logs. Il faudrait commencer par cela. Sous Debian, regardez par exemple dans `/var/log/nginx/`

**Comment by ToEvenStay** [comment]
Version Dev comment puis-je vous donnez les logs de cette facon ?

**Comment by Alkarex** [comment]
Essayez de voir dans votre répertoire `/var/log/nginx/` (peut varier selon la configuration nginx) s'il y a des logs. S'il y en a, essayez de copier-coller ici les dernières lignes.

**Comment by ToEvenStay** [comment]
Voici le fichier des erreur des log : 

2015/10/07 04:13:27 [emerg] 11477#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2015/10/07 04:13:27 [emerg] 11477#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2015/10/07 04:13:27 [emerg] 11477#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2015/10/07 04:13:27 [emerg] 11477#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2015/10/07 04:13:27 [emerg] 11477#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2015/10/07 04:13:27 [emerg] 11477#0: still could not bind()
2015/10/07 04:13:29 [emerg] 11536#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2015/10/07 04:13:29 [emerg] 11536#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2015/10/07 04:13:29 [emerg] 11536#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2015/10/07 04:13:29 [emerg] 11536#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2015/10/07 04:13:29 [emerg] 11536#0: bind() to 0.0.0.0:80 failed (98: Address already in use)
2015/10/07 04:13:29 [emerg] 11536#0: still could not bind()
2015/10/07 04:46:06 [notice] 24976#0: signal process started
2015/10/07 05:17:43 [error] 25680#0: *91 open() "/var/www/html/manual/ja/developer/API.html" failed (2: No such file or directory), client: 66.249.78.217, server: server1, request: "GET /manual/ja/developer/API.html HTTP/1.1", host: "homenursingcare.be"
2015/10/07 06:03:02 [error] 26506#0: *119 "/var/www/html/manual/index.php" is not found (2: No such file or directory), client: 66.249.78.74, server: server1, request: "GET /manual/ HTTP/1.1", host: "filesilver.com"
2015/10/07 06:06:41 [error] 26506#0: *123 "/var/www/html/manual/index.php" is not found (2: No such file or directory), client: 66.249.64.113, server: server1, request: "GET /manual/ HTTP/1.1", host: "homenursingcare.be"
2015/10/07 06:07:33 [error] 26506#0: *124 open() "/var/www/html/manual" failed (2: No such file or directory), client: 66.249.64.190, server: server1, request: "GET /manual HTTP/1.1", host: "www.homenursingcare.be"
2015/10/07 08:04:59 [error] 26506#0: *291 open() "/var/www/html/test/php/test.html" failed (2: No such file or directory), client: 66.249.78.224, server: server1, request: "GET /test/php/test.html HTTP/1.1", host: "homenursingcare.be"
2015/10/07 09:05:04 [error] 26506#0: *372 open() "/var/www/html/manual/de/mod/mod_status.html" failed (2: No such file or directory), client: 66.249.78.230, server: server1, request: "GET /manual/de/mod/mod_status.html HTTP/1.1", host: "homenursingcare.be"
2015/10/07 14:04:04 [error] 4473#0: *84 open() "/var/www/html/test/ssi/test.html" failed (2: No such file or directory), client: 69.30.213.146, server: server1, request: "GET /test/ssi/test.html HTTP/1.0", host: "filesilver.com"
2015/10/07 14:08:13 [error] 4473#0: *89 open() "/var/www/html/manual/de/mod/mod_filter.html" failed (2: No such file or directory), client: 66.249.78.224, server: server1, request: "GET /manual/de/mod/mod_filter.html HTTP/1.1", host: "homenursingcare.be"
2015/10/07 14:21:50 [error] 4473#0: *96 open() "/var/www/html/test/php/test.html" failed (2: No such file or directory), client: 66.249.74.28, server: server1, request: "GET /test/php/test.html HTTP/1.1", host: "filesilver.com"
2015/10/07 14:51:11 [error] 4473#0: *115 open() "/var/www/html/test/python/test.html" failed (2: No such file or directory), client: 5.9.111.70, server: server1, request: "GET /test/python/test.html HTTP/1.0", host: "filesilver.com"
2015/10/07 14:51:14 [error] 4473#0: *115 open() "/var/www/html/test/ssi/test.shtml" failed (2: No such file or directory), client: 5.9.111.70, server: server1, request: "GET /test/ssi/test.shtml HTTP/1.0", host: "filesilver.com"
2015/10/07 16:46:10 [error] 4474#0: *272 "/var/www/html/HNAP1/index.php" is not found (2: No such file or directory), client: 194.63.140.103, server: server1, request: "GET /HNAP1/ HTTP/1.1", host: "188.165.120.241:443"
2015/10/07 19:11:22 [error] 4474#0: *369 open() "/var/www/html/manual/de/ssl/ssl_compat.html" failed (2: No such file or directory), client: 66.249.79.149, server: server1, request: "GET /manual/de/ssl/ssl_compat.html HTTP/1.1", host: "homenursingcare.be"
2015/10/07 21:42:55 [error] 4474#0: *424 open() "/var/www/html/manual/es/mod/mod_status.html" failed (2: No such file or directory), client: 66.249.78.230, server: server1, request: "GET /manual/es/mod/mod_status.html HTTP/1.1", host: "homenursingcare.be"
2015/10/07 22:58:42 [error] 4474#0: *450 open() "/var/www/html/manual/tr/mod/mpm_common.html" failed (2: No such file or directory), client: 66.249.78.230, server: server1, request: "GET /manual/tr/mod/mpm_common.html HTTP/1.1", host: "homenursingcare.be"
2015/10/08 00:14:29 [error] 4473#0: *484 open() "/var/www/html/manual/ja/platform/index.html" failed (2: No such file or directory), client: 66.249.78.230, server: server1, request: "GET /manual/ja/platform/index.html HTTP/1.1", host: "homenursingcare.be"
2015/10/08 01:10:59 [error] 4473#0: *521 open() "/var/www/html/wp-content/plugins/table-of-contents-plus/screen.min.css" failed (2: No such file or directory), client: 66.249.74.115, server: server1, request: "GET /wp-content/plugins/table-of-contents-plus/screen.min.css?ver=1509 HTTP/1.1", host: "www.toevenstay.com"
2015/10/08 01:11:00 [error] 4473#0: *522 open() "/var/www/html/wp-content/plugins/table-of-contents-plus/front.min.js" failed (2: No such file or directory), client: 66.249.78.68, server: server1, request: "GET /wp-content/plugins/table-of-contents-plus/front.min.js?ver=1509 HTTP/1.1", host: "www.toevenstay.com"
2015/10/08 01:11:01 [error] 4473#0: *523 open() "/var/www/html/wp-content/themes/omaha/style.css" failed (2: No such file or directory), client: 66.249.78.61, server: server1, request: "GET /wp-content/themes/omaha/style.css HTTP/1.1", host: "www.toevenstay.com"
2015/10/08 01:11:01 [error] 4473#0: *524 open() "/var/www/html/wp-content/themes/omaha/css/bootstrap.min.css" failed (2: No such file or directory), client: 66.249.78.75, server: server1, request: "GET /wp-content/themes/omaha/css/bootstrap.min.css HTTP/1.1", host: "www.toevenstay.com"
2015/10/08 01:11:02 [error] 4473#0: *524 open() "/var/www/html/wp-content/themes/omaha/css/font-awesome.min.css" failed (2: No such file or directory), client: 66.249.78.75, server: server1, request: "GET /wp-content/themes/omaha/css/font-awesome.min.css HTTP/1.1", host: "www.toevenstay.com"
2015/10/08 01:30:17 [error] 4473#0: *533 open() "/var/www/html/manual/ko/mod/mod_status.html" failed (2: No such file or directory), client: 66.249.79.142, server: server1, request: "GET /manual/ko/mod/mod_status.html HTTP/1.1", host: "homenursingcare.be"
2015/10/08 04:01:55 [error] 4473#0: *610 open() "/var/www/html/manual/tr/mod/mod_status.html" failed (2: No such file or directory), client: 66.249.78.217, server: server1, request: "GET /manual/tr/mod/mod_status.html HTTP/1.1", host: "homenursingcare.be"
2015/10/08 05:17:38 [error] 4473#0: *632 open() "/var/www/html/manual/fr/mod/mpm_common.html" failed (2: No such file or directory), client: 66.249.78.224, server: server1, request: "GET /manual/fr/mod/mpm_common.html HTTP/1.1", host: "homenursingcare.be"
2015/10/08 06:33:25 [error] 4474#0: *752 open() "/var/www/html/manual/ko/vhosts/details.html" failed (2: No such file or directory), client: 66.249.78.224, server: server1, request: "GET /manual/ko/vhosts/details.html HTTP/1.1", host: "homenursingcare.be"
2015/10/08 07:29:32 [error] 4476#0: *781 "/var/www/html/HNAP1/index.php" is not found (2: No such file or directory), client: 194.63.140.103, server: server1, request: "GET /HNAP1/ HTTP/1.1", host: "188.165.120.241:443"
2015/10/08 07:49:12 [error] 4476#0: *794 open() "/var/www/html/manual/es/vhosts/details.html" failed (2: No such file or directory), client: 66.249.78.217, server: server1, request: "GET /manual/es/vhosts/details.html HTTP/1.1", host: "homenursingcare.be"
2015/10/08 10:20:47 [error] 4476#0: *892 open() "/var/www/html/manual/de/platform/index.html" failed (2: No such file or directory), client: 66.249.75.6, server: server1, request: "GET /manual/de/platform/index.html HTTP/1.1", host: "homenursingcare.be"

**Comment by Alkarex** [comment]
Bonsoir,
Cela montre effectivement des erreurs, mais rien qui concerne FreshRSS...

**Comment by Alkarex** [comment]
N'hésitez pas a réouvrir s'il y a toujours un problème
