### ISSUE TITLE
No embeded videos from youtube?

### ISSUE THREAD

**Issue by NerosTie** [FreshRSS/FreshRSS#997]
This is what I get for a link coming from youtube:

![tmp4](https://cloud.githubusercontent.com/assets/4572452/10459710/1030d98e-71d1-11e5-8fcc-71c1afc94362.png)

It could be nice to launch the video directly in Freshrss or, at least, a preview image.

**Comment by Alkarex** [comment]
Could you please provide an example of address for such a problematic feed?

**Comment by NerosTie** [comment]
Well, every feeds coming from youtube.

example: https://www.youtube.com/feeds/videos.xml?channel_id=UCvQECJukTDE2i6aCoMnS-Vg
(big think)

(I didn't try feeds from vimeo or dailymotion)

**Comment by NerosTie** [comment]
For Vimeo, it's fine:

![tmp6](https://cloud.githubusercontent.com/assets/4572452/10462677/400036fa-71e0-11e5-935d-b9a8a630492a.png)

( https://vimeo.com/channels/staffpicks/videos/rss )

For dailymotion.... I think there is no rss feeds for a channel.

**Comment by marienfressinaud** [comment]
It is not a feed problem, we should support `<media>` tags to have Youtube videos in FRSS.

Duplicate https://github.com/FreshRSS/FreshRSS/issues/944

**Comment by NerosTie** [comment]
With the <media> tags support, it will be the browser's default HTML5 player?  
Why is there an issue with the embeded videos from youtube but it's ok with vimeo?

**Comment by marienfressinaud** [comment]
I was talking about RSS tags, not HTML tags :). The reason is Vimeo embedded their videos in the `<description>` tag while Youtube uses `<media>`. What you see in FreshRSS is only the `<description>`.

**Comment by NerosTie** [comment]
Ha, I understand now! Thank you!

**Comment by kevinpapst** [comment]
Pretty old topic, but nevertheless...
I am watching Youtube videos almost exclusively from my RSS reader. As FreshRSS does not yet support embedding YouTube Videos from channel feeds, I wrote a little extension, that does the job:
https://github.com/kevinpapst/freshrss-youtube

**Comment by NerosTie** [comment]
@kevinpapst It works very well! It's a great improvement for FreshRSS. Thanks! (just an issue: files shouldn't be executable)

**Comment by Alkarex** [comment]
@kevinpapst Nice 👍 Feel free to make a pull request to https://github.com/FreshRSS/Extensions
