### ISSUE TITLE
personal password and  RSS feed password

### ISSUE THREAD

**Issue by ghost** [FreshRSS/FreshRSS#998]
J'ai un pb avec FreshRSS qui me récupère l'identifiant et mot de passe de ma session et qui l'ajoute automatiquement dans la section **Identification** quand j'ajoute un nouveau flux. 
Du coup, pour les nouveaux flux ajoutés, mon identifiant perso est automatiquement envoyé sans que je le désire.

Je pense que le problème vient du navigateur (Iceweasel/Firefox) qui mémorise le mot de passe et l'ajoute dans tous les champs qu'ils trouvent.
Le pb est que je ne peux même pas vérifier s'il y a un mot de passe associé à un flux RSS (ou pas) puisqu'il est systématiquement ajouté. Obligé de passer par la navigation privée ou un autre navigateur pour faire le ménage. 

> Login
> HTTP username [xxxxxxxx] ⓘ Connection allows to access HTTP protected RSS feeds
> HTTP password  [xxxxxxxx]

 [xxxxxxxx] correspondant aux identifiants de l'utilisateur FreshRSS

>  ⓘ Votre version actuelle de FreshRSS est la 1.0.0. 
> page "Subscriptions management" -> https://freshrss/p/i/?c=subscription&id=81

---

My personal login and password is  automatically added in RSS feed **Login**.
The problem seems to be related with Firefox which stores my personal passwords.

**Comment by Alkarex** [comment]
Je pense que ce problème est https://github.com/FreshRSS/FreshRSS/issues/880
Cela a été corrigé dans la version 1.1.2 de FreshRSS.

**Comment by ghost** [comment]
C'est exactement ça. Désolé, j'ai fait une recherche rapide mais pas sur les bons termes.

Je ferme le ticket, pas besoin d'avoir de doublon surtout quand c'est corrigé.

**Comment by marienfressinaud** [comment]
@Alkarex je propose qu'on sorte une nouvelle version stable très rapidement (ça aurait dû être fait mais pas eu le temps). Qui dit nouvelle stable dit nouvelle beta (et tant pis s'il n'y a pas eu de changement depuis la dernière version, au moins on restera raccord sur les numéros de versions). Ce weekend pas le temps mais je peux le faire lundi.

Edit: ça me paraît important vis-à-vis de ce ticket en fait :)

**Comment by Alkarex** [comment]
@marienfressinaud Bonne idée :-)
