### ISSUE TITLE
Mysqld error on each feeds update

### ISSUE THREAD

**Issue by Epy** [FreshRSS/FreshRSS#999]
Hello
I found a repeating error in my logs, it seems to occur on each manual updates (as I didn't made a cron job)

```
oct. 15 10:08:32 user mysqld[3256]: 151015 10:08:32 [Warning] Unsafe statement written to the binary log using statement format since BINLOG_FORMAT = STATEMENT. Statements writing to a table with an auto-increment column after selecting from another table are unsafe because the order in which rows are retrieved determines what (if any) rows will be written. This order cannot be predicted and may differ on master and the slave. Statement: UPDATE `freshrss_Epy_feed` SET cache_nbEntries=(SELECT COUNT(e1.id) FROM `freshrss_Epy_entry` e1 WHERE e1.id_feed=`freshrss_Epy_feed`.id),cache_nbUnreads=(SELECT COUNT(e2.id) FROM `freshrss_Epy_entry` e2 WHERE e2.id_feed=`freshrss_Epy_feed`.id AND e2.is_read=0),lastUpdate='1444896512', error='1' WHERE id='2'
```

[...]

```
oct. 15 10:08:42 user mysqld[3256]: 151015 10:08:42 [Note] Suppressing warnings of type 'Statements writing to a table with an auto-increment column after selecting from another table are unsafe because the order in which rows are r [...]
```

From a fresh install on a dedicated Debian server.
It might be a mysql config error of myself but I don't know

Thanks

**Comment by Alkarex** [comment]
Thanks. What MySQL version is that?

**Comment by Epy** [comment]
`mysql  Ver 15.1 Distrib 10.0.21-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2`
it's MariaDB in fact, I forgot that ^_^

**Comment by Alkarex** [comment]
We seem to have other users with MariaDB without problem (https://github.com/FreshRSS/FreshRSS/issues/1034). I do not know what the problem can be in your case. Would need additional debugging.

**Comment by Epy** [comment]
Hi
I'll try to find time to make more tests

**Comment by Alkarex** [comment]
Documentation:
- http://stackoverflow.com/questions/20925792/mysql-warning-code-1592-unsafe-statement-written-to-the-binary-log-using-stateme
- https://mariadb.com/kb/en/mariadb/unsafe-statements-for-replication/
- https://github.com/owncloud/core/issues/7769#issuecomment-89188909

**Comment by Alkarex** [comment]
Any update on that? Feel free to re-open if still relevant. Now, FreshRSS also supports PostgreSQL, just FYI :-)
